### ISSUE TITLE
Navigation option missing in mobile screens.  

### ISSUE THREAD

**Issue by Aanandgupta** [mozilla/addons-frontend#10019]
### Describe the problem and steps to reproduce it:
When we are switching from desktop screens to mobile screens "Explore" option from the navbar is not visible.

### Anything else we should know?
I am new to open source I would like to work on this issue. 

![for desktop](https://user-images.githubusercontent.com/71023799/105408291-c827ec80-5c54-11eb-9bb7-56dd0b1ddd9c.png)
![for mobile](https://user-images.githubusercontent.com/71023799/105408335-d413ae80-5c54-11eb-9524-59c7ed82fdbc.png)

**Comment by bobsilverberg** [comment]
This is by design and is therefore not something that needs to be fixed.

**Comment by jvillalobos** [comment]
(Adding this comment since I was already typing it when the issue was closed :) )The Explore link just takes you back to the homepage, which has the same effect as tapping on the logo. Adding it back could impact layout, especially in other languages.

**Comment by Aanandgupta** [comment]
> (Adding this comment since I was already typing it when the issue was closed :) )The Explore link just takes you back to the homepage, which has the same effect as tapping on the logo. Adding it back could impact layout, especially in other languages.

Agreed but let's say the user directly lands on the themes page using this https://addons.allizom.org/en-US/firefox/themes/ URL in their mobile phone's browser how will they interact with the home page if they are not knowing about the fact that tapping on the logo takes you to the home page. And if adding back could impact layout in other languages We can add it back in more dropdown or think of any other alternative.
