### ISSUE TITLE
Server errors on AMO homepage on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10016]
### Describe the problem and steps to reproduce it:
1. Create a new Firefox profile (just to make sure there is no caching involved)
2. Open addons.allizom.org

### What happened?
A Server Error page is displayed. Besides the 500 error for the homepage URL, I've also noticed the following error in the browser console: `Caught application error: TypeError: Parameter 'url' must be a string, not object`

### What did you expect to happen?
The homepage is loaded successfully

### Anything else we should know?
- if the issue does not reproduce by following the steps above (although I've been able to repeatedly reproduce it with this method) you can try reloading the homepage several times by clicking on the logo 
- initially, I thought this issue was connected to the server errors coming from the sponsored shelf API, but now with the shelf gone the issue persists 
- I only reproduced the error on stage and no other pages besides the homepage seem to be affected
- this issue is rather high priority because it causes many of our release tests to fail 

![image_2021-01-20_123433](https://user-images.githubusercontent.com/31961530/105162900-dde5c680-5b1b-11eb-98d3-e99be03d2f0b.png)

**Comment by bobsilverberg** [comment]
The problem here is that the `homepage` property returned for `external` for the primary hero shelf is a localized, and outgoingified, URL, but the code was assuming it would be a string. It turns out that the `name` is also localized, so the fix should address that too.

**Comment by AlexandraMoga** [comment]
I've enabled an [external primary hero](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/378/change/?_changelist_filters=p%3D0) on -dev and loaded the homepage several times afterwards. The primary hero is displayed and there are no errors in the console.

This issue is verified fixed on -dev.
