### ISSUE TITLE
Blocked add-on name is incorrectly shown as [object Object]

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10014]
Regression from https://github.com/mozilla/addons-frontend/issues/6422 

Blocked add-on pages, like https://addons.mozilla.org/en-US/firefox/blocked-addon/%7Ba73cc3ed-9261-4571-94f6-3679930f0332%7D/3.0/, are displaying `[object Object]` as the add-on name instead of, well, the add-on name.

This is because the `addon_name` field in the v5 API is following the same behavior as other translated fields in v5 API and returns an object instead of a string.

**Comment by bobsilverberg** [comment]
Wow, I'm surprised we missed that. I'll fix it tomorrow.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Fixed on AMO dev - FF84(Win10). 

![fixed prod bug](https://user-images.githubusercontent.com/33448286/105509255-ff8aad80-5cd5-11eb-8485-4a064e188f46.png)
