### ISSUE TITLE
Remove code related to the sponsored shelf endpoint

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10031]
This is a follow-up to https://github.com/mozilla/addons-server/issues/16390, which removed the sponsored shelf endpoint. We should remove any code we have which supports that API.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
Homepage dev and stage don't seem to be affected. Primary, secondary hero and the shelves are displayed.
Sponsored GA events are no longer present in the Console.
/api/v5/shelves/sponsored/ is not present in the Network.
