### ISSUE TITLE
Remove ability to filter by Operating System in the search results 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10047]
All WebExtensions should be compatible with all platforms for the application they support (Firefox or Firefox for Android). Let's remove the ability to filter by Operating System in the search results (It's currently displayed in the sidebar, and also passed down to the API if the parameter is present in the URL).

**Comment by smayer97** [comment]
Not sure what the intention is and what benefit it would have but please do not do this if this prevents a user to pull up addons when on a different platform.... e.g. if on Windows, cannot see macOS addons... There are many times when doing research on add-ons that one can be on a different platform... 

Often on Android, or Windows, or macOS researching...

**Comment by diox** [comment]
See the first sentence. There is no such thing as add-ons for Windows or Linux or macOS only - except as a bug for some old ones that haven't been migrated yet (we [removed the possibility to upload add-ons specific to a particular OS over 2 years ago](https://github.com/mozilla/addons-server/issues/8752)). We currently filter by default and let you change the filter, but it doesn't make any sense, fixing that issue will remove the filtering completely so that we'll always show all add-ons instead.

You'll still be able to to go to https://addons.mozilla.org/en-US/android/search/ to search for Android-specific add-ons from any OS, and use https://addons.mozilla.org/en-US/firefox/ from Android (that's a different mechanism at play - application compatibility, which we are very much keeping)

**Comment by iamvedant** [comment]
I would like to work on this. Can you please help me out setting up the code in my local machine. I am trying to set it up but some error is popping up and I am not able to start the dev server

**Comment by diox** [comment]
This is already assigned (to me), already has a pull request opened, and not marked as a good first bug/contributions welcome issue.

**Comment by AlexandraMoga** [comment]
The 'Operating System'  filter option is no longer present on -dev:

![image](https://user-images.githubusercontent.com/31961530/107219327-96b36d00-6a19-11eb-8cae-3d464da6869c.png)

Manually entering a `?platform=windows/mac/linux` in the URL will result in the parameter being stripped and ignored.

Searching and filtering is working as expected. 

This issue is verified fixe on -dev.
