### ISSUE TITLE
chrome_settings_overrides

### ISSUE THREAD

**Issue by richie3355** [mozilla/addons-frontend#10043]
Lets assume you name your search provider as WebSearch1 and then rename as WebSearch2 in the next update of the addon the search provider stops working. Is this an expected behaviour?

After debugging the ff code found that in SearchServices.jsm searches for the searcheengine based on the key and any update on engine name does not change the key and only the _name inside values

**Comment by jvillalobos** [comment]
This sounds like (possibly) a Firefox bug. [Please file it here](https://bugzilla.mozilla.org/enter_bug.cgi?product=WebExtensions).
