### ISSUE TITLE
Record Web Vitals stats & progress over time

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10041]
We want to keep an eye on our [Web Vitals](https://web.dev/vitals/) for SEO and general perf health, so we need to find the right tool for the job. Ideally this would be fed into statsd so that we aggregate the data with other graphs in Grafana.

**Comment by willdurand** [comment]
We could probably use the `web-vitals` js lib: https://web.dev/vitals/#measure-core-web-vitals-in-javascript. Maybe we could have a server endpoint that would receive the data from `web-vitals` and push it to statsd?

**Comment by willdurand** [comment]
looks like we can also use GA to receive the web vitals stats: https://github.com/GoogleChrome/web-vitals/#send-the-results-to-google-analytics. I feel like this would be a lot simpler.

**Comment by willdurand** [comment]
> looks like we can also use GA to receive the web vitals stats: [GoogleChrome/web-vitals#send-the-results-to-google-analytics](https://github.com/GoogleChrome/web-vitals/#send-the-results-to-google-analytics). I feel like this would be a lot simpler.

I am going to try to use the GA approach since there is a nice dashboard too: https://web-vitals-report.web.app/.

**Comment by willdurand** [comment]
Oh noes.. most APIs used by the web-vitals lib are only available in Chromium-based browsers:

> Browser Support
> 
> The web-vitals code has been tested and will run without error in all major browsers as well as Internet Explorer back to version 9. However, some of the APIs required to capture these metrics are currently only available in Chromium-based browsers (e.g. Chrome, Edge, Opera, Samsung Internet).
> 
> Browser support for each function is as follows:
> 
>     getCLS(): Chromium,
>     getFCP(): Chromium, Safari Technology Preview
>     getFID(): Chromium, Firefox, Safari, Internet Explorer (with the polyfill)
>     getLCP(): Chromium
>     getTTFB(): Chromium, Firefox, Safari, Internet Explorer

The most interesting metrics are:

- Largest Contentful Paint (LCP): measures loading performance. To provide a good user experience, LCP should occur within 2.5 seconds of when the page first starts loading.
- First Input Delay (FID): measures interactivity. To provide a good user experience, pages should have a FID of less than 100 milliseconds.
- Cumulative Layout Shift (CLS): measures visual stability. To provide a good user experience, pages should maintain a CLS of less than 0.1.

As we can see, we'd only get `FID` on Firefox.

Chrome represents <7% of our traffic according to GA so I am not sure we can actually leverage the `web-vitals` library in a meaningful way :( I am going to take a look at which APIs are used to see if we have bugs filed.

**Comment by willdurand** [comment]
So I think CLS requires something called [`layout-shift`](https://web.dev/cls/#measure-cls-in-javascript) and there is a bug for that: https://bugzilla.mozilla.org/show_bug.cgi?id=1651528

For LCP, we need [`largest-contentful-paint`](https://web.dev/lcp/#measure-lcp-in-javascript).

**Comment by AlexandraMoga** [comment]
@willdurand is there any QA needed for this issue?

**Comment by willdurand** [comment]
@AlexandraMoga you should see new GA logs about "web vitals" in the devtools console. It's best to use Google Chrome for that, though. We only send data when pages are first loaded (so reload the pages you navigate to).

**Comment by AlexandraMoga** [comment]
@willdurand I can see the following events in the devtools console:

After reloading a page:
```
[GA: ON] trackingSendWebVitals is enabled undefined
```
After clicking randomly or performing some action on the page I've opened:
```
[GA: ON] sendWebVitalStats: {name: "CLS", delta: 0.019371690299618088, id: "v1-1613054599645-4673670748539"}
[GA: ON] sendWebVitalStats: {name: "LCP", delta: 1979.01, id: "v1-1613054599646-2002495213567"}
```
