### ISSUE TITLE
Increasing amount of 500 errors after 2/4 release

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#10059]
### Describe the problem and steps to reproduce it:

We've noticed increased amount of 500 errors after 2/4 release (as shown by the green line in the below screen shot).

<img width="719" alt="Screen Shot 2021-02-04 at 10 22 45 PM" src="https://user-images.githubusercontent.com/2209111/106997417-b3108a80-6737-11eb-994d-f5730b57a51e.png">

We don't have an excessive amount of 500 at this point, but the difference from a day before is noticable.

So far, the paths that return 500 include the following,

```
/af/about
/af/review_guide
/api/v3/addons/%7B359f86e7-3c99-4f55-bb1c-afff6317ea95%7D/versions/2.6.4051.387/uploads/a6b15db94d624861852dfc30499a0896/
/ar/review_guide
/az/about
/az/review_guide
/de/about
/dsb/review_guide
/en-GB/about
/en-US/about
/en-US/about/
/en-US/firefox/user/%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%A2/
/en-US/review_guide
/fi/about
/fi/review_guide
/hr/review_guide
/mn/about
/mn/review_guide
/ms/review_guide
/pt-PT/about
/pt-PT/review_guide
/ru/review_guide
/sq/review_guide
/sv-SE/about
/tr/about
/zh-CN/about
```

### What happened?
We released a new version today and then started to see more 500 than the previous day.

### What did you expect to happen?
We'd like to know if the increased amount of 500 is due to today's release or not, and fix the underlying issue accordingly.

### Anything else we should know?
n/a

**Comment by wagnerand** [comment]
I believe this is a frontend issue, transferring...

**Comment by willdurand** [comment]
I think we should cherry-pick the patch and redeploy addons-frontend once the issue has been verified.

**Comment by wagnerand** [comment]
Verified on -dev: https://addons-dev.allizom.org/en-US/review_guide and https://addons-dev.allizom.org/en-US/about work again.

Not sure if https://addons.allizom.org/en-US/firefox/user/%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%A2/ warrants a follow-up . What's weird is that this seems to happen at a low level (nginx?), and does not appear in sentry, as far as I can see. /cc @diox

**Comment by willdurand** [comment]
> Not sure if https://addons.allizom.org/en-US/firefox/user/%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%A2/ warrants a follow-up . What's weird is that this seems to happen at a low level (nginx?), and does not appear in sentry, as far as I can see. 

This is a different issue I believe and I am almost sure we already took a look in the past.

**Comment by willdurand** [comment]
@AlexandraMoga could you verify this issue on -dev please?

**Comment by AlexandraMoga** [comment]
@willdurand the /about and /review_quide pages are no longer triggering a server error, so this part is verified fixed.

The error with user profile page is a different issue as far as I understand.

**Comment by willdurand** [comment]
> The error with user profile page is a different issue as far as I understand.

Yes, the actual error is:

```
"URIError: Pathname "/en-US/firefox/user/%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%A2/" could not be decoded. This is likely caused by an invalid percent-encoding."
```

I am not sure what we can do about it but I'll file an issue for that. This isn't new, though.

**Comment by AlexandraMoga** [comment]
This issue has been verified fixed on all servers.
