### ISSUE TITLE
Explore option missing from UI for mobile devices.

### ISSUE THREAD

**Issue by Aanandgupta** [mozilla/addons-frontend#10055]
### Describe the problem and steps to reproduce 
If the user directly lands on the themes page using this https://addons.allizom.org/en-US/firefox/themes/ URL in their mobile phone's browser they can't interact with the home page as explore option is missing and if they are not knowing about the fact that tapping on the logo takes you to the home page.
 And if adding back could impact layout in other languages We can add it back in "more" dropdown or think of any other alternative.WE can also add on tooltip text "home" when  we hover over logo.

![Screenshot (125)](https://user-images.githubusercontent.com/71023799/106784942-e50be900-6672-11eb-87fc-a2a01514e3e0.png)

**Comment by willdurand** [comment]
I don't think we want to change that for now.
