### ISSUE TITLE
Codeofconduct redirects to 404 page

### ISSUE THREAD

**Issue by Aanandgupta** [mozilla/addons-frontend#10052]
### Describe the problem and steps to reproduce it:
In README.md  when we click on codeofconduct we are been redirected to 404 page

### What did you expect to happen?
We should have been redirected to a page which describes codeofconduct

![Screenshot (123)](https://user-images.githubusercontent.com/71023799/106773934-9dcc2b00-6667-11eb-8ad8-3f8d8c1c1093.png)

on clicking on code of conduct it redirects us to 404 err page

**Comment by championshuttler** [comment]
Apparently it should be closed , @willdurand can you take care of this thanks
