### ISSUE TITLE
Make category pages indexable

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10069]
We currently [forbid robots from indexing /{lang}/{app}/search/](https://addons.mozilla.org/robots.txt). We want to keep that, but at the same time, we're currently re-use the search pages for category pages, and we'd like _those_ to be indexed.

Easiest way to start fixing this is probably going to resolve around exposing "true" category pages under a specific URL, leaving the functionality and underlying templates/API calls the same. Eventually we may want to completely customize the category pages to make them look different, add specific content etc but that will be different follow-up issue(s).

Note: we also forbid indexing collections, but explicitly allow the Mozilla ones by id and username, so all the "special" collections are currently indexed already.

**Comment by willdurand** [comment]
I am wondering: what's the rationale for indexing category pages (and actually create new category pages in the first place)? There is something called the "crawl budget", which we should keep in mind. Last time we did a project around SEO, @rraue said that it was important.

**Comment by jvillalobos** [comment]
This issue comes directly from Raphael. It's currently not possible for a crawler to find all listing pages using only our internal links (given that search pages are excluded).

**Comment by rraue** [comment]
I am not recommending just indexing all category pages without a second thought, but to use this with a content approach. A good example is the keyword "adblocker" where the category page would be the best fit to rank, as it gives a user the overview of all/best adblockers for Firefox, but currently only the single adblocker pages have a chance to rank for this. 

If we approach category pages in that way, I am sure a lot of category pages would give users a real value, if they are sorted and/or curated to give an overview but also a "recommendation"

**Comment by diox** [comment]
We already have curated lists for specific topics like "Ad Blockers" and those technically collections, not categories. They have a short description and contain a limited set of add-ons we recommend on a particular topic. *Those* pages are already indexed - they are not linked much though: currently on the homepage we display https://addons.mozilla.org/en-US/firefox/collections/4757633/privacy-matters/ and https://addons.mozilla.org/en-US/firefox/collections/4757633/password-managers/, that's it.

**Comment by jvillalobos** [comment]
@rraue can you clarify? I thought the value of indexing category pages was to provide a way for crawlers to find any listing page by following links on the site. Currently, only Recommended extensions can be found that way, if you start on the homepage.

**Comment by rraue** [comment]
Exactly. Right now only recommended extensions can be directly crawled. But if we flood the crawler with all categories, it will be difficult for any crawler to get the job done as well, so we should index all categories that matter (having more than x extensions within the category) and build a category index page, so its easy to get there for crawlers, as they cant use search.

Thats what I mean with a content approach. No need to verify all categories, but having a useful system which categories should be displayed on the index page and therefor to crawlers makes sense to prevent "category" pages that have one extension on them or in general are pretty useless.

And regarding the adblocker: privacy matter and adblocker are completely different intends to search for for a search engine and we definetely should have a page for adblockers. We could solve that problem by a lot more recommended lists, as that would give the crawler what it needs, so my recommendation with categories is not better, but I thought more feasable and easier to do, but if you want to get a full content direction, that's fine as well. But then we need a big keyword research to find opportunities and get a more search user centered perspective. Indexing the "good" categories would solve this hopefully as well.

**Comment by jvillalobos** [comment]
Here's how a crawler can find most listing pages, starting from the homepage:

1) Homepage
2) Extensions ([/extensions](https://addons.mozilla.org/en-US/firefox/extensions/)) or themes ([/themes](https://addons.mozilla.org/en-US/firefox/themes/)) landing page
3) Category pages
4) Listing pages

The landing pages in (2) have a list of all categories. The proposal here is to change the URL for category pages so they are indexed and listing pages can be found.

Pretty much all categories have hundreds if not thousands of add-ons in them. Extension developers can pick up to 2 categories for their extensions, so there is some duplication there.

As for the quality and quantity of our categories, it's something we've been meaning to refactor for quite some time, but hasn't been a top priority. It's something we could potentially add as a followup if the high-priority work bears fruit.

**Comment by jvillalobos** [comment]
We discussed this offline and decided that:
1) There's value in indexing category pages as specified in this issue.
2) We'll look into more dynamic and scalable auto-curated content as a followup, probably bringing back the old tags feature in some capacity. We'll file separate issues when that comes up.

**Comment by bobsilverberg** [comment]
@jvillalobos Now that we're making this an actual Category page, as opposed to a Search Results page, we can give it a custom title. The title is currently just "Search results". I was thinking "{CategoryName} extensions|themes". What do you think?

Also, we need to retrieve the category name via an API call, so there is a point at which we don't know the category name, although that all happens on the server, so a user should never see the page without a category name, but we need to account for this possibility in the code. If we don't have a category name, can we use just "Extensions|Themes", or can you think of something better for that case?

**Comment by willdurand** [comment]
> @jvillalobos Now that we're making this an actual Category page, as opposed to a Search Results page, we can give it a custom title. The title is currently just "Search results". I was thinking "{CategoryName} extensions|themes". What do you think?

Are you talking about a custom _HTML_ title?

**Comment by bobsilverberg** [comment]
> > @jvillalobos Now that we're making this an actual Category page, as opposed to a Search Results page, we can give it a custom title. The title is currently just "Search results". I was thinking "{CategoryName} extensions|themes". What do you think?
> 
> Are you talking about a custom _HTML_ title?

Yes

**Comment by jvillalobos** [comment]
I think "Extensions|Themes in {CategoryName}", which is close to the title on the page.

**Comment by AlexandraMoga** [comment]
I've verified the Extensions and Themes (from Themes landing page and from the homepage shelf) on stage and these are my results:
- category pages have a dedicated URL now, for example https://addons.allizom.org/en-US/firefox/extensions/category/bookmarks/ for extensions and https://addons.allizom.org/en-US/firefox/themes/category/holiday/ for themes
- the default sorting remained as before, namely recommended results sorted by users are displayed first in the list, followed by non-recommended results sorted by users
- results can be sorted differently by using the search filter, noting that the `recommended` sort will be preserved for all sort types
- category page routing seems to be working too; for example, if I access https://addons.allizom.org/extensions/category/feeds-news-blogging/, the app will redirect to https://addons.allizom.org/en-US/firefox/extensions/category/feeds-news-blogging/ (where `en-US` is my browser locale)
- searching within the same category results is no longer possible but I see that this change was approved by product in https://github.com/mozilla/addons-frontend/pull/10146#issuecomment-797639575

I'm marking this issue as verified fixed on stage.
