### ISSUE TITLE
No result for Android-specific extensions on the "Edit collection" page

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons-frontend#10064]
### Describe the problem and steps to reproduce it:
* Open `https://addons.mozilla.org/collections` on the desktop version of Firefox. It redirects to a URL containing `/firefox/`.
* Create a new collection.
* Search for `Video Background Play Fix`, an Android-specific extension.

### What happened?
No results. It only shows up if you manually change the URL to `https://addons.mozilla.org/android/collections`

### What did you expect to happen?
The `Find an add-on to include in this collection` search bar should include all extensions regardless of whether you're using a desktop or mobile browser at the moment.

**Comment by jvillalobos** [comment]
This is a duplicate of https://github.com/mozilla/addons/issues/1252. Not closing this yet in case there are ideas on how to fix this easily. Otherwise it'll need to wait until we invest more time on Android compatibility.
