### ISSUE TITLE
Add Silesian lang to the list of supported languages by AMO

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10067]
In https://github.com/mozilla/addons-frontend/issues/10068, a new (unfiltered) language has been added. It is available in Pontoon so we might want to enable this new lang for AMO too.

@peiying2 WDYT?

**Comment by peiying2** [comment]
> In #10068, a new (unfiltered) language has been added. It is available in Pontoon so we might want to enable this new lang for AMO too.
> 
> @peiying2 WDYT?

Please advise the communities to request  through Pontoon: https://pontoon.mozilla.org/projects/. Try to be realistic and one project at a time.
