### ISSUE TITLE
URIError when path is invalid

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10061]
When an URL path is invalid, we get the following error and we return a minimal 500 page (from Express, I guess):

```
"URIError: Pathname "/en-US/firefox/user/%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%A2/" could not be decoded. This is likely caused by an invalid percent-encoding."
```

Not sure what we can about it, though.

**Comment by diox** [comment]
Traceback from other issue:
```
URIError: Pathname "/en-US/firefox/tag/%abc/" could not be decoded. This is likely caused by an invalid percent-encoding.
    at createLocation (/srv/node/node_modules/history/cjs/history.js:110:13)
    at /srv/node/node_modules/history/cjs/history.js:835:40
    at Array.map (<anonymous>)
    at createMemoryHistory (/srv/node/node_modules/history/cjs/history.js:834:32)
    at _createHistory (/srv/code/src/amo/server/base.js:50:14)
    at /srv/code/src/amo/server/base.js:270:23
    at Layer.handle [as handle_request] (/srv/node/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/srv/node/node_modules/express/lib/router/index.js:317:13)
    at /srv/node/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/srv/node/node_modules/express/lib/router/index.js:335:12)
```

**Comment by bqbn** [comment]
Can we raise the priority of this since we noticed more errors of this in production?

**Comment by bobsilverberg** [comment]
@willdurand I've been looking into this, and we can wrap the call to `_createHistory` at https://github.com/mozilla/addons-frontend/blob/master/src/amo/server/base.js#L257 in a `try`, but I'm not sure what to do in the `catch`. I tried returning `showErrorPage`, with a hack to make `_createHistory` return an empty object, and setting `status` to `404`, which does cause the request to return a `404`, but just displays a blank page. I'm not sure what we can do in the `catch` to make the site show our standard `404` page. Do you have any suggestions?

**Comment by willdurand** [comment]
> @willdurand I've been looking into this, and we can wrap the call to `_createHistory` at [`master`/src/amo/server/base.js#L257](https://github.com/mozilla/addons-frontend/blob/master/src/amo/server/base.js#L257) in a `try`, but I'm not sure what to do in the `catch`. I tried returning `showErrorPage`, with a hack to make `_createHistory` return an empty object, and setting `status` to `404`, which does cause the request to return a `404`, but just displays a blank page.

Yeah, annoyingly we cannot simply extend the first `try` block` to add the following code into it: https://github.com/mozilla/addons-frontend/blob/193656da70a5922740024db944bd432b03487917/src/amo/server/base.js#L257-L268

That's because the error handler registered next calls `showErrorPage()`, which calls `_createHistory()`.

>  I'm not sure what we can do in the `catch` to make the site show our standard `404` page. Do you have any suggestions?

I don't think we can show our standard 404 page because the error occurs too early. Well, we _could_ fake the URL by setting `req.url` to `/en-US/firefox/404/` but that does not sound too good: (1) the locale and app would likely be hardcoded because we cannot parse the original URL. I think we can return a minimal 404 page instead.

So, I think you're approach is fine. We should wrap the first call to `_createHistory()` in a `try` and then return a minimal 404 (given that's what ops wants): https://github.com/mozilla/addons-frontend/blob/193656da70a5922740024db944bd432b03487917/src/amo/server/base.js#L137

The page content should probably contain the error, so we could do something like this I guess:

```js
let history;

try {
  history = _createHistory({ req });
} catch (URIError err) {
  // When we catch a URIError, there is nothing we can do because the URL in the request
  // isn't valid.
  return res.status(404).send(`<!DOCTYPE html>\nOh noes, we could not parse the request URL: ${error}`).end(); 
}
```

**Comment by bobsilverberg** [comment]
Thanks @willdurand. That code above is pretty much what I was playing around with. I suppose, if we want, instead of just the string with the error, we could send enough HTML to generate a nicer looking 404 page, but it would require a lot of code in this module to define it. You think it's ok to just present an essentially blank page with a line of text explaining an error occurred?

**Comment by willdurand** [comment]
>  You think it's ok to just present an essentially blank page with a line of text explaining an error occurred?

I'd think so? That would be better than a 500 with "Internal Server Error" I suppose.

**Comment by bobsilverberg** [comment]
> > You think it's ok to just present an essentially blank page with a line of text explaining an error occurred?
> 
> I'd think so? That would be better than a 500 with "Internal Server Error" I suppose.

It's definitely better than that, but I'm just wondering if we're taking the time to present something else to the user, if we shouldn't make it a bit nicer. I suppose this is an error that a user really never should see, unless they have been monkeying around with the URL themselves, so it's probably fine. Let's do it for now.

**Comment by willdurand** [comment]
I agree, and we can make it better later if needed. Make it pretty upfront seems like a lot of effort.

**Comment by bobsilverberg** [comment]
@willdurand In the tests for `server/base.js` we have a couple of tests for the overall error handler and they are relying on `_createHistory` to throw a 500, but now we are catching that and doing something else. I guess we need a test specific to `_createHistory` throwing an error for the new logic, and then we'll need to have a different way of emulating an error in the test. At first glance it looks like we could inject a mock for `langToLocale` or `makeI18n` and use that to generate the error instead. Does that seem right to you?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Wherever I tried to insert into a frontend URL `%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%A2/` I get now a 404 with 
`We're sorry, we were unable to parse the request URL: URIError: Pathname "/en-US/firefox/%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%C3%AF%C2%BF%C2%BD%A2//extensions/" could not be decoded. This is likely caused by an invalid percent-encoding.`

This is not happening right now on AMO stage - where I get a 500 server error instead.
