### ISSUE TITLE
Fetch grouped ratings while fetching add-on detail

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10074]
This is a spin off from https://github.com/mozilla/addons-frontend/issues/10038.

Now that https://github.com/mozilla/addons-server/issues/16459 has landed, we can retrieve the grouped ratings at the same time as the add-on detail, so we should adjust our code to do that, and eliminate the extra API call.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and these are my results:
- total ratings count and the breakdown by score are correctly displayed on the add-on detail page
- the Filter by score option from All reviews page is working as expected
- the `/detail/` API call includes the `show_grouped_ratings=true` parameter and there is no longer a separate call to the `/ratings/` API to retrieve grouped ratings
