### ISSUE TITLE
Allow target locales with 3 parts (e.g., `oc-FR-gascon`)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10071]
If a langpack has a `target_locale` like `oc-FR-gascon` (3 parts) as opposed to 2 parts (`fa-IR`) or even 1 part (`fa`), we don't list it in the language tools page. We should, though.

**Comment by willdurand** [comment]
cc @jvillalobos this is the issue I mentioned on Matrix

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/107493955-de133800-6b96-11eb-9f4b-1d7c800c4201.png)

The dictionaries and language packs for single and two-parts `target_locales` are still being displayed on the language-tools page.
