### ISSUE TITLE
Enable web-vitals collection in all envs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10070]
We added web vitals collection in https://github.com/mozilla/addons-frontend/issues/10041, let's enable the collection in all envs once we have validated that it collects useful data in -dev.

**Comment by AlexandraMoga** [comment]
WebVitals are sent on stage as well:

![image](https://user-images.githubusercontent.com/31961530/108217476-500df300-713c-11eb-8d1a-daaef357fedd.png)
