### ISSUE TITLE
Investigate removing preload/prefetch for About and ReviewGuide resources

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10085]
We currently add these to every page:
```
<link as="style" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/ReviewGuide-6b9bcda93c71841d23cc.css" rel="preload">
<link as="style" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/ReviewGuide-6b9bcda93c71841d23cc.css" rel="prefetch">
<link as="style" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/About-6b9bcda93c71841d23cc.css" rel="preload">
<link as="style" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/About-6b9bcda93c71841d23cc.css" rel="prefetch">
<link as="script" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/About-ef2cd78be4cf0c608d5e.js" rel="preload">
<link as="script" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/About-ef2cd78be4cf0c608d5e.js" rel="prefetch">
<link as="script" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/ReviewGuide-5360b8cc124f842e8fbd.js" rel="preload">
<link as="script" data-parent-chunk="amo" href="https://addons-amo.cdn.mozilla.net/ReviewGuide-5360b8cc124f842e8fbd.js" rel="prefetch">
```

This is causing those 4 js/css bundles to be fetched super early. It doesn't seem to block anything, but it does compete with other resources for bandwidth & parallel connections.

Is it really useful ? I think we could live with a slightly degraded transition when navigating to those pages (the links only appear in the footer anyway), if that helps performance of the rest of the site.

**Comment by willdurand** [comment]
To give some more context, we added `preload` in addition to `prefetch` because we need to configure CSP with `prefetch-src` in order to use `prefetch` but FF didn't support it back then. I don't know if that has changed but we should not use `preload` because this feature is about making sure that the resources are loaded early **for the current page**, which is why they are loaded first (after the main HTML page).

We use both to avoid a flash when navigating to those pages but I agree it's probably acceptable.

**Comment by diox** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/prefetch-src doesn't seem good regarding browser support... so I'd lean towards removing both.

**Comment by willdurand** [comment]
Yep, I tend to agree.

**Comment by AlexandraMoga** [comment]
The https://addons.allizom.org/en-US/review_guide and https://addons.allizom.org/en-US/about are loaded (reloaded) correctly and I didn't notice loading issues with other pages either.

I'm marking this issue as verified fixed on stage.
