### ISSUE TITLE
Investigate homepage theme previews optimizations

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10095]
See also the issue about [detail page previews optimizations](https://github.com/mozilla/addons-frontend/issues/10094)

On the homepage, we only display theme previews (excluding the hero specific image which isn't an add-on preview). There are a couple things we could consider doing:
- Load a (smaller) thumbnail ? We load a full 720x92 image that is displayed at 375x47 (approximately). Like on the detail page, it looks good on fancy retina displays, but is this necessary ? Note that in this case, this isn't even a thumbnail: it's directly one of the previews.
- On the same note, some of these previews can be quite large in file size (100 KB or more sometimes - which adds up, since we typically display 6 themes on the homepage, and 3 of them are likely going to end up in the first contentful paint). Maybe, if we were to switch to a thumbnail instead, we could consider generating them with a 8 bit palette, or a different format, to reduce file size.

**Comment by willdurand** [comment]
It might be a good opportunity to look into `srcset`: https://github.com/mozilla/addons-frontend/issues/1519

**Comment by eviljeff** [comment]
fwiw ,the api returns thumbnails of previews for extensions and themes.  In the case of themes, a 473x64 thumb (I can't remember the size reasoning - might have been because we displayed them at that size at the time; might be arbitrary).   

Using the thumbnail should give a ~50% file size saving alone.

**Comment by willdurand** [comment]
We probably want to support retina screens.

**Comment by eviljeff** [comment]
> We probably want to support retina screens.

If we can use srcset or otherwise to only serve the double size files to retina display owners, sure.

**Comment by diox** [comment]
Do we really need fancy retina images for such basic & small thumbnails though ? I'm curious if the difference would really be that noticeable. I agree looking at `srcset` or different formats could be a solution too, but maybe we can just use the thumbnail and we wouldn't see a difference in quality even on fancy screens.

**Comment by eviljeff** [comment]
/agree.  Our support for retina is pretty inconsistent anyway - in most places we just use the literal image size and if we do have a larger one it's more accident than design.  IMO, lets use the correct size now (or the thumbnail at least) and then actively add support (with srcset, etc, and api changes to serve multiple sizes rather than just a full and thumb) as a follow-up.

**Comment by willdurand** [comment]
I'll double check but even small images that are not optimized for retina displays look very ugly usually.

**Comment by diox** [comment]
We discussed this during stand-up, and we need some data. So, we should do a simple experiment with the current homepage: see how much we'd save if we were to use the thumbnails, and see what the homepage would look like (between all of us we have a good assortment of monitors so it'll be interesting to see if we'd notice the difference)

**Comment by eviljeff** [comment]
#10125 for screenshots of the change (looks fine to me on my laptop)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Looking in comparison the same themes on dev and then stage on homepage:
- size has been reduced from 55.6KB to 33.71 for the [Moon Cat](https://addons-dev.allizom.org/en-US/firefox/addon/the-moon-cat-recommended/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured)
- the version previews dimensions are 501px × 64px from 720px × 92px
- visually I don't see a change of quality - I have a desktop with 2 monitors

Another dev/stage comparison right now for [this ](https://addons-dev.allizom.org/en-US/firefox/addon/theme-for-reelease/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured)theme:
![dev versus stage](https://user-images.githubusercontent.com/33448286/109520399-de776280-7ab4-11eb-872b-fc7f6f128a87.png)
