### ISSUE TITLE
Investigate detail page previews optimizations

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10094]
We spend a significant time loading preview images when loading a detail page (https://www.webpagetest.org/result/210212_DiDG_22aa7b4334f8b6993f9a754cff680fbb/1/details/). Some ideas to explore:
- Lazy loading ? Notably, previews from detail page are all loaded early even though some are behind scroll
- Smaller thumbnails ? We load a 640x480 thumbnail that is displayed at 320x240. It looks good on fancy retina displays, but is this necessary ?
- More aggressive image optimization techniques or different format (WebP?)

**Comment by diox** [comment]
Regarding lazy loading, all it would take would be to add some `loading=lazy` to the preview images and see if they are actually loaded lazily or not. Ideally we wouldn't load more than the first 3 or 4 previews initially but maybe the scroll size isn't large enough that using `loading=lazy` would make a difference.

**Comment by willdurand** [comment]
> so would lead to a lower LCP

Would you have an idea of how much that would lower LCP?

**Comment by eviljeff** [comment]
> > so would lead to a lower LCP
> 
> Would you have an idea of how much that would lower LCP?

I was speaking theoretically.  But from using Google's lighthouse tool, 0.2s - I found it very difficult to get accurate numbers locally though (YMMV)

**Comment by diox** [comment]
I would imagine it can get wildly different depending on the page, too - some previews are much larger than others currently. Still, a potential 200ms gain on LCP is worth doing if there are no adverse effects.

**Comment by eviljeff** [comment]
fwiw I was testing with `addon/video-downloadhelper/` on addons-dev - it has more than 3 screenshots.

**Comment by eviljeff** [comment]
As for thumbnail dimensions, we have a similar mismatch to theme previews displayed in shelves - the css fixes the height for the Thumbnail at 200px (`.ScreenShots-image { height: 200px}` via `$image-height`) but addons-server renders the thumbnail at up to 640x480 - i.e. even taking into account retina displays the image is too big (see mozilla/addons-server#9487 & mozilla/addons-server#10069 - increasing from 200h to 240h was a deliberate decision, but I don't see any link to a frontend issue to make the change here).

For a random png thumbnail:
- 480h: 223k
- 400h: 209k 
- 200h: 61k
(note: I just used a standard save in an image tool - the 400h and 200h numbers may be improved by the pngcrush we routinely do in addons-server)

saving the 400h png as 400h jpeg with default (probably 80) compression: 56k. 

All of these numbers are very dependant on the original source material, obviously.

**Comment by diox** [comment]
IMHO we should add `loading=lazy` and use similar logic you implemented for the themes preview: ensure frontend is always using the thumbnail for, well, the thumbnail (and full size image for when user clicks on it). Then play with format, size, quality in addons-server in a separate issue.

**Comment by eviljeff** [comment]
assuming we don't plan to increase the thumbnail size to 240px any time soon then there's only `loading=lazy` to add - thumbnails are already correctly loaded vs. full size.

**Comment by eviljeff** [comment]
filed addons-server#16717 for server-side work

**Comment by ioanarusiczki** [comment]
@eviljeff 
When the detail page loads for an addon with screenshot viewer images:

the loading-lazy attribute is present for all the uploaded images:

![loading lazy](https://user-images.githubusercontent.com/33448286/110945747-c0c4bb80-8346-11eb-9add-61b8303f0f85.png)

In the Network, I can see `lazy-img` as the Initiator for the images displayed (if 6 are visible from 8 without scrolling to the right then there's 6 requests with lazy-img):

![Network loading lazy](https://user-images.githubusercontent.com/33448286/110945850-e05be400-8346-11eb-9cbe-8ca5b72a733b.png)

This is the example from my screenshots on AMO dev https://addons-dev.allizom.org/en-US/firefox/addon/not-promoted/

Verified on AMO dev - FF86(Win10).
