### ISSUE TITLE
Unexpected behaviour  for arabic language

### ISSUE THREAD

**Issue by Aanandgupta** [mozilla/addons-frontend#10097]
### Describe the problem and steps to reproduce it:
When the pages are viewed in arabic language the page look much more like mirror image.which breaks the alignment with whole application for this particular language.

Components are looking very ugly for eg ratings 

### What did you expect to happen?
It must be rendered same as pages in other language are.
### Anything else we should know?
Go through the attached image for better understanding.
![Screenshot (144)](https://user-images.githubusercontent.com/71023799/108062481-da445180-707f-11eb-8151-69fc33193f73.png)

**Comment by willdurand** [comment]
Hi, could you tell me more about why you think the page is broken (which is what I understand based on your initial report)?

**Comment by Aanandgupta** [comment]
Hey, willdurand for this particular language every thing looks like mirror image when compared with same pages in different languages. for example icons in this page for this language are right-aligned whereas in other languages it left aligned. same goes with many other things.
1- In a bigger picture I don't find any reason for different styling from the whole application for any particular language.
2- We have some default view for pages so that help us providing better readability to users
for example
a.) Have a look at ratings in the above picture see how 3.5 star is been displayed.
b.)The icons in most of the cases we find icon towards the left of the text but here itis right of the text.

**Comment by willdurand** [comment]
The Arabic language is a Right To Left (RTL) language, which is why the site appears mirrored, see: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/RTL_Guidelines

**Comment by Aanandgupta** [comment]
Thank you  I was not knowing about this fact.

**Comment by willdurand** [comment]
I am going to close this issue then.
