### ISSUE TITLE
pre-commit hook doesn't work (for me - using Windows)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10096]
On commit I get 

```
'"C:\Users\Andrew Williamson\dev\addons-frontend\node_modules\.bin\husky-run"' is not recognized as an internal or external command,

operable program or batch file.
```

This is likely because I'm using git in Windows and husky-run has been set up under linux (WSL).  The `husky-run` file is there but it's just an empty file in Windows rather than a symlink to the script so trying to run `husky-run` doesn't do anything.

**Comment by bobsilverberg** [comment]
I'm not sure how to debug this without Windows. Are you saying that you configured the setup in WSL, but then later are using Git just with plain Windows? Is it possible to run `yarn` in plain Windows as well, and maybe that will fix it? Or will that just generate a ton of errors?

**Comment by eviljeff** [comment]
addons-frontend is setup and run entirely in WSL (it doesn't work in Windows proper).  Git (and VSCode) are running in Windows.  If it try to run `yarn` in plain windows it'll just break addons-frontend instead - unless I can _just_ re-install husky in Windows?

**Comment by bobsilverberg** [comment]
I suppose you could attempt to install husky globally in Windows and see if that does the trick?

**Comment by bobsilverberg** [comment]
It looks like this issue might be the same, and there are a few workarounds suggested you might try: https://github.com/typicode/husky/issues/720
