### ISSUE TITLE
Webpack v5

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10107]
Let's upgrade webpack to v5.

For QA: this affects the entire site but hopefully it shouldn't have an impact. Style and images should load fine and the site should work as before, there shouldn't be any noticeable changes.

---

### `yarn amo:dev`

- [x] investigate the following warning:

      replace autoprefixer browsers option to Browserslist config

- [x] investigate the following error:

      [DEP_WEBPACK_TEMPLATE_PATH_PLUGIN_REPLACE_PATH_VARIABLES_HASH]
      DeprecationWarning: [hash] is now [fullhash] (also consider using
      [chunkhash] or [contenthash], see documentation for details)
      [0] (Use `node --trace-deprecation ...` to show where the warning
      was created)

- [x] investigate the following error:

      [webpack-isomorphic-tools/plugin] [error] Module
      "./src/amo/img/icons/default-64.png" has no source. Maybe Webpack
      compilation of this module failed. Skipping this asset.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO stage - FF86(Win10).
