### ISSUE TITLE
Ignore `platform` in files returned by the API

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10117]
https://github.com/mozilla/addons-server/issues/16466 will remove the `platform` field from the API. Since there are now only one file per version since https://github.com/mozilla/addons-server/issues/16464, frontend should just pick the first file and ignore `platform` information.

(Note: we may make further API changes in the future like exposing `file` instead of `files` or completely merging `version` and `files`, but for now, `files` is still a list, even if it only contains a single file at most)

**Comment by diox** [comment]
QA: make sure detail page and installing add-ons still work (both by navigating to detail page directly from URL or from homepage/search and following a link to one of the add-ons being displayed)

**Comment by ioanarusiczki** [comment]
@diox I tested addon and theme installs with FF86 Unbranded on -dev yesterday and a couple more today on AMO stage.

The only issue noticed is an edge case scenario:
1. from about:profiles I restart the browser with add-ons disabled (the top right grey button) 
2. I go to a detail page and try to install an add-on or theme
3. if I check in about:addons - the addon or theme is in disabled state

This is also reproducible with addons from the recommendations page (it's not only an amo issue)

If I restart normally the browser again the add-ons will be correctly installed - with enabled state
In case I should file an issue, let me know.

**Comment by bobsilverberg** [comment]
@ioanarusiczki I don't quite follow your description of the problem. At which step is there a problem, and what exactly is the problem. When I complete steps 1-3 on prod I see the same results you document above.

**Comment by ioanarusiczki** [comment]
@bobsilverberg

Sorry, I forgot to mention that this behavior it's on prod too. 

I've asked around and I turned to the conclusion that what I described might just be the expected: after restarting with add-ons disabled in safe mode, if I try to install a new addon - this is installed directly into disabled state.

The name of the button is a bit ambiguous, so I first thought that at restart I should see the already installed addons disabled (which is happening) but a new install should behave as usual - the addon is enabled.  

Can you confirm that's the expected?

**Comment by bobsilverberg** [comment]
Yes, this is the expected behaviour.
