### ISSUE TITLE
Look into improvements to css that could impact performance

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10111]
This is a spin off from https://github.com/mozilla/addons/issues/1296, from that issue:

"Our CSS bundle is quite big and takes a long time to download"

We discussed this on Slack and the following suggestions/observations were made:

- Code splitting likely won't help, so not worth investigating for this.
- It was suggested it might be worth trying to reduce the size of the classNames, to reduce the size of the bundle, but it was determined that, because of gzipping, this would likely have a minimal impact.
- Random idea: maybe we have significant dead code or redundant code in our CSS? Andrew says "yes" for addons-server, but it is doubtful we have a significant amount of redundate css code in addons-frontend.
- Repetition in the generated css (as a result of @mixins) was suggested as a possible culprit, but then it was suggested that it's not a serious issue as the resulting css compresses very well. 
- fixing prefixes to target only modern browsers (Will mentioned improving autoprefixer via Webpack upgrade).
- Removing inline images from the css would improve things, and that is something we could try doing after we migrate to HTTP/2. From Mat: "that would greatly reduce css size and browsers would re-use the same connection to request the images they care about - the catch is, the css would need to be small enough that it's parsed quickly enough for the browser to make those requests."
```
un-scientific experiment: a straight search-replace-with-nothing (so not 100% accurate) through our css bundle results in:
116K	amo-0daec8c004e8bad39ed7.css.gz (original)
36K	amo-0daec8c004e8bad39ed7-no-data.css.gz (with data urls removed)
```
- Also discussed was the possibility of switching to css-in-js (which would be a lot of work), but it doesn't seem like that would yield the results we seek, because Webpack.

**Comment by willdurand** [comment]
As of March 9, 2021 the CSS bundle size is 63KB gzipped

**Comment by willdurand** [comment]
> Removing inline images from the css would improve things, and that is something we could try doing after we migrate to HTTP/2. From Mat: "that would greatly reduce css size and browsers would re-use the same connection to request the images they care about - the catch is, the css would need to be small enough that it's parsed quickly enough for the browser to make those requests."

I think this is all we need to do once we have HTTP/2. In the meantime, I think 63KB is good enough.

**Comment by willdurand** [comment]
I am going to work on our css bundle again now that we have http/2 enabled on the CDNs.

**Comment by ioanarusiczki** [comment]
@willdurand 
- if I use a hard refresh on AMO dev pages - I see a .css file being transferred at 36.03 KB, which currently is ~62 KB on the other testing servers. 

![AMO dev](https://user-images.githubusercontent.com/33448286/112833528-86298580-909f-11eb-850f-10e12aa1411f.png)

If there's anything else I should check, let me know.
