### ISSUE TITLE
Update to the latest Flow and fix all the types-first errors

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10120]
In order to update to the latest Flow a large number of changes are required, many of which can be applied automatically via a codemode, but after applying that a number of new errors are reported. Both I and Luca spent some time working on this and we can now produce a patch that addresses all of them.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Please add some str for qa.
Thanks!

**Comment by bobsilverberg** [comment]
> @bobsilverberg Please add some str for qa.
> Thanks!

Sorry @ioanarusiczki. I updated the description.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good after the release testing on AMO stage with FF86 (Win10 + Android 10.0)
