### ISSUE TITLE
Update logic for ShowMoreCard to determine when it needs to reset

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10127]
This issue was discovered when we attempted to remove `connect()` from `PermissionsCard` and found that it created an infinite loop for the `ShowMoreCard`. Upon investigation it appears that the issue is that the logic that determines when we need to reset the UIState for `ShowMoreCard` is flawed, and will create an infinite loop as the content is truncated and then expanded over and over again. There was also a flaw where we were resetting the UIState even when we didn't need to, as it was already in the initial state.

Changing the logic in `ShowMoreCard` to utilize a passed-in `id`, rather than the `content`, along with adding a check that we actually need to change the state in `resetUIState` should fix the problems.

**Comment by diox** [comment]
@bobsilverberg can you add QA instructions for this ?

**Comment by bobsilverberg** [comment]
> @bobsilverberg can you add QA instructions for this ?

Done!

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on AMO stage with FF86(Win10):
- description and developer comments display content as before (nothing unusual noticed) and I don't remember them being expandable - all text is shown no matter of the length.
- a review, version notes, permissions show the content edited in dev hub - they display the "Read More" button which expands the text in case it's longer. A page refresh shows again the Read More button. I think it works as before. 
- a review is displayed on the reviews listing page too with a Read More button in case the text is a bit longer.
- the fields support some HTML (as mentioned by the dev hub tooltip).
