### ISSUE TITLE
Do not include the auth tokens in HTML from the server

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1013]
We currently set the JWT in the state and it gets serialised to the page. We should instead read from the cookie and on the client to avoid including the sensitive token in the page.

**Comment by muffinresearch** [comment]
@mstriemer would be good to fix this one.

**Comment by willdurand** [comment]
I am not sure we can easily do that because the cookie is http-only IIRC. We had to add a server in code-manager for that reason.
