### ISSUE TITLE
Investigate rewriting tests that use mapStateToProps

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10140]
As part of https://github.com/mozilla/addons-frontend/issues/10120, `mapStateToProps` was no longer exported from most components. There are a few tests, however, that use `mapStateToProps` and will therefore fail if we stop exporting it from those components being tested. This means there are a number of components that still export `mapStateToProps`. We should look at all of these tests and see if they can be re-written to not use `mapStateToProps`. It could be that some of them can simply be deleted, and in other cases new tests may need to be written to match the coverage of those currently using `mapStateToProps`.

Update:
Most of this was done during the migration to react-testing-library, but there was one test remaining in the repo which I have fixed to close this issue.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-2
