### ISSUE TITLE
Replace log in button with plain link

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10163]
A really large number of users visit AMO and log in (which creates an AMO account if you don't have one) but don't appear to use the account in any way. It's possible that people think they need to log in, and the button's prominence encourages them to do so.

Let's change the button on the top right corner of AMO pages to a link. The position and copy should stay the same: `Register or Log In`.

The log in button used for reviews and collections should continue to be the same, as well as the button on [Developer Hub](https://addons.mozilla.org/developers/).

**Comment by championshuttler** [comment]
@siddhi523 you might find this a good bug to start with :), good luck

**Comment by championshuttler** [comment]
@siddhi523 you might find this a good bug to start with :), good luck

**Comment by siddhi523** [comment]
thanks, can you assign it to me @jvillalobos ?

**Comment by caitmuenster** [comment]
Hey @siddhi523, once you open a PR, we'll assign you to the issue. :)

**Comment by caitmuenster** [comment]
Hey @siddhi523, are you still interested in this? It turns out we have a deadline on this bug and need to start moving on it in the next week. If you're not able to do it, no worries at all -- there are other good first bugs without deadlines.

**Comment by bobsilverberg** [comment]
From a discussion with @verdi:

- Change the link text to "Register or log in" (no uppercase "L")
- Do not include an underline for the "Register or log in" link

**Comment by kanish671** [comment]
I would like to pick this up if no one else is working on it

**Comment by kanish671** [comment]
<img width="468" alt="Screenshot 2021-03-29 at 9 46 25 PM" src="https://user-images.githubusercontent.com/8206856/112867173-3915d580-90d8-11eb-8577-9cfcd143748a.png">
Is this something similar to what it should look like? Should I make the font sizes the same as for the other links?

**Comment by willdurand** [comment]
> Do not include an underline for the "Register or log in" link

we still need an underline for the hover/active styles, right? (for accessibility/keyboard navigation)

**Comment by jvillalobos** [comment]
The EW and DevHub links have no underline nor distinct hover styles, so this one should be consistent with those IMO.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
This is verified on AMO dev -FF87(Win10). 
on FF
![FF](https://user-images.githubusercontent.com/33448286/114395362-ef7fbd00-9ba4-11eb-9959-82cd5c989f46.png)

non-FF browsers

![nonFF](https://user-images.githubusercontent.com/33448286/114395392-f9a1bb80-9ba4-11eb-8fea-2709038668df.png)
