### ISSUE TITLE
Exclude IE in `browserslist`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10171]
The default browserslist config supports IE but we don't really need to so let's drop support for IE (not Edge).

**Comment by ioanarusiczki** [comment]
@willdurand 
- IE <=11 does not support AMO, there are all kind of visual issues. 
- I'm noticing with the latest Microsoft Edge and Chrome official builds (64-bit Windows) that AMO dev and stage addon detail pages return a 500 server error - which is not reproducible with prod so this seems to be a regression (don't know which issue caused) so I filed it https://github.com/mozilla/addons-frontend/issues/10183

**Comment by willdurand** [comment]
> IE <=11 does not support AMO, there are all kind of visual issues.

@ioanarusiczki how does it look like with AMO -prod?

**Comment by ioanarusiczki** [comment]
@willdurand 

IE - loads the content on dev/stage

![testing on IE](https://user-images.githubusercontent.com/33448286/110643637-f9d12480-81bc-11eb-8c79-b185c5ce54ed.png)

**Comment by willdurand** [comment]
@ioanarusiczki and prod looks the same on IE?

**Comment by ioanarusiczki** [comment]
@willdurand yes, looks similar to me

![similar](https://user-images.githubusercontent.com/33448286/110653386-de1e4c00-81c5-11eb-8f0f-68ea053a2015.gif)

**Comment by willdurand** [comment]
@ioanarusiczki fantastic, thanks. So I guess we didn't really regress, which is good.
