### ISSUE TITLE
CSP errors are thrown when loading detail page

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10173]
### Describe the problem and steps to reproduce it:

- Go to an add-on detail page directly (not by navigating from elsewhere on the site)

### What happened?

- Look at your console: there are CSP errors thrown

### What did you expect to happen?

- No CSP errors

### Anything else we should know?

10 CSP errors are reported. I suspect this is caused by the grouped ratings (5 x 2, probably because we get some at loading time that are then replaced by actual values)

**Comment by bobsilverberg** [comment]
The problem is in `RatingsByStar`, which defines an inline style for a div.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I verified AMO dev and stage - 204 are no longer generated in the Network at page refresh or when "View Product Page" is clicked from dev hub.
