### ISSUE TITLE
Remove dependency on html-entities

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10179]
We use the `html-entities` library to fix #4375 but this is a rather big dependency (in terms of size). 

I am wondering (1) if we can find a smaller replacement and (2) why this is actually needed (it does not seem to be a problem for other user contents like user descriptions).

**Comment by willdurand** [comment]
For (2), the reason is described in https://github.com/mozilla/addons-server/issues/7648

**Comment by diox** [comment]
@willdurand how much would we gained in the gzip bundle if we avoided html-entities completely and fixed that on the API side ?

**Comment by willdurand** [comment]
> @willdurand how much would we gain in the gzip bundle if we avoided html-entities completely and fixed that on the API side ?

Hard to tell but IIRC it was quite significant.

**Comment by diox** [comment]
I've re-opened https://github.com/mozilla/addons-server/issues/7648 to try to tackle this on the API side. I'll probably consist of applying the same "hack" we currently do on the frontend, but directly in the API.

**Comment by diox** [comment]
Here are some quick & dirty test build numbers:

With html-entities:
1319505 bytes raw, 394432 gzipped

Without html-entities:
1241349 bytes raw (78 KB improvement), 366707 gzipped (27 KB improvement, ~7%)
