### ISSUE TITLE
Remove SurveyNotice and related code

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10177]
We removed a reference to the `SurveyNotice` component in #10166 but we didn't
remove the component itself (miscommunication). Let's remove all code related to
this component as we aren't using it.

**Comment by ioanarusiczki** [comment]
@willdurand Please add some str.

**Comment by willdurand** [comment]
> @willdurand Please add some str.

@ioanarusiczki added (there is no visible change, it's only deleted code)

**Comment by AlexandraMoga** [comment]
I've checked our frontend pages on stage and I did not find issues.

I'm marking this issue as verified fixed on stage.
