### ISSUE TITLE
'Flag' label has wrapping issues on mobile view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10184]
### Describe the problem and steps to reproduce it:

1. Open AMO on mobile 
2. Navigate to All reviews page for an add-on
3. Tap on the 'Flag' option

### What happened?
The label is wrapped

### What did you expect to happen?
The Flag label should not be wrapped 

### Anything else we should know?
The issue is reproducible on all AMO servers, so its not new

![R10jlphQQ1](https://user-images.githubusercontent.com/31961530/110637402-09993a80-81b6-11eb-9197-2c63e28ed047.gif)

**Comment by willdurand** [comment]
Thanks for the issue, I was going to report it as well.

**Comment by championshuttler** [comment]
I was facing it on desktop as well

**Comment by championshuttler** [comment]
Still Able to reproduce after latest git pull on desktop:

![image](https://user-images.githubusercontent.com/22130317/110678798-b5fe0f80-81fc-11eb-9c2e-3b7f7d858e5c.png)

**Comment by championshuttler** [comment]
Ohh can we use `word-wrap: normal;` for this @willdurand ? :p,

**Comment by AlexandraMoga** [comment]
FWIW I can't reproduce the issue on desktop (by desktop I mean normal view, not mobile view in responsive design mode). I'm on a Win10 machine. 

![image](https://user-images.githubusercontent.com/31961530/110752633-34cf6880-824e-11eb-9921-0c19897da62c.png)

**Comment by championshuttler** [comment]
> FWIW I can't reproduce the issue on desktop (by desktop I mean normal view, not mobile view in responsive design mode). I'm on a Win10 machine.


I am on macOS bigSur, tested in Firefox Desktop and Brave, still facing this

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on dev:

![image](https://user-images.githubusercontent.com/31961530/112167836-715d7580-8bf9-11eb-999c-e2f8ffb41552.png)
