### ISSUE TITLE
Select a generic reason for your add-on rating

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1018]
This is to implement the UI component for selecting a generic reason that describes why you rated your add-on experience either [happy, meh, or sad](https://github.com/mozilla/addons-frontend/issues/1017).

This screen differs based on the initial smiley you selected. Example:

![screenshot 2016-09-02 13 22 41](https://cloud.githubusercontent.com/assets/55398/18214157/175f818e-7111-11e6-8a55-afad3b427245.png)

UX flow: https://mozilla.invisionapp.com/share/A58EEQUK6#/screens/183938155
UX flow tracker: #927
This supports mozilla/addons#151

**Comment by muffinresearch** [comment]
This is no longer relevant.
