### ISSUE TITLE
Investigate long initial connection problems

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10194]
When running various tools like Lighthouse (locally) or PageSpeed Insight, we noticed very long initial connections and that's a problem because it makes the site less fast than it should. If we take a big site like airbnb.com, which returns pretty much the same amount of HTML (gzipped or not), it loads _a lot_ faster than AMO and there is no long initial connection.

We don't know the root cause(s) yet so let's investigate TLS negotiation, TCP config (maybe?), etc.

**Comment by willdurand** [comment]
I did some tests and used airbnb.com as the baseline (to ignore my local/Internet connection settings):

- DNS resolution looks okay
- connecting to an AMO server (TCP established) is slower (20-100ms for Airbnb, 180-200ms for AMO)
- SSL handshake is quite slow: > 500ms for AMO compared to 60-100ms for Airbnb
- Time To First Byte on AMO for cold requests is slow (1s) but quite decent for subsequent requests (250-300ms). Airbnb is pretty fast for cold requests (< 150ms) and super fast for subsequent requests (20ms, caching maybe?)

I used the following commands:

```
$ curl -w "dns_resolution: %{time_namelookup}, tcp_established: %{time_connect}, ssl_handshake_done: %{time_appconnect}, TTFB: %{time_starttransfer}\n" -o /dev/null -s "https://www.airbnb.com/"
$ curl -w "dns_resolution: %{time_namelookup}, tcp_established: %{time_connect}, ssl_handshake_done: %{time_appconnect}, TTFB: %{time_starttransfer}\n" -o /dev/null -s "https://addons.mozilla.org/en-US/firefox/"
```

For subsequent requests, one can append `-o /dev/null -s "<same url>"`.

**Comment by diox** [comment]
> Time To First Byte on AMO for cold requests is slow (600ms) but quite decent for subsequent requests (250-300ms). Airbnb is super fast for any requests (20-50ms)

https://github.com/mozilla/addons-frontend/issues/10116 should help there

**Comment by bobsilverberg** [comment]
Results from Canada (average of 5 executions):

```
		 dns_resolution  tcp_established  ssl_handshake_done  TTFB
		 --------------  ---------------  ------------------  ----
airbnb   0.0104		     0.2461		      0.4915			  0.6230
moz.org  0.1741			 0.3693			  0.8278			  1.4027
```

**Comment by rik** [comment]
I think your biggest issue here is the OCSP verification because of an EV certificate used for addons.mozilla.org.

[WebPageTest run showing the issue](https://www.webpagetest.org/result/210316_AiYB_a3aa88a06fc317434822abb97784b7de/2/details/)
![Screenshot Safari WebPageTest Test Details - London  addons addonepubreader - 031621 120956 2021-03-16 at 12 31 26](https://user-images.githubusercontent.com/3653/111309687-17d2d500-8654-11eb-8261-4f2989029aad.png)


Some blog posts to understand what's going on:
- [Short explainer](https://simonhearne.com/2020/drop-ev-certs/)
- [Long explainer](https://nooshu.github.io/blog/2020/01/26/the-impact-of-ssl-certificate-revocation-on-web-performance/)

**Comment by willdurand** [comment]
I filed a bug for the cert: https://bugzilla.mozilla.org/show_bug.cgi?id=1700098

**Comment by diox** [comment]
The certificate has been updated and it has made a big difference (~ a second over 4G). We have also identified potential issues with gzip and caching not being as fast as it should in general that once fixed should improve server processing time for our pages.

**Comment by rik** [comment]
[With/Without EV WebPageTest comparison](https://www.webpagetest.org/video/compare.php?tests=210413_AiDc97_7e7b659379e1c7b0cbdc1e64b53c0465%2C210409_AiDc69_25c24d424010b160281c522c8c5d8450&highlightLCP=1&thumbSize=200&ival=500&end=visual)

**Comment by willdurand** [comment]
Nice, I think our job here is done. I'll file an issue for gzip. Thanks @rik!
