### ISSUE TITLE
Test platform code for installing an add-on

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#102]
Very similar to #15, this is to check that an add-on can be installed using the funky new api and get the appropriate messages and status back. This bug doesn't need to get into how the buttons look in all those states, it just needs to check that when we do get the buttons UX it will work nicely.

The bugs to track this work are in: https://bugzilla.mozilla.org/show_bug.cgi?id=1245571

**Comment by muffinresearch** [comment]
We tested this closing.
