### ISSUE TITLE
Use webpack's contenthash instead of chunkhash for better long-term caching

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10206]
From the webpack docs:

> The [contenthash] substitution will add a unique hash based on the content of
> an asset. When the asset's content changes, [contenthash] will change as well.

We should update our webpack config to use `contenthash` instead of `chunkhash`
given that the content hash approach is more useful than what we currently have.

**Comment by ioanarusiczki** [comment]
@willdurand If qa can check on this, let me know.

**Comment by willdurand** [comment]
> @willdurand If qa can check on this, let me know.

@ioanarusiczki added

**Comment by AlexandraMoga** [comment]
I've navigated through our frontend pages and they were all loaded without any layout issues. I've also looked in the console for  css and js files and there were no errors reported.

I'm marking this issue as verified fixed on stage.
