### ISSUE TITLE
Some content in the footer is hard to read

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10201]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-dev.allizom.org/en-US/firefox/
2. Scroll down to see the footer

### What happened?

The content at the bottom (`Except where otherwise noted [...]`) is hard to read: it's too thin.

### What did you expect to happen?

It's easily readable.

### Anything else we should know?

Let's remove `font-weight: lighter` in `Footer/styles.scss`.

**Comment by ioanarusiczki** [comment]
@willdurand I verified on FF86, Chrome, Edge and Android - footer looks good, font-weight:lighter has been removed.

Before:
![footer on dev](https://user-images.githubusercontent.com/33448286/111332524-8d519c00-867a-11eb-91cc-47667fb0d19b.png)

Now:
![footer on dev now](https://user-images.githubusercontent.com/33448286/111332561-9478aa00-867a-11eb-8484-1895f5be0beb.png)
