### ISSUE TITLE
Generate bundles in a sub-directory

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10219]
This is related to https://bugzilla.mozilla.org/show_bug.cgi?id=1501687.

We'd like to generate the JS/CSS bundles in a sub-directory, e.g., `static/`,
which would result in a `dist/` folder with a single `static/` folder, and the
latter should contain the JS/CSS files.

For QA: it should not change anything.

**Comment by ioanarusiczki** [comment]
@willdurand 

I did some testing on the frontend and I didn't find anything unusual.

Verified on AMO dev - FF86(Win10).
