### ISSUE TITLE
Dev Hub landing page

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#1021]
This is a new issue to address the [landing page](https://addons.mozilla.org/developers/) specifically. Some of the discussion has [started here](https://github.com/mozilla/addons/issues/153). We are aiming to revamp the landing page in Q4 2016.

I started an [outline](https://docs.google.com/document/d/1p4FvylMqrg0apdvcE1eGdV1un_STX61VjgUq6ZswTu0/edit#) of the content we want on this page.

Next step is to wireframe it taking into account this outline and the work Bram started in [issue 153](https://github.com/mozilla/addons/issues/153).

I don't want to get bogged down on naming issues for this refresh, because that's a whole other project. We'll use "add-ons" when talking about personalizing Firefox, and "extensions" and "themes" for distinguishing between different kinds of add-ons. "WebExtensions" should be used when talking about changes to the underlying technology of add-ons and the impact on compatibility.

There might be a few additional pages we'll have to refresh or create in order to support the new content and flow.

**Comment by brampitoyo** [comment]
I’ve updated my mockups to unify the visual design of the signed out/signed in state and incorporated the new navigation footer, too.

### Signed out

On the signed out state, we’ve reduced our six-colour backgrounds down to blue, dark blue and light grey. It’s less vibrant, but some pink and white texts help keep some of the colour intact.

![landing page - not signed in with sidebar - visual design](https://cloud.githubusercontent.com/assets/51007/19257405/ccadd5bc-8fcb-11e6-85e9-e9f42dfc0987.png)

![landing page - mobile - not signed in with sidebar - visual design](https://cloud.githubusercontent.com/assets/51007/19257722/61477320-8fce-11e6-9fad-f0b92f0260bf.png)

### Signed in

On the signed in state, the same dark blue section is now applied to our “Documentation, Tools & Contribute” section. Also note how the text size on this state is smaller than the signed out one. This page is less marketing-y and more densely packed with information, so smaller text sizes help keep the proportion (between header – content – footer) balanced.

![landing page - signed in - visual design](https://cloud.githubusercontent.com/assets/51007/19257526/c39e3e8e-8fcc-11e6-8720-963feaeea44c.png)

#### Signed in – no add-on

When you have no add-on submitted, we’re going to replace your list of add-ons with a message that asks you to start the submission process.

![landing page - signed in - firstrun - visual design](https://cloud.githubusercontent.com/assets/51007/19257660/ec622d3e-8fcd-11e6-9add-8d538409af94.png

### Measurements

The measurements for the signed out state is quite simple. The signed in state is more tricky, so it’s provided here.

![landing page - signed in - measurement - visual design](https://cloud.githubusercontent.com/assets/51007/19257726/6c203bba-8fce-11e6-8cd8-1b9ab19c7aa0.png)

### File

The latest Sketch file can be found inside this folder:
https://www.dropbox.com/sh/8o9j8a47fjunel0/AABIaUrmx50AkbS3MuQlsy61a?dl=0

**Comment by atsay** [comment]
Here are some text edits for the [Signed In, no add-ons](https://cloud.githubusercontent.com/assets/51007/19257660/ec622d3e-8fcd-11e6-9add-8d538409af94.png) view:
- Change the button text "Submit Your First Add-on" to "Submit Your First Extension"
- Change description to "This is where you view and manage your add-ons. To publish your first add-on, click "Submit Your First Extension" or "Submit Your First Theme".
- Remove "Download a sample extension" link.

**Comment by atsay** [comment]
Change footer text under the Documentation header to:

Support
- [About](https://addons.mozilla.org/about)
- [FAQ](https://addons.mozilla.org/faq)
- [Report Bug](https://github.com/mozilla/addons/issues/new)
- [Site Status](https://status.mozilla.org/#addons.mozilla.org_service_history)

Developers
- [Add-ons](https://developer.mozilla.org/en-US/Add-ons)
- [Themes](https://developer.mozilla.org/en-US/Add-ons/Themes/Background)
- [Review Policies](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy)
- [Get Your Add-on Featured](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Featured)

Community
- [Forum](https://discourse.mozilla-community.org/c/add-ons)
- [Blog](https://blog.mozilla.org/addons/)
- [Contact us](https://developer.mozilla.org/en-US/Add-ons#Contact_us)

Legal
- [Report Trademark Abuse](https://www.mozilla.org/about/legal/fraud-report/)
- [Privacy Policy](https://www.mozilla.org/privacy/websites/)
- [Legal Notices](https://www.mozilla.org/about/legal/)

**Comment by brampitoyo** [comment]
Hi Amy, thanks for all the content feedback! I’ve incorporated them below and will update the master post up above when it’s final.

> Change footer text under the Documentation header…

One question I have is whether this change refers to the dark blue section, or the white section below it?

In the mockup below, I’ve made the change on the dark blue section, and subsequently gotten rid of the white one. Is this what you meant, or is it something else?

Talk to you next week!

![landing page - signed in - firstrun - visual design](https://cloud.githubusercontent.com/assets/51007/19795569/6f688f0e-9d28-11e6-8e29-ecc05ccabf68.png)

**Comment by atsay** [comment]
@brampitoyo I edited the last comment to reflect changes based on our last discussion.

**Comment by brampitoyo** [comment]
@atsay I’ve edited the master post with the new footer content based on your suggestion. Let me know what you think of it!

**Comment by atsay** [comment]
@brampitoyo It looks great, thanks Bram! Do you think the design will look even more balanced if there is a third column under the Contribute header? If so, we can add this:

**More Ways to Participate**
You don’t need coding skills to help keep Firefox the most customizable
browser available!
See how

**Comment by EnTeQuAk** [comment]
Hey, I'll be working on the footer this week. Reading that @atsay wanted the footer to be changed to be dark blue all the time - is that still something to integrate or did you talk about it and discard that idea?

@brampitoyo I'm assuming you keep the sketch file in the original post up-to-date too right?

**Comment by atsay** [comment]
Bram suggested going all blue based on my content feedback, and I agreed.

**Comment by EnTeQuAk** [comment]
Ah, perfect. Thanks!

**Comment by atsay** [comment]
Just realized that in the signed out state, the footer background color is reversed from the signed in state. @brampitoyo - should we make both consistent, or do you mean for it to be reversed upon sign-in? I actually slightly prefer the white version because it looks cleaner, but consistency and overall design are more important to me.

**Comment by brampitoyo** [comment]
@atsay wrote:

> Do you think the design will look even more balanced if there is a third column under the Contribute header?

Yes. Absolutely. Where would this “See How” link lead to? Either way, I’m happy to add it.


> I actually slightly prefer the white version because it looks cleaner, but consistency and overall design are more important to me.

What if it’s a compromise: the footer on the signed out state remains white as before, but the signed in state is a very light grey similar to the header?

I’ve updated the master post with the latest images. Let me know what you think of these changes!


@EnTeQuAk – I haven’t updated the Sketch file for the past two weeks due to bad upload speed, but it’s been fixed. Check out the latest iteration on Dropbox!

**Comment by EnTeQuAk** [comment]
@brampitoyo awesome, thanks!

**Comment by atsay** [comment]
@brampitoyo Love the compromise and the gray, thanks!

The "See How" link goes to https://wiki.mozilla.org/Add-ons/Contribute

**Comment by fangshih** [comment]
Just updated the illustration assets! 
The latest Sketch file and image assets can be found inside this folder:
https://www.dropbox.com/sh/8o9j8a47fjunel0/AABIaUrmx50AkbS3MuQlsy61a?dl=0

Please let me know if you have any questions, or need the assets in a different format. 
Thanks!! :)

**Comment by brampitoyo** [comment]
I’ve updated the master post with mockups containing the latest illustration. We’re now ready to implement. Thank you, @fangshih!

**Comment by EnTeQuAk** [comment]
Awesome, thanks a lot everyone! I'll integrate them asap. They look beautiful ^_^

**Comment by EnTeQuAk** [comment]
@brampitoyo one smaller question to make sure this change is intended - the footer text color changed from an orange-ish color to that mint-ish (I fail to describe colors). Is that intended?

**Comment by brampitoyo** [comment]
> […] the footer text color changed from an orange-ish color to that mint-ish (I fail to describe colors). Is that intended?

Yes. That’s intended. For both the signed out and signed in state, the footer should always be coloured light grey – the same colour as the header in signed in state.

**Comment by EnTeQuAk** [comment]
@brampitoyo @pwalm small detail question: For the links in general (white ones in the top heading green-ish ones and the blue ones in the footer), do you have any preference in regard to hover-changes, e.g changing colors etc? Otherwise I'd just fade them a bit while hovering.

**Comment by pwalm** [comment]
fade em a bit

**Comment by atsay** [comment]
@EnTeQuAk For the signed-in What's New section, let's update them to the following:

Happy New Year! See what's in store for add-ons in 2017
Button: Show me (https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/)

WebExtensions are becoming the standard for add-on development in Firefox. You'll need to update your legacy add-ons to stay compatible.
Button: Learn how (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on)

**Comment by andymckay** [comment]
I feel like we can probably start to drop the "becoming the standard". We've deprecated everything else.

**Comment by EnTeQuAk** [comment]
@jvillalobos @pwalm one detail question, in the "My Addons" section (https://cloud.githubusercontent.com/assets/51007/20368698/4031d714-aca9-11e6-89e1-171342676250.png) - for the first two entries there's explicitly an `AMO` and the `Self-hosted` tag visible. At the moment we are hiding this on AMO if an add-on is fully listed or unlisted and are only showing that if there are mixed listed/unlisted versions.

Should I stay with the current behavior of AMO or was there a decision to show the tag explicitly now?

**Comment by brampitoyo** [comment]
@EnTeQuAk wrote:
> At the moment we are hiding [AMO and Self-hosted tags] if an add-on is fully listed or unlisted and are only showing that if there are mixed listed/unlisted versions.

Let’s stay with the current behaviour for now and not show the tag unless it’s required to clarify.

**Comment by jvillalobos** [comment]
Agree with Bram.

**Comment by EnTeQuAk** [comment]
Perfect, thanks!

**Comment by EnTeQuAk** [comment]
This landed now so it's done. If there are any issues or follow-ups, let's open separate new issues. Thanks everyone for the help and work on this!
