### ISSUE TITLE
Change download button to include "with add-on name"

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10217]
There is a suggestion that the Download Firefox button, which currently says "Only with Firefox — Get Firefox Now", be changed to say "Download Firefox with {add-on name}". Some issues to discuss:

- Should we still say "with {add-on name}" if the add-on does not support RTAMO?
	- We do not currently know (based on the API response) if an add-on is supported.
	- We hope to support more/most add-ons in the future.
- Should we be excluding this new text if the user is on the mobile (`/android/`) site? RTAMO is not supported on Fenix (nor on iOS).
- Add-on names can be quite long, as long as 50 characters. How will that affect the button's appearance and is there anything we can do to mitigate this?

**Comment by bobsilverberg** [comment]
@jvillalobos @Verdi I believe it was decided to drop this, and not include the name of the add-on in the Download Firefox button. Can you please confirm if that is correct?

**Comment by jvillalobos** [comment]
Based on the current state of the designs, that's correct.

**Comment by bobsilverberg** [comment]
> Based on the current state of the designs, that's correct.

Thanks Jorge. In that case I am closing this issue.

**Comment by ioanarusiczki** [comment]
@bobsilverberg From what I understand the issue did not bring code and ux changes - could you mark it qa not needed?

**Comment by bobsilverberg** [comment]
Sorry about that @ioanarusiczki. This was closed with no changes, but I forgot to remove the milestone. I have done that now.
