### ISSUE TITLE
The new font is not very readable in non-Firefox browsers

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10216]
Follow up for #10040 

### Describe the problem and steps to reproduce it:
1. Load AMO -dev in a non-Firefox browser - an add-on detail page is the best example for this case (example: https://addons-dev.allizom.org/en-US/firefox/addon/terms-of-service-didn-t-read/)
2. Try to read the various sections present on the detail page - focus on the 12px text particularly (see add-on description, permissions, Download file link, etc.)

### What happened?
The text is very faded, making the content hard to read

### What did you expect to happen?
The text should be more readable

### Anything else we should know?
- I've checked with Chrome, Opera and Edge on Win10 and Fenix with Android 10
- I'm not sure how we should address this issue overall, but we should at least do something about the  'Download file' link, which is barely readable currently 

[Chrome]
![image](https://user-images.githubusercontent.com/31961530/111293283-c45f8780-8651-11eb-96ca-f5e4b0780873.png)

[Fenix]
![image](https://user-images.githubusercontent.com/31961530/111293309-cb869580-8651-11eb-8265-964bbd9c3591.png)

**Comment by willdurand** [comment]
I don't think it's super readable on FF either but I am not sure that it's not because it's a new font and my eyes are used to the previous one. Maybe with time, we'll think it's fine? I agree the "Download file" link looks almost invisible on the screenshots above, though.

**Comment by willdurand** [comment]
We think that https://github.com/mozilla/addons-frontend/issues/9078 could help here.

**Comment by KrasnayaPloshchad** [comment]
What happened if you try to use Inter Condensed for the content?

**Comment by bobsilverberg** [comment]
@AlexandraMoga Can you please take another look at this when you have time. We did increased the base font size overall, and specifically addressed the Download File link. If there are still issues, can you update this to call them our specifically?

**Comment by bobsilverberg** [comment]
@AlexandraMoga Just bumping this again. Can this be closed?

**Comment by AlexandraMoga** [comment]
Ah, yes, I forgot about this issue. I think the font is more readable now with the increased size.
