### ISSUE TITLE
Experiment design for new Download Firefox CTA

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10218]
We plan to conduct an experiment for the new Download Firefox CTA. Here are some assumptions/issues.

Assumptions:
- The experiment will compare the current UX with one single variation of the new UX.
- The experiment will be focused on the rate at which the Download Firefox CTA is clicked.
- The experiment will evaluate the final conversion rate (actual Firefox downloads) of the new CTA vs the existing CTA, but will not hypothesize on an increased rate of conversion. It is hypothesized, however, that there will be no regression in the conversion rate.
- A utm param will be used to allow mozilla.org to differentiate between the new CTA and the old CTA.
- A series of GA events will be used to record user behaviour wrt the new vs old CTAs, and will then be used for analysis.

Questions:
- What is our hypothesis for the increased click-rate for the new CTA?
- What utm parameter can/should we use to allow mozilla.org to differentiate between the new CTA and the old CTA? GA supports using the `utm_content` param to perform analysis, but that is the same param that is currently used by RTAMO, so there is a conflict there.
- Will the experiment be active for the mobile (`/android/`) site as well as the desktop (`/firefox/`) site?

Pinging @jvillalobos for validation and feedback.

**Comment by jvillalobos** [comment]
Agreed on the assumptions.

>  What is our hypothesis for the increased click-rate for the new CTA?

The expected increase is detailed in the [spec doc](https://docs.google.com/document/d/1Hw1ETpXCu6ZlpVGm8aQ9XW-U8cJBUiCvHD33PqT-Wvw/edit#), under section 2.1 ("Increase conversion rate of non-Firefox users"). I hesitate on publishing the actual numbers here, so I'm playing it safe.

> What utm parameter can/should we use to allow mozilla.org to differentiate between the new CTA and the old CTA? 

I think we can use `utm_campaign` for this purpose. Currently we use `non-fx-button` as value in all cases. I'd like to make some changes to it:

- Use `amo-fx-cta` for the general CTA that appears at the top of the page.
- Use `amo-fx-cta-($ID)` for the CTA that appears on a listing page, with the numerical add-on ID appended to it. This is a bit of scope creep but it will help us in the future to identify which add-ons drive more downloads.
- Append `-groupa` or `-groupb` to the above values, for test participants.

> Will the experiment be active for the mobile (/android/) site as well as the desktop (/firefox/) site?

Yes.

/cc @tublitzed

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos 

> Agreed on the assumptions.
> 
> > What is our hypothesis for the increased click-rate for the new CTA?
> 
> The expected increase is detailed in the [spec doc](https://docs.google.com/document/d/1Hw1ETpXCu6ZlpVGm8aQ9XW-U8cJBUiCvHD33PqT-Wvw/edit#), under section 2.1 ("Increase conversion rate of non-Firefox users"). I hesitate on publishing the actual numbers here, so I'm playing it safe.
> 

Can you define exactly what we mean by "conversion rate of non-Firefox users on AMO"? Is this just measuring click-through, or does it also take into account whether the user actually downloads Firefox from mozilla.org? I want to make sure we are recording the correct data to allow us to measure the impact on this metric.

> > What utm parameter can/should we use to allow mozilla.org to differentiate between the new CTA and the old CTA?
> 
> I think we can use `utm_campaign` for this purpose. Currently we use `non-fx-button` as value in all cases. I'd like to make some changes to it:
> 
> * Use `amo-fx-cta` for the general CTA that appears at the top of the page.
> 
> * Use `amo-fx-cta-($ID)` for the CTA that appears on a listing page, with the numerical add-on ID appended to it. This is a bit of scope creep but it will help us in the future to identify which add-ons drive more downloads.
> 
> * Append `-groupa` or `-groupb` to the above values, for test participants.
>

I checked the existing data on GA for mozilla.org and can confirm we can use `utm_campaign` for this, but I'm not entirely sure about the approach for listing pages (including the add-on id). I am concerned that making these unique per add-on might make it difficult to measure the impact overall of `groupa` vs `groupb`. Do you share that concern, or have you done similar things in the past and been able to aggregate the data even with a unique value embedded in the middle of the utm param?

If this might be a problem for measurement, then maybe we can just omit the add-on id from the utm param on the listing page for the duration of the experiment. This is something we should validate.

**Comment by jvillalobos** [comment]
> Can you define exactly what we mean by "conversion rate of non-Firefox users on AMO"? Is this just measuring click-through, or does it also take into account whether the user actually downloads Firefox from mozilla.org?

It means click-through. That's the metric we want to increase. The UTM param changes should allow us to measure actual downloads, in addition to the click-through rate, but that's more in the nice to have territory.

> Do you share that concern, or have you done similar things in the past and been able to aggregate the data even with a unique value embedded in the middle of the utm param?

GA allows filtering a UTM param using various options, like "Starts with", "Ends with", and even regular expressions. I think that for our measuring purposes we should be okay. That is, unless we expect to use other tools to keep track of this and they aren't as robust.

**Comment by bobsilverberg** [comment]
@jvillalobos @Verdi One of the things we plan to do is to change the colour of the Download Firefox buttons to blue. I believe we plan to do that regardless of what happens with the experiment. To that end, I think it makes sense to do that *now*, before the experiment, as opposed to making that part of the experimental CTA. That will reduce the number of factors we are testing.

WDYT?

**Comment by bobsilverberg** [comment]
> 
> > > What utm parameter can/should we use to allow mozilla.org to differentiate between the new CTA and the old CTA?
> > 
> > 
> > I think we can use `utm_campaign` for this purpose. Currently we use `non-fx-button` as value in all cases. I'd like to make some changes to it:
> > 
> > * Use `amo-fx-cta` for the general CTA that appears at the top of the page.
> > * Use `amo-fx-cta-($ID)` for the CTA that appears on a listing page, with the numerical add-on ID appended to it. This is a bit of scope creep but it will help us in the future to identify which add-ons drive more downloads.
> > * Append `-groupa` or `-groupb` to the above values, for test participants.
>

@jvillalobos Is it important to use `-groupa` and `-groupb` to obfuscate what these groups mean, or can I use `current-cta` and `new-cta` to make it more obvious in GA which is which?

**Comment by bobsilverberg** [comment]
@jvillalobos @Verdi We also need to figure out what to do with the current "Download Firefox" button in the header, when the user is enrolled into the "new cta" cohort in the experiment. My first inclination was to remove it in that case, but that is a problem because the new banner is dismissable, and if we remove the current header button, and they dismiss the banner, there is no longer a link to download Firefox except on the add-on detail page, so I don't think we can do that.

The question is, how do we mark it up so it doesn't mess with our statistics? I.e., if a user is in the new cohort, and they do click on a Download Firefox button, but it's not the link from the new banner, nor is it a link from the add-on detail page, how do we want to interpret that? Would that still count as a conversion accredited to the new-style CTA, as the user was seeing the new CTA on the site, or should be be accredited to the current CTA, because they didn't click on a link with the new CTA associated with it, but rather clicked on a link they would have seen with the old CTA? Or would we want to simply not count it at all, because it is kind of a hybrid of the two styles?

**Comment by bobsilverberg** [comment]
I don't think GitHub sends notifications when you add a mention of someone to an already existing comment, so I'm just going to do it again here.

@muffinresearch @tublitzed @mozilla/addons-amo-engineering and anyone else with an opinion on this, see the comment directly above this one.

**Comment by jvillalobos** [comment]
>  One of the things we plan to do is to change the colour of the Download Firefox buttons to blue. I believe we plan to do that regardless of what happens with the experiment. To that end, I think it makes sense to do that now

Agree.

> can I use current-cta and new-cta to make it more obvious in GA which is which

Yeah, good idea.

> We also need to figure out what to do with the current "Download Firefox" button in the header

It shouldn't show up for the cohort with the new CTA. You're right that dismissing the banner can't be easily undone, but the listing CTA is still there, so that should cover most cases. There are also footer links leading to mozilla.org, so it's not like non-fx users are completely out of options. Maybe we can add a nicer download Firefox link to the footer for those users, but I wouldn't consider it a high priority and like you pointed out it would add unnecessary noise to the experiment.

This got me thinking that maybe we should also add a GA event to the banner being dismissed. It could be useful to count how often people remove it, at least for the duration of the experiment.

**Comment by bobsilverberg** [comment]
> > One of the things we plan to do is to change the colour of the Download Firefox buttons to blue. I believe we plan to do that regardless of what happens with the experiment. To that end, I think it makes sense to do that now
> 
> Agree.
> 

Great, I opened https://github.com/mozilla/addons-frontend/issues/10323 for this and plan to land it this week.

> > can I use current-cta and new-cta to make it more obvious in GA which is which
> 
> Yeah, good idea.
>

Thanks!
 
> > We also need to figure out what to do with the current "Download Firefox" button in the header
> 
> It shouldn't show up for the cohort with the new CTA. You're right that dismissing the banner can't be easily undone, but the listing CTA is still there, so that should cover most cases. There are also footer links leading to mozilla.org, so it's not like non-fx users are completely out of options. Maybe we can add a nicer download Firefox link to the footer for those users, but I wouldn't consider it a high priority and like you pointed out it would add unnecessary noise to the experiment.
>

Ok, I am still a bit worried that we might somewhat regress on the conversion rate if we hide the banner and don't have anything else prominent there, but I guess a user who dismisses the banner is probably not going to download Firefox anyway.
 
> This got me thinking that maybe we should also add a GA event to the banner being dismissed. It could be useful to count how often people remove it, at least for the duration of the experiment.

I have added that to the patch I am working on.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

1.  The classic view (or current view): 
On mozilla.org I see in the network at query string parameters: 
utm_campaign: amo-fx-cta-616840-current-cta when I click the download button from the detail page
utm_campaign: amo-fx-cta-current-cta for the Download Firefox button on the top of the pages

2.  The other cohort - with the new view:
On mozilla.org I see in the network at query string parameters: 
utm_campaign: amo-fx-cta-616840-new-cta from a detail page
utm_campaign: amo-fx-cta-new-cta for the yellow banner at the top of the pages

3.  When the banner is dismissed:
- the Console indicates an event was sent

[GA: ON] sendEvent: {hitType: "event", eventCategory: "AMO Download Firefox Banner", eventAction: "download-firefox-banner-dismiss", eventLabel: undefined, eventValue: undefined}

- there is a POST to https://www.google-analytics.com/collect and the event is present in the request payload

`v=1&_v=j89&a=899737954&t=event&_s=5&dl=https%3A%2F%2Faddons-dev.allizom.org%2Fen-US%2Ffirefox%2F&ul=en-us&de=UTF-8&dt=Add-ons%20for%20Firefox%20(en-US)&sd=24-bit&sr=1920x1080&vp=1903x356&je=0&ec=AMO%20Download%20Firefox%20Banner&ea=download-firefox-banner-dismiss&_u=SACAAEABEAAAAC~&jid=&gjid=&cid=1289943668.1615379307&tid=UA-36116321-7&_gid=1536551950.1618309835&cd3=addons-frontend&z=201244756`

 "Download firefox" blue button is not present for the new cta - the yellow banner is shown instead. 

I verified this with Chrome and Edge - on AMO dev. 
In case there's anything else I should check, please let me know.
