### ISSUE TITLE
Link to archived "Developer Policies" should point to updated content.

### ISSUE THREAD

**Issue by tublitzed** [mozilla/addons-frontend#10223]
### Describe the problem and steps to reproduce it:
In the sitewide footer, we have a link to "Developer Policies" that points to this [archived page](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy) - guessing there's an updated policy location to link to?

### What happened?
Link went to archived page.

### What did you expect to happen?
Link goes to current page :)

### Anything else we should know?
![Screen Shot 2021-03-16 at 10 38 15 AM](https://user-images.githubusercontent.com/1756056/111327392-bacf2300-8643-11eb-8d67-a98a9adb8741.png)

**Comment by ioanarusiczki** [comment]
@eviljeff This is fixed on AMO dev - FF86(Win10). 

I think that this should be fixed for the dev hub - footer section too so I filed on server https://github.com/mozilla/addons-server/issues/16787
