### ISSUE TITLE
"Find add-ons" notice on Android

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10228]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-dev.allizom.org/en-US/android/addon/bubbles-for-mozilla-appr/versions/?utm_content=featured&utm_medium=referral&utm_source=addons.mozilla.org

### What happened?

There is a notice about add-ons compatible with Firefox for Android.

### What did you expect to happen?

No notice? I am on the Android site already so I don't think the notice should appear here.

I'll try to find the docs about this notice to understand why it could be here, though. I also see it on user profiles.

### Anything else we should know?

![Screenshot_20210317-082130_Firefox_Nightly](https://user-images.githubusercontent.com/217628/111430040-18be4200-86fa-11eb-9054-f27b9e8a99ef.png)

**Comment by bobsilverberg** [comment]
The doc that describes the various versions of the notice can be found here: https://docs.google.com/spreadsheets/d/1rqPj5NXPNE9EPDuIPy8AjMxs5k0BBic9c_c7WGjGhWs/edit?usp=sharing, and I believe the above notice is correct, assuming this add-on is not available on Fenix.

**Comment by bobsilverberg** [comment]
> > I believe the above notice is correct, assuming this add-on is not available on Fenix.
> 
> It's a "all versions" page? 🤔 And that notice also appears on user profiles..

That is line 3 of the spreadhseet that I shared, which indicates that this notice is wanted. I believe the general idea is that a user on Fenix cannot find an add-on to install from any of these locations, and therefore are directed back to the main `android` home page which is the only place guaranteed to display add-ons that are compatible with Fenix.

**Comment by willdurand** [comment]
> That is line 3 of the spreadhseet that I shared, which indicates that this notice is wanted. I believe the general idea is that a user on Fenix cannot find an add-on to install from any of these locations, and therefore are directed back to the main `android` home page which is the only place guaranteed to display add-ons that are compatible with Fenix.

I've seen that, indeed. I guess I forgot about it and now I find this notice kinda odd as a end user.
