### ISSUE TITLE
Flash of content before Inter font gets loaded

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10222]
### Describe the problem and steps to reproduce it:

1. Load https://addons-dev.allizom.org/en-US/firefox/ (use hard reload)

### What happened?

There is a flash of content because the text size changes.

Jorge described it as:

> I see the font getting thinner and more spaced out when hard-reloading

### What did you expect to happen?

No flash of content.

### Anything else we should know?

@eviljeff said:

> the font switch might be adding font-display: swap; - Firefox will render without Inter if it's not available initially, rather than block on the file being available.

**Comment by ioanarusiczki** [comment]
@willdurand I tested on AMO dev and stage - FF86, Chrome and Edge, refreshing pages with Ctrl+Shift + R or Ctrl+F5 (Win10)I don't see any visual issue, the letters reappear without being thinner, it's just like before the hard reload.
