### ISSUE TITLE
Update CSP once we use a sub-folder

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10220]
After https://github.com/mozilla/addons-frontend/issues/10219 and is verified, we should update the CSP config.

**Comment by willdurand** [comment]
@muffinresearch I implemented the change for the sub-folder in #10219 and it works.

I think we can update the CSP but the `favicon.ico` is at the root directory and we don't control that (i.e. we don't push it and it's not versioning in this repo) 🤔

**Comment by muffinresearch** [comment]
So I think one solution to that which would be ok would be to mention that entire path explicitly along with the new directory-based path.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me. Verified on AMO stage - FF87(Win10).
