### ISSUE TITLE
Remove FeaturedCollectionCard

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10236]
After https://github.com/mozilla/addons-frontend/pull/10065 lands, we will no longer be using [`FeaturedCollectionCard`](https://github.com/mozilla/addons-frontend/tree/master/src/amo/components/FeaturedCollectionCard) in code, so we might as well delete it.

**Comment by NegiAkash890** [comment]
Hi @bobsilverberg can I work on this issue?

**Comment by bobsilverberg** [comment]
@NegiAkash890 You may, but note that this change cannot land until the PR at #10065 lands, so it probably makes sense to wait for that, otherwise you'll end up with some failing tests.

**Comment by eviljeff** [comment]
#10065 has been merged, I note.

**Comment by ioanarusiczki** [comment]
verified on AMO stage - FF88(Win10)
