### ISSUE TITLE
WebExtension uploading takes a very long time and eventually fails

### ISSUE THREAD

**Issue by nodeticswww** [mozilla/addons-frontend#10231]
### Describe the problem and steps to reproduce it:

I'm trying to upload a new version of one of our WebExtensions to AMO on page
https://addons.mozilla.org/en-GB/developers/addon/pageprobe/versions/submit/

### What happened?

After selecting the file the upload takes a loooooong time (2-3 minutes, uploading about 20 kB/s) and finally fails with error:

Your add-on failed validation with 1 error.
    Received an empty response from the server; status: 504

I have 100 Mbit/s fiber optic internet connection.

**Comment by nodeticswww** [comment]
Now the upload succeeded. Perhaps it was a temporary glitch or someone managed to fix it quickly.

**Comment by willdurand** [comment]
Probably a glitch, sorry about that!
