### ISSUE TITLE
Resize the themes on homepage shelves

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10249]
As discussed : https://github.com/mozilla/addons-server/issues/16704#issuecomment-802880932

STR:
1. Load the homepage with only 2 themes available on a shelf - the recommended shelf 

![olny 2 themes available](https://user-images.githubusercontent.com/33448286/111996093-58ce5c00-8b22-11eb-8c12-1cc25f1a2ca5.png)

Expected result:
Themes should always be displayed at ~370x48 (as they are in the themes page https://addons-dev.allizom.org/en-US/firefox/themes/)

Actual result:
theme icons have a dimension of ~593x76

**Comment by willdurand** [comment]
@eviljeff can you add some labels/priority to this issue please?

**Comment by eviljeff** [comment]
having only 2 theme recommendations seems like an edge case so marking down priority.

**Comment by Krishnaraj-shankar** [comment]
Where can I find the folder in cloned code.Im a beginner

**Comment by eviljeff** [comment]
> 
> 
> Where can I find the folder in cloned code.Im a beginner

I'm not clear what folder you're talking about.  In any case, debugging setup problems isn't practical via github issues - come speak to us on https://chat.mozilla.org/ in the AMO room.

**Comment by eviljeff** [comment]
I think this is just a css fix

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg

**Comment by Krishnaraj-shankar** [comment]
@caitmuenster  yes It is my first contribution..

**Comment by FuryACE007** [comment]
Hi, how can I reproduce this bug on my local machine? I am a beginner, please point me in the right direction..

**Comment by FuryACE007** [comment]
Hii, I was trying to set up my pc for working on firefox bugs, and I am getting this error
![Screenshot 2021-11-02 142419](https://user-images.githubusercontent.com/66339967/139816299-18d43118-07bc-4785-8a5d-9371e61682a7.jpg)
Please guide me on how to deal with this issue..

**Comment by eviljeff** [comment]
> Hii, I was trying to set up my pc for working on firefox bugs, and I am getting this error 

That looks like you're trying to build Firefox itself.  This issue is for the web frontend to the add-ons website - you don't need to build Firefox to reproduce it or contribute a fix.  See https://github.com/mozilla/addons-frontend#readme for installation instructions.  In general, github issues are an impractical way of debugging someone's setup problems - come talk to us on https://chat.mozilla.org in the AMO room.

**Comment by anantraghuvanshi** [comment]
Hey there,

**Comment by anantraghuvanshi** [comment]
Hey there, I have set up addon-frontend on the local computer and wanted to work on this issue, since it is still open. Also, I wanna ask if this is the correct place where we need to resize the theme shelve? 
![image](https://user-images.githubusercontent.com/43936308/149837101-d576347c-86f3-460a-be8e-03fdb4324c19.png)

or we need to resize it where my second picture points too? 

![image](https://user-images.githubusercontent.com/43936308/149837211-2e3c60a8-8564-4027-a94c-f673fdd52fcc.png)

**Comment by eviljeff** [comment]
@anantraghuvanshi it's just the shelves, where multiple theme preview images are displayed on the same line.

**Comment by anantraghuvanshi** [comment]
> @anantraghuvanshi it's just the shelves, where multiple theme preview images are displayed on the same line.

Thanks, @eviljeff  for that, so basically it's the first pic. Since I am a beginner I will get along with the code base and see if I could fix this CSS.

**Comment by eviljeff** [comment]
> > @anantraghuvanshi it's just the shelves, where multiple theme preview images are displayed on the same line.
> 
> Thanks, @eviljeff for that, so basically it's the first pic. Since I am a beginner I will get along with the code base and see if I could fix this CSS.

btw, you can probably replicate the shelve only having 2 themes but just editing the DOM in dev tools

**Comment by anantraghuvanshi** [comment]
> > > @anantraghuvanshi it's just the shelves, where multiple theme preview images are displayed on the same line.
> > 
> > 
> > Thanks, @eviljeff for that, so basically it's the first pic. Since I am a beginner I will get along with the code base and see if I could fix this CSS.
> 
> btw, you can probably replicate the shelf only having 2 themes but just editing the DOM in dev tools

So I tried to fix that in the console of my browser as what was mentioned earlier and got a similar result which was mentioned at the starting of this thread. Check if it was what was desired. 
![image](https://user-images.githubusercontent.com/43936308/150015911-381a5004-109c-457c-8202-efcaf74948ab.png)

**Comment by eviljeff** [comment]
I can't tell from a screenshot if it fixes the issue.  The issue description states the expected result.

**Comment by anantraghuvanshi** [comment]
> I can't tell from a screenshot if it fixes the issue. The issue description states the expected result.

I just meant to show if it is done in a similar way which was expected since I did all that in my console of the browser.

**Comment by janvi01** [comment]
is this issue availaible? @eviljeff

**Comment by janvi01** [comment]
is this issue available? @eviljeff

**Comment by PavanS04** [comment]
Can someone help me with how to start contribution as this is my first contribution?

**Comment by eviljeff** [comment]
Caitlin provided a link in her comment https://github.com/mozilla/addons-frontend/issues/10249#issuecomment-918350059

**Comment by Garimak1204** [comment]
hi, Is this bug still open. Can you assign it to me ? I would love to work on it.

**Comment by eviljeff** [comment]
> hi, Is this bug still open. Can you assign it to me ? I would love to work on it.

It's open.  Please open a pull request when you're ready and we will assign the issue to you once we merge it.

**Comment by Garimak1204** [comment]
Hi can you please tell which folder is the code regarding this issue placed as it is difficult to find the folder as so many folders are there.

**Comment by Garimak1204** [comment]
Hey can you please help me in getting started with this

**Comment by eviljeff** [comment]
> Hey can you please help me in getting started with this

Caitlin provided a link in her comment https://github.com/mozilla/addons-frontend/issues/10249#issuecomment-918350059

and I mentioned how you could replicate it easily locally https://github.com/mozilla/addons-frontend/issues/10249#issuecomment-1015481693

**Comment by curtag** [comment]
This is my first contribution. I have made a pull request (#11707) that meets the expected result.

**Comment by ioanarusiczki** [comment]
@eviljeff This is verified on AMO dev with FF102(Win10)

![theme size](https://user-images.githubusercontent.com/33448286/179480854-243c21a8-9321-43f7-8329-87e7e0021919.png)
