### ISSUE TITLE
Create callouts for the new Download Firefox button CTAs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10252]
For the experiment, the new CTAs will include callouts, which are elements which point to the existing buttons and draw the user's attention to them, from the Figma file at https://www.figma.com/file/7FnxRoHYpyEfMOIfob423s/Non-Firefox-Download?node-id=136%3A0:

![Screen Shot 2021-03-22 at 11 07 59 AM](https://user-images.githubusercontent.com/142755/112011719-e9934080-8afe-11eb-9815-f098a826dc8c.png)

![Screen Shot 2021-03-22 at 11 08 44 AM](https://user-images.githubusercontent.com/142755/112011804-00399780-8aff-11eb-9224-2b7222f7f131.png)

**Comment by bobsilverberg** [comment]
Some screenshots of what I have so far for the Add-on Detail Page button:

<details>
<summary>Large screen</summary>

Supports RTAMO:
![Screen Shot 2021-03-22 at 12 29 55 PM](https://user-images.githubusercontent.com/142755/112024206-56600800-8b0a-11eb-8d93-9968edfae45e.png)

Does not support RTAMO:
![Screen Shot 2021-03-22 at 12 27 23 PM](https://user-images.githubusercontent.com/142755/112024101-3b8d9380-8b0a-11eb-9b7b-f4b17d6a11d6.png)
</details>

<details>
<summary>Medium screen</summary>

Supports RTAMO:
![Screen Shot 2021-03-22 at 12 31 30 PM](https://user-images.githubusercontent.com/142755/112024433-91fad200-8b0a-11eb-92d8-c64aa17198e4.png)

Does not support RTAMO:
![Screen Shot 2021-03-22 at 12 32 28 PM](https://user-images.githubusercontent.com/142755/112024553-b35bbe00-8b0a-11eb-8350-047bb8d517bf.png)

</details>

<details>
<summary>Small screen</summary>

Supports RTAMO:
![Screen Shot 2021-03-22 at 12 34 41 PM](https://user-images.githubusercontent.com/142755/112024881-00d82b00-8b0b-11eb-9bca-c8406f10ee64.png)

Does not support RTAMO:
![Screen Shot 2021-03-22 at 12 33 50 PM](https://user-images.githubusercontent.com/142755/112024779-e7cf7a00-8b0a-11eb-8b54-46d6ceb1be99.png)

</details>

**Comment by bobsilverberg** [comment]
@jvillalobos @verdi and anyone else interested, I have added some screenshots of the callout above.

**Comment by bobsilverberg** [comment]
For the Download Firefox button in the header, at a larger screen sizes, the spec includes this:

![Screen Shot 2021-03-22 at 1 10 22 PM](https://user-images.githubusercontent.com/142755/112029789-fcfad780-8b0f-11eb-8c36-ae47c5132e24.png)

@verdi should I infer from that that the callout + download button are meant to be centered in the space that is available between the left side of the page and the beginning of the "Extension Workshop" link?

**Comment by willdurand** [comment]
> @Verdi should I infer from that that the callout + download button are meant to be centered in the space that is available between the left side of the page and the beginning of the "Extension Workshop" link?

During a meeting, I think I heard about this button/banner being left-aligned with the menu below (Explore)

**Comment by bobsilverberg** [comment]
@verdi / @jvillalobos The callout text for the button in the header says "You'll need Firefox to use these extensions and themes", and there is also an example with a smaller screen that just says "You'll need Firefox to use these extensions". Is the assumption that, if the user is visiting the mobile site, we would use the latter text, because themes are not currently supported on mobile?

**Comment by jvillalobos** [comment]
> Some screenshots of what I have so far for the Add-on Detail Page button

I know localization introduces a lot of variability, but maybe the yellow bubble should at least be as wide as the button, so they line up in many cases.

> Is the assumption that, if the user is visiting the mobile site, we would use the latter text, because themes are not currently supported on mobile?

I don't know if that was the original assumption behind it, but it makes sense to me, and it's also shorter.

**Comment by bobsilverberg** [comment]
In the smallest view of the samples, there is an issue: The "Download Firefox" button has been moved below the "Register or Log in" link. While this looks good with the callout, once a user logs in the "Register or Log in" link becomes a menu. This won't work very well with the "Download Firefox" button below it (the button will be in the way of the menu).

One way to address this, which would actually simplify things in other ways too, would be to only show the "Download Firefox" button to users who are not logged in. While I realize we don't want to limit the cases where we show this button to users, it seems reasonable to think that anyone who has a Firefox Account and was therefore able to log in, probably has Firefox already.

If we don't want to take that route then I think we need to think of another way of making this smallest screen work.

Existing screen:
![Screen Shot 2021-03-23 at 3 46 18 PM](https://user-images.githubusercontent.com/142755/112208621-f000e580-8bee-11eb-8f2c-0f5be14c258e.png)

Suggestion from the mocks:
![Screen Shot 2021-03-23 at 3 45 31 PM](https://user-images.githubusercontent.com/142755/112208552-de1f4280-8bee-11eb-9edc-d5ab473e3947.png)

cc @Verdi @jvillalobos

**Comment by jvillalobos** [comment]
> the button will be in the way of the menu

What does this mean? The button will appear on top of menu items?

**Comment by bobsilverberg** [comment]
> > the button will be in the way of the menu
> 
> What does this mean? The button will appear on top of menu items?

We could make it so that the menu appears over top of the button, when it's opened, but I still think that's a pretty bad experience.

**Comment by jvillalobos** [comment]
What's the bad experience? That the opened menu will cover the button? That doesn't seem to justify hiding the CTA for many users. Note that we know lots of users log in to the site for no discernible reason, so we don't really know if they're even Firefox users.

**Comment by bobsilverberg** [comment]
> What's the bad experience? That the opened menu will cover the button? That doesn't seem to justify hiding the CTA for many users. Note that we know lots of users log in to the site for no discernible reason, so we don't really know if they're even Firefox users.

I might have not been clear with my intentions. Removing the button for logged-in users was, imo, a last resort. I was thinking more of a different design, but I will try implementing what is suggested here, and we can see how it looks.

**Comment by bobsilverberg** [comment]
Some new screenshots for the add-on detail page:

Some screenshots of what I have so far for the Add-on Detail Page button:

<details>
<summary>RTAMO version</summary>

ExtraLarge:
![Screen Shot 2021-03-25 at 4 22 28 PM](https://user-images.githubusercontent.com/142755/112539363-4bfe7200-8d87-11eb-880b-0aa88c560b78.png)

Large:
![Screen Shot 2021-03-25 at 4 24 06 PM](https://user-images.githubusercontent.com/142755/112539458-67697d00-8d87-11eb-8d54-d62d9e5aa742.png)

Medium:
![Screen Shot 2021-03-25 at 4 23 06 PM](https://user-images.githubusercontent.com/142755/112539412-591b6100-8d87-11eb-92b5-ce07ead1cec3.png)

Small:
![Screen Shot 2021-03-25 at 4 24 23 PM](https://user-images.githubusercontent.com/142755/112539485-705a4e80-8d87-11eb-84bc-8670ed807a56.png)

ExtraLarge (theme):
![Screen Shot 2021-03-25 at 4 25 07 PM](https://user-images.githubusercontent.com/142755/112539733-bca58e80-8d87-11eb-8bb0-fb5110316fbd.png)
</details>

<details>
<summary>Non-RTAMO version</summary>

ExtraLarge:
![Screen Shot 2021-03-25 at 4 25 52 PM](https://user-images.githubusercontent.com/142755/112539826-d515a900-8d87-11eb-92f2-6deb28043729.png)

Large:
![Screen Shot 2021-03-25 at 4 26 50 PM](https://user-images.githubusercontent.com/142755/112539916-f4acd180-8d87-11eb-9d43-3d839476f4fb.png)

Medium:
![Screen Shot 2021-03-25 at 4 26 31 PM](https://user-images.githubusercontent.com/142755/112539882-e6f74c00-8d87-11eb-80a9-d645a8861176.png)

Small:
![Screen Shot 2021-03-25 at 4 27 31 PM](https://user-images.githubusercontent.com/142755/112539934-fb3b4900-8d87-11eb-8854-602efc9db5da.png)

ExtraLarge (theme):
![Screen Shot 2021-03-25 at 4 34 57 PM](https://user-images.githubusercontent.com/142755/112540017-127a3680-8d88-11eb-9868-5d83e92e89fb.png)
</details>

Please let me know what you think @jvillalobos and @Verdi

**Comment by bobsilverberg** [comment]
Here is the latest mock from @Verdi:

https://firefox.michaelverdi.com/amo-header-info/

**Comment by jvillalobos** [comment]
The screenshots look good to me!

**Comment by bobsilverberg** [comment]
@jvillalobos @Verdi Some screenshots for the new header banner:

Small:
![Screen Shot 2021-04-02 at 08 29 35](https://user-images.githubusercontent.com/142755/113294025-7fc82300-92c4-11eb-811b-c6293f37f17e.png)

Medium:
![Screen Shot 2021-04-02 at 08 32 27](https://user-images.githubusercontent.com/142755/113294313-d33a7100-92c4-11eb-8d90-6d37db26e950.png)

Large:
![Screen Shot 2021-04-02 at 08 32 01](https://user-images.githubusercontent.com/142755/113294248-c0c03780-92c4-11eb-82b6-18bb84a3aa67.png)

**Comment by bobsilverberg** [comment]
@jvillalobos and @Verdi, do we want to show the the header banner on the add-on detail page, which will also include the new callout pointing at the "Download Firefox" button, or should we exclude the header banner if we are on that page? As they both have different appearances (a big yellow banner vs. a light yellow callout) it might make sense to still show both of them on the detail page. WDYT?

**Comment by jvillalobos** [comment]
I think the idea is to only use the header banner on non-listing pages. If you're on a listing page and made the decision to get Firefox, odds are that you want it along with the add-on, so we want to encourage that flow.

**Comment by bobsilverberg** [comment]
Here are some screenshots of the most recent version of the add-on detail page button:

Small:
![Screen Shot 2021-04-09 at 12 12 02 PM](https://user-images.githubusercontent.com/142755/114209615-d371e680-992c-11eb-8f83-fddb6734e826.png)

Medium:
![Screen Shot 2021-04-09 at 12 12 45 PM](https://user-images.githubusercontent.com/142755/114209688-ebe20100-992c-11eb-9d33-e396a11d4a5f.png)

Large:
![Screen Shot 2021-04-09 at 12 13 57 PM](https://user-images.githubusercontent.com/142755/114209841-1633be80-992d-11eb-881b-4c9ee1529efe.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I checked on AMO dev - with Chrome

1. Detail page messages:

- Recommended addons: 

![recommended addons](https://user-images.githubusercontent.com/33448286/114683670-11706100-9cc5-11eb-89b0-701bd7a4a729.png)

- Recommended themes: 

![recommended themes](https://user-images.githubusercontent.com/33448286/114683761-25b45e00-9cc5-11eb-884b-07aea1a787a9.png)

- non -recommended extension:  - I'll file an issue, the medium and large size screens are affected 

![extension](https://user-images.githubusercontent.com/33448286/114689017-23083780-9cca-11eb-9c35-9f8ef3e5539a.png)

- non-recommended theme:

![themes](https://user-images.githubusercontent.com/33448286/114689382-7f6b5700-9cca-11eb-926a-28e40bf72a5c.png)

- Android small screen: - half of the add-ons logo is visible but I don't see it as an issue

![Android - Chrome](https://user-images.githubusercontent.com/33448286/114689824-f6085480-9cca-11eb-82b8-1347937a5abe.png)

2. The message on the other pages:

- If I dismiss the message and refresh the page the message reappears, I don't know if that's expected: 

![page refresh](https://user-images.githubusercontent.com/33448286/114691488-97dc7100-9ccc-11eb-9f25-7d8f0e90f1fc.gif)


- when I click "download Firefox URL" it will open https://www.mozilla.org/en-US/firefox/new/?utm_campaign=amo-fx-cta-new-cta&utm_content=banner-download-button&utm_medium=referral&utm_source=addons.mozilla.org in the same tab. If I navigate back the yellow message is still available, it can only be dismissed using "X".  I hope that's fine.

**Comment by bobsilverberg** [comment]
@ioanarusiczki Thanks for the feedback. I have addressed the issue mentioned above which was opened as #10375. The banner is behaving as expected. I don't think there are any other outstanding issues mentioned above, but correct me if I am wrong about that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I initially thought that after the banner is dismissed it should not re-appear back. I am sure that was happening at a full page reload, now I can't check it since the experiment is disabled. But then I realized the "download firefox" blue button is not available for the new cta group so this should be expected. Can you confirm?

**Comment by bobsilverberg** [comment]
> @bobsilverberg I initially thought that after the banner is dismissed it should not re-appear back. I am sure that was happening at a full page reload, now I can't check it since the experiment is disabled. But then I realized the "download firefox" blue button is not available for the new cta group so this should be expected. Can you confirm?

The banner is expected to come back after a reload. We only save the dismissed state in the redux store, and don’t persist it on disk.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Testing today a bit more on Android - small screen maybe as a UX is not quite ok when the banner overlaps the logo because that can be used for site navigation and now it's only partially visible. 

Also the search bar and Register or log in button are completely hidden in this case.

Let me know what you think of this. 

![Android - Chrome](https://user-images.githubusercontent.com/33448286/114689824-f6085480-9cca-11eb-82b8-1347937a5abe.png)

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. I think it’s fine because really we mostly expect people to either click on the link to download Firefox, or, if they really want to use the site, to dismiss the banner. The site isn’t particularly useful to someone on a mobile phone that isn’t Firefox. 

WDYT @jvillalobos @Verdi

**Comment by Verdi** [comment]
> Thanks @ioanarusiczki. I think it’s fine because really we mostly expect people to either click on the link to download Firefox, or, if they really want to use the site, to dismiss the banner. The site isn’t particularly useful to someone on a mobile phone that isn’t Firefox.
> 
> WDYT @jvillalobos @Verdi

Agreed. We designed it with this rationale.

**Comment by jvillalobos** [comment]
+1
