### ISSUE TITLE
Compatibility message for iOS users is incorrect on non-listing pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10253]
If you open the AMO homepage on iOS, you get this message: "This add-on is not compatible with this browser. Try installing it on Firefox for desktopn". It looks like we should have a different message for non-listing pages. It looks like it wasn't specified as part of https://github.com/mozilla/addons-frontend/issues/9177, so how about something like:

"Add-ons are not compatible with this Firefox for iOS. Try installing them on Firefox for desktop."

**Comment by bobsilverberg** [comment]
> If you open the AMO homepage on iOS, you get this message: "This add-on is not compatible with this browser. Try installing it on Firefox for desktopn". It looks like we should have a different message for non-listing pages. It looks like it wasn't specified as part of #9177, so how about something like:
> 
> "Add-ons are not compatible with this Firefox for iOS. Try installing them on Firefox for desktop."

Should that be "Add-ons are not compatible with Firefox for iOS." as opposed to "Add-ons are not compatible with *this* Firefox for iOS."?

**Comment by jvillalobos** [comment]
"Add-ons are not compatible with Firefox for iOS.", yes.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I've checked AMO dev on iOS - the new message is available on all pages, which I think it's expected.

![homepage on iOS](https://user-images.githubusercontent.com/33448286/112976889-14fcd780-915e-11eb-97be-0ebaea8ae0a1.jpg)
![the detail page on iOS](https://user-images.githubusercontent.com/33448286/112976911-1c23e580-915e-11eb-857e-e777b44dc678.jpg)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I filed a UX issue on iOS 
https://github.com/mozilla/addons-frontend/issues/10289
