### ISSUE TITLE
Hide Workshop and DevHub links for non-Firefox users

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10259]
As discussed in a meeting today, to make space for the new Download Firefox CTA, hide the links to Extension Workshop and Developer Hub for non-Firefox users.

This is only needed with the new CTA, which will be experimental to begin with, but our hopes are that it will have an impact and therefore be adopted. For this reason, I think we can implement this change now, as opposed to just for the experiment.

@jvillalobos WDYT?

**Comment by jvillalobos** [comment]
I'm okay with making this change now, with the observation that we will still have footer links for both, so those users will still have a way to reach those sites.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev with Chrome and Edge - Win10

![ew and dev hub removed](https://user-images.githubusercontent.com/33448286/112827220-e4744b00-9042-11eb-846b-44207eb96232.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg this should be with a 08.04.2021 milestone
