### ISSUE TITLE
Problem with the "Register or Log in" button at 900px in German

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10258]
I discovered this when working on #10254. The "Register or Log in" gets bumped down to a new line at `900px` in German. Doing a bit more testing, this seems to only be a problem from `900px` - `904px`, and fixes itself at `905px`, so I guess it's not much of an issue. I imagine we could find problems like these at boundaries in a number of different languages, so perhaps this should just be a wontfix, but as I observed it I figured I should report it.

WDYT @mozilla/addons-engineering @jvillalobos 

![Screen Shot 2021-03-23 at 10 45 53 AM](https://user-images.githubusercontent.com/142755/112165267-f8442b00-8bc4-11eb-82b3-f7e249e3a558.png)

**Comment by jvillalobos** [comment]
This can be impacted by https://github.com/mozilla/addons-frontend/issues/10163, assuming that changes its width. That said, what's the expected behavior? Everything on a single line, or the EW and DevHub links going away so everything else fits in a single line?

**Comment by bobsilverberg** [comment]
I'm not sure what the expectation is, that's why I asked. 😉 

As mentioned above, we can likely find lots of these cases where things don't quite fit near a breakpoint in different languages, so I'm not sure it's something we should even try to fix, or we might end up with a never ending game of whack-a-mole.

**Comment by jvillalobos** [comment]
German is a pretty important locale, so I'd like to fix this particular glitch (if it continues after the change to a link). What I was getting towards with my previous question is whether we have some kind of spec that explains what things are flexed and removed at what sizes, which dictate what to expect in these situations.

**Comment by bobsilverberg** [comment]
> German is a pretty important locale, so I'd like to fix this particular glitch (if it continues after the change to a link). What I was getting towards with my previous question is whether we have some kind of spec that explains what things are flexed and removed at what sizes, which dictate what to expect in these situations.

This is a good question. I have never seen a spec about this. There are some rules in code about what changes position and/or gets hidden at different screen resolutions, but, as far as I know, the reasons for those rules are not documented anywhere. I think we should verify that our current breakpoints actually make sense, as I have been encountering quite a few issues around the breakpoint bounadires, and I am wondering if some of these have to do with us bumping up our font sizes. I'll add this as a discussion item for the UX meeting.

**Comment by bobsilverberg** [comment]
Some changes to the header and buttons have made this problem go away. Here's the current screen at 900px:

![Screen Shot 2021-05-06 at 1 08 57 PM](https://user-images.githubusercontent.com/142755/117338229-5161d880-ae6c-11eb-9ba8-586821668239.png)
