### ISSUE TITLE
Enable TLS 1.3 to reduce latency

### ISSUE THREAD

**Issue by rik** [mozilla/addons-frontend#10263]
addons.mozilla.org [does not support TLS 1.3](https://www.wormly.com/test_ssl/h/addons.mozilla.org/i/34.210.16.75/p/443). TLS 1.3 handshake only needs one round trip when TLS 1.2 requires two. Enabling this would therefore reduce Time To First Byte.

This will have less impact than https://github.com/mozilla/addons-frontend/issues/10194#issuecomment-800222271. But it would be still be quite noticeable.

For completeness, [addons-amo.cdn.mozilla.net report](https://www.wormly.com/test_ssl/h/addons-amo.cdn.mozilla.net/i/13.32.204.120/p/443) and [addons.cdn.mozilla.net report](https://www.wormly.com/test_ssl/h/addons.cdn.mozilla.net/i/13.249.39.63/p/443). They are using TLS 1.3 so that's alright.

See also [Mozilla's recommended TLS configurations](https://wiki.mozilla.org/Security/Server_Side_TLS) for the security aspects.

**Comment by diox** [comment]
Command line STR:
`% curl -s --tlsv1.3 https://addons.mozilla.org/ -I -v`

Expected:
A bunch of info about the connection then HTTP headers are returned

Actual:
A handshake failure is returned

**Comment by diox** [comment]
TLS 1.3 isn't supported by AWS ELB/ALB at the moment. We'll get it once we switch away from that, but it's a long-term thing, wontfxing for now.
