### ISSUE TITLE
Do not lazy load images that are likely to be in the viewport

### ISSUE THREAD

**Issue by rik** [mozilla/addons-frontend#10266]
When you use `<img loading="lazy">`, browsers need to know the position of that image to determine if it is in the viewport or close enough. The position of an image is only known after the layout phase (also sometimes called render). To compute the layout, they need to have downloaded and parsed all CSS.

Images without a `loading` attribute (or `loading="eager"`) can be downloaded sooner, while parsing the HTML. Therefore, important images (like the ones that might be the Largest Contentful Paint) should not be marked for lazy downloading.

With many possible viewports, it is not possible to get this 100% right. My recommendation would be to avoid `loading="lazy"` for the images that are visible in the biggest viewport you support.

I noticed this while looking at https://github.com/mozilla/addons-frontend/pull/10247. But it would also be applicable to the previews on the addon/theme detail page.

**Comment by diox** [comment]
Let's remove all lazy loading for this week, and then figure out if it's worth to try to be smarter about this depending on the context and only apply it after x images in the list or something.

**Comment by ioanarusiczki** [comment]
@diox What's been added to https://github.com/mozilla/addons-frontend/issues/10246#issuecomment-805896637 and https://github.com/mozilla/addons-frontend/issues/10094#issuecomment-797490142 is no longer available.
I verified on AMO dev and stage - FF87(Win10).
