### ISSUE TITLE
Revert change to default line-height, and use 1.2 instead

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10260]
This contributed to a number of minor UX glitches, as reported at https://github.com/mozilla/addons-frontend/issues/9078#issuecomment-805006220.

**Comment by bobsilverberg** [comment]
This addresses the following issues discussed at https://github.com/mozilla/addons-frontend/issues/9078#issuecomment-805006220:

this was before - the "y", "g" look truncated a bit but the menu is aligned:

![before](https://user-images.githubusercontent.com/33448286/112167443-20e61800-8bf9-11eb-821a-0c010a1b87a2.png)

now the user name seems to stand a bit higher:

![now](https://user-images.githubusercontent.com/33448286/112167829-6f93b200-8bf9-11eb-9882-deae1eb075e4.png)

- some elements don't look aligned:
"✓" with the message when adding an addon to a collection
![collection card from detail page](https://user-images.githubusercontent.com/33448286/112169351-cb126f80-8bfa-11eb-9171-3b6eae41a91d.png)
"!" into the site notice:

![warnings](https://user-images.githubusercontent.com/33448286/112169719-1e84bd80-8bfb-11eb-81d0-335331f3638c.png)

icons in the autocomplete results:

![autocomplete](https://user-images.githubusercontent.com/33448286/112169835-365c4180-8bfb-11eb-9f7d-070ff6a5522a.png)

**Comment by willdurand** [comment]
For the future AMO team: we use `1.2` because it's roughly equivalent to what we were using before, except that we were using a value in... pixels, which we tried to avoid. We should preferably set `line-height` using a unitless value.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Results on dev or stage - FF87(Win10):

1. I think these look good again:

![collection check mark is fixed](https://user-images.githubusercontent.com/33448286/112307193-534f4e00-8ca9-11eb-8dfb-baf777d3ce2f.png)

![warning messages fixed](https://user-images.githubusercontent.com/33448286/112307211-59452f00-8ca9-11eb-8eef-c7bbfe358989.png)

2. Icons in autocomplete - should be fine, checking multiple times, I see that it also depends on the shape of the icon, so I'm leaving here 2 examples:

![icons fixed](https://user-images.githubusercontent.com/33448286/112307515-b7721200-8ca9-11eb-818d-bebd5c9646f7.png)
![icons fixed2](https://user-images.githubusercontent.com/33448286/112307531-bb9e2f80-8ca9-11eb-94f4-2938a556087b.png)

3. Display name is now aligned but the "y" and "g" look truncated (similar with what's now in production with font of 12px)

![sample one](https://user-images.githubusercontent.com/33448286/112308226-93630080-8caa-11eb-8236-d0f1f8e4a872.png)

![sample2](https://user-images.githubusercontent.com/33448286/112308233-96f68780-8caa-11eb-8df6-a3ae93f8b041.png)

this is at 12 px:

![before](https://user-images.githubusercontent.com/33448286/112308613-01a7c300-8cab-11eb-8f31-6b704301e7e0.png)
