### ISSUE TITLE
Some layout issues should be fixed as a result of increased font size

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10264]
Some layout issues should be fixed as a result of increasing the font-size, it was discussed in https://github.com/mozilla/addons-frontend/issues/9078#issuecomment-805075678

1. The Register or Log in - seems to stand a bit higher than EW and Dev Hub in the header - font-size at 11px

Before increasing the font sizes:

![log out before](https://user-images.githubusercontent.com/33448286/112276329-47539400-8c89-11eb-9273-351775c4985f.png)

Now:
![log out now](https://user-images.githubusercontent.com/33448286/112276348-4e7aa200-8c89-11eb-8816-6ee27ef1e350.png)

"Download Firefox" on Chrome is at 11 px too:

![Download Firefox](https://user-images.githubusercontent.com/33448286/112277298-4b33e600-8c8a-11eb-9177-d8629837a483.png)

2.  At the footer of the page there's a 18px "Add-ons" then "Browsers" and "Products" is at 16 px

![footer](https://user-images.githubusercontent.com/33448286/112276685-af09df00-8c89-11eb-90ce-92643f056722.png)

3. edit user profile page has some 10 px font which looks very small in contrast with the increased fonts

![edit profile page](https://user-images.githubusercontent.com/33448286/112276855-d82a6f80-8c89-11eb-8fa5-4560ea109075.png)

**Comment by championshuttler** [comment]
I think first issue will be fixed by #10210, rest needs to be confirmed, I can take a stab once someone confirms it :)

**Comment by AlexandraMoga** [comment]
Adding to what was mentioned above, there are some font size inconsistencies on the language tools page and on the blocked-addon page - i.e. some headers are still at 12px:

[blocked-addon]
![image](https://user-images.githubusercontent.com/31961530/112339290-324a2580-8cc8-11eb-8c60-54779da136e1.png)

[language-tools]
![image](https://user-images.githubusercontent.com/31961530/112339389-47bf4f80-8cc8-11eb-9897-0900f41d2d63.png)

**Comment by bobsilverberg** [comment]
Some of these should be addressed by https://github.com/mozilla/addons-frontend/issues/10250.

**Comment by bobsilverberg** [comment]
> Some layout issues should be fixed as a result of increasing the font-size, it was discussed in [#9078 (comment)](https://github.com/mozilla/addons-frontend/issues/9078#issuecomment-805075678)
> 
> 1. The Register or Log in - seems to stand a bit higher than EW and Dev Hub in the header - font-size at 11px
> 
> Before increasing the font sizes:
> 
> ![log out before](https://user-images.githubusercontent.com/33448286/112276329-47539400-8c89-11eb-9273-351775c4985f.png)
> 
> Now:
> ![log out now](https://user-images.githubusercontent.com/33448286/112276348-4e7aa200-8c89-11eb-8816-6ee27ef1e350.png)
> 

I believe this is now fixed.

> "Download Firefox" on Chrome is at 11 px too:
> 
> ![Download Firefox](https://user-images.githubusercontent.com/33448286/112277298-4b33e600-8c8a-11eb-9177-d8629837a483.png)
>

This should be fixed by https://github.com/mozilla/addons-frontend/pull/10539.
 
> 1. At the footer of the page there's a 18px "Add-ons" then "Browsers" and "Products" is at 16 px 
> 
> ![footer](https://user-images.githubusercontent.com/33448286/112276685-af09df00-8c89-11eb-90ce-92643f056722.png)
> 

This should be fixed by https://github.com/mozilla/addons-frontend/pull/10539.

> 1. edit user profile page has some 10 px font which looks very small in contrast with the increased fonts 
> 
> ![edit profile page](https://user-images.githubusercontent.com/33448286/112276855-d82a6f80-8c89-11eb-8fa5-4560ea109075.png)

This should be fixed by https://github.com/mozilla/addons-frontend/pull/10539.

**Comment by bobsilverberg** [comment]
> Adding to what was mentioned above, there are some font size inconsistencies on the language tools page and on the blocked-addon page - i.e. some headers are still at 12px:
> 
> [blocked-addon]
> ![image](https://user-images.githubusercontent.com/31961530/112339290-324a2580-8cc8-11eb-8c60-54779da136e1.png)
> 
> [language-tools]
> ![image](https://user-images.githubusercontent.com/31961530/112339389-47bf4f80-8cc8-11eb-9897-0900f41d2d63.png)

These should both be fixed by https://github.com/mozilla/addons-frontend/pull/10539

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- font-size was increased to 12 px (from 11px) for buttons like "Log in to rate this extension" or when logging to see collections or profile pages

![at 12 px](https://user-images.githubusercontent.com/33448286/117815345-0b42b580-b26e-11eb-8613-65f3d8beb967.png)

- footer-links-header font-size:18 px each, and footer links at 18 px (from 16 px) I hope that's the expected.

![new footer](https://user-images.githubusercontent.com/33448286/117816272-04687280-b26f-11eb-93df-d3711e512264.png)

- edit user profile 10 px small text was increased to 12px
- yellow lines (card-contents) from https://github.com/mozilla/addons-frontend/issues/10264#issuecomment-833546623 were increased to 18 px. The card-headers were left at 16 px (for the block and language tool pages) If that should be different - let me know and I'll file a followup. 

![a block page](https://user-images.githubusercontent.com/33448286/117816985-cddf2780-b26f-11eb-8b70-9f35fc396c11.png)
