### ISSUE TITLE
Install button available on Fenix, but not working (confusing UX)

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-frontend#10270]
### Describe the problem and steps to reproduce it:

When an add-on has been marked as compatible with Android (checkbox), then the "Install" button is visually available (dark blue instead of soft blue). When the button is clicked, Fenix opens the recommended add-on list instead of installing the add-on. This seems to only happen with add-ons in the Recommended Extensions program; other add-ons that had been marked as compatible with Android don't have the same behavior.
Related bug: https://github.com/mozilla-mobile/fenix/issues/18511

STR:
1. Visit https://addons.mozilla.org/en-US/android/addon/dont-track-me-google1/versions/ on mobile
2. Click on the "Add to Firefox" button at version 2.24 or earlier. For these versions I've marked the add-on as compatible with Android, because the add-on is. In the last version I unchecked it because the add-on cannot be installed due to it not being part of the Fenix collection, and I received multiple emails and reviews from users who were wondering why they were not able to install the add-on.

### What happened?
- The add-on is not installed. The "Add-ons manager" appeared, but I don't see the add-on in the list of add-ons.

### What did you expect to happen?
- The add-on should be installable. If it is not, then AMO should disable the "Add to Firefox" button.

### Anything else we should know?

Related bug: https://github.com/mozilla-mobile/fenix/issues/18511

**Comment by jvillalobos** [comment]
The expected behavior in this case is that all install buttons should be disabled, given the add-on is not part of the "Recommended for Android" group. This includes buttons in the "All Versions" page, which is what's in the STR.

**Comment by Rob--W** [comment]
In this STR the button at the install page is not clickable, but according to https://github.com/mozilla-mobile/fenix/issues/18511 (when the last version of the add-on was marked as "compatible with Android").

**Comment by willdurand** [comment]
We should get rid of all these install butons on the "all versions" page tbh..

**Comment by jvillalobos** [comment]
So, let's fix https://github.com/mozilla/addons-frontend/issues/9811 then :)

**Comment by bobsilverberg** [comment]
There is a PR currently open for #9811, which will hopefully be ready to land soon. Is that the only change needed for this issue, or is it about something more than that?

**Comment by Rob--W** [comment]
This issue also happens on the add-on detail page, not just versions, see earlier comment that references the issue on the issue tracker of Fenix.

**Comment by willdurand** [comment]
> This issue also happens on the add-on detail page, not just versions, see earlier comment that references the issue on the issue tracker of Fenix.

I don't quite get the issue on the add-on detail page. We use the recommended list on AMO to determine whether an add-on can be installed on Fenix, this list and the "Fenix collection" should be the same. The only problem I could see is that, when you uploaded the latest version, the add-on was automatically removed from the recommended list but not immediately from the collection?

The Fenix team should use the recommended list eventually. I cannot find the bug but they should rely on AMO collections and the recommendation was to use the search endpoint, and therefore, the "recommended list".

**Comment by Rob--W** [comment]
There is the recommended extension program and the Fenix collection. Apparently the install button relies on the recommended extension program (list of recommended add-ons), but it may be out of sync with the Fenix collection.

**Comment by willdurand** [comment]
Yeah, that's what I think too, but maybe @diox can confirm that the recommended list is updated automatically (I know the special collection for Fenix isn't). I think we should be more careful about which extensions get "allowed" on Fenix but ultimately this is a Fenix bug because they don't rely on the right tool (i.e. API endpoint).

**Comment by bobsilverberg** [comment]
What you have both said above is correct. AMO uses the data about the add-on (whether it is recommended for android) to determine if it is available or not. We don't use the collection at all. This is a Fenix issue.

**Comment by Rob--W** [comment]
The "recommended for Fenix" part is controlled by the add-on author who is part of the recommended extension program. In contrast, the Fenix collection is curated.

If Fenix still wants to fully curate the list, then it's a bug that the add-on developers can mark their add-on as compatible with Android/Fenix, because that option allows third parties to enable themselves on Fenix.

**Comment by bobsilverberg** [comment]
Actually, I think something else is going on. This add-on *is* marked as recommended on android, so something else is making AMO think it is incompatible. I believe it is the fact that the add-on is not marked as compatible with android at all (in its compatibility data, as opposed to its promoted data).

**Comment by bobsilverberg** [comment]
> The "recommended for Fenix" part is controlled by the add-on author who is part of the recommended extension program. In contrast, the Fenix collection is curated.
> 
> If Fenix still wants to fully curate the list, then it's a bug that the add-on developers can mark their add-on as compatible with Android/Fenix, because that option allows third parties to enable themselves on Fenix.

Our comments collided 😄 

There are actually 2 pieces of metadata in play:

1. Compatibility, which, as you mention, is controlled by the developer.
2. Promoted status, which can only be controlled by us.

An add-on must be both marked as compatible *and* as recommended in order for AMO to see it as available for download on android.

**Comment by Rob--W** [comment]
> > The "recommended for Fenix" part is controlled by the add-on author who is part of the recommended extension program. In contrast, the Fenix collection is curated.
> > 
> 
> The first part of this is incorrect. An add-on author cannot set their add-on as recommended. They can only control its compatibility data.

The comment is correct, and your statement is too. I specifically mentioned "add-on author who is part of the recommended extension program". This is controlled by us, but being recommended on desktop should not automatically grant the ability to be enabled on mobile.

> > If Fenix still wants to fully curate the list, then it's a bug that the add-on developers can mark their add-on as compatible with Android/Fenix, because that option allows third parties to enable themselves on Fenix.
> 
> Our comments collided 😄 
> 
> There are actually 2 pieces of metadata in play:
> 
> 1. Compatibility, which, as you mention, is controlled by the developer.
> 2. Promoted status, which can only be controlled by us.
> 
> An add-on must be both marked as compatible *and* as recommended in order for AMO to see it as available for download on android.

Yep. 1 is controlled by add-on authors, from the set of add-ons matching category 2. The bug is that the set of "enabled add-ons on Fenix (from AMO's perspective)" is not strictly limited to the curated set of add-ons (which is a subset of 2/promoted add-ons).

**Comment by bobsilverberg** [comment]
> > > The "recommended for Fenix" part is controlled by the add-on author who is part of the recommended extension program. In contrast, the Fenix collection is curated.
> > 
> > 
> > The first part of this is incorrect. An add-on author cannot set their add-on as recommended. They can only control its compatibility data.
> 
> The comment is correct, and your statement is too. I specifically mentioned "add-on author who is part of the recommended extension program". This is controlled by us, but being recommended on desktop should not automatically grant the ability to be enabled on mobile.
> 

I must provide another correction. 😄 

The set of add-ons recommended on desktop is separate from the set recommended on android. We control both sets and they do not necessarily contain the same sets of add-ons.

> > > If Fenix still wants to fully curate the list, then it's a bug that the add-on developers can mark their add-on as compatible with Android/Fenix, because that option allows third parties to enable themselves on Fenix.
> > 
> > 
> > Our comments collided 😄
> > There are actually 2 pieces of metadata in play:
> > 
> > 1. Compatibility, which, as you mention, is controlled by the developer.
> > 2. Promoted status, which can only be controlled by us.
> > 
> > An add-on must be both marked as compatible _and_ as recommended in order for AMO to see it as available for download on android.
> 
> Yep. 1 is controlled by add-on authors, from the set of add-ons matching category 2. The bug is that the set of "enabled add-ons on Fenix (from AMO's perspective)" is not strictly limited to the curated set of add-ons (which is a subset of 2/promoted add-ons).

I'm finding that a bit difficult to parse, but I don't think it's accurate. As mentioned above, there are two distinct sets of recommended add-ons: one for desktop and one for android.

**Comment by Rob--W** [comment]
The user from the Fenix bug reported that they observed my add-on in the search results. I didn't see it myself, because I saw the issue only a few days later.

I can also see that the install button of older versions are clickable.

After I unchecked the Compatible for Android option, I can confirm that it's no longer in the search results, and not installable either.

If the sets are separate, I wouldn't be surprised if the add-on is recommended for Android, because I vaguely recall mentioning to Scott that it works on Android.

I guess that you can check if the add-on was curated from AMO's perspective (maybe by Scott?) and if it is, ir would explain my observations.

**Comment by jvillalobos** [comment]
Here's where I think we are with this:
* Don't Track Me Google is currently in Recommended for Android.
* It is currently _not_ on the [latest compatibility collection](https://addons.mozilla.org/collections/4757633/7dfae8669acc4312a65e8ba5553036/), unless I'm looking at the wrong one.
* All recent versions except for the latest one are marked as compatible with Android.

As far as I can tell, AMO is doing the right thing given the current state of the data. Fenix is probably also doing the right thing, if I'm correct about the collection. So, either the Recommended group is wrong or the collection is wrong (cc @devaneymoz). That the latest version is marked as incompatible is introducing complexity to the whole scenario, but I don't see a bug there. I suggest @Rob--W reverts this.

**Comment by devaneymoz** [comment]
I just adjusted Don't Track Me Google's state in the AMO admin so it should not show as Recommended for Android.

**Comment by Rob--W** [comment]
Thanks, that should resolve this issue. I'd rather be able to use the add-on on mobile, but given the limited capacity I understand that it's not always an option.
