### ISSUE TITLE
Long strings break the layout of the homepage/detail pages on iOS

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10289]
I've noticed that long unbroken strings for addon names don't look good - on FF for iOS 

![looks truncated on iOS](https://user-images.githubusercontent.com/33448286/112977236-7a50c880-915e-11eb-97f8-5b19e1572413.jpg)

![detail page on iOS](https://user-images.githubusercontent.com/33448286/112977253-7e7ce600-915e-11eb-86ac-088f8730e266.jpg)

**Comment by championshuttler** [comment]
I checked `word-break: break-all;` could trick for us here ;)

**Comment by willdurand** [comment]
@championshuttler re: this bug, we could probably fix it like this: https://github.com/mozilla/addons-blog/issues/108

**Comment by ioanarusiczki** [comment]
@championshuttler 
@willdurand 

On AMO dev I see the following:
- on the detail pages the issue is no longer reproducible on iOS 

- on homepage long unbroken strings break the layout of the page on iOS and that's because the page for https://addons-dev.allizom.org/en-US/firefox/ . Also on Android with Chrome the issue is reproducible. On the other hand the android page can be accessed with https://addons-dev.allizom.org/en-US/android/. If I check the android URL on all platforms and browsers it looks optimized for small screens and these issues are not reproducible. 

Hero Shelves - on Android with Chrome when accessing https://addons-dev.allizom.org/en-US/firefox/ - issue reproducible on iOS with Safari and FF

![Android ff page](https://user-images.githubusercontent.com/33448286/115023653-c2dee480-9ec7-11eb-9e5f-2f67b0c9ceb2.png)

![ioS issue](https://user-images.githubusercontent.com/33448286/115028439-87471900-9ecd-11eb-86b1-f51d31f35b66.jpg)


If this must be fixed for iOS I'll file an issue. Let me know.

**Comment by willdurand** [comment]
right,  I also noticed that it does not work for all cases, especially not long unbroken strings... @championshuttler suggested a different CSS rule but we'd like to avoid it because we don't want to different yet similar rules. Maybe we could have some sort of media query to detect Safari? I am not sure, though (I think it requires some js)

**Comment by championshuttler** [comment]
> Maybe we could have some sort of media query to detect Safari? I am not sure, though (I think it requires some js)

@willdurand you suggesting using media query for safari with `word-break: break-all;` ;) 

Though do we have any real addons with unbroken strings in their title, William could you confirm?

**Comment by willdurand** [comment]
> Though do we have any real addons with unbroken strings in their title, William could you confirm?

I don't think so but it's up to the users.
