### ISSUE TITLE
Issue with experiment enrollment events and SSR

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10296]
When we enroll a new user in an experiment, we sent an event to GA to record the fact. If a page that contains an experiment is the first page that a user lands on, then all (well, most) of the code to render the page runs on the server. We cannot send a GA event from the server, hence this issue.

We want to do all of the experiment processing on the server (i.e., determining the variant for the user and setting the cookie) because if we defer that to the client then we will end up with a flash of content as the page adjusts to the user's variant. 

Therefore, we need a way to either:
1. Send the GA event from the server, or
2. Send the GA event from the client, after the page has been rendered.

The former is likely fragile, as I don't think there are any supported libraries for doing this, and issuing our own requests to the GA API doesn't seem like a great idea.

For the latter, we could store some data in state on the server and then read that data on the client. To make that work we'd need a couple of things:
1. A way to ensure that reading and sending code only runs on the client. We could possibly use `componentDidMount` for that, or `config.get('server')`, and I imagine there are other possibilities as well.
2. We'd need to have the code in a path somewhere that is guaranteed to be executed on the client, even if the whole page is rendered on the server. It seems like both `componentDid...` methods, as well as `render` execute on the client in that case, but I'd want to double check that.

At this point it looks like we only need this for the experiment enrollment event, but we might want to consider building something generic where we could queue up events on the server and have them called on the client, if there are other/future cases where we need this.

@willdurand WDYT?

**Comment by bobsilverberg** [comment]
For QA:

There isn't a way to test this without an enabled experiment, but we do plan to land a patch that enables an experiment this week as well. Assuming that that patch also lands, here's the expected behaviour:

When a user first encounters a page with an experiment enabled, if they do not already have the experiment defined in the cookie (which is called `frontend_active_experiments`), then an enrollment event should be sent to GA indicating that the user was enrolled in the experiment, and including the variant.

Prior to this patch, this enrollment event was not sent to GA if the page was the first page loaded for the site - it only worked when the page on which the user was enrolled was reached by client-side navigation.

With this patch in place, we should *always* see an enrollment event sent to GA for the user, regardless of whether it is the first page they visit or not.

One way to test this is to delete the `frontend_active_experiments` cookie and refresh the page. You should see an enrollment event sent. If the cookie already has a value for the experiment, you should not see an enrollment event sent.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Reading from [the patch](https://github.com/mozilla/addons-frontend/pull/10333) this is an experiment for non FF browsers. 

For now I tried with Chrome and Edge - I navigated from the hompepage to a detail page but I don't see a cookie called `frontend_active_experiments`. Perhaps I must wait for the patch to land. 

![cookies](https://user-images.githubusercontent.com/33448286/114541438-972fd600-9c0b-11eb-97d5-4a5f9a66bccf.png)

**Comment by bobsilverberg** [comment]
@ioanarusiczki This did need to wait for the other patch to land to be tested, but I just merged it, so hopefully it will be on dev soon, and both will be testable.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I checked with Chrome - every time I delete the cookie and refresh a page I was on I get the enrollment event:

`[GA: ON] sendEvent: {hitType: "event", eventCategory: "AMO Experiment Enrollment - 20210404_download_cta_experiment", eventAction: "new-cta", eventLabel: undefined, eventValue: undefined}`

This is a one time event - until I delete again the cookie.

**Comment by bobsilverberg** [comment]
That's great, thanks @ioanarusiczki. One more thing to check is whether the data is actually sent to GA. That message you see in the console means we attempted to send it, but this patch fixes an issue where we were not successful in actually sending it.  You can check the network tab for a POST to https://www.google-analytics.com/collect, and if you check the Request payload you should see the enrollment event.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Alright, I'll be on the whole experiment tomorrow morning, I'll check it 👍

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
POST to  https://www.google-analytics.com/collect is present in the Network. 

The enrollment event in the request payload:

![enrollment event in request payload](https://user-images.githubusercontent.com/33448286/114674537-2f859380-9cbc-11eb-8453-fb0066c20aaa.png)
