### ISSUE TITLE
Expose `buildStaticAddonCard` in `addons-frontend-blog-utils`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10297]
Once we have the library set up, we'll need a function to build a static add-on card.

**Comment by ioanarusiczki** [comment]
@willdurand Is this a qa not needed?

**Comment by willdurand** [comment]
> @willdurand Is this a qa not needed?

Yes, we'll use https://github.com/mozilla/addons-blog to verify stuff related to this "blog-utils" library.
