### ISSUE TITLE
Investigate improvements around nginx cache key 

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10291]
The frontend pages are now cached by nginx following https://github.com/mozilla/addons-frontend/issues/10116.

We added `$http_user_agent` to the cache key in https://bugzilla.mozilla.org/show_bug.cgi?id=1701649, because we have the `userAgent` in the redux state, and use that to show different banners/download buttons to non-Firefox users. Even just for Firefox itself, we need our pages to distinguish between different versions to only allow installing compatible add-ons, and also need to distinguish between mobile and desktop.

A few things we want to look at:
- Is the cache hit good enough with the full UA in there ?
- Could and should we be smarter about the logic ? Extract what we need (is firefox, is mobile, firefox version, etc) It would likely mean more logic in the nginx config though
- On the flip side of this, if we don't do a smarter key, there is an alternate way of telling nginx to depend on the full UA: setting the `Vary` header ourselves in addons-frontend. That would simplify the nginx config.

**Comment by bobsilverberg** [comment]
Note that we also discussed adding the contents of the experiments cookie to the cache key, in order to allow experiments to work with caching. See https://github.com/mozilla/addons-frontend/issues/10188 for details.

**Comment by diox** [comment]
Short update:

> Is the cache hit good enough with the full UA in there ?

We still don't have good data on this :(

> Could and should we be smarter about the logic ? Extract what we need (is firefox, is mobile, firefox version, etc) It would likely mean more logic in the nginx config though

We're trying to avoid having more logic in nginx, so we're not pursuing this.

> On the flip side of this, if we don't do a smarter key, there is an alternate way of telling nginx to depend on the full UA: setting the `Vary` header ourselves in addons-frontend. That would simplify the nginx config.

The `Vary` on `User-Agent` was added to our frontend responses in https://github.com/mozilla/addons-frontend/issues/10381 so we can remove `$http_user_agent` from the nginx cache key, the `Vary` should ensure the cache depends on the user agent automatically.

**Comment by diox** [comment]
The underlying problem will remain with the switch to a CDN for caching, but ultimately any improvements at this point are going to have a significant cost in complexity, compounded by the fact that it will have to be done at the CDN config level. Wontfixing for now.
