### ISSUE TITLE
Investigate splitting fonts by unicode range

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10290]
https://github.com/mozilla/addons-frontend/issues/10040 had us switch to Inter and use variable fonts. For most pages, we load a single variable font that has all characters at all the weights we need, and if italics are used on the page, we load a second one for that.

Both fonts are around 230 KB. Maybe we could split them by unicode blocks as well: on most pages in many locales, we only need to display non-latin text if emoji or fancy unicode chars are used, so if we could load a single font that has all the latin alphabet + diacritic for that, it'd be smaller, resulting in a perf win for users on those pages.

Few things to think about:
- How deep do we want to go ? We could generate a bunch of different fonts each covering various popular languages if that's worth it.
- The language selector at the bottom of every page has a bunch of non latin text, so it would likely need to be rendered using a generic system sans-serif font for this to work.
- ~~At the moment in Chrome loading the font(s) doesn't affect LCP - except maybe from a bandwidth perspective~~

**Comment by eviljeff** [comment]
re: Italics.  We use italics _very_ sparingly on frontend - that I can see, only the `UsersUnsubscribe-content-notification` class, and developer defined content.  Using the variable font file is a net saving when we're using many different font weights; but it can be a net cost if we only use 1 or 2 - which we appear to, and not even on the same page - so we should perhaps switch italic back to single font files for italics.  

Also, we should consider dropping the use of italic in `UsersUnsubscribe-content-notification` (use bold or underline if necessary instead) so that use is eliminated.  Though I'm pretty sure that's only used on the logged in edit account profile page so also possibly a little to niche to care about.

**Comment by rik** [comment]
There's also the option of not serving the italic font file and let the browser synthesise an italic version from the roman font file.

**Comment by eviljeff** [comment]
> 
> 
> There's also the option of not serving the italic font file and let the browser synthesise an italic version from the roman font file.

interesting idea.  I played around with the css in dev tools:

Real inter italic font file:
![Screenshot 2021-04-01 10 30 51](https://user-images.githubusercontent.com/768592/113275991-46e57980-92d7-11eb-9f12-d4ca7d339695.png)
Browser synthesized italic
![Screenshot 2021-04-01 10 31 46](https://user-images.githubusercontent.com/768592/113275958-3af9b780-92d7-11eb-85c4-3f5a70b37174.png)

I can see a difference - the genuine Inter italic has a less pronounced angle - but I can't say the browser version looks bad.

**Comment by willdurand** [comment]
I like the browser version (and the overall idea). Is it browser-dependent? How does it look in Chrome or Edge? Would it look different on MacOS or Linux?

**Comment by eviljeff** [comment]
> 
> 
> I like the browser version (and the overall idea). Is it browser-dependent? How does it look in Chrome or Edge? Would it look different on MacOS or Linux?

I tested on Edge and it appears the Italic styling is just dropped entirely, rendering the text as Normal.  I don't have access to MacOS or Linux but it's possible there would be differences - fonts are partially an OS thing.  (I don't have Chrome installed currently but can install and give it a try if necessary)

**Comment by eviljeff** [comment]
logged #10478 to drop the variable italic font file (so the browser would use the individually weighted files instead).  Synthesizing seems to have some OS/Browser variations so is a bit more controversial.

**Comment by diox** [comment]
See https://github.com/mozilla/addons-frontend/issues/10495 for the future follow-up for other locales. Initial experiment will be with `en-US` only.
