### ISSUE TITLE
Replace Facebook with Instagram in footer

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10304]
The AMO footer currently links to the Firefox account on Facebook, which hasn't been updated in a very long time. If you look at www.mozilla.org, they are now linking to the [Instagram account](https://www.instagram.com/firefox/) instead, which is active. Let's replace the fb footer link and icon with the Instagram equivalent.

**Comment by NegiAkash890** [comment]
Hi @jvillalobos, I would like to fix this. How should I get started?

**Comment by championshuttler** [comment]
@NegiAkash890 first step would be to setup the project locally by following Readme :)

**Comment by ioanarusiczki** [comment]
@bobsilverberg In case this change should be made for dev hub footer on server side, I can file an issue. Let me know.


This is verified on AMO dev - FF87(Win10)


![Instagram](https://user-images.githubusercontent.com/33448286/114532570-a2a7ef00-9c55-11eb-874b-9df5858135f4.gif)

**Comment by bobsilverberg** [comment]
@ioanarusiczki I believe it should be. Please file an issue for it.
