### ISSUE TITLE
urls that don't have either an locale and app aren't handled correctly

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10308]
The middleware that checks for handles urls, and processes the app and locale parts, doesn't handle urls that are both in `validLocaleUrlExceptions` and `validClientAppUrlExceptions` (i.e. no app or locale in the url), and tries to add an app onto it.  On dev/stage/prod this isn't a problem because there is a complete nginx config managed by ops that captures those urls before frontend sees them; in a local development environment we use a much simplified [ngnix config](https://github.com/mozilla/addons-nginx/blob/master/addons.conf) that delegates most urls to frontend.   

Locally, you'll most likely encounter this bug if frontend is being used in combination with addons-server, where 404s generated are passed by the nginx config to addons-server to see if it can handle them instead.  Because the frontend middleware adds on an app and redirects, addons-server receives a url that isn't valid, and is then fixed by addons-server and redirected back (in a loop until the browser detects the loop and gives up)

e.g.

1. /contribute.json -> 301 by frontend to /firefox/contribute.json
2. /firefox/contribute.json -> 404 by frontend
3. /firefox/contribute.json is passed to addons-server by nginx
4. /firefox/contribute.json -> 302 by addons-server to /contribute.json
5. goto 1...

**Comment by eviljeff** [comment]
QA: the actual fix for this is only testable in a local dev environment, so out of scope, but I changed the code that's used for all urls, so best double check I haven't broken anything.  In particular, urls that are missing the locale (e.g. `/firefox/extensions`), or the app (e.g. `/en-US/extensions`), or both (e.g. `/extensions`) still work.  And urls that don't normally contain the app (about pages, etc) or the locale (mainly addons-server pages - I think only `/__frontend_version__` ?)

**Comment by ioanarusiczki** [comment]
@eviljeff  

- when /about and /review guide pages don't have locale such as  https://addons-dev.allizom.org/about - the redirect is made to https://addons-dev.allizom.org/en-US/firefox/ on AMO dev and AMO stage. This does not happen on prod so it might be a regression. 

In case I must file a separate issue, let me know.

**Comment by bobsilverberg** [comment]
Reopening as we are reverting the change. A new PR will need to be done to address this issue as well as the regression reported above.

**Comment by ioanarusiczki** [comment]
@eviljeff The issue from https://github.com/mozilla/addons-frontend/issues/10308#issuecomment-814879754 is no longer reproducible on AMO dev - FF87(Win10). 
I did not notice other issues while checking other URLs when they're missing locale, app or both.
