### ISSUE TITLE
The 'All Rights Reserved' license name is not displayed on the all versions page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10329]
### Describe the problem and steps to reproduce it:
1. Open the versions page of an add-on with versions published under the 'All Rights Reserved' license - see https://addons.allizom.org/en-US/firefox/addon/strict-compat-addon/versions/
2. Look at the 'Source code released under' section

### What happened?
The 'All Rights Reserved' license name is not mentioned

### What did you expect to happen?
The section should read "Source code released under **All Rights Reserved**"

![image](https://user-images.githubusercontent.com/31961530/113879340-16b04600-97c3-11eb-9e91-32290fffdb6b.png)

**Comment by bobsilverberg** [comment]
I opened https://github.com/mozilla/addons-server/issues/16952, which I believe is the root cause of this. Fixing that will likely fix this, so we might want to move this to addons-server.

**Comment by AlexandraMoga** [comment]
This issue was fixed on -dev by https://github.com/mozilla/addons-server/issues/16952:

![image](https://user-images.githubusercontent.com/31961530/115397551-e6b76880-a1ee-11eb-9ec5-7d7575229e6d.png)
