### ISSUE TITLE
Change the Download Firefox buttons to blue

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10323]
The buttons on the site to download Firefox are currently green, but they should be changed to blue. This should be done before the new CTA experiment is started.

**Comment by AlexandraMoga** [comment]
I've verified the install buttons ( `Add to Firefox`/`Install Theme`/`Download Firefox`) in Firefox and non-Firefox browser on Windows and Android and these are my results:

In non-Firefox Browsers (Chrome, Edge - Desktop, Brave - Android) the Download Firefox button is now blue:

[Desktop - Header + Detail page]
![image](https://user-images.githubusercontent.com/31961530/113873319-612ec400-97bd-11eb-8729-3843729c515e.png)

[Android - Header + Detail page]
![image](https://user-images.githubusercontent.com/31961530/113873534-93d8bc80-97bd-11eb-9956-9bbdb56c74ec.png)

[All versions page]
![image](https://user-images.githubusercontent.com/31961530/113874416-722c0500-97be-11eb-8a7e-7b0d07505e12.png)

The button functionalities remain the same.

In Firefox browsers - Windows and Android - the Install button works as before. The various button states (Enabled/Disabled, Remove, inactive) are displayed with their corresponding colors. 

@bobsilverberg the `Download Firefox` and `Login and Register` button alignments on Android is not ideal. I think we should try to display them on the same line and make the Search field smaller. 
![image](https://user-images.githubusercontent.com/31961530/113875706-b7046b80-97bf-11eb-8488-09fb0cd411c9.png)


I see that you've opened https://github.com/mozilla/addons-frontend/issues/10258 to address a similar issue. Would that also try to fix the alignment in general?

**Comment by bobsilverberg** [comment]
> 
> @bobsilverberg the `Download Firefox` and `Login and Register` button alignments on Android is not ideal. I think we should try to display them on the same line and make the Search field smaller.
> ![image](https://user-images.githubusercontent.com/31961530/113875706-b7046b80-97bf-11eb-8488-09fb0cd411c9.png)
> 
> I see that you've opened #10258 to address a similar issue. Would that also try to fix the alignment in general?

The Register or log in button is changing to a link, and that's landed on dev, but not stage yet. I think we should wait for that to land and then decide what, if anything, needs to be done.
