### ISSUE TITLE
Collections should display the themes like the search results 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10326]
As I mentioned https://github.com/mozilla/addons-server/issues/16755#issuecomment-814071930 I've noticed that the image from collections is visibly at lower quality compared to the one displayed into search results:

The theme into a search result:
https://addons-dev.allizom.org/en-US/firefox/search/?q=Themes%20again%20with%20wizard

The theme added to a collection: (with a lower quality)
https://addons-dev.allizom.org/en-US/firefox/collections/10641574/Themes-again-with-wizard/?page=1&collection_sort=-added

Another example (here it's not that obvious, so it also depends on the graphics):
https://addons-dev.allizom.org/en-US/firefox/search/?q=black%20rain%20animated%20tested
into a collection:
https://addons-dev.allizom.org/en-US/firefox/collections/10641574/Black-Rain-Animated/?page=1&collection_sort=-added

It does not seem to be a regression from https://github.com/mozilla/addons-server/issues/16755 

That looks like a frontend problem - it's displaying a thumbnail image at full size rather than a full size image.  - as mentioned by @eviljeff https://github.com/mozilla/addons-server/issues/16755#issuecomment-814145785

This is reproducible on all AMO servers - FF87(Win10).

**Comment by willdurand** [comment]
cc @diox

**Comment by diox** [comment]
Probably a regression from https://github.com/mozilla/addons-frontend/pull/10125 ? I never paid enough attention to the collection page and never noticed it was displayed in a similar layout to search...
