### ISSUE TITLE
The font size for the 'Register or log in' button should be increased

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10328]
Follow up for #10163 

### Describe the problem and steps to reproduce it:
1. Load AMO -dev while being logged out 
2. Observe the 'Register or log in' button

### What happened?
The font size of the button text is at 12px

### What did you expect to happen?
The 'Register or log in' button should have the same font size and weight as the 'Extension Workshop' and 'Developer Hub' links

![image](https://user-images.githubusercontent.com/31961530/113877460-655ce080-97c1-11eb-8e05-809bee6a5f8a.png)

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga, although I'm not sure it should be the same size as the links. When it was in a button the font size was smaller, like this, and I'm not sure we want it to be as prominent.

@jvillalobos @Verdi WDYT?

**Comment by AlexandraMoga** [comment]
Yes, I understand that the scope of the 'Register or Log in' button is different from the other two links, but visually it makes that header section appear unbalanced.

**Comment by willdurand** [comment]
> Thanks @AlexandraMoga, although I'm not sure it should be the same size as the links. When it was in a button the font size was smaller, like this, and I'm not sure we want it to be as prominent.

I think we do want the same size, it doesn't look great right now.. The button was smaller to match the other textual links but now it looks a bit odd (and small).

**Comment by jvillalobos** [comment]
Yes, I agree the font styles should match.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Maybe "Donwload Firefox" can go to 14 px too?

**Comment by bobsilverberg** [comment]
@ioanarusiczki I'm not sure we want to do that. It's always been a smaller font than the other links. If we just increase the font size then it appears to have less room in the button, and I don't think we want to change the button height as that will cause it to be larger than the links.

With 14px:
![Screen Shot 2021-04-13 at 7 50 56 AM](https://user-images.githubusercontent.com/142755/114547980-2699b100-9c2d-11eb-830f-2553b89ade15.png)

Current (11px):
![Screen Shot 2021-04-13 at 7 51 15 AM](https://user-images.githubusercontent.com/142755/114547952-1da8df80-9c2d-11eb-9fa5-e116a6b2b97b.png)

@jvillalobos @Verdi WDYT?

**Comment by Verdi** [comment]
I would leave it as is. The larger type needs more padding which will make the button bigger which may lead to other problems. If our experiment goes well, we'll be getting rid of it anyway.
