### ISSUE TITLE
Provide error page HTML via components.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1033]
At the moment we use basic strings for errors. These are not translated and they aren't HTML. 

To fix this we should have a base error component and then specialise that for specific errors where we need to override the messaging.

**Comment by muffinresearch** [comment]
Relates https://github.com/mozilla/addons-frontend/issues/307

**Comment by kumar303** [comment]
Check out https://github.com/mozilla/addons-frontend/pull/1637 which lays a bit of foundation for rendering resource errors such as 404, 500, etc.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by tofumatt** [comment]
QA: To verify simply visit a page that results in error (easiest is a 404 Not Found page) and verify it is rendered with HTML and is not a plaintext string.

... although because addons-server provides our 404 errors right now this would be hard to test, so I can mark this as QA not needed for now, though when we move to using the frontend for everything it's worth testing. What would QA prefer?

**Comment by ValentinaPC** [comment]
I'll try to find a 404 page to check this.
I'll also wanna add a legacy frontend label, if it is ok with you, to test this after the big changes coming up in our way.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Android 6.0.1)
Accessing https://addons-dev.allizom.org/en-US/android/mobile/ on my Android device will load a 404 page rendered with HTML.
Postfix screenshot:
![mobile](https://cloud.githubusercontent.com/assets/15685960/26311929/92b990d8-3f0e-11e7-8daa-7fedd29d8813.png)

Also, "`file an issue`" form the 404 page shouldn't redirect to "https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact" as "Report an issue" does, and not to the Github login page?
Thanks!

**Comment by tofumatt** [comment]
The file an issue page should not go directly to GitHub but to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact, yes. That's the current behaviour, right?

**Comment by ValentinaPC** [comment]
> The file an issue page should not go directly to GitHub but to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact, yes. That's the current behaviour, right?

The `file an issue` link redirects to Github - this is the current behavior.
