### ISSUE TITLE
Back out change to prefixMiddleware

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10331]
We need to back out the change from https://github.com/mozilla/addons-frontend/pull/10309 as it introduced a regression.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Right now I can still reproduce the issue for About and Review Guide pages on AMO dev and AMO stage. 
Tagging @eviljeff to see this too. 

![reproducible](https://user-images.githubusercontent.com/33448286/113987705-604a7080-9857-11eb-99b6-5e0246569f17.gif)

**Comment by eviljeff** [comment]
Works for me, so it's probably just browsing caching (frontend uses a 301 for it's redirects, so it'd stick).

Although from a look at the other changes landing this week there is also code added (`getClientAppAndLangFromPath`) that parses the url to split it into app and lang that wouldn't work for any url in `validClientAppUrlExceptions` or `validLocaleUrlExceptions` so I can't discount that either.

**Comment by ioanarusiczki** [comment]
@eviljeff You're right - into a new profile worked for me too. Verified on AMO dev and AMO stage - FF87(Win10). 

The rest of the pages seem to work as expected too.
