### ISSUE TITLE
Recommended themes collection - the size of themes on the homepage is smaller than expected

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10357]
STR: 

I tested the new homepage shelf module for https://github.com/mozilla/addons-frontend/issues/9996 - and added all type of shelves for the homepage -> among them the [Recommended theme collection ](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/) which uses the collections endpoint and I've noticed that the size of the themes is 266x34 instead of 375x48. 

![Featured themes](https://user-images.githubusercontent.com/33448286/114522413-0a593c80-9c4c-11eb-8db3-3395359c3312.png)

This is reproducible on AMO dev with FF87(Win10).

**Comment by bobsilverberg** [comment]
I believe the issue here is that the `collections` type is not intended to be used for themes. There are not any collections of themes on the current home page, so this shouldn't affect us when this goes to production.

I suppose if we need to fix this one option would be to add a `collections-themes` type, similar to the existing `search-themes` type, although I don't know if there are any plans to ever use a collection for themes on the home page.

@devaneymoz Do you know if that's something you'll need to do in the future?

**Comment by jvillalobos** [comment]
It should be possible to feature theme collections in the homepage, yes. In the past we've promoted campaigns that involve a list of themes (like for example a collection of flag themes for the World Cup or the Olympics).

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. @xlisachan how do you think we should approach this? As mentioned above, we could create a `collections-themes` type similar to the `search-themes` type, but I am also wondering if this is something we could detect when the page is rendered, by checking the type of the first add-on returned? Is that feasible? I don't recall why we went with the `search-themes` type the first time around and didn't try to detect on the client. Maybe it has to do with the loading skeleton?

**Comment by xlisachan** [comment]
@bobsilverberg, I believe everyone considered determining the type using `criteria` for search was considered a hack approach and, therefore, `search-themes` type was added instead ([#16327])(https://github.com/mozilla/addons-server/pull/16327). I think it would be more consistent (and cleaner) to add a `collections-themes` type, can I handle this if you agree?

**Comment by bobsilverberg** [comment]
> @bobsilverberg, I believe everyone considered determining the type using `criteria` for search was considered a hack approach and, therefore, `search-themes` type was added instead ([#16327](https://github.com/mozilla/addons-server/pull/16327)). I think it would be more consistent (and cleaner) to add a `collections-themes` type, can I handle this if you agree?

Yes, that sounds like a good idea, thanks @xlisachan!

**Comment by bobsilverberg** [comment]
@xlisachan As you've started on the server piece of this, I have assigned this to you. I believe this needs a change both in addons-server and addons-frontend, so if there isn't already one, can you file an issue for the addons-server part of this?

**Comment by eviljeff** [comment]
@bobsilverberg what do we do currently for a shelf containing collection of themes?  Is it hard-coded?  (I'm assuming it's at least happened before because Jorge says "In the past we've promoted campaigns that involve a list of themes")

**Comment by bobsilverberg** [comment]
> @bobsilverberg what do we do currently for a shelf containing collection of themes? Is it hard-coded? (I'm assuming it's at least happened before because Jorge says "In the past we've promoted campaigns that involve a list of themes")

The current code doesn't really have a concept of shelf types, so yeah, if we had a shelf of themes that was based on a collection we would just have hardcoded the differences into it. Now that shelves are dynamic and based on data, we need a way for the frontend to understand that a shelf contains themes.  Now that we're thinking about adding a `collections-themes` type, it might actually make more sense to have an additional property for `addonType` which is either `extensions` or `themes`, and do away with the `search-themes` type.

@xlisachan WDYT?

**Comment by xlisachan** [comment]
@bobsilverberg, sounds good! Should I edit the issue I had opened for adding `collections-themes` or should I close it and open a new issue?

**Comment by bobsilverberg** [comment]
This should be fixed by #10439, along with the landing of https://github.com/mozilla/addons-server/pull/16967.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @xlisachan 

Right now on AMO dev - the size of themes is  266x34 instead of 375x48 on every shelf 

![small size](https://user-images.githubusercontent.com/33448286/116045471-ef60d200-a626-11eb-8b66-7aba8bcd8c01.png)

**Comment by ioanarusiczki** [comment]
@xlisachan 

A collection of staticthemes - looks good

![collection endpoint](https://user-images.githubusercontent.com/33448286/116521725-003a6d80-a8dd-11eb-8d6e-d24f14b1a84a.png)

Verified on AMO dev - FF88(win10).
