### ISSUE TITLE
Update the event category for the GetFirefoxBanner click

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10359]
I updated the event category for clicks on the `GetFirefoxButton` to include the variant from the experiment, but the clicks on the `GetFirefoxBanner` do not include the variant. We should include it there as well.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I'm not sure if that's the way to check this but when I click the banner and land on mozilla.org,  I see as utm_content=banner-download-button 
If I dismiss the banner I see as eventCategory in the Console -"AMO Download Firefox Banner" 

I've also added more detailed info about the utm_campaign here https://github.com/mozilla/addons-frontend/issues/10218#issuecomment-819462850
