### ISSUE TITLE
Look into moving away from Enzyme

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10350]
This is something we have discussed, more than once. There are incompatibilities between Enzyme and modern React, and React has no plans to try to support Enzyme moving forward.

I did a bunch of experimentation with [React Testing Library](https://testing-library.com/docs/react-testing-library/intro/) back in 2020/early 2021, and I wasn't pleased with its limitations in terms of the kinds of tests we can write, but it seems like the industry is moving away from shallow rendering, so perhaps we have to bite that bullet as well.

I was reminded of this issue, and the direction the industry is taking, by [this post](https://github.com/enzymejs/enzyme/issues/2429#issuecomment-817750268) by Dan Abramov on an issue about supporting React 17 with Enzyme.

Enzyme is also blocking us from upgrading [`react-redux`](https://github.com/mozilla/addons-frontend/issues/8251) and [`react-router`](https://github.com/mozilla/addons-frontend/issues/7727).

**Comment by ljharb** [comment]
To be clear, React hasn't really "supported" enzyme since v16 came out. What this means isn't that enzyme can't or won't work with react; it just means that enzyme has to play catchup every time React makes a breaking change that they'd like to pretend is semver-minor.

**Comment by diox** [comment]
Done in https://github.com/mozilla/addons-frontend/issues/11624
