### ISSUE TITLE
Add bug reporting information to /about page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-frontend#10351]
Related to [#16884 on the addons-server repo](https://github.com/mozilla/addons-server/issues/16884). 

Let's add a few sentences about how to report bugs/issues on addons.mozilla.org/about. The following text should be added under the "Get Involved" section: 

_____

**Report an issue**
If you find a problem with the site, we'd love to fix it. Please file an [issue](https://github.com/mozilla/addons/issues/new) and include as much detail as possible.

To report a security vulnerability for an extension, even if it is not hosted on this site, please file an [issue](https://bugzilla.mozilla.org/enter_bug.cgi?product=addons.mozilla.org&component=Add-on%20Security&maketemplate=Add-on%20Security%20Bug&bit-23=1&rep_platform=All&op_sys=All) on Bugzilla or email amo-admins@mozilla.com. All security vulnerability reports are [confidential](https://www.mozilla.org/en-US/about/governance/policies/security-group/bugs/).

_____

This should be tagged as a good first issue. 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg

**Comment by diox** [comment]
The code is in https://github.com/mozilla/addons-frontend/blob/master/src/amo/pages/StaticPages/About/index.js

Please add a new `<section>` with `Report an issue` as the `<h2>`. Also, add an `id` attribute so that this new section can be linked to (we'll do that in mozilla/addons-server#16884)

**Comment by wayfaringjou** [comment]
Hi @diox can I work on this issue? Just add the `<section>` to [About/index.js](https://github.com/mozilla/addons-frontend/blob/master/src/amo/pages/StaticPages/About/index.js)?

**Comment by pranav1601** [comment]
Hey @diox Could i work on this?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO dev - FF87(Win10). 

![on AMO dev](https://user-images.githubusercontent.com/33448286/115239411-5a8e3e00-a127-11eb-8ce3-2a5cbd0792a0.png)
