### ISSUE TITLE
Install buttons are busted because of JS error TypeError: $(...).installButton is not a function

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-frontend#1036]
### steps to reproduce:
1. Load https://addons.allizom.org/en-US/firefox/addon/image-block/?src=hp-dl-featured
2. Notice the install button

### Expected behavior:
Install button says "Install". There are no JS errors in the console

### Actual behavior:
Install button says "Download". Console shows

10:36:53.794 ReferenceError: gettext is not defined1impala-min.js:1:29651BrowserUtilshttps://addons-stage-cdn.allizom.org/static/js/impala-min.js:1:29651<anonymous>https://addons-stage-cdn.allizom.org/static/js/impala-min.js:2:992

10:36:53.795 TypeError: z.button is undefined1buttons.js:14:1<anonymous>https://addons-stage-cdn.allizom.org/en-US/firefox/addons/buttons.js:14:1

10:36:53.801 TypeError: $(...).installButton is not a function1impala-min.js:1:31145<anonymous>https://addons-stage-cdn.allizom.org/static/js/impala-min.js:1:31145nhttps://addons-stage-cdn.allizom.org/static/js/impala-min.js:1:12223p.Callbacks/uhttps://addons-stage-cdn.allizom.org/static/js/preload-min.js:1:28568p.Callbacks/l.fireWithhttps://addons-stage-cdn.allizom.org/static/js/preload-min.js:1:29405.readyhttps://addons-stage-cdn.allizom.org/static/js/preload-min.js:1:31288Fhttps://addons-stage-cdn.allizom.org/static/js/preload-min.js:1:31656

### screenshot:
<img width="1437" alt="screenshot 2016-09-06 10 41 44" src="https://cloud.githubusercontent.com/assets/301317/18284415/ace21842-741e-11e6-944e-bf508175fb80.png">

**Comment by EnTeQuAk** [comment]
I believe this should be addons-server and something with our js is very busted, weird. cc'ing @bqbn on this since I have the feeling that this is related to our deployment on stage.

**Comment by EnTeQuAk** [comment]
Or maybe something is wrong with https://github.com/mozilla/addons-server/commit/d6a00b6396cf5231e5872d89493bd5956966cbc6 but I don't see it yet

**Comment by EnTeQuAk** [comment]
https://addons-stage-cdn.allizom.org/en-US/firefox/jsi18n.js?b=0f46477-57cef26e returns 502, Bad Gateway, looks more like an ops issue than a assets issue or anything else.

**Comment by bqbn** [comment]
This might be django v1.8 upgrade related. Found this discussion https://groups.google.com/forum/#!topic/django-developers/4Wim25pSG4M

After I run ```./manage.py clear_cache -v 3```, the above problematic url starts to return 200.

@krupa, can you try again?

**Comment by EnTeQuAk** [comment]
thanks a lot @bqbn this appears to have fixed the problem. I'll add this to the list for Thursday to make sure this won't happen in -prod.

**Comment by vcarciu** [comment]
Verified as fixed : 
![addtofirefox](https://cloud.githubusercontent.com/assets/1583842/18378897/4e3220ce-7678-11e6-87ef-3d3b35b0129f.png)
