### ISSUE TITLE
Review UTM params in `StaticAddonCard` (blog-utils)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10368]
Some UTM parameters are rendered in the `StaticAddonCard`, let's make sure they are what we want. I am wondering if the "download button" should have UTM params referencing an AMO experiment for instance.

**Comment by bobsilverberg** [comment]
I would think it should have unique params to indicate that it came from the blog.

**Comment by willdurand** [comment]
@jvillalobos currently, we have the following "download link":

> https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=rta%3AZmlyZWZveEBnaG9zdGVyeS5jb20

If this needs to change, let us now.

**Comment by jvillalobos** [comment]
We will need something consistent with https://github.com/mozilla/addons-frontend/issues/10218, maybe replacing `amo` with `amo-blog` to make them easy to tell apart. However, it's best to wait for the resolution of https://github.com/mozilla/addons-frontend/issues/10476 and related bugs/issues, since we haven't landed on the params that we'll be using more permanently.

**Comment by willdurand** [comment]
> We will need something for `utm_campaign` consistent with #10218, maybe replacing `amo` with `amo-blog` to make them easy to tell apart. However, it's best to wait for the resolution of #10476 and related bugs/issues, since we haven't landed on the params that we'll be using more permanently.

Stating the obvious: tgere is no experiment on the blog.

**Comment by jvillalobos** [comment]
Yup, I'm interested in the part where we send the add-on ID in the param. It can be extracted from `utm_content`, but it makes it harder to figure things out in Google Analytics, for instance.

**Comment by willdurand** [comment]
@jvillalobos it looks like we'll have the following download links (during the experiment):

```
https://www.mozilla.org/firefox/new/?utm_campaign=non-fx-button&utm_content=rta:<hash>&utm_medium=referral&utm_source=addons.mozilla.org&utm_term=amo-fx-cta-853731-new-cta
```

**Comment by jvillalobos** [comment]
> Something like amo-blog-fx-cta-<addon-id>

That looks good.

**Comment by ioanarusiczki** [comment]
@willdurand 

utm_term from blog has the expected format when the download button is clicked from the blog

![download cta blog](https://user-images.githubusercontent.com/33448286/117447589-614deb00-af46-11eb-869f-1515d55a0fcd.png)
