### ISSUE TITLE
Remove code which allows events to be called on the server

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10376]
Some code was added to support the experiment enrollment event which allowed an event to be stored on the server and then later sent to GA on the client. We aren't going to need to do this anymore when we move all of the experiment code to the client, so we can remove this code.

We should also add code to tracking that will raise an exception if we ever try to send an event on the server, as this will be impossible to do, and we don't want any code attempting to do it, and failing silently.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Re-checked this morning the experiment with Edge - deleting the experiment cookie without login (because of the caching) and then with login and I did not see issues. 

If there's anything else I should be looking for please let me know.

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. I assume the above means you verified the enrollment events sent to GA? Is so, then I don't think there's anything else that needs to be checked.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

What I verified for https://github.com/mozilla/addons-frontend/issues/10218#issuecomment-819462850 is still available.

I managed to take a screenshot from the Console for the events so this also verifies https://github.com/mozilla/addons-frontend/issues/10359 

1. The current cta events:

Download firefox blue button is clicked:

![event sent for the general download button](https://user-images.githubusercontent.com/33448286/115386484-1c098980-a1e2-11eb-9876-55aecb1c64bf.png)

Download ff from a detail page is clicked:

![event variant for the detail page](https://user-images.githubusercontent.com/33448286/115386508-23c92e00-a1e2-11eb-8af3-3ce3e07ac2de.png)

2. The new cta events:

The banner is clicked:

![banner event for newcta](https://user-images.githubusercontent.com/33448286/115386822-94704a80-a1e2-11eb-88e3-0530e7e2b344.png)

The download button on a detail page is clicked:

![event sent for newcta detail page](https://user-images.githubusercontent.com/33448286/115386910-ad78fb80-a1e2-11eb-8b8e-310224053faf.png)

3. I've noticed on https://www.mozilla.org/en-US/firefox/ that the utm_content parameter has the following format for clicks from the detail pages:

![utmcontent from detail page](https://user-images.githubusercontent.com/33448286/115388038-18770200-a1e4-11eb-941b-cd629a67a5d1.png)


meanwhile the clicks from the banner have a different value:

![the value for utm content banner](https://user-images.githubusercontent.com/33448286/115387890-ec5b8100-a1e3-11eb-8a16-efb6d719c8ac.png)


I hope that's fine.

**Comment by bobsilverberg** [comment]
Yes, the `utm_content` is expected to be different between the add-on detail page and the banner.
