### ISSUE TITLE
Fix `title` and `footer text` within homepage shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-frontend#10373]
Per #9996, the `title` and `footer text` fields from the [shelfmodule](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/) are not limited to a number of chars. The screenshot below displays both fields at 100 characters:

![114384010-dbcd5a00-9b96-11eb-80e9-4cc2c8417a3d](https://user-images.githubusercontent.com/28129806/114649399-779db980-9cae-11eb-9326-21d7f367e48b.png)

The maximum text length that the UI supports will also need to be determined.

**Comment by ioanarusiczki** [comment]
@xlisachan I don't think the number of chars have been limited but I tested with 150 chars and the layout is not broken. 
I don't think that on prod this length will be reached anyway for both fields. 
I tested around the views, I don't see isssues into the review card or on the addon review page.
Verified on -dev with FF90(Win10).
