### ISSUE TITLE
Layout issues for the detail page message in large and medium views

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10375]
Followup for https://github.com/mozilla/addons-frontend/issues/10252#issuecomment-819399908

The experiment yellow message doesn't look good on pages with a longer summary - for not recommended extensions and themes
It is reproducible on AMO dev - with Chrome and Edge

Examples:

extension:  

![extension](https://user-images.githubusercontent.com/33448286/114689017-23083780-9cca-11eb-9c35-9f8ef3e5539a.png)

theme:

![themes](https://user-images.githubusercontent.com/33448286/114689382-7f6b5700-9cca-11eb-926a-28e40bf72a5c.png)

**Comment by championshuttler** [comment]
There is breakage for download button too for other browsers i guess, @ioanarusiczki can confirm?


![image](https://user-images.githubusercontent.com/22130317/114723944-b8520d00-9d58-11eb-92f4-85c0410148f9.png)

**Comment by ioanarusiczki** [comment]
@championshuttler The experiment is disabled right now on AMO dev - but I am going to check it once it's back.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @championshuttler 

I could not reproduce the issue [above](https://github.com/mozilla/addons-frontend/issues/10375#issuecomment-819546482) with Chrome for Android - on a small screen 

However, I've noticed that for https://addons-dev.allizom.org/en-US/firefox/ the button for recommended addons is different from https://addons-dev.allizom.org/en-US/android/ 

This is the recommended - long version on https://addons-dev.allizom.org/en-US/firefox/

![android Chrome](https://user-images.githubusercontent.com/33448286/114999132-3eca3400-9eaa-11eb-945d-aa9942acb736.png)

This is the recommended detail page on https://addons-dev.allizom.org/en-US/android/ where "and get the extension" is not included.  Should the button be like on https://addons-dev.allizom.org/en-US/firefox/?

![on android url](https://user-images.githubusercontent.com/33448286/114999575-a7191580-9eaa-11eb-84b1-e15b268f672a.png)

**Comment by bobsilverberg** [comment]
> @bobsilverberg @championshuttler
> 
> I could not reproduce the issue [above](https://github.com/mozilla/addons-frontend/issues/10375#issuecomment-819546482) with Chrome for Android - on a small screen
> 
> However, I've noticed that for https://addons-dev.allizom.org/en-US/firefox/ the button for recommended addons is different from https://addons-dev.allizom.org/en-US/android/
> 
> This is the recommended - long version on https://addons-dev.allizom.org/en-US/firefox/
> 
> ![android Chrome](https://user-images.githubusercontent.com/33448286/114999132-3eca3400-9eaa-11eb-945d-aa9942acb736.png)
> 
> This is the recommended detail page on https://addons-dev.allizom.org/en-US/android/ where "and get the extension" is not included. Should the button be like on https://addons-dev.allizom.org/en-US/firefox/?
> 
> ![on android url](https://user-images.githubusercontent.com/33448286/114999575-a7191580-9eaa-11eb-84b1-e15b268f672a.png)

My apologies for not mentioning this in the instructions, but this is expected. RTAMO is not supported on android, so we use this simpler version of the button text.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This is fixed on AMO dev - FF87(Win10) 

![fixed](https://user-images.githubusercontent.com/33448286/115202911-8f869a80-a0ff-11eb-893b-961df098ff55.png)

About the other Download button (RTAMO type), I may have something at medium size screens with extensions only:

![ux issue for the download medium size](https://user-images.githubusercontent.com/33448286/115203016-aaf1a580-a0ff-11eb-81b5-91be4d5a028d.png)

If you think it needs a ux fix, let me know and I'll file this.

**Comment by bobsilverberg** [comment]
I'll just comment here, and add this to the new issue when it is opened, that this only seems to occur very close to a breakpoint. Specifically, I only see this with a screen resolution between 720px and 730px, so while it would be nice to fix, I'm not sure it's particularly critical.
