### ISSUE TITLE
Enable compression (express) middleware

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10374]
Our responses aren't gzipped because we deferred this step to Nginx. Now that we have html caching, we think that the app should serve gzipped content so that Nginx can directly forward the content to the client, without having to gzip it. (similar to addons-server)

We should enable the `compression` middleware on the server and that should be enough on our side. We'll also need to check the nginx config to make sure we vary on `accept-encoding`.

**Comment by diox** [comment]
This seems to be working well on dev. nginx is adding a `Vary: Accept-Encoding` on top of our own, but that shouldn't be a problem.

**Comment by ioanarusiczki** [comment]
@diox Please add some str for qa.
Thanks

**Comment by diox** [comment]
I know comparing dev and prod performance is... questionable at best, but this is encouraging:

(Each time I actually did several rounds to prime the cache, and then ran the command multiple times to ensure results were all consistent - they were)
```
/usr/bin/time -f '%e' curl -s https://addons.mozilla.org/en-US/firefox/ -H 'Accept-Encoding: gzip' > /dev/null
1.02
```
```
/usr/bin/time -f '%e' curl -s https://addons-dev.allizom.org/en-US/firefox/ -H 'Accept-Encoding: gzip' > /dev/null
0.55
```
