### ISSUE TITLE
Disable the current experiment on dev

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10377]
Due to problems with caching, we want to disable the current experiment on dev.

For QA:
The experiment will no longer be testable on dev until we re-enable it, which will happen sometime in the next few days.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I can see again the experiment beeing active today.

**Comment by ioanarusiczki** [comment]
Should be fine now https://github.com/mozilla/addons-frontend/issues/10188#issuecomment-820371425 so I'm adding verified here.
