### ISSUE TITLE
Require login before rating an add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1037]
This is to implement the UI needed for logging in before beginning the rate-an-add-on flow (the entry to the flow is [rating your overall experience](https://github.com/mozilla/addons-frontend/issues/1017)).

UX is TBA. I don't think we can do much to a Firefox Accounts login prompt so we may need an interstitial that says "You need to sign in before you can rate an add-on. [Sign In Now]"

UX flow: https://mozilla.invisionapp.com/share/A58EEQUK6#/screens/183938152
UX flow tracker: #927
This supports mozilla/addons#151

**Comment by muffinresearch** [comment]
I wonder if logged out the interaction with the widget could start the login flow, we might be able to maintain some state via the return url?

**Comment by mstriemer** [comment]
There's a mock of this in the sketch file.

<img width="516" alt="screen shot 2017-01-12 at 9 20 45 am" src="https://cloud.githubusercontent.com/assets/211578/21895480/864cd278-d8a8-11e6-9dd0-c215895e2e56.png">

**Comment by vcarciu** [comment]
@kumar - I think that after logging, we should scroll to ratings star section if possible. Please let me know if I should open another issue for this.

**Comment by kumar303** [comment]
Yeah, please open another issue

**Comment by ValentinaPC** [comment]
Verified fixed on AMO-dev FF51(Android 6.0.1)
Postfix video:
![block](https://cloud.githubusercontent.com/assets/15685960/23303919/98aa3e7e-fa9f-11e6-85f8-62d4f3b7c45f.gif)
