### ISSUE TITLE
Update url to Blog in the footer (with a feature flag)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10389]
We should add a feature flag that, when turned on, will set the URL of the AMO blog to `/blog/` instead of the current absolute URL in the footer.

**Comment by willdurand** [comment]
For QA: the link to the blog in the footer of amo -dev should redirect to `/blog/` while other envs should send users to blog.mozilla.org/addons/

**Comment by eviljeff** [comment]
@jvillalobos are we replacing the link to the old blog entirely, or still linking to it as "developer blog" (or whatever)?

**Comment by jvillalobos** [comment]
Yes, let's add a footer link labeled "Developer Blog" between Developer Policies and Forum, pointing to the current blog.

**Comment by jvillalobos** [comment]
URL: `https://blog.mozilla.com/addons?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=footer-link`

**Comment by ioanarusiczki** [comment]
@willdurand 

on AMO dev:

Blog redirect to https://addons-dev.allizom.org/blog/
Developer Blog to https://blog.mozilla.org/addons/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=footer-link

I don't know about the dev hub footer - is this going on server side too?
