### ISSUE TITLE
cleanup `clientAppRoutes` now we're on react-router v4

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10396]
`clientAppRoutes` was added as a workaround to limitations in react-router (#3162) but now we're on v4+ we don't need it.

**Comment by willdurand** [comment]
It's probably something we really want to do to reduce the amount of config and also code in the middleware so let's make it a p3.

**Comment by ioanarusiczki** [comment]
Verified on AMO stage - FF88(win10).
