### ISSUE TITLE
External URL `footer_pathname` in homepage shelves should open in a new tab

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-frontend#10397]
Per feedback in #9996, the `footer_pathname` supports external URLs, which currently opens in the same tab. However, these URLs should have the same behavior as URLs in the secondary hero shelf (the page opens in a new tab).

**Comment by ioanarusiczki** [comment]
@xlisachan This is verified on AMO dev - FF87(Win10). 

![newtabfix1](https://user-images.githubusercontent.com/33448286/115559547-a4327200-a268-11eb-9fbf-768281706d64.gif)
