### ISSUE TITLE
Do not set clientApp and locale in links generated by the `Header` for the blog

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10406]
We introduced a prop to render the `Header` or addons-blog in https://github.com/mozilla/addons-frontend/issues/10382 but URLs contain `firefox` and `en-US` (the default values). We should change that to have no clientApp and no locale instead so that users will be redirected to AMO according to their user agent.

For QA: when this is closed, the blog should have no `clientApp` or `locale` in the URLs of the header (top nav), e.g., `/extensions/` instead of `/en-US/extensions/`.

**Comment by ioanarusiczki** [comment]
@willdurand 
1. for 
https://addons-dev.allizom.org/en-US/blog 
https://addons-dev.allizom.org/firefox/blog 

message is: 

![another 404](https://user-images.githubusercontent.com/33448286/115226378-d7192080-a117-11eb-802b-cade322ef78c.png)

Maybe it should look like all the other 404 pages (like below) ?

for https://addons-dev.allizom.org/en-US/firefox/blog 

message is: 

![404](https://user-images.githubusercontent.com/33448286/115226333-c9639b00-a117-11eb-831b-9492008c6981.png)

2. Things noticed about the blog page:

- the header does not look like other AMO pages - no EW , dev hub user menu(register/login on the right side) or search bar.

![header](https://user-images.githubusercontent.com/33448286/115228187-22343300-a11a-11eb-903d-8b2f20a03603.png)

- the footer on https://addons-dev.allizom.org/blog/ is going to open all external URLs in a new tab. On other AMO pages - all footer URLs open in the same tab.

**Comment by willdurand** [comment]
>  for
>  [addons-dev.allizom.org/en-US/blog](https://addons-dev.allizom.org/en-US/blog)
>  [addons-dev.allizom.org/firefox/blog](https://addons-dev.allizom.org/firefox/blog)

Could you file an issue for that? I don't really know why it is doing this, but there must be a reason and it is not related to this issue. You're right, it should either fix the url itself or show a "page not found" error, but not that.

> for [addons-dev.allizom.org/en-US/firefox/blog](https://addons-dev.allizom.org/en-US/firefox/blog)

This is expected, that URL does not exist.

> the header does not look like other AMO pages - no EW , dev hub user menu(register/login on the right side) or search bar.

Yes, this is expected. The only "unexpected" change is that there is no "More..." link on the blog and, instead, a "Blog" link, which isn't on other AMO pages. This will be fixed in #10407

**Comment by ioanarusiczki** [comment]
@willdurand Done https://github.com/mozilla/addons-frontend/issues/10443

I've noticed something about the footer of the blog too ->  From https://addons-dev.allizom.org/blog/ all external URLs are opened in a new tab. 
On other AMO pages (homepage, extensions, search results, about and so on) - all footer URLs open in the same tab.
