### ISSUE TITLE
Add-on reviews, letters hidden (fractionally) by rounded corners

### ISSUE THREAD

**Issue by harl** [mozilla/addons-frontend#10405]
On pages with add-on reviews that contain at least one line of text, the lower left corner of the text is sometimes hidden by the rounded corner overlapping(?) the text and cutting off certain letters' tails below the typographical font baseline, most prominently with the lower letters p and g, but other letters are affected as well (even upper letters, although this may seem petty).

![210417_addons mozilla org_issue_report](https://user-images.githubusercontent.com/1159811/115105161-6b8b5380-9f5d-11eb-82d9-49504ff30b78.png)
![210417_addons mozilla org_issue_report_1](https://user-images.githubusercontent.com/1159811/115105305-6549a700-9f5e-11eb-9511-96e963a7b949.png)

The letter p of "preview" looks slightly confusing, almost like an o, and the letter g looks almost like a q.

**Comment by willdurand** [comment]
I suggest we increase the default `line-height` to fix this issue (`1.5` should be better if default font size is `16px`).

**Comment by AlexandraMoga** [comment]
I believe this issue describes a similar problem to what is tracked in #10267 - which could also be fixed by adjusting the default `line-height`.

**Comment by bobsilverberg** [comment]
It sounds like, as a precursor to https://github.com/mozilla/addons-frontend/issues/10251, we should just increase the default line height to 1.5, and then further tweak it in https://github.com/mozilla/addons-frontend/issues/10251.

This is already proposed in https://github.com/mozilla/addons-frontend/pull/10412, so I'll just double check that that seems okay overall and if it does, then let's merge https://github.com/mozilla/addons-frontend/pull/10412.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
On AMO dev:
on addon reviews page:
"j" looks just a little bit truncated, "p" and "g" look good now. So I'd say it's fine. 

![j](https://user-images.githubusercontent.com/33448286/125456504-6421f30c-079a-442a-8810-d2280f9ac002.png)


The detail page shows the review too (for the user). In this case "j" and "p" still look truncated:

![j detail page](https://user-images.githubusercontent.com/33448286/125456519-5f618bf6-5ffa-48a6-8e6e-1fd2d59aa080.png)

![p on the detailpage](https://user-images.githubusercontent.com/33448286/125456536-f7dffc61-e041-4710-8aa8-d6c542b6945a.png)

If you want me to file a new issue about the detail page case let me know. 

I'll mark this one verified on AMO Dev. - FF89(Win10).

**Comment by bobsilverberg** [comment]
@ioanarusiczki As we are about to cut a tag, it's probably best if you open a new issue for the detail page case. You might as well mention the `j` issue there as well, as I might be able to fix that by bumping up the padding by a pixel.
