### ISSUE TITLE
Show "More..." in the Header for the blog

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10407]
In #10382, we added some code to render the `Header` component for addons-blog. The "more..." link/dropdown was hidden because of a UI issue but after the last UX meeting, it was decided to:

1. show this "More..." link in the header of the blog
2. put the link to the Blog in the dropdown menu

**Comment by ioanarusiczki** [comment]
@willdurand 
1. "More" is available from the blog page - there's a UX issue I filed https://github.com/mozilla/addons-blog/issues/157
2. Blog is available in the dropdown menu from More
3. on Android - I can access https://addons-dev.allizom.org/blog/ from the footer of the page and it will redirect to the same content as the desktop. To access https://addons-dev.allizom.org/en-US/android/ again either I navigate back or I click "Add-ons for Android" from More.
