### ISSUE TITLE
UX issue with "Download file" links on small screens

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10417]
### Describe the problem and steps to reproduce it:

1. Browse a "all versions" page on AMO with a mobile device or small screen
2. Observe the "download file" links

### What happened?

Download file links appear at the bottom right of each card, with no padding so it looks a bit broken:

![signal-2021-04-16-205811](https://user-images.githubusercontent.com/217628/115204038-58f95180-a0f8-11eb-9cb8-b772096b0361.png)

### What did you expect to happen?

Not that.

**Comment by bobsilverberg** [comment]
I think the problem here isn't the lack of padding below the Download file link, it's the gap between each version, which really shouldn't be there. If we remove that gap (which appears as grey), it looks much better. I'll include a screenshot with the PR to fix it.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev, with Firefox for desktop (Win10) and Fenix on Android as well as non-Firefox browsers:

![image](https://user-images.githubusercontent.com/31961530/115877384-0bf6e180-a450-11eb-9b44-160e68926255.png)
