### ISSUE TITLE
Rating stars inside the Write a review form are misaligned 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10423]
### Describe the problem and steps to reproduce it:
1. Log into AMO
2. Open an add-on detail page
3. Post a rating
4. Click on the Write a review button to open the review form
5. Notice the rating stars alignment compared to the accompanying text 

### What happened?
The rating stars are misaligned

### What did you expect to happen?
The rating stars are correctly aligned

### Anything else we should know?
The issue also reproduces on the Write/Edit review form displayed on the All reviews page or on the User profile

[Add-on detail]
![image](https://user-images.githubusercontent.com/31961530/115235816-48aa9c00-a123-11eb-8085-fa3b64a7e844.png)

[All reviews/User profile page]
![image](https://user-images.githubusercontent.com/31961530/115235831-4ba58c80-a123-11eb-87f8-cf6079954851.png)

**Comment by bobsilverberg** [comment]
I guess we have no way of knowing if this was introduced last week, or possibly earlier than that? I don't recall anything landing last week that should have affected this. I will take a look to see if I can diagnose/fix it.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/115414686-eb841880-a1fe-11eb-8311-f20b8a4fea95.png)

![image](https://user-images.githubusercontent.com/31961530/115414728-f3dc5380-a1fe-11eb-99d0-386e99d9730c.png)
