### ISSUE TITLE
Add `addonType` property to homepage shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-frontend#10438]
Add `addonType` property to the homepage shelves to help differentiate the type of add-ons it contains (e.g., extensions or themes). This will also handle the number of add-ons displayed across each shelf (4 for extensions, 3 for themes).

**Comment by ioanarusiczki** [comment]
@xlisachan 

I don't see issues with the extensions - adding a collection and a search endpoint without changing the addon count (4 per shelf) it looks good. 

The themes are different: 
the search endpoints with static themes contain more than 3 add-ons (such as ?sort=users&type=statictheme or ?promoted=recommended&sort=random&type=statictheme). Also the collection featured-personas I tested with has 6 themes. 

Frontend does not display the see more links , there are 3 themes displayed (when no custom number is used) but the size is still 266x34. 

This is visible right now on AMO dev https://addons-dev.allizom.org/en-US/firefox/

**Comment by xlisachan** [comment]
Thanks for the update, @ioanarusiczki ! The addonType property was lost - I have opened an issue and submitted a pull request that should fix the appearance of the theme shelves and links.

**Comment by ioanarusiczki** [comment]
This was fixed by https://github.com/mozilla/addons-frontend/issues/10496
