### ISSUE TITLE
Fix the lint issues required to upgrade to eslint-config-airbnb 11

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1043]
Looks like there's a lot of updated incoming rules we're going to need to fix to pass lint.

See https://travis-ci.org/mozilla/addons-frontend/jobs/158381739 via https://github.com/mozilla/addons-frontend/pull/1042

**Comment by kumar303** [comment]
Running into https://github.com/yannickcr/eslint-plugin-react/issues/816 but I can work around it.

**Comment by kumar303** [comment]
It also looks like we can't reuse PropType definitions: https://github.com/yannickcr/eslint-plugin-react/issues/817

**Comment by muffinresearch** [comment]
Fixed by https://github.com/mozilla/addons-frontend/pull/1042
