### ISSUE TITLE
Unexpected result when accessing the blog using a locale or app in the URL

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10443]
From https://github.com/mozilla/addons-frontend/issues/10406#issuecomment-822398312

the 2 URLs 
https://addons-dev.allizom.org/en-US/blog 
https://addons-dev.allizom.org/firefox/blog 

Should either fix themselves and redirect to https://addons-dev.allizom.org/blog/ or show a 404 page.

Right now: (actual)

![another 404](https://user-images.githubusercontent.com/33448286/115226378-d7192080-a117-11eb-802b-cade322ef78c.png)

The 404 pages (probably the expected)

![404](https://user-images.githubusercontent.com/33448286/115226333-c9639b00-a117-11eb-831b-9492008c6981.png)

**Comment by willdurand** [comment]
This should be fixed _via_ https://github.com/mozilla/addons-frontend/issues/10396 (cc @eviljeff)

**Comment by eviljeff** [comment]
`blog` needs to be in `clientAppRoutes` too.  But yeah, that's going away with #10396 so that fixes it instead.

**Comment by willdurand** [comment]
That has been fixed, actually.
