### ISSUE TITLE
Investigate Add-on versions page performance issues

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10446]
The add-on versions pages (/{language}/{app}/addon/{slug}/versions/) often show up in Google Search Console has having bad performance. We should investigate and find ways to improve it.

**Comment by diox** [comment]
Because it shows release notes for each version, there is a slightly higher chance than the rest of the site to display italic content on this page, which is slowing things down a bit. So finding a solution for https://github.com/mozilla/addons-frontend/issues/10478 (at least optimizing the italic font file, or removing it) would be a bonus for this page. This matters on https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/ for instance.

There is also a higher chance than the rest of the pages that we'll end up needing the full font as well, simply because developers might mention translations added in particular languages in the release notes. https://github.com/mozilla/addons-frontend/issues/10534 should help once it lands.

Finally, as with https://github.com/mozilla/addons-frontend/issues/10444 there can be a lot of HTML to transfer, so the same remark I made here still applies: if we could improve caching of the HTML, or serve it faster, or reduce its size, things would improve.

Paris/4G webpagetest: https://www.webpagetest.org/result/210512_BiDcK2_0f7b71eb93ac81102e07d64106ac2785/6/details/#waterfall_view_step1

**Comment by rik** [comment]
From the WebPageTest, the HTML is 357.2 KB gzipped, 1150.3 KB uncompressed. And `redux-store-state` is 1051613. That seems a bit much :)

From a quick scan, a quick win here could be to remove the full text of the GPL license from every version.

**Comment by diox** [comment]
We should look into removing the license text from the API completely when fetching multiple versions (and not even fetch it from the db either in that case). Also, I don't think the text is ever used for built-in licenses, so we should probably remove it from the database itself, although this would be a backwards-incompatible change.

**Comment by diox** [comment]
https://github.com/mozilla/addons-server/issues/17163, https://github.com/mozilla/addons-frontend/issues/10583 and https://github.com/mozilla/addons-frontend/issues/10478 should help. Leaving opened to verify in production.

**Comment by diox** [comment]
https://www.webpagetest.org/result/210521_AiDcPN_8b1c3f6f94bbca4c991b87bfdd7b424e/

It has improved (likely as a result of dropping license text, since HTML is much smaller and takes a lot less time to load) but like in https://github.com/mozilla/addons-frontend/issues/10444, the LCP is often occurring twice, for the same element. I suspect something weird with the fonts, might be just an issue with WebPageTest.

**Comment by rik** [comment]
The issue here is the yellow banner having a different height with or without JS. This shifts the content up, displaying more of the LCP element in the viewport, resulting in a larger largest contentful paint. This may be highly specific to the way release notes are authored but it could be an easy fix.

**Comment by diox** [comment]
Filed as https://github.com/mozilla/addons-frontend/issues/10605
