### ISSUE TITLE
At a resize - the menu from the top of the pages has layout issues 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10458]
This has regressed - on AMO prod right now looks good but not on dev and stage

![broken header](https://user-images.githubusercontent.com/33448286/115552364-17d08100-a261-11eb-8d47-3359c846ed4f.png)

**Comment by bobsilverberg** [comment]
@willdurand @championshuttler This is a regression from the addition of `word-break: break-word;`. ☹️ 

I think we can fix it by overriding that property for just these elements, and hopefully we won't have to do that too often.

**Comment by willdurand** [comment]
ugh, again!

**Comment by bobsilverberg** [comment]
> ugh, again!

My sentiments exactly!

**Comment by championshuttler** [comment]
Can we render that `word-break: break-word;` specifically for safari/ios for now atleast it will save us for meantime to not break things on FF and Chrome? https://stackoverflow.com/questions/16348489/is-there-a-css-hack-for-safari-only-not-chrome

**Comment by bobsilverberg** [comment]
I'm not sure if we want to introduce a safari-only hack. WDYT @willdurand?

**Comment by willdurand** [comment]
> I'm not sure if we want to introduce a safari-only hack. WDYT @willdurand?

If we can only have `word-break: break-word` for Safari, that would be nice but the SO answers have way too many hacks in there so it does not look like there is a good/common solution for targeting Safari only (I did try `-webkit-word-break` but that doesn't work).

**Comment by championshuttler** [comment]
Hey @willdurand , its working I guess

--- a/src/amo/components/App/styles.scss
+++ b/src/amo/components/App/styles.scss
@@ -35,7 +35,11 @@ textarea {
   // container does not have a well-defined width.
   overflow-wrap: anywhere;
   // This is needed for Safari, which does not support `anywhere`.
-  word-break: break-word;
+  @media not all and (min-resolution:.001dpcm) {
+    @supports (-webkit-appearance:none) {
+      word-break: break-word;
+    }
+}
 }

 body {

**Comment by bobsilverberg** [comment]
My concerns are the same as @willdurand's. What might work now, might not work in a future version of Safari, based on the multitude of hacks that seem to be suggested for different versions. We definitely don't want something we have to change to support future versions, so I'm a r- on this safari-only approach. WDYT @willdurand?

**Comment by willdurand** [comment]
> My concerns are the same as @willdurand's. What might work now, might not work in a future version of Safari, based on the multitude of hacks that seem to be suggested for different versions. We definitely don't want something we have to change to support future versions, so I'm a r- on this safari-only approach. WDYT @willdurand?

Yes, let's keep what we have and see if it breaks other things. If it's only 3 or 4 elements that we need to adjust, it's fine. More than that and we'll have to consider something else.

**Comment by ioanarusiczki** [comment]
@bobsilverberg On desktop - on non-FF browsers on AMO stage - More overlaps the search bar 
It is not reproducible on Firefox.

Chrome versus Firefox

![Chrome versus Firefox](https://user-images.githubusercontent.com/33448286/115674028-186d2400-a302-11eb-86be-d17767787566.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I was wrong about this not being reproducible on FF, filed it.
