### ISSUE TITLE
Flag button is breaking on small screen

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-frontend#10452]
While triaging #10449, I found Flag button in reviews is breaking and it was possible regression from `word-break:break-word` we added for safari 😢 

![image](https://user-images.githubusercontent.com/22130317/115436013-18005a80-a228-11eb-89cb-2d174bd43ecf.png)

**Comment by diox** [comment]
@championshuttler can you provide more information regarding how to reproduce for this issue ? I don't see the problem even on small screens. Do I need a specific browser, is it happening on a specific page, are you seeing this in production, on your local environment, on dev or stage ?

**Comment by championshuttler** [comment]
@diox So I ran amo:dev locally and resize the browser to mobile screen in Firefox 88 happening in other browsers too, if you click on Flag button it will break,  its happening on desktop too, I tested for http://localhost:3000/en-US/firefox/addon/search_by_image/reviews, also @bobsilverberg also tested see in #10449, I am attaching video for your reference


https://user-images.githubusercontent.com/22130317/115529940-f5feea80-a2b0-11eb-832c-a9f7cd12d680.mov

**Comment by AlexandraMoga** [comment]
I confirm that I can reproduce this too on -dev and stage both on desktop(Win10, FF88) and mobile (Android, latest Fenix).

**Comment by ioanarusiczki** [comment]
This issue is not reproducible on AMO -dev with FF88 (Win10) or Fenix - Android 

![fixed flag](https://user-images.githubusercontent.com/33448286/116046252-bd9c3b00-a627-11eb-8857-5b52bac57ff1.png)
