### ISSUE TITLE
Add un-install modal window to disco pane

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1045]
We have a little modal that pops up and tells users where an add-on lives once it is installed, but what about when they un-install? We need to inform the user that:
- the add-on has been turned off, not removed
- where the add-on lives
- and what they can do with the add-on in prefs

No design for this yet, but it will be the same as the install modal.

**Comment by muffinresearch** [comment]
Is this going to be unique to the disco pane or would we consider doing something like this for general Add-on uninstalls too?

**Comment by muffinresearch** [comment]
I don't think we're going to do this in content since we're moving to relying on doing what the browser does based on installation. If the browser doesn't show a notification for uninstalls I don't think we should add one from content.
