### ISSUE TITLE
Disable `download_cta_experiment`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10469]
See: https://bugzilla.mozilla.org/show_bug.cgi?id=1697793

---

The experiment relies on `utm_campaign`, which is also used for RTAMO. A value other than `non-fx-button` will break RTAMO and the `download_cta_experiment` experiment changes it, which is why we should disable this experiment and re-enable it once we have a plan.

**Comment by ioanarusiczki** [comment]
@willdurand 

I checked on AMO dev and AMO stage - with Chrome and Edge - I no longer see the experiment cookie, new-cta not displayed. 
Looks good.
