### ISSUE TITLE
Remove `search-themes` endpoint from homepage shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-frontend#10463]
Pending #10439, as the `addon_type` property for homepage shelves will differentiate the type of shelves, `search-themes` endpoint will not be used/needed. Remove `search-themes` endpoint and clean up tests.

**Comment by ioanarusiczki** [comment]
@xlisachan I don't see anything broken on AMO Dev - I added a collection with extensions, one with static themes. Also adding a search query using extensions or static themes worked for me. 

Shelf layouts look good as it can be seen https://addons-dev.allizom.org/en-US/firefox/

Verified with FF88(Win10).
