### ISSUE TITLE
Try using `utm_term` for download attribution

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10479]
This is a spin-off from https://github.com/mozilla/addons-frontend/issues/10476. We want to be able to see, in GA for mozilla.org, whether a download was attributed the existing CTA or the new CTA. We were using `utm_campaign` for that, but we cannot continue to do that because of RTAMO.

Let's try using `utm_term` for that instead. This won't solve the redash query issue, but will allow us to check for conversions on mozilla.org for the two different CTAs.

After deploying it to dev, we can check the data in GA for mozilla.org to see if it flows through.

According to the GA docs, `utm_term` becomes `keyword` when generating a report.

**Comment by willdurand** [comment]
According to GA docs and Wikipedia:

> utm_term: Identify paid search keywords. If you're manually tagging paid keyword campaigns, you should also use utm_term to specify the keyword.

**Comment by bobsilverberg** [comment]
> According to GA docs and Wikipedia:
> 
> > utm_term: Identify paid search keywords. If you're manually tagging paid keyword campaigns, you should also use utm_term to specify the keyword.
> 
> Therefore, I am not sure we should use `utm_term` with other values than search keywords.

We would definitely be *misusing* it, no argument from me there, but we're not using it for anything else, so I don't think it would be the end of the world. It also looks, however, as if we might be able to continue using `utm_campaign`, based on the discussion at https://github.com/mozilla/addons-frontend/issues/10476#issuecomment-825078779, so let's resolve that first and maybe this one can simply be closed.

**Comment by bobsilverberg** [comment]
After speaking with Dan Brown and Alex Gibson of the mozilla.org team, it sounds like there are no problems from their end with us using `utm_term`. We would prefer to [use a custom dimension](https://github.com/mozilla/bedrock/issues/10175), but we might not be able to get that set up by next week's tag/push, so we're going to move forward with using `utm_term` for now.

**Comment by willdurand** [comment]
> After speaking with Dan Brown and Alex Gibson of the mozilla.org team, it sounds like there are no problems from their end with us using `utm_term`. We would prefer to [use a custom dimension](https://github.com/mozilla/bedrock/issues/10175), but we might not be able to get that set up by next week's tag/push, so we're going to move forward with using `utm_term` for now.

I haven't found any evidence that it would affect _our_ SEO either and i also think hat we should move forward with using `utm_term` for now. The experiment is short (2 weeks) and we'd like the results ASAP so a dependency on another team doesn't seem like a good idea right now.

We should think about a more long term solution, though (and the custom dimension might be useful in the future).

**Comment by bobsilverberg** [comment]
We discussed writing the patch for this in a way that the URL param was itself parameterized, in order to make is simpler to substitute a custom dimension for `utm_term` when one is available, *but* I think we might actually want to pass `variant` and `addonId` in *different* custom dimensions, if we really need both, and that would mean more changes and therefore I don't think it's worth parameterizing it at this point.

**Comment by willdurand** [comment]
Oh ok, I understand now. Thanks!

**Comment by ioanarusiczki** [comment]
@bobsilverberg This looks good for AMO dev/stage - the utm_term is present and it is using a variant and addonID. 
I added more detailed results here https://github.com/mozilla/addons-frontend/issues/10518#issuecomment-832629568

I've noticed on non-FF browsers the presence of the experiment layout on the blog for the add-on cards.  So I'll tag @willdurand too because I don't know if the behaviors below are expected:

- on Edge or Chrome the add-on cards show the UX experiment present at all times (no matter what cookie AMO dev or AMO stage has meaning current-cta or new-cta) 

- when I click the Download Firefox and get the extension button mozilla.org opens in a new tab and I have utm_term as parameter but without `experiment` or `variation`

![the experiment](https://user-images.githubusercontent.com/33448286/117147410-19726c80-ad6a-11eb-9735-584e05fc1f0d.gif)

**Comment by willdurand** [comment]
> [](https://github.com/mozilla/addons-frontend/issues/10518#issuecomment-832629568)
> 
> I've noticed on non-FF browsers the presence of the experiment layout on the blog for the add-on cards. So I'll tag @willdurand too because I don't know if the behaviors below are expected:
> 
>     * on Edge or Chrome the add-on cards show the UX experiment present at all times (no matter what cookie AMO dev or AMO stage has meaning current-cta or new-cta)
> 
>     * when I click the Download Firefox and get the extension button mozilla.org opens in a new tab and I have utm_term as parameter but without `experiment` or `variation`

Yep, everything here is expected: the blog does not run any experiment, the design of the blog uses the "new style" of the download buttons. That's also why there is no `experiment`/`variation` and the `utm_term` value is a bit different (it contains "blog").
