### ISSUE TITLE
Make sure we set `utm_campaign` to `non-fx-button` in "download FF" link

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10470]
See: bugzilla.mozilla.org/show_bug.cgi?id=1697793

---

The RTAMO flow (see: https://docs.google.com/document/d/1vXpEg_ypqr-eiXu6pWBDiyQWwf_rxYhHAGnsp3qwpCo/edit#heading=h.qfzhhiib3sm5) works when specific UTM params are defined with fixed values. For example, `utm_campaign` should always be `non-fx-button`.

**Comment by ioanarusiczki** [comment]
@willdurand 

Clicking the download button on the detail page: 

utm_campaign: non-fx-button
utm_content: rta:QGNvbnRhaW4tZmFjZWJvb2s
utm_medium: referral
utm_source: addons.mozilla.org


Clicking "Download Firefox" button:
utm_campaign: non-fx-button
utm_content: header-download-button
utm_medium: referral
utm_source: addons.mozilla.org

Verified on AMO stage - with Chrome
