### ISSUE TITLE
remove the variable italic font file

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10478]
spun out from #10290

We use italics very sparingly on frontend - that I can see, only the UsersUnsubscribe-content-notification class, and developer defined content. Using the variable font file is a net saving when we're using many different font weights; but it can be a net cost if we only use 1 or 2 - which we appear to, and not even on the same page - so we should switch italic back to single font files for italics.

**Comment by eviljeff** [comment]
attempted this but I'm not totally convinced - it's possible to use 2 font files easily by having both italic and bold italic

**Comment by diox** [comment]
As mentioned in https://github.com/mozilla/addons-frontend/issues/10446 the italic shows up in versions pages every now and then because developers sometimes use it in release notes. At the very least it should be optimized like the other fonts, but possibly completely dropped if we can (while maintaining italics support)

**Comment by diox** [comment]
As mentioned in https://github.com/mozilla/addons-frontend/issues/10290#issuecomment-811794877 if the italic font is dropped, browsers can make up a fake italic themselves. The main issue is that it doesn't work in Chrome (and Edge): it displays the text with the normal, non-italic style.

Given that the italics are only really used once in the edit profile and where developers use it in their descriptions/release notes, and that it falls back nicely, I think completely removing the file to improve client performance is worth it.

**Comment by ioanarusiczki** [comment]
@diox I tested this using html italic tag on edit user profile - Biography field and into the Description, Developer comments and release(version) notes on add-on detail pages. 

As you mentioned above, for Chorme and Edge - italic is no longer available. 

On FF88(Win10) - works fine, this is the add-on https://addons-dev.allizom.org/en-US/firefox/addon/dark22reader/
User profile page https://addons-dev.allizom.org/en-US/firefox/user/10641572/

**Comment by diox** [comment]
For Chrome, it's tracked by this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=971610
