### ISSUE TITLE
Replace mozilla-version-comparator

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10474]
We do have our own comparator now! See: https://github.com/mozilla/addons-moz-compare

For QA: this affects the compatibility logic, more specifically the browser version is compared to the min/max version of an add-on.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and stage and these are my results:

- add-on is built for a higher Firefox version:
![image](https://user-images.githubusercontent.com/31961530/117019018-b64af080-acfd-11eb-9191-2434276c1ce2.png)

- add-on is built for a lower Firefox version - I've used a language pack, where strict compatibility is taken into consideration (*)
![image](https://user-images.githubusercontent.com/31961530/117021097-b64bf000-acff-11eb-9d63-7083abdda9ad.png)

- I've also tested around language packs which normally have a stricter dependency on the Firefox version they're installed in; I've used a language pack with multiple versions and checked that the versions are correctly selected for FF 88, 89 and 90.

@willdurand I don't remember exactly how a webextension `strict_min_version` is handled. I've created an [add-on](https://addons-dev.allizom.org/en-US/developers/addon/min-max/versions/1692620) that is supposed to be compatible with Firefox 77, but it can be successfully installed in FF 88 as well.

**Comment by willdurand** [comment]
> @willdurand I don't remember exactly how a webextension `strict_min_version` is handled. I've created an [add-on](https://addons-dev.allizom.org/en-US/developers/addon/min-max/versions/1692620) that is supposed to be compatible with Firefox 77, but it can be successfully installed in FF 88 as well.

I thought it was strict "max" version? We should always respect min versions.

**Comment by AlexandraMoga** [comment]
When I'm uploading an add-on with a `strict_max_version` I do get a validation warning about max version not being required:

```
Warning: "strict_max_version" shouldn't be used unless the add-on is expected not to work with future versions of Firefox.
```

There is no warning for min version though, so I'm no longer sure what is expected in that case.

**Comment by willdurand** [comment]
> When I'm uploading an add-on with a strict_max_version I do get a validation warning about max version not being required:
> [...snip...]
> There is no warning for min version though, so I'm no longer sure what is expected in that case.

mokay, I don't know either to be honest.

Reading [about `strict_min_version`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings), I think being able to install the add-on on FF 88 is correct.

**Comment by AlexandraMoga** [comment]
Ok, so after reading through my comments again, I think I need to rephrase some things. 

The [documentation](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings) says the following about `strict_max_version`:
```
Maximum version of Gecko to support. If the Firefox version on which the extension is being installed or run is above this version, then the extension will be disabled, or not permitted to be installed.
```

So, if my manifest has the following set-up, I would assume this extension is not installable in FF 88 (or any other FF version above 68.0).  
```
 "browser_specific_settings": {
     "gecko": {
          "strict_min_version": "57.0",
	  "strict_max_version": "68.0"
  }
}
```
However, [this extension](https://addons-dev.allizom.org/en-US/firefox/addon/lower-than-current-ff-version/) can be successfully installed from the frontend and does not appear disabled in add-ons manager.

Another interesting fact: if I'm uploading the same extension as unlisted and then try to install the `.xpi` from DevHub, the Firefox install prompt will prevent the installation saying that the add-on is not compatible with FF 88.0.

I've tried to find something relevant through our closed issues where the logic for `strict_max_version` is explained but I couldn't find anything definitive.

**Comment by willdurand** [comment]
> However, [this extension](https://addons-dev.allizom.org/en-US/firefox/addon/lower-than-current-ff-version/) can be successfully installed from the frontend and does not appear disabled in add-ons manager.

ha well.. I don't know then. I know AMO does not check the max version unless there `is_strict_compatibility_enabled` is `true` but I don't know how that is set. Maybe in DevHub? cc @diox

**Comment by wagnerand** [comment]
> AMO doesn't set is_strict_compatibility_enabled for add-ons that specify a strict_max_version

Maybe we should? If a developer explicitly adds that to their manifest, shouldn't we take that into account?
