### ISSUE TITLE
Download button on non-Firefox browsers is truncated in various locales

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10472]
### Describe the problem and steps to reproduce it:
Load an add-on detail page on mobile with Chrome, in French or German.

### What happened?
The download with Firefox button next to the add-on summary is truncated

### What did you expect to happen?
The download with Firefox button text should be fully visible

### Anything else we should know?
![facebook_container_mobile_fr](https://user-images.githubusercontent.com/187006/115721878-be5e7400-a37e-11eb-9680-51a2ef5ba7f0.png)

**Comment by willdurand** [comment]
I think we fixed a similar problem not too long ago (probably for the other version of the button). IIRC our `.Button` sets `white-space` in a way that does what's shown in the screenshot above.

**Comment by bobsilverberg** [comment]
We don't seem to have a default for `white-space` for `.Button`, but it is set for specific buttons in a number of places. We need to be careful, because we do want `nowrap` at some screen resolutions. One thing to note is that this problem will be somewhat mitigated if we end up keeping the new buttons from the experiment as the text will be a bit shorter, but I agree we should fix this.

**Comment by championshuttler** [comment]
This bug was also mentioned in some bug for the yellow banner IIRC, I had patch locally @bobsilverberg if you are not working on it atm (I see you self-assigned it though), I would raise the PR , thanks

**Comment by bobsilverberg** [comment]
> This bug was also mentioned in some bug for the yellow banner IIRC, I had patch locally @bobsilverberg if you are not working on it atm (I see you self-assigned it though), I would raise the PR , thanks

Please feel free to submit your PR. I will assign it to you. Thanks!

**Comment by ioanarusiczki** [comment]
@bobsilverberg @championshuttler 

This is verified on Chrome - Android 10
![french](https://user-images.githubusercontent.com/33448286/116411206-2b21b480-a83e-11eb-9cc6-a82c8193ab01.png)
![German](https://user-images.githubusercontent.com/33448286/116411211-2bba4b00-a83e-11eb-9a61-6c1982685c03.png)
