### ISSUE TITLE
Deal with the need to revert `utm_campaign` changes

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10476]
We had to [revert the recent changes to the value of `utm_campaign`](https://github.com/mozilla/addons-frontend/issues/10470) for the Download Firefox button because they broke RTAMO. Those changes were required for the following:

1. To be able to attribute Firefox downloads on mozilla.org to either the new CTA or the old CTA.
2. To capture the `addonId` in telemetry so it can be reported upon. This is being used to enable the report that @tublitzed created at https://sql.telemetry.mozilla.org/queries/79488/source#197431.

We therefore need a different approach for both of those items. Here are some ideas:
- Use a different `utm` param to capture attribution data on mozilla.org. We have an unused `utm` param called `utm_term` which can possibly be used for this. We need to verify that we can report against that in Google Analytics. We might also be able to use `utm_medium`, although I understand from @muffinresearch that that is required to remain as `referral`.
- If we use `utm_term` to capture the same data as the reverted `utm_campaign`, maybe we can use that in redash. Do we know if that is currently captured by telemetry? Does telemetry capture only specific `utm` params, or will it capture *any* `utm` params that are on the URL? @willdurand Do you know the answer to this?
- Can we possibly use the encoded GUID that is currently stored in `utm_content` that powers RTAMO? We would need to read it and decode it in redash, which may or may not be possible.

**Comment by bobsilverberg** [comment]
Partially answering my own question, but still looking for confirmation, but in redash I only see `attribution.campaign`, `attribution.content`, `attribution.medium` and `attribution.source`. I don't see `attribution.term`, so I assume it's not captured, or maybe it just hasn't been captured because it's never been used?

**Comment by willdurand** [comment]
> Partially answering my own question, but still looking for confirmation, in redash I only see `attribution.campaign`, `attribution.content`, `attribution.medium` and `attribution.source`. I don't see `attribution.term`, so I assume it's not captured, or maybe it just hasn't been captured because it's never been used?

If you look at `clients_daily` only, not everything is exposed (it is a derived view).

From a quick look at the FF code, it looks like we support the following parameters for attribution: https://searchfox.org/mozilla-central/source/browser/components/attribution/AttributionCode.jsm#45-54

What's interesting is the following: https://searchfox.org/mozilla-central/source/browser/components/attribution/AttributionCode.jsm#198. It looks like we could use `campaign` and that would override `utm_campaign` in Telemetry, but that could make RTAMO continue to work.

That being said @mixedpuppy is likely the best person to ask.

**Comment by willdurand** [comment]
>     * We might also be able to use `utm_medium`, although I understand from @muffinresearch that that is required to remain as `referral`.

Yep, see: https://docs.google.com/document/d/1BukJcOsfXoP651IN8P2BTZ8jpc83KAa3caMKlpjTxDQ/edit#heading=h.z6i8v5j3q0gy

**Comment by bobsilverberg** [comment]
> 
> If you look at `clients_daily` only, not everything is exposed (it is a derived view).
> 
> From a quick look at the FF code, it looks like we support the following parameters for attribution: [searchfox.org/mozilla-central/source/browser/components/attribution/AttributionCode.jsm#45-54](https://searchfox.org/mozilla-central/source/browser/components/attribution/AttributionCode.jsm#45-54)
> 
> What's interesting is the following: [searchfox.org/mozilla-central/source/browser/components/attribution/AttributionCode.jsm#198](https://searchfox.org/mozilla-central/source/browser/components/attribution/AttributionCode.jsm#198). It looks like we could use `campaign` and that would override `utm_campaign` in Telemetry, but that could make RTAMO continue to work.
> 
> That being said @mixedpuppy is likely the best person to ask.

Interesting, so we could use `campaign` on the URL and it would be captured by telemetry, but might not interfere with the RTAMO code. Although https://searchfox.org/mozilla-central/source/browser/components/newtab/aboutwelcome/lib/AboutWelcomeDefaults.jsm#406 references `attributionData`, so I would be concerned that our new `campaign` param would also be used for that and therefore it *would* break RTAMO. 

@mixedpuppy Can you comment on the above?

**Comment by willdurand** [comment]
>  I would be concerned that our new `campaign` param would also be used for that and therefore it _would_ break RTAMO.

Ha, right. That might not work but that also depends on what we want. If we want `utm_campaign` for GA, that _could_ work but if we want `utm_campaign` for GA _and_ Telemetry, that's a different thing indeed.

**Comment by bobsilverberg** [comment]
> > I would be concerned that our new `campaign` param would also be used for that and therefore it _would_ break RTAMO.
> 
> Ha, right. That might not work but that also depends on what we want. If we want `utm_campaign` for GA, that _could_ work but if we want `utm_campaign` for GA _and_ Telemetry, that's a different thing indeed.

Yeah, the problem is that we need to use `utm_campaign` for GA, and we *want* to use the same value for telemetry, but we want to use a *different* value for RTAMO. If both RTAMO and telemetry are based on that `attributionData` code, then we can't use our new value for that. *But*, if we can get `utm_content` to work for telemetry data (as I think we've seen it can), then we can just forget about using any form of `campaign` for telemetry data. This would leave us with using `utm_campaign` with the new values for GA, using `campaign` with the existing values for RTAMO, and not using any form of `campaign` for telemetry.

Does this make sense?

**Comment by willdurand** [comment]
> Does this make sense?

I think it does, yes. We should make sure that the `utm_campaign`/`campaign` trick will work in FF first. Assuming this is okay, we can probably follow your suggestion.

**Comment by willdurand** [comment]
I looked at the code again and I discovered a few things. TL;DR we cannot use `campaign` and `utm_campaign` to avoid breaking RTAMO.

1. RTAMO does not work on MacOS because mozilla.org does not pass any attribution data to the "thanks page" during the download FF flow. The URL of this page is stored in the MacOS's quarantine database. This database is [read by Firefox to find the download URL and parse it](https://searchfox.org/mozilla-central/source/browser/components/attribution/AttributionCode.jsm#268) to get the attribution data. AFAICT RTAMO has _never_ worked on MacOS, see: https://github.com/mozilla/bedrock/issues/9346
2. Enabling RTAMO for MacOS is a matter of enabling a feature flag in bedrock **but** that wouldn't allow us to use the trick mentioned above because the attribution data is normalized when added to the "thanks" URL, see: https://github.com/mozilla/bedrock/blob/e6da436be7480263be54a72673159a489b23ee7e/media/js/base/stub-attribution-macos.js#L73-L97
3. On Windows, which seems to be the only OS supporting RTAMO at the time of writing, the attribution data is passed in a different manner but there is also a normalization step, preventing us to `campaign`: https://github.com/mozilla/bedrock/blob/e6da436be7480263be54a72673159a489b23ee7e/media/js/base/stub-attribution.js#L248-L272

**Comment by mixedpuppy** [comment]
> It looks like we could use campaign and that would override utm_campaign in Telemetry, but that could make RTAMO continue to work.

I don't think you can use both campaign and utm_campaign, I don't think you can use campaign directly at all.  My recollection of the reason for the two is that on windows the "utm" was stripped, but due to how attribution works on osx, it is not stripped.  So you have to pass utm_campaign to the download service, but on windows the attribution file contains campaign, and on osx the quarantine database contains utm_campaign.

> AFAICT RTAMO has never worked on MacOS

Have you verified that?  osx attribution works different, it gets tracked by the os itself.  The initial attempt at reading the quarantine database did not work, but it was rewritten to do a lower level access.  As I recall, the attributes need to be on the button that the user clicks on to initiate the download, and did not need to make it through to the last page.

nalexander (on slack) was the last to work on the firefox side of that, if it's not working he'd probably have some insight.

https://bugzilla.mozilla.org/show_bug.cgi?id=1525076

**Comment by mixedpuppy** [comment]
>  As I recall, the attributes need to be on the button that the user clicks on to initiate the download, and did not need to make it through to the last page.

The details on this are foggy in my mind, so I could be wrong here.

**Comment by willdurand** [comment]
> Have you verified that?

Yes but I should add something: it has never worked for AMO because AMO goes to mozilla.org, which redirects the user to a "thanks page" when clicking the download FF button. In the bug you linked, there are STR but for a different page. With this page (or with the script you gave to QA), RTAMO would work because the query string is stored in the quarantine DB.

**Comment by bobsilverberg** [comment]
This seems like a reasonable place to continue to discuss our options. I will open new issue(s) when we decide on what we want to do moving forward.

To review, there are two problems we need to solve after reverting the changes to `utm_campaign`:

1. The report that @tublitzed created at sql.telemetry.mozilla.org/queries/79488/source#197431 relies on there being an `addonId` in `utm_campaign`, but that is no longer the case.
2. We were planning on using `utm_campaign` to report on conversions on mozilla.org for the two variations in the experiment. With `utm_campaign` now having a static value, it cannot be used for that reporting.

Note that we do not need the new values for `utm_campaign` in order to analyze the performance of the experiment on AMO - we were only going to use it to verify that downloads from mozilla.org do not regress.

For 1, above, it's possible we can use the `guid` that is embedded in `utm_content` to create a similar query. @muffinresearch do you know where we stand with this?

For 2, there have been a couple of suggestions:
1. Use `utm_term` to differentiate the experiment variations. This would be captured by GA and can be used for reporting. The main problem with this is that we'd be misusing `utm_term` which is supposed to be used for a search term. It's possible this could have an impact on SEO, but we're not sure about that. I discussed this with agibson and he didn't feel it would interfere with mozilla.org's own use of `utm_param`, so I think it is feasible, but there may be a better option.
2. If we pass `experiment` and `variation` on the URL to mozilla.org, they will be stored in telemetry when Firefox is installed. agibson doesn't feel that our use of these will conflict with anything that mozilla.org is currently doing. If these are stored, then we could potentially report on the performance of the different variations using telemetry data, rather than GA. One potential problem with this, however, is that this will only allow us to count *installs* and not *downloads*. Maybe that is good enough, as we can just compare the two variations and make sure that the new one doesn't regress installs, but it is true that installs and downloads are two different things.

**Comment by jvillalobos** [comment]
> One potential problem with this, however, is that this will only allow us to count installs and not downloads. Maybe that is good enough

No, we should be able to measure both. It's important to understand the impact of our changes to the different stages in the funnel.

**Comment by bobsilverberg** [comment]
As discussed in yesterday's meeting, there are downsides to both of the approaches mentioned above. A third option might be to use a custom GA dimension, which is probably the best route because it is most "correct", but it requires cooperation and buy-in from the team that manages GA for mozilla.org. I have opened [an issue](https://github.com/mozilla/bedrock/issues/10175) about it with them.

**Comment by bobsilverberg** [comment]
After speaking with Jeff Klukas (Sr Staff Data Engineer), it sounds like our best move forward for Telemetry is to start reporting `experiment` and `variation` by adding them to the links that we generate to mozilla.org for downloads. We can then verify that they do appear in telemetry data, after which he said he would work to get them included in `clients_daily`. I will open an issue for this. Note that this does not affect the current experiment (for which we still plan to use exclusively GA data), but will be needed for future experiments.

**Comment by willdurand** [comment]
> After speaking with Jeff Klukas (Sr Staff Data Engineer), it sounds like our best move forward for Telemetry is to start reporting `experiment` and `variation` by adding them to the links that we generate to mozilla.org for downloads. We can then verify that they do appear in telemetry data, after which he said he would work to get them included in `clients_daily`. I will open an issue for this. Note that this does not affect the current experiment (for which we still plan to use exclusively GA data), but will be needed for future experiments.

@mixedpuppy you've been involved in discussions about these two params. It is supposed to work, right? Do you know if they have been used for real experiments?

**Comment by bobsilverberg** [comment]
This can be closed. We're now using `utm_term` for GA, and `experiment` and `variation` for telemetry, and @muffinresearch has created a new redash query at https://sql.telemetry.mozilla.org/queries/79573/source#197658 which draws the add-on identifier from `attribution.content` instead of `attribution.campaign`.
