### ISSUE TITLE
The search endpoint returns 500 for unknown types

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#10480]
### Describe the problem and steps to reproduce it:

We got paged for too many 500 errors on the website, and it turns out it was triggered by a crawler that sent requests to the `search/`.

It looks like any request that has a unknown type will return 500, for example these ones

```
/en-US/firefox/search/?category=foo&type=bar1
/en-US/firefox/search/?category=foo&type=bar2
/en-US/firefox/search/?category=foo&type=bar3
/en-US/firefox/search/?category=foo&type=bar4
... ...
```

The log shows the following:

```
Apr 22 20:38:05 ip-172-31-10-11 docker-addons-frontend[5194]: {"EnvVersion":"2.0","Fields":{"amo_request_id":"7d400b19-5aa4-4d22-9507-e315be1bdc19","msg":"Caught an unexpected error while handling the request: Error: \"bar1\" not found in VISIBLE_ADDON_TYPES_MAPPING"},"Hostname":"ip-172-31-10-11","Logger":"amo","Pid":236,"Severity":3,"Timestamp":1619123885841362400,"Type":"app.log","severity":500}
Apr 22 20:38:05 ip-172-31-10-11 docker-addons-frontend[5194]: {"EnvVersion":"2.0","Fields":{"amo_request_id":"7d400b19-5aa4-4d22-9507-e315be1bdc19","msg":"Showing 500 page for error: Error: \"bar1\" not found in VISIBLE_ADDON_TYPES_MAPPING"},"Hostname":"ip-172-31-10-11","Logger":"amo","Pid":236,"Severity":3,"Timestamp":1619123885841450800,"Type":"app.log","severity":500}
Apr 22 20:38:05 ip-172-31-10-11 docker-addons-frontend[5194]: {"EnvVersion":"2.0","Fields":{"amo_request_id":"7d400b19-5aa4-4d22-9507-e315be1bdc19","msg":"{}"},"Hostname":"ip-172-31-10-11","Logger":"amo","Pid":236,"Severity":3,"Timestamp":1619123885841501400,"Type":"app.log","severity":500}
```

### What happened?

As described as the above.

### What did you expect to happen?
The unknown types shouldn't cause 500s. This is false positive and causes a lot of noise to our monitoring since we monitor 500s for site usability and healthiness, and in this case, the site is perfectly functional.

### Anything else we should know?

n/a

**Comment by bobsilverberg** [comment]
Is this a fontend bug or is it a server bug? Should the API be returning a 500?

**Comment by bobsilverberg** [comment]
Oh, wait, it's not the API returning a 500, is it? It's the frontend.

**Comment by willdurand** [comment]
> Oh, wait, it's not the API returning a 500, is it? It's the frontend.

It's a frontend bug because when both type and category are passed, we try to build a `pathname` based on the type and one of the functions throws an error for invalid types.

**Comment by AlexandraMoga** [comment]
I've verified this issue on -dev and these are my results:

The links that used to cause a server error are now returning a 404:
https://addons-dev.allizom.org/en-US/firefox/search/?category=foo&type=bar
![image](https://user-images.githubusercontent.com/31961530/117013616-b2689f80-acf8-11eb-8ec7-42ada04f6498.png)


URLs are being built if a valid combination of `category` and `type` parameters is used:
https://addons-dev.allizom.org/en-US/firefox/search/?category=shopping&type=extension => https://addons-dev.allizom.org/en-US/firefox/extensions/category/shopping/
https://addons-dev.allizom.org/en-US/firefox/search/?category=fashion&type=statictheme => https://addons-dev.allizom.org/en-US/firefox/themes/category/fashion/
