### ISSUE TITLE
Add-on icon is center aligned in the in the Addon summary card header

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10483]
### Describe the problem and steps to reproduce it:
1. Open the detail page of an add-on with a longer name - see https://addons.mozilla.org/en-US/firefox/addon/youtube_downloader_webx/
2. Navigate to All reviews page for this add-on (or any other page that displays the `AddonSummaryCard` - i.e. all versions page, license page, etc)
3. Notice the add-on icon position in relation to the add-on name

### What happened?
The icon is center-aligned 

### What did you expect to happen?
The icon should be aligned to the top

[current - center alignment]
![image](https://user-images.githubusercontent.com/31961530/115872856-f3d09380-a44a-11eb-92d3-1170ef3f3856.png)

[proposed alignment]
![image](https://user-images.githubusercontent.com/31961530/115872822-eca98580-a44a-11eb-8df9-8d6e3e1f7146.png)

**Comment by AtharvaParkale** [comment]
I would like to work on this issue.

**Comment by NegiAkash890** [comment]
This issue was closed by MR #10502.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on FF88, Win10:

![image](https://user-images.githubusercontent.com/31961530/117420316-220fa200-af26-11eb-90db-b5304ebd8e4e.png)
