### ISSUE TITLE
Fix addon_type property for homepage shelves

### ISSUE THREAD

**Issue by xlisachan** [mozilla/addons-frontend#10496]
Per QA feedback in #10357 and #10438, themes are not displaying correctly for homepage shelves.

The shelves are missing the`addonType` property.

**Comment by eviljeff** [comment]
does the missing `addonType` property explain "Frontend does not display the see more links" too?

**Comment by xlisachan** [comment]
Correcting the missing `addonType` property fixes the link issue as well - 
Before fix:
<img width="646" alt="Screen Shot 2021-04-27 at 12 03 25 PM" src="https://user-images.githubusercontent.com/28129806/116274575-ce949b80-a750-11eb-82ef-7b2b6b9c9a47.png">

After fix:
<img width="650" alt="Screen Shot 2021-04-27 at 12 02 23 PM" src="https://user-images.githubusercontent.com/28129806/116274653-dbb18a80-a750-11eb-92fb-17f091ca9e10.png">

**Comment by ioanarusiczki** [comment]
@willdurand 
- See more links and the size of themes are ok.

![looks good](https://user-images.githubusercontent.com/33448286/116518389-d8e1a180-a8d8-11eb-9806-137b9b06ef6d.png)

- when resizing the screen at 850 px there are still issues - Filed https://github.com/mozilla/addons-frontend/issues/10509
