### ISSUE TITLE
Include CSS style before `meta` tags

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10492]
Although it's unclear whether this is going to help (and I could not find a lot of documentation about it), we'd like to move the tags to include the CSS _before_ the `meta` tags in `<head>`. There shouldn't be any negative impact and it's a fairly small change so we decided to accept it.

For QA: in the source code of the page, the `link` to the style should be above most of the `meta` tags.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev - FF88(Win10). 

![css moved](https://user-images.githubusercontent.com/33448286/116409183-44296600-a83c-11eb-90cc-9d54ee44b1e9.png)
