### ISSUE TITLE
Lots of 'Failed to parse appversion for client app' warnings

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#10493]
Stackdriver logs a lot of warnings from https://github.com/mozilla/addons-frontend/blob/cabfc342cdbd1fed6c9907051cdedceb8998971a/src/amo/api/index.js#L253, more than 40k entries per hour on average during low times of the day.

Do we need that warning to be logged? Is there anything we can do to reduce the amount?

**Comment by willdurand** [comment]
It's not a p2: this isn't a new issue and, although it generates some noise in the logs, it's not really important.

That being said, we could look at some of the entries and, if they make sense, we could downgrade the log level of the statement linked above.

**Comment by wagnerand** [comment]
Fair enough. But it causes additional effort whenever I (or someone else) have to dig through the logs, so it would be good to address it sooner rather than later.
