### ISSUE TITLE
add tests to check we don't regress sitemap assuming page_size

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10498]
in mozilla/addons-server#16959 (and others from https://github.com/orgs/mozilla/projects/156) we generate the correct number of paginated urls by assuming the default page_size of 25 results per page - i.e. the api request doesn't include `page_size=xx`.  We need to add a test to confirm that we continue to request without setting page_size for the following pages:
- ratings
- category results (re-uses search)

note: if we _do_ need to change frontend to request a different number of results, that's fine, we just need to add a constant to addons-server to match it, and update the sitemap code to use it.

**Comment by eviljeff** [comment]
After a brief look at this, it's not clear to me exactly what tests are needed here - testing a negative, that a parameter _isn't_ present is a challenge because there are multiple levels in the call stack before the underlying `callApi` that could add  `page_size` to the function parameters.

**Comment by bobsilverberg** [comment]
> After a brief look at this, it's not clear to me exactly what tests are needed here - testing a negative, that a parameter _isn't_ present is a challenge because there are multiple levels in the call stack before the underlying `callApi` that could add `page_size` to the function parameters.

I haven't looked into what you need to do, but we do have tests that verify what parameters are passed to APIs, which would fail if a new param was added that was not expected, so maybe our existing tests are good enough?

You just want to make sure that for certain API calls we don't override the `page_size` parameter?

**Comment by eviljeff** [comment]
> 
> 
> > After a brief look at this, it's not clear to me exactly what tests are needed here - testing a negative, that a parameter _isn't_ present is a challenge because there are multiple levels in the call stack before the underlying `callApi` that could add `page_size` to the function parameters.
> 
> I haven't looked into what you need to do, but we do have tests that verify what parameters are passed to APIs, which would fail if a new param was added that was not expected, so maybe our existing tests are good enough?

yeah, probably?

> You just want to make sure that for certain API calls we don't override the `page_size` parameter?

That was my thinking.  The request to do this came from a PR comment so don't know if @willdurand has more to add here.
