### ISSUE TITLE
Expand logic to generate and preload fonts subsets to other languages

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10495]
https://github.com/mozilla/addons-frontend/pull/10494 adds a minimal font subset to en-US that is preloaded. The logic behind it is described in detail in https://github.com/mozilla/addons-frontend/issues/10473#issuecomment-827479012

This issue is about expanding that logic to other key languages of the site. In some cases it might be worth it to make a single font subset for several languages, it should be possible by just following the naming conventions from #10494 (`-subset-locale1+locale2.var.woff2`)

We'll also need to figure out what to do for other languages, but it's likely they'll have to use the full font and no preload. We can use this issue to also optimize the full font a little bit and strip it of characters or features we know we don't need.

**Comment by diox** [comment]
Note: we are likely going to want to only care about the primary language subtag (the first group of letters before the hyphen, if any). That way we'll use the same font for all English locales (en-US, en-CA, en-GB...), another one for all Portuguese locales (pt-PT, pt-BR...) without having to specify all possible combinations.

**Comment by diox** [comment]
I had a [branch with that strategy](https://github.com/diox/addons-frontend/commit/320458af7865f66844545d842e3c61dadce9aea8) but I had to give up on it because browsers always downloads the best subsets that they need without taking preloading into account. So we would preload the subset for `de`, but it would also end up downloading the "best" subset, which is `en`. It would be worse with overlaps between locales, and for `fr` if a page included something that was in both `de` and `fr` subset but not `en`, it would preload `fr` but still download `de` and `en`... And so on.

Instead, we're going to go with a single subset for the "main" locales used on AMO, and preload that. That subset replaces the `en-US` one built for https://github.com/mozilla/addons-frontend/issues/10473 previously.

**Comment by diox** [comment]
QA:
- There should be a single preloaded font for all our pages. It should appear in the `<head>` of the HTML, and you should see it downloaded in devtools network panel (it should be around 32 KB, named `Inter-roman-subset-en_de_fr_ru_es_pt_pl_it.var.[something].woff2`). 
- In most pages in `en`, `de`, `fr`, `ru`, `es`, `pt`, `pl` & `it` languages (and their country-specific variants if any) no other font should be downloaded (*)
- Pages in other languages should typically download the preloaded font and the full font ~ 200 KB font

(*) The only exception is when there is content on the page that falls outside of these languages, or just fancy characters like emojis. For instance, at the time I'm writing this, the `en-GB` and `en-CA` homepage include an add-on that has a `default_locale` set to `hu`, and no translation in `en-GB` or `en-CA`, so we fall back to the Hungarian translation, which uses characters outside of the preloaded font, so you'll get 2 fonts downloaded just like described for pages in other languages.

**Comment by AlexandraMoga** [comment]
@diox I've verified this on -dev and these are my results:

- **Firefox** - new profile, no cache, default browser language set to en-US, loading pages with simple characters:
  - loading a simple extension page which includes only simple characters: https://addons-dev.allizom.org/en-US/firefox/addon/something-simple/; page loaded while being logged out => looking in DevTools Network panel, the `Inter-roman-subset-en_de_fr_ru_es_pt_pl_it.var.e1356516cc45b7a3d55ea6e94d67a272.woff2` is loaded _twice_
  - the file is loaded twice for other pages as well, i.e. homepage, `/en-US/firefox/extensions/`, `/en-US/firefox/themes/`, `/en-US/about` etc.
  - at a page reload, the font preload file is loaded only once (from cache)
  - I've verified with the other locales included in the preload file and the behavior is the same as with `en-US`.
- **Chrome** - new profile, no cache, default browser language set to en-US, loading pages with simple characters: 
  - loading the same simple extension page in `en-US` while being logged out => looking in DevTools Network panel, the `Inter-roman-subset-en_de_fr_ru_es_pt_pl_it.var.e1356516cc45b7a3d55ea6e94d67a272.woff2` is loaded _once_
  - the font preload is visible only once for other amo subpages too
  -  I've verified with the other locales included in the preload file and the behavior is the same as with `en-US`.
  
- **Firefox and Chrome** - loading pages in the locales included in the preload file, but the pages contain some special characters:
  - loading an extension that has some emoji in the summary https://addons-dev.allizom.org/de/firefox/addon/de-something-simple/ => both the `Inter-roman-subset-en_de_fr_ru_es_pt_pl_it.var.e1356516cc45b7a3d55ea6e94d67a272.woff2` (twice in firefox, as pointed above) and the 200 kB font files are loaded.

- **Firefox and Chrome** - loading pages in locales not included in the preload file:
  - for example, https://addons-dev.allizom.org/zh-CN/firefox/extensions/ => both the `Inter-roman-subset-en_de_fr_ru_es_pt_pl_it.var.e1356516cc45b7a3d55ea6e94d67a272.woff2` (twice in firefox, as pointed above) and the 200 kB font files are loaded
  - loading https://addons-dev.allizom.org/id/firefox/addon/something-simple/ => only the `Inter-roman-subset-en_de_fr_ru_es_pt_pl_it.var.e1356516cc45b7a3d55ea6e94d67a272.woff2` (twice in firefox, as pointed above) is loaded; I've noticed this for other locales, such as `nl`, `fi` and probably more. The 200 kB file normally loads only if the locale has some unique characters from what I've seen

**Comment by AlexandraMoga** [comment]
Also, I forgot to mention that the DevTools console shows the following warning:

```
The resource at “https://addons-amo-dev-cdn.allizom.org/static/Inter-roman-subset-en_de_fr_ru_es_pt_pl_it.var.e1356516cc45b7a3d55ea6e94d67a272.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly.
```
I'm not sure if this is important or not.

**Comment by diox** [comment]
@AlexandraMoga mmm, I'm not seeing the font being loaded twice, it's weird. Could you retest on a page that loaded twice, with devtools opened, and click the gear icon in network panel, select Save All As HAR, and share the resulting file ?

**Comment by AlexandraMoga** [comment]
@diox sorry for forgetting to mention my test env. I was testing on Win10 with Firefox 88 (release). I've also looked in 89.0b7 today and the issue is reproducing there as well. I can't reproduce in latest Nightly though.

**Comment by diox** [comment]
Same here yeah. I think this is not a huge deal and shouldn't block this going to production - if it's a real request and not an issue with devtools, it's wasteful, but still better than before, and should eventually be fixed.

**Comment by diox** [comment]
After more testing: it looks like a devtools network monitor bug to me. A weird one... If I load any site (http://example.com/ is enough) and _then_ I load the page I want to inspect, it will be shown correctly (and I don't get the font duplication)
