### ISSUE TITLE
Homepage shelves - at a screen resize letters overlap 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10509]
The layout won't look good when the title and see more links are a bit longer starting at ~ 850 px

I can reproduce this on AMO prod - with Recommended password managers at 728 px

On dev: 
![800px](https://user-images.githubusercontent.com/33448286/116518677-3bd33880-a8d9-11eb-98e2-156e2221e6c3.gif)

**Comment by willdurand** [comment]
I think this isn't a new issue, it was always like that and we don't have much options, besides truncating the text when it's too long. Ideally, titles and footer texts should be short. I'll let @bobsilverberg decide what to do, though.

**Comment by bobsilverberg** [comment]
It looks like @xlisachan opened https://github.com/mozilla/addons-frontend/issues/10373 which is about the same issue. She is working on possible fixes, but yes, this has been noted before, and was found to be very difficult to fix. Let's see what @xlisachan comes up with.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO -dev with FF90(Win10)

![looks good shelf](https://user-images.githubusercontent.com/33448286/127166936-a18c9432-b737-4c39-84ca-4a363e950728.gif)
