### ISSUE TITLE
Reduce number of weights included in our variable font

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10500]
Our variable font has 9 named axis declared for different weights: Thin, Extra Light, Light, Regular, Medium, Semi Bold, Bold, Extra Bold and Black. We don't need all that, so editing the variable font to strip those might be beneficial, it could lower the file size and improve performance.

This could have even more impact now that we're trying to preload a subset of the font (in https://github.com/mozilla/addons-frontend/issues/10495 we'll make several subsets for several languages)

**Comment by diox** [comment]
Not sure what we can do and how much impact it will have but it's worth investigating.

**Comment by diox** [comment]
Using https://github.com/source-foundry/Slice, dropping weights 100, 200, 700, 800, 900 (which are unused, if we look at our `mixins.scss`):
- subset went from 32K to 29K 
- full font went from 220K to 200K

So not that dramatic of an improvement, but still, I'll take what I can get. The full font will also be optimized in https://github.com/mozilla/addons-frontend/issues/10534 so the gains are likely going to be lower then.

**Comment by bobsilverberg** [comment]
I notice that the blog uses `font-weight: 700;` in `StaticAddonCard`. Does the blog use a different font file, and therefore is unaffected?

**Comment by willdurand** [comment]
> Does the blog use a different font file, and therefore is unaffected?

It does yes but that's a good call. I asked @diox on Matrix about which weights would be kept and didn't think about the `StaticAddonCard`. I'd say it's fine as long as we use the original `Inter` font file (which is what we do in addons-blog and we use the Inter font from a CDN for local dev in this project).

**Comment by ioanarusiczki** [comment]
@diox 
- Inter-roman subset package has 29.6 kB, the other package has 155kB
- the results from https://github.com/mozilla/addons-frontend/issues/10534#issuecomment-839805021 were verified with FF88 and Chrome.
