### ISSUE TITLE
Icon not aligned in autocomplete results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10505]
### Describe the problem and steps to reproduce it:

1. Go to https://addons.mozilla.org/en-US/firefox/
2. Search something in the search bar

### What happened?

![Screenshot 2021-04-28 at 14 55 16](https://user-images.githubusercontent.com/217628/116407307-ef80ed80-a831-11eb-82a2-78275348b5af.png)

### What did you expect to happen?

The icons should be aligned.

### Anything else we should know?

This is yet another regression, likely caused by the new font.

**Comment by ioanarusiczki** [comment]
@willdurand Looking on AMO dev I don't see this issue reproducible (maybe I could not reproduce it as easily here but I also see that it looks better or worse depending on the shape of the icon) 

Examples:

![first example](https://user-images.githubusercontent.com/33448286/117667108-3ca77c80-b1ad-11eb-8bf5-dd45de3306be.png)

![second example](https://user-images.githubusercontent.com/33448286/117667131-4335f400-b1ad-11eb-8337-9d757202136e.png)
