### ISSUE TITLE
Pass `experiment` and `variation` in download firefox URL

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10518]
This is a spin-off from https://github.com/mozilla/addons-frontend/issues/10476. In order to be able to query install data from telemetry, without the use of `utm_campaign`, we can instead use  `experiment` and `variation` in the URL to mozilla.org and they will be recorded in telemetry. For now they just appear in `main_summary`, but we've been told they can be added to `clients_daily` once we see that the data exists.

**Comment by bobsilverberg** [comment]
I think ideally we want something generic here, that will also work for future experiments, but the way the current experiment is coded makes that a bit difficult. Ideally we should pass both the `experimentId` as `experiment` and the `variant` as `variation`. These are provided via the `withExperiment` HOC, but the way the current experiment is coded, partially to deal with pieces wanting to be used by the blog, is to have the HOC at a higher level than the components that generate the URLs. This means that `withExperiment` isn't actually providing `experimentId` or `variant` to these components (specifically `GetFirefoxButton` and `GetFirefoxBanner`), which complicates things if we want to take a generic approach.

I think we can still have a shared function that adds `experiment` and `campaign` to the download URL, but from whence those values come might be handled in an odd way. For example, I think we're going to have to just hardcode the `experimentId` based on what we know it to be. This is not ideal in the long term, but I think for this particular patch, which is needed for next week's tag, we are going to have to do it this way. Just a heads up for whoever ends up reviewing this.

I will likely file a follow-up to come up with a more generic way of making this work for future experiments.

**Comment by willdurand** [comment]
I just tried on -dev with my windows machine. On the screenshot below, we can see that the installer contains the data we set on download links:

![Screenshot 2021-05-04 103359](https://user-images.githubusercontent.com/217628/116978633-453b1700-acc4-11eb-8aed-88394e7d8d6c.png)

At this point, it is up to Firefox to actually send the data with Telemetry but I dont see why this wouldn't work. Unfortunately, I found out that my pihole was dropping telemetry pings so my instance wont send the data.

**Comment by willdurand** [comment]
I did another test and I see the data in `about:telemetry`:

![Screenshot 2021-05-04 110629](https://user-images.githubusercontent.com/217628/116982213-cdbbb680-acc8-11eb-8a7f-a1dd6756ef50.png)

I let telemetry send data to our servers so we should have data in redash eventually..

**Comment by bobsilverberg** [comment]
Thanks for doing these checks @willdurand! It looks good. 😄

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this with Chrome - I see the experiment active on -dev and -stage:

- Current cta

1. "Download firefox" blue button query string parameters:
experiment: 20210404_download_cta_experiment
variation: current-cta
utm_campaign: non-fx-button
utm_content: header-download-button
utm_medium: referral
utm_source: addons.mozilla.org
utm_term: amo-fx-cta-current-cta

2. "Only with Firefox-Get Firefox Now"
experiment: 20210404_download_cta_experiment
variation: current-cta
utm_campaign: non-fx-button
utm_content: rta:d29ybGR3aWRlQHJhZGlv
utm_medium: referral
utm_source: addons.mozilla.org
utm_term: amo-fx-cta-621354-current-cta

- New cta
1. Click on the banner
experiment: 20210404_download_cta_experiment
variation: new-cta
utm_campaign: non-fx-button
utm_content: banner-download-button
utm_medium: referral
utm_source: addons.mozilla.org
utm_term: amo-fx-cta-new-cta

2. Click "X" on the banner - the event is registered by GA
`[GA: ON] sendEvent: {hitType: "event", eventCategory: "AMO Download Firefox Banner", eventAction: "download-firefox-banner-dismiss", eventLabel: undefined, eventValue: undefined}`

3. Click on the download firefox from the detail pages:
experiment: 20210404_download_cta_experiment
utm_campaign: non-fx-button
utm_content: rta:e2RiNGY2NTQ4LWRhMDQtNDNmYi1hMDNlLTI0OWJmNzBlZjVhMX0
utm_medium: referral
utm_source: addons.mozilla.org
utm_term: amo-fx-cta-502859-new-cta
variation: new-cta

Every time I land on mozilla.org page - I see a 200 and 301  GET request with these parameters mentioned above. 

![requests](https://user-images.githubusercontent.com/33448286/117137252-47ea4a80-ad5e-11eb-8525-94f386f07af3.png)
