### ISSUE TITLE
Langpicker looks more compact than before with the new font

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10524]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-dev.allizom.org/
2. Scroll down to see the footer and the langpicker

### What happened?

The langpicker (`select`) looks more "compact" than before. See how it is right now on -dev:

<img width="524" alt="Screen Shot 2021-05-03 at 09 39 55" src="https://user-images.githubusercontent.com/217628/116852309-603e5600-abf4-11eb-8ccd-ac331ae93955.png">

This is "before" we changed the font of this element (which is what we have on -prod):

<img width="526" alt="Screen Shot 2021-05-03 at 09 39 49" src="https://user-images.githubusercontent.com/217628/116852312-60d6ec80-abf4-11eb-965b-ac431b12a068.png">

### What did you expect to happen?

Even with the new `sans-serif` font, there shouldn't be any visual regression.

The `font-family` has been introduced in https://github.com/mozilla/addons-frontend/pull/10494

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO dev - FF88(Wi10) - looks good to me

![language picker](https://user-images.githubusercontent.com/33448286/117956050-86878400-b2cd-11eb-8c77-948a63f6ecc6.png)
