### ISSUE TITLE
Account dropdown does not stay open and cannot be used.

### ISSUE THREAD

**Issue by ArmEagle** [mozilla/addons-frontend#10520]
### Describe the problem and steps to reproduce it:

I just logged in to https://addons.mozilla.org/en-US/firefox/ for the first time in months.
The dropdown in the top right, to access "Account", "Tools" and "Logout" does not stay open when I try to move my mouse down to entries in the menu (unless I carefully move my mouse over the little 'chevron' at the top).

The similar dropdown at the "More..." element in the menu is positioned more snug against that element so the same issue doesn't occur there. But to be honest there the dropdown looks terrible positioned like that. It seems to me that the positioning there is a hack to workaround the problem.

And I'm sorry, but a little IMHO added; Who, in this day and age, makes a simple dropdown like this work with JavaScript and not with CSS?!

### What happened?

Dropdown closes before I can access elements in it.

### What did you expect to happen?

Dropdown works in a usable way.

### Anything else we should know?

I'm using Firefox 88.0 on Windows.

Both dropdowns open (combined screenshot). Addons hidden:
- NoScript (automatically disabled, because Addons is a privileged website).
- LastPass (pretty much useless, because Addons is a privileged website).
- uBlock Origin (disabled for this domain).
- GreaseMonkey (doesn't matter whether I disable it or not).
- Facebook Container
- HTTPS Everywhere
- 
![addons-mozilla-org-dropdown-issue](https://user-images.githubusercontent.com/606753/116785906-51449000-aa9c-11eb-8d9f-0ba049a2a502.png)

**Comment by willdurand** [comment]
> A quick (and somewhat dirty) solution is to reduce the size of this gap, as is the case with the "More..." menu. Perhaps we should implement that now, to make clicking on this menu less difficult, and think about addressing the design issue later.

+1

Also thank you for digging into a pure css alternative.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO dev - FF88(Win10) 

![fixed1](https://user-images.githubusercontent.com/33448286/117968207-cbfe7e00-b2da-11eb-9512-342ffe237994.gif)
