### ISSUE TITLE
Look into changing Codecov's threshold

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10535]
When Codecov tests run for addons-frontend, if there is any negative change in overall coverage that check fails. Because we do not have 100% code coverage, deleting a single line of code that had been covered by tests results in a reduction (albeit very small) of our total coverage, which then results in a check failure. We don't really care about this case.

We should look into configuring Codecov to do one of two things:
1. Increase the acceptable threshold of negative total coverage changes, so that this check won't fail in cases like this.
2. Disable the check for changes in total coverage. As long as the diff does not have a negative coverage change then the diff check should be all we need, and we needn't worry about the test for changes in total coverage at all.

@mozilla/addons-amo-engineering Do people have thoughts on which approach to take?

**Comment by willdurand** [comment]
> @mozilla/addons-amo-engineering Do people have thoughts on which approach to take?

Maybe start with (1) and if that is still annoying, we'll do (2)?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Is this a qa not needed?

**Comment by bobsilverberg** [comment]
> @bobsilverberg Is this a qa not needed?

Oops, sorry, yes, and I see Will added the label.
