### ISSUE TITLE
Optimize Inter full font

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10534]
Follow-up to a bunch of work on fonts (from https://github.com/mozilla/addons-frontend/issues/10040 to #10473, https://github.com/mozilla/addons-frontend/issues/10495 and others...) we should look at what glyphs we don't need from our font, `Inter`.

https://github.com/mozilla/addons-frontend/issues/10495 will make us use a subset in major locales, but the others still need to download the full 220 KB font right now. What we would do about that:
- Drop a bunch of glyphs from it to make it smaller. From a quick look at it I think we don't need:
    - Number — Latin : U+2160-2188
    - Number — Decimal Digit (only specific ones): U+24EA-2788
    - Number — Small: a bunch of them... (although we U+2080 in our subset right now, because it showed up in some content, so we may want to keep it)
    - Symbol: a bunch of them...
    - Symbol — Arrow: U+2191-27FA
    - Symbol — Geometry: U+25A0-25E6
    - Mark — Nonspacing Latin: U+363-1DE9
    - Uncategorised: U+E??? and U+47A-47F, U+2DFF
- Specify the full `unicode-range` it covers so that browsers don't download it if they don't need it (for Chinese or Japanese characters for instance, it's completely useless to download it only to realize it doesn't have them)

**Comment by ioanarusiczki** [comment]
@diox 
1. The font-size part will be checked during the weekly release testing - as far as I've checked I don't see anything unusual
2. I checked the .woff files with the hompeage on AMO stage and then with [language tools](https://addons.allizom.org/hu/firefox/language-tools/):
- for the main locales, Japanese, Chinese, AMO homepage (which is not containing emojis or other more unusual chars) there's one download, the 29K file. Language tools requires the 29K and 151K file too. 
- Czech and other languages will require both files: 29K and 151K for the homepage and language tools pages.
