### ISSUE TITLE
URLs served by addons-server without a trailing slash cause a redirect loop locally

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10545]
On local environments, URLs served by addons-server, that are not supposed to have a trailing slash, like many in devhub, don't work any more: the user is stuck in a redirect loop.

For example, when you submit an add-on
- You make a request to http://olympia.test/en-US/developers/addon/submit/agreement
- addons-frontend intercepts that request, serves a redirect to http://olympia.test/en-US/developers/addon/submit/agreement/
- addons-server sees that request, serves a redirect to the correct URL, http://olympia.test/en-US/developers/addon/submit/agreement/
- and so on...

This is used to work. The logic for local envs in nginx is to [try addons-frontend first, and then fall back to addons-server if addons-frontend serves a 404](https://github.com/mozilla/addons-nginx/blob/4112aa36c693f3f72d07ac14c6a63819e31e559b/addons.conf#L93-L97). This allows us/contributors to introduce URLs in addons-server locally without having to change nginx configuration. The breakage was probably caused by https://github.com/mozilla/addons-frontend/issues/10308 or something around that issue.

**Comment by eviljeff** [comment]
this might (or might not) be fixed by dropping the special handling for `clientAppRoutes` (see discussion/links in #10363)

**Comment by willdurand** [comment]
> this might (or might not) be fixed by dropping the special handling for `clientAppRoutes` (see discussion/links in #10363)

That looks more like a problem with the trailing slash middleware, which can be configured here: https://github.com/mozilla/addons-frontend/blob/fb4bfbae5a8491ecf4ed02857628618718959325/config/default.js#L365-L378

#10363 fixed a bug or two, which likely revealed a misconfiguration of the trailing slash middleware.

**Comment by AlexandraMoga** [comment]
Is this a 'qa:not needed' since only local dev is affected?
