### ISSUE TITLE
Delete unused icons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10557]
While working on #10536, I removed some icons that weren't used anymore. I think the `Icon` component has some icons that we are not using and we could delete the files as well as remove some of the CSS. If we don't need those icons, there is no need to keep them around, we can re-add them later.

While working on this issue, we should look at the other components to see if they embed files that aren't useful (we usually have an `img/` folder for images in the component's folder).

**Comment by ioanarusiczki** [comment]
@willdurand I've checked the frontend for regressions and I did not find anything unusual except https://github.com/mozilla/addons-frontend/issues/10588 which is caused by another issue.

Verified on AMO dev - FF88(Win10).
