### ISSUE TITLE
Fix callout icon alignment when message splits into multiple lines

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10585]
This is a followup for https://github.com/mozilla/addons-frontend/issues/10571 

When the text from the cta message splits into multiple lines the icon doesn't look good:

![now on stage2](https://user-images.githubusercontent.com/33448286/117941086-9b105000-b2be-11eb-894e-b25206c35933.png)

On AMO prod right now:

![on prod](https://user-images.githubusercontent.com/33448286/117941159-aebbb680-b2be-11eb-8539-330e6ce92eed.png)

**Comment by willdurand** [comment]
> When the text from the cta message splits into multiple lines the icon doesn't look good:

To me, the version on -dev/-stage looks a lot better than -prod.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, maybe the icon a bit closer to the first line and it would be alright.

**Comment by bobsilverberg** [comment]
@ioanarusiczki Here is what it currently looks like on prod, which seems fine to me:

![Screen Shot 2021-07-05 at 1 16 48 PM](https://user-images.githubusercontent.com/142755/124503331-57543700-dd93-11eb-8e7b-52caa3ab540a.png)

If you feel that it still needs to change, can you be explicit about what changes you think are required?

**Comment by willdurand** [comment]
@ioanarusiczki can we close this issue? I think we're good with the current UX.

**Comment by willdurand** [comment]
I am going to close this issue now. Please re-open it if you'd like to get it fixed.
