### ISSUE TITLE
Bump down notice icon a bit

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10580]
The icon in the Notice component is still slightly higher than the text:

![image](https://user-images.githubusercontent.com/31961530/117945099-a727fc00-b316-11eb-94bc-f73e9c6de0a2.png)

Let's move it down a bit.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good to me on AMO dev - FF88(Win10). 

![lgtm](https://user-images.githubusercontent.com/33448286/118265237-851ead00-b4c1-11eb-9a15-e2a4e52a42fc.png)
