### ISSUE TITLE
Add font-display: swap on the full font

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10583]
When we added Inter, we decided that the flash of content caused by `font-display: swap` was too annoying and we removed that declaration. Now that we have a subset that is good for most of our content (https://github.com/mozilla/addons-frontend/pull/10494, https://github.com/mozilla/addons-frontend/issues/10495), we should consider adding `font-display: swap` back, but only on the "full" font. 

The full font is only used as a last resort, when characters on the page are not present in the subset but are in the full. So for most pages, that should be pretty limited: maybe a couple characters here and there, or maybe a full paragraph of user text in the middle of the page, but rarely a lot of content, and rarely in the initial viewport. 

This would improve the LCP on pages that need the full font for some of their content: https://github.com/mozilla/addons-frontend/issues/10444, https://github.com/mozilla/addons-frontend/issues/10445, https://github.com/mozilla/addons-frontend/issues/10446

**Comment by ioanarusiczki** [comment]
@diox

> Display a fallback font while the full font is being downloaded, for text not covered by out subset font but covered in the full font

I can't tell if this proves it, but navigating on language-tools page (after I'm deleting browser's data) text is not displayed straight away, and I see a loading "state" for a very short while:

![fallback text](https://user-images.githubusercontent.com/33448286/118660989-90b0f300-b7a3-11eb-8c7f-d7626f5949b6.gif)

I've also did a check on the results from last week - .woff files are loading as[ expected](https://github.com/mozilla/addons-frontend/issues/10534#issuecomment-839805021). 

If there's anything else I could be looking for please let me know.
