### ISSUE TITLE
Notice icon has a different positioning on AMO dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10588]
AMO Dev: 

![this is now](https://user-images.githubusercontent.com/33448286/118273653-e13afe80-b4cc-11eb-9cb4-a1e136710812.png)

This is in production:

![production](https://user-images.githubusercontent.com/33448286/118274061-5ad2ec80-b4cd-11eb-9b27-5f1ce3d95eea.png)

**Comment by championshuttler** [comment]
Regression from #10581

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Verified on AMO stage - FF88(Win10). 

![verified on AMO stage](https://user-images.githubusercontent.com/33448286/118794692-81649f00-b8a2-11eb-8849-c465c7995538.png)
