### ISSUE TITLE
Icon-user could use a better alignment or size

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10589]
I think that after the increase of font - the user icon next to the number of users looks a bit too small and it's not aligned 

Homepage shelves:

![homepage shelves](https://user-images.githubusercontent.com/33448286/118275116-ad60d880-b4ce-11eb-998c-c3104b4d1170.png)

View my profile:

![view my profile page](https://user-images.githubusercontent.com/33448286/118275286-eac56600-b4ce-11eb-8568-aa963041536b.png)

Other popular extensions: 

![other popular extensions](https://user-images.githubusercontent.com/33448286/118275445-17797d80-b4cf-11eb-9037-8d6dfbb74ac1.png)

**Comment by championshuttler** [comment]
Doing this helped in making it better, WDYT @bobsilverberg :

```diff
diff --git a/src/amo/components/SearchResult/styles.scss b/src/amo/components/SearchResult/styles.scss
index 6985ea3..0a4f6d6 100644
--- a/src/amo/components/SearchResult/styles.scss
+++ b/src/amo/components/SearchResult/styles.scss
@@ -195,7 +195,7 @@ $icon-default-size: 32px;
 }

 .SearchResult-users-icon {
-  height: 10px;
+  height: 12px;
   margin-bottom: -1px;
 }
```

After:

![image](https://user-images.githubusercontent.com/22130317/118277812-d0978200-b4e6-11eb-81e4-cae86958f6b5.png)

**Comment by bobsilverberg** [comment]
> Doing this helped in making it better, WDYT @bobsilverberg :
> 
> ```diff
> diff --git a/src/amo/components/SearchResult/styles.scss b/src/amo/components/SearchResult/styles.scss
> index 6985ea3..0a4f6d6 100644
> --- a/src/amo/components/SearchResult/styles.scss
> +++ b/src/amo/components/SearchResult/styles.scss
> @@ -195,7 +195,7 @@ $icon-default-size: 32px;
>  }
> 
>  .SearchResult-users-icon {
> -  height: 10px;
> +  height: 12px;
>    margin-bottom: -1px;
>  }
> ```
> 
> After:
> 
> ![image](https://user-images.githubusercontent.com/22130317/118277812-d0978200-b4e6-11eb-81e4-cae86958f6b5.png)

I agree, that looks good, thanks @championshuttler. I will assign the issue to you if you can create a PR.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good at 12px

Verified on AMO stage - FF88(win10)

![12px](https://user-images.githubusercontent.com/33448286/119667642-566ed380-bdeb-11eb-84b8-29038e3c5a9a.png)
![12px again again](https://user-images.githubusercontent.com/33448286/119667663-5a025a80-bdeb-11eb-9e2b-66331b211867.png)
![12px again](https://user-images.githubusercontent.com/33448286/119667666-5a025a80-bdeb-11eb-9968-c20915418387.png)
