### ISSUE TITLE
Make changes from the CTA experiment permanent

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10599]
Pending final analysis, and if a decision is made to make the CTA changes permanent, update our code so that the Download Firefox CTAs are no longer controlled by an experiment and instead use the new version of the CTAs for all users.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev:
- the new cta is present and permanent on non-FF browsers on Win10 and Android 
- utm_term: amo-fx-cta-616930 (as an example, it is fx-cta without current or new). No cookie set either.
- Rtamo is working on AMO dev with FF Nightly (I tested with a verified add-on)

UX:

I think that while the experiment was going on with current and new cta, the layout for rtamo addons was a bit different - the length of the yellow banner was equal with the download button.  

Right now it is shorter:

![yellow banner lenght](https://user-images.githubusercontent.com/33448286/120466664-2b890000-c354-11eb-91be-b1ff8c2773ba.png)

I think it looks good this way too, but if that's unexpected please let me know.

**Comment by bobsilverberg** [comment]
@ioanarusiczki I ended up having to make a couple of changes to the styles and I guess this occurred. We should fix it. Can you please open an issue for it?

**Comment by bobsilverberg** [comment]
Nevermind, I opened https://github.com/mozilla/addons-frontend/issues/10642
