### ISSUE TITLE
User is not redirected back to AMO after clicking the back button on the Sign in page

### ISSUE THREAD

**Issue by acornestean** [mozilla/addons-frontend#10602]
**Build:**
Production (1.205.0)
Stage (1.206.0)
Dev

**Affected versions:**
Nightly (90.0a1/20210519083222)
Beta (89.0b14/20210518190425)
Release (88.0.1/20210504152106)

**Affected platforms:**
Windows 10 64-bit

**Steps to reproduce:**
1. Launch Firefox with a new/fresh profile
2. Navigate to AMO (https://addons.mozilla.org/en-US/firefox/)
3. Click on the “Register or login” button in the top right corner
4. Notice that the user is redirected to the Sign in page
5. Click on the browser’s Back button
6. Observe that the user is not redirected back to the AMO page

**Actual result:**
The user is not redirected back to the previous page (AMO), even though the Back button is active/not grayed out.

**Expected result:**
The user is redirected to the previous page (AMO) after clicking the Back button while on the Sign in page.

**Notes:**
1. The same behavior is observed when accessing the Sign in page from AMO stage (https://addons.allizom.org/en-US/firefox/) and AMO dev (https://addons-dev.allizom.org/en-US/firefox/)
2. Initially filed the issue against FxA, but got redirected here. For further details, see: https://jira.mozilla.com/browse/FXA-3558

https://user-images.githubusercontent.com/50236075/118981099-a92b3400-b982-11eb-82dd-fe4573362092.mp4

**Comment by AlexandraMoga** [comment]
Just wanted to point out that this issue also reproduces when the login is initiated from Developer Hub, so it is not restricted to the frontend.

**Comment by willdurand** [comment]
This is the expected flow apparently. There is nothing we (AMO) can do.
