### ISSUE TITLE
Content "jumps" on add-ons versions pages using a Notice after loading

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10605]
STR:
- Load https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/
- Observe the size of the yellow notice "Be careful with old versions"

Expected results:
- It shouldn't change

Actual results:
- It changes when JavaScript is executed (you can load the page with and without JavaScript enabled to see the difference more clearly)

This seems to be caused by the fact that we put paragraphs inside paragraphs. In the original HTML, before JavaScript is executed, we see:
```html
<div class="Notice-content"><p class="Notice-text"><p class="AddonVersions-warning-text">Be careful with old versions! ...
```
In the generated DOM, elements are shuffled around to fix this, ending up with:
```
- <div class="Notice-content">
  - <p class="Notice-text"></p>
  - <p class="AddonVersions-warning-text">Be careful with old versions! ... </p>
  </div>
```

But React doesn't behave the same way, and happily lets us put a `<p>` inside a `<p>`, so after it's done rendering it transforms the DOM back to something closer to our original intent:
```
- <div class="Notice-content">
  - <p class="Notice-text">
    - <p class="AddonVersions-warning-text">Be careful with old versions! ... </p>
    </p>
  </div>
```

This is bad because it causes a subtle layout change, which forces the LCP to be computed again (making our score worse than it should be for this page). This likely is the cause behind https://github.com/mozilla/addons-frontend/issues/10446 (and I suspect other pages have similar, less visible issues)

**Comment by ioanarusiczki** [comment]
@diox I tested it on AMO Dev 

- enabling/disabling javascript or at page refresh the notice seemed to "jump" 

Before: 

![enabling disabling java script](https://user-images.githubusercontent.com/33448286/119482462-bfc9e600-bd08-11eb-9da2-e7337d05b12a.gif)

Now on dev:

![on dev looks good](https://user-images.githubusercontent.com/33448286/119482500-c8bab780-bd08-11eb-9a22-d2e9f45967f7.gif)
