### ISSUE TITLE
Add tests validating HTML of full pages

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10608]
https://github.com/mozilla/addons-frontend/issues/10605 could have been detected by a test validating the HTML of the corresponding pages. It might not be something that would cover all scenarios (it can depend on content) but it would be a nice start to ensure this doesn't happen again.

**Comment by prsmahajan** [comment]
Hi,  I would like to work on this issue, Can anyone suggest me to get started?

**Comment by caitmuenster** [comment]
Hi @prsmahajan, thanks for your interest! This issue isn't a good one for contributors. :) However, we'd love it if you wanted to work on an issue labeled 'contrib: good first bug' on one of our repositories! Here's a list of [current issues](https://addons-pm.herokuapp.com/contrib/good-first-bugs/?dir=desc&sort=updatedAt) with that tag. We try to update it every two weeks or so. Feel free to work on any issue that someone else hasn't been working on for at least two weeks.
