### ISSUE TITLE
Replace default add-on icon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10616]
The default icon for add-ons was replaced in addons-server in https://github.com/mozilla/addons-server/pull/17200. We should replace the one we use in addons-frontend as well.

The icon we currently use can be found at https://github.com/mozilla/addons-frontend/blob/master/src/amo/img/icons/default-64.png. 

We would need to replace this icon and update any code in addons-frontend to point to the new filename.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified on AMO stage - FF88, Chrome (Win10) and Fenix for Android. I think I checked all pages where the presence of this icon is possible, including collections and user profile page.

Examples:
![autocomplete](https://user-images.githubusercontent.com/33448286/120492981-68162500-c36f-11eb-837f-5ab1b12a29f4.png)
![detail page](https://user-images.githubusercontent.com/33448286/120493045-75cbaa80-c36f-11eb-98b7-7231f5db8f6b.png)
![detail page2](https://user-images.githubusercontent.com/33448286/120493049-76644100-c36f-11eb-9a02-34ec55d493fd.png)
![search result](https://user-images.githubusercontent.com/33448286/120493129-8aa83e00-c36f-11eb-98d5-8031516100e5.png)
![shelves](https://user-images.githubusercontent.com/33448286/120493130-8b40d480-c36f-11eb-8ed2-9c7f1c5ca82f.png)
