### ISSUE TITLE
Disable the current experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10613]
We want to disable the current experiment for now, and then we'll evaluate what the next steps should be.

**Comment by ioanarusiczki** [comment]
@bobsilverberg On AMO dev or AMO stage - the experiment is no longer active. 

- the parameter: utm_term: amo-fx-cta-620564-current-cta (as an example that it's always `current-cta`)
- the current layout is always displayed
- Rtamo is working on AMO dev with FF Nightly (I tested with a recommended addon)
