### ISSUE TITLE
Allow for excluding experiment users based on user agent

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10618]
This is a spin-off from https://github.com/mozilla/addons-frontend/issues/10598. For the upcoming download funnel experiment, we need to be able to exclude users from the experiment with IE 9 and lower. It is possible that for future experiments we may want to do something similar. One could imagine, for example, an experiment that only targets users on non-Firefox browsers.

To this end, we should consider adding the ability to exclude and/or segment users in an experiment based on data from their user agent. 

In the exclude use case, a user would either be included in or excluded from an experiment based on their user agent. In the segment use case, we would be able to place users into specific cohorts based on their user agent. 

The download funnel experiment does not require the segment use case, but, because of the existence of the special `NOT_IN_EXPERIMENT` variant, we could use the segment use case to satisfy the exclude use case, if we feel we need both.

In either case, the high-level idea for this would be to make sure that the experiment infrastructure has access to `userAgentInfo`. An individual experiment's config could include a function which can either be used to exclude users based on user agent (returning a boolean) or could include a function which is its own version of the `getVariant` function which would return a variant based on logic defined for the specific experiment, using user agent data.

Both of these are technically feasible, but will require a not insignificant amount of effort.

For the download funnel experiment, we can satisfy the requirement by simply forcing any user with IE9 or less into the special `NOT_IN_EXPERIMENT` variant, and not implement this feature, although we would still need to provide access to the `userAgentInfo` object, so at least some changes would be required.

We need to decide:
1. Whether to update our experiment infrastructure to allow for users to be excluded and/or segmented  based on user agent, and use that new feature for the download funnel experiment, or postpone implementing this feature (as we don't necessarily need it right now) and simply force IE <=9 users into the `NOT_IN_EXPERIMENT` variant?
2. If we do want to implement the feature, do we think there will be a need to segment users based on user agent, or do we think that simply being able to exclude users based on user agent will suffice?

@jvillalobos @mozilla/addons-amo-engineering What do you think?

**Comment by jvillalobos** [comment]
I would expect the IE9 situation to be fairly exceptional and not something we'll normally need. Thinking about what we do on AMO, I think normally we would have experiments in these buckets:
* Firefox users only
* Non-Firefox users only
* Mobile users only
* Desktop users only

Or an intersection of the above. I don't know if this warrants creating the infrastructure for UA identification or not.

**Comment by bobsilverberg** [comment]
> I would expect the IE9 situation to be fairly exceptional and not something we'll normally need. Thinking about what we do on AMO, I think normally we would have experiments in these buckets:
> 
> * Firefox users only
> 
> * Non-Firefox users only
> 
> * Mobile users only
> 
> * Desktop users only
> 
> Or an intersection of the above. I don't know if this warrants creating the infrastructure for UA identification or not.

Thanks @jvillalobos. We could consider making those available options, as opposed to making it entirely flexible, although we are already faced with an edge case (the IE9 thing). To support those we'd need to make the experiment infrastructure able to interpret user agent data, so I'm not sure how much more work it would be to add the level of flexibility discussed here.

Also note that while it's not specifically covered by this issue, we did talk about the need to exclude users based on language as well, which is another argument for adding a feature that allows us to exclude users conditionally.

I'm interested to hear what the rest of the team thinks.

**Comment by willdurand** [comment]
> This is a spin-off from #10598. For the upcoming download funnel experiment, we need to be able to exclude users from the experiment with IE 9 and lower.

Did we try to browse AMO on IE 9? We dropped support for IE 11 a while ago and it was already _not great_ so I don't really know what to expect of IE 9. If AMO isn't functional in IE (all versions), that's one less problem to solve because it would become a non-issue.

Also, what's the percentage of users in GA with "IE 9"?

As for the rest, I kinda agree with the overall idea of having more than two buckets for an experiment as well as assigning users to buckets with something else than `Math.random()` but I am a bit lost: is this **required** for the download funnel experiment? (I don't see anything about that in the spec for this experiment).

**Comment by bobsilverberg** [comment]
> > This is a spin-off from #10598. For the upcoming download funnel experiment, we need to be able to exclude users from the experiment with IE 9 and lower.
> 
> Did we try to browse AMO on IE 9? We dropped support for IE 11 a while ago and it was already _not great_ so I don't really know what to expect of IE 9. If AMO isn't functional in IE (all versions), that's one less problem to solve because it would become a non-issue.
> 

I haven't tried, but the problem is, if we send a user on IE<=9 to the new URL (a version of /thanks), as opposed to the current URL (which is /new), then it is impossible for them to download Firefox. So even if AMO is mostly unusable for someone on IE<=9, if the link to download Firefox is still visible and clickable (which seems reasonable to expect), we should make sure it actually works.

> Also, what's the percentage of users in GA with "IE 9"?

It's minuscule. As I mentioned in a [comment on a related issue](https://github.com/mozilla/addons-frontend/issues/10600), we had 40 users on IE<=9 over a 2 week period. Maybe we can say we don't care about such a small number of users, but we do run the risk of making it impossible for them to download Firefox from our site, so we need to consider that.

> 
> As for the rest, I kinda agree with the overall idea of having more than two buckets for an experiment as well as assigning users to buckets with something else than `Math.random()` but I am a bit lost: is this **required** for the download funnel experiment? (I don't see anything about that in the spec for this experiment).

No, there are no special segmenting requirements for the download funnel experiment. Also, just FYI, we can currently have more than two buckets, if we want to test more than 2 variations. We have the ability to specify any number of buckets along with the percentage of users who should be allocated to each bucket.

The reason I am bringing this up is because this requirement has brought to light some limitations in our current experiment infrastructure, and this is an opportunity to enhance it. We do not absolutely need to do it now, which is why I raised the topic for conversation.

**Comment by bobsilverberg** [comment]
> > but we do run the risk of making it impossible for them to download Firefox from our site, so we need to consider that
> 
> Is it impossible? I think they're sent to the /thanks page and the download isn't started. Presumably they can click on a link on the page and start it themselves?

Perhaps. We discussed this in the standup today and the suggestion is, based in the fact that we don't actually support IE at all on AMO, and the site doesn't render properly, we can just ignore this very small number of users and not complicate the experiment by trying to exclude them.

Do you agree @jvillalobos?

**Comment by jvillalobos** [comment]
Yes, I think it should be fine to ignore those users. It would be good to know what they'll experience, though. Hopefully it's not such a terribly broken experience.

**Comment by willdurand** [comment]
> Hopefully it's not such a terribly broken experience.

Browsing websites with IE9 in 2021? 😹

**Comment by bobsilverberg** [comment]
Based on the discussion at https://github.com/mozilla/addons-frontend/issues/10403, I think we're going to want to at least be able to run an experiment that only targets non-Firefox users, so I am going to pick this up again.

**Comment by bobsilverberg** [comment]
experiment

> I would expect the IE9 situation to be fairly exceptional and not something we'll normally need. Thinking about what we do on AMO, I think normally we would have experiments in these buckets:
> 
> * Firefox users only
> 
> * Non-Firefox users only
> 
> * Mobile users only
> 
> * Desktop users only
> 
> 
> Or an intersection of the above. I don't know if this warrants creating the infrastructure for UA identification or not.

@jvillalobos How do you define "Mobile" and "Desktop" users? Is it based on the `clientApp`, i.e., whether they are currently browsing the `/android/` or `/firefox/` site, or is it based on something else? What sorts of use cases exist for those?

**Comment by jvillalobos** [comment]
I would define them by their user agent and not the site they're using. So, anyone on a phone on tablet would be a mobile user, regardless of the site being visited.

I think having that distinction would remove the noise if we're making certain layout changes that only impact larger screens or smaller screens, or we're testing something that only matters to mobile users, like messaging on mobile add-on pages. Unfortunately we get desktop traffic on `/android/` and mobile traffic on `/firefox/`, and that could give us the wrong idea when we experiment with certain features. We can sort them out after the fact on GA, but ideally we should be able to do it up front.

**Comment by bobsilverberg** [comment]
> I would define them by their user agent and not the site they're using. So, anyone on a phone on tablet would be a mobile user, regardless of the site being visited.
> 
> I think having that distinction would remove the noise if we're making certain layout changes that only impact larger screens or smaller screens, or we're testing something that only matters to mobile users, like messaging on mobile add-on pages. Unfortunately we get desktop traffic on `/android/` and mobile traffic on `/firefox/`, and that could give us the wrong idea when we experiment with certain features. We can sort them out after the fact on GA, but ideally we should be able to do it up front.

Ok, thanks for clarifying. Currently, the [logic we use](https://github.com/mozilla/addons-frontend/blob/master/src/amo/utils/index.js#L168-L184) to decide whether to direct a user to either `firefox` or `android` is based entirely on whether the `userAgentString` contains the string `android` or not, which is very simplistic. I am guessing we want something more complex than this when we decide to implement this feature.

My plan is to start by implementing the "Firefox users only" and "Non-Firefox users only" options first, so we can defer figuring this out to a separate issue, which I will file.
