### ISSUE TITLE
Button layout in the abuse report form is broken for some locales in mobile view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10624]
### Describe the problem and steps to reproduce it:

1. Open an add-on detail page
2. Change the site language to `/de/`
3. Click on the Report add-on for abuse button
4. Notice the Confirmation and Cancellation buttons

### What happened?
There is  no space between the two buttons and the text doesn't fit in properly

### What did you expect to happen?
No layout issues

[de]
![image](https://user-images.githubusercontent.com/31961530/119835335-6d0b4c80-bf09-11eb-87c0-39e6e6cdb79a.png)

[ru]
![image](https://user-images.githubusercontent.com/31961530/119835358-71376a00-bf09-11eb-9f0e-d1cd2fa4a985.png)

**Comment by championshuttler** [comment]
Dont know much Deutsch but what about changing text to `Missbrauchsbericht senden` in German l10n :P jk

**Comment by AlexandraMoga** [comment]
The button layout is looking better now:

[mobile]
![image](https://user-images.githubusercontent.com/31961530/122547412-bf3b1b80-d038-11eb-92d3-6837d59a88b7.png)

[medium] - word splitting is still not ideal for this screen size
![image](https://user-images.githubusercontent.com/31961530/122547425-c4986600-d038-11eb-86fa-020a820d5c2c.png)

[desktop]
![image](https://user-images.githubusercontent.com/31961530/122547446-ca8e4700-d038-11eb-923c-624bfb3d747a.png)

This issue is verified fixed on -dev with Win10 and Android.

**Comment by championshuttler** [comment]
> [medium] - word splitting is still not ideal for this screen size
> ![image](https://user-images.githubusercontent.com/31961530/122547425-c4986600-d038-11eb-86fa-020a820d5c2c.png)

I dont think we could do much about it wdyt @bobsilverberg ?
