### ISSUE TITLE
Investigate rendering experiments on the server and serving from cache

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10634]
This is a spin off from https://github.com/mozilla/addons-frontend/issues/10601#issuecomment-851637114.

Investigate updating our experiment infrastructure to render the final experiment content on the server, which is the opposite of what we are doing currently. We would still need a cookie on the client to make a user's cohort consistent for the length of the experiment, and we'd need to make sure that the cookie was written on the client and not the server, as the latter breaks caching.

We also need to continue to deal with making sure that GA events do not get sent on the server, so we would need to emit an enrollment event on the client if a user was enrolled into a cohort on the server.

**Comment by bobsilverberg** [comment]
Note that I reopened https://bugzilla.mozilla.org/show_bug.cgi?id=1702993 to address adding the cookie contents to the cache key.

**Comment by ioanarusiczki** [comment]
@bobsilverberg On AMO dev with Chrome:
- when I am on a page or navigate to other AMO pages with a funnel-cookie set, I don't see experiment events sent in the Console.  (this does not include clicking the download buttons)
- when I do not have a cookie (I cleared all from the browser's settings) and I refresh the page or navigate to another AMO page, there's an enrollment experiment registered by the Console: 
![a onetime event](https://user-images.githubusercontent.com/33448286/123098761-53fd9a80-d3e6-11eb-8c0e-256e8480c7fe.png)
