### ISSUE TITLE
When text is unavailable, install buttons are displayed on the left on the detail pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10648]
I deleted summary/description for themes/addons using the admin (because I've noticed the button on the left for a [Metallica](https://addons-dev.allizom.org/en-US/firefox/addon/metallica-live-shit/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search) theme which had no summary added, this case is not quite realistic since at submission the summary is mandatory) ->

AMO dev - will keep displaying install button on the right 
AMO stage - install button appears on the left

Examples on AMO Dev:

https://addons-dev.allizom.org/en-US/firefox/addon/testing-again-a-themes/
https://addons-dev.allizom.org/en-US/firefox/addon/buzzsumo3/
https://addons-dev.allizom.org/en-US/firefox/addon/koutter2359/

Examples on AMO stage: 
https://addons.allizom.org/en-US/firefox/addon/mountain-lake/
https://addons.allizom.org/en-US/firefox/addon/listed-vers/
https://addons.allizom.org/en-US/firefox/addon/peachy/

AMO dev:
![AMO dev](https://user-images.githubusercontent.com/33448286/120632370-8ebc8480-c471-11eb-97f3-f24bc9ce5688.png)

AMO stage:
![AMO stage](https://user-images.githubusercontent.com/33448286/120632307-7ba9b480-c471-11eb-8407-1013c3629a4e.png)

**Comment by ioanarusiczki** [comment]
AMO dev has not been updated, so this could be a regression caused by https://github.com/mozilla/addons-frontend/issues/10648

**Comment by bobsilverberg** [comment]
I am not seeing this reproduce anymore. Can you please check again @ioanarusiczki?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, right now it's about this being a regression on both testing servers, probably caused by https://github.com/mozilla/addons-frontend/issues/10642 

Initially because the deployment was not completed on -dev, this was only visible on -stage. Right now, on both servers the button is on the left side when text is unavailable. The button should be on the right side. 

I'm going to change the title.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This issue is not reproducible on AMO dev - FF89(Win10). 

![on AMO dev](https://user-images.githubusercontent.com/33448286/121162409-c1b0a080-c802-11eb-9b97-e65453af1c98.png)
