### ISSUE TITLE
Callout should be same width as download Firefox button

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10642]
This is a follow-up from https://github.com/mozilla/addons-frontend/issues/10599. The callout should be the same width as the download button, not narrower as it is currently:

![yellow banner lenght](https://user-images.githubusercontent.com/33448286/120466664-2b890000-c354-11eb-91be-b1ff8c2773ba.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I see this fixed on AMO stage - Chrome/Edge

![fixed on stage](https://user-images.githubusercontent.com/33448286/120621283-9ac52980-c412-11eb-9044-0c3f8aca4cd4.png)

Looking on AMO dev - I can still see the old layout present - even if I deleted cache, it won't refresh the content. 

I don't know if it's related to https://github.com/mozilla/addons-server/issues/17262, but using Windows Sandbox I have the same result, the old layout on AMO dev:

![windows sandbox](https://user-images.githubusercontent.com/33448286/120624264-5edf9380-c415-11eb-9e9e-9cd00b3737a7.png)

**Comment by ioanarusiczki** [comment]
Reason: AMO dev's deployment did not finish.
