### ISSUE TITLE
Remove special casing for Download Firefox link for Facebook Container

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10650]
Back in [2018](https://github.com/mozilla/addons-frontend/commit/185a48e96a1ab707e6424ef7d4e83466202a04a9), we added some special casing which uses a different download URL for the `AddonCompatibilityError` when it is displayed on the detail page for the Facebook Container add-on. It looks like this was done to address https://github.com/mozilla/addons-frontend/issues/4737.

We're removing the download link entirely from the `AddonCompatibilityError`, and instead will use the `GetFirefoxButton` in these cases, and during the conversations around that it was decided that we don't really need this special casing anymore and that all Download Firefox links should point to the same place.

ccing @jvillalobos for confirmation on this.

**Comment by willdurand** [comment]
It would be nice to hear from the "Facebook Container team" since they asked for this change in the first place: https://bugzilla.mozilla.org/show_bug.cgi?id=1451542

**Comment by bobsilverberg** [comment]
> It would be nice to hear from the "Facebook Container team" since they asked for this change in the first place: [bugzilla.mozilla.org/show_bug.cgi?id=1451542](https://bugzilla.mozilla.org/show_bug.cgi?id=1451542)

Fair enough. One thing to keep in mind, and maybe it was an oversight back in 2018 when this was implemented, is that we only use the special Facebook Container URL in the `AddonCompatibilityError`, and we do not use it on the add-on detail page for Facebook Container. I'll ping them on Slack to see what they think.

**Comment by jvillalobos** [comment]
Per Slack conversations, this is something that was set up a while ago and kinda forgot it was there, so we can get rid of it safely.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

This is on AMO dev https://addons-dev.allizom.org/en-US/firefox/addon/facebook-container/ :

![on dev](https://user-images.githubusercontent.com/33448286/121139617-cc146f80-c7ed-11eb-972c-b72242d11ad2.png)

This one's on production https://addons.mozilla.org/en-US/firefox/addon/facebook-container/ :

![on prod](https://user-images.githubusercontent.com/33448286/121139637-d33b7d80-c7ed-11eb-86f6-73d6abcd088f.png)

In both cases the download buttons redirect to https://www.mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=rta:QGNvbnRhaW4tZmFjZWJvb2s&utm_medium=referral&utm_source=addons.mozilla.org&utm_term=amo-fx-cta-495646 

What's been verified in 2018 https://github.com/mozilla/addons-frontend/issues/4737 is not applicable anymore. 

If there's something I did not understand, please let me know. 

I verified this on AMO dev with Chrome.

**Comment by bobsilverberg** [comment]
> 
> In both cases the download buttons redirect to [mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=rta:QGNvbnRhaW4tZmFjZWJvb2s&utm_medium=referral&utm_source=addons.mozilla.org&utm_term=amo-fx-cta-495646](https://www.mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=rta:QGNvbnRhaW4tZmFjZWJvb2s&utm_medium=referral&utm_source=addons.mozilla.org&utm_term=amo-fx-cta-495646)
> 
> What's been verified in 2018 #4737 is not applicable anymore.
> 
> If there's something I did not understand, please let me know.
> 
> I verified this on AMO dev with Chrome and Edge.

This isn't marked as "verified", but I'm not sure why not, based on the above. If the issue is that the button has a different caption between dev and prod, that's because the add-on is not set up as Recommended on dev. The only thing this patch is concerned with is the destination link, which is correct.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified!
