### ISSUE TITLE
Display overall add-on rating (How other users feel)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1065]
This is to implement the UI that shows a summary of ratings for an add-on. Example:

![screen shot 2016-09-14 at 5 03 25 pm](https://cloud.githubusercontent.com/assets/55398/18531710/47f9c6ac-7a9d-11e6-86fa-5358f1b931ec.png)

UX flow: https://mozilla.invisionapp.com/share/A58EEQUK6#/screens/183938152
UX flow tracker: #927
This supports mozilla/addons#151

**Comment by kumar303** [comment]
@diox do we need a new API to display the percentage of smiley ratings? If there is something that already gives us 1-5 star ratings then we could probably map it to percentages on the frontend.

**Comment by diox** [comment]
Yes, I filed https://github.com/mozilla/addons-server/issues/3550

**Comment by muffinresearch** [comment]
This was superceded we don't use smiley faces any more :(
