### ISSUE TITLE
The `Header` for the blog should not render the "Get FF" banner

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10657]
The latest `blog-utils` version (0.19) renders a header with the "Get FF" banner, which isn't expected. Let's fix it: there shouldn't be any banner on the blog.

**Comment by eviljeff** [comment]
Isn't referring people who don't have Firefox to download it a good thing?  Or was this a Product request/requirement not to have it on the blog?

**Comment by willdurand** [comment]
> Isn't referring people who don't have Firefox to download it a good thing? Or was this a Product request/requirement not to have it on the blog?

We are following the mocks and this is a bug that should be fixed.

Showing a banner would be a new (and undocumented) feature, which could be a good idea but that would require a new issue filed by Product in the addons-blog repo :)

**Comment by eviljeff** [comment]
@jvillalobos do we want a feature for free? 😉

**Comment by willdurand** [comment]
There is no free feature, if we ever want to add a banner, we'll need to develop specific code in addons-blog so can we go ahead and fix _this_ issue first? Discussions about a new feature should live in a new issue.

**Comment by eviljeff** [comment]
Okay I guess I don't understand the issue then - a get Firefox banner is rendered at the moment but there would be further code needed to render a get Firefox banner.  Can you include a screenshot or otherwise?

**Comment by willdurand** [comment]
Yes, the library is supposed to output static markup (enhanced with JS in addons-blog).

`yarn build:blog-utils-dev` would show this:

<img width="1552" alt="Screen Shot 2021-06-07 at 16 57 41" src="https://user-images.githubusercontent.com/217628/121039563-7ae68a80-c7b1-11eb-89ea-92a209f502a4.png">

**Comment by jvillalobos** [comment]
Since individual blog pages will have extension CTAs, they should be treated like listing pages and the top banner should not appear. I think the only blog page that should show the banner is the index page.

**Comment by ioanarusiczki** [comment]
@willdurand Looking at the blog with Chrome, the articles don't display the banner. 

Looking at Jorge's comment above, should this page https://addons-dev.allizom.org/blog/ display it?

**Comment by ioanarusiczki** [comment]
@willdurand Done https://github.com/mozilla/addons-blog/issues/228
