### ISSUE TITLE
Display generic add-on ratings

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1066]
This is to implement the UI just below [overall ratings](https://github.com/mozilla/addons-frontend/issues/1065) that shows generic icons selected by other users. Example:

![screen shot 2016-09-14 at 5 07 19 pm](https://cloud.githubusercontent.com/assets/55398/18531797/c2819ae4-7a9d-11e6-8123-58e21c8bae0d.png)

UX flow: https://mozilla.invisionapp.com/share/A58EEQUK6#/screens/183938152
UX flow tracker: #927
This supports mozilla/addons#151

**Comment by muffinresearch** [comment]
Superceded.
