### ISSUE TITLE
Login on AMO stage is not responsive

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10667]
I could not reproduce on dev or prod but on AMO stage:
1. I log in a new profile the first time with an old account
2. I log out and then try to log back in 

Expected: 
Login is successful 

Actual result:
The Register or log in is displayed instead

Sometimes I could reproduce it from the first attempt on a new profile - with an existing account when the passcode from the mobile app is required. 

![login](https://user-images.githubusercontent.com/33448286/121539029-f6447800-ca0d-11eb-847c-249a4c25a06f.gif)

**Comment by ioanarusiczki** [comment]
@diox 
More info:
- What I did first was log out from my admin account and login with rusiczki.ioana@gmail.com and that's when I could no longer login on my default profile. 
- I tried then on new FF profiles with rusiczki.ioana@gmail.com and irusiczki@mozilla.com and it was reproducible but not always at the first login, so try to log out and login again. 
- I tried with a new account on stage and I reproduced it on AMO stage. 
- I could not reproduce it on dev or prod. 
- 
@AlexandraMoga said:
- tested on AMO prod and reproduced it at register (from 4 attempts only once was reproducible).
- on AMO prod with a new FF profile, login with an existing account.

**Comment by bobsilverberg** [comment]
I have been unable to reproduce on stage. Are you still able to consistently reproduce this?

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I could reproduce it again today on my Win10x86 profile - on AMO stage, the way described above.
On my Win10x64 I could not. 
Also it is not reproducible on VM - Sandbox. 

Yesterday, on the profile I'm having this issue, I tested around a security patch and I used a VPN to change my ip address. Also I added one of the e-mails mentioned above into django - it's restricted for auto-approval.  
@AlexandraMoga also tested around the security patch and used a VPN for that.

**Comment by bobsilverberg** [comment]
I'm not really sure what to do with this information. It doesn't sound like we have a reliable STR, and I haven't been able to reproduce it with many attempts.

Have we seen it on prod at all, or only on stage? There is a lot of information above, but it's difficult to sift through. Can you provide a single STR that seems to reproduce most often that we can try?

**Comment by diox** [comment]
A few things to try:
- Can you figure out if it's related to logging out at all ? Like, logging in multiple times in separate containers or closing all your private windows and opening a new one - or even a new browser ?
- Can you figure out if waiting a few seconds between each attempt changes things ?
- Can you reproduce with a fresh account ?

**Comment by ioanarusiczki** [comment]
@diox @bobsilverberg 
I could no longer reproduce the issue on AMO stage. Very strange, but now it's all working fine so I'm closing it.
