### ISSUE TITLE
Add-on compatibility messages should have a unified style

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10662]
Follow up for https://github.com/mozilla/addons-frontend/issues/10649#issuecomment-856695457

### Describe the problem and steps to reproduce it:
Currently the add-on detail page (and the all versions page) displays several compatibility error messages on a red banner based on the following criteria:

[1] add-on requires a higher Firefox version - this will be changed in #10637
![2021-06-08_15h01_17](https://user-images.githubusercontent.com/31961530/121181782-0bcd6c80-c86b-11eb-86f1-706f672b4de2.png)

[2] add-on requires a lower Firefox version
![image](https://user-images.githubusercontent.com/31961530/121181857-20aa0000-c86b-11eb-8370-18398389da6a.png)

[3] add-on is not compatible with the used platform
![image](https://user-images.githubusercontent.com/31961530/121181893-2b649500-c86b-11eb-96e6-24a5eae9315d.png)

I think we should also change the style for the second and third compatibility message to be more in line with the non-Firefox CTA banners.

**Comment by jvillalobos** [comment]
* The "restart" warning should no longer be possible, so I think we can drop it now.
* The "platform" warning shouldn't be possible, either, I think. This was from back when we had OS-specific files for extensions, right? And it wouldn't show up for mobile vs. desktop? Maybe @diox should chime in on this.
* For both the "platform" warning and the "max version" warning the user wouldn't benefit from downloading Firefox. It's possible they are already using the latest version, so it would be confusing to send them to download. The "max version" case should also be really unlikely to happen.

Maybe we could reuse the message box to show the warning messages and leave the disabled button as we currently do. It'd be good to check with UX to make sure that makes sense. That said, these are very rare use cases so I don't think it's something we should worry about much.

**Comment by bobsilverberg** [comment]
It does seem like all of these cases are rare, so perhaps it makes sense to just do nothing at this point. We could remove the code for both detecting and displaying the warnings for "restart" and "platform", because that would remove a bit of technical debt, but putting effort into changing the appearance of the other warnings seems like it wouldn't have a great ROI as they are unlikely to appear much at all.

**Comment by bobsilverberg** [comment]
The "restart" message is being removed via https://github.com/mozilla/addons-frontend/issues/10716. I think the other messages are rare enough that it doesn't merit making any changes to them at this point, so I am going to close this issue.
