### ISSUE TITLE
Node 14

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10671]
With Node 16 already available, we can switch from Node 12 to Node 14 in the coming weeks. This issue is about doing it.

**Comment by willdurand** [comment]
cc @bqbn

**Comment by ioanarusiczki** [comment]
@willdurand Is this with same str for qa ? https://github.com/mozilla/addons-server/issues/17331#issuecomment-879261512

**Comment by willdurand** [comment]
no, this can affect all frontend pages but breakages should be obvious

**Comment by ioanarusiczki** [comment]
@willdurand Release testing is complete now - looks good. 
Verified on AMO stage - FF90(Win10).
