### ISSUE TITLE
Link to the new blog in all envs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10672]
We should soft launch the new blog on June 15th. The next push is on June 17th so we can update the links to point to it in all envs now.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO stage - FF89(Win10) and Fenix for Android.

![linked to stage](https://user-images.githubusercontent.com/33448286/122197602-3449fd80-ce4d-11eb-9d1a-f5df062a8ebe.gif)
