### ISSUE TITLE
Allow for identifying users as on desktop or not

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10670]
This is a spin off from https://github.com/mozilla/addons-frontend/issues/10618.

In order to make it possible to configure an experiment to exclude either all desktop users or all mobile users we need an `isDesktop` function that will identify as user as being on desktop or not.

This is marked as "qa: not needed" as there is no exposed code that uses this function yet.

**Comment by bobsilverberg** [comment]
The library that we currently use to detect `browser` and `os`, [`us-parser-js`](https://github.com/faisalman/ua-parser-js), includes the ability to detect `device`. `device` is further broken down into `model`, `type` and `vendor`, and it looks like `type` is what we want here. The possible values for `type` are `console`, `mobile`, `tablet`, `smarttv`, `wearable` and `embedded`. As can be seen there is no value for `desktop`.

In my local testing, when a desktop browser is used, `device.type` returns `undefined`, and I was able to verify that `console`, `mobile`, `tablet`, `smarttv` and `wearable` are all returned when expected with different user agent strings.

Based on this, I think we could simply say that if `device.type` is `undefined` then it is a desktop browser, and if `device.type` is not `undefined` then we consider it some type of mobile browser. I know this isn't entirely accurate, but it might be close enough. Looking at Google Analytics data for both Browser and Mobile Device over a two week period, the number of devices that are not actually desktops or phones/tablets appears to be very small.

@jvillalobos @mozilla/addons-amo-engineering What do you think of taking this approach for trying to identify mobile vs desktop users?

**Comment by bobsilverberg** [comment]
I opened https://github.com/faisalman/ua-parser-js/issues/502 to discuss whether returning `desktop` from `device.type` could be an option.

**Comment by jvillalobos** [comment]
That sounds like a reasonable approach to me.
