### ISSUE TITLE
Link to the add-on listing page from the add-on name in blog cards

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10684]
Just like we link to the developer page in the add-on card in blog posts, let's also link the add-on name to the listing page. The styling should be the same: blue color and no underline.

**Comment by willdurand** [comment]
It is now available on -dev: https://addons-dev.allizom.org/blog/translate-the-web-easily-with-a-browser-extension/

**Comment by ioanarusiczki** [comment]
@willdurand I added the result in https://github.com/mozilla/addons-blog/issues/241#issuecomment-865848064 

Let me know if it's fine. 
Thanks

**Comment by willdurand** [comment]
> @willdurand I added the result in [mozilla/addons-blog#241 (comment)](https://github.com/mozilla/addons-blog/issues/241#issuecomment-865848064)
> 
> Let me know if it's fine.
> Thanks

@ioanarusiczki it isn't the same feature, right? This one is about the add-on cards.

**Comment by ioanarusiczki** [comment]
@willdurand oh yes, sorry, the add-on card right now displays the name of the add-on with blue - and once it's clicked it redirects to the add-on detail page - on AMO dev ( it's a 404 when the addon is not available on the testing servers). 
The name on the addon-card is not underlined. 

An example:

![blue name](https://user-images.githubusercontent.com/33448286/122925243-7f678300-d31b-11eb-9576-262464485024.gif)
