### ISSUE TITLE
Show more precise star rating in RatingByStar

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-frontend#10688]
### Describe the problem and steps to reproduce it:

Star ratings are rounded to the nearest ten percent. This level of granularity can cause confusion, as just one review can result in the difference between a 10% bar growth. A user has reported about this confusing appearance at https://discourse.mozilla.org/t/review-totals-are-broken-on-amo/81743 .

STR:
1. Visit an add-on with 98 5* ratings, 5 4* ratings, 2 3* ratings and 6 1* ratings - https://addons.mozilla.org/en-US/firefox/addon/custom-scrollbars/
2. Look at the rating

### What happened?
1. 5* yellow bar has width of 90%, 1*'s yellow bar has width of 10%.
![](https://discourse-prod-uploads-81679984178418.s3.dualstack.us-west-2.amazonaws.com/original/3X/f/0/f08564b1c194c0e78d2e89fe5cff06571188ce85.png)

### What did you expect to happen?
There are 111 reviews. I expected the bars to have the following widths:

```
5* 88.288%
4* 4.505%
3* 1.802%
2* 0%​
1* 5.405%
```

### Anything else we should know?

The implementation appears to round to the nearest ten percent: https://github.com/mozilla/addons-frontend/blob/48bec321693671c5fa714be3317019846204f4de/src/amo/components/RatingsByStar/index.js#L36

The original implementation had 100 buckets of precision, but the implementation changed to avoid CSP errors (#10174). This work-around to avoid inline styles (causing the loss of precision) isn't necessary. CSP allows DOM-based style assignments, i.e. using `.style.width = width + "%";` instead of `style="...%"`.

**Comment by iamvaishnav** [comment]
> CSP allows DOM-based style assignments, i.e. using `.style.width = width + "%";`

How can I do it? Should I use ref to access the DOM element?

**Comment by bobsilverberg** [comment]
> > CSP allows DOM-based style assignments, i.e. using `.style.width = width + "%";`
> 
> How can I do it? Should I use ref to access the DOM element?

It sounds like that is what is being suggested, yes.

**Comment by bobsilverberg** [comment]
@iamvaishnav Just checking, are you working on this?

**Comment by iamvaishnav** [comment]
> @iamvaishnav Just checking, are you working on this?

I've been busy these past couple of weeks. I will fix it as soon as possible.

**Comment by iamvaishnav** [comment]
@bobsilverberg I don't think there's any efficient way to test the current fix in jest.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I checked the same data on dev versus stage and noticed that the percentage of the width on -dev has a better distribution:
the sample on [-dev ](https://addons-dev.allizom.org/en-US/firefox/addon/black-shine/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search )
Reviews: 26
5 * 46%
4 * 12%
3 *12%
2 *15%
1 *15%

![distribution on dev](https://user-images.githubusercontent.com/33448286/130443923-2fd944d1-c2a4-446d-900f-c302092fd75d.png)

[Stage](https://addons.allizom.org/en-US/firefox/addon/eyes-in-the-clouds/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search):
5 * 50%
4 * 10%
3 * 10%
2 * 20%
1 * 20%

![distribution on stage](https://user-images.githubusercontent.com/33448286/130443949-2d9d94fa-1d2d-4756-af80-8fb8ec155f22.png)
