### ISSUE TITLE
Exclude Firefox users from the download funnel experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10708]
Firefox users should not be enrolled in the download funnel experiment. 

- If a user already has a cookie placing them in a cohort for this experiment, then that should be respected, regardless of which browser they are using.
- If a user has not been assigned to a cohort yet (i.e., they do not have a cookie), then, if they are on Firefox they should be placed in the special `notInExperiment` cohort, and the experience they should have is the same as someone in the `current` cohort.

**Comment by bobsilverberg** [comment]
This was fixed via #10706

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> * on older FF profiles where I opened AMO dev the previous week, I've noticed current-link but also new-link cookie still being available. In both cases the same layout is available, users have download buttons on the detail pages, so the experiment is not visible here.
> 

I'm not really sure what you are reporting with the above. Any cookies set previously will remain in place and unchanged.

> * I opened several Sandbox sessions and I went on AMO dev on Edge/Chrome, I could see here the current-link and new-link cookies set. Then I installed Firefox and accessed AMO dev, checked the cookie here and I could see `notInExperiment` set.
>

That sounds good, thanks!
 
> 
> Let me know if my method of testing covers this issue.

It does sound like you have it covered. I am just not sure what your first bullet point was reporting.

**Comment by ioanarusiczki** [comment]
@bobsilverberg With the first one I tried to test this:

> If a user already has a cookie placing them in a cohort for this experiment, then that should be respected, regardless of which browser they are using.

Then I think this should be fine, I'm marking it verified on AMO dev - Edge, Chrome and FF89
