### ISSUE TITLE
Update footer link to "Community Blog"

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10705]
We recently updated the footer link label to be "Developer Blog", but we finally settled on "Community Blog" for its new name. The target URL is still the same, we just need the text updated.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev - FF89(Win10). 

![Community blog](https://user-images.githubusercontent.com/33448286/122923367-7f668380-d319-11eb-843c-00711eeaa4ba.png)
