### ISSUE TITLE
Remove all code relating to is_restart_required and is_webextension

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10716]
This started as a spin-off from #10662, but has expanded.

The frontend no longer needs to be concerned with the `is_restart_required` field or the `is_webextension` field returned by the add-on detail API because, for all intents and purposes, the former will always be `false` and the latter will always be `true`.

This allows us to remove quite a bit of code, and will result in the following changes to the app:
- The "Restart Required" badge and the "Not compatible with Firefox Quantum" badges no longer exist.
- The "Your version of Firefox does not support this add-on because it requires a restart" warning no longer exists.

Nothing else about the app should change.

**Comment by AlexandraMoga** [comment]
I'm not sure that we have the possibility to test the removal of those badges specifically (not even from admin) so I verified instead that other badges (like experimental and requires payment) and compatibility notices (platform or firefox version incompatibility) are still displayed correctly. 

![image_2021-07-12_122230](https://user-images.githubusercontent.com/31961530/125263581-d43f5d80-e30b-11eb-9421-72546675a96f.png)
