### ISSUE TITLE
AMO Download Firefox GA event has an incorrect name

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10724]
The name of the GA "download FF" events has unexpectedly changed recently. The regression was introduced in https://github.com/mozilla/addons-frontend/pull/10660.

This is a major problem because some of our GA dashboards are broken:

![Screenshot 2021-06-23 at 16-23-16 Analytics 360](https://user-images.githubusercontent.com/217628/123235758-7540b280-d4dc-11eb-8e36-0e732ff0eddf.png)

When the experiment is disabled (like on -stage/-prod), the GA event shouldn't have an experiment variant, and the name should be "AMO Download Firefox".

When the experiment is enabled (-dev, local dev), there should be a variable appended to the default name (which is the one above).

**Comment by ioanarusiczki** [comment]
@willdurand 

AMO dev:
- enrollment event:
![enrollment on dev](https://user-images.githubusercontent.com/33448286/123252628-5bce4500-d4a1-11eb-8db7-d769bff7759a.png)
- banner click event:
![click event on dev](https://user-images.githubusercontent.com/33448286/123253028-d4350600-d4a1-11eb-9b12-49e359bbcbd3.png)
- detail page click:
![dev detail page click](https://user-images.githubusercontent.com/33448286/123254117-1e6ab700-d4a3-11eb-8415-1323ecb55b3c.png)



AMO stage: 
- banner click event: 
![click event on stage](https://user-images.githubusercontent.com/33448286/123253119-f464c500-d4a1-11eb-83ca-1fdad6b91783.png)

- from a detail page:
![click event detail page stage](https://user-images.githubusercontent.com/33448286/123253691-971d4380-d4a2-11eb-98e6-1c4c24fb660d.png)

Reading the instructions - this should be the expected.

**Comment by ioanarusiczki** [comment]
I checked above -dev and -stage before tags deployed so:
@willdurand 
I re-checked -dev:
same results, this means that I did not see regressions on the funnel experiment 

On AMO stage: 
- the banner and the clicks from the detail pages have "AMO Download Firefox" at `eventCategory` 
banner click:
![click banner on stage](https://user-images.githubusercontent.com/33448286/123283325-26851f80-d4c0-11eb-864b-e00ebd942790.png)

from a detail page :
![click2](https://user-images.githubusercontent.com/33448286/123283520-52a0a080-d4c0-11eb-8d26-c1b40d7d6221.png)
