### ISSUE TITLE
Configure the kab locale

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1072]
A new locale was added via pontoon [1]  and the servertests are failing because that locale hasn't been setup.

[1] https://github.com/mozilla/addons-frontend/commit/f1c1bd8a869d47b052a68a694840ce59c6b5a78b

**Comment by kumar303** [comment]
Example: https://travis-ci.org/mozilla/addons-frontend/jobs/160536074

**Comment by muffinresearch** [comment]
Fixed in https://github.com/mozilla/addons-frontend/pull/1074
