### ISSUE TITLE
Update experiment naming convention to support custom GA dimension on www.mozilla.org

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10749]
This supports https://github.com/mozilla/bedrock/issues/10175

The bedrock team is going to set something up so that, when we are directing traffic to www.mozilla.org, it will automatically pass `experiment` and `variation` to GA so we can use those values when analyzing GA data for www.mozilla.org. 

In order to limit this custom logic to AMO, it's been requested that our value for `experiment` match a specific format. We already have a naming convention that states that experiment names must start with `YYYYMMDD`, and we are going to add to that so that, in the future, experiment names will all start with `YYYYMMDD_amo_`. 

This issue is about documenting and enforcing that new naming convention.

Update:

A concern was raised that perhaps we shouldn't change our naming convention for all experiments to support just one experiment, and that maybe we should just use the new naming convention in the experiment that needs it. Here are some points to counter that concern:
- This convention is not needed for 1 experiment, but rather it's something that will be useful for any experiments we do that send traffic to www.mozilla.org. We already have another one planned (the one for the VPN promo), and it is likely we will continue to experiment with the Download Firefox funnel as driving Firefox installs is a pretty significant goal for our team.
- We could do it on an individual basis, but that seems like more work:
	-  We would have to remember to do it, and the possibility of forgetting introduces a possible footgun.
	- We would have to write a test for the name each time, as opposed to writing one test now which covers all future cases.
- One could argue that it makes sense to include `amo` in each experiment name as this data also ends up in telemetry and therefore helps to identify the source of the data as an AMO experiment.

**Comment by bobsilverberg** [comment]
Based on the implementation in https://github.com/mozilla/bedrock/commit/732a696618c500e35dd7336fffccd15e1c6e51f9, we should also ensure that neither `experimentId` nor `variant` are greater than 50 characters long.

**Comment by willdurand** [comment]
> Based on the implementation in [mozilla/bedrock@732a696](https://github.com/mozilla/bedrock/commit/732a696618c500e35dd7336fffccd15e1c6e51f9), we should also ensure that neither `experimentId` nor `variant` are greater than 50 characters long.

Good call, I wanted to suggest that as well.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue with non-FF browsers and for `new-link` or `current-link` the `experiment` has the new value:

![experiment](https://user-images.githubusercontent.com/33448286/125284299-23ff3400-e2ce-11eb-80ab-28336e6ac77f.png)
