### ISSUE TITLE
Enable download funnel experiment on stage and prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10753]
Everything is ready for us to run the experiment, so we can enable it on stage next Tuesday and on prod next Thursday.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

On AMO stage I've noticed the experiment being present on desktop Win10 and Android.
I don't see a different behavior compared to -dev in GA events, telemetry data, RTAMO flow.
