### ISSUE TITLE
Investigate enhanced ecommerce on dev

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10756]
Enable GA's enhanced ecommerce plug-in on dev to experiment with its functionality.

The idea is to see whether it will enable us to track impressions and report on the number of impressions a user sees prior to clicking on and dismissing the promo. I'm not sure it will give us the data we need, but it's worth investigating locally and/or on dev.

Here are some links to docs about the enhanced ecommerce plug-in:
- [Implementation guide](https://developers.google.com/analytics/devguides/collection/analyticsjs/enhanced-ecommerce)
- [Enhanced Ecommerce reports](https://support.google.com/analytics/answer/6014872)

I may be able to do this investigating locally, without deploying anything to dev, and if that is the case I will do that.

**Comment by bobsilverberg** [comment]
I enabled enhanced ecommerce for the `localhost` view on GA, and generated a bunch of data from my local installation. It doesn't look like we can get the specific data we need from this. Here is [a link to a report on GA](https://analytics.google.com/analytics/web/#/report/conversions-ecommerce-internal-promotion/a36116321w65861930p240326961/_.goalOption=ECOMMERCE/). We are able to see total number of impressions, and total number of clicks, as well as the CTR, but we cannot see anything about number of impressions before a click. I therefore don't think this is actually going to give us what we need for this experiment, and we can abandon the idea of using this plug-in.

If we are going to eventually implement this promo then this feature could be useful, to allow us to report on the CTR for various groups, perhaps in future A/B experiments, although we can probably do that without this feature.

@jvillalobos You might want to look at the report linked to above and see if you have any comments before I close this issue.

**Comment by jvillalobos** [comment]
Yeah, it doesn't look like what we need. It's more like the usual impressions vs. clicks that is used for ad performance. I agree it doesn't provide what we're looking for in the experiment.
