### ISSUE TITLE
Implement a VPN Promo banner

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10755]
For the VPN Promo experiment, we need to display a banner at the top of the page. The banner should be the same as the one currently displayed at https://monitor.firefox.com/, which looks like:

<img width="1107" alt="Screen Shot 2021-07-09 at 12 49 05 PM" src="https://user-images.githubusercontent.com/142755/125111699-3736b780-e0b4-11eb-8e67-d3a4ecc7f955.png">

The code for this banner can be found at https://github.com/mozilla/blurts-server/blob/main/views/partials/vpn-promo.hbs.

**Comment by bobsilverberg** [comment]
Here are some screenshots of the current implementation for AMO, using the Inter font:

Monitor:

![Screen Shot 2021-07-13 at 1 19 54 PM](https://user-images.githubusercontent.com/142755/125497369-3e5c457c-cc50-47dd-adb1-c70670111d4e.png)

AMO:

![Screen Shot 2021-07-13 at 1 19 36 PM](https://user-images.githubusercontent.com/142755/125497340-46871568-c830-49f2-939d-25c73660e9bb.png)

Monitor:

![Screen Shot 2021-07-13 at 1 23 14 PM](https://user-images.githubusercontent.com/142755/125497589-4be38084-6ab2-41ff-8b6a-18e35252d2a0.png)

AMO:

![Screen Shot 2021-07-13 at 1 23 52 PM](https://user-images.githubusercontent.com/142755/125497673-5c1cee50-978c-485f-806d-2742da576648.png)

Monitor:

![Screen Shot 2021-07-13 at 1 25 10 PM](https://user-images.githubusercontent.com/142755/125497879-3b930eb5-5868-4152-866c-cdd6b7cd6c0e.png)

AMO:

![Screen Shot 2021-07-13 at 1 25 51 PM](https://user-images.githubusercontent.com/142755/125498008-664b6782-4b50-459f-b49c-22ec3000f7d2.png)

**Comment by bobsilverberg** [comment]
Here's an example where the font size for the copy is slightly smaller, and the font weight for the headline is bumped up a bit, trying to get closer to the original. I think, because of the nature of our font file, we aren't actually able to bump up the boldness of the font, so although the `font-weight` is higher, it doesn't actually look any bolder. I'll see if there's anything we can do about that.

Monitor:

![Screen Shot 2021-07-13 at 1 19 54 PM](https://user-images.githubusercontent.com/142755/125497369-3e5c457c-cc50-47dd-adb1-c70670111d4e.png)

Updated AMO: 

![Screen Shot 2021-07-13 at 1 53 03 PM](https://user-images.githubusercontent.com/142755/125501439-c231fcba-c077-4a20-986a-91dee3808997.png)

**Comment by bobsilverberg** [comment]
Here's an example using the system `sans-serif` font, instead of our custom Inter font:

![Screen Shot 2021-07-13 at 2 08 36 PM](https://user-images.githubusercontent.com/142755/125503408-931b5d4f-45c1-460a-b824-a43a8e0ed114.png)

It's closer to what monitor has in terms of size and weight, and I think it looks decent. There is some concern that, in order to allow for a bolder font than in the example at https://github.com/mozilla/addons-frontend/issues/10755#issuecomment-879285800, we're going to have to regenerate the font file with an additional weight and that's going to increase the size of the file.

Do you think the above is acceptable?

**Comment by jvillalobos** [comment]
Yes, I think that looks a bit better than Inter, so it should be good for the test. Given that it's a system font, was this taken on Windows? Would it look different on macOS?

**Comment by bobsilverberg** [comment]
> Yes, I think that looks a bit better than Inter, so it should be good for the test. Given that it's a system font, was this taken on Windows? Would it look different on macOS?

It was taken on a Mac, I don't have Windows, but I would assume it might look different on different OSs and even on different browsers.

**Comment by willdurand** [comment]
> I don't have Windows

You might want to use a VM for quick testing: https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
