### ISSUE TITLE
Send a separate event for experiments

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10750]
This is follow-up from https://github.com/mozilla/addons-frontend/issues/10724.

When we enable the Download Funnel Experiment on prod the same problem as reported in the issue above will manifest. We want to be able to count the number of events that come from each variation, but we also don't want to affect data that is continually being collected outside of experiments.

The problem with the current setup is that, when an experiment is running, we add the variant name to the event category, so "AMO Download Firefox" becomes "AMO Download Firefox-new-link", for example. This means that any reports that are counting the "AMO Download Firefox" event will show zero data for the duration of the experiment.

It was decided that the best way to address this is to keep the current event (which in this case is "AMO Download Firefox") untouched, and to send an additional event just for the experiment. This way the existing event can continue to be used for reporting as usual, and the additional event can be used for counting events on a per-variant basis.

In terms of implementation, it's thought that we might be able to make this automatic by enhancing the `sendEvent` function in `tracking` to make it smart enough to be able to issue the additional event for an experiment if one is active.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev with non-FF browsers the Console events when at download button clicks:

1. The `new-link`:

- banner click:
![37](https://user-images.githubusercontent.com/33448286/125287587-f7e5b200-e2d1-11eb-9f62-a7fd454e65d9.png)

- detail page click:
![25](https://user-images.githubusercontent.com/33448286/125287610-ffa55680-e2d1-11eb-8bb8-2409a751a0cc.png)

2. The `current-link`:

- banner click:
![32](https://user-images.githubusercontent.com/33448286/125287677-121f9000-e2d2-11eb-8780-5e10c27a14da.png)

- detail page click:
![27](https://user-images.githubusercontent.com/33448286/125287716-1e0b5200-e2d2-11eb-96cf-39d8cd3fc31e.png)


3. The enrollment event is present only once in the console:

![Enrollment event](https://user-images.githubusercontent.com/33448286/125287982-76daea80-e2d2-11eb-99cf-de128f0ee741.png)
