### ISSUE TITLE
Address code coverage issues with addonManager and installAddon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10762]
The [coverage report](https://app.codecov.io/gh/mozilla/addons-frontend/compare/10760) for https://github.com/mozilla/addons-frontend/pull/10760 highlights some missing coverage for [`addonManager`](https://app.codecov.io/gh/mozilla/addons-frontend/compare/10760/tree/src/amo/addonManager.js) and [`installAddon`](https://app.codecov.io/gh/mozilla/addons-frontend/compare/10760/tree/src/amo/installAddon.js), both of which can likely be addressed.

This issue is about bumping up the reported code coverage for those components.

For QA:

Some unneeded code was identified and removed in this patch, so please verify that the install button and download links continue to work as before, and that add-on installation works.

**Comment by vcarciu** [comment]
Verified as fixed
