### ISSUE TITLE
Reviews show some letters truncated 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10763]
Followup for https://github.com/mozilla/addons-frontend/issues/10405#issuecomment-879071916

Some UX minor issues have been noticed:

On AMO dev with FF89(Win10):
- on addon reviews page "j" looks just a little bit truncated:

![j](https://user-images.githubusercontent.com/33448286/125456504-6421f30c-079a-442a-8810-d2280f9ac002.png)

- The detail page shows the review too (for the user). In this case "j" and "p" still look truncated:

![j detail page](https://user-images.githubusercontent.com/33448286/125456519-5f618bf6-5ffa-48a6-8e6e-1fd2d59aa080.png)

![p on the detailpage](https://user-images.githubusercontent.com/33448286/125456536-f7dffc61-e041-4710-8aa8-d6c542b6945a.png)

**Comment by championshuttler** [comment]
I will stab it!

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
Verified on AMO dev - FF90(Win10). 

![j on detail page](https://user-images.githubusercontent.com/33448286/125937473-d371d3ce-589f-48c8-90da-35e3dc588c98.png)
![j is fixed](https://user-images.githubusercontent.com/33448286/125937484-08d6c20d-78c2-4d5d-a88c-75ca3e632608.png)
![p is fixed](https://user-images.githubusercontent.com/33448286/125937494-bd57236a-5046-429c-ba93-163b24dc26f9.png)
