### ISSUE TITLE
Enable reporting of VPN Promo impressions per click/dismissal

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10772]
We would like to be able to report on the number of times that a user saw the promo prior to clicking on or dismissing the banner, which will enable us to make decisions about how to display the banner if we decide to proceed post-experiment.

The simplest way to do this is to keep track of impression counts via `localStorage`, and then, when a user either clicks on the CTA or dismisses the banner, we can send the impression count in the `label` of the GA event. This will allow is to use the impression count as a dimension in GA reports. If we think we'll want to also report on aggregate data about impression counts (e.g., average number of impressions per user before clicking or dismissing), then we could also add a custom metric, but I don't think that's something we're particularly interested in reporting on.

@jvillalobos What do you think of that last part?

**Comment by jvillalobos** [comment]
I think that having it as a dimension should be sufficient for our purposes.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I verified using the browser-console with Chrome on AMO -dev (VPN set for Chicago):

With `show-promo` cohort : The number of times a user saw the promo is stored into `eventLabel:` which means if I navigate and see 6 different detail pages the eventValue will be "6". Then if I click on the banner (impression or dismiss) there's the "vpn-promo-banner-impression" or "vpn-promo-banner-dismiss" that stores the last value "6" for example - in case that's the place where the user took action on the banner.

![eventLabel](https://user-images.githubusercontent.com/33448286/127143609-7b743685-a462-446b-b0d3-a2a2cd79cea4.png)


Note: "eventLabel" increases to "2" if I am on the detail page and refresh the page. So a page refresh is also counted (but this could be expected)
