### ISSUE TITLE
expose tags on addon details page

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10771]
We want to expose the tags an add-on has in the More Information box on the addon details page, linking to a url that will show other add-ons with the same tag.  Tags are in the process of being changed on addon-server (see other issues in https://github.com/orgs/mozilla/projects/158) but the API already supports and exposes tags so none of the server side work blocks.

mockup from PRD:
![Screenshot 2021-06-25 at 10-33-18 LastPass Password Manager – Get this Extension for 🦊 Firefox (en-US)](https://user-images.githubusercontent.com/768592/125611459-58042579-ff33-4c45-862b-f43287f32b09.png)

**Comment by ioanarusiczki** [comment]
@eviljeff 

- the tags from the addon detail page redirect to a search result that contains that tag as parameter. The search result opens into the same tab. 
- as UX, the dots that separate tags look quite tiny on desktop - Win 10 (I'd increase the size)

![tags on Win](https://user-images.githubusercontent.com/33448286/127872678-94bc9fdc-851b-4d31-b8df-bc0fd32100c7.png)

- on small screens dots and tags look good - on Android. Also the tags redirect to search results that will display only recommended for android addons that contain the same tag. 

![tags on android1](https://user-images.githubusercontent.com/33448286/127872982-96458d10-a911-4ed6-8ee9-371a94415332.png)

**Comment by eviljeff** [comment]
>     * as UX, the dots that separate tags look quite tiny on desktop - Win 10 (I'd increase the size)

Jorge chose the smaller dots based on my screenshots in the PR and looks alright to me but possibly monitor dpi/etc dependant.
