### ISSUE TITLE
Limit the VPN Promo Experiment to users from specific regions and to desktop only

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10774]
Exclude any users from the experiment who are not from `US`, `DE` or `FR`. We should also only enroll users who visit the desktop (`/firefox/`) site. Although this isn't strictly necessary, by doing so we can share the logic between the experiment's `shouldExcludeUser` function and the display logic for the banner, as we do not want the banner to appear on any `/android/` pages.

The patch for this issue does the following:
- Introduces an experiment for the VPN Promo, which is enabled on dev.
- For experiment enrollment:
  - excludes users not in US, FR or DE
  - excludes anyone who first lands on an `/android/` page
  - for those not excluded by the above criteria, will place 5% in a `show-promo` cohort, will place 5% in a `hide-promo` cohort, and will place the remaining 90% in the `notInExperiment` cohort. Note that this `notInExperiment` cohort is also where excluded users are placed.
- For the logic for when to display the promo:
  - will hide the promo on any `/android/` page
  - will hide the promo if the user is not in US, FR or DE
  - will hide the promo if the user is in any cohort other than `show-promo`

If the promo is shown, then an impression event should be sent to GA. If the promo is hidden then no impression event should be sent to GA.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

- Using a VPN - with FF90, region: FR, most of the times I got `notInExperiment` and once the `show-promo` cookie - expected

- I tried with Edge, region:DE, most of the times I got `notInExperiment` and once the `hide-promo` cookie - expected

- Chrome with region:US most of the times `notInExperiment` and once `show-promo` appeared - expected

- going from a region where the banner is expected to be displayed (with `show-promo` cookie) to a region where it's restricted also works as expected - the banner is no longer displayed
 
- the enrollment events are registered by the console
an example: 
![show promo enrollment event](https://user-images.githubusercontent.com/33448286/127147434-0c8e0459-50c5-4be4-a28c-5ee00a430dba.png)
- the click events on the banner are registered as I detailed into https://github.com/mozilla/addons-frontend/issues/10772#issuecomment-887420131 - please note: the banner still cannot be dismissed (but it's known from the last week)

- with `show-promo` cookie from a region where the banner is available I switched to android pages - the banner is not displayed for `android`. Also, I tried on an Android device from my region (where the banner should not be visible) and I could not see the banner being displayed (last week it's been visible). 

- with `hide-promo` cookie, I did not see the banner being displayed on detail pages. 

- given the small percentage when the banner is shown (5%), I've been able to get the `show-promo` cookie twice. I filed an issue https://github.com/mozilla/addons-frontend/issues/10794, I tried to add all details I could remember.
