### ISSUE TITLE
drop fallback using Shelf.criteria from API if Shelf.footer.url isn't provided

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10776]
If there isn't a custom footer url specified for a shelf we currently build the url using an assumed base url for the `endpoint`, and the `criteria`.  The same construction is already done server-side and returned in the `url` property - frontend should be able to rely on that instead.  Less duplication and work would only need to be done in a single place if the url construction changed (or a slightly different url construction was needed e.g. for the tag shefl)

**Comment by eviljeff** [comment]
After looking into this, it would be more straightforward to just always return footer (url and text) - i.e. generate those server side when they aren't set in admin.

(using `url` is problematic because it's the _api_ url, which needs to be modified to be a frontend url)

**Comment by eviljeff** [comment]
QA: make sure shelves still work - in particular shelves that don't specify a footer pathname in django admin.  The API side work that enables this in mozilla/addons-server#17544 so might be easier to verify that issue first.

**Comment by ioanarusiczki** [comment]
@eviljeff I enabled several shelves using collections, search and random-tag endpoints  without a footer pathname specified in admin and I did not get errors. 
Looks good to me.
