### ISSUE TITLE
Only display the VPN Promo Banner on the detail page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10773]
The first iteration of the VPN Promo Banner appears on every page, but, for the experiment, we only want it to appear in the add-on detail page, and only for extensions.

**Comment by bobsilverberg** [comment]
@jvillalobos The document says "For the experiment, the ad will be shown on all extension listing pages on AMO, for desktop users only."

Does this include theme listing pages as well, or should it only be displayed on extension listing pages? Note that limiting it to only extension pages will add complexity to the code required for the experiment.

Also, we currently have a flag that tells us if a page is an "addonInstallPage", and those pages include both the Add-On Detail page, as well as the All Versions page. Is it okay if the banner appears on both of those types of pages? Again, limiting it to just the Add-On Detail page will add complexity for the experiment.

**Comment by jvillalobos** [comment]
Showing it in version pages is fine. I would prefer not to show it on theme pages because it will probably impact the conversion numbers and I don't think we have a good way to tell extension and theme pages apart on GA.

**Comment by bobsilverberg** [comment]
> Showing it in version pages is fine. I would prefer not to show it on theme pages because it will probably impact the conversion numbers and I don't think we have a good way to tell extension and theme pages apart on GA.

Fair enough. I'd like to implement the minimum amount of changes necessary to run the experiment, but I can see how this could affect the numbers we get from the experiment, so I will look into making it work for just extensions.

**Comment by bobsilverberg** [comment]
@jvillalobos The complication we have here has to do with the way the site requests data from the API asynchronously. When we first navigate to an add-on detail page, we do not know which type of add-on it is, when we display the add-on detail page in a loading state. After the API request returns the data, we populate the page with the details of the add-on.

This creates a problem with hiding and showing the banner based on add-on type. With the current set up, we can either:
- assume it is an extension, and therefore show the banner during the loading state, and then hide it if a theme loads, or
- assume it is not an extension, and therefore hide the banner during the loading state, and then show it if an extension loads.

Neither of these are ideal. The latter, I think, is worse, as it really makes the banner feel like it's in your face when it pops in and moves all the content of the page down, while the former is slightly annoying, with the banner appearing for a moment and then disappearing.

I don't think there is any way of addressing this issue without introducing another change to the site, which I will describe below.

Note that this only happens with client-side navigation and isn't an issue with the initial page load, as we are able to determine the add-on type on the server before rendering the page for the initial page load. Given this, one change we could make to the site to fix this would be to always include the add-on type in the URL when navigating to an add-on detail page. We should always have this information when we are generating a link, so we should be able to add it, and if we have access to it on the URL then we could use this info to determine whether the banner should be shown or not, even during the loading phase.

@willdurand what do you think of this proposal, or can you think of another way of dealing with it?

**Comment by jvillalobos** [comment]
> assume it is an extension, and therefore show the banner during the loading state, and then hide it if a theme loads, or
> assume it is not an extension, and therefore hide the banner during the loading state, and then show it if an extension loads.

If this delayed reaction is also true for users who have dismissed the ad or already clicked on the CTA, I would definitely prefer showing it after loading the data than hiding it. If that use case isn't impacted, then I don't feel that strongly for one over the other. It's a glitchy UX, but probably not that annoying and also it's for a short experiment.

> include the add-on type in the URL when navigating to an add-on detail page

I suppose you mean adding something like `?type=extension` rather than change the current URL structure. That sounds fine to me, though I don't know if that will lead to buggy behavior when trying to cover all the use cases for internal linking. Maybe it's a one-line change 🤷 

Tossing another idea into the mix: would it be possible that we record whether something is happening on an extension or theme page in the events that we're recording for this experiment? That way we would be able to count impressions and clicks on extension vs. theme pages independently. It would have some noise for users who navigate both, but they are probably a small group.

**Comment by willdurand** [comment]
> would it be possible that we record whether something is happening on an extension or theme page in the events that we're recording for this experiment?

Yes, I believe we already make this distinction for install events: https://github.com/mozilla/addons-frontend/blob/fc042952607445737bf6a2865be8b455a8a3899a/src/amo/constants.js#L218-L219

**Comment by bobsilverberg** [comment]
> > assume it is an extension, and therefore show the banner during the loading state, and then hide it if a theme loads, or
> > assume it is not an extension, and therefore hide the banner during the loading state, and then show it if an extension loads.
> 
> If this delayed reaction is also true for users who have dismissed the ad or already clicked on the CTA, I would definitely prefer showing it after loading the data than hiding it. If that use case isn't impacted, then I don't feel that strongly for one over the other. It's a glitchy UX, but probably not that annoying and also it's for a short experiment.
> 

I think we can avoid it for people who have already dismissed or clicked on the ad (we're still trying to work out exactly how we're going to make that work with the caching issue), so maybe we just accept the ugly UI for the length of the experiment? 

> > include the add-on type in the URL when navigating to an add-on detail page
> 
> I suppose you mean adding something like `?type=extension` rather than change the current URL structure. That sounds fine to me, though I don't know if that will lead to buggy behavior when trying to cover all the use cases for internal linking. Maybe it's a one-line change 🤷
>

Yes, I'm talking about adding a URL parameter, not changing the path of the URL. It is a pretty small change, but it does cascade across a number of components. I don't anticipate bugs, but I can do a quick verification locally.

> Tossing another idea into the mix: would it be possible that we record whether something is happening on an extension or theme page in the events that we're recording for this experiment? That way we would be able to count impressions and clicks on extension vs. theme pages independently. It would have some noise for users who navigate both, but they are probably a small group.

As Will mentioned, we can probably do this by using a different event category, or we could use the event label, as that's not currently being used for this event. We still have the issue of how to deal with an impression during loading, because at that point we don't know the add-on's type, but we could possibly defer the impression event until after the add-on loads. That would, unfortunately somewhat complicate the component as currently we don't need to worry about the lifecycle for this component and we simply send the impression when it first loads on the client.

It seems there are tradeoffs with each approach. I'll summarize them here, and I'd be interested to hear which @willdurand thinks is the best option:
1. Always hide the banner by default and show it when an extension loads. This will cause the UI to shift when an extension loads, but in some ways that might not be terrible as it will draw more attention to the banner, which might be advantageous. I am suggesting this approach (as opposed to always showing it and then hiding it for themes) because it will make the impression logic simpler.
2. Add a URL paramater for `addonType` to all internal URLs that point to the add-on detail page, which should resolve the issue and allow us to only show the banner on extension pages. We should also consider if this might be something we'll need for future use cases as well.
3. Always show the banner on the add-on detail page, regardless of the type of add-on, but add information to the GA event we send which will indicate which type of add-on was present. This will require a bit of extra code to deal with impressions as we'll need to defer sending the event until an add-on has loaded.

@willdurand WDYT?

**Comment by bobsilverberg** [comment]
Note that another advantage of option 2 is that it makes it easier to only display the banner on Add-On Detail pages, and not also on the All Versions page. As I've already spent a bunch of time testing it, I'm going to put up a PR for option 2.

**Comment by willdurand** [comment]
Option 2 does not sound great to me 🤷 In fact, if we already have the add-on loaded, we can look-up the redux state while loading the detail page and get the information needed from there.

**Comment by bobsilverberg** [comment]
> Option 2 does not sound great to me 🤷 In fact, if we already have the add-on loaded, we can look-up the redux state while loading the detail page and get the information needed from there.

Well, most of the time we will not already have the add-on loaded, so that doesn't really solve the problem, unless I am misunderstanding what you are saying. As mentioned above, I've already done the work for option 2, and it seems to work well, so I will ask you to take a look at the PR and let me know what issues you have with it. I think the tradeoffs we have to accept with options 1 and 3 are things that we should try to avoid if we can come up with a solution that works (which I think option 2 does).

**Comment by willdurand** [comment]
But how do you know the add-on type if the add-on isn't loaded?

**Comment by willdurand** [comment]
And how is this solved on the server?

**Comment by bobsilverberg** [comment]
> But how do you know the add-on type if the add-on isn't loaded?

An internal link to an add-on detail page is only ever created when we have data for the add-on. We are using the data from the search result (for example) to populate a URL param on the link to the add-on detail page. It's not needed if the user is landing directly on an add-on detail page, as this problem only manifests for client-side navigation.

**Comment by bobsilverberg** [comment]
> And how is this solved on the server?

We already have the add-on before we return the page to the client when the add-on detail page is rendered via SSR.

**Comment by willdurand** [comment]
> An internal link to an add-on detail page is only ever created when we have data for the add-on. We are using the data from the search result (for example) to populate a URL param on the link to the add-on detail page. It's not needed if the user is landing directly on an add-on detail page, as this problem only manifests for client-side navigation.

so it is in the redux store then?

**Comment by bobsilverberg** [comment]
> > An internal link to an add-on detail page is only ever created when we have data for the add-on. We are using the data from the search result (for example) to populate a URL param on the link to the add-on detail page. It's not needed if the user is landing directly on an add-on detail page, as this problem only manifests for client-side navigation.
> 
> so it is in the redux store then? Edit: I commented in #10778

Well it is, temporarily, and also we don't know exactly where it is, plus looking it up is difficult. These seem like reasons why we might not want to be tasked with looking it up. 

For example, if we just did a search then the data would be in the `search` state (in a `results` array, which would have to be searched for the add-on in question), whereas if we are coming from the home page, the data would be in the `home` state (in `homeShelves.results`, which is itself an array of shelves, each of which has an array of `addons`) so again, it's difficult to find the data for a specific add-on. Those are just two examples, and there are quite a few more.

So I think just "looking it up" with our current setup would be a lot of trouble. An alternative would be to have a state where we store any and all search results, and then we could use that for looking up add-ons, but this would also require quite a bit of work (creating the reducer for this, and updating every reducer to write to it). We would also then end up double-storing all of the add-ons, which doesn't sound ideal.

I might be overlooking a different solution that you had in mind, so please let me know if there is one.

**Comment by willdurand** [comment]
Well, I guess I'll write a patch then.

**Comment by willdurand** [comment]
> Well it is, temporarily, and also we don't know exactly where it is, plus looking it up is difficult. These seem like reasons why we might not want to be tasked with looking it up.
> [...]

I don't think that's fair. There are only a few redux states in the whole store where we'd need to look for the add-on type so we can look in each sequentially until we find the type for the add-on we need to load in `Addon`. I agree with the last part of your comment, duplicating data in the store is almost never a good idea, but that isn't what I was suggesting.

Is adding noise to URLs any better? The query string will end up being used by end users because that's what they will copy/paste, which is mainly why I am against using query parameters here.

Now back to your options, we can discard Option 3 because we don't want to display the banner for theme detail pages. Option 1 does not seem too good on the paper but maybe that would work? When we load a detail page on the client, the loading indicators already cause flickering and for theme pages, the theme preview also moves the content down by about the same height as the VPN banner.

I just tried Option 1 and it is not _that_ bad. If we know that once users dismiss the banner, they won't see it any time soon and that server-side requests will show the final content directly, I'd say it is worth a try (and still a lot better than adding query params to our URLs).

**Comment by willdurand** [comment]
> I just tried Option 1 and it is not _that_ bad. If we know that once users dismiss the banner, they won't see it any time soon and that server-side requests will show the final content directly, I'd say it is worth a try (and still a lot better than adding query params to our URLs).


Gif or it didn't happen!

![2021-07-19 14 53 18](https://user-images.githubusercontent.com/217628/126162884-6500f0ed-8970-4c9d-81f3-472e734c9f2c.gif)

**Comment by bobsilverberg** [comment]
> > Well it is, temporarily, and also we don't know exactly where it is, plus looking it up is difficult. These seem like reasons why we might not want to be tasked with looking it up.
> > [...]
> 
> I don't think that's fair. There are only a few redux states in the whole store where we'd need to look for the add-on type so we can look in each sequentially until we find the type for the add-on we need to load in `Addon`. 

There are, in fact, at least 7 different states where the data could be (as listed at https://github.com/mozilla/addons-frontend/pull/10778#discussion_r672271730), which is part of my concern. If we added more states that could possibly include search results we'd need to remember to update this function, which is why I am not too keen on it.

> 
> Is adding noise to URLs any better? The query string will end up being used by end users because that's what they will copy/paste, which is mainly why I am against using query parameters here.
>

TBPH, that's not really a major concern of mine, but I hear it is something you see as a problem.
 
> Now back to your options, we can discard Option 3 because we don't want to display the banner for theme detail pages. Option 1 does not seem too good on the paper but maybe that would work? When we load a detail page on the client, the loading indicators already cause flickering and for theme pages, the theme preview also moves the content down by about the same height as the VPN banner.
> 
> I just tried Option 1 and it is not _that_ bad. If we know that once users dismiss the banner, they won't see it any time soon and that server-side requests will show the final content directly, I'd say it is worth a try (and still a lot better than adding query params to our URLs).

Given all of this, I think it makes sense to just go with option 1 for this experiment, and then, if we do decide to implement this in a more permanent manner, we can decide if that's still okay or if we need something else.

**Comment by bobsilverberg** [comment]
@jvillalobos, given the discussion above, and the complexity required to always know if a page being loaded is an extension page or not, it seems like we should keep things simple for the experiment and take what is listed as [option 1, above](https://github.com/mozilla/addons-frontend/issues/10773#issuecomment-881397729). 

When navigating to an extension page client-side, the banner would not be shown while the add-on is being fetched and would then appear afterwards. @willdurand included a [screencap](https://github.com/mozilla/addons-frontend/issues/10773#issuecomment-882523974) of this above.

Please confirm if you're okay with us taking this approach for the experiment. Note that this only happens with client-side navigation, and it ensures that the banner only appears on the Add-On Detail page, and only for extensions.

**Comment by jvillalobos** [comment]
That approach is fine with me.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I verified this on Chrome on AMO dev:
- the promo banner is available only on the extension detail pages. It is not displayed for themes, langpacks or dicts.

- "Get Mozilla VPN" can be clicked and redirects to https://www.mozilla.org/en-US/products/vpn/?utm_campaign=amo-vpn-promo&utm_medium=referral&utm_source=addons.mozilla.org 

- I could not dismiss the banner with `X`  - is this expected ? 

![VPN promo](https://user-images.githubusercontent.com/33448286/126334442-04460d46-4c71-4080-b8a4-ccd1ab90a745.gif)

- the banner is available on Android but I see there's another issue opened https://github.com/mozilla/addons-frontend/issues/10774 to fix that.

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki!

The dismiss button behaviour has indeed not been implemented yet, so that is expected, and you are correct that excluding this from `/android/` pages is coming in a future patch.
