### ISSUE TITLE
Remember the dismissed status of the VPN Promo Banner

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10770]
When a user clicks the dismiss button on the VPN promo banner we should dismiss it and remember not to show it to them again. In order to persist this information, it should be stored in a cookie.

**Comment by bobsilverberg** [comment]
As discussed on Slack:

The Problem:
- We cannot write a cookie on the server as it breaks caching, but this is solvable bu only writing the cookie on the client.
- If we want a server-rendered request to respect a cookie (i.e., read a cookie and return a different UI based on it), which in this case would mean reading a cookie and hiding the VPN Promo banner if the cookie says it's been dismissed, then we would need to add the cookie to the cache key. This is something we have done for experiments, but we are wary of adding yet another element to the cache key.
  - Not only is this not scalable (we cannot just keep adding new elements to the cache key), but also...
  - We potentially break caching by making the cache key so complex that very few requests actually hit the cache. 

Some Potential Solutions:
- Instead of adding a new element to the cache key, change our cookie approach so we have one single cookie that acts as a container for any data we need to store in a cookie.
  - This simplifies our configuration (i.e., we don't need to keep adding new elements to the cache key), but introduces a couple of other issues:
    - We would need to write a layer to manage this cookie, as different components would be writing to it for different reasons.
    - It doesn't really address the cache hit problem, because as the number of possible combinations of values that might be stored in this cookie grows, the likelihood of getting a cache hit decreases, just as it would with multiple cookies being added to the cache key.
 - Hack around this requirement by forcibly removing a user from the experiment after they dismiss the banner.
   - If the user is not in the experiment then they won't see the banner, so this should work, and it doesn't introduce an extra element to the cache key.
   - This would work if we no longer need to record anything about the user after they have dismissed the banner, but that's actually not the case. For example, we also want to know if users in the experiment install fewer add-ons, and removing them from the experiment at the point at which they dismiss the banner would prevent us from collecting that info.
   - We could possibly further hack around that limitation by introducing yet another experiment variant, one which says "yes, this user is still in the experiment, but please don't show them the banner anymore".
   - While it seems like we could make this approach work for the experiment, it won't work long term if we end up deciding to run this promotion *without* an experiment.

Let's discuss this further and see if anyone has any other suggestions/concerns, @jvillalobos @diox @willdurand @eviljeff @muffinresearch

**Comment by bobsilverberg** [comment]
Some questions about requirements for @jvillalobos:

1. In the doc you say "we want to avoid showing the ad once the user has dismissed it. I would add that dismissing the ad should be permanent, even if the user dismissed it during the experiment, so we should keep the cookie for as long as possible." We can do this by setting a long expiry date for the cookie - perhaps 1 year?
2. Should we use the same logic for hiding the banner if a user clicks on the CTA? Do we want to hide the banner after a user clicks on the CTA, or only if they dismiss it? And if the former, do we keep it hidden "permanently" as well?

**Comment by willdurand** [comment]
> In the doc you say "we want to avoid showing the ad once the user has dismissed it. I would add that dismissing the ad should be permanent, even if the user dismissed it during the experiment, so we should keep the cookie for as long as possible." We can do this by setting a long expiry date for the cookie - perhaps 1 year?

If this was looking more like part of the UI and not an "ad", we could have omitted the dismissal feature entirely IMO. This wouldn't solve the technical issue but now that we have caching and that we want to optimize it, we don't have a lot of options except not having to rely on cookies too much.

On that topic, I remember many moons ago that an option to have aggressive caching **and** dynamic content was [edge side includes](https://www.w3.org/TR/esi-lang/). Maybe that could be an idea? I see there is a react project for ESI: https://github.com/dunglas/react-esi

**Comment by bobsilverberg** [comment]
Further to the long comment above at https://github.com/mozilla/addons-frontend/issues/10770#issuecomment-879827203, I think the best approach, for this experiment, is to use the `variant` to identify whether someone has dismissed the ad or not. This would add nothing to our current cache key, and isn't really that hacky.

This does not solve a couple of issues, though:
1. After the experiment, we will not "remember" that certain users dismissed the banner.
2. If we want to implement the ad after the experiment we will need a different approach.

Given these two items, I think it's still worth entertaining the idea of using a dedicated cookie to record dismissal and adding it to the cache key, so I think this still needs discussion.

**Comment by bobsilverberg** [comment]
> > In the doc you say "we want to avoid showing the ad once the user has dismissed it. I would add that dismissing the ad should be permanent, even if the user dismissed it during the experiment, so we should keep the cookie for as long as possible." We can do this by setting a long expiry date for the cookie - perhaps 1 year?
> 
> If this was looking more like part of the UI and not an "ad", we could have omitted the dismissal feature entirely IMO. This wouldn't solve the technical issue but now that we have caching and that we want to maximize it, we don't have a lot of options except not having to rely on cookies too much.
> 

I suppose that not allowing the banner to be dismissed, and just treating it like it's just part of the UI would solve this issue, so that's something we should at least discuss. WDYT @jvillalobos?
 
> On that topic, I remember many moons ago that an option to have aggressive caching **and** dynamic content was [edge side includes](https://www.w3.org/TR/esi-lang/). Maybe that could be an idea? I see there is a react project for ESI: [dunglas/react-esi](https://github.com/dunglas/react-esi)

This is interesting, but that project doesn't seem to be very active, nor have a lot of downloads, so I would be wary of relying on it for anything we'd run in production. The overall idea of ESI does seem worth considering, though, in the long term.

**Comment by bobsilverberg** [comment]
One more option we should at least consider, even though it's not ideal, is to allow for the possibility of hiding the promo banner client-side, if it's already been dismissed. If we do that then we can ignore the caching issue and always serve the banner on the server, and just hide it client-side.

This will, however, be ugly, and also could very well impact performance in a way that has been discussed in the past, so we probably don't want to do thus, but I figured it was worth putting out there as a possibility.

**Comment by jvillalobos** [comment]
> In the doc you say "we want to avoid showing the ad once the user has dismissed it. I would add that dismissing the ad should be permanent, even if the user dismissed it during the experiment, so we should keep the cookie for as long as possible." We can do this by setting a long expiry date for the cookie - perhaps 1 year?

Yes, I think a long expiration time is reasonable as a compromise. We'll probably need to update the ad at some point and want users to see it again.

>  Should we use the same logic for hiding the banner if a user clicks on the CTA? Do we want to hide the banner after a user clicks on the CTA, or only if they dismiss it? And if the former, do we keep it hidden "permanently" as well?

Yes, good catch.

> I suppose that not allowing the banner to be dismissed, and just treating it like it's just part of the UI would solve this issue, so that's something we should at least discuss. WDYT @jvillalobos?

I don't think users will appreciate that distinction :). We want it to be removable because we know our users are _very_ ad-adverse. That said, it's possible that the design and the fact that it's a Mozilla VPN ad may make it more acceptable. It's part of what we want to measure and figure out.

**Comment by diox** [comment]
Once we're on the CDN for the main domain, Cloudfront has a couple options to manipulate content at the edge:
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html
- https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-the-edge.html

However, I'm not sure what Google Cloud supports, we'd need a plan for when we switch to GCP.

**Comment by bobsilverberg** [comment]
> Once we're on the CDN for the main domain, Cloudfront has a couple options to manipulate content at the edge:
> 
>     * [docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-functions.html)
> 
>     * [docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-the-edge.html](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/lambda-at-the-edge.html)
> 
> 
> However, I'm not sure what Google Cloud supports, we'd need a plan for when we switch to GCP.

Taking a quick look at those, it looks like we might be able to use those to better manage the cache key (e.g., instead of using the full user agent string, we could parse it and create keys like "isFirefox", "isMobile"), but I'm not sure I see a way to use them to deliver different content outside of caching. It looks like we can redirect to different URLs, but everything would still need to be cached. It's certainly possible I'm missing a possibility in there though.

**Comment by diox** [comment]
From [CloudFront docs](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/writing-function-code.html#function-code-modify-response):
> When you modify an HTTP response with CloudFront Functions, you cannot alter or modify the response body. If you need to alter the response body, use Lambda@Edge. With Lambda@Edge, you can replace the entire response body with a new one, or remove the response body. However, you cannot modify individual properties within the response body.

So using Lambda@Edge, maybe we could update the response body to remove/add something in order to hide/completely remove the banner if the request came with a particular cookie, without forwarding that cookie to the origin/letting it be part of the cache key.

The thing that worries me is that it seems super overkill (this is something we'd need to do for every request), especially as Lambda@Edge functions are not free.

**Comment by eviljeff** [comment]
can we add a header instead? (i.e. don't touch the response body itself)

**Comment by bobsilverberg** [comment]
> can we add a header instead? (i.e. don't touch the response body itself)

I'm not sure how that's going to help us in this case. At its most basic, the problem is this:

If a user has dismissed the banner, which will be indicated by a cookie stored on their machine, we don't want the response served to them to include the banner. Ideally we do not want to hide it client-side, but rather we want to serve them a page from the server without a banner on it. If this is being served from the cache, we would need to retrieve the correct version of the page from the cache (the one without the banner). 

Unless we can do something fancy with one of those CDN functions, which does indeed sound like overkill, it seems to me that this means we need to have stored two versions of the page in the cache, one for "with banner" and one for "without banner", and then we need to ask the cache for the correct version, which comes down to having the cookie in the cache key.

An alternative, which would involve showing or hiding the banner client-side, is being discussed, but I was under the impression that we want to avoid that for performance measurement purposes - that either adding or removing a block of content on the client, immediately after loading the page, will impact our performance measures. Is that accurate @diox?

**Comment by bobsilverberg** [comment]
@jvillalobos It seems we are at a crossroads with this issue. We are discussing two alternatives:
1. We store the dismissed status in a cookie, which means we'll be able to remember it post-experiment, which was discussed as a requirement. The problem here is that it impacts caching. @diox has expressed some concerns about us doing something that impacts caching at the same time we are moving to the CDN, which increases the number of variables in play with that change. If we wish to do this the request is that we delay the experiment to happen later (i.e., not August).
2. We can use the experiment variant to keep track of the dismissed status, and this will not impact caching. The downside to this is that we won't remember the fact that someone had dismissed (or clicked on) the banner post-experiment. Perhaps this isn't that big an issue considering that we are only going to show the banner to 5% of eligible users in the experiment, so the number of people affected by us "forgetting" their status isn't that high.

What do you think?

**Comment by jvillalobos** [comment]
I prefer to stick to the current schedule, and like you said the impact is minor, so going with option 2 sounds best.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on FF, Edge and Chrome:

- when the `show-promo` cookie is present - the banner is displayed. 
- after  vpn-promo-banner-dismiss or vpn-promo-banner-click events if I navigate to other detail pages, refresh page or navigate back, I will no longer see the banner displayed. Also the status of the cookie changes to `NotInExperiment`

![banner click or dismiss](https://user-images.githubusercontent.com/33448286/128015366-81618104-1869-4bcb-811b-7be91b9b0b46.gif)


- the expiration of the cookie is set to one month
- as UX the banner text has a long line between "data" and "and", this was already there the previous weeks, I hope it's fine 
![banner](https://user-images.githubusercontent.com/33448286/128014940-4b8010d3-e820-4e72-a40b-7faf0d2357c9.png)
