### ISSUE TITLE
Serve addons-frontend static assets through the CDN on -dev

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10785]
Now that [-dev is behind the CDN](https://github.com/mozilla/addons-server/issues/17521) the next steps are deploying it to stage and prod. After that, we need to start moving everything to the main domain, under the same CDN distribution.

addons-frontend static assets are one of the things that need to be moved. 

We need to select a prefix that will only apply to those. Let's go with `/static-frontend/`. Then:

On the origin side:
- nginx needs to be configured to allow serving those statics from the origin the CDN uses, with the prefix path chosen, without redirecting (currently we push those to S3 and they are served by a different CDN distribution, `addons-amo-dev-cdn.allizom.org`)
     - Alternatively we could continue to push statics to S3 and use a different origin in the CDN configuration ? I don't know if you can mix origin types like that.
- addons-frontend needs to be configured to point to the correct static URL prefix (probably remove the domain completely since it will be the same as the one the pages are served from).

On the CDN side:
- The CDN needs to have a separate behavior for `/static-frontend/`, with a different caching policy set that doesn't care about any particular cookies or headers for the cache key.

On either side (as long as it's present in responses we serve to users):
- We need to set `control-allow-methods` to `GET, HEAD`, `access-control-allow-origin` to `*` and `cache-control` to `max-age=315360000, immutable` in the responses
- We need to ensure a `Content-Security-Policy` is set (see https://bugzilla.mozilla.org/show_bug.cgi?id=1282068) for responses to requests under that path prefix.

It's also important to note that addons-server also has static assets that we'll want to serve, and those are different. They shouldn't conflict, but to be on the safe side it's probably best to use a different path for each. So we'll use `/static-server/` for these.

**Comment by diox** [comment]
> Alternatively we could continue to push statics to S3 and use a different origin in the CDN configuration ? I don't know if you can mix origin types like that.

I experimented with this and it's working fine, so maybe that's something to explore. The only drawback is it might require us to push to a different path on S3 so that the `/static-frontend/` path matches, if we can't find a way to rewrite that part of the URL.

**Comment by bqbn** [comment]
> I experimented with this and it's working fine, so maybe that's something to explore. The only drawback is it might require us to push to a different path on S3 so that the `/static-frontend/` path matches, if we can't find a way to rewrite that part of the URL.

IIRC, Cloudfront can serve different paths with different origins. In our case, we can just add a `/static-frontend/*` path to the new CDN (like we did for `/api/*` path) and set its origin to the same origin the `addons-amo-dev-cdn.allizom.org` distribution uses (which is an s3 bucket).

As for pushing to a different path on S3, that can be easily done by changing the deployment script to push to both paths during the transition time, and after we cut over, we'll stop pushing to `/static/` path.

**Comment by diox** [comment]
Yep that's what I experimented with (I tried with /static-server/ but same idea). Pushing to both paths sound fine.

**Comment by diox** [comment]
Jira ticket for the ops side of this: https://mozilla-hub.atlassian.net/browse/SVCSE-25

We can keep this issue for our own side (modifying the code to stop pointing to the special domains)

**Comment by willdurand** [comment]
> Yep that's what I experimented with (I tried with /static-server/ but same idea). Pushing to both paths sound fine.

I am not 100% sure but it is possible that the static path is hardcoded in the client bundle and also used on the server for CSP config.

**Comment by diox** [comment]
Yes, but that's fine - we'll update the CSP as soon as we start pointing statics to the new path on the main domain.

**Comment by AlexandraMoga** [comment]
@diox what am I supposed to follow for this change?

**Comment by AlexandraMoga** [comment]
I couldn't find regressions on the frontend on -dev. I've also noticed the following:
- files served by `addons-dev.allizom.org/static-frontend/`: font files, js files, _some svg_ (placeholders from what I've noticed) - files are served from cache in subsequent visits
- files served by `addons-dev-cdn.allizom.org`: user media (images) - also served from cache after subsequent visits
