### ISSUE TITLE
Use variable utm_campaign for attribution

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#10786]
The `utm_campaign` attribution parameter couldn't be changed previously due to RTAMO validation: https://github.com/mozilla/addons-frontend/issues/10476. This has been [fixed on the Firefox side](https://bugzilla.mozilla.org/show_bug.cgi?id=1707038), so it should be safe to have variable values for `utm_campaign`, which will give us more granular reporting on the telemetry side.

We're currently using `utm_term` for that data as a workaround right now, so I think this is only a matter of sending that value using `utm_campaign` instead.

I don't know if the current funnel experiment is impacted by this change, so this might need to wait for the experiment to wrap up.

**Comment by bobsilverberg** [comment]
It looks like there is only one places where we sending the `utm_term`; from the Download Firefox button, but there are three variations of that:
1. In the banner that appears at the top of non-detail pages, where `utm_campaign` is "non-fx-button" and `utm_term` is "amo-fx-cta".
2. On the add-on detail page, where `utm_campaign` is "non-fx-button" and `utm_term` is "amo-fx-cta-{addonId}".
3. On the static add-on card on the blog, where `utm_campaign` is "non-fx-button" and `utm_term` is "amo-blog-fx-cta-{addonId}".

@jvillalobos To confirm, should we be removing `utm_term` and replacing `utm_campaign` in each of the above with what is currently in `utm_term` (i.e., "amo-fx-cta", "amo-fx-cta-{addonId}" and "amo-blog-fx-cta-{addonId}")? Note that while this will give us more granularity for `utm_campaign` it will also mean that using it as a dimension in simple reports will no longer aggregate data for all values. I recall there was an issue where a dashboard changed in the past, and I want to avoid a similar issue with this, so let's make sure this is exactly what we want.

**Comment by jvillalobos** [comment]
> To confirm, should we be removing utm_term and replacing utm_campaign in each of the above with what is currently in utm_term (i.e., "amo-fx-cta", "amo-fx-cta-{addonId}" and "amo-blog-fx-cta-{addonId}")?

Yes

> it will also mean that using it as a dimension in simple reports will no longer aggregate data for all values

I'm not sure what you mean here. Do you mean we won't be able to easily check for all "non-fx-button" grouped together? If so, I don't think that's a big problem; it just requires a slightly more complex query.

> I recall there was an issue where a dashboard changed in the past

I don't have any dashboards that rely on those values at the moment, so we should be good there.

**Comment by bobsilverberg** [comment]
> 
> > it will also mean that using it as a dimension in simple reports will no longer aggregate data for all values
> 
> I'm not sure what you mean here. Do you mean we won't be able to easily check for all "non-fx-button" grouped together? If so, I don't think that's a big problem; it just requires a slightly more complex query.

Yes, that's what I mean, and yes, it can be overcome. Just wanted to check.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- as mentioned [above](https://github.com/mozilla/addons-frontend/issues/10786#issuecomment-889838675) I could see the utm_term being replaced with utm_campaign when the banner or the download buttons are clicked on AMO dev
- from the blog https://addons-dev.allizom.org/blog/read-epub-e-books-right-in-your-browser/ (I clicked the EPUBReader), I can still see utm_campaign being used:
https://www.mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=rta:ezUzODQ3NjdFLTAwRDktNDBFOS1CNzJGLTlDQzM5RDY1NUQ2Rn0&utm_medium=referral&utm_source=addons.mozilla.org&utm_term=amo-blog-fx-cta-45281
- Rtamo flow is not broken on AMO dev
- in case I should be checking anything related to the funnel experiment please let me know

**Comment by bobsilverberg** [comment]
That sounds good, thanks @ioanarusiczki!

**Comment by ioanarusiczki** [comment]
@bobsilverberg Ok, but is the blog alright with both parameters being used ?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I filed https://github.com/mozilla/addons-frontend/issues/10858
