### ISSUE TITLE
Check support for Firefox versions over 100

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#10793]
As Firefox versions > 100 are not too far off it would be good to check if there are any issues from using Firefox versions that are >= 100 and ensure we have tests covering those areas. Feel free to add details to this bug of what those areas are, or create new bugs as needed.

Hopefully this will be a non-issue but it wouldn't hurt to be sure.

**Comment by willdurand** [comment]
There is (was?) an experiment in Nightly and we didn't hear anything from Nightly users. I think we are good here.
