### ISSUE TITLE
Remove code for the Download Funnel experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10797]
The experiment will end running this week, and there is code specific to the experiment that should be removed. It probably makes sense to wait a week or two before removing it in case something comes to light in the review of the data from the experiment that causes us to decide to run it again.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This has been disabled o while ago https://github.com/mozilla/addons-frontend/issues/10795 
Please let me know what to check for this issue.
