### ISSUE TITLE
Generate QR codes for the add-ons recommended for Android

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10799]
As part of the Mobile Add-Ons Promo project, we will need to have a QR code for each add-on that points to the add-on detail page on our mobile site. This issue is about generating those QR codes and storing them in the repo.

**Comment by willdurand** [comment]
We can use a script that would fetch the data from the prod API and store the images somewhere, which we would track in git. We can then have a CI check to make sure everything is up to date (by running the script and checking the git status)

**Comment by bobsilverberg** [comment]
> We can use a script that would fetch the data from the prod API and store the images somewhere, which we would track in git. We can then have a CI check to make sure everything is up to date (by running the script and checking the git status)

Thanks @willdurand. Are you talking about generating the images from data from the API, or just using that data to make sure we have all of the images we need?

I also just asked some questions about this on Slack, but it makes sense to move that conversation here, for durability.

I'm wondering if we should store these images in addons-server, like we do for other add-on specific images, or in addons-frontend. One thing to consider is that this is just an experiment, so we want to take the most lightweight approach at this time, as opposed to writing code that may never be needed.

**Comment by willdurand** [comment]
> Thanks @willdurand. Are you talking about generating the images from data from the API, or just using that data to make sure we have all of the images we need?

I am not so sure what we need (in terms of data encoded in the qr code) but I guess we want to generate qr codes for all recommended add-ons for Android, so I'd use the API to automatically generate them. I read we have 16 add-ons right now but that might change in the future.

> I also just asked some questions about this on Slack, but it makes sense to move that conversation here, for durability.

+1

> I'm wondering if we should store these images in addons-server, like we do for other add-on specific images, or in addons-frontend. One thing to consider is that this is just an experiment, so we want to take the most lightweight approach at this time, as opposed to writing code that may never be needed.

I think we can store them in addons-frontend. We're going to use a single CDN soon so in the future, it won't matter much where we actually store them. In the future, we might move the generation logic to addons-server to pre-generate these QR codes or create + cache them on the fly but for now, I think it will be a lot easier to have them in addons-frontend.

I have some other questions: do we know which version of QR Code (QR code has different versions with different features) we want to use? Do we care? Is the QR code going to start the install process in Fenix once scanned?

**Comment by jvillalobos** [comment]
> Do we know which version of QR Code (QR code has different versions with different features) we want to use?

I used [this tool](https://www.qr-code-generator.com/) with its default settings for testing and writing the spec.

> Do we care?

We just want to make sure it's good enough to support AMO listing URLs (like `https://addons.mozilla.org/android/addon/ublock-origin/`) and is widely supported on Android devices.

> Is the QR code going to start the install process in Fenix once scanned?

No, it should just point to the listing page.

**Comment by bobsilverberg** [comment]
@willdurand While I agree that an eventual implementation should automatically generate QR codes based on the result of a query (at the least), because this is an experiment we might want to not even bother with writing a routine to generate them. The experiment will only run for 2 weeks, and it is doubtful that the list of recommended add-ons for Android will change during that time, and even if it does, if we miss out on one it won't have a significant impact on the experiment.

Part of the philosophy behind running an experiment is to undertake the least amount of development work required to be able to deliver the temporary experience to experiment users, and then to evaluate the results to determine whether we want to actually implement the feature, at which point we would undertake a proper implementation. 

With this philosophy in mind, I think it makes more sense to just use an online tool to manually create the QR codes (each of which takes just a few minutes), download them, and store them in the repo. We can do a quick audit before running the experiment to make sure we have the correct images, and, as mentioned above, it is unlikely the list of recommended add-ons will change during the two weeks of the experiment.

@jvillalobos / @diox What are your thoughts on this?

**Comment by jvillalobos** [comment]
I'm fine with that.

**Comment by willdurand** [comment]
> @willdurand While I agree that an eventual implementation should automatically generate QR codes based on the result of a query (at the least), because this is an experiment we might want to not even bother with writing a routine to generate them. The experiment will only run for 2 weeks, and it is doubtful that the list of recommended add-ons for Android will change during that time, and even if it does, if we miss out on one it won't have a significant impact on the experiment.
> 
> Part of the philosophy behind running an experiment is to undertake the least amount of development work required to be able to deliver the temporary experience to experiment users, and then to evaluate the results to determine whether we want to actually implement the feature, at which point we would undertake a proper implementation.
> 
> With this philosophy in mind, I think it makes more sense to just use an online tool to manually create the QR codes (each of which takes just a few minutes), download them, and store them in the repo. We can do a quick audit before running the experiment to make sure we have the correct images, and, as mentioned above, it is unlikely the list of recommended add-ons will change during the two weeks of the experiment.

I disagree.

A script makes the process reproducible and we can adjust everything for all qrcodes at once if needed. For example the name of the qrcodes are the GUID right now so that it is both easy to import and unique, but that might not be what we need. Anyway here is the script I wrote in 5 minutes:

```js
const fs = require("fs");
const fetch = require("node-fetch");
const QRCode = require("qrcode");

(async () => {
  const res = await fetch(
    `https://addons.mozilla.org/api/v5/addons/search/?app=android&promoted=recommended&type=extension&lang=en-US`
  );
  const { results: addons } = await res.json();

  await Promise.all(
    addons.map(({ guid, url }) => {
      return QRCode.toFile(`${guid}.png`, url);
    })
  );
})();
```

Here are the QR codes:

[qrcodes.zip](https://github.com/mozilla/addons-frontend/files/6903309/qrcodes.zip)

**Comment by willdurand** [comment]
Based on this script, we could update the URLs if we want locale-less URLs (which, I think, would be a good idea), it is faster and less error-prone than doing it manually.

**Comment by bobsilverberg** [comment]
> Based on this script, we could update the URLs if we want locale-less URLs (which, I think, would be a good idea), and the script makes the process faster and less error-prone than by doing it manually.

Fair enough. I was thinking also about the time it would take to write tests for it, but I guess if it's just a script we're going to run manually then it doesn't necessarily need tests? Although anything we plan on landing in the repo should probably have some tests, which is my concern.

**Comment by willdurand** [comment]
> Although anything we plan on landing in the repo should probably have some tests, which is my concern.

I don't think this script needs tests. We can make sure to run it on Circle CI maybe in case it breaks in the future but it isn't very complicated (even with the change to generate locale-less URLs).
