### ISSUE TITLE
Add autocomplete to search component

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1079]
#798 includes an autocomplete in the search page, which we will need to add to it.

The current AMO has autocomplete but the autocompete results seem different to the actual search results.

I'd like a consistent search experience so I want the results to be the same as the add-ons search in terms of order/etc. But hammering the search API `onChange` and getting all that data back is likely overkill, so we may need to add a param to the search API for autocomplete.

**Comment by tofumatt** [comment]
Ohai, @willdurand did this already for #2971. This is basically a duplicate of #2747.

**Comment by willdurand** [comment]
Haha looks like I can close issues even when I am off
 ☺️
