### ISSUE TITLE
Implement an AddonQRCode component 

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10800]
For the Mobile Add-Ons Promo project, we need a box that appears that contains a QR code, as well as some text that explains what the user is seeing. According to https://docs.google.com/document/d/1upD3G06aJFZg4XjhIeQ-MKo494ny-7geOu3YPyxXH3Q/edit, the code should appear in a black frame, and should have the following text underneath it:

"To get {addonName} on Firefox for Android, point your device camera to the code above or copy this link"

Sample image:

<img width="639" alt="Screen Shot 2021-07-27 at 2 37 41 PM" src="https://user-images.githubusercontent.com/142755/127209432-bb20e166-1c20-4098-90fa-aa9581a93184.png">

**Comment by willdurand** [comment]
@bobsilverberg We have the [`OverlayCard` component](https://github.com/mozilla/addons-frontend/blob/4fbf4b1424360f739290555f05325b3673ab8052/src/amo/components/OverlayCard/index.js#L10) for what you're calling "modal pop-up". For a QR code, it might be a bit easier for apps to scan the code with an overlay that greys out the rest of the page.

**Comment by bobsilverberg** [comment]
> @bobsilverberg We have the [`OverlayCard` component](https://github.com/mozilla/addons-frontend/blob/4fbf4b1424360f739290555f05325b3673ab8052/src/amo/components/OverlayCard/index.js#L10) for what you're calling "modal pop-up". For a QR code, it might be a bit easier for apps to scan the code with an overlay that greys out the rest of the page.

Thanks @willdurand. I forgot about that component. I'm still not a huge fan of the "fake modal", but I guess we can implement it that way if that's what's in the spec.

**Comment by muffinresearch** [comment]
@bobsilverberg  For UX input you could reach out to @designakt to see what's possible there.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I checked on -dev the [fenix ](https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/5497603/change/?_changelist_filters=author%3D10641574) collection. There are lots of addons which are recommended on both platforms so I was thinking I'll see the URL described above under the blue button with FF or another browser. 

I downloaded a QRCode app, scanning the code from https://github.com/mozilla/addons-frontend/pull/10904 I am redirected to HTTPS Everywhere from prod.  

Pls let me know how to test this.

**Comment by ioanarusiczki** [comment]
@bobsilverberg To add: I tried with these pages:
https://addons-dev.allizom.org/en-US/firefox/addon/bubbles-for-mozilla-appr/
https://addons.allizom.org/en-US/firefox/addon/youtube-high-definition/
https://addons-dev.allizom.org/en-US/firefox/addon/not-promoted/ 

None has "Also available on Firefox for Android"

**Comment by willdurand** [comment]
@ioanarusiczki unfortunately, there is nothing visible yet: this issue is about adding a new UI component but it isn't used right now. It will be used in #10905

**Comment by ioanarusiczki** [comment]
@willdurand Ok, thanks!

**Comment by bobsilverberg** [comment]
Yes, my apologies for not updating this issue. I will mark it as qa: not needed and all of it can be tested after the next patch lands which makes it visible.
