### ISSUE TITLE
Move withExperiment from VPNPromoBanner to Page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10802]
Because the `VPNPromoBanner` does not get rendered on the server until the second component render, having `withExperiment` in it is a problem as the `variant` used on the server is not stored and therefore not available to be read on the client. This can result in a page being served by the server that is not the same as the one that is later rendered on the client. This was difficult to observe due to the fact that 90% of the time the variant is calculated as `notInExperiment`, which means that it is less likely that a different variation would be used on the server than on the client.

Moving `withExperiment` up a level, to `Page` fixes this problem. 

This is something I noticed when debugging for https://github.com/mozilla/addons-frontend/issues/10794, but I don't believe it is the source of that problem as it doesn't fit in with the behaviour described.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I did not encounter issues if I compare with the results from https://github.com/mozilla/addons-frontend/issues/10774
The only change is described already into https://github.com/mozilla/addons-frontend/issues/10770#issuecomment-891808399

I verified it on AMO dev with Chrome, Edge and FF90
