### ISSUE TITLE
In `withExperiment`, do not call `experimentSetup()` in `render()`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10811]
Given that `experimentSetup()` can dispatch actions, we should not call it in `render()`. This can break the app and it actually breaks the addons-server local dev env.

**Comment by ioanarusiczki** [comment]
@willdurand Should be good. Same results as for https://github.com/mozilla/addons-frontend/issues/10802#issuecomment-891821780

To add: every time I delete the cookie and refresh the page on AMO - the enrollment event for the promo-experiment is registered by the Console, on any AMO page, it doesn't have to be an extension detail page. 
I've encountered the `hide-promo` in US, FR or DE regions while testing.  

I verified this with Chrome, FF90.

**Comment by willdurand** [comment]
> To add: every time I delete the cookie and refresh the page on AMO - the enrollment event for the promo-experiment is registered by the Console, on any AMO page, it doesn't have to be an extension detail page.

I think this is expected yeah
