### ISSUE TITLE
Reviewer links on listing page should use the AMO ID instead of slug

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#10826]
### Describe the problem and steps to reproduce it:

The listing page includes links to reviewer tools (if you have permission).

### What happened?

The links use the add-on slug.

### What did you expect to happen?

The links use the AMO ID.

### Anything else we should know?

The AMO ID became the canonical identifier in https://github.com/mozilla/addons-server/commit/8c81b12efe5181b233ddacb4442c6f7ac9d95256. This update here saves us a redirect.

**Comment by AlexandraMoga** [comment]
The links to reviewer tools - Review add-on code, Content review add-on and Review theme - from the add-on detail page are now using the add-on internal ID instead of the slug.

This issue is verified fixed on -dev.
