### ISSUE TITLE
500 server errors on lang pack and dictionary detail pages 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10829]
Currently on AMO dev only - the detail pages for lang packs and dicts return a 500

![500lang packs](https://user-images.githubusercontent.com/33448286/128855745-fc28f859-e6c8-4e40-a9ae-a6c577946a33.gif)

Not reproducible with extensions or themes

**Comment by wagnerand** [comment]
`Caught application error: Error: "dictionary" not found in VISIBLE_ADDON_TYPES_MAPPING`

**Comment by willdurand** [comment]
heh, sorry I forgot to check langpacks/dicts.

**Comment by ioanarusiczki** [comment]
@willdurand Pages are displayed on AMO dev and AMO stage

Verified wit FF90(Win10).
