### ISSUE TITLE
pass on ratings and users search filters to api/v5/addons/search

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10835]
After mozilla/addons-server#17497 added the ability to have addon search queries filtered by ratings and users - and allowed greater than and less than thresholds- it's likely that tag shelves will limit the results using those parameters and possible the subsequent query may also want to limit the results by users or ratings in the same way.  Currently the search pages (e.g.https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gte=3&users__gt=500&tag=content%20blocker) don't pass on the (unknown to frontend) parameters to the api though.  We probably don't need UI to control the parameters (at least not initially) but we should pass them on.

https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-threshold-param details the possible variants of `ratings` and `users` parameters there might be.

**Comment by ioanarusiczki** [comment]
@eviljeff 
- I checked the URLs mentioned into https://github.com/mozilla/addons-server/issues/17497 and the new parameters are passed in all cases except for 
https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gt=3.5&users__gt=500&tag=antivirus 
If I click the above URL it will redirect to https://addons-dev.allizom.org/en-US/firefox/tag/antivirus/  without passing the rating and users params. I could not reproduce this with other tags. 

- When clicking the See more link from the homepage -> I get to see the URL in the following format:
https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gte=3&users__gt=500&tag=word%20counter 
Only after refreshing the page - I'll get the same content but the URL is:
https://addons-dev.allizom.org/en-US/firefox/tag/word%20counter/?ratings__gte=3&users__gt=500

![with refresh](https://user-images.githubusercontent.com/33448286/129361486-e5d8af31-5555-4826-a6f3-fc9e0b845621.gif)

**Comment by eviljeff** [comment]
>     * I checked the URLs mentioned into [limit the results for a (tag) shelf to minimum thresholds addons-server#17497](https://github.com/mozilla/addons-server/issues/17497) and the new parameters are passed in all cases except for
>       https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gt=3.5&users__gt=500&tag=antivirus
>       If I click the above URL it will redirect to https://addons-dev.allizom.org/en-US/firefox/tag/antivirus/  without passing the rating and users params. I could not reproduce this with other tags.

it passes them for me, so might just be a cached?

>     * When clicking the See more link from the homepage -> I get to see the URL in the following format:
>       https://addons-dev.allizom.org/en-US/firefox/search/?ratings__gte=3&users__gt=500&tag=word%20counter
>       Only after refreshing the page - I'll get the same content but the URL is:
>       https://addons-dev.allizom.org/en-US/firefox/tag/word%20counter/?ratings__gte=3&users__gt=500

Either link is fine really, but ideally the api should be returning the canonical url for tags, rather than search, now tag pages exist (they didn't at the time).  Could you log an issue on addons-server?

**Comment by AlexandraMoga** [comment]
> it passes them for me, so might just be a cached?

the URL parameters are passed for me as well



> Either link is fine really, but ideally the api should be returning the canonical url for tags, rather than search, now tag pages exist (they didn't at the time). Could you log an issue on addons-server?

Filed https://github.com/mozilla/addons-server/issues/17712
