### ISSUE TITLE
Set meta=robots (noindex, follow) to search pages with 0 results

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10831]
### Describe the problem and steps to reproduce it:

1. Load a search page (or category page) with no results

### What happened?

This page will be indexed by search engines.

### What did you expect to happen?

This page should NOT be indexed.

### Anything else we should know?

We should render a `<meta="robots" content="noindex, follow">`.

**Comment by willdurand** [comment]
In addition to being useful, this issue supports https://github.com/mozilla/addons-frontend/issues/10789

**Comment by AlexandraMoga** [comment]
Search pages with no matching results have the following property now:
`<meta data-react-helmet="true" name="robots" content="noindex, follow"/>`

Search pages with results do not have this property. 

This issue is verified fixed on -dev.
