### ISSUE TITLE
Remove `enableFeatureBlockPage` flag

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10836]
We enabled the block page feature in all envs a year ago: https://github.com/mozilla/addons-frontend/issues/9451, let's remove the feature flag now.

For QA: block pages should still be available.

**Comment by ioanarusiczki** [comment]
@willdurand I can see block pages on -dev
An example: https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B6f005954-f0ac-415d-84e5-f30090e7640e%7D/
or https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B2e47731c-5807-4310-b6dd-81e0f2d34681%7D/

![block-pages](https://user-images.githubusercontent.com/33448286/129340144-f7a8d200-695b-49d8-8172-2bf42fa8d6c0.png)
