### ISSUE TITLE
Remove `enableFeatureAllowAndroidInstall` flag

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#10838]
We enabled this feature in all envs a while ago: https://github.com/mozilla/addons-frontend/issues/9878, let's remove the feature flag now.

For QA: (recommended) add-ons should be installable on Android (as before).

**Comment by AlexandraMoga** [comment]
I've created a custom Fenix debug build for AMO -dev and I was able to install Recommended addons from AMO and from the Fenix built in Add-ons section.

This issue is verified fixed on -dev.
