### ISSUE TITLE
`<link>` for font preload should come before the CSS

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10867]
Chrome is going to change the way it deals with `<link rel=preload>` - https://chromium-review.googlesource.com/c/chromium/src/+/3122306

Previously, just having a `<link rel=preload>` would ensure that resource would be loaded first, potentially jumping ahead of other resources not explicitly marked as needing preloading. Now it won't do that anymore, but still obey the order in which things are declared.

We have a `font-display: block` on the preloaded font, and that ensures there is no flash of text, but there could still be a layout shift if the font is not ready when the browser does its first layout - it might make layout computations with a fallback font anyway, causing a layout shift later when the font is available.

To avoid this, we should put the preloaded font before the CSS in the HTML, or consider doing the preload in HTTP headers in the responses.

**Comment by karthiknadar1204** [comment]
If ths issue is still open,please assign it to me

**Comment by GregSherman** [comment]
@diox Requesting assignment of this issue

**Comment by AlexandraMoga** [comment]
I had a look on the frontend in Firefox, Chrome and Edge and didn't notice any issues with fonts or css loading.

I'm marking this issue as verified fixed on -dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-15
