### ISSUE TITLE
Show that an addon cannot be uninstalled

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1086]
https://bugzilla.mozilla.org/show_bug.cgi?id=1297028 has added a hint to tell that an addon cannot be uninstalled.

We need to add support for this and show a disabled state for installed to show in the UI  that the add-on cannot be uninstalled.

**Comment by muffinresearch** [comment]
Relates to #959

**Comment by willdurand** [comment]
marking this issue as duplicate of https://github.com/mozilla/addons-frontend/issues/8418
