### ISSUE TITLE
Serve addons-frontend static assets through the CDN on -stage and prod

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#10870]
When we're ready to deploy the first batch of CDN changes to production, we need to start using the same domain to load addons-frontend static assets.

This was already done for dev in #10785, this is about stage and prod.

**Comment by diox** [comment]
It might be more prudent to deploy the CDN first, and then do this. That way if a request ends up not being served by the CDN because the client has the old IP for instance, it will still work correctly. Once we're completely sure everyone is being served by CloudFront we can switch.

**Comment by AlexandraMoga** [comment]
As for the case of #10785, I've checked that fronted pages on stage function as before. I've also verified that static files are served as follows:

- files served by `addons.allizom.org/static-frontend/`: font files, js files, some svg- files are served from cache in subsequent visits
- files served by `addons-stage-cdn.allizom.org`: user media (images) - also served from cache after subsequent visits
