### ISSUE TITLE
Use constants for all redux action types

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1087]
Now that we have [import linting](https://github.com/mozilla/addons-frontend/issues/931) we should switch all redux action types from strings to constants. This will allow the linter to catch any cases where an invalid action type is used (due to a typo or refactoring, etc).

For example, instead of:
````javascript
export function discoResults(results) {
  return {
    type: 'DISCO_RESULTS',
    payload: {
      results,
    },
  };
}
````

let's do:
````javascript
import { DISCO_RESULTS } from '../somewhere/actionTypes';
export function discoResults(results) {
  return {
    type: DISCO_RESULTS,
    payload: {
      results,
    },
  };
}
````

**Comment by bjdixon** [comment]
/src/(disco|amo|core)/ each has a constants.js file. Would that be an appropriate location for their actions constants?

**Comment by kumar303** [comment]
yep, I think using each local constants.js file would be fine. If there isn't an existing one, you can create it.
