### ISSUE TITLE
Indicate that a user has already rated an add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1088]
In https://github.com/mozilla/addons-frontend/issues/1017 the UI was implemented to present the smileys that a user can select to give their overall rating of an add-on. If the user returns to this page after rating the add-on, they cannot re-rate the add-on. How do we visually indicate that they have already taken this action?

UX flow tracker: #927
This supports mozilla/addons#151

**Comment by kumar303** [comment]
@pwalm let me know your thoughts on this. I see that [an older revision](https://github.com/mozilla/addons-frontend/issues/800#issuecomment-238436613) had some grey smileys. Maybe we can use an approach like that?

**Comment by kumar303** [comment]
Actually, now that we have star ratings (https://github.com/mozilla/addons-frontend/issues/1288) the UX for this will be super easy. It will just look like a selected star range.

**Comment by pwalm** [comment]
Need anything else on this issue from me, @kumar303?

**Comment by kumar303** [comment]
Nope, we're good. I realized that the selected star view is in the Sketch mock.

**Comment by ValentinaPC** [comment]
Verified as fixed on FF51(Android 6.0.1)
After an add-on is rated, second time the user goes to add-on details page, a selected star range can be seen.
Postfix screenshot: 
![screenshot_20170206-160718](https://cloud.githubusercontent.com/assets/15685960/22650237/eda98406-ec86-11e6-830c-7cd7c0d3f865.png)
