### ISSUE TITLE
Login errors from "Login to create a collection button"

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10887]
The user is not authenticated.
STR:
1. From an addon detail page go to Select a Collection - Create a new collection 
2. Click on Log in to create a collection
3. Enter credentials

Expected result:
The login is successful 

Actual result: 
No login - usermenu is not present

Notes:
I could not reproduce it on AMO prod.
It's reproducible on AMO dev and AMO stage - on AMO dev after step 3 - I get a broken layout of the page.
On AMO stage I can login the second time without problems:

![issue](https://user-images.githubusercontent.com/33448286/132705477-cee1065c-094a-4d08-89a0-a3bbdce474be.gif)

**Comment by AlexandraMoga** [comment]
Similar to this issue where I've provided more details - https://github.com/mozilla/addons-frontend/issues/10879

**Comment by diox** [comment]
Yeah, the redirection to the mozaws.net domain is the culprit here.

**Comment by diox** [comment]
This particular redirection seems to be handled by nginx. Looking more closely, all the redirections & rewrites handled by nginx are using the wrong hostname.

Another trivial one to check:
```
% curl -sI https://addons-dev.allizom.org/en-US/firefox/bookmarks/
```

This should 301 to https://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/ but it redirects to https://amo.dev.mozaws.net/en-US/firefox/extensions/bookmarks/ instead.

**Comment by bqbn** [comment]
I filed https://github.com/mozilla-services/cloudops-deployment/pull/4309/commits/295efd94ceac736dbe5e0928eb45744559d30ae4 and it seems to have fixed the redirection problem.

```
$ curl -sI https://addons-dev.allizom.org/en-US/firefox/bookmarks/
HTTP/2 301
content-type: text/html
content-length: 162
location: https://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/
content-security-policy: default-src 'none'; base-uri 'none'; form-action 'none'; frame-ancestors 'none'; object-src 'none'; report-uri /__cspreport__
date: Thu, 09 Sep 2021 18:22:56 GMT
server: nginx
x-cache: Miss from cloudfront
via: 1.1 a4fe306096165bb1e86e69365dc8fac2.cloudfront.net (CloudFront)
x-amz-cf-pop: HIO50-C1
x-amz-cf-id: AdKyIpQslYraCdoW9owQDpzjSB30-GGwXoJUtn4-2jgD2l4NIgajNg==
```

**Comment by ioanarusiczki** [comment]
@diox I tested on both -dev and -stage and I could not reproduce the issue now.
