### ISSUE TITLE
Pass the id of the add-on from the VPN Promo

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10888]
The current implementation of the VPN Promo passes only the `source`, `medium` and `campaign` as utm parameters, with the latter being used to uniquely identify referrals from this promotion. It could be valuable to also pass the add-on's id in `content`, which would allow us to identify if particular add-ons were generating more clicks on the promo banner.

@muffinresearch @tublitzed Do you think this is something we should do?

**Comment by bobsilverberg** [comment]
From a technical perspective, we actually only have access to `slug` directly in this component, via the URL. I know that `slug` can change, but perhaps for the purposes of this experiment it's okay to use that as an identifier? If not, we can look up the `addonId` in the Redux store using the `slug`, but I'm not sure if that's necessary.

What are your thoughts @willdurand @diox?

**Comment by bobsilverberg** [comment]
After taking a look at the code, it's not particularly difficult to get the id from the Redux store, but we probably want to deal with a case where the add-on isn't loaded. That should never happen as the promo only appears on add-on detail pages, but we should still address the possibility. I'm going to use the `addonId` if we can find it in the store, and if we cannot, I'll use the `slug`.

**Comment by willdurand** [comment]
> It could be valuable to also pass the add-on's id in `content`, which would allow us to identify if particular add-ons were generating more clicks on the promo banner.

Why exactly would that be useful? Is there any specific existing question that would get answered by this? I haven't read anything about that in the [specs](https://docs.google.com/document/d/15cKIk5AwBPLShwWnj_eFWCJ1cXOkOY7dXoECU5zOsfA/edit#).

**Comment by bobsilverberg** [comment]
The question that would be answered by this is, as mentioned above "are there particular add-ons that generate more clicks on the promo banner?". 😉 

This could also be stated as "are there particular types, or categories, of add-ons that generate more clicks?" Part of the goal of the experiment is to provide data that can be used to determine how best to implement this promo on an ongoing basis, if we deem the experiment successful. Understanding how users behave differently with respect to the promo, based on which add-on they are viewing, could be quite useful in making that determination. For example, we might choose to only show the promo on certain pages where we think it is likely to generate traffic, as opposed to all pages.

It seems unwise to me to *not* collect this data and then later regret that we don't have it.

**Comment by bobsilverberg** [comment]
I was hoping for some confirmation from @tublitzed or @muffinresearch about whether we should do this, as we don't currently have a product person, but I think it's fine to move forward with this in any case. I have taken full responsibility for this experiment, including analyzing the results, coming up with conclusions, and recommending next steps. This is data I would like to have to help with that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I've noticed the presence of addon ID set for utm_content param. - verified on AMO stage - FF92(Win10).

Examples:
?utm_campaign=amo-vpn-promo&utm_content=1004961&utm_medium=referral&utm_source=addons.mozilla.org
?utm_campaign=amo-vpn-promo&utm_content=619569&utm_medium=referral&utm_source=addons.mozilla.org
