### ISSUE TITLE
Server error when navigating back and forth between collections

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#10886]
Steps to reproduce:
1. Log in AMO prod with valid credentials 
2. Create 2 collections containing some addons
3. View both collections and eventually sort the collections inside by another criteria(ie. name, pupularity)
4. Navigate back and forth many times between pages previously accessed

Expected results:
No errors should be displayed when navigating back and forth

Actual results:
Server error displayed on https://addons.mozilla.org/en-US/firefox/collections/

Please see a screenshot with the encountered error in console: 
![collectionsnavigation](https://user-images.githubusercontent.com/1583842/132693418-4cf94e50-f6ff-45db-aac0-194764c34872.png)

**Comment by bobsilverberg** [comment]
@vcarciu I cannot seem to reproduce this error. What are the exact steps? I.e., exactly which screens are you navigating back and forth between? I tried going to "My Collections", viewing a collection, changing the sort, going back to "My Collections", vieiwing a different collection, changing the sort, and then using the back and forward buttons to navigate between those pages, several times, and never saw any errors.

What steps can I take to reproduce this issue?

**Comment by vcarciu** [comment]
Hey @bobsilverberg : 
You performed the exact steps to reproduce this issue, but when you navigate back and forth(two times back and two times forward multiple times) please try to do this as fast as you can. Unfortunately this is the sequence and I don't have more specific steps, but I recorded a video and I hope that this will help : 
https://www.screencast.com/t/NZcXwV886Dh

**Comment by bobsilverberg** [comment]
I still cannot reproduce it. 😢 

Looking at the video above, it seems like the error is on a different page than the original description. IIUC, the original report said that the error was on addons.mozilla.org/en-US/firefox/collections, which is the "My Collections" page, but looking at the video above, it looks like the error happens immediately after clicking the back button, *after* you have changed the sort sequence. If you click the back button after changing the sort sequence, it would take you back to the details for that collection, with the default sort sequence, not to the My Collections page. Can you please confirm at exactly what point the error occurs?

**Comment by bobsilverberg** [comment]
Nevermind, I finally reproduced it. I guess in the video you were clicking the back button twice in rapid succession.

**Comment by vcarciu** [comment]
> 
> 
> Nevermind, I finally reproduced it. I guess in the video you were clicking the back button twice in rapid succession.

Yes, I pressed the back button twice in rapid succession. Sorry if this was not very clear from video.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on -dev and this is no longer reproducible - FF92(Win10).
I could reproduce it 5/5 on stage like this: went to a collection and changed the sorting option then double clicked fast on the back button. 

Before:
![before](https://user-images.githubusercontent.com/33448286/133240816-f09e6f3b-77ef-43e8-8f98-699f69d729b7.gif)

After: 
![after](https://user-images.githubusercontent.com/33448286/133240843-9a7c6cb7-13f5-4857-ba8b-3a1b91e88cd7.gif)
