### ISSUE TITLE
Enable the VPN Promotion experiment on prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10883]
We are ready to enable this experiment, pending confirmation that the copy has not changed, and also pending a decision about whether to send information about the add-on being viewed via a utm parameter.

This issue is about enabling the experiment on production.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I'll be waiting for this to be present on -stage tomorrow.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I verified this issue on AMO stage - FF92(Win10):

The experiment is present on -stage. I used the -dev results as a guide from the issues below:
https://github.com/mozilla/addons-frontend/issues/10774
https://github.com/mozilla/addons-frontend/issues/10772
https://github.com/mozilla/addons-frontend/issues/10770
