### ISSUE TITLE
support addon.version.file (rather than .files) in API

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10900]
Once mozilla/addons-server#17913 is deployed on prod we should update to access `file` on the version detail response, rather than `files`.

To be doubly safe, the patch for this should be deployed in a subsequent week to mozilla/addons-server#17913

**Comment by willdurand** [comment]
For the future AMO team, it was possible to consider `file` as a required/always valid field on a `version` because of the work mentioned in these comments: https://github.com/mozilla/addons-frontend/pull/10903#discussion_r711993097

**Comment by ioanarusiczki** [comment]
@eviljeff I don't see issues with detail pages not loading or the versions page on frontend. 
Checking the search API from the network when a detail page loads - the `file` attribute is present with `files` - expected for now. 

Let me know if there's anything else I should be checking.
