### ISSUE TITLE
using a numeric addon id in the /versions/ urls is broken

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10916]
A url such as
https://addons.mozilla.org/en-GB/firefox/addon/521900/ works - it redirects to normative slug based url https://addons.mozilla.org/en-GB/firefox/addon/cliqz/ - but the versions page, e.g. https://addons.mozilla.org/en-GB/firefox/addon/521900/versions/ results in a forever loading page with continual re-flows making stuff jump around.

**Comment by bobsilverberg** [comment]
As discussed on Matrix, this is pretty low priority as very few users would land on the /versions page using an addonId, as opposed to a slug. We should investigate, and fix this, but it isn't urgent.

**Comment by AlexandraMoga** [comment]
The same goes when trying to access the versions page with the add-on guid - https://addons.allizom.org/en-US/firefox/addon/%7B4620cfa6-8d87-4d7f-8b7b-db792f7a9149%7D/versions/.

If this issue is going to be fixed at some point, we might as well fix it for both variants.
