### ISSUE TITLE
Could not install Search by Image and some intermittent issues with Privacy Badger

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#10920]
I checked AMO prod addons today as a followup for https://github.com/mozilla/addons-frontend/issues/10912

1. Search by Image - every time throws "Addon is not supported" - checked on two Android devices and reproduced the problem every time. The addon manager install is working. 

2. The problem described https://github.com/mozilla/addons-frontend/issues/10912#issuecomment-924881156 occurs in an intermittent way with Privacy Badger and Ghostery (I could reproduce it more often with Privacy Badger)

Instead of an install - the download is triggered. I could reproduce it the second time after an install attempt just by navigating back on the addon detail page.  After the download was triggered if I refreshed the page - the correct install behavior occurs. 

P.S> uBlock seems to be fine and the rest of the addons but I'm going to investigate on Monday again around them.

![Search by image](https://user-images.githubusercontent.com/33448286/134688371-129c5e7c-f279-446e-86d8-9f26fb65dca3.png)

![Ghostery](https://user-images.githubusercontent.com/33448286/134688403-a14cb006-a76d-4cdf-b49f-99d56b60ee64.png)

![Privacy](https://user-images.githubusercontent.com/33448286/134688423-c9332521-30b0-4373-8dfc-e8502b60f15f.png)

**Comment by willdurand** [comment]
"Add-on is not supported" sounds like a different issue to me. Maybe this was added lately and the cache wasn't updated?

**Comment by willdurand** [comment]
I cannot reproduce on my main Android phone right now.

**Comment by ioanarusiczki** [comment]
@willdurand Yesterday - Search by image install worked. 
Then the download issue - I could only reproduce it randomly with Search by Image addon.  - I saw that the URL contained /firefox/ instead of /android/
So I don't have steps when it occurs, it is intermittent and  I could not reproduce it with the other two addons, Ghostery or Privacy Badger.

**Comment by ioanarusiczki** [comment]
@diox I tried for a while but I remember that I could not reproduce it so I'll close it.
