### ISSUE TITLE
Upgrade webpack-dev-middleware

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1092]
This upgrade broke the webpack dev server (asset bundle is a 404): https://github.com/mozilla/addons-frontend/commit/888576dbdadc60d243e8927226a5d591a3b92e3c

Let's fix it an re-apply the upgrade. In the meantime I reverted it in https://github.com/mozilla/addons-frontend/commit/b92e868f4fc02f6292295e1b8491a126be2362fa

Example of the breakage from hitting the server started by `npm run dev:amo`:

![screenshot 2016-09-20 11 13 58](https://cloud.githubusercontent.com/assets/55398/18679251/64bd8f5e-7f24-11e6-9f0e-2195227b8df4.png)

If it's not too difficult, maybe we can add a test to catch this in the future too?

**Comment by tofumatt** [comment]
Oh, shoot, I assumed the tests would catch that, I'm probably to blame, sorry 😢 

Good call.

**Comment by kumar303** [comment]
Oh, no biggie, I don't manually test every greenkeeper upgrade either :) I only noticed it because push duty made me stash all my changes and I needed to get rolling again.
