### ISSUE TITLE
Disable the VPN Promo Experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10928]
Our intention was to run this experiment for two weeks, and it looks like we have collected enough data to make a decision, so let's disable it as of this week's push.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified this on AMO dev and AMO stage with:
- with a new profile on FF - I don't see a frontend_active_experiments cookie generated in Storage/cookies.
- old profiles with the cookie set on FF or Edge - display frontend_active_experiments with a value set to `%7B%7D`. Connecting to France (for example) using a VPN , I see the same result. Also the promo which used to be displayed on the addon detail pages is not present. 

![disabled experiment](https://user-images.githubusercontent.com/33448286/135246601-00b081ca-bd7b-499c-8f51-6908b1f5c06c.png)
