### ISSUE TITLE
add/adjust utm parameters for tag shelf

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10939]
We currently don't include any particular utm parameters for an add-on displayed in the tag shelf, so it's just sent through as `featured`.  Ideally we'd want to know the click came from the tag shelf to know if it's driving engagement, and the tag too.

@bobsilverberg does changing the `utm_content` seem useful?  Or keep it as is and append the tag?  

(one potential complication is frontend doesn't know what tag it's displaying - it's all rendered on server.  Should we append something in the server response instead?)

**Comment by bobsilverberg** [comment]
I agree it would be nice to be able to measure the engagement of the tag shelf, and would be useful to even know which tag it was for, but...

Those utm params that we put on those links are not actually doing anything. They are internal links, and the code we have to send pageviews to GA doesn't include anything other than the path to the page. This is something we discovered back when we were looking into the issue of having utm params on internal links. I am pretty sure this has always been the case, and I guess nobody noticed? I could be wrong about this, and maybe @willdurand knows of a way in which those utm params are used, but it seems to me that we should either remove them, or change our logic to capture them. The problem with the latter is that it introduces the problem of having utm params on internal links, which can cause issues with GA sessions.

**Comment by willdurand** [comment]
> The problem with the latter is that it introduces the problem of having utm params on internal links, which can cause issues with GA sessions.

Yeah, exactly. We cannot have UTM params on internal links and it is a good thing that they are ignored. I think we didn't remove them yet because it is simpler to have them in all cases (as opposed to only include them for non-internal links).

**Comment by eviljeff** [comment]
So, is there anything to be done here?  It _would_ be nice to know what effect the tag shelf is having, and we used to be able to tell if the source of an add-on install was from a collection, or from the homepage, etc (not sure if that's still a thing with the statistics pipeline changes over the years)

**Comment by willdurand** [comment]
> we used to be able to tell if the source of an add-on install was from a collection, or from the homepage, etc (not sure if that's still a thing with the statistics pipeline changes over the years)

This is still possible, with UTM params.

**Comment by bobsilverberg** [comment]
> > we used to be able to tell if the source of an add-on install was from a collection, or from the homepage, etc (not sure if that's still a thing with the statistics pipeline changes over the years)
> 
> This is still possible, with UTM params.

Ah, right, I knew there was something I was missing. This information is written to telemetry, correct? So it's not available in GA (which is where we'd usually analyze things like this), but it is available in redash? If that's the case, and we think we want to be able to report on it from there, then I guess it does make sense to change the `utm_content` for the tag shelf to use a unique value, and to include the name of the tag, if possible.

**Comment by willdurand** [comment]
> This information is written to telemetry, correct?

Yes.

> So it's not available in GA (which is where we'd usually analyze things like this), but it is available in redash?

Yes.

> it does make sense to change the utm_content for the tag shelf to use a unique value, and to include the name of the tag, if possible

Yes.

**Comment by AlexandraMoga** [comment]
Addons opened from the Homepage tag shelves will have the `utm_content=tag-shelf-{tag_name}` utm parameter, as seen in the example below:

![image](https://user-images.githubusercontent.com/31961530/140052024-a6c69795-8141-4479-a5b4-7b8abc80f99c.png)
![image](https://user-images.githubusercontent.com/31961530/140052063-d394e71f-4442-4cf9-8bf7-ce5f610102c0.png)

The utm parameters are preserved during client side navigation until another instance overrides the existing one. For example, if the user reaches a search result page, after having started on the tag shelf, and then opening an addon from the search results page, the utm content parameter will change to `utm_content=search`.
This applies to other utms as well, so it is not specific to tags.
