### ISSUE TITLE
Make redux actions hot reloadable again

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1096]
### Describe the problem and steps to reproduce it:

Run a dev server with the react hot reloader enabled. Example:

```
npm run dev:amo
```

Change the code in any action creator.
### What happened?

The old code is still running.
### What did you expect to happen?

The hot reloader should automatically reload the action code so that you don't have to refresh the entire page and potentially lose your state.
### Anything else we should know?

It looks like this was a regression in some upstream module but there are a couple different issues. See:
- https://github.com/reactjs/redux/issues/782
- https://github.com/gaearon/babel-plugin-react-transform/issues/26

React Hot Loader 3.0 should fix this. Preview: https://github.com/gaearon/react-hot-boilerplate/pull/61

**Comment by willdurand** [comment]
Here is a patch for that: https://github.com/mozilla/addons-frontend/commit/b5f49aae9eeb05622ab5923e12e84eb42791f462

See also this (minor) issue: https://github.com/mozilla/addons-frontend/pull/5652#discussion_r205609278

**Comment by AlexandraMoga** [comment]
Please add STR or the label 'qa:not needed'
Thanks
