### ISSUE TITLE
AMO page UI elements are invisible when high contrast options are enabled

### ISSUE THREAD

**Issue by acornestean** [mozilla/addons-frontend#10962]
Description:
Several AMO UI elements become invisible when “Override the colors specified by the page with your selections above” is set to “Always” in about:preferences.
Such UI elements include:
- “Firefox Browser Add-ons” title (next to the Firefox icon in the page header)
- Rating bars (for both extensions and themes)
- Badges (for both extensions and themes)

Steps to reproduce:
1. Go to about:preferences and under the “Fonts and Colors” section, access the “Colors...” option and set “Override the colors specified by the page with your selections above” to “Always”.
2. Go to https://addons.mozilla.org/en-US/firefox/.
3. Notice the “Firefox Browser Add-ons” title is invisible in the page header.
4. Access the details page of any add-on or theme (preferably “Recommended”, so they have a badge).
5. Notice the “Rating bars” and CSS badge styling are invisible
6. Access https://addons.mozilla.org/en-US/firefox/search/?promoted=recommended&sort=random&type=extension (list of recommended extensions).
7. Notice the extension badge styling is invisible.
8. Access https://addons.mozilla.org/en-US/firefox/search/?promoted=recommended&sort=random&type=statictheme (list of recommended themes).
9. Notice the theme badge styling is invisible.

Actual:
When high contrast options are enabled:
1. The header “Firefox Browser Add-ons” title is invisible
2. Rating bars are invisible for both extensions and themes
3. Badge styling is gone

Expected:
When high contrast options are enabled:
1. The header “Firefox Browser Add-ons” title should still be visible
2. Rating bars should still be visible for both extensions and themes
3. Badge styling should persist

![2021-10-12_10h19_17](https://user-images.githubusercontent.com/50236075/136921718-4cd71afa-6697-4b1c-afc7-d3a938a87097.png)

![2021-10-12_10h19_25](https://user-images.githubusercontent.com/50236075/136921757-0a359050-be80-4e51-b05b-0bbb4455c370.png)

![2021-10-12_10h19_35](https://user-images.githubusercontent.com/50236075/136921773-5feb1aa0-aadb-47ea-9baf-cfb9a5b5fa58.png)

![2021-10-12_11h14_44](https://user-images.githubusercontent.com/50236075/136921797-e6ba9228-96c6-42f0-b798-8e2773859cba.png)

![2021-10-12_11h17_01](https://user-images.githubusercontent.com/50236075/136921828-070f4026-c08a-4ddc-8c0d-13510cb7c2ed.png)

![2021-10-12_11h36_30](https://user-images.githubusercontent.com/50236075/136921894-f7e1bdd6-c6ce-4a6a-b1b9-66446465c448.png)

**Comment by willdurand** [comment]
Yep, this is known but I would like to understand what the aim of this pref is, though, because it kinda breaks _all_ websites.
