### ISSUE TITLE
The “Extensions” and “Themes” menu buttons remain highlighted if the user navigates away from either of them to Profile or Collections pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#10970]
### Describe the problem and steps to reproduce it:
1. Log into AMO
2. Go to “Extensions” or “Themes” from the header menu. Alternatively click on an extension or a theme on the front page. Notice the header menu highlights the proper item in the header in all cases.
3. From Extensions or Themes, hover over the username in the top right corner of the page and navigate to any of the pages listed under “My Account” (Collections, Edit Profile, View Profile).

### What happened?
The “Extensions” or “Themes” buttons remain highlighted if the user  navigates away from either of them to Profile or Collections pages.

### What did you expect to happen?
None of the header menu items remain highlighted when accessing Collections or Profile pages since the context has changed

### Anything else we should know?
- the underline is removed if the Collections or Profile pages are refreshed
- the issue reproducers on all AMO servers, so it's not a new issue

**Comment by bobsilverberg** [comment]
The fact that this has always been the case, as it also exists on stage and prod, suggests to me it is a low priority to fix. I'm going to assign it a P4.

**Comment by BhavyaT-135** [comment]
Hey @AlexandraMoga, Can I work on this issue?

**Comment by kdbiddle** [comment]
Hey I picked this up and found this issue. I'll work up a PR on it this weekend.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on stage:

![firefox_6ghyIt5nkL](https://user-images.githubusercontent.com/31961530/157395842-bb7d4c23-213f-4f1b-b775-3e3bd4f381a9.gif)
