### ISSUE TITLE
statics aren't loading in local (docker) env

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#10978]
For frontend running within addons-server's docker containers the static assets (javascript, fonts, images, css) aren't loading correctly.  Whichever service is supposed to serve those urls isn't doing it, so they're being redirected to `/<locale>/app/` like any other random addons url would be (and then 404'ing).

It's not clear where the change needs to be made (could be in this repo, or addons-server, or addons-nginx) so move when the fix it identified.

**Comment by jrbenny35** [comment]
> 
> 
> Adding `staticPath: 'http://olympia.test:7011/static-frontend/',` in `development-local.js` config fixes it for me. It matches [the docker-compose config on addons-server](https://github.com/mozilla/addons-server/blob/5c7279fcb211e40f54068baa0941f84af9aa6646/docker-compose.yml#L107).
> 
> Obviously we shouldn't hardcode that though, and make the env variable work. I haven't looked through the history to understand how it broke though (it's probably my changes around static files handling).

This fix doesn't seem to work for me. 

After applying the suggested changes I ran ``yarn amo:olympia```. Are those the same steps you did?

**Comment by diox** [comment]
I applied those changes in the addons-frontend container spawned by addons-server's `docker-compose` and restarted it.

**Comment by diox** [comment]
p2 to keep this on our radar. It would be good to figure out exactly how to fix this.

**Comment by willdurand** [comment]
I find odd that the `development-local.js` config uses the express middleware to serve static assets. This likely only works when we compile the project, which isn't the case when we are in development mode. I would remove this config:

```diff
diff --git a/config/development-local.js b/config/development-local.js
index a2e9f444d..49a00e123 100644
--- a/config/development-local.js
+++ b/config/development-local.js
@@ -1,5 +1,9 @@
 import { staticPath } from './lib/shared';
 
+const webpackServerHost = process.env.WEBPACK_SERVER_HOST || '127.0.0.1';
+const webpackServerPort = 7001;
+const webpackDevServer = `${webpackServerHost}:${webpackServerPort}`;
+
 // This config should be used with a local addons-server setup.
 module.exports = {
   apiHost: 'http://olympia.test',
@@ -9,15 +13,16 @@ module.exports = {
 
   baseURL: 'http://olympia.test',
 
-  webpackServerPort: 7001,
+  webpackServerHost,
+  webpackServerPort,
 
   mozillaUserId: 10968,
+
   CSP: false,
 
-  // `config/development.js` overrides the static path to use
-  // webpack-dev-server but we don't want that for this environment.
-  staticPath,
-  enableNodeStatics: true,
+  // In local dev, we serve static files using webpack-dev-server.
+  // We need to remove the protocol because of `yarn amo:dev-https`.
+  staticPath: `//${webpackDevServer}/`,
 
   // See: https://github.com/mozilla/addons-frontend/issues/10545
   enableTrailingSlashesMiddleware: false,
```

**Comment by bobsilverberg** [comment]
Thanks @willdurand. Applying those patches does allow me to run locally via `yarn:olympia` and the statics (js and css) load fine,  but I am getting 500 errors back from API requests, so something is going wrong with my local addons-server. I'll dig in a bit to see what I can see.

**Comment by willdurand** [comment]
> I am getting 500 errors back from API requests, so something is going wrong with my local addons-server. I'll dig in a bit to see what I can see

interesting, I had that problem too!

**Comment by bobsilverberg** [comment]
> > I am getting 500 errors back from API requests, so something is going wrong with my local addons-server. I'll dig in a bit to see what I can see
> 
> interesting, I had that problem too!

I had to run `make update_docker` and then `manage.py reindex` and after that the API seems to be working. This all seems to be working for `yarn:olympia`, but I think this issue is about running addons-frontend inside the docker container, not locally. I will give that a try as well.

**Comment by willdurand** [comment]
> > 
> 
> I had to run `make update_docker` and then `manage.py reindex` and after that the API seems to be working. This all seems to be working for `yarn amo:olympia`, but I think this issue is about running addons-frontend inside the docker container, not locally. I will give that a try as well.

Yep, same here. I don't get why I had to run `make update_docker` after having run `make initialize` (since I recreated the entire docker stack locally...). Anyway, that fully works for me now.

**Comment by willdurand** [comment]
@jrbenny35 let us know if that fixed the problem for you as well, thanks!
