### ISSUE TITLE
Update react/require-extension rule

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1098]
Running `npm run lint` outputs the deprecation warning:

`The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.`

We should upgrade to get rid of that warning.

**Comment by muffinresearch** [comment]
That's not in our code-base, probably we're seeing that via the airbnb rules so this will depend on an upstream update.

**Comment by muffinresearch** [comment]
Blocked by `https://github.com/airbnb/javascript/issues/978`

**Comment by tofumatt** [comment]
Aha, good point. I was gonna see about a simple upstream patch until I saw the amount of things that need changing, we'll just wait on this I guess 😄

**Comment by kumar303** [comment]
`npm run lint` no longer shows this warning so it must have been fixed upstream
