### ISSUE TITLE
Do not display other site links in the AMO header for the blog

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#10997]
The code at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Header/index.js#L253-L257 that displays `otherSiteLinks` and the login/menu isn't intended to be displayed on the blog.

Due to a quirk of how the blog is rendered, it is not currently being displayed, but we really should only display this conditionally, when `forBlog` is `false`, to make sure it is never displayed.

**Comment by eviljeff** [comment]
@bobsilverberg from your writeup it appears that this is change/fix that would only be apparent in the blog?  Given the extra complexity involved is it practical for a contributor to work on it?  (or would you be willing to accept a patch that won't have been tested locally?)

**Comment by bobsilverberg** [comment]
> @bobsilverberg from your writeup it appears that this is change/fix that would only be apparent in the blog? Given the extra complexity involved is it practical for a contributor to work on it? (or would you be willing to accept a patch that won't have been tested locally?)

I'm not sure that this can be tested manually, as the behaviour already exists, albeit by accident. I think a patch with a test is fine, even if it hasn't been tested locally.

**Comment by willdurand** [comment]
There is a page that shows the different components in addons-frontend, and tests.

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

Mentor: @bobsilverberg

**Comment by rksingh2001** [comment]
Can I take up this issue?

**Comment by AlexandraMoga** [comment]
So, by fixing this issue, are we going to basically fix https://github.com/mozilla/addons-blog/issues/331 as well, no?

**Comment by venkateshprabhu2** [comment]
Hi. Is this issue still open? Can I work on it? @bobsilverberg

**Comment by vyshnavrajs2019** [comment]
@bobsilverberg _a

**Comment by AlexandraMoga** [comment]
As we still not have a reliable way to verify blog changes in -dev and stage, this will have to be verified in prod once the code lands.

**Comment by bobsilverberg** [comment]
> There hasn't been any change in display or functionality on the AMO header, both on the frontend and the add-ons blog side. @bobsilverberg If I understand correctly, this issue shouldn't have changed anything on a display level, isn't it?

That's correct.
