### ISSUE TITLE
update 'Products' in footer

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#10998]
In the Products section of the site footer, please...

- Remove Lockwise
- Add [VPN](https://www.mozilla.org/products/vpn/#pricing)
- Add [Relay](https://relay.firefox.com)

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
On frontend stage: 

![frontend stage](https://user-images.githubusercontent.com/33448286/140036580-77e6dd6e-f4ec-460a-a6f0-badfc023dbb4.png)

I've noticed that the vpn link is https://www.mozilla.org/en-US/products/vpn/?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org#pricing. 
"#pricing" was added after the utm params but as long as it redirects correctly it should be fine.

**Comment by bobsilverberg** [comment]
> @bobsilverberg On frontend stage:
> 
> ![frontend stage](https://user-images.githubusercontent.com/33448286/140036580-77e6dd6e-f4ec-460a-a6f0-badfc023dbb4.png)
> 
> I've noticed that the vpn link is [mozilla.org/en-US/products/vpn/?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org#pricing](https://www.mozilla.org/en-US/products/vpn/?utm_content=footer-link&utm_medium=referral&utm_source=addons.mozilla.org#pricing). "#pricing" was added after the utm params but as long as it redirects correctly it should be fine.

Yes, that was intentional, thanks!
