### ISSUE TITLE
Internal Add-ons API doesn't have a details page so "I'm Feeling Lucky" is broken

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1101]
Since the move to config-based API prefixes, we hit `/api/v3/internal/addons/addon/${slug}` when we find an exact match for an add-on. But this API doesn't (yet) exist in add-ons server, so nothing happens.

Filing here for posterity, but ultimately @diox said an internal details endpoint was on the table and this should eventually be fixed upstream in the API.

**Comment by tofumatt** [comment]
To be clear: this only happens in the admin app because `/internal` is prefixed to all its URLs. Everything is still fine elsewhere.

**Comment by diox** [comment]
Fixed in #3798
