### ISSUE TITLE
Run the node security platform tool in CI to check dependencies

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1102]
It would be helpful to run the [nsp](https://github.com/nodesecurity/nsp) command as part of our continuous integration checks so that we can be sure we're never shipping any known vulnerabilities in the new AMO frontend.

This should be as simple as adding `npm check` to our `.travis.yml`.

So far so good:

```
$ nsp check
(+) No known vulnerabilities found
```

**Comment by muffinresearch** [comment]
Snyk [1] s another similar resource that might be worth a look.

[1] https://snyk.io/

**Comment by kumar303** [comment]
The free version of Snyk only lets you test weekly
