### ISSUE TITLE
Upgrade stylelint to v14

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11030]
I am opening this issue so QA can verify that the changes in https://github.com/mozilla/addons-frontend/pull/10980 don't break any styling for the site.

The syntax for the stylesheets for many of our components has been updated in https://github.com/mozilla/addons-frontend/pull/10980. I checked most of it locally, but I think it would be good for QA to verify that nothing has regressed as well.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I'm marking this verified on AMO stage - FF94(Win10).
