### ISSUE TITLE
Test all React components with Enzyme

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1104]
It may be worth trying out [Enzyme](http://airbnb.io/enzyme/) to replace `Simulate.click()` and other 'react-addons-test-utils' things. A few things jump out from reading the docs:
- Shallow rendering looks like it works better
- It looks like event simulations are implemented better
- finding nested components looks easier

**Comment by tofumatt** [comment]
The "future" section seems especially promising if I'm reading it right; they want to focus on better event propagation in shallowly-rendered components. I'm hoping that means things like "clicking a button or enter in an `<input>` will fire a `<form>`'s `onSubmit` event", but maybe I'm being too optimistic.

**Comment by muffinresearch** [comment]
Fixing this should also mean removing all of our home-grown shallow rendering functionality.

**Comment by tofumatt** [comment]
> Fixing this should also mean removing all of our home-grown shallow rendering functionality.

I ended up adding Enzyme easily then seeing about moving all our shallow rendering tests over. Turns out it was pretty easy, so I've filed #2539 and have a PR incoming.

**Comment by kumar303** [comment]
Here's how to find all the remaining tests that need converting to Enzyme: https://github.com/mozilla/addons-frontend/search?utf8=%E2%9C%93&q=renderIntoDocument&type=

**Comment by kumar303** [comment]
Only 32 tests left 😭

**Comment by muffinresearch** [comment]
Now there's only 20 left.

**Comment by willdurand** [comment]
Only 5 files (excluding two files scheduled for deletion):

- `tests/unit/core/testErrorHandler.js`
- `tests/unit/amo/components/TestRatingManager.js`
- `tests/unit/core/components/TestInfoDialog.js`
- `tests/unit/ui/components/TestOverlayCard.js`
- `tests/unit/ui/components/TestRating.js`

**Comment by AlexandraMoga** [comment]
@willdurand could you please add a "qa:not needed" label?
Thanks
