### ISSUE TITLE
Use new direct download URL for links to download Firefox

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11045]
As a result of an experiment run a few months ago, the Bedrock team has [implemented a download page](https://github.com/mozilla/bedrock/issues/10520) that will start a download automatically, as opposed to requiring users to click a download button on www.mozilla.org. In order to use this new page, one links to the `thanks` page and adds the query param of `s=direct` to the download URL, as documented [here](https://bedrock.readthedocs.io/en/latest/download-buttons.html#external-referrers).

This issue is about updating the destination of our "Get Firefox" buttons to point to this new direct page.

For QA:
Downloading Firefox from either the button on an add-on detail page, or from the banner that appears on all other pages, should result in an immediate download of Firefox from `https://www.mozilla.org/firefox/download/thanks/`. The URL should include the `s=direct` parameter. If downloaded on a Windows device, the correct attribution data should be recorded and end up in telemetry.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
1. https://www.mozilla.org/firefox/download/thanks/ with s=direct is opened and it triggers an immediate download of Firefox on Win10.  -> expected 

2. On Android I am redirected from https://www.mozilla.org/firefox/download/thanks/ (I've noticed the ?s=direct here too) to Google store to Firefox Android app. -> expected

![androidapp](https://user-images.githubusercontent.com/33448286/148231904-2eab2428-6120-4c7e-9139-f72864723a06.png)



3. If I go to about:telemetry#environment-data-tab_settings I see:  attribution.campaign ->	amo-fx-cta-9978 from a detail page or amo-fx-cta  when clicking the download button. I hope that's fine too. 

4. Addons that require a [newer FF version](https://addons.allizom.org/en-US/firefox/addon/wombarish-humminocon-elamster/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured) have the behavior described at 1.
4. Are the blog addon cards expected to behave the same way? Right now the blog on stage redirects to the other page https://www.mozilla.org/en-US/firefox/new/ where the manual download is required but probably changes are going to be visible after the push ?

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki, that all sounds good, except for...
> 
>  5. Are the blog addon cards expected to behave the same way? Right now the blog on stage redirects to the other page [mozilla.org/en-US/firefox/new](https://www.mozilla.org/en-US/firefox/new/) where the manual download is required but probably changes are going to be visible after the push ?

I think I need to do a new release of `addons-frontend-blog-utils` in order to pick up the change in the download button. I will do that and report back.

**Comment by bobsilverberg** [comment]
@ioanarusiczki I have made the updates and the blog should now be using the correct destination on its buttons.

Thanks for calling this out!

**Comment by ioanarusiczki** [comment]
@bobsilverberg It is working now from the blog articles too. 
I see in telemetry : amo-blog-fx-cta-506646 
Verified on AMO stage with Edge on Win10, and Chrome on Android.

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki!
