### ISSUE TITLE
Move the InstallWarning above the install button

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11042]
The `InstallWarning` currently appears below the install button and add-on description:

![Screen Shot 2021-12-01 at 12 46 59 PM](https://user-images.githubusercontent.com/142755/144286370-a411a217-bbb9-4e33-9a6a-f3af6720e812.png)

To make it more prominent, it should be moved above the install button.

**Comment by wagnerand** [comment]
QA:

Please check the layout of listing and versions pages on various screen resolutions.

**Comment by ioanarusiczki** [comment]
@wagnerand 

1. On addon detail pages:

for desktop views, the layout of the page is alright. I notice the button a bit too close to the message, probably it could go a bit higher towards authors 

![detail page1](https://user-images.githubusercontent.com/33448286/145223306-e6428e72-2eb8-40d1-989c-d2df1ee96362.png)

For smaller screens  I say it's fine

![detailpage2](https://user-images.githubusercontent.com/33448286/145223877-9e313201-dc04-49b3-a404-897390c30053.png)

And with badges

![detail page with badges](https://user-images.githubusercontent.com/33448286/145224065-3846fe1e-84d0-4ec9-9872-38d46aeb9001.png)

2. On the versions page from 700 px below I see a difference between prod and the testing servers -> the install button won't expand all the way from left to right 

![see all versions](https://user-images.githubusercontent.com/33448286/145225862-54f4ff10-e447-45c4-92c8-6546efc56136.gif)

that's prod:

![on prod](https://user-images.githubusercontent.com/33448286/145226171-d590d883-636d-4b3c-9d84-ca3f3fe33e11.png)

**Comment by wagnerand** [comment]
Hm, I didn't change the layout of the install button and I think it's using the full width again once you are below 500px. @bobsilverberg is this something we need to address?

**Comment by bobsilverberg** [comment]
> Hm, I didn't change the layout of the install button and I think it's using the full width again once you are below 500px. @bobsilverberg is this something we need to address?

Ideally we should, as we've changed the layout from prod. @ioanarusiczki can you please file a new issue for this?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I filed https://github.com/mozilla/addons-frontend/issues/11053
