### ISSUE TITLE
Please add healthcheck URLs

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#11059]
### Describe the problem and steps to reproduce it:

Per https://mana.mozilla.org/wiki/display/SVCOPS/New+Service+Guide#NewServiceGuide-StandardEndpoints, all applications running in containers should support a few standard endpoints.

Although the addons-frontend supports the `__version__` endpoint, it does not support the following health check URLs,

* `/__heartbeat__`
* `/__lbheartbeat__`

Can we add them please?

### What happened?

Currently the load balancer checks the TCP port for the app health, which is not accurate, and sometimes when the app is in a bad state, even though the TCP port is still responding to pings, the app may have stopped responding to requests. Thus we need an endpoint to tell the real health of the app.

### What did you expect to happen?
The addons-frontend should support the above said two health check URLs (per Mozilla standard).

### Anything else we should know?

n/a

**Comment by bobsilverberg** [comment]
Thanks for filing this @bqbn. Based on what I am reading in the mana page, it sounds like  `/__heartbeat__` should attempt an API call to make sure that integration with addons-server, etc. is working, whereas `/__lbheartbeat__` could just serve an html page, is that accurate? Given that, is there really anything different between what we would plan to do for `/__lbheartbeat__` and what we currently do for `__version__`?

**Comment by willdurand** [comment]
This is how code-manager has implemented the two endpoints: https://github.com/mozilla/addons-code-manager/blob/bd26044d8f155584cfc45867b3ce979d4dd43bd6/src/server/index.tsx#L229-L231

**Comment by bobsilverberg** [comment]
> This is how code-manager has implemented the two endpoints: [mozilla/addons-code-manager@`bd26044`/src/server/index.tsx#L229-L231](https://github.com/mozilla/addons-code-manager/blob/bd26044d8f155584cfc45867b3ce979d4dd43bd6/src/server/index.tsx#L229-L231)

Interesting, so it doesn't actually check any dependent services (like an API call)?

**Comment by willdurand** [comment]
> Interesting, so it doesn't actually check any dependent services (like an API call)?

Yeah, that was easier to implement (aka "good enough"). I thought this was ported from addons-frontend, though, but I see we don't implement these endpoints (surprisingly).

**Comment by bobsilverberg** [comment]
> > Interesting, so it doesn't actually check any dependent services (like an API call)?
> 
> Yeah, that was easier to implement (aka "good enough"). I thought this was ported from addons-frontend, though, but I see we don't implement these endpoints (surprisingly).

I have vague recollections of removing them at some point, tbh. I guess maybe at one point there weren't needed, and now they're needed again.

**Comment by bqbn** [comment]
> Thanks for filing this @bqbn. Based on what I am reading in the mana page, it sounds like `/__heartbeat__` should attempt an API call to make sure that integration with addons-server, etc. is working, whereas `/__lbheartbeat__` could just serve an html page, is that accurate? 

That is correct. 

For the `__/lbheartbeat__`, 200 with a simple `OK` will do. For the `__heartbeat__`, normally people would return 200 with a json file listing health of its dependencies. 

> Given that, is there really anything different between what we would plan to do for `/__lbheartbeat__` and what we currently do for `__version__`?

Probably just the returned contents are different.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

On `https://addons-dev.allizom.org/__frontend_heartbeat__ `  -> I receive a 200 response with "ok"

but I get a 404 with  `https://addons-dev.allizom.org/__frontend_lbheartbeat`
I also tried `https://addons-dev.allizom.org/__lbheartbeat__ ` but it's still a 404.

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> On `https://addons-dev.allizom.org/__frontend_heartbeat__ ` -> I receive a 200 response with "ok"
> 
> but I get a 404 with `https://addons-dev.allizom.org/__frontend_lbheartbeat` I also tried `https://addons-dev.allizom.org/__lbheartbeat__ ` but it's still a 404.

https://addons-dev.allizom.org/__frontend_lbheartbeat__ seems to work for me.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Hm, yes, I tried again and I receive a 200 response "ok" on https://addons-dev.allizom.org/__frontend_lbheartbeat__ 

Same on https://addons-dev.allizom.org/__frontend_heartbeat__

👍
