### ISSUE TITLE
[tracker] Update the tracking on the disco pane

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1107]
See https://bugzilla.mozilla.org/show_bug.cgi?id=1302552 for the documentation. I'll split this out into discrete issues per update that link back to this tracker.

Relates to #1153

**Comment by alsternerd** [comment]
I've got a solution: Remove all the tracking as Firefox wants to be a privacy aware browser.

**Comment by tofumatt** [comment]
We won't be removing analytics entirely as they make it possible to improve our services. But there should be a way to opt out of it easily, I think.

A good question actually is how can users (easily) opt-out of analytics on the disco pane, as I assume Adblock and other privacy add-ons wouldn't block Google Analytics as they aren't allowed to run in the context of an `about:` page–unless they DO run in the iFrame? But I'd imagine not, as add-ons can't run content scripts on, for instance, AMO.

Presumably we have browser configs for opting out of submitting usage data? We should respect that in the disco pane, as the alternative is DNS blocking 😒

**Comment by arne-cl** [comment]
I doubt that you really need this type of analytics to improve your services, but in case you do: why not host your own solution (e.g. Piwik) instead of risking the privacy of millions of users and voluntarily handing over data to your main competitor?

**Comment by tofumatt** [comment]
Hosting our own solution (eg. Piwik) would be a considerable increase in effort and time better spent on improving our own services–additionally I find Google Analytics a superior product to Piwik. While I can't speak for product managers and metrics people on AMO who rely on these analytics, I imagine they feel similarly and decided it was best to use a better tool.

We aren't "handing over data", Google has a policy regarding data–it is not shared without explicit consent given by the customer (in this case: Mozilla). https://support.google.com/analytics/answer/6004245?hl=en

We won't be discontinuing our usage of analytics for our web properties, but I do think it would be nice to consider easy opt-outs for users like yourself who clearly do not want to participate in analytics sharing.

**Comment by Zoba273** [comment]
@tofumatt any kind of data sharing should clearly be an opt-in instead of opt-out, don't you think?

**Comment by tofumatt** [comment]
FYI: Please be careful about issuing blanket statements around what Mozilla or all users should do regarding their trust in Google. You may feel one way about trusting Google, but that's a choice that's up to you and to every user.

I'm happy to have a discussion around this and am clearly on the side of user *choice*, but as you would prefer we do not use Google Analytics at all, many Mozilla Staff and users are either happy we do or ambivilant. We should not presume to make sweeping choices for all users in any direction.

-------

Regarding opt-in/opt-out:

I believe the Firefox first-run experience asks users to opt-in to sharing usage data. What I'm saying is that it'd be great to hook into that setting to tell `about:addons` whether or not we should load analytics for that user.

**Comment by shevegen** [comment]
> I believe the Firefox first-run experience asks users to opt-in to sharing usage data. What I'm
> saying is that it'd be great to hook into that setting to tell about:addons whether or not we
> should load analytics for that user.

Agreed. It should also be very transparent for users. I think a similar discussion was in regards to the Atom editor.

Also, Mozilla should seriously consider consistency in their behaviour for PR reason alone. Either you care about user privacy and user rights - or you don't. There is no "middle ground" just as there are no "acceptable ads" either defined upstream, unless the user decides for his/her use case alone.

**Comment by toolforger** [comment]
@tofumatt still, Firefox shouldn't tell Google about what its users do.
Not if Firefox advertises itself as privacy-protecting browser; right now, it has all the signs of being quite the opposite:
- Tracks users
- By opt-out
- Though opt-out doesn't work with PrivacyBadger, or any plugin that does not expect about: to lead to external pages
- Without telling users, so it's actually not even opt-out, but ignoring what the user wanted

Let me add the user perspective here, to complement your developer focus:

To anybody who has this as first impression, this sounds like "we protect your privacy, except if we don't, in which case we don't care about your privacy".
Even if Google Analytics gives Mozilla better numbers and is much less work (points that I don't contest): breaking the "protects your privacy" promise on just these grounds is going to create lingering doubt about the project's honesty. And that's very, very bad for the project's public standing, because now anything dubious will be held against the project instead of being dismissed as ludicrous.

**Comment by tofumatt** [comment]
Thanks for your input, folks. This issue tracker is pretty specifically followed by the frontend developers on AMO and not the wider Firefox community. I don't mean to pass the buck, but if you want to raise more issues with Mozilla regarding our usage of Google Analytics you may wish to [reach out to Mozilla PR](https://bugzilla.mozilla.org/enter_bug.cgi?product=Mozilla%20PR&component=Other%20-%20Privacy). Adding to this issue won't be seen by many people and is going to clog up our development-focused bugs. Do note, however, that there are many open bugs around Mozilla using GA and it seems something we have evaluated and are comfortable with. Still, we are receptive to your feedback.

One thing to note: please do not insist "there is no middle ground". We are making a browser for hundreds of millions of people. While we appreciate your concerns and opinions, remember they are but one set of many. I agree we could be better about privacy and options here, but do not insist there are but two options (one of which you think is right)–that shuts down healthy, constructive discussions.

I'm locking this issue to contributors so it can return to its focus of implementing GA changes. If there is a bugzilla or other issue/place of discussion that is created I can link to it. Just send it to me on IRC or via email 😄

**Comment by tofumatt** [comment]
Looks like the discussion is happening over at #2785

**Comment by muffinresearch** [comment]
Closing this since we're not going to go this route.
