### ISSUE TITLE
Remove reviewer name from addons-frontend

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11073]
https://github.com/mozilla/addons-server/issues/17318 is going to do away with the `reviewer_name` field, and therefore addons-frontend should be updated to no longer make use of it. As mentioned at https://github.com/mozilla/addons-server/issues/17318#issuecomment-1004593171, the reviewer name is exposed to a user who is also a reviewer via the Edit User Profile screen:

![image](https://user-images.githubusercontent.com/31961530/148026777-b734d5f5-5f2a-4b48-98f7-1d2e37efb76a.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

On AMO dev, I verified the groups with Addons:Review permission : Reviewers: Add-ons, Reviewers: Legacy. 
Also, Reviewers: Unlisted with Addons:ReviewUnlisted permission and Reviewers: Content with Addons:ContentReview permission.

- the Reviewer Name is no longer displayed on Edit Profile page.
- I edited Display Name navigated away, checked that dev hub and the frontend displays the new name.
