### ISSUE TITLE
Replace "Occitan (Lengadocian)" with "Occitan" 

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#11096]
See mdn/content#11868

In short, we should use `Occitan` without the specific dialect (Lengadocian) because Occitan has different dialects, see also: https://en.wikipedia.org/wiki/Occitan_language

**Comment by ioanarusiczki** [comment]
@willdurand 
What I understand is that on the [Dictionaries & Language Packs](https://addons.mozilla.org/en-US/firefox/language-tools/) page,  "Lengadocian" should be removed from the Occitan's lang pack name and link text. 

This is now on -dev:

![on dev](https://user-images.githubusercontent.com/33448286/149944073-8d489a48-fb7e-49af-ba3e-cd6640264c48.png)

Clearly  "Lengadocian" was removed from the name. 
Link text is "Lang pack-oc-FR-gascon" -> I'm not sure if that's alright.

This is now on prod: 

![on prod](https://user-images.githubusercontent.com/33448286/149944313-4c9fce98-02ab-4b93-9239-fa099b45ee0a.png)

Please let me know if there's anything else to check on this or https://github.com/mozilla/addons-server/issues/18626

**Comment by ioanarusiczki** [comment]
@willdurand I've checked this on AMO prod and there's still "lengadocian" into the link name but this can be edited using admin tools (it worked for me).

**Comment by willdurand** [comment]
I think what we have on prod looks good. The category (left column on a LTR layout) should be `Occitan` and then we should have all the occitan langpacks and dictionaries. It looks like we only have one langpack that is specific to `Occitan / Lengadocian`, which is probably correct.
