### ISSUE TITLE
Add a URL parsing library and use it in the API

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#111]
Currently the API has a function to create a query string but it probably doesn't handle encoding stuff well and probably has some bugs. We should decide on a library to use for parsing/generating query strings and use that instead.

**Comment by muffinresearch** [comment]
Here's one option for covering universal url parsing https://github.com/unshiftio/url-parse. If we just need to deal with query-strings then this should suffice: https://www.npmjs.com/package/query-string
