### ISSUE TITLE
Accessing a user profile page with an expired session triggers infinite requests to the `/ratings/` API

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#11109]
### Describe the problem and steps to reproduce it:
1. Open AMO homepage and log in
2. Open a new tab and log out
3. Return to the first tab - where you still appear as logged in - and try to navigate to the View User Profile page from the header user menu

### What happened?
The profile page is loaded and there are three red banners indicting that the User session has expired. If you open the Console Network tab, you can see a failed request to `/ratings/rating/?user={id}` running in an infinite loop

### What did you expect to happen?
The failed request to the `/ratings/` API should be visible only once. Also, we should see only one red banner in the page for the expired session message. 

### Anything else we should know?
This issue reproducers on all AMO servers

![image](https://user-images.githubusercontent.com/31961530/150968084-e3d1318c-92a1-4468-ae0f-133cd27a9d41.png)

**Comment by bobsilverberg** [comment]
@eviljeff As this relates to code that you've been working with, do you want to take a look and see if you can figure out the issue here? If not, I can take it.

**Comment by eviljeff** [comment]
> @eviljeff As this relates to code that you've been working with, do you want to take a look and see if you can figure out the issue here? If not, I can take it.

I think it's the older error handling for API calls rather than the new component so isn't connected, but I can take a look

**Comment by bobsilverberg** [comment]
> > @eviljeff As this relates to code that you've been working with, do you want to take a look and see if you can figure out the issue here? If not, I can take it.
> 
> I think it's the older error handling for API calls rather than the new component so isn't connected, but I can take a look

Thanks @eviljeff. I agree that's probably what's happening, but I was thinking that if this particular page is an exception, and isn't showing the new AuthExpired component, then maybe we should remove that exception so the UX is consistent?

**Comment by eviljeff** [comment]
I think the fix is just passing down `errorHandler` to the `Page` component (`UserProfile` doesn't do this)

observations along the way:
- It's unclear why we repeat three (identical) requests to /ratings/rating/?user=xxx even in the success case for a profile page.  
- I didn't discover why the ratings requests are retried infinitely, but if once `errorHandler` is passed to `Page` it doesn't happen any longer anyway.

**Comment by AlexandraMoga** [comment]
I've verified this issue on stage and the infinite requests to the ratings API are no longer occurring. We are also displaying the new Login expired page when opening the View profile page with an expired session:

![image](https://user-images.githubusercontent.com/31961530/155304867-d0e2ab31-f17d-4c30-ade1-e508eda93c37.png)

@eviljeff as you can see in the screenshot, there still are two requests to the `/ratings/` API which return a 401 and another one with a 200 response. I don't quite understand why this happens.

**Comment by eviljeff** [comment]
> @eviljeff as you can see in the screenshot, there still are two requests to the `/ratings/` API which return a 401 and another one with a 200 response. I don't quite understand why this happens.

yeah, me neither.  I think there's an underlying bug with repeated ratings calls but I didn't investigate further than getting the correct error page to show.

**Comment by AlexandraMoga** [comment]
> yeah, me neither. I think there's an underlying bug with repeated ratings calls but I didn't investigate further than getting the correct error page to show.

ok, I'll mark this issue as verified fixed for now, since the main problem has been fixed.
