### ISSUE TITLE
reformat "Reload the page to continue without authentication..." message to allow l10n

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#11107]
Even though it's to be read as sentence it's defined as two separate strings currently which makes localization difficult.

**Comment by AlexandraMoga** [comment]
This hasn't caused any regressions on the Login expired page as far as I can see:

![firefox_fArsvPLE9Q](https://user-images.githubusercontent.com/31961530/151162707-f712e501-52a2-44ca-8576-9e7aeebc80c2.gif)

I'm marking this as verified fixed on stage.
