### ISSUE TITLE
Support addons-server SessionIDAuthentication

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#11110]
https://github.com/mozilla/addons-server/pull/18475 adds a new internal authentication method, that would be specified in the `authorization` header as `Session xxxx` (rather than `Bearer xxxx`).  The value is stored in the `sessionID` cookie - it's the django session ID.  We need to change addons-frontend so it uses this cookie rather than `frontend_auth_token` and specifies the value in the `authorization` header.

note: The cookie/auth token is no longer a JWT, it's just a session id.

**Comment by diox** [comment]
> note: The cookie/auth token is no longer a JWT, it's just a session id.

Note that `frontend_auth_token` hasn't been a JWT for a while. It's an opaque token, though the underlying implementation mimics what Django does for session handling (the salt differs though, so it cannot directly by used instead of a sessionid and vice versa)

**Comment by AlexandraMoga** [comment]
@eviljeff I can see the `sessionid` cookie being set at login, but we still have the `frontend_auth_token` alongside it. Is there a way to figure out that the  `sessionid` cookie is the one being used?

FWIW, login are working fine.

**Comment by eviljeff** [comment]
you can check the headers of the request in network panel (for client side navigation, at least) to see the `authorization` header using `Session: xxx`

**Comment by AlexandraMoga** [comment]
Ah, right. I can see the new authorization method sent with requests that require authentication:

![image](https://user-images.githubusercontent.com/31961530/153015582-86c6e3cb-1633-45b5-94c4-81963443cd68.png)
