### ISSUE TITLE
Use a fully qualified URL when logging in locally

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11114]
To help address https://github.com/mozilla/addons-server/issues/18637, when running locally, we should pass a fully qualified URL in the `to` in `startLoginUrl`.

**Comment by AlexandraMoga** [comment]
@bobsilverberg should this be a qa:not needed since it  affects only the local env?

**Comment by bobsilverberg** [comment]
@AlexandraMoga Please verify that there are no regressions with logging into AMO from the frontend.

**Comment by AlexandraMoga** [comment]
We've been verifying the login process in frontend, devhub, revtools and code manager and there were no issues found.

I'm marking this as verified fixed on -dev.
