### ISSUE TITLE
Consider removing fastclick

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#11135]
fastclick was added in 2017 (#1883) to try to work around issues with tapping links on Android. It was already supposed to be obsolete back then, but it seemed to help at the time and we've kept it since without noticing any issues.

Recently we became aware of issues with `<select>`s that may be caused by fastclick: https://github.com/webcompat/web-bugs/issues/99191

We should try removing it and see if that fixes that problem for those experiencing it. Obviously at the same time we want to ensure links etc still work properly when tapped on mobile, without delay.

**Comment by willdurand** [comment]
See also: https://github.com/mozilla/addons-frontend/issues/3465

**Comment by diox** [comment]
Aaah GitHub search failed me, didn't find this :( I knew I had seen a discussion about it before.

From my testing locally fastclick seems to be responsible for the issues with `<select>` and removing it doesn't cause any issues with tapping on links, so I've submitted https://github.com/mozilla/addons-frontend/pull/11136 to get rid of it.

**Comment by AlexandraMoga** [comment]
There were no other problems found on mobile, so I'm marking this issue as verified fixed on stage, with Android 11 and Android 10.
