### ISSUE TITLE
Implement the new mobile search page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1114]
Now that we have mocks and a search component, we should get to implementing the designs in #798.

**Comment by muffinresearch** [comment]
FWIW I've split the header task out into a separate bug. https://github.com/mozilla/addons-frontend/issues/1115

**Comment by tofumatt** [comment]
I'll split out a few more as I work on them too, so this may turn into a bit of a tracker...

**Comment by tofumatt** [comment]
Oh, these were all closed, I forgot to close this.
