### ISSUE TITLE
Migrate /components/TestAddAddonToCollection.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11147]
Migrate /components/TestAddAddonToCollection.js to react-testing-library

**Comment by ioanarusiczki** [comment]
@bobsilverberg So far , we've filed https://github.com/mozilla/addons-frontend/issues/11328 but it's a prod bug.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I did not find other issues. Verified on -dev FF97(Win10)
