### ISSUE TITLE
Migrate /components/TestAddonsByAuthorsCard.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11168]
Migrate /components/TestAddonsByAuthorsCard.js to react-testing-library

**Comment by ioanarusiczki** [comment]
@bobsilverberg Does this or https://github.com/mozilla/addons-frontend/issues/11248 require qa?

**Comment by bobsilverberg** [comment]
> @bobsilverberg Does this or #11248 require qa?

Sorry, yes, some changes were made to the "Other add-ons by author" component, so that should be checked for regressions.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I checked the section on -dev and -stage , looks good to me. Win10 &Android
