### ISSUE TITLE
Migrate /components/TestAddonRecommendations.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11161]
Migrate /components/TestAddonRecommendations.js to react-testing-library

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Looking at -stage -> the section is displayed on all extension detail pages 

![other popular extensions](https://user-images.githubusercontent.com/33448286/168991346-3b533e14-cb28-4292-b8f2-fc7354b1f964.png)


On Android on stage all looks good but I've noticed that on prod the section displays the desktop only addons too -> they look as not recommended/compatible with this platform. 
I believe this is an old known issue. In case I should file an issue let me know. 

![how it looks for Android](https://user-images.githubusercontent.com/33448286/168993641-fc18bf1e-8af0-45ff-81d8-51e82c48ebee.png)
