### ISSUE TITLE
Migrate /components/TestAddonQRCodeLink.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11160]
Migrate /components/TestAddonQRCodeLink.js to react-testing-library

**Comment by ioanarusiczki** [comment]
@bobsilverberg This if I remember well used to be a feature on Android, there was only one addon I could test with. Let me know if I should take a look.

**Comment by bobsilverberg** [comment]
> @bobsilverberg This if I remember well used to be a feature on Android, there was only one addon I could test with. Let me know if I should take a look.

Sorry, no need to test. I added the label.
