### ISSUE TITLE
Migrate /components/TestAuthenticateButton.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11172]
Migrate /components/TestAuthenticateButton.js to react-testing-library

For QA:

A minor refactor was done on the Log In button, which should not have any effect. Please check this in a couple of places. This appears, for example, in the "Rate your experience" box when not logged in.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good to me, I checked log out views on details pages, collections, profile page, homepage Win10&Android
