### ISSUE TITLE
Migrate /components/TestDismissibleTextForm.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11190]
Migrate /components/TestDismissibleTextForm.js to react-testing-library

**Comment by bobsilverberg** [comment]
> @bobsilverberg Let me know if you need qa

There was a minor refactor to DimissibleTextForm, which saves the local state of a form. This should be checked in the report User Abuse in the UserProfile screen.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I did not see changes - verified on AMO stage - FF101(Win10).
