### ISSUE TITLE
Migrate /components/TestInstallWarning.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11214]
Migrate /components/TestInstallWarning.js to react-testing-library

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
Looks good to me

![Screenshot 2022-05-13 at 15-46-00 TinEye Reverse Image Search – Get this Extension for 🦊 Firefox (en-US)](https://user-images.githubusercontent.com/33448286/168286028-fc8db958-aa92-4e4c-861f-62b2c080f436.png)
