### ISSUE TITLE
Migrate /components/TestShowMoreCard.js to react-testing-library

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11252]
Migrate /components/TestShowMoreCard.js to react-testing-library

For QA:

Some refactoring was done to the `ShowMoreCard` component which should not impact behaviour, but should be checked for regressions. This is the card that shows a "Read more" link when the contents of the card are too big. Some places to check this include:
- The Permissions card on the Add-on Detail page
- The Add-on description card on the Add-on Detail page
- The Developer comments card on the Add-on Detail page
- The Release notes card on the Add-on Detail page

It's not necessary to check all of these, but checking a couple would make sense.

**Comment by AlexandraMoga** [comment]
I haven't found issues with the 'Read more' component in the sections mentioned in the QA notes. I've also checked the Reviews section where we show a 'Read more' when there is a review with long text.

This issue is verified fixed on stage with both Desktop and Android.
