### ISSUE TITLE
Remove "Site Status " link from AMO footer 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#11308]
After some discussions on Slack, we agreed that we should remove the "Site status" link from AMO footer since the page is not active anymore and it is redirecting to https://www.mozilla.org .

Thanks.

**Comment by AlexandraMoga** [comment]
This issue is verified as fixed on all AMO servers. 

![image](https://user-images.githubusercontent.com/31961530/156726202-06c62e5b-a59b-4979-a984-b3658000b523.png)
