### ISSUE TITLE
add integration test for UserProfile showing AuthExpired component

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#11315]
follow-up for #11291 - once the react testing library base code is landed (#11309 etc) we should use that to write a test that proves the user sees the nice(r) authentication expired error page that logs them out.

**Comment by eviljeff** [comment]
@bobsilverberg now the testing has been rewritten is it an appropriate time to work on this?  And is it still necessary?

**Comment by bobsilverberg** [comment]
> @bobsilverberg now the testing has been rewritten is it an appropriate time to work on this? And is it still necessary?

I haven't gone through `TestUserProfile` to look at every test, but at a glance it doesn't look like there's anything in there for this, so that would suggest this is still something that would be useful to have. If you need any help with it please let me know.
