### ISSUE TITLE
Update circleci images

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#11340]
Our CircleCI config is referencing an obsolete machine image:
https://github.com/mozilla/addons-frontend/blob/55e627ced3a6d1e1cef2af91cd421abb12270f54/.circleci/config.yml#L27

Similar to how we moved addons-server away from `machine: true` in https://github.com/mozilla/addons-server/issues/18843 we should switch to a more recent image that is still supported like `ubuntu-2004:202201-02`.

**Comment by diox** [comment]
On top of this, we're using the legacy `circleci/node:14` convenience image to execute tests which is [also deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034).

**Comment by ioanarusiczki** [comment]
@diox I see this being closed for frontend and blog. 
Does this impact images uploaded by users, or it's + icons, banners, could impact layouts etc ?
