### ISSUE TITLE
replace use of `icon_url` with `icons` in API response

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#11349]
the api response for addon detail contains an `icons` object, as well as `icon_url`, [since 2018](https://github.com/mozilla/addons-server/issues/7514) but looks like we forgot to file an issue to upgrade frontend to use it.

A straight swap would be to use `icons['64']` (`icon_url` currently always returns the 64x64 icon) as a replacement for `icon_url`, follow-up work could involve selectively using the 32 and 128 sized icons in appropriate places (the 128 size was added with the expectation they would be used in a future refresh of the frontend pages which didn't happen)

**Comment by lharti** [comment]
PR related to this is merged
