### ISSUE TITLE
Rating component doesn't handle 0 reviews for an add-on well

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#11351]
https://addons.mozilla.org/blog/firefox-extensions-for-creatives/ includes a card for https://addons.mozilla.org/en-US/firefox/addon/extended-color-management/ and it doesn't have any reviews (at the time of writing).  This appears to have broken the rating star representation.

![Screenshot 2022-03-22 at 10-26-34 Firefox extensions for creatives - Firefox Add-ons Blog](https://user-images.githubusercontent.com/768592/159461351-142471a8-ebe2-4fb3-a4c1-b31f2fedd826.png)

**Comment by AlexandraMoga** [comment]
> For QA: you'll have to test this when the blog gets updated.

This means, when the code reaches production I guess, provided we're going to have this add-on with 0 ratings still.

**Comment by willdurand** [comment]
stage also but there is an issue with a PR dependency so it isn't deployed anywhere yet.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on stage:

[desktop]
![image](https://user-images.githubusercontent.com/31961530/159731641-e6bc44eb-7dc8-4902-bbb1-c0b6383f471b.png)

[mobile]
![image](https://user-images.githubusercontent.com/31961530/159731715-62b39578-e1b1-4b77-b78c-c62b70f5b71d.png)
