### ISSUE TITLE
Get consistent with indented lines in JSX

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1135]
Sometimes we align based on the attrs:

``` jsx
<Foo whatever="blah" something="else"
     another="whatevs" />
```

And sometimes we do it like this with just a 2 space indent

``` jsx
<Foo whatever="blah" something="else"
  another="whatevs" />
```

We should decide on the preferred approach and see if we can enforce it with linting.

**Comment by tofumatt** [comment]
Weighing in, I much prefer aligning than the two-space indent.

**Comment by kumar303** [comment]
I like two space indenting

**Comment by mstriemer** [comment]
If we're going to make it consistent with our python indenting (not needed but could make it simpler I think we'd want:

```jsx
<Foo whatever="blah" something="else"
     another="whatevs" />
<Foo
  whatever="blah" something="else"
  another="whatevs" />
```

So if you're going to do a two space indent you can't have the arguments start on the same line as the component name.

I'm happy with either of these but I'd lean towards a two space indent. With `Foo` for a component name aligning looks fine but when it is something like `OverallRating` and you're already 8 spaces in it gets annoying in my opinion.

```js
  render() {
    return (
      <Foo>
        <ul>
          {/* This looks gross :( */}
          <OverallRating count={count}
                         average={average} />
          {/* So simple! */}
          <OverallRating
            count={count}
            average={average} />
        </ul>
      </Foo>
    );
  }
```

**Comment by mstriemer** [comment]
Whatever we decide on we should likely enforce the same thing for our JS code. I'd lean towards what we do in python since we know it which is essentially either of these but not the mixed one:

```js
somethingLong(bar,
  baz); // bad
somethingLong(
  bar,
  baz); // good
somethingLong(bar,
              baz); // good (with caution, imo)

**Comment by tofumatt** [comment]
Your example convinces me of the elegance of two-space. Let's do that.
