### ISSUE TITLE
Username is not visible when changing the screen resolution.

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#11350]
Steps to reproduce:

1.Go to https://addons-dev.allizom.org/en-US/firefox/
2.Register for a new account without filling in the display name.
3.Enable Responsive Design Mode
4.Change the resolution, e.g. 918x918.

Expected results: 
Firefox User ID should be visible and the user should be able to access the links from the Account menu.

Actual results: 
Firefox User ID is hidden behind the Search box and the user can not access the links from the Account menu.

NOTES: 
Reproducible in all AMO servers.
Reproducibility depends on the username’s length.

Please see a screenshot for this issue:
<img width="929" alt="responsive" src="https://user-images.githubusercontent.com/1583842/159000779-aac02311-c233-4d64-8b06-997f9955d7f7.png">

**Comment by eviljeff** [comment]
username or display name?  (I'm assuming you mean the latter because we don't really expose the username anymore these days?)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-29
