### ISSUE TITLE
Work out the best way to deal with link prefixes

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1136]
I added a link to the homepage '/' with the locale prefixing this will result in a redir to `/en-US/firefox/`.

Can we deal with this with routing links? Or, should we set a base element to point to `/%locale%/%appname%`

The goal is whenever we link something in the app if the locale (e.g. `en-US`) and app prefix (e.g:  `firefox`, `android`) is set links should automatically be prefixed with those paths so we don't redirect on every new link.

**Comment by kumar303** [comment]
My first thought is something like `<Link href="/" />`. The `Link` component could connect to redux state so that it has `locale` and `appname` before it calls `router.push()` in its click handler.

**Comment by tofumatt** [comment]
Hmm, just realised the issue with not rendered the URL (as in @kumar303's solution): what happened when we want to output a search form with a `locale`/`appname` in it (e.g. the search form)?

I think we should render the params as part of the URLs instead of doing things in the `router.push` section.

**Comment by tofumatt** [comment]
Passing the locale and application through is a bit annoying but it certainly feels more explicit/functional/react-y, from my limited experience with it. Certainly makes it easy to follow the path of things. Oddly I'm less bothered by it than I thought...

**Comment by mstriemer** [comment]
I think a custom component as suggested above is a good idea. It should be able to just defer to `Link` though.

```jsx
import { Link } from 'react-router';

const InternalLinkBase = ({ base, children, href, ...props }) => (
  <Link href={base + href} {...props}>{children}</Link>
);

function mapStateToProps(state) {
  return {
    base: `/${state.api.lang}/${state.api.app}`,
  };
}

export default compose(
  connect(mapStateToProps),
)(InternalLinkBase);
```

If you want to set the lang and application you would just use the regular `Link` otherwise you can use the internal link.
