### ISSUE TITLE
Remove enableSearchFilters property from Search component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11377]
The `Search` component supports an `enableSearchFilters` property, which can be used to not display search filters, but all of the pages/components that include the `Search` component currently set the value to `true`, so we are not actually using the feature at all. I see it was added way back in https://github.com/mozilla/addons-frontend/commit/4a6de01a7f951a5c8b138de963306ffeaff2b917, in order to hide the sort filters on the Category page, but we now include the filters on the category page, so this seems unnecessary.

The reason this has come up is that, because we are now testing the `Search` component via integration with an actual page, and not in isolation, there is never a case during a test where `enableSearchFilters` is set to `false` and therefore we are missing test coverage.

Rather than accept less than 100% coverage, I think we should just remove this unused feature.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I did not find any regressions on the search component on AMO dev with FF98(Win10&Android).
