### ISSUE TITLE
Unexpected characters while editing a Collector’s note containing “& < >”

### ISSUE THREAD

**Issue by SilviaSabou** [mozilla/addons-frontend#11372]
Preconditions: User is logged in https://addons-dev.allizom.org/en-US/firefox/ and has at least one add-on in a collection.

Steps to reproduce:

1. Hover over your display name and select “View my collection”.
2. Click on the collection with an added add-on.
3. Click on “Edit this collection”.
4. Click on the “Leave a note” blue button.
5. Add a text containing “& < >” and save it.
6. Click on “Edit”.

Expected results: The editable text appears correctly.

Actual results: In the editable text , “& < >” appears with their HTML name.

NOTES: Reproducible in all AMO servers. - FF96(MacOS 12.2.1)
              Reproducible only with the mentioned characters.

Please see a screenshot for this issue:

before editing
<img width="791" alt="Screenshot 2022-04-04 at 14 29 31" src="https://user-images.githubusercontent.com/86671716/161704152-27fa1884-5e38-482a-9359-83a41331e2c7.png">

while editing
<img width="789" alt="Screenshot 2022-04-04 at 14 29 44" src="https://user-images.githubusercontent.com/86671716/161704185-a574dd60-5397-48cd-8a14-17f0029d5420.png">

**Comment by bobsilverberg** [comment]
This is intentional. We run sanitization against the string to prevent actual HTML from being rendered.
