### ISSUE TITLE
Remove check for `null` from `onTextInput` in `CollectionManager`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11391]
It is not possible for `event.target.value` to be null, but we are checking for it at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/CollectionManager/index.js#L190. This check is unnecessary, and impossible to test now that we have moved to an integration test via the `Collection` page, so we should remove this check.

**Comment by MReyna12** [comment]
@bobsilverberg I'd like to work on this one.
