### ISSUE TITLE
Remove `className` prop from `UserReview`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11408]
The [`className` prop in `UserReview`](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/UserReview/index.js#L23) is never used, and therefore can not be exercised in an integration test. We should remove it.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good to me. I verified this on Win10&Android - AMO dev
