### ISSUE TITLE
Update po2json

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#11414]
`po2json` hasn't had a new release in a long time, but there are fixes to its dependencies in the repo. We should update our `package.json` to reference a specific commit to grab those fixes.

**Comment by ioanarusiczki** [comment]
@diox Can this be verified by qa?

**Comment by diox** [comment]
QA noticed some translations were broken on the homepage as a result of this. I had spot-checked a few translations, but apparently some are fine and some aren't.

The key difference in the locale files is that we've done from strings like:
```js
Experimental:[ "Expérimental" ],
```

to

```js
Experimental:[ null, "Expérimental" ],
```

**Comment by ioanarusiczki** [comment]
@diox I filed a followup https://github.com/mozilla/addons-frontend/issues/11427

**Comment by ioanarusiczki** [comment]
@diox I hope this is fine, I switched to some other languages besides en-US on AMO stage and I did not see anything unusual.
