### ISSUE TITLE
Update documentation on how to set up and run UI tests

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1142]
### Describe the problem and steps to reproduce it:

The [UI tests documentation](https://github.com/mozilla/addons-frontend/tree/master/tests/ui) seems to be out of date with what's actually done in `.travis.yml`

### What happened?

I tried to run `tox -e discopane-ui-tests` locally but I get this error:
````
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
````

### What did you expect to happen?

I should be able to run the tests. I know I haven't configured it right but the installation steps should be documented. Also, can't all of these dependencies just live in Python so they can be managed by tox?

### Anything else we should know?

I am on Mac OS X

**Comment by davehunt** [comment]
@kumar303 you need to download geckodriver from https://github.com/mozilla/geckodriver/releases and make sure it's in the path. This is actually noted in the documentation, but the version is out of date. Note that this still won't be identical to what's run in Travis, as we also start the docker container running the application under test. If we want a local run that's identical to Travis then we could write a shell script that Travis can run, but that we can also run locally.
