### ISSUE TITLE
URL with kanji results in 404

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#11438]
I assume it is a regression caused by something on the next milestone (05.05.2022)

STR:
1. From edit page of an addon that uses kanji in the name click on View Product Page

https://addons-dev.allizom.org/en-US/developers/addon/%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E5%AD%A6%E5%B9%B4%E5%88%A5%E6%BC%A2%E5%AD%97%E9%85%8D%E5%BD%93%E8%A1%A814/edit

Actual result: 
404 page

Expected result:
The detail page should be displayed because the addon has been approved

Notes:
not reproducible on AMO stage, it is only reproducible on AMO dev
only reproducible with kanji addons
cc @diox 

![404](https://user-images.githubusercontent.com/33448286/165720299-8df43e3e-9ed2-4f79-9801-4648ee5d42a8.gif)

**Comment by diox** [comment]
Locally, I see this which is suspicious:
`
[2] [1651139258663] DEBUG (proxy/519696 on fiber): 404 ~> https://addons-dev.allizom.org/api/v5/addons/addon/%C3%A6%C2%BC%C2%A2%C3%A5%C2%AD%C2%97%C3%A6%C2%BC%C2%A2%C3%A5%C2%AD%C2%97%C3%A6%C2%BC%C2%A2%C3%A5%C2%AD%C2%97%C3%A5%C2%AD%C2%A6%C3%A5%C2%B9%C2%B4%C3%A5%C2%88%C2%A5%C3%A6%C2%BC%C2%A2%C3%A5%C2%AD%C2%97%C3%A9%C2%85%C2%8D%C3%A5%C2%BD%C2%93%C3%A8%C2%A1%C2%A814/?app=firefox&appversion=101.0&show_grouped_ratings=true&lang=en-US
å½è¡¨14/ (status: 404)00] WARN (amo/519793 on fiber): Failed to load add-on with slug 漢字漢字漢字学年別漢字配当表14: Error: Error calling: /api/v5/addons/addon/æ¼¢å­æ¼¢å­æ¼¢å­å­¦å¹´å¥æ¼¢å­é
[1]     amo_request_id: "47ed8a79-c0cb-4797-a898-d063ab096367"
`

Note how the API call is incorrect.

**Comment by diox** [comment]
Bisected down to 0dc0fe4896aa1bb4c855fb5b0c8500cb3c600820 which passes tests and should have been just a minor upgrade, but evidently wasn't...

**Comment by diox** [comment]
See also:
- https://github.com/mozilla/addons-frontend/issues/1898
- https://github.com/mozilla/addons-frontend/issues/3138

When verifying the fix for this issue we should also ensure these issues have not regressed either.

**Comment by ioanarusiczki** [comment]
@diox I'm still investigating about non ascii slugs (but seems to be working). 
Right now all category pages are throwing a 404. Same for the tags (from the detail pages)

**Comment by ioanarusiczki** [comment]
@diox the query search https://addons-dev.allizom.org/en-US/firefox/search/?q=%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E5%AD%A6%E5%B9%B4%E5%88%A5%E6%BC%A2%E5%AD%97%E9%85%8D%E5%BD%93%E8%A1%A8 

is failing right now, I get a 404 

![search kanji](https://user-images.githubusercontent.com/33448286/165918523-454617a4-1397-4cd4-b4fa-6be8cc2102fb.png)

I've uploaded many addons with kanji like this one https://addons-dev.allizom.org/en-US/firefox/addon/%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E5%AD%A6%E5%B9%B4%E5%88%A5%E6%BC%A2%E5%AD%97%E9%85%8D%E5%BD%93%E8%A1%A814/

**Comment by bobsilverberg** [comment]
I am hoping that https://github.com/mozilla/addons-frontend/pull/11450 will fix these issues as well.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @diox Looks good to me now. Verified on AMO dev - FF 99(Win10)
