### ISSUE TITLE
Replace conditionals with invariants in some components for unreachable code

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11431]
There are some conditional statements in some components that will never resolve to `true` because of the way the components are included in other components. For example, in `ReportAbuseButton`, we have a check in the `render` method that returns `null` for the component if `addon` is false. However, because `ReportAbuseButton` is only ever included in `RatingManager`, and `RatingManager` has its own check to not render `ReportAbuseButton` unless `addon` is `true`, it will never be the case that `addon` is false during the `render` method of `ReportAbuseButton`.

Furthermore, because we are moving to more integration style tests, we will never render `ReportAbuseButton` on its own in a test, but will only ever render it in the context of a `RatingManager`. This means it is impossible to cover that code path and we will end up with reduced coverage.

For this reason we should replace the cases where we have unreachable code inside conditions with calls to `invariant`, which will endure that should a case ever occur where the condition would have been `true`, an error will be thrown to alert us to the fact.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This issue was verified on AMO dev - FF99, no regressions were found. 
An issue was filed on Abuse Report but it's reproducible on all servers 
https://github.com/mozilla/addons-frontend/issues/11452
