### ISSUE TITLE
Confirmation message is not displayed after the second “Report this add-on for abuse” process is complete. 

### ISSUE THREAD

**Issue by SilviaSabou** [mozilla/addons-frontend#11452]
**Tested with:** FF99, macOS (12.3.1)
                                 
**Preconditions:** User is logged in https://addons-dev.allizom.org/en-US/firefox/ .

**Steps to reproduce:**

1. Open an add-on details page - ex: https://addons-dev.allizom.org/en-US/firefox/addon/dark22reader/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=tag-shelf-antivirus
2. Click on the “Report this add-on for abuse” button.
3. From the smaller window opened with a list of issues, select “Something else” and click “Next”.
4. Fill in additional information in the textbox and click on the “Submit” button.
5. Refresh the page after “You reported this add-on for abuse” message is displayed.
6. Repeat steps 2, 3 and 4.

**Expected results:** “You reported this add-on for abuse” message should be displayed.

**Actual results:** “Report this add-on for abuse” button is available and “You reported this add-on for abuse” message is not displayed.

**Notes:** Reproducible with all AMO servers.
                 It’s an intermittent issue which is reproducible most of the times when the same option from the list is picked.

Please see a video for this issue:

https://user-images.githubusercontent.com/86671716/166226464-da11afc0-4408-45ca-ba45-2bc05a41d339.mov

**Comment by bobsilverberg** [comment]
I am trying to reproduce this, but can't seem to get the Firefox dialog to appear. This does not reproduce with the AMO flow (where the AMO form is used, as opposed to the Firefox dialog). How are you reproducing this on dev? Is there some specific config needed for Firefox to have it show the dialog on dev?

**Comment by bobsilverberg** [comment]
Oh, I have an idea what might be going on anyway. When you reproduce this, do you see a message in the console saying "Reporting add-on for abuse via firefox failed: Error: Error submitting abuse report"? It could be that the abuse report is being rejected, and if that is the case that would explain why we don't show the confirmation message.

**Comment by SilviaSabou** [comment]
<img width="499" alt="Screenshot 2022-05-03 at 08 13 42" src="https://user-images.githubusercontent.com/86671716/166407235-f894ebf2-31bb-4dd2-a70b-f99bc344762b.png">

**Comment by SilviaSabou** [comment]
and i used this prefs for -dev : 

- extensions.abuseReport.url - https://addons-dev.allizom.org/api/v4/abuse/report/addon/
- extensions.abuseReport.amoDetailsURL - https://services.addons-dev.allizom.org/api/v4/addons/addon/
- extensions.webapi.testing = true

**Comment by bobsilverberg** [comment]
@SilviaSabou Your reply at https://github.com/mozilla/addons-frontend/issues/11452#issuecomment-1115746372 confirms that the abuse report is rejected (probably as a duplicate), which explains why we don't show the message. This is the expected behaviour.
