### ISSUE TITLE
Addon detail and /blocked-addon/ pages return a 404 when accessed with a `guid` in format `{6eeb4879-...}`

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#11485]
### Describe the problem and steps to reproduce it:
Open the following detail page - `https://addons.allizom.org/en-US/firefox/{6eeb4879-9c55-4c50-bc21-ad9af693e6ae}/`

### What happened?
A 404 is received

### What did you expect to happen?
The page should redirect to this addon - https://addons.allizom.org/en-US/firefox/addon/release-11-05/

### Anything else we should know?
This issue also affects the /blocked-addon/  pages, where requests are using the  `guid` by default, so there is no workaround there: `https://addons.allizom.org/en-US/firefox/blocked-addon/{f95e62ba-170b-444c-81ca-46520cad582e}/`; here is the link to the block page from [admin](https://addons-internal.stage.mozaws.net/en-US/admin/models/blocklist/block/343/change/) where the add-on is fully blocked.

Also, here is another example to show that block pages are opened when the `guid` doesn't use the format causing the issues: https://addons.allizom.org/en-US/firefox/blocked-addon/adio-guid@1user.com/

This issue reproduces in all AMO environments.

**Comment by AlexandraMoga** [comment]
> @AlexandraMoga Do you know if this is a regression or something that has always been the case?

It is definitely a regression and a pretty recent one. This used to work in the past.

**Comment by diox** [comment]
When testing this, we should also retry https://github.com/mozilla/addons-frontend/issues/11438 - and URLs with non-ascii characters in general.

**Comment by AlexandraMoga** [comment]
The following pages are no longer throwing 404 errors:
- add-on detail - https://addons-dev.allizom.org/en-US/firefox/addon/{f6af7435-1df6-43e0-9177-11b2c24f58c8}/
- blocked add-on - https://addons-dev.allizom.org/en-US/firefox/blocked-addon/{eadd68e4-fd9c-465a-bdc9-30346a3acb91}/
- non-ascii slug:
  - https://addons-dev.allizom.org/en-US/firefox/addon/%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E6%BC%A2%E5%AD%97%E5%AD%A6%E5%B9%B4%E5%88%A5%E6%BC%A2%E5%AD%97%E9%85%8D%E5%BD%93%E8%A1%A85/
  - https://addons-dev.allizom.org/en-US/firefox/addon/%E0%A8%AE-%E0%A8%86%E0%A8%AA%E0%A8%A3-%E0%A8%B5-%E0%A8%9A-%E0%A8%B0-%E0%A8%A8-%E0%A8%B2%E0%A8%B9/
  - https://addons-dev.allizom.org/en-US/firefox/addon/%EC%9B%83/

This issue is verified fixed on -dev.
