### ISSUE TITLE
Incompatible addons are displayed on Android into other popular extensions section

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#11495]
As discussed https://github.com/mozilla/addons-frontend/issues/11161#issuecomment-1129721661

TAAR service is recommending addons on the detail pages into "Other popular extensions" section - on Android 2 of them are not compatible therefore they do not display the "recommended" badge either. 

![other popular extensions](https://user-images.githubusercontent.com/33448286/168991346-3b533e14-cb28-4292-b8f2-fc7354b1f964.png)

This is a screenshot from AMO prod - on testing servers the issue is not noticeable.
Not marking is prod bug , I'm very sure the issue is quite old.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-36)

**Comment by diox** [comment]
Fixed in https://github.com/mozilla/addons-frontend/issues/12535

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-36
