### ISSUE TITLE
Implement a mixed themes/extensions search page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1155]
We need to separate extensions and themes in search results as in the mock here:

<img width="207" alt="screenshot 2016-09-28 17 35 19" src="https://cloud.githubusercontent.com/assets/90871/18922779/f08fbbd2-85a1-11e6-8002-6ecce2476883.png">

And then use our existing style of search result page for the "show more" results here:

<img width="203" alt="screenshot 2016-09-28 17 35 57" src="https://cloud.githubusercontent.com/assets/90871/18922800/094bf370-85a2-11e6-9253-029a07e4ecb4.png">

**Comment by muffinresearch** [comment]
This feels like it might interfere with search result relevance. I wonder if we should refer this back to UX. 

For example: 

If I'm searching for a theme called foo, and we always show extensions first, the theme result will be hidden from view even if it was the most relevant result for the search term.

**Comment by tofumatt** [comment]
Yeah... I was thinking about this a bit and I'd say that what we should do is prioritise the top result somehow, and then show each section. Though perhaps we could be smart about it; if there are *four theme* results for "Harry Potter" and *one extension* (and I'd imagine either many more of one kind of result for a search would be common, though data would be better from common search terms), we show *themes first*.

But no matter what show the first result at the top?

UX input would help though, agreed.

**Comment by muffinresearch** [comment]
@tofumatt can this issue be closed or is it still relevant?

**Comment by tofumatt** [comment]
The intricacies of result order could be said to need more UX, but I
figured whichever "type" of add-on had the most relevant results would show
up on top (search results are returned sorted by relevance) so if searching
for  "nature" gets you a bunch of themes and one is the first result themes
show first.

I think this component is complex

- tofumatt

**Comment by Ryuno-Ki** [comment]
Hm, what about putting exact matches (whole word appears in title or description) first (both themes and extensions).
Below it show fuzzy searches (i.e. „food” when searched for „foo”).

Ranking criteria could be recent updates or average vote.

**Comment by pwalm** [comment]
Any more ux or direction needed from me on this?

**Comment by muffinresearch** [comment]
I think this one is covered elsewhere now.
