### ISSUE TITLE
Show data loading indicator for overall rating submission

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1156]
While the user is submitting an [overall rating](https://github.com/mozilla/addons-frontend/issues/1017) the UI should show some kind of loading indicator. Maybe a simple spinner would be enough.

UX flow tracker: #927

**Comment by muffinresearch** [comment]
Relates to https://github.com/mozilla/addons-frontend/issues/1219

**Comment by kumar303** [comment]
This should get fixed by https://github.com/mozilla/addons-frontend/issues/2179

**Comment by Ryuno-Ki** [comment]
As I said in https://github.com/mozilla/addons-frontend/issues/2179#issuecomment-289306398 watch out for a11y support.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7)
While hovering over the rating stars, no matter if a review was already submitted or a new one is made, any selection I made, same info is displayed, "no ratings" in my case.
Please see the video:
![no rating](https://user-images.githubusercontent.com/15685960/31070711-0c6f755a-a76a-11e7-9cdc-07a4bc0cebb6.gif)

Am I missing something?

**Comment by kumar303** [comment]
The 'No ratings' label is confusing and will be fixed in https://github.com/mozilla/addons-frontend/issues/3231

As for the original issue here, I'm re-opening it because there is still no visual indication that submitting a rating is *in progress*. For slow connections, this may cause confusion and lead to double submissions. 

All in all, it's not an urgent bug but I think we could do something here like render the stars read-only or something.

**Comment by kumar303** [comment]
Now that we have some production usage, submitting a review is a bit slow (almost one second on average). We should definitely add a loading indicator.

![amo prod frontend apis usage performance datadog](https://user-images.githubusercontent.com/55398/32347998-7a30a224-bfe0-11e7-919c-a9229cd6b060.png)
