### ISSUE TITLE
locale bundle should be loaded using dynamic import rather than bundle-loader

### ISSUE THREAD

**Issue by ziir** [mozilla/addons-frontend#11601]
Related to https://github.com/mozilla/addons-frontend/issues/10596

The locale bundle is currently being loaded using [bundle-loader](https://github.com/webpack-contrib/bundle-loader):

https://github.com/mozilla/addons-frontend/blob/0693e23eb40ebca1ffa77dcfb9f095348ec10f65/src/amo/client/base.js#L79-L85

`bundle-loader` is deprecated and should be removed in favor of [dynamic import](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import).

**Comment by diox** [comment]
QA: should be a transparent change, changing language on the frontend using the dropdown should still work, as well as loading pages in different languages via their URL directly.

**Comment by ioanarusiczki** [comment]
@diox Looks good to me. Verified on AMO dev - FF101(Win10).
