### ISSUE TITLE
Remove code for the Fenix QR code feature which was never turned on

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11649]
There was an intention to run an experiment to test the value of including a link on pages for Fenix-compatible add-ons which would display a QR code for the `/android/` details page for the add-on. The general idea is that someone visiting this page would be able to use the camera on their android phone to scan the QR code which would then take them to the correct page for the add-on on their phone.

The experiment was never run, and there is some maintenance required for the code when the list of Fenix-compatible add-ons changes, which is now causing CI to fail.

As this code was never used, the recommendation is to remove it, which will also address the CI failure. If a point comes where we want to have this code back, we can always resurrect it from Git.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified the page https://addons-dev.allizom.org/en-US/firefox/addon/youtube-high-definition/ where this feature was tested, this was the only add-on where "Also available on Firefox for Android" blue link was available and now I no longer see it displayed on the page. 

Let me know if there's anything else I should be looking at.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I verified the page [addons-dev.allizom.org/en-US/firefox/addon/youtube-high-definition](https://addons-dev.allizom.org/en-US/firefox/addon/youtube-high-definition/) where this feature was tested, this was the only add-on where "Also available on Firefox for Android" blue link was available and now I no longer see it displayed on the page.
> 
> Let me know if there's anything else I should be looking at.

That sounds fine, thanks @ioanarusiczki
