### ISSUE TITLE
Reduce docker image

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#11647]
The docker image is 2.1GB and changes very often, presumably due to the changed JS dependencies.

Biggest contributors to that size are:
1) Yarn cache at `/usr/local/share/.cache/yarn` (471MB)
2) `.git` folder at `/srv/code/.git` (774MB)
3) node modules at `/srv/node/node_modules` (478MB)

4) Also, there is `gcc` at `usr/lib/gcc` (87MB)

I believe we should be able to remove (1) and (2) easily, not sure about (3) and (4).

**Comment by willdurand** [comment]
> 4\. Also, there is `gcc` at `usr/lib/gcc` (87MB)

Can you try to uninstall `gcc` after we ran `yarn install`?

**Comment by wagnerand** [comment]
> > 4. Also, there is `gcc` at `usr/lib/gcc` (87MB)
> 
> Can you try to uninstall `gcc` after we ran `yarn install`?

https://github.com/mozilla/addons-frontend/blob/master/Dockerfile#L31 was added years ago but never enabled, not sure why. Can we un-comment that now?

**Comment by willdurand** [comment]
> [`master`/Dockerfile#L31](https://github.com/mozilla/addons-frontend/blob/master/Dockerfile?rgh-link-date=2022-07-05T12%3A37%3A10Z#L31) was added years ago but never enabled, not sure why. Can we un-comment that now?

We cannot remove `yarn`, I think so I'd only purge gcc to being with (or `build-essential` maybe).

**Comment by ioanarusiczki** [comment]
@wagnerand Do you need qa here?
