### ISSUE TITLE
Rating stars are smaller in size than before 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#11746]
While checking AMO stage on Android I've noticed that in edit mode -> the rating stars look different , a lot smaller

Dev and Stage

![now on stage](https://user-images.githubusercontent.com/33448286/180198230-cb930a6d-4c55-49e8-853a-0870197ae93f.png)

Prod 

![now on prod](https://user-images.githubusercontent.com/33448286/180198294-e99b5d40-8867-4346-be5c-57c5e9a9dd7c.png)

On Desktop -> I've noticed a layout issue , the text is centered , but maybe that's expected ?

![desktop stage](https://user-images.githubusercontent.com/33448286/180198404-5e30ae37-aeb9-45be-b5e4-66fa8d30e8a9.png)

On prod it looks like:

![desktop prod](https://user-images.githubusercontent.com/33448286/180198463-b9d88541-72a6-4b95-bbab-5e9b933cbfac.png)

**Comment by ioanarusiczki** [comment]
Probably regressed from https://github.com/mozilla/addons-frontend/issues/11701

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. @diox Do you want to take a look at these, having made the changes to the stars?

**Comment by diox** [comment]
Definitely https://github.com/mozilla/addons-frontend/issues/11701 - I tried to be extra careful checking the styles in various pages on desktop & mobile, but missed that one...

**Comment by ioanarusiczki** [comment]
@diox

The issues are no longer reproducible on AMO dev FF102(Win10) & Android.
