### ISSUE TITLE
Removed extension appears in "Trending" section

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons-frontend#11799]
https://addons.mozilla.org/firefox/addon/vpnfox/

![vpn](https://user-images.githubusercontent.com/6733770/182996209-65f925ba-b6e1-48b0-986d-8c1f243da533.png)

![removed](https://user-images.githubusercontent.com/6733770/182996315-f3219eb1-0c47-4886-82a3-a66ece78529b.png)

**Comment by diox** [comment]
This can happen intermittently when extensions are disabled/removed because of the delay for reindexing the content (as our homepage APIs are search-based) and/or caching.
