### ISSUE TITLE
Remove HTTPS Everywhere from recommendations

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons-frontend#11801]
HTTPS Everywhere is still a recommended extension and might even appear at the top of the front page, even though Firefox now has a built-in HTTPS-only mode.

>With these simple settings available, EFF is preparing to deprecate the HTTPS Everywhere web extension as we look to new frontiers of secure protocols like SSL/TLS. After the end of this year, the extension will be in “maintenance mode.” for 2022

>https://www.eff.org/deeplinks/2021/09/https-actually-everywhere

![https](https://user-images.githubusercontent.com/6733770/183712196-4c171155-72fe-48d8-ad84-87b916a3ae96.png)

**Comment by eviljeff** [comment]
@devaneymoz

**Comment by anewuser** [comment]
Another one:

![Smart HTTPS](https://user-images.githubusercontent.com/6733770/187815664-5ae9af5c-ed9e-4a0c-8d07-bb4e0404478d.png)

**Comment by anewuser** [comment]
HTTPS Everywhere has been removed from the site, and Smart HTTPS doesn't currently have any badge.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-95
