### ISSUE TITLE
Calculate computed state properties only when the relevant state changes

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1181]
As a companion to https://github.com/mozilla/addons-frontend/issues/1126, here is another optimization we can apply to any component that computes a property from Redux state.

Let's say, for example, we moved the [user entities calculation](https://github.com/mozilla/addons-frontend/blob/master/src/core/reducers/users.js#L2-L4) into just the components that need to work with user objects (as derived from the Redux state key, `entities`). We would do this in something like [mapStateToProps](http://redux.js.org/docs/basics/UsageWithReact.html#container-components) but it would be calculated on every state change, even if the user entities had not changed.

Let's use something like [reselect](https://github.com/reactjs/reselect) to only derive properties from state when that relevant state _changes_.

**Comment by mstriemer** [comment]
Another advantage of this is that we can move the selector function into the same file as the reducer. This would work well with #1299 where we combine the constants, action creators, reducers and in this case selectors into one file.

Example where we don't want the redux state format being included all over:

```js
function mapStateToProps(state, { clientApp, addonType }) {
  const categories = state.categories.categories[clientApp][addonType] ?
    state.categories.categories[clientApp][addonType] : {}; 
}
```

This is really structured and requires each consumer to go digging into that state object. We could reduce the dependence on the structure of state by doing:

```js
import { getAllCategories } from 'amo/reducers/categories';
function mapStateToProps(state, { clientApp, addonType }) {
  const categories = getAllCategories(state, { app: clientApp, addonType });
}
```

**Comment by kumar303** [comment]
Dupe of https://github.com/mozilla/addons-frontend/issues/1126
