### ISSUE TITLE
Firefox theme remains white 

### ISSUE THREAD

**Issue by Carmentataru** [mozilla/addons-frontend#11829]
Firefox theme remains white

STR: 

 1. Launch AMO homepage  

2. Access theme categories  

3. Download an old version of a theme (ex: https://addons-dev.allizom.org/en-US/firefox/addon/black-and-white/versions/?utm_content=search&utm_medium=referral&utm_source=addons.mozilla.org)  

4. The Firefox theme becomes white  

5. Go to about:add-ons 

6. Select check for updates 

7. The theme can’t be updated because of the issue https://github.com/mozilla/addons-frontend/issues/11485

8. Remove theme  

9. The Firefox remains white  

Expected: 

The Firefox should return to the default theme (ex: black)  

Actual:  

The Firefox remains white after the theme is removed from the browser  

 Notes: This issue is reproducible on FF Developer Edition v. 105.0b9, AMO dev using macOS 12.4 

[Screen Recording 2022-09-13 at 12.38.27-1.mov.zip](https://github.com/mozilla/addons-frontend/files/9556440/Screen.Recording.2022-09-13.at.12.38.27-1.mov.zip)

**Comment by bobsilverberg** [comment]
I'm not sure that this is an AMO issue. It sounds more like a Firefox issue. @willdurand WDYT?

**Comment by willdurand** [comment]
Yeah, I don't see how it can be a bug in AMO given the STR.

I am curious, does not checking for updates (Step 6) restores the previous theme in Step 9?

**Comment by Carmentataru** [comment]
Hello,
Thank you, I logged it in Bugzilla, and related to your question, if the user does not check for updates (step 6) the Firefox returns to the default theme. 
Can I close this issue now since we have opened the Bugzilla one?
