### ISSUE TITLE
Remove code for TAAR Lite experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11822]
We have been sending custom dimensions for a very old TAAR Lite experiment to GA for a very long time (since [May of 2018](https://github.com/mozilla/addons-frontend/commit/875b3b48d4fc5c7bed860c8b447e7140743ddacb)). The experiment was turned off in [July of 2018](https://github.com/mozilla/addons-frontend/commit/e55a742acfc09b8cfafc02d1ff03971a2f205a06), but we continue to send these custom dimensions.

We should now remove all of the code that was put in place for this experiment and stop sending these custom dimensions.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

When the detail pages are loaded the Console displayed 2 events with values "TAAR_COHORT_INCLUDED" and "TAAR-LITE-AB"  -> these are no longer displayed for AMO dev. 

"Other popular extensions" section is available for all extensions.
