### ISSUE TITLE
Add `si` to the list of supported languages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11838]
[This commit](https://github.com/mozilla/addons-frontend/commit/e456c1a98f5c7876db983ba3d6ac0188e143a074) added `si` as a locale, which broke our test automation. I assume that if it is supported in Pontoon, it is a valid language to support, and should be added to our list of supported languages in addons-frontend.

@peiying2 can you comment on this?

**Comment by peiying2** [comment]
Hello @bobsilverberg yes, the community requested to add the locale to the project in Pontoon, so please make necessary changes to support it on your side.

**Comment by bobsilverberg** [comment]
> Hello @bobsilverberg yes, the community requested to add the locale to the project in Pontoon, so please make necessary changes to support it on your side.

Thanks @peiying2. Could you please tell me the English name of this language, and the native name of the language? The latter can be expressed in Unicode (e.g., `u'\u09ac\u09be\u0982\u09b2\u09be'`) if necessary.

**Comment by bobsilverberg** [comment]
> English name: Sinhala (or Sinhalese) Native name: සිංහල

Thanks. It looks like we already have that as `\u0dc3\u0dd2\u0d82\u0dc4\u0dbd`. Does that look correct?

**Comment by bobsilverberg** [comment]
> > English name: Sinhala (or Sinhalese) Native name: සිංහල
> 
> Thanks. It looks like we already have that as `\u0dc3\u0dd2\u0d82\u0dc4\u0dbd`. Does that look correct?

I confirmed, it looks the same. Thanks!

**Comment by peiying2** [comment]
Thank you all for implementing the updates.
