### ISSUE TITLE
Implement a categories component/page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1183]
Implement the design in #803 and create a page to view the categories.

**Comment by ValentinaPC** [comment]
The categories sections (for themes and add-ons) where added and look like it should.
Postfix screenshot: 
![screenshot_20170207-085633](https://cloud.githubusercontent.com/assets/15685960/22680998/ab98e164-ed13-11e6-9dfa-6b655db4752a.png)
