### ISSUE TITLE
Experiment cookie should be set to SameSite=Strict

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11836]
I noticed a warning about the experiment cookie in the console on dev:

`Cookie “frontend_active_experiments” does not have a proper “SameSite” attribute value. Soon, cookies without the “SameSite” attribute or with an invalid value will be treated as “Lax”. This means that the cookie will no longer be sent in third-party contexts. If your application depends on this cookie being available in such contexts, please add the “SameSite=None“ attribute to it. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite`

Because this cookie is only used by addons-frontend, it never needs to be sent to third party sites, so it can be set to `SameSite=Strict`. Allowing it to default to `SameSite=Lax` does not cause any issues, but it will generate a warning in the console, and best practices dictate that we set a value and not rely on the default.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Moving this on the next milestone ->  06.10.2022

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I found the value: it's SameSite:"Strict"-> in Storage -> Coolies -> Data , for in or not in experiment. 

Also I've noticed there's a a-branch and b-branch for in experiment cookies. 

Verified on AMO dev - FF104(Win10) .
