### ISSUE TITLE
Update react-router monorepo to v5

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11844]
This is part of https://github.com/mozilla/addons-frontend/issues/11843

**Comment by ioanarusiczki** [comment]
@bobsilverberg At a quick look over the frontend pages on AMO dev I did not see issues. - FF104(Win10)
If there's anything in particular I should check, please let me know.

**Comment by bobsilverberg** [comment]
> @bobsilverberg At a quick look over the frontend pages on AMO dev I did not see issues. - FF104(Win10) If there's anything in particular I should check, please let me know.

I think just clicking around a bit to make sure that navigation works is probably enough.
