### ISSUE TITLE
Fix bundle size regression introduced by docker images optimization

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#11853]
In https://github.com/mozilla/addons-frontend/issues/11647 we added `.*/` to the dockerfile, to reduce its size by removing the `.git` folder.

Unfortunately, that has removed _all_ dotfiles from the image, and not just "dotfolders". This had quite an impact, because our bundles are built from the docker image, so we were building without the correct `.browserslistrc`, which caused our bundle to be a lot larger than it should in dev/stage/prod environments !

We never noticed in CI because our `bundlewatch` check runs on a local checkout without building a docker image at all.

The difference is significant : the main bundle does from 1.7 M (325K after brotli) to 1.2 M (288K after brotli) in size. This also likely explains the recent poor scores on the Interaction To Next Paint experimental metric in Google CrUX.

**Comment by AlexandraMoga** [comment]
@diox is this a qa not needed?

**Comment by diox** [comment]
We can see using devtools network panel that for dev, the main bundle is now 1.18 MB in uncompressed size, against 1.74 MB on stage and prod. (unfortunately it looks like cloudfront brotli compression is not at the maximum quality level, so prod&stage transferred size is around 376 kB vs 329 kB for dev)
