### ISSUE TITLE
an option to show only reviews with text content

### ISSUE THREAD

**Issue by FranklinYu** [mozilla/addons-frontend#11915]
This is a feature request for AMO.

AMO shows review for an add-on, which is essential for choosing add-ons. It looks like this:

![image](https://user-images.githubusercontent.com/3153452/148673904-b6c0f4d7-0b1d-4fbf-8ec6-02ece2a04050.png)

I feel that review with text content typically gives more information than a score-only review; the latter doesn’t provide more information than the general statistics at the left. For example, the one-star review in the screenshot above isn’t really a problem of the extension itself, but the user unaware of iOS platform limitations.

It would be nice to be able to only see the review with text contents. For example, we can add a mode to the drop-down menu at the top-right. Mock:

![image](https://user-images.githubusercontent.com/3153452/148674084-b2e9b2b3-8459-4f20-a409-3d7f986a99c1.png)

**Comment by Zaglim** [comment]
Adding comment to keep this issue open. Still not possible to filter to only reviews with text content

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-107
