### ISSUE TITLE
Horizontol scrollbars in detail page with long description text

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1191]
Very long text with no line breaks will cause horizontal scrolling on the details page.

<img width="1388" alt="screenshot 2016-10-07 12 35 06" src="https://cloud.githubusercontent.com/assets/90871/19188593/a3dee2b4-8c8a-11e6-8ad0-1c880f7cef47.png">

If you're using the dev server you can see it at this URL: http://127.0.0.1:3000/en-US/firefox/addon/gmail-notifier-restartless/

**Comment by jvillalobos** [comment]
Mentor: @tofumatt 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by Katy310** [comment]
I would like to work on this issue. Any pointers or guidelines apart from the Code Contribution guidelines?

**Comment by tofumatt** [comment]
No other guidelines I can think of. You'll want to make sure long strings are hyphenated instead of stretching outside the bounds of the box there. You should be able to do this with CSS's [`word-wrap`](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap)

**Comment by tofumatt** [comment]
In this specific case it's a long string of dashes that should really be converted into an `<hr>`.

**Comment by muffinresearch** [comment]
> In this specific case it's a long string of dashes that should really be converted into an `<hr>`.

I think we should keep this simple for v1 and consider automatic conversation later if it's something that occurs in a lot of addon descriptions.

**Comment by tofumatt** [comment]
Amazingly, this seems to have been fixed when we moved to the updated card styles in #1423.

Closing as fixed; here's the screenshot on `master`:

<img width="396" alt="screenshot 2016-12-23 15 02 38" src="https://cloud.githubusercontent.com/assets/90871/21456577/f93bba34-c920-11e6-85eb-8e0b1423e69b.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix screenshot: 
![a1](https://cloud.githubusercontent.com/assets/15685960/22681194/9d086ef2-ed14-11e6-98af-2c91f8bd2b15.png)
