### ISSUE TITLE
Scrollbar on top of expanded image

### ISSUE THREAD

**Issue by madprops** [mozilla/addons-frontend#11922]
![scrolllbar](https://user-images.githubusercontent.com/206498/203153081-2ab8f457-9907-4a55-9ecb-1b502a0b3fd3.jpg)

The scrollbar of the thumbnails gets on top when I expand an image.

**Comment by bobsilverberg** [comment]
@madprops Can you provide some additional information about this issue? What is the URL on the web site where you noticed this issue? What browser and version are you using?

**Comment by madprops** [comment]
Firefox developer edition 108.0b3 (64-bit) (Linux)

Happens here:

https://addons.mozilla.org/en-US/firefox/addon/grasshopper-urls/

**Comment by madprops** [comment]
If I disable "widget.gtk.overlay-scrollbars.enabled"
The problem disappears

**Comment by diox** [comment]
This looks like a Firefox bug with linux and overlay scrollbars disabled. The scrollbar being seen corresponds to the underlying element with the thumbnails.

I'd suggest filing a Firefox bug for this, I don't think it's an AMO bug.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-109
