### ISSUE TITLE
'Unexpected error' raised when creating a new collection

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#11947]
### Describe the problem and steps to reproduce it:

1. Log in on AMO -dev
2. Create a new collection

### What happened?
"An unexpected error occurred" is raised 

### What did you expect to happen?
The collection is created successfully and the user lands on the collection detail page after submitting it. 

### Anything else we should know?
- if you go to the collections page after submission, you can see that the collection was actually created
- the API responds with a 201 when the collection is submitted, so this doesn't look like an API issue
- the issue is currently reproducing only on AMO dev

![image](https://user-images.githubusercontent.com/31961530/208067400-44c23486-5363-40aa-a8d2-4153d012dde1.png)

**Comment by diox** [comment]
```
Failed to CREATE_COLLECTION: TypeError: can't access property "results", addons is undefined
```

**Comment by AlexandraMoga** [comment]
I've verified this issue on AMO -dev and collections are created now without the unexpected error:

![firefox_YdhmebRh59](https://user-images.githubusercontent.com/31961530/208387269-387c6a20-7b5d-4053-a626-fde0f47d337f.gif)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-182
