### ISSUE TITLE
Implement suggestions reducer and saga

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11951]
This supports #11950, and is about implementing the reducer and saga logic needed to support the suggested add-ons.

**Comment by ioanarusiczki** [comment]
@bobsilverberg In case I can do some testing for this issue, let me know.

**Comment by bobsilverberg** [comment]
> @bobsilverberg In case I can do some testing for this issue, let me know.

Nothing specific to this, as it isn't being used yet, but a different patch, which does make use of the code in here, is expected to land before the next tag.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-184
