### ISSUE TITLE
Implement an AddonSuggestions component and display it via an experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11959]
This supports https://github.com/mozilla/addons-frontend/issues/11950, and is about implementing an `AddonSuggestions` component and displaying it on the add-on detail page via an experiment.

If the `variant` assigned to the user is `VARIANT_SHOW_TOP`, here is where the shelf will appear:

![Screen Shot 2023-01-13 at 11 47 20 AM](https://user-images.githubusercontent.com/142755/212374058-079ae903-3600-4402-9b2b-ec44f9819df1.png)

If the `variant` assigned to the user is `VARIANT_SHOW_MIDDLE`, here is where the shelf will appear:

![Screen Shot 2023-01-13 at 11 48 20 AM](https://user-images.githubusercontent.com/142755/212374268-edb4c71b-71a4-4cc6-884f-6ed8d1ff8807.png)

**Comment by diox** [comment]
Note that you can inspect (and change) which variant of the experiment you're on by manipulating cookies through the developer tools (in the Storage tab): the cookie `frontend_active_experiments` will have a value like `%7B%2220221130_amo_detail_category%22%3A%22show-suggestions-top%22%7D` which is really urlencoded json. Once decoded, you'll get:
```
{"20221130_amo_detail_category":"show-suggestions-top"}
```

You can change the value to `show-suggestions-top`, `show-suggestions-middle` or `hide-suggestions`, urlencode the value, stick it back into the cookie and reload to activate the other variants.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @diox 

At my first attempt I ran into hide-suggestions but then I manually changed the cookie to show-suggestions-top. I remember the section just appeared on top of the page. Then after I navigated away I could no longer see it displayed on any other detailed page.

So I went and created new profiles but this time even with cookie set to show-suggestions-top I could not see the section displayed. I tried with login thinking that cache could be the problem, but I still won't get the section displayed.

What I noticed is that the section is visible for a second at reload -> with cookie set to show-suggestions-top or show-suggestions-middle

![middle-experiment](https://user-images.githubusercontent.com/33448286/212701979-f4c66dee-60e7-4f85-9abd-572a77c7557c.gif)

**Comment by diox** [comment]
If the add-on you're testing with has multiple categories set, be careful as we only pick one of them to show suggestions. Which means we have internally an order of preference, defined here: https://github.com/mozilla/addons-frontend/blob/fba0fbd287be5462eefc131b388aa7a82d558f64/src/amo/components/AddonSuggestions/index.js#L65

It matters because if your add-on has a second category a category higher up in that list than the other but that we haven't created a collection for it, suggestions won't show up. The fact that we display and then quickly hide the box is a symptom of this (which shouldn't happen in prod where all collections have been created and populated).

**Comment by bobsilverberg** [comment]
> @bobsilverberg something I noticed while explaining this, that I didn't catch before: we're not consistent with the `collection` property in that list, sometimes including the author id and a slash, sometimes not. From a quick look I don't think it would work when the author id and slash is included ?

That was a copy/paste error on my part. The authorId and slash should not be there at all. I will file and issue and fix it.

**Comment by bobsilverberg** [comment]
@ioanarusiczki My apologies. I meant to include more detailed info on testing this feature, but it seems that @diox has provided what's needed. The main point is that the category that has been chosen for an add-on must also have the corresponding collection created, otherwise the shelf will be hidden. I only created one collection on dev for testing, which is the one for `alerts-updates`, but if you want to test add-ons with other categories, more collections will need to be created, and we will also need collections on stage as well.

Please let me know if you have any questions about this, or about any other aspect of testing this.

**Comment by bobsilverberg** [comment]
@ioanarusiczki One thing to note: this will not be active on stage, even after today's tag. We will activate it on stage after the push on Thursday. The plan is to activate it on prod with next week's push.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Thanks for letting me know. 

I started testing this after -dev was back and so far it looks good. but I'll continue testing , add all the possible collections, check the UX and so on.

**Comment by bobsilverberg** [comment]
@ioanarusiczki This is now enabled on stage

**Comment by ioanarusiczki** [comment]
I've been looking around a bit more on AMO dev:

1. As UX
- I've noticed that the recommended badge is not displayed in this shelf for addons that are recommended and added in a collection (probably it's expected)

- for language-support collection, the text overlaps a bit the See Firefox Staff  Pick url when I resize at ~700 px

![700px](https://user-images.githubusercontent.com/33448286/213715461-371d9733-6e71-4e4d-a140-3dfa5edcd20f.png)

- without the site notice, the shelf is close to the header with more space towards the next section below. -> it looks good to me but I don't know if it's expected to be more centered 

![top](https://user-images.githubusercontent.com/33448286/213715727-181bbabf-1bf4-4bf7-bca0-7398c19a612f.png)

- when it's at the middle, it's closer to the section above (same as for top)

![middle](https://user-images.githubusercontent.com/33448286/213715840-517799c3-93f3-4883-8657-8fe1a2bded16.png)

2. As functionality:

- once the collection is created with the slug from[ here](https://github.com/mozilla/addons-frontend/blob/fba0fbd287be5462eefc131b388aa7a82d558f64/src/amo/components/AddonSuggestions/index.js#L65) addons that have a category checked in dev hub , let's say privacy & security -> they display automatically the shelf (except when the cookie is set to suggestions-hide). The entire collection is displayed when "See Firefox Staff Picks" URL is clicked. 

- I did not encounter technical issues while adding/editing collections in admin. I added on dev all the possible collections. There's tabs and bookmarks in one collection. Same for shopping and other categories. 

- there's a categoryHierarchy which works as expected when an addon is part of 2 categories ( As @diox mentioned above. )

- in most of the cases the addon I'm seeing displayed is also visible in the shelf -> probably expected

![up on shelf](https://user-images.githubusercontent.com/33448286/213723070-836f0608-361d-440a-ab66-c57b61ce4d4a.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-188
