### ISSUE TITLE
Meta tag content attribute has HTML in it

### ISSUE THREAD

**Issue by mkaply** [mozilla/addons-frontend#11983]
### Describe the problem and steps to reproduce it:
I pasted the URL for the webcompat reporter (https://addons.mozilla.org/en-US/firefox/addon/webcompatcom-reporter/)  into Slack and got HTML in the result:

![image](https://user-images.githubusercontent.com/345868/212131652-2b744b37-70da-4280-bfed-c4b20eee3f34.png)

### What happened?

There was raw HTML in the result.

### What did you expect to happen?

Just the link, no HTML

### Anything else we should know?

Based on my reading of the content attribute spec, it's not allowed to have HTML.

**Comment by diox** [comment]
I agree, we should probably strip any HTML when rendering the meta tags.

**Comment by diox** [comment]
Thanks for filing that bug @mkaply, the fix will land in production next week.

**Comment by mkaply** [comment]
That was fast! Thanks!

**Comment by ioanarusiczki** [comment]
@diox 

On AMO dev:

I added as summary the text like this: `Adds a button to allow users to easily report site compatibility issues at <a href="https://webcompat.com/">webcompat.com</a>, for the active tab.` -> the html <a> tag is no longer present in the meta description tag if I check it with Inspector.

I also sent the url on slack:

![on slack](https://user-images.githubusercontent.com/33448286/212325784-bcae5659-6e6e-498b-8b07-ce6f42df236f.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-191
