### ISSUE TITLE
Implement pino-mozlog in this repo

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11985]
Take the code that currently exists in [`pino-mozlog`](https://github.com/mozilla/pino-mozlog), which generates an `npm` package, and move it into this repo so it is available as an internal utility as opposed to a public `npm` package.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I only assume , that's a qa not needed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-192
