### ISSUE TITLE
Improve "You need an updated version of Firefox for this extension" message for MV3 extensions

### ISSUE THREAD

**Issue by anewuser** [mozilla/addons-frontend#11987]
### Describe the problem and steps to reproduce it:

Use Firefox 108 to open the download page for a Manifest V3-only extension, for example: https://addons.mozilla.org/addon/youtube-volume-scroll/.

### What happened?

The page displays this message, even though I'm using the latest stable version: 

>You need an updated version of Firefox for this extension

### What did you expect to happen?

The message should explain that this extension will only work on future Firefox versions instead of suggesting me to update Firefox.

I know that Firefox 109 is going to be released in a few days, but this likely affects Firefox 102 ESR too, which will be supported until late August.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-193
