### ISSUE TITLE
Configure AMO to start sending data to GA4

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11992]
Our plan is to run GA4 in parallel with UA until such a time as UA is discontinued. We will need to make some decisions about what data to send to GA4, but as a starting point we should set up AMO so the default data (e.g., page views) is being sent to GA4. This issue is about doing that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I left here some results https://github.com/mozilla/addons-frontend/issues/12009#issuecomment-1406419184 

Let me know if there's anything else.

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> I left here some results [#12009 (comment)](https://github.com/mozilla/addons-frontend/issues/12009#issuecomment-1406419184)
> 
> Let me know if there's anything else.

Looks good, thanks @ioanarusiczki !

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-196
