### ISSUE TITLE
Make some UX tweaks to AddonSuggestions

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11999]
This is a follow-up to https://github.com/mozilla/addons-frontend/issues/11959.

1. Reduce the size of the gap at the bottom of the suggestions shelf when it is in the middle position:

![Screen Shot 2023-01-20 at 10 35 32 AM](https://user-images.githubusercontent.com/142755/213740737-39f4e167-1306-4719-9373-2cf2a972f212.png)

2. Fix the issue with squished header text at smaller screen sizes:

![Screen Shot 2023-01-20 at 10 58 22 AM](https://user-images.githubusercontent.com/142755/213745417-5d1a497d-e6dd-4d9a-bde3-330a0ea6cf1b.png)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-197
