### ISSUE TITLE
Enable suggested add-ons experiment on stage

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#11990]
Currently the experiment is only enabled on dev, but it would be good to have it on stage for this week's tag so more testing can be done before enabling it on prod next week.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I see it present on AMO stage too, I'll look around.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I created all collections on AMO stage. I did not notice other issues after testing on AMO dev https://github.com/mozilla/addons-frontend/issues/11959

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-195
