### ISSUE TITLE
Enable suggested add-ons experiment on prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#12006]
The experiment is meant to go live this week, so we need to update the config to enable it everywhere.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I looked around on AMO prod, (if I manually changed the cookie ) -> the shelves are displayed. looking good. 

I don't know what the percentage of the suggestions-top or suggestions-middle should be, but opening new FF profiles , I only got the hide-suggestions so far (on ~10 new profiles)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-198
