### ISSUE TITLE
Fix problem sending data to GA4

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#12009]
This is a follow-up to https://github.com/mozilla/addons-frontend/issues/11992.

There was a coding issue that was preventing the sending of data to GA4. I solved the problem and will use this issue to push a fix.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I navigated on many AMO dev pages -> for each page I've noticed:
- a 200 status with analytics.js as Initiator and somewhere in the headers a `tid:UA-36116321-7`
- a 204 status with .js as Initiator and `tid:G-B9CY1C9VBC` 

I think that's the expected.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-199
