### ISSUE TITLE
Send custom events to GA4

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#12012]
Our current, basic setup for GA4 includes all automatic events, which include page views and some interactions (clicks on external links, scroll actions, form actions), but does not include any of the custom events we are currently sending to UA.

Although we may choose to change some of these, change the way they are named, and change the parameters being sent, for now we can simply send the exact same events to GA4 to start collecting them. Also, having the current taxonomy in GA4 will help inform decisions moving forward about exactly how we want to collect and report on custom events in GA4.

This issue is just about sending all of the custom events we currently send to UA to GA4, without changing the names or parameters.

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've verified this issue on AMO stage by looking at the requests from an addon detail page and these are my results:

- for `analytics.js (xhr)` request:

[request URL where the `tid=UA-36116321-7` value is present]
```
POST https://www.google-analytics.com/j/collect?v=1&_v=j99&a=619833442&t=pageview&_s=1&dl=https://addons.allizom.org/en-US/firefox/addon/firefox-relay/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured&ul=en-us&de=UTF-8&dt=Firefox Relay – Get this Extension for 🦊 Firefox (en-US)&sd=24-bit&sr=1920x1080&vp=1903x530&je=0&_u=QACAAEABAAAAACAAI~&jid=823665145&gjid=2113963841&cid=348529429.1675255865&tid=UA-36116321-7&_gid=1123993593.1675255865&_r=1&z=2007189209
```

- for `analitics.js (beacon)` requests:

[request URL]
`POST https://www.google-analytics.com/collect`

[payload, where the `tid=UA-36116321-7` is present]
```
v=1&_v=j99&a=619833442&t=event&_s=2&dl=https%3A%2F%2Faddons.allizom.org%2Fen-US%2Ffirefox%2Faddon%2Ffirefox-relay%2F%3Futm_source%3Daddons.mozilla.org%26utm_medium%3Dreferral%26utm_content%3Dfeatured&ul=en-us&de=UTF-8&dt=Firefox%20Relay%20%E2%80%93%20Get%20this%20Extension%20for%20%F0%9F%A6%8A%20Firefox%20(en-US)&sd=24-bit&sr=1920x1080&vp=1903x530&je=0&ec=AMO%20Addon%20%2F%20Recommendations%20Shown&ea=recommended_fallback-no_results&el=private-relay-stage%40firefox.com&_u=QACAAEABAAAAACAAI~&jid=&gjid=&cid=348529429.1675255865&tid=UA-36116321-7&_gid=1123993593.1675255865&cd3=addons-frontend&cd8=20221130_amo_detail_category&cd9=show-suggestions-top&z=2063283083
```
- `js (beacon)` request:

[request where the `tid=G-B9CY1C9VBC` value is visible]
```
POST https://region1.google-analytics.com/g/collect?v=2&tid=G-B9CY1C9VBC&gtm=2oe1u0&_p=619833442&cid=348529429.1675255865&ul=en-us&sr=1920x1080&uaW=1&sid=1675255864&sct=1&seg=1&dl=https://addons.allizom.org/en-US/firefox/addon/firefox-relay/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured&dt=Firefox Relay – Get this Extension for 🦊 Firefox (en-US)&_s=1
```
Note that for this request, the `tid=G-B9CY1C9VBC` is not present in the payload, only in the request URL. 

Let me know if these are the results you also expected to see.

**Comment by bobsilverberg** [comment]
@AlexandraMoga Yes, that looks fine, thanks!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-200
