### ISSUE TITLE
Disable the add-on suggestions experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#12022]
The experiment will have been running for three weeks as of this week's push, so we should disable it for now. We can leave the code in place in case we decide we want to re-enable it after fully analyzing the data.

**Comment by AlexandraMoga** [comment]
I've verified that the experiment is disabled on -dev and stage. These are some more specific things I've noticed:

- the `frontend_active_experiments` cookie is not present on a new profile
- on older profiles where the cookie was present is now having the value `%7B%7D`
- if I'm trying to manually set the value to `%7B%2220221130_amo_detail_category%22%3A%22show-suggestions-top%22%7D` for example, the cookie will be reset back to `%7B%7D` when the page is refreshed
- the suggestions shelf is no longer visible on the detail pages and loading animations for the shelf are also not present

I'm marking this issue as verified fixed.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-202
