### ISSUE TITLE
Show MV3 host permissions

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12038]
This needs https://github.com/mozilla/addons-server/issues/20418 first but once the MV3 `host_permissions` field is exposed, we should show these permissions on the detail page of an add-on. Host permissions are optional in Firefox, and not granted by default.

As such, host permissions should be displayed in the second section of the permissions card (with the other optional permissions): https://github.com/mozilla/addons-frontend/blob/ab4c872e88af09b002273d79e09b62a45740164a/src/amo/components/PermissionsCard/index.js#L91-L100

It's also going to require some changes here to add the MV3 host permissions to the list of optional permissions: https://github.com/mozilla/addons-frontend/blob/ab4c872e88af09b002273d79e09b62a45740164a/src/amo/components/PermissionsCard/permissions.js#L80

Just like MV2, MV3 also has mandatory "API" `permissions` as well as optional "API" permissions in `optional_permissions`. For an MV2 add-on, the changes above wouldn't change anything (since the `host_permissions` manifest key isn't supported in MV2).

For an MV3 add-on, that would allow all permissions to be shown, which isn't currently the case.

**Comment by bobsilverberg** [comment]
@willdurand Just checking to see if product and/or UX were consulted on this. I'm happy to make this change, but want to make sure this is exactly how we want these new permissions exposed.

**Comment by willdurand** [comment]
UX didn't get back to me. OTOH this is a simple change that only shows missing information, we would need UX if we wanted to go fancier but not showing all the permissions for MV3 add-ons isn't great at the moment..

**Comment by willdurand** [comment]
> UX didn't get back to me. [...]

Scratch that, got r+ on slack

**Comment by bobsilverberg** [comment]
We currently deduplicate host permissions, so, for example, if an extension had these permissions:

```
[
     'https://*.okta.com/a',
     'https://*.okta.com/b',
]
```

we simply display "Access your data for sites in the okta.com domain".

What if an extension has both a `permission` for `https://*.okta.com/a` and also a `host_permission` for `https://*.okta.com/b`? Should we end up showing that message ("Access your data for sites in the okta.com domain") twice, once under "This add-on needs to:", and again under "This add-on may also ask to:", or would it make sense to fully deduplicate and only show that message under "This add-on needs to:", because that basically covers the second case as well?

**Comment by bobsilverberg** [comment]
Of course now that I've asked that, and looked at the code, it's actually going to require changes to the way the components are designed to be able to deduplicate across required and optional, because as it currently stands, neither knows anything about the other, and the host permissions get turned into readable text. It's certainly doable, but much simpler to keep them separate and show both messages if a domain is used in both required and optional permissions.

**Comment by willdurand** [comment]
> much simpler to keep them separate and show both messages if a domain is used in both required and optional permissions.

I'd agree with that.

That makes me think.. how are unsupported permissions handled at the moment? Theoretically, a host permission should never be included in `permissions` when we also have `host_permissions` but the linter only emits a warning (Firefox would do the same). But now, what if there is a Chrome permission in `permissions`, e.g. `"background"` (which we don't support in Firefox)?

**Comment by willdurand** [comment]
Replying to myself, it looks like we only display what we explicitly support. In fact, we should probably update some strings as described in https://github.com/mozilla/addons-frontend/blob/5ab36e3624bafb9df5e909ded027495c3222c588/src/amo/components/PermissionsCard/permissions.js#L24, we have some new permissions now.

As for the host permissions in `permissions` for MV3 add-ons (only), ideally we'd hide them in the first section because they will be ignored. If this is complicated, I think it's fine to not do this for now, but we should file an issue to address that eventually.

**Comment by bobsilverberg** [comment]
> Replying to myself, it looks like we only display what we explicitly support. In fact, we should probably update some strings as described in
> 
> https://github.com/mozilla/addons-frontend/blob/5ab36e3624bafb9df5e909ded027495c3222c588/src/amo/components/PermissionsCard/permissions.js#L24
> , we have some new permissions now.
> 

Thanks. I will file a separate issue for that.

> As for the host permissions in `permissions` for MV3 add-ons (only), ideally we'd hide them in the first section because they will be ignored. If this is complicated, I think it's fine to not do this for now, but we should file an issue to address that eventually.

Thanks, I will file an issue for that as well.

**Comment by willdurand** [comment]
> but now host_permissions are returned separately for mv2 too since [mozilla/addons-server#20418](https://github.com/mozilla/addons-server/issues/20418)

That looks like a bug in fact. `host_permissions` is only valid on Firefox for MV3+ but we don't emit errors on invalid top-level manifest keys so it is possible that MV2 add-ons declare `host_permissions`. In this case, we should ignore this key.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-209
