### ISSUE TITLE
User Menu is not responsive while displayed between dev hub and search bar

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12033]
Followup for https://github.com/mozilla/addons-frontend/issues/11824#issuecomment-1436521898

1. Resize the screen until user's display name is between Developer Hub and the Search Bar

2. Hover over the name

Expected result:
User Menu should be displayed 

Actual result:
User Menu is not available

This is reproducible on dev and stage (it's more obvious after the fix for https://github.com/mozilla/addons-frontend/issues/11824)

![user menu](https://user-images.githubusercontent.com/33448286/220917812-2d52ac85-7e18-4092-86ac-e21feeaf6a85.gif)

**Comment by Gaurab4** [comment]
Hey, I would like to work on this

**Comment by karthiknadar1204** [comment]
@ioanarusiczki ,if this issue is still open,please assign it to me,i would like to work on it

**Comment by ioanarusiczki** [comment]
@karthiknadar1204 I'll CC @diox

**Comment by GregSherman** [comment]
Fixed issue prematurely, commenting for assignment

**Comment by karthiknadar1204** [comment]
@GregSherman could you guide me with setting up the project on the local machine,i am working on another issue in the same project but I am unable to understand the set up commands,what is flow and all. Could you please help me with it

**Comment by ioanarusiczki** [comment]
@eviljeff I see this landed on -dev and lgtm. 

![fixed on dev](https://github.com/mozilla/addons-frontend/assets/33448286/308bb056-4475-4c4b-a57a-398abcca786f)

**Comment by eviljeff** [comment]
@karthiknadar1204 
> could you guide me with setting up the project on the local machine,i am working on another issue in the same project but I am unable to understand the set up commands,what is flow and all. Could you please help me with it

come speak to us on https://chat.mozilla.org/#/room/#amo:mozilla.org - it's not practical to debug set up problems via github.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-207
