### ISSUE TITLE
Escape error messages returned by API calls

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#12040]
We should run error messages returned by API calls through `DOMPurify` in case they contain user-specified data.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I tried to trigger all possible error messages on frontend with ratings, abuse reports, collections, user profile -> I did not see anything unusual on AMO Dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-210
