### ISSUE TITLE
Update permission strings

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#12044]
As mentioned at [here](https://github.com/mozilla/addons-frontend/issues/12038#issuecomment-1461687840), the [permission strings](https://github.com/mozilla/addons-frontend/blob/5ab36e3624bafb9df5e909ded027495c3222c588/src/amo/components/PermissionsCard/permissions.js#L24) that are meant to be kept in sync between Firefox and AMO need to be updated.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I submitted an addon for all permissions from [here](https://github.com/mozilla/addons-frontend/blob/5ab36e3624bafb9df5e909ded027495c3222c588/src/amo/components/PermissionsCard/permissions.js#L24) 

Looks good to me https://addons-dev.allizom.org/en-US/firefox/addon/all-permissions_strings/

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-211
