### ISSUE TITLE
Fix smoke test broken since addons-server Dockerfile merge

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12053]
We have [a very barebones smoke test in addons-frontend](https://github.com/mozilla/addons-frontend/tree/master/tests/smoke) that uses addons-server docker-compose setup to load the homepage of a freshly built addons-frontend image. We run that on `master` and tags.

https://github.com/mozilla/addons-server/issues/20472 broke it. IMHO the value of this test is questionable as it only proves addons-frontend image works in the addons-server development environment, but still it's breaking the build now so it should be fixed or removed.

**Comment by ioanarusiczki** [comment]
@diox That's without qa not needed but I assume it can be marked?

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-213
