### ISSUE TITLE
Use inline SVG for header so we can style it

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1207]
As discussed here: https://github.com/mozilla/addons-frontend/pull/1194#discussion_r82698882

**Comment by kumar303** [comment]
There might be some trade-offs with including an in-line SVG that we'll need to consider

**Comment by muffinresearch** [comment]
@tofumatt do we still need this one?

**Comment by tofumatt** [comment]
Not for the header but as a general rule yes. We should be smarter about SVGs and there are places (like pagination links) we use coloured SVGs that cannot be styled but would be better if we could CSS style them.

The particular use-case outlined in the original issue text doesn't apply, but this is still worth doing.

**Comment by muffinresearch** [comment]
We are using masks more now, which negates some of this. We can move to that more fully when we get away from ESR being at 52 which only has partial mask support. I think on the basis this bug isn't very targetted any more we can close it.
