### ISSUE TITLE
Pass add-on hash into mozAddonsManager

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#1208]
Please see https://bugzilla.mozilla.org/show_bug.cgi?id=1308261 for more.

**Comment by muffinresearch** [comment]
The API data for the disco pane provides the sha so we just need to start passing the SHA to the API. 

This will also need to be implemented for AMO too but hopefully most of the code will be shared in any case.

The args are passed as an object to `window.navigator.mozAddonManager.createInstall()` so assuming the method doesn't complain about unexpected props we can just implement this now and it will continue to work in the versions before 50.

**Comment by muffinresearch** [comment]
@willdurand was this done as part of the mozAddonManager button re-implementation?

**Comment by willdurand** [comment]
I have to check but I am not sure, I reused some existing code that wraps the mozAddonManager.

**Comment by willdurand** [comment]
> @willdurand was this done as part of the mozAddonManager button re-implementation?

so no, it was not implemented. I am going to add it.

**Comment by ioanarusiczki** [comment]
@willdurand I assume the mozAddonsManager install buttons on AMO dev and Disco Pane -dev should be re-checked?

**Comment by willdurand** [comment]
@ioanarusiczki right, installs should work just like before.

**Comment by ioanarusiczki** [comment]
Tested it with extensions, lw themes and static themes - install works as expected.
Verified fixed with AMO dev - FF64 (Win10).
