### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by kplotnik** [mozilla/addons-frontend#12112]
There are 7 pull requests from the dependabot.

**Comment by diox** [comment]
Of those:
- https://github.com/mozilla/addons-frontend/pull/11982 is blocked until we switch to ESM
- https://github.com/mozilla/addons-frontend/pull/11994 needs to be investigated
- https://github.com/mozilla/addons-frontend/pull/11995 is blocked until we switch to react-router v6, which is a non-trivial change we decided against for now, so I've closed it.
- https://github.com/mozilla/addons-frontend/pull/12069 is a flow update, which should probably be closed as we have decided not to invest more into flow for the moment (maybe switch to TypeScript in the future)
- https://github.com/mozilla/addons-frontend/pull/12078 needs some testing
- https://github.com/mozilla/addons-frontend/pull/12082 needs to be investigated
- https://github.com/mozilla/addons-frontend/pull/12106 needs some testing

**Comment by diox** [comment]
Closing since the 2 remaining ones are blocked

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-214
