### ISSUE TITLE
The Flagged review confirmation menu is not displayed after a Flag is submitted

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#12122]
### Describe the problem and steps to reproduce it:

1. Open an add-on review page that has some written reviews - https://addons-dev.allizom.org/en-US/firefox/addon/moonlight-breeze/reviews/
2. Flag a review

### What happened?
The Flagged review confirmation menu is not displayed after the flag is submitted 

### What did you expect to happen?
A confirmation menu is displayed after a Flag is submitted 

### Anything else we should know?
- the issue is currently reproducing only on -dev
- in the -dev vs stage comparison, you can see that on -dev the user review card expands when clicking on Flag; this behavior is not visible on stage

[dev]
![firefox_gqzoddK3Xd](https://user-images.githubusercontent.com/31961530/231131877-b703f724-cb61-49c1-98d2-50173e0f733f.gif)

[stage]
![firefox_40SaaxxTx4](https://user-images.githubusercontent.com/31961530/231133637-dced4149-497a-40c8-b175-d56810e493ec.gif)

**Comment by AlexandraMoga** [comment]
The issue is fixed now on -dev. 

![firefox_66Z7v8s47g](https://user-images.githubusercontent.com/31961530/231415833-c720952a-b947-4772-8e2b-6ea0f463ae4a.gif)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-216
