### ISSUE TITLE
Implement a nice search result loading placeholder component

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1219]
Instead of showing "Searching..." while we request and load more search results, we should show at least a spinner, but I think it'd be quite nice if we took a page out of the kind of wireframe-with-no-content loading screens on things like Facebook. The search result styles are consistent, so a nice animation with their boxes would make the loading screen possibly feel faster, if I'm making any sense.

**Comment by muffinresearch** [comment]
One of the things that was mentioned at Fronteers was an experiment that Viget carried out [1] that customised loading indicators tend to have a better perception than generic ones. It's worth noting the sample data was pretty small but it's an interesting idea in any case.

[1] https://www.viget.com/articles/experiments-in-loading-how-long-will-you-wait

**Comment by tofumatt** [comment]
That makes sense. I was actually thinking that'd I'd *love* if we used the add-on fox logo animating in a way for a loading graphic, paging @pwalm for thoughts.

I saw some UX talks and read posts about using skeleton layouts increased *perceived* load times even when they're the same. Can't cite sources though, so you win 😉

**Comment by pwalm** [comment]
The icon could start out diagonally (so it looks like a fox), spin around twice really quickly and end up back at its original starting point. It would pause for .5 secs and then start again.

Similar to the "Follow through and overlapping" animation style in [this video](https://vimeo.com/93206523) (0:59). Not moving side to side like the animation shown, but spinning with a bit of a wobble at the end, like it's being stopped by something.

**Comment by pwalm** [comment]
Oh and icon would be 48x48px and #ced4da

**Comment by Ryuno-Ki** [comment]
I can imagine you've read an article on SitePoint on [how to speed up UX with Skeleton Screens](https://www.sitepoint.com/how-to-speed-up-your-ux-with-skeleton-screens/).

https://github.com/ksux/ks-design-guide/issues/38 researched some more links.

I even found [a CodePen for it](https://codepen.io/oslego/pen/XdvWmd).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (Android 6.0.1)
A placeholder was added while navigating through AMO mobile.
Postfix video: 
![videotogif_2017 03 06_11 06 45](https://cloud.githubusercontent.com/assets/15685960/23603333/6cfdf200-025d-11e7-95c5-fef478a38d8d.gif)

**Comment by ValentinaPC** [comment]
The placeholder is no longer present after entering a search term or navigating through search results.
@tofumatt : do you know something about this?

Please see video from AMO-prod FF53 (Android 6.0.1)
![videotogif_2017 05 12_12 12 42](https://cloud.githubusercontent.com/assets/15685960/25991656/acf7fc28-370c-11e7-8ebd-03254512eb99.gif)

**Comment by tofumatt** [comment]
We've moved to a loading bar and removed the placeholder. In the future we'll actually have a better loading indicator similar to:

![may-05-2017 14-40-30](https://cloud.githubusercontent.com/assets/90871/25747988/5fd8ee04-31a1-11e7-9933-06431afaad1b.gif)

But yes for now it missing I think is intended.
