### ISSUE TITLE
Remove husky pre-commit

### ISSUE THREAD

**Issue by GregSherman** [mozilla/addons-frontend#12202]
### Describe the problem and steps to reproduce it:

For many users on MacOS, they are unable to commit and push work due to a PATH issue despite flow existing in the PATH.

On MacOS, make changes to the code and attempt to commit work.

### What happened?
An error occurs:
```
.husky/pre-commit: line 4: flow: command not found
husky - pre-commit hook exited with code 127 (error)
husky - command not found in PATH=/opt/homebrew/Cellar/git/2.40.1/libexec/git-core:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.11/bin
```
### What did you expect to happen?
Pre-commit hook would run to check for linting and flow errors.

### Anything else we should know?

Remove the pre-commit hook entirely and rely on CI for enforcement.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-219
