### ISSUE TITLE
Travis builds/UI tests are broken with CircleCI Docker builds

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1221]
Since 411ac2c70f6c5ce5e80382ce7705a3a53622f739 the tests on Travis are broken, which makes it hard to ensure the PR checks out.

@davehunt mentioned the error `docker: Error parsing reference: "/bin/sh" is not a valid repository/tag` in the logs.

Could we figure out which CI we're using and make sure it passes? I'm a bit confused at this point.

**Comment by muffinresearch** [comment]
This should get fixed by https://github.com/mozilla/addons-frontend/pull/1222

**Comment by tofumatt** [comment]
#1222 merged though and that seems to be when it started happening, so I'm confused.

**Comment by muffinresearch** [comment]
> #1222 merged though and that seems to be when it started happening, so I'm confused.

#1202 was when it started afaict
