### ISSUE TITLE
Server error when trying to access some pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#12227]
### Describe the problem and steps to reproduce it:
1. Open the following extension category pages on stage:
- https://addons.allizom.org/en-US/firefox/extensions/category/games-entertainment/
- https://addons.allizom.org/en-US/firefox/extensions/category/language-support/
2. Open the following theme detail page on -dev:
- https://addons-dev.allizom.org/en-US/firefox/addon/full-moon-kitty/
- https://addons-dev.allizom.org/en-US/firefox/addon/pacific/

### What happened?
A server error page is displayed
![image](https://github.com/mozilla/addons-frontend/assets/31961530/1badb193-8703-468f-88cb-48e25525ee01)

### What did you expect to happen?
The expected pages are opened

### Anything else we should know?
This issue started occurring today (tests that run overnight caught the issue for the first time)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-222
