### ISSUE TITLE
Support blocklist changes to have an explicit set of blocked versions, rather than a min and max range

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12252]
Once all the work for https://github.com/mozilla/addons-server/issues/20748 has landed there won't a min and max version for each guid that is blocked, and that's what we currently expose on the block page.   A side effect of this is there isn't a concept of a `0 - *` block, like most blocks are currently - every block is for a finite and defined number of versions, and the add-on would just be disabled if we didn't want to developer to upload new versions that would be outside of that defined list.

At the most basic we can just display a list of every version number that is blocked for that guid.  If we want to expose something different than that, let's define it.  

cc @wagnerand @kplotnik (@diox)

p.s. the shim for `min_version` and `max_version` for backwards compatibility would be to show the lowest version in list of blocked versions as the min, and the highest of the max, though this is going to be wrong for non-continuous ranges of versions.

**Comment by wagnerand** [comment]
The latter sounds fine with me.

**Comment by eviljeff** [comment]
Filed https://github.com/mozilla/addons-server/issues/20857 for the server side changes needed

**Comment by eviljeff** [comment]
> If not all versions are blocked, would the list of blocked versions include self-hosted versions?

All version numbers, yes.  (Though I guess it wouldn't be apparent if a version number shown but not in the list of versions on the detail page was self-hosted or just disabled/deleted after signing).

**Comment by eviljeff** [comment]
> If not all versions are blocked, would the list of blocked versions include self-hosted versions?

btw, the implementation right now is the list of blocked version is always sent in the api response, regardless of if those blocked versions represent all versions or not - but I suppose frontend wouldn't need to expose them on the page.  We can also change the api response if necessary.

**Comment by ioanarusiczki** [comment]
@eviljeff 

What works as expected: 

- blocked version, add-on not force-disabled https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B91ed242d-5635-46c6-b3da-35ffbfb8a12b%7D/
- all versions blocked, add-on force-disabled https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B9403a2ba-e2cc-40c7-8493-22f2fd9cca16%7D/

This should be expected:
- only a couple of versions are blocked, the add-on was force-disabled when creating the blocks: https://addons-dev.allizom.org/en-US/firefox/blocked-addon/@contain-facebook/  -> all versions that have been blocked no matter of their state, even unreviewed , unlisted or deleted are available in the frontend page. 

When unblocking versions: 

- [an unlisted ](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625745) has one version unblocked. [Frontend page](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B266bb06f-7869-47fb-ab5b-0bf0b241b9ea%7D/) displays Versions blocked: all versions.

- an addon with 2 listed versions blocked then unblocked at the same time. I can still view the [block page ](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B7eda1a0a-75a3-4f5b-8ddd-f69efbb2514c%7D/)-> it should throw a 404 instead.  Another example, [this page](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7Ba261fbaa-4e7f-40d0-8f3d-203d5f91131f%7D/). I un-blocked one version and content was updated correctly to Versions blocked: 1.0, then I un-blocked the other ->  now it should throw a 404. 

- I also have a case when it's throwing a 404 after un-blocking all 3 versions. https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B8bf605e5-d9c2-41d8-8d81-c20db710be4e%7D/ -> which should be the expected

Other notes:

- The last reason from [block history](https://addons-internal.dev.mozaws.net/en-US/admin/models/blocklist/block/26329/change/) is available in ["Why was it blocked?"](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/@contain-facebook/) section together with the last edited [URL](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B102e8870-fb45-4f1b-8bef-9e0ddca7f7fe%7D/) but I assume that's expected.

**Comment by eviljeff** [comment]
Frontend (and the api) should be returning what the status of the `Block` instance is - which can be seen in /admin.  It's not clear to me from the testing comments if the admin is correct (in which case it is indeed a frontend problem and we should reopen this issue); or the model instances in the admin aren't as expected after the blocking and unblocking actions taken (i.e. there are bugs in server code)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Pages I said won't throw a 404 -> all throw a 404 today, so maybe I had to wait a while, probably it's from cache. 

I tried again for 2 unlisted blocked versions to unblock one of them, and checking the frontend pages , they both look the way it's expected 
https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B66b0548b-f4ec-4e71-b2b0-16fcded1f1c5%7D/
or https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B13a9ab4d-8199-47db-86c1-0c1b8d10ce7a%7D/

so I can't explain why [this](https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-unlisted/625745) continues to display all versions blocked on the [frontend page.](https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B266bb06f-7869-47fb-ab5b-0bf0b241b9ea%7D/)

**Comment by ioanarusiczki** [comment]
@eviljeff 

I force-enabled and submitted a new version, after approval the block page was updated -> only the blocked version is displayed 
https://addons-dev.allizom.org/en-US/firefox/blocked-addon/%7B266bb06f-7869-47fb-ab5b-0bf0b241b9ea%7D/

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-224
