### ISSUE TITLE
Simplify Paginator links

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1226]
Once the style updates in https://github.com/mozilla/addons-frontend/pull/1223 land we should look at simplifying the Paginator links.

The links are currently created in the `makeLink()` method that does some checks and creates a `<span>` or a `<Link>` based on it being active or not. This could be simplified by using the `activeClassName` prop of `Link`.

``` jsx
<Link
  to={{ ...this.url, query: { ...this.url.query, page: currentPage + 1 } }}
  className="Paginator-link Paginator-link--next"
  activeClass="Paginator-link--active"
>{i18n.gettext('Next')</Link>
```

**Comment by muffinresearch** [comment]
Fixed

**Comment by kumar303** [comment]
We have a [<PaginatorLink>](https://github.com/mozilla/addons-frontend/pull/2055/files#diff-3c78bf6785502ddd7d66bf11a64192c3R102) component now
