### ISSUE TITLE
Should pagination stay left-to-right in RTL?

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1231]
See our discussion here for context: https://github.com/mozilla/addons-frontend/pull/1223#discussion_r83313187

Right now the pagination changes Next and Previous around in RTL, but should they be swapped or should we keep Next on the right? @mstriemer points out that Google in Hebrew keep things in the same spots between LTR and RTL.

Paging @designakt for thoughts.

**Comment by tofumatt** [comment]
Just chatted with @sarahmonster about RTL randomly at breakfast and she mentioned that was an oddness of RTL for her as well. eg seems we should keep "Next" on the right for RTL. I'll do a quick PR.

**Comment by muffinresearch** [comment]
I was curious and looking around Yahoo does invert the direction where as @mstriemer noted Google doesn't.

<img alt="foo_-_yahoo_maktoob_ _ _-__private_browsing_" src="https://cloud.githubusercontent.com/assets/1514/19387397/d58c97fc-9211-11e6-8071-77cd45614f73.png">

Maybe some of the recent contributors of RTL fixes on addons-server or l10ners might have some insights on what they think is the most expected approach?

Another consideration is if we'd automated an RTL stylesheet with something like http:/rtlcss.com/ what would we have ended up with?

**Comment by atiqueahmedziad** [comment]
In [Google Hebrew](https://www.google.co.il/) , going to 2nd page of the search results, the left link is working as next button(taking me to next page) and the right link is working as previous button(taking me to previous page) . So, I think pagination should **not** be consistent in both LTR and RTL. That means the next button should be in left side and the previous button should be in right side.
![screenshot](http://i.imgur.com/cxEjOJt.jpg)

**Comment by designakt** [comment]
I too think pagination navigation should be mirrored. Most sites I checked mirror it.

**Comment by tofumatt** [comment]
Cool, I have closed the PR and will close this. Thanks for your help @atiqueahmedziad and @designakt!

**Comment by Kelele-m3** [comment]
I have been working with such kind of issue recently, at first it was confusing, but I agree with @designakt, the pagination should be mirrored. not only the icons but also their respective function.
