### ISSUE TITLE
old date still shown after deleting a comment and adding a new one

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-frontend#12345]
### Describe the problem and steps to reproduce it:

1. As a developer of an add-on answer to a review
2. After some time delete you answer
3. Write a new answer

### What happened?

The answer has the date from the deleted answer.

### What did you expect to happen?

The answer should have the current date.

### Anything else we should know?

Maybe related to #2043? But note that this issue is NOT about using the edit feature.

**Comment by eviljeff** [comment]
> Maybe related to #2043? But note that this issue is NOT about using the edit feature.

It's the same cause as #2043 - when you delete a rating it's not immediately deleted in the database (it's just marked as deleted), so if a new rating is submitted it just edits the existing rating and marks it not deleted.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-228
