### ISSUE TITLE
Remove `restrictSearchResultsToAppVersion` config and related code

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12379]
addons-frontend has a configuration variable, `restrictSearchResultsToAppVersion`, that governs whether or not it will restrict search results to add-ons compatible with the browser version or not.

That config was intended to make local development easier but it's more confusing than not, it potentially hides bugs that would only be occurring if you add a custom compatibility check elsewhere like the one we might need for non-Firefox browsers in https://github.com/mozilla/addons-frontend/issues/12372.

Nowadays we don't have legacy add-ons, dev has fewer weird add-ons than before (and plenty of "modern" add-ons) so we don't need to keep that config. Let's remove it completely and always show only compatible add-ons to Firefox browsers.

**Comment by ioanarusiczki** [comment]
@diox I'll add a qa not needed since it's local dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-230
