### ISSUE TITLE
Rename Firefox Accounts to Mozilla Accounts everywhere (frontend)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12407]
part of https://mozilla-hub.atlassian.net/browse/AOP-119

similar to mozilla/addons-server#21161 the current plan is to have the new strings with a date condition around them, so at the scheduled release datetime we switch automatically to the new branding without having to co-ordinate a one-off push.

(A follow-up would be to remove the old strings and the datetime logic)

The only place we mention Firefox accounts is the profile edit page.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-232)

**Comment by eviljeff** [comment]
In addition to the branding switching around, we should have some messaging about the change on the edit profile page too (ideally dismissible, but I don't think that's a hard requirement)

**Comment by ioanarusiczki** [comment]
@eviljeff Let me know when to test this, currently on  Edit profile page on -dev I see the old "Manage Firefox Accounts" URL 
and no banner.

On fxA side there is a banner - at login and on the account's settings page.

**Comment by eviljeff** [comment]
@ioanarusiczki This can be tested now.  The date is currently [set to 1st October](https://github.com/mozilla/addons-frontend/blob/f489f756ad16c9750c9f1dd562fb4160a7f0f5a9/src/amo/utils/fxa.js#L3) so the future state (Mozilla accounts) can be validated.  After you've given the okay we'll land a patch to correct the date to 1st November.

**Comment by alexandruschek** [comment]
Hello @eviljeff ,

I'm ready to test the changes. Please let me know when they're on -dev.

Thank you!

**Comment by eviljeff** [comment]
> I'm ready to test the changes. Please let me know when they're on -dev.

They're on -dev already.  I misread the date though - it's set to 1st November so right now it's in the current state where it should still say Firefox accounts, with the banner in https://github.com/mozilla/addons-frontend/issues/12469

then see https://github.com/mozilla/addons-frontend/issues/12407#issuecomment-1770365797

**Comment by ioanarusiczki** [comment]
@eviljeff 

The banner is displayed only on Edit profile page. Learn More redirects to https://support.mozilla.org/en-US/kb/firefox-accounts-renamed-mozilla-accounts

Managed Firefox Accounts is available below the email address fields which stays like that until Nov 1st (if I'm understanding this right)

I've verified the banner on Win10 and Android 

![banner is displayed](https://github.com/mozilla/addons-frontend/assets/33448286/a039ef33-f23f-4205-8637-2a8040f7d681)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Right now on AMO dev:

![Mozilla Accounts](https://github.com/mozilla/addons-frontend/assets/33448286/fbccaa7f-297e-4978-b049-cac2917e07e6)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-232
