### ISSUE TITLE
Remove the `enableFeatureMoreAndroidExtensions` flag once it is enabled everywhere

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12401]
In https://github.com/mozilla/addons-frontend/issues/12372, we'll add a new feature flag named `enableFeatureMoreAndroidExtensions`. Once this is enabled everywhere, we should remove the flag and clean up the code to simplify it.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-231)

**Comment by ioanarusiczki** [comment]
@willdurand regression on feedback form?

**Comment by ioanarusiczki** [comment]
@willdurand I'll look over the homepage, the 2 enabled shelves and some search results.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good on -dev. I verified with Fenix 119.1.1 and 121.0a1

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-231
