### ISSUE TITLE
Handle categories with no application

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12414]
At the moment, all categories have an application assigned to them. We have a set of categories for extensions for Firefox Desktop, and another for Firefox for Android. The API reflects this: the [categories list endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/categories.html#category-list) returns an `application` field for each category, and add-ons have a `categories` object with keys being application names, values being a list of category slugs for each application. addons-frontend code mimics this in its internal data structures.

When unifying categories in https://github.com/mozilla/addons-server/issues/5989 this will need to change. Only current categories for Firefox will stay, categories will no longer have a specific application attached, the API will stop returning the `application` field and add-ons will just expose a flat list. 

addons-frontend needs to prepare for that:

- When we load the categories list:
    - Allow the `application` field to be absent. If it's present though, only record the category if marked for `firefox`, ignore anything else.
    - Stop storing categories per app, store globally
- When we load categories for an add-on:
    - Cope with object and flat list format. Only use categories for `firefox` if dealing with the object format.

We intend to ship addons-server and addons-frontend at the same time, but we need to make sure we don't error out with old API data.

**Comment by GregSherman** [comment]
assignment comment

**Comment by ioanarusiczki** [comment]
@diox Looks good, I tried on the URLs that had the error and also submitted a new addon with Android compatibility (without Firefox).  For all cases, the error is gone.

**Comment by ioanarusiczki** [comment]
@diox 

I didn't find other regressions while checking -stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-233
