### ISSUE TITLE
Finding non-recommended extensions on Android is difficult

### ISSUE THREAD

**Issue by evilpie** [mozilla/addons-frontend#12436]
### Describe the problem and steps to reproduce it:

Go to http://addons.mozilla.org on Firefox for Android (Nightly)

### What happened?

There is a search bar and a list of recommended extensions.
I can click on "See more recommended extensions" to see 17 extensions in total.
It's not obvious what other extensions exists.

### What did you expect to happen?
On Desktop there are multiple categories with many more extensions to choose from. It would be good to have different lists on Android as well. Or maybe just a link to all extensions.

### Anything else we should know?

I do realize that I can click on "Filter results" and "Badging" to see all extensions. At least the term "badging" seems non obvious to me.
If this ships I think a lot people will be disappointed because they assume Firefox for Android still has a very limited list of extensions.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-235)

**Comment by diox** [comment]
https://github.com/mozilla/addons-frontend/issues/12523 (goes in production later this week) should help with that - it adds a second shelf of the homepage with "Trending" extensions that are not necessarily recommended. Clicking the link to see more will show the full list, and users will be able to sort differently if they want, or search from there.

(categories might happen later, but not for now)
