### ISSUE TITLE
Create banner for MzA change, followup to #12407

### ISSUE THREAD

**Issue by GregSherman** [mozilla/addons-frontend#12469]
There should be a banner at the top that states this. Also when the time passes, the banner should turn past tense.

![image](https://github.com/mozilla/addons-frontend/assets/63402349/70699ba4-a6b7-4295-b3d1-775da3749b93)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-239)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-239
