### ISSUE TITLE
Expose details about the add-on on the feedback form

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12478]
When a feedback form is launched for a particular guid we should show the add-on name for a publicly available add-on, and the add-on GUID otherwise.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-243)

**Comment by ioanarusiczki** [comment]
@willdurand 

I verified this on AMO dev:

- only public listed add-ons have the Name, author, number of users and ratings 

- for unlisted, invisible, disabled by developer, disabled by Mozilla (rejected, blocked), awaiting review or deleted versions/add-ons. The guid is required and that's all it's going to be displayed in the header. Feedback can be sent using the guids, it won't work with the internal amo id or slugs (which I believe it is expected).

**Comment by willdurand** [comment]
> * Feedback can be sent using the guids, it won't work with the internal amo id or slugs (which I believe it is expected).

is this a general comment or only for unlisted add-ons?

**Comment by ioanarusiczki** [comment]
@willdurand 

It's for all : unlisted + the rest of the scenarios invisible, disabled by developer, disabled by Mozilla (rejected, blocked), awaiting review or deleted versions/add-ons 

For example: I am on the form of a listed add-on but the developer makes it invisible or disabled the version. If I refresh the page automatically the metadata is replaced by the add-ons guid. This is applicable for the rest of the scenarios (disabled by Mozilla or deleted)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-243
