### ISSUE TITLE
Add location field to (addon) feedback form

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12476]
We want to capture if the content being reported to us is in the add-on itself, or on the listing page.  This will depend on an API change to capture this information.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-241)

**Comment by ioanarusiczki** [comment]
@eviljeff 

Checked https://github.com/mozilla/addons-frontend/issues/12432#issuecomment-1782777611 and re-checked today sending it with the Abuse Report API, worked with all 3 options. 

Also checked the Admin[ field ](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/26929/change/). 

I forgot to ask last week, I've noticed on Android once the form is sent -> this is the landing area for a phone, to see the message the user must scroll up 

![landing area after sending the form](https://github.com/mozilla/addons-frontend/assets/33448286/2f708100-0090-45bb-a44c-6bbb951160da)

In case I should file an issue , let me know.

**Comment by eviljeff** [comment]
@ioanarusiczki can we have an issue for the android scrolling bug please?  I'd be low priority but seems like a paper cut worth fixing at some point.

**Comment by ioanarusiczki** [comment]
@eviljeff 

I filed https://github.com/mozilla/addons-frontend/issues/12520

Initially I noticed it on Android but it's also reproducible on Win10. If one of the cases is fixed and the other is not, I'll file a followup for the remaining one.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-241
