### ISSUE TITLE
Notice component should add `rel="noopener"` when `actionTarget` is `_blank`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12479]
Similar to #5700 but for `Notice`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-244)

**Comment by GregSherman** [comment]
<img width="1248" alt="Screenshot 2023-10-23 at 6 56 14 PM" src="https://github.com/mozilla/addons-frontend/assets/63402349/a9c9a47c-aa38-4ab3-b205-b1d338bb0d6c">

Inside this Notice, the link already has the proper `rel`. Looks like `<Link>` is called with our `target='_blank'` inside our Notice. This happens in the `<Button>` component when we have `href` in our props. As far as I'm aware, any Notice called with the actionTarget being `_blank` will use a Link component which handles this case already. 

Was just a quick look through, I could be mistaken.

**Comment by willdurand** [comment]
I think you're right, thanks for double-checking!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-244
