### ISSUE TITLE
Switch SearchForm components to HoC router pattern

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1248]
After https://github.com/mozilla/addons-frontend/pull/1229, the [amo/SearchForm](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/SearchForm.js) and [admin/SearchForm](https://github.com/mozilla/addons-frontend/blob/master/src/admin/components/SearchForm.js) components will be the last to use `context.router`.

Let's switch them to using a `router` property, configured by the [withRouter()](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#withroutercomponent-options) HoC (higher order component). This makes them easier to test since you can do `<SearchForm router={fakeRouter} />`.

Here is an example patch but it needs tests and stuff :) I didn't want to wedge this into https://github.com/mozilla/addons-frontend/pull/1229

``` diff
diff --git a/src/amo/components/SearchForm.js b/src/amo/components/SearchForm.js
index ea9ed60..bed4aaf 100644
--- a/src/amo/components/SearchForm.js
+++ b/src/amo/components/SearchForm.js
@@ -1,5 +1,7 @@
 import React, { PropTypes } from 'react';
 import { connect } from 'react-redux';
+import { withRouter } from 'react-router';
+import { compose } from 'redux';

 import { loadEntities } from 'core/actions';
 import { fetchAddon } from 'core/api';
@@ -12,15 +14,13 @@ import './SearchForm.scss';
 export class SearchFormBase extends React.Component {
   static propTypes = {
     pathname: PropTypes.string.isRequired,
+    router: PropTypes.object.isRequired,
     query: PropTypes.string.isRequired,
   }
-  static contextTypes = {
-    router: PropTypes.object,
-  }

   goToSearch(query) {
     const { pathname } = this.props;
-    this.context.router.push(`${pathname}?q=${query}`);
+    this.props.router.push(`${pathname}?q=${query}`);
   }

   handleSearch = (e) => {
@@ -63,4 +63,7 @@ export function mapDispatchToProps(dispatch) {
   };
 }

-export default connect(mapStateToProps, mapDispatchToProps)(SearchFormBase);
+export default compose(
+  withRouter,
+  connect(mapStateToProps, mapDispatchToProps),
+)(SearchFormBase);
```

**Comment by muffinresearch** [comment]
This is the docs for the new router https://reacttraining.com/react-router/web/api/withRouter

**Comment by kumar303** [comment]
This may need to happen when updating the router (https://github.com/mozilla/addons-frontend/issues/2161) but I'm not sure

**Comment by kumar303** [comment]
This was fixed in https://github.com/mozilla/addons-frontend/pull/2971 🌹

**Comment by vcarciu** [comment]
@kumar303 Please add some STRs to this bug or mark it as "qa: not needed"
