### ISSUE TITLE
The yellow banner should not be present on /android/ pages 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12496]
1. Login and go to collections or the profile pages or from a detail page navigate to read all reviews or see all versions page

Actual result:
There's a yellow banner "To find add-ons compatible with Firefox for Android, [click here](https://addons.allizom.org/en-US/android/)"

Expected result: 
The banner should be available on an android device when urls with `firefox` are open such as  https://addons.allizom.org/en-US/firefox/ 

![findaddonscompatible](https://github.com/mozilla/addons-frontend/assets/33448286/18f35798-49ce-4664-b747-402b7a9d5f20)

I've seen this reproducible on -stage and -prod.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-246)

**Comment by diox** [comment]
This is not a new regression: it's been there for years, and was actually implemented as per product spec for https://github.com/mozilla/addons-frontend/issues/9714.

Back then, we considered developer pages and collection pages as out of scope, though I assume the fact that it's shown on reviews pages for an add-on was an oversight, those should be considered supported listing pages.

I believe the thinking was that for collections for instance, it's sort of an orphaned page on android, so we want to nudge the user towards the home for android. But I'm not super convinced by that, and we don't want to do that for reviews or developer pages anyway, so we should just remove that message unless the user is on a `/firefox/` page.

**Comment by diox** [comment]
The logic is: 
- `WrongPlatformWarning` is called on all pages (unless explicitly disabled by passing `WrongPlatformWarning={false}` to the `Page` component
- On the add-on detail page, we don't call it at the `Page` level but instead as part of the install warning. We pass the `addon` in that case.
- If there is no `addon`, `WrongPlatformWarning` uses `correctLocationForPlatform()` and if the location is the homepage for Android, shows the message (with a link to the homepage). It also has some logic to show a message with a relevant link to Desktop users browsing `/android/` pages.
- `correctLocationForPlatform()` specifically returns the homepage unless we're already on the homepage or dealing with a search page https://github.com/mozilla/addons-frontend/blob/0ee31064db24342bb1a004e524d648fd91e4cef6/src/amo/utils/compatibility.js#L312-L322

We do want to keep showing the message for Android users browsing `/firefox/` pages (and vice-versa, the other message for Desktop users browsing `/android/`), and we want to show the correct message if the `addon` is passed as well.

**Comment by GregSherman** [comment]
commenting for assignment

**Comment by ioanarusiczki** [comment]
@GregSherman 

This is verified on AMO dev - Fenix 119.0

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-246
