### ISSUE TITLE
Fix up CSP config for -dev

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1249]
There's a few CSP violations to clean-up on the newly stood-up dev instance.

**Comment by ValentinaPC** [comment]
On what we should focus our attention to verify this? Thanks!
I've made some exploratory testing with the web-console opened in -dev. 
Will this do it?

**Comment by muffinresearch** [comment]
Yep there should be no further CSP warnings on https://amo.addons-dev.allizom.org/ but since we're away from releasing this it's fine to skip looking at it.
