### ISSUE TITLE
Convert setState() to redux actions

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1250]
Some components use `this.setState()` for various things. Here's an example of showing an error:

```
this.setState({ error: 'you must enter a blah before blah' });
```

This is OK but we completely lose any benfits of Redux, such as:
- time travel, which is nice for debugging state changes 
- error diagnostics, which is something I think we should add in the future
  - i.e. we can post the stack of redux state changes to an API endpoint from the client and replay the state changes on our local machines to reproduce the bug.

Let's switch `this.setState({ error: '...' })` to `this.props.setUIState({ error: '...' })` via `withUIState()` (see https://github.com/mozilla/addons-frontend/issues/5343).

This may end up sharing functionality with https://github.com/mozilla/addons-frontend/issues/1032 but it will be a little different.

**Comment by muffinresearch** [comment]
We should also review other use of `setState`

**Comment by kumar303** [comment]
One exception is using `setState` for typing into a text box. Using redux for this would probably be overkill.

**Comment by kumar303** [comment]
Maybe do this one at the same time too https://github.com/mozilla/addons-frontend/issues/2345

**Comment by tofumatt** [comment]
https://github.com/mozilla/addons-frontend/pull/2995#discussion_r135146819 is another place we should convert in the future.

**Comment by willdurand** [comment]
Given that we have issues for each occurrence where it makes sense to use the `withUIState()` HOC, I am closing this issue now.
