### ISSUE TITLE
Please check this box ... warning is not displayed when unchecking the box

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12508]
Followup for https://github.com/mozilla/addons-frontend/issues/12432

On Android go to an abuse report form

https://addons-dev.allizom.org/en-US/android/feedback/addon/privacy-possum/ 

Check the mandatory fields : reason, details and the agreement check-box below details of the report 
Un-check the agreement box and try to submit the form 

Expected result:
A warning "Please check this box if you want to proceed"

Actual result:
No warning , Submit report button is active , clicking it won't send the report.

![no warning on Android](https://github.com/mozilla/addons-frontend/assets/33448286/43c6f41a-85b2-4cf7-8f45-277ba782ddbd)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-250)

**Comment by willdurand** [comment]
@ioanarusiczki I just landed some changes that touched this checkbox. Could you please re-verify? The checkbox is now only shown for "illegal" content.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, I'm going to check https://github.com/mozilla/addons-server/issues/21375 too and look around.

**Comment by ioanarusiczki** [comment]
@willdurand 

The checkbox will be displayed only for illegal content " It violates the law ... " at the bottom of the form, text has changed too

Once un-checked the Submit report button is automatically greyed out

https://github.com/mozilla/addons-frontend/assets/33448286/a811ee4d-82fe-4fde-bef5-0cec3f94ba91

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-250
