### ISSUE TITLE
Report abuse against ratings using new feedbackform (behind `enableFeatureFeedbackForm` config)

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12507]
Reporting a rating should be done using the new `FeedbackForm` component, if `enableFeatureFeedbackForm` config is enabled.

Instead of the feedback/report add-on categories, the user should choose between (copy yet to be approved, subject to change):
- Spam
- Misplaced bug report or support request
- Hateful, violent, deceptive or illegal content

User can be logged in or unauthenticated, in the latter case they can leave their name and email as with reports against add-ons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-249)

**Comment by alexandruschek** [comment]
Hello,

While I was testing this: https://github.com/mozilla/addons-frontend/issues/12582 on dev env, I noticed the following:
1. The user can acces the report form only after clicking on a second flag reason
(as seen in this example, i've selected the first reason, does not matter which of the reasons you select first, and only after clicking on the second/third one I can access the form
<img width="1290" alt="image" src="https://github.com/mozilla/addons-frontend/assets/139126091/f4cbba17-413e-4a0f-b811-4c07ed2af5c8">
2. After submitting the report and going back to the reviews page, the review will not be shown as flagged:
<img width="1290" alt="image" src="https://github.com/mozilla/addons-frontend/assets/139126091/022a4fc1-e2cf-4b10-abcc-54f4ed6ea57e">

Thank you!

**Comment by willdurand** [comment]
I think (1) is expected - only the "This contains inappropriate language" item will send the user to the feedback form page. Clicking "Span" or "bug report" should send the report right away, without navigating to a different page. @alexandruschek is that what you observed?

For (2), let me investigate.

**Comment by alexandruschek** [comment]
Hello @willdurand,

Yes, by clicking "This contains inappropriate language", the user is sent to the feedback form page directly and the other two options send the report right away.

**Comment by willdurand** [comment]
> Yes, by clicking "This contains inappropriate language", the user is sent to the feedback form page directly and the other two options send the report right away.

Great, so far so good then. This is how it is supposed to work (for now).

**Comment by willdurand** [comment]
> For (2), let me investigate.

So that is caused by something we introduced/fixed in 2018.... https://github.com/mozilla/addons-frontend/pull/6342#discussion_r219958350 - It looks like for these review/rating abuse reports, we don't keep a record of what we (as users) have done.

**Comment by alexandruschek** [comment]
Hello,

Everything looks good, marking this as verified fix

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-249
