### ISSUE TITLE
implement user reporting for DSA

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12514]
┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-253)

**Comment by ioanarusiczki** [comment]
@willdurand 

- The user form is functional when going to the user's profile page and clicking "Report this user for abuse" 

- It looks like the themes/dictionary feedback forms. 

- I could send reports with/without the reporter's information. 

- UX looks good, I did not find issues on Win10 or Android.

- did notice there is no 1 min throttle when sending feedback one after another (checking admin they're sent) and this is happening for addons and users so let me know if I should file an issue about that.

![user feedbackform](https://github.com/mozilla/addons-frontend/assets/33448286/c1b2afed-6359-46a9-8413-abb762d8a265)

**Comment by willdurand** [comment]
> * did notice there is no 1 min throttle when sending feedback one after another (checking admin they're sent) and this is happening for addons and users so let me know if I should file an issue about that.

No idea about throttling here. @diox maybe?

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-253
