### ISSUE TITLE
Spelling error in string

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-frontend#12515]
Spelling error in this string: [`Anything that does’t fit into the other categories`](https://pontoon.mozilla.org/en-GB/amo-frontend/LC_MESSAGES/amo.po/?string=286615)

`does't` should be `doesn't`

### What did you expect to happen?

Correct the spelling error

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-254)

**Comment by peiying2** [comment]
@diox

**Comment by ioanarusiczki** [comment]
@willdurand 

This has been fixed

![doesn't](https://github.com/mozilla/addons-frontend/assets/33448286/1cc280f8-66ef-4b79-89ce-afa0a3fb316d)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-254
