### ISSUE TITLE
The message after sending an abuse report is not visible on smaller resolutions

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12520]
Followup for https://github.com/mozilla/addons-frontend/issues/12476#issuecomment-1787381428 

After sending the abuse report form the message is not visible on deskop on a laptop screen (~1500x900)

![desktop form after sending](https://github.com/mozilla/addons-frontend/assets/33448286/97f491f2-27f0-4d73-b6c0-42fd8b4261d9)

On Android devices (phones) AMO footer is displayed instead of the message:

![landing area after sending the form](https://github.com/mozilla/addons-frontend/assets/33448286/f54a1e8b-5396-4b79-a8cc-c605e6e61895)

This is not reproducible on higher resolutions (~1800x900)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-255)

**Comment by ioanarusiczki** [comment]
@willdurand 

This has been fixed on both platforms.

Verified on AMO dev - Win10 and Android

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-255
