### ISSUE TITLE
Relax eslint arrow-body-style rule

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1252]
The [arrow-body-style](http://eslint.org/docs/rules/arrow-body-style) rule makes us prefer to use arrow shortcuts when possible. However, I think it makes long promise chains harder to read and harder to refactor.

Take this example:

``` javascript
it('requires URL params',
  () => loadAddonReview({ params: {} })
    .then(() => assert(false, 'unexpected success'))
    .catch((error) => {
      assert.match(error.message, /missing URL params/);
     })
);
```

I think it would be easier to follow the promise chain if written with a return statement. It's also a lot easier to refactor when you need to declare variables at the top.

``` javascript
it('requires URL params', () {
  return loadAddonReview({ params: {} })
    .then(() => assert(false, 'unexpected success'))
    .catch((error) => {
      assert.match(error.message, /missing URL params/);
     });
});
```

**Comment by mstriemer** [comment]
You could probably use `()` to make the formatting a bit nicer then if you want to add multiple lines you just switch them to `{}` and add the return.

This could create some ambiguity around whether something is being returned or not but it does format more nicely in my opinion.

```js
it('requires URL params', () => (
  loadAddonReview({ params: {} })
    .then(() => assert(false, 'unexpected success'))
    .catch((error) => {
      assert.match(error.message, /missing URL params/);
     })
));

**Comment by tofumatt** [comment]
I really like seeing the explicit returns in JS myself as well; I don't feel like implicit returns are a thing in JS like they are in Ruby, so I like always seeing the explicit one. I'd be for this rule being enabled 👍

**Comment by Ryuno-Ki** [comment]
Yepp, implicit returns in Ruby made me scratch my head in the past. Especially when debugging oO
