### ISSUE TITLE
On Firefox for Android, opening an addon to its details page will display incompatible addons in "Other popular extensions"

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#12535]
Steps to reproduce:
1. On Firefox for Android, open any addon from addons.mozilla.org to its details page (ie. https://addons.mozilla.org/en-US/android/addon/darkreader/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured)
2. Scroll down to "Other popular extensions" section
3. Observe the addons present in section from above

Expected results:
All addons should be compatible with Android and installable

Actual results:
A not recommended addon, "New tab override" is present and it is not compatible with Android
You can see directly that the addon is not compatible by opening this link on Android device: https://addons.mozilla.org/en-US/android/addon/new-tab-override/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=recommended_fallback

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-259)

**Comment by diox** [comment]
FWIW it had already been reported a while back actually : https://github.com/mozilla/addons-frontend/issues/11495

**Comment by vcarciu** [comment]
Add-on recommendations are now hidden on Android.
Marking issue as verified

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-259
