### ISSUE TITLE
Header colour isn't white at first

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1253]
I think this is related to us using the `a:link` selector instead of just `a` (why do we do that?)

<img width="1268" alt="screenshot 2016-10-19 00 30 35" src="https://cloud.githubusercontent.com/assets/90871/19500255/5bc98580-9593-11e6-8c2f-148d9fdc2800.png">

So we need to set the `.Masthead-title` element to `color: #fff` or whatever colour it should be.

**Comment by muffinresearch** [comment]
We use a:link to match an unvisited link (a with href).

**Comment by tofumatt** [comment]
Ah, fair enough. Just means overwriting the style of `a` doesn’t always
work if I remember correctly.

**Comment by muffinresearch** [comment]
Yeah that's the problem because you need to overcome the specificity of `a:link` which is higher than a single class e.g.`.foo` on the `a`.

**Comment by Katy310** [comment]
This would be my first contribution to Mozilla. Any pointers on how to resolve this issue?

**Comment by tofumatt** [comment]
The issue is that the header colour is the colour of a link unless it's been clicked on when the user first loads the site. `.MastHead-title` is being overwritten by `a:link`.

As @muffinresearch mentioned, we should also be passing `isHomepage` through to the component but that may be a separate issue.

**Comment by mstriemer** [comment]
Added to v1 and blocks release since this is gross.

**Comment by tofumatt** [comment]
Thanks, sorry, I should have added it to V1 😓

- tofumatt

**Comment by vcarciu** [comment]
Verified as fixed : 
![headermobilewhite](https://cloud.githubusercontent.com/assets/1583842/22336684/b4045706-e3eb-11e6-913a-b496b82a09d5.png)
