### ISSUE TITLE
Add disclaimer next to message textarea in feedback form

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12543]
This disclaimer should be added to the feedback form message (which is and needs to stay optional):

> Please provide any additional information that may help us to understand your report (including which policy you believe has been violated).  While this information is not required, failure to include it may prevent us from addressing the reported content.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-262)

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on AMO dev

![disclaimer](https://github.com/mozilla/addons-frontend/assets/33448286/3ba7383c-b1a3-4a87-abcc-b8056fb6db13)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-262
