### ISSUE TITLE
Introduce a reusable `FeedbackForm` component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12558]
The `FeedbackForm` component introduced recently became highly coupled to add-ons because we started by implementing the feedback form for add-ons. Other feedback forms will look like the form for add-ons so we could reuse some of the logic. This issue is about introducing a reusable component - not tied to an add-on or anything - which would render a feedback form for _any_ type of content.

**For QA:** please make sure that there is no obvious regression in the feedback form for add-ons.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-267)

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on AMO dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-267
