### ISSUE TITLE
Rename `FeedbackForm` to `AddonFeedbackForm`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12559]
In order to reuse the `FeedbackForm` component, we first need to move all the "add-on logic" to its own component. That is needed because the feedback form for add-ons uses the install helper HOC (a wrapper for `mozAddonManager`), which requires an add-on to be passed as a prop to the component.

The goal here is to simply rename the existing `FeedbackForm` component. We'll reintroduce a reusable `FeedbackForm` component in https://github.com/mozilla/addons-frontend/issues/12558.

**For QA:** please make sure there is no obvious regression in the feedback form component, either visually or functionally.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-268)

**Comment by willdurand** [comment]
> Everything looks ok, I noticed that in the response after submitting the form, not all details from the addon are shown.

that is expected yeah

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-268
