### ISSUE TITLE
Enable `enableFeatureFeedbackForm` feature flag in all envs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12557]
Once the feedback form for addons is feature-complete, we should enable the `enableFeatureFeedbackForm` flag in all envs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-266)

**Comment by willdurand** [comment]
dup of https://github.com/mozilla/addons-frontend/issues/12556

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-266
