### ISSUE TITLE
Filter out some location options when we report feedback on a non-public add-on

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12553]
When we report feedback on a non-public add-on, the "place of violation" can only be inside the add-on. I suppose we can force this value and hide the input field when that's the case.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-264)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-264
