### ISSUE TITLE
Enable `enableFeatureFeedbackForm` on stage/prod

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12556]
We want to enable the feedback form (not the links to it yet!) so that reporting through Firefox works.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-265)

**Comment by diox** [comment]
@willdurand if we trigger `mozAddonManager.reportAbuse` with the flip preffed in Firefox to use the new feedback form, what does it do ?

**Comment by willdurand** [comment]
We don't prevent that API from working so the firefox popup would open.

**Comment by ioanarusiczki** [comment]
@willdurand 

On AMO stage:

- the old abuse report form is available and functional for extensions, themes, dictionaries. Lang packs don't have the Abuse Report button displayed. 
- the old form is present and functional on Android
- the new feedback form is available for public, non-public addon-ons from the URL 
https://addons.allizom.org/en-US/firefox/feedback/addon/%7B11b5feb9-003a-4851-8d1e-93bffe60acda%7D/ - not public
https://addons.allizom.org/en-US/firefox/feedback/addon/london/ public extension

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-265
