### ISSUE TITLE
Only show location field when needed

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12550]
According to the "spec", the `location` field is only relevant for some of the categories. Let's hide the input when it isn't needed. It looks like we only need this location for the following categories: B, C, D, E and F (i.e. all but the first one).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-263)

**Comment by ioanarusiczki** [comment]
@willdurand 

Location is hidden once A is checked. This is only applicable for extensions. Themes and dicts don't have A

![A has no location](https://github.com/mozilla/addons-frontend/assets/33448286/153bcde2-ece2-46d5-bdb9-9c94c2aab0e6)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-263
