### ISSUE TITLE
A 500 server error is displayed instead of the detail pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12566]
Submit a feedback form
Refresh the page after sending it
Tap the back button

Actual result:
500 server error

Expected result: 
the detail page

![server error](https://github.com/mozilla/addons-frontend/assets/33448286/d33cc814-d75d-4843-9635-66534e3771c6)

This is not reproducible without the page refresh

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-271)

**Comment by willdurand** [comment]
I overlooked an error that I saw a few times, I think:

> TypeError: addon.ratings.grouped_counts is undefined

**Comment by ioanarusiczki** [comment]
@willdurand Fixed on AMO dev

![bugfix](https://github.com/mozilla/addons-frontend/assets/33448286/f2ed04b1-451d-41ab-9e88-e82fff855c71)

**Comment by willdurand** [comment]
uh oh, why are the stars left-aligned after refresh? That looks like a bug @ioanarusiczki  :(

**Comment by ioanarusiczki** [comment]
@willdurand Ups. I'll re-check

**Comment by ioanarusiczki** [comment]
@willdurand I filed https://github.com/mozilla/addons-frontend/issues/12599 but it's a bit different than in my first attachment. 

I remember then the network was slow and I clicked the back button quickly to make a point for this issue. The rating stars seem to be misplaced indeed but for a short while, then they reappear on the right.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-271
