### ISSUE TITLE
Update user abuse report data logic to handle `reporter_name`, `reporter_email` and `reason`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12568]
In order to address #12514, we need to change the data logic to allow more fields to be sent to the API.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-272)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-272
