### ISSUE TITLE
Remove the Report abuse button for lang packs 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12561]
Followup https://github.com/mozilla/addons-frontend/issues/12485#issuecomment-1802202427

The new feedback form has been linked to the detail pages on all add-on types but it's been decided that " Report this add-on for abuse button " must be removed for language packs.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-269)

**Comment by ioanarusiczki** [comment]
@willdurand 

Lang packs no longer display the abuse report button on -dev

![no button](https://github.com/mozilla/addons-frontend/assets/33448286/0f0d87af-6bc2-4571-bccb-9f736153fbab)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-269
