### ISSUE TITLE
Rename `Feedback` page component to `AddonFeedback`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12564]
We'll have one page (component) per form so we should make the page component names a bit less generic.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-270)

**Comment by ioanarusiczki** [comment]
@willdurand I assume it's the same as for https://github.com/mozilla/addons-frontend/issues/12558#issuecomment-1814103532

**Comment by willdurand** [comment]
> @willdurand I assume it's the same as for [#12558 (comment)](https://github.com/mozilla/addons-frontend/issues/12558#issuecomment-1814103532)

correct, specifically about the add-on feedback form.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-270
