### ISSUE TITLE
Fix spam label

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12571]
It should be `It's spam` not `It's SPAM`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-273)

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on AMO dev

![it's spam](https://github.com/mozilla/addons-frontend/assets/33448286/8f48c35d-72ae-47a0-9826-7c654f41284c)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-273
