### ISSUE TITLE
Allow unauthenticated users to flag reviews

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12588]
~~It should now be possible for any user to flag a review.~~

Unauthenticated users should be able to access the rating feedback form.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-276)

**Comment by willdurand** [comment]
This is blocked by https://github.com/mozilla/addons-server/issues/21425

**Comment by ioanarusiczki** [comment]
@willdurand 

I verified on AMO Dev the logout views. When the user is unauthenticated, only the illegal option is available.  Is that expected?
I also filed https://github.com/mozilla/addons-frontend/issues/12627

Ratings 

![logoutview](https://github.com/mozilla/addons-frontend/assets/33448286/b81ea715-ecae-471f-a90b-f0e381df5323)


Replies:

![dev reply2](https://github.com/mozilla/addons-frontend/assets/33448286/850456df-e89a-44fc-b8c3-4cfb8c43a2de)

**Comment by willdurand** [comment]
> I verified on AMO Dev the logout views. When the user is unauthenticated, only the illegal option is available. Is that expected?

Expected, yes.

> Should the name of the addon redirect to the detail pages? (that's a question for all the forms so far)

Nope, not at the moment.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-276
