### ISSUE TITLE
The add-on's name in a review response should be defined as a localized string

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12582]
The `ExternalReviewTypeBase` type should define `addon.name` as a `LocalizedString`, not a `string`. This is required for https://github.com/mozilla/addons-frontend/issues/12507

**For QA:** please make sure there is no regression in the review pages, including when flagging a review/reply.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-274)

**Comment by alexandruschek** [comment]
Hello, 

Everything looks ok, marking this as verified fix.

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-274
