### ISSUE TITLE
Add API/saga/reducer code to be able to submit a rating abuse report

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12584]
In order to fully implement #12507, we need to be able to submit a rating abuse report to the AMO API. This issue is about doing that.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-275)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-275
