### ISSUE TITLE
Show add-on metadata in the add-on feedback form page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12592]
We should show add-on metadata for public add-ons:

<img width="665" alt="Screenshot 2023-11-13 at 15 01 39" src="https://github.com/mozilla/addons-frontend/assets/217628/109eaa48-1088-4873-8548-835dd54a5d6d">

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-278)

**Comment by ioanarusiczki** [comment]
@willdurand 

On Firefox - desktop

![on Firefox desktop](https://github.com/mozilla/addons-frontend/assets/33448286/2dfe5d57-cb92-45c6-907e-c1b9f909a0d8)

On Edge - desktop 

![on Edge](https://github.com/mozilla/addons-frontend/assets/33448286/2f633b85-b412-4f86-8448-08b3112da29a)

On Android - Chrome, after report has been submitted ( not sure if the position of the add-on icon is alright or it should be higher next to the name)
Actually, the icon is somewhere between name and author on desktop too, so it should be alright. 

![on Android with Chrome](https://github.com/mozilla/addons-frontend/assets/33448286/65de3642-4d8b-4b84-94f4-6747f457b3b6)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-278
