### ISSUE TITLE
Use constants in `TestAddonFeedback`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12590]
We should use constants imported from the `FeedbackForm` component in `TestAddonFeedback`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-277)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-277
