### ISSUE TITLE
Add more test coverage for the feedback pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12597]
I noticed that - despite codecov reporting 100% of code covered - we still have blind spots. This issue is about adding more test coverage to the existing feedback pages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-280)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-280
