### ISSUE TITLE
After sending a report at page refresh the rating stars are not correctly displayed 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12599]
Followup https://github.com/mozilla/addons-frontend/issues/12566#issuecomment-1810046653 

1. Send a feedback
2. Refresh the page and watch the header

Expected result: 
All elements are aligned correctly 

Actual result:
The rating stars would show up at the middle (for a second or 2) and then move back on the right side of the screen 

Notes:
This is happening only after sending the feedback form 

![one second](https://github.com/mozilla/addons-frontend/assets/33448286/ade5ded3-961e-4f62-85e7-dc5ac82a8467)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-281)

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on -dev

![no glitch](https://github.com/mozilla/addons-frontend/assets/33448286/f5816906-5602-454d-b848-a4845aadd52b)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-281
