### ISSUE TITLE
`yarn check-fonts` is broken

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12603]
The `yarn check-fonts` command is currently broken because `fonttools` released a new version (`4.44.1`).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-283)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-283
