### ISSUE TITLE
Update confirmation message after a report is submitted

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12607]
After we submit feedback for an add-on, user or collection, going back to the detail page of one of these content types will show a confirmation message instead of showing the report button (and until the next page reload). We should adjust the copy of these messages.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-286)

**Comment by ioanarusiczki** [comment]
@willdurand 

Addon or user, this is what I see after sending the feedback form

![userform](https://github.com/mozilla/addons-frontend/assets/33448286/ed3ce05f-4c2d-4aad-889a-5456fbd9fcb8)

**Comment by willdurand** [comment]
> Addon or user, this is what I see after sending the feedback form

You should go back to the detail page (or user profile) and observe the absence of the "report" button.

**Comment by ioanarusiczki** [comment]
@willdurand 

Ah, right, if I go back I will see the messages, they've been updated as [mentioned](https://github.com/mozilla/addons-frontend/pull/12608).

A page refresh before or after navigating back will display the button - that is expected. 

![message after reporting](https://github.com/mozilla/addons-frontend/assets/33448286/fca23491-be60-4d44-9bf9-55e62d752a8a)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-286
