### ISSUE TITLE
Update flag review menu strings

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12605]
We should update the strings in this menu:

<img width="372" alt="Screenshot 2023-11-15 at 10 53 26" src="https://github.com/mozilla/addons-frontend/assets/217628/9580f995-6329-4c1a-a41c-424708b04c8c">

The new strings are still being discussed so I'll update the issue when we have the final copy.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-284)

**Comment by ioanarusiczki** [comment]
@willdurand  

I verified on AMO dev on Win 10 and Android 

with login

![loginview](https://github.com/mozilla/addons-frontend/assets/33448286/6e94bbef-c960-48b2-b866-bccc96325e08)

logout view

![logoutview](https://github.com/mozilla/addons-frontend/assets/33448286/042296cd-2318-4076-860b-a01dd2584608)

dev reply 

![dev reply](https://github.com/mozilla/addons-frontend/assets/33448286/98acd7b7-6413-4efc-9864-4bdcdebce5ec)
![dev reply2](https://github.com/mozilla/addons-frontend/assets/33448286/850456df-e89a-44fc-b8c3-4cfb8c43a2de)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-284
