### ISSUE TITLE
Feedback form success message is not shown for non-public add-ons you have access to

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12618]
STR on dev:
- Log in with an account that is the author of an add-on
- In devhub, make that add-on invisible
- Visit the detail page for that add-on ; you should be able to, since you're an author
- Click on report button, that takes you to the submit page (you can also use the direct URL, but local caching may mess with the reproducibility - see the note below)
- Try to submit report from the feedback page

Expected results:
- The report gets submitted and you see the success message

Actual results:
- The report gets submitted but you don't see the success message and stay on the page.

Note:
You can "predict" the bug is going to be triggered by looking whether or not the add-on card at the top of the feedback page shows the authors or not. If the authors show up but the add-on is not supposed to be public (it's invisible, or pure unlisted, disabled etc), you'll trigger the bug. If only the guid is shown, it should not trigger the bug. If you previously loaded the page without being logged in (or without being logged in with the right account), caching might prevent the bug from being triggered.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-288)

**Comment by diox** [comment]
This is reproducible in production using the direct URL to the feedback form, but see the note in the description if you're doing multiple attempts.

**Comment by diox** [comment]
I suggest testing with an account that has `API:BypassThrottling` when attempting to reproduce, it will make things easier - otherwise the rate limit on abuse API will quickly become annoying, as it's set to 20/day.

**Comment by willdurand** [comment]
my theory: we load the add-on data thanks to the extra privileges, this includes its id, guid and slug. add-on abuse reports are indexed by slug historically, so we've reused that. now the problem is that when we retrieve the result of an abuse report, there is nothing other than the guid , whose value is used for the slug too. that's why there is a mismatch

**Comment by ioanarusiczki** [comment]
@willdurand 

I tried with invisible, disabled when reports are sent by the author. Issue is no longer reproducible on -dev.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-288
