### ISSUE TITLE
Submit report is inactive with authentication, only anonymous reports can be sent 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12610]
1. Login on -dev or -stage and go to a feedback form https://addons.allizom.org/en-US/firefox/feedback/addon/extreme-biking/ 
or https://addons-dev.allizom.org/en-US/firefox/feedback/addon/decentraleyes/ 
2. Check a reason 
3. Observe Submit report button 

Expected result:
the button should be active , report should be sent 

Actual result:
the button is greyed out

Notes:
not reproducible with an admin account 
Report can be sent anonymously
Reproducible with the user's feedback form too

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-287)

**Comment by ioanarusiczki** [comment]
@willdurand 

I tried with other users and could not reproduce , then I tried again with rusiczki.ioana+41@gmail.com 

![one user](https://github.com/mozilla/addons-frontend/assets/33448286/c7efbea2-085a-420e-9e27-0c9b3ba345c8)

**Comment by ioanarusiczki** [comment]
@willdurand 

I reproduced the issue again with a new account, I did not finish the last step on Edit profile page : to add a display name and click Create My Profile. Instead I navigated away to a feedback report. That's when the Submit report stays inactive. 

These accounts have as display name "Firefox user + id"

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on AMO stage

![bug fix](https://github.com/mozilla/addons-frontend/assets/33448286/e87773c6-2dfb-4321-8376-a4e856059005)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-287
