### ISSUE TITLE
Inconsistency on Android versus Desktop - at ratings feedback form 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12627]
When reporting a rating the rating starts are missing on Android's form

Same is happening when reporting a developer reply - on Desktop empty ratings are displayed and on Android none, here maybe there should be no ratings at all ? 

Android (rating and dev reply look the same)

![Screenshot_2023-11-20-13-13-49-126_org mozilla fenix debug](https://github.com/mozilla/addons-frontend/assets/33448286/41c673f8-8698-41d1-80d8-ce878eef806b)

Desktop view for a rating 

![rating on desktop](https://github.com/mozilla/addons-frontend/assets/33448286/06bc2944-1838-431c-8867-89c604beb9ca)

Developer's reply flagged 

![dev reply on desktop](https://github.com/mozilla/addons-frontend/assets/33448286/712cbd7d-e376-4f53-94a7-bab26e66f9f5)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-291)

**Comment by willdurand** [comment]
This isn't about Android specifically, this is expected on narrow screens, which doesn't have a lot of room for that kind of information so it is hidden on screen width < 500px.

**Comment by ioanarusiczki** [comment]
@willdurand 

At developer's response the rating stars on desktop are the average ratings of the developer?

**Comment by willdurand** [comment]
oh, hm, sorry. No, it's probably nothing since developer responses don't have ratings. Maybe we shouldn't show the ratings for developer replies, which is part of what you suggested above. WDYT?

**Comment by ioanarusiczki** [comment]
@willdurand 
filed https://github.com/mozilla/addons-frontend/issues/12628

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-291
