### ISSUE TITLE
Send installed add-on version for non-public add-ons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12623]
## STR

1. Go to the add-on feedback form of a non-public add-on (e.g. unlisted) that is installed in your profile
2. Submit the form

## Expected

The installed add-on version should be sent to the AMO API.

## Actual

The installed add-on version isn't sent.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-289)

**Comment by ioanarusiczki** [comment]
@willdurand 

I installed on -dev unlisted versions from versions pages and then reported

Admin:
![version is passed](https://github.com/mozilla/addons-frontend/assets/33448286/7f700f0d-dab8-4be0-bc32-ce8bbf01bfef)

API response:

![APIresponse](https://github.com/mozilla/addons-frontend/assets/33448286/b22b4693-1ce8-4b44-80ba-57b19b153419)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-289
