### ISSUE TITLE
Remove the rating stars at developer replies

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12628]
Followup for https://github.com/mozilla/addons-frontend/issues/12627#issuecomment-1818947973

On the feedback form : when flagging a developer reply for illegal content , on feedback page there shouldn't be rating stars displayed (since dev replies don't get rating stars)

![dev reply on desktop](https://github.com/mozilla/addons-frontend/assets/33448286/712cbd7d-e376-4f53-94a7-bab26e66f9f5)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-292)

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev

![stars removed](https://github.com/mozilla/addons-frontend/assets/33448286/91b50a32-8c18-488c-b232-aec714eb38cb)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-292
