### ISSUE TITLE
Update some strings in the user profile feedback form

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12631]
As per T&S feedback, we should update some of the strings:

> "send some feedback about the user profile/report the user profile because
> it's illegal or incompliant" might work better?

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-293)

**Comment by vcarciu** [comment]
Verified as fixed:
<img width="1106" alt="Screenshot 2023-11-22 at 12 13 07" src="https://github.com/mozilla/addons-frontend/assets/1583842/7c53228f-c5ea-409a-b450-391fef420acd">

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-293
