### ISSUE TITLE
Fix localized strings in feedback form

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12640]
Localized strings in the form should not be split for better localization.

**For QA:** please make sure there is no regression around optional/required fields, etc.

**Comment by alexandruschek** [comment]
Hello,

I tested this on dev environment, and all looks good. Marking this as fix verified

Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-298
