### ISSUE TITLE
Implement the homepage category layout

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1264]
Relates to https://github.com/mozilla/addons-frontend/issues/797

Implement the body of the homepag with static cat or search links. We might not have the links initially so will start with just the layout and go from there.

<img width="151" alt="amo_-_v1_1__sketch" src="https://cloud.githubusercontent.com/assets/1514/19603608/b89cc6d8-97a9-11e6-9a1c-2c4c7e2806b7.png">

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF51(Android 6.0.1)
The header section of the homepages, as illustrated in your screenshot and in mocks, appears different on my Android device: gray - not blue and without the section with the buttons:
Screenshot: 
![a3](https://cloud.githubusercontent.com/assets/15685960/22681423/c4fe0bbe-ed15-11e6-9f75-0a7c9ed6f146.png)


Is this the way is suppose to look? Thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix screenhsot:  
![untitled](https://cloud.githubusercontent.com/assets/15685960/22829737/b1c825e0-efac-11e6-976d-d9982ee7f399.png)
