### ISSUE TITLE
Add new add-on badge for android-compatible add-ons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12650]
On the Desktop version of an add-on detail page, an add-on (also) compatible
with Android should have a new badge (like we have for "payment required" or
"experimental" for instance).

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-301)

**Comment by ioanarusiczki** [comment]
@willdurand 

The new badge is automatically available for all extensions compatible with Android 

Desktop - the badge is displayed 

![all badges](https://github.com/mozilla/addons-frontend/assets/33448286/136b3399-695c-43be-9f3f-34a95825fe81)

on Android - the badge is not available

![onAndroid](https://github.com/mozilla/addons-frontend/assets/33448286/53ac2ab4-aa91-4283-8d1a-346c79677cf5)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-301
