### ISSUE TITLE
Enable new feedback form links in all envs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12651]
We'd like to enable the feedback form links in all envs, which essentially means making this new form the default for add-ons, users, ratings, and collections (this is new!). Under the hood, this is about turning the `enableFeatureFeedbackFormLinks` feature flag `on` in `config/default.js`.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-302)

**Comment by ioanarusiczki** [comment]
@willdurand 

This has been verified on AMO stage. 

I've sent reports for extensions, themes, collections, ratings and replies. 

AMO stage frontend reports are registered in Abuse reports admin.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-302
