### ISSUE TITLE
Remove feedback form feature flags after everything is enabled on prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12654]
We added two feature flags for the new feedback forms: `enableFeatureFeedbackForm` and `enableFeatureFeedbackFormLinks`. Once everything is deployed on prod, we should remove these feature flags and clean-up the code.

**For QA:** please make sure there is no obvious regression.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-303)

**Comment by vcarciu** [comment]
Regression testing was performed, will continue on Stage and we will close this after prod push.

**Comment by vcarciu** [comment]
Regression testing done also on Stage.

**Comment by vcarciu** [comment]
Verified as fixed

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-303
