### ISSUE TITLE
Update the `APPVERSION_FOR_ANDROID` logic

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12660]
We'd like to show more add-ons compatible with Android by default.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-304)

**Comment by willdurand** [comment]
@ioanarusiczki I think we are good then.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-304
