### ISSUE TITLE
Add UTM params to the Play Store download URL

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12667]
In https://github.com/mozilla/addons-frontend/issues/12664, we added a download URL pointing to the Play Store so that users can download Firefox for Android. We should add UTM params to the link.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-306)

**Comment by willdurand** [comment]
So we'd like to have:

- utm_source: addons.mozilla.org
- utm_campaign: the value of the `utm_campaign` on the inbound link or the fallback value that we use for Firefox for desktop
- utm_content: banner-download-button
- utm_medium: referral

**Comment by ioanarusiczki** [comment]
@willdurand 

I see the following utm parameters:

utm_campaign=amo-fx-cta
utm_content=banner-download-button
utm_medium=referral
utm_source=addons.mozilla.org

**Comment by willdurand** [comment]
@ioanarusiczki sorry, I forgot a scenario: when AMO URLs have a `utm_campaign` value, we should pass it in the Play Store link.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-306
