### ISSUE TITLE
Update wrong platform notice and get firefox banner for Android

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12664]
We need to update the wrong platform notice and the get firefox banner for Android so that we offer users to download install Firefox for Android.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-305)

**Comment by willdurand** [comment]
> The banner is not centered, it's having the length of a shelf. I hope it's the expected.

What is not centered exactly? The text in the notice?

**Comment by willdurand** [comment]
@ioanarusiczki ^

**Comment by ioanarusiczki** [comment]
@willdurand Non-FF browsers have the centered layout:

This is Edge (Win10) 

![Edge view](https://github.com/mozilla/addons-frontend/assets/33448286/b77a8298-d1ea-45b3-a13e-25de229e3332)

**Comment by ioanarusiczki** [comment]
@willdurand Sorry, it's not centered, it's smaller.

**Comment by willdurand** [comment]
Yeah, that isn't the same UI component. We have two components:

- the banner, sticked to the top of the web page
- the notice, inlined below the header

Both have different style.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-305
