### ISSUE TITLE
Add -dev URL to the GitHub repo

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1267]
Just realised we stood up the -dev server but we don't link to it anywhere. We should add a link in the README (and maybe the GitHub URL for now while -dev is the only site) so new devs (and us) can go to it without having to remember the URL... which I had already forgotten and had to comb through emails to find ^_^

**Comment by muffinresearch** [comment]
I probably isn't worth adding a link just yet since accessing the site here is only temporary the plan is to start using the normal domains in due course.

**Comment by tofumatt** [comment]
As @atiqueahmedziad pointed out this issue is confusing and the site is now accessible on `-dev` with the MAMO cookie, so closing this.
