### ISSUE TITLE
Bump max bundlesize to accommodate for Node 18.19

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12684]
Node 18.19 made our bundle slightly larger so tests/builds are failing on `master`, preventing deploys. Let's bump the max to accommodate for the difference.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-310)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-310
