### ISSUE TITLE
The value of the locale is not present in admin when sending reports from AMO frontend 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#12682]
Followup for https://github.com/mozilla/addons-server/issues/21529#issuecomment-1839220954

When sending from the browser reports (en-US or using other locales), this is displayed in admin:  `Application locale: -` 

Expected result:
the local used by the frontend should be displayed in admin too

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-308)

**Comment by ioanarusiczki** [comment]
@willdurand 

I sent with different locales reports of all types and Application locale is now present in [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/abuse/abusereport/28081/change/)

![applicationlocalefixed](https://github.com/mozilla/addons-frontend/assets/33448286/b3d9b727-da79-4501-8f3b-ad8488ec9986)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-308
