### ISSUE TITLE
UTM parameters should be passed into a `referrer` query param to the Play Store

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12698]
We currently set the UTM parameters to the Play Store link directly but that is not going to work to get attribution data in Fenix via [Google Play Install Referrer](https://developer.android.com/google/play/installreferrer). We should pass all the UTM params into a single `referrer` query parameter instead.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-313)

**Comment by willdurand** [comment]
For QA, the STR are a bit more involved than usual because they require a real device with a Google (Play Store) account.

0. Make sure Firefox for Android (Release) is not installed
1. Open `https://addons.mozilla.org/en-US/android/?utm_campaign=qa-test` in Chrome
2. Click on the "Firefox for Android" link in the banner - This step should open the Play Store
3. Install Firefox for Android (Release) from the Play Store
4. Open Firefox for Android (Release) once it is installed
5. Open the file `/data/user/0/org.mozilla.firefox/shared_prefs/fenix_preferences.xml` on your device and verify the presence of the different UTM parameters

**Comment by ioanarusiczki** [comment]
@willdurand 

I tested with a Xiaomi with Android 7.0 

1. From Chrome I went to 
https://addons.mozilla.org/en-US/android/?utm_campaign=qa-test
2. Clicked the banner and installed Android from that link
3. Enabled debugging from Firefox, connected to the device from desktop in about:debugging#/setup and then I opened a page in Firefox 

name="pref_key_utm_source">addons.mozilla.org
name="pref_key_utm_medium">referral
name="pref_key_utm_campaign">qa-test
name="pref_key_utm_term"></string> <string name="pref_key_utm_content">banner-download-button

The entire xml:
![xml with utmparams](https://github.com/mozilla/addons-frontend/assets/33448286/95ffd1f1-7e4f-4609-8a1a-9005fd64053c)

**Comment by ioanarusiczki** [comment]
@willdurand I checked on both -dev and -stage.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-313
