### ISSUE TITLE
Outbound links from AMO should be "nofollow" to discourage SEO spam

### ISSUE THREAD

**Issue by abhn** [mozilla/addons-frontend#12708]
### Describe the problem and steps to reproduce it:
Spam add-ons on AMO usually contain the link of a website. A motivation for spam add-ons is to get backlinks for the website that's usually in the website/support website/summary/description fields. From content reviews, I know often these are websites that are themselves promising SEO optimizations and backlinks, giving more weight to the SEO spam hypothesis. 

### What happened?
Links to third party websites show an intermediate page that has a `http-equiv="refresh" content="0; ..."` directive which google seems to treat as a permanent redirect, which would be considered a backlink.

### What did you expect to happen?
Outgoing links to developer pages should be "nofollow" to discourage any SEO spam as that would render the effort useless. 

### Anything else we should know?
We do a http-equiv="refresh" from a non-`mozilla.org` domain, specifically `prod.outgoing.prod.webservices.mozgcp.net`. Does that already mean that the backlink is from the `mozgcp.net` domain and not from `addons.mozilla.org` (in which case this ticket can be closed already)? I'm not very fluent in SEO but I wanted to create this issue to clarify in any case.

- https://webmasters.stackexchange.com/questions/141237/seo-effect-of-http-equiv-refresh-for-redirect

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-315)

**Comment by vcarciu** [comment]
Verified as fixed for for support and homepage links too.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-315
