### ISSUE TITLE
Don't show "Available on Firefox for Android™" badge for extensions not compatible with Android 120.0 and higher

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#12709]
STR:
- Load an extension that is compatible with Firefox for Android up to 68.* and not higher. At the moment in production, https://addons.mozilla.org/en-US/firefox/addon/consent-o-matic/ is one of them.

Expected results:
- You don't see the "Available on Firefox for Android™" badge since compatibility with Firefox for Android stops at 68.* for that add-on

Actual results:
- You see the "Available on Firefox for Android™" badge. If you're using a recent version of Firefox for Android, you won't be able to find and use that extension though.

Recommendation:
- If the add-on is compatible with Firefox for Android but the `max` version is not `*`, we shouldn't show the badge.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-316)

**Comment by vcarciu** [comment]
Verified as fixed using addons-dev.allizom.org/en-US/developers/addon/tomato-clockzzz/ on AMO-dev

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-316
