### ISSUE TITLE
update a link in about:addons

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#12713]
In the Add-ons Manager (about:addons) on the "Recommendations" page, we need to update a link in the final sentence of the top-of-page blurb 

"... Here’s a selection Firefox **recommends** for exceptional security, performance, and functionality."

Please make that **recommends** link point here (instead of SUMO): 
https://addons.mozilla.org/firefox/search/?promoted=recommended&sort=rating&type=extension

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-317)

**Comment by willdurand** [comment]
This is a firefox bug, see: https://bugzilla.mozilla.org/show_bug.cgi?id=1873404

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-317
