### ISSUE TITLE
Pontoon doesn't show the comments intended to localizers

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12756]
While we do generate comments in PO files, they are _translator_ comments that Pontoon doesn't parse. We should generated _extracted_ comments instead as per https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html. This is what addons-server (via pybabel) does.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-320)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-320
