### ISSUE TITLE
Use separate "Other" category ID for new (DSA) abuse report flow

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#12752]
Between the old and the new abuse report categories, we are only reusing "Other" internally. We should make that a new category ID as well to have a clean cut between pre-DSA and post-DSA.

This issue complements https://github.com/mozilla/addons-server/issues/21662.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-319)

**Comment by diox** [comment]
This should be completely transparent to end-users, but when using that `Other` category when submitting feedback it should result in `DSA: Something else` as the reason in the abuse admin tool instead of `Other`.

**Comment by vcarciu** [comment]
Verified as fixed . "Something else" is now displayed instead of "Other".

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-319
