### ISSUE TITLE
Remove FxA -> Mxa banner in frontend

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12777]
The migration completed last year; it's time to remove the notifications about the rebranding.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-324)

**Comment by GregSherman** [comment]
commenting for assignment

**Comment by alexandruschek** [comment]
Hello,

I checked this on -Stage and it looks ok, the banner no longer appears.
<img width="1452" alt="image" src="https://github.com/mozilla/addons-frontend/assets/139126091/6351a93f-92ad-42bc-8bf1-a66939f0dc49">

 Thank you!

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-324
