### ISSUE TITLE
Abuse report form: "place of violation" field changes

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#12841]
We need to make some changes to the abuse report form:

1) When selecting the reason "Spam", we hide the "place of violation" field

2) When selecting any of the DSA related reasons, the "place of violation field is mandatory to fill out and "Select Place" is not a valid selection. We can keep it as the default and fail form validation, or remove it and have no default and then fail form validation as well if no option was selected.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-328)

**Comment by wagnerand** [comment]
If this results in API changes, could someone please file a corresponding issue on addons-server?

**Comment by willdurand** [comment]
> 1\. When selecting the reason "Spam", we hide the "place of violation" field

I am curious: how do we know whether the spam is in the add-on or on the AMO detail page then?

> 2\. When selecting any of the DSA related reasons, the "place of violation field is mandatory to fill out and "Select Place" is not a valid selection. We can keep it as the default and fail form validation, or remove it and have no default and then fail form validation as well if no option was selected.

In this case, that means we make the "place of violation" field mandatory unconditionally and we remove the "Select Place" option if it is no longer valid. That's because the "does not work" category already hides this field.

> If this results in API changes necessary, could someone please file a corresponding issue on addons-server?

I suppose the API might not like a "spam" report without an empty "place of violation".

**Comment by alexandruschek** [comment]
Hello,

I tested the abuse report form and it works great, I just have one question that came up in my mind while testing.
When we are choosing the "Something else" option, is intended to also make the user choose a place of violation?
<img width="1403" alt="image" src="https://github.com/mozilla/addons-frontend/assets/139126091/1ad9bffc-0817-4db0-8ea8-e51743da1ebc">

Thank you!

**Comment by wagnerand** [comment]
> Hello,
> 
> I tested the abuse report form and it works great, I just have one question that came up in my mind while testing. When we are choosing the "Something else" option, is intended to also make the user choose a place of violation? <img alt="image" width="1403" src="https://private-user-images.githubusercontent.com/139126091/304380945-1ad9bffc-0817-4db0-8ea8-e51743da1ebc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MjU0OTUsIm5iZiI6MTcwNzgyNTE5NSwicGF0aCI6Ii8xMzkxMjYwOTEvMzA0MzgwOTQ1LTFhZDliZmZjLTA4MTctNGRiMC04ZWE4LWU1MTc0M2RhMWViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxM1QxMTUzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MTE1M2I2MjYyZGMyNGZhNmUxMjRmYjViZDUxM2NhZWRkMGVjZjcwN2UzMzZmOWVlNTgwYzFlODgzNGZjNjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KfyP6zSMdAAbxJMWM3_L-s_sAa-U-kD84yu5kdcdEdo">
> 
> Thank you!

That's ok.

**Comment by alexandruschek** [comment]
Thank you! Then I will mark this as verified fix.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-328
