### ISSUE TITLE
Change "legal" link to point to new central policy landing page [frontend]

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#12843]
AMO is going to have a dedicated landing page for all policies relating to AMO/add-ons.  This should replace the existing url.  

New url is https://www.mozilla.org/about/legal/amo-policies/ (per https://mozilla-hub.atlassian.net/browse/AMO-185)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-329)

**Comment by ioanarusiczki** [comment]
Verified on AMO dev

![legal](https://github.com/mozilla/addons-frontend/assets/33448286/a1b5c572-bb29-4f00-8abb-3dbfde91f534)

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-329
