### ISSUE TITLE
Implement the themes home page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1285]
See the sketch file in the assets folder for more details:

![amo_-_v1_sketch](https://cloud.githubusercontent.com/assets/1514/19685426/75a0aa94-9ab4-11e6-9513-c20d8f33347b.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix video:
![videotogif_2017 02 10_15 58 58](https://cloud.githubusercontent.com/assets/15685960/22829253/5b96fe96-efaa-11e6-909a-2519c3780fab.gif)

Browse by category and welcome mat will be added in v2.
Also themes layout are being fixed.
Marking this verified.
