### ISSUE TITLE
Implement the extensions home page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1286]
See the sketch file for more info:

![amo_-_v1_sketch](https://cloud.githubusercontent.com/assets/1514/19685446/9a4605e2-9ab4-11e6-998c-38158b09c356.png)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF51(Android 6.0.1)
Video: 
![videotogif_2017 02 07_09 58 04](https://cloud.githubusercontent.com/assets/15685960/22682772/5b3aa3ec-ed1d-11e6-98fe-7270ff055317.gif)

@muffinresearch : the "Browse by categories" section was removed?
Thanks!

**Comment by ValentinaPC** [comment]
Observed that my question has a fix in v2. Marking this verified.
