### ISSUE TITLE
Update ratings to stars as per latest UX

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1288]
We have faces currently and now we're going to go back to stars: 

![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/19685738/ea32961e-9ab5-11e6-9367-c6e45efa9b70.png)

Should now be:

![amo_-_v1_sketch](https://cloud.githubusercontent.com/assets/1514/19685751/f79f2042-9ab5-11e6-886d-5c7f1512178c.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Ff51(Android 6.0.1)
Postfix screenshot: 
![r1](https://cloud.githubusercontent.com/assets/15685960/22682457/68115252-ed1b-11e6-83ea-9d6cbf076ae8.png)
