### ISSUE TITLE
Dictionary for Standard Moroccan Tamazight (zgh) not available in language-tools page

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-frontend#12889]
CC @wagnerand

I tried to add the language name to languages.js in #12888, but I think this might require more work to support the characters in the font.

The language name in question is ⵜⴰⵎⴰⵣⵉⵖⵜ ⵜⴰⵏⴰⵡⴰⵢⵜ

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-333)

**Comment by wagnerand** [comment]
@flodolo Thank you for getting it started!

**Comment by MedAymenF** [comment]
Thank you for adding it!

**Comment by flodolo** [comment]
I see it in https://addons.mozilla.org/firefox/language-tools/

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-333
