### ISSUE TITLE
Hook up locales to the language drop-down

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1289]
The language chooser doesn't currently have any data in it.

![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/19685798/2b13eafc-9ab6-11e6-9c81-04ddc7588a4b.png)

**Comment by Ryuno-Ki** [comment]
Does that happen on every page or just on special sites? Are there sites without associated translations?

**Comment by tofumatt** [comment]
That is on every page (in the footer) on the new front-end. We should have a list of supported translations that it should list (and then switch to `onChange`).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7)
A list of languages are listed while tapping on the language selector.
Postfix screenshot: 
![m1](https://cloud.githubusercontent.com/assets/15685960/22683349/331f01f2-ed20-11e6-9664-427b257cda93.png)

@muffinresearch : the languages are not the same like on desktop, is that ok?
