### ISSUE TITLE
Hook up category links on the homepage

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1290]
The homepage is pretty much an empty shell. Once we know and have the category pages to link to we should update the links.

![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/19685828/4d3a49c8-9ab6-11e6-8a2d-1d8656788ea0.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Links where attached to every extension/theme category.
Postfix video: 
![videotogif_2017 02 07_10 39 22](https://cloud.githubusercontent.com/assets/15685960/22683747/2500af2e-ed22-11e6-9142-f67ab8cb5bc5.gif)
