### ISSUE TITLE
Hookup the install button

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1291]
This will be a bit complicated because of the limitations on origin for the install apis. 

It also needs to take into account the fallback see https://github.com/mozilla/addons-frontend/issues/946

![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/19685896/a2b382c0-9ab6-11e6-9a1d-e0f7e83b84c3.png)

**Comment by mstriemer** [comment]
QA:

This includes updates to how the install button is handled on the disco pane to make it work on the new mobile pages. Can you please test that the install buttons are still working as expected with these changes.

**Comment by ValentinaPC** [comment]
Verified all buttons from disco pane using prefs for -dev (+`extensions.webapi.testing` on true) and -prod on FF 53.0a1 (2016-11-17) (32-bit) and work as before.
Let me know if there is anything else to be checked.
