### ISSUE TITLE
Show user count data on add-on detail page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1293]
For V1, we will only implement the user count metadata. Note this likely shares data with the "more information widget"

See https://docs.google.com/document/d/13g8tmoII8oCNrUXOl2HegsQst7WEsXukBnIqPUNrqb0/edit#heading=h.2ltzvz63pc6h

![amo_-_v1_sketch](https://cloud.githubusercontent.com/assets/1514/19686010/4f2b7cb0-9ab7-11e6-95fa-13ae37e86ca5.png)

**Comment by mstriemer** [comment]
I don't think we have any way of detecting "Editor's Choice". We could presumably show currently featured add-ons but I don't think that data is currently surfaced in the API.

For downloads the value we have on mobile currently and in the API is "weekly downloads".

It might be nice to include the star rating up top, not sure if we can reuse the star icon from the rating widget but that might work.

**Comment by kumar303** [comment]
According to the latest comment on the doc linked above, all of this has been pushed to V2 *except* the user count metadata. We need to show the user count for V1. I will update the title of this issue.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1).
User count data is displayed in add-on details page.
Postfix screenshot: 
![u1](https://cloud.githubusercontent.com/assets/15685960/22686450/e07272b0-ed2c-11e6-821c-8f9f34e59f56.png)
