### ISSUE TITLE
Implement the details page more information widget 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1294]
See https://docs.google.com/document/d/13g8tmoII8oCNrUXOl2HegsQst7WEsXukBnIqPUNrqb0/edit#heading=h.ofi3bxtmofqf

![amo_-_v1_sketch](https://cloud.githubusercontent.com/assets/1514/19686084/9952f6f6-9ab7-11e6-9cac-544ce21aa525.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
A "More information" section was added in every add-on and theme details page.
Postfix screenshot:
![mi](https://cloud.githubusercontent.com/assets/15685960/22686871/95b75338-ed2e-11e6-8420-1a96d9b58e2c.png)
