### ISSUE TITLE
Remove the favorites button placeholder for v1

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1295]
We don't need the favorites functionality for v1 so this can be removed for now.

![add-ons_for_firefox](https://cloud.githubusercontent.com/assets/1514/19686812/cb09b40c-9aba-11e6-9809-2b4e7aefd521.png)

**Comment by vgvenkat** [comment]
Hi, I am just getting started in this repo, would this be a good bug to start with? Should I request access to the google doc?

**Comment by muffinresearch** [comment]
@vgvenkat hi, there's nothing in the doc that's really helpful for this one so I've removed the link (I'll look at making that doc public separately since it's linked for other issues here too).

This is an ideal first bug. Give me a shout if you need any help. It should just be a case of deleting: 

https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonDetail.js#L64

And the import in the same file. You can probably leave the placeholder code, css and the svg since we'll need it for when we actually implement this feature.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
No Favorite(Like) button in add-ons/themes details page.
Postfix screenshot: 
![untitled](https://cloud.githubusercontent.com/assets/15685960/22687198/b8b6faf4-ed2f-11e6-886c-8ee93b15d93c.png)
