### ISSUE TITLE
Update the "about this add-on" block and add truncation.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1296]
This data already exists and is represented on the page. Fixing this should only require:
- Truncate the display of content and show a read more link. Any truncation will need to take care to not break the HTML.
- Update the styles.

Here's a snippet from the latest sketch file:

![amo_-_v1_sketch](https://cloud.githubusercontent.com/assets/1514/19687540/aa15ad66-9abd-11e6-846a-ee88ec8ee298.png)

**Comment by Ryuno-Ki** [comment]
Is there a requirement to label the link "read more"?

Because screenreader users can choose to get only links spoken (c.f. https://www.drupal.org/docs/7/creating-accessible-themes/accessibility-principles#link-text et al).

> **Links make sense when taken out of context**
> Every link should make sense if the link text is read by itself. Screen reader users may choose to read only the links on a web page. Certain links like "read more" or "click here" should therefore be avoided because those will not allow a user to understand where the links lead once they are taken out of their context.
> - If such links need to be used, consider making them understandable out of context by completing them with significant complementary text that will then be positioned off-screen using CSS.

**Comment by muffinresearch** [comment]
@Ryuno-Ki thanks, we're aware of basic accessibility requirements and will look to do something that doesn't create links without context.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix screenshot:
![rm](https://cloud.githubusercontent.com/assets/15685960/22687552/30503e58-ed31-11e6-8068-f947b4f0418e.png)
