### ISSUE TITLE
Implement the search sort widget

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1297]
Since this is essentially changing the search the easiest way to implement this is probably going to be with a list of links that are revealed when the sort is expanded as opposed to trying to use a form control which will get messy if there's implicit submission.

The whole thing should be keyboard accessible.

See https://docs.google.com/document/d/13g8tmoII8oCNrUXOl2HegsQst7WEsXukBnIqPUNrqb0/edit#heading=h.22jk2sku8h5t

![amo_-_v1_sketch](https://cloud.githubusercontent.com/assets/1514/19687682/542b3ab4-9abe-11e6-998d-459d613334b1.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix video:
![videotogif_2017 02 07_12 33 42](https://cloud.githubusercontent.com/assets/15685960/22687747/f8124e04-ed31-11e6-91f1-8450e42bdb32.gif)
