### ISSUE TITLE
Remove reportAbuse/abuseReportPanelEnabled from the mozAddonManager type

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#12970]
This is the counter-part of https://phabricator.services.mozilla.com/D208730.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-336)

**Comment by alexandruschek** [comment]
Hello, 

I tested on stage env the abuse report on the addon detail page and it all looks good.
@ioanarusiczki can you help with checking the addons manager part, I'm having some tehnical problems locally? 

Thank you!

**Comment by willdurand** [comment]
This is probably good enough.

**Comment by ioanarusiczki** [comment]
I've checked from addon manager too sending some reports for extensions/themes. Looks good to me too.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-336
