### ISSUE TITLE
Switch to using ducks for actions/actionTypes/reducers

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1299]
Having multiple files for actions, reducers and actionTypes (constants) is a little cumbersome and these things normally change together. There's another format that some people use called [ducks](https://github.com/erikras/ducks-modular-redux) that combines these together.

> ### Rules
> 
> A module...
> 1. MUST `export default` a function called `reducer()`
> 2. MUST `export` its action creators as functions
> 3. MUST have action types in the form `npm-module-or-app/reducer/ACTION_TYPE`
> 4. MAY export its action types as `UPPER_SNAKE_CASE`, if an external reducer needs to listen for them, or if it is a published reusable library

This would give us something like:

``` js
// src/disco/actions/discoResults.js
const LOAD_RESULTS = 'disco/discoResults/LOAD_RESULTS';

export function loadResults(results) {
  return {
    type: LOAD_RESULTS,
    payload: { results },
  };
}

export default reducer(state = [], action) {
  switch (action.type) {
    case LOAD_RESULTS:
      return [...action.payload.results];
    default:
      return state;
  }
}
```

I'm not sure where we'd want to store these, could be in a folder called `ducks`, `actions`, `reducers` or something else.

I found another article while looking for this format that suggests [organising your app even more like how django does](http://jaysoo.ca/2016/02/28/organizing-redux-application/) so we'd have `addons/components`, `reviews/components`, etc. That might play nicely into this but could be another incremental step if we'd like to do it.

Inspired by #1281.

**Comment by tofumatt** [comment]
Oh, that is really cool! 👍🏻

**Comment by muffinresearch** [comment]
Seems like a good approach, I've always found having these things disconnected makes it hard to see overview of the relationship between them.

**Comment by kumar303** [comment]
putting them both in one place makes sense to me

**Comment by willdurand** [comment]
We do this for a while now, so let's close this issue.
