### ISSUE TITLE
Create a Provider test helper for components that use AMO's internal `<Link>`

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1316]
See: https://github.com/mozilla/addons-frontend/pull/1309/files#r85552951

**Comment by kumar303** [comment]
It would be helpful to add a provider helper (for i18n and redux) to all tests by default

**Comment by kumar303** [comment]
It's possible that moving to a universal link component will fix this: https://github.com/mozilla/addons-frontend/issues/2053

**Comment by willdurand** [comment]
I don't think this is valid anymore. We do not use `Provider` and inject props directly on the components, often using `shallowUntilTarget()` and a base component.
