### ISSUE TITLE
Footer background cut off before end of viewport

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1320]
I believe when I added the footer this wasn't the case, so this might be a regression.

Screenshot here:

<img width="1388" alt="screenshot 2016-10-30 22 40 37" src="https://cloud.githubusercontent.com/assets/90871/19840627/0da28592-9ef2-11e6-867f-2f1c1e1f3f76.png">

The black colour should go until the end of the viewport but doesn't.

**Comment by muffinresearch** [comment]
The footer should probably "stick" to the bottom of the viewport so when there's not enough content it still sits at the bottom.

**Comment by tofumatt** [comment]
The footer not reaching the end naturally is a rarity and that "sticky" effect is usually more work+code for an effect I'm not convinced is much better. I'd prefer to just fill the colour, but I wouldn't r- the code if I were reviewing it 😉
