### ISSUE TITLE
Scroll position is maintained for new pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1323]
### Describe the problem and steps to reproduce it:

* Visit https://amo.addons-dev.allizom.org/en-GB/firefox/ in responsive mode.
* Make a search e.g. "foo" https://amo.addons-dev.allizom.org/en-GB/firefox/search/?q=foo
* Scroll down and click one of the last results

### What happened?

The details page is loaded at the same scroll position as the click:

e.g: 

<img width="210" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/19891580/a91608fe-a038-11e6-9ecf-2c8ae4f05303.png">

### What did you expect to happen?

The scroll position should be the top of a new page after navigating. However, clicking back should keep the original scroll position.

**Comment by tofumatt** [comment]
Oh thanks for reporting this, it’s an issue across the site that’s been
irking me. I think we’ll want to move the page position to .App-content
(below the search bar) after any route change.

**Comment by muffinresearch** [comment]
There are router middlewares to deal with this in relation to history: https://github.com/taion/react-router-scroll which is probably what we want.

**Comment by muffinresearch** [comment]
I'll try out the middleware and report back.

**Comment by ValentinaPC** [comment]
Verified as fixed using https://amo.addons-dev.allizom.org/en-GB/firefox/ in responsive mode under FF51(Win 7) and AMO-dev on my Android 6.0.1 device.
Postfix video: 
![videotogif_2017 02 07_12 43 11](https://cloud.githubusercontent.com/assets/15685960/22688112/83506dba-ed33-11e6-94e4-b2da46d3dbb4.gif)
