### ISSUE TITLE
Add the privacy policy/legal links

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1339]
<strike>We link to the privacy policy in the footer, but it goes nowhere. We need to create a privacy policy page using http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#add-on-eula-and-privacy-policy and link to it.</strike>

I got confused. Just need to change these links. Doing that now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Privacy policy and Legal notices links are available and redirecting as expected.
Postfix screenshot: 
![foo](https://cloud.githubusercontent.com/assets/15685960/22688445/03002d24-ed35-11e6-803b-16733f8a08eb.png)
