### ISSUE TITLE
Unset "mamo" cookie and refresh page from "View desktop site" link

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1341]
This will make more sense once the mobile pages are served via the same host as AMO. 

The "View desktop site" link in the footer should remove the mamo cookie and refresh the page as per the existing mobile page functionality.

See also https://github.com/mozilla/addons-server/issues/3712

**Comment by ValentinaPC** [comment]
Verified the functionality of "View desktop site" from mobile using AMO-dev under FF51(Android 6.0.1) and works as expected.... @muffinresearch : is there something else to be checked here?

**Comment by muffinresearch** [comment]
@ValentinaPC no that should be ok.

**Comment by ValentinaPC** [comment]
Verified this on AMo-dev Ff51(Android 6.0.1)
Postfix screenshot: 
![1](https://cloud.githubusercontent.com/assets/15685960/22832069/41da6316-efb5-11e6-9810-72142b1e534a.png)
