### ISSUE TITLE
Ensure URL parity with AMO

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1349]
The mobile pages need to have parity in terms or URLs or fallback to AMO  if a url does not exist in the mobile app.

Due to the way we need to serve traffic we can't deviate the URLs otherwise dropping the cookie and refreshing will result in a 404 when going from the mobile to desktop pages.

Any proposed changes to urls should come after we expand the mobile pages across desktop.

## Exceptions 

URLs that exist in the mobile pages but don't exist on AMO

Mobile URL | Solution
------------ | -------------
*Example: /bah/whatsit* | *Example: Redirect to /whatever on desktop*

**Comment by mstriemer** [comment]
Are we going to an a category listing to desktop then? I didn't see a related page to the one currently being added to mobile. Should we start a list of new URLs somewhere?

**Comment by tofumatt** [comment]
There are pages that don’t exist on mobile current we’ll be linking to; I
assume pages we don’t have URLs for will force the desktop view? Would we
do the same for mobile pages with no desktop version?

Seems weird, but dunno what else to do. Implementing an AMO version that is
planned to go away soon seems wasteful, but I suppose it is an _easy_ page
to implement.

**Comment by muffinresearch** [comment]
We could look redirections for special cases if we've created something on mobile that doesn't have a counterpart on AMO e.g. an cats listing page for extensions on mobile could probably just be the extension homepage for example or whatever is the most relevant page with the same content.

I'm going to see if @bqbn has some time to hookup -dev so we can start seeing what breaks.

**Comment by muffinresearch** [comment]
For exceptions feel free to list them on this issue.

**Comment by tofumatt** [comment]
One thing to note is right now our search uses `category=alerts-updates&type=extension` whereas the existing AMO uses `atype=1&cat=14`. Given we plan to display search results differently in general (not showing incompatible add-ons on the new front-end, especially on mobile), this might not be a huge issue and it's certainly less code for us to use slugs over IDs... but I figured I'd mention it here so it's known.

**Comment by mstriemer** [comment]
As a start we should only redirect /locale/android/ and maybe /locale/firefox/ to the mobile site.

There are a few other URLs but that should be a good start.

**Comment by muffinresearch** [comment]
I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1330939 for ops to look into falling back for urls that are 404. We'll need to fix the bug that causing 500s for what should be 404s, I'll file something for that shortly.

**Comment by muffinresearch** [comment]
I think we now have fallbacks in place and that's working pretty well in general. Going to close this for now and we can deal with any additional pieces separately.
