### ISSUE TITLE
Investigate Hub builds not building

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#136]
See https://hub.docker.com/r/addons/addons-frontend/builds/ looks like it was 18 days ago.

**Comment by mstriemer** [comment]
@muffinresearch can you check that GitHub is pinging docker hub? I don't think I have permission to set that up.

**Comment by muffinresearch** [comment]
I've tried adding the hook, test payloads don't appear to do anything. I then tried recreating from the hub side and still it doesn't appear to be building. :/

**Comment by muffinresearch** [comment]
I've now tried deleting the hook and setting up the automated build from scrach. Let see if that works....

**Comment by muffinresearch** [comment]
Ok looks to be working now.
