### ISSUE TITLE
Language drop down styling needs minor adjustments for RTL

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1363]
### Describe the problem and steps to reproduce it:

Using the debug RTL locale (once #1361 has landed) look at the language dropdown in the footer.

### What happened?

Looks like this:

![pp-ous_ o _ i ox](https://cloud.githubusercontent.com/assets/1514/20173000/4a37ef34-a72f-11e6-8389-dd4958be8a5f.png)

### What did you expect to happen?

Should look like this:

This ignores the fact the language is wrong that's a separate bug here: https://github.com/mozilla/addons-frontend/issues/1289

![pp-ous_ o _ i ox](https://cloud.githubusercontent.com/assets/1514/20172965/281db4ce-a72f-11e6-8c79-195a75a533c7.png)

**Comment by tofumatt** [comment]
Note that the style of the language picker has changed a fair bit so this is no longer a good first bug and will actually require more effort.

**Comment by vcarciu** [comment]
Verified as fixed : 
![mobilertl](https://cloud.githubusercontent.com/assets/1583842/22653833/5d872cb8-ec93-11e6-8dfc-e3b881f64f0d.png)
