### ISSUE TITLE
Adjust the review text prompt based on star selection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1366]
### Describe the problem and steps to reproduce it:

Go to an add-on detail page, select a one or two star rating.

### What happened?

Your review is saved (if there isn't an error) and on the next screen the review prompt asks you "Tell the world why you think this extension is fantastic!" The placeholder for the review starts with "Tell us what you love about this extension."

### What did you expect to happen?

It should say something more relevant to the feelings of the reviewer who is not happy with the add-on.

**Comment by vcarciu** [comment]
Verified as fixed : 
![mobilefantastic](https://cloud.githubusercontent.com/assets/1583842/22654014/145dac14-ec94-11e6-9837-e9f5be14e0ab.png)

Notes:
@kumar303  In description , we asked for another text for 1 or 2 stars rating, but I observed that same text is added for a 3 star rating. I think that this is reasonable, but I want to be sure , so please confirm
