### ISSUE TITLE
Odd test failures for DiscoPane UI test

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1367]
Seems there is a disco pane UI test failure if production is down. Or at least we suspect one because while prod was down master and our branches were failing but once it was back up they passed.

Filing this here just so it's on someone's mind to check out on a rainy day.

**Comment by kumar303** [comment]
oops, I think we don't have a failing Travis job to link to anymore. I was seeing this error:

    NoSuchElementException: Message: Unable to locate element: .play-video
