### ISSUE TITLE
Change all raw state representations to redux dispatches in test code

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1371]
A lot of our unit tests for functions like `mapStateToProps` pass in a raw state representation (i.e. a plain object). This is dangerous because it's hard to keep raw objects in sync with reducer code as the state evolves.

Here is an example:

````javascript
const state = {
  api: {
    lang: 'en-US',
    clientApp: 'firefox',
    token: 'secret-token',
  },
};
const props = mapStateToProps(state);
// make assertions about the props
````

Instead, let's use a real store and dispatch real actions.

````javascript
import createStore from 'amo/store';
import { setJWT } from 'core/actions';
import { userAuthToken } from 'tests/client/helpers';

const store = createStore();
// This would create the equivalent state and would more 
// closely resemble how a user signs into the real app.
store.dispatch(setJWT(userAuthToken()));
const props = mapStateToProps(store.getState());
// make assertions about the props
````

**Comment by tofumatt** [comment]
Bonus: it will likely make many of our tests a lot shorter and easier to parse!

**Comment by kumar303** [comment]
Let's move everything to ducks first https://github.com/mozilla/addons-frontend/issues/1299

**Comment by tofumatt** [comment]
We've closed https://github.com/mozilla/addons-frontend/issues/1452 but we should implement it when we do this.

**Comment by kumar303** [comment]
This is mostly done. We've written all new code this way for a long time now.

**Comment by willdurand** [comment]
> This is mostly done. We've written all new code this way for a long time now.

Yep, and on this basis, I am closing this issue now.
