### ISSUE TITLE
Show logging during test failures

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1373]
### Describe the problem and steps to reproduce it:

Create a unit test that runs code looking something like this:
````javascript
import log from 'core/logger';
function something() {
  log.info('a message that you want to see during testing');
}
````

### What happened?

When a function like this is executed from a unit test, nothing is logged to the console.

### What did you expect to happen?

The test suite should show this logging output, at least when there is a failure.

### Anything else we should know?

If you change it to `console.log()` you will see the output while testing.

**Comment by kumar303** [comment]
Actually, `console.log()` statements are hidden now too so this is really painful. It seems that `console.error()` can be used as a workaround (if you remember).

**Comment by tofumatt** [comment]
Looked through this for about thirty minutes and I can't tell if it's a rabbit hole or not, but will look again after lunch. We don't seem to be using `drop_console` in tests but maybe it's inheriting the prod config... though when I disable it there it still seems to happen. 🤷‍♀️

**Comment by kumar303** [comment]
I think the tests do inherit the prod config which means it could well be dropping console logging. I haven't looked too closely but after updating webpack things will shift around https://github.com/mozilla/addons-frontend/issues/1761

**Comment by muffinresearch** [comment]
Fixed with https://github.com/mozilla/addons-frontend/commit/a5b3855d17b5c75563d9106aa8a9f5c241e4287a since Jest shows logging.
