### ISSUE TITLE
Allow categories to be searched

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1377]
Allow search to look for categories. Supports #1183.

**Comment by vcarciu** [comment]
I am not able to see any categories in search results . This is what i see when searching "Game" : 
![categmobile](https://cloud.githubusercontent.com/assets/1583842/22692293/e365a5a4-ed46-11e6-88a7-1a0f5ce91527.png)

**Comment by tofumatt** [comment]
Sorry about this; this was a developer note talking about our JS APIs and not UI. Doesn't need QA as this was a note-to-developer-only-type-issue.
