### ISSUE TITLE
Allow existing review text to be edited

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1381]
When you rate an add-on and return to its detail page, you will see your saved star rating (as of https://github.com/mozilla/addons-frontend/issues/1088). You can also select a new star rating which will update your chosen rating. This redirects you to the review text entry.

The review text entry needs to be populated with your saved text. Currently it is empty.

**Comment by madalincm** [comment]
Verified as fixed in FF50(Android 6.0) in addons-dev.allizom.org
After taping on the stars the user is redirected and can edit the previous review.
Marking as verified fixed.
