### ISSUE TITLE
Virtual keyboard should be hidden after searching

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1384]
When you perform a search the keyboard remains visible and the search field remains focused. This is a little annoying as it forces you to manually close the keyboard and makes it less obvious that you have in fact triggered a search.

We should hide the keyboard when they submit the form. Perhaps clearing focus will do this. I'm not really sure.

**Comment by madalincm** [comment]
After performing a search the keyboard is hidden and the search field loses focus. Marking bug as verified fixed.
