### ISSUE TITLE
Add a lint rule for key sorting

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1387]
Having brought this up a few times in reviews this week, we should see about linting for alphabetised keys. I find it's an easy way to be consistent and makes things easier to scan.

Bonus points for alphabetised CSS attributes, which I love, but I've been told that's sometimes a bit much for some people 😄

**Comment by muffinresearch** [comment]
> Bonus points for alphabetised CSS attributes, which I love, but I've been told that's sometimes a bit much for some people 😄

Sometimes you need to move CSS descriptors out of being alpha-sorted to be able to override based on ordering. Although if the linter can do it and there's a way to make exceptions that could work.

**Comment by kumar303** [comment]
I seem to recall we had some problems with the lint plugin for alphabetized React prop-types because some systems do wacky things; eslint might fail on one system but not the other.

**Comment by kumar303** [comment]
We generally start off bugs like this with 'maybe good first bug' so that it can get triaged. I'm not sure this would be a good first bug because it will touch a mountain of code.

**Comment by tofumatt** [comment]
Oh, good point. My bad.

**Comment by kumar303** [comment]
Personally, I think alphabetizing keys would slow me down when refactoring. One of the beautiful things about object shorthand syntax is that you can build lots of functions that look like `theCall({ one, two, three })`. When you need to add a new parameter, it's really easy to add one on to the end. I feel like alphabetizing keys only helps for readability if the list is really long. However, I'd argue that if a *function* argument list is really long then you should break it into smaller functions.

Functions aside, I can see how configuration objects with a ton of keys will be easier to read when alphabetized. I would suggest that we keep enforcing such situations manually in code reviews.

**Comment by muffinresearch** [comment]
> Personally, I think alphabetizing keys would slow me down when refactoring. One of the beautiful things about object shorthand syntax is that you can build lots of functions that look like theCall({ one, two, three }). When you need to add a new parameter, it's really easy to add one on to the end. I feel like alphabetizing keys only helps for readability if the list is really long. However, I'd argue that if a function argument list is really long then you should break it into smaller functions.

If there was a enforce sort on multiline that might work? Alpha-sorting per-line is generally easy in editors.

I'd love for it to be possible to get to a point where all stylistic and code standards stuff is automated (with only the most minimal amount of exceptions) so that reviews get to focus more on the important stuff. Maybe part of that is agreeing on what isn't important as much as it is about enforcing what is?

**Comment by muffinresearch** [comment]
FWIW: If we want to try the stylelint sorting - there's this plugin: https://github.com/hudochenkov/stylelint-order which looks like it might do the necessary.

**Comment by kumar303** [comment]
I would feel better about enforcing sorting only for multi-line key definitions. I'd have to try it out and see how annoying it gets though 🍌

**Comment by muffinresearch** [comment]
Discussed this, wontfix.
