### ISSUE TITLE
An invalid JWT token causes pages not to load and serve unauthorised rather than an error (or just resetting the cookie)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1389]
This is largely a development issue but could possibly bite someone with an expired JWT token, I'm not sure how they work.

### Describe the problem and steps to reproduce it:
I signed into the frontend using `olympia.dev` as my `API_HOST`, then started using `dev:amo` with the default host.

### What happened?

Client-side renders failed with an unhandled Promise error.

### What did you expect to happen?

My token would be reset/deleted (or at least get an error).

---

This might be related to #1032.

**Comment by tofumatt** [comment]
It should be noted that I at least *think* this is what's happened.

When it's rendered on the server I get `Unauthorized`. I deleted the cookie and it's still happening though, maybe this is unrelated and it's a different bug 😒

**Comment by kumar303** [comment]
I don't quite understand the steps to reproduce this. Could you expand on them maybe using actual config values so I could try it myself?

We should probably swallow cookie errors like this, sign the person out, and log an error about it in the console. The page should still render.

**Comment by muffinresearch** [comment]
Discussed this and we need to better document the various auth scenarios but otherwise this will be fixed elsewhere.
