### ISSUE TITLE
Deploy dependencies to production with yarn

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1391]
### Describe the problem and steps to reproduce it:

When we deploy AMO/discopane to production the install step uses `npm`

### What happened?

This installs all dependencies as it should but it does not verify the contents of each package.

### What did you expect to happen?

We should switch to [yarn](https://yarnpkg.com/en/docs/install#linux-tab) which will verify the contents of each package we install. This will make sure none of them have been tampered with

### Anything else we should know?

To bootstrap our system, i.e. install `yarn` itself, we can use their RPM: https://yarnpkg.com/en/docs/install#linux-tab

This issue should also involve updating all the developer to documentation so that devs all use `yarn` locally.

**Comment by mstriemer** [comment]
We should also add a test that verifies there are no changes to `yarn.lock` when installing on CI.

This should be as easy as checking the exit code of a shell command. With git available it should just be `git diff --exit-code yarn.lock`. Without git we can copy the file before install and use `diff yarn.lock.orig yarn.lock`.

**Comment by mstriemer** [comment]
There's actually a [`yarn check`](https://yarnpkg.com/en/docs/cli/check) command that seems to do this. It has a `--integrity` flag that we should pass when deploying.

**Comment by kumar303** [comment]
I moved the `yarn check` bit to https://github.com/mozilla/addons-frontend/issues/3034
