### ISSUE TITLE
Investigate comma-dangle for functions

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1394]
An update to the airbnb eslint config mean that trailing commas are always required for function args when they are spread across multilines. 

comma-dangle has been overridden so trailing commas are not enforced in function args for now but we might want to re-visit if we actually want this enabled. Apparently trailing commas for functions are introduced in es2017. Before we re-enable this we should make sure our transpilation steps are happy with it too.

**Comment by mstriemer** [comment]
If babel is stripping this like it should be I'm on board for this. I'd say trailing commas for all the things.

Hell, let's use them instead of semicolons.

**Comment by muffinresearch** [comment]
This is fine.
