### ISSUE TITLE
Always return a Promise for functions passed to asyncConnect

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1403]
Right now we return `true` for certain functions passed to `asyncConnect`, which is technically supported but is weird as it usually returns a Promise. Even returning `Promise.resolve(true)` would be nicer, probably.

See: https://github.com/mozilla/addons-frontend/pull/1398#discussion_r88937885

(Side note, we do this a lot in places where we're caching results, so maybe we just want to not cache stuff.)

**Comment by kumar303** [comment]
I think returning a consistent value (a Promise) always makes everything easier: tests, calling code. The biggest win is that the calling code won't have to write defensive code like:
````javascript
const val = loadSomeData();
if (isPromise(val)) {
  return val.then(...)
}

**Comment by kumar303** [comment]
I think https://github.com/mozilla/addons-frontend/pull/1890 partially addresses this. It makes sure that no errors are thrown. Making sure all callbacks return promises when successful seems good but I'm not sure if it will be so helpful.

**Comment by kumar303** [comment]
We're going to remove async connect in https://github.com/mozilla/addons-frontend/issues/2356
