### ISSUE TITLE
Paginate should default to showPages={0}

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1405]
See: https://github.com/mozilla/addons-frontend/pull/1398#discussion_r88934951

**Comment by eviljeff** [comment]
@tofumatt can you expand on comment 0?  (I didn't follow it... so a new contributor may not either)

**Comment by tofumatt** [comment]
Currently we pass `showPages={0}` to the `<Paginate>` component to disable numbered page links (eg. `page 1 | 2 | 3` links between `previous` and `next`), but as we likely want that to be the default behaviour (according to the mocks it always is), we should make `showPages={0}` the default and supply an argument to it only on the admin search.

**Comment by eviljeff** [comment]
what file/method would need to be changed?

**Comment by tofumatt** [comment]
https://github.com/mozilla/addons-frontend/blob/master/src/core/components/Paginate/index.js#L33 needs changing to `0` and the admin call to `<Paginate>` would need `showPages={9}` as I see it.

Tests should need changing too but they'll fail and can be found then.

**Comment by jvillalobos** [comment]
Mentor: @tofumatt

**Comment by caitmuenster** [comment]
Hi all - just heard from a new contributor, Tin, that he'd like to pick this one up. We'll get him officially assigned once he gets back from the holidays to an area with wifi.

**Comment by tinhtooaung** [comment]
Thanks guys, I will be working on this soon :-D

**Comment by caitmuenster** [comment]
Hey @tinhtooaung! Are you still interested in working on this bug?

**Comment by aayushsanghavi** [comment]
@caitmuenster I guess tofumatt merged this in #1656. For some reason this issue is still open.

**Comment by caitmuenster** [comment]
Thanks for the heads up, @aayushsanghavi!
