### ISSUE TITLE
Show InfoDialog when an add-on is installed

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1414]
The mobile frontend will be able to install add-ons once #1388 lands. The data is being set in state for the `InfoDialog` to appear but since it isn't being rendered and doesn't support mobile.

Update `InfoDialog` to support mobile, move it to `core/` and render it in `App` so that it can be displayed on install.

**Comment by muffinresearch** [comment]
We also need to bear in mind the Firefox changes that should mean that there is a browser notification for when addons are installed. That bug is here: https://bugzilla.mozilla.org/show_bug.cgi?id=1308310 I'm not sure what's planned re: FF Android for that.

**Comment by muffinresearch** [comment]
Here's the specific comment re: Android - https://bugzilla.mozilla.org/show_bug.cgi?id=1308310#c18
