### ISSUE TITLE
Don't spread add-on and installation in mapStateToProps

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1416]
`InstallButton` and some add-on components depend on properties of `addon` and `installation` to be set at the root rather than being namespaced. This means the status of an add-on and the status of its installation can collide and cause annoying errors where `status` is expected to be an installation status but is actually an add-on status.

We should return `{ addon, installation }` from mapStateToProps instead of `{ ...addon, ...installation }`.

**Comment by kumar303** [comment]
It looks like discopane's Addon is the only one left: https://github.com/mozilla/addons-frontend/blob/fd669beb91ea311a8d1b8de97cc946a40189f00b/src/disco/components/Addon.js#L227

**Comment by kumar303** [comment]
I plan to fix the ones that were in `amo`'s `AddonDetail` as part of https://github.com/mozilla/addons-frontend/pull/2520

**Comment by kumar303** [comment]
> I plan to fix the ones that were in amo's AddonDetail as part of #2520

Sigh. That didn't work out so well. I added them back in https://github.com/mozilla/addons-frontend/pull/2536 Things get complicated because the reducer also spreads `addon.them_data` onto `addon`.

**Comment by tofumatt** [comment]
We also do a pretty gnarly spread here https://github.com/mozilla/addons-frontend/blob/master/src/core/reducers/addons.js#L32 which is causing #2569.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label qa not needed?
Thanks

**Comment by willdurand** [comment]
@AlexandraMoga sorry. The add-on detail page should be displayed correctly, and installing/uninstalling an add-on should work on AMO. On Disco, add-ons should also be displayed correctly, and installing/uninstalling an add-on should work as expectedtoo.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage, with FF62 and Nightly 64, Wn10x64 and Android 8.0
Add-on details page and disco pane look fine. Installing/uninstalling working as expected.
