### ISSUE TITLE
Create an AddonSection component for common UI components

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1421]
Things like:

<img width="310" alt="screenshot 2016-11-24 18 50 42" src="https://cloud.githubusercontent.com/assets/90871/20608158/eed86c74-b276-11e6-85cc-322c48447c0b.png">
<img width="313" alt="screenshot 2016-11-24 18 50 34" src="https://cloud.githubusercontent.com/assets/90871/20608157/eed63076-b276-11e6-8724-1be8e946280b.png">

and other components for #1285 and #1286 are essentially all the same round-corner header/content/footer components, usually with a list of add-ons in the centre.

Realising this, we should make it a generic UI component. I'm nearly finished it so I'll have a PR soon.

**Comment by mstriemer** [comment]
We could call this a `Card` or something similar. I think that's what this concept is essentially. I'm not sure of a good way to do the heading/footer, props on `Card` seem to make sense but suck for links.

```jsx
// Works well for heading
<Card heading="More information">
  <dl>
    <dt>Website</dt>
    <dd>http://blahblahblah.com</dd>
  </dl>
</Card>

// Less so for the link
<Card
  linkText={`See all ${resultCount} results`}
  linkParams={{ ...searchParams, type: 'themes' }}
>
  <AddonList addons={themeResults} />
</Card>

// Maybe multiple related components?
<Card>
  <CardHeading>Themes</CardHeading>
  {/* Could have a <CardBody>, but it probably isn't needed */}
  <AddonList addons={themeResults} />
  <CardFooter>
    <Link to={{ ...searchParams, type: 'themes' }}>See all {resultCount} results</Link>
  </CardFooter>
</Card>
```

**Comment by tofumatt** [comment]
So thus far I’ve only needed text for headers, but I think what should work is just:

```jsx
<Card header=“Foo bar” />
```

or

```jsx
const header = <Link to=“/foo/bar”>Foo bar</Link>;
<Card header={headerHTML} />
```

That’s what I’ve done for the footer, which does use HTML in some places. It wfm.

**Comment by tofumatt** [comment]
fwiw mine looks like:

```jsx
const footer = <Link to="/extensions/featured/">{i18n.gettext('More featured extensions')}</Link>;
<Card addons={results} header={i18n.gettext('Featured Extensions')} footer={footer}>
  <div>
    This is extra content rendered above add-ons (or in place of
    them if no add-ons supplied like in the `<MoreInfo>` component.
  </div>
</Card>
```

**Comment by mstriemer** [comment]
Could you either make that an `AddonsCard` that boils down to a `Card` under the hood, or use `Card` directly? I think it would be good to keep `Card` as generic as possible, we can always wrap it with more logic.

```jsx
const footer = (
  <Link to="/extensions/featured/">{i18n.gettext('More featured extensions')}</Link>
);
<AddonsCard addons={results} header={i18n.gettext('Featured Extensions')} footer={footer}>
  <div>
    This is extra content rendered above add-ons (or in place of
    them if no add-ons supplied like in the `MoreInfo` component.
  </div>
</AddonsCard>
// Becomes
<Card header={header} footer={footer}>
  {children}
  <AddonList addons={addons} />
</Card>
 
// More info card uses Card directly
<Card header={i18n.gettext('More Info')}>
  <dl>
    <dt>Website</dt>
    <dd>http://blahblahblah.com</dd>
  </dl>
</Card>

**Comment by tofumatt** [comment]
Hmm, fair enough. Yeah that's no problem.
