### ISSUE TITLE
Theme preview on detail page

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1422]
When holding down on the theme image on the detail page we should provide a theme preview.

> I like "press" instead of "tap". Tapping is just like flicking the switch. Pressing is a deliberate action: press down and you preview, release and you go back to what it was before. Made the label/icon a bit smaller:
> ![screen shot 2016-11-18 at 1 54 57 pm](https://cloud.githubusercontent.com/assets/6797635/20448093/27b31cf4-ad97-11e6-9654-7f4f5900c632.png)

> Oh, nix that "icon only" view.

Extracted from #946.

**Comment by mstriemer** [comment]
@pwalm I'm not seeing this eye icon in the sketch file. Is there somewhere I can grab it from?

**Comment by mstriemer** [comment]
The dimensions of our preview image are not great unfortunately. It looks weird with the label (and without frankly).

![screen shot 2016-11-30 at 01 19 53](https://cloud.githubusercontent.com/assets/211578/20743309/418fea8c-b69b-11e6-87fa-db9e13a3e0af.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![prevmobile](https://cloud.githubusercontent.com/assets/1583842/22733120/4f77c8aa-edf9-11e6-8ac1-efb3cd946c01.gif)
