### ISSUE TITLE
Document how the application runs

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1433]
Here is TheOne (and pretty much anyone) trying to figure out how addons-frontend works:

````
<TheOne> wow, you really need to be familiar with react to even read it :/
<TheOne> where are the actual api calls made?
>> TheOne gives up
````

The app relies on a lot of declarative interfaces which means you can't follow the flow of the program by reading it unless you already know how the declarative APIs work.

Let's make a cheat sheet that summarizes how the application flow works. In other words, let's summarize all the redux / react conventions we use so that someone could understand how the program runs without first having to read all of the upstream library docs.

**Comment by mstriemer** [comment]
The [React developer tools](https://addons.mozilla.org/en-US/firefox/addon/react-devtools/) can be quite useful for figuring out what's going on. You can Inspect Element something and pop over to the React tab and it will show you the JSX it came from in React. If things are being passed in with props you'll have to go up the tree which isn't great but it's at least a starting point.

**Comment by muffinresearch** [comment]
Potentially a q2 issue since this supports making development easier.
