### ISSUE TITLE
Search box is unresponsive until animation ends

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1443]
### Describe the problem and steps to reproduce it:
Types characters are ignored while the magnifying glass is animating.

1. Click on the empty search bar.
2. Immediately start typing.

### What happened?
The first few characters are ignored until the animation ends.

### What did you expect to happen?
The characters I type after clicking should all appear in the search bar regardless of the animation state.

### Anything else we should know?
![uuuuck mov](https://cloud.githubusercontent.com/assets/211578/20768396/64c83fd2-b703-11e6-85fa-e4a384ecfd89.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![instantwrite](https://cloud.githubusercontent.com/assets/1583842/22928243/1b2b4fc6-f2be-11e6-9a36-a9af6cfae61e.gif)
