### ISSUE TITLE
Include eye icon on theme image label

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1444]
The mocks have an eye icon in the label on the theme image. Once we have that asset we should add it to `Icon` and drop it in the label.

> ![screen shot 2016-11-18 at 1 54 57 pm](https://cloud.githubusercontent.com/assets/6797635/20448093/27b31cf4-ad97-11e6-9654-7f4f5900c632.png)

Extracted from #1422 and #1442.

**Comment by pwalm** [comment]
Eye icon is [here](https://github.com/mozilla/addons-frontend/blob/master/assets/eye-icon.svg)

**Comment by madalincm** [comment]
Verified as fixed in FF50(Android 6.0)
Postfix screencast:
![capture _2017-01-26-17-49-58](https://cloud.githubusercontent.com/assets/15685441/22338467/1cd39aae-e3f0-11e6-99be-b5ffa631e0b2.png)
