### ISSUE TITLE
Don't preview a theme if the user wants to scroll

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1445]
### Describe the problem and steps to reproduce it:
Tap the theme header image and try to scroll. The theme is previewed, scrolling does not happen.

### What happened?
The theme header touch events have prevented default so that the user isn't shown a context menu when long pressing but this cancels scrolling too.

### What did you expect to happen?
If I scroll quickly I should get scrolling. If I keep my finger within the theme header image for a few hundred ms I should get a preview.

### Anything else we should know?
![theme-preview-finalish mp4](https://cloud.githubusercontent.com/assets/211578/20771053/828dabba-b70d-11e6-97c7-cb4e1a80ec13.gif)

Extracted from #1422 and #1442.

**Comment by mstriemer** [comment]
@pwalm is it okay if we reduce the touch target to just the button on the image?

We have a fix in mind for this issue but it's a bit of a hack and aren't 100% sure it will work.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
![videotogif_2017 02 06_17 54 19](https://cloud.githubusercontent.com/assets/15685960/22654504/9acf4824-ec95-11e6-89f1-5d1e311a8d7b.gif)
