### ISSUE TITLE
Show users a message about unexpected errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1446]
We have many parts of the code where an error is thrown because of something catastrophic. Even though these typically won't be errors that the user can recover from we should show a message like "oops, an unexpected error occurred."

The error handler added for https://github.com/mozilla/addons-frontend/issues/1032 is probably generic enough to use for that. Perhaps we could hook up `window.onerror()` to catch them (or something like that).

**Comment by aayushsanghavi** [comment]
I would like to work on this. @kumar303 how should I get started with it? Which component or container should I be looking into?

**Comment by muffinresearch** [comment]
For now we are logging in sentry all client-side exceptions so we think that this would be a detrimental UX.

**Comment by kumar303** [comment]
@aayushsanghavi sorry, I somehow missed your comment. Thanks for offering to help! To expand on the last comment, we're worried that showing a user message would be too intrusive since we have a lot of unexpected exceptions getting thrown right now.
