### ISSUE TITLE
Make the build depend on our coverage

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#145]
We should break the build if tests are missing.

**Comment by muffinresearch** [comment]
Aha yes I was just writing it's a bit easier when we have 100% coverage.

**Comment by muffinresearch** [comment]
I'll set coveralls to fail on less than the current coverage level and then when we get to 100% we should update it.

**Comment by muffinresearch** [comment]
OK I've upped the overall threshold to 93% we're currently on 93.7% and the decrease threshold to 0

**Comment by muffinresearch** [comment]
Ok upped to 100% + 0 for the change threshold.

**Comment by mstriemer** [comment]
Is coveralls doing this? I think there's a way to get karma-coverage to fail it. I just pushed an update to a PR and was waiting on coveralls and it seemed to take a while.
