### ISSUE TITLE
Hide focus on install switch when using touch/click

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1458]
### Describe the problem and steps to reproduce it:
A shadow is shown around the slider on the install switch when it is focused. This is only shown for accessibility when navigating with a keyboard so it is not needed when using a pointer to interact with the button.

1. Tap the install switch.
2. Successfully installed!

### What happened?
The shadow is shown.

### What did you expect to happen?
No shadow is shown.

### Anything else we should know?
Using [`:-moz-focusring`](https://developer.mozilla.org/en-US/docs/Web/CSS/:-moz-focusring) instead of `:focus` should fix this. Alternatively, there is a hack we could try where mouse/touch events add a `pointer-detected` class and keydown events clear it.

**Comment by mstriemer** [comment]
This Discourse [1] post shows how you can use `:-moz-focusring` in a backwards-compatible manner.

[1] https://discourse.wicg.io/t/detecting-users-dont-require-visible-focus-rings/804/10

**Comment by muffinresearch** [comment]
The install button doesn't appear to do this anymore.

**Comment by ValentinaPC** [comment]
@muffinresearch : if matters, a focus is shown in about:addons if the pref "`extensions.webapi.testing`" is set to "`true`"
Please see the video: 
![focus](https://cloud.githubusercontent.com/assets/15685960/24154144/063b7ca6-0e59-11e7-8bd6-89b0895ee3a6.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC that's not the slider button that the original issue relates to. Generally mozAddonManager should be available so the slider button is what most people will see here.

**Comment by ValentinaPC** [comment]
Yes, that is why I said "if matters" in my comment.
So I guess not. :)

Marking this verified-fixed.

**Comment by muffinresearch** [comment]
@ValentinaPC ah ok - my bad, thanks!
