### ISSUE TITLE
Support authentication for client side requests

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#146]
We need a way to pass a JWT to the server for client-side requests. We could pull it from a cookie and put it in the state for the client to pick up.

I don't think addons-server supports our long-lived JWTs yet, unfortunately.

**Comment by diox** [comment]
I plan to work on auth in addons-server next week. The login view will probably generate and return a JWT when you, well, log in. Follow https://github.com/mozilla/addons-server/issues/1859 for details.

**Comment by mstriemer** [comment]
https://github.com/mozilla/addons-server/pull/2150 has been merged and it is setting a JWT in the `jwt_api_auth_token` cookie.
