### ISSUE TITLE
Protect function args with invariant

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1461]
We have a lot of functions that protect against incorrect arguments like this:
````javascript
export function doTheThing({ error, id } = {}) {
  if (!id) {
    throw new Error('id cannot be empty');
  }
  if (!error) {
    throw new Error('error cannot be empty');
  }
  ...
}
````
We should use [invariant](https://github.com/zertosh/invariant) instead because that's what it's meant for. It will also give us a bit more granularity about what type of argument we are expecting.

**Comment by kumar303** [comment]
It might be more helpful to focus on moving more parts of the app to Flow instead

**Comment by kumar303** [comment]
In separate discussions, @tofumatt had requested not to use Flow so I'll re-open this.

**Comment by tofumatt** [comment]
Heh, it's definitely made it in more places... I'll happily admit while I wouldn't elect to use it it's caught a few bugs and I've found it handy a fair few times. 😄

But yeah, given we protect a lot of action creators with and without flow, this might still be handy for the "without-flow" bit.

**Comment by kumar303** [comment]
Also, adding Flow coverage to all the test files would be a near impossible feat so I don't think we'd ever get there.

**Comment by muffinresearch** [comment]
@kumar303 @tofumatt where are we at with this? Do you think this is still something we'd like to do?

**Comment by tofumatt** [comment]
Invariant would decrease the size of our bundle by changing our error messages in production, but that’s it. I think it’s worth keeping open but we already throw when required args aren’t supplied in most functions these days.

- Matt (Sent from mobile)

**Comment by kumar303** [comment]
I'm getting a little annoyed with writing `if (!param) { throw new Error(...) }` and adding tests to cover each case so ... 😎

**Comment by kumar303** [comment]
We're using invariant for all new code now.
