### ISSUE TITLE
Use the user's locale for API requests

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#147]
Set the user's locale in API requests. We currently pass `lang=en-US` but this should be set to whatever the user wants for their languages.

We shouldn't need to pass the language to our API helpers but this might not be feasible without some middleware.

It would be really convenient if the API checked the `Accept-Language` header, I'm not sure why we don't do this currently. Caching, maybe?

**Comment by muffinresearch** [comment]
I think AMO uses accept-language when there's no other indicator but it doesn't second guess the user if the user asks for english (via the url) when their headers have fr as a priority for example. The API should probably work the same way.

**Comment by diox** [comment]
The API uses `?lang` because I copied how we did it in Marketplace. It was done that way in Marketplace to work with fireplace caching, which did not rely on headers for its caching (we didn't want the user to get the cached version in the wrong language if they changed their settings).

**Comment by mstriemer** [comment]
The API gives a different response when `lang` is set. If there is no `lang` then all translations are returned (`"name": {"en-US": "My add-on", "fr": "Mon add-on"}}`) vs with a `lang` just the one value is returned (`"name": "Mon add-on"`).

Using `Accept-Language` like the `lang` param might make the "return everything" case not work, although the client could make a point of not setting the header. It is really inefficient to return everything so it's probably a bad default anyway.

**Comment by diox** [comment]
Yeah, the main problem with `Accept-Language` is that the browser always sends it - by relying on `lang` query parameter, the API knows the browser is explicitely asking for a language and can return back a s shorter response with just the appropriate translation - this matters a lot for performance on addons supporting tons of different languages.

**Comment by mstriemer** [comment]
One thing I never liked about the `lang` parameter is it doesn't have a fall back. If the user has `Accept-Language` set to `de,fr;q=0.8,en-US;q=0.5,en;q=0.3` then we should provide French if the add-on doesn't have German. With `lang` I think we'd give the translation that matches the add-ons `default_locale` instead regardless of whether there is a French translation or not.

**Comment by diox** [comment]
Our translations app can not handle such fallbacks anyway. It falls back to the addon default locale and that's it.
