### ISSUE TITLE
WebPagetest Performance Audit

### ISSUE THREAD

**Issue by digitarald** [mozilla/addons-frontend#1471]
Did a quick review of performance in webpagetest and just wanted to kick off the analysis but follow up later with more.

**Thinkpad in Dulles, DSL**: https://www.webpagetest.org/result/161209_S5_17EG/1/details/

On first sight …

## Fonts

On first load while the addons list is visible after 4s, fonts are only loaded after 6.5s; barely making the timeout of 3s font loading timeout for falling back to unstyled text.

<img width="457" alt="image" src="https://cloud.githubusercontent.com/assets/8599/21068403/dbfb1278-be15-11e6-85c6-c837170fcc74.png">

**Possible fix:** Control how fonts are loaded, having a similar looking default font to show first (solved by `font-display`). More ideas are covered in [this guide](https://www.zachleat.com/web/comprehensive-webfonts/). Critical FOFT could reduce the amount of fonts (3 files right now) and file size loaded for meaningful paint.

## Carousel Animation

The carousel sliding in during load causes a second spike of layout and isn't smooth as the page is still loading. Loading the panel during the load cycle (I assume it was supposed to open shortly after load), causes layout jitter and gets in the way of users of actually clicking addons after the meaningful paint.

[From the Chrome timeline](https://www.webpagetest.org/result/161209_GV_17MR/1/details/#waterfall_view_step1): <img width="938" alt="image" src="https://cloud.githubusercontent.com/assets/8599/21068353/89bbbb70-be15-11e6-997b-ad3323894729.png">

**Possible fix:** Have the panel open by default as it is part of the final layout and fill in when the content is loaded

## Carousel

Assets are loaded even if it isn't visible, in this case 2 large background images 50-100kb

**Possible fix:** Defer loading, maybe even to when the carousel is used

<img width="879" alt="image" src="https://cloud.githubusercontent.com/assets/8599/21068661/a8c3b44e-be17-11e6-8863-972cb25f1ff7.png">

## Theme Previews

Previews for 6 themes (below the fold) are loaded before meaningful paint is even done. To make this worse, images sizes are not scaled to how they are displayed. Larger versions range from 50 to 150kb

**Possible fix:** Scale to fit and defer loading

<img width="985" alt="image" src="https://cloud.githubusercontent.com/assets/8599/21068545/c938461e-be16-11e6-8f49-7df5c815c918.png">

## Slow First Byte Time

`867 ms First Byte Time`. Server side issue?

**Comment by tofumatt** [comment]
The site you hit is the current Django site, not the mobile front-end. To get the mobile version you'll need to set a cookie to toggle the new front-end. The name is "mamo" and the value is "on".

**Comment by kumar303** [comment]
Thanks Harald! To clarify what Matt said, you can only see the new site on dev for now: https://addons-dev.allizom.org/ You can click 'view mobile site' at the bottom to toggle the cookie. This new one is in React/Redux and will soon be for desktop too. However, it probably has a lot of performance problems as we haven't had time to start optimizing it yet.

**Comment by digitarald** [comment]
[Re-tested](https://www.webpagetest.org/result/161212_MG_YGM/1/details/) with Firefox & `Slow 3G` setting.

Only one issue still applies, mostly because the other elements are not present.

## Font

Fonts delay loading from 4s to 7s.

<img width="600" alt="image" src="https://cloud.githubusercontent.com/assets/8599/21109802/79e818ec-c04f-11e6-8281-44b7734b7fbb.png">

**Comment by muffinresearch** [comment]
Re-tested on prod and you see most things with good 2g setting on devtools right now I don't think there's anything actionable to do here for mobile pages but we should keep an eye out for possible perf improvements.
