### ISSUE TITLE
Don't clear out search results when running a new search

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1485]
Right now the search results page shows "No results found" in between a loaded set of results and a next page because we remove the results as part of the "start search" action.

We shouldn't clear them out.

Semi-related we should have a loading spinner there.

**Comment by Ryuno-Ki** [comment]
Hm, maybe reducing the opacity or blurring the current search results would made a decent effect as well … assuming you're referring to the search result while typing.

After finishing typing you may want to show a spinner, yes.

There was a Smashing article about [best practices regarding progress indicators](https://www.smashingmagazine.com/2016/12/best-practices-for-animated-progress-indicators/#use-a-progress-indicator-for-any-action-that-takes-longer-than-one-second) recently.

**Comment by vcarciu** [comment]
Verified as fixed : 
![searchmobile](https://cloud.githubusercontent.com/assets/1583842/22703452/e210acaa-ed6c-11e6-8af9-3a9a81edf4bd.gif)
