### ISSUE TITLE
Use named components for icons

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1491]
Currently the `Icon` component works by passing a `name` prop that sets the `className` prop. This would make it fairly easy to try and use an icon that isn't supported. It should instead export a component with the name of the icon.

```jsx
import Icon from 'ui/components/Icon';
<Icon name="magnifying-glass" className="foo" />
// Becomes
import { MagnifyingGlassIcon } from 'ui/components/Icon';
<MagnifyingGlassIcon className="foo" />

**Comment by tofumatt** [comment]
We discussed this and I think the move to better SVG handling will fix the issues with named icons.
