### ISSUE TITLE
Test platform code for introspecting an add-on is installed

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#15]
In https://bugzilla.mozilla.org/show_bug.cgi?id=1245571 we are allowing AMO access to see if the add-on is installed. We'll need to make sure we are able test that this works as expected in the disco pane. Because this requires Firefox changes if there is any issues, let's make sure that we can test this relatively soon after that bug lands.

**Comment by Mossop** [comment]
Test builds with window.navigator.AddonManager.getAddonByID working are available here https://archive.mozilla.org/pub/firefox/try-builds/dtownsend@mozilla.com-d7ae286883297eab30cf8a8d02fe1cc9e99759fd/

No need to wait to check things work!

The preference extensions.webapi.testing set to true will make this work on AMO dev and staging sites.

**Comment by andymckay** [comment]
That link goes to the build logs, but I couldn't see any builds to download. I tried clicking around in try to find it here: https://treeherder.mozilla.org/#/jobs?repo=try&author=dtownsend@mozilla.com&selectedJob=17842383, but couldn't find the build.

**Comment by Mossop** [comment]
Try this one https://archive.mozilla.org/pub/firefox/try-builds/dtownsend@mozilla.com-3eb5b9baec15a7ecab29bb446bd2de8917a5a4a8/

**Comment by Mossop** [comment]
This should work better https://archive.mozilla.org/pub/firefox/try-builds/dtownsend@mozilla.com-d3e499d71292bb46143426ca895ed2ea1a437028/

**Comment by andymckay** [comment]
A quick test, worked just great, when run against AMO. Thanks @Mossop.

https://www.dropbox.com/s/6qkuryxqtgj6q0s/Screenshot%202016-03-17%2009.42.55.png?dl=0

```
var lookup = window.navigator.AddonManager.getAddonByID('mute-all-inactive-tabs@evilpie.tomschuster.name');
lookup.then(
  function(addon) { 
    if (!addon) {
      console.log('no add-on found');
    } else {
      console.log(addon);  
    }
  }
);
```

**Comment by andymckay** [comment]
Update: `window.navigator.AddonManager` is now `window.navigator.mozAddonManager`

**Comment by muffinresearch** [comment]
We tested this closing.
