### ISSUE TITLE
Make callApi() cope with URLs that have trailing slashes

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1511]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Write some code that sends a URL with a trailing slash to [callApi()](https://github.com/mozilla/addons-frontend/blob/master/src/core/api/index.js#L33)

### What happened?

It appends `/?lang=` to the end which looks something like `/your/url//?lang=` and this results in a fetch error like this:

Fetch API cannot load http://olympia.dev/api/v3/addons/addon/chillout-page-action/reviews//?lang=. Redirect from 'http://olympia.dev/api/v3/addons/addon/chillout-page-action/reviews//?lang=' to 'http://olympia.dev/api/v3/addons/addon/chillout-page-action/reviews/?lang=' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

It's a CORS error because it's trying to do a redirect.

### What did you expect to happen?

It should probably just strip the slash.

**Comment by Ryuno-Ki** [comment]
Isn't that a _leading_ slash? O_o

**Comment by SeanPrashad** [comment]
Hey guys, I'd like to try taking this one on! I think we could use [`str.endsWith()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith) to check for the forward slash character and strip it, if present.

[`callAPI()`](https://github.com/mozilla/addons-frontend/blob/146ee1c93ea5b99414b81926016fb587c7d08a90/src/core/api/index.js#L83) now lives over here:

https://github.com/mozilla/addons-frontend/blob/146ee1c93ea5b99414b81926016fb587c7d08a90/src/core/api/index.js#L83

We'll also need to update the tests over [here](https://github.com/mozilla/addons-frontend/blob/674e4a49c5535f380320bdd8340f7077c4738121/tests/unit/disco/test_api.js#L12)!

**Comment by SeanPrashad** [comment]
Ok so I got a chance to dig into this and it might already be solved..

10 months ago, 2c5cfa4703b8639194ea3eb7dcd1de59308d3f51 introduced code that handled trailing slashes here:

https://github.com/mozilla/addons-frontend/blame/2c5cfa4703b8639194ea3eb7dcd1de59308d3f51/src/core/api/index.js#L159-L160

but we only add a trailing slash if none is present:

```js
adjustedEndpoint = adjustedEndpoint.endsWith('/')
	? adjustedEndpoint
	: `${adjustedEndpoint}/`;
```

Would love a second opinion on my findings!

**Comment by kumar303** [comment]
Yes, whoops. Looks like it was fixed in https://github.com/mozilla/addons-frontend/pull/4117
