### ISSUE TITLE
"How are you enjoying your experience?" is localised with a &nbsp; in French

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1513]
There should just be a regular space before the "?" in the sentence but the localisation includes a `&nbsp;` instead, which we escape and thus display as escaped text in French.

This happens on the add-ons details page (example link: https://addons-dev.allizom.org/fr/firefox/addon/test-ie/)

See attached screenshot:

<img width="321" alt="screenshot 2016-12-21 16 29 45" src="https://cloud.githubusercontent.com/assets/90871/21397260/fe6deaa4-c79a-11e6-8e8c-d728f9733e6a.png">

-----

We may want to point out to localisers that we can't accept HTML in our most of our translations, I'm thinking.

**Comment by Ryuno-Ki** [comment]
Would the Unicode character be accepted (not as HTMl entity)?

**Comment by tofumatt** [comment]
I would think yes. I haven't explored the cause too much, just filing here
for posterity. Why?

- tofumatt

**Comment by Ryuno-Ki** [comment]
You could provide a comment which reads

> Please copy and paste the following character for non-breaking space ([U+00A0](http://www.fileformat.info/info/unicode/char/00a0/index.htm)) where appropriate: "  "

**Comment by ValentinaPC** [comment]
Verified as fixed on FF51(Android 6.0.1)
Postfix screenshots for `it` and `fr`:
![2017-02-20_1149](https://cloud.githubusercontent.com/assets/15685960/23119898/cb25000e-f762-11e6-8d26-dbcf037e07dc.png)
![it](https://cloud.githubusercontent.com/assets/15685960/23119899/cb294100-f762-11e6-8d69-79119eb369ea.png)
