### ISSUE TITLE
Test for regressions from redux 5.x

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1522]
Redux 5.x breaks the `withInstallHelpers()` HOC. The updates were reverted in #1520.

This could be due to the discoResults reducer setting an `addon` property to the guid which overrides the `addon` object later, or it could be that `mapStateToProps()` from a parent isn't setting `ownProps` for the child like it was before.

**Comment by willdurand** [comment]
We use `react-redux` 5.x for a while now.
