### ISSUE TITLE
Tidy up all test descriptions so they're easy to scan

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1525]
Our test descriptions are mostly good but it'd be great if we used file paths/names everywhere (or in most places) and possibly always used `<ComponentName>` for components.

We're mostly good about it but not perfect. Filing this so I remember to comb through the tests some day and tidy things up.

(From: https://github.com/mozilla/addons-frontend/pull/1493#discussion_r93521566)

**Comment by kumar303** [comment]
We should also look into a mocha reporter that shows test file and function. Maybe it exists, I'm not sure. BDD sentences are nice but they don't always help you find the source code when stack traces are dangling from the event loop.

**Comment by muffinresearch** [comment]
Closing this in favour of trying to find a more useful reporter.
