### ISSUE TITLE
Add title to review entry, update styles

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1526]
The review entry form has changed a bit in the latest Sketch file. We need to bring the style up to date and also add title entry which wasn't there before.

Here is the mock but check the Sketch file for the latest:

![screenshot 2016-12-22 15 10 00](https://cloud.githubusercontent.com/assets/55398/21440509/ee00c128-c858-11e6-8631-7f8e09b21839.png)

**Comment by vcarciu** [comment]
With keyboard open, the scroll should work inside _Write a review_ form , because else you will not be able to submit the review : 
![scrollreview](https://cloud.githubusercontent.com/assets/1583842/22787913/9ade03e8-eee6-11e6-9072-9085aa3618fa.gif)

**Comment by kumar303** [comment]
@vcarciu D'oh. Good catch, thanks. Can you open a new bug for this? That will make it easier to track because https://github.com/mozilla/addons-frontend/issues/1739 is about to land soon as well (which will remove the title).

**Comment by vcarciu** [comment]
@kumar303 : logged https://github.com/mozilla/addons-frontend/issues/1773

**Comment by kumar303** [comment]
Thanks
