### ISSUE TITLE
Invalid OAuth parameter: state (when signing in after error)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1528]
### Describe the problem and steps to reproduce it:

* Click the login button at the top right
* enter an invalid email or something that will fail
* you now see a screen telling you the login failed
* Click the Login button from the content to try again (not from the top right)
* Sign in with a valid account

### What happened?

FxA says shows an error on their sign-in page saying: Invalid OAuth parameter: state

### What did you expect to happen?

It should log me in

### Anything else we should know?

The log in works in normal cases

**Comment by muffinresearch** [comment]
@kumar303 is this specific to the mobile app?

**Comment by kumar303** [comment]
I can no longer reproduce this; I can't get past the FxA screen with an invalid account or an invalid password. I think this bug was filed before FxA was hooked up correctly so I'm just going to close it.

**Comment by externl** [comment]
I'm currently seeing this with an account I created recently. Should I open a new issue?
![screen shot 2017-11-15 at 4 39 34 pm](https://user-images.githubusercontent.com/2126835/32861785-d0d6b31e-ca23-11e7-95e2-76a44911aa3d.png)

**Comment by kumar303** [comment]
Hmm, I can't use the steps up above to reproduce it so I'm not sure if it's the same bug.

@externl are you able to sign in to https://addons.mozilla.org/ at all? Does it happen every time? Does it happen when you sign in to https://addons.mozilla.org/en-US/developers/ ?

**Comment by externl** [comment]
- https://addons.mozilla.org/  works
- https://addons.mozilla.org/en-US/developers/  works

After trying both of those, https://accounts.firefox.com/oauth/ seems to be working too!

**Comment by willdurand** [comment]
could it be that the newly created account was not propagated?

**Comment by AlexandraMoga** [comment]
Tried to reproduce this with several scenarios but the error was not triggered

**Comment by externl** [comment]
If it helps I created the account by:
- Installing Firefox 
- Open preferences -> Firefox account
- Sign in, then create account
