### ISSUE TITLE
Add "Featured" search page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1535]
https://github.com/mozilla/addons-frontend/pull/1493#discussion_r93798968 points out that we need to link to the popular and top rated searches for the "More popular add-ons" and "More highly rated add-ons" links on the landing pages (#1285 and #1286).

I'm not sure we have a "Featured" page (eg, can it be done using a search) or if we need to create a page with pagination that loads all featured add-ons.

Alternately–do we even want a "more featured add-ons" search page? A big list of "featured" add-ons almost seems odd to me, but I guess we can tackle that later as it isn't hard to build.

**Comment by tofumatt** [comment]
Actually, [Featured add-ons are sorted randomly](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#featured) and like I mentioned it's weird to have a search of featured add-ons... so we can build out a page of featured add-ons but it's going to be a weird UX as the landing page of 5 add-ons could have different results than the full page.

Anyway, I'll build out the featured page, but yeah... maybe we need to tweak the API for this? Or get all featured add-ons with a large `page_size` argument to `/api/v3/addons/featured/`

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (Android 6.0.1)
Postfix screenshots (featured extensions and featured themes pages):
![fe](https://cloud.githubusercontent.com/assets/15685960/22683069/dee911a0-ed1e-11e6-883c-76a6675f3e09.png)
![ft1](https://cloud.githubusercontent.com/assets/15685960/22683068/dee89a04-ed1e-11e6-922e-06547876df50.png)
