### ISSUE TITLE
Camel case API responses in a consistent fashion

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1536]
### Describe the problem and steps to reproduce it:
Currently the [`DiscoPane`](https://github.com/mozilla/addons-frontend/blob/6d4258986c9343b58b0fa59856de72df01fe8a1c/src/disco/containers/DiscoPane.js#L123) component is camel casing the add-on keys when they are passed into the child component. On AMO we have not been camel casing keys at all.

### What happened?
The `showInfo` helper expects an `iconUrl` in `ownProps` but AMO provides `icon_url`.

### What did you expect to happen?
AMO should provide `iconUrl` or disco should provide `icon_url`.

### Anything else we should know?
We should be consistently camel casing in API responses or in reducers. Doing it in [`callApi`](https://github.com/mozilla/addons-frontend/blob/6d4258986c9343b58b0fa59856de72df01fe8a1c/src/core/api/index.js#L73) would be a one line change (other than fixing all the code we broke):

```js
    .then(({ response, jsonResponse }) => {
      if (response.ok) {
        return camelCaseProps(jsonResponse);
      }
```

The `camelCaseProps` helper will only do one level of keys, so we should make that function recursive or use [humps](https://www.npmjs.com/package/humps) instead which provides a `camelizeKeys` helper that will perform the operation on nested objects too.

**Comment by muffinresearch** [comment]
Discussing this we prefer not to break the relationship between props and the real api responses.
