### ISSUE TITLE
API calls for themes are using "theme" and not "persona" 😠

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1545]
So I'm using `theme` in most places for tests and also actual API calls in the app but lightweight themes, the kind we want to fetch, are `type: 'persona'`. So that needs to be changed.

cc @diox: I assume there's no way to change the API at this point and rename `theme` to `oldTheme` or `completeTheme` as this'll be a weird relic going forward and presumably we're the biggest API consumer?

**Comment by diox** [comment]
We could change it in the API, but that'd mean introduce a special case for the new API while the rest of addons-server uses `persona`, so I'm reluctant to do it - I feel it'd make things quite confusing in addons-server land.

**Comment by tofumatt** [comment]
No problem, @mstriemer and I were chatting about it and we'll likely just use `theme` internally but convert that to `persona` when we make the API calls. I mean we should have constants mostly anyway but for things like URLs where we have `/extensions/` and `/themes/` I don't want to use `/personas/`.

Cool, all good!
