### ISSUE TITLE
Long author names float icon too far to the right

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1546]
### Describe the problem and steps to reproduce it:
Have a long author name in the search results

### What happened?
The icon is pushed (partially) off-screen.

### What did you expect to happen?
The author name should wrap and not affect icon positioning.

### Anything else we should know?
Seems I made this with floats but really should use flexbox; I'll update the styles and it should fix it.

### Screenshot

<img width="308" alt="screenshot 2016-12-30 17 29 01" src="https://cloud.githubusercontent.com/assets/90871/21569542/aa1dce0c-ceb5-11e6-98aa-841e3e0fd772.png">

**Comment by aniketkudale** [comment]
I'd like to work on this!

**Comment by tofumatt** [comment]
Hi @aniketkudale, sounds good! We can't assign issues to people outside the organisation on GitHub, but feel free to work on this and send a PR when it's ready.

**Comment by Ryuno-Ki** [comment]
@tofumatt Maybe introducing a label as workaround? Something like __assigned__?

**Comment by aayushsanghavi** [comment]
@tofumatt any progress on this issue? If not, would it be fine if I worked on it?

**Comment by tofumatt** [comment]
@aayushsanghavi No progress yet, if you wanted to work on it that would be awesome! 👍

**Comment by mstriemer** [comment]
If someone's feeling ambitious there is a similar bug on the add-on detail page which references the same add-on #1607.
