### ISSUE TITLE
Logging out from addons-server does not log you out from addons-frontend

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1557]
### Describe the problem and steps to reproduce it:

* Go to https://addons-dev.allizom.org as a desktop site.
* Login
* Click view mobile site link in the footer.
* Note the link "logout" is present in the header.
* Clicking logout sent me to the FXA auth page.
* Going to the desktop site I could logout
* Returning to the mobile site it was still showing "logout".

### What did you expect to happen?

* Clearing cookies was required to restore the correct logged out state.
* The logged-in state should stay in-sync between desktop and mobile.
* The mobile page Logout link should logout and not send the user to the login page.

**Comment by muffinresearch** [comment]
Note: Fxa for -dev seems to have broke (JS error) - so maybe that's related?

**Comment by ValentinaPC** [comment]
@muffinresearch : going on https://addons-dev.allizom.org from you mobile device and logging in, you will not me able to **log out** because clicking on the "Log Out" button will redirect you to FxA "_Sign in_" page.
Is this a correct behavior? Not being able to log out only from desktop site? Thanks!

**Comment by mstriemer** [comment]
This is not intended. I'll split that into its own bug though, thanks.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Win 7, Android 6.0.1) for the STR described and the result:
> The logged-in state should stay in-sync between desktop and mobile.
Postfix video:
![logout](https://cloud.githubusercontent.com/assets/15685960/23120590/9dcb7af4-f765-11e6-9c2e-b8b8b6fdc429.gif)
