### ISSUE TITLE
Review homepage categories and icons

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1560]
Not all of the homepage categories in the mocks mapped to categories that we have data for in #1538. If we'd like to maintain those categories we'd need to come up with some way of creating them or curating the content (this is definitely out of scope).

I updated the 2 extension and 1 theme categories that didn't map well:

Extensions:
**Save stuff** became **Find news** (Feeds, News & Blogging)
**Share stuff** became **Play games** (Sports & Games) -- these are mostly for game info/streaming stuff.

Themes:
**Mystical** became **Solid** (Solid)

If there are other categories or strings or icons that we would like to use, please let us know here.

![screen shot 2016-12-29 at 16 36 07-fullpage](https://cloud.githubusercontent.com/assets/211578/21556292/f7a9e16e-cde4-11e6-8189-7dc318da70ff.png)

**Comment by pwalm** [comment]
@mstriemer Icons coming!

**Comment by pwalm** [comment]
Icons are [here](https://github.com/mozilla/addons-frontend/tree/master/assets/collection%20icons)

**Comment by mstriemer** [comment]
@pwalm is there a different icon we can use for fashion? Since it's taller than it is wide it pokes out under the text and there's no easy way of making it fit (I think it's possible but if there's another icon that works it'd save me half a day).

I also really wish the die were square, but this is likely outside of our control.

**Comment by mstriemer** [comment]
Screenshot without tweaking the fashion CSS (I don't think I can fix it in CSS).

![screen shot 2017-01-03 at 15 49 24-fullpage](https://cloud.githubusercontent.com/assets/211578/21624357/4f4a289e-d1cc-11e6-8285-9c0f139a0877.png)

**Comment by tofumatt** [comment]
Not to design by committee, but I too think the dice needs a bit of angle
to it; it takes awhile to read as dice in my mind. Maybe it’s a bit too
“flat”? Anyway, it just seems a bit hard to read as dice.

**Comment by pwalm** [comment]
Changed the dice to a game controller. Updated file.

**Comment by pwalm** [comment]
Also changed dress to a shirt for "fashionable"

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix screenshot: 
![h1](https://cloud.githubusercontent.com/assets/15685960/22683568/1f5c144c-ed21-11e6-97e7-dff4a665b268.png)
