### ISSUE TITLE
When user closes video on add-on discovery pane, the hover over the theme immediately triggers theme preview

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1561]
Refiled from https://bugzilla.mozilla.org/show_bug.cgi?id=1327151

### Describe the problem and steps to reproduce it:

1. Open about:addons
2. Click on the video to open it
3. Hover mouse over the (sic!)link "Close video", then click left mouse button

### What happened?

All UI twitches badly, and all tabs blink to irrelevant color and back

### What should happen?

Tabs shouldn't blink. That's too strange result for clicking on a button-link to close the video

This is regression. Firefox 47 is unaffected, Firefox 48 is affected.

### Anything else we should know?

My Info:   Win7_64, Nightly 49, 32bit, ID 20160526082509

**Comment by muffinresearch** [comment]
@pwalm could we consider moving the close link to prevent this behaviour?

**Comment by pwalm** [comment]
Sure? Don't know about this issue, I can't reproduce it. And the tabs kinda twitch around anyway. We could turn the text link into an "x" in the top R corner of the video when expanded.

**Comment by muffinresearch** [comment]
I think the issue is more that the mouse causes the hover theme preview due to being positioned over the first theme when the video is closed.

**Comment by ValentinaPC** [comment]
Verified as fixed on about:addons set for -dev using FF51(Win 7) and theme preview is not triggered automatically when closing the video.
Postfix video: 
![themehover-autotrigger](https://cloud.githubusercontent.com/assets/15685960/22638510/357dcf02-ec51-11e6-996a-a477bf736f98.gif)
