### ISSUE TITLE
On loading disco pane big blue buttons appear

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#1568]
Open disco pane and watch it load. Upon loading you will see big blue buttons first that then disappear and the actual on/off install toggles appear. (see gif)
![disco-pane-load-20170105](https://cloud.githubusercontent.com/assets/8145891/21692590/daefa182-d37d-11e6-9c32-989f33322041.gif)

I did expect no blue buttons to appear at first, but only see the toggles.

It is confusing to see something appear only to be gone before I know what it is/was.

**Comment by muffinresearch** [comment]
@mstriemer could you investigate this and see about improving on it - it's pretty jarring.

**Comment by mstriemer** [comment]
Ugh, that is gross. I'd rather not user agent sniff but it might make sense to guess at whether `mozAddonManager` will be available on the server and render the right button.

If the user doesn't have javascript and we default to the switch then the switch won't work at all. I guess we could throw some extra styles in a `<noscript>` block and render both 😖.

**Comment by muffinresearch** [comment]
If this is ready today we should look to pick this on the the Tuesday reviewer tools push.

**Comment by ValentinaPC** [comment]
Verified this using FF50.1 (Win 7) and FF53.0a1 (Win 7)
- about:addons set for -dev -  the big blue buttons are displayed for a sec
![n-dev](https://cloud.githubusercontent.com/assets/15685960/21802747/a5364e64-d72f-11e6-9226-8d50328a01e4.gif)
- about:addons set for -stage - the big blue buttons are not displayed
![n-stage](https://cloud.githubusercontent.com/assets/15685960/21802756/ad90df70-d72f-11e6-90b3-f3e4afb51628.gif)

Note: both cases were made with new and clean profiles.

**Comment by AlexandraMoga** [comment]
This is not reproducing anymore on any of the servers.
