### ISSUE TITLE
If installing a theme from Disco Pane, the author will not be displayed in More section for that theme

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1572]
Moved from mozilla/addons-server#4236.

Steps to reproduce:
1.On latest Aurora , go to about:addons and install Ice Flower theme
2.From Disco Pane - Appearance press More button for the newly installed theme
3.Remove the theme and install exactly same theme from AMO (https://addons.mozilla.org/en-US/firefox/addon/ice-flower-265447/?src=ss)
2.From Disco Pane - Appearance press More button for the theme installed from AMO

Expected results:
Same info are presented in More section for both installations

Actual results:
If installed from Disco Pane, the More section will not show the author , but if installed from AMO the Disco Pane will show it

Please see video for this bug:

![discopane](https://cloud.githubusercontent.com/assets/1583842/21723991/39c786b2-d43b-11e6-8ff3-d20227b75795.gif)

**Comment by mstriemer** [comment]
The `author` property is missing from the `data-browsertheme` JSON that we set on the install button.

This is set in the [`getThemeData()`](https://github.com/mozilla/addons-frontend/blob/4015ee5027aa84c38ff9e48ce27f234708f66863/src/core/themePreview.js#L14) helper in `core/themePreview`. The author should be available here so adding it to the function definition and returning it should be all that is required along with updating the tests.

**Comment by wagnerand** [comment]
The mentor for this bug is: @mstriemer 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by aayushsanghavi** [comment]
I'd like to take this up.

**Comment by aayushsanghavi** [comment]
@mstriemer where is the data returned from themePreview being displayed, which file? We will have to update it there too right? And you mentioned "updating the tests" in your comment; what is to be done with respect to that?

**Comment by mstriemer** [comment]
Hi @aayushsanghavi, the only change that needs to be made is in `src/core/themePreview.js`. It looks like the `getThemeData` function isn't actually tested though.

If you inspect at a button on the discovery pane you should see it has a `data-browsertheme` attribute with some JSON data. Currently that wouldn't have `author` in it but after updating `getThemeData` it should have author in it.

The buttons are from [`InstallButton` (blue button)](https://github.com/mozilla/addons-frontend/blob/master/src/core/components/InstallButton/index.js#L38) and [`InstallSwitch`](https://github.com/mozilla/addons-frontend/blob/1b8b6026695ba6c23029db32f01ae1eb27fda3f4/src/core/components/InstallSwitch/index.js#L103) but you shouldn't need to update either of those.

**Comment by vcarciu** [comment]
This is not entirely fixed. If installing from add-ons manager, the description of theme is not listed in about:addons : 
![difffrominstall](https://cloud.githubusercontent.com/assets/1583842/24802564/19ab4e8c-1bb1-11e7-8d09-233bf828d356.gif)

**Comment by aayushsanghavi** [comment]
@tofumatt @mstriemer we're just missing a description variable [here](https://github.com/mozilla/addons-frontend/blob/master/src/core/themePreview.js#L16), aren't we?

**Comment by tofumatt** [comment]
@aayushsanghavi Actually looks like you did the right thing with your fix but the browser behaviour has changed.

It appears we're using the key `"author"` same as legacy AMO–compare the `data-browsertheme` attribute on https://addons.mozilla.org/en-GB/firefox/addon/abstract-color-splash/ for both legacy and mobile.

I installed this theme from old and new AMO and it missed the author info for both. So it seems like a Firefox bug.

**Comment by tofumatt** [comment]
Oh okay I understand now. Ignore my old comment for now, it also seems my Firefox is messed up re: theme installs so we'll leave my issues alone for now.

@aayushsanghavi yes adding `description` to that filter function should hopefully do the trick and fix this author bug as well.

**Comment by vcarciu** [comment]
Verified as fixed : 
![them](https://cloud.githubusercontent.com/assets/1583842/25706583/8029a12a-30e9-11e7-8827-74538f88ec06.gif)
