### ISSUE TITLE
Load our JS bundle with `async`

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1574]
Currently our script tag looks like this:

```html
<script src="https://addons-discovery.cdn.mozilla.net/disco-6fc7e9484a5f0795d9fa.js" integrity="sha512-+OioMJzA4dH5W6bZpMqtKRBSkyA0l40oWyudOnw4eTkQs43tZNXQyHix1LGdSzCZBXFR+5YIntfoS+swF7azqg==" crossorigin="anonymous" data-reactid="13"></script>
```

This means rendering will be blocked on loading this JS, defeating much of the benefit of server-side rendering.

We should add an `async` attribute to that.

**Comment by mstriemer** [comment]
It seems that we might be fine without `async` since the tag is the last thing on the page. CSS Tricks [1] says it doesn't make a difference (mostly) but they also link to an Ilya Grigorik article [2] that suggests that it might be a good idea since it will execute the script earlier which could provide a speed-up.

[1] https://css-tricks.com/async-attribute-scripts-bottom/
[2] https://www.igvita.com/2014/05/20/script-injected-async-scripts-considered-harmful/#comment-1398899164

**Comment by kumar303** [comment]
I read an article once (that I can no longer find) saying to always use `async` because the JavaScript parsing time is significant. Although I can't recall exactly how that applies to scripts at the bottom of the page.

**Comment by muffinresearch** [comment]
We'd need to prove adding async improved things, closing for now since it's unlikely that this will bubble up in priority.
