### ISSUE TITLE
Yarn installs packages and defaults to versions starting with ^

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1587]
We turned this off for npm so we get explicit versions. 

So the question is, is there something that needs changing in the yarn config to get the same setup or does the lock file mitigate the need to lock down versions, in which case should the npm package.json be updated?

**Comment by kumar303** [comment]
That's really odd. I could have sworn I fixed this in another repo by adding `.npmrc`. In other words, I thought yarn honors `.npmrc`.

**Comment by muffinresearch** [comment]
Yeah could be yarn version specific too (since it's probably getting updated quite quickly) , so we could compare notes on that.

I have 0.17.10.

**Comment by mstriemer** [comment]
Looks like there is a `yarn config` command.

```
$ yarn config list
yarn config v0.18.1
info yarn config
{ lastUpdateCheck: 1484071239974,
  'version-tag-prefix': 'v',
  'version-git-tag': true,
  'version-git-sign': false,
  'version-git-message': 'v%s',
  'init-version': '1.0.0',
  'init-license': 'MIT',
  'save-prefix': '^',
  'ignore-scripts': false,
  'ignore-optional': false,
  registry: 'https://registry.yarnpkg.com',
  'strict-ssl': true,
  'user-agent': 'yarn/0.18.1 npm/? node/v4.7.1 darwin x64' }
info npm config
{ 'save-prefix': '' }
✨  Done in 0.08s.
```

So the `save-prefix` between yarn and npm is different. Unfortunately running `yarn config set save-prefix ''` doesn't seem to modify any files locally, but I just copied the file over to addons-frontend from `~` and it works. I don't see a `--local` flag but maybe it's there, I didn't try.
