### ISSUE TITLE
More touch ups to detail, search and header

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1597]
From comments in #1570.

- [x] copy should be larger and white in the search bar
- [x] "by [developer name]" should be the same size as the extension name
- [x] let's use the "read more" button at the bottom of the "about this extension" block instead of the faded text under the link. We'll still keep the fade, but can we make it shorter? Like, 20px transition.
![screen shot 2017-01-06 at 3 52 41 pm](https://cloud.githubusercontent.com/assets/6797635/21736811/3b213778-d428-11e6-86db-b99bcceb2b02.png)
- [x] some body copy looks grey, it should all be #000000
- [x] One big, site wide thing: Can we change the blue header zone to dark grey? Things will clash less and the switch will stand-out better.
![screen shot 2017-01-06 at 3 54 51 pm](https://cloud.githubusercontent.com/assets/6797635/21736845/7c121e28-d428-11e6-8863-3ff4391a933f.png)
top: #343A40
search bar: #495057

**Comment by ValentinaPC** [comment]
> copy should be larger and white in the search bar
@mstriemer : Not sure what "copy" means in this context.

I verified the other things in FF51(Android 6.0.1) and look good.
Postfix screenshots:
![touch](https://cloud.githubusercontent.com/assets/15685960/23605536/cc6b1738-0265-11e7-92bd-2167106434c6.png)
