### ISSUE TITLE
Load noscript styles through webpack

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1598]
I started trying to load the noscript styles through webpack but unfortunately it looks like we can't get the raw CSS bundle from webpack-isomorphic-tools. There may be a way to do it but it seems difficult/unlikely.

If we support webpack 2 we could likely switch to universal-webpack [1] which is by the same author and seems to integrate with webpack a little better. They provide documentation on how to avoid the flash of unstyled content that we have in development mode and I believe we could use a similar technique to extract the CSS bundle for noscript styles.

Initial work on this is in #1594.

[1] https://github.com/halt-hammerzeit/universal-webpack

**Comment by muffinresearch** [comment]
@mstriemer Not sure if this is still relevant if it is can you reopen and add more info pls?

**Comment by mstriemer** [comment]
We're still including noscript styles so I'd say it's still relevant. If we never have a need to add to them then this is probably not worth the effort.

There would be two benefits to doing this:

1. Less repetition since we can `@import "ui/componenets/InstallButton/noscript"` instead of having a copy of the same file for disco and amo.
2. Webpack will strip comments and shorten the CSS to reduce overall page size (with this amount of CSS this is probably not a huge win but would be the best thing to do).

No script styles are in [amo/noscript.css](https://github.com/mozilla/addons-frontend/blob/67172d02f9022bfcd7025431215ab54f27a9680d/src/amo/noscript.css) and [disco/noscript.css](https://github.com/mozilla/addons-frontend/blob/67172d02f9022bfcd7025431215ab54f27a9680d/src/disco/noscript.css).
