### ISSUE TITLE
Throw an error for relative links

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1601]
### Describe the problem and steps to reproduce it:

Create an instance of `amo/components/Link` with a relative path (i.e. not beginning with a slash), like:

    <Link to="somewhere/relative">Some text</Link>

### What happened?

It will render an anchor and you can click it but it doesn't do anything. It changes the URL but does not update the route. The [react-router docs](https://github.com/ReactTraining/react-router/blob/master/docs/API.md#link) say that relative paths are unsupported.

### What did you expect to happen?

It should throw an error explaining that relative paths are unsupported.

**Comment by kumar303** [comment]
We should try this to see if relative links are still broken after updating the router in https://github.com/mozilla/addons-frontend/issues/2161

**Comment by willdurand** [comment]
RR v4 now throws an error:

```
 Caught application error: Error: ""to" prop cannot contain a relative path; it must start with a "/"."
```

**Comment by AlexandraMoga** [comment]
Could you please add STR to this issue or the label "qa:not needed"?
Thanks
