### ISSUE TITLE
Check that all API requests have withErrorHandling

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1605]
We need to make sure all our components/API requests use error handling for mobile v1 until we get #1484 done.

**Comment by kumar303** [comment]
The tricky thing is that `withErrorHandling` doesn't support any `asyncConnect` API interaction. Related: https://github.com/mozilla/addons-frontend/issues/1521

**Comment by kumar303** [comment]
When looking at this, you can ignore any component that relies solely on `asyncConnect` because error handling for that will be covered in https://github.com/mozilla/addons-frontend/issues/1521
