### ISSUE TITLE
Long author names cause horizontal scrolling

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1607]
A long author name without spaces will cause the page to have horizontal scrollbars. This text should wrap instead. Check the same thing for the add-on name too.

See https://amo.addons-dev.allizom.org/en-US/firefox/addon/update-scanner/.

**Comment by aayushsanghavi** [comment]
@mstriemer thanks for suggesting this bug. I'll take it up.

**Comment by vcarciu** [comment]
Verified as fixed : 

![dragn](https://cloud.githubusercontent.com/assets/1583842/22939940/ff871450-f2e8-11e6-9647-b21e74520e06.png)
