### ISSUE TITLE
Localise user count in search results

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1608]
The user count in search results is not localised the same as it is on the detail page.

<img width="361" alt="screen shot 2017-01-12 at 10 41 43 am" src="https://cloud.githubusercontent.com/assets/211578/21898849/cc8f4a12-d8b3-11e6-9085-c91f6a059675.png">
> Search page

<img width="364" alt="screen shot 2017-01-12 at 10 41 27 am" src="https://cloud.githubusercontent.com/assets/211578/21898850/cc971ce2-d8b3-11e6-84ea-4d831feb43da.png">
> Detail page

The search results should have a comma in the number in English, `606,461 users` rather than `606461 users`.

**Comment by cosminbadescuSV** [comment]
The user count has a comma in search results for the numbers of users,  this issue is verified as fixed on AMO-dev on FF51.0 (Android 7.1.1).
Postfix video: 
![numbers](https://cloud.githubusercontent.com/assets/15885467/22507998/b571793a-e890-11e6-8bc9-eebc8e67f9ec.gif)
