### ISSUE TITLE
Re-implement the configuration for auto-prefixing (via postcss-loader)

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1609]
Since the post-css auto-prefixing config was originally setup postcss-loader looks like it has changed. As a result it's likely that the auto-prefixing is not working additionally this was causing an error in the uitests. (See https://github.com/mozilla/addons-frontend/pull/1596)

`postcss-loader` allows for a standalone config file. It also allows for config via webpack. 

We should remove the standalone config file and re-implement/check the configuration via webpack and make sure amo gets cross-browser css prefixes when built, and disco pane doesn't (because the audience for the disco pane is just Firefox).

If postcss-loader gets the config as expected then it should stop complaining about the missing config.

A boolean config value controls the setup of the config here: https://github.com/mozilla/addons-frontend/blob/master/webpack.prod.config.babel.js#L141

The current docs for postcss setup are here: https://github.com/postcss/postcss-loader#webpack-1-1

**Comment by kumar303** [comment]
Also, maybe we should run the auto-prefixed in all environments, not just prod? Seems like it might be good to prevent any surprises.

**Comment by muffinresearch** [comment]
> Also, maybe we should run the auto-prefixer in all environments, not just prod? Seems like it might be good to prevent any surprises.

It should be since the dev webpack config is inherited from the production one it just needs DRY'ing up so that less config is repeated.
