### ISSUE TITLE
Sort appears in category pages but doesn't work

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1626]
### Describe the problem and steps to reproduce it:
Visit http://localhost:3000/en-GB/firefox/extensions/feeds-news-blogging/ and activate the search sort.

### What happened?

Nothing.

### What did you expect to happen?

The sort should work... or it shouldn't appear (but the former is better).

### Anything else we should know?
The URLs are largely hooked up properly (though there is some erroneous data in there), but the params are likely just not passed through.

-----

![sortmobile](https://cloud.githubusercontent.com/assets/1583842/22699144/4c314968-ed5f-11e6-9b99-564e06851c09.gif)

**Comment by tofumatt** [comment]
Turns out the kinds of sorting we do by default is different in categories as well.

For now (v1) I'm going to hide this on the non-search pages. We can improve sort in v2.

**Comment by vcarciu** [comment]
Verified as fixed : 
![nosort](https://cloud.githubusercontent.com/assets/1583842/23066227/23c88cd2-f522-11e6-90b0-16531d5233ac.png)
