### ISSUE TITLE
Log out tries to log you in again

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1632]
The log in/out button has its text update when the user authenticates however the action that is performed when it is clicked is always "start log in process".

If the user is already logged in the "Log out" button should "log out" the user.

Related to #1557.

**Comment by cosminbadescuSV** [comment]
The ” Log out” button works as expected, this issue is verified as fixed on AMO-dev on FF51.0 (Android 7.1.1).
Postfix video: 
![logout](https://cloud.githubusercontent.com/assets/15885467/22473455/abd158be-e7e1-11e6-8228-6a0ad682e4bb.gif)
