### ISSUE TITLE
Inconsistent case in https://addons-dev.allizom.org/en-US/developers/

### ISSUE THREAD

**Issue by wbamberg** [mozilla/addons-frontend#1635]
### Describe the problem and steps to reproduce it:
Visit https://addons-dev.allizom.org/en-US/developers/

### What happened?

The green button reads “Learn How to make an Add-on” - if we're using sentence case this should probably be "Make".

The second blue button reads "Sign in", but the third one reads "Sign In ... ". Should be consistent (probably "Sign In").

**Comment by muffinresearch** [comment]
@wbamberg thanks for the bug report. This particular project lives on addons-server so if you need to file any more bugs on the landing page you can file them here: https://github.com/mozilla/addons-server/issues/new

**Comment by atsay** [comment]
Under the header "Publish Your Add-on", the first sentence says, "Have you an add-on ready?" It should say, "Have an add-on ready?"

**Comment by atsay** [comment]
In the signed out state, please change the text in the "Evolution in Add-on Development" box to:

WebExtensions are now the standard for add-on development in Firefox. You'll need to update your legacy add-ons to stay compatible.
Button: Learn how (https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Porting_a_legacy_Firefox_add-on)

**Comment by tofumatt** [comment]
Because this affects code in addons-server, I've moved the issue (and relevant comments) there. Please leave further comments at: https://github.com/mozilla/addons-server/issues/4400 😄

**Comment by muffinresearch** [comment]
@tofumatt Thanks for moving the issue
