### ISSUE TITLE
Star rating on search page is always shown as 4/5

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1639]
The search page has a star count but it is always 4/5. There's now a `Rating` component that can be set to `readOnly` and it will render the stars for us instead of using the placeholder image.

<img src="https://cloud.githubusercontent.com/assets/211578/22094999/27978f46-ddd7-11e6-831b-81765a35a955.png" alt="screen shot 2017-01-18 at 23 37 20" style="max-width:100%;" width="300">

While we're at it the CSS could probably be updated to use `flex` instead of `float` for the icon. The icon should also be vertically centred. There are 4 headings in each component as well. I could see the add-on name being a heading (it's an `h2` right now) but the rating, author and number of users probably don't need to be in `h3` tags.

**Comment by kumar303** [comment]
I can take this

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on AMO-dev on Firefox 50.1.0 (Android 7.1.1) 
After performing a search the stars from search results are displayed correctly.
Here is a video:
![stars](https://cloud.githubusercontent.com/assets/15885467/22366579/1bef43f4-e486-11e6-8a1b-25f7cb103cc5.gif)
