### ISSUE TITLE
Remove requirement for spaces around `=` in default args

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#164]
Our eslint config requires spaces around the `=` in default args. We all think this looks weird so we should force no space and update all the existing code to match.

```js
// Currently required (bad)
const doSomething = (foo, bar = 99) => console.log(foo, bar);
// What we want (good)
const doItMoreBetter = (foo, bar=99) => console.log(foo, bar);

**Comment by mstriemer** [comment]
This actually isn't yet supported by eslint. See `https://github.com/eslint/eslint/issues/3380` and `https://github.com/eslint/eslint/issues/5553` (among others).

**Comment by mstriemer** [comment]
Removing milestone since this is dependent on eslint.

**Comment by muffinresearch** [comment]
I think we're ok with this now, so I'm going to close this.
