### ISSUE TITLE
Remove authentication reducer

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1644]
The `authentication` reducer has a lot of duplication with the `api` reducer. It seems to store the JWT and some info about the user but that user info doesn't seem to be exposed anywhere (on amo anyway). It does look like some code is checking if `auth.token` is set to detect if the user is logged in.

It is probably a good idea to remove the `authentication` reducer and add any user-specific data that we need to a `user` or `account` reducer.

There was a bug with logging out due to this that was fixed in #1643.

**Comment by kumar303** [comment]
oof, yeah, I'd love to clean up some other reducers too
