### ISSUE TITLE
Prepend protocol to links that are missing one

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#1647]
Looks like the links in "More information" are relative:

![screenshot 2017-01-23 13 53 50](https://cloud.githubusercontent.com/assets/74699/22224437/8016ce08-e173-11e6-8da0-a4bf80337584.png)

Example:

https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/

**Comment by tofumatt** [comment]
I believe that’s because the privacy policy page is on AMO and not
external, but we don’t implement that page on mobile yet. related to #1349;
we want this to fall back to the desktop view if not available (though
eventually we want to implement this page too).

Actually scratch all that; the URL is /privacy but I made it /privacy-policy

I’ll fix this!

**Comment by andymckay** [comment]
Thanks, please note its both links "www.Diigo.com" and "Read the privacy policy for this add-on". I believe both should be going through outgoing if they point to external sites.

**Comment by tofumatt** [comment]
Oh, that’s true, we should have an <ExternalLink> component for something
like that. Or our <Link> component could be smart enough to append out to
external links...

**Comment by tofumatt** [comment]
Some upon review looks like:

* we should prepend `http://` to any link that doesn't have `http://` or `https://` at the start of it
* we should add outgoing to any external link (we probably need to check the hostname for this)
* we should be using `<Link>` for all links, external and internal, so the above rules are respected

**Comment by tofumatt** [comment]
Note that the content of add-ons with links may or may not be converted, so this requires more research.

**Comment by muffinresearch** [comment]
Potentially blocked by https://github.com/mozilla/addons-frontend/issues/842 in that the correct links might cause infinite looks until #842 is fixed.

**Comment by tofumatt** [comment]
I looked this up further and frustratingly the URLs supplied by the API seem to be allowed to be ones without a protocol (maybe it's test data).

I'll make it so we prepend `http://` if there isn't a protocol.

**Comment by vcarciu** [comment]
This is how it looks now for https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/ : 
![website](https://cloud.githubusercontent.com/assets/1583842/23222499/c110e1d0-f930-11e6-888c-dc0fb29e9162.png)

**Comment by tofumatt** [comment]
This was fixed/superceded in #1877; now we show "Add-on Homepage" and "Add-on Support".

**Comment by vcarciu** [comment]
Verified as fixed : 
![otg](https://cloud.githubusercontent.com/assets/1583842/23657643/c1b8b4d4-0347-11e7-93de-fef8a852ae32.png)
