### ISSUE TITLE
After previewing a theme, it remains loaded after a refresh or when navigating to other pages

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#1657]
### Describe the problem and steps to reproduce it:
Preview any theme on Android.

### What happened?
The theme is loaded but after a refresh or if you navigate to other web pages it remains loaded in the web page.

### What did you expect to happen?
The theme should not be visible, after a refresh of the web page or when you navigate to other web pages.

### Anything else we should know?
Verified on FF50.1.0 (Android 7.1.1) on -dev server.
Here is a video:
![previewtheme](https://cloud.githubusercontent.com/assets/15885467/22370790/f15bf0cc-e49b-11e6-870e-8f1363af00a3.gif)

**Comment by tofumatt** [comment]
We chatted about this and I think we should change this from a "press and hold to preview" to a "tap to preview" then change to "stop preview" toggle button. We should disable the preview on navigation away from the page.

This means it should be less error-prone, more accessible, remove some weird scrolling handler code we have for this, and possibly fix other bugs.

**Comment by mstriemer** [comment]
I can't reproduce this. As soon as I remove my finger from the screen the preview ends.

**Comment by cosminbadescuSV** [comment]
I did not performed a “press and hold” for this issue, I only used one tap on the theme.
I hope this movie is better than the previous one.
![an](https://cloud.githubusercontent.com/assets/15885467/22777633/8471d366-eebc-11e6-809d-85be6dbc4eb2.gif)

**Comment by mstriemer** [comment]
I was able to reproduce this, although it takes quite a few tries on my phone. I wonder if the reset preview event is firing before the preview is actually setup. Performing the reset after a delay may fix this. Doing an extra reset on navigation is probably a good idea too.

I wouldn't be opposed to switching this to a toggle though. @pwalm do you mind if the theme is previewed with a tap and then reset with a tap? I feel we've discussed this before and preferred the hold to preview method but it's come up again so figured I'd ask.

**Comment by pwalm** [comment]
What about a... switch? 😉 

Tap could work, we would need to change the button label, though: "Tap to preview" and then "Tap to change back" (which is a mouthful). @devaneymoz, any suggestions?

**Comment by tofumatt** [comment]
"Tap to preview” then “Cancel Preview” seems fine to me, as the action to activate the button has already been established, so I don’t think you need “tap to” on the cancel action. Plus in that case we’d cancel on navigation anyway, so if the user got really freaked out and just went “back” we’d revert.

For a11y reasons we could still have “[tap to] cancel preview” but hide the “tap to” part of the text, too.

**Comment by pwalm** [comment]
Good point, @tofumatt. "Cancel preview" works for me. 👍

**Comment by devaneymoz** [comment]
"Cancel preview" rules.

**Comment by mstriemer** [comment]
I filed #1776 to update how previews work.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF51.0 (Android 7.1.1) on -dev server.
After a refresh of the web page or if you navigate to other web pages the theme is not visible anymore.
Please see the video:
![prev1](https://cloud.githubusercontent.com/assets/15885467/23464609/51169cbc-fe9e-11e6-91ea-b5dd249617c5.gif)
