### ISSUE TITLE
Dropdown menus are not pointing to correct buttons in Flagged and Updates Themes queues

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1659]
Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/editors/themes/queue/updates and observe the _Request More Info_ , _Updates_ or _Reject_ collapsing menus

Expected results:
Every collapsing menu should point to its parent button

Actual results:
Menus are not pointing to the correct button

Notes:
Not reproducible for _Pending_ queue (because there is a Flag button here , so the reason of the bug is that this button is not present on the other queues)

Video of the issue : 
![collapsingmenus](https://cloud.githubusercontent.com/assets/1583842/22339903/4ab0c5f6-e3f4-11e6-9da8-c717ed19ce7e.gif)

**Comment by tofumatt** [comment]
This is actually an addons-server issue. Add-ons frontend issues should only be filed, essentially, for pages that look like this:

![screen shot 2017-01-26 at 17 04 05](https://cloud.githubusercontent.com/assets/90871/22341631/74c98d06-e3e9-11e6-95b9-a50638fd1943.png)

eg the new mobile frontend.

**Comment by tofumatt** [comment]
Issue moved to https://github.com/mozilla/addons-server/issues/4493

**Comment by vcarciu** [comment]
@tofumatt : Oh yes, I am sorry I worked on many addons-frontend issues yesterday and I pressed New Issue button from one of these pages.
