### ISSUE TITLE
Registering is not supported

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1660]
The log in API endpoint won't create a new user. Once addons-server is updated to support this it should work on the mobile pages without any modifications. At some point we'll want to prompt the user to set their username.

The addons-server work is tracked in https://github.com/mozilla/addons-server/issues/3515.

**Comment by muffinresearch** [comment]
@mstriemer do you have any time to look at this. Since this is planned to go live next week it would be a shame to not have registration working.

**Comment by mstriemer** [comment]
We are no longer using that login endpoint so registration should now work. The config for -dev was wrong so I fixed that and now registering works (sort of).

On addons-server we redirect the user to the edit page so they can set their username after they've registered and for some reason this gives a plain grey page?

<img width="350" alt="screen shot 2017-02-22 at 10 10 50 am" src="https://cloud.githubusercontent.com/assets/211578/23220477/c51ce9c0-f8e7-11e6-8689-d1f636249fb0.png">

@muffinresearch I'm guessing we aren't worrying about the username right now since we don't have a user edit page? I can update addons-server to skip the redirect for addons-frontend and then it should work fine.

**Comment by muffinresearch** [comment]
@mstriemer that grey page should be 500 I'll file a bug for that separately.

**Comment by tofumatt** [comment]
I just tested this and now it works. Yay! 🎉

**Comment by ValentinaPC** [comment]
Registering is working on AMO-dev (Android 6.0.1).
User is redirected to homepage or the same page as before registering.
Postfix video: 
![data](https://cloud.githubusercontent.com/assets/15685960/23604893/39c7563c-0263-11e7-9732-53f3da22f2fd.gif)
