### ISSUE TITLE
Search sort has no margin-top

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1663]
### Describe the problem and steps to reproduce it:
I went to a page with the search sort. (Run any search)

### What happened?
There was no margin-top.

### What did you expect to happen?
It had margin-top. It used to! 

### Anything else we should know?

Screenshots attached.

#### Old screenshot:
<img width="317" alt="screenshot 2016-12-30 15 42 11" src="https://cloud.githubusercontent.com/assets/90871/21567761/92efb196-cea6-11e6-819a-49df10c5d91b.png">

#### New screenshot:
<img width="312" alt="screenshot 2017-01-27 01 57 13" src="https://cloud.githubusercontent.com/assets/90871/22358039/10920426-e434-11e6-8821-0056d5a22ad6.png">

**Comment by kumar303** [comment]
I can't think of anything obvious but it could have been something in here https://github.com/mozilla/addons-frontend/pull/1586/files

**Comment by aayushsanghavi** [comment]
Hey @kumar303 I found where it is going wrong. Have a look at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/SearchSort/SearchSort.scss#L16. The extra 0 in the beginning of the line is what is causing the problem. I am opening a PR that fixes it.

**Comment by madalincm** [comment]
Verified as fixed in FF51(Android 7.1.1) in addons-dev.allizom.org
Postfix screencast:
![screenshot_20170206-170056](https://cloud.githubusercontent.com/assets/15685441/22652134/ecacc28c-ec8d-11e6-9141-4f2c7dc01957.png)
