### ISSUE TITLE
After performing a review the time is not added correctly in the comment

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#1664]
### Describe the problem and steps to reproduce it:
Make a review for any add-on or theme.

### What happened?
The time from the comment is not displayed correctly.

### What did you expect to happen?
The time from the comment is displayed correctly after the review was made.

### Anything else we should know?
Verified on FF50.1.0 (Android 7.1.1) in AMO-dev server.
Here is a video:
![hour](https://cloud.githubusercontent.com/assets/15885467/22370130/80eb173a-e498-11e6-8118-4c8a0eb7fb52.gif)

**Comment by muffinresearch** [comment]
@cosminbadescuSV is this reproducible on production?

**Comment by cosminbadescuSV** [comment]
@muffinresearch yes, this issue is reproducible on production.
Please take a look at the video:
![test](https://cloud.githubusercontent.com/assets/15885467/24192829/f3606e16-0ef8-11e7-96a6-acc2553cd57c.gif)

**Comment by muffinresearch** [comment]
I think this is fixed:

<img width="774" alt="reviews_for_awesome_screenshot_plus_-_capture__annotate___more_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35516693-59a7d2b6-0504-11e8-94bd-72190006f8de.png">

**Comment by AlexandraMoga** [comment]
Confirmed as fixed

![image](https://user-images.githubusercontent.com/31961530/35553386-67e0aadc-05a0-11e8-8c8c-dadcf4e1327f.png)
