### ISSUE TITLE
Author’s name from detailed page of an add-on, returns “Internal Server Error” message

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#1665]
### Describe the problem and steps to reproduce it:
In the detailed page of an add-on or of a theme select the author name.

### What happened?
After selecting author’s name you are redirected to a web page that displays “Internal Server Error” message.

### What did you expect to happen?
The redirection is done to the author’s detailed page.

### Anything else we should know?
Verified on FF50.1.0 (Android 7.1.1) in AMO-dev server.
Here is a video: 
![internal](https://cloud.githubusercontent.com/assets/15885467/22377501/e3d834dc-e4ba-11e6-858b-a6b452dbb0a9.gif)

**Comment by muffinresearch** [comment]
This is due to there being no mobile view for this URL (it doesn't exist as a mobile page in the old mobile amo). This should be fixed once the server serves a Django fallback if the mobile site doesn't have a view. 

See https://github.com/mozilla/addons-frontend/issues/1349 for more details.
