### ISSUE TITLE
reduxAsyncConnect stops further navigation

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1673]
### Describe the problem and steps to reproduce it:
In working on the error pages (and have been struggling with them for awhile). I thought originally I just wasn't clearly the set error handlers but that's not the case. It seems that `reduxAsyncConnect`, after handling an error either with our `handleResourceError` HOC or by `catch()`ing the promises in `utils.js` or similar, stops all further rendering of the app. I've tried this with everything from a simple hard-coded string in `App.js` to render error components which will display but then stop all further updates of components.

What's especially strange is the actions are clearly still being sent and they are updating state, including state that I've added to `App.js` container in `amo/containers/App.js` (see screenshot) but the components do not re-render. It seems as soon as there's an error component or string rendered in `App.js` further rendering (but not navigation, action disptaching, or state/store changes) stops.

Either I'm missing something incredibly simple but not obvious, or something is wrong here.

![jan-29-2017 14-37-04](https://cloud.githubusercontent.com/assets/90871/22404867/a1bed04c-e631-11e6-8e0b-1046e171de2e.gif)

---

I should note this happens with both links on the page (when I had an error component that rendered links) and the back button. Sometimes the second link click would not be caught by the router and would force a page reload upon navigation. But I can't exactly tell what the steps to reproduce there are so not sure it's important.

---

### Basic steps to reproduce

1. Edit https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/SearchResult.js#L22 to change the URL to `/addon/${addon.slug}-not/`
2. Navigate to any search result page (eg http://localhost:3000/en-US/firefox/search/?q=test)
3. Click on a link
4. Get an error page
5. Navigate back

Note that nothing happens.

**Comment by tofumatt** [comment]
I added some steps to reproduce the issue above.

**Comment by tofumatt** [comment]
The issue isn't that the app stops rendering, but that it stops updating the page content after further navigation. You can see in the console log that actions are being dispatched, the state is being updated, but the components are not updating.

**Comment by tofumatt** [comment]
@kumar303 @mstriemer Maybe you could have a look at this? https://github.com/mozilla/addons-frontend/pull/1685?

It's, I think, a simple PR that catches the DetailPage Error and handles it, renders an error page rather than the usual content, and works. Except I can't render the NotFound component (or any other component) there, only a string. I'm baffled as to why that would be.

**Comment by ValentinaPC** [comment]
Please add some STR for us to verify this or the "no qa needed" label. Thanks!
