### ISSUE TITLE
Pressing on the label “Press to Preview” flashes the theme over another theme that is already installed

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#1677]
### Describe the problem and steps to reproduce it:
Install a theme, then press on the label “Press to Preview” from another theme.

### What happened?
After pressing on the label “Press to Preview”, the theme you want to preview flashes over the installed theme.

### What did you expect to happen?
Pressing on the label “Press to Preview” should not flash the theme you want to preview over the installed theme.

### Anything else we should know?
Press&hold will display the theme you want to preview, until you release it.
Verified on FF51.0 (Android 7.1.1) in AMO-dev server.

Here is a video: 
![flash](https://cloud.githubusercontent.com/assets/15885467/22421025/f02e6992-e6ed-11e6-9e3d-991d0b138002.gif)

**Comment by muffinresearch** [comment]
Needs investigating to find out why this is happening.

**Comment by mstriemer** [comment]
I'm not sure what's going on here. This looks like the intended behaviour. If you press and hold it shows you the theme you want to preview.

Is it that tapping the "button" does something weird?

**Comment by cosminbadescuSV** [comment]
One tap on the theme will cause the flash, I did not performed a “press and hold” for this issue.
It is hard for me to catch the flash in the video because tapping on the theme will be interpreted as  “press and hold” in the video which in this case isn’t.
Video for this issue:
![anos](https://cloud.githubusercontent.com/assets/15885467/22778302/281ae41a-eebf-11e6-9dbd-e5f8354f26ea.gif)

**Comment by muffinresearch** [comment]
We discussed this feature in a triage yesterday and thought that it might make sense to make this work on a click with requiring click to turn off the preview. 

Holding a press is a little bit counter-intuitive and probably "Press to preview" doesn't give enough of a hint to hold the press. A click might be simpler for users to understand.

We'd probably want to consider having the preview be dismissed if the user clicks something else / navigates away from the page too.

**Comment by muffinresearch** [comment]
Will be solved by #1776

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF51.0 (Android 7.1.1) on -dev server.
The theme you want to preview will not flash over the installed theme, it will disappear after you tap on the theme to cancel the preview.
Please see the video:
![videotogif_2017 03 01_17 16 07](https://cloud.githubusercontent.com/assets/15885467/23466744/a1f61b7a-fea4-11e6-9316-ec64e971e956.gif)
