### ISSUE TITLE
The message “No results were found for “<symbol>”. ” is not displayed for some symbols

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#1681]
### Describe the problem and steps to reproduce it:
Perform a search for the symbols “&”, “#” or “%”.

### What happened?
The message “No results were found for “<symbol>”. ” is not displayed.

### What did you expect to happen?
The message “No results were found for “<symbol>”. ” is displayed.

### Anything else we should know?
Verified on FF51.0 (Android 7.1.1) in AMO-dev server.
Here is a video:
![symbols](https://cloud.githubusercontent.com/assets/15885467/22430028/64f59f26-e715-11e6-8c72-e524d97c72a2.gif)

**Comment by kumar303** [comment]
We discussed this one. It's still a bug but we're removing the v1 label for now.

**Comment by aayushsanghavi** [comment]
@kumar303 I did a little look up. When we enter any of those special characters mentioned above, they are not considered as string queries, instead they are treated as undefined objects. What could cause that to happen?

**Comment by kumar303** [comment]
hmm, I'm not sure. I won't have time to investigate until we finish [v1](https://github.com/mozilla/addons-frontend/labels/mobile%20pages%20v1)

**Comment by muffinresearch** [comment]
This was already fixed.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF52.0 (Android 7.1.1) on -dev server.
The message “No results were found for (symbol). ” is displayed.
Please see the video:
![test2](https://cloud.githubusercontent.com/assets/15885467/24193272/6ba24790-0efa-11e7-82d7-bfe11880259d.gif)
