### ISSUE TITLE
All user-generated links should use outgoing

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1696]
As noted in https://github.com/mozilla/addons-frontend/issues/1647#issuecomment-274632001 there's currently some api responses with links that are not setup to be run through outgoing. This needs to be fixed prior to release.

Relates to https://github.com/mozilla/addons-server/issues/4270 which was the bug filed for fixing this in the API.

Since outgoing links are signed I'm feel like fixing it in the API is the way to go to keep the signing in one place. This is issue is just here to track that we fix it in some way or other ahead of putting this into production.

**Comment by tofumatt** [comment]
How will signed links work with things like https://github.com/mozilla/addons-frontend/pull/1685/files#diff-746716be1ee643b487345fd8abf59e5aR23 ?

Seems like we need to be able to generate outgoing links on the client side for pages where we have outgoing links, unless we aren't interested in tracking them, or want to hardcode in the particular outgoing URLs into our templates (which I guess would work if we put the link content in a variable and only set outgoing in PROD or something, but that seems weird).

**Comment by muffinresearch** [comment]
So I should clarify that as all user-generated links, links we add are ok. I've updated the title  - good catch!

**Comment by mstriemer** [comment]
I think technically that github link should be outgoing as well. Probably not as big of a deal since we clearly trust github to some extent by using it as a service but the same reasons for using outgoing would apply I believe.

If we've got some technical reason we can't do it it's probably not a huge deal, but if we're making outgoing links client side I think we may as well.

**Comment by muffinresearch** [comment]
That specific example is fine since a) we defined the link b) the translation is run through DOMPurify in addition. 

I think we're ok if we're supplying the links even if they're 3rd party domains. However if there's a case where we have UGC containing links then all of those must be run through outgoing. Since the source of all that data should be coming from the API I think we should be good to look to get this resolved by mozilla/addons-server#4270 unless there's some other source of 3rd party content I've missed in which case we should re-think this and start working on adding a way to generate outgoing links in the frontend code.

**Comment by muffinresearch** [comment]
This is covered by the API so marking this one as closed.
