### ISSUE TITLE
Document how CSRF is mitigated

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1697]
It would be good to summarise how the use of the APIs on AMO mitigates CSRF.

It's important to clarify the understanding of this so we can ensure we're not missing any CSRF protection before we put the mobile pages live.

**Comment by mstriemer** [comment]
For the most part CSRF is mitigated by not using the cookie for authentication. Authentication is done by passing a JWT in the `Authorization` header, which the browser will not do by default. 

The primary exception to this is some of the accounts APIs. The new session API for logging out will delete cookies but won't read them (and requires authentication) and the authenticate/login/register APIs will set cookies but verify the `state` parameter from the FxA OAuth flow against a cookie, acting as a CSRF token.

**Comment by kumar303** [comment]
hopefully we can do this in https://github.com/mozilla/addons-frontend/issues/2118
