### ISSUE TITLE
Syntax error should always cause the tests to fail

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1700]
### Describe the problem and steps to reproduce it:
* Start `npm run unittest:dev`
* Watch the tests pass
* Edit a file to cause a syntax error (I had typed something like `assert.('first value', 'second value')`)
* Wait for tests to re-run after the change

### What happened?

If you're paying attention, you'll see a message about the syntax error but the tests will pass

### What did you expect to happen?

The tests should fail

### Anything else we should know?

This was recently tweaked in https://github.com/mozilla/addons-frontend/issues/1103 -- the behavior of not killing the test suite is nice so it's almost there!

**Comment by kumar303** [comment]
This is fixed in Jest (https://github.com/mozilla/addons-frontend/issues/2372). It does exactly what I want now!

<img width="612" alt="screenshot 2017-06-02 11 13 35" src="https://cloud.githubusercontent.com/assets/55398/26734758/d31afc60-4784-11e7-87f9-c36122a6215d.png">

**Comment by muffinresearch** [comment]
![baby-groot-dancing](https://cloud.githubusercontent.com/assets/1514/26735566/5b0d7abe-47ba-11e7-9b80-3c29eb3d7cfd.gif)
