### ISSUE TITLE
[Dev Hub] Add ratings to listings in signed-in view

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#1717]
We should add ratings to the add-ons listed under "My Add-ons" when you are signed in. Perhaps above the "Last Updated" line.

**Comment by brampitoyo** [comment]
Thanks for assigning this to me. I’ll tackle this issue first thing next week!

**Comment by brampitoyo** [comment]
Showing the ratings stars above “Last Updated” is a good idea!

![ratings](https://cloud.githubusercontent.com/assets/51007/22871335/0d7282a6-f204-11e6-8cef-96c5f512c98f.png)

But along the way, I’ve found one layout problem which I’ve described on #1800. Fixing that issue first will allow us to display star ratings properly without causing any layout problem.

Thoughts?

**Comment by Ryuno-Ki** [comment]
#1800 is closed by now.

**Comment by tofumatt** [comment]
Moved to add-ons server.
