### ISSUE TITLE
A Log Out user is not requested to Sign In while rating an add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1719]
Prerequisites:
User is signed out.

Steps to reproduce:
1. Load AMO-dev on your Android device
2. Go to an add-on details page
3. Rate the add-on

Expected results:
User is redirected to sign in.

Actual results:
Nothing happens.

Notes/Issues:
Verified on AMO-dev FF51(Android 6.0.1).
Video for this issue: 
![videotogif_2017 02 07_08 21 09](https://cloud.githubusercontent.com/assets/15685960/22680114/14f83a2e-ed0f-11e6-8419-106adc9f7b27.gif)

#927

**Comment by kumar303** [comment]
Thanks for filing this. We're already tracking it in https://github.com/mozilla/addons-frontend/issues/1037

**Comment by ValentinaPC** [comment]
Verified this as fixed in #1037.
