### ISSUE TITLE
No pagination in All Written Reviews page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1720]
Steps to reproduce:
1. Load AMO-dev on your Android device
2. Go to details page for an add-on with reviews
3. Click to "Read all `x` reviews"

Expected results:
Review page is loaded. User can navigate through pages and see all reviews.

Actual results:
There isn't any navigation possibility.

Notes/Issues:
Verified on AMO-dev FF51(Android 6.0.1)
Video for this issue:
![videotogif_2017 02 07_08 32 17](https://cloud.githubusercontent.com/assets/15685960/22680409/729780d0-ed10-11e6-9874-fd376361ddd0.gif)

**Comment by kumar303** [comment]
Yes, I can confirm. There are TODO comments in the code to handle paging: https://github.com/mozilla/addons-frontend/blob/master/src/amo/api/index.js#L53

**Comment by muffinresearch** [comment]
I think we can probably make this one not a blocker.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 6.0.1) for themes and add-ons.
Postfix screenshot:
![2017-04-28_0956](https://cloud.githubusercontent.com/assets/15685960/25517623/ec45251e-2bf8-11e7-83ee-9e589ccb6556.png)
