### ISSUE TITLE
There are no Last page/First page navigation option in search results page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1721]
Steps to reproduce:
1. Search for an add-on in AMO-dev using your Android device
2. Go to last page of search results

Expected results:
User can go directly to the last page (or return to first page after navigation) of search results.

Actual results:
User can only navigate from page to page.

Notes/Issues:
The option does not exist in any AMO page on device.
Verified on AMO-dev FF51(Android 6.0.1)
Video for this issue: 
![videotogif_2017 02 07_08 42 57](https://cloud.githubusercontent.com/assets/15685960/22680699/09ffeb50-ed12-11e6-9dfa-dd05921cb82e.gif)

**Comment by tofumatt** [comment]
This is intended; the mocks only show previous/next navigation buttons.

The mocks are here https://github.com/mozilla/addons-frontend/blob/master/assets/sketch%20files/AMO%20-%20V1.sketch and can be compared against the site.

**Comment by ValentinaPC** [comment]
@tofumatt : Leaving the mocks for a second out of this discussion, what do you think? 
Let's say you access page 5, from page to page, going back to page 1 will be annoying, no? Or you wanna access last page...
You will say: "the URL can be change to access the desired page" - well...you cannot do this either, because of a 504 or a blank page.

**Comment by tofumatt** [comment]
I wouldn't argue changing the URL is good UX 😉  (though I think the 504 is an error I'm working on fixing).

Personally I don't find going to the last page of results (or back to the first) that useful. I like the reduced paginator clutter as well with just two very simple and obvious links. I think on mobile it makes a lot of sense especially. I'd argue keeping it as-is.
