### ISSUE TITLE
Themes with add-ons "facelift"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1722]
Steps to reproduce:
1. Load AMO-dev on your Android device
2. Click "Browse All Themes" link

Expected results:
Themes divided in 3 categories: featured, top rated and most popular are listed. Above each theme name a preview of it appears ([mocks](https://mozilla.invisionapp.com/share/GY8O3Z4ZE#/screens/190292731)).

Actual results:
Themes are listed like add-ons.

Notes/Issues:
- also, no "trending today" theme section, intended?
  
Verified on AMO-dev FF51(Android 6.0.1)
Screenshot for this issue: 
![t1](https://cloud.githubusercontent.com/assets/15685960/22681749/9a133b70-ed17-11e6-9529-9a61303fd4bd.png)

**Comment by muffinresearch** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/1746
