### ISSUE TITLE
No content in Themes categories

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1723]
Steps to reproduce:
1. Load AMO-dev on your Android device
2. Click on any theme category i.e Wild

Expected results:
Themes are displayed.

Actual results:
No themes displayed.

Notes/Issues:
- "Browse all themes" link is working as expected.
  
Verified on AMO-dev FF51(Android 6.0.1)
Screenshot for this issue: 
![wt](https://cloud.githubusercontent.com/assets/15685960/22684066/738bb7dc-ed23-11e6-9f1f-82525d730fe5.png)

**Comment by tofumatt** [comment]
The API is returning `400 Bad Request` for this combo of Android/Persona (Theme)/Wild. Possibly all themes. Will investigate; I hope these aren't all desktop-only categories 😒

**Comment by tofumatt** [comment]
Further investigation confirms that Android/Theme/Wild is not a valid combo. In fact: **none of our categories work for themes for mobile**. 😢 

So we will need all new illustrations for a set of mobile themes from this list: https://addons-server.readthedocs.io/en/latest/topics/api/categories.html#current-categories

OH NO. Actually there are no mobile theme categories. So we'll need to make some. For now it seems we should remove the themes categories from the home page.

I would say this is pretty important as it throws off the homepage a lot. We'll need to create the categories and then add the right themes to them 😒

**Comment by tofumatt** [comment]
Note: in this case we may need to request personas without asking for android ones, as any persona will work on Android.

**Comment by ValentinaPC** [comment]
Verified as fixed on FF51(Android 6.0.1)
Postfix video:
![videotogif_2017 03 03_09 17 53](https://cloud.githubusercontent.com/assets/15685960/23541841/8b072a9a-fff2-11e6-9fd9-72a3268c7960.gif)
