### ISSUE TITLE
404 page while clicking on "Add to firefox" button from add-on details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1724]
Steps to reproduce:
1. Load details page for an add-on on your Android device
2. Click "Add to Firefox" button

Expected results:
The add-on can be installed.

Actual results:
A 404 page is loaded inside of AMO-mobile page.

Notes/Issues:
Verified on AMO-dev FF51(Android 6.0.1)
Screenshot for this issue: 
![2017-02-07_1108](https://cloud.githubusercontent.com/assets/15685960/22685218/281fe782-ed28-11e6-841f-9a45b42e0f10.png)

**Comment by muffinresearch** [comment]
@ValentinaPC do you have a URL for this?

**Comment by ValentinaPC** [comment]
Well, I'll say "sure", but seems like today the page loaded after clicking on the "Add to Firefox" button is not the same like yesterday.

Today's page:
![2017-02-08_1908](https://cloud.githubusercontent.com/assets/15685960/22748278/3317bfb0-ee32-11e6-92dc-bed94e3b585c.png)

Today's link: https://addons-dev.allizom.org/android/downloads/file/205524/scroll_to_top_mobile-1.1-an%2Bfxandroid.xpi?src=

**Comment by muffinresearch** [comment]
This seems to be the same thing as this: https://github.com/mozilla/addons-frontend/issues/1867
