### ISSUE TITLE
Add-ons puzzle with no padding for other langs

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1725]
Steps to reproduce:
1. Load AMO-dev homepage on your Android device
2. Change the language to `it`
3. Observe page title

Expected results:
There are no layout issues.

Actual results:
There is no padding before the add-ons puzzle.

Notes/Issues:
- title is not entirely translated for other languages, but for long title will reproduce for other langs too.
Verified on AMO-dev FF51(Android 6.0.1)
Screenshot for this issue:
![it](https://cloud.githubusercontent.com/assets/15685960/22685917/d517d010-ed2a-11e6-99ee-738a50c846c0.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![aggiuntivi](https://cloud.githubusercontent.com/assets/1583842/23064277/d223d74c-f517-11e6-9fa4-f27f3f10ce34.png)
