### ISSUE TITLE
Add "Read less" link for add-ons with "Read more" link available in addon description

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1736]
Steps to reproduce : 
1.On Android, go to any addon with a long description (ie. Adblock Edge)
2.Press _Read more_ link at the end of visible description

Expected results:
We should have a _Read less_ button at the end of description

Actual results:
No _Read less_ button available

Please see video for this bug : 
![readless](https://cloud.githubusercontent.com/assets/1583842/22696559/1e33435c-ed57-11e6-8701-446b7facf661.gif)

**Comment by muffinresearch** [comment]
This was an explicit decision to make the interaction one-way. There's minimal value in closing this.
