### ISSUE TITLE
Your new review will replace latest review 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1738]
Steps to reproduce:
1.On Android, go to any add-ons with reviews
2.Write a new review

Expected results:
Number of reviews will increase and all reviews are visible

Actual results:
Number of reviews is the same and we can observe that your review replaced latest review for that add-on

Please see video for this issue : 
![reviewreplace](https://cloud.githubusercontent.com/assets/1583842/22700940/e20dfac6-ed64-11e6-9e89-d0be78d28332.gif)

**Comment by kumar303** [comment]
Hi @vcarciu ! Thanks, I can reproduce this on dev too. If I refresh the pages a couple times I can see both reviews so it's some kind of caching issue but it might be client-side caching, I'm not sure yet.

**Comment by vcarciu** [comment]
Verified as fixed : 
![lastrew](https://cloud.githubusercontent.com/assets/1583842/22823144/071d42a4-ef8b-11e6-9386-da7b252a6512.gif)
