### ISSUE TITLE
Review titles are awkward to write

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1739]
As of https://github.com/mozilla/addons-frontend/pull/1706 , writing a review for an add-on requires you to enter a title. The titles make the list of reviews look nice but it's not so nice as a user to think of a title. 

For me, I often get tripped up by this because my first inclination is to say something simple, e.g. "I like the way this add-on helps me do X." Thinking of a title slows me down.

Maybe the title could be auto-populated with the first sentence of the review if the user wants to leave it blank? Maybe we could make titles optional? Maybe we could put the title input underneath the body input? Just thinking out loud.

**Comment by pwalm** [comment]
Or... no title? I'm very happy to have no title. It removes one more barrier of "[blank slate syndrome](http://www.urbandictionary.com/define.php?term=Blank%20Page%20Syndrome)"

**Comment by tofumatt** [comment]
We'd probably need to update the server but I'd be happy with no title or an optional title at the very least. 👍

**Comment by muffinresearch** [comment]
We like the idea of removing the title. We can always add it back if there's more rationale to do so later.

**Comment by kumar303** [comment]
I'll file an issue to consider the review list layout now that none will have titles. It might need tweaking.

**Comment by vcarciu** [comment]
Verified as fixed : 
![notitlerew](https://cloud.githubusercontent.com/assets/1583842/22822951/442828ea-ef8a-11e6-8f63-df6b40b6ae24.png)
