### ISSUE TITLE
Too much space between header and category buttons

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1741]
Spacing between the header and the buttons on the Explore page should be tighter.

Currently:
<img width="337" alt="screen shot 2017-02-07 at 2 59 10 pm" src="https://cloud.githubusercontent.com/assets/6797635/22715490/01e76536-ed46-11e6-9d4a-2a2a66cdf895.png">

Mocks:
<img width="1327" alt="screen shot 2017-02-07 at 3 01 37 pm" src="https://cloud.githubusercontent.com/assets/6797635/22715574/5caa6e5a-ed46-11e6-9b76-3a0cc2e5bc6a.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![align](https://cloud.githubusercontent.com/assets/1583842/22968699/1ee3bb1a-f374-11e6-8bbf-48f2063b2de1.png)
