### ISSUE TITLE
Copy changes on Explore page

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1742]
- Change "What do you want Firefox to do?" to "You can change how Firefox works…"
- Change "How do you want Firefox to look?" to "…or what it looks like"

**Comment by vcarciu** [comment]
Verified as fixed : 
![worksorlooks](https://cloud.githubusercontent.com/assets/1583842/22977349/f4a48cd0-f396-11e6-857c-e205d7164dd2.png)
