### ISSUE TITLE
Layout of extension module is incorrect

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1743]
- Dev and user # is spread over two lines, it should be on one.
- Icon should be centered to block.

Currently:
<img width="335" alt="screen shot 2017-02-07 at 3 09 10 pm" src="https://cloud.githubusercontent.com/assets/6797635/22715785/7352104e-ed47-11e6-8f16-0c742f19b6a4.png">

Mock:
<img width="656" alt="screen shot 2017-02-07 at 3 07 40 pm" src="https://cloud.githubusercontent.com/assets/6797635/22715801/88ad6e0c-ed47-11e6-8e2d-b08a95d0daed.png">

**Comment by muffinresearch** [comment]
@pwalm the problem with using a dash is what should happen when it wraps?

**Comment by pwalm** [comment]
The problem is It shouldn't wrap., want to keep it all on one line.

**Comment by tofumatt** [comment]
Long/multiple usernames can cause it to wrap, unfortunately.

**Comment by muffinresearch** [comment]
Looks like desktop has tweaked this layout so this is no longer required.
