### ISSUE TITLE
Layout of Extensions home is incorrect

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1744]
- Search bar should say "Search Extensions" only
- Missing "welcome mat" describing what extensions are
- Missing "Browse by Category" button

Currently:
<img width="350" alt="screen shot 2017-02-07 at 3 13 44 pm" src="https://cloud.githubusercontent.com/assets/6797635/22715910/095795f0-ed48-11e6-85e0-504d099cec5a.png">

Mock:
<img width="443" alt="screen shot 2017-02-07 at 3 14 02 pm" src="https://cloud.githubusercontent.com/assets/6797635/22715919/14b26e48-ed48-11e6-8dc2-6e312fbd5656.png">

**Comment by mstriemer** [comment]
I thought we moved the searching for extensions/themes specifically to v2.

Looks like this still needs copy.

**Comment by tofumatt** [comment]
> I thought we moved the searching for extensions/themes specifically to v2.

We did, and we're missing copy for the extensions bit.

If we get the copy we can add that to the V1 but it's not something in the old app and the search is a v2 thing.

**Comment by aayushsanghavi** [comment]
@tofumatt I have taken up #1745, so I'll make the patch general to fix this issue too.

**Comment by mstriemer** [comment]
@aayushsanghavi here's the icon, I thought we had that one already but it looks like we just have a blue one.

[extensions.zip](https://github.com/mozilla/addons-frontend/files/821692/extensions.zip)

**Comment by mstriemer** [comment]
@devaneymoz we need some copy for this welcome mat as well. Looks like the mock has some ideas about what to say but it isn't complete.

**Comment by aayushsanghavi** [comment]
@mstriemer how about this - I submit my patch for now and open an issue for changing the text on the extensions page. That way, the issue won't have to be kept waiting.

**Comment by mstriemer** [comment]
We have this string on the discovery pane (roughly): "Install powerful tools that make browsing faster and safer, add-ons make your browser yours." Let's go with that and we can file to change it later.

**Comment by pwalm** [comment]
Love it! Ship it!

**Comment by aayushsanghavi** [comment]
@mstriemer I've opened a PR but there is some merge conflict issue.

**Comment by ValentinaPC** [comment]
> Search bar should say "Search Extensions" only

This is not changed, @tofumatt, is it ok?

Everything else seems ok.
Verified on FF52(Android 6.0.1) using AMO-dev.
Postfix screenshots:
![untitled](https://cloud.githubusercontent.com/assets/15685960/24290474/c85837e4-108d-11e7-8add-98daaa8da378.png)

**Comment by ValentinaPC** [comment]
I'll mark this verified fixed, because I saw you logged a separate issue.
