### ISSUE TITLE
Layout of Themes home is incorrect

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1745]
- Search bar should say "Search Themes" only
- Missing "welcome mat" describing what themes are
- Missing "Browse by Category" button

Currently:
<img width="346" alt="screen shot 2017-02-07 at 3 18 17 pm" src="https://cloud.githubusercontent.com/assets/6797635/22716033/ae0addb4-ed48-11e6-9740-fc7f1c5eb3dc.png">

Mocks:
<img width="434" alt="screen shot 2017-02-07 at 3 22 59 pm" src="https://cloud.githubusercontent.com/assets/6797635/22716142/5990270c-ed49-11e6-9205-fb8333352d6c.png">

**Comment by mstriemer** [comment]
I thought we moved the searching for extensions/themes specifically to v2.

Looks like this still needs copy.

**Comment by mstriemer** [comment]
@devaneymoz do you have copy for this?

Here's the icon: [themes.zip](https://github.com/mozilla/addons-frontend/files/804315/themes.zip).

I don't think we can update the search text yet since we only support searching for extensions and themes together right now.

**Comment by mstriemer** [comment]
If you have sketch the [AMO - V1.sketch](https://github.com/mozilla/addons-frontend/blob/master/assets/sketch%20files/AMO%20-%20V1.sketch) file has the mocks in it and you can export the icons from there. If you don't have sketch and need another icon in the future just ping one of the developers and we can extract it for you.

**Comment by aayushsanghavi** [comment]
@mstriemer thanks for the theme icon. Also, could you tell me what icon/glyphicon is to be used for the browse categories button.
And how do I change the placeholder according to the addonType? Any ideas on that?

**Comment by mstriemer** [comment]
Should have looked a little closer. I don't see that icon being used yet, so here it is [bullet-list.zip](https://github.com/mozilla/addons-frontend/files/804674/bullet-list.zip).

These icons should go in the [`Icon`](https://github.com/mozilla/addons-frontend/tree/1244c0dcaff3af740e43a55544a1f1064d730a52/src/ui/components/Icon) component so they're easier to re-use.

**Comment by aayushsanghavi** [comment]
@mstriemer thanks a lot! I'll get back to you in case I have a doubt.

**Comment by devaneymoz** [comment]
For copy under the header "Themes" how about we go with:

Change your browser’s appearance. Choose from thousands of themes to give Firefox the look you want.

**Comment by aayushsanghavi** [comment]
@mstriemer my patch is ready but for the extensions page I will need the extensions icon. Could you could share it? Also, @devaneymoz if you could suggest some text for the extensions page too.

**Comment by mstriemer** [comment]
@aayushsanghavi the icon is in now in https://github.com/mozilla/addons-frontend/issues/1744#issuecomment-284442050.

**Comment by aayushsanghavi** [comment]
@mstriemer thanks! Can you also suggest the text to be written beside the icon?

**Comment by ValentinaPC** [comment]
> Search bar should say "Search Themes" only

This should also be fixed here, @tofumatt ?

Taping on "Browse by category" does not load any category.
Please see screenshot:
![2017-03-24_1217](https://cloud.githubusercontent.com/assets/15685960/24289933/d0be4a6a-108b-11e7-8bda-2aba654fa021.png)


Reopening.

**Comment by tofumatt** [comment]
Ah, for "Search bar should say "Search Themes" only" we want to move that to the v2 label. Everything else should be fixed, so I'll make a new issue for that and the "Search Extensions" only text as well.

**Comment by tofumatt** [comment]
Shoot though, I think I know why theme categories aren't working. That is a separate issue, I'll file.

**Comment by ValentinaPC** [comment]
> Shoot though, I think I know why theme categories aren't working. That is a separate issue, I'll file.

Great.

I'll wait with the "verified fixed" label, until bug #2170 is fixed.
