### ISSUE TITLE
Layout of theme module is incorrect

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1746]
Theme module doesn't look anything like mocks:

Currently:
<img width="330" alt="screen shot 2017-02-07 at 3 24 56 pm" src="https://cloud.githubusercontent.com/assets/6797635/22716202/9ebdf584-ed49-11e6-9333-dca397b45814.png">

Mocks:
<img width="347" alt="screen shot 2017-02-07 at 3 25 25 pm" src="https://cloud.githubusercontent.com/assets/6797635/22716209/af61f5f2-ed49-11e6-9ffa-9d47aafb8b68.png">

**Comment by muffinresearch** [comment]
Related to https://github.com/mozilla/addons-frontend/issues/1837

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix screnshot:
![themes](https://cloud.githubusercontent.com/assets/15685960/23259595/90ab9b2e-f9d6-11e6-98f2-f7c9aad6aeb0.png)

**Comment by muffinresearch** [comment]
As noted in the PR, the ratings were left in (albeit floated) and the author users link matches the current one for extensions since there is an open question about wrapping for that.
