### ISSUE TITLE
Add titles for Categories detail pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1750]
Steps to reproduce:
1.On Android, go to AMO-dev and open any category present in home page

Expected results:
Based on mocks, we should have a title for every category : 
![categdetail](https://cloud.githubusercontent.com/assets/1583842/22741722/da658632-ee1c-11e6-94e7-713cfebf7ae1.png)

Actual results:
No titles for Categories

Please see screenshot for this issue(Games Category details page ) : 
![actualdetailspage](https://cloud.githubusercontent.com/assets/1583842/22741898/7fab99b0-ee1d-11e6-97c8-8de3e0095721.png)

**Comment by tofumatt** [comment]
This is true but outside the v1 scope, so marking as a v2 😄

**Comment by muffinresearch** [comment]
@devaneymoz do you have some thoughts on what copy we should use here?

**Comment by devaneymoz** [comment]
Unless I'm missing something, why not just display the title of the category (perhaps its icon as well)? 

Category titles should set clear enough context. I don't think we need to swap that lorem ipsum in the mock-up for added context, especially given the tightness of real estate on mobile.

**Comment by willdurand** [comment]
I think this can be closed now.

**Comment by vcarciu** [comment]
@willdurand : thanks, I will mark it as verified since categories have titles now
