### ISSUE TITLE
Log Out button should have user's name on it 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1751]
Steps to reproduce:
1.On Android, go to addons-dev.allizom.org and log in with valid credentials

Expected results:
According to mocks, the log-out button should contain user's display name : 
![usernamemocks](https://cloud.githubusercontent.com/assets/1583842/22748839/15f32710-ee34-11e6-8f42-38953c6dd38d.png)

Actual results:
Button's text is "Log out"

Please see screenshot for this issue : 
![usernameactual](https://cloud.githubusercontent.com/assets/1583842/22748875/31e1b6e4-ee34-11e6-83a5-0005cd27e2dc.png)

**Comment by tofumatt** [comment]
I think we could move this out of V1 to V2. Log out seems to do enough for now, and there is minimal space for long usernames here.

**Comment by mstriemer** [comment]
It would be nice to know who you're logged in as so I wouldn't be opposed to this. It does seem strange to click your username and get logged out so we'd need to add a dropdown menu to this, potentially. Perhaps we could cheat and do tap your name, text changes to log out, tap again you get logged out.

**Comment by vcarciu** [comment]
Maybe we can split the button in 2 sections , one with log out and one with the name which will redirect to user's info(I can see that this is requested in mocks too)

**Comment by tofumatt** [comment]
> It would be nice to know who you're logged in as so I wouldn't be opposed to this. It does seem strange to click your username and get logged out so we'd need to add a dropdown menu to this, potentially. Perhaps we could cheat and do tap your name, text changes to log out, tap again you get logged out.

Yeah I like that. I guess I was thinking more for v1. But yeah, eventually showing your username would be nice.

**Comment by mstriemer** [comment]
@pwalm what would you like us to do here? Is just **Log out** okay for now or would you rather see the name as well?

**Comment by pwalm** [comment]
We had is mocked up so that it shows the user name, the user would tap it to go to their profile/settings page, and log out would be at the bottom of that. Can we do that?

**Comment by aayushsanghavi** [comment]
I would like to take this up. @tofumatt what variable/object has the username that we would have to display - https://github.com/mozilla/addons-frontend/blob/master/src/core/components/AuthenticateButton/index.js#L36 ?

**Comment by tofumatt** [comment]
@aayushsanghavi That variable would be in the redux state somewhere, I'm not sure where. If you don't have a good understanding of Redux yet this might be a pain bug to take on.

I'm guessing it's in `state.auth`, which you'd need to map in the `mapStateToProps` function inside the file you referenced, then get it as a prop in `render()`. Not sure if that makes sense, let me know if not.

**Comment by mstriemer** [comment]
The username is not currently put into the state. It can be put into the `auth` reducer though with [`setCurrentUser`](https://github.com/mozilla/addons-frontend/blob/8356cf0c6fee77c5edf1257829ed850ad4cca2d0/src/core/actions/index.js#L45). Issue #1644 was filed to remove the `auth` reducer however as it is mostly redundant with the `api` reducer right now.

The username is stored in the JWT so it would need to be parsed from that. I think before we do this we'd want to write the `account` or `user` reducer and get it accepting the payload from the JWT (which has the username, user ID and email). I filed #1820 to track this work.

**Comment by aayushsanghavi** [comment]
@tofumatt, @mstriemer thanks, for your inputs. I'll wait till #1820 gets fixed, meanwhile I'll try my hands on Redux.

**Comment by willdurand** [comment]
I'll work on that once the new header gets merged. I think #2745 should be done at the same time too given the previous discussions here.
