### ISSUE TITLE
Sort control should be platform-standard dropdown

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1752]
I know I had designed a funky custom control for the Sort option, but we (the collective and royal we) had talked awhile back about making it just a generic OS dropdown. Can we do that please?

**Comment by tofumatt** [comment]
We (developers and non-royal 😉) chatted about this and feel there are actually some usability and accessibility wins to the current component (plus we kinda like it).

Marking this as "needs discussion".

**Comment by pwalm** [comment]
Alright, fine with it sticking around, the touch targets need to be bigger by about 2x.

**Comment by pwalm** [comment]
Touch target still needs to be bigger, please. 😄

**Comment by tofumatt** [comment]
Indeed, I still haven't got to it but noted!

**Comment by tofumatt** [comment]
This is actually fixed, like ages ago.
