### ISSUE TITLE
Make a scanner/test for locale files

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1753]
After encountering #1513, we should check all the locale files for things like HTML entities, substitutions match, etc. (I hear something named "Denis" exists).

**Comment by muffinresearch** [comment]
The dennis linter is this project: https://github.com/willkg/dennis/ there's also https://github.com/mozilla/grunt-l10n-lint which could be good if it had the lib bits and tests extracted out to be more standalone and not depend on grunt.

**Comment by muffinresearch** [comment]
Closing in favour of it being done as part of https://github.com/mozilla/addons-frontend/issues/529
