### ISSUE TITLE
Upgrade to webpack 2

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1761]
I was gonna just do this in the Greenkeeper PR but it's a fair bit of changing so closing the Greenkeeper PRs for now and leaving this as a code quality issue.

https://webpack.js.org/guides/migrating/

**Comment by muffinresearch** [comment]
Nominating this for consideration for q2 - this would probably be tied quite closely to any potential changes wrt webpack-isomorphic-tools.

**Comment by muffinresearch** [comment]
Also assumes https://github.com/mozilla/addons-frontend/issues/353 which was closed since upgrading to webpack2 assumes a clean-up of the webpack config at the same time.
