### ISSUE TITLE
SearchForm.loadAddon() can maybe get deleted

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1767]
I can't see where [loadAddon()](https://github.com/mozilla/addons-frontend/blob/613538dd9e5a8b96dcf8c68dd976a497175e4faa/src/amo/components/SearchForm.js#L67-L73) is used (except one unit test) so I think it can be deleted. It will need a little more probing but we should get rid of it if we don't need it.

**Comment by kumar303** [comment]
I think it was copied from `admin/components/SearchForm.js`

**Comment by muffinresearch** [comment]
Closed by https://github.com/mozilla/addons-frontend/pull/2668

**Comment by AlexandraMoga** [comment]
Please add some STR or the label 'qa:not needed'
