### ISSUE TITLE
With keyboard open, the scroll should work inside "Write a review" form 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1773]
Steps to reproduce:
1.On Android, AMO-dev, try to rate an addon 

Expected results:
With keyboard open, the scroll should work inside the  _Write a review_ form

Actual results:
Scroll is active behind _Write a review_ form and review cannot be submitted because submit button is under opened keyboard

Please see video for this bug : 
![scrollreview](https://cloud.githubusercontent.com/assets/1583842/22793875/d01a040e-eef9-11e6-80c1-2ed533c43ddd.gif)

**Comment by kumar303** [comment]
The original patch was for https://github.com/mozilla/addons-frontend/issues/1526

**Comment by vcarciu** [comment]
Please note that this is worse when in Landscape mode, because you cant submit even if the keyboard is closed.

**Comment by vcarciu** [comment]
Verified as fixed : 
![scroollinside](https://cloud.githubusercontent.com/assets/1583842/22886657/78ee9b7a-f207-11e6-9985-b4750441a3a7.gif)
