### ISSUE TITLE
Preview themes using a toggle

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1776]
Currently previewing themes is achieved by pressing and holding on the theme image. This isn't super intuitive and currently has a bug if you tap really quickly.

This interaction should be changed to **Tap to preview** and then switch to **Cancel preview** once the theme is being previewed.

This should resolve #1657 and #1677.

**Comment by mstriemer** [comment]
Once this is done we should be able to remove the code that switches the theme image from an image to a background image in `componentDidMount`. I filed #1777 to remove this.

**Comment by cosminbadescuSV** [comment]
Marking as verified fixed since  #1657 and #1677 were fixed.
