### ISSUE TITLE
Remove background for theme image

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1777]
Theme images are provided as an `<img>` on the server but that is switched out for a CSS background image once the page loads to avoid prevent the long-press interaction for an image which was preventing scrolling.

Once #1776 lands we should be able to remove this code.

**Comment by cosminbadescuSV** [comment]
Do you have any STR for this issue or is it enough that #1776 is already marked as verified-fixed?

**Comment by muffinresearch** [comment]
@cosminbadescuSV yeah I think you can skip this one.
