### ISSUE TITLE
Updating review text shows the old text when you press submit

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1779]
### Describe the problem and steps to reproduce it:

* rate an add-on on the detail page
* write a review
* save the review
* select a new star rating to change it
* enter in new review text
* press save again

### What happened?

For a split second, while the review is saving, the form contains the old text.

### What did you expect to happen?

It should only show the new text you just entered otherwise the user might think the site has a glitch.

**Comment by vcarciu** [comment]
Verified as fixed :  
![replacementtext](https://cloud.githubusercontent.com/assets/1583842/22888483/8dfa7b86-f20e-11e6-8e32-770b6542b8a4.gif)
