### ISSUE TITLE
'No reviews yet' is not styled correctly on add-on detail page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1782]
### Describe the problem and steps to reproduce it:

* Go to an add-on detail page for an add-on that has 0 reviews

### What happened?

The 'No reviews yet' text isn't styled correctly

<img width="387" alt="screenshot 2017-02-09 18 10 55" src="https://cloud.githubusercontent.com/assets/55398/22808774/53636186-eef3-11e6-803e-53a19bfe23a5.png">

### What did you expect to happen?

It should match the mock

**Comment by vcarciu** [comment]
Verified as fixed : 
![norewstyle](https://cloud.githubusercontent.com/assets/1583842/22970634/73f1670e-f37b-11e6-953b-074e75053a70.png)
