### ISSUE TITLE
Wrong message when trying to submit a second empty review

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1783]
Steps to reproduce:
1.On Android, go to any add-on details page (https://addons-dev.allizom.org/en-US/android/addon/send-to-mail/)
2.Submit a review by pressing on rating stars
3.Try to submit again a review , but this time leave the text field empty and press Submit

Expected results:
A correct warning is displayed without UI issues

Actual results : 
The  "body : This field may not be blank." message is displayed, a white dot is present in the left side ,look of warning it is not stylized and the text field is automatically filled with the previous text

NOTES:
If you try to submit an empty review from first time, the review entry will be closed without any warning. Should I look a separate issue for this?

Please see a screenshot for this bug : 

![bodymobile](https://cloud.githubusercontent.com/assets/1583842/22820804/080c381e-ef81-11e6-8a88-9b614ede5bb6.png)

**Comment by kumar303** [comment]
The dot and other style issues will be fixed in https://github.com/mozilla/addons-frontend/issues/1771

> Expected results: ... A correct warning is displayed

What did you mean by this? Can you provide an example?

> If you try to submit an empty review from first time, the review entry will be closed without any warning. Should I look a separate issue for this?

Yes, please. I'd like to see the STR for this.

**Comment by muffinresearch** [comment]
@vcarciu there's a couple of questions for you in the previous comment ^

**Comment by vcarciu** [comment]
So , if you already have a review for an add-on and you press again the rating stars, you are able to edit your previous review. At this point, just delete any text from review form and press _Submit review_ again and you will see the error message.

Related to "Expected results: ... A correct warning is displayed" I meant that the message is incorrect because of the "body:" part as you can see in the screenshot.

Related to "If you try to submit an empty review from first time, the review entry will be closed without any warning. Should I look a separate issue for this?"  - This was already logged , but I forgot to add this info here : https://github.com/mozilla/addons-frontend/issues/1837

I am sorry if the description was not clear enough from the first time so I added a video now : 
![body](https://cloud.githubusercontent.com/assets/1583842/23660455/29c76f3e-0352-11e7-8157-4618923c9398.gif)

**Comment by kumar303** [comment]
Ah, thanks for the additional details. This is pretty much the same as https://github.com/mozilla/addons-frontend/issues/1837 except that you're seeing an error while editing. I am going to close this one though because https://github.com/mozilla/addons-frontend/issues/1837 will fix it. I'll add a note to make sure we cover the editing case.
