### ISSUE TITLE
Issue in seeing "Press to Preview" section for themes designed in bright colors

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1784]
Steps to reproduce:
1. Load details page for a theme with a light colored design i.e. https://addons-dev.allizom.org/en-US/android/addon/almost-white/?src=ss
2. Observe "Press to Preview" section

Expected results:
The "Press to Preview" section can be observed without any issues.

Actual results:
User has trouble in seeing the "Press to Preview" section.

Notes/Issues:
There are a bunch of themes designed in bright colors.
Verified on FF51(Android 6.0.1).
Screenshots for this issue: 
![themes](https://cloud.githubusercontent.com/assets/15685960/22830500/67e0d104-efaf-11e6-874c-5aeb4b083fd8.png)

**Comment by pwalm** [comment]
This is no good. Should I design a reversed, dark version of this button?

**Comment by tofumatt** [comment]
That would be good. The easiest option for V1 is to have a dark background with light text always so it's easier to see regardless.

I'm sure for V2 we could see about using a light/dark colour depending on the theme's preview image with some canvas magic, but that's too fancy for next week's tag 😄

**Comment by pwalm** [comment]
Let's make the background colour of the button #000000 @ 50% opacity, but keep the text and icon #ffffff. Looks good on dark and light themes:
<img width="1094" alt="screen shot 2017-02-23 at 9 48 02 am" src="https://cloud.githubusercontent.com/assets/6797635/23271700/5caab356-f9ad-11e6-86db-15e100a70b92.png">

**Comment by muffinresearch** [comment]
This was resolved by the change to button that toggled the theme.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7)
Postfix screenshots:
![taps](https://cloud.githubusercontent.com/assets/15685960/25943394/63c3c93e-3648-11e7-915d-fd248b6f8498.png)
