### ISSUE TITLE
No design displayed for some themes on mobile

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1785]
Steps to reproduce:
1. Load AMO-dev on your Android device and search something i.e. "wild" (https://addons-dev.allizom.org/en-US/android/search/?q=wild)
2. Scroll through results and observe all themes

Expected results:
Every theme has a design. 

Actual results:
Some themes don't have a design.

Notes/Issues:
- **on desktop those exact themes have a design**
Examples: 
   1. https://addons-dev.allizom.org/en-US/android/addon/wild-horses-by-redbud/?src=ss
   2. https://addons-dev.allizom.org/en-US/android/addon/c-e-wild-horses/?src=ss
   3. https://addons-dev.allizom.org/en-US/android/addon/joker-is-wild/?src=ss
   4. https://addons-dev.allizom.org/en-US/android/addon/catching-fire-peeta-katniss/?src=ss
etc.

Verified on FF51(Android 6.0.1).
Screenshots for this issue:
![nodesign](https://cloud.githubusercontent.com/assets/15685960/22831725/11744e68-efb4-11e6-9baa-2fabc781607d.png)

**Comment by muffinresearch** [comment]
This might be resolved by https://github.com/mozilla/addons-frontend/issues/1746

**Comment by ValentinaPC** [comment]
Unfortunately this was not fixed by #1746.
There are still some themes that have no design preview after search.
I.e: 
![1](https://cloud.githubusercontent.com/assets/15685960/23260335/fe4c07a6-f9d9-11e6-9d87-a4d7fd7909f7.png)

Notes:
- refreshing the page in theme details will make the design visible
- theme design will remain "invisible" in search results page or the second time we access theme details page.

See video:
![videotogif_2017 02 23_15 13 17](https://cloud.githubusercontent.com/assets/15685960/23260551/0a4e70a6-f9db-11e6-879a-b0344d0c2068.gif)

**Comment by muffinresearch** [comment]
This is due to the image files being 404. I think this might be a data problem or data import related.

**Comment by muffinresearch** [comment]
I'll investigate this one to see what's going on.

**Comment by muffinresearch** [comment]
Having added a test theme the images appeared to be generated correctly. I think this is purely a data issue but we should re-open this if we see it on stage.

**Comment by ValentinaPC** [comment]
This seems to be fixed in #1964 .
Verified as fixed in AMO-dev FF51(Android 6.0.1).
Postfix video: 
![videotogif_2017 03 06_14 35 32](https://cloud.githubusercontent.com/assets/15685960/23610237/8833f9b2-027a-11e7-9214-81ebbdfb8301.gif)
