### ISSUE TITLE
404 error page in desktop-site view while logging in from mobile-site view

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1786]
Prerequisites:
User is log out.

Steps to reproduce:
1. Load AMO-dev homepage o mobile
2. Make a search i.e **https://addons-dev.allizom.org/en-US/android/search/?q=fire**
3. Click "Log in/Sign up" button to log in
4. Enter valid credentials and sign in

Expected results:
User is redirected in search results page from where he logged in.

Actual results:
A 404 page is displayed, but the URL is the same as in step 2.

Notes/Issues:
- after refresh the correct page is reloaded.
Verified on AMO-dev FF51(Android 6.0.1)
Screenshot for this issue:
![2017-02-10_1759](https://cloud.githubusercontent.com/assets/15685960/22833461/b873d3fe-efba-11e6-8adb-accbca47de9a.png)

**Comment by ValentinaPC** [comment]
These results changed:
**Longing in from any page using mobile-site view will NOW redirect the user to a desktop-site 404 page.**

Verified this on AMO-dev FF51 and Android 6.0.1 and the results were the same.
Please see the video:
![404](https://cloud.githubusercontent.com/assets/15685960/23121068/ab51d068-f767-11e6-9469-82e1014449cb.gif)

Link loaded: https://addons-dev.allizom.org/en-US/firefox/fxa-authenticate/?state=972187b3c8479c58d6825bf4ce3798cd27a42835f3e3c8cadbde5ed70e84dfbe%3AL2VuLVVTL2ZpcmVmb3gv&code=219c24b5c7c5bb9758f4ba5559899fa86ee5c247d8f98356b98978bfedbd78b8&action=signin

**Comment by muffinresearch** [comment]
@ValentinaPC this is caused by the way 404 urls fall-back to using addons-server. Of course the root cause needs to be fixed.

**Comment by muffinresearch** [comment]
@ValentinaPC I can't reproduce this. Logging in take me to the same page I was on. Can you re-test and see if it's the same for you?

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev (Android 6.0.1)
Log in works as expected; I've checked from search results page, homepage, add-on details page or using other languages.
Postfix video: 
![videotogif_2017 02 23_14 22 09](https://cloud.githubusercontent.com/assets/15685960/23259173/775e17ac-f9d4-11e6-8067-226142584ab6.gif)
