### ISSUE TITLE
Bad  behavior for Back action after logging in

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1788]
Steps to reproduce:
1.On Android, go to AMO-dev and login with valid credentials
2.Press back button

Expected results:
User is sent to FXA login page and login can be successfully performed

Actual results:
A big Login Required message together with an additional text saying that there was an error during logging are displayed even if the user looks to be still logged in . There is also a blue Login link under message and if you press it the fxa page will be displayed but if you try to log in from here the "Ivalid OAuth parameter:state " error is displayed

Please see video for this issue : 
![loginback](https://cloud.githubusercontent.com/assets/1583842/22835317/f2aa3e18-efc0-11e6-9068-6732caa9b0ba.gif)

**Comment by muffinresearch** [comment]
@mstriemer any ideas what we could do to work around this?

**Comment by kumar303** [comment]
Hmm. The video looks similar to what I remember from https://github.com/mozilla/addons-frontend/issues/1528 (which I can't reproduce anymore)

**Comment by muffinresearch** [comment]
Trying this, I get back to the login page and when I login it works fine.

**Comment by vcarciu** [comment]
Not sure what fixed this, but this is not reproducible anymore. Thanks

**Comment by mstriemer** [comment]
This would have been fixed when I updated the fxa config a few days ago.
