### ISSUE TITLE
Check for race condition in search loading reducer

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#180]
There might be a race condition in the search results reducer where the latest results returned always win regardless of it being the current search term.

``` js
startSearch({query: 'foo', page: 1});
startSearch({query: 'bar', page: 1});
searchLoaded({query: 'bar', page: 1, results: [...]});
searchLoaded({query: 'foo', page: 1, results: [...]});

// store.getState().search.query should still be `bar` here.
```

**Comment by muffinresearch** [comment]
So I suppose for this case we should not allow a new search if the previous one is still in-flight OR we need to abort the in-flight request when starting a new one.

**Comment by mstriemer** [comment]
I don't think there is a way to cancel an in-flight `fetch` call unfortunately. I think we'd want to check in the reducer if the results that were loaded matched the current query.

```js
export default function search(state = initialState, action) {
  const { payload } = action;
  switch (action.type) {
    // snip...
    case 'SEARCH_LOADED':
      // Add this check
      if (payload.query === state.query && payload.page === state.page) {
        // Return updated state, as before.
        return {
          ...state,
          count: payload.result.count,
          loading: false,
          query: payload.query,
          results: payload.result.results.map((slug) => payload.entities.addons[slug]),
        };
      }
      // Skip updating the state, these results are stale.
      return state;
    // snip...
  }
  return state;
}

**Comment by muffinresearch** [comment]
Yep the latter sounds good given the lack of a built-in abort to fetch. This lib has a similar albeit more generalized approach: https://github.com/idolize/redux-requests

**Comment by kumar303** [comment]
Since this is an edge case we're going to just wait until it becomes a problem and then solve it as needed
