### ISSUE TITLE
[Dev Hub] When the add-on name is too long, it breaks the layout

### ISSUE THREAD

**Issue by brampitoyo** [mozilla/addons-frontend#1800]
/CC @atsay 

It was described to us [on this tweet by @s_hentzschel](https://twitter.com/s_hentzschel/status/825280472435589120):

![s_hentzschel_2017-jan-28](https://cloud.githubusercontent.com/assets/51007/22871389/902e95c2-f204-11e6-894d-e84030a8b485.jpg)

The solution is as follows:

* The add-on name should be given its own line, so when it becomes too long, it just continues down the next line uninterrupted
* The “Edit Listing” link should also have its own line, directly below the add-on name (no longer appearing inline and to the side of the add-on name)
* The “Last Updated” field is always aligned right and to the bottom, so it lines up with add-on version and status.
* The rating stars appears above “Last Updated”, lining up with “Edit Listing”

I’ve visualised what the new layout can look like on #1717.

**Comment by atsay** [comment]
Yes, it makes sense to fix this first, then #1717. Thanks Bram!

**Comment by EnTeQuAk** [comment]
I'll take a look at this and will implement the new layout according to https://github.com/mozilla/addons-frontend/issues/1717#issuecomment-279295146 except for the rating-stars which will be added with #1717 in a separate pull request.

**Comment by vcarciu** [comment]
Verified as fixed : 
![germana](https://cloud.githubusercontent.com/assets/1583842/22939278/d7af1088-f2e6-11e6-85e7-5a1a2f8dafd5.png)

**Comment by brampitoyo** [comment]
Corner case: what happens if – for one reason or another – the add-on name is longer than one line?

Tell me if I’m overthinking this corner case. I’m sure 99% of add-ons out there don’t have that long of a name!

**Comment by EnTeQuAk** [comment]
The screenshots have the max length for the add-ons name (30 characters), if I add some more this is how it looks:

![screenshot from 2017-02-15 10-35-51](https://cloud.githubusercontent.com/assets/139033/22968503/f2d9e200-f36a-11e6-9528-669e3ec31014.png)

But then again, this is technically not possible. Fixing it to look like…

![screenshot from 2017-02-15 10-39-26](https://cloud.githubusercontent.com/assets/139033/22968530/0abe043c-f36b-11e6-8aa8-751c2bd47132.png)

is relatively simple, I'll put it on the list for times when I need something easy but as this is a unrealistic use-case I wouldn't worry about it.

**Comment by brampitoyo** [comment]
Thanks. I didn’t know that add-ons name has a character limit. This isn’t a critical issue to fix, then.
