### ISSUE TITLE
Integrate development workflow into addons-server docker

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1813]
We now depend on a local addons-server to be running with our default development configuration.

It would be much nicer if we could have addons-server (or some other blanket add-ons docker setup) support addons-frontend so that we can have a workflow that is much closer to production and one place to go to work on add-ons code.

**Comment by kumar303** [comment]
If this is an easy stepping stone towards production then let's do it but ultimately I'd like to see https://github.com/mozilla/addons-frontend/issues/1814

**Comment by muffinresearch** [comment]
Closing in favour of #1814
