### ISSUE TITLE
The holy grail: develop locally with the production Docker config

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1814]
We can do it! AMO is deployed to production with [Docker](https://github.com/mozilla-services/puppet-config/tree/master/amo/modules) and we develop locally with a completely separate and unrelated [Docker configuration](http://addons-server.readthedocs.io/en/latest/topics/install/docker.html).

Let's adjust the production Docker config for local development.

If you're not going to dream big, why dream at all?!

**Comment by kumar303** [comment]
FYI, the Docker configuration in `addons-frontend` is already the one used in production. However, we don't develop `addons-frontend` with Docker currently.

**Comment by willdurand** [comment]
Given that most developers use MacOS and that the only requirement for this project is Node, I don't think we should spend time setting up a Docker dev environment. We use the API to develop, for each we provide nice npm commands. In addition, developing in offline mode is feasible by installing addons-server locally too.
