### ISSUE TITLE
Log all the things

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#182]
We'll want some logging in production. Currently we're logging with redux-logger which is pretty noisy so that should be disabled in production.

We'll want to log URLs at a minimum, most likely some other stuff too.

**Comment by muffinresearch** [comment]
This will be a good time to DRY up the createStore function between the apps.

**Comment by andymckay-limited-access** [comment]
On logging, I'd like it if we logged every server request (especially for
the internal search). If we can log in a structured format e.g.: json it
would be really easy to pull into kibana. Something that has always annoyed
me in addons-server.

**Comment by muffinresearch** [comment]
Buyan will be a good fit for that it defaults to JSON but comes with a binary for formatting for humans.

**Comment by andymckay** [comment]
And the authors wife is on my curling team.

**Comment by muffinresearch** [comment]
Would be nice to turn off all the logging in tests unless explicitly enabled too.
