### ISSUE TITLE
Privacy policy URL is wrong

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1826]
Separating out from #1647; we need to link to `/privacy/` not `/privacy-policy/`. Blocked by #1798.

(Because we don't currently show the privacy policy, this should also be a `<a>` tag as it's not currently navigating inside our router.)

**Comment by vcarciu** [comment]
@tofumatt : The link is now https://www.mozilla.org/en-US/privacy/websites/ . Is this correct?

**Comment by tofumatt** [comment]
@vcarciu Sorry, you're looking at the wrong privacy policy because I didn't do a good job with this bug.

The issue was that https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/ linked to https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/privacy-policy/ but should link to https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/privacy/

Aaaand I just realised the link is still wrong, so reopening this to fix it again.

**Comment by vcarciu** [comment]
@tofumatt 
The link is now correct , https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/privacy/ and it will open the desktop view, but I assume that this is correct if we don't have mobile page for that. Please confirm.

**Comment by tofumatt** [comment]
That’s correct; we’ll add the mobile page in v2.

**Comment by vcarciu** [comment]
Verified as fixed then
