### ISSUE TITLE
Sort icon is a bit odd because it's centred

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1835]
I think the sort icon we use is feeling a bit odd to me because it's centred instead of left-aligned like most sort icons I see (eg https://thenounproject.com/search/?q=sort).

Any chance we could rework the sort icon to be left-aligned? (Also most seem to be an odd number of columns instead of even, not sure if that's why it feels a bit harder to grok)

<img alt="cursor_and_add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/23026251/8c71942e-f458-11e6-8837-704ed5682a06.png">

**Comment by mstriemer** [comment]
I have a feeling the left-aligned icon would look a bit odd floating in space where the centred one currently is.

I have a feeling the lines are centred because left-aligning them is a LTR convention. We would likely want to flip that around so it's right-aligned for RTL locales. Centring the lines is probably a more universal icon to use.

**Comment by tofumatt** [comment]
Hmm, that's a good point. But if the left-aligned one is better, flipping it for RTL and improving usability everywhere is still better.

**Comment by aayushsanghavi** [comment]
@tofumatt @mstriemer does this need any fixing or changing?

**Comment by mstriemer** [comment]
I think we'll need input from @pwalm if a left/right aligned icon would be better than having it centred, first.

**Comment by pwalm** [comment]
Would prefer it centered since the button is centered over the four sort options. I would use left-aligned if we just used a standard dropdown control, though.

**Comment by tofumatt** [comment]
Cool, I think that makes sense. I'll close this for now then, I think perhaps it's a non-issue 😄
