### ISSUE TITLE
Switch to new review API endpoints

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1838]
This is to adjust the UI so that it connects to the new review API endpoint: https://github.com/mozilla/addons-server/pull/4692

For QA, please check that this doesn't create any regressions for the following actions:
* Go to add-on detail page, add a star rating, edit star rating
* After selecting a star, create a review, edit the review
* From the add-on detail page, tap 'read N reviews' to see a list of all reviews

**Comment by kumar303** [comment]
@muffinresearch @vcarciu oof, sorry. We should have waited on the frontend patch before landing the backend patch. The dev server will be broken until this lands. In all honesty, it took more effort/time to fix the frontend than I thought it would.

**Comment by muffinresearch** [comment]
@kumar303 np - at least this way one patch will close multiple issues :)
