### ISSUE TITLE
Handle updated disco pane data from Firefox

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#1840]
Since we aren't using the list of installed add-ons on the disco pane and we have a separate method of retrieving this data for add-ons we care about Firefox is going to stop sending the user's add-on data in the URL's hash. This work is tracked in [bug 1340312](https://bugzilla.mozilla.org/show_bug.cgi?id=1340312).

Hopefully we'll get something like `{"hasExtensions": false, "hasThemes": true}` instead, but check the bug.

**Comment by muffinresearch** [comment]
The original bug was closed wontfix so I think we can live with things the way they are for now until that situation changes.
