### ISSUE TITLE
"Not found" message when trying to add a review

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1843]
Steps to reproduce:
1.On Android, login to AMO-dev and open an add-on(https://addons-dev.allizom.org/en-US/android/addon/clean-links/)
2.Try to add a review by pressing on rating stars

Expected results:
Review form is opened

Actual results:
_Not found_ error is displayed and users are not able to add reviews

NOTES:
Console error:
Unhandled promise rejection Error: Error calling API
Stack trace:
a@https://addons-amo-dev-cdn.allizom.org/amo-3dfc525cff9991fbb53a.js:12:12173
u/<@https://addons-amo-dev-cdn.allizom.org/amo-3dfc525cff9991fbb53a.js:12:13078

Please see video for this issue:
![notfound](https://cloud.githubusercontent.com/assets/1583842/23068090/d6536ea0-f52a-11e6-8055-7063923e7e4c.gif)

**Comment by muffinresearch** [comment]
I think this probably depends on https://github.com/mozilla/addons-frontend/issues/1838

**Comment by kumar303** [comment]
This should be fixed by https://github.com/mozilla/addons-frontend/issues/1838

**Comment by vcarciu** [comment]
Verified as fixed : 
![reviewsok](https://cloud.githubusercontent.com/assets/1583842/23218855/07094386-f926-11e6-9aeb-8943f22d1669.png)

**Comment by vcarciu** [comment]
Verified as fixed :  
![writeok](https://cloud.githubusercontent.com/assets/1583842/23218923/4c5e5a2a-f926-11e6-8b6d-47d9e31d9e78.png)
