### ISSUE TITLE
Forever "Loading" screen when trying to read add-ons reviews

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1844]
Steps to reproduce:
1.On Android, login to AMO-dev and open an add-on(https://addons-dev.allizom.org/en-US/android/addon/clean-links/)
2.Try to read all reviews for this add-on

Expected results:
A list of reviews is displayed

Actual results:
Forever "Loading" screen is displayed

Please see screenshot for loading screen : 
![foreverloading](https://cloud.githubusercontent.com/assets/1583842/23068275/b6073ec8-f52b-11e6-9a32-6955e2e65245.png)

**Comment by muffinresearch** [comment]
I think this probably depends on https://github.com/mozilla/addons-frontend/issues/1838

**Comment by kumar303** [comment]
This should be fixed by https://github.com/mozilla/addons-frontend/issues/1838

**Comment by vcarciu** [comment]
Verified as fixed : 
![reviewsok](https://cloud.githubusercontent.com/assets/1583842/23218879/25a07cb0-f926-11e6-88e2-83c9406790bf.png)
