### ISSUE TITLE
URL should be truncated if too long and outgoing prefix removed from text

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1859]
Steps to reproduce:
1.On Android, open https://addons-dev.allizom.org/en-US/android/addon/gotomeeting
2.Go to More information section
3.Observe the address listed under _Website_

Expected results:
The _Website_ should be should be a link to the website page like on desktop

Actual results:
The address displayed is the _outgoin.stage.mozaws,.net..._ long address 

NOTES:
Desktop link to same add-on : https://addons-dev.allizom.org/en-US/firefox/addon/gotomeeting/?src=ss

Please see screenshot of this issue : 
![linkify](https://cloud.githubusercontent.com/assets/1583842/23135715/5a904ce6-f7a2-11e6-9eb6-4f0d6f079775.png)

**Comment by tofumatt** [comment]
The website header should not be a link; it is a header/content arrangement as per the mocks. But the long URL in here could be shortened for sure. Unfortunate that this one has the outgoing URL in it... I hope most of these aren't prefixed with the outgoing URL; if so we'll need to remove that...

**Comment by muffinresearch** [comment]
Actually displaying the links is still likely to run into long string issues even without the outgoing prefix. I wonder if we should consider a different approach to handling all the links in one go. 

E.g: 

### Add-on Links
* Add-on Homepage
* Add-on Support URL

Or something else?

**Comment by tofumatt** [comment]
That’s a good point, and I like the idea of adding the support URL into that section. I’ll tidy it up that way.

**Comment by vcarciu** [comment]
Verified as fixed : 
![outgoinglinks](https://cloud.githubusercontent.com/assets/1583842/23400034/323d69ea-fdab-11e6-8a1f-b9fc95cfb721.png)
