### ISSUE TITLE
Search is not working as expected

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1863]
Steps to reproduce:
1.On Android(6.0.1), open latest Nightly and go to https://addons-dev.allizom.org
2. Search for "Video" in searchbox

Expected results:
A list of results is displayed

Actual results:
Nothing happens 

NOTES:

- This is consistently reproducible for me, but I saw different results for other colleagues. When searching for "Video" some of them are receiving "No results found" even if this is not true. 
- For another searchterms nothing happens for me too, but for other colleagues this worked fine(ie. searching for "Game" will do nothing for me, but worked on another Android devices)
- If entering in a Category , Search will work

Console results when nothing happened after search : 

TypeError: this._recipeManager is null[Learn More]  LoginManagerParent.jsm:73:9
Unhandled promise rejection TypeError: n is null
Stack trace:
[object Object]  amo-71e408971f66f1171904.js:194:15063
Unhandled promise rejection TypeError: n is null  (unknown)

Please see video for this bug : 
![searchmobile](https://cloud.githubusercontent.com/assets/1583842/23170487/f56d00e6-f857-11e6-9100-d8f4de0a9ad2.gif)

**Comment by muffinresearch** [comment]
@vcarciu Can you compare nightly versions for where it works and where it doesn't? The console message points to a FF bug potentially so it might just be a momentary problem with nightly.

**Comment by muffinresearch** [comment]
Probably fixed by https://github.com/mozilla/addons-frontend/pull/1950

**Comment by vcarciu** [comment]
Verified as fixed : 
![srch](https://cloud.githubusercontent.com/assets/1583842/23661452/742b5556-0355-11e7-9dad-761e96e26857.gif)
