### ISSUE TITLE
Add-ons cannot be installed from disco pane when mamo cookie is set

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1867]
Prerequisites:
- `extensions.webservice.discoverURL` is set to point to -dev (https://discovery.addons-dev.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%)
- `xpinstall.signatures.dev-root` set to true
- browser used: FF54

Steps to reproduce:
1. On AMO-dev (desktop) homepage,  go to footer and click "View Mobile Site"
2. Go to about:addons and try to install an add-on i.e. Video DownloadHelper

Expected results:
The add-on is installed.

Actual results:
The add-on cannot be installed.

Notes/Issues:
- issue is not reproducing for -stage or -production.
- issue is not reproducing on -dev either if first step is not fulfilled
Verified on FF54(Win 7). Issue is reproducing on AMO-dev.
Screenshot for this issue:
![about_addons](https://cloud.githubusercontent.com/assets/15685960/23212329/d3fd073c-f90e-11e6-874a-cd350d83f8f7.png)

**Comment by muffinresearch** [comment]
I can reproduce this.

The cause is the redirection fallback mechanism. If you look at network traffic the redirects look like this: 

```
10:55:45.283 GET
https://addons-dev.allizom.org/en-GB/firefox/downloads/file/224748/video_downloadhelper-4.9.21-fx%2Bsm.xpi/[HTTP/1.1 301 MOVED PERMANENTLY 125ms]  

10:55:45.412 GET
https://addons-dev.allizom.org/firefox/downloads/file/224748/video_downloadhelper-4.9.21-fx%2Bsm.xpi/[HTTP/1.1 302 Found 106ms]  

10:55:45.526 GET
https://addons-dev.allizom.org/en-GB/firefox/downloads/file/224748/video_downloadhelper-4.9.21-fx%2Bsm.xpi/[HTTP/1.1 301 MOVED PERMANENTLY 125ms]  

10:55:45.657 GET
https://addons-dev.allizom.org/firefox/downloads/file/224748/video_downloadhelper-4.9.21-fx%2Bsm.xpi/[HTTP/1.1 302 Found 92ms]  

10:55:45.757 GET
https://addons-dev.allizom.org/en-GB/firefox/downloads/file/224748/video_downloadhelper-4.9.21-fx%2Bsm.xpi/[HTTP/1.1 301 MOVED PERMANENTLY 132ms]  
```

We need to add locale prefix exclusions to fix this.

**Comment by muffinresearch** [comment]
See https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L273 for the list on AMO.

**Comment by tofumatt** [comment]
My understanding of this issue is we shouldn't be doing any redirects here like we do for lang/locale/clientApps. We're simply allowing certain URLs to be supplied without a locale. I'll proceed with a patch assuming that.

**Comment by ValentinaPC** [comment]
Verified the initial issue on FF55(Win 7) and work as expected for all add-ons available in Disco Pane.
Please see video: 
![install](https://cloud.githubusercontent.com/assets/15685960/23701084/e277a584-03fd-11e7-97d7-c92c3f9000be.gif)
