### ISSUE TITLE
No "Report an issue" section in add-ons details page on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1868]
Steps to reproduce:
1. Load add-on details page for an add-on using your Android device
2. Report an issue

Expected results:
According to mock-ups, user is able to report an issue.

Actual results:
The "Report an issue" section does not exist.

Notes/Issues:
Verified on AMO-dev FF51(Android 6.0.1)
Screenhsot for this issue:
- mock-ups: 
![2017-02-22_1632](https://cloud.githubusercontent.com/assets/15685960/23216632/4c8bcd5e-f91f-11e6-9a8a-2d34fba35938.png)
- actual add-on details page
![report](https://cloud.githubusercontent.com/assets/15685960/23216888/2914b6f0-f920-11e6-9ebb-8f2ac1bf0539.png)

**Comment by muffinresearch** [comment]
What I am adding in the PR is a report an issue link in the footer.

**Comment by ValentinaPC** [comment]
@muffinresearch : so, "Report an Issue" from every add-on details page will not be implemented, as initially intended?

The "Report a bug" link in AMO footer, mobile, was added and works as expected.
Postfix screenshot:
![link](https://cloud.githubusercontent.com/assets/15685960/23602315/a47f2a1e-0258-11e7-9278-0ab65f04256c.png)
