### ISSUE TITLE
Extensions are shown when clicking "More popular themes"

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1869]
### Describe the problem and steps to reproduce it:
Relates to https://github.com/mozilla/addons-frontend/issues/1811

- Go to /en-US/firefox/themes/ 
- Scroll down and click "MORE POPULAR THEMES" 

### What happened?
- You are sent to /en-US/firefox/search/?sort=hotness which is just extensions.

### What did you expect to happen?
- You should see a url that is just themes e.g. /en-US/firefox/search/?sort=hotness&type=persona

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Screenshot of /en-US/firefox/search/?sort=hotness

![screen shot 2017-02-22 at 15 27 12](https://cloud.githubusercontent.com/assets/1514/23218156/67ca99d0-f913-11e6-958a-76da22a390d8.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![pentru vict](https://cloud.githubusercontent.com/assets/1583842/23312140/48b89308-fac1-11e6-9746-87ce2f71c09f.gif)
