### ISSUE TITLE
No button for sharing add-ons or themes

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1870]
Steps to reproduce:
1.On Android, go to amo-dev and open any add-on or theme

Expected results:
Share option should be available (required in mocks) : 
![addonsharing](https://cloud.githubusercontent.com/assets/1583842/23223471/d710b0ac-f933-11e6-8bc0-52f9631dbca7.png)

Actual results:
No share option available

NOTES:
If this is the same case as for Favorites, please change the label to mobile pages v2

**Comment by muffinresearch** [comment]
That's not part of v1.

**Comment by muffinresearch** [comment]
I don't think this feature is required or necessary.
