### ISSUE TITLE
Cannot uninstall a theme when mozAddonManager is not available

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1871]
Steps to reproduce:
1.On Android, go to AMO-dev and open a theme (ie. https://addons-dev.allizom.org/en-US/android/addon/colorful-cubes/)
2.Install it 

Expected results:
User should have an uninstall button for installed themes(required in mocks) : 
![themeuninstall](https://cloud.githubusercontent.com/assets/1583842/23223987/5154841e-f935-11e6-8627-f9547565279f.png)

Actual results:
No "Uninstall" button available

Screenshot of actual behavior : 
![screenshot_20170222-193044 1](https://cloud.githubusercontent.com/assets/1583842/23224060/8a60d168-f935-11e6-8f62-9ce804078b79.png)

**Comment by vcarciu** [comment]
Sorry for the huge second screenshot, this is how it looks if you upload directly from device :)

**Comment by muffinresearch** [comment]
@vcarciu Presumably if you have mozAddonManager available you don't see this? Is the device setup for testing?

**Comment by vcarciu** [comment]
I can confirm that after setting the extensions.webapi.testing to true, I can install/uninstall the theme via radio on/of button

**Comment by muffinresearch** [comment]
Whilst this is a less common case we should still consider if we can do any reasonable fallback api for uninstalling for UAs that would otherwise be able to install but don't have mozAddonManager enabled.

**Comment by muffinresearch** [comment]
Afaict there's no API for uninstalling if mozAddonManager is not available. So this is a wontfix as this will just work in the same way the historical amo does.
