### ISSUE TITLE
Check RTL theme position in a true RTL FF edition

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1879]
This can be filed under "Sweat the details" I'm not sure if LW theme images are inverted when installed. If they are we should transform the images on the site so the themes are a true reflection of the FF UI.

* [x] Are theme images inverted when installed in a RTL language download of FF?
* ~If the answer to the first question is yes, invert the theme images on amo.~
* [ ] If the answer to the first question is no we should stop inverting the background anchor position for RTL - see comment below for CSS file references.

**Comment by muffinresearch** [comment]
Fixed my RTL FF install so I could check this - see below the theme image orientation is the same for both LTR and RTL. 

To that end we should not reverse the anchor location for preview and background images here [1] and here [2] 

[1] https://github.com/mozilla/addons-frontend/blob/master/src/amo/css/AddonDetail.scss#L85
[2] https://github.com/mozilla/addons-frontend/blob/master/src/core/css/SearchResult.scss#L109

<img width="375" alt="moz-logo-one-color-white-rgb_png___100___layer_0__rgb_8____and_ ____ _" src="https://cloud.githubusercontent.com/assets/1514/23269011/227e1062-f9e7-11e6-9ff4-53fa050d3333.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on FF51.0.1 RTL - build 20170125094131 under Windows 7.
Postfix screenshot: 
![button](https://cloud.githubusercontent.com/assets/15685960/23543338/67034432-fffa-11e6-8e62-7f21b8960f6a.png)

Verified in: My Themes, My Profile - themes section, theme details - More Other Themes/More by this artist, homepage, themes homepage - all buttons are displayed as expected.
Please let me know if there is anywhere else I should check this.
