### ISSUE TITLE
Fallback install buttons are shown for all UAs even if they can't install add-ons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1881]
### Describe the problem and steps to reproduce it:

Visit addons-dev with chrome on ios or chrome android or FF ios.

### What happened?

Since there's no mozAddonManager there's a fallback to install buttons which won't do anything when pressed since the UA doesn't work with FF extensions.

### What did you expect to happen?

A notice to show that the UA is not supported with a link to where to download FF from if relevant.
The buttons should also be disabled if they can't be used.

The notice will need UX input. This is something that can come as a post-release update.

**Comment by muffinresearch** [comment]
A quick v1 solution is to disable the button for all UAs (including FF ios) that can't install addons. This should ideally be done for the release.

A v2 solution is to prompt for firefox if we know it is relevant e.g. android non-firefox but not when on Firefox ios. This is not a blocker but the former is.

**Comment by muffinresearch** [comment]
> A quick v1 solution is to disable the button for all UAs (including FF ios) that can't install addons. This should ideally be done for the release.

This will be both the fallback install buttons + theme preview buttons too.

Theme buttons to disable for UAs that can't install add-ons (non-FF + FF IOS):

<img width="233" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/23453581/ca3bb642-fe60-11e6-9b17-14ff7d4b0b5e.png">

Addon button to disable for UAs that can't install add-ons (non-FF + FF IOS):

<img width="236" alt="add-ons_for_firefox" src="https://cloud.githubusercontent.com/assets/1514/23453658/1908212a-fe61-11e6-85da-06d077f05347.png">

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF51, FF54 and Chrome under Android 6.0.1 and obtained the following results:
1. FF browsers (_without the `extensions.webapi.testing`_) will not display disabled buttons and the possibility of _uninstalling a theme is unavailable_.
![untitled](https://cloud.githubusercontent.com/assets/15685960/23648557/e5486404-0323-11e7-961b-32e2b75013ad.png)

2. non-FF browser will display the buttons as disabled
![disabled](https://cloud.githubusercontent.com/assets/15685960/23648696/6289d894-0324-11e7-8b73-59e071113c5c.png)

@muffinresearch : I am interested if the first case is intended? Thanks!

**Comment by muffinresearch** [comment]
@ValentinaPC afaik there is no api for uninstalling a theme if mozAddonManager is not available. See also https://github.com/mozilla/addons-frontend/issues/1938 for the preview button being no-op.
