### ISSUE TITLE
How is compatibility of extensions handled?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1882]
In the mobile site it's unclear how we are dealing with compatibility for older user agents etc.
Are we doing anything in the API to filter out data for a specific versions of the client?

**Comment by kumar303** [comment]
The answer is no but could you restate this from a user perspective? Are you asking what will happen if a user has a page loaded in the mobile browser and we deploy a breaking change to the API before they have a chance to refresh the page?

**Comment by muffinresearch** [comment]
> The answer is no but could you restate this from a user perspective? Are you asking what will happen if a user has a page loaded in the mobile browser and we deploy a breaking change to the API before they have a chance to refresh the page?

To clarify I'm asking are we filtering out add-ons or extensions that are not compatible with the client installing them.

**Comment by kumar303** [comment]
Oh, I misunderstood. I believe this [app=android|firefox param](https://github.com/mozilla/addons-frontend/blob/master/src/core/api/index.js#L123) will only show supported add-ons in search results but @tofumatt probably knows more.

**Comment by muffinresearch** [comment]
> Oh, I misunderstood. I believe this app=android|firefox param will only show supported add-ons in search results but @tofumatt probably knows more.

Yeah I think we're filtering at a client application type level e.g. `firefox` or `android` but I thinking about version issues. If the add-on says it only supports up to `53.x` would we should it as incompatible for something running `54.x`?

**Comment by muffinresearch** [comment]
@pwalm how do you think we should handle version compatibility? I wonder if the quickest way would be to do something in parity with what we do for amo today e.g. disabling the buttons and adding a message since that check can be done in JS. 

The only bad part of that is having to do UA sniffing to make it work which can be unreliable if users change their UA string. 

Long term if we want to do it client-side we should get it added as a browser API.

**Comment by muffinresearch** [comment]
Adding this as `blocks release` for the moment but it might not be depending on the requirements.

**Comment by pwalm** [comment]
I generally think we should just not show users extensions that are incompatible, but that sucks for users browsing with other devices/browsers. I say parity today, with a better solution when we launch AMO Desktop later this year.

**Comment by muffinresearch** [comment]
I'm going to close this and file a new bug for the V1 action.
