### ISSUE TITLE
Consider using fastclick or similar.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1883]
I notice when using an android device sometimes clicks can be hard to activate  (e.g. the logout button) and having to hit it multiple times feels clunky.

We should at implementing some kind of fast click support e.g: https://www.npmjs.com/package/react-fastclick

**Comment by kumar303** [comment]
Hmm, maybe https://github.com/mozilla/addons-frontend/issues/1904 is related to this

**Comment by ValentinaPC** [comment]
Clicks - Taps seem to work ok on FF52(Android 6.0.1), even if #1904 is still reproducing.

Please let me know if anything in particular should be tested here.

**Comment by kumar303** [comment]
@ValentinaPC the only thing that needs testing here is that nothing was regressed in relation to taps on Android. If you can tap on links and buttons and they work just as they did before then this patch can be marked as verified.

**Comment by ValentinaPC** [comment]
Tapping is working as before on Android.
Verified as fixed on AMO-dev FF52(Android 6.0.1).
Checked a bunch of pages and tapping :)
Marking this verified-fixed.
