### ISSUE TITLE
Improve ratings and user count meta data

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1888]
From @pwalm's comment in https://github.com/mozilla/addons-frontend/issues/1698#issuecomment-282094051 :

Proposed:
<img width="575" alt="screen shot 2017-02-23 at 11 24 20 am" src="https://cloud.githubusercontent.com/assets/6797635/23275261/b32a62dc-f9ba-11e6-8cf3-77e20a0aaf8f.png">
We kill the icons and just use text for users/reviews. We'll run into less errors with long l10n translations.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF52(Android 6.0.1).
Changes seem to be implemented, but I have a question: @tofumatt, for other languages like for example - French, should the rating stars be aligned with the number of users and the number of reviews?
Please see the screenshot to see what I mean:
![2017-03-22_1436](https://cloud.githubusercontent.com/assets/15685960/24198129/2b5af890-0f0d-11e7-8489-998e7c7413ae.png)

**Comment by tofumatt** [comment]
Yes they should... I'm surprised they aren't. Can you send me a link to the page where it's happening?

**Comment by ValentinaPC** [comment]
While checking through more languages, I can see that ratings stars are always centered after the length of the number of users.
Examples:
- https://addons-dev.allizom.org/de/firefox/addon/extended-statusbar/?src=hp-dl-featured
- https://addons-dev.allizom.org/dsb/firefox/addon/extended-statusbar/?src=hp-dl-featured
- https://addons-dev.allizom.org/fr/firefox/addon/extended-statusbar/?src=hp-dl-featured
- https://addons-dev.allizom.org/nl/firefox/addon/extended-statusbar/?src=hp-dl-featured
- etc.

**Comment by tofumatt** [comment]
Ah, okay. That’s a separate bug, can you file and assign it to me? I’ll fix it :-)

**Comment by ValentinaPC** [comment]
Sure! Logged it. 
Marking this verified fixed.
