### ISSUE TITLE
"Server Error" page displayed while page refresh for some add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1898]
Steps to reproduce:
1. Load AMO-dev homepage
2. Search for "Venezuela" and access "Spanish (Venezuela) spell check dictionary" add-on details page
3. Refresh the page

Expected results:
There are no display or layout issues.

Actual results:
A "Server Error" page is loaded.

Notes/Issue:
- issue can be reproduce on desktop if on add-on details page from step 2 - https://addons-dev.allizom.org/en-US/android/addon/diccionario-espa%C3%B1ol-venezuela/?src=ss we click "View Mobile Site"
- the URL stays the same (https://addons-dev.allizom.org/en-US/android/addon/diccionario-espa%C3%B1ol-venezuela/?src=ss)
- other examples:
   - https://addons-dev.allizom.org/mk/android/addon/google-translate-auto-espa%C3%B1ol/?src=ss

Verified on FF51(Android 6.0.1, Win 7).
Issue is reproducing on AMO-dev.
Video for this issue on device:
![videotogif_2017 02 24_17 06 07](https://cloud.githubusercontent.com/assets/15685960/23308967/91fbb54c-fab5-11e6-8357-c190b323030e.gif)
Video for this issue on desktop:
![desktop](https://cloud.githubusercontent.com/assets/15685960/23309300/d4b9da20-fab6-11e6-87f3-7ad91a884781.gif)

I think that this is localization related. Supposition.

**Comment by kumar303** [comment]
Good catch, thanks. Here is the stacktrace:
<img width="643" alt="screenshot 2017-02-24 09 57 26" src="https://cloud.githubusercontent.com/assets/55398/23310310/bdfddc26-fa77-11e6-8f2e-967b9a3679df.png">

**Comment by kumar303** [comment]
`index.js:92` is `./src/amo/components/RatingManager/index.js:92`

**Comment by ValentinaPC** [comment]
Verified this on AMo-dev FF51(Win 7, Android 6.0.1) and is still reproducing on both mobile and desktop.
Video from desktop:
![desktop](https://cloud.githubusercontent.com/assets/15685960/23353547/af0ce8dc-fcd5-11e6-8672-1a10b6f78224.gif)

**Comment by kumar303** [comment]
Whoops. This was an entirely separate bug that was hidden by the first. A fix is forthcoming in https://github.com/mozilla/addons-frontend/pull/1920

**Comment by ValentinaPC** [comment]
Verified as fixed on FF51(Win 7, Android 6.0.1)
Postfix video:
![dict](https://cloud.githubusercontent.com/assets/15685960/23395630/4f74753e-fd98-11e6-9c13-1146b4286e7e.gif)
