### ISSUE TITLE
No "Show less" option for extension description

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1907]
On an extension detail page, a user can click "Read more" to see more of the written description, but they can't "read less" and close the expanded block. Can we add "Close" at the bottom of the block in the same style?

**Comment by tofumatt** [comment]
I responded to a QA issue about this in #1736. I don't think it makes sense to offer a "read less"/"close" button as the user has already expanded the info with an explicit action that doesn't make anything on the page less usable really. I guess if the description is massive it's more work to scroll, but even so it feels like it clutters up the page to have a "show less" button after explicit user action to show it. I'd rather leave this as won't fix unless I'm totally wrong (if so reopen).
