### ISSUE TITLE
White blocks behind icons

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#1908]
White blocks are showing up behind extension icons. Can we remove these please?

![screen shot 2017-02-24 at 12 56 43 pm](https://cloud.githubusercontent.com/assets/6797635/23320712/c0a25c18-fa90-11e6-8109-b887dbc6fb85.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![iconback](https://cloud.githubusercontent.com/assets/1583842/23411057/ea48cbdc-fdd9-11e6-8bcb-9ac80a8d989c.png)
