### ISSUE TITLE
Allow deferred: true to be overridden in safeAsyncConnect (or remove deferred: true as it seems to do nothing)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#1909]
I think it would be nice to be able to override `deferred: true` in `safeAsyncConnect`. I know it's our default but not being able to override the conf values when it _looks_ like we should be able to seems like a bad API.

Not a priority, but filing here as I think it's a good idea.

**Comment by kumar303** [comment]
I thought about this but the `safeAsyncConnect` function is already throwing an error if we don't define a promise. Thus, our usage is always `deferred: true`. I think it would be good until we have an actual use case for not passing a `promise` to `asyncConnect()` and then rework this code. Hopefully by that time we will have ported away from `asyncConnect()` anywa6y.

**Comment by kumar303** [comment]
Wait, wat. It doesn't even look like `deferred` is used for anything: https://github.com/makeomatic/redux-connect/search?utf8=%E2%9C%93&q=deferred

**Comment by kumar303** [comment]
Sounds like we should just remove `deferred` altogether since it doesn't appear to be doing anything. We should do this after the v1 launch to be safe though.
