### ISSUE TITLE
Old AMO page for Complete Themes on mobile

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1916]
Steps to reproduce:
1. Load AMO-dev Complete Themes page on mobile https://addons-dev.allizom.org/en-US/android/complete-themes/

Expected results:
404 page is displayed or a page using new mobile redesign.

Actual results:
An old AMO page is displayed.

Notes/Issues:
Verified on FF51(Android 6.0.1).
Screenshot for this issue:
![ct](https://cloud.githubusercontent.com/assets/15685960/23355752/e8976762-fcdf-11e6-98a3-d604d6b20266.png)

**Comment by tofumatt** [comment]
That seems to load an empty page and we aren't supporting complete themes so closing this as won't fix.

**Comment by ValentinaPC** [comment]
If we aren't supporting CT, then displaying a 404 page, as for https://addons-dev.allizom.org/en-US/android/seamonkey/ while loaded on mobile, may be a solution. 
But, it for chance, an user sees this... is not nice. 
Thanks!

**Comment by tofumatt** [comment]
Ah, I see. Because we 404 and fallback to the existing site with a page...

Okay, reopening this.

**Comment by muffinresearch** [comment]
If this is an empty page on  addons-server then we should 404 it there for mobile UAs.

**Comment by tofumatt** [comment]
Yeah, so this is more an addons-server bug. I'll file an issue for that.

Matthew Riley MacPherson (sent from mobile)

**Comment by muffinresearch** [comment]
> Yeah, so this is more an addons-server bug. I'll file an issue for that. 

@tofumatt did you get a chance to create a server bug for this?

**Comment by tofumatt** [comment]
Oh shoot, I did not. Filed: https://github.com/mozilla/addons-server/issues/4869
