### ISSUE TITLE
What is the solid category for themes?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1932]
It's not clear what solid means in this context? 

We could consider changing the name so it's clearer what it represents.

**Comment by jvillalobos** [comment]
It means single colors or simple gradients, but we don't monitor categorization. /cc @devaneymoz @atsay

**Comment by devaneymoz** [comment]
I recently-ish wrote a PRD for updating our category and tagging systems. jorgev +1'd my suggestion to kill the Solid category.

https://docs.google.com/document/d/1-5Ad5kcKtwJizyDm2Jrz9hLy9dTYwxUcSHbHkXTKz_0/edit#

**Comment by muffinresearch** [comment]
Question answered!
