### ISSUE TITLE
Send client side errors to Sentry

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1933]
When an error happens on the client, let's [send it to Sentry](https://sentry.io/for/javascript/). Sentry for server side errors was hooked up in https://github.com/mozilla/addons-frontend/issues/1559

**Comment by muffinresearch** [comment]
@kumar303 does this still make sense to keep in as a release blocker or would we be ok to patch this post release?

**Comment by kumar303** [comment]
I think it would be nice to block release on this because otherwise we'll be flying blind. However, I'm trying to work out the server errors first since they seem more important. In any case, if we had to release without client error reporting, nothing will *break* in the philosophical sense because we won't know what's broken.

**Comment by kumar303** [comment]
This is broken because CSP is blocking the Sentry API. Oops.
