### ISSUE TITLE
Disable buttons for incompatible FF clients

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1935]
If the version of the add-on is not supported by the FF client we should disable the button as a minimum. We should also add a basic message since the switches don't support copy by themselves and I don't think it's great to rely on a tooltip for that.

Note this change will also apply to the fallback buttons in the case where mozAddonManager is not available *and* the Add-on is incompatible with that version.

**Comment by tofumatt** [comment]
Does this mean install buttons or something else? Because I think this is the same as #1881, aside from this one asking for some copy (which I can land once #1957 lands (just to make the diffs less annoying).

**Comment by kumar303** [comment]
#1881 is about disabling the button on browsers that don't support add-ons at all, like Chrome. This bug (#1935) is a little more complicated; it's saying to disable the button on incompatible Firefox versions. For example, on Firefox 46, we should disable the button if the add-on requires Firefox 49 or higher.

**Comment by tofumatt** [comment]
Oh, okay, cool. Makes sense, I'll start on it tomorrow then.

**Comment by ValentinaPC** [comment]
@tofumatt : not sure where I can find the red banner for themes... as far as my knowledge goes theme don't have versions or compatibility options with Firefox... maybe you are talking about "themextensions"?
Would you please clarify this? Thanks!

**Comment by tofumatt** [comment]
I think you're right, themes are always compatible. But if you visit a theme page in chrome it will show the red banner.

**Comment by ValentinaPC** [comment]
> I think you're right, themes are always compatible. But if you visit a theme page in chrome it will show the red banner.

Yes, but not the banner from your screenshots. :P

Verified as fixed on AMO-dev using FF52, FF55, Chrome (Android 6.0.1) and FF6.1()1 under iOS 9.3.5.
Postfix screenshots:
![red](https://cloud.githubusercontent.com/assets/15685960/23892891/230e3030-08a5-11e7-818e-5da2bf7f03a4.png)
