### ISSUE TITLE
Convert theme installation to make state changes 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1936]
Recently the theme previewing was updated to dispatch, but the installation is still directly running events. It would be nice to fire the event calls off the back of state changes instead.

Making this dispatch would be nice for consistency but should also come in handy when we need to install an extension based theme (new themes) in place of the light-weight theme installation.

**Comment by willdurand** [comment]
@muffinresearch I am not sure to fully understand this issue, is it still valid?

**Comment by muffinresearch** [comment]
I think this can be closed out since it won't be worth fixing as static themes are going to supercede LWTs.
