### ISSUE TITLE
Get synchronous errors working in Sentry

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1942]
After adding [simulation URLs](https://github.com/mozilla/addons-frontend/pull/1934) I can confirm that async errors are being reported to Sentry but not synchronous errors. This could mean the middleware isn't fully configured.

**Comment by kumar303** [comment]
@jasonthomas could you set me up with a Sentry test instance to try and debug this?

**Comment by jasonthomas** [comment]
Sent info via IRC.
