### ISSUE TITLE
TypeError: n.authors[0] is undefined

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1949]
### Describe the problem and steps to reproduce it:
* Try to search for "data" (goes to https://addons-dev.allizom.org/en-US/firefox/search/?q=data)

### What happened?

* Note nothing happens and there's a JS error

### What did you expect to happen?

* Search results are displayed.

Looks like this line might not be defensive enough in the case where the authors list is empty. We should handle that and just not display anything in that case to prevent us breaking the listings.

**Comment by muffinresearch** [comment]
@kumar303 thanks!

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF51(Win 7, Android 6.0.1)
Search returns results. Tried with different criteria.
Postfix video:
![data](https://cloud.githubusercontent.com/assets/15685960/23603718/ee51bc78-025e-11e7-8780-2624f126ffde.gif)

If there is anything else must be checked here, please let me know.
