### ISSUE TITLE
"More Popular" Themes/Extensions are not sorted correctly

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1952]
Steps to reproduce:
1. Load AMO-dev on you device : https://addons-dev.allizom.org/en-US/android/
2. Go to "Browse All Themes"
3. Tap on "More Popular Themes"

Expected results:
Themes sorted ascending by users are displayed.

Actual results:
Random themes are listed.

Notes/Issues:
- "Most Popular Themes" section is also not sorted after popularity
- "Most Users" option from Sort menu is not selected, as "Top Rated" is selected wile accessing "More Highly Rated Themes".
- shouldn't we use same terms for popular themes? ("More Popular Themes" in themes homepage vs. "Most Users" option from Sort menu) 
Verified on AMO-dev FF51(Android 6.0.1).
Video for this issue: 
![videotogif_2017 03 03_09 43 14](https://cloud.githubusercontent.com/assets/15685960/23544217/c188132a-fffe-11e6-88a2-e04295f3b071.gif)

**Comment by ValentinaPC** [comment]
While using the new desktop pages, and accessing the page indicated in this issue - https://addons-dev.allizom.org/en-GB/firefox/search/?sort=hotness&type=extension - we will see no sort option being selected....I guess is not intended.
See screenshot:
![sort_001](https://user-images.githubusercontent.com/15685960/27663241-1269e8e6-5c6a-11e7-8aa9-fff98e4c1fcd.png)

**Comment by ValentinaPC** [comment]
This is happening for the new Filter menu also.
![more popular](https://user-images.githubusercontent.com/15685960/30954129-b4180e9c-a437-11e7-9232-7228923d3935.gif)

**Comment by tofumatt** [comment]
It seems we lack a "popularity" feature in the sort options which maps to "hotness" on the API.

We should add that sort option and this shoud be fixed, I'd think.

**Comment by willdurand** [comment]
@tofumatt does that mean our `SEARCH_SORT_POPULAR` constant is flawed? https://github.com/mozilla/addons-frontend/blob/10146082fb9b11b21408dd80ef14a6f5b24214f6/src/core/constants.js#L100

Related bug report: https://github.com/mozilla/addons-frontend/issues/3308#issuecomment-334690400

**Comment by ValentinaPC** [comment]
This is happening for each category.

**Comment by tofumatt** [comment]
Hmm, I guess this is a semantic difference then. "Popular" doesn't mean "by users", it means "what's popular"–the API lists it as "(average number of users progression), descending."

Maybe we need another option for "User count". @pwalm–what do you think about this? The idea with the popular sort is it's sort of ephemeral/changing with new add-ons getting more downloads, etc. But if that's confusing and people think it means "by most users" we should drop it/change it.

**Comment by pwalm** [comment]
How about "Trending"? That indicates add-ons that are popular **right now**.

**Comment by tofumatt** [comment]
Works for me!

So we’ll change “popular” to “trending” and add a new “popular” that maps to “most users”. Yay!

**Comment by willdurand** [comment]
@tofumatt could you please explain what should be changed because I am a bit confused currently.

- Do we have to replace all strings "Popular" by "Trending"?
- Do we have to change the `sort` algorithm in #3308 (most popular add-ons on homepage)?
- Where do we want "most popular" as in "trending" instead of "most users"?

**Comment by tofumatt** [comment]
Ah, this was assigned to me so I was gonna grab it, but:

1. Yes, the existing strings for "popular" should be changed to "trending". The constant should be changed too; anything pointing to the actual string `'hotness'` should be called `TRENDING`.
2. Most popular on the homepage should be changed to be most users, yes.
3. We want trending as a search filter, not sure if it exists on the homepage.

@devaneymoz: Did you want "Popular" on the homepage to mean "trending/up and coming" or "Most users"?

**Comment by willdurand** [comment]
There should also be a up and coming shelf (the last one).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Popular add-ons are correctly sorted.
A new sort option was added - trending - for the up & coming extensions.
Postfix screenshots:
![more](https://user-images.githubusercontent.com/15685960/31452365-66354cc8-aeb7-11e7-9522-3fbbd24b3261.png)
![popular-homepage](https://user-images.githubusercontent.com/15685960/31452371-6d648fae-aeb7-11e7-87e9-99db4555a2ff.png)
![ext_homepage](https://user-images.githubusercontent.com/15685960/31452404-7d1e4f66-aeb7-11e7-81f0-ad2afe0db523.png)
