### ISSUE TITLE
Navigation flow is strange

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1953]
Load https://addons-dev.allizom.org/en-US/firefox/themes/ and then click "MORE FEATURED THEMES"

When navigating the UI updates in the following order:

* URL changes
* Scroll jumps to the top
* Delay with no loading indicator
* Data loads in.

It would feel less strange if we didn't change the scroll position until the data is ready.
You'll see the same thing when using the back and forward button too.

**Comment by tofumatt** [comment]
I noticed the scroll jump too and it was annoying. We could certainly use the `<LoadingIndicator />` to overlay a generic loading screen on navigating that might help. Or do a more subtle one for generic nav.

**Comment by muffinresearch** [comment]
There's some discussion in this bug about why async transitions are not supported: https://github.com/taion/react-router-scroll/pull/59 

This polyfill looks like it might be a viable alternative to the scroll-behaviour route. https://github.com/brigade/delayed-scroll-restoration-polyfill

**Comment by tofumatt** [comment]
This should be solved by #2356.

**Comment by tofumatt** [comment]
This was, in fact, solved already even though we haven't 100% stripped out `redux-connect` (#2356). The navigation flow across the app uses our `LoadingText` component and is often quoted as being "really effing fast". 🕺🏻
