### ISSUE TITLE
Scroll position is not preserved pressing back after exploring non-search lists

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1954]
### Describe the problem and steps to reproduce it:

- Go to https://addons-dev.allizom.org/en-US/firefox/themes/
- Scroll down 
- Click an item to go to its details page
- Press back

### What happened?

The scroll position is not at the same point you were when clicking through to the details page.

### What did you expect to happen?

The search preserves the scroll position if you make a search, scroll down - click through to a details page. When you click back the scroll position is at the same place you were. The features view should work the same way.

**Comment by muffinresearch** [comment]
One notable difference between search and the themes page is that the API requests are re-made when going back. This should probably not happen.

**Comment by pwalm** [comment]
Our UX view: return user to same spot in scrolled list.

**Comment by tofumatt** [comment]
We could probably ensure that happens by scrolling to the add-on's guid if we made that an ID in the page.

**Comment by muffinresearch** [comment]
> We could probably ensure that happens by scrolling to the add-on's guid if we made that an ID in the page.

@tofumatt the main problem is waiting for data to be loaded to be able to get to it and this would suffer from that too.

I noted this on https://github.com/mozilla/addons-frontend/issues/1953 but it's probably more relevant here. I think this might provide a good general approach to scroll position restoration without tying it to any specific data.

> This polyfill looks like it might be a viable alternative to the scroll-behaviour route. https://github.com/brigade/delayed-scroll-restoration-polyfill

The only other consideration with this is that it's behaviour does somewhat overlap with what react-router-scroll does.

Note also react-router v4 does some things differently see https://reacttraining.com/react-router/web/guides/scroll-restoration - this might be good to tackle after https://github.com/mozilla/addons-frontend/issues/2161 to see what we actually need from scratch.

**Comment by muffinresearch** [comment]
I don't see this is an issue any longer.
