### ISSUE TITLE
Add unit tests for server middleware and request handlers (i.e. baseServer())

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1961]
We have integration tests for some app specific parts of [our middleware and request handlers](https://github.com/mozilla/addons-frontend/blob/master/src/core/server/base.js#L115) but we also need to add more unit-ish tests to exercise all the different types of error handling and recovery. I say unit-ish because ideally they will still use real web requests, just with fake routes.

**Comment by kumar303** [comment]
Beware this code will change when we switch to the new router https://github.com/mozilla/addons-frontend/issues/2161

**Comment by muffinresearch** [comment]
The main middlewares are now unit tests under Jest. There are other parts of the base server that need coveraget so I think this can stay open until that's done unless that's covered elsewhere.

**Comment by willdurand** [comment]
We do have tests for the `baseServer` for a while now, closing.
