### ISSUE TITLE
Developer link in listing page opens new tab

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#1962]
### Describe the problem and steps to reproduce it:
1. Go to https://addons-dev.allizom.org/addon/forecastfox-weather/
2. Click on the developer name (Ensolis).

### What happened?

Page opens in new tab.

### What did you expect to happen?

Page opens in same tab.

**Comment by ValentinaPC** [comment]
1. Tried this on device using FF51(Android 6.0.1) on -dev and a new tab was opened.
2. Tried this on desktop using FF51(Win 7) on -dev and the page opens in same tab.

Which case you are talking about?

**Comment by jvillalobos** [comment]
I'm referring to the first case. I was expecting it to open on the same tab on mobile.

**Comment by muffinresearch** [comment]
This is fixed it opens in the same tab now.

**Comment by AlexandraMoga** [comment]
Confirmed as fixed both for Android and Desktop.
