### ISSUE TITLE
Homepage and Support site links open in same tab

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#1963]
### Describe the problem and steps to reproduce it:
1. Go to https://addons-dev.allizom.org/addon/video-downloadhelper/
2. Scroll to the bottom and click on "Homepage" link.

### What happened?
Same tab navigates to homepage.

### What did you expect to happen?
New tab is opened with homepage, since we're going to a different site.

**Comment by muffinresearch** [comment]
This was by design I'm not sure we should always open a new tab for links to external sites the user can always click back.
