### ISSUE TITLE
Divisions in theme search results are too subtle

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#1965]
### Describe the problem and steps to reproduce it:
1. Run a query that generates many themes: https://addons-dev.allizom.org/en-US/firefox/search/?page=1&q=nature
2. Scroll down.

### What happened?

The division between themes is often invisible due to the theme image, so it's not clear which theme the metadata corresponds to. Ping @pwalm for opinion.

![theme](https://cloud.githubusercontent.com/assets/62568/23571718/5bbd06d6-0030-11e7-8479-9b3c2a1f5652.png)

**Comment by pwalm** [comment]
Not too worried about it now (theme decisions aren't destructive), but spacing will be increased in the AMO Desktop launch/mobile update.

**Comment by muffinresearch** [comment]
This would be simple to fix, we should do it.

**Comment by aayushsanghavi** [comment]
@pwalm @muffinresearch I'd like to work on this.
We just have to increase the bottom margin for fixing it right? or do you propose a different solution?

**Comment by muffinresearch** [comment]
This is fixed:

<img width="774" alt="reviews_for_awesome_screenshot_plus_-_capture__annotate___more_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35516886-d7871502-0504-11e8-8c31-d6cd137f562b.png">

**Comment by AlexandraMoga** [comment]
Confirmed as fixed. There is a separator now to mark the division;

![image](https://user-images.githubusercontent.com/31961530/35553565-17442f58-05a1-11e8-9ef0-cb0ba22207af.png)
