### ISSUE TITLE
Replace Fashionable category with something else

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#1966]
### Describe the problem and steps to reproduce it:
1. Go to https://addons-dev.allizom.org/android/ (on mobile)
2. Click on Fashionable.

### What happened?
Maxim

### Anything else we should know?
Not to be a prude, but maybe we should pick a category with less controversial content for the front page. How about "Music" or "Film and TV"?

/cc @atsay @devaneymoz @pwalm

**Comment by tofumatt** [comment]
👍 I too am not a prude but I dislike advertising those themes.

**Comment by pwalm** [comment]
Ugh. Those bikini/sexy lady themes are gross, we need to definitely remove them out of that collection. OR put in an equal amount of shirtless hunky dudes. Just kidding.

"Fashionable" to me was clothing brands, patterns, etc. If we can't find enough themes to fill out this collection we can change it to whatever. Let me know and I can make an icon.

**Comment by pwalm** [comment]
Just realized that this collection has 193 pages. Are we just pulling tags? These should be curated, best-of-the-best type stuff. This is a first impression for a lot of users, stumbling into a randomly generated group of themes/extensions will not serve us well.

**Comment by jvillalobos** [comment]
They are currently pointing to categories, not curated collections.

**Comment by muffinresearch** [comment]
@jvillalobos  @pwalm if we have an alternative plus an icon we can get this replaced before the release.

**Comment by jvillalobos** [comment]
We'll have to rely on categories for now, so what we need in the short term is an icon for another one of the categories. I suggested a couple already, but the full list can be seen at https://addons.mozilla.org/android/themes/

**Comment by pwalm** [comment]
How about "Festive" that points to the Holiday category?

**Comment by tofumatt** [comment]
Do we have a festive icon? If you can send the icon I can switch it.

**Comment by pwalm** [comment]
Festive icon!

[festive-icon.zip](https://github.com/mozilla/addons-frontend/files/825473/festive-icon.zip)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1).
Postfix screenshot:
![2017-03-08_1140](https://cloud.githubusercontent.com/assets/15685960/23698427/2c36597c-03f4-11e7-857c-6df5b8afb60a.png)
