### ISSUE TITLE
Use page_size from responses in Pagination object

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1971]
Now that page_size is exposed in paged responses we can use it in the Pagination object. This means that requests are free to tune the page_size to whatever they want and as long as we consume the page_size from the response the pagination will reflect the correct number of pages.

**Comment by ValentinaPC** [comment]
This is happening in a strange way in production in what concerns empty searches for themes and collections.

STR:
1. Make an empty search from themes homepage https://addons.mozilla.org/en-US/firefox/search/?q=&cat=themes
2. Scroll down and click on the last available page number https://addons.mozilla.org/en-US/firefox/search/?page=20494&cat=themes

Results:
-URL is changed
-Listed results are from page 1.

Screenshot:
![2017-09-08_1251](https://user-images.githubusercontent.com/15685960/30206348-86cad36e-9494-11e7-86a7-e008cd3529a1.png)

Note:
- Page 1191 will display search unavailable message.
https://addons.mozilla.org/en-US/firefox/search/?page=1191&cat=themes

**Comment by ValentinaPC** [comment]
How it looks like now while making an empty search from Extensions homepage and going to page 401 - https://addons-dev.allizom.org/en-US/firefox/search/?page=401&platform=windows&type=extension
![untitled](https://user-images.githubusercontent.com/15685960/31330823-9c578508-ace8-11e7-853b-0b05301ab544.png)

**Comment by willdurand** [comment]
Good catch @ValentinaPC, I was about to fill an issue for a similar problem:

<img width="1392" alt="screen shot 2017-10-09 at 11 04 23" src="https://user-images.githubusercontent.com/217628/31332340-50d03d02-ace6-11e7-94e2-e79af803c8ed.png">

**Comment by ioanarusiczki** [comment]
@willdurand  The blank search on AMO -dev with FF61(Win10),indicates 14245 pages. The pages display content until page 1000, then the new frontend displays Page not found , switching on the old pages some content will be available.

![page1000blanksearch](https://user-images.githubusercontent.com/33448286/42519687-448b8ad8-846d-11e8-82e2-c52cf616492b.gif)

**Comment by willdurand** [comment]
> @willdurand The blank search on AMO -dev with FF61(Win10),indicates 14245 pages. The pages display content until page 1000, then the new frontend displays Page not found , switching on the old pages some content will be available.

I think this is a known issue, probably https://github.com/mozilla/addons-frontend/issues/3887

**Comment by ioanarusiczki** [comment]
@willdurand I'm marking this issue verified fixed on AMO dev with FF61(Win10). 

![returns content](https://user-images.githubusercontent.com/33448286/42570253-f69e102a-851b-11e8-85e4-ad8a95b5fac1.gif)
