### ISSUE TITLE
Login appears like is failing from a "Server Error" page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1973]
Steps to reproduce:
1. Load details page for any add-on i.e. https://addons-dev.allizom.org/en-US/android/addon/foxtrick/ on your device
2. Tap on add-on author name
3. Try to log in from the resulted page

Expected results:
User is logged in.

Actual results:
User cannot log in.

Notes/Issues:
- taping on "Firefox Add-ons" from that page loads mobile homepage;
- making a search from that page works as expected;
- going back to the first tab and refreshing the page, user is logged in;

Verified on AMO-dev FF51(Android 6.0.1)
Video for this issue:  
![videotogif_2017 03 06_13 28 55](https://cloud.githubusercontent.com/assets/15685960/23609239/b72b6e6c-0275-11e7-9084-0153756a3012.gif)

Relates to #1962

**Comment by mstriemer** [comment]
I think this is the same issue as #1975, we don't have a mobile version of a user page which the author link is sending you to. Closing in favour of #1975 since it has stack traces attached.
