### ISSUE TITLE
"No results were found" for some categories while being in "View Mobile Site"

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#1974]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/ desktop (device)
2. Click "View mobile site"
3. Go to "Block ads" category

Expected results:
Add-ons from that category are listed.

Actual results:
"No results were found" message is displayed.

Notes/Issues:
- if the user knows only the desktop site, may be confused, while loading it on device and being redirected to a _mobile site_ but does not find add-ons in a category.

Verified on AMO-dev FF51(Win 7, Android 6.0.1)
Video fro this issue: 
![videotogif_2017 03 06_15 29 51](https://cloud.githubusercontent.com/assets/15685960/23612147/edc86d1e-0282-11e7-803c-d3e4dab264f8.gif)

**Comment by muffinresearch** [comment]
This will be resolved as the mobile site is expanded onto desktop. Currently the categorization is different although I wonder if that should continue to be the case as we update the mobile site to work with desktop too?

**Comment by ValentinaPC** [comment]
Reproducing also for FF 6.1(1) under iOS 9.3.5.
Screenshot: 
![iphone](https://cloud.githubusercontent.com/assets/15685960/23892314/b5fb6e38-08a2-11e7-8079-12c7f135aac8.png)

**Comment by ValentinaPC** [comment]
This is also happening in the new desktop pages because the category from desktop is "Privacy & Security" while on "View Mobile Site" we call "https://addons.allizom.org/en-US/firefox/extensions/security-privacy/".
Screenshot:
![2017-06-21_1827](https://user-images.githubusercontent.com/15685960/27392444-5de62e94-56af-11e7-971c-fdb2f8deb89a.png)

**Comment by ValentinaPC** [comment]
This is in -prod.

**Comment by tofumatt** [comment]
Just for the record this is because those categories don't exist for desktop Firefox.

It might actually be best to 404 when the category isn't found.

**Comment by ValentinaPC** [comment]
> Just for the record this is because those categories don't exist for desktop Firefox.

The interesting fact is that for the first category "Block Ads" we load the page https://addons-dev.allizom.org/en-US/android/extensions/**security-privacy**/ and for desktop we have https://addons-dev.allizom.org/en-US/firefox/extensions/**privacy-security**/ :)

**Comment by tofumatt** [comment]
Yes, that’s because we have different categories for desktop versus mobile :-/

**Comment by ValentinaPC** [comment]
Based on https://github.com/mozilla/addons-frontend/issues/2084 this can be closed.
