### ISSUE TITLE
AddType not found should not be a 500

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1975]
Looks like certain paths lead to checking addonType and when the addonType is found it throws which results in a 500 error. 

One example is user urls which don't have a mobile component.

https://addons-dev.allizom.org/en-US/firefox/user/ensolis/

See both of these for examples of the same error:

- https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/384916/
- https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/384914/

I would think that most cases like this should actually be a 404?

**Comment by muffinresearch** [comment]
Would be nice to fix this for release if possible.

**Comment by mstriemer** [comment]
Could we set up nginx to redirect the `/blah/blah/user/.*` URLs to addons-server?

**Comment by muffinresearch** [comment]
> Could we set up nginx to redirect the /blah/blah/user/.* URLs to addons-server?

Could do, but it seems odd to me that there's an assumption that the first part of the url after `/%locale%/%clientApp%/` is a `addonType`. 

We're going to need a user page for desktop soon in any case.

**Comment by tofumatt** [comment]
> Could do, but it seems odd to me that there's an assumption that the first part of the url after `/%locale%/%clientApp%/` is a `addonType`.

It's because of how react-router works; we can't supply a regex for the URL (which is really just `/themes/` and `/extensions/` for our purposes) so the route is `/:addonType/` and that catches everything 😞

**Comment by kumar303** [comment]
The react-router docs are not great but I don't see an easy way to fix this. I guess we could just add a route for `user` so that it is forced into a 404? https://github.com/ReactTraining/react-router/blob/master/docs/guides/RouteMatching.md

**Comment by kumar303** [comment]
hmm, clicking on the user from here is still a 500 for me https://addons-dev.allizom.org/en-US/firefox/addon/tile-tabs/

**Comment by ValentinaPC** [comment]
Verified on FF51(Android 6.0.1) using AMO-dev: 500 page for me too.
Please see video: 
![videotogif_2017 03 07_16 42 24](https://cloud.githubusercontent.com/assets/15685960/23661488/925ae668-0355-11e7-849a-2cfd8c17283c.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC this patch isn't live yet the rev that's on -dev is 0fc05a5a7a8e4a954eff9e5842661e1c8a2120b5 which is before that patch landed.

**Comment by muffinresearch** [comment]
-dev deploys are currently blocked due to deps issues but once https://amo.addons-dev.allizom.org/__version__ is beyond 0fc05a5 it should be ready to test.

**Comment by kumar303** [comment]
This landed on dev. It's working for me now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix video:
![videotogif_2017 03 08_11 45 47](https://cloud.githubusercontent.com/assets/15685960/23698804/a5357d34-03f5-11e7-8db9-4b69199f25d3.gif)
