### ISSUE TITLE
Error: Can't set headers after they are sent for /en-US/developers/

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1976]
Sentry is logging an error for: https://addons-dev.allizom.org/en-US/developers/

https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/385086/

Might be related to the explicit 404 in middleware here: https://github.com/mozilla/addons-frontend/blob/master/src/core/middleware.js#L62

As mentioned in: https://github.com/mozilla/addons-frontend/pull/1915#issuecomment-284442753 that will be removed in a separate bug if that is the cause.

404 fallback appears to work correctly so I don't think this is necessarily a block it's just noise in Sentry.

**Comment by Ryuno-Ki** [comment]
Since you mentioned in that PR that you are about to fix it later I'd suggest to linkt to the file at a certain commit (hit <kbd>y</kbd> in the view) instead of the ever-changing master.

**Comment by muffinresearch** [comment]
Dupe of #2003
