### ISSUE TITLE
No tests/uitests should ever depend on an externally hosted resource

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1977]
I think some uitests rely on externally hosted resources such as the AMO dev API and production CDN. Here is a plan:

* Look at all [configs](https://github.com/mozilla/addons-frontend/tree/master/config) that start with `test-` or `uitest-`
* If any of those configs contain an external host, replace each value with `http://not-a-real-host`
* See what tests fail
* Kill those tests with fire (or fix them)
* Profit

I know for sure that this has caused issues in our build. For example, the CDN went offline and caused very hard to diagnose test failures. This kind of operational problem is better detected with op-specific health checks and alerts.

**Comment by willdurand** [comment]
@kumar303 I don't think we depend on external stuff anymore, at least not for the ui tests. I see that the CDN is disabled and we server assets with node (in `config/functional-development-amo.js`).
