### ISSUE TITLE
Sign Up - Age field should take maximum of 2 digits value.

### ISSUE THREAD

**Issue by MadhuriQA** [mozilla/addons-frontend#1982]
Steps to reproduce :

    1) open latest firefox release in android
    2) go to https://addons-dev.allizom.org/en-US/firefox/
    3) tap on Login/Sign Up button
    4) Sign Up - field - "How old are you?" - give input = 999  

Actual Result : 
 It proceeds with with the largest 3 digit value (as max.limit given in this field is 3 digits)

Expected Result :
Age field should take maximum of 2 digits value.

**Comment by muffinresearch** [comment]
@MadhuriQA this issue tracker is for the addons site itself - issues related to the Firefox Accounts UI should be filed here: https://github.com/mozilla/fxa-content-server/issues/new

FWIW someone could potentially be over 100 years old and then the 3 digits would be necessary.

**Comment by tofumatt** [comment]
I hope Firefox is the browser of centenarians! 😉
