### ISSUE TITLE
Implement the UX for navigation and data loading

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#1983]
In order to smooth out some of the kinks in the way navigation works in the mobile pages it would be good to define the way we want navigation to work so that it feels intuitive to the user.

@pwalm do you have thoughts on how navigating between pages should work are we just aiming for making it work as a traditional site would or should we be looking to aim for something that provides some kind of transition?

It would be good to cover general page navigation and how loading indicators should be surfaced. If there are specific interactions that aren't yet covered we could add details for those here too.

Related issues:

* Navigation flow is strange https://github.com/mozilla/addons-frontend/issues/1953 
* Scroll position is not preserved pressing back after exploring non-search lists  https://github.com/mozilla/addons-frontend/issues/1954

**Comment by kumar303** [comment]
What I've seen on other sites is a horizontal bar at the top of the page that changes colors or something.

**Comment by muffinresearch** [comment]
> What I've seen on other sites is a horizontal bar at the top of the page that changes colors or something.

@kumar303 yeah that could work. Something that at least indicates that something is happening could alleviate the current slightly adrift feeling when navigating. Sometimes I've made multiple clicks on something and inadvertently gone into a details page because it wasn't obvious a request was underway.

**Comment by muffinresearch** [comment]
This looks like the sort of thing: https://www.npmjs.com/package/react-redux-loading-bar

**Comment by pwalm** [comment]
I've done the same, not sure if the page is thinking on not. Let's try the loading bar at the top, using the colour @329AF0

**Comment by muffinresearch** [comment]
Thanks @pwalm sounds good!
