### ISSUE TITLE
Search placeholder overflows for non-en locales

### ISSUE THREAD

**Issue by mMARUF** [mozilla/addons-frontend#1986]
Steps to reproduce : 

1. open https://addons-dev.allizom.org/en-US/firefox/ in Android
2. hen at the bottom of the page , change the language from English to something else

Actual Result:

The search bar string crosses the mobile window. Then to read the whole string , scrolling the screen to the right is needed.

Actual Result :

The string should have been between the screen. It should not cross the screen size.

Attachment - 

1. https://drive.google.com/open?id=0B75_JfziYeofd3BndktvRXZYLTg
2. https://drive.google.com/open?id=0B75_JfziYeofTElzNnRRazRwMDA

**Comment by muffinresearch** [comment]
@mMARUF feel free to drop screenshots straight into bug descriptions it helps us to see the problem more directly without cross-referencing.

**Comment by muffinresearch** [comment]
@mMARUF thanks for the bug report by they way, good catch.

**Comment by muffinresearch** [comment]
The patch for this is a quick fix to stop the layout breaking but we should look at a better fix to not hide part of the placeholder in locales that have longer text.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF51(Android 6.0.1)
- Default text from search field is truncated;
- no horizontal scroll available;

But, typed text in the search field is not displayed.
Please see video: 
![videotogif_2017 03 08_10 48 13](https://cloud.githubusercontent.com/assets/15685960/23697180/629c6e70-03ef-11e7-9e7f-2757225bab0e.gif)

@muffinresearch : Please let me know if reopening this should be ok, or logging another is better.

**Comment by muffinresearch** [comment]
@ValentinaPC please open a new bug.

**Comment by ValentinaPC** [comment]
Thanks!
Marking this verified-fixed.
