### ISSUE TITLE
Problem:After go to the site https://addons-dev.allizom.org/en-US/firefox/ by mobile ,click on the search button "Search extensions and themes" . It will show '|' this emitted. But after few sec it will stop emitting.  Reproduce: Open Firefox browser in mobile.Go to this link " https://addons-dev.allizom.org/en-US/firefox/  " ,click the search option "Search extensions and themes". Happened: It will emitting this '|' ,but after few sec it will gone. Expect: This '|' will stay emitting as long as I stay in that page.

### ISSUE THREAD

**Issue by danialmas** [mozilla/addons-frontend#1989]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by danialmas** [comment]
![screenshot_2017-03-07-22-48-20-229_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23668462/5aa43aea-038b-11e7-8126-819f84a5e884.png)
![screenshot_2017-03-07-22-48-29-030_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23668461/5aa4359a-038b-11e7-97fb-f89e215d822f.png)

**Comment by muffinresearch** [comment]
This is default browser behaviour not anything specific to the site.
