### ISSUE TITLE
In a category, after clicking the next button 'no result' shows

### ISSUE THREAD

**Issue by nuzhat105** [mozilla/addons-frontend#1993]
steps to reproduce:
1.Go to home page(https://addons-dev.allizom.org/en-US/firefox/).
2.Click on any category themes(eg: wild).
3.Go to the bottom of that category page.
4.Press the next button.

Actual Result:
'there is no result found' - this message is shown and after few moment the page shows the search result.

Expected Result:
The page should show the search result immediately after clicking the next button.

**Comment by ValentinaPC** [comment]
I think this was tracked here: https://github.com/mozilla/addons-frontend/issues/1894 .
Thank you!
