### ISSUE TITLE
UI tests are broken on Circle CI (because of a pip bug)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1995]
The UI tests are currently broken in Circle CI. Here is an example: https://circleci.com/gh/mozilla/addons-frontend/1655#tests/containers/0
 
The UI tests are not broken on Travis CI. This is probably because Circle CI has a newer version of tox and / or pip.

This fix to pip looks like it will solve our traceback but it has not been released yet: https://github.com/pypa/pip/commit/dd3defe509d6103605d8da8270a4787f0e8ec616

**Comment by kumar303** [comment]
Note to self: if you add `--no-cache-dir` to the `install_command` in tox.ini here's how to reproduce the traceback locally:
- `npm run dev:disco`
- In a new shell...
  - `rm -fr .tox`
  - `tox -e discopane-ui-tests -- --base-url=http://localhost:3000`

**Comment by kumar303** [comment]
I think pip 9.1.0 will fix this

**Comment by tofumatt** [comment]
Is this still the case? The tests are passing now, right? So this can be closed?

**Comment by kumar303** [comment]
I guess it's still theoretically a problem since pip `9.1.0` hasn't been released yet but I downgraded and froze all deps in https://github.com/mozilla/addons-frontend/pull/1926 as a workaround so we can probably close this.
