### ISSUE TITLE
Don't use res.end()/render 404 in middleware for clientApp/locale exceptions

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2003]
Right now we render 404 inside the middleware and it causes errors with sending status codes twice. It also makes it harder to have more fine-grained URL exceptions.

What we want is to avoid prepending anything to the URL in the middleware for `*UrlExceptions` without actually sending a response. The app will still eventually 404, but it will be React Router doing it.

This is basically a follow-up/nicer way to implement #1915, but I likely won't get to it before we launch the new mobile pages.

**Comment by kumar303** [comment]
One thing to keep in mind is that without calling `res.end()` our responses will hang around in memory without getting garbage collected, leading to a memory leak.

**Comment by tofumatt** [comment]
Eventually we will call `res.end()`, but in `server/base.js` rather than `middleware.js` where we currently do for the 404 exceptions.

Now that we're routing only the correct routes via nginx, this might actually be worth just removing...
