### ISSUE TITLE
"Add to Firefox" button is too long for non-EN locales

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2006]
Steps to reproduce:
1. Load AMO-dev page on device
2. Navigate to an add-on details page 
3. Change the language to hu (other example: nl) i.e. https://addons-dev.allizom.org/hu/android/addon/phony/
4. Observe "Add to Firefox" button

Expected results:
There are no display or layout issues.

Actual results:
The button is too long.

Notes/Issues:
- also, an horizontal scrollbar is available.
Verified on AMO-dev FF51(Android 6.0.1)
Video for this issue: 
![videotogif_2017 03 08_12 01 33](https://cloud.githubusercontent.com/assets/15685960/23699313/4c988b38-03f7-11e7-9b0f-d1a33187f171.gif)

**Comment by muffinresearch** [comment]
This should only be the case for UAs without mozAddonManager enabled.

**Comment by ValentinaPC** [comment]
Closed in favor of #2047 .
