### ISSUE TITLE
Substitutions in debug locales are being mangled by podebug

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2008]
Running dennis polinter on amo revealed that podebug is mangling the var substitutions:

```
E201: invalid variables: %(ɐʌǝɹɐƃǝᴚɐʇıuƃ)s
56:#: src/amo/components/AddonMeta.js:28
57:msgid "%(averageRating)s out of 5"
58:msgstr "‮%(ɐʌǝɹɐƃǝᴚɐʇıuƃ)s onʇ oɟ 5"
```

For the debug locales to be any use we need to find a way to prevent this happening.

**Comment by muffinresearch** [comment]
This is fixed.

**Comment by AlexandraMoga** [comment]
Please add some STR or the label 'qa:not needed'
