### ISSUE TITLE
We should change the Sporty theme category from homepage

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2009]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/android/ (on mobile)
2.Click on Sporty.

Expected results:
No controversial themes should be advertised on homepage

Actual results:
There are some controversial themes displayed in this category

Notes:
Logged based on https://github.com/mozilla/addons-frontend/issues/1966 . The "controversial" themes are not nearly as many as for Fashionable category, but they are still there.

**Comment by kumar303** [comment]
We have a production test link so I checked it there and it's not as bad as dev. There is only one bikini theme (Sports Illustrated) but it's way at the bottom of the result list. I don't think we need to get rid of the category just for that.
