### ISSUE TITLE
No on screen "Go to" button for search.

### ISSUE THREAD

**Issue by danialmas** [mozilla/addons-frontend#2010]
### Describe the problem and steps to reproduce it:
=> **Problem**: Can't search any item by clicking on screen search button or "go to" button. 
**Reproduce**:
•	Go to the link "https://addons-dev.allizom.org/en-US/firefox/".
•	Click on the Search button.
•	 Search for something by clicking on screen search button or "go to" button.

### What happened?
   =>  There has no on screen "go to" or search button.

### What did you expect to happen?
=> There should have an on screen search button or "go to" button.
![screenshot_2017-03-08-19-18-35-795_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23705829/cf893798-0435-11e7-800e-57ee97cbf3c6.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by kumar303** [comment]
Thanks for taking the time to submit a bug. This was a conscious design decision so I'm closing the issue. You press enter to search.
