### ISSUE TITLE
Problem with the themes button to set any theme in normal window when that page or any other theme page is open in private window.

### ISSUE THREAD

**Issue by danialmas** [mozilla/addons-frontend#2011]
### Describe the problem and steps to reproduce it:
=> **Problem**: After set a theme in normal window, open a private window and set a theme again in there. Then back to the normal window  when I set a different theme again in here, the theme set button was hanged.
**Reproduce**: 
•	Go to the link "https://addons-dev.allizom.org/en-US/firefox/".
•	Set any theme from there. 
•	The theme set button work properly and it will turn into green.
•	 Then go to the private window.
•	Go to the same link. 
•	Set any of the theme.
•	The theme set button work properly. 
•	Back to the normal window, now set any of the theme again.

### What happened?
=>The theme set button will not work this time. The button will be hanged. But the theme is set properly. When go to back and come back to the same page, now the theme set button goes green. If want to disable it to click the button again and it will be hanged again. If we will do the process in reverse, means if open the private window 1st and the open the normal window, show this time the problem will be shown in private window.

### What did you expect to happen?
=> The theme set button should not be hanged. 
![screenshot_2017-03-08-19-20-09-473_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23706081/f11db3d8-0436-11e7-8b11-d40b5be95fa1.png)
![screenshot_2017-03-08-19-21-17-279_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23706082/f1211348-0436-11e7-8f2e-1ab0033b530b.png)
![screenshot_2017-03-08-19-21-27-758_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23706080/f11b09ee-0436-11e7-8232-d9ba737cebca.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by muffinresearch** [comment]
@danialmas is this still reproducible for you?
