### ISSUE TITLE
For faster scrolling a black band appear on the bottom of the page.

### ISSUE THREAD

**Issue by danialmas** [mozilla/addons-frontend#2013]
### Describe the problem and steps to reproduce it:
=> **Problem**: When I scroll the page faster ,there was a black band appear on the bottom of the page for few moment.
**Reproduce**:
•	Go to the link "https://addons-dev.allizom.org/en-US/firefox/".
•	Scroll the page slowly. It will work normally.
•	Now scrolling the page up and down faster.

### What happened?
=> A black band will appear on the bottom of the page for few moments.

### What did you expect to happen?
=> There should be no black band on the bottom of the page how I scroll it. 
![screenshot_2017-03-08-02-46-18-914_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23706371/1ea7860c-0438-11e7-83b6-900934fd3530.png)
![screenshot_2017-03-08-02-46-28-641_org mozilla firefox](https://cloud.githubusercontent.com/assets/15236297/23706372/1ec1edee-0438-11e7-8c34-dcd67c15c60b.png)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by kumar303** [comment]
Hi, thanks for the bug report. This looks like a platform issue so there's not much we can do.
