### ISSUE TITLE
"Blocked add-on" message displayed when trying to install "Scroll to top Mobile" add-on

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2014]
Steps to reproduce:
1.On Android, open https://addons-dev.allizom.org/en-US/android/addon/scroll-to-top-mobile/
2.Try to install it by pressing the "Add to Firefox" button

Expected results:
Add-on is installed without issues

Actual results:
"Blocked add-on" message is displayed without visible reasons

Notes:
I was able to install same add-on on prod
Other add-ons can be installed without issues on -dev
No errors found in console
Not sure if this is a block release so please feel free to add the adequate label

Please see video for this issue:

![scrolltotop](https://cloud.githubusercontent.com/assets/1583842/23707943/dad6bb70-041c-11e7-8980-df0ad09b39d7.gif)

**Comment by kumar303** [comment]
Did you set up your device with the right certs for installing add-ons from dev? It could be a signing issue. Does the console (adb logcat) have any clues as to why Nightly is blocking it?

**Comment by muffinresearch** [comment]
@vcarciu any thoughts re ^

**Comment by vcarciu** [comment]
@kumar303 - Unfortunately , I don't have any other info than the ones described in bug description : 
Notes:
I was able to install same add-on on prod
Other add-ons can be installed without issues on -dev - so the settings are ok 
No errors found in console

**Comment by vcarciu** [comment]
@kumar303 I tried one more time after a system update in order to try to gather logs again and now issue is not reproducible anymore. It was a strange issue , but since it was reproducible only for this add-on and now I can't replicate, I think that we can close it .
Sorry for all the noise around this, but I was able to reproduce it 100% before.
