### ISSUE TITLE
Text entered in search box is not visible in French language

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2015]
Steps to reproduce:
1.On Android , open AMO-dev
2.Change the language to French
3.Enter some text in search box

Expected results:
Search text can be entered without issues

Actual results:
Text entered is not visible

NOTES:
Not reproducible for another languages, but we were not able to find another language where default text from search box is so long that it needs to be truncated 

Please see video for this issue : 
![notvisible](https://cloud.githubusercontent.com/assets/1583842/23708202/d5b685b6-041d-11e7-9112-03ebee4b69cb.gif)

**Comment by muffinresearch** [comment]
I see what's happening, the animation is a no-op due to the fact that the lable pushes the icon over so far. This means that the transitionEnd event never fires.

**Comment by vcarciu** [comment]
Verified as fixed : 
![francia](https://cloud.githubusercontent.com/assets/1583842/23746756/c3d57c5a-04c5-11e7-890a-71b245d6a91b.gif)
