### ISSUE TITLE
Use mozlog logging format to get access to server logs

### ISSUE THREAD

**Issue by jasonthomas** [mozilla/addons-frontend#2025]
https://wiki.mozilla.org/Firefox/Services/Logging contains a description about the mozlog format. Switching to mozlog will help get addons-frontend hooked up to Logging 2.0 https://mana.mozilla.org/wiki/display/SVCOPS/Logging+2.0

**Comment by kumar303** [comment]
Seems doable. We use [bunyan](https://github.com/trentm/node-bunyan) (which already supports JSON) so maybe we can hook it up to [mozlog](https://www.npmjs.com/package/mozlog).

**Comment by kumar303** [comment]
This is high-ish priority. I'm putting it in the London Work Week milestone but anyone should feel free to grab it before then.

**Comment by kumar303** [comment]
We need to do this if we want to see logs in the [new Kibana](https://amo-kibana.prod.mozaws.net/_plugin/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'amo*',interval:auto,query:(match_all:()),sort:!(Timestamp,desc))). The old one is still active but won't be around for much longer.

**Comment by willdurand** [comment]
I have a PR for switching to `pino` (#5826) and a [pino transport](https://github.com/pinojs/pino#transports) almost ready :)

Mozlog is a no-go however... It is a complete logger that leverages an older logger (`intel`) without a way to use their formatter...

**Comment by willdurand** [comment]
See: https://github.com/willdurand/pino-mozlog (WIP/quick & dirty)
