### ISSUE TITLE
Cannot register on Stage from Android

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2029]
Steps to reproduce:
1.On Android, go to AMO-Stage and try to register

Expected results:
After pressing confirmation link from confirmation email received, user is successfully logged to AMO-Stage

Actual results:
Server error page is displayed and user is not logged in

NOTES:
Same like https://github.com/mozilla/addons-frontend/issues/1660 , but on Stage

**Comment by muffinresearch** [comment]
Hmm this seems odd because the patch for that should have landed 

Here's the sentry report for it: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-stage/issues/385485/

**Comment by muffinresearch** [comment]
Ah ok - this sounds like it might be FXA config related. 

The patch I referred to above being landed was actually to force a 404 for `user/[USER]` whereas this path is `users/edit/`. 

Whilst config can probably prevent us hitting this URL, it would be good to add a route to force a 404 for this case so that we do still fall-back to the non-mobile site without blowing up.

**Comment by muffinresearch** [comment]
Fwiw: I've just tried the same thing on our prod instance and a 500 occurs there the same.

**Comment by kumar303** [comment]
The workaround in https://github.com/mozilla/addons-frontend/issues/2034 didn't work. Here's what happens: 
* `addons-frontend` starts by serving a `404` for `/users/edit/`
* This tells the proxy to let `addons-server` serve `/users/edit/`
* `addons-server` sees `/users/edit/` and redirects to `/users/edit`
* `addons-frontend` sees `/users/edit` and adds a slash to the end
* hilarity ensues

**Comment by kumar303** [comment]
The server change landed on stage and I was just about to sign in with a brand new account 🍨

**Comment by vcarciu** [comment]
Verified as fixed

**Comment by vcarciu** [comment]
Please see postfix video : 
![regstage](https://cloud.githubusercontent.com/assets/1583842/23792204/aabca6b6-058e-11e7-852b-00158b6bed31.gif)

**Comment by vcarciu** [comment]
Please see postfix video : 
![regstage](https://cloud.githubusercontent.com/assets/1583842/23799068/dae59390-05af-11e7-8925-203dd2215d0b.gif)
