### ISSUE TITLE
Themes "Tap To Preview" is too big for some languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2030]
Steps to reproduce:
1. Load theme details in AMO-stage i.e. https://addons.allizom.org/en-US/android/addon/dancing-daisies-by-madonna/
2. Change the language to `hsb` - https://addons.allizom.org/hsb/android/addon/dancing-daisies-by-madonna/
3. Observe the "Tap To Preview" button

Expected results:
There are no display or layout issues.

Actual results:
The button overlays aprox 70% of theme design.

Notes/Issues:
Verified on FF51(Android 6.0.1). Issue is reproducing on AMO-dev and stage.
Screenshot for this issue: 
![preview](https://cloud.githubusercontent.com/assets/15685960/23756736/451d0e96-04ed-11e7-8819-4c732cac2ac3.png)

**Comment by muffinresearch** [comment]
wont-fixing this on the basis that the preview is going away soon see https://github.com/mozilla/addons-frontend/issues/3056
