### ISSUE TITLE
"Submit review" button is smaller after clicking inside of review field

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2031]
Steps to reproduce:
1. Load details page for any add-on in AMO-stage on your device i.e. https://addons.allizom.org/en-US/android/addon/phony/
2. Type the rating stars to add a review for that add-on
3. Enter some text in the review field
4. Observe the "Submit review" button

Expected results:
Button, before and after typing a review, has same dimensions. 

Actual results:
"Submit review" button appears "cut" after entering some text in the review field.

Notes/Issues:
Verified on FF51(Android 6.0.1). Issue is reproducing on stage and dev.
Screenshots for this issue: 
![submitr](https://cloud.githubusercontent.com/assets/15685960/23757469/99a9aada-04ef-11e7-97cb-56e87f0def9f.png)

**Comment by muffinresearch** [comment]
Closing as modals are being replaced in https://github.com/orgs/mozilla/projects/29
