### ISSUE TITLE
"Report a bug" link is returning a 404 error page for some languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2032]
Steps to reproduce:
1. Load AMO-stage homepage on device i.e. https://addons.allizom.org/en-US/android/
2. Change the language to `tr` aka Türkçe - https://addons-dev.allizom.org/tr/firefox/
3. Tap "Report a bug" link from footer

Expected results:
The page https://developer.mozilla.org/th/Add-ons/AMO/Policy/Contact is loaded.

Actual results:
A 404 page is loaded.

Notes/ Issues:
Other languages: nn-NO, hsb, 
Verified on FF52(Android 6.0.1, Win 7). Issue is reproducing on AMO-stage and -dev.
Video for this issue:
![404](https://cloud.githubusercontent.com/assets/15685960/23759411/674430b4-04f5-11e7-8b5c-a834a6e9059b.gif)

**Comment by muffinresearch** [comment]
It's annoying that it works for some languages and not others. Sounds like this bug https://bugzilla.mozilla.org/show_bug.cgi?id=1283422 which I filed a while ago. 

The only viable solution is probably to forgo the localized link 🐼

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Android 6.0.1)
Postfix video:
![videotogif_2017 03 10_10 17 36](https://cloud.githubusercontent.com/assets/15685960/23787538/408b5660-057b-11e7-9b56-6942d125817a.gif)
