### ISSUE TITLE
Deleted add-ons are showing up in search results then causing a 404

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2035]
### Describe the problem and steps to reproduce it:

- Submit and approve an Android add-on so that it's public
- Delete it (example of a deleted add-on: https://github.com/mozilla/addons-frontend/issues/2021)
- Search for it on the AMO mobile site
- Click on the detail page
- Refresh the page so that the server tries to load it

### What happened?

You get a 404

### What did you expect to happen?

The deleted add-on shouldn't have shown up in the search results at all.

### Anything else we should know?

This looks like an API bug: https://github.com/mozilla/addons-server/issues/4894

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-frontend/issues/2021

**Comment by muffinresearch** [comment]
Closing in favour of mozilla/addons-server#4894
