### ISSUE TITLE
API 404s are reported to Sentry as errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2036]
### Describe the problem and steps to reproduce it:

* Set up your local config with a Sentry DSN for https://sentry.prod.mozaws.net/operations/addons-frontend-test/
* Go to a URL for an add-on that you know will be a 404

### What happened?

It reports an error to Sentry like https://sentry.prod.mozaws.net/operations/addons-frontend-test/issues/385551/

````
{
  response: {
    apiURL: http://localhost:3000/api/v3/addons/addon/tasty-pie-nope/?lang=en-US, 
    data: {}, 
    status: 404
  }
}
````

### What did you expect to happen?

It should not report to Sentry

**Comment by kumar303** [comment]
Looks like the [Sentry (Raven) error handler](https://github.com/mozilla/addons-frontend/blob/master/src/core/server/base.js#L315) is processing the error before it reaches showErrorPage(). Hmmm.

**Comment by willdurand** [comment]
@kumar303 I cannot reproduce it anymore. 404 pages are not reported.
