### ISSUE TITLE
Redirect loop on /users/edit[/]

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2037]
### Describe the problem and steps to reproduce it:
From https://github.com/mozilla/addons-frontend/issues/2029#issuecomment-285452339

Whilst the fxa config has been updated to fix the redirection post-registration the redirect loop still exists.
 
- Login and click my profile.
- And then edit profile.
- Then click "view mobile site" in the footer.
- addons-frontend starts by serving a 404 for /users/edit/
- This tells the proxy to let addons-server serve /users/edit/
- addons-server sees /users/edit/ and redirects to /users/edit
- addons-frontend sees /users/edit and adds a slash to the end
- hilarity ensues

### What happened?

A redirect loop

### What did you expect to happen?

Fallback to /users/edit (we could also not show the "View mobile site" link on this page)
Longer term this will be fixed by added pages for these views in the new mobile site.

**Comment by muffinresearch** [comment]
One way to prevent this behaviour would be to have exclusions for adding slashes.

**Comment by muffinresearch** [comment]
> One way to prevent this behaviour would be to have exclusions for adding slashes.

Or another way would be to add a slash on the amo-server side. Might mean we'd need to change the redirect endpoint for server logins to avoid an unnecessary 301.

**Comment by kumar303** [comment]
We could also put some middleware right at the front of the chain that responds with 404s to known addons-server URLs. However, this could be a little confusing and won't work for when someone is loading pages on the client.

**Comment by tofumatt** [comment]
QA: we'd love to cherry-pick this patch into this week's tag, so if you could test this and the URLs it should cover (`/users/edit`, etc.) on `-dev` and confirm it's working that would be great. ❤️

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF52(Win 7) while following the first 3 steps (Login and click my profile->click edit profile->click "view mobile site" in the footer) and obtained the following results:

 - default scenario will reload "https://addons-dev.allizom.org/en-US/firefox/users/edit#" page on desktop
![1scenario](https://cloud.githubusercontent.com/assets/15685960/23991548/6542b11c-0a42-11e7-9a81-1db1b19e74c1.gif)


 - +Clicking on "Other Applications" like Thunderbird and Seamonkey or My Collections-> addons-frontend starts by serving a 404 page and a Server Error page 
![2-scenario](https://cloud.githubusercontent.com/assets/15685960/23991713/efb4bd04-0a42-11e7-9ffe-1588f0d0391a.gif)


- +Clicking on "Manage User" from My Profile, "My Themes", "Delete current photo" from Account Settings -> loads a "The page isn’t redirecting properly" page.
![3-scenario](https://cloud.githubusercontent.com/assets/15685960/23991839/65037b0e-0a43-11e7-94d9-95653f3544d1.gif)


- +Clicking on "Edit review" link for any comment listed in My Profile page will not work and display an error in the console.
![2017-03-16_1154](https://cloud.githubusercontent.com/assets/15685960/23991473/2e39d06a-0a42-11e7-91fb-9ecd58c27f10.png)

Not sure if these scenarios should be taken into consideration.

**Comment by muffinresearch** [comment]
I think there's more scenarios here that aren't working well with the fallback mechanism which are going to cause requests to be sent to the wrong place.

E.g:

If we fallback to the addons-server site and then that page does XHR it will get routed to mobile pages.

**Comment by muffinresearch** [comment]
I'm talking to ops about making a change around the fallback to iron out these problems by using an explicit set of routes that we know the mobile app should respond to.

**Comment by tofumatt** [comment]
Our routes are much smaller and easier to grok as well. That seems like a better plan 👍

**Comment by ValentinaPC** [comment]
All above scenarios are no longer reproducing.
Verified this as fixed on AMO-dev FF52(Win 7).
Video for this issue: 
![redirect](https://cloud.githubusercontent.com/assets/15685960/24142195/88ed36c4-0e2e-11e7-8a22-992b8ec8c57e.gif)

Thunderbird and SeaMonkey will load an old mobile -dev page.
Please see video: 
![t-s](https://cloud.githubusercontent.com/assets/15685960/24142291/cafe0d18-0e2e-11e7-9731-3cef8830fc84.gif)

@tofumatt : I guess it is intended?
