### ISSUE TITLE
A redeclared constant should cause a test suite failure

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2045]
### Describe the problem and steps to reproduce it:

Create a new file in the test suite like `TestThing.js` that accidentally redeclares a constant:
````js
describe('thing', () => {
  it('does stuff', () => {
    const mochReportsFailures = 'yep';
    const mochReportsFailures = 'nope';
    assert.equal(mochReportsFailures, 'yep');
  });
});
````

### What happened?

The tests all pass!

### What did you expect to happen?

The test should fail with some kind of message, I don't even care what that message is

### Anything else we should know?

If you delete the redeclaration you will see a test failure:
````js
describe('thing', () => {
  it('does stuff', () => {
    const mochReportsFailures = 'nope';
    assert.equal(mochReportsFailures, 'yep');
  });
});
````
This is is really hard to track down in the real world. My face hurts from getting punched.

**Comment by kumar303** [comment]
maybe it's a dupe of https://github.com/mozilla/addons-frontend/issues/1700

**Comment by muffinresearch** [comment]
<img width="953" alt="sh" src="https://cloud.githubusercontent.com/assets/1514/26735636/a8641336-47ba-11e7-9bbb-d71c48ec0bf4.png">

Also fixed in Jest
