### ISSUE TITLE
"Add to Firefox" install button goes crazy for other languages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2047]
Steps to reproduce:
1. Load details page for an add-on on your Android device i.e. https://addons-dev.allizom.org/en-US/android/addon/styler123/
2. Change the language to `de` - https://addons-dev.allizom.org/de/android/addon/styler123/?src=ss

Expected results
There are no display or layout issues.

Actual results:
The "Add to Firefox" button has layout issues.

Notes/Issues:
- other example: https://addons-dev.allizom.org/hsb/android/addon/styler123/
Verified on FF52(Android 6.0.1). Issue is ONLY reproducing on AMO-dev.
Screenshot for this issue:
![mobile-de](https://cloud.githubusercontent.com/assets/15685960/23866157/a25e84a0-0820-11e7-8bf9-51cf21fbc921.png)

**Comment by muffinresearch** [comment]
This is only seen when falling back due to mozAddonManager not being available.

Should still fix this in any case.

**Comment by tsl143** [comment]
@ValentinaPC, With the design change is this still valid?
![photo6258143740187223987](https://user-images.githubusercontent.com/5318732/27822971-206400b2-60c5-11e7-9300-9c3e0aac34f1.jpg)

**Comment by tofumatt** [comment]
It might b pie worth testing with a very long install button text but I think this can be closed.
