### ISSUE TITLE
Compatibility message is cramped

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2048]
### Describe the problem and steps to reproduce it:

Go to https://addons-dev.allizom.org/en-US/firefox/addon/testing-amotuff1234/

![screen shot 2017-03-13 at 17 45 10](https://cloud.githubusercontent.com/assets/1514/23867771/e85153e0-0814-11e7-9b61-40b0a1f8945a.png)

**Comment by ValentinaPC** [comment]
@muffinresearch : this was fixed only for FF? because red banner looks cramped on non-Firefox browsers.
Please see screenshot from Chrome: 
![c](https://cloud.githubusercontent.com/assets/15685960/23955343/4f3701de-09a2-11e7-939b-c8ffd565f0c6.png)

**Comment by tofumatt** [comment]
Shoot, I only tested in Firefox. It’s only on -dev though, IIRC.

**Comment by ValentinaPC** [comment]
> Shoot, I only tested in Firefox. It’s only on -dev though, IIRC.

In Firefox, AMO-dev, everything looks fine.

**Comment by tofumatt** [comment]
Does -dev look okay in Chrome or is the issue there as well?

**Comment by ValentinaPC** [comment]
> Does -dev look okay in Chrome or is the issue there as well?

When I've checked Chrome, I've used dev. Above screenshots are from -dev,

**Comment by tofumatt** [comment]
Cool, thanks. I’ll need to patch this again, then.

**Comment by tofumatt** [comment]
@ValentinaPC could you try shift-refreshing the page or send me a link to the page that's still cramped in Chrome? Just tested it locally and see:

<img width="392" alt="screenshot 2017-03-15 17 25 03" src="https://cloud.githubusercontent.com/assets/90871/23961947/72b4d044-09a4-11e7-823e-3319fbc28b71.png">
<img width="347" alt="screenshot 2017-03-15 17 27 13" src="https://cloud.githubusercontent.com/assets/90871/23962009/a6f8c25c-09a4-11e7-8fb3-676d864c9a05.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on Chrome 56.0.2924.87 (Android 6.0.1)
Postfix screenshots:
![untitled](https://cloud.githubusercontent.com/assets/15685960/23985416/a6e6f828-0a27-11e7-8251-234a905cbffc.png)
