### ISSUE TITLE
Post-install notification popup is superfluous

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2049]
### Describe the problem and steps to reproduce it:

Need to check this on release once in prod, but in FF Android nightly it looks like the post-install notification is superfluous since there's a notification that pops-up from the bottom of the screen which is shortly followed by a notification at the top of the screen.

Assuming this is also the case in release let's conditionally remove the post-install notification for FF Android.

![img_1082](https://cloud.githubusercontent.com/assets/1514/23869017/7b330b5a-0819-11e7-8925-d079726d7da1.jpg)

**Comment by pwalm** [comment]
We just spoke with Jack in Taipei about this, he has experienced the same issue. Let's kill the top  notification.

**Comment by ValentinaPC** [comment]
I receive now, two notifications on AMO-prod FF53(Android 6.0.1) for require restart add-ons at install and no notification at uninstall.
Please see screenshot and video:
![restart](https://cloud.githubusercontent.com/assets/15685960/25992082/2d2574ba-370e-11e7-9031-b636997e847f.png)
![videotogif_2017 05 12_12 28 45](https://cloud.githubusercontent.com/assets/15685960/25992536/7cc4784e-370f-11e7-85fd-9ee36c9c1399.gif)

@muffinresearch : should I log a separate issue for the uninstall part?

**Comment by muffinresearch** [comment]
@ValentinaPC since we're moving in the direction of the browser controlling notifications this would need a bug filing on bugzilla.

**Comment by ValentinaPC** [comment]
Done: https://bugzilla.mozilla.org/show_bug.cgi?id=1364405
Thanks!

**Comment by muffinresearch** [comment]
I think this is no longer an issue.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF58 (Android 8.0.0)
