### ISSUE TITLE
Open search plugins cannot be installed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2050]
### Describe the problem and steps to reproduce it:

Relates to this old addons-server issue: https://github.com/mozilla/addons-server/issues/3581

There's no functionality to enable installation of a opensearch add-on in the new mobile pages. 

I'm not sure quite how searches are showing up in the new mobile pages I would have thought the search should just be returning themes and add-ons but they are there if you look for them.

### What happened?

Find an opensearch add-on and try and install it. E.g:  https://addons.mozilla.org/en-US/android/addon/google-dictionary-53151/?src=search

If the fallback button is shown it links to XML as per https://github.com/mozilla/addons-server/issues/3581 -if the addon switch install button is shown it will look like it's installing and then fail.

### What did you expect to happen?

It should install as normal.

The installation needs to be special-cased to work for opensearch in a similar way to the way it works for lightweight themes as mozAddonManager doesn't handle search installs.

**Comment by ValentinaPC** [comment]
Verified this in AMO-dev FF53(Android 6.0.1) and search tools are successfully installed.

@muffinresearch, @tofumatt : did we intend to show "Add to firefox" button for search tools and not the switch button? Because this is the format now and looks pretty bad for other languages. 

Please see screenshot:
![2017-04-24_1231](https://cloud.githubusercontent.com/assets/15685960/25331010/4047f82e-28ea-11e7-8909-2e13e6c6cd69.png)

**Comment by tofumatt** [comment]
Yes, that button looking bad is a separate issue we should file but using the switch for that add-on was odd as there's still a prompt and no confirmation of install.

**Comment by ValentinaPC** [comment]
There is a bug logged for that button while using other languages, under addons-frontend - https://github.com/mozilla/addons-frontend/issues/2047

**Comment by muffinresearch** [comment]
> Yes, that button looking bad is a separate issue we should file but using the switch for that add-on was odd as there's still a prompt and no confirmation of install.

Is it also the case that we can't introspect an opensearch installation too? Would it be possible tof file some Firefox bugs to add opensearch abilities to mozAddonManager - that way we can at least look to address this in the future.

We should also look to limit opensearch appearing in search results unless they've been asked for explicitly, assuming that's not already happening.

**Comment by tofumatt** [comment]
I think we could check for them in mozAddonManager, I didn't do that for now because it was a lot more effort for that fix and wanted to get this out first. But yeah, I'll see about checking with mozAddonManager and using a switch for later.

Matthew Riley MacPherson (sent from mobile)

**Comment by muffinresearch** [comment]
If mozAddonManager can detect install state then this should use the switch even if there's no events to determine success. Success could be assumed (iirc themes work this way).

**Comment by ValentinaPC** [comment]
Search engine can be installed on AMO-dev using FF53(Android 6.0.1).
I've logged an issue that maybe is related to this: #2412 .
We can mark this verified-fixed.
