### ISSUE TITLE
Incorrect client side links do not show a 404 page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2051]
### Describe the problem and steps to reproduce it:

Create a component with a 404 link like:
````js
import { Link } from 'react-router';
...
class Component extends React.Component {
  render() {
    return <Link to={{ pathname: '/definitely-a-404 '}}>some link</Link>;
  }
}
````

### What happened?

When you click on the link, the URL changes but nothing renders (the page doesn't change)

### What did you expect to happen?

It should render a 404 page.

### Anything else we should know?

If you refresh the page on the new URL it will render a 404.

**Comment by tofumatt** [comment]
Shoot, that's new. It definitely used to work :'(

Matthew Riley MacPherson (sent from mobile)

**Comment by kumar303** [comment]
I wonder if this is because I wasn't using an AMO Link. It's likely! Maybe https://github.com/mozilla/addons-frontend/issues/2053 will fix it.

**Comment by muffinresearch** [comment]
Closing in favour of #2053
