### ISSUE TITLE
Fix tests in the Paginate component

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2054]
There are multiple tests for the Paginate comment that are failing silently due to not returning the promises. It also needs a bit of cleanup.

**Comment by muffinresearch** [comment]
I wonder if something like the `catch-or-return` rule here [1] would have caught this or at least some of it?

[1] https://github.com/xjamundx/eslint-plugin-promise#promise-rules

**Comment by kumar303** [comment]
> I wonder if something like the catch-or-return rule here [1] would have caught this or at least some of it?

Good idea! Filed https://github.com/mozilla/addons-frontend/issues/2065
