### ISSUE TITLE
Some strings will not be translated due to the use of oneLine

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2059]
We have a babel transform `dedent` which needs to be used for template strings wrapped in gettext calls.

The reason for this is that dedent is a babel transform that happens before the extraction process. Since the point that a different indent removal lib was introduced (`oneLine`) anything that's a translated template string that doesn't use dedent is not extracted.

See https://github.com/mozilla/addons-frontend/search?utf8=%E2%9C%93&q=i18n.gettext%28oneLine

**Comment by muffinresearch** [comment]
Having converted all that list to use dedent there's still a problem with extraction on lines like these:  https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonCompatibilityError/index.js#L67

**Comment by tofumatt** [comment]
Is there a way we can use the same type of setup for oneLine? I like that it doesn’t add weird newlines making it easier to test string contents, and also just doesn’t output erroneously `\n`.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
