### ISSUE TITLE
Make search result pagination match the UI mock

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2064]
### Describe the problem and steps to reproduce it:

Perform a search that results in many pages. Scroll down to the previous/next buttons. Example: https://addons-dev.allizom.org/en-US/android/search/?page=1&q=food

### What happened?

The buttons don't match the UI mock. They are are not centered or at least they are missing some margins.

### What did you expect to happen?

They should match the UI mocks closer.

<img width="363" alt="screenshot 2017-03-14 12 55 30" src="https://cloud.githubusercontent.com/assets/55398/23915043/e2d3e01c-08b5-11e7-9300-311803ab6e15.png">

### Anything else we should know?

This is not fallout from https://github.com/mozilla/addons-frontend/issues/2054 :) I checked before and after. The layout was the same.

**Comment by tofumatt** [comment]
The mocks look like this:

<img width="267" alt="screenshot 2017-03-14 20 01 42" src="https://cloud.githubusercontent.com/assets/90871/23920071/2e0e66b6-08f1-11e7-848e-d205e379f939.png">

**Comment by aayushsanghavi** [comment]
@tofumatt I'd like to work on this issue

**Comment by tofumatt** [comment]
Sure thing, let me know once you have a PR ready.

**Comment by aayushsanghavi** [comment]
@tofumatt its up

**Comment by vcarciu** [comment]
@tofumatt : You can observe that the first letters from "Previous" and "Next" buttons are a bit bigger that the rest of the text . Not sure if this is enough to reopen this issue(it looks ok from my point of view), but please add your input here : 
![prevnext](https://cloud.githubusercontent.com/assets/1583842/25008129/6dbcbb64-206b-11e7-8275-cc4558f437a1.png)

**Comment by tofumatt** [comment]
That is as the mocks intended, all good! 👍🏻

**Comment by vcarciu** [comment]
Thanks. Verified as fixed
