### ISSUE TITLE
Add ES lint rule to catch broken promises in the test suite

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2065]
### Describe the problem and steps to reproduce it:

Create a test with a promise but forget to return the promise or call `done()`.

### What happened?

It could fail silently. See https://github.com/mozilla/addons-frontend/issues/2054

### What did you expect to happen?

An ES lint rule should yell at you!

### Anything else we should know?

Something in here should do it: https://github.com/xjamundx/eslint-plugin-promise#promise-rules

If adding is too intrusive, let's at least add it just to `tests/.eslintrc`.

**Comment by tofumatt** [comment]
Even just in the test suite we have dozens of un-returned promises. It's about as much work to convert everything over, though it will result in a fair bit of slightly odd `return true` or `return null` statements that seem odd.

Still, I think it's a solid set of rules to use around Promises and it's worth doing.
