### ISSUE TITLE
No-op gettext/ngettext is being used and will result in untranslated strings.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2071]
Before localization there was a no-op gettext and ngettext in core/utils. The problem is that this is being used in some places instead of `i18n.ngettext` this will result in untranslated strings.

E.g: https://github.com/mozilla/addons-frontend/blob/c884314b9827bcbb420a1a9547f1bf73d22c90d3/src/amo/components/AddonDetail.js#L131

**Comment by kumar303** [comment]
Let's do this after https://github.com/mozilla/addons-frontend/issues/2373
