### ISSUE TITLE
Large number of non-functional pages for highly rated/popular themes

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2072]
Steps to reproduce:
1. Load AMO-stage page on device https://addons.allizom.org/en-US/android/
2. Tap "Themes" button
3. Tap "More Highly Rated Themes" option - https://addons.allizom.org/en-US/android/search/?sort=rating&type=persona

Expected results:
Highly rated themes are listed and distributed in a bunch of pages. User can navigate without any issues.

Actual results:
Themes are displayed in over 15000 pages. Navigating to page i.e 2000 will display "No results found".

Notes/Issues:
- navigating to a future page (i.e. 2000) was made by modifying the URL.
- "More Popular Themes" has the same large number of pages
Verified on FF52(Android 6.0.1). Issue is reproducing all around AMO-servers.
Video for this issue: 
![manypg](https://cloud.githubusercontent.com/assets/15685960/23951518/f219d96e-0996-11e7-8fb9-f2bb332e693c.gif)

**Comment by muffinresearch** [comment]
Looking at the response shows the count is providing the right number of pages but the api is clearly giving us the wrong count if pages within that number are not obtainable.

**Comment by Ryuno-Ki** [comment]
IIRC there was an issue with the count per page number not matching the items in the response. I couldn't find it :-(

**Comment by tofumatt** [comment]
That issue was on dev and stage only and might have been fixed. The issue was actually with addons-server elastic search/API sending the wrong data. I think it's since been fixed, but I forget. @diox would know.

**Comment by diox** [comment]
We've added a hard limit in the search API to prevent elasticsearch from blowing up in https://github.com/mozilla/addons-server/issues/4702 ; that limit is 25000 *items*, so with 25 items per page 1001 is the biggest you can reach (try it - page 1001 works, page 1002 is a 404). We could push it higher, but at a cost - we figured it wasn't worth it.

When setting that limit I didn't bother correcting the count, so you can see a higher count than the page you can actually reach. We have 2 options here:
- We can have the API never return a count higher than 25000
- We can have addons-frontend notice a count is higher than 25000 and display something like "a lot of items" or some vague wording that hides the actual number when it's super high.

**Comment by ValentinaPC** [comment]
This is also happening for an empty search in themes homepage.

**Comment by ValentinaPC** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/3887
