### ISSUE TITLE
Theme with no author causing layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2073]
Steps to reproduce:
1. Search the theme "Eyes in the clouds" while in AMO-stage using your device - https://addons.allizom.org/en-US/android/search/?q=eyes+in+the+coulds

Expected results:
There are no displayed or layout issues.

Actual results:
Theme has no author. 

Notes/Issues:
- having no author causes layout issues in listing pages for that theme.
Verified on FF52(Android 6.0.1). Issue is reproducing all around AMO servers.
Screenshot for this issue:
![2017-03-15_1602](https://cloud.githubusercontent.com/assets/15685960/23952043/c991ef0c-0998-11e7-935f-3dadb70e2ea1.png)

**Comment by tofumatt** [comment]
Why are there themes with no authors? That seems quite weird.

Is it because the author ticks an anonymous box or something?

**Comment by ValentinaPC** [comment]
> Is it because the author ticks an anonymous box or something?

In desktop view, the exact theme has an author, but while changing to mobile view....is mysteriously ...gone.
See: https://addons.allizom.org/en-US/android/addon/eyes-in-the-clouds/ on desktop.

**Comment by muffinresearch** [comment]
For this theme the authors array is empty 

```
"authors":[]
```

This includes production https://addons.mozilla.org/api/v3/addons/addon/eyes-in-the-clouds/

For addons frontend we should ensure the layout doesn't break when this is the case and we also need an issue for addon-server to see why this add-on has no author. I'll file that now...

**Comment by muffinresearch** [comment]
@tsl143 is working on this and I'm mentoring.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev and stage using FF53(Android 7.1.2)
I saw in the pull request that "After" screenshot does not list the author... looking for the same theme in AMO-dev - the author is displayed...
![2017-06-06_1547](https://cloud.githubusercontent.com/assets/15685960/26829792/7bd30dc8-4acf-11e7-9d73-9d1df320eab9.png)
I was not able to find another theme.
In AMO-stage - the issue is not fixed. 
![stage](https://cloud.githubusercontent.com/assets/15685960/26829871/ae1e0512-4acf-11e7-91b3-b94f47526dca.png)

So...I am bit confused of what is happening...

**Comment by tsl143** [comment]
@ValentinaPC Sorry, I was on vacation I wasn't able to reply.

I think it may be code push delay or something, I see the issue fixed on https://addons.allizom.org.
![photo6204049404483184574](https://user-images.githubusercontent.com/5318732/27208858-fab6b78c-5265-11e7-890f-a0abaef4c9b1.jpg)

**Comment by ValentinaPC** [comment]
@tsl143 : not a problem. :)

Verified as fixed on AMO-dev FF53(Win 7, Android 7.1.2)
Postfix screenshots:
![desktop](https://user-images.githubusercontent.com/15685960/27217939-a8f79c26-5284-11e7-929b-aa056f7d4102.png)
![mobile](https://user-images.githubusercontent.com/15685960/27217964-c4a84024-5284-11e7-9244-411cf0d68b78.png)
