### ISSUE TITLE
Theme preview does not work on Android

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#2075]
### Describe the problem and steps to reproduce it:
Go to addons.mozilla.org using Firefox on your Android device. I have a Nexus 5x running Android version 7.1.1

### What happened?
Tap on a theme, then tap on Tap to Preview.

### What did you expect to happen?
I expected to see the theme appear on my tab. But it didn't appear. It only appears when I install.

### Anything else we should know?
![2017-03-15 17 29 45](https://cloud.githubusercontent.com/assets/2701092/23965979/fe20332c-0976-11e7-8f5c-ea8043661486.png)

**Comment by muffinresearch** [comment]
@atsay which firefox version are you running? I don't seen any issues on FF android release.

Can you check you don't have any testing flags set. From checking nightly it looked like it didn't work when extensions.webapi.testing is true when looking at production.

**Comment by atsay** [comment]
I'm running 52.0! Sorry, tried to include this info yesterday but "About Firefox" was grayed out for some reason and I couldn't access it.

Also, just now I tried to uninstall the theme and preview again to try it out, but the Disable and Uninstall buttons didn't do anything when I tapped them. Also note the [strange gradient](https://www.dropbox.com/s/m2usy0ynupe8gl1/Screenshot_20170316-124429.png?dl=0) in the tab. Restarting the browser solved the problem. The Preview problem as described in this bug persisted.

**Comment by muffinresearch** [comment]
@atsay did you check if you had testing flags set?

**Comment by atsay** [comment]
I just checked--no extensions.webapi.testing in my about:config

**Comment by muffinresearch** [comment]
Theme previews are going away see https://github.com/mozilla/addons-frontend/issues/3056
