### ISSUE TITLE
devloper extension not added,what I will do?

### ISSUE THREAD

**Issue by 0x5B82** [mozilla/addons-frontend#2076]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by 0x5B82** [comment]
Devloper not added what I will do

**Comment by jvillalobos** [comment]
Please explain your problem in detail. Your comment isn't enough to understand what's wrong.

**Comment by muffinresearch** [comment]
Please re-open if you have further information to add.
