### ISSUE TITLE
Updates on "Display Name" cannot be seen on mobile device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2079]
Steps to reproduce:
1. Load Edit Profile page in AMO-stage https://addons.allizom.org/en-US/firefox/users/edit
2. Change your "Display Name"
3. Navigate to listing pages **_on device_** and see display name of an add-on/theme you created

Expected results:
Display name is updated.

Actual results:
Display name is not updated.

Notes/Issues:
- adding a review on device will be listed under the updated display name
- desktop site in Firefox for Android pages will list the updated display name
- View Mobile Site on desktop will list the old display name while navigating through listing pages, but going from an android add-on details page in desktop view to android add-on details page in mobile view will list the changed display name.

Verified on FF52(Win 7, Android 6.0.1). Issue is reproducing on AMO-stage and AMO-dev.
Video for this issue:
![videotogif_2017 03 16_14 43 39](https://cloud.githubusercontent.com/assets/15685960/23997387/d7f4b04a-0a59-11e7-92aa-01d4a106912f.gif)

**Comment by muffinresearch** [comment]
Closing this in favour of https://github.com/mozilla/addons-server/issues/6964 since this is an API issue that needs to be fixed there.
