### ISSUE TITLE
Explicit nginx routes for amo mobile pages 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2082]
Relates to https://github.com/mozilla/addons-frontend/issues/2037

Currently we are routing traffic to the mobile pages based on:

* Presence of mamo cookie with value "on"
* OR, a mobile UA string

In addition to this we have a fallback which will fallback based on the mobile pages providing a 404. The fallback mostly works but there are a few cases which are causing problems:

* Any time the addons-server app issues a redirect it will be subject to being routed to the mobile pages again. 
* If the mobile page urls do not match the addons-server server urls there can be a game of redirect tennis which results in an infinite redir loop.
* If when on a  fallback page the client issues an XHR that might be routed incorrectly.

To fix this we could set up an explicit list of routes that the mobile pages responds to as this will be less prone to problems - the only downside will be one of maintenance. I'll add comments to the routes to make it clear that ops need to be told when new routes are added.

Based on https://github.com/mozilla/addons-frontend/blob/e356c928debbb226b57540b28e8a9b3d49cbaa91/src/amo/routes.js#L27

Here's the list of routes:

**All** routes are optionally prefixed with `/%locale%/(android|firefox)` though we also fill in both the locale and or the app if one does not exist.

```
/
/addon/%slug%/
/addon/%slug%/reviews/
/(dictionary|extensions|language|search|themes)/categories/
/(dictionary|extensions|language|search|themes)/featured/
/(dictionary|extensions|language|search|themes)/%slug%/
/search/
/simulate-async-error/
/simulate-sync-error/
/simulate-client-error/
/(dictionary|extensions|language|search|themes)/
```

**Comment by muffinresearch** [comment]
@bqbn If it's possible to set this up we can verify it on -dev and stage and once verified get this out into the production as soon as possible.

**Comment by muffinresearch** [comment]
@bqbn I just made a change because I just noticed this line: https://github.com/mozilla/addons-frontend/blob/master/src/core/constants.js#L65

```
persona -> themes
extension -> extensions
```

**Comment by bqbn** [comment]
I've pushed some nginx changes to -dev for this. Please test and let us know how things are looking.

**Comment by muffinresearch** [comment]
@bqbn thanks will check it out.

**Comment by ValentinaPC** [comment]
@muffinresearch : I've checked all the routes that I've mentioned in #2037 using AMO-dev FF52(Win7) - clean profile - and did not see any changes.
As far as read above, some changes should be o -dev, yes?

**Comment by bqbn** [comment]
FWIW, ```/users/edit/``` (which is https://github.com/mozilla/addons-frontend/issues/2037 about) isn't mentioned in the above list of routes thus it's not included in the nginx changes (I can add it if needed be).

**Comment by muffinresearch** [comment]
@bqbn /users/edit/ is a addon-server route only so there should be no need to have config to send it to the mobile pages.

**Comment by bqbn** [comment]
@muffinreseach, so to clarify, is this ticket to not do 404 fallback for the listed routes on mobile site?

**Comment by muffinresearch** [comment]
@bqbn correct, it's to send traffic to only those routes assuming a mamo cookie is set to "on" or the UA is a mobile UA.

**Comment by bqbn** [comment]
After talking to @muffinresearch, I've updated our nginx configs and pushed them to -dev.

Please test it again.

**Comment by muffinresearch** [comment]
The nginx config is broken currently and will be reverted see also https://github.com/mozilla/addons-server/issues/4978

Once this is fixed this can be re-tested.

**Comment by bqbn** [comment]
The issue was because nginx didn't try the main site when UA is not mobile, and no mamo cookie. I've fixed it and pushed it to -dev again. Can we re-test it?

**Comment by ValentinaPC** [comment]
I've verified all routes I've mentioned in #2037 using AMO-dev FF52(Win 7) and all seem to redirect correctly (updated the issue).
Please let me know if anything else should be checked here.

**Comment by bqbn** [comment]
@muffinresearch I took the liberty and just pushed the nginx changes to -stage for this.

Can you let me know what is your plan to release this to -prod?

**Comment by muffinresearch** [comment]
@bqbn, brilliant thanks - I meant to asked you to do this when tagging yesterday. Assuming no issues are found we should push this on Thursday. Thanks again!

**Comment by muffinresearch** [comment]
Closing this since it's ready.

**Comment by ValentinaPC** [comment]
Verified as fixed on -stage and -dev using FF52(Win 7) for the routes I've mentioned in the other issue.

@muffinresearch : Not sure **how** to check, for example "/simulate-async-error/" or "/simulate-sync-error/", or if I **can** check this routes?
