### ISSUE TITLE
Invalid category slugs should result in a 404 rather than no results.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2084]
If a CategoryPage slug passed is invalid it should be a 404 rather than just show no results. 

See https://addons-dev.allizom.org/en-US/firefox/extensions/whatever/

Presumably to do this we'd need to fetch a list of cats for the clientApp dynamically. 

We should do this differently per-client application in any case since currently we don't change the list of categories based on app.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Invalid categories slug return a "404" page, instead of a "no results" one.
Postfix screenshot:
![404](https://user-images.githubusercontent.com/15685960/28318934-1f9500d0-6bd5-11e7-8e80-5b23e4d6058d.png)
