### ISSUE TITLE
Clean-up forced 404 routes once new nginx config is released

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2088]
Once the nginx configs from https://github.com/mozilla/addons-frontend/issues/2082 are rolled out to stage and prod it would be good to remove the forced 404 routes that should no longer be needed.

See https://github.com/mozilla/addons-frontend/blob/c8e567e7b6b7098368123d12fa698855c8e00d44/src/amo/routes.js#L32

**Comment by kumar303** [comment]
This will be a little confusing (for local development only) since we won't see 404s anymore. I think we can get back to 404s after https://github.com/mozilla/addons-frontend/issues/2346
