### ISSUE TITLE
"Add to Firefox" button replaced with a toggle switch

### ISSUE THREAD

**Issue by SubhrajyotiSen** [mozilla/addons-frontend#2091]
### Steps to reproduce it:

1. Go to the details page of any add-on
2. Scroll to the section which shows the rating and number of users

### What happened?
There is no "Add to Firefox" button. There is only a toggle switch

### What did you expect to happen?
An "Add to Firefox" button should be displayed next to the rating.
### Anything else we should know?
<img src="https://image.ibb.co/dpPGaa/firefox.jpg" width=225 height=400>

**Comment by tofumatt** [comment]
That toggle switch is the new install button; clicking it will install the add-on to Firefox automatically.

@pwalm Perhaps we need some clearer labelling or UX on this if more users find this confusing. Not sure what you think. Looking at it now I can see it being a bit unintuitive on the site versus the disco pane.
