### ISSUE TITLE
Remove babel-plugin-dedent

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2092]
Since we don't need the pre-processing powers of babel-plugin-dedent for extraction anymore we can stop using entirely by replacing it with oneLine and removing it from deps and config.

To complete this issue:
1. [Find](https://github.com/mozilla/addons-frontend/search?utf8=%E2%9C%93&q=dedent&type=) all instances of `dedent`
2. Replace them with a call to `oneLine` [like these](https://github.com/mozilla/addons-frontend/search?utf8=%E2%9C%93&q=oneLine&type=) instead
3. Remove `babel-plugin-dedent` from the `plugins` array in `.babelrc`

**Comment by kumar303** [comment]
We added some dedent support for Flow in https://github.com/mozilla/addons-frontend/pull/2196 which can be removed once dedent is no longer used.

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @wagnerand

**Comment by ValentinaPC** [comment]
@tofumatt : Is there a way that QA can check this? if yes, please add some STR.
Thanks!

**Comment by tofumatt** [comment]
Oops, sorry about that. No QA needed on this one, thanks!
