### ISSUE TITLE
Remove ":" listed after a beta version from Development Channel

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2093]
Steps to reproduce:
1.Open an addon with a beta version available (https://addons.allizom.org/en-US/firefox/addon/permissionsallheh/)
2.Expand the Development channel option
3.Observe the ":" punctuation mark after Beta version

Expected results:
No ":" punctuation mark should be displayed since there is no info after it

Actual results:
There is a ":" punctuation mark and it looks like we have something incomplete in this section

Please see screenshot for this issue : 
![punctuation](https://cloud.githubusercontent.com/assets/1583842/24052742/32dc84c0-0b3f-11e7-80b4-26a6911a59c9.png)

**Comment by muffinresearch** [comment]
@vcarciu that looks like the addons-server site, is this issue also present in the mobile pages? If not it might be better to move this issue to mozilla/addon-server.

**Comment by vcarciu** [comment]
Yes, this should be under addon-server. I will log another one.
Thank you
