### ISSUE TITLE
Create eslint plugin to prevent tagged template literals being used for localization

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2108]
The new set-up for multi-line strings for extraction and gettext calls requires template literal tags to be not tagged and leading whitespace in multiline template literals is implicitly removed.

Since a tagged template literal will not be extractable we could use a eslint plugin to flag a tagged template literal inside any gettext calls.

**Comment by willdurand** [comment]
So, I wrote a plugin for that last night.

**Comment by kumar303** [comment]
Really cool! This will be very helpful.
