### ISSUE TITLE
AMO prod is including docstring comments in JS bundle

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2113]
See the JS bundle file on https://addons.mozilla.org/en-GB/firefox/; we should remove the docstrings with uglify or whatever.

**Comment by eviljeff** [comment]
this should be just updating uglify configuration
@tofumatt to point to the right places.

**Comment by wagnerand** [comment]
@tofumatt thinks this might not be a good first bug.

**Comment by tofumatt** [comment]
I feel bad I was the one who added the maybe good first bug label in the first place. Oops!

**Comment by tofumatt** [comment]
QA: To verify this issue just make sure the production JS has no comments in it like:

```js
/**!
Cool library, etc. etc.
*/
```

**Comment by ValentinaPC** [comment]
This verification requires checking the web console for comments in the JS tab while navigating through AMO-prod?
Thanks!

**Comment by tofumatt** [comment]
It involves looking at the JS file/bundle in the <script> tag for amo and making sure it doesn't contain JS comments.

Matthew Riley MacPherson (sent from mobile)

**Comment by kumar303** [comment]
This doesn't need QA. It was just a change to how we build the JS file. Everything is looking good:
````
curl 'https://addons-amo-cdn.allizom.org/amo-i18n-en_GB-54804c1208249a8243fd.js' | less
````
