### ISSUE TITLE
[Dev Hub] Add ratings to listings in signed-in view

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2120]
Originally filed on addons-frontend by @atsay, but should be here.

See: https://github.com/mozilla/addons-frontend/issues/1717

**Comment by atsay** [comment]
There was already [UX](https://github.com/mozilla/addons-frontend/issues/1717#issuecomment-279295146) done on this...?

**Comment by tofumatt** [comment]
I meant to refile it in addons-server, but if it's done, I'll just close.

**Comment by atsay** [comment]
It's not done--I meant the UX is already done. But the feature has not been implemented, I don't think.

**Comment by tofumatt** [comment]
Ah, sorry, I meant to file this in addons-server though. I've moved it.
