### ISSUE TITLE
Support non-JWT authentication tokens for login/logout

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2123]
Steps to test this change:
* log in
* log out
* navigate the site and make sure you're still logged in

The session authentication token will no longer be a JWT as of https://github.com/mozilla/addons-server/issues/4907 so the frontend code needs to be adjusted accordingly.

**Comment by ValentinaPC** [comment]
> Steps to test this change:
> 
>     log in
>     log out
>     navigate the site and make sure you're still logged in

"make sure that we are still logged in", after log out?
Should we check this on mobile pages?
Thanks!

**Comment by tofumatt** [comment]
Yes, this change was for the mobile pages so it should be checked on them :-)

**Comment by ValentinaPC** [comment]
I like your sens of humor, but, sorry to insist, not sure I follow - what part of "log out and make sure you are still logged in" is normal? :)

**Comment by tofumatt** [comment]
Ahaha okay I see. Sorry!

Each of those steps are separate, not one after the other. So just make sure login works, logout works, and that after login you can navigate the site and stay logged in. Sorry! 😄

**Comment by kumar303** [comment]
Hah! My bad, I can see how that was really unclear now. I just updated the description.

**Comment by ValentinaPC** [comment]
It was fun, nevertheless. Thanks for clarification! Will check :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Android 6.0.1).
I've navigated through mobile pages, being logged in or out, or tried to make actions that require to be logged in, while logged out and everything behaves as expected.
Note: A video showing this would be too long.
