### ISSUE TITLE
(non-EN) locales may cause issues to "Last updated" date format from an add-on details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2127]
Steps to reproduce:
1. Load details page for an add-on on AMO-prod using your device i.e https://addons.mozilla.org/it/android/addon/cloud-viewer/?src=hp-dl-featured
2. Change the language to "Italiano"
3. Go to "More information" section and see the date from "Last updated"

Expected results:
There are no display or layout issues.

Actual results:
Date is replaced with "(timeFromNow)s".

Notes/Issues:
Verified on FF52(Android 6.0.1). Issue is reproducing all around AMO servers.
Screenshot for this issue:
![2017-03-22_1445](https://cloud.githubusercontent.com/assets/15685960/24198444/a18ca3c8-0f0e-11e7-892a-e0d849de8ad1.png)

**Comment by muffinresearch** [comment]
This is a broken placeholder in the translation.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Android 6.0.1)
Postfix screenshot:
![addon](https://cloud.githubusercontent.com/assets/15685960/24241026/281e529e-0fbc-11e7-9f5b-cf8eb0f4c47b.png)
