### ISSUE TITLE
Some locales are causing rating stars from "ratings and user count" section to be unaligned

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2128]
Steps to reproduce:
1. Load details page for any add-on in AMO-dev using your device i.e. https://addons-dev.allizom.org/en-US/firefox/addon/extended-statusbar/?src=hp-dl-featured
2. Change the language to French (https://addons-dev.allizom.org/fr/firefox/addon/extended-statusbar/?src=hp-dl-featured) and observe "rating and user count" section

Expected results:
Number of users, rating stars and number of reviews are aligned.

Actual results:
Rating stars are not aligned.

Notes/Issues:
- while checking through more languages, I can see that ratings stars are always centered after the length of the number of users.
Other examples:
- https://addons-dev.allizom.org/de/firefox/addon/extended-statusbar/?src=hp-dl-featured
- https://addons-dev.allizom.org/dsb/firefox/addon/extended-statusbar/?src=hp-dl-featured
- https://addons-dev.allizom.org/nl/firefox/addon/extended-statusbar/?src=hp-dl-featured
- etc.
Verified on FF52(Android 6.0.1). Issue is only reproducing on -dev.
Screenshot for this issue:
![2017-03-22_1436](https://cloud.githubusercontent.com/assets/15685960/24198921/7b177ed2-0f10-11e7-9ffd-b3e290300db6.png)

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @kumar303

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 6.0.1)
Postfix screenshots:
![2017-05-25_1110](https://cloud.githubusercontent.com/assets/15685960/26441851/da6379b6-413a-11e7-998f-36446e3e9e6d.png)
