### ISSUE TITLE
Existing user cannot sign in on AMO-dev without clearing cookies

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2139]
Steps to reproduce:
1. Load AMO-dev page on mobile https://addons-dev.allizom.org/en-US/android/
2. Try to sign in

Expected results:
User is signed in.

Actual results:
User is not signed in.

Notes/Issues:
- FxA page works as expected, but user seems logged out.
- if same steps are tried on desktop, with "mobile site view" on, user is signed in

Verified on FF52(Android 6.0.1). Issue is **only** reproducing on AMO-dev.
Video for this issue: 
![videotogif_2017 03 23_11 37 19](https://cloud.githubusercontent.com/assets/15685960/24241628/200c2a8e-0fbe-11e7-96e2-bc24e1d8ca62.gif)

**Comment by kumar303** [comment]
If you empty your cache on Firefox for Android, refresh the page, and try again does it work?

**Comment by ValentinaPC** [comment]
> If you empty your cache on Firefox for Android, refresh the page, and try again does it work?

Yes.

**Comment by kumar303** [comment]
ok, thanks. What happened is the code for handling login/logout changed. We need to think of a way to bust the cache automatically for changes like this.

**Comment by kumar303** [comment]
I added https://github.com/mozilla/addons-frontend/issues/2157 to show STR that can be performed in a fresh browser session.

**Comment by kumar303** [comment]
This has been fixed by https://github.com/mozilla/addons-server/pull/5030
