### ISSUE TITLE
Cannot sign in when certain cookies are missing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2157]
### Describe the problem and steps to reproduce it:

* Sign in to AMO on mobile
* After returning from a successful Firefox Accounts log in, note that you are logged in (login button changes to logout)
* Go to your browser settings and delete your `api_auth_token` cookie but do not delete your `sessionid` cookie
* Refresh the AMO mobile page you are on
* The logout button will turn into "log in" since you are no longer logged in
* Go through the log in flow and enter a correct Firefox Accounts password

### What happened?

When you return to AMO, you will not be logged in. The button will still say "log in."

### What did you expect to happen?

You should be logged just like normal

### Anything else we should know?

Of course, a user should not be deleting random cookies like this but the site should also not break! When we *renamed* the auth cookie (https://github.com/mozilla/addons-frontend/issues/2123) we inadvertently introduced this scenario on all users, see https://github.com/mozilla/addons-frontend/issues/2139 for a bug caused by the same root problem.

On the server, the `api_auth_token` is not regenerated which is part of the problem. Also, an error is generated about this but it is [never shown to the frontend](https://github.com/mozilla/addons-server/issues/5018).

**Comment by kumar303** [comment]
This is a relevant server side issue https://github.com/mozilla/addons-server/issues/5017

**Comment by kumar303** [comment]
This blocks release because all existing users will hit it when https://github.com/mozilla/addons-frontend/issues/2123 is deployed

**Comment by kumar303** [comment]
This has been fixed by https://github.com/mozilla/addons-server/pull/5030

**Comment by ValentinaPC** [comment]
> Go to your browser settings and delete your api_auth_token cookie but do not delete your sessionid cookie

Not very sure how to do this, can you give me a hand? :(

**Comment by Ryuno-Ki** [comment]
You need to activate the [Storage Inspector](https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector) in your browser's Developer Tools.

Then select „cookies” in the storage tree (see the MDN article).

**Comment by ValentinaPC** [comment]
@Ryuno-Ki : Thanks for info!

Verified as fixed on AMO-dev (Android 6.0.1, Win 7)
Postfix video: 
![storage](https://cloud.githubusercontent.com/assets/15685960/24411176/e17002fe-13dd-11e7-9163-851c79ca69ba.gif)
