### ISSUE TITLE
Extensions categories have layout issues for RTL lang

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2168]
Steps to reproduce:
1. Load Extensions categories page on your device https://addons-dev.allizom.org/en-US/android/extensions/categories/
2. Change the language to a RTL one i.e. https://addons-dev.allizom.org/ar/android/extensions/categories/

Expected results:
There are no display or layout issues.

Actual results:
Categories arrows are not RTL.

Notes/Issues:
Verified on AMO-dev FF52(Win 7).
Screenshot for this issue: 
![2017-03-24_1236](https://cloud.githubusercontent.com/assets/15685960/24290686/86260c88-108e-11e7-9c30-2a4cdbf86a48.png)

**Comment by ValentinaPC** [comment]
Now that #2170 is fixed, this is happening for themes categories also. 
Please see screenshot:
![2017-03-30_1229](https://cloud.githubusercontent.com/assets/15685960/24497640/c7bf3bfa-1544-11e7-8562-701220e71878.png)

Thanks!

**Comment by jvillalobos** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @tofumatt

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
![2017-05-26_1608](https://cloud.githubusercontent.com/assets/15685960/26495867/f43b2cd2-422d-11e7-9678-7a4afc6b6be2.png)
