### ISSUE TITLE
Search should be scoped to add-on type

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2169]
See #1744 and #1745–when in the "Themes" section of the site the search bar placeholder text should be scoped to say "Search Themes" only and not "Search Extensions and Themes". Same for Extensions.

**Comment by tofumatt** [comment]
In fact, this was fixed by #2523!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Postfix screenshots:
![search](https://user-images.githubusercontent.com/15685960/27271550-1a61f988-54ce-11e7-9b64-ff3fa59ac189.png)
