### ISSUE TITLE
Android Theme categories don't exist so "Browse Theme Categories" link goes nowhere

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2170]
Because #1875, this happens: https://github.com/mozilla/addons-frontend/issues/1745#issuecomment-288984336

We'll need to catch that request as well and stub in the `clientApp` as Firefox instead of Android until Android has its own theme categories...

**Comment by tofumatt** [comment]
This is similar to #1723.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev and AMO-stage using FF52(Android 6.0.1)
All categories are listed and redirect as expected.
Postfix screenshot: 
![2017-03-30_1142](https://cloud.githubusercontent.com/assets/15685960/24495542/29dba8ac-153e-11e7-9059-7886f5cb34a1.png)
