### ISSUE TITLE
Integrate <LoadingBar> into callApi calls

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2179]
Currently we only render the loading bar if reduxConnect dispatches an action we interpret as loading/finished loading. This means direct calls to the API like in the Ratings component won't render the loading bar. We should pass `dispatch` to those `callApi` calls and dispatch in callApi.

**Comment by kumar303** [comment]
We may need to introduce [thunk](https://github.com/gaearon/redux-thunk) to make it easier to use dispatch in `callApi()`.

**Comment by Ryuno-Ki** [comment]
I've looked into the source code of that react loading bar library.
It seems to just style a `<div>`, so AT users wouldn't be informed.

Shall I open a new issue about it?

**Comment by ValentinaPC** [comment]
Please add some STR for us to check his or the label "qa: not needed". Thanks!
