### ISSUE TITLE
Add application logs to Sentry errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2180]
When an error occurs and is logged to Sentry, it would be nice to see all console logging that led up to that error. We can do this with [breadcrumbs](https://docs.sentry.io/clients/javascript/usage/#raven-js-recording-breadcrumbs) but note that we strip out `console` logging in prod. We should also be careful of memory usage when collecting logs in the background.

**Comment by willdurand** [comment]
Do we still want to do this or can we leverage Logging2.0, which will be available soon for addons-frontend?

**Comment by willdurand** [comment]
@kumar303 Do we still want to do this or can we leverage Logging2.0, which will be available soon for addons-frontend?

**Comment by EnTeQuAk** [comment]
Breadcrumbs in sentry have been super useful to us on addons-server and helped a lot figure out scenarios how a user ended up with that specific exception.

**Comment by willdurand** [comment]
From what I am seeing, we have that enabled already, only logs are missing because we remove them.

**Comment by kumar303** [comment]
We have a request ID now but I forget if we added that to Sentry or not. We could use that to find logs in stackdriver.

**Comment by willdurand** [comment]
> We have a request ID now but I forget if we added that to Sentry or not. We could use that to find logs in stackdriver.

The request ID is available in Sentry (Sentry collects the req/res headers and the request ID is present).

**Comment by kumar303** [comment]
ok, having the request ID is enough to find logs so I guess we can close this. I suppose it would be slightly nicer to see all logs in Sentry itself but such an integration is probably not so straight forward since we will need to push backend data through the frontend somehow. I don't think it's worth the effort.
