### ISSUE TITLE
<title> is rarely changed

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2184]
We use `react-helmet` which lets us change the `<title>` tag across pages but we almost never change it from the default `Firefox Add-ons` title. We should change the title per-page–it makes it easy to tell pages apart and also probably helps with search.

**Comment by Ryuno-Ki** [comment]
Plus, it's a SEO criterium.

**Comment by grahamperrin** [comment]
Please, when might this enhancement be made? 

The lack of distinction between titles can be troublesome, for example: 

![2017-09-01 04 49 04 addons mozilla org desktop view of a comment after switching to mobile](https://user-images.githubusercontent.com/192271/30081603-b8c11f16-927f-11e7-9b7f-f213cdea3ee7.png)

**Comment by tofumatt** [comment]
I agree, and it would be great to get this fixed. But I don't think it's high-priority compared to a lot of other issues we are tying to close for the end of this month. We'd definitely welcome contributions though, if someone could tackle it.

Otherwise I'd think it's a month or two away at least :-(

Matthew Riley MacPherson (sent from mobile)

**Comment by muffinresearch** [comment]
We should look at doing this prior to the launch. We should also reflect the change to android from firefox if under that clientApp.

**Comment by willdurand** [comment]
I've started to work on this one. @tofumatt let me know if it conflicts with you.

**Comment by tofumatt** [comment]
Feel free to, I was out today so I'm a bit behind. I'll pick up anything you don't get to but I can work on other stuff in the meantime so I'll remove my assignment for now 😄

**Comment by grahamperrin** [comment]
Big thanks @willdurand 

I would have leapt in with a PR weeks ago, but I simply don't have coding skills. FWIW (I don't know the launch schedule) I should treat good titling as **essential** before launch. Considerations include the likelihood of people have more than the usual numbers of windows/tabs open, to add-ons, whilst seeking things that will be 57-compatible. 

Cheers

**Comment by vcarciu** [comment]
Verified as fixed : 
<img width="1280" alt="screen shot 2017-10-23 at 17 55 09" src="https://user-images.githubusercontent.com/1583842/31896675-095da030-b81d-11e7-9260-cc4895004a8d.png">

**Comment by grahamperrin** [comment]
Thanks, we're at the milestone date but the fix is not yet verifiable by me. 

https://discourse.opensourcedesign.net/t/-/411?u=grahamperrin includes a frame from a screen recording. 

A content delivery network (CDN) issue, maybe? Brighton, UK here.

**Comment by kumar303** [comment]
The deploy was in progress when you commented. Do you see it now?

**Comment by grahamperrin** [comment]
Yes! Both https://addons.mozilla.org/addon/switch-container/ and https://addons.mozilla.org/addon/switch-container/reviews/ appear fine, without a forced reload, when sent to the container that I use for testing. 

Yippee!
