### ISSUE TITLE
Hint text from Search field should be a lighter shade than the actual search input

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-frontend#2189]
*Environment*
Firefox: Nightly 55.0a1
Server: -dev
OS: Android 7.0

*Steps to reproduce*
1. Go to AMO mobile homepage and observe the text inside the Search field.

*Expected results*
The text should be a lighter shade than the actual search input.

*Actual results*
Hint text and search text have the same shade.

![hint text from search filed should be a lighter shade](https://cloud.githubusercontent.com/assets/26005101/24357048/fba70336-1304-11e7-9a86-addf2c15b2b3.gif)

**Comment by muffinresearch** [comment]
I think this currently matches the mocks. @pwalm I can see the rationale for changing this - if we're happy to do this what colour should it be?

**Comment by pwalm** [comment]
Makes sense. I've got the copy spec'd out at #FFF already, can't get any lighter. We could lower the hint text/search icon to #DCDCDC and the go to #FFF when active.

**Comment by raresmsv** [comment]
I don't know how this can be technically done, but from my perspective, there can be two ways:
1. The first one and I think the easiest, would be to use a gray color.
2. Second would be to reduce opacity of the text.

**Comment by vcarciu** [comment]
Verified this issue and the searchtext is now lighter than the hint text. Please let me know if this is the expected behavior : 
![lighter](https://user-images.githubusercontent.com/1583842/27335962-da4e2b78-55d6-11e7-850e-b8008c228e41.gif)

**Comment by tofumatt** [comment]
Yes, that screenshot is correct.

**Comment by vcarciu** [comment]
Thanks!
