### ISSUE TITLE
Add-on screenshot is overlayed by its caption if the text is too long 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2192]
Steps to reproduce:
1. Add a long screenshot description for an Android compatible add-on i.e. https://addons-dev.allizom.org/en-US/android/addon/bluhell-firewall/
2. Tap to preview the screenshot

Expected results:
There are no display or layout issues.

Actual results:
Text is displayed over the screenshot.

Notes/Issues:
- if the caption is larger than device's display, it cannot be read entirely;
- given the fact that this is causing troubles in desktop too (https://github.com/mozilla/addons-server/issues/1712), we could set a chars limit while adding a caption for screenshots.

Verified on FF52(Android 6.0.1). Issue is reproducing on AMO-dev and -stage. (I don't have rights to check it on prod)
Screenshot for this issue: 
![text](https://cloud.githubusercontent.com/assets/15685960/24361086/b3f5a2c4-1311-11e7-8ff1-b6136e4d839d.png)

**Comment by muffinresearch** [comment]
Seem like a bit of an edge case, but the screenshot viewer needs to be reviewed.
