### ISSUE TITLE
Disco Pane - light colored or translucent themes problematic in display

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#2197]
#### Proposed fix:

Ok, let's add a `1px stroke #F5F5F5` in between the theme image and the info block below:
![screen shot 2017-04-03 at 11 21 21 am](https://cloud.githubusercontent.com/assets/6797635/24624165/d2e17b1a-185f-11e7-9251-d8a1884cce27.png)

----

#### Original issue

Because of the frame-less way themes are displayed in Disco Pane, light-colored, translucent, or border-less themes are avoided because they appear to just float in space. 

For example, consider the awkwardness of a theme like this in Disco:

https://addons.mozilla.org/firefox/addon/cat-glasses/

... should we consider addressing in some way? Apply some type of border? 

@pwalm, @designakt

**Comment by pwalm** [comment]
We're in Taipei this week, but will look at it when we get back home.

**Comment by pwalm** [comment]
I'm not sure if adding a border saves this particular theme. The theme looks great when applied, but that big white block under the cat is going to look weird, no matter what:
<img width="740" alt="screen shot 2017-03-30 at 9 55 12 am" src="https://cloud.githubusercontent.com/assets/6797635/24484128/2da19438-152f-11e7-82ad-a3432092d742.png">

I'm ok with this theme looking a bit "off" in relation to the other themes (since it looks great when applied).

**Comment by devaneymoz** [comment]
This particular theme was just meant as an example. The issue crops up pretty regularly with other white-ish or translucent themes. If interested try experimenting with other light-colored themes and see what you think. 

I filed this in response to @designakt requesting we select more Disco themes that do NOT invert the color of the Firefox UI buttons. But because I tend to select darker colored themes for Disco (due to aforementioned issue) nearly all of them invert the buttons for contrast.

**Comment by designakt** [comment]
@devaneymoz Talking with @pwalm I think he sees no problem with bright themes as there is a shadow around the themes card that serves as a border. @pwalm correct me if I got that wrong.

**Comment by pwalm** [comment]
Ok, let's add a 1px stroke @ #F5F5F5 in between the theme image and the info block below:
![screen shot 2017-04-03 at 11 21 21 am](https://cloud.githubusercontent.com/assets/6797635/24624165/d2e17b1a-185f-11e7-9251-d8a1884cce27.png)

**Comment by pwalm** [comment]
@tofumatt or @mstriemer: Can I ask one of you guys to please add this to your (very long) to-do list? 😅 Thanks!

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @tofumatt

**Comment by ValentinaPC** [comment]
Is there a way for us to check this? Because, in -dev, Disco Pane, we do not have "white" themes available so...need help. Thanks!

**Comment by muffinresearch** [comment]
@ValentinaPC easiest way is to delete the src attribute with dev tools. This will break the image and it should just show alt text.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
Postfix screenshot:
![disco_pane](https://user-images.githubusercontent.com/15685960/30645687-248017a2-9e1f-11e7-8b2d-9eff53123112.png)
