### ISSUE TITLE
Average rating stars is not looking good

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2200]
Steps to reproduce:
1.On Android, go to https://addons-dev.allizom.org/en-US/android/addon/shamrocks2/
2.Observe the average rating stars under number of users (2,5 out of 5)
3.Open "Read all 3 reviews" link under rating section
4.Observe the Ratings(2x4 star ratings and one of 3 stars rating)

Expected results:
The average rating stars should indicate an average of 3,66 out of 5 stars

Actual results:
2,5 out of 5 stars

Please see video for this issue : 
![avgstars](https://cloud.githubusercontent.com/assets/1583842/24412173/641190c2-13e0-11e7-98f8-4b0630431331.gif)

**Comment by tofumatt** [comment]
This is confusing, but appears to be an API bug, not an addons-frontend bug. The API is returning an average of `2.66[...]` which we display as `2.7 of out 5` and 2.5 stars.

Not sure why the average is wrong but could have to do with a lot of the data inconsistencies we've been seeing on -dev. 😢

<img width="180" alt="screenshot 2017-03-28 16 04 45" src="https://cloud.githubusercontent.com/assets/90871/24412474/77345faa-13d0-11e7-92f5-b5af6a18850b.png">
<img width="1200" alt="screenshot 2017-03-28 16 04 41" src="https://cloud.githubusercontent.com/assets/90871/24412475/7734d430-13d0-11e7-8b80-2d20e6c9ab79.png">

**Comment by vcarciu** [comment]
@tofumatt - and in this case another bug should be logged?

Also, just as an assumption , maybe if some of reviews were edited (not sure about that) , maybe the previous ratings were added too to the average? If yes is this still and api bug?

**Comment by tofumatt** [comment]
Yes, sorry, I shouldn't have closed it so fast. It should be logged on addons-server as an api bug. It could be what you said it might be but we can track it and verify there.

Matthew Riley MacPherson (sent from mobile)
