### ISSUE TITLE
No restart required after a "requires restart" add-on uninstall

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2207]
Steps to reproduce:
1.On Android, install an add-on that requires restart (https://addons.allizom.org/en-US/android/addon/stylish/)
2.Try to uninstall it

Expected results:
User is asked for a restart in order to complete the uninstall

Actual results:
First time when trying to uninstall it, the uninstall button will be on a continuous waiting state, without any Restart pop-up . 
After going back and opening again the add-on details page, the button will be green and when trying to uninstall the add-on again, it will looks like the add-on is uninstalled and again no Restart pop-up is displayed. After a page refresh , we will see that the add-on is still not uninstalled.
After closing and restarting the browser, the add-on will be correctly uninstalled, 

NOTES:
Reproducible on all servers

Please see video for this bug : 
![ff does not request restart at uninstall](https://cloud.githubusercontent.com/assets/1583842/24509326/bc1de8d0-156e-11e7-8e31-ffe46a133829.gif)

**Comment by muffinresearch** [comment]
This is pretty much the same bug as https://github.com/mozilla/addons-frontend/issues/2028 except for uninstall instead of install. That bug contains the UX that needs implementing. We should be getting a needsRestart hint we just need to respond to it on AMO.

**Comment by muffinresearch** [comment]
I've linked this up from the other bug, since that one has UX I'm going to mark this as a dupe.
