### ISSUE TITLE
Unnecessary long and meaningless search term, will return results in AMO and Add-ons manager

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-frontend#2213]
*Environment*
Firefox: Unbranded 52.0.3
Server: prod
OS: Windows 10

*Steps to reproduce*
1. Go to AMO mobile homepage and in the Search box enter meaningless and unnecessary search term. Make sure you include a separate group of two letters (eg: SE, IT). Press Enter. Observe the results.

*Expected results*
No results are returned.

*Actual results*
Results are returned.

*Notes*
1. Reproducibility: 5/5.
2. Also reproducible in Add-ons manager.
3. Strings used to reproduce:
•	"se itaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa”
•	“bugcjkvazladfhkldhklsdhklsd hsdhdlfh sdlfsdkljskldfklafjklsfklasdfjklsdjklasdjfkl;sdjfdjfad;jf;jjsdklgjsdfjf gjasdklgjdgjerphpetgpg40t9-4uy24n se”

**Comment by raresmsv** [comment]
![meaningless search term returns results](https://cloud.githubusercontent.com/assets/26005101/24546091/7710e05e-1612-11e7-8015-c4ef3eefc206.gif)

**Comment by muffinresearch** [comment]
This just means the search perspective something matched one of the "words" used. This doesn't have to be a full match either thanks to stemming etc. 

I don't think there's anything actionable to do here.

FWIW: search issues are probably best to be filed on mozilla/addons-server for future reference.
