### ISSUE TITLE
Language selector and language from URL are different

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2219]
Steps to reproduce:
1. Navigate to a page on your Android device  i.e. https://addons-dev.allizom.org/en-US/android/themes/
2. Change the language
3. Go back to previous page

Expected results:
Language listed in the page footer is the same as the one listed in the page URL.

Actual results:
Different results are displayed.

Notes/Issues:
- in the URL is displayed the language from step 1, in the language selector is displayed the language selected at step 2;
- navigating to other pages after step 3 will not change anything;
- refreshing the page will make things turn back to normal;

Verified on FF52(Android 6.0.1). Issue is reproducing all around AMO servers.
Video for this issue: 
![videotogif_2017 04 03_10 21 50](https://cloud.githubusercontent.com/assets/15685960/24599855/cb768b22-185a-11e7-8b08-f5eea0bffe9a.gif)

**Comment by muffinresearch** [comment]
This is typical browser behaviour, you returned to the old language url and the form is set to the same value you set it to when you navigated away.

**Comment by tofumatt** [comment]
I'm not sure why this is flagged as an enhancement; going back after a language change will reset the language and as @muffinresearch said is standard browser behaviour when a site's locale is in the URL.

I think we can close this; getting around it in any way would be a huge hack.
