### ISSUE TITLE
The number of users for extensions/themes is not updated after install

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-frontend#2221]
*Environment*
Firefox: Nightly 55.0a1
Server: -dev
OS: Android 7.0

*Steps to reproduce*
1. Go to AMO mobile homepage and install any extension/theme. Observe the number of users before and after install.

*Expected results*
The number of users is updated.

*Actual results*
The number of users remains the same.

*Notes*
1. Reproducibility: 5/5.

![screenshot_20170403-173500](https://cloud.githubusercontent.com/assets/26005101/24614563/3c0649ca-1894-11e7-98c9-2f7da2362d76.png)
![screenshot_20170403-170911](https://cloud.githubusercontent.com/assets/26005101/24614573/40b6bcca-1894-11e7-97e6-3bcd405de2c6.png)

**Comment by muffinresearch** [comment]
@raresmsv could you re-check after a duration? I think counts are eventually consistent and not necessarily immediate.

**Comment by vcarciu** [comment]
@muffinresearch : I rechecked exactly same addo-on tried by Rares on -dev last month and it is still having 35 users. 
Also, I tried with another add-on , and number was not increased even if I checked it after a duration.

**Comment by muffinresearch** [comment]
@diox do you know if install counts should be working on -dev?

**Comment by kumar303** [comment]
I'm pretty sure this is a frontend issue.

After any change to the data, we have to explicitly [refresh the add-on](https://github.com/mozilla/addons-frontend/blob/fcafeb6f3bd345123adbb167759edd945ad60601/src/core/utils.js#L99).

My guess is that calling `refreshAddon` [right after installation](https://github.com/mozilla/addons-frontend/blob/fcafeb6f3bd345123adbb167759edd945ad60601/src/core/installAddon.js#L238) will fix it. It probably needs to be applied in multiple places though.

**Comment by diox** [comment]
> @diox do you know if install counts should be working on -dev?

They should not. Stats do not work in dev/stage.

**Comment by muffinresearch** [comment]
@raresmsv based on https://github.com/mozilla/addons-frontend/issues/2221#issuecomment-324756087 if this isn't reproducible on production I think we can close this.

**Comment by vcarciu** [comment]
@muffinresearch  : Unfortunately , this is reproducible on prod too . Tried many installs and number of users was not increased even if I re-checked after a duration .

**Comment by muffinresearch** [comment]
@vcarciu ok, thanks for the update - in that case we need to dig into precisely where the problem is. /cc @kumar303 @diox

**Comment by kumar303** [comment]
> this is reproducible on prod too

@vcarciu could you provide some example add-on URLs?

**Comment by vcarciu** [comment]
@kumar303 : 
I installed last week https://addons.mozilla.org/en-US/android/addon/game-fun/ and it still shows 17 users , same number as before installing it.

**Comment by diox** [comment]
Is this still an issue? The URL above does not work.

**Comment by ValentinaPC** [comment]
@diox : I've tried with other extensions - https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/ .
The number of users before install:
![bfore_installl](https://user-images.githubusercontent.com/15685960/32949931-3c466420-cbad-11e7-931e-fb2a39e27e15.png)

After install nothing changed. 
How long should we wait so that we could see the number increased?

**Comment by diox** [comment]
@ValentinaPC it won't work on dev/stage - stats are not processed there.

**Comment by ValentinaPC** [comment]
@diox : I've installed this add-on https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/ using FF59, about 2 hours ago and the number of users is the same as before install.

**Comment by diox** [comment]
Install count stats are processed every day, not live. So I don't see the issue here.

**Comment by ioanarusiczki** [comment]
I installed 3 days ago 2 add-ons submitted by me on AMO prod using FF 59. I made stats public and checked them.  The number of user in the add-ons page was still not updated, stats also show that avarage daily users is 0 but the number of downloads increased by one. 

https://addons.mozilla.org/en-US/firefox/addon/hedger/
![stats](https://user-images.githubusercontent.com/33448286/36369374-ac8f48b4-1563-11e8-8b85-480848be8dcc.png)
![number of users](https://user-images.githubusercontent.com/33448286/36369384-b3f8ec5e-1563-11e8-98bb-b8f7cbc85a4d.png)

**Comment by tofumatt** [comment]
If stats aren't being updated for certain pages after several days and a refresh I don't think it's a frontend problem; none of the data is cached for us so the API isn't updating the stats.

Right now we don't update them right after install but that's a separate issue that we can't fix until we go back to using `mozAddonManager` to install things anyway (#3954).

Is there something wrong with that add-on in particular? This is not an easily-reproduced issue, as many add-ons in production get updated stats.

**Comment by kumar303** [comment]
This doesn't appear to be a frontend problem.
