### ISSUE TITLE
"Read More" link from add-on description is not displayed for Italiano

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2225]
Steps to reproduce:
1. Load details page for an add-on with long description on your Android device i.e. https://addons-dev.allizom.org/en-US/android/addon/rememberpass/
2. Change the language to "Italiano"
3. Observe the Description section

Expected results:
There is a "Read More" link that reveals the entire description.

Actual results:
The "Read More" link is not available.

Notes/Issues:
- reproducing only for "`it`";
- taping in the area where the link it supposed to be, reveals add-on description;
- reproducing for themes also;

Verified on FF52(Android 6.0.1, Win 7). Issue is reproducing all around AMO servers.
Screenshot for this issue: 
![2017-04-04_1545](https://cloud.githubusercontent.com/assets/15685960/24657103/b9f164f0-194d-11e7-83b3-f5bfb3ba6301.png)

**Comment by muffinresearch** [comment]
The reason for this is there's a slightly malformed translation here: https://github.com/mozilla/addons-frontend/blob/master/locale/it/LC_MESSAGES/amo.po#L578

**Comment by muffinresearch** [comment]
@kitsunenosaraT hi would you have a moment to look at this and provide a translation for the hidden part and move the translation for "Read more" outside the span as per the english key?

**Comment by kitsunenosaraT** [comment]
@muffinresearch I've just updated the string on Pontoon. Really sorry about the inconvenience!

**Comment by muffinresearch** [comment]
@kitsunenosaraT no problem, thanks for the fix.

Fixed in https://github.com/mozilla/addons-frontend/commit/a5c26ee5dd0ddc50084ca26cc23065987cff0994

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52(Android 6.0.1)
Postfix screenshots:
![2017-04-05_1341](https://cloud.githubusercontent.com/assets/15685960/24702068/d653a0fa-1a05-11e7-94fb-7601ba1eede2.png)
