### ISSUE TITLE
Switch to the official GitHub Greenkeeper integration

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2230]
GitHub "officially" supports Greenkeeper now: https://github.com/integration/greenkeeper

We should try enabling it because something I read (that I can no longer find) said "less pull requests."

**Comment by tofumatt** [comment]
I thought we already did that? It will create a comment when a newer version than the one in the PR comes out with a link that says “Create a PR with this version instead” and will close the old PR.

**Comment by kumar303** [comment]
oh! I see. I didn't know that was coming from the official integration. Hmm, I guess they don't give you "less pull requests" after all then. Or perhaps they just mean the "new version has been posted" feature.

**Comment by tofumatt** [comment]
Yeah, I think that’s it. In the past they’d make a new PR for every version bump; the official ones comments on existing ones. It IS better, but yeah still pretty noisey.
