### ISSUE TITLE
Installing on Android gives a "access it in the toolbar" message

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#2235]
I don't have a toolbar on my Android.

![screenshot_20170405-164843](https://cloud.githubusercontent.com/assets/74699/24731659/565ff1da-1a20-11e7-877b-6058f71c1f32.png)

**Comment by kumar303** [comment]
This was a dialog [originally meant for discopane](https://github.com/mozilla/addons-frontend/pull/671) on desktop. What should it say on Android? "Now you can access Emoji Keyboard" ...?
