### ISSUE TITLE
NEW MOZILLA ADDON SITE CRASH

### ISSUE THREAD

**Issue by boneburner** [mozilla/addons-frontend#2236]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

COOLPAD CATYLYST,  ANDROID,  ORFOX V 45.5.1/ORBOT,  NEW MOZILLA ADDON SITE CRASHESFIREFOX CRASH AT NEW MOZILLA ADDON SITE

**Comment by kumar303** [comment]
Can you provide some details on what you did to cause the crash?

**Comment by muffinresearch** [comment]
Closing, but please re-open if you have additional details.
