### ISSUE TITLE
CSS reloader fails after a syntax error

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2240]
### Describe the problem and steps to reproduce it:

* Fire up a dev server and start working on some CSS/SCSS
* Trigger a Sass error such as using an undeclared variable
* Fix the error

### What happened?

The error screen disappears but all styles are broken in the component that triggered the error.

### What did you expect to happen?

The styles should not be broken.

### Anything else we should know?

Reloading the page fixes it.

**Comment by muffinresearch** [comment]
create-react-app has a great experience for this kind of thing using an overlay for errors.

**Comment by willdurand** [comment]
This has been fixed by the new HMR/dev setup I think because the STR in the OP don't produce any issue to me. We also have an overlay with the errors.
