### ISSUE TITLE
RtaCloud

### ISSUE THREAD

**Issue by radhefa** [mozilla/addons-frontend#2243]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org
