### ISSUE TITLE
The review button from the developer’s page does not scroll the page to the Reviews section

### ISSUE THREAD

**Issue by raresmsv** [mozilla/addons-frontend#2256]
*Environment*
Firefox: Nightly 55.0a1
Server: -dev
OS: Windows 10

*Steps to reproduce*
1. Go to AMO homepage and access the details page of any add-on with reviews.
2. Go to the developer’s page.
3. From the list of products, click on the review button of one of listed add-ons and observe the behavior.

*Expected results*
The user is taken to the details page of the add-on, scrolled to the Reviews section.

*Actual results*
The details page of the add-on is displayed, but it is not scrolled to the Reviews section.

*Notes*
1. Reproducibility: 5/5.

![review button page not scrolled to reviews](https://cloud.githubusercontent.com/assets/26005101/24869809/15ecddb0-1e1d-11e7-8bdf-0b88e6fd9c07.gif)

**Comment by kumar303** [comment]
Hi, thanks for taking the time to file an issue. This code is in [addons-server](https://github.com/mozilla/addons-server) so it's not relevant to the frontend repo. The code will be replaced soon though so that team may not wish to prioritize it.
