### ISSUE TITLE
Rely on Flow types for external libraries

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2257]
Once we have [basic Flow support](https://github.com/mozilla/addons-frontend/pull/2196) we should start adding definitions for the external libraries we depend on: https://github.com/flowtype/flow-typed 

We don't need to fall down the rabbit hole and define everything. We should just pick some ones that we rely on very heavily and that do not have great test coverage. For example, we rely on using the `redux` interfaces correctly and our tests do not cover this. We should definitely define the `redux` interfaces.

**Comment by willdurand** [comment]
Redux interfaces are defined by us. I have lost faith in flow-typed because most of the time we get a lot of files/directories for "stubs". Are there any dependencies that would need definitions that we do not have already?

**Comment by willdurand** [comment]
I'd be inclined to close this issue and open it again if we feel the need.
