### ISSUE TITLE
Rely on Flow types for action/reducer types

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2260]
We use constants to link an action type to reducer code in a switch statement. We can probably just ditch the constant and rely on Flow (initial support added in https://github.com/mozilla/addons-frontend/pull/2196) to make sure that these two values stay in sync.

It might be helpful to switch to ducks first: https://github.com/mozilla/addons-frontend/issues/1299

**Comment by willdurand** [comment]
We do this now, so closing.
