### ISSUE TITLE
update AMO favicon

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#2262]
### Describe the problem and steps to reproduce it:
Go to the new AMO website and look at the favicon.

### What happened?
The favicon is a very old depiction of the puzzle-piece that does not match the appearance of AMO.

### What did you expect to happen?
See the same puzzle-piece we use as a logo on the mobile website.

### Anything else we should know?
![amo-favicon](https://cloud.githubusercontent.com/assets/8145891/24904704/96d92ac0-1eb1-11e7-80b3-3bd3654ba2c6.PNG)

@pwalm what do you think the favicon should be?

**Comment by designakt** [comment]
here is a related to a bug to create a set of add-on icons that align with Photon icon guidelines: https://bugzilla.mozilla.org/show_bug.cgi?id=1048912#c20

**Comment by pwalm** [comment]
Updated icon in new header, will propagate to the mobile site due to magical responsive goodness.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1).
Postfix screenshot:
![2017-09-13_1041](https://user-images.githubusercontent.com/15685960/30365354-254f1656-9870-11e7-857c-95e25f87ba9e.png)

**Comment by muffinresearch** [comment]
This bug was actually about the favicon, however this is actually superceded by #2824 in any case.
