### ISSUE TITLE
Prompt the user to upgrade when a newer version of AMO is available

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2264]
### Describe the problem and steps to reproduce it:

- Open AMO
- [wait for a new version of the site to be deployed]
- Keep using the app

### What happened?

You get the old version of the site

### What did you expect to happen?

You should be prompted to reload the page so you get the new version of the site

### Anything else we should know?

We could use a message like this: https://github.com/mozilla/addons-frontend/issues/2238#issuecomment-293326491

We could probably poll this endpoint (once a day or something) https://github.com/mozilla/addons-frontend/issues/2060

**Comment by mstriemer** [comment]
Every so often when I click on something in my webmail client I will get a full refresh instead of the JS-based one. I always assumed this was doing an update in the background but I'm not totally sure (I think that makes sense anyway).

Perhaps that solution would work for us too?

**Comment by kumar303** [comment]
oh yeah, we can probably do it seamlessly on link click. I guess it would be unlikely that they would be using the site for a long time without clicking on at least one link.

**Comment by willdurand** [comment]
Now that the website is feature complete, we do not have much updates that require a full reload, so I am going to close this issue for now.
