### ISSUE TITLE
website not available with Pocket application went Pro high or vanished

### ISSUE THREAD

**Issue by darkpixie** [mozilla/addons-frontend#2276]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

### What happened?

Website not available with software

### What did you expect to happen?

To download it

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

Pocket software for android saving named Save-it-later is gone?

**Comment by kumar303** [comment]
Hi, this repository is for code related issues, not content related issues. I can still try to help. Can you elaborate on the problem? Is it that you can no longer find the Pocket extension on addons.mozilla.org for Android?

**Comment by darkpixie** [comment]
yes, maybe its deleted or pro gone? what du you think tank?

It was Pocket and its not working because of gone wildly commercialised?

Greets,
axxo




On Apr 18, 2017 4:29 PM, "Kumar McMillan" <notifications@github.com> wrote:

Hi, this repository is for code related issues, not content related issues.
I can still try to help. Can you elaborate on the problem? Is it that you
can no longer find the Pocket extension on addons.mozilla.org for Android?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mozilla/addons-frontend/issues/2276#issuecomment-294862577>,
or mute the thread
