### ISSUE TITLE
UI issues for cyrillic languages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2277]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/bg/developers/addons (Same for Russian)
2.Observe the header 

Expected results:
No UI issues in Cyrillic languages

Actual results:
There are overlaying issues for Cyrillic languages

Notes:
I know that there are small overlaying issues for other non Cyrillic languages and we agreed that these will not be fixed, but in this case the UI issues are very obvious

Please see screenshot for this issue : 
![cirillyc](https://cloud.githubusercontent.com/assets/1583842/25134535/84c3d3c4-2458-11e7-8f6f-520526832f4f.png)

**Comment by muffinresearch** [comment]
This is actually an addons-server issue.

**Comment by vcarciu** [comment]
I will move it to addons-server then. Thanks
