### ISSUE TITLE
Show "Compatible with Firefox 57+/XX (android)" for relevant add-ons on the amo site.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2279]
See https://github.com/mozilla/addons-server/issues/4974

We'll need to expose the `Compatible with Firefox 57+` on the mobile/desktop new frontend. This assumes we have a flag for determining this easily already from the API.

Needs UX since this is quite a long string.

**Comment by muffinresearch** [comment]
Sounds like Fennec is aiming to turn off legacy ext in 59 so this label will need to be conditional based on desktop vs mobile.

**Comment by pwalm** [comment]
I think is done, right @muffinresearch ?

If not, we've got designs for it.

**Comment by pwalm** [comment]
This is covered here:
<img width="702" alt="screen shot 2017-10-06 at 2 43 31 pm" src="https://user-images.githubusercontent.com/6797635/31299740-bde210e4-aaa4-11e7-912a-ae233a325c2a.png">

**Comment by kumar303** [comment]
Thanks. I removed the needs:ux label but I'll leave it open until it's live on the site. However, we have discussed that maybe we don't need this badge since we have a compatibility banner already.

**Comment by muffinresearch** [comment]
I think this is a wontfix.
