### ISSUE TITLE
Bump dompurify version to 0.8.6

### ISSUE THREAD

**Issue by g-k** [mozilla/addons-frontend#2292]
### What happened?

Cure53 released a new version of DOMPurify https://twitter.com/cure53berlin/status/855421226751328258

### What did you expect to happen?

We should update to the latest version to pick up the Safari fix: https://github.com/mozilla/addons-frontend/blob/d0b0a475f7d029401471fbe56823c7ae87b5b873/package.json#L185

### Anything else we should know?

**Comment by tofumatt** [comment]
Cheers, I'll get on this for the next tag.

**Comment by kumar303** [comment]
Thanks for the heads ups! Looks like Greenkeeper has us covered. https://github.com/mozilla/addons-frontend/pull/2291
