### ISSUE TITLE
Clarify max characters error message upon addon submit

### ISSUE THREAD

**Issue by Smile4ever** [mozilla/addons-frontend#2295]
### Describe the problem and steps to reproduce it:
An newly submitted addon with supporting i18n names can hit the name limit without a clear message on addons.mozilla.org.

### What happened?
The addon name i18n for Dutch is for example "Shop & winkel goedkoop bij Amazon.com zonder extra kosten" (57 characters). The English name is "Shop on Amazon.com without extra costs" (38 characters).

You put in "Shop on Amazon.com without extra costs" as a name (38 characters) and yet is says "Ensure this value has at most 50 characters (it has 57)".

### What did you expect to happen?
A message is displayed which shows the name which is too long, instead of the vague message right now.

### Anything else we should know?
Screenshot from https://discourse.mozilla-community.org/t/cannot-submit-because-of-the-limitation-for-name/14096/6
![](https://discourse-paas-production-content.s3.amazonaws.com/original/2X/8/864b083e5f6f2a7183b7420793923461502ff0fb.png)

**Comment by kumar303** [comment]
Hi, thanks for taking the time to file an issue. This part of the code, while it is "frontend," is actually in https://github.com/mozilla/addons-server so it will be more actionable if you can re-file the issue in that repo.

**Comment by tofumatt** [comment]
I've re-filed it at https://github.com/mozilla/addons-server/issues/5229

**Comment by kumar303** [comment]
Thanks @tofumatt !
