### ISSUE TITLE
Comma in the wrong places for Hungarian

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2305]
Steps to reproduce:
1. Load any add-on details page on your Android device i.e. https://addons-dev.allizom.org/en-US/android/addon/lock/
2. Change the language to `Hungarian` and check add-on's name section and "read more" link i.e. https://addons-dev.allizom.org/hu/android/addon/lock/

Expected results:
Sections are localized.

Actual results:
A unusable comma is displayed before "by" from add-on name section and before "Read more" link.

Notes/Issues:
Verified on FF53(Android 6.0.1). Issue is reproducing all around AMO servers.
Screenshots for this issue:
![comma](https://cloud.githubusercontent.com/assets/15685960/25338851/5181b688-2909-11e7-9a83-302be4f8e154.png)

**Comment by muffinresearch** [comment]
This is in the translation: https://github.com/mozilla/addons-frontend/blob/bcdb256648181d12177751eefb6d8c7e7b65cb51/locale/hu/LC_MESSAGES/amo.po#L62

@meskobalazs hi, would it be possible to adjust the translation to not start the line after the add-on name with a comma?

**Comment by meskobalazs** [comment]
Sure. If it is not in the hint already it should be specified, that there is a line break after the name. From the span, it is not obvious, as it is an inline element :)

**Comment by muffinresearch** [comment]
> Sure. If it is not in the hint already it should be specified, that there is a line break after the name. From the span, it is not obvious, as it is an inline element :)

Yep, I agree we could do a lot better re comments for localizers. I'll file a bug to add something to help with that.

**Comment by muffinresearch** [comment]
This looks to have been fixed in the translation.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Postfix screenshot:
![hu](https://user-images.githubusercontent.com/15685960/27170055-380c2c5e-51b5-11e7-9a10-eff723eb60c8.png)
