### ISSUE TITLE
Start adding comments for localizers. 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2307]
Relates to https://github.com/mozilla/addons-frontend/issues/2305

Extraction should be ok to handle comments for localizers so we should start adding them where the context needs additional explanation.

**Comment by kumar303** [comment]
Sounds like a good idea. What is the actionable outcome that would close this issue? Should we comb through and add comments to existing `gettext()` calls?

**Comment by muffinresearch** [comment]
> Sounds like a good idea. What is the actionable outcome that would close this issue? Should we comb through and add comments to existing gettext() calls?

Yeah first thing would be to try adding one for the issue covered in #2305 and check the extraction  handles it as expected. 

Then I'd suggest reviewing anything with a placeholder replacement since they could probably use more explanation in some cases.

**Comment by muffinresearch** [comment]
@suhailsinghbains the comment above details a [potential starting point](https://github.com/mozilla/addons-frontend/issues/2307#issuecomment-296782027) - but please note that comment is quite old so the references might be out of date. 

The goal is making it clear what is being substituted in translation strings and pointing out any other specific things a localizer should be aware of. It's best done at the time of writing the strings, and whilst I don't want to stop you - this might not be the easiest bug to work on unless you can rationalize where the strings are displayed and understand the intent.

**Comment by suhailsinghbains** [comment]
Hi, Are we going to add a comment to each gettext() Calls?
Thanks

**Comment by willdurand** [comment]
> Hi, Are we going to add a comment to each gettext() Calls?

No. I am wondering whether this issue is still relevant to be honest, because we've added comments for localizers over the last few months, and I believe localizers reported issues to us.

**Comment by willdurand** [comment]
So I think we can close this issue now. We use translator comments already and we likely won't review all the `gettext()` calls anyway.
