### ISSUE TITLE
Investigate server rendering every page request instead of client-side navigation

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2318]
@kumar303 mentioned this before - we could potentially server render every distinct page rather than ever having the client respond to any page requests from first load onwards.

Today we have a universal app which means:

* Client makes first request to AMO
* First request is rendered by the server and sent to the client
* Client receives the page
* Client executes JS 
* From this point on all interactions and navigations are run from the client and all data is requested from the client.

The server request model would look more like this:

* Client makes request to AMO
* Request is rendered by the server and sent to the client
* JS is executed and react would handle only the most minimal set of client-side interactions / data fetching for widgets with interactions.
* Anything that's a page level request would be a request to the server again.

One thing that would make this better is if we could minimise the client-side JS bundle size with this kind of approach? E.g. it would be nice if you could server-side render a page and only send the relevant JS necessary to enhance the page for interactions.

Add thoughts and suggestions here:

## Pros

- Traditional serving probably easier to reason about.
- Might make some of the pieces that client-side apps need to re-invent go away. E.g. scroll position / back button etc.
- Potential to reduce the amount of JS sent to the client.

## Cons

- Difficult to know how to define the boundaries between server and client e.g what's enhanced what's not etc. Maybe the line could be drawn at anything that requires a URL update should be a server request.
- State limited to representing only the current page (but maybe that's not a downside).
- node app server load; we'll need to effectively run two servers for every request and will have to scale up our node app instances to be in line with AMO users. see below: https://github.com/mozilla/addons-frontend/issues/2318#issuecomment-297688601

## Open questions

*  How far would server-rendering go? What would we do with forms for example?
* What are the trade-offs in terms of data over the wire. Server request might be bigger than just a pure-data request, but how does this compare if less JS is needed to be executed etc.

## What is the primarily JS-only pieces of our site?

* Install button
* Ratings interactions? (Probably could have been done with server-side forms too).

**Comment by tofumatt** [comment]
Another con is that the server has to do more work. I don’t know how substantial that is but right now after the first page load the addons-frontend node server can just sit there. With this approach we need a node/react server AND a Python/Django server for every request.

Dunno how much that matters but AMO gets a lot of traffic. Offloading the render to the client afterward is less work our servers need to do. I don’t know if the extra processing even a phone needs to do to load the page matters, but millions of requests hitting our node servers will...

**Comment by muffinresearch** [comment]
> Another con is that the server has to do more work. I don’t know how substantial that is but right now after the first page load the addons-frontend node server can just sit there. With this approach we need a node/react server AND a Python/Django server for every request.

Yep good call - can you add that under cons?

**Comment by muffinresearch** [comment]
@kumar303 @tofumatt any further thoughts on this? Should we keep this open for consideration or are we able to conclude that at least for now this isn't a direction we should be looking to head in?

**Comment by kumar303** [comment]
I vote that we close this issue. This [story](https://medium.com/elemefe/upgrading-ele-me-to-progressive-web-app-2a446832e509) suggests that it is technically impossible to achieve single-page-app speed with a multi-page app. They tried everything.
