### ISSUE TITLE
We should add a rule for how words are separated at the end of lines in reviews listing

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2319]
Steps to reproduce:
1.On Android, go to https://addons.allizom.org/en-US/android/addon/youtube-center/reviews/
2.Observe how the words are separated in syllables at the end of each line

Expected results:
Words are correctly separated in syllables or they should be entirely moved to the next line 

Actual results:
Words are separated without any rule at the end of each line

NOTES: 
Reproducible on all servers

Please see screenshot for this issue : 
![screenshot_20170427-141636](https://cloud.githubusercontent.com/assets/1583842/25482340/f88fc97c-2b59-11e7-9273-95325d421f8a.png)

**Comment by muffinresearch** [comment]
Regression from https://github.com/mozilla/addons-frontend/pull/1795

**Comment by muffinresearch** [comment]
@vcarciu it's on -dev now.

**Comment by vcarciu** [comment]
Verified as fixed : 
![align](https://cloud.githubusercontent.com/assets/1583842/25485747/9f516a38-2b67-11e7-815f-ff883cd90430.png)
