### ISSUE TITLE
Preserve unsubmitted review text

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2322]
### Describe the problem and steps to reproduce it:

* Log in
* Rate an add-on and begin entering a text review
* Be unfortunate enough to have your [auth token expire](https://github.com/mozilla/addons-frontend/issues/2237) (or have your browser crash or your tab accidentally closed, etc)

### What happened?

The text you entered will be lost (in most cases).

### What did you expect to happen?

The text should not be lost. It should appear in the text field when you return to rate the add-on again.

### Anything else we should know?

This is more important now that https://github.com/mozilla/addons-frontend/issues/2237 landed

**Comment by ValentinaPC** [comment]
The review text is preserved.
Verified this on AMO-dev FF53(Win 7) while in Mobile Site View.
Postfix video:
![close](https://cloud.githubusercontent.com/assets/15685960/26300480/dfebd3d4-3ee6-11e7-9d9e-792b18557e1c.gif)
