### ISSUE TITLE
Cannot edit a star rating (without review text)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2325]
### Describe the problem and steps to reproduce it:

* Log in
* Go to an add-on that you have not rated
* Select a star rating but do not enter any text for the review (tap outside the box to close it)
* Simulate returning to the site by clicking the browser refresh button on the URL

### What happened?

The stars you had saved disappeared. If you try to rate the add-on again you see an error like 'you cannot leave more than one review'

### What did you expect to happen?

The saved stars should appear selected. You should not get an error when you try to edit the rating.

### Anything else we should know?

This is broken in production.

Here is some more info from the API perspective: https://github.com/mozilla/addons-server/issues/5288

The root cause is that a null `review.body` (which is due to no text being entered) triggers some code that excludes the review from the filter -- this makes the site think no saved rating exists. Part of the complication here is that the API request to query for existing reviews is not made with authentication even though the user is signed in.

**Comment by kumar303** [comment]
I'm landing a quick fix to this. Here are the follow-ups that need to happen:
* We need a new API filter: https://github.com/mozilla/addons-server/issues/5297
* We need to fix the frontend code to use that filter: https://github.com/mozilla/addons-frontend/issues/2327
* We should really provide a way to visualize star rating reviews (instead of hide them) https://github.com/mozilla/addons-frontend/issues/2328

**Comment by SVSanta** [comment]
Verified as fixed using AMO-dev FF55(Win 10 64Bit).
Postfix video:
![videotogif_2017 05 02_12 56 37](https://cloud.githubusercontent.com/assets/28138132/25616761/3d58a86c-2f47-11e7-83e8-d7ff4efdab95.gif)

**Comment by kumar303** [comment]
Note that this was a regression of https://github.com/mozilla/addons-frontend/issues/2019
