### ISSUE TITLE
Hide empty reviews from the review list because review count is wrong

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2327]
Steps to reproduce:

1. Go to an add-on details page for an add-on that has empty reviews (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/multi-highlight/). An empty review is one where the user has just selected a star but did not enter any text.
2. In the rating section observe the number of reviews associated with the add-on and then click on 'Read all Reviews'
3. Once the page loads, verify the actual number of reviews displayed

Expected result:
Number of reviews mentioned in the add-on details page and total reviews form 'All reviews' page are the same

Actual result:
Number of reviews from "All reviews' page is lower than the number mentioned in the details page

![inconsistentrew](https://user-images.githubusercontent.com/31961530/32233348-d5ca71e8-be62-11e7-9b98-308abcffe7d9.gif)

The textless reviews are currently [filtered out in JS](https://github.com/mozilla/addons-frontend/blob/bce519f694d022820ff1907ebf19b0ec5fdf1720/src/amo/components/AddonReviewList.js#L127-L130) but once we have a proper filter (https://github.com/mozilla/addons-server/issues/5297), let's use it. Among other things, this will fix pagination counts.

This fix should also hide the *Read N* reviews link if there are no reviews with text for the add-on.

**Comment by kumar303** [comment]
I'm adding `filter: without_empty_body` to the API in https://github.com/mozilla/addons-frontend/issues/2608 which will partially close this issue. The *Read N reviews* text is going to require an extra API call though until we can get https://github.com/mozilla/addons-server/issues/5748

**Comment by muffinresearch** [comment]
https://github.com/mozilla/addons-server/issues/5748 is fixed

**Comment by AlexandraMoga** [comment]
@kumar303 I've tested this on -dev but I couldn't see any changes yet.

See https://addons-dev.allizom.org/en-US/firefox/addon/saerch_my_addons/reviews/ 

![empty reviews](https://user-images.githubusercontent.com/31961530/32649934-9dd38e7e-c604-11e7-83c8-b4bb1777a449.gif)

**Comment by kumar303** [comment]
Auto-updates to the dev server were broken due to a security upgrade on one of our services -- sorry about that. The patch should be on dev now. You can also check the [commit hash at this URL](https://addons-dev.allizom.org/__frontend_version__) and compare it to the commit mentioned in the issue (or check [the log](https://github.com/mozilla/addons-frontend/commits/master)).

**Comment by AlexandraMoga** [comment]
@kumar303 the review list title is still displaying the total number of reviews for the add-on, not only the number of written reviews. The below add-on has a total number of 6 reviews out of which only 3 are written. Shouldn't the title read "3 reviews for this add-on" in this case?

![image](https://user-images.githubusercontent.com/31961530/32718703-933431bc-c866-11e7-84c5-ade3a4197adf.png)

**Comment by kumar303** [comment]
Ah, whoops, I missed that part :) A fix is on the way.

**Comment by AlexandraMoga** [comment]
Can't properly verify the last fix until issue described in [#3904](https://github.com/mozilla/addons-frontend/issues/3904) is resolved.

**Comment by AlexandraMoga** [comment]
Verified as fixed in [#3904](https://github.com/mozilla/addons-frontend/issues/3904)
