### ISSUE TITLE
Show an indication of star ratings in the list of all reviews

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2328]
### Describe the problem and steps to reproduce it:

* Go to an add-on detail page that only has one review (entered without text) -- i.e. a star rating.
* Tap on *Read 1 Review*

### What happened?

You see an indication that there is a review:
<img width="324" alt="screenshot 2017-04-28 15 18 14" src="https://cloud.githubusercontent.com/assets/55398/25545800/fa319464-2c25-11e7-9e3e-0c9ed6b9c023.png">

but when you tap on the link, you don't see any reviews:
<img width="327" alt="screenshot 2017-04-28 15 17 53" src="https://cloud.githubusercontent.com/assets/55398/25545807/ffc4a5ba-2c25-11e7-92d5-4c1f7298040f.png">

### What did you expect to happen?

There should be some indication that these star ratings exist. I don't think we should hide individual star ratings.

### Anything else we should know?

@pwalm and/or @jvillalobos do you have any ideas of what should happen here?

Reviews without text are explicitly hidden (also see https://github.com/mozilla/addons-server/issues/4966) but I don't think that's the right thing to do in this case.

Here are some ideas I have:
* We could list star rating reviews and just not show any text. This would at least avoid confusion and could also show which user left which star rating (dunno if that's helpful)
* We could show a summary at the top of the list saying something like '5 reviews without text are hidden'
* At the very least we should make the count of reviews match up -- that will be fixed in https://github.com/mozilla/addons-frontend/issues/2327

**Comment by jvillalobos** [comment]
I would suggest not showing the link unless there are reviews with text. Maybe we need a different place to say how many ratings were involved to get the average.

**Comment by kumar303** [comment]
> I would suggest not showing the link unless there are reviews with text.

Ah, yeah, that's a good place to start. I'll make sure to fix that in https://github.com/mozilla/addons-frontend/issues/2327

**Comment by kumar303** [comment]
This will be tackled in https://github.com/mozilla/addons-frontend/issues/3918 and https://github.com/mozilla/addons-frontend/issues/3919
