### ISSUE TITLE
Add an HTTP mocking library

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#234]
The API tests are using mocks which is a pain. We should mock at HTTP instead of `window.fetch`.

**Comment by muffinresearch** [comment]
This might be worth a look - https://github.com/ctide/fakeweb

**Comment by mstriemer** [comment]
Another option https://github.com/wheresrhys/fetch-mock.

**Comment by muffinresearch** [comment]
Definitely following our discussion on Vidyo today the latter makes more sense given the app is universal and ideally any mocking should work both in the client and server sense.
