### ISSUE TITLE
Disco Pane permissions issues after moving the tab to a new window 

### ISSUE THREAD

**Issue by vasilicamihasca** [mozilla/addons-frontend#2341]
**Steps to reproduce:**

1. Launch Firefox with a clean profile and navigate to about:addons -> Get Add-ons.
2. Choose a webextension and enable the switch button.
3. While permissions pop-up is displayed, right click on “Add-ons Manager” tab and select “Move to New Window” option.
4. Click “Cancel”/“Add” button from permissions pop-up.

**Expected results:**
The webextension installation process is canceled/completed without any issues.

**Actual results:**
- The webextension is not installed/is successfully installed but the switch button becomes unresponsive.
- This issues is no longer reproducible if the page is reloaded

**Additional notes:**
- This issue reproduces on AMO-production using Firefox 55.0a1 (2017-05-03) under Windows 10 64-bit.
- Please see the attached screencasts for this issue:

![animation](https://cloud.githubusercontent.com/assets/18114210/25662539/92b768ee-301d-11e7-805b-2f30b9bfec68.gif)
![animation1](https://cloud.githubusercontent.com/assets/18114210/25662559/a220fe08-301d-11e7-8364-55606953bd89.gif)

**Comment by tofumatt** [comment]
I wonder if this is related to #1435. If #1435 doesn't fix this it seems like a browser bug; I don't think we're failing to handle any events here...

**Comment by muffinresearch** [comment]
@vasilicamihasca Looks like moving to a new window breaks the events tied to the install object in some way. Can you file a bug on bugzilla [1] and reference it here. I could be wrong but this looks like a browser issue.

[1]  https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons%20Manager
