### ISSUE TITLE
Introduce redux-thunk to get implicit dispatching

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2344]
Whenever we dispatch an action we dispatch actions explicitly. This creates complications that can be solved by having implicit access to `dispatch()`.

For example, if you make an API request, you get the API response and dispatch the action. But when the API handler is beginning to load data it might want to dispatch a *begin_load* action. If it fails, it might want to dispatch an *error* action. This would all be easier to do if we could get implicit (rather than explicit) access to the `dispatch()` function. 

Thunk will allow us to do it: https://github.com/gaearon/redux-thunk

**Comment by kumar303** [comment]
Can this replace async-connect?

**Comment by kumar303** [comment]
Oh wait! I think maybe [redux-saga](https://github.com/mozilla/addons-frontend/pull/2195/) will give us the same implicit dispatching mechanism. From their docs:

> You might've used redux-thunk before to handle your data fetching. Contrary to redux thunk, you don't end up in callback hell, you can test your asynchronous flows easily and your actions stay pure.

**Comment by willdurand** [comment]
I guess this should be closed now that redux-saga is in use?

**Comment by kumar303** [comment]
Yeah, saga solved this for the main use case I had in mind when filing the issue.
