### ISSUE TITLE
Expose X_IS_MOBILE_AGENTS header in the app

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2355]
A header `X_IS_MOBILE_AGENTS` is sent to the mobile app via nginx [1]. This can be used to do different things based on the user's preferences or the UA causing them to get the mobile site.

This should be exposed to the app in a generic way so that decisions can be made in components to tune the UX to suit mobile or desktop if not present.

This should be set both in the case of the mamo cookie being set *and* if the mamo cookie is not present and it's a mobile UA.

The first step would be to set something up without relying on it so that it can be tested. We'll also need a good process for emulating this in development too.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1361323

**Comment by kumar303** [comment]
> We'll also need a good process for emulating this in development too.

This part worries me a bit. What do we need to use `X_IS_MOBILE_AGENTS` for that we can't already do?

**Comment by muffinresearch** [comment]
@kumar303 it combines the funtionality of the cookie and or UA string parsing in one place.

**Comment by kumar303** [comment]
oh, ok, so we can remove some custom cookie parsing that the frontend app already does? That sounds good.

**Comment by muffinresearch** [comment]
@kumar303 right now we're not really doing anything with the cookie since this is just a mobile site at the moment. However, if we want to do different things for desktop or mobile (e.g. change amount of data fetched, or withhold functionality for mobile) this provides a good solution.

**Comment by muffinresearch** [comment]
We've not needed this yet so I'm thinking we should just close this out until such point that we do.
