### ISSUE TITLE
Do all pre-loading with redux-saga, not redux-async-connect

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2356]
Once we have [redux-saga](https://github.com/mozilla/addons-frontend/pull/2195), we can do all data pre-loading in a saga. This should allow us to convert all historic `asyncConnect()` decorators into sagas and remove `redux-async-connect`. We also need to remove `redux-async-connect` if we want to migrate to [react-router 4](https://github.com/mozilla/addons-frontend/issues/2161).

**Comment by tofumatt** [comment]
Will fix #2269.

**Comment by tofumatt** [comment]
I have this part-way finished but I'm just gonna bump it one milestone to focus on getting a few more product-y feature-y patches in.
