### ISSUE TITLE
No warning when editing a message with no text

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#2359]
Steps to reproduce:

1. Navigate to a page on your Android device i.e. addons.allizom.org
2. Tap on any extension.
3. Rate that extension with text.(ex. "Test")
4. Rate the same extension again but leave the text box empty.

Expected results:
The user is warned that he can't edit a message with no text.

Actual results:
No warning is displayed, the review has the previously entered text "Test".

Notes/Issues:
Verified on FF53(Android 6.0.1). Issue is reproducing all around AMO servers.
Video for this issue:
![Uploading videotogif_2017.05.09_18.20.27.gif…]()

**Comment by kumar303** [comment]
Why shouldn't you be able to leave a rating without text? This is okay. It means that you have selected a star rating but you have nothing more to say about it. I'm closing it but correct me if I'm wrong here.

**Comment by SVSanta** [comment]
The issue here is that the user is unable to leave an empty comment. When editing a previously added review and deleting all the text from it, after submitting the review, the text is not updated, the review has the previous text and only the start rating changes.
