### ISSUE TITLE
AMO Mobile crashes when adding reviews in landscape mode

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2364]
Prerequisites:
Device : Galaxy S7 Edge, Latest Nightly

Steps to reproduce:
1.On Android, open AMO-dev and try to add some reviews when device is in landscape mode
2.During review writing , scroll up and down in "Write a review" window and also in the AMO page seen in background

Expected results:
Everything should work as expected

Actual results:
Somehow, after randomly scrolling up and down, the AMO from the background becomes active in the same time with "Write a review" window. At this moment the AMO becomes unusable(buttons not working, extremely slow response) and "Logout" button is not displayed anymore. 

Unfortunately, I don't have very clear STRs because I was not able to find a pattern for this bug , but I reproduced it three times today so it is a pretty serious issue given the fact that users have to restart their phones in order to use AMO again(a page refresh will not solve the problem). I will continue to investigate and add more info if I will find something new.

I will add a video in order to show that AMO is unusable and the behavior of "Logout" after steps described above , but I don't have a video with what exactly was pressed to trigger the issue, because as I said, I randomly reproduced it, not even scrolling in the same areas when issue was observed :  
 
![blockrel](https://cloud.githubusercontent.com/assets/1583842/25863950/4fdcd95e-34f6-11e7-89da-20ce95e8039b.gif)

**Comment by muffinresearch** [comment]
@vcarciu you mention this was on nightly - do you see the same on release? Also does this happen in production or just -dev?

**Comment by vcarciu** [comment]
@muffinresearch until now, I was not able to see it on release or prod

**Comment by muffinresearch** [comment]
> @muffinresearch until now, I was not able to see it on release or prod

@vcarciu interesting -  I wonder if it's a bug in nightly? Can you provide the precise version you're running?

**Comment by vcarciu** [comment]
@muffinresearch it is 55.0a1, buildid 20170509100139

**Comment by kumar303** [comment]
If possible, could you attach some output from the console? There are a couple options for how to do this:
* https://addons.mozilla.org/en-us/android/addon/console/
* https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Debugging_Firefox_for_Android_with_WebIDE

**Comment by vcarciu** [comment]
@kumar303 I managed to reproduce again the issue two times today, but unfortunately , I dont think that the logs are relevant. Below you can see latest logs recorded before crash : 
![consolalog](https://cloud.githubusercontent.com/assets/1583842/25999734/eeb910b2-372e-11e7-8712-dbd27cbc08bb.png)

**Comment by muffinresearch** [comment]
@vcarciu does `adb logcat` show anything useful? That might also expose wider errors if those are related to the crash. Note: you might want to redact sensitive data from the output if needed.

**Comment by vcarciu** [comment]
I tried to reproduce again the issue , but last days I was not able to reproduce it, I will try more.

**Comment by muffinresearch** [comment]
@vcarciu I'm going to close this on the basis it doesn't appear to be happening any more, please reopen if that's not the case.
