### ISSUE TITLE
Let's improve code quality [tracker]

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2369]
Here are some specific pain points that I'd like to solve.

* Development
  * ~~Replace async-connect with saga for pre-loading https://github.com/mozilla/addons-frontend/issues/2356~~
  * ~~Use Redux for routing https://github.com/mozilla/addons-frontend/issues/181 (requires upgrading react-router and ditching async-connect)~~
  * ~~Use Jest for running partial tests https://github.com/mozilla/addons-frontend/issues/2372~~
  * ~~Make actions hot reloadable again https://github.com/mozilla/addons-frontend/issues/1096~~
  * ~~Make hot reloading work on functional components https://github.com/mozilla/addons-frontend/issues/99~~
  * Run all "fast" checks in `yarn test`: https://github.com/mozilla/addons-frontend/issues/2281
  * Use Redux in place of setState everywhere https://github.com/mozilla/addons-frontend/issues/1250
  * Convert `setState` for errors to redux dispatching https://github.com/mozilla/addons-frontend/issues/1250
  * ~~Upgrade react-router https://github.com/mozilla/addons-frontend/issues/2161~~
  * Use Enzyme for better interaction tests: https://github.com/mozilla/addons-frontend/issues/1104
  * Start up the dev server faster with only a few locales https://github.com/mozilla/addons-frontend/issues/2389
  * Restart the dev server automatically when configs change https://github.com/mozilla/addons-frontend/issues/2402
  * ~~make mock `calledWith()` assertion failures more helpful https://github.com/mozilla/addons-frontend/issues/2437~~
  * Switch theme install to Redux https://github.com/mozilla/addons-frontend/issues/1936
  * Switch langs with Redux https://github.com/mozilla/addons-frontend/issues/1640
* No surprises
  * Make callApi less surprising: https://github.com/mozilla/addons-frontend/issues/1511
  * ~~Stop tests from reaching the Internet https://github.com/mozilla/addons-frontend/issues/1138~~
  * ~~Remove footgun no-op gettext/ngettext https://github.com/mozilla/addons-frontend/issues/2071~~
  * ~~Fix logging in tests: https://github.com/mozilla/addons-frontend/issues/1373~~
  * Make the tests dispatch actions more like the real app: https://github.com/mozilla/addons-frontend/issues/1371
  * Make reducer code less surprising: https://github.com/mozilla/addons-frontend/issues/1126
  * Split server/client configs explicitly https://github.com/mozilla/addons-frontend/issues/2422
* Organization
  * ~~Re-organize actions/reducers as ducks https://github.com/mozilla/addons-frontend/issues/1299~~
  * ~~Consolidate auth state: https://github.com/mozilla/addons-frontend/issues/1644~~
  * ~~Standardize on component layout: https://github.com/mozilla/addons-frontend/issues/1260~~
* Documentation
  * Re-organize the docs: https://github.com/mozilla/addons-frontend/issues/2223
  * Document how the app runs: https://github.com/mozilla/addons-frontend/issues/1433
* Metrics
  * Start gathering measurements to prevent regressions and improve performance in the future?
* Data
  * Keep app in sync with API as much as possible https://github.com/mozilla/addons-frontend/issues/1971

**Comment by kumar303** [comment]
Time travel: to see route changes we need redux-router (https://github.com/mozilla/addons-frontend/issues/181) which requires an update to react-router (https://github.com/mozilla/addons-frontend/issues/2161) which requires moving off of async-connect (https://github.com/mozilla/addons-frontend/issues/2356)

**Comment by kumar303** [comment]
Run all "fast" when a file changes: https://github.com/mozilla/addons-frontend/issues/2281

**Comment by kumar303** [comment]
Fix action hot reloading: https://github.com/mozilla/addons-frontend/issues/1096

**Comment by kumar303** [comment]
Re-organize project documentation: https://github.com/mozilla/addons-frontend/issues/2223

**Comment by kumar303** [comment]
Time travel: convert `setState` to redux dispatching: https://github.com/mozilla/addons-frontend/issues/1250

**Comment by kumar303** [comment]
Organization: using ducks will make finding action/reducer logic easier: https://github.com/mozilla/addons-frontend/issues/1299

**Comment by muffinresearch** [comment]
I'm going to close this since the record is still here but this is much easier to track and keep up to date  in a project.
