### ISSUE TITLE
Expose /__frontend_version__ URL in nginx

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2370]
The patch in https://github.com/mozilla/addons-frontend/pull/2366 will introduce a new URL served from `addons-frontend` that can be accessed at `https://addons-dev.allizom.org/__frontend_version__`. Let's expose this in nginx.

**Comment by bqbn** [comment]
Is this needed only in -dev, or -stage and -prod as well?

If you just need the convenience of not having to set a cookie when retrieving the version for mobile site, we currently have amo.addons-dev.allizom.org that points to the frontend directly. For example you can do this without having to set the mamo cookie:

```
$ curl https://amo.addons-dev.allizom.org/__version__
{"commit":"2754e5c7faf719f65527fc853afb4243876d7df3","version":"","source":"https://github.com/mozilla/addons-frontend","build":"https://circleci.com/gh/mozilla/addons-frontend/2441"}
```

Although I'm not sure why currently this ```amo.``` prefix only exists for -dev and -stage but not for -prod. We have
* amo.addons-dev.allizom.org for -dev and amo.addons.allizom.org for -stage

but don't have

* amo.addons.mozilla.org for -prod.

/cc @jasonthomas to see if he has more info about history.

**Comment by jasonthomas** [comment]
amo.addons-dev.allizom.org was stood up for testing purposes and there is a issue filed to decommission. https://github.com/mozilla/addons-frontend/issues/2026

**Comment by kumar303** [comment]
Yes, we'd like to use the `__frontend_version__` URL (or any other method) to retrieve the deployed commit in dev, stage, and prod.

**Comment by bqbn** [comment]
Can you try https://addons-dev.allizom.org/__frontend_version__?

I've only deployed it to -dev env for now. Can you verify its working and didn't break anything else? Then I'll deploy it to -stage and -prod later.

**Comment by kumar303** [comment]
> Can you try https://addons-dev.allizom.org/__frontend_version__?

It's working great, thanks.

Did the other URL break? We still need to support the old one (for `addons-server`):

````
curl 'https://addons-dev.allizom.org/__version__'
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
````

**Comment by bqbn** [comment]
As mentioned in the irc channel, -dev is currently broke due to the following error:
```
... ...
for lang in settings.AMO_LANGUAGES)
File "/data/olympia/src/olympia/zadmin/forms.py", line 140, in <genexpr>
for lang in settings.AMO_LANGUAGES)#012KeyError: 'dbl'
```

Maybe try again after the error is fixed?

**Comment by bqbn** [comment]
I have just deployed the nginx change to -stage.

See https://addons.allizom.org/__frontend_version__

**Comment by kumar303** [comment]
Thanks, I verified that it's working on stage.

**Comment by bqbn** [comment]
This is in -prod now.
