### ISSUE TITLE
Dismissed review on mobile playing hide&seek on desktop

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2371]
Steps to reproduce:
1. Find an unreviewed add-on on your Android device 
2. Select some rating stars, but dismiss the review popup (by clicking outside the popup)
3. Go to desktop and find that add-on i.e. https://addons.allizom.org/en-US/android/addon/testrelease05-010-17-1-0/?src=ss

Expected results:
The add-on has the same number of reviews in the header section of add-on details page as in the "Reviews" section.

Actual results:
The add-on has `1 user review` as a link and "This add-on has not yet been reviewed. Be the first!" in the Reviews section below.

Notes/Issues:
- on device the review is counted and the stars are recorded, even if the "submit review" button was not tapped.

Verified on FF53(Android 6.0.1, Win 7). Issue is reproducing on both stage and dev.
Screenshot and video for this issue:
![videotogif_2017 05 11_18 04 48](https://cloud.githubusercontent.com/assets/15685960/25956701/153f91e4-3675-11e7-812e-ba59c83826c1.gif)
![duck](https://cloud.githubusercontent.com/assets/15685960/25956776/4cb97d56-3675-11e7-9bac-5a98edb0159a.png)

**Comment by kumar303** [comment]
This is probably due to caching. Can you try it again but wait 10 minutes before checking it on desktop?

**Comment by ValentinaPC** [comment]
Tried after a day - same results - I don't think is cache.
Add-on: https://addons.allizom.org/en-US/firefox/addon/duckduckbang/?src=ss
Screenshot:
![2017-05-12_0930](https://cloud.githubusercontent.com/assets/15685960/25985919/d73af204-36f5-11e7-8917-2a8113298033.png)

**Comment by muffinresearch** [comment]
@ValentinaPC Isn't this expected behaviour now, since doesn't the addons-server site filters reviews with no comment as per https://github.com/mozilla/addons-server/pull/5227 - or were you logged in as the same user in both cases?

In any case the contradictorary messaging seems odd.

**Comment by ValentinaPC** [comment]
@muffinresearch:
The behavior is to hide the empty reviews, yes, but here I am talking about a dismissed review (with no action on the "submit review" button) and I am also, signed out.
![2017-05-12_1633](https://cloud.githubusercontent.com/assets/15685960/26000262/f12f9882-3730-11e7-88ce-902c099c3153.png)

**Comment by muffinresearch** [comment]
Afaik ratings on the mobile site are submitted even if you don't write text. That was how the UX was defined so that writing text was not a requirement.

I think the filtering out of non-body reviews is not complete and that should be filed for on addons-server.

**Comment by ValentinaPC** [comment]
> Afaik ratings on the mobile site are submitted even if you don't write text

Even if I don't click "submit review" but outside the popup?

**Comment by muffinresearch** [comment]
> Even if I don't click "submit review" but outside the popup?

@ValentinaPC yep. See https://github.com/mozilla/addons-frontend/issues/1812#issuecomment-288983452

**Comment by muffinresearch** [comment]
@ValentinaPC I'm not sure what to do with this bug, I don't think there's anything to do in this repo - but you might want to file for the inconsistent messaging and filtering for the current frontend on addons-server.

**Comment by ValentinaPC** [comment]
I've logged this under add-ons server repo. (https://github.com/mozilla/addons-server/issues/5643)
Closing thins.
