### ISSUE TITLE
Remove the admin app

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2373]
As [discussed](https://groups.google.com/a/mozilla.com/d/topic/addons-dev-internal/ZSbSnYJa9GA/discussion) on `addons-dev-internal`, we decided it's a good idea to remove the admin app. Here's why:

* The code is outdated enough to where adding new features to it would pose a burden
  * A lot of modules were copy/pasted rather than shared so there is a lot of bitrot
* No one is using the admin app in its current form
* It's slowing down our test suite
* If we are able to spin it up again to make it useful, it will be easier to take a fresh approach to it using the current `addons-frontend` idioms and patterns
* We can always reference the old code

**Comment by muffinresearch** [comment]
Blocked by https://github.com/mozilla/addons-frontend/issues/2385
