### ISSUE TITLE
Remove "Ad-on Developer Hub" hyperlink

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#2376]
Steps to reproduce:

1. Navigate to addons.allizom.org.
2. Login with any valid user.
3. Click on "Tools>Developer Hub".
4. Click on the "Ad-on Developer Hub" hyperlink.

Expected results:
The "Ad-on Developer Hub" is not a hyperlink.

Actual results:
The user is redirected to the same page(https://addons.mozilla.org/en-US/developers/).

Notes/Issues:
Verified on FF53(Win 10 64 Bit). Issue is reproducing all around AMO servers.
Picture for this issue:
![link to same page](https://cloud.githubusercontent.com/assets/28138132/26003137/8450dea6-373a-11e7-8c01-213d6c17e7b3.PNG)

**Comment by jvillalobos** [comment]
The Developer Hub is considered a sub-site on AMO, and it's pretty standard for site headers to have a logo / name on the top left leading to the main site page. See the AMO homepage and the GitHub homepage for examples.
