### ISSUE TITLE
Remove the no-op ngettext usage from amo

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2378]
Relates to #2071 but this is just to cover the amo parts so we can get it done ahead of the admin app removal.

This is the problem now:

<img width="480" alt="modules_pour_firefox" src="https://cloud.githubusercontent.com/assets/1514/26008862/6a676f9c-373e-11e7-86f5-b014055834a1.png">

Once fixed the `READ ALL N REVIEWS` should be translated, correctly.

**Comment by muffinresearch** [comment]
QA Notes: 

* Go to any details page using the mobile site and look at the reviews card. 
* The fix means that the "Review all N reviews" text is now translated in non-en locales.

**Comment by ValentinaPC** [comment]
Did you meant "**Read** all N reviews"?

Verified as fixed on AMO-dev Ff53(Android 6.0.1).
Verified all 48 languages.
Postfix screenshots:
![2017-05-22_1413](https://cloud.githubusercontent.com/assets/15685960/26305659/e4f190dc-3ef8-11e7-9a66-39213a1f2a5a.png)
