### ISSUE TITLE
Shutdown admin app in production and deploys.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2385]
See also https://github.com/mozilla/addons-frontend/issues/2373

This is the ops issue to shutdown the admin search app in production and remove it from the deployment pipeline.

**Comment by bqbn** [comment]
I'm not in the ```addons-dev-internal``` group. Can I get an invite to join it so that I can read the discussion?

A few questions in the mean time,

1. Is this the addons-admin.prod.mozaws.net end point we're shutting down?
2. When must this be shut down at the latest? 
3. And just for my information, how do people access the said admin app nowadays?

**Comment by muffinresearch** [comment]
@bqbn I've emailed you re accessing that mailing-list/group.

> Is this the addons-admin.prod.mozaws.net end point we're shutting down?

Yes  

> When must this be shut down at the latest?

No big rush, as soon as convenient.

> And just for my information, how do people access the said admin app nowadays?

They don't use this app in general which is why it's being shut down. The standard amo admin still exists as before though.

**Comment by bqbn** [comment]
Thanks @muffinresearch .

Is it OK to stop pushing for addons-frontend-admin from this week? 

I believe its end point is accessed via VPN, so not pushing for it should have no end-user impact. We'll then remove the cloudformation stacks related to this app in a couple weeks.

**Comment by kumar303** [comment]
> Is it OK to stop pushing for addons-frontend-admin from this week?

Yes, the sooner the better since I'd like to get started with removing the code.

**Comment by bqbn** [comment]
We've decommission the addons-frontend-admin stacks across all 3 envs, as well as removed it from the deployment pipeline.
