### ISSUE TITLE
Start up the dev server faster by limiting the locales

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2389]
It takes 35 seconds on my fast macbook pro to start up the dev server. It might be possible to shorten this by limiting the locales to just a few, like, English and French or something.

The bundle locales get loaded by magic like this: https://github.com/mozilla/addons-frontend/blob/master/src/core/client/base.js#L81

**Comment by willdurand** [comment]
@kumar303 is this still needed given that #5530 has landed?

**Comment by kumar303** [comment]
Probably not.

**Comment by willdurand** [comment]
Perfect, thanks. Closing.

**Comment by kumar303** [comment]
Well, we still have to restart the server every time after upgrading deps with yarn. This is a common occurrence, like, once a day typically.

**Comment by kumar303** [comment]
It would be cool if we could type `r` to reload the server manually (or something like that).
