### ISSUE TITLE
Fail early if keys are missing from an array of JSX elements

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2399]
Would be nice to have something e.g. a lint rule to prevent keys being missed from elements provided via a loop: https://facebook.github.io/react/docs/lists-and-keys.html#keys

Maybe there's an existing lint available to catch it, or some other way to fail harder earlier?

**Comment by muffinresearch** [comment]
Looks like this will do the job https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-key.md

**Comment by kumar303** [comment]
ooh, nice. I wonder if it handles all edge cases in how we pass props to components.
