### ISSUE TITLE
Automatically restart the dev server when config files change

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2402]
When any config file changes, the dev server needs to be restarted. We already have a file watcher so let's try to do this automatically.

**Comment by bobsilverberg** [comment]
This is something I think is worth still trying to do. I did a bit of digging through related issues/PRs and it looks like https://github.com/mozilla/addons-frontend/pull/5777 supposedly fixed this, but as far as I can tell it isn't fixed. Any changes to config files still require a manual restart of the server.

Are others seeing this as fixed, and if not is this still something we want to try to do?
