### ISSUE TITLE
Unsupported red banner in search engines details page at page refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2412]
Steps to reproduce:
1. Load details page for a search tool on your Android device i.e. https://addons-dev.allizom.org/en-US/android/addon/makepolo-search/
2. Refresh the page

Expected results:
Search tool can be installed.

Actual results:
A red banner saying that your browser is not supporting the search plugin is displayed.

Notes/Issues:
- "Add to Firefox" button is grayed out.
- on desktop, in Mobile Site View, the banner is preserved until after page refresh.

Verified on FF53(Android 6.0.1, win 7). Issue is reproducing all around AMO servers.
Video for this issue:
![videotogif_2017 05 22_12 28 49](https://cloud.githubusercontent.com/assets/15685960/26304584/b02cc1b8-3ef4-11e7-8285-ad25845a3570.gif)

**Comment by tofumatt** [comment]
For info: this is because the OpenSearch API detection only happens on the client side and the server props make it seem like the API isn't available (hence the temporary red bar until the API is checked again on the client).

The solution here is to render it without the red bar on the server, exactly how I'll deal with when I go to fix this 😄

**Comment by ValentinaPC** [comment]
This is happening in new AMO desktop pages also.

**Comment by muffinresearch** [comment]
@tofumatt - could you provide some steps on where to start on this as  good first bug?

**Comment by tofumatt** [comment]
Hmm, I would just say that on the server we should not render the error and leave it to the client–I'm not sure we have a path to know if we're on the server or not.

Since I'm not sure about that maybe this isn't a good first bug after all.

**Comment by kumar303** [comment]
Using [Redux devtools](https://addons.mozilla.org/en-US/firefox/addon/remotedev/) would be the easiest way to work on this. You could step back through the actions until you reach the state that shows the red banner, work on the code, and let auto-reloading update the screen.

**Comment by willdurand** [comment]
I think this has been fixed.

**Comment by AlexandraMoga** [comment]
I can't reproduce on either desktop or mobile

![2019-07-08_12-04-09](https://user-images.githubusercontent.com/31961530/60797757-946f9980-a178-11e9-8025-3558d03f036a.gif)
