### ISSUE TITLE
Default text from search field is not removed while typing

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2414]
Steps to reproduce:
1. Load AMO-dev homepage on your Android device https://addons-dev.allizom.org/en-US/android/
2. Type something on the search field

Expected results:
Default text from search field is erased.

Actual results:
Search term is displayed over the default text from the search field.

Notes/Issues:
- did not figure it out what triggers this on order to add more precise STRs
- is not a recent issue, but did not manage to capture it until today;

Verified on AMo-dev FF53(Android 6.0.1)
Video fro this issue:
![videotogif_2017 05 22_12 26 14](https://cloud.githubusercontent.com/assets/15685960/26315220/155796de-3f19-11e7-9189-180efce52983.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC how easy is this to repro. I can't reproduce it on a nexus 7. Can you repro in production?

**Comment by muffinresearch** [comment]
Do you see any js console errors when this behaviour occurs?

**Comment by ValentinaPC** [comment]
@muffinresearch : I wanted to record another thing, while bumped over it again - this is how hard is to reproduce it. :)
Unfortunately I did not had the device connected to my computer to see the console.

**Comment by ValentinaPC** [comment]
I've tried to reproduce this, but not being able to reproduce the **entire thing**: only the part when the cursor is put in front of the magnifier and the default text is not removed, but while typing everything goes as expected.
I think has something to do with changing the languages.
Nothing in the console, for now. :(
Video:
![videotogif_2017 05 25_16 37 56](https://cloud.githubusercontent.com/assets/15685960/26452630/5626325e-4169-11e7-81ce-6ea447b91683.gif)

**Comment by ValentinaPC** [comment]
@muffinresearch : Reproduced it again today using AMO-dev FF53(Android 7.1.2)
From logs:
```
05-29 10:58:09.721 2017-2188/? E/BrcmNfcJni: nfaConnectionCallback: unknown event ????
05-29 10:58:14.929 504-504/? E/SurfaceFlinger: releasePendingBuffer failed: Unknown error -1 (1)
```
Hope it helps!

**Comment by kumar303** [comment]
Thanks for the logs. I didn't see anything obvious in there but here they are again since the pastebin link will expire: 
[9022963.txt](https://github.com/mozilla/addons-frontend/files/1038804/9022963.txt)

**Comment by ValentinaPC** [comment]
I think this is related to #2471 and its root cause, because this is happening again in -dev.

**Comment by ValentinaPC** [comment]
Happening in stage, today.
Video:
![videotogif_2017 07 13_10 36 13](https://user-images.githubusercontent.com/15685960/28155429-5fa479f2-67b7-11e7-97ce-182251582b77.gif)

**Comment by apoorvasingh17** [comment]
Hi, can I work on this issue?

**Comment by tofumatt** [comment]
@apoorvasingh17 You're welcome to work on it though this one seems quite hard to reproduce and will require an Android phone to replicate. Are you able to reproduce the issue locally?

**Comment by apoorvasingh17** [comment]
@tofumatt I guess I will have to pass on this one as I have just started contributing and would like to start off with something easier.

**Comment by tofumatt** [comment]
That’s okay, good thinking. I didn’t want you to get overwhelmed on your first issue. Right now we don’t seem to have a lot of issues filed as good first bugs but I’ll see if I can find some that are good to start with!

**Comment by muffinresearch** [comment]
@ValentinaPC is this still an issue now that the header has be reimplemented?

**Comment by ValentinaPC** [comment]
@muffinresearch : did not see it in the new header.
We can close this as fixed.
