### ISSUE TITLE
Add-on with long name is causing layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2415]
Steps to reproduce:
1. Submit an add-on with long name i.e. https://addons-dev.allizom.org/en-US/android/addon/lastpass-password-manager/?src=search (without spaces)
2. Access its details page

Expected results:
There are no display or layout issues.

Actual results
Add-on name is not truncated or rendered as expected.

Notes/Issues:
- add-on details page: long name causes horizontal scrolling
- listing pages: icon is moved from its place

Verified on FF53(Android 6.0.1). Issue is reproducing on AMO-dev and stage.
Screenshots for this issue:
![untitled](https://cloud.githubusercontent.com/assets/15685960/26316777/08294926-3f1e-11e7-9bf4-36210b48cfb0.png)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Android 7.1.2)
- add-on details page for add-on with long name was fixed
![yes-details](https://cloud.githubusercontent.com/assets/15685960/26495395/1e4b748e-422c-11e7-8c5b-c5f55983fc94.png)
- add-on listing page was not fixed
![nor-listing](https://cloud.githubusercontent.com/assets/15685960/26495411/23ef76e2-422c-11e7-83cb-7cf0916f3ab3.png)
- there is also "all reviews" page where this needs fixing
![no-allrev](https://cloud.githubusercontent.com/assets/15685960/26495419/28730b7a-422c-11e7-80b5-2abeb4b3989b.png)

Reopening.

**Comment by muffinresearch** [comment]
@tsl143 hi - looks like there's a couple more issues that need fixing that require additional styling - would you be interested to take that on?

**Comment by tsl143** [comment]
@muffinresearch Not a problem I will do that :)

**Comment by tsl143** [comment]
@muffinresearch Fixed the rating section in current PR. 
The search listing page was fixed in previous PR,
I already added `word-wrap: break-word` in src/core/css/SearchResult.scss.(Also attached screenshot before).

**Comment by tsl143** [comment]
Okay now this is interesting, on chrome(Android it works as desired) but on firefox it word wraps but issue with width, I will try to figure the compatible solution.
![photo6145460660381788078](https://cloud.githubusercontent.com/assets/5318732/26509158/35ff9012-4275-11e7-8729-f1ba3cc721be.jpg)
![photo6145460660381788079](https://cloud.githubusercontent.com/assets/5318732/26509157/35fd8c2c-4275-11e7-8f3b-a5e20d94dbe1.jpg)

**Comment by tsl143** [comment]
Fixed the compatibility issue by adding width to non floating box (but interestingly the width of text is auto handled by Chrome unlike Firefox [self note for compatibility])

**Comment by tsl143** [comment]
This issue is already fixed in new layout, can we close it already? @ValentinaPC

**Comment by tofumatt** [comment]
Issue closed via the design updates.

**Comment by vcarciu** [comment]
This is still not fixed in "All writen reviews page" : 
![allwrittenrew](https://user-images.githubusercontent.com/1583842/27867018-1f81ef2e-61a1-11e7-9da8-bc774653dc94.png)

**Comment by tofumatt** [comment]
Good catch, thanks :-)

**Comment by tsl143** [comment]
https://github.com/mozilla/addons-frontend/pull/2720

![bug](https://user-images.githubusercontent.com/5318732/27990967-55f10b30-6485-11e7-810c-31396b15ac30.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![screenshot_20170710-183718 1](https://user-images.githubusercontent.com/1583842/28026469-dab261ce-659e-11e7-8b49-b328232418f6.png)
