### ISSUE TITLE
"File an issue" link from a 404 page isn't redirecting correctly

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2417]
Steps to reproduce:
1. Access page https://addons-dev.allizom.org/en-US/android/mobile/  on you Android device
2. Click on the "file an issue" link

Expected results:
Link redirects to `https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Contact`

Actual results:
Link redirects to Github.

Notes/Issues:
Verified on AMO0-dev FF53(Android 6.0.1).
Video fro this issue: 
![videotogif_2017 05 23_10 23 12](https://cloud.githubusercontent.com/assets/15685960/26342888/8464007e-3fa2-11e7-959c-a948af2b3813.gif)

**Comment by tsl143** [comment]
@ValentinaPC Isnt that a desired functionality as I get following form (given I was already logged on to github)?

<img width="776" alt="screen shot 2017-05-24 at 8 27 54 pm" src="https://cloud.githubusercontent.com/assets/5318732/26409966/9a9ffc12-40bf-11e7-9be7-af8e8558ecde.png">

**Comment by tofumatt** [comment]
We want the user to get to a landing page that directs them to the right place to raise issues depending on the problem. Right now we get a lot of users filing issues in our repo for add-on issues that should be raised with authors, info on missing add-ons, etc. So no, we shouldn't direct them to GitHub first, but it is an option on the page we should direct them to.

**Comment by tofumatt** [comment]
Oh shoot, I'm sorry. I got confused between the usual "report an issue" links we have that should go to MDN and these explicitly labelled "file an issue" links which *should* go to GitHub. Sorry about this, the GitHub link was right all along.

**Comment by tsl143** [comment]
No problem :)
