### ISSUE TITLE
Privacy policy URL isn't prefixed

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2419]
### Describe the problem and steps to reproduce it:
The "Privacy policy" link on https://addons-dev.allizom.org/en-US/android/addon/url-fixer/?src=ss and any other page is missing client app and locale.

Privacy Policy links to https://addons-dev.allizom.org/addon/url-fixer/privacy/ but should link to https://addons-dev.allizom.org/en-US/android/addon/url-fixer/privacy/

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF53(Android 6.0.1) and the URL from the privacy policy link has a locale.
@tofumatt - What should be checked here for "client app"? Thanks!
Postfix video:
![videotogif_2017 05 25_10 39 11](https://cloud.githubusercontent.com/assets/15685960/26441211/48b6ace2-4138-11e7-83f7-0e8db89d51ff.gif)

**Comment by tofumatt** [comment]
The client app is "firefox", "android", etc. It should contain that as well.

**Comment by ValentinaPC** [comment]
> The client app is "firefox", "android", etc. It should contain that as well.

I thought about that, but I was not able to reproduce the initial issue in production, so I was wondering if I missed something.
