### ISSUE TITLE
Unify logging

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2423]
I'm not sure how much value there is in special server vs client-side logging. 

Let's decide whether this is still needed and consolidate on a single logging solution that works the same in node and browsers.

This is best done after the change to use Jest.

**Comment by kumar303** [comment]
For the server, we just need to format logging for the new hotness: https://github.com/mozilla/addons-frontend/issues/2025

**Comment by muffinresearch** [comment]
Looks like addons-linter/dispensary moved to pino from bunyan https://github.com/pinojs/pino which side-steps the dtrace-provider issue and also looks like it might have some ways to support browser logging.

**Comment by willdurand** [comment]
We should try to fix this in Q3 and also start formatting logs correctly (#2025).

**Comment by willdurand** [comment]
@muffinresearch why do we want to change our logging layer again? I haven't found the dtrace-provider issue and our current setup is both simple and fully functional. This issue is a blocker for #2025.

**Comment by muffinresearch** [comment]
It's using webpack magic to do a split between server and client and it seemed like it might be a good idea to remove this if it was possible to consolidate on a single solution that worked without dependency wrangling. If it's not causing problems and @kumar303 is ok with leaving this then we can focus on more important issues.

**Comment by willdurand** [comment]
Removing the webpack magic is a fair point.

**Comment by willdurand** [comment]
Turns out that it was rather simple to switch and also bunyan does not seem to be maintained anymore...

**Comment by vcarciu** [comment]
@willdurand : 
Can you please add some STRs to this bug or mark it as "qa: not needed" ?

**Comment by vcarciu** [comment]
@willdurand : thanks. Logs are still working: 
![logs](https://user-images.githubusercontent.com/1583842/43826687-9bd7b06a-9b00-11e8-92d2-923a06c16009.png)
