### ISSUE TITLE
Create a desktop Add-on details page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2430]
Create a desktop version of the add-on detail page according to mocks.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev using desktop and mobile under FF53(Win7, Android 7.1.2) and seems like there is a situation with ratings on both pages.
Please see screenshots:
![desktop](https://user-images.githubusercontent.com/15685960/27130476-11bd4890-510f-11e7-8ab6-73c7ee8c28cb.png)
![mobile](https://user-images.githubusercontent.com/15685960/27130480-14b38762-510f-11e7-876c-3a4b2e62566d.png)

**Comment by tofumatt** [comment]
Could you please add links to those pages so I can check the error? Thanks.

**Comment by ValentinaPC** [comment]
It is on every add-on detail page.
Examples:
- on desktop in View Mobile Site mode: https://addons-dev.allizom.org/en-US/firefox/addon/fb-purity-cleans-up-facebook/
- on mobile: https://addons-dev.allizom.org/en-US/android/addon/facebook-phishing-protector/?src=ss

**Comment by tofumatt** [comment]
The placement of the review/user info on mobile is correct; I've moved it and I think it works better.

On desktop I can't recreate your screenshot. The page looks like this to me:

![screen shot 2017-06-14 at 13 47 14](https://user-images.githubusercontent.com/90871/27132786-03642e6e-5108-11e7-9832-01a8b837b898.png)

**Comment by ValentinaPC** [comment]
> The placement of the review/user info on mobile is correct; I've moved it and I think it works better.

So is not like in the screenshot from https://github.com/mozilla/addons-frontend/pull/2551 ?


> On desktop I can't recreate your screenshot.

Yeah, sorry, my bad. This is because is happening only for browser width over 1540px.

**Comment by tofumatt** [comment]
Correct, I've updated the page. Sorry about that!

Gotcha, I'll try it with a very large viewport and will report back 😄

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO Ff53(Win 7).
Postfix screenshot:
![2017-06-15_1517](https://user-images.githubusercontent.com/15685960/27181088-b1c032ce-51de-11e7-827a-6c66babd74d5.png)
