### ISSUE TITLE
Integrate greenkeeperio/greenkeeper-lockfile

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2431]
Looks like greenkeeper now have a package for keeping the yarn.lock up to date. 

Would be nice to look at integrating that on travis. See https://github.com/greenkeeperio/greenkeeper-lockfile for details.

**Comment by willdurand** [comment]
No need to do this anymore, it is built-in! https://greenkeeper.io/docs.html#lockfiles
