### ISSUE TITLE
Create a Desktop Header (for detail and landing pages)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2436]
Create a desktop header for inner/detail and one for landing pages.

### Landing Pages
<img width="514" alt="screenshot 2017-05-25 16 05 20" src="https://cloud.githubusercontent.com/assets/90871/26456073/f6cf6780-4163-11e7-8fe8-6056ce901104.png">

### Detail Pages
<img width="516" alt="screenshot 2017-05-25 13 43 22" src="https://cloud.githubusercontent.com/assets/90871/26450588/240d5072-4150-11e7-8648-fd926e19cc0c.png">

**Comment by ValentinaPC** [comment]
This is partially on AMO-dev FF52(Android 7.1.2).
- new "Developer Hub" button in the header which redirects correctly, but with no way to get back to homepage.
- new color for header also
- "purple" color and shadow applied to the options of Sort menu 

@tofumatt : Should this be checked on Desktop? On Desktop with mobile view? On device while "Request desktop site" option is checked? 
I am a bit confused on where and how these should be checked.
Thanks in advance!

**Comment by tofumatt** [comment]
* "with no way to get back to homepage" not sure what that means. The back button should work?
* yes there are a lot of new styles, they're in the mocks in assets/
* wasn't sure about that, I should have a look

This should really be checked on desktop and mobile I guess... the styles will affect both but they stem from design updates we're calling "Desktop" because they have new desktop-sized layouts. But they'll affect mobile as well.

**Comment by ValentinaPC** [comment]
> "with no way to get back to homepage" not sure what that means. The back button should work?
 
"Back" button from the browser, but nothing in the AMO page.

This issue still requires parts to be implemented, so I cannot mark it verified, yes?

**Comment by tofumatt** [comment]
Well, it's up to the dev hub to have a "back to AMO" page, that's not really in the scope of this issue.

But I think I can take a look at the sort button. Can you post a screenshot?

**Comment by ValentinaPC** [comment]
![2017-06-07_1510](https://user-images.githubusercontent.com/15685960/26877706-783b26ea-4b93-11e7-83c0-ebccd5608271.png)
Live, the "purple" shadow looks more obvious. But here too we can see a different color for arrow/sort icon and the sort filters.

**Comment by tofumatt** [comment]
Ah, gotcha. That is a regression from modifying the button stuff I'm pretty sure. I will fix that in a follow-up patch, I'll re-open for now.

**Comment by ValentinaPC** [comment]
@tofumatt : please take into consideration that the "shadow" is olse present on the page nav arrows.
Please see the screenshot:
![2017-06-09_1535](https://user-images.githubusercontent.com/15685960/26975633-46be9132-4d29-11e7-8551-1bc65603e006.png)

Sorry for late notice.

**Comment by tofumatt** [comment]
@ValentinaPC No problem, I'll add that to #2534.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Postfix screenshots:
![nav](https://user-images.githubusercontent.com/15685960/27022663-a03ada7e-4f57-11e7-91e9-205c51495081.png)
![sort](https://user-images.githubusercontent.com/15685960/27022662-a039bd7e-4f57-11e7-9eea-177cadd65cee.png)
