### ISSUE TITLE
Replace sinon calls wrapped with expect to use sinon.assert directly

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2437]
If we wrap things like `stub.calledWith('blah')` with assertions then it hides useful error messages that tell us that the args were wrong etc.

A better solution is to cover to using [sinon.assert](http://legacy.sinonjs.org/docs/#assertions) directly OR use something like [sinon-jasmine](https://github.com/froots/jasmine-sinon). 

I have already tried the latter and it appears to be out of date so it might be easier just to use sinon.asserts for now.

**Comment by tofumatt** [comment]
We've often tended to use `stubFunction.firstCall.args[0]` to get around this which is a less cool API, so being able to use `calledWith()` directly sounds 👍

**Comment by muffinresearch** [comment]
Here's an example of this in action:

<img width="771" alt="node" src="https://cloud.githubusercontent.com/assets/1514/26488989/745faedc-41fd-11e7-91ec-1ae0c14a3899.png">

**Comment by kumar303** [comment]
We have converted most calls to `sinon.assert` but you can see the stragglers here: https://github.com/mozilla/addons-frontend/search?utf8=%E2%9C%93&q=calledWith&type=

**Comment by willdurand** [comment]
In addition to that, we do not need to use `sinon.assert.called()` when we use `sinon.assert.calledWith()` on the same spy, in the same test case.
