### ISSUE TITLE
Create a better, more flexible button element using the new specs

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2438]
Our current usage of "button" elements is a bit all-over-the-map and leading to it being frustrating to add new ones for the desktop header. I have specs for all possible button colours and sizes and we should make ours consistent and a bit easier to work with.

This might mean using some common classes for them rather than our current mixins directly which leads to slightly different buttons everywhere...

**Comment by tofumatt** [comment]
We never really did #1225 so this is effectively that...

**Comment by SVSanta** [comment]
Tested the pagination buttons for: Themes, Extensions, Search, Review and other languages.
Are there any other pages where buttons were improved?
Verification screenshot:
![buttons merged0](https://user-images.githubusercontent.com/28138132/27138000-1fbedbfc-5128-11e7-84e1-33074ac025ca.png)

**Comment by tofumatt** [comment]
The buttons for "Tap to preview" on the themes page and the "Add to Firefox" buttons on an Open Search plugin are also buttons.
