### ISSUE TITLE
Convert search and add-on detail page to sagas

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2442]
Instead of using async-connect to pre-load the add-on detail page, we should use a saga. As part of this, let's also stop populating the add-on detail page with data from search results because it will fix bugs like https://github.com/mozilla/addons-frontend/issues/2435

Steps to test this for QA:
* Load the add-on detail page, make sure it works. 
* Try refreshing the detail page, make sure it still works.
* Try searching for an add-on and navigating to its detail page, make sure it works.

**Comment by kumar303** [comment]
This is a step towards https://github.com/mozilla/addons-frontend/issues/2356

**Comment by kumar303** [comment]
I moved this to https://github.com/mozilla/addons-frontend/issues/2574 and https://github.com/mozilla/addons-frontend/issues/2573 . I'll do the search conversion later once I catch my breath.

**Comment by vcarciu** [comment]
Verified all scenarios from description and more other around and everything looks fine.
Marking as verified.

**Comment by kumar303** [comment]
whoops, sorry. I closed this because it was invalid but I forgot to change the flags. No code change landed.

**Comment by vcarciu** [comment]
I will remove the verified label then and verify same scenarios for the other issues. Thanks
