### ISSUE TITLE
Configure tests that don't require jsdom to use the node env

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2445]
Jest provides a way to run tests within the node env instead of the jsdom environement. To do that you just need to add a special comment at the top of the file:

```
/**
 * @jest-environment node
 */
```

It might speed things up to specify that for all the tests that don't need a dom.

See also https://facebook.github.io/jest/blog/2017/05/06/jest-20-delightful-testing-multi-project-runner.html#new-improved-testing-apis under "Custom environment".

**Comment by muffinresearch** [comment]
This also requires removing the window from here: https://github.com/mozilla/addons-frontend/blob/master/src/core/client/logger.js#L11

**Comment by kumar303** [comment]
I took a quick look at this and I didn't see any speed-up. Maybe jsdom is only applied lazily? I didn't spend much time on it so maybe I missed something.

**Comment by muffinresearch** [comment]
I don't think this issue is worth keeping around especially if there's no speed-up.
