### ISSUE TITLE
Fix missing coverage for the base server

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2447]
With Jest the super-test files have been removed. As a result of that and tracking the complete coverage across the code base we're now missing some coverage in the main server app.

To fix this we either need to:

* Re-organize the server code and make sure every line is covered
* Re-instate some of the supertest tests (the new version has promise support so supertest-as-promised would not be needed). 

The downside of the latter is speed + you need to build the code. Not going this route might also mean that most of the combined build scripts could be removed.

I think re-organizing and testing the server logic in more discrete tests is the way to go - but this is definitely one that's open for discussion.

**Comment by kumar303** [comment]
Is this really a p2? The coverage was always missing, we were just pretending it wasn't

**Comment by muffinresearch** [comment]
> Is this really a p2? The coverage was always missing, we were just pretending it wasn't

Whilst it was skipped from a perspective of the coverage tool the old super-test based server tests covered the most important pieces of it.

**Comment by muffinresearch** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/1961
