### ISSUE TITLE
Allow coveralls/coverage to pass with existing coverage for now

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2454]
After landing Jest the build is flagged as broken because coverage is failing. This is causing issues like #2452 to be filed because Greenkeeper thinks the build isn't passing. While #2447 is ultimately what we want, for now we should configure Coveralls to not fail as long as we don't introduce more uncovered code. We should ignore certain files, I guess, for now.

**Comment by kumar303** [comment]
well, huh. I think you have to be the owner of the repo (maybe?) to set the coverage threshold https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-121078445

Supposedly there should be some settings at the bottom left of this page but I don't see it (when signed in) https://coveralls.io/github/mozilla/addons-frontend

@muffinresearch do you have special powers to see this setting?

We just need to adjust it to 94%

**Comment by muffinresearch** [comment]
I've set it to 94%.

**Comment by muffinresearch** [comment]
It's now 90% because coveralls went a bit crazy.
