### ISSUE TITLE
Clean-up env vars in the package.json scripts

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2457]
I think we might be able to remove most of that. Jest should default to NODE_ENV=test env by itself afaik.

If we do then removing the npm-better-run might be a good move. Anything that still needs it could move to the `bin` directory.

**Comment by willdurand** [comment]
We use `development-amo.js` to configure the `yarn amo` env (docker/local). If we remove the en variables for the `amo:dev` command, this file gets used and we don't leverage the -dev AMO env anymore. Thus, we cannot remove all the env vars, only some of them.

**Comment by muffinresearch** [comment]
Closing this, as I don't think there's much need to make these changes.
