### ISSUE TITLE
Action button has poor contrast

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2461]
### Describe the problem and steps to reproduce it:
In the specs for the desktop pages, the button background/text colour combo fails the [WebAIM contrast checker](http://webaim.org/resources/contrastchecker/):
<img width="711" alt="screenshot 2017-05-26 15 50 02" src="https://cloud.githubusercontent.com/assets/90871/26499591/217ef514-422b-11e7-87f2-e1420197cac4.png">

I personally find the button quite hard to read at the small size. Other buttons have similar issues:
<img width="661" alt="screenshot 2017-05-26 15 53 37" src="https://cloud.githubusercontent.com/assets/90871/26499718/86052594-422b-11e7-94ab-05362d21a6b1.png">

White text helps but generally many of the buttons have issues with the backgrounds.

### What happened?
I found the buttons hard to see.

### What did you expect to happen?
I could see the buttons; they at least pass the AA test.

**Comment by tofumatt** [comment]
Using white text and the type colour for a shadow seems to yield the most readable button. Here's a comparison of buttons:

### Black text, no shadow
<img width="690" alt="screenshot 2017-05-26 16 02 53" src="https://cloud.githubusercontent.com/assets/90871/26500185/e65f9586-422c-11e7-9ae3-177d3ba2d7e5.png">

### White text, no shadow
<img width="682" alt="screenshot 2017-05-26 16 02 19" src="https://cloud.githubusercontent.com/assets/90871/26500208/fe4eb136-422c-11e7-8955-2c749c21e766.png">

### White text, shadow
<img width="682" alt="screenshot 2017-05-26 16 02 12" src="https://cloud.githubusercontent.com/assets/90871/26500213/036aaca6-422d-11e7-89dc-8b38f8d1a571.png">

**Comment by pwalm** [comment]
Colours were recently updated to follow the Photon Design Guide, which pass colour contrast guidelines. Will provide updated file!

**Comment by tofumatt** [comment]
Ah sweet, I missed that! Please ping me when the assets file is updated and I'll update my specs 😄  👍

**Comment by pwalm** [comment]
Does the photon colour palette address this issue, @tofumatt ?

**Comment by tofumatt** [comment]
I think they do; if not #3111 will bring it up so I'll close this out for now.
