### ISSUE TITLE
Store current addon type for addon/context in store

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2468]
### Describe the problem and steps to reproduce it:
The new header (#2436) highlights Explore, Extensions, or Themes based on the URL currently, but it should really use the current "context" of add-on type we're viewing. Most of the time our URLs provide the context for the add-on type we're exploring (Extension or Theme) but once we go to the Add-on detail page that info isn't in the URL so we should store it (or check it from the `SectionLinks` component) and use that to inform which link we highlight.

**Comment by vcarciu** [comment]
Can you please add some STRs to this issue or mark it as "qa: not needed" ?

**Comment by tofumatt** [comment]
You should see the explore, extensions, and themes in the header and in the search placeholder.

**Comment by vcarciu** [comment]
@tofumatt : then we can mark this as Verified after responding to questions from https://github.com/mozilla/addons-frontend/issues/2477

**Comment by tofumatt** [comment]
Questions answered, cheers!

**Comment by vcarciu** [comment]
Thanks!
