### ISSUE TITLE
Tapping is only working after second attempt on AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2470]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/android/ on your Android device
2. Tap on "Extensions"

Expected results:
"Extensions" page is loaded.

Actual results:
A blue loading bar is displayed, while loading the "Extensions" page is not finalized.

Notes/Issues:
- refreshing the page loads the desired page.
- happens with every link from homepage, or extensions/themes categories
- tapping again on the item, loads the page
- no errors displayed in the console

Verified on AMO-dev FF53(Android 7.1.2). Issue is only reproducing on DEV.
Video for this issue:
![videotogif_2017 05 29_10 29 58](https://cloud.githubusercontent.com/assets/15685960/26540450/3947947c-445a-11e7-8e78-c9adb63adaf1.gif)

**Comment by kumar303** [comment]
I can reproduce it too (on Android) but not in Firefox Nightly

**Comment by kumar303** [comment]
I think this is the same as the missing `Intl` problem noted in https://github.com/mozilla/addons-frontend/issues/2471

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Tapping is working as expected all around AMO pages on device.
Postfix video:
![videotogif_2017 05 31_12 45 42](https://cloud.githubusercontent.com/assets/15685960/26626458/f7547bc8-45ff-11e7-87d4-c450780aea84.gif)
