### ISSUE TITLE
Installation is not working for themes/extensions on AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2471]
Steps to reproduce:
1. Load any theme/extensions details page on your Android device i.e. https://addons-dev.allizom.org/en-US/android/addon/shamrocks2/
2. Observe the install button

Expected results:
The installation button is enabled.

Actual results:
The installation button is disabled.

Notes/Issues:
- not reproducing on desktop while in Responsive Design Mode - View Mobile Site
- only reproducing on AMO-dev
-  "tap to preview" button is not working also
- all `prefs` are set

Verified on FF53(Android 6.0.1, 7.1.2).
Video for this issue:
![videotogif_2017 05 29_12 41 06](https://cloud.githubusercontent.com/assets/15685960/26544970/9b0fe5ee-446c-11e7-9360-a1765ffcb776.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC based on the version you're quoting this isn't nightly. Release doesn't allow the prefs for testing.

Please re-open if this is a problem on nightly.

**Comment by muffinresearch** [comment]
I'm going to re-open this because it suggests that something might be broken causing the fallback buttons not to be displayed.

**Comment by muffinresearch** [comment]
This is caused by Intl not being available on FF Android.  See also https://bugzilla.mozilla.org/show_bug.cgi?id=1215247

```
ReferenceError: Intl is not defined
```

The fix will be to fallback to our previous solution for this case. It's apparently coming in 54.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2).
Installation is working for add-ons and themes.
Postfix video:
![videotogif_2017 05 31_12 27 37](https://cloud.githubusercontent.com/assets/15685960/26625501/f485db24-45fc-11e7-9f7b-508915df0b17.gif)

**Comment by ValentinaPC** [comment]
This is happening again, together with #2472 .

**Comment by ValentinaPC** [comment]
Was logged - #2521
