### ISSUE TITLE
"Read more" link is not available in add-on details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2472]
Steps to reproduce:
1. Load an add-on details page that has a long description on your device i.e. https://addons-dev.allizom.org/en-US/android/addon/quitnow/
2. Check out the "Read More" link

Expected results:
Link is displayed and working.

Actual results:
Link is not displayed.

Notes/Issues:
Verified on FF53(Android 6.0.1, 7.1.2). Issue is **only** reproducing on dev.
Video for his issue:
![videotogif_2017 05 29_16 36 42](https://cloud.githubusercontent.com/assets/15685960/26551887/5b997a8a-448d-11e7-92ae-f351b1f29228.gif)

**Comment by kumar303** [comment]
Weird. I can't reproduce this on Firefox 54 desktop (using responsive mode).

**Comment by tofumatt** [comment]
It's because, seemingly, as @muffinresearch pointed out, Intl isn't available on android. It's breaking a lot of things that rely on client-side JS.

Matthew Riley MacPherson

**Comment by muffinresearch** [comment]
Same issue as noted in https://github.com/mozilla/addons-frontend/issues/2471

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Postfix screenshot:
![2017-05-31_1223](https://cloud.githubusercontent.com/assets/15685960/26625195/09744f58-45fc-11e7-97bc-e80b8ce4c073.png)
