### ISSUE TITLE
Add "Explore", "Extensions", and "Themes" to header/search context

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2477]
We need the "Explore", "Extensions", and "Themes" links in the header and for them to be contextually active based on where you are on the site.

To do this we'll need to implement #2468 first.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Postfix screenshots:
![header](https://user-images.githubusercontent.com/15685960/27170562-0457c006-51b7-11e7-8663-865038459a07.png)

@tofumatt : I have 2 questions for you
1. "empty" search is not possible while in Explore, but possible while in Extensions or Themes - is this ok?
2. while in Extensions or Themes homepages, the titles of every group of extensions (Featured extensions for example) is not centered - is this intended?

Thanks!

**Comment by tofumatt** [comment]
To answer:

1. Ah yes, this is because technically searching from the extensions and themes pages, `type=extension` is added to the search query and thus the component doesn't see it as an empty search. I think this is okay... but if you wanted to file an issue about it that's alright, we could improve the handling of that
2. Yes, the new mocks shifted the headers in the cards to the left rather than centre.

**Comment by ValentinaPC** [comment]
> Yes, the new mocks shifted the headers in the cards to the left rather than centre.

Shouldn't be aligned with extensions names?

Thanks for your reply!

**Comment by tofumatt** [comment]
When #2560 is complete the extension name/content should look as intended but the header is where it is supposed to be as per the mocks. It looks a bit odd now but should be fixed once #2560 is ready.
