### ISSUE TITLE
Clean up stylelint deprecation warning

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2482]
Running yarn stylelint reveals the following message:

```
Deprecation Warning: 'max-nesting-depth's' "at-rules-without-declaration-blocks" option 
has been deprecated and in 8.0 will be removed. Instead use the "blockless-at-rules" option. 
See: https://stylelint.io/user-guide/rules/max-nesting-depth/
```

Would be good to replace the relevant rules as per the message details.

**Comment by muffinresearch** [comment]
Stylintrc is here: https://github.com/mozilla/addons-frontend/blob/master/.stylelintrc

**Comment by wagnerand** [comment]
Mentor: @muffinresearch 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.
