### ISSUE TITLE
Subresource integrity checks fail when building production locally

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2487]
### Describe the problem and steps to reproduce it:
Followed https://github.com/mozilla/addons-frontend/#building-and-running-services and used Charles to serve the Add-ons CDN to my local machine, running an HTTP server in `dist/`.

The code builds and the server starts and accepts/returns requests, but fails to load CSS and JS.

I've checked and the files exist. I have unmodified configs and no local configs.

I've successfully done this in the past.

### What happened?
The page is loaded without resources.

### What did you expect to happen?
The page loads with CSS/JS.

### Anything else we should know?
This is blocking #2409 because I need to test the prod version to test it.

Should be noted this happens on master.

**Comment by kumar303** [comment]
Before we can allow `local-production-*` configs we have to fix all of the tests that rely on the production config.

**Comment by tofumatt** [comment]
Yeah, that's fine, but using them to build the app locally for testing a production issue (as I needed to for #2409) was handy... so even if it's just for creating it then immediately deleting it, we should have clear docs.
