### ISSUE TITLE
Create a test helper for common API dispatch store

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2494]
We have been moving tests to use `dispatch` instead of raw state, usually on an ad-hoc basis, which has led to this block of code often being repeated:

```js
import createStore from 'amo/store';
import { setClientApp, setLang } from 'core/actions';

const { store } = createStore();
store.dispatch(setClientApp('android'));
store.dispatch(setLang('fr'));
```

It's good that we're doing this because it's safer and more realistic than raw state (eg `signedInApiState`) but we should abstract this store/state into a test helper because we need it nearly everywhere and it'd be handy to be able to load up a freshly-created store like this instead:

```js
import { testStore } from 'tests/client/helpers'; // or whatever

const store = testStore();
console.log(store.getState().api);
// => would output { clientApp, lang, etc. }

// It could even take *specific* args like: 
const store = testStore({ clientApp, lang });
// Which would dispatch `setClientApp` and `setLang` with custom values,
// rather than using raw state.
```

**Comment by kumar303** [comment]
Yeah, a helper to dispatch sign-in actions would be awesome

**Comment by kumar303** [comment]
heh, I was searching my awesome bar for this and found a similar issue (this is more to convert everything over): https://github.com/mozilla/addons-frontend/issues/2000

**Comment by kumar303** [comment]
This got fixed in https://github.com/mozilla/addons-frontend/pull/2520
