### ISSUE TITLE
setCurrentUser action is missing coverage

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2495]
### Describe the problem and steps to reproduce it:
Not sure why but `setCurrentUser` in `core/actions` is missing coverage and it's bugging me.

**Comment by tofumatt** [comment]
Actually it looks like we don't use this function (anymore). I'm guessing it's related to the removal of the `admin` app but we didn't notice because we're forgiving with coverage!

I think this can just be removed, testing locally to verify then ditching it.

**Comment by kumar303** [comment]
Ah, whoops. I agree -- looks like this was just for admin.

**Comment by kumar303** [comment]
I took a look at the coverage report to make sure there wasn't anything else admin-related. I didn't see anything.
