### ISSUE TITLE
Convert .amo-link <a> in Disco Pane to be a <Button>

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2502]
This is largely a note-to-self: there's a link tag that is effectively a button and we should just convert it. It's at https://github.com/mozilla/addons-frontend/blob/master/src/disco/containers/DiscoPane.js#L132

I'll do this after #2478 lands...

**Comment by willdurand** [comment]
This has been fixed, apparently... I cannot find the link anymore. L132 is a button, so I guess everything is fine.
