### ISSUE TITLE
Are we using the new puzzle icon in the header?

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2509]
I know there was talk of wanting UX sign-off on it before Tuesday's tag as once #2436 lands it will be on the live mobile site too.

I've taken it out of the mocks for now but if it's good I'll put it back in, either in that patch if it's still open or in a follow-up patch.

**Comment by tofumatt** [comment]
### Old
<img width="310" alt="screenshot 2017-06-02 16 05 17" src="https://cloud.githubusercontent.com/assets/90871/26731852/4fb1d83e-47ad-11e7-90c1-ae1f46c35283.png">

### New
<img width="304" alt="screenshot 2017-06-02 16 04 46" src="https://cloud.githubusercontent.com/assets/90871/26731856/54331558-47ad-11e7-961c-e82ee2b31d28.png">

**Comment by tofumatt** [comment]
PS I really like the icon and think it's sort of adorable, even though I do love the puzzle fox too.

**Comment by pwalm** [comment]
New puzzle icon is nixed, proceed with the old puzzle icon.

**Comment by tofumatt** [comment]
Ten four, old puzzle icon remains!
