### ISSUE TITLE
Categories page does not surface API errors.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2516]
Locally if the local API isn't running directly reloading a category page (/en-US/android/extensions/)  results in a 200 with no results. There is also no error message shown to indicate something has gone wrong.

I would expect this to be a 500 for a reload, and both server + client-side requests should at least show an error page.

**Comment by muffinresearch** [comment]
Not sure if this has always done this or if it's a side-effect of the saga implementation?

**Comment by tofumatt** [comment]
It’s a saga one I believe, though it SHOULD say “no categories found”. So something isn’t 100% right, I’ll have a look.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by tofumatt** [comment]
You would need to run the site locally to get this to work I think, running it, loading a categories page, shutting down the API server, and then refreshing it. I think this is likely a non-QA-needed issue, correct me if I'm wrong anyone!

**Comment by kumar303** [comment]
That's correct. @ValentinaPC if you have time to test for any regressions, that would still be helpful. The category page should still be working as it did before.

**Comment by ValentinaPC** [comment]
> That's correct. @ValentinaPC if you have time to test for any regressions, that would still be helpful. The category page should still be working as it did before.

Sure thing!

**Comment by ValentinaPC** [comment]
Verified for regression while loading all categories pages for extensions and themes, and were not found.
