### ISSUE TITLE
Refactor Button component, mixin, and colours

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2517]
The Photon colours are a bit different than what's in the Sketch mock and our Button mixin is a bit more verbose than it needs to be: we should clean it up.

See: https://github.com/mozilla/addons-frontend/pull/2478#pullrequestreview-42061544 and https://github.com/mozilla/addons-frontend/pull/2478#pullrequestreview-42062630

**Comment by tofumatt** [comment]
Additionally, we should refactor the component's API by not requiring `className` props https://github.com/mozilla/addons-frontend/pull/2478#pullrequestreview-42098327

**Comment by tofumatt** [comment]
This should also include #3752.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, FF58 (Win10x64)

- inactive/active/hover +Add to Firefox button
![image](https://user-images.githubusercontent.com/31961530/35738262-fe751058-0836-11e8-980e-101a51ab453e.png)

- smaller screens size; Android view
![image](https://user-images.githubusercontent.com/31961530/35738254-f1d58f94-0836-11e8-8b0d-01172eca3f88.png)

- navigation buttons in different states
![image](https://user-images.githubusercontent.com/31961530/35738320-2cfde544-0837-11e8-9b23-0664cfceb9c5.png)

- Report abuse function; Contribute button
![image](https://user-images.githubusercontent.com/31961530/35738360-598e8ff0-0837-11e8-8a8e-c175ca2c036a.png)

@tofumatt - some things that need to be clarified:
 1. The color of the navigation buttons in hover state is very close to the AMO background. This seems to be the specification but I thinks it looks a bit odd:
![image](https://user-images.githubusercontent.com/31961530/35738590-f5b2b6cc-0837-11e8-86a5-5a7f365e6c0d.png)
2. On Android, some of the buttons (i.e Tap to preview, Install theme, Add to Firefox etc), when tapped, they remain in a hover state (color remains dark blue). They return to the initial state (light blue) only if you tap somewhere else on the page.
3. The text for the Log in button in Flag review section needs to be white. For this I filed a new issue [#4303](https://github.com/mozilla/addons-frontend/issues/4303)

![image](https://user-images.githubusercontent.com/31961530/35740496-a66cd010-083d-11e8-972e-01189f40cf43.png)

**Comment by tofumatt** [comment]
Addressing your points:

1. Yes, I saw this too, but it's according to spec so I think we'll leave it as "working as intended" for now. I agree it looks a bit weird though, so I'll see if we can address it later. 😄
2. I think this is how mobile browsers implement hover and is tough to change but if you wanted to file an issue about it and label it a low priority it would be handy to have
3. Thanks! I'll get to that one.

**Comment by AlexandraMoga** [comment]
Marking this as verified fixed based on the above comments.
The DiscoPane issue is being tracked here [#4291](https://github.com/mozilla/addons-frontend/issues/4291)
