### ISSUE TITLE
Implement the desktop footer

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2518]
We should change the footer colour over to match the header, and implement the new style from the mocks. (Minus the "view mobile site" link because the site will be responsive. Actually that link should be "Leave AMO beta" on desktop and "View Desktop Site" on mobile sizes...)

<img width="732" alt="screenshot 2017-06-05 17 39 54" src="https://cloud.githubusercontent.com/assets/90871/26793471/09e34dae-4a16-11e7-8fe9-94f181775ca7.png">

**Comment by tofumatt** [comment]
Update: I've changed the text to "View Classic Desktop Site"

**Comment by tofumatt** [comment]
To be clear the mobile site should have the logo on the left.

![screen shot 2017-06-13 at 16 38 04](https://user-images.githubusercontent.com/90871/27090990-b7abca92-5056-11e7-8584-aa43b1397be6.png)

**Comment by vcarciu** [comment]
Based on the latest comments, I will mark this as verified : 
Desktop: 
![deskfooter](https://user-images.githubusercontent.com/1583842/27091134-ed63e2ee-5067-11e7-8e96-7f0e8d7fbfaf.png)

Mobile:
![mobilefooter](https://user-images.githubusercontent.com/1583842/27091163-075ef76a-5068-11e7-9dd0-56f3ece82b68.png)
