### ISSUE TITLE
Consolidate add-on detail views before converting it to saga

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2519]
The add-on detail components needed a lot of cleanup before porting it to a saga so I think it makes sense to land the cleanup patch first. This is in preparation for https://github.com/mozilla/addons-frontend/issues/2442

For QA: It would be helpful if you could check for regressions on the add-on detail page. Some things to check:
- Can you install add-ons?
- Does theme previewing still work?
- Can you install themes?
- Does the detail page still look right after the theme is installed?

**Comment by kumar303** [comment]
It looks like this caused a regression: https://github.com/mozilla/addons-frontend/issues/2531

**Comment by kumar303** [comment]
Actually, I'm tracking the regression in https://github.com/mozilla/addons-frontend/issues/2531 so let's just close this since it landed in https://github.com/mozilla/addons-frontend/pull/2520

**Comment by vcarciu** [comment]
Tried all scenarios from description and some more scenarios around and everything looks fine.
Marking bug as verified.

**Comment by kumar303** [comment]
Thanks for taking a look. Keep in mind that the fix for https://github.com/mozilla/addons-frontend/issues/2531 hasn't on dev landed yet.
