### ISSUE TITLE
Intl TypeError on android devices

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2521]
The root cause of this is due to Intl being undeclared resulting in a ReferenceError

**Comment by muffinresearch** [comment]
Actually on further investigation it's the global Intl default that's causing the error under Android.

**Comment by muffinresearch** [comment]
This is fixed on -dev

**Comment by ValentinaPC** [comment]
Verified things on AMO-dev FF55 and FF52 under Android 7.1.2.
The installation buttons for both add-ons and themes are disabled. Same with the "Tap Preview" theme button.
Anything else like: read more link, license link, etc seem to work as expected.
Screenshots: 
![2017-06-07_1224](https://user-images.githubusercontent.com/15685960/26871566-570b2fe0-4b7c-11e7-8575-be1b9179bd46.png)

**Comment by muffinresearch** [comment]
@ValentinaPC can you open a new issue please? Unless you're seeing the `Intl is not defined` in the debug console this is a different issue. I don't see the slider buttons on -dev or stage anymore using release at all.

On nightly are you running test settings?

**Comment by ValentinaPC** [comment]
On both Nightly and Release I am using the `extensions.webapi.testing` pref set to true as before.

**Comment by muffinresearch** [comment]
For anyone else following along, the new bug is being tracked here: https://github.com/mozilla/addons-frontend/issues/2531

**Comment by ValentinaPC** [comment]
@muffinresearch : can I mark this verified-fixed, as the "`Intl is not defined`" error is not the error that was causing the issue from my last comment? Thanks!
