### ISSUE TITLE
addonReviewList not using isAllowedOrigin

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2528]
EDIT: Issue updated; I should just change my CDN host but we should fix the `AddonReviewList` component to check origin. I noticed this issue in the first place because it didn't check.

------

Original issue:

If you use `API_HOST=https://addons.mozilla.org yarn dev:amo` as I often do for more robust data for testing, you'll notice all the add-on icons are missing. Actually, a lot of data is missing for any icon that uses `isAllowedOrigin`. I'm guessing we do this so we only even bother rendering images for CDN hosts we allow and otherwise use the fallback icon which is nice, but I'd like an override for development so I can view all the remote content when I'm working with external server data.

Interestingly the `AddonReviewList` component doesn't use it so it shows the icon.

**Comment by muffinresearch** [comment]
From looking at my old local config I think you can work around this by setting the correct amoCDN entry e.g: `amoCDN: 'https://addons.cdn.mozilla.net'`

**Comment by tofumatt** [comment]
That's true, though it feels a bit more roundabout than the explicit nature of the config switch I added.

But if you'd rather not add more code I can do that. It just feels less obvious/more fragile.

**Comment by tofumatt** [comment]
Actually it's fine and less code, but I'm gonna change this to "AddonReviewList wasn't using `isAllowedOrigin`" 😄

**Comment by kumar303** [comment]
> I should just change my CDN host

If you get a minute, could you add docs explaining this?

**Comment by tofumatt** [comment]
> If you get a minute, could you add docs explaining this?

Totally. I'll make a new issue just so I remember. Will do it for this week.
