### ISSUE TITLE
Add-ons installation button is disabled

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2531]
Steps to reproduce:
1. Load any add-on details page on your Android device i.e. https://addons.allizom.org/en-US/android/addon/phony/?src=hp-dl-featured
2. Observe the installation button

Expected results:
The button is enabled.

Actual results:
The button is disabled.

Notes/Issues:
- issue is reproducing on bot stage and dev
- issue is reproduced for both themes and add-ons
- issue is reproduced on both FF55 and FF52
- pref `extensions.webapi.testing`  is set to true as it was before
- "tap to preview" is also affected
- issue is also reproducing on desktop while in Mobile Site View

Screenshots for this issue:
![2017-06-07_1224](https://user-images.githubusercontent.com/15685960/26876169-845cc4c0-4b8d-11e7-8b7d-88fd26830da4.png)

**Comment by muffinresearch** [comment]
I'm looking into it...

**Comment by muffinresearch** [comment]
It's a regression from https://github.com/mozilla/addons-frontend/commit/0a0e650b25deb74841802e387f93920eda02135d - reverting that commit restores expected functionality.

**Comment by muffinresearch** [comment]
This won't revert cleanly on master but a revert on the tag will work if we need to just get things working as quickly as possible and take more time with the patch for master.

**Comment by muffinresearch** [comment]
@kumar303 also let me know if you need any help with reproducing this locally.

**Comment by muffinresearch** [comment]
Actually I'm going to go ahead and revert in the tag to unblock QA sooner.

**Comment by muffinresearch** [comment]
Reverted for the tag see https://github.com/mozilla/addons-frontend/compare/2017.06.01...2017.06.08-2 

@ValentinaPC this will mean it should be fixed on stage (once deployed shortly) but won't be fixed on -dev. Leaving this bug open to track the fix that needs to land in master.

**Comment by tofumatt** [comment]
Shoot, sorry I didn't notice this myself.

**Comment by ValentinaPC** [comment]
Verified this on **stage** while using FF53(Android 7.1.2).
The install button is enabled (verified also for Nightly)
Video: 
![videotogif_2017 06 07_19 12 26](https://user-images.githubusercontent.com/15685960/26889020-6886112a-4bb5-11e7-862b-839a41d88896.gif)

**Comment by ValentinaPC** [comment]
Depends on #2545
