### ISSUE TITLE
Document CDN host to change when modifying API host during development

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2535]
If you change your `API_HOST`, to get images to appear you also need to modify your `amoCDN` (see: https://github.com/mozilla/addons-frontend/issues/2528#issuecomment-306752163).

We should document how to do this and when you'd want to.

I actually feel like a cool option would just be `API_DATA=prod yarn dev:amo` and it would set all options needed to load another dataset locally (because sometimes docker is borked but oftentimes the docker data just isn't as full-featured). Thoughts on that idea?

**Comment by kumar303** [comment]
> API_DATA=prod yarn dev:amo

I like it. We might need a different name just because the CDN isn't API related but I like the idea.
