### ISSUE TITLE
Add-on details page is returning server error

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2545]
Steps to reproduce:
1. Load details page for an add-on/theme on device i.e. https://addons-dev.allizom.org/en-US/android/addon/mobile-password-manager/?src=hp-dl-featured

Expected results:
Page is loaded with no display or layout issues.

Actual results:
A server error page is loaded.

Notes/Issues:
- may be a regression from #2531 ?
- tapping on add-on name works after second action, first tap returns an error in the console (screenshot from desktop while in Mobile Site View):
![first_click](https://user-images.githubusercontent.com/15685960/26970143-f1435aa2-4d10-11e7-9eb3-4c2365b2c5fd.png)

Verified on AMO-dev FF53(Android 7.1.2). Issue is only reproduced on dev.
Video: 
![videotogif_2017 06 09_12 42 20](https://user-images.githubusercontent.com/15685960/26970514-56dba314-4d12-11e7-8325-ce3651480339.gif)

**Comment by ValentinaPC** [comment]
Please give us a hand in this, because is blocking QA while testing a massive part from -dev.
Thanks!

**Comment by tofumatt** [comment]
I've figured out what this is and am just submitting the patch now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2).
Postfix video:
![videotogif_2017 06 12_14 11 21](https://user-images.githubusercontent.com/15685960/27033777-7db34910-4f83-11e7-8c14-b1d5488b18c0.gif)
