### ISSUE TITLE
Developer Hub is not responsive when logged in

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2548]
Steps to reproduce:
1.On your Android device, login to AMO-dev
2.Press the Developer Hub button

Expected results:
The developer hub page opened on mobile should be responsive(should fit to mobile screen, no left/right scroll needed, user is able to scroll to see the footer of the page)

Actual results:
The developer hub page opened on mobile is not responsive, user is not able to scroll to see footer of the page

Note:
Logged out page is responsive

Please see video for this issue:
![nonresponsivedevhub](https://user-images.githubusercontent.com/1583842/26982892-95403ab8-4d42-11e7-80b7-decc8cd5b1cf.gif)

**Comment by muffinresearch** [comment]
This was a design decision in the orignal developer hub page specification because the pages beyond this one will not work on a mobile device either. 

It might be worth us reconsidering whether this link should be present on smaller viewport widths so prominently.

@pwalm any thoughts?

**Comment by vcarciu** [comment]
Please keep in mind that you can't reach any link from the footer page

**Comment by pwalm** [comment]
Drop the dev hub button. One of those things we don't need at mobile viewports (especially if devhub itself is not responsive).

**Comment by tofumatt** [comment]
Ten four, I'll hide the link on mobile.

**Comment by vcarciu** [comment]
Verified as fixed : 
![nodevhub](https://user-images.githubusercontent.com/1583842/27034370-18cd1f6e-4f86-11e7-8b8c-9f4de94e9c9d.png)
