### ISSUE TITLE
"About this add-on" should be on right side of desktop view

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2550]
The desktop pages put the "About this add-on" on the left side of the screen, but because we expand that context down it renders very strangely with an add-on that has a reasonable amount of text in the description once expanded:

![jun-10-2017 17-34-16](https://user-images.githubusercontent.com/90871/27004581-12ec265a-4e03-11e7-9889-2fa5db00e67e.gif)

I think the issue is to move the "About this add-on" text to the right side of the screen, either above or below the screenshots (prob below).

**Comment by tofumatt** [comment]
Another possibility is to move screenshots over to the left (essentially swapping them) as they use a flexbox anyway and seeing a few scrolling horizontally isn't that great anyway, especially on windows with the scrollbars. Swapping them would show there ARE screenshots and show basically one full screenshot with the option to scroll but give the add-on description and info into much more space/prominence.

**Comment by pwalm** [comment]
Sorry, I flagged this issue and then promptly forgot about it (story of my life).

I'll move the about copy to the L side, and place it below the screenshots.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7).
Postfix screenshot from theme and add-ons details page:
![theme](https://user-images.githubusercontent.com/15685960/27130656-e4cfdc84-510f-11e7-95a3-bae9da6b36d0.png)
![about](https://user-images.githubusercontent.com/15685960/27130659-e79174d2-510f-11e7-886c-fb3923bd44b7.png)
