### ISSUE TITLE
Create a useable ReviewList component that can be used in AddonDetail

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2552]
The current `AddonReviewList` component relies a bit too much on location, params, etc. to load reviews–this makes it difficult to include in the `Addon` component as per the desktop mocks. I'd like to make it easier to use in that component but will track that work here so it doesn't get to be too big of a PR. Might be a good chance to move the review fetching to a saga...

**Comment by kumar303** [comment]
It looks like https://github.com/mozilla/addons-frontend/pull/3612 landed without the need for a more usable ReviewList component.
