### ISSUE TITLE
Document how to test Disco Pane

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2555]
We should move these docs into `addons-frontend` (or just link to them or something).

https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing

**Comment by muffinresearch** [comment]
This was partly covered by https://addons-frontend.readthedocs.io/en/latest/moz-addon-manager/.

**Comment by muffinresearch** [comment]
I think the docs are pretty good for this now. Closing.
