### ISSUE TITLE
Sometimes `flow:dev` gets stuck on initializing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2556]
### Describe the problem and steps to reproduce it:

Run `yarn flow:dev`

### What happened?

When it starts you see:

    flow is still initializing; this can take some time.

Occasionally, it never finishes.

### What did you expect to happen?

This command (when it works) will start a Flow server in the background and check for Flow errors when the files change.

### Anything else we should know?

It uses `flow status` which, according to Flow docs, starts the server automatically if it needs to. As a workaround, I've had luck with manually stopping and starting the server and then running `flow:dev` again.

**Comment by vcarciu** [comment]
Please add some STRs to this bug or mark it as "qa: not needed"
