### ISSUE TITLE
Implement a desktop "all reviews" page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2564]
Implement the review page for desktop, relates to #2552.

**Comment by tofumatt** [comment]
It turns out there isn't a mock for this in the mocks... maybe it was overlooked?

@pwalm Can you confirm there's no desktop version of "all reviews" (after the list that's on the details page)? No worries if not, the mobile will work okay, just want to confirm I'm not missing it in the mocks.

**Comment by pwalm** [comment]
I am missing it, but it won't be hard to throw together. Kind of a hectic week, can I have it to you by Friday?

**Comment by tofumatt** [comment]
Oh gosh yeah that's fine. No rush at all, this Friday or even the next one is fine.

Matthew Riley MacPherson

**Comment by tofumatt** [comment]
Arg, I thought I updated this issue with the image but I must've not clicked submit. Here's the mock from @pwalm:

![all reviews page - 1366px](https://user-images.githubusercontent.com/90871/28961468-5033ec10-78fa-11e7-9bc9-c56ce106ae8a.png)

**Comment by kumar303** [comment]
Is there an API bug on file to get a tally of ratings grouped by star count? We do not currently have this data: http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v3-addons-addon-(int-id|string-slug|string-guid)-

**Comment by kumar303** [comment]
whoops, we already have the grouped rating data in the API: http://addons-server.readthedocs.io/en/latest/topics/api/reviews.html#list-reviews

**Comment by ValentinaPC** [comment]
Verified All Review page in AMO-dev FF56(Win 7) and this is how it looks like now:
![2017-10-27_1227](https://user-images.githubusercontent.com/15685960/32097439-4c4c1136-bb12-11e7-9cf5-dfdfeaddd5cd.png)
- no write a review button
- no average rating stars section
- rating stars from each add-on are gray (logged https://github.com/mozilla/addons-frontend/issues/3661)

@tofumatt : Looks like mocks and actual page are very different. Is there an intend to implement those options? Or this is how it should look like? Thanks a lot!

**Comment by pwalm** [comment]
Should look like this:
<img width="979" alt="screen shot 2017-10-27 at 12 26 43 pm" src="https://user-images.githubusercontent.com/6797635/32099804-207f796c-bb12-11e7-901f-ed863e02cef9.png">

**Comment by ValentinaPC** [comment]
But, it looks like this:
![2017-10-30_1046](https://user-images.githubusercontent.com/15685960/32161865-bfecefee-bd5f-11e7-887e-d13e8d475ef7.png)

- I saw that for the "average" section was logged #3647, but I cannot see the "Write a review" button, so I'll reopen this.

**Comment by tofumatt** [comment]
The write a review button is part of a new flow and should be a separate bug then. Because most of the work here is done and changing that review flow with the new button will be its own issue :-)

- Matthew Riley MacPherson
tofumatt.com

**Comment by ValentinaPC** [comment]
We can mark this as verified-fixed, then.
