### ISSUE TITLE
Create a responsive desktop home page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2565]
Create a responsive desktop home page.

**Comment by tofumatt** [comment]
Closed by #2655.

**Comment by vcarciu** [comment]
Verified as fixed: 
Large : 
![large](https://user-images.githubusercontent.com/1583842/27868513-95836294-61a5-11e7-96ad-4ec2b0cf218d.png)

Medium:
![medium](https://user-images.githubusercontent.com/1583842/27868524-9c027808-61a5-11e7-8e2a-0b048a2eff20.png)

Mobile:
![mobile](https://user-images.githubusercontent.com/1583842/27868528-a282cd40-61a5-11e7-9bb2-98a6e94d8e42.png)
