### ISSUE TITLE
Theme without description have layout issues in details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2569]
Steps to reproduce:
1. Load details page on desktop for a theme without a description i.e. https://addons-dev.allizom.org/en-US/firefox/addon/cute-pastel-flowers/

Expected results:
There are no display or layout issues.

Actual results:
"None" text is affecting the review section.

Notes/Issues:
Verified on AMO-dev FF53(Android 7.1.2).
Screenshot for this issue:
![none2](https://user-images.githubusercontent.com/15685960/27132594-182ae512-5118-11e7-94a9-c0c0b41ddeed.png)

**Comment by tofumatt** [comment]
@kumar303 or @muffinresearch The API is definitely returning `null` for this description property (https://addons-dev.allizom.org/api/v3/addons/addon/cute-pastel-flowers/) but the code is at some point changing that to `'None'`. A quick grep through the code for `'None'` or `description` doesn't yield anything and this doesn't happen to the summary, just `description`. Any ideas?

**Comment by kumar303** [comment]
I'm not sure where None is coming from. Are you sure the API isn't returning the string `None`? I am suspicious that the Python side is converting something to None. FWIW, this is reproducible using docker locally with auto-generated add-ons but that could be related to the auto-generation code, I'm not sure.

**Comment by muffinresearch** [comment]
I see None in the description: https://addons-dev.allizom.org/api/v3/addons/addon/cute-pastel-flowers/

**Comment by tofumatt** [comment]
!!!!!

There is also a `description: null`.

That `'None'` is in `theme_data`. We're probably doing an object spread or something. Thanks for the help, I'm on this now should be easy to figure out. *Brutal!*

**Comment by tofumatt** [comment]
![preview](https://user-images.githubusercontent.com/90871/27144635-8e89cdec-512a-11e7-9c40-a7e41ca6b095.jpg)

**Comment by tofumatt** [comment]
Note for QA that the fix for this includes omission of the "About this persona" block when the summary/description are empty.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2, Win 7).
Postfix screenshots:
![desktop-mobile](https://user-images.githubusercontent.com/15685960/27272835-fc541924-54d4-11e7-88d4-a43b8749ecff.png)
