### ISSUE TITLE
Theme description is causing layout issues on device while in details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2570]
Steps to reproduce:
1. Load details page for a theme with description (or without) on device i.e. https://addons-dev.allizom.org/en-US/android/addon/shamrocks2/

Expected results:
There are no display or layout issues.

Actual results:
Description is causing layout issues.

Notes/Issues:
Verified on AMO-dev FF53(Android 7.1.2)
Screenshot for this issue:
![2017-06-14_1547](https://user-images.githubusercontent.com/15685960/27132820-ea52ffb6-5118-11e7-8f53-8dfb62b8a25d.png)

Maybe regressed from #2559 ?

**Comment by tofumatt** [comment]
This is related to #2569; a description that is too short causes errors. I'll have a fix soon.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Android 7.1.2)
Postfix screenshot:
![descript](https://user-images.githubusercontent.com/15685960/27180267-594f3804-51db-11e7-95d7-dd14219e75f9.png)
