### ISSUE TITLE
Screenshots from new desktop are too small

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2571]
Steps to reproduce:
1. Go to any add-on details pages and press "View Mobile Site" from the bottom of the page (https://addons-dev.allizom.org/en-US/firefox/addon/findbar-tweak/)
2. Open screenshots to full size in order to view them

Expected results:
Screenshots should be at least same size like on the classic desktop site

Actual results:
Screenshots are too small, and the details can be hardly distinguished

Please see video for this bug : 
![screenshotsize](https://user-images.githubusercontent.com/1583842/27137300-3e3a2fa2-5126-11e7-9c46-f550c0d24d3c.gif)

**Comment by kumar303** [comment]
I think it would be nice to address this for Q3 if possible. Otherwise we can kick it out.

**Comment by vcarciu** [comment]
Verified as fixed : 
![screenshotsizefix](https://user-images.githubusercontent.com/1583842/30542290-79854d42-9c87-11e7-9de8-72586b6fa3df.png)
