### ISSUE TITLE
Convert the add-on detail page to using sagas

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2573]
Instead of using async-connect to pre-load the add-on detail page, we should use a saga. 

Steps to test for regressions:
* Load the add-on detail page, make sure it works. 
* Try refreshing the detail page, make sure it still works.

This is a step towards https://github.com/mozilla/addons-frontend/issues/2356

**Comment by vcarciu** [comment]
Verified around scenarios from description and everything looks fine.

**Comment by vcarciu** [comment]
Yesterday , everything looked ok , but I started to see again the black bars before add-on is loaded on -dev : 
Mobile: 
![blackbarmobile](https://user-images.githubusercontent.com/1583842/27592560-74932946-5b5d-11e7-9a09-a04104632e9a.gif)

Desktop: 
![blackbardesktop](https://user-images.githubusercontent.com/1583842/27592575-7ee5354c-5b5d-11e7-99a7-957388f4146e.gif)

**Comment by kumar303** [comment]
Oh, yeah, the black bars are a new feature we added -- they are expected :) They are placeholders for the real text while it's still loading in the background. Before the black bars, the page would not load until all data was available. With this new strategy, the page loads immediately (with black bars) which feels a lot faster to the user.

**Comment by vcarciu** [comment]
@kumar303 : thanks!
