### ISSUE TITLE
Stop loading add-on data into state from the search page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2574]
After https://github.com/mozilla/addons-frontend/issues/2573, let's stop populating the add-on detail page with data from search results because it will fix bugs like https://github.com/mozilla/addons-frontend/issues/2435 Instead, let's always let the add-on detail page load its own state. This means, when you perform a search and navigate to the add-on detail page, a new API request will be made (and less bugs will be filed!).

Steps to test for regressions:
* Load the add-on detail page, make sure it works. 
* Try refreshing the detail page, make sure it still works.
* Try searching for an add-on and navigating to its detail page, make sure it works.

**Comment by tofumatt** [comment]
A thought: you can make the transition from search to detail feel faster by using the data you do have (title, description, etc.) but using a `LoadingText` or whatnot for data that isn't available. As soon as data is not found, dispatch an action to load more data into the state.

This is obviously more complex but I'd imagine will lead to much better UX as any add-on returned from the search can load *most* of its data right away.

**Comment by muffinresearch** [comment]
@kumar303 this looks like a dupe of https://github.com/mozilla/addons-frontend/issues/1404 - I'll leave it to you to decide which one you want to close.

**Comment by kumar303** [comment]
Indeed! Thanks
