### ISSUE TITLE
Add-on detail has layout issues on non-Firefox browsers

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2577]
### Describe the problem and steps to reproduce it:

Load an add-on detail page in Chrome (or any non-Firefox browser)

### What happened?

There are layout issues. Example:

<img width="325" alt="screenshot 2017-06-14 10 39 30" src="https://user-images.githubusercontent.com/55398/27141805-ca8675ca-50ee-11e7-9d26-4e75de453346.png">

### What did you expect to happen?

The install disabled button should be aligned better and the 'download Firefox' banner needs some space

**Comment by tofumatt** [comment]
The disabled install button is where the switch would be (that's its intended position) but yeah the banner should be better spaced. Thanks, I'll get on that.

**Comment by kumar303** [comment]
Ah, right

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Chrome 58.0.3029.83 under Android 7.1.2.
Postfix screenshots:
![non-ff](https://user-images.githubusercontent.com/15685960/27271763-39fde8f0-54cf-11e7-88b8-8c3b19980ac5.png)
