### ISSUE TITLE
Rating stars from "ratings and user count" section are unaligned for some langs

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2587]
Steps to reproduce:
1. Load details page for an add-on/theme on device or desktop (using Mobile Site View) while in other locale i.e. https://addons-dev.allizom.org/dsb/firefox/addon/extended-statusbar/?src=hp-dl-featured
2. Observe the "rating and user count" section

Expected results:
Number of users, rating stars and number of reviews are aligned.

Actual results:
Rating stars are not aligned.

Notes/Issues:
Verified on AMO-dev FF53(Win 7, Android 7.1.2)
Screenshot for this issue:
![aligned](https://user-images.githubusercontent.com/15685960/27181480-709e8c62-51e0-11e7-96cf-1b0af531855b.png)

**Comment by muffinresearch** [comment]
This looks to be a small regression from the recent desktop changes.

**Comment by tofumatt** [comment]
I think we're supposed to use "maybe good first bug" until the issue has been reviewed in the triage meeting for contributor bugs.

**Comment by ValentinaPC** [comment]
I've added the label based on this: https://github.com/mozilla/addons-frontend/issues/2128 .
I will not do this in the future.
Thanks.

**Comment by tsl143** [comment]
I think this has already been fixed.

<img width="1279" alt="screen shot 2017-06-30 at 10 48 07 pm" src="https://user-images.githubusercontent.com/5318732/27746812-494b4a94-5de6-11e7-9d3a-ce69c521bef9.png">

**Comment by tofumatt** [comment]
Nope, this is still an issue (see the attached link) and it seems spaced out more based on the text above.

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
mentor @muffinresearch

**Comment by tsl143** [comment]
@tofumatt then consider this PR https://github.com/mozilla/addons-frontend/pull/2606, it still fixes the issue.
Please refer same screenshots in the PR.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7)
Postfix screenshots:
![de](https://user-images.githubusercontent.com/15685960/28111604-be246154-66fe-11e7-9205-352c281814fb.png)
![dsb](https://user-images.githubusercontent.com/15685960/28111603-be1be452-66fe-11e7-85b4-0a5299c45571.png)

@tofumatt Seems like the issue is still reproducing on mobile pages, what do you think?
Screenshot:
![dev](https://user-images.githubusercontent.com/15685960/28111781-4fe2a54c-66ff-11e7-8506-302179f0fe92.png)

**Comment by tofumatt** [comment]
Agreed, I think the alignment is still off.

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7, Android 7.2.1)
Postfix screenshots:
![2017-07-26_1155](https://user-images.githubusercontent.com/15685960/28612976-a7586b22-71f9-11e7-848b-417f58212c41.png)
