### ISSUE TITLE
Left-sided theme design is causing issues in theme details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2588]
Steps to reproduce:
1. Search for a theme that has its design oriented on the left side i.e. "Flow Free" using AMO-dev
2. Observe theme design in search results pages
3. Access theme details page

Expected results:
Entire theme design is displayed in theme details page.

Actual results:
Theme design is cut.

Notes/Issues:
Verified on AMO-dev FF53(Win 7, Android 7.1.2).
- this is also happening on desktop but with issues in search suggestions and search results page.
Screenshot from desktop:
![desktop](https://user-images.githubusercontent.com/15685960/27182673-b84da418-51e4-11e7-8b82-9289b7ecede0.png)

Screenshots from device:
![2017-06-15_1541](https://user-images.githubusercontent.com/15685960/27182702-cef0f27e-51e4-11e7-84e6-6ae9cc33de5c.png)

Another example: https://addons-dev.allizom.org/en-US/android/addon/free-step-and-mozilla-firef/?src=ss
Screenshots: 
![2017-06-15_1611](https://user-images.githubusercontent.com/15685960/27182881-6a4bf7d2-51e5-11e7-864c-976243822262.png)

**Comment by muffinresearch** [comment]
As rightly pointed out by @eviljeff on irc themes are right-aligned in the browser so this results in this if the browser window is small.

<img width="948" alt="add-ons_for_firefox_and_add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/27191156-d7433874-51ee-11e7-9e82-eefc437aab6a.png">

I think this is a wontfix - this was last updated 8 years ago too FWIW.

**Comment by tofumatt** [comment]
Oh sweet because this was gonna be kind of annoying to fix 😅
