### ISSUE TITLE
"Custom License" is not a link on new desktop pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2589]
Steps to reproduce:
1. Load details page for an extension that has "Other" set as a license in "Manage Authors & License" i.e. https://addons-dev.allizom.org/en-US/firefox/addon/fb-purity-cleans-up-facebook/
2. Click on "View Mobile Site"
3. Go to "More information" and observe the license 

Expected results:
License is a link.

Actual results:
License is not a link.

Notes/Issues:
- another strange thing is also happening: all add-ons that have "Custom License" set in Dev Hub, clicking the link from add-on details will load the page: https://www.mozilla.org/en-US/MPL/1.1/ 
Video for this note
![license](https://user-images.githubusercontent.com/15685960/27186956-97cdb918-51f2-11e7-900a-116ace6812a0.gif)

- reproducing also on device

Verified on FF53(Win 7, Android 7.1.2)
Issue is reproducing on AMO-dev and stage.
**Screenshots for this issue:**
![desktop](https://user-images.githubusercontent.com/15685960/27186929-853fe032-51f2-11e7-8d56-6b49264ce2d7.png)

**Comment by aayushsanghavi** [comment]
I was running the application locally (amo-dev) and this happened -

![customlicense](https://user-images.githubusercontent.com/19590302/27235316-db04dad2-52af-11e7-88c1-e20192f66d4b.gif)

When I clicked on the extension, the license information wasn't showing in the "more information" section. On refreshing the page, we're able to see the license information with the license link.

I also checked this on my android device and the behaviour is exactly as we see in the gif above.

@ValentinaPC could you verify this?
(I was just checking out and reproducing the issue and I found this behaviour odd)

**Comment by tofumatt** [comment]
@aayushsanghavi That is a known issue, see #2435.

**Comment by aayushsanghavi** [comment]
Sorry, I just happened to see it on IRC. My bad. 😅

**Comment by tofumatt** [comment]
This is actually not a bug. We had the URL property and test for it. Having just looked at the data returned by the API on dev this is because this add-on is returning `null` for a license:

https://addons.allizom.org/api/v3/addons/search/?app=firefox&q=Cleans%20Up%20Facebook&page=1&lang=en-US

It's interesting that addons-server (on both user pages and on devhub) is setting MPL as the default license URL if the license is custom but the URL isn't set. That's probably why the devhub is setting everything to MPL.

But this isn't an issue as the license isn't actually set, and when it is our code works 😄

**Comment by ValentinaPC** [comment]
Let me give you an example.
- We have the add-on: https://addons-dev.allizom.org/en-US/developers/addon/fb-purity-cleans-up-facebook/ownership - you can see that it has a license set.
- Access the new desktop pages for this add-on: https://addons-dev.allizom.org/en-US/firefox/addon/fb-purity-cleans-up-facebook/
- Observe the license section:
![cl](https://user-images.githubusercontent.com/15685960/28560456-6724452a-7123-11e7-80dc-17d3ca2b2582.png)
 @tofumatt : Are you sure this is ok?
Thanks for your reply!

**Comment by tofumatt** [comment]
Ah, it seems in that case we should just be linking to a set URL and nothing would come back in the API then? Weird, okay... I'll re-open and have another look. Maybe the API docs for what to expect were wrong.

**Comment by tofumatt** [comment]
Figured out this is blocked by https://github.com/mozilla/addons-server/issues/6168.

**Comment by ValentinaPC** [comment]
Verified on AMo-dev FF54(Win 7, Android 7.2.1)
Based on the fix from mozilla/addons-server#6168 this can be closed and marked as verified fixed.
