### ISSUE TITLE
Missing padding from install button on disco pane in prod.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2592]
The gutter has gone from the right-hand side of the install button.

<img width="1027" alt="add-ons_manager" src="https://user-images.githubusercontent.com/1514/27194547-dac27e54-51fa-11e7-8dd4-117ce570dea5.png">

Need to check this on RTL too and make sure the fix doesn't impact amo.

**Comment by tofumatt** [comment]
There's also issues with the buttons when `mozAddonManager` isn't available:

<img width="728" alt="screenshot 2017-06-15 19 07 35" src="https://user-images.githubusercontent.com/90871/27195241-e8057c3a-51fd-11e7-8d4b-e493ebdf4e89.png">

-----

I've fixed that in the PR too.
