### ISSUE TITLE
Please allow different screenshots for different languages

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-frontend#2596]
Hi,

please allow different screenshots for different languages.

At the moment I can either upload screenshots showing the UI of my add-on in one language (but not the correct language for a lot of the users) or I have to upload the same screens in all languages so if my add-on is available in 8 languages the user see the same screens 8 times - 1x for every language. Both options are not great.

Since almost everything is localizable it would make sense to also allow screenshots in different languages.

**Comment by tofumatt** [comment]
Thanks for filing! This is a good idea; I totally think we should do it.

I know we're looking to spend some time improving a few things for screenshots; they're in need of some updating and this would be a good feature to add while we're doing that.

This repo is largely for the front-end and display of the add-ons site, so I've moved this issue to the addons-server repo: https://github.com/mozilla/addons-server/issues/5662
