### ISSUE TITLE
Theme icon from "All written reviews" page is too small

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2598]
Steps to reproduce:
1. Load "All written reviews" page for a theme on device i.e. https://addons-dev.allizom.org/en-US/android/addon/one-piece-luffy-and-sun-256856/reviews/
2. Observe theme icon

Expected results:
Theme icon is aligned.

Actual results:
Theme icon is smaller than extensions icons from the same page and is not aligned with theme title and author.

Notes/Issues:
- reproducing on moth mobile pages and new desktop pages.
Verified on FF53(Android 7.1.2, Win 7). Issue is reproducing on all AMO servers.
Screenshots for this issue: 
![theme](https://user-images.githubusercontent.com/15685960/27221739-5e343e66-5292-11e7-89bd-173abcce9267.png)
![theme_icon](https://user-images.githubusercontent.com/15685960/27221747-6215bd02-5292-11e7-949d-9bda12866cb8.png)

**Comment by aayushsanghavi** [comment]
@ValentinaPC should the review list header look like this -

![theme_icon](https://user-images.githubusercontent.com/19590302/27231408-0c3d9520-52a2-11e7-8b63-f20ae0753939.png)

The image has to have a height and width equal to the height of the text divs?

**Comment by ValentinaPC** [comment]
Let's ask @tofumatt .
Matt, what do you think about this?

**Comment by tofumatt** [comment]
Hi there, sorry my late reply.

Yes it should look like that, at least aligned like that... the icon is `32px x 32px` so it shouldn't be stretched anymore than that. `32px` icons already look blurry on modern devices with retina and better screens.

**Comment by aayushsanghavi** [comment]
@tofumatt should we resize all theme header icons to 32x32, for uniformity? What do you suggest?

**Comment by tofumatt** [comment]
Yes. We shouldn't be stretching them beyond the file size; preferably we should have higher resolution files but that's a whole thing...

Maybe we do and I'm just seeing bad add-ons. Can you find add-one whose icons are above 32px?

- Matthew Riley MacPherson (sent from mobile)

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-server/issues/5805

**Comment by vcarciu** [comment]
Verified as fixed : 
![screenshot_20170707-112106 1](https://user-images.githubusercontent.com/1583842/27950003-60e9e24c-6308-11e7-9bdb-5076e51125b2.png)
