### ISSUE TITLE
Sections titles are not RTL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2605]
Steps to reproduce:
1. Load Details page for any extension on device i.e. https://addons-dev.allizom.org/en-US/android/addon/home-links/?src=hp-dl-featured
2. Change the language to a RTL one https://addons-dev.allizom.org/ar/android/addon/home-links/?src=hp-dl-featured
3. Observe sections titles

Expected results:
Titles are RTL.

Actual results:
Title are not RTL.

Notes/Issues:
- issue is also reproducing on new desktop pages
- issue is reproduced while in Extenions/Themes homepages

Verified on AMO-dev FF53(Android 7.1.2, Win 7).
Screenshots for this issue: 
![2017-06-19_1006](https://user-images.githubusercontent.com/15685960/27273263-ed59b508-54d6-11e7-8cb3-079d8e1575f2.png)

**Comment by tofumatt** [comment]
This was fixed by #2641.
