### ISSUE TITLE
"View Mobile Site" is not working

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2607]
Step to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/android/
2. Click on "View Mobile Site" link from the footer

Expected results:
User is redirected to new desktop pages.

Actual results:
Nothing happens.

Notes/Issues:
- at click a `#` is added to the URL
- nothing listed in the console while the link is clicked
 Verified on FF53(Win 7, Android 7.1.2). Issue is only reproducing on -dev.
Video for this issue: 
![link](https://user-images.githubusercontent.com/15685960/27282370-4d31e06a-54f8-11e7-8081-df3a27503788.gif)

**Comment by kumar303** [comment]
I don't have Firefox 53 right now but I can't reproduce this in 54 (desktop, Mac) which is Firefox's current release. Does it still happen for you in 54?

**Comment by tofumatt** [comment]
I couldn’t reproduce it in developer edition Mac or 54 desktop release on Mac either.

**Comment by muffinresearch** [comment]
There was a js error earlier caused by a jquery-pjax lib upgrade. Since that's been resolved, this bug is probably no longer reproducible.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF53(Win 7, Android 7.1.2).
Postfix video:
![view mobile site](https://user-images.githubusercontent.com/15685960/27322639-88dc7e2c-55a7-11e7-90bf-cb11dd2f9efb.gif)
