### ISSUE TITLE
Convert add-on review list to sagas

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2608]
Instead of using async-connect to pre-load data for the add-on review listing, we should use a saga. 

Steps to test for regressions:
* Load an add-on detail page for an add-on that has reviews
* Click 'Read N reviews'
* Make sure the review listing still works

This is a step towards https://github.com/mozilla/addons-frontend/issues/2356

**Comment by vcarciu** [comment]
@kumar303 : Please let me know if this is ok and will be solved in another issue, or this should be reopened: 
![reviewsbeforeloading](https://user-images.githubusercontent.com/1583842/27592843-2f0582ba-5b5e-11e7-8d3c-45fefa34c547.gif)

**Comment by kumar303** [comment]
Hi @vcarciu , your screencast looks right. What were you expecting to happen that should be solved in another issue? Thanks for testing it out.
