### ISSUE TITLE
Sort header section borders are cut on the corners

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2611]
Steps to reproduce:
1.On Android , select any field from header (ie. Extensions)
2.Press "More popular extensions " link
3.Expand the "Sort" section

Expected results:
No UI issues

Actual results:
Sort header section borders are cut on the corners

Notes : 
Reproducible also on Desktop with mobile view

Please see screenshot for this issue : 
![borders](https://user-images.githubusercontent.com/1583842/27336281-b7196144-55d7-11e7-8454-c4ae41cf0850.png)

**Comment by tofumatt** [comment]
This sort component has actually changed and will likely look different so this will be closed by changing it, but thanks for the heads-up :-)
