### ISSUE TITLE
After installing a "requires restart" add-on, the restart pop-up will not trigger a browser restart

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2613]
Browser: Latest Nightly
Device : Android 7.0, Samsung Galaxy S8

Steps to reproduce:
1.On Android, install any "requires restart" add-on(https://addons-dev.allizom.org/en-US/android/hotpost/)
2.Press the Restart button from the Restart pop-up displayed after installation

Expected results:
Browser is restarted

Actual results:
Browser is closed but it will never start again

I added some logs for this issue, because a video is not so relevant here : 
https://pastebin.mozilla.org/9025377

**Comment by muffinresearch** [comment]
@vcarciu I think a video would be useful here. Are you referring to a native dialog with a restart button?

**Comment by vcarciu** [comment]
Okay, here you have the video : 
![restartnorestart](https://user-images.githubusercontent.com/1583842/27340766-02b790e2-55e4-11e7-9231-224da51ec6cd.gif)

**Comment by muffinresearch** [comment]
@vcarciu this is a Android issue. If this is still relevant can you file a bug on bugzilla for this?
