### ISSUE TITLE
Stage is not working on mobile mode

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2617]
Steps to reproduce:
1. Load AMO-stage on device i.e. https://addons-dev.allizom.org/en-US/firefox/ (or on desktop and click "View Mobile Site" link)

Expected results:
Page is loaded without any issues.

Actual results:
Page has no `css` format.

Notes/Issues:
- issue is only reproducing on -stage
- there are some `js` and `css` 404 errors int he console
Verified on FF54(Win 7, Android 7.1.2)
Screenshot for this issue:
![stage](https://user-images.githubusercontent.com/15685960/27374350-188ff5ea-5674-11e7-9e87-81ecde423863.png)
![device](https://user-images.githubusercontent.com/15685960/27374351-1b2e7e2a-5674-11e7-824a-b18bc430a8b4.png)

**Comment by EnTeQuAk** [comment]
This works on -dev, maybe even something ops related, files not copied properly to our cdn? cc @bqbn on this

**Comment by muffinresearch** [comment]
Yep the hash mismatch on the console suggests the static deploy failed. 

I recently was talking to Jason about how this worked and old statics are not removed so this case can only really come about when the static deploy breaks. If we're still serving old html we still have the old statics on the CDN, whereas if there aren't newer statics to match the hashes in the HTML it will break like this as SRI prevents the resources from loading.

**Comment by muffinresearch** [comment]
I'll see I can re-run the deploy via Jenkins.

**Comment by muffinresearch** [comment]
> I'll see if I can re-run the deploy via Jenkins.

The pipeline looks stuck/paused although it's unclear if that's expected. 

It might work if we cut a new tag but it doesn't look like I can restart it from the jenkins interface.

**Comment by tofumatt** [comment]
Pushed a new tag with the sa,e contents to trigger a new deploy and all is well!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-stage FF54(Win 7, Android 7.1.2)
Postfix video:
![desktop](https://user-images.githubusercontent.com/15685960/27385457-6d990a8c-569b-11e7-8091-8d8a706a745f.gif)
