### ISSUE TITLE
Convert featured add-ons to load data with a saga

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2620]
Convert the featured add-ons component to load its data with a saga instead of async-connect.

Steps to test for regressions:
* Go to [more featured add-ons](https://addons-dev.allizom.org/en-US/android/extensions/featured/)
* Make sure the page still works

This is a step towards https://github.com/mozilla/addons-frontend/issues/2356

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
The link you provided returns a 502 Bad Gateway page.... as everything on dev (https://github.com/mozilla/addons-server/issues/6026).
Please see screenshot:
![2017-07-27_0954](https://user-images.githubusercontent.com/15685960/28657943-ca37dbb0-72b1-11e7-86ec-6425b8954743.png)

**Comment by kumar303** [comment]
The dev server is back! Sorry about that. See https://github.com/mozilla/addons-server/issues/6026

**Comment by ValentinaPC** [comment]
@kumar303 : I you sure the link - https://addons-dev.allizom.org/en-US/android/extensions/featured/ - is correct?
Shouldn't be: https://addons-dev.allizom.org/en-US/android/extensions/?sort=featured ?
Because accessing the your link returns a 404 page.
![404](https://user-images.githubusercontent.com/15685960/28705793-0b771dac-737a-11e7-885b-1c4e03d3dba4.png)

Thanks!

**Comment by kumar303** [comment]
Yes, the link is correct: https://addons-dev.allizom.org/en-US/android/extensions/featured/

You need to first make sure you are "pinned" to the desktop site by way of a cookie. Since the desktop site is not live yet you need to view the mobile site first by clicking 'View mobile site' in the footer of https://addons-dev.allizom.org/en-US/firefox/ As long as you are using a desktop browser, it will show you the new desktop site. It's a bit confusing, sorry about that!

**Comment by kumar303** [comment]
Actually, it would be better to verify this particular feature on an Android device since that is where we need to protect against regressions the most.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7, Android 7.2.1)
Both https://addons-dev.allizom.org/en-US/android/extensions/featured/ and https://addons-dev.allizom.org/en-US/android/themes/featured/ are working as expected.
Tried also for different languages - works as expected.
![2017-07-31_1049](https://user-images.githubusercontent.com/15685960/28767846-06689e38-75de-11e7-86fd-11f0158ad798.png)
