### ISSUE TITLE
Need icons for every category

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2621]
The mocks for categories feature an icon for the category but looking through the sketch file I can't find the list of icons for each category. Could you please provide these icons? They are:

#### Extensions

* [x] Language Support
* [x] Feeds, News & Blogging
* [x] Download Management
* [x] Alerts & Updates
* [x] Bookmarks
* [x] Appearance
* [x] Games & Entertainment
* [x] Other
* [x] Photos, Music & Videos
* [x] Privacy & Security
* [x] Search Tools
* [x] Shopping
* [x] Social & Communication
* [x] Tabs
* [x] Web Development

#### Themes

* [x] Abstract
* [x] Causes
* [x] Fashion
* [x] Film and TV
* [x] Firefox
* [x] Foxkeh
* [x] Holiday
* [x] Music
* [x] Nature
* [x] Other
* [x] Scenery
* [x] Seasonal
* [x] Solid
* [x] Sports
* [x] Web Sites

-----

I'm referring to this bit, by the way:

<img width="424" alt="screenshot 2017-06-21 23 05 56" src="https://user-images.githubusercontent.com/90871/27408760-2f4ec600-56d6-11e7-836d-95800d8dbe34.png">

**Comment by tofumatt** [comment]
Sorry I didn't catch this earlier. 😢

**Comment by tofumatt** [comment]
I figure this will take some time... also depending on the licensing @sarahmonster pointed out I can probably grab icons from the Noun Project for a lot of these, though if I should just refrain from that because we want a specific style let me know. Otherwise I could have a look.

**Comment by pwalm** [comment]
We have picked an icon kit, just waiting on budget approval. (I'll provide SVGs shortly anyway)

**Comment by pwalm** [comment]
Icons:
![screen shot 2017-08-01 at 12 00 14 pm](https://user-images.githubusercontent.com/6797635/28842041-03051dc4-76b1-11e7-9e1e-4acb40d39414.png)

Actual SVG magic to follow shortly

**Comment by pwalm** [comment]
oops, closed by accident 👯‍♂️

**Comment by pwalm** [comment]
Revised. Just got to tweak some svg code and we'll be ready to rock.

<img width="593" alt="screen shot 2017-08-04 at 11 51 47 am" src="https://user-images.githubusercontent.com/6797635/28982608-541fb212-790b-11e7-9ac5-9edb7ca7fc91.png">

**Comment by pwalm** [comment]
[Files are here](https://github.com/mozilla/addons-frontend/tree/master/assets/category%20icons)!

In the svg code, I've added the classes "one" and "two" to the corresponding stroke weights (thick/thin) of the icons. So we can apply some cool duotone colouring at larger scales (like on the category detail pages.

**Comment by ValentinaPC** [comment]
@pwalm : Is this fixed?
I cannot see an icon for any category.
Thanks!

**Comment by tofumatt** [comment]
This issue was just to create the icons. They don't appear yet; no QA is needed.
