### ISSUE TITLE
Get add-on icon more safely

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2623]
We use this line of code a lot:

```js
const iconURL = isAllowedOrigin(addon.icon_url) ? addon.icon_url : fallbackIcon;
```

We should wrap this up in a function because it would be a shame if someone forgot to check the origin of the icon URL.

**Comment by tofumatt** [comment]
It actually happened! #2529

So yeah this is a good idea. Not using it also makes testing weird if you're using stage data or something because the icon would load on a page missing the check.

**Comment by tsl143** [comment]
@kumar303  Is https://github.com/mozilla/addons-frontend/pull/2638 is what we require to do for this?
