### ISSUE TITLE
If you try to open an incomplete webextension on mobile, the amo will be blocked on the "Server error page"

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2624]
Steps to reproduce:
1. On Android, AMO Stage,  try open an Incomplete webextension (as described in https://github.com/mozilla/addons-server/issues/5588) . The "WebExt-simple-stage" can be found in Extensions section, under "More popular extensions" on your device
2.Observe the "Server error" page for this
3.Try to navigate away from this page(by pression on another section like Themes or by press homepage puzzle icon)

Expected results:
User should be able to navigate away from this page without any problems

Actual results:
User is not able to navigate away. If you want to use Stage again , you have to reload the page from url bar

NOTES:
This issue is logged in order to handle this type of error pages better. The listing of Incomplete webextensions issue will be solved in addons-server bug : https://github.com/mozilla/addons-server/issues/5588

Please see video of the issue :  
![nocompatversmobile](https://user-images.githubusercontent.com/1583842/27444528-5256c374-577f-11e7-9ad3-0e8d483386b2.gif)

**Comment by muffinresearch** [comment]
@vcarciu is this still an issue?

**Comment by vcarciu** [comment]
@muffinresearch : sorry for late response. Not a problem anymore
