### ISSUE TITLE
Use description/summary as fallback for each other in reducer

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2626]
We have a few bits of code that check for description or summary as sometimes only one is set–what's especially confusing is the fallback for themes is opposite the one for extensions. Right now we check in components, hence this comment: https://github.com/mozilla/addons-frontend/pull/2618#discussion_r123539791

Really we should just set the description and summary properly in the reducer.

**Comment by willdurand** [comment]
This is now invalid because of #6058 and https://github.com/mozilla/addons-frontend/issues/5364#issuecomment-404312967.
