### ISSUE TITLE
Show placeholders for 'more info' on Add-on detail page when loading

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2629]
### Describe the problem and steps to reproduce it:

* Search for an add-on
* Tap on a search result
* Watch the add-on detail page load

### What happened?

You will see placeholders for the data as it gets loaded from the API.

### What did you expect to happen?

You should see placeholders for the 'more info' section ([`AddonMoreInfo`](https://github.com/mozilla/addons-frontend/blob/c3a616ce6e92a00a94659811709263c8e01fca65/src/amo/components/AddonMoreInfo.js)) but instead this section is hidden until the add-on data loads from the API. It's not essential to show placeholders for this section but it would make the transition to the fully loaded view a bit less jarring.

### Anything else we should know?

Placeholders were initially added to the add-on detail page in https://github.com/mozilla/addons-frontend/pull/2602

**Comment by SeanPrashad** [comment]
Hey guys - I doing some light triaging for the `contrib: welcome` issues and noticed that this might be fixed.

I was using Redux Devtools to try and reproduce it, but the action just before the add-on data is loaded seems to have placeholders now:

![before_and_after_redux_actions](https://user-images.githubusercontent.com/13009507/47274375-99e96d00-d572-11e8-9fcb-6d2ac460eae8.gif)

**Comment by SeanPrashad** [comment]
Hey guys - I was doing some light triaging on the `contrib: welcome` issues whilst I was waiting on a response for #6368.

I don't seem to be able to reproduce this locally with Redux Devtools. I've found the actions that occur before and after the addon data is retrieved, but it looks like there's a `LoadingText` component in place now:

![before_and_after_redux_actions](https://user-images.githubusercontent.com/13009507/47273824-5fc79d80-d569-11e8-93ec-c080f40b712d.gif)

**Comment by SeanPrashad** [comment]
Hey guys - I was doing some light triaging on the `contrib: welcome` issues whilst I was waiting on a response for #6368.

I don't seem to be able to reproduce this locally with Redux Devtools. I've found the actions that occur before and after the addon data is retrieved, but it looks like there's a `LoadingText` component in place now:

![before_and_after_redux_actions](https://user-images.githubusercontent.com/13009507/47273824-5fc79d80-d569-11e8-93ec-c080f40b712d.gif)

**Comment by willdurand** [comment]
indeed, thanks!

**Comment by willdurand** [comment]
indeed, thanks!

**Comment by willdurand** [comment]
indeed, thanks!

**Comment by willdurand** [comment]
indeed, thanks!

**Comment by willdurand** [comment]
indeed, thanks!

**Comment by AlexandraMoga** [comment]
I'm still able to reproduce the issue mentioned in the above steps. For me, the 'More add-ons...' card is reloaded completely at page refresh.
The same can be observed with the 'More themes by author' and the 'Recommendations' cards

![placeholders](https://user-images.githubusercontent.com/31961530/47289245-6eae5e80-d602-11e8-8115-da80fb31c572.gif)

**Comment by willdurand** [comment]
It is the More Info card, not the more add-ons.
