### ISSUE TITLE
`jest --watch` runs tests twice after editing a file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2639]
### Describe the problem and steps to reproduce it:

Run `yarn test`, edit a file.

### What happened?

Sometimes the tests are run twice

### What did you expect to happen?

They should only be run once for each file change

### Anything else we should know?

This is happening because our [WebpackIsomorphicToolsPlugin](https://github.com/mozilla/addons-frontend/blob/65d4e802edad8b78f0df955e363ef38214179c5d/webpack.prod.config.babel.js#L52) auto-generates a `webpack-assets.json` file. The change to this file triggers a second test run.

It is not yet possible to [ignore changes to this file](https://github.com/facebook/jest/issues/3923) and I haven't found a good workaround yet.

**Comment by kumar303** [comment]
To clarify: the `webpack-assets.json` file is only getting generated because of `yarn dev:amo` (which is typically running in a separate shell for me) which has its own watcher/builder.

**Comment by muffinresearch** [comment]
@kumar303 is this still happening?

**Comment by kumar303** [comment]
Yes but there is now an option called [`watchPatchIgnorePatterns`](https://facebook.github.io/jest/docs/en/configuration.html#watchpathignorepatterns-array-string) that we can use to fix it! I think we just need to ignore all the things that webpack touches on a rebuild (`sri.json`? I forget).
