### ISSUE TITLE
Figure out the l10n story

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#264]
The data will be localized to some degree but we will still need to handle some localization within the apps.

**Comment by mstriemer** [comment]
We have some template strings in some places, we'll need to update them to use format or find a way to handle them in extraction.

```js
_(`Preview ${theme}`)

**Comment by muffinresearch** [comment]
We discussed this in Vidyo. Assuming there's not any problems from the l10ners perspective we're thinking the easiest starting point will be to use i18n-abide and extract into `/src/[app]/locale` initially.

I've emailed matjaz to see what his thoughts are on it.

**Comment by muffinresearch** [comment]
* [x]  Decide on the directory setup for the locales.
  _Plan here is to use a locale directory in the main tree and specialize by app. Each app localization (per-locale) must have both the core and app specific strings extracted into them._
* [ ]  Decide if we need to hookup the l10n to state
* [ ]  Extract strings. Must cover *both* the server code and client-side code.
* [ ]  Setup server-side gettext func
* [ ] Setup client-side gettext func
* [ ] Check handling of JS template strings + substitutions.

**Comment by muffinresearch** [comment]
I'm going to file some smaller bugs to cover the l10n stuff.

**Comment by Ryuno-Ki** [comment]
@muffinresearch When mentioning this ticket, you can easily spot the status of those other issue here (thereby converting this issue to a meta-ticket).
