### ISSUE TITLE
Create a horizontal card list view

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2640]
We need a horizontal add-on view for landing pages and other pages in the mocks.

Here for posterity, PR incoming!

**Comment by SVSanta** [comment]
Verified as fixed on AMO-dev FF45(Win 10)
Postfix screenshots:
![h extensions](https://user-images.githubusercontent.com/28138132/28309673-c09de604-6bb2-11e7-8855-aa45f327be4a.PNG)
![h themese](https://user-images.githubusercontent.com/28138132/28309674-c09f64de-6bb2-11e7-837e-6923dc69fd04.PNG)
