### ISSUE TITLE
Padding is off on rtl horizontal cards

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2645]
The horizontal add-on cards on desktop should not have padding that gets the icon out-of-alignment with the header text. But it does on RTL:

<img width="981" alt="screenshot 2017-06-28 09 10 42" src="https://user-images.githubusercontent.com/90871/27648009-0a654d80-5be2-11e7-96a0-f5490254d7b2.png">

**Comment by vcarciu** [comment]
This looks fixed: 
![rtlpadding](https://user-images.githubusercontent.com/1583842/27688692-2aecca94-5ce4-11e7-8c9e-02f052ee81c4.png)
