### ISSUE TITLE
Complete themes cause an error because they are unsupported

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2646]
### Describe the problem and steps to reproduce it:
See the error here: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/618227/

Visit https://addons-dev.allizom.org/en-GB/android/addon/firefox-2-theme-for-firefox-3x/ when *signed out*, and there will be an error. This is because we don't support complete themes in `validAddonTypes`, but evidently we should 😄 

### What happened?
There was an error.

### What did you expect to happen?
No error!

### Anything else we should know?
Easy fix, incoming.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Postfix screenshot:  
![ct](https://user-images.githubusercontent.com/15685960/27663592-c225b49e-5c6b-11e7-9857-64c1ff4448c7.png)
