### ISSUE TITLE
No results listed in add-ons categories

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2650]
Steps to reproduce:
1. Load categories page https://addons-dev.allizom.org/en-US/android/extensions/categories/
2. Click on any category i.e. https://addons-dev.allizom.org/en-US/android/extensions/photos-media/

Expected results:
Add-ons from that category are listed.

Actual results:
No add-ons are listed,

Notes/Issues:
Verified on FF54(Win 7).
Issue is only reproducing on -dev.
Screenshot for this issue:
![noaddons](https://user-images.githubusercontent.com/15685960/27663835-ed94e310-5c6c-11e7-87be-f61cc40eeb0e.png)

**Comment by vcarciu** [comment]
Verified as fixed (for all categories):
![categresults](https://user-images.githubusercontent.com/1583842/27866340-a6382478-619e-11e7-97b6-f9186ddc10ca.png)
