### ISSUE TITLE
The label “Cancel preview” from a theme is not changing to “Tap to preview”

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#2651]
### Describe the problem and steps to reproduce it:
1.Install a theme, for example: https://addons.allizom.org/en-US/firefox/addon/dew-on-spider-web/ 
2.Open a new web page.
3.Go back to the page from where you installed the theme.

### What happened?
The label “Cancel preview” has not changed to “Tap to preview”.

### What did you expect to happen?
The label “Cancel preview” changes to “Tap to preview”, since the theme is not loaded anymore in the web page.

### Anything else we should know?
This issue is reproducing constantly on AMO-dev, stage and production servers.
Verified on Firefox 54 under Android 6.0.1
Please see the video for this issue:
![videotogif_2017 06 29_17 40 05](https://user-images.githubusercontent.com/15885467/27693490-4382de0a-5cf2-11e7-89b8-da0b122a3f36.gif)

**Comment by muffinresearch** [comment]
Previews have been removed.
