### ISSUE TITLE
Merge Categories and CategoriesHeader

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2653]
#2649 merged a component that is quite similar to the `Categories` component because there were a few differences and it was nice to land. But really we should get them to be the same because it should be easy to reuse them.

**Comment by tofumatt** [comment]
QA: To test this, make sure the list of categories at https://addons.mozilla.org/en-GB/firefox/extensions/ and https://addons.mozilla.org/en-GB/firefox/extensions/categories/ remain the same as before the PR.

**Comment by ValentinaPC** [comment]
> QA: To test this, make sure the list of categories at https://addons.mozilla.org/en-GB/firefox/extensions/ and https://addons.mozilla.org/en-GB/firefox/extensions/categories/ remain the same as before the PR.

For the second link you wanted to say "https://addons.mozilla.org/en-GB/firefox/extensions/category_name/"? Because that one is not working.
Thanks, @tofumatt !

**Comment by tofumatt** [comment]
The second link will only work on the new site.

**Comment by ValentinaPC** [comment]
So, when can we this be tested? :)

**Comment by tofumatt** [comment]
You can test it now but you’ll need to be viewing the mobile site only.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54( Win 7).
Each category is listed and redirects as expected from each page.
Postfix video:
![cat](https://user-images.githubusercontent.com/15685960/28629455-2799e1ae-7230-11e7-9f2c-b7171f6974ea.gif)
