### ISSUE TITLE
Paragraphs in description go way too wide

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2654]
The description text on a very wide desktop page doesn't wrap and looks weird. We should set a max width:

<img width="974" alt="screenshot 2017-06-29 19 12 38" src="https://user-images.githubusercontent.com/90871/27718201-318cf3cc-5cff-11e7-8faf-8db4a4fc8d91.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![widthdescription](https://user-images.githubusercontent.com/1583842/27867239-c918fba4-61a1-11e7-87de-954d0c077f53.png)
