### ISSUE TITLE
Categories should not be centred

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2660]
I centred the categories when they're on one line but it turns out this looks weird and detaches them from the card header. We should put them back in line with the header.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7, Android 7.1.2)
I suppose you are talking about the categories labels from https://addons-dev.allizom.org/en-US/firefox/extensions/ ?
If yes, they are not centered.
Postfix screenshot:
![cat](https://user-images.githubusercontent.com/15685960/28007393-e41ae72e-655b-11e7-849d-6b3c748c34c6.png)
