### ISSUE TITLE
Mouse cursor should be pointer on Review submit Link/button

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#2669]
### Describe the problem and steps to reproduce it:
1. Navigate to any addon page - https://addons.mozilla.org/en-US/firefox/addon/vimfx/?src=hp-dl-featured#
2. Click on review stars.
3. Popup opens for review text
4, Hover over submit option

### What happened?
Cursor did not change

### What did you expect to happen?
Cursor should be pointer type.

### Anything else we should know?
Screenshot
![photo6255835573222746050](https://user-images.githubusercontent.com/5318732/27789559-ba198602-600a-11e7-8862-e9e6e90f269d.jpg)

**Comment by tofumatt** [comment]
We tend not to change the cursor type on buttons, so I’m not sure this is valid. Though I guess we do for header links that look like buttons, so maybe we should.

Thoughts @pwalm?

**Comment by muffinresearch** [comment]
If it's a button then the cursor won't change. Maybe another way of looking at this issue is that the submit button here doesn't look like a button?

https://github.com/mozilla/addons-frontend/blob/9c192bef624c4405cdbe5fd10b0771c2d765d741/src/amo/components/AddonReview.js#L179

**Comment by pwalm** [comment]
Make it pointer! Should be that way for all buttons/links.

**Comment by tsl143** [comment]
Awesome, simple and effective :)

**Comment by tsl143** [comment]
This fix does only for `addonReview` page, are we planning to do this globally?

**Comment by pwalm** [comment]
Globally.

**Comment by muffinresearch** [comment]
@pwalm I don't think we should make buttons have a hand cursor only links should have them. Changing buttons to have a pointer cursor breaks long established conventions both in the browser and in operating systems. See https://medium.com/simple-human/buttons-shouldnt-have-a-hand-cursor-b11e99ca374b and https://ux.stackexchange.com/questions/105024/why-dont-button-html-elements-have-a-css-cursor-pointer-by-default for further explanations.

Here's a JSbin showing the defaults: http://jsbin.com/lebeyov/edit?html,output

IMHO it follows that ideally we shouldn't have any button elements that don't look like buttons. Especially on a form.

**Comment by pwalm** [comment]
Hmm, I'm seeing a mix of both "pointer for everything" and "pointer for links" on a few different sites, but reading that post has steered me to only showing pointer on links only.

**Comment by muffinresearch** [comment]
> Hmm, I'm seeing a mix of both "pointer for everything" and "pointer for links" on a few different sites, but reading that post has steered me to only showing pointer on links only.

Ok based on that I'm going to close this issue and the related pull request.
