### ISSUE TITLE
Restrict max-width of content

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2680]
There's a few pages that don't look too good if run on a maximized browser with lots of pixels.

E.g:

<img width="2549" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/27798996-6a4600aa-600b-11e7-86c9-940e6dd9db6f.png">

Would this work better if constrained? E.g: here's an example using 1400px:

<img width="2555" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/27799408-f9281e10-600c-11e7-9e9d-4170fa9d64fa.png">

**Comment by pwalm** [comment]
Constrain that sucker at 1366px wide.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Width is constraint at 1366px.
Postfix screenshot:
![2017-09-12_1527](https://user-images.githubusercontent.com/15685960/30325842-fa9eb34a-97ce-11e7-9182-1e3cd7c75a3f.png)
