### ISSUE TITLE
Uninstalling an add-on shows incorrect switch state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2681]
### Describe the problem and steps to reproduce it:

* Make sure you are set up to [see install switches](https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md)
* Install an add-on and leave the AMO tab open
* Go to `about:addons` and remove the add-on
* Change back to the AMO tab

### What happened?

The switch changed state but it changed to a loading stage, like this (but animated):

<img width="322" alt="screenshot 2017-07-03 13 38 37" src="https://user-images.githubusercontent.com/55398/27804565-3c7e9eea-5ff5-11e7-9ee2-df6063ffaf21.png">

### What did you expect to happen?

It should change to an uninstalled state

### Anything else we should know?

If you refresh the AMO tab, the switch is rendered in the correct uninstalled state

**Comment by kumar303** [comment]
meh, this seems to be an `about:addons` issue

**Comment by kumar303** [comment]
Specifically, the `about:addons` page has an "undo" feature which sort of explains what's happening. When you refresh the `about:addons` page, it "commits" the change and everything looks as expected.

**Comment by SVSanta** [comment]
Verified this on AMO-dev FF54(Android 6.0.1).
Postfix gif:
![addon uninstall state](https://user-images.githubusercontent.com/28138132/27868445-5d7f50ba-61a5-11e7-9e87-16bf0eac3f70.gif)

**Comment by kumar303** [comment]
Sorry, I forgot to label this as invalid. Nothing was added to address the problem. I don't think it's worth fixing because the `about:addons` page does some weird magic here.

**Comment by kumar303** [comment]
Also, I see from your screencast that this is only a desktop bug, not a mobile one. That's helpful to know, thanks!
