### ISSUE TITLE
Document how to set up localhost for add-on actions better

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2682]
There are a few localhost development things that aren't documented well:
* how to test theme previews
* how to fully install add-ons

**Comment by vcarciu** [comment]
@kumar303 
Where can we test this ?

**Comment by tofumatt** [comment]
Generally speaking, things in the documentation component shouldn't need QA, but I've marked this one explicitly. 😄

**Comment by vcarciu** [comment]
@tofumatt , thanks, I just asked in order to see if we have some links pointing to this doc from AMO , but I guess that we don't add the info about how to set things on localhost here

**Comment by kumar303** [comment]
@vcarciu sorry, I forgot the label. I think the info won't be so helpful for QA folks since you don't need to work with a local source checkout.
