### ISSUE TITLE
Category slugs are not proper in Home category tiles

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#2685]
### Describe the problem and steps to reproduce it:
1: Naviagte https://addons.mozilla.org/en-US/firefox/
2.Click Screenshot button in Home category div

### What happened?
Shows No result found

### What did you expect to happen?
Gives addons related to photos-media

### Anything else we should know?
The category slug is wrong in few tiles example For photo and media its `photos-media` it should be `photos-music-videos`

<img width="1280" alt="screen shot 2017-07-04 at 1 07 15 pm" src="https://user-images.githubusercontent.com/5318732/27819874-c63965ce-60b9-11e7-9655-5e1e82f54cc7.png">
<img width="1280" alt="screen shot 2017-07-04 at 1 07 30 pm" src="https://user-images.githubusercontent.com/5318732/27819873-c635ec64-60b9-11e7-976f-3b1047ff794f.png">

**Comment by SVSanta** [comment]
Verified this on AMO-dev FF54(Win 10 64Bit).
Postfix screenshot:
![screen1a](https://user-images.githubusercontent.com/28138132/27866641-d5d52180-619f-11e7-9d1e-0250da2fa38d.PNG)
