### ISSUE TITLE
Review form is too wide on desktop

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2687]
On desktop it looks like this one a large monitor:

<img width="2551" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/27837768-2b3323c4-60de-11e7-9049-d07e0ced2a2b.png">

The overlay's max width should be limited.

**Comment by muffinresearch** [comment]
Fixed by #3092

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(win 7).
Postfix screenshot:
![2017-09-12_1536](https://user-images.githubusercontent.com/15685960/30326251-a08ed75c-97d0-11e7-9b2a-196441ec9031.png)
