### ISSUE TITLE
Categories titles are not correctly aligned

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2688]
Steps to reproduce: 
1.Go to AMO-dev and open any add-ons category (https://addons-dev.allizom.org/en-US/firefox/extensions/feeds-news-blogging/)
2.Observe the Categories title

Expected results:
Categories titles are correctly aligned

Actual results:
Categories titles are not correctly aligned with the white background

NOTES:
I think that we can completely remove the white background as an easy fix

Please see screenshot for this issue : 
![categtitle](https://user-images.githubusercontent.com/1583842/27874317-c660e96a-61b7-11e7-9070-c80c8aa06b29.png)

**Comment by tofumatt** [comment]
Whoa, I didn't even ever *notice* that white background on my screens. Good catch!

Yeah, we'll just remove it 👍

**Comment by aayushsanghavi** [comment]
@tofumatt may I work on this?

**Comment by tofumatt** [comment]
Sure thing, thanks! 

Matthew Riley MacPherson (sent from mobile)

**Comment by vcarciu** [comment]
Verified as fixed : 
![categfix](https://user-images.githubusercontent.com/1583842/27904878-e253c324-6246-11e7-9566-cd7912e5ebbd.png)
