### ISSUE TITLE
[RTL] Extensions page title is not correctly aligned in RTL

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2689]
Steps to reproduce:
1.Go to AMO-dev , mobile view
2.Select extensions tab and then switch to any RTL language (https://addons-dev.allizom.org/ar/firefox/extensions/)

Expected results:
Everything looks on in RTL

Actual results:
Extensions page title is not correctly aligned in RTL

Please see a video for this issue:
![extrtl](https://user-images.githubusercontent.com/1583842/27874643-e8485b0c-61b8-11e7-8a28-63c54f855868.gif)

**Comment by tofumatt** [comment]
Hah, yeah, I think this is actually because the SVG has (mostly) whitespace on the end of it with a gust of wind or something faint in the background. Might make sense to use a different amount of margin in RTL.

**Comment by vcarciu** [comment]
Please note that this is strangely not repducible for Themes

**Comment by tofumatt** [comment]
See above comment: it’s actually because of the contents of the Extensions SVG. The issue isn’t inconsistent margins in CSS but that in LTR margins aren’t needed.

**Comment by vcarciu** [comment]
Verified as fixed : 
![rtlext](https://user-images.githubusercontent.com/1583842/28025849-2d74883a-659d-11e7-8f46-5c0a4e4b994b.png)
