### ISSUE TITLE
The tab selected before pressing back button is still underlined 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2690]
Steps to reproduce:
1.Go to AMO-dev and select mobile view
2.Navigate between home tabs (Explore, Extensions, Themes) 
3.Press back button

Expected results:
Previously selected tab si selected and underlined

Actual results:
The tab selected before pressing back button is still underlined 

Please see video for this bug : 
![underline](https://user-images.githubusercontent.com/1583842/27874922-0d23e3c8-61ba-11e7-83a6-4dddaa8f0423.gif)

**Comment by tofumatt** [comment]
This is because the link is still active, having been clicked on, and has an active style applied to it. Perhaps we want to remove that.

**Comment by muffinresearch** [comment]
If that's related to focus then we definitely need a distinct style for that. Maybe it should be different to the hover style in some way?

**Comment by muffinresearch** [comment]
Assigning to @pwalm for input on what a different focus style should look like.

**Comment by muffinresearch** [comment]
Seeing this in practice the style is different to the active state so I think this is actually a wontfix.

**Comment by muffinresearch** [comment]
Removed the wontfix and assigned to tofumatt since the header updates fixed this.
