### ISSUE TITLE
Unable to log in to AMO dev local development account

### ISSUE THREAD

**Issue by aayushsanghavi** [mozilla/addons-frontend#2696]
### Describe the problem and steps to reproduce it:
Click on the login button on the local dev environment of addons-frontend. Fill the login form and hit "Sign In".

### What happened?
Unable to log in to my "AMO-dev local development" account -

![screenshot from 2017-07-06 16-08-07](https://user-images.githubusercontent.com/19590302/27907738-61d0b59e-6238-11e7-8dcb-580d076dd347.png)

### What did you expect to happen?
Successful login

### Anything else we should know?
Some of the hundred console warnings -

![screenshot from 2017-07-06 16-14-54](https://user-images.githubusercontent.com/19590302/27907760-7a219000-6238-11e7-8a9b-c52094b0b349.png)
![screenshot from 2017-07-06 16-15-27](https://user-images.githubusercontent.com/19590302/27907761-7a22c5d8-6238-11e7-839b-784be58fd022.png)
![screenshot from 2017-07-07 00-47-54](https://user-images.githubusercontent.com/19590302/27928738-e305dc7e-627f-11e7-86f6-0e549ddc0285.png)

Tried dev:amo and dev:amo:no-proxy environments. Didn't work in either.
And I created an account and verified it earlier today (if it is any relevant)

**Comment by tofumatt** [comment]
Can you please attach a full *text* output of your console, possibly from the server? It would help to see what the errors are–most of those are just CSP errors which shouldn't be the issue. (Though you should set `CSP: false` in your `config/local-development.js` file to silence them as I bet they get annoying 😄 )

**Comment by aayushsanghavi** [comment]
My bad 😅. I mistook "console errors" for developer console errors. I'll put up the console errors right away.

**Comment by aayushsanghavi** [comment]
@tofumatt I've put it up but I don't see any errors as such. Also, I tried logging in again and I got this -

![screenshot from 2017-07-07 00-52-53](https://user-images.githubusercontent.com/19590302/27928972-bb2bcdde-6280-11e7-8e24-6630e2f7950a.png)

**Comment by muffinresearch** [comment]
@aayushsanghavi is this still an issue for you?

**Comment by kumar303** [comment]
I'm not sure if it's the exact same issue but logins are now fixed on dev. See https://github.com/mozilla/addons-frontend/issues/2941
