### ISSUE TITLE
Theme automatically applied when switching tabs

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#2697]
Steps to reproduce:
1. Press the "Alt" button and navigate to: "Tools>Add-ons".
2. Click on the theme "preview image".
3. Go to any other page in the browser.
4. Go back to the "about:addons" page.

Expected results:
The selected theme is not active.

Actual results:
The selected theme is active.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on all AMO servers.
Video Gif for this issue:
![disco pane bug1](https://user-images.githubusercontent.com/28138132/27917667-574b937c-6275-11e7-8a37-eca730a42009.gif)

**Comment by muffinresearch** [comment]
Since the new static themes don't support previews we may just remove previewing as a feature since it doesn't make sense to have a feature on the new amo frontend only to remove it later.

**Comment by muffinresearch** [comment]
Theme previews are removed.
