### ISSUE TITLE
Blank search will show no results for Explore tab

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2702]
Steps to reproduce:
1.On your Android device, go to AMO-dev
2.While Explore tab is selected,  perform a blank search

Expected results:
If blank search is allowed, a list of results is displayed

Actual results:
Number of results is displayed, but the list of results is missing

NOTES:
For Extensions or Themes tabs , blank search will show the results

Please see video for this issue : 
![blanksearchandroid](https://user-images.githubusercontent.com/1583842/27951355-469eb87c-630d-11e7-8c7c-1e6445ccc2a8.gif)

**Comment by muffinresearch** [comment]
@vcarciu it works like this in production so I'll move the blocks release, but it would be good to get this fixed for the next push in any case.

**Comment by muffinresearch** [comment]
A blank such should not result in a search request, instead we should show an error message and prevent submission. Unfortunately there's no visible search button so we can't simply disable it until it has meaningful input.

**Comment by tsl143** [comment]
@muffinresearch , will this solution work?

**Comment by tsl143** [comment]
Also shall I add, trimming blank spaces, to avoid blank space results?

**Comment by muffinresearch** [comment]
> @muffinresearch , will this solution work?

I think this needs some UX for showing a message when the user submits a search that is invalid.

> Also shall I add, trimming blank spaces, to avoid blank space results?

Yep, a search that is nothing but white-space should be prevented too.

**Comment by pwalm** [comment]
If a user triggers a blank search, we should show a helpful error message on the results page, along with our most popular extensions or themes. I've pinged Michelle Huebusch for some copy, will update this issue when it gets addressed.

**Comment by pwalm** [comment]
Copy: "Sorry! Enter a search term and try again."

**Comment by pwalm** [comment]
Scratch that: remove "Sorry." It should read "Enter a search term and try again."

OR

We could not let a user initiate a blank search?

**Comment by muffinresearch** [comment]
> We could not let a user initiate a blank search?

@pwalm if we had a visible submit we could do that more easily since the button would be disabled until there's valid content, without it I think it would make more sense to need to show a message instead.

**Comment by muffinresearch** [comment]
@pwalm do we have a design for how to present the message?

**Comment by pwalm** [comment]
Just below the search bar on the page after a blank search is launched. Same copy style as the "xxx,xxx add-ons found".

![add-ons - 2017-08-09 15 32 16](https://user-images.githubusercontent.com/6797635/29146897-93cf8d36-7d18-11e7-9c39-ab827248d564.jpg)

**Comment by ValentinaPC** [comment]
Now we have navigation also, in this page.
Please see screenshot:
![prod](https://user-images.githubusercontent.com/15685960/29706009-049bce36-8989-11e7-9818-1aac163fe578.png)

**Comment by tsl143** [comment]
This has been taken care of in https://github.com/mozilla/addons-frontend/pull/2703, once it gets merged, this will he handled :)

**Comment by pwalm** [comment]
Why did this get reopened, do you need more guidance from ux?

**Comment by willdurand** [comment]
@pwalm nope, but this fix for this caused another bug (#3096). That is why it has been reopened. I removed the needs:ux tag though.

**Comment by tsl143** [comment]
@tofumatt , As you mentioned in https://github.com/mozilla/addons-frontend/issues/3096#issuecomment-328843898
What are the next steps?

**Comment by tofumatt** [comment]
You would need to have separate URLs with pagination support for `/featured/` etc. so they aren't using the search URL. Or there'd need to be a more flexible/param-aware check in search for when to show the "enter a query" bit. I like the idea of always using the search URL as much as possible because it means less mess of stuff like this but I'm not sure it'll work without having a lot of confusing code paths.

**Comment by tofumatt** [comment]
This now displays results, so I'm closing this. We should still show an "Enter a search term"... maybe... an empty search technically works and maybe we should just allow it.

**Comment by vcarciu** [comment]
This is now displaying "No-addons found" message on device, together with "Please enter a search term to search Firefox Add-ons" message. Please note that on desktop an empty search with explore tab selected will return results:
![blankl](https://user-images.githubusercontent.com/1583842/31127483-bb826136-a857-11e7-941c-42d8c3186c20.png)

**Comment by willdurand** [comment]
we now see all the results.
