### ISSUE TITLE
"About this <add-on type>" needs l10n for add-on types, and for some locales, a localizable "this"

### ISSUE THREAD

**Issue by TonnesM** [mozilla/addons-frontend#2705]
When viewing an add-on’s or theme’s details, "About this `<type>"` is displayed, probably taken from "About this %(addonType)s". This can be several items, such as add-on, theme, persona or (formerly?) extension. However these items display in English and are not available in the l10n files, so e.g. "Over deze extension" is displayed.

1) Please make sure all available items are available for l10n.
2) The "this" part may depend on the type for some locales, i.e. be gender related. Please make this possible. If needed, it may be best and easier to get rid of the type variable type and create separate strings, as was the case for "About this add-on"and "About this collection".

**Comment by EnTeQuAk** [comment]
This is happening in https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Addon/index.js#L273-L276

**Comment by vcarciu** [comment]
Verified as fixed : 
![aboutthis](https://user-images.githubusercontent.com/1583842/32556276-a8cba0c2-c4a7-11e7-8a12-2ad751e6a518.gif)
