### ISSUE TITLE
[suggestion] Correct dimesion logo image for social shares

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#2707]
### Describe the problem and steps to reproduce it:
I shared an addon on twitter.

### What happened?
The logo image rendered is blur

### What did you expect to happen?
The image should not be blur

### Anything else we should know?
The image rendered is of 64x64px and stretched  to 125x125.
The `meta property="og:image"` takes default 64px image, can we put 128x128px image in `og:image` (given its uploaded by developer)

**Comment by tsl143** [comment]
<img width="591" alt="screen shot 2017-07-08 at 8 41 31 am" src="https://user-images.githubusercontent.com/5318732/27982205-ee86d6b2-63b9-11e7-818c-055fe969d576.png">

**Comment by willdurand** [comment]
This has been fixed by #6525
