### ISSUE TITLE
On screens with width over 720 categories listing pages look weird

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2724]
Steps to reproduce:
1. Load any category page on desktop using the new pages format, while on larger screens (i.e width over 720) i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/appearance/

Expected results:
No gray padding on left side of the page.

Actual results:
Category name is expanded over the entire page while the results are on the right side of it.

Notes/Issues:
Verified on AMO-dev FF54(Win 7).
Screenshot for this issue:
![large](https://user-images.githubusercontent.com/15685960/28008306-a9bca3fc-655f-11e7-9277-16d8861f9602.png)

**Comment by tofumatt** [comment]
The issue here is we are missing (e.g. haven't yet implemented) extra components that go on the side of the page. The layout here is correct but is missing things like sort, etc.

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
oh...

**Comment by muffinresearch** [comment]
There's nothing here to fix aside from continuing with the work already underway so I'm going to close this one.

**Comment by ValentinaPC** [comment]
@tofumatt : beside sort - that you guys decided to remove it from every category page, what else needs to be added here? Thanks!

**Comment by tofumatt** [comment]
Nothing I think? I would say #3092 actually solves this entirely.

**Comment by ValentinaPC** [comment]
Still look weird, but if you think is ok. Will do it for me too.

**Comment by willdurand** [comment]
I also tend to think something is missing here. Would full-width make sense?

**Comment by ValentinaPC** [comment]
If there isn't anything else to be added in this pages, full - width, as @willdurand suggested above, will look cleaner and nicer.
What do you think, @tofumatt ?

**Comment by tofumatt** [comment]
That looks nice, though eventually we'll want to add the filters and other things. It's just a technical limitation that prevents them from appearing for now.
