### ISSUE TITLE
Different colors for categories inside and outside of containing pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2726]
Steps to reproduce:
1. Load Extensions homepage i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Click on any category to load corresponding page 

Expected results:
Label color from extensions homepage is the same as inside that category.

Actual results:
Colors differ.

Notes/Issues:
- for Themes homepage the labels are only in a green scale and not multicolored (but the initial issue is not reproduced)
![themes](https://user-images.githubusercontent.com/15685960/28017180-ac02f8ac-6580-11e7-8f3c-9d4815027f33.png)

Verified on FF54(Win 7).
Video for this issue:
![ext](https://user-images.githubusercontent.com/15685960/28017924-d90a8812-6583-11e7-89a6-e1f10b10e5da.gif)

**Comment by tofumatt** [comment]
The colours are different for themes and extensions, just so you know.

I’ll have a look at this though! Seems we can do better with these colours :-)

**Comment by ValentinaPC** [comment]
> the colors are different for themes and extensions, just so you know.
I know... but... seems a bit weird to be only green shades for themes. And also different colors for extensions while in Extensions homepage or inside a category.
![dmdm](https://user-images.githubusercontent.com/15685960/28018330-8b49c5d2-6585-11e7-8a99-c776deea85bd.png)

**Comment by brainzest** [comment]
This is the result after fixing
<img width="1278" alt="color_fix" src="https://user-images.githubusercontent.com/432669/28241996-fae5ae06-69bd-11e7-9201-41f1b9848f5d.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Colors are consistent for extensions and themes - inside and outside of categories pages.
Postfix screenshot:
![2017-07-19_1222_001](https://user-images.githubusercontent.com/15685960/28360362-e2998ca6-6c7d-11e7-9b02-5d329a579456.png)

@tofumatt : Colors for themes categories remain all green? Thanks!

**Comment by ValentinaPC** [comment]
1. Android platform i.e. https://addons-dev.allizom.org/en-US/android/
- Themes categories:
![themes](https://user-images.githubusercontent.com/15685960/28516780-14702244-706b-11e7-9c51-8933461e318b.png)
- Extensions categories 
![2017-07-24_1222](https://user-images.githubusercontent.com/15685960/28516943-904e9b48-706b-11e7-824d-8d3fb549b6cc.png)

2. Firefox platform i.e. https://addons-dev.allizom.org/en-US/firefox/
- Themes categories:
![f2](https://user-images.githubusercontent.com/15685960/28517015-bfc149de-706b-11e7-9f04-b049e2dd521b.png)
- Extensions categories:
![f1](https://user-images.githubusercontent.com/15685960/28517024-c630f9d6-706b-11e7-9d5e-baeadca1b703.png)

My question was if the "green section" stays the same ore you have something more colorful prepared for the green categories?
