### ISSUE TITLE
Themes homepage has layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2734]
Steps to reproduce:
1. Load AMO-dev Themes homepage on desktop https://addons-dev.allizom.org/en-US/firefox/themes/
2. Observe page

Expected results:
The page has no display or layout issues.

Actual results:
The page has layout issues.

Notes/Issues:
Verified on FF54(Win 7). Issue is only reproducing on AMO-dev.
Screenshot for this issue:
![th](https://user-images.githubusercontent.com/15685960/28052120-9e317e6a-6611-11e7-8efa-4cfdec9b10da.png)

**Comment by tofumatt** [comment]
What is the viewport size for the browser you're using, just so I can narrow down exactly where this is happening? :-)

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
Over 720px, but seems like is no longer reproducible...
I'll check it around and see if is happening again :(

**Comment by ValentinaPC** [comment]
No trace of this anymore.
