### ISSUE TITLE
Add-on description is changing at page refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2735]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/optional-permissions-example1/ on your desktop
2. Refresh the page

Expected results:
Nothing changes.

Actual results:
Add-on description changes.

Notes/Issues:
Verified on FF54(Win 7) on dirty and clean profile.
I've managed to reproduce it only on -dev.
Video for this issue:
![sum](https://user-images.githubusercontent.com/15685960/28053589-edba365e-6619-11e7-8076-ede1124e0f74.gif)

**Comment by muffinresearch** [comment]
Different data is present in the search versus the details page data. Only seems to happen if you get to the details page via the search and then refresh.

**Comment by muffinresearch** [comment]
Root cause is https://github.com/mozilla/addons-frontend/issues/1404

**Comment by muffinresearch** [comment]
Going to dupe this to #1404
