### ISSUE TITLE
If pressing on a category from bottom, the page is first scrolled to the top , then the category is opened

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2736]
Steps to reproduce:
1.On your Android device, go to AMO-dev
2.Select the Explore tab
3.Select Explore all categories link under page header
4.Scroll down and select a category from the bottom(ie. Sports & Games)

Expected results:
Category is directly opened

Actual results:
All page is scrolled up to the top and only after that the category is opened

Please see video for this issue:

![scrolltop](https://user-images.githubusercontent.com/1583842/28077243-e7a0e4a2-6669-11e7-8599-e1294713964c.gif)

**Comment by tofumatt** [comment]
This is a common issue across the site for any page that still uses `redux-connect`. It will be fixed when #2356 is fixed.

**Comment by kumar303** [comment]
Specifically, this will be fixed by https://github.com/mozilla/addons-frontend/issues/2857

**Comment by kumar303** [comment]
This was fixed in #2857
