### ISSUE TITLE
Convert search to load data with a saga

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2737]
We should migrate the search to use reduxs-saga. Related to #2356.

Steps to test for regressions:

* Search for add-ons
* Search should load instantly with loading text placeholders while searching
* Content should then appear

Blank searches should not be allowed and should display an error.

**Comment by tofumatt** [comment]
Because of the DNT stuff I'm gonna push this to the next milestone, sorry all 😞

**Comment by ValentinaPC** [comment]
> Search should load instantly with loading text placeholders while searching

- like this:
![place](https://user-images.githubusercontent.com/15685960/29372900-21ca4eea-82b5-11e7-9ac1-cd9115a6cf27.png)
?

**Comment by tofumatt** [comment]
Yes :-)

**Comment by ValentinaPC** [comment]
> Blank searches should not be allowed and should display an error.
- blank search are blocked only in Explore - intended?

Verified this on AMO-dev FF54(Win 7)
Search is working as expected.
