### ISSUE TITLE
Setup statics to be served from the relevant CDN

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#274]
Right now we're serving the code all from /. Ideally the static resources should be served from the relevant CDN.

~~This is blocked by #272~~

**Comment by muffinresearch** [comment]
Note: the disco pane will only run script from a new host as opposed to the AMO CDNs, the CSP config needs to be updated to that and test it too.

**Comment by muffinresearch** [comment]
Blocked by https://bugzilla.mozilla.org/show_bug.cgi?id=1271684 and https://bugzilla.mozilla.org/show_bug.cgi?id=1271679

**Comment by jasonthomas** [comment]
This has been setup on -dev and stage.

**Comment by muffinresearch** [comment]
Thanks @jasonthomas
