### ISSUE TITLE
Show username and user menu when user is logged in

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2744]
When signed in, the username and a user menu should appear in the top right of the page where the "log out" button currently resides.

<img width="616" alt="screenshot 2017-07-12 00 43 03" src="https://user-images.githubusercontent.com/90871/28095597-25e7f1b6-669b-11e7-946c-1caea42e7abd.png">

**Comment by willdurand** [comment]
Updated mockup:

![auth](https://user-images.githubusercontent.com/217628/29464730-0d44e4fc-8437-11e7-97a4-0f4d7aab165e.png)

**Comment by willdurand** [comment]
fixed by #2994

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1).
Postfix screenshots:
![2017-09-13_1100](https://user-images.githubusercontent.com/15685960/30366471-d337cf58-9873-11e7-90b8-d204a07a126b.png)
![2017-09-13_1107](https://user-images.githubusercontent.com/15685960/30366474-d5576762-9873-11e7-9c13-577f8214cb51.png)
