### ISSUE TITLE
Show tools menus/links for signed in, authenticated users

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2745]
If a user is signed in to AMO and has any relevant permissions for tools, we should display a tools menu.

Note: this doesn't seem to be in the UX mocks so this needs UX. It might simply fit well in the user menu from #2744.

Tools menus are:

* Reviewer Tools
* Admin Tools
* Localizer Tools

Existing menu:

<img width="333" alt="screenshot 2017-07-12 00 46 21" src="https://user-images.githubusercontent.com/90871/28095714-de7b06e6-669b-11e7-82d3-b079064d22d5.png">

**Comment by willdurand** [comment]
Looks like it is now part of the mockups, see: https://github.com/mozilla/addons-frontend/issues/2744#issuecomment-323378139.

**Comment by vcarciu** [comment]
The specs have changed a lot here, but we can keep this open until implemented. New specs : 
https://user-images.githubusercontent.com/6797635/29692108-37b5b102-88e3-11e7-9ae5-a11f9a6358fa.png

**Comment by willdurand** [comment]
#2994 has added the menu. I keep this issue open as we need to add more links now.

**Comment by willdurand** [comment]
@tofumatt it seems we does not deal with permissions in the app yet. We should start by doing this before being able to add the following links to the menu:

- Reviewer Tools
- Admin Tools
- Localizer Tools

**Comment by tofumatt** [comment]
@willdurand They are sent during the login API step (http://addons-server.readthedocs.io/en/latest/topics/api/auth_internal.html#get--api-v3-accounts-login-)... which I'm just realising could cause issues if permissions are updated during site usage, but maybe we can still get them without logging in again–I forget how often we re-check the auth endpoint for new info about the existing user.

**Comment by kumar303** [comment]
I was late to the IRC conversation but I don't think we need to block this on getting any API changes. We can only get permissions on login currently but that will be fine 90% of the time.

**Comment by willdurand** [comment]
@kumar303 yes but we have not way to get it on the server right now. We could add more information to the cookie though. However, this is not nice for UX if you have to logout/login to get access to something you did not have access to before.

**Comment by kumar303** [comment]
Yes, adding permissions to the user profile endpoint would be ideal. I was just saying doing a logout/login after someone grants you admin privileges is something we could live with if needed.

**Comment by willdurand** [comment]
Ah ok. I have requested the API change at: https://github.com/mozilla/addons-server/issues/6415. I am going to work on the cookie-based version.

**Comment by willdurand** [comment]
Actually, we need an API change because we never call [the `login` endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/auth_internal.html#get--api-v3-accounts-login-). This old code is going to be removed in #3145.

**Comment by kumar303** [comment]
I know this is a simple patch now that we have the new API data but I think we could defer this until after MVP; the workaround is for reviewers/localizers/admins to keep bookmarks for all the URLs they need.

**Comment by kumar303** [comment]
As a prerequisite, we need to store user permissions in state https://github.com/mozilla/addons-frontend/issues/3702

**Comment by willdurand** [comment]
this issue has been fixed a while ago
