### ISSUE TITLE
Create a drop down menu under "Extensions" link in header

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2746]
“More Add-ons” with drop down menu: Language Tools, Search Providers, Dictionaries.

Complete themes were in this list but I should think they are not worth surfacing in the new front-end. They will not be usable by anyone but ESR users... I think if they want that feature it should be added later and only viewable by a browser with an older version.

This may need UX.

**Comment by pwalm** [comment]
I want to get “This may need UX.” On a t-shirt. 😆 

We could add “more” to the list of high level links in the header. Are these things in “more” important enough to get real estate at the top of the page? Could these links live in the footer?

**Comment by tofumatt** [comment]
They're things like dictionaries, search tools, etc. I don't *feel* like they're that important but that's probably something @jvillalobos has numbers on and knows.

@jvillalobos Could we move things like dictionaries, search tools, etc. to the footer? Are they commonly accessed?

**Comment by jvillalobos** [comment]
Dictionaries and language packs have very significant usage ([for example](https://addons.mozilla.org/en-US/firefox/search/?sort=users&platform=all&appver=any&atype=5)). I don't have stats on search tools handy, but I suppose they're all on the same boat / secondary menu.

We eventually want them to use WebExtensions APIs, so they would eventually be extensions, maybe with a special category or tag. For now, though, I think they should have more visibility than the footer.

**Comment by vcarciu** [comment]
The new specs from https://user-images.githubusercontent.com/6797635/29692108-37b5b102-88e3-11e7-9ae5-a11f9a6358fa.png are the updated one, so I will change the title accordingly

**Comment by muffinresearch** [comment]
We decided not to do this.
