### ISSUE TITLE
Add extra links to footer

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2748]
Links that need adding from the old site:

* Report Trademark Abuse
* Site Status
* About
* Creative Commons License

Note that these are missing from the UX mocks so we'll need guidance on where to put these.

**Comment by pwalm** [comment]
We may not need all of these, I know legal said it was ok to drop some boilerplate from the Mozilla footer. I’d say the footer from mozilla.org as guidance for now, as a new common footer component is en route.

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/addons-frontend/issues/3158

**Comment by ValentinaPC** [comment]
This can be marked as verified fixed based on #3158 .
