### ISSUE TITLE
Reveal add-on ID by clicking/hovering on icon

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2750]
According to @jvillalobos, this exists on the current site (though I couldn't get it to work–maybe it's a staff-only feature?) and is useful for debugging.

I'm guessing it's the database ID that should be shown here? @jvillalobos?

**Comment by jvillalobos** [comment]
It should work for everyone, even when logged out:
1) Go to a listing page, [like this one](https://addons.mozilla.org/addon/privacy-badger17/).
2) Click on the extension icon (the badger face in this case).

The URL in the location bar should include the add-on database ID now (https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/#id=506646)

**Comment by muffinresearch** [comment]
Would there be any objections to showing this in the metadata? Otherwise this is a bit of a [mystery meat](https://en.wikipedia.org/wiki/Mystery_meat_navigation) 🍖 feature. For example @wagnerand didn't know this feature existed until recently and as a reviewer he's someone who probably could have made use of it.

**Comment by tofumatt** [comment]
Oh, I see!

I would prefer not to pollute the URL with that info, any chance you'd mind if we just stuck it in the metadata or something? It seems fine to expose to all users and I find the hidden nature of this feature a bit strange.

**Comment by tofumatt** [comment]
@muffinresearch Omg twinsies!

**Comment by jvillalobos** [comment]
Exposing it elsewhere wfm, as long as we don't have to rely on add-ons surfacing it. WebExtension add-ons don't work on AMO, after all.

**Comment by tofumatt** [comment]
> WebExtension add-ons don't work on AMO, after all.

Maybe this is a joke but I am totally confused by this statement.

**Comment by wagnerand** [comment]
@tofumatt no joking, https://bugzilla.mozilla.org/show_bug.cgi?id=1295324

**Comment by tofumatt** [comment]
Ohhhhh okay I understand what you meant. I thought you meant "WebExtensions won't be hosted on AMO". Yes, I knew they couldn't run on addons.mozilla.org. All good! 😄

**Comment by kumar303** [comment]
Can we just put the ID in the More Information section and show it all the time without any secret clicks?

**Comment by tofumatt** [comment]
@kumar303 I say yes. That seems fine, and it's an appropriate place to put slightly "techie" information.

**Comment by vcarciu** [comment]
Verified as fixed : 
![siteindentifier](https://user-images.githubusercontent.com/1583842/30485887-722cc6f8-9a37-11e7-8a85-e26c64c2f350.png)
