### ISSUE TITLE
User count should link to stats dashboard

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2751]
If signed-in user has access to an add-on's statistics dashboard, the user count should link to it.

Alternatively we could add a link next to the count with (View stats), as the contextual link on a small element like that feels like sub-par UX.

**Comment by muffinresearch** [comment]
This is important for the release because without a link we won't have access to stats from the new frontend.

**Comment by ValentinaPC** [comment]
@tofumatt 
Verified this on AMO-dev FF55(Win 7) new desktop pages and observed the following:
- no meter if stats are set to be public on Dev Hub or not, the link "Visit stats dashboard" will be displayed for author in add-on details page
- if set to be public, from Dev Hub, stats are still displayed only for author, and not for admins 
- do we need 2 links to redirect to stats page?
![stats_001](https://user-images.githubusercontent.com/15685960/30907970-df7e91ae-a384-11e7-862b-0e37945007ed.png)

What do you think?

**Comment by tofumatt** [comment]
I was wondering about this... but I think I’d like to link the review count to reviews as well. So I think whenever it’s possible to add more context to text (eg a link) I think it’s worth doing.

So yes I think two links are worth it.

- Matthew Riley MacPherson (sent from mobile)

**Comment by ValentinaPC** [comment]
Marking this as verified fixed based on the above comments.
