### ISSUE TITLE
Add badge for featured (featured add-on indicator)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2752]
If an add-on is featured, that should be exposed as a badge (as per the UX mocks).

API landed in https://github.com/mozilla/addons-server/issues/5769.

**Comment by willdurand** [comment]
Mockup:

![badge featured](https://user-images.githubusercontent.com/217628/29465038-1fdeac32-8438-11e7-90db-75feca640127.png)

**Comment by kumar303** [comment]
That mock is missing fonts. And, actually, my Sketch install is as well, d'oh.

**Comment by willdurand** [comment]
Arg, going to fix this 😞

**Comment by willdurand** [comment]
Just replaced the mockup.

**Comment by madalincm** [comment]
Verified as fixed in FF55(Win7) in addons-dev.allizom.org
Postfix screencast: 
![featuredextensionlabel](https://user-images.githubusercontent.com/15685441/29617559-f92a375c-881d-11e7-8fdf-77c4b749f4c8.png)
