### ISSUE TITLE
Add badge for needs restart

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2753]
If an add-on requires a restart, we should add a badge (in UX mocks).

Uses https://github.com/mozilla/addons-server/issues/5772, which is complete.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1)
The requires restart badge is added.

1. Fix from new desktop pages:
![desktop](https://user-images.githubusercontent.com/15685960/29772440-82d6ae18-8c01-11e7-8f78-f7ab2375dc1c.png)
2. Fix from device:
![device](https://user-images.githubusercontent.com/15685960/29772476-a7fe4ade-8c01-11e7-82b8-981f837f25e7.png)

Is this the intended position of the badges, or should we post them one under the other....I feel like we can skip some layout issues from when the label would be localizable , if we put them one under the other. Just a thought.
@kumar303 ?

**Comment by willdurand** [comment]
If the badges don't fit on a single row, they will appear one under the other.

**Comment by ValentinaPC** [comment]
Based on above comments I'll mark this issue verified-fixed.
