### ISSUE TITLE
Add badge for "Compatible with Firefox 57+"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2754]
If an add-on works with FF 57+, we should add a badge as per the UX mocks.

We can use `is_webextension` for this; no new API is needed.

**Comment by kumar303** [comment]
Which UX mocks? Is it in `AMO Desktop - Master.sketch`? I can't find it

**Comment by tofumatt** [comment]
It seems they've changed, but the badges are in Extensions Detail:
<img width="686" alt="screenshot 2017-08-17 22 58 20" src="https://user-images.githubusercontent.com/90871/29435603-97b56be0-839f-11e7-8dad-f65bacd22218.png">

That said, @muffinresearch and I chatted about this and going forward we should simply add a legacy badge instead of a "compat with 57+" for a few reasons:

1. every web ext will have this badge. A badge on "every" add-on is silly
2. we need to warn users of legacy anyway so a legacy badge needs to exist
3. "compatible with 57+" isn't really true as pre-57 FF versions worked with WebExt and maybe FF 70+ will have an API change and it won't be compatible

So really this should be "add a legacy badge to old extensions". Or it should just be closed 😅

**Comment by kumar303** [comment]
I feel like the incompatibility message that users will see after https://github.com/mozilla/addons-frontend/pull/2934 might be enough to address this.

**Comment by tofumatt** [comment]
Fair point, this seems less relevant even now and by the time the new front-end is live for desktop users #2934 should be fine. If anything the legacy badge should be implemented there... but I think the generic compat warning is fine as once #2912 lands we shouldn't be showing (many) incompatible add-ons to users anyway...

**Comment by willdurand** [comment]
Can we close this?

**Comment by tofumatt** [comment]
Indeed we can.

Note to QA: there won't be a badge; just an incompatibility notice as added in #2934.

**Comment by muffinresearch** [comment]
@tofumatt @kumar303 did product approve this decision to not add the badge? If so then this can stay closed. If not then we should get product input on the direction to take.

**Comment by tofumatt** [comment]
My recollection is that they agreed that by the time the site launched most add-ons would be 57+ compat and we DON’T show incompatible add-ons anyway. Plus, as mentioned, the badge is misleading because it’s not compatible with 57+ necessarily.

But we already have a notice for incompatible add-ons which we don’t even show anywhere by default. So this will appear on every add-on a user sees. I think it’s just noise.

- tofumatt

**Comment by diox** [comment]
Note: if you do decide to add the badge, you need to make it visible when any of `is_webextension` or `is_mozilla_signed_extension` are `true` (mozilla signed extensions may be compatible with 57+ without being WebExtensions).

**Comment by muffinresearch** [comment]
@jvillalobos can you let us know if you're happy for this to stay as is, relying on compat info or if we need to do something different and reopen this issue?

**Comment by jvillalobos** [comment]
I think it's okay to drop the label, since the new site should be better at hiding incompatible content and the timing looks right.
