### ISSUE TITLE
Add badge for "experimental add-on notice"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2755]
See https://addons.mozilla.org/en-GB/firefox/addon/add-to-collection/ on old site.

**Comment by willdurand** [comment]
Adding "needs: ux" since we do not have any badge/icon for this in the Sketch files. I think it would make sense to have a badge similar to the existing ones for "featured", "restart required".

ping @pwalm

**Comment by pwalm** [comment]
Badges!
<img width="686" alt="screen shot 2017-09-08 at 7 57 30 pm" src="https://user-images.githubusercontent.com/6797635/30236516-0064db12-94d0-11e7-8158-a9ee77d39e7b.png">

Will provide specs asap

**Comment by pwalm** [comment]
Specs!
![screen shot 2017-09-11 at 3 41 15 pm](https://user-images.githubusercontent.com/6797635/30300094-b5c2058c-9707-11e7-8e37-0848475f837f.png)

**Comment by pwalm** [comment]
I will provide svg icons for these badges, do we have a full list of all the options?

**Comment by tofumatt** [comment]
Looks like we want one for "Experimental Add-on"... though I have no idea what that really means. @jvillalobos: what's the point of labelling an add-on experimental, especially when we already have a "Beta" version feature?

**Comment by jvillalobos** [comment]
The experimental flag is global for an add-on, and it's meant to signify the add-on isn't quite ready for everyone to use. Generally it should be used for early stages of an add-on, or for add-ons that aren't meant for a very wide audience.

Beta versions are meant for distribution of test versions of well-established add-ons, like AdBlock Plus. We'll probably remove Beta versions in the future, since it's not a very well-designed feature and not used heavily.

**Comment by tofumatt** [comment]
To me, a user, those two things sound exactly the same to me though. I get the technical difference but it sounds like "Beta" would be a fine name for "Experimental Add-on" because it seems to be a way more commonly-used phrase. And then if an add-on doesn't have the global "beta" flag the "beta" version can just be the development version.

**Comment by willdurand** [comment]
@muffinresearch I saw you removed the `needs: ux` label. What should be done here? Adding the "compatible with ff 57+" badge?

**Comment by muffinresearch** [comment]
@willdurand oops - I've added that back

**Comment by willdurand** [comment]
Hi @pwalm, we need an icon for the experimental badge, nothing more for this issue :)

**Comment by tofumatt** [comment]
As I've been saying as well, I think the forward-facing text for this feature to users could be more along the lines of "Beta Add-on" rather than "Experimental". I know we use the terminology in two places but I think the text "experimental" is very confusing and strange.

**Comment by muffinresearch** [comment]
> As I've been saying as well, I think the forward-facing text for this feature to users could be more along the lines of "Beta Add-on" rather than "Experimental". I know we use the terminology in two places but I think the text "experimental" is very confusing and strange.

I think we risk more confusion if experimental and the Beta channel get confused. I'd suggest we stick with existing terminology if that's how it's currently exposed on the developer hub etc. Changing it requires more changes that how it's displayed here.

**Comment by willdurand** [comment]
@pwalm sorry to bother you, any chance to get an "experimental" icon? 😗

**Comment by pwalm** [comment]
Yes! Here it is, sorry for the delay:
![screen shot 2017-10-02 at 3 16 48 pm](https://user-images.githubusercontent.com/6797635/31101952-d064e25a-a784-11e7-9913-53dd04df4a99.png)

SVG:
[beaker.svg.zip](https://github.com/mozilla/addons-frontend/files/1350588/beaker.svg.zip)

**Comment by willdurand** [comment]
Thank you so much!

**Comment by ValentinaPC** [comment]
Verified this as fixed on AMO-dev FF56(Win 7, Android 7.2.1).
The experimental badge was added.
Postfix screenshots:
![desktop](https://user-images.githubusercontent.com/15685960/31115426-f39d8f5a-a82a-11e7-8a54-3cee27aafedb.png)
![2017-10-03_1107](https://user-images.githubusercontent.com/15685960/31115466-1db8b120-a82b-11e7-81e6-30d3cc96f9ca.png)

@muffinresearch : should there be an "compatible with ff 57+" badge also? Thanks!

**Comment by muffinresearch** [comment]
@ValentinaPC only if it's a webextension.

**Comment by ValentinaPC** [comment]
This is a webext - https://addons-dev.allizom.org/en-US/firefox/addon/webext-simple/ -  and has no compatibility badge.

**Comment by muffinresearch** [comment]
@ValentinaPC Hmm I thought the webext badge had already been added but it would appear other decisions were made. For the purposes of this bug it's fine - I'm going to look into potentially re-opening https://github.com/mozilla/addons-frontend/issues/2754 to deal with that separately.

**Comment by ValentinaPC** [comment]
I forgot about that one, where they decide to leave out the badge and add only a compatibility banner.
