### ISSUE TITLE
Add contextual link for a developer to manage their add-on

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2756]
If the user has access we should display links to:

* manage add-on (developer/author)
* ~~review add-on (reviewers)~~
* ~~admin add-on (admins)~~

---

**Update March 2020:** the idea would be to add a shortcut link to a product page when the user is the author of the add-on, cf. @jvillalobos's comment:

> This issue is for adding a shortcut link or button to manage an add-on when a developer is looking at its product page. Some developers have hundreds of add-ons, so navigating through devhub isn't ideal.

**Comment by muffinresearch** [comment]
Marking mvp as this will be a pain for reviewers/admins without this.

**Comment by kumar303** [comment]
> Marking mvp as this will be a pain for reviewers/admins without this.

Yes but we could circulate a list of links that they could copy/paste/edit to get the job done. We should definitely follow up and add this but I'm not nominating it for MVP removal so we can ship more important things.

**Comment by muffinresearch** [comment]
@jvillalobos was ok for us to leave this as a post-release follow-up though we should try and fit it in if we have the time.

**Comment by caitmuenster** [comment]
Hey @jvillalobos, is there any way this could be covered in Q2? This would make my job a lot easier. :)

**Comment by willdurand** [comment]
We do have a link to "manage my submissions" in the top menu.

**Comment by jvillalobos** [comment]
This issue is for adding a shortcut link or button to manage an add-on when a developer is looking at its product page. Some developers have hundreds of add-ons, so navigating through devhub isn't ideal.

**Comment by avgupt** [comment]
@willdurand @caitmuenster Can I take up this issue?

**Comment by willdurand** [comment]
> @willdurand @caitmuenster Can I take up this issue?

I think so, yes.

We have a `Admin Links` section in the `AddonMoreInfo` card/component. I think we could add a similar section for "Author Links". @jvillalobos WDYT?

**Comment by jvillalobos** [comment]
Yes, that sounds good. I think we only need one `Edit Add-on` link, which is the same we have in the Admin section.

**Comment by muskangupta-iitr** [comment]
> Yes, that sounds good. I think we only need one `Edit Add-on` link, which is the same we have in the Admin section.

As you said we only need one link that is already present so I think this issue is already completed. Am I correct or any further changes required ?

**Comment by willdurand** [comment]
> @jvillalobos @willdurand As you said we only need one link that is already present so I think this issue is already completed. Am I correct or any further changes required ?

Yes and no. The link is only shown to admins, not authors of the add-ons. Admins are special users that have access to all kind of features on AMO (admins are Mozilla employees). Authors are developers or theme artists for instance. Those are end users and they don't see the admin links.

So the issue is still valid and we still need to show this link to them.

I suggest we add a "Author Links" (similar to the "Admin Links") and we only show one link, which is the same as the "Edit add-on" link from the admin links. If an admin is also an author, the link will be shown twice but I don't think it is a problem (and that will make things much simpler).

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

The 'Edit add-on' link is exposed in the More info card to users that are listed as authors for that add-on. The link is present for all add-on types. 

![image](https://user-images.githubusercontent.com/31961530/78142903-2ff71780-7436-11ea-8e65-f3d78f729b35.png)
