### ISSUE TITLE
Add release notes on add-on details

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2760]
If release notes are available we should show them. May need a new section, probably at the top.

**Comment by kumar303** [comment]
We have release notes: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail-object

**Comment by kumar303** [comment]
From `AMO Desktop - Master.sketch` :

<img width="486" alt="screenshot 2017-08-17 16 28 04" src="https://user-images.githubusercontent.com/55398/29434585-30823a92-8369-11e7-9728-be4296cf7be7.png">

**Comment by kumar303** [comment]
Hmm, we may want to wait on https://github.com/mozilla/addons-server/issues/6268 otherwise I'd have to create a version saga (which do we need anyway, eventually).

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
Version notes are listed for each version.
Postfix screenshot:
![rel_notes](https://user-images.githubusercontent.com/15685960/30015280-affb7b6a-9158-11e7-8e48-698253a1fb73.png)

@kumar303 : Is there anywhere else where this notes should be displayed?

**Comment by ValentinaPC** [comment]
Found it! :P
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1).
Release notes are listed in new desktop pages for current add-on version.
Postfix screenshots:
![release_notes-last_vers](https://user-images.githubusercontent.com/15685960/30107954-12282192-9309-11e7-9059-90892b33d555.png)
![device](https://user-images.githubusercontent.com/15685960/30107958-152e26f2-9309-11e7-9a77-b887d2a49ba3.png)

**Comment by kumar303** [comment]
oh yeah, sorry, I should have included a URL
