### ISSUE TITLE
Add link to full version history

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2761]
Link to the full version history page from an add-on's detail page.

**Comment by muffinresearch** [comment]
@tofumatt this could use a bit more information as to what the feature will end up doing both for QA purposes + clarity.

**Comment by tofumatt** [comment]
This actually means a version history page, I think. So this will be a list of all previous versions of an add-on.

Not sure how useful it is especially when older versions might not work on 57+ but I get it's important for reference 😄

**Comment by muffinresearch** [comment]
Duplicate.
