### ISSUE TITLE
Link to source code URL

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2762]
We're dropping the Source Code Viewer but we should allow (or maybe already allow) users to submit a URL with the source code of their add-on. And we should display that.

Do we already support setting a URL for this explicit purpose @jvillalobos or @diox? If not this might need an API.

**Comment by jvillalobos** [comment]
We don't support this in the developer tools at the moment. There's a homepage URL that is sometimes used to point to GitHub, but we should probably have a separate one for source code.

**Comment by muffinresearch** [comment]
According to the doc this is dropped - see way down in https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.4qn2rle47cci "Link to View Source (when public)"
