### ISSUE TITLE
Show current beta version in addons details page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2763]
Show a card on the addon detail page with the current beta version's info and a download button. This will be similar to the "development version" section on the old site (at the bottom of the add-on detail page).

**Comment by muffinresearch** [comment]
@tofumatt this could use a bit more information as to what the feature will end up doing both for QA purposes + clarity.

**Comment by tofumatt** [comment]
This should actually be a card on the addon detail page with the current beta version's info and a download button.

**Comment by kumar303** [comment]
I'm going to pick this up with parts of https://github.com/mozilla/addons-frontend/compare/development-channel-2763

**Comment by tofumatt** [comment]
Thinking this can be removed from MVP as most add-ons will be 57 compatible when we ship... and this feature didn't even appear in the mocks. The All Versions page will hopefullty show this anyway.

**Comment by kumar303** [comment]
Here is an MVP issue to link to the old pages which would allow someone to install a beta version: https://github.com/mozilla/addons-frontend/issues/3229

**Comment by muffinresearch** [comment]
@jvillalobos what do you think? Are we ok to pull this from the MVP on the basis that users will still be able to get to the data from the old site pages?  The only other though I had was if there are high profile add-ons that might be relying on the beta feature heavily.

**Comment by jvillalobos** [comment]
Some high-profile add-ons have been using the Beta channel to test their WE versions while they continue distributing the legacy versions in the main channel. _Ideally_ they would migrate fully to WE before the 57 release, but that won't be the case for everyone.

I don't think we need to show the install button or the latest version in the listing page in the MVP. But there should at least be a way to get to the All Beta Versions page to install them, which is what I think you're saying.

**Comment by tofumatt** [comment]
Yeah, that's what we're proposing. We'll link to the old site for those versions–perhaps once all high-profile extensions migrate to WE we can just hide the feature.

**Comment by kumar303** [comment]
> there should at least be a way to get to the All Beta Versions page

Yep, that's about to land in https://github.com/mozilla/addons-frontend/pull/3230

> I don't think we need to show the install button or the latest version in the listing page in the MVP. 

ok, I'll remove it for now. It's actually a non-trivial amount of work because of how the code is set up to pass data to the hierarchy of components that handle installation.

**Comment by muffinresearch** [comment]
Beta versions are being phased out so I'm going to close this.
