### ISSUE TITLE
Add Developer's Comments to add-on detail/description

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2764]
Relies on https://github.com/mozilla/addons-server/issues/5773, being discussed.

**Comment by muffinresearch** [comment]
This is sort of an announcement from the developer / note to users.

**Comment by eviljeff** [comment]
no longer blocked :)

**Comment by muffinresearch** [comment]
We'll need some UX input on how these comments should be displayed. @eviljeff do you have an example of where these are currently being used?

**Comment by eviljeff** [comment]
https://addons.mozilla.org/en-US/firefox/addon/noscript/#developer-comments uses it.

**Comment by pwalm** [comment]
No mocks for this, but I'd treat it the same as the "About this extension" block.

**Comment by willdurand** [comment]
@jvillalobos do we still want to implement this?

**Comment by jvillalobos** [comment]
Yes

**Comment by willdurand** [comment]
@jvillalobos so I believe we still want to do this, right?

Do you think we should have a new `Card` like this on the left side?

![Screen Shot 2020-03-19 at 11 06 51](https://user-images.githubusercontent.com/217628/77055795-cf95be00-69d1-11ea-8f33-14729b7d883f.png)

Or should we add a (larger) card on the right panel?

![Screen Shot 2020-03-19 at 11 08 36](https://user-images.githubusercontent.com/217628/77055938-ff44c600-69d1-11ea-8915-caedfab7410e.png)

**Comment by jvillalobos** [comment]
Per pwalm's comment from before, it should be on the right panel.

**Comment by xlisachan** [comment]
@willdurand I'm an Outreachy applicant, can I work on this issue?

**Comment by willdurand** [comment]
> @willdurand I'm an Outreachy applicant, can I work on this issue?

Yes. If you're familiar with JS/React, then you should be able to work on this. Start by looking at the README file to install the project locally (use `yarn amo:dev`). Then, see how you could introduce a new "Card" named "Developer's comments" as shown below:

![](https://user-images.githubusercontent.com/217628/77055938-ff44c600-69d1-11ea-8915-caedfab7410e.png)

The API exposes the comment in the response of this API endpoint: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v4-addons-addon-(int-id|string-slug|string-guid)- (look for `developer_comments`). We need to display the card if the value is not `null`.

**Comment by ioanarusiczki** [comment]
@willdurand The Developer comments section is available on the detail pages: 
As you can see below, the text from this section will fill more of the area reserved compared to "About this extension" section. 

Can't tell if it's fine that way. Maybe they should look alike ?

![developer comment layout](https://user-images.githubusercontent.com/33448286/77442401-0ebd7800-6df3-11ea-9fa8-811f43cc7fcd.png)

**Comment by willdurand** [comment]
> Can't tell if it's fine that way. Maybe they should look alike ?

Ah, good catch. Could you please file a new issue for that?
