### ISSUE TITLE
Implement review/rating flow for rating

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2766]
The new AMO desktop scoping docs mentions a review/rating flow we need to implement. Guessing it's in UX but I forget, so filing here.

**Comment by muffinresearch** [comment]
@tofumatt this needs more info + details. Are there specific questions that need answering?

**Comment by tofumatt** [comment]
Shoot, this issue sucks, eh? I think this was about the new review flow but I can't find it in sketch. Maybe @pwalm can supply the new review flow (for desktop). It was in the PRD, sorry I didn't fill this in more... 😢

**Comment by muffinresearch** [comment]
In lieu of additional information I'm closing this since there's nothing actionable here at the moment. Feel free to re-open/re-file a new issue to cover new flow changes.

**Comment by pwalm** [comment]
Is this regarding the "new" rating/review flow I proposed earlier in the year?
