### ISSUE TITLE
Add link to " More add-ons by these developers"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2767]
Relies on the API here https://github.com/mozilla/addons-server/issues/5786, already complete.

Note the feature is labeled differently when there’s a [single dev](Note the feature is labeled differently when there’s a single dev or multiple devs.) or [multiple devs](https://addons.mozilla.org/en-GB/firefox/addon/wikipedia-panel/).

**Comment by willdurand** [comment]
It seems it is not a link but a section/panel.

**Comment by willdurand** [comment]
I have asked for an API update for this feature: https://github.com/mozilla/addons-server/issues/6285.

**Comment by willdurand** [comment]
I am a bit confused by the Sketch file, I reused our `SearchResult` component to display the other addons but it does not look like the mock-ups. Yet, other parts of the app don't look like the mock-ups (cc @tofumatt @kumar303)

<img width="510" alt="screen shot 2017-09-06 at 17 25 41" src="https://user-images.githubusercontent.com/217628/30120225-87b8adcc-9328-11e7-9091-f18ebd142006.png">

**Comment by tofumatt** [comment]
Hmm, that style will appear in an `AddonsCard` if you use `type="horizontal"`. That is admittedly not a great API, sorry about that 😢

https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/LandingAddonsCard/index.js#L35

**Comment by willdurand** [comment]
Ah thanks, this is a nice one.. I was about to re-create the same thing.. So now I have it, but I still get this style. In the mock-ups, the icon should be on top of the text, not on the left.

<img width="490" alt="screen shot 2017-09-07 at 14 32 48" src="https://user-images.githubusercontent.com/217628/30163477-703e9754-93d9-11e7-941f-8d44cff4f92e.png">
