### ISSUE TITLE
Add an add-on to an existing collection

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2768]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

The user should be able to:
- Sign in
- Go to the detail listing of an add-on
- Add the add-on to an existing collection

UX mock: https://github.com/mozilla/addons-frontend/issues/3993#issuecomment-349064460

**Comment by jvillalobos** [comment]
The [plan for collections](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit) eliminates the special-casing of the favorites collection. The Add to Collection feature should let you pick from your existing collections, similarly to how it currently works on AMO theme listings.

**Comment by kumar303** [comment]
I'm nominating this for MVP removal because it would only cripple a small percentage of users if we release without it. If should be enough to ship with read-only views (https://github.com/mozilla/addons-frontend/issues/3140 https://github.com/mozilla/addons-frontend/issues/3141). We can do a follow-up release with this edit feature.

**Comment by jvillalobos** [comment]
Removing from MVP since the old front-end hasn't had this for a while. We want it back, but it's not that urgent.

**Comment by jvillalobos** [comment]
There are many requests for this feature, so moving to P2. I was wrong about the old front-end, because we did support it for themes before moving to the new one.

Not sure if we have UX for this one.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF57 (Win10 and Android 7.0)

Observations:
- Create a collection function works as expected
- Adding an add-on to an existing collection is possible and the add-on is listed among the other items inside the collection 
- notification messages (success/errors) are triggered correctly

Notes:
There are some issues that concern mostly the layout of some specific elements for which I will create separate cases

![image](https://user-images.githubusercontent.com/31961530/35103678-3d192fac-fc6f-11e7-9be6-195ffc8c9f89.png)

![image](https://user-images.githubusercontent.com/31961530/35103697-507c3efe-fc6f-11e7-833e-2997bc274cd2.png)
