### ISSUE TITLE
Implement the "All versions" / "All development channel versions"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2770]
See: https://docs.google.com/document/d/1cJ1k8HsAb6taauvJMDLOiYMa1McfUXNgEtax3hoToPc/edit#heading=h.k7gt9cmz94zx

The only difference between All Versions and All Development Channel Versions is that the first one excludes beta versions, and the second one only includes beta versions.

- [ ] Link back to listing page
- [ ] Warning about installing old versions
- [ ] Version count
- [ ] List of versions with: version number, version notes, compatibility info, release date, license info
- [ ] Download link or button for each version
- [ ] Permalink for each version on list

**Comment by kumar303** [comment]
I'm nominating this for MVP removal since needing to install historic versions is not very common and we want to discourage it anyway. We could link to the old page for the MVP release and follow-up with this new page later.

**Comment by jvillalobos** [comment]
Installing old versions may actually be very common during the 57 transition, and we actually link to the All Versions page more often because of it. However, showing the old page should do for an MVP.

**Comment by kumar303** [comment]
Here is the MVP issue to link to the old pages: https://github.com/mozilla/addons-frontend/issues/3229

**Comment by muffinresearch** [comment]
Refs: #3761

**Comment by kumar303** [comment]
We should make sure we support the STR in https://github.com/mozilla/addons-frontend/issues/4340

In summary:
- Enter version notes in locale A
- View the site in locale B
- Expect to see the version notes for locale A

**Comment by bobsilverberg** [comment]
It looks like we don't need any new API work for this, and can use http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#versions-list.

I see there's a needs:ux label on this, and I don't see any mockups in Sketch, so I guess we need those. @pwalm would you be able to do that? I think all we need is a screen to duplicate the functionality of https://addons.allizom.org/en-US/firefox/addon/noscript/versions/ (as an example).

**Comment by pwalm** [comment]
All Versions mock (similar to what we have on the old site, but photon-ized):
![all versions - 1366px](https://user-images.githubusercontent.com/6797635/43019605-69df4606-8c12-11e8-8a39-840e840da1fe.png)

**Comment by bobsilverberg** [comment]
Just checking about the "All development channel versions" part of this. The original description says:

> The only difference between All Versions and All Development Channel Versions is that the first one excludes beta versions, and the second one only includes beta versions.

Am I correct in recalling that we do not support beta versions anymore? If that's the case, does that mean the "All development channel versions" part of this is now irrelevant, and we only need a single "All versions" page?

**Comment by jvillalobos** [comment]
> Am I correct in recalling that we do not support beta versions anymore? If that's the case, does that mean the "All development channel versions" part of this is now irrelevant, and we only need a single "All versions" page?

Yes, that's no longer relevant, per https://github.com/mozilla/addons-server/issues/7163

**Comment by bobsilverberg** [comment]
If I'm going to implement the page as mocked above, it will make sense to extract everything that creates the Add-on Card on the left into its own component, as it is identical to what is shown on the Reviews Listing page. Before I go ahead and do that, I want to make sure this is exactly what we want.

@pwalm and @jvillalobos can you confirm that we want an add-on card which shows the rating stars and the rating breakdown, as illustrated above, on this "All Versions" page? I.e., the page will be identical to the review listing page other than the fact that this page will list versions whereas the review listing page will list reviews.

**Comment by jvillalobos** [comment]
It looks okay to me. Further down the line (Q2, I suppose) I think we'll be using a different card to represent add-ons throughout AMO, which would replace the card in the mock. But that's something to worry about later, I think.

**Comment by ioanarusiczki** [comment]
@bobsilverberg The new page is not displayed yet on AMO dev. Could you be more specific about what to test for this issue? 
Thanks!

**Comment by ioanarusiczki** [comment]
@bobsilverberg I filed https://github.com/mozilla/addons-frontend/issues/7332 and https://github.com/mozilla/addons-frontend/issues/7333. I'll continue testing this issue tomorrow.

**Comment by ioanarusiczki** [comment]
The following issues were filed:
https://github.com/mozilla/addons-frontend/issues/7343
https://github.com/mozilla/addons-frontend/issues/7348
https://github.com/mozilla/addons-frontend/issues/7346
https://github.com/mozilla/addons-frontend/issues/7349
https://github.com/mozilla/addons-frontend/issues/7351

I don't see it as a problem, but I can't tell if it's intended: when the rating count (on the left side of the screen) is clicked from All version page it will redirect to the reviews. This behavior is also present on Custom Licence page, perhaps just the [mocks](https://github.com/mozilla/addons-frontend/issues/2770#issuecomment-406693377) do not display the numbers as being underlined and therefore clickable too.

Verified on AMO dev with FF64(Win10 & Android 8.0).
