### ISSUE TITLE
Add a permalink to a specific review / single review page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2771]
Use the time of review in the `ReviewList` as a permalink to the specific review, which we'll need a simple page for.

**Comment by grahamperrin** [comment]
Hi! Looking good with the go-live. Absence of permalinks was one of just three significant issue that I noticed within the first few minutes. 

Highlighted, pink (with Firefox using a SeaMonkey user-agent string, for the traditional view of things): 

![2017-11-02 17 48 35 conex reviews add-ons for firefox](https://user-images.githubusercontent.com/192271/32342612-cb159826-bff8-11e7-8543-e64e4b654f04.png)

**Comment by grahamperrin** [comment]
> … specific review, which we'll need a simple page for.

Should I/we raise a separate issue for that? For tracking purposes; to be labelled [component: legacy pages](https://github.com/mozilla/addons-frontend/labels/component%3A%20legacy%20pages).

**Comment by eviljeff** [comment]
The legacy site uses the Rating|Review id in the permalink, so that will need to work as well / instead of a timestamp.

**Comment by bobsilverberg** [comment]
I feel like we discussed this when discussing what to include in the Q3 project, but I don't recall if we came up with any solutions. Is our goal to have a page for a single review, like on the legacy site, or is it to bring the user to the list of reviews for the add-on in question, with the linked review at the top (or anchored in some way)? If the latter there's an issue that a specific review could end up on any page of the reviews listing for an add-on, so it might be tricky to tell which page to show.

For reference, here's the page that shows a single review from the legacy site:

![screenshot 2018-08-29 11 23 58](https://user-images.githubusercontent.com/142755/44797788-0ac96580-ab7e-11e8-8047-b736a4a21f5d.png)

Pinging @pwalm for input.

**Comment by kumar303** [comment]
> bring the user to the list of reviews for the add-on in question, with the linked review at the top

I think this would be the most useful view. When you click on a permalink for a review, you want to see the review but it would also be helpful to see a card underneath that of all other reviews. Rather than dealing with anchors, I say just put the permalinked review at the top in its own card.

**Comment by pwalm** [comment]
Proposed change: The permalink to the review is a page with the review broken out up top into its own block, with all others below for context.
<img width="1482" alt="screen shot 2018-08-31 at 2 41 45 pm" src="https://user-images.githubusercontent.com/6797635/44937009-08a50980-ad2c-11e8-9821-bb27a249b107.png">

**Comment by bobsilverberg** [comment]
Thanks @pwalm! One question, and maybe this is for @MeridelW, the header currently says "My Review", but this could be a review written by someone else. A user doesn't even need to be logged in in order to see this page.

What do we think would be a good header for the upper review card if this is not a review written by the current user?

**Comment by MeridelW** [comment]
Hi @bobsilverberg, I'm a bit confused. What is the criteria for displaying the current "My Review" field in the reviews view? If the user did not write the review, why is that review being featured there?

**Comment by kumar303** [comment]
@MeridelW this issue is about making a page for a single review. Example stories:

As an add-on user, you write a review and would like to share a link to it on Twitter so that other people can read it. 

As an add-on developer, you receive an email about a review someone has just posted. You would like to reply to the review so you click on a link (in your email) that takes you directly to the review.

**Comment by MeridelW** [comment]
Got it, thank you. I think we should include the reviewer's name. Would it be possible to replace the "My Review" header with this header? **Review by [user name]**

Example: Review by hanshin-cat

**Comment by bobsilverberg** [comment]
@MeridelW yes, that should be possible. I like it, too. Thanks!

**Comment by AlexandraMoga** [comment]
Verified on dev and stage with FF62, WIn10x64

Here is how the feature looks like:
[1] when writing a review
![image](https://user-images.githubusercontent.com/31961530/45809709-8b890680-bcd1-11e8-83c0-998a07c6bd85.png)

[2] on the user profile
![image](https://user-images.githubusercontent.com/31961530/45809719-92b01480-bcd1-11e8-87b9-0f3656cba726.png)


[3] on the add-on reviews page
![image](https://user-images.githubusercontent.com/31961530/45809732-9c397c80-bcd1-11e8-9058-20a3ba8d3f88.png)

Given the amount of issues found around this feature (see bugs linked above), we should consider keeping it out of production this week

**Comment by AlexandraMoga** [comment]
Considering that the final decision was to push this in production and some of the more significant issues have been clarified I'm going to mark this as verified fixed.
