### ISSUE TITLE
Show developer reply to a review

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2773]
Show developer reply:

* Content of the reply
* user (not linked)
* “Developer” indicator
* time of reply

For QA:
- Sign in as a developer of an add-on
- Go to the detail page for one of your add-ons that has some reviews
- Click 'Reply to this review'
- Enter some text and submit
- You should now see your reply

**Comment by kumar303** [comment]
I'm nominating MVP removal for the same reason as https://github.com/mozilla/addons-frontend/issues/2775#issuecomment-330894373

**Comment by muffinresearch** [comment]
This goes hand in hand with #2775 so if we're keeping that it makes sens to keep this one in the MVP.

**Comment by kumar303** [comment]
The UI for this is in Sketch now. See also https://github.com/mozilla/addons-frontend/issues/2775#issuecomment-332973335

**Comment by vcarciu** [comment]
Trying to submit a blank review(some blank spaces inserted) should not be allowed and actually this action is failing the reply submission : 
![blanlrev](https://user-images.githubusercontent.com/1583842/31345483-8e0bc92e-ad1e-11e7-8e27-f355aba051f6.gif)

**Comment by kumar303** [comment]
Thanks, good catch. I re-filed that as https://github.com/mozilla/addons-frontend/issues/3415

Does it pose a problem for QA to file bugs like this as new issues? It's easier for us because it adds more visibility to what the developers are working on and shipping (and in what releases).

**Comment by vcarciu** [comment]
@kumar303 : 
We can easily log a new issue, but sometimes the original issue cannot be marked as verified because of the new one. Anyway in this case I think that we can mark it as verified since the main purpose was achieved.
