### ISSUE TITLE
Add UI to flag a review for spam, abuse, etc

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2774]
This is a UI that lets a user flag an add-on review for the following reasons:
* It's spam
* It contains inappropriate language
* It is a bug report or support request (not a review)

Related to #2772.

You will be able to flag a review for a different reason than what's listed here in ﻿﻿https://github.com/mozilla/addons-frontend/issues/3573

**Comment by muffinresearch** [comment]
This is probably going to follow the UX for reviews.

**Comment by kumar303** [comment]
The UX for this form can follow https://github.com/mozilla/addons-frontend/issues/2775#issuecomment-332973335 (which is also in Sketch now)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
The "Flag" blue link and options were added.
Postfix screenshots:
![flag](https://user-images.githubusercontent.com/15685960/31879708-e510acda-b7e6-11e7-81cf-ccb715714c91.png)
![rtl](https://user-images.githubusercontent.com/15685960/31879838-555c3af4-b7e7-11e7-9a2b-014c37d76d8e.png)

logged a separate issue for anything that seems to not work as expected around flag option (https://github.com/mozilla/addons-frontend/issues/3598).
We can mark this verified fixed.
