### ISSUE TITLE
Add a promo carousel to the homepage

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2776]
We need a promo carousel comonent for the home page and an API to power it.

This needs an API and I don't know if the relevant bug has been filed on addons-server yet, so marking this as needs: more triage.

**Comment by muffinresearch** [comment]
This will be hard-coded content initially. See also https://github.com/mozilla/addons-frontend/issues/3000

**Comment by muffinresearch** [comment]
In fact I think it will make more sense to close this in favour of #3000
