### ISSUE TITLE
Add a Language Tools "Landing" page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2777]
The frontend needs a version of https://addons.mozilla.org/en-GB/firefox/language-tools/

- [x] Title and description of language tools
- [x] "Available in your locale"
- [x] All locales
- [x] Links to dictionaries, when available
- [x] Links to language packs, when available

**Comment by eviljeff** [comment]
https://github.com/mozilla/addons-server/issues/5803 for server side

**Comment by kumar303** [comment]
@pwalm do we have UX mocks for this?

**Comment by pwalm** [comment]
We do not, but you're gonna get one! It's going to follow the design for the top-level category pages, like almost exactly. So that's a start.

**Comment by pwalm** [comment]
So "Language Tools" should look just like category pages.
<img width="1272" alt="screen shot 2017-10-06 at 12 12 00 pm" src="https://user-images.githubusercontent.com/6797635/31294411-a4eae0a8-aa8f-11e7-8929-7b1d30a85c8d.png">

Should we just put all the other features of the page in the filter section on the left?
<img width="298" alt="screen shot 2017-10-06 at 12 13 46 pm" src="https://user-images.githubusercontent.com/6797635/31294486-e44752e0-aa8f-11e7-9de3-14c5aa22372b.png">

**Comment by eviljeff** [comment]
> So "Language Tools" should look just like category pages.

But it's got very different content so not sure how that can work?  It's not just a list of addons, it's arranged per locale.  Like @tofumatt has done in #3289

**Comment by pwalm** [comment]
Ah crap, forgot about that part. Ignore above.

**Comment by pwalm** [comment]
Ah crap, forgot about that part. Ignore above.

**Comment by tofumatt** [comment]
Just FYI this won't be visible on a direct page load until #3438 is closed, but you can navigate here from another page.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1).
Postfix screenshots:
![en](https://user-images.githubusercontent.com/15685960/31484961-ea98537e-af3a-11e7-8061-1436b9184898.png)
![fr](https://user-images.githubusercontent.com/15685960/31484962-eb2069b2-af3a-11e7-92f6-50bde45c7ac5.png)

Other small issues regarding this page were tracked separately.
