### ISSUE TITLE
Implement new category icons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2778]
~~We need editorial copy for all categories so we can display things that look like:~~

This is now just to update to the new Icons. The icons are available in https://github.com/mozilla/addons-frontend/issues/2621

<img width="467" alt="screenshot 2017-07-12 02 03 16" src="https://user-images.githubusercontent.com/90871/28097199-46d4a9b8-66a6-11e7-9953-9ab79959ddb2.png">

----

Categories we need to replace the icons for:

#### Extensions

* [x] Language Support
* [x] Feeds, News & Blogging
* [x] Download Management
* [x] Alerts & Updates
* [x] Bookmarks
* [x] Appearance
* [x] Games & Entertainment
* [x] Other
* [x] Photos, Music & Videos
* [x] Privacy & Security
* [x] Search Tools
* [x] Shopping
* [x] Social & Communication
* [x] Tabs
* [x] Web Development

#### Themes

* [x] Abstract
* [x] Causes
* [x] Fashion
* [x] Film and TV
* [x] Firefox
* [x] Foxkeh
* [x] Holiday
* [x] Music
* [x] Nature
* [x] Other
* [x] Scenery
* [x] Seasonal
* [x] Solid
* [x] Sports
* [x] Web Sites

**Comment by devaneymoz** [comment]
@pwalm @muffinresearch 

How do you feel about foregoing descriptive copy for these categories? It doesn't seem necessary (really, if the category title isn't evocative enough that's an issue). 

My recommendation would be to bump up the sizing of the category title to compensate for the space reserved for copy. 

Thoughts? 

If it's determined that we do need descriptive copy, I can put it together fairly quickly. But before proceeding, I'd appreciate a re-evaluation.

**Comment by muffinresearch** [comment]
I like the addition of some context since some of there might not be obvious on their own. However, we can certainly start with headings and add the context later.

**Comment by muffinresearch** [comment]
Icons were provided here. So let's start with adding those. https://github.com/mozilla/addons-frontend/issues/2621

**Comment by kumar303** [comment]
I agree that for the MVP version of this feature let's just add category titles without descriptive text

**Comment by devaneymoz** [comment]
@pwalm any thoughts on eschewing a copy blurb for category pages?

**Comment by pwalm** [comment]
Not necessary! I'm fine with dropping it.

**Comment by AlexandraMoga** [comment]
The new icons are available for all the mentioned categories (both extensions and themes) in the Firefox platform.
Theme category icons are applied for the Android platform as well.

Several examples:

Extensions
![new icons_ext](https://user-images.githubusercontent.com/31961530/31081482-b99694aa-a794-11e7-9344-b48d94336733.png)
Themes
![new icons_themes](https://user-images.githubusercontent.com/31961530/31081490-c039270a-a794-11e7-84c3-e795d9d0ec5b.png)




Notes: Android Extension categories are slightly different than Firefox categories. Is there a plan to update the category icons for Android extensions as well? Currently, only the categories coinciding with those for Firefox have a matching icon.

Verified in AMO-dev with FF56, Win 10 and Android 7.0

**Comment by willdurand** [comment]
> Notes: Android Extension categories are slightly different than Firefox categories. Is there a plan to update the category icons for Android extensions as well, @muffinresearch ? Currently, only the categories coinciding with those for Firefox have a matching icon.

done!
