### ISSUE TITLE
Separate search results by add-on type

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2779]
Results in search should be broken down by add-on type, eg:

<img width="483" alt="screenshot 2017-07-12 02 06 46" src="https://user-images.githubusercontent.com/90871/28097254-c876b4de-66a6-11e7-97c9-e129b09790f3.png">

This shouldn't need an API modification... but will require dispatching two search requests–one for extensions and one for themes.

**Comment by willdurand** [comment]
Hi,

Should people expect to find "themes" under the "extension" page? It seems the extension page filters by extension, and same for the theme page. The attached screenshot highlights the extension page though.

I would expect to have two different search results on the "explore" page. Since it already gets everything mixed, should we really do two API requests or sort the result set into two sub-sets?

**Comment by tofumatt** [comment]
No, on the extensions page it should only search extensions. Like you said, the only place we should serve results for both is from "explore".

I think two API requests might be best because otherwise we'll get an uneven/unpredictable number of each kind of result.

**Comment by willdurand** [comment]
Below is the full screenshot. If I understand correctly, we should retrieve 6 add-ons of each type, and link to the paginated list for each add-on type.

What should be written/displayed if there is no "extension" add-on for instance?

![search results - 1366px](https://user-images.githubusercontent.com/217628/29464161-53ed1002-8435-11e7-96e6-bb4cffe44897.png)

**Comment by kumar303** [comment]
> The attached screenshot highlights the extension page though.

That was a mistake. It should highlight the Explore tab.

**Comment by kumar303** [comment]
> Question: what should be written/displayed if there is no "extension" add-on for instance?

I think we should still show the Extensions header but display something like 'No extensions found' in the card contents. It's probably easiest just to throw something together then get some feedback from @pwalm

**Comment by willdurand** [comment]
> . It's probably easiest just to throw something together then get some feedback from @pwalm

Ok good to know, I was also thinking about keeping the card along with a message.

**Comment by muffinresearch** [comment]
I still don't know this is really that useful. If another addon-type is the most relevant and at the bottom of the page due to splitting by type, we're not helping our users find what they need.

**Comment by muffinresearch** [comment]
@jvillalobos I'm thinking this should be closed out due to the impact on relevancy - any thoughts?

**Comment by jvillalobos** [comment]
This was part of a larger idea of how users could narrow down the query to categories and tags, but I don't see that happening now. We should aim to have the most relevant results on the first page, so how things are structured for deeper search is secondary. I think it's okay to close this.
