### ISSUE TITLE
Add "Featured Add-on" search filter

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2780]
We should have a checkbox to allow users to filter by featured add-on only in the search filters.
This is waiting on https://github.com/mozilla/addons-server/issues/6205.

<img width="245" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30427440-bf184ee2-9947-11e7-8f71-858c28c074d2.png">

**Comment by muffinresearch** [comment]
@tofumatt this issue could use a bit more detail / breaking up.

**Comment by tofumatt** [comment]
At this point I'll just convert this to being the featured checkbox. Not sure this is a must-land/MVP feature for Q3.

**Comment by jvillalobos** [comment]
Not an MVP blocker, IMO.

**Comment by muffinresearch** [comment]
@tofumatt, can you add some guidance for what's involved unless this should be removed form the maybe good first bug label?

**Comment by tofumatt** [comment]
Probably not a good first bug after all. It's conceptually not hard but it's a lot of moving parts. I'll remove it from the list.

**Comment by vcarciu** [comment]
Verified as fixed : 
![featured](https://user-images.githubusercontent.com/1583842/31668474-f7be4544-b35a-11e7-9e76-4a2297ab95a1.gif)

Verified also on Android mobile device and filter was successfully applied
