### ISSUE TITLE
"View Mobile Site" is not working from themes categories pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2786]
Steps to reproduce:
1. Load Themes homepage on you device https://addons.allizom.org/en-US/android/themes/
2. Go to any theme category page i.e. https://addons.allizom.org/en-US/android/themes/abstract/
3. Click "View classic desktop site" 
4. Click " View Mobile Site"

Expected results:
The mobile page is loaded again.

Actual results:
Nothing happens.

Notes/Issues:
- issue is not reproducing for extensions
- nothing displayed in the console
- issue is also reproducing while using new desktop pages

Verified on FF54(Android 7.1.2, Win 7). Reproducible around all AMO servers.
Video fro this issue:
![nothing](https://user-images.githubusercontent.com/15685960/28123720-5e86ce5e-672a-11e7-8e2f-e08926f61004.gif)

**Comment by tofumatt** [comment]
I think this is an issue with the server, actually. That code is running on the addons-server code.

**Comment by ValentinaPC** [comment]
If you want I can move it?

**Comment by tofumatt** [comment]
Yeah that would be good, so the team there knows what’s up with it :-)

**Comment by eviljeff** [comment]
I'm not 100% sure this is fixable on addon-server either - see https://github.com/mozilla/addons-server/issues/5895#issuecomment-315164089
