### ISSUE TITLE
Strange behavior when switching from Mobile view to classic desktop site on Android

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2788]
Prerequisites:
Samsung Galaxy S7, Android 7.0, Latest Nightly

Steps to reproduce:
1.Go to AMO Stage
2.Click View Classic Desktop Site link at the bottom of the page
3.From classic view, click View Mobile Site

Expected results:
In both cases , after step 2 and 3 , the screen should resize to the view selected

Actual results:
Screen is not correctly resized

NOTES:
Not reproducible for another colleagues, but I am able to reproduce it constantly . Nothing interesting in the logs

Please see video for this bug : 
![mobiledesktop](https://user-images.githubusercontent.com/1583842/28129434-f715f01c-673b-11e7-9504-a9ec915cbb5a.gif)

**Comment by muffinresearch** [comment]
@vcarciu is this still reproducible? That behavior is certainly strange, and I've not been able to reproduce it.

**Comment by vcarciu** [comment]
Yes, this is still reproducible for me, but not for the other colleagues. I am not sure what triggered this behavior on my device. I deleted all installed add-on and I can reproduce it, but it is not reproducible for my colleagues.
Also , I borrowed a Samsung Galaxy S7 Edge and I am able to reproduce here too with a fresh install of Latest Nightly(2017-070-13)

**Comment by muffinresearch** [comment]
I think we'll need concrete steps for how to reproduce this. Until then I'm not sure what we can do.

**Comment by AlexandraMoga** [comment]
Coming back with STR:

Steps to Reproduce:
 
1. Access AMO homepage (ex https://addons-dev.allizom.org/en-GB/firefox/) from an Android mobile device
2. Select “Classic desktop view” from the page footer
3. Zoom out until the entire desktop page layout fits on your screen
4. Select “View Mobile site” from the page footer

Expected results:
The AMO Homepage Mobile view should load to its original size

Actual result:
The zoom out applied in the Desktop view resulted in a resize in the Mobile view as well

Notes: tested on FF55 with  three Android devices: Samsung Galaxy S7 and Samsung Galaxy S7 Edge -  both with Android 7.0, Asus Zenfone Max - Android 6.0.1
The issue reproduces on all AMO servers

Video reproduction: 
![desktop to mobile view](https://user-images.githubusercontent.com/31961530/30809940-17a8efe0-a20c-11e7-901e-5c13cdfea66f.gif)

**Comment by decembre** [comment]
Solved:
Now, there is no possibility to switch for the  “Classic desktop view” 👎
