### ISSUE TITLE
Add a link to Mozilla's Privacy Policy to the footer of the Discovery Pane

### ISSUE THREAD

**Issue by potch** [mozilla/addons-frontend#2789]
Looks like we're missing a link to the privacy policy from the Discovery Pane views, which show up in the Add-on Manager. Since that view has Google Analytics in it and isn't clearly linked to AMO, we should probably put a pointer to AMO's Privacy Policy in the footer.

**Comment by justjanne** [comment]
For compliance with [Directive 2002/58/EC](http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32002L0058&from=EN) it would be advised to also add a modal, header, or other form of cookie notice, as the normal mozilla websites had before the redesign, too.

**Comment by tofumatt** [comment]
Thanks @justjanne. That would be a separate issue, but I've checked with our team about it and if we need to post that notice I will file a new issue about it.

**Comment by justjanne** [comment]
@tofumatt Do you happen to know who is responsible for the tor browser? Because this also affects them: http://i.imgur.com/vdlFWYR.png

**Comment by tofumatt** [comment]
Looks like you want https://trac.torproject.org/projects/tor

**Comment by ValentinaPC** [comment]
Verified as fixed on about:addons while Disco Pane is set to point stage/dev.
Postfix screenshot:
![pp](https://user-images.githubusercontent.com/15685960/28154586-5eb32448-67b3-11e7-854b-1a638bdb3330.png)
