### ISSUE TITLE
Do not serve GA assets when DNT is enabled

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2792]
It is Mozilla's website policy to not serve Google Analytics when DNT is enabled in a browser. We should check for a DNT header and not serve Google Analytics if one is present (or at least not run them, I'm not sure how we include/bundle them right now).

This issue will disable tracking for both AMO and Disco Pane (and any other site that uses our `Tracking` class).

**Comment by alsternerd** [comment]
But what if DNT isn't available anymore, will there be some option of Opt-In (or at least, but worst Opt-Out) for tracking in the future then?

My idea is to ask the user not at the first start, but in the installation stage if he wants tracking or not. Also a commandline-command for msi installers would then be great.

**Comment by tofumatt** [comment]
Do not track is available as a browser setting and automatically enabled when tracking protection is on as well. If it's removed there will be plenty of notice and we'll cross that bridge when we come to it.

We cannot do this at installation stage (e.g. Mac for instance doesn't even have an install stage). Additionally landing that kind of feature would be a lot more time and effort and we want to ship this kit to users quickly (it can ship today using this fix). It would also need to "ride the Firefox release train" from Nightly to release, meaning users on release channel wouldn't see this feature for months.

We will be disabling GA using DNT.

**Comment by usrnamatnull** [comment]
Why I use Firefox
- because in firefox I can use multitabs and IE.6 don't have this options 
- because Firefox kill firebug 
- because web developer tools are slow shi.
- because Mozilla was protecting my privacy ?
- because mozilla kill own extensions like "Menu Editor"
- because mozilla remove themes and add background themes
- because Firefox is not Firefox is some clone of bad thinks form chrome ?

Question is when Mozilla pissed me of so much that i change browser still counting

**Comment by vcarciu** [comment]
Verified as fixed on AMO , discovery pane, new frontend , using nightly , release and some secondary browsers and everything looks fine to me. I will mark the issue as verified based on my results from : https://public.etherpad-mozilla.org/p/ZQNxSyyVwM

**Comment by vcarciu** [comment]
Verified as fixed on AMO , discovery pane, new frontend , using nightly , release and some secondary browsers and everything looks fine to me. I will mark the issue as verified based on my results from : https://public.etherpad-mozilla.org/p/ZQNxSyyVwM
