### ISSUE TITLE
Google Analytics is disabled for everyone

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2798]
### Describe the problem and steps to reproduce it:

Load the site after https://github.com/mozilla/addons-frontend/issues/2792

### What happened?

Google Analytics is never loaded

### What did you expect to happen?

We should load GA for anyone who doesn't have DNT enabled.

### Anything else we should know?

This logic is backwards: https://github.com/mozilla/addons-frontend/commit/1312536f6e1b075c508bccb2de7f050876eba172#diff-d174de3c0985bc0d979157795f96ae2bR134 It should be `!isDoNotTrackEnabled()` otherwise it will never be enabled for either case.

However, I recommend removing isDoNotTrackEnabled() from that line altogether since it's redundant (and makes the code more complicated). DNT is already checked in the constructor.

**Comment by vcarciu** [comment]
Verified as fixed on AMO , discovery pane, new frontend , using nightly , release and some secondary browsers and everything looks fine to me. I will mark the issue as verified based on my results from : https://public.etherpad-mozilla.org/p/ZQNxSyyVwM
