### ISSUE TITLE
In the Tor Browser, Google Analytics script still appears when visiting "Get Add-ons" in about:addons.

### ISSUE THREAD

**Issue by ghost** [mozilla/addons-frontend#2805]
### Describe the problem and steps to reproduce it:

1. Open latest version of the Tor Browser (7.0.2).
2. Open the network monitor in the developer tools.
3. Open `about:addons` then go to `Get Add-ons`.
4. Google Analytics should appear.

### What happened?

Google Analytics script loaded.

### What did you expect to happen?

@tofumatt said that "[This will affect any browser that visits https://discovery.addons.mozilla.org/ with the Do Not Track flag set (that includes Tor Browser).](https://github.com/mozilla/addons-frontend/issues/2785#issuecomment-315212909)" But this is not what happens, instead Google Analytics script appears.

### Anything else we should know?

Note also that the Tor Browser does not set the Do Not Track flag.

**Comment by tofumatt** [comment]
To clarify: I meant that when DNT is enabled in Tor it would disable the script. That said, it seems we are having issues with server caches for that page not varying on DNT headers. We are working on a fix and will let you know when it's deployed.

For what it's worth I believe Tor is looking to disable that pane altogether (given Tor recommends not browsing with extra add-one I think that's the right call anyway).

Sorry about this caching issue. I'll update this bug when we get it fixed.

Matthew Riley MacPherson

**Comment by kumar303** [comment]
> Note also that the Tor Browser does not set the Do Not Track flag.

Ha, really? I am surprised by that.

Thanks for raising the bug. We are indeed working on resolving this for Do Not Track users. I'm closing this issue since it relates to Tor and they are already tracking it here: https://trac.torproject.org/projects/tor/ticket/22900

**Comment by banoaqlla** [comment]
> Ha, really? I am surprised by that.

You shouldn't be :) Here are the reasons that they gave for such choice https://trac.torproject.org/projects/tor/ticket/5501

> I'm closing this issue since it relates to Tor and they are already tracking it here:

I confirm, they fixed it by disabling the Get Addons from the panel. https://trac.torproject.org/projects/tor/ticket/22073
