### ISSUE TITLE
Discovery Pane is still cached when DNT pref is changed

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2806]
### Describe the problem and steps to reproduce it:

- In Firefox (Release or Nightly), start with a new profile. Alternatively, you can empty your cache and make sure DNT (Do Not Track) is disabled in about:preferences
- Load https://discovery.addons.mozilla.org/en-US/firefox/discovery/pane/54.0/Darwin/normal in a tab
- Using Devtools, check network tab and notice that Google Analytics is loaded. You'll see a request for https://www.google-analytics.com/analytics.js which comes from the script tag in the server HTML
- Go to about:preferences and enable DNT
- Go back to the tab with https://discovery.addons.mozilla.org/ , press enter in the URL bar (do not press refresh)

### What happened?

You will still see a request for https://www.google-analytics.com/analytics.js

### What did you expect to happen?

You should not see a request for https://www.google-analytics.com/analytics.js since DNT is enabled

### Anything else we should know?

We need the server to send Vary: DNT so that the browser doesn't use a cached response

**Comment by tofumatt** [comment]
We want to do this for AMO as well, because we also don’t Vary on DNT there.

**Comment by kumar303** [comment]
As far as I can tell, this is only needed for Discopane since that's the only place we tell the browser to cache the response so hard. However, I'm going to add it to all apps just in case.

**Comment by kumar303** [comment]
Actually, no we do need it for AMO too, my bad

**Comment by kumar303** [comment]
I verified that this patch fixed it, using the STR on https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/56.0a1/Darwin/normal

**Comment by vcarciu** [comment]
Verified on Release and Nightly , -dev and Stage and everything looks fine. Marking bug as verified.
