### ISSUE TITLE
 On hover event over the selected Search option, the background color turns white

### ISSUE THREAD

**Issue by brainzest** [mozilla/addons-frontend#2810]
### Describe the problem and steps to reproduce it:

1.Search for a query in search bar on browser ( Firefox, Safari )
2. Go to search results and use search filters. -relevance (default), top rates, most users, and recently updated on left panel. 
3. On hovering/focussing the mouse over the selected Search option, the background color turns white (which is by selection blue) and the text color is also white.

### What did you expect to happen?
 The hover event  shouldn't make background white
### Anything else we should know?

<img width="1270" alt="screen shot 2017-07-16 at 12 56 09 am" src="https://user-images.githubusercontent.com/432669/28242272-cac2cf5e-69c4-11e7-9aac-4276ad22e735.png">

**Comment by tofumatt** [comment]
Thanks for posting! We're going to revamp the search a bit with new mocks so this will get fixed with a bit of a redesign :-)

Matthew Riley MacPherson (sent from mobile)

**Comment by apoorvasingh17** [comment]
Hi, can I work on this issue?

**Comment by tofumatt** [comment]
@apoorvasingh17 This issue will be fixed by a larger overhaul to the search sort. We didn't have an issue for it so I just created it: #2956.

If you would like to work on that issue you can but it might not be the best one to get started with on this repository. 😄

**Comment by apoorvasingh17** [comment]
@tofumatt ohk! Will look for some other issue then :)
