### ISSUE TITLE
Unusable vertical scrollbar in Screenshots section from add-ons details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2821]
Steps to reproduce:
1. Load details page for an extension with screenshots i.e. https://addons-dev.allizom.org/en-US/firefox/addon/video-downloader-player/
2. Observe screenshots section

Expected results:
There are no display or layout issues.

Actual results:
There is an unusable vertical scroll bar.

Notes/Issues:
- issue is not reproducing using Responsive Design Mode
- issue is not reproducing on device using landscape mode
- issue is reproducing for any browser dimensions

Verified on AMO-dev Ff54(Win 7, Android 7.1.2). Reproducing around all servers. 
Video fro this issue:
![scrollbarvert](https://user-images.githubusercontent.com/15685960/28315482-4b812ace-6bc7-11e7-8b1b-111475b2ac10.gif)

**Comment by brainzest** [comment]
![before](https://user-images.githubusercontent.com/432669/28525292-56d635ac-70a1-11e7-84a0-b7e7b6fb6c0c.gif)

After the fix:
![test](https://user-images.githubusercontent.com/432669/28525326-70cb780a-70a1-11e7-8ac3-04639663c469.gif)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix video:
![screenshots](https://user-images.githubusercontent.com/15685960/28624061-8a8cb68e-7220-11e7-81e5-e43328c54b26.gif)
