### ISSUE TITLE
Unable to run this project on windows 10

### ISSUE THREAD

**Issue by viswanathamsantosh** [mozilla/addons-frontend#2822]
### Describe the problem and steps to reproduce it:
*Cloned the project
*yarn
*yarn dev:amo

### What happened?
Throws out an npm error

### What did you expect to happen?
The project should be up and running
### Anything else we should know?

![amoerror](https://user-images.githubusercontent.com/3799600/28322832-bfd6d2e8-6bf4-11e7-935d-3efd56947e7b.JPG)

**Comment by viswanathamsantosh** [comment]
npm log file is not generated. 
Node version: 6.9.1
npm version: 4.0.3
yarn version: 0.16.1

**Comment by viswanathamsantosh** [comment]
Hope someone could help me with this :)

**Comment by tofumatt** [comment]
Probably not related but looks like your version of `yarn` is pretty out of date, it might be worth upgrading.

Could you give us info as to which version of Windows you're on? Usually we're a bit bad at testing on node for Windows, though the project will work flawlessly using [Windows Subsystem for Linux](https://msdn.microsoft.com/en-gb/commandline/wsl/install_guide) if you're using Windows 10. I use it myself and it's great.

**Comment by viswanathamsantosh** [comment]
I tried after upgrading to yarn 0.27.5 but still facing the same issue. Im running on windows 10. let me try on windows subsystem for linux.

**Comment by viswanathamsantosh** [comment]
Thanks @tofumatt ! worked fine on Windows Subsystem for Linux. I was able to get my local up. :)
