### ISSUE TITLE
Modify the disco pane data source for shield study recommendations

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2823]
Related to https://github.com/mozilla/addons-server/issues/5943 (see for additional context)

The disco pane will need some changes in order to point to a different data source to be able to show a user in the shield study a list of recommendations as opposed to the usual curated content.

Here is an example of the URL that will load our Discovery iframe when the [shield study add-on](https://github.com/benmiroglio/taar-experiment/) is installed:

https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%?clientId=1234ABC

**Comment by kumar303** [comment]
Refactoring the add-on reducer in https://github.com/mozilla/addons-frontend/issues/2823 is going to help out with this

**Comment by muffinresearch** [comment]
@kumar303 could you take a look at getting this out for next week now that the API is available. 

Testing this with good data might be tricky since guids that TAAR returns might only exist on production.

**Comment by muffinresearch** [comment]
I'm going to see where the stage/prod instances are at.

**Comment by kumar303** [comment]
Sure

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed".
Thanks!
