### ISSUE TITLE
Replace the retro green favicon with the cool new black one

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2824]
@pwalm says we should use the icon at https://amo-dashboard.herokuapp.com/

It's cool; let's do it! 😄

**Comment by tsl143** [comment]
The Favicon is not setup at the local setup.
It renders default icon from react at local and from `https://addons-dev-cdn.allizom.org/static/img/favicon.ico` at dev server.

**Comment by muffinresearch** [comment]
Needs info on what size icons we want, I think the one I created for the dashboard is probably not sufficient quality.

**Comment by caitmuenster** [comment]
@pwalm, could you provide a copy of this icon?

**Comment by pwalm** [comment]
svg attached!
[amo-favicon.svg.zip](https://github.com/mozilla/addons-frontend/files/1242830/amo-favicon.svg.zip)

**Comment by atiqueahmedziad** [comment]
I am seeing https://amo-dashboard.herokuapp.com is already updated with the black favicon icon.
![screenshot from 2017-08-24 21-58-36](https://user-images.githubusercontent.com/8364578/29675593-6bab731e-8917-11e7-86ca-8f3bd06e0027.png)

**Comment by muffinresearch** [comment]
I'll provide the info on what we need here in terms of format / size etc.

**Comment by muffinresearch** [comment]
See https://github.com/audreyr/favicon-cheat-sheet for modern guidelines. I think we should look to start with the basics and add other things from there.

**Comment by muffinresearch** [comment]
Interestingly mozilla.org just uses a single 64px image in ico format.

**Comment by muffinresearch** [comment]
Here's a 16x16 + 32x32 .ico made from optimized pngs.

[favicon.ico.zip](https://github.com/mozilla/addons-frontend/files/1303247/favicon.ico.zip)

**Comment by muffinresearch** [comment]
I think once the new icon lands in addons server that will be used here by default however we should look to file an issue to fix it for the local development server separately.

**Comment by vcarciu** [comment]
@muffinresearch : should we see this new favicon everywhere where the old green puzzle was used? I am asking because I can see it only in the link from bug(https://amo-dashboard.herokuapp.com)

**Comment by muffinresearch** [comment]
@vcarciu this has essentially been verifed as part of https://github.com/mozilla/addons-server/issues/6433 since in the process the colour got changed to work better with dark and light themes.
