### ISSUE TITLE
Be able to tell apart the new frontend from the legacy frontend in analytics

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2827]
To be able to check things like page perf metrics against the old site we need a good way to tell them apart. 

I'm thinking that a custom dimension would be the best way to do that, but there might be an alternative.

**Comment by muffinresearch** [comment]
Have asked gcull for input into this via email.

**Comment by muffinresearch** [comment]
Gareth has set up a new dimension which is here - we can use this like so:

> I've enabled Custom Dimension 3 in the admin for you and you just need to set the value and send along prior to the pageview request.

```
var dimensionValue = 'SOME_DIMENSION_VALUE';
ga('set', 'dimension3', dimensionValue);
```

**Comment by ValentinaPC** [comment]
Please add some STR so we can check this or the label "qa: not needed". Thanks!
