### ISSUE TITLE
Don't show "Searching for..." text when navigating between search results pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2830]
Steps to reproduce:
1.Go to AMO Stage on your Android device and enter a search term
2.In the search results pages, see the "X results for "searchterm" " text at the top of the page
3.Navigate between search results pages by pressing Next/Previous buttons at the bottom of the page

Expected results:
The "X results for "searchterm" " text at the top of the page remains unchanged when navigating between search results pages 

Actual results:
 "Searching for "Searchterm" " is displayed when navigating between search results pages 

NOTES:
Same issue when sorting the search results

Please see a video for this issue:

![searchlistingpages](https://user-images.githubusercontent.com/1583842/28370656-82be1da8-6ca3-11e7-9064-0804c7aa680b.gif)

**Comment by tofumatt** [comment]
This will be fixed when we move to Saga, but for the record I'd say I disagree: informing the user that they're _performing_ a search (which is what the change in header text does) is a good thing. The current UX was a _bit_ unintentional but I noticed it and thought it was nice as it let the user know a search was happening.

Anyway, this is going to change a fair bit with sagas and I think should be closed. We can re-evaluate it once the new search UX with sagas lands.
