### ISSUE TITLE
Let's replace "View Mobile Site" with something more suggestive

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2835]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/, go to page footer and observe "View Mobile Site"

Expected results:
Maybe we could change the link with something like "View Experimental Site".

Actual results:
The link is named "View Mobile Site".

Notes/Issues:
Verified on FF54(Win 7).
Screenshot:
![2017-07-19_1943](https://user-images.githubusercontent.com/15685960/28378944-adb0c5e4-6cba-11e7-8a14-b764b198b3b4.png)

**Comment by muffinresearch** [comment]
@ValentinaPC see https://github.com/mozilla/addons-frontend/issues/2828 - I'm going to dupe this to that since we're planning to do something here, but it's like it should be distinct to the mobile cookie.
