### ISSUE TITLE
Images in Screenshots section overlaps the container if there are more than 1 images in Safari

### ISSUE THREAD

**Issue by brainzest** [mozilla/addons-frontend#2847]
Images in Screenshots section overlaps the container if there are more than 1 images in Safari

Steps to reproduce:
1. Open [https://addons.mozilla.org/en-US/firefox/search/?q=videos&type](https://addons.mozilla.org/en-US/firefox/search/?q=videos&type) in Safari
2. Go to any extension in the result and check for screenshots which has more than 1 image.
3. The images overlaps the About this extension container.

### What happened?
The images overlaps the About this extension container.

### What did you expect to happen?
The images should be inside the screenshots container with a horizontal scroll

<img width="1280" alt="screen shot 2017-07-24 at 6 22 10 pm" src="https://user-images.githubusercontent.com/432669/28525731-caf076cc-70a2-11e7-8503-1fdf45eaed32.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Safari 10.0.3 (Mac OS Sierra 10.12.3)
Postfix screenshot:
<img width="1280" alt="screen shot 2017-07-31 at 18 50 57" src="https://user-images.githubusercontent.com/15685960/28786550-39ace68e-7622-11e7-9554-8fd2fe68e941.png">

@muffinresearch Just, one thing, there is no horizontal scroll bar to view screenshots, is this ok?

**Comment by muffinresearch** [comment]
> @muffinresearch Just, one thing, there is no horizontal scroll bar to view screenshots, is this ok?

How do you mean? For me there is one, it is just hidden until you scroll.

**Comment by ValentinaPC** [comment]
@muffinresearch : yes, you are correct!
Marking this verified fixed.
