### ISSUE TITLE
Small issue in Extensions/Themes homepage while in Italian

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2852]
Steps to reproduce:
1. Load Extensions homepage on you device i.e https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Change the language to "Italiano"
3. Observe explore categories link

Expected results:
There are no display issues.

Actual results:
At the end of the link there is a "." .

Notes/Issues:
Verified on FF54 (Android 7.2.1). Issue is reproducing on all servers.
Screenshot:
![2017-07-25_1544](https://user-images.githubusercontent.com/15685960/28572545-2eccedb2-7150-11e7-85b2-aff13149917f.png)

**Comment by tofumatt** [comment]
After checking this is an issue in the actual translation–we just need to edit the PO file and it should be fine.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Android 7.1.2)
Postfix screenshots:
![2017-07-26_1642](https://user-images.githubusercontent.com/15685960/28624329-7ff99628-7221-11e7-94d6-d5ff5315c289.png)
