### ISSUE TITLE
Categories are not alphabetically sorted

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2855]
Steps to reproduce:
1. Load categories pages for extensions or themes while using the new desktop pages i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/categories/

Expected results:
Categories are alphabetically sorted.

Actual results:
Categories are not alphabetically sorted.

Notes/Issues:
- same issue in extensions/themes homepages
Verified on AMO-dev FF54(Win 7).
Screenshots for this issue:
![2017-07-26_1853](https://user-images.githubusercontent.com/15685960/28630734-be94344e-7233-11e7-8878-9e7b63909c7c.png)
![11](https://user-images.githubusercontent.com/15685960/28630618-653bbcbe-7233-11e7-8222-cbd81506b295.png)
![22](https://user-images.githubusercontent.com/15685960/28630617-6536a544-7233-11e7-94fa-022fca8b4cd4.png)

**Comment by jvillalobos** [comment]
Mentor: @tofumatt

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7).
Postfix screenshots:
![p](https://user-images.githubusercontent.com/15685960/29168516-e0a25a02-7dd7-11e7-80d7-a08a2680b1f4.png)
