### ISSUE TITLE
Convert Category detail page to load data with a saga

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2857]
We already have a categories saga but we need to update the Category detail page to use it.

Here's how to test for regressions:
* From the home page, click 'Browse all extensions' (or themes)
* Click on 'Explore all categories'
* Click on one of the categories
* Make sure the category detail page loads and works fine

This is a step towards https://github.com/mozilla/addons-frontend/issues/2356

**Comment by tofumatt** [comment]
This uses the search utils though, right? Effectively this is part of the search change because behind-the-scenes they're just using the same search component, I thought.

**Comment by kumar303** [comment]
Do you mean https://github.com/mozilla/addons-frontend/issues/2737 will cover converting the Category detail page to a saga? If so, I think it should be done in a separate patch since `Category` is a top-level component.

**Comment by tofumatt** [comment]
Well, SearchBase will start using a saga so I'd imagine it will implicitly convert. Okay but I'll try to keep it separate.

**Comment by kumar303** [comment]
I took a quick look at this. It definitely needs a saga implementation for search first but I still think it can be kept for a separate patch, after https://github.com/mozilla/addons-frontend/issues/2737

**Comment by kumar303** [comment]
This was fixed in #2737 ❤️

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
For each category issue #2953 is reproducing....don't know if is the same root cause or not?
Please see video:
![cat](https://user-images.githubusercontent.com/15685960/29371597-6df40c74-82b1-11e7-8577-b2e7ecff77e6.gif)
