### ISSUE TITLE
Convert LandingPage to load data with a saga

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2859]
Convert the AMO LandingPage component to load its data using a saga.

To test for regressions:
* Go to the home page
* Click on 'Browse all extensions' (or themes)
* This is served by the LandingPage component. Make sure the page still works.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Both pages are loaded, but for a second the other page is loaded, for example while clicking "Browse all extensions" loads extensions page with themes, and vice-versa.
Logged separate issue for this.
Leaving this unmarked as verified until we figure it out if has something to do with the new issue or not.
