### ISSUE TITLE
Revised AMO header

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#2863]
Below: The header! And it's many states.
![header](https://user-images.githubusercontent.com/6797635/28647452-1c7165cc-721c-11e7-8194-82a2b0492460.png)

This should address a few issues, namely #2745 and #2746 

CSS for transitions and such to follow.

**Comment by tofumatt** [comment]
Huzzah! I dig it.

**Comment by kumar303** [comment]
Very cool! Would the *More* text change to any selected item? (Besides DevHub.)

**Comment by pwalm** [comment]
@kumar303 Yup!

**Comment by pwalm** [comment]
Updated as per our meeting on Wednesday:
![header-revised](https://user-images.githubusercontent.com/6797635/29437917-74fecdd0-8368-11e7-8a0c-7afc055de6cc.png)

Specs to follow!

**Comment by pwalm** [comment]
Spec!
![header revised - spec](https://user-images.githubusercontent.com/6797635/29675618-83b92d60-88aa-11e7-80b8-fc71f8dc4c23.png)

**Comment by tofumatt** [comment]
My goodness that is pretty! ❤️

**Comment by tofumatt** [comment]
I'll likely include https://github.com/mozilla/addons/issues/474 in this issue.

**Comment by pwalm** [comment]
Added the "download firefox" button to bottom of spec:
![header-revised](https://user-images.githubusercontent.com/6797635/29692090-214a7074-88e3-11e7-9a60-8167b380138b.png)

**Comment by vcarciu** [comment]
I verified what was implemented after talking with tofumatt and everything looks good . The username and Explore drop down are still under implementation, but I will add two issues for that for a better QA tracking:
Desktop:
![revisedheaderdesktop](https://user-images.githubusercontent.com/1583842/30171303-479243f2-93fa-11e7-8c91-3a9c53dd23d7.gif)

Mobile:
![revisedheadermobile](https://user-images.githubusercontent.com/1583842/30171876-ca0f0eb8-93fb-11e7-83ed-ea84865c288b.gif)

Download firefox: 
![downloadfirefox](https://user-images.githubusercontent.com/1583842/30171965-157b8d90-93fc-11e7-8868-e3ebcdb1303b.png)
