### ISSUE TITLE
Transparent gradient renders Grey in Safari

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2865]
With the mamo cookie set visit: https://addons.allizom.org/en-US/firefox/addon/download-youtube/
in Safari - not the grey line above the read more link

Safari:

<img width="513" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/28668513-12960786-72c8-11e7-8144-5052854d8e99.png">

Firefox: 

<img width="594" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/28668491-f689ec06-72c7-11e7-9cf5-b4812b34686c.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Safari 10.0.3 (Mac OS Sierra 10.12.3)
Postfix screenshot:
<img width="1280" alt="screen shot 2017-07-31 at 18 38 53" src="https://user-images.githubusercontent.com/15685960/28786028-a8fc7f92-7620-11e7-9112-a33e2c35c8d4.png">
