### ISSUE TITLE
Layout issue in Extensions/Themes homepage while using Safari

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2877]
Steps to reproduce:
1. Load Extensions/Theme homepage using Safari browser https://addons-dev.allizom.org/en-US/firefox/extensions/

Expected results:
The extensions are listed on a single line for each sort option.

Actual results:
Each extension is listed on a new line.

Notes/Issues:
Verified on AMO-dev using Safari 10.0.3 (Mac OS Sierra 10.12.3).
Screenshot for this issue:
<img width="1280" alt="screen shot 2017-08-01 at 10 05 54" src="https://user-images.githubusercontent.com/15685960/28813446-f45575a8-76a1-11e7-9816-d446a331fd12.png">

**Comment by muffinresearch** [comment]
It doesn't look like that for me. Safari: 10.1.2 (12603.3.8), Sierra 10.12.6 (16G29)

<img width="1439" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/28819452-2bf675ee-76a6-11e7-928a-27b8a8edf5f3.png">

**Comment by tsl143** [comment]
This cant be reproduced on Firefox 54/Mac OS 10.12.4

<img width="1278" alt="screen shot 2017-08-02 at 12 01 55 pm" src="https://user-images.githubusercontent.com/5318732/28860489-7ca87620-777a-11e7-9647-97876f9fb2c8.png">

**Comment by ValentinaPC** [comment]
@tsl143 : you need Safari :)
@muffinresearch : maybe the difference is made by the dimension of the display? I have 13" ... or I don't know. :(

**Comment by muffinresearch** [comment]
@ValentinaPC Ah ok - thanks for the info. I still can't repro it though - can you see if you can find out if a specific viewport size causes it? You might find an upgrade fixes it too.

**Comment by muffinresearch** [comment]
@ValentinaPC is this still a problem?

**Comment by ValentinaPC** [comment]
@muffinresearch : this is no longer the case.
Closing.
