### ISSUE TITLE
Big difference between old and new desktop pages while making a search

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2878]
Steps to reproduce:
1. Search for something i.e "firecookie" - https://addons.allizom.org/en-US/firefox/search/?q=firecookie&type=extension
2. Click on "View classic desktop site"

Expected results:
Similar results are listed.

Actual results:
While new desktop pages return 535 results, old desktop page returns 1 result,  for this particular example.

Notes/Issues:
- even if in Extensions tab, from new pages the plugins or search tools are not included, the difference is still big.
Verified on AMO-stage FF54(Win 7). Reproducing on AMO-dev also.
Video for this issue:
![search](https://user-images.githubusercontent.com/15685960/28822060-86b25e16-76c0-11e7-8b0b-0dabe70cdcfe.gif)

#[5209](https://github.com/mozilla/addons-server/issues/5209)

**Comment by ValentinaPC** [comment]
Let me know if this should me moved under the add-on server repository.
Thanks!

**Comment by EnTeQuAk** [comment]
This got fixed via https://github.com/mozilla/addons-server/pull/6171

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Search results for same search term are very similar on new and old desktop pages.
Postfix video:
![search](https://user-images.githubusercontent.com/15685960/29617813-c993d59c-881e-11e7-9eda-dae258b8a5e7.gif)
