### ISSUE TITLE
Themes search results page loads Extensions search results page with wrong URL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2879]
Steps to reproduce:
1.  Load Themes homepage while in new desktop pages https://addons.mozilla.org/en-US/firefox/themes/
2. Make a search 
3. Click "View classic desktop site"

Expected results:
User is redirected to personas search page results.

Actual results:
User is redirected to extensions search page results.

Notes/Issues:
- `&type=persona` is preserved in the URL
Verified on AMO-prod FF54(Win 7).
Video for this issue:
![persona](https://user-images.githubusercontent.com/15685960/28822890-c1756676-76c3-11e7-80f4-5a109d836526.gif)

**Comment by muffinresearch** [comment]
Fixing this would require a rewrite, since this is short-lived I'm not sure it's worth worrying about ahead of replacing the frontend with the new ui.

**Comment by muffinresearch** [comment]
Closing this since the legacy UI is gone.
