### ISSUE TITLE
Long search term is not wrapped

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2880]
Steps to reproduce:
1. Make a search while typing a long search term without spaces (will be quicker on your device) i.e. https://addons.mozilla.org/en-US/android/search/?q=gheriuiergherighsdifghdjgsdklfghdfkjghsdfjksfghsdfgfd

Expected results:
There are no display or layout issues.

Actual results:
The text is not wrapped and causes a layout issue in the "0 results for search_term" header.

Notes/Issues:
- reproducing on new desktop pages also;

Verified on AMO-prod FF54(Win 7, Android 7.2.1).
Screenshots for this issue:
![device](https://user-images.githubusercontent.com/15685960/28826158-b0bf7714-76d1-11e7-9913-1c9b62e1a83a.png)
![desktop](https://user-images.githubusercontent.com/15685960/28826163-b42ca8d6-76d1-11e7-98d2-29f6f4942532.png)

**Comment by ValentinaPC** [comment]
This in not in -dev yet.

**Comment by ValentinaPC** [comment]
This is still not fixed.
Reopening.

**Comment by willdurand** [comment]
@muffinresearch Just tried to reproduce the issue from `master` with Firefox 54 (MacOS) and Chrome: cannot reproduce..

**Comment by tofumatt** [comment]
Yup, I also tried on desktop/resposive design ode and saw:

![screen shot 2017-08-16 at 00 46 37](https://user-images.githubusercontent.com/90871/29341478-739a5ad8-821c-11e7-84da-4cdbb0122d24.png)

I think this is closed, unless it's only happening on actual mobile devices.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7, Android 7.2.1).
Issue was fixed on device, but still **reproducing** in new desktop pages.
I'll attach a video for clarification:
![new-pages](https://user-images.githubusercontent.com/15685960/29357678-fb581a82-8280-11e7-9d03-7234ad512ecd.gif)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF54(Win 7, Android 7.2.1)
Postfix screenshot:
![longterm](https://user-images.githubusercontent.com/15685960/29406131-ce1c4f20-8348-11e7-8a07-38e074395a28.png)
