### ISSUE TITLE
Fira Sans is no longer loaded

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2881]
I just got a new MacBook and it didn't have Fira Sans installed. This meant I hit the addons-frontend site locally and got the page in Helvetica instead of in Fira Sans.

However, I went to https://addons.mozilla.org/ and it loaded the site properly, so it seems this is a config-related issue? [local](http://localhost:3000/en-US/firefox/), [dev](https://addons-dev.allizom.org/en-US/firefox/), and [stage](https://addons.allizom.org/en-US/firefox/) all yield the Helvetica font but [production](https://addons.mozilla.org/en-US/firefox/extensions/) yields Fire Sans.

**Comment by muffinresearch** [comment]
Looks like this is a recent regression - my money would be on https://github.com/mozilla/addons-frontend/commit/4f95431165284ada02c0aee10967214767a3f1ab but we'll need to dig into it to confirm.

**Comment by muffinresearch** [comment]
Sounds like we're hitting: https://github.com/webpack-contrib/file-loader/issues/181

**Comment by muffinresearch** [comment]
Looks good on -dev.

**Comment by ValentinaPC** [comment]
Could you add some STR for us to check this?
Thanks!
