### ISSUE TITLE
Loading indicators aren't show when switching between landing pages

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2882]
Sorry I didn't catch this when doing local testing, I must not have noticed as I was on a fast enough connection that blinking would hide the fact that no loading bars appeared.

### Describe the problem and steps to reproduce it:
If you are on a landing page (`/extensions/` or `/themes/`) then navigate to the other landing page, loading indicators are not shown and the old content remains until the new content is loaded from the server.

### What happened?
The old content remains until the new content loads.

### What did you expect to happen?
There to be an intermediate loading state while the route changes but the load is taking place.

### Screencasts

![2017-08-01 23 06 15](https://user-images.githubusercontent.com/90871/28856028-9c0fbf1c-770e-11e7-91d3-abbe98e95a56.gif)

Loading animation happens on first landing page load, but not on subsequent loads:

![2017-08-01 23 06 35](https://user-images.githubusercontent.com/90871/28856033-a101a8dc-770e-11e7-989e-3d157666e4c0.gif)

**Comment by willdurand** [comment]
Hi! I started to read the code related to this issue. It is the `loading` state attribute that decides whether to display the loading indicators or not, which is only updated when there is an API call.

Question is: how to approach this? `loading` should maybe computed somewhere else? Maybe by first having a component state attribute and `componentWillReceiveProps()` with `setState()` in it.

Otherwise not sure what `setViewContext()` exactly is yet, but maybe this could be there?

**Comment by kumar303** [comment]
Yeah, the `loading` attribute controls the loading indicators (the blurry lines) but *also* the presence of each set of add-ons, i.e. `state.featured`. I think the thing to do is reset each set of add-ons when a new request gets started. For example:

```diff
diff --git a/src/amo/reducers/landing.js b/src/amo/reducers/landing.js
index 6c159823..7fa7272b 100644
--- a/src/amo/reducers/landing.js
+++ b/src/amo/reducers/landing.js
@@ -18,7 +18,7 @@ export default function landing(state = initialState, action) {
   switch (action.type) {
     case LANDING_GET:
       return {
-        ...state,
+        ...initialState,
         addonType: payload.addonType,
         loading: true,
         resultsLoaded: false,
```

**Comment by tofumatt** [comment]
Yup, that solution should be fine.

**Comment by willdurand** [comment]
Indeed, that does the trick. Thanks for the solution.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF54(Win 7).
Loading indicators are shown almost everywhere.
While loading Extensions homepage coming from Explore the indicators are not shown. Things seem to work as expected while coming back from Themes. Is this ok, @muffinresearch ?
Please see video:
![loading-indic](https://user-images.githubusercontent.com/15685960/29401535-40d50ade-833a-11e7-9aa2-a38e391a8a9b.gif)
