### ISSUE TITLE
Install buttons should be disabled for legacy extensions if 57+

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#2888]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1374607

If using a 57+ browser the install button should be disabled in amo and the disco pane preventing an installation of a legacy extension.

Currently as described in https://bugzilla.mozilla.org/show_bug.cgi?id=1374607 if the pref `extensions.legacy.enabled` is false it still looks like you can install a legacy extension except it is disabled immediately.

The disco pane has already moved to only showing web-ext so this is lower priority there but likely if we fix this for the general install button case it will also make sure this happens for disco too in the unlikely event non web-ext content was shown.

**Comment by muffinresearch** [comment]
This should also disable the fallback button for legacy installs in 57+ browsers to handle the edge case where `mozAddonManager` is disabled.

**Comment by muffinresearch** [comment]
We'll need additional copy to explain why the button is disabled - this should probably match up with what we're doing on addons-server.

**Comment by muffinresearch** [comment]
@tofumatt Could you look at this for next week please?

**Comment by tofumatt** [comment]
Will do!

**Comment by jvillalobos** [comment]
Wouldn't this be covered by https://github.com/mozilla/addons-server/issues/5277?

**Comment by muffinresearch** [comment]
@jvillalobos we still need to change the UI for the new frontend as well.

**Comment by ValentinaPC** [comment]
> This should also disable the fallback button for legacy installs in 57+ browsers to handle the edge case where mozAddonManager is disabled.

@muffinresearch : Do you mean that even with the pref set to false, the install buttons should remain the same?
Because they are not. Please see video:
![addto fff](https://user-images.githubusercontent.com/15685960/29618350-858f502c-8820-11e7-8155-794b1f3f3383.gif)

Verified this on AMO-dev FF55(Win 7)
New desktop pages list a red banner and a disabled installation button for add-ons that are not compatible with used FF version.
![inst](https://user-images.githubusercontent.com/15685960/29618408-b9ee03cc-8820-11e7-9d6c-7d19bccfcea2.png)

**Comment by kumar303** [comment]
> This should also disable the fallback button for legacy installs in 57+ browsers to handle the edge case where mozAddonManager is disabled.

...

> Do you mean that even with the pref set to false, the install buttons should remain the same?

He meant that without mozAddonManager (i.e. with the testing pref set to false) the fallback buttons should also be disabled in the same way as the switch was disabled. I verified that this is true in 57:

<img width="782" alt="screenshot 2017-08-23 09 18 12" src="https://user-images.githubusercontent.com/55398/29620741-5eaf6d3e-87e4-11e7-811f-103d30889d8f.png">

**Comment by ValentinaPC** [comment]
@kumar303 : got it! verified, and you are right!
But this should not apply for Disco Pane also?

**Comment by kumar303** [comment]
This should apply to Disco Pane as well but that may be tricky to test since mozAddonManager is always enabled for Disco Pane (but perhaps there is a way). More importantly, no real user would ever use Disco Pane without mozAddonManger enabled.

**Comment by ValentinaPC** [comment]
Based on above comments and verification this can be marked as verified.
