### ISSUE TITLE
"View Mobile Site" redirects any search to "Explore"

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#2889]
Steps to reproduce:

1. Load AMO homepage https://addons.mozilla.org/en-US/firefox/ .
2. Click on "Themes".
3. Perform a search.
4. Click on the "View Mobile Site" button.

Expected results:
The user is redirected to the "Themes" search.

Actual results:
The user is redirected to the "Explore" search.

Notes/Issues:
Verified on FF54(Win 10). Issue is reproducing on all AMO servers.
This issue is reproducible for searches for: Extensions, Themes, Collections, Dictionary & Language Packs.
Gif for this issue:
![collections on mobile](https://user-images.githubusercontent.com/28138132/28880808-cb1ba406-77ae-11e7-8d22-387802a264aa.gif)

**Comment by muffinresearch** [comment]
Since the old pages will be replaced in Q4 this probably isn't worth fixing.
