### ISSUE TITLE
No "Read More" link for add-ons with long description

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2890]
Steps to reproduce:
1. Load https://addons.allizom.org/en-US/firefox/extensions/ page
2. Click on any add-on with long description i.e. Omnibar
3. Observe About this extension section

Expected results:
There is a "Read More" link and a part of description is hidden.

Actual results:
Entire description is displayed. No "Read More" link.

Notes/Issues:
- "Read More" link is displayed after page refresh.
- reproducing also on device.

Verified on AMO-stage(Win 7, Android 7.2.1). Reproducing on all servers.
Video fro this issue:
![read more](https://user-images.githubusercontent.com/15685960/28881683-9229a8d4-77b1-11e7-9837-a717ef3a5b53.gif)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev on a new FF55 clean profile under Win 7.
Read more link is still not displayed, until after page refresh.
Please see video:
![read-more](https://user-images.githubusercontent.com/15685960/29511450-eb74a38e-8667-11e7-9db7-91dd670503d3.gif)

**Comment by willdurand** [comment]
Hi @ValentinaPC, I cannot reproduce the issue in dev, can you confirm? Thanks!

**Comment by ValentinaPC** [comment]
Hi @willdurand, seems like this got fixed somehow during the way. I cannot reproduce either.
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1)
Postfix screenshot:
![rm](https://user-images.githubusercontent.com/15685960/29866446-14f2a8ee-8d81-11e7-8bb2-ba4d72d41af9.png)

**Comment by willdurand** [comment]
Potential explanation: I fixed a bug on this detail page (#3017) to make sure it loads the data correctly.
