### ISSUE TITLE
Declare response status with Redux, not NestedStatus

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2892]
We currently declare the response status by rendering a [`NestedStatus`](https://github.com/Ambroos/react-nested-status) component with a `code` somewhere in the tree of rendered components.

This is terrible because it's hard to control or understand what the final status code will be. See https://github.com/mozilla/addons-frontend/pull/2891

Let's use the power of Redux instead by:

* Introducing a reducer/state for response code
* dispatching an action to change the response code whenever needed

We probably need to move to be on `react-redux-router` (https://github.com/mozilla/addons-frontend/issues/181) first so we know to reset the status whenever a new request is made. This may not apply though since our main concern is server side rendering.

**Comment by tofumatt** [comment]
Agreed, this sounds much better. The NestedStatus component is definitely a bit of a hack and is opaque. 👍

> This is terrible
😆

**Comment by kumar303** [comment]
Now that https://github.com/mozilla/addons-frontend/issues/181 has landed, we can probably just use `getState().routing` to figure out the status code.
