### ISSUE TITLE
Add lint rule to check new line for scss

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#2897]
We can have a lint rule for ensuring there is a new line before writing a css rule.

Referring to https://github.com/mozilla/addons-frontend/pull/2884#issuecomment-319846246

**Comment by muffinresearch** [comment]
Looks like this rule will cover it: https://stylelint.io/user-guide/rules/rule-empty-line-before/

**Comment by tsl143** [comment]
@muffinresearch , we already have this rule in `stylelintrc`.
But it has ignore rule for inside-block
https://github.com/mozilla/addons-frontend/blob/master/.stylelintrc#L32

**Comment by muffinresearch** [comment]
@tsl143 it would be good to understand why that didn't fail.

**Comment by tsl143** [comment]
@muffinresearch I understand, they are not failing as they are inside a block and lint-rule says ignore the style-rules which are inside a block.
So now either we should correct all of the rules or just live with it.

**Comment by muffinresearch** [comment]
@tsl143 I think we can get what we want by using https://stylelint.io/user-guide/rules/rule-empty-line-before/#first-nested and removing the ignore for inside-block.

**Comment by tsl143** [comment]
Awesome, thanks @muffinresearch this is exactly what we need :)

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
