### ISSUE TITLE
"Invalid date" after add-on submission

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2898]
Steps to reproduce:
1. Submit a new theme https://addons.allizom.org/en-US/firefox/addon/thm2/
2. Approve it
3. Check the date while using new desktop details page for the newly submitted theme

Expected results:
Date is displayed.

Actual results:
Instead of date the message "Invalid date (Invalid date)" is displayed.

Notes/Issues:
- after about 30 minutes the correct date appears;
- not reproducing for add-ons;

Verified on AMO-stage FF54(Win 7). Issue is reproducing on all servers.
Screenshot for this issue:
![2017-08-03_1054](https://user-images.githubusercontent.com/15685960/28913035-4189a850-783f-11e7-98f0-05953f7c4175.png)

**Comment by muffinresearch** [comment]
@ValentinaPC is this still an issue?

**Comment by ValentinaPC** [comment]
@muffinresearch : yes, as described above.
![invalid](https://user-images.githubusercontent.com/15685960/31544559-08edfae2-b024-11e7-9a6f-bdbf9f930c79.png)

**Comment by willdurand** [comment]
@ValentinaPC any chance to know what is returned by the API (in the devtools?)?

**Comment by ValentinaPC** [comment]
@willdurand : 
- there is a 403 API response few minutes after add-on review - https://addons-dev.allizom.org/api/v3/reviews/review/?user=10622061&addon=494914&version=1533149&lang=en-US - could this be related with the "invalid date" thing?

![author](https://user-images.githubusercontent.com/15685960/31940633-8423ef2c-b8c7-11e7-9be6-363ceb642827.gif)

**Comment by willdurand** [comment]
@ValentinaPC no, I think it is a problem with the response returned for the request right above (`/api/v3/addons/search/`).

**Comment by muffinresearch** [comment]
This one needs further investigation - it sounds like it may be an addons-server API issue.

**Comment by willdurand** [comment]
I believe this ha been fixed.

**Comment by AlexandraMoga** [comment]
This can't be reproduced anymore. The correct date is populated immediately after submission.

![image](https://user-images.githubusercontent.com/31961530/60891023-26ed6700-a265-11e9-8ef4-5f641e82f3b6.png)
