### ISSUE TITLE
Convert the Discovery Pane to load data with sagas

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2902]
The Discovery Pane needs to load data with a saga instead of async-connect.

To test for regressions:
* Load the discovery pane via `about:addons`
* Make sure the add-on data still loads
* Make sure themes can be previewed and installed
* Make sure extensions can be installed/uninstalled

**Comment by SVSanta** [comment]
Verified as fixed on AMO-dev FF57(Win 10).
Postfix gif:
![sagas](https://user-images.githubusercontent.com/28138132/29271622-0734a866-8105-11e7-920d-8172c99dfbbf.gif)
