### ISSUE TITLE
Can’t install some WebExtensions on Firefox 57.0a1

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/addons-frontend#2910]
### Describe the problem and steps to reproduce it:
On AMO, some WebExtensions, despite having a “Compatible with Firefox 57+” box have a greyed out “Add to Firefox” button saying “This add-on is not compatible with your version of Firefox.”, even when the WebExtension doesn’t have an explicit max version.

1. Go to [AMO](https://addons.mozilla.org/).
2. Find [any arbitrary WebExtension](https://addons.mozilla.org/en-US/firefox/tag/firefox57).
3. Some of them can’t yet be installed.

### What happened?
Some WebExtensions have a greyed out “Add to Firefox” button saying “This add-on is not compatible with your version of Firefox.”.

### What did you expect to happen?
That WebExtensions should have a green “Add to Firefox” that works.

### Anything else we should know?
List of WebExtensions that I am aware as not working at the time of this issue’s creation, despite being installable just fine through [`about:addons`](about:addons):
- [`about:about` Button](https://addons.mozilla.org/firefox/addon/firefox-about-button/)
- [Application Menu](https://addons.mozilla.org/firefox/addon/application-menu/) (Inspired by [CTR](https://addons.mozilla.org/en-US/firefox/addon/classicthemerestorer/) and [Supported by Aris](https://addons.mozilla.org/en-US/firefox/addon/application-menu/reviews/890444/))
- [Reddit Enhancement Suite](https://addons.mozilla.org/firefox/addon/reddit-enhancement-suite/)

**Comment by diox** [comment]
I can't seem to reproduce the problem with nightly 57.0a1 (2017-08-05), at least with those 3 add-ons, I see the green "Add to Firefox" button and not the greyed out button w/ "This add-on is not compatible with your version of Firefox.” text.

**Comment by ExE-Boss** [comment]
They still don’t work for me.

It’s probably similar to back when the [firefox57](https://addons.mozilla.org/en-US/firefox/tag/firefox57) tag was being added, where some automated tests are being performed on the WebExtensions.

**Comment by diox** [comment]
> It’s probably similar to back when the firefox57 tag was being added, where some automated tests are being performed on the WebExtensions.

I'm the one who built the code adding that tag and I have no idea what you are referencing :)

**Comment by ExE-Boss** [comment]
It does work on a new profile, so it’s probably something on my end.

**Comment by diox** [comment]
Closing then. I suspect it's just your user-agent string, or maybe you have an add-on that messes up with the javascript on AMO.

**Comment by ExE-Boss** [comment]
I tried disabling all my add-ons and that didn’t help either.

After that I found out that my user agent is somehow  `Mozilla/5.0 (Windows NT 6.1; rv:50.0) Gecko/20100101 Firefox/50.0` (it should be: `Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0`), which explains why AMO was reporting incompatibility, but it doesn’t explain why the user agent is wrong.

**Comment by ExE-Boss** [comment]
Turns out that this is a duplicate of [bug 1394448](https://bugzil.la/1394448).
