### ISSUE TITLE
Create explicit API data mappings (i.e. replace normalizr) for AMO

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2917]
We use magical schemas (via [normalizr](https://github.com/paularmstrong/normalizr)) to store API data in a mappable format. Sometimes this helps look up objects better but other times we have code that *unmaps* it entirely.

Instead of using `normalizr`, let's just map what we need explicitly in our reducers. It might require more code but the mapping logic will be a lot easier to follow. This is what our reducers are for!

---

Let's do this for AMO!

For QA: please make sure add-ons are loaded correctly and no information are missing (icons, names, titles, authors)

**Comment by tofumatt** [comment]
Sounds good, normalizr is a kind of weird API for me anyway.

**Comment by kumar303** [comment]
This is annoying to work around: https://github.com/paularmstrong/normalizr/issues/290

**Comment by kumar303** [comment]
Grep the code for this issue number. I'm adding some TODOs.

**Comment by ioanarusiczki** [comment]
Looks good to me. Verified on AMO dev with FF62-Win10
