### ISSUE TITLE
Eye Alarm and Restclient: strings not extracted for l10n

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-frontend#2919]
### Describe the problem and steps to reproduce it:
1). https://addons.mozilla.org/bg/firefox/addon/eyes-alarm/
2). https://addons.mozilla.org/bg/firefox/addon/restclient/

### What happened?
1). A few strings are not extracted as the rest of the page. 
2). This page is not extracted. 
### What did you expect to happen?
Extract the strings so they are localizable.

**Comment by wagnerand** [comment]
Hello!

Are you talking about strings on those pages or strings inside the add-ons?

**Comment by peiying2** [comment]
I am not sure if this is the right place to file for both issues, I am simply relaying community's findings.  If the strings inside an add-on is not localized normally, we can make it clear what strings are extracted and what usually are not.

**Comment by wagnerand** [comment]
@peiying2 would you be able to find more details about this? I am not sure how actionable to current report is. Thank you.

**Comment by muffinresearch** [comment]
@peiying2 it might be easiest to add screenshots indicating the parts of the page you're referring to.

**Comment by muffinresearch** [comment]
@peiying2 please could you clarify the issue? See above ^

**Comment by peiying2** [comment]
@muffinresearch I was relaying the message from a localizer who reported the problem through #l10n on IRC. From what we could see, the description is in English. I think he expects it to be localizable.

**Comment by muffinresearch** [comment]
@peiying2 ah ok - this isn't a bug then, the description can only be localized by the author.

**Comment by peiying2** [comment]
@muffinresearch Just so I know what to look for to avoid filing this kind of bugs, Is it up to the author (developer of the app) to make it localizable?  And when he/she does, you (AMO devs) will extract the strings to make it available on Pontoon. Correct?
