### ISSUE TITLE
Cannot build locale bundles for all apps

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2923]
### Describe the problem and steps to reproduce it:

Run this command to build all app bundles:

```
ADDONS_FRONTEND_BUILD_ALL=1 yarn build
```

### What happened?

It builds all app bundles:
```
$ ls dist/*.js
dist/amo-7ef7b5286cbc10a03561.js	
dist/disco-e9940474a666699cb69a.js
```

### What did you expect to happen?

It should also build locale bundles for each app.

### Anything else we should know?

If you build a specific app, locale bundles are built as expected, e.g.

```
NODE_APP_INSTANCE=amo yarn build
```

The difference is that `NODE_APP_INSTANCE` triggers some magic config loading logic. I suspect that's the issue but I can't see where it may be happening.

**Comment by tofumatt** [comment]
Looks like it's right here: https://github.com/mozilla/addons-frontend/blob/master/bin/build-locales#L25

Seems like if it's not specified we could build all locales? Though really we just want to test each app's size, right? So we should be specifying a `NODE_APP_INSTANCE` env var anyway...

**Comment by kumar303** [comment]
> Looks like it's right here: https://github.com/mozilla/addons-frontend/blob/master/bin/build-locales#L25

How so? That if branch allows [buildAll](https://github.com/mozilla/addons-frontend/blob/master/bin/build-locales#L20) which is set by `ADDONS_FRONTEND_BUILD_ALL=1`.

> So we should be specifying a NODE_APP_INSTANCE env var anyway...

Well, we want to test all app bundle sizes so it seems suboptimal to run the bundle size check in a loop for each app. Also, this approach introduces some complications because `yarn build` cleans the dist directory before running and `bundlesize` doesn't let you define a "context" to configure each app. In other words, it's a workaround that doesn't work because I tried it :)

**Comment by tofumatt** [comment]
Oh shoot, right. So that's just a bug 😢

**Comment by willdurand** [comment]
So the issue is related to the config. The condition in `config/default.js` allows a `null` value for `appName`, which is the case when `NODE_APP_INSTANCE` is not set (because we set `ADDONS_FRONTEND_BUILD_ALL` instead).

`appName` being `null` means the `require` for locales in `src/core/client/base.js` does not load any file.
