### ISSUE TITLE
Q3/Q4 AMO-rewrite - Missing "Via: [version] [hash value].cloudfront.net (CloudFront)" header on favicon costs us 15 points/% in WebPageTest

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-frontend#2924]
(Sorry for the egregious title/summary - tweak as you see fit!)

Compare the response headers for /favicon.ico between AMO-rewrite (dev)[0] and prod[1], and you'll see that the former is lacking the following line, which the latter has:

```Via: 1.1 173748bfac8713c88182cd1b8118e99a.cloudfront.net (CloudFront)```

This omission takes us down to a WebPageTest score on AMO-rewrite dev of 85/100, vs 100/100, on prod.

The logic from WebPageTest's side in determing the above is partly in https://github.com/WPO-Foundation/webpagetest/blob/d53fba00bc0941cbfc9c15cb27944c1ba052f345/agent/wpthook/cdn.h#L201

/cc @digitarald (thanks for the pro-tip!)

[0] https://www.webpagetest.org/result/170810_2E_QK7/3/details/#step1_request8
[1] https://www.webpagetest.org/result/170810_BR_RKQ/3/details/#step1_request15

**Comment by stephendonner** [comment]
@bqbn is this something I can/should file in Cloud Services, Operations:AMO, as discussed in our meeting yesterday?

**Comment by bqbn** [comment]
@stephendonner that's the correct category to file for AMO ops related tickets.

Going forward, if you think an issue is ops related, feel free to file it in Bugzilla and we'll look into and prioritize  them accordingly. Feel free to cc Dev members as you see fit.

Meanwhile, I recommend closing this one so it won't show up in Dev's queue.

Lastly, are [0] and [1] safe to click now? Yesterday I had to rotate my LDAP password due to a security issue in wpt product.

**Comment by stephendonner** [comment]
Thanks, @bqbn - earlier in the meeting we had (before you were able to join), we agreed that filing here, first, in addons-frontend was fine, as long as it's a perf issue related to the redesign/rewrite, for extra visibility, and, like you suggest, we can and should always then move the appropriate backend or Ops-related bugs in Bugzilla, which I will now do :-)

Also, https://webpagetest.org is a public instance, so there shouldn't be any issue in using it.  The problems relating to encoded credentials were isolated to our 3 private instances of WPT.

**Comment by stephendonner** [comment]
Closing out, now that I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1389393
