### ISSUE TITLE
"Tap to preview" button state is not changed after switching browser tabs when preview of a theme is activated

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2927]
Steps to reproduce:
1.Go to https://addons.mozilla.org/en-US/firefox/addon/galaxy-wonder-of-nature/
2.Click the "Tap to preview" button and observe that the theme was applied and the button is now labeled "Cancel preview"
3.Switch to another tab in your FF browser and observe that the theme is not applied anymore
4.Go back to the tab where theme page is opened

Expected results:
Button state should be changed to "Tap to preview" again since preview is not active anymore

Actual results:
Button state is still "Cancel preview" even if the preview is not applied

Please see a video for this issue:
![teptopreview](https://user-images.githubusercontent.com/1583842/29218614-0823db96-7ebe-11e7-8aab-2f6015cead2d.gif)

**Comment by muffinresearch** [comment]
Will be redundant once the previews get removed see https://github.com/mozilla/addons-frontend/issues/3056

**Comment by svitlana-galianova** [comment]
Hi,
I was looking for new issues to fix and after I tried to reproduce this one, I realized that it was fixed and probably should be closed now.

![2](https://user-images.githubusercontent.com/31850821/39010244-00d055f2-43dc-11e8-86a3-9a2940df81ff.gif)

**Comment by muffinresearch** [comment]
Previews have been removed.
