### ISSUE TITLE
Show test suite file names in failure output

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2928]
### Describe the problem and steps to reproduce it:

Trigger a test failure that happens on the event loop. In other words, one that won't produce a stack trace pointing back to the test file.

### What happened?

You have no easy way to figure out which test file produced the error. Example:

<img width="666" alt="screenshot 2017-08-11 10 26 14" src="https://user-images.githubusercontent.com/55398/29220091-aaa16a30-7e7f-11e7-9469-1568ae559127.png">

### What did you expect to happen?

You should be able to easily figure out which test file produced the error.

### Anything else we should know?

We can totally do this now that Jest runs from NodeJS! We can start every test with `describe(__filename, ...)` which will produce errors like this:

<img width="666" alt="screenshot 2017-08-11 10 23 57" src="https://user-images.githubusercontent.com/55398/29220149-cef9cf12-7e7f-11e7-9ac9-fff5fe1756d7.png">

**Comment by kumar303** [comment]
Hah, ignore me. I have *so much console output* (thinking of https://github.com/facebook/jest/issues/4156) that I forgot how Jest prints the failing test name at the top:

<img width="373" alt="screenshot 2017-08-11 11 00 48" src="https://user-images.githubusercontent.com/55398/29221467-7b564dd6-7e84-11e7-9b14-a016ea50ee2b.png">

**Comment by tofumatt** [comment]
That's what I thought happened but figured maybe with a catastrophic failure it wouldn't print.

Nothing to see here then! 😅

**Comment by kumar303** [comment]
I thought about this more and I still think the change would be helpful. What do you think? Here are the benefits I see:

* The bottom line of a failing test will always show the filename. Otherwise, you'd have to scroll up beyond all the console logging to find it.
* We won't have to think of what to type in the initial `describe()` function ever again :) It can just always be `__filename`

**Comment by tofumatt** [comment]
I'm okay with all root-level `describe()`s amounting to `describe(__filename)` but I'd rather there just be a helper–that sort of boilerplate is annoying...

Dunno if that's possible though. I'm cool with doing that though, I can never think of what to name these things!

**Comment by kumar303** [comment]
I don't think a helper would be helpful because you'd have to pass it `__filename` since that is different depending on the file. In other words, a helper would have to look like:

```js
describe(showFile(__filename), ...);
```
which is pointless.

**Comment by tofumatt** [comment]
Oh shoot, duh, right. I didn’t think that one through 😓
