### ISSUE TITLE
Rename withErrorHandling to withErrorHandlerRenderer

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2931]
I was a bit confused to learn we have two HOCs for our error rendering: `withErrorHandling` and `withErrorHandler` (https://github.com/mozilla/addons-frontend/pull/2909#discussion_r132560152). They're very close and I think could be easily mistaken for each other as-is–plus they don't clearly differentiate themselves based on name, so we should rename the one that automatically outputs to something more meaningful.

**Comment by kumar303** [comment]
maybe `withRenderedErrorHandler` ? 🚲

**Comment by tofumatt** [comment]
Even better, I dig it 👍 🚴
