### ISSUE TITLE
Don't render pagination if there is only one set of results

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2932]
Right now we'll render a paginator that has disabled forward and back buttons if the page size is 25 add-ons per-page but we return 23 add-ons.

I thought (here: https://github.com/mozilla/addons-frontend/pull/2909#discussion_r132562395) it might be nicer to hide the paginator when it's not needed, but I'm wondering if that's the right UX decision. Is it better to hide it when unneeded or just leave things disabled as they are now so users are more familiar with the layout/components on the site?

@pwalm what do you think? It feels weird to render a whole component full of disabled items but maybe it's better to keep the page items somewhat consistent so people don't think there's (urgh) infinite scroll.

**Comment by grahamperrin** [comment]
> … if the page size is 25 add-ons …

[Allow readers to prefer more than 25 per page · Issue #3038 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/3038)

**Comment by pwalm** [comment]
If there is no pagination, don't show paginator. 👍

**Comment by tsl143** [comment]
This has already been taken care of
<img width="1278" alt="screen shot 2017-10-09 at 12 13 12 pm" src="https://user-images.githubusercontent.com/5318732/31327210-5d56b196-aceb-11e7-8756-40374cd5637b.png">

**Comment by willdurand** [comment]
Yes, it seems covered by this commit: https://github.com/mozilla/addons-frontend/commit/e14e7f134b41518ac0851082e8efe7dda28408d6, although there might be something else related to the 23/25 add-ons/page size thing.

**Comment by muffinresearch** [comment]
Closing based on https://github.com/mozilla/addons-frontend/issues/2932#issuecomment-335076465

**Comment by AlexandraMoga** [comment]
This can be marked as verified fixed

![image](https://user-images.githubusercontent.com/31961530/35903752-2f12bec6-0be9-11e8-9594-2ac2ae92a05d.png)
