### ISSUE TITLE
Add new footer links to AMO

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2935]
See: https://github.com/mozilla/addons/issues/471

Looks like these footer links may need UX consideration re: placement, etc. so adding in @pwalm for some UX. Maybe "put them where the old ones go" is good enough, though!

**Comment by nileshgulia1** [comment]
I want to work on this issue.
Can I add footer links like "About,Our blog,Mobile site.."etc....

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/addons-frontend/issues/3158
