### ISSUE TITLE
Infer query params to use for paginator based on existing location.query data

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2937]
Basically, see: https://github.com/mozilla/addons-frontend/pull/2909#discussion_r133043076

Instead of using a set of query params we want the paginator to care about we should just pass location to the paginator and use the data already set in `location.query` (plus page, obviously) as the things that should be query params. It's less error-prone when refactoring and a little more elegant to boot.

**Comment by muffinresearch** [comment]
See https://github.com/mozilla/addons-frontend/issues/1971 which relates to passing the page_size info from the response to the paginator which should always be correct.

**Comment by muffinresearch** [comment]
I think this can probably be closed since #1971 is now fixed and that should control the pagination based on the returned data.
