### ISSUE TITLE
…/collections/…/edit/#addons-edit fails to find some add-ons

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#2948]
Spun off from [Ability to Add to collection · Issue #2768 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/2768)

## Example

[Clear Tabs](https://addons.mozilla.org/firefox/addon/clear-tabs/) can not be found. Seeking: 

- _Clear Tabs_ lists one thing – _Opaque + ClearTabs_, not Clear Tabs
- _Clear_ lists a few things but not Clear Tabs
- _Tabs_ lists a few things but not Clear Tabs.

**Comment by grahamperrin** [comment]
## Synonymity

Another example: seeking _Archive URL_, as the extension is listed in `about:addons`, finds nothing. 

I discovered that the name in `about:addons` is different from the name at `addons.mozilla.org`. [Save URL to Wayback Machine :: Versions :: Add-ons for Firefox](https://addons.mozilla.org/firefox/addon/save-url-to-wayback-machine/versions/) – no mention of _Archive URL_ there, but that's the extension. 

## First words

Seeking _Save URL_ fails to find _Save URL to Wayback Machine_; seeking _Wayback_ found what's required. 

Result: https://addons.mozilla.org/firefox/collections/grahamperrin/favorites/ work in progress …

**Comment by tofumatt** [comment]
Hi there,

This issue tracker is for the new add-ons frontend (currently accessible with a mobile user agent or by clicking "View Mobile Site" on addons.mozilla.org). I'm not sure I follow your issue or if it's related to the front-end.

Could you clarify the issue you're having and attach any screenshots? Thanks.

**Comment by grahamperrin** [comment]
Thanks, no mention of 'mobile' at the head of https://github.com/mozilla/addons-frontend/ or in https://github.com/mozilla/addons-frontend/blob/master/README.md

Should we raise an issue for this repo to be more clearly identifiable? 

----

The failures to find affect desktop, not mobile. Should I recreate the issue, with screenshots, in the addons-server repo?

**Comment by tofumatt** [comment]
Eventually these pages will run the desktop site too but not yet, sorry it's a bit confusing 😢

Yeah, I think this is an issue with addons-server, if you could file there (with screenshots) that'd be great. Sorry about that!
