### ISSUE TITLE
Categories never load (via server rendering)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2949]
### Describe the problem and steps to reproduce it:

- Go to the all-categories page, such as https://addons-dev.allizom.org/en-US/firefox/extensions/categories/
- Click on a category, like Bookmarks
- Bookmark-related add-ons load as expected
- Click the browser Refresh button to reload it

### What happened?

Bookmark-related add-ons never load. You just see the placeholders.

### What did you expect to happen?

Bookmark-related add-ons should load.

### Anything else we should know?

This is probably fallout from https://github.com/mozilla/addons-frontend/issues/2737 but I think the component already had loading issues that were just previously hidden.

**Comment by kumar303** [comment]
This one was tricky to track down but I have a patch ready (it just needs test fixups and cleanup). The issue is that when `Category` first renders on the server, [this logic](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Category/index.js#L45-L47) returns `NotFound` instead of rendering `Search`. Because of that, `Search` does not get a chance to dispatch its data loading actions. Confusingly, the second render (after sagas have ended) will cause `Search` to trigger its loading actions. By that time it's too late because no sagas are running to process them.

**Comment by kumar303** [comment]
Everything seems to be working on dev. I'll cherry-pick to stage.

**Comment by kumar303** [comment]
btw, I now know a ton about how sagas work; their `SagaMonitor` feature is pretty handy: https://redux-saga.js.org/docs/api/index.html#sagamonitor

**Comment by kumar303** [comment]
I'm a bit worried this bug will happen again so I filed https://github.com/redux-saga/redux-saga/issues/1132

**Comment by kumar303** [comment]
I just tested on stage. Everything looks fine.

**Comment by SVSanta** [comment]
Verified as fixed on AMO-stg FF55(Win 10, Android 7.2.1).
Tested on all categories for Extensions, Themes for Firefox, Android, Thunderbird and SeaMonkey.
Postfix gif:
![categories](https://user-images.githubusercontent.com/28138132/29405885-f83b6166-8347-11e7-8f51-a793f622b001.gif)
