### ISSUE TITLE
-dev app for Firefox Accounts shows up as "AMO-dev local development (unused?)"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2950]
Seems like someone flagged the Firefox Accounts app we use for development as "unused". See screenshot:

<img width="1276" alt="screenshot 2017-08-15 23 01 53" src="https://user-images.githubusercontent.com/90871/29338581-be418a84-820d-11e7-910b-7b9fed3de3ca.png">

This is the app name that shows up when trying to sign in from `localhost:3000` when running `yarn amo:dev`.

We should probably let whoever admins that setting know we are still using it. Not sure where to file this really... but logging here now so we at least know it's happening.

**Comment by kumar303** [comment]
We just need to find someone who has access to edit https://oauth-stable.dev.lcip.org/console/client/063dd7f1edaf1507

**Comment by muffinresearch** [comment]
@mstriemer did you have access to this?

**Comment by mstriemer** [comment]
Updated

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
