### ISSUE TITLE
Implement new Search Sort widget

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2956]
The new search sort widget will be more standard (no custom weird buttons) and look like:

<img width="366" alt="screenshot 2017-08-16 16 35 47" src="https://user-images.githubusercontent.com/90871/29371722-04a5f7b0-82a1-11e7-8c9c-db962d60f025.png">

This will fix:

* #2611
* #2810

**Comment by tofumatt** [comment]
What kind of options do we want to see in Browser Version, @pwalm/@jvillalobos? Once we go to WebExtensions (which this site is aiming to primarily serve) offering version selection seems odd. Even operating system seems a bit weird but I understand there could still be WebExtensions that communicate with a host process only available on certain OSes.

Still, do we want to offer browser version as a filter at all? If so, what do we put in there... just every version of Firefox? Seems a beast to maintain...

**Comment by jvillalobos** [comment]
I'm thinking we could default to a `Firefox 57 and Above` option, and have only another `All Versions` option.

**Comment by tofumatt** [comment]
Alright, that works. Thanks!

**Comment by tofumatt** [comment]
Actually, sounds like this should just be a checkbox: “Include Legacy Extensions”. I think that will be simpler to understand than a drop-down with just two options.

**Comment by jvillalobos** [comment]
Makes sense.

**Comment by tofumatt** [comment]
@diox made a good point about why we even bother to surface old/imcompatible extensions in the UI for 57+ users here: https://github.com/mozilla/addons-frontend/pull/2969#issuecomment-323547861

@jvillalobos–can we just axe the versions param in the filters altogether? We can keep it as a hidden search param but showing it in the search filters seems silly when it will just show a bunch of uninstallable extensions that won't work.

**Comment by kumar303** [comment]
> I'm thinking we could default to a Firefox 57 and Above option, and have only another All Versions option.

...

> Actually, sounds like this should just be a checkbox: “Include Legacy Extensions”.

Could we make it a more general checkbox like *Hide Incompatible Extensions* which would default to checked? I don't think the concept of *legacy* will be easy for people to understand. 

Also, I don't see how we need to make a special case for 57 since version compatibility will continue to be an issue post 57. If we do need this to be a special case for 57 then how about making the message more explicit?

**Comment by tofumatt** [comment]
Yeah, you're right about 57. Again though, I'd rather just not surface this at all? What value is there to searching for an extension you can't use? 😞

If we had to use it having *Hide Incompatible Extensions* that defaulted to checked is better UX, I agree. Thanks 👍

**Comment by jvillalobos** [comment]
Here are the groups of users we should be targeting:
* Users of release versions of Firefox. They should generally be offered add-ons that are compatible with 57+, though some may be lagging a couple versions behind and may still want to install legacy add-ons. If we want to hide that filter for 57+ users, that's okay with me, though that doesn't cover all users.
* Users of Firefox ESR. Similarly, we want to favor 57+, but they will still have a need to look for legacy add-ons for quite a while (almost a year until ESR 59 replaces 52). `Incompatible` isn't really an accurate term in this case, and we've been using `Legacy` publicly for some time.

**Comment by tofumatt** [comment]
The way the underlying code works is by default:

* Firefox 57+ users automatically send `appversion=57.0` (well, whatever their app version actually is, but the minimal to trigger sending it is having FF57). They only get WebExtensions in the search results; any extension they don’t see in those results we would just disable installation of anyway via #2934. Surfacing those add-ons in search would, at the VERY most, allow them to go to a page where the add-on is flagged as incompatible.

* Users who aren’t yet at version 57 get all add-ons because we don’t send an appversion filter. They will continue to get legacy extensions in their search results

It sounds like we’ve already covered, the “Show Legacy Extensions” will only surface unactionable results. Sounds like we should omit that checkbox. 👍🏻

**Comment by ValentinaPC** [comment]
The new sort widget was implemented.
Verified this on AMO-dev FF55(Win 7)
Postfix screenshot:
![sort](https://user-images.githubusercontent.com/15685960/29914984-09c28c7e-8e43-11e7-8b67-63b55c8ec36a.png)

@tofumatt : the last filter criteria - Browser version - was not added tho the new sort widget, intended?

**Comment by tofumatt** [comment]
Yes, we decided not to add the browser version.

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
Based on above comments we can mark this verified-fixed.
