### ISSUE TITLE
"More featured extensions" will not show any featured extensions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2957]
Steps to reproduce:
1.Load https://addons.allizom.org/en-US/firefox/extensions/featured/ on mobile view

Expected results:
A list of featured extensions is loaded

Actual results:
User is asked to "Please enter a search term to search Firefox Add-ons."

Notes:
Reproducible also for: 
https://addons.allizom.org/en-US/firefox/themes/featured/

Please see a video for the issue:
![morefeatured](https://user-images.githubusercontent.com/1583842/29373129-e727e896-82b5-11e7-821c-16ca5d2efa56.gif)

**Comment by vcarciu** [comment]
Please note that this is happening on Android devices too.

**Comment by muffinresearch** [comment]
Looks like it makes a request for the data [1], it just doesn't display anything. 

[1] https://addons.allizom.org/api/v3/addons/featured/?app=firefox&page_size=25&type=extension&lang=en-US

**Comment by muffinresearch** [comment]
Whether this is picked / is a release blocker will depend on what the patch looks like - if it's a big or risky patch we might be better to wait.

**Comment by tofumatt** [comment]
The culprit is the new `hasSearchFilters` in `SearchResults` component. This should be a low-stakes fix. Working on it with some tests to catch this for next time...

**Comment by vcarciu** [comment]
Verified as fixed on Stage : 
![veriffeatstage](https://user-images.githubusercontent.com/1583842/29420234-1663cbf6-837a-11e7-8250-d5060771a60b.gif)
