### ISSUE TITLE
Can't install add-on by moving installation slider

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#2959]
The installation button is styled as a slider, which can confuse some people about how it works. It currently only supports tapping on it, but it should also support a slide motion, given its design.

Related forum threads:
https://discourse.mozilla.org/t/cannot-move-slider-to-activate-add-on/
https://discourse.mozilla.org/t/no-way-to-load-webextension-from-amo-on-android-fennec/

**Comment by tofumatt** [comment]
The install slider is no more, so I'm closing this. Even in the future: it will be a button.
