### ISSUE TITLE
"Tap to preview" button is not RTL

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2963]
Steps to reproduce:
1.Go to any theme details page in mobile view
2.Change language to any RTL language (https://addons.allizom.org/ar/firefox/addon/sunrise-on-the-pier-jen/)
3.Observe the "Tap to preview" button

Expected results:
"Tap to preview" button should be RTL

Actual results:
"Tap to preview" button is not RTL

NOTES:
Reproducible on production
Reproducible on Android devices

Please see screenshot for this issues : 
![taptopreview](https://user-images.githubusercontent.com/1583842/29412941-64f55b16-8363-11e7-9ea0-7f0da09b5245.png)

**Comment by kumar303** [comment]
Thanks, good catch

**Comment by tofumatt** [comment]
Note: The tap to preview button will be going away in the future/Q3; installing the theme will be the new way to preview it as new themes will not allow previewing and installing/uninstalling with the button is essentially the same action.

**Comment by kumar303** [comment]
Oh, I didn't know that. We really shouldn't spend time on this then. Thanks again, @vcarciu, for spotting the bug though.
