### ISSUE TITLE
Horizontal scrollbar without a scroll

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2965]
Steps to reproduce:
1. Load details page for an add-on with one screenshot i.e. https://addons-dev.allizom.org/en-US/firefox/addon/ad-killer/
2. Observe screenshot section

Expected results:
There is no horizontal bar.

Actual results:
There is an horizontal bar (without a scroll option).

Notes/Issues:
Verified on FF55(Win 7). Issue is reproducing in all servers.
Screenshot for this issue:
![screenshot](https://user-images.githubusercontent.com/15685960/29460188-afc4d8d4-842f-11e7-9ddf-a2814b3114f0.png)

![2017-09-01_1553](https://user-images.githubusercontent.com/15685960/29970591-df407006-8f2d-11e7-98f7-72cb7fbb91dc.png)

**Comment by muffinresearch** [comment]
@ValentinaPC please can this be refiled on addons-server - it doesn't relate to the new frontend.

**Comment by ValentinaPC** [comment]
@muffinresearch : it actually does relate to the new desktop pages. :)
I'll make a wider screenshot:
![2017-09-01_1553](https://user-images.githubusercontent.com/15685960/29970591-df407006-8f2d-11e7-98f7-72cb7fbb91dc.png)

**Comment by muffinresearch** [comment]
@ValentinaPC ah ok, my bad. Thanks for clarifying!

**Comment by muffinresearch** [comment]
@pwalm -since this was already filed I duped the #3762 here - please let us know what we should look to aim for. We can also see if it's possible to make the display on windows better in the meantime.
