### ISSUE TITLE
Green install button for incompatible langpacks

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2966]
Steps to reproduce:
1.Go to https://addons.mozilla.org/en-US/firefox/addon/english-us-language-pack/ on latest nightly
2.Try to install the lang pack from the green install button

Expected results:
If the lang pack is not compatible with Firefox version, the button should not be green

Actual results:
The button is green, but an incompatibility message is displayed when trying to install it and lang pack cannot be installed 

Please see video for this bug:
![langpackgreenbutton](https://user-images.githubusercontent.com/1583842/29462363-c48295c4-8437-11e7-99b5-eee0e129ecb9.gif)

**Comment by kumar303** [comment]
Hi @vcarciu , thanks for adding a video. In the video you are running the old site which is in a different code base. Can you re-file the bug over there? https://github.com/mozilla/addons-server/

**Comment by vcarciu** [comment]
@kumar303 : oh , sorry , I will file this under addons-server 
Thanks
