### ISSUE TITLE
Layout display issues in screenshot slider

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#2968]
Navigate to https://addons.mozilla.org/en-US/firefox/addon/epubreader/
Observe screenshot section.

### What happened?
Block contains first addon image and some portion of other image

### What did you expect to happen?
The block should contain single image.

![screen shot 2017-08-19 at 8](https://user-images.githubusercontent.com/5318732/29487885-fdf11510-851d-11e7-9307-b6d3d794843a.png)

**Comment by muffinresearch** [comment]
It's not actually supposed to only show a single item in the view.

The latest mocks have this:

<img width="224" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30436663-9a1e47b4-9964-11e7-85fc-0a32b0ebf3f1.png">
