### ISSUE TITLE
Jest test output is too big because of console logging

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#2980]
This has been happening realistically since Jest but I think the bundle size has made it more intense. Basically our test output is so huge that Travis stops rendering it and it makes looking up failed tests quite difficult.

I don't think there's an easy fix but I'm filing this here because having to download the raw logs for failing tests is pretty annoying and locally I'll often run `yarn test -- --silent` because otherwise it's way too loud.

We should fix things up so test output, especially on Travis, is nice and concise so we can see–at a glance–test failures.

**Comment by kumar303** [comment]
I think this will help https://github.com/facebook/jest/issues/4156

Also, maybe it's possible to hide webpack output?

**Comment by kumar303** [comment]
This isn't going to happen: https://github.com/facebook/jest/issues/4156

At the very least we start running jest without colors on Travis because that will make it easier to read in the raw log.

**Comment by willdurand** [comment]
\o/
