### ISSUE TITLE
"View classic desktop site" is not working anymore on -dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#2981]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/ in mobile view
2.From any page , click the "View classic desktop site" on the bottom of the page

Expected results:
Classic desktop page is displayed 

Actual results:
A "#desktop" text is added to URL, but nothing happens

NOTES:
Not reproducible on Stage

Please see video for this bug : 
![viewclassicdesktopsite](https://user-images.githubusercontent.com/1583842/29566848-eb7ef18a-8753-11e7-810e-fc2a0828511e.gif)

**Comment by tofumatt** [comment]
Before reporting any further errors with -dev, know that this seems to be an issue where the JS on the page isn’t being loaded. This will cause a lot of errors. I’ll look into this...

**Comment by tofumatt** [comment]
Guessing this has to do with a library update, possibly DOMPurify. I'm checking now.

<img width="510" alt="screenshot 2017-08-22 14 13 43" src="https://user-images.githubusercontent.com/90871/29567390-f58e9b44-8744-11e7-91a5-5ff883908439.png">

**Comment by willdurand** [comment]
It is a known DOMPurify issue: https://github.com/cure53/DOMPurify/issues/249.

**Comment by vcarciu** [comment]
Verified as fixed : 
![classicviewpostfix](https://user-images.githubusercontent.com/1583842/29573500-cf2c32cc-8767-11e7-881e-c55eeeea2559.gif)
