### ISSUE TITLE
Turn on CSP for local development

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2984]
We rely on CSP (Content Security Policy) rules in production and on our hosted dev servers but we don't have CSP enabled for local development. This is mostly because the dynamic assets served by the webpack server are a bit tricky to deal with. If possible, let's turn on CSP so that our local environment will see failures just like production.

**Comment by kumar303** [comment]
This is definitely tricky because so many libraries use eval and inline styles for development. I'm not really sure that it's worth it because our CSP policy will end up being so far from production anyway.

I'll leave this issue open in case someone else has an idea for it.

I got this far but there are still errors in the console I don't understand:

<details>
  <summary>Patch</summary>


```diff
diff --git a/config/development-amo.js b/config/development-amo.js
index 4429b073..7b129bd1 100644
--- a/config/development-amo.js
+++ b/config/development-amo.js
@@ -1,3 +1,10 @@
+import { sentryHost } from './lib/shared';
+
+const staticHost = 'http://127.0.0.1:3001'; // webpack dev server
+const amoLocal = 'http://olympia.dev'; // standard host for Docker
+const amoDev = 'https://addons-dev.allizom.org';
+const amoStage = 'https://addons.allizom.org';
+
 module.exports = {
   apiHost: 'http://localhost:3000',
   proxyApiHost: 'http://olympia.dev',
@@ -5,4 +12,30 @@ module.exports = {
   proxyEnabled: true,
   fxaConfig: 'local',
   trackingEnabled: false,
+  staticHost,
+  CSP: {
+    directives: {
+      connectSrc: ["'self'", sentryHost, staticHost],
+      fontSrc: [staticHost],
+      formAction: ["'self'"],
+      scriptSrc: [
+        staticHost,
+        'https://www.google-analytics.com/analytics.js',
+        "'unsafe-eval'",
+      ],
+      styleSrc: ["'self'", staticHost, "'unsafe-inline'"],
+      imgSrc: [
+        "'self'",
+        'data:',
+        staticHost,
+        // Here are some possibilities for where you may get images from
+        // depending on whether you ran `yarn amo`, `yarn amo:dev`,
+        // or `yarn amo:stage`
+        amoLocal,
+        amoDev,
+        amoStage,
+        'https://www.google-analytics.com',
+      ],
+    },
+  },
 };
```

</details>

**Comment by willdurand** [comment]
Could we imagine a CI script instead? This might be better than nothing.

Quickly found this example: https://github.com/yahoo/csptester/blob/master/csp-validator/csp-validator.js.

**Comment by kumar303** [comment]
Yeah, that might be worth a try. This is how to make a production build: https://github.com/mozilla/addons-frontend/#building-and-running-services

**Comment by muffinresearch** [comment]
As you mention I'm not sure that enabling a very lax policy for local dev buys us that much since it will allow things that we'd otherwise want to be caught if a mistake is made in development.
