### ISSUE TITLE
Installation button is on the wrong side on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#2990]
Steps to reproduce:
1. Load details page for an add-on on your Android device using FF55 i.e. https://addons-dev.allizom.org/en-US/android/addon/cloud-viewer/?src=ss
2. Observe installation button

Expected results:
Button is in the right side.

Actual results:
Button is on the left side.

Notes/Issues:
- not reproducing on desktop pages

Verified on AMO-dev FF55(Android 7.2.1). Issue is only reproducing on -dev.
May be related with #2888 or with #2752 .
Screenshot for this issue:
![1](https://user-images.githubusercontent.com/15685960/29622891-4e4b38e4-882d-11e7-866e-7f219df9c408.png)

**Comment by willdurand** [comment]
Hum indeed, I have modified the order of the elements. This issue will be fixed in #2753 though.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Adnroid 7.2.1.)
Postfix screenshot:
![install](https://user-images.githubusercontent.com/15685960/29772253-9d1b8844-8c00-11e7-8ec6-117acb4807d9.png)
