### ISSUE TITLE
Document how to install missing fonts for Sketch

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2992]
When developers set up Sketch for viewing the UX mocks they need to install some fonts

**Comment by willdurand** [comment]
Can we archive the mobile Sketch file? It seems outdated now, and I have relied on the wrong one at the beginning 😞

**Comment by tofumatt** [comment]
I think that’s fine; feel free to move them in a PR. I don’t think they’ve been updated in ages...
