### ISSUE TITLE
Number of addons doesn't require to refresh after pressing "next" button

### ISSUE THREAD

**Issue by atiqueahmedziad** [mozilla/addons-frontend#2997]
### Describe the problem and steps to reproduce it:
1. Visit any extension category page. (Example - https://addons-dev.allizom.org/en-US/firefox/extensions/social-communication/)
2. You can see there is written on top the number of add-ons that have been found. 
![screenshot from 2017-08-24 22-48-11](https://user-images.githubusercontent.com/8364578/29677922-838bb8de-891e-11e7-9272-781e90e6a7e7.png)

3. Go to the bottom and press the **"next"** button. Observe the number of add-ons found section.
 
### What happened?
 When you press the next button, the number of add-ons are refreshed. The many times you are pressing the next button, the number of add-ons is refreshed every time.

### What did you expect to happen?
This is unnecessary because the number of add-ons doesn't change when one goes to the next or previous page.

### Screenshot
![screenshot from 2017-08-24 22-36-40](https://user-images.githubusercontent.com/8364578/29678173-65d581d4-891f-11e7-92cd-c77b31555912.png)

**Comment by willdurand** [comment]
Thanks for reporting this issue. It is refreshed because of the way we consume API data. While it seems unnecessary, it does not display invalid information so I am going to close this issue.
