### ISSUE TITLE
Move all calls to getAddonIconUrl() to reducer state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#2999]
We do this a lot:

```js
const iconUrl = getAddonIconUrl(addon);
```

This helper function will return a fallback URL if `addon.icon_url` is not on the allowed CDN domain. This is important for security. We should try to do it in the reducer instead so that it can simply be accessed as `addon.icon_url` and so that people don't forget to call `getAddonIconUrl()`.

**Comment by bobsilverberg** [comment]
I think this code quality issue is worth keeping around.
