### ISSUE TITLE
Add Homepage carousel 

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#3000]
Primary components of the new Homepage carousel will include:

- Headline is the only copy element needed 
- @pwalm will experiment with designs to see if a CTA is required; would it be too minimalist or un-engaging to eschew?

[PRD](https://docs.google.com/document/d/1JLNsuRbd8m4uG-HW5j67_sAT4wb1z-pAj0YaHd_76wE/edit#heading=h.ifofy8kjhyvh) for reference

@pwalm @muffinresearch

**Comment by pwalm** [comment]
Carousel spec below!
![carousel spec](https://user-images.githubusercontent.com/6797635/30043406-068ecf1a-91ac-11e7-9732-bc738e83d605.png)

**Comment by pwalm** [comment]
Notes:
- Photos will be pulled from Unsplash.com
- Opacity of the colour overlay is 80%

**Comment by muffinresearch** [comment]
@devaneymoz please can we get the copy for the initial content first along with any references to the assets per slide? As discussed the first set of content will be added directly via the source code with editorial tools to follow later.

**Comment by devaneymoz** [comment]
@muffinresearch To make sure I'm clear, you want to know the actual copy/content we'll launch the new carousel with? 

Or can it be dummy copy/content for the sake of the design/build phase? 

I ask because if the launch is still more than a few months away it would be ideal to hold on making final programming decisions until we're closer (for example, between now and December we may get a few more killer Chrome ports or something we'll want to spotlight). 

But if indeed you need actual launch programming, it's not impossible to do. Please give me a sense of how much time I have to work with.

**Comment by muffinresearch** [comment]
@devaneymoz the launch is due to be ahead of 57 (currently ideal release would be very early November) so I'd like to get as close to real copy as soon as possible. Changing links and copy is easy enough though so getting something and updating is won't be too much of an issue.

**Comment by devaneymoz** [comment]
Carousel content is reflected in the [launch content plan](https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#). 

This is also reflected in issue [3152](https://github.com/mozilla/addons-frontend/issues/3152)

**Comment by tofumatt** [comment]
@pwalm Can you let us know which images we should use for each of the carousels in the [launch content plan](https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#)? I'll use generic things for now but we'll want specific images 😄

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7, Android 7.2.1).
- first load of the AMO homepage displayed the caroused on vertical
![vertical](https://user-images.githubusercontent.com/15685960/31212468-680c325e-a9a9-11e7-9fbf-d121964dc76a.png) - going to another page and coming back seems to fix this issue.
- navigation in carousel is difficult while swapping
![stuck](https://user-images.githubusercontent.com/15685960/31212566-e2b667cc-a9a9-11e7-9ede-8c9cd3824015.gif)
-third option from the carousel loads a 404 link - https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/privacy-matters/
- on device navigation points are cut
![2017-10-05_0850](https://user-images.githubusercontent.com/15685960/31212638-4a6aa66c-a9aa-11e7-8e9c-5baf0009b8a7.png)

If you wanna track this separately, please let me know.
Reopening until then.
Thanks!

**Comment by ValentinaPC** [comment]
Updated: seems like first issue was tracked in https://github.com/mozilla/addons-frontend/issues/3349 .

**Comment by tofumatt** [comment]
Actually I’ll close this but if you could open new issues for the mis-aligned navigation dots that would be great! 😊
