### ISSUE TITLE
design Slider Shelves (AMO front-end desktop redesign)

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#3001]
Slider shelves will be a new editorial vehicle, as part of the AMO desktop redesign (they're comprised of individually displayed add-ons). Primary components include:

- One short text field for overarching context (3 - 8 words, typically)
- @pwalm to play with how the metadata of various individual add-ons will appear in the shelf (icon, title, # of users?; perhaps during hover state star rating appears?)

[PRD](https://docs.google.com/document/d/1JLNsuRbd8m4uG-HW5j67_sAT4wb1z-pAj0YaHd_76wE/edit#heading=h.ifofy8kjhyvh) for reference. 

@pwalm @muffinresearch

**Comment by pwalm** [comment]
Spec below:
![slider shelves and blocks](https://user-images.githubusercontent.com/6797635/30045466-69140936-91b9-11e7-9903-075611fc077b.png)

**Comment by muffinresearch** [comment]
I think we got what we needed out of this.
