### ISSUE TITLE
design Subject Shelves (AMO front-end desktop redesign)

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#3002]
Subject shelves will be a new editorial vehicle, as part of the AMO desktop redesign (they're comprised of editorially branded icons representing various types of content, such as "Ad blockers" or "Bookmarks" which in turn lead to curated collection pages). Primary components include:

- Fixed headline, such as "I'm interested in..."
- @devaneymoz will deliver the two dozen or so subjects that will comprise the ecosystem of editorial subject shelf brands to @pwalm for design

[PRD](https://docs.google.com/document/d/1JLNsuRbd8m4uG-HW5j67_sAT4wb1z-pAj0YaHd_76wE/edit#heading=h.ifofy8kjhyvh) for reference. 

@pwalm @muffinresearch

**Comment by pwalm** [comment]
Spec below!
![slider shelves and blocks](https://user-images.githubusercontent.com/6797635/30045450-53d5cb5e-91b9-11e7-9aed-2b93b046f996.png)

**Comment by pwalm** [comment]
This is kind of already implemented, so I don't think I need to spec it out?

**Comment by devaneymoz** [comment]
@pwalm: how is it already implemented? 

These "subjects" will be comprised of new, original topics—not to be confused with AMO's standard categories. It's kinda confusing because some topical overlaps will occur. For example, AMO has a "Privacy" category, but that's not a Subject Shelf; whereas we may have Subject Shelves that relate to privacy, such as... "Ad Blockers" or "Anti-Tracking"

I need to deliver to you the final list of subjects here (maybe 15 - 24), and can prioritize that for this week. These were the items you were planning ot make custom icons for.

**Comment by pwalm** [comment]
Sorry, to clarify: the structure of the shelf has been done and is implemented already. The content (icons, etc) have not been done yet. I’m good to go on icon structure whenever you’ve got your list all set. 👍

**Comment by muffinresearch** [comment]
@pwalm @devaneymoz Do you have a screenshot that you can add to the description of the issue? It'll help tie the concepts to something more concrete.

**Comment by pwalm** [comment]
Design-wise, they are the same. Content-wise, they're a bit different. Not sure they should be merged based on that.

**Comment by devaneymoz** [comment]
Slider and subject shelves certainly have distinct purposes from a content perspective (sliders display individual add-ons while subject shelves have icons that lead to collections), and I think ideally they also offer some visual distinction from each other as well.

**Comment by devaneymoz** [comment]
Below comprises the ecosystem of branded "subjects" that may be populated into a subject shelf at any given time (thus each requires a corresponding icon). Perhaps we'll add more to the ecosystem over time, but this should suffice to start. 

- Ad Blockers
- Privacy Protection
- Bookmarks
- Video Downloaders
- Password Managers
- Watching Videos
- Educational Tools
- Shopping
- Having Fun!
- Organizing Tabs
- Email Support
- Social Media

@pwalm ready for your icon making magic!

**Comment by pwalm** [comment]
Subject icons are [here](https://github.com/mozilla/addons-frontend/tree/master/assets/icons/subjects)!

**Comment by pwalm** [comment]
Screenshot for reference:
<img width="846" alt="screen shot 2017-10-05 at 6 35 27 pm" src="https://user-images.githubusercontent.com/6797635/31259502-fb2a56cc-a9fb-11e7-823c-b83a038f3fe8.png">

**Comment by willdurand** [comment]
I think this could be closed now.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/31549021-7b96a48e-b035-11e7-94ba-17881992711e.png)

![image](https://user-images.githubusercontent.com/31961530/31549054-9d2bb49a-b035-11e7-87af-fb01fe3b9259.png)

**Comment by pwalm** [comment]
Hey how come these shelves don't look like what's been spec'd out in the PRD?

<img width="653" alt="screen shot 2017-10-13 at 11 08 33 am" src="https://user-images.githubusercontent.com/6797635/31559841-f00ee490-b006-11e7-888a-f989633dae33.png">

**Comment by devaneymoz** [comment]
Is it a matter of adding the translucent background colors? If so I agree that is a superior aesthetic.

**Comment by willdurand** [comment]
Hi @pwalm, would you like something like this?

<img width="1392" alt="screen shot 2017-10-16 at 18 31 52" src="https://user-images.githubusercontent.com/217628/31623635-56ef7f9e-b2a0-11e7-8282-c7da15de1dc0.png">

**Comment by pwalm** [comment]
Looks good, @willdurand, just a couple tweaks:
- Using the [Photon colours](http://design.firefox.com/photon/visuals/color.html), let's set the background at 50 and the icon colour at 90.
- Make the icons bigger, have them max out at 96px.

![screen shot 2017-10-16 at 2 22 09 pm](https://user-images.githubusercontent.com/6797635/31636001-b5921bd8-b27d-11e7-9498-e01e1afd5146.png)

**Comment by willdurand** [comment]
@pwalm thanks, here it is:

<img width="1392" alt="screen shot 2017-10-17 at 11 25 03" src="https://user-images.githubusercontent.com/217628/31657110-da8d2c06-b32d-11e7-81a0-92187426ba8a.png">

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF56 (Win10 and Android 7.0)
Postfix screenshot:

![image](https://user-images.githubusercontent.com/31961530/31672633-c84ba922-b365-11e7-995f-dcab2053f969.png)

![image](https://user-images.githubusercontent.com/31961530/31672665-db102542-b365-11e7-9efa-29ded7109557.png)
