### ISSUE TITLE
new promo area on Detail pages (AMO front-end desktop redesign)

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#3003]
We want to add a new content promo area to Detail pages. The leading concept is to leverage a new, automated [add-on recommendation tool](https://docs.google.com/document/d/1v8yKnzD2hQnIpN8HWesGDkYOXdaeOHZbGY9P7M3y7cI/edit?ts=5953f1d3) that is currently being tested. This wil require a completely new design element for these pages. 

It's worth noting that if the Shield study does not produce the results necessary for implementation—or if this tool simply isn't ready in time for the desktop redesign debut—we should have a backup plan. Perhaps leveraging a [slider shelf](https://github.com/mozilla/addons-frontend/issues/3001). 

@pwalm @muffinresearch

**Comment by muffinresearch** [comment]
For the future recommendations engine work will need a fall-back in any case so anything we do here will have a future use as a fallback.

First step is to decide what's the most appropriate data to show, maybe top X for the same categories as the current add-on?

**Comment by devaneymoz** [comment]
I like the concept of "Top X" from the same category. Or perhaps featured extensions from the same category, shown as they are atop category pages.

**Comment by pwalm** [comment]
Promo area follows the same spec as the slider shelf and block spec:
https://github.com/mozilla/addons-frontend/issues/3001

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/addons-frontend/projects/5
