### ISSUE TITLE
Changelog doesn’t appear if it is submitted after the extension is reviewed

### ISSUE THREAD

**Issue by ExE-Boss** [mozilla/addons-frontend#3004]
### Describe the problem and steps to reproduce it:
1. Submit an extension update
2. Start writing the changelog for the latest version
3. Have it reviewed
4. Finish writing the changelog for the latest version
5. Submit the changelog for the latest version

### What happened?
The changelog for the version doesn’t appear

### What did you expect to happen?
The changelog for the version should appear

### Anything else we should know?
The extension and version where this happened ([Application Menu](https://addons.mozilla.org/firefox/addon/application-menu/versions/0.1.5)).

#### The version changelog should be:
```html
<b>Changes – 0.1.5</b>
<ul>
<li>Photon Theme no longer highlights the disabled expander icons on hover</li>
<li>Implemented Classic Theme for those who want the menu to resemble Firefox 4–28.</li>
<li><a href="https://addons.mozilla.org/firefox/user/ntim/">Tim Nguyen</a> implemented the Exit, Save Page As… and a part of the Fullscreen command.
<ul>
<li>Disclaimer: The Exit command might potentially cause issues with Session Restore with sufficiently large amounts of open windows, but no such issue came up during testing.</li>
</ul>
</li>
<li>The Popup is now closed when an action is performed, mimicking the behaviour of Firefox 4–28.</li>
<li>The shortcut for the Exit command was changed to Firefox’s <code>Ctrl+Shift+Q</code>.</li>
</ul>
```

Which can be seen [here](https://github.com/ExE-Boss/app-menu/releases/tag/0.1.5) on the GitHub repository.

#### Re-filed at:
mozilla/addons-server#6253

**Comment by kumar303** [comment]
Hi @ExE-Boss, thanks for taking the time to file an issue. Can you re-file it in [addons-server](https://github.com/mozilla/addons-server/issues/new)? I know this is a "frontend" issue but the Developer Hub frontend is still served from the repo I linked to.

**Comment by ExE-Boss** [comment]
I have now re-filed this at mozilla/addons-server#6253.
