### ISSUE TITLE
Remove better-npm-run

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#301]
We might not need better-npm-run anymore. We have a few long commands that it makes nicer but lots of short ones that it makes much more verbose. If it is reasonable to remove it would should get rid of it.

**Comment by muffinresearch** [comment]
Since we have less env vars in those commands now since the new config landed I think it makes sense to remove it.

**Comment by muffinresearch** [comment]
A counter argument would be that `better-npm-run` will do the right thing with env vars x-platform.

**Comment by muffinresearch** [comment]
I'm not sure we do still want to remove this. Closing for now - we can re-open if it does seem more of an issue later.
