### ISSUE TITLE
Search results page has a height of more than 17000px on Chrome/Desktop view

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3015]
When displaying search results, _e.g._, https://addons-dev.allizom.org/en-US/firefox/search/?q=ad+block, then Chrome users will show an extra height:

![screen shot 2017-08-28 at 17 30 06](https://user-images.githubusercontent.com/217628/29780564-8c1d5ed0-8c16-11e7-928f-465b43b08450.png)

It does not happen on small screens (< 768px).

---
Chrome Version 59.0.3071.115 (Official Build) (64-bit) on MacOS.

**Comment by vcarciu** [comment]
Verified as fixed : 
![space](https://user-images.githubusercontent.com/1583842/31622628-9f26f36e-b2a5-11e7-8254-eb51ed1617bf.png)
