### ISSUE TITLE
Accessing second search suggestion is not working as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3017]
Steps to reproduce:
1. Load Extensions homepage https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Search for something i.e. "love"
3. Click on a search suggestion 
4. Search for something else i.e. "hate"
5. Click on a search suggestion

Expected results:
Corresponding add-on details page is loaded.

Actual results:
The page is continuously loading.

Notes/Issues:
- issue is reproducing in Themes page also

Verified on FF55(Win 7, Android 7.2.1). Issue is only reproducing on dev.
Video for this issue:
![loading search res](https://user-images.githubusercontent.com/15685960/29812246-9d72eb4e-8cae-11e7-807b-808515d360ef.gif)

#2747

**Comment by tofumatt** [comment]
A quick guess is we aren't checking for `componentWillRecieveProps` or something similar on the `Addon` page to `dispatch` a new fetch call because previously we didn't have add-ons that linked to other add-ons on the page.

**Comment by willdurand** [comment]
Exact. No `fetchAddon()` call when addon changes. I am working on it!

**Comment by tofumatt** [comment]
Ah, okay then, I shall ignore. Feel free to ping me for a review 😄

**Comment by kumar303** [comment]
lol at love vs hate. Good catch, @ValentinaPC. I actually remember seeing this locally (d'oh) but I couldn't reproduce it so I thought it was fleeting.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix video:
![free](https://user-images.githubusercontent.com/15685960/29863255-c3887bae-8d77-11e7-9dd4-2b1ba6be787e.gif)
