### ISSUE TITLE
No results search has continuously loading search suggestions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3019]
Steps to reproduce:
1. Load homepage https://addons-dev.allizom.org/en-US/firefox/
2. Tap something that would not return any results in the search field
3. Observe suggestions

Expected results:
No suggestions are displayed.

Actual results:
Continuously loading suggestions are displayed.

Notes/Issues:
Verified in FF55(Win 7,Android 7.2.1). Issue is only reproducing on -dev.
Video for this issue:
![suggestions](https://user-images.githubusercontent.com/15685960/29815000-e187c882-8cb7-11e7-97ef-f40ccc15cdda.gif)

#2747

**Comment by tofumatt** [comment]
This is working as expected; we can't really determine right now locally what is a reasonable set of characters in all locales to consider "likely to return autocomplete results" so we'll always loading the "loading" state while we make an autocomplete request.

This is the component working as intended 😄

**Comment by kumar303** [comment]
Hmm. The way this bounces is pretty terrible. However, I couldn't think of a realistic search term that would reproduce it. We should keep an eye on this.

**Comment by tofumatt** [comment]
Fair enough actually. It might be we just want fewer loading text suggestions too.

There are also a few issues with the spacing jumping around a tiny bit but I’m working on that after rebasing the header changes onto the new search suggestions...
