### ISSUE TITLE
Check authentication state consistently 

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3020]
Now that we have proper user state (https://github.com/mozilla/addons-frontend/pull/2989) let's make all components answer the question "is the user logged in?" consistently. Some of them were accessing `api` state and some were accessing `user` state.

For QA: please verify that this doesn't cause any regressions in each part of the site that requires user log in.

**Comment by willdurand** [comment]
I think the last commit in #2989 is supposed to fix this.

**Comment by kumar303** [comment]
Awesome! Thanks for diving into that.

**Comment by SVSanta** [comment]
Verified as fixed on AMO-dev FF55(Win 10).
For: refresh, login, restart, submit theme, extension, developer hub, reviewer tools, admin tools, approve, reject, comment, Thunderbird, seamoneky, android, multiple users, etc.
