### ISSUE TITLE
Let users download incompatible add-ons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3021]
### Describe the problem and steps to reproduce it:

* Do something to your Firefox user agent to make AMO think it is incompatible. For example, use anti-fingerprinting settings to make your version look older (see https://bugzilla.mozilla.org/show_bug.cgi?id=1393283).
* Go to the detail page for an add-on that you know is compatible

### What happened?

The install button may be disabled

### What did you expect to happen?

Even though AMO thinks the add-on is incompatible, it should still let you download the XPI file anyway.

### Anything else we should know?

By letting the user download the file, they can at least see if Firefox supports the add-on or not. They will have to decipher browser console messages to debug it but, hey.

The current site lets you do this. See the 'download anyway' button:

<img width="496" alt="screenshot 2017-08-29 11 52 13" src="https://user-images.githubusercontent.com/55398/29833293-8c1823ee-8cb0-11e7-8e61-a6fd9c12080f.png">

**Comment by Thorin-Oakenpants** [comment]
@kumar303 - see https://bugzilla.mozilla.org/show_bug.cgi?id=1394448#c10

[1] https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/AddonManagerWebAPI.cpp#39

**Comment by kumar303** [comment]
Dup'ing to https://github.com/mozilla/addons-frontend/issues/3445 because it explains more scenarios that would cause a user to end up in this state
