### ISSUE TITLE
Make add-on reducer state more explicit

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3024]
It's really tough to see what properties we actually store in the add-on reducer state. This has led to numerous bugs and has also made it tricky to add new add-on properties.

I'd like to start by restructuring the reducer a bit and getting rid of all spreads, carefully. This will be focused on preparing to solve the following bugs:

* Lack of platform support: https://github.com/mozilla/addons-frontend/issues/2998
* Incomplete theme objects: https://github.com/mozilla/addons-frontend/issues/3014

For QA: please test for regressions in AMO and the Discovery Pane for anything related to installing add-ons and themes.

**Comment by willdurand** [comment]
I was feeling the same when thinking about new features to add. Semi-related, I have converted the addon code into a ducks module: https://github.com/willdurand/addons-frontend/commit/933f81cfd86ece933e6149186fe4a2f168c6b609.
