### ISSUE TITLE
Short description has "Read More" link

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3026]
Steps to reproduce:
1. Load details page for an add-on with short description i.e. https://addons-dev.allizom.org/en-US/firefox/addon/adblock-edge/

Expected results:
No "Reed More" link.

Actual results:
"Read More" link is present even if the description is 1 row long.

Notes/Issues:
Verified on FF55(Win 7, Android 7.2.1). Issue is reproducing on both dev and stage.
Screenshot for this issue:
![2017-08-30_1311](https://user-images.githubusercontent.com/15685960/29867630-d45accd6-8d84-11e7-809c-43990ffa925a.png)

Could be related to #3017

**Comment by muffinresearch** [comment]
@ValentinaPC I don't see this any more on -dev:

<img width="1102" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/29929213-d277386c-8e62-11e7-9ae5-e1294cf5cb98.png">

**Comment by ValentinaPC** [comment]
Seems like it is happening only if an add-on details page that has a short description is loaded after an add-on details page with long description.
Might be related to #3017 or might be caching?
Please see video:
![rm](https://user-images.githubusercontent.com/15685960/29929493-517efa76-8e74-11e7-8a38-5b55f0f5471f.gif)

**Comment by kumar303** [comment]
Yep, I can reproduce it too:

* Go to https://addons-dev.allizom.org/
* Search for 'ad block edge'
* Pick Image Block from the search suggestions
* Search again for 'ad block edge'
* Pick Ad Block Edge from the search suggestions

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1)
Postfix video:
![readmore](https://user-images.githubusercontent.com/15685960/30024711-c0cab300-917d-11e7-9ab1-f7c8d6cc3441.gif)
