### ISSUE TITLE
Search button title is not clear

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3028]
Translators [do not really understand the purpose/meaning of the title of the (hidden) search `button`](https://github.com/mozilla/addons-frontend/commit/9fb119bf608a649d0ecad0c5de6d0e8401327918). It was not translated before, that is why it has only been revealed recently.

~~I propose to update it from `Enter` to `Search`.~~

I propose to remove this `title` attribute, the button text should be enough.

**Comment by yfdyh000** [comment]
I translated it to "Press Enter key to search", which is not correct?

**Comment by willdurand** [comment]
Unfortunately, it is not exactly that.

Removing this `title` attribute would make sense actually.

**Comment by vcarciu** [comment]
Please add some steps to reproduce or mark this as "qa:not needed"

**Comment by willdurand** [comment]
@vcarciu sorry, marked as "qa: not needed" just now
