### ISSUE TITLE
Autocomplete files when clicking on an already-run search

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3030]
### Describe the problem and steps to reproduce it:
If you type a search term into the search box, let the results load, click away, and then focus the search again, it will run the autocomplete search a second time despite having local results. This creates an unneeded network request and also feels a bit too frantic.

### What happened?
The autocomplete action dispatched again despite the filters all being the same.

### What did you expect to happen?
The existing results are simply loaded/shown again because the filters haven't changed.

### Screenshot
![2017-08-30 15 49 45](https://user-images.githubusercontent.com/90871/29878712-288c5be2-8d9b-11e7-8cc6-d0e5ab9a0f6d.gif)

**Comment by willdurand** [comment]
So, what happens here is that when you loose `focus`, [`onSuggestionsClearRequested`](https://github.com/moroshko/react-autosuggest#onsuggestionsclearrequested-required-unless-alwaysrendersuggestionstrue) is called. It fires the `AUTOCOMPLETE_CANCELLED` action, which resets the state (`suggestions = []`) as indicated in the documentation of the `onSuggestionsClearRequested` method. That is why it needs to fetch `suggestions` again.

It seems not resetting the `suggestions` solves the issue...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1).
Postfix video:
![refil](https://user-images.githubusercontent.com/15685960/30265695-95badbaa-96e5-11e7-8770-59581b43f4fd.gif)
