### ISSUE TITLE
Autocomplete `fetchAutocompleteResults` saga should be cancelled on AUTOCOMPLETE_CANCELLED

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3031]
When the action `AUTOCOMPLETE_CANCELLED` is fired, it should not only reset the `autocomplete` state but also cancel the saga to prevent the state to update after (with new loaded suggestions).

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by willdurand** [comment]
@ValentinaPC sorry but what does STR mean?

No regression should be observed on the search autocompletion. It should still be possible to select suggested add-ons multiple times, with different search terms.

**Comment by ValentinaPC** [comment]
@willdurand : "Steps to reproduce" for QA testing.

**Comment by tofumatt** [comment]
I think for this particular issue (as the issue itself is just about the saga code) it can be marked as QA: not needed 😄
