### ISSUE TITLE
Clicking on an autocomplet result clears the search input

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3032]
### Describe the problem and steps to reproduce it:
After autocomplete suggestions are loaded, if one is clicked the search input is cleared, which I don't expect. It's nice to keep it around (it gives context to what you searched for) and that isn't the case when browsing through the site with a "normal" search. Leaving it there after #3030 is fixed would also let a user click through to multiple autocomplete results right from an addon detail page without loading new suggestions.

### What happened?
The search term is cleared from the input.

### What did you expect to happen?
The search term remained.

### Screenshot
![2017-08-30 15 53 32](https://user-images.githubusercontent.com/90871/29878951-b01f39f8-8d9b-11e7-8e7e-770b5d46c9c2.gif)

**Comment by willdurand** [comment]
That was intentional because I thought either you trigger the search because suggestions are not helpful or you found what you were looking for and only want to quickly get to it.

Of course, leaving the search query would also make sense, as you said, to give context.
