### ISSUE TITLE
Add app switcher for Firefox/Android

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3035]
### Describe the problem and steps to reproduce it:
There should be a way to switch any page between `clientApp`s. See: https://github.com/mozilla/addons-frontend/pull/2995#discussion_r135637960

This could be integrated into the search filters, but it might be nice to switch between client apps anywhere on the page, in case you arrive on an Android page but mean to search using Firefox.

**Comment by kumar303** [comment]
Do we need to add this for Q3? It seems like a nice feature but we only have a month left 😬

**Comment by tofumatt** [comment]
Probably not then.

**Comment by muffinresearch** [comment]
Another way to deal with this is pro-actively notifying the user if they're looking at the Android site having followed a link but are actually using a desktop browser. That could also provide a link to the alternative version.

**Comment by tofumatt** [comment]
I think both of those things are useful, yeah. It’s sort of a separate bug though, as I’d want the notice to be dismissible/only on the first page. This switcher could/should be site-wide.

**Comment by muffinresearch** [comment]
> I think both of those things are useful, yeah. It’s sort of a separate bug though, as I’d want the notice to be dismissible/only on the first page. This switcher could/should be site-wide.

As a thought depending on its UX, a nag bar could possible minimize upon dismissal to something that indicates the current clientApp which  could potentially cover both of these cases and at the same time inform the user of how to switch.

**Comment by willdurand** [comment]
This has been fixed. There is a link in the menu.
