### ISSUE TITLE
Add yarn gpg key to the repository instead of fetching it each time

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3037]
Let's fix up the Dockerfile after https://github.com/mozilla/addons-frontend/pull/3033 so that we use a yarn gpg key that has been committed to the `addons-frontend` repo instead of fetching it from the Internet each time. 

We can follow the pattern here: https://github.com/mozilla/addons-server/blob/master/Dockerfile#L6-L13

**Comment by kumar303** [comment]
@willdurand I got this suggestion from jason. Could you take a look at fixing this up?

**Comment by willdurand** [comment]
Just out of curiosity, what's the benefit of versioning the GPG key?

**Comment by muffinresearch** [comment]
> Just out of curiosity, what's the benefit of versioning the GPG key?

It saves depending on an additional network request.

**Comment by kumar303** [comment]
Also, sometimes ops will set up our production machines so that they can only make external requests to a strict set of hosts. I don't think they're doing that for this case but, just in general, fetching external resources introduces attack vectors.

**Comment by willdurand** [comment]
thanks for your replies!
