### ISSUE TITLE
Allow readers to prefer more than 25 per page

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3038]
With desktop Firefox at `addons.mozilla.org` I often find myself with dozens of pages of results. 

Not through laziness – contributory factors include [Improve relevancy of search results · Issue #2661 · mozilla/addons-server](https://github.com/mozilla/addons-server/issues/2661) – I too often feel that I'm _wading_ through page after page after page … 

## Enhancement request

Please allow greater numbers of add-ons per page. 

The UI to the preference should probably be at the head of the list of results, not the foot. 

I would often prefer unlimited (non-paginated) but that's probably a power use edge case. 

A less eyebrow-raising set of visible preferences might be: 

- 25
- 50
- 100

– plus for power users, a hidden option to set any greater number by manually editing the URL. 

Thanks

**Comment by grahamperrin** [comment]
I wasn't aware of (or had completely forgotten) the _View Mobile Site_ switch –sorry! 

Now <https://addons.mozilla.org/firefox/search/?q=wayback+machine> looks good to me.

**Comment by grahamperrin** [comment]
In retrospect, the _looking good_ might have been my lack of familiarity with the new. 

Now for example https://addons.mozilla.org/en-GB/firefox/search/?featured=true&type=extension&sort=name is spread across three pages with no way to make them all in one. 

Very frustrating when I'm trying to rediscover an extension that has disappeared (OT: maybe an issue with Firefox Sync), and when those three pages may be just the starting point. The less pagination, the better. 

Please consider reopening this issue – thanks.

**Comment by kumar303** [comment]
Yes, it seems worth re-opening this so we can consider it along with other feature requests. Thanks.

**Comment by Tanookirby** [comment]
How about add another option to allow infinite scrolling? This could apply to all lists on the site (addons, reviews, versions, etc.). As you near the end of a section, the contents of the next page would added.

**Comment by kumar303** [comment]
> allow infinite scrolling?

Personally, I can't stand these UIs because I have a hard time coming to a stopping point. That's probably just me being a weirdo though.

**Comment by tofumatt** [comment]
Shoot, I thought I responded to this. But yes I too dislike infinite scrolling. It's also an easy way for pages to consume lots of memory on mobile, but worse it means users can never reach the footer. I don't think scrolling to the bottom of the page is a good enough signifier of intent to load more content.

**Comment by muffinresearch** [comment]
Relates to https://github.com/mozilla/addons-frontend/issues/1971 which would make this easier.

**Comment by muffinresearch** [comment]
#1971 has been fixed so you can now specify manually a `page_size` parameter to a search response and the pagination is correctly calculated.

To fix this issue we'd need to expose an option to set a page size that's different to the default in the UI.

**Comment by grahamperrin** [comment]
Thanks, 

https://addons.mozilla.org/search/?type=extension&sort=created&page_size=100

– seems to return fifty results (not one hundred), is fifty a hard limit?
