### ISSUE TITLE
Filter options don't work in any category pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3039]
Steps to reproduce:
1. Load any add-on/theme category i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/
2. Change a filter criteria

Expected results:
Filter criteria is changed. Results are listed accordingly. 

Actual results:
Nothing happens.

Notes/Issues:
Verified on AMO-dev FF55(Win 7, Android 7.2.1).
Video for this issue:
![filter](https://user-images.githubusercontent.com/15685960/29915532-c9ddf768-8e44-11e7-8459-7884b8334117.gif)

Related to #2956

**Comment by tofumatt** [comment]
Odd, I didn't think the sorts should appear here. I'll either remove them or fix this depending on effort involved...

**Comment by tofumatt** [comment]
This is a regression from the addition of `SearchFilters` over `SearchSort`. Looks like we didn't update `enableSearchSort={false}` to `enableSearchFilters={false}`.

We can update the categories to support filters but that's more involved and a separate bug. For now we'll restore the old UX and this bug will go away.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1)
The filter menu was removed from add-ons categories pages.
Postfix screenshot:
![cat1](https://user-images.githubusercontent.com/15685960/29971122-d8c3a9e4-8f2f-11e7-9e25-0b6f52074332.png)
