### ISSUE TITLE
Add search widget to the Category page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3053]
Refs #2956 #3039 #3051

---

The search page has a search widget with filters. We should probably add it to the Category page too since this page reuses the search feature. We might have to disable some filters though (I am thinking about the `addonType` filter for instance).

Both Category and Search (results) pages are similar, we can therefore reuse the same UI.

**Comment by muffinresearch** [comment]
The category page as specced doesn't appear to share much with the search pages.

<img width="794" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30223572-57007556-94c3-11e7-860c-0794b5dc0536.png">

**Comment by muffinresearch** [comment]
@pwalm - it's a bit unclear what the content is supposed to be on this page - could you clarify it. The category page today is more like a search result. See https://addons-dev.allizom.org/en-US/firefox/extensions/appearance/

**Comment by pwalm** [comment]
The content should match the [current AMO category pages](https://addons.mozilla.org/en-US/firefox/extensions/alerts-updates/).

**Comment by muffinresearch** [comment]
Closing this to deal with it in #3086
