### ISSUE TITLE
Featured add-on disappear while hovering over featured section for any Category

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3054]
Steps to reproduce:
1.From https://addons.mozilla.org/en-US/firefox/ , select any category (ie, https://addons.mozilla.org/en-US/firefox/extensions/download-management/)
2.Hover over Featured add-ons section 

Expected results:
The focus will be on the add-on which is hovered, without any issues

Actual results:
While hovering over them, one of the add-ons disappear 

NOTES:
NOT reproducible on Stage or -dev.

Please see video for this issue : 
![philadelphiaexperiment](https://user-images.githubusercontent.com/1583842/29965611-eff27050-8f16-11e7-8f1f-4d1d35a15739.gif)

**Comment by muffinresearch** [comment]
@vcarciu since this affects the current addons-server site would you mind refiling it there?

**Comment by vcarciu** [comment]
@muffinresearch : sure
