### ISSUE TITLE
Remove theme previews

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3056]
Since future web-ext based lightweight themes don't allow preview and install and uninstall is quick and easy I'd like to propose we remove the theme preview feature everywhere.

@jvillalobos are you ok for us to do this sooner rather than later?

**Comment by jvillalobos** [comment]
Yes, I'm okay with doing this. It'll require an announcement in the blog or the forum, so I just need to be pinged when we're ready to ship this.

**Comment by muffinresearch** [comment]
I think this one makes sense to fold into https://github.com/mozilla/addons-frontend/issues/3388

**Comment by rebmullin** [comment]
Hey @muffinresearch

Just digging into this a bit per our discussion and I want to make sure I’m looking in the right place:

![Alt text](https://monosnap.com/image/MC8bNf0e3kE88Sanzu2GP7PpQP5Yka.png)

is this right? I couldn’t find this under addons-frontend however i do see it under the addons-server repo. Assuming this is correct do we need to move this issue over there for tracking? Or let me know if I am missing something : )

**Comment by muffinresearch** [comment]
@rebmullin it's the preview feature on the front end e.g:

<img width="987" alt="spring_garden_serenity_by_madonna_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/39517727-9fee9218-4df8-11e8-89c1-fdd4790611c4.png">

**Comment by rebmullin** [comment]
@muffinresearch  - ahh i see..cool, thank you

**Comment by muffinresearch** [comment]
@rebmullin The preview feature also exists on the disco pane too: if you got to about:addons. I think it makes sense to remove it from there too. @jvillalobos are you ok with that?

<img width="1143" alt="add-ons_manager" src="https://user-images.githubusercontent.com/1514/39539728-5be0f094-4e38-11e8-9cbc-8c66589c03f9.png">

**Comment by muffinresearch** [comment]
If it's easier to split out the disco pane change into a separate issue patch that's fine, we just need to make sure we don't ship a broken disco pane in between.

**Comment by jvillalobos** [comment]
Yes, I agree we should remove it from disco pane too.

**Comment by rebmullin** [comment]
@muffinresearch @jvillalobos  so theme description displays here instead - is this okay? it looks something like this on disco v:
![Alt text](https://monosnap.com/image/jawrwTxCyeUDmTNwmc3ULg5JxQPyQ9.png)

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64 and Android 8.0.
The 'Tap to preview' button is no longer available on a theme details page on the frontend and the hover preview is no longer applied in the discopane:
![image](https://user-images.githubusercontent.com/31961530/42812527-a1becbda-89c6-11e8-97ad-0198bf49fac3.png)

![image](https://user-images.githubusercontent.com/31961530/42812552-aec82740-89c6-11e8-9018-e8e2abf84099.png)

@muffinresearch the preview on hover is still used on the legacy site (see theme details page, lightweight theme reviewer tool). Should it be removed from there too, or the legacy site is out of scope in this regard?
