### ISSUE TITLE
Disco Pane Visual Design Tweaks

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3060]
After discussing with a colleague, we need to make some small changes to the disco pane for Photon:
- Move header and copy to be aligned left.
- Remove video and put a small link below the copy saying "Find out more.", the video will play in a light box.
- Add button saying "Get More Add-ons" at top of page, and use the same button copy at the bottom of the page.
![2017-08-29 16 07 58](https://user-images.githubusercontent.com/6797635/29982175-923784f2-8f05-11e7-9cc2-b223dff6b2fb.jpg)

Mocks are good to go, we just need some genius engineering talent to implement it!

**Comment by pwalm** [comment]
Updated specs!
![screen shot 2017-09-06 at 2 48 30 pm](https://user-images.githubusercontent.com/6797635/30136197-b0f0f480-9312-11e7-8797-08caf3bbd3c6.png)

![screen shot 2017-09-06 at 2 48 39 pm](https://user-images.githubusercontent.com/6797635/30136202-b5ea81ae-9312-11e7-9af2-e4b9ec1f75ce.png)

![screen shot 2017-09-06 at 2 48 48 pm](https://user-images.githubusercontent.com/6797635/30136210-ba2d2fbe-9312-11e7-9663-ea615af8bc18.png)

**Comment by muffinresearch** [comment]
Closing this since it has been superceded by https://github.com/orgs/mozilla/projects/21
