### ISSUE TITLE
[layout issue] Unapproved addon should give 'Not Found' error

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#3061]
Navigate to https://addons.mozilla.org/en-US/firefox/addon/share-backported/

### What happened?
Gives "You do not have permission to perform this action." error
(Its an unapproved addon [under review])

### What did you expect to happen?
Addon detail page should be visible as in legacy website.
[update] As per new frontend specifications this should throw 404 error.

### Anything else we should know?
**Mobile website view**
<img width="1280" alt="screen shot 2017-09-03 at 12 42 14 pm" src="https://user-images.githubusercontent.com/5318732/30001253-ecc1c1c0-90a5-11e7-8c5b-09ae9a3e6c83.png">

**Legacy view**
<img width="1278" alt="screen shot 2017-09-03 at 12 42 28 pm" src="https://user-images.githubusercontent.com/5318732/30001255-0200694c-90a6-11e7-8c9c-8530f96e935c.png">

Also layout shows loading icons, which shouldn't be visible in any case other than loading time.

**Comment by jvillalobos** [comment]
Per the specification for the new front-end, the expected behavior is to show a Not Found page, rather than a permissions error. So, this is still a valid issue, but for different reasons.

**Comment by muffinresearch** [comment]
The empty page looks bad so marking this MVP

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF55(Win 7).
A 404 page is displayed for unapproved add-ons.
@muffinresearch For a second add-on details page wants to be loaded, are we ok with that?
Please see video:
![404](https://user-images.githubusercontent.com/15685960/30366031-65d58848-9872-11e7-8bf3-65475166c7ad.gif)

**Comment by kumar303** [comment]
> For a second add-on details page wants to be loaded, are we ok with that?

Yeah, that's fine. It's an indication that the request for the add-on is still loading. Technically there is a server vs. client bug in how the component is detecting whether data has been fetched or not but it's not worth fixing right now.

**Comment by ValentinaPC** [comment]
Marking this verified-fixed.
