### ISSUE TITLE
Search box bottom corners are not rounded after deleting searchterm

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3064]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/ , mobile view
2.Enter a search text in search box , then delete it

Expected results:
Search box is not affected

Actual results:
Search box bottom corners are not rounded after deleting searchterm

Please see video for this issue : 
![rounded](https://user-images.githubusercontent.com/1583842/30028423-b4fa6614-918d-11e7-80e4-757808b4df48.gif)

**Comment by tofumatt** [comment]
I thought this would be solved by the autocomplete cancel fix, guess not. I'll have a look, thanks!

Matthew Riley MacPherson (sent from mobile)

**Comment by willdurand** [comment]
Ah I think the autocomplete cancel does not change `autocompleteIsOpen` in `SearchForm`.

**Comment by willdurand** [comment]
Updating `isOpen` almost work, but there is still a visual glitch:

![2017-09-04 17 06 02](https://user-images.githubusercontent.com/217628/30031889-7b8953c6-9193-11e7-9e06-93ec79b8e22c.gif)

**Comment by vcarciu** [comment]
Verified as fixed on both mobile and desktop(video only for desktop view, since mobile is working in the same way) : 
![verifsearchcorner](https://user-images.githubusercontent.com/1583842/30169545-5ad266cc-93f5-11e7-8126-2f9a610de5d4.gif)
