### ISSUE TITLE
Start autocomplete search after n chars entered

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3070]
The autocomplete should only start sending requests once there's more than `n` characters because the results for a single char aren't that useful.

In the past typical values for `n` would be 2-3 chars - it'll make sense to make this configurable so it's easily tweaked. Let's start with 2 chars and go from there.

**Comment by hellokarthic** [comment]
Hi @muffinresearch , I would like to work on this bug! :)

**Comment by wagnerand** [comment]
Mentor: @tofumatt

**Comment by abiduzz420** [comment]
@muffinresearch I would like to suggest using lodash to handle API requests made in a second using debounce.

**Comment by willdurand** [comment]
we already have a debounce implementation.

**Comment by abiduzz420** [comment]
Great! @willdurand let's use that. I think that would be better

**Comment by caitmuenster** [comment]
Hey @abiduzz420, it looks like @hellokarthic isn't working on this bug. Do you want to pick it up?

**Comment by abiduzz420** [comment]
Yeah sure @caitmuenster I will need to do bit of groundwork before I finally write the code. I shall share the progress soon.

**Comment by caitmuenster** [comment]
Thanks for the heads up, @abiduzz420! Are you still working on this?

**Comment by abiduzz420** [comment]
I am so sorry @caitmuenster I have not been able to juggle between different works. I would like some body else to take it up. Apologies :(

**Comment by caitmuenster** [comment]
No worries at all, @abiduzz420! I'll unassign you from this for now but you are always welcome to come back and pick it up, or try another good first bug. :)

**Comment by SeanPrashad** [comment]
Hey everyone - I'm coming over from addons-server and would love to pick up this bug as my first for the front-end!

I've done some digging and have found the following code block that looks of interest:

https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/SearchForm/index.js#L139-L156

I'll open up a PR and continue my work from there! ✌🏽

**Comment by kumar303** [comment]
Why do we still need this feature given that we have a [debounce function](https://github.com/mozilla/addons-frontend/blob/01f773d4a156583a35dccfccf939616f5321d752/src/amo/components/SearchForm/index.js#L130)?

**Comment by tofumatt** [comment]
Because search results for single-characters or even two characters are not relevant (it's nigh-impossible to return a good autocomplete suggestion from "t" or "b"). They end up just being extra requests that clutter the UI and reduce the first relevant set of autocomplete results.

It's pretty common for sites not to autocomplete until a few characters.

**Comment by ioanarusiczki** [comment]
The autocomplete is initiated when the third char is typed. 
This issue is verified on AMO dev with FF59 (Win10). 

Here's the new versus the old behavior
![autocomplete after n](https://user-images.githubusercontent.com/33448286/37956986-79b984cc-31b5-11e8-88ff-cc9c3b0fd82d.gif)
