### ISSUE TITLE
Logo is not the new moz://a branding

### ISSUE THREAD

**Issue by aphillipo** [mozilla/addons-frontend#3071]
### Describe the problem and steps to reproduce it:
Logo on Mozilla Addons should reflect the current corporate logo.

### What happened?
The old Mozilla Logo Appears.

### What did you expect to happen?
The new Mozilla Logo Appears.

### Anything else we should know?
Is an SVG okay and I'll send a pull request?  

https://www.mozilla.org/media/img/pebbles/moz-wordmark-dark-reverse.2cbc28bb9895.svg

I will change the background to white and the wext to the blue to match the current header?

I can't see a fallback in the code on Mozilla.org so I assume SVG is enough?

**Comment by tofumatt** [comment]
Hi there,

Yes, a new SVG to replace the old ones would be great if the current one is wrong. Could you attach a screenshot of the issue as it is now just so we're clear on what to look for when QA testing the difference? Thanks!

**Comment by aphillipo** [comment]
Currently:

<img width="982" alt="original-masthead" src="https://user-images.githubusercontent.com/52347/30104896-e55300be-9331-11e7-924e-c47fe2e3f8cc.png">


Suggested change:

<img width="982" alt="suggested-update" src="https://user-images.githubusercontent.com/52347/30104897-e556d6da-9331-11e7-942b-2b01c20f1f6d.png">

We are going with SVG only 🔥

**Comment by ValentinaPC** [comment]
Take a look also at: https://github.com/mozilla/addons-server/issues/4658

**Comment by tofumatt** [comment]
Ah, thanks for the screenshot, sorry for the confusion. This repo is for the new front-end which is currently only the default for mobile users. So this issue should be filed over on addons-server.

Aha, yes, this should be taken care of by the issue @ValentinaPC linked to. Thanks!

**Comment by aphillipo** [comment]
Okay! Sorry for the noise!
