### ISSUE TITLE
There is no way to delete own review

### ISSUE THREAD

**Issue by atiqueahmedziad** [mozilla/addons-frontend#3075]
### Describe the problem and steps to reproduce it:
1. To go AMO mobile website and visit any add-ons details page. ( Example- https://addons.mozilla.org/en-US/firefox/addon/real-madrid-blue/ )
2. Write a review
### What happened?
There is option for the review owner to delete his/her review
### What did you expect to happen?
There should be option for the review owner to delete his/her review like we have in the classic desktop website.
### Anything else we should know?
The following is my own written review. There is no option to delete it.
![screenshot_2017-09-07-21-47-03-962_org mozilla fennec_aurora](https://user-images.githubusercontent.com/8364578/30172767-88d81a0e-9417-11e7-8c85-d5726972dc51.png)

**Comment by kumar303** [comment]
I split off the edit part into its own issue since that one is easier https://github.com/mozilla/addons-frontend/issues/3180

**Comment by kumar303** [comment]
I'm nominating this for MVP removal because it is rare to delete a review and editing (https://github.com/mozilla/addons-frontend/issues/3180) would suffice in a dire circumstance. We should definitely add this feature but it can be done as a follow-up.

**Comment by bobsilverberg** [comment]
@jvillalobos Should a user be able to delete a review that has had a reply posted to it? I don't see why not, but I figured it was worth checking. Are there any other things we need to consider about deleting reviews?

**Comment by jvillalobos** [comment]
> Should a user be able to delete a review that has had a reply posted to it?

Yes, it should be possible. And the reply should be deleted along with it.

**Comment by bobsilverberg** [comment]
> And the reply should be deleted along with it.

@eviljeff Does the DELETE API take care of this?

**Comment by bobsilverberg** [comment]
@diox When we delete a review via the API, do any replies to that review get deleted as well?

**Comment by bobsilverberg** [comment]
@jvillalobos Should a user be able to delete their reply to a review?

**Comment by jvillalobos** [comment]
> Should a user be able to delete their reply to a review?

Yes.
