### ISSUE TITLE
Make tests more predictable by removing setState callbacks

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3077]
I don't think our tests should rely on `setState()` being synchronous as it's [unclear](https://github.com/airbnb/enzyme/issues/509#issuecomment-237362893) that this will always work in enzyme as its libraries evolve and get upgraded.

We have a few problems in the test suite related to this but first let's try not to rely on `setState` callbacks.

Here are two places that (hopefully) can be fixed with different approaches:

* https://github.com/mozilla/addons-frontend/pull/3058#pullrequestreview-60648776
* https://github.com/mozilla/addons-frontend/pull/3057#pullrequestreview-60631026

**Comment by willdurand** [comment]
should be fixed now.
