### ISSUE TITLE
Quickly typing a search term does not autocomplete it

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3078]
### Describe the problem and steps to reproduce it:

Quickly type a word in the search box

### What happened?

The last few characters you type will not be included in the search term. You can verify this in the network panel -- inspect the API request made to the `autocomplete` endpoint. 

For example, if you type "ad block" quickly, the search term will just be "a". If you type a bit slower, you may get more of the word but probably not the whole thing.

### What did you expect to happen?

Autocompletion should always search for the full word you type.

### Anything else we should know?

This is a regression from fixing https://github.com/mozilla/addons-frontend/issues/3064 . We chatted about it in IRC and I think `handleSuggestionsFetchRequested` can immediately call `setState` without a debounce to change its class name. The call to `dispatch(autocompleteStart())` should still be debounced.

**Comment by vcarciu** [comment]
I tested this by quickly typing "download" search term . You can see the results below and it looks like there are three different url requests for this action : 
![rapidtyping](https://user-images.githubusercontent.com/1583842/30326518-70dce0a2-97d1-11e7-9489-0add538e46ce.gif)

Please let me know if this is ok

**Comment by willdurand** [comment]
This looks good to me because the last search term is the one that you typed ("download").

**Comment by vcarciu** [comment]
@willdurand , but the other two actions are not redundant?

**Comment by willdurand** [comment]
@vcarciu I dont think so. It is because autocompletion is enabled on every letter but we use debouncing to avoid too many API calls. It is normal to have a few calls since we debounce at 200ms. The most important thing here is to have the correct search term in the last API call.

**Comment by vcarciu** [comment]
@willdurand : thanks for explanation ! Marking bug as verified.
