### ISSUE TITLE
Add compatibility filter to collection views

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3080]
After some discussion in https://github.com/mozilla/addons-server/issues/6279, I think it would be a good idea to hide incompatible add-ons by default in collection views, but still leave the option to see the full collection. I'm thinking just a checkbox labeled `Hide incompatible add-ons`.

**Comment by tofumatt** [comment]
That box will be checked by default which to me is a bit of a weird UX. "Show incompatible add-ons" as a checkbox seems better, but again: why ever show them? I recall @pwalm saying ages ago search results just shouldn't contain incompatible add-ons... I guess maybe we could add a query param that showed them for expert users, but what's the use-case for showing incompatible add-ons in search results? What is a user to do with them?

**Comment by jvillalobos** [comment]
There are a number of popular collections around that are either all-legacy or mostly legacy. I think some people will be confused if they find them empty knowing that they should have something. We still want to give the option to show incompatible add-ons because some people look for old content to try to get in touch with the developer, or find code info or files so they can fork it.

**Comment by tofumatt** [comment]
Fair enough. I suppose a nice feature (for the future) for all-legacy collections would be to detect they're all legacy and tick the "show incompat" checkbox by default in the UI and return all add-ons.

**Comment by grahamperrin** [comment]
As both of these are becoming familiar – 

![yellow](https://user-images.githubusercontent.com/192271/30243291-568c1590-959e-11e7-8cb5-cf8a99801bd9.png) 

![green](https://user-images.githubusercontent.com/192271/30243292-5691b1e4-959e-11e7-8378-7aa4fb68545c.png)

– maybe a filtering UI could make use of them (or something like them; tone down the SHOUTING, and so on). 

## Early thoughts

If each one was a switch, then switching both on would show a full collection. Switch off the green to show legacy only. Switch off the yellow to show Firefox 57+ compatible only. 

The switching interface might confuse users. An alternative: 

![yellow](https://user-images.githubusercontent.com/192271/30243291-568c1590-959e-11e7-8cb5-cf8a99801bd9.png)  | ![green](https://user-images.githubusercontent.com/192271/30243292-5691b1e4-959e-11e7-8378-7aa4fb68545c.png)

– the two, alongside each other, with a three-way switch above or below. Something like the one at https://es.123rf.com/photo_18316187_tres-posiciones-interruptor-deslizante-con-opciones-para-pasado-presente-y-futuro.html but ignore the wording there. Basically: the midway position to show both legacy and future-oriented add-ons.

**Comment by jvillalobos** [comment]
Hiding incompatible isn't only about the legacy / WE distinction, so those labels wouldn't apply in this case. It's also a bit too flashy for what will be a very low-key feature.

**Comment by pwalm** [comment]
We could add some copy along the lines of "5 incompatible extensions are hidden. Click to show them" and then on click, those add-ons would appear at the bottom of the list with greyed out install buttons.

**Comment by pwalm** [comment]
Like dis:
![screen shot 2017-09-12 at 2 31 02 pm](https://user-images.githubusercontent.com/6797635/30349300-685517e2-97c7-11e7-8acd-e61d7bbf01c2.jpg)

**Comment by grahamperrin** [comment]
> …  too flashy …

👍 

> … at the bottom of the list …

Only if the list is to be sorted by compatibility; https://github.com/mozilla/addons-server/issues/6279 was originally _Filter and/or sort by compatibility within a collection_

In most cases the list will be sorted by some other criterion or criteria. Don't break that order by adding without sorting.

**Comment by willdurand** [comment]
@jvillalobos is there still any need for this or can we close this issue?

**Comment by jvillalobos** [comment]
No
