### ISSUE TITLE
Update Category Page

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3086]
Category pages currently look like:

![screen shot 2017-09-08 at 18 32 42](https://user-images.githubusercontent.com/1514/30223783-32c836a0-94c4-11e7-80aa-f81d81e76ee8.png)

But the mocks have:

<img width="794" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30223768-29c94328-94c4-11e7-8726-0c833e5cab3b.png">

**Comment by muffinresearch** [comment]
Based on the mock it's unclear what a lot of this data should be. @pwalm do we know what the shelves should be? I would have thought the current solution of using a search is probably more accurate for representing the content of a category in which case it would make sense to close this and action https://github.com/mozilla/addons-frontend/issues/3053 instead

**Comment by tofumatt** [comment]
Ah, shoot, those specs are new.

**Comment by pwalm** [comment]
I'm thinking the shelves will have similar data to what category pages have now:
- Featured
- Most Popular
- Top Rated
- Recently Added

Not sure what a "search widget" is, though? What would that add to the page?

**Comment by muffinresearch** [comment]
Following a review with @pwalm this should not be a search results page but instead should follow the data we have on the existing category pages on the legacy frontend:

<img width="1082" alt="alerts___updates____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30423904-379931c6-993c-11e7-845d-22e02ade457d.png">

Recently added was one that was OK to drop: From the scope doc "Top add-on lists: Featured, Top Rated, Most Popular".

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
All categories pages are changed and using the new form.
Postfix screenshots:
![addons](https://user-images.githubusercontent.com/15685960/31280653-ba9fd64e-aab5-11e7-86b1-5f0bdea01ffa.png)
![themes](https://user-images.githubusercontent.com/15685960/31280658-bd957d22-aab5-11e7-8a4b-36215a3bd32d.png)

Issues: https://github.com/mozilla/addons-frontend/issues/1952 and https://github.com/mozilla/addons-frontend/issues/3169 is happening in each category.
