### ISSUE TITLE
four of five stars is not fantastic

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3090]
https://github.com/mozilla/addons-frontend/pull/1368 (2016-11-10) fixed [Adjust the review text prompt based on star selection · Issue #1366 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/1366), but when I rate four stars the dialogue uses the word _fantastic_.

**Comment by muffinresearch** [comment]
@grahamperrin What do you think the copy should say? I can't promise we'll update it since this gets into something that's quite subjective, 4/5 seems pretty good to me.

**Comment by grahamperrin** [comment]
For three stars we have: 

> **Write a review**
> Tell the world about this extension.

– and the number of stars is hidden. 

For five: 

> **Write a review**
> Tell the world why you think this extension is fantastic!

– and the number of stars is hidden. 

For four, maybe: 

> **Write a review**
> Tell the world why you rated four out of five. 

In all cases I think that it will be better to show (not hide) the number of stars whilst inviting the reviewer to write. Show the stars, and just one line at the head of the dialogue: 

> **Write a review**

– with a change of wording of the submission line, from: 

> **SUBMIT REVIEW**

– to: 

> **Submit for publication**

**Comment by muffinresearch** [comment]
@devaneymoz do you have thoughts on what we should be aiming for here?

**Comment by pwalm** [comment]
Rating scale guidance:
<img width="255" alt="screen shot 2018-05-11 at 11 53 18 am" src="https://user-images.githubusercontent.com/6797635/42589609-6bad6922-84f6-11e8-91e2-2936499f8683.png">

**Comment by grahamperrin** [comment]
I'd define two stars as bad.

**Comment by kumar303** [comment]
We are no longer displaying a prompt when a user enters or edits their star rating so this issue can be closed.

As of https://github.com/mozilla/addons-frontend/pull/6231 we are showing a different set of screens for submitting reviews. That PR has a screencast you can watch to see it.
