### ISSUE TITLE
"More highly rated extensions"/"More popular extensions" links load an empty page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3096]
Steps to reproduce:
1. Load Extensions homepage https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Click on "More highly rated extensions"/"More popular extensions"

Expected results:
Extensions sorted accordingly are displayed.

Actual results:
An empty page with the message "Enter a search term and try again." is displayed.

Notes/Issues:
- only reproducing on -dev
- reproducing for themes also

Verified on AMO-dev FF55(Win 7).
Video for this issue:
![issue](https://user-images.githubusercontent.com/15685960/30326465-4d48e424-97d1-11e7-8075-528f7ddd737a.gif)

**Comment by tofumatt** [comment]
This is a regression from 045c9e1a03688f126f5b941bd2f5e25520c49527. For now I'll revert that, looks like we need to have separate pages for these featured pages or something... 😢

**Comment by ValentinaPC** [comment]
Verified as fixed on AMo-dev FF55(Win 7, Android 7.2.1)
Postfix video:
![more](https://user-images.githubusercontent.com/15685960/30369381-f886fb36-987c-11e7-9e00-93e5051bd064.gif)
