### ISSUE TITLE
Review modal can be broken

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3097]
Steps to reproduce:
1. Go to details page for an add-on and try to write a review i.e. https://addons-dev.allizom.org/en-US/firefox/addon/imacros-for-firefox/
2. While in the review modal try to resize the text section

Expected results:
The review modal cannot be resized.

Actual results:
The text section can be resized.

Notes/Issues:
- reviews can be submitted;
Verified on AMO-dev FF55(Win 7).
Before #2687 landing, this could not make any visual damage.
Video fro this issue:
![modal](https://user-images.githubusercontent.com/15685960/30326858-93a9ace0-97d2-11e7-875d-87baf4cfd708.gif)

**Comment by tofumatt** [comment]
I would say there's no need to allow this to be resized, so that'd be the easy fix.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix video:
![modal](https://user-images.githubusercontent.com/15685960/30368186-1ae77588-9879-11e7-8713-5f2ddde936ea.gif)
