### ISSUE TITLE
Pagination doesn't match the mocks

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3100]
The mocks have a new pagination: 

<img width="621" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30333663-5b19bda4-97d5-11e7-907e-f1bc37fa041a.png">

Site currently has: 

<img width="1517" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30333594-2dac1196-97d5-11e7-8267-28bbbbf8ab4d.png">

This could be a post-release fix-up or something to focus on at the end if we have time.

**Comment by tsl143** [comment]
Can I pick this one?

**Comment by tofumatt** [comment]
Yes, feel free to work on this. Let us know if you are and we'll mark it `contrib:assigned`, thanks.

**Comment by tofumatt** [comment]
The touch targets here I'm suspicious of actually so this will have different versions for desktop/mobile. Eg. mobile should still have large(r) buttons, maybe fewer pages with more padding.

**Comment by tsl143** [comment]
Great, I am picking this up.

**Comment by tsl143** [comment]
Great, I am picking this up.

**Comment by tofumatt** [comment]
Hi @tsl143, are you still working on this one or are you focusing on other issues? No worries either way, but I'll unassign this if you're busy with other stuff–I know you've been closing a tonne of issues lately so no worries if you don't have time for this one! 😄

**Comment by tsl143** [comment]
Hi @tofumatt , thanks :)
I started on this, but got occupied with something, I may not be working on this for now. Please feel free to unassign this.

**Comment by willdurand** [comment]
Unassigned you @tsl143, thanks for all your contributions btw!

**Comment by willdurand** [comment]
I need this for the user profile page.

**Comment by willdurand** [comment]
For QA, the new paginator still looks a bit different (please see #5336) but here are the things to test:

- make sure there are more pages displayed by default
- make sure that links work
- on small screens, the paginator should look different (i.e. only prev/next buttons as before)

**Comment by vcarciu** [comment]
Verified as fixed : 
![pagination](https://user-images.githubusercontent.com/1583842/41716471-35a7e10a-755f-11e8-80ba-96d86dbaa627.gif)

Also verified for small screens and everything works as expected.
