### ISSUE TITLE
Default text from search field is cut for non-en locales

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3109]
Steps to reproduce:
1. Load AMO homepage on your device
2. Change the language to "French" i.e. https://addons-dev.allizom.org/fr/firefox/ 
3. Observe search field

Expected results:
There are no display or layout issues.

Actual results:
Default text from search field is cut.

Notes/Issues:
Other examples:
- https://addons-dev.allizom.org/el/firefox/
- https://addons-dev.allizom.org/es/firefox/
- https://addons-dev.allizom.org/hu/firefox/
- https://addons-dev.allizom.org/it/firefox/
- etc.

Verified on AMO-dev FF55(Android 7.2.1). Also reproducing on -stage.
Screenshot for this issue:
![2017-09-13_1131](https://user-images.githubusercontent.com/15685960/30367544-314feeb0-9877-11e7-99af-8b68b595ed8a.png)

**Comment by tsl143** [comment]
@muffinresearch , what should be ideal behavior, text-ellipsis or increase width of search box?

**Comment by tofumatt** [comment]
We should have an ellipsis. We can’t make the box wider on such narrow screens. Hopefully in most locales “search” will be the first word and between the placement, magnifying glass, visible words, and style it will be very apparent as a search box.

**Comment by ValentinaPC** [comment]
We could do this, like you guys did it in Dev Hub?
Please see screenshot:
![2017-09-13_1700](https://user-images.githubusercontent.com/15685960/30381488-3c76e018-98a5-11e7-9433-2a8bdf786332.png)

**Comment by tofumatt** [comment]
Yes, that's what we'd want.

**Comment by tsl143** [comment]
I will give a PR soon for this

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Android 7.2.1).
Postfix screenshots:
![2017-09-14_0830](https://user-images.githubusercontent.com/15685960/30413487-f32e5102-9926-11e7-8a0e-93e445d0d3ba.png)
