### ISSUE TITLE
Get add-on installation status in the store

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#311]
We'll want to drive the install button state from the store. Since there can be more than one install happening at a time we'll likely want to add another reducer for this and key off of the add-on slug or guid (slug isn't needed but it is how the add-ons are keyed so maybe worth being consistent). We'll want something like:

```js
{
  installations: {
    'my-addon': {
      slug: 'my-addon',
      guid: 'my-addon@my-domain.com',
      url: 'https://addons-cdn.com/download/my-addon.xpi',
      state: 'uninstalled', // 'downloading', 'installing', 'uninstalling', 'cancelled', 'error', 'installed', 'unknown'
      progess: 0, // Percentage, between 0 and 1.
    },
  }
}
```

We'll need to check the status of each fetched add-on when the page loads, hopefully that happens quickly. I guess we could serialize that last accessed status to a cookie that the server could use to initialize the buttons. I added the `unknown` state to show that we haven't checked yet.

**Comment by muffinresearch** [comment]
`cancelled` is an addon state we probably won't need to deal with since cancellation coming from the browser apis should mean we need to query the current state of the addon and reflect that back.
