### ISSUE TITLE
Request Accessibility review

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3111]
Would be good to get a review of the general accessibilty on AMO like we did for the discovery pane.

~~This can happen early Q4.~~

A few ideas of things we'd want checked out (but not limited to):

* Keyboard accessibility.
* Screenreader accessibility.
* Colour checks e.g. contrast.

**Comment by willdurand** [comment]
Let's make it happen!

**Comment by willdurand** [comment]
Hi @MarcoZehe, can you get in touch to make this happen?

**Comment by MarcoZehe** [comment]
@willdurand Hi! Thanks for reaching out! I can help with screen reader accessibility and some keyboard accessibility, but not contrast, or checking of focus visibility at all times. :) Please let me know where the material is you would like me to check out.

**Comment by willdurand** [comment]
Hi @MarcoZehe! That would be awesome if we could get some sort of report (screen reader accessibility and some keyboard accessibility) for the following pages:

- the Homepage: https://addons.mozilla.org/
- an add-on detail page: https://addons.mozilla.org/en-US/firefox/addon/facebook-container/

Those pages are the most important ones. I'd personally be interested in things to improve and how we can verify that changes go in the right direction. I mainly know about the WAVE tool (and also `lynx`).

**Comment by bobsilverberg** [comment]
@willdurand I think perhaps we should not allow this to be closed, as I do believe this is something we'd like to get done. What do you think?
