### ISSUE TITLE
Update sign-in button link to use photon colours

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3112]
Currently looks like:

<img width="245" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30371543-d741cf46-9872-11e7-9a42-e027b02e4513.png">

Mocks have:

<img width="504" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30371727-5ef6a7d6-9873-11e7-8676-90af51e1bca1.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7, Android 7.2.1)
Postfix screenshot:
![color](https://user-images.githubusercontent.com/15685960/30423106-877fb562-994a-11e7-9eed-8911da050fbd.png)
