### ISSUE TITLE
Update category colours to use photon colours

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3114]
Currently we have:

<img width="1377" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30372360-802379dc-9875-11e7-974b-8c881d0f4cc5.png">

The mocks have:
<img width="645" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30373217-77cf7c2e-9878-11e7-839a-5b1f952ba4b1.png">

**Comment by ValentinaPC** [comment]
@muffinresearch This is only for Extensions categories?
