### ISSUE TITLE
Don't set the user menu label to username if there is a display name available

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3118]
Steps to reproduce:
1.Login to amo-dev , mobile view
2.Be sure that your account have both username and display name filled

Expected results:
Display name should be used as user menu label 

Actual results:
Username is used

NOTES:
If username is deleted from account settings, then the label will be set to "anonymous ... " even if we have a display name 
Reproducible on Android devices too

Please see video for this issue : 
![username](https://user-images.githubusercontent.com/1583842/30383252-f7c5b124-98a9-11e7-846b-c0f1833ecc12.gif)

**Comment by willdurand** [comment]
This is interesting. I only saw "username" mentioned in the mock-ups and issue description. Yet, it would probably make sense to use the display name if available. ping @muffinresearch

**Comment by tofumatt** [comment]
Yeah we totally should use display name, that’s what it’s for :-)

**Comment by vcarciu** [comment]
Verified as fixed : 
![displayname](https://user-images.githubusercontent.com/1583842/30482609-75b96458-9a2c-11e7-94db-35a723a550a5.gif)
