### ISSUE TITLE
Use exclusion filter to retrieve other add-ons by authors

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3119]
We currently rely on a small ~~hack~~ alternative way of fetching the list of add-ons by any of the authors of a given add-on because the API does not allow to exclude add-ons yet. We fetch one more add-on than we need and filter this list to exclude the add-on we don't want.

https://github.com/mozilla/addons-frontend/blob/799872e3cac357a039957832b6a86357327fa45f/src/amo/sagas/addonsByAuthors.js#L27-L29

Once https://github.com/mozilla/addons-server/issues/6376 is fixed, we will be able to pass a new query parameter to the API and avoid this hack.

**Comment by muffinresearch** [comment]
The upstream issue was fixed in https://github.com/mozilla/addons-server/pull/6414

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF57 (Win10 and Android 7.0)

I've looked at several extension/theme details pages and compared the listed add-ons with the suggestions presented in 'More extensions by developer'/ 'More themes by artist' sections. In all cases, the listed add-on was not included among the other suggestions.

![image](https://user-images.githubusercontent.com/31961530/33204202-75bef9fc-d10b-11e7-8b01-d0dbd8efb80e.png)
![image](https://user-images.githubusercontent.com/31961530/33204314-cee5388e-d10b-11e7-9414-f21428845c14.png)
