### ISSUE TITLE
User menu drop down should be displayed over search suggestions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3120]
Steps to reproduce:
1.Login to AMO Stage , mobile view and enter a search term in search box
2.Wait for suggestions to appear
3.Hover over user menu from top right corner

Expected results:
User menu drop down should be displayed over search suggestions

Actual results:
User menu drop down menu cannot be entirely seen because of search suggestions

Please see video for this issue : 
![dropdownoverlap](https://user-images.githubusercontent.com/1583842/30385069-ad4b7eb2-98ae-11e7-8746-0ce5c4407a0c.gif)

**Comment by willdurand** [comment]
Mmmh, it looks like a `z-index` issue.

**Comment by vcarciu** [comment]
Verified as fixed : 
![overlapping](https://user-images.githubusercontent.com/1583842/30486682-f86cf52e-9a39-11e7-9224-51c9558af7cd.gif)
