### ISSUE TITLE
Cannot close the search suggestions after overlapping with user menu drop down on Android

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3122]
Steps to reproduce:
1.Login to AMO Stage on your Android device and enter a search term in search box
2.Wait for suggestions to appear
3.Switch to landscape view
4.In scroll down a bit like you want to see more of search suggestion(they are covered by keyboard)
5.Press on user menu in order to open the drop down
6.Switch back to portrait view and try to close search suggestions by tapping somewhere outside of its area

Expected results:
Search suggestions are closed without issues

Actual results:
Search suggestions cannot be closed

NOTES:
Please note that without Step 4, I was not able to reproduce the bug and you have to try few times until reproducible

Please see video for this bug : 
![suggestionsnonresponsive](https://user-images.githubusercontent.com/1583842/30385604-5b33fe72-98b0-11e7-8492-889049f06880.gif)

**Comment by willdurand** [comment]
Hi @vcarciu, could you please give me more details? I have tried to reproduce this issue on a real device with latest Firefox browser but could not reproduce it 😢 

Note: I used https://addons-dev.allizom.org/, which got a few fixes related to the menu and autocomplete feature. Could you please let me know if it is still an issue in dev for example?

**Comment by vcarciu** [comment]
@willdurand :  
It looks like https://github.com/mozilla/addons-frontend/issues/3120 fixed this too, thanks.
