### ISSUE TITLE
Theme description is covered by "More Themes by author_name" section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3123]
Steps to reproduce:
1. Load a details page for a theme with description i.e. https://addons-dev.allizom.org/en-US/firefox/addon/firefox-saucers/

Expected results:
There are no display or layout issues.

Actual results:
Description is covered by "More Themes by author_name" section.

Notes/Issues:
Verified on AMO-dev FF55(Win 7). Not reproducing on device.
Regression from #2767
Video for this issue:
![hide](https://user-images.githubusercontent.com/15685960/30412999-477e37f2-9924-11e7-8692-f6bac979877b.gif)

**Comment by willdurand** [comment]
Oh, I think something is wrong with the CSS grid 😢

**Comment by ValentinaPC** [comment]
The important thing is to catch this things, I am no doubt you guys will fix it asap :P

**Comment by kumar303** [comment]
I don't see any layout issues in FF57. Can you attach a screenshot?

**Comment by willdurand** [comment]
@kumar303 the other addons card hides the "About this persona" card.

**Comment by kumar303** [comment]
Oh, ha, it happened so fast I didn't notice. I see it now.

**Comment by vcarciu** [comment]
Verified as fixed : 
![fixformorebyauthor](https://user-images.githubusercontent.com/1583842/30548381-acf0dad0-9c9a-11e7-9d89-e955792c3481.png)
