### ISSUE TITLE
Show LoadingText in AddonMoreInfo Card on details page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3127]
Right now during loading states the "More information" card is hidden, but it *should* render with LoadingText content. I was adding something (the DB ID, #2750) to this card and realised it was an easy addition so I folded it into #3126, filing here for posterity/QA.

**Comment by vcarciu** [comment]
Verified as fixed : 
![loadinginfo](https://user-images.githubusercontent.com/1583842/30485820-4194969c-9a37-11e7-9b7b-a4dbb695dbbf.gif)
