### ISSUE TITLE
"More extensions by author" card is not loaded on the server

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3130]
I just noticed that the "More extensions by [author]" content is only loaded client-side, after the content has been sent from the server.

We should be loading this server-side and not seeing it load in after the page has been sent over the wire.

### Screenshot
![2017-09-14 01 30 22](https://user-images.githubusercontent.com/90871/30407211-d246a27e-98ee-11e7-8853-7a72142cc912.gif)

**Comment by willdurand** [comment]
Indeed, but how is this possible actually? We are not waiting for the saga to finish in SSR? Oh. No. We need an add-on because the addon type is required. That's the problem I think..

**Comment by willdurand** [comment]
The way data fetching and sagas work on the server makes it nearly impossible to fix this issue, so this is a wontfix.
