### ISSUE TITLE
Written review: escape from the 'Submit for publication' dialogue

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3131]
From today's <https://github.com/mozilla/addons-frontend/issues/3090#issuecomment-329348748>: 

> Submit for publication

It should be possible to: 

1. <kbd>Esc</kbd> from that dialogue; **and**
2. know without doubt that the star rating, which preceded the invitation to write, is unaffected by the escape. 

True: the stars _are_ visible after declining to write, but there's sense of uncertainty after an unfinished routine. 

`#thinkbubbles` maybe something other than a modal dialogue will be better.

**Comment by kumar303** [comment]
Thanks for filing the issue. This would definitely be worth fixing but the current plan is to completely replace the modal window you are referring to. See https://github.com/mozilla/addons-frontend/issues/3636 . The new form will have a cancel button which should be more intuitive.
