### ISSUE TITLE
"View Mobile Site" unusable link in Reviewer Tools

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3133]
Steps to reproduce:
1. Load Reviewer Tools homepage https://addons-dev.allizom.org/en-US/editors/
2. Observe page footer

Expected results:
There is no "View Mobile Site" link.

Actual results:
There is a "View Mobile Site" unusable link.

Notes/Issues:
- this is a suggestion as per Developer Hub page
Verified on AMO-stage FF55(Win 7).
Screenshot:
![2017-09-14_1200](https://user-images.githubusercontent.com/15685960/30421105-67e97284-9944-11e7-8ee0-cf818707476f.png)

**Comment by muffinresearch** [comment]
It would definitely be nice to not show this link on parts of the site that don't have a mobile counterpart.

**Comment by muffinresearch** [comment]
@ValentinaPC since this needs to change over on addons-server would you mind re-filing there?

**Comment by ValentinaPC** [comment]
Logged https://github.com/mozilla/addons-server/issues/6411.
Closing this.
