### ISSUE TITLE
Theme loading indicators do not match the content

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3134]
The loading indicators for themes is the same as the one for add-ons this results in the page jumping around when the data loads because themes contain a larger image and not just text and an icon.

STR:

Go to https://addons-dev.allizom.org/en-US/firefox/themes/ and watch the themes load.

Loading state:

<img width="912" alt="untitled" src="https://user-images.githubusercontent.com/1514/30425303-a2ab2cfe-9940-11e7-8b26-c075fa0caa55.png">

Loaded content:

<img width="1396" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30425272-8ee813e4-9940-11e7-95a4-b3970242324e.png">

**Comment by ioanarusiczki** [comment]
@willdurand I can see the "No theme preview available" when I load the themes page (it's more obvious on Android). 
However, most of the time the themes load pretty quickly and that empty preview is not present at all. 

![themestab](https://user-images.githubusercontent.com/33448286/67388676-ca0e8600-f5a1-11e9-99fc-c3ec10693ba0.gif)

**Comment by willdurand** [comment]
> @willdurand I can see the "No theme preview available" when I load the themes page (it's more obvious on Android).
> However, most of the time the themes load pretty quickly and that empty preview is not present at all.

Yes, that is intended.
