### ISSUE TITLE
Loading indicators on extensions and themes pages have an extra icon

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3135]
Go to https://addons-dev.allizom.org/en-US/firefox/extensions/

See:

<img width="883" alt="untitled_2" src="https://user-images.githubusercontent.com/1514/30425488-4a40bf06-9941-11e7-9fc5-daca7a89a89a.png">

**Comment by muffinresearch** [comment]
Looking at the markup for this there's a lot of extra unecessary indicators in the shelves:

<img width="452" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31575701-806d9346-b0e4-11e7-809d-e5123b128046.png">

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Loading indicators from themes homepage are looking as expected.
Postfix screenshot:
![cut icons](https://user-images.githubusercontent.com/15685960/31656860-9488d356-b335-11e7-8705-acb8b8932d1b.gif)
