### ISSUE TITLE
"More featured" is inconsistent compared to "More highly rated" and "More popular"

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3137]
See https://addons-dev.allizom.org/en-US/firefox/extensions/featured/

This is inconsistent with "more highly rated" and "more popular" which are just search results pages.

<img width="1408" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30427498-f727fbf2-9947-11e7-93f9-ed3f11a6364e.png">

@pwalm not sure there's specific mocks for these - can we consolidate on a search page based approach?

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.0)

Postfix:
![image](https://user-images.githubusercontent.com/31961530/31667197-5fe2f326-b357-11e7-91b8-2eec5ec1d7b8.png)

![image](https://user-images.githubusercontent.com/31961530/31667340-d9907f5e-b357-11e7-976f-e0fd94be5b4d.png)
