### ISSUE TITLE
Collection view

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3140]
Refs: https://github.com/mozilla/addons-frontend/issues/2782

Mocks are in the Sketch file:

<img width="710" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30435430-a78733b4-9961-11e7-9d55-6077548b6293.png">

**Comment by muffinresearch** [comment]
Iconography is likely to need to dropped for the first release.

**Comment by muffinresearch** [comment]
Otherwise the page to show a collection is fairly vital for representing curated content so should stay in the MVP.

**Comment by muffinresearch** [comment]
This should reflect themes as well as extensions since a collection can contain both.

**Comment by pwalm** [comment]
All three versions:
![extensions collection - 1366px](https://user-images.githubusercontent.com/6797635/30937512-e0a152ea-a38b-11e7-8cf9-0bc713c30b15.png)

![themes collection - 1366px](https://user-images.githubusercontent.com/6797635/30937519-e55fb196-a38b-11e7-9c1c-539f4e125624.png)

![collection mixed - 1366px](https://user-images.githubusercontent.com/6797635/30937525-e95f1c50-a38b-11e7-8816-367c3b36a8d2.png)

**Comment by tofumatt** [comment]
@pwalm: I have a general question about the ways extensions/themes are split up here (and on other pages)–what happens if there's only one theme in the list? Or if the search results surface themes that are more relevant for a search? Should we always de-emphasize themes?

For collections this is a bit less of an issue but for searches the API returns results largely based on relevancy–would it be possible to mock something up that mixed the two results together a bit more? It means fewer API requests (site is faster) but would also mean sorting by relevancy is a lot more straightforward/accurate.

**Comment by devaneymoz** [comment]
From an Editorial perspective, it's not an MVP to have both themes and extensions within the same collection. 

Also, I didn't think Search returns mixed these add-on types?

**Comment by tofumatt** [comment]
Search results can return mixed result types if no “add-on type” filter is set. Right now we just render them each on one row.

**Comment by willdurand** [comment]
Quick question about these screens: where do we fetch the images displayed on the left side? I don't think it is a blocker for MVP, but I am curious.

**Comment by ValentinaPC** [comment]
Is this on -dev? Because, to me, everything looks the same. I am missing something? Thanks!

**Comment by kumar303** [comment]
It looks like we need to open a route for it on dev. When this bug gets closed it should be testable: https://bugzilla.mozilla.org/show_bug.cgi?id=1405351

**Comment by willdurand** [comment]
Ah sorry for that, I forgot about it 😔

**Comment by willdurand** [comment]
This is now available in dev.

**Comment by ValentinaPC** [comment]
@willdurand : Are you talking here about the collection from AMO homepage, "change-up-your-tabs", and its view? Because I am not seeing any other collection. Thanks!

**Comment by willdurand** [comment]
@ValentinaPC in theory you should be able to browse any collection:

- https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/privacy-matters/
- https://addons-dev.allizom.org/en-US/firefox/collections/idenis/power/

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
New AMO pages display without any issues a collection.

**Comment by willdurand** [comment]
@ValentinaPC We do not have iconography for the collections yet (top left card). Add-ons are not split yet because it is not clear what to do, see this comment: https://github.com/mozilla/addons-frontend/issues/3140#issuecomment-332673578.

**Comment by ValentinaPC** [comment]
I suppose new issue will be added for those things and we can mark this verified-fixed.
