### ISSUE TITLE
Read more link doesn't show more content for release notes

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3148]
## STR:

* Go to https://addons-dev.allizom.org/en-US/firefox/addon/requestpolicy/
* Click "Read more" on the release notes:

### What happens:

The read more link disappears but there's no additional content

### What should happen:

A "Read more" link should not be required if the content is already visible.

Before clicking "read more":

<img width="511" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30445836-44f1c750-997f-11e7-84d9-d44ebde1a542.png">

After clicking "read more":

<img width="532" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30445882-653850ec-997f-11e7-9e06-84950b234a89.png">

**Comment by tsl143** [comment]
This is probably because `.ShowMoreCard-contents` have `max-height: 150px` and we test `truncateToMaxHeight` with `MAX_HEIGHT = 100`

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix screenshot:
![rn](https://user-images.githubusercontent.com/15685960/30592215-931b5a18-9d4e-11e7-9349-7166e88f5e43.png)
