### ISSUE TITLE
Update Homepage Category Icons for themes and extensions

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3151]
We're going to simplify the initial release and not make this content carousel based so this is really about updating to the new look and feel category icons and backgrounds. 

We do need to clarify which categories are going to be most prominent if we're limited to less categories. We'll also need the spec, icons and colours etc.

<img width="687" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30450962-49aae014-998a-11e7-9c65-3e79a8316674.png">

**Comment by devaneymoz** [comment]
The attached design here looks to be our subject shelves. I didn't think we had an icon shelf for categories. 

Is this a duplicate issue as this one? https://github.com/mozilla/addons-frontend/issues/3002

**Comment by muffinresearch** [comment]
From a conversation on Vidyo with @devaneymoz this is indeed a dupe of #3002
