### ISSUE TITLE
Add additional data to the homepage

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3152]
We want to have other data on the homepage aside from the carousel and extension and theme categories. 

We need to decide on that that data should be - which is a question for editorial. It should be data we already have as much as possible. So most popular, featured etc.

Here's the mock which doesn't have much on what the data should be

<img width="709" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30451222-e371bc72-998a-11e7-9e0c-ba2a6cc97fc8.png">

**Comment by devaneymoz** [comment]
@muffinresearch  In addition to promo types we already have (i.e. featured, "Up & Coming" etc) are we ready for content programming for the new promo modules - slider and subject shelves?

**Comment by muffinresearch** [comment]
> @muffinresearch In addition to promo types we already have (i.e. featured, "Up & Coming" etc) are we ready for content programming for the new promo modules - slider and subject shelves?

We need to use data we have today, that doesn't rely on new editorial admin being built. Or alternatively something that we hard-code today and make editorial in the future. We've got to keep it simple for the first release.

**Comment by kumar303** [comment]
I'm nominated this from MVP removal since it's a bit vague at the moment. We could put it back when we have something more concrete and actionable.

**Comment by muffinresearch** [comment]
Need to figure this out - so I'm going to leave it in the MVP for now to help remind everyone what's missing detail.

**Comment by devaneymoz** [comment]
Here is the entire content lineup for the Homepage for launch. It includes the carousel and all shelves that appear down the page. The content should be ordered on the page as it appears in the doc. 

https://docs.google.com/a/mozilla.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit?usp=sharing

**Comment by muffinresearch** [comment]
I've split this out into individual issues for each shelf so we can use them instead of this issue.

**Comment by tofumatt** [comment]
This data was provided in the PRD Scott shared (available here: https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg) so I'm closing this one out.
