### ISSUE TITLE
Add categories to search filters

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3155]
From the scope doc: "Below the type filter, list categories for the selected type"

Here's the categories in the search filtering:

<img width="268" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30452617-41e88698-998e-11e7-9adb-fe4ca18c220f.png">

I think this can be something we iterate on post-release.

**Comment by kumar303** [comment]
I think this is important because it's currently not obvious that you're inside a category when descend into add-on results from a category page. Example: [Games & Entertainment](https://addons.mozilla.org/en-US/firefox/extensions/games-entertainment/) > top rated.
