### ISSUE TITLE
Review count links to review section

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3157]
From the PRD:

"Review count links to reviews section in listing page"

Presumably the review content in the header needs to link down to the review section via a fragment identifier?

<img width="771" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30478832-977974ec-9a0a-11e7-8f61-7c846af54fd0.png">

@jvillalobos does this sound right? ^

**Comment by jvillalobos** [comment]
Yes, but by "review section", it refers to the place that shows the most recent reviews, rather than the place where you can create a review.

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/addons-frontend/issues/4287
