### ISSUE TITLE
Implement the new footer

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3158]
Update the footer with the new download links and to match the new org style:

<img width="1260" alt="moz_org_footer_053117_sketch" src="https://user-images.githubusercontent.com/1514/30479071-770bc542-9a0b-11e7-9569-fa047df81df0.png">

For mobile

<img width="212" alt="moz_org_footer_053117_sketch" src="https://user-images.githubusercontent.com/1514/30479292-8756bcb2-9a0c-11e7-9109-6021d634e32a.png">

See the footer specific sketch file in the assets folder for specific details.

**Comment by muffinresearch** [comment]
@pwalm The mock needs to reflect the AMO specific links:

About (Once page exists this is AMO about page not the global one)
Review Policy (Once page exists)
Report a Bug
View classic desktop site. (this will eventually go since this is that site)

**Comment by ValentinaPC** [comment]
@muffinresearch : shouldn't we use same color as for header for the footer background?
Thanks!

**Comment by tofumatt** [comment]
Nope, the footer colour should be that black (or nearly black) colour across Mozilla sites. But the top header is our own colour.

Matthew Riley MacPherson (sent from mobile)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Footer is updated and all links redirect and works as expected.
Postfix screenshot:
![2017-09-22_1217](https://user-images.githubusercontent.com/15685960/30737722-45625bca-9f90-11e7-9398-0e7871f22fbf.png)
