### ISSUE TITLE
Prefix middleware doesn't allow for non-clientApp urls to be served by the app

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3162]
The Prefixmiddleware has code which forcibly returns a 404. See https://github.com/mozilla/addons-frontend/blob/05da066d1638d77c6e667b21f6282e59e57253f6/src/core/middleware/prefixMiddleware.js#L90

This prevents adding nonClientApp urls that actually need to be served by our app because they result in 404s. (I'm currently working on getting the static pages ready to land). Our about page needs to be at `/%locale%/about/` there's an exception for this which does prevent it being re-written to `/%locale%/%clientApp%/about/` but then we hit https://github.com/mozilla/addons-frontend/blob/05da066d1638d77c6e667b21f6282e59e57253f6/src/core/middleware/prefixMiddleware.js#L90 which causes a 404.

Removing this code means that the non-clientApp part is matched by the `:application` placeholder for other routes e.g: `/%locale%/editors/` (which then serves the homepage) so that's a non-starter because we ideally want this to fall through to a `notFound` route.

We really need a way to ensure only firefox and android are matched as applications. This might require a router upgrade :/

@tofumatt I'd be interested to chat this over with you next week and see if we can find an easy way out of the problem.

**Comment by tofumatt** [comment]
Ten four. I'll have a quick look over the weekend and will be around Monday to chat about it. Sorry about that–that implementation is definitely hacky as a workaround the the weirdness of our router's limitations.

**Comment by muffinresearch** [comment]
As discussed on Vidyo there's two possible solutions to this:

1. Add to the existing hack so that certain clientApps are allowed through to the app but the rest 404
2. Remove the last pieces of `redux-connect` and upgrade to RR4. 

We're opting to investigate what the 2nd option would take with a **strictly time-boxed** look at removing the last pieces of `redux-connect` - this looks to be mostly limited to dispatching `loadFail` looking at:

* https://github.com/mozilla/addons-frontend/search?p=1&q=redux-connect&type=&utf8=%E2%9C%93
* https://github.com/mozilla/addons-frontend/search?utf8=%E2%9C%93&q=loadFail&type=
 
If that's viable then upgrading to RR4 will be a follow-up. If the limited look at redux-connect removal  looks to be too involved we will instead opt for option 1.

**Comment by muffinresearch** [comment]
Ok so the outcome of this is we'll need to deal with an exclusion to get the routes working and come back to the router upgrade in due course.
