### ISSUE TITLE
Category links as overlays in the new frontend

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3175]
The scope doc refers to "Drop down for Extensions and Themes, listing categories "

This needs to work for both the themes and extensions primary navigation.

This should mirror the legacy frontend:

<img width="1166" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30590336-052037f0-9d36-11e7-85ef-29f3e8af5a98.png">

It should be navigable with the keyboard in the same way the dropdown menu for the user currently is.

**Comment by tofumatt** [comment]
But is this still in any of the UX mocks? The extensions section will have a drop-down that will include Language Packs & Dictionaries, Search Plugins, etc. Given these categories appear on the add-on type's landing page this seems like something worth dropping.

**Comment by jvillalobos** [comment]
In the current design it only takes an extra click to get to a category page, so I think we can drop this.
