### ISSUE TITLE
Keep "More extensions by author_name" section in the same position

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3176]
Steps to reproduce:
1. Load details page for an add-on that has release notes i.e. https://addons-dev.allizom.org/en-US/firefox/addon/xnotifier/
2. Load details page for an add-on that does not have release notes i.e. https://addons-dev.allizom.org/en-US/firefox/addon/ratopuse-weasp-vulturkal/
3. Compare "More extensions by author_name" section position from both pages.

Expected results:
The section is positioned in the same place in both pages.

Actual results:
The "More extensions by author_name" section is after More information section for the add-on with release notes and before this section for the add-on without release notes.

Notes/Issues:
Verified on AMO-dev FF55(Win 7).
Screenshot for this issue: 
![more](https://user-images.githubusercontent.com/15685960/30591419-6b05f40a-9d4b-11e7-9ac5-ae566bf24a0a.png)

**Comment by tofumatt** [comment]
This looks like it could be a grid issue but I don't even see "More Extensions" for xnotifier.

Ah, I see. Please make sure to specify the viewport size you're using when filing issues like this as they are out-of-order on mobile but one is entirely obscured on Desktop.

See:

<img width="1280" alt="screenshot 2017-09-19 13 22 10" src="https://user-images.githubusercontent.com/90871/30592189-b90cc092-9d3d-11e7-9cc8-fa3de89101a3.png">
<img width="1280" alt="screenshot 2017-09-19 13 22 07" src="https://user-images.githubusercontent.com/90871/30592188-b904c82e-9d3d-11e7-8219-751c1911d719.png">

I'm considering it the same issue though as it's a grid bug.

I'll try to get this fixed up before the tag right now as it should be easy and is sort of annoying 😄

**Comment by tofumatt** [comment]
Oddly this is worse than reported. I can't see more add-ons on the frontend by the author at all... yet they appear on the old site. Something is amiss and this will require more investigation...

**Comment by ValentinaPC** [comment]
@tofumatt : my initial screenshots look like I am using small browser size but I am not, just cropped the important part of the screen.
I am using same as always: 1600 x 900 px. 
Thanks!

**Comment by tsl143** [comment]
@tofumatt, the `more addons by author` section, will be visible on chrome for this sepcific addon
`http://localhost:3000/en-US/firefox/addon/xnotifier/`.
On Firefox(I am using nightly) the `appversion=57.0` is appended in querystrings of Api for fetching more addons by the users, and in this case no addons are fetched as other addons by this user are not compatible with 57.

**Comment by tofumatt** [comment]
Oh, shoot. So that definitely shouldn't be appended for add-on detail requests. Thanks for catching that @tsl143, that's super helpful! Will make it much easier to fix. 😄

**Comment by tsl143** [comment]
For the layout issue, I submitted PR already.

**Comment by ValentinaPC** [comment]
> @ValentinaPC , can you help us with the version of Firefox you are using?

Late, I know :). As I mentioned while logging this, I was using FF55. Thanks!

**Comment by ValentinaPC** [comment]
While checking this in FF58 (Win 7), I saw that the issue is reproducing but in a weird way.
For the add-on with the release notes - the more add-ons by author_name section is no longer displayed.
Please see screenshot:
![rn-more](https://user-images.githubusercontent.com/15685960/30796728-0942d112-a1dc-11e7-9eb2-f5b654fe2e3a.png)

Add-on used: https://addons-dev.allizom.org/en-US/firefox/addon/xnotifier/

@tofumatt : I'll reopen this, but let me know if a Bugzilla issue is required here.

**Comment by tofumatt** [comment]
This is expected because when searching for “more add-ons by this author” we only look for add-ons compatible with your current browser version. So you’ll need to check from a 57+ compatible add on or use an older browser for that add on.

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
Based on above comments, I'll mark this verified fixed.
Postfix screenshots:
![m1](https://user-images.githubusercontent.com/15685960/30797435-b4771438-a1de-11e7-9494-e885b026cc3f.png)
![m2](https://user-images.githubusercontent.com/15685960/30797436-b6ce1a2e-a1de-11e7-8f9c-0e50f21bbbe7.png)
