### ISSUE TITLE
Verify fonts are correct

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#318]
The spec suggests using SanFranciso for the font which is OS X only. I'm guessing this should use the platform default then, but we should confirm that and make sure it works on all platforms (Windows, OS X, Ubuntu, whatever linux you happen to have installed).

UX spec is in https://github.com/mozilla/addons/issues/64.

@pwalm can you please confirm how the fonts should be handled.

**Comment by pwalm** [comment]
Sorry, we should use whatever typeface is the default on that platform.

**Comment by muffinresearch** [comment]
This was already done see https://github.com/mozilla/addons-frontend/blob/master/src/disco/css/App.scss#L9
