### ISSUE TITLE
There is no obvious way to edit your review

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3180]
### Describe the problem and steps to reproduce it:

* go to AMO and visit any add-ons details page.
* Write a review

### What happened?

You have no obvious way to edit the review

### What did you expect to happen?

There should be an edit button for your own review

### Anything else we should know?

The review is actually editable but you have to click a star as if you were rating the add-on again (which doesn't make sense). See https://github.com/mozilla/addons-frontend/issues/3075 for original report.

**Comment by muffinresearch** [comment]
See also the tracker for other https://github.com/mozilla/addons-frontend/issues/2772 in-case there's other relevant parts of this to take into consideration.

**Comment by AlexandraMoga** [comment]
I've verified this feature on AMO-dev F55 (WIn 10 and Android 7.0)
In both tests I observe the following:

1. Click on 'Edit My review" 
2. Type additional text in the text area
3. Modify the star rating

Expected result:
The modifications made in the text area should show the updates just made

Actual result:
The updates made in the text area disappear if the star rating is modified after new text is added

Video reproduction:
![edit review](https://user-images.githubusercontent.com/31961530/30914711-3f24a4d2-a39d-11e7-9222-8ce4384e9576.gif)

**Comment by kumar303** [comment]
Good catch, thanks. It will be easier to track this in a separate issue so I moved it to https://github.com/mozilla/addons-frontend/issues/3255
