### ISSUE TITLE
Make the search look more obviously focused

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3184]
Unfocused: 

<img width="308" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30636871-91632458-9dee-11e7-9041-6094e78a98ef.png">

Focused:

<img width="311" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30636888-a319fece-9dee-11e7-809f-47246238d8d2.png">

For styling we should look at something similar for what we do for the logged-out sign in button.

<img width="336" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30636950-d6496b40-9dee-11e7-8e82-5f2ca0ca8211.png">

**Comment by AlexandraMoga** [comment]
Verified in AMO-Dev Mobile view and the search field appears focused as expected:

![focused search](https://user-images.githubusercontent.com/31961530/30648209-2d54c952-9e26-11e7-8e7f-5ee4308711cb.png)
