### ISSUE TITLE
Menu jumps vertically on logout

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3185]
When logging out the user menu jumps vertically see the following animated gif:

![jumping-menu-logout](https://user-images.githubusercontent.com/1514/30638537-a6685fa8-9df3-11e7-8379-8e0f3ca8a259.gif)

Fixing this requires matching the logged in heights/padding/margin etc with the styles for logged-out so there's no vertical displacement.

**Comment by AlexandraMoga** [comment]
verified on FF56 (Win 10 and Android 7.0)

Postfix video:

![vertical jump menu](https://user-images.githubusercontent.com/31961530/31075857-3fb4d2d2-a780-11e7-98b9-ed631c596f8f.gif)
