### ISSUE TITLE
Fix the minor difference between button height and search box height

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3186]
On mobile there's a small difference between the search box height and the login button. 

![screen-shot-2017-09-20-at-10 56 30](https://user-images.githubusercontent.com/1514/30638328-f6fdfbf4-9df2-11e7-8a53-a873132a0123.png)

It's a really minor difference, but would be nice to fix it for consistency.

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-frontend/issues/3185 - which affects a related area and could be fixed at the same time.

**Comment by tofumatt** [comment]
I think there’s actually supposed to be a height difference… but at least vertically centering the button inside would be nicer. I think it was supposed to be… if the login button were moved 1px up that would work I think.

**Comment by muffinresearch** [comment]
For me, the height difference stands out a mile and looks like a bug, but if aligning-top helps alleviate my inner sense of discord that could work too. Either way it's super minor issue.

**Comment by vcarciu** [comment]
This looks fixed now : 
![align](https://user-images.githubusercontent.com/1583842/30738507-fb6e4c10-9f92-11e7-8f1f-ed37692a8620.png)
