### ISSUE TITLE
Developer Hub page layout issues when using split screen view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3189]
Scenario 1:
Preconditions: User is logged into his AMO account

Steps to reproduce:
1.Log in to AMO stage, desktop view
2.Access Developer Hub while in full screen view
3.Observe the page layout (pay attention to Header Menus and Page Footer)
4.Split your screen (i.e by using START+LEFT KEY)
5.Observe the page layout again

Expected Results:
Page layout in split screen view should include the same options as the full screen view

Actual result:
When in split screen view, the page does not include the following: 
-'My Add-ons' and the Profile Logo in the Header menu
-No vertical scroll bar to reach the Footer menu

Video demonstration - User Logged In:
![devhub login layout](https://user-images.githubusercontent.com/31961530/30637411-ea0b9286-9e00-11e7-969b-62419fad2c66.gif)

Scenario 2:
Preconditions: User has logged  out from his AMO account

Steps to reproduce:
1.Access AMO stage while logged out
2.Access Developer Hub while in full screen view
3.Observe the page layout (pay attention to Header Menus and the Page Footer)
4.Split your screen (i.e by using START+LEFT KEY)
5.Observe the page layout again

Expected Results:
Page layout in split screen view should include the same options as the full screen view

Actual result:
When in split screen view, the page does not include the following: 
-the 'Sign in' or 'Register' links in the Header menu
-The vertical scroll bar does not reach to the Footer menu

Video demonstration - User Logged out:
![devhub logout layout](https://user-images.githubusercontent.com/31961530/30637538-3d8fc300-9e01-11e7-89ee-a5387c2f29fa.gif)

Notes: the issue can be reproduced on AMO-Dev and AMO-Prod as well

**Comment by tofumatt** [comment]
Confusingly this code is actually in the addons-server repository, sorry about that! I've moved the issue to that repo. 😄
