### ISSUE TITLE
Categories labels all green on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3193]
Steps to reproduce:
1. Load Extensions categories page on your Android device (or on desktop, after changing the app to "Firefox for Android" )i.e. https://addons.allizom.org/en-US/android/extensions/
2. Observe the color of the labels

Expected results:
Categories labels have different colors.

Actual results:
All extensions categories are green.

Notes/Issues:
- all sort of green is happening for themes categories also.
Screenshot for this issue:
![untitled](https://user-images.githubusercontent.com/15685960/30682829-baedb534-9eb3-11e7-8020-f5abae07be25.png)

Reproducing on all AMO servers.
Verified using FF55(Win 7, Android 7.2.1).

**Comment by muffinresearch** [comment]
This might be resolved if we get to unify the categories see https://github.com/mozilla/addons-server/issues/5989

**Comment by willdurand** [comment]
closing in favor of https://github.com/mozilla/addons-frontend/issues/8180
