### ISSUE TITLE
callApi has a public API that is frustrating (and also sends query params for POST requests)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3197]
I expected to be able to use `callApi` for `POST` requests as I do `GET` requests:

```js
return callApi({
  auth: true,
  endpoint: 'abuse/report/addon',
  method: 'POST',
  params: { addon: addonSlug, message },
  state: api,
});
```

But that doesn't work at all. It sends no params to the server. Seems like I need to use `body` instead. I get that's how HTTP works, but I think it would be nice if this API handled simple POST requests like mine for me.

It also sends `queryParams` when it's not making a `GET` request, which it seems like it should just ignore instead.

Essentially I'd expect `params` for non-`GET` requests to be changed to `options.body`.

**Comment by kumar303** [comment]
The `lang` query param may be necessary for some POST requests to set the default locale.

**Comment by kumar303** [comment]
I'd really like to whip `callApi` into shape. In addition to the `params` thing, `auth` should default to `true` so we don't have to set it every time.

**Comment by suhailsinghbains** [comment]
Hi, I want to solve this issue, can I please be assigned this.

**Comment by willdurand** [comment]
@suhailsinghbains sorry but this is not an issue you should work on now. I'll remove the contrib tag. Sorry.

**Comment by willdurand** [comment]
I don't think we're going to ever change that, so I am closing this issue for now.
