### ISSUE TITLE
"My Add-on doesn't fit into any of the categories" is auto checked in Android section when selecting a category from Desktop

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3199]
Steps to reproduce:
1. Log into to AMO-stage
2. Go to Submit a New Add-on and select a file to upload
3. Once the file passes validation, press Continue to add your Add-on information
4. Select an Add-on category in the Desktop section

Expected result:
Category selected for Desktop section should not affect the Categories in the Android section

Actual result;
The category for Android defaults to "My Add-on doesn't fit into any of the categories" after a  category is selected in the Desktop section

Notes: reproduces on AMO-dev

Video Demonstration:
![categories at webext submission](https://user-images.githubusercontent.com/31961530/30701742-b25fdf06-9ef3-11e7-9c82-2059f650e01a.gif)

**Comment by ValentinaPC** [comment]
@muffinresearch : I think this is not something new. Please take a look at: https://github.com/mozilla/addons-server/issues/4736 .

**Comment by diox** [comment]
Fixed in https://github.com/mozilla/addons-server/pull/6471

**Comment by AlexandraMoga** [comment]
Issue seems to be resolved. Works on AMO-prod, stage and dev
