### ISSUE TITLE
Reduce click target of mozilla logo

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3200]
The click target for the mozilla logo is a little bit too big, that can be reduced to something a bit more sane.

<img width="777" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30704339-5cc02ce4-9eea-11e7-99c8-c55d82d95878.png">

**Comment by tofumatt** [comment]
lol I didn't notice this! 😆

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7).
Postfix video:
![mozilla](https://user-images.githubusercontent.com/15685960/30731554-b98b6e2a-9f76-11e7-9d0f-ce11c1f6297f.gif)
