### ISSUE TITLE
No padding between extensions icons and extensions categories names for Italian on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3204]
Steps to reproduce:
1. Load AMO homepage on your device
2. Change the language to "Italian" - https://addons-dev.allizom.org/it/android/
3. Observe Extensions categories

Expected results:
There are no layout issues.

Actual results:
There is no padding between extensions icons and extensions categories names.

Notes/Issues:
Verified on AMO-dev FF55(Win 7). Issue is reproducing around all servers.
Screenshot for this issue:
![dev](https://user-images.githubusercontent.com/15685960/30731858-861e5bb8-9f78-11e7-8ea0-1e224489324a.png)

**Comment by muffinresearch** [comment]
This is all going to change soon, so it's probably not worth fixing separately until after the content gets changed and the icons updated.
