### ISSUE TITLE
Send appversion in autcomplete params

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3209]
### Describe the problem and steps to reproduce it:
Autocomplete results include incompatible add-ons because we don't send `appversion=${firefoxVersion}` as a param like we do for regular searches. This causes a lot of results in autocomplete that are clicked on using 57+ being incompatible. This isn't a great UX.

### What happened?
Search suggestions don't hide incompatible add-ons if you're on 57+.

### What did you expect to happen?
Search suggestions hide incompatible add-ons if you're on 57+.

----

Related to #2706.

**Comment by tofumatt** [comment]
I think this is MVP because:

* it's easy
* it is an important part of not surfacing incompatible add-ons

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!

**Comment by tofumatt** [comment]
If using Firefox 57+, autocomplete results should only surface compatible add-ons. You should not be able to go to an incompatible add-on from the autocomplete result in 57+

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF58(Win 7).
Incompatible add-ons are not listed between search suggestions if using FF58.
Postfix screenshots:
![2017-09-26_1422](https://user-images.githubusercontent.com/15685960/30857886-2c2517a4-a2c6-11e7-8705-c454264969c7.png)
