### ISSUE TITLE
Add in a __version__ end point

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#321]
So we can tell what's deployed. You know this will come in helpful to @jasonthomas and everyone else at some point in the future:

See an example here: https://addons-dev.allizom.org/__version__

**Comment by muffinresearch** [comment]
This is something ops historically setup so I've filed this bug:  https://bugzilla.mozilla.org/show_bug.cgi?id=1270453 

But we can leave this open to track it from here.
