### ISSUE TITLE
Allows links in the summary for recommended add-ons.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3213]
Currently recommended add-ons have links removed by DOMPurify:

<img width="768" alt="add-ons_manager" src="https://user-images.githubusercontent.com/1514/30755496-d4d94916-9fbe-11e7-8173-4fff226a6e37.png">

We need to look to allow links in the sanitization step so they don't get removed from the content entirely.

**Comment by ValentinaPC** [comment]
Verified this while Disco Pane is set to point -dev using FF58(Win 7).
Added a link in description for the recommended theme https://addons-dev.allizom.org/en-US/firefox/addon/dog-pichu/ , but the link is not listed in Disco Pane, not even after install in Themes tab. Is there another place where the description should be added for the recommended add-ons, @muffinresearch ?

Also, installing the recommended theme directly from AMO will not parse correctly the URL in Themes tab.
![2017-09-26_1058](https://user-images.githubusercontent.com/15685960/30849040-add01cb2-a2a9-11e7-8041-7f13dcece30c.png)
