### ISSUE TITLE
Fix up theme and extension hero content to closer match mocks

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3215]
Today: 

<img width="1448" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/30759849-ba50dfe4-9fcf-11e7-8952-db05929a313e.png">

Mocks:

<img width="1042" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/30759877-d8027cb4-9fcf-11e7-9054-4660380b433e.png">

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev mobile view and mobile device

![fix_exte_layout](https://user-images.githubusercontent.com/31961530/30812886-a1e66252-a214-11e7-9066-0e80a9f64fa5.png)

![fix_theme_layout](https://user-images.githubusercontent.com/31961530/30812892-a40b21c6-a214-11e7-83a7-722431b0f687.png)
