### ISSUE TITLE
Show a 404 error for 403 add-ons

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3218]
Similar to how (and why) we render a `404 NOT FOUND` response for `401` pages, we should show `404` for an add-on that returns a `403` response, at least for now. Same for the "All reviews" page of any add-ons that returns a `403` error from the API.

Part of #2769.

**Comment by vcarciu** [comment]
Can you please add some STR for this issue or mark it as "qa:not needed" ?

**Comment by tofumatt** [comment]
Navigate to an add-on that would give a 403 response and ensure there is a 404 Not Found response. You may need to create an add-on that is visible only to certain sign-in users then access it as none of those users to hit such a page.

If that's a pain let me know and we can skip the QA on this one as it's pretty basic.
