### ISSUE TITLE
Rename denormalizeReview() to createInternalReview()

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3219]
A pattern has emerged where we take an external API object and store it with a function like [`createInternalAddon()`](https://github.com/mozilla/addons-frontend/blob/cc5baba5d47e508323b3b8f45ea16b94a7f19a58/src/core/reducers/addons.js#L83). This is a good name because it illustrates the intent. 

There is an older function called [`denormalizeReview()`](https://github.com/mozilla/addons-frontend/blob/cc5baba5d47e508323b3b8f45ea16b94a7f19a58/src/amo/actions/reviews.js#L22) that did pretty much the same thing. Let's rename it to `createInternalReview()` since that makes more sense.

Ask before working on this to avoid conflicts with open PRs.

**Comment by plant99** [comment]
Can I work on it? @kumar303

**Comment by tofumatt** [comment]
There is a large review-code-related patch in review right now (#3220) so now is not a good time to do fix this issue as it will create confllicts.

**Comment by vcarciu** [comment]
Reviews looks good. Marking issue as verified.
