### ISSUE TITLE
Fix review by user state so that it stores object IDs not objects

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3221]
**For QA:**
Please check for regressions in the flows related to leaving a star rating, writing a review, editing a review, and browsing reviews.

As of https://github.com/mozilla/addons-frontend/pull/3220 the review state has a map of reviews by ID. All other parts of the state link to IDs instead of objects. However, I didn't have time to fix the user state because it wasn't relevant for the patch and it introduced some complexities. It will rot away so we should fix it.

**Comment by vcarciu** [comment]
No reviews related regressions found. Marking issue as verified.
