### ISSUE TITLE
Exclude from updates – a persistent preference for any selected add-on

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3223]
With Firefox 55.0.3, for an extension that I preferred to **not** _Include in update_ (singular), the subsequent review of _Available Updates_ wrongly assumes that my preference was a one-off: 

![2017-09-23 08 42 06](https://user-images.githubusercontent.com/192271/30771273-49dbae1c-a03b-11e7-9c05-733ccf4fd85e.png)

– that's an example of an add-on that I **never** include in an update. I must **repeatedly** take care to deselect what Firefox has selected. 

## Enhancement request

Allow a single, per-add-on preference that will persist, across multiple update routines, for as long as the user wants: 

☑️ **Exclude from updates**

**Comment by tofumatt** [comment]
Sorry for the confusion but this bug tracker is a catch-all mostly for Mozilla add-ons websites and less to do with browser code, which is where this setting exists.

You'll want to file this over at https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons%20Manager (that's the correct Bugzilla component). Sorry about the confusion, but thanks for the feature request and the clear bug report 😄

**Comment by grahamperrin** [comment]
For reference only: 

- [about:addons ☑ Exclude from updates (Updates: … 🔘 never) · Issue #349 · MrAlex94/Waterfox](https://github.com/MrAlex94/Waterfox/issues/349)

– I'm not ignoring Bugzilla@Mozilla `:-)` just slowly letting things take shape in the Waterfox area …
