### ISSUE TITLE
Long description and "More extensions by author_name" section cause layout issues in add-on details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3226]
Steps to reproduce:
1. Load and add-on details page that has a long description i.e. https://addons-dev.allizom.org/en-US/firefox/addon/ratopuse-weasp-vulturkal/
2. Click the "Read More" link

Expected results:
There are no display or layout issues.

Actual results:
A gray space separates the "More extensions by author_name" section from "More information" section.

Notes/Issues:
Verified on AMO-dev FF55(Win 7).
Screenshot for this issue:
![read_more](https://user-images.githubusercontent.com/15685960/30797122-84f0ab94-a1dd-11e7-86d2-62b8d4f64c63.png)

**Comment by tofumatt** [comment]
Pretty sure I have a fix for this, we probably need to stop using `grid-row` entirely on the left and just let things auto-flow. I'll have a fix after I come back from squash/running.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF55(Win 7) and FF58 and everything looks ok.
Postfix screenshot: 
![1](https://user-images.githubusercontent.com/15685960/30867150-d6783ea8-a2e3-11e7-9176-1ac5baa4d446.png)
