### ISSUE TITLE
Warning Git/GitHub about Sketch files

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3227]
Hi,

I just got these warnings from GitHub:

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File assets/sketch files/moz.org_footer_053117.sketch is 76.22 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

It is generally not a good idea to version Sketch files like this. Every change implies the whole file to be part of the commit, which means +76MB to the repo for each committed change.

**Comment by tofumatt** [comment]
Yeah, that's a good point... but otherwise it can be tough to keep up-to-date with Sketch. Is there another easy workflow that would allow everyone to access the Sketch file easily?

**Comment by willdurand** [comment]
Git LFS is recommended here. It works almost has without it, except that it stores files tracked by Git LFS differently, and you do not have to download all versions of all tracked files all the time. You version a pointer to a file and Git LFS downloads the file (and cache it).

**Comment by tofumatt** [comment]
What’s the flow like for UX, who works on these files? :-)

If we can show UX how to use it I think it should be fine!

**Comment by willdurand** [comment]
I think these are two good starting points:

- https://about.gitlab.com/2017/01/30/getting-started-with-git-lfs-tutorial/
- https://github.com/blog/2079-managing-large-files-with-git-lfs

To sum up:

1. people interacting with the sketch files have to install `git lfs` (`brew install git-lfs` + `git lfs install`)
2. one has to "track" all sketch files (`git lfs track *.sketch` so that it is future-proof)
3. there is not step 3, Git LFS handles everything else

It is "too late" for what has been committed already (what is in Git stays in Git, because no one wants to `filter-branch` the history), but it is still better than nothing.

Note: if you don't have `git lfs` installed, that's fine but you will not get the sketch files on a fresh "clone". If you need them, you can `git lfs fetch` them though.

**Comment by muffinresearch** [comment]
We tried this in the past and it didn't go too well. We could take another look since things may have improved since last time but it's worth bearing in mind. I will see if I can find out what happened so we can check it's no longer an issue.

**Comment by muffinresearch** [comment]
Here's the previous issue for reference https://github.com/mozilla/addons-frontend/issues/453#issuecomment-221904480

**Comment by muffinresearch** [comment]
Discuss this a bit with @tofumatt today - on of the things suggested was that if LFS is still bad we could also consider spinning the assets out into their own repo.

**Comment by willdurand** [comment]
So other option is to get rid of these files entirely with `git filter-branch`, which will invalidate all other branches but also completely remove the files.

UX has a shared Google drive and InVision.
