### ISSUE TITLE
Link to All versions / All development channel versions from add-on detail page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3229]
Before implementing the [All versions / All development channel versions](https://github.com/mozilla/addons-frontend/issues/2770) pages we can link to those existing pages on the old site. This will at least let users (e.g. ESR or pre-57 users) attempt to find compatible versions.

**Comment by vcarciu** [comment]
Verified as fixed : 
![see versions](https://user-images.githubusercontent.com/1583842/30873628-8968c3d6-a2f6-11e7-95f2-60d6e98704b0.gif)
