### ISSUE TITLE
Hovering over a star shows the tooltip "No ratings"

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3231]
### Describe the problem and steps to reproduce it:

* On desktop, go to the detail page for an add-on that you want to rate
* Sign in
* Hover over a star that you want to click to select a rating

### What happened?

The tool tip says "No ratings" which doesn't make any sense

<img width="315" alt="screenshot 2017-09-25 17 20 51" src="https://user-images.githubusercontent.com/55398/30833833-4935036e-a216-11e7-9c73-366ba4c8552c.png">

### What did you expect to happen?

It should say "Click the star to rate the add-on" or something.

**Comment by SeanPrashad** [comment]
Hey everyone, I've managed to implement a small fix for this bug! Check out my PR below.

**Comment by tofumatt** [comment]
Hi Sean! Thanks for the PR! We get notifications about new PRs and since you already mentioned this issue in your PR you don’t have to comment on the issue as well–we’ll see the PR and get to reviewing it :-)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF59, Win10x64

![rating tooltip](https://user-images.githubusercontent.com/31961530/38186714-f7873f9c-365c-11e8-9ff7-2bcef8b91a2c.gif)
