### ISSUE TITLE
Addon Detail Page Card order doesn't match mocks

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3241]
The card order should look like:

<img width="750" alt="screenshot 2017-09-26 13 28 52" src="https://user-images.githubusercontent.com/90871/30860327-b604682e-a2be-11e7-8fe8-f864c6875c23.png">
<img width="686" alt="screenshot 2017-09-26 13 28 46" src="https://user-images.githubusercontent.com/90871/30860328-b605136e-a2be-11e7-9922-193eb2e51111.png">

I've got a quick patch to change this.

QA: Note this won't update all the styles, but will at least keep the order presented here.

**Comment by vcarciu** [comment]
The order is not the one described in the bug . Verified on -dev and issue is applied to both extensions and themes : 
![order](https://user-images.githubusercontent.com/1583842/30873140-ed77aa2e-a2f4-11e7-879c-3160f4371442.png)

**Comment by tofumatt** [comment]
Seems there's an issue with dev being updated. This should work but the fix isn't deployed...

**Comment by tofumatt** [comment]
The dev site updated–this is now working on -dev.

**Comment by vcarciu** [comment]
Verified as fixed for both Themes: 
![tabthemes](https://user-images.githubusercontent.com/1583842/30926511-120e4540-a3be-11e7-9c11-0504df32e083.png)

...and extensions:
![tabextensions](https://user-images.githubusercontent.com/1583842/30926527-206326d8-a3be-11e7-9e01-fe351e85212c.png)

Please note that not all tabs are implemented and on device, the tabs from right should come first.
