### ISSUE TITLE
Fix link colour in disco pane recommendations

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3245]
Link colour is falling back to default which makes them stick out a little too much. Let's drop them back to the same colour as the body text.

<img width="737" alt="discover_add-ons" src="https://user-images.githubusercontent.com/1514/30874050-26749c1e-a2e7-11e7-89ab-37593270a42e.png">

**Comment by ValentinaPC** [comment]
Could not check this on Disco Pane, but, I can reproduce it on new frontend.
Do we wanna apply the changes in here too?
Please see screenshot:
![link](https://user-images.githubusercontent.com/15685960/30924410-50d7532c-a3b7-11e7-8fcd-f99f0cd017e1.png)

**Comment by tofumatt** [comment]
No, this only applies to the Disco pane. We want to keep the visited style on the AMO site 😄

**Comment by ValentinaPC** [comment]
Is there a way to check this in Disco Pane? I have only a theme displayed there while set to point -dev. :(

**Comment by muffinresearch** [comment]
It's pretty much impossible to test until it gets to prod due to the recommendations data not being based on -dev/stage.
