### ISSUE TITLE
Clicking a star while editing a review will erase some text

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3255]
from https://github.com/mozilla/addons-frontend/issues/3180#issuecomment-332513834 

I've verified https://github.com/mozilla/addons-frontend/issues/3180 on AMO-dev F55 (WIn 10 and Android 7.0)
In both tests I observe the following:

- Click on 'Edit My review"
- Type additional text in the text area
- Modify the star rating

Expected result:
The modifications made in the text area should show the updates just made

Actual result:
The updates made in the text area disappear if the star rating is modified after new text is added

Video reproduction:
![edit review](https://user-images.githubusercontent.com/31961530/30914711-3f24a4d2-a39d-11e7-9222-8ce4384e9576.gif)

**Comment by AlexandraMoga** [comment]
Retested scenario and works as expected now
verified on AMO-dev F55 (WIn 10 and Android 7.0)

Postfix video:

![edit review fix](https://user-images.githubusercontent.com/31961530/31069433-208e9a34-a765-11e7-95d0-ee3652485422.gif)
