### ISSUE TITLE
Fix the contrast for the background behind the logo.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#326]
See https://discovery.addons-dev.allizom.org/

The background behind the logo is the specced colour but there's very minimal contrast.

<img alt="discover_add-ons" src="https://cloud.githubusercontent.com/assets/1514/15051966/2d19f7ec-12f3-11e6-8cd7-dab7c2b2afa5.png">

@pwalm - what do you think - do you have an alternative colour that would make this more distinct?

**Comment by pwalm** [comment]
I'm ok with the low contrast. It's not meant to be dramatically different.
