### ISSUE TITLE
Regular expression denial of service in `mime` package

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3260]
The `mime` package can cause a denial of service: https://nodesecurity.io/advisories/535

This is used by `express` so it would affect our production server:

```
$ npm ls mime
mozilla-addons-frontend@0.0.1 /Users/kumar/dev/addons-frontend
├─┬ express@4.15.5
│ └─┬ send@0.15.6
│   └── mime@1.3.4
├── UNMET PEER DEPENDENCY react@15.6.2
├── UNMET PEER DEPENDENCY react-redux@5.0.6
├─┬ supertest@3.0.0
│ └─┬ superagent@3.5.2
│   └── mime@1.3.6
├─┬ url-loader@0.5.9
│ └── mime@1.3.6
├── UNMET PEER DEPENDENCY webpack@3.1.0
└─┬ webpack-dev-middleware@1.11.0
  └── mime@1.3.6
```

**Comment by kumar303** [comment]
Express claims that it's not vulnerable so we can probably add an exception for this advisory until they release a patch. https://github.com/expressjs/express/issues/3431

**Comment by wagnerand** [comment]
@kumar303  Let's update express to 4.16 now :)
