### ISSUE TITLE
Add-on abuse report UI does not show errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3262]
### Describe the problem and steps to reproduce it:

* Using a local development server, go to an add-on detail page
* Click Report this add-on for abuse
* Enter some text for the abuse report
* Stop your development server. This will cause the API to respond with a 500 error. I'm not sure of any other way to trigger an API error.
* Click the Send abuse report button

### What happened?

Nothing. The UI is stuck in a state where you can't dismiss the prompt:

<img width="275" alt="screenshot 2017-09-27 15 06 47" src="https://user-images.githubusercontent.com/55398/30935304-df072540-a395-11e7-9c05-aafde490864e.png">

### What did you expect to happen?

The UI should render the error caught by `errorHandler`

**Comment by tofumatt** [comment]
Oh shoot, good catch, thanks! I can grab this one.
