### ISSUE TITLE
Unusable "See all versions" for themes

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3265]
Steps to reproduce:
1. Load details page for a theme i.e. https://addons.allizom.org/en-US/firefox/addon/summer-ladybug/
2. Observe "More information" section

Expected results:
There is no "See all versions" link for themes.

Actual results:
There is a "See all versions" link fro themes that redirects to an extension empty "version history" page.

Notes/Issues:
Verified on AMO-stage FF55/FF58(Win 7, Android 7.2.1).
Video for this issue:
![all vrs](https://user-images.githubusercontent.com/15685960/30954791-2de97ccc-a43a-11e7-8794-0371026ceb19.gif)

**Comment by tofumatt** [comment]
The fix here is to not show that link on themes, which seemingly do not have a version history.

**Comment by tofumatt** [comment]
Because themes don't have a version we should also omit the "version" info on the More Information card–it's always "0".

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Not version information is listed in themes details page.
Postfix screenshot:
![no_vers](https://user-images.githubusercontent.com/15685960/31116206-db993c44-a82d-11e7-8282-1b319c769528.png)
