### ISSUE TITLE
Add-ons incompatible with your platform look installable

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3266]
Steps to reproduce:
1. Load details page for an add-on that is not compatible with your platform i.e. https://addons.allizom.org/en-US/firefox/addon/webext-no-platf/
2. See the installation button

Expected results:
The install button is disabled. A red banner saying that the add-on is not compatible with your platform is displayed.

Actual results:
No banner regarding the add-on platform incompatibility. Install button is enabled. At click the switch is moved but the color is not turned to green. Add-on is not installed.

Notes/Issues:
Verified on AMO-stage FF55(Win 7). Issue is also reproducing on -dev.
- refreshing the page will put the switch button in its correct position.
Screenshot for this issue:
![noplatform](https://user-images.githubusercontent.com/15685960/30956918-5a7c15f4-a441-11e7-8cc6-8dff980f60ad.png)

**Comment by tofumatt** [comment]
@kumar303, I wonder if this is related to the new platform install feature?

- Matthew Riley MacPherson (sent from mobile)

**Comment by ValentinaPC** [comment]
@muffinresearch 👍 
- example: https://addons.allizom.org/en-US/developers/addon/webext-no-platf/versions
- platforms - anything beside the platform you are using, in my case: Linux and Mac
![2017-10-02_0944](https://user-images.githubusercontent.com/15685960/31066558-737fa79c-a756-11e7-8fa3-2f50e308105a.png)

**Comment by kumar303** [comment]
> I wonder if this is related to the new platform install feature?

Yes, sort of. What's happening here is that no install URL exists for the add-on since it doesn't support the platform. However, why did the code even get that far.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshot:
![no_plat](https://user-images.githubusercontent.com/15685960/31435255-a10693f0-ae87-11e7-8b6e-cf286d7a385e.png)
