### ISSUE TITLE
404 initial render for out of range pagination has no content

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3273]
The first render of a 404 page for **out of range pagination** shows a blank page:

![ssr-404](https://user-images.githubusercontent.com/1514/31008425-ff5b2b36-a4fb-11e7-99aa-bfc3bb3b7f86.gif)

## STR:
URL: https://addons.mozilla.org/en-US/firefox/addon/transparent-standalone-imag/reviews/?page=3

At time of  filing this is Page 3 of 2 pages.

## What happens: 

Looks like the right UI is shown when the JS kicks in which makes this a low priority fix.

##  What should happen

I'd expect a 404 to be the initial render. 
Note: Navigating to this URL shouldn't be possible by default so this is minor in terms of impact.

**Comment by tofumatt** [comment]
That sends a 404 HTTP code though, so that's bad for SEO.

**Comment by muffinresearch** [comment]
> That sends a 404 HTTP code though, so that's bad for SEO.

It should be a 404 though since that resource/page doesn't exist

**Comment by tofumatt** [comment]
Ohhh wait I misread the bug. Yeah, I understand now. My bad.

Matthew Riley MacPherson (sent from mobile)

**Comment by ValentinaPC** [comment]
Verified this as fixed using AMO-dev FF56(Win 7).
I made a search, navigate to last page and forced a next page by typing a number in the URL.
As a result a 404 page was rendered directly. 
Postfix video:
![404-no](https://user-images.githubusercontent.com/15685960/32781089-5f92c72e-c94c-11e7-8fe9-0c674e0d413a.gif)
