### ISSUE TITLE
Add far futures expires to static content for the new frontend.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3274]
From looking at https://www.webpagetest.org/performance_optimization.php?test=170927_7D_c174dc90ef600bdd9247e31192a3adf3&run=1#cache_static_content there's some easy changes we can make to improve our perf scores.

Here's the specific bit we're interested in:

```
Leverage browser caching of static assets: 54/100

FAILED - (No max-age or expires) - https://addons.mozilla.org/favicon.ico?v=1
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/amo-e5a42058f1500c4581e317152d4778a7.css
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/amo-6fba0981b0db8c8231a7.js
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/af42317212d492ac0f5ffabd918b8493.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/979a13914c3398f40c3114ead422ed41.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/0eff19a04ae3b96909f34d747d538642.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/a1ea7f348ffcb1af730d8bb90d6c7792.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/2b8fee7c129fcad1c9014f69ccddc4a5.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/a4b5655f2fdbe07f1fe26d5a77ab79a9.woff2
FAILED - (No max-age or expires) - https://addons.mozilla.org/__cspreport__
FAILED - (No max-age or expires) - https://addons.mozilla.org/api/v3/addons/search/?app=firefox&author=Wladimir-Palant&page_size=7&sort=hotness&type=extension&lang=en-US
FAILED - (No max-age or expires) - https://addons.mozilla.org/__cspreport__
FAILED - (18.0 minutes) - https://www.google-analytics.com/analytics.js
WARNING - (2.0 days) - http://ocsp.digicert.com/
WARNING - (2.0 days) - http://ocsp.digicert.com/
```

There's room for  a few easy changes.

* [x] The JS, CSS and woff2 files should have far-futures expires headers. The bundling will change the URL to cause a request so a date in the future e.g. +10years should be good. @bqbn would you be able to make this change to our origin nginx?

## Other issues filed elsewhere

The favicon is currently going to redirect. We should look to fix this by changing the URL to point to the right CDN directly (or alternatively the redirection should be made cacheable) the first option is probably better since it's explicit. It should also be verified that the final resource response has far-futures expires. https://github.com/mozilla/addons-frontend/issues/3275. 

Lastly we could possibly do something on the APIs responses to make them more cacheable - I'd be interested in thoughts on what a sane value for that would be or if we'd be better to stick to conditional requests instead to avoid stale content for any length of time. This might also be something that would be different depending on what part of the API is being called - we would need to make these changes in addons-server - See https://github.com/mozilla/addons-server/issues/6544 for the discussion around that.

**Comment by muffinresearch** [comment]
Assigning to @bqbn for the expires headers on the statics.

**Comment by bqbn** [comment]
PR https://github.com/mozilla-services/cloudops-deployment/pull/1195 submitted for the first item.

**Comment by bqbn** [comment]
The change is in -stage now. Please verify.

**Comment by bqbn** [comment]
@muffinresearch the change related to Expires header went out to -prod today. I spot checked a couple files that were built and uploaded by today's push, and they look OK. For example,

```
$ curl -Is https://addons-amo.cdn.mozilla.net/58bf65077b5c26c708a53e4e63cc55e5.woff2 |egrep '^HTTP|^Expires'
HTTP/1.1 200 OK
Expires: Tue, 05 Oct 2027 17:52:47 GMT
```

Thanks!

**Comment by mstriemer** [comment]
I took a look at a [webpagetest](https://www.webpagetest.org/performance_optimization.php?test=171030_BC_1417a185fc59541c9c744ee7507563c8&run=3#first_byte_time) today as well. It looks like the fonts don't have an Expires header right now and the initial HTML file isn't being compressed.

```
FAILED - (158.0 KB, compressed = 29.7 KB - savings of 128.4 KB) - https://addons.mozilla.org/en-US/android/
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/af42317212d492ac0f5ffabd918b8493.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/979a13914c3398f40c3114ead422ed41.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/a1ea7f348ffcb1af730d8bb90d6c7792.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/0eff19a04ae3b96909f34d747d538642.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/668362de763a7132b42ce73dc1eabb74.woff2
FAILED - (No max-age or expires) - https://addons-amo.cdn.mozilla.net/5cf854f3d1c050a8382d35770855ffd5.woff2
```

If you look at the [waterfall](https://www.webpagetest.org/result/171030_BC_1417a185fc59541c9c744ee7507563c8/2/details/#waterfall_view_step1) there's also about a second between the initial request for the stylesheets and the request for the JS. I'm guessing this is because it takes some time to parse the HTML document and hit the script tag at the end. There could be a minimal speed up from moving that script to the top and using async, see #1574.

**Comment by muffinresearch** [comment]
@bqbn ^

**Comment by bqbn** [comment]
When I curl the files directly, it does come back with the Expire header. For example, so I wonder if it's an issue with the webpagetest tool, its configuration, or not.

```
$ curl -I https://addons-amo.cdn.mozilla.net/a1ea7f348ffcb1af730d8bb90d6c7792.woff2
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
Content-Length: 140452
Connection: keep-alive
Date: Tue, 31 Oct 2017 21:22:41 GMT
Last-Modified: Thu, 26 Oct 2017 16:31:19 GMT
ETag: "a1ea7f348ffcb1af730d8bb90d6c7792"
Expires: Tue, 26 Oct 2027 16:31:16 GMT
x-amz-version-id: E.b36tqKwW7OiJSx88wFGxBhG2m.uQMu
Accept-Ranges: bytes
Server: AmazonS3
X-Cache: Miss from cloudfront
Via: 1.1 49a20f9e65ba305141854762073c3102.cloudfront.net (CloudFront)
X-Amz-Cf-Id: VHyx9BFcRGN29CSbxjgQKz06pd8sEAgtVv09qGghLivuAebX-hwdeQ==
```

As for the initial page, does the application gzip it according to the Accept-Encoding request header at all? or does it ignore the Accept-Encoding request header, and always depend on Nginx to do the gzip?

**Comment by muffinresearch** [comment]
@bqbn, I think if these fonts are unchanged we might still have ones in the edge cache with different headers because when I looked at this before I saw the same thing (although at that point the headers had just been added. The difference in webpagetest was that it showed a hit on cloudfront.

I think we might need to purge statics from the CDN to get the change seen by webpagetest.

**Comment by bqbn** [comment]
@muffinresearch I thought the file names are different each release (i.e. each build). Is that not the case (they look like random alphanumeric string to me)?

**Comment by muffinresearch** [comment]
@bqbn the filename hashing is based on the content. So you only get a new filename if the content has changed. This would explain why the fonts are the only thing showing up as not having expires because these won't change once added.

**Comment by bqbn** [comment]
I invalidated *.woff2 files in the cache and then re-run the above curl command. This time I got both a cache hit and the Expires header.

```
$ curl -I https://addons-amo.cdn.mozilla.net/a1ea7f348ffcb1af730d8bb90d6c7792.woff2
HTTP/1.1 200 OK
Content-Type: binary/octet-stream
Content-Length: 140452
Connection: keep-alive
Date: Mon, 06 Nov 2017 22:19:13 GMT
Last-Modified: Thu, 02 Nov 2017 16:17:48 GMT
ETag: "a1ea7f348ffcb1af730d8bb90d6c7792"
Expires: Tue, 02 Nov 2027 16:17:46 GMT
x-amz-version-id: mB9RoUYXhIF024x5XNH9TvEX0E4bjtAo
Accept-Ranges: bytes
Server: AmazonS3
Age: 19
X-Cache: Hit from cloudfront
Via: 1.1 641a0f932299b827b56d2560405082d5.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 5_u0ScCSALdic13-BjYBfU1sTFXQqhuwwWvQnKnpmoaTWr6LYJ3lew==
```

**Comment by muffinresearch** [comment]
Thanks @bqbn

**Comment by ValentinaPC** [comment]
@muffinresearch : what should we check here? Can you provide some STRs?

**Comment by muffinresearch** [comment]
@ValentinaPC sorry I missed the `qa: not needed` label.

**Comment by ValentinaPC** [comment]
Not a pb! Thanks!
