### ISSUE TITLE
Update the favicon urls to directly point to the CDN

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3275]
Refs: https://github.com/mozilla/addons-frontend/issues/3274

Hitting /favicon.ico  currently redirects to the CDN for each deployed environment.

This should be fixed by setting the url to point to the CDN relevant to each deployment.

PROD: https://addons.cdn.mozilla.net/favicon.ico
STAGE: https://addons-stage-cdn.allizom.org/favicon.ico
DEV:  https://addons-dev-cdn.allizom.org/favicon.ico

Since we'll be changing the host, we can drop the manual cache-busting query string param.

**Comment by eviljeff** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 
mentor @muffinresearch

**Comment by PhillypHenning** [comment]
Hey, could I work on this issue?

**Comment by tofumatt** [comment]
> Since we'll be changing the host, we can drop the manual cache-busting query string param.

Somewhat related: we should really have a helper that does that for us. But that's a separate bug 😄. Maybe there's some node utility that does it already?

**Comment by tofumatt** [comment]
@PhillypHenning Feel free to work on it, the CDN hosts are actually in the config so you can use the `config` library to get at them rather than hard-coding them.

**Comment by PhillypHenning** [comment]
Hey @tofumatt I've found the library that you mentioned.. but I'm kinda lost to what it is exactly that needs to be changed. 
What does @muffinresearch mean when he says 'manual cache-busting query string param' I feel like this is the part of the puzzle I'm misunderstanding..

**Comment by aagandhi1** [comment]
Hey @muffineresearch I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by muffinresearch** [comment]
> What does @muffinresearch mean when he says 'manual cache-busting query string param' I feel like this is the part of the puzzle I'm misunderstanding..

I mean the `?v=1` here: https://github.com/mozilla/addons-frontend/blob/be7e98e5d4588e60168aa9c5c46d28ca37c3e069/src/core/containers/ServerHtml.js#L94

> Hey @muffineresearch I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course. If no one else is currently working on it, I'd like to give it a try.

@aagandhi1 looks like @PhillypHenning is already planning to work on this.

**Comment by muffinresearch** [comment]
> Somewhat related: we should really have a helper that does that for us. But that's a separate bug 😄. Maybe there's some node utility that does it already?

Yeah webpack does that, but this is a weird case since it's a static file not handled by webpack currently.

**Comment by PhillypHenning** [comment]
Hey @muffinresearch I'm just getting rid of the static string and adding the cdnProd const we are switching to correct?

**Comment by caitmuenster** [comment]
Hey @phillyphenning, @muffinresearch is out traveling this week and it might take him a few days to respond. Hang in there -- he'll get to this when he gets a minute!

**Comment by muffinresearch** [comment]
@PhillypHenning sorry for slow reply, I had issues seeing mentions on github which I've now fixed with a better email filter.

> Hey @muffinresearch I'm just getting rid of the static string and adding the cdnProd const we are switching to correct?

Yep, that's correct.

**Comment by caitmuenster** [comment]
Hey @phillyphenning, are you still interested in working on this bug?

**Comment by anweshknayak** [comment]
Can I take this up ?
