### ISSUE TITLE
Refactor report abuse form to use DismissibleTextForm

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3279]
Part of the report abuse form was extracted into a reusable component. It landed in https://github.com/mozilla/addons-frontend/issues/3277

The [`ReportAbuseButton`](https://github.com/mozilla/addons-frontend/blob/9366b4b6856dbc99371f3aa1f9e80ec113952271/src/amo/components/ReportAbuseButton/index.js) component should now use [`DismissibleTextForm`](https://github.com/mozilla/addons-frontend/blob/9366b4b6856dbc99371f3aa1f9e80ec113952271/src/ui/components/DismissibleTextForm/index.js). Take a look at [`ReportUserAbuse`](https://github.com/mozilla/addons-frontend/blob/9366b4b6856dbc99371f3aa1f9e80ec113952271/src/amo/components/ReportUserAbuse/index.js) for an example of how to do the conversion.

For QA:
- go to an add-on detail page
- click Report Abuse
- make sure the abuse report form still works

**Comment by willdurand** [comment]
Bumping priority because other components use auto-save, so it'd be nice to have auto-save for that too.

**Comment by kumar303** [comment]
Yes, they were designed at different times. I would suggest making it look consistent with 'report user abuse' because that one uses newer button styles.
