### ISSUE TITLE
Work out a different way to separate dev/stage/production wrt NODE_ENV

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#328]
Currently we're using `NODE_ENV` to determine `stage`/`dev` or `production` the problem with that is most frontend tools think of NODE_ENV as either `production` or not. 

The problem this causes is that `dev` and `stage` are still running react in development mode for example.

 We need to either change the basis on which the config is determined or just use the DefinePlugin in webpack to make `NODE_ENV === 'production'` when the server NODE_ENV is `stage`/`dev` or `production`.

**Comment by mstriemer** [comment]
I updated the config so we don't need to compare against `'development'` all over, maybe something like that could help. I guess we need a way to load the different environment configs still which I think was running off of `NODE_ENV`.

**Comment by mstriemer** [comment]
https://github.com/mstriemer/addons-frontend/blob/logging-182/config/default.js#L27-L28

**Comment by muffinresearch** [comment]
Cool it'll be nice to get rid of this: https://github.com/mozilla/addons-frontend/blob/master/src/core/server/base.js#L22 

One thought is since webpack has dev or production configs we can probably just always assume built files should have the process.env.NODE_ENV set to production and dead code elimination will do the right thing.
