### ISSUE TITLE
Add More Section to header

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3281]
Turns out the UX of having the "Extensions" link in the header also be a dropdown was quite bad and I've opted to return to the old "More..." link–it's in a previous mock-up.

We're going to need this for the Language Tools and Search add-ons so I'm gonna add it.

**Comment by AlexandraMoga** [comment]
Verified in FF55 (Win 10 and Android 7.0)

Postfix screenshot:
![more menu layout verified](https://user-images.githubusercontent.com/31961530/31073566-19e75062-a775-11e7-8903-8bae18156890.png)

![mobile view](https://user-images.githubusercontent.com/31961530/31073656-890d8d44-a775-11e7-8089-ff72dbce819b.png)
