### ISSUE TITLE
Extensions main page needs new copy

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#3282]
The [Extensions page on dev](https://addons-dev.allizom.org/firefox/extensions/) needs proper copy. Please REPLACE: 

Install powerful tools that make browsing faster and safer, add-ons make your browser yours.

WITH NEW COPY:

Explore powerful tools and features to customize Firefox and make it all your own.

**Comment by tofumatt** [comment]
We chatted about this in IRC and we’re actually going with:

> Explore powerful tools and features to customize Firefox and make the browser all your own.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56 (Win 7).
The text was changed in AMO homepage, but not in the Extensions homepage.
Please see screenshots from both places:
![homepage](https://user-images.githubusercontent.com/15685960/31069285-7d530634-a764-11e7-8584-942c450e0af5.png)
![ext_h](https://user-images.githubusercontent.com/15685960/31069291-8436e2f4-a764-11e7-8f4c-1e650e922000.png)

I think we should change everywhere.
Reopening.

**Comment by tofumatt** [comment]
Good point, I’ll follow this up with another patch.

- Matthew Riley MacPherson (sent from mobile)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Both pages have the same text.
Postfix screenshot:
![2017-10-03_1034](https://user-images.githubusercontent.com/15685960/31114415-a1ffc4aa-a826-11e7-8afa-b23889073355.png)
![e](https://user-images.githubusercontent.com/15685960/31114418-a462abd6-a826-11e7-827b-9372738b55d0.png)
