### ISSUE TITLE
Dev server server render is using stale code

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#33]
The server side rendering appears to be using the code that the server started with. If I start the server and then make changes I see this error on a full page refresh:

```
Warning: React attempted to reuse markup in a container but the checksum
was invalid. This generally means that you are using server rendering and the
markup generated on the server was not what the client was expecting. React
injected new markup to compensate which works but you have lost many of
the benefits of server rendering. Instead, figure out why the markup being
generated is different on the client or server:
 (client) ctid=".jeorm4yp6o"><span data-reactid=".
 (server) ctid=".jeorm4yp6o"><form class="search-f

**Comment by muffinresearch** [comment]
I think this is a non-issue. 

The server doesn't reload the code but the hot-module-reloading does. 

The server *is* still running the old code and this would be the case until the server is re-started. We could probably work around it by having express restart but I think that's probably unecessary.
