### ISSUE TITLE
[RTL] 'More' menu layout appears sectioned on browser width <720

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3300]
Steps to reproduce:

1. Go to AMO homepage
2. Select a RTL language (i.e. https://addons-dev.allizom.org/fa/firefox/)
3. Change page width to <720
4.  Open the 'More' menu

Expected result:
'More' menu is displayed without any layout issues

Actual result
'More' menu  appears sectioned on the right hand side

Notes:
Tested on FF56, Win10
Reproduces also on Android device in landscape mode

![sectioned more mnu](https://user-images.githubusercontent.com/31961530/31075025-23913252-a77c-11e7-9ca4-02af5ad187a9.png)

**Comment by tsl143** [comment]
This issue has been resolved by the right translation, but it should be noted that if the text is large in any locale this issue will reoccur.
<img width="836" alt="screen shot 2017-10-07 at 10 08 04 pm" src="https://user-images.githubusercontent.com/5318732/31309939-6d7ea848-abac-11e7-805e-25a7b9ed67e5.png">

**Comment by tsl143** [comment]
The issue mentioned is already fixed by translation, but this PR takes care of any long name translations of any `DropdownMenuItem`

**Comment by AlexandraMoga** [comment]
Re-opening this as the issue can still be reproduced both for RTL and for regular orientation

https://addons-dev.allizom.org/ko/firefox/
![image](https://user-images.githubusercontent.com/31961530/31328430-c88540bc-acdd-11e7-98cc-ebe2b5488467.png)

https://addons-dev.allizom.org/ur/firefox/
![image](https://user-images.githubusercontent.com/31961530/31328448-e9897ce2-acdd-11e7-9abf-921c2b18a31e.png)

**Comment by willdurand** [comment]
Looks fixed, I cannot reproduce anymore.

**Comment by AlexandraMoga** [comment]
I'm not reproducing either on desktop or mobile:

![image](https://user-images.githubusercontent.com/31961530/60712191-1ebcc100-9f1f-11e9-9b44-f296f7e79539.png)
