### ISSUE TITLE
"More..." option is moving while using up/down arrows from the keyboard

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3302]
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Navigate to "More..." using `tab` option from the keyboard
3. When on it, tap up/down arrows from the keyboard

Expected results:
Page is moved up/down.

Actual results:
"More..." menu option is moved.

Notes/Issues:
- another thing is that going from Themes option to More..., requires 2 "tabs".
Verified on AMO-dev FF56 (Win 7) 
Please see video:
![more](https://user-images.githubusercontent.com/15685960/31075496-7df5113a-a77e-11e7-9d7f-e4543e5a8992.gif)

**Comment by muffinresearch** [comment]
> another thing is that going from Themes option to More..., requires 2 "tabs".

That is related to https://github.com/mozilla/addons-frontend/issues/3110 and should be fixed by the solution to that.

**Comment by muffinresearch** [comment]
I can't repro this any more.
