### ISSUE TITLE
Developer Hub and Account Name options are not aligned

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3303]
Steps to reproduce:

1. Go to AMO homepage (i.e https://addons-dev.allizom.org/en-US/firefox/)
2. In the page header, observe the Developer Hub and Account Name links alignment

Expected result:
 Developer Hub and Account Name links are aligned

Actual result:
There is a small difference between the two links alignment

Notes: observed on FF56, Win 10

Screenshot:
![allignment issue](https://user-images.githubusercontent.com/31961530/31076332-44ba147a-a782-11e7-88ef-4ae4a5402b84.png)

**Comment by willdurand** [comment]
Looks like this "Developer" link has moved for some reasons..

<img width="408" alt="screen shot 2017-10-02 at 14 13 11" src="https://user-images.githubusercontent.com/217628/31076730-e654cdfe-a77b-11e7-92a3-d7b404617399.png">

**Comment by naperkovskiy** [comment]
I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by tsl143** [comment]
@willdurand This is caused due to removal of `vertical-align: top` from `.Header-button`
https://github.com/mozilla/addons-frontend/commit/09606b62c9ba14722bc4de83d7624413d2bc5a42#diff-227870732fbf4923ff3b0f5488402c62L114

**Comment by willdurand** [comment]
@tsl143 good catch, want to submit a patch?

**Comment by tsl143** [comment]
@willdurand , here you go.

**Comment by AlexandraMoga** [comment]
Verified as fixed in FF56 (Win10 and Android 7.0)

Postfix screenshot:

![image](https://user-images.githubusercontent.com/31961530/31379977-9e768ebc-adb8-11e7-8ba6-63a349f9b609.png)
