### ISSUE TITLE
getFakeI18nInst is a weird name

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3304]
We should rename `getFakeI18nInst` because it's weird to remember, import, and is clearly from a bygone era–the great UNIX vowel shortage of 1970.

I think `fakeI18n()` would be fine.

**Comment by muffinresearch** [comment]
> is clearly from a bygone era–the great UNIX vowel shortage of 1970.

Come on, I'm not quite that old 😆
