### ISSUE TITLE
Featured add-ons should be compatible with user browser

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3307]
The current implementation of the featured add-ons retrieval relies on the [Featured API endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#featured). This is not good since we try not to show incompatible add-ons to the users. This endpoint has no notion of `appversion` parameter for instance.

The featured add-ons retrieval does not rely on the Search API but ideally we should do that. I have filled an issue on addons-server to ask for a new `sort` type (random) so that it mimics the existing Featured API endpoint: https://github.com/mozilla/addons-server/issues/6560.

This would help us to always retrieve compatible featured add-ons.

Once we have the API for that, we could remove the code to retrieve the featured add-ons (in `core/api/index`) and use the regular Search API (in `core/api/search`).

**Comment by willdurand** [comment]
API is ready now! https://github.com/mozilla/addons-server/issues/6560

**Comment by ValentinaPC** [comment]
All listed add-ons from More Featured Extensions page, are compatible with used browser version.
Verified this on AMO-dev FF56(Win 7).
Is there anything else we should check here? Thanks!

**Comment by willdurand** [comment]
> Is there anything else we should check here? Thanks!

@ValentinaPC no, it is enough :)

**Comment by ValentinaPC** [comment]
Thanks for you answer! Marking this verified-fixed.
