### ISSUE TITLE
Add most popular extensions shelf to the homepage [1/5]

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3308]
Breaking this out from #3152

Add a shelf  of content  on the homepage to  feature  "Most Popular" content.

https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#heading=h.mnb8tk6s8el0

Not sure if there's specific UX for this see below for what's in the mock - I'd suggest starting with the same as the default shelf and then we can specialize the look and feel separately.

**NOTE: We already have this content on the extensions landing page:**

<img width="1433" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31087636-aaa8aa4a-a795-11e7-890e-752d0c7cf3e1.png">

Order: based on the doc  this is the first  shelf under the carousel.

**Comment by muffinresearch** [comment]
Added  needs: ux to get explicit visual input but that shouldn't block  the first cut of getting the data hooked up.

**Comment by ValentinaPC** [comment]
@willdurand 
Verified this on AMO-dev FF56(Win 7)
A collection was added to homepage, but does not contains popular extensions.
Please see screenshot:
![2017-10-06_1119](https://user-images.githubusercontent.com/15685960/31269228-3591d8b2-aa88-11e7-9bee-0123e6aaea10.png)

**Comment by vcarciu** [comment]
The collection contains now the most popular extensions:
![morepopular](https://user-images.githubusercontent.com/1583842/31771540-2c0486ac-b4e5-11e7-98f8-7a2f244cc3e0.png)

Verified this on AMO-dev FF56(Win 7)
