### ISSUE TITLE
Add collection based shelf to Homepage [2/5]

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3309]
Breaking this out from #3152

Add a shelf of content on the homepage to feature a defined collection.

https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#heading=h.mky7j18wsuga

For release the collection is going to be called: "Change your tabs" and points to  

https://addons.mozilla.org/firefox/collections/mozilla/change-up-your-tabs/

Not sure if there's specific UX for this  - I'd suggest starting with the same as the default shelf and  then we can specialize the look and feel separately.

E.g see this look and feel for  Most Popular content: 

<img width="1433" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31087670-d24c2040-a795-11e7-8183-c19f2764d663.png">

Order - based  on the doc this is shelf no.2

**Comment by muffinresearch** [comment]
Marked as UX because we  could use explicit UX for all the homepage shelves.

**Comment by willdurand** [comment]
@muffinresearch this collection is not available in dev or stage, so don't know how QA will be able to test it. How can we add it to those environments?

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev and AMO-stage using FF56(Win 7, Android 7.2.1).
Postfix screenshot:
![2017-10-09_1356](https://user-images.githubusercontent.com/15685960/31335262-74ccacb8-acfa-11e7-8c4b-d5a67c433b24.png)
![2017-10-09_1402](https://user-images.githubusercontent.com/15685960/31335280-84240c10-acfa-11e7-89a4-3f951c83f0af.png)

**Comment by willdurand** [comment]
@ValentinaPC sorry, the issue description is a bit misleading. You should look for a second shelf. The one you highlight here is the first one (see #3308).

**Comment by ValentinaPC** [comment]
The collection is listed on AMO-dev FF56 (Win 7), but not on Android.
But, if we click on "Browse this collection" link and refresh the loaded page, user is redirected to the old AMO coll page.
Please see video:
![refresh](https://user-images.githubusercontent.com/15685960/31336395-5abbe0f0-acff-11e7-8379-51c884c04505.gif)

Reopening.

**Comment by willdurand** [comment]
ah right. I think this is an Nginx (configuration) issue.

**Comment by willdurand** [comment]
This is now available in dev.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Postfix video:
![coll](https://user-images.githubusercontent.com/15685960/31371013-7109677c-ad97-11e7-9e56-6fa35936b081.gif)
