### ISSUE TITLE
Add curated link "subject shelf" to homepage [3/5]

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3310]
Breaking out from #3152 

https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#heading=h.bcmv6y37ccp

This  one is a hard-coded curated collection. 

This one needs specialised UX since it's a hard-coded list of links to a collection  - see the doc for the content. 

This is what is known as a subject shelf - this requires iconography.

Order: this is shelf no. 3

**Comment by willdurand** [comment]
Hi @pwalm, we need you here :)

**Comment by pwalm** [comment]
Icons! More icons! I think some of the Subject Icons will cover these, but i'll design options for the theme icons this week.

**Comment by pwalm** [comment]
Subject shelf icons in situ:
<img width="1175" alt="screen shot 2017-10-10 at 3 04 51 pm" src="https://user-images.githubusercontent.com/6797635/31413058-71b13ba2-adcc-11e7-8ac7-36b0abbed187.png">

Only had to create two new icons: "screenshots" and "wild". SVGs of those files are [here](https://github.com/mozilla/addons-frontend/tree/master/assets/icons/subjects).

**Comment by willdurand** [comment]
Cool, thanks!

**Comment by devaneymoz** [comment]
@pwalm your [Subject Shelf icon designs](https://github.com/mozilla/addons-frontend/tree/master/assets/icons/subjects) are looking great! 

Just so we're in sync on Subject Shelf icons for launch, I had these four specifically noted because they will lead to strong curated collections by November: 
- [Ad blockers](https://addons.mozilla.org/firefox/collections/mozilla/ad-blockers/)
- [Password Managers](https://addons.mozilla.org/firefox/collections/mozilla/password-managers/)
- [Bookmarks](https://addons.mozilla.org/firefox/collections/mozilla/bookmark-managers/)
- [Watching Videos](https://addons.mozilla.org/firefox/collections/mozilla/watching-videos/)

... however if UX calls for more than four Subject Shelf icons to be displayed on the Homepage, please let me know asap so I can make programming adjustments, additions.

**Comment by willdurand** [comment]
Hi @pwalm and @devaneymoz, here is how it looks so far:

<img width="1392" alt="screen shot 2017-10-12 at 14 36 09" src="https://user-images.githubusercontent.com/217628/31496208-bb5099bc-af5a-11e7-8561-a14312d94d5f.png">

I find it a bit too empty... Either we should have some description below the "I'm interested in..." or more subjects, or both. Let me know :)

**Comment by willdurand** [comment]
Also, I had to color some icons myself. Let me know if colors are okay too!

**Comment by willdurand** [comment]
This is a bit better, but not quite right:

<img width="1392" alt="screen shot 2017-10-12 at 14 47 40" src="https://user-images.githubusercontent.com/217628/31496609-5bc540c2-af5c-11e7-976e-c91c48bb9981.png">

**Comment by muffinresearch** [comment]
Would it make sense to re-purpose the old category icon shelves since that looks really close to the screenshot in pwalms comments here: https://github.com/mozilla/addons-frontend/issues/3310#issuecomment-335623033 ?

**Comment by willdurand** [comment]
@muffinresearch that's what I did in the first place, cf. my first screenshot. That's also why I ask for either a description or more collections (i.e. more icons to display). Without that, it looks just weird, and that's why I slightly changed the UI in the second screenshot. It feels less weird.

**Comment by muffinresearch** [comment]
Yep, I agree that 4 icons looks too sparse.

I'm thinking re-using the category icon approach might be easiest albeit we'll need the additional content.

**Comment by willdurand** [comment]
Indeed. This shelf only shows collections, so I would not add categories here. With one or two more curated collections, that would be better I guess.

**Comment by muffinresearch** [comment]
@willdurand yep I'm referring only to the look and feel - *not* the data when I'm talking about the old category content.

**Comment by willdurand** [comment]
@muffinresearch ah yes yes, we are on the same page.

**Comment by devaneymoz** [comment]
Agree it looks sparse. 

I'm unsure if @pwalm has the time to create new icons that will fill out the space better. Perhaps we simply add more Subject Shelf icons to the page? If this is the best course I need to know soon so I can start prepping the content in other Subject Shelf collections. 

I'd prefer not to add copy just to fill space. And the idea with "I'm interested in..." is to lead naturally to the titles of the collections. "I'm interested in... ad blocking"

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7, Android 7.2.1).
The curated collection was added to homepage and looks very nice, but each option inside it is returning a 404 page.
Please see video:
![shelf](https://user-images.githubusercontent.com/15685960/31534868-6af0d778-b001-11e7-8a93-6f2cd8e8f7c2.gif)

Reopening.

**Comment by ValentinaPC** [comment]
I saw that @willdurand added an issue for those collections (https://github.com/mozilla/addons-frontend/issues/3463), we can mark this issue verified.
