### ISSUE TITLE
Create featured themes shelf on the homepage [4/5]

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3311]
Splitting this out from:  #3152 

https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#heading=h.fw1kgamyk5ju

I'd suggest following the existing shelf look and feel so we can update them universally later.

**Note: this data is already on the themes landing page:**

<img width="1458" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31087567-6a770962-a795-11e7-9648-a65d3dac8bce.png">

Order: shelf 4th based on the doc.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
New shelf with featured themes was added in homepage.
Postfix video:
![ft](https://user-images.githubusercontent.com/15685960/31372441-675bbf66-ad9e-11e7-881d-2e0acb619854.gif)
