### ISSUE TITLE
Add  Up & Coming shelf to the homepage [5/5]

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3312]
Split out from #3152

https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#heading=h.rf8x4i1of5cm

Should follow existing shelf  styling so we  can update all later: 

Here's an example of that for most popular data:

<img width="1433" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31087889-ac8a9a0c-a796-11e7-9c9e-e52c506b88ed.png">

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev FF56 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/31502607-450bd4da-af76-11e7-93b6-0d435a65220d.png)
![image](https://user-images.githubusercontent.com/31961530/31502656-680d4e14-af76-11e7-91fb-0f3a3898f1ad.png)
