### ISSUE TITLE
Switch -dev to running the new frontend pages by default.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3314]
It'll be a good idea as soon as possible to switch -dev to start loading the new frontend pages by default so that anyone can easily check the progress without explicitly flipping hitting a link to set a cookie.

The cookie set to mamo=off should still work as an opt out but that should be the only way to see the legacy frontend.

This will test what we need in place from a configurations perspective. I'd imagine the bulk of this issue is going to be in the server configuration. 

Here's a  few  thoughts  on what criteria need to be met (feel free to add to them if you can think of others).

* [ ] with no mamo cookie set all UAs (inc mobile) should get the new frontend.
* [ ] with a mamo cookie set to "on" all UAs (inc mobile)  should get the new frontend.
* [ ] with a mamo cookie set to  "off" all UAs (inc mobile) should get the legacy (django) frontend. (Note: when we are ready for stage we will consider not providing this escape hatch, see #3352).
* [ ] Pages not yet provided by the new frontend should still fallback to the legacy frontend.

**Comment by bqbn** [comment]
Couple questions:

1. When you say "new frontend", do you mean the mobile site? 

2. What is the approximate timeline for the same set of rules to be applied to -stage and -prod?

**Comment by tofumatt** [comment]
Yes, the new front-end is the same as the mobile site. It now has desktop pages as well 😄 

For production the site is planned to be launched by/before Nov 14 (Firefox 57 release date). But probably before then.

Stage would be sometime in between I guess.

**Comment by muffinresearch** [comment]
> For production the site is planned to be launched by/before Nov 14 (Firefox 57 release date). But probably before then.

Planned release date is the 2nd November Push

**Comment by tofumatt** [comment]
Note: if we don't want to provide the escape hatch then we should remove it from the footer. I've filed #3352 for that.

**Comment by bqbn** [comment]
-dev now shows mobile site by default.

**Comment by ValentinaPC** [comment]
@muffinresearch: what do you mean exactly when you say "mamo cookie"?
I though "mamo coockie" means the pref "extensions.webapi.testing", but maybe I got it wrong.

**Comment by willdurand** [comment]
@ValentinaPC it is the cookie set when you click on "View mobile site" in the footer (to get the new website based on this project instead of the old one).

**Comment by ValentinaPC** [comment]
@muffinresearch : Not sure about that....because if you are right, then, how can I test the case where the cookie is "off"?

**Comment by muffinresearch** [comment]
@ValentinaPC you can test this by clicking "View classic desktop site" in the footer.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF58(Win 7).
New AMO frontend is opened by default while using -dev in a new profile.
Postfix video:
![new frontend by default](https://user-images.githubusercontent.com/15685960/32168677-418104f8-bd76-11e7-8c45-edbb2d022f36.gif)
