### ISSUE TITLE
No preview of theme in collection view

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3318]
The collection view should display a preview of the themes, currently it shows "no preview available" but this is not correct. It should display a preview of these themes for instance:

<img width="1392" alt="screen shot 2017-10-02 at 23 52 04" src="https://user-images.githubusercontent.com/217628/31101150-b44ec944-a7cc-11e7-8025-5c306b6631d5.png">

**Comment by ValentinaPC** [comment]
Is this on -dev?

**Comment by tofumatt** [comment]
We’re still waiting for the collections url routes on dev to be opened up... so the code is there but it’s inaccessible 😓
