### ISSUE TITLE
Move calls to isAllowedOrigin(url) to reducer / state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3325]
We do this a lot as a security measure:

```js
const url = isAllowedOrigin(data.theUrl) ? data.theUrl : null;
```

Let's move that logic to the reducers so that `data.theUrl` would be automatically set to `null` if it pointed to a disallowed origin.

See also: https://github.com/mozilla/addons-frontend/issues/2999 https://github.com/mozilla/addons-frontend/issues/3006

Note that CSP already mitigates against injecting images or whatever on an unexpected URL.

**Comment by bobsilverberg** [comment]
I think this code quality issue is worth keeping around.
