### ISSUE TITLE
Catch and throw errors in sagas while testing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3328]
We use a pattern like this to test sagas:

```js
sagaTester.dispatch(initialAction());

const lastExpectedAction = someAction();
await sagaTester.waitFor(lastExpectedAction.type);
```

If the saga encounters an exception, you will see something like this in the console:

```
console.warn src/amo/sagas/your-saga.js:76
  [Some information about the exception]

Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
```

It would be great if the exception were just thrown so you wouldn't have to wait for the timeout and dig through the console to find the warning.

**Comment by willdurand** [comment]
I think this issue is a duplicate of #3493, which has more information.
