### ISSUE TITLE
Update name in FxA config

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#3330]
The config for FxA is setup with the name as "Firefox Add-ons Frontend". This is what users sees when logging in with addons-frontend in production.

This string should be shortened or the frontend should be piggy backing on the addons-server config.

I don't recall exactly why we aren't using the server config, but I suspect is has to do with `skip_register_redirect` since without that a new user will land on the desktop site. Once there's a user edit page here the frontend may be able to use the server config. Alternatively, we could store that the user is logging in from the frontend in the `state` parameter rather than using a separate config.

/cc @ryanfeeley

**Comment by kumar303** [comment]
I think the ultimate goal here is to make only one entry for AMO in the [devices & apps](https://accounts.firefox.com/settings/clients) section:

<img width="635" alt="screenshot 2017-10-03 14 47 26" src="https://user-images.githubusercontent.com/55398/31145082-4bb35964-a848-11e7-9bc1-a16f467dd9ba.png">

Solving that probably means using the same FxA config for both frontend and server.

**Comment by eviljeff** [comment]
dupe of mozilla/addons/issues/489 ?

**Comment by mstriemer** [comment]
Ah, I thought I remembered something but only looked in here. I'll copy the info over there.
