### ISSUE TITLE
Randomize header content order

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3332]
Doing this as a follow-up bug, but after discussing with @devaneymoz and @pwalm, we're gonna randomize the header content by default.

**Comment by muffinresearch** [comment]
@tofumatt since this might be related to how we are going to display the content statically in https://github.com/mozilla/addons-frontend/issues/3430 I'll leave to you if you want to adapt this issue or close it.

**Comment by tofumatt** [comment]
I'll leave it open here because we'll still be randomizing the header (and I've that working in the new static one), but I want the behaviour to be documented.

**Comment by tofumatt** [comment]
I'll leave it open here because we'll still be randomizing the header (and I've that working in the new static one), but I want the behaviour to be documented.

**Comment by AlexandraMoga** [comment]
Verified as fixed on all AMO servers with FF56 (Win10 and Android 7.0)

The order of the header content changing at page refresh:
![randomization](https://user-images.githubusercontent.com/31961530/31547114-cb1f8586-b02e-11e7-8582-8af0ca85148e.gif)
