### ISSUE TITLE
Internal Server Error on addons detail page in chinese

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#3335]
First reported at https://github.com/webcompat/web-bugs/issues/10426

STR:
- Set the mamo cookie to see the new frontend
- Visit https://addons.mozilla.org/zh-TW/android/addon/ublock-origin/

Expected Result:
- You can see the detail page in chinese

Actual Result:
- You get an Internal Server Error page in chinese

Sentry traceback: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/648103/

**Comment by muffinresearch** [comment]
From a quick look at the .po file there’s some mismatched placeholders. These will need fixing. We could also look at wrapping sprintf longer term to try the English key string on a failure like this.

**Comment by tofumatt** [comment]
Oh that’s a clever idea, so we don’t have errors like this in the future.

Sad our tests didn’t catch it, I thought we ran some locale tests these days?

Matthew Riley MacPherson (sent from mobile)

**Comment by muffinresearch** [comment]
@tofumatt https://github.com/mozilla/addons-frontend/issues/3336 should fix this in terms of failing CI if things like this come in via l10n updates.

**Comment by muffinresearch** [comment]
@kumar303 until #3336 gets fixed could you look at running dennis after extraction? That will mean we'll know if something is in the tag because that gets run after tagging but before release.

**Comment by kumar303** [comment]
Ugh, that sounds like motivation enough just to do #3336. The manual extract process is getting painful.

**Comment by muffinresearch** [comment]
QA Notes: 

3 locales have issues resulting in various 500s here are examples:

* https://addons.mozilla.org/zh-TW/android/addon/ublock-origin/
* https://addons.mozilla.org/te/android/addon/ublock-origin/
* https://addons.allizom.org/he/firefox/search/?platform=mac&q=foo&type=persona

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF56 (Win 10) for the first two locales

Postfix screenshots:
![image](https://user-images.githubusercontent.com/31961530/31232280-1b8f7366-a9f2-11e7-8680-f50589fe3968.png)

![image](https://user-images.githubusercontent.com/31961530/31232318-36baeb98-a9f2-11e7-8687-941f2afefe47.png)


Note @muffinresearch :
I wasn't able to reproduce the internal server error for the third locale. Am I missing something here?

**Comment by muffinresearch** [comment]
@AlexandraMoga the fix was probably already on to stage by the time you checked.
