### ISSUE TITLE
Lint l10n translations with dennis-cmd

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-frontend#3336]
Part of https://github.com/mozilla/addons-frontend/issues/529

To avoid things like broken placeholders or other obvious problems.

* [ ] automate and document dennis-cmd installation
* [ ] Integrate dennis-cmd into linting package.json, potentially run it after `build-locales` script
* [ ] add to travis to run on every commit to catch these problems early on in the development process

**Comment by vcarciu** [comment]
Can you please add some STRs or mark the issue as "qa:not needed" ?
