### ISSUE TITLE
Unable to take screenshot of AMO

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#3337]
### Describe the problem and steps to reproduce it:
Go to AMO and take a screenshot, using Firefox Screenshots.

### What happened?
It doesn't work, stating that AMO is not a standard website.

![amo-screenshot-not-possible](https://user-images.githubusercontent.com/8145891/31172264-2a388488-a903-11e7-83b6-f085257cabf9.gif)

### What did you expect to happen?
I expected to take a screenshot of AMO.

**Comment by tofumatt** [comment]
It’s not a standard website and add-ons aren’t allowed to run on AMO.

This is by design, for security purposes.

Matthew Riley MacPherson (sent from mobile)

**Comment by designakt** [comment]
Not even extensions that are built into Firefox, like our own screenshots feature?

**Comment by tofumatt** [comment]
No, it’s built into the browser to be this way. It’s not anything we set on AMO or could enable/disable from the site if we wanted to. You’d need to get Firefox to allow only specific add-ons to run on that URL… but that’s a huge security risk if they’re compromised as they have access to mozAddonManager then.

I think the message that screenshots gives could be more helpful though, certainly, and could include a link explaining which websites won’t work and why.

But the screenshots doesn’t get any special features as far as I know to run on AMO.

**Comment by jvillalobos** [comment]
A workaround is to use the Developer Toolbar in the Developer Tools. There's a `screenshot` command you can use.
