### ISSUE TITLE
License link is not working

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3339]
Steps to reproduce:
1. Load an add-on details page i.e. https://addons.allizom.org/en-US/firefox/addon/youtube-unblocker/
2. Click on the license link

Expected results:
License page is loaded.

Actual results:
A 404 old AMO desktop page is loaded.

Notes/Issues:
- on device a 404 mobile page is loaded.
Verified on FF56(Win 7, Android 7.2.1).
Issue is reproducing on both stage and dev.
Screenshot for this issue:
![2017-10-04_1522](https://user-images.githubusercontent.com/15685960/31175381-d46ee668-a917-11e7-9e04-4de0aed7613b.png)

**Comment by tofumatt** [comment]
The license link here is getting prefixed. Should be an easy fix...

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7)
Postfix video:
![lic](https://user-images.githubusercontent.com/15685960/31213161-b10ad59c-a9ad-11e7-8f1c-2029820d98e1.gif)
