### ISSUE TITLE
Move denormalizeReview() / createInternalReview() into the reducer

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3342]
The `denormalizeReview()` function (which will get renamed to `createInternalReview()` in https://github.com/mozilla/addons-frontend/issues/3219) is called in an action creator. It is bad practice to add this kind of logic to action creators because action functions are not replayable. In other words, hypothetically, we would not be able to reproduce a user reported bug in this function. We should always move logic like this to the reducer.

**Comment by willdurand** [comment]
heh. This one is weird because we reuse the same `SET_REVIEW` action for two action creators, one being the `setReview()` and the other one `setDenormalizedReview()`...

**Comment by kumar303** [comment]
You could rename it to `setInternalReview()`. It's only in use right now by `AddonReview` to set an "in memory" review object before the API returns a real one. There is probably a better way to do that, maybe by converting that form to make better use of `setState` or maybe `setUIState`.
