### ISSUE TITLE
Carousel scrolls LTR on RTL pages

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3344]
Because of an issue with the `NukaCarousel` component we use, in RTL locales the carousel still scrolls the content left to right. The slider at the bottom is correct but the scrolling is off. This is because we force LTR on the slides to prevent them scrolling off-screen.

This seems to be a bug with the carousel. We could try to work around it or submit an upstream patch.

**Comment by muffinresearch** [comment]
Closing since we're moving to static content in https://github.com/mozilla/addons-frontend/issues/3430
