### ISSUE TITLE
Homepage carousel fails CSP

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3349]
The homepage fails to load with CSP enabled on first page load if you are loading the home page (eg. https://addons-dev.allizom.org/en-GB/firefox/). This results in the homepage looking messed up:

<img width="1286" alt="screenshot 2017-10-04 22 01 48" src="https://user-images.githubusercontent.com/90871/31199546-a56edcc8-a94f-11e7-8b71-180421af6bfb.png">

Navigate to the homepage from another page and it's fine:

<img width="1286" alt="screenshot 2017-10-04 22 02 10" src="https://user-images.githubusercontent.com/90871/31199558-b16d587e-a94f-11e7-87c2-991b265b0105.png">

This is because CSP is blocking it from loading a `<style>` tag.

Possibly related to https://github.com/FormidableLabs/nuka-carousel/issues/182. Hopefully an easy fix!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMo-dev FF56(Win 7).
Postfix video:
![csp](https://user-images.githubusercontent.com/15685960/31231139-a98303f8-a9ee-11e7-9b02-be99aa03daf6.gif)
