### ISSUE TITLE
'More Featured Themes' doesn't show theme preview

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3353]
Steps to reproduce:

1. Go to the 'Themes' tab from AMO homepage (i.e https://addons-dev.allizom.org/en-US/firefox/themes/)
2. Click on 'More featured themes'

Expected result:
A list with featured themes preview is displayed

Actual result:
The list displays "No theme preview available" error message

Notes: Reproduces on AMO dev and stage with FF56 (Win10 and Android 7.0)
Might be related to [#3318](https://github.com/mozilla/addons-frontend/issues/3318)

Example:
![image](https://user-images.githubusercontent.com/31961530/31218883-518c4f26-a9c4-11e7-9054-369287eb4e8c.png)

**Comment by willdurand** [comment]
Good catch, I missed this page in my refactoring 😞  (#3319)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev FF56 (Win10 and Android 7.0)

Postfix screenshot:

![image](https://user-images.githubusercontent.com/31961530/31270410-f0039ede-aa8c-11e7-9a3b-2f7becbecf3e.png)

**Comment by AlexandraMoga** [comment]
Note: the issue can still be reproduced on production
