### ISSUE TITLE
Carousel navigation dots are cut on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3358]
Steps to reproduce:
1. Load AMO-dev homepage on your device i.e. https://addons-dev.allizom.org/en-US/firefox/
2. Observe carousel navigation dots

Expected results:
There are no display or layout issues.

Actual results:
Navigation dots are cut.

Notes/Issues:
Verified on AMO-dev FF56(Android 7.2.1).
Screenshot for this issue:
![2017-10-05_0850](https://user-images.githubusercontent.com/15685960/31225201-a2109af0-a9d9-11e7-9447-471e6fad6b66.png)

**Comment by muffinresearch** [comment]
Since we're replacing the carousel with static content in https://github.com/mozilla/addons-frontend/issues/3430 this is now a wontfix.
