### ISSUE TITLE
Swiping through carousel options is difficult

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3359]
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Navigate through the carousel by swiping

Expected results:
Navigation its easy.

Actual results:
User has trouble in passing from an image to another without using the dots.

Notes/Issues:
- if your mouse stays in the range of the carousel, the options "get stuck" on it
- should there be some nav arrows on the sides of the carousel?
Verified on AMO-dev FF56(Win 7).
Video fro this issue:
![sw](https://user-images.githubusercontent.com/15685960/31225634-a758c79c-a9db-11e7-9241-960c9072a1a8.gif)

**Comment by willdurand** [comment]
Indeed, I also noticed this but was not sure if it was not only me...

**Comment by muffinresearch** [comment]
Closing this since we're moving to static content instead: https://github.com/mozilla/addons-frontend/issues/3430
