### ISSUE TITLE
i18n `getDirection()` helper should rely on constants

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3362]
In `core/i18n/utils`, the `getDirection()` function should not use hardcoded values for `ltr` and `rtl` because then we need to test with the hardcoded values when using this helper:

https://github.com/mozilla/addons-frontend/blob/92b83273ba0c86ab750e92faf1c8e5a50c033aa8/src/core/i18n/utils.js#L104-L106

We should rather have `LTR` and `RTL` as constants, and use them. When working on this issue, please "grep" for `'rtl'`, `'ltr'` and `getDirection()` and update the code accordingly.

**Comment by PhillypHenning** [comment]
Can I have this issue please :)

**Comment by willdurand** [comment]
@PhillypHenning sure! Do you know how to start? You have to install the application locally first, and you should run the test suite before anything else (and all tests must pass).

**Comment by PhillypHenning** [comment]
@willdurand Hey could we throw the hacktober label on this please?

**Comment by PhillypHenning** [comment]
Thanks! I think I'm ready to submit the fix, I've ran yarn test-once;
![image](https://user-images.githubusercontent.com/16713447/31255764-8cc434f4-a9fc-11e7-82d7-5472659d31e4.png)
Is there a process I should follow?

**Comment by tsl143** [comment]
> Is there a process I should follow?

@PhillypHenning , try running `yarn lint` too, if it passes please raise the PR.

**Comment by willdurand** [comment]
@PhillypHenning as @tsl143 said, be sure to run the linter too, then you can open a PR where discussion will happen. I'll be happy to review your fix!

**Comment by PhillypHenning** [comment]
Hey @willdurand I've ran the linter and it passed as well! I'm getting an error when trying to push though.. 
![image](https://user-images.githubusercontent.com/16713447/31308946-ccb0f358-ab4c-11e7-91f3-c3d9c1a86a94.png)

**Comment by tofumatt** [comment]
You’ll need to push to your own fork; you don’t have access to the Mozilla repo, that’s what the error is saying :-)

There’s GitHub help docs on forking a repo here: https://help.github.com/articles/fork-a-repo/

**Comment by willdurand** [comment]
thanks @championshuttler!
