### ISSUE TITLE
Carouesl assets are gigantic

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3366]
I naively pulled and committed very large images to the carousel component. We should compress them–@muffinresearch pointed out right now they're like 18MB.

![shame-cube](https://user-images.githubusercontent.com/90871/31239183-2a266d88-a9f4-11e7-9a23-a5de1035f978.gif)

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this or the label "qa: not needed". Thanks!
