### ISSUE TITLE
Allow developers to edit their reply to a review

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3368]
### Describe the problem and steps to reproduce it:

* Sign in as the developer of an add-on
* Go to your add-on detail page
* Go to the review page
* Reply to one of the reviews
* Try to edit your reply after you've posted it

### What happened?

There is no edit link

### What did you expect to happen?

You should be able to edit your reply just like editing a normal review

### Anything else we should know?

When implementing https://github.com/mozilla/addons-frontend/issues/2773 this required some extra effort so I wanted to postpone the feature.

**Comment by vcarciu** [comment]
Verified as fixed : 
![updatereply](https://user-images.githubusercontent.com/1583842/31550519-4c429224-b03a-11e7-9fa0-84936901d55d.gif)

Also, verified on device and replies are correctly edited.
