### ISSUE TITLE
Change style of reply-to-review form

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3370]
To see this UI element:
* Sign in as a developer of an add-on
* Go to the detail page of your add-on
* Click to read all reviews
* Click Reply to this review
* Enter some text

This issue is to make UI changes based on the latest mocks, shown in Sketch and below:

<img width="1463" alt="screenshot 2017-10-05 16 33 44" src="https://user-images.githubusercontent.com/55398/31253556-0165a46c-a9eb-11e7-8871-95b0f317d152.png">

**Comment by ValentinaPC** [comment]
@kumar303: according to mocks, it should be a preview reply option, but I cannot see it. It was removed?

**Comment by tofumatt** [comment]
Yes, the Pull request mentioned it I think but maybe not the issue, whoops!

The preview was dropped for this issue but should be implemented later, if there isn’t an issue for it it should be filed.

- Matthew Riley MacPherson (sent from mobile)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Reply to this review option is working as expected. Checked also using a RTL lang.
Postfix screenshots:
![2017-10-10_1305](https://user-images.githubusercontent.com/15685960/31381114-41eaebd0-adbc-11e7-874d-98b326ac115b.png)
![2017-10-10_1306](https://user-images.githubusercontent.com/15685960/31381117-46369946-adbc-11e7-8220-10c199302d91.png)
