### ISSUE TITLE
Don't rely on empty arrays as being unloaded

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3372]
As noted in https://github.com/mozilla/addons-frontend/pull/3365#discussion_r143069482, we sometimes treat an empty array as one that hasn't loaded yet, but strictly speaking this isn't true. We could get a legitimate empty response from the server that would keep us constantly dispatching.

We should follow @kumar303's idea in the linked comment and differentiate between unloaded and loaded but empty.

**Comment by tofumatt** [comment]
Note that I think we do this in a few places across the app, not just in the section reviewed in the commented link.

**Comment by willdurand** [comment]
Also note that #3313 is somehow related to this.
