### ISSUE TITLE
Check old routes post-launch and update + redirect

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3374]
We have some old urls that we're re-implementing such as `/%locale%/review_guide`. For simplicity we're using the same urls in the new frontend. However post-launch it would be good to revisit these urls and redirect any that we want to change.

E.g. if we change `/%locale%/review_guide` to`/%locale%/review-guide` we should add a redirect for the old url on making that change.

**Comment by willdurand** [comment]
> We have some old urls that we're re-implementing such as `/%locale%/review_guide`. For simplicity we're using the same urls in the new frontend. However post-launch it would be good to revisit these urls and redirect any that we want to change.

@muffinresearch is there anything we can do here? What would be the reason to change these URLs?

**Comment by muffinresearch** [comment]
@willdurand I think in general we've focused on parity with the old ui's urls, this was really about looking back over what we have once the legacy frontend is removed, and seeing if there are urls we'd want to change for better overall consistency.

**Comment by muffinresearch** [comment]
Closing this since I don't think we have an pressing actions required on this front.
