### ISSUE TITLE
"Dictionaries and Language Packs" unusable page on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3375]
Steps to reproduce:
1. Load https://addons.mozilla.org/en-US/android/ on your device
2. Go to "More..." and click "Dictionaries and Language Packs"

Expected results:
Corresponding page is loaded.

Actual results:
A 404 page is loaded.

Notes/Issues:
- I saw this on desktop too, but thought that it is not implemented, and will not be an issue, if we are still using old AMO pages for production, but on device, this is an issue that users can encounter.
Verified in AMO-prod FF58(Android 7.2.1).
Screenshot for this issue:
![2017-10-06_1152](https://user-images.githubusercontent.com/15685960/31270375-d7f816bc-aa8c-11e7-9bac-31d87fefd3e8.png)

**Comment by tofumatt** [comment]
Arg, shoot, I forgot about this. It’s because we use link to rather than href. I can fix this easily. My bad. 😓

- Matthew Riley MacPherson (sent from mobile)

**Comment by tofumatt** [comment]
Note the desktop and mobile pages are the same as long as seen on this new site now. The only different between device and browser is the viewport/css rules applied. Everything else should be the same between desktop/mobile now. I guess the addons returned are different too but that’s because of a different `clientApp` 😀

**Comment by ValentinaPC** [comment]
> Note the desktop and mobile pages are the same as long as seen on this new site now. The only different between device and browser is the viewport/css rules applied. Everything else should be the same between desktop/mobile now.

I thought that the link will work only after issue https://github.com/mozilla/addons-frontend/issues/2777 will be fixed. That's my bad. :(

**Comment by ValentinaPC** [comment]
Is there a chance to fix this for this push? Thanks!

**Comment by tofumatt** [comment]
Hmm, I have the actual page ready and we could pick it, so yes.

**Comment by tofumatt** [comment]
Just FYI this won't be visible on a direct page load until #3438 is closed, but you can navigate here from another page.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1).
Postfix screenshot:
![desktop](https://user-images.githubusercontent.com/15685960/31484099-98dee88e-af37-11e7-9bdc-0e280aa72328.png)
![fr](https://user-images.githubusercontent.com/15685960/31484100-99017f52-af37-11e7-92a2-5e1dde3e2670.png)
