### ISSUE TITLE
Android "Experimental" category icon is not rendered correctly

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3377]
Steps to reproduce:
1. Load AMO-prod page on your device i.e. https://addons.mozilla.org/en-US/android/
2. Go to Extensions - "Experimental" category  https://addons.mozilla.org/en-US/android/extensions/experimental/
3. Observe it's icon

Expected results:
The icon is rendered correctly.

Actual results:
The icon has layout issues.

Notes/Issues:
- seems like its icon was added for "Other" category 
Verified on AMO-prod FF56(Android 7.2.1).
Screenshots:
![2017-10-06_1323_001](https://user-images.githubusercontent.com/15685960/31273980-a1def052-aa99-11e7-8bb8-18f7831b6272.png)
![2017-10-06_1323](https://user-images.githubusercontent.com/15685960/31273987-a5ba3768-aa99-11e7-9d06-68100bc994ea.png)

**Comment by willdurand** [comment]
arf, good catch. too bad it is already in production 😢

**Comment by willdurand** [comment]
So it looks like we dont have icons for Android. I am going to remove icons for all Android category pages.

**Comment by willdurand** [comment]
Actually, we do have most of the icons, so I will rather request the missing icons and fix this one (that is not correct anyway).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshot:
![exp](https://user-images.githubusercontent.com/15685960/31370833-6e01fc34-ad96-11e7-8460-5040b2842a50.png)
