### ISSUE TITLE
Extension category icons are missing for Android

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3378]
Steps to reproduce:

1. Go to the Extensions tab from AMO homepage (i.e.https://addons.mozilla.org/en-US/android/extensions/)
2. Browse through the available Categories

Expected result:
Each Category has a category icon

Actual result:
Categories highlighted with red in the below screenshot don't have any icons

![android categories](https://user-images.githubusercontent.com/31961530/31274305-08cb2a8c-aa9b-11e7-8ed7-1f8a6fc0b9cc.png)

Notes: this issue can be reproduced on all AMO servers with FF56 (Win10 and Android 7.0)
This issue has been highlighted in bug [#2778](https://github.com/mozilla/addons-frontend/issues/2778#event-1272187156) Notes

**Comment by willdurand** [comment]
See also: #3377

**Comment by willdurand** [comment]
I have requested the missing icons in: https://github.com/mozilla/addons-frontend/issues/3379.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.0). All Android extension categories have a corresponding icon now.

Postfix screenshot:
![image](https://user-images.githubusercontent.com/31961530/31378565-60ec132c-adb4-11e7-94e9-2dc7f7a0f9cb.png)
