### ISSUE TITLE
Android category icons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3379]
Hi, I definitely missed that but the previous issue (#2778) did not mention some of the Android categories, therefore a few icons are missing. I managed to find similar issues for some categories but not for everything.

## Extensions

- [x] Device Features & Location
- [x] Experimental
- [x] Performance
- [x] Photos & Media: I can use `photos-music-video`
- [x] Security & Privacy: I can use `privacy-security`
- [x] Social Networking: I can use `social-communication`
- [x] Sports & Games: I can use `sports`
- [x] User Interface

## Themes

All good 😃

**Comment by pwalm** [comment]
I'll work on these today 👍

**Comment by pwalm** [comment]
New icons are [here](https://github.com/mozilla/addons-frontend/tree/master/assets/icons/extensions/android).

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.0). All Android extension categories have a corresponding icon now.

Postfix screenshot:
![image](https://user-images.githubusercontent.com/31961530/31378939-7a2c97b6-adb5-11e7-8079-c2b1d5a97f43.png)
