### ISSUE TITLE
[layout] Carousel has white space on first slide

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#3381]
I am not sure if its desired functionality.

### Describe the problem and steps to reproduce it:
White space on carousel on first slide ad last slide.

### What happened?
White space on first slide and on last slide.

### What did you expect to happen?
There shouldnt be white space

### Anything else we should know?
<img width="1270" alt="screen shot 2017-10-06 at 5 29 55 pm" src="https://user-images.githubusercontent.com/5318732/31276999-5597beea-aabc-11e7-9480-20e5c4b4032f.png">

<img width="1274" alt="screen shot 2017-10-06 at 5 33 34 pm" src="https://user-images.githubusercontent.com/5318732/31277033-8797f482-aabc-11e7-9450-4e220f7e2bf7.png">

**Comment by willdurand** [comment]
I think it is intended because it is used to center the current carousel "card" (section).

**Comment by tsl143** [comment]
But this doesn't look cool, and that too on homepage. It looks incomplete :(

**Comment by muffinresearch** [comment]
Ideally in a future interation the carousel would work continuously and then there would always be a slide to the left or right of centre.

**Comment by tofumatt** [comment]
Yes, this is the eventual plan 😊

Matthew Riley MacPherson (sent from mobile)

**Comment by willdurand** [comment]
Ok, closing this one for now as it is actually expected.
