### ISSUE TITLE
"Internal Server Error" on AMO-dev

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3385]
Steps to reproduce:
1. Load AMO-dev Extensions homepage or any other page i.e. https://addons-dev.allizom.org/en-US/firefox/extensions/

Expected results:
Page is loaded without any issues.

Actual results:
After a while a red banner labeled "Internal Server Error" is displayed.
Extensions  suggestions are continuously loading.

Notes/Issues:
Verified on AMO-dev FF56(Win 7, Android 7.2.1)
Screenshot for this issue:
![2017-10-06_1753](https://user-images.githubusercontent.com/15685960/31283779-37b45ebc-aabf-11e7-869e-793758480fff.png)
![2017-10-06_1716](https://user-images.githubusercontent.com/15685960/31283781-39d64d86-aabf-11e7-898c-eb6f526ad745.png)

**Comment by kumar303** [comment]
This was a glitch in our search service (ElasticSearch) but it has been fixed now. Here is a bit more info: https://github.com/mozilla/addons-server/issues/6610#issuecomment-334873926

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Internal server error message is no longer listed in AMO pages.
![nav](https://user-images.githubusercontent.com/15685960/31329043-da9e9854-ace0-11e7-808b-3dca82061376.png)
