### ISSUE TITLE
Create a separate component for fetching add-ons by author for better errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3387]
The Addon component shows add-ons by other authors as of https://github.com/mozilla/addons-frontend/pull/3083

We should move this to a separate component so that it can have its own error handler. Otherwise, an error might looks like this (example triggered by https://github.com/mozilla/addons-server/issues/6610). This screenshot would have made a confusing bug report.

<img width="799" alt="screenshot 2017-10-06 11 14 44" src="https://user-images.githubusercontent.com/55398/31289016-f100defa-aa8c-11e7-9d8e-280af17cd546.png">

**Comment by willdurand** [comment]
This has been done.
