### ISSUE TITLE
Support Static Themes in front-end

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#3388]
Depending on how much work this is, it might need splitting out into other issues.  The API returns `'type': 'statictheme'` for Static Themes.  In the trivial case they are similar to LWT (personas), but static themes also support extra functionality to style the url bar and set other colors, and support additional images and tiling/alignment options.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme

~The API is going to have to return some extra stuff to allow preview but right now it doesn't do any of that.  It's likely to be similar in structure to the manifest [JSON itself](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/theme#Examples)~

See https://github.com/mozilla/addons/issues/501 for tracker and background&links.

**Comment by muffinresearch** [comment]
@jvillalobos @pwalm do you have some input here as to any differences that should be displayed on the frontend or should this just follow what already exists for lightweight themes?

**Comment by jvillalobos** [comment]
For an MVP, I think we can show the same metadata as lightweight themes. Since static themes will be using the same dev tools as other add-ons, we should consider adding contributions and support info.

I would also like that the preview image reflects all the changes done to the main toolbar, rather than just show the background image. I mention a similar visual for the [submission process changes](https://docs.google.com/document/d/1NB5RNu_eoJmDAlb1V_BrT-4BpmHUc1ZvGjOEZS5hQvQ/edit#heading=h.1oiwflhch2xm).

**Comment by eviljeff** [comment]
The preview image showing the toolbar is a problem here as its going to need something close to implementing Firefox's UI in client-side javascript.  And then keeping it up to date with changes to the Firefox UI.  (The submission process document references a literal screenshot of Firefox, rather than a mockup).

**Comment by jvillalobos** [comment]
What I was thinking could be done is have an SVG representation of the toolbar that can have the styles from the theme set. I would hope the Firefox toolbar won't change radically in the next year or so, and even in those cases we may not want to bother updating the template unless the changes are really significant.

Do you have suggestions for alternatives? Just showing the background image won't be a good representation of many future themes.

**Comment by kumar303** [comment]
Relevant section from the [PRD](https://docs.google.com/document/d/1d9acBumpdK87sYg7Ah98BEKvL7b4tuO-RDpgqbm7FTs/edit#heading=h.w64xax5t65re)

**Listing and search**

Static themes and lightweight themes should be mostly indistinguishable to end users:
 
* Listing pages for static themes should use the same layout and have the same features.
* Searching for themes should yield both lightweight themes and static themes. 
* Categories should be the same for both.
* Their preview images should be the same dimensions.
* Static themes should be annotated like how it was done with the No Restart flag, to give them some additional promotion and encourage testing. 
* For performance and consistency reasons, the preview installation feature should be disabled for lightweight themes. Both theme types can be easily installed and uninstalled.

**Comment by muffinresearch** [comment]
Closing in favour of #4898
