### ISSUE TITLE
The More header menu item is covered by a white square (glitch?)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3389]
### Describe the problem and steps to reproduce it:

Go to the site in Firefox release 56 or Firefox Nightly 58.0a1 (2017-10-06) on macOS

### What happened?

I see a white square over the More header item

![screenshot-2017-10-6 add-ons for firefox](https://user-images.githubusercontent.com/55398/31295310-bfef9312-aaa3-11e7-8320-e88980686b4b.png)

### What did you expect to happen?

No white square

### Anything else we should know?

It goes away in responsive mode but *not* by manually shrinking the window. Maybe it's a Firefox bug.

**Comment by ValentinaPC** [comment]
I cannot reproduce the initial issue on FF56 (MacOS Sierra v. 10.12.3)
