### ISSUE TITLE
Unauthenticated requests trigger API calls on the server

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#339]
The values aren't shown on the page but the server is still calling the API when it doesn't have a token for the user. The API call should be skipped if the user is unauthenticated.

**Comment by mstriemer** [comment]
My initial attempts at fixing this did not work.

Wrapping each component with the old `loginRequired` higher-order component breaks reduxAsyncConnect and no data-fetching happens so the app just breaks entirely.

Requiring the user to be logged in to perform the request doesn't seem like the right solution but does fix the problem.

Another approach might be to redirect the user with an `onEnter` hook. This would mean when the user enters the authenticated section they would be redirected to `/login` instead of just being shown a login form on the current page. This seems like the best solution, hopefully it actually fixes the problem. react-router has [documentation](https://github.com/reactjs/react-router/blob/master/docs/guides/RouteConfiguration.md#enter-and-leave-hooks) and an [example](https://github.com/reactjs/react-router/blob/cbdc49442aba5cc6f225ff5546ac5f4a217fa4ec/examples/auth-flow/app.js#L133).

**Comment by kumar303** [comment]
Any protected API view already requires authentication so I don't think this is a problem
