### ISSUE TITLE
"More extensions by author_name" section has layout issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3404]
Steps to reproduce:
1. Load an add-on details page that has the "More extensions by author_name" section on device i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-simple/

Expected results:
The  "More extensions by author_name" has no layout issues.

Actual results:
There is an empty row between add-on name and the number of users.

Notes/Issues:
- the row is useful for add-ons with long name, but look like something is missing for short name add-ons.
- not reproducing for themes
Verified on AMO-dev FF56(Android 7.2.1).
Screenshot for this issue:
![2017-10-09_1112](https://user-images.githubusercontent.com/15685960/31329429-c0f07470-ace2-11e7-975b-67e01921cdeb.png)

**Comment by grahamperrin** [comment]
Should the phrase at the head of the card be broader? Like, 

> More _add-ons_ by …

Or, is this card intentionally restricted to show extensions alone?

**Comment by muffinresearch** [comment]
I think this layout is now fixed:

![screen shot 2018-07-31 at 18 16 29](https://user-images.githubusercontent.com/1514/43475510-eb40d2bc-94ed-11e8-8728-0f9a6322c360.png)

**Comment by willdurand** [comment]
ah yes I fixed it a few weeks ago!

**Comment by AlexandraMoga** [comment]
Verified fixed

![image](https://user-images.githubusercontent.com/31961530/43503719-1a5878fe-9569-11e8-8992-0c791ad7f01c.png)
