### ISSUE TITLE
Language box has double dropdown arrows on Mac

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3407]
Steps to reproduce:
1. Load AMO-dev homepage on your Mac https://addons-dev.allizom.org/en-US/firefox/
2. Go to page footer and observe language dropdown

Expected results:
There is only a dropdown arrow.

Actual results:
The language box has 2 dropdown arrows.

Notes/Issues:
Verified on AMO-dev FF56(MacOS Sierra v. 10.12.3)
Screenshot:
<img width="1280" alt="screen shot 2017-10-09 at 12 07 02" src="https://user-images.githubusercontent.com/15685960/31331896-e6e45566-acec-11e7-8e67-ba4ef52cc986.png">

**Comment by willdurand** [comment]
I believe this is expected, at least according to the mock-ups:

<img width="691" alt="screen shot 2017-10-09 at 11 42 11" src="https://user-images.githubusercontent.com/217628/31332506-f18d71d8-ace6-11e7-8c6e-b4d0e74b792c.png">

**Comment by ValentinaPC** [comment]
Then...is not according to mocks, on Windows :)
I suggest using same representation.
Please see screenshot:
![2017-10-09_1303](https://user-images.githubusercontent.com/15685960/31333341-48f220da-acf2-11e7-88c4-044e2f90fe71.png)

**Comment by willdurand** [comment]
I see, it must be platform-dependent then and I guess users of these platforms are used to the respective dropdown arrows. I don't know if we should make it consistent here or leave it as is.

ping @tofumatt

**Comment by tofumatt** [comment]
These dropdown styles are platform-independent usually. I’m not cleared on how they currently look on windows, Mac, etc.

Could someone attach screenshots in a comment of how they look right now for each OS?

**Comment by ValentinaPC** [comment]
Win 7:
![win](https://user-images.githubusercontent.com/15685960/31335825-f253f284-acfc-11e7-8193-24ee15a00f0a.png)

Mac OS Sierra:
![mac](https://user-images.githubusercontent.com/15685960/31335831-fadae2f0-acfc-11e7-9384-e6fe01de1b2d.png)

Ubuntu 14
![linux](https://user-images.githubusercontent.com/15685960/31335846-01982db4-acfd-11e7-8ffb-f98e4ba7bf01.png)

**Comment by muffinresearch** [comment]
Yep this is just a native browser select now, so it will differ per platform.

**Comment by tofumatt** [comment]
Yeah, this is working as expected and they should not be consistent 😄

**Comment by ValentinaPC** [comment]
Oook.
