### ISSUE TITLE
Themes categories have issues on Android

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3408]
Steps to reproduce:
1. Load Themes homepage using "Add-ons for Android" option https://addons-dev.allizom.org/en-US/android/themes/
2. Click on any category i.e. Abstract

Expected results:
Corresponding category page is loaded without any display or layout issues.

Actual results:
Add-ons are continuously loading. For some categories an error message are displayed on top of the page.

Notes/Issues:
- reproducing only using "Add-ons for Android" option.
Verified on AMO-dev FF56(Win 7, Android 7.2.1)

Screenshot for this issue:
![invalid](https://user-images.githubusercontent.com/15685960/31334992-3ba78882-acf9-11e7-9c9f-8dd687889712.png)

**Comment by willdurand** [comment]
It seems we have more categories displayed than supported according to this list: https://addons-server.readthedocs.io/en/latest/topics/api/categories.html#current-categories.

**Comment by willdurand** [comment]
Oh well, I found #2170 in the meantime. I guess that's the reason...

**Comment by ValentinaPC** [comment]
@willdurand : are you sure? because that bug was fixed and verified long time ago....

**Comment by willdurand** [comment]
> @willdurand : are you sure? because that bug was fixed and verified long time ago....

It is very related, but it affects a different part of the code. The featured add-ons are not retrieved with the same search feature currently (#3307), that is why it fails here. The featured add-ons cannot be loaded on Android for the same reason as #2170. I am working on a fix for this issue :)

**Comment by ValentinaPC** [comment]
You know better! :)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Postfix video:
![cat](https://user-images.githubusercontent.com/15685960/31435713-3dcb7420-ae89-11e7-942c-a49295ed48cc.gif)
