### ISSUE TITLE
Add about and review_guide urls to the nginx config

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3409]
We should now have `/%locale/about` and `/%locale%/review_guide` served by the addons-frontend app. (Note: no slash)

Please can these two be added to the nginx config so that they can be served by addons-frontend?

If we do this first on -dev then it can be tested and pushed to stage and then prod (these pages should be released to prod this week (2017-10-12)).

**Comment by bqbn** [comment]
The above mentioned 2 routes are on -dev and -stage now. Please test.

**Comment by muffinresearch** [comment]
@bqbn - thanks, I've just pushed a new tag for stage but it looks good on -dev.

**Comment by muffinresearch** [comment]
This was pushed to prod today.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-prod FF56(Win 7, Android 7.2.1)
Postfix screenshots:
![about](https://user-images.githubusercontent.com/15685960/31537298-3bc7ce08-b00a-11e7-979d-378b99c610e7.png)
![rev_g](https://user-images.githubusercontent.com/15685960/31537299-3be6cdd0-b00a-11e7-9767-9ac6e757e37d.png)
