### ISSUE TITLE
Refactor static pages components

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3410]
From https://github.com/mozilla/addons-frontend/pull/3207#discussion_r142559054 as mentioned by @tofumatt:

> I'd rather us have a StaticPage component that included this CSS and a bit of the boilerplate Card stuff rather than importing CSS from other components. We've done stuff like this in the past, I think with error pages for instance, but we've since got out the habit of doing it and I think just having a StaticPage component would be better. We tend not to import other component's CSS. Something like:

```JS
// amo/components/StaticPage/index.js
import 'amo/components/StaticPages/styles.scss';

export default class StaticPage extends React.Component { [...] };

// src/amo/components/AboutPage/index.js
import StaticPage from 'amo/components/StaticPage';


export default class AboutPage extends React.Component {
  [...]
  render() {
    return <StaticPage title="About this site">{CONTENT}</StaticPage>
  }
};
```
> But that's a later optimisation. We should just file a bug for it to remind us to tidy up the static pages unless it's super-easy to convert.

**Comment by muffinresearch** [comment]
Not only the above, but these probably could be both separate entry points to save all that content being part of the bundle.

**Comment by xu3u4** [comment]
Hello!
I just sent a PR, please check 🙂

**Comment by ioanarusiczki** [comment]
@willdurand Looking at AMO dev I see in the Network when I first load `About` or `Review Guide` pages a .css such as `https://addons-amo-dev-cdn.allizom.org/ReviewGuide-57efc2892ebd46949fcc.css`

When I reload one of the pages the Network shows the .css for both : Review and About 

![css for the pages](https://user-images.githubusercontent.com/33448286/65940158-72f91380-e430-11e9-92cb-1a31f79ce5ce.png)

Pages load without UI issues. 

Let me know if anything else should be tested.
