### ISSUE TITLE
Submitting a blank developer reply breaks the form

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3415]
### Describe the problem and steps to reproduce it:

* Sign in as an add-on developer
* Go to an add-on you own
* Click to read all reviews
* Reply to one of the reviews
* Enter only blank spaces and click Publish

### What happened?

The form gets stuck in a loading state.
![blanlrev](https://user-images.githubusercontent.com/1583842/31345483-8e0bc92e-ad1e-11e7-8e27-f355aba051f6.gif)

### What did you expect to happen?

* It should be possible to submit a reply with only blank spaces
* An API error should be visible on the screen and should allow the user to fix the form and re-submit

### Anything else we should know?

This was a bug introduced by https://github.com/mozilla/addons-frontend/issues/2773

**Comment by vcarciu** [comment]
@Kumar : 
I am a bit confused by your comment that says "It should be possible to submit a reply with only blank spaces". Right now, the "Publish reply" button is not active if you have a comment only with blank spaces:
![publish](https://user-images.githubusercontent.com/1583842/31496423-e7b7c788-af63-11e7-806a-2101c5a42ed6.gif)

**Comment by kumar303** [comment]
Oh sorry! It was a typo. I meant to say "It should *not* be possible to submit a reply with only blank spaces".

**Comment by vcarciu** [comment]
Verified as fixed then :)
