### ISSUE TITLE
About and review guide are only SSR'd

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3416]
Once the routes are working via nginx we should be able to switch from `href` to `to` in the Links used which will make client-side routing pick them up correctly.

**Comment by muffinresearch** [comment]
blocked by https://github.com/mozilla/addons-frontend/issues/3409

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
About page: https://addons-dev.allizom.org/en-US/about
Review Guide page: https://addons-dev.allizom.org/en-US/review_guide
Postfix screenshots:
![about](https://user-images.githubusercontent.com/15685960/31431949-dbd7b4a0-ae7d-11e7-9fc4-ffd557f55950.png)
![rev](https://user-images.githubusercontent.com/15685960/31431960-e045432c-ae7d-11e7-8bb9-dec75a8c0639.png)
