### ISSUE TITLE
Number of add-ons from a collection is not decremented while removing an add-on

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3422]
Steps to reproduce:
1. Remove an add-on from "change-up-your-tabs" collection available in homepage - https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/change-up-your-tabs/
2. Check collection details page

Expected results:
Number of add-ons from collection is decremented.

Actual results:
Number of add-ons from collection stays the same.

Notes/Issues:
- adding an add-on to collection will increment the number of add-ons.

Verified on AMO-dev FF56(Win 7, Android 7.2.1)
Screenshot for this issue:
![6](https://user-images.githubusercontent.com/15685960/31371386-243ebae4-ad99-11e7-84e6-2b66cf0efdd4.png)

**Comment by tofumatt** [comment]
This looks like an API count issue as I think we use the count variable here... maybe hints just aren’t re-indexed super-fast on dev?

- Matthew Riley MacPherson (sent from mobile)

**Comment by ValentinaPC** [comment]
> maybe hints just aren’t re-indexed super-fast on dev?

I let it sleep on it, but in the morning, the number was the same. :)

**Comment by tofumatt** [comment]
@diox Any chance this is a server bug where the collection count isn't being updated? We just use the count attribute so I don't think this is anything on our end.

**Comment by ValentinaPC** [comment]
This was taking care in https://github.com/mozilla/addons-server/issues/6629#event-1285824400.
We can close this as verified-fixed.
