### ISSUE TITLE
Add "Preview reply" option for reply-to-review form

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3423]
Follow up for #3370 

Steps to reproduce:
1. Sign in as a developer of an add-on
2. Go to the detail page of your add-on
3. Click to read all reviews
4. Click Reply to this review
5. Enter some text

This issue is to make UI changes related to "Preview reply" based on the latest mocks, shown in Sketch and below:
![preview_reply](https://user-images.githubusercontent.com/15685960/31380821-2f4c983a-adbb-11e7-8469-b297587c656c.png)

**Comment by muffinresearch** [comment]
Closing this since we don't think a preview adds anything other than more steps.
