### ISSUE TITLE
A user with long name that leaves a review causes layout issues for "Reply to this review" option on device

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3424]
Prerequisites:
The person who reviewed your add-on has long account name;
User uses an Android device;

Steps to reproduce:
1. Sign in as a developer of an add-on
2. Go to the detail page of your add-on 
3. Click to read all reviews
4. Observe the "Reply to this review" option

Expected results:
There are no display or layout issues.

Actual results:
The link is not displayed, only the reply arrow.

Notes/Issues:
Verified on AMO-dev FF56(Android 7.2.1)
Screenshot for this issue:
![2017-10-10_1315](https://user-images.githubusercontent.com/15685960/31381424-26163b3e-adbd-11e7-9b86-4760bcacaa18.png)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Android 8.0) 

![small screen - button is now visible](https://user-images.githubusercontent.com/33448286/44347362-44281400-a4a0-11e8-9353-347079f8fa3f.png)
