### ISSUE TITLE
Carousel animation stops after reaching last slide

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3427]
Steps to reproduce:

1. Go to AMO homepage (i.e. https://addons-dev.allizom.org/en-US/firefox/)
2. Observe the Carousel animation

Expected results:
The carousel animation is continuous (i.e. it won't stop after reaching the last slide)

Actual result:
The carousel animation stops at the last slide

Note: normally, when introducing a page carousel, the user would expect to see a continuous animation, so the suggestions here would be:
a) make the animation continue to the first slide after the last slide is displayed (fluid navigation)
b) make the animation jump back at the first slide once the last slide is displayed (replay the same animation)
Observed with FF56 (Win10 and Android 7.0)

![carousel animation](https://user-images.githubusercontent.com/31961530/31389503-dc6da342-add9-11e7-8901-b9cda687a526.gif)

**Comment by muffinresearch** [comment]
The carousel is being completely replaced with static content see https://github.com/mozilla/addons-frontend/issues/3430
