### ISSUE TITLE
Always request gzip'd API responses

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3428]
The client/server code should always request a gzip'd API response. 

gzip'd API responses will be turned back on in https://github.com/mozilla/addons-server/issues/6636

This of course means we'll need to ungzip responses.

For QA:
- Load any page on the site
- Watch the network panel in developer tools
- Interact with the site so that you see requests made to URLs that look like `/api/v3/...`
- Make sure the pages still work

**Comment by willdurand** [comment]
It seems like we are already consuming gzip'ed API responses (I see `Content-Encoding: gzip` in the response headers).
