### ISSUE TITLE
Prevent searches with a query of more than 100 characters in length

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#3429]
https://github.com/mozilla/addons-server/issues/6604 will introduce a limit to the `q` parameter in the search API. When called with a query longer than 100 characters, it will answer with a 400 Bad Request. 

The frontend should prevent the user from making such a request by limiting the user input (and/or be prepared to handle the potential 400 Bad Request response)

**Comment by kumar303** [comment]
The error for this looks kinda bad so I'm putting it in the post-release bucket for now.

<details>
  <summary>Screenshot</summary>

![screenshot-2017-10-23 search results for it is a long established fact that a reader will be distracted by the readable con](https://user-images.githubusercontent.com/55398/31896930-97bc9176-b7da-11e7-84a9-c0df3023c59f.png)


</details>

**Comment by vcarciu** [comment]
Verified as fixed. Cannot enter more than 100 chars in search box : 
![100chars](https://user-images.githubusercontent.com/1583842/32112602-5ae30ca2-bb46-11e7-9e98-fccde6068f22.png)
