### ISSUE TITLE
Replace homepage carousel with three static panes

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3430]
Chatted with @pwalm about this, and we're looking to replace the carousel with a set of static panes, something like:

<img width="583" alt="5_alternatives_to_using_a_carousel_on_your_website_homepage" src="https://user-images.githubusercontent.com/90871/31399691-15803e1e-ade5-11e7-8e9c-75ec7d6e3a60.png">

This will allow all "carousel" items to be viewed at once, prevents CSP issues, should increase load times (by being able to load smaller assets), and should be a bit nicer overall. Plus we don't have to implement an infinite carousel so it's more time for us to knock out other bugs.

**Comment by vcarciu** [comment]
Verified as fixed: 
Desktop:
![staticcarrousel](https://user-images.githubusercontent.com/1583842/31504740-d8143b0a-af7b-11e7-91af-d1364c45f739.png)

Mobile:
![staticcarrouseldevice](https://user-images.githubusercontent.com/1583842/31504755-de3ccd4e-af7b-11e7-840d-a635d46a256a.png)
