### ISSUE TITLE
Keep consistency for nav arrows between search results and collections details pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3436]
Steps to reproduce:
1. Load a collection details page that contains more than 25 add-ons i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/privacy/
2. Observe navigation arrows
3. Search for something i.e. "test" - https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=test
4. Observe navigation arrows

Expected results:
Pagination arrows are positioned in the same place.

Actual results:
Pagination arrows position differ.

Notes/Issues:
Verified on AMO-dev FF56(Win 7)
Screenshots:
![2017-10-11_1344](https://user-images.githubusercontent.com/15685960/31436072-66b8afaa-ae8a-11e7-8a11-8e72a37b2bde.png)

**Comment by willdurand** [comment]
Haha cool that you have opened this one. I wanted to submit a patch for that today.

Personally I prefer the first screenshot (collectiobs). WDYT? /cc @pwalm

**Comment by willdurand** [comment]
(ooops wrong button)

**Comment by tsl143** [comment]
Ohh, I fixed other way round  :/

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Nav arrows look the same in any pages that require navigation.
Postfix screenshots:
![coll](https://user-images.githubusercontent.com/15685960/31653574-b3904f68-b32b-11e7-8a74-c06e1e552772.png)
![search](https://user-images.githubusercontent.com/15685960/31653575-b3b08166-b32b-11e7-8064-746e55c5fe95.png)
