### ISSUE TITLE
Update nginx route for language packs

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3438]
Hello, to get #2777 working we need the route `/:lang/:clientApp/language-tools/` to point to the new front-end. Sorry for the late-notice but this fixes a bug so it would be good to get this out ASAP, for this week's push.

**Comment by bqbn** [comment]
The Nginx change for the new route has been deployed to -dev and -stage. Please test.

**Comment by muffinresearch** [comment]
This was pushed to production today.
