### ISSUE TITLE
"Cookies" link from Footer has a glitch after click

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3439]
Steps to reproduce:
1. Load AMO-stage page https://addons.allizom.org/en-US/android/
2. Click on "Cookies" option from the page footer

Expected results:
Page is loaded without any issues.

Actual results:
Cookies page footer is loaded for a second.

Notes/Issues:
- this can be seen more clearly on device;
Verified on AMO-stage FF56 (Android 7.2.1). Issue is reproducing on all servers.
Video for this issue:
![videotogif_2017 10 11_15 10 19](https://user-images.githubusercontent.com/15685960/31439924-b40ca02a-ae96-11e7-9180-b0839b2015a9.gif)

**Comment by tofumatt** [comment]
I'm not convinced this is an issue with our page, it seems like the mozilla.org page is moving around? 🤔

**Comment by ValentinaPC** [comment]
I was thinking that maybe we can do something on our end, to load top page content and not the footer, while clicking on the "Cookies" link. :)

**Comment by tofumatt** [comment]
But it's their page that's loading content strangely. It might even be a device bug? I don't think there's anything we can do on our end 😞

**Comment by tofumatt** [comment]
Yeah, actually, seeing the loading bars still loading and then it going to the top of the page... I think this is either a browser bug on an issue on moz.org. Closing as a won't fix, as there's not anything we can do on our end, sorry! 😢

**Comment by ValentinaPC** [comment]
Is not a device issue, it can be seen on desktop too, for a sec.
Ok, no pb.
