### ISSUE TITLE
No way to see if Trending add-ons are sorted as expected

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3444]
Steps to reproduce:
1. Load Extensions homepage : https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Click on "More Trending extensions" link - https://addons-dev.allizom.org/en-US/firefox/search/?sort=hotness&type=extension
3. Observe the results

Expected results:
User can see that the results are ordered correctly.

Actual results:
User cannot see if the results are sorted as expected.

Notes/Issues:
Verified on AMO-dev FF56(Win 7).
Screenshot for this issue:
![trend](https://user-images.githubusercontent.com/15685960/31452841-ca377a88-aeb8-11e7-83c6-30c9f33c7fc6.png)

**Comment by tofumatt** [comment]
What do you mean " User can see that the results are ordered correctly."? I don't quite understand.

**Comment by ValentinaPC** [comment]
I mean that from this page (above screenshot) I cannot understand if sort option "Trending" works as expected. Is there a way to check this?

**Comment by tofumatt** [comment]
Oh, I see. You could use the network pane in the dev tools to check the HTTP network request to the API to make sure we’re requesting the right sort method? That’s about it I guess. 😅

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
I could, but the normal user? (after push) :)

**Comment by willdurand** [comment]
> I could, but the normal user? (after push) :)

Hehe, that's the feature actually. Trending means it is popular right now and the order/list will likely vary a lot. There is no really way to know other than trusting the API response. Having the right filter set in the left form should be enough for our lovely muggles.
