### ISSUE TITLE
Download the source of an incompatible add-on

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3445]
### Describe the problem and steps to reproduce it:

Go to an add-on detail page using an unsupported browser or platform. For example: Chrome.

See https://github.com/mozilla/addons-frontend/issues/3266 for STR

### What happened?

It says the add-on is incompatible or it says you need to download Firefox or something. The install button is disabled.

### What did you expect to happen?

The install button should be disabled but there should be a way to download the add-on source anyway. Here are a few scenarios in which this could be helpful:

- Maybe you are running Firefox with `privacy.resistFingerprinting` or some related settings (see https://bugzilla.mozilla.org/show_bug.cgi?id=1393283 and https://bugzilla.mozilla.org/show_bug.cgi?id=1394448). There is no way to correctly detect these versions of Firefox, by design, so you will likely see an incompatibility warning.
- Maybe you are on an experimental build of Firefox with some bonkers settings but you know the add-on will still work
- Maybe you are viewing the site in Chrome and are curious about how the add-on works; you just want to see the source code
- The incompatibility error may not be correct -- see https://github.com/mozilla/addons-frontend/issues/3315 . In this case, letting the user download the source could give them a working add-on.

### Anything else we should know?

The old site provided a link to the source like "download it anyway" which was nice.

**Comment by diox** [comment]
Is this technically a dupe of https://github.com/mozilla/addons-frontend/issues/3021 ?

**Comment by kumar303** [comment]
The UX for this should be straight forward. We can add a *Download Anyway* action button to the error notice that looks like *Retry* in the [spec](https://design.firefox.com/photon/components/message-bars.html#error).

**Comment by kumar303** [comment]
> Is this technically a dupe of #3021 ?

Indeed. I kept this one open because it explains more of the scenarios that could lead to the experience.

**Comment by Thorin-Oakenpants** [comment]
With regards to `privacy.resistFingerprinting` listed in OP, the bugzilla is [1394448](https://bugzilla.mozilla.org/show_bug.cgi?id=1394448) and is being worked on

Note: you can *still* install extensions: right click the `+ Add to Firefox` button and open in a new tab
