### ISSUE TITLE
A disabled legacy add-on shows up as installable, but cannot be installed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3447]
STR:

Pre-requisites.

* I have Awesome Screenshot Plus installed and disabled (see screenshot below from about:addons)
* To replicate this you'd probably need a release profile and install something that will be disabled when upgrading to a later Firefox version.

<img width="1386" alt="add-ons_manager" src="https://user-images.githubusercontent.com/1514/31460199-7e905078-aebd-11e7-8fbb-3a25d92c4208.png">

On visiting https://addons.mozilla.org/en-US/firefox/addon/screenshot-capture-annotate/

The button makes it look like I can install it but I can't. 

<img width="1374" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31460420-4fe125ee-aebe-11e7-9ba0-5c13d0287be7.png">

My case here seems to be due to having an old profile which has some content disabled due for multiprocess reasons. This is probably something of an edge case but it would be good to make sure this isn't something that a user of pre-57 will see a lot of when they upgrade to 57.

**Comment by muffinresearch** [comment]
@vcarciu @ValentinaPC as we get closer to the release of the desktop site it would be useful to test the upgrade experience and see if anything like this crops up through the upgrade experience ? E.g: 

* Start with a release browser and install some legacy add-ons + web-exts.
* Upgrade to 57 with the same profile.
* Look at some of the AMO pages for add-ons you have installed - does everything make sense?

/cc @krupa

**Comment by vcarciu** [comment]
@muffinresearch : yes , it makes sense, testing started

**Comment by vcarciu** [comment]
@muffinresearch : we tried few scenarios , but I was not able to reproduce your initial issue. Do you have any other info about that? Awesome screenshot plus is now a webextension so maybe you have to check for updates for it.

**Comment by muffinresearch** [comment]
> @muffinresearch : we tried few scenarios , but I was not able to reproduce your initial issue. Do you have any other info about that? Awesome screenshot plus is now a webextension so maybe you have to check for updates for it.

Yep this was a profile I'd not used for a while. So I'd expect this would probably make my STR more of an edge case. If you haven't hit the same issue trying to recreate what a user might go through in getting onto 57 we're probably ok.
