### ISSUE TITLE
"More..." dropdown list is not closed if "Dictionaries & Language Packs" is clicked

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3452]
Steps to reproduce:
1. Load AMO-dev page on your device https://addons-dev.allizom.org/en-US/android/
2. Navigate to "Dictionaries & Language Packs"

Expected results:
Corresponding page is loaded. The drop down list is closed.

Actual results:
Corresponding page is loaded. The drop down list is not closed.

Notes/Issues:
- reproducing on desktop too, while the hover is still on the option;
Verified on AMO-dev FF56(Win 7).
Video for this issue:
![videotogif_2017 10 12_10 13 01](https://user-images.githubusercontent.com/15685960/31483797-97d11238-af36-11e7-815e-0635196b3eaa.gif)

**Comment by tofumatt** [comment]
This is seemingly an issue with any dropdown, I think it’s just the first item we’ve had that isn’t either:

* an external link
* something that removes the dropdown from the DOM

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
You are right!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Postfix video:
![dropdown](https://user-images.githubusercontent.com/15685960/32212537-e476e7d2-be1f-11e7-8057-8a4818e555fe.gif)
