### ISSUE TITLE
Changing "Other Browser Sites" option does not change results from "Dictionaries & Language Packs" page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3453]
Steps to reproduce:
1. Load "Dictionaries & Language Packs" page on AMO-dev https://addons-dev.allizom.org/en-US/firefox/language-tools/
2. Go to More... and select "Other Browser Sites" - "Add-ons for Android" option
3. Go back to "Dictionaries & Language Packs" page

Expected results:
Add-ons compatible with Android are listed.

Actual results:
Add-ons compatible with Firefox are listed.

Notes/Issues:
- refreshing the page fixes the issue.
- happening also viceversa.

Verified on AMO-dev FF56(Win 7, Android 7.2.1)
Video for this issue:
![refreshhh](https://user-images.githubusercontent.com/15685960/31484342-9c6bbd64-af38-11e7-8ebe-f7a94fd430a9.gif)

**Comment by AlexandraMoga** [comment]
We observed that the page content is not automatically refreshed when switching from Firefox to Android and vice-versa  for other sections as well (i.e. Featured extensions, Most popular extensions, Featured themes, Up&Coming).
Below is an example for 'Featured extensions':
![refresh2](https://user-images.githubusercontent.com/31961530/31669627-4b87fba4-b35e-11e7-8caf-96c9a7efd2aa.gif)

**Comment by willdurand** [comment]
This is not reproducible anymore. We don't link to "Dictionaries & Language Packs" on Android (anymore).

**Comment by AlexandraMoga** [comment]
Apart from not having the language-tools page on android, we also verified in #6650 that the app refreshes when interchanging `/firefox/` and `/android/` from the More... menu
