### ISSUE TITLE
Small issue in "Dictionaries & Language Packs" page for small browser dimensions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3454]
Steps to reproduce:
1. Load "Dictionaries & Language Packs" page on your device (or on your desktop resized FF 56 browser) https://addons-dev.allizom.org/en-US/firefox/language-tools/ but using Add-ons for Firefox option
2. Navigate through page

Expected results:
There are no display or layout issues.

Actual results:
Small issue in gray background sections.

Notes/Issues:
- reproducing only for small browser dimensions, while using "Add-ons for Firefox" option, because it has results for both dictionaries and lang packs.

Verified on AMO-dev FF56(Win 7, Android 7.2.1)
Screenshot for this issue:
![2017-10-12_1041](https://user-images.githubusercontent.com/15685960/31484727-142a93ce-af3a-11e7-8eac-d81194401809.png)

**Comment by tofumatt** [comment]
Ah, this is because that locale has no dictionary. I thought I covered that but looks like not everywhere. Thanks, should be a quick fix!

Matthew Riley MacPherson

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Android 7.2.1)
Postfix screenshot:
![lp](https://user-images.githubusercontent.com/15685960/31940040-69c87c80-b8c5-11e7-9e19-044287a9e101.png)
