### ISSUE TITLE
'Publish reply' button appears inactive after trying to publish an empty review

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3458]
Steps to reproduce:

1. Sign in as an add-on developer
2. Go to an add-on you own
3. Click to read all reviews
4. Reply to one of the reviews
5. Enter only blank spaces and tap on Publish reply
6. Enter text and observe the 'Publish reply' button

Expected result:
The 'Publish reply' button is active once text is introduced

Actual result:
The 'Publish reply' button looks like it is inactive

Notes:  
Tapping the "apparently inactive" button once text is introduced will publish the reply
This can be reproduced only on device (AMO-dev - FF58, Android 7.0)
Relates to [#3415](https://github.com/mozilla/addons-frontend/issues/3415)

Video for the issue:
![publish button](https://user-images.githubusercontent.com/31961530/31497937-3f63687a-af69-11e7-8b10-78f03ad92f20.gif)

**Comment by kumar303** [comment]
This is working as expected. A user should not be able to publish a blank reply because that would be confusing. How would an empty reply be helpful? I [made a typo in the issue you mentioned](https://github.com/mozilla/addons-frontend/issues/3415#issuecomment-336166466) which I think is what caused the confusion. Sorry about that.

**Comment by kumar303** [comment]
If I misunderstood the issue just let me know.

**Comment by kumar303** [comment]
I think I may know what you are referring to. When you have your mouse hovering over the Publish button, it has a hover style that makes the button look disabled.

**Comment by kumar303** [comment]
Was that it?

**Comment by AlexandraMoga** [comment]
@kumar303 : the issue described by me does not imply that the user should be allowed to submit an empty review. 
I was pointing specifically to the way the "Publish reply" button is behaving when making an attempt to leave an empty review and then typing actual text.
When the text field contains only blank spaces, the Publish button is disabled, which is correct. But if the user tries to type text after attempting to submit an empty review, the button still looks as it was inactive.
Hope this makes more sense now. If not, I will try to make the scenario more clear.

**Comment by kumar303** [comment]
> the button still looks as it was inactive.

This is just because your mouse was hovering over the button. Try moving your mouse cursor off of the button. I don't think you'll be able to reproduce it anymore.

**Comment by AlexandraMoga** [comment]
As mentioned in the bug, this can be reproduced only on device, so the mouse hovering does not apply.
What you see in the gif is the actual reproduction from my device screen, but I use the mouse pointer to make it more clear in the video what options are selected.

**Comment by kumar303** [comment]
Thanks for the extra info. It still is related to the hover state but there is a mobile-only bug in here that's worth fixing. I can reproduce it now.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 Android 7.0

![publish reply fix](https://user-images.githubusercontent.com/31961530/31599532-87c2bfb8-b25b-11e7-9808-4d83267d6b50.gif)
