### ISSUE TITLE
Hero content is not rendered on the server

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3461]
If JS is off there will be no content in the top of the homepage.

**Comment by ValentinaPC** [comment]
Please add some STR for us to check this. Thanks!

**Comment by tofumatt** [comment]
If JS is disabled, when you load the homepage make sure the three hero images (one of Featured Extensions, Privacy, ublock, YouTube hd) are loaded. Previously we had a bug where they wouldn’t load on the server, just the client.

**Comment by ValentinaPC** [comment]
Is there a way that I could see "server" side?
I think that I only have access to client side.

**Comment by willdurand** [comment]
@ValentinaPC can you see it if you disable JavaScript?

**Comment by ValentinaPC** [comment]
Yes, I can, but I was trying to reproduce the initial issue.

**Comment by willdurand** [comment]
You get the server side rendering when you disable JS.

**Comment by ValentinaPC** [comment]
Verified as fixed, using the above indications, on AMO-dev FF56(Win 7).
While JS is disabled, all "heroes" are listed and functional.
![js-disabled](https://user-images.githubusercontent.com/15685960/31550151-0efa8698-b039-11e7-9a5c-c19e737ce8e8.png)
