### ISSUE TITLE
Create curated collections in -dev and -stage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3463]
The following collections are needed in -dev and -stage, under the `mozilla` umbrella:
Prod
- [ad-blockers](https://addons.mozilla.org/firefox/collections/mozilla/ad-blockers/)
- [bookmark-managers](https://addons.mozilla.org/firefox/collections/mozilla/bookmark-managers/)
- [password-managers](https://addons.mozilla.org/firefox/collections/mozilla/password-managers/)
- [watching-videos](https://addons.mozilla.org/firefox/collections/mozilla/watching-videos/)

Dev

- [x] [ad-blockers](https://addons-dev.allizom.org/firefox/collections/mozilla/ad-blockers/)
- [x] [bookmark-managers](https://addons-dev.allizom.org/firefox/collections/mozilla/bookmark-managers/)
- [x] [password-managers](https://addons-dev.allizom.org/firefox/collections/mozilla/password-managers/)
- [x] [watching-videos](https://addons-dev.allizom.org/firefox/collections/mozilla/watching-videos/)

Stage

- [x] [ad-blockers](https://addons.allizom.org/firefox/collections/mozilla/ad-blockers/)
- [x] [bookmark-managers](https://addons.allizom.org/firefox/collections/mozilla/bookmark-managers/)
- [x] [password-managers](https://addons.allizom.org/firefox/collections/mozilla/password-managers/)
- [x] [watching-videos](https://addons.allizom.org/firefox/collections/mozilla/watching-videos/)

**Comment by muffinresearch** [comment]
Done

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7) .
AMO stage could not be verified because new shelfs where not yet implemented. 
I'll leave this open, until it can be checked in -stage.

**Comment by ValentinaPC** [comment]
@muffinresearch : I have a situation :(
I've edited one of the collection added above, on AMO-dev,, to see of things work, but while in the edit coll page, no name was listed. To save changes, I needed to add a name for this coll....and I've manage to broke it - and now returns a 404 page.
The availability of these collection without the possibility of edit, is not very helpful.

What do you think?

**Comment by ValentinaPC** [comment]
Clarified my last question on IRC.
