### ISSUE TITLE
Prevent a tap on mobile from triggering hover styles in buttons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3464]
### Describe the problem and steps to reproduce it:

* Create a component with a button
* Give the button a hover style
* Use the button mobile

### What happened?

You have to tap the button twice. The first tap will trigger the hover style.

### What did you expect to happen?

You should only need to tap the button once and it should not enter the hover style.

### Anything else we should know?

If you use our common Button component and give it an `href` then it will be rendered as an anchor tag and this prevents the tap-hover behavior. It's easy to forget about adding an `href` though. Also, rendering an anchor tag can make forms inaccessible. 

Another possibility is to put a touch / no-touch class on the body and use that in each style rule to disable hover. However, I'm not sure if that fixes the double-tap problem or not.

**Comment by willdurand** [comment]
@kumar303 is this issue also related to https://github.com/mozilla/addons-frontend/issues/2594?

**Comment by kumar303** [comment]
Yeah, I'm pretty sure this was fixed in Firefox 62 so we don't need to worry about it, per https://github.com/mozilla/addons-frontend/issues/2594#issuecomment-438481007
