### ISSUE TITLE
Consider removing FastClick

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3465]
### Describe the problem and steps to reproduce it:

We use the [FastClick](https://github.com/ftlabs/fastclick) library but it might not be necessary anymore.

### What happened?

According to their README:

> Note: As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and **risks introducing bugs into your application**. Consider carefully whether you really need to use it.

## What should we do?

We should remove this dependency.

**Comment by muffinresearch** [comment]
@willdurand would be good to understand whether FF Android has still got that issue or not. IIRC it did when we implemented it.
