### ISSUE TITLE
Pulsing during page load may be an accessibility concern

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-frontend#3466]
The animation when search results load has a pulsing effect and if the response takes a while, it may become an accessibility concern.

**Comment by muffinresearch** [comment]
It would be good to carry out some user testing to find out if this is a problem. Also it would be interesting if any of @pwalm's recent testing discovered any feedback from users in relation to this.

**Comment by muffinresearch** [comment]
I haven't seen any other reports of this being an issue. I'm going to close this for now, but we should definitely re-open this if we hear any further reports of this being a problem.
