### ISSUE TITLE
Collections not updated on the client

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3482]
### Describe the problem and steps to reproduce it:

1. Go to the "Block ads" collection from homepage
2. Return to the homepage
3. Navigate to the "Change your tabs" collection

### What happened?

You still get the old content, i.e. the data of the "Block ads" collection

### What did you expect to happen?

The new collection "Change your tabs" is loaded

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
This is still happening.
Please see video:
![old](https://user-images.githubusercontent.com/15685960/31536934-2d78819a-b009-11e7-929c-002886cbb8fe.gif)

**Comment by willdurand** [comment]
@ValentinaPC this is likely another bug related to the 404 error you get with non-existent collections. This should not happen as the collections should exist, but I agree there is something else to fix (but maybe not here).

**Comment by willdurand** [comment]
So I think we should track this 404 bug in #3313, because it is related.

**Comment by muffinresearch** [comment]
@ValentinaPC the collections that were missing on -dev have now been added via https://github.com/mozilla/addons-frontend/issues/3463

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
After adding these collection, the initial issue is no longer reproducing.
Postfix video:
![cool](https://user-images.githubusercontent.com/15685960/31608266-6d686e48-b278-11e7-8801-e7c93ab86bed.gif)
