### ISSUE TITLE
More... dropdown doesn't work over the hero elements

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#3484]
### Describe the problem and steps to reproduce it:
1. Go to the homepage on desktop
2. Hover over menu, dropdown opens
3. Hover over the first link, it gets highlighted
4. Hover over the second link (which is above the hero)

### What happened?
The dropdown was closed.

### What did you expect to happen?
The second link becomes highlighted.

### Anything else we should know?
![more-menu mov](https://user-images.githubusercontent.com/211578/31520868-02f16078-af6d-11e7-9f09-dd103a242507.gif)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7)
Postfix video:
![more](https://user-images.githubusercontent.com/15685960/31549512-1df41d50-b037-11e7-96bd-41d0b5a01e42.gif)
