### ISSUE TITLE
Extension Icon Is Blurry

### ISSUE THREAD

**Issue by patrickdark** [mozilla/addons-frontend#3486]
### Describe the problem and steps to reproduce it:
1. Go to the extension page at https://addons.mozilla.org/firefox/addon/ksftd/.
2. If necessary, click "View Mobile Site" to view the site using the new front-end.

### What happened?
The extension icon (shown at the top-left of the page) has blurry edges.

### What did you expect to happen?
The extension icon should have crisp (not blurry) edges like in the Firefox 57 UI. The proper rendering is shown on the extension's about:addons "Options" button page.

**Comment by willdurand** [comment]
Hi @patrickdark, thanks for your report.

Based on my understanding, it looks like an issue with the icon itself. An icon with a higher resolution (larger size) would probably render crisp edges, or am I missing something?

**Comment by patrickdark** [comment]
@willdurand The extension includes a 96×96 icon and is rendering a 64×64 icon that's blurry. The extension also includes a 48×48 icon which is seemingly what's being rendered.

Both the 48×48 and 96×96 icons are declared in the extension's manifest in that order.
