### ISSUE TITLE
Drop-down options have display issues

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3488]
Steps to reproduce:
1. Load AMO-prod page on your device https://addons-dev.allizom.org/en-US/android/
2. Tap "More..."

Expected results:
A drop down list is displayed without any display or layout issues.

Actual results:
Options inside the drop down are not very clear.

Notes/Issues:
- reproducing also for some options inside account menu.

Verified on AMO-prod FF56(Win 7, Android 7.2.1)
Screenshots:
![2017-10-13_1056](https://user-images.githubusercontent.com/15685960/31535859-52ac3fdc-b005-11e7-93c9-c16ad1e189e2.png)
![d](https://user-images.githubusercontent.com/15685960/31535871-56192676-b005-11e7-912a-2361de644d08.png)

**Comment by willdurand** [comment]
This is the white text of the hero banner that does that. It seems to appear on top of the dropdown menu (z-index).

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7, Android 7.2.1) and **the issue is still reproducing** as follows:
- on desktop for the account menu. if hero element under
![acc](https://user-images.githubusercontent.com/15685960/31547371-bfed9850-b02f-11e7-97d3-150c1257e382.png)
- on device for More... menu
![2017-10-13_1603](https://user-images.githubusercontent.com/15685960/31547465-1ba92e0c-b030-11e7-8190-e8e1d641d5f2.png)

**Comment by willdurand** [comment]
@ValentinaPC the fix has been deployed in -dev, you should be able to see it!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Postfix screenshots:
![desk](https://user-images.githubusercontent.com/15685960/31549327-835cef42-b036-11e7-8bbb-2f2969cc78be.png)
![2017-10-13_1650](https://user-images.githubusercontent.com/15685960/31549355-99337566-b036-11e7-9892-75934a344e7e.png)
