### ISSUE TITLE
Safari header grid moves around

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3497]
Visit https://addons.mozilla.org in safari and you'll see something like this (this is RTL) but you get the idea:

<img width="1855" alt="localhost_3000_ar_firefox_themes_" src="https://user-images.githubusercontent.com/1514/31558476-da9de79e-b044-11e7-9e2b-dbbe884f1335.png">

Navigate and the login button part off-screen in the screenshot above moves backwards and forwards.

Here's a gif showing the craziness that ensures:

![safari-weirdness](https://user-images.githubusercontent.com/1514/31559003-fe6d27fa-b046-11e7-978d-b0a528f7d8ec.gif)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with Safari 11.0 macOS 10.12.6

![header menu](https://user-images.githubusercontent.com/31961530/31606355-8942b558-b271-11e7-9cf7-52e4a8968f72.gif)
