### ISSUE TITLE
Search results summary have issues with long unbroken strings.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3499]
Summary goes too wide:

<img width="1404" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31560084-e2fa68a8-b04a-11e7-889c-7ce198f86788.png">

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56, Win10

Postfix:
![image](https://user-images.githubusercontent.com/31961530/31606936-345b85ae-b273-11e7-8a0f-323e70949b54.png)
