### ISSUE TITLE
Search box length was regressed

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3501]
In fixing the header the search box is smaller in large viewports:

On prod:

<img width="1360" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31560352-d94d1c8c-b04b-11e7-897d-c5210f4deeb1.png">

Locally:

<img width="1400" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31560377-fb34ea3c-b04b-11e7-944a-8ff51eeef6c2.png">

**Comment by AlexandraMoga** [comment]
Verified this on FF56 with Windows 10 and macOS 10.12.6. However, I wasn't able to spot a difference between the Search box layout on either of the systems or AMO servers.

Production:
![image](https://user-images.githubusercontent.com/31961530/31618583-037d4850-b29b-11e7-863c-cf82fee9984c.png)


-Dev:
![image](https://user-images.githubusercontent.com/31961530/31618554-f070c728-b29a-11e7-9887-1cb9f231f435.png)

@muffinresearch : Am I missing some verification steps here?

**Comment by willdurand** [comment]
@AlexandraMoga hi, you should not see any difference between the width of the search bar in -dev and its width in production. According to your screenshots, it looks ok to me.

**Comment by AlexandraMoga** [comment]
@willdurand Thanks a lot for clarifying this.
