### ISSUE TITLE
More link is mis-aligned in safari

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3503]
<img width="656" alt="localhost_3000_ar_firefox_" src="https://user-images.githubusercontent.com/1514/31561428-b9bb9962-b04f-11e7-8ca0-2bd765743475.png">

**Comment by ekowahyusantoso** [comment]
I want porn anonymoX film and vidio

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Safari 11 (Mac OS 10.13)
Postfix screenshot:
![2017-10-17_1438](https://user-images.githubusercontent.com/15685960/31662992-3dac79ac-b349-11e7-8ac8-b7954c742f61.png)
