### ISSUE TITLE
Fix small header movement when mousing over Explore

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3505]
![small-header-movement](https://user-images.githubusercontent.com/1514/31563958-0ac33e60-b059-11e7-9d4e-c7b21c011894.gif)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev Safari 11 (Mac OS 10.13)
Postfix video:
![explore](https://user-images.githubusercontent.com/15685960/31663280-25137f0c-b34a-11e7-9c1d-da295946d783.gif)
