### ISSUE TITLE
Read More is invisible on Firebug AddOn Page

### ISSUE THREAD

**Issue by B00ze64** [mozilla/addons-frontend#3508]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/addon/firebug/
In the "About This Extension" box bottom right, the "Read More" text at the bottom of the box is invisible.
### Anything else we should know?
FF52ESR, using "Mobile Site" to access new AMO.

![image](https://user-images.githubusercontent.com/15389810/31572753-ce07b3f8-b07a-11e7-8810-f5a2128f5820.png)

**Comment by muffinresearch** [comment]
I think this is probably fixed by https://github.com/mozilla/addons-frontend/pull/3510

**Comment by B00ze64** [comment]
Sorry, still happening :-(
