### ISSUE TITLE
Screenshots overflow on ESR

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3509]
See: https://addons.mozilla.org/en-US/firefox/addon/firebug/ using FirefoxESR 52.4.1

<img width="1692" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31575578-f428ca88-b0e1-11e7-99cb-6aa178e1531c.png">

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF52.4.1 (Win 7).
Screenshots section is fixed.
Postfix screenshot:
![esr](https://user-images.githubusercontent.com/15685960/31655170-b9b05c80-b330-11e7-97fa-ae56f0e0bbae.png)
