### ISSUE TITLE
'Read More' link appears even when content is full

### ISSUE THREAD

**Issue by Marat-Tanalin** [mozilla/addons-frontend#3511]
In the new AMO frontend, texts in blocks “About this extension” and “Release notes” on addon’s page is shrinked even if there is enough space to show the text entirely. See the screenshot below.

Shrinking could probably be smarter. Thanks.

![a-shrinked](https://user-images.githubusercontent.com/1833563/31577032-cf2868dc-b10f-11e7-970c-15d6d1120a72.png)

**Comment by muffinresearch** [comment]
We're planning not to do this at all on desktop so it's only done where necessary. 

Superceded by https://github.com/mozilla/addons-frontend/issues/3787
