### ISSUE TITLE
[desktop] HomeHeroBanner overlaps search autocomplete

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#3512]
### Describe the problem and steps to reproduce it:
Navigate to https://addons.mozilla.org/en-US/firefox/
put something in search box say `mea`

### What happened?
Auto suggest drop down is overlapped by hero-contents

### What did you expect to happen?
auto suggest shouldn't be overlapping.

### Anything else we should know?
Reproduced only on Production and Staging
<img width="525" alt="screen shot 2017-10-15 at 1 25 32 pm" src="https://user-images.githubusercontent.com/5318732/31582895-5f57a2c2-b1ad-11e7-98b1-889eca465e6a.png">

**Comment by ValentinaPC** [comment]
I think this was fixed in https://github.com/mozilla/addons-frontend/issues/3488.
You can see the fix on -dev.
Thanks!

**Comment by tsl143** [comment]
Duplicate of #3488
