### ISSUE TITLE
Author name can be hidden in add-ons details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3516]
Steps to reproduce:
1. Modify your display name with "<? name >" in AMO-dev - https://addons-dev.allizom.org/en-US/firefox/users/edit
2. Access details page for an add-on you've submitted

Expected results:
Author name is displayed.

Actual results:
Author name is not displayed. Old desktop page display author name.

Notes/Issues:
- not hidden from account menu
Verified on AMO-dev FF56(Win 7).
Video for this issue:
![nodisplay](https://user-images.githubusercontent.com/15685960/31604706-ca7c49c6-b26c-11e7-8845-2257844bac32.gif)
![2017-10-16_1223](https://user-images.githubusercontent.com/15685960/31604754-efe00d7e-b26c-11e7-973b-d46ac17b208e.png)

**Comment by muffinresearch** [comment]
Looks like DOMPurify is removing what it sees as an unknown tag. We can fix this by escaping the name ahead of the DOMPurify santization.

**Comment by willdurand** [comment]
This has been fixed. I cannot reproduce anymore.

**Comment by AlexandraMoga** [comment]
Not reproducing either:

![image](https://user-images.githubusercontent.com/31961530/60710647-d51ea700-9f1b-11e9-837c-9edbb679103d.png)
