### ISSUE TITLE
Unbroken summary strings in Add-on details page are not wrapped

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3517]
Steps to reproduce:

1. Access the extension detail page of an add-on with a long unbroken summary (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/mingrafow-crafow-donbise/)
2. Notice the layout of the Add-on summary 

Expected result:
The add-on summary is wrapped

Actual result:
The summary spreads too wide, causing layout issues

Note: 
The issue is also observed in "About this extension" on the Add-on details page and in DevHub at "Edit information" section
Reproduces on all AMO servers with FF56 (Win10 and Android 7.0)
Related to [#3499](https://github.com/mozilla/addons-frontend/issues/3499#issuecomment-336842638l)

![image](https://user-images.githubusercontent.com/31961530/31608460-1d7bc352-b279-11e7-80c4-d21539447cf9.png)

![image](https://user-images.githubusercontent.com/31961530/31610132-9fce319a-b27f-11e7-86bb-73044f02ea52.png)

**Comment by muffinresearch** [comment]
Not the patch in this repo only addresses the issues on addons-frontend - the ones on the add-on devhub pages should be re-filed in addons-server.

**Comment by AlexandraMoga** [comment]
Summary text still appears unwrapped on device: 

![image](https://user-images.githubusercontent.com/31961530/31668056-cc197676-b359-11e7-8bf8-5b1ffb9f4729.png)


Note: for the desktop pages things are looking fine now:

![image](https://user-images.githubusercontent.com/31961530/31668139-0d68ec60-b35a-11e7-815c-3e9e477e17e1.png)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev and stage FF56 (Win10 and Android 7.1.2)

Postfix screenshot:

![image](https://user-images.githubusercontent.com/31961530/31719371-e3b03fbe-b41b-11e7-9b81-a99ba7df4b6a.png)
