### ISSUE TITLE
SuggestedPages component should link to "all" extensions and themes, not "featured" ones

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3518]
### Describe the problem and steps to reproduce it:

Navigate to an URL that triggers an error, like a 404, e.g.: https://addons-dev.allizom.org/en-US/firefox/collections/nope/nope/.

### What happened?

A list of suggested pages is displayed but the links are not correct:

- "Browse all extensions" redirects to the featured extensions page
- "Browse all themes" redirects to the featured themes page

### What did you expect to happen?

- "Browse all extensions" redirects to the list of all extensions
- "Browse all themes" redirects to the list of all themes

**Comment by vcarciu** [comment]
Verified as fixed : 
![wronglinks](https://user-images.githubusercontent.com/1583842/31663547-2888a63e-b34b-11e7-8322-41fc953af775.gif)
