### ISSUE TITLE
[i18n] Separate different usages of the word "featured"

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozilla/addons-frontend#3520]
### Describe the problem and steps to reproduce it:
The term "featured" (as single word) is used around 10 times and in several different contexts. In my language it is not appropriate for a category to be "featured" the same way as the add-on is. It is gender incompatible, it is wrong in terms of sequence of tenses (you get the picture).
### What happened?
There is only one string that is used site-wide.
### What did you expect to happen?
To have separate strings for every usage so that the translator have the opportunity to use correct translation for his locale.
### Anything else we should know?
Link to the term in Pontoon: https://pontoon.mozilla.org/en-GB/amo/all-resources/?search=featured&string=63947

For screenshots see https://github.com/mozilla/addons-server/issues/6500#issuecomment-331936868

**Comment by willdurand** [comment]
Hi, I just looked at our codebase and it seems the new frontend does not have any occurrence of the single word `Featured`.

**Comment by muffinresearch** [comment]
Going to close this as invalid since the bug doesn't exist in this repo based on https://github.com/mozilla/addons-frontend/issues/3520#issuecomment-336916658
