### ISSUE TITLE
DRY up the webpack loaders

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#353]
Currently we duplicate most of the loaders between the prod, dev and karma conf. We should look to DRY this up.

**Comment by muffinresearch** [comment]
Closed since we'll do this when updating to webpack 2

**Comment by kumar303** [comment]
Let's keep it open so we don't forget

**Comment by kumar303** [comment]
fixed in https://github.com/mozilla/addons-frontend/pull/2380
