### ISSUE TITLE
Featured add-ons are not displayed on device with "Add-ons for Android" selected, even if they are compatible 

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3537]
Steps to reproduce:
1.On Latest Nightly, AMO-dev, click on Featured Extension static panel under header
2.Observe that we have 2 extensions listed 
3.Go to manage versions page for the first one (https://addons-dev.allizom.org/en-US/developers/addon/webext-setinterval7/versions/1532652) and observe that it is compatible with Firefox for Android (it is also installable on devices)
4.Go back to amo-dev homepage(on new frontend) and from "More" section in the header, select "Addons for Android"
5.Repeat Step 1

Expected results:
Al least the add-on described at step 3 should be listed

Actual results:
No add-ons listed

NOTES:
Same behavior on Android device.
After Step 4 is done, a page refresh is needed 

Please see video for this issue : 
![androidfeatnotlisted](https://user-images.githubusercontent.com/1583842/31672892-66f92f68-b366-11e7-86d9-8e337a1810e6.gif)

**Comment by muffinresearch** [comment]
This one needs further investigation

**Comment by willdurand** [comment]
Featured add-ons will be gone soon, so I guess we can close this issue.
