### ISSUE TITLE
The active locale leaks between server responses

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3538]
### Describe the problem and steps to reproduce it:

I haven't been able to prove this but by reading the code, I think this is possible:

* Go to a page that displays a date or time
* Begin a request from one browser in the `en-US` locale
* Begin a request simultaneously from another browser in the `de` locale

### What happened?

Date/time data on the page may be rendered with the wrong locale

### What did you expect to happen?

Date/time data should always be rendered in the requested locale

### Anything else we should know?

The problem is that we use a `moment.locale(locale)` to set the local globally and then we pass the global instance to all components. Due to the asynchronous nature of the program (especially with saga processing), we cannot always rely on this global instance to be the right one.

The fix is to pass an instance of `moment` which will always be configured for the right locale:

```diff
diff --git a/src/core/i18n/utils.js b/src/core/i18n/utils.js
index 7260b3e1..f525c2ba 100644
--- a/src/core/i18n/utils.js
+++ b/src/core/i18n/utils.js
@@ -289,6 +289,6 @@ export function makeI18n(
 
   // We add a translated "moment" property to our `i18n` object
   // to make translated date/time/etc. easy.
-  i18n.moment = moment;
+  i18n.moment = moment();
   return i18n;
 }
```

However, this change breaks everything because our code is using the global localization functions. We have to replace code like this...

```js
const timestamp = i18n.moment(dateCreated).fromNow();
//     TypeError: i18n.moment is not a function
//         at AddonReviewListItemBase.render (/Users/kumar/dev/addons-frontend/src/amo/components/AddonReviewListItem/index.js:194:30)
//         ...
//         at Object.renderToString (/Users/kumar/dev/addons-frontend/node_modules/react-dom/lib/ReactServerRendering.js:71:10)
//         at hydrateOnClient (/Users/kumar/dev/addons-frontend/src/core/server/base.js:106:14)
//         at /Users/kumar/dev/addons-frontend/src/core/server/base.js:320:20
//         at process._t
```

...with some alternative. It's not immediately clear to me from the docs how we can replace it. We may need to introduce a proxy function that allows you to get a new moment instance configured with the same locale.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10)

Verified by opening the "Change up your tabs" collection separately in /en-US/ and /de/ and requested a tab refresh:

![de_en_refresh](https://user-images.githubusercontent.com/31961530/32721553-84824ede-c86f-11e7-8b0b-fa6ec53c845a.gif)
