### ISSUE TITLE
"Download Firefox" links have inconsistent URLs

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3540]
If you go to [this page](https://addons.mozilla.org/es/firefox/addon/adblock-57/) using Chrome, you'll see a "Download Firefox" ("Descargar Firefox") button at the top right of the page, and another one in a red message below the disabled install button.

They point to different paths:
https://mozilla.org/firefox/
https://www.mozilla.org/es/firefox/

The first one is probably best, since it delegates localization to the browser settings, rather than force it to use the same as AMO (also doesn't have the `www`).

**Comment by willdurand** [comment]
This has been fixed in #3805

**Comment by ValentinaPC** [comment]
Verified as fixed on Chrome Version 62.0.3202.89 using Win 7.
Postfix video:
![same links](https://user-images.githubusercontent.com/15685960/32734110-b9df485a-c899-11e7-8d43-d87b96379b65.gif)

@willdurand Using the second link option for redirection page is intended, as Jorge suggested using the first? Thanks!

**Comment by willdurand** [comment]
@ValentinaPC this issue has been superseded by #3803.
