### ISSUE TITLE
Move the download firefox button

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3541]
This button is inline as part of the content, this means it's in a slightly weird place and it makes doing responsive styling more difficult. 

I think we could have this be more of a banner or overlay which is seen once and dismissed.

<img width="618" alt="componenti_aggiuntivi_per_firefox" src="https://user-images.githubusercontent.com/1514/31679882-856a1564-b340-11e7-8d15-383a780d07b1.png">

**Comment by pwalm** [comment]
Let's move it to a notification bar:
![screen shot 2017-12-04 at 11 03 38 am](https://user-images.githubusercontent.com/6797635/33570787-d45a9410-d8e2-11e7-9f9f-0029d5701ec9.png)

**Comment by caitmuenster** [comment]
Hey @richa031, welcome! If you're new to open source, you probably want to get started with some issues tagged `good-first-bug`. :) 

Want to check out our [onboarding documentation](https://wiki.mozilla.org/Add-ons/Contribute/Code) and then look for another issue?

**Comment by richa031** [comment]
Can you please help me finding them, as I can't find these tags anywhere

**Comment by willdurand** [comment]
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by willdurand** [comment]
@muffinresearch do we still want to do that?
