### ISSUE TITLE
Out of range search results pages should be a 404

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3542]
https://addons.mozilla.org/en-US/firefox/search/?page=30000&platform=mac&q=search

Currently if you attempt to load a page with an out of range page you get a loading page:

<img width="1375" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31684481-f1292896-b34d-11e7-9209-97186f319c3b.png">

**Comment by willdurand** [comment]
I think this is related to #3313: client and server don't generate the same error handler id, thus the client is not aware of the error and the page gets stuck. And it seems the server does not render the 404 by itself.

**Comment by muffinresearch** [comment]
Duplicate of #3313
