### ISSUE TITLE
Curated collection links are very bright

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3543]
See https://addons-dev.allizom.org/en-US/firefox/

The new collection links are using new photo colours. In context these links are so bright I can't really see any other content on the page because my eye is drawn to the brightness. 

Perhaps it would be possible to reduce the intensity of the colours?

<img width="1411" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31689495-953e3a20-b35d-11e7-9ec9-7ec0c26c7d97.png">

**Comment by pwalm** [comment]
Sure, take the 50 colours down to 70

**Comment by vcarciu** [comment]
@willdurand : Is this on -dev?

**Comment by willdurand** [comment]
@vcarciu the collections yes, the fix for this issue, no, not yet.

**Comment by vcarciu** [comment]
@willdurand : my bad, I had the feeling that the issue was closed, but I was just blind

**Comment by willdurand** [comment]
@vcarciu it is now :D

**Comment by vcarciu** [comment]
Verified as fixed : 
![colors](https://user-images.githubusercontent.com/1583842/31758792-8ea63040-b4b7-11e7-947a-dc91f3dda73a.png)
