### ISSUE TITLE
No search results message has no background or rounded corners

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3545]
<img width="1378" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31692241-011150b2-b367-11e7-984f-50d3910359ec.png">

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.1.2)

![image](https://user-images.githubusercontent.com/31961530/31722309-6e68e856-b424-11e7-8246-66ccf8f31a57.png)
