### ISSUE TITLE
Show compatibility info on "all versions" page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#3547]
It's useful to show the compatibility info of a(n old) version of an add-on–see #3507. When we implement an "all versions" page on the new front-end we should make sure to list explicit compatibility info for each version, as this page will be for reasonably technical users anyway.

**Comment by willdurand** [comment]
Looks like this has been implemented:

![Screen Shot 2019-04-18 at 17 25 58](https://user-images.githubusercontent.com/217628/56372338-0fbb5200-61ff-11e9-8061-63ec0f822321.png)
