### ISSUE TITLE
404 page is loaded for an existing collection

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3548]
Steps to reproduce:
1. Load a collection page that returns a 404 i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/ad-blocker/
2. Go back to homepage
3. Go to an existing collection page i.e https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/change-up-your-tabs/

Expected results:
Collection page si loaded.

Actual results:
A 404 page is loaded.

Notes/Issues:
- reproducing only in case of collections vs. collections.
- issue fixed at page refresh

Verified on AMO-dev FF56(Win 7). Reproducing on all AMO servers.
Video for this issue:
![404](https://user-images.githubusercontent.com/15685960/31710431-b0dab722-b3fd-11e7-9233-0bca134e70cf.gif)

**Comment by willdurand** [comment]
Hello. Yes, you have actually reported this in a previous issue and it is being tracked in #3313.

**Comment by ValentinaPC** [comment]
Just wanted to be sure, we do not forgot about this in the issue you mentioned :P

**Comment by muffinresearch** [comment]
@willdurand is this actually a case of #3313 or is it more related to the different collection slug not being noticed?

**Comment by willdurand** [comment]
It is related to #3313 and I work on both in parallel. The problem here is due to the synchronization between the client and server error handlers.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7)
The issues is still happening:
![404](https://user-images.githubusercontent.com/15685960/32652948-be9663b6-c60e-11e7-968f-49f9cc798f5d.gif)

**Comment by willdurand** [comment]
It has not been deployed in -dev yet, investigating...

**Comment by willdurand** [comment]
should be in -dev now.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix video:
![404-coll](https://user-images.githubusercontent.com/15685960/32727058-d7163282-c883-11e7-85b3-22a5a18d8855.gif)
