### ISSUE TITLE
In drop down menus, when navigating via keyboard, focus should not jump out of the drop down menu until it is closed

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3550]
Steps to reproduce:
1.In AMO-dev, navigate to any drop down menu(More or Username) via keyboard(Tab) and press Enter
2.When drop down menu is collapsed, navigate through options by pressing Tab on keyboard

Expected results:
When reaching the last option, one more Tab press should focus the first option on the drop down(basically user should stay inside the opened drop down menu )

Actual results:
The next option on site is selected and user is not able to go back in the drop down menu without going through entire site with the keyboard

NOTES:
Reproduced in AMO-dev, FF Release

Please see video for this issue:
![tabbing](https://user-images.githubusercontent.com/1583842/31722295-65d18a18-b424-11e7-8d80-e038e6277949.gif)

**Comment by muffinresearch** [comment]
@vcarciu can you provide examples or citations where this is expect / seen elsewhere? I could be convinced otherwise but I generally thought that focus trapping was seen as a bad practice.

**Comment by vcarciu** [comment]
I am sorry for late response, but I was on PTO. 
I saw that in another applications (ie, my gmail account), but I was not aware that this is a bad practice. My opinion is that if you have to use the Tab, then it is a time consuming action to come back to a drop down menu if you accidentally pressed Tab at the last item of drop down.

Example of what I saw on my email : 
![tabbing](https://user-images.githubusercontent.com/1583842/36098865-41863316-1009-11e8-9c69-1410037ec791.gif)
