### ISSUE TITLE
Bring the subject shelves back on homepage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3552]
The subject shelves (see screenshot below) have been removed from the homepage in https://github.com/mozilla/addons-frontend/pull/3460 according to the editorial google doc., but it looks like users like them so we need to add them again (with a slightly different content though).

![](https://user-images.githubusercontent.com/1514/31491473-591d17e0-af3f-11e7-9d6d-c7fa27d08f09.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Postfix screenshots:
![d1](https://user-images.githubusercontent.com/15685960/31930851-deb1705e-b8a9-11e7-9cf9-a30919299ffe.png)
![d2](https://user-images.githubusercontent.com/15685960/31930852-ded20490-b8a9-11e7-89fc-99152f930901.png)
![m1](https://user-images.githubusercontent.com/15685960/31930853-def17b72-b8a9-11e7-8d92-ff39bb51722d.png)
![m2](https://user-images.githubusercontent.com/15685960/31930854-df103f94-b8a9-11e7-9719-70019312a0ff.png)
