### ISSUE TITLE
Report abuse button is too prominent

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#3553]
### Describe the problem and steps to reproduce it:
https://www.dropbox.com/s/a7bfp2ip84mz1gp/Screenshot%202017-10-18%2010.28.56.png?dl=0

In the new design, the Report Abuse button is too prominent; it comes before ratings and is more noticeable than ratings. We should move it below ratings and make it less prominent.

**Comment by tofumatt** [comment]
This is where it was in the mocks and I think it’s important to give users the chance to report abuse for an add-on, especially now that we do automatic reviews.

@pwalm–what are your thoughts here? :-)

**Comment by muffinresearch** [comment]
This was flagged as mvp on the basis that the CTA for report abuse is more prominent than the install button. Moving the position is less critical but is presumably fairly simple to do.

**Comment by tofumatt** [comment]
It should be below ratings once they move up, as per the mocks. For now I've made it less prominent in terms of size and colour; I've also increased the size of the "Add to Firefox" button in #3577.

**Comment by pwalm** [comment]
- Move "Rate your experience" block above "More info" block
- "Report Abuse" button changes colour from red to grey, follow spec from [design system](http://design.firefox.com/photon/components/buttons.html):
<img width="775" alt="screen shot 2017-10-20 at 9 13 51 am" src="https://user-images.githubusercontent.com/6797635/31831086-124b150e-b577-11e7-9c2a-7a2739a28aa8.png">

New mocks below:
![extension detail - 1366px](https://user-images.githubusercontent.com/6797635/31831097-1a678f6a-b577-11e7-9534-e6bf68f3fc72.png)

![theme detail - 1366px](https://user-images.githubusercontent.com/6797635/31831108-23da4a06-b577-11e7-8f02-cd0d77f610c3.png)

**Comment by vcarciu** [comment]
Verified the changes added in #3577 and everything looks ok : 
![abuselittle](https://user-images.githubusercontent.com/1583842/31892518-e5bda1a8-b811-11e7-8fb1-03e69f690791.png)

Also , after talking with @tofumatt , the button will change on device too following the new mocks.
