### ISSUE TITLE
Clicking on author name on the detail page opens new tab

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#3554]
On an add-on detail page, when you click on the author's name underneath the name of the add-on, a new tab opens that takes you to the user profile page.

It should not open a new tab.

**Comment by muffinresearch** [comment]
The reason for this is that the purification setup has a hook added that defaults to target="_blank" for all links. This was necessary for the disco pane but it's not necessary for amo. We need to provide a domPurify instance that doesn't have this hook and one that does and use the right one in each case.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postifx video:
![author](https://user-images.githubusercontent.com/15685960/31939770-60d83efe-b8c4-11e7-824b-650e7eaabc07.gif)

@willdurand : On device, we wanna keep the old behavior?

**Comment by willdurand** [comment]
@ValentinaPC on which device?

**Comment by ValentinaPC** [comment]
On Android 7.2.1 using FF56 and AMO-dev while clicking on author name, the corresponding page was loaded in a new tab.
Seem to be working now.

Will mark this verified-fixed.
Thanks, @willdurand !

**Comment by muffinresearch** [comment]
@ValentinaPC did you check the disco pane is still loading links in a new tab? If not It'll be worth checking that since that's part of the code affected by this.

**Comment by ValentinaPC** [comment]
Verified this on disco pane also and all links are loaded in new tabs, as expected.
