### ISSUE TITLE
Make the Tooltip Menu fully keyboard accessible

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3556]
The `TooltipMenu` component added in https://github.com/mozilla/addons-frontend/issues/3534 is not fully keyboard accessible. In the interest of preserving forward momentum, let's try and tackle this in a separate issue.

A helpful guide: http://heydonworks.com/practical_aria_examples/#progressive-collapsibles

**Comment by kumar303** [comment]
Related: https://github.com/react-component/tooltip/issues/93

**Comment by vcarciu** [comment]
@kumar303 : we should definitely fix #3550 before closing this.

**Comment by vcarciu** [comment]
Forgot to add the video where you can see why I added previous comment : 
![tabdoi](https://user-images.githubusercontent.com/1583842/31940007-3b87a558-b8c5-11e7-92c4-f5b49e0fbb43.gif)

**Comment by kumar303** [comment]
> Forgot to add the video where you can see why I added previous comment

Can you file a new bug for that? I don't think https://github.com/mozilla/addons-frontend/issues/3550 is related because the header dropdown is separate from the flag-review menu.

The video you posed is definitely a bug that needs fixing but I think this one should remain closed because the patch made progress towards keyboard accessibility.

**Comment by kumar303** [comment]
^ there, I edited the title 😄

**Comment by vcarciu** [comment]
@kumar303 : I will open another bug, but I think that the root problem is the same(drop down menu should not be left when navigating with keyboard inside it).
I agree that this can be closed since the menu is accessible now via keyboard.
Marking this as verified.
