### ISSUE TITLE
Launch Content for Explore Page

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3558]
- Content displayed in the image below is accurate and matches to @devaneymoz's [launch content doc](https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit#)
- Make sure copy matches what is in the doc/mock up
- Icons are already designed and in the repo
- Theme icons should link to their respective categories, while the extension icons will link to the collections @devaneymoz has made

![explore - launch content - 1366px](https://user-images.githubusercontent.com/6797635/31736389-757be9fc-b3f9-11e7-96b0-c143f9675e5c.png)

**Comment by pwalm** [comment]
Oh, and the text size under the icon is bumped up from `title13` to `title17`

**Comment by willdurand** [comment]
Working on it :)

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF56(Win 7).
Explore page looks like above.
Postfix screenshot:
![2017-10-24_0953](https://user-images.githubusercontent.com/15685960/31928583-543d680e-b8a1-11e7-9473-cb5804873f82.png)

The 2 new collections added have no corresponding pages on dev (and return a 404 page), could we add them?
I am talking about:
- Smarter Shopping
- Productivity

**Comment by muffinresearch** [comment]
@ValentinaPC I've filed a separate bug for that here: https://github.com/mozilla/addons-frontend/issues/3617

**Comment by devaneymoz** [comment]
@pwalm for the extension and theme subject shelves, I was thinking we do NOT need the headline parts: "Extensions change the way Firefox works" and "Themes change the way Firefox looks" respectively. 

The new copy (which sits under the headlines) was intended to be stand-alone. As it currently is here it's redundant messaging. Can we simply remove the current headlines for these sections and make the  subheds the headlines?

**Comment by kumar303** [comment]
@devaneymoz yeah, I raised that issue here too: https://github.com/mozilla/addons-frontend/pull/3585#issuecomment-338734117

I agree that they are redundant so I filed this to remove them: https://github.com/mozilla/addons-frontend/issues/3621

**Comment by pwalm** [comment]
Ok! Remove the headlines. 👍

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
"Explore" page was added and looks as expected.
Other issues, related with things that still need fixing were logged separately.
We can mark this verified fixed.
