### ISSUE TITLE
Home page shows descriptions at specific widths

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#3559]
When you resize the home page, there seems to be a specific width that will show the descriptions and then they go away. Wasn't sure if that was intentional or not.

https://www.dropbox.com/s/229hf9ivqhcjt2y/description-resize.mov?dl=0

**Comment by tofumatt** [comment]
Yup, this is intentional; the smaller sizes are largely mobile screens and descriptions end up consuming a lot of real estate then, especially because the add-ons are stacked on top of each other.
