### ISSUE TITLE
Install switch doesn't work with an extension that is partially (?) uninstalled

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#3562]
### Describe the problem and steps to reproduce it:
1. Install an extension, like https://addons.mozilla.org/en-US/firefox/addon/tabby-cat-friend/.
    * Leave this window open.
2. Open the Add-ons manager in a new window.
3. Remove the extension.
    * You should see the "You removed The Extension. **Undo**" text.
4. Go back to the AMO page, the install button is still in the "uninstalling" state (grey stripes).
5. Refresh AMO, button looks functional.
6. Click the button, nothing happens.
7. Refresh the Add-ons manager window.
8. Install the add-on again
    * This time it should work.

### What happened?
The add-on isn't installed all the way until the user navigates away from the add-on manager. I tried to figure out what events were being triggered but I couldn't get a breakpoint to work on the live site for some reason.

### What did you expect to happen?
The install switch should still install the add-on if it is in this weird state (somehow?). It should also show that the uninstall is complete.

### Anything else we should know?
![uninstalled-install mov](https://user-images.githubusercontent.com/211578/31743644-690e9750-b421-11e7-991d-d37dcbdbd009.gif)

**Comment by muffinresearch** [comment]
Would be good to understand if this is a bug in the site or Firefox - this might be an issue in about:addons rather than the site if the uninstall event isn't being fired until about:addons is unloaded.

**Comment by mstriemer** [comment]
There may be some other event to listen to for uninstall. For installing it it might need to enable it instead of installing but I'm not sure.

**Comment by muffinresearch** [comment]
@mstriemer IIRC this happens because of the "undo" feature. You can undo the uninstall up to the point that you "commit" the change by navigating away from about:addons.

**Comment by muffinresearch** [comment]
This is somewhat related to https://github.com/mozilla/addons-frontend/issues/562 which can now be implemented since the bug to add that was added a while ago.

**Comment by willdurand** [comment]
Closing this issue in favor of #6164.
