### ISSUE TITLE
CSS isn't minified

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3564]
The CSS doesn't appear to be minified. See https://addons-amo.cdn.mozilla.net/amo-321654c630d69c27208050b742279e1a.css

**Comment by willdurand** [comment]
For QA: the style should load and the website should look nice.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on AMO dev with FF61(Win10). 
When the homepage loads I received a 200 response, with 
https://addons-amo-dev-cdn.allizom.org/amo-784a053dcab4de979264defdfa26df33.css 
Also, the website has no layout issues.
![stylesheetamo](https://user-images.githubusercontent.com/33448286/43776282-09711408-9a58-11e8-86e5-533943b036c2.png)

Is there anything else I should be checking? Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki that looks good to me
