### ISSUE TITLE
Remove "Site Identifier" from listing pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3567]
After some discussion we've decided to not show the add-on ID on the listing page. We might bring it back later on, but just visible to certain people. As long as the numerical ID can be found somewhere in the HTML code of the listing page, admins can figure it out.

**Comment by tofumatt** [comment]
I’m not sure if it’s anywhere else on the page in the HTML right now, but we could certainly add it in a comment.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshots:
![add-on](https://user-images.githubusercontent.com/15685960/31877010-8769fd7e-b7dd-11e7-8fbe-3be7a7d63905.png)
![themes](https://user-images.githubusercontent.com/15685960/31877011-8788af4e-b7dd-11e7-9471-600c1739e1c6.png)
