### ISSUE TITLE
Validate CSP directives in the server tests.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#357]
helmet csp doesn't appear to validate directives are valid so we should validate them ourselves just so that we can protect against mis-configuration and remove a potential foot-gun.

**Comment by phun-ky** [comment]
+1 for this, I need this in my project as well. I realize that this isn't the "helmet" issues, but I would be really interested in how you will solve this :)

**Comment by muffinresearch** [comment]
@phun-ky recent versions of helmet uses a strict mode by default so should protect much more against misconfiguration than it did in the past. On that basis I'm closing this issue.
