### ISSUE TITLE
Browser resize causes layout issues in Add-on details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3571]
Steps to reproduce:

1. Go to an Add-on details page (i.e. https://addons.allizom.org/en-US/firefox/addon/opoodcon-sealo-ramana/)
2. Resize your browser to a width between 750 - 1200
3. Observe the page layout in "More extensions by author" section

Expected result:
The  mentioned section is adapting when the browser is resized

Actual result:
The section will not be correctly displayed for the current browser size

The above steps can be reproduced on AMO-stage with FF56 (Win10)
Notes:
If the Add-on Name has a long unbroken string, the text will not be wrapped (this will reproduce  on all AMO servers and on device - Android 7.1.2 - in landscape mode)

Screenshots:

![image](https://user-images.githubusercontent.com/31961530/31781431-1bb61bf0-b501-11e7-8860-b814aa017bd7.png)

![image](https://user-images.githubusercontent.com/31961530/31781524-53f80cd0-b501-11e7-82d4-355249d4de55.png)

**Comment by AlexandraMoga** [comment]
I've verified this on AMO-dev and it looks like  the Add-on name is still not wrapped in the page header. Please have a look:

https://addons-dev.allizom.org/en-US/firefox/addon/mingrafow-crafow-donbise/

![image](https://user-images.githubusercontent.com/31961530/31808658-d6b00e7c-b57c-11e7-9e70-c2c5559d605e.png)

**Comment by willdurand** [comment]
I submitted a fix for this: https://github.com/mozilla/addons-frontend/pull/3590.

**Comment by vcarciu** [comment]
If the name of the developer is a longer string, then it will not be wrapped in  "More extensions by author" section after resizing the browser : 
![nameissues](https://user-images.githubusercontent.com/1583842/31894760-fb85e6ca-b817-11e7-8380-0f035ed058c8.png)

**Comment by muffinresearch** [comment]
@vcarciu ok I'll take a look.

**Comment by vcarciu** [comment]
Verified as fixed : 

Long Name:
![namenottruncated](https://user-images.githubusercontent.com/1583842/31940995-d54d419a-b8c8-11e7-8237-f1e5e8a54ae3.png)

"More extensions by author" section and dev name:
![devnameandmoreextsection](https://user-images.githubusercontent.com/1583842/31941041-f7b4f1e2-b8c8-11e7-9b05-9d8f92e0f50d.png)
