### ISSUE TITLE
Filtering by "Featured add-ons only" results in a 404 error for an inaccessible page number

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3579]
Steps to reproduce:
1.Go to AMO homepage and perform a string search (i.e. 'block' - https://addons-dev.allizom.org/en-GB/firefox/search/?platform=windows&q=block)
2.Navigate to the next pages
3. Filter by "Featured add-ons only"

Expected result:
Featured add-ons are displayed, according to the selected filter

Actual result:
An 'invalid result' is displayed and the page is stuck in loading mode

Notes:
Reproduced on all AMO servers with FF56 (Win10 and Android 7.1.2)

![404](https://user-images.githubusercontent.com/31961530/31825006-7bd7b288-b5b9-11e7-9063-ef154f251e7f.gif)

![image](https://user-images.githubusercontent.com/31961530/31825019-8260a0ec-b5b9-11e7-9d1f-24146b66cd57.png)

**Comment by willdurand** [comment]
Ah, I guess we should reset the page number on filter change...

**Comment by vcarciu** [comment]
Verified as fixed in FF56 (Win10) : 
![featuredpage](https://user-images.githubusercontent.com/1583842/31894291-aadd4a20-b816-11e7-9e8b-20e65aef416b.gif)

Everything looks good on Android device too.
