### ISSUE TITLE
Hovering over an outgoing URL should show the URL

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3580]
### Describe the problem and steps to reproduce it:

* Go to a page that has an outgoing URL. For example, go to an [add-on detail page](https://addons.mozilla.org/en-US/firefox/addon/first-party-isolation/) where a *homepage* or *support site* is listed.
* Hover over the URL on a desktop browser

### What happened?

You see a bizarro URL in the status bar, something like `https://outgoing.prod.mozaws.net/v1/7e6414285a7ee4ce71bb4c015a16d7bdc83c237522cb926da4d69feac27ebb58/https%3A//github.com/mozfreddyb/webext-firstpartyisolation`

### What did you expect to happen?

It should somehow indicate that you will be going to `https://github.com/mozfreddyb/webext-firstpartyisolation` when you click on it. 

### Anything else we should know?

Perhaps it could be shown as a tooltip.

---

**For QA:** it affects the following links:

- on the addon detail page:
  - contributions
  -  homepage
  - support_url

- on a blocklist block page:
  - the block request link

**Comment by tofumatt** [comment]
Yeah, even just a `title` attribute would do the trick.

**Comment by aayushsanghavi** [comment]
@tofumatt is this to be done for all <a> elements with no existing title attributes in the amo directory only or the others as well?

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

Mentor: @willdurand

**Comment by willdurand** [comment]
This change actually requires an API change, requested in https://github.com/mozilla/addons-server/issues/11206. Therefore, it's not a good first bug for contributors and the issue is currently blocked anyway (until the API issue is fixed).

**Comment by ioanarusiczki** [comment]
@willdurand 
- when hovering over homepage, support site or contribute now the URL a tooltip showing the URLs is shown which I think it's the expected result:

![frontend urls are shown at hover](https://user-images.githubusercontent.com/33448286/104462229-f81e2280-55b8-11eb-8d8b-bc85e63fd205.gif)

- the url from the blocklist block page is displayed also as a blue link and when I hover over the status bar shows it:

![blocklist url](https://user-images.githubusercontent.com/33448286/104462609-7975b500-55b9-11eb-8c85-ee4b69bf7a24.png)

  Let me know if that's the expected result, so I can mark this verified. 

I verified on AMO dev and AMO stage with FF84(win10).

**Comment by willdurand** [comment]
> Let me know if that's the expected result, so I can mark this verified.

it's the expected result.
