### ISSUE TITLE
Revised Tags, Placement on Detail Page

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3588]
Tags on the detail page looked too much like buttons, so I removed the stroke around them and moved them to the top-right corner of the main information block:
<img width="1020" alt="screen shot 2017-10-20 at 12 21 32 pm" src="https://user-images.githubusercontent.com/6797635/31838929-bb9aafae-b593-11e7-94d6-b31a5f02524e.png">

**Comment by tofumatt** [comment]
Where should these appear on mobile? Right now they're just at the bottom of the card; moving them to the top-right won't work here because there isn't much horizontal space.

<img width="316" alt="screenshot 2017-10-26 16 10 31" src="https://user-images.githubusercontent.com/90871/32060945-33c3c910-ba68-11e7-8584-23838d12512b.png">

**Comment by tofumatt** [comment]
Actually after changing the metadata (stars, etc.) around we can likely fit these to the right of the icons even on mobile. I'll give it a go.

**Comment by ValentinaPC** [comment]
@tofumatt : I guess the screenshot from this issue was overtaken by the ones from https://github.com/mozilla/addons-frontend/pull/3659 ?
Also, the average rating section was not yet implemented?

**Comment by tofumatt** [comment]
Average ratings are still not implemented, correct.

- Matt (Sent from mobile)

**Comment by ValentinaPC** [comment]
And the first question? :)

**Comment by tofumatt** [comment]
Oh, yes, sorry. Yeah we decided to do them below the title as it's nicer 😄

**Comment by ValentinaPC** [comment]
Yes and no... 👯 
Please see screenshot from device, while in details page for an add-on:
![2017-11-01_1146](https://user-images.githubusercontent.com/15685960/32269197-6a0cc576-befa-11e7-92e6-5be24ae09046.png)

**Comment by tofumatt** [comment]
That new screenshot is correct; on mobile there isn't enough space to have them run across.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
![untitled](https://user-images.githubusercontent.com/15685960/32269814-2e67be34-befc-11e7-9e30-944bb3764de9.png)

**Comment by willdurand** [comment]
I really like the badge alignment 🎖
