### ISSUE TITLE
Shelf implementation does not match mocks

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3593]
- Shelf and content blocks need padding
- Content blocks are missing their hover state
 - Background of block fades from #fffff to #F9F9FA
 - Add-on name changes to link blue
 - ~~Star rating replaces user count~~ (this will be done separately)
- Link to list view should only say "See more"

Current:
<img width="1035" alt="screen shot 2017-10-20 at 2 48 56 pm" src="https://user-images.githubusercontent.com/6797635/31843211-90247324-b5a6-11e7-8cb6-caf3bc16f9b4.png">

Mocks:
<img width="1119" alt="screen shot 2017-10-20 at 3 01 08 pm" src="https://user-images.githubusercontent.com/6797635/31843398-8993308a-b5a7-11e7-8b39-e7761d4bf0d1.png">

**Comment by willdurand** [comment]
A small update on the different improvements here:

> ~~Shelf and content blocks need padding~~
> Content blocks are missing their hover state
> Background of block fades from #fffff to #F9F9FA
> Add-on name changes to link blue
> Star rating replaces user count
> ~~Link to list view should only say "See more"~~

**Comment by kumar303** [comment]
FYI, https://github.com/mozilla/addons-frontend/pull/3614 is in the 2017.10.26 tag

**Comment by willdurand** [comment]
> Star rating replaces user count (this will be done separately)

Follow-up in #3622.

**Comment by ValentinaPC** [comment]
Verified this as fixed on AMO-dev FF56(Win 7).
Postfix screenshot:
![s](https://user-images.githubusercontent.com/15685960/31988787-e6fd41a0-b978-11e7-9377-23636806682d.png)

@willdurand : What does your comment means: you don't want to implement the first and the last option?

> A small update on the different improvements here:
> 
>     Shelf and content blocks need padding
>     Content blocks are missing their hover state
>     Background of block fades from #fffff to #F9F9FA
>     Add-on name changes to link blue
>     Star rating replaces user count
>     Link to list view should only say "See more"

Thanks!

**Comment by willdurand** [comment]
@ValentinaPC it means this was already done when I started to look at this issue. Sorry for the confusion. Except the star rating, everything else has been implemented.

**Comment by ValentinaPC** [comment]
this can be marked as verified fixed, based on above comments.
Thanks, @willdurand !
