### ISSUE TITLE
Hero area does not match mocks

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3595]
This kind of came together only a few weeks ago, but the hero area of the top-level Extensions and Themes pages do not match the mocks. We need to remove those illustrations. The copy might need to change too, @devaneymoz ?

Current:
<img width="1035" alt="screen shot 2017-10-20 at 3 14 37 pm" src="https://user-images.githubusercontent.com/6797635/31843712-72db981c-b5a9-11e7-8c74-db640b783c3a.png">
<img width="1033" alt="screen shot 2017-10-20 at 3 14 49 pm" src="https://user-images.githubusercontent.com/6797635/31843716-769a5cd6-b5a9-11e7-9095-8e01e1b40f2d.png">

Mocks:
<img width="1047" alt="screen shot 2017-10-20 at 3 15 21 pm" src="https://user-images.githubusercontent.com/6797635/31843765-9c1806f2-b5a9-11e7-9a96-7d3fdaefb9e5.png">
<img width="1040" alt="screen shot 2017-10-20 at 3 15 35 pm" src="https://user-images.githubusercontent.com/6797635/31843767-9df18700-b5a9-11e7-8a21-e234d02e7fe3.png">

**Comment by devaneymoz** [comment]
Final copy is on the examples with the octopus and unicorn. So please use that messaging regardless of what happens with design.

**Comment by tofumatt** [comment]
Why no illustrations?! They were so pretty and fun and whimsical and added a lot of personality to the site–when so much of the content of the site is what devs make it was nice to put a fun little touch in one or two spots 😢

Was this because of negative responses in user testing? I would really dig these staying around, I think they're so great...

**Comment by pwalm** [comment]
Illos had to go, they were done at a time when we thought we'd use them in more situations, but they've been scaled back.

**Comment by muffinresearch** [comment]
@pwalm are we OK to fix this post-release?

**Comment by pwalm** [comment]
No, this is something that has to come out. They are un-approved, older versions of Firefox brand illustrations.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Icons are gone.
Postfix screenshots:
![ext](https://user-images.githubusercontent.com/15685960/32165019-fefbe794-bd69-11e7-9fce-9eff183c9265.png)
![th](https://user-images.githubusercontent.com/15685960/32165021-0157d732-bd6a-11e7-98dd-424307268c78.png)
