### ISSUE TITLE
A review can be flagged for multiple reasons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3598]
Steps to reproduce:
1. Load All reviews page for an add-on with reviews i.e. https://addons-dev.allizom.org/en-US/firefox/addon/imgur-uploader/reviews/
2. Click on all 3 flagging options

Expected results:
Review can be flagged only once.

Actual results:
All 3 flagging options can be picked for the same review.

notes/Issues:
- _flag link is also not changing in "marked as flagged" or something like this giving the user the chance to flag that review as many times as he wants_;
- in Moderated reviews page only the first selected flagging option is stored 

Verified on AMo-dev FF56(Win 7).
Video for this issue:
![flag0v](https://user-images.githubusercontent.com/15685960/31880413-1ec193ca-b7e9-11e7-88bd-7c374d9c4c10.gif)

**Comment by kumar303** [comment]
This is working as intended. However, I too am not sure if the intention was correct. I think we need some UX and product related guidance on what to do here.

**Comment by kumar303** [comment]
> in Moderated reviews page only the first selected flagging option is stored

What do you mean by *moderated* reviews page? What do you mean be *stored*?

**Comment by ValentinaPC** [comment]
@kumar303 : 
- the initial title was more general because not only was possible to flag multiple times a review, but the fact that if I select 2 options, only the one action is recorded in moderated review queue (https://reviewers.addons-dev.allizom.org/en-US/editors/queue/reviews)
Example of selecting all 3 flagging options:
![2017-10-24_0913](https://user-images.githubusercontent.com/15685960/31927235-d74b1170-b89b-11e7-8ffb-8af29a159dcf.png)

**Comment by kumar303** [comment]
Ah! I didn't know about that page. Thanks. If only one flag reason is shown in the reviewer tools then the UI should match that.

**Comment by ValentinaPC** [comment]
We should check the intended behavior from Reviewer Tools with @wagnerand :), just to be sure.
Thanks guys!

**Comment by kumar303** [comment]
> in Moderated reviews page only the first selected flagging option is stored

Correct me if I'm wrong but I observed that the last selected flagging reason is shown in the reviewer tools. Because of that I allowed the user to switch their reason for flagging the review. They can still only choose one. This would allow someone to change their mind or make a correction if they accidentally flagged for the wrong reason.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
1. Selected option for flagging is recorded as expected in Reviewer Tools also.
2. "Flag" link turns into "Flagged" after flagging the review.
3. User can change its mind and selected other option.
![2017-10-30_1214](https://user-images.githubusercontent.com/15685960/32165653-2e863f08-bd6c-11e7-8a08-70f88ee47796.png)
4. Hovering over the "Flagged" link will display the "Flag this review" text - which I guess make sense if the reason for flagging can be changed.
![2017-10-30_1216](https://user-images.githubusercontent.com/15685960/32165799-a5a5b3c0-bd6c-11e7-8356-cfb2476bc2ac.png)
5. Refreshing the page will change the link from "flagged" to "flag" and the user is able to flag again, for the same reason, the review.

@kumar303 : Is 5 correct?
Thanks!

**Comment by kumar303** [comment]
> Refreshing the page will change the link from "flagged" to "flag" and the user is able to flag again, for the same reason, the review.

Yes. We don't have an API yet to retrieve information about flagged reviews. We could add it in the future.

**Comment by ValentinaPC** [comment]
Based on above comments we can mark this issue verified - fixed.
