### ISSUE TITLE
Change the report abuse button following the new mocks

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3599]
Please change the report abuse button as described in https://github.com/mozilla/addons-frontend/issues/3553#issuecomment-338252865

Also, not sure if or how should we change this on Android device.

**Comment by tofumatt** [comment]
Arguably ties in with #3398.

**Comment by vcarciu** [comment]
Verified as fixed : 
![newmocksabuse](https://user-images.githubusercontent.com/1583842/32285371-b76770fe-bf32-11e7-9480-9bbceb684773.png)
