### ISSUE TITLE
Link based install button doesn't appear to send explicit tracking

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3600]
The switch-based button had explicit tracking based on the various states of interaction. Having removed that to use a direct link button, we lost that tracking.

STR
- Go to an add-on detail page
- Open the network panel in Devtools
- Click the install button

Expected: a request is made to `https://www.google-analytics.com/r/collect`
Actual: no request is made

QA Notes:
- Please also make sure the Discopane install button does not have regressions. It should already be sending tracking events.

**Comment by muffinresearch** [comment]
Since the type of installation has changed I think an appropriate fix for this would be to know we're on the details page and add `src=dp-btn-primary` which should mean we're still sending a stat for the same install as before. 

We can consider adding back more complete instrumentation at the same time as bringing back some of the features of mozAddonManager which is work that's still to be defined and specced out.

**Comment by kumar303** [comment]
Sorry, I was a bit confused and thought this was comprised of two issues. I moved the `src` part to https://github.com/mozilla/addons-frontend/issues/3618

Maybe I'll just leave this one open so I can verify that we're still sending tracking events.

**Comment by vcarciu** [comment]
@kumar303 : I cand see any request https://www.google-analytics.com/r/collect . Am I doing something wrong? : 
![analytics](https://user-images.githubusercontent.com/1583842/32106483-778f1a4c-bb34-11e7-9bfe-2dea71983a57.gif)

**Comment by kumar303** [comment]
That's weird. What Firefox version are you using? I can see the request when installing that same add-on using 58.0a1 (2017-10-25) on Mac:
<img width="1631" alt="screenshot 2017-10-27 20 40 14" src="https://user-images.githubusercontent.com/55398/32130132-e9a8df28-bb57-11e7-9d97-b726c93de25d.png">

**Comment by kumar303** [comment]
@vcarciu make sure you have *do not track* disabled.

**Comment by vcarciu** [comment]
@kumar303 : Not sure what happened, do not track was not enabled, but anyway Today it is working fine : 
![ga](https://user-images.githubusercontent.com/1583842/32166668-410c5f1a-bd6f-11e7-80d9-ab39706c0e1b.png)

I observed that if you are trying to install a webext from about:addons search results, no google analytics request is made. Please let me know if this is ok (I used latest Nightly on AMO-dev): 
![noga](https://user-images.githubusercontent.com/1583842/32168039-b09832c4-bd73-11e7-9621-876c29813062.gif)

**Comment by muffinresearch** [comment]
> I observed that if you are trying to install a webext from about:addons search results, no google analytics request is made. Please let me know if this is ok (I used latest Nightly on AMO-dev):

@vcarciu It's fine. This patch only relates to the addons-frontend and as a result would only impact amo and the disco pane.

**Comment by vcarciu** [comment]
@muffinresearch : thanks. Marking as verified since Disco Pane is sending the GA request
