### ISSUE TITLE
statistics link should be there for all user for Addon.public_stats == true

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#3603]
STR
* Create an add-on and mark its stats as public
* View the add-on detail page
* Make sure you are logged out
* Refresh the page

You should still see a link to the stats but you do not.

(On the backend the API data exposes this as `public_stats` = `true`)

**Comment by kumar303** [comment]
> The stats link should also be shown for all add-ons where the user has `Stats:View` also, though this is arguably a lower priority fix.

Moved to https://github.com/mozilla/addons-frontend/issues/3604

**Comment by ValentinaPC** [comment]
@kumar303 : I have a question - for admins, in old pages, we displayed the stats no matter if they where set public or not in Dev Hub, shouldn't be the case of the new frontend?
Thanks!

**Comment by kumar303** [comment]
> for admins, in old pages, we displayed the stats no matter if they where set public or not

Yes, the new site should do that too but it was a little harder to implement so we are doing it in a separate issue: https://github.com/mozilla/addons-frontend/issues/3604

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7)
Postfix screenshot:
![2017-11-02_1353](https://user-images.githubusercontent.com/15685960/32324793-3badb088-bfd5-11e7-8bae-6a96f3b054b6.png)
