### ISSUE TITLE
Admins should be able to always see a stats link

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3604]
### Describe the problem and steps to reproduce it:

* Log in as an admin or any user with the `Stats:View` permission
* Go to an add-on detail page for an add-on that you are not an owner of

### What happened?

There is no link to add-on statistics

### What did you expect to happen?

You should see a link to add-on statistics

### Anything else we should know?

This is similar to https://github.com/mozilla/addons-frontend/issues/3603

**Comment by kumar303** [comment]
As a prerequisite, we need to store user permissions in state https://github.com/mozilla/addons-frontend/issues/3702

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Admins can always see stats.
Postfix screenshots:
![firebug1](https://user-images.githubusercontent.com/15685960/32366851-9f1f3f52-c088-11e7-8560-5fc42ff9fb5a.png)
![firebug_logged_out](https://user-images.githubusercontent.com/15685960/32366854-a1b8b838-c088-11e7-8f10-f15ba26d85c7.png)
