### ISSUE TITLE
Hero banner does not display all possible sections

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3608]
### Describe the problem and steps to reproduce it:

1. Refresh the homepage many times

### What happened?

You should notice that you will never see "Ad blocks" in the Hero Banner (the three cards displayed at the top of the page).

### What did you expect to happen?

At some point, "Ad blocks" should be displayed.

### Anything else we should know?

The sorting algorithm is not applied on the set of all sections but on a subset only.

**Comment by ValentinaPC** [comment]
@willdurand Are you referring at "Block ads"?

**Comment by willdurand** [comment]
Ooops. No I actually meant "uBlock Origin".

There are 4 possibilities: Block ads, Featured extensions, uBlock Origin and YouTube High Definition.

**Comment by ValentinaPC** [comment]
All 4 heroes are displayed as expected.
Verified on AMO-dev FF56(Win 7, Android 7.2.1).
Postfix video:
![4heroes](https://user-images.githubusercontent.com/15685960/31931925-6b8925a0-b8ad-11e7-8e6f-e4766b79c68d.gif)
