### ISSUE TITLE
Loading add-on page using numerical id instead of slug leads to blank page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3610]
STR:
Go to https://addons-dev.allizom.org/en-US/firefox/addon/9609/

It should load the same data as https://addons-dev.allizom.org/en-US/firefox/addon/ghostery/ (or redirect to it).

**Comment by tofumatt** [comment]
Just out of curiosity, why is this an MVP? Shouldn't be too hard a fix but I wonder: do we allow slugs/add-on names that are just numbers? Because if so fixing this in a way that never loads the wrong add-on or shows a 404 we shouldn't show is to fallback to a second request on 404.

**Comment by muffinresearch** [comment]
It currently looks like this:

<img width="1413" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31937712-45dae302-b8ad-11e7-826f-3f7c54670a2b.png">

**Comment by muffinresearch** [comment]
This is distinct to what is shown for https://addons-dev.allizom.org/en-US/firefox/addon/totallymade-up/ although this is also a 200 OK when it should be a 404.

<img width="1386" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31938032-347fdc06-b8ae-11e7-9de1-20fe59e25884.png">

**Comment by willdurand** [comment]
We actually retrieve all the data we need, it is a pure UI issue.

**Comment by willdurand** [comment]
Quick fix would be: https://gist.github.com/willdurand/7c0f2ab14104613b38f3c655f8336027.

**Comment by eviljeff** [comment]
> do we allow slugs/add-on names that are just numbers?

We don't allow purely numeric slugs.

**Comment by jvillalobos** [comment]
> Just out of curiosity, why is this an MVP?

It could lead to external links being broken. I don't know how common it is in reality, but the URL with the numerical ID is more stable because slugs can change.

**Comment by muffinresearch** [comment]
@willdurand I feel that the long-term correct approach for this would be to 301 from the server response in a case like this. Otherwise if we show the same data on multiple URLS we could have issues in terms of duplicate data which might impact on our search results.

This would mean the node server would talk to the API and then 301 the client, only to re-fetch mostly the same data again on the new request.

If we move forward with fixing the data display to avoid a blank 200 OK, would it be possible to update the URL client-side?

Then it would make sense to follow-up with the server-side 301 approach and make sure those 301s are cacheable.

@tofumat mentioned that guids may also be an issue since the API also supports them:

`/api/v3/addons/addon/(int:id|string:slug|string:guid)/`

See http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#detail

**Comment by willdurand** [comment]
> @willdurand I feel that the long-term correct approach for this would be to 301 from the server response in a case like this. Otherwise if we show the same data on multiple URLS we could have issues in terms of duplicate data which might impact on our search results.

This can be solved with a canonical meta.

**Comment by muffinresearch** [comment]
> 301 isn't completely accurate though - slug might be changed so it's not a permanent redirect. 302? (or 303)

Yeah that's a fair point.

**Comment by muffinresearch** [comment]
> This can be solved with a canonical meta.

That's a good idea in the short-term. 👍

**Comment by muffinresearch** [comment]
> 301 isn't completely accurate though - slug might be changed so it's not a permanent redirect. 302? (or 303)

What do we do re: old slug redirs?

**Comment by eviljeff** [comment]
actually, in legacy frontend we 301 so it would be consistent at least

**Comment by kumar303** [comment]
We haven't done a server redirect based on loaded data before (IIRC) so it will take some thought. Maybe something like this:

```diff
diff --git a/src/amo/components/Addon/index.js b/src/amo/components/Addon/index.js
index 96c10b06..932712ca 100644
--- a/src/amo/components/Addon/index.js
+++ b/src/amo/components/Addon/index.js
@@ -89,6 +89,11 @@ export class AddonBase extends React.Component {
     // of an error.
     if (!errorHandler.hasError()) {
       if (addon) {
+        if (!isNaN(params.slug)) {
+          // The slug was a numeric ID.
+          dispatch(serverRedirect({ to: `/addon/${addon.slug}`, status: 301 }));
+          return;
+        }
         dispatch(setViewContext(addon.type));
         this.dispatchFetchOtherAddonsByAuthors({ addon });
       } else {
diff --git a/src/core/server/base.js b/src/core/server/base.js
index d813fc7e..a9c2ef72 100644
--- a/src/core/server/base.js
+++ b/src/core/server/base.js
@@ -317,7 +317,16 @@ function baseServer(routes, createStore, {
           // Once all sagas have completed, we load the page.
           return runningSagas.done.then(() => {
             log.info('Second component render after sagas have finished');
-            return hydrateOnClient({ props, pageProps, res });
+            const finalPage = hydrateOnClient({ props, pageProps, res });
+
+            // We have to make sure the timing of this is correct.
+            const redirectTo = store.getState().redirectTo;
+            if (redirectTo.url) {
+              res.redirect(redirectTo.status, redirectTo.url);
+              return;
+            }
+
+            return finalPage;
           });
         })
         .catch((loadError) => {

```

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Examples:
- https://addons-dev.allizom.org/en-US/firefox/addon/16/
- https://addons-dev.allizom.org/en-US/firefox/addon/1778/
- https://addons-dev.allizom.org/en-US/firefox/addon/413630/

All links redirect as expected.
Postfix video:
![id](https://user-images.githubusercontent.com/15685960/32176738-311d3e2c-bd91-11e7-9984-76c6c7808fa3.gif)

**Comment by jvillalobos** [comment]
Reopening this bug because it seems to have regressed.

**Comment by ValentinaPC** [comment]
Verified this again using FF57(Win 7).
Examples:
- https://addons-dev.allizom.org/en-US/firefox/addon/357
- https://addons-dev.allizom.org/en-US/firefox/addon/494620
- https://addons-dev.allizom.org/en-US/firefox/addon/355193
- https://addons-dev.allizom.org/es/firefox/addon/10423

Numerical ID used instead of SLUGs, in URLs, load correct pages.
