### ISSUE TITLE
"More extensions by" block doesn't show up when logged in

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3611]
I'm seeing this on -dev when looking at the listing for [Awesome Screenshot](https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/). When logged out, I see a "More extensions by Diigo Inc." block below the rating block. When logged in, the block doesn't appear.

**Comment by muffinresearch** [comment]
I don't seem to be able to repro this.

**Comment by jvillalobos** [comment]
I can see it on a release profile if I'm logged out. It's the one I'm using as a sample for the announcement blog post.

![asp-fullpage](https://user-images.githubusercontent.com/62568/31954078-d1934260-b8a1-11e7-901b-6d52619b056b.png)

**Comment by willdurand** [comment]
mmh I dont have any other add-ons on Firefox Nightly and you should not have any too. The "Diigo Web Collector" is not compatible and we only list compatible add-ons.

**Comment by kumar303** [comment]
> I dont have any other add-ons on Firefox Nightly

Their other add-on is not compatible with Nightly so you can only view the *other add-ons* block using Firefox Release.

@jvillalobos does it happen to you with other user accounts? Were you logged in as an admin? I can see the *more extensions by Diigo* block when logged in and logged out.

**Comment by jvillalobos** [comment]
@willdurand nailed it. On release it appears because it's compatible and on Nightly it won't.
