### ISSUE TITLE
Hero banners have no background images

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3613]
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Observe hero banners

Expected results:
There are no display or layout issues.

Actual results:
The banners have no background images.

Notes/issues:
Verified on AMO-dev FF56(Win 7).
Screenshot for this issue:
![2017-10-24_0936](https://user-images.githubusercontent.com/15685960/31928151-b51fb566-b89f-11e7-95d6-e8df85b628c4.png)

**Comment by ValentinaPC** [comment]
@willdurand - I found the comment when you guys decided to remove the background pics, if this is intended, please reconsider...they were way better before.

**Comment by muffinresearch** [comment]
@ValentinaPC this is currently being discussed with UX we'll update this issue when we know what the direction is.

**Comment by kumar303** [comment]
> they were way better before

I agree but there might be some performance issues with them.

**Comment by pwalm** [comment]
No pics, perhaps some patterns. I'm thinking some sort of abstract imagery works better than both of those options. I'll whip something up when I get some spare time this week (team work week in Berlin).

**Comment by muffinresearch** [comment]
@pwalm is there any way to have this today if at all possible? What we put out this week (we're already past the tag) should ideally be what we're releasing tomorrow (Thursday)? 

If we're adding a pattern via CSS or a repeating background image then we can probably add that as a low-risk cherry-pick.

**Comment by pwalm** [comment]
Revised hero area *MUST*:
- Change typography to match spec below
- Add background patterns from [Hero Patterns](http://www.heropatterns.com/): 4 point star, wiggle, bubbles, polka dots, floor tile, tic tac toe, plus, falling triangles. Use the main category colour as the background, and hover as the foreground (values can be found in the Sketch file)
<img width="1365" alt="screen shot 2017-10-25 at 3 58 10 pm" src="https://user-images.githubusercontent.com/6797635/32002697-622efe26-b99d-11e7-8f0d-96f3d026646f.png">

Revised hero area *NICE TO HAVE*:
- Show extension icon or appropriate svg icon to match collection on blocks.

Spec:
<img width="1354" alt="screen shot 2017-10-25 at 3 52 58 pm" src="https://user-images.githubusercontent.com/6797635/32002769-8d9f101e-b99d-11e7-918b-c99ffb050da7.png">

**Comment by willdurand** [comment]
So that would look like this, ok?

<img width="1392" alt="screen shot 2017-10-25 at 17 28 57" src="https://user-images.githubusercontent.com/217628/32007603-43842502-b9aa-11e7-8994-53d7d6b9b063.png">

**Comment by pwalm** [comment]
Looking better!

**Comment by willdurand** [comment]
It does not use the full palette (7 colors out of 12) and 6 different hero patterns. No icons have been added so far, this could be a follow-up patch, post-release.

**Comment by vcarciu** [comment]
Verified as fixed : 
![herobackground](https://user-images.githubusercontent.com/1583842/32058195-10c6f6f8-ba72-11e7-93b3-1aab8996d434.gif)

@willdurand  : Will you open another issue for icons?

**Comment by muffinresearch** [comment]
@vcarciu this was cherry-picked and is now on stage so is going out today.

**Comment by vcarciu** [comment]
@muffinresearch : yes, I can see it on Stage, thanks!
