### ISSUE TITLE
Gray glitch while tapping in the search field

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3615]
Steps to reproduce:
1. Load AMO-dev Extensions homepage https://addons-dev.allizom.org/en-US/firefox/extensions/ using your device
2. Tap on the search field

Expected results:
There are no display or layout issues.

Actual results:
Entire search field turns gray for a second.

Notes/Issues:
- no reproducing on desktop 
Reproducing on all AMO-servers using both FF56 and FF58 under Android 7.2.1.
Video for this issue:
![videotogif_2017 10 24_14 42 36](https://user-images.githubusercontent.com/15685960/31941325-162b16e6-b8ca-11e7-8911-049c39423095.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![telefonsearch](https://user-images.githubusercontent.com/1583842/32060434-6a997d86-ba77-11e7-910b-930638115cd6.gif)
