### ISSUE TITLE
Add new collections to -dev and stage

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3617]
As pointed out [here](https://github.com/mozilla/addons-frontend/issues/3558#issuecomment-338893444) we're missing the collections on -dev and stage:

## Prod:

* [smarter shopping](https://addons.mozilla.org/en-US/firefox/collections/mozilla/smarter-shopping/)
* [productivity](https://addons.mozilla.org/en-US/firefox/collections/mozilla/be-more-productive/)

## Dev:

* [x] [smarter shopping](https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/smarter-shopping/)
* [x] [productivity](https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/be-more-productive/)

## Stage:

* [x] [smarter shopping](https://addons.allizom.org/en-US/firefox/collections/mozilla/smarter-shopping/)
* [x] [productivity](https://addons.allizom.org/en-US/firefox/collections/mozilla/be-more-productive/)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev and -stage using FF56(Win 7, Android 7.2.1).
Postfix video:
![coll](https://user-images.githubusercontent.com/15685960/31990071-b7621d9a-b97c-11e7-8e6a-887b098d288c.gif)
