### ISSUE TITLE
Link based install button doesn't set a src

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3618]
### Describe the problem and steps to reproduce it:

- Go to an add-on detail page
- Hover over the install button

### What happened?

You see a link to the XPI but without a `src` parameter in the URL

### What did you expect to happen?

The URL should include a `src` for statistics. See https://addons-server.readthedocs.io/en/latest/topics/api/download_sources.html#id1

### Anything else we should know?

Originally filed as https://github.com/mozilla/addons-frontend/issues/3600

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
The `src` param is listed in the URL while hovering over the Add to Firefox install button.
Postfix screenshot:
![addon](https://user-images.githubusercontent.com/15685960/31990662-6af1e90c-b97e-11e7-927a-0c1b95e3634b.png)
