### ISSUE TITLE
Minor issues with hover shelf style

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3620]
The text colour change seem to occur independently of the background hover. 

It's also possible to get the text colour change to "stick on". Leaving the text blue when the mouse isn't over it.  See an example below - the mouse isn't hovering over the content with the blue link.

Since shelves now have a special hover style it might be nice to make this also the focus style rather than the default outline which is a bit funky on the block level links.

<img width="521" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/31960204-ece6bfb8-b8ee-11e7-86d4-71458eb29d24.png">

Here's a screencast:

![hover-styles](https://user-images.githubusercontent.com/1514/31960350-6ce5a102-b8ef-11e7-9683-0b50f41b0ee5.gif)

**Comment by willdurand** [comment]
This is likely due to the need for alignment of the icons with the shelf headers:

![](https://image.ibb.co/ndubQm/Screen_Shot_2017_10_24_at_21_10_51.png)

I probably used a wrong margin.

**Comment by muffinresearch** [comment]
Not sure I follow the comment re: icon alignment.

To me it looks like there's a difference in the hit target of the `a` versus the `li`. 

Just a thought but it might be simpler in a future revision to make the link match the size of the li and pad that instead of the li. That would also help to be able to tie together the focus and hover style since the link is the element that is focusable.

**Comment by vcarciu** [comment]
Verified as fixed : 
![minorissue](https://user-images.githubusercontent.com/1583842/32100148-a8df0fbc-bb1b-11e7-9257-336533c3cdc3.gif)
