### ISSUE TITLE
Remove subject shelf headlines

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3621]
According to the [content doc](https://docs.google.com/document/d/1PeBCNbx0V-5NReKdyv1c14Za6sVjTJ60-ondGaJDBBg/edit), the subject shelves should not have headers.

Specifically, these should be removed: *Extensions change the way Firefox works* and *Themes change the way Firefox looks*. The headlines make the messages redundant.

See also: https://github.com/mozilla/addons-frontend/issues/3558#issuecomment-339038939

**Comment by willdurand** [comment]
Something like this?

<img width="1392" alt="screen shot 2017-10-27 at 14 51 07" src="https://user-images.githubusercontent.com/217628/32104816-4c94e1a4-bb26-11e7-9aeb-7c821f2a1cd8.png">

**Comment by pwalm** [comment]
Needs to be centered to the shelf. Looks like it needs to move down 5-10px?

**Comment by pwalm** [comment]
Also: let's change the copy to `Title17`
<img width="955" alt="screen shot 2017-10-27 at 3 01 48 pm" src="https://user-images.githubusercontent.com/6797635/32105166-ce1c3b90-bb27-11e7-8773-d16ec6b1d2dd.png">

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF56 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/32169238-543be994-bd78-11e7-8353-e2ef17467887.png)




![image](https://user-images.githubusercontent.com/31961530/32169259-779301d4-bd78-11e7-9eb5-7a1b56a809c6.png)




![image](https://user-images.githubusercontent.com/31961530/32169299-a1df1126-bd78-11e7-8eed-f1fec1565266.png)
