### ISSUE TITLE
Add star rating instead of user count on add-on hover (shelves)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3622]
Refs #3593

![](https://user-images.githubusercontent.com/6797635/31843398-8993308a-b5a7-11e7-8b39-e7761d4bf0d1.png)

**Comment by muffinresearch** [comment]
@pwalm I'm not sure I understand the intention with the proposed UX here? It seems somewhat odd to switch the data from users to ratings on hover/focus. 

Is there some insight that doing this is more likely to lead to the click?

**Comment by pwalm** [comment]
We hid the star rating behind a hover to reduce visual clutter on the page but having a combo of rating/number of users is quite important in most users decision to install an extension (we saw a lot of this in the Portland user study). I feel confident that having this information appear on hover will convert users.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix video:
![hover](https://user-images.githubusercontent.com/15685960/32175380-76633a6c-bd8d-11e7-9844-de1a244738b5.gif)

**Comment by pwalm** [comment]
😍😍 😍 😍 😍 😍 😍 

Looks so good! Well done, all 😎
