### ISSUE TITLE
Ratings lower than 4 stars should require a written review

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-frontend#3628]
The legacy frontend does not allow ratings to be submitted without a review body, while the new frontend submits ratings instantly and written reviews are optional.

Review text being optional seems nice and should result in more reviews being submitted, but it is also an easy target for abusers and makes reviewing them difficult to impossible for moderators.

I think it would be better to keep review text optional for positive ratings, but anything lower than 4 stars should require a written review.

Please consider making this change before the new frontend is deployed on the desktop site, empty negative reviews are not helpful and will cause frustration for users, add-on developers and moderators.

**Comment by jvillalobos** [comment]
Supporting empty reviews in ratings is intentional, and like you said it's meant to lower the bar for people who want to rate add-ons, both positively and negatively. Negative reviews are often deleted incorrectly by moderators because the policies are subjective and it's easy to empathize with the developers flagging them.

If it turns out that ratings become hard to manage after this change, we will consider changing them back, but for now we'll go with it.

**Comment by dessant** [comment]
I see your point, but how does a moderator review a flagged one star review without any text being available?

**Comment by dessant** [comment]
Consider you're making an add-on which you think works as intended, but you sometimes get negative reviews, without any actionable info being available.

These reviews have an effect on user perception and also impact search rankings both on AMO and other search engines. As a developer it is in your best interest to find out the reason for someone leaving a negative review, so you can fix the underlying issue, and to flag negative reviews which are made for misplaced reasons.

For example add-ons which have not yet been ported to WebExtensions have a bunch of one star reviews stating the lack of a port being available as the reason for the negative review, despite the extension functioning correctly with the current stable version of Firefox.

They will also place negative reviews for any other reason, without thinking too much about the implications or reading the review guidelines, including for issues caused by Firefox bugs, and for issues caused by changes in websites with which the extension interacts with.

And sometimes they just don't understand how the add-on works, or use reviews as a leverage to request new features.

We must have ways to manage these aspects, but that is not possible without written reasons being available for negative reviews.

**Comment by jvillalobos** [comment]
I get your point that actionable feedback is valuable for developers, but we shouldn't force users to provide reasons for rating down an add-on. It raises the bar for rating unnecessarily. If a user wants to provide detailed feedback, they can still do that. Same goes for positive feedback.

**Comment by ghostwords** [comment]
As I posted in https://github.com/mozilla/addons-server/issues/6817#issuecomment-345067594, developers have no way to understand, respond to, or, yes, flag no-text 1/2/3 star reviews.

>Negative reviews are often deleted incorrectly by moderators because the policies are subjective and it's easy to empathize with the developers flagging them.

@jvillalobos I agree this is also an issue, but I don't see how allowing text-free reviews solves it.

**Comment by jvillalobos** [comment]
It addresses part of the problem, which is that users are forced to justify their negative ratings, and it's easy to interpret those reasons as misplaced bug reports. Another part of the problem we intend to fix in the future is to better expose support information alongside the review options, so users know how to ask for help before they write a review.

**Comment by ghostwords** [comment]
Making it easier for (frustrated) users to find proper support channels would be a good change.

I want to point out that flagging reviews as support requests should remain a legitimate workflow. Users run into a bug, they don't know where to get help or maybe they can't be bothered, they are just upset. It is very helpful for developers to see what's bugging users, but it isn't fair to be stuck with "support reviews" when you (the developer) have made your best effort to reach out and explain what is being done about the issue (or why it isn't an issue at all).

I understand this gets tricky when developers abuse this workflow by leaning on it as a tactic for getting rid of low ratings. The thing that bugs me about allowing ratings without explanations is that I get no feedback as to what prompted the rating. Just knowing somebody out there is unhappy isn't very helpful.

**Comment by tshirtman** [comment]
It's also useful for other users to know why another user let a bad review, maybe their reason is not relevant to me, or maybe even something that would make me give a good review. A bad review without comment is really a poor signal to interpret, not sure there is any use to it to anyone.

**Comment by kumar303** [comment]
> A bad review without comment is really a poor signal to interpret, not sure there is any use to it to anyone.

The alternative could be no signal at all so I think it's still helpful. In other words, requiring a text explanation might cause some users to give up submitting a rating.

**Comment by tshirtman** [comment]
Stumbled upon this which reminded me about this bug report, hope it gets my point accross.

![](https://i.imgur.com/V23I0Tv.jpg)
![](https://i.imgur.com/70U3bQL.jpg)

"source" https://imgur.com/gallery/1K42r
