### ISSUE TITLE
Reimplement styles for writing/editing an add-on review

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3636]
### Describe the problem and steps to reproduce it:

On a desktop browser...

1.
* Go to an add-on detail page
* Select a star to write a review

2. 
* After writing a review, go to the all reviews page
* Click *edit my review*

### What happened?

You see a text box that is better suited for mobile:

<img width="805" alt="screenshot 2017-10-25 15 27 00" src="https://user-images.githubusercontent.com/55398/32021790-0c624b5e-b99a-11e7-8466-208cf9d09926.png">

### What did you expect to happen?

This should be redesigned for desktop.

**Comment by grahamperrin** [comment]
Thanks. A point from #3131: 

> … the star rating, which preceded the invitation to write, is unaffected by the escape.

– now, I'm not sure whether that's out of scope; 

- [Submitting an empty review should fail with an error · Issue #1837 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/1837)

– is starring _alone_ classed as emptiness?

**Comment by kumar303** [comment]
Yeah, this concern has come up before. I think we'll have a chance to make this more obvious when an inline textarea appears after you select a star. It should hopefully feel more like an *additional* action whereas the current flow feels like one continuous action.

**Comment by kumar303** [comment]
@pwalm I see that you started a mock for this (based on Collections) in the Sketch file but it's incomplete. Is this something you're still working on?

I'm not sure if my idea for the inline-editor will work or not. We could still do an overlay, perhaps one like https://github.com/mozilla/addons-frontend/issues/4198

**Comment by pwalm** [comment]
Yep, still working on it. Let's chat about it IRL in the front-end/ux meeting.

**Comment by pwalm** [comment]
Re-reading this issue: yes, "editing" should behave the same way as a developer response. Not sure what writing a review inline looks like yet though. Still some iterating happening on that.

**Comment by pwalm** [comment]
INLINE EDITING (right issue this time):
<img width="924" alt="screen shot 2018-02-09 at 12 12 41 pm" src="https://user-images.githubusercontent.com/6797635/36054599-316f3252-0dac-11e8-8176-e512af33df4f.png">
<img width="962" alt="screen shot 2018-02-09 at 12 12 50 pm" src="https://user-images.githubusercontent.com/6797635/36054601-33fefc64-0dac-11e8-9c50-643ca94df2d0.png">
<img width="951" alt="screen shot 2018-02-09 at 12 12 57 pm" src="https://user-images.githubusercontent.com/6797635/36054605-36e0d588-0dac-11e8-88c4-b734675a853f.png">

**Comment by muffinresearch** [comment]
@pwalm is there any additional UX required to action this?

**Comment by pwalm** [comment]
The only thing I need to spec out is motion/transition, but that's not a blocker. Who is working on this now that @kumar303 is on leave. I can work with them directly.

**Comment by muffinresearch** [comment]
@pwalm we're closing this on the basis that it is likely superceded by new UX, but please reopen if not.

**Comment by pwalm** [comment]
OK. Our current ux for this is pretty close to "final" but it couldn't hurt for a review/revisit before being made a new issue.
