### ISSUE TITLE
Add SSL certs to allow for local https developing

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#3638]
Currently a custom build of Firefox is needed to allow for local server testing/development. It seems that the server has no options for starting up with any kind of SSL certificates installed. 

I think if we could get SSL working we would not have to use a custom build of Firefox for local development, only a few select Firefox preferences.

**Comment by jrbenny35** [comment]
I am happy to work on this as the new discopane UI tests could benefit the most.

**Comment by tofumatt** [comment]
The custom certificate would need to spoof an allowed development domain, right? One of the things we need the custom build for is `mozAddonManager`, which is [enabled only on a few, selected, hardcoded domains](https://hg.mozilla.org/mozilla-central/file/tip/toolkit/mozapps/extensions/AddonManagerWebAPI.cpp#l52).

This would be more for testing than development I think, as otherwise we'd need to install a cert on our browser that allowed `addons-dev.allizom.org` or `addons.allizom.org` to be redirected to localhost, which I don't think we want to do in development 😄

**Comment by jrbenny35** [comment]
@tofumatt very good points.

Honestly....I have no idea how to go about this. I've worked with a few node apps but this one seems quite complex. Could someone point me in the right direction?

**Comment by tofumatt** [comment]
To get SSL certs working you'd need to get express (our node server) to use the SSL cert and run the server on HTTPS. But I don't think that will stop you from needing to build Firefox given the mozAddonManager restrictions.

**Comment by jrbenny35** [comment]
This is what testpilot does: https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md

This allows the testpilot extension to be installed even from a local server. They do use HTTPS for their local dev server.

**Comment by kumar303** [comment]
> The custom certificate would need to spoof an allowed development domain, right?

I think it would, yes.

Testpilot serves their dev site from `example.com` which is whitelisted. From their [quickstart](https://github.com/mozilla/testpilot/blob/master/docs/development/quickstart.md):

```
# Add hostname alias to /etc/hosts and start up dev webserver
echo '127.0.0.1 example.com' | sudo tee -a /etc/hosts
```

They also set the pref `extensions.install.requireBuiltInCerts` to `false` which I think allows them to use a self-signed cert? @jrbenny35 it would be incredible if you can get this working. The way we have to rely on a custom Firefox build has a lot of problems.

**Comment by tofumatt** [comment]
Ah, right on, that’d be cool and wouldn’t require us spoofing usual AMO domains. I forgot about example.com 👍🏻

- Matt (Sent from mobile)

**Comment by kumar303** [comment]
I tried to mimic what testpilot does but I couldn't get it working -- Firefox says *Secure connection failed* for `example.com:3000`. We have a proxy which makes things confusing. This might be heading in the right direction (but I'm not sure).

```diff
diff --git a/src/core/server/base.js b/src/core/server/base.js
index 19a97f69..2e1cdbc8 100644
--- a/src/core/server/base.js
+++ b/src/core/server/base.js
@@ -1,5 +1,6 @@
 import fs from 'fs';
 import path from 'path';
+import https from 'https';
 
 import 'babel-polyfill';
 import { oneLine } from 'common-tags';
@@ -399,7 +400,14 @@ export function runServer({
         const server = baseServer(
           routes, createStore, { appInstanceName: appName });
         if (listen === true) {
-          server.listen(port, host, (err) => {
+          const options = {
+            key: fs.readFileSync('/Users/kumar/dev/testpilot/frontend/certs/server/my-server.key.pem'),
+            cert: fs.readFileSync('/Users/kumar/dev/testpilot/frontend/certs/server/my-server.crt.pem'),
+            ca: fs.readFileSync('/Users/kumar/dev/testpilot/frontend/certs/server/my-private-root-ca.crt.pem'),
+            passphrase: '',
+          };
+          const httpsServer = https.createServer(options, server);
+          httpsServer.listen(port, host, (err) => {
             if (err) {
               return reject(err);
             }
```

**Comment by jrbenny35** [comment]
@kumar303 so even with the cert you got that error? I was getting that without the certs too.

**Comment by jrbenny35** [comment]
So I got this to work locally but only for the ```yarn start-func-test-server``` command. For the other commands like ```yarn amo``` it seems to break the UI. The site loads but there is no styling.

**Comment by jrbenny35** [comment]
In the browser console I get this error: ```Loading failed for the <script> with source “https://127.0.0.1:3001/amo-292a4d25e02b0dc0a4eb.js”.```

**Comment by jrbenny35** [comment]
Per irc: with yarn amo:no-proxy, I get html but no styling. With yarn amo I get 'connection has been interrupted'.

**Comment by kumar303** [comment]
Can you post a patch somewhere of what you have so far?

**Comment by jrbenny35** [comment]
I haven't done anything different from your patch. I just followed the config that testpilot has.

**Comment by jrbenny35** [comment]
@kumar303 @tofumatt Did you guys get a chance to try this? I would like to help solve the problem of using a custom firefox build as well as update the discopane tests.

**Comment by tofumatt** [comment]
Sorry, I don't know what I'm supposed to be trying. @kumar303's patch? I guess we'd need to generate certificates for the server–do we need to install them in Firefox too? I'm game to test stuff out but I'm not sure what we should be doing.

**Comment by muffinresearch** [comment]
This is possible now as documented here: https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md#developing-with-a-local-https-server-recommended
