### ISSUE TITLE
Search bar has no explicit bg color, which can be overriden by OS theme

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3640]
Got this one reported in [the blog](https://blog.mozilla.org/addons/2017/10/25/test-new-look-addons-mozilla-org/#comment-224521).

> The search bar has its text color set explicitly, but not its background color. Looks pretty horrible on Linux with a dark Gtk theme: https://imgur.com/a/7Icmi
> Please always overwrite either both background and foreground color for input elements (and body too)!

**Comment by willdurand** [comment]
Screenshot:

![](https://imgur.com/a/7Icmi)

**Comment by vcarciu** [comment]
@jvillalobos : can you please ask the reporter to verify this? Not sure how he applied the theme on Linux in order to change the background of the search field.
