### ISSUE TITLE
Remove unused errorPage reducer for old error pages

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3648]
This code is no longer used: https://github.com/mozilla/addons-frontend/blob/2e870ae660214ab6873793497f29cca17d9a7049/src/core/server/base.js#L300

The reducer can also be removed: https://github.com/mozilla/addons-frontend/blob/9fd02d91f28d2c96d5541f1883640f6b4bfd6be1/src/core/reducers/errorPage.js

This was an older implementation of rendering error pages when redux async connection failures occurred. We currently handle this directly at the end of the promise chain: https://github.com/mozilla/addons-frontend/blob/9fd02d91f28d2c96d5541f1883640f6b4bfd6be1/src/core/server/base.js#L345

**Comment by nileshgulia1** [comment]
I would like to work on this

**Comment by kumar303** [comment]
Thanks for the offer. Just beware that we may not have time to review a patch for it because we're all busy with next week's release.

**Comment by nileshgulia1** [comment]
hey @kumar303 ,After removing(commenting )the following code  from ```base.js```
```javascript
 const errorPage = store.getState().errorPage;
          if (errorPage && errorPage.hasError) {
            log.info(`Error page was dispatched to state: ${errorPage.error}`);
            throw errorPage.error;
}
``` 
and removing ```errorPage.js``` .The Web page fails to run locally.

**Comment by kumar303** [comment]
I appreciate your help but unfortunately we just don't have extra bandwidth right now to spend time on this. I think we'll be able focus on code quality issues like this one after a couple weeks.

**Comment by kumar303** [comment]
This reducer was fixed at some point
