### ISSUE TITLE
Install button looks misaligned with badge on 2680px desktop screen

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3651]
### Describe the problem and steps to reproduce it:

- Load the site on a desktop screen that is 2680px wide or smaller
- go to the detail page for a featured add-on

### What happened?

The install button looks misaligned with the featured badge:

<img width="1340" alt="screenshot 2017-10-26 12 35 09" src="https://user-images.githubusercontent.com/55398/32067941-7161201a-ba4a-11e7-8a60-b182e0917e9a.png">

### What did you expect to happen?

I can't find any mocks for this page with badges so I'm not sure. Maybe the badge and the button could line up? But I don't know.

**Comment by tofumatt** [comment]
I'll be fixing this as part of #3588, it's pretty much the same issue really as moving the badge around should fix the button.

**Comment by ValentinaPC** [comment]
@tofumatt 
Here are some window resize screenshots:
![r1](https://user-images.githubusercontent.com/15685960/32267261-51e9182a-bef3-11e7-902e-f9000725b683.png)
![r2](https://user-images.githubusercontent.com/15685960/32267263-520a849c-bef3-11e7-8dd4-34fc88b5ae9d.png)
![r3](https://user-images.githubusercontent.com/15685960/32267264-52299a26-bef3-11e7-9ad6-d7efb586cc70.png)

What do you think?

**Comment by tofumatt** [comment]
That only happens with all three badges which is very unlikely given featured, experimental, and restart required are pretty mutually exclusive. I guess I’d be cool with fixing it in a follow-up issue actually but this one can be closed. It’s pretty minor :-)

- Matt (Sent from mobile)

**Comment by ValentinaPC** [comment]
Based on above comments and screenshots, this can be marked as verified-fixed on AMO-dev FF56(Win 7).
