### ISSUE TITLE
Rating stars look jumpy when you hover over them

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3652]
### Describe the problem and steps to reproduce it:

* go to an add-on detail page on desktop
* log in
* hover over a star to rate the add-on

### What happened?

The stars look jumpy because the hover image shrinks in size (or maybe it doesn't have the same stroke).

![addons-frontend-star-jump mov](https://user-images.githubusercontent.com/55398/32068694-8392659e-ba4c-11e7-8f8d-bed8e8069ee4.gif)

### What did you expect to happen?

The stars should not jump on hover

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10)

![ratingstars](https://user-images.githubusercontent.com/31961530/32166595-02f38226-bd6f-11e7-9c23-833ba46e2990.gif)
