### ISSUE TITLE
Firefox Pioneer installed (added) and enabled, then there's an invitation to add it

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3653]
## Steps

In the screen recording embedded at https://discourse.mozilla.org/t/-/20860/8?u=grahamperrin 

1. the extension was installed (added) and enabled before recording began; and then
2. the new front-end invited me to add the extension. 

### Observation

https://addons-dev.allizom.org/en-GB/firefox/search/?page=5&q=firefox+pioneer&sort=name&type=extension does **not** find _Firefox Pioneer_. I guess that it's somehow exceptional. 

#### Side note

@jvillalobos did I see you, somewhere, abbreviate a Discourse URL without the topic number? If so: it is (as far as I recall) not as robust as using the `/-/` slug e.g. as shown above. AFAIR without the topic number, there is (or was) a risk of no longer finding the topic _if_ there's a change of title. (The number is persistent; the title can be volatile.)

**Comment by kumar303** [comment]
> the new front-end invited me to add the extension

Can you elaborate on this. What do you mean by *invited me*? I don't see an invitation message in your screencast.

**Comment by grahamperrin** [comment]
Hi, thanks for asking. I meant the button that invites me to 'Add to Firefox'. Pointed at, but not clicked, in this frame from the recording: 

![2017-10-26 20 17 13 frame](https://user-images.githubusercontent.com/192271/32076281-50ce1b44-ba97-11e7-87bd-ffe6f2b35590.png)

> … https://addons-dev.allizom.org/en-GB/firefox/search/?page=5&q=firefox+pioneer&sort=name&type=extension does not find Firefox Pioneer. …

For reference: 

![2017-10-26 20 37 47](https://user-images.githubusercontent.com/192271/32076344-8758173c-ba97-11e7-8886-b11bfa5d7932.png)

**Comment by kumar303** [comment]
Thanks for taking the time to file an issue. This is a known bug. It happened because we had to revert the install switch in https://github.com/mozilla/addons-frontend/issues/3557 but we will soon put back the functionality that detects when an add-on is already installed.

**Comment by grahamperrin** [comment]
@kumar303 thanks. 

Also I can confirm that where https://addons-dev.allizom.org/en-GB/firefox/search/?page=5&q=firefox+pioneer&sort=name&type=extension fails to find _Firefox Pioneer_, https://addons.mozilla.org/en-GB/firefox/search/?q=Firefox+Pioneer&type=extension succeeds.
