### ISSUE TITLE
LoadingText is added on server render for out of range pages causing a lot of CSP reporting

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3655]
## STR:

Go to https://addons.mozilla.org/en-US/firefox/search/?page=30000&platform=mac&q=search and watch the network tab.

## What happens:

There's a lot of network caused by CSP reporting. The CSP reports look to be caused by style props that are rendered as in-line styles in the server render.

Each report is uploading ~1.6k of json and that report is sent 100s of times over.

## What should happen:

The loading indicators should not be shown in a server render or the style props should be with-held. This might be fixed by solving #3313 

<img width="2329" alt="search_results_for__search__-_add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32075983-5adab4c2-ba96-11e7-85c3-e16517307295.png">

**Comment by muffinresearch** [comment]
This may suggest that https://github.com/mozilla/addons-frontend/issues/3313 should be increased in priority.

**Comment by willdurand** [comment]
I think this is fixed now, at least in -dev. @muffinresearch could you confirm?

**Comment by muffinresearch** [comment]
@willdurand looks good to me on -dev.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF57(Win 7).
2 CSP report lines are still displayed, but I guess is not an issue, yes?
Please see screenshot:
![last_page_of_themes](https://user-images.githubusercontent.com/15685960/32836722-7837f854-ca13-11e7-8ae3-df42baa455fa.png)

**Comment by willdurand** [comment]
@ValentinaPC could you provide the details of these CSPs?

**Comment by ValentinaPC** [comment]
These kind of details:
![2017-11-15_1528](https://user-images.githubusercontent.com/15685960/32838491-c3cb94a0-ca19-11e7-8655-d5dd60e5d82e.png)
If not, please be more specific about what details will help you. Thanks!
Also I want to add that those 2 cspreport lines are listed while heading to the last pages of search results.

**Comment by willdurand** [comment]
@ValentinaPC yep, that's helpful. Could you share the "Params" tab (on the right panel)?

**Comment by ValentinaPC** [comment]
![param](https://user-images.githubusercontent.com/15685960/32839364-dc01ecc4-ca1c-11e7-96c7-3c7c427c3758.png)

**Comment by willdurand** [comment]
So I think this is a different report, unrelated to this issue.

**Comment by ValentinaPC** [comment]
Ok, so I'll mark this verified fixed, then.
If is necessary to log a separate issue for those csp messages, please let me know.
