### ISSUE TITLE
Hero description is missing on desktop

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3660]
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Observe hero banners

Expected results:
Each hero has a short description under its name.

Actual results:
Only the hero positioned on the left has a description.

Notes.Issues:
_Not reproducible on device._
Verified on AMO-dev FF56(Win 7, Android 7.2.1). Reproducing on desktop an all servers.
Screenshot for this issue:
![2017-10-27_0954](https://user-images.githubusercontent.com/15685960/32091440-dab61626-bafc-11e7-8412-b118f224a210.png)

**Comment by willdurand** [comment]
Yes, it works as expected actually. On desktop, there should be subheading for the largest hero.

**Comment by ValentinaPC** [comment]
@willdurand : and nothing for the small ones?
I thought it should be consequent with mobile pages.

**Comment by willdurand** [comment]
See here for the new mock-ups: https://github.com/mozilla/addons-frontend/issues/3613#issuecomment-339339255.

On mobile, heros have the same size, therefore I kept the headings for all of them.

**Comment by ValentinaPC** [comment]
Ook :)
They look a bit big and empty, but is not my choice.
We can close this.
