### ISSUE TITLE
Average rating stars are not yellow in listing pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3661]
Steps to reproduce:
1. Make a search i.e. https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&q=test&type=extension
2. Observe each add-on rating stars

Expected results:
Average ratings starts are yellow.

Actual results:
Average ratings stars are gray.

Notes/Issues:
Verified on AMO-dev FF56(Win 7, Android 7.2.1)
Screenshot for this issue:
![2017-10-27_1230](https://user-images.githubusercontent.com/15685960/32097636-dc99c846-bb12-11e7-8031-fd3d1adf03db.png)
 
Relates to #3612

**Comment by willdurand** [comment]
Isnt it part of the new mock-ups?

**Comment by ValentinaPC** [comment]
Hope not. :)

**Comment by willdurand** [comment]
See: https://github.com/mozilla/addons-frontend/issues/2564#issuecomment-339934865.

**Comment by kumar303** [comment]
I know, right? I was sad to see them turn to gray. It used to be so colorful.
