### ISSUE TITLE
New review submitted on all-reviews page is not visible

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3664]
### Describe the problem and steps to reproduce it:

* Go to an add-on detail page
* Click on *Read N reviews* to see the list of all reviews
* Click a star (from the left sidebar) to begin reviewing the add-on
* Write a review, click Submit

### What happened?

The review does not show up on the page

### What did you expect to happen?

The review should show up on the page

### Anything else we should know?

If you reload the page you can see the review

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.0)

![pagerefresh](https://user-images.githubusercontent.com/31961530/32235034-0a8ac0fa-be67-11e7-81dc-4d6d1c640bd8.gif)
