### ISSUE TITLE
typo: suport -> support

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-frontend#3665]
https://github.com/mozilla/addons-frontend/blob/9203f9b4b9a87a01262df9b0429d8384e768fe86/locale/en_US/LC_MESSAGES/amo.po#L1312

**Comment by willdurand** [comment]
Good catch, thanks! Do you want to contribute? This typo is located in the `StaticPages` component: https://github.com/willdurand/addons-frontend/blob/d62d26014829fdff100baf78ebe972341c0b0fb0/src/amo/components/StaticPages/About.js#L71.

**Comment by kumar303** [comment]
Let's just get this fixed :) Thanks @peiying2

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix screenshot:
![2017-10-30_1136](https://user-images.githubusercontent.com/15685960/32164234-836e75da-bd67-11e7-8579-655ca03fecda.png)
