### ISSUE TITLE
All themes are disabled and cannot be installed

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3669]
### Describe the problem and steps to reproduce it:

* Go to a theme detail page using a desktop browser or Android

### What happened?

The theme is disabled

![screenshot-2017-10-27 eyeballs2 - add-ons for firefox](https://user-images.githubusercontent.com/55398/32126354-d0720ace-bb35-11e7-9e43-0d532269d178.png)

### What did you expect to happen?

It should be enabled

### Anything else we should know?

Regression from https://github.com/mozilla/addons-frontend/issues/3649

**Comment by vcarciu** [comment]
Verified as fixed : 
![themeunavailable](https://user-images.githubusercontent.com/1583842/32232313-743b9742-be60-11e7-8d12-db329251fce8.png)
