### ISSUE TITLE
Switch stage to run the new frontend by default

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3677]
This should follow the same criteria as #3314 and should be done following the tag **_on Tuesday (31st October)_**

The cookie set to mamo=off should still work as an opt out but that should be the only way to see the legacy frontend.

Here's a few thoughts on what criteria need to be met (feel free to add to them if you can think of others).

* [x] with no mamo cookie set all UAs (inc mobile) should get the new frontend.
* [x] with a mamo cookie set to "on" all UAs (inc mobile)  should get the new frontend.
* [x] with a mamo cookie set to  "off" all UAs (inc mobile) should get the legacy (django) frontend. 
* [x] Pages not yet provided by the new frontend should still fallback to the legacy frontend.
* [x] Pages for Thunderbird and SeaMonkey should still be served by the old frontend regardless of cookie setting

**Comment by muffinresearch** [comment]
QA: Notes - once this is configured on stage it would be good to validate the checkboxes as noted above.

**Comment by bqbn** [comment]
-stage is now showing mobile site by default.

**Comment by vcarciu** [comment]
Verified as fixed for all criteria from above. Marking bug as verified.
