### ISSUE TITLE
Switch prod to run the new frontend by default

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3678]
This should follow the same criteria as #3314 and should be done following the push **_on Thursday (2nd Nov)_**

The cookie set to mamo=off should still work as an opt out but that should be the only way to see the legacy frontend.

Here's a few thoughts on what criteria need to be met (feel free to add to them if you can think of others).

* [ ] with no mamo cookie set all UAs (inc mobile) should get the new frontend.
* [ ] with a mamo cookie set to "on" all UAs (inc mobile)  should get the new frontend.
* [ ] with a mamo cookie set to  "off" all UAs (inc mobile) should get the legacy (django) frontend. 
* [ ] Pages not yet provided by the new frontend should still fallback to the legacy frontend.
* [ ] Pages for Thunderbird and SeaMonkey should still be served by the old frontend regardless of cookie setting

Follows on from #3314 and #3677

**Comment by vcarciu** [comment]
Verified as fixed for all situations described in description
