### ISSUE TITLE
"Register or Sign in" link in Developer Hub header disappears if window isn't wide enough

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3683]
The header on the Developer Hub has a strange transition when it is narrowed a bit
Wide:
<img width="1040" alt="header-1" src="https://user-images.githubusercontent.com/62568/32173995-8d5aa954-bd78-11e7-8122-04229cca2d5b.png">
Narrow:
<img width="1020" alt="header-2" src="https://user-images.githubusercontent.com/62568/32173997-8f2f0090-bd78-11e7-970d-f24bc04e85ed.png">
The layout changes significantly, and most importantly, the "Register or Sign in" link disappears completely.

What I would expect is the middle space to get narrower, and then the "Add-ons Developer Hub" title to disappear to make more room.

**Comment by tofumatt** [comment]
Moved to addons-server.
