### ISSUE TITLE
No rating stars at hover for add-ons inside  "More extensions by author_name" section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3684]
Steps to reproduce:
1. Load an add-on details page i.e. https://addons-dev.allizom.org/en-US/firefox/addon/quick-translator/
2. Hover over the add-ons listed in the "more extensions by author_name" section

Expected results:
Number of users are hidden. Average ratings stars are shown. 
There are no display or layout issues.

Actual results:
Number of users are hidden, but no average ratings stars are shown. 
There is a layout issue at hover for add-ons with names on 2 rows.

Notes/issues:
Verified on AMO-dev FF56(Win 7).
Video for this issue:
![li](https://user-images.githubusercontent.com/15685960/32174952-fd35ca20-bd8b-11e7-9dd1-405e978a6c0e.gif)

Relates with #3622

**Comment by willdurand** [comment]
ah good catch, thanks!

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Postfix video:
![hover](https://user-images.githubusercontent.com/15685960/32212646-89317698-be20-11e7-9941-d35f91707056.gif)
