### ISSUE TITLE
Remove "Manage API Keys" from user dropdown when logged in

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3686]
This isn't a primary action, even for developers, so it makes sense to only have it in the Developer Hub.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7, Android 7.2.1)
Postfix screenshot:
![2017-10-31_0934](https://user-images.githubusercontent.com/15685960/32212351-1ee02b82-be1f-11e7-8d48-b5872564133a.png)
