### ISSUE TITLE
Search box should work the same from all sections of the site

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3689]
Instead of having "Find add-ons", "Find extensions", and "Find themes", there should only be "Find add-ons". If users need to filter down results, there are controls in the search results page. I think it's better to provide a consistent experience so users can find any add-on from anywhere on the site.

**Comment by muffinresearch** [comment]
@jvillalobos I'm not so sure about this, it seems counter-intuitive that if I make a search from the themes page I get add-ons and vice versa. 

Do you know if @pwalm got any feedback on this aspect of the site from user-testing?

**Comment by jvillalobos** [comment]
Don't know about user testing. My take is that users shouldn't know the difference between a theme, an extension, or something else. Search should work consistently across the site because users shouldn't have to figure out where in the site they are in order to know which results they will get.

**Comment by muffinresearch** [comment]
@jvillalobos ok, do you want us to land the patch to implement as specced in this issue? Or, can it wait a bit to see if Phil had any insights into what users made of the changing search context?

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF56 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/32542689-128fc460-c47c-11e7-843a-d00c373b9a18.png)
Mixed search suggestions:
![image](https://user-images.githubusercontent.com/31961530/32545131-62b9a7ba-c483-11e7-9ab9-f1864c72901f.png)

Note:There is one scenario in which, I believe, the new search type doesn't work as expected:
STR:
1. select the Themes tab from AMO homepage
2. perform a random search which will expose mixed results (i.e. blue)
3. observe what happens in the header menu

Expected:
Given the fact that the search results are showing now a mixture of themes and extensions, the Explore tab should be the one highlighted

Actual result;
The Themes tab remains highlighted, which might be misleading considering that our search results are not only themes
Note: Explore tab is highlighted after a page refresh. Same applies for a search made from Explore tab.

![newsearch](https://user-images.githubusercontent.com/31961530/32546691-93b836e2-c488-11e7-8669-62e06d4acc97.gif)

**Comment by willdurand** [comment]
Indeed. That's a bug I cannot trigger with Firefox Nightly, but I can reproduce it with Chrome for instance.

**Comment by willdurand** [comment]
Ah no actually, it is slightly different.

**Comment by willdurand** [comment]
@AlexandraMoga could you make sure these STR can trigger the bug you're mentioning if you start from the homepage, without having performed any action before? Like no previous search with "blue"?

**Comment by AlexandraMoga** [comment]
@willdurand you are right, there was a step missing. The issue will appear at the second search with the same search term. I can reproduce this constantly now.

**Comment by kumar303** [comment]
@AlexandraMoga since the regression you discovered in https://github.com/mozilla/addons-frontend/issues/3689#issuecomment-342791142 was minor (it was only a display issue) then it would have been more helpful to file as a follow-up issue. It creates confusion for us when an issue is re-opened because it's hard to keep of track of how the original patch is moving through the release process. It was a good catch though, thank you.

**Comment by AlexandraMoga** [comment]
@kumar303 Thanks for your suggestion. I will keep that in mind. If you think it is still helpful, I could file a new issue now and mark this one as closed.

**Comment by kumar303** [comment]
I don't think we need a new issue for the latest patch.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO dev with FF56 (Win10 and Andorid 7.0)

![fixsearch](https://user-images.githubusercontent.com/31961530/32597217-b6efce16-c53e-11e7-916d-3c8731fdfca1.gif)

**Comment by krupa** [comment]
Can we give users the option to reset the search from the header? this way, we can provide context-specific search and a way to easily reset it without having to fiddle with the filter options.

**Comment by jvillalobos** [comment]
I don't understand the question. What do you mean by reset the search?

**Comment by willdurand** [comment]
I got feedback about this issue today. For some users, filters are not visible enough on the search results page. Thinking about it, I tend to agree.

So, some users tend to navigate to a section (extensions or themes) to hopefully get refined results based on their initial search. This does not work and they navigate to a landing page instead. From here, they search again but get the same results as before, hence entering an infinite loop until they find the filter they need..

**Comment by jvillalobos** [comment]
Maybe the add-on type drop-down should be replaced with something like a radio-button, so users can see the words "Extension" and "Theme" rather than just the less-clear "Add-on type".

**Comment by pwalm** [comment]
- @jvillalobos Could do the radio button solution as opposed to the drop down.
- @krupa I've spec'd out a reset search function ("[x] Clear Filters", would that solve the issue?
<img width="543" alt="screen shot 2017-11-16 at 3 47 37 pm" src="https://user-images.githubusercontent.com/6797635/32922128-8a448f94-cae5-11e7-9be4-6439476a573f.png">

**Comment by ValentinaPC** [comment]
@pwalm - your "Clear filters" solution makes sense only if the search is depended of each page - in Extensions page we return only extensions, in Themes page only themes, which is not the case right now due to this exact issue. 
While present case - mixed search results - not sure how "Clear filters" will help, because Add-on type is "All" from the start.

**Comment by tofumatt** [comment]
That space is used on mobile to show/hide (expand/contract), so that's also an issue:

![2017-11-17 16 26 34](https://user-images.githubusercontent.com/90871/32957634-3172cad2-cbb4-11e7-8ff3-5861307b0ca6.gif)

**Comment by willdurand** [comment]
Please see #3942 instead. This issue is closed.
