### ISSUE TITLE
Write a review window can't be closed if the user click on it's right or it's left side

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#3691]
### Steps to reproduce:
1. Open an add-on page
2. Click on the review stars to open the write a review page
3. Click outside the write a review page on the right or on the left

### Expected results:
The write a review page can be closed.

### Actual results:
The page is not closed if the user clicks on the right or the left side. The page closes only if the user clicks on top or on the bottom of the page

### Notes/Issues
Verified in FF56(Win7) Issue can be reproduce in amo-dev, stage and prod.
Screeshot for this issue:
![writeareviewclose](https://user-images.githubusercontent.com/15685441/32178536-9cf330f8-bd95-11e7-9af2-46dc4ab88672.png)

**Comment by kumar303** [comment]
This can be closed after https://github.com/mozilla/addons-frontend/issues/3636

**Comment by pwalm** [comment]
I've redesigned our modal layouts, they now have an "x" to close:
![screen shot 2017-12-01 at 1 24 21 pm](https://user-images.githubusercontent.com/6797635/33504094-f6a7d9dc-d69a-11e7-809d-09ed9af82f38.png)

I'll redesign this specific flow/modal shortly.

**Comment by kumar303** [comment]
> I'll redesign this specific flow/modal shortly.

@pwalm That would be great. Take a look at https://github.com/mozilla/addons-frontend/issues/3636 where I'm proposing that we actually ditch the modal and make it look more like an inline textarea similar to how replying to a review (as a developer).

**Comment by muffinresearch** [comment]
Would be nice to make the close work on pressing `escape` too.

**Comment by pwalm** [comment]
Agreed, pressing "esc" would be a great closing option as well.

**Comment by muffinresearch** [comment]
The new designs are modal free so closing.

**Comment by bobsilverberg** [comment]
This can be closed when https://github.com/mozilla/addons-frontend/issues/6349 lands, which should be next week.

**Comment by AlexandraMoga** [comment]
The above scenario can't be reproduced anymore with the new inline review form.

I'm marking this issue as verified fixed.
