### ISSUE TITLE
Show links to statistics dashboard when stats are public and when user has permission

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3692]
#2751 added the link when the user owns the add-on, but there are other cases to support:
* When the developer chooses to make the statistics public. This is an setting that is set per-add-on.
* When the user has `Addons:Edit` permission.

**Comment by kumar303** [comment]
Duplicates: https://github.com/mozilla/addons-frontend/issues/3603 https://github.com/mozilla/addons-frontend/issues/3604
