### ISSUE TITLE
Show add-on name in expanded screenshot view

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3695]
The expanded screenshots view take over the entire content area, so only the URL and page title point to the add-on being looked at. @pwalm, what do you think about adding text to the title bar of the screenshots view saying something like "Screenshots for $ADDON"?

**Comment by pwalm** [comment]
New expanded screenshot view:
![screenshot detail - 1366px](https://user-images.githubusercontent.com/6797635/36331618-789ff93c-1323-11e8-8b44-345b569a136e.png)

This kills a few birds: Adds name, follows Photon, removes the migraine inducing "flash" of the current implementation. The modal should fill the screen (with the above margins/padding), but the screenshot should not exceed the grey bounding area (which is variable). The screenshot should sit centered to the modal, and not scale up the image to fit the area (if it is too small, that's on the developer). Any images larger than the grey bounding area should scale down. Button follow the ["ghost" implementation](https://design.firefox.com/photon/components/buttons.html#ghost-3) in the design guide.

**Comment by pwalm** [comment]
Updated to add "1 of [x]" caption at the bottom of the modal:
![screenshot detail - 1366px](https://user-images.githubusercontent.com/6797635/36331894-a34c00f8-1324-11e8-80b9-59cfeaa1da98.png)

**Comment by avgupt** [comment]
Hey, can I work on this?

**Comment by bobsilverberg** [comment]
@avgupt Thanks for your interest. You might be able to work on this, but that UX guidance is very old, so I'm not sure it's accurate anymore. @jvillalobos what do you think? Should we get an updated opinion from UX, or just move forward with implementing this as @pwalm suggested?

**Comment by jvillalobos** [comment]
The UX proposal still looks valid, but I think it'd be good to get a second opinion from @aaronrbenson if he has time. I'll ask on the next frontend meeting.

**Comment by aaronrbenson** [comment]
Yeah this looks good! I might line up the extension name and the closing 'x' horizontally. Outside of that, this would be a nice update.

**Comment by jvillalobos** [comment]
With Aaron's note I think we're good to go with this.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-124
