### ISSUE TITLE
Show support e-mail address in More Information box

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3696]
Developers can provide a Support URL, a Support E-mail address, both, or neither. The new front-end currently doesn't support the e-mail address.

**Comment by jvillalobos** [comment]
Setting as MVP because it could block some users from requesting support from add-on devs.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Andorid 7.0)

![supportemail](https://user-images.githubusercontent.com/31961530/32273982-769cd426-bf0d-11e7-9162-0829fac1e46a.gif)
