### ISSUE TITLE
Hover on nav links should mimic tab hover

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3704]
For consistency's sake, the line underneath the links on the nav should animate the same way they do when hovering a tab in the browser:
https://cl.ly/0u0W2s0p360B

The line should still be underneath the text, but it should expand outward from the centre of the copy.

**Comment by muffinresearch** [comment]
@pwalm I'm not sure I follow what's being requested here. Can you point to an example of what the end result should be?

**Comment by willdurand** [comment]
I think we want this now: https://codepen.io/anon/pen/emNjGo. If so, I can give it a quick go since I found how to do it 😄

**Comment by vcarciu** [comment]
Verified as fixed : 
![mimic](https://user-images.githubusercontent.com/1583842/32231446-44e324f8-be5e-11e7-9d6f-8739f299628b.gif)

**Comment by MajedHaimour** [comment]
Please, I need Hover Zoom for Firefox
