### ISSUE TITLE
"Register/Log in" button needs to be made solid

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3705]
We don't have a ghost/outline button spec yet in the design system, so until then, we need to make this button solid. I'll provide the proper spec for this soon.
<img width="145" alt="screen shot 2017-10-30 at 7 42 34 pm" src="https://user-images.githubusercontent.com/6797635/32205135-c347853c-bdaa-11e7-9c09-18d9bbac4ee6.png">

**Comment by pwalm** [comment]
Solid! Follow the [button spec on the Design system](http://design.firefox.com/photon/components/buttons.html) and you're set:
![screen shot 2017-12-04 at 11 01 48 am](https://user-images.githubusercontent.com/6797635/33570701-8c49ec84-d8e2-11e7-8b89-8e5e1d40f2f9.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![registerlogin](https://user-images.githubusercontent.com/1583842/35638159-113a8566-06bf-11e8-93f6-f751a1fd3074.png)
