### ISSUE TITLE
User name is not hyperlink on reviews page

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#3707]
### Describe the problem and steps to reproduce it:
Navigate to https://addons.mozilla.org/en-US/firefox/addon/measure-it/reviews/
Observe username of reviewer

### What happened?
Username is plain text <Atomico>

### What did you expect to happen?
Username should be hyperlink <https://addons.mozilla.org/en-US/firefox/user/Atomico/> 
(as on legacy website)

### Anything else we should know?
Legacy
<img width="476" alt="screen shot 2017-10-31 at 11 23 27 am" src="https://user-images.githubusercontent.com/5318732/32209375-fea4af28-be2d-11e7-9b73-63486af25f01.png">

New mobile layout
<img width="467" alt="screen shot 2017-10-31 at 11 23 43 am" src="https://user-images.githubusercontent.com/5318732/32209385-0ab803e6-be2e-11e7-8ba5-b31aa5dd0bb1.png">

**Comment by tofumatt** [comment]
User pages are no longer visible unless the user is a developer who has published an add-on, if I recall correctly. I think there could be another criteria but leaving a review isn’t enough, so this is working as intended.

**Comment by tofumatt** [comment]
@willdurand and I chatted on IRC and we don’t think these should ever be links, actually. It will be inconsistent and it’s not a great place to point users to developer pages; they’re trying to learn about an add-on by reading a review so linking away to a devkeoper’s profile is just distracting. So I think this will be a won’t fix entirely.

**Comment by eviljeff** [comment]
A call for @jvillalobos

**Comment by jvillalobos** [comment]
I agree. We will only show user pages for developers in the future, and it's not particularly useful to make them into links in the reviews section.

**Comment by FlorianFranzen** [comment]
So there will be no view, that allows one to view all reviews written by the same reviewer? I think that such a feature would help users weigh reviews more appropriately, as well as giving them the chance to discover new Addons.

**Comment by tofumatt** [comment]
Hmmm... that’s a good point. A negative review from someone who ONLY writes negative reviews may carry less weight. Maybe we should display profiles for anyone who has written a review.

- Matthew Riley MacPherson
tofumatt.com

**Comment by jvillalobos** [comment]
Profiles are a common vector for spamming, which is why we don't want to display them unless strictly necessary. It's not uncommon for spam accounts to be created that then write seemingly legitimate reviews for multiple add-ons.

Developer profiles are useful because a user may be interested in seeing other add-ons by a developer they like. I don't think looking at other reviews by a user is useful enough to warrant the spamming problem.

**Comment by tofumatt** [comment]
Do spam profiles still get created with much regularity, after the move to Firefox Accounts? I’d think it’s a fair bit more effort to spam things with it in place. Dunno if we have any data on that.

**Comment by jvillalobos** [comment]
I haven't seen any decrease in spamming since the move to FxA (but I don't have hard numbers on that). FxA actually makes it impossible for us to effectively delete spam accounts, so dealing with them has been a bit harder.
