### ISSUE TITLE
"Explore" option from the menu is showing active at refresh in add-on details page

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3712]
Steps to reproduce:
1. Load an extension/theme details page i.e https://addons-dev.allizom.org/en-US/firefox/addon/converter/
2. Refresh the page while looking at menu options

Expected results:
There are no issues.

Actual results:
Explore option from the menu is showing active for a second.

Notes/Issues:
Verified on AMo-dev FF56(Win 7). Reproducing on all AMO servers.
Video for this issue:
![explore](https://user-images.githubusercontent.com/15685960/32225938-c110f140-be4f-11e7-9c81-43dabe941818.gif)

**Comment by willdurand** [comment]
I cannot reproduce it locally, but it is indeed reproducible on -dev. The HTML sent by the server marks the "Explore" button as "active" whereas the serialized state has `viewContext = extension` 🤔

**Comment by AlexandraMoga** [comment]
By following the above steps we can observe now that the Explore tab will remain permanently highlighted.
Here is the reproduction:
![exploretab](https://user-images.githubusercontent.com/31961530/33660598-14142d86-da8d-11e7-9395-abe2322c9bf6.gif)

Reproduced only on -dev and -stage with FF57 Win10
In production, the behavior is the same as described initially by Valentina.

**Comment by muffinresearch** [comment]
I can still reproduce this.
