### ISSUE TITLE
Missing border (bottom) on active section link

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3713]
While looking at #3712, I saw that the border bottom was not displayed anymore after #3710:

<img width="380" alt="screen shot 2017-10-31 at 15 11 23" src="https://user-images.githubusercontent.com/217628/32228218-f127b91a-be4d-11e7-9c8a-153f30c0ece7.png">

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.0)

![bottomborder](https://user-images.githubusercontent.com/31961530/32271186-6605cab6-bf01-11e7-921e-60f4696d3125.gif)
