### ISSUE TITLE
Summary text can push up against the button

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3716]
https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/

I added some extra text `a a a` to demonstrate.

<img width="992" alt="awesome_screenshot_plus_-_capture__annotate___more_-_add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32229769-86a9c33e-be49-11e7-87f8-c9cabd888c5a.png">

**Comment by tofumatt** [comment]
I fixed this in #3659 😄

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7)
Postfix screenshot:
![2017-11-01_1031](https://user-images.githubusercontent.com/15685960/32266372-d8fac434-beef-11e7-9ad0-abf1566f99a3.png)
