### ISSUE TITLE
Number of reviews from Add-on details page and "All reviews" page are inconsistent

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3718]
Steps to reproduce:

1. Go to an add-on details page (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/multi-highlight/)
2. In the rating section observe the number of reviews associated with the add-on and then click on 'Read all Reviews'
3. Once the page loads, verify the actual number of reviews displayed

Expected result:
Number of reviews mentioned in the add-on details page and total reviews form 'All reviews' page are the same

Actual result:
Number of reviews from "All reviews' page is lower than the number mentioned in the details page

Notes: reproduced on AMO-dev with FF56 (Win10 and Android 7.0)

![inconsistentrew](https://user-images.githubusercontent.com/31961530/32233348-d5ca71e8-be62-11e7-9b98-308abcffe7d9.gif)

**Comment by willdurand** [comment]
mmh I think I know what it is..

**Comment by kumar303** [comment]
Sorry, there was an issue already filed for this but it didn't have a very searchable description. I'll try to fix it up and add your STR. https://github.com/mozilla/addons-frontend/issues/2327
