### ISSUE TITLE
New Homepage carousel promo: Games!

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#372]
@andymckay 

We'd like to promote a new collection on the Homepage. Could we please get this games collection placed in the [Disco Pane management tool](https://addons.mozilla.org/en-US/firefox/discovery/modules) by no later than **Tuesday, May 31**? 

------------------------------------

Overlay text (title, blurb, button):

**Games!**
Add more fun to your Firefox. Play dozens of games right from your browser—puzzles, classic arcade, action games, and more!
[Play now]

------------------------------------

Final URL will be:
https://addons.mozilla.org/firefox/collections/mozilla/games/

But please note that content curation is still in progress, so until I make Mozilla the "owner" of this collection, it lives here:
https://addons.mozilla.org/firefox/collections/sdevaney/games/

------------------------------------

And here's a generic background image suited for AMO's new-look design (created by pwalm)
![white-backgrounds-9](https://cloud.githubusercontent.com/assets/8496249/15234645/b64da7b4-1868-11e6-97e6-58dc94e11e47.png)

**Comment by muffinresearch** [comment]
@devaneymoz this should be re-filed on mozilla/addons-server as this looks like this is for the current amo.

This repo is going to contain the future amo frontend work but it's not used for that quite yet.

**Comment by andymckay** [comment]
@diox, could you add this in please? Given the timeline, we'd need to get it created before the next tag at the lastest so it can be deployed on the 26th.

**Comment by andymckay** [comment]
And sooner, if we want to give localisations a chance to get localised for this 😞

**Comment by diox** [comment]
I filed https://github.com/mozilla/addons-server/issues/2682 in addons-server so we can close this one.
