### ISSUE TITLE
Oldest review disappears from 'All Reviews' page after a new review is submitted

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3720]
Steps to reproduce:
1. Go to an add-on details page (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/mingrafow-crafow-donbise/reviews/)
2. In the rating section, click on 'Read all reviews'
3. Once the page loads, make a note of the oldest review left for the add-on
4. Select some rating stars and submit your own review
5. After the page refreshes, check again the oldest review

Expected results:
The oldest review remains the one observed before submitting your own review

Actual result:
The oldest review is no longer visible among the listed reviews

Notes: reproduced on AMO-dev with FF56 (Win10 and Android 7.0)

![reviewdisappears](https://user-images.githubusercontent.com/31961530/32234059-84f81372-be64-11e7-9e40-c39f6701e594.gif)

**Comment by muffinresearch** [comment]
Possibly related to https://github.com/mozilla/addons-frontend/issues/4109

**Comment by ioanarusiczki** [comment]
I noticed that when I deleted my review(with text) from old pages went back to the new front end and submitted a new review (with text) the oldest review will not be displayed. 
Reproducible on AMO dev and stage using FF58 (Win10).

![delete review](https://user-images.githubusercontent.com/33448286/36090443-0dc1ff4e-0fe9-11e8-844d-105dda25f9bc.gif)

**Comment by muffinresearch** [comment]
Close in favour of the API issue. https://github.com/mozilla/addons-server/issues/6800
