### ISSUE TITLE
some of the new look pages do not work with e.g. ScrollUp

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3727]
Probably minor, maybe negligible. 

[ScrollUp](https://addons.mozilla.org/addon/scrollup/) with Firefox 56.0.2 (64-bit) on FreeBSD-CURRENT – one of a number of extensions that feature in the five-minute screen recording embedded in [post 101](https://discourse.mozilla.org/t/favorite-webextensions/17087/101?u=grahamperrin) under _Favorite WebExtensions? - Add-ons / Contribute - Mozilla Discourse_

The in-page button of the extension is: 

- apparent at pages such as https://addons.mozilla.org/en-GB/firefox/search/?page=73&sort=name&type=persona 
- non apparent at some of the other new look pages within the recording. 

If we ignore the legacy nature of ScrollUp, does this hint at a possible accessibility issue?

**Comment by tofumatt** [comment]
I don't think this points to an accessibility issue–if I'm wrong feel free to open a bug describing what we're doing wrong and steps to reproduce, but I consider this an issue with the add-on.
