### ISSUE TITLE
Add Preconnect header for mozilla CDNs

### ISSUE THREAD

**Issue by digitarald** [mozilla/addons-frontend#3730]
```
Link: <https://addons-amo.cdn.mozilla.net>; rel=preconnect; crossorigin
Link: <https://addons.cdn.mozilla.net>; rel=preconnect; crossorigin
```

Will cut down connect times and speed up loading for all assets on first-view.

More info: https://www.igvita.com/2015/08/17/eliminating-roundtrips-with-preconnect/

**Comment by tofumatt** [comment]
Is it best to add these to the HTTP headers over using the inline `rel="preconnect"` attribute on `<link>` tags? I guess that means the page can open the sockets earlier than when it parsed the `<link>` tag. We could configure these dynamically in our app based on our CDN config values which is less work I think if we used the tag hint.

Otherwise it's an ops bug.

**Comment by muffinresearch** [comment]
One additional thing to bear in mind is that on the legacy AMO we had some issues with how preloading was treated differently wrt CSP causing preloads to get blocked. The bugs related to this may have been fixed by now, but it's something to look out for by whoever looks at implementing this.

> Is it best to add these to the HTTP headers over using the inline rel="preconnect" attribute on <link> tags? I guess that means the page can open the sockets earlier than when it parsed the <link> tag. We could configure these dynamically in our app based on our CDN config values which is less work I think if we used the tag hint.

I would have thought we might be better to do this one in the app since we have the data of the urls to hand. We could also set the headers from the app if that was preferable - it might be easier since the app knows what statics are relevant, whereas above the app (in nginx) that might be more difficult to determine.

**Comment by digitarald** [comment]
Since preconnect does just a list of origins and not list full URLs that are only known to the app; the HTTP header would be easy and allow earlier discovery. <link> might be discovered right before the style/js resources are parsed as well, not giving much of a head start.

**Comment by diox** [comment]
FWIW, the webpagetest runs I've been doing suggest that it might help quite a bit, even if done in the HTML.

![Connection Waterfall](https://www.webpagetest.org/waterfall.png?test=180125_MK_98236855cacdafaa6ba7b3e39b466c76&run=1&width=930&type=connection&mime=1)

But as @digitarald said, we only need to list origins, not full URLs, so it's probably best to do this as a header. In any case, it looks like we can gain a couple hundreds milliseconds head start at least, for free.

**Comment by tofumatt** [comment]
I think it'd be best to do this on the ops side of things for now.


@bqbn:

Could we get two HTTP headers added to AMO stage (for testing), both should be `Link` headers with the content:

* `<https://addons-stage-cdn.allizom.org>; rel=preconnect; crossorigin`
* `<addons-amo-cdn.allizom.org>; rel=preconnect; crossorigin`

-------

If that all works we want the same `Link` header added to production but with the content:

* `<https://addons-amo.cdn.mozilla.net>; rel=preconnect; crossorigin`
* `<https://addons.cdn.mozilla.net>; rel=preconnect; crossorigin`

**Comment by willdurand** [comment]
@bqbn can we try what @tofumatt suggested above? Thanks!

**Comment by bqbn** [comment]
I may not have time working on this in a week time, so I'll drop it to p3.

Please let me know if this must be a p2 for now.

**Comment by willdurand** [comment]
cc @diox

**Comment by diox** [comment]
Blast from the past ! This looks interesting to try out. We determined that it was better to do this via the header, but any reason why we wouldn't set the header from the nodejs app ?

**Comment by diox** [comment]
Note: I haven't tested it in Firefox, but https://bugzilla.mozilla.org/show_bug.cgi?id=1543990 claims it broke at some point - maybe just the HTML tag, not necessarily the header too. But even if it only benefits Chrome it's likely worth having.

**Comment by willdurand** [comment]
> Blast from the past ! This looks interesting to try out. We determined that it was better to do this via the header, but any reason why we wouldn't set the header from the nodejs app ?

Maybe because the nginx config removes some of the headers?

**Comment by diox** [comment]
I suspect this was just for our convenience (at the expense of ops). I think I'd rather have this in the app, then we could be smarter about it in the future, and we can re-use our settings without having to hardcode things in the nginx config.

**Comment by willdurand** [comment]
> I suspect this was just for our convenience (at the expense of ops). I think I'd rather have this in the app, then we could be smarter about it in the future, and we can re-use our settings without having to hardcode things in the nginx config.

Yes, in the past we didn't really support headers in our app but now we do so if `preconnect` can be set in our app, :+1:

**Comment by ioanarusiczki** [comment]
@diox I checked several AMO dev frontend pages - the response headers for the html documents (which the Network reveal at a page refresh) show the [mentioned](https://github.com/mozilla/addons-frontend/issues/3730#issuecomment-360844050) content:

![preconnect](https://user-images.githubusercontent.com/33448286/113721564-4fcfb400-96f8-11eb-939f-39868a221d5c.png)
