### ISSUE TITLE
Add link: preload for fonts

### ISSUE THREAD

**Issue by digitarald** [mozilla/addons-frontend#3731]
Add before the CSS in the `<head>`.

```
<link rel="preload" href="https://addons-amo.cdn.mozilla.net/979a13914c3398f40c3114ead422ed41.woff2" as="font" type="font/woff2" crossorigin>
…
```

Kickstarts the font download when the browser parsed the header but has not started parsing the CSS yet.

**Comment by muffinresearch** [comment]
One additional thing to bear in mind is that on the Django AMO we had some issues with how preloading was treated differently wrt CSP causing preloads to get blocked. The bugs related to this may have been fixed by now, but it's something to look out for by whoever looks at implementing this.

**Comment by Shivansh2407** [comment]
In which CSS file do we need to add this?
