### ISSUE TITLE
Add fallback using font-display to avoid text delay

### ISSUE THREAD

**Issue by digitarald** [mozilla/addons-frontend#3732]
Page load benchmarks show a large delay for showing a text-less page for more than 3+s (using Cable) on the addons details page.

More details: https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display (Landing in Firefox 58)

**Comment by tofumatt** [comment]
Reading this it seems like `fallback` will block for an "extremely small" bit (I wish the docs defined it), but then render the text with a fallback font after another undefined "short" waiting period.

That sounds like flash of unstyled text. It's cute that we have a CSS property to define that, but I'm not sure it's what we want. 😄

If there's a way to say "after 5-10 seconds if the font still isn't loading show a fallback" I'm okay with that, but I can't tell what the timing windows are from that doc and I don't want FOUT.

Maybe I'm missing something.

**Comment by digitarald** [comment]
The design goal for both swap and fallback is to have fonts that are as similar as possible, a trade off to avoid 3s invisible text, prioritizing content over design.

**Comment by tofumatt** [comment]
I’d like to get @pwalm’s thoughts on this then: are there fallback fonts you’d be okay with seeing while the actual fonts are loaded? If so then yeah let’s do this.

**Comment by digitarald** [comment]
This came up again in a [perf audit webinar](https://www.smashingmagazine.com/smashing-tv/auditing-performance-live/) that @tkadlec did recently for smashing conf (prompted by [me](https://twitter.com/digitarald/status/981654266837286912)).

Re-testing, on DSL the fonts cause the page to stay empty for 2sec+, which is close to hitting the browser cap (3sec) to fall back to the default font:

![filmstrip 1](https://user-images.githubusercontent.com/8599/38887104-bcb7fdda-422c-11e8-8354-b78d4efdaecb.png)

[Webpagetest results](https://www.webpagetest.org/result/180417_Q9_a1b7d49ecf64a4649d4eb08e27069914/) shows waterfall charts. Cluster of long red bars are fonts.

**Comment by digitarald** [comment]
For comparison, this is how it looks with fallback font (which triggered for 3G after 3sec).

![image](https://user-images.githubusercontent.com/8599/38911653-a97244e8-4285-11e8-99f4-e7eed9f6ee91.png)

![image](https://user-images.githubusercontent.com/8599/38911646-9a34c96a-4285-11e8-9c91-fdb1fc550102.png)

While this shows that the fallback works pretty well and doesn't seen to shift the layout, it also illustrates that users might already see the fallback but only after staring at empty boxes for 3sec.

**Comment by digitarald** [comment]
The fallback font is the system font (`sans-serif`). Screenshots are from Windows, so the fallback you see is Segoe UI.

Using only system fonts would cut out a massive resource and solve *all* slow font issues. Meanwhile, font-display can improve page loading drastically with only minor impact on design while the final fonts loads.
