### ISSUE TITLE
Investigate CSS bundle splitting

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3735]
Relates to https://github.com/mozilla/addons-frontend/issues/3734

Would it help perf to split up our CSS so that only relevant CSS is loaded for specific entry points?

We currently load all the styles in one go. Should we consider loading the CSS in smaller chunks splitting the bundles by different page entry points?

To figure this out we'd need to do some analysis of traffic and usage patterns and look at what others have discovered doing similar.

**Comment by willdurand** [comment]
Not sure we'll ever work on that realistically so I'm going to close this issue for now.
