### ISSUE TITLE
"Support Email" link is not marked as visited after click

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3737]
Steps to reproduce:
1. Load details page for an add-on that has Support Email set i.e. https://addons.allizom.org/en-US/firefox/addon/tile-tabs/
2. Click on it
3. Go pack to add-on details page

Expected results:
Link is marked as visited.

Actual results:
Link is not marked as visited.

Notes/Issues:
- any other link from More Info section behave as expected.
Verified on AMO-stage FF56(Win 7). Issue is also reproducing on -dev,.
Video for this issue:
![sl](https://user-images.githubusercontent.com/15685960/32277279-93d85ea4-bf1a-11e7-9ca7-ba9734b5570a.gif)

**Comment by willdurand** [comment]
I dont think it is possible to do that because email links are not usually visited.

**Comment by tofumatt** [comment]
Yeah, email links aren't marked as visited so this is working as expected.
