### ISSUE TITLE
Use Snyk in place of nsp to test for known security vulnerabilities

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3742]
### Describe the problem and steps to reproduce it:

When a known security vulnerability in one of our dependencies is disclosed, we want our tests to fail so we can apply the patch or ignore the advisory.

### What happened?

We already use [`nsp`](https://github.com/nodesecurity/nsp) for this but it doesn't catch all advisories.

### What did you expect to happen?

We should catch as many advisories as possible. Let's try switching to [`Snyk`](https://snyk.io/) because it reports more advisories.

**Comment by wagnerand** [comment]
You could also use both :)

**Comment by tofumatt** [comment]
If one is a superset of the other (which it sounds like `Synk` might be of `nsp`) we'll end up with double notifications for some things though, so unless they provide *different* notices we should stick to one 😄

**Comment by muffinresearch** [comment]
I've added the team to Snyk (you should get invites) and added it to addons-frontend and addons-linter for now to try it out.

**Comment by kumar303** [comment]
It looks like Synk is set up for our project which is great (I like it!) but this issue was about fully integrating it into our CI process which would start by replacing this test:

https://github.com/mozilla/addons-frontend/blob/master/.travis.yml#L18
