### ISSUE TITLE
Tag search doesn't work

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#3743]
Quite a few people have been sharing the link

https://addons.mozilla.org/en-US/firefox/search/?tag=firefox57

Because that's the way we've been looking to find out how many WebExtension add-ons there are.

On the new site it returns zero results :(

Might give people the impression that there aren't any WebExtensions, which I don't think is the intent.

**Comment by tofumatt** [comment]
Darn. I don’t think we link to tag search anywhere in the new UI so we never implemented it. FWIW it’s probably not too much work to implement support for next week’s tag, but if a user searches with FF57+ they’ll only get compatible extensions with any search, so they shouldn’t explicitly need a tag. The new site is designed not to surface incompatible add-ons.

- Matthew Riley MacPherson
tofumatt.com

**Comment by muffinresearch** [comment]
@tofumatt what would it take to pass through a tag param to the api if supplied in the search box. Fixing that would solve this bug and setup the ability to surface tags in the UI.

**Comment by tofumatt** [comment]
Probably almost nothing. I can take a look right now; thinking you want to cherry-pick this? It would *probably* be safe to do so.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/32326405-592fdaa4-bfdb-11e7-8df5-e46896f9cdd5.png)

**Comment by andymckay** [comment]
Great thanks! 

Also noting that https://addons.mozilla.org/en-US/firefox/search/ gives you zero results where as a user might expect it to return everything.
