### ISSUE TITLE
"See more" link available for less than 4 add-ons in that section

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3745]
Steps to reproduce:
1. Load an extension category i.e. : https://addons.allizom.org/en-US/android/extensions/feeds-news-blogging/
2. Observe "Featured" section

Expected results:
No "See more" link if less then 4 add-ons in this section.

Actual results:
"See more" link available even if there is only one add-on in that section.

Notes/Issues:
- reproducing on each category, for any section.
Verified on AMO-stage FF56(Win 7, Android 7.2.1).
Screenshot for this issue:
![2017-11-02_1121](https://user-images.githubusercontent.com/15685960/32318456-03b2950a-bfc0-11e7-8cb0-ce5aa199d76e.png)

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF57(Win 7) and is not fixed.
Please see screenshot:
![2017-11-15_1805](https://user-images.githubusercontent.com/15685960/32846307-932767d2-ca2f-11e7-8dd8-0eb5ac612b22.png)

**Comment by willdurand** [comment]
it is not deployed yet

**Comment by ValentinaPC** [comment]
Sorry about that. But when an issue is closed I am tempted to verify it, after let's say 2 hours.

**Comment by willdurand** [comment]
Usually it is deployed quickly but it looks like something is slow today.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win7)
Postfix screenshots:
![f1](https://user-images.githubusercontent.com/15685960/32881768-f240b03a-caba-11e7-8f6c-73581b0a82b7.png)
![f2](https://user-images.githubusercontent.com/15685960/32881769-f2604abc-caba-11e7-9e6c-626c8a257c41.png)
