### ISSUE TITLE
Add-on type is not changed to "All" from Featured results page after unchecking the featured box

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3746]
Steps to reproduce:
1. Load Extension homepage https://addons.allizom.org/en-US/firefox/extensions/
2. Go to "see more" from Featured section https://addons.allizom.org/en-US/firefox/search/?featured=true&type=extension
3. Uncheck "featured" box
4. Change Add-on type to "All"

Expected results:
The add-on type is changed. Results are also changed accordigly.

Actual results:
Add-on type option cannot be "all". No results are listed together with navigation functional arrows.

Notes/Issues:
- reproducing only for "relevance" sort option.
Verified on AMO-stage FF56(Win 7). Reproducing on all servers.
Screenshot for this issue:
![featured](https://user-images.githubusercontent.com/15685960/32319736-344b81c8-bfc4-11e7-81b7-f0cd2d237045.png)

**Comment by ValentinaPC** [comment]
Due to #3747 fix, this is no longer reproducing from "see more" featured pages in each category.
But there are still some pages where it happens like:
- homepage
- extension homepage
- themes homepage
Screencast from homepage:
![h](https://user-images.githubusercontent.com/15685960/32372490-b80fadd4-c09d-11e7-8918-98ae3d979d7b.gif)

**Comment by muffinresearch** [comment]
On a related note, I think we are protecting the search from empty searches. It was noted elsewhere that we don't show anything if no search term is provided. Despite this the api itself returns everything for an empty search. 

This would probably get fixed if we allowed a url with no params to return everything.

**Comment by ValentinaPC** [comment]
I observed that empty search is now working from homepage... but, is not entirely the same case as above, because I have an "OS" set in here, and above, I don't.
See video:
![empty](https://user-images.githubusercontent.com/15685960/32377479-7d91ac1c-c0b0-11e7-887a-2eaf85f62118.gif)


So, above scenario is only possible if we synchronize both "Add-on type" and "Operating System" to "All"

**Comment by willdurand** [comment]
Interesting, I think the patch in #3775 could fix this too (thanks to the new `SEARCH_ABORTED` action).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
While filter are set to "All", search is reset.
Postfix screenshot:
![themes_ext_homepage_-_featured](https://user-images.githubusercontent.com/15685960/32730025-6cc735a6-c88e-11e7-933e-2d225245bf76.png)
