### ISSUE TITLE
"Invalid 'type' parameter" red banner for "All" add-on type in each category

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3747]
Steps to reproduce:
1. Load any add-on category page i.e. https://addons.allizom.org/en-US/firefox/extensions/shopping/
2. Choose "see more" for any sorting option i.e. https://addons.allizom.org/en-US/firefox/search/?category=shopping&sort=hotness&type=extension
3. Change the add-on type to "All"

Expected results:
The search results are refined.

Actual results:
"Invalid 'type' parameter" red banner is displayed.

Notes/Issues:
Verified on AMO-stage FF56(Win 7, Android 7.2.1). 
Reproducing on all servers.

Not sure if is not related with https://github.com/mozilla/addons-frontend/issues/3563 .
Screenshot for this issue:
![2017-11-02_1203](https://user-images.githubusercontent.com/15685960/32320594-0384ba34-bfc7-11e7-93a6-daf012bd6ac0.png)

**Comment by tofumatt** [comment]
😱 Oh my, that's not good.

**Comment by muffinresearch** [comment]
A small step towards improving this would be to fix the error message to not be the size of a house.

The second step is probably to disable the type selector for category searches. 

Long term it would be really great to fix the categories to be the same across types which is a whole separate issue.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7, Android 7.2.1).
Add-on type is no longer listed in any add-on category.
Postfix video:
![cat](https://user-images.githubusercontent.com/15685960/32367170-e56b9d7e-c089-11e7-9622-af1dbaf8a6f2.gif)
