### ISSUE TITLE
CSP errors from discovery pane

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-frontend#3751]
### Describe the problem and steps to reproduce it:

Steps to reproduce: Using Firefox Nightly, open the console then open about:addons and visit the "Get Add-ons" pane.

### What happened?

The console has a CSP warning and a CSP error:
```
Content Security Policy: Directive ‘frame-src’ has been deprecated. Please use directive ‘child-src’ instead.
Content Security Policy: The page’s settings blocked the loading of a resource at self (“style-src https://addons-discovery.cdn.mozilla.net 'sha256-DiZjxuHvKi7pvUQCxCVyk1kAFJEUWe+jf6HWMI5agj4='”).
```

### Anything else we should know?

This was originally reported at:
https://bugzilla.mozilla.org/show_bug.cgi?id=1413892

**Comment by muffinresearch** [comment]
The frame-src one being deprecated is a wontfix since that for backwards compatbility for old clients.

The other one needs investigation because I can't seem to find why it would be triggered. There is an inline style element but it should be covered by the hash in style-src.

**Comment by willdurand** [comment]
We won't spend more time on the discopane since it has moved to FF.
