### ISSUE TITLE
Fallback buttons in the disco pane regressed with the "+"

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3752]
No-one will generally see this, but if you load the disco pane and mozAddonManager is disabled it looks like this:

<img width="879" alt="discover_add-ons" src="https://user-images.githubusercontent.com/1514/32337183-35aa2612-bfe9-11e7-869d-abb5b053e7dd.png">

**Comment by AlexandraMoga** [comment]
This can't be verified until a fix for [#4291](https://github.com/mozilla/addons-frontend/issues/4291) will be available
