### ISSUE TITLE
Add back "This review is for a previous version...." 

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3756]
## Issue

Unless I'm missing something: 

- no new look indication that a review may be **outdated**. 

Attention to the second of the pink highlights: 

![2017-11-02 17 48 35 conex reviews add-ons for firefox](https://user-images.githubusercontent.com/192271/32342612-cb159826-bff8-11e7-8543-e64e4b654f04.png)

Without the SeaMonkey user-agent string: 

![2017-11-02 17 41 28](https://user-images.githubusercontent.com/192271/32342772-5f217738-bff9-11e7-9254-580d92a5ee7e.png)

**Comment by grahamperrin** [comment]
Also, expect to see version specificity in user-specific lists of reviews such as https://addons.mozilla.org/user/muffinresearch/ where traditionally/currently we see: 

> This review is for a previous version of the add-on (0.3.4).

**Comment by kumar303** [comment]
We don't intend to carry over the concept of one review per version from the legacy site. We may still have some technical issues to work out before we can achieve one review per add-on, though.

**Comment by smayer97** [comment]
Never liked one review per add-on. Just does not make a lot of sense. There needs to be a way to continue to provide feedback when changes are made to an add-on. This is valuable info to see from others too.

**Comment by jvillalobos** [comment]
We're not doing this, for the reasons given by Kumar.
