### ISSUE TITLE
Please add a hidden string to the landing page for monitoring purpose

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#3757]
### Describe the problem and steps to reproduce it:
The old desktop site has a hidden string on the landing page for Ops to do site availability monitoring, for example https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/templates/addons/home.html#L33-L34 

### What happened?
The new mobile site doesn't have such a string. We're using "Firefox" for now.
### What did you expect to happen?
Can you add a hidden string on the landing page so we can use to monitor the site availability? Ideally, please put a note that says "not remove it" so it won't get removed by accident.

### Anything else we should know?
We have no preference what the hidden string is, as long as it's unique and not too long. :)

**Comment by willdurand** [comment]
@bqbn the comment is `<!-- Godzilla of browsers -->`

For QA, you should look at the homepage HTML and find `<!-- Godzilla of browsers -->` in it.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev FF56 (Win 10)

![image](https://user-images.githubusercontent.com/31961530/32782873-838e1f42-c952-11e7-9a9e-666dfc130d1d.png)
