### ISSUE TITLE
no longer compatible with (e.g. Diigo) highlighting, annotation …

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3758]
Hi, is CSP for the new look more 'heavyweight' than for the traditional?

Traditional and new looks: 

![2017-11-02 17 48 35 conex reviews add-ons for firefox](https://user-images.githubusercontent.com/192271/32342612-cb159826-bff8-11e7-8543-e64e4b654f04.png)

![2017-11-02 17 41 28](https://user-images.githubusercontent.com/192271/32342772-5f217738-bff9-11e7-9254-580d92a5ee7e.png)

----

Notes to self: 

- https://github.com/PhilGrayson/chrome-csp-disable/blob/master/background.js
- https://www.diigo.com/user/grahamperrin?query=%40addons.mozilla.org eighty-two bookmarks in the domain, twenty-six of which are annotated.

**Comment by tofumatt** [comment]
Yes. The CSP is very restrictive on the new site.

**Comment by grahamperrin** [comment]
OK, thanks. I have the user-agent string and other workarounds ☑️
