### ISSUE TITLE
Paginating through reviews should load new data more clearly

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3759]
### Describe the problem and steps to reproduce it:

* Go to an add-on detail page for an add-on with many reviews
* Click on *Read N reviews* to see the full list of reviews
* Scroll down and click the arrow to advance the page

### What happened?

The page scrolls to the top but shows the old reviews while it's loading. It happens pretty fast in this screencast but you will notice that there is no skeleton loading text at all.

![addons-frontend-review-scroll mov](https://user-images.githubusercontent.com/55398/32343978-40f1c4fa-bfd3-11e7-8b44-f7833705d2ce.gif)

### What did you expect to happen?

The page should scroll to the top but it should show the skeleton loading text while it's loading. This will make it more clear on slower connections/devices that the content is about to change.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF64, WIn10x64 and Android 8.0

Instead of showing the old reviews, the page now has loading indicators:

![2019-01-16_15-55-58](https://user-images.githubusercontent.com/31961530/51253653-9e71c600-19a7-11e9-985d-014371e3e196.gif)
