### ISSUE TITLE
Side-scrolling looks weird on Windows 10

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#3762]
Some Windows-related feedback I received today: There is a big thick scrollbar at the bottom of the screenshots area on a detail page, and it's there even if there is nothing to scroll.
![image](https://user-images.githubusercontent.com/6797635/32346868-2456560a-bfcc-11e7-8a85-1c6ff22d02f8.png)

Should we bring back the step-through buttons on screenshots?

**Comment by kumar303** [comment]
Looks the same on Mac too. Are you suggesting to remove the scrollbar and provide alternate navigation?

**Comment by ValentinaPC** [comment]
I think this is the same as https://github.com/mozilla/addons-frontend/issues/2965. Not sure. :)

**Comment by muffinresearch** [comment]
@kumar303 I think the distinction is the scrollbar is always present on windows.

**Comment by muffinresearch** [comment]
Dupe of #2965
