### ISSUE TITLE
Not all search filters are included in paginated links

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#3764]
### Describe the problem and steps to reproduce it:
1. Go to a search page with extra filters, like [`category=web-development&type=extension`](https://addons.mozilla.org/en-US/firefox/search/?category=web-development&type=extension).
2. Click **Next**.

### What happened?
You are now on page 2 of a search for `type=extension`.

### What did you expect to happen?
You are now on page 2 of a search for `category=web-development&type=extension`.

### Anything else we should know?
![search-link](https://user-images.githubusercontent.com/211578/32348621-58cf8954-bfe2-11e7-859f-9edeb8ba581a.jpg)

**Comment by kumar303** [comment]
Nice Firefox theme :)

I could reproduce it on Mac so I tried on Windows in Nightly 58.0a1 2017-11-01. I still couldn't reproduce it. What version were you using?

**Comment by kumar303** [comment]
Oh, sorry, ignore me. I *can* reproduce it on Mac and Windows. I misread the issue.

**Comment by mstriemer** [comment]
Screenshot is from https://twitter.com/prashantak/status/926181742620364800. You'll have to ask him about the theme if you're interested ;)
