### ISSUE TITLE
Add link to edit collection from collection view, when user has rights

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3766]
There's currently no way to go from viewing a collection to editing it. The only way to edit collections right now is to go to View My Collections from the dropdown and then choose to edit one from the list. This doesn't work for collections you don't own, which affects our theme reviewers, who edit the Featured Themes collection.

So, if a user has permission to edit a collection, there should be a link or button in the collection view leading to the edit page for that collection.

**Comment by eviljeff** [comment]
`Collections:Edit` is the permission (in addition to the user being the collection owner).  

@jvillalobos do the theme reviewers have that permission as part of a group, or are they collection contributors instead?  The latter is a problem currently - we don't expose them in the serializer output so frontend wouldn't know they have access.  (The API knows, just doesn't expose it)

**Comment by willdurand** [comment]
> Collections:Edit is the permission (in addition to the user being the collection owner).

@eviljeff just to be sure, does that mean any user with the `Collections:Edit` permission OR collection owner?

**Comment by eviljeff** [comment]
@willdurand OR.  Though there may be an extra `or` in there depending on the answer to the contributors question to Jorge.

**Comment by willdurand** [comment]
Thanks!

**Comment by jvillalobos** [comment]
> @jvillalobos do the theme reviewers have that permission as part of a group, or are they collection contributors instead?

They are collection contributors specifically for the Featured Themes collection.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
The "Edit this collection" link was added and is redirecting as expected.
Postfix screenshot:
![2017-11-13_1643](https://user-images.githubusercontent.com/15685960/32731317-26562a88-c892-11e7-9b3d-0524e51c6ed8.png)
