### ISSUE TITLE
'Version History' is superflous to the 'See all versions' link

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3768]
## First impresion …

> Version History
> See all versions

Where there's any history – any more than one version of an add-on: 

- you need not present the non-linked subheading (Version History) above the link to the history (of all versions). 

## Enhancement request

Be less verbose; save a little space. 

## Thoughts

The phrase _See all versions_ is relatively plain English. (To me, the phrase _Version history_ is fractionally more geeky.)

If the add-on has a beta/development/experimental channel then I'll expect _all versions_ to **truly** list all versions – including those that are experimental (notionally (without ploughing through repos of issues) two columns, with releases to the left). 

Notes to self: 

- whilst _beta_ is a good word, it's debatably not good when alphas are generalised in that way
- _experimental_, yeah, and the purple flask, that works for me. 

### Suggested priority

Low.

**Comment by grahamperrin** [comment]
## Second impressions

https://addons.mozilla.org/addon/ghostery/ debatably two superfluous subheadings :-)

**Comment by muffinresearch** [comment]
Here's a screenshot showing ghostery:

<img width="293" alt="ghostery_-_add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32367199-3aa2e592-c079-11e7-8fc2-6eaa27261a67.png">

**Comment by willdurand** [comment]
Maybe w could simplify by having a "History" title and the two links below..

**Comment by muffinresearch** [comment]
@willdurand yeah I think that might be a good way to go, less direct duplication that way.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win 10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/32440625-ad8092c8-c2fc-11e7-9e65-6d784dabbfeb.png)
