### ISSUE TITLE
Search form missing data-no-csrf attribute

### ISSUE THREAD

**Issue by psiinon** [mozilla/addons-frontend#3770]
### Describe the problem and steps to reproduce it:
The Search form included on most (all?) pages doesnt have an anti-csrf token (which is fine) and also doesnt have a 'data-no-csrf' attribute (which is not).
This means that the addons.mozilla.org and addons.allizom.org are now failing the baseline tests.

For more background see https://bugzilla.mozilla.org/show_bug.cgi?id=1328560

Is here a good place to add it? https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/SearchForm/index.js#L242-L251
If so I'm happy to submit a PR...

**Comment by tofumatt** [comment]
Yeah, that tag is the perfect place to add it. Just let me know when the PR is up and I'll review it 😄

**Comment by psiinon** [comment]
@tofumatt PR is #3772 :)

**Comment by psiinon** [comment]
patch updated - hopefully ok now...

**Comment by ValentinaPC** [comment]
@muffinresearch : could you please add some STR for us to check this or the label "qa: not needed".
Thanks!

**Comment by muffinresearch** [comment]
@psiinon can you confirm this looks good from the dashboard perspective.

**Comment by psiinon** [comment]
@muffinresearch Its fixed the issue with the search form, but I missed the fact that the review-edit-form and report-user-form on the user pages also dont have tokens or the data-no-csrf attribute, so the baseline is still failing. I'll look at raising PRs for those.
