### ISSUE TITLE
Developer name in header of listing page should be highlighted as a hyperlink

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3771]
Steps to reproduce:
1, Navigate to an add-on details page (i.e. https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/)
2. Go to More extensions by author section

Expected result:
Developer name is displayed as a hyperlink redirecting to the Developer profile

Actual result:
Developer name is displayed as plain text

Notes: Reproduces on all AMO servers with FF56 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/32377664-1488330c-c0b1-11e7-9e15-d83a7577851a.png)

**Comment by willdurand** [comment]
Hmm I don't think this is a feature we want here.

**Comment by jvillalobos** [comment]
Yeah, I don't think there should be an expectation for a link there. Linking the developer's name in the header is enough.

**Comment by AlexandraMoga** [comment]
> Linking the developer's name in the header is enough.

In that case, shouldn't the link be more emphasized (i.e. adding an underline)? Right now, the developer name looks too much like plain text:

![image](https://user-images.githubusercontent.com/31961530/32432281-9d7066a0-c2df-11e7-87fb-db258879efac.png)

**Comment by jvillalobos** [comment]
The main purpose of linking to the developer account is to see other add-ons created by that dev. It's not a primary use case, but people still do it. So maybe we should highlight the developer name more, like you suggest, or have a "See more" link on the "More extensions by X" box. @pwalm, what do you think?

**Comment by FlorianFranzen** [comment]
@jvillalobos I think a "see more", or similar link would be very favorable!

**Comment by pwalm** [comment]
The dev name in the header of the detail page should be hyperlinked/highlighted, and it should link to a page of all the add-ons the dev has created.

<img width="728" alt="screen shot 2017-11-16 at 3 55 35 pm" src="https://user-images.githubusercontent.com/6797635/32922352-9c05d912-cae6-11e7-80d4-b2708e4f4025.png">

**Comment by AlexandraMoga** [comment]
Based on the above comments, we should consider keeping this topic open.

**Comment by jvillalobos** [comment]
I changed the title to reflect what we're trying to do now. One nit about @pwalm's design: the "by" shouldn't be highlighted, since there could be a list of multiple authors after it.

**Comment by kumar303** [comment]
The description of this issue is about something we decided not to implement. Can you update it to match the change requested in https://github.com/mozilla/addons-frontend/issues/3771#issuecomment-342081979 or file a new issue for that?

**Comment by jvillalobos** [comment]
Filed a new one.
