### ISSUE TITLE
Avoid AMO l10n mess

### ISSUE THREAD

**Issue by StoyanDimitrov** [mozilla/addons-frontend#3774]
### Describe the problem and steps to reproduce it:
The l10n of the whole AMO project is divided in only two files. `djangojs.po` – 250+ strings and `django.po` – 2400+ strings. This is quite a large amount of strings in one place. Hopefully the AMO Frontend project is not that big at the moment but it is growing. I want to draw your attention to this issue. Please do not follow the path of AMO and separate the stings by topic or whatever it is convenient to you. I understand that you probably had automated the string extraction process but still consider separation in different files. It is important for localizers.

**Comment by muffinresearch** [comment]
@StoyanDimitrov Thanks for filing this. 

We'll need to think carefully about how any file splitting would work, it would be quite complicated to start extracting by different file so I think I'd really like to consider this fully before going down this route. 

So I understand the issue better, what are the precise problems when dealing with a large single file? Can you provide some more details on how this makes things difficult from a localizer's perspective?

**Comment by muffinresearch** [comment]
I think it's worth mentioning this issue is already a proposed discussion topic in the upcoming all-hands.

**Comment by StoyanDimitrov** [comment]
In l10n context is a king. A string with no context is untranslatable or at best low quality.
1. Having more granulated filenames/folders will give the localizer a higher level of context to the containing strings.
2. Although this will be fixed eventually – currently Pontoon has a problem navigating long lists of strings. Let's just say one can not easily reach certain group of strings (presumably related to each other) that are together in the list. I call it positional context.

**Comment by muffinresearch** [comment]
> Although this will be fixed eventually – currently Pontoon has a problem navigating long lists of strings. Let's just say one can not easily reach certain group of strings (presumably related to each other) that are together in the list. I call it positional context.

To me that sounds like a Pontoon bug. 

I'll keep this issue open for consideration but I think realistically it's likely to be relatively low priority compared to other things we are trying to do at the moment, splitting things up is likely to be a complex change.
