### ISSUE TITLE
Gzip-compress static assets (HTML, favicon, CSS)?

### ISSUE THREAD

**Issue by stephendonner** [mozilla/addons-frontend#3776]
**Update for QA (2019.07.16):** please make sure the `favicon` is still displayed in all envs.

---

According to https://webpagetest.org/performance_optimization.php?test=171103_BA_cfaf6b04d96bcc5ba50d34c420f4b7a2&run=4#compress_text, we don't Gzip-encode/compress the following:

1,010.1 KB total in compressible text, target size = 441.3 KB - potential savings = 568.9 KB

FAILED - (619.1 KB, compressed = 79.2 KB - savings of 539.9 KB) - https://addons-amo-dev-cdn.allizom.org/amo-e10c3688997f3544f58365d7dfab0c72.css
FAILED - (31.8 KB, compressed = 7.0 KB - savings of 24.8 KB) - https://addons-dev.allizom.org/en-US/firefox/addon/adobe-flash/
FAILED - (5.3 KB, compressed = 1.1 KB - savings of 4.2 KB) - https://addons-dev-cdn.allizom.org/favicon.ico?v=1

Looks like there might be an outstanding concern with the HTML assets due to CSRF leaking (https://github.com/mozilla/addons-server/issues/6636#issue-264291074) but filing for consideration.

**Comment by diox** [comment]
@kumar303 where do we stand regarding the API token presence in the HTML? That'll determine whether or not we can safely enable gzip for HTML (which would result in huge savings...).

In any case .css should be gzipped...

**Comment by kumar303** [comment]
> API token presence in the HTML?

When signed in, the API token is indeed part of the HTML. It contains a script tag with the id `redux-store-state` which includes `api.token` in the JSON.

> In any case .css should be gzipped...

Maybe that was just a dev issue? It appears gzipped in prod unless I'm missing something.

<img width="1624" alt="screenshot 2017-11-08 12 11 43" src="https://user-images.githubusercontent.com/55398/32566649-2f70bb6e-c47e-11e7-9283-672cc2c4754b.png">

**Comment by muffinresearch** [comment]
@bqbn could we get gzip turned on for the favicons. CSS is already gzipped and we can't do gzip for HTML as yet.

**Comment by muffinresearch** [comment]
@bqbn any idea when turning this on for favicons might be possible?

**Comment by bqbn** [comment]
I haven't had time to look at this one before. I'll say next week, if that works.

**Comment by willdurand** [comment]
@bqbn can we have that?

**Comment by bqbn** [comment]
The config for gzipping favicon.ico is deployed to -dev and -stage. Please test.

You may need to clear your browser caches before verifying it.

It works for curl at this point.

```
$ curl -I -H "accept-encoding: gzip, deflate, br" https://addons-stage-cdn.allizom.org/favicon.ico
HTTP/1.1 200 OK
Content-Type: image/vnd.microsoft.icon
Connection: keep-alive
Cache-Control: max-age=315360000
Cache-Control: immutable
Content-Encoding: gzip
Date: Thu, 11 Jul 2019 21:56:49 GMT
ETag: W/"3cec07462a3d8e6ba2b472d204fa1f30"
Expires: Sun, 08 Jul 2029 21:56:49 GMT
Last-Modified: Thu, 11 Jul 2019 16:14:58 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Encoding
X-Cache: Miss from cloudfront
Via: 1.1 4dde8ec6d6c12741888c2d3a059d4a2f.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: HIO50-C1
X-Amz-Cf-Id: Wc2FPh05NRIRbG9NfROioYVRF4_hVK-6qZBdBcp7sLKAtynDZIV3dQ==
```

**Comment by willdurand** [comment]
@bqbn it works for me in both -dev and -stage.

**Comment by bqbn** [comment]
Deployed to -prod as well.

**Comment by vcarciu** [comment]
Favicon displayed in all envs. Marking the issue as verified.
