### ISSUE TITLE
en dash – in lieu of hyphen - in HTML titles of pages

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3781]
Noted with thanks: 

- reduced use of `::`
- increased use of `-` (in, for example, the title of <https://addons.mozilla.org/en-GB/firefox/addon/tab-tally/>). 

## Enhancement request

As a subtle improvement, please consider using an en dash

`–`

– in lieu of the hyphen. 

----

> U+2013
> Name: EN DASH
> General Character Properties
> Block: General Punctuation
> Unicode category: Punctuation, Dash
> Various Useful Representations
> UTF-8: 0xE2 0x80 0x93
> UTF-16: 0x2013
> C octal escaped UTF-8: \342\200\223
> XML decimal entity: `&#8211;`

----

Guys and gals from the States might prefer an em dash but I have a British <strike>stiff </strike>wobbly upper lip pweference for the en dash in this situation. Tomato, tomato, potato, potato, let's call the whole thing off, rabbits, wabbits etc., https://english.stackexchange.com/a/2126/11504 and thereabouts.

**Comment by muffinresearch** [comment]
@grahamperrin Thanks for the bug report, this will be going out this week.

**Comment by ValentinaPC** [comment]
@muffinresearch : not sure where to check the replacement, could you give me a hand?
Thanks!

**Comment by willdurand** [comment]
> not sure where to check the replacement, could you give me a hand?
> Thanks!

@ValentinaPC you can look at the HTML titles in your tabs. It should display a slightly different separator in -dev. For instance, on a category page, on a search results page, on an add-on detail page.

**Comment by ValentinaPC** [comment]
@willdurand : that was the place where I looked....but everything looks the same in all AMO servers.
![dev](https://user-images.githubusercontent.com/15685960/32444411-34856240-c30b-11e7-9997-0a54d409c861.png)
![prod](https://user-images.githubusercontent.com/15685960/32444412-34aa0b18-c30b-11e7-9aba-fa5a01c23fde.png)
![stage](https://user-images.githubusercontent.com/15685960/32444414-34ca6c3c-c30b-11e7-9947-8fd1060f5ece.png)

I am using FF56 and Win 7, you?

**Comment by muffinresearch** [comment]
This is what I see - an en dash is wider than a hyphen:

## Dev en dash

<img width="461" src="https://user-images.githubusercontent.com/1514/32494129-616dbdb8-c3b8-11e7-9563-1ce052d4a305.png">

## Prod hyphen

<img width="430" src="https://user-images.githubusercontent.com/1514/32494262-db9b0654-c3b8-11e7-96c3-8dd3c33cd8d2.png">

**Comment by ValentinaPC** [comment]
Ooooh :)
Still, seems like when I checked the issue, yesterday, there was no dash in -dev....was a hyphen everywhere.

Things changed today and I can see a dash in dev, also.
Postfix screenshots:
![2017-11-07_1447](https://user-images.githubusercontent.com/15685960/32494519-9b0eaa48-c3ca-11e7-928e-4a30a4d9f838.png)
