### ISSUE TITLE
Show Creation/Update Date when sorting by date-related property

### ISSUE THREAD

**Issue by siffegh** [mozilla/addons-frontend#3783]
Please add date added or updated to the search results page as in the 'old' version.

I search for new and updated addons daily, so without these dates being initially visible I'd have to keep opening the results to see them.

![image](https://user-images.githubusercontent.com/18728013/32409582-ed6212be-c184-11e7-9339-a61ccde8ab11.png)

tx,

Ed

**Comment by tofumatt** [comment]
The search results page at https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=test on both the old/"Classic desktop site" and the new front-end site don't show a "last updated"/"added on" field. I'm not sure what URL these results appear on in the old site–if you could let us know what URL on the old site shows this info please do and we can look at this issue further.

That said this data isn't in our new mocks and I don't think it's worth highlighting in the search results.

**Comment by siffegh** [comment]
The dates appear on the classic site when you choose either 'Newest' or 'Recently Updated'.  On the new site, there is a Filtering option for 'Recently Updated' so I don't understand "this data isn't in our new mocks".
![image](https://user-images.githubusercontent.com/18728013/32410517-6673cebe-c198-11e7-9a69-c58a900be378.png)

**Comment by tofumatt** [comment]
Ah, okay. So they appear contextually only for that search option. The mocks we had from UX didn’t ever include that data but I see how showing it when sorting by a date property would be useful. Thanks for the clarification, that helps!

- Matt (Sent from mobile)

**Comment by siffegh** [comment]
YW :-)

**Comment by siffegh** [comment]
So is this issue not going to be considered?

**Comment by tofumatt** [comment]
I didn't originally understand the issue and then replied via email and forgot to re-open it after I understood the context better, sorry about that!

I think it's worth exploring actually, so thanks for commenting on the issue again 😄

**Comment by siffegh** [comment]
Cool, thanks!

⁣Sent from BlueMail ​

**Comment by grahamperrin** [comment]
@tofumatt thanks, I missed this one when searching 'cause it didn't have the keyword _list_ ;-)

**Comment by grahamperrin** [comment]
https://addons.mozilla.org/firefox/search/?sort=created&type=extension https://addons.mozilla.org/firefox/search/?sort=created&type=extension&page=2 etc..

[2017-11-08 20:16.ogv.zip](https://github.com/mozilla/addons-frontend/files/1455290/2017-11-08.20.16.ogv.zip)

![sort created classic presents dates](https://user-images.githubusercontent.com/192271/32572051-5437556e-c4c1-11e7-96da-aa97aa54462e.png)

Side note: no horizontal scroll bar.

**Comment by bobsilverberg** [comment]
I have taken a first stab at this and am submitting a PR. For now I have simply added the Last Updated date, in a format that is consistent with the **More Information** section, immediately after the author information. This is likely not ideal, so some feedback from UX, @pwalm, on exactly how this should look would be appreciated, please and thank you. 

Note that the Last Updated information will only appear with a search result if the search performed used "Recently Updated" as a sort order.

I am attaching a screenshot of the current version:

<img width="858" alt="screenshot 2018-02-12 16 47 38" src="https://user-images.githubusercontent.com/142755/36121673-e78eb5b6-1014-11e8-9f5b-d15874b456c7.png">

**Comment by kumar303** [comment]
Hi @siffegh , thanks for raising an issue about this. I have a question about...

> I search for new and updated addons daily, so without these dates being initially visible I'd have to keep opening the results to see them.

Why would you like to see the dates? What will it help you accomplish? The results are already sorted from newest to oldest.

**Comment by tofumatt** [comment]
To me the rationale for showing a "last updated" date is to show the up-to-date-ness of software. I think it actually isn't the use-case for the person who originally filed the issue but I check App Store release dates and GitHub last commit dates to see if software has been recently updated... something that's four years old might not work great anymore.

That said we show that info on the detail page (the only place installs take place anyway on the new site) so I actually think this could be scrapped.

**Comment by kumar303** [comment]
> That said we show that info on the detail page ... so I actually think this could be scrapped.

Well, @siffegh mentioned that this is inconvenient because he has to click through to each detail page. I'd like to learn more about why. @tofumatt your use case about wanting to know how old the extension is seems like it's covered by the detail page.

**Comment by jvillalobos** [comment]
I think Last Updated made lots of sense as a primary UI feature back when legacy add-ons were around. Something that was 1+ year was bound to be broken somehow. This shouldn't be the case for WebExtensions add-ons, at least not that much, and it's certainly not relevant for themes. I also looked at search pages for the App Store and the Chrome Web Store, and neither show the update date on their search results.

I'm inclined to close this, since it adds noise to search results and the value seems very limited. Similar to https://github.com/mozilla/addons-frontend/issues/3813, people who need more specific uses of AMO data can use the API to create tools that better suit them.

**Comment by siffegh** [comment]
Hi. I've been accessing new/updated addons by using https://addons.mozilla.org/en-US/firefox/search/?platform=windows&sort=updated&type=extension, so having the date on the search results is really not necessary for me any more. But using that URL is; I don't see any way to get a listing of all new and updated addons from the main AMO page. Maybe I'm missing something?

**Comment by kumar303** [comment]
Thanks for everyone's input. I'm closing this based on the last two comments.

> I don't see any way to get a listing of all new and updated addons from the main AMO page.

Why do you need to get the same listing on the main AMO page if you can already use the search page?
