### ISSUE TITLE
Name of add-on should be in same line as logo

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-frontend#3789]
<img width="807" alt="bildschirmfoto 2017-11-05 um 08 29 25" src="https://user-images.githubusercontent.com/1100614/32412808-76e5ad06-c203-11e7-9b7e-ecb30b68ce4f.png">

This looks not great and is a waste of space. The name of the add-on and of the developer should be on the right of the logo. It would also be consistent with the reviews view:

<img width="418" alt="bildschirmfoto 2017-11-05 um 07 28 29" src="https://user-images.githubusercontent.com/1100614/32412811-9e3bc6d8-c203-11e7-8c78-9dd02d9b0fe3.png">

**Comment by tofumatt** [comment]
This is an intended part of the new design of the detail page and the white space is intentional. There were badges to the right originally but we may, in the future, use it for other content.
