### ISSUE TITLE
Consider implications of adding a radius to extension logos.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3793]
Latest mocks of the reviews section show border radiused icons. This causing some icons to be cropped if they are square. 

Not sure if the intent in the mock was to represent a generic icon or if it was direction to add border radius to icons? If the latter we should re-consider since this does mean that extension icons are being cropped and we don't have an easy way to ensure this doesn't happen. 

<img width="380" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/32438710-6bcef194-c2e3-11e7-9485-56cf129ebe29.png">

**Comment by pwalm** [comment]
Not a crop, that was just a placeholder for the icon. Place the icon as you normally would.

**Comment by tofumatt** [comment]
Issue is fixed and we shouldn't do the corner crop so seems like this can be closed 😄
