### ISSUE TITLE
Collections include deleted add-ons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3795]
See https://addons.mozilla.org/en-US/firefox/collections/mozilla/featured-personas/ for an example.

This will be resolved by https://github.com/mozilla/addons-server/issues/6845

<img width="1323" alt="featured_themes_-_add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32444564-10af7604-c2fb-11e7-85c5-6ca875118557.png">

**Comment by eviljeff** [comment]
Fixed in the API
