### ISSUE TITLE
Fix links to Firefox marketing/download on new AMO pages

### ISSUE THREAD

**Issue by hoosteeno** [mozilla/addons-frontend#3803]
### Describe the problem and steps to reproduce it:

1. Go here (or really to any addon page) *in Chrome*: https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/
2. Hover over the green "Download Firefox" button in the header -- the link is https://mozilla.org/firefox/
3. Hover over the red "download Firefox" message in the page -- the link is https://www.mozilla.org/en-US/firefox/
4. Hover over the "Download Firefox" link in the footer -- the link is https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_campaign=footer&utm_medium=referral

### What happened?

The footer link is correct. Other links are incorrect because...
1. Links shouldn't have l10n on them (we should let the destination site handle l10n routing)
2. Links should have link-specific UTM parameters on them
3. "Download Firefox" links should point at the download page at /firefox/new. 

### What needs to happen?

We should replace the **green header link** with this:

https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=header-download-button

We should replace the **red in-page link** with this:

https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=install-addon-button

**Comment by hoosteeno** [comment]
The steps above address several problems that we see when links aren't perfect:
* Without UTM parameters, we can't attribute Firefox downloads to AMO -- in the 3 days since launch, **AMO's share of Firefox downloads went down 90%**, simply because they're no longer attributable.
* When links include l10n or don't point at the right destination, the *incredible SEO value* of a link from AMO is lost.

**Comment by vcarciu** [comment]
Verified as fixed : 
![chromemozilla](https://user-images.githubusercontent.com/1583842/32494608-f7521268-c3ca-11e7-94d9-ec17339b8bb1.gif)
