### ISSUE TITLE
[TAAR] Pass locale/platform to the TAAR-api when opening the Discopane

### ISSUE THREAD

**Issue by Dexterp37** [mozilla/addons-frontend#3804]
This is a feature request for the [TAAR project](https://github.com/mozilla/taar/). When Firefox opens the Discopane, it sends along some bit of information (locale, platform, ...). 

We would love this informations to be propagated to the TAAR api to make use of it if some user requesting recommendations is not in our database.

I will file a similar issue in mozilla/addons-server.

**Comment by muffinresearch** [comment]
Needs be ready by November 30th.

**Comment by muffinresearch** [comment]
This will be a case of getting the locale and platform from the discopane URL and passing it along via the API .

```
https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%```

So that will likely be the `%LOCALE%` and `%OS%` parts see http://addons-server.readthedocs.io/en/latest/topics/api/discovery.html#discovery-recommendations for the API docs.
