### ISSUE TITLE
Firefox Add-ons logo is not RTL

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3812]
Steps to reproduce:
1. Load AMO-dev homepage using a RTL language i.e. https://addons-dev.allizom.org/ar/firefox/
2. Observe Firefox logo

Expected results:
Logo is RTL.

Actual results:
Logo is not RTL.

Notes/Issues:
Verified on AMO-dev FF56(Win 7)
Screenshot for this issue:
![2017-11-06_1655](https://user-images.githubusercontent.com/15685960/32481161-d135eb52-c39a-11e7-8e28-fbdd6e3af4a2.png)

**Comment by willdurand** [comment]
I noticed that too but it is a brand. I dont think Youtube or other Mozilla change their logo (I checked these examples), so not sure if we should change anything.

**Comment by ValentinaPC** [comment]
I did not check Youtube, but the old logo, that was RTL.
![2017-11-07_0913](https://user-images.githubusercontent.com/15685960/32481456-16d870de-c39c-11e7-9d19-041d3be2d3e6.png)

**Comment by willdurand** [comment]
The logo contains the text now and won't be translated.

**Comment by ValentinaPC** [comment]
Then, your choice. :)

**Comment by muffinresearch** [comment]
Yep since it's a brand and the logo is in LTR I don't think there's any action to take here.
