### ISSUE TITLE
sort add-ons by newest add-ons

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-frontend#3813]
In the new design in the search results the option is missing to sort the add-ons by the newest. It seems to be still possible with the URL parameter sort=created but it should be added to the dropdown. I think it's a very nice option to discover new add-ons. There was also already a request in the German speaking Firefox forum where this option in the new design is.

It's maybe related to #3252 but I opened a separate ticket because the other ticket has the focus on the option to sort by name and this is a different use case (and so maybe there will be a different decision).

**Comment by grahamperrin** [comment]
#3252 has "and other sort options" in its title. 

@tofumatt would you like a separate issue for each possible type of sort? Please advise – thanks.

**Comment by decembre** [comment]
Good idea, and the date of creation / update should be always visible (near the addon name) in all places where the addons are visible (search / listing / addon infos pages etc.. ).
It's not a trivial infos.

**Comment by cadeyrn** [comment]
This issue did never got an label, but most other issues. Was it overlooked? ;-)

**Comment by muffinresearch** [comment]
Docs are here: http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#search

**Comment by davidhedlund** [comment]
This should be fixed to make it possible for people keep their add-on collections up to date.

**Comment by jvillalobos** [comment]
Here's why I don't think we should do this:
* We have a sort option for last updated, which is very close to "newest" (almost redundant). Having both of them seems excessive and noisy.
* We should choose our sort options carefully, since there's limited UI space, particularly on mobile.
* Most people asking to bring back "newest" are very active community members who are constantly looking at the latest add-ons for things they are interested in. If going through "last updated" is too much, we also have the API available (see comment above). It shouldn't be hard to create an extension or app that consumes that API and shows a nice feed of the latest add-ons. I don't think we need this to be an AMO feature.

**Comment by tofumatt** [comment]
Sounds like this is not a feature that should be surfaced in the UI of the site. As @jvillalobos mentioned: it's a good candidate for a community-supported feature using the API, and as @cadeyrn mentioned it is possible to produce even on the site by changing the URL for the users who really desire the feature.

Given the limited space for UI we have and our aim to reduce complexity, I'm gonna close this one.

**Comment by davidhedlund** [comment]
> We have a sort option for last updated, which is very close to "newest" (almost redundant). Having both of them seems excessive and noisy.

This is not the same thing as to sort add-ons by the date of their first version, right?

**Comment by davidhedlund** [comment]
@tofumatt @jvadillo 

> We have a sort option for last updated, which is very close to "newest" (almost redundant). Having both of them seems excessive and noisy.

This is not the same thing as to sort add-ons by the date of their first version, right?

**Comment by jvillalobos** [comment]
"Last updated" sorts add-ons by the date the last version was uploaded, IIRC. This means you get a mix of the newest add-ons and the add-ons that had new versions recently uploaded.

**Comment by grahamperrin** [comment]
Thumbs-down for the loss of functionality in the absence of an extension. Hey-ho.

**Comment by jvillalobos** [comment]
Here's my little Friday afternoon project: https://addons.mozilla.org/addon/latest-on-amo/

[Issues](https://github.com/jvillalobos/latest-on-amo/issues) and patches welcome.

**Comment by davidhedlund** [comment]
@jvillalobos I didn't mean the latest version release, I meant that I want to be able to sort add-ons by the release date of the first version. Example for the three most popular extensions would look like this:
* uBlock Origin: 2015-07-02 (see https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/)
* Video DownloadHelper: 2006-12-12 (see https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/versions/)
* Adblock Plus: 2006-01-17 (see https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/versions/)

**Comment by davidhedlund** [comment]
Shouldn't this issue be re-opened base on my [previous comment](https://github.com/mozilla/addons-frontend/issues/3813#issuecomment-360931830)?

**Comment by cadeyrn** [comment]
In my opinion as opener of this issue, yes, it should be reopened. But it's not my decision…

> We have a sort option for last updated, which is very close to "newest" (almost redundant). 

That's not true at all, it's a very different use case…

> Having both of them seems excessive and noisy

Having updated but old add-ons if you're interested in new add-ons, that's noisy.

> We should choose our sort options carefully, since there's limited UI space, particularly on mobile.

On desktop AND mobile it's in a dropdown with only a few items. There is really no space issue.

> Most people asking to bring back "newest" are very active community members who are constantly looking at the latest add-ons for things they are interested in

I can't confirm that. I have a few Mozilla related projects like my not that small blog and I am also the administrator of the German speaking support Forum of Firefox so German speaking people often ask me or in one of my projects. There were more requests for this feature from simple users which are no active community members. These are users interested in the newest add-ons, they want discover new add-ons. I don't see how this use case should correlate with community engangement.

**Comment by davidhedlund** [comment]
Search Tools can be sorted by [Created](https://addons.mozilla.org/en-US/firefox/search-tools/?sort=created). But not add-ons.

**Comment by grahamperrin** [comment]
> … more requests for this feature from simple users … interested in the newest add-ons, they want discover new add-ons. …

@cadeyrn you probably figured this out long ago but for convenience: 

* https://addons.mozilla.org/search/?type=extension&page_size=100&sort=created
* https://addons.mozilla.org/search/?type=extension&page_size=100&sort=created&recommended=true

For me the redirects are to `en-GB` pages, your community will probably gain `de` pages. 

Where `sort=created` is forced, a minor UI issue arises: 

> Sortieren nach ▶ Relevanz

– appears to be pre-selected and will **not** perform the sort, when required. 

It becomes necessary to select a different sort order, then (again) select *Relevanz*

HTH
