### ISSUE TITLE
Category isn't kept when visiting page 2

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-frontend#3818]
STR:
* Visit any page with a category filter on, e.g https://addons.mozilla.org/en-US/firefox/search/?category=privacy-security&sort=rating&type=extension or https://addons.mozilla.org/en-US/firefox/search/?category=bookmarks&sort=rating&type=extension
* Click on "Next" (Page)
* See that the category filter is gone now

Looks like either a regression or a serious bug.

**Comment by muffinresearch** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/3764

**Comment by willdurand** [comment]
This should be fixed in -dev, could you please test? I think it has been fixed by #3765.

**Comment by EnTeQuAk** [comment]
Yes, it's working fine on -dev. I didn't test that first, sorry about that!
