### ISSUE TITLE
"Last updated" section of a detail page changes to another language at page refresh

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#3819]
Similar to https://github.com/mozilla/addons-frontend/issues/3443 but with an add-on detail page.

STR:
- `curl -s https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/` 10 times

Expected Result:
- The page is always the same, fully in english

Actual Result:
- The "Last Updated" section is sometimes in a different language. For instance I just saw `<dt class="AddonMoreInfo-last-updated-title" data-reactid="193">Last updated</dt><dd data-reactid="194">21 小時前 (2017年11月6日)</dd>`.

Happening on prod and stage at least.

**Comment by muffinresearch** [comment]
I can reproduce the STR.

**Comment by willdurand** [comment]
FTR, here is the 10 times example:

``` bash
$ repeat 10 curl https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/ -s | grep --color -oE 'Last updated</dt><dd data-reactid=\"\d+\">.+?</dd>'
Last updated</dt><dd data-reactid="194">il y a 2 jours (6 nov. 2017)</dd>
Last updated</dt><dd data-reactid="194">2 days ago (Nov 6, 2017)</dd>
Last updated</dt><dd data-reactid="194">2 days ago (Nov 6, 2017)</dd>
Last updated</dt><dd data-reactid="194">2 hari yang lalu (6 Nov 2017)</dd>
Last updated</dt><dd data-reactid="194">2 days ago (Nov 6, 2017)</dd>
Last updated</dt><dd data-reactid="194">2 days ago (6 Nov 2017)</dd>
Last updated</dt><dd data-reactid="194">2 dias atrás (6 de nov de 2017)</dd>
Last updated</dt><dd data-reactid="194">2 days ago (Nov 6, 2017)</dd>
Last updated</dt><dd data-reactid="194">2 天前 (2017年11月6日)</dd>
Last updated</dt><dd data-reactid="194">2 days ago (Nov 6, 2017)</dd>
```

**Comment by kumar303** [comment]
This explains the root cause of the bug https://github.com/mozilla/addons-frontend/issues/3538

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win 10)

![autorefresh](https://user-images.githubusercontent.com/31961530/32719896-8da4d748-c86a-11e7-8e04-66582ccd2ee7.gif)
