### ISSUE TITLE
"View classic destktop site" is not correctly opened in a new tab

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3820]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/
2.Right click on "View classic desktop site" from footer of the page and open it in a new tab

Expected results:
Old view is opened in a new tab
https://addons-dev.allizom.org/en-US/firefox/#desktop is opened in a new tab, but the new frontend is still displayed

NOTES:
Reproducible on all servers
Tested with Windows 10x64, FF Release

Please see video of this bug : 
![newtab](https://user-images.githubusercontent.com/1583842/32499709-01625b12-c3dc-11e7-8c91-57d7599d59a9.gif)

**Comment by tofumatt** [comment]
This is working as expected because this link runs JS code and switches the site. Making it work in a new link would be a bit of a hack and also not worth doing as the old site will eventually go away.
