### ISSUE TITLE
Remove workarounds for determining add-on compatibility

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3824]
Now that compatibility responses have been fixed in the API (https://github.com/mozilla/addons-server/issues/6781) we can rely on them.

For QA, please help test for compatibility related regressions. Here are some ideas of what to test:

* On AMO, go to the detail page for a {theme, dictionary, search plugin} and make sure it is installable
* On Discopane, make sure all install switches still work for themes

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF58(Win 7).
1. Disco Pane set to point -dev:
- all themes and extensions can be installed

2. AMO
- tried to install different lang packs, dictionaries, search tools. static themes or normal extensions and seem to be working as expected **almost** for all categories;
- here are a few examples of extensions that return a corrupt message - could not figure it out why:
a) https://addons-dev.allizom.org/en-US/firefox/addon/love-o-clock/
b) https://addons-dev.allizom.org/en-US/firefox/addon/readlang-dev/
c) https://addons-dev.allizom.org/en-US/firefox/addon/bookmark-manager123/
d) https://addons-dev.allizom.org/en-US/firefox/addon/web-timer/

**Comment by kumar303** [comment]
The corrupt file messages look like problems just with our development server. I see this in the Browser Console:

Download of `https://addons-dev-cdn.allizom.org/user-media/addons/491802/love_oclock-1.0.7-an+fx.xpi?filehash=sha256%3Af6e106403e4d9af4396b351f470ff9fd5486096463f35a50fa1dcc2eb6a669c0` failed: Error: Webextension is signed with an invalid id (696f2b35-a3ad-4f12-9514-80c7c8456dd0)
