### ISSUE TITLE
Using 'yarn amo', the homepage does not load correctly.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#3826]
The different sections on the home page, i.e.: "Most Popular Extensions" does not show any extensions when viewing it from the homepage.

The URL request at ```http://olympia.dev/api/v3/addons/search/?app=firefox&appversion=58.0&page_size=4&sort=hotness&type=extension&lang=en-US``` returns a 200 however the loading text never goes away.

It would be nice to make sure these sections work as they are a part of the integration tests.

**Comment by tofumatt** [comment]
This is likely because there is no data being returned by these requests on a new docker instance; our code should be smarter and catch it but it likely is assuming an empty result set means still loading (as this never happens in production) 😢

**Comment by jrbenny35** [comment]
@tofumatt how could I get it to work?

**Comment by tofumatt** [comment]
You'd need to add the data to what gets populated by `make initialize_docker` in `addons-server`... I'm not sure how the data population works and my understanding is it's generally quite lacking–especially in a post-extensions world.

You could manually add it via the admin interface or with the seed data task that's buried somewhere in `make initialize_docker` but that's about all I'd know off the top of my head without digging into the code, so it might require some digging 😞

**Comment by jrbenny35** [comment]
@tofumatt I have run ```make initiailze_docker``` as well as ```make populate_data```. The addons appear if I search for them but just the home page shows the continuous loading text within the sections even though the server shows a 200, or a 304.

**Comment by tofumatt** [comment]
Right, but there probably aren’t any addons set to be in the featured extensions. The response is a 200 but what’s in it? Are there any addons?

**Comment by jrbenny35** [comment]
@tofumatt ohhh....great point. I didn't even think of that.

**Comment by jrbenny35** [comment]
It looks as if the same URL enpoints load correctly when view from the ```/extensions/``` URL. 

On the homepage I get this error: ```Home add-ons failed to load: Error: Error calling: /api/v3/accounts/account/mozilla/collections/change-up-your-tabs/addons/ (status: 404)```. I wonder if the react ```render() return {}``` fails since I do not have this extension created.

**Comment by jrbenny35** [comment]
Per irc:
```willdurand: what's the endpoint being called on the homepage?
14:37 b4hand:  /api/v3/accounts/account/mozilla/collections/change-up-your-tabs/addons/
14:37 b4hand: which doesn't exist and I get an error
14:37 b4hand: but the featured extensions, or tending extensions sections never show their addons.
14:39 willdurand: aaaah right
14:40 willdurand: this collection must exist for now
14:42 b4hand: willdurand: so looks like its a bug. If an endpoint doesn't exist the page fails to load. 14:43 willdurand: b4hand: yes and no. this collection is part of the editorial content and cannot *not* exist
14:44 willdurand: so yes, we should better handle this but it is low priority given that this collection is hardcoded anyway
```

**Comment by kumar303** [comment]
We would need something in [`populate_data`](https://github.com/mozilla/addons-server/blob/06206ba81e6b27f9b74e1402eb85ac128bf238ad/Makefile-docker#L80) like `python manage.py generate_homepage_collections` but that command doesn't exist so it also would need to be created.

I suggest filing an issue in `addons-server` asking for a command to generate/populate the home page collections (for starters).

**Comment by jrbenny35** [comment]
@kumar303 Well the thing is, the user 'mozilla' has a unique ```user_id``` that I can't create, or can't be created it seems. I have tried creating the 2 collections and it seems that, even though the collections are correct, the user is not. 

According to this: https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#account

**Comment by jrbenny35** [comment]
Actually, I got this figured out. Looks like I wasn't assigning a user to the generated collection.
