### ISSUE TITLE
Admins cannot reply to reviews

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3829]
### Describe the problem and steps to reproduce it:

* Sign in as an admin
* Go to the detail page for an add-on you are not an author of
* Click *Read N reviews*

### What happened?

You do not see a *reply* link to any review

### What did you expect to happen?

You should be able to reply to reviews

### Anything else we should know?

The old site allowed admins to do this: https://github.com/mozilla/addons-server/blob/c0d8e97cb7251d0702c0b8b4c18a5e9d9127680a/src/olympia/reviews/templates/reviews/review.html#L74

**Comment by vcarciu** [comment]
Admin reply available and functional. Please note that admin replies are displayed as "developer response", but I can see same behavior on the old site. We can mark this as verified and open another issue if we want to change "developer response" display issue : 
![adminreply](https://user-images.githubusercontent.com/1583842/32842515-f40d9490-ca25-11e7-8b09-618be6163a19.png)
