### ISSUE TITLE
the 'More extensions by …' card should show a red alert wherever an add-on will be incompatible with Firefox Quantum

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3830]
## Issue

For users of ESR 52.x and 56.x, in some cases the card shows a mixture of legacy and non-legacy add-ons: 

- with **no hint of incompatibility** with Firefox Quantum. 

### Example

![2017-11-07 02 24 31 56 0 2 user-agent switcher sdk - add-ons for firefox](https://user-images.githubusercontent.com/192271/32474403-4d6bffae-c364-11e7-98a1-8c6588122d72.png)

Image source: https://addons.mozilla.org/addon/user-agent-switcher-firefox/ viewed with 56.0.2 on FreeBSD-CURRENT.

## Enhancement request

Show an alert. Currently used in other situations: 

- a red 'no entry' icon. 

Show the alert – that small icon – without requiring the user to point or hover.  

If the add-on will require a restart: no need to _also_ show the yellow alert – an overarching single red alert should suffice.

### Suggested milestone

- 2017-11-23
- https://github.com/mozilla/addons-frontend/milestone/80

### Related

["More extensions by author_name" section has layout issues · Issue #3404 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/3404)

- not yet milestoned (and I don't imagine any urgency). 

## Background

From <https://github.com/mozilla/addons-frontend/pull/3807#issuecomment-342271723> (2017-11-06) under _**Not compatible with Firefox Quantum** by willdurand · Pull Request …_: 

> … It'll be nice to also have the icon **in listings** e.g. as shown in the shots at https://github.com/mozilla/addons-frontend/issues/3780#issuecomment-342248970

A little later: 

> I'm in two minds about that. One mind: 
> 
> - discourage unnecessary clicks.
> 
> Second mind: 
> 
> - serendipitous discovery of '**More extensions by …**' the same developer
> 
> – and the more can be a **very** good thing, and 👍 it is already disclosed (without a _Show more_ click) in the primary page for an add-on. 
> 
> ----
> 
> Unless I'm missing something (I'm speeding through screenshots, not code), we do not yet have: 
> 
> - the **no entry** icon (_Not compatible with Firefox Quantum_) in the **More extensions by …** area: 
> 
> …

**Comment by jvillalobos** [comment]
I don't think we should be showing the "not compatible" messaging beyond the listing pages. In a couple of weeks most users will either be using Quantum (in which case they will only see Quantum-compatible add-ons on AMO) or ESR (in which case they will probably stick with ESR for the next ~8 months). This clutters the UI and gives little benefit to users, who can click through and see the warning in the listing page anyway.
