### ISSUE TITLE
UX: list view: maybe show a red alert (alone) wherever an add-on will be incompatible with Firefox Quantum

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#3831]
## Enhancement request

I'm in two minds about this, but here goes. For users of ESR 52.x and 56.x: 

- wherever there will be incompatibility with Firefox Quantum, show a single red alert e.g. the no entry icon. 

In the context of **lists**, I reckon that it should suffice to simply **show the _no entry_ icon – without making it clickable**. 

If the user _really_ wants to know what's meant by the **no** entry icon, they can **enter** :-) the page for the add-on, and then see what's meant. In these cases the no entry icon will mean: 

> Not compatible with Firefox Quantum

No need to also show a yellow (restart) alert in listings. 

### Multiple meanings

Elsewhere there's an alternative meaning of the red no entry icon. Thoughts: 

- I do not imagine confusion in the context of the page for an add-on
- I _can_ imagine confusion in the context of a list – "Does _no entry_ mean incompatible with my platform? Or does _no entry_ mean incompatible with Mozilla's Firefox Quantum?" – the user may find the answer to those questions by proceeding to view the page for the add-on (expect to see red alerts, where appropriate, on or after Thursday of this week) so this is probably not a concern. 

## Background

From <https://github.com/mozilla/addons-frontend/pull/3807#issuecomment-342271723> (2017-11-06): 

> … It'll be nice to also have the icon in listings e.g. as shown in the shots at https://github.com/mozilla/addons-frontend/issues/3780#issuecomment-342248970

<https://github.com/mozilla/addons-frontend/pull/3807#issuecomment-342415872> from @willdurand: 

> I think the list view needs more UX input and therefore might be updated later. … you should open another issue to ask for a visual hint on the add-on lists.

👍 

### Vaguely overlapping

[the 'More extensions by …' card should show a red alert wherever an add-on will be incompatible with Firefox Quantum · Issue #3830 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/3830)

**Comment by jvillalobos** [comment]
I don't think we should do this, for the same reasons I mentioned in https://github.com/mozilla/addons-frontend/issues/3830#issuecomment-342839301

**Comment by grahamperrin** [comment]
> …  clutters the UI 

![not-compatible-min](https://user-images.githubusercontent.com/192271/32977408-adc902e8-cc24-11e7-84ba-64b935e72f85.png)

I enjoy non-cluttered UIs, but is there not room for that?

> and gives little benefit to users, who can click through and see the warning in the listing page anyway.

https://www.youtube.com/watch?v=lJZQVRqFFPw for four of the five most followed collections, how many clicks away from those lists? ;-)
