### ISSUE TITLE
Add up blocked by administrater

### ISSUE THREAD

**Issue by Anoniemepanda** [mozilla/addons-frontend#3834]
### Describe the problem and steps to reproduce it:

I was trying to look something up on my laptop and to open it I needed an ad on but as soon as I clicked the link I got the following message:
Page not found
This add-on has been disabled by an administrator.

### What happened?
I tried installing an add on in order to open something on my laptop but it is blocked by an administrater

### What did you expect to happen?
That I could download the add on so I could open the page

### Anything else we should know?

https://testlauncher.secure.cito.nl/LaunchPage.aspx

**Comment by tofumatt** [comment]
An add-on disabled by an administrator of the add-ons site it was likely done because of an issue with the add-on. If you link to the add-on maybe @jvillalobos can shed more light on why it was disabled but the message is accurate and we likely won't re-enable a disabled add-on.
