### ISSUE TITLE
Add missing redirect for persona type

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3835]
I noticed that going from the new site with a persona search to the old site on stage, you get correctly redirected from `type=persona` -> `atype=9`, however when doing the reverse there's no redirect on the new frontend.

STR:

* Go to https://addons.allizom.org/en-US/firefox/search/?platform=mac&q=foo&type=persona in the new site.
* Click "View classic desktop site" 
* Note the URL is now: https://addons.allizom.org/en-US/firefox/search/?platform=mac&q=foo&atype=9
* Click "View new site"
* Note the URL was not converted back again.

We need a 302 redirect for `atype=9` -> `type=persona`.

_Be aware the `foo` search shows mostly themes so the data might look correct but you are actually searching all add-ons when you come back to the new site._

**Comment by muffinresearch** [comment]
I think this is a relatively quick fix, we should look to get it into the release this week.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF56 (Win10)

![meerkat](https://user-images.githubusercontent.com/31961530/32549377-e2650b9a-c491-11e7-9bf4-f9c2475716d8.gif)
