### ISSUE TITLE
Screenshot preview moves before being opened

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3842]
### Describe the problem and steps to reproduce it:

Go to an add-on detail page and click on a screenshot.

### What happened?

The screenshot thumbnail moves down before being opened:

![2017-11-08 13 59 43](https://user-images.githubusercontent.com/217628/32550443-768bf7ca-c48d-11e7-92dd-6499b8895f8f.gif)

### What did you expect to happen?

No move.

**Comment by muffinresearch** [comment]
I don't the same thing with the second and third items which is odd. See https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/ for an example.
