### ISSUE TITLE
Disabled add-on renders as 500 for admins: TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3845]
### Describe the problem and steps to reproduce it:

* Sign in as an administrator
* Load a disabled add-on: https://addons-dev.allizom.org/en-US/firefox/addon/developer-disabled/

### What happened?

The response is a 500

### What did you expect to happen?

The response should be a 404 explaining that the add-on was disabled.

### Anything else we should know?

https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/678680/

```
TypeError: Cannot read property 'id' of null
  File "/srv/code/src/amo/components/RatingManager/index.js", line 217, col 49, in Function.mapStateToProps [as mapToProps]
    addonId ${ownProps.addon.id}, versionId ${ownProps.version.id}`);
...
```

Also see https://github.com/mozilla/addons-frontend/issues/2261

**Comment by muffinresearch** [comment]
Is this only when logged in? I get a 200 OK going to https://addons-dev.allizom.org/en-US/firefox/addon/developer-disabled/ 

<img width="915" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32571426-4192b4dc-c4bf-11e7-8f3e-5491098f7bc7.png">

**Comment by muffinresearch** [comment]
FWIW: This only appears to show a 500 when using an account with permissions to see the add-on since logged in as a regular account I see the same as above.

**Comment by kumar303** [comment]
Ah, true. I can confirm that it only affects admin users.

**Comment by jvillalobos** [comment]
Must have been fixed a while ago.
