### ISSUE TITLE
"Find more search engines" link in Firefox leads to empty search results page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3846]
In `about:preferences#search` there's a link to "Find more search engines" on AMO. This points to this URL: https://addons.mozilla.org/firefox/search/?atype=4, which is currently showing an empty page. It looks like this should either redirect to https://addons.mozilla.org/firefox/search-tools/, or we should support Search Tools in the search filter.

We might discontinue search providers as an add-on type in the future, but for now we should make sure the right page is shown.

**Comment by ValentinaPC** [comment]
I think this was implemented in the last days in -dev (https://github.com/mozilla/addons-frontend/issues/3791) and will work as expected in -prod after today push.

**Comment by willdurand** [comment]
Yes, it is covered by #3791 and #3835.
