### ISSUE TITLE
Can't able to add extensions in Firefox it's showing unable to extract amo credentials what to do

### ISSUE THREAD

**Issue by PAVAN9497** [mozilla/addons-frontend#3848]

**Comment by kumar303** [comment]
Sorry that you're having trouble. Can you provide more details? Which extension are you trying to add? What do you mean by *extract amo credentials*? Could you provide a screenshot? What version of Firefox do you have? What platform are you on?

**Comment by PAVAN9497** [comment]
I'm trying to add price tracker extension and I'm on android platform.Can
you please help me to solve this.

**Comment by PAVAN9497** [comment]
I'm trying to add price tracker.it exactly saying that could extract generated credentials.im in the latest version of Firefox on android platform.

**Comment by muffinresearch** [comment]
@PAVAN9497 please can you provide the specific steps to what you're trying to do and include as much detail as possible. Please add links and screenshots if at all possible to demonstrate the issue.

**Comment by kumar303** [comment]
> it exactly saying that could extract generated credentials

I've never seen a message like this -- can you take a picture of it on your Android screen using another phone and send us the picture? Or you could take an Android screenshot: https://www.pcworld.com/article/208566/phones/how-to-take-screenshots-on-an-android-phone.html

**Comment by PAVAN9497** [comment]
![screenshot_2017-11-13-14-00-00-603_org mozilla firefox](https://user-images.githubusercontent.com/33501957/32716486-21a737be-c84e-11e7-96bd-b27f76e5f657.png)

**Comment by PAVAN9497** [comment]
I'm trying to add price tracker extension but it's not adding not only price tracker I can't able to add any other extensions solve this problem as soon as possible

**Comment by muffinresearch** [comment]
@PAVAN9497 this looks like the foxified add-on. We're unable to provide support for this add-on please contact the developers instead. Support details are available here: https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/
