### ISSUE TITLE
No able to add any extension from chrome Web store to Firefox.Its showing error like amo 

### ISSUE THREAD

**Issue by PAVAN9497** [mozilla/addons-frontend#3852]

**Comment by tofumatt** [comment]
Looks like a duplicate.

**Comment by PAVAN9497** [comment]
![screenshot_2017-11-13-14-00-00-603_org mozilla firefox](https://user-images.githubusercontent.com/33501957/32716354-8cb0fcda-c84d-11e7-933e-065c9ddac382.png)
