### ISSUE TITLE
Add-on "Last Updated" includes unlisted data

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#3856]
https://addons.mozilla.org/en-US/firefox/addon/personas-plus/ says
```
Last updated:
19 hours ago (Nov 8, 2017)
```

however, that's when I submitted an unlisted version. There were no listed submissions at that time.

**Comment by muffinresearch** [comment]
@diox is this expected? If so should the last-modified data be split so it's possible to only use data specifically for the listed add-on we're displaying on the frontend?

**Comment by diox** [comment]
That's a bug. The logic to handle `last_updated` has not been updated (ahah!) to handle unlisted versions - it should have, that field is not really relevant for unlisted versions.

@wagnerand can you please re-file on addons-server?

**Comment by ValentinaPC** [comment]
Something related - https://github.com/mozilla/addons-server/issues/4083
