### ISSUE TITLE
'See more' links in Theme Category pages are not consistent with the links in the homepage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3858]
Same as #3854 but for themes.

---

![image](https://user-images.githubusercontent.com/31961530/32604949-36c10fce-c558-11e7-91cf-c07c0a96f1f8.png)

**Comment by tsl143** [comment]
on it :)

**Comment by AlexandraMoga** [comment]
Verifed as fixed on AMO dev (WIn10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/32608549-5f61cf74-c565-11e7-920c-e5404c1ef2ef.png)
