### ISSUE TITLE
"Send abuse report" button appears inactive on device

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3862]
Steps to reproduce:

1. Go to an extension details page in AMO-satge on your device (i.e. https://addons.allizom.org/en-US/firefox/addon/bluhell-firewall/)
2. Navigate to report abuse section and tap on 'Report this add-on for abuse'
3. Write your report while observing the 'Send abuse report' button

Expected result:
The button will change to a darker shade of grey when text is entered

Actual result;
The button is not highlighted and appears as it was inactive

Notes:
Tapping on the 'Send abuse report' button before entering any text will make the button change its shade once text is entered
Reproduced on all AMO servers with FF56, Android 7.0

![abuse report](https://user-images.githubusercontent.com/31961530/32612862-0162c786-c572-11e7-9835-e379f2293b50.gif)

**Comment by AlexandraMoga** [comment]
This can also be reproduced on desktop. In the below video, you can see how the 'Send abuse report' button will display, for a short moment, the inactive red sign before submitting the report:

![desktopreport](https://user-images.githubusercontent.com/31961530/32666857-852bd204-c641-11e7-85aa-b11412183420.gif)

**Comment by tsl143** [comment]
Right now, the dark effect is given only on hover, and not matched with disable condition of button. (The tap action serves as hover on mobile, that's the reason why its darkened).
But this can be considered as a feature to differentiate between able/disable states. @tofumatt

**Comment by muffinresearch** [comment]
@AlexandraMoga buttons were recently re-styled - would you be able to see if this is still reproducible?

**Comment by AlexandraMoga** [comment]
This has been fixed by the button restyling 

![send abuse](https://user-images.githubusercontent.com/31961530/35848930-8bd48a3e-0b28-11e8-8e7a-f23f1f5c3c93.gif)
