### ISSUE TITLE
Use a JS API to install addons to side-step connection errors caused by MITM SSL certs

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3867]
Refs: https://github.com/mozilla/addons/issues/525
### Describe the problem and steps to reproduce it:

* Install a custom root CA (instructions below)
* Go to any add-on detail page and click the install button

### What happened?

The add-on fails to install with a window showing this message:

"The add-on failed to download due to a connection failure"

### What did you expect to happen?

If you have set up Firefox to use a custom root CA then it should allow add-on installations too.

### Anything else we should know?

Further analysis of the differences between the new AMO install buttons and the old shows that the old site uses a JS install API [InstallTrigger](https://github.com/mozilla/addons-server/blob/master/static/js/zamboni/buttons.js#L310) and the use of this API doesn't prevent installs from working when a MITM cert is installed.

## Reproducing the install connection failure issue

Using [Charles proxy](https://www.charlesproxy.com/) with the MITM cert installed and SSL proxying  set up to work for addons.mozilla.org  _(Update you only need the CDN host - see screenshot below)_. I can repro the issue on https://addons.mozilla.org using the new frontend.

_Charles SSL Proxying Settings ([requires the Charles Cert to be installed in Firefox first](https://www.charlesproxy.com/documentation/using-charles/ssl-certificates/) I recommend using a different profile for this):_

<img width="584" alt="ssl_proxying_settings" src="https://user-images.githubusercontent.com/1514/32652267-9de8f8a8-c5fb-11e7-84ab-dc5fe27e637a.png">

_Screenshot of the install connection error:_

<img width="962" alt="fullscreen_09_11_2017__19_07" src="https://user-images.githubusercontent.com/1514/32624551-7cc14f38-c581-11e7-91c7-a21d44539447.png">

* With charles setup to proxy SSL for the CDN as per the instructions above.
* Visit any details page
* Click the install button
* You will see the download start and then it will be followed by the connection error (shown in the screenshot above).

## Fixing the issue

There's a couple of possible fixes.

###  Using InstallTrigger

From the console running 

```InstallTrigger.install({URL: "https://addons.mozilla.org/firefox/downloads/file/764482/ublock_origin-1.14.18-an+fx.xpi?src=dp-btn-primary"});``` with Charles enabled successfully starts the install.

If we switch to using this old API for the button then this should prevent the users of AntiVirus software experiencing the issue.

### Using mozAddonManager

The alternative here would be to use mozAddonManager since installs in the discovery pane work fine when using Charles to MITM the connection. 

## QA Notes: 

* The STR above should be good for reproducing the original issue problem in production - you'll want to check on production to see you can repro the original issue with the new frontend first before validating the fix in stage. 
* **Note:** You'll need to add the relevant CDN hosts to Charles' SSL settings dialogue for validation. Here's the CDN hosts for -dev and stage.
  * addons-stage-cdn.allizom.org
  * addons-dev-cdn.allizom.org
* **Important** clear your cache between test runs. If the download is cached you will not see the problem.
* Please check the discovery pane as well as amo. The install button code is shared so it'll be a good idea to double-check that everything there is continuing to work as expected. The hosts for the download should be the same as above. AFACT mozAddonManger downloads are not impacted by the original issue.

**Comment by tofumatt** [comment]
The plan is to restore mozAddonManager in the future once we get the buttons working with it, but that’s probably a way’s out from now.

- Matt (Sent from mobile)

**Comment by kumar303** [comment]
There could be a bug in `InstallTrigger` that allows a non built-in certificate issuer so I'm not sure if this would work in `mozAddonManager` at all. Implementing `InstallTrigger` seems like a good first step.

**Comment by kumar303** [comment]
As mentioned in https://github.com/mozilla/addons/issues/525 , when an anti-virus user clicks our *current* install button on https://addons.mozilla.org (the new site), the download of the XPI fails and you can see this in the console:

```
"1510156312761 addons.xpi WARN Download of https://addons.cdn.mozilla.net/user-media/addons/832020/addon-1.1.0-an+fx-windows.xpi?filehash=sha256%3A61bf622b2cac2749de8a43a3fada3597eda7863800fe146e20c04eafa2adacaa failed:
 [Exception... "Certificate issuer is not built-in." nsresult: "0x80004004 (NS_ERROR_ABORT)" 
location: "JS frame :: resource://gre/modules/CertUtils.jsm :: checkCert :: line 169" data: no] 
Stack trace: checkCert()@resource://gre/modules/CertUtils.jsm:169 < onStopRequest()@resource://gre/modules/addons/XPIInstall.jsm:2405"
```

Here is a platform bug about the same thing: https://bugzilla.mozilla.org/show_bug.cgi?id=1403075

**Comment by kumar303** [comment]
> There could be a bug in `InstallTrigger` ...

As I read the platform bug linked up above more closely, I think it's actually the other way around. The bug may be in `XPIInstall.jsm`.

**Comment by aswan** [comment]
> There could be a bug in InstallTrigger that allows a non built-in certificate issuer so I'm not sure if this would work in mozAddonManager at all. Implementing InstallTrigger seems like a good first step.

I don't think there's a bug, InstallTrigger lets AMO pass a checksum for the thing to be installed and if we have that checksum then we don't care about the download channel since we can verify the actual xpi contents.  If we don't have the checksum for verification, then we get more paranoid about the channel actually being safe.

**Comment by muffinresearch** [comment]
> There could be a bug in InstallTrigger that allows a non built-in certificate issuer so I'm not sure if this would work in mozAddonManager at all. Implementing InstallTrigger seems like a good first step.

FWIW: As mentioned in the OP I saw install working with both mozAddonManager (on disco pane) and InstallTrigger (via the console) when running with the MITM proxy Cert, when the direct link on the new frontend was blocked post download. 

> I don't think there's a bug, InstallTrigger lets AMO pass a checksum for the thing to be installed and if we have that checksum then we don't care about the download channel since we can verify the actual xpi contents. If we don't have the checksum for verification, then we get more paranoid about the channel actually being safe. 

I didn't pass a checksum in the call when trying InstallTrigger from the console and it worked without one, but it _was_ blocked when clicking the direct link to the xpi.

**Comment by aswan** [comment]
> I didn't pass a checksum in the call when trying InstallTrigger from the console and it worked without one, but it was blocked when clicking the direct link to the xpi.

What was the URL?  If the original URL is a redirect that includes an `X-Target-Digest` header we get the checksum from there.

**Comment by muffinresearch** [comment]
> What was the URL? If the original URL is a redirect that includes an X-Target-Digest header we get the checksum from there.

Ah ok that is happening. Thanks for the clarification.

```
curl -s -D - https://addons.mozilla.org/firefox/downloads/file/764482/ublock_origin-1.14.18-an+fx.xpi?src=dp-btn-primary
```

Shows the `X-Target-Digest` header in the response.

**Comment by muffinresearch** [comment]
Looks good on -dev testing in nightly (`requires xpinstall.signatures.dev-root` pref added to about:config and set to true).

**Comment by muffinresearch** [comment]
This was hotfixed in production last friday and verified post-release.
