### ISSUE TITLE
Check that Mozilla signed extensions show up correctly 

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#3868]
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/ is a Mozilla signed extension. On the new site its showing up as "Not compatible with Firefox Quantum". On the old site it is showing up as a compatible.

Would consider this reasonably high priority (I just added that but feel free to disagree). Here's what mat said in IRC:

mat> the API says it is
mat> the frontend shouldn't use is_webextension or things like that, just rely on the compatibility info

**Comment by diox** [comment]
The issue lies with https://github.com/mozilla/addons-frontend/blob/0fdbc1d40776c50a45aa3af49152db189d4384cc/src/amo/components/AddonBadges/index.js#L33-L34 which should use the `compatibility` object on the current version to display that message instead.

`is_webextension` should never be used by the frontend.

**Comment by kumar303** [comment]
This fix is to switch to [`getCompatibleVersions({ addon, clientApp })`](https://github.com/mozilla/addons-frontend/blob/master/src/core/utils/compatibility.js#L19)

**Comment by willdurand** [comment]
@kumar303 I am not sure to understand how to use this method. I looked at its usage in the source code and it is weird with lots of rules. Is this patch correct by chance?

``` diff
diff --git a/src/amo/components/AddonBadges/index.js b/src/amo/components/AddonBadges/index.js
index e2b034a..e3f9aac 100644
--- a/src/amo/components/AddonBadges/index.js
+++ b/src/amo/components/AddonBadges/index.js
@@ -1,9 +1,11 @@
 /* @flow */
 import React from 'react';
 import { compose } from 'redux';
+import mozCompare from 'mozilla-version-comparator';
 
 import { ADDON_TYPE_EXTENSION, ADDON_TYPE_THEME } from 'core/constants';
 import translate from 'core/i18n/translate';
+import { getCompatibleVersions } from 'core/utils/compatibility';
 import Badge from 'ui/components/Badge';
 import type { AddonType } from 'core/types/addons';
 import type { I18nType } from 'core/types/i18n';
@@ -13,11 +15,12 @@ import './styles.scss';
 
 type Props = {|
   addon: AddonType,
+  clientApp: string,
   i18n: I18nType,
 |};
 
 export const AddonBadgesBase = (props: Props) => {
-  const { addon, i18n } = props;
+  const { addon, clientApp, i18n } = props;
 
   const getFeaturedText = (addonType: string) => {
     switch (addonType) {
@@ -30,8 +33,13 @@ export const AddonBadgesBase = (props: Props) => {
     }
   };
 
-  const isIncompatible = addon && addon.type === ADDON_TYPE_EXTENSION &&
-    !addon.isWebExtension;
+  const { supportsClientApp, minVersion } = getCompatibleVersions({
+    addon,
+    clientApp,
+  });
+  // A result of `1` means the first argument is higher in version than the
+  // second.
+  const compatible = supportsClientApp && mozCompare(minVersion, '56.0') === 1;
 
   return (
     <div className="AddonBadges">
@@ -53,7 +61,7 @@ export const AddonBadgesBase = (props: Props) => {
           label={i18n.gettext('Experimental')}
         />
       ) : null}
-      {isIncompatible ? (
+      {!compatible ? (
         <Badge
           type="not-compatible"
           label={i18n.gettext('Not compatible with Firefox Quantum')}
```

**Comment by willdurand** [comment]
Or maybe I should just extract some logic related to the `minVersion` and `maxVersion` from `isCompatibleWithUserAgent()`?

**Comment by kumar303** [comment]
> Or maybe I should just extract some logic ... from isCompatibleWithUserAgent()

Yeah, I think that would be the best approach.

Also, here is an extension on dev to reproduce the issue: https://addons-dev.allizom.org/en-US/firefox/addon/multi-account-containers/

**Comment by willdurand** [comment]
There was a long discussion on IRC yesterday and we decided to use the `getClientCompatibility()` helper function along with a hand-crafted User Agent for Firefox Quantum as a hotfix (it is well tested and should not introduce any regression).

**Comment by willdurand** [comment]
So, I have one more question: this "multi containers" extension is not available on Android, so if one browses the website on Android or with "android" as `clientApp`, what is she supposed to see?

- Should we display the "Not compatible with Firefox Quantum" on Android devices?
- Should we use this badge only for desktop compatibility?

**Comment by kumar303** [comment]
Fixing this issue led to a philosophical dilemma of how exactly we should be displaying this *incompatible with Quantum* label and what it even means. Here are some notes on the patch that landed:

- We decided the label is meant as a hint to help users know whether to invest their time in installing/using an extension
- If the extension supports desktop Quantum **or** Android Quantum, we think of it as *supports quantum* -- all other extensions will see the *incompatible with Quantum* label
- The enabled/disabled button states were not affected by this patch

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7) and observed a case:

1. Pick a signed by Mozilla extension i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext-locked/
2. Go to Manage Status & Version page and pick last public version 
5. Change "All Platforms" to one that your are not using while testing this i.e Linux and save changes
6. Go to add-ons details page while using new AMO pages

Results:
"Not compatible with Firefox Quantum" label is displayed.

Note: not reproducing for "MacOS" option.

**Comment by ValentinaPC** [comment]
@kumar303 : so you logged https://github.com/mozilla/addons-frontend/issues/3895 for my case?
Thanks!

**Comment by willdurand** [comment]
@ValentinaPC yes and it is fixed now.

**Comment by ValentinaPC** [comment]
This can be marked as verified fixed, because the related case we found was fixed and verified.
