### ISSUE TITLE
Search passes down "platform=all" parameter to the API if it was in the URL

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#3870]
When searching for add-ons in the new frontend, it filters by platform by default, and you can remove that filtering by selecting "Operating Systems: All" in the dropdown. That's good.

However, when the `platform=all` parameter is present in the URL, the dropdown looks the same *but* the `platform=all` parameter is passed to the API call. That results in fewer add-ons found, because instead of not filtering on platform at all, it filters add-ons that specifically have a file that is available for the special "all" platforms.

This matters because the old frontend does use that "platform=all" parameter. So, as a STR:
- Go to the old site
- Make a search
- In the filters, select Firefox 57.0 (if it doesn't let you, select 56.0 then change it in the URL) and extensions category
- Look at the results
- Click on view the new site
- Look ad the results

Expected:
- You should get the same results

Actual:
- You get a lot fewer add-ons.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev FF56(Win 7).
While passing from old to new site, platform is kept as expected.
@willdurand : More results are listed using new site, for the same search criteria... I guess this is because we do not have a browser version filter here?
