### ISSUE TITLE
https://addons.mozilla.org/en-US/firefox/addon/13993/

### ISSUE THREAD

**Issue by ws9235365** [mozilla/addons-frontend#3873]

**Comment by ksrinivasdevops** [comment]
Phrase Highlighter  addons in Mozilla Firefox is not working . with the new version these addon is not available any alternate for this

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
