### ISSUE TITLE
What has happend to BetterPrivacy? Where can i download?

### ISSUE THREAD

**Issue by athenaelectrical** [mozilla/addons-frontend#3878]

**Comment by muffinresearch** [comment]
This add-on has been removed by it's author see: https://addons.mozilla.org/en-US/firefox/addon/BetterPrivacy/.

**Comment by athenaelectrical** [comment]
OK thanks for the grim news.

**Comment by muffinresearch** [comment]
@athenaelectrical this might be a possible alternative to look at see: https://addons.mozilla.org/en-US/firefox/addon/clear-flash-cookies/

**Comment by Jerich-no** [comment]
about:addons "More" link for BetterPrivacy addon (above) lists 'Homepage' and 'By' links going to a webpage showing "Page not found" along with "If you followed a link from somewhere, please file an issue."

Better if "This add-on has been removed by its author." is shown immediately on about:addons page (without non-functional links).
