### ISSUE TITLE
'My Favorite add-ons' page returns a 404 error if collection has no add-ons included

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3884]
Steps to reproduce:

1. Log into AMO-dev with a user that has no collections
2. Open the user account menu and select 'View my Collections'
3. From the Collections menu, click on 'My favorite Add-ons'

Expected result:
My favorite Add-ons page opens even if there are no add-ons included in this collection yet

Actual result:
A 404 error page is opened instead

Notes:
Going to the desktop site and selecting there 'View the new site' will open"My Favoite...' collection page on the new frontend
Reproduced with AMO-dev, FF56 (Win 10)

![collections](https://user-images.githubusercontent.com/31961530/32725278-1a8ebd1a-c87d-11e7-8e8d-8ed981085e68.gif)

**Comment by willdurand** [comment]
@AlexandraMoga I cannot reproduce :( Could you make sure you start your STRs from a clean state, like from a fresh homepage?

The only way I see this could occur is if you get a 404 for this collection *before* with not page refresh/reload in the meantime. Yet, I am not sure it is even possible. Investigating...

**Comment by AlexandraMoga** [comment]
@willdurand I've created a clean Firefox profile, a new username and then opened AMO-dev homepage with this new user. I went to 'View My Collections' - at this point the collections desktop page is opened - and selected ' My Favorite Add-ons' from the menu on the left. This action triggered the 404 error page on the new frontend. I haven't refreshed the page and have not received any errors before this.
Hope this makes the steps more clear

**Comment by kumar303** [comment]
I can reproduce it but the *My Favorites* feature is going away.

The [simplification document](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit) declares this as a feature that will replace it:

> Maintain a way for users to create a set of collections they can manage. Don’t special-case a My Favorites collection.

**Comment by kumar303** [comment]
However, this is kind of a crappy experience for users who relied on this feature (note that no one has filed a bug). I opened this issue to route the URL to the old site https://github.com/mozilla/addons-frontend/issues/3888

**Comment by AlexandraMoga** [comment]
Verified as fixed in [#3888](https://github.com/mozilla/addons-frontend/issues/3888#event-1368412275)
