### ISSUE TITLE
Category pages with no featured Themes will briefly display the 'Featured' shelf when loading 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3886]
Steps to reproduce:

1. Go to AMO-dev and navigate to Themes homepage (i.e. https://addons-dev.allizom.org/en-US/firefox/themes/)
2. Select a theme category which does not include any featured themes (i.e. Causes)

Expected result:
Theme category page is loading details only for the available content (i.e. Top rated themes and Trending themes)

Actual result:
The 'Featured themes' shelf also appears to be loading for a brief moment

Notes: reproduced on all AMO servers with FF56 (Win 10)

![featured shelf](https://user-images.githubusercontent.com/31961530/32729337-f9e99508-c88b-11e7-8713-273ec61515de.gif)

Frame:
![image](https://user-images.githubusercontent.com/31961530/32729397-43736690-c88c-11e7-807c-0c5911135fce.png)

**Comment by willdurand** [comment]
Yes, I dont think we are able to know if a given category contains featured add-ons *before* trying to load them. We cannot fix this I believe.
