### ISSUE TITLE
New AMO pages don't return correct number of pages after empty search

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3887]
Steps to reproduce:
1. Make an empty search for themes -  https://addons-dev.allizom.org/en-US/firefox/search/?platform=windows&type=persona
2. Observe number of available pages - 14.006
3. Navigate to page 1000 - https://addons-dev.allizom.org/en-US/firefox/search/?page=1000&platform=windows&type=persona (which is also last working page from 14 006 pages)

Expected results:
There is a 25k add-ons returned by the API and the frontend should take this into account.

Actual results:
"No results were found" page is displayed. 

Notes/Issues:
- after page refresh a 404 page is displayed.
Verified on AMO-dev FF56(Win 7).
Video for this issue:
![nav-themes](https://user-images.githubusercontent.com/15685960/32732198-84d1b008-c894-11e7-8d77-5767ae57b275.gif)

**Comment by ValentinaPC** [comment]
I've already logged an issue for this, few months ago, but I forgot. :(
I'll mark it as duplicate to this one.

**Comment by muffinresearch** [comment]
Note: based on https://github.com/mozilla/addons/issues/552 this is happening in production.

**Comment by willdurand** [comment]
It is not possible to go over 25k results. I have requested an API change to get the max number of results.

**Comment by ValentinaPC** [comment]
> Note: based on mozilla/addons#552 this is happening in production.

Is happening in production for a few months now, but did not matter, because the new pages were not yet live. (https://github.com/mozilla/addons-frontend/issues/2072)

**Comment by willdurand** [comment]
The API change has been requested here: https://github.com/mozilla/addons-server/issues/6919. We have to wait for it before being able to solve this issue.

**Comment by willdurand** [comment]
API just landed.

**Comment by AlexandraMoga** [comment]
@willdurand in the context of the pagination work done now, do you think this could be addressed as well?

**Comment by AlexandraMoga** [comment]
It would be nice to fix this issue eventually :)
