### ISSUE TITLE
Serve My Favorites collection from the Django site

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3888]
A URL like this should be served from the old site:

```
https://addons-dev.allizom.org/en-US/firefox/collections/<your_username>/favorites/
```

Normal collections should be served from the new site.

Until this is fixed, users will see a 404 when taking the steps outlined in this bug: https://github.com/mozilla/addons-frontend/issues/3884

**Comment by bqbn** [comment]
@kumar303 can you help clarify what you said in https://bugzilla.mozilla.org/show_bug.cgi?id=1405351#c3,

```
But it looks like you'll need to make this pattern come before it so that the old site serves it:

^collections/mine/([^/]+)?$
```

does that refer to the literal word ```mine```, or does that refer to ```<your_username>``` you mentioned here?

**Comment by kumar303** [comment]
Yeah, the literal word `/mine/` is in the URL. I was suggestion that if you order the regular expressions like this:

```
^collections/mine/([^/]+)?$
^collections/[^/]+/[^/]+/$
```

then it should work because the first match will catch URLs like `collections/mine/<any-user>`

**Comment by bqbn** [comment]
But ```^collections/mine/([^/]+)?$``` doesn't match ```collections/<your_username>/favorites/``` (which is what is asked in this issue), does it?

So, if I understand what you mean correctly, the following two patterns should be redirected to the desktop site,

```
^collections/mine/([^/]+)?$
^collections/[^/]+/favorites/$
```

and the following pattern should be redirected to the mobile site.

```
^collections/[^/]+/[^/]+/$
```

Does this sound right?

**Comment by kumar303** [comment]
@bqbn yes, your proposal in https://github.com/mozilla/addons-frontend/issues/3888#issuecomment-345402858 is correct.

Sorry for the confusion, the `/mine/` URL is a separate issue but we still need to map it. The `/favorites/` URL is what will solve #3884

**Comment by bqbn** [comment]
@kumar303 the nginx change is now on -dev and -stage. Please test.

**Comment by kumar303** [comment]
Thanks, this is working great. I followed the steps in https://github.com/mozilla/addons-frontend/issues/3884 to test it on dev.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF57 Win10

![myfav](https://user-images.githubusercontent.com/31961530/33549498-65d3b04c-d8f3-11e7-9b56-db142abb7036.gif)
