### ISSUE TITLE
Collection comments missing from new layout

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#3890]
[Re-filed from mozilla/addons-server#6892]

This depends on https://github.com/mozilla/addons-frontend/issues/4193

### Describe the problem and steps to reproduce it:
When adding comments to an add-on when creating a collection, these comments are no longer shown to users of the collection with the new layout.

### What happened?
Comments can still be entered as part of the collection, but not shown to users of the collection.

### What did you expect to happen?
I should be able to enter the comments and users should be able to see them.

### Anything else we should know?
Comments can still be entered:

![2017-11-12_8-47-11](https://user-images.githubusercontent.com/979729/32699586-2bb6d656-c786-11e7-8625-1e006466ebbf.png)

However, the view of the collection no longer displays any of the comments.

![2017-11-12_8-48-50](https://user-images.githubusercontent.com/979729/32699599-643a7e42-c786-11e7-80a7-f0aa526bfb67.png)

For me, the usefulness of the comments was to help users understand WHY either I use them or why THEY might want to use them.  

I don't have a screenshot of my comments in the old format and was only able to find an old screenshot  via Google Images.

![2017-11-12_8-54-21](https://user-images.githubusercontent.com/979729/32699644-3d9b2056-c787-11e7-8685-7d754bcfd037.png)

**Comment by willdurand** [comment]
We do not have UX for that but according to [this Google doc](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit), we should keep notes.

**Comment by pwalm** [comment]
Collection notes! Added the little message bubble. Clicking it opens a field below the add-on:
![screen shot 2017-12-05 at 3 29 24 pm](https://user-images.githubusercontent.com/6797635/33636526-6ef3ae78-d9d1-11e7-9a80-5ce5bf85717b.png)

And it follows the "developer reply" style on the collection detail page:
![screen shot 2017-12-05 at 3 29 46 pm](https://user-images.githubusercontent.com/6797635/33636543-8025ea94-d9d1-11e7-897d-3cd2e5acd2b6.png)

**Comment by pwalm** [comment]
The suggestion text in the comment field that pops down should say something along the lines of "This note will only be visible to you and other collection contributors"

**Comment by eviljeff** [comment]
> The suggestion text in the comment field that pops down should say something along the lines of "This note will only be visible to you and other collection contributors"

@pwalm bit confused here - the purpose of the collection comments is for end users to read.

**Comment by kumar303** [comment]
Yeah, collection comments are publicly visible. I was trying to find an example but I can't now. The way I've seen them used in practical ways are to amend the description of the add-on description. 

For example, the owner of the collection might add a comment like "Be sure to register for an account first" which would appear underneath some add-on. It's also a way to provide additional context for why the add-on is in the collection.

**Comment by pwalm** [comment]
Oh, ok. Make them visible then. 👍

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10 and Android 8.0)
