### ISSUE TITLE
Theme description is not listed if installed from Discovery Pane

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3892]
Steps to reproduce:
1. Pick a theme with description - i.e. https://addons-dev.allizom.org/en-US/firefox/addon/all-fall/
2. Install it from AMO
3. Go to about:addons Themes tab and observe theme description
4. Go to Discovery Pane and install the same theme
5. Repeat step #3

Expected results:
Theme description is listed.

Actual results:
Theme description is not listed if installed from Discovery pane.

Notes/Issues:
Verified on AMO-dev FF58(Win 7).
Screenshots for this issue:
![descr-amo](https://user-images.githubusercontent.com/15685960/32733463-fcc4291c-c897-11e7-8934-6b29eefe13e1.png)
![descr-disco_pane](https://user-images.githubusercontent.com/15685960/32733466-ff7dfc3c-c897-11e7-8f6d-195a0e9c6e48.png)

Relates with #3798

**Comment by tofumatt** [comment]
This is linked to the fact that we don’t expose all properties for the themedata attribute on the install button. There’s an issue open for it.

- Matthew Riley MacPherson
tofumatt.com

**Comment by kumar303** [comment]
> we don’t expose all properties ... There’s an issue open for it.

I asked for it to be filed separately from https://github.com/mozilla/addons-frontend/issues/3798 because I think it may be related to the weird description fallback we have in the reducer. If so, this could be harder to fix. I can look into this.

**Comment by tofumatt** [comment]
Ah okay, cool.

- Matthew Riley MacPherson
tofumatt.com

**Comment by kumar303** [comment]
I looked into this further and the Discovery API does not return descriptions for themes. Apparently, the Discovery Pane has never shown descriptions for themes. Also, it seems that the description field is rarely used in production data.

@jvillalobos can you confirm that the Discovery Pane not showing descriptions for themes is expected?

**Comment by jvillalobos** [comment]
I don't know if it was an intentional decision. In my opinion, we should show the description in the Add-ons Manager when the theme is installed. As for the Discovery Pane specifically, I think that's more of a matter of layout and I don't mind that much if it isn't shown there.

**Comment by ValentinaPC** [comment]
I am not for displaying the description in Disco Pane, but if any of the themes listed in Disco Pane have description (in AMO), I think we should show it in Add-ons Manager (after installation) and make no difference for same theme (no matter from where is installed - AMO or Discovery Pane)

**Comment by kumar303** [comment]
ok, we'll need an API change to get the descriptions: https://github.com/mozilla/addons-server/issues/6953

**Comment by ioanarusiczki** [comment]
This issue is not reproducible on AMO dev with FF62 - Win10

![text displayed](https://user-images.githubusercontent.com/33448286/47210777-82588b80-d39c-11e8-999f-7813d9834d3b.gif)
