### ISSUE TITLE
Windows-only and Linux-only add-ons are flagged as incompatible with Quantum

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3895]
### Describe the problem and steps to reproduce it:

* Create a windows-only or linux-only extension that supports Firefox 57
* Go to its listing page

### What happened?

It says *incompatible with Firefox Quantum*

### What did you expect to happen?

It should not include this badge.

### Anything else we should know?

See https://github.com/mozilla/addons-server/issues/6905 for details. Also see this thread: https://discourse.mozilla.org/t/extension-not-compatible-with-firefox-quantum/21460/7

This is a follow-up to https://github.com/mozilla/addons-frontend/issues/3868

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7).
Only-Win and only-Linux compatible add-ons are not flagged as incomaptible with Quantum.
Examples:
- https://addons-dev.allizom.org/en-US/developers/addon/webext-linux/versions/1533230
![linux](https://user-images.githubusercontent.com/15685960/32773350-86572b9a-c931-11e7-9cca-ac43733f7370.png)

- https://addons-dev.allizom.org/en-US/firefox/addon/webext-win/
![win](https://user-images.githubusercontent.com/15685960/32773971-8349e0da-c933-11e7-99d2-1d2e8dae4fcf.png)
