### ISSUE TITLE
Expose the Addon size in the Add-on metadata

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3900]
Refiled from https://github.com/mozilla/addons/issues/535

On the old site we exposed the add-on download size. 

<img width="693" alt="ublock_origin____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32725509-4613b964-c86d-11e7-9d91-434562eb50ad.png">

However, in the new frontend this detail is missing. It's useful for knowing the size of the download ahead of time so it would be good to re-instate this data.

**Comment by anweshknayak** [comment]
@muffinresearch how to expose this? Make it like blue or dark black?

**Comment by muffinresearch** [comment]
@anweshknayak as a starting point it can follow the other metadata e.g how version is exposed:

<img width="490" alt="adblock_plus_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35435423-9914a8ea-0282-11e8-9f79-9310c73aa9b7.png">

**Comment by muffinresearch** [comment]
@anweshknayak how are you going with this? Please let us know if you have any questions.

**Comment by anweshknayak** [comment]
hey @ryanfeeley I couldn't locate this one. If I tried getting into this page it took me to the production one.

**Comment by jvillalobos** [comment]
Mentor: @willdurand

**Comment by rpl** [comment]
The file size is provided by the [Addon Version Detail api endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v4-addons-addon-(int-addon_id|string-addon_slug|string-addon_guid)-versions-(int-id)-).

**Comment by divakarvenu** [comment]
Hi, can i take this as my first contribution?

**Comment by caitmuenster** [comment]
Hey @divakarvenu, welcome! You can absolutely take this bug up. We'll officially assign this to you once you have a PR up. :)

**Comment by AlexandraMoga** [comment]
Verified fixed on stage with Fx67, Win10x64
The version size is now exposed in the More information section on the addon details page and on All versions page:
![image](https://user-images.githubusercontent.com/31961530/60586380-a5946100-9d9a-11e9-9919-eacc65f17c43.png)
