### ISSUE TITLE
Install from collection missing from new layout

### ISSUE THREAD

**Issue by irvinm** [mozilla/addons-frontend#3907]
### Describe the problem and steps to reproduce it:
Similar to https://github.com/mozilla/addons-frontend/issues/3890, the old layout allowed people to install an add-on directly from a collection.

### What happened?
Viewing a collection, there is no way to install the add-on unless you click on the add-on link and leave the collection OR right-click on the link and open it in a new tab to install it.

### What did you expect to happen?
I would expect people could directly install the add-on from the collection page like in the old layout.

### Anything else we should know?
It appears that "installs from collection page" was intended to remain with the new layout. (https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit)

Old screenshot (just a search on google images):

![2017-11-14_10-41-32](https://user-images.githubusercontent.com/979729/32788978-a7f91fe6-c928-11e7-80f3-3599f205f4b7.png)

Current layout:

![2017-11-14_10-44-53](https://user-images.githubusercontent.com/979729/32789114-f990815a-c928-11e7-9982-620c2e6b4c4d.png)

**Comment by dessant** [comment]
It looks like this is by design, the same way search results don't have install buttons anymore. It's safer for users to visit the details page and learn about extensions before installing them.

**Comment by muffinresearch** [comment]
Supeceded by #3992
