### ISSUE TITLE
Misleading banner and installation button for incompatible add-ons

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3914]
Steps to reproduce:
1. Load details page for an add-on that is not compatible with your used platform and FF version i.e. https://addons.allizom.org/en-US/firefox/addon/disconnect/
2. Observe incompatibility banner and installation button

Expected results:
The banner "This add-on is not available on your platform." is displayed (because is has higher coverage than the other one) and not install button.

Actual results:
The banner with the FF browser incompatibility is displayed and an useless install button.

Notes/Issues:
- also "+Add to Firefox" install button should be removed when the add-on is not compatible with your platform because is useless
Reproducing on AMO-dev FF57(Win 7).
Screenshots:
![old_pg](https://user-images.githubusercontent.com/15685960/32843347-390b634a-ca28-11e7-9885-23daed33a1d8.png)
![new_pg](https://user-images.githubusercontent.com/15685960/32844020-f6345cb4-ca29-11e7-8cac-3fb79c848720.png)

**Comment by muffinresearch** [comment]
I'm not sure what action we need to take here. The button is disabled and now the bar is above the copy in a more prominent location. Marking as wontfix.
