### ISSUE TITLE
Display warning when a page is not public when shown to developers or admins

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3915]
If you're a developer or an admin, it should be very clear when you're seeing a page and it's not a page that is public for any given reason.

It should be clear that:

- The page isn't public
- A reason why it isn't public (awaiting approval, blocked, disabled, invisible etc)
- The state of the add-on button should also be updated if the addon isn't yet signed so that it's clear that you can't install the add-on.

For STR, see: https://github.com/mozilla/addons-frontend/issues/3817

**Comment by pwalm** [comment]
We should just use the [message bar spec](http://design.firefox.com/photon/components/message-bars.html) for this.
