### ISSUE TITLE
Screenshots should display tips while hovering them

### ISSUE THREAD

**Issue by marcoagpinto** [mozilla/addons-frontend#3917]
Describe the problem and steps to reproduce it:

Open:
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2/
and hover the mouse over the screenshots.

What happened?

No tips are shown (they used to be on the old site) and the screenshots don't fit in the gadget.
What did you expect to happen?

See the tips and the images should fit in the gadget.

Anything else we should know?

(Please include a link to the page, screenshots and any relevant files.)

**Comment by marcoagpinto** [comment]
I was told to open the case here.

Originally it was at:
https://github.com/mozilla/addons-server/issues/6879

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF58 (Win 10)

![show hint](https://user-images.githubusercontent.com/33448286/35983811-946ccd6c-0cfb-11e8-92a6-3eb185d78e60.png)
