### ISSUE TITLE
Show star rating / review summary in detail page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3918]
The Add-on detail page should show a summary of star ratings and reviews to help users better assess the quality of the add-on before installing it.

Please check the mocks before implementing but currently it looks like:

<img width="507" alt="screenshot 2017-11-15 11 55 46" src="https://user-images.githubusercontent.com/55398/32852022-566b7b72-c9fc-11e7-9cbb-46774203ff82.png">

**Comment by muffinresearch** [comment]
Superceded by https://github.com/mozilla/addons-frontend/issues/5437
