### ISSUE TITLE
Featured section from homepage is not hidden if no featured add-ons available

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3922]
Steps to reproduce:
1. Load Extensions homepage while using "Add-ons for Android" option in AMO-dev i.e https://addons-dev.allizom.org/en-US/android/extensions/
2. Observe featured section

Expected results:
No featured add-on should dismiss featured section.

Actual results:
An empty featured section is displayed.

Notes/Issues:
- not reproducing in any add-ons categories.
Verified on AMO-dev FF57(Win 7, Android 7.2.1).
Screenshot for this issue:
![2017-11-16_1053](https://user-images.githubusercontent.com/15685960/32882264-75dce11a-cabc-11e7-900a-be9d4c00edda.png)

**Comment by willdurand** [comment]
This is weird because I can load the featured extensions.

**Comment by ValentinaPC** [comment]
@willdurand : are you using Add-ons for Android option - https://addons-dev.allizom.org/en-US/android/extensions/ ?
Although I guess it reproduces for Add-ons for Firefox also, if there are no featured extensions at all.

**Comment by willdurand** [comment]
Yes, android device with Firefox for Android and the Android version of the website :/

**Comment by ValentinaPC** [comment]
You should be able to reproduce it on Desktop too, with Firefox for Android option.

**Comment by willdurand** [comment]
Indeed, I only reproduce on Desktop.

**Comment by willdurand** [comment]
Ok, in theory it should not be possible to have no addons in any of the shelves but let's fix it, just in case.

**Comment by devaneymoz** [comment]
There are a host of issues relative to how content (featured or otherwise) surfaces on AMO for Android. I'm actually writing up a doc detailing the various issues and I will include this. It may be we need to point Android users to a new, distinct featured collection and not a singular Featured Extensions collection.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win 7, Android 7)
Postfix screenshot:
![ext_homepage](https://user-images.githubusercontent.com/15685960/33063734-02e06fd0-ceac-11e7-85d2-32729534ed73.png)
