### ISSUE TITLE
Add missing languages to our languages file

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3925]
The fix for https://github.com/mozilla/addons/issues/528 used the full set of languages in the list as far as they matched up with the language pack data. However, there are also another ~25 languages that we have langpacks or dictionaries for that aren't represented in that list and as a result are not shown the the langpacks page.

The old site does a bit of a hack for that data by including it without an english or native name e.g:

<img width="1194" alt="dictionaries___language_packs____add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/32893733-7fb4f522-cad2-11e7-9ab6-2f6205cc9645.png">

The better fix for the new frontend is to look in to those languages and add the relevant entries into  languages.js to fix the problem.

**Comment by richa031** [comment]
please tell me the details of this, I want to see through it

**Comment by willdurand** [comment]
we've been adding new languages from time to time so I believe we can continue to do that.
