### ISSUE TITLE
Website header is untranslatable

### ISSUE THREAD

**Issue by piotrdrag** [mozilla/addons-frontend#3926]
### Describe the problem and steps to reproduce it:

![screenshot-2017-11-16 dodatki do firefoksa](https://user-images.githubusercontent.com/139229/32894332-d3045092-cadc-11e7-868d-aa3bdc4b6244.png)

### What happened?
“Firefox Add-ons” is in English on https://addons.mozilla.org/pl/firefox/.
### What did you expect to happen?
“Firefox Add-ons” in Polish on https://addons.mozilla.org/pl/firefox/.
### Anything else we should know?

CCing @peiying2

**Comment by willdurand** [comment]
Hi @piotrdrag, the header is actually a brand and therefore has no translation or RTL equivalent. The only translation key you have is "visually hidden" but what you see is an image (logo + text).

**Comment by tofumatt** [comment]
This seems like an issue a few people have run into and does feel like a bug. Maybe we should be translating this? cc @pwalm

- Matt (Sent from mobile)

**Comment by muffinresearch** [comment]
FWIW: the heading is translated behind the scenes as a text alternative, it's just not visually translated.

**Comment by muffinresearch** [comment]
This is also consistent with other brand usage elsewhere e.g the Thunderbird site in AR.

<img width="1022" alt="thunderbird_ _ _ _ _ _ _ _ _mozilla" src="https://user-images.githubusercontent.com/1514/32901243-49ca7b84-cae7-11e7-851d-6bca1a1c2c86.png">

**Comment by tofumatt** [comment]
It’s consistent with other sites but I still think it’s wrong/unexpected :-)

It’s more “brand-consistent” I guess, but when it’s the only “English” (and sometimes ASCII) text on screen it feels off.

**Comment by piotrdrag** [comment]
I wouldn’t equate a proper name like Thunderbird to a descriptive name like “Firefox *Add-ons*”. I believe the latter should be localized, just like we localize Firefox Account.

**Comment by eviljeff** [comment]
Fwiw, we translated 'Add-ons' on the legacy site.  Product names, like Firefox, weren't translated.

**Comment by peiying2** [comment]
Brand names, such as Mozilla, Firefox, Pocket are not translated, per current branding guidance. Add-ons is a product name, can be translated, and has been.  If this is an image, then, it will be very difficult (remember Marketplace).  If it is hard-coded, we should change it so it is localizable.

**Comment by piotrdrag** [comment]
> If this is an image, then, it will be very difficult (remember Marketplace). If it is hard-coded, we should change it so it is localizable.

A week ago it was localizable. :)

**Comment by kumar303** [comment]
> A week ago it was localizable. :)

That's because it did not follow the [Photon](http://design.firefox.com/photon/welcome.html) brand guidance, which was a mistake. The change request was in https://github.com/mozilla/addons-frontend/issues/3763

**Comment by muffinresearch** [comment]
I mentioned this to @jvillalobos and there's some upcoming discussions re: branding. It'll make sense to hold off making any changes here until those are concluded.

**Comment by pwalm** [comment]
> A week ago it was localizable. :)

Yeah, that was my fault. We should have been implementing the wordmark from the get-go.
