### ISSUE TITLE
Cannot open collections if a sign-up process was previously interrupted

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3930]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/ while logged out
2.Try to login and enter some invalid credentials
3.When credentials are not recognized, press the "Sign up" link provided
4.Change your mind and go again to https://addons-dev.allizom.org/en-US/firefox/ 
5.Try to open "Password managers" collection from homepage

Expected results:
Collection is opened without any issue

Actual results:
Collection cannot be loaded and "Authentication credentials were not provided." message is displayed

NOTES:
Not reproducible on Stage
Reproducible only for collections listed under the "Customize the way Firefox works with extensions. Are you interested in…" module
Reproducible on Android devices also

Please see video for this issue : 
![credentialsnotprovided](https://user-images.githubusercontent.com/1583842/32898199-2873f678-caf0-11e7-8f72-6552dab85a46.gif)

**Comment by willdurand** [comment]
Well, it looks like the STRs are optional because the API returns 401 for these collections, e.g., https://addons-dev.allizom.org/api/v3/accounts/account/mozilla/collections/password-managers/.

**Comment by willdurand** [comment]
These two collections were turned private but they should stay public. That's why it stopped working and the STRs did not play any special role here. I'll open a new issue to better handle the private collections.

**Comment by willdurand** [comment]
Follow-up in https://github.com/mozilla/addons-frontend/issues/3931. Thanks for the report @vcarciu!
