### ISSUE TITLE
Determine max load that the addons-frontend server can handle

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3932]
In https://github.com/mozilla/addons-frontend/issues/3916 the `addons-frontend` servers were way over capacity.

In order to help ops determine how many workers the server needs, we should figure out the current load limits. For starters, this could be a quick spot check using some graphs and basic traffic patterns. We may need to file follow-ups for automated load testing and more realistic traffic simulations.

**Comment by muffinresearch** [comment]
@bqbn do you have any tooling for working this out already?

**Comment by bqbn** [comment]
The tool I can think of to test website responsiveness is ab (https://httpd.apache.org/docs/2.4/programs/ab.html). As for graphing we can probably use datadog.

**Comment by willdurand** [comment]
I suppose we don't need to do this anymore (after 1.5 years).

**Comment by kumar303** [comment]
> In order to help ops determine how many workers the server needs, we should figure out the current load limits. 

We figured it out the old fashion way: in production! 💥
