### ISSUE TITLE
Expose environment var for statsd / datadog connection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3933]
Similar to how `addons-server` gets a [`STATSD_HOST`](https://github.com/mozilla/addons-server/blob/bba78ddf2fd97e897077778564f5af4db1cc5c21/src/olympia/conf/dev/settings.py#L162) (and other variables), the `addons-frontend` server needs access to env vars that it can use to configure a connection to https://app.datadoghq.com/

This issue is to start by exposing the environment vars in dev, stage, and prod.

**Comment by bqbn** [comment]
Is it OK to expose the env vars to all environments now?

This is so we don't have to submit two PRs later, one for -dev and one for non-dev.

If the code requires the vars to be only on -dev first, we can do that.

**Comment by kumar303** [comment]
Yes, adding the vars to all environments would be great. I was just going to start by testing on dev but it won't hurt to have them everywhere. Thanks.

**Comment by bqbn** [comment]
The 2 env variables are now passed to the app.
