### ISSUE TITLE
Fix translation keys for the Lastpass -> LastPass change

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#3934]
There was a capitalization typo in the LastPass heading which was fixed in https://github.com/mozilla/addons-frontend/issues/3928

Since the translations were extracted for this after the tag, we can updated the keys in the translations that have already landed to save the translations being marked fuzzy in the next extraction. 

The patch for this can also update any translations using Lastpass instead of LastPass.

**Comment by ioanarusiczki** [comment]
This issue was verified on AMO dev with FF57 for Win10x64 
LastPass Password Manager  is translated in some of the languages such as Deutsch, Polish, Russian, French.
Please let me know if you want any further verifications.
