### ISSUE TITLE
Space between add-on title and author (also author should be underlined)

### ISSUE THREAD

**Issue by marcoagpinto** [mozilla/addons-frontend#3936]
### Describe the problem and steps to reproduce it:
There is no space between the line of the add-on title and author.

See how it looked in the past:
http://marcoagpinto.cidadevirtual.pt/dictionaries-installing/en-mozilla_1.png

How it looks now:
https://addons.mozilla.org/en-US/firefox/addon/british-english-dictionary-2

### What happened?
The line spacing vanished and so did the underline of the author's name.

### What did you expect to happen?
In the old version there was line spacing and author underlining.

### Anything else we should know?
Links already included above.

**Comment by jvillalobos** [comment]
Highlighting the author as a link is covered in #3771. Leaving this open for now to discuss the spacing. /cc @pwalm
