### ISSUE TITLE
New themes added to a user collection are not visible on the collection details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#3938]
Steps to reproduce:

1. Log into AMO-prod (i.e. https://addons.mozilla.org/en-US/firefox/)
2. From the user drop down menu, click on 'View My Collections' 
3. Select one of the available collections to view its details page
4. In the collection details page, click on 'Edit collection'
5. Add a couple more add-ons to your collection (make sure to include themes as well)
6. Click on 'Save Changes' and then 'View your collection' to see the changes.

Expected result:
The new add-ons included in the collection are visible on the collection details page

Actual result:
New themes added to the collection are not displayed and themes that were already part of the collection are no longer visible

Notes: The new items are visible after refreshing the page several times.
Reproduced on all AMO-servers with FF57 (Win 10 and Android 7.0)

The below video starts from Step4 - Edit collection:

![collection](https://user-images.githubusercontent.com/31961530/32949411-5e5430b2-cbab-11e7-8d35-962925fb7270.gif)

**Comment by kumar303** [comment]
Thanks for raising an issue but we're going to replace this legacy page in https://github.com/mozilla/addons-frontend/issues/4004 which means you won't see the legacy page at all when add-on add-ons to a collection.
