### ISSUE TITLE
Search filters are not visible enough

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3942]
I got feedback about the way search works, especially after #3689. We made the search in the header global and not specific depending on the view context (extensions, themes, explore, etc.).

For some users, filters are not visible enough on the search results page:

![screen shot 2017-11-17 at 17 42 52](https://user-images.githubusercontent.com/217628/32958454-d40a3d48-cbbe-11e7-9c22-0c64637f7a28.png)

Here is what I have heard: user searches for "keyword". She gets a lot of themes on the first page but she is interested in extensions. She navigates to the "extensions" section to hopefully get refined results based on her initial search. This does not work and she gets the "extensions" landing page instead. From here, she searches again but get the same results as before, hence entering an infinite loop until she finds the filter she needs or she gives up.

**Comment by willdurand** [comment]
This has been discussed a bit in #3689 but it is better to have a proper issue for this discussion. Below are the last comments from #3689.

---

@jvillalobos said:

Maybe the add-on type drop-down should be replaced with something like a radio-button, so users can see the words "Extension" and "Theme" rather than just the less-clear "Add-on type".

---

@pwalm said:

- @jvillalobos Could do the radio button solution as opposed to the drop down.
- @krupa I've spec'd out a reset search function ("[x] Clear Filters"), would that solve the issue?
<img width="543" alt="screen shot 2017-11-16 at 3 47 37 pm" src="https://user-images.githubusercontent.com/6797635/32922128-8a448f94-cae5-11e7-9be4-6439476a573f.png">

---

@ValentinaPC said:

@pwalm - your "Clear filters" solution makes sense only if the search is depended of each page - in Extensions page we return only extensions, in Themes page only themes, which is not the case right now due to this exact issue. 
While present case - mixed search results - not sure how "Clear filters" will help, because Add-on type is "All" from the start.

---

@tofumatt said:

That space is used on mobile to show/hide (expand/contract), so that's also an issue:

![2017-11-17 16 26 34](https://user-images.githubusercontent.com/90871/32957634-3172cad2-cbb4-11e7-8ff3-5861307b0ca6.gif)

**Comment by jvillalobos** [comment]
I propose that we move the add-on type selection to the top of the filters, and for the desktop site we show a radio button selection instead of the drop down. Could be something like:

> Show results for:
> * All add-ons
> * Extensions
> * Themes

I initially proposed that we show search results categorized by type, which is what the Google Store does. So, you get a block of extension results, a block of theme results, etc., each linking to a "results of this type" page. That's another way to go, but would require more work.

The Chrome Store also uses radio buttons for filtering by type, fwiw.

**Comment by pwalm** [comment]
This is going to get a big redesign, closing this in anticipation of a bigger issue/project
