### ISSUE TITLE
New design cannot be translated anymore with Google Translate

### ISSUE THREAD

**Issue by Smile4ever** [mozilla/addons-frontend#3943]
### Describe the problem and steps to reproduce it:
I tried to translate addons.mozilla.org with the Google Translate service for pages. https://github.com/Smile4ever/firefoxaddons/issues/85

### What happened?
The page didn't translate to the choosen language. Instead, the page was rendered incompletely (see the linked issue above, it contains a screenshot)

### What did you expect to happen?
I expected the page to be translated to the selected language.

### Test URL
https://translate.google.com/translate?hl=&sl=auto&tl=en&u=https%3A%2F%2Faddons.mozilla.org%2Fen-US%2Ffirefox%2Faddon%2Fbrowser-security-1%2F&sandbox=1

**Comment by andymckay** [comment]
Because content scripts cannot be run on AMO as per docs https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts this isn't addons-frontend fault. I can't remember if there's a bugzilla bug on lifting that restriction, you could file one, it might get won't fixed quite quickly though. As a side note, you can't run Chrome content scripts on the Chrome store either, for similar reasons.

**Comment by wagnerand** [comment]
If I read this issue correctly, it's not about an add-on failing to work on AMO. At least not only. See the test url in the original post, which does not require any add-ons, but just opens AMO in Google Translate.

**Comment by andymckay** [comment]
You are right, total fail. It's Friday afternoon, I need to go do something else.

**Comment by muffinresearch** [comment]
Looking at the translated frame directly in Firefox I see: 

`SecurityError: Permission denied to access property "gtcomm" on cross-origin object` 

Looking in chrome there's similar frame related errors. 

```
Uncaught DOMException: Blocked a frame with origin "https://translate.google.com" from accessing a cross-origin frame.
```

These all look to point to issues on the google site, but I'm not sure if there's something we're doing that's triggering it.

**Comment by muffinresearch** [comment]
Still happens - needs further investigation as to why this is happening.

**Comment by Smile4ever** [comment]
Kind of fixed: the page is translated, but the layout disappears after a few seconds.

**Comment by grahamperrin** [comment]
> …  disappears after a few seconds.

For an issue with similar symptoms, from the [closing comment](https://github.com/webcompat/web-bugs/issues/25772#issuecomment-465361483) under **(JavaScript) Reddit www.reddit.com redesign versus the Internet Archive Wayback Machine · Issue #25772 · webcompat/web-bugs**, with added emphasis:

> … The same thing is happening in all browsers. This is indeed an issue to **report to web.archive.org**, … 

> … guess both reddit and wayback (Internet archive) know about it.
> 
> To note that with all these sites entirely generated on the client side through JS (including webcompat.com) it will become harder to archive the content.
