### ISSUE TITLE
See top extensions Firefox ad mail leads to 404

### ISSUE THREAD

**Issue by LeoniePhiline** [mozilla/addons-frontend#3947]
### Describe the problem and steps to reproduce it:

I got a Firefox ad email "Give your browser superpowers with extensions". 

I clicked the mail's call to action button "see the top extensions" 

### What happened?
I ended up on https://addons.mozilla.org/en-US/firefox/collections/mozilla/trending-add-ons/?utm_source=email&utm_medium=email&utm_campaign=desktop&utm_content=emlear_6
This was a 404 error page! 

### What did you expect to happen?
To see the top extensions. 

### Anything else we should know?

This form does not offer me to upload my Screenshot. 

The full mail text is:

Discover Essential Extensions for Firefox
Extensions are like toppings for your baked potato — once you try them, you can't imagine going without them. Firefoxers use extensions to give their privacy a boost, play games, block ads, manage video downloads and all kinds of other extraordinary stuff. 

Give your browser superpowers and discover the top Firefox extensions:
SEE THE TOP EXTENSIONS

The full resulting page text is:

Page not found

Sorry, but we can't find anything at the address you entered.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it.

**Comment by willdurand** [comment]
thanks for reporting, it has been answered in #3951.
