### ISSUE TITLE
Problem with email link

### ISSUE THREAD

**Issue by Postphunk** [mozilla/addons-frontend#3951]
### Describe the problem and steps to reproduce it:
Received an email from Firefox about exploring extensions available and when I clicked the link to do so, it sent me to a firefox page which said the link could not be found.

### What happened?
See above
### What did you expect to happen?
See above
### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/collections/mozilla/trending-add-ons/?utm_source=email&utm_medium=email&utm_campaign=desktop&utm_content=emlear_6

**Comment by devaneymoz** [comment]
Thanks for this! It's being addressed. (We'll fix the link in the email)

**Comment by muffinresearch** [comment]
@devaneymoz do you want to keep this issue open to track it, or can this be closed?

**Comment by devaneymoz** [comment]
@muffinresearch I'm fine if you want to kill this issue. I've brought it up with the email team and it's being addressed outside of this issue (I don't believe marketing folk are on github).

**Comment by devaneymoz** [comment]
Oh - but worth noting here's another issue we encountered when a slug changes.

**Comment by kumar303** [comment]
We've seen a few problems around changing slugs. It might require a lot of effort but we could keep track of old slugs in the database and serve redirects.

**Comment by muffinresearch** [comment]
FWIW there's a discussion on handling slug redirections here: https://github.com/mozilla/addons-server/issues/6943
