### ISSUE TITLE
Flag link remains enabled after report

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3952]
From https://github.com/mozilla/addons/issues/554:

> Once user flag any review at addons.mozilla.org web site, the link remains enabled. In old web site, user was not able to flag the review until reviewer check report (either with positive or negative result). Disabling link was helping to identify which reviews are already reported and prevented from duplicate report. Thanks

I can see this being useful to developers who are flagging reviews for their add-ons. They would like to know which flagged reviews are pending moderation, so they should appear as "Flagged" until they are handled.

**Comment by kumar303** [comment]
Seems reasonable. I requested API changes in https://github.com/mozilla/addons-server/issues/7037

**Comment by willdurand** [comment]
API has landed, is this still a thing or can we either downgrade or close this issue?
