### ISSUE TITLE
More... Button on 5xx width devices invisible.

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-frontend#3955]
### Describe the problem and steps to reproduce it:
![screenshot from 2017-11-21 21-03-56](https://user-images.githubusercontent.com/139033/33094170-85f28b1c-ceff-11e7-82e3-dbcde21e790a.png)

There appears to be a missing breakpoint for display sizes around 500px width, e.g the Motoro Moto E (2. Gen) which for English isn't much of a problem but for the German translation results in the "Mehr" (More...) button to be almost invisible.

### What did you expect to happen?

The search bar should still be at the point where it is at lower widths (at the very top).

This is probably very low priority :)

**Comment by muffinresearch** [comment]
@EnTeQuAk I can't repro that - I see this: 

![screen shot 2017-11-22 at 09 29 10](https://user-images.githubusercontent.com/1514/33119737-d0147044-cf67-11e7-8f33-496dbcd4471b.png)

What version of FF are you running there? In your screenshot it looks like the search isn't shrinking like it should.

**Comment by willdurand** [comment]
FWIW, we already noted false-positives with the Firefox "responsive view" tool.

**Comment by EnTeQuAk** [comment]
Unfortunately I don't have that specific device, I just forwarded a report by @Lyra2108 so maybe she can provide some more details about what firefox version got used.

My reproduction happened in Firefox Nightly and I can reproduce this without the "responsive view" tool as well.

**Comment by Lyra2108** [comment]
I used the default PlayStore version (57.0).
When I compare your screenshot with mine it seems to me that you use larger font settings than I do. The display and the font settings are set to the lowest possible values on my phone.

![grafik](https://user-images.githubusercontent.com/2102141/33143444-2e025c8c-cfba-11e7-80f2-e16189904d07.png)

**Comment by wagnerand** [comment]
The triage team has a hard time to reproduce it, it's not a good first bug.
