### ISSUE TITLE
Missing search module

### ISSUE THREAD

**Issue by MikkCZ** [mozilla/addons-frontend#3956]
STR:
1. Navigate to AMO.
1. See the dedicated search field.
1. No AMO search module is offered to add.
1. Switch to desktop version.
1. Search module is offered.

**Comment by willdurand** [comment]
Indeed, thanks for the report. It looks like a duplicate of #3836. Can you confirm?

**Comment by MikkCZ** [comment]
You are right, it's a duplicate of #3836.
