### ISSUE TITLE
Save to Feedly Knowledge Board missing

### ISSUE THREAD

**Issue by zomars** [mozilla/addons-frontend#3959]
### Describe the problem and steps to reproduce it:
I'm following the links from the official website: https://addons.mozilla.org/en-US/firefox/addon/save-to-knowledge-board-feedly/

### What happened?

It can't find it.

**Comment by tofumatt** [comment]
Unfortunately this likely means the add-on has been unlisted/removed (presumably by the developer).

This is the issue tracker for the website itself, not specific add-ons, so we can't actually help more than that as to the reason, you'd need to contact the add-on developer directly for that.

Sorry! 😞
