### ISSUE TITLE
"Featured Extensions" collection on Android surfaces flawed content

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#3961]
Clicking/tapping "Featured Extensions" on Android returns strange results, often showing as little as a three or four total featured extensions. 

Also, it's unclear where it's pulling this content from, exactly? Is it pulling from the same featured collection that desktop pulls from?

https://addons.mozilla.org/firefox/extensions/?sort=featured

Regardless of how featured content surfaces on today on Android, an ideal outcome would be to create a custom featured collection made just for Android, since what's considered feature worthy on Android is often different than desktop.

**Comment by jvillalobos** [comment]
It looks like we're using this collection, actually: https://addons.mozilla.org/en-US/firefox/collections/mozilla/mob/

So it might just be a matter of adding more useful mobile content to it.

**Comment by jvillalobos** [comment]
We confirmed that we just need to modify the collection, and it's up to date now.
