### ISSUE TITLE
No way to set public or private statistics for a theme

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3965]
Steps to reproduce:
1. Submit a theme i.e. https://addons-dev.allizom.org/en-US/developers/theme/12-test-theme/edit and set stats for it

Expected results:
There is a way to set public or private statistics for a theme.

Actual results: 
There is no way to set statistics for a theme, but link to stats is listed in theme details pages using the new frontend.

Notes/Issues:
Verified on AMO-dev FF57(Win 7).
Screenshot:
![stats_for_themes](https://user-images.githubusercontent.com/15685960/33169022-ae5ffe7a-d04b-11e7-9775-37cb50b7c96a.png)

**Comment by jvillalobos** [comment]
A complete stats dashboard and private/public stats should become available for WebExtensions themes, which is what @eviljeff is working on. In the meantime we should probably just hide the stats link for lightweight themes.

**Comment by willdurand** [comment]
> A complete stats dashboard and private/public stats should become available for WebExtensions themes, which is what @eviljeff is working on. In the meantime we should probably just hide the stats link for lightweight themes.

@jvillalobos do we have stats for other add-ons? (question is: should we only display the link for webext or more?)

**Comment by jvillalobos** [comment]
All add-on types, except for search engines, have a stats dashboard. There's a per-add-on setting for making the dashboard public, which we should honor. So, the link should appear if the dev chose to make the dashboard public.

**Comment by willdurand** [comment]
> All add-on types, except for search engines, have a stats dashboard. There's a per-add-on setting for making the dashboard public, which we should honor. So, the link should appear if the dev chose to make the dashboard public.

I believe this is fixed then. I am pretty sure we're doing this already.
