### ISSUE TITLE
Unreviewed themes seem "reviewed" 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3966]
Steps to reproduce:
1. Submit a new theme i.e. https://addons-dev.allizom.org/en-US/firefox/addon/cbnmchnmkjm/
2. Don't wait to be approved and see its details page

Expected results:
A message regarding that the theme is not public and awaits to be reviewed is displayed.

Actual results:
No message regarding that the theme is not public is displayed.

Notes/Issues:
- if not logged, old pages display a note regarding the unreviewed theme, while new pages load a 404 page.
Verified on AMO-dev FF57(Win 7). Issue is reproducing on all servers.
Screenshot from old and new AMO pages while logged in or not:
![old1](https://user-images.githubusercontent.com/15685960/33172302-3d81e9ae-d058-11e7-8345-0910647207e5.png)
![2017-11-23_1412](https://user-images.githubusercontent.com/15685960/33172322-56cbb1d8-d058-11e7-9d77-05531d704035.png)
![old](https://user-images.githubusercontent.com/15685960/33172344-7020aed6-d058-11e7-8fc0-481d3481561b.png)
![new2](https://user-images.githubusercontent.com/15685960/33172389-8cc747f2-d058-11e7-808d-7201b333d64e.png)

**Comment by ValentinaPC** [comment]
Reproducing for extensions also.
![2017-11-29_1420](https://user-images.githubusercontent.com/15685960/33374875-934a9360-d510-11e7-83ad-f2de37176b0b.png)
![2017-11-29_1421](https://user-images.githubusercontent.com/15685960/33374876-93699620-d510-11e7-9c3d-91d428271cc9.png)

**Comment by kumar303** [comment]
> Reproducing for extensions also.

This is a separate issue since it's not displaying a 404. It would be helpful if you could file it separately since we may need to get some guidance on the UX / messaging.

**Comment by ValentinaPC** [comment]
@kumar303 : I think is the same, because, my example has a problem :( - I think was auto approved until I accessed extension details page, and that is why I did not received a 404 page.
I've tried with a static theme and new AMO pages return a 404 page.

**Comment by ValentinaPC** [comment]
The case for the 404 message is, as I mentioned in my initial issue, at notes:
- > if not logged, old pages display a note regarding the unreviewed theme, while new pages load a 404 page.
Same for extensions.
While being logged with an admin account, or being the developer of the add-on, no "pending review" message is displayed in details pages.

**Comment by kumar303** [comment]
Oh, duh, I forgot to log out when I was testing it.

OK, so we just need to add the "pending review" messaging. This requires an API change: https://github.com/mozilla/addons-server/issues/7064

**Comment by diox** [comment]
Per @jvillalobos's comment in mozilla/addons-server#7064 I'm wontfixing the API change:
> Yes, the new front-end shouldn't expose an add-on as pending review, and that should extend to themes. Themes are reviewed very quickly, so it's not useful to show anything while they await review. The only other possible case is if an admin changes its status back to under review, but that should be very rare and we don't expose reasons when other add-ons are de-listed due to review.

**Comment by willdurand** [comment]
@diox so I guess we should close this issue as wontfix?
