### ISSUE TITLE
Search add-ons do not have average daily users

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3968]
### Describe the problem and steps to reproduce it:

Browse: https://addons.mozilla.org/fr/firefox/search/?type=search

### What happened?

All add-ons have "0 users", which is a bad signal. The problem is that search add-ons do not have average daily users (the API returns `0`) because of the nature of these add-ons.

### What did you expect to happen?

Not to see "0 users" everywhere at the very least.

### Proposal

We could display the number of weekly downloads for these add-ons. The `SearchResult` component should not display the average daily users when `addonType` is "(open-)search". It should display the number of weekly downloads and reflect this difference in the UI (using a different icon and text).

**Comment by jvillalobos** [comment]
Makes sense to me, it's what we do on the old front-end. Note that this also applies to listing pages and other places where these add-ons are shown.

**Comment by willdurand** [comment]
This has been fixed already.
