### ISSUE TITLE
Expose metadata via Open Graph for easier AMO page sharing

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#3969]
Sharing AMO pages on sites like Facebook or Discourse doesn't show much data from the contents of the page. Talking to the Discourse admins, it looks like all we need to do is expose some metadata via Open Graph. Here's a comparison between AMO and airmo:

http://iframely.com/debug?uri=https%3A%2F%2Fair.mozilla.org%2Fmozilla-weekly-project-meeting-20171120%2F

http://iframely.com/debug?uri=https%3A%2F%2Faddons.mozilla.org%2Faddon%2Ffebe%2F

**Comment by nexinspiration** [comment]
Can I work on this?

**Comment by kumar303** [comment]
@nexinspiration thanks for your interest. This seems like a complex patch so I'm not sure that we'd be able to mentor a contribution for it. Here are some others to consider: https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug

**Comment by rraue** [comment]
We definetly should add the necessary og-tags and as well a meta description, because unfortunately Google is not reading og-tags. Some addons have really great sharing numbers.

One thought on this: Do we have bigegr pictures then the thumpnails available? With this size FB is previewing our urls way less attractive then it could be. [They write](https://developers.facebook.com/docs/sharing/best-practices):

> Use images that are at least 1200 x 630 pixels for the best display on high resolution devices. At the minimum, you should use images that are 600 x 315 pixels to display link page posts with larger images. Images can be up to 8MB in size.

When we do this, we need to be aware of localisations, as og:url shouldnt contradict the url and the canonical.

**Comment by willdurand** [comment]
> When we do this, we need to be aware of localisations, as og:url shouldnt contradict the url and the canonical.

`og:url` is the add-on URL (canonical), the locale is part of this URL.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on AMO dev and AMO stage with FF62 - Win 10 
I've noticed that the new meta properties are available for extensions, static and lw themes.
Also checked these after changing the language - I did not see issues.
Here's an example for the meta properties on AMO dev
![ogimage for extensions](https://user-images.githubusercontent.com/33448286/46742510-d635e700-ccaf-11e8-883c-36ef81d34a59.png)




The only question is about the `og:image` meta property:

-  `og:image` for extensions is displayed only if the screenshot section contains images, it's an URL of the first screenshot (such as this one https://addons-dev-cdn.allizom.org/user-media/previews/full/77/77620.png?modified=1529678019 for [Adblock Edge](https://addons-dev.allizom.org/en-US/firefox/addon/adblock-edge/?src=rating)).  - is this as expected to be?

- `og:image` is always displayed for static themes such as below but it is not available for lw themes 
 
```html
<meta property="og:image" content="https://addons-dev-cdn.allizom.org/user-media/version-previews/full/0/188.png?modified=1528980436" data-react-helmet="true">
```
Let me know if I should file an issue for the lw themes.

**Comment by ioanarusiczki** [comment]
@willdurand I filed https://github.com/mozilla/addons-frontend/issues/6587
I think @jvillalobos could tell what it's expected for extensions, the first screenshot or the logo, so please let us know.

> og:image for extensions is displayed only if the screenshot section contains images, it's an URL of the first screenshot (such as this one https://addons-dev-cdn.allizom.org/user-media/previews/full/77/77620.png?modified=1529678019 for Adblock Edge). - is this as expected to be?

Meanwhile, I'm marking this verified on AMO dev - FF62- Win10

**Comment by jvillalobos** [comment]
I agree that using the first screenshot and the logo as fallback is the best approach.

There are a couple of changes coming up that will affect this eventually: (1) having at least one screenshot will be required, (2) there will be a way to select a "primary" screenshot. We don't need to worry about that now, though.

**Comment by ioanarusiczki** [comment]
Ok @jvillalobos, thanks for clarification.
