### ISSUE TITLE
Convert quotes to blockquote and cite ready for the real data

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#397]
In the real data we're using more correct markup for the quotes. This will be blockquote and cite. Quotation marks will be in the markup in order to allow for localized quotation marks.

This should update the markup used and expect the data to have the HTML. Also the styling needs to be updated so it will remain unchanged.

**Comment by Ryuno-Ki** [comment]
> Quotation marks will be in the markup in order to allow for localized quotation marks.

Why is this better than styling blockquote with [CSS quotes](https://developer.mozilla.org/en-US/docs/Web/CSS/quotes)?

**Comment by muffinresearch** [comment]
Because quotation marks can be localized and this allows localizers to provide them as they see fit.

**Comment by Ryuno-Ki** [comment]
In my mind blockquotes serve as pull quotes. Something like this (look at the middle of the image):

![Pull Quote](https://upload.wikimedia.org/wikipedia/en/d/de/Pull-Quote.PNG)
(Source: [CC BY-SA 3.0](http://creativecommons.org/licenses/by-sa/3.0/ "Attribution-ShareAlike 3.0"), https://en.wikipedia.org/w/index.php?curid=8820640)

Here, the quotation marks serve only as decoration, hence CSS.
