### ISSUE TITLE
Searches are not working as expected in disco pane

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#3982]
Steps to reproduce:
1.Set all prefs to point to -dev disco pane
2.Restart Firefox and go to about:addons
3.From "Extensions" tab , search for "Firefox"
4.Go to https://addons-dev.allizom.org/en-US/firefox/ and perform same search
5.Observe that there are compatible extensions returned for AMO-dev search

Expected results:
We should display some results in disco pane too

Actual results:
There are no results for "Firefox" search in disco pane

NOTES:
Tested in FF Nightly, Win10
Some searches are working but I can't see any reason for the different behaviors. For example a search for "Grammarly" with same settings will correctly return results.

Please see video for this issue : 
![discosearch](https://user-images.githubusercontent.com/1583842/33278877-8d1bc6f6-d3a5-11e7-9c44-f506723ff010.gif)

**Comment by tofumatt** [comment]
That page isn't actually Disco Pane; it's in `about:addons` but is browser code hitting an older API that addons-server is responsible for.

That search is really old and I don't think we should really be filing bugs against it other than if it's totally broken. It needs updating and I think that's a plan for the future (many of us chatted about this very thing on IRC last week and think that search box should just send the search to AMO in a (new) tab).

But this isn't a frontend bug. It could be an issue with the results from the API Firefox hits. If it's only -dev too it's likely an indexing issue or something.
