### ISSUE TITLE
Map Redux routing location to component props

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3986]
Now that https://github.com/mozilla/addons-frontend/issues/181 has landed, we can update all components that were passing around a `location` object via props. This should make everything less magical and should cut down on unnecessary parent to child prop passing. Here is an example of how to find them with [rg](https://github.com/BurntSushi/ripgrep)

<details>
<summary>
Show output

```
$ rg 'location='
```

</summary>

```
src/amo/components/Addon/index.js
253:            location={location}

src/amo/components/AddonReviewListItem/index.js
289:              location={location}

src/amo/components/AddonReviewList/index.js
254:              location={location}
271:                    location={location}

src/amo/components/App/index.js
224:            location={location}
237:            location={location}

src/amo/components/FlagReviewMenu/index.js
58:            location={location}

src/amo/components/Header/index.js
74:        <SectionLinks className="Header-SectionLinks" location={location} />
144:              location={location}

src/amo/components/RatingManager/index.js
158:          location={location}

src/amo/components/Footer/index.js
171:              location={location}

src/core/containers/LoginRequired/index.js
23:    return <LoginPage location={location} />;

tests/unit/amo/components/TestSearchPage.js
28:        location={location}
```

</details>

**Comment by willdurand** [comment]
So, I found occurrences of `location=` in some test files, in page components (expected) and:

- `Footer` and `Header` components, but they are used only by the `App` component (which automatically gets a `location` prop), so I guess it is fine to leave it as is
- the `SearchForm` component passes the `location` to the `AutoSearchInput`, but only this component passes the `location` to it (the other call does not need to pass the `location` and the `AutoSearchInput` works without a `location`).

So, I guess we are good here too :)
