### ISSUE TITLE
Account name is moving at click

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3987]
Steps to reproduce:
1. Load AMO-dev homepage https://addons-dev.allizom.org/en-US/firefox/
2. Click multiple times on your account name

Expected results:
There are no display or layout issues.

Actual results:
The name is moving.

Notes/Issues:
Verified on AMO-dev FF57(Win 7). Reproducing on all AMO servers.
Video fro this issue:
![acc name](https://user-images.githubusercontent.com/15685960/33312976-0f2639ba-d432-11e7-9c62-a7dd485b82d5.gif)

**Comment by tsl143** [comment]
@ValentinaPC , does this issue, still exist? I am unable to reproduce :(

**Comment by AlexandraMoga** [comment]
@tsl143 I was still able to reproduce this issue on all servers

![account_move](https://user-images.githubusercontent.com/31961530/35498298-73d8d848-04d6-11e8-8b13-ca8b3c99b449.gif)

**Comment by willdurand** [comment]
I can't reproduce anymore.

**Comment by AlexandraMoga** [comment]
This looks fixed indeed. I can't reproduce on either desktop or mobile.
