### ISSUE TITLE
Upgrade moment to avoid Regular Expression Denial of Service  

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#3989]
NSP reported a vulnerability in the `moment` library we're using for formatting dates (see [this build for example](https://travis-ci.org/mozilla/addons-frontend/jobs/308515032)). There is not fix yet but we should upgrade as soon as a new release is out.

Upstream issue: https://github.com/moment/moment/issues/4163

**Comment by kumar303** [comment]
fixed in https://github.com/mozilla/addons-frontend/pull/4011
