### ISSUE TITLE
Sort add-ons in a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3991]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

Depends on: https://github.com/mozilla/addons-server/issues/8354

The user should be able to:
* View a collection
* Sort the add-ons by popularity, name, and time added

Here's how it looked on the classic site:

<img width="751" alt="screenshot 2017-11-28 12 02 38" src="https://user-images.githubusercontent.com/55398/33335989-46d9606a-d434-11e7-93c6-78c797f35eb5.png">

**Comment by pwalm** [comment]
Should appear below the collection info on the left side of the screen:
![screen shot 2017-12-04 at 10 53 59 am](https://user-images.githubusercontent.com/6797635/33570374-80278f48-d8e1-11e7-9a61-bf1c8b7affef.png)

**Comment by smayer97** [comment]
I would recommend that instead of a drop-down menu, that it be the ability to click on Column Header to trigger the sort. 
Also would be nice to be able to remember last sort used.

**Comment by smayer97** [comment]
And as implied by the grpahic in the OP, the "Date Added" field needs to be add/included.

If not treated as part of this issue, see this issue entry:
Date Added column missing from new Edit Collection window
https://github.com/mozilla/addons-frontend/issues/4794

**Comment by pwalm** [comment]
Add "Newest first" and "Oldest first" to the sort options.
