### ISSUE TITLE
Install an add-on from a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3992]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

The user should be able to:
* View a collection of add-ons
* Click an install button in the add-on listing within the collection
* (Analytics should track how the install came from a collection)

**Comment by pwalm** [comment]
View Collection mode:
![screen shot 2017-12-04 at 10 50 09 am](https://user-images.githubusercontent.com/6797635/33570203-eb681df0-d8e0-11e7-9864-f8b96787a51e.png)

**Comment by kumar303** [comment]
We should consider implementing an A/B testing framework (https://github.com/mozilla/addons-frontend/issues/4262) before tackling this issue so we can measure the effectiveness of allowing installs from a Collection.

**Comment by jrbenny35** [comment]
This would also be a good test for the upcoming functional tests.

**Comment by bobsilverberg** [comment]
I'm wondering where we stand on this. We do not currently include an install button in our list of search results, and this seems like a similar situation. There was also some discussion above about possibly A/B testing this in some way.

@jvillalobos and @pwalm in what direction do you think we should do with this feature?

**Comment by jvillalobos** [comment]
For now I think we should be consistent with search results and *not* do this. I suspect we'll eventually bring back install buttons for all of these cases, but that's a larger project to be done down the line.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. I suppose we can close this issue then, and open a new one if and when we decide this should be done.
