### ISSUE TITLE
On detail page: this add-on is featured in <Collection>

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#3994]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

An add-on that is part of a *featured* collection should have a panel on its detail page saying "this add-on is featured in `<Collection>`" (which links to the collection).

For example, [Ghostery](https://addons.mozilla.org/en-US/firefox/addon/ghostery/) should have a panel saying "...featured in [Privacy Matters](https://addons.mozilla.org/en-US/firefox/collections/mozilla/privacy-matters/)."

This isn't in the scope document but it [is discussed here](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit?disco=AAAABg6h01Q).

**Comment by pwalm** [comment]
I mocked this up in some original screens a while back, but it was for collections with icons/images. Could look like this?
![screen shot 2017-12-04 at 10 46 34 am](https://user-images.githubusercontent.com/6797635/33570039-6db6cb7c-d8e0-11e7-97fc-2029027ae528.png)

**Comment by willdurand** [comment]
Since featured collections are gone (soonish), I don't think we need to spend time on this. We have recommended extensions now.
