### ISSUE TITLE
Allow contributors to maintain a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4000]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

As an admin (or collection owner), grant some user the ability to maintain a collection. The new UI for this will be implemented in https://github.com/mozilla/addons-frontend/issues/3995 but the classic site should let you do it.

The user with maintenance privileges should now be able to:
- Sign in
- Go to an add-on detail page
- Add the add-on to the collection
- Go to the collection page
- Edit add-ons in the collection

**Comment by bobsilverberg** [comment]
As per https://github.com/mozilla/addons-frontend/issues/3995#issuecomment-350380170, contributors will not be able to be assigned to a collection via the new front end. @jvillalobos can you please confirm that we can close this?

**Comment by jvillalobos** [comment]
Confirmed.
