### ISSUE TITLE
[Tracker] Edit all details about collection add-ons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4004]
**This has been split apart into** https://github.com/mozilla/addons-frontend/issues/4577  https://github.com/mozilla/addons-frontend/issues/4578 https://github.com/mozilla/addons-frontend/issues/4590 https://github.com/mozilla/addons-frontend/issues/4576

Tracker: https://github.com/mozilla/addons-frontend/issues/2782

A user should be able to:

- Sign in
- View an existing collection that they created (the classic site enables creation)
- Edit the comments about an add-on in the collection
- Delete an add-on in the collection
- Add a new add-on to the collection with comments

**Comment by pwalm** [comment]
Screenshot of the edit modal:
![screen shot 2017-12-04 at 10 33 52 am](https://user-images.githubusercontent.com/6797635/33569477-ae388764-d8de-11e7-9a86-f7ab70862987.png)

[Screens are here](https://mozilla.invisionapp.com/share/YCCYEOFRH) ("Collections" section at the bottom)

**Comment by pwalm** [comment]
> Add a new add-on to the collection with comments
I thought this was being dropped?

**Comment by kumar303** [comment]
Comments on each add-on is not getting dropped. The [doc](https://docs.google.com/document/d/1DutmS8yco-hNiKJ1-0MrkAkze7Ue88xpA4b-MWx6MLI/edit) calls *Collector’s note (per add-on in collection)*.

**Comment by kumar303** [comment]
I split out https://github.com/mozilla/addons-frontend/issues/4577 (deleting add-ons) and https://github.com/mozilla/addons-frontend/issues/4578 (editing comments) since those are pretty big.

**Comment by kumar303** [comment]
Styles for view add-ons within the collection editor: https://github.com/mozilla/addons-frontend/issues/4579

**Comment by kumar303** [comment]
This was just too massive so I split it apart (see the updated description).
