### ISSUE TITLE
Homepage content programming update - 7 Dec '17

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4005]
Please see this [content doc](https://docs.google.com/a/mozilla.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit?usp=sharing) for homepage programming updates to go live on **Thursday, 7 December**. 

@muffinresearch

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF57 Win10:

A few questions:
@devaneymoz: I see that the 'Top rated themes' shelf has been repositioned. Wouldn't the page look more organized if the 'Change the way Firefox looks...' and the 'Top rated Themes' shelves were consecutive? Just a thought.
@tofumatt: 
1.Will the homepage content be updated also in -dev and -stage, or will the changes be fully testable only when they reached production? Currently, some of the examples have no matches in -dev (see hero banners), which means they will generate a 404.
2.In the 'Top rated themes' shelf, "Themes" starts with a upper letter. Compared to the other shelves' titles and 'More...'links, this looks like a small inconsistency.
![image](https://user-images.githubusercontent.com/31961530/33605412-506bbd7e-d9c2-11e7-91c6-828052a926ca.png)
