### ISSUE TITLE
Sorting search results by Add-on Type - Extensions is not working as expected

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4008]
Steps to reproduce:
1.Go to https://addons.allizom.org/en-US/firefox/
2.Search for  "fire" and press Enter
3.Sort by recently updated and observe that there are at least two webextensions in the list of results
4.From "Add-on Type" filter option, select "Extension"

Expected results:
At least the webextensions listed at step3 should be visible in the list

Actual results:
No results were found for "fire" message is displayed

NOTES:
Tested in FF Release, Win10x64

Please see a video for this issue : 
![firesearch](https://user-images.githubusercontent.com/1583842/33370389-14867b8a-d500-11e7-91e5-abc268a2175f.gif)

**Comment by kumar303** [comment]
> observe that there are at least two webextensions in the list of results

Those are not extensions, they are search plugins

![firefox add ons test add ons for firefox](https://user-images.githubusercontent.com/55398/33386042-b6a0b2fc-d4ef-11e7-8dc5-a7d63e708ceb.png)

**Comment by vcarciu** [comment]
@kumar303 : I don't think that this is invalid even if they are search plugins. If I filter by themes, these search plugins are not displayed. If I filter by extensions they are not displayed. If we have only these 2 types of filters the results from "All" add-on types should fall in one of the options(or add more filters :) ).

**Comment by kumar303** [comment]
> the results from "All" add-on types should fall in one of the options ... or add more filters

Yes, we probably do need more filters. Here are the other types that we do not have in the drop-down:
https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-type

I would suggest filing that as another issue since it's a bit different than your description.

**Comment by vcarciu** [comment]
@kumar303 : thanks, will do that
