### ISSUE TITLE
Theme without an icon is causing layout issues through search suggestions

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4009]
Steps to reproduce:
1. Load AMO-stage https://addons.allizom.org/en-US/firefox/
2. Search for "1b"
3. Observe search suggestions

Expected results:
There are no display or layout issues.

Actual results:
A theme that seems to have no icon, is causing layout issues.

Notes/Issues:
Verified on AMO-stage FF57(Win 7).
Screenshot for this issue:
![2017-11-29_1454](https://user-images.githubusercontent.com/15685960/33376213-7a29db8e-d515-11e7-9edd-e14242bdf038.png)

**Comment by kumar303** [comment]
The icon URL is a 404 which is strange but might only be happening on the stage server. We should look out for this on production but we should also see if maybe a height/width default would fix the rendering.

**Comment by tsl143** [comment]
@kumar303, the alt text is shown when image is 404, this may be an edge case but we can cover this putting `overflow: hidden` on image tag.
Consider #4249

**Comment by AlexandraMoga** [comment]
Verified as fixed on -dev and stage (FF56, Win10x64)

![image](https://user-images.githubusercontent.com/31961530/35612118-4bf198d8-0670-11e8-80af-4b253c57e746.png)
