### ISSUE TITLE
"Request was throttled" message displayed if trying to rate an extension after sending a report abuse

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4010]
Steps to reproduce:
1.Go to AMO Stage (https://addons.allizom.org/en-US/firefox/)
2.Select any extension or theme which was not visited before
3.Send a report abuse
4.Try to rate the extension\theme

Expected results:
Rating should be allowed

Actual results:
"Request was throttled" message displayed and rating is not added

Notes/Issues:
Verified on AMO-stage FF57(Win 10x64).
Probably related to #4007 

Please see video for this issue : 
![throttled](https://user-images.githubusercontent.com/1583842/33376817-d7e4a86a-d517-11e7-8f24-e10fa3894ff2.gif)

**Comment by kumar303** [comment]
This is an API issue: https://github.com/mozilla/addons-server/issues/7062

**Comment by vcarciu** [comment]
@kumar303 : I think that this can be closed, right?

**Comment by kumar303** [comment]
Yes!

**Comment by AlexandraMoga** [comment]
Verified in [#7062](https://github.com/mozilla/addons-server/issues/7062)
