### ISSUE TITLE
Expand state for user collections

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4016]
In https://github.com/mozilla/addons-frontend/issues/2768 we need to store collections for the signed in user. The existing state needs to be reorganized.

For QA, please test for regressions in the collection viewing features. For example:
- Go to the home page and click on a collection
- Check that pagination works
- Go back and view another collection

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF57 Win10

Checked collection view and navigation for homepage and user collections. No errors have been spotted during the verification process.
