### ISSUE TITLE
Polyfill request animation in the test suite

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4017]
We load a polyfill in the web application for React 16 (search for `import 'raf/polyfill'`) but not in the test suite. This litters the console with warnings. We should add that polyfill to the test suite, maybe in `tests/setup.js`.

<img width="982" alt="screenshot 2017-11-30 16 53 16" src="https://user-images.githubusercontent.com/55398/33459363-514951a6-d5ef-11e7-8c53-f2c3458f1ed9.png">

**Comment by tofumatt** [comment]
Good call, thanks for noticing. The tests since moving to Jest have been so noisy that I run them with the --silent argument most of the time, so I missed this entirely. 😓

**Comment by willdurand** [comment]
Why would the reducers yield such warnings though? 🤔

**Comment by kumar303** [comment]
> The tests since moving to Jest have been so noisy...

Yeah, when I get time I'm going to create a console reporter plugin to accomplish this: https://github.com/facebook/jest/issues/4156

**Comment by kumar303** [comment]
This depends on a new polyfill module introduced by https://github.com/mozilla/addons-frontend/pull/4119

I'll fix this when that patch lands.

**Comment by kumar303** [comment]
A few of the tests in https://github.com/mozilla/addons-frontend/pull/4182 kept failing with out of memory errors. I guess the Travis VM doesn't perform well with the polyfill. Instead of spending a lot of time investigating I'm just going to close this for now. Maybe there's another way to make the React warnings go away.
