### ISSUE TITLE
unable to log into AMO with a specific account only

### ISSUE THREAD

**Issue by jawz101** [mozilla/addons-frontend#4023]
https://addons.mozilla.org/en-US/android/

Not Authorized

Sorry, but you aren't authorized to access this page. If you aren't signed in, try signing in using the link at the top of the page.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you are signed in and think this message is an error, please file an issue. Tell us where you came from and what you were trying to access, and we'll fix the issue.

**Comment by jawz101** [comment]
You also cannot get it to bring up the login box if privacy.resistfingerprinting is set to true

**Comment by kumar303** [comment]
Logins should work with the resist fingerprintings prefs. Do you also have cookies disabled? Or is javascript disabled? Can you provide some more details about the steps to reproduce the issue? From reading your description I'm assuming some initial step is missing -- maybe you began by tapping the *Register or Log in* button?

**Comment by jawz101** [comment]
Ok.,  It looks like no specific settings are causing this problem for me.
Running Firefox for Android Nightly (59)

I'm going to write down every step so I take all of the factors out.

- I cleared data on the app so I'm starting on scratch
- Rebooted Android device
- Cleared data on Firefox for Android one more time
- Open Firefox for Android and click next through the initialization steps
- I hit the 3 dot menu in upper right hand corner and pick add-ons, then browse all firefox Add-ons
 takes me to https://addons.mozilla.org/en-US/android
- click on register or login link and it takes me to

`https://accounts.firefox.org/oauth/signin?scope=profile&state=(some string of stuff)&redirect_url=https%3A%2F%2Faddons.mozilla.org%2Fapi%2Fv3%2Faccounts%2Fauthenticate%2F&client_id=(another different string)`

- I sign-on with sync credentials and it takes me back to https://addons.mozilla.org/en-US/android
click never on the "do you want to remember this site" popup.
- Behind the pop-up it already had displayed that I am not authorized to login to the AMO site.

**Comment by kumar303** [comment]
Thanks for the detailed notes. I still can't reproduce it with these steps.

> I cleared data on the app so I'm starting on scratch

You mean in the Android system menu? I don't think this will remove your installed add-ons, if you have any. If you have any privacy add-ons they could be affecting things like cookies or internal Firefox behavior. 

Also, it's possible that an add-on (or privacy configuration) altered a preference in your profile. Sometimes, disabling the add-on will not restore the original preference. I'm not sure what the easiest way is to erase all customizations in your Firefox Android profile but if you do it, make sure you back up your profile first or try it on a different device, etc.

**Comment by jawz101** [comment]
ok this may be something completely different.
I deleted my profile on my computer and created a new one from my desktop computer.  I also deleted my Firefox Sync account and created a new one.  Whenever I sign on from my Desktop I still get the error msg.  This is with no add-ons and out-of-the-box prefs.  It has to be something with my Firefox account or something.  I don't know what could be going on.

**Comment by kumar303** [comment]
Is it working for you using a new Firefox Account? You could use the plus sign to make a new account with the same email like `existing-email+test123@provider.com`.

**Comment by jawz101** [comment]
I was using the exact same email.  Lemme try your suggestion

**Comment by jawz101** [comment]
ok, that worked with email+firefox@domain.com

**Comment by kumar303** [comment]
So, yeah, I guess somehow your other account is triggering an error on the server. What is the email address of the account that causes the Not Authorized problem? If you prefer, you could send it to me via `kmcmillan@mozilla.com`

**Comment by jawz101** [comment]
I just emailed you.  Thanks

**Comment by kumar303** [comment]
It's fine, I have spam filtering.

**Comment by kumar303** [comment]
@EnTeQuAk @wagnerand @eviljeff is anyone able to look into why this account is triggering Not Authorized on two different machines? I imagine there is some `addons-server` logging about it. You can PM me for the email.

**Comment by kumar303** [comment]
@jawz101 just to confirm, are you able to log in repeatedly with the new `email+firefox@domain.com` account you just created? I am wondering if more than just the initial registration succeeded for you.

**Comment by jawz101** [comment]
seems to be doing well today

**Comment by kumar303** [comment]
what seems to be doing well? Is your old account working again?

**Comment by jawz101** [comment]
the old account still gets a msg that it's not authorized.

**Comment by muffinresearch** [comment]
@jawz101 is this working for you now or are you still experiencing an issue?

**Comment by jawz101** [comment]
you can close it.  I am just ticking with the new account  email+firefox@domain.com convention
