### ISSUE TITLE
Move report abuse button to add-on rating section

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4025]
### Describe the problem and steps to reproduce it:

* Get mad about an add-on that is [running cryptomining code in the background](https://getpocket.com/a/read/1896599118)
* Search for it and go to its detail page
* Express your rage

### What happened?

If you don't find the *report abuse* button you might decide to leave a one star rating instead.

### What did you expect to happen?

You should find the *report abuse* button before leaving a one star rating.

### Anything else we should know?

The new user mocks have already been updated to help mitigate this:

<img width="507" alt="screenshot 2017-12-04 11 50 46" src="https://user-images.githubusercontent.com/55398/33567746-d4c17e12-d8e9-11e7-9ea2-91f19c3555e8.png">

**Comment by jvillalobos** [comment]
That wording isn't right. It could be misinterpreted (more) as a way to report bugs. The text currently is "Report this add-on for abuse", which is more accurate.

**Comment by kumar303** [comment]
ok, thanks for catching that

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win 7, Android 7).
Postfix screenshot:
![2017-12-05_0917](https://user-images.githubusercontent.com/15685960/33594735-c6bf76c0-d99d-11e7-890f-eb0c60dd5208.png)
