### ISSUE TITLE
Implement yellow stars for user's add-on rating

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4029]
Per UX, the add-on rating stars should be yellow whenever they indicate the site user's personal rating. They should be gray in all other cases (for example: cumulative ratings in add-on listings).

Consult the UX specs before implementing. The spec currently looks like:

<img width="509" alt="screenshot 2017-12-04 15 11 34" src="https://user-images.githubusercontent.com/55398/33576433-707c9538-d905-11e7-8c6a-f5edb2dc1e24.png">

**Comment by bobsilverberg** [comment]
The current ratings use svg files for display, specifically:

- dim-star.svg
- full-star.svg
- half-star.svg

All of which are found in /src/ui/components/Rating/img

I assume we'll need some new images for the gold stars? Who might be able to produce those?

**Comment by bobsilverberg** [comment]
So @kumar303 was kind enough to show me how to extract the gold outlined star from the sketch file, but I think we also need a full gold star. I assume we don't need a gold half-star, as gold is only used for the UI when a user can set a rating, and users cannot set half-star ratings. But I imagine that the UI would show all outlined stars if a user has not provided a rating, and then once they have rated an add-on we would show filled in gold stars to indicate their rating.

Are those assumptions correct @pwalm?

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58 (Win10, Android 7.0)

Interactive stars are now yellow:
![image](https://user-images.githubusercontent.com/31961530/36094610-9f60a21c-0ff7-11e8-9662-3adab3686a25.png)
![image](https://user-images.githubusercontent.com/31961530/36094625-ab5fd358-0ff7-11e8-9c8f-7ed3adbbafb0.png)
![image](https://user-images.githubusercontent.com/31961530/36094627-b17868cc-0ff7-11e8-86f8-cfc17b65a57e.png)

**Comment by dessant** [comment]
Please consider using a different tone of yellow. My gut reaction is to not touch the rating widget or give a small rating to see less of the current color 😋, it pierces your eyes on the white background.

Here's a yellow that is more pleasant in my opinion.
![screenshot from 2018-02-12 15-13-50](https://user-images.githubusercontent.com/7513068/36098393-6faa2060-1007-11e8-8453-d3c850a294c7.png)

**Comment by pwalm** [comment]
@dessant Thanks for your feedback, but we have a design system in place that unifies things like colour, so we are unable to change that.

**Comment by wesinator** [comment]
there is still confusing implementation of the star colour  
#9077
