### ISSUE TITLE
ESR 52 - More link is mis-aligned.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4032]
![add-ons_for_firefox](https://user-images.githubusercontent.com/1514/33605755-e8db827a-d9b2-11e7-8033-13bb0c8295f9.jpg)

Looks like removing display: block from `.SectionLinks-dropdown .DropdownMenu-button` fixes it - but it will need further testing to make sure this doesn't regress other versions.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF52.0 (64-bit) under Win 7.
Postfix screenshot:
![2017-12-05_1712](https://user-images.githubusercontent.com/15685960/33614270-87d5503c-d9df-11e7-9452-5b3d31e91060.png)
