### ISSUE TITLE
ESR 52: theme icon masking isn't working

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4033]
This is on the homepage with Firefox ESR 52:

![add-ons_for_firefox](https://user-images.githubusercontent.com/1514/33605841-37b02e82-d9b3-11e7-88bd-0d9b57ec6056.jpg)

**Comment by muffinresearch** [comment]
> 2 Partial support in Firefox refers to only support for inline SVG mask elements i.e. mask: url(#foo).

See https://caniuse.com/#search=mask

**Comment by willdurand** [comment]
Looks like the `mask` is not well-supported then, because that's used here: https://github.com/mozilla/addons-frontend/blob/72af49fab33969fa65ff44530b06cc7ef948c8e1/src/amo/components/CategoryIcon/styles.scss.

I guess the IE fallback should also be made for ESR 52.

**Comment by muffinresearch** [comment]
@willdurand yep full mask support came in 53 unfortunately.

**Comment by ioanarusiczki** [comment]
Verified on all AMO servers FF52 ESR (Win10)
Theme icons are correctly displayed.
![theme icons](https://user-images.githubusercontent.com/33448286/33760961-35604fe0-dc10-11e7-961b-cf84636ac767.png)
