### ISSUE TITLE
Show if an add-on requires payment on listing page

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#4036]
There will be some policy change around add-ons that require payment. Developers already declare whether their add-on requires a payment on the developer hub. We also need to expose that information on the public listing page.

**Comment by muffinresearch** [comment]
Is this a duplicate of https://github.com/mozilla/addons-frontend/issues/2080 ?

**Comment by wagnerand** [comment]
Wow, I forgot that I had filed this already, sorry. Closing...
