### ISSUE TITLE
the keyword "jetpack" is still auto-listed on upgraded webext

### ISSUE THREAD

**Issue by Ulf3000** [mozilla/addons-frontend#4037]
### Describe the problem and steps to reproduce it:

upload a sdk addon and amo always adds the keyword "jetpack" automatically, which already sucks ... 

now i ported my first extension to webext , since it still has the @jetpack in its id, amo will still add jetpack to the keywords . 

i suggest removing that feature completely  also for older addons 

thanx for listening :)

**Comment by kumar303** [comment]
Eesh, sorry about that. Sounds like a bug. Can you re-file it on [addons-server](https://github.com/mozilla/addons-server/) ? That's where the fix will need to be applied.

**Comment by muffinresearch** [comment]
Re-filed as https://github.com/mozilla/addons-server/issues/7189
