### ISSUE TITLE
Developer name in header of listing page should be highlighted as a hyperlink

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#4040]
Previously discussed in #3771 and #3936, but the scope of those bugs was different. We should highlight the username in the header of add-on listing pages, to make it clearer that it's a link:
<img width="728" alt="screen shot 2017-11-16 at 3 55 35 pm" src="https://user-images.githubusercontent.com/6797635/32922352-9c05d912-cae6-11e7-80d4-b2708e4f4025.png">
The image above also highlights the word "by", but I don't think that should be part of the link, since there can be multiple authors.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO dev with FF57 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/33664308-cc6925a4-da9b-11e7-9d62-180c074c22b5.png)
