### ISSUE TITLE
View server logs in browser devtools

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4041]
The `addons-frontend` server logs are pretty hard to deal with in the shell console. We should try hooking up [Chrome logger](https://addons.mozilla.org/en-US/firefox/addon/chromelogger/) to view them in browser devtools. We can probably use this [express middleware](https://github.com/olahol/express-chrome-logger).

**Comment by willdurand** [comment]
If we switch to Pino (see #5826), then this might be a good way to solve this issue: https://github.com/willdurand/pino-devtools.
