### ISSUE TITLE
Themes menu option is not highlighted while accessing any theme category from homepage

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4043]
Steps to reproduce:
1. Load a theme category from homepage i.e. https://addons.allizom.org/en-US/firefox/themes/scenery/
2. Observe underlined option from the menu

Expected results:
"Themes" option is underlined.

Actual results:
"Explore" option is underlined.

Notes/Issues:
Verified on AMO-stage FF57(Win 7). Issue is reproducing on all servers.
Screenshot for this issue:
![2017-12-06_1311](https://user-images.githubusercontent.com/15685960/33658929-1da33410-da87-11e7-893c-45d1d2fe860f.png)

**Comment by muffinresearch** [comment]
This works if you navigate client-side via themes -> picking a category link.

**Comment by bobsilverberg** [comment]
The problem reproduces if you navigate to a category, then click the "Explore" link, and then use the back button to navigate back to the theme category. "Explore" is still underlined, even if you refresh the page. This also seems to happen for other types with categories (e.g., Extensions).

I will see if I can figure out the cause.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF58 (Win 10, Android 8.0.0)

![themescategories](https://user-images.githubusercontent.com/33448286/35912021-1b75433c-0c04-11e8-99e1-ca357ffc7ba9.png)
