### ISSUE TITLE
Loading an incomplete add-on causes purple/blank screen while logged in as an admin

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4045]
Steps to reproduce:
1. Load homepage while logged in https://addons.allizom.org/en-US/firefox/
2. Click on an hero banner that has no stage correspondent i.e. https://addons.allizom.org/en-US/firefox/addon/decentraleyes/
3. Refresh the page
4. Go back to homepage
5. Refresh the page

Expected results:
After step 2 a 404 page should be displayed.

Actual results:
After step 2 a purple page is loaded.
After step 3 the purple page is replaced with a Server Error page and user seems logged out.
After step 5 user seems logged in again.

Notes/Issues:
- issue is not reproducing while logged out.
- issue is also loaded for unexisting add-ons i.e. https://addons.allizom.org/en-US/firefox/addon/photo-screen-saver/

Verified on AMO-stage FF57(Win 7).
Video for this issue:
![login-logout](https://user-images.githubusercontent.com/15685960/33662176-8dc341e8-da93-11e7-8cc1-0e9e01041127.gif)

**Comment by kumar303** [comment]
@ValentinaPC from my observations, this only happens when you sign in using an admin account. For any other user account, it's not happening. Can you verify?

**Comment by kumar303** [comment]
The root cause is https://sentry.prod.mozaws.net/operations/addons-frontend-amo-stage/issues/776253/

<img width="969" alt="screenshot 2017-12-06 10 26 11" src="https://user-images.githubusercontent.com/55398/33672482-ea2315d6-da6f-11e7-93bf-4df7ad513531.png">

**Comment by ValentinaPC** [comment]
@kumar303 : Yes I can confirm that being logged out or being logged in with a non-admin account will not cause the issue.

**Comment by kumar303** [comment]
Another problem is that `decentraleyes` is an incomplete add-on meaning that it was not fully submitted through DevHub. This won't be happening in prod (for this specific add-on). Normal users can't see these add-ons but admins can.

```
$ ssh ...@olympia-web-amostage1...
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
>>> a = Addon.objects.filter(slug='decentraleyes')[0]
>>> a
<Addon: 521554: Decentraleyes>
>>> a.status
0
```

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF57(Win 7).
Postfix video:
![404](https://user-images.githubusercontent.com/15685960/33714806-fbd551b0-db58-11e7-9ad2-9d9f289bf7e1.gif)
