### ISSUE TITLE
Email link incorrect

### ISSUE THREAD

**Issue by wshuman3** [mozilla/addons-frontend#4046]
### Describe the problem and steps to reproduce it:
Received email with subject: Give your browser superpowers with extensions

### What happened?
Clicked link got 404'd. 

https://click.e.mozilla.org/?qs=36000c20f37b8afe56a7c9d2da7d84a2343b0c7237b74685b41918ecc2ac87d7339ee67ee3d43ae6743d651bf266260f4e7dcf773f838c0a

### What did you expect to happen?
See some trending extensions.

### Anything else we should know?
Nope.

**Comment by wagnerand** [comment]
Thank for the report. I fixed it.

Heads up to @devaneymoz that I changed the slug for the "Trending Extensions" collection from https://addons.mozilla.org/en-US/firefox/collections/mozilla/trending-extensions/ to https://addons.mozilla.org/en-US/firefox/collections/mozilla/trending-add-ons/ to make that link work.
