### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by 09wattry** [mozilla/addons-frontend#4048]
Trying to downgrade my SSL connection to be able to get into an old router via https. I followed this support link
https://support.mozilla.org/en-US/questions/1042061 and tried to download this add-on: https://addons.mozilla.org/firefox/addon/ssl-version-control/ . The add-on no longer exists and therefore I am unable to access my router.

**Comment by andymckay** [comment]
That add-on is not compatible with Firefox 57. You can make the changes to Firefox as recommended in first comment of that article on support.mozilla.org.
