### ISSUE TITLE
Show a 500 instead of a blank page for component errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4050]
### Describe the problem and steps to reproduce it:

Create a component that triggers an error like in https://github.com/mozilla/addons-frontend/issues/4045#issuecomment-349693123

(Note that you have to edit the code to do this.)

### What happened?

You will see a blank (dark purple) screen and the app will be unusable. See the screencast in https://github.com/mozilla/addons-frontend/issues/4045 . In the console you'll see something like:

<img width="608" alt="screenshot 2017-12-06 16 14 05" src="https://user-images.githubusercontent.com/55398/33689718-1cc7eff8-daa6-11e7-89e1-741559b099c7.png">

### What did you expect to happen?

You should see a 500 error page like for other errors. The app should still be usable.

### Anything else we should know?

This is a regression introduced by React 16. See https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html

Before React 16 the error might have broken the app in unexpected ways but I think some errors would have not broken the app (you'd just see it in the console).

**For QA**

Since reproducing this is hard, please check for general regressions in both AMO and Discopane. In particular, you could check that 404 pages still render the same.

**Comment by ValentinaPC** [comment]
Verified this on AMO-dev using FF57(Win 7).
Links that should return a 404 page, work as expected.

Not being able to find a 404 link from about:addons/Discovery Pane to see what happens - maybe you have a suggestion, @kumar303 ?

On the other hand, pages and redirection seems to work as expected from Add-ons Manager, too.

**Comment by kumar303** [comment]
I'm not sure either. Thanks for testing! If 404s work in AMO then it should be fine.

**Comment by vcarciu** [comment]
Marking as verified based on comments from above.
