### ISSUE TITLE
Indicator position for Flag options should be under Flag link 

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4053]
Steps to reproduce:
1. Load "All Reviews" page on your device i.e. https://addons.allizom.org/en-US/android/addon/evernote-web-clipper/reviews/
2. Click "Flag" option for a "Developer response"
3. Observe flag options indicator position

Expected results:
Indicator is under Flag link.

Actual results:
Indicator is under "Reply to this review" link, or in the middle of the page.

Notes/Issues:
- reproducing for any flag link, more confusing in this particular case.

Verified on AMO-stage FF57(Android 7)
Screenshot for this issue:
![2017-12-07_1207](https://user-images.githubusercontent.com/15685960/33710992-0b18fbc6-db4b-11e7-8080-b9e6a3cb6ecb.png)

**Comment by kumar303** [comment]
This won't be reproducible on large screens (like desktop). The problem is that the screen is small so when the flag menu opens, it is re-positioned to the center. 

It would be nice to fix the arrow but because of the re-positioning it would be really hard to fix.
