### ISSUE TITLE
Unusable "Reply to this review" link option for a Developer response

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4054]
Prerequisites:
User is logged with an admin account;

Steps to reproduce:
1. Load "All reviews" page for an add-on i.e. https://addons.allizom.org/en-US/firefox/addon/clip-to-onenote/reviews/
2. Observe link options for a Developer response

Expected results:
No "Reply to this review" option available.

Actual results:
Unusable "Reply to this review" link option.

Notes/Issues:
- a reply to a developer response is not possible - but still display the link; 
- also 2 developers replies for same review are not possible - that is why we **do not list** the "reply to this review" link in this case.

Verified on AMO-stage FF57(Win 7, Android 7)
Screenshot for this issue:
![2017-12-07_1210](https://user-images.githubusercontent.com/15685960/33711388-7e8f039c-db4c-11e7-9183-aed481aeb7ac.png)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev and AMO stage with FF59(Win10 and Android 8.0.0).
I used admin accounts and The Reply to this review url is no longer available. - edit my reply option is available
![removed reply to this review](https://user-images.githubusercontent.com/33448286/39524330-467d8a6c-4e21-11e8-9751-71d7f7665100.png)
