### ISSUE TITLE
Add-on name has layout issues in 'Read all reviews' page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4056]
Steps to reproduce:
1. Load 'All reviews' page for an add-on with a longer title (i.e. https://addons.allizom.org/en-US/firefox/addon/grammarly-spell-checker/reviews/)
2. Observe the add-on name displayed in the details section

Expected result:
Add-on name is wrapped correctly

Actual result;
Characters are pushed to the second row if the entire word does not fit on the first line

Notes: reproduced on all AMO servers with FF57 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/33716921-9f3805f8-db60-11e7-916a-fc4abcd2e959.png)
![image](https://user-images.githubusercontent.com/31961530/33716971-d72e544e-db60-11e7-8297-83755427930d.png)

**Comment by tsl143** [comment]
@tofumatt , can we close this against https://github.com/mozilla/addons-frontend/commit/4af23d304f4d11d2d6b51a96341aa33ed6b4a5e7 ?

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF57 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/34572418-003a80e0-f17a-11e7-8f0b-76654cc5c56e.png)

![image](https://user-images.githubusercontent.com/31961530/34572454-1c7035e8-f17a-11e7-9a61-10688310005a.png)
