### ISSUE TITLE
Unbroken description causes layout issues in Add-ons Manager

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4057]
Prerequisites:
- search results pref is set to point -dev;

Steps to reproduce:
1. Go to about:addons and search for an extension with unbroken description i.e. "Webext-hide"
2. Click on "More" link
3. Observe description

Expected results:
Description is wrapped.

Actual results:
Unbroken description causes layout issues.

Notes/Issues:
- summary behaves the same;

Verified on AMO-dev FF57(Win 7).
Video for this issue:
![unbr](https://user-images.githubusercontent.com/15685960/33719745-6cd9c9a2-db6a-11e7-8d34-97239d31c3f9.gif)

**Comment by kumar303** [comment]
Good catch. This is a bug in Firefox though, not `addons-frontend`. You can re-file it here: https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=Add-ons%20Manager

**Comment by ValentinaPC** [comment]
I though about that, but taking into consideration that this page shows description from AMO, and not from `manifest.json`.... I logged it here. but I can move it.

**Comment by kumar303** [comment]
That page gets data from the [addons-server](https://github.com/mozilla/addons-server/) API but it's then displayed using Firefox code. The display code is the issue here, not the data.

**Comment by ValentinaPC** [comment]
Closing this in favor of https://bugzilla.mozilla.org/show_bug.cgi?id=1413127 .
