### ISSUE TITLE
Release Notes won't be displayed when they contain some HTML tags

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4063]
Steps to reproduce:

1. Go to the details page of an addon that contains Release Notes written with some HTML tags (i.e.https://addons-dev.allizom.org/en-US/firefox/addon/test-of-today/)
2. Scroll down to the Release Notes section and observe the text included by the developer
3. Refresh the page and take another look into the Release Notes section

Expected result:
Release Notes are displayed

Actual result:
The notes have disappeared from their section

Notes: I was able to reproduce this issue by using the following HTML tags: `<ul> <ol> <li> <blockquote>`
Reproduces on all AMO servers with FF57 (Win 10 and Android 7.0)

![release notes](https://user-images.githubusercontent.com/31961530/33765758-091c11b8-dc23-11e7-85f3-10c655fad016.gif)

**Comment by kumar303** [comment]
I can reproduce but with slightly different STR:
- go to https://addons-dev.allizom.org/en-US/firefox/
- search for 'test of today'
- select the add-on to load its detail page
- refresh the page

**Comment by tsl143** [comment]
I am not sure, but this works if I replace `<p>` tag with `<span>` tag in [this](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Addon/index.js#L344).

One rationale to that is `<p>` tag can have only and only text content ([ref](https://html.spec.whatwg.org/dev/grouping-content.html#the-p-element)) and given example puts `<ul>` under `<p>` tag.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF57, (Win10)

![relnotes](https://user-images.githubusercontent.com/31961530/34879020-84c7dea8-f7b4-11e7-8e90-8954a58c6315.gif)
