### ISSUE TITLE
The operating system filter from the search result page is set to "All" when the sent platform attribute is linux

### ISSUE THREAD

**Issue by aswan** [mozilla/addons-frontend#4065]
Copied over from https://bugzil.la/1424270

Pre-requisites:
download and start this build: https://treeherder.mozilla.org/#/jobs?repo=try&revision=5297cd03d7b11b278e3439bf631b29962e7b0f25

Steps to reproduce:
1. Open about:addons
2. Enter any search term and hit the enter button
3. Observe the search results page

Expected results:
In the search result page the operating system filter is set to Linux.

Actual results:
The platform parameter is set to linux but in the search results page the operatig system filter is set to "All"

Notes/Issues:
Verified in Ubuntu 12.04 64 bit using the build provided in here: https://treeherder.mozilla.org/#/jobs?repo=try&revision=5297cd03d7b11b278e3439bf631b29962e7b0f25
please view the attached screenshot

![image](https://user-images.githubusercontent.com/3308522/33783866-5c2a01e0-dc13-11e7-974b-e418cd3e8dba.png)

**Comment by andymckay** [comment]
Works for linux, but not Linux.

**Comment by andymckay** [comment]
As per http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-platform

**Comment by aswan** [comment]
Hrm, I don't have my Linux VM handy at the moment but I bet we have this problem right now with the "See all N results" link at the bottom of the in-browser search page.  We also use the upper-case form in other places like discovery pane URLs, the old search API, SUMO URLs, etc.  Can we make AMO consistent with all the above or should we put a special hack for this case into the browser?

**Comment by ValentinaPC** [comment]
This was already tracked in https://github.com/mozilla/addons-frontend/issues/4064 .
Maybe we can close one of the issue.

**Comment by muffinresearch** [comment]
I see there are a few options:

* Update the frontend to allow for both Linux and linux
* Rewrite this Query string at the Nginx level

Both of those would result in duplicate content e.g. same content at a different URL, which isn't ideal and having to use rel-canonical would be a bit of a pain.

We could redirect at the nginx level, which would be better for avoiding duplicate content but then it would also require a change in Firefox so we don't depend on it permanently.

@aswan if we went the redirect route would you be able to update Firefox so the redirect is only used  temporarily or is it possible to just fix FF so we don't need the redirect at all?

**Comment by aswan** [comment]
> @aswan if we went the redirect route would you be able to update Firefox so the redirect is only used temporarily or is it possible to just fix FF so we don't need the redirect at all?

Well it is software so just about anything is possible, but this part of the URL is formatted with a standard Gecko routine (`Services.urlFormatter.formatURL()`) so it would involve some pretty gross ad hoc code to work around...

**Comment by muffinresearch** [comment]
@aswan Please can you let me know if there's params other than platform that additionally need this change? Are there values for `platform` that use title-casing too or is it just `Linux`?

Once we have a list I can look to pass this to ops to get a redirect setup.

**Comment by aswan** [comment]
Let's see, of course none of this is documented on the Firefox side but it looks like the substitution for OS comes from here:
https://searchfox.org/mozilla-central/rev/84cea84b12145d752e50ddca6be5462c38510e35/toolkit/components/urlformatter/nsURLFormatter.js#108
which comes from:
https://searchfox.org/mozilla-central/rev/84cea84b12145d752e50ddca6be5462c38510e35/toolkit/components/urlformatter/nsURLFormatter.js#108
And that comes from somewhere in the build system which is mostly a mystery to me :/
Empirically that has the value "Darwin" on macosx and it looks like it has a bunch of possible values that AMO doesn't know about (eg Solaris, a bunch of BSD variants).  I guess we're going to have a totally ad hoc mapping somewhere, if you want to bounce this back to Firefox we can maintain that list there...

**Comment by AlexandraMoga** [comment]
@aswan I see that this issue applies now to all platforms, not just linux.
Here is how it looks for Windows (10x64) and Mac (High Sierra Version 10.13.3)

[1] **Windows (10x64)**
![image](https://user-images.githubusercontent.com/31961530/37772371-163de404-2de3-11e8-812a-5081011e4bc2.png)

[2] **macOS High Sierra Version 10.13.3**

![image](https://user-images.githubusercontent.com/31961530/37772422-408a4b8a-2de3-11e8-886e-4fa320a94a21.png)

**Comment by jvillalobos** [comment]
Platform-specific add-ons should be rare, so I don't think we really need this filtering anymore. Maybe Firefox should stop sending the `platform` in its search string so it doesn't confuse people. /cc @mstriemer
