### ISSUE TITLE
Searched for Bitbucket extension, but target url is broken

### ISSUE THREAD

**Issue by velosipedist** [mozilla/addons-frontend#4071]
### Describe the problem and steps to reproduce it:

Searched for extension here
https://addons.mozilla.org/en-US/firefox/search/?q=bitbucket

Passed to this result
https://addons.mozilla.org/en-US/firefox/addon/bitbucket-server-reviewers/?src=api

### What happened?
I see an error page

### What did you expect to happen?
To see an extension page

### Anything else we should know?
Firefox 57 ¯\_(ツ)_/¯

**Comment by tsl143** [comment]
Adding to this, this works on legacy website

<img width="983" alt="image" src="https://user-images.githubusercontent.com/5318732/33910005-5b105662-dfb3-11e7-9b47-d6d2cc5bfd26.png">

**Comment by kumar303** [comment]
Hi. Thanks for the bug report. I opened an API issue to investigate this: https://github.com/mozilla/addons-server/issues/7132

**Comment by muffinresearch** [comment]
Looks like the dependent issue was resolved albeit the add-on mentioned in the STR is now at different URL https://addons.mozilla.org/en-US/firefox/addon/bitbucket-server/
