### ISSUE TITLE
Vertical scroll-bar for some languages in add-ons/themes shelves sections

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4074]
Steps to reproduce:
1. Load AMO-dev homepage using "Japanese" https://addons-dev.allizom.org/ja/firefox/
2. Observe Add-ons/Themes shelves section

Expected results:
There are no display or layout issues.

Actual results:
There is a vertical scroll-bar in this sections.

Notes/Issues:
- reproducing also for https://addons-dev.allizom.org/te/firefox/

Verified on AMO-dev FF57(Win 7). Reproducing on all AMo servers.
Screenshots for this issue:
![2017-12-13_1458](https://user-images.githubusercontent.com/15685960/33940033-1bfc7510-e016-11e7-87b5-475c7410888d.png)

**Comment by muffinresearch** [comment]
This appears to be windows specific.
