### ISSUE TITLE
Can't get to installed theme page

### ISSUE THREAD

**Issue by s777s** [mozilla/addons-frontend#4079]
### Describe the problem and steps to reproduce it:
A few days ago I've clicked Customize... -> Themes -> Suggested and choosed theme. At page about:addons I can see the theme, that I am "wearing" ("Space Fantasy" by fx5800p), but can't get to its page.

### What happened?
When I click to "Homepage: https://addons.mozilla.org/en-US/firefox/addon/space-fantasy/", I see "Sorry, but we can't find anything at the address you entered.", Page not found error.
### What did you expect to happen?
Only a few days have passed (Last update 11 December, today was 13 December), so I expected to get to the themes page.
### Anything else we should know?
The theme is licensed under CC-BY-SA, so I just wanted to download the whole image from the theme and check another works by fx5800p.

**Comment by jvillalobos** [comment]
It's possible that the theme was removed by the developer, which is the reason you can't find it anymore.

**Comment by s777s** [comment]
So, you think that the cool theme was created at 11 december, I've installed it and it was removed 1-2 days later? I think, there may be some mistake...

**Comment by s777s** [comment]
May I somehow find the author? I want ask him the whole picture from the theme.
