### ISSUE TITLE
Incorrect page numbers don't return an error in "All reviews" pages

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#4081]
Steps to reproduce:
1. Load https://addons-dev.allizom.org/en-US/firefox/addon/adblock-edge/reviews/?page=2
2. Change the page number to "0" or a random letter i.e. "x"

Expected results:
A 404 page is displayed.

Actual results:
Page 1 is displayed.

Notes/Issues:
- not reproducing in search results pages;
- not reproducing if the number you enter is bigger than the max page

Verified on AMO-dev FF57(Win 7). Reproducing on all AMO servers.
Video for this issue:
![pagen](https://user-images.githubusercontent.com/15685960/33996141-f3b64c92-e0e8-11e7-91ff-b39bfe31e77b.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![notfound](https://user-images.githubusercontent.com/1583842/36313614-b2fc8c0a-133a-11e8-8523-9c2266e5bff8.gif)
