### ISSUE TITLE
Implement anti-spam measures for developer support email addresses

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4082]
See: https://github.com/mozilla/addons/issues/588

**Comment by mrj** [comment]
Published my add-on. Spam flood began soon after. Yes to JavaScript email encoding.

**Comment by caitmuenster** [comment]
When discussing this on IRC, @kumar303 noted that this isn't a good first bug and recommended closing this issue because of improvements in spam filtering.

**Comment by kumar303** [comment]
By *improvements in spam filtering* I just meant it's not so important to hide email addresses on the Internet these days -- filtering spam is mostly a solved problem. We also haven't received any other complaints about the lack of email obfuscation so it's apparently not much of an issue for others.
