### ISSUE TITLE
'Featured shelf' is not hidden in homepage when no featured add-ons are available

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4084]
STR:

1. Go to AMO homepage while using 'Add-ons for Android'  (i.e. https://addons-dev.allizom.org/en-US/android/)
2. Observe the featured shelf 

Expected result:
Featured shelf is hidden when no featured add-ons are available

Actual result:
An empty featured shelf is displayed instead

Notes:
<li> reproduced on AMO-dev and stage with FF57 (Win10 and Android 7.0) </li>
</br>

![image](https://user-images.githubusercontent.com/31961530/34035170-d9e60c98-e189-11e7-8c8c-251670f1a7ef.png)

**Comment by willdurand** [comment]
It is a problem with the data on - dev, there must be data for this shelf and it should always be visible.

**Comment by shikhar-scs** [comment]
@AlexandraMoga If this issue is still up, can I please work on this?

**Comment by willdurand** [comment]
I believe this is either fixed or no longer valid.
