### ISSUE TITLE
Unbroken strings are not wrapped for Release Notes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4086]
Steps to reproduce:  

 1. Log into AMO and go to Developer Hub (i.e. https://addons-dev.allizom.org/en-US/developers/)
 2. Click one of your submitted add-ons
 3. In the  Manage Status&Versions section click the Version of your ad-on (such as https://addons-dev.allizom.org/en-US/developers/addon/swarrand/versions/1533356)
 4. Insert a long unbroken text in the Version Notes and Save Changes
 5. Click on View Listing and observe the Release Notes field

Expected result:
Text is wrapped 

Actual result:
Text is not entirely displayed and appears cut

Notes:
Reproduced on both AMO-stage and dev with FF57(Win 10)
Copied from addons-server [#7128](https://github.com/mozilla/addons-server/issues/7128#issuecomment-352232259)
![release notes](https://user-images.githubusercontent.com/33448286/33887271-ebab6552-df51-11e7-97a6-57c78c83886a.png)

**Comment by ioanarusiczki** [comment]
This issue is verified on AMO dev and stage with FF 58 (Win10). 

![release notes](https://user-images.githubusercontent.com/33448286/35671986-aa4bdd1e-0745-11e8-9e67-c3038f02e06d.png)
