### ISSUE TITLE
AMO homepage has layout issues for German on smaller screen sizes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4087]
STR:

1. Load AMO homepage in responsive design (~720 - 750 width)
2. Change your locale to Deutsch
3. Observe the layout of the Collections shelf (Customize the way Firefox works...)

Expected result:
There are no layout issues

Actual result;
There is little to no spacing between the Collection titles

Notes:
- reproduced on all AMO servers with FF57 Win10 and Android 7.0 (tablet).

![image](https://user-images.githubusercontent.com/31961530/34110069-36ece7dc-e40e-11e7-9404-4518457dff13.png)

**Comment by himanish-star** [comment]
@AlexandraMoga , I can fix this. May I ?

**Comment by muffinresearch** [comment]
@himanish-star if you are still interested in looking at this then feel free - please let me know if you have any questions. When you have a PR please file it referencing this issue with "Fixes #ISSUE_NUMBER".  Thanks!

**Comment by himanish-star** [comment]
@muffinresearch, Thanks. I am currently a bit occupied elsewhere :sweat_smile: . So if someone else wants to work on this they can surely move ahead. In the meanwhile if I find some time, I'll surely work on this and file a PR.

**Comment by muffinresearch** [comment]
@himanish-star no problem - I've updated the labels and this is open for other contributions.

**Comment by wagnerand** [comment]
@pwalm Could you advise what we'd do best in this case?

**Comment by pwalm** [comment]
Here's a layout I mocked up for skinnier view ports that should accommodate longer text strings/localization:
<img width="980" alt="screen shot 2018-03-02 at 1 53 36 pm" src="https://user-images.githubusercontent.com/6797635/36923791-3948abc2-1e21-11e8-83c7-48fd86d5a92b.png">

**Comment by hritvi** [comment]
Hey @caitmuenster I would like to work on this issue...

**Comment by championshuttler** [comment]
Hi @hritvi  thanks for your interest. Go for it! If you need any help, please feel free to ask here :smile:

**Comment by willdurand** [comment]
Hi @hritvi, I just saw [your Pull Request](https://github.com/mozilla/addons-frontend/pull/5974) for this issue. Thank you!

Yet, I don't think we should modify the CSS breakpoints, because that impacts everything, not just what we're trying to fix. I think we should rather update the CSS for the `Card` (or the closest component possible).

**Comment by hritvi** [comment]
Hey @willdurand. Thanks for the quick review. 
I agree with you on CSS Breakpoints. Would update my pull request soon.

**Comment by willdurand** [comment]
Awesome, thanks for your contribution @hritvi!

**Comment by AlexandraMoga** [comment]
I think this patch might have broken the Theme categories section from the homepage:

This is for full size screens
![image](https://user-images.githubusercontent.com/31961530/45365332-f5742280-b5e4-11e8-9633-e9b19dd3150a.png)

Medium size:
![image](https://user-images.githubusercontent.com/31961530/45365394-19376880-b5e5-11e8-921f-8b4fd6414790.png)

**Comment by willdurand** [comment]
oh noes... it could be this line: https://github.com/mozilla/addons-frontend/pull/5974/files#diff-60639a955bb764f0dc57c23a34ffbd85R135

**Comment by hritvi** [comment]
oh sorry... I would change it right now...

**Comment by willdurand** [comment]
I am looking into it now

**Comment by willdurand** [comment]
> oh sorry... I would change it right now...

@hritvi no worries, it is fine and that's why we have QA

**Comment by willdurand** [comment]
@hritvi I just saw your new patch. Thanks for that! We are going to revert the first patch, and then you will be able to submit your patch again along with the second fix. We'll try to make sure everything works well before merging :)

**Comment by willdurand** [comment]
@hritvi reverted! Now (and if you like) you can submit a new PR with your previous changes + your fix in #6211. I can help you with that if you need, just let me know!

**Comment by willdurand** [comment]
We usually don't revert commits but we freeze the code in 30 minutes (meaning the code in `master` in 30 minutes will go live in two days). That's why we prefer reverting your patch, it gives everyone more time to work on it and test it before everyone can see it.

**Comment by willdurand** [comment]
awesome, thanks @hritvi!
