### ISSUE TITLE
Report abuse option has layout issues for German on smaller screen sizes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4090]
STR:

1. Go to AMO homepage in responsive design mode (~750 - 900 width)
2. Set your locale to Deutsch
3. Select an Add-on to view its listing page (i.e. https://addons-dev.allizom.org/de/firefox/addon/awesome-screenshot-plus-/)
4. Go to the rating section and click on Report abuse button

Expected result:
Report abuse section expands with no layout issues

Actual result;
There is no spacing between "Cancel" and "Send abuse report" buttons

Notes:
- reproduces on all AMO servers with FF57, Win10 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/34113905-e736fbc2-e419-11e7-87b7-3c29d0ef11f1.png)

**Comment by willdurand** [comment]
This has been fixed I believe.
