### ISSUE TITLE
Loading disabled add-on page flashes add-on name on tab title

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#4095]
Load the page for a disabled add-on, like [this one](https://addons.mozilla.org/addon/starwars-123movies-torrent/). The name of the add-on appears as the tab title, briefly, and changes to "Add-ons for Firefox". Since disabled add-ons can contain abusive content, this behavior should be flipped, so the name appears when it's known the add-on listing will show up.

**Comment by kumar303** [comment]
The component needs to fetch the add-on before it can see that it's disabled (which would render a title) but this fetch/render happens on the server so the client should never see a title. Weird.

**Comment by muffinresearch** [comment]
Without JS this currently looks like this:

<img width="877" alt="screenshot of 500" src="https://user-images.githubusercontent.com/1514/34563441-90d4783e-f14a-11e7-9728-8355ad04f6fa.png">

The title of the server render is the add-on. This is overridden when JS kicks in and renders the 500 like so:

<img width="1387" alt="add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/34563467-b1469bc4-f14a-11e7-9763-ee31d42b563f.png">

**Comment by muffinresearch** [comment]
Since this is a 500 it shouldn't be indexed. But in any case we should look to get server rendered 500s working for a case like this.
