### ISSUE TITLE
removed link

### ISSUE THREAD

**Issue by ZealotTKO** [mozilla/addons-frontend#4098]
### Describe the problem and steps to reproduce it:

click hyperlink https://www.cnet.com/how-to/how-to-customize-firefox-keyboard-shortcuts/
find removed content
### What happened?
hyperlink contains missing content
### What did you expect to happen?
hyperlink contains download

**Comment by andymckay** [comment]
That article is from 2011 and links to an addon that is no longer compatible with Firefox. https://addons.mozilla.org/en-US/firefox/addon/customizable-shortcuts/

There's not a lot we can do about articles from 2011 linking to old software I'm afraid.

A search for "keyboard" or "shortcuts" on AMO might help you find some other alternatives.
