### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by ngroon** [mozilla/addons-frontend#4099]
### Describe the problem and steps to reproduce it:

Followed the link on the Secret Server Login Helper extension page to the new version and received a page not found message.

### What happened?
Received page not found error

### What did you expect to happen?
The new extension version installation page would come up so I can install it

### Anything else we should know?

Originating page: https://addons.mozilla.org/en-US/firefox/addon/secret-server-login-helper/
Destination link: https://addons.mozilla.org/en-US/firefox/addon/secret-server-login-assist-2/
![image](https://user-images.githubusercontent.com/13801592/34261633-6b785c70-e62f-11e7-8ec8-5550e0c5de1a.png)

**Comment by jvillalobos** [comment]
It looks like the add-on was taken down due to a review issue. We're talking to the developer about this and the add-on should be back soon.
