### ISSUE TITLE
Sticky metrics tracking

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#41]
In bug https://bugzilla.mozilla.org/show_bug.cgi?id=1191887 it was requested that we do sticky metrics tracking. Since we are re-doing the disco pane, tracking here so we don't forget about it.

**Comment by andymckay-limited-access** [comment]
Asking in bugzilla to find out what people actually want.

**Comment by muffinresearch** [comment]
The PR in #513 uses the same tracking id as we currently do and adds `install` and `uninstall` events. The uninstall events are new to this disco pane as the only one only sent events for installs.
