### ISSUE TITLE
Changing the locale after editing a review will not show the updated version of the review

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4109]
STR:

1. Go to AMO homepage and select an add-on to view its details page (i.e. https://addons-dev.allizom.org/de/firefox/addon/dancing-candy-canes/)
2. Navigate to the rating section and leave a review for this add-on
3. Click on 'Read all reviews' and verify that your review was listed 
4. Change your locale
5. With the new locale, click on the option to edit your review
6. After submitting the review update, re-set the previous locale
7. Check if your review is updated

Expected result:
The edited review is visible after changing back to the previous locale

Actual result:
After re-setting the locale, the original version of your review is displayed

Notes:
- any locale different than the one in which the review was edited will display the previous version of the review
- refreshing the page will not solve the issue
- issue is reproducing also when editing a developer reply
- reproduced on all AMO servers with FF57 Win10 and Android 7.0

![reviews](https://user-images.githubusercontent.com/31961530/34410710-cd018a7e-ebda-11e7-8600-b8ae6c93ea90.gif)

**Comment by muffinresearch** [comment]
This seems like it might a caching issue - but it needs more investigation to find out what's going on here.

/cc @diox

**Comment by muffinresearch** [comment]
There seems to be an issue with state, I see that the server-rendered page has the correct data. However when the page is updated on the client the JS reverts the review text to the previous content that was there before the edit!

**Comment by muffinresearch** [comment]
I had updated the review copy from 'test' to 'test test'. But after the page loads I see this in the console:

<img width="670" alt="bewertungen_fur_dancing_candy_canes_ _add-ons_fur_firefox" src="https://user-images.githubusercontent.com/1514/35819875-e52b6612-0a9b-11e8-84ef-07d9dd1521e5.png">

**Comment by muffinresearch** [comment]
Looks like the API is serving stale content.  I see the pre-edited data in the API response JSON.

@diox any ideas?

**Comment by muffinresearch** [comment]
FWIW I'm not sure the locale has anything to do with this issue.

**Comment by diox** [comment]
It could be because of the locale somehow, because even though we don't expose it as such, a rating body is actually a translated field behind the scenes - just one that we never bother to expose multiple translations of. (dates back from when AMO was offering the possibility to translate ratings using google translate)

**Comment by diox** [comment]
And indeed:
```
>>> a = Addon.objects.get(pk=55625)
>>> a
<Addon: 55625: Dancing Candy Canes>
>>> ra = a.ratings.all()[0]
>>> ra
<Rating: test test>
>>> ra.body 
<Translation: test test>
>>> ra.body_id
8160135L
>>> Translation.objects.filter(id=8160135)
[<Translation: test>, <Translation: test test>]
```

Clearly an addons-server bug, and tied to the locale. We saved 2 different translations, each with a different locale. This is going to be tricky to fix properly...

**Comment by muffinresearch** [comment]
@diox Thanks for digging into it.  Would it make sense to move/file an issue on addons-server with these specifics to supercede this one?

**Comment by diox** [comment]
Yeah, please do that.

**Comment by muffinresearch** [comment]
Moved to https://github.com/mozilla/addons-server/issues/7517
