### ISSUE TITLE
A link redirect me to the Firefox add on

### ISSUE THREAD

**Issue by SHUBHAMDAVE001** [mozilla/addons-frontend#4110]
### What happened?
when I try to go another link it redirects me to the Firefox add-on

### What did you expect to happen?
I expect it to go to another link
### Anything else we should know?
someone else is using this link to redirect the users.

**Comment by kumar303** [comment]
Thanks for the bug report. Which add-on? Please provide a specific URL.

**Comment by SHUBHAMDAVE001** [comment]
hey there
i m sending u the link
this was the link which redirects me to the add-on page
<https://addons.mozilla.org/en-US/firefox/addon/download-tiger-zinda-hai-hd/>


[image: --]

Shubham Dave
[image: https://]about.me/shubham.dave
<https://about.me/shubham.dave?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>

**Comment by kumar303** [comment]
Hi. Thanks for the details. What happened is that someone who is not affiliated with Mozilla linked to an add-on that has been disabled by an administrator. There is nothing we can do about this, sorry. Thank you for taking the time to submit a bug report.

**Comment by SHUBHAMDAVE001** [comment]
okk



[image: --]

Shubham Dave
[image: https://]about.me/shubham.dave
<https://about.me/shubham.dave?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=chrome_ext>
