### ISSUE TITLE
Create a shared Select component

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4114]
Since the UI for adding add-ons to a collection (https://github.com/mozilla/addons-frontend/issues/2768) needs a select box, we need to move the current select styles to a shared component.

For QA: please test the functionality and look and feel of the [current search filters](https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=ad+blocker) (the select boxes) for regressions.

**Comment by vcarciu** [comment]
No regressions were found so far in this area. I will mark the issue as verified.
