### ISSUE TITLE
Support next page API URLs

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4116]
For adding add-ons to a collection (https://github.com/mozilla/addons-frontend/issues/2768) we need to load multiple pages of [user collections](https://addons-server.readthedocs.io/en/latest/topics/api/collections.html#list). This requires the following adjustments to our core `callApi()` function:

* It should accept absolute URLs since that's what the API returns in the `next` parameter
* It should preserve query string parameters in API endpoint URLs

For QA: It would be helpful to test some pages with query string parameters for regressions, such as the [search page](https://addons.mozilla.org/en-US/firefox/search/?platform=mac&q=ad+block).

**Comment by AlexandraMoga** [comment]
I've looked for possible regressions around query string parameters but no issues were noticed.
I will mark this as verified fixed (AMO-dev, FF57, Win10)
