### ISSUE TITLE
Search filters are reset by a new search

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4120]
### Describe the problem and steps to reproduce it:

* Make a search in the new frontend
* Change the filter for type to "Extensions" 
* Add another search term in the search box and submit

### What happened?

* The search results include All add-on types and the filter was reset.

### What did you expect to happen?

* The search filters I selected should stay selected.

**Comment by muffinresearch** [comment]
This hurts search usability so marking as p2

**Comment by kumar303** [comment]
This is pretty bad. It's not just the type filter -- none of the filters are remembered between searches. Well spotted.

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev, FF57 (Win 10 and Android 8.0)
The filters are preserved when typing a new search. 

![filter not reset win](https://user-images.githubusercontent.com/33448286/35278453-c4acc78a-0052-11e8-9240-5dffc7c0b632.gif)


![filter not reset](https://user-images.githubusercontent.com/33448286/35278463-cf540c3e-0052-11e8-8cc0-e8925b7994bb.gif)
