### ISSUE TITLE
Empty shelves are displayed when loading AMO dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4121]
Steps to reproduce:

1. Log into AMO dev (i.e.https://addons-dev.allizom.org/en-US/firefox/)
2. Observe Featured extensions and Popular extensios shelves
     
Expected result:
The shelves are populated with results.

Actual result:
The shelves are empty.
![empty shelves](https://user-images.githubusercontent.com/33448286/34568799-98d10708-f16f-11e7-809a-7bbb9cb9ce42.png)

Notes:
Reproduced on AMO dev with FF57(Win 10)

**Comment by tofumatt** [comment]
Either way it's not a bug; just a lack of good data. I'd gather a new add-on has simply been added in the meantime.
