### ISSUE TITLE
Cannot sign in to dev server: invalid assertion

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4123]
### Describe the problem and steps to reproduce it:

Try to sign in to https://addons-dev.allizom.org/en-US/firefox/

### What happened?

The Firefox Accounts page shows the error *Invalid assertion* for any valid user account

### What did you expect to happen?

It should log in and redirect to AMO

### Anything else we should know?

<img width="1553" alt="screenshot 2018-01-04 09 20 04" src="https://user-images.githubusercontent.com/55398/34570237-b63d1ed8-f130-11e7-8933-addb2f4ac6a4.png">

**Comment by AlexandraMoga** [comment]
This issue was also reported on addons-server. See [#7212](https://github.com/mozilla/addons-server/issues/7212)

**Comment by kumar303** [comment]
Ah, thanks, I'll dupe it
