### ISSUE TITLE
Remove duplicate UI tests from Circle CI build

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4124]
We run UI (functional) tests in two places:
* TravisCI
* CircleCI

The CircleCI implementation is older and is not connected to the TravisCI one. Let's delete them from CircleCI for now.

Here is an example of a recent failure which is likely due to inexact pip dependencies https://circleci.com/gh/mozilla/addons-frontend/5678#tests/containers/0

**Comment by AlexandraMoga** [comment]
Please include some STR or the label "qa: not needed"
