### ISSUE TITLE
Followed link to new-tab-speed-dial extension, but target url is broken 

### ISSUE THREAD

**Issue by m2xw** [mozilla/addons-frontend#4127]
### Describe the problem and steps to reproduce it:
Followed this link from the developers website:
https://addons.mozilla.org/en-US/firefox/addon/new-tab-speed-dial/

### What happened?
Leads to error page

### What did you expect to happen?
To see the extension page

### Anything else we should know?
Developers website:
https://speeddial2.com/

**Comment by kumar303** [comment]
Do you still see an error page? This page loads fine for me without an error: https://addons.mozilla.org/en-US/firefox/addon/new-tab-speed-dial/

**Comment by kumar303** [comment]
If you still see an error page, are you signed in? Try signing out.

**Comment by m2xw** [comment]
You are right, works just fine now. 

Thanks for looking into it tough.

**Comment by 360andy** [comment]
Still no access, the above link indicates the file is missing.
