### ISSUE TITLE
Expose Hidden Metadata in Search Engine Results 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-frontend#4129]
When you search for an add-on on a search engine like Google, you can see the extension's average ratings from Google Play and the Chrome Store (if the add-on is available on multiple browsers), but not the average rating from AMO. An example is below: 

![screen shot 2018-01-04 at 3 06 12 pm](https://user-images.githubusercontent.com/23342476/34588323-32f8a124-f161-11e7-8458-925dd17b402c.png)

Could we expose an extension's AMO rating on search engine results?

**Comment by jvillalobos** [comment]
This could be related to https://github.com/mozilla/addons-frontend/issues/3969, but maybe Google is using other metadata.

**Comment by tsl143** [comment]
@jvillalobos Google needs specific sets of `itemprops` metadata in HTML

here - https://developers.google.com/search/docs/data-types/review
I will try to work on this.

**Comment by kumar303** [comment]
Thanks @tsl143 ! This seems useful

**Comment by rraue** [comment]
I think its a great idea to increase ctr in search and therefor rankings and clicks to our site. I suggest to implement this via js+ld and not via Microdata, as Google (even if the chrome store uses microdata) preferres js+ld and we will need it for other snipped optimizations. 

As a example it used Adblock plus:

```
<script type="application/ld+json">
{
  "@context": "http://schema.org/WebApplication",
  "@type": "WebApplication",
	"name": "Adblock Plus",
	"url": "https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/",
        "image": "https://addons.cdn.mozilla.net/user-media/previews/thumbs/137/137084.png?modified=1530207986",
        "version": "3.2",
        "applicationCategory": "http://schema.org/OtherApplication",
        "interactionCount": "UserDownloads:10879887",
        "operatingSystem": "Firefox",
        "description": "Blocks annoying video ads on YouTube, Facebook ads, banners and much more. Adblock Plus blocks all annoying ads, and supports websites by not blocking unobtrusive ads by default (configurable).",

        "offers": {
             "@type": "Offer",
             "price": "0",
             "priceCurrency": "USD",
             "availability": "http://schema.org/InStock"
                       }
        "aggregateRating": {
	    "@type": "AggregateRating",
            "ratingValue": "4.6",
            "ratingCount: "7774"
                        }
</script>
```

I used all information Chrome uses in the webstore as well. There are more usefull information, we could add, but for a first test, if this really will show up in search results, we should be fine with this. Google is using here not the Review schema, but WebApplication which is a subsidary of SoftwareApplication, which fits better, as reviews are just for local business, music, books and recipes. SoftwareApplication is still beta, but as Chrome is using it, very likely to show up: https://developers.google.com/search/docs/data-types/software-app

**Comment by rraue** [comment]
Another though, based on this[ study](https://www.brightlocal.com/learn/review-search-click-through-study/#organicserp) we should probably only add add-ons with a positive rating above 4.0, as it seems that listings with three stars get a worse ctr than ones without any rating. 

But I dont know if we can do this, as we need to update ratings regularly anyway and it might look suspicious to sometimes have them and sometimes not for the same item. So if a add-on has one week 4.0 and the next week 3.9 and therefor one week a rating and one week not, thats weird. Any thoughts on that?

**Comment by jvillalobos** [comment]
One thing we can do is expose the rounded star rating, rather than the more accurate measurement. So, `3.9`, `4.0`, `4.1`, etc. would all be exposed as `4.0` for search engines (we round to the nearest half-star). That would decrease the frequency of change.

I think it's okay to set a minimum of 4 stars before exposing them to search engines.

**Comment by jvillalobos** [comment]
Then I guess we should figure out if Google does any rounding. If you expose `3.9`, does Google round it down to `3`?

Assuming the answer to the above is yes, then it takes about 60 reviews for a 1-star review to not drop you from 4 to 3.9.

**Comment by rraue** [comment]
Google doesnt round, they even show half stars. We can see this in the screenshot above, where the Rating of 4.4 is shown in the search results as 4 and a half star. I found a addon in teh chromestore with a rating of 3.9 and it is shown as 4 stars, with the exact rating aside:

<img width="609" alt="screen shot 2018-08-13 at 13 02 38" src="https://user-images.githubusercontent.com/36700618/44028160-4d676e00-9ef9-11e8-8e61-405027a1879a.png">

So I think we are safe showing extentions down to 3.3 and shouldnt show ones with a lower rating than 3.2.

<img width="611" alt="screen shot 2018-08-13 at 13 04 28" src="https://user-images.githubusercontent.com/36700618/44028238-83297dbc-9ef9-11e8-9396-65f59ab41ac7.png">

**Comment by willdurand** [comment]
> **Important is, that "url" is localised as well, else we might get a internationalization problem. So on /locale/ it should be as well "url": "[addons.mozilla.org/locale/firefox/addon/adblock-plus](https://addons.mozilla.org/locale/firefox/addon/adblock-plus/)"**

what do you mean?

**Comment by willdurand** [comment]
> But I dont know if we can do this, as we need to update ratings regularly anyway and it might look suspicious to sometimes have them and sometimes not for the same item. So if a add-on has one week 4.0 and the next week 3.9 and therefor one week a rating and one week not, thats weird. Any thoughts on that?

Does Google always provide ratings for each extension?

**Comment by willdurand** [comment]
@rraue @jvillalobos about rating data, my understanding is that we should actually expose ratings for all add-ons, using the raw numbers (no rounding) because that's what Google does too. In addition, it does not seem good to sometimes expose ratings and sometimes not if rating value reaches a threshold.

**Comment by rraue** [comment]
@willdurand Googles pages itself aren't usually a good example for best practice SEO, as the search team and the teams building pages do not communicate. For good reasons. Keeping that in mind, Amazon or Apple are usually better websites to look at, as they both have a really good and big Seo team. And at Amazon I can't find any rating below 3 in search results and as well none with very little ratings.

And therefore I would go with the original plan and add the ratings-code only to extensions with an average rating above 3.3. 

Below 3.3 we shouldn't show any rating code in js+ld, as it definitely will show up as a warning in search console and then it will be harder to filter for real errors and to fix them.

**Comment by willdurand** [comment]
Ok, I've added the threshold for the ratings and we don't plan to expose the interactive count (# of downloads).
