### ISSUE TITLE
Wunderlist extension link is broke

### ISSUE THREAD

**Issue by saldarriaga** [mozilla/addons-frontend#4131]
When I click on link Download For Firefox from https://www.wunderlist.com/download/ site... It sends me to https://addons.mozilla.org/en-US/firefox/addon/add-to-wunderlist/

Attached firefox Add-ons screenshot
![wunderlist-extension-link-broke](https://user-images.githubusercontent.com/753485/34628089-1eae4d6a-f231-11e7-8af7-d79a0b6a76ab.png)

**Comment by andymckay** [comment]
The author of the add-on has chosen to remove the add-on from the site. Please contact the add-on author about why they have done this: https://www.wunderlist.com/contact/
