### ISSUE TITLE
clicked on link from an old email from mozilla, got broken link, filing bug report per suggestion of page

### ISSUE THREAD

**Issue by danh1** [mozilla/addons-frontend#4132]
### Describe the problem and steps to reproduce it:

Click on this link
https://urldefense.proofpoint.com/v2/url?u=https-3A__click.e.mozilla.org_-3Fqs-3D4ae5965b153a60c73ebf99e38ac8cd51637cd52336b9d1f219978ba56daf70cf8564cc3e61408992&d=DgMDaQ&c=B73tqXN8Ec0ocRmZHMCntw&r=uLEi1uR4HlsB_MZQw9a_uiZwtcATXFnZ1W2XYK7CZj4&m=ZLU6uUpERFVD6oO5FwvuyDatSkWGOnx50zoZRmGV3I0&s=2NwfRMqMmGafhnGNGe1oDWgWcvutzFsznVB_X60dHHs&e=

### What happened?
I arrived at some firefox page which suggested that i file an issue.  ("Please", it said.)  So i'm filing.

### What did you expect to happen?
I expected to see the top 5 add-ons for 2016, per the subject of the email from mozilla.

### Anything else we should know?

Normally i would not file a bug, and rather just ascribe it to the tendency of links to rapidly rot.

However, this email i got was from mozilla, and it landed me on some mozilla page that specifically asked me to file an issue, so i am.

Here's the original email:

From: Firefox <Mozilla@e.mozilla.org>
Sent: Friday, January 13, 2017 1:41 PM
To: Hitt, Dan
Subject: The year's best add-ons
 
Firefox
Top 5 add-ons of 2016
Wait, what's an add-on again? Add-ons boost your Firefox with special features, shortcuts, and other superpowers. Last year, Firefoxers used them to download videos, block ads, stay anonymous online, and more. Imagine what they can do for you.
CHECK THEM OUT
Have a shiny new device?
Download a shiny new version of Firefox.

  	FIREFOX FOR DESKTOP 	 
  	FIREFOX FOR ANDROID OR iOS 	 
You can update your email preferences at any time by clicking the link below.
Modify your preferences

You're receiving this email because we think you’re neat, AND you subscribed to hear from us. If our newsletters aren’t sparking joy, we’ll understand if you Unsubscribe.
A tidy inbox frees the mind.

331 E. Evelyn Avenue Mountain View CA 94041
Legal • Privacy

 

  |  
-- | --

**Comment by tofumatt** [comment]
That doesn’t look like a legitimate Mozilla email to me. Or it’s a bit old? The current year is 2018. At any rate this issue is a bit unclear to me so I’m going to close it.

**Comment by tofumatt** [comment]
Oh sorry I just saw in the title you flagged the email as old. Still, I’d say best to leave this issue closed.

**Comment by danh1** [comment]
That's fine with me.

Link rot is certainly our current state of the art, and i wouldn't have filed an issue except that the page i landed on specifically said "please file an issue".  :) :)
