### ISSUE TITLE
404 Bookmarks

### ISSUE THREAD

**Issue by 13regent** [mozilla/addons-frontend#4133]
### Describe the problem and steps to reproduce it:

Went looking for add-on 404 Bookmarks and I cannot find this extension

### What happened?

Went to page at 404 Bookmarks is gone: https://addons.mozilla.org/en-US/firefox/addon/404-bookmarks/?src=api

### What did you expect to happen?

Expected to find add-on

**Comment by caitmuenster** [comment]
It looks like there was an issue with a recent update to 404 Bookmarks. We're working with the developer to resolve it.
