### ISSUE TITLE
Zoho notebook webclipper missing

### ISSUE THREAD

**Issue by juzQrios** [mozilla/addons-frontend#4134]
### What happened?
Page not found
### What did you expect to happen?
To find notebook webclipper add-on
### Anything else we should know?

https://addons.mozilla.org/en-GB/firefox/addon/notebook_web_clipper/

**Comment by tofumatt** [comment]
cc @jvillalobos to see if he can shed some light on why the add-on was unlisted, but beyond that it's up to the add-on developer to fix this issue. I can't tell if the add-on was disabled by the author or not, but any disabled add-on will show a 404.

**Comment by jvillalobos** [comment]
It looks like it's under review and needs to resolve some issues before it's published again.
