### ISSUE TITLE
Add-on Review Pop-up: Font inconsistency

### ISSUE THREAD

**Issue by fayetandog** [mozilla/addons-frontend#4135]
### Describe the problem and steps to reproduce it:

1. Go to any add-on
2. Navigate to 'Rate your experience'
3. Click on the stars for your rating

### What happened?
The font for Placeholder text, form text and submit review text is different from the rest of the site (which uses Fira Sans)

### What did you expect to happen?
Have the same font as the rest of the pages

### Anything else we should know?
![image](https://user-images.githubusercontent.com/5814811/34672622-26d09158-f4a5-11e7-86d0-f252494a7f27.png)

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev. The font for Placeholder text uses Fira Sans.

![firasansdev](https://user-images.githubusercontent.com/33448286/35502589-2100d796-04e6-11e8-9736-7de6a0f2b872.png)
