### ISSUE TITLE
Users should be able to navigate through multiple screenshots by drag and drop

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4137]
Steps to reproduce:
1.Open any add-on with multiple screenshots (ie. https://addons-dev.allizom.org/en-US/firefox/addon/fireshot/) 
2.Try to navigate between screenshots by drag and drop

Expected results:
Users should be able to navigate through multiple screenshots by left\right drag and drop (right now, only scrollbar can be used)

Actual results:
Only scrollbar(which is very narrow) or the left\right arrows(which is slow if we have multiple screenshots) can be used

Please see a video of the issue : 
![screenshotnav](https://user-images.githubusercontent.com/1583842/34723454-595160e0-f553-11e7-83da-fcab81ed9acf.gif)

**Comment by tofumatt** [comment]
I think the screenshot navigation could be redone but I don't think this is an issue worth tracking. Users can scroll with trackpads and click and hold the scroll bar. I don't think click and drag on desktop with a pointer should be the expected interaction method here, so closing as won't fix.

**Comment by vcarciu** [comment]
@tofumatt : I know that the navigation can be done as described above, I am just saying that we should chose the easier method for users.
