### ISSUE TITLE
Show Parent Folder removed by author

### ISSUE THREAD

**Issue by blstumpf** [mozilla/addons-frontend#4144]
Show Parent Folder was available on Feb 9 2017 for Firefox 51.0.1. It improved lists of Bookmarks at
 https://addons.mozilla.org/en-US/firefox/addon/show-parent-folder/

Today it shows "This add-on has been removed by its author."

Is there a working replacement available?  Today is Jan 11, 2018

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on. Unfortunately we can't help with a particular add-on issue; it's best to contact the developer directly if you know their contact info. I don't know off-hand if there's a replacement available. It might help to search the web or the Add-ons forums about it: https://discourse.mozilla.org/c/add-ons
