### ISSUE TITLE
Broken link about Firefox GPO

### ISSUE THREAD

**Issue by jpjeffery** [mozilla/addons-frontend#4146]
### Describe the problem and steps to reproduce it:
Found an article about setting Firefox to never remember history, by GPO. Article contains a link, to a page which doesn't exist

### What happened?
Link was redirected to a 'File an issue' page

### What did you expect to happen?
The link to work.

### Anything else we should know?
Article page: https://support.mozilla.org/en-US/questions/1067860
Link that doesn't work: https://addons.mozilla.org/firefox/addon/cck2wizard/

**Comment by tofumatt** [comment]
It looks like that add-on is no longer available, so the page is now displaying a "Not found" error. Unfortunately it's up to the add-on author to add their add-on back; the best course here is to edit the support document and remove that link.

**Comment by jpjeffery** [comment]
Thanks, tofumatt

I found the add-on on the author's own website here: https://mike.kaply.com/cck2/

...but it's not compatible with FF v57.0.4 (which probably explains why it's no longer listed via that link)
