### ISSUE TITLE
Pass additional parameters through to the API

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4155]
TAAR is starting to use some new query string parameters in the disco pane so we should pass through `study` and `branch` as well as the `clientId`.

To make this easier in the future I'm wondering if we should just add a list for params that are OK to pass through, that way we just need to add to the list to send additional parameters.

**Comment by muffinresearch** [comment]
@tofumatt as mentioned earlier on irc we're going to just pass anything through to the TAAR from the API so we may as well do the same thing here, that way if TAAR want to add new things those params will just get passed along.

**Comment by tofumatt** [comment]
Sorry, just looking over this now, the issue isn't 100% clear: will these query params be passed to the Disco Pane URL? Right now our router expects [`/:lang/firefox/discovery/pane/:version/:platform/:compatibilityMode`](https://github.com/mozilla/addons-frontend/blob/master/src/disco/routes.js#L21), so I don't see those new params. Will they be query params (eg. `?study=foo&branch=bar`)

**Comment by tofumatt** [comment]
I'm not super clear on where these params are coming from so I need a bit more info to fix this actually. Sorry about that 😢

**Comment by muffinresearch** [comment]
> I'm not super clear on where these params are coming from so I need a bit more info to fix this actually. Sorry about that 😢

Here's an example: 

```
https://discovery.addons.mozilla.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%?study=taarexpv2&branch=$BRANCH$&clientId=$CLIENTID$
```

**Comment by AlexandraMoga** [comment]
@tofumatt could you please add some steps to help us verify these changes?

**Comment by tofumatt** [comment]
This one is a server side only code part actually and I don’t think needs QA. Marked as QA not needed!

**Comment by muffinresearch** [comment]
@AlexandraMoga I think the best thing for a QA test would be to hit the stage discovery pane with the following:

You can change the url in `about:config` see `extensions.webservices.discoverURL`  you'll need to change the host to `discovery.addons.allizom.org`.  (see also the notes at: https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing)

* No extra paramters (reset the config for extensions.webservices.discoverURL` and then set up the stage host as mentioned above) 
  * Check the disco pane loads ok
* Add clientId=[CLIENTID] you can get the data from about:telemetry
 * Should see recommendations (e.g. different data to the first request)
* Add query param for `study` e.g. the query string will now be `?clientId=foo&study=blah`
  * Everything should load and you should still get recommended disco pane results
* Add query param for `branch` e.g. the query string will now be `?clientId=foo&branch=baz`
  * Everything should load and you should still get recommended disco pane results
* Add query param for `study` and `branch` e.g. the query string will now be `?clientId=foo&study=blah&branch=baz`
  * Everything should load and you should still get recommended disco pane results

We'll need to separately check with the TAAR people that they are receiving the expected parameters. I can look to ask them to check that this afternoon.

**Comment by muffinresearch** [comment]
Right now I get no recommendations from taar.dev.mozaws.net and taar.prod.mozaws.net is 503'ing.

**Comment by AlexandraMoga** [comment]
@muffinresearch Thanks for the detailed steps.
I've applied the configuration in about:config and I've used the query parameters as suggested.
One thing is not very clear though:

> Add clientId=[CLIENTID] you can get the data from about:telemetry
> Should see recommendations (e.g. different data to the first request)

Does this mean that once the clientId parameter is introduced, we should see different add-on suggestions in Discovery Pane?
For hat I've tried, Disco pane always returned the same results.

**Comment by muffinresearch** [comment]
@AlexandraMoga as mentioned in my comment https://github.com/mozilla/addons-frontend/issues/4155#issuecomment-358266652 I don't currently see recommendations and apparently the recommendations engine is in a state of Flux on -dev. 

I'll be looking to do an end to end test later with the TAAR team to validate they are seeing the params, I think from your perspective as long as nothing blows-up for those various tests it's fine.
