### ISSUE TITLE
The text in About this extension section doesn't fill the box

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4158]
Steps to reproduce:
1. Log into AMO and choose any listed addon with a longer description (i.e. https://addons.allizom.org/en-US/firefox/addon/swarald/)
2. Observe how the text is displayed in About this extension section 
     
Expected result:
The text fills the box.

Actual result:
The box is not entirely filled with text. An empty area is noticeable on the right side of the screen.

Notes:
Reproduced on both AMO dev and stage with FF57(Win 10).
This issue is also reproducible for themes.

![text in the box](https://user-images.githubusercontent.com/33448286/34981130-49744fdc-faaf-11e7-9a50-cd573912752b.png)

**Comment by tofumatt** [comment]
This is intentional; filling the entire area with text would result in lines much too long and actually makes the text harder to read. So the `max-width` means on a larger screen there's some empty space there, but that's as designed. 😄
