### ISSUE TITLE
Infinite loop when accessing a category from the homepage using data from docker

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4170]
My work exists [here](https://github.com/jrbenny35/addons-server/tree/update_ui_test_config_for_frontend).

Environment:
I have created a collection with the user as 'Mozilla' and the collection is named 'be-more-productive'.

Steps to reproduce:
1. Create and fill database with addons
2. Start the amo frontend server using ```yarn amo```
3. Click on the 'Productivity' category under the 3 main featured categories at the top.

Result: The page will act like it is load and the ```Loading-text``` CSS will change continuously. If you look in the terminal where you started the amo frontend server, you will see multiple requests to 2 different URLs both returning a ```200``` but they never stop.

**Comment by AlexandraMoga** [comment]
Are there any steps to follow in order to verify this from our end?

**Comment by kumar303** [comment]
@AlexandraMoga this one is hard to reproduce without running your own server and configuring the homepage collection data. It would be helpful if you could test the home page collection features for any regressions after we made this change.

**Comment by vcarciu** [comment]
@kumar303 : performed exploratory testing around home page collections and everything looks fine . Marking as verified.
