### ISSUE TITLE
Rename all className imports to makeClassName

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4171]
This is just a convention change and it's quite small, but I liked that @kumar303 imported the `classnames` package as `makeClassName` instead of our usual `className` name [here](https://github.com/mozilla/addons-frontend/pull/4148/files#diff-79d1d6288c9a4baa1c738148e96b9b83R4).

Our naming of `className` over `classname` is already convention, so I say we do it everywhere and update the convention.

**Comment by KhushilMistry** [comment]
Hey @tofumatt , I want to work on this. I have deployed the app on the local server.
So I have have to use this new convention every component of the amo, right ?

**Comment by tofumatt** [comment]
That’s right. Everywhere in the app should be changed.

- Matt (Sent from mobile)

**Comment by KhushilMistry** [comment]
I have made a PR #4187. Can you review it ?
