### ISSUE TITLE
Fix error icon in Photon notification

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4175]
### Describe the problem and steps to reproduce it:

Trigger an error, such as viewing an incompatible add-on. You could try viewing https://addons-dev.allizom.org/en-US/firefox/addon/friday_fun/ in Firefox 57 which will show an error like "This add-on requires a newer version of Firefox."

### What happened?

An error message is rendered with an *i* icon

### What did you expect to happen?

The error message should be rendered with a *!* icon

### Anything else we should know?

This icon is missing from the Photon spec. See https://github.com/FirefoxUX/photon/issues/249

**Comment by anweshknayak** [comment]
@kumar303 can I do this ?

**Comment by kumar303** [comment]
Fixed icon: https://design.firefox.com/icons/viewer/#error

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/36660957-866a03ca-1ae2-11e8-94b0-72c3abd17698.png)
