### ISSUE TITLE
Re-style the Download Firefox page as seen in other browsers

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4176]
This [comment](https://github.com/mozilla/addons-frontend/issues/3706#issuecomment-345868336) had requested a new style for the Download Firefox page.

To view this page:

* Open Chrome (or any other non-Firefox browser)
* Go to the detail page for any add-on

It currently looks like:

<img width="1043" alt="screenshot 2018-01-17 16 37 49" src="https://user-images.githubusercontent.com/55398/35072369-e4ededba-fba9-11e7-9538-12410da53e4c.png">

@pwalm can you update the mock of what you were asking for here?

**Comment by pwalm** [comment]
Standard message bar, but green and with a little firefox icon: 
<img width="857" alt="screen shot 2018-01-23 at 8 56 50 pm" src="https://user-images.githubusercontent.com/6797635/35315267-4ef830a0-0080-11e8-9125-b4205d8083d1.png">

Not sure on the messaging, let me follow up with content.

**Comment by svitlana-galianova** [comment]
Hello, I have worked with this pop-up before and I would like to help out again.

**Comment by willdurand** [comment]
This issue has been fixed by changing the main button:

![Screen Shot 2019-04-18 at 17 10 42](https://user-images.githubusercontent.com/217628/56371178-e7caef00-61fc-11e9-929f-20532aa9a573.png)
