### ISSUE TITLE
Add to collection drop down menu contains a redundant "Add to collection" option

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4181]
Follow up of [#2768](https://github.com/mozilla/addons-frontend/issues/2768#event-1429241861)

STR:

1. Log in to AMO-dev 
2. Select an add-on to see its details page (i.e. https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/)
3. Scroll down to More information section and click on Add to collection

Expected results:
A drop down menu with functional options is opened

Actual results:
The drop down menu contains an 'Ad to collection' option which doesn't seem to have a specific function

Notes;
reproduced on AMO-dev with FF57 (Win10, Android 7.0)

![add to collection](https://user-images.githubusercontent.com/31961530/35104297-14f03316-fc71-11e7-8834-6789859aaeaf.gif)

</br>

Android as well:

![image](https://user-images.githubusercontent.com/31961530/35104326-2f928aac-fc71-11e7-8c96-16bd7f374c20.png)

**Comment by kumar303** [comment]
I know it's a bit weird but this was intentional. It's a limitation of using a select box as an action oriented UI element. /cc @pwalm in case he has any additional concerns here.

**Comment by pwalm** [comment]
It is a bit weird... there's no way that "Add to collection" can just appear as a subhead or title?

**Comment by muffinresearch** [comment]
I agree this is a bit odd and we should re-think it. 

@kumar Is there any way we can config off this UI until we can resolve it. I think in general it might be better to feature flag all the collections UI in the new frontend until we have more of it so that we can ensure it hangs together correctly. 

As @pwalm suggest, a quick fix to this specific problem would be to add a label to the select saying "Collections" and then the first option could be a regular "please select" kind of thing.

**Comment by muffinresearch** [comment]
Marking this as blocks release, I think we should either update the markup or set this up with config so it's not exposed on prod.

**Comment by kumar303** [comment]
@pwalm how about making it into a standalone card?

<img width="523" alt="screenshot 2018-01-24 10 34 53" src="https://user-images.githubusercontent.com/55398/35344289-634034fa-00f2-11e8-82cd-30eb1e5a1a45.png">
<img width="495" alt="screenshot 2018-01-24 10 35 09" src="https://user-images.githubusercontent.com/55398/35344294-66d9e9f8-00f2-11e8-9cb8-649caed97d06.png">

<details>
<summary>See a screenshot of the entire page</summary>

![screenshot-2018-1-24 duckduckgo plus add-ons for firefox](https://user-images.githubusercontent.com/55398/35344453-cb618214-00f2-11e8-8acd-08518e8232f8.png)


</details>

**Comment by kumar303** [comment]
We went with the UX proposed up above. You can see more screenshots at https://github.com/mozilla/addons-frontend/pull/4215

**Comment by AlexandraMoga** [comment]
Having "Select a collection" as first option in the drop-down list still seems redundant, but, if this is the best workaround for now, I believe we can work with that..

![image](https://user-images.githubusercontent.com/31961530/35381852-3fca1cbe-01c6-11e8-96fb-b9177b59f427.png)

**Comment by kumar303** [comment]
> Having "Select a collection" as first option in the drop-down list still seems redundant

I see what you're saying. I didn't think there was a way to fix it but I did some research and I have an idea. I filed a new issue: https://github.com/mozilla/addons-frontend/issues/4226

**Comment by pwalm** [comment]
Standalone card is 👍
