### ISSUE TITLE
Hyperlink from Baris' 

### ISSUE THREAD

**Issue by genericnk** [mozilla/addons-frontend#4183]
### Describe the problem and steps to reproduce it:
Hyperlink not working for all the toolbar buttons from Baris...
http://barisderin.com/?p=18

### Anything else we should know? nope.  I was ready to go to a new browser until I used your latest version.  Quantum rocks.  TY

http://barisderin.com/?p=18

Luisa Hahn
genericnk@cox.net

**Comment by muffinresearch** [comment]
Hi @genericnk. It's not clear from the description what this issue relates to. 

If you're having a problem with a specific add-on please contact the author for assistance. Generally this issue tracker should only be used for issues related to the usage of the https://addons.mozilla.org site.

If you think this _is_ a bug with the site please reopen this ticket and add more information so we can better understand the problem.
