### ISSUE TITLE
Unbroken strings are breaking the layout for ' Added to <collection>' notification

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4184]
STR:

1. Log into AMO-dev 
2. Select option 'View my collections' from the user menu
3. Click on Create a Collection to open the collection submission form
4. Fill in the fields of the submission form, making sure that your collection name includes a long unbroken string
5. Submit your new collection
6. Go back to AMO homepage and select an add-on to view its details page
7. Scroll down to 'More information' section and select the option to 'Add to collection'
8. Add the add-on to the collection containing the unbroken string

Expected result:
"Added to <collection name>" notification is displayed without any layout issues

Actual result:
The collection name falls outside the notification block

Notes:
Reproduced on AMO-dev with FF57 (Win10 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/35139984-2200eedc-fcfe-11e7-9148-ce5a8575646c.png)

**Comment by BenTarman** [comment]
I started working on this just now

**Comment by softvision-danielorban** [comment]
"Added to" notification is displayed without any layout issues.
Issue verified on dev with FF 70.0.1 (Win10/64-bit); FF 68.2.0 (Android 8.0).
Screen capture attached:
![one word](https://user-images.githubusercontent.com/43445968/69060829-b8919000-0a20-11ea-8d28-436c30d3d84a.JPG)
