### ISSUE TITLE
Can't install multiple extensions in Disco Pane

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4189]
Re-filing from https://github.com/mozilla/addons-server/issues/7343 originally reported by @cosminbadescuSV 

### Describe the problem and steps to reproduce it:
1.Open Firefox.
2.Go to about:addons web page.
3.Toggle the install button for multiple extensions.
4.Observe the toggle button of the extensions.

### What happened?
The toggle button of some extensions is stuck and the extensions are not installed.

### What did you expect to happen?
The toggle button of the extensions is working and the extensions are successfully installed.

### Anything else we should know?
Reproduced on AMO prod with FF57 (Win7 64-bit and Mac OS X 10.13)
![multiple](https://user-images.githubusercontent.com/15885467/35150936-022e6216-fd25-11e7-8781-dd82ee744765.gif)

**Comment by muffinresearch** [comment]
I can repro this. Looks like the 2nd install clears the dialogues for the currently in progress install which leaves it in a downloaded/pending state.

I can see this might be one of two issues, either there's an event firing for cancellation that's not listened to, or a bug in Firefox that means the second install doesn't cancel the first. We'll need to figure out which.

Even if this is a Firefox issue, we might be able to work around it in the UI.

**Comment by muffinresearch** [comment]
Should be revalidated once https://github.com/mozilla/addons-frontend/issues/3954 lands.

**Comment by willdurand** [comment]
ahm, interesting. Adding this on my radar.

**Comment by willdurand** [comment]
I have tested the disco pane locally with the new `AMInstallButton` (also available in -dev) and I cannot reproduce.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, WIn10x64

Add-ons and themes can be installed simultaneously 

![disco multiple install](https://user-images.githubusercontent.com/31961530/44205138-05bbed80-a15e-11e8-865a-3ad49d6f7d5f.gif)
