### ISSUE TITLE
Toggle button of the extension is not displayed correctly on resize

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4190]
Refiled https://github.com/mozilla/addons-server/issues/7342 originally reported by @cosminbadescuSV 

### Describe the problem and steps to reproduce it:
1.Open Firefox.
2.Go to about:addons web page.
3.Resize the web page.
4.Observe the toggle button of the extension.

### What happened?
The toggle button of the extension is displayed on the left side after resize.

### What did you expect to happen?
The toggle button of the extension is displayed on the right side after resize.

### Anything else we should know?
Reproduced on AMO-dev, stage and prod with FF59 and FF57 (Win7 64-bit and Mac OS X 10.13)
![resize](https://user-images.githubusercontent.com/15885467/35144776-44234f22-fd0e-11e7-9efc-287984491cc7.gif)

**Comment by KhushilMistry** [comment]
Hey, I want to work on this issue.
Toggle button should be right align always, right ?

**Comment by muffinresearch** [comment]
@KhushilMistry yes, though it's the other way around for RTL locales.

E.g:

<img width="540" alt="dynamic_media_downloaders_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35240839-9f6dbc78-ffac-11e7-93d3-6859e242b7f0.png">

**Comment by muffinresearch** [comment]
@KhushilMistry I've marked this contrib:assigned - please reference this issue in your PR - thanks!

**Comment by cosminbadescuSV** [comment]
I noticed a difference on the -dev server between Firefox 60.0a1 and Firefox 58.0.2.
As you can see in the screenshot: 
- in Firefox 60.0a (left) looks good.
- in Firefox 58.0.2 (right) the button moves out of the add-on panel and at the bottom of the page there is an extra scroll bar.

![bug4190](https://user-images.githubusercontent.com/15885467/36247703-b106ae74-123d-11e8-8573-98a66fed818c.png)

Is this expected?

**Comment by tofumatt** [comment]
That is not expected. Can you send the url you tested against?

- Matt (Sent from mobile)

**Comment by cosminbadescuSV** [comment]
Sure, here it is: https://discovery.addons-dev.allizom.org/%LOCALE%/firefox/discovery/pane/%VERSION%/%OS%/%COMPATIBILITY_MODE%

![buttons](https://user-images.githubusercontent.com/15885467/36261453-1522b32e-126d-11e8-8db2-7083ea6bced0.gif)

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF58.0.2 (Win 7 64-bit) on AMO -dev server.

The toggle button of the extensions are displayed on the right side after resize.
Please see the attached video:
![bug 4190](https://user-images.githubusercontent.com/15885467/36433840-31fb175a-1666-11e8-92f5-54613bd65bd1.gif)
