### ISSUE TITLE
Wunderlist addon is missing?

### ISSUE THREAD

**Issue by dalehenrich** [mozilla/addons-frontend#4192]
### Describe the problem and steps to reproduce it:
Attempted to follow the Wunderlist[1] download link for firefox[2] and ended up on the this page[3] with a tiny "page not found" message ... I was using Wunderlist on my other machine with a probably slightly older version of FireFox, but I got a new laptop yesterday and today installed the latest version of firefox and then tried to install Wunderlist ... a bit disappointing because I was using Wunderlist pretty heavily ...

[1] https://www.wunderlist.com/web/
[2] https://www.wunderlist.com/download/add-to-wunderlist-firefox
[3] https://addons.mozilla.org/en-US/firefox/addon/add-to-wunderlist/

**Comment by muffinresearch** [comment]
Unfortunately the add-on looks to have been removed by the developer. You could try contacting them for advice on what there plans are. Unfortunately there's nothing that we can do from here.
