### ISSUE TITLE
Delete a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4195]
After creating a collection (see https://github.com/mozilla/addons-frontend/issues/4003 or use the legacy site), the user should be able to enter the edit mode (see https://github.com/mozilla/addons-frontend/issues/4002) and then click the delete button shown in the bottom left of the overlay. This will remove the collection from all listings.

<img width="685" alt="screenshot 2018-01-22 11 21 04" src="https://user-images.githubusercontent.com/55398/35234321-5de38440-ff66-11e7-9996-6089a95d3885.png">

Tracker: https://github.com/mozilla/addons-frontend/issues/2782

**Comment by bobsilverberg** [comment]
@pwalm Could you please let me know where you think the delete button should go on the current version of the Edit Collection screen, and what it should look like?

Current screen:

<img width="1218" alt="screenshot 2018-05-29 12 09 20" src="https://user-images.githubusercontent.com/142755/40671513-18fb92f4-633a-11e8-932a-49c2544ff263.png">

**Comment by pwalm** [comment]
Hmm... let's put a link below the white box that says: "Delete this collection" which will then ask for a confirmation.
![add-ons - 2018-05-29 09 52 34](https://user-images.githubusercontent.com/6797635/40673656-3a127f4c-6327-11e8-87f0-5bc63d3f862d.jpg)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10&Android 8.0)

For what I've noticed I filed https://github.com/mozilla/addons-frontend/issues/5255
