### ISSUE TITLE
Add-on screenshot images up-scaling degrades quality

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-frontend#4197]
I noticed that on AMO screens/images are up-scaled which causes them to lose clarity, especially for small images.

Example:
https://addons.mozilla.org/en-US/firefox/addon/foxytab/

Transferred from: https://github.com/mozilla/addons/issues/627

**Comment by kumar303** [comment]
This is pretty embarrassing. Does anyone know the associated addons-server issue? I can't find it. I'm assuming that we need to store higher res images?

**Comment by diox** [comment]
The only issue already filed is https://github.com/mozilla/addons/issues/221 I think.

**Comment by kumar303** [comment]
Also related: https://github.com/mozilla/addons-frontend/issues/1519

**Comment by erosman** [comment]
As of today, the issue is still present.

**Comment by dessant** [comment]
Is storing higher resolution images a must for fixing this issue? Couldn't images be centered and displayed with their natural size when they are smaller than the available space?

**Comment by willdurand** [comment]
> Is storing higher resolution images a must for fixing this issue?

No.

> Couldn't images be centered and displayed with their natural size when they are smaller than the available space?

That's the plan I believe, and we are going to work on it soon.

**Comment by dessant** [comment]
Sounds great, thanks for the update!

**Comment by eviljeff** [comment]
@dessant fwiw, we've been storing the original size images uploaded since mozilla/addons-server#7208 was fixed in February, so we are able to produce larger images from the originals - and will once mozilla/addons-server#7908 is finished.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10 &Android 8.0)
Here's a demo for dev (improved especially for small image samples) versus stage (the old view)

![dev versus stage](https://user-images.githubusercontent.com/33448286/41840308-169a1e10-786e-11e8-9908-77f6b981b23b.gif)
