### ISSUE TITLE
Add a new overlay for editing in context (like for collections)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4198]
We need an overlay component for editing or creating something in the context of something else. For example, you may need to create a collection from the collection listing screen. We have an existing overlay component but it has a lot of problems. See https://github.com/mozilla/addons-frontend/issues/3636

**For QA**: The actual overlay won't be testable until https://github.com/mozilla/addons-frontend/issues/4198 . For this issue, please check for style regressions on any page with forms (review entry, review replies, search box, etc).

Here is what we need in a new overlay component:

- Click the X to close it
- Click outside of it it close it
- Specify a header
- Specify the bottom row of buttons and their functionality
- Specify the content

Example:
<img width="685" alt="screenshot 2018-01-22 11 21 04" src="https://user-images.githubusercontent.com/55398/35235937-40795a88-ff6b-11e7-8a86-db80c4d7281f.png">

**Comment by muffinresearch** [comment]
@kumar303 do we have details of how these would work on mobile - does the modal just essentially fill the screen?

**Comment by kumar303** [comment]
@pwalm how should this work on mobile?

**Comment by pwalm** [comment]
Great question. I'll have to design breakpoints for this UI, but that's something that needs to happen on quite a few screens (2018!!), so I'll do some work on that.

Short answer: that same, but thinner.

**Comment by kumar303** [comment]
Mobile styles will be added in https://github.com/mozilla/addons-frontend/issues/4258

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev using FF58 (Win 10 and Android 8.0.0) Developer Response form changed the display for the Cancel button and Report this add-on for abuse form changed the display for Send abuse report button. They respond to click and look ok. 

The only inconsistency is in Write a review form ->  font size for Placeholder text changed on AMO dev it looks larger than on AMO stage and AMO prod.

![font size on dev](https://user-images.githubusercontent.com/33448286/35808942-34a97c44-0a90-11e8-9143-2bf183e5f1e9.png)
![font size on stage](https://user-images.githubusercontent.com/33448286/35808973-3ab38788-0a90-11e8-9ec6-8a57576462cc.png)

**Comment by kumar303** [comment]
@ioanarusiczki Yes, this text change is fine. Thank you for verifying.

**Comment by pwalm** [comment]
INLINE REVIEWS:
<img width="924" alt="screen shot 2018-02-09 at 12 12 41 pm" src="https://user-images.githubusercontent.com/6797635/36048011-aed96ca4-0d92-11e8-9af9-3d66a77931ef.png">
<img width="962" alt="screen shot 2018-02-09 at 12 12 50 pm" src="https://user-images.githubusercontent.com/6797635/36048015-b2970d10-0d92-11e8-8dfe-f659e2d22fdc.png">
<img width="951" alt="screen shot 2018-02-09 at 12 12 57 pm" src="https://user-images.githubusercontent.com/6797635/36048020-b4571906-0d92-11e8-8e03-49bf7e72ca33.png">

What do we think?

**Comment by kumar303** [comment]
Hi @pwalm, this is great. Can you move the mocks to https://github.com/mozilla/addons-frontend/issues/3636 ? I think that's better because maybe we won't implement an overlay for this at all.

One thing that comes to mind is that as soon the user clicks a star, they have to also click *write a review* before entering text. What if a text box just appeared? That would reduce the need for a button click and might help encourage users to leave a text review. Did you consider that?

**Comment by pwalm** [comment]
Clicking a star and going right into review mode could be an option. I don't want a user to feel "forced" into writing a review though. I kind of like the idea of making a user click to leave a review since it shows intent. I worry we'll end up with more 1 word reviews, which aren't great.

**Comment by kumar303** [comment]
I like the idea of capturing intent. I was thinking about users who leave one star reviews and then no text. This is frustrating for developers because they don't know anything about that one-star rating. Just something to keep this in mind.

**Comment by pwalm** [comment]
Revised with message bars:
<img width="1025" alt="screen shot 2018-03-02 at 2 11 48 pm" src="https://user-images.githubusercontent.com/6797635/36924534-da17c568-1e23-11e8-9bcf-fd4f187ac7e3.png">
<img width="1025" alt="screen shot 2018-03-02 at 2 12 11 pm" src="https://user-images.githubusercontent.com/6797635/36924544-df926ffc-1e23-11e8-8694-beb94a24a8d1.png">
<img width="960" alt="screen shot 2018-03-02 at 2 12 39 pm" src="https://user-images.githubusercontent.com/6797635/36924548-e2e2587a-1e23-11e8-8888-3b5f695efce2.png">
