### ISSUE TITLE
Implement new "Card" design for hero area of homepage

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4202]
Recent user testing confirms that AMO's current design for the hero area (main upper portion of the homepage where the carousel traditionally sits) can be improved. UX has designed a new approach—called "cards"—we'd like to implement as soon as possible. 

Specs courtesy of pwalm. 

![card_specs](https://user-images.githubusercontent.com/8496249/35251895-77da8e26-ff92-11e7-9f59-ad8f85b4fc12.png)

**Comment by muffinresearch** [comment]
@devaneymoz have these been tested and proved to perform better? I may have missed the research that was carried out, are there any details of the user testing performed?

@pwalm From this screenshot alone it's hard to understand how these will work in the homepage, I see the cards in the Sketch file but is there a mock of this all together - when should the 3 cards vs 4 cards be used. 

Also what defines the logos and the colours, can those be specified up front?

**Comment by pwalm** [comment]
@muffinresearch Just wanted to get these screens out the door last week, I'll make a more detailed spec with answers to your questions this week.

**Comment by devaneymoz** [comment]
@pwalm @muffinresearch 

Also, the question about testing this concept may be best answered by pwalm. Is there some way we can execute some basic user testing on cards to help validate the concept?

**Comment by muffinresearch** [comment]
depends on https://github.com/mozilla/addons-frontend/issues/4262

**Comment by pwalm** [comment]
Closing this. The home page is going to have a bigger refresh in the not-too-distant future.
