### ISSUE TITLE
 Cannot navigate profile pages in AMO with Fennec

### ISSUE THREAD

**Issue by miketaylr** [mozilla/addons-frontend#4204]
Originally filed @ https://bugzilla.mozilla.org/show_bug.cgi?id=1428041

### Describe the problem and steps to reproduce it:

1. Go to https://addons.mozilla.org/en-US/firefox/user/andreipetcu/ or any other AMO profile with more than 5 extensions so it will have pages.
2. Click the next button

Expected results:
Go to next page.

Actual results:

Nothing. I cannot navigate to the next page.

Note: clicking the last link works.

### Anything else we should know?

Vimeo recording from original reporter: https://vimeo.com/249664361

**Comment by tofumatt** [comment]
Technically this is an issue with addons-server as this page is still rendered by the old Django app.

That said, this will be fixed by #2749 so we don't need to move it.

**Comment by miketaylr** [comment]
Thanks @tofumatt 
(it's hard to know where exactly to file issues for AMO...)

**Comment by tofumatt** [comment]
Yeah, I totally understand :-)

No worries! :-)

**Comment by muffinresearch** [comment]
Marking as a duplicate based on https://github.com/mozilla/addons-frontend/issues/4204#issuecomment-359868096
