### ISSUE TITLE
Add some space between "Private whiteboard" section and "Update whiteboard" button

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4206]
Steps to reproduce:
1.Go to Reviewer Tools and open an add-on (https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/mixed-add-on)

Expected results:
We should have some space between "Private whiteboard" section and "Update whiteboard" button

Actual results:
There is almost no space between "Private whiteboard" section and "Update whiteboard" button

NOTES:
Issue was reproducible on Win10x64, FF 57

Please see screenshot for this issue : 
![whiteboard](https://user-images.githubusercontent.com/1583842/35290594-599c06f6-0073-11e8-8a33-fb3235ebd48f.png)

**Comment by tofumatt** [comment]
The reviewer tools are currently not part of the addons-frontend so this should be moved to addons-server. Moved to https://github.com/mozilla/addons-server/issues/7377
