### ISSUE TITLE
Uncompressed CSS on stage is 5.84mb vs 1.75mb on prod

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4211]
Just noticed this checking out the cache immutable changes.

I'm not sure what's changed, but we should check this out before release in case there's a been any changes resulting in a lot more CSS being generated etc.

**Comment by muffinresearch** [comment]
Running the prod build locally e.g:

```
NODE_APP_INSTANCE=amo NODE_ENV=production yarn build
```

I can confirm the size difference for the pending tag (2018.01.25) versus the previous one.

**Comment by muffinresearch** [comment]
The commit that regressed the CSS bundle is https://github.com/mozilla/addons-frontend/commit/48b6c12f636080005b62aadcf9229084752ab3db which is the homepage content update.

**Comment by tofumatt** [comment]
I think the best way around this is to un-complicate the CSS we use for the homepage. It will make it a bit less dynamic but I think is worth it because:

1. we may actually be moving to another “Card” header anyway
2. it reduces CSS weight a LOT

**Comment by vcarciu** [comment]
@tofumatt : do you have some specific STRs to this issue? If not, please add the "qa: not needed" label.
