### ISSUE TITLE
Assume HTML for collection descriptions

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4213]
The API currently has a special case for translated content for collection descriptions. This process will handle any HTML in the descriptions. For descriptions with no HTML this may result in `&` being sent by the API as `&amp;`

To fix this we should use DangerouslySetInnerHTML + DOMPurify on collection descriptions, and we can set the allowed tags to an empty list since they shouldn't actually contain unescaped HTML.

Ideally in the future the code behind API wouldn't need to do this treatment of the content, but for now this is a pragmatic solution that gets us the desirable result with a small change on the frontend.

Example of the problem [1] and the API response [2]:

<img width="540" alt="dynamic_media_downloaders_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/35239866-9247b9de-ffa9-11e7-8ce1-1efec748cf97.png">
 
[1] https://addons.allizom.org/en-US/firefox/collections/mozilla/dynamic-media-downloaders/
[2] https://addons.allizom.org/api/v3/accounts/account/mozilla/collections/dynamic-media-downloaders/

refs: https://github.com/mozilla/addons-server/issues/7368

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF58 (Win10x64, Android 7.0) and the collection description is rendered correctly by the frontend.
The API response is still the same, so I assume nothing changed there, right?


![image](https://user-images.githubusercontent.com/31961530/35501728-6764388e-04e3-11e8-9ce2-1a97f864cb5f.png)
