### ISSUE TITLE
The paginator does not handle non-numeric pages correctly

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4218]
### Describe the problem and steps to reproduce it:

* Go to any URL that has a paginated result set. For example, go to the home page and click on *See more popular extensions*.
* Click on a next page link so that you see `?page=2` in the URL
* Manually edit the URL bar to make that `?page=bla`, for example: https://addons-dev.allizom.org/en-US/firefox/search/?page=bla&sort=users&type=extension

### What happened?

The result is a 404

### What did you expect to happen?

The app should ignore the invalid page parameter and load page 1 of the results.

### Anything else we should know?

The bug is because we are using `Number.isNaN()` when we should be using `isNaN()`:

https://github.com/mozilla/addons-frontend/blob/a1891d5480db8e92e30b0dda5c8f8665f99482d7/src/core/utils/index.js#L288

**Comment by kumar303** [comment]
On a closer look, `parseInt()` is used to mitigate the fact that `Number.isNaN()` doesn't report strings as not numbers. And since `parseInt()` returns `NaN` for strings then it's safe to use.

Also, I realize that a 404 is in the intended result here! My bad.

**Comment by muffinresearch** [comment]
> Also, I realize that a 404 is in the intended result here! My bad.

👍
