### ISSUE TITLE
Decide how to proceed with the babel-gettext-extractor fork

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#422]
We're going to be using a fork of babel-gettext-extractor with a couple of patches.  It would be good to:
- Pass the relevant patches upstream + tests
- Be able to switch to a released package.

It's complicated because the sentry branch which is the original is already a fork of bable-gettext-plugin however it (the sentry fork) doesn't support babel 6 by default, so our fork adds that from patches in a PR by a contributor to the sentry project + a couple of other fixes.

**Comment by muffinresearch** [comment]
We could also consider moving the fork under mozilla as a temporary measure and set up a release from there. I'm going to ask the upstream when and if they're planning to update to babel6 at some point.

**Comment by tofumatt** [comment]
We should move this to a Mozilla repo and publish it as an NPM package we can use. We'll need to update our `package.json` to point to the new package when we publish it.

**Comment by muffinresearch** [comment]
This has been moved here: https://github.com/mozilla/babel-gettext-extractor I'll file an issue for renaming the package so it can be released without colliding.
