### ISSUE TITLE
AMO-stage is not loading the page CSS content

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4221]
STR:

1. Access AMO-stage at https://addons.allizom.org/en-US/firefox/
2. Observe how the page content is loaded

Actual result:
The page CSS content is not loaded (404 received in the console)

Expected result:
AMO homepage content is loaded correctly

Notes:
- reproduces only on AMO-stage with FF58 (Win10x64 and Android 7.0)
- you might need to refresh the page if the error is not visible on the first loading
- could be related to [#4211](https://github.com/mozilla/addons-frontend/issues/4211#event-1440344677)

![image](https://user-images.githubusercontent.com/31961530/35379163-df828a74-01bd-11e8-8049-db2768aa2092.png)

**Comment by AlexandraMoga** [comment]
per @muffinresearch's  comment on irc, this is " a Staging deployment issue. Waiting for ops"

**Comment by muffinresearch** [comment]
OPs are currently looking into it and re-deploying stage.

**Comment by kumar303** [comment]
The ops team has sorted out the deployment failures. Stage looks healthy again: https://addons.allizom.org/en-US/firefox/

**Comment by vcarciu** [comment]
Verified as fixed.
