### ISSUE TITLE
betternet

### ISSUE THREAD

**Issue by tuvia5761** [mozilla/addons-frontend#4222]
### Describe the problem and steps to reproduce it:

i searched up betternet for firefox
i followd a link to the website
i clicked "get the app"
the link took me to the extensions store, and the app was not there
### What happened?
the app did not show up in the extensions store
### What did you expect to happen?
to be able to install the addon with no dificulty

**Comment by tofumatt** [comment]
Could you please include a link to the add-on URL where you encountered the error?

It sounds like the add-on was unlisted/is no longer available. In that case we might be able to tell you why but it's up to the add-on developer to restore their extension to the site. Sorry about that.

**Comment by FatOrangutan** [comment]
They probably mean [this url](https://addons.mozilla.org/en-us/firefox/addon/unlimited-free-vpn-betternet). Taken from https://www.betternet.co/firefox-vpn.

**Comment by tofumatt** [comment]
Ah, okay. In that case it looks like a no-longer-listed add-on. @jvillalobos might be able to provide more info as to why it's no longer available, but it's up to the add-on developer to restore it.

**Comment by jvillalobos** [comment]
Looks like the developer recently took it down.
