### ISSUE TITLE
Selecting "Create new collection" from add-on details page will not include the listed add-on in the new collection 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4223]
STR:

1. Log into AMO homepage
2. Select an add-on to see its details page
3. Scroll down to Select a collection section and click on 'Create new collection"

Actual result:
The user is redirected to the collection creation form but the listed add-on is not automatically included in the new collection

Expected result:
The listed add-on is automatically included in the new collection when the user chooses "Create a collection" option

Notes:
- this has been an option on the old pages so maybe the users are still having this expectation when choosing "Create new collection" 
- reproduced with AMO-dev, FF58 (Win10x64)

![new col](https://user-images.githubusercontent.com/31961530/35386173-c254ceb0-01d3-11e8-8fe0-19d97ee608a2.gif)

**Comment by tofumatt** [comment]
That's a good point. I guess we should add something to the new collection creation URL (probably just on the new frontend, not worrying about addons-server code) that includes the add-on ID so the newly-created collection adds it on creation.

**Comment by kumar303** [comment]
The current option, *Create a new collection…*, is just a placeholder for convenience that lets users literally create a new collection and that's it. The feature you are requesting is definitely valid and we will be adding it in https://github.com/mozilla/addons-frontend/issues/3993 so I'm marking this as a duplicate.
