### ISSUE TITLE
[Legacy pages] A second search for collections will show add-ons suggestions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4224]
Steps to reproduce:
1.Go to AMO , legacy pages
2.Search for a collection and press Enter
3.Search again for a collection

Expected results:
For collections, there is no search suggestions

Actual results:
Search suggestions are displayed under search box and the suggested items are add-ons not collections

NOTES:
Reproducible in production
Tested with Win10x64, FF release

Please see video for this issue : 

![collsuggestions](https://user-images.githubusercontent.com/1583842/35390984-eac98536-01e5-11e8-9de1-94612a679986.gif)

**Comment by tofumatt** [comment]
I think for legacy pages we should not be filing in addons-frontend. The fixes will not be committed in this repository and the code is unrelated. Could you please move this issue? Thanks!

**Comment by vcarciu** [comment]
@tofumatt : Where should I move this one ?

**Comment by tofumatt** [comment]
Any pages with the old style belong on addons-server.

**Comment by vcarciu** [comment]
@tofumatt : thanks!
