### ISSUE TITLE
Labels are displayed underneath their specific value in the collection detail page

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#4225]
### Steps to reproduce:
1. Open a collection detail page: https://addons.allizom.org/en-US/firefox/collections/updateSF/madalinawesomecollection/
2. Observe the collection details in the left hand side of the page

### Expected results:
In the details section the labels Add-ons, Creator and Last update are displayed on top of their specific value.

### Actual results:
The labels are displayed underneath their value

### Anything else we should know?
Verified in FF58(Win7) Issue can be reproduced in amo-stage.
Screencast for this issue:
![labels](https://user-images.githubusercontent.com/15685441/35396813-65a9f078-01f6-11e8-9fe9-92e749c2335c.png)

**Comment by tofumatt** [comment]
This is the intended design, according to the mocks. Closing as a won't fix.
