### ISSUE TITLE
The site sometimes loads without any styles

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4229]
In prod the site was sometimes loading without styles.

Example: `404 https://addons-amo.cdn.mozilla.net/amo-69e8718763f05c8201cce284cc051a23.css`

```
HTTP/1.1 404 Not Found
Access-Control-Allow-Methods: GET, HEAD
Access-Control-Allow-Origin: *
Age: 157
Connection: keep-alive
Content-Type: application/xml
Date: Thu, 25 Jan 2018 17:54:10 GMT
Server: AmazonS3
Transfer-Encoding: chunked
Vary: Origin
Via: 1.1 23200c8e198c63e37634260fcea1e52c.cloudfront.net (CloudFront)
X-Amz-Cf-Id: NM2iFHgPG4vyJTpAho3Gxu4tRtFe7fJMi_z7W0yd5rb6svhhr0Czwg==
X-Cache: Error from cloudfront
```

**Comment by kumar303** [comment]
Note that we experienced the missing styles issue on stage but the root cause of the bug was not clear. We were having stage deployment failures and a re-deploy seemed to make the styles load again. This could have been dumb luck in how stage only runs with two instances.

**Comment by vcarciu** [comment]
Verified as fixed in production. There are no missing styles.
