### ISSUE TITLE
Plugin page suddently showing as missing

### ISSUE THREAD

**Issue by mail3dexter** [mozilla/addons-frontend#4232]
Today, I had downloaded a well known plugin knows as CompareIt/BuyHatke and later I tried to download on my other laptop and it was not present on mozilla addons page. I am getting "Sorry, but we can't find anything at the address you entered." message on firefox page.

This should be the addon page from where it should be downloaded:
https://addons.mozilla.org/en-US/firefox/addon/compare-hatke/

Also, I tried to google it and tried to click on the first link pointed to firefox addon page:
https://www.google.co.in/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwjFzrTG6fPYAhXKKY8KHb8TAVEQFggoMAA&url=https%3A%2F%2Faddons.mozilla.org%2Fen-US%2Ffirefox%2Faddon%2Fbuyhatke-best-price-shopping%2F&usg=AOvVaw2vIDcuIKG19HNcxNVkCl9x

**Comment by tofumatt** [comment]
Unfortunately it's likely the add-on was unlisted and it's up to the add-on developer to get it listed again. It's possible @jvillalobos could explain why it's been unlisted but that's about all we can help with, sorry about that 😢

**Comment by jvillalobos** [comment]
It was either deleted or renamed. I can't find more information about it.

**Comment by mail3dexter** [comment]
I found 1 more link from the author's website to same plugin but the result is same:
https://addons.mozilla.org/firefox/downloads/file/731316/buyhatke_price_comparison_and_price_graph-3.4.276-an+fx.xpi
