### ISSUE TITLE
Setup addons-frontend in pontoon

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#424]
Once #423 lands we should be ready for the l10ners to set up this project in pontoon.

**Comment by muffinresearch** [comment]
@mathjazz has set this up in stage already https://mozilla-pontoon-staging.herokuapp.com/sl/amo-frontend/LC_MESSAGES/disco.po/?string=160086

**Comment by muffinresearch** [comment]
Checking if there's more to do...

**Comment by mathjazz** [comment]
There actually is one thing - @mozilla-pontoon needs to be added as a [collaborator](https://help.github.com/articles/inviting-collaborators-to-a-personal-repository/) to this repo in order to be able to push translations to it.

**Comment by andymckay** [comment]
Done.

**Comment by mathjazz** [comment]
Confirmed in https://github.com/mozilla/addons-frontend/commit/b97779d0bf16344fc1c4066eb220ae2e070c4d58. Thanks!

**Comment by muffinresearch** [comment]
Thanks @mathjazz
