### ISSUE TITLE
Firefox Extension disabled

### ISSUE THREAD

**Issue by dmancini** [mozilla/addons-frontend#4254]
Our custom extension was recently removed from the addons.mozilla.org website. It was previously available at the following URL:
	https://addons.mozilla.org/en-US/firefox/addon/saba-meeting-firefox-connector/

After reading the following link:
	https://blog.mozilla.org/addons/2017/02/16/the-road-to-firefox-57-compatibility-milestones/
we determined that the issue with our extension is probably that we are using the chrome.runtime API instead of the browser.runtime API. Our extension is a WebExtension. We can make the changes to use the browser.runtime API but I can't test it to know if this is the only change necessary because the old extension works fine because the browser does not reject it. The extension is only filtered out on the addons.mozilla.org website. So the old extension works fine, the new extension works fine, how do I know if I've made enough changes without submitting it for approval and waiting to see if it is rejected?

Is there a way to make the old/existing extension available until the new one is available?

**Comment by andymckay** [comment]
If you have a question about your add-on, please contact amo-admins AT mozilla.org and they will be able to tell you why it was rejected.
