### ISSUE TITLE
Use isSearchProviderInstalled for a better AMO experience

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4256]
We should use the isSearchProviderInstalled API to detect if a search provider is already installed.

See https://github.com/mozilla/addons-server/issues/2714 for further details.

**Comment by muffinresearch** [comment]
This API seems to be deprecated.

**Comment by agnelvishal** [comment]
@muffinresearch Maybe isSearchProviderInstalled was deprecated by Google to prevent competition to its search engine
