### ISSUE TITLE
Mobile style for Collection editing form overlay

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4258]
We have a new form overlay that will be used for editing/creating Collections among other things (https://github.com/mozilla/addons-frontend/issues/4198).

We need to implement mobile styles. A spec will follow.

**Comment by pwalm** [comment]
The screen on the right is the mobile user collection and the two on the left are modal options. I'm partial to the one in the middle, it follows some more modern best practices and will grow/contract nicely depending on viewport. Some kinks to work out, but this is a good starting point!

<img width="1260" alt="screen shot 2018-02-01 at 3 17 06 pm" src="https://user-images.githubusercontent.com/6797635/35709042-b9c6a38a-0765-11e8-89c9-dfd97fb26dd5.png">

**Comment by tofumatt** [comment]
The one in the middle is certainly prettier; possibly a bit more work to do generically as the “origin point” would change but we could work toward it. I like them though!

**Comment by pwalm** [comment]
Yeah, i'm just so sick of the look on right. I know we do it on desktop, it's something I'd like to move away from in 2018. More inline input.

**Comment by bobsilverberg** [comment]
I think this issue can be closed. Here is what the edit screen currently looks like at the smallest size:

<img width="333" alt="screenshot 2018-05-17 13 32 39" src="https://user-images.githubusercontent.com/142755/40193950-d7e469b0-59d6-11e8-8b6d-790a573a4d99.png">

What do you reckon @pwalm?

**Comment by pwalm** [comment]
Yep 👍

**Comment by bobsilverberg** [comment]
Great, thanks @pwalm 😄
