### ISSUE TITLE
Move Icon files to a sub directory

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4259]
The [Icon](https://github.com/mozilla/addons-frontend/tree/2d36a5e20268d51f921f10e5a764323bc6188855/src/ui/components/Icon) component has many icon files which are referenced by `styles.scss`. To reduce clutter, let's move those to a sub directory within the same component.

For QA: please check for regressions everywhere that we use icons, such as next/previous page arrows, error notices, search box magnifier, etc.

**Comment by vcarciu** [comment]
Verified as fixed . Icons looks fine.

**Comment by kumar303** [comment]
I'd suggest waiting until we fix the issue before verifying it but thanks @vcarciu 😆 The issue only calls for reorganizing the icon code, not the icons themselves. The steps for QA verification will be to check for regressions.

**Comment by bobsilverberg** [comment]
I'll give this a go.

**Comment by vcarciu** [comment]
@kumar303 : Wow, I was so sure that this was closed when I verified it 😄 . 
I am sorry for that, I will verify it again when fixed.

**Comment by vcarciu** [comment]
No regressions were observed around icons , so I will mark this as verified. 
@kumar303 : verification was done after fix this time 😆
