### ISSUE TITLE
Show a "javascript required" message when submitting a form

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4260]
### Describe the problem and steps to reproduce it:

* Go to any page that has a form. I am looking for them with: `rg '<form' src/`
* Turn off JavaScript
* Try to submit the form

### What happened?

In each case it may be a bit different. Most of them will reload the page.

### What did you expect to happen?

Ideally the form should work but that may require too much effort since we'd have to change how our frontend server processes requests and interacts with the API.

For this issue, let's make the form submit to a page that explains how JavaScript is required for the form to work.

### Anything else we should know?

See https://github.com/mozilla/addons-frontend/issues/1552 for a specific example.

**Comment by muffinresearch** [comment]
This is a really nice solution, in lieu of more fancy server-side form handling 👍
