### ISSUE TITLE
Investigate A/B testing Component or framework

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4262]
This issue is for investigating prior art for an A/B testing solution for React components. 

For our initial use-case we'd like to try and do this for the Homepage switch to cards in place of the current homepage hero content.

## Example libs to look at:

* react-ab https://github.com/olahol/react-ab (looks good because it's simple and we can easily tie it in with our current GA instrumentation.
* Afaik [Optimizely](https://www.optimizely.com/) has been used elsewhere at mozilla, but I don't know much about how it might work.
* [Amplitude](https://auth.mozilla.auth0.com/samlp/ql6V6DHXglhTCq9qe6DPdV3eAW2da44F) is used by Firefox Accounts and Pocket. I *think* it can be used for A/B testing but I'm not sure. There is a [presentation](https://docs.google.com/presentation/d/1dhC5JsPDfi7LSQVJ53UmHGzSmUWAHg8Y9uf_8LZrg18/edit#slide=id.g2af8fbdae6_0_69)!
* [INSERT OTHERS HERE]

## Arbitrary requirements:

* Should ideally supprt GA - anything else may require legal + privacy unless already in use on other mozilla properties.
* Should be CSP compliant - optimizely historically had issues with this, though they may be fixed already.
* Needs to work within our Universal App setup.

**Comment by willdurand** [comment]
[react-ab](https://github.com/olahol/react-ab) looks interesting but we might want to contribute code to it in order to add [react-cookie](https://github.com/reactivestack/cookies/tree/master/packages/react-cookie).

**Comment by kumar303** [comment]
A custom A/B solution was added in [the TAAR patch](https://github.com/mozilla/addons-frontend/pull/4942/files#diff-cd4abfb75699370a11298ce429e85e10R63) and then removed in https://github.com/mozilla/addons-frontend/pull/5467

**Comment by willdurand** [comment]
We are adding a a/b HOC leveraging the TAAR patch linked above.

**Comment by willdurand** [comment]
Looks like this issue has been fixed.
