### ISSUE TITLE
Clean-up prod build warnings

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4265]
Webpack is issuing a lot of warnings about postcss in production builds - this is from the raw log of a travis run:

```
    [1m[33mWARNING in ./node_modules/css-loader?{"importLoaders":2,"sourceMap":true}!./node_modules/postcss-loader/lib?{"plugins":[null]}!./node_modules/sass-loader/lib/loader.js?{"outputStyle":"expanded","sourceMap":true,"sourceMapContents":true}!./src/ui/components/Switch/Switch.scss
    (Emitted value instead of an instance of Error) 
```

Might be worth checking out https://github.com/mozilla/addons-frontend/issues/4264 first since those updates might fix some of it.

**Comment by willdurand** [comment]
@muffinresearch I don't see these errors anymore. Fixed?

**Comment by willdurand** [comment]
I think this is solved because I don't see any `warning` messages anymore.
