### ISSUE TITLE
Summarize ratings by star for an add-on on its detail page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4266]
The add-on detail page is missing a summary of ratings by star as shown in the mocks. This will help users make a decision about whether to install the add-on or not. Check the mocks for the most up to date version. It looks something like:

<img width="683" alt="screenshot 2018-01-30 12 16 40" src="https://user-images.githubusercontent.com/55398/35583499-bce28ef8-05b7-11e8-9767-cd03c207501d.png">

This will probably share the same component needed for https://github.com/mozilla/addons-frontend/issues/3647

**Comment by tofumatt** [comment]
I think this is a duplicate of #3918.

**Comment by kumar303** [comment]
Thanks! That's the issue I couldn't find 👻
