### ISSUE TITLE
"Featured add-ons only" check box is not correctly displayed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4268]
Steps to reproduce:
1. Load AMO dev and make a search.
2. Observe the Featured Add-ons only option from Filter results.

Expected results:
Check box is displayed before Add-ons only option. 

Actual results:
The check box is incorrectly positioned. 

Notes:
This issue is reproducible only on AMO dev ff58 (Win10)

![featured check box](https://user-images.githubusercontent.com/33448286/35614633-746a74e4-0678-11e8-908f-be284b0bfa74.png)

**Comment by tofumatt** [comment]
Wondering if this is a regression related to #4248...

**Comment by tofumatt** [comment]
Looks like this is actually from ade72db31997cb87728c9f556ef9769a524de0a3. I'll have a fix coming soon.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF58 (Win 10, Android 8.0.0)
