### ISSUE TITLE
A glitch appears when a search that won't return results is made 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4269]
Steps to reproduce:

1. Load AMO homepage and make a search that won't return results ( I used special characters "@", "#")
2. Change the sorting criteria using the drop down menu from the Sort by filter option
3. Observe the Search results section

Expected result:
"No results were found for" message continues to be displayed in the Search results section.

Actual result:
For a moment some search results appear then "No results were found for" message is displayed.

Notes:
This issue is reproducible on AMO dev and AMO stage for FF58 (Win 10 and Android 8.0)

![searchglitch](https://user-images.githubusercontent.com/33448286/35616925-5ff4968c-067f-11e8-9677-c5aa49ac093b.gif)

**Comment by tofumatt** [comment]
Those aren’t search results but placeholders. We can’t know if a search will have zero results or some but rendering the placeholders is usually a better experience so I think we’ll stick with that.
