### ISSUE TITLE
Allow external tracking sources through to install buttons

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4270]
Refiled copy of https://github.com/mozilla/addons/issues/615 - see that issue for the original issue details + additional comments.

### Describe the problem and steps to reproduce it:
1. Open the add-on's details page with a tracking parameter, like: `https://addons.mozilla.org/en-US/firefox/addon/example?src=external-example`.
2. Open the "Downloads > by Source" statistics page (`https://addons.mozilla.org/en-US/firefox/addon/example/statistics/downloads/sources/`) and see the table.

### What happened?

The pageview in the first step is counted in "Detail Page" category.

### What did you expect to happen?

It should be counted in a column called `external-example`.

### Anything else we should know?

**For QA**: in addition to verifying the feature, please check for regressions in the install process for all extensions on AMO and the Discopane.

![image](https://user-images.githubusercontent.com/6646473/34776395-b3398cb4-f651-11e7-85b8-d6895bd49995.png)

Here's a [copy of the comment](https://github.com/mozilla/addons/issues/615#issuecomment-358707507) I posted that details what seems to be happening and the root cause of the bug.

If you visit a details page with a src query param e.g: https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/?src=external-test what is sent when installing the add-on is src=dp-btn-primary whereas I think the expectation is that it would be src=external-test. (You can see this when inspecting network in the browser console)

Looking into the code, as you noted it does look like the src param is extracted from the URL here: https://github.com/mozilla/addons-frontend/blob/6447fa8b0fbea6c14ffdeb879e059b8ab3e0ce35/src/core/installAddon.js#L274

However, it looks like the install function overrides that src here: https://github.com/mozilla/addons-frontend/blob/6c7cc717af0905f310c96f0d7b19eb0952a9dfbd/src/core/addonManager.js#L52

See this line for where this is called: https://github.com/mozilla/addons-frontend/blob/6c7cc717af0905f310c96f0d7b19eb0952a9dfbd/src/core/installAddon.js#L404 - as you can see we get the url via findInstallURL which will add a src, however the _addonManager.install() then overrides it.

**Comment by jvillalobos** [comment]
https://github.com/mozilla/addons-frontend/issues/4372 has details on what we expect of the `src` parameter.

**Comment by vcarciu** [comment]
I can see that in AMO-dev console when using src=external-test "1519657683163    addons.xpi    WARN    Failed to remove temporary file C:\Users\svuser\AppData\Local\Temp\tmp-04c.xpi for addon https://addons-dev.allizom.org/firefox/downloads/file/253547/webext_simple-22-an+fx.xpi?src=external-test" and I confirmed that this is ok with @muffinresearch , because I  can see the src=external-test .

Also, different scenarios were tested for installation from AMO and DIsco Pane and everything looks good.

Marking bug as verified
