### ISSUE TITLE
No results are found when special characters are used for search

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4272]
Prerequisites:
make sure you have a couple of submitted add-ons 

Steps to reproduce:
1. Load AMO dev and go to Developer Hub.
2. From Manage my submission edit the name of an add-on, insert some special characters 
3. Go back to AMO dev and make a search using only the special character from the edited name
4. Observe the search results.

Expected results:
The add-on is displayed in search results.

Actual results:
"No results were found for " message is displayed.

Notes:
This issue is reproducible on AMO dev and AMO stage ff58 (Win10, Android 8.0)

![special characters](https://user-images.githubusercontent.com/33448286/35624874-f3dab6c4-0698-11e8-860e-9007f4b3e08e.gif)

**Comment by muffinresearch** [comment]
@ioanarusiczki Please can you provide details of the exact add-on names you're using? It will help us to reproduce and also help us eliminate indexation taking time before it's there.

**Comment by muffinresearch** [comment]
URL extracted from the screencast for the add-on in question: https://addons-dev.allizom.org/en-US/firefox/addon/barlin-raverk-chiching/

**Comment by muffinresearch** [comment]
@EnTeQuAk what would you expect ES to make of this?

**Comment by ioanarusiczki** [comment]
@muffinresearch I tested this scenario again using FF65 (Win10). The search results are displayed only after the third letter or number is typed in the search filed but this rule won't apply for special chars or emojs (which were lately introduced on AMO). Looks like this is still reproducible.
