### ISSUE TITLE
Create a user profile photo upload component

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4276]
### Describe the problem and steps to reproduce it:
We need a user profile upload component that accepts a user's photo and sends it to the API as part of the edit profile form.

It should look like:

<img width="356" alt="screenshot 2018-01-31 14 25 04" src="https://user-images.githubusercontent.com/90871/35628039-9ef71090-0692-11e8-9d24-6a65b3fe0402.png">

**Comment by willdurand** [comment]
Server issue related to this feature: https://github.com/mozilla/addons-server/issues/8265.

**Comment by ioanarusiczki** [comment]
Verified this issue on AMO dev with FF60(Win10).
Still reproducible issues are https://github.com/mozilla/addons-frontend/issues/5107 and https://github.com/mozilla/addons-frontend/issues/4596
@willdurand @pwalm Compared with the old pages - The "Delete this picture" button is with black letters, the old pages had red letters and before deleting the image a message that is no longer displayed by the new frontend ( in my personal opinion it's better without this step)
Delete my user picture now - old pages
![delete user photo](https://user-images.githubusercontent.com/33448286/40648974-6f61cad4-6338-11e8-996f-e58c0528ee7c.png)

**Comment by willdurand** [comment]
> @willdurand @pwalm Compared with the old pages - The "Delete this picture" button is with black letters, the old pages had red letters and before deleting the image a message that is no longer displayed by the new frontend ( in my personal opinion it's better without this step)
> Delete my user picture now - old pages

Indeed. I am thinking about adding a different button with a confirmation step to prevent unwanted deletion.

**Comment by willdurand** [comment]
> @willdurand Is this the same thing you were talking about with the Delete Account interaction?

Exactly. Maybe we don't need a modal for the profile picture?

**Comment by pwalm** [comment]
Correct! No modal!
