### ISSUE TITLE
Show "Extensions created" on the user profile page

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4280]
Create a card that shows extensions a user has created on the profile.

<img width="482" alt="screenshot 2018-01-31 14 50 59" src="https://user-images.githubusercontent.com/90871/35629308-31bf268a-0696-11e8-9bd9-9ea071ba5173.png">

**Comment by ioanarusiczki** [comment]
@tofumatt 
Two questions here:
1. The number of ad-ons displayed is three (when number of submitted ad-ons in dev hub is more than3).  I have an account with many add-ons (30 plus), also many lightweight themes. If I refresh the page or log out then log in later the [User Profile](https://addons-dev.allizom.org/en-US/firefox/user/DevTesting/) page displays same ad-ons and themes. Shouldn't this be updated when refreshing page the way promo banners are on AMO homepage? Or maybe a See more by *Username* link added?

2. Static themes are not displayed yet on the info card. I submitted some static themes and approved for [another account ](https://addons-dev.allizom.org/en-US/firefox/user/Contrating2/)to see if they show up on the info card.

**Comment by tofumatt** [comment]
1. Could you please send a link? That might be better filed as new issue though.

2. Are static themes a new theme type (cc @eviljeff)? Sounds like a new issue, maybe we need to expand the addonType we search for.

- Matt (Sent from mobile)

**Comment by ioanarusiczki** [comment]
@tofumatt 
I filed two separate issues 
the More/Refresh issue https://github.com/mozilla/addons-frontend/issues/4809
the Static Themes https://github.com/mozilla/addons-frontend/issues/4810

Marking this verified fixed on AMO dev with FF59 (Win10).

**Comment by tofumatt** [comment]
Yeah, the cards are explicitly just supposed to show extensions and themes so the other types are ignored. But I didn’t know about the new static theme type. We’ll have to add that.

- Matt (Sent from mobile)
