### ISSUE TITLE
Show user info in card on profile

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4283]
We should show the user's name, photo, etc. in a card.

<img width="231" alt="screenshot 2018-01-31 14 56 29" src="https://user-images.githubusercontent.com/90871/35629616-fcb243f4-0696-11e8-8b0b-024e96ec04cd.png">

**Comment by ioanarusiczki** [comment]
1. I filed the following issues for what I've noticed during testing 
https://github.com/mozilla/addons-frontend/issues/4585
https://github.com/mozilla/addons-frontend/issues/4586
https://github.com/mozilla/addons-frontend/issues/4587
2. The checkboxes for The Add-on's developer Theme artist are not displayed yet - is this tracked already or should I file an issue?
3. The avarage rating stars are grey - when user is watching his own profile should they be displayed yellow? Maybe @pwalm could clear this out for me.
4. It seems that photo profile, homepage and number of add-ons sections work as expected. Also a user without admin rights cannot view the profile for another user with 0 submitted ad-ons.
@tofumatt if the second issue that I described above is known then I'll mark this verified fixed.

**Comment by tofumatt** [comment]
1. Thanks!
2. I don't know what you mean but I think you can file an issue. It's always best to do that and we can close it if it's not relevant 😄
3. The rating stars should always be grey on the profile. Yellow rating stars are for exact ratings the current user has left; the ratings stars on the profile page are an average.
4. On the new site (or anything using the API) user profiles are hidden (and will 404) for non-admins unless the user has submitted at least 1 add-on. So yes, that behaviour is intentional.

**Comment by pwalm** [comment]
3. Thank you @tofumatt

**Comment by ioanarusiczki** [comment]
@tofumatt Thanks ! I filed #4599 and #4598.
 This is verified fixed on AMO dev with FF59 (Win10).
