### ISSUE TITLE
Add new routes for user profile and edit user profile pages

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4284]
We'll need new routes in nginx to route user profile and edit profile requests to the front-end, but that's dependant on other code landing, so filing this for now so we don't forget 😄 

- [x] User Profile: `/user/:username/` (Depends on #4283, ready)
- [x] User Profile Edit: `/user/:username/edit`
- [x] User Profile Edit: `/users/edit`

**Comment by tofumatt** [comment]
`/user/:username/` is now ready and should be enabled **on `-dev` only** for now 😄

**Comment by bqbn** [comment]
@tofumatt what regex would you recommend we use to match `:username`?

For example, we use https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/urls.py#L9 to match `addon_id`. 

We try as much as possible to keep consistent with the application.

**Comment by tofumatt** [comment]
Whatever the old app used to match usernames would work I guess. Seems like it's here: https://github.com/mozilla/addons-server/blob/master/src/olympia/users/urls.py#L7

I think usernames are largely alphanumeric with dashes, but they can probably have other characters too. I'm not sure if the Django regex is overly generous in terms of characters but you can use it if that works.

**Comment by bqbn** [comment]
`/user/:username/` is now on mobile. 😄

**Comment by bqbn** [comment]
Re-routing for both `/user/:username/edit/` and `/users/edit` is on -dev env now.

**Comment by willdurand** [comment]
Thank you!

**Comment by AlexandraMoga** [comment]
@willdurand  I have checked that both [https://addons-dev.allizom.org/en-US/firefox/**users/edit/**](https://addons-dev.allizom.org/en-US/firefox/users/edit/) and [https://addons-dev.allizom.org/en-US/firefox/**users/edit**](https://addons-dev.allizom.org/en-US/firefox/users/edit) are redirecting to the Update account page on the new frontend. Let me know if there is anything more I could test here.

I also have one question:
I you access one of the above links while being logged out, the new frontend will show a Page not Found (404). My opinion is that the user should be prompted to the FxA log in page instead. This flow was available on the legacy pages for example. What do you think?

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF60, WIn10x64
