### ISSUE TITLE
User review is listed only after page refresh, if the reviews page for the same add-on was previously visited

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4290]
STR:

1. Log into AMO and pick an add-on that has some reviews to see its details page
2. Scroll to Rating section and submit an empty review for this add-on
3. Click on 'Read all reviews' to check the reviews submitted for this add-on
4. Go back to the listing page and click on the rating stars to open the review modal
5. Write your review and submit it
6. Repeat step 3 and check if your written review is listed

Actual result:
The written review is listed only after page refresh

Expected result:
The written review is instantly listed when user navigates to all reviews page

Notes:
Reproduced on AMO-stage with FF58 (Win10x64)

![refresh_rev](https://user-images.githubusercontent.com/31961530/35671335-c370ad9e-0743-11e8-9442-c38ccefad312.gif)

**Comment by kumar303** [comment]
Ah whoops. I think this is because we need some state changes specified in https://github.com/mozilla/addons-frontend/issues/3221

**Comment by kumar303** [comment]
This appears to be fixed as of https://github.com/mozilla/addons-frontend/issues/5942

**Comment by AlexandraMoga** [comment]
Verified fixed on  stage with FF61, Win10x64

![instant review](https://user-images.githubusercontent.com/31961530/44918281-2a5dbb00-ad43-11e8-9890-edcf8ab225d8.gif)
