### ISSUE TITLE
Disabled switch buttons in discopane if mozAddonManager is disabled

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4291]
Steps to reproduce:
1.Open FF release and set the disco pane to -dev
2.Set the extensions.webapi.testing to false 
3.Open the discovery pane

Expected results:
Fallback buttons should be correctly displayed

Actual results:
Switch buttons are still available, but greyed out

Please see video for this bug : 
![fallbackbuttonsz](https://user-images.githubusercontent.com/1583842/35687358-2dfaa2c2-0777-11e8-8d76-0e9046633d0e.gif)

**Comment by muffinresearch** [comment]
I see this on -dev and stage and the disabled switch is shown in chrome in prod too.

**Comment by muffinresearch** [comment]
This issue has a screenshot of what it used to look like https://github.com/mozilla/addons-frontend/issues/3752

**Comment by kumar303** [comment]
Since a large percentage of our users will never see this, I think we should drop the priority.

**Comment by willdurand** [comment]
we do not have switches anymore
