### ISSUE TITLE
Serve the edit collection screen from a URL

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4293]
The first version of the edit collection screen (https://github.com/mozilla/addons-frontend/issues/4004) will be shown as an overlay. The URL will not be changed. This will allow us to roll out the feature incrementally, hidden by a config setting.

When the feature is ready and working, let's make it accessible by this URL: `/collections/<username>/<collection-slug>/edit/`.

Until the feature is fully working, we need to preserve the old URL so that it goes to the legacy page.

User story:
* Sign in
* Create a collection
* View the collection
* Click on *Edit this collection*
* The URL should change to something like the example up above

**Comment by kumar303** [comment]
Let's wait on https://github.com/mozilla/addons-server/issues/7529 (allowing ID based URLs) before implementing this new edit URL. Having a URL with an ID in it will allow us to remove some hairy redirect logic in the saga which was necessary when the user edits the slug value.

**Comment by ioanarusiczki** [comment]
@kumar303 Is the blocked label left there by mistake? I checked it and seems to be alright. 

Verified fixed on AMO dev with FF59 (Win10)
When Edit my collection is clicked URL changes to https://addons-dev.allizom.org/en-US/firefox/collections/IoanaTestingDev/theMarch/edit/

![edit collection](https://user-images.githubusercontent.com/33448286/37959758-8600f1c8-31bc-11e8-8a37-fb106b026d54.gif)

**Comment by bobsilverberg** [comment]
I believe it was blocked on https://github.com/mozilla/addons-server/issues/7529, which has landed, so I think it was unblocked awhile ago. There was also a comment about not implementing this until the new collections feature is fully ready for stage and prod, and that *is not* the case, so we need to make sure that if the config flag is off we can still access the old edit screen. I guess that's something we'll be able to tell once this gets to stage.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I thought of checking this tomorrow on stage to make sure it won't be there. 
I'll update this if something is wrong. 
Thanks!
