### ISSUE TITLE
Update README to include information on the functional/integration tests.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4296]
The tests currently live on [addons-server](https://github.com/mozilla/addons-server) but I will add a link to them once we have some docs over there. This will also explain what the file ```config/functional-development-amo.js``` does and why it is needed (see https://github.com/mozilla/addons-frontend/issues/4294).

**Comment by willdurand** [comment]
UI Tests should move to another repo so I am going to close this issue.
