### ISSUE TITLE
Explore all categories link should be blue and it is not centered 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4298]
Steps to reproduce:
1. Load AMO dev homepage and go to Extensions
2. Observe Explore all categories link
3. Repeat the steps for Themes

Expected result:
"Explore all categories" text is centered and it is blue (such as See more top rated extensions)

Actual result:
"Explore all categories" is on the left side of the screen and leaves the impression that it is only a text box

Notes:
There is a difference now between AMO dev and AMO stage in the way the link is highlighted in responsive design mode on desktop when hovering over "Explore all categories".
This issue is reproducible only on AMO dev using FF58 (Android 8.0).

![explore all - extensions](https://user-images.githubusercontent.com/33448286/35728232-9caa762e-0813-11e8-81a1-80e62444d39e.png)
![explore all - themes](https://user-images.githubusercontent.com/33448286/35728239-a2afa6fc-0813-11e8-8aa4-946ec5929f45.png)

Responsive design mode:

![explore all categories](https://user-images.githubusercontent.com/33448286/35728043-ed67fcf4-0812-11e8-8ba9-4fb3d110089e.gif)

**Comment by tofumatt** [comment]
This is probably a regression from #3863; I'll handle it.

**Comment by tofumatt** [comment]
Note: These buttons should not be blue as stated in the issue, but the text should be centred and look better 😄

**Comment by ioanarusiczki** [comment]
@tofumatt The text looks alright now.  I thought that blue would help the user understand that it's a link and not a simple text box. 
This is verified fixed on AMO dev (Android 8.0.0)
