### ISSUE TITLE
“Create a collection” option from add-on details page creates only empty collections on Android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4311]
Steps to reproduce:
1. Load AMO dev and from the homepage or from other pages choose an extension or theme and click on it
2. Open the drop down menu from “Add to Collection” section and select Create a new collection
3. Type a name, description for your new collection
4. Try to add an extension or theme using Add to Collection button from Add-ons in your Collection section

Expected result:
Extensions/Themes can be added to the newly created collection.

Actual result:
Add to Collection button is not responsive. 

Notes:
The new collection is created and displayed after Create Collection is tapped but it is empty because items cannot be added. 
This is reproducible on AMO dev and AMO stage using FF58 (Android 8.0.0)

![coolections](https://user-images.githubusercontent.com/33448286/35812759-8f3053c2-0a9a-11e8-96d3-74cd9f111b56.gif)

**Comment by kumar303** [comment]
This is the legacy site. We will be rebuilding this screen in https://github.com/mozilla/addons-frontend/issues/4003
