### ISSUE TITLE
Two or more collections with the same name can be created

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4312]
Steps to reproduce:
1. Load AMO dev and from the homepage or from other pages choose an extension or theme and click on it
2. Open the drop down menu from “Add to Collection” section and select Create a new collection
3. Fill in the form and click Create Collections
4. Repeat the above steps to create another collection and at step 3 fill in the Name field the same name used when the first collection was created

Expected result:
The user cannot create two collections with identical names.

Actual result:
A warning message to correct the url is displayed but after editing it another collection can be created with an already existing name.

Notes:
This issue is reproducible on AMO dev and AMO stage using FF58 (Win 10 and Android 8.0.0)

![same names](https://user-images.githubusercontent.com/33448286/35814358-8b67ddba-0a9e-11e8-9e29-92b116b0523a.gif)

Android

![nume dublu android](https://user-images.githubusercontent.com/33448286/35814402-a95765de-0a9e-11e8-84a8-5a7edc1ae1bf.png)

**Comment by jrbenny35** [comment]
I've seen this in my testing actually. I think this is more of a addons-server bug though.

**Comment by kumar303** [comment]
> The user cannot create two collections with identical names.

We will address this in https://github.com/mozilla/addons-frontend/issues/3993 so I'm dupe'ing it to that one.
