### ISSUE TITLE
Prevent faking invalid config keys in tests

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4313]
We use dependency injection to rely on config values in tests. We should prevent a test from accidentally relying on an invalid config value. Such a failure would indicate a typo or an old config key that had been since renamed.

This test made me think that the feature would be useful: https://github.com/mozilla/addons-frontend/pull/4304/files#diff-9c08b23edee72c13339e20d85241c391R116

**Comment by AlexandraMoga** [comment]
@kumar303 is there anything to be done by QA here? This doesn't have an impact on AMO code as far as I can tell but a confirmation would be helpful.
