### ISSUE TITLE
Display generic errors with an error handler

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4315]
When certain form fields are blank we need to use an error handler to show messages. See https://github.com/mozilla/addons-frontend/issues/4002 . The error handler currently only works for API response errors.

**For QA**: This new feature is not visible yet but please test for regressions in any place we show an error in response to a user action. Example STR:
- Upload an extension
- Sign into AMO
- Try to leave a review for that extension
- This should show an error using the same error handler code

**Comment by AlexandraMoga** [comment]
Tried several scenarios which would generate an error in response to a user action, like for example: rating your own extension, adding same addon to the same collection, flagging your own review, 
The error messages are triggered when expected and no other issues were identified.

![image](https://user-images.githubusercontent.com/31961530/35856715-815f1328-0b3f-11e8-831f-63dedb1e6faa.png)
----------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/31961530/35856727-8703b356-0b3f-11e8-9cf6-4754b41ab173.png)
----------------------------------------------------------------------------------
![image](https://user-images.githubusercontent.com/31961530/35856744-94f1534c-0b3f-11e8-91ce-44f7329d15d3.png)
