### ISSUE TITLE
Remove beta version support

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#4317]
This is part of https://github.com/mozilla/addons-server/issues/7163

The frontend currently exposes beta versions. Since we're going to remove this feature, we need to remove all references to beta versions, gated by a waffle flag.

**Comment by muffinresearch** [comment]
@wagnerand waffle does not exist in addons-frontend. However you can probably use config to amount to the same thing.

**Comment by wagnerand** [comment]
@kumar303 if you have documentation or an example on how to use config, that would be great, thanks!

**Comment by wagnerand** [comment]
STR:

You want to test this together with https://github.com/mozilla/addons-server/issues/7435#issuecomment-365627222.

0. Make sure you have an add-on with at least one beta version.
1. Go the the listing page of the add-on:
 * If the `beta-versions` waffle is enabled, there should be a link to the beta versions page.
 * If the `beta-versions` waffle is disabled, there link should not appear.

**Comment by vcarciu** [comment]
In the new frontend, even if the beta-versions waffle is enabled, the link to beta versions is not available : 
![betalink](https://user-images.githubusercontent.com/1583842/36428329-518b69b6-1658-11e8-9f12-512c98416694.gif)

**Comment by wagnerand** [comment]
@vcarciu Sorry that is due to a hard setting which is for -dev only. It should be fixed once https://github.com/mozilla/addons-frontend/pull/4417 lands, so you can properly test it then.

**Comment by vcarciu** [comment]
Verified as fixed : 
![beta1](https://user-images.githubusercontent.com/1583842/36479810-b2b34a82-1712-11e8-90de-2148413d7e45.gif)
