### ISSUE TITLE
'Log in to flag review' button is not correctly centered

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4318]
Another follow up for [#2517](https://github.com/mozilla/addons-frontend/issues/2517) which sadly I forgot to mention :disappointed:

STR:
1. Access an add-on review's page while logged out (i.e. https://addons-dev.allizom.org/en-US/android/addon/awesome-screenshot-plus-/reviews/)
2. Click on 'Flag' for any of the listed reviews
3. Observe the position of the 'Log in to flag review' button

Actual result:
The button is not correctly centered

Expected result:
The button should be perfectly centered

Notes:
Reproduced on AMO dev with FF58 (Win10 and Android 7.0)

**Comment by muffinresearch** [comment]
Here's a screenshot. This button is a weird thin and wide button. It would be nice to fix that too.

<img width="670" alt="bewertungen_fur_dancing_candy_canes_ _add-ons_fur_firefox" src="https://user-images.githubusercontent.com/1514/35854001-02bda772-0b27-11e8-8c12-ea4e3c501ca4.png">

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-frontend/issues/2056

**Comment by tofumatt** [comment]
Those "weird thin and wide" buttons are the spec for small buttons 😄

But yes, the padding could be improved.

**Comment by vcarciu** [comment]
Verified as fixed : 
![flagreview](https://user-images.githubusercontent.com/1583842/38553334-a273a114-3cc7-11e8-95d3-273f9da7180e.png)
