### ISSUE TITLE
Allow "edition" query param to be passed through to the disco pane API.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4320]
A follow-up from https://github.com/mozilla/addons-server/issues/7489 

Once this lands, passing `?edition=china` on the end of a disco pane URL should show different content.

**Comment by AlexandraMoga** [comment]
This was verified in [mozilla/addons-server/#7489](https://github.com/mozilla/addons-server/issues/7489#issuecomment-363709106)
