### ISSUE TITLE
Fix how localized params are passed through collection actions/sagas

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4323]
The API function requires [a localized string](https://github.com/mozilla/addons-frontend/pull/4201/files#diff-f2a5dd9c232205755bd944f602a2e32fR161) but the action/saga was only [passing a regular string](https://github.com/mozilla/addons-frontend/pull/4209/files#diff-5c509a4b5942e40bfb891f933815dc7bR454).

Interestingly, the point of contact with the API function was through the saga and since the saga doesn't have Flow coverage, the invalid types went unnoticed. Flow would have thrown an error.

**Comment by AlexandraMoga** [comment]
Verified on AMO-stage with FF58 (Win10 and Android 7.0). There were no issues spotted around the available collection pages/features.
