### ISSUE TITLE
Rename taarParamsToUse to discoParamsToUse or similar

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4326]
Since the params passed to the discovery API are not all specifically just for TAAR we should now rename it to reflect reality.

**Comment by kumar303** [comment]
Thanks for filing -- I was looking at this code and thinking to myself, hmm, what is TAAR again? It could probably use some more comments too.

**Comment by tofumatt** [comment]
@KhushilMistry is working on this and has a PR ready–it just needs one more tweak and should be good to merge.
