### ISSUE TITLE
Edit collection URL (slug)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4336]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

A user should be able to:
- Sign in
- View an existing collection that they created (the classic site enables creation)
- Edit the collection URL which is really just the slug (e.g. a readable name) at the end of the URL. The form field for this is *Custom URL*

**Notes for QA**:
- The URL form field looks a little different than the mocks. This is intentional.
- Since URLs always read left-to-right, switching to a right-to-left language will not alter this form field.
- The *Custom URL* error messages are not very helpful. I have filed this bug to address it: https://github.com/mozilla/addons-server/issues/7547

<img width="685" alt="screenshot 2018-01-22 11 21 04" src="https://user-images.githubusercontent.com/55398/35234388-8f9d3152-ff66-11e7-9bb1-27626eb7c463.png">

**Comment by vcarciu** [comment]
Verified as fixed : 
![editslug](https://user-images.githubusercontent.com/1583842/36478740-a4e8575c-170e-11e8-8b96-ed578dad457a.gif)
