### ISSUE TITLE
Notice for add-on dependencies isn't shown

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#4338]
### Describe the problem and steps to reproduce it:
Go to the page of an extension that has listed another extension as a dependency. E.g. [[STG plugin] Load custom group](https://addons.mozilla.org/en-US/firefox/addon/stg-plugin-load-custom-group/)

### What happened?
There was no dependency notice.
<img width="779" alt="screenshot 2018-02-08 00 22 48" src="https://user-images.githubusercontent.com/90871/35948782-3bbcd332-0c66-11e8-9abf-460bdff53cf8.png">

### What did you expect to happen?
Expected to see something like the following:
![screenshot-2018-2-8 stg plugin load custom group](https://user-images.githubusercontent.com/8336638/35940195-606752b2-0c74-11e8-9fe6-e4fb2607108a.png)

**Comment by tofumatt** [comment]
I amended the issue to show a screenshot of the current site where the issue happens; originally I was confused and thought this was an issue with the old site based on the screenshot.

**Comment by bobsilverberg** [comment]
I could be wrong, but I don't think that WebExtensions have a way of specifying that they have another extension as a dependency. If you look at https://github.com/Drive4ik/simple-tab-groups/blob/master/plugins/stg-plugin-load-custom-group/manifest.json there isn't anything in the manifest that says that plugin depends on the Simple Tab Groups extension. 

If the above is correct, then I don't see how we can expose this information on the front-end, what it doesn't actually exist in the metadata. Or is it maintained in the AMO database somewhere?

**Comment by tofumatt** [comment]
The example used in this issue is installable in Firefox 57+ so is a web extension. I'm assuming it's in the AMO database, but it's definitely doable.

**Comment by willdurand** [comment]
Looks like we dont need that anymore.
