### ISSUE TITLE
Use <React.Fragment> over <div>s where possible

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4339]
We wrap a lot of things in `<span>` or `<div>` when we don't need to, simply because JSX needs us to enclose multiple node in a wrapper. But React has a tool for that: https://reactjs.org/docs/fragments.html

We should totally use it. 👍

**Comment by willdurand** [comment]
Hi! Do you know if Babel needs to be updated too in case we want to use the short syntax (`<>`)?

**Comment by tofumatt** [comment]
I would think it does but I don't really like the `<>` syntax anyway; I think it's not very explicit or discoverable, whereas `React.Fragment` is... so I say we just stick with that.

**Comment by kumar303** [comment]
Typing `<React.Fragment></React.Fragment>` might get annoying. I like the shorthand. We could try it out and see.

I was curious about the discoverability; googling *what's an empty html element in React jsx* gave me `React.Fragment` as the fourth result. For our project though, I feel like someone will just ask about it in IRC if they've never seen the syntax.

**Comment by bobsilverberg** [comment]
I'm +1 on @kumar303's comment.

**Comment by tofumatt** [comment]
I definitely dislike the <> tag; it’s easy to miss when scanning through tags, it’s not imported anywhere so it’s harder to trace, it’s less explicit, and maybe I’m spoiled but my editor auto completes Resct.Fragment just fine :-)

- Matt (Sent from mobile)

**Comment by willdurand** [comment]
> it’s easy to miss when scanning through tags [...] it’s less explicit

I'd argue that's the main purpose of this tag 😛

**Comment by tofumatt** [comment]
Hah, I guess so. Alright, fine: I cave! :-)

- Matt (Sent from mobile)

**Comment by SeanPrashad** [comment]
Hey everyone 👋🏽 I was hoping to take this on as my second bug in AMO's front-end and was just wondering if this patch would span **ALL** `<div>`/`<span>` tags within the project?

I don't think it's as easy as `Cmd` + `Shift` + `F` and replacing all occurrences but I might be wrong. Thanks!

**Comment by tofumatt** [comment]
Sadly it’s not as simple as a find/replace, but it's not *too* far off!

This patch will require looking through the components and finding instances where we're wrapping things in a tag simply because JSX requires it. It's probably a fair amount of manual judgment calls, but a good start *would* be to look for empty `<div>` and `<span>` tags with no attributes/props–chances are they're there simply to wrap other JSX and can be converted. You'll want to do it one-by-one though and make sure it doesn't break anything, but fortunately most of our CSS selectors don't rely on nesting/tag-type so you should be 👍

Side note: we do have a "good first bug" tag here: https://github.com/mozilla/addons-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22contrib%3A+good+first+bug%22 if you're looking for other issues. This issue isn't in there but come to think of it is probably fine as a contributor bug, so feel free to work on it.

**Comment by willdurand** [comment]
It looks like this issue is not really "actionable" to me, because it is a nice thing, yet not something we can do. I don't think one should spend a lot of time reviewing all our components and decide to use/not use `React.Fragment`. (The problem with such issues is that they become stale and no one can really work on them)

I'd rather encourage reviewers to suggest the use of `React.Fragment` when it makes sense, which has been the case multiple times already. On this basis, I am closing the issue.
