### ISSUE TITLE
When submitting a new WebExtension version, changelog textarea is not working

### ISSUE THREAD

**Issue by nodeticswww** [mozilla/addons-frontend#4340]
### Describe the problem and steps to reproduce it:

1. Click to submit a new version of a WebExtension
2. Upload the file and proceed to the screen which should have a text area for the changelog and comments text area for the reviewer

### What happened?

Sometimes the changelog text area is not visible at all (by looking at the CSS, it has 'display: none' setting). Sometimes the field is visible but anything you enter there is only shown for the locale you are using.

### What did you expect to happen?

The changelog text area is always visible and whatever is written there is then visible in the add-on history regardless of the language/locale setting of the AMO user.

### Anything else we should know?

Example (change logs visible):
https://addons.mozilla.org/en-GB/firefox/addon/cookiebro/versions/

Example (same add-on, change logs not visible due to different locale link):
https://addons.mozilla.org/en-US/firefox/addon/cookiebro/versions/

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to submit this bug.

This is a good catch. However, we're not spending time to fix this version listing page since it's on the legacy site. Instead, we plan to reimplement the page (see https://github.com/mozilla/addons-frontend/issues/2770). I added a note to that issue to make sure we handle this case.

**Comment by kumar303** [comment]
I noticed that we have a similar issue since we do display release notes for the current version. I filed this to track it https://github.com/mozilla/addons-server/issues/7535
