### ISSUE TITLE
Login required page is quite unstyled

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4341]
### Describe the problem and steps to reproduce it:
Go to a page that requires login (eg. http://localhost:3000/en-US/firefox/users/edit on the `user-profile` branch).

### What happened?
This page appears:
<img width="1349" alt="screenshot 2018-02-08 12 04 51" src="https://user-images.githubusercontent.com/90871/35972133-802c3000-0cc8-11e8-9942-5a0e8f1fb822.png">

### What did you expect to happen?
I expected either an automatic redirect (there's only one option on the page, why not just do it for the user unless that'd be confusing, which maybe it would be) or a more styled page. Even something like a large card on the 404 page would be fine, but this just looks a bit unrefined. 😄

**Comment by tofumatt** [comment]
This actually probably doesn't need UX right away, I'll just do something like the 404 page.

**Comment by willdurand** [comment]
This has been fixed, more or less: https://addons.allizom.org/en-US/firefox/users/edit
