### ISSUE TITLE
Create a styled DL with a renderIfNodes API

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4342]
The User profile page requires something very similar to:

<img width="406" alt="screenshot 2018-02-08 12 50 49" src="https://user-images.githubusercontent.com/90871/35973871-ea2d10e0-0cce-11e8-8389-c424c7d57a28.png">

which also has a handy `renderNodesIf()` helper.

https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonMoreInfo/index.js#L180

I think we could abstract this out into a component for displaying DL-type info with a common style and nicer API.

**Comment by tofumatt** [comment]
For QA: make sure the "More information" section on the add-on details page has no regressions after this issue is fixed.

**Comment by ioanarusiczki** [comment]
I verified on AMO dev using FF58 (Win10) the "More information" section on the add-on details page for display issues. Also checked if the links work as expected. I did not find any problems.
