### ISSUE TITLE
Use React.Fragment when returning multiple elements

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4345]
If you search for `<div>` you will find a lot of components that are rendering multiple elements. We should switch to [`React.Fragment`](https://reactjs.org/docs/fragments.html) for this to reduce HTML clutter, minimize nesting, and cut down on page size.

**Comment by tofumatt** [comment]
I filed this as #4339 😄

**Comment by kumar303** [comment]
Hah. I have been starting my day by writing code *instead* of reading email. It's been great for productivity but I guess I missed your issue 😎
