### ISSUE TITLE
Handle multiple icon sizes in Addon detail response from AMO

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#4346]
see mozilla/addons-server#7514 - we're looking to expand the `icon_url` property in the Addon detail response to be list of size, path pairs, rather than a single path (to the 64x64 icon). 

-We did implement it as a new `icons` property, rather than overload the existing `icon_url` property.

**Comment by eviljeff** [comment]
This blocks implementation of mozilla/addons-server#7514

**Comment by diox** [comment]
We're going to need this soon: as @eviljeff pointed out it blocks the server implementation which itself blocks Firefox from using it, and we don't want to miss the Firefox 60 train.

**Comment by diox** [comment]
See https://github.com/mozilla/addons-server/issues/7514#issuecomment-365795492  : I'd like to do this in a new field called `icons` instead of re-using `icon`. The linked comment has an example of how the response would look once implemented.
