### ISSUE TITLE
Make all visual representations of the user's personal ratings yellow

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4355]
This is a follow-up to PR #4337. There is a question about whether all visual representations of the user's personal ratings should be yellow, or if we should only show yellow stars where a user can interact with them to set their rating.

For example, should the stars be yellow in the attached screenshot, @pwalm? 

![image](https://user-images.githubusercontent.com/142755/35997754-7909798e-0ce8-11e8-9af0-01415758b28c.png)

**Comment by pwalm** [comment]
Yep, all versions of a users star ratings should be yellow, everywhere.

**Comment by kumar303** [comment]
Thanks. I'm pretty sure the only place that they are visible are in the review listing (the screen in this issue).

@bobsilverberg this issue sounds right up your alley if you have bandwidth for it.

**Comment by bobsilverberg** [comment]
I've got the code for this working, but I need assets for the small stars in yellow. We need a small filled-in yellow star, and a small hollow yellow star. I created a filled-in one by taking the existing svg for the grey star and changing the fill colour, but it doesn't look quite right to me. It looks a bit small. See below:

<img width="1001" alt="screenshot 2018-02-12 11 42 17" src="https://user-images.githubusercontent.com/142755/36108119-03f98008-0fea-11e8-9556-be24f863955f.png">

@pwalm or @kumar303 would one of you be able to provide me with the assets I need for this?

**Comment by pwalm** [comment]
Assets can be pulled from the “symbols” page of the Sketch doc

**Comment by ioanarusiczki** [comment]
Verified this on AMO dev with FF58 (Win 10, Android 8.0)
@bobsilverberg I've noticed that the old site had yellow stars for all written reviews and  not only for the user's personal review which gives a better UX experience in my opinion.

![yellow stars](https://user-images.githubusercontent.com/33448286/36893166-b179ffe0-1e0f-11e8-87d1-7c97aa266d5c.png)

Old pages - yellow stars
![old yellow](https://user-images.githubusercontent.com/33448286/36893341-5bb69176-1e10-11e8-943b-aefdcf43c0f5.png)

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki, but I'm pretty sure this is how @pwalm wants it to be. Can you confirm that, @pwalm?
