### ISSUE TITLE
Nano Defender is no longer available on Add-ons Mozilla

### ISSUE THREAD

**Issue by TonyTough** [mozilla/addons-frontend#4357]
Nano Defender, which is a highly valuable and effective Add-on, is no longer available on Add-ons Mozilla:
https://addons.mozilla.org/de/firefox/addon/real-nano-defender/

The Add-on should be available immediately again on Add-ons Mozilla.

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org/
