### ISSUE TITLE
Truncated options from 'Flag' review menu end too abruptly after selection

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4359]
STR:

1. Log into AMO and set your locale to `/ru/`
2. Pick a rated add-on to view its details page
3. Go to the rating section and click on Read all reviews to view all available reviews for this add-on (i.e. https://addons-dev.allizom.org/ru/firefox/addon/awesome-screenshot-plus-/reviews/)
4. Click on 'Flag' for any of the listed reviews and select the second or the last option from the menu

Actual result:
After selection, the text will end too abruptly (it doesn't seem to have a text-overflow rule applied)

Expected result:
The text for the selected option should end with an 'ellipsis' 

Notes:
- it would also be helpful to show a tooltip for truncated options to give the user the possibility to read the full text
- reproduced on all AMO servers with FF58, Win10 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/36026803-540a405a-0da1-11e8-81a0-c4f141fa8af3.png)

**Comment by tofumatt** [comment]
@svitlana-galianova Nice job, two issues with one pull request! 🏅 😄

**Comment by vcarciu** [comment]
Verified as fixed  : 
![russian](https://user-images.githubusercontent.com/1583842/38553457-009f042c-3cc8-11e8-8b52-9cf56ed8ec45.png)
