### ISSUE TITLE
The favicon is not correctly displayed on AMO prod

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4365]
STR:

1. Load AMO-prod - https://addons.mozilla.org/en-US/firefox/
2. Observe the favicon displayed in the page title

Actual result:
The favicon is represented by a green puzzle piece

Expected result:
The favicon is represented by the blue puzzle piece

Notes:
- I see that [#3275](https://github.com/mozilla/addons-frontend/issues/3275) is scheduled for the next push, so it shouldn't be reflected on production, right?
- Reproduced only on AMO-prod, FF58 (WIn10)

![image](https://user-images.githubusercontent.com/31961530/36087602-eb97a052-0fdb-11e8-9473-8ef70fb2077d.png)

**Comment by bobsilverberg** [comment]
This does not reproduce for me on either Firefox or Chrome on OS X. When I go to https://addons.mozilla.org/en-US/firefox/ I see the blue favicon and it is pointing to https://addons.cdn.mozilla.net/favicon.ico. Could it be a caching issue?

**Comment by diox** [comment]
I am seeing this right now - even after hard refreshing or opening in a new browser, when hitting the homepage or https://addons.cdn.mozilla.net/favicon.ico directly I still see the old green puzzle icon.

**Comment by bobsilverberg** [comment]
We think this may be a caching issue with the icon. Adding a query string should allow each client to grab the latest version, so I'm going to do that.

**Comment by kumar303** [comment]
This issue will be addressed by https://github.com/mozilla/addons-frontend/issues/4407

**Comment by AlexandraMoga** [comment]
I'm still reproducing this on -prod. Also tried with a new profile and the green favicon was displayed.
@bobsilverberg are we going to see the changes only after Thursday's push? 

![image](https://user-images.githubusercontent.com/31961530/36720178-eca1d866-1baf-11e8-8a60-08323b84edf4.png)

**Comment by tofumatt** [comment]
Yes, the changes will appear on Thursday when this is deployed.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-prod, FF58 (win10x64)

![image](https://user-images.githubusercontent.com/31961530/36970954-ee3ecd2e-2072-11e8-8c4c-840cfbbe85b8.png)
