### ISSUE TITLE
Useful addon no longer available

### ISSUE THREAD

**Issue by PascalBQ** [mozilla/addons-frontend#4366]
### Describe the problem and steps to reproduce it:

1. did search on Goolge with search string "firefox addon bookmark search"
    https://www.google.be/search?q=firefox+addon+bookmark+search&ie=utf-8&oe=utf-8&client=firefox-b-ab&gfe_rd=cr&dcr=0&ei=QWSBWuSPOpyF1gKKuK7wAQ
2. followed the following link from the list:
    https://support.mozilla.org/nl/questions/1002905
3. result seemed promising ...
    <pasted below>
   Gekozen oplossing

    You can search for bookmarks from the address bar by prefixing your query with an asterisk, e.g. * mozilla support
    You can search for bookmarks from the search bar in the Bookmarks Sidebar (Ctrl+B; Mac: Command+B).
    You can search for bookmarks from the search bar in the Library (Ctrl+Shift+B; Linux: Ctrl+Shift+O; Mac: Command+Shift+B).
        Bookmarks in Firefox 

However, none of the above search methods will show you in which folder a bookmark resides. You can remedy that with the following add-ons.

    https://addons.mozilla.org/firefox/addon/show-parent-folder/
    https://addons.mozilla.org/firefox/addon/go-parent-folder/
    https://addons.mozilla.org/firefox/addon/sidebar-bookmarks-search-plus/ 

4. tried above 3 links, but got message that the page was not available and author had removed the addon... 
=> pitty

### What happened?
Impression existed that addon was found ... but it seems to be removed

### What did you expect to happen?
The functionality as described is certainly what I would expect Firefox' Bookmarks Manager to include 

### Anything else we should know?

I would appreciate to find the possibility to easily export Firefox bookmarks into eg. Excel, with full 'data fields' that document the bookmarks - rather than only the html format/text

THANK YOU
:-)

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons website and related projects, not for an add-on. Sorry to hear the add-ons you were looking for aren't available, but it's up to add-on authors to list/unlist their add-ons and keep them up-to-date.

If you're having an issue with an add-on please contact the developer directly; though given they removed their add-on I understand that might be difficult. Sorry about that 😞
