### ISSUE TITLE
"See more ..." links are not working anymore

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4374]
Steps to reproduce:
1.Go to amo-dev and try the "See more... " links for "Privacy tools" , "Re-imagine search" and "February’s new featured extensions" collections

Expected results:
Collections are opened without any problems

Actual results:
Nothing happens. Collection cannot be opened.

NOTES:
Tested using Windows 10x64, FF Release, AMO-dev
Not reproducible for "See more popular themes"
Possible related to #4330 

Please see video for this bug : 
![seemore](https://user-images.githubusercontent.com/1583842/36151781-4cb03d5e-10d1-11e8-996b-1fae4db52b89.gif)

**Comment by bobsilverberg** [comment]
I'll take a look at this as it sounds related to the work I did for #4330.

**Comment by vcarciu** [comment]
Verified as fixed : 
![seemoresolved](https://user-images.githubusercontent.com/1583842/36199273-bf8a4dbe-1181-11e8-97fa-b2303245eb48.gif)
