### ISSUE TITLE
"&" is interpreted as "&amp" in Edit collection description

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4375]
Follow up from [#4002](https://github.com/mozilla/addons-frontend/issues/4002)

STR:

1. Log into AMO-dev as an admin
2. Select the "Ad Blockers' collection - https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/ad-blockers/
3. Click on Edit this collection
4. Observe the description available in the Edit description section

Actual result:
"&"s are interpreted as "&amp"s

Expected result:
There are no text formatting issues around Edit description for a collection

Notes:
- there was a similar issue addressed here [#4213](https://github.com/mozilla/addons-frontend/issues/4213)
- Reproduced on AMO -dev with FF58, Win10 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/36154985-cbe12606-10db-11e8-837b-39d6f6ba11b7.png)

**Comment by vcarciu** [comment]
Also "<script>alert('problem')</script>" is interpreted as "&lt;script&gt;alert('problem')&lt;/script&gt;"

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF58 (Win10x64 and Android 7.0)

![image](https://user-images.githubusercontent.com/31961530/36718873-f8c9dc6e-1bab-11e8-8edc-80503a718cac.png)
