### ISSUE TITLE
After a new registration, users are not redirected to Edit Profile page in order to change their display names

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4376]
Steps to reproduce:
1.Go to AMO-dev and register with a new account
2.Finish the registration process and click on account confirmation email link

Expected results:
Users are redirected to Edit Profile page in order to add their usernames

Actual results:
Users are not redirected to Edit Profile page and they are logged in as Anonymous - xyz123

NOTES:
Tested using Windows 10x64, FF Release, AMO-dev
Reproducible on all servers
NOT reproducible if registration is made from Developer Hub

Please see a video for this bug : 
![anonymous](https://user-images.githubusercontent.com/1583842/36155030-ec5614fa-10db-11e8-8017-b7dd0e8fe322.gif)

**Comment by kumar303** [comment]
I think this was an intentional change because landing on the old legacy profile page is confusing.

**Comment by tofumatt** [comment]
This will be fixed by #3144 as well I guess, but maybe we'll need to update the redirect page.

**Comment by vcarciu** [comment]
Verified as fixed : 
![displayname](https://user-images.githubusercontent.com/1583842/40312671-2ab05d82-5d1c-11e8-9160-eae7dc5eeb7b.gif)
