### ISSUE TITLE
Unbroken strings are not wrapped for screenshot tips

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4378]
STR:
1. Load AMO dev and from Developer Hub click on Edit information for an already submitted add-on
2. Click Edit for Images section to add a screenshot
3. Insert an unbroken string in the box below "Please provide a caption for this screenshot"
4. Save changes and go to View Listing page.
5. Hover over the screenshot and observe the text.

Expected result:
Text is wrapped.

Actual result:
Text is not entirely displayed and appears cut.

Notes:
This issue is reproducible on AMO dev using FF58 (Win10)

![tips text](https://user-images.githubusercontent.com/33448286/36157591-c813970a-10e2-11e8-9e60-c45497dcf192.png)

**Comment by bobsilverberg** [comment]
Hmm, I'm not sure what we can do about this one. I believe it's the browser itself that is responsible for rendering the tooltip, if we're just using the `title` attribute which is how this is currently implemented. Do we want to implement our own tooltip code so we can have more control over the wrapping? Tbh, I don't know how likely it is that a developer will enter a very long, unbreaking string at the beginning of their caption. Perhaps this isn't a case we need to support?

**Comment by tofumatt** [comment]
Yeah that's a browser limitation; a user who decides to enter garbage text will have their text be cut off. It doesn't break anything so I think this is a won't fix.
