### ISSUE TITLE
Edit collection popup displays layout issues when zoomed in on Android devices

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4379]
STR:
1. Load AMO dev and open the drop down menu below the username
2. Tap on View my collections
3. Tap the name of a collection
4. Tap Edit this collection
5. Zoom in Edit collection popup
6. Observe the layout

Expected result:
Edit collection has no display issues.

Actual result:
Collection name and Description fields are smaller and Cancel button is no longer displayed.

Notes:
This issue is reproducible on AMO dev with FF58 (Android 8.0.0)

![popup](https://user-images.githubusercontent.com/33448286/36159473-79ce1d4a-10e7-11e8-96f2-730a2f488251.gif)

**Comment by kumar303** [comment]
This will probably be addressed by https://github.com/mozilla/addons-frontend/issues/4258

**Comment by bobsilverberg** [comment]
We removed the overlay some time ago. @ioanarusiczki can you please confirm whether this is still an issue, or if this issue can be closed?

**Comment by ioanarusiczki** [comment]
@bobsilverberg This can be closed because of ux changes which led to the removal of the overlay.
Verified on AMO dev - FF65 (Android 8.0)

![edit overlay removed](https://user-images.githubusercontent.com/33448286/54537335-01c5a780-499b-11e9-8e22-938f42dacdf0.gif)
