### ISSUE TITLE
Hello, I would like to collaborate with your project by serving as a translator into Spanish which is my native language

### ISSUE THREAD

**Issue by LuigiBaute** [mozilla/addons-frontend#4380]

**Comment by caitmuenster** [comment]
Hey Luigi! We'd love your help with localization! Can you head over to the  the [L10n wiki](https://wiki.mozilla.org/L10n:Contribute) for more information about how to get started? 

Localization is run through a platform by the name of Pontoon. Here's the link to AMO project on Pontoon: https://pontoon.mozilla.org/en-GB/amo/

**Comment by tofumatt** [comment]
There's also https://wiki.mozilla.org/Add-ons/Contribute#Localization for l10n contributions related to Add-ons.

I'm going to close this issue as there's nothing further to do here, but thanks for your interest in localising the app! 👍
