### ISSUE TITLE
Collection edit fields are too narrow on Android

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4386]
Steps to reproduce:
1.Go to AMO-dev on your Android device
2.Click on any collection and click on "Edit this collection" link

Expected results:
The edit fields width are consistent with the edit page width

Actual results:
Collection edit fields are too narrow

NOTES:
Tested on Android 7.0, FF Release

Please see a screenshot for this issue : 
![narrow](https://user-images.githubusercontent.com/1583842/36205041-035790a6-1196-11e8-9207-22b183353147.png)

**Comment by tofumatt** [comment]
The mobile styles aren't ready for this yet so this will be fixed in #4258.

**Comment by kumar303** [comment]
dup'ing to https://github.com/mozilla/addons-frontend/issues/4258
