### ISSUE TITLE
If a single section fails to load on the home page, all of them fail to load

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4387]
Currently, if any of the sections defined on the home page via `LandingAddonsCard` components fails to load its data (for example, if a collection does not exist in the environment), then all of the sections fail to load and an error message is displayed at the top of the page:

![feb-14-2018 07-46-18](https://user-images.githubusercontent.com/142755/36205042-576596e2-115b-11e8-91c1-9fa634effc96.gif)

We should probably fix this so that any sections that _can_ load _do_ load. There was a suggestion to just hide any sections that fail to load, but I am concerned if we do that, and there's a problem with a section, we might never know about it. Maybe we could display an error message in the section that fails to load? Or is there a way we can make sure we are informed if a situation arises where a section fails to load and is subsequently hidden?

**Comment by jrbenny35** [comment]
I've reported this before, just adding the issue for extra discussion. #3826

**Comment by bobsilverberg** [comment]
We discussed this in today's meeting. @muffinresearch do you think we should up the priority on this?

**Comment by muffinresearch** [comment]
@bobsilverberg Ideally we should try and make the site robust to failures + missing data as much as possible. 

It would be good to look at what we can do here. For example how difficult is it to fix this? Do we have a capability to gracefully fail an individual module if the data's not there or the response fails for any reason?

There might be some broader architectural concerns to think about, so maybe this is one we could discuss further at the all-hands?

**Comment by bobsilverberg** [comment]
> There might be some broader architectural concerns to think about, so maybe this is one we could discuss further at the all-hands?

+1 to that. I'll add it to the agenda.

**Comment by willdurand** [comment]
Likely related (and on my list for the all-hands): https://github.com/mozilla/addons-frontend/issues/3101

**Comment by AlexandraMoga** [comment]
I've verified this on AMO -dev by: 
- deleting a collection 
- modifying the collection slug 
- making the collection private

For the first two scenarios, the respective collection shelf will be removed from the homepage
@bobsilverberg is this the behavior you settled for eventually? 

For the last scenario, I have logged #5287

**Comment by bobsilverberg** [comment]
> For the first two scenarios, the respective collection shelf will be removed from the homepage @bobsilverberg is this the behavior you settled for eventually?

Yes, my apologies for not updating this issue or making that clear in the PR.
