### ISSUE TITLE
Add-ons included inside a collection are not correctly counted

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4388]
STR:

1. Log into AMO dev and select 'View My Collection" from the user menu
2. Click on Create new Collection
3.  Name your collection and include some add-ons
4. Click on Create Collection to view the results
5. Check the number of add-ons displayed in the collection details card

Actual result:
The collection cards says that there are '0 add-ons" in the collection

Expected result:
The number of add-ons included is correctly displayed in the collection card

Notes:
- The number of add-ons will be displayed correctly if you edit the collection and include a new add-on
- reproduced on AMO-dev with FF58 Win10x64

![image](https://user-images.githubusercontent.com/31961530/36206775-423ba180-119c-11e8-97ee-3ca2309475b6.png)

**Comment by AlexandraMoga** [comment]
I've just spotted that this is also happening when editing a collection:

STR
- go to a collection details page
- edit collection
- add a new add-on
- see results

![col count](https://user-images.githubusercontent.com/31961530/36307610-9942f246-1325-11e8-890e-8379e089424a.gif)

**Comment by kumar303** [comment]
If you wait 5 minutes does the correct count appear? It may be a caching issue.

**Comment by AlexandraMoga** [comment]
I've waited more than 30 minutes, refreshed the page but still the number was not updated.

**Comment by tofumatt** [comment]
This seems like a server/API bug, because we are just displaying the data sent down from the API.

I know stats for *add-ons* are disabled on -dev and I think -stage, is that true of collection stats as well @diox? If so we'd need to test this on production.

**Comment by AlexandraMoga** [comment]
I've tested this again on -dev and stage but it seems that the issue is not reproducible anymore. 
Based on these results I'm going to close it.
