### ISSUE TITLE
Explore is highlighted instead of Extensions in the menu when View listing is clicked from dev hub

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4389]
STR:
1. Load AMO stage and go to Developer Hub in Manage my Submissions.
2. Click on Edit information for a submitted ad-on from the list.
3. Click on View Listing.
4. Observe that Explore is highlighted. 
5. Click on the banner or on Explore.
6. Click the back button of the browser.
7. Observe that this time Extensions is highlighted.

Expected results:
Extensions is highlighted after View Listing is clicked.

Actual results:
Explore is highlighted.

Notes: 
This issue is also reproducible for Themes.
This issue is reproducible on AMO stage with FF58 (Win10). 

Extensions

![explore highlighted instead of extensions](https://user-images.githubusercontent.com/33448286/36209093-73d25b4c-11a3-11e8-9204-43f151955794.gif)

Themes

![explore highlighted instead of themes](https://user-images.githubusercontent.com/33448286/36209107-7f0893e6-11a3-11e8-99db-e6134519ca75.gif)

**Comment by ioanarusiczki** [comment]
Another scenario when navigation from dev hub to the add-on detail page is made
Click on View Listing for one of the submitted ad-ons from dev hub
Click Themes from the menu
Observe that both Explore and Themes are highlighted
While being in Themes click one to open it's detail page
Refresh page
Observe that explore remains highlighted

This is reproducible with Extensions tab too on AMO dev with FF59(Win10).

![highlighted menu1](https://user-images.githubusercontent.com/33448286/37842415-bd33ae00-2eca-11e8-8b11-243b999b675d.gif)

**Comment by AlexandraMoga** [comment]
This is similar to #3712

**Comment by tofumatt** [comment]
This is pretty low-priority as loading another page should set the right context, but it is annoying, so marking as a P5 papercut.
