### ISSUE TITLE
Send a parameter in API requests indicating that the API should wrap URLs with outgoing.*.mozaws.net

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#4393]
## User story

* As a site user, go to an add-on detail page (or a similar page) that lists an external link in its metadata. For example, *homepage* is an external link on the [AdBlock Plus](https://addons.mozilla.org/en-US/firefox/addon/adblock-plus/) page.
* Click on the external link
* The request should be served by https://outgoing.prod.mozaws.net/ (or the equivalent dev/stage site) before redirecting to the final destination

## Context

We want to start returning unwrapped URLs by default in the API, instead of having all of them go through `outgoing.*.mozaws.net`. We still want that wrapping to be active for addons-frontend though, so it needs to send addons-server a parameter that the API will recognize that will enable the wrapping.

See https://github.com/mozilla/addons-server/issues/7513 for more details

**Comment by vcarciu** [comment]
Tested for regressions, everything looks fine.
