### ISSUE TITLE
Keyboard navigation issues in the Edit collection overlay

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4396]
Follow up for [#4002](https://github.com/mozilla/addons-frontend/issues/4002)

STR:

1. Log into AMO-dev and select one of the collections available on the homepage
2. Click on Edit this collection to trigger the collection edit dialog
3. Press Esc on your keyboard 

Actual result:
The dialog can't be closed by pressing Esc

Expected result:
Esc closes the edit collection dialog

Notes: 
- one more issue regarding keyboard accessibility is TAB navigation; keyboard users need to tab through other focusable elements before the focus shifts to the edit overlay
- reproduced on AMO dev, FF58 (Win10x64)

Here is  a representation for the TAB navigation:
![tab nav](https://user-images.githubusercontent.com/31961530/36260705-dc23152a-126a-11e8-8fc7-b8cde3f80ba9.gif)

**Comment by AlexandraMoga** [comment]
Update:

- keyboard navigation arrows (for scrolling up or down) are also not working inside the overlay; the background content is the one that moves:

![navig arrows](https://user-images.githubusercontent.com/31961530/37714201-a4c3af14-2d21-11e8-8799-87111eb3206b.gif)

**Comment by kumar303** [comment]
Ah, this isn't good. We are removing the overlay in https://github.com/mozilla/addons-frontend/issues/4623
