### ISSUE TITLE
View/Edit Profile options will trigger a Page not found

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4397]
STR:

1. Log into AMO-dev
2. Click on View/Edit profile in the user menu

Actual result:
The user is redirected to a Page not found

Expected:
The user is redirected to view/edit his profile

Notes: 
- not sure if this has any connection to [#4342](https://github.com/mozilla/addons-frontend/issues/4342)
- reproduced on AMO-dev, FF58 (Win10x64, Android 7.0)
- the profile page will be displayed after page refresh

Video:
![profile error](https://user-images.githubusercontent.com/31961530/36263930-02fe1a92-1274-11e8-9466-845bb9486d96.gif)

**Comment by tofumatt** [comment]
Shoot, a change to the header was committed by mistake. I’ll revert it before the next tag.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF58 (Win 10).
