### ISSUE TITLE
Show when an add-on is using experimental API

### ISSUE THREAD

**Issue by mconca** [mozilla/addons-frontend#4402]
### Describe the problem and steps to reproduce it:
For the first time, WebExtensions supports experimental API (tab hiding, in this case). MDN does a great job of labeling these as experimental and warning developers that the API could change or even go away. For example: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/tabs/hide

Users who install an extension, though, have no idea if that extension is using an experimental API. With any luck, the developer marked their add-on as experimental, but they may not have.

### What happened?
If the experimental API used by the developer changes or goes away in a future release of Firefox, the extension itself may misbehave and even break.  The user would likely have no idea what happened.

### What did you expect to happen?
Just like MDN warns the developer, it would be nice if AMO warned the user (at install time) that the extension is using an experimental API and that it could lead to unexpected behavior or even complete failure of the extension.

**Comment by jvillalobos** [comment]
We already support an experimental flag for add-ons which is shown in the listing header. [See this one](https://addons.mozilla.org/addon/amo-admin-assistant/), for example. So, the question becomes: how do we know APIs are experimental and how do we enforce the flag?

IIRC, the linter is frequently updated to keep up with API additions. If that data includes the experimental state, we could use the linter to detect experimental APIs and flip the experimental flag on by default (/cc @EnTeQuAk).

Developers can change this flag whenever they want. It doesn't sound like this is a situation where we would want or need to force the flag state on them. Do you agree, @mconca?

**Comment by jvillalobos** [comment]
(Clicked close button accidentally)

**Comment by mconca** [comment]
@jvillalobos I didn't want to prescribe a solution in the initial issue report, but I was thinking something very similar. Using the linter to detect experimental API and then setting the flag automatically sounds like a good idea.  We probably don't have to force the flag state, although if we see people reversing it, we might want to revisit this idea.

Realistically, there should only be a very small number of experimental API at any given time.  My guess is that we'd always have less than six. That could make maintaining the linter by hand a much easier job (assuming it is practical as an idea in the first place).

**Comment by willdurand** [comment]
@jvillalobos is this still something to consider (and worth keeping in the backlog)?

**Comment by jvillalobos** [comment]
I don't think so.
