### ISSUE TITLE
The last update for themes is not accurate on the newfrontend 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4404]
STR:
1. Load AMO stage 
2. From Developer Hub upload a new theme design for an older theme from the list.
3. Approve the new design from Reviewer Tools - Themes Updates.
4. Go to Manage my submissions in My Themes tab and click on Edit listing for the edited theme.
5. Check the View Recent Changes.
6. Click on View listing and observe the Last Updated field.
7. Click on Classic desktop site view and observe the Updated field.

Expected results:
Last Updated field on the new front end is today. 

Actual results:
Only the classic view displays the date correctly for the updated theme.

Notes:
This issue was verified on AMO stage with FF58 (Win10).

![last updated](https://user-images.githubusercontent.com/33448286/36308055-a3e405f8-1327-11e8-8a08-8621d14d53e4.gif)

**Comment by kumar303** [comment]
If you wait 5 minutes, does the correct date appear? I'm wondering if it's a caching issue.

**Comment by ioanarusiczki** [comment]
@kumar303 No, the date on new front end is still not updated. I made the changes 3 days ago.

**Comment by tofumatt** [comment]
Wondering if this could be an API bug, @diox? I hate passing the buck on so many of these issues but we're just loading the data we get from the API, so it could be the old site's doing some more direct DB calls and we're getting stuff from ElasticSearch that missed making an update. 🤷‍♂️

**Comment by diox** [comment]
This is an API bug, probably caused by the fact that in database, themes have 2 separate models, and the legacy frontend must have a hack in place to use the right one and not the API. This will go away once we migrate to static themes, though.
