### ISSUE TITLE
Change puzzle favicon to a Firefox favicon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4407]
This issues has been moved from https://github.com/mozilla/addons/issues/632 into this repo. There has already been quite a bit of discussion about it, which I won't repeat here. Please see the other issue for the details.

**Comment by bobsilverberg** [comment]
I did some work on this today, trying to get webpack to write the new favIcon file as an asset and then use the address from webpack in ServerHtml.js. There was a problem that the import I had to add to ServerHtml.js was throwing an error, because webpack didn't seem to be using a loader to process it. Some testing revealed that the same import did work in a different component (e.g., the component), so it does point to an issue with ServerHtml.js.

I am attaching a patch with my changes thus far so this issue can be (somewhat) easily picked up again when I or someone else has the time.

[patch.txt](https://github.com/mozilla/addons-frontend/files/1732286/patch.txt)

**Comment by willdurand** [comment]
I guess the current favicon is okay. It gives the site a personality. I also believe that this might change with Trailhead and so on, but so far..  no one really complained.

**Comment by mlissner** [comment]
I mean.... *I* complained, and others agreed that it could be better over in the other issue this was was copied from: https://github.com/mozilla/addons/issues/632. Hell, @bobsilverberg even made a patch! You're the boss, but I do still think this is a valid issue and that the favicon for the site is weird.
