### ISSUE TITLE
Remove beta version code

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4420]
As it turns out, we can rely on the API to flip beta versions on/off so we can remove all the code added by https://github.com/mozilla/addons-frontend/pull/4353 which was for flipping beta versions on/off on the frontend.

A quick fix for this was added in https://github.com/mozilla/addons-frontend/pull/4417

For QA: this patch will not add new features but please test for regressions in add-on detail pages

**Comment by wagnerand** [comment]
I don't expect us to go back to beta versions. I propose that we remove the entire beta handling code for one of the next few pushes instead of removing just the config for the very next push and then the remaining beta code a week later.

**Comment by kumar303** [comment]
Sure, that's fine, whatever is easier. Removing all of the code sounds good.
