### ISSUE TITLE
Clicking on 'View Profile' after changing the account name will lead to a 404

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4421]
STR:

1. Log in to AMO and click on Edit Profile form the user menu
2. Change your username and click on Update profile
3. Go back to AMO and select View profile

Actual result:
A 404 page is triggered and the URL still shows the previous account name

Expected result:
Updated user profile is loaded

Notes:
- the user has to refresh AMO homepage if he wants to see the updated profile
- also happens when clicking on View My Collecion
- reproduced on all AMO servers with FF58 Win10x64

![profile 404](https://user-images.githubusercontent.com/31961530/36474446-2eb1f876-1700-11e8-99ee-730c7f2cc92a.gif)

**Comment by tofumatt** [comment]
Seems like stale data sticking around in the cookie? I venture this will probably be fixed by #3144 because then we'll update the cookie/state on username change?

**Comment by willdurand** [comment]
should be fixed by https://github.com/mozilla/addons-frontend/pull/4922

**Comment by AlexandraMoga** [comment]
I'm going to mark this as verified  on AMO-dev, since the exact same steps are no longer applicable after #4922 

**Postfix:**
![profile 404](https://user-images.githubusercontent.com/31961530/40057479-15af688e-5857-11e8-9813-aae5b8833a96.gif)


@willdurand please note that this can still be reproduced if the user initiates the action on the legacy pages. Do you think a follow up issue would be worth or, considering that the problem is reproducible only on the legacy site, it should be left as it is?
