### ISSUE TITLE
AMO Stage is down

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4423]
Steps to reproduce:
1.Load AMO Stage

Expected results:
AMO Stage loads successfully 

Actual results:
AMO Stage returns 503 

NOTES:
Not reproducible on -dev 
This is affecting the release testing

**Comment by tofumatt** [comment]
https://addons.allizom.org/en-US/firefox/ loads fine for me.

**Comment by vcarciu** [comment]
The problem was solved.
