### ISSUE TITLE
Add a platformFiles map to internal addon object and use it to replace installURLs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4426]
This is a spin-off from issue #2757 because that issue is quite large. It will require a `platformFiles` map in order to get the correct permissions for an addon, and that `platformFiles` map can also be used to fulfill the purpose of the current `installURLs` map.

This issue is about creating the `platformFiles` map and removing the `installURLs` map.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa: not needed" ?

**Comment by bobsilverberg** [comment]
Some QA would be good, but I'm not sure which STRs should be tested. It mostly affects installing addons, so some checks to make sure there are no problems with installing would be great. Is that reasonable, or is that too vague?

**Comment by kumar303** [comment]
Yes, since this touched a lot of installation code, it would be helpful to check for regressions.

**Comment by AlexandraMoga** [comment]
We have looked for regressions around add-on installation (in AMO, Discopane and Addons manager) and everything seems to be working as expected.
Based on that, this can be marked as verified fixed.
