### ISSUE TITLE
Update docs to specify that xpinstall.signatures.dev-root needs to be added

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4428]
The pref `xpinstall.signatures.dev-root` mentioned at https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md#install-add-ons-for-development does not exist by default in Firefox and therefore needs to be added. We should mention that in the docs along with how to add it.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg

**Comment by championshuttler** [comment]
Can i work on this as my first contribution?

**Comment by bobsilverberg** [comment]
Certainly, @championshuttler, go for it.

**Comment by wagnerand** [comment]
@championshuttler Hey, I am checking-in on this. Are you still working on it? Do you need help?

**Comment by championshuttler** [comment]
@bobsilverberg , do i need to add this into separate file?

**Comment by bobsilverberg** [comment]
Closed via #4950

**Comment by AlexandraMoga** [comment]
Could you please specify if there is any QA required for this?
Thank you

**Comment by championshuttler** [comment]
Hi @AlexandraMoga, I am attaching the screenshot of changes I made. I think its enough ;) 

![screenshot-2018-5-11 mozilla addons-frontend](https://user-images.githubusercontent.com/22130317/39915186-dbf71964-5524-11e8-9290-51cc414963b9.png)
