### ISSUE TITLE
Add-on name is not displayed in Install prompt on Android

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4435]
STR:

1. Access AMO homepage on your Android device
2. Go to an add-on details page and tap on Add to Firefox (i.e. https://addons.mozilla.org/en-US/android/addon/ghostery/)
3. Check the information displayed on the install prompt

Actual result:
The add-on name is not correctly rendered

Expected result:
The add-on name is correctly displayed

Notes:
- reproduced on all AMO servers with FF60.0a1, Android 7.0
- I wasn't able to reproduce it with FF release

![image](https://user-images.githubusercontent.com/31961530/36547950-b5b791e4-17f7-11e8-8b03-bfc09b331f91.png)

**Comment by tofumatt** [comment]
On Firefox release what does the same screen look like, out of curiosity? I'm wondering if it's changed and there's a new attribute we need to add or if something that used to work broke 😄

**Comment by tofumatt** [comment]
This could be a very unpleasant bug (though fortunately it's not happening in release so we have time to fix it).

**Comment by AlexandraMoga** [comment]
A screenshot from FF release, for comparison:

![image](https://user-images.githubusercontent.com/31961530/36581760-54984afe-1877-11e8-8126-1cfa8deb78d0.png)

**Comment by tofumatt** [comment]
Thanks! So it looks like something has changed in Nightly... are we sure this isn't a bug in Nightly then? We haven't changed anything around this.

**Comment by AlexandraMoga** [comment]
@tofumatt should we file an issue in Bugzilla then, or do you need to investigate more on the AMO side?

**Comment by tofumatt** [comment]
I haven't looked into it further but given we changed nothing (that I know of) it is worth filing a bugzilla issue I think, because it seems likely to be a Firefox bug.

**Comment by AlexandraMoga** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1442155

**Comment by kumar303** [comment]
I [removed our use of `InstallTrigger`](https://bugzilla.mozilla.org/show_bug.cgi?id=1442155#c1) to try and deduce the problem. This seems like a platform issue.

**Comment by AlexandraMoga** [comment]
This was verified in [Bug 1442155](https://bugzilla.mozilla.org/show_bug.cgi?id=1442155)
I believe this issue can be closed now.
