### ISSUE TITLE
Malwarebytes – Add-ons for Firefox : disapeared again

### ISSUE THREAD

**Issue by mazesy** [mozilla/addons-frontend#4440]
Hi,

Not an AOM issue so please pardon me if my report is off-topic.

I'd just wish to know what is happening with [Malwarebytes – Add-ons for Firefox](https://addons.mozilla.org/en-US/firefox/addon/malwarebytes/) which is experimental by the way, if that may be part of the answer : it's disappeared again. I don't use this extension myself but was seeking for its development status.

Thanks.

**Comment by tofumatt** [comment]
Unfortunately we won't be able to help; this is the issue tracker for the add-ons site and related projects, we cannot give help for an add-on.

If you're having an issue with an add-on please contact the developer directly; I'm not sure if doing a web search for their info will yield contact info but they'd need to be contacted directly for help. Cheers!
