### ISSUE TITLE
Different counts shown for “Reviews” on detail page

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#4442]
On an extension detail page, there are two different values for “Reviews” on the same page: One at the top, and one in the “Rate your experience” block. One is both star ratings and written reviews, and one is just written reviews:
![538b0d5c-bbac-42d8-adc8-ccff6e859f5c](https://user-images.githubusercontent.com/6797635/36614146-948c5f06-1890-11e8-8dbe-ff0b4dc79ee5.jpeg)

We just need to clarify what is what:
- the top number should have a subhead of “Ratings & reviews”
- The copy around the number in the “experience” block should read “Read all [number] written reviews”

**Comment by tofumatt** [comment]
Just FYI: a subheading of "Ratings & reviews" will likely make for very crammed text in German locale. That section is already quite tight in German... could we get away with just "Ratings" there?

**Comment by pwalm** [comment]
@tofumatt yep, “Ratings” works.

**Comment by ioanarusiczki** [comment]
@tofumatt The "reviews" in the experience section didn't change into "written reviews" . If this remains unchanged I will mark it as verified fixed. 

![written reviews and ratings](https://user-images.githubusercontent.com/33448286/36662041-d22aa53c-1ae5-11e8-8275-83f7fd721749.png)

**Comment by tofumatt** [comment]
I think it should remain unchanged because it takes up less space and we don’t differentiate with the word “written” elsewhere.

So yes I think you can mark it verified :-)

- Matt (Sent from mobile)

**Comment by ioanarusiczki** [comment]
Ok, thanks, I'll mark it verified fixed.
