### ISSUE TITLE
Moved extension page is not found

### ISSUE THREAD

**Issue by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [mozilla/addons-frontend#4453]
### Describe the problem and steps to reproduce it:
I previously installed the extension 3P Request Blocker 1.0.22.1. I opened the about:addons page, opened the 3P Request Blocker 1.0.22.1 extension page, clicked on the reviews link.

### What happened?
The page https://addons.mozilla.org/en-US/firefox/addon/3p-request-blocker/reviews/ (Page not found) has been opened.
### What did you expect to happen?
An extension review page should have been opened, previously it was at https://addons.mozilla.org/en-US/firefox/addon/3p-request-blocker/reviews/, maybe now it's at https://addons.mozilla.org/en-US/firefox/addon/3prb/reviews/ .

**Comment by jvillalobos** [comment]
The review link is exposed by the API, and should update on a daily basis. It sounds like you clicked on the link in the interval between the add-on URL being changed by the dev and the API reloading it. It should only be a temporary issue, and rare since add-ons normally don't change URLs.

**Comment by SCmkQrK1NhwcWoPJF3FImaqHnG2PqPLWBt2GtSU** [comment]
Strange, but within 1 month, nothing is automatically fixed. I had to update manually.
