### ISSUE TITLE
Malicious pop up from advertiser or other malware only allows "ok" to be pressed all else is locked.

### ISSUE THREAD

**Issue by kitkat189** [mozilla/addons-frontend#4467]
### Describe the problem and steps to reproduce it:
Firefox for IOS on iPad Pro with latest Firefox. A malicious advertiser issues a pop up where you only can enter ok to exit. All windows and controls in Firefox are locked. Seems like bug 61098 and 432687 were allowed back in, or never fixed. Only way out is to uninstall Firefox as could not control history and start in safe mode on iPad. This will force me to use safari or chrome. This happens all the time. 

### What happened?
The pop up dialog was from http://reward debit cards.top  credits itself from "Amazon.com User"
I was not on, nor any widow opened on Amazon.com. Nor clicked on any advertisement.

### What did you expect to happen?
I am unable to use Firefox on iPad Pro — this seems to be a bug that just came back. 61098 and 432687. I NEED TO BE ABLE TO KILL THAT WINDOW AND STOP RECURRENCE.

### Anything else we should know?
<!-- Please include a link to the page, screenshots and any relevant files. -
PLEASE LET ME KNOW WHAT INFORMATION YOU NEED.

**Comment by kitkat189** [comment]
The malicious site is "http://rewarddebitcards.top "

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for Firefox.

If you could please file this bug in Bugzilla at https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox%20for%20iOS that would be great. Thanks so much! 😄

**Comment by kitkat189** [comment]
Matthew, this site was referred to by an entry related to add on 13176
which is no longer existing and is related to my bug entry. I got a 404 on
the reference in Mozilla support.
This entry was entered on Oct 30, 2010 at 3:39.43 PDT by cor-el.
I will re enter in bugzilla. Thanks.

**Comment by kumar303** [comment]
> This will force me to use safari or chrome. 

FWIW, I've seen the same exact thing in Mobile Safari from malicious ads. I suggest using [Firefox Focus](https://www.mozilla.org/en-US/firefox/mobile/)! It would be great to fix this though.

**Comment by kitkat189** [comment]
Thank you. I would be happy if this exact problem DOES NOT happen again
when I close and reopen Firefox. I am unable to set
browser.sessionstore.max_resumed_crashes to 0  as suggested in some
solution on the iPad Pro, so on restart I do do not encounter the problem
instantly.
I would also like to be able to reset the history on the iPad from the
general settings in the main iPad menu, just like Safari, instead of
forcing me to reopen Firefox to do those settings.
I do not mind to use Firefox focus, except it does us no good in banking
logins, where you have to re-certify and prove who you are.
As a side note, I have not encountered this issue on Safari on the iPad Pro
to be exact.
Many thanks for the Firefox developers and support people.
