### ISSUE TITLE
1 Click Video Download link broken

### ISSUE THREAD

**Issue by MarkOliva** [mozilla/addons-frontend#4470]
### What happened?
Leads to a Mozilla "can't find it" page

### What did you expect to happen?
Download the app.
### Anything else we should know?

http://www.clickvideodownload.com/download.php

**Comment by tofumatt** [comment]
Unfortunately the add-on has been unlisted; you'll need to contact the author at http://www.clickvideodownload.com/contact.php and request they re-publish their add-on.
