### ISSUE TITLE
Create a ReportUserAbuse component

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4473]
We'll need a component similar to the `ReportAbuseButton` but for the user abuse report feature on the user profile page.

It should use the `DismissibleTextForm` component though, unlike `ReportAbuseButton` which doesn't as it predates that component.

<img width="377" alt="screenshot 2018-02-28 23 01 13" src="https://user-images.githubusercontent.com/90871/36818043-4a90d360-1cdb-11e8-9217-6e342e023f6b.png">

**Comment by tofumatt** [comment]
QA: To test this please make sure the add-on abuse report functionality remains intact.

(This will affect the abuse report reducer so it's important to make sure add-on abuse reports still work after this is fixed.)

**Comment by vcarciu** [comment]
Verified abuse reports from different places and everything looks fine.

**Comment by ioanarusiczki** [comment]
I made some tests to check report abuse functionality and it seems to be alright !
Verified this issue on AMO dev with FF59 (Win 10 and Android 8.0).
