### ISSUE TITLE
Some Add-on install sources are missing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4475]
This is a follow-up to https://github.com/mozilla/addons-frontend/issues/4372

1. `src=featured` -  only works when accesing an add-on details page from AMO homepage; doesn't work for add-ons featured in [Extension/Theme homepage](https://addons.allizom.org/en-US/firefox/extensions/) or [Category pages](https://addons.allizom.org/en-US/firefox/themes/nature/)
2. ~~Regarding Filtered groups - filters are normally applied after executing a search; this means that the `src=search` param will always precede  the `src=filter` parameter, [like in this example](https://addons.allizom.org/en-US/firefox/search/?platform=windows&q=search&sort=rating)~~ This will not be addressed as part of the issue.
4. `src=rating` - doesn't work for _Top Rated_ add-ons shelf  available in [Extension/Theme homepage](https://addons.allizom.org/en-US/firefox/extensions/) or [Category pages](https://addons.allizom.org/en-US/firefox/themes/nature/); ~~not working as a filter parameter because of **point 2.**~~
5. ~~`src=created` - there is no _Recently added_ filter on the new frontend, only _Recently updated_; maybe we need a parameter for this option;~~ Since this has been implemented as a search filter on the new site, we use `src=search` instead.
6. `src=hotness` - doesn't work for _Trending_ add-ons shelf  available in [Extension/Theme homepage](https://addons.allizom.org/en-US/firefox/extensions/) or [Category pages](https://addons.allizom.org/en-US/firefox/themes/nature/); ~~not working as a filter parameter because of **point 2.**~~

(**EDIT**: The `src=hotness` and `src=rating` indicators do not apply to search results; those are always given `src=search`)

**Comment by kumar303** [comment]
> Regarding Filtered groups - filters are normally applied after executing a search; this means that the `src=search` param will always precede the `src=filter` parameter, like in this example

What did you mean by `src=filter` here? I don't see that on the old or new site and I didn't see it in your example link.

**Comment by kumar303** [comment]
@AlexandraMoga Heh, whoops, I forgot to tag you in my question up above.

I'm going to land a patch that fixes the parts of this issue that are not crossed out in the description. If something more should be done about `src=filter`, please file another issue.

**Comment by AlexandraMoga** [comment]
@kumar303 Sorry for misleading you with my 'src=filter' example.

I think in fact that you might have answered my question here:

> (EDIT: The src=hotness and src=rating indicators do not apply to search results; those are always given src=search)

What you actually mean here is that `src=search` will always be the parm sent, regardless of the search filters (i.e _Top Rated_) I apply in my search results, right?

**Comment by kumar303** [comment]
Yep, that's what I meant.

**Comment by AlexandraMoga** [comment]
Verified On AMO-dev with FF58, Win10x64
`src=featured` , `src=rating` and `src=hotness` are also sent now from Extension/Theme homepage or Category pages
