### ISSUE TITLE
AMO homepage is opened for some extensions when pressing the "Contribute now" button

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4478]
Steps to reproduce:
1.Go to https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/?src=search
2.Press the "Contribute now" button

Expected results:
User is redirected to contributions page 

Actual results:
A new AMO homepage is opened

Notes:
Not reproducible for all extensions with contributions set.

Please see video for this bug:

![donate](https://user-images.githubusercontent.com/1583842/36869500-ac38e91c-1da4-11e8-9197-e6ce0c013921.gif)

**Comment by diox** [comment]
Turns out this is entirely an addons-server issue: https://github.com/mozilla/addons-server/issues/7691
