### ISSUE TITLE
Investigate a caching strategy

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#448]
Since all of the data that we depend on is in the URL and we are anonymous only we should be able to add a good amount of caching in front of the node server. This will avoid slamming the API and dealing with high load in node.

@jasonthomas what are your thoughts? Can we add a caching proxy in front and set some headers?

**Comment by muffinresearch** [comment]
The alternatives @mstriemer and I discussed were to cache the API response our end, but if it's possible to use infrastructure to solve this it will be simpler and likely easier to manage in general.

**Comment by jasonthomas** [comment]
+1
We can leverage nginx's microcaching here. That is what we are using today for blocklist and versioncheck endpoints.

**Comment by jasonthomas** [comment]
https://www.nginx.com/blog/benefits-of-microcaching-nginx/

**Comment by muffinresearch** [comment]
@jasonthomas sounds great. Do you want this bug left open or should we file an ops bug instead?

**Comment by jasonthomas** [comment]
Let's just keep this open, no need to file a ops bug.

Are there any paths we don't want to cache?

> Can we add a caching proxy in front and set some headers?
Are we planning on setting Cache-Control headers in addons-frontend response? If not, what should I set the max-age for objects? For blocklist and versioncheck I've set it to 60 minutes.

What other headers would you like to set here?

**Comment by jasonthomas** [comment]
I've deployed a nginx caching configuration onto -dev. Cached responses will contain X-Proxy-Cache: HIT in the response header. Also I've set Cache-Control header max-age to 3600 seconds.

We may want to lower max-age or disable caching on -dev all together. Let me know what you would like to do here.

**Comment by muffinresearch** [comment]
What do we do for -dev elsewhere wrt caching like this? I suppose not having it enabled would expose problems with the underlying service sooner as opposed to covering them up with the cache. But since deploys should bust the cache it wouldn't necessarily get in the way anyway.

**Comment by jasonthomas** [comment]
> What do we do for -dev elsewhere wrt caching like this?

I forgot that we flush nginx cache today on -dev for AMO static assets after deploy. We can do the same here for for discovery cache on -dev.
