### ISSUE TITLE
Homepage content should have different add-ons for Android/other clientApp

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4485]
Steps to reproduce:
1.On your Android device, open AMO prod
2.Open a collection listed on Homepage(ie. Bookmarks) and open the first extension listed : https://addons.mozilla.org/en-US/android/addon/evernote-web-clipper/?src=collection

Expected results:
All extensions listed in these collections should be available for Android

Actual results:
"The add-on is not available on your platform" red banner is displayed

NOTES:
Reproducible for many extensions from homepage collections or promo banners
Example from promo banner : https://addons.mozilla.org/en-US/android/addon/search-site-we/?src=hp-dl-promo

Please see a video for this bug : 

![androidunavailable](https://user-images.githubusercontent.com/1583842/36905521-40f0db90-1e3c-11e8-8b36-3aa039ce8936.gif)

**Comment by tofumatt** [comment]
This is an issue for editorial and the content we show based on `clientApp`. We should have content for both mobile and desktop from an editorial perspective, including collections and other content we include.

It's worth checking to see if that's important to editorial as I think the majority of visitors are desktop users. Maybe it would be best just to hide certain cards if the user is on Android for now.
