### ISSUE TITLE
Small size screenshots/pics are enlarged (zoomed in) and unclear (pixelated)

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4486]
STR:
1. Load AMO dev and from Dev Hub go to a submitted add-on from the list.
2. From Edit information click on Edit Images and add some screenshots/images but make sure they have smaller sizes (I resized a sample to 400 pixels width and 225 pixels height)
3. Click Save changes.
4. Click on View Listing and open the screenshots with the screenshot viewer.
5. Check the image opened.

Expected results:
Image is clear.

Actual results:
Image is enlarged and quite unclear.

Notes:
This issue is reproducible on all AMO servers with FF58 (Win10).
Larger images have a similar tendency but they look much clearer. 

I attached a comparison of the Screenshot viewer with the native Windows Photos app.
The 400x225 sample 
![photos versus screenshot viewer2](https://user-images.githubusercontent.com/33448286/36907707-f76b27c2-1e41-11e8-9fa8-a88b4dc6ed89.gif)

The large image 3180x1975 
![photos versus screenshot viewer](https://user-images.githubusercontent.com/33448286/36907941-97b350b0-1e42-11e8-8de0-cc1a709fe184.gif)

**Comment by kumar303** [comment]
Ugh, yeah, I really want to fix this. We're already tracking it in https://github.com/mozilla/addons-frontend/issues/4197

**Comment by tofumatt** [comment]
That said: a 400x225px screenshot is very small; on a modern 13" laptop's 2x DPR monitor that will be either illegibly small or pixelated when enlarged.

We do have to improve the screenshot viewer but I don't think this is a bug. Either option is bad, I think this one is better.

**Comment by ioanarusiczki** [comment]
@kumar303 @tofumatt It's really good that it's being tracked !  To add -  680x480 size images don't look clear either, or any other sizes if we make a comparison with other image viewers. There is room for improvement. 
Thanks for answering so fast!
