### ISSUE TITLE
Truncate the long screenshot descriptions

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4499]
Steps to reproduce:
1.Submit and approve an extension containing a long description for a screenshot
2.After auto approval, go to extension's detail page
3.Open the screenshot

Expected results:
Screenshot is seen at its full size and description is truncated(An option to see all description should be added)

Actual results:
Screenshot is seen minimized in order to make space for the long description

NOTES:
Reproducible on all servers

Please see video for this issue : 
![screenshotissues](https://user-images.githubusercontent.com/1583842/36980670-abbb52e4-2093-11e8-9043-249ece2f44de.gif)

**Comment by tofumatt** [comment]
Seems like we should have a max-length for screenshots much below that amount. I don't think there's any value in having screenshot descriptions of that length, so maybe this should be handled by the server? cc @diox 

We could easily truncate it on the front-end but that's a bad UX; the developer will add a long-winded screenshot then be surprised when it's cut-off on the site.

**Comment by diox** [comment]
It's a fairly low priority issue (if a developer wants to mess up with their own listing, that's their prerogative) but there should probably be a limit on the server side, yes. @vcarciu could you file a bug for this in addons-server ?

**Comment by realslimshanky** [comment]
@diox should I go ahead and create an issue while @vcarciu is unavailable?

**Comment by diox** [comment]
@realslimshanky sure, anyone can create that issue :) Make sure it does not exist already first.

**Comment by willdurand** [comment]
Closing as it should be restricted by the server.
