### ISSUE TITLE
Create a new collection with add-ons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4502]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

A user should be able to:

- Sign in
- Create a collection
- Enter a name, description, URL (implemented in https://github.com/mozilla/addons-frontend/issues/4003)
- Add some add-ons to the collection before saving
- Save the collection

**Comment by bobsilverberg** [comment]
We have decided not to support this workflow. A user must create a collection first (which means simply giving it a name and clicking "Create collection") in order to add add-ons to it.
