### ISSUE TITLE
Saga helpers for creating a collection

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4505]
We need saga helpers to facilitate creating a collection #4003 

For QA: please check for regressions in any of the existing collection pages and in particular with the "Edit a collection" feature.

**Comment by ioanarusiczki** [comment]
Verified this issue on AMO dev with FF59(Win10). 
I filed https://github.com/mozilla/addons-frontend/issues/4729 and https://github.com/mozilla/addons-server/issues/7975 for observed issues.
