### ISSUE TITLE
AMO is returning a server error after any search related action

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4507]
STR:

1. Go to AMO-dev homepage and perform a search

Actual result:
A server error is received after any search action

Expected results:
Search results are listed

Notes:
- reproduces also  for 'See more" links and  Collections listed on homepage

![server error](https://user-images.githubusercontent.com/31961530/37038329-29178a7c-215d-11e8-8a1e-dd9f36aa46be.gif)

**Comment by tofumatt** [comment]
Guessing this is an issue with the API returning bad responses, I can investigate in a few minutes if no one else gets to it.

**Comment by kumar303** [comment]
I see this in the console:

"The currentPage property cannot be undefined"

Our source maps are broken on dev 😞 but this comes from either `Paginate` or `PaginatorLink`

When I checked locally, this is a regression from https://github.com/mozilla/addons-frontend/pull/4503

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO dev and stage, with FF58, Win10x64

![search working](https://user-images.githubusercontent.com/31961530/37079669-0ac21134-21ec-11e8-96d0-30630d432588.gif)
