### ISSUE TITLE
Source maps are not working on dev

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4508]
### Describe the problem and steps to reproduce it:

Open the web console and trigger some kind of error. See https://github.com/mozilla/addons-frontend/issues/4507

### What happened?

The error points to the minified source

### What did you expect to happen?

Source maps should point to the actual source

### Anything else we should know?

I tried in both Firefox and Chrome to be sure.

**Comment by willdurand** [comment]
I think this is fixed now because I can use source maps. I will open a PR to use `cheap-module-eval-source-map` though, because it is faster and the recommended sourcemap config for webpack 2+.
