### ISSUE TITLE
Extract AutoSearchInput component

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4510]
We have an input field that autosuggests search results when you type in it. I need to use this for putting add-ons in a collection (https://github.com/mozilla/addons-frontend/issues/4004) so I will extract it into a shared component.

For QA: Please test for regressions in all features related to the search bar in the header.

**Comment by ioanarusiczki** [comment]
I tested the search feature using the test cases from[ here](https://testrail.stage.mozaws.net/index.php?/suites/view/97&group_by=cases:section_id&group_order=asc) with FF58 (Win10 and Android 8.0) 
It seems to be alright so I mark it as verified fixed.

**Comment by kumar303** [comment]
@ioanarusiczki the issue had not been closed yet. I just landed the patch -- can you verify it again when the patch lands on dev? It could take up to 15 minutes to land but you can check the commit at https://addons-dev.allizom.org/__frontend_version__

**Comment by ioanarusiczki** [comment]
Ups! The issue was verified today by @vcarciu on AMO stage with FF59 (Win10).  I re-checked for android 8.0.
The test results are[ here](https://testrail.stage.mozaws.net/index.php?/runs/view/8825&group_by=cases:section_id&group_order=asc)
