### ISSUE TITLE
Google calendar Plugin

### ISSUE THREAD

**Issue by Pilarbrist** [mozilla/addons-frontend#4512]
In order to access gotomeeting.com my mac need google calendar plugin, when I click the link to install the plugin, it redirect to Github.

**Comment by jvillalobos** [comment]
Is the install button on addons.mozilla.org? Can you please include the address of the page where this happened?

**Comment by caitmuenster** [comment]
Thanks @Pilarbrist! 

I went to the gotomeeting site, which noted that they currently only support the Google calendar extensions in Chrome. I emailed them with instructions for porting their Chrome extension to Firefox.  Hopefully they will have a Firefox version available soon.
