### ISSUE TITLE
Pagination on Search results and Collection screens is broken

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4513]
PR #4509 broke pagination, yielding unusual results. For example, if you go to https://addons-dev.allizom.org/en-US/firefox/search/?q=test and click the `Next` button, it takes you to page 2, but if you click `Next` again from there it takes you to page 21, and `Next` is disabled.

I will try to fix this ASAP.

**Comment by tofumatt** [comment]
Oh no! I only tested page 1 to page 2 and back 😱

Would be good to add a test for this if possible... thanks for catching it!

Once you need a review just ping me... I should be around the next three hours if it's ready tonight.

**Comment by bobsilverberg** [comment]
For the record, it wasn't #4509 that broke pagination, it was #4503.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO dev and stage with FF58 Win10x64 and Android 7.0

![next page](https://user-images.githubusercontent.com/31961530/37081208-5ff3015e-21f1-11e8-9bc4-993c3f0223d5.gif)
