### ISSUE TITLE
15 March homepage content programing update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4515]
For the Thursday, 15 March push, please update the AMO homepage programming in accord with what's [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#heading=h.2dl5oxy3ewcc).

@muffinresearch @diox @EnTeQuAk

**Comment by bobsilverberg** [comment]
I'm happy to take this one.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Hello! I checked the updates as mentioned [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#heading=h.2dl5oxy3ewcc)
The Smarter Shopping collection returns a Page not found message when clicked, could you please check if that is alright so I can mark this verified? 
Thanks!

**Comment by bobsilverberg** [comment]
The smarter-shopping collection disappeared, which is odd because I assume it was there the last time an update was tested. Does anyone know why some collections keep disappearing?

I recreated it so you should be able to verify it now.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Maybe developers or testers delete these collections for testing purposes as well?
I remember having the same problem with 3 collections from this section for a previous update and you recreated those collections too. 
This is verified fixed on AMO dev with FF58 (Win10 and Android 8.0)
