### ISSUE TITLE
Pagination is broken when using some specific symbols

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4516]
STR:

1, Go to AMO homepage and perform a search
2. Change your page number to "%" - i.e. https://addons.allizom.org/en-US/firefox/search/?page=%&platform=windows
3. Observe the results

Actual result:
An Internal Server Error is returned

Expected result:
A Page Not Found error is returned

Notes:
- another example is "page=#" which will return a 'No add-ons Found' result- i.e. https://addons.allizom.org/en-US/firefox/search/?page=#&platform=windows&type=persona
- the behavior is the same when the symbols are combined with other characters
- reproduced on all AMO servers with FF58, Win10x64 and Android 7.0

[1] - "page=%"

![image](https://user-images.githubusercontent.com/31961530/37086188-a19f4a28-21ff-11e8-94bd-acfa047014eb.png)

[2] "page=#"

![image](https://user-images.githubusercontent.com/31961530/37086241-bf99c4c2-21ff-11e8-8341-6d107f267130.png)

**Comment by tofumatt** [comment]
This is specific to the `%` character, which is a special URI character and is causing `decodeQuery` to throw. This actually happens on production too but this is a malformed URI.

Assuming we can catch this before React does we should fix it but it's low-priority; this only happens if a user specifically enters a malformed URI.

**Comment by willdurand** [comment]
> Expected result:
> A Page Not Found error is returned

Looks like this has been fixed:

![Screen Shot 2019-04-18 at 17 13 11](https://user-images.githubusercontent.com/217628/56371359-42644b00-61fd-11e9-9869-10d9dca47a7a.png)

**Comment by AlexandraMoga** [comment]
The below pages are throwing a 404, as expected:

https://addons.mozilla.org/en-US/firefox/search/?platform=windows&page=%
https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/reviews/?page=%
