### ISSUE TITLE
Review date changes briefly at page refresh

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4517]
STR:

1. Log into AMO and pick an add-on to view its details page
2. Write a review for the selected add-on
3. Go to add-on reviews page and look at the date assigned to your review
4. Refresh the page several times

Actual result:
At page refresh, the review date changes for a brief moment

Expected result:
The review date stays the same when page is refreshed

Notes:
- I was not able to reproduce for reviews  ≥ an hour old
- reproduced on all AMO servers with FF58, Win10x64

![review date](https://user-images.githubusercontent.com/31961530/37103419-d967fe40-2232-11e8-9e71-f127c36154af.gif)

**Comment by tofumatt** [comment]
Is this *always* happening or is it intermittent? I would guess that the page is re-rendering client-side on load and the time simply changed enough that the review went from being 42 to 43 minutes old. 😄

**Comment by AlexandraMoga** [comment]
I can't reproduce this anymore, so I'm guessing it was just an intermittent issue.
Closing based on latest results.
