### ISSUE TITLE
Update Addon-header-info-card to match Sketch specs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4520]
The Sketch specs for the Addon-header-info-card differ from what we currently have in a number of ways. The layout and formatting of the text is different (which was also reported in issue #4431), and the badges are in a different location.

Sketch has the card looking like:

<img width="427" alt="screenshot 2018-03-07 12 46 58" src="https://user-images.githubusercontent.com/142755/37108638-a9ee3314-2205-11e8-8c30-d7282788fc1c.png">

Whereas the current site looks like:

<img width="853" alt="screenshot 2018-03-07 12 47 45" src="https://user-images.githubusercontent.com/142755/37108657-c1373b10-2205-11e8-9cf1-3d252e2fe660.png">

Duplicates #4431

**Comment by bobsilverberg** [comment]
As I mentioned at https://github.com/mozilla/addons-frontend/pull/4551#issuecomment-373007201, I don't think PR #4551 addresses the text layout and sizing issues discussed in this issue, so I don't think this should be closed. I'm going to reopen it. Perhaps that's not correct and a new issue needs to be opened for the leftover requirements. If that's the case please let me know.

**Comment by tofumatt** [comment]
Shoot, right on. My bad.

**Comment by tsl143** [comment]
@bobsilverberg , can you help me with sketch files (url)?

**Comment by bobsilverberg** [comment]
@tsl143 The Sketch file is available in the repo at https://github.com/mozilla/addons-frontend/blob/master/assets/sketch%20files/AMO%20Desktop%20-%20Master.sketch, but you need Sketch to view it, which is a commercial application. I did post a screen shot from Sketch in this issue, and the requirements were discussed at https://github.com/mozilla/addons-frontend/issues/4431#issuecomment-369987147. Hopefully that's enough to get started on it.

**Comment by tofumatt** [comment]
We chatted about this on IRC and I think the layout has changed enough to call this closed. The rest of the layout and sizing issues are site-wide and can be addressed in a separate issue.

**Comment by vcarciu** [comment]
Thanks @tofumatt 
I will mark this as verified since the other issues found were logged as separate bugs.
