### ISSUE TITLE
SHAPass cannot be found

### ISSUE THREAD

**Issue by jpcrevoisier** [mozilla/addons-frontend#4522]
### Describe the problem and steps to reproduce it:

I have published my extension ( SHAPass ) on addon.mozilla.org
### What happened?
Unable to found it
### What did you expect to happen?
To found and download my extension

**Comment by muffinresearch** [comment]
Seems to be here just fine: https://addons.mozilla.org/en-US/firefox/addon/shapass/

**Comment by jpcrevoisier** [comment]
Yes sorry, i was à little bit toi quick ..

Le jeu. 8 mars 2018 à 17:48, Stuart Colville <notifications@github.com> a
écrit :

**Comment by tofumatt** [comment]
It takes a few minutes for add-ons to appear publicly after they are scanned/approved/etc. Sorry about the delay! 😄

**Comment by jpcrevoisier** [comment]
No, no it's clearly m'y fault. You can close the ticket of course.

Sorry again.
