### ISSUE TITLE
Remove large video files from git

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#453]
See https://git-lfs.github.com/ for more info.

I see this in the git CLI:

```
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File src/disco/video/AddOns.mp4 is 61.15 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
```

**Comment by muffinresearch** [comment]
Sounds like if we go this route we'd need to run git-lfs to retrieve the files prior to a deploy.

The alternative is to put the videos straight up on the CDN and remove them from the tree.

**Comment by muffinresearch** [comment]
@jasonthomas do you have a preference?

**Comment by jasonthomas** [comment]
I think we should keep it in version control. Are there going to be more files like this? Github's recommendation is to use LFS if there are a lot of large files and files greater than 100MB. If it is just a few files and less than 100MB I don't think it should be a issue.

**Comment by muffinresearch** [comment]
@jasonthomas it seems to noticeably impact the repo performance.

**Comment by jasonthomas** [comment]
If that's the case then I am okay with using LFS.

**Comment by muffinresearch** [comment]
Hmm so I just tried lfs locally and I hate it already. Seems we'd also have issues with shaving a bunch of yaks to get travis to install it since it requires auth. 

Thinking we'll try and live with the files in the repo for now.
