### ISSUE TITLE
Add functional UI tests

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4530]
@kumar303 was suggesting a suite of UI tests, similar to what is found on addons-server, but run within this repo. 

I think this is a good idea and should be pretty straightforward as the config within addons-server is all set.

**Comment by jrbenny35** [comment]
I think these could run on circleci as we know that works and how to set it up best.

**Comment by jrbenny35** [comment]
Would it be wanted to run these locally?

**Comment by kumar303** [comment]
We discussed this over Vidyo. Here are some notes:

* We need functional tests for the `addons.mozilla.org` website, period. Thinking about it in terms of frontend/backend here is not relevant.
* We'd like for code changes in both `addons-server` and `addons-frontend` to trigger the tests
* We'd like pull requests to trigger the tests so we can detect breakage before hitting master
* The integration for both `addons-server` and `addons-frontend` should share as much configuration as possible
* We don't want to slow down pull request build times (I want a pony too ✨ )
* Other than adding yet another pull request builder perhaps there are viable alternatives
  * a separate repo to contain test files
  * something that runs in the background for each PR and just notifies devs of failures (like, by automatically opening an issue or something)
  * tests that are only run once a day
* Devs should be able to run the tests locally so they can help troublehsoot and fix breakage

**Comment by jrbenny35** [comment]
I am thinking maybe we could have a few different ways to run the tests. One that would setup everything from scratch, and maybe a set of instructions on running the tests with addons-server already cloned and the docker container already set up. Thoughts @kumar303 @krupa?

**Comment by kumar303** [comment]
Sure. We have to start somewhere so I say try something out with the goals from https://github.com/mozilla/addons-frontend/issues/4530#issuecomment-373156492 in mind.

**Comment by jrbenny35** [comment]
This is an attempt: https://circleci.com/gh/jrbenny35/addons-frontend/10

About 17min run time, which is...not short.
