### ISSUE TITLE
Screenshots display a visual issue when opening them for the first time

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4540]
STR:
1. Load AMO dev and submit a static theme
2. Click on View Listing from Edit information to check the preview of the the theme saved as a screenshot
3. Click the screenshot displayed on the new frontend
4. Observe the screen

Expected result:
Screenshot is opened on a black background.

Actual result:
A grey background appears for a short time and then the black background.

Notes:
The issue is not reproducible when screenshot is opened again the second time but it is reproducible every time you navigate away from the theme's detail page and then returning to it.
This issue is reproducible on AMO dev with FF58 (Win10).

![grey visual issue](https://user-images.githubusercontent.com/33448286/37333496-275fce9c-26b2-11e8-92bd-ab9adc3130e5.gif)

**Comment by ioanarusiczki** [comment]
This issue is also reproducible on AMO dev and AMO stage with FF59 (Win10) for all types of extensions with uploaded screenshots.

**Comment by tofumatt** [comment]
This is probably a bug with the screenshot viewer itself and not us, as it's pretty shaky.
