### ISSUE TITLE
Impossible to load an add-on detail page when its slug begins with a dash followed by only numbers

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#4541]
### Describe the problem and steps to reproduce it:
1. Submit an add-on with a slug being a dash (`-`) followed by numbers only.
2. Wait for it to be approved, visit its listing page

### What happened?
On the new frontend, the detail page only shows placeholder content.
![37206690-6cd2b0e2-23a2-11e8-85ba-61dd1bc2bb60](https://user-images.githubusercontent.com/187006/37341654-705f82c6-26c2-11e8-8d67-032f1ffeb2cb.png)

### What did you expect to happen?
It should be loaded without any issues. The legacy site works fine in this case.

### Anything else we should know?
Changing the slug to a dash followed by some letters works fine.

There are a few hundred add-ons (probably exclusively themes that were imported with a blank name a long time ago, see mozilla/addons-server#7599) on prod that are affected.

**Comment by tofumatt** [comment]
I wonder if some weird typecasting or something else is happening here. Maybe there's some weirdness with how JS deals with object keys that start with `-` and end with digits? But looking at the console output of this add-on, the state is definitely updated and the data is correct. We are fetching the data and storing it in state properly, it could just be whatever check we use to make sure we aren't still loading is messing up.

💡 is that I think we check for numbers as slugs before we load the slug as a string for compatibility reasons. I'm guessing checking `-40913` as a number gets the front-end thinking we should treat it as an ID.

**Comment by muffinresearch** [comment]
@rebmullin depending on how you're doing with other issues, if you have some time at some point do you think you could take a look at this one?

**Comment by rebmullin** [comment]
@muffinresearch  - sure thing

**Comment by ioanarusiczki** [comment]
This is verified fixed on AMO dev with FF59 (Win10).
Also checked to see if the list of themes sorted by Name from https://github.com/mozilla/addons-server/issues/7599 can be viewed https://addons-dev.allizom.org/en-US/firefox/search/?page=1&platform=windows&sort=name
