### ISSUE TITLE
[Android] Badges are not correctly aligned on Android devices

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4542]
Steps to reproduce:
1.On Android device, open your Firefox and go to AMO-dev
2.Open any extension with some badges (ie. https://addons-dev.allizom.org/en-US/android/salmoish-alpar-alpantelew/ - experiemental and payments badges)

Expected results:
Badges are aligned to the left (for consistency with desktop view)

Actual results:
Badges are aligned to the right

NOTES: 
Logged based on #2080 latest comments. 

Please see a photo with this issue: 

![payment](https://user-images.githubusercontent.com/1583842/37342820-64a36c02-26ce-11e8-9acc-ea4254923702.png)

**Comment by bobsilverberg** [comment]
As I mentioned in issue #2080, I'm not sure this is a bug at all. We have issue #4520 open which will update desktop to have the icons right-aligned too, so when that's complete this will be consistent with desktop. If we fix this now (to make them left-aligned), we'll have to fix it again when #4520 lands. @pwalm can you comment on whether what we see above on mobile is a bug, or actually the way we want it to appear?

**Comment by tofumatt** [comment]
This appears to have been fixed, I believe in #4551.

**Comment by AlexandraMoga** [comment]
This is solved for portrait orientation:

![image](https://user-images.githubusercontent.com/31961530/38236346-8c7c513a-372c-11e8-93fd-f9d5d3ad47c4.png)


@tofumatt in landscape mode, the badges are still aligned to the right (not the top right, as they are on desktop). Shouldn't we see them on the left as well?

![image](https://user-images.githubusercontent.com/31961530/38236302-6a0da824-372c-11e8-92c1-cbaa10c78c5f.png)

**Comment by tofumatt** [comment]
I think they should be above, floated to the right of the icon and add-on name.

That or left-aligned, but that look is weird, agreed. Could you file a new issue for that?

**Comment by AlexandraMoga** [comment]
Thanks! I've filed #4712 for the last issue.

This issue can be marked as verified fixed on AMO-dev with FF59, Android 7.0
