### ISSUE TITLE
The icon for the "Store unlimited amount of client-side data" permission has display issues

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4543]
STR:
1. Load AMO dev and upload an add-on that contains the Store unlimited amount of client-side data permission. My saples are here https://addons-dev.allizom.org/en-US/firefox/addon/all-of-the-permissions2/
and here https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus-testing-for/
2. Go to the add-ons detail page to Permissions section and observe the icon. 

Expected result:
Icon is displayed as in[ here](https://user-images.githubusercontent.com/6797635/36286688-a3962652-1265-11e8-8502-cbcde2aa3d15.png)

Actual result:
The icon looks different than the one from specs.

Notes:
This issue is reproducible on AMO dev with FF58 (Win 10).

The one displayed 
![icon](https://user-images.githubusercontent.com/33448286/37347541-be1404b6-26da-11e8-9372-1fdfc491d0c8.png)

Icon should look like
![icon2](https://user-images.githubusercontent.com/33448286/37347256-15148f34-26da-11e8-9a31-b8fd5fb7fd2a.png)

**Comment by bobsilverberg** [comment]
This is what I see at https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus-testing-for/:

<img width="483" alt="screenshot 2018-03-14 12 55 37" src="https://user-images.githubusercontent.com/142755/37417600-10c5f726-2787-11e8-9644-77a694e89977.png">

which looks fine to me. That's with Nightly, but I also tried with Beta and see the same, proper icon. I'm not sure why it's rendering strangely for you. Could someone else try to reproduce this?

**Comment by bobsilverberg** [comment]
Hmm, when I look at your screenshot, @ioanarusiczki, all of the icons look "worse". Does this have to do with your screen resolution? It doesn't look like it's a problem with just the storage icon in any case.

**Comment by kumar303** [comment]
I don't see the pixelation on Windows 10

**Comment by bobsilverberg** [comment]
@pwalm Do you have any idea what might be causing the problem @ioanarusiczki reports above? None of us seem to be able to recreate it, but maybe you've seen something similar?

**Comment by pwalm** [comment]
I don't see it either:
<img width="322" alt="screen shot 2018-03-14 at 10 45 36 am" src="https://user-images.githubusercontent.com/6797635/37420789-df3dd514-2774-11e8-900e-b05cfb7d3a33.png">

There is an error in the top half of that SVG, but I'm not sure what could be causing it in a one-off case like this...

**Comment by bobsilverberg** [comment]
I guess, if there's an error in the SVG, it's worth exporting it from Sketch again. I'll do that and submit it and we can see if that makes any difference.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I checked this again and yes, it does look worse on my side because I'm on desktop using Win10. Did not change any of the resolution settings, left them as recommended. I tried reducing the browser's size but it does not change the issue.  I tested withFF59 and FF61 but I have the same results on both versions. 
This is not reproducible on small devices, I checked on a laptop with Mac OS X 10.13.2 and on a Pixel phone with Android 8.0 and the icons look alright there. - with FF59

Desktop screen
![win10 resolution settings](https://user-images.githubusercontent.com/33448286/37455472-d553e454-2845-11e8-9278-4488df272489.png)

Android view
![icons on android](https://user-images.githubusercontent.com/33448286/37455569-0f16966e-2846-11e8-9012-7f28d9cbf463.png)

**Comment by bobsilverberg** [comment]
@ioanarusiczki I created and deployed a new icon. Let's see if that's any better.

**Comment by ioanarusiczki** [comment]
I checked it and now it looks alright. Verified fixed on AMO dev with FF59(Win10). 

![icons look good](https://user-images.githubusercontent.com/33448286/37521250-baf8997c-2928-11e8-9116-37c20e4a4c45.png)

**Comment by bobsilverberg** [comment]
Great, thanks @ioanarusiczki!
