### ISSUE TITLE
Update circleci to version 2

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4544]
We should update circleci to version 2 as the new config is a bit cleaner and allows for faster builds. It will also help with the new frontend tests I will be adding.

**Comment by kumar303** [comment]
It looks like this accidentally broke stage deploys. See https://github.com/mozilla/addons-frontend/issues/4604

**Comment by muffinresearch** [comment]
It is version 2 now: https://github.com/mozilla/addons-frontend/blob/935bb70af9f1bd9a7f871133b38f9b025e567f2e/.circleci/config.yml#L6
