### ISSUE TITLE
Create a URL/path helper aware of clientApp/lang/etc.

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4545]
As mentioned in https://github.com/mozilla/addons-frontend/pull/4536#discussion_r173959506 and #2053, it would be nice to have a utility function that created a URL with the right clientApp/lang set. Presumably it would look like:

```js
createURL(state, '/addon/500/')
// '/en-US/firefox/addon/500/'
```

**Comment by kumar303** [comment]
This might be part of a [universal link component](https://github.com/mozilla/addons-frontend/issues/2053) but it should be usable outside of `<Link/>`.
