### ISSUE TITLE
Change "Download Firefox" message bar from red to grey

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#4547]
This red is scary and could be (probably is) negatively affecting Firefox download numbers:
<img width="691" alt="screen shot 2018-03-13 at 8 45 23 am" src="https://user-images.githubusercontent.com/6797635/37352667-0605be58-269b-11e8-9e29-fe676fd6b4af.png">

We need to change it to the ["generic" style](https://design.firefox.com/photon/components/message-bars.html#color).

**Comment by tofumatt** [comment]
Downgrading this to at least a p2 because it's not breaking the site and we don't actually have numbers on it yet 😉

Should be an easy fix though. We could probably get it in this week's tag if it's urgent.

**Comment by ioanarusiczki** [comment]
I verified this issue with Chrome on Windows and Android platforms and Safari for iOS.
The messages are displayed grey in add-on detail page.
Win10
![chrome 1](https://user-images.githubusercontent.com/33448286/37398346-eb9a0eb0-2786-11e8-87f0-dae053185c59.png)
Android 8.0
![android chrome](https://user-images.githubusercontent.com/33448286/37398366-f3cfd1be-2786-11e8-9c40-b4aa542fbb77.png)
iOS 11.2.6
![safari](https://user-images.githubusercontent.com/33448286/37398372-f98a7a5a-2786-11e8-9fbd-0c34e7bb0879.PNG)
