### ISSUE TITLE
Allow fetchAddonsByAuthors to omit the exclude_addons param

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4556]
To implement #4280 and similar issues, we need to be able to fetch add-ons by a user.

Turns out we essentially have this functionality in `fetchAddonsByAuthors` but it requires a `slug` to send to the API as an `exclude_addons` param. But if we make that `slug` optional we can re-use this reducer for "add-ons by this user" on the profile page.

**Comment by vcarciu** [comment]
@tofumatt  : Can you please add some STRs to this issue or mark it as "qa: not needed" ?
