### ISSUE TITLE
editing developer response is incomplete

### ISSUE THREAD

**Issue by cadeyrn** [mozilla/addons-frontend#4558]
The feature to edit an developer response to a review is incomplete on the new frontend. You can edit the main content but you can't edit the headline of the response.

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file a bug. Can you send me a link to the review page of where you saw a headline in a developer reply? I thought we did not display them.

**Comment by cadeyrn** [comment]
Unfortunately I don't know how I get a permalink in the new design but there are a few reviews with developer responses. Some of these responses has a headline:

https://addons.mozilla.org/en-US/firefox/addon/bookmarks-organizer/reviews/?page=4

**Comment by kumar303** [comment]
ok, thanks. We should hide these headlines because they are no longer used on the new site:

<img width="731" alt="screenshot 2018-03-14 09 53 52" src="https://user-images.githubusercontent.com/55398/37410022-ae000e60-276d-11e8-8c82-a618b2db61af.png">

**Comment by cadeyrn** [comment]
Please note that if someone writes a review the developer of the add-on receives an email with a link to the review. If you click this link the *old* site will be opened in the browser and it also contains the headline field in the form for the developer response. So if the plan is to remove the headline from the new frontend you should also remove the input field from the old form _or_ you shouldn't send the developers to the old page.

**Comment by muffinresearch** [comment]
Titles were removed in https://github.com/mozilla/addons-server/issues/8144
