### ISSUE TITLE
Expose AutoSearchInput label and make it more embeddable

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4562]
The AutoSearchInput component added in https://github.com/mozilla/addons-frontend/issues/4510 needs some tweaks for https://github.com/mozilla/addons-frontend/issues/4004

* It has a hidden form label. This should be visible by default and configurable.
* It requires a `position: relative` container. This should be fully extracted from `SearchForm`. This will allow it to be embeddable in other components.

**For QA**: Please check for style regressions in the search box at the top of the page

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF59 (Win10 and Android 8.0). No style regressions observed.
