### ISSUE TITLE
Error loading Themes page in old view 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4566]
STR:
1. Load AMO stage and click on Themes.
2. Switch to classic view.
3. Observe screen.

Expected result:
Legacy page is loaded.

Actual result:
Oops! We had an error. message is displayed.

Notes:
This issue is reproducible on AMO stage with FF59 (Win10). 

![legagy page - themes](https://user-images.githubusercontent.com/33448286/37470810-0060afe4-2871-11e8-9d8f-2d92e70ee09b.gif)

**Comment by tofumatt** [comment]
If the issue is only happening on the legacy site it's not a frontend code issue so this should be re-filed on addons-server.

**Comment by ioanarusiczki** [comment]
@tofumatt Done! https://github.com/mozilla/addons-server/issues/7819
