### ISSUE TITLE
Use new collection add-on modifier on add-on detail page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4574]
We have a new API helper to create/update collection add-ons (https://github.com/mozilla/addons-frontend/issues/4567). The `Addon` component should use this for the dropdown that lets you add an add-on to a collection.

**QA**, please check regressions around this feature:
* Sign in
* Create a collection
* Go to any add-on detail page
* Add the add-on to a collection using the dropdown menu:

<img width="353" alt="screenshot 2018-03-16 11 57 30" src="https://user-images.githubusercontent.com/55398/37533898-3f17d1e0-2911-11e8-96a0-b850ecdbad76.png">

**Comment by ioanarusiczki** [comment]
I made some tests on AMO dev with FF59 (Win10) - no regressions found. I'm marking this as verified fixed.
