### ISSUE TITLE
Create a saga to create/update collection add-ons

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4576]
In https://github.com/mozilla/addons-frontend/issues/4004 we need a screen that lets the user edit the add-ons in a collection.

We currently have a saga that lets us *create* collection add-ons. We need a new saga that lets us both create and update.

**QA**, please check regressions around this feature:
* Sign in
* Create a collection
* Go to any add-on detail page
* Add the add-on to a collection using the dropdown menu:

<img width="353" alt="screenshot 2018-03-16 11 57 30" src="https://user-images.githubusercontent.com/55398/37533898-3f17d1e0-2911-11e8-96a0-b850ecdbad76.png">

**Comment by kumar303** [comment]
See https://github.com/mozilla/addons-frontend/pull/4534 for an example of how to create a single modifier saga for two create and update actions.

**Comment by bobsilverberg** [comment]
This was done some time ago.
