### ISSUE TITLE
Edit comments about an add-on in a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4578]
Tracker: https://github.com/mozilla/addons-frontend/issues/2782

A user should be able to:

- Sign in
- View an existing collection that they created
- Edit the collection (which opens the overlay)
- Add/edit comments about an add-on in the collection

**Comment by bobsilverberg** [comment]
@pwalm I'm wondering about the UX for this. I have attached the current mockup from Sketch, but it is a bit out of date as it still shows the overlay. The mockup looks like this:

![collections - edit collection with notes - 1366px](https://user-images.githubusercontent.com/142755/40670697-e5e0e4de-6337-11e8-8f46-b55036090a8b.png)

And the current edit page looks like this:

<img width="1218" alt="screenshot 2018-05-29 12 09 20" src="https://user-images.githubusercontent.com/142755/40671164-23c414c8-6339-11e8-9b42-73a57f7e9e3b.png">

I can pretty much infer what to do with the new screen based on the mockup, but I'm unsure about the workflow. 

I assume that a textarea should appear when a user clicks on the "notes" icon for an addon, but how do they save notes? Should there be a save button somewhere to go with the textarea? Should we automatically show a text area for any add-ons that already have notes? In not, in what other way can we indicate to a user that the add-on has notes?

Maybe we can discuss this in this week's Front End review meeting?

**Comment by pwalm** [comment]
Yeah, let's talk about it in the meeting.

**Comment by pwalm** [comment]
Ok, here we go (forgive my artistry):
Create comment mode:
![add-ons - 2018-05-29 18 59 59](https://user-images.githubusercontent.com/6797635/40738645-f0e37a6a-63f8-11e8-9d43-eeb2fda0a76e.jpg)

Commented state (once it has been saved):
![add-ons - 2018-05-29 18 59 59 2](https://user-images.githubusercontent.com/6797635/40738669-06254ab6-63f9-11e8-9501-8863e2437622.jpg)

Edit mode (returning to edit an existing comment):
![add-ons - 2018-05-29 18 59 59 3](https://user-images.githubusercontent.com/6797635/40738681-12449202-63f9-11e8-9044-040c798a0b7d.jpg)

Clicking "Delete" just deletes the comment, no confirmation needed.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60 (Win10 and Android 8.0).
I filed a separate issue https://github.com/mozilla/addons-frontend/issues/5315
