### ISSUE TITLE
Add styles to view add-ons within the collection editor

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4579]
As an initial step towards adding add-ons (https://github.com/mozilla/addons-frontend/issues/4590), deleting add-ons (https://github.com/mozilla/addons-frontend/issues/4577), and editing comments (https://github.com/mozilla/addons-frontend/issues/4578), we need to see the add-ons in a collection.

This will just implement styles for collection add-ons, without any functionality.

Here are some notes about what this issue does and does not cover:
* All collection add-ons should be visible and look like the mock
* Some add-on related buttons from the mock **will be missing**
* Clicking on collection add-ons should **do nothing**
* It will be possible to type a name of an add-on and see results
* Selecting a name from the result list **will do nothing**

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59 Win10x64 and Android 7.0

Working:
- the edit collection form will display the add-ons that are part of the collection
- add-ons will include icons and names
- a search field that allows searching for add-ons is present
- search results are will show add-ons according to the searched term used (similar to AMO search)

For the rest of the issues found during testing, separate bugs were filed: #4612, #4614, #4616, #4617
