### ISSUE TITLE
Some permission icons have jagged edges or are blurry and show differently on Firefox vs Edge

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#4581]
### Describe the problem and steps to reproduce it:
Visit https://addons-dev.allizom.org/en-US/firefox/addon/all-of-the-permissions2/ in vanilla Firefox Nightly and in Edge.

### What happened?
[Click for uncompressed screenshot](https://i.cubeupload.com/JnScPM.png) Edit: [alternative link](https://i.lensdump.com/i/8ToROT.png)
Most icons, especially those for 'clear recent history,' 'read the text,' 'access browsing history,' have jagged edges on Firefox but look fine on Edge.
Some other icons e.g. those for 'clipboard,' 'download,' 'access tabs,' 'store data' etc. are blurry on Edge.

### Anything else we should know?
The svg code for the (i) icon in use is:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24"> <defs> <path id="info-a" d="M12,1.5 C17.7989899,1.5 22.5,6.20101013 22.5,12 C22.5,17.7989899 17.7989899,22.5 12,22.5 C6.20101013,22.5 1.5,17.7989899 1.5,12 C1.5,6.20101013 6.20101013,1.5 12,1.5 Z M12,6 C12.8284271,6 13.5,6.67157288 13.5,7.5 C13.5,8.32842712 12.8284271,9 12,9 C11.1715729,9 10.5,8.32842712 10.5,7.5 C10.5,6.67157288 11.1715729,6 12,6 Z M12,10.5 C12.8284271,10.5 13.5,11.1715729 13.5,12 L13.5,16.5 C13.5,17.3284271 12.8284271,18 12,18 C11.1715729,18 10.5,17.3284271 10.5,16.5 L10.5,12 C10.5,11.1715729 11.1715729,10.5 12,10.5 Z"/> </defs> <g fill="none" fill-rule="evenodd"> <rect/> <mask id="info-b" fill="#fff"> <use xlink:href="#info-a"/> </mask> <use fill="#000" xlink:href="#info-a"/> <g fill="#0C0C0D" fill-opacity=".8" mask="url(#info-b)"> <rect width="24" height="24"/> </g> </g> </svg>`

If I take that very same path and reuse it as:
`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
	<path fill="#0F1126" fill-rule="evenodd" d="M12,1.5 C17.7989899,1.5 22.5,6.20101013 22.5,12 C22.5,17.7989899 17.7989899,22.5 12,22.5 C6.20101013,22.5 1.5,17.7989899 1.5,12 C1.5,6.20101013 6.20101013,1.5 12,1.5 Z M12,6 C12.8284271,6 13.5,6.67157288 13.5,7.5 C13.5,8.32842712 12.8284271,9 12,9 C11.1715729,9 10.5,8.32842712 10.5,7.5 C10.5,6.67157288 11.1715729,6 12,6 Z M12,10.5 C12.8284271,10.5 13.5,11.1715729 13.5,12 L13.5,16.5 C13.5,17.3284271 12.8284271,18 12,18 C11.1715729,18 10.5,17.3284271 10.5,16.5 L10.5,12 C10.5,11.1715729 11.1715729,10.5 12,10.5 Z"/>
</svg>`

it looks much smoother in Firefox: [uncompressed screenshot](https://i.cubeupload.com/jwRiVO.png). I don't know why though. Edit: [alternative link](https://i.lensdump.com/i/8To1Tz.png).

PS: there are easy savings through SVGO e.g. above becomes simpler:
`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24">
  <path fill="#0F1126" fill-rule="evenodd" d="M12 1.5c5.799 0 10.5 4.701 10.5 10.5S17.799 22.5 12 22.5 1.5 17.799 1.5 12 6.201 1.5 12 1.5zM12 6a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3zm0 4.5a1.5 1.5 0 0 1 1.5 1.5v4.5a1.5 1.5 0 0 1-3 0V12a1.5 1.5 0 0 1 1.5-1.5z"/>
</svg>`

Edit: added alternative links to screenshots as cubeupload appears to be down.

**Comment by FatOrangutan** [comment]
Another issue:

STR: Whether in Firefox or in Edge, resize the browser window (at least horizontally) such that some permissions now run over two lines.

AR:

Edge:
![edge](https://user-images.githubusercontent.com/8336638/37559242-68be18a0-2a48-11e8-853d-79f510c09581.PNG)
Firefox: (icon should be 24x24 but is deformed)
![20 9px](https://user-images.githubusercontent.com/8336638/37559285-4b562126-2a49-11e8-9791-212fc95cbbb2.PNG)

**Comment by muffinresearch** [comment]
@FatOrangutan please file another issue if you have an additional separate bug to report on the same feature.

**Comment by muffinresearch** [comment]
@bobsilverberg this appears to be the same thing as https://github.com/mozilla/addons-frontend/issues/4543 I suspect the mask is the issue again.

**Comment by bobsilverberg** [comment]
I "fixed" this in issue #4543 for the storage icon by replacing the one in the repo with a new one I exported from Sketch. I suppose we could do the same with all of the other icons which may address this issue. @pwalm do you have any suggestions/opinions on what's discussed above about the svg files?

**Comment by bobsilverberg** [comment]
@pwalm I know I already pinged you on this, but based on the comment above it seems there is an issue with the svg's and one that apparently cannot be fixed by simply re-exporting them from Sketch. Is this something you can look into and possibly fix?

**Comment by pwalm** [comment]
Straight from the library file. Hope this one works!
[Storage - 32.svg.zip](https://github.com/mozilla/addons-frontend/files/1895527/Storage.-.32.svg.zip)

**Comment by bobsilverberg** [comment]
@FatOrangutan Do you mind trying the attached svg and letting us know if it seems to address the issue you were seeing with the previous versions.

**Comment by FatOrangutan** [comment]
This unfortunately has the same issue. If I take the path from this svg and reuse it without relying on a mask, then much like the previous two comparisons, it looks smoother: before / after: https://i.cubeupload.com/EhziuE.png.

FWIW, the 'smooth svg' is:
`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="26" viewBox="4 3 24 26"> <path fill="#0C0C0D" fill-rule="evenodd" fill-opacity=".8" d="M26,21.1 L6,21.1 C4.9,21.1 4,22 4,23.1 L4,27 C4,28.1 4.9,29 6,29 L26,29 C27.1,29 28,28.1 28,27 L28,23.1 C28,22 27.1,21.1 26,21.1 Z M24.1,27 C23,27 22.1,26.1 22.1,25 C22.1,23.9 23,23 24.1,23 C25.2,23 26.1,23.9 26.1,25 C26.1,26.1 25.2,27 24.1,27 Z M25,3 L7,3 C5.3,3 4,4.4 4,6.2 L4,19.5 C4.6,19.2 5.3,19 6,19 L26,19 C26.7,19 27.4,19.2 28,19.5 L28,6.2 C28,4.4 26.7,3 25,3 Z"/> </svg>`

**Comment by pwalm** [comment]
[Oops, didn't mean to close the issue lol]

Forgive my ignorance, but what is the issue here: Is it a rendering problem in the browser, or do these icons need to adjusted/redesigned/re-exported?

**Comment by FatOrangutan** [comment]
>Forgive my ignorance, but what is the issue here: Is it a rendering problem in the browser, or do these icons need to adjusted/redesigned/re-exported?  
  
I don't know, but a specific 'readjustment' on the svg's seems to fix the issue for me.

See [this screenshot](https://i.cubeupload.com/JnScPM.png) for the rough edges issue - especially noticeable on the i-inside-circle, lens and the clock icons in the Firefox window.

I've found that if I create an svg using the exact same path from the svg's currently in use, but avoid the `mask`, they turn out to be smooth e.g. [screenshot](https://i.cubeupload.com/jwRiVO.png). In this screenshot, the jagged svg is the one currently used on the addons.mozilla.org site, and its svg code is:
`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24" height="24" viewBox="0 0 24 24"> <defs> <path id="info-a" d="M12,1.5 C17.7989899,1.5 22.5,6.20101013 22.5,12 C22.5,17.7989899 17.7989899,22.5 12,22.5 C6.20101013,22.5 1.5,17.7989899 1.5,12 C1.5,6.20101013 6.20101013,1.5 12,1.5 Z M12,6 C12.8284271,6 13.5,6.67157288 13.5,7.5 C13.5,8.32842712 12.8284271,9 12,9 C11.1715729,9 10.5,8.32842712 10.5,7.5 C10.5,6.67157288 11.1715729,6 12,6 Z M12,10.5 C12.8284271,10.5 13.5,11.1715729 13.5,12 L13.5,16.5 C13.5,17.3284271 12.8284271,18 12,18 C11.1715729,18 10.5,17.3284271 10.5,16.5 L10.5,12 C10.5,11.1715729 11.1715729,10.5 12,10.5 Z"/> </defs> <g fill="none" fill-rule="evenodd"> <rect/> <mask id="info-b" fill="#fff"> <use xlink:href="#info-a"/> </mask> <use fill="#000" xlink:href="#info-a"/> <g fill="#0C0C0D" fill-opacity=".8" mask="url(#info-b)"> <rect width="24" height="24"/> </g> </g> </svg>`
I create the smooth svg by taking the same path description attribute but avoiding the use of a mask. So basically:
`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"> <path fill="#0F1126" fill-rule="evenodd" d="M12,1.5 C17.7989899,1.5 22.5,6.20101013 22.5,12 C22.5,17.7989899 17.7989899,22.5 12,22.5 C6.20101013,22.5 1.5,17.7989899 1.5,12 C1.5,6.20101013 6.20101013,1.5 12,1.5 Z M12,6 C12.8284271,6 13.5,6.67157288 13.5,7.5 C13.5,8.32842712 12.8284271,9 12,9 C11.1715729,9 10.5,8.32842712 10.5,7.5 C10.5,6.67157288 11.1715729,6 12,6 Z M12,10.5 C12.8284271,10.5 13.5,11.1715729 13.5,12 L13.5,16.5 C13.5,17.3284271 12.8284271,18 12,18 C11.1715729,18 10.5,17.3284271 10.5,16.5 L10.5,12 C10.5,11.1715729 11.1715729,10.5 12,10.5 Z"/> </svg>`

**Comment by FatOrangutan** [comment]
Appears to have been fixed in Nightly with [Bug 1448667](https://bugzilla.mozilla.org/show_bug.cgi?id=1448667). Closing.

**Comment by bobsilverberg** [comment]
Nice to see this has been fixed in Firefox. Thanks for updating and closing the issue, @FatOrangutan.

**Comment by ioanarusiczki** [comment]
I verified this on AMO dev with Microsoft Edge, Chrome and Firefox 59 with Win10 desktop - full screen. 
Perhaps the FF displays them with jagged edges (seems like anti aliasing is not applied) compared to the other two browsers, an example for this should be the Exchange messages with programs other than Firefox icon. On Chrome and Edge -> Access your location and Access browsing history are a little bit blurry but hardly noticeable. 
FF59
![ff](https://user-images.githubusercontent.com/33448286/39180111-bd430bea-47be-11e8-87cc-b4a34370eee7.png)
Chrome
![chrome](https://user-images.githubusercontent.com/33448286/39180132-c7cb2ac0-47be-11e8-9ee5-5813ce23a297.png)
Edge
![edge](https://user-images.githubusercontent.com/33448286/39180154-cddf1598-47be-11e8-90b6-f9cb92be4fd7.png)
