### ISSUE TITLE
add on not found via cash rewards link

### ISSUE THREAD

**Issue by lennon101** [mozilla/addons-frontend#4583]
### What happened?
Opened the following link: https://addons.mozilla.org/en-US/firefox/addon/cashrewards/ 
I was directed from: http://join.cashrewards.com.au/
Instead I was given a file not found: "Sorry, but we can't find anything at the address you entered."

### What did you expect to happen?
I expected the link to reveal the add-on

### Anything else we should know?
![image](https://user-images.githubusercontent.com/1709944/37577444-ee4b1cda-2b7d-11e8-8fd4-bb6f047336b6.png)

**Comment by tofumatt** [comment]
https://addons.mozilla.org/en-US/firefox/addon/cashrewards/ displays fine for me:

<img width="1187" alt="screenshot 2018-03-19 09 45 26" src="https://user-images.githubusercontent.com/90871/37588499-4bbbde14-2b5a-11e8-9155-23bcfc7560d3.png">
