### ISSUE TITLE
Long description is not truncated in user info card

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4584]
Steps to reproduce:
1.Log in to AMO-dev
2.Be sure that you have a long description in user profile
3.From username drop-down menu, chose view profile

Expected results:
The description is truncated and we should have a "View more" button

Actual results:
The description is not truncated and users cannot see complete description

NOTES:
Reproducible also if the homepage is a long address (edge case though)

Please see a screenshot with the issues:
![longname](https://user-images.githubusercontent.com/1583842/37589754-dac6a67a-2b6e-11e8-9e54-490f3ede9158.png)

**Comment by willdurand** [comment]
Fixed by #5079

**Comment by vcarciu** [comment]
Verified as fixed : 
![trunc](https://user-images.githubusercontent.com/1583842/40428857-ea4c2ed0-5ea9-11e8-84d7-06c3ec16746e.png)
