### ISSUE TITLE
Send abuse report should not work for self reporting 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4585]
STR:
1. Load AMO dev and log in with an account that has no admin rights.
2. From View Profile click on report this user for abuse.
3. Type some text and send it.

Expected results:
A message that user cannot report himself for abuse is displayed.

Actual results:
The abuse report is sent. 

Notes:
This issue is reproducible on AMO dev with FF59 (Win10).

![self reporting](https://user-images.githubusercontent.com/33448286/37591140-28e58e6c-2b73-11e8-9e18-b123748bb0d0.gif)

**Comment by tofumatt** [comment]
I'm happy to hide the abuse report for the existing user... but @diox: shouldn't the API not allow this? I would have expected an error from the API... but I'm happy to hide the button for the existing, non-admin user.

**Comment by diox** [comment]
I... don't see the harm of letting users self-report themselves. I guess you could hide the button if you care :)

**Comment by tofumatt** [comment]
Fair point. We'll take care of it on the frontend but it's not high priority.

**Comment by SeanPrashad** [comment]
Hey guys - I'll be happy to take this one on!

With some quick digging, I've found the chunk of code for generating the respective HTML [here](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/ReportUserAbuse/index.js#L88). I also noticed that one of the properties for this component was a `user` and that each `user` has an [array of strings representing their account permissions](https://github.com/mozilla/addons-frontend/blob/master/src/amo/reducers/users.js#L49).

I also started searching through [/reducers/users.js](https://github.com/mozilla/addons-frontend/blob/master/src/amo/reducers/users.js) but realized that we might be able to pull the current user, and subsequentally their unique ID from the `state` object right within `/components/ReportUserAbuse/index.js` (_This is what Redux is for I think_).

I'll open up a WIP PR within the next few days - stay tuned! 📺

**Comment by willdurand** [comment]
Sorry @SeanPrashad, I just grabbed it 🐱

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10).
While viewing someone else's profile the Report this user for abuse is available. 
While viewing my profile - the button is no longer displayed.
![self reporting for abuse](https://user-images.githubusercontent.com/33448286/40354864-9a78ede0-5dbd-11e8-828b-87e3059f4086.gif)
