### ISSUE TITLE
User profile page for a previous account is still displayed after you log in with another account

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4586]
Prerequisites:
- accounts must have at least one submitted ad-on for testing 

STR:
1. Load AMO dev and click on View Profile.
2. After the page is displayed click on log out from the drop down menu.
3. Click on Use a different account and log in.
4. Observe the user profile page. 

Expected result:
User profile page is displayed for the second account.

Actual result:
The previous user profile page for the first account used is still displayed.

Notes:
This issue is reproducible on AMO dev with FF59(Win10).
The correct page is displayed when clicked on View profile from the menu, refreshing page is not working.

![previous user issue](https://user-images.githubusercontent.com/33448286/37599832-56d52ba0-2b8e-11e8-9015-a5656886940d.gif)

**Comment by tofumatt** [comment]
This is the intended behaviour; after you log in you are redirected to the last page you were on, so this is the right behaviour.

**Comment by ioanarusiczki** [comment]
@tofumatt Yes, it is not a bug it's invalid. Thanks, at least I understood it now.
 I re-tested with an account that has 0 add-ons submitted logged out then logged back in with an account that has no admin rights. Page not found loads  - it is expected to work that way.
