### ISSUE TITLE
Update postcss-loader usage and config

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4592]
According to their recent [release](https://github.com/postcss/postcss-loader/compare/v2.1.1...v2.1.2) the devs seem to be patching an unsupported usage of ```options``` within the ```webpack``` config. You can see this [here](https://github.com/postcss/postcss-loader/pull/346). 

We should update our ```webpack-common.js``` to support this change. A [PR](https://github.com/mozilla/addons-frontend/pull/4591) has been submitted to pin the version to v2.1.1 until we can figure out a solution.

Lets also not forget to add the ```^``` caret back as well.

**Comment by willdurand** [comment]
We have upgraded the package many times, currently version 2.1.6 and there is no issue anymore. Actually, it looks like postcss-loader `2.1.3` reverted the BC break: https://github.com/postcss/postcss-loader/releases/tag/v2.1.3.

Closing this issue now.

**Comment by willdurand** [comment]
Upgrading to 3.0.0 seems fine as well: https://github.com/mozilla/addons-frontend/pull/5884
