### ISSUE TITLE
Docker builds on circleci should not be pushed without testing

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#4594]
It seems our docker builds get pushed to dev whether they work or not. The current circleci configuration does not test that the docker image built actually works. It simply builds, and if the build is successful, it will push to docker hub and, in turn, to dev.

We could run the new functional/integration tests after a successful build to check that the image is working correctly, or we could simply start the image and ping the server running within the container to check for an appropriate response. All of this would need to happen before a push to docker hub via a merge to master or a tag.

**Comment by willdurand** [comment]
> or we could simply start the image and ping the server running within the container to check for an appropriate response.

@jrbenny35 can we do that in a simple and fast manner?

**Comment by jrbenny35** [comment]
The best way would be to run an integration test to test the docker image. But that wouldn't be super fast. Maybe its not an issue as the docker deploys aren't that important, at least per PR.

**Comment by willdurand** [comment]
> The best way would be to run an integration test to test the docker image. But that wouldn't be super fast. Maybe its not an issue as the docker deploys aren't that important, at least per PR.

can't we just boot the image and `curl`+`grep` a specific string like `<!-- Godzilla of browsers -->`?

**Comment by jrbenny35** [comment]
We could do a _really_ simple selenium test, just checking the hero section is shown.

**Comment by willdurand** [comment]
I'd like to have a smoke test, without any dependencies if possible, and super fast. The string I mentioned earlier is always present in the HTML, so that should be enough.

**Comment by jrbenny35** [comment]
Well then that works!

**Comment by willdurand** [comment]
@jrbenny35 do you think you could work on this issue?

**Comment by jrbenny35** [comment]
I'll take it, just gotta finish up some other work.

**Comment by jrbenny35** [comment]
@willdurand so what should we do to test this? I could change the circleci config to require an integration-test before a tag build

**Comment by willdurand** [comment]
> @willdurand so what should we do to test this? I could change the circleci config to require an integration-test before a tag build

I am not sure what we want to do here but a smoke test to make sure the docker image has been built correctly would be nice.

**Comment by jrbenny35** [comment]
I think we could do the same setup as the integration-tests, as that will actually show that everything works together, but just run like 4 tests. It shouldn't take too long but idk how quickly you guys want it.

**Comment by willdurand** [comment]
> I think we could do the same setup as the integration-tests, as that will actually show that everything works together, but just run like 4 tests. It shouldn't take too long but idk how quickly you guys want it.

This works for me. Time is not an issue here because we're not running circle-ci in pull requests. it will slightly take more time to deploy a commit to -dev, but that's fine I guess.

**Comment by AlexandraMoga** [comment]
Please add a qa:not needed label to this issue.
Thank you
