### ISSUE TITLE
The text box is not triggered for ratings after request was throttled message appeared 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4595]
STR:
1. Load AMO dev and open an add-on details page.
2. Click once on the rating stars. Try to rate an add-on until the request was throttled message appears. 
3. Wait until the time mentioned in the message expires and click once on a star again.
4. Observe the screen.

Expected result:
The rating text box is opened.

Actual result:
The text box is not triggered when the star is clicked.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF59 (Win10). 

![no text box](https://user-images.githubusercontent.com/33448286/37645934-f1c4b55c-2c30-11e8-8d34-ce36482c1e99.gif)

**Comment by muffinresearch** [comment]
Closing since the new ratings flow doesn't have an overlay.
