### ISSUE TITLE
A .jpg photo with portrait orientation is not correctly displayed on User profile info card and for the add-on screenshot section

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4596]
STR:
1.  Load AMO dev and go to Edit profile page.
2. Upload a .jpg photo of any size that has less than 4 MB and has a portrait orientation. Observe it's display after photo is selected from folder.
3. Update account and click on View Profile.
5. View the image saved.

Expected results:
The image is displayed in portrait orientation.

Actual results:
The image is displayed in landscape view.

Notes:
This issue is reproducible on AMO dev with FF59 (Win10).
This issue is also reproducible when uploading images for the add-on screenshots section.
This issue is not reproducible for a .png file with portrait orientation.
 
![portrait orientation](https://user-images.githubusercontent.com/33448286/37654037-77784200-2c49-11e8-884f-aa8fa68a2be6.gif)

**Comment by willdurand** [comment]
Could be fixed by #5006

**Comment by willdurand** [comment]
Is this still reproducible on the new frontend?

**Comment by willdurand** [comment]
Hi @ioanarusiczki, is this still reproducible on the new frontend?

**Comment by ioanarusiczki** [comment]
@willdurand Hi, sorry for answering with such a delay. It is still reproducible, I will mention it in https://github.com/mozilla/addons-frontend/issues/4276

**Comment by willdurand** [comment]
@ioanarusiczki could you provide a picture that triggers this issue?

**Comment by willdurand** [comment]
@ioanarusiczki according to a discussion on IRC, it is a addons-server issue and not a frontend issue. Could you please move this issue to https://github.com/mozilla/addons-server/issues?

**Comment by ioanarusiczki** [comment]
And closing this one
 https://github.com/mozilla/addons-server/issues/8390
