### ISSUE TITLE
Add-ons developer and Theme artist options are not available on the user's info card 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4599]
As a followup for #4283 
STR:
1. Load AMO dev and click on View Profile.
2. Check if Add-ons developer and Theme Artist are present on the right upper part of the card as in [here](https://user-images.githubusercontent.com/90871/35629616-fcb243f4-0696-11e8-8b0b-024e96ec04cd.png)

Expected result:
The check boxes and the two options are present.

Actual result:
The two options are not displayed.

Notes:
This issue is reproducible on AMO dev with FF59 (Win10).

![infocard](https://user-images.githubusercontent.com/33448286/37657879-da10f9c4-2c54-11e8-9ba6-a3a40d848e51.png)

**Comment by tofumatt** [comment]
Those are not checkboxes; they're placeholder icons that would accompany each descriptor. 😄

**Comment by ioanarusiczki** [comment]
@tofumatt @my bad ! Yes, you cannot check or uncheck those! I hurried to describe them.

**Comment by tsl143** [comment]
@tofumatt , do we have any design doc for this, precisely I need following:
Icons for developer and theme artist, `font-size`, `font-weight`

**Comment by tofumatt** [comment]
@tsl143 They are in the Sketch file in the `assets/` folder, though you'll need Sketch (only available on MacOS) to view it.

**Comment by tsl143** [comment]
I dont have sketch, so I tried online viewers, I got following, but still cant get hands on any icon for both.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/5318732/38400905-21e5bc1c-3970-11e8-9f85-853e6707f5a3.png">

**Comment by tsl143** [comment]
Or there is no image, we need to put just squares?

**Comment by willdurand** [comment]
@pwalm would you have some more information/icons?

**Comment by pwalm** [comment]
Like this! (sorry about the missing icons)
<img width="1119" alt="screen shot 2018-05-29 at 10 11 13 am" src="https://user-images.githubusercontent.com/6797635/40674153-d857779c-6328-11e8-9eab-882c201dc185.png">
[icons.zip](https://github.com/mozilla/addons-frontend/files/2049673/icons.zip)

**Comment by AdityaSrivast** [comment]
I would like to work on it.This is my first time. What do I have to do?

**Comment by AdityaSrivast** [comment]
@rebmullin Can I work on it now? I am facing problem in finding out the corresponding HTML file for the code. Please help me how to find out the same. Sorry for late response. Will try to report back in 2 days.

**Comment by rebmullin** [comment]
sure thing @AdityaSrivast, that'd be great : )

Regarding finding the correct file - have you found the `UserProfile` file?  In here you will find the following snippet of code:
```javascript
 const userProfileHeader = (
   <React.Fragment>
     <UserAvatar className="UserProfile-avatar" user={user} />

     <h1 className="UserProfile-name">
       {user ? user.name : <LoadingText />}
     </h1>
   </React.Fragment>
 );
```

you will probably want to add the logic/HTML for this here and then style according to the mocks shown above

does that help?

**Comment by AdityaSrivast** [comment]
@rebmullin The code uses advanced reactjs and I am just a n00b for it at the moment. I may not be able to fix this out in the manner code is being written. But thanks a lot for your trust in me. I will surely learn quickly and contribute to the community in near future. It will be great if you can guide me for the learning, for eg., sources to be referred or any course, etc.

**Comment by tsl143** [comment]
No Problem @AdityaSrivast , I will take this up :) cheers.

**Comment by rebmullin** [comment]
Hi @AdityaSrivast, of course and no worries : ) 

Regarding learning react, I would suggest looking at the reactjs docs and going through their tutorial.  In addition, I suggest googling for additional resources/tutorials. I think there is a lot out there now and depending on your preferred style of learning you should be able to find some good docs/tutorials that suit you. Once you have some basic understanding, I would suggest diving into the code: ). I think that is the best way to learn and you can always ask questions.

Look forward to hearing from you in the near future : )

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60 (Win10)
@willdurand The static themes in this context should be included into Theme artist. For now if a static theme is submitted and approved is considered into Add-ons developer. 

![titles](https://user-images.githubusercontent.com/33448286/41666117-6416bcd0-74b2-11e8-8a0d-26f6ec4c9de0.png)
