### ISSUE TITLE
Reset userId in addonsByAuthors reducer (or remove it)

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4602]
The `byUserId` portion of the `addonsByAuthors` reducer isn't 100% implemented because we only pass usernames and not entire user objects to the actions that fetch add-ons by user.

See: https://github.com/mozilla/addons-frontend/pull/4571#discussion_r175822983

**Comment by willdurand** [comment]
That has been fixed in https://github.com/mozilla/addons-frontend/pull/4611
