### ISSUE TITLE
Tags are no longer auto-deploying to stage

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4604]
When we tag `addons-frontend` on Tuesdays, the tag is automatically deployed to stage via CircleCI. It loks like https://github.com/mozilla/addons-frontend/pull/4546 somehow broke this. We are going to revert it to restore stage. We should put the CircleCI update patch back when we can figure out the issue.

**Comment by kumar303** [comment]
Maybe the [`only: master`](https://github.com/mozilla/addons-frontend/pull/4546/files#diff-1d37e48f9ceff6d8030570cd36286a61R87) filter is preventing the tag from deploying? Also, it looks like [`circle.yml`](https://github.com/mozilla/addons-server/blob/master/circle.yml) file for `addons-server` was not renamed. Was it necessary to rename it?

**Comment by jrbenny35** [comment]
Wait, what is happening? I see a tag AFTER the revert to V1

**Comment by jrbenny35** [comment]
Looks like we just need to add
```
filters:
  tags:
    only: /.*/
```

**Comment by tofumatt** [comment]
Our deploy tags fit a predictable and well-defined format, so if we can be more specific `/\d{4}\.\d{2}\.\d{2}/` might work and prevent accidental tags from being pushed... if we want that 🤷‍♂️

**Comment by jrbenny35** [comment]
I think the name change is just more in line with what circleci suggests.
