### ISSUE TITLE
add-on services: Tier-3 platform BSD equivalence to Tier-1 Linux

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#4610]
https://github.com/mozilla/addons-frontend/pull/3575 (Give XPIs to all Linux/Unix users) (2017-10-20) fixed: 

- [Cannot install add-on if it supports multiple platforms · Issue #2998 …](https://github.com/mozilla/addons-frontend/issues/2998)
- [AMO: Tier-3 platform BSD equivalence to Tier-1 Linux for new front-end purposes · Issue #3513 …](https://github.com/mozilla/addons-frontend/issues/3513)

A few months later (2018-02-10) I encountered a difficulty that made me wonder whether the equivalence had been partially lost, https://github.com/mozilla/addons-server/issues/2661#issuecomment-364655611 suggested raising the issue at addons-frontend. 

## Example A: Firefox Quantum about:addons search for Vertical Tabs Reloaded

https://addons.mozilla.org/firefox/search/?q=Vertical%20Tabs%20Reloaded&platform=FreeBSD&appver=59.0.1 does not find what's required (the named extension is not on the first page of results).

https://addons.mozilla.org/firefox/search/?q=Vertical%20Tabs%20Reloaded&platform=Linux&appver=59.0.1 – a manually edited URL, _Linux_ in lieu of _FreeBSD_ – has what's required first and foremost. 

https://addons.mozilla.org/addon/vertical-tabs-reloaded/versions/ at a glance, I can't see any platform specificity. 

----

Please: is there a bug? Or is there a logical reason (not visible to the end user) for not finding that particular named extension when FreeBSD is in the URL?

I might have stumbled across one or two other front end examples, but I don't have them handy.

**Comment by muffinresearch** [comment]
@grahamperrin Can you state the problem case a bit more concisely? I'm struggling to parse the content of the report above and understand what the problem actually is.

**Comment by jbeich** [comment]
Typing in `about:addons` search field shows less results on Tier3 platforms. For example, what's platform-specific in the following addons to be delisted on FreeBSD?
- https://addons.mozilla.org/en-US/firefox/search/?q=Multi%20Containers&platform=FreeBSD&appver=59.0.2
- https://addons.mozilla.org/en-US/firefox/search/?q=Tree%20Style%20Tab&platform=FreeBSD&appver=59.0.2

**Comment by jbeich** [comment]
Firefox replaces `%OS` string in `extensions.getAddons.search.browseURL` with `OS_TARGET` which for [supported](https://searchfox.org/mozilla-central/rev/028cd8342899/build/moz.configure/init.configure#592-622) Tier3 platforms would be either SunOS, GNU/kFreeBSD, DragonFly, FreeBSD, NetBSD, OpenBSD. Of those FreeBSD and SunOS have *incomplete* search results while DragonFly, NetBSD, OpenBSD, GNU/kFreeBSD show `Invalid "platform" parameter.`

**Comment by jbeich** [comment]
@landryb, can you try searching for Multi-Account Containers via "Search all addons" field in `about:addons` on OpenBSD? Do you see the addon in search results?

**Comment by jbeich** [comment]
For updates newer version is never found:
- Multi-Account Containers ([Linux](https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=@testpilot-containers&version=4.1.0&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=59.0.2&appOS=Linux&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=59.0.2&updateType=97&compatMode=normal) vs. [FreeBSD](https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=@testpilot-containers&version=4.1.0&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=59.0.2&appOS=FreeBSD&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=59.0.2&updateType=97&compatMode=normal) vs. [OpenBSD](https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=@testpilot-containers&version=4.1.0&maxAppVersion=*&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=59.0.2&appOS=OpenBSD&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=59.0.2&updateType=97&compatMode=normal))
- Tree Style Tab ([Linux](https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=treestyletab@piro.sakura.ne.jp&version=2.4.3&maxAppVersion=null&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=59.0.2&appOS=Linux&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=59.0.2&updateType=97&compatMode=normal) vs. [FreeBSD](https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=treestyletab@piro.sakura.ne.jp&version=2.4.3&maxAppVersion=null&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=59.0.2&appOS=FreeBSD&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=59.0.2&updateType=97&compatMode=normal) vs. [OpenBSD](https://versioncheck.addons.mozilla.org/update/VersionCheck.php?reqVersion=2&id=treestyletab@piro.sakura.ne.jp&version=2.4.3&maxAppVersion=null&status=userEnabled&appID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&appVersion=59.0.2&appOS=OpenBSD&appABI=x86_64-gcc3&locale=en-US&currentAppVersion=59.0.2&updateType=97&compatMode=normal))

**Comment by landryb** [comment]
https://addons.mozilla.org/en-US/firefox/search/?q=Multi-Account%20Containers&platform=OpenBSD&appver=60.0 -> Invalid Platform parameter.

Why am i not surprised ?

**Comment by muffinresearch** [comment]
@jbeich Thanks for the clarification.

**Comment by muffinresearch** [comment]
@diox looks like the API supports some additional platforms but not all. 

It seems like a possible workaround might be to map these other OSs to a closer matching platform e.g. Linux even if that's arguably not technically accurate. There might be other compatibility cases to consider here too.

Before doing that I'd like to understand what we're currently doing since we seem to have API responses for FreeBSD:

https://addons.mozilla.org/api/v3/addons/search/?q=test&platform=FreeBSD

but not OpenBSD:

https://addons.mozilla.org/api/v3/addons/search/?q=test&platform=OpenBSD

Whereas the documentation for the [platform parameter of the search API suggests FreeBSD isn't a valid platform ](http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-platform)

Would it be best to add additional mappings in the API? I don't see any OS mappings in the frontend AFAICT.

**Comment by diox** [comment]
We used to have a `BSD` platform, and still have aliases in place making `bsd`, `bsd_os` and `freebsd` work in API requests (the API is case insensitive here). So searching with `platform=FreeBSD` returns add-ons that, a super long time ago, were marked as compatible with BSD.

As is mentioned above the frontend *does* already have a workaround for this, and should already be mapping *BSD to Linux. This was implemented in https://github.com/mozilla/addons-frontend/pull/3575 . Presumably that's what should be fixed here ? Not sure where those URLs with platform=FreeBSD are coming from.

We could make the API treat *BSD as Linux as well but I'd like to understand how the API is receiving requests with such platform parameters in the first place...

**Comment by jbeich** [comment]
> Not sure where those URLs with platform=FreeBSD are coming from.

Firefox's addon manager appends `&platform=%OS%` when sending users to AMO.

https://searchfox.org/mozilla-central/rev/ce9ff94ffed3/browser/app/profile/firefox.js#48
https://searchfox.org/mozilla-central/rev/ce9ff94ffed3/toolkit/components/urlformatter/nsURLFormatter.js#92
https://searchfox.org/mozilla-central/rev/ce9ff94ffed3/xpcom/system/nsIXULRuntime.idl#46
https://searchfox.org/mozilla-central/rev/ce9ff94ffed3/toolkit/xre/nsAppRunner.cpp#872
https://searchfox.org/mozilla-central/rev/ce9ff94ffed3/build/moz.configure/init.configure#851
https://searchfox.org/mozilla-central/rev/ce9ff94ffed3/build/moz.configure/init.configure#627-628
https://searchfox.org/mozilla-central/rev/ce9ff94ffed3/build/autoconf/config.guess#833-841

**Comment by diox** [comment]
Ah I thought it'd do that for updates only. Ok then, it's unfortunate but I guess we need to handle that... @muffinresearch since we do have some mapping in the frontend already (see my previous comment) would it make sense to continue there and only send "linux" to the API in those cases?

My reasoning for doing this in the frontend is, you already need to handle API *output*, which will only ever be all/mac/linux/android/windows, so might as well make sure you're only sending one of those as well?

**Comment by muffinresearch** [comment]
@diox yep, I think that would make sense.

**Comment by landryb** [comment]
This is a running joke. Closing issues because they're stale is so sad.. they're stale because mozilla doesnt care about Tier3.

**Comment by willdurand** [comment]
@landryb hi, we can always reopen issues but we can't fix everything.. A repo with too many (old) issues is not healthy, especially when a team is working fulltime on it and external contributors are also helping. We are trying to fix this problem with the stalebot, maybe that is not a good solution, we'll see. Your comment allows us to know that people still care about this issue so I am going to reopen it.

**Comment by krytarowski** [comment]
Can you fix it for NetBSD? Thanks.

**Comment by iamleot** [comment]
Pong (issue still relevant)

**Comment by iamleot** [comment]
Can you please "pin this" or similar to avoid possible (non-)stale humans vs stalebots fights? :)

**Comment by grahamperrin** [comment]
Refresh?

**Comment by willdurand** [comment]
I think we can close this issue, we don't handle multiple platforms anymore.

**Comment by landryb** [comment]
can confirm that, using the search field in about:extensions on OpenBSD properly opens valid search results on AMO.

**Comment by grahamperrin** [comment]
For what it's worth, I haven't noticed any issue with everyday use of Firefox on FreeBSD `13.0-CURRENT` or `14.0-CURRENT`. 

I **do** see `platform=Linux` in the URL, however it very quickly appears to redirect.
