### ISSUE TITLE
Add-on name is overlapping the add-on icon in edit Collection form

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4612]
Follow up for #4579 

STR:

1. Log in to AMO dev and select "My Collections' from the user menu
2. Choose one collection to view it's details page
3. Click on Edit Collection link
4. In the edit collection form, observe the add-ons listed in your collection

Actual result:
Add-on name is overlapping the add-on icon

Expected result:
There is proper spacing between add-on name and add-on icon

Notes:
- reproduced on AMO-dev, FF59, Win10x64
- I think icons could be rendered a bit smaller, for a more consistent look

![image](https://user-images.githubusercontent.com/31961530/37710804-73d52bb2-2d17-11e8-8c1a-684363b2b468.png)

**Comment by kumar303** [comment]
Huh. Weird. It didn't look like this for me. Anyway, this screen has a lot of problems which are more apparent once I started using it.

I'm going to move it to a different screen in https://github.com/mozilla/addons-frontend/issues/4623
