### ISSUE TITLE
Do not hardcode en-US in "Learn more about permissions" link

### ISSUE THREAD

**Issue by TonnesM** [mozilla/addons-frontend#4613]
In issue #2757, a "Learn more about permissions" support link was added which includes /en-US/, so all locales redirect to the en-US article. Please remember to _never_ include /en-US/ in support links.

The link should use https://support.mozilla.org/kb/permission-request-messages-firefox-extensions instead to make it redirect to and display localized versions based on the browser locale.

https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/PermissionsCard/index.js#L57

**Comment by tofumatt** [comment]
Thanks for catching this! Some Mozilla sites actually won't redirect properly (and will 404 without a locale) so I think occasionally we get mixed up as to what we should do. In this case you're right though 👍

**Comment by tofumatt** [comment]
Fixed by #4615.

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF59, Win10x64

1. The permissions link is no longer hardcoded to /en-US/

![image](https://user-images.githubusercontent.com/31961530/37914839-d526c38c-3120-11e8-8c97-42b7486297b3.png)

2. even if the permissions link is not limited to /en-US/ anymore, when navigating to Permissions info page from AMO with a different locale, the permissions page will still be set to /en-US/

![locale perm](https://user-images.githubusercontent.com/31961530/37915233-bccdfbec-3121-11e8-90ad-ef095f6e5abe.gif)

@TonnesM , @tofumatt - I was under the impression that by fixing this issue, the user will be redirected to the same locale set in AMO. Is this not the case yet?

**Comment by TonnesM** [comment]
@AlexandraMoga This could occur when _en-US_ is set above _de_ in accepted languages (Options > Languages). There is no German version of the support article available at this point either, but you should see a warning in German for that when properly redirected, not the full en-US page. Also note some caching may be involved. When testing the link / button for my locale (nl), the Sumo redirect works as expected.

**Comment by AlexandraMoga** [comment]
@TonnesM thanks for clarifying. 
Retested after changing my language options and the redirection is happening as expected:

![lang perm](https://user-images.githubusercontent.com/31961530/37949510-b7a98218-319d-11e8-918f-d6d0f28b6487.gif)
