### ISSUE TITLE
The number of add-ons from edit Collection form matches only the number included in the active collection page 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4614]
Follow up for #4579 

STR:

Prerequisites: you need to have a collection with more than 25 add-ons included

1, Log in to AMO-dev and select a collection with more than 25 add-ons 
(i.e. https://addons-dev.allizom.org/en-US/firefox/collections/AlexandraMoga1/friday-afternoon/)
2. In the collection details, click on Edit collection link
3. Count the add-ons displayed in the edit collection form

Actual result:
The edit collection form includes 25 add-ons, which is also the maximum displayed on one collection page

Expected result:
The edit collection form should include the total number of add-ons, including those available on the next pages

Notes:
- if you navigate to page 2 of the collection and click again on Edit collection, the add-ons displayed in the edit collection form will also be only those available on page 2
- reproduced on AMO dev with FF59, Win10x64 and Andorid 7.0

![max add-ons](https://user-images.githubusercontent.com/31961530/37711925-090784a2-2d1b-11e8-8b88-a719a58469c9.gif)

**Comment by kumar303** [comment]
Ah, whoops, good catch. I think this overlay isn't going to work at all (there are other reasons). I'm going to move it to a different view in https://github.com/mozilla/addons-frontend/issues/4623

Because this bug won't apply to the new view, I'm closing it.
