### ISSUE TITLE
Search field in edit collection form has an action arrow with no functionality

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4617]
Follow up for #4579 

STR:

1. Log in to AMO-dev and select a collection to view its details page (i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/bookmark-managers/)
2. Click on Edit collection link
3. In the edit collection dialog, look at the search field in the far right

Actual result:
There is an action arrow similar to the one from the AMO header search, but for collections this has no practical function

Expected result:
The arrow should not be present in the search field included in the edit collection component

Notes:
- reproduced on AMO-dev, FF59, Win10x64 and Android 7.0

![arrow](https://user-images.githubusercontent.com/31961530/37715104-d495e08e-2d23-11e8-9d5c-9a3a5d2f58e8.gif)

**Comment by kumar303** [comment]
I may have forgotten to mention this in the styling issue but the arrow will be fixed in https://github.com/mozilla/addons-frontend/issues/4590

**Comment by AlexandraMoga** [comment]
The fix that was supposed to address this issue has been closed but the problem reported still exists.
Based on that, I'm reopening this bug.

![image](https://user-images.githubusercontent.com/31961530/42816884-ea47d974-89d4-11e8-85fd-3fd12542ce2a.png)

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF61(Win10)
While navigating with keyboards I've also noticed that the arrow is selected yet it has no role because pressing enter won't trigger an action. If I search for an extension and I wish to add it to the list using keyboard I use the arrow key then press enter. 

![the arrow - no action](https://user-images.githubusercontent.com/33448286/42817242-313180fa-89d6-11e8-92fb-0da7c461b136.gif)

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga, that indeed was not addressed as part of PR #4800, so thanks for re-opening.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF61, WIn10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/43311993-ae2b8ba8-9194-11e8-8141-a8245749450b.png)
