### ISSUE TITLE
Searching for add-ons inside the edit collection form is not working on Android in landscape mode

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4618]
STR:

1. Log in to AMO-dev on an Android device
2. Select a collection to view it's details page (i.e. https://addons-dev.allizom.org/en-US/android/collections/mozilla/ad-blockers/)
3. Turn your device in landscape mode and click on Edit collection
4. Tap on the search field inside the edit collection form and try to search for add-ons

Actual result:
The search field and other elements will disappear from the edit collection component when the device keyboard is active

Expected result:
The user is able to search for add-ons inside the edit collection form when using an Android device in landscape mode

Notes:
- reproduced on AMO-dev, FF59, Android 7.0
- this might be addressed when fixing #4258 

![edit-landscape](https://user-images.githubusercontent.com/31961530/37717004-7bf01684-2d28-11e8-85d5-fcab4485213b.gif)

**Comment by bobsilverberg** [comment]
This may also have been fixed by moving away from the overlay. @AlexandraMoga can you please check whether this is still reproducible?

**Comment by AlexandraMoga** [comment]
Not reproducible anymore with the new Edit collection form.
