### ISSUE TITLE
Edit collections on the detail view without an overlay

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4623]
The edit collection screen (https://github.com/mozilla/addons-frontend/issues/4579) is currently shown in a full screen overlay. After discussing it with @tofumatt, we think it would be better to re-use the existing collection detail view ([example](https://addons.mozilla.org/en-US/firefox/collections/mozilla/good-time-tabs/)) for editing collections. 

For QA:
* sign in
* create a collection
* view the collection
* click *Edit collection* underneath the collection info
* The info card view on the left should turn into a form where the values can be edited
* You should be able to change the collection name, description, and URL
* You will not be able to edit the add-ons (yet)
* Searching for and selecting an add-on will not add it to the collection (yet)

Why? Here are some problems with the overlay
* Add-on pagination is going to be complicated (see https://github.com/mozilla/addons-frontend/issues/4614)
* Overlays are hard for mobile because of scrolling
* The current edit view has a more efficient screen layout because the add-ons are on the right, info is on the left

**Comment by ioanarusiczki** [comment]
I tested this issue on AMO dev with FF59(Win10). 
The info card turns into a form which can be used to change the name, description and URL.
Editing the add-ons inside the collection or adding new add-ons don't work yet.

![edit collection testing new form](https://user-images.githubusercontent.com/33448286/37966061-eb6d5002-31cf-11e8-8331-b71e4a220384.gif)
