### ISSUE TITLE
Cannot login to AMO

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4627]
Steps to reproduce:
1.Try to login to AMO , with any account

Expected results: 
Users are logged without problems

Actual results:
Server error encountered

NOTES:
Started to be reproducible right now, not an old issue

**Comment by EnTeQuAk** [comment]
https://sentry.prod.mozaws.net/operations/olympia-prod/issues/3365259/

**Comment by kumar303** [comment]
I can log in just fine on dev, stage, and prod. Can you provide more details? What page did you start from?

**Comment by diox** [comment]
Fixed in https://github.com/mozilla/addons-server/commit/be2425e4462e2a7e2f298cd9930f15e7b76343fb

See https://github.com/mozilla/addons-server/issues/7822#issuecomment-375404267

**Comment by vcarciu** [comment]
Verified as fixed yesterday.
