### ISSUE TITLE
Open/Close AutoSearchInput dropdown with Redux state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#4631]
The [AutoSearchInput](https://github.com/mozilla/addons-frontend/blob/dd0afb33cac75326dd0cceb8a19ec5bf9b85bd67/src/amo/components/AutoSearchInput/index.js) component does `setState({ autocompleteIsOpen: true | false })`. It should use Redux state instead so that we can use the [Redux development tool](http://extension.remotedev.io/) to work on this component. Beware that `setState({ searchValue: '...' })` is still necessary because typing characters in a text box should not dispatch Redux actions.

**For QA**: Please check for regressions in the autcomplete functionality of the search box in the header

**Comment by willdurand** [comment]
To me, this logic (open/close) belongs to the component because it is a pure UI piece of information.

**Comment by tofumatt** [comment]
> To me, this logic (open/close) belongs to the component because it is a pure UI piece of information.

I was thinking that when commenting/talking to @SeanPrashad but wasn't 100% sure and was admittedly half-occupied with other stuff 😅

Also given it already needs to use `setState` I think it's okay to leave out of Redux. The devtools are handy but we already don't store absolutely everything in Redux (usually in cases like this) so I think it's okay to not store it here either.

**Comment by willdurand** [comment]
The React devtools allows to (easily) toggle boolean attributes in the state (with a checkbox). I often have the React panel with the component I am working on selected.

**Comment by willdurand** [comment]
Redux is not a drop-in replacement for React state. And, Redux is useful to manage the app state,  that is the data, not the UI stuff like "is this dropdown open/closed?". https://redux.js.org/faq/organizing-state#organizing-state-only-redux-state

**Comment by kumar303** [comment]
Before we converted the [open/close overlay state change](https://github.com/mozilla/addons-frontend/issues/3222) to Redux, it was not possible at all to develop one of those screens with Redux tools. Why break the tools? They are super helpful.

There are several open bugs filed by QA that no one else can reproduce. Imagine if we could just download a stack of actions and replay them? Life would be so good.

**Comment by kumar303** [comment]
Maybe I'm misunderstanding but the [link](https://redux.js.org/faq/organizing-state#organizing-state-only-redux-state) you posted completely reinforces my point.

> Is there value to you in being able to restore this state to a given point in time (ie, time travel debugging)?

YES; immense value. If we *do not* agree that this is valuable then we shouldn't be using Redux at all! Redux definitely adds overhead to the initial development process but once it's there you can edit and refactor it quite easily.

**Comment by willdurand** [comment]
You picked one point out of 5, the 4 others don't really go into your direction. Anyway, I understand what you mean (and did not see your previous comment before your last one). Yet, I don't think it is all or nothing.

I don't think we should be storing everything in redux and I don't think it is a "poor design choice" because only the component that renders the dropdown should know about whether it is open or not. I don't really want the whole app to get notified and potentially updated entirely because this dropdown switches from a closed to open state. That's my main concern.

Of course, I see the value in replaying a set of actions for bug fixes if we can achieve this somehow.

**Comment by kumar303** [comment]
> You picked one point out of 5, the 4 others don't really go into your direction.

I'll clarify what I meant here. When considering the dropdown open/closed state I would indeed answer *no* to [all of these questions](https://redux.js.org/faq/organizing-state#organizing-state-only-redux-state) except this one: *Is there value to you in being able to restore this state to a given point in time?* Answering *yes* to that one question validates using Redux. If we don't use Redux then it is not possible to restore state at any given time. Game over.

> I don't really want the whole app to get notified and potentially updated entirely because this dropdown switches from a closed to open state.

That would just be a reducer bug like any other reducer bug. We have had success in preventing these bugs through code review. If the switch case in a reducer is checking for action types incorrectly it's usually pretty obvious.

By the way, tracking [overlay open/close state](https://github.com/mozilla/addons-frontend/blob/b2ed7540f2085dc0b07442248d05ab78f2ffe15d/src/ui/components/FormOverlay/index.js#L168) is working very well. It executes all other reducers but they just ignore the action, similar to any other foreign action. For the first time ever I've been able to use Redux developer tools on overlay pages which is really helpful.

The *Organizing State* page in the Redux docs has some links to projects that aim to reduce the boilerplate around connecting local component state to Redux: [redux-ui](https://github.com/tonyhb/redux-ui), [redux-component](https://github.com/tomchentw/redux-component), [redux-react-local](https://github.com/threepointone/redux-react-local). I didn't know about these and took a quick look. I'm concerned about ID generation (mostly for SSR), how testable they are, and how we could use Flow to validate state but I like the idea of using an abstraction to make Redux-ification easier.

**Comment by willdurand** [comment]
> The Organizing State page in the Redux docs has some links to projects that aim to reduce the boilerplate around connecting local component state to Redux: redux-ui, redux-component, redux-react-local. I didn't know about these and took a quick look. I'm concerned about ID generation (mostly for SSR), how testable they are, and how we could use Flow to validate state but I like the idea of using an abstraction to make Redux-ification easier.

All of them seem abandoned.

Let's stick to what you've done in the `FormOverlay` component then, and see how it goes. Reverting to good old local state won't be that complicated if it turns out that it does not work as well as expected.
