### ISSUE TITLE
Change "Download Firefox" message bar from grey to green

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#4633]
I'd rather we A/B test grey vs. green on the message bar, but since we can't let's just go with [the green style](https://design.firefox.com/photon/components/message-bars.html#color-2) for the "Download Firefox" prompt for non-Fx users.

<img width="641" alt="screen shot 2018-03-23 at 1 46 28 pm" src="https://user-images.githubusercontent.com/6797635/37845341-9ffef116-2ea0-11e8-9124-0498cc90d37e.png">

**Comment by pwalm** [comment]
To be extra clear, this one:
<img width="815" alt="screen shot 2018-03-23 at 1 50 03 pm" src="https://user-images.githubusercontent.com/6797635/37845506-2142e69c-2ea1-11e8-8f1f-c056c0689a5b.png">

**Comment by svitlana-galianova** [comment]
Hi, I would like to help out with this issue

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev using Chrome for Win10, Chrome for Android and Safari on iOS
The message is green. Download Firefox button is green too. 

![message green](https://user-images.githubusercontent.com/33448286/37916696-31d7692a-3125-11e8-9535-3cde84909ff5.png)

![safari green message](https://user-images.githubusercontent.com/33448286/37916722-3ea33544-3125-11e8-8ecd-19da041798de.jpg)

![android - chrome](https://user-images.githubusercontent.com/33448286/37916752-5626c816-3125-11e8-937a-9acd0fadc8ee.png)

**Comment by pwalm** [comment]
My fault: I should have specified the glyph for the message bar. We should use the firefox single colour glyph, not the checkmark.
[glyph-firefox-16.svg.zip](https://github.com/mozilla/addons-frontend/files/1878485/glyph-firefox-16.svg.zip)
