### ISSUE TITLE
Enable collection access via id in the front end

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4640]
With https://github.com/mozilla/addons-server/issues/7529 landed, we are now able to have URLs that point to collections using the id rather than the slug. This is something that was requested to remove a [hack](https://github.com/mozilla/addons-frontend/blob/ceb360b6ab5358eee52baebca0f7d49202409f01/src/amo/sagas/collections.js#L197-L202) that is in place to address a race condition when a user saves a collection with a new slug.

There has also been some discussion in https://github.com/mozilla/addons-server/issues/7529 about whether we actually want to expose collection URLs via ids, so I am not sure exactly what we want to implement at this time. I think more discussion is required around this.

**Comment by eviljeff** [comment]
From https://github.com/mozilla/addons-server/issues/7529#issuecomment-370877881 Jorge said:

> >  should we allow non-API URLs to work by both id and slug too?

> I'd prefer to only support the slug, since ID enumeration would be trivial to find existing collections. I know they're all technically public, but I'd favor not making them so easy to find.

That's the question settled, isn't it?

**Comment by tofumatt** [comment]
Yeah. We redirect to slugs from IDs for add-ons themselves on the frontend but it's a server-redirect and it's only to support legacy URLs. Let's keep URLs simple and avoid ID-based ones if we have slugs.

**Comment by bobsilverberg** [comment]
@eviljeff Yes, that's pretty clear, but I feel like it contradicts the comment at https://github.com/mozilla/addons-frontend/blob/ceb360b6ab5358eee52baebca0f7d49202409f01/src/amo/sagas/collections.js#L197-L202, which suggests that once https://github.com/mozilla/addons-server/issues/7529 lands we'll switch to using an id based URL. 

Also the comments at https://github.com/mozilla/addons-server/issues/7529#issuecomment-366014676 and https://github.com/mozilla/addons-server/issues/7529#issuecomment-369311349 further suggest that https://github.com/mozilla/addons-server/issues/7529 was opened for the purpose of serving the edit link via id, which we're now saying we won't do. I'm just a bit wary of saying we won't do it when it seems like it's the whole reason that https://github.com/mozilla/addons-server/issues/7529 was opened in the first place. 

Maybe it's okay to serve edit by id, because one needs to have access to a collection in order to edit it? Although I think the current implementation would still reveal that a collection exists, even if the user doesn't have access to edit it.

Comments?

**Comment by eviljeff** [comment]
mozilla/addons-server#7529 it was mentioned that there is no concept of a private collection any more, so I don't think exposing the collection's existence is a problem.  If addons-frontend is going to use IDs in edit collection urls that's probably okay too - it's the view collection urls that should only be slug accessible, afaik.
@jvillalobos can contradict if I've #fakequoted him

**Comment by bobsilverberg** [comment]
I think I misspoke when I suggested we could do it just for edit. The point of the change was to allow all collection access via id as opposed to via slug, and it doesn't sound like that's something we want to do.

**Comment by jvillalobos** [comment]
Correct, we don't want to have collections be easily accessible with just their ID in the public URL. There are other areas where their existence is exposed via ID, like the devhub and some parts of the API (as I understand it), but that's acceptable IMO.

**Comment by bobsilverberg** [comment]
Based on the discussions, I am going to close this issue, as it doesn't seem like something we want.
