### ISSUE TITLE
Increase the truncation limit of the About this extension description

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/addons-frontend#4642]
### Describe the problem and steps to reproduce it:
Viewing a [fantastic add-on](https://addons.mozilla.org/en-US/firefox/addon/facebook-container/) page, I noticed that the description was cut off far too early with the **Read more** link.

### What happened?
Well, what happened was the description was cut off way too early and the page was very imbalanced.

### What did you expect to happen?
I expected for it to at least balance off before truncating.

### Anything else we should know?
What was really strange was that when I expanded the entire description, it was still shorter than the left column.

**Comment by tofumatt** [comment]
Agreed! There is an existing issue for this: #3787. Thanks for filing, but I'll close this one as a duplicate. 😄
