### ISSUE TITLE
Search suggestions list in edit collection form is showing only 4 add-ons and ends abruptly 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4645]
Follow up for #4623 

STR:

1. Log in to AMO-dev and click on a collection to view its details page (i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/password-managers/)
2. Click on Edit collection option
3. In the search field, enter a search term 
4. Observe the list with add-on suggestions

Actual result:
There are only 4 add-ons displayed and the list looks cut off

Expected result:
The search suggestion list should display more add-ons and should fit entirely inside the edit collection form

Notes:
- on mobile, there are only 3 suggestions displayed
- reproduced on AMO-dev, FF59, WIn10x64 and Android 7.0

**[1] desktop**
![image](https://user-images.githubusercontent.com/31961530/38011340-ba68f560-3265-11e8-9a84-d81aec2ff300.png)

**[2] mobile**
![image](https://user-images.githubusercontent.com/31961530/38011449-2ab788d6-3266-11e8-80db-35c5174e9c83.png)

**Comment by tofumatt** [comment]
Closed by #4699

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF59, Win10x64 and Android 7.0

![search coll list](https://user-images.githubusercontent.com/31961530/38257971-059a282a-376a-11e8-86a1-a2e431e634a1.gif)
