### ISSUE TITLE
User is redirected to the legacy site when refreshing the page while editing a collection

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4647]
Follow up for #4293

STR:

1. Log in to AMO-dev and click on a collection to view its details page (i.e. https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/password-managers/)
2. Click on Edit collection option
3. Observe that the URL changes to `/collections/<username>/<collection-slug>/edit/`
4. Refresh the page

Actual result:
The legacy page for collection edit is displayed after page refresh

Expected result:
The user remains on the new frontend after refreshing the page while editing a collection

Notes:
 - reproduced on AMO-dev with FF59, Win10x64 and Android 7.0
 - clicking 'back' or 'View the new site' from the page footer will not redirect the user on the new frontend

![legacy coll](https://user-images.githubusercontent.com/31961530/38013037-57e9a342-326c-11e8-8416-68d32b5ce50c.gif)

**Comment by tofumatt** [comment]
That implies that these routes are not enabled in nginx. @bqbn: are there nginx settings for `/collections/:username/:slug/` to point to the new front-end?

**Comment by muffinresearch** [comment]
On the basis this is on -dev I'm marking as p3.

**Comment by bobsilverberg** [comment]
I'm not really clear on how all this works, but I just wanted to point out, so it's not missed, that this is something we want working on dev, but we don't want the new screen on stage or prod yet. I assume nginx rules can be set up just for dev?

**Comment by tofumatt** [comment]
They can. We actually have rules for the user profile page that work like that already.

- Matthew Riley MacPherson
tofumatt.com

**Comment by bqbn** [comment]
> are there nginx settings for `/collections/:username/:slug/` to point to the new front-end?

Yes, there are. But, there is no route for `/collections/:username/:slug/edit/`.

@bobsilverberg, if there are new routes being added to https://github.com/mozilla/addons-frontend/blob/master/src/amo/routes.js and needing to be routed to the mobile site, please feel free to file an issue and assign to me.

And if the route only needs to be in a particular environment, please indicate that in the issue. Here is an example for that: https://github.com/mozilla/addons-frontend/issues/4284#issuecomment-373744991

Thanks.

**Comment by bobsilverberg** [comment]
@AlexandraMoga with #4655 done, can you please check this again?

**Comment by AlexandraMoga** [comment]
This is working now:

![coll refresh](https://user-images.githubusercontent.com/31961530/38095444-2c2e65a4-3379-11e8-8fcb-be5174629d91.gif)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF59, Win10x64
