### ISSUE TITLE
Collection name can be left blank by entering only blank spaces in the Name field in the edit collection form

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4652]
Follow up for #4623 

STR:

1, Log in to AMO dev and select 'View My Collections' from the user menu
2. Choose a collection to view its details page
3. Click on Edit collection underneath the collection info card
4. Edit the collection name by entering only blank spaces
5. Click on Save Collection

Actual result:
Collection is successfully saved with a blank name

Expected result:
A collection should not be saved when the Name field contains only blank spaces

Notes:
 - reproduced on AMO-dev, with FF59, Win10x64

![blank col name](https://user-images.githubusercontent.com/31961530/38031709-8f51b1ca-32a4-11e8-83b2-4ee236ab974d.gif)

**Comment by muffinresearch** [comment]
This should be validated on the frontend but this also probably needs a API counterpart to prevent it there too.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, FF59, Win10x64 and Android 7.0

![coll blank name](https://user-images.githubusercontent.com/31961530/38188537-0faf5ae8-3665-11e8-96a5-c973d9f897a5.gif)

**Comment by bobsilverberg** [comment]
#4698 is a nice fix, but I am also concerned that the validation in `onSubmit` did not catch this. @tofumatt do you think it's enough to disable the `Save Collection` button, or should we also make sure that there's working validation for this case in `onSubmit`?

**Comment by tofumatt** [comment]
Hmmm... I think us disabling the form is good enough but if the server allows empty collection names we could check... but in the future I expect someone who actually managed to still get `onSubmit` to fire would get an API error.

But at that point it feels like an API bug our error handler would just catch. They can still submit empty data to the API if they really want, we are already stopping all but the most ardent Devtools Inspector punks. 😉

If you wanted to open a new code quality issue for it though, feel free.
