### ISSUE TITLE
Add new routes for new collections UI

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4655]
We'll need new routes in nginx to route collection requests to the new front-end. Here is what we need:

- [ ] Edit collection: collections/:user/:slug/edit/ (landed in #4623)
- [ ] Create collection: collections/add/ (depends on #4003)
- [ ] My collections: collections/

These should both be enabled on dev only for now, and I will update this issue when we want them turned on for stage and prod.

**Comment by bqbn** [comment]
Both endpoints, `collections/:user/:slug/edit/` and `collections/add/` are routed to the mobile site on -dev.

Please test.

Please ping me when this is ready for -stage and/or -prod.

**Comment by bobsilverberg** [comment]
@bqbn Could you please enable the third route listed above `collections/` on -dev?

**Comment by bqbn** [comment]
`collections/` should now be routed to the mobile site on -dev.

**Comment by bobsilverberg** [comment]
Thanks @bqbn!

**Comment by bobsilverberg** [comment]
@bqbn These are also now ready to be configured on stage. Could you please enable the rules on stage for: 

- collections/:user/:slug/edit/
- collections/add/
- collections/

Thanks!

**Comment by bqbn** [comment]
The said 3 endpoints are now routed to the mobile site on -stage.

**Comment by bobsilverberg** [comment]
Thanks @bqbn

**Comment by bobsilverberg** [comment]
@bqbn We also need these routes enabled on prod to coincide with this week's push. Can you please take care of that? The rules are: 

- collections/:user/:slug/edit/
- collections/add/
- collections/

Thanks!

**Comment by bqbn** [comment]
PR https://github.com/mozilla-services/cloudops-deployment/pull/2257 merged.

Please add a note to the etherpad as a reminder for the push day.

**Comment by bobsilverberg** [comment]
> Please add a note to the etherpad as a reminder for the push day.

Done, thanks @bqbn!

**Comment by AlexandraMoga** [comment]
Verified fixed in prod
