### ISSUE TITLE
No entro en esta pagina

### ISSUE THREAD

**Issue by flarry9** [mozilla/addons-frontend#4659]
Estimados,  no entro es esta pagina https://getcryptotab.com/121506, al principio pude acceder a ella, luego desintalé el Plugin y desde ese momento no puede entrar y configurar mi login en esta pagina para minar, gracias

**Comment by flarry9** [comment]
Estimados, no entro es esta pagina https://getcryptotab.com/121506, al principio pude acceder a ella, luego desintalé el Plugin y desde ese momento no puede entrar y configurar mi login en esta pagina para minar, gracias

**Comment by jvillalobos** [comment]
El complemento fue removido porque no pasó la revisión de calidad y seguridad. El desarrollador deberá hacer algunos cambios para poder habilitar el complemento nuevamente y que la página se pueda acceder.
