### ISSUE TITLE
stop vertical cropping theme previews (and some other comments)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#4661]
refiled based on the conclusion of mozilla/addons-server#7888

quoting @jvillalobos 
> What I'd like to avoid is what is shown in the "Search results / category list page (wide browser)" screenshot, which is cropping the image vertically. Can we at least make sure the full height of the preview is shown? 

Search results / category list page (wide browser)
![screenshot 2018-03-27 18 22 50](https://user-images.githubusercontent.com/768592/37962176-e57183c2-31ec-11e8-8228-d1fae8674f6e.png)

And possible follow-ups:
> Maybe in the future we can do some fancy expand or scroll on hover, so the user can inspect the rest of the preview from those pages.

> It'd be nice if the shelves expanded vertically to become 2x2 rather than 1x4

**Comment by tofumatt** [comment]
2x2 is in the UX mocks and was added I think after the first implementation of this. It makes it harder to display mixed results (we'd need to re-sort the results locally to tetris them together) and would technically change the order returned by the API, but it would totally look nicer and probably not mess up ordering *that* much.

It could be that theme 2x2 only show when the results are *only* themes. 🤷‍♂️

**Comment by eviljeff** [comment]
@tofumatt I think @jvillalobos was talking about the featured shelves - the results aren't 1x4, but the shelves are (see mozilla/addons-server#7888 for the rest of the screenshots) which, afaik, only contain one type of content.  Regardless, the cropping on the previews on search results is the main issue here.

**Comment by jvillalobos** [comment]
Yeah, I think the shelves issue is a separate thing. The vertical cropping is what I would like to fix before we launch static themes.

**Comment by jvillalobos** [comment]
Not sure is this would be a P2, since I don't know if we're already showing static themes on search results on dev.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10).
The new height is 100px, before it was 64px 
Before and after the fix
![issue 4661](https://user-images.githubusercontent.com/33448286/40925914-8227730e-6823-11e8-9f8c-5c4590fd19b7.png)
