### ISSUE TITLE
fix

### ISSUE THREAD

**Issue by anggun04** [mozilla/addons-frontend#4667]

**Comment by anggun04** [comment]
I can't access my addons

**Comment by tofumatt** [comment]
This is the issue tracker for the add-ons site and related projects, not for an add-on or Firefox.

If you're having an issue with an add-on please contact the developer directly; you can find a link to their contact details on the add-on page on https://addons.mozilla.org/

If you have a Firefox bug, please file it at http://bugzilla.mozilla.org/show_bug.cgi?id=1445552
