### ISSUE TITLE
Theme installation shows a bar post-installation

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#467]
There's currently no way to install a lightweight theme with the addonmanager apis exposed to the disco pane. As a result of the user will see this following the installation of a lightweight theme.

![unspecified](https://cloud.githubusercontent.com/assets/1514/15618993/2695413a-2449-11e6-92b7-11c37ef1afb4.png)

We're working out to handle the "Undo" case if we can't silently install the theme (which at this point it doesn't look like we can).

This bug is here mainly to make UX aware that this is going to be the current flow and to discuss what the ideal approach is and balance that with what's possible in the time we have before this hits beta.

**Comment by muffinresearch** [comment]
Current plan is to assume we can't silently install and to get an event exposed so we can know if the user clicks undo and can show the change in state in the button.

The bug to cover that is here [1]  (Although it was raised for a different purpose so the title is misleading) 

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1268077

**Comment by aswan** [comment]
Good news / bad news.
The good news is I got AddonListener events exposed through mozAddonManager.
The bad news is I think there are other bugs somewhere that are going to make this tricky.  In particular, I did the following sequence of actions:
1. go to discovery.addons-dev.allizom.org
2. in the console add an event listener for onDisabled: `navigator.mozAddonManager.addEventListener("onDisabled", e => {console.log(e)})`
3. click the button to install the "japanese tattoo" theme and click "allow"
(at this point, the new theme has been applied and i see an onDisabled event logged to the console for the default theme, which is expected)
4. click "undo" in the "new them" bar that drops down
(at this point, some state somewhere is wrong, i don't see an onDisabled event for the tattoo theme and the following error is logged:
`1464387392740	addons.xpi	WARN	Attempting to activate an already active default theme`
which together suggest that the browser is in an inconsistent state in which it think the default theme is active when in fact the tattoo them is active.

I tried dismissing the "new theme" bar and then clicking the green button again, that did uninstall the theme but again, no onDisabled event (though I didn't get the addons.xpi warning that time...)

However, going through those steps, then opening a new tab at about:addons, going to "Appearance" and disabling or removing the theme from there *does* generate an onDisabled event.

I'll attach my AddonListener patch to the bugzilla bug that Stuart mentioned above, it will need tests and review if its going to land, but I think this needs to be sorted out first.

**Comment by aswan** [comment]
If anybody wants to play around with this, I kicked off a try build with the AddonListener patches (for mac only).  A build with the patches should appear shortly at
https://archive.mozilla.org/pub/firefox/try-builds/aswan@mozilla.com-20430d0c1ecff7f918137ecb05e1d2c3f684cf72/

**Comment by designakt** [comment]
Having a confirmation for theme installs is good. We would like to have one for [extensions too](https://github.com/mozilla/addons/issues/112). It being a notification bar is probably not the best, but I think it is OK for a first version.
Not knowing the installation state however is problematic as it challenges the on/off UI we have in place.
Thanks for letting us know and I hope we find a way to always know the right state. :-)

**Comment by muffinresearch** [comment]
@aswan I only see what looks like a log for the try build.

Does `onExternalInstall` not fire for themes?

**Comment by muffinresearch** [comment]
If the event stuff doesn't work out, another solution (until we can track state) would be to make the Theme installation UI not use the same button as the addon installation which is more like the current discovery pane. E.g. there's not reflection on theme installation state in the UI.

**Comment by aswan** [comment]
There was a hiccup with the AddonListener patch, but there should now be a usable build here:
https://archive.mozilla.org/pub/firefox/try-builds/aswan@mozilla.com-55b3c71b30e48129e8a32c30c6a602c8b06bcf13/try-macosx64/

It looks like onExternalInstall should get called but that method is called on InstallListeners, not AddonListeners, which are two separate things.  We could wire up a DOM interface to create an InstallListener but having onDisabled work for themes seems "more right".

**Comment by muffinresearch** [comment]
@aswan - playing with the build looks like we get `onEnabled` as well as `onDisabled` I see that working in the sense that it's fired both on installing the new theme and when pressing undo because that enables the old theme so you see the onEnabled. I think that might do what we need as a result.

**Comment by muffinresearch** [comment]
Here's what clicking install for a lightweight theme and then hitting "undo" in the bar shows:

```
onEnabled { target: AddonManager, isTrusted: true, id: "702919@personas.mozilla.org", needsRestart: false, currentTarget: AddonManager, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464793462645340, originalTarget: AddonManager }
onEnabled { target: AddonManager, isTrusted: true, id: "{972ce4c6-7e08-4474-a285-3208198ce6fd}", needsRestart: false, currentTarget: AddonManager, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464793467969887, originalTarget: AddonManager }
```

**Comment by aswan** [comment]
@muffinresearch are you printing all events or just onEnabled events?  I would think the "right" thing would be to get onDisabled for the old theme at the same time you get onEnabled for the new theme, its not clear from the combination of the previous two comments if that's happening or not.  I guess if you can work with it I shouldn't be too picky though!
Just asked for review for the firefox patches, hoping to land them before the end of the week and request uplift to 48.

**Comment by muffinresearch** [comment]
@aswan, I agree - but as you previously described you only get the `onDisabled` event for the original theme and no onDisabled event happens when pressing undo presently. As you already said that seems to be a bug - I saw that in the try build.

Here's the full log with both events:

```
onDisabled { target: AddonManager, isTrusted: true, id: "{972ce4c6-7e08-4474-a285-3208198ce6fd}", needsRestart: false, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464855728682982, originalTarget: AddonManager, explicitOriginalTarget: AddonManager }
onEnabled { target: AddonManager, isTrusted: true, id: "703294@personas.mozilla.org", needsRestart: false, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464855728703405, originalTarget: AddonManager, explicitOriginalTarget: AddonManager }
1464855734389	addons.xpi	WARN	Attempting to activate an already active default theme
onEnabled { target: AddonManager, isTrusted: true, id: "{972ce4c6-7e08-4474-a285-3208198ce6fd}", needsRestart: false, eventPhase: 0, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464855734433826, originalTarget: AddonManager, explicitOriginalTarget: AddonManager }
```

**Comment by muffinresearch** [comment]
Further digging around looks like this part of the code is getting called when hitting undo: https://dxr.mozilla.org/mozilla-central/source/toolkit/mozapps/extensions/LightweightThemeManager.jsm#

If I listen to `onUninstalling` and `onUninstalled` those are bothe fired for the installed theme when hitting undo:

```
navigator.mozAddonManager.addEventListener("onEnabled", e => {console.log(e)})
undefined
navigator.mozAddonManager.addEventListener("onDisabled", e => {console.log(e)})
undefined
navigator.mozAddonManager.addEventListener("onUninstalling", e => {console.log(e)})
undefined
navigator.mozAddonManager.addEventListener("onUninstalled", e => {console.log(e)})
undefined

// Install the new theme

onDisabled { target: AddonManager, isTrusted: true, id: "{972ce4c6-7e08-4474-a285-3208198ce6fd}", needsRestart: false, currentTarget: AddonManager, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464856864510023, originalTarget: AddonManager }
onEnabled { target: AddonManager, isTrusted: true, id: "362876@personas.mozilla.org", needsRestart: false, currentTarget: AddonManager, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464856864527716, originalTarget: AddonManager }

// Press Undo
onUninstalling { target: AddonManager, isTrusted: true, id: "362876@personas.mozilla.org", needsRestart: false, currentTarget: AddonManager, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464856868100164, originalTarget: AddonManager }
onEnabled { target: AddonManager, isTrusted: true, id: "{972ce4c6-7e08-4474-a285-3208198ce6fd}", needsRestart: false, currentTarget: AddonManager, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464856868114336, originalTarget: AddonManager }
onUninstalled { target: AddonManager, isTrusted: true, id: "362876@personas.mozilla.org", needsRestart: false, currentTarget: AddonManager, eventPhase: 2, bubbles: false, cancelable: false, defaultPrevented: false, timeStamp: 1464856868115878, originalTarget: AddonManager }

```

**Comment by muffinresearch** [comment]
As a side note I did find I had to set the Addons installation permission for the site (https://discovery.addons-dev.allizom.org) (via the permissions UI accessed via the info box to the left of the address bar) to not get the bar that says "This site tried to install a theme". 

Not sure if that's a step missed for using the try build with the dev new disco pane site?

**Comment by muffinresearch** [comment]
This is now covered by #507 and #540. Thanks all.
