### ISSUE TITLE
Desktop only addon

### ISSUE THREAD

**Issue by fadefa** [mozilla/addons-frontend#4672]
### What happened? 
I was looking for the add-on "desktop only", but I couldn't find it any more in the Mozilla add-ons site. Googling it I foun the link for the add-on, but I got this answer from the server:
"Sorry, but we can't find anything at the address you entered.
If you followed a link from somewhere, please file an issue. Tell us where you came from and what you were looking for, and we'll do our best to fix it."
I'd like to know if the add-on I'm looking for is steel available

### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/addon/desktop-only

**Comment by tofumatt** [comment]
That means the add-on has been unlisted from the site. If there's contact info for the author elsewhere you could ask them; otherwise @jvillalobos might know why.

**Comment by jvillalobos** [comment]
The add-on has pending review issues that need to be addressed before it can be listed again.
