### ISSUE TITLE
Permission icons are resized if the permission text runs into two lines

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#4689]
Split from https://github.com/mozilla/addons-frontend/issues/4581#issuecomment-373947303

STR: Whether in Firefox or in Edge, resize the browser window (at least horizontally) such that some permissions now run over two lines.

AR:

Edge:
![edge](https://user-images.githubusercontent.com/8336638/37559242-68be18a0-2a48-11e8-853d-79f510c09581.PNG)
Firefox: (icon should be 24x24 but is deformed)
![20 9px](https://user-images.githubusercontent.com/8336638/37559285-4b562126-2a49-11e8-9791-212fc95cbbb2.PNG)

**Comment by tofumatt** [comment]
Marking as a P4; this is annoying and a papercut but it doesn't especially interfere with usability or the information each permission icon+text is trying to convey. It's just not very pretty 😦

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59 (Win10).

Resizing the browser the icons keep their size at 24x24

![24x24](https://user-images.githubusercontent.com/33448286/38203041-7eac924e-36a6-11e8-90c5-69fc63b31185.png)

![keeps 24x24](https://user-images.githubusercontent.com/33448286/38203058-88bad796-36a6-11e8-8de9-84222c964755.png)
