### ISSUE TITLE
Each rating star should have its own title attribute with the rating number in it

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4692]
### Describe the problem and steps to reproduce it:
1. Go to an add-on detail page (eg https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)
2. Make sure you're signed in so you can leave a review
3. Hover over the rating stars to rate the add-on
4. Note the title is the same across the entire set of stars

### What happened?
The entire enclosing div (https://github.com/mozilla/addons-frontend/blob/master/src/ui/components/Rating/index.js) has the same title attribute ("Click to rate this add-on").

### What did you expect to happen?
Each star has its own `title` attribute like `"Click to rate this add-on 1 out of 5"`.

**Comment by tofumatt** [comment]
Why was this issue closed?

**Comment by ioanarusiczki** [comment]
All rating stars still display the Click to rate this add-on title attribute on AMO dev and AMO stage with FF59 (Win10).

**Comment by caitmuenster** [comment]
Whoa that was an accident! Sorry @tofumatt, @ioanarusiczki, and @bobsilverberg -- definitely did not mean to close this.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59(Win10)
I filed https://github.com/mozilla/addons-frontend/issues/4955 as an improvement of the actual behavior.
