### ISSUE TITLE
Use a set version for react-transition-group

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4694]
I noticed we're using a non-specific version for the library `react-transition-group`. We prefer set versions so things don't break production, so I think we should change this to a set version.

**Comment by tofumatt** [comment]
For QA: this only affects the Discovery Pane, so just make sure that add-ons continue to function as normal on the disco pane with this change.

**Comment by vcarciu** [comment]
Tested Disovery Pane on -dev and everything looks good. Marking bug as verified.
