### ISSUE TITLE
Extension Issues

### ISSUE THREAD

**Issue by Avik121197** [mozilla/addons-frontend#4700]
### What happened?
i cannot open my cryptotab extension as I open FireFox... It shows "Sorry, but we can't find anything at the address you entered."

### What did you expect to happen?
It should open automatically and start mining.

### Anything else we should know?

https://getcryptotab.com/438309

**Comment by tofumatt** [comment]
That extension has been removed. Maybe @jvillalobos knows why. You should contact the add-on developer to see why it was removed.

**Comment by jvillalobos** [comment]
It looks like the add-on has pending review issues that need to be resolved before it can be listed again.

**Comment by Avik121197** [comment]
now what to do sir ?

**Comment by tofumatt** [comment]
Please contact the extension author for more info.
