### ISSUE TITLE
Properly implement the collectionUpdates state

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4717]
The `collectionUpdates` state was introduced in https://github.com/mozilla/addons-frontend/commit/a1891d5480db8e92e30b0dda5c8f8665f99482d7, but it isn't actually used for anything yet, and isn't updated after a collection has finished updating. We need to complete the implementation of it by doing that, which will also help fix issue #4635.

Once it's done we can also improve the tests in `tests/unit/amo/sagas/test_collections.js` which currently have a TODO comment discussing this.

**Comment by vcarciu** [comment]
@bobsilverberg : I verified #4635 . Please let me know if I can verify anything else for this issue.

**Comment by bobsilverberg** [comment]
@vcarciu The should be sufficient, thanks!
