### ISSUE TITLE
Disable Save Collection button if the slug is blank

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4719]
This is a replacement for issue #4650 and will be similar to the resolution in issue #4698. If the collection slug is blank, or a string which is only spaces, the "Save Collection" button should be disabled.

@tsl143 Are you interested in taking this one, as it's very similar to the work you did for #4698?

**Comment by tsl143** [comment]
@bobsilverberg done :)

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF59 (Win10). When only spaces are used or the slug is blank the save collection button is disabled. 
I filed https://github.com/mozilla/addons-frontend/issues/4735 for an issue observed when spaces are typed before typing some text and then save collection is clicked.
