### ISSUE TITLE
Remove validation for Collection name from CollectionManager form

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4720]
The current validation is insufficient, as it allows a name which consists of only blanks. PR #4698 addresses the issue by preventing the form from being submitted with a blank collection name, so we don't really need the validation anymore. As well, https://github.com/mozilla/addons-server/issues/7936 has been opened to address this at the API level.

Rather than fixing the incorrect code, and adding a test for it, we can just remove the validation code, which can be found at https://github.com/mozilla/addons-frontend/blob/9b24540befffde77af3834a044afda27d0724ac3/src/amo/components/CollectionManager/index.js#L109-L115.

**Comment by caitmuenster** [comment]
Mentor: @bobsilverberg 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by biskit1** [comment]
Hello :raised_hand:
Can I work on this as my first bug?

**Comment by caitmuenster** [comment]
Hey @biskit1, go for it! Please feel free to mention @bobsilverberg in a comment if you need any help. :)

**Comment by vcarciu** [comment]
@bobsilverberg : I verified that no blank names can be added when creating a new collection. Is this enough for this bug?

**Comment by bobsilverberg** [comment]
@vcarciu This bug won't result in any changes to the front end. Just making sure the edit form is still working as expected should be sufficient.

**Comment by vcarciu** [comment]
@bobsilverberg : thank you !
