### ISSUE TITLE
PAGE NOT FOUND

### ISSUE THREAD

**Issue by RB-Rutledge** [mozilla/addons-frontend#4728]
### Describe the problem and steps to reproduce it:

I had a tab open up on my browser advertizing a bitcoin mining add on available for FireFox.  After reading through some of the Q&As and Getting Started Guides, I clicked on the icon for get the app.  It was supposed to direct me to https://addons.mozilla.org/en-US/firefox/addon/cryptotab/, but that came up as not found.

### What happened?
Read above
### What did you expect to happen?
Well, I sort of expected something DIFFERENT to happen, even though I wasn't sure what exactly.
### Anything else we should know?

Nah, that's about it.

**Comment by tofumatt** [comment]
The add-on was unlisted because of an issue with its review. You should contact the author from their homepage to get it listed again.
