### ISSUE TITLE
Respect `no-descending-specificity` stylelint rule

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4732]
Right now we ignore the `no-descending-specificity` rule in Stylelint, but that's just because it's a new rule and it's a fair bit to update our CSS to respect it.

The consensus seems to be it's worth implementing the rule, but it should be its own issue.

See the discussion in: https://github.com/mozilla/addons-frontend/pull/4483 for more info.

**Comment by tofumatt** [comment]
Lol, mid-air collision with #4731.

**Comment by vcarciu** [comment]
Can you please add some STRs to this bug or mark it as "qa: not needed" ?
