### ISSUE TITLE
Wrong alignment for "More themes by this user" if view listing is pressed on your submitted theme

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#4744]
Steps to reproduce:
1.Login with an account where you have more themes submitted and approved
2.In developer hub, open one of your submitted themes
3.Press View Listing link for that theme

Expected results:
The themes listed under "More themes by this user" are correctly aligned (6 themes listed , 3 on every row)

Actual results:
Each theme is displayed on one line

NOTES:
Reproducible on Stage and -dev 

Please see video for this issue : 
![lexa](https://user-images.githubusercontent.com/1583842/38372970-c3af0e36-38f8-11e8-8664-fe58a82e91e2.gif)

**Comment by tofumatt** [comment]
This is a pretty weird bug, and I wonder if it happens when the page is fully reloaded as well.

**Comment by AlexandraMoga** [comment]
@tofumatt This bug can be reproduced by refreshing the page on the theme details page, as captured below:

![theme regresh](https://user-images.githubusercontent.com/31961530/39177887-14def068-47b9-11e8-90b4-fe65af238660.gif)

**Comment by tofumatt** [comment]
Ah, I see. So this is an SSR-related bug then.

**Comment by willdurand** [comment]
I don't think there is anything SSR-related because this component loads on the client only.

**Comment by vcarciu** [comment]
Verified as fixed : 
![themeslistview](https://user-images.githubusercontent.com/1583842/42524082-21233cf2-8478-11e8-8b23-f3cd1273b4c4.gif)
