### ISSUE TITLE
Discopane ui tests are failing

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4747]
Starting with https://github.com/mozilla/addons-frontend/commit/3fd1e1acfae57b55171e9cc85bee3fccbd93cc57, the discopane ui tests are failing. See 
https://travis-ci.org/mozilla/addons-frontend/builds/362738197 for the failure related to that commit.

There doesn't seem to be anything in that commit that would trigger a failure.

**Comment by tofumatt** [comment]
I'm going to disable the tests for now as the noise is making it tough to work on PRs, but I'll leave the issue open because it needs to get fixed.
