### ISSUE TITLE
Add badge for add-ons owned by the Mozilla account

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#4760]
We want to highlight Mozilla-developed add-ons on AMO and give users some confirmation that they are official. We've talked before about a larger "verified developer" program, but that has never come together, so this limits the scope to the [Mozilla account](https://addons.mozilla.org/user/mozilla/).

This badge should appear on add-on listing pages and search results. It should say something like "Created by Mozilla", or "Official Firefox Add-on" (final copy TBD). It should only appear if the Mozilla account is a listed owner of the add-on.

**Comment by willdurand** [comment]
@jvillalobos do we still want that?

**Comment by jvillalobos** [comment]
There might still be value in doing this, even having the Recommended badge. This would be a bigger project if we want the badge to also work in Firefox, though.

@atsay, what do you think?

**Comment by atsay** [comment]
Let's backlog this for now--use case doesn't seem strong enough at the moment.

**Comment by willdurand** [comment]
> Let's backlog this for now--use case doesn't seem strong enough at the moment.

Based on that, I am closing this issue. We'll reopen it if needed.
