### ISSUE TITLE
Missing "s" for setting in Control browser proxy settings permission

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4770]
STR:
1. Load AMO dev and check the Control browser proxy settings for https://addons-dev.allizom.org/en-US/firefox/addon/all-of-the-permissions/
2. Observe how  Control browser proxy settings permission is displayed on the add-ons detail page.

Expected result:
Control browser proxy settings is displayed.

Actual results:
"setting" instead of "settings" is displayed.

Notes:
This is reproducible on AMO dev with FF59 (Win10).

**Comment by tofumatt** [comment]
This is a case of a missing "s" in the "Control browser proxy setting" string itself.

All that this needs is for the string to be updated. Mentor @tofumatt.

**Comment by championshuttler** [comment]
Can i work on this as my first contribution

**Comment by tofumatt** [comment]
Sure thing, just submit a pull request when you are ready!

- Matt (Sent from mobile)

**Comment by tsl143** [comment]
@tofumatt #4773 has been merged, can this be closed?

**Comment by tofumatt** [comment]
Ah, shoot, indeed. Looks like the wrong text was used in the PR. 😓

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59 (Win10). 

![settings](https://user-images.githubusercontent.com/33448286/38815929-a8c77dda-419d-11e8-92de-4c2ee6604522.png)
