### ISSUE TITLE
AddonsByAuthorsCard always says "More add-ons by user"

### ISSUE THREAD

**Issue by tofumatt** [mozilla/addons-frontend#4774]
See https://github.com/mozilla/addons-frontend/pull/4756#issuecomment-379751761

Basically we should allow an override to the default header here. I think the defaults make sense but an override would be handy.

**Comment by tsl143** [comment]
@tofumatt , can we have this header text from any existing API?

**Comment by tofumatt** [comment]
No, this is always text created on the front-end, as it's situational.

**Comment by tsl143** [comment]
So what exactly we need to do here?

**Comment by AlexandraMoga** [comment]
I have checked the 'Add-ons by author' cards from the user profile and add-on details pages and here is how they're looking now:

**[1] '_Add-ons_ by author' in the user profile page:**
 
![image](https://user-images.githubusercontent.com/31961530/39753137-67b9ffcc-52c6-11e8-8cef-6db9d49f2de8.png)

**[2] 'More _add-ons_ by author' from add-on details page:**
![image](https://user-images.githubusercontent.com/31961530/39753166-7bcfa0e8-52c6-11e8-8104-6f6a4db32bb6.png)
![image](https://user-images.githubusercontent.com/31961530/39753176-87bf608c-52c6-11e8-928d-335337178404.png)


@rebmullin @bobsilverberg I believe this is what you were trying to achieve here, right?

**Comment by willdurand** [comment]
@AlexandraMoga it is indeed!

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, Win10x64
