### ISSUE TITLE
[suggestion] Put badges below theme name on addon details page

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#4775]
The badge position on theme details page for desktop looks a bit awkward. Can we put it below theme and author name, same as we do on smaller screens. @pwalm @tofumatt 

Current view on desktop
<img width="783" alt="screen shot 2018-04-11 at 11 42 48 am" src="https://user-images.githubusercontent.com/5318732/38599414-19e92104-3d7e-11e8-8259-a8f546b485f6.png">

Suggested view on desktop
<img width="783" alt="screen shot 2018-04-11 at 11 43 57 am" src="https://user-images.githubusercontent.com/5318732/38599435-2c6e899a-3d7e-11e8-9e15-013a99b8ee0c.png">

### Describe the problem and steps to reproduce it:
On desktop, navigate to any theme details page say https://addons-dev.allizom.org/en-US/firefox/addon/st-patrick-cupcakes

### What happened?
Theme badges are on the right

### What did you expect to happen?
Theme badges can be put below theme and author name

**Comment by realslimshanky** [comment]
Added PR #4777 to entertain the changes suggested in this issue just in case it's decided to introduce them to the website.

**Comment by pwalm** [comment]
Move the badge below the author name, but do not bump the "Install Theme" button down further.

**Comment by tsl143** [comment]
Thanks for input @pwalm, and yes, will surely take care of install button.

**Comment by jvillalobos** [comment]
Recommended badges now appear in the expected location.
