### ISSUE TITLE
Implement an EditableCollectionAddon component to support the new Edit collections screen

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4778]
As discussed with @pwalm, when a user edits a collection, the list of add-ons displayed on the right-hand side of the screen will change from a standard AddonsCard to a list of editable add-ons with less information (only name and icon), but with a button to remove the add-on from the collection and also a means of adding notes to the add-on.

This will be similar to what appears on the bottom of the form in the current mockups, for example:

<img width="554" alt="screenshot 2018-04-11 10 41 02" src="https://user-images.githubusercontent.com/142755/38630412-dfafb8f2-3d84-11e8-856a-fa82fd1ca17b.png">

This first step is to simply replace the existing list of add-ons with an editable list. The ability to remove an add-on from a collection and to add notes to an add-on will be implemented in follow up issues.

@pwalm will be providing a mockup of this new screen.

**Comment by bobsilverberg** [comment]
@pwalm provided a mockup for the edit collections screen at issue #4590, which I am copying below:

<img width="1546" alt="screen shot 2018-04-11 at 10 45 27 am" src="https://user-images.githubusercontent.com/6797635/38633766-7eda9ce0-3d75-11e8-90bf-b7903d795c3d.png">

**Comment by bobsilverberg** [comment]
For QA:

With this patch in place when you click on the edit link for a collection the list of add-ons on the right-hand side of the screen should switch to look like the list above. This only implements the display; the comments icon and the "Remove" button don't do anything at this point.

**Comment by smayer97** [comment]
Please consider the following issue:
Title/Name and Description fields for Collection are blank and do not show up in Edit Collection view. https://github.com/mozilla/addons-frontend/issues/4793

The above applies to the old/current Edit Collection page but want to make sure that this is not a problem in the new one either.

**Comment by smayer97** [comment]
BTW the way, this new view is missing the Date Added column, like in the old/current view. Please consider adding this too.

**Comment by smayer97** [comment]
I hope this new Edit Collection window will allow the option of listing more than 25 add-ons at a time, as other add-on lists are currently limited to.

**Comment by smayer97** [comment]
Just saw this: https://github.com/mozilla/addons-frontend/pull/4783

Should my posts above be move to that thread?

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev, with FF59, Win10x64 and Android 7.0

- a list of all add-ons available in the collection is opened on the right side when the user hits Edit collection
- collection name and description are present when selecting edit collection
- for collections with a large number of add-ons, loading time is too long - filed #4812
- collection names with unbroken strings are breaking the from layout - filed #4813

![image](https://user-images.githubusercontent.com/31961530/38817903-0f869e3a-41a2-11e8-994a-90cabde2314f.png)
