### ISSUE TITLE
Average star ratings should be rounded to the nearest half star

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#4784]
Split from #4186 

The problem is that we're only rounding down, rather than rounding to the nearest half-star. So, an average rating of 3.1 should be 3 stars, and an average rating of 3.3 should be 3.5 stars (not 3 stars, as we currently show).

This has been brought up by a couple of developers before, and it is a big disadvantage for those with average ratings close to the top of the half-rating.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. You only mention ratings under 3.5. I assume from this that you also want to round up to full stars? I.e., a rating of 3.9 would render as 4 stars? Where exactly is this cutoff? 3.25 and 3.75? And if so, do we round .25 up or down, and do we round .75 up or down?

**Comment by bobsilverberg** [comment]
For QA:

A rating of 3.249 should round down, and therefore the star for 4 should be empty.
A rating of 3.25 should round up to the half-star, and therefore the star for 4 should show a half-star.
A rating of 3.749 should round down to the half-star, and therefore the star for 4 should show a half-star.
A rating of 3.75 should round up, and therefore the star for 4 should show a full star.

**Comment by AlexandraMoga** [comment]
Verified on AMO dev with FF59, Win10x64

A few add-on samples were selected and were rated with the given boundary values. The average rating displayed in the frontend was matching the expected result.

Here are two examples, but note that these values might change if more ratings will be added:
- https://addons-dev.allizom.org/en-US/firefox/addon/webext-simple/?src=search - rated 3.75 - rounded to 4 stars
- https://addons-dev.allizom.org/en-US/firefox/addon/blue-jeans-w/?src=search - rated 3.749, rounded to 3.5 stars
