### ISSUE TITLE
Collection content is missing Comments and Date Added section for each add-on

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4788]
### Describe the problem and steps to reproduce it:

When viewing the content of a Collection, the Comment text added to the collection and the date the add-on was added to the collection do not show up.

### What happened?
They are only visible when editing the collection but no one else can see them.

### What did you expect to happen?
That comments and the date an add-on was added be displayed for all users.

**Comment by bobsilverberg** [comment]
The comments are being added in issue #3890, and I do not believe we have plans to include the date the add-on was added to the collection. @jvillalobos can you please confirm that second point?

**Comment by jvillalobos** [comment]
Yeah, I don't think we need to expose the date added for individual collection items.
