### ISSUE TITLE
Add Sort By feature to content view of Add-on Collection

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4790]
### Describe the problem and steps to reproduce it:
Would like to see sort feature added to view of contents of add-on collection view.

### What happened?
Cannot sort contents of Collection.

### What did you expect to happen?
Ability to sort by Name, # Users, Date Add-On Added to collection.

### Anything else we should know?

Would make browsing content of collection more useful.

**Comment by smayer97** [comment]
Related:
Collection content is missing Comments and Date Added section for each add-on:
https://github.com/mozilla/addons-frontend/issues/4788

**Comment by jvillalobos** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/3991
