### ISSUE TITLE
Add option to display more or all add-ons on the content view of collections

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4791]
### Describe the problem and steps to reproduce it:

Viewing the content of a collection is limited to 25 per page. 

### What happened?
as above

### What did you expect to happen?
Have an option to be able to view more add-ons at one time...
Ideally option to view ALL. Another option to set the # to display.
Would also be nice to save this setting in user profile.

### Anything else we should know?

Would be very helpful when browsing the content of larger collections.

Would work nicely with the following related request:
Add Sort By feature to content view of Add-on Collection: https://github.com/mozilla/addons-frontend/issues/4790

**Comment by jvillalobos** [comment]
We won't be optimizing the collections feature for very large collections. This feature wouldn't be useful for the majority of users, so maintaining it isn't worth the cost.

**Comment by smayer97** [comment]
Oh Well. That's too bad.

**Comment by smayer97** [comment]
Revisiting this...if possible...

What about simply list ALL add-ons in a collection, i.e. no pagination, just as is done for list complete list of collections on 'My Collections' page? BTW, response for that page is excellent, so performance or optimization should not be an issue... Just list them all.
