### ISSUE TITLE
Date Added column missing from new Edit Collection window

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4794]
### Describe the problem and steps to reproduce it:
The new view for the Edit Collection window (not yet deployed) is missing the Date Added column, like in the old/current view. Please consider adding this too. 

### What did you expect to happen?
To see the Date Added column like in the old/current Edit Collection view.

### Anything else we should know?

See Implement an EditableCollectionAddon component to support the new Edit collections screen:
https://github.com/mozilla/addons-frontend/issues/4778

**Comment by smayer97** [comment]
Also related:
Add an add-on to a collection from the edit screen 
https://github.com/mozilla/addons-frontend/issues/4590

**Comment by jvillalobos** [comment]
What is the rationale for having this column in the edit screen?

**Comment by smayer97** [comment]
For working with larger collections, easier to find an add-on.
Also keeps the view consistent when going from the list of addons in the view of the Collection to the Edit window.


BUT this is already part of and implied by 'Sort add-ons in a collection':
https://github.com/mozilla/addons-frontend/issues/3991

So if it is, and this detail is not lost in https://github.com/mozilla/addons-frontend/issues/3991 then this issue is a duplicate also...Otherwise, this request should be kept open.

**Comment by pwalm** [comment]
We're going to leave "date added" info from this view for now. We will provide the option to sort by date though.
