### ISSUE TITLE
Add Sort By feature in the new Edit Collection window

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4795]
### Describe the problem and steps to reproduce it:

Would be helpful to have the ability to sort the list of add-ons in the new Edit Collection window.
(see Implement an EditableCollectionAddon component to support the new Edit collections screen https://github.com/mozilla/addons-frontend/issues/4778 )

Sort by clicking column title. Sort by Name, Date Added.

### What happened?
Cannot sort list of add-ons in the the Edit Collection window. Especially useful for larger collections.

### What did you expect to happen?
Ability to click the column title to sort list of add-ons.

### Anything else we should know?

See related:
Date Added column missing from new Edit Collection window: 
https://github.com/mozilla/addons-frontend/issues/4794

**Comment by smayer97** [comment]
Also related:
Add an add-on to a collection from the edit screen 
https://github.com/mozilla/addons-frontend/issues/4590

**Comment by jvillalobos** [comment]
Probably a duplicate of https://github.com/mozilla/addons-frontend/issues/3991. Reopen if it isn't addressed with that issue.

**Comment by smayer97** [comment]
For working with larger collections, easier to find an add-on. 
Also keeps the view consistent when going from the list of addons in the view of the Collection to the Edit window.

**Comment by smayer97** [comment]
Yes. It is a duplicate. Thx.

**Comment by smayer97** [comment]
Sorry...NOT a duplicate... https://github.com/mozilla/addons-frontend/issues/3991 is about sorting the Add-on Collection main view. This request is about sorting the Edit Collection view.

**Comment by smayer97** [comment]
As noted, this is not a duplicate request. Can this be re-opened?

**Comment by smayer97** [comment]
Can this be re-opened please since this is not a duplicate request?

**Comment by jvillalobos** [comment]
I see the sort options in the Edit mode and they appear to work. What's missing?

**Comment by smayer97** [comment]
Some time ago, the sort only worked in the collection list but not while in edit mode. Not sure when this changed but I see now that it works in the edit mode too. 
So this is done. Sorry about that. Thanks kindly for following up.
