### ISSUE TITLE
404 Page not found when refreshing view profile page after the username is updated

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4797]
STR:
1. Load AMO dev and go to View Profile
2. Open a new tab load AMO dev and go to Edit Profile
3. Edit the username and save changes
4. Go back to the View profile from the first tab and refresh page 
5. Observe page

Expected result:
User info card is displayed.

Actual result:
404 Page not found.

Notes:
This issue is reproducible on AMO dev with FF59(Win10). 
I could not reproduce it when editing the display name.

![page not found](https://user-images.githubusercontent.com/33448286/38742125-5f687730-3f44-11e8-964c-07a6ee70f00f.gif)

**Comment by AlexandraMoga** [comment]
This issue seems to be related to #4421

**Comment by bobsilverberg** [comment]
As #4421 is a P4 and is very similar, I'm marking this as a P4 as well.

**Comment by willdurand** [comment]
I think this is fixed by https://github.com/mozilla/addons-frontend/pull/4922.

**Comment by ioanarusiczki** [comment]
I can still reproduce this issue on AMO dev with FF60 (Win10) 
I cannot reproduce the other similar issue https://github.com/mozilla/addons-frontend/issues/4281

![reproducible](https://user-images.githubusercontent.com/33448286/40059564-098a16c0-585d-11e8-9566-a2a8674f37f9.gif)

**Comment by willdurand** [comment]
@ioanarusiczki mmh I am not sure to understand, if you change your username, the previous profile URL is invalid but that's normal because the username is part of the URL.

**Comment by ioanarusiczki** [comment]
@willdurand Hmm then it was invalid all along. Closing it!
