### ISSUE TITLE
The cryptotab extension could not be found

### ISSUE THREAD

**Issue by Kristofp** [mozilla/addons-frontend#4801]
### What happened?
The cryptotab extension could not be found
https://addons.mozilla.org/firefox/addon/cryptotab/
### What did you expect to happen?
I expected to be able to download the extension

**Comment by championshuttler** [comment]
Hi @Kristofp, Thanks for raising issue. 
Are you looking for this add-on?
https://addons.mozilla.org/en-US/firefox/addon/crypto-tab/

**Comment by Kristofp** [comment]
No that's a different extension

**Comment by Kristofp** [comment]
I mean the one you find if you go to this page with Firefox there's a button to install the extension however it does not seem to exist.
[https://getcryptotab.com](https://getcryptotab.com/409337)

**Comment by jvillalobos** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/4751
