### ISSUE TITLE
More extensions by anonymous…

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#4806]
At https://addons.mozilla.org/addon/session-boss/ https://addons.mozilla.org/addon/clear-site-cookies/ and https://addons.mozilla.org/addon/tip-tab/ – all three of which are by _William Wng_, there's what seems to be a user ID (not his name): 

> More extensions by anonymous-ebfc53d39e40ce99692ab6d6be09d2bf

**Comment by bobsilverberg** [comment]
This looks like a problem with the newly introduced `AddonsByAuthorsCard`. I'll look into it.

**Comment by bobsilverberg** [comment]
I see that this in fact  duplicates #4796, so I will close in in favour of that.
