### ISSUE TITLE
Paginate extensions and themes views on user profile so they are all accessible

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4809]
Prerequisites:
Make sure that you have an account with more than 3 extensions and 6 themes submitted and approved.

STR:
1. Load AMO dev and go to your User Profile page.
2. Observe the displayed extensions and themes. 
3. Refresh page multiple times. 
4. Observe the displayed extensions and themes.
5. Check for a See more by Username link.

Expected results:
Different extensions are displayed after refreshing page or a See more link will show a complete list of extensions/themes.

Actual result:
The same extensions and themes are displayed. See more link is not available.

Notes:
This issue is reproducible on AMO dev with FF59 (Win10). 

![extensionsthemes](https://user-images.githubusercontent.com/33448286/38810613-fb14b20a-418f-11e8-978d-61b3be273ca3.png)

**Comment by bobsilverberg** [comment]
I'm not sure about whether we should randomize the extensions displayed, like we do for the Hero elements on the home page, but I agree we should at least provide a link somewhere to see all of the extensions/themes for an author.

@jvillalobos what do you think this needs? @pwalm Where do you think the link should go?

**Comment by jvillalobos** [comment]
I would prefer that we do two things:

1) We show more add-ons by default in the developer page. At least 10 of each kind.
2) Have pagination on those views, so it's possible to look at the next page of extensions or themes without having to go to a different page. This means the default view should not be randomized. Sorting by users is what makes most sense to me.

**Comment by bobsilverberg** [comment]
@jvillalobos or @ioanarusiczki would one of you mind filing two separate issues for the suggestions at https://github.com/mozilla/addons-frontend/issues/4809#issuecomment-381748215? I suppose we could morph this issue into one of them, as it sounds like we are no longer requesting a "See more" link.

**Comment by ioanarusiczki** [comment]
@jvillalobos Sounds like an elegant approach 👍

**Comment by willdurand** [comment]
Hi @pwalm, would you have an input on this? We don't have paginated components yet, only pagination at a "page" level (e.g., search results). When trying to reuse the pagination below each card, it looks like this:

![screenshot-2018-5-28 user profile for add-ons for firefox](https://user-images.githubusercontent.com/217628/40609775-a31d6058-6267-11e8-9384-253f5b78d5f6.png)

I don't think it looks nice **but** I don't think a lot of developers have more than 10 extensions, but a few users have lots of themes (and likely no extensions)

**Comment by bobsilverberg** [comment]
I agree that that looks bad. At the very least I would think that the pagination links should appear as if they're inside the cards for the themes/extensions. As it is above it's difficult to know that each paginator actually belongs to the card above it.

I guess this is also going to cause some implementation complexities for us, because right now we pass the page on the URL, so any given screen can only be on a single page, but with this new model a user could, theoretically, be on page 2 of extensions and page 4 of themes (for example).

**Comment by willdurand** [comment]
I stumbled upon mock-ups that have a different pagination component, which made me think about #3100 again:

<img width="913" alt="screen shot 2018-05-28 at 15 58 00" src="https://user-images.githubusercontent.com/217628/40620237-fb3102b8-628f-11e8-92ce-b863ff0b8bd1.png">

This new UI for the pagination component look better for our use case here.

> I guess this is also going to cause some implementation complexities for us, because right now we pass the page on the URL, so any given screen can only be on a single page, but with this new model a user could, theoretically, be on page 2 of extensions and page 4 of themes (for example).

I was about to implement 2 different `page` query parameters. I believe the main issue is the use of the `AddonsByAuthorCard`, which was not designed for fetching a lot of data (not in a dynamic fashion at least).

**Comment by pwalm** [comment]
So the pagination in use currently is basically the scaled-up mobile version. This mock-up is for the desktop.

**Comment by willdurand** [comment]
I am still wondering what the best approach is because the `AddonsByAuthorsCard` component (+ its logic) is not designed for pagination. Maybe it would be faster to build another component, or maybe updating the existing `AddonsByAuthorsCard` to support pagination would be easier.

**Comment by willdurand** [comment]
Ok, so I think supporting pagination in `AddonsByAuthorsCard` is easier and makes sense, here is a WIP:

![](https://screenshots.firefox.com/zp4vHvhEsX1vHYAX/localhost)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10 and Android 8.0)

![paginationnew](https://user-images.githubusercontent.com/33448286/41920617-c0fc3a4a-7969-11e8-8221-20c9630656fd.gif)
