### ISSUE TITLE
Static themes are not displayed on the new User info card 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4810]
Prerequisites:
Make sure you have an account with static themes submitted and approved

STR:
1. Load AMO dev and click on View Profile.
2. Observe the "More themes by" section.

Expected result:
Static themes are displayed in the "More themes" section.

Actual result:
Only lightweight themes are displayed.

Notes: 
This issue is reproducible on AMO dev with FF59 (Win10).

![static themes](https://user-images.githubusercontent.com/33448286/38811609-a86dc1a6-4192-11e8-9178-baccbda97867.gif)

**Comment by bobsilverberg** [comment]
There is some discussion about this at https://github.com/mozilla/addons-frontend/issues/4280#issuecomment-381644228. It sounds like we do want to add static themes to this page, but it's not clear whether they should be added to the existing "More themes by" card or whether they should have their own card.

@jvillalobos Do you have thoughts on this?

**Comment by jvillalobos** [comment]
We shouldn't make a distinction between static and lightweight themes for users, so it should be on the same card.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10&Android 8.0)
![lightweightandstaticthemes](https://user-images.githubusercontent.com/33448286/41780043-4758d570-763c-11e8-8ae0-739cb5214873.png)
