### ISSUE TITLE
The "More add-ons by..." card does not appear on the add-on details page when the current add-on has more than one author

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4818]
STR:

1. Visit the details page for an extension with more than one author, e.g., https://addons-dev.allizom.org/en-US/firefox/addon/easy-passwords/.

Expected:

A card showing "More extensions by these developers" appears towards the bottom of the page (below the Permissions card).

Actual:

The "More extensions by these developers" does not appear on the page.

**Comment by tofumatt** [comment]
I would think that doing that would prevent future improvements but I suppose for now it would work. I guess the main use case is covered by byAuthorNamesAndAddonType so actually yeah that might well be fine. I’d say give it a go and we could always revert the code.

**Comment by bobsilverberg** [comment]
After going down that rabbit hold for awhile I realized that there's probably a much simpler fix to this, which I then discovered. So while I'm still not a big fan of having unused code in the codebase, I did not remove anything for this issue, and just came up with a quick (but not dirty) fix in #4828.
