### ISSUE TITLE
Mozilla

### ISSUE THREAD

**Issue by isdaan** [mozilla/addons-frontend#4822]
### Describe the problem and steps to reproduce it:
<!I clicked a link on Firefox browser to add CryptoTab>

###I received error : Sorry, but we can't find anything at the address you entered.

**Comment by EnTeQuAk** [comment]
This bug tracker is for the addons.mozilla.org site directly. If you have a problem with the CryptoTab Add-on please contact the author directly: https://cryptotab.net/en/
