### ISSUE TITLE
Edited fields are reset when adding a new add-on to a collection in the edit collection form

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4824]
Follow up for #4590 

STR:

1. Log in to AMO-dev and select a previously created collection to view its details page
2. Click on Edit collection
3. Edit the name, description, slug fileds
4. Search for a new add-on to add to your collection and select one of the returned search suggestions
5. Observe the fields edited at point 3

Actual result:
The edited fields are reset to their previous values when a new add-on is added to the collection

Expected results:
The new values added in the edit fields are preserved when a new add-on is added to the collection

Notes;
- reproduced on AMO-dev with FF59, Win10x64 and Android 7.0
![edit collection refr](https://user-images.githubusercontent.com/31961530/38864607-ed06f24a-4243-11e8-89be-e0cf804fd623.gif)

**Comment by daiict218** [comment]
Hi @bobsilverberg, I am looking for contributing to open source. I can take this up if you can give me a KT of this

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF60, Win10x64 and Android 7.0

![edit coll](https://user-images.githubusercontent.com/31961530/40119602-cd81136c-5925-11e8-9b72-229c4f9a64eb.gif)
