### ISSUE TITLE
Cannot add  new extensions or themes into a collection with an admin account 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4829]
Prerequisites:
Must have at least one admin account

STR:
1. Load AMO dev and log in with an account without admin rights, search a collection, open it's edit page.
2. Log out then click the Log in to edit this collection but this time use the admin credentials.
3. Enter a term in the search field and try to add it to the collection created by the other user.
4. Observe behavior.

Expected result:
The extension/theme can be added to the list on the right side of the screen.

Actual result:
Red message "Not found" is displayed. The searched and selected item is not added to the list.

Notes:
This issue is not reproducible with the name, description or editing the collection URL by an admin.
This issue is reproducible on AMO dev with FF59 (Win10). 

![cannot add](https://user-images.githubusercontent.com/33448286/38872256-7944854e-425b-11e8-96a4-307f333a5d50.gif)

**Comment by bobsilverberg** [comment]
An administrator should not be able to edit a collection in any way, including adding new add-ons, so this is expected.
