### ISSUE TITLE
Display more extensions and themes in user profile page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#4832]
Branched off from #4809.

We should show at least 10 extensions and 10 themes in the user profile page, so it doesn't require too much clicking to cycle through all add-ons for most developers (some theme designers have thousands of those, but we're not optimizing for that case).

It looks like 4 lines of themes in the original mock would show 12 themes, which is sufficient IMO.

**Comment by tsl143** [comment]
@jvillalobos so is the scope of this bug is just increasing the number of addons to 10 and themes to 12?

**Comment by jvillalobos** [comment]
Yes. This is for the new user profile page, which hasn't shipped on prod yet.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64 and Android 7.0

![screen shot 2018-05-21 at 11 59 03-fullpage](https://user-images.githubusercontent.com/31961530/40299353-a7ac5fe4-5cee-11e8-8bbb-0de6d799d406.png)
