### ISSUE TITLE
Use pagination for the list of add-ons that are currently in a collection in edit mode

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4834]
Tracker: #4835
Depends on #4833.

This covers changing the behaviour of the collection edit screen so that when an add-on is added to a collection we only refresh the list of add-ons in the collection, and do not refresh the collection itself.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev, with FF60, Win10x64 and Android 7.0
- edit collection page is now showing paginated lists of max. 25 addons
- page navigation is working
- loading time for large collections is improved

I've logged #5022 which could be a regression, but I can't say for sure as the previous behavior can no longer be tested

![coll pagin](https://user-images.githubusercontent.com/31961530/40118695-4c98b5b8-5923-11e8-8d18-5aaab6102031.gif)
