### ISSUE TITLE
26 April Homepage programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4838]
For the **26 April** push, please update homepage content the programming as outlined [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg @diox

**Comment by ioanarusiczki** [comment]
It is verified on AMO Dev with FF59(Win10& Android 8.0).
The full content will be verified in production.

**Comment by vcarciu** [comment]
Verified in prod
