### ISSUE TITLE
Layout breaks down when narrower than 680px

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#484]
We should be setting the width to `680px` instead of setting a `max-width`. The add-on rows might need to update too.

<img width="597" alt="screenshot 2016-05-31 16 32 06" src="https://cloud.githubusercontent.com/assets/211578/15691265/4aacb100-274d-11e6-82ad-fc32360556ae.png">

**Comment by muffinresearch** [comment]
Well we should probably just implement the mobile changes in #324

**Comment by mstriemer** [comment]
This is a really small change, I'd rather not depend on getting the mobile version setup.

**Comment by muffinresearch** [comment]
You could have fixed it by now then :)
