### ISSUE TITLE
Possible improvements for add to collection feature

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4842]
Follow up for #4590 

STR:
1. Log in to AMO and select  a collection that has a large number of add-ons ( see https://addons-dev.allizom.org/en-US/firefox/collections/AlexandraMoga1/friday-afternoon-100-andro/)
2. Click on Edit collection
3. Use the search feature to add a new add-on in this collection

Expected results:
1. There should be a confirmation message that the add-on was successfully added to the collection
2. Before saving the collection, the new added add-on could be highlighted in some way to make it easier for the user to identify it's position in the list. This would be helpful when the collection has a large number of add-ons
3. A new  add-on should not be automatically saved in the collection when selected. For example, if a user selects by mistake an add-on that he didn't really want to choose for his collection, he would be tempted to use the 'Cancel' button to correct his action. However, with the current functionality, the add-on is saved already so the only choice the user has is to edit the collection again, search for the misplaced add-on and remove it. The new add-ons should be saved only when 'Save collection' button is selected.
This point contradicts a bit what was suggested by **pwalm:** in [#4590 comment](https://github.com/mozilla/addons-frontend/issues/4590#issuecomment-380664085)

Notes:
- Cc @pwalm , @bobsilverberg to hear your opinions with regards to the points mentioned above
- if any of these suggestions can be implemented, I can open separate issues for better tracking

**Comment by bobsilverberg** [comment]
1. Sounds good to me. @pwalm could you suggest where that message should appear? I'm thinking maybe above the edit form, the same place that error messages currently appear.
2. This also sounds like a good idea, again, not sure exactly how it should look.
3. I'm not against this approach, and it would actually improve performance, because we wouldn't have to re-fetch the collection add-ons each time an add-on was added - we could just add its entry to the top of the list on the right hand side of the screen until it is saved. This is how the current (old) site works (I believe), but does contradict https://github.com/mozilla/addons-frontend/issues/4590#issuecomment-380664085 as you mention. It also means a user has to *remember* to save the collection after adding add-ons, instead of the system taking care of that for them. I'm interested to hear what @pwalm has to say about this.

**Comment by smayer97** [comment]
May I suggest, along the current line of discussion that if the concern is about the user forgetting to save the collection before moving away from that page, there are ways to put up a dialog when there are changes to a page that are not saved. I do not know how hard that would be but it would address the concern.

**Comment by pwalm** [comment]
@bobsilverberg Implement #2 if it's not too heavy of a lift, no to the rest.

**Comment by decembre** [comment]
Should be great to show in which collection an addon is yet adde, before we add it to  a collection:
In short the add to colledtion feature of the desktop design!
Why you don't keep it ?

**Comment by smayer97** [comment]
I think this is in reference to the Add To Collection from WITHIN a collection and not from a specific Add-on page, where the Add To Collection menu is used.

That said, I too would like to see the better design that AMO used to have as the Add To Collection menu, as illustrated here:
https://github.com/mozilla/addons-frontend/issues/4331#issuecomment-377615994

It is a simple looking and intuitive interface, with easy Add and Remove functionality with simple feedback to the user as to which Collection an add-on already exists in or not, and with direct access to that collection.

**Comment by bobsilverberg** [comment]
I think this can be closed now, as all of the suggestions are either being addressed by separate issues or will not be addressed. Specifically:

> 1. There should be a confirmation message that the add-on was successfully added to the collection

This is being addressed via issue #4979.
 
> 2. Before saving the collection, the new added add-on could be highlighted in some way to make it easier for the user to identify it's position in the list. This would be helpful when the collection has a large number of add-ons.

We will not be doing this.

> 3. A new  add-on should not be automatically saved in the collection when selected. For example, if a user selects by mistake an add-on that he didn't really want to choose for his collection, he would be tempted to use the 'Cancel' button to correct his action. However, with the current functionality, the add-on is saved already so the only choice the user has is to edit the collection again, search for the misplaced add-on and remove it. The new add-ons should be saved only when 'Save collection' button is selected.

We will also not be changing this. A user who adds an add-on by mistake can simply click the remove button (which doesn't work yet, but will work before shipping the feature).

**Comment by smayer97** [comment]
I think that one of the issues is still not being addressed, as mentioned by decembre here
https://github.com/mozilla/addons-frontend/issues/4842#issuecomment-385631110

and illustrated in https://github.com/mozilla/addons-frontend/issues/4331#issuecomment-377615994

yet this capability is SO IMPORTANT for those working with collections.
