### ISSUE TITLE
Possible improvement for the create a collection form

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4843]
Follow up for #4003 

STR:

1. Log in to AMO-dev and follow [this link](http://addons-dev.allizom.org/en-US/firefox/collections/add/) to access the create collection form
2. Observe the page layout

Actual result:
The page has a lot of unused space, which makes the form a bit bland 

Expected result:
There could be a placeholder on the right side of the page to mark the fact that the add-ons which are going to be added to the new collection will be placed there. This could make the form a bit nicer to look at.

Notes:
- Cc @pwalm and @bobsilverberg, could this be feasible? 
- reproduced on AMO-dev, FF59, Win10x64

![image](https://user-images.githubusercontent.com/31961530/38916342-b03f0a80-42ef-11e8-9862-942b12fb4045.png)

**Comment by pwalm** [comment]
We will create a cold-start for this page.

**Comment by bobsilverberg** [comment]
Thanks @pwalm. Will you be providing the text to display on the right-hand side?

**Comment by bobsilverberg** [comment]
For now, let's just add text that says "Please save your collection and then you can add add-ons to it". @pwalm will let us know exactly what to put on the screen.

**Comment by pwalm** [comment]
Yep, got this on my to-do list, need Meridel to return from vacation for copy guidance.

**Comment by willdurand** [comment]
@rebmullin is this issue fixed now that #4876 has been merged? If so, I suggest you to close the issue (and to make sure you're assigned to it + a milestone is set).

**Comment by MeridelW** [comment]
I'm not able to see how this actually behaves using [the link](https://addons-dev.allizom.org/en-US/firefox/collections/add/). **Should I be able to?**

It's my understanding, based on Bob's comment above, that first the user must create and save the collection and THEN the user adds extensions/themes to it. Is that right? If so, I think the current lay-out may need adjustment:
-In particular, it seems like the "Save Collection" button should appear above the search-and-add function. 
-Is is possible to make this more dynamic? See my suggestions below:

1. When the user is creating the collection, before they have added anything to it, we would have the following copy appear in the grey space:

"First, create and save your collection. After that, you can add extensions and themes."

2. Once the user hits Save, the following copy would appear (I am not sure of its placement visually):

"Add extensions and themes to your collection."

Philip - we may need to huddle up on this so I understand what's feasible!

**Comment by bobsilverberg** [comment]
@MeridelW We're going to track this via issue #4918 instead of this, sorry for the confusion. I will copy your comment above into that issue.

**Comment by rebmullin** [comment]
@willdurand  - this is partly fixed but given that there is a new issue - #4918 - to track remaining concerns/questions, I will close this.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF59, Win10x64 and Android 7.0 for the placeholder text part.
I'm going to look for further  improvements suggested in #4918 

![image](https://user-images.githubusercontent.com/31961530/39744686-c72b6644-52ad-11e8-8d17-ebbbf3d00c0c.png)
![image](https://user-images.githubusercontent.com/31961530/39744703-d429ec44-52ad-11e8-8763-2deb64025554.png)
