### ISSUE TITLE
The "unavailable for your FF version/platform" banner displays the Firefox logo icon instead of an exclamation mark

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4851]
STR:

1. Access AMO and visit the listing page of an add-on that is incompatible with your FF version or platform (see https://addons.allizom.org/en-US/firefox/addon/csp-warning-22-02/)
2. Observe the red notification banner displayed on the add-on details card

Actual result:
The banner displays a Firefox logo icon instead of an exclamation mark **"!"**

Expected result:
The message banner should be displaying the exclamation mark **"!"** icon

Notes:
- most likely introduced by #4749, which, from my understanding, was intended only for the "download Firefox" message
- reproduced on all AMO servers, with FF59, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/38985402-e885a0c4-43d1-11e8-929a-64e1829e3c51.png)

![image](https://user-images.githubusercontent.com/31961530/38985408-f009156a-43d1-11e8-91d1-a574b77a2ed8.png)

![image](https://user-images.githubusercontent.com/31961530/38985431-fdf16d08-43d1-11e8-827f-e1e5c7aed52f.png)

**Comment by bobsilverberg** [comment]
If this really is a bug it's probably a P2. @pwalm can you confirm that this should have the exclamation point icon instead of the Firefox icon?

**Comment by AlexandraMoga** [comment]
See #4175 for some background (when photon notifications were implemented)

**Comment by bobsilverberg** [comment]
That seems pretty definitive, thanks @AlexandraMoga.

**Comment by pwalm** [comment]
Yep, that's a bug. Should be the exclamation mark @AlexandraMoga mentioned.

**Comment by bobsilverberg** [comment]
Fixed via #4853

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO stage with FF59, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/39516754-8a746080-4e06-11e8-9d63-68d64d16f0c0.png)
![image](https://user-images.githubusercontent.com/31961530/39516765-9093b84e-4e06-11e8-8bd7-8047a3cec63b.png)
![image](https://user-images.githubusercontent.com/31961530/39516772-9892dbf6-4e06-11e8-8aa2-424b9e5bba2f.png)
