### ISSUE TITLE
Missing extension Apollo Client Devtools

### ISSUE THREAD

**Issue by HansCronau** [mozilla/addons-frontend#4861]
### Describe the problem and steps to reproduce it:
I decided to install the Apollo Client Devtools for Firefox while on this page: https://github.com/apollographql/apollo-client-devtools
I clicked the link leading to https://addons.mozilla.org/en-US/firefox/addon/apollo-developer-tools/ and found nothing there.

### What happened?
I did not see a page where I could install the Apollo Client Devtools.

### What did you expect to happen?
I expected to see a page where I could install the Apollo Client Devtools with a single click.

### Anything else we should know?
Nope.

**Comment by wagnerand** [comment]
This add-on is currently not available. Please contact the developer of the add-on for more details.
