### ISSUE TITLE
Implement API, saga and reducer code to interact with TAAR Lite service via addons-server

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4867]
Tracker: #4865

- [ ] Update API code to call the TAAR Lite endpoint, which will be [provided by addons-server](https://github.com/mozilla/addons-server/issues/8118).
- [ ] Update saga code to dispatch the API request and load the results into state.
- [ ] Update reducer code to introduce actions for retrieving and loading TAAR Lite results.

**Comment by bobsilverberg** [comment]
For QA: 

There's nothing specific to test for this, as none of the code implemented here is currently used in the site,  but a quick smoke test to make sure this doesn't break anything would be worthwhile.

**Comment by ioanarusiczki** [comment]
Release testing was performed[ here](https://testrail.stage.mozaws.net/index.php?/runs/overview/19)
I'm marking this verified fixed on AMO stage with FF60 (Win10&Android 7.0)
