### ISSUE TITLE
What needs to happen re: compatibility?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#487]
There's no UX for what should happen if an Add-on is incompatible with the version of Firefox viewing the page on the UX docs for the disco pane: https://addons.readthedocs.io/en/latest/ux/disco-pane.html

The initial release of this will be only for a specific version of Firefox (48) and newer. However at some point we might have old versions of FF looking at the page where the compatibility has moved on and those older version might not be able to install the addons in about:addons. 

Assuming that the issue here will eventually be a problem. What should we show for an incompatible addon?

**Comment by pwalm** [comment]
Can we just not show the add-on in question? Seems to be the simplest way. Greyed out things suck, as do alerts/banners/etc.

**Comment by muffinresearch** [comment]
> Can we just not show the add-on in question? Seems to be the simplest way. Greyed out things suck, as do alerts/banners/etc.

What if that meant all the addons were removed?

**Comment by andymckay** [comment]
We will need to consider how the UX and the buttons deal with incompatible add-ons when we do the new mobile pages, so this supports: mozilla/addons#151

**Comment by muffinresearch** [comment]
This is happening for AMO elsewhere.
