### ISSUE TITLE
Changing non-Firefox install banner on AMO to button

### ISSUE THREAD

**Issue by shell1** [mozilla/addons-frontend#4872]
### Describe the problem and steps to reproduce it:
Changing UX seen when looking at adding an add-on from a browser other than firefox (the "non-fx add-ons install") from a banner to a button.  Based on research and data this year, that should result in 3-5 more Firefox downloads every week.  

### What happened?
Before our time, the OnBoarding team did a study [1] to see if there was a way to improve clicks and installs from that location (coming to AMO from a non-Firefox browser).  There had been a banner originally - but with a series of test they found that the right combo of size and button format increased clicks nearly 10 times.

That button on AMO, which drove ~1.1M firefox downloads has performed significantly worse since the change in mid-January to a banner.  Prior research into the UX was unknown to us when the UX refresh was taking place.  

[1] https://mana.mozilla.org/wiki/display/FIREFOX/AMO+Optimization+for+Non-Firefox+Users+Landing+on+Add-on+Pages

### What did you expect to happen?
We'd expect the Fx installs to go back to where they were before the mid-January change.

Data is here [2] filters: source ="addons.mozilla.org, "campaign=non-fx-button, ad content=install add-on button, browser=NOT firefox, timespan=Nov 10-present 

[2] https://datastudio.google.com/org/Ra9O2QIYT8We-1pOmnS_6w/reporting/1kUrSfYdDAWPp7p6GcB2Qcfo-QdEFqdS_/page/QsnK

### Anything else we should know?
@atsay is the PM for a project to improve the whole install flow that is launched from that button.   @pwalm and Meridel will be engaged in case there are potential UX/Copy tweaks (if we need to change the notification when the flow is fixed).  Any UX would be very close to the button (since that is what testing and data say works, won't happen until August-October, will likely be copy work, so we shouldn't give up thousands of installs a week to delay the change until then.

Adding @jvillalobos and @muffinresearch @deadsquid to discuss any questions of priority - since I'm just filing the issue.

<img width="829" alt="screen shot 2018-04-05 at 2 11 34 pm" src="https://user-images.githubusercontent.com/8192232/39315741-4c49f2cc-492c-11e8-8f75-bc760eebf3cc.png">
<img width="789" alt="screen shot 2018-04-04 at 6 33 58 am" src="https://user-images.githubusercontent.com/8192232/39315742-4c6c67d0-492c-11e8-9e33-a40d4df2d7a3.png">

**Comment by pwalm** [comment]
UX guidance: Remove the message banner, replicate the button shown above on new AMO.

**Comment by shell1** [comment]
sorry - reviewing data scale it is 4-5K fewer installs a week, not per day.

**Comment by pwalm** [comment]
Mildly better, still not great 👎🏻

**Comment by muffinresearch** [comment]
@jvillalobos purely based on other things we've got going on I'd think this would be good for q3 since that's not actually that far away - what do you think?

**Comment by jvillalobos** [comment]
I think that if this is a small change, we should get it done soon (P2). Theoretically it's a huge acquisition channel, and making this change before the upcoming first run changes (Q3) will make it easier to understand the numbers that come out of that.

**Comment by muffinresearch** [comment]
@jvillalobos I was thinking we'd want to A/B test this scenario to prove the expectations so it's going to be a  bit more than just moving a button.

**Comment by pwalm** [comment]
Agreed with Jorge. Let's see if those numbers go back up post-button change, and then we can fine tune and A/B test some more/new options.

**Comment by rebmullin** [comment]
hey @pwalm - how does the following look:

![Alt text](https://monosnap.com/image/o1rt2STbGmzuDZXMZZTAefnXRLOgTV.png)

Also - I have a few follow up questions too:

do we need to we need to update the text copy to match what’s above (“Only with Firefox - Get Firefox Now!”), or leave current text as is? 

Is this the only place we are replacing the banner? 

I have not changed the url - it's still: `https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&amp;utm_medium=referral&amp;utm_campaign=non-fx-button&amp;utm_content=install-addon-button` - is this what we want?


// cc @bobsilverberg @muffinresearch

**Comment by pwalm** [comment]
Hello Rebecca,
Couple things to clarify (since I was unclear before! apologies):
- We're going to get rid of the banner entirely for non-Firefox users. (Looks like you restyled it bigger and more button-like in that screenshot)
- The light blue (deactivated) "Install Theme" button needs to be restyled to be the green “Only with Firefox - Get Firefox Now!” button seen at the top of this issue. Follow the [design system guidance for the puffy button](https://design.firefox.com/photon/components/buttons.html#puffy).
- I think the url stays the same for now. @shell1 can you clarify that?

**Comment by rebmullin** [comment]
cool - thanks @pwalm @bobsilverberg  : )

**Comment by willdurand** [comment]
@rebmullin so, this has been fixed no?

**Comment by rebmullin** [comment]
@willdurand  - yep -thanks - it should be fixed by PR #4925. I guess b/c i didn't put ~`#4872`, it didn't close this..?

I'll close now...

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev and AMO stage with Chrome, Microsoft Edge, Internet Explorer. 
On iOS platform - Safari and on Android - Chrome for small devices.
The button "Only with Firefox - Get Firefox now" instead of greyed out "Add to Firefox" is displayed and redirects to https://www.mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=install-addon-button&utm_medium=referral&utm_source=addons.mozilla.org

I filed an issue for what I've noticed on Internet Explorer  - https://github.com/mozilla/addons-frontend/issues/4963

**Comment by willdurand** [comment]
@ioanarusiczki I am not sure to understand, is this issue marked as verified?

**Comment by ioanarusiczki** [comment]
@willdurand I'm sorry, forgot to add label, thanks for the reminder :)

**Comment by bobsilverberg** [comment]
@MeridelW We don't generally re-open issues unless there's a critical bug that needs to be fixed related to the original patch, so this would best be done as a new issue. I will open one on your behalf, but something to keep in mind in the future. :-)

**Comment by MeridelW** [comment]
@bobsilverberg Ah, got it! Thanks, Bob - for the explanation and for opening a new bug. =)
