### ISSUE TITLE
Two or more add-ons with the same name can be submitted 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4877]
Prerequisites:
User is logged in 
STR:
1. Go to dev hub and submit an add-on.
2. Submit a new add-on using the same name.
3. After they're auto approved go to AMO homepage and make a search.
4. Observe results.

Actual results:
The search returns two add-ons with the same name.

Expected results:
User should be warned during submission that the name already exists and he should change it to avoid a duplicate name.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF59(Win10).
While submitting an add-on a warning message is displayed to correct the slug "This slug is already in use. Please choose another". It should also warn the developer about the Name.

![same name](https://user-images.githubusercontent.com/33448286/39351804-591ad1a8-4a0b-11e8-9d8e-029c0617d3ec.png)

![slug](https://user-images.githubusercontent.com/33448286/39351796-5192bd74-4a0b-11e8-9789-7fe4c6e5db8f.png)

**Comment by bobsilverberg** [comment]
@ioanarusiczki Dev hub is the legacy site, is it not? If so then I think this needs to be filed for addons-server, not addons-frontend.

**Comment by ioanarusiczki** [comment]
Alright, https://github.com/mozilla/addons-server/issues/8156
I'm closing this one. It's a dupe now.
