### ISSUE TITLE
The add-on and author's name are too close 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4878]
STR:
1. Submit an add-on that contains "y" "q" "p" "g" in it's name
2. Go to the add-ons detail page
3. Observe the Add-on details section

Expected result:
It's a reasonable space between the Add-on's Name and Author.

Actual result:
The two names are too close, they look jammed in.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF59 (Win10).

I'll give below two examples to make it more clear
![too close](https://user-images.githubusercontent.com/33448286/39354056-1b4f7d40-4a12-11e8-9c33-27b6274c60e8.png)

and another one 
![another example](https://user-images.githubusercontent.com/33448286/39354075-2a2b3dfe-4a12-11e8-8c9a-4da41f48c7e3.png)

**Comment by wagnerand** [comment]
Mentor: @rebmullin 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by muffinresearch** [comment]
Here's a screenshot of the current mock:

<img width="910" alt="amo_desktop_-_master_sketch" src="https://user-images.githubusercontent.com/1514/39533608-67daa130-4e27-11e8-9f55-15d2d6960372.png">

**Comment by biskit1** [comment]
Hi there, 
I'd like to work on this if possible. 

Got started and will open pull request shortly.

**Comment by bobsilverberg** [comment]
Sounds good, go for it @biskit1.
