### ISSUE TITLE
Remove the h3 for the review titles since they aren't added as part of the form.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4880]
In https://github.com/mozilla/addons-frontend/issues/1739 review titles were removed from the review form. 

However the display on the all reviews page shows empty h3s for the reviews page.

<img width="1234" alt="reviews_for_ublock_origin_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/39374375-90583700-4a42-11e8-962f-58873d73b72c.png">

@jvillalobos Do we need to keep displaying titles for historical reviews or can this markup be completely removed?

Even if we do want to keep titles for historical reviews that have that data, we could at least avoid outputting empty markup.

**Comment by jvillalobos** [comment]
They can be removed, yes.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF59(Win10)
h3 for review titles is removed

![removed h3](https://user-images.githubusercontent.com/33448286/39628741-ae7ecc4c-4fb2-11e8-8004-c5d85f19ca73.png)
