### ISSUE TITLE
on Focus outline is visible

### ISSUE THREAD

**Issue by ashigupta007** [mozilla/addons-frontend#4881]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-GB/firefox
Outline visible on click of the h3 of  div class HeroSection.

### What happened?
On clicking the Div class HeroSection the outline of the h3 is visible.
### What did you expect to happen?
No outline shall come up and the page should redirect to the reffered link
![screenshot 2018-04-28 13 31 54](https://user-images.githubusercontent.com/26579662/39394170-3205bfce-4aec-11e8-9853-1534dafc3879.png)

### Anything else we should know?

Mentored by: @CuriousLearner @realslimshanky

**Comment by muffinresearch** [comment]
This looks to be outlined because it's focused. Removing the outline would require something that indicated focus to replace the outline for accessibility. We could do that but this isn't the only place where we're relying on implicit outline.

**Comment by bobsilverberg** [comment]
@ashigupta007 You say "No outline shall come up and the page should redirect to the reffered link". The page does redirect, does it not? If so is this issue only about the fact that an outline appears around the element when you click it?

**Comment by ashigupta007** [comment]
@bobsilverberg yes it does redirect. outline is the main issue

**Comment by muffinresearch** [comment]
The hero element has been completely replaced.
