### ISSUE TITLE
dropdown selector not properly styled

### ISSUE THREAD

**Issue by ashigupta007** [mozilla/addons-frontend#4882]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-GB/firefox/addon/mp3-downloader-youtube/
The dropdown menu is not properly styled.
### What happened?
On clicking the dropdown the dropdown menu is not appropriately styled
### What did you expect to happen?
The Dropdown should be styled as per the design of the dropdown selector
![screenshot 2018-04-28 14 01 36](https://user-images.githubusercontent.com/26579662/39394228-15f75102-4aed-11e8-8dc7-289c3925031a.png)

### Anything else we should know?

Mentored by: @CuriousLearner @realslimshanky

**Comment by ashigupta007** [comment]
@muffinresearch the dropdown menu list is not of the proper theme as per the website. it needs a proper height and other few detailing for the same

**Comment by muffinresearch** [comment]
@ashigupta007 What specifically is wrong? Please be as detailed as possible so we can understand what needs to be done. 

Are you comparing this to some other part of the site for example? If so please can you provide the reference?
