### ISSUE TITLE
Outlines visible on clicking the arrow buttons

### ISSUE THREAD

**Issue by ashigupta007** [mozilla/addons-frontend#4885]
### Describe the problem and steps to reproduce it:
On clicking the arrow buttons on the page https://www.mozilla.org/en-GB/firefox/
the outline for the arrow buttons gets visible.

### What happened?
On Clicking the arrow button on the page given for navigating between sections the outline gets visible.
### What did you expect to happen?
The outlines should not be visible on clicking them
![screenshot 2018-04-28 14 40 00](https://user-images.githubusercontent.com/26579662/39394703-b078ceb8-4af2-11e8-95c9-7e6c256f3a2a.png)

### Anything else we should know?

Mentored by: @CuriousLearner @realslimshanky

**Comment by muffinresearch** [comment]
@ashigupta007 this issue tracker is for issues related to the UI for https://addons.mozilla.org and does not cover mozilla.org.

Please can you re-file this issue on https://github.com/mozilla/bedrock?
