### ISSUE TITLE
Line height less in 320*480 dimension of Webpage

### ISSUE THREAD

**Issue by im-gozmit** [mozilla/addons-frontend#4886]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/en-US/firefox/
In Responsive Version of this website the line height between text is very less.

### What happened?
![capture1](https://user-images.githubusercontent.com/22200140/39394734-19e9b8a8-4af3-11e8-920b-70dad61a23ad.PNG)
The line spacing between **Experience** and **designs** when you view the website in 320*480 dimensions is not adequate.
### What did you expect to happen?
The Line Height should be changed from 1 to 1.5 ( in this section .HeroSection-content p of the CSS file)
Mentored by: @curiouslearner @realslimshanky

**Comment by wagnerand** [comment]
Mentor: @bobsilverberg 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by xu3u4** [comment]
Hi, I am interested in this project. Can I take this issue as my first try?
Thank you.

**Comment by ioanarusiczki** [comment]
There is a visible space between the lines compared with the screenshot above.
Verified fixed on AMO dev with FF59 (Win10) using Responsive Design Mode 
![space between the lines](https://user-images.githubusercontent.com/33448286/39761662-59244bb4-52e1-11e8-8db3-40f4fc00c574.png)
