### ISSUE TITLE
Image Orientation not proper

### ISSUE THREAD

**Issue by im-gozmit** [mozilla/addons-frontend#4887]
### Describe the problem and steps to reproduce it:
In the **Screenshots** section of any add-on the image is not properly oriented 

### What happened?

Full Image View :

![capture2](https://user-images.githubusercontent.com/22200140/39394881-ede6fbba-4af4-11e8-928f-2274f145369c.PNG)

In the ScrollBar the image is cut from bottom and which doesn't look good.

![capture3](https://user-images.githubusercontent.com/22200140/39394880-e8ba7824-4af4-11e8-9b94-81f5baf91c9b.PNG)

### What did you expect to happen?

 Either there should be a vertical scroll bar too or the dimensions of the Screenshots section should be changed to get proper view.  

Mentored by: @curiouslearner @realslimshanky

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10). 
The images don't look cropped anymore
Before
![before](https://user-images.githubusercontent.com/33448286/40921244-91d4a288-6817-11e8-8fdc-ea45619ed78a.png)

After 
![after](https://user-images.githubusercontent.com/33448286/40921250-99098f8c-6817-11e8-9c65-dabf44b7dce0.png)
