### ISSUE TITLE
Password Reset Page Problem

### ISSUE THREAD

**Issue by im-gozmit** [mozilla/addons-frontend#4889]
### Describe the problem and steps to reproduce it:
When you click on the link **Forgot Password** and via email you are resetting it .
After you successfully reset the password this page will appear.

![screenshot 55](https://user-images.githubusercontent.com/22200140/39395348-47cf1670-4afb-11e8-9bb9-643e9eddf4ff.png)

### What happened?

When I tried to reset the password then after the password changed successfully there is no button on page to go back to add-on site or anywhere else.

### What did you expect to happen?
In the UI, there can be a button to go back to add-on site or firefox site.

Mentored by: @curiouslearner,@realslimshanky

**Comment by bobsilverberg** [comment]
@im-gozmit This page is in a new tab that opens when you click the link from your email. The add-ons web site should still be open in a separate tab, where you originally clicked the "Register or Log in" button. After you reset your password and see the screen above, the tab containing the add-ons web site should automatically sign you back in. 

Is that not what you're seeing?

**Comment by bobsilverberg** [comment]
I believe the explanation at https://github.com/mozilla/addons-frontend/issues/4889#issuecomment-385394330 explains this, and we haven't heard anything back from the reporter in over a week, so I'm going to close this.
