### ISSUE TITLE
Hover Button Color Needs to be of proper contrast

### ISSUE THREAD

**Issue by ashigupta007** [mozilla/addons-frontend#4890]
### Describe the problem and steps to reproduce it:
The background color of the button on hover needs to be improved with better contrast.
https://addons.mozilla.org/en-US/firefox/addon/leechblock-ng/reviews/?page=2

### What happened?
The contrast for the button on hover  matches almost with the background color of the body
### What did you expect to happen?
the button hover background color needs to be improved for a better visibility.
### Anything else we should know?
![screenshot 2018-04-28 16 10 17](https://user-images.githubusercontent.com/26579662/39395696-38b7b314-4aff-11e8-93aa-2eb48e4b695d.png)
![screenshot 2018-04-28 16 10 21](https://user-images.githubusercontent.com/26579662/39395701-3f871360-4aff-11e8-8922-294411aee81a.png)

**Comment by AlexandraMoga** [comment]
Issue first reported in [#2517 comment](https://github.com/mozilla/addons-frontend/issues/2517#issuecomment-362619270)

**Comment by muffinresearch** [comment]
See also https://design.firefox.com/photon/components/buttons.html#behaviours for the photon button behaviour spec.

**Comment by willdurand** [comment]
I think this is fixed by #5191.

**Comment by ioanarusiczki** [comment]
The light grey while hovering is more evident now with the new design although it could be made even darker.
Verified fixed on AMO Dev with FF60(Win10). 

![hover over next](https://user-images.githubusercontent.com/33448286/41660877-ff02db96-74a5-11e8-8062-bbc3ba13b3f1.png)
