### ISSUE TITLE
Unify the display of Lightweight and static themes

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4899]
To faciliate the handling of static themes on addons-frontend we need to unify the display of lightweight (LWT) and static themes.

## Key differences

* Static themes have a single static "baked" preview image. LWTs display the main theme image which is truncated by the container. This will impact the unification of the main image.
* Static themes are installed the same way a web extension is installed. LWT themes use a special API that reads a blob of JSON that defines the theme's assets.

## UX needed

First we need UX that Unifies the following areas to minimise the differences

* Search results
* Shelves with theme results.
* Details page

**Comment by pwalm** [comment]
Thank you for filing this! On it.

**Comment by jvillalobos** [comment]
There was some discussion around this in https://github.com/mozilla/addons-frontend/issues/4661. The main thing I want to make sure we do is not crop the preview image vertically. There are cases where there's horizontal cropping, inevitably, but that's a similar problem for LWT. 

Other than the preview image, I hope we can keep both theme types nearly identical, to avoid confusing users too much about them.
