### ISSUE TITLE
10 May homepage content programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#4903]
For the **10 May** push, please find homepage content updates detailed [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @diox @bobsilverberg

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev and the content is updated.
Full validation will be made in prod with actual data
