### ISSUE TITLE
Simply clicking the link to go to the page of and install an extension gives me error page

### ISSUE THREAD

**Issue by Clearwaterblues** [mozilla/addons-frontend#4906]
### Anything else we should know?
I get this page instead:

Server Error

Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it.

**Comment by muffinresearch** [comment]
@Clearwaterblues please can you provide the URL you were on and the browser version you're using?

Can you also tell us what page you started on?

**Comment by muffinresearch** [comment]
This is likely to be the same cause as https://github.com/mozilla/addons-frontend/issues/4907 but having the URL will enable us to confirm it.

**Comment by Clearwaterblues** [comment]
The url? To what exactly? All extension links do this. I start here:
https://addons.mozilla.org/en-US/firefox/extensions/ and I am using version
59.0.3 64bit I hope this helps

**Comment by Clearwaterblues** [comment]
Seems to be working now
