### ISSUE TITLE
Enable the download button for incompatible clients (link to extension source)

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4910]
Following on from: https://github.com/mozilla/addons/issues/703 

We should look to leave the "install" button enabled for incompatible clients so that users that user `privacy.resistFingerprinting` set to true can still install add-ons.

![screenshot from 2018-04-23 13-18-36](https://user-images.githubusercontent.com/2735603/39142521-76e3d32c-471a-11e8-8846-f7f907d9d046.png)

We'll need to figure out the correct wording in this case as well as make sure the JS API falls-back to the add-on link gracefully for incompatible UAs.

**Comment by muffinresearch** [comment]
@jvillalobos is there anything else you'd like to be considered for this issue?

**Comment by muffinresearch** [comment]
> It's not only non-Fx UAs, but also incompatible versions, since that's what the preference changes.

Thanks, I've updated the description.

**Comment by willdurand** [comment]
@muffinresearch is this still needed? I know some users find the link to the xpi _via_ the install button already.

**Comment by gavinr** [comment]
I am [having this issue](https://discourse.mozilla.org/t/browser-detection-incorrect/48787), and I suspect others are running into this too.

**Comment by gavinr** [comment]
This should not be closed, see discussion here: https://discourse.mozilla.org/t/browser-detection-incorrect/48787

**Comment by bobsilverberg** [comment]
@jvillalobos Do we know how we want this to look? I was imagining a simple text link under the button that can be used to download the xpi. Do we want this in cases where the download button is disabled and also in cases where the button is a "Download Firefox" button? If we're going with a text link (or a button for that matter), what should the text read?

**Comment by jvillalobos** [comment]
> I was imagining a simple text link under the button that can be used to download the xpi. 

A simple text link is what I had in mind, yeah.

> Do we want this in cases where the download button is disabled and also in cases where the button is a "Download Firefox" button?

Yes

> what should the text read?

"Download file"

**Comment by willdurand** [comment]
Note that when we have the Install button, the XPI link is available with a right click in some cases. I like the idea of a small-ish text below the button with the direct link to the XPI, though.

**Comment by bobsilverberg** [comment]
@jvillalobos Here are some examples of what I've done. Note that I made the link grey and lighter to make it less noticeable. Please let me know if you'd like to see style changes.

<img width="861" alt="Screen Shot 2020-09-15 at 11 46 17 AM" src="https://user-images.githubusercontent.com/142755/93233593-40cbe900-f749-11ea-9ffe-28950f21572d.png">

<img width="417" alt="Screen Shot 2020-09-15 at 11 48 02 AM" src="https://user-images.githubusercontent.com/142755/93233655-57724000-f749-11ea-86e3-354790c8b9a8.png">

<img width="651" alt="Screen Shot 2020-09-15 at 11 48 46 AM" src="https://user-images.githubusercontent.com/142755/93233742-71138780-f749-11ea-9619-637a67f9029f.png">

<img width="405" alt="Screen Shot 2020-09-15 at 11 49 29 AM" src="https://user-images.githubusercontent.com/142755/93233840-8983a200-f749-11ea-80c6-0038fc4c845b.png">

<img width="865" alt="Screen Shot 2020-09-15 at 11 51 52 AM" src="https://user-images.githubusercontent.com/142755/93234126-eaab7580-f749-11ea-88af-15928cda8b77.png">

<img width="445" alt="Screen Shot 2020-09-15 at 11 53 10 AM" src="https://user-images.githubusercontent.com/142755/93234253-0f075200-f74a-11ea-96fe-fd3fe591b50e.png">

**Comment by jvillalobos** [comment]
Can you please add an underline so it is clearer that it's a link? I'm also slightly curious why the spacing between the button and the link changes in some screenshots. It's very close to the button for some of them.

**Comment by bobsilverberg** [comment]
> I'm also slightly curious why the spacing between the button and the link changes in some screenshots. It's very close to the button for some of them.

That was a result of a style in place for the mobile view. I've fixed that so that in all sizes there is the same 12px gap between the button and the link, and I've added the underline:

<img width="449" alt="Screen Shot 2020-09-16 at 10 30 54 AM" src="https://user-images.githubusercontent.com/142755/93351641-f78e9e80-f807-11ea-9385-7e7213796ddd.png">

**Comment by AlexandraMoga** [comment]
I've verified several instances in which the Install button is disabled:

[1] - Incompatible Firefox version (needs lower version)
![image](https://user-images.githubusercontent.com/31961530/93779780-00300c00-fc30-11ea-8508-b5a012ca7eab.png)

[2] - Incompatible Firefox version (needs higher version)
![image](https://user-images.githubusercontent.com/31961530/93779866-1b028080-fc30-11ea-90a9-56abdc975b9b.png)

[3] - Incompatible platform 
![image](https://user-images.githubusercontent.com/31961530/93780269-9cf2a980-fc30-11ea-850c-08ff11103782.png)

[4] - Browser other than Firefox
![image](https://user-images.githubusercontent.com/31961530/93780386-c3b0e000-fc30-11ea-8e0e-77e5a61d3295.png)

@bobsilverberg On non-Firefox browsers and on Android, the Download file link will trigger the `.xpi` download to the file system while In Firefox desktop, the link will trigger an installation (see [example](https://addons-dev.allizom.org/en-US/firefox/addon/release-lang-pack-80/)). It is not clear from the requirements if an installation is to be expected, or if the download button should always trigger an actual file download.

**Comment by Rob--W** [comment]
> On non-Firefox browsers and on Android, the Download file link will trigger the `.xpi` download to the file system while In Firefox desktop, the link will trigger an installation (see [example](https://addons-dev.allizom.org/en-US/firefox/addon/release-lang-pack-80/)). It is not clear from the requirements if an installation is to be expected, or if the download button should always trigger an actual file download. 

This is expected for now, as Firefox for Android (Fenix) doesn't support installations of xpi files yet.

**Comment by cadeyrn** [comment]
I gueess the question was more about the other part:

> while In Firefox desktop, the link will trigger an installation

I don't expect that a "Download file" link triggers an installation, I expect it to trigger a download of the file.

**Comment by AlexandraMoga** [comment]
Filed #9679 as a follow up
