### ISSUE TITLE
opening link from search results leads to "Sorry, but we can't find anything at the address you entered."

### ISSUE THREAD

**Issue by djbacon** [mozilla/addons-frontend#4911]
### What happened?
I clicked on item from search results searching form "xmarks". 
https://addons.mozilla.org/en-US/firefox/search/?q=xmarks&platform=Linux&appver=59.0.2
Xmarks Sync was first result. I clicked on that and i got message "Sorry, but we can't find anything at the address you entered.".

### What did you expect to happen?
It was supposed to me Xmarks Sync addon page.

### Anything else we should know?
Using Ubuntu Mate 18.04 (64bit), Firefox Quantum 59.0.2 (64-bit)

**Comment by djbacon** [comment]
It appears that Xmarks Sync is shut down on May 1, 2018, so i guess Xmarks Sync page is removed, but search database not updated.

**Comment by willdurand** [comment]
Hi @djbacon, indeed the add-on has been deleted from the website and that's why you cannot access it. However, we should not list this addon in the search/autocomplete results anymore.

**Comment by willdurand** [comment]
I am going to close this issue as we cannot do anything on our side except refreshing the suggestions/search results. Thank you for reporting this issue!
