### ISSUE TITLE
Discuss the treatment of long homepage URLS

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4916]
A PR was put up to truncate the long URL with an ellipsis to fix the long homepage URL:

<img width="367" alt="screen shot 2018-04-20 at 11 03 42 pm" src="https://user-images.githubusercontent.com/31850821/39079778-5705a922-44ef-11e8-944f-dd6edf7a3e3e.png">

Rather than do this I'm wondering if we should instead just link the word homepage so that we don't have a truncated string at all. A link's href doesn't need to be visible on the page afterall.

@pwalm thoughts?

**Comment by pwalm** [comment]
Yeah, I prefer a linked "Homepage" as well. Let's do that.

**Comment by bobsilverberg** [comment]
Thanks @pwalm. Just wondering, how would this look? The current page uses a format where we have a label (with a lighter font) with a value underneath it (see "User since" and "Number of add-ons" in the image above). Would we just keep the "Homepage" label, with the lighter font, and not have any value underneath it, or do you envision something different from that?

**Comment by bobsilverberg** [comment]
Ok, just to confirm, because I'm dense, for Homepage, there will be no label, and all that will appear is the word "Homepage" which will look like the link in the example above. Is that correct?

**Comment by pwalm** [comment]
Yes, correct. It's either this or we show the whole URL.

~OR~

We could provide a title field and an url field. So the use could enter both, we'd have a nice url title link with a subhead of "Home page".

~OR~

Is there a way the user can enter and URL and we can grab the <title>?

**Comment by jvillalobos** [comment]
We're going with the "Homepage" label to keep things simple.

Mentor: @bobsilverberg

**Comment by robertdudaa** [comment]
I'd like to take up this issue. My first contribution here. @willdurand

**Comment by willdurand** [comment]
@robertdudaa go for it :)

**Comment by willdurand** [comment]
@robertdudaa thank you for your first contribution! 🎉 /cc @caitmuenster

**Comment by ioanarusiczki** [comment]
@pwalm - I verified on AMO dev with FF66(Win10). 

> "Home page" should just be the link.

So from the discussions above I understood that the light grey Homepage should no longer be there. 
Can you confirm please?

![homepage twice](https://user-images.githubusercontent.com/33448286/58105170-b9bb3f00-7bee-11e9-8186-d6f5e42a6a3c.gif)

**Comment by willdurand** [comment]
@ioanarusiczki in the recent comments, I see:

> We're going with the "Homepage" label to keep things simple.

**Comment by ioanarusiczki** [comment]
@willdurand Oh ok, so this means that the label is kept `Homepage` - that's the light grey. And below it's the link named also `Homepage` as it's displayed above which further means why the merged issue says 
>Kept the lightgray 'Homepage' label, as discussed in #4916
