### ISSUE TITLE
When creating a new collection, the slug should be prefilled

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4919]
As discussed with @pwalm a couple of weeks ago, in order to speed the process of creating a collection, on the "Create a collection" form, we should pre-fill the stub field so the user only has to enter a Collection name in order to save the collection. They will be free to change the slug if they wish, but they won't have to.

We can use whatever the user entered for the name as the basis for the slug, replacing spaces with `-` and removing invalid characters.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10). 

![prefilled](https://user-images.githubusercontent.com/33448286/40306905-1eabcdfe-5d09-11e8-9bb6-f9f89f55c421.gif)

Filed https://github.com/mozilla/addons-frontend/issues/5057 for what I noticed. And https://github.com/mozilla/addons-frontend/issues/5058 which is already a dupe of https://github.com/mozilla/addons-frontend/issues/5022
