### ISSUE TITLE
Cachebust all JS 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4927]
Updating to a newer version of Uglify in webpack caused webpack to use the same filenames for different content. 

This meant that SRI (subresource integrity hashes were broken noticed for some locale files). 

Since rolling back this change (Done in https://github.com/mozilla/addons-frontend/commit/e7c4176f1e004e0a67c78c6b40caf1ff95255663) could result in a content change without a filename change again we need to ensure that we cache-bust all JS. 

The easiest way to do this is likely to be to modify the locale generated JS. Doing this will not only cachebust the locale js but it will also cachebust the main js since it has to reference it to dynamically load the locale js.

/cc @eviljeff @diox

**Comment by muffinresearch** [comment]
Here's the files on stage as of now (Friday AM):

Main JS file:
https://addons-amo-cdn.allizom.org/amo-64299d5e8d5aa362d65b.js

A sample of locale JS files:
https://addons-amo-cdn.allizom.org/amo-i18n-ro-82c34f731c39ea92bdc3.js
https://addons-amo-cdn.allizom.org/amo-i18n-en_GB-168c1fd26685e4e755bb.js
https://addons-amo-cdn.allizom.org/amo-i18n-de-1137007829a6be3b8a6b.js
https://addons-amo-cdn.allizom.org/amo-i18n-fr-2408f1b15cda4bab74d3.js

**Comment by muffinresearch** [comment]
## QA Notes: 

To validate this on stage + prod we need to check the following:

### AMO

* Load AMO with ro, en-GB, de and fr locales (you can check other locales too, just these should be used for the purposes of the asset filename changes).
* Check the site functions and JS is working
* Watch the network tab for JS and you should see different file-names compared to those listed in the comment above. The hash part in particular should be different e.g. amo-i18n-fr-**2408f1b15cda4bab74d3**.js

### DISCO PANE

* Load the disco pane with ro, en-GB, de and fr locales (you can check other locales too, just these should be used for the purposes of the asset filename changes). 
* Check the site functions and JS is working
* Watch the network tab for JS and you should see different file-names compared to those listed in the comment above. The hash part in particular should be different e.g. disco-i18n-fr-**5a6aaf7667f31cd149e0**.js

**Comment by muffinresearch** [comment]
WIth tag 2018.05.4 on stage

On AMO stage I see: 

* **main file** https://addons-amo-cdn.allizom.org/amo-d2f806a24040e0c2d973.js
* **ro** https://addons-amo-cdn.allizom.org/amo-i18n-ro-080ef9c0d2c8c5d46e62.js
* **en-GB** https://addons-amo-cdn.allizom.org/amo-i18n-en_GB-f58e538f4c843c889cd8.js
* **de** https://addons-amo-cdn.allizom.org/amo-i18n-de-1f79f02fa18737ae3bdc.js
* **fr** https://addons-amo-cdn.allizom.org/amo-i18n-fr-2dc1ceea589de0d37951.js

On disco pane stage I now see:

* **main file**: https://addons-discovery-cdn.allizom.org/disco-5bbb98a7d3b0a6036088.js
* **en-GB** https://addons-discovery-cdn.allizom.org/disco-i18n-en_GB-27d3cdc62c52e556779c.js
* **ro** https://addons-discovery-cdn.allizom.org/disco-i18n-ro-21fb7e8657d57b794ff7.js
* **de** https://addons-discovery-cdn.allizom.org/disco-i18n-de-51e67b8788478ceb2bba.js
* **fr** https://addons-discovery-cdn.allizom.org/disco-i18n-fr-5f941a90423a07cb7c57.js

**Comment by vcarciu** [comment]
Verified as fixed.
