### ISSUE TITLE
Refreshing the page on search tools landing page will load the legacy frontend version

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4934]
STR:

1. Go to AMO homepage
2. Click on More... menu and select Search Tools
3. Refresh the page

Actual result:
The legacy version for Search Tools landing page is loaded when the page is refreshed

Expected result:
The frontend version for Search Tools landing page is displayed at page refresh

Notes:
- clicking on 'View the new site' will not redirect back to the frontend version for Search Tools landing page
- this seems to be similar to issue #4647 
- reproduced on all AMO servers with FF59, WIn10x64

![src-tool](https://user-images.githubusercontent.com/31961530/39628422-b6147a2a-4fb1-11e8-8135-378e867de568.gif)

**Comment by rebmullin** [comment]
Hey @jvillalobos   - I was looking into this a bit and saw some discussion about search at #4496 which I think discusses this a bit. Can you please confirm that I have this right - the header link here (`/search-tools/`) should be updated to the following:

'/search-engines/' (set up redirect to /search/?type=search)

Or do you have more info here?

**Comment by jvillalobos** [comment]
Yes, it looks like redirecting to `/search/?type=search` should fix this problem.

**Comment by muffinresearch** [comment]
@mozilla/addons-ops should be able to confirm, but it's possible the `/%LOCALE%/%APP%/search-tools/` path isn't in the nginx config which routes this route to the new frontend for a server-side rendered page.

**Comment by philipcristiano** [comment]
I can confirm that there isn't anything for `search-tools` in the config management repo. So there isn't anything in the nginx config for this.

**Comment by rebmullin** [comment]
thanks @philipcristiano 

@muffinresearch  - given what @philipcristiano notes above  - is this a matter of just updating the config? how / where is that done?

**Comment by philipcristiano** [comment]
I think it should be very similar to #1987. I'm planning to start on this once I finish up another deploy to the proxy servers.

**Comment by philipcristiano** [comment]
https://addons.mozilla.org/en-US/firefox/search-tools/ now loads the proper UI.

**Comment by AlexandraMoga** [comment]
Verified as fixed on all AMO servers

![src-tool](https://user-images.githubusercontent.com/31961530/40184204-52f7b104-59f8-11e8-833f-4120386ecccc.gif)
