### ISSUE TITLE
Clicking Browser Back button when navigating large collections generates Server error.

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#4936]
### What happened?
Open large collection that is paginated into 2 or more pages, e.g.
https://addons.mozilla.org/en-GB/firefox/collections/smayer97/for-mr-tech-toolkit/
Go to second page. 
Click browser Back button generates server error message
![screen shot 2018-05-04 at 10 18 19 am](https://user-images.githubusercontent.com/6752849/39633007-4cc3e75a-4fa6-11e8-9646-2d65b21b50d0.png)

### What did you expect to happen?
To be able to go back to previous page of collection.

### Anything else we should know?
Occurs regardless of browser used...
Refreshing the page seems to load page correctly.
Also, clicking Previous button at bottom of page also seems to work correctly.

**Comment by smayer97** [comment]
Oops...just noticed someone else posted the exact same thing as me just moments ago...
https://github.com/mozilla/addons-frontend/issues/4933

So this is now a duplicate.

**Comment by willdurand** [comment]
indeed, thanks for your report @smayer97.

**Comment by smayer97** [comment]
;-)
