### ISSUE TITLE
The Video download helper plugin can't be uninstalled.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#494]
Using the testing steps from: https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing and pointing at -dev.

The VideoDownloadHelper looks to install - but actually needs a restart to complete so we can't uninstall it without first finishing the install.

You see `Error: Addon not found` in the console.

**Comment by muffinresearch** [comment]
Better described in #495

**Comment by muffinresearch** [comment]
Needs investigation - this might be a dupe of #495

**Comment by andymckay** [comment]
This is because the version on -dev is not restartless, its out of date 4.9.21. The one on prod is restartless its version 5.6.1, so we should be good as we move the disco pane up AMO servers. We could also just copy the newer version down so this doesn't trip up others.
