### ISSUE TITLE
AddonRecommendations card does not have enough space at the bottom when loading

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4947]
This may be difficult to reproduce depending on how fast the recommendations are loaded, but here's an STR:

1. Go to the details page for an add-on.
2. Observe the `AddonRecommendations` card which appears below the "About this extension" card on the right-hand side.
3. Try to observe it when it is in its loading state. You can re-trigger this by doing a hard refresh on the page.

Expected:

The card looks good, with proper spacing.

Actual:

There is not enough space at the bottom of the card.

Example:

![screen shot 2018-05-07 at 10 49 55](https://user-images.githubusercontent.com/217628/39694853-ef9546e2-51e8-11e8-81e1-33a83dcb4f64.png)

**Comment by AlexandraMoga** [comment]
Update:

Add-ons with longer names do not fit entirely in the recommendations card on smaller screen sizes:

![image](https://user-images.githubusercontent.com/31961530/39817542-1b8dd484-53a7-11e8-8ff8-8a30a5256f17.png)

@bobsilverberg I guess this is related with your issue, but if you prefer, we can track it separately.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I guess this is related with your issue, but if you prefer, we can track it separately.

I think this is the same issue as I discussed above, so I don't think we need a separate issue to track it.

@rebmullin Would you be willing to take this one on? I tried to fix it but couldn't seem to figure it out.

**Comment by rebmullin** [comment]
@bobsilverberg  - sure thing!

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40124602-8f86bace-5931-11e8-8ac2-b457e0784c12.png)
![image](https://user-images.githubusercontent.com/31961530/40124624-9f64d75a-5931-11e8-9775-cc9201e84bec.png)
