### ISSUE TITLE
e10s and the new disco pane

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#495]
For some versions of Firefox e10s will request a restart if you install an add-on to turn off e10s. It currently does this in the doorhangers, in the disco pane it fails.

Given the updated timeline of e10s, this is something that will likely occur around the same time as the disco pane rolls out which is unfortunate.

To reproduce:
- I started with a clean nightly profile
- Turned on the disco pane as discussed here: https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing
- Turned on being in the e10s flag by going to about:config and adding in `extensions.e10sBlocksEnabling` as `true`.
- Double check that you have no add-ons installed and multiprocess is enabled

Go to the new disco pane. The add-on gets to the green check mark but its not actually installed.

If you go to about:addons its installed but has a banner:

![screenshot 2016-06-01 13 08 14](https://cloud.githubusercontent.com/assets/74699/15723996/f0c96568-27f9-11e6-8b18-ea0d22d33183.png)

There's a movie here:

https://www.dropbox.com/s/673vzqlnpi0etz6/e10s-install-disco-pane.mov?dl=0

There's two ways around this:
- alter the UX to cope with this and display information to the user about the restart being required. I'll note that once an add-on has been "installed" and in that state, `mozAddonManager.getAddonByID('...')` does not return the add-on. I'm not sure if an event occurred during the install that the front end can capture. If there is an event there, we have the pieces in place to implement a slightly different UX.
- don't make these add-ons trigger the e10s check, in theory all these add-ons are vetted by the add-ons team and should be e10s compatible, but allowing them in does kind of mess up the e10s plans so that decision should be made with the e10s team.

**Comment by aswan** [comment]
When https://bugzilla.mozilla.org/show_bug.cgi?id=1268077 lands we should have the information about restarts readily available (via the `needsRestart` flag on install events).
adding a special exception for some extensions is doable, that's obviously work on the firefox side and at this point, getting it into 48 is going to be a chunk of work.

**Comment by designakt** [comment]
Wow, that sounds bad. What % of users might be affected by this?
Not showing that a restart is needed is one thing, and could be solved with some UI.
![e10sdiscotest](https://cloud.githubusercontent.com/assets/8145891/15742940/3be4a8d2-28c2-11e6-80a9-d4e83de797ba.gif)
But re-introducing restarts into disco pane, where being restartless is one of the core principles of making the installation as smooth as possible, is even worse.
I understand that e10s wants no add-ons in that phase of testing, so it seams contradictory that we will start our efforts of getting add-ons to more people at the same time.
Either we delay, or we exempt those add-ons from that rule. Or, if this only affects a small subset of users, it could be acceptable to tell them to re-start.

**Comment by pwalm** [comment]
I'm fine with alerting users to restart (better than nothing) like we have spec'd out above. Just remove the "restart" link since we can't do that. What versions of Firefox require this? % of users affected? Can we use this to prompt them to update?

**Comment by designakt** [comment]
As I understand this is connected to e10s. In Firefox 48 we will roll out e10s to all users that currently do not have extensions installed. About 50% of our users? 
And then we tell them to install add-ons in the same release with our new disco pane... And require them to restart because we just enabled e10s but have to disable it again now that they installed an add-on we suggested... Seams to be very odd behavior to me.
This restart is acceptable if it affects a very small percentage of users, but not on such a scale and not when we are the cause for the need to restart because we just enabled e10s.

**Comment by andymckay** [comment]
Its tough to have multiple streams like e10s and a better install behaviour at the same time. I don't think we want to stop the disco pane till next year considering all the other benefits it brings, and we can't stop e10s. I don't think the two are exclusive, the restart before installing an add-on was going to happen anyway when you are in the e10s cohort, would you rather have it with a doorhanger or a flow you can control?

But for the bigger picture, I would direct you towards Kev or Shell.

**Comment by shell15** [comment]
@andymckay @muffinresearch is there a path forward for this bug and a timeframe?  It starts to be an issue in 48  when e10s is going to eligible population =\ (who will get into this situation if they try to install add-on after being determined eligible).  the e10s goal is to get to 100% of eligible in Fx8 if the telemetry coming back doesn't block them from doing that (so unless negative impact seen in telemetry)

**Comment by andymckay** [comment]
Do the restart message as @pwalm mentioned.

**Comment by muffinresearch** [comment]
@andymckay @shell15 We should already handle the restart hint if it's give to us. It works for a normal add-on that requires restart - e.g. Video Downloader (on -dev which requires a restart because it's an older version of the add-on) We should test the e10s specific case too though.

**Comment by andymckay** [comment]
Awesome. Closing and assigning to QA then.

**Comment by designakt** [comment]
@shell15 last time I talked to @deadsquid about this, he mentioned that our disco pane add-ons will be whitelisted for e10s tests in 48 so that they will not require a restart.
If we know all our add-ons will require a restart in 48 we should wait for the next version. No restart was one of our initial selectors for add-ons being eligible for discovery. We should not talk about bringing a better install if it then requires restart for all add-ons.
@shell15 @andymckay I am happy to talk about how to move forward, but I am not happy with our first version if discovery requiring restart for all add-ons. Let us meet today, or tomorrow to chat about that.

**Comment by Ryuno-Ki** [comment]
I'm already on Firefox v49 (with lots of AddOns). What is the current state here, @designakt?

**Comment by designakt** [comment]
@Ryuno-Ki TO my knowledge all add-ons on disco pane should be whitelisted to not require a restart of Firefox if e10s is enabled. Do you have e10s enabled, and do any add-ons on the disco pane trigger a restart of Firefox if you install them?

**Comment by Ryuno-Ki** [comment]
Nope. No e10s for me. Way too much addons in use :-)

**Comment by muffinresearch** [comment]
I don't think this is a problem any longer since we deal with the restart hint and the list is curated.

**Comment by ValentinaPC** [comment]
Verified this using a FF55 clean profile under Windows 7 with Disco Pane set to -dev and  the pref `extensions.e10sBlocksEnabling` is set to `true`, and obtained the following results:
- after installation, the add-on requires restart in both "Get Add-ons" and "Extensions" tabs;
![2017-04-20_1719](https://cloud.githubusercontent.com/assets/15685960/25235370/9dc7e6bc-25ed-11e7-91f8-d68e0056d6a9.png)

- the "require restart" option is not available for the uninstall process. 

But, as far as I know, add-ons that require restart will not be present in the new Disco Pane...ever. :)
I'll mark this verified-fixed.
