### ISSUE TITLE
The select box to add an add-on to a collection should be hidden until the collection is saved

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4951]
On the Add a Collection screen (https://addons-dev.allizom.org/en-US/firefox/collections/add/) we should hide the select box that is used to add an add-on to the collection before the collection is saved. It serves no purpose when creating a collection.

**Comment by xu3u4** [comment]
Hi may I take this issue?

**Comment by willdurand** [comment]
Hi @xu3u4, yes of course! The "select box" is the autocomplete search for add-ons.
