### ISSUE TITLE
Add-ons by author cards from user profile page show only extensions and themes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#4954]
STR:

1. Load AMO-dev homepage
2. Visit a profile page for a user that has only language packs, dictionaries or search tools submitted:
      Lang Pack and dictionaries: https://addons-dev.allizom.org/en-US/firefox/user/tmd10/
      Search Tools: https://addons-dev.allizom.org/en-US/firefox/user/rangeva/
3. Check the information displayed on the user profile page

Actual result:
There is no "_Add-ons_ by author" card displayed on the user profile page 

Expected result:
Add-on types other then extensions and themes should also be visible on the user profile page

Notes:
Reproduced on AMO-dev with FF59, WIn10x64

![no ext type](https://user-images.githubusercontent.com/31961530/39752343-cb84c1e8-52c3-11e8-9586-4b290aabd806.gif)

**Comment by willdurand** [comment]
I see in the code that it has been done on purpose.

@jvillalobos do we want to display addons other than extensions and themes?

**Comment by jvillalobos** [comment]
We're phasing out all other add-on types, so I don't think we need to show them there.
