### ISSUE TITLE
A different title should be displayed while hovering over the rated star

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4955]
Prerequisites:
user is logged in 

STR:
1. Load AMO dev and go to an add-on or theme's detail page
2. Rate an add-on or theme, no text is needed (such as 3 out of 5)
3. Hover over the rated star and observe the message

Expected result:
Rated 3 out of 5 message is displayed while hovering over the star.

Actual result:
Update your rating to 3 out of 5 is displayed.

Notes:
This issue is reproducible from the add-on detail's page, write a review message box and add-on's review page on AMO dev with FF59(Win10).

![message while hovering after rating](https://user-images.githubusercontent.com/33448286/39755708-8ca7fa1a-52cf-11e8-917a-1c656a9c4a4c.png)

**Comment by SeanPrashad** [comment]
This was my oversight as a result of #4692. [Chaya](https://github.com/biskit1) and I will work on this one together in the near future!

**Comment by SeanPrashad** [comment]
Just letting everyone know that this is still on my radar.. I've just had very little time to get a chance to sit down and work on it :(

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10)
![text for rating](https://user-images.githubusercontent.com/33448286/44667218-d8efbc00-aa22-11e8-9d69-c30f32e9252b.gif)
