### ISSUE TITLE
Set a custom dimension based on the TAAR Lite cohort of the user

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4957]
We are currently sending a single ping to Google Analytics (GA) for each impression of the AddonRecommendations card. We are sending the `outcome`, which will indicate what was requested from the API and what was received, and appending the `fallbackReason` to that with a dash if there was a fallback reason. We are also sending the name of the add-on in question.

We should confirm whether this is the data that is desired, and if this is the correct format.

@muffinresearch Do you want to run with this, or would you like me to take it?

**Comment by muffinresearch** [comment]
@bobsilverberg Martin's Team are writing a doc to cover instrumentation so as soon as that's complete I'll send it your way and from there it should be fairly easy to make a few updates as needed.

**Comment by bobsilverberg** [comment]
Here's a link to the doc for reference: https://docs.google.com/document/d/1xrx2mxh3oCw-6AFoCqmNsXwc4xeqLROSBK9Z58z3A2I

**Comment by bobsilverberg** [comment]
We need to set a custom dimension to support the requirements in the doc mentioned above. I'm going to re-purpose this issue to be about implementing that custom dimension.

**Comment by AlexandraMoga** [comment]
@bobsilverberg could you please add some steps to help us verify this?
Thank you

**Comment by bobsilverberg** [comment]
Hmm, I'm not sure how you might verify this. If you have access to Google Analytics for dev you could check there, but I'm guessing you probably do not. You could check for the logging statement in the web console, but that really only proves that something was logged. It still might be worth checking that, so here's some STR:

1. Open up the web console and observe the console tab.
2. Visit a page for an add-on.
3. You should see a statement in the console similar to:

<img width="654" alt="screenshot 2018-05-14 11 01 30" src="https://user-images.githubusercontent.com/142755/40005571-3dcc2ea2-5766-11e8-936a-b48fc8e7438e.png">

4. The `dimension` should always be "dimension4" and the `value` should be the same as the value of the `taar_cohort` cookie installed for the site.

**Comment by ioanarusiczki** [comment]
I verified the steps above on AMO dev with FF60(Win10). 

@bobsilverberg
I noticed that the statement is displayed in the console not only for add-ons but also for themes, dictionaries, search engines and lang packs too. If that's alright this should be verified fixed.

![gaon](https://user-images.githubusercontent.com/33448286/40056871-50bb91ca-5855-11e8-97cb-e6bf9d04d609.png)

**Comment by bobsilverberg** [comment]
Yes, I believe that is okay. This statement is sending data to GA to inform which cohort the user belongs to. It doesn't really matter which page they're on when this statement is sent.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Alright, marking this verified fixed on AMO dev with FF60(Win10).
