### ISSUE TITLE
Remove stylefmt from dependencies to eliminate nsp-check failure

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4960]
Travis' nsp-check is [failing](https://travis-ci.org/mozilla/addons-frontend/jobs/376447158) because of a component which is a dependency of `stylefmt`, which we appear not to use. Removing `stylefmt` as a dependency *should* resolve this issue.

**Comment by vcarciu** [comment]
Please add some STRs to this issue or mark it as "qa:not-needed"
