### ISSUE TITLE
Truncated text on the "Only with Firefox - Get Firefox now!" button when the add-on's detail page is opened with Internet Explorer

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4963]
STR:
1. Load with Internet Explorer an add-on's detail page that has a longer summary on the left side of the button.
2. Observe the button.

Actual result:
Only with Firefox - Get Firefox now is displayed correctly.

Expected result:
The "w" is truncated and "!" is missing.

Notes:
This issue is not reproducible with Microsoft Edge.

![truncated w](https://user-images.githubusercontent.com/33448286/39814988-3fb25338-539f-11e8-9b60-710e4589003d.png)

**Comment by willdurand** [comment]
I think we focus on Firefox a lot, and then best effort for the other browsers. IE is getting old, so P3 seems fine.

**Comment by bobsilverberg** [comment]
In that case it might make sense to downgrade it to a P4.

**Comment by jvillalobos** [comment]
Agree on low priority. Is this potentially a good first bug?

**Comment by bobsilverberg** [comment]
>  Is this potentially a good first bug?

I'm not sure, it's probably just a css fix, but it might be a tricky one, as it only surfaces on IE.
