### ISSUE TITLE
Don't show all inputs to users who don't have a public-facing user profile page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#4964]
> We should not show these to users who don't have a public-facing user profile page (e.g., developers). It's just noise and may encourage them to enter a lot of text (especially the bio) which no one will see. It also gets in the way of settings, like notifications, below.

In other words, the following inputs should be hidden:

- homepage
- location
- occupation
- biography

**Comment by bobsilverberg** [comment]
I'm sure you know what this means, @willdurand, but the description above does not make it very clear exactly which inputs should be hidden, or under what circumstances. Maybe something a bit more explicit would be beneficial.

**Comment by willdurand** [comment]
Thinking about this again and looking at the other issues, I have the feeling that users who are NOT developers should never have to fill the input fields mentioned in the issue description.

**Comment by willdurand** [comment]
@jvillalobos so, this issue raises a point about user profile page visibility: do we really want to restrict access to these pages so that only "developer" profile pages are public?

- What happens when a user (non-developer) navigates to their profile page?
- What happens when an admin navigates to a non-developer user profile page?
- What happens when a (random) user navigates to a non-developer user profile page?
- Are we sure we never link user profile pages of non-developer users? (e.g., in ratings or reviews)

**Comment by jvillalobos** [comment]
Yes, we want to restrict access to user profile pages because it's a vector for spamming.

>  What happens when a user (non-developer) navigates to their profile page?

There is content that regular users should be able to see on their profile page, like their ratings and their collections.

>  What happens when an admin navigates to a non-developer user profile page?

I think we should show the same we show for the owner of the account. The content being shown is fairly harmless.

>  What happens when a (random) user navigates to a non-developer user profile page?

It shouldn't be possible to navigate to it, but it should show a 404 is the page is visited.

>  Are we sure we never link user profile pages of non-developer users? (e.g., in ratings or reviews)

For the new front-end we avoided user links except for developers in listing pages. If there are others around, they will need to be fixed as they are found.

**Comment by willdurand** [comment]
@jvillalobos if a user already has content (like homepage, bio, etc.) on their profile but is not a developer or artist, should we still display the input fields on their edit profile page? Or does it really matter to show all inputs to all userS?

**Comment by jvillalobos** [comment]
I think it's better to show all inputs for all users. I can picture some dev polishing their profile before publishing their first add-on. And it would also be weird if you enter that info and then those inputs disappear because your add-on is disable or deleted or something.

**Comment by willdurand** [comment]
> I think it's better to show all inputs for all users. I can picture some dev polishing their profile before publishing their first add-on. And it would also be weird if you enter that info and then those inputs disappear because your add-on is disable or deleted or something.

Cool, thanks!
