### ISSUE TITLE
User profile edit page should probably not return a 404 when user is not logged in

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#4965]
See: https://github.com/mozilla/addons-frontend/pull/4922#discussion_r186486440

I don't really know what should be done here, but the legacy frontend redirects to FxA. Maybe we should be doing this too. Displaying a login button would be the easiest option, but this would also show a very empty page with nothing else than a button.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64

![user-edit](https://user-images.githubusercontent.com/31961530/40546834-f3f23732-6038-11e8-884f-30c15d7491c6.gif)
