### ISSUE TITLE
Minor nits with the non-firefox "Get firefox" button

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4967]
STR: Using chrome, visit a details page (on -dev or stage)

The Get Firefox button is not aligned with the text. It might look more harmonious if that is aligned. 

Secondly `Only with Firefox - Get Firefox Now!` should use an em dash rather than a hyphen e.g `Only with Firefox — Get Firefox Now!`

<img width="926" alt="fullscreen_09_05_2018__18_29" src="https://user-images.githubusercontent.com/1514/39829703-27edd034-53b7-11e8-87f3-d24461e81dc2.png">

**Comment by ioanarusiczki** [comment]
@rebmullin Could you please re-check this issue ? 
I see a problem now on FF60 too, the button is no longer centered. Still the same for Chrome or Microsoft Edge.
This is AMO dev 
![nowindev](https://user-images.githubusercontent.com/33448286/40232284-cc5225a8-5aa6-11e8-8b16-f0c357e35af8.png)
And before - was centered - now in AMO stage
![now in stage with ff60](https://user-images.githubusercontent.com/33448286/40232512-c0f87db4-5aa7-11e8-983d-23315e90988b.png)

This is with Chrome - still the same result
![with chrome](https://user-images.githubusercontent.com/33448286/40232699-854b4a84-5aa8-11e8-98dc-88dc12bcd0d2.png)

**Comment by rebmullin** [comment]
hey @ioanarusiczki  I thought the issue instructions were to align button to top text/paragraph. I guess we can check with @pwalm on this too to be sure on which way to proceed:

Intall Firefox button aligned to top of text:
![nowindev](https://user-images.githubusercontent.com/33448286/40232284-cc5225a8-5aa6-11e8-8b16-f0c357e35af8.png)

Install Firefox button centered to text:
![now in stage with ff60](https://user-images.githubusercontent.com/33448286/40232512-c0f87db4-5aa7-11e8-983d-23315e90988b.png)

Get Firefox button aligned to top of text:
![with chrome](https://user-images.githubusercontent.com/33448286/40232699-854b4a84-5aa8-11e8-98dc-88dc12bcd0d2.png)

Get Firefox button centered to text:
![Alt text](https://monosnap.com/image/tzSqaGrQRQDT79otwqYxbeyQQdfD97.png)

**Comment by pwalm** [comment]
Alignment should be from the bottom left corner of the block, 36px of padding of either side:
<img width="1193" alt="screen shot 2018-05-18 at 9 45 37 am" src="https://user-images.githubusercontent.com/6797635/40247163-515b6010-5a80-11e8-8af6-82bc681afd2f.png">

**Comment by rebmullin** [comment]
ahh! ok thanks @pwalm

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10).
Firefox
![padding 24px 36px firefox](https://user-images.githubusercontent.com/33448286/40548083-611aebda-603c-11e8-965a-a6cdc82964b6.png)
Chrome
![padding 36pxchrome](https://user-images.githubusercontent.com/33448286/40548090-670b8c84-603c-11e8-92b0-c5ae17b81dfe.png)
