### ISSUE TITLE
fixing locale bug that shows up on travis-ci

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#4972]
seeing failed test on ci check:

see: https://travis-ci.org/mozilla/addons-frontend/jobs/377046751

**Comment by AlexandraMoga** [comment]
@rebmullin could you please add a "qa:not needed" label when QA's input is not required for a closed issue?
Thank you

**Comment by rebmullin** [comment]
@AlexandraMoga  - yep ...sorry about that...will do moving forward : )
