### ISSUE TITLE
Change the workflow for Add A Collection to leave the user at the edit screen

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4977]
Currently, after a user saves a new collection, they are taken to the View Collection screen, from whence they must click the "Edit this collection" link in order to get back into edit mode to be able to add add-ons to the collection. We determined that this is not the best user experience.

Instead of this the user should "remain" on the edit collection screen, the Search box, which can be used to add an add-on to the collection, will appear, and the cold start text on the right will change to text that suggests the user add some add-ons to the collection.

**Comment by rebmullin** [comment]
hey @bobsilverberg  - i was going to look into this one but i wasn't sure - how do we update urls coming from legacy pages to new pages? for example from here (click on `rm-test-1`): 
![Alt text](https://monosnap.com/image/0NjI9FtADx52PpVDASJooZETpRJqLj.png)

it looks like from what i can tell it's set up correctly on our end but wondering if we need to update this anywhere else?

**Comment by bobsilverberg** [comment]
Oops, sorry @rebmullin, I just saw your comment. I'm not sure what this issue has to do with links from legacy pages, we should probably open a separate issue if there's a problem with that. This is just about changing the workflow of the edit screen on the new front end. Did you want to take this one? If not I'll start working on it.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10). 

![skipping edit my collection](https://user-images.githubusercontent.com/33448286/40714700-0b36e948-640c-11e8-8b83-c550b9099330.gif)


@bobsilverberg I noticed that in the scenario when no text fields are edited after clicking Create collection Cancel and Save Collection have the same effect -> maybe Cancel should no longer be active until some text is edited ? 

![cancel button](https://user-images.githubusercontent.com/33448286/40714668-f4f58a40-640b-11e8-95e9-7f497cbf8a36.gif)

Right now I access the following link https://addons-dev.allizom.org/en-US/firefox/collections/add/ 
Clicking cancel before Creating a collection works like this
![cancel before create](https://user-images.githubusercontent.com/33448286/40715087-26da8780-640d-11e8-985e-8ce8ca643452.gif)
