### ISSUE TITLE
Change button copy in collections flow

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#4978]
Some copy changes need to happen during the create collection flow:

View collection page
- "Edit this collection" needs to be an actual button (not a link)

Edit collection view
- When giving the collection a name in order to create it, the button should read "Create collection"
- When adding add-ons to the collection, the button should read "Save collection"

I think this was it? Meridel, can you add to clarify anything I've missed?

**Comment by MeridelW** [comment]
Thanks, @pwalm. That covers the button copy. Here is all of the copy for the new flow described in [4977](https://github.com/mozilla/addons-frontend/issues/4977)

**User state:** Creating collection
**Grey Space Copy:** First, create your collection. Then you can add extensions and themes. 
Button Copy, State One: Create Collection

From Bob: "User remains on on the edit collection screen, the Search box, which can be used to add an add-on to the collection, will appear, and the cold start text on the right will change to text that suggests the user add some add-ons to the collection."

**User state:** No add-ons in collection. User adding first add-on.
**Grey Space Copy:** Search for extensions and themes to add to your collection. 
**Button copy:** Save Collection

Mentioning @rebmullin so she has final copy. Let's see how this looks.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10)
![create and save collection](https://user-images.githubusercontent.com/33448286/40718853-2f3ff7b8-641a-11e8-80e5-aa3ef8fc4a94.gif)


@pwalm @bobsilverberg This was verified also with https://github.com/mozilla/addons-frontend/issues/4977 where I added what I've noticed about the "Cancel" button.
