### ISSUE TITLE
Add a confirmation when adding add-ons to a collection

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#4979]
We need to add a confirmation when a user adds something to their collection, so they know it happened even if they don't see it. Similar to how I've mocked it up below (for ratings):
<img width="929" alt="screen shot 2018-05-10 at 4 10 32 pm" src="https://user-images.githubusercontent.com/6797635/39898746-0ac45d28-546d-11e8-9ae6-c5e09489f6f0.png">

Rules:
- The message bar should appear above the "Find add-ons" field.
- It should read: "Extension added" or "Theme added" depending on type.
- It should have the green checkmark glyph.
- It should fade away after 5 seconds.

**Comment by bobsilverberg** [comment]
> It should fade away after 5 seconds.

I'm not sure that we're doing this anywhere else. I guess we could enhance the `Notice` component to make that an option. @muffinresearch or @willdurand do you know if this is something we've done previously in the app?

**Comment by willdurand** [comment]
I don't think we have done that yet.

**Comment by bobsilverberg** [comment]
> Not a deal breaker if we don't say the specific add-on type. Just say "Added to collection" instead.

Great, thanks @pwalm. I've changed it to use that text.

**Comment by ioanarusiczki** [comment]
Verified fixed this on AMO dev with FF60(Win10 and Android 8.0) - the Added to Collection message is displayed when an extension or theme is added to the collection.
The following works as expected:
> The message bar should appear above the "Find add-ons" field.
> It should have the green checkmark glyph.
> It should read: "Extension added" or "Theme added" depending on type. - it's Added to collection instead

I noticed that the message won't fade away after 5 seconds - after adding the first extension/theme to the collection it remains permanent - I filed https://github.com/mozilla/addons-frontend/issues/5105

**Comment by bobsilverberg** [comment]
I see that @willdurand  already pointed out that #5105 is a duplicate of #5101. Thanks @willdurand!
