### ISSUE TITLE
Cat glasses doesn't look as cool as a cat should

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#498]
In the discovery pane the cat glasses them looks wierd. I think that's just a problem of having a white image on a white background:

![screenshot 2016-06-01 13 31 50](https://cloud.githubusercontent.com/assets/74699/15724717/3787b9ac-27fd-11e6-8052-5796698043cc.png)

vs.

![screenshot 2016-06-01 13 32 05](https://cloud.githubusercontent.com/assets/74699/15724719/3da49c6a-27fd-11e6-8a82-c394a98a7b3a.png)

Cat's power the internet and perhaps we can find a theme that works better with the disco pane.

**Comment by diox** [comment]
FWIW I raised the issue in https://github.com/mozilla/addons/issues/109#issuecomment-220308660 when the theme selection was made

**Comment by andymckay** [comment]
And that comment totally dupes this one, so Ill close.
