### ISSUE TITLE
We need tests for CollectionManager.onAddonSelected

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#4982]
I'm not sure how I managed to land this without any tests, but I did, so we need some tests for the "Add to Collection" feature of the CollectionManager.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
Hello Bob. Could you provide some STR for QA, or some more details of what to test on this part.
Thanks!

**Comment by willdurand** [comment]
I don't think there is a need for QA here since it is more a code quality issue and related to the test suite.
