### ISSUE TITLE
[suggestion][mobile] Limit more addons per row to 2 in More extensions by user on mobile

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#4987]
![2018-05-13 16 22 28](https://user-images.githubusercontent.com/5318732/39966496-3a6e601e-56ca-11e8-8ec7-a40a9273432f.jpg)
More extensions by user card has 3 addons per row, that looks kind of odd or rather broken, lets limit this to 2 adodns per row for mobile.

@pwalm @muffinresearch

**Comment by willdurand** [comment]
We should maybe use the full width for each addon actually, as done for the shelves if I remember correctly.

**Comment by tsl143** [comment]
Cool, then I will start working on it.

**Comment by championshuttler** [comment]
Seems like its fixed. Can we close this issue ?
![hh](https://user-images.githubusercontent.com/22130317/44732256-84bc0900-ab02-11e8-83cb-3a5bd0e875ae.png)

**Comment by championshuttler** [comment]
On mobile 
![screenshot_2018-08-28-20-41-39-905_com android chrome](https://user-images.githubusercontent.com/22130317/44732453-eda38100-ab02-11e8-8a73-7f82eb52598e.png)

**Comment by willdurand** [comment]
ah yeah, that's totally fixed. Thanks!
