### ISSUE TITLE
'Pick of the Month' Homepage module can't handle add-ons with longer titles

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#499]
I just tried updating AMO's POTM for June by inputting the the add-on's details into this module: 

https://addons.mozilla.org/en-US/admin/monthly-pick

However, June's POTM is called "Smart HTTPS (Encrypt Your Communications)" and as the attached screen grab illustrates, it seems our front end display doesn't adjust well to a title of this length. 

@pwalm 

![screenshot 2016-06-01 16 07 39](https://cloud.githubusercontent.com/assets/8496249/15728918/90d05fde-2814-11e6-97c7-86d260906d06.png)

**Comment by pwalm** [comment]
Can you delete the stuff in the brackets?

**Comment by andymckay-limited-access** [comment]
Also that blue icon doesn't look great with the blue background.

**Comment by devaneymoz** [comment]
I cannot change the title, of which the parenthetical is a part.

**Comment by pwalm** [comment]
@andymckay-limited-access Don't mention the blue background :/

**Comment by andymckay** [comment]
You could get the add-on author to do that (or with their permission we could change it).

**Comment by devaneymoz** [comment]
I'm not entirely comfortable getting into the habit of asking authors to change their add-on titles to accommodate our limited featuring capabilities. Perhaps for this isolated case, but how tricky is the fix to be able to stretch titles to two lines? Because I'm certain we'll run into this issue again.

**Comment by andymckay** [comment]
We might but by then we might have a completely new design. I certainly think its acceptable to ask an author to change things for the value of being on the front of the home page rather than being infinitely flexible in something we might be deleting.

**Comment by devaneymoz** [comment]
If we go the route andymckay suggests is there any way I can get a hard character count for titles so I know before publishing time if a title needs adjusting?

**Comment by andymckay** [comment]
The dev tools are your friend.

https://www.dropbox.com/s/ja5md54s0hnq6jv/Screenshot%202016-06-02%2017.17.27.png?dl=0

Looks like 19 characters.

**Comment by devaneymoz** [comment]
Okay, thanks. I'll reach out to see if the author won't abide.

**Comment by devaneymoz** [comment]
For the record though that's a really tiny character count. We'll encounter this issue frequently I'm afraid. Big gap between infinite flexibility and 19 characters. Redesign!
