### ISSUE TITLE
Update add-on rating text to be infinitive rather than imperative

### ISSUE THREAD

**Issue by SeanPrashad** [mozilla/addons-frontend#4995]
### Describe the problem and steps to reproduce it:
As per [this comment](https://github.com/mozilla/addons-frontend/pull/4693#issuecomment-388758954) found in #4693, we should remove the trailing period as it makes the rating string instructive/imperative rather than infinitive, which affects a number of localizations.

Simply hover over the rating portion on any add-on details page to see the tooltip at large.

### What happened?

The tooltip shows `"Rate this add-on / Update your rating to %(thisRating)s out of 5."`

### What did you expect to happen?

The tooltip should show `"Rate this add-on / Update your rating to %(thisRating)s out of 5"` (_note the period has been removed!_)

### Anything else we should know?
The source code to be modified can be found here:

https://github.com/mozilla/addons-frontend/blob/9ef46f3f0adfd716ffc39f61d03d7804aa6d57da/src/ui/components/Rating/index.js#L55-L73

**Comment by muffinresearch** [comment]
@SeanPrashad thanks for filing + fixing this 👍

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10) The "." was removed 

![fixed](https://user-images.githubusercontent.com/33448286/40063713-9de0eb4c-5866-11e8-98b7-60d8ab698c48.png)
