### ISSUE TITLE
Add a edit link to user profile page when it makes sense

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#4997]
The user profile page should have a link to the edit page when:

1. the current viewed profile is the current logged-in user's profile
2. the current logged-in user has permission to edit a user profile (admin or user with `Users:Edit` permission)

Does that make sense? If so, where should we put this link?

We could maybe add a text link below the "report" button:

![screen shot 2018-05-15 at 11 58 36](https://user-images.githubusercontent.com/217628/40050348-765374e8-5837-11e8-8b30-fa5e076ba00d.png)

**Comment by willdurand** [comment]
mmh I just stumbled upon @pwalm's comment with mock-ups: https://github.com/mozilla/addons-frontend/issues/2749#issuecomment-355688372

Can you quickly confirm that we will have a second button bellow the "report" button? Maybe we could hide the "report" button for the profile of the current logged-in user though? (but we will have to keep it for admins, therefore there will be two buttons, stacked)

**Comment by willdurand** [comment]
Ok I went ahead and added a new button below the "report" one.

**Comment by pwalm** [comment]
Two buttons stacked in admin view is fine, since it's a special case for a more advanced user.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64 and Android 7.0

**Regular user**
 [1] Logged In
![image](https://user-images.githubusercontent.com/31961530/40309262-89cb41b6-5d11-11e8-8dba-6cf97cb01c59.png)

 [2] Logged out
![image](https://user-images.githubusercontent.com/31961530/40309267-8fea05b4-5d11-11e8-93cc-99a5c232e358.png)

**Admin user**
[1] Profile view
![image](https://user-images.githubusercontent.com/31961530/40309315-b5ace8e8-5d11-11e8-977e-f09ff8704291.png)

[2] Edit view
![image](https://user-images.githubusercontent.com/31961530/40309332-bed26600-5d11-11e8-84a7-978ad899f8df.png)
