### ISSUE TITLE
Redirect user to profile page when profile has been updated?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#4998]
When a user edits their profile and clicks "update", the current behavior is to display a "success" message and to stay on the same (edit) page. It is the behavior on the legacy frontend as well.

Should we change that? For instance, we could redirect the user to their profile once updated.

**Comment by pwalm** [comment]
Correct: Clicking update should just take you to the profile page.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10&Android 8.0)
![update profile](https://user-images.githubusercontent.com/33448286/41278989-f09946b2-6e33-11e8-8894-8c6008c3b082.gif)
