### ISSUE TITLE
Clicking the theme image in the disco pane should trigger the install

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#4999]
### Describe the problem and steps to reproduce it:
* Go to the disco pane in about:addons 
* Click the theme image

### What happened?

* A hand icon is shown indicating a click should do something.
* Nothing

### What did you expect to happen?

* On clicking the image the theme should install

**Comment by willdurand** [comment]
> On clicking the image the theme should install

@muffinresearch do we expect anything when a theme is installed and we hover the theme image?

**Comment by muffinresearch** [comment]
> @muffinresearch do we expect anything when a theme is installed and we hover the theme image?

On the disco pane this will should show a preview until #4914 is landed.

**Comment by willdurand** [comment]
@muffinresearch yes, but one it is installed. What do we want? I have #4914 running locally, and there is still a hand icon once the theme has been installed.

**Comment by willdurand** [comment]
> @willdurand On the disco pane this will should show a preview until #4914 is landed.

@muffinresearch ok, but what should we expect when hovering the current installed/used theme? It still displays a hand icon.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10).
As @willdurand mentioned above the current installed theme will continue to display the hand icon.

@muffinresearch If the click does the install for a theme does it mean that the install button will be removed?

![click and install](https://user-images.githubusercontent.com/33448286/40663266-f93ee0a2-6360-11e8-9897-f97aff4d6f0e.gif)

**Comment by muffinresearch** [comment]
@ioanarusiczki no it's just an additional method for install. It used to be this way but at some point this behaviour regressed.

**Comment by AlexandraMoga** [comment]
@rebmullin @muffinresearch this wasn't working for me in prod. Could you please have a look?

**Comment by rebmullin** [comment]
@AlexandraMoga  clicking on the image DOES install the theme for me..
does anything happen?

Hey @muffinresearch, can you verify if it's working for you?

**Comment by AlexandraMoga** [comment]
@rebmullin it's working for me today as well, but it definitely didn't work yesterday after the push.  Maybe it needed some more time to synchronize.

**Comment by muffinresearch** [comment]
> @rebmullin @muffinresearch this wasn't working for me in prod. Could you please have a look?

@AlexandraMoga The disco pane has specific explicit caching on the HTML of 1 hour. Whenever testing after a push it's a good idea to append a query parameter to the `extensions.webservice.discoverURL` in `about:config` to bust the cache and be sure you're testing the latest version of all the code. /cc @rebmullin
