### ISSUE TITLE
Add notification settings in user profile edit page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5000]
Users should be able to edit their notification settings on the user profile edit page:

<img width="513" alt="notifs" src="https://user-images.githubusercontent.com/217628/40051670-e5b1ad06-583b-11e8-9d5c-5cd1ab38a151.png">

**Comment by willdurand** [comment]
This feature depends on https://github.com/mozilla/addons-server/issues/8286.

**Comment by willdurand** [comment]
Also I will not be able to ship this one next week (some parts might land though).

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF60 win10x64 and Android 7.0

Users are able to select/deselect notification options when updating their profiles. Notification options are also displayed in accordance to the type of user (i.e regular user or developer) 

![notif user](https://user-images.githubusercontent.com/31961530/41045107-5a6bd59c-69b0-11e8-88ec-104f65a0e2d6.gif)


@willdurand I've noticed that the Notifications component seems to be the only one that loads somewhat independently from the rest of the sections. Also, in the loading state it appears to be loading fewer notification options. I am just wondering if there is anything that can be done to improve this aspect. On the legacy pages for example, I can't see this behavior.

**Comment by willdurand** [comment]
> @willdurand I've noticed that the Notifications component seems to be the only one that loads somewhat independently from the rest of the sections.

Yes, because we have to retrieve the notifications data separately.

> Also, in the loading state it appears to be loading fewer notification options.

Yes, we chose to display only 2 "loading notifications" because users who are not developers won't have more than 2 notifications.
