### ISSUE TITLE
URL to add a collection is invalid (it conflicts with -prod URL)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5004]
### Describe the problem and steps to reproduce it:

We have a user called `add` in -prod, we can browse their collections here: https://addons.mozilla.org/en-US/firefox/collections/add/.

### What happened?

The current route to add a collection in the new frontend is:

```
/collections/add/
```

This conflicts with the link to the list of the collections of the user mentioned above.

The legacy frontend uses the following URL:

```
/collections/add
```

(without a trailing slash)

### What did you expect to happen?

The URL to add a collection on the new frontend should be: `/collections/add`.

### Discussion

The new frontend should, at least, use the same URL as the legacy app but **a completely different URL** that does not conflict with users' collections would be ❤️ 
What do you think? Can we change the URL to something different than the legacy frontend?

**Comment by bobsilverberg** [comment]
I think we could change the URL to something different, but, as @eviljeff pointed out, /collections/{username}/ will never be a URL in the new frontend that points to anything, because you cannot list the collections belonging to another user. So I think this can be closed.

**Comment by willdurand** [comment]
Indeed, and the current logged-in user will be able to browse their collections on any URL, it won't have any impact.
