### ISSUE TITLE
Allow `callApi` to send form data

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5012]
The `callApi` helper transforms the `body` parameter into a JSON string and forces the `content-type` to be `application/json`. In order to [upload a profile picture](https://addons-server.readthedocs.io/en/latest/topics/api/accounts.html#uploading-a-picture), we need a way to send form data (`multipart/form-data`) (see #4276).

https://github.com/mozilla/addons-frontend/blob/5d5103ab4ba76d4b1e0be476af1c98e91d353c0f/src/core/api/index.js#L86-L98

My proposal is to allow `FormData` instances and JS objects as `body`, because the API allows to send both files and other data (fields) at the same time.

**Comment by vcarciu** [comment]
Please add some STRs to this bug or mark it as "qa: not needed"

**Comment by willdurand** [comment]
oops sorry @vcarciu, added "qa: not needed"
