### ISSUE TITLE
Static themes show an 'Add to Firefox' button instead of an 'Install Theme' button on theme details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5015]
STR:

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/green-space2/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/green-space2/
3. Compare the 'Install' button for the two themes

Actual result:
Static theme detail page shows an 'Add to Firefox' button 

Expected result:
Static theme detail page shows an 'Install Theme' button

Note:
- reproduced on AMO-dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40111446-8bedd2d8-590b-11e8-8101-a6944ceef1cb.png)

**Comment by rebmullin** [comment]
@jvillalobos - same thing here, right : ) keeping with the "theme" version of "Install Theme" (Vs "Add to Firefox")?

**Comment by jvillalobos** [comment]
Yup, "Install Theme".

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF60, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/40914114-998b5034-67ff-11e8-8127-f4344718bc01.png)
