### ISSUE TITLE
'About this add-on' card should be renamed to 'About this theme' on static theme details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5016]
STR:

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/green-space2/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/green-space2/
3. Compare the 'About this xxxx' card for the two themes

Actual result:
The card title in static theme details page is "About this add-on"

Expected result:
The card title in static theme details page is "About this theme"

Notes:
- reproduced on AMO-dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40111940-160aa954-590d-11e8-95ef-f24d93f272b3.png)

**Comment by rebmullin** [comment]
@jvillalobos per your notes here: REF: https://github.com/mozilla/addons-frontend/issues/4899#issuecomment-385553081, we should keep "About this theme" (vs "About this add-on"), right?

**Comment by jvillalobos** [comment]
It should be "About this theme", yes.

**Comment by championshuttler** [comment]
@rebmullin , I would like to work on it

**Comment by willdurand** [comment]
@championshuttler please go ahead!

**Comment by championshuttler** [comment]
@willdurand , I need a little help.
I was going through the code and I checked there is no field like Static theme in `src/core/constants.js`
So we need to create a ADDON_TYPE_STATIC_THEME and then import it to `src/amo/components/Addon/index.js` and then write a new case for static theme here `https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Addon/index.js#L303`

**Comment by rebmullin** [comment]
hey @championshuttler  - I am working on the static theme updates/issues. Maybe we can find you another issue to work on? :)

**Comment by championshuttler** [comment]
@rebmullin sure 😀

**Comment by rebmullin** [comment]
thanks @championshuttler : )

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF60 WIn10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/40913588-c16df216-67fd-11e8-953e-247c92aa7181.png)
