### ISSUE TITLE
'More themes by author' card is not correctly positioned in static theme details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5017]
STR

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/my-first-sentence/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/my-first-sentence/?src=rating
3. Compare the 'More...by this author' cards for the two themes

Actual result:
'More...by this author' card in Static theme details page is displayed at the bottom and the title says 'More **add-ons** by this author'

Expected result:
'More...by this author' card in Static theme details page should be moved where the 'Screenshots' section is positioned now  and the title should say 'More **themes** by this author'

Notes:
- reproduced on AMO-dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40112600-3aca166a-590f-11e8-9646-ee6f2ff6d956.png)

**Comment by bobsilverberg** [comment]
It seems like we need some discussion / details about exactly how we are going to handle static themes. They *are* extensions, and not themes, but do we want to treat them like that on the front end? Maybe this discussion has already happened, and I just missed it.

**Comment by rebmullin** [comment]
same thing here ...I think the "mockups" are to follow the design of the current theme (LWT) - REF: https://github.com/mozilla/addons-frontend/issues/4899#issuecomment-385553081. My understanding is to keep the theme wording and placement of things the same as much as possible (without vertically cropping)

// cc @jvillalobos  please correct me if i am wrong

**Comment by jvillalobos** [comment]
Same as https://github.com/mozilla/addons-frontend/issues/5018, yes.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60 Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/40913180-73e54176-67fc-11e8-8879-ee0921af71b4.png)
