### ISSUE TITLE
Static theme preview should be positioned similar to LWT preview in theme details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5018]
STR:

1. Log in to AMO-dev and go to a static theme details page - see https://addons-dev.allizom.org/en-US/firefox/addon/my-first-sentence/
2. Open the same LWT theme's detail page on AMO stage - https://addons.allizom.org/en-US/firefox/addon/my-first-sentence/?src=rating
3. Compare the two theme previews

Actual result:
Static theme preview is displayed in a Screenshots section which doesn't clearly mark the theme design as the main focus on the theme details page

Expected result:
Static theme preview should be displayed in the same card LWT are currently displayed; also, the Screenshots section shouldn't really be present on the ST detail page

Notes:
- reproduced on AMO dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40113039-bb286dc4-5910-11e8-8da3-a2e8db5a6587.png)

**Comment by bobsilverberg** [comment]
This seems valid. I know supporting static themes on the front end is something new. Do we have issues open for it? Are there mockups for exactly how they should look?

**Comment by rebmullin** [comment]
I think the "mockups" are to follow the design of the current theme (LWT) - REF: https://github.com/mozilla/addons-frontend/issues/4899#issuecomment-385553081

// cc @jvillalobos  please correct me if i am wrong

**Comment by jvillalobos** [comment]
Yes, the layout should be as close as possible to current lwt. Not sure if the issues to work on this have been filed already. /cc @eviljeff

**Comment by eviljeff** [comment]
Correct.  The only difference with the preview vs. lwt header is UX defined the size as exactly as 680 x 92 (as of mozilla/addons-server#8248).  Frontend displays something between 770 x 90 and 630 x 90 now, depending on if there are badges, (the actual header image is 680 x 100) but the static theme preview shown on the detail page shouldn't be cropped (and ideally shouldn't be scaled either).

(The "thumbnail" of the preview is smaller and to be used on list results, shelves, etc, and can be cropped at the right hand size)

**Comment by rebmullin** [comment]
how should we handle the header in mobile / smaller devices? Is this okay to scale here or should we use the same height and cut the right side off? 

regarding "shelves" - where can i see that? Is that this multi column view:
![Alt text](https://monosnap.com/image/dCuLndowhikqmNr5UZlfzNbvdzqPf5.png)

or something different?

@jvillalobos @eviljeff

**Comment by jvillalobos** [comment]
I believe that on mobile we show the full image height and crop on the left when needed. Shelves are the multi column view, yes. You can also see them on the AMO homepage.

**Comment by eviljeff** [comment]
with the static theme previews the cropping is on the right (from the svgs UX have created - see zip in of mozilla/addons-server#8248).

**Comment by AlexandraMoga** [comment]
I'm marking this issue as verified fixed on AMO-dev with FF60, WIn10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/40910750-a557aba6-67f5-11e8-92b6-f7920079f8c4.png)

![image](https://user-images.githubusercontent.com/31961530/40910759-acd6ac24-67f5-11e8-8204-206b811a0b92.png)
