### ISSUE TITLE
View Profile page does not display location and occupation - only the old page does

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5019]
STR:
1. Load AMO dev and log in with an account then go to Edit my profile page.
2. Fill in all the fields from Profile section and click Update my profile button.
3. Click View my profile and observe the section below the user/display name.

Expected result:
Homepage, Location and Occupation are displayed on View profile page.

Actual result:
Only the homepage is displayed as information.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).
It is not reproducible with the old view.

![location occupation](https://user-images.githubusercontent.com/33448286/40114348-3e52bbb0-5915-11e8-87c8-69c2866082c3.gif)

**Comment by willdurand** [comment]
I guess it is a feature for now, the profile page does not display such information on purpose and I dont see anything in the mock-ups.

**Comment by bobsilverberg** [comment]
Well, if we're not going to display it, why bother collecting it? Seems like one of those two should change.

**Comment by willdurand** [comment]
It might be related to #4964.

**Comment by bobsilverberg** [comment]
Heh, yeah it might be, but I'm still not sure what #4964 is about either. 🤷‍♂️
