### ISSUE TITLE
Allow unbroken strings in Biography to be wrapped on View Profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5020]
STR:
1. Load AMO dev and login with an account then go to Edit my profile.
2. In the biography field insert a long unbroken string then click Update my profile.
3. Click on View Profile.
4. Observe the text below average ratings.

Expected result:
Text is wrapped.

Actual result:
Text is not entirely displayed and appears cut.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).

![biography - long unbroken strings](https://user-images.githubusercontent.com/33448286/40115111-05877c3c-5918-11e8-88a6-792a2e3b3c46.gif)

**Comment by dominictwlee** [comment]
I'll take a look at this and see what I can do.

**Comment by willdurand** [comment]
Thanks @dominictwlee!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10)

![biographytext](https://user-images.githubusercontent.com/33448286/40415309-44709468-5e83-11e8-9ff5-65f59940c83d.png)
