### ISSUE TITLE
A Server error page is displayed if user logs out on the Edit Profile page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5034]
STR:

1. Log in to AMO-dev
2. Select Edit my Profile from the user menu
3. On the Edit Profile page, click on Log out

Actual result:
A Server error is displayed when the user logs out while being on the Edit Profile page

Expected result:
User is redirected back on AMO homepage when he logs out on the Edit Profile page

Notes:
- reproduced on AMO-dev, with FF60, Win10x64

![server error](https://user-images.githubusercontent.com/31961530/40220524-17ec3e42-5a82-11e8-8edc-9dc51f15116a.gif)

**Comment by willdurand** [comment]
Ah thanks for this bug report, I guess it is the same as #5036. We'll see if my patch fixes both.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF60, Win10x64

When logging out on the Edit profile page, the user is now redirected to the Log in page:

![prof logout](https://user-images.githubusercontent.com/31961530/40491455-c48fb950-5f76-11e8-952e-6f5482c2f8e8.gif)


@willdurand you mentioned in the pull request that the button should be called "Log in to continue" but when I'm testing this I see that the button is called "Log in to edit the profile" Have you re-decided on the naming in the meantime?
