### ISSUE TITLE
On a user profile page the star ratings title should be updated if there are no ratings yet

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5042]
### Describe the problem and steps to reproduce it:
Go to "View My Profile" or find another user's profile.
Find a user that does not have any ratings on their add-ons yet.
If you hover over the stars ratings, it says "The add-on has not been rated yet" 

### What happened?
If you hover over the stars ratings in this scenario, it says "The add-on has not been rated yet"

### What did you expect to happen?
It should say something like ~ "There are no ratings yet" if there are no ratings yet

### Anything else we should know?
![Alt text](https://monosnap.com/image/41o3uJoT4uDyEIumzgDbHvuf5RU1Pf.png)

**Comment by championshuttler** [comment]
@rebmullin I would like to work on it

**Comment by willdurand** [comment]
@championshuttler that works for me, although I think you have a Pull Request in progress, right?

**Comment by championshuttler** [comment]
@willdurand  yeah i think it will work

**Comment by willdurand** [comment]
Thank you @championshuttler!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10).
![no ratings yet](https://user-images.githubusercontent.com/33448286/40308556-4abe5636-5d0f-11e8-9746-fbba7b8b5ddf.png)
