### ISSUE TITLE
Recommendations are empty for some add-ons.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5044]
### Describe the problem and steps to reproduce it:
* Go to https://addons-dev.allizom.org/en-US/firefox/addon/bloody-vikings/
* Note the empty recommendations block. Note the fallback should be shown for all legacy add-ons.

### What happened?
<img width="1057" alt="bloody_vikings__ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/40244160-ffe4237c-5ab9-11e8-96df-64b3aeb8abf1.png">

### What did you expect to happen?

Show the fallback add-ons.

**Comment by willdurand** [comment]
The API response is:

```json
{
    "count": 0,
    "fallback_reason": null,
    "next": null,
    "outcome": "recommended",
    "page_count": 1,
    "page_size": 1,
    "previous": null,
    "results": []
}
```

**Comment by muffinresearch** [comment]
Yep looks like this is only happening when cohort cookie is `TAAR_COHORT_INCLUDED`

**Comment by muffinresearch** [comment]
Re-filed at https://github.com/mozilla/addons-server/issues/8300
