### ISSUE TITLE
Add additional custom dimension on AMO for A/B testing

### ISSUE THREAD

**Issue by mlopatka** [mozilla/addons-frontend#5045]
The dimension is currently described in GA360 analytics as:

> Experiment participant

`var dimensionValue = 'SOME_DIMENSION_VALUE'; ga('set', 'dimension5', dimensionValue);`

Where value should be set to 

> TAAR-LITE-AB

for all page visitors. this will help to track the subset of visitors over time who participated in the study. The existing custom dimension is still needed to track experimental branch.

further details available [here](https://docs.google.com/document/d/1xrx2mxh3oCw-6AFoCqmNsXwc4xeqLROSBK9Z58z3A2I/edit?ts=5af33bd3#)

**Comment by mlopatka** [comment]
@muffinresearch I can not set priority on this.

**Comment by willdurand** [comment]
@mlopatka what is the priority for this issue?

**Comment by mlopatka** [comment]
@willdurand P1

**Comment by willdurand** [comment]
ack, working on this now.

**Comment by AlexandraMoga** [comment]
@willdurand I have looked in the console and I can see now that there are two dimensions listed: `"dimension4"`, value: `"TAAR_COHORT_INCLUDED"` and `"dimension5"`, value: `"TAAR-LITE-AB"`

Is there anything else we could check for this issue?

![image](https://user-images.githubusercontent.com/31961530/40292627-0118d180-5cd5-11e8-9928-08dd5d261fc4.png)

**Comment by willdurand** [comment]
> Is there anything else we could check for this issue?

No, it is all good.

**Comment by AlexandraMoga** [comment]
Marking issue as verified fixed on AMO-dev, FF60, Win10x64
