### ISSUE TITLE
Static themes are missing from the user profile page

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5048]
### Describe the problem and steps to reproduce it:
find a user with static theme and view their user page, e.g:
https://addons-dev.allizom.org/en-US/firefox/user/ValentinaDDD/
or 
https://addons-dev.allizom.org/en-US/firefox/user/rebdev-test/ (it might be a little to see here since there are currently less things added)

### What happened?
The static theme doe not appear in the either section of the user profile list:
![Alt text](https://monosnap.com/image/UXKuDA0ZmbzThW5j39g5GX9Lw59ulF.png)

### What did you expect to happen?
This should also appear in the themes section

### Anything else we should know?
REF: https://github.com/mozilla/addons-frontend/issues/4899#issuecomment-385553081

**Comment by ioanarusiczki** [comment]
@rebmullin Hei Rebecca, I think this is already tracked here https://github.com/mozilla/addons-frontend/issues/4810 This is a dupe.
