### ISSUE TITLE
Feature: opportunity to not see recommendations

### ISSUE THREAD

**Issue by birdsarah** [mozilla/addons-frontend#5049]
Assuming all is well and we continue on with displaying recommendations to folks.

We could provide an x "stop showing recommendations" and hide the recommendation box (presumably we'd have to set a cookie to store this preference). If we tracked this we could maybe use this as a way to detect any signals of people being upset with recommendations.

**Comment by muffinresearch** [comment]
I've marked this a p3 to put this on the backlog. I would envisage we'd be able to to look at this after the all-hands, though there's nothing blocking us working on this sooner if the feature is behind a flag so it doesn't impact the study.

**Comment by willdurand** [comment]
I believe this is not on our backlog anymore.
