### ISSUE TITLE
The Edit Profile form is loaded when the page is accessed with a non-existent user

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5056]
STR:

1. Log in to AMO-dev
2. Access the edit profile URL with a non-existent username (i.e. https://addons-dev.allizom.org/en-US/firefox/user/no-username-here-bro/edit/)

Actual result:
The page returns a 404 error, but the Edit profile form is diplayed

Expected result:
The standard 'Page not Found' should be displayed when the edit profile URL is accessed with a non-existent user

Notes; reproduced on AMO-dev, with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40295345-a433017c-5ce1-11e8-975f-9500363ed60f.png)

**Comment by willdurand** [comment]
I think this will be fixed by https://github.com/mozilla/addons-frontend/pull/5039

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO-dev with FF60, Win10x64

![profile edit 404](https://user-images.githubusercontent.com/31961530/40545576-0161cf8a-6035-11e8-9db0-ca95384758a5.gif)
