### ISSUE TITLE
The underscore is interpreted as hyhen on Create a collection new form

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5057]
STR:
1. Load AMO dev and access the new create a collection form. https://addons-dev.allizom.org/en-US/firefox/collections/add/
2. Type in a name that contains "_" and observe the Custom URL while it autocompletes

Expected result:
Custom URL displays the "_"

Actual result:
Custom URL displays "-" instead of "_"

Notes:
This issue is reproducible on AMO dev with FF60(Win10).

![underscore copied as hyphen](https://user-images.githubusercontent.com/33448286/40298671-974980ac-5cec-11e8-909c-6bfe757e1c1d.gif)

**Comment by willdurand** [comment]
Do we actually have instructions on this? I find legit to use hyphens in collection slugs.

**Comment by ioanarusiczki** [comment]
@willdurand Yes, both underscores and hyphens are allowed but when the underscore is typed in the "Name" field the hyphen shows up  - with autocomplete - in the Custom URL.  Please take a look at the .gif above.

**Comment by willdurand** [comment]
I saw it, I wonder if it would make sense to transform underscores like hyphens.

**Comment by tsl143** [comment]
We have implemented that anything except numbers and alphabets will be converted to `-`. Moreover hyphens in URLs are always SEO friendlier than underscores (https://www.woorank.com/en/blog/underscores-in-urls-why-are-they-not-recommended)

**Comment by bobsilverberg** [comment]
> We have implemented that anything except numbers and alphabets will be converted to -. Moreover hyphens in URLs are always SEO friendlier than underscores (https://www.woorank.com/en/blog/underscores-in-urls-why-are-they-not-recommended)

I think it's okay to keep it as is. This is just a prefill, so a user could change it back to an underscore if it's really important to them that the URL have an underscore instead of a hyphen. That's my opinion anyway.

**Comment by willdurand** [comment]
I second @bobsilverberg's opinion, closing this issue as wontfix now. Feel free to comment/reopen if you think we should really change this behavior.
