### ISSUE TITLE
User profile card is loaded briefly when the page is accessed with a non-existent user

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5060]
STR:

1. Log in to AMO-dev
2. Access the user profile page with a non-existent user (see https://addons-dev.allizom.org/en-US/firefox/user/no-username-here-bro/)

Actual result:
The user profile card will load for a brief moment before the "Page not found" is displayed

Expected result:
"Page not found" is displayed at the instant when the profile page is accessed with a non existent user

Notes:
- reproduced on AMO-dev with FF60, Win10x64

![profile load](https://user-images.githubusercontent.com/31961530/40293897-afc4d4a8-5cdb-11e8-8b91-9a72c4999c14.gif)

**Comment by AlexandraMoga** [comment]
@willdurand I'm still reproducing this on -dev. I think that after two hours I should  be able to see the fix in -dev. Do you know if there were any deployment issues that would prevent that?

**Comment by willdurand** [comment]
@AlexandraMoga there were issues earlier today, but that should be deployed now.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO dev with FF60, Win10x64

![no user correct](https://user-images.githubusercontent.com/31961530/40356863-137febee-5dc3-11e8-9a1d-8a13d994ba84.gif)
