### ISSUE TITLE
Truncate long text in "View profile" page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5062]
Steps to reproduce:
1.Go to https://addons-dev.allizom.org/en-US/firefox/users/edit
2.Add long text in all fields under "Profile section" and save the updates
3.Click the "View my profile" link

Expected results:
The text from "View profile" page is truncated

Actual results:
Text is not truncated

Please see a video of this bug : 
![truncate](https://user-images.githubusercontent.com/1583842/40313080-52569d32-5d1d-11e8-93e6-38844407fd04.gif)

**Comment by willdurand** [comment]
Isn't it related to #4584?

**Comment by vcarciu** [comment]
Verified as fixed : 
![trunc](https://user-images.githubusercontent.com/1583842/40428876-f9b8e372-5ea9-11e8-8688-cb2172a44ef4.png)
