### ISSUE TITLE
Button should be named "Edit user's profile" when another account can be edited by an admin

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5072]
STR:
1. Load AMO dev and login with an admin account
2. View any other profile page - here's an example https://addons-dev.allizom.org/en-US/firefox/user/AnaTestUsernameadmin/
3. Observe the Edit profile button

Expected result:
"Edit user's profile" button is displayed.

Actual result:
"Edit profile" button is displayed.

Notes:
While logged in to view a personal account of any type when "Edit profile" button is clicked the Edit profile page displays "View My Profile" and "Edit my profile". When an admin views another account there is View user's profile and Edit user's profile, therefore the button that redirects to edit profile page should be "Edit user's profile".

![edit user s profile](https://user-images.githubusercontent.com/33448286/40367761-d4fcfb12-5de2-11e8-9e12-9bf571d2b334.gif)

**Comment by willdurand** [comment]
> therefore the button that redirects to edit profile page should be "Edit user's profile".

I don't think it needs to be changed for that use case. Not a lot of users have the right to edit other profiles anyway and the copy on this button works for everyone, so I am not really inclined to change it.

**Comment by ioanarusiczki** [comment]
@willdurand I just thought that it would be more clear for the admin too if "user's" is added and also because the edit profile page already mentions the "user's".
forgot to mention above - it's reproducible on AMO dev with FF60(Win10)

**Comment by willdurand** [comment]
I understand but the other page has a different copy. This neutral text works in both case, so I guess that's fine.

**Comment by ioanarusiczki** [comment]
@willdurand I agree it could work both ways, this was a suggestion (enhancement) as it could improve the UX but on the other hand an admin knows the pages better than anyone else.

**Comment by willdurand** [comment]
Yup, I am closing this issue for now because, as you said, "an admin knows the pages better than anyone else" 😉
