### ISSUE TITLE
Update install tracking to special case static themes

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5073]
The lightweight theme (LWT) installation uses its own API but static themes will be installed in the same way as extensions are. 

We'll need to special case the install events to not just use the "addon" action for static themes. 

One question is, should we special use something other than `theme` for the action so that we can tell static-themes apart from LWTs or just use `theme` for continuity?

**Comment by jvillalobos** [comment]
I think it would be good to be able to tell them apart. Both stats can be added together if there's a need for an "all themes" stat, right?

**Comment by vcarciu** [comment]
@rebmullin : can you please add some STRs for QA or mark the issue as "qa: not needed" ?

**Comment by rebmullin** [comment]
hey @muffinresearch, can you advise/assist? should QA be verifying this? or what's the best way to have this verified?

Basically the following event updates were made:
persona:
eventCategory: "AMO Theme [install category]"
eventAction: "theme"

static theme:
eventCategory: "AMO Theme [install category]"
eventAction: "addon:statictheme"

extension:
eventCategory: "AMO Addon [install category]"
eventAction: "addon"

you should see something like this in the console (for persona): `[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Theme Installs Started","eventAction":"theme","eventLabel":"MegaFox"}`

**Comment by muffinresearch** [comment]
@vcarciu if you install a static theme you should see the Analytics beacons fired reflecting the data shown above.

@rebmullin was there a reason to prefix `statictheme` with `addon:` that prefix feels like it might be redundant?

**Comment by vcarciu** [comment]
Verified as fixed : "[amo] [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Theme Installs Started","eventAction":"addon:statictheme","eventLabel":"RM static Pink theme"}"

**Comment by rebmullin** [comment]
@muffinresearch , I can change that but it was originally to differentiate between the install of an extension but I guess category does that now too...

is it possible there could be other kinds of themes down the line? maybe in that way it could be a useful distinction. Otherwise, I can take that out...

**Comment by willdurand** [comment]
It is a bit weird that only static themes have a prefix now.

**Comment by muffinresearch** [comment]
> @muffinresearch , I can change that but it was originally to differentiate between the install of an extension but I guess category does that now too...

Yeah I think `statictheme` is clear enough. Can you remove the `addon:` prefix? I've filed an new issue for that [here](https://github.com/mozilla/addons-frontend/issues/5578).

**Comment by rebmullin** [comment]
sure thing
