### ISSUE TITLE
31 May homepage content programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#5075]
For the **31 May** push, please find homepage content updates detailed [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#).

@muffinresearch @diox @bobsilverberg

**Comment by ioanarusiczki** [comment]
Full validation will be done in AMO dev with FF60(Win10)
@bobsilverberg I verified the banners and all sections and noticed that compared to what's in the [document](https://addons.mozilla.org/en-US/firefox/collections/mozilla/essential-extensions/)
on AMO dev when See more link is clicked for Change Up Your Tabs, Essential Extensions and Translation Tools, they are displayed with uppercase letters and contain en dashes.

AMO dev 
![essential-extensions](https://user-images.githubusercontent.com/33448286/40541808-1095b354-6026-11e8-800d-b9b77fc6a3e7.png)

**Comment by willdurand** [comment]
@ioanarusiczki I think Bob created the collections in -dev for testing purpose, if the links have the correct URLs, it is enough. In -prod, we will have the correct content for each collection, but I don't think -dev needs to have the exact same collection title and/or description.

**Comment by bobsilverberg** [comment]
What @willdurand says above is accurate, @ioanarusiczki. The concern you raised is not an issue that needs to be addressed.
