### ISSUE TITLE
Combined theme (lw and static) results are not displayed together on the AddonsByAuthorsCard (on addon detail page)

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5077]
### Describe the problem and steps to reproduce it:
go to a static theme detail page:
https://addons-dev.allizom.org/en-US/firefox/addon/rm-static-theme-3/?src=search

or go to lwt detail page:
https://addons-dev.allizom.org/en-US/firefox/addon/rm-test-new-theme/?src=search

you will only see "more themes" of that same type 

### What did you expect to happen?
if an author has different types of themes it should be combined here

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10)

![lw and static themes combined](https://user-images.githubusercontent.com/33448286/41782617-6bfa7fb2-7643-11e8-813e-143b66ae6012.gif)
