### ISSUE TITLE
Combined lightweight and static theme results when filtering by theme in search

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5078]
### Describe the problem and steps to reproduce it:
when you search for an addon and then filter by Theme, static themes are not included in the results. 

### What did you expect to happen?
static themes will be included in the Theme filter results

also make sure come up on the home page, any landing pages and in its respective category

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10). 
General search, Category search, and also checked the search from add-ons manager - extension tab.

AMO search
![general search](https://user-images.githubusercontent.com/33448286/41974220-0849f44e-7a20-11e8-81d8-78eb84e3aef4.gif)

Searched by category
![search by category](https://user-images.githubusercontent.com/33448286/41974280-32c8c722-7a20-11e8-92e2-c2b6f701a3c5.gif)
