### ISSUE TITLE
Display issues for the ToolTip when hovering over it - the new collection form

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5081]
STR:
1. Load AMO dev and login with a new account that has a username such as anonymous-ada73ef9cabf810cf119216caf409f5b and click the new collection form https://addons-dev.allizom.org/en-US/firefox/collections/add/
2. Mouse hover over the Custom URL and observe the URL displayed
3. Go to edit profile page and edit your username then go back to the new collection form
4. Mouse hover over the Custom URL and observe the ToolTip

Expected result:
The ToolTip displays the URL correctly.

Actual result:
Some extra spaces and slashes - doesn't look right.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).

When the username is anonymous-ada73ef9cabf810cf119216caf409f5b
![the generated username](https://user-images.githubusercontent.com/33448286/40424693-f22a8d00-5e9e-11e8-8eaa-b1155563dd55.png)

And when the username is edited
![edited username](https://user-images.githubusercontent.com/33448286/40424713-fee758d4-5e9e-11e8-9ec2-d62ac2f14dfc.png)

**Comment by willdurand** [comment]
Thanks for your first contribution @mirefly! /cc @caitmuenster
