### ISSUE TITLE
Add-on recommendations card could end up recommending the same extension the user is currently viewing

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5082]
STR:

1. Open AMO homepage and select an extension to view its details page (i.e. https://addons.allizom.org/en-US/firefox/addon/ublock-origin/?src=recommended_fallback)
2. Look for the recommendations card on the add-on details page

Actual result:
The extension the user is currently viewing is also listed among add-on recommendations

Expected result:
The recommendations card should not display an add-on currently viewed by the user

Notes:
- this situation could occur when the user receives `fallback` or `curated` results;
- Cc @muffinresearch to give his input on this possible situation
- reproduced on AMO-dev and stage with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/40427041-3d36d5e6-5ea5-11e8-86cf-2759a189ab68.png)

**Comment by bobsilverberg** [comment]
I recall that we discussed this and decided to punt on it for now, as it only affects the curated/fallback scenario, and curated will go away once the experiment is over. We should keep this issue open, but I don't think we plan on fixing it right away.

**Comment by muffinresearch** [comment]
@AlexandraMoga as @bobsilverberg says, the TAAR team are aware of this scenario and we're not going to fix it for this test to avoid the possibility of skewing the control.
