### ISSUE TITLE
Update flow type for TAAR recommendation fallback reasons

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5084]
The flow type `FallbackReasonType` is outdated because of a recent change on addons-server, we should update it according to this documentation section: https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#recommendations.

**Comment by championshuttler** [comment]
Can i take this up ;)

**Comment by bobsilverberg** [comment]
Certainly @championshuttler, go for it, and thanks!

**Comment by muffinresearch** [comment]
Mentor: @willdurand 

@championshuttler if you have any questions let will know.

**Comment by championshuttler** [comment]
Hi @muffinresearch , I got stuck in my University exams 😓, will back in a week ;)

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed'?
Thank you

**Comment by willdurand** [comment]
ooops, sorry added "qa: not needed", thanks!
