### ISSUE TITLE
Cosmetic changes to non-Firefox install button

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5086]
This is a follow-up to issue #4872.

As reported by @MeridelW:

Recommending small adjustments to the button copy here:
-Replace en dash with an em dash
-Remove spaces around em dash
-Remove exclamation point

So, new button copy would be:
**Only with Firefox—Get Firefox Now**

I synced with @atsay on this and she approved new version. Pretty minor changes so I assume we don't need to do any testing?

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10)
![cosmetic improvements](https://user-images.githubusercontent.com/33448286/40533907-e0344bda-600c-11e8-8fe1-f473e4892fb2.png)
