### ISSUE TITLE
Update docs instructions in "Developing with a local server"

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5099]
### Describe the problem and steps to reproduce it:
go to: http://addons-frontend.readthedocs.io/en/latest/moz-addon-manager/#developing-with-a-local-server

the instructions show a patch that is needed to get this fully working but some of this code shown here is outdated:
![Alt text](https://monosnap.com/image/SIhOXvhu8112aOXnwOgESCAnFCoC73.png)

### What happened?
since some of the patch is outdated, you have to do a variation of this to get it to work.

**Comment by willdurand** [comment]
ah oops. I missed this issue, sorry!
