### ISSUE TITLE
Lets use SRI

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#51]
https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

SRI will ensure that the JS we get from the server is the JS we expect

**Comment by muffinresearch** [comment]
We should take a look at what tools are available to automate this. For example this looks interesting from the webpack angle but there's others:

https://www.npmjs.com/package/sri-stats-webpack-plugin

Also this applies to other statics too, e.g. CSS.

**Comment by jonathanKingston** [comment]
Hey Both,

There is a Mozilla-ish project that was used as part of: https://www.srihash.org/ called: https://github.com/neftaly/npm-sri-toolbox

It's robust in that it's being used under the hood for Ember right now. I can probably help with writing some other form of automation using the toolbox if you need something.
