### ISSUE TITLE
Rating Manager component text should be updated for static theme type

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5102]
### Describe the problem and steps to reproduce it:

**(once static theme is added as a valid addon type - see PR #5067)
make sure you're logged out
find a static theme addon: eg: https://addons-dev.allizom.org/en-US/firefox/addon/rm-static-theme-3/?src=search
![Alt text](https://monosnap.com/image/oy2i4FQtraOp7XWVueDpbFkH7s8K5j.png)

### What did you expect to happen?
expect if on env where static themes are enabled text to be correct (match lwt/persona type text) 

### Anything else we should know?
see somewhat related issue #3601 - also error handling error should be looked at too as noted in the issue

**Comment by willdurand** [comment]
@rebmullin we have to add the "contrib: assigned" label when an issue has been fixed by a contributor 😉

**Comment by rebmullin** [comment]
hey @willdurand, thanks for adding and for the tip : )

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF60, WIn10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/41144364-5adcd3f4-6b05-11e8-8d72-a1559bd5eab0.png)
