### ISSUE TITLE
Profile picture is too little in "View my profile page"

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5106]
Steps to reproduce:
1.Open a profile page after uploading a new photo

Expected results:
Picture size is big enough to distinguish the photo details

Actual results:
Picture size is too little

NOTES:
Not sure about the size from specs, but I am not able to distinguish any details from the picture.

Please see screenshot for this bug : 
![picture](https://user-images.githubusercontent.com/1583842/40547310-40d3fe54-603a-11e8-804c-e79ba7d414ec.png)

**Comment by willdurand** [comment]
> Not sure about the size from specs, but I am not able to distinguish any details from the picture.

Spec size is 64x64 max.

**Comment by vcarciu** [comment]
@willdurand : can we ask if we can increase the size?

**Comment by willdurand** [comment]
@vcarciu sure, but do we need two issues or we can do everything in #5107?

**Comment by vcarciu** [comment]
@willdurand : you are right, we can do everything in #5107

**Comment by willdurand** [comment]
@vcarciu can we close this one then?

**Comment by vcarciu** [comment]
Sure
