### ISSUE TITLE
Portrait pictures are cropped off in profile view page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5107]
Steps to reproduce:
1.Try to update your profile by adding a portrait picture
2.Go to view profile page

Expected results:
Entire photo is displayed

Actual results:
Picture is cropped

NOTES:
Related to #4276 

Please see a video for this bug : 
![cropped](https://user-images.githubusercontent.com/1583842/40547976-0c80f45c-603c-11e8-9564-9a1ecafb095f.gif)

**Comment by willdurand** [comment]
The API crops the uploaded images indeed, I think it is a wanted behavior. Is it different on the legacy frontend?

**Comment by willdurand** [comment]
Right. I don't know what to do, though.

Should we keep the ratio or have squared/cropped profile pictures?

/ping @pwalm

**Comment by ioanarusiczki** [comment]
This was also filed for old page too https://github.com/mozilla/addons-frontend/issues/4629

**Comment by aastha980** [comment]
@willdurand I want to work on this issue , can you please tell me where can i find the main code for this issue ?

**Comment by willdurand** [comment]
@aastha980 unfortunately there is nothing we can do for this issue yet, it would be better if you could find another issue. We have labels for contributor-friendly issues ("good first bug").

**Comment by AlexandraMoga** [comment]
@willdurand maybe it is not the best user experience but since this is in accordance with the specs I guess this can be closed.

**Comment by ioanarusiczki** [comment]
Another example with FF64 - Win 10 I used a 300 KB , Height 912 pixels, Width 394 pixels

![image](https://user-images.githubusercontent.com/33448286/50697571-4522a200-104b-11e9-859f-3053f056e248.gif)
