### ISSUE TITLE
Different search results after page refresh when sorting by 'relevance' or 'hotness'

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5108]
STR:

1, Make a blank search on AMO -dev 
2. Sort the search results by relevance - https://addons-dev.allizom.org/en-US/firefox/search/?sort=relevance
3. Refresh the page
4. Observe the search results again

Actual result:
A different set of results is displayed after page refresh

Expected results:
The same results are displayed after page refresh

Notes:
- reproduces also when sorting by 'hotness'
- refiled from [add-ons-server/issue#3571](https://github.com/mozilla/addons-server/issues/3571#issuecomment-392060352)
- reproduced on all AMO servers with FF60, Win10x64

![sort-relev](https://user-images.githubusercontent.com/31961530/40548128-819a59a4-603c-11e8-8578-4721547d4fbb.gif)

**Comment by willdurand** [comment]
I don't think it is a frontend issue because we do not do much here, we only display the results coming from the API.
