### ISSUE TITLE
React developer tools stopped working

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#511]
The react developer tools extension for Firefox and Chrome has stopped working. It used to work on older version of the site but it no longer does. I'm not sure what broke it.

**Comment by muffinresearch** [comment]
It appears to work if you disable SSR. Not sure what the root cause is though.

**Comment by muffinresearch** [comment]
<img width="717" alt="discover_add-ons_and_discover_add-ons" src="https://cloud.githubusercontent.com/assets/1514/15775834/169de682-297c-11e6-9395-5cadb4fb6863.png">
