### ISSUE TITLE
Broken Link from Twitter 

### ISSUE THREAD

**Issue by sewcraftyme** [mozilla/addons-frontend#5110]
### Describe the problem and steps to reproduce it:
I did a search in Duck Duck Go for Shorten a Link for Twitter

It gave me a link to this page - among others:
https://twitter.com/shortenurl

I picked the link above because it mentioned it was an add-on for Firefox. 
![broken link for add on](https://user-images.githubusercontent.com/27222252/40557816-5e5b6158-601f-11e8-8d3f-4db666e064dd.JPG)

I clicked the link at https://twitter.com/shortenurl 
for the add on for Firefox since its the browser I prefer

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/shorten-url/

Is where the link took me and asked me to report a broken link which I am doing.  I would love to have a link shortener for Firefox as I post a lot of links on Twitter and it would make my life so much easier.

Thank you. 

Ila in Maine
mailto:sewcraftyme@gmail.com

**Comment by willdurand** [comment]
This add-on has probably been removed. /cc @wagnerand

**Comment by wagnerand** [comment]
Yes, like the screenshot says: "This add-on has been removed by its author."

**Comment by willdurand** [comment]
> Yes, like the screenshot says: "This add-on has been removed by its author."

Oh, I did not know we had that.. Sorry, I did not pay attention to the message :/
