### ISSUE TITLE
Users reducer should store username in lowercase (in `byUsername` attribute)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5118]
### Describe the problem and steps to reproduce it:

Browse a user profile with a username that has been stored with capital letters in database, for example `Madonna` but use `madonna` in the URL: http://localhost:3000/en-US/firefox/user/madonna/ (in -dev).

### What happened?

The profile is not loaded and is stuck in an inconsistent state (loading mode).

### What did you expect to happen?

The profile is successfully displayed if the user exists, otherwise 404. In this case, the user does exist.

The problem comes from the `users` reducer not storing the usernames in lowercase in the `byUsername` attribute, which implies lookup problems as the one described above.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10). 

My steps were:
1. Created a new account and edited it like Anonymous2301. 
2. Went to a tab pasted the URL like this https://addons-dev.allizom.org/en-US/firefox/user/anonymous2301/

Another test:
1.  Renamed for an already existing account the username as CONTdedisplaytestadmin
2.  Copied the link went to a new profile and pasted the URL as https://addons-dev.allizom.org/en-US/firefox/user/contdedisplaytestadmin/

![uppercaselowercase](https://user-images.githubusercontent.com/33448286/40657216-b085f910-634f-11e8-8ce3-b69bced4a81e.gif)
