### ISSUE TITLE
Report this add-on for abuse

### ISSUE THREAD

**Issue by EffPeh** [mozilla/addons-frontend#5121]
### Describe the problem and steps to reproduce it:

Today I reported an add-on abuse for the first time. I wasn't sure if a popup with advertising text and a link to a website (it's spam for me) violated the policies. So I clicked the link to [_Mozilla's add-on policies_](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy)

### What happened?
Even the first paragraph is irritating for normal users:

> Mozilla is committed to ensuring an excellent experience for both our users and developers of add-ons. Please review the policies below before submitting your add-on.

What? I'm here to report abuse. So what's this now?

The first and the third link will take you to a 404-page.
[Developer Agreement](https://developer.mozilla.org/Mozilla/Add-ons/AMO/Policy/Agreement)
[Featured Add-ons](https://developer.mozilla.org/Mozilla/Add-ons/AMO/Policy/Featured)

The linked page of  [_Review Process_](https://developer.mozilla.org/de/Add-ons/AMO/Policy/Reviews) is too technical for normal users and doesn't offer any information about spam. I think. My English isn't the best either. 

### What did you expect to happen?
I expect a uncluttered single page that explains clearly what Mozilla means by abuse. And preferably not only in English. In many cases, anything else could lead to frustration and abandonment of the action.

### Anything else we should know?

[_Mozilla's add-on policies_](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy)
[_Review Process_](https://developer.mozilla.org/de/Add-ons/AMO/Policy/Reviews)

Broken Links:
[Developer Agreement](https://developer.mozilla.org/Mozilla/Add-ons/AMO/Policy/Agreement)
[Featured Add-ons](https://developer.mozilla.org/Mozilla/Add-ons/AMO/Policy/Featured)

**Comment by jvillalobos** [comment]
> Broken Links:
> Developer Agreement
> Featured Add-ons

Those links work for me. Can you check again? Can you look at the URL of the 404 pages and make sure they're the same you posted here?

As for linking to the policies, the idea is that add-ons that don't meet those policies should be reported, which seems clear from what's stated when you click on the Report Abuse button. Maybe @caitmuenster or @MeridelW have other opinions on this point.

**Comment by EffPeh** [comment]
> Those links work for me. Can you check again? Can you look at the URL of the 404 pages and make sure they're the same you posted here?

Yes, I'm sure. Have a look... :)
![404-1](https://user-images.githubusercontent.com/296535/40626249-ab011b66-62b7-11e8-8246-c391915ddf61.JPG)
![404-2](https://user-images.githubusercontent.com/296535/40626258-b48152c8-62b7-11e8-93be-8381796d6f8b.JPG)
Maybe it's a locale problem. I'm from Germany.

> As for linking to the policies, the idea is that add-ons that don't meet those policies should be reported, which seems clear from what's stated when you click on the Report Abuse button. Maybe @caitmuenster or @MeridelW have other opinions on this point.

Okay. Are you sure this is the view of any inexperienced user? ;)
And what about spam? The extension I reported was just advertising. No benefit for a user.

**Comment by EffPeh** [comment]
If I go to the English version of the extension page, I have the same problem. 
Let's say I'm on _https: // addons.mozilla.org/**en-US**/firefox/addon/extension-I-want-to-report/_
If I click the link to _Mozilla's add-on policies_ there, I will be directed to the English version.
But if I click on the link to _Developer Agreement_ there, I also get to the German 404 page.

**Comment by jvillalobos** [comment]
We're linking to the en-US version of the policy index page directly, probably because that's the only version we know is up-to-date. I suppose MDN throws a 404 when it figures out your browser wants a different language and the page doesn't exist in it...

Maybe we should just link directly to the [policy page (in English)](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews), which is more useful in this context, and should bypass the bad link issue. @caitmuenster, what do you think?

**Comment by EffPeh** [comment]
> Maybe we should just link directly to the policy page (in English), which is more useful in this context, and should bypass the bad link issue.

Maybe. But the pages in other languages should have the same content. That's not the case here. If I follow your link and change the language to German, I get a different content - in English. ;)

**Comment by caitmuenster** [comment]
Thanks for reporting this issue, @EffPeh! I agree that linking to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy from the abuse report box was pretty clunky. 

[The AMO Policy Page](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy) seems more focused on developers and doesn't look like a good place for users to land. I'd prefer to have them land directly on the [Review Policies](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews) page, which makes sense given the prompt when a user goes to report abuse. 

We updated the [policy page in English](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews) in April, and it looks like those changes did not carry over to the localization pages.  I can copy/paste the updated English text over to the other pages and request localization on the updates. I'm not entirely sure how we can account for this in the future but happy to investigate.

**Comment by wagnerand** [comment]
@caitmuenster Maybe it makes sense to create a dedicated page about user reviews policy. I agree with the statement in the original comment that "The linked page of Review Process is too technical for normal users and doesn't offer any information about spam." That page is targeted to add-on developers.

> I can copy/paste the updated English text over to the other pages and request localization on the updates.

I would prefer if we instead deleted the localized page content and redirected those to en-US. The localized pages will often be out of date, and we cannot verify that their content is accurate. Both can have a significant negative effect on developers, trying to submit their add-on.
(Remember that the official policy went through extensive review from various departments inside Mozilla, including Security, Privacy and Legal. I learned that every word in there needs to be reviewed because some general statements can imply liability, for example.)

I can understand that developers would like to read the policies in their language. We could potentially allow localized versions, but they would have to start with a very prominent disclaimer that the localized version is not authoritative and link to the en-US version. And if developers are told not to rely on the localized version, I am wondering how much sense it makes to have them at all.

**Comment by EffPeh** [comment]
Thank you all for looking at the problem. :)
I also think that linking to _review policies_ is the best solution. At the moment. ;)
But I also hope that a German translation will be available as soon as possible, because I know that many, especially older Germans have problems with the English language.

> Maybe it makes sense to create a dedicated page about user reviews policy.

I agree with that. 
_Review Policies_ is okay for the moment, but there are still many points incomprehensible to the normal user. Sometimes the user cannot judge the situation at all.

**Comment by jvillalobos** [comment]
Wrong button, sorry.

**Comment by caitmuenster** [comment]
Summary: 
Currently, the "report abuse" link goes to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy. 

[Good First Bug - Abuse Report .pdf](https://github.com/mozilla/addons-frontend/files/2054760/Good.First.Bug.-.Abuse.Report.pdf)

We want to change this link to go to https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews (note: we want to direct link to the en-US link) 

Mentor: @willdurand 

If this is If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by Gabbyjose** [comment]
Hi there, I'm interested in helping out with this if it's still available!

**Comment by caitmuenster** [comment]
Hey @Gabbyjose! Go for it! If you need any help, please feel free to ping @willdurand. :)

**Comment by Gabbyjose** [comment]
Thanks @caitmuenster! @willdurand, what's the best way to reach you? should i sign up for IRC? i'm reading the docs now and i've never used Docker before so i want to get that set up first

**Comment by willdurand** [comment]
@Gabbyjose you can write here or email me at <my github username>@mozilla.com.

You do not need docker I think, only node 8 and yarn. Once you have both, you can run `yarn` followed by `yarn amo:dev` in the project root directory. After a while, you'll have the website running at http://127.0.0.1:3000/.

**Comment by willdurand** [comment]
Thanks for your first contribution @Gabbyjose!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev and AMO stage with FF60(Win10).

![new link for policies](https://user-images.githubusercontent.com/33448286/41089162-d4cd4e9e-6a49-11e8-9902-686544a5399c.gif)
