### ISSUE TITLE
Create a user notifications component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5127]
In order to allow a user to view/edit their notifications, we need a notifications component that is able to display such notifications with `input[type="checkbox"]` and a loading state (when notifications are not fetched from the API yet).

**Comment by ioanarusiczki** [comment]
I've noticed  and filed two issues on AMO dev, FF60 (Win10)   
https://github.com/mozilla/addons-frontend/issues/5137
https://github.com/mozilla/addons-frontend/issues/5139

**Comment by ioanarusiczki** [comment]
@willdurand Well then, in case we find other issues I'll let you know by updating this.

**Comment by willdurand** [comment]
> @willdurand Well then, in case we find other issues I'll let you know by updating this.

Up to you but if you can see notifications and check/uncheck the checkboxes (even if it does not update on submit), then this issue is done. It is only about UI, nothing more here. The big issue for this feature is #5000

**Comment by willdurand** [comment]
@ioanarusiczki would something like this work for you?

<img width="731" alt="screen shot 2018-05-31 at 11 45 57" src="https://user-images.githubusercontent.com/217628/40778190-3aec8884-64c8-11e8-9369-573422711308.png">

**Comment by ioanarusiczki** [comment]
@willdurand Way better, I will file a separate issue then.
