### ISSUE TITLE
personas plus is not working , I can't change themes or add new ones. i uninstalled personaas & now i cant even install the add on again . every time i try to do anything wiht it i get this: 

### ISSUE THREAD

**Issue by peaches67** [mozilla/addons-frontend#5129]

**Comment by peaches67** [comment]
Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.

**Comment by muffinresearch** [comment]
@peaches67 please can you provide more information? This sounds like an issue with personas plus but you also mention a server error. Can you provide the URL you're on when you see this message?

**Comment by willdurand** [comment]
Duplicate of #5116
