### ISSUE TITLE
themes wont work at all

### ISSUE THREAD

**Issue by peaches67** [mozilla/addons-frontend#5130]

**Comment by peaches67** [comment]
cannot install any theme . everytime i try i get this: Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it. and it has been doing this for a long time

**Comment by jvillalobos** [comment]
This is a duplicate of https://github.com/mozilla/addons-frontend/issues/5116, so I'm closing this one. Can you please comment on that issue with the exact steps that lead to that error?
