### ISSUE TITLE
An admin cannot add extensions into a collection created by another user on the new frontend

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5136]
STR:
1. Load AMO dev and login with an admin account
2. Search for a collection created by another user and try to edit it by adding a new item https://addons-dev.allizom.org/en-US/firefox/collections/willdurand/foo1234/edit/
3. Observe the page

Expected results:
Extension or theme selected is added to the collection.

Actual result:
Not found message is displayed.

Notes:
This is not reproducible for the old pages. Also removing extensions or editing the text fields work.
This is reproducible on AMO dev with FF60(Win10).

![add to a collection - admin](https://user-images.githubusercontent.com/33448286/40712496-8cba54ec-6406-11e8-9345-f5c55d6c20c4.gif)

**Comment by willdurand** [comment]
Do admins need an "edit" access if they cannot edit collections?

**Comment by jvillalobos** [comment]
I don't think admins need to be able to do that. Deleting a collection, yes, but not editing. Per https://github.com/mozilla/addons-server/issues/6273#issuecomment-326025262, we have a way for admins to set contributors for internal collections, which is the only use case for collaborative editing we need to support.

**Comment by bobsilverberg** [comment]
Sorry to ask again, @jvillalobos, but I realized, after asking my question, that we do have code in place specifically to allow admins (or anyone with the `Collections:Edit` permission) to edit collections, so I want to be totally clear before removing that.

Do you want me to remove the code that allows users who are not the owner to maintain collections? That would mean they could not:
- edit the details of a collection.
- add an add-on to a collection.
- remove an add-on from a collection.
- maintain the notes for an add-on in a collection.

As you described above, someone with the `Collections:Edit` permission would still be able to delete a collection.

**Comment by bobsilverberg** [comment]
As per issue #5162, admins should not be allowed to edit a collection in any way.
