### ISSUE TITLE
Unchecking notifications is not working - new pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5139]
STR:
1. Load AMO dev and login with an account then go to Edit my profile page
2. Uncheck the available options from Notifications and click Update my profile
3. Observe the screen

Expected result:
Options are displayed as being unchecked.

Actual result:
Profile successfully updated is displayed but notification section won't display the list of options.

Notes:
This issue is reproducible clicking Update my profile without unchecking the box too - the notification section is no longer displayed correctly.
Refreshing page will display again the list with all options unchecked.
It is not reproducible with old pages.
Reproducible on AMO dev with FF60(Win10). 

![uncheck and update](https://user-images.githubusercontent.com/33448286/40725068-27c8d9f8-642b-11e8-9e3f-0c16948239be.gif)

**Comment by willdurand** [comment]
Indeed, we can only see the notifications for now but not edit them. This will be possible once #5128 is merged.
