### ISSUE TITLE
Consistently use one user identifier in collections reducers and sagas

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5142]
While working on the "Delete a collection" feature, I discovered that we are inconsistently using either the string `username` or the numeric `userId` in different reducer and saga methods, and I see no reason to do so. All of the APIs are designed to accept either a numeric `userId` or a string `username`, and both are guaranteed to be unique to an individual user. We should update our code to either always use `userId` or always use `username` to remove the inconsistency and resulting confusion in the codebase.

**Comment by bobsilverberg** [comment]
For QA:

There shouldn't be any noticeable changes from this, but it touched a lot of collections code, so it's probably a good idea to quickly verify that collections are still working as expected. It probably makes sense to verify this at the same time as issue #5164.

**Comment by ioanarusiczki** [comment]
Collection seem to be working fine - no new issues found
This is verified fixed on AMO dev with FF60(Win10&Android 8.0)
