### ISSUE TITLE
Link to Manage Firefox Accounts is missing from the Edit profile page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5146]
STR

1. Log in to AMO-dev
2. Click on Edit profile from the user menu
3. Check the data available on the Account card

Actual result:
There is no link to redirect the user on the Manage Firefox Account page

Expected result:
A link to Manage Firefox Account should be present on the edit profile page. This was a useful feature that was available on the legacy pages. 

Notes:
- reproduced on AMO dev with FF60 Win10x64

![image](https://user-images.githubusercontent.com/31961530/40772508-cc156452-64c8-11e8-869f-7c26b6944a38.png)

**Comment by willdurand** [comment]
Mock-up: <img width="925" alt="screen shot 2018-05-31 at 10 08 49" src="https://user-images.githubusercontent.com/217628/40773381-a41ca8f6-64ba-11e8-8546-143dbad15dd7.png">

**Comment by rishabh-bansal** [comment]
Hey! This is my first time, how can I get started?

**Comment by willdurand** [comment]
> Hey! This is my first time, how can I get started?

Let's start with #5145 first 😉

**Comment by dominictwlee** [comment]
I'll give this a go :), will report back within a week.

**Comment by willdurand** [comment]
@dominictwlee interested in contributing on this issue?

**Comment by dominictwlee** [comment]
@willdurand Sure, I should have a bit of time over the weekend to take a look at this.

**Comment by dominictwlee** [comment]
@willdurand What link are you precisely referring to for manage firefox accounts? 
[(https://www.mozilla.org/en-GB/firefox/accounts/)]?

**Comment by willdurand** [comment]
@dominictwlee I think it is https://accounts.firefox.com/settings

**Comment by AlexandraMoga** [comment]
Verified on AMO-dev with FF60, Win10x64 and Android 7.0

An issue regarding link redirection was fond and filed separately - see #5390

[1] edited user logged in
![image](https://user-images.githubusercontent.com/31961530/41850723-4e0c1266-788e-11e8-8c4d-5310148d969d.png)

[2] edited user logged out
![image](https://user-images.githubusercontent.com/31961530/41850740-5ed137a2-788e-11e8-9b40-3fe786735b5e.png)
