### ISSUE TITLE
Hide "Dictionaries and Language Packs" page on Android

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#5150]
In the future Firefox for Android might support some sort of language packs, but at the moment it doesn't. As pointed out in https://bugzilla.mozilla.org/show_bug.cgi?id=1462689 at best they do nothing, at worst they break about:addons. In https://github.com/mozilla/addons-server/issues/8381 we are going to make langpacks incompatible with Firefox for Android, so ultimately they won't show up in the "Dictionaries and Language Packs" page...

... But dictionaries are actually not that much more useful in Android. As far as I can tell installing one doesn't break anything, but doesn't do anything either. The only place where there is spellchecking in Firefox for Android seems to be the keyboard, which is not controlled by Firefox.

So, unless I'm wrong, I think the link to "Dictionaries and Language Packs" page should not be displayed for Android, and we should add a warning in that page if accessed through Android (in both cases, instead of doing UA sniffing inside the page, just checking that we're in a /android/ URL should be enough)

**Comment by 78760611** [comment]
我没用这个浏览器  我现在语言不全  没有中文

**Comment by muffinresearch** [comment]
@diox could we just 404 the /%LOCALE%/android/language-tools/ route? As well as remove the link?

**Comment by diox** [comment]
> @diox could we just 404 the `/%LOCALE%/android/language-tools/` route? As well as remove the link?

Yeah I think so.

**Comment by vcarciu** [comment]
@diox : should we remove the link from legacy frontend Android Add-ons page too?

**Comment by willdurand** [comment]
> could we just 404 the /%LOCALE%/android/language-tools/ route? As well as remove the link?

@muffinresearch this is currently implemented in addons-frontend, would it make sense to do it at the nginx level?

**Comment by muffinresearch** [comment]
> @muffinresearch this is currently implemented in addons-frontend, would it make sense to do it at the nginx level?

The appserver really needs handle this to display something doesn't it?

**Comment by willdurand** [comment]
> The appserver really needs handle this to display something doesn't it?

ah right, but I thought nginx could maybe internally redirect to `/404/`.

**Comment by muffinresearch** [comment]
> ah right, but I thought nginx could maybe internally redirect to /404/.

Probably doesn't buy us enough to be worth special-casing.

**Comment by willdurand** [comment]
Fair enough.

**Comment by vcarciu** [comment]
Verified as fixed : 
![nolangpack](https://user-images.githubusercontent.com/1583842/41970247-c95b1900-7a12-11e8-83ce-78d342d622f3.png)
