### ISSUE TITLE
Add a confirmation step before deleting a profile picture

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5151]
### Describe the problem and steps to reproduce it:

1. As a logged-in user, edit your profile
2. Make sure you have uploaded a profile picture
3. Click "delete this picture" below the profile picture

### What happened?

The profile picture is deleted.

### What did you expect to happen?

A confirmation step would be nice to avoid deletion by accident.

### Anything else we should know?

We should create a `ConfirmButton` component for this use case, so that we can reuse it elsewhere.

**Comment by ioanarusiczki** [comment]
verified fixed on AMO dev with FF60(Win10)
I filed https://github.com/mozilla/addons-frontend/issues/5188
