### ISSUE TITLE
Only allow the owner of a collection to edit it

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5162]
As per the conversation in yesterday's meeting, only the owner of a collection (or collaborators in the case of a Mozilla collection) should be allowed to edit the collection. This issue is to remove the code that supports allowing an administrator to edit a collection.

**Comment by vsnehil92** [comment]
@bobsilverberg i would like to work on this issue

**Comment by bobsilverberg** [comment]
@vsnehil92 Sure, go right ahead.

The code that needs to change is in `Collection/index.js`, specifically [lines 344-347](https://github.com/mozilla/addons-frontend/blob/cf064079110aa0406daf36f0e2b90a2442cb9608/src/amo/components/Collection/index.js#L344-L347).

Some tests for the Collection component, which are in [`TestCollection.js`](https://github.com/mozilla/addons-frontend/blob/cf064079110aa0406daf36f0e2b90a2442cb9608/tests/unit/amo/components/TestCollection.js), will also need to be changed and/or removed.

**Comment by vsnehil92** [comment]
@bobsilverberg  Thanks I am on it, if i need any help I'll ask you.

**Comment by vsnehil92** [comment]
@bobsilverberg  I am able to see the collections on the main website but i am not able to view those on my localhost. May you please help.

**Comment by bobsilverberg** [comment]
@vsnehil92 Which website are you looking at, and what command are you using to start the site locally? The two have to match, so I would suggest using https://addons-dev.allizom.org/en-US/firefox/ to view the live site, and starting the site locally with `yarn amo:dev`.

**Comment by vsnehil92** [comment]
![image](https://user-images.githubusercontent.com/20948883/41213196-3d771e74-6d61-11e8-9d50-78a1969ef038.png)
My collection on local host is showing this, I have reverted back my canges to main master still i can't see the page

**Comment by bobsilverberg** [comment]
This was fixed via #5163.
