### ISSUE TITLE
Support allowing collaborators to edit a Mozilla collection

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5163]
Depends on ~~https://github.com/mozilla/addons-server/issues/8509~~

As documented in the above issue, there will be one permission that indicates that a user can edit any Mozilla-owned collection, as well as a permission that indicates that a user can edit one particular Mozilla-owned collection.

**Comment by vcarciu** [comment]
Collections can now be edited by users with permissions. I will mark this issue as verified and a follow up issues was logged separately : https://github.com/mozilla/addons-frontend/issues/5499
