### ISSUE TITLE
Consistently use slug as the name for collection slugs, except for modify collection

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5164]
This is similar to issue #5142. I discovered, when working on the "edit the notes for a collection add-on" function that we inconsistently use the variable names `slug` and `collectionSlug` in api, reducer and saga code to refer to the slug of a collection.

We can just use `slug` in all cases, except for modifying a collection itself, because in that case there may be an old slug and a new slug.

This issue is to change all of the code to just use `slug` unless there is a need to also have a `collectionSlug`.

**Comment by bobsilverberg** [comment]
For QA:

There shouldn't be any noticeable changes from this, but it touched a lot of collections code, so it's probably a good idea to quickly verify that collections are still working as expected. It probably makes sense to verify this at the same time as issue #5142.

**Comment by ioanarusiczki** [comment]
Collection seem to be working fine - no new issues found
This is verified fixed on AMO dev with FF60(Win10&Android 8.0)
