### ISSUE TITLE
Right-cropping theme previews will hide important elements in the theme design

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5173]
Follow up for #5067 

STR:
1. Load AMO-dev homrpage (https://addons-dev.allizom.org/en-US/firefox/)
2. Examine the Featured Themes shelf

Actual result:
The cropped theme previews are hiding important elements from the theme design

Expected result:
The user should be able to see a more complete representation of the theme design when looking at the Featured themes shelf

Notes:
- the same behavior is visible on Theme's homepage and in More themes by artist card (present on theme details page and in User profile page)
- it is also the design used for smaller screen sizes
- maybe a good point to address in https://github.com/mozilla/addons-server/issues/8412
- reproduced on AMO-dev with FF60, Win 10x64 and Android 7.0

[1] AMO homepage
![image](https://user-images.githubusercontent.com/31961530/40905914-02cbb52e-67e8-11e8-8ab8-9be516159d8b.png)

[2] Theme homepage
![image](https://user-images.githubusercontent.com/31961530/40905924-09b8036a-67e8-11e8-9d82-fe317e2d6f9f.png)

[3] More themes by author card
![image](https://user-images.githubusercontent.com/31961530/40905941-1335bedc-67e8-11e8-981f-8b1a25b17637.png)

**Comment by muffinresearch** [comment]
LWTs need to be right aligned and when truncated they should lose the left side of the image.

**Comment by muffinresearch** [comment]
Marked as P1 since this will break display of lightweight themes once this change hits production.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF60, Win10x64 and Android 7.0

[1] AMO homepage
![image](https://user-images.githubusercontent.com/31961530/40962648-c652f63a-68ae-11e8-8a71-23de3de664c8.png)

[2] Theme homepage
![image](https://user-images.githubusercontent.com/31961530/40962670-d5ba4420-68ae-11e8-869a-b938b3eda993.png)

[3] More themes by author card
![image](https://user-images.githubusercontent.com/31961530/40962703-ee3150c0-68ae-11e8-8d1d-9ea6e498d204.png)
