### ISSUE TITLE
Static themes: Cropping makes it hard to tell what you're going to get at small viewports

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5174]
Maybe there's a limit to what can be done here but as viewport sizes decrease it gets harder to see enough of a static theme preview to be useful.

This is going to be particularly an issue with LWTs that are converted, because they rely on right-aligned images.

URL: https://addons-dev.allizom.org/en-US/firefox/search/?platform=mac&q=static+theme

Here's a mobile size viewport:

![screen shot 2018-06-04 at 10 22 07](https://user-images.githubusercontent.com/1514/40909445-77aa89d0-67e1-11e8-809c-33d2615d6dfa.png)

Here's a wider view on the same data:

![screen shot 2018-06-04 at 10 24 46](https://user-images.githubusercontent.com/1514/40909497-93601a00-67e1-11e8-8db2-31a68720ff83.png)

Do we have alternative images that we can show at mobile viewports?

**Comment by muffinresearch** [comment]
This will need some discussion as to how to best handle this.

**Comment by rebmullin** [comment]
Per our discussion at all-hands and [addons-server-issue-8412](https://github.com/mozilla/addons-server/issues/8412), I think we are a good place with this, i.e. we are going to get some new images sizes and scale down if necessary by adjusting the css - which I've started in [this PR](https://github.com/mozilla/addons-frontend/pull/5225).

**Comment by rebmullin** [comment]
also additional notes from discussion at all-hands:

implement srcset once the additional sizes are ready:
mozilla/addons-server#8412 (comment)

Update themes grid in the following places:
Homepage,
Themes landing,
Category landing
Note for above pages: 
desktop: change from 4 to 3 col grid
~tablet: change from 4 to 2 col grid
~mobile: should be 1 col - should already be this way


AuthorsAddoncards,
Note for above component: 
desktop: change from 3 to 2 col grid
landscape tablet: change from 3 to 2 grid
portrait tablet && mobile: should be 1 col - should already be this way

**Comment by rebmullin** [comment]
note: we are holding off on srcset to further discuss. Will update this PR # shortly..

**Comment by rebmullin** [comment]
note for QA:

disregard srcset (per my notes above - a follow up PR will happen if that is needed)

make sure columns match what i've above (except note for tablet grids - on home, landing and cat pages, we are not able to switch the results so it is still 3 here)

make sure images aren't cropped

please double check nothing is broken or looks off

also note some static themes will have the older sizes so you may want to create new ones to get the most updated sizes (some discussion about that [here](https://github.com/mozilla/addons-server/issues/8412#issuecomment-400049143))

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64 and Android 8.0

1. Below are the new previews:

**Homepage**

[Desktop]
![image](https://user-images.githubusercontent.com/31961530/43137086-75d695e2-8f53-11e8-93dd-d6b690803bec.png)

[Tablet]
![image](https://user-images.githubusercontent.com/31961530/43137250-06326eea-8f54-11e8-8105-1f8774504031.png)


[Mobile]
![image](https://user-images.githubusercontent.com/31961530/43137111-854fbada-8f53-11e8-987f-e8b0cc721cd6.png)

**Themes landing/ Categories**

[Desktop]
![image](https://user-images.githubusercontent.com/31961530/43137164-b0135cfe-8f53-11e8-946b-70c4bbcc423d.png)
[Mobile]
![image](https://user-images.githubusercontent.com/31961530/43137193-d0dba8ce-8f53-11e8-8a4a-758c482e7676.png)

**More Themes by author**

{Desktop]
![image](https://user-images.githubusercontent.com/31961530/43137218-ea4a00ee-8f53-11e8-8312-8e298bd06f2a.png)

[Mobile]
![image](https://user-images.githubusercontent.com/31961530/43137281-1fbd8d2c-8f54-11e8-9900-1ab6cbdbb3e1.png)

2. No vertical cropping observed

![image](https://user-images.githubusercontent.com/31961530/43137405-7b383c1a-8f54-11e8-896d-2c802eb48ae2.png)

3. Question from @rebmullin 

I've noticed that there is a difference in height between lwt and static themes. Is there a reason behind that?

![image](https://user-images.githubusercontent.com/31961530/43137570-c0730120-8f54-11e8-9e7c-f2963e289642.png)

**Comment by rebmullin** [comment]
@AlexandraMoga,

Regarding question 3 - here are the full sizes that we are scaling down on the shelves:

lwt size: 680 x 100

new static theme size: 760 x 92

old static theme size: 680 x 92

So right now you will see various heights (which of course includes when they are scaled down). You could even see a height discrepancy if you see an older static theme next to a new version - if that makes sense - b/c ultimately they will scale a little differently if they have different dimensions.

I believe this should change after migration and everything has the same size. 

Does that help?

I didn't see a question 1 or 2...let me know if I am missing something : )

**Comment by AlexandraMoga** [comment]
@rebmullin thanks for your answer. Your explanation make sense. When all the lwt will be migrated we will only have one size to scale from, which means that in production there won't be any size discrepancy. 

This was my only question.

Marking issue as verified fixed.
