### ISSUE TITLE
Add Flow type for users API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5177]
The user API does not have Flow types for the return values. We started to add
return types for collections, and we should be doing this for all APIs.

**Comment by Gabbyjose** [comment]
hey will, i'd be interested in taking a stab at this ticket if it's ready for contributors. let me know!

**Comment by Gabbyjose** [comment]
thank you Will! I've never used Flow personally but it seems rather similar to React PropTypes which I've used. I'll look at the documentation and let you know if I have any questions

**Comment by ioanarusiczki** [comment]
@willdurand Could you please add qa not needed for this one or perhaps there might be something we could check ?

**Comment by willdurand** [comment]
@ioanarusiczki sorry, added "qa: not needed" label
