### ISSUE TITLE
Header image on theme detail page needs be right aligned

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5181]
### Describe the problem and steps to reproduce it:
similar to #5173 but seen in header (especially mobile).
this isn't so much an issue at desktop but is more evident in mobile/smaller viewport

### What happened?
lightweight themes are left aligned

### What did you expect to happen?
lightweight themes should be kept right aligned

left aligned:
![Alt text](https://monosnap.com/image/VXejTgjNZXL9YmEvZfrOzghk4lZQHB.png)

vs right aligned:
![Alt text](https://monosnap.com/image/qKtTaYGKn3IfUIw1hA1f8BDXsfbwH3.png)

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/40963378-0198ebc6-68b1-11e8-8bee-13ca6b89a9ca.png)
