### ISSUE TITLE
Add-on type filter is set to search tool but extensions of all types are returned when performing a search from the search tools landing page

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#5182]
This issue was open as a follow up of: https://github.com/mozilla/addons-server/issues/8402

### Steps to reproduce:
1. Open the search tools landing page: https://addons.allizom.org/en-US/firefox/search-tools/
2. Observe the "add-on type" filter
3. Perform a search and observe the results

### Expected results:
~We do not show the "add-on type" filter
~We return only search tools when performing a search from https://addons.allizom.org/en-US/firefox/search-tools/

### Actual results:
all types of add-ons are returned even if the "add-on type" filter is set to search tools.

### Notes/Issues
Verified in FF 60.0.1 on Win7(x64) Issue can be reproduced on amo-dev, amo-stage and amo-prod

**Comment by jvillalobos** [comment]
We're dropping the search tool type soon, so we won't need this anymore.
