### ISSUE TITLE
Review copy for "account deletion" screens

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5184]
Hi,

We need to proof-read/validate the warning messages displayed to users/admins when they are about to delete a user profile.

Message for a regular user who is about to delete their profile:

![screen shot 2018-06-04 at 18 09 32](https://user-images.githubusercontent.com/217628/40928670-74313934-6822-11e8-902a-2ba8e4bcd635.png)

Message for admins who are about delete a user profile:

![screen shot 2018-06-04 at 18 09 18](https://user-images.githubusercontent.com/217628/40928668-7376bf64-6822-11e8-9a0a-f901cc1e1eff.png)

---
See also: https://github.com/mozilla/addons-frontend/pull/5140

**Comment by willdurand** [comment]
@MeridelW I assigned you because you're likely the right person for this issue :)

**Comment by willdurand** [comment]
@MeridelW hi, any chance to get some help from you?

**Comment by vcarciu** [comment]
Verified as fixed based on images from https://github.com/mozilla/addons-frontend/pull/5464 👍 
Admin: 
![admindelete](https://user-images.githubusercontent.com/1583842/42283979-c56d99fc-7fb3-11e8-8bb3-5dbfe90c2a61.png)

User: 
![userdelete](https://user-images.githubusercontent.com/1583842/42283989-cbc70446-7fb3-11e8-838c-3b83f55113bd.png)
