### ISSUE TITLE
June homepage content programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#5187]
For the **14 June** push, please update homepage programming to reflect what's detailed [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#).

@muffinresearch @bobsilverberg

**Comment by muffinresearch** [comment]
@devaneymoz there is no 14th push due to the all-hands. Is this ok to go out on the 21st instead?

**Comment by devaneymoz** [comment]
@muffinresearch yes 21st is fine. Thanks.

**Comment by AlexandraMoga** [comment]
Verified fixed in prod
