### ISSUE TITLE
Delete profile picture text overlaps its border when clicked

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5189]
Steps to reproduce:
1.Go to AMO-dev and log in with an account having a profile picture
2.Go to edit profile page
3.Click on "Delete this picture" photo

Expected results:
The text should properly fit inside the blue border displayed when clicking the text

Actual results:
The text overlaps the blue border

Please see video for this bug : 
![deletepict](https://user-images.githubusercontent.com/1583842/40975269-0a9c82b0-68d3-11e8-9694-6cb79bef7e64.gif)

**Comment by willdurand** [comment]
Thanks for reporting this bug @vcarciu, I also noticed it and was about to submit a PR to fix it :)

**Comment by vcarciu** [comment]
Verified as fixed : 
![deletepicture](https://user-images.githubusercontent.com/1583842/41028233-a2c6184a-6981-11e8-8389-f1bd8221444c.gif)
