### ISSUE TITLE
Cannot log back in with an account after another account was deleted - new pages

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5190]
STR:
1.Load AMO dev and log in with an account and go to Edit profile page
2. Delete the account - Click on Delete my profile
3. Try to log back in using another account

Expected result:
The user is logged in.

Actual result:
401 Unauthorized page is displayed.

Notes:
This is reproducible with FF60(Win10).

![not authorized](https://user-images.githubusercontent.com/33448286/40976641-633f4ebc-68d7-11e8-91c5-7a7f89b79ee3.gif)

**Comment by willdurand** [comment]
It is a "known" issue that has just been fixed on the server: https://github.com/mozilla/addons-server/issues/8387. In the meantime, you have to clear all your cookies for this domain.

Could you please retry in like 1h or so? (to wait until the server fix is deployed).

**Comment by ioanarusiczki** [comment]
@willdurand Ok, I've also noticed (and don't know if it's known) -> the new frontend won't display the message that an account with listed add-ons cannot be deleted
Classic desktop site - the message 
![listed add-ons cannot delete](https://user-images.githubusercontent.com/33448286/40980365-db660eae-68e0-11e8-92a1-75e34475fe90.png)

This is the new behavior when deleting an account with listed add-ons/themes
![no message when deleting](https://user-images.githubusercontent.com/33448286/40980462-15200e38-68e1-11e8-96af-7516a6344ab5.gif)

**Comment by willdurand** [comment]
> Ok, I've also noticed (and don't know if it's known) -> the new frontend won't display the message that an account with listed add-ons cannot be deleted
> Classic desktop site - the message

There is a note about that in the warning modal now.

**Comment by ioanarusiczki** [comment]
This is verified fixed on AMO dev with FF60(Win10).
