### ISSUE TITLE
Rename `editUserAccount` to `updateUserAccount`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5195]
We want to rename `editUserAccount` action creators, actions (`EDIT_USER_ACCOUNT`, etc.), api method and so on to `updateUserAccount` (and `UPDATE_USER_ACCOUNT`, etc.) to be more consistent with the rest of the code that uses "update" to convey the intent of "change".

**Comment by gabru-md** [comment]
@willdurand If this issue is open then I would love to help :smiley:

**Comment by willdurand** [comment]
> @willdurand If this issue is open then I would love to help 😃

Yup, assigned to you!

**Comment by ioanarusiczki** [comment]
@willdurand Could you add some STR for qa or mark it qa not needed ?
Thanks!
