### ISSUE TITLE
A card with a footer sometimes has bottom corners

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5199]
Example: The review card (see the bottom corners below the grey button, it should not be rounded)

![screen shot 2018-06-05 at 18 57 14](https://user-images.githubusercontent.com/217628/40991065-ece2856a-68f2-11e8-8819-d9e66b9a7884.png)

It is a visual regression introduced in https://github.com/mozilla/addons-frontend/pull/5050 while trying to fix https://github.com/mozilla/addons-frontend/issues/4884.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage with FF60, Win10x64 and Android 7.0


![image](https://user-images.githubusercontent.com/31961530/41047913-462cd7e2-69b6-11e8-9cd4-ed322a9eb046.png)
