### ISSUE TITLE
Remove gear menu and search bar from disco pane

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#520]
I remember talking about this with someone and I'm not sure what the final decision was: are we removing the gear menu and search bar from disco pane? I would prefer we did, but am open to having my mind changed.

**Comment by muffinresearch** [comment]
Probably @aswan

**Comment by andymckay** [comment]
@aswan has been working on that, there's two patches for this the first landed and got rid of it in some cases, but not all second patch is in the process of trying to be landed and (hopefully) uplifted here: https://bugzilla.mozilla.org/show_bug.cgi?id=1273958.

**Comment by andymckay** [comment]
Because the bugzilla bugs are in progress, closing.
