### ISSUE TITLE
Update Requirements section in Readme.md

### ISSUE THREAD

**Issue by vsnehil92** [mozilla/addons-frontend#5205]
![image](https://user-images.githubusercontent.com/20948883/41022192-637b7a90-6986-11e8-88bd-f9195ef844db.png)

The current LTS version is Node 8.x. Won't it be updated in the readme.md? I think it need to be fixed.

**Comment by muffinresearch** [comment]
We generally don't switch to the active LTS as soon as it becomes active, but in any case these docs can be updated independently since we're already testing on node 8 and most developers are using node 8 already.

**Comment by gabru-md** [comment]
Can I do this? I will change it in the readme? :smiley:

**Comment by gabru-md** [comment]
Did not notice that a PR is already there :+1:

**Comment by willdurand** [comment]
Hi @gabru-md, there is already a contributor assigned to this issue (see the "contrib: assigned" label) so I invite you to find another "contrib: welcome" or "contrib: good first bug" issue 😄

**Comment by willdurand** [comment]
This has been fixed in #5996
