### ISSUE TITLE
Information text regarding 'hosted addons' should not be present in the notifications section for regular users

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5206]
STR:

1. Log in to AMO dev with a non-developer account
2. Click on Edit My Profile
3. Scroll down to the Notifications section
4. Observe the information text present in the section

Actual result:
There is an information text explaining that the user might receive notifications concerning his hosted addons

Expected result:
Since the user is not a developer, this information text should not be present in the notifications section

Notes:
- reproduced on AMO-dev with FF60, Win10x64

![image](https://user-images.githubusercontent.com/31961530/41023236-803cb5ca-6974-11e8-92c0-a3b9b4bf7b35.png)

**Comment by willdurand** [comment]
ah, good catch thanks!

**Comment by willdurand** [comment]
@AlexandraMoga I see that the legacy frontend always expose this information text.

**Comment by willdurand** [comment]
I think it is a server issue.

**Comment by AlexandraMoga** [comment]
I'm marking the issue as verified fixed on AMO -dev as the second scenario can't be reproduced any longer.
