### ISSUE TITLE
Cannot login with another user after an account with listed add-ons was deleted 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5207]
STR:
1. Load AMO dev and log in with an account that contains listed add-ons or themes
2. Go to Edit profile page and click the Delete profile button
3. Confirm the deletion
4. Log back in from AMO homepage with another account
5. Go to Edit profile page and observe the email address (also check the dev hub content)

Expected results:
Login is made successfully into the second account from step 4.

Actual results:
The user is logged back into the previous deleted account.

Notes:
This issue is reproducible on AMO dev with FF60(win10).
Workaround: log out and log in again using the credential from step4 and the correct account is displayed.

![relogged in the deleted account](https://user-images.githubusercontent.com/33448286/41029734-259dc17a-6985-11e8-8bd6-6645d2b24dc0.gif)

**Comment by willdurand** [comment]
ahm, I suppose we should not allow the user with add-ons to confirm deletion because the API won't permit that anyway, hence this bug: because the API won't delete the user, cookies won't be removed correctly, and the user will end up in a weird state as described in #5190.

**Comment by ioanarusiczki** [comment]
This issue is no longer reproducible because https://github.com/mozilla/addons-frontend/issues/5211 was fixed. An account with listed add-ons cannot be deleted.
Verified fixed on AMO dev with FF60(Win10)
![greyed out yes delete my profile](https://user-images.githubusercontent.com/33448286/41221465-e1b2b9d4-6d6c-11e8-8bf4-9bc0945a205b.png)
