### ISSUE TITLE
Decrease line spacing for add-on name

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#521]
It currently looks like this when an add-on name carries over onto a new line:
<img width="433" alt="screen shot 2016-06-03 at 8 05 12 am" src="https://cloud.githubusercontent.com/assets/6797635/15784021/8304749c-2965-11e6-96de-b9d9df619a20.png">

Which is no good. So I suggest this:
font-family: [platform default];
font-size: 14px;
color: #6A6A6A;
letter-spacing: 0px;
line-height: 18px;

**Comment by muffinresearch** [comment]
This was updated along-side other recent changes - it looks like this now:

<img width="403" alt="discover_add-ons" src="https://cloud.githubusercontent.com/assets/1514/16342129/75d5559c-3a28-11e6-9de5-2507d65b9df3.png">
