### ISSUE TITLE
Notification options are stuck in a loading state after the user delets his profile picture

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5214]
STR:

1. Log in to AMO-dev
2. Go to Edit My Profile and set a profile picture if you don't have one already
3. Delete your profile picture 
4. Check the Notifications section

Actual result
Notification options are stuck in a loading state after the profile picture is deleted

Expected result:
Notification options should not be affected when a user deletes his profile picture 

Notes:
- reproduced on AMO -dev with FF60 Win10x64

![delete pic](https://user-images.githubusercontent.com/31961530/41039539-68054066-69a2-11e8-9369-e9081425cba8.gif)

**Comment by willdurand** [comment]
mmmh so did I break this after merging #5144 or is it an integration bug due to the two features being worked in parallel? 🤔 I'll figure it out.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64 and Android 7.0

![prof pic delete](https://user-images.githubusercontent.com/31961530/41540209-4ab27248-7318-11e8-998e-636f1a7de27f.gif)
