### ISSUE TITLE
Can't call setState (or forceUpdate) on an unmounted component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5217]
### Describe the problem and steps to reproduce it:

1. Go to a collection edit page
2. Add some add-ons (at least one)
3. "Save" the collection
4. Observe the console logs

### What happened?

I see this message:

```text
Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in CollectionManagerBase (created by Connect(CollectionManagerBase))
    in Connect(CollectionManagerBase) (created by Connect(Connect(CollectionManagerBase)))
    in Connect(Connect(CollectionManagerBase)) (created by Translate[Connect(Connect(CollectionManagerBase))])
    in Translate[Connect(Connect(CollectionManagerBase))] (created by withRouter(Translate[Connect(Connect(CollectionManagerBase))]))
    in withRouter(Translate[Connect(Connect(CollectionManagerBase))]) (created by CollectionBase)
    in div (created by Card)
    in section (created by Card)
    in Card (created by CollectionBase)
    in div (created by CollectionBase)
    in div (created by CollectionBase)
    in CollectionBase (created by Connect(CollectionBase))
    in Connect(CollectionBase) (created by Connect(Connect(CollectionBase)))
    in Connect(Connect(CollectionBase)) (created by Translate[Connect(Connect(CollectionBase))])
    in Translate[Connect(Connect(CollectionBase))] (created by CollectionEdit)
    in CollectionEdit (created by RouterContext)
```

### What did you expect to happen?

There should not be any message like that.

I don't think it breaks anything since it is a warning but it is worth investigating.

**Comment by ioanarusiczki** [comment]
@willdurand I don't receive the warning message above but I still get an error in the console when adding a theme or extension into a collection with FF60 (Win10).

![browser console](https://user-images.githubusercontent.com/33448286/41960998-df44d012-79f9-11e8-9d58-0a8ac6686bad.png)
![web console](https://user-images.githubusercontent.com/33448286/41961008-e482103a-79f9-11e8-82f6-d66a0db25d6a.png)

**Comment by willdurand** [comment]
Those logs are only warning from our error handler HOC, not errors. So that looks good to me.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10).
