### ISSUE TITLE
'About:addons' notification is unchecked when the user accesses the edit profile screen right after choosing this subscription

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5219]
STR:

1. Log in to AMO -dev with a developer account
2. Click on Edit My Profile
3. Scroll down to the Notifications sections and opt-in for the 'about:addons' newsletter
4. Click on Update my profile
5. Once you are redirected to the View profile page, select again Edit my profile
6. Check the options selected in the notifications section 

Actual result:
The 'about:addons' newsletter appears deselected on the Edit profile page, while the subscription on the email preference center has been registered.  

Expected result:
The 'about:addons' newsletter should appear selected on the Edit profile page

Notes:
- the checkbox will be marked if you refresh the Edit profile page
- the same scenario applies for the reverse action, i.e. unchecking the 'about:addons' newsletter from the Edit profile page
- reproduced on AMO-dev with FF60, Win10x64

![basket notif](https://user-images.githubusercontent.com/31961530/41043685-1d2c69d8-69ad-11e8-8ade-2eb41d1be487.gif)

**Comment by AlexandraMoga** [comment]
@willdurand yes, this is the only notification that displays this behavior.

**Comment by eviljeff** [comment]
I wasn't involved with the initial implementation of the basket integration so I'm not really sure about the timing/race conditions. Maybe @diox and/or @EnTeQuAk have more of an understanding.

**Comment by diox** [comment]
AFAIK this is a known issue with basket. It takes a while to sync the data with salesforce - not much we can do about it on our end.

**Comment by willdurand** [comment]
mmh I am not sure what we can do on the frontend side either.

**Comment by willdurand** [comment]
@muffinresearch should we try to fake the update on the frontend so that the notification appears selected even though the API did not acknowledge the update?

**Comment by muffinresearch** [comment]
@willdurand that sounds complicated. To do that we'd probably need to maintain a record of the state requested and the actual state. 

@diox did we get anywhere with the proposal of linking direct to the basket page with the token? This would alleviate this completely.

**Comment by diox** [comment]
@muffinresearch unfortunately my proposal wasn't met with huge approval :) https://github.com/mozilla/addons/issues/727

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev and AMO stage with FF61(Win10)
![newsletter](https://user-images.githubusercontent.com/33448286/42282020-dd0925be-7fad-11e8-8f9a-b2807e8aa902.gif)
