### ISSUE TITLE
AMO CTA Button Copy

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#522]
Was this what we decided on, Scott?
<img width="245" alt="screen shot 2016-06-03 at 8 04 08 am" src="https://cloud.githubusercontent.com/assets/6797635/15784035/98feb4a6-2965-11e6-9feb-550b6bceaca9.png">

**Comment by muffinresearch** [comment]
See reply here: https://github.com/mozilla/addons/issues/130#issuecomment-223631373
