### ISSUE TITLE
Page shows 404 when all addons in the second page are deleted

### ISSUE THREAD

**Issue by xu3u4** [mozilla/addons-frontend#5220]
### Describe the problem and steps to reproduce it:
1. Editing a collection (an existing collection)
2. Having more than 25 addons in a collection, so that the pagination shows up.
3. Go to the second page, and delete them all.

### What happened?
It shows `Page not found`. 

### What did you expect to happen?
Ideally, it should be redirected to previous page, page 1 in this case.

![vlpebxfoo1](https://user-images.githubusercontent.com/6767433/41170045-6870e6a4-6b7d-11e8-8bb8-de57ab45fbeb.gif)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, WIn10x64

![remove add-on from coll](https://user-images.githubusercontent.com/31961530/44094148-0f143a3a-9fde-11e8-9c7b-c735e473593e.gif)


@bobsilverberg I've filed a regression in https://github.com/mozilla/addons-frontend/issues/5928
