### ISSUE TITLE
Menu section should be hidden when playing the disco pane video in full screen

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5229]
STR:

1. Load the Discovery pane (about:addons)
2. Select 'Click to play' to start the promo video
3. Open the video in full screen mode

Actual result:
The menu bar on the right is displayed when the video is played in full screen mode

Expected result:
The menu bar should be hidden when the promo video is played in full screen mode

Notes:
- reproduced on all AMO servers with FF60, WIn10x64

![full video](https://user-images.githubusercontent.com/31961530/41088604-9b00257a-6a48-11e8-9a3f-6ffc56f03aac.gif)

**Comment by muffinresearch** [comment]
Yep there's nothing we can do here since the video (and the entire discopane) is running in a frame. 

It's likely the upcoming redesign of the disco pane is dropping the video in any case.
