### ISSUE TITLE
Installing a theme triggers warning banners

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#523]
- Click on the install switch for a theme. It downloads and "installs."
- A warning banner appears and will not show the theme until the user clicks "Allow": 
<img width="1147" alt="screen shot 2016-06-03 at 8 00 34 am" src="https://cloud.githubusercontent.com/assets/6797635/15784104/dcfe2c54-2965-11e6-8d2f-5a8dcb8b68b9.png">
- Turning off the theme via the switch triggers this warning (and "Undo" doesn't do anything): 
<img width="1138" alt="screen shot 2016-06-03 at 8 01 31 am" src="https://cloud.githubusercontent.com/assets/6797635/15784110/e5dfa852-2965-11e6-9faa-3a0a6c704019.png">

Ideally, these banners would not appear at all on Disco Pane. This is a safe place where warnings don't appear!

**Comment by muffinresearch** [comment]
The workaround for dev/stage is to add an exception in about:preferences#security

**Comment by muffinresearch** [comment]
I've updated the docs for this on the wiki so closing.
