### ISSUE TITLE
Report this user for abuse -  Mozilla's add-on policies link is not available

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5230]
STR:
1. Load AMO dev and go to an add-on or a theme's detail page
2. Click on the developer's name
3. Click Report this user for abuse
4. Observe the Mozilla's Add-on Policies

Expected results:
"Mozilla's Add-on Policies" is a link to https://developer.mozilla.org/de/Add-ons/AMO/Policy/Reviews

Actual results:
Link is not available yet.

Notes:
This issue is reproducible on AMO dev - new View Profile page - with FF60(Win10).

![report user and the policies](https://user-images.githubusercontent.com/33448286/41088940-65bd0b0c-6a49-11e8-8eab-57c22bef3441.gif)

**Comment by willdurand** [comment]
Interesting, I think the link never appeared.

**Comment by ioanarusiczki** [comment]
It appears now. Also appears in Report a user for abuse too. Verified fixed on AMO dev with FF60(Win10)
![report for abuse](https://user-images.githubusercontent.com/33448286/41159013-b7285b00-6b33-11e8-92dc-e694cf42fc5f.gif)
