### ISSUE TITLE
A component is changing an uncontrolled input of type text to be controlled

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5234]
When creating a new collection, I got this warning in the devtools:

```
Warning: A component is changing an uncontrolled input of type text to be controlled. Input elements should not switch from uncontrolled to controlled (or vice versa). Decide between using a controlled or uncontrolled input element for the lifetime of the component. More info: https://fb.me/react-controlled-components
    in input (created by CollectionManagerBase)
    in form (created by CollectionManagerBase)
    in CollectionManagerBase (created by Connect(CollectionManagerBase))
    in Connect(CollectionManagerBase) (created by Connect(Connect(CollectionManagerBase)))
    in Connect(Connect(CollectionManagerBase)) (created by Translate[Connect(Connect(CollectionManagerBase))])
    in Translate[Connect(Connect(CollectionManagerBase))] (created by withRouter(Translate[Connect(Connect(CollectionManagerBase))]))
    in withRouter(Translate[Connect(Connect(CollectionManagerBase))]) (created by CollectionListBase)
    in div (created by Card)
    in section (created by Card)
    in Card (created by CollectionListBase)
    in div (created by CollectionListBase)
    in div (created by CollectionListBase)
    in CollectionListBase (created by Connect(CollectionListBase))
    in Connect(CollectionListBase) (created by Translate[Connect(CollectionListBase)])
    in Translate[Connect(CollectionListBase)] (created by component)
    in component (created by RouterContext)
    in ErrorPageBase (created by Connect(ErrorPageBase))
    in Connect(ErrorPageBase) (created by AppBase)
    in div (created by AppBase)
    in div (created by AppBase)
    in div (created by AppBase)
    in NestedStatus (created by SideEffect(NestedStatus))
    in SideEffect(NestedStatus) (created by AppBase)
    in AppBase (created by Translate[AppBase])
    in Translate[AppBase] (created by Connect(Translate[AppBase]))
    in Connect(Translate[AppBase]) (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContext (created by Router)
    in Router
    in Provider
    in I18nProvider
```

I see that the internal state of the `CollectionManager` component as `undefined` values for the corresponding `input` values. It should never be `undefined` (or `null`), only strings that can be empty.

I think the problem comes from `propsToState()`. It does not seem easy to add default values (which should be the case in the constructor at least), so maybe getting rid of this method and using traditional `setState` calls would be better, maybe.

**Comment by Gabbyjose** [comment]
Hi Will, I'm interested in taking this if it's open. Please let me know!

**Comment by willdurand** [comment]
@bobsilverberg hi, do you know if this issue is still valid?

**Comment by willdurand** [comment]
@bobsilverberg hi, do you know if this issue is still valid?

**Comment by kumar303** [comment]
Hi @Gabbyjose, sorry we missed your question! Not all bugs are ready for contributors. The ones that are will appear under this label: https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug Thanks for your interest in helping.

**Comment by willdurand** [comment]
Thanks for the details @bobsilverberg, I am opening this issue for contributions. It is not the most interesting fix ever but it is an important one.

/cc @Gabbyjose (also sorry for having missed your comment)

**Comment by willdurand** [comment]
For QA, please make sure we can create new collections

**Comment by ioanarusiczki** [comment]
Verified on AMO Dev with FF63(Win10) - new collections can be created

![creating a collection](https://user-images.githubusercontent.com/33448286/47660632-1944f500-dba0-11e8-8c31-449173eb20aa.gif)
