### ISSUE TITLE
In reducers/collections.js, rename deleteCollectionBySlug to unloadCollectionBySlug

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5238]
As discussed at https://github.com/mozilla/addons-frontend/pull/5186#discussion_r193733916, the current name of the method is a bit misleading, and it should be changed.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed'?
Thank you

**Comment by bobsilverberg** [comment]
For QA:

Please verify that there are no regressions with the "Create a collection", "Edit a collection" and "Delete a collection" features.

**Comment by ioanarusiczki** [comment]
No new issues found - Create, Edit and Delete are working as expected.
Verified fixed on AMO dev with FF60(Win10)
