### ISSUE TITLE
Roll over theme preview does not work on Dev Edition

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#524]
version 48.0a2

**Comment by muffinresearch** [comment]
Do you have the permission to install addons as per: https://github.com/mozilla/addons-frontend/issues/523#issuecomment-223613290

**Comment by muffinresearch** [comment]
Add an exception in about:preferences#security for dev/stage and it should work. 

The hosts are: 

* dev: https://discovery.addons-dev.allizom.org/
* stage: https://discovery.addons.allizom.org/

**Comment by muffinresearch** [comment]
Let me know if that doesn't work.

**Comment by pwalm** [comment]
Solved! A regular user won't have to do this though, right?

**Comment by muffinresearch** [comment]
> Solved! A regular user won't have to do this though, right?

No, the production version should have this permission with no other intervention.
