### ISSUE TITLE
Static themes are not returned in search results on Android

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5248]
STR:

1. Load AMO-dev - https://addons-dev.allizom.org/en-US/firefox/
2. Enter a search term that will return static themes - i.e. _lastar_
3. Observe the search results
4. Switch to Firefox for Android - https://addons-dev.allizom.org/en-US/android/
5. Enter the same search term used in step 2
6. Observe the search results

Actual result:
Static themes are not returned in search results when searching on Android

Expected result:
Static themes are returned in search results when searching from an Android device

Notes:
- reproduced on AMO-dev with FF60, Android 7.0

![st for android](https://user-images.githubusercontent.com/31961530/41145637-771ca310-6b09-11e8-96f8-8df98a6f8e09.gif)

**Comment by willdurand** [comment]
We don't really decide which add-ons to show in the frontend, if the API does not return static themes for Android, we cannot do anything here.

In addition, static themes are not really supported on Android anyway, so the API does not return static themes for Android on purpose.

**Comment by eviljeff** [comment]
Like @willdurand said, static themes aren't supported on Firefox for Android so for now the API is returning the correct response.  
If Android does eventually add support then addon-server will have to start returning them (no need for an issue now)
On the other-hand, if it _still_ doesn't support static themes by the time LWT are migrated then I guess frontend will have to stop offering themes at all to Android users.
