### ISSUE TITLE
Edit profile page scrolls up when trying to edit a field after an error is generated

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5250]
STR:
1. Log in to AMO-dev
2. Go to Edit my Profile
3. Edit some of the fields, making sure that at least one of the values entered will generate an error (i.e. an invalid image type)
4. Click on update profile
5. After the corresponding errors are generated, scroll down and edit one of the available fields

Actual result:
The Edit profile page will automatically scroll up when trying to edit a field after an error is generated

Expected result:
The Edit profile page is not moving when trying to edit a field after an error is generated

Notes:
- reproduced on AMO -dev with FF60, Win10x64
- it think this was  introduced by #5224 

![scroll up](https://user-images.githubusercontent.com/31961530/41149734-04cf61d8-6b15-11e8-969a-556f401321cd.gif)

**Comment by willdurand** [comment]
Interesting, I cannot trigger this bug because I cannot submit the form, HTML5 validation prevents this to happen. But I agree that there is a bug here.

**Comment by willdurand** [comment]
Ah, I got it! Uploading a picture with an invalid type triggers the bug, sorry I misread the STR obviously.

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64

![no more scroll](https://user-images.githubusercontent.com/31961530/41642239-6e78d27c-7470-11e8-86f4-5fa475e53ef1.gif)
