### ISSUE TITLE
The updated profile photo and add-on custom icon is displayed only after refreshing page - the previous image is displayed instead

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5252]
STR:
1. Load AMO dev and go to Edit profile page to replace the existing profile picture  but make sure it's >3MB (I attached the samples I used)
2. Update profile
3. Observe the image displayed in View profile
4. Click the Edit profile button and observe the image

Expected result:
The new profile picture is displayed.

Actual result:
The previous picture is displayed. Only after page is refreshed the new image is visible.

Notes:
This issue is reproducible on AMO dev with FF60(Win10). Also because it's an intermittent issue and I've noticed that in most cases is reproducible with larger than 3MB images I attached my samples.
It is not reproducible on android or with old pages.

![previous image displayed](https://user-images.githubusercontent.com/33448286/41157071-14779d72-6b2d-11e8-8858-2f4feb0bb63c.gif)

Sometimes the image is not available - page must be refreshed
![no image](https://user-images.githubusercontent.com/33448286/41157178-75061c22-6b2d-11e8-9368-1bdb1a6704e7.png)

[above 3MB.zip](https://github.com/mozilla/addons-frontend/files/2084278/above.3MB.zip)

**Comment by ioanarusiczki** [comment]
@willdurand Can't reproduce this at all with smaller than 1MB images but the issue becomes intermittent with those between 1 to 3 Mb.

**Comment by willdurand** [comment]
I don't see what's causing the issue, except the browser not being able to load the image..

Did you try with another browser such as Chrome for instance?

**Comment by ioanarusiczki** [comment]
@willdurand It is reproducible with Chrome too.
What I've noticed is that this is much easier to reproduce it for the custom add-on icons in both browsers FF and Chrome. 
![custom icon](https://user-images.githubusercontent.com/33448286/41849727-9b85b0be-788a-11e8-9b3b-4ebc55c9808d.gif)

**Comment by willdurand** [comment]
> What I've noticed is that this is much easier to reproduce it for the custom add-on icons in both browsers FF and Chrome.

I cannot reproduce with the add-on icon but I acknowledge the bug.

**Comment by willdurand** [comment]
I also think it is related to https://github.com/mozilla/addons-server/issues/7954 /cc @eviljeff.

**Comment by eviljeff** [comment]
It's likely partly mozilla/addons-server#7954 (and in the case of addon icons partly the way we cache bust user uploaded images).

I don't have much further insight unless it can be confirmed that the API is serving the wrong url *, or serving the right url but getting the wrong file content. *(after a reasonable amount of time to account for resizing/crushing time).  My money is still on an unavoidable delay between the user uploading and the new image being available.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10) 

![updated photo no refresh](https://user-images.githubusercontent.com/33448286/42280075-651ca53a-7fa8-11e8-83e2-577f2930b777.gif)
