### ISSUE TITLE
Server issue when trying to change theme

### ISSUE THREAD

**Issue by greenbirdslave** [mozilla/addons-frontend#5260]
I am loading apps on a new P{C, downloaded Firefox. Accessed my favorite
themes, and clicked on one, and got a server issue message.

I expected to be able to use my favorite themes or other themes, but none will work.

https://addons.mozilla.org/en-US/firefox/collections/greenbirds/

**Comment by bobsilverberg** [comment]
@greenbirdslave We need a bit more information in order to troubleshoot your issue. Could you please provide us with the exact steps you take to reproduce this issue? Any information about error messages, URLs or screen shots you can provide would be helpful as well.

**Comment by bobsilverberg** [comment]
Closing this as no info has been provided.
