### ISSUE TITLE
Editthiscookie

### ISSUE THREAD

**Issue by DragoCubed** [mozilla/addons-frontend#5262]
### Describe the problem and steps to reproduce it:

It's not there anymore
### What happened?
Nothing?
### What did you expect to happen?
To be able to install Editthiscookie
### Anything else we should know?
I don't really know how this works

https://addons.mozilla.org/en-GB/firefox/addon/editthiscookieaddon/
http://www.editthiscookie.com/

**Comment by championshuttler** [comment]
Hi @DragoCubed , I think this addon is deleted by the creator. We can not do anything in this case.
I suggest you to search for another addon for same functionality if its available.
Let me know if you need any help apart from this :)

**Comment by willdurand** [comment]
Hi, I think @championshuttler is correct and we cannot do anything here.

**Comment by DragoCubed** [comment]
It was because Firefox removed many capabilities related to cookies. It's a very Google like move. https://www.ghacks.net/2018/02/26/mozilla-removes-individual-cookie-management-in-firefox-60/

**Comment by Moustachauve** [comment]
If you are still looking for an alternative, I suggest you take a look at this extension that I made that is very similar to EditThisCookie

https://addons.mozilla.org/en-US/firefox/addon/cookie-editor/
