### ISSUE TITLE
Maybe allow 'Add to Firefox' (and other blue buttons) where the user agent string includes Waterfox/

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#5263]
### Example string 'A-02'

`Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2) Gecko/20100101 Firefox/56.2 Waterfox/56.2` 

– harmonious with both: 

- https://github.com/browser-update/browser-update/commit/e2aa26319b14de1ba73b88c4a6cbfeabb8fb5403 _Whitelist waterfox_ **and**
- the Browser-Update.org developer's plea to  add a an explicit name of the browser to the string. 

### Example string 'vESR-60-01'

`Mozilla/5.0 (X11; FreeBSD amd64; rv:60.0) Gecko/20100101 Firefox/60.0 / Waterfox/60.0`

– experimental, with a view to the future **v**ariant of Waterfox that will be based on releases of Firefox **ESR**. 

### Results

With both example strings, at https://addons.mozilla.org/addon/latest-on-amo/ we have the two (green) directions to use Firefox. With my vESR-60-01 example: 

![2018-06-09 10 24 01](https://user-images.githubusercontent.com/192271/41190062-dcea5342-6bcf-11e8-8cc4-27c4d089301b.png)

Side note: about:config?filter=privacy.resistFingerprinting `false`

## Enhancement request
 
The blue **Add to Firefox** button will be preferable, if AMO developers can allow it, for users of Waterfox (in cases where an identifying string will be used). 

As if you have not enough on your plates already for this year :-)

**Comment by grahamperrin** [comment]
… also e.g. the blue **Install theme** button at https://addons.mozilla.org/addon/firefox-quantum-nightly/

## Observation

Classic desktop site views are OK, at a glance. Not the new look blue buttons, but it's possible to add extensions and themes whilst using the `Mozilla/5.0 (X11; FreeBSD amd64; rv:56.2) Gecko/20100101 Firefox/56.2 Waterfox/56.2` string.

**Comment by willdurand** [comment]
@jvillalobos what do you think about this proposal?

**Comment by jvillalobos** [comment]
Officially, we only support Firefox and Firefox for Android (after we're done with legacy add-ons later this year). While it would be nice to support Firefox forks, we have no guarantees about their support for WebExtensions add-ons, or how compatibility ranges apply to them.

It'd be best for the owners of those forked products to either have their own add-ons distribution system or inject a userscript into AMO that makes it work to fit their needs.

**Comment by grahamperrin** [comment]
Thanks, 

> … no guarantees about their support for WebExtensions add-ons, or how compatibility ranges apply to them. …

Understood and agreed. 

> … own add-ons distribution system …

https://github.com/MrAlex94/Waterfox/issues/303#issuecomment-400970178 re: the classic add-on archive mirror (legacy extensions database)
