### ISSUE TITLE
Pagination area has a different styling on the add-on reviews page compared to other sections on the site

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5266]
STR:

1. Load AMO -dev
2. Go to an add-on details page (https://addons-dev.allizom.org/en-US/firefox/addon/gtranslate/)
3. In the Ratings section, click on Read all reviews
4. Scroll down until you reach the bottom of the page and observe the card edges and the pagination styling 

Actual result:
The page numbers have a smaller font and the card edges don't have a border radius 

Expected result:
The styling used in other sections of the site should be applied to the Reviews page - see second screenshot for comparison 

Notes:
- reproduced on all AMO servers with FF60, WIn10x64

**[1] - Reviews page**
![image](https://user-images.githubusercontent.com/31961530/41234034-c546b620-6d93-11e8-8799-b4f29226d624.png)

**[2] - Search results**
![image](https://user-images.githubusercontent.com/31961530/41234054-d810f612-6d93-11e8-9d3d-d00964a818d6.png)

**Comment by willdurand** [comment]
Hi, this will be fixed in https://github.com/mozilla/addons-frontend/pull/5191, which (partially) fixes #3100.

**Comment by AlexandraMoga** [comment]
The styling issues have been fixed by the implementation of the new pagination format.

Verified as fixed on AMO stage with FF60 and Android 7.0
![image](https://user-images.githubusercontent.com/31961530/41708937-a7af8862-754a-11e8-9f9b-c539b02047c1.png)

![image](https://user-images.githubusercontent.com/31961530/41708957-af888dae-754a-11e8-8a48-dcf34c44202f.png)
