### ISSUE TITLE
MMB installation perfomed in the same tab

### ISSUE THREAD

**Issue by SVSanta** [mozilla/addons-frontend#5267]
STR:
1. Load AMO and click on any extension to view the details page.
2. Click using the middle mouse button on the "+ Add to Firefox" button.

Expected result:
A new page is opened with the add extension popup.

Actual result:
The add extension popup is displayed in the same page.

Notes:
This issue is reproducible on all AMO servers with FF62(Win10 64Bit).
![mmb same page](https://user-images.githubusercontent.com/28138132/41238763-41846cd6-6d86-11e8-991f-a1cad11311e8.gif)

**Comment by willdurand** [comment]
I am sorry but I don't understand the issue.

**Comment by willdurand** [comment]
@SVSanta would you have more information?

**Comment by vcarciu** [comment]
@willdurand : MMB is probably middle mouse button
