### ISSUE TITLE
Word break points are not set correctly in the Biography section on the user Profile page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5268]
STR:

1. Load AMO -dev
2. Visit a user profile page with a Biography included (https://addons-dev.allizom.org/en-US/firefox/user/MaDonna-3/)
3. Observe the Biography section

Actual result:
Word-break is not set correctly,  words are split on different rows

Expected result:
Word-break should be reset to prevent incorrect word splitting 

Notes:
- reproduced on AMO -dev with FF60, Win10x64 and Android 7.0

![image](https://user-images.githubusercontent.com/31961530/41239135-601fb55a-6da0-11e8-8647-4b8fc61ce726.png)

**Comment by championshuttler** [comment]
I think it will be fixed by using `word-wrap` instead of using `word-break` . 
Can i take this up?

**Comment by AlexandraMoga** [comment]
Verified as fixed on AMO -dev with FF60, Win10x64, Android 7.0

![image](https://user-images.githubusercontent.com/31961530/41350563-408a7bd0-6f1c-11e8-8c3d-e1e06bdda84f.png)
