### ISSUE TITLE
Bookmark parent folder display

### ISSUE THREAD

**Issue by PascalBQ** [mozilla/addons-frontend#5272]
### Describe the problem and steps to reproduce it:

looking for Bokmarks feature that can display the parent folders containing the bookmark item

### What happened?
found the link but "This add-on has been removed by its author."

### What did you expect to happen?
I would expect the possibility to contact the author and request re-activation ... or at least the reason why it is no longer available ...
or a recommended alternative...
or better still: standard addition in Firefox itself

### Anything else we should know?

the following was found on url= https://addons.mozilla.org/en-US/firefox/addon/locate-in-bookmark-folders/reviews/

Use Go To Parent Folder instead. It is up to date, works great and compatible with FF 3.5-3.7
https://addons.mozilla.org/en-US/firefox/addon/7377/

A nice complement to this is Show Parent Folder
https://addons.mozilla.org/en-US/firefox/addon/7372/
FF 3.0-3.7

**Comment by smayer97** [comment]
Would definitely be VERY useful to integrate into current FF. I depend on this so much...

**Comment by jvillalobos** [comment]
Most add-ons disabled by their devs are abandoned, so it's unlikely the devs will like to be contacted by users. However, some devs might still have websites or webpages dedicated to the abandoned add-ons, so I suggest you look for that.

I don't think there's anything to do on the AMO side.
