### ISSUE TITLE
The default icon is displayed for the static themes search suggestions 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5277]
STR:
1. Load AMO dev and make a search for a static theme.
2. Observe the icon displayed below into the search suggestions.

Expected result:
The static theme's square image is visible.

Actual result:
The general icon (green icon) is displayed.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).
This issue is also reproducible with collections - when making a Search for a static theme.

The General Search
![static themes - icons while search](https://user-images.githubusercontent.com/33448286/41342248-7b66283e-6f04-11e8-9936-4a8cfd09b197.png)

The search suggestions for the collection feature
![icons in search suggestions collections](https://user-images.githubusercontent.com/33448286/41342325-a23eef2c-6f04-11e8-97ac-01825f9ad33b.png)

**Comment by willdurand** [comment]
Could it be an API issue? /cc @eviljeff

**Comment by eviljeff** [comment]
Yes, in a way.  As far as I was aware static themes didn't have icons so they just aren't generated and you'd get the generic one instead.  Is search suggestions the only place icons are used for static themes?

**Comment by AlexandraMoga** [comment]
The frontend is exposing icons for static themes on the Edit collections screen and the Reviews page as well.

[1] Edit collection
![image](https://user-images.githubusercontent.com/31961530/41452796-110f66ac-707c-11e8-97eb-d9822cd1ed41.png)

[2] Reviews 
![image](https://user-images.githubusercontent.com/31961530/41452814-1b7d192c-707c-11e8-8d19-bb270ed18e27.png)

**Comment by willdurand** [comment]
@pwalm do we want icons for static themes? And if so, how do we get/generate them?

**Comment by eviljeff** [comment]
We could generate a icon or use part of the existing preview.  Either way, using the left-hand part of the preview with the stylised Firefox gui could look super weird.  I don't know what the alternative is though.

**Comment by AlexandraMoga** [comment]
@eviljeff forgot to mention Add-on Manager, where an icon is also needed for the installed Themes list:
I think that, once the format to be used is decided, I should file an issue for Firefox, right?

![image](https://user-images.githubusercontent.com/31961530/41534621-d52a72f6-7307-11e8-89f2-b45b126cf091.png)

**Comment by eviljeff** [comment]
@AlexandraMoga I'd file a bug, yes.  I'm not sure what the in-Firefox solution would be exactly - I'd guess it's just displaying the icon specified in the manifest (or the default in this case) but that's kinda weird to require a non-mandatory field to allow the user to differentiate a theme from another field.

If Firefox continues to display the icon defined in the manifest AMO may have to start generating an icon for inside the the .xpi too, which is a little different than an icon just for AMO display.

**Comment by pwalm** [comment]
@willdurand No icons for static themes

**Comment by eviljeff** [comment]
@pwalm that's good for me, but what should frontend display instead in the places @ioanarusiczki and @AlexandraMoga have identified?

**Comment by muffinresearch** [comment]
> @pwalm that's good for me, but what should frontend display instead in the places @ioanarusiczki and @AlexandraMoga have identified?

@pwalm any thoughts ^ should the frontend display white-space?

**Comment by pwalm** [comment]
Yeah, white space for now.

**Comment by ioanarusiczki** [comment]
@pwalm @rebmullin I checked the places mentioned in the opened issues and also what @AlexandraMoga mentioned in her comments.  The review page still shows the green icon. Is that intended? 
![reviews - icon for static themes](https://user-images.githubusercontent.com/33448286/42762614-71154a3e-8919-11e8-9cd3-6a77d7c9e6b6.png)

**Comment by rebmullin** [comment]
@ioanarusiczki, thanks for catching that. I will do a follow up PR for this..

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10). 
the general search
![static themes - general search](https://user-images.githubusercontent.com/33448286/42802607-1d4269ee-89ac-11e8-943c-b3b3d1e6c428.png)

the collections
![static themes search collections](https://user-images.githubusercontent.com/33448286/42802629-23ce497c-89ac-11e8-9939-ccac492f281b.png)

add-on manager
![static themes - add-on manager](https://user-images.githubusercontent.com/33448286/42802635-2812cf8a-89ac-11e8-874b-b537aff917fc.png)

**Comment by rebmullin** [comment]
hey @ioanarusiczki, I just merged #5613, which addresses the review section you discovered. Do you want to just verify that piece too?

**Comment by AlexandraMoga** [comment]
No icon displayed on static theme review page:

![image](https://user-images.githubusercontent.com/31961530/43147609-231d454e-8f6c-11e8-9b33-ee40b1e85d47.png)
