### ISSUE TITLE
Make sure we report errors to Sentry

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5278]
In #4051, we introduced a component to catch all uncaught errors (using `componentDidCatch()`). When an error occurs, we serve a server error page to the end user and we log the error.

~~The problem is that this error is lost because logging happens on the client side, and we never get any notification and we do not send anything to Sentry.~~

~~Before this patch #4051, Sentry was notified because the sentry lib catches all uncaught errors, but it is not the case anymore.~~ => We should make sure that logging with `console.error` sends data to Sentry.

We should send errors caught by the `ErrorPage` component as described here: https://docs.sentry.io/clients/javascript/integrations/react/#expanded-usage

**Comment by kumar303** [comment]
> I am able to trigger a client error from this page but it does not get caught by the `componentDidCatch()`.

I think the page could use another button to simulate an error that gets caught by `componentDidCatch()` so we can test it out.

**Comment by kumar303** [comment]
Well, I guess the more important thing to simulate from that page is that `console.error()` goes to Sentry. Right now it only simulates that `throw new Error(...)` goes to Sentry.

**Comment by willdurand** [comment]
> I think the page could use another button to simulate an error that gets caught by componentDidCatch() so we can test it out.

That's what I am working on.

I don't fully understand why errors are not always caught by `componentDidCatch()` though...

**Comment by willdurand** [comment]
> Well, I guess the more important thing to simulate from that page is that console.error() goes to Sentry. Right now it only simulates that throw new Error(...) goes to Sentry.

This would be nice because that's not obvious, but not sure how to test a third-party lib that gets installed globally.
