### ISSUE TITLE
Addon not found mention in support mozilla

### ISSUE THREAD

**Issue by anuppsaikia** [mozilla/addons-frontend#5283]
### Describe the problem and steps to reproduce it:

 Addon not found mention in support Mozilla
### What happened?
The Addon is mentioned in support Mozilla and when you click the link the addon is not on available anymore
### What did you expect to happen?
That I would be able to find the addon in as mentioned in the support Mozilla forum
### Anything else we should know?
Just update it so that people know that it is no more available or valid

https://support.mozilla.org/en-US/questions/785554

**Comment by jvillalobos** [comment]
The add-on was disabled by the developer a while ago. Unfortunately we can't change old answers in the support forum. You can either look for more recent recommendations, or look for [other translation extensions in the add-ons website](https://addons.mozilla.org/firefox/search/?q=translate).
