### ISSUE TITLE
"This add-on already belongs to the collection" should be displayed above Search 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5286]
STR:
1. Load AMO dev and go to your collections, edit one of the existing collections or create a new one
2. Add an extension or theme to the collection
3. Try to add the previous extension again to the collection and observe the message displayed

Expected result:
"This add-on already belongs to the collection" message is displayed above the Search.

Actual result:
"This add-on already belongs to the collection" message is displayed above Collection name field.

Notes:
Reproducible on AMO dev with FF60(Win10&Android 8.0).

On small devices such as android phones if the message is above "Collection name" name field to observe the red message the user must scroll to top.
![the red message - small devices](https://user-images.githubusercontent.com/33448286/41459015-eb1f36d8-7090-11e8-9e09-1eb70a2d8d4b.gif)

**Comment by bobsilverberg** [comment]
This should be fixed when PR #5676 lands.

**Comment by vcarciu** [comment]
Verified as fixed  : 
![alreadybelongs](https://user-images.githubusercontent.com/1583842/43210232-33960eee-9037-11e8-828e-234b96e8fb46.gif)
