### ISSUE TITLE
Automate extraction of new strings ready for translation

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#529]
We should extract if we detect new strings. 

This process would cover:
- [ ] Extracting new strings
- [ ] Merge locales
- [ ] Build debug locales
- [x] Lint with dennis or similar
- [ ] Land it once green

**Comment by muffinresearch** [comment]
@EnTeQuAk fancy this one for a rainy day now you've done it for addons-server?

**Comment by EnTeQuAk** [comment]
Absolutely :)

**Comment by muffinresearch** [comment]
@EnTeQuAk do you have an update on where this is at / what it would take to copy what we've done with addons-server?

**Comment by muffinresearch** [comment]
@EnTeQuAk any updates?

**Comment by EnTeQuAk** [comment]
I started working on finishing up the outstanding things on addons-server, which essentially makes the script auto-merge the PR once everything is green: https://github.com/mozilla/addons-server/tree/auto-merge-l10n-pr

I'll test this on addons-server and work on addons-frontend l10n extraction probably this week as a side-project and see where I get.

**Comment by willdurand** [comment]
@EnTeQuAk Is this still feasible? Or should we just close this issue and continue the manual extraction? We were able to remove two manual steps and it does not take too long if we continue to do it once a week.
