### ISSUE TITLE
translator wiktionary and google translate

### ISSUE THREAD

**Issue by JorgeM12** [mozilla/addons-frontend#5290]
a couple of weeks ago I was looking for a translator for my browser mozilla firefox and I find this translator that is like google chrome or similar because we are in 2018 and the whole thing
well this translator is called
"wiktionary and google translate"
and this was in the list of add-ons to mozilla firefox from what I saw in some videos and nowadays it is not unfortunately
and if I go to the page I get this error
saying that it is not available or that supposedly the author has taken it
https://addons.mozilla.org/en-US/firefox/addon/google-dictionary-and-google-t/
 
here I leave a video a video of how it is
https://www.youtube.com/watch?v=QZZ2II0NZB4

I speak Spanish what more or less says the video esque teaches how to install it leaving a description the address of the extension and how to use it I do not know if this translator is still available because it really seems great and I would like to have it and if it is possible for free hehe

**Comment by willdurand** [comment]
The add-on has probably been removed unfortunately, I cannot access it either.

**Comment by irwanwr** [comment]
if anyone interested to update or anything else so the add-on can be operational again, 
here is the webpage of it:
https://www.toptip.ca/2010/10/firefox-extension-google-dictionary-and.html
that's the author webpage.
