### ISSUE TITLE
Add components to storybook

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5299]
After storybook is up and running the first step is going to be to move the current components that we have into the story book. We should aim to try and break them up into relevant categories as we do so. 

Feel free to break this issue up into additional new issues for each separate group of components as required.

See https://lonelyplanet.github.io/backpack-ui/ for a good example.

**Comment by willdurand** [comment]
This issue is not really actionable. Realistically, we won't add stories for all the existing components.
