### ISSUE TITLE
Move the create collection feature from the CollectionList to the Collection component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5302]
This is some refactoring that makes sense to do before tackling issue #3142. The create collection feature was located at the `CollectionList` component back when we were still using an overlay for the form, but it doesn't make sense to have it there anymore. This will remove the `CollectionList` component and use the `Collection` component instead for the "create a collection" feature.

For QA:

Please check for any regressions of the "create a collection", "edit a collection" and "view a collection" features.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10 & Android 8.0)
Filed https://github.com/mozilla/addons-frontend/issues/5335
