### ISSUE TITLE
Version History for static themes is not available on the new frontend 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5304]
STR:
1. Load AMO dev and go to the detail page of a static theme with one or more listed versions
2. Observe the More information section
3. Check for Version History

Expected result:
The version history is displayed in More information section.

Actual result:
The Version History is not available yet.

Notes:
This issue is reproducible on AMO dev with FF60(Win10).
The old pages display the versions as you can see below:
 
![new versions](https://user-images.githubusercontent.com/33448286/41544439-6d49580e-7321-11e8-8903-3314cddc17b9.gif)

**Comment by rebmullin** [comment]
hey @jvillalobos, can you please take a quick look? It looks like we explicitly were hiding this for lightweight themes. I am not sure if this was b/c this couldn't be updated on lightweight themes (so far i've only seen lightweight themes versions with "0"). It should be a quick update but I just want to verify we DO want to display this before making this change.

**Comment by jvillalobos** [comment]
You're right, we didn't show a version history for LWT because we didn't keep track of them. Since static theme versions are treated like those of other add-ons, we should also show their version history.

**Comment by rebmullin** [comment]
ok cool, will update...thanks : )

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10 & Android 8.0)

![static themes - version history](https://user-images.githubusercontent.com/33448286/41768732-c59d25f2-7615-11e8-8571-b2c808b1ea42.gif)
