### ISSUE TITLE
Use Prettier 🔥

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5312]
I'd like to consider the use of [Prettier](https://prettier.io/) again (We have discussed this point during the SF All Hands June 2018). I am a bit tired of leaving/reading comments about style and coding standards, especially because it is always difficult to interpret them and very much subjective, not to say boring and a waste of time.

By adopting Prettier, we'll be able to fix all these "coding standard issues" and stop leaving comments with little value. There are languages where it is (almost) built-in, like Python (indentation matters + PEP8) or Go. This is pure joy. I also believe that contributors will benefit from this, because they'll be able to push code that looks prettier 😉 

According to our current code base and ESLint rules, this command should fix our code while respecting what we want:

```
prettier --single-quote --trailing-comma all --arrow-parens always --write "{src,tests}/**/*.js"
```

FYI, the `--arrow-parens` option fixes an issue we had in the past, which led to the non-adoption of Prettier.

---
Related issues: #3045, #4940 and PR #3059

**Comment by bobsilverberg** [comment]
While we're discussing styles, can we consider dropping the `--arrow-parens always` rule? I've always found it odd to have to include parens when there is only one argument. If everyone disagrees with me I'm fine to keep it, but I'd rather drop it. What do others think?

**Comment by willdurand** [comment]
> I've always found it odd to have to include parens when there is only one argument. If everyone disagrees with me I'm fine to keep it, but I'd rather drop it. What do others think?

I'd rather not do that for the sake of consistency. It is a bit annoying to know when to add/not add parentheses (we need them when no argument or more than one argument), and if you want to add a second parameter, then you'll have to add parentheses anyway.

**Comment by willdurand** [comment]
I added `prettier` to the exclusion list of dev deps that need to be pinned because Prettier recommends to use exact versions.

**Comment by willdurand** [comment]
For existing PRs, the best is to:

1. squash all the commits first

```
git rebase -i HEAD~<NB OF COMMITS>`
```

- Add `r` instead of `pick` one the first line
- Add `f` instead of `pick` on all subsequent lines
- Save, it will ask for the new commit message, write it and save again

2. install Prettier locally:

```
yarn add prettier
```

3. run the command below to apply Prettier on changed files:

```
git diff-tree --no-commit-id --name-only -r HEAD | xargs prettier --single-quote --trailing-comma all --arrow-parens always --write "{}"
```

4. Clean your diff (remove unwanted changes):

```
git checkout -- package.json yarn.lock *.css
```

5. Check that everything looks good:

```
yarn lint
```

should not report any errors.

6. Update your commit:

```
git add . && git commit --amend --no-edit
```

7. Rebase \o/

```
git fetch origin
git rebase -Xtheirs origin/master
```
