### ISSUE TITLE
A long unbroken text is not wrapped in notes 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5315]
STR:
1. Load AMO dev and go to collections
2. In edit this collection make a note, use a long unbroken string, for an extension or theme that was added in the list
3. After saving it observe the layout of the note

Expected result:
Text is wrapped.

Actual result:
Text appears cut.

Notes:
This issue is reproducible on AMO dev with FF60(Win10 and Android 8.0).

![text is not wrapped notes](https://user-images.githubusercontent.com/33448286/41602243-05f55e42-73e3-11e8-9d22-680e3c76d1fb.png)

**Comment by devshiva619** [comment]
@ioanarusiczki hey I am a beginner and would like to work on this. If you can guide me how I can solve this I would like to work on this. 😃

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10 &Android 8.0)

![user comment](https://user-images.githubusercontent.com/33448286/41853818-5703ac72-7897-11e8-9b7f-0623659ecf4c.png)
