### ISSUE TITLE
Improve Flow coverage of the SearchResults component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5316]
I ported the old prop types to Flow types but did not spend too much time defining precise types in `src/amo/components/SearchResults/index.js`. We should avoid the `Object` Flow type whenever possible.

In this comment, we could probably add a better type for:

- `filters`
- `results`
- `paginator` (which should receive an instance of `Paginate`)

**Comment by vcarciu** [comment]
Can you please add some STRs to this issue or mark it as "qa: not needed" ?
