### ISSUE TITLE
Create a new Button style that looks like "cancel"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5317]
Our `Button` component has different "types" that are used to change its style (using the `buttonType` prop). We mix appearance and function types though, e.g., "neutral" and "cancel".

We often use "cancel" to create buttons that look like simple links without borders or background. In some cases, those buttons are not technically speaking "cancel" buttons.

We should create an alias/new button type for this "cancel" button style with a name other than "cancel".

**Comment by bobsilverberg** [comment]
Just a note for whoever implements this, please look through the existing code for instances of `Button`s with `buttonType` of `cancel` to see if they should be switched to this new style/type.
