### ISSUE TITLE
Infer action types from action creators instead of using separate Flow types

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5318]
This [article](https://hackernoon.com/redux-flow-type-getting-the-maximum-benefit-from-the-fewest-key-strokes-5c006c54ec87) has a recipe for inferring action types from action creator functions instead of defining, exporting, and maintaining separate action types. This will make everything simpler.

For example, instead of this:
```js
export const SET_NAME = 'SET_NAME';
export const SET_AGE = 'SET_AGE';

export type SetName = {type: 'SET_NAME', payload: string}
export type SetAge = {type: 'SET_AGE', payload: number}

const setName = (name: string): SetName => {
    return {type: SET_NAME, payload: name}
}

const setAge = (age: number): SetAge => {
    return {type: SET_NAME, payload: age}
}

export type Actions = SetName | SetAge;
```

We can do this:
```js
export const SET_NAME = 'SET_NAME';
export const SET_AGE = 'SET_AGE';

const setName = (name: string) => {
    return {type: SET_NAME, payload: name}
}

const setAge = (age: number) => {
    return {type: SET_AGE, payload: age}
}

export type Actions =
    ExtractReturn<typeof setName> |
    ExtractReturn<typeof setAge>
```

**Comment by kumar303** [comment]
There is a better version here: https://github.com/facebook/flow/issues/4002#issuecomment-384756198

**Comment by kumar303** [comment]
Well, huh. I can get things to work in Flow Try but not in our code. It seems to always set `action` and all of its properties to `any` which is not helpful. That is, it's not actually extracting the type of the returned object.

**Comment by bobsilverberg** [comment]
I just tried doing this as well, for a new action I was adding to the collections reducer, and noticed that flow reports the type as `any | {|payload: {|username: string|}, type: "UNLOAD_USER_COLLECTIONS"|}`, so the `any` is breaking Flow's ability to type check. I'm also not sure why it works on Flow Try but not in our code.

**Comment by bobsilverberg** [comment]
Ugh, now I cannot get it to work again. :-( Nevermind me.
