### ISSUE TITLE
No featured extensions in -stage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5321]
I dont see any featured extensions on https://addons.allizom.org:

![screenshot_20180619-232335](https://user-images.githubusercontent.com/217628/41625389-facb0554-7418-11e8-983e-164c7baea2bb.png)

**Comment by AlexandraMoga** [comment]
@willdurand isn't this issue occurring with Firefox for Android only?

We had similar issues reported a while back, See #4084 and #3357 (possibly related)

**Comment by willdurand** [comment]
ah right, it is indeed a duplicate of #4084.
