### ISSUE TITLE
Remove video from top of about:addons (disco pane)

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/addons-frontend#5323]
As a first step in making the content at the top of about:addons better, remove the video from the top of about:addons. 

The screenshot below shows content and a link to the video. Remove the video. 
![disco pane screenshot](https://user-images.githubusercontent.com/911251/41627175-04a396bc-73d4-11e8-9051-a5fbd2e43351.png)

**Comment by vcarciu** [comment]
Verified as fixed : 
![removevideo](https://user-images.githubusercontent.com/1583842/42769749-cdeb4f1c-892b-11e8-95ab-996422f70e55.png)

**Comment by brassy-** [comment]
Hey, vcarciu!

Here how I'm expecting to see the content below.
<img width="704" alt="screen shot 2018-07-17 at 10 40 20" src="https://user-images.githubusercontent.com/6309827/42806073-de85656a-89ad-11e8-8301-e6cbcbee3dc7.png">

To achive this I simply made some change to `.disco-content` 

```
.disco-content 
{
    font-size: 16px;
    margin-right: 50px;
    max-width: 620px;
    line-height: 1.5;
}
```
and set `.video-wrapper` on `display: none`. 
Feel free to implement it in the way you prefer — I assume have the video on display none can be bad for performance.

**Comment by vcarciu** [comment]
@willdurand : can we made the changes requested above? I will remove the verified fixed label .

**Comment by willdurand** [comment]
Do we really need this margin-right of `50px`? Here is the content with a larger font size + line-height, but no margin:

![screen shot 2018-07-17 at 13 43 49](https://user-images.githubusercontent.com/217628/42815384-84618798-89c7-11e8-89d2-61a0fa2ce114.png)

**Comment by brassy-** [comment]
We don’t IMHO, but we need the max-width!

Il giorno mar 17 lug 2018 alle 13:44 William Durand <
notifications@github.com> ha scritto:

**Comment by willdurand** [comment]
> We don’t IMHO, but we need the max-width!

roger that, thanks!

**Comment by vcarciu** [comment]
@brassy- : Please have a look and let us know if everything is ok now : 
![layout](https://user-images.githubusercontent.com/1583842/42817704-91bf64b8-89d7-11e8-9e16-c875644a51b6.png)

**Comment by brassy-** [comment]
Thank you! It looks good :)
