### ISSUE TITLE
Replace about:addons (disco pane) toggle switches with Add to Firefox buttons

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/addons-frontend#5325]
We want the experience in about:addons to be consistent with the experience on addons.mozilla.org. Right now, the about:addons disco pane experience uses a toggle switch, and addons.mozilla.org uses a button.

Wait to implement the button in disco pane, until the button is updated in addons.mozilla.org.

**Comment by jvillalobos** [comment]
That's https://github.com/mozilla/addons-frontend/issues/3954, I believe.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF63(Win10)

This is a demo using the pref extensions.webextPermissionPrompts set to false to show the new info dialog. 
![button states disco pane](https://user-images.githubusercontent.com/33448286/44083951-0f40359c-9fbe-11e8-8b57-60ab294bf435.gif)

**Comment by ioanarusiczki** [comment]
@willdurand it's not the case the disco pane to contain incompatible add-ons on AMO prod but testing it on -dev with FF63(Win10) I've noticed that the button is displayed as being active and it loads an error after clicking it.  
Let me know if the button is supposed to be greyed out such as on the add-on's detail page when an add-on is not compatible with the FF version.

![incompatible add-on](https://user-images.githubusercontent.com/33448286/44090943-822f7c0a-9fd4-11e8-9515-01075ab12d38.gif)

**Comment by jvillalobos** [comment]
@muffinresearch @willdurand Is deploying this in prod blocked on anything?

**Comment by muffinresearch** [comment]
> @muffinresearch @willdurand Is deploying this in prod blocked on anything?

Yep, the disco recommendations shield study is still running so we're going to switch this on in prod once that's completed.
