### ISSUE TITLE
Can't tell when the screenshots slideshow has begun looping

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#5326]
### Describe the problem and steps to reproduce it:
1. Go to an add-on page e.g. https://addons.mozilla.org/en-US/firefox/addon/never-pay-extra/
2. Click the first screenshot
3. Try to browse through the available screenshots by using the right arrow key.

### What happened?
Went through all the screenshots twice before I realized they were looping. Although the screenshots themselves are text+image heavy, the add-on is only adding a couple of buttons so I suppose I was only looking for them and sort of zoned out the rest of the details in the images. 

### What did you expect to happen?
Either don't let the screenshot counter (`#pswp__counter`) disappear automatically or don't loop. Or maybe some fancy swipe animation to indicate when the loop begins.

### Anything else we should know?
Yes I do need some coffee but I still believe not letting the counter hide automatically could be a good idea.

**Comment by bobsilverberg** [comment]
@rebmullin and/or @willdurand I seem to recall some discussion about replacing the `PhotoSwipeGallery` with something else. Is that correct? If so, maybe this issue can be taken into consideration when looking at a new solution.

**Comment by rebmullin** [comment]
@bobsilverberg, yep, that's the plan (to replace the existing gallery)..

I think that's a good idea to maybe address/consider these all together. As as reference that issue is #1519. I'll add note in that one too..
