### ISSUE TITLE
Success message wrongly displayed on user profile edit page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5331]
### Describe the problem and steps to reproduce it:

- As an admin, go to a user profile edit page for a newly created user (without a profile picture)
- Navigate to your own edit page
- Refresh the page
- Go back to the previous page using the browser "back" button

### What happened?

The message "Picture successfully deleted" appears.

### What did you expect to happen?

No message.

### Anything else we should know?

Regular users are not affected, only admins (but it is quite convoluted so not easy to trigger).

**Comment by AlexandraMoga** [comment]
I've run the steps several times with a few users and the misplaced message didn't appear.
I'm marking the issue as verified fixed on AMO-dev with FF60, WIn10x64

![no misplaced error mess](https://user-images.githubusercontent.com/31961530/41919927-4d75cc7c-7968-11e8-981f-cb9ea4e4e184.gif)
