### ISSUE TITLE
Use thumbnails in Screenshots component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5338]
For obscure reasons, we don't use thumbnails in the `Screenshots` component, but full size images that are down-scaled to appear as thumbnails. The API returns both images and thumbnails, so we should use the thumbnails.

It is also worth mentioning that, as of this week, the API returns larger full size images. This will negatively impact the frontend performances because loading `N` big images as thumbnails will take time.

**Comment by vcarciu** [comment]
@willdurand  : can you please add some STRs for this issue or mark it as "qa: not needed" ?

**Comment by willdurand** [comment]
@vcarciu on an add-on detail page, the thumbnails should not be the same images as the ones displayed when you click a thumbnail. The thumbnails should be small images.

Example: https://addons-dev.allizom.org/en-GB/firefox/addon/octopar-troose-jagle/

**Comment by vcarciu** [comment]
Thanks @willdurand 
Verified as fixed : 
![thumbnails](https://user-images.githubusercontent.com/1583842/41782477-0647bcfc-7643-11e8-82e2-270bedbf25ac.gif)
