### ISSUE TITLE
Control local component state with Redux

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5343]
It's convenient to use `this.setState()` to change local component state. However, all uses of `setState()` will break Redux. By that I mean we will lose the ability for Redux to track our state changes. Here are things that will be broken:

* The Redux devtool will not let you time travel between state changes if you use `setState()`
* A future hypothetical error reporter (which would [send all state changes to Sentry](https://github.com/mozilla/addons-frontend/issues/2176)) would not know about `setState()` so it would not be very useful

**All components should use Redux instead of setState()**. 

There is one exception: capturing keystrokes in a text field. For this case, we should still use `setState()` but be sure to store the final typed value in Redux. This exception is because triggering all reducers on every keystroke could hurt performance.

**But, wait! I *love* `setState()` and I don't want to create reducer/action boilerplate just for one component.** 

I feel you. Thus, this issue will focus on an abstraction that lets you use something like `setState()` but with Redux under the hood. I looked at existing libs for this but they don't support SSR.

See https://github.com/mozilla/addons-frontend/issues/1250 for converting all of `setState()` to Redux.

**Comment by ioanarusiczki** [comment]
Verified the notes on AMO dev and AMO stage with FF61(Win10 and Android 8.0):  add, edit, delete - it seems to work without problems.
