### ISSUE TITLE
Specific user page doesn't work on dev

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5345]
### Describe the problem and steps to reproduce it:
getting 404 for https://addons-dev.allizom.org/en-US/firefox/user/c.cheng/

### What happened?
getting 404 for this specific user only

### What did you expect to happen?
user page will appear

### Anything else we should know?
happens if logged in or out.

if you look at legacy site, it comes up there. 

There may be other occurrences but so far only came across this one.

**Comment by willdurand** [comment]
Super good catch! I think it is an API issue though, because I get a 404 when calling the API with this username.

**Comment by rebmullin** [comment]
I think the culprit is the period in their name.  I see the following message when I try to change my username to have a period in it:

![Alt text](https://monosnap.com/image/UABZmj0WxpjQj9g7g2hJnrx2Smrzp3.png)

so we need to either change the dots to something else (or remove these) or see if this restriction can be removed.

**Comment by willdurand** [comment]
You should probably report this issue on addons-server.

**Comment by rebmullin** [comment]
yep - will do that..

**Comment by rebmullin** [comment]
moving issue to addons-server: https://github.com/mozilla/addons-server/issues/8607
