### ISSUE TITLE
Add UTM parameters to Disco Pane links

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#5346]
Per [this spec](https://docs.google.com/document/d/1zQddLWnKj4TyGOrEbECLlEENN0iljUjoBrGvDFz8yrI/edit), we should add UTM parameters to all links on disco pane, so they are easy to track in analytics dashboards.

There are 3 links I see that need this treatment.

Link to add-on listing on each Disco Pane entry:
* `utm_source=discovery.addons.mozilla.org`
* `utm_medium=firefox-browser`
* `utm_content=discopane-entry-link`
* `src=api` (not an UTM parameter, but it's used internally by AMO to track downloads in the stats dashboards for developers; looks like we dropped it at some point)

See More Add-ons button:
* `utm_source=discovery.addons.mozilla.org`
* `utm_medium=firefox-browser`
* `utm_content=see-more-link`
* `src=api` (not an UTM parameter, but it's used internally by AMO to track downloads in the stats dashboards for developers; looks like we dropped it at some point)

Link to Privacy Policy:
* `utm_source=discovery.addons.mozilla.org`
* `utm_medium=firefox-browser`
* `utm_content=privacy-policy-link`

The last one doesn't point to AMO, but the referral info could still be of use for people managing mozilla.org

**Comment by willdurand** [comment]
> Link to add-on listing on each Disco Pane entry:
> 
>     utm_source=discovery.addons.mozilla.org
>     utm_medium=firefox-browser
>     utm_content=discopane-entry-link
>     src=api (not an UTM parameter, but it's used internally by AMO to track downloads in the stats dashboards for developers; looks like we dropped it at some point)

I think this is done in addons-server, not in the frontend.

**Comment by ioanarusiczki** [comment]
@willdurand  Should we check anything in particular for the disco-pane? Could you add some STR?
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki yes, sorry:

- the `See More Add-ons` button should have UTM params as described in the issue description above
- the `Privacy Policy` link should have UTM params as described in the issue description above

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10)

> the See More Add-ons 
![utm parameters see more link](https://user-images.githubusercontent.com/33448286/42942302-177b056c-8b68-11e8-9ce1-2f77b48ad54e.png)

> the Privacy Policy
![privacy policy utm](https://user-images.githubusercontent.com/33448286/42942398-6d935166-8b68-11e8-8246-c3a390f24d56.png)
