### ISSUE TITLE
Favicon disappears sometime during browsing

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#5347]
### Describe the problem and steps to reproduce it:
I don't have any reproducible steps, just that while browsing AMO (new site), at some point its favicon will stop showing up in the tab bar for new page loads.

### Anything else we should know?
![capture](https://user-images.githubusercontent.com/8336638/41700003-2b2d4726-7544-11e8-8e86-22114ebc0522.PNG)
Fwiw, I can manually load `https://addons.cdn.mozilla.net/favicon.ico?v=2`. Don't know how to troubleshoot further.

**Comment by bobsilverberg** [comment]
I'm not sure how to troubleshoot this either. Perhaps QA could try to reproduce it?

**Comment by vcarciu** [comment]
We started to test this issue, but is was not reproducible for us.

@FatOrangutan : can you please tell us if you have any specific add-ons installed?

Thanks

**Comment by FatOrangutan** [comment]
It only just occurred to me to check if my adblocker is interfering, and indeed it was. Fanboy's Enhanced Tracking List has a filter for `/favicon.ico$third-party,image,domain=~reddit.com|~4chan.org|~twitter.com|~live.com|~espn.com`.

Sorry for the noise. I should have checked this prior to reporting. Closing the issue now.
