### ISSUE TITLE
Add 'pagination' state to the addonsByAuthors reducer/saga

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5353]
In order to address #4809, we need to be able to paginate the results shown in the `AddonsByAuthorsCard`. In order to do that, the `addonsByAuthors` needs a few changes, such as:

- adding `pageSize` as a required argument to `fetchAddonsByAuthors()` in order to pass this value from the UI
- adding `page` and `sort` arguments (optional) to `fetchAddonsByAuthors()` to be able to paginate the add-ons related to a user
- adding `countFor` attribute to the state, which is designed like `loadingFor`
- passing `count` and `pageSize` to `loadAddonsByAuthors()`, `pageSize` was computed two times before, now this value is defined once in the UI and passed everywhere
- adding a `getCountForAuthorNames()` selector, similar to `getLoadingForAuthorNames()`

For QA: please make sure that the addons by authors listed in the user profile AND the add-on detail page still work as intended, in other words: there should be not difference and add-ons should be displayed as before.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF60(Win10 and Android 8.0)
