### ISSUE TITLE
Disable ESLint rule `react/sort-comp` globally

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5357]
The [`react/sort-comp` rule](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/sort-comp.md) often forces us to either disable it or to write code we did not want to write in the first place (for example, adding attribute declarations in the middle of a class, not at the top of it).

We should disable this rule globally.

**Comment by muffinresearch** [comment]
@willdurand can this also be ported to [eslint-config-amo](https://github.com/mozilla/eslint-config-amo)?

**Comment by willdurand** [comment]
I was hesitant because maybe it was addons-frontend specific, but sure, I will do that!
