### ISSUE TITLE
clean up / remove any lightweight theme logic once migration is ready

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5359]
### Describe the problem and steps to reproduce it:

There is code specific to lightweight themes which I believe can be removed once the migration is ready:

there is some logic that defines valid types, which includes persona. We should be able to remove and replace with statictheme. 

remove all the themedata set up that lightweight themes is using

update the search filter

other stuff?

---

**For QA:** please make sure all pages with static themes behave as before. There should be no obvious regression. In addition, here is a list of "known changes":

- [search result pages with "recommended" themes](https://addons-dev.allizom.org/en-US/firefox/search/?platform=mac&recommended=true&type=statictheme) should have a new HTML title ("Recommended themes" instead of "Recommended add-ons")
- the contribution card on [a static theme detail page](https://addons.mozilla.org/en-US/firefox/addon/matte-black-v2/) now shows "Support this artist" rather than "Support this author" (bug fix, yay)

**Comment by kumar303** [comment]
> there is some logic that defines valid types, which includes persona.

Just FYI, this logic has been intertwined in surprising ways over the history of the code base so removing it may not be so trivial.

**Comment by kumar303** [comment]
See https://github.com/mozilla/addons-frontend/pull/7627 for some initial removal

**Comment by diox** [comment]
The migration happened some time ago, can we make some progress on this now ? We assumed we could remove most of the personas-related code in addons-server, and it caused https://github.com/mozilla/addons-frontend/issues/8480, which forced us to add back a hack pretending some lightweight theme categories still exist.

**Comment by muffinresearch** [comment]
This will need further investigation, but in looking at this today, It might be worth considering if it would be easier to change the `ADDON_TYPE_THEME` from `persona` to `statictheme` and remove the `ADDON_TYPE_STATIC_THEME` instead of the other way around.

**Comment by diox** [comment]
I suspect a few of these occurrences are hack to work around the subtleties of personas though. I think it's worth double-checking each.

**Comment by willdurand** [comment]
> - the contribution card now shows "Support this artist" rather than "Support this developer" (bug fix, yay)

@jvillalobos I am not sure whether we have static themes with "contribution cards", but I think we should had have that when we introduced the static themes. Thoughts?

**Comment by willdurand** [comment]
> We do support contributions for themes. [Here are the ones](https://sql.telemetry.mozilla.org/queries/65715/source#166931) that have it enabled, and I see the button in their page.

Awesome, thanks. So the change I quoted above is related to this contribution card. We will change from "Support this author" to "Support this artist". Does that sound right to you?

**Comment by jvillalobos** [comment]
Yeah, the current card is generalized to "author", so I don't think we need to make any changes to it.

**Comment by willdurand** [comment]
> Yeah, the current card is generalized to "author", so I don't think we need to make any changes to it.

ah wait, so you would like to keep "author" and "add-on" instead of "artist" and "theme" for static themes?

**Comment by jvillalobos** [comment]
Correct. We worded that card in a way that would work for all add-ons on the site.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage. I haven;t found regressions around the theme related features.

the mentioned changes are also visible:

![image](https://user-images.githubusercontent.com/31961530/68395533-8ce8ed00-0178-11ea-86f5-2070afa01fa1.png)

![image](https://user-images.githubusercontent.com/31961530/68395544-91ada100-0178-11ea-88a2-5ce83f8b172e.png)
