### ISSUE TITLE
UI for voting for user reviews (helpful / not helpful)

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#5360]
[Ratings PRD](https://docs.google.com/document/d/1oUz9Ng9v159IPdW4UqHhbNspWa9m5SaicAAX5jU7OjA/edit#heading=h.z6eh8thy43a6).

Logged in users should be able to vote on a user review's helpfulness, up or down, once. They can't vote for reviews they wrote, or for add-ons they have authored. They should be able to undo or change their vote. The UI should show if a review was previously voted on by that user.

If positive, the usefulness score for each review should be shown as "N users found this review useful."

**Comment by tiansh** [comment]
May a review be edited after getting voted? What will happen to the voting count if someone edited the review to something else? Is there a way to checkout history of edition?

**Comment by jvillalobos** [comment]
We currently have no plans to work on this issue (and others related to it). You bring up a good point, though. It's a separate issue, but we should probably not allow editing reviews, or only allow it for a short timeframe.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-134
