### ISSUE TITLE
"About this theme" should be displayed for static themes 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5364]
Moving https://github.com/mozilla/addons-server/issues/8554 to front-end
STR:
1. Load AMO dev and go to a static theme's listed page
2. Observe that the same text is displayed at the summary (text at the left of the Install Button and into the "Above this theme" section)

Expected result:
"About this theme" section is not displayed.

Actual result:
About this theme section is available and repeats the same description as the summary on the left side of the Install button.

Notes:
This issue is reproducible on AMO dev with FF60(Win10). 
![about this theme](https://user-images.githubusercontent.com/33448286/41780932-cd03771e-763e-11e8-8b36-e9e5da7ed21b.png)

**Comment by rebmullin** [comment]
hey @jvillalobos, can you please advise on this?

FYI, we have the same for lightweight themes:
![Alt text](https://monosnap.com/image/4RLUFZYGWXU7jxPjVJj8eXmBlXPiMr.png)

**Comment by jvillalobos** [comment]
I don't remember if we decided to have both a summary and description for static themes, or just one of them. @eviljeff?

We should remove the duplication either way. So, if we only have a one field, remove the "About this theme" module. If we have both, then there's a possibly bug in their display.

**Comment by eviljeff** [comment]
@jvillalobos you said just one of them, like personas.  I can't find where it was discussed though.  If you really want both summary and description it wouldn't be terribly difficult to make the change in edit listing to expose it again.  But for most themes even the summary will be unused (though it is required so I guess we'll get lots of "." and "    " summaries.

The duplication is the same as LWT now, though, isn't it?  Maybe it should be dropped for LWT too?

**Comment by jvillalobos** [comment]
Yes, I think we should drop the "About this theme" module for both. /cc @pwalm @MeridelW for confirmation.

**Comment by pwalm** [comment]
This is fine for now, but when we reduce the summary text to just be a subtitle (like ~30 characters) in the not-too-distant future, the longer copy of the summary (some people really go for it and write a paragraph) will have to live in the "About this theme" area.

If anything, it makes more sense to kill the summary text area for themes and move that copy into the "About this theme" area.

**Comment by jvillalobos** [comment]
If the plan is to reduce the summary length and encourage devs to write a description, then it sounds that the better solution in this case is to enable the description field for static themes, and show that in the "About this theme" area for those (I don't think we can do this easily for LWT). We can drop that area for LWT only.

**Comment by eviljeff** [comment]
I'm not really convinced most themes designers will need more than 30 characters anyway, but I'll re-open mozilla/addons-server#8554 then so they can add a description in devhub.  

imo I'd leave LWT as now, if that's easier/more consistent, and just change for static themes.  The property is already in the API, so there's no blocker on the addons-server side to make API changes

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10).

![about this theme2](https://user-images.githubusercontent.com/33448286/42170336-ed3f480e-7e1e-11e8-9c34-f2efab475e24.png)

**Comment by willdurand** [comment]
@ioanarusiczki why is it fixed?

**Comment by pwalm** [comment]
Let's just not show dupe text. I don't really care at this point whether the copy shows up in the short desciption, the "About this theme", or (if the creator has filled out both) both. Let's just not duplicate it to fill space.

**Comment by rebmullin** [comment]
@pwalm, thanks for the update. I will remove dupe text (for both themes types)
