### ISSUE TITLE
Update the "Get the add-on" Badge

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#5370]
As mentioned in this [discourse thread](https://discourse.mozilla.org/t/get-download-addon-for-firefox-badge-button-to-embed-into-website/28162), we have a "Get the add-on" badge for developers to add to their websites and link directly to the extension detail page on AMO. It needs to be visually updated to match [Photon](https://design.firefox.com/photon), but I'm wondering if it needs to live somewhere else more permanent (other than the original blog post on The Mozilla Add-ons Blog)?

**Comment by jvillalobos** [comment]
The button is a useful asset to developers, so we should probably have it available on some documentation page or repository. Maybe MDN is a good enough (temporary) home for it?

**Comment by atsay** [comment]
Let's put it on MDN and point to it in the announcement section of signed-in AMO dev hub. Fyi @mconca @caitmuenster

**Comment by mconca** [comment]
Dev Launch Pad to-do:  find home for this (and maybe other dev-related assets).

**Comment by caitmuenster** [comment]
This looks good. FYI, I'm removing the "good first bug" label until this is ready to go (which will be during the next dev hub content update).

**Comment by MeridelW** [comment]
- Do theme developers also use this button? 

- What terminology are developers using on their own websites? Do the majority describe their add-ons as an 'add-on' or as an 'extension'? 

I ask these questions because we may want to update button copy to: "Get Extension"

**Comment by caitmuenster** [comment]
@jvillalobos might be the best person to answer that question (he's out on holiday today). 

Generally speaking, I think most developers who list their extension on AMO drive users to download from AMO because that's where they are managing current releases; developers of unlisted extensions link directly to the XPI because they are self-distributing.

**Comment by jvillalobos** [comment]
I don't think we have a good notion of what developers are linking to. I've seen both cases in the wild. Regarding the broken links, there's a way to get a "permalink" to the latest version of an add-on without linking to a specific version number. Unfortunately we're not exposing that link in the current front-end (https://github.com/mozilla/addons-frontend/issues/4083), so developers are unlikely to know about it.

**Comment by MeridelW** [comment]
Thanks, @jvillalobos. I think my work is done here regarding copy for the button. 

Regarding permalink, do you think those will be exposed in the future?

**Comment by jvillalobos** [comment]
Yes, we should probably fix that issue before shutting down the old front-end (so, this year).

**Comment by willdurand** [comment]
@jvillalobos @caitmuenster according to [this issue](https://github.com/mozilla/addons/issues/1157), I think we can close this one?

**Comment by caitmuenster** [comment]
Yes, I think we can go ahead and close this! Thanks @willdurand
