### ISSUE TITLE
Download Firefox button is squished on mobile screens

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5371]
### Describe the problem and steps to reproduce it:

* Load any page of the site on a non-Firefox mobile browser (Chrome, Safari, etc)

### What happened?

The Download Firefox button is squished and the text is broken across lines.

<img width="326" alt="screenshot 2018-06-22 13 57 17" src="https://user-images.githubusercontent.com/55398/41794735-fc10dc36-7625-11e8-94c7-6a467fa55de9.png">

### What did you expect to happen?

The text should appear on one line

### Anything else we should know?

I think this was a regression from https://github.com/mozilla/addons-frontend/issues/5306

**Comment by vcarciu** [comment]
Verified as fixed : 
![downloadfirefox](https://user-images.githubusercontent.com/1583842/41899594-861acbfa-7935-11e8-8b02-f4d4260f7985.png)
