### ISSUE TITLE
Send add-on GUID to Firefox install page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#5374]
When users visit a listing page with a browser that isn't Firefox, they get a Firefox install button that points to mozilla.org.

In order to support the Return to AMO project, we need to add `utm_content=ADDON_GUID` to the URL parameters. This project is still being planned and will probably land late in Q3, so this issue is blocked on product decisions.

**Comment by vcarciu** [comment]
Verified as fixed : 
![utmuuid](https://user-images.githubusercontent.com/1583842/45302201-5505fb80-b51b-11e8-9bb2-6086ea956313.png)
