### ISSUE TITLE
Implement EULA view

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#5376]
When you click on a license agreement link on a listing page (like [this one](https://addons.mozilla.org/addon/sovetnik/)), the old site is shown. We should open a EULA page or show it inline. I suppose the same approach would apply for this and the privacy policy (#1828). /cc @pwalm for ux.

**Comment by bobsilverberg** [comment]
API support is available via http://addons-server.readthedocs.io/en/latest/topics/api/addons.html#add-on-eula-and-privacy-policy.

@pwalm I think we need a mockup for this.

**Comment by pwalm** [comment]
EULA/License/Privacy Policy page:
![privacy policy page - 1366px](https://user-images.githubusercontent.com/6797635/43019682-a90125e8-8c12-11e8-9a03-db0870a29791.png)

**Comment by muffinresearch** [comment]
Duplicate of #3697
