### ISSUE TITLE
where did it go? Don't tell me they dropped it.

### ISSUE THREAD

**Issue by CodeManDeluxe** [mozilla/addons-frontend#5378]
### Anything else we should know?

**_Last.fm SoundCloud Scrobbling_**

**Comment by championshuttler** [comment]
Hi @CodeManDeluxe , I think developer deleted the addons from AMO sadly . And in this case we can not do anything. I tried to find some alternate for it. Please check the second answer of this question. May be this can help you https://www.quora.com/How-do-you-scrobble-from-Soundcloud-to-Last-fm-without-Extension-fm.
Let me know if it works :) 
Thanks
Shivam
