### ISSUE TITLE
Clarify headings and placeholder text for My Collections screen

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5381]
The current mockup for the "My Collections" screen has identical headings for the "info" card on the left and the "listing" card on the right, both of which is "My Collections". This seems a bit odd, so I'm looking to see if anyone (i.e., @pwalm or @MeridelW) has any ideas about improving it. See the screenshot below for an example.

As well, no placeholder text was specified for when a user has no collections, so I've gone with a simple "You do not have any collections.", but perhaps @MeridelW has some better ideas for that too.

Screenshot with collections (notice the duplicated header):

![screenshot 2018-06-23 14 19 48](https://user-images.githubusercontent.com/142755/41812425-83c7cb38-76f0-11e8-82bb-4d154a6af45a.png)

Screenshot with placeholder text:

![screenshot 2018-06-23 14 34 04](https://user-images.githubusercontent.com/142755/41812529-82b9b9fc-76f2-11e8-8227-c39743d570e2.png)

**Comment by willdurand** [comment]
> The current mockup for the "My Collections" screen has identical headings for the "info" card on the left and the "listing" card on the right, both of which is "My Collections". This seems a bit odd, so I'm looking to see if anyone (i.e., @pwalm or @MeridelW) has any ideas about improving it. See the screenshot below for an example.

At the very least (and I'd say it should be part of #5309), the left card (with the create button) should be named "About collections" because that's basically the aim of this card according to the copy inside.

**Comment by bobsilverberg** [comment]
Sure, I can make the current heading be "About collections" pending a response to this issue.

**Comment by pwalm** [comment]
Let's just make it "Collections"

**Comment by bobsilverberg** [comment]
Latest screenshot with new headings:

![screenshot 2018-06-27 12 36 33](https://user-images.githubusercontent.com/142755/41987330-cfb20324-7a06-11e8-987d-b12273899987.png)

**Comment by bobsilverberg** [comment]
This has all been resolved.

**Comment by vcarciu** [comment]
@bobsilverberg : tje distance between collections looks bigger in your screenshots than what I see on my collections card. Please let me know if this is ok.
![coldistance](https://user-images.githubusercontent.com/1583842/42575558-7ace0fc8-8529-11e8-9171-a811d9a5d7fd.png)

**Comment by vcarciu** [comment]
@bobsilverberg : thanks
