### ISSUE TITLE
AddonsByAuthorsCard does not look nice on small screens

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5382]
Browse an add-on with "other add-ons by authors", e.g., http://localhost:3000/en-US/firefox/addon/enhancer-for-youtube/?src=recommended_fallback or a user profile, e.g., http://localhost:3000/en-US/firefox/user/l4/ using a device with a small screen.

User profile (no ratings 😞)

<img width="461" alt="screen shot 2018-06-23 at 23 05 21" src="https://user-images.githubusercontent.com/217628/41813635-2631ddf2-773a-11e8-95be-7396154daabe.png">

Add-on detail page (weird layout)

<img width="461" alt="screen shot 2018-06-23 at 23 05 23" src="https://user-images.githubusercontent.com/217628/41813636-264f202e-773a-11e8-9df0-bd2592799d35.png">

It is not consistent with the rest of the website. As far as I remember, the layout of this component was "special" according to some older mock-ups, but there is no reason to have a different layout on small screens.

**Comment by vcarciu** [comment]
Verified as fixed : 
![morebyauthorpostfix](https://user-images.githubusercontent.com/1583842/41972634-1627e58a-7a1b-11e8-93b5-11a898987407.png)
![noratingpostfix](https://user-images.githubusercontent.com/1583842/41972640-199a3056-7a1b-11e8-90b0-24dcd7f5c093.png)
