### ISSUE TITLE
Two buttons to edit a collection note

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5386]
### Describe the problem and steps to reproduce it:

1. Create a collection at: http://localhost:3000/en-US/firefox/collections/add/
2. Add one add-on to the collection
3. Click the "comment"/"note" icon to leave a note about this add-on in the collection
4. Save the note

### What happened?

We see an "edit" button but the original button to add a note is still visible (the icon):

![screen shot 2018-06-25 at 11 41 49](https://user-images.githubusercontent.com/217628/41843113-f2ab5998-786c-11e8-8b52-1ad41b4d5d1c.png)

### What did you expect to happen?

The icon should not be visible anymore:

![screen shot 2018-06-25 at 11 41 49](https://user-images.githubusercontent.com/217628/41843138-040a43c0-786d-11e8-9ab4-7cb160b892b1.png)

**Comment by mann27** [comment]
I am not able to find where to change the code and also I am not able to understand the steps..can someone explain me. Thanks.

**Comment by caitmuenster** [comment]
Hey @mann27, we're not sure if this one is a good first bug yet. Want to take a look at some other known [good first bugs](https://waffle.io/mozilla/addons?label=contrib:%20good%20first%20bug)? 

@pwalm, can you confirm what the expected behavior should be?

**Comment by pwalm** [comment]
The icon should be changed into a button that reads "Leave a note". When the collection creator leaves a note, the copy should change to "Edit note". The "edit" button in the bottom right becomes redundant and is no longer needed.

**Comment by bobsilverberg** [comment]
FYI, this has been fixed by PR #5569 which is currently in review.

**Comment by caitmuenster** [comment]
Thanks @bobsilverberg!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev and AMO stage with FF61(Win10 & Android 8.0). 
![no icon](https://user-images.githubusercontent.com/33448286/42867402-3002a61c-8a78-11e8-935b-38fedeedcebf.png)
