### ISSUE TITLE
Last updated date can be `null` on an add-on detail page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5387]
I guess this only occurs when browsing the add-on detail page of an add-on with self-hosted versions (for instance, when creating and signing a brand new extension with `web-ext`):

![screen shot 2018-06-25 at 12 16 38](https://user-images.githubusercontent.com/217628/41844857-d582d5e4-7871-11e8-926d-6fe5267af490.png)

It shows "invalid date" in the "More information" card.

**Comment by vcarciu** [comment]
I created and signed a self hosted webextension using _webext_, but the Last update date is correctly displayed for me : 
![lastupdate](https://user-images.githubusercontent.com/1583842/41962986-1b786648-79ff-11e8-9ece-0ab4890dca2e.png)

@willdurand  : can we mark the issue as verified with this scenario?

**Comment by willdurand** [comment]
> @willdurand : can we mark the issue as verified with this scenario?

I think so, yes.

**Comment by vcarciu** [comment]
@willdurand : thanks
