### ISSUE TITLE
Add-on custom icons are not correctly displayed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5388]
Moving issue https://github.com/mozilla/addons-server/issues/7956

STR:
1. Go to Edit images in dev hub for a submitted ad-on
2. Upload a .jpg sample from edit images using upload a custom icon button
3. Save changes and click on View Listing
4. Observe the icon on the ad-on detail page

Actual result:
Images look a bit squashed.

Expected result:
Images are correctly displayed.

Notes:
This issue was reproducible for the user info card but then fixed [here](https://github.com/mozilla/addons-frontend/issues/4598).
This issue is reproducible with .jpg and .png samples with normal size and dimension, it is more obvious for images with a larger width.
This is reproducible on AMO dev with FF59(Win10).

![picture squashed](https://user-images.githubusercontent.com/33448286/41848506-56041f3e-7886-11e8-885e-e208989add18.png)

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @willdurand

**Comment by ShivangiKakkar** [comment]
Hey, I am new to contributions for Mozilla. I would love to work on this issue, can I be assigned this issue, please?

**Comment by ShivangiKakkar** [comment]
Thank you! @championshuttler 
Working on it. :)

**Comment by ShivangiKakkar** [comment]
Hey @championshuttler, I wanted to clear few doubts I am facing:
1.) Expected result: Images look a bit squashed? 
2.) When I click on dev hub it is showing an error saying, "This page does not exist in addons-frontend."
3.) Same error if I try to submit a new add-on.

**Comment by ioanarusiczki** [comment]
@ShivangiKakkar 1. I corrected the expected result - I switched the actual with expected - now it's alright. Thanks!
2. &3.&4.  For AMO dev https://addons-dev.allizom.org/en-US/firefox/ - I don't encounter this problem just make sure you have an account and sign in then click on Developer Hub and go to Submit an new add-on. Try with https://staticfil.es/webext-generator/ to download a dummy extension to test with.
Let me know if you succeeded !
Ioana

**Comment by championshuttler** [comment]
Hi @ShivangiKakkar 
 Sorry expected result is  Images are correctly displayed. I think @ioanarusiczki mentioned it by mistake ;)
 For devhub you need to go to https://addons-dev.allizom.org/en-US/developers. 
 For test-addon you can use this tool https://staticfil.es/webext-generator/

**Comment by ShivangiKakkar** [comment]
Thanks :) @championshuttler  & @ioanarusiczki

**Comment by ShivangiKakkar** [comment]
Hey, @championshuttler 
I am almost done with the issue, I am about to file PR.
Do I need to write a test case for it too?

**Comment by championshuttler** [comment]
Hey @ShivangiKakkar , it would be great with test case or you can add it while reviewing phase ;)

**Comment by willdurand** [comment]
Amazing, thanks for contributing @ShivangiKakkar!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10)
It sure looks way better now! Thanks @ShivangiKakkar 

![sample one](https://user-images.githubusercontent.com/33448286/44345076-f2c95600-a49a-11e8-8971-28903bc15188.png)

![sample two](https://user-images.githubusercontent.com/33448286/44345087-fbba2780-a49a-11e8-81f4-c62fa27b66be.png)
