### ISSUE TITLE
Different URLs for "Manage firefox account" links in legacy and new frontend.

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5390]
Steps to reproduce:
1.Login to AMO-dev
2.From Edit Profile, click the "Manage firefox account" link from both new frontend and legacy frontend
3.Observe the URLs

Expected results:
URLs are the same

Actual results:
Links are different (https://accounts.firefox.com/settings for new frontend, https://stable.dev.lcip.org/settings for legacy frontend)

Please see a photo of this bug :
![fxa](https://user-images.githubusercontent.com/1583842/41850897-e2fbc664-788e-11e8-828b-026e7338db8a.png)

**Comment by willdurand** [comment]
@eviljeff I see that we're using an undocumented endpoint for login (`/accounts/login/start/`), which is convenient because we don't have to know the FXA url (we pass a `config` query parameter instead).

Would it be possible to expose this FXA url somewhere so that we don't have to know it in addons-frontend? Would that make sense?

**Comment by eviljeff** [comment]
Expose where?

**Comment by willdurand** [comment]
> Expose where?

"somewhere" 😅 – I don't know, maybe in the user profile response.

**Comment by eviljeff** [comment]
Can you file an addons-server bug?  Mention if you just want the server address (like frontend shows now) or the full url with params for email and fxa_id (like legacy shows)

**Comment by willdurand** [comment]
Please see: https://github.com/mozilla/addons-server/issues/8674

**Comment by vcarciu** [comment]
Now I can see same link for both legacy and new frontend(https://stable.dev.lcip.org/....) , but I receive this error in the console:
![errorfxa](https://user-images.githubusercontent.com/1583842/47437231-cb4f7c00-d7b0-11e8-80db-46dc970c21c7.png)

@willdurand do you think that the issue is related to this fix? Because I don't remember to see this error before

**Comment by willdurand** [comment]
> Now I can see same link for both legacy and new frontend([stable.dev.lcip.org](https://stable.dev.lcip.org/)....) , but I receive this error in the console:

That looks weird, I've never seen this before. It is not related to our code.

**Comment by willdurand** [comment]
> @willdurand : do you think that a FXA bug is needed here?

I don't know. Is this error preventing you from getting access to your FxA account?

**Comment by vcarciu** [comment]
I don't know. Is this error preventing you from getting access to your FxA account?

Nope

**Comment by willdurand** [comment]
Then, I guess it is alright :)
