### ISSUE TITLE
Express Flow external/internal prop types more concisely

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5398]
As a follow-up to https://github.com/mozilla/addons-frontend/issues/5342, intoduce a more concise pattern for expressing external and internal component props.

**Comment by willdurand** [comment]
> As a follow-up to #5342, intoduce a more concise pattern for expressing external and internal component props.

Could you maybe document a bit? I guess we don't want to use `InjectedProps` anymore?
