### ISSUE TITLE
Link is dead and returns a 404 "page not found error," and states that the add-on was removed by it's author.

### ISSUE THREAD

**Issue by TotalEclipseStudios** [mozilla/addons-frontend#5403]

**Comment by TotalEclipseStudios** [comment]
Visited this web site here -->http://www.notebookreview.com/news/top-10-google-chrome-extensions-for-better-faster-browsing/ Clicked a link to Fasterfox that took me here, -->   https://addons.mozilla.org/en-US/firefox/addon/9825/ Which returns with "Page Not Found" error on the top left of the page, with the statement, and I quote, "This Add-on has been removed by its Developer." So apparently the link is now dead. (See Included Screenie)
![add-on removed by it s author dead link](https://user-images.githubusercontent.com/34611561/41906663-6ff5585a-790c-11e8-9757-3de6e2658bfd.png)

**Comment by bobsilverberg** [comment]
If the add-on has been removed then you are seeing the correct page.
