### ISSUE TITLE
Should static themes have contribute cards

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5409]
it seems we can add a contribution url (via edit screen) for a static theme - is this expected? as far as I could tell, this option is not available on lightweight themes

![Alt text](https://monosnap.com/image/as9soSOGXdv3sWocZlnZEMtHrJ3icL.png)

@jvillalobos

**Comment by jvillalobos** [comment]
Yes, this should be allowed.

**Comment by rebmullin** [comment]
great - thanks. closing since this does this already : )
