### ISSUE TITLE
The AddonsCard on the Collection Detail page shows an empty footer

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5413]
When there are fewer add-ons in a collection than are required to show the `Paginate` component, an empty footer is displayed instead.

![screenshot 2018-06-26 13 46 32](https://user-images.githubusercontent.com/142755/41929844-5de32670-7947-11e8-8fd2-60f85dcf57ce.png)

I believe this is a regression introduced in https://github.com/mozilla/addons-frontend/commit/ec24c583a04d9c3c16e063bbc68aaf098028ed54 and it may impact pages other than the Collection Detail page, but I haven't checked any others.

**Comment by willdurand** [comment]
> I believe this is a regression introduced in ec24c58 and it may impact pages other than the Collection Detail page, but I haven't checked any others.

Yes, I am aware of that small issue, and I have it noted on a post-it... It is indeed a problem with the paginator being injected in the `footer`.

**Comment by ioanarusiczki** [comment]
I verified on AMO dev with FF61(Win10) the collections from AMO homepage, the "see more" links , and personal collections created by a user and did not see the presence of the empty footer.

![no white border](https://user-images.githubusercontent.com/33448286/42510359-531bcfa6-8457-11e8-9eca-1042c5ee1452.gif)
