### ISSUE TITLE
Static theme badge text should match lightweight theme's badge text

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5417]
### Describe the problem and steps to reproduce it:
Find a featured lightweight theme
![Alt text](https://monosnap.com/image/LVYyN6T70XS71Kl25Or2kNdQrxHzQm.png)

Find a featured Static theme
![Alt text](https://monosnap.com/image/Og8d8oVS5u2npB06uqaOmNqOygEXUo.png)

Compare the "Featured xxx" text

### What did you expect to happen?

These should be both say "Featured Theme"

hey @pwalm , can you also advise about the icon here? Will this be the same regardless of the type? I may be misremembering but I thought I heard this * might * be different so just wanted to verify

**Comment by pwalm** [comment]
Nope, the icon should stay the same. The icon and text should sit under the theme though, and the theme preview should be full width (w padding) to the block.

**Comment by vcarciu** [comment]
Verified as fixed : 
![featstatictheme](https://user-images.githubusercontent.com/1583842/42567819-bbc3c93e-8513-11e8-8d4f-80fda900b5bc.png)
