### ISSUE TITLE
User is redirected to collections old page after log out and then log back in 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5420]
STR:
1. Load AMO dev and click on View my Collections from the drop down menu below the user name.
2. Log out and click the Log in to view you collection button.
3. Sign in and observe the page displayed.

Expected result:
The new collection page with the list of personal collections reappears.
Actual result:
The old collection is displayed https://addons-dev.allizom.org/en-US/firefox/collections/

Notes:
This issue is reproducible with AMO dev on FF60(Win10&android 8.0)

![log out and login collections](https://user-images.githubusercontent.com/33448286/41965660-bf44182a-7a05-11e8-991d-c33b1d53014b.gif)

**Comment by bobsilverberg** [comment]
This should be fixed by adding a route to collections/ as I just requested in issue #4655.

**Comment by bobsilverberg** [comment]
This should now be fixed.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I tested this on AMO dev with FF61(Win10) with 3 different accounts (an admin and two developer accounts). With all accounts I've tested I can confirm that repeating the log in and log out sometimes the new page is displayed and other times the old collection page too.

Here's a demo
![second trial](https://user-images.githubusercontent.com/33448286/42210682-50a99598-7eba-11e8-8115-594aca5b0240.gif)

**Comment by bobsilverberg** [comment]
This is very odd, but I was also able to reproduce it. After logging out and back in twice, the third time I was taken to the old /collections page. The same thing happens if you hard-refresh the page. Sometimes it shows you the legacy /collections page.

@kumar303 do you have any idea what could be causing this? Could it be a browser or CDN caching issue?

**Comment by kumar303** [comment]
We had a ghost nginx server instance which did not have the updated config. It's fixed now. This has happened before (only on dev) so I filed an issue to try and fix it: https://bugzilla.mozilla.org/show_bug.cgi?id=1473145

**Comment by ioanarusiczki** [comment]
I cannot reproduce the problem above. Verified fixed on AMO dev with FF61(Win10).

![fixed](https://user-images.githubusercontent.com/33448286/42271045-09875a02-7f8b-11e8-8358-e27fcff3a6fa.gif)
