### ISSUE TITLE
Add a `.prettierignore` file to tell Prettier not to process some files

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5423]
As @bobsilverberg pointed out on IRC, Prettier should not process the locale files (because it does not do anything anyway and it is a waste of time).

We should create a `.prettierignore` file with the following content:

```
src/locale/
```

**Comment by bobsilverberg** [comment]
Let's add all files/folders that we intend to ignore to this, not just `src/locale/`.

**Comment by gabru-md** [comment]
It is fairly simple, I can take this issue up.
Can you point me to the discussion where all the files to be ignored are listed? :sweat_smile:

**Comment by willdurand** [comment]
> It is fairly simple, I can take this issue up.
> Can you point me to the discussion where all the files to be ignored are listed? 😅

Actually, it is not trivial since it is not only about the locale files. I have started to look at it and the Prettier ignore file has more than 20 lines already :/
