### ISSUE TITLE
Creating a new collection named "favorites" will generate a 404 on the new frontend

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5424]
STR:

1. Log in to AMO -dev with a user that doesn't have a 'My favorite add-on' collection
2. Go to My Collections and click on Create Collection
3. Enter _favorites_ in the collection name field
4. Click on Create Collection

Actual result:
A Page not Found is displayed

Expected result:
The user remains on the same screen and continues to edit his collection

Notes:
 - reproduced on AMO -dev with FF60, Win10x64

![favorites 404](https://user-images.githubusercontent.com/31961530/41974007-5fcf7f5a-7a1f-11e8-894e-3653deb83d9e.gif)

**Comment by bobsilverberg** [comment]
What seems to be happening is that when we submit the API request to the server to create a collection with the slug `favorites`, it actually creates a collection with the slug `favorites~`, I assume because `favorites` had a special meaning on the legacy site. 

@eviljeff Is this something we can fix on the server side? Do we still need to prevent users from creating a collection with a slug of `favorites`?

**Comment by eviljeff** [comment]
`favorites` is still a special slug unfortunately until the favorites code is removed.  https://github.com/mozilla/addons-server/issues/6496 was intended to cover that, but that was going to be done after the legacy pages are dropped entirely.  If this is sufficiently big problem please file a server issue and we'll look into pulling forward the deprecation of that feature.

**Comment by kumar303** [comment]
> it actually creates a collection with the slug `favorites~`

The quickest fix on the frontend is just to do this, I guess.

**Comment by kumar303** [comment]
But our code might have a legit bug in it where it redirects to the *requested* slug, not the actual slug from the API response.

**Comment by bobsilverberg** [comment]
This is a good point that I hadn't thought of @kumar303. We really should be doing that (and we're not), and that will also fix the issue. I'm on it.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64

A collection named `favorites` can be created and will be saved under `https://addons-dev.allizom.org/en-US/firefox/collections/<user>/favorites~/`

![fav coll](https://user-images.githubusercontent.com/31961530/43139743-4260561e-8f5b-11e8-9848-6b278a6f4751.gif)
