### ISSUE TITLE
New created collection does not appear on My Collections page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5425]
STR:

1. Log in to AMO -dev
2. Go to View My Collections and click on Create a collection
3. Fill in the necessary fields and Save the new collection
4. From the user menu, select View My Collection
5. Check if the new collection is present in the list

Actual result:
The new collection is not listed in My Collections

Expected result:
The new collection is listed in My Collections

Notes:
- if you click again on Create a Collection, the form will display the values of the collection previously created
- both issues will be solved if the page is refreshed
- reproduced on AMO -dev with FF60, Win10x64

![create a collection reset](https://user-images.githubusercontent.com/31961530/41972728-62794550-7a1b-11e8-96a6-8a7d0ae56046.gif)

**Comment by vcarciu** [comment]
Verified as fixed : 
![collections](https://user-images.githubusercontent.com/1583842/42567649-1ca79394-8513-11e8-930c-572b357a5086.gif)
