### ISSUE TITLE
Change rating count to review count on add-on detail page

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#5434]
<img width="1071" alt="screen shot 2018-06-27 at 11 01 58 am" src="https://user-images.githubusercontent.com/6797635/41991263-a806562a-79f9-11e8-8968-28aeea8f4a61.png">

- Change the "Ratings" count on the detail page to a "Reviews" count.
- Make the "Reviews" text and accompanying number clickable, linking to the all reviews page.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64 and Android 8.0
- Ratings count replaced with Reviews count, the number including only written reviews
- both the 'number' and the Reviews link are clickable and are opening the reviews page for the visited add-on

![reviews link](https://user-images.githubusercontent.com/31961530/44325333-31dab580-a461-11e8-980b-59ff447fc6c3.gif)
