### ISSUE TITLE
Making rating stars yellow

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#5435]
<img width="1071" alt="screen shot 2018-06-27 at 11 01 58 am" src="https://user-images.githubusercontent.com/6797635/41991443-466f5e2e-79fa-11e8-8cab-c725f6d566ac.png">

Make the rating stars on the detail page yellow:
filled: RGBA: 255,233,0,100
empty: RGBA: 255,233,0,25

**NOTE**: the wording, *4 star average*, will be handled in https://github.com/mozilla/addons-frontend/issues/5436

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win 10&Android 8.0)

@kumar303 I couldn't find using the Inspector the RGBA values as mentioned above for the rating stars. 
> filled: RGBA: 255,233,0,100
empty: RGBA: 255,233,0,25

For the rating bar, I found rgba(255, 233, 0, 0.75) - yellow. 
The rating stars have : rgb(29, 29, 29) and rgba(0, 0, 0, 0); 
Let me know if it's ok. Thanks!
