### ISSUE TITLE
Show average star rating

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#5436]
<img width="1071" alt="screen shot 2018-06-27 at 11 01 58 am" src="https://user-images.githubusercontent.com/6797635/41991577-c3065992-79fa-11e8-9b81-ae1c702ef945.png">

Change the "Overall rating" copy on the detail page to "[number] star rating". Show to one decimal point ("4.3" for example).

**Comment by bobsilverberg** [comment]
@pwalm Your screenshot shows the text "4 star average", but your textual description says the text should be "[number] star rating". Which should it be?

**Comment by pwalm** [comment]
Sorry for being unclear: It should say "[x] star average"

And if there are no ratings it should say "Not rated yet"

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/44098965-37d27c6e-9fea-11e8-9463-4f588df61f3e.png)

![image](https://user-images.githubusercontent.com/31961530/44098981-3e5d28fe-9fea-11e8-9da2-4bec6cf98475.png)

![image](https://user-images.githubusercontent.com/31961530/44098992-435890d2-9fea-11e8-9384-d302de62d51d.png)

![image](https://user-images.githubusercontent.com/31961530/44099004-498c3a44-9fea-11e8-9535-91b76754a3c7.png)
