### ISSUE TITLE
Navigating to a non existent page in More add-on by author cards in the User profile page will lock the cards in a loading state

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5442]
STR:

1. Load AMO -dev
2. Open a user profile page that lists both add-ons and themes - see https://addons-dev.allizom.org/en-US/firefox/user/AlexandraMoga1/?page_e=7&page_t=6
3. Set the page query for the two cards to a non-existent page (i.e. 7 for add-ons and 6 for themes for this case)

Actual result:
The two cards are locked in a loading state when a non-existent page is requested

Expected result:
Display (maybe) a Page not found on the card that is causing the error to appear

Notes:
- reproduced on AMO -dev with FF60, WIn10x64

[1] Page when both cards are requesting an invalid page
![screen shot 2018-06-28 at 09 11 21-fullpage](https://user-images.githubusercontent.com/31961530/42016912-de21d7d6-7ab5-11e8-8acf-4e55b85c2356.png)

[2] Page when only on card is requesting an invalid page

![image](https://user-images.githubusercontent.com/31961530/42016920-e8f2cf4e-7ab5-11e8-8671-300a778f329c.png)

**Comment by muffinresearch** [comment]
@willdurand If either of these modules are out of range we should probably just simply make the whole page a 404. It would be unfortunate if being a 200 meant this got indexed. Even if we're not linking to it, we can probably assume that someone else will and page lengths could change over time.

I suppose an alternative might be to 301 to an highest in-range value for the module that 404s, but that might be overly complex.

**Comment by willdurand** [comment]
> @willdurand If either of these modules are out of range we should probably just simply make the whole page a 404.

Yes, that's what we do for the search results.
