### ISSUE TITLE
[Android] Grey background displayed when selecting "Featured add-ons only" filter

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5443]
Steps to reproduce:
1.On your Android device open Firefox and go to AMO 
2.Enter a search term and press Enter
3.Press filter results and check the "Featured add-ons only" filter

Expected results:
Checkbox is checked without any UI issue

Actual results:
A grey background is flickering for a second when the checkbox is checked

NOTES:
Reproducible on all servers
Tested with FF Release for Android on Samsung Galaxy S7 edge

Please see a video with this issue : 
![androidfilter](https://user-images.githubusercontent.com/1583842/42029971-ef897172-7ad9-11e8-94d8-5037b574a425.gif)

**Comment by muffinresearch** [comment]
I think this is part of the platform or browser so I don't think that's something we can change on AMO.

@vcarciu do you see this on other sites or apps?

**Comment by willdurand** [comment]
We discussed with @vcarciu on IRC and this is a wontfix as it is indeed platform specific and nothing we can "fix".
