### ISSUE TITLE
Only run prettier on changed files

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5448]
For contributors who are relying on the `yarn prettier` command, it will be a slow and annoying. We should give them something like `yarn prettier-dev` which will only run prettier on the changed files.

It looks like [Pretty-Quick](https://github.com/azz/pretty-quick#pretty-quick) will do this for us.

**Comment by SeanPrashad** [comment]
Would we want to implement the [pre-commit hook functionality](https://github.com/azz/pretty-quick#pre-commit-hook) of pretty-quick **and** add a `yarn prettier-dev` command or simply the latter?

The reason why I'm asking is that automating it via pre-commit hooks would automate prettier and provide a seamless experience. What do you think?

**Comment by willdurand** [comment]
No pre-commit.
