### ISSUE TITLE
User should land on AMO homepage when logging out from My Collections page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5451]
Follow up for https://github.com/mozilla/addons-frontend/issues/3142

STR:
1. Log in to AMO -dev
2. Go to My Collections page - https://addons-dev.allizom.org/en-US/firefox/collections/
3. Log out

Actual result:
The user lands on a mostly blank Log in page

Expected result:
The user should land on AMO homepage

Notes:
- reproduced on AMO -dev with FF60, Win10x64

![my coll log out](https://user-images.githubusercontent.com/31961530/42076276-27df6eca-7b7d-11e8-9c09-d98fed493ca7.gif)

**Comment by willdurand** [comment]
I don't think we want to fix this "right now", because this is something we do almost everywhere else.

**Comment by willdurand** [comment]
@jvillalobos what do you think about that? Or should I rather ping someone in UX?

**Comment by jvillalobos** [comment]
I think the behavior is right. It'd be a bit strange to be redirected to a different page after logging out, IMO. But it's also a good idea to check in with UX. There might be something that can be added to make the logged out state more useful.
/cc @pwalm @MeridelW

**Comment by pwalm** [comment]
Yeah, agree with @jvillalobos, the behaviour is right. But we could use some copy that says "Log in to create a collection" or something along those lines.

**Comment by bobsilverberg** [comment]
Currently the button says "Log in to view your collections" which seems reasonable to me. I'm going to close this based on the responses from @jvillalobos and @pwalm.
