### ISSUE TITLE
The distance between collection rows in My Collections page could be reduced

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5452]
Follow up for https://github.com/mozilla/addons-frontend/issues/3142

STR:
1. Log in to AMO -dev
2. Open My Collections page https://addons-dev.allizom.org/en-US/firefox/collections/
3. Observe the page layout 

Actual result:
There is too much white space between collection rows

Expected result:
White space between collection names should be reduced in order to make My Collections page look more compact

Notes:
- reproduced on AMO-dev with FF60, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/42077372-598c17a8-7b81-11e8-85a1-0bd679b72885.png)

**Comment by willdurand** [comment]
Yes, I think it would make sense to have less white space.

**Comment by lavish205** [comment]
I would like to work on this bug.

**Comment by bobsilverberg** [comment]
@lavish205 Thanks for the interest, but this one is already being worked on, as can be seen from the fact that it's assigned and it has a pull request attached. I really should have removed the "maybe good first bug" label when I assigned it. My apologies for that.

**Comment by ioanarusiczki** [comment]
The height of the area was reduced and it looks better to me.
Verified fixed on AMO dev with FF61(Win10&Android 8.0).
![collectionsdistance](https://user-images.githubusercontent.com/33448286/42508000-b83c325c-844f-11e8-9ac0-da4136c3cd4c.png)
