### ISSUE TITLE
Add user profile routes in -stage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5453]
See also: #4284

We plan to enable the user profile feature in -stage next push (2018.07.05), so we need to setup the nginx routes in -stage before the push. We need the following routes (same as -dev):

- [x] `/user/:username/`
- [x] `/users/edit`
- [x] `/user/:username/edit/`

**Comment by bqbn** [comment]
The 3 routes should now be routed to the mobile site on -stage.

**Comment by willdurand** [comment]
thanks!

**Comment by ioanarusiczki** [comment]
I verified with FF61(Win10 and Android 8.0) Edit profile and View Profile pages on AMO stage.
Filed https://github.com/mozilla/addons-frontend/issues/5495
