### ISSUE TITLE
Enable user profile in -stage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5454]
In order to enable the user profile feature in -stage, we need to:

- [x] setup the Nginx routes: #5453 
- [x] configure the frontend to enable this feature

**Comment by willdurand** [comment]
For QA: the user profile feature has been enabled and should be available on -stage.

**Comment by ioanarusiczki** [comment]
I verified user profiles on AMO stage with FF61(Win10).
One issue filed https://github.com/mozilla/addons-frontend/issues/5494
