### ISSUE TITLE
Theme artist or Add-on developer should be displayed on the user's info card only after the add-on or theme is approved 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5457]
STR:
1. Create a new account and sign in.
2. Submit an extension and approve it - notice that before approving it the Add-on developer is already displayed on the card but the card is public only after the first add-on or theme is approved.
3. Submit a lightweight theme for the new account then with an admin account reject it.
4. Go to View my profile page and sign out. 

Expected result:
Theme artist is not available on the info card because the card does not display a theme.

Actual result:
Theme artist is displayed on the card which is public since it contains a submitted add-on. 

Notes:
This issue is reproducible on AMO dev with FF60(Win10).

![userinfocard1](https://user-images.githubusercontent.com/33448286/42090283-88f699f0-7ba9-11e8-8946-01c7ac85b84a.png)

**Comment by willdurand** [comment]
That's a server issue I believe. We don't decide what we display.

**Comment by willdurand** [comment]
@ioanarusiczki can you move this issue to addons-server please?
