### ISSUE TITLE
Static themes are included in Add-ons developer instead of Theme artist on user's info card

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5458]
STR:
1. Load AMO dev and using a new account submit a static theme and approve it
2. Go to view profile and observe the category displayed at the top of the page

Expected result:
Theme artist.

Actual result:
Add-ons developer.

Notes:
This issue is reproducible with FF60(Win10). 
![theme not add-on](https://user-images.githubusercontent.com/33448286/42091187-f9177120-7bac-11e8-8f21-67581cf7b3e5.png)

**Comment by willdurand** [comment]
It's a server issue I believe.

**Comment by ioanarusiczki** [comment]
@willdurand Let me know if I must transfer it on the server repository together with https://github.com/mozilla/addons-frontend/issues/5457

**Comment by willdurand** [comment]
@ioanarusiczki yes, please.
