### ISSUE TITLE
https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews doesn't explain how to report add-ons that violate the policy

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/addons-frontend#5465]
Searching for "report firefox add-on abuse" doesn't seem to give any really useful results. https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews is the best result and it doesn't explain how to report add-ons that violate the policy.

**Comment by EnTeQuAk** [comment]
For add-ons hosted on AMO we have a direct link that gives you the ability to report an add-on. Not sure there's more we can do.


![screenshot-2018-7-2 private bookmarks add-ons for firefox](https://user-images.githubusercontent.com/139033/42151105-25595bbe-7ddc-11e8-940c-db0ab674d008.png)

**Comment by bobsilverberg** [comment]
This is a good point @EnTeQuAk, but would it also make sense to have it mentioned somewhere on MDN about how to go about reporting an add-on for abuse? Some users might not think to go to the AMO page for the add-on.

**Comment by caitmuenster** [comment]
Hmm -- we should probably have something on [SUMO](https://support.mozilla.org/en-US/products/firefox/manage-preferences-and-add-ons-firefox/install-and-manage-add-ons). I'm not sure how many users will end up on MDN. If they do go to MDN, we can point to SUMO. 

I'll take a look today to see if there's anything on SUMO and if there isn't, I'll add it to the backlog. 

Thanks!

**Comment by caitmuenster** [comment]
Oh, like in `about:addons`? Let me talk to @atsay  about this.

**Comment by atsay** [comment]
SUMO article would be good. Also a good idea to include something in the add-on manager. Tagging @brassy - maybe a Report abuse link next to "More":

![listing](https://i.imgur.com/6XFknV6.png)

Or on the detail page:
![detail](https://i.imgur.com/MXINLkE.png)

**Comment by jvillalobos** [comment]
We've talked about doing something like this before in `about:addons`. What Chrome does is give the user the option to report abuse after an add-on is disabled or uninstalled, instead of having a permanent link.

**Comment by muffinresearch** [comment]
@jvillalobos do you know if there's an existing Firefox bug for that? I'm thinking that there's probably nothing actionable here if we're planning to do something in the client instead.

**Comment by jvillalobos** [comment]
There are no bugs filed for Firefox that I know of, but I agree that this is not the place to track that. Neither creating a SUMO article for this. There's a documentation Trello, so I'll leave that up to @caitmuenster

**Comment by caitmuenster** [comment]
We should have a SUMO article up within a few weeks. 

We do have an open question about adding a 'report abuse' to `about:addons`, which I think would be good.
