### ISSUE TITLE
total av Safe Site for Firefox

### ISSUE THREAD

**Issue by kpfisher** [mozilla/addons-frontend#5466]
### Describe the problem and steps to reproduce it:

tried to get the total av safe site for firefox from the total av site.

### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/addon/total-av-safe-site/
https://my.totalav.com/safe-site

**Comment by EnTeQuAk** [comment]
Please notify the developer if you're running into problems installing their add-ons. This is outside of our control if they pulled their add-on from AMO.
