### ISSUE TITLE
When I click on a persona to use the error comes up

### ISSUE THREAD

**Issue by BabyChloe333** [mozilla/addons-frontend#5468]

**Comment by BabyChloe333** [comment]
It says server error

**Comment by EnTeQuAk** [comment]
Can you maybe give us an example of which persona you tried to install?

**Comment by BabyChloe333** [comment]
Hi Chris: 

I can apply the Personas from my icon when I click on one of the Favorites but when I go to click on any of the Personas on the site under Themes or my own Favs, I get this page vs the clicked persona: 

"Server Error 


Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it. Suggested Pages 


    * Browse all extensions 
    * Browse all themes 
    * Add-ons Home Page 


If you have additional information that would help us you can file an issue . Tell us what steps you took that lead to the error and we'll do our best to fix it." 




Thanks, 


Dianne

**Comment by kumar303** [comment]
Hi. Thanks for taking the time to file a bug report. The 'My Favorites' collection will be moved to the new site when we launch a redesign of collections, currently targeted for late July 2018. At that time, the install button should work as expected. 

I cannot reproduce the specific bug you mention here but you can try installing each theme from their detail pages instead for now. Sorry for the inconvenience. If you are really stuck and can't find any way to install your themes, let us know by giving us specific URLs to each theme.

**Comment by BabyChloe333** [comment]
Hello Kumar: 

When I click on the detail page for each Persona - I get that Error page. Hopefully your redesign will clear this up. 

Thanks, 
Dianne
