### ISSUE TITLE
Handle enabled/disabled add-ons

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#547]
Currently we treat disabled add-ons as installed and disabled themes as uninstalled. We should treat disabled as uninstalled for now and verify that add-ons work correctly when installing from disabled.

**Comment by mstriemer** [comment]
It appears as though installing a disabled add-on does not enable it. The enabled/disabled status seems to be set from the Extensions section of about:addons and installing an add-on seems to install it into the last user-defined status. So if you disable, then install it stays disabled. If you disable, then remove, then install it is also disabled. If it was enabled when it was removed installing it again will make it enabled.

This doesn't seem ideal, perhaps we should add some messaging to the button to notify the user that it is disabled and they need to manage it under Extensions until we can enable it.

@aswan can you think of a way to enable a disabled add-on?

@pwalm is there some messaging we should add to the button if the add-on is disabled?

**Comment by aswan** [comment]
In privileged browser code, there is a `userDisabled` attribute on an instance of Addon that can be toggled to enable the add-on, but we haven't exposed that to content.  We could expose a new method or attribute for this if that's desired.

**Comment by pwalm** [comment]
I'd rather not have to add any messaging. In the user's eyes off means off, on means on. When you say "disabled" do you mean "off"? or do you mean that we have disabled it due to signing/compat issues?

**Comment by aswan** [comment]
@pwalm, There are lots of ways an add-on can become disabled, all of which I think we need to take into account here.  As you mention, compatibility or signing issues is one case, but those are issues that we should be able to prevent by choosing the featured add-ons with care, and if one of those occurs, there's not much we can do other than display an error.
The other big case is that users can also choose to disable an add-on (the "Disable" button in the add-ons manager).  The idea is that the add-on stops running but it remains installed so you can re-enable it without having to download it again.  If a user happens to have one of the featured add-ons installed but in this user-disabled state, we don't currently have a way for the disco pane to enable it (I suppose technically the disco pane could uninstall and then re-install but lets not do that)

**Comment by mstriemer** [comment]
> I suppose technically the disco pane could uninstall and then re-install but lets not do that

I was thinking the same thing but I don't think that would actually work since Firefox seems to persist the setting across installs. But we also shouldn't do that. It does mean we have no hack that we could put in on our end so we'd need something in Firefox and I'm assuming it's quite late for uplifts.

**Comment by aswan** [comment]
We have a little less than 8 weeks until 48 goes to release so its not too late to ask but the closer we get to release the higher the bar gets for uplift.  I'm thinking we should do the firefox work anyway so we can use it at some point and if it doesn't make 48, we could at least display a warning with a link to about:addons where there should be more detail and the ability to enable if it was user-disabled.  Its not ideal but its probably not a very common scenario.

**Comment by muffinresearch** [comment]
@aswan do you have a bugzilla bug for adding the APIs to enabled/disable addons already or do you need one?

**Comment by aswan** [comment]
there isn't one yet

**Comment by muffinresearch** [comment]
@aswan ok I've filed https://bugzilla.mozilla.org/show_bug.cgi?id=1279034

**Comment by muffinresearch** [comment]
Here's a few things we can do that aren't blocked:

* Have the UI respond to onDisabled / onEnabled events - we don't currently.
* Initialise the UI based on isEnabled / isActive states when checking current state. 

We could use the disabled button state temporarily to deal with the lack of the ability to reverse the disabled state.

**Comment by muffinresearch** [comment]
Fix for this is landed on -dev, but will only work for 48 beta 5 upwards (so it will work on nightly until 48b5 is out).

QA notes:

* Install an add-on from the diso pane.
* Go to about:addons#extensions (the extensions list) and disable the add-on.
* Go back to about:addons and click the install button and you should see it change to a green with a tick.
* Note on about:addons#extensions the add-on is now shown as enabled. (The button/link there should change from `enable` -> `disable`).

If it doesn't work check you're running at least 48b5 +
