### ISSUE TITLE
Provide a hint about the image upload types allowed in the user profile

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5471]
I uploaded a gif which was displayed in the page. Then when I hit save I saw an error message: "Images must be either PNG or JPG."

Gif displayed:

<img width="348" alt="user_profile_for_muffinresearch__script_alert_0___script__ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/42161318-622d5372-7df2-11e8-8bc5-16980986a9f2.png">

Error message:

<img width="736" alt="user_profile_for_muffinresearch__script_alert_0___script__ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/42161331-75d953f8-7df2-11e8-93e0-4008f4e83e16.png">

It presumably should also be possible to limit the file uploads to the relevant file types using the accept attribute to limit selecting  + uploading incorrect file types.

**Comment by madalincm** [comment]
Verified in FF61(Win7) in amo-stage.
The selection is now limited to only accepted files 
Postfix screencast:
![supportedfiles](https://user-images.githubusercontent.com/15685441/42623758-58449ca8-85cc-11e8-9930-99cf678604f7.png)

Marking bug as verified fixed.
