### ISSUE TITLE
Profile page biography field creates invalid markup

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5473]
STR:

Edit user profile and add the following:

```html
<ul>
<li>ul li</li>
</ul>
```

The output on the page after saving is:

```html
<ul>
<br>
<li>ul li</li>
<br>
</ul>
```

There shouldn't be brs created inside the `ul`.

**Comment by willdurand** [comment]
I think the existing helper function to format/sanitize HTML and create `nl2br` is a bit naive, because I also noticed this for double new lines. I would have expected dom-purify to "fix" this, but I guess it is not its job.

**Comment by madalincm** [comment]
Verified in FF61(Win7) in amo-dev
Issue is no longer reproducing:
![userbiography](https://user-images.githubusercontent.com/15685441/42624072-258875d6-85cd-11e8-8231-0dbe029459d0.png)
Marking bug as verified fixed.
