### ISSUE TITLE
Empty reviews are not visible on the new front end - user profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5474]
STR:
1. Load AMO dev and create a new account then make a couple of empty reviews for some add-ons
2. Click the View my profile page and observe the page

Expected result:
Reviews are displayed.

Actual result:
Review section is empty. Only the old page displays them.

Notes:
This issue is reproducible on AMO dev with FF60(Win10 and Android 8.0). 

![empty reviews not displayed](https://user-images.githubusercontent.com/33448286/42164066-7b4f35e4-7e0d-11e8-8355-bfef513afcb6.gif)

**Comment by willdurand** [comment]
Indeed, see https://github.com/mozilla/addons-frontend/issues/4282#issuecomment-400851802, I forgot to open an issue for that.

I thought maybe we did not want the reviews without a body but actually we want them.

The reviews saga should be edited to remove the `filter`.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10 &Android 8.0)
![empty reviews](https://user-images.githubusercontent.com/33448286/42500641-80a6ea72-843a-11e8-8953-b2bc5ab66eda.png)
