### ISSUE TITLE
Featured Extensions `src` not being tracked in all cases

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#5475]
Re-filed from https://github.com/mozilla/addons-server/issues/8263. 

**Original description by @devaneymoz:**

Go to the AMO homepage. Content programming changes frequently, but typically we have a "Featured extensions" shelf somewhere on the page. 

If you find it, click one of the featured extensions in the module display. For example, I see Enhancer for YouTube, I click it, I go to its detail page, and the URL looks like so:

https://addons.mozilla.org/firefox/addon/enhancer-for-youtube/?src=featured

Now, go back to the homepage. This time, instead of clicking on an individual featured extension in the shelf, click the "See more featured extensions" link on the far right of the module. Find Enhancer for YouTube and click thru to its detail page. The URL will look like so:

https://addons.mozilla.org/firefox/addon/enhancer-for-youtube/?src=search

It appears we're tracking the discovery flow differently (featured vs. search) when in truth they both should be the same -- src=featured

It will be difficult to measure the effectiveness of AMO's primary "Featured Extensions" collection if portions of its effect are measured as "search" results.

**Comment by diox** [comment]
**Original comment by @jvillalobos:**

When you click on "See more featured extensions", you land on a search page, which is why the `src` changes to `search`.

Would it make sense to use the `featured` value whenever the search page has the "featured only" checkbox selected?

While testing this, I also noticed that if you go directly to the featured add-ons collection and click on an entry, the `src` is `collection`, so we might want to special-case the `src` from that collection as well.

**Comment by diox** [comment]
Original reply by @devaneymoz:

I think it does make sense to use the "featured" value whenever the search page has the "featured only" checkbox selected, since that's effectively taking the same action as navigating to the featured collection.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10)
 The same URL is now available in both places (when clicked the extension is clicked from AMO homepage and then from See more... link) 
https://addons-dev.allizom.org/en-US/firefox/addon/hyfy-screen-recorder/?src=featured
Same behaviour for the themes from Featured Themes shelf.

![same url](https://user-images.githubusercontent.com/33448286/42385034-596016c6-8144-11e8-951d-2a6f119ede29.gif)
