### ISSUE TITLE
Use `src=collection` when clicking on collection shelf on homepage

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#5476]
Re-filed from https://github.com/mozilla/addons-server/issues/8264 (see also #5475)

**Original description by @devaneymoz:**

Go to the AMO homepage. Content programming frequently changes, but often we'll use a collection to feed into a homepage shelf. 

Currently we have a "Privacy tools" collection on the homepage. If you click one of the individual extensions directly from the shelf—for instance Ghostery—you click thru to its detail page and the URL looks like so:

https://addons.mozilla.org/firefox/addon/ghostery/

Now, go back the homepage. And click "See more privacy tools" link at the far right of the module. Then find Ghostery and click. Its detail page will look like so:

https://addons.mozilla.org/firefox/addon/ghostery/?src=collection

~~The source should be the same in both cases (src=collection), regardless of whether it's clicked directly from the homepage shelf, or from within the full collection.~~

The source should be `homepage-collection-featured` per https://github.com/mozilla/addons-frontend/issues/5476#issuecomment-401807353

**Comment by diox** [comment]
**Original comment by @jvillalobos :**

Should the `src` for collections in the homepage be the same as for any other random collections on the site? Would it be more useful to have a `homepage` or `homepage-collection` value for `src` so they can be differentiated?

**Comment by diox** [comment]
**Original reply by @devaneymoz :**

It would definitely be more useful if we can get more granular with the 'src' from homepage collections. 

I think the ideal case would be to know the specific collection it originated from, as well. In other words, we often have the same extension promoted in multiple concurrent homepage collections (e.g. uBlock Origin is in the "Featured" collection, as well as "Ad blockers" collection; understanding which performs better could help to optimize future programming decisions. So maybe it would be something like... src=homepage-collection-featured  ....  src=homepage-collection-ad-blockers

**Comment by kumar303** [comment]
> So maybe it would be something like... src=homepage-collection-featured .... src=homepage-collection-ad-blockers

Adding `src=homepage-collection-featured` is a bit easier to maintain since we won't have to keep it in sync with every collection. I'll add that. If you want more specific sources, just let me know.

**Comment by ioanarusiczki** [comment]
@diox 
Verified this issue on AMO dev with FF61 (Win10)
1. I checked the URLs for all the actual available shelves on AMO homepage and **homepage-collection-featured** is available except for "Featured extensions" and "Featured Themes" shelves where the URL looks like https://addons-dev.allizom.org/en-US/firefox/addon/st-patrick-cupcakes/?src=featured 

![clicked from amo](https://user-images.githubusercontent.com/33448286/42380143-8a82cb4a-8135-11e8-9cd5-089201ceb206.gif)

2. URLs for the detail pages clicked from "See more.." link contain only src=collection

Please let me know if it's ok.

**Comment by kumar303** [comment]
> URLs for the detail pages clicked from "See more.." link contain only src=collection

Whoops, they should be consistent. I filed this follow-up issue to fix it: https://github.com/mozilla/addons-frontend/issues/5514 Thanks!

**Comment by ioanarusiczki** [comment]
Then this is verified fixed on AMO dev with FF61(Win10)
The  "Featured extensions" and "Featured Themes" are a separate issue  "Featured extensions" and "Featured Themes" which answered to my question above.
