### ISSUE TITLE
The association between theme previews and their related button is not obvious

### ISSUE THREAD

**Issue by msujaws** [mozilla/addons-frontend#548]
See the following screenshot.

The themes have a preview, and a related description. But the description is placed just as far away from the preview as other items such as add-ons. This is confusing because the toggle for the add-on looks like it could also be the toggle for the theme, and vice versa.

![2016-06-07_1225](https://cloud.githubusercontent.com/assets/272055/15866002/ff159bcc-2caa-11e6-9254-cb9076c8e0b9.png)

**Comment by muffinresearch** [comment]
This is made partly worse because we had to drop the background colour which makes for a minimal contrast between the addons and themes. Whereas with a darker background each item was more distinct.

@pwalm - could we add a border/box-shadow (even a subtle one)  on the addons/theme blocks to help make a clearer visual separation between the addons and theme blocks?

**Comment by pwalm** [comment]
I like the idea of the box-shadow. I have that mocked up for future pref pane design changes, so it's ready to go:

box-shadow: 0px 1px 2px 0px rgba(0,0,0,0.50);

**Comment by muffinresearch** [comment]
@pwalm OK trying that out 0.5 opacity is pretty strong. 

Here's some screen shots showing the specced style through to lighter versions, what do you think stick with 0.5 or go lighter?

Click the images to see them larger (click again to get the proper resolution).


## rgba(0,0,0,0.5);
<img alt="discover_add-ons_and_the_association_between_theme_previews_and_their_related_button_is_not_obvious_ _issue__548_ _mozilla_addons-frontend" src="https://cloud.githubusercontent.com/assets/1514/15890792/3b7838e0-2d69-11e6-910f-519b7ebe9644.png">


## rgba(0,0,0,0.4);

<img alt="discover_add-ons_and_charles_3_11_2_-_session_1__" src="https://cloud.githubusercontent.com/assets/1514/15890805/49f7199a-2d69-11e6-8bf3-67a93af41fa6.png">

## rgba(0,0,0,0.3);

<img alt="discover_add-ons_and_charles_3_11_2_-_session_1__" src="https://cloud.githubusercontent.com/assets/1514/15890812/577ff668-2d69-11e6-8b9c-209d0728895a.png">


## rgba(0,0,0,0.2);

<img alt="discover_add-ons_and_charles_3_11_2_-_session_1__" src="https://cloud.githubusercontent.com/assets/1514/15890826/62bbe726-2d69-11e6-8f73-902a12a4f277.png">

## rgba(0,0,0,0.1);

<img alt="discover_add-ons_and_charles_3_11_2_-_session_1__" src="https://cloud.githubusercontent.com/assets/1514/15890836/6f365c70-2d69-11e6-8fcd-27eb69dc6d44.png">

**Comment by designakt** [comment]
Wow, great to have that comparison. Interesting how little it takes for me to see the separation.
I very much like 0.2 or 0.3

**Comment by muffinresearch** [comment]
I landed 0.2 so you can see it for real when it's on -dev. Feel free to re-open if it needs to be tweaked further.

**Comment by pwalm** [comment]
@muffinresearch Thanks for that comparison! Weird that what I sent you looks so dramatic when applied, it looks super faint in Sketch. Let's go with 0.1. It just needs to be nice and subtle.

**Comment by muffinresearch** [comment]
@pwalm thanks - I've updated that in https://github.com/mozilla/addons-frontend/commit/085f347a48970d0060acbbb0daacf06219aec9db should be on -dev shortly.

**Comment by andymckay** [comment]
It could be my crappy monitor, but I can barely see that at all on -dev. In fact it is my crappy dell monitor, it looks better on retina. I think it needs more contrast (personally).
