### ISSUE TITLE
Navigate to Manage My Submissions from AMO header

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-frontend#5487]
@MeridelW and I did a walkthrough of how developers manage their extensions, and it looks like developers currently can't navigate to 'manage my add-ons' from the AMO header: 

![screen shot 2018-07-03 at 1 49 16 pm](https://user-images.githubusercontent.com/23342476/42244120-8aa937c2-7ec8-11e8-91ff-de2c06820278.png)

Can we add it to the drop down under 'Tools'? Otherwise, developers have to scroll down to the footer to access the Developer Hub, or they have to start a "submit new extension/theme" and then navigate to "manage my add-ons".

**Comment by caitmuenster** [comment]
Oh - sorry! It just occurred to me that we want to drive people to the Developer Hub, which is right next to the profile name. 

I was really confused by this, but maybe that was just me.

**Comment by muffinresearch** [comment]
I think it would make sense to add a link under tools too - good idea.

**Comment by caitmuenster** [comment]
Looks like there's already a PR in for this. Thanks @championshuttler!

**Comment by willdurand** [comment]
Good job @championshuttler!

**Comment by ioanarusiczki** [comment]
@caitmuenster Maybe Developer Hub on the AMO homepage should have it's own dropdown menu? Tools could be moved there. 

I verified this issue on AMO -dev with FF61(Win10&Android 8.0) 
![manage my submissions](https://user-images.githubusercontent.com/33448286/42818310-32816ae4-89d9-11e8-8175-be76069da778.gif)

**Comment by caitmuenster** [comment]
Thanks, @ioanarusiczki! I'm definitely not opposed to the Dev Hub menu, but it's @jvillalobos and @pwalm's call.

**Comment by jvillalobos** [comment]
I prefer to keep it simple. The Dev Hub should be the place to look for all of these tools. The menu items under the account are just shortcuts, and we know that those will always be available when you're logged in.
