### ISSUE TITLE
Download page is down for stylish

### ISSUE THREAD

**Issue by jdomingi** [mozilla/addons-frontend#5491]

**Comment by cadeyrn** [comment]
https://blocked.cdn.mozilla.net/c635229f-7aa0-44c5-914f-80c590949071.html

**Comment by muffinresearch** [comment]
Stylish has been blocklisted - see the links posted above for the context.

**Comment by muffinresearch** [comment]
Here's a possible alternative to consider https://addons.mozilla.org/en-US/firefox/addon/styl-us/

**Comment by grahamperrin** [comment]
#5504
