### ISSUE TITLE
Dokieli Firefox Add-on not found

### ISSUE THREAD

**Issue by IanOW** [mozilla/addons-frontend#5492]
### Describe the problem and steps to reproduce it:
Tried to add Firefox Add-on via link from https://github.com/linkeddata/dokieli/blob/master/README.md using link https://addons.mozilla.org/en-US/firefox/addon/dokieli/ 

### What happened?
Message "Sorry, but we can't find anything at the address you entered."
### What did you expect to happen?
Install the Add-on
### Anything else we should know?

https://github.com/linkeddata/dokieli/blob/master/README.md

**Comment by muffinresearch** [comment]
See https://github.com/linkeddata/dokieli/issues/231 for more context.
