### ISSUE TITLE
Link from Feedly Add on does not work

### ISSUE THREAD

**Issue by itstheglue** [mozilla/addons-frontend#5493]
### Describe the problem and steps to reproduce it:

Hi, 

I want to add a Feedly Add on- but the URL does not work - neither through the feedly site directly nor through the google search results: 

https://addons.mozilla.org/en-US/firefox/addon/feedly-save-to-board/

https://addons.mozilla.org/en-US/firefox/addon/feedly-save-to-board/

I expected to access the add-on site

Instead, a page not found message showed up. 

Thank you for looking into this!

Best, 

Matthias

**Comment by muffinresearch** [comment]
Unfortunately this add-on is not currently available. Please contact the developer for an update.
