### ISSUE TITLE
Display name will appear cut when is longer than 25 chars on the user profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5494]
STR:
1. Load AMO stage and go to Edit profile page
2. Edit your display name , make sure it contains more than 25 chars
3. Update profile and observe it on the view profile page

Expected result:
Name is displayed without layout issues.

Actual result:
Name appears cut.

Notes:
This issue is reproducible when editing the username too in case the user won't edit the displayname, also when edited with a long unbroken string it will appear cut in the Extension by section.
This issue is reproducible on AMO dev and AMO stage with FF61(Win10). 

![unbrokenstringdisplay](https://user-images.githubusercontent.com/33448286/42269706-8b510866-7f87-11e8-85f8-869f0c87554e.png)

**Comment by willdurand** [comment]
This has to be fixed before the next tag 😞

**Comment by bobsilverberg** [comment]
I can take it if you like, @willdurand

**Comment by willdurand** [comment]
> I can take it if you like, @willdurand

If you want sure, otherwise I come back on Monday morning :)

**Comment by bobsilverberg** [comment]
> If you want sure, otherwise I come back on Monday morning :)

I was just trying to turn your frown upside-down. I interpreted it as a concern about landing this before the next tag. I probably do have time for it, so I'll take it.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10). 
A long string is cut now 
![a long string](https://user-images.githubusercontent.com/33448286/42452145-ec330e82-8391-11e8-93dd-b6598b658b19.png)

@bobsilverberg Maybe the height of the text box should be increased a bit so the "p", "g" or "y" would not look cut ? - check the screenshot 
Also are the new user profile pages going to land on prod at the end of this week ?

![lenght](https://user-images.githubusercontent.com/33448286/42452358-7274b324-8392-11e8-9035-2fb9725ca1fb.png)
