### ISSUE TITLE
“View My Collections” returns “Page not found” on amo-stage

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#5496]
### Describe the problem and steps to reproduce it:
1.Create some collections
2.Hover over the username.
3.Click on "View My Collections".
### What happened?
“Page not found” is displayed in the web page.
### What did you expect to happen?
To see the collections I have created.
### Anything else we should know?
Reproduced on FF61.0, AMO-stage under Win 7 64-bit and Android 8.0.0

On AMO-prod there is a different behavior. The user is redirected to "Collections" page and not at "Collections by [User]"

I attached videos for both cases.

**Stage**
![collectionstage](https://user-images.githubusercontent.com/15885467/42281797-52222f86-7fad-11e8-882b-5d9257cc7119.gif)

**Prod**
![collectionsprod](https://user-images.githubusercontent.com/15885467/42281819-5e38f930-7fad-11e8-80af-d5fcf09789b5.gif)

**Comment by bobsilverberg** [comment]
This is happening because the nginx rules for stage have been updated, but the feature was not turned on. I planned to turn it on but then we decided not to do it at the last minute so we wouldn't be turning on both User Profile and Collections on stage at the same time.

There will be certain collections features that do not work on stage at this time because of this.

**Comment by bobsilverberg** [comment]
Our plan is to turn on the new Collections features on stage with the next push, so perhaps we can keep this open until then and check it again after the next tag.

**Comment by bobsilverberg** [comment]
There shouldn’t be an issue on prod, only on stage. Is there an issue on prod too? Also is this blocking any QA on stage? If so we can fix it with a new tag..

**Comment by vcarciu** [comment]
@bobsilverberg according to bug description, "The user is redirected to "Collections" page and not at "Collections by [User]" " on prod.

**Comment by bobsilverberg** [comment]
@vcarciu Ah, thanks, I missed the prod issue reported in the bug above. That is a separate issue which should be fixed immediately. Can you file a new bug for that and mark it a P1?

**Comment by cosminbadescuSV** [comment]
@bobsilverberg I have filed the bug for AMO-prod  https://github.com/mozilla/addons-frontend/issues/5506

Thanks for the help!

**Comment by bobsilverberg** [comment]
No problem, thanks for opening the bug!

**Comment by bobsilverberg** [comment]
This is now fixed on stage.

**Comment by cosminbadescuSV** [comment]
This issue is verified as fixed on FF61.0.1, AMO-stage under Win 7 64-bit and Android 8.0.0.

![bug5496](https://user-images.githubusercontent.com/15885467/42624164-6c5f380a-85cd-11e8-9a63-f1ee88df46b2.png)
