### ISSUE TITLE
Delete accounts forms cannot be dismissed when pressing outside of the pop up screen.

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5497]
Steps to reproduce:
1.Go to AMO-dev and try to delete an account 
2.While deletion account screen is displayed press somewhere outside of it

Expected results:
Form is closed

Actual results:
Form can be closed only from Cancel button

Please see a video for this issue : 
![deletedismiss](https://user-images.githubusercontent.com/1583842/42284484-4f2e9f6e-7fb5-11e8-8d2a-5100b5f4465e.gif)

**Comment by willdurand** [comment]
I changed the component label because I observe a similar issue with the rating modal (not always, though)
