### ISSUE TITLE
Unable to Downgrade Stylish due to Extension Removed from Front End

### ISSUE THREAD

**Issue by redyoshi49q** [mozilla/addons-frontend#5504]
The URL for the Stylish extension ( https://addons.mozilla.org/en-US/firefox/addon/stylish/ ) currently returns a "Page not found" response.  I imagine that this was done in light of the discovery of malware in the last year or so of Stylish's releases (see https://robertheaton.com/2018/07/02/stylish-browser-extension-steals-your-internet-history/ ).

While I can appreciate the proactive measure to protect the privacy and security of Firefox users, the complete removal of the page for the Stylish extension prevents someone from downgrading their Stylish install by downloading a downgraded .xpi of Stylish (from before the extension was compromised).  While the Stylus extension ( https://addons.mozilla.org/en-US/firefox/addon/styl-us/ ) is a suitable alternative for Firefox users, it isn't necessarily suitable for users of legacy Firefox, Firefox ESR, and forks of Firefox such as Pale Moon due to the Stylus extension's use of WebExtensions (which Pale Moon and older Firefox versions do not support).

In order to allow such users to more easily downgrade Stylish to a more secure version, it would be more suitable to keep the Stylish extension page up, but remove the insecure releases of that extension from 2017 and later.

**Comment by grahamperrin** [comment]
https://addons.mozilla.org/firefox/downloads/file/756207/type:attachment/stylish-2.1.1-an+fx+sm+tb.xpi?src=version-history not found. 

I'm aware of a respectable file sharing area (not mine) that is currently without 2.1.1, but where 2.1.1 might appear. It's publicly available, but I'll respect the block-list by not disclosing. 

----

End users can gain support in the Stylish support area, for example: 

- [no longer available on AMO - forum.userstyles.org](https://forum.userstyles.org/discussion/67684/no-longer-available-on-amo) (2018-07-03, captured at <https://web.archive.org/web/*/https://forum.userstyles.org/discussion/67684/no-longer-available-on-amo>)

– there are various duplicates of that topic so users should (please) be prepared to browse until what's required, from the developers of Stylish, is provided by the developers (or a fellow end user).

**Comment by grahamperrin** [comment]
@redyoshi49q NB non-blocked 2.1.1 is legacy – not usable with Mozilla Firefox ESR 60, and so on. 

AMO will cease to serve all such extensions. I should not expect short-term reinstatement of anything relating to 2.1.1.

**Comment by jvillalobos** [comment]
The listing will be back up when and if the add-on aligns with our policies again.
