### ISSUE TITLE
“View My Collections” does not redirect the user correctly on AMO-prod

### ISSUE THREAD

**Issue by cosminbadescuSV** [mozilla/addons-frontend#5506]
### Describe the problem and steps to reproduce it:

1.Create some collections
2.Hover over the username.
3.Click on "View My Collections".

### What happened?
The user is redirected to "Collections" page and not "Collections by [User]".
### What did you expect to happen?
The user to be redirected to "Collections by [User]".
### Anything else we should know?

Reproduced on FF61.0, AMO-prod under Win 7 64-bit and Android 8.0.0
![amo-prod](https://user-images.githubusercontent.com/15885467/42322883-c4816420-8066-11e8-8153-5bde3eba64c3.gif)

**Comment by vcarciu** [comment]
Verified as fixed in AMO Stage. User's collections are now displayed.
