### ISSUE TITLE
Top rated add-ons should only include add-ons for the current language

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/addons-frontend#5512]
https://addons.mozilla.org/en-US/firefox/search/?sort=rating&type=extension

Has a bunch of add-ons that are not English:

The top one is:
https://addons.mozilla.org/en-US/firefox/addon/biglion-cashback/?src=search

There's also:
https://addons.mozilla.org/en-US/firefox/addon/pakkujs/?src=search
https://addons.mozilla.org/en-US/firefox/addon/ypsuperkey/?src=search
https://addons.mozilla.org/en-US/firefox/addon/yandex-music-fisher/?src=search
https://addons.mozilla.org/en-US/firefox/addon/%D0%BA%D1%8D%D1%88%D1%84%D0%BE%D0%B1%D1%80%D0%B5%D0%BD%D0%B4%D1%81-%D0%BA%D1%8D%D1%88%D0%B1%D1%8D%D0%BA-%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81-1/?src=search

**Comment by jvillalobos** [comment]
We don't do language filtering for a few reasons:

1) Listing localization and add-on localization are independent.
2) Users may still be interested in add-on that are in a different language they are browsing on.
3) External links to AMO may contain the language code in them, forcing the user to the site in a particular language.
