### ISSUE TITLE
Improve the experience of rating and writing a review

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5519]
This is a placeholder issue for UX changes to improve the experience of rating an add-on, writing a review, and seeking support.

UX specs are in progress. Check the [PRD](https://docs.google.com/document/d/1oUz9Ng9v159IPdW4UqHhbNspWa9m5SaicAAX5jU7OjA/edit#) for details. Ideas:

- When you select a star, make it obvious that the rating has been saved (https://github.com/mozilla/addons-frontend/issues/5941)
- Show a generic button for reporting any kind of issue with an add-on, not just abuse. This will open a new flow for things like seeking support from the developer or reporting a bug. (https://github.com/mozilla/addons-frontend/issues/6199)
- Write a review inside of a text-box, not in an overlay (https://github.com/mozilla/addons-frontend/issues/5942, https://github.com/mozilla/addons-frontend/issues/5944)
- Make it obvious how to edit your written review (https://github.com/mozilla/addons-frontend/issues/5943)

**Comment by muffinresearch** [comment]
@kumar303 do you need a tracker issue for this? Now that we have projects we're typically using them to replace tracker issues.

**Comment by kumar303** [comment]
@muffinresearch I guess I meant a "tracker" (in quotes). We don't have anything filed currently so I wanted to put something in the project. I know this will be big but once we have UX specs we can split this apart and file separate issues.

**Comment by pwalm** [comment]
OK, revised the flow:
<img width="1729" alt="screen shot 2018-07-23 at 3 50 20 pm" src="https://user-images.githubusercontent.com/6797635/43107085-47443c02-8e90-11e8-8648-494e8d4c379b.png">

**Comment by kumar303** [comment]
@pwalm this looks great, thanks! Some feedback...

> Roll over stars to select rating

Could we say *select a star* or something to indicate that they need to click/tap on a star? Or would that be obvious?

In the read-only view of the written review, there is a pipe character separating the posted date and *Edit review*. We don't use pipes elsewhere and this strays from the current read-only view of written reviews. Could we make them consistent?

**Comment by kumar303** [comment]
@jvillalobos :

What should we do for the *Contact the developer for support* button when the developer has not specified a support URL? Just hide the button? It would be helpful if we could email the developer the written message but I know that's a big feature.

For example, [this add-on](https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/?src=homepage-collection-featured) has a support URL but [this one](https://addons.mozilla.org/en-US/firefox/addon/lizardextension/?src=search) does not.

**Comment by kumar303** [comment]
I'm a little concerned that the *Report abuse* and *Contact the developer for support* buttons only appear after selecting a star rating. Can we always display those buttons? Otherwise, we may end up with one star ratings for either of those cases.

**Comment by bobsilverberg** [comment]
@kumar303 This seems like a pretty big feature. Do you think we should put this behind a flag so we can develop it incrementally?

**Comment by MeridelW** [comment]
@pwalm Here are my copy thoughts:

1. "how are you enjoying" feels a bit leading. And the answer, "Very good," isn't grammatically correct: the answer should instead be "Very well," which doesn't work well (ahem, heh) in this context. How about changing the heading to "Rate this extension" and then kill the line "How are you enjoying..."? Is it important to name the extension? I wouldn't think so since they are on the listing page already.
2. Are we adding tips for leaving a review? I don't see that copy in mock
3. How does the user "save" the rating? This isn't clear to me from mock but I am sure y'all have something worked out. 
4. What are the labels for each star?

**Comment by MeridelW** [comment]
Update from me: I am working on the ratings label. Will report back tomorrow.

**Comment by jvillalobos** [comment]
> What should we do for the Contact the developer for support button when the developer has not specified a support URL?

Listings can have a support URL or a support email address. It's probably best to favor the URL. If there's no URL and there's an email address, I think just using a `mailto` link like on the listing should be good. If neither are set, hide the button.

> I'm a little concerned that the Report abuse and Contact the developer for support buttons only appear after selecting a star rating. Can we always display those buttons?

Yeah, I think it makes sense to show the buttons from the start, since one of the goals is to send users to the right place when they're not aware of the other options available.

**Comment by jvillalobos** [comment]
> Are we adding tips for leaving a review? I don't see that copy in mock

The current copy links to the [review guidelines page](https://addons.mozilla.org/review_guide), FWIW.

**Comment by MeridelW** [comment]
Thanks, @jvillalobos. It would probably be a good idea to include some tips in the actual review field, too as many users, I presume, would not bother to follow a link in the midst of writing a quick review. @pwalm, are tips within scope?

@pwalm Per our discussion with the localizing team, we should skip descriptors for the ratings system. Let's go with five whole stars, not half stars, and leave it at that for more global accessibility. 

Thank you!

**Comment by kumar303** [comment]
All bullet points now have their own issues so we can close this.
