### ISSUE TITLE
AMO semantic search "help" can be downright user-hostile.

### ISSUE THREAD

**Issue by jonqrandom** [mozilla/addons-frontend#5528]
### Describe the problem and steps to reproduce it:
search for "markdown"; `https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=markdown`

### What happened?
the first result, and most of the results included the term "download" but not the term "markdown". from [page 4](https://addons.mozilla.org/en-US/firefox/search/?page=4&platform=windows&q=markdown) onwards, there are occasional entire pages where the results don't contain the term "markdown" at all.

### What did you expect to happen?
most (all?) of the results to contain the term "markdown". 

i appreciate that natural language is hard to work with, but the real issue here is that there's no obvious way to turn semantic help __off__; no `please stop "helping" me` checkbox i can tick, no response to using quotes;
`https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=%22markdown%22`,
other common syntax;
`https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=%2Bmarkdown+-download`
`https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=markdown+NOT+download`
or even this monstrosity;
`https://addons.mozilla.org/en-US/firefox/search/?platform=windows&q=%2B%28%22markdown%22%29+-%28%22download%22%29`

whatever i do, AMO insists that i _really_ ought to look at all these results for "download". 
please provide a user-facing way to let AMO know that the search term we actually enter is the _only_ term we want results for?

**Comment by EnTeQuAk** [comment]
This indeed seems to have been improved considerably by mozilla/addons-server#8868

![screenshot from 2018-08-17 07-49-48](https://user-images.githubusercontent.com/139033/44249856-246bc400-a1f2-11e8-81ca-e69bc409ce2e.png)

I'm closing this for now but please feel very free to open new issues about search related issues if you see any.
