### ISSUE TITLE
Install switch looking a bit wonky

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#553]
@shorlander was looking at the disco pane today and noticed that the white circle in the switch was looking a bit different based on state. I analyzed some screenshots and sure enough, he's right!

<img width="475" alt="screen shot 2016-06-07 at 5 58 02 pm" src="https://cloud.githubusercontent.com/assets/6797635/15879505/a265600e-2cd9-11e6-950d-b48cadeda11e.png">

The off state is bigger than the on, which looks clipped or masked behind something. The circle should be 26x26px.

**Comment by muffinresearch** [comment]
@pwalm - thanks for the heads (thank @shorlander for spotting it!). All these fixes are on -dev. Let us know if there's any other tweaks needed or spec stuff that we've overlooked.

**Comment by pwalm** [comment]
Awesome! Looks great. But there is a new issue. When installing a theme, the switch does this:
![screen shot 2016-06-08 at 10 27 31 am](https://cloud.githubusercontent.com/assets/6797635/15903879/c1e5256a-2d63-11e6-8213-4f4c13f88361.png)
Seems to happen when the "install" banner appears at the top of the page.

**Comment by muffinresearch** [comment]
@pwalm - Could you file a new bug for that please?

I've seen this (are you looking on an external monitor - when I saw it, it was only on an external monitor)

It might be improved by the PR I've got up to improve/re-instate the animations. Worse case we might have to poke the button to force a repaint.

**Comment by muffinresearch** [comment]
Ah I think my PR fixes it.

**Comment by muffinresearch** [comment]
I'll let you know when that's landed and you can try it out.

**Comment by pwalm** [comment]
Looks good on my Macbook, haven't looked at it again on my big monitor at work. Will file another issue.
