### ISSUE TITLE
Automatically reload dev server code on every change

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5530]
We use a hot reloader but it only applies to client side code. The server code does not hot reload. It should!

Here's why:
- First, you really need to develop with SSR enabled since it catches so many bugs
- React [reconciliation](https://reactjs.org/docs/reconciliation.html) has a lot of optimizations now which means our dev environment goes quickly out of sync until you manually restart the server
- Restarting the server is very slow
- Switching code branches or doing a yarn update is especially annoying

This issue will probably be harder than https://github.com/mozilla/addons-frontend/issues/2402 but maybe not.

**Comment by willdurand** [comment]
I see that most people use `nodemon` (or similar) to watch and reload the node server when files change. It is not what we want because it takes a lot of time to restart our web server...
