### ISSUE TITLE
No Stylish addon for Mozilla Firefox 61.0 Snap

### ISSUE THREAD

**Issue by Pipivi** [mozilla/addons-frontend#5534]
Trying to install **Stylish** addon on Mozilla Firefox 61.0 Snap for Ubuntu, no search results on addons.mozilla.org
Following the link from duckduckgo search results - https://addons.mozilla.org/en-US/firefox/addon/stylish/ - no addon there. Version 3.13 dated July 9, 2018 is available at https://addons.mozilla.org/en-US/firefox/addon/stylish/versions/ but browser does not allow to install it.

**Comment by EnTeQuAk** [comment]
Stylish has been blocked for security and privacy reasons. See https://blocked.cdn.mozilla.net/i1900.html for more details.

https://addons.mozilla.org/en-US/firefox/addon/styl-us/ should be an adequate alternative.
