### ISSUE TITLE
generare hash

### ISSUE THREAD

**Issue by jobsergio** [mozilla/addons-frontend#5537]

**Comment by jobsergio** [comment]
non so come fare per generare la chiave hash privata ho fatto in mille modi ma non sono riuscito

**Comment by willdurand** [comment]
> non so come fare per generare la chiave hash privata ho fatto in mille modi ma non sono riuscito

Ciao @jobsergio, che cosa vuole fare Lei? Parla di una chiave ma non è chiaro. Sarebbe più facile con maggiori dettagli e in inglese 😉

**Comment by muffinresearch** [comment]
This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services. If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
