### ISSUE TITLE
Add user profile routes in -prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5540]
We plan to enable the user profile feature in -prod next push (2018.07.12), so we need to setup the nginx routes in -prod before the push. We need the following routes (same as -dev and -stage):

- [x] `/user/:username/`
- [x] `/users/edit`
- [x] `/user/:username/edit/`

**Comment by bqbn** [comment]
Previous -dev and -stage issues:
* https://github.com/mozilla/addons-frontend/issues/4284
* https://github.com/mozilla/addons-frontend/issues/5453

**Comment by bqbn** [comment]
The change is staged. Please update the etherpad as a reminder for us to do it before the push.

**Comment by willdurand** [comment]
Ok, I consider this issue fixed then.

**Comment by vcarciu** [comment]
User profiles are in prod.
