### ISSUE TITLE
Remove the feature flag for user profile pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5544]
Once the user profile pages are deployed in -prod, and everything works as intended, we can remove the feature flag logic (grep for "enableUserProfile" occurrences).

**Comment by ioanarusiczki** [comment]
@willdurand Should we check that the user profile pages still work as intended?

**Comment by willdurand** [comment]
> @willdurand Should we check that the user profile pages still work as intended?

yes please, sorry for the lack of information. New user profile pages should still be there.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10). 
I filed an issue https://github.com/mozilla/addons-frontend/issues/5608
