### ISSUE TITLE
Bit.ly addon for Firefox

### ISSUE THREAD

**Issue by PerfectMagic** [mozilla/addons-frontend#5547]
I tried the link from Bit.ly to get the add on for Firefox. 
The response was could not find the page
I expected to be able to get add on like I normally do.
I am running Firebox 61.0.19(64 bit) on an iMac running macOs 10.3.5 High Sierra.
Here is a screen shot of the response I got from Bit.ly
![screen shot 2018-07-10 at 1 58 52 pm](https://user-images.githubusercontent.com/41081473/42528624-167398de-844a-11e8-993e-4d9021406fe3.png)

**Comment by wagnerand** [comment]
Please get in touch with Bit.ly to get information about the availability of their add-on.
