### ISSUE TITLE
Remove duplication of isTheme logic

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5548]
Working on issue #4632, I've discovered that we have logic for `isTheme` sprinkled around the code base in a number of places, and ideally we should have a function in just one place and import it from there whenever we need it. It probably makes sense to put it in `core/utils/index.js` and then replace all other instances with calls to that function.

I've found it also in `amo/components/Addon`, `amo/components/AddonsCard`, `amo/components/SearchResult`, and `core/tracking.js`, and it may be elsewhere as well.

@rebmullin I know you've worked on some of this code in the past - are you willing to take this on? I'm going to need it for #4632 fairly soon.

**Comment by rebmullin** [comment]
@bobsilverberg, yes actually I think we are on the same page : ) as I've added a isTheme function to utils in [this PR](https://github.com/mozilla/addons-frontend/pull/5225/files#diff-2b9cfd3cee84a8831d24b85dac4455e0L330)

after this was merged, the I was planning to update the mentioned files but I'd rather keep that separate if possible. 

However, if you do need it very soon (before I can get this PR merged), I can def extract it out in its own PR and then update in the various places in a 2nd PR...

**Comment by bobsilverberg** [comment]
Oh, nice, thanks @rebmullin. I'm not in such a huge rush, I can just wait for PR #5225 to be merged to get access to the function. I guess we can leave this issue open for the clean-up afterwards.

**Comment by vcarciu** [comment]
@rebmullin 
Please add some STRs to this bug or mark it as "qa: not needed"
