### ISSUE TITLE
 Convert setState() in ConfirmButton to setUIState()

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5550]
The [ConfirmButton](https://github.com/mozilla/addons-frontend/blob/54c4a4ddbfaea24c27620bead2254b183ba8bc61/src/ui/components/ConfirmButton/index.js) component can be converted to using [`setUIState()`](https://github.com/mozilla/addons-frontend/issues/5343).

It's only using `setState()` to show a prompt about what the user is about to confirm.

**For QA**: please make sure that confirm buttons on the collection and user profile screens still work as expected.

Part of https://github.com/mozilla/addons-frontend/issues/1250

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev and AMO stage with FF61(Win10&Android 8.0)
I don't see problems, all buttons works as expected.
