### ISSUE TITLE
Convert setState() in ExpandableCard to setUIState()

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5552]
The [ExpandableCard](https://github.com/mozilla/addons-frontend/blob/54c4a4ddbfaea24c27620bead2254b183ba8bc61/src/ui/components/ExpandableCard/index.js) component can be converted to using [`setUIState()`](https://github.com/mozilla/addons-frontend/issues/5343).

It's only using `setState()` to expand/collapse the card.

**For QA**: please make sure that tapping *filter results* in the mobile view of the search page still expands/collapses.

<img width="323" alt="screenshot 2018-07-10 14 04 56" src="https://user-images.githubusercontent.com/55398/42531733-5be0a812-844a-11e8-96cb-a08e6cc48a1d.png">
<img width="323" alt="screenshot 2018-07-10 14 05 10" src="https://user-images.githubusercontent.com/55398/42531736-5d49f23a-844a-11e8-84d8-4bacfb02b3e3.png">

Part of https://github.com/mozilla/addons-frontend/issues/1250

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF61, Win10x64 and Android 8.0
