### ISSUE TITLE
Convert setState() in ShowMoreCard to setUIState() 

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5553]
The [ShowMoreCard](https://github.com/mozilla/addons-frontend/blob/54c4a4ddbfaea24c27620bead2254b183ba8bc61/src/ui/components/ShowMoreCard/index.js) component can be converted to using [`setUIState()`](https://github.com/mozilla/addons-frontend/issues/5343).

It's using `setState()` to expand/collapse content.

**For QA**: please make sure that long add-on descriptions can still be expanded/collapsed.

Part of https://github.com/mozilla/addons-frontend/issues/1250

**Comment by ioanarusiczki** [comment]
Verified this issue on Android 8.0 with FF62 (Win10)
If I navigate away and return,  click it from search results, simply click back to see the detail page or I'm expanding the text and then refresh page the text will look collapsed.
Also if I click another add-on from the More recommendations the text will look collapsed.

![expanded on android](https://user-images.githubusercontent.com/33448286/46395626-a017c680-c6f5-11e8-85e0-eb1ab438e5b9.gif)
