### ISSUE TITLE
 Convert setState() in Overlay to setUIState()

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5555]
The [Overlay](https://github.com/mozilla/addons-frontend/blob/54c4a4ddbfaea24c27620bead2254b183ba8bc61/src/ui/components/Overlay/index.js) component can be converted to using [`setUIState()`](https://github.com/mozilla/addons-frontend/issues/5343).

It's using `setState()` to show/hide the overlay content.

**For QA**: please make sure the overlay on the user profile screen still works as expected.

Part of https://github.com/mozilla/addons-frontend/issues/1250

**Comment by ioanarusiczki** [comment]
I checked for regressions the Delete my profile modal from Edit profile page.
Verified fixed on AMO dev with FF61(Win10&Android 8.0).
