### ISSUE TITLE
The delete user account modal should contain more info

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#5560]
### STR:
1.  Go to edit user profile page: https://addons.allizom.org/en-US/firefox/users/edit
2. Click the "Delete My Account" button
3. Observe the wording

### Actual result
There is no mention that the user will be able to log in again with the deleted account but that account will not be linked with the deleted one.

### Expected result:
The wording should look like on the old pages: 
![oldpagesdeleteaccount](https://user-images.githubusercontent.com/15685441/42570232-e562cdd2-851b-11e8-82f7-5a23b3133a2c.png)

### Notes:
- reproduced on AMO -dev  and AMO -stage, FF60 Win7
Please view this screencast: 
![newpagesdeleteaccount](https://user-images.githubusercontent.com/15685441/42570248-f4dae0e2-851b-11e8-8d2f-555551fa1bc4.png)

**Comment by willdurand** [comment]
New copy available: https://docs.google.com/document/d/1nnv1gwiQe5K3tvYXdsA2QmtWKO6XD75aD31V0hoyI_k/edit?ts=5b4f947e

**Comment by madalincm** [comment]
Verified as fixed in FF61(Win7) in amo-dev and amo-stage
Postfix screencast:
![deleteuserprofile](https://user-images.githubusercontent.com/15685441/43189948-90194852-9000-11e8-84ac-9cc886dd0ca5.png)

Marking bug as verified fixed
