### ISSUE TITLE
Collection add comment button is inaccessible

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5566]
The comment button for a collection owner to add their own comments about the collection has no text alternative. It also uses purely a graphical icon with no visible text. It would be better if this was a button with an icon so the iconography assists with informing the user of what the action will do. 

As it stands there's no way to understand what the button does if you don't know what the icon represents.

If nothing else adding a text alternative for the icon would be good to get done before this is made live.

<img width="1430" alt="stuart_s_collection_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/42584182-832bc65a-852a-11e8-936e-2e6abfe3d896.png">

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-frontend/issues/5386 which relates to the same feature.

**Comment by bobsilverberg** [comment]
We're going to switch the icon to a button that says "Leave a note".
