### ISSUE TITLE
Update logic in disco pane so static themes is displayed similiarly to lightweight themes

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5568]
### Describe the problem and steps to reproduce it:

once static themes are [added to the disco pane](https://github.com/mozilla/addons-server/issues/8572), we should make sure it looks similar to lightweight themes

**Comment by rebmullin** [comment]
waiting to hear back on this [here](https://github.com/mozilla/addons-server/issues/8863) - basically we need previews so the image can be displayed:

![Alt text](https://monosnap.com/image/ki4U33wDFqkp9fiGygH8kDHgFPRbX7.png)

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64

Here is the discopane preview (680x92) of a static theme:

![image](https://user-images.githubusercontent.com/31961530/43506677-6dddbdd6-9573-11e8-8c20-dd514c8e1603.png)

@rebmullin In your last comment to this issue , you are mentioning the install when the image is clicked behavior. Was this supposed to be addressed by this patch or is it something that will follow in https://github.com/mozilla/addons-frontend/pull/5712

**Comment by willdurand** [comment]
@AlexandraMoga the install logic is indeed covered in #5712 and there is a specific issue for the disco pane: #5681.

**Comment by AlexandraMoga** [comment]
This issue can be marked as verified fixed specifically for the visual part
The install part will be tested in #5681
