### ISSUE TITLE
Collections edit buttons style inconsistencies

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5575]
On the edit collections page the buttons sometimes have outline and a blue focus style - not sure if this means this isn't using a shared button component since buttons elsewhere don't have both.

<img width="160" alt="stuart_s_collection_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/42621465-ca304b58-85b5-11e8-8aed-6cc81ee70765.png">

There's also an inconsistency with text-shadow being used in some places and not in others. I would have thought they should be consistent.

<img width="1365" alt="stuart_s_collection_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/42621632-3976c780-85b6-11e8-82ff-e54fceef5d94.png">

**Comment by arnavvats** [comment]
Hi, I'd like to take up the issue.

**Comment by willdurand** [comment]
@arnavvats go for it!

**Comment by jvillalobos** [comment]
Mentor: @willdurand

**Comment by caitmuenster** [comment]
Hey @arnavvats, how's it going with this?

**Comment by PunitGr** [comment]
Hey @willdurand. Can I take it up, since @arnavvats isn't active?

**Comment by PunitGr** [comment]
@willdurand Hey, I've opened a PR. Please take a look at it.
Also, I wasn't able to reproduce the issue with `buttons` outline. The UI has also changed w.r.t to the one mentioned in the issue above.
Please let me know if it required any more changes.

Cheers

**Comment by kumar303** [comment]
> There's also an inconsistency with text-shadow being used in some places and not in others.

This was done on purpose for accessibility. Please make sure we are following these guidelines to ensure usability of the micro buttons when the text shadow gets removed: https://github.com/FirefoxUX/photon/issues/264#issuecomment-364927535

**Comment by ioanarusiczki** [comment]
@willdurand I verified this on AMO dev - FF67 (Win10)

That's how it appeared before 

![with text-shadow](https://user-images.githubusercontent.com/33448286/58971068-53741600-87c3-11e9-9827-fe42d416a8be.png)

The text-shadow has been removed 

![no text shadow](https://user-images.githubusercontent.com/33448286/58970993-2f183980-87c3-11e9-98f7-62361803b29b.png)

@muffinresearch  I could not reproduce the outline +blue focus style issue for the "Cancel" button either on Win10, I used the Tab key for navigation. 

![only blue](https://user-images.githubusercontent.com/33448286/58971407-13f9f980-87c4-11e9-8a87-e21a36192242.png)
