### ISSUE TITLE
Remove addon: prefix from new statictheme tracking

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5578]
As discussed here: https://github.com/mozilla/addons-frontend/issues/5073 the `addon:` part is not required since `statictheme` by itself is clear enough.

**Comment by vcarciu** [comment]
Verified as fixed : 
[amo] [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Theme Installs Started","eventAction":"statictheme","eventLabel":"RM static Pink theme"}
