### ISSUE TITLE
Sort by popularity should use descending order

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#5581]
### STR:
1.  Open any collection i.e: https://addons.allizom.org/en-US/firefox/collections/mozilla/ad-blockers/
2. Go to "Sort add-ons by" drop down menu and select popularity.

### Expected result:
Most popular add-ons are displayed first

### Actual result
The add-ons are not sorted by popularity

### Notes:
Verified in FF61 Win7x64. Issue can be reproduced in amo-dev amo-stage and amo-prod
Please view this screencast:
![collectionspopularity](https://user-images.githubusercontent.com/15685441/42636155-b1926f28-85f0-11e8-95f3-528623caf2bb.png)

**Comment by bobsilverberg** [comment]
@madalincm Sort by popularity isn't based on number of users, but rather on [Number of total weekly downloads] (http://addons-server.readthedocs.io/en/latest/topics/api/collections.html#collection-addon-list-sort), so it's not obvious from this screen. I guess you can see that information in a detail API response and use that to verify that they are in fact sorted by popularity.

**Comment by bobsilverberg** [comment]
As per https://github.com/mozilla/addons/issues/760, there is an issue that we are sorting the add-ons by popularity in ascending order, but what we actually want is to sort them in descending order.

**Comment by madalincm** [comment]
Due to the lack of data from -dev and stage this can be accurate verified only in production.
Please view this request: https://addons-dev.allizom.org/api/v3/accounts/account/mozilla/collections/ad-blockers/addons/

**Comment by vcarciu** [comment]
Verified as fixed in prod.
