### ISSUE TITLE
Enable new collections UI and features on prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5585]
In order to enable the new collections UI and features on prod, we must set a the `enableNewCollectionsUI` config flag to true.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Should we test that the pages still work as intended on AMO ?

**Comment by bobsilverberg** [comment]
@ioanarusiczki Yes please!

**Comment by ioanarusiczki** [comment]
Verified on AMO dev and AMO stage with FF61(Win10 and Android 8.0) 
I filed for what I've noticed this week the following issues:
https://github.com/mozilla/addons-frontend/issues/5644
https://github.com/mozilla/addons-frontend/issues/5649
https://github.com/mozilla/addons-frontend/issues/5615
https://github.com/mozilla/addons-frontend/issues/5608
https://github.com/mozilla/addons-frontend/issues/5627
https://github.com/mozilla/addons-frontend/issues/5629
