### ISSUE TITLE
Support numeric IDs in user profile URLs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5594]
The legacy frontend allows to browse a user profile page using the numeric ID of a user and not their username: `/user/123/`. Having a numeric username is not allowed so there is no conflict.

The new/current user profile pages require the username, and passing the user ID will not work (404 returned). FWIW, the change to make it work is quite easy.

@kewisch told me he used such URLs with numeric IDs in STMO (but could change to use usernames instead).

Do we want to support numeric IDs in user profile URLs? Only for user profile pages, not for editing a user though (so only URLs like `/user/{ID or username}/`).

**Comment by muffinresearch** [comment]
My take is since there's no conflict and therefore no disambiguation issue, I think it makes sense to accommodate having ids as well as usernames under the same view.

**Comment by jvillalobos** [comment]
I'm also in favor of supporting this. Usernames can change or accounts can be deleted. The ID link is the most permanent way to link to an account.

**Comment by AlexandraMoga** [comment]
Verified on AMO stage with FF61, Win10x64

A user profile can be accessed both by slug and ID:

https://addons.allizom.org/en-US/firefox/user/basket-stage/

is the same as

https://addons.allizom.org/en-US/firefox/user/11686498/
