### ISSUE TITLE
 19 July Homepage content update

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#5599]
For the 19 July push, please update homepage content to reflect the programming in this [doc](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#heading=h.7w3i7akxugyj).

@muffinresearch

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev.

**Comment by vcarciu** [comment]
Verified as fixed in Stage too

**Comment by vcarciu** [comment]
Marking as verified since we tested in prod.
