### ISSUE TITLE
Wunderlist add on not available

### ISSUE THREAD

**Issue by fad1** [mozilla/addons-frontend#5603]
### Describe the problem and steps to reproduce it:

Go to: https://www.wunderlist.com/integrations/external/add_to_wunderlist_firefox

Click on add,

Add on was removed by author. Why??

**Comment by championshuttler** [comment]
Hi @fad1 , the decision to keep addon listing on addons.mozilla.org or deleting it is totally depend on the developer of add-on. We can not do anything in this case. Sorry . Let me know if you need any other help :)

**Comment by EnTeQuAk** [comment]
Closing with the same comment as @championshuttler, please contact the Add-ons author about their listing. We do not have any influence on their decision to be listed or not.
