### ISSUE TITLE
Only reviews are visible after editing the username

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5608]
STR:
1. Load AMO dev and go to View My Profile , make sure your account displays content for "Extensions by",  "Themes by" and "My reviews" sections.
2. Click Edit profile and update your username.
3. Observe the profile page.

Expected result:
All sections are displayed.

Actual result:
Only "my reviews" is visible. 

Notes:
After refreshing the page all the sections are displayed. 
It is not reproducible when editing the display name.
This issue is reproducible on AMO dev and AMO stage with FF61(Win10). 
 
![only reviews](https://user-images.githubusercontent.com/33448286/42753156-a76eb280-88f8-11e8-8795-a51d68146bb9.gif)

**Comment by willdurand** [comment]
Interesting, I cannot reproduce locally but I can reproduce it in -dev.

**Comment by willdurand** [comment]
Ok, I think I found the issue. When updating a username, the search API does not return the add-ons to display in the two cards ("My extensions" and "My themes"), because it has not been re-indexed I suppose.

**Comment by willdurand** [comment]
Filed an issue on addons-server: https://github.com/mozilla/addons-server/issues/8901

**Comment by ioanarusiczki** [comment]
This is no longer reproducible on AMO dev with FF63 (Win10)

![editing the username](https://user-images.githubusercontent.com/33448286/47564285-24441f00-d92d-11e8-999b-176a85ac734f.gif)
