### ISSUE TITLE
Leave a note - the layout of the collection pages are broken when a long unbroken string is used inside a note

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5615]
Re-filing https://github.com/mozilla/addons-frontend/issues/5315 The note icon was replaced with "Leave a note" and the unbroken string issue is reproducible again.

STR:
1. Load AMO dev and go to collections
2. In edit this collection make a note, use a long unbroken string, for an extension or theme that was added in the list
3. After saving it observe the layout of the page

Expected result:
Page is displayed without any layout issues.

Actual result:
Layout of the page is broken.

Notes:
This issue is reproducible on AMO dev with FF61(Win10). 

![unbroken string](https://user-images.githubusercontent.com/33448286/42765667-381bd380-8921-11e8-9164-c8d10e6f12c9.gif)

**Comment by willdurand** [comment]
@Shubhamchinda maybe something for you if you like :)

**Comment by Shubhamchinda** [comment]
Okay @willdurand . I'll work on it.
Thanks :)

**Comment by Shubhamchinda** [comment]
I'm sorry for closing the PR, my master branch is creating issues while creating new branches. I think I need to refork the rep and create upstream for further issues. "Doing newbie mistakes" -_-
I hope you understand.

**Comment by willdurand** [comment]
@Shubhamchinda it's fine, no worries. Something I wanted to suggest you for a while was to create git branches: https://www.atlassian.com/git/tutorials/using-branches

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx68, Win10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/61710382-32a75600-ad5a-11e9-89b6-c3583417ada2.png)
