### ISSUE TITLE
Standardize test files

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5616]
See also: #1260

---

I'd like to have a common naming rule for the test files, currently we have:

- `TestComponent` for a React `Component`
- `test_someThing` for a `someThing` JS file

But it is not really consistent and not always used that way (for instance, we have `testSomeThing` files sometimes).

I suggest we use the two rules above and we stick to them.

**Comment by nabendu82** [comment]
@willdurand I will like to work on this.

**Comment by willdurand** [comment]
@nabendu82 sure! please open a pull request for each folder under `tests/unit` to avoid too many changes in the same PR. It is only about renaming files, but still. Thanks!

**Comment by nabendu82** [comment]
Sorry @willdurand didn't saw your comment. Everything in one PR.

**Comment by willdurand** [comment]
haha ok, then let's see!

**Comment by willdurand** [comment]
Thanks @nabendu82!
