### ISSUE TITLE
Unable to reflect pending uninstall undo from about:addons#Extensions 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#562]
STR:
- Install an add-on via the new disco pane
- Open about:addons#Extensions
- Click remove - see the state change to uninstalling (a restart UI should be shown here - that will be covered elsewhere)
- Click undo

What happens:
- Nothing

What should happen:
- We should get an event telling us the user has cancelled the pending uninstallation.

I've filed this platform bug to expose `onOperationCancelled` https://bugzilla.mozilla.org/show_bug.cgi?id=1279046

**Comment by vcarciu** [comment]
Verified as fixed : 
![eventcancelled](https://user-images.githubusercontent.com/1583842/46081800-17a19f00-c1a6-11e8-80a6-43c20238720a.png)
