### ISSUE TITLE
Enable redux devtools in -dev

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5622]
We'd like to enable the redux devtools in -dev (and later other environments).

For QA, in -dev only:

1. install a browser extension, see: https://github.com/zalmoxisus/redux-devtools-extension#installation.
  For Firefox on AMO: https://addons.mozilla.org/en-US/firefox/addon/remotedev/
2. browse: https://addons-dev.allizom.org/
3. open the browser devtools OR click the extension icon
4. you should see something like this:

<img width="633" alt="screen shot 2018-07-16 at 23 32 06" src="https://user-images.githubusercontent.com/217628/42784766-7c259f5a-8950-11e8-8341-35a0700ad7fa.png">

**Comment by vcarciu** [comment]
Verified in both Firefox and Chrome. In Chrome everything works as expected, but nothing is displayed in Firefox. After a chat with @willdurand we decided that this one can be closed based on results from Chrome and I will open a new issue for Firefox. 

Chrome:
![reduxxhrome](https://user-images.githubusercontent.com/1583842/42820692-68ce7d20-89df-11e8-936a-df68f29c29c3.png)

Firefox:
![reduxfirefox](https://user-images.githubusercontent.com/1583842/42820701-6fce9a92-89df-11e8-923d-427cacb3d67b.png)
