### ISSUE TITLE
Try to create a read-only Button component (e.g. for styling `input[type="file"]`) instead of reusing its CSS

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5623]
In the `UserProfileEditPicture` component, the style of the `Button` component is used to create a fake button (`<span />`) that is used to style a `input[type="file"]`.

Instead of borrowing the style, we should create a read-only `Button` component OR update the existing `Button` component to render a `<span />` given certain prop (`readonly` or `fake` maybe).

**Comment by AlexandraMoga** [comment]
@willdurand could you please add STR to this issue?
Thank you

**Comment by willdurand** [comment]
@AlexandraMoga the "Choose photo" button on the edit profile page should work as expected and should visually look like on -stage or -prod.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with Firefox 61, WIn10x64

The Choose photo button works as expected and there are no style regressions. 

![image](https://user-images.githubusercontent.com/31961530/43187878-6466c54a-8ffb-11e8-95c6-55f5dad26ea4.png)
