### ISSUE TITLE
Description text box should have only a vertical expansion

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5627]
STR:
1. Load AMO dev and go to View my collection
2. Click one of the collections then edit my collection button
3. Mouse hover over the right edge of the box and expand it towards the list of extensions/themes

Actual result:
Extensions/themes overlap the text box.

Expected result:
The box won't expand over the list of extensions/themes.

Notes:
When the list of add-ons is empty the placeholder text "Search for extensions and themes to add to your collection" looks like it's in the text box.
This issue is reproducible on AMO dev and AMO stage with FF61(Win10). 

![text box should expand only vertically](https://user-images.githubusercontent.com/33448286/42804655-45a287ec-89b2-11e8-9764-55cb6e9c5408.gif)

**Comment by caitmuenster** [comment]
Mentor: @rebmullin 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by suhailsinghbains** [comment]
Hi, I am new to contributions for Mozilla, can I please be assigned this issue, would love to work on it.

**Comment by championshuttler** [comment]
Hi @suhailsinghbains Go for it! If you need any help, please feel free to ask here :wink:

**Comment by suhailsinghbains** [comment]
Okay, thanks @championshuttler . Working on it right away!

**Comment by suhailsinghbains** [comment]
I thought I would figure out the file that needs to be changed, but, was not successful at that.
Please tell the file that require the change.

**Comment by championshuttler** [comment]
Hi @suhailsinghbains if i am not wrong the files you are looking for are here  `src/amo/components/CollectionDetails`

**Comment by suhailsinghbains** [comment]
My old PC is not working properly, I'll load the project onto my new PC, will update you soon.

**Comment by suhailsinghbains** [comment]
![image](https://user-images.githubusercontent.com/10033914/44005301-f923fed6-9e8e-11e8-8bb7-415de9a5150c.png)
I did a lot research, can't just past this step.
Please if someone could help me.

**Comment by championshuttler** [comment]
Hi @suhailsinghbains, as the error in the attached screenshot, you have to use node version =>6 <=8.
This means please use node version 6 or more but less than 8 . You can use [nvm](https://github.com/creationix/nvm) to use different node versions ;)

Let us know if you need any other help :smile:

**Comment by suhailsinghbains** [comment]
I had to make some packages, delete some, all in all, the project works, now, this shohuldn't take long.

**Comment by suhailsinghbains** [comment]
@championshuttler Hi, the issue has been solved, should I make another branch addressing my issue or just make a Pull Request.

**Comment by willdurand** [comment]
> @championshuttler Hi, the issue has been solved, should I make another branch addressing my issue or just make a simple Pull Request.

A Pull Request starts from a branch, but it does not matter which one as far as you have only the commit(s) for fixing this issue in that branch (and not other commits for other issues for example). Usually, we create one branch per issue to keep things separated and we avoid to work on the main branch (`master`) but this is up to you :)

**Comment by suhailsinghbains** [comment]
Okay, I'll use the branch method. 
Thanks for your help @willdurand !

**Comment by willdurand** [comment]
Amazing first contribution @suhailsinghbains!

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10)
![only vertical expansion](https://user-images.githubusercontent.com/33448286/44340989-4afa5b00-a48f-11e8-9410-017dbc367d3a.gif)

I filed a separate issue https://github.com/mozilla/addons-frontend/issues/5988 for what I've noticed while testing this one.
