### ISSUE TITLE
Install switch moves when turning on

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#563]
When turning on the install switch, the switch moves down a pixel and kind of "glitches out" at the top:
![c1e5256a-2d63-11e6-8213-4f4c13f88361](https://cloud.githubusercontent.com/assets/6797635/15916030/4b3743cc-2da3-11e6-83c8-60d84ed72395.png)
It returns to normal when switched off.
@muffinresearch says it could be an issue with secondary monitors, as it looks fine on my Macbook currently.

**Comment by muffinresearch** [comment]
Looks like adding a transition on the border prevents this jank. Should be fixed by #561
