### ISSUE TITLE
Redux devtools not working in Firefox in -dev

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#5634]
Steps to reproduce:
1. Install a browser extension, see: https://github.com/zalmoxisus/redux-devtools-extension#installation.
    For Firefox on AMO: https://addons.mozilla.org/en-US/firefox/addon/remotedev/
2. Browse: https://addons-dev.allizom.org/
3. Open the browser devtools and select Redux panel

Expected results:
You should see something like this:
![reduxxhrome](https://user-images.githubusercontent.com/1583842/42821095-74062692-89e0-11e8-977d-4bc8ae080dd8.png)

Actual results:
I can see this on Firefox : 
![reduxfirefox](https://user-images.githubusercontent.com/1583842/42821136-8cd9cc1e-89e0-11e8-97d8-c02d026355d8.png)

NOTES:
Follow up from #5622 
Working in chrome

**Comment by kumar303** [comment]
I asked on IRC and the reason `addons-dev.allizom.org` is blocked from running extensions is because that domain has access to [`mozAddonManager()`](https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md) which has super powers. We should probably close this as cant-fix.

**Comment by willdurand** [comment]
Closing as wontfix then.
