### ISSUE TITLE
Disable the "Save collection" button unless one of the fields in the edit form has been changed

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5635]
As discussed in last week's front-end UX meeting, the following changes should be made to the collection edit screen:

1. Move the select which is used to add an add-on to a collection from the edit form into the card below (the one that currently holds the sort select).
2. Disable the "Save collection" button unless one of the fields in the edit form has been changed.

**Comment by bobsilverberg** [comment]
I've decided to split this into two issues. The first requirement above was moved into issue #5675, so I am going to repurpose this issue to be solely about the second requirement, which is to disable the "Save collection" button unless one of the fields in the edit form has been changed.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, WIn10x64 and Android 8.0

The Save button for the edit collection form is disabled until one of the fields - name, description, url - are edited.

![save button](https://user-images.githubusercontent.com/31961530/43131744-6e28452c-8f42-11e8-94da-4b9753ea4a0d.gif)


I have filed a follow up issue #5702  for my concern regarding the Save button state after an add-on is added/removed from the collection
