### ISSUE TITLE
Create a CollectionSort component to reduce the code in the Collection component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5638]
As we're going to relocate the sort select in #5635, it seems like a good time to extract the code for the sort select into its own component, and that's what this issue is about.

**Comment by AlexandraMoga** [comment]
@bobsilverberg should I understand that this fix is targeting mostly the Sort feature in Collection?
Thanks

**Comment by bobsilverberg** [comment]
@AlexandraMoga Yes, verifying the behaviour of sort should suffice for QA, thanks!

**Comment by AlexandraMoga** [comment]
There were no issues found with the collection Sort functionality.
Marking issue as verified fixed
