### ISSUE TITLE
Leave a note in collections field - text typed in after an emoji is not displayed 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5644]
STR:
1. Load AMO dev and go to Edit collection page
2. Click the "leave a note" for a theme/add-on
3. Insert some text then an emoji and then some more text then click save
4. Observe the comment

Actual result:
The emoji and the text typed after the emoji are not displayed.

Expected result:
The text and emojis are visible.

Notes:
This issue is also reproducible with the description field for collections.
This issue is reproducible on Android 8.0 with FF61(Win10).

![android emoji](https://user-images.githubusercontent.com/33448286/42868463-146b9bcc-8a7b-11e8-9350-45d06310450f.gif)

**Comment by muffinresearch** [comment]
Seems to be the same thing as https://github.com/mozilla/addons-frontend/issues/5649

**Comment by muffinresearch** [comment]
I've created a server issue for this here, and it will be fixed there: https://github.com/mozilla/addons-server/issues/8923
