### ISSUE TITLE
Improve contrast of survey notice box

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5653]
As a follow up to https://github.com/mozilla/addons-frontend/issues/5438, improve contrast of the notice box. Currently you cannot see the notice box because it's the same as the background color.

From @pwalm on IRC:

> kumar: Can we change the background of the survey message bar to #d7d7db for better contrast against the background?

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10&Android 8.0)
on desktop - Win10
![survey without white space](https://user-images.githubusercontent.com/33448286/42994888-0c04c2f8-8c18-11e8-93c0-78077369fea7.png)

mobile device - Android 8.0
![short survey android](https://user-images.githubusercontent.com/33448286/42994833-e535a7b4-8c17-11e8-9105-1308b81b3ba8.png)
