### ISSUE TITLE
Add-on review listing has too much whitespace under the survey

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5655]
As fallout from https://github.com/mozilla/addons-frontend/issues/5438, the add-on review listing has too much whitespace under the survey.

<img width="833" alt="screenshot 2018-07-18 14 58 28" src="https://user-images.githubusercontent.com/55398/42904688-6659d618-8a9b-11e8-89c2-b455ef876680.png">

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10 & Android 8.0)

![survey on reviews page](https://user-images.githubusercontent.com/33448286/42995096-a71e182a-8c18-11e8-91f6-4a388f5e7da8.png)

![survey without white space](https://user-images.githubusercontent.com/33448286/42995061-8ba11e1c-8c18-11e8-8cdf-53d61975fb62.png)
