### ISSUE TITLE
Integration test for uploading an XPI to DevHub is flaky

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5657]
The CircleCI integration tests for uploading an XPI to DevHub times out a lot. We should fix it or disable the test.

Example https://circleci.com/gh/mozilla/addons-frontend/8848?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
______ ERROR at setup of test_devhub_addon_upload[Resolution: 1080x1920] _______
...
E       TimeoutException: Message:
```

**Comment by kumar303** [comment]
Looks like it's still timing out. Is there a way to get more logging?

```
tests/ui/test_devhub.py::test_devhub_addon_upload[Resolution: 1080x1920] Too long with no output (exceeded 10m0s)
```

https://circleci.com/gh/mozilla/addons-frontend/9032?utm_campaign=build-failed&utm_medium=email&utm_source=notification

**Comment by jrbenny35** [comment]
The current errors are related to fxa, same as what we are seeing on addons-server. I thought this was related to the permissions, maybe it was, but now it is the fxa failures.

**Comment by willdurand** [comment]
moving to next milestone

**Comment by jrbenny35** [comment]
Should be fixed now with https://github.com/mozilla/addons-server/pull/9266
