### ISSUE TITLE
'Remove' button is hard to read on collection edit screen

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5658]
### Describe the problem and steps to reproduce it:

- Create a collection
- Add some add-ons
- Edit the collection

### What happened?

The Remove button is hard to read on various screen sizes:

<img width="1266" alt="screenshot 2018-07-18 15 52 32" src="https://user-images.githubusercontent.com/55398/42907244-d35939a0-8aa2-11e8-8c36-aeba68f17421.png">

### What did you expect to happen?

The Remove button should be easy to read

**Comment by AlexandraMoga** [comment]
This seems to reproduce only on MacOS (Sierra 10.13.2). I've tried in parallel on Windows 10x64 and Android 8.0 (FF61 and Nightly 63.0a1) an the issue was not reproduced.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, macOS (High Sierra 10.13.2)

![image](https://user-images.githubusercontent.com/31961530/43125534-fecdce7c-8f32-11e8-9c04-fd0fb4c14119.png)
