### ISSUE TITLE
"See more add-ons!" button at top and bottom of Disco Pane list

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#5660]
We have a button at the bottom of the extensions/themes on the disco pane:
<img width="800" alt="screen shot 2018-07-18 at 2 30 41 pm" src="https://user-images.githubusercontent.com/6797635/42908936-2bdded16-8a97-11e8-81ec-9ceb809c00a9.png">

We need the same button at the top of the list as well, since some users don't scroll all the way down. Is the copy ok @MeridelW?

**Comment by MeridelW** [comment]
Please change button copy to: **Find more add-ons**

Rationale: "see more" sounds like more extensions will be unveiled within Disco Pane when in fact the user will be sent out to AMO, where they can "find" add-ons. Also, in product we try to limit exclamation points.

**Comment by willdurand** [comment]
I have updated the tracking label from "See more add-ons" to "Find more add-ons" (no matter which button is clicked) and the `utm_content` query parameter is either `find-more-link-top` or `find-more-link-bottom` depending on the button.

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev : 
![findaddons](https://user-images.githubusercontent.com/1583842/43319270-bf65bc82-91ac-11e8-80e3-0ee613974118.png)
