### ISSUE TITLE
Collection button styles are off after update

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5661]
### Describe the problem and steps to reproduce it:

The styles/classname got changed in last PR #5642

### What happened?

This is throwing off the styles a bit

**Comment by AlexandraMoga** [comment]
@rebmullin just wanted to check if your issue also targets the following style regression:

![image](https://user-images.githubusercontent.com/31961530/42926054-e99cca1a-8b38-11e8-9ad6-d0046bed420a.png)

![image](https://user-images.githubusercontent.com/31961530/42926058-eca5e386-8b38-11e8-846e-b8338a7ca232.png)

**Comment by rebmullin** [comment]
Hey @AlexandraMoga, yes this should be fixed in both places you have shown. thanks!
