### ISSUE TITLE
Create a CollectionAddAddon component to extract the display and logic for the AutoSearchInput for adding an add-on to a collection

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5667]
Supports #5635 

We're going to move the AutoSearchInput for adding an add-on to a collection from the current edit form into the card where the Sort select currently resides. To support this we should extract all the logic and display code for it into its own component.

**Comment by AlexandraMoga** [comment]
I have made some checks around the Search /add to collection and Sort components and I have the following results:
- searching and adding add-ons to a collection is working as expected
- success/error messages are generated according to the action made by the user
- the error messages are displayed now right above the search box [1]
- sorting is working as expected

[1]
![image](https://user-images.githubusercontent.com/31961530/43196832-f265ae18-9011-11e8-947c-fa48075ba844.png)


I have found one issue with regards to the errormesseage displayed when trying to add the same add-on to a collection - see https://github.com/mozilla/addons-frontend/issues/5722 

I'm marking this issue as verified fixed on AMO stage with FF61, Win10x64 and Android 8.0
