### ISSUE TITLE
Add analytics event to "Take the survey" button

### ISSUE THREAD

**Issue by jenniferdavidson** [mozilla/addons-frontend#5670]
Add an analytics event on the "Take the survey" button that's part of the message bar implemented here in Issue #5438 so we can tell how many people have clicked on the button.

**Comment by kumar303** [comment]
From IRC:

> Surveygizmo only records if they’ve completed the first page.

so we don't really have any *view* events at all.

**Comment by jenniferdavidson** [comment]
@kumar303 Correct. [Screenshot of Fall Off Report from SurveyGizmo](https://screenshots.firefox.com/X4mIK3s0YZhzFfet/app.surveygizmo.com)

**Comment by kumar303** [comment]
OK, we'll have analytics going out next push (Thursday). The new google analytics category will be `AMO Addon / Experience Survey Notice` and we'll have these events:

- `Shown survey notice` (notice appeared for this user)
- `Visited survey` (they clicked on the button)
- `Dismissed survey notice` (they clicked the X)
