### ISSUE TITLE
My Favorite Add-ons collection still points to the legacy site

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5671]
### Describe the problem and steps to reproduce it:

- Log in
- Go to *View my collections*
- Click on the built-in collection *My Favorite Add-ons*
- Reload the page

### What happened?

At first you see the new site but when you reload you see the old site.

### What did you expect to happen?

You should always see the new site.

### Anything else we should know?

I think the [route to `/favorites/`](https://github.com/mozilla-services/cloudops-deployment/blob/046c6021680a9a74708f8a4d9bfb81a5a0566f2f/projects/amo/puppet/modules/amo_proxy/templates/nginx.addons.conf.erb#L395) did not get updated in https://github.com/mozilla/addons-frontend/issues/4655.

**Comment by bqbn** [comment]
So what needs to be fixed here?

Per https://github.com/mozilla/addons-frontend/issues/3888, `collections/<your_username>/favorites/` should **NOT** be routed to the mobile site.

Is it that we need to change that? i.e. route `collections/<your_username>/favorites/` to the mobile site, and the issue would be fixed?

**Comment by willdurand** [comment]
@bqbn the configuration for `/collections/:user/favorites/` should be removed, i.e. the new frontend should accept it now.

**Comment by bobsilverberg** [comment]
It looks like this was fixed via https://github.com/mozilla-services/cloudops-deployment/pull/2279.

**Comment by vcarciu** [comment]
Verified as fixed : 
![myfavcollection](https://user-images.githubusercontent.com/1583842/43136295-f33c1c58-8f50-11e8-93f6-529a339de545.gif)
