### ISSUE TITLE
The loading screen is jarring while editing a collection

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5672]
### Describe the problem and steps to reproduce it:

- Log in
- Create a new collection
- Edit the collection
- Add/remove add-ons

### What happened?

Each time you add or remove an add-on, the loading screen fills the whole page which is jarring.

### What did you expect to happen?

The loading screen could be a little less jarring.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64

![less loading screen](https://user-images.githubusercontent.com/31961530/43071805-8c1372bc-8e7c-11e8-8fa0-28125ed9e1b4.gif)
