### ISSUE TITLE
Move the select which is used to add an add-on to a collection out of the edit form

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5675]
Move the select which is used to add an add-on to a collection from the edit form into the card that appears below the edit form (the one that currently holds the sort select).

This is an attempt to make it more obvious that saving collection metadata is an operation independent of adding add-ons to the collection.

**For QA** please make sure that all collection editing functionality (saving metadata and adding/removing add-ons) still works.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64 and Android 8.0

![search box](https://user-images.githubusercontent.com/31961530/43322625-d895c368-91b7-11e8-95ec-649a951b5481.gif)
