### ISSUE TITLE
Replace 302 locale redirects with 301

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5677]
To improve the SEO signals we should use a 301 for locale redirects instead of a 302.

**Comment by AlexandraMoga** [comment]
I can see a 301 response if I request an unsupported locale, for example, in which case the page will be redirected to `en-US` by default.

https://addons.allizom.org/en/firefox/


![image](https://user-images.githubusercontent.com/31961530/46407256-ef222380-c716-11e8-941f-600782b01415.png)

@willdurand is there a better method to test this functionality?

**Comment by willdurand** [comment]
> @willdurand is there a better method to test this functionality?

You can try to use `en` as locale (as you did), but also `en-us` (lowercase) and omit the trailing slash. That should redirect you.

**Comment by AlexandraMoga** [comment]
> You can try to use `en` as locale (as you did), but also `en-us` (lowercase) and omit the trailing slash. That should redirect you.

I've tried with these examples and the results were as expected.

Marking issue as verified fixed.
