### ISSUE TITLE
Update logic in disco pane so static themes are installed similiarly to lightweight themes

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5681]
### Describe the problem and steps to reproduce it:

Right now, you can't see the theme when it's toggled on. It seems to install but be enabled

You should also be able to click the image to "toggle on"

### What did you expect to happen?

If should appear to work the same way lightweight themes

### Anything else we should know?
notes for dev: 
if you run `setCurrentStatus` on the change of status in `componentsWillReceiveProps`, you see the following with toggling on/off:

first toggle on: 
you see theme

first toggle off:
you see theme turn off and uninstalls

2nd toggle on:
it's seems to download/install but it gets disabled. You can click the switch here and enables  ** this is the issue - need to look into this more

2nd toggle off:
you see theme turns off and uninstalls

**Comment by muffinresearch** [comment]
To workaround https://bugzilla.mozilla.org/show_bug.cgi?id=1477328 (mozAddonManager doesn't enable static themes after install) we'll need to try to use `installTrigger.install()` for installs and see if we can use mozAddonManager to uninstall so that the button still reflects the state properly.

/cc @willdurand for the issue about re-implementing mozAddonManager features in the AMO install button.

**Comment by rebmullin** [comment]
After digging in a bit more, I noticed there is an enable helper function in the addonManager file. I discussed with @muffinresearch and will use this the workaround with addonManager's install instead of installTrigger. 

// cc @willdurand

**Comment by rebmullin** [comment]
closing this as @willdurand is working on related work to this in PRs #5712 (and maybe #5791)

**Comment by willdurand** [comment]
Let's keep it open to make sure we address this issue as it is specific to the disco pane.

**Comment by willdurand** [comment]
@rebmullin I think we should probably bring your patch back for disco pane, since pending PRs are... still pending.

**Comment by willdurand** [comment]
There is a function on the `mozAddonManager` called `mozAddonManager.getAddonByID()`, which takes a GUID and returns data about the add-on, including `isEnabled` that we could use to determine whether a static theme has to be enabled after having installed it.

**Comment by willdurand** [comment]
We should do that in both `InstallButton` and `AMInstallButton`.

**Comment by rebmullin** [comment]
thanks @willdurand, I'll take another look at this now your other PR is merged.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, Win10x64
- static themes can be installed by clicking on the 'Install Theme' button
- static themes can be installed by clicking on the preview image
- static themes can be uninstalled by clicking on the Remove button

![st disco install](https://user-images.githubusercontent.com/31961530/44204644-1b301800-a15c-11e8-8f61-ea167bd5fd99.gif)
