### ISSUE TITLE
Use / discuss using available srcset options for previews

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5691]
### Describe the problem and steps to reproduce it:

we removed srcset out of the following PR #5225 to discuss further.

**Comment by willdurand** [comment]
I don't think we should be spending time on adding `srcset` on theme previews. The recent changes have improved the situation and the result is super great!

If we want to give `srcset` a try, it would be more valuable to start looking at the screenshot component IMHO.

**Comment by muffinresearch** [comment]
@rebmullin please could you update the description with more details and the key benefits we would get from implementing srcset here? It'll be helpful to provide an overview in this issue for the purposes of any discussion and to know where this should be in terms of priorities.

**Comment by rebmullin** [comment]
I guess I thought the srcset setup would be a work in progress. Right now the current sizes do work but are really only noticeable on non-retina devices.  Unfortunately, I didn’t realize resolution would matter even if we used its w options. Also the sizes attributes don’t work as I expected so you don’t really have control over the breakpoints like I thought you would (like with the picture element). Picture element may be worth looking into too IMO.

So this is what I am seeing for the current sizes that we are have (using header for example)- at approx 670px, the thumb versions are downloaded for non-retina. For retina it's going to use the bigger size here b/c this is about the min size you would want for retina mobile.  I don’t think it hurts anything and it does swap out the images but again only really with the lower resolutions devices so I agree that’s its not as useful with our current sizes.

I am actually going to do another PR for this same issue using the Picture element and maybe we can compare set up, etc.
