### ISSUE TITLE
Crono Gone from Addons

### ISSUE THREAD

**Issue by arkag** [mozilla/addons-frontend#5695]
### Describe the problem and steps to reproduce it:

Crono extension from https://crono.app has disappeared from the addon store.

### What happened?

It was there yesterday afternoon and is now no longer there.

### What did you expect to happen?

To be available to download

### Anything else we should know?

Not sure what happened, would love to know why this was pulled.

**Comment by jvillalobos** [comment]
The add-on listing is not available right now due to pending issues with its code review. It's up to the developer to respond so the listing is enabled again.
