### ISSUE TITLE
A glitch appears when opening a theme listing page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5703]
STR:

1. Load AMO -dev
2. Select a theme to view its listing page

Actual result:
A glitch appears (a zoomed in default icon) right before the theme details page is loaded

Expected result:
There are no display issues when visiting a theme details page

Notes:
- reproduced on AMO dev with FF61, Win10x64 and Android 8.0
- the issue is also visible on stage but a little bit less pronounced 

![theme icon glitch](https://user-images.githubusercontent.com/31961530/43135064-ca53bfc0-8f4c-11e8-9a45-d29124485d08.gif)

**Comment by rebmullin** [comment]
QA note: The default icon should still show up while we are waiting for the addon to load but it should look a little nicer. By limiting the height for the respective sections, it should hopefully appear a little less intrusive.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with Firefox 61, Win10x64

Here is how the loading theme looks now:

![glitchy icon](https://user-images.githubusercontent.com/31961530/43318882-475c7ee8-91ab-11e8-97bb-a1f941e8f33c.gif)

@rebmullin I see that there are two icons displayed before the theme preview is generated:

**[1]**
![image](https://user-images.githubusercontent.com/31961530/43318954-91ef45d0-91ab-11e8-8670-a7e001cf470f.png)

**[2]**
![image](https://user-images.githubusercontent.com/31961530/43318969-a591fdb2-91ab-11e8-9d98-8f09dd4ea781.png)

I know that **[1]** is expected to be there but what about **[2]** ? Is there no possibility to get rid of that?

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF61, Win10x64 and Android 8.0

![no more glitch](https://user-images.githubusercontent.com/31961530/43505944-24468d3a-9571-11e8-95b8-6c25056e874e.gif)
