### ISSUE TITLE
Reddit Pro Tools

### ISSUE THREAD

**Issue by DiscreteChi** [mozilla/addons-frontend#5705]
I think this addon has been falsely flagged with the "report abuse" feature. 

https://addons.mozilla.org/en-US/firefox/addon/reddit-pro-tools/

It's an addon for the site that helps identify people that take part in discussions in right wing groups known to troll and brigade other subreddits. You can find a description of it's functionality here:

https://www.reddit.com/r/Fuckthealtright/comments/8hiwux/reddit_pro_tools_automatically_tag_trolls_and/

**Comment by wagnerand** [comment]
Please contact the author of the add-on about its status.
