### ISSUE TITLE
My collections page is trying to access a deleted collection right after the collection has been deleted

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5708]
STR:

1. Log in to AMO
2. Go to View My collection
3. Select one of your collections to view its details page
4. Open the web console and go to the Network tab
5. Click on Delete this collection
6. Observe the API calls made in the Network tab

Actual result:
There is a request sent to get the details of the collection that has just been deleted, resulting in a 404 response

Expected result:
My collections page should not try to access details for a collection that has just been deleted

Notes:
- there are no visible errors on My collections listing page
- these are the two endpoints accessed: 
1. `https://addons-dev.allizom.org/api/v3/accounts/account/<user>/collections/<coll_slug>/?lang=en-US&wrap_outgoing_links=true`
2. `https://addons-dev.allizom.org/api/v3/accounts/account/<user>/collections/<coll_slug>/addons/?page=1&sort=-added&lang=en-US&wrap_outgoing_links=true`
- reproduced on all AMO servers with FF61, Win10x64

![404 req my coll](https://user-images.githubusercontent.com/31961530/43148310-b54e67b2-8f6d-11e8-8b78-289a18e146b6.gif)

**Comment by bobsilverberg** [comment]
This is happening because we are calling `unloadCollectionBySlug` in the saga before `pushLocation`, which is resulting in the state changing while we are still on the collection details screen, and is therefore causing it to attempt to retrieve the collection again. I believe that simply changing the order of these calls will fix this.

**Comment by caitmuenster** [comment]
Looks like @championshuttler is already working on this. :) 👍🏽

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, WIn10x64

![delete ok](https://user-images.githubusercontent.com/31961530/43962747-263123d8-9cc1-11e8-8cd7-aad733036b32.gif)
