### ISSUE TITLE
The edit profile page should not load when accessed with a numeric username

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5720]
STR:

1. Log in to AMO stage
2. Access an edit profile page that has a numeric username in the URL - see https://addons.allizom.org/en-US/firefox/user/11686498/edit/

Actual result:
The edit profile form is loaded with no actual user data displayed

Expected result:
The edit profile page should return a 404 when accessed with a numeric username 

Notes:
- reproduced on AMO dev and stage with FF61, Win10x64

**Comment by willdurand** [comment]
This is now a wontfix because we want to get rid of the `username` now, hence having the user ID in the URL will become a feature.

**Comment by willdurand** [comment]
See: #6526
