### ISSUE TITLE
The "Added to collection" message will not fade out after 5 seconds on stage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5721]
STR:

1. Log in to AMO stage
2. Go to Visit my Collections
3. Select one of your collections to edit
4. Add a new add-on to the collection
5. Check how much time it takes for the "Added to collection" message to fade out

Actual result:
The "Added to collection" message fades out after about 20 - 30 seconds

Expected result:
The "Added to collection" message fades out after 5 seconds

Notes:
- only reproduced on AMO stage
- not sure if it has anything to do with https://github.com/mozilla/addons-frontend/pull/5715

![message fade out](https://user-images.githubusercontent.com/31961530/43191618-2f9ef176-9004-11e8-89ce-de247626e711.gif)

**Comment by willdurand** [comment]
Re-running the Circle CI job to be able to deploy on -stage. The fix for this issue has been merged (so available in -dev) and cherry-picked (2018.07.26-1).

**Comment by AlexandraMoga** [comment]
Verified fixed in stage.
