### ISSUE TITLE
Fix "login" -> "log in" instance

### ISSUE THREAD

**Issue by TonnesM** [mozilla/addons-frontend#5726]
Recent commit https://github.com/mozilla/addons-frontend/pull/5716/commits/1a6547fd9c91977b18cb26383a8066ffeb8915ae added the following:

+#: src/amo/components/UserProfileEdit/index.js:787
+msgid ""
+"When you use this email address to login again to addons.mozilla.org, you "

"Login" should be "log in", as it is not a noun.

**Comment by bobsilverberg** [comment]
I believe the original text was suggested by @MeridelW. Can you confirm whether we should use "login" or "log in"?

**Comment by TonnesM** [comment]
For the record, in case the upcoming change would lead to moving "again" for some reason, be sure to use

"When you use this email address to log in to addons.mozilla.org again, you ..."

... i.e. do not use "log into" (see [here](https://design.firefox.com/photon/copy/word-list.html#s)).

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed
Thanks

**Comment by willdurand** [comment]
@AlexandraMoga A user should read "When you use this email address to log in again to addons.mozilla.org, you [...]" when clicking the "delete profile" button. It should simply be "log in" and not "login".

**Comment by vcarciu** [comment]
Verified as fixed : 
![login](https://user-images.githubusercontent.com/1583842/43455035-568cd2ae-94c7-11e8-89e9-c863f836c9de.png)
