### ISSUE TITLE
Feedly Add-On

### ISSUE THREAD

**Issue by JKA88** [mozilla/addons-frontend#5731]
### Describe the problem and steps to reproduce it:

The link ( https://addons.mozilla.org/en-US/firefox/addon/feedly-save-to-board/ ) should lead to a Feedly Add-On but it is not available. Feedly customer support told me they have submitted their Add-On for approval by Mozilla. Is there an ETA for this? Thank you!

### What happened?

Official Add-On not available

### What did you expect to happen?

Add-On should be available

**Comment by wagnerand** [comment]
I checked and can confirm that there is no version waiting for review. It is up to the developer to submit a version that follows our review policies.
