### ISSUE TITLE
The links for Thunderbird and Seamonkey need to be updated in the 'About add-ons' guide 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5733]
STR:

1. Load https://addons.allizom.org/en-US/about
2. Hover over 'Thunderbird"
3. Check the redirection link displayed in the tooltip 

Actual result:
The redirection link points to https://addons.allizom.org/thunderbird/

Expected result:
The redirection link should  point to https://addons.thunderbird.net/thunderbird/

Notes:
- it also applies for the link pointing to Seamonkey 
- the redirection is happening as expected, this issue only refers to the information displayed on AMO

![image](https://user-images.githubusercontent.com/31961530/43251129-ca2dc62c-90c7-11e8-9888-fe4979245895.png)

**Comment by willdurand** [comment]
@AlexandraMoga by not adding a specific locale on these URLs, the thunderbird/seamonkey websites will choose the best locale for the user. I am not sure we should be changing those URLs on AMO.

**Comment by willdurand** [comment]
oh ok!

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF61, Win10x64

![image](https://user-images.githubusercontent.com/31961530/43317349-26c9a738-91a5-11e8-8e6b-4ec4184e0f04.png)
