### ISSUE TITLE
Proposal to identify "page-level" components

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5735]
We do have some components that are "page-level" components because we do not instantiate them ourselves, we pass them to React Router, which does the instantiation and so on.

Those components should be identified as "page-level" components. Those components get props from the React Router layer (without a HOC) and we should make it clear that they are a bit special.

I see two options:

1. we introduce a new directory `pages` either in `src/<project>/` or `src/<project>/components/`
2. we suffix these components with `Page`, but I don't really like the idea

I'd go for a new directory, probably: `src/<project>/components/pages/`.

What do you think?

**Comment by bobsilverberg** [comment]
Do we need to do this? What do we save by not using the `withRouter` HOC for those components? I'm thinking that maybe it's simpler if we just always use `withRouter` when we need access to router variables like `history` and `location`.

**Comment by bobsilverberg** [comment]
In that case I vote for #1, using `src/<project>/components/pages/`.

**Comment by willdurand** [comment]
I also like `src/<project>/components/pages/`, so the idea would be to move all these "page-level" components to this new directory.

**Comment by willdurand** [comment]
We have 2 more voices in favor of `src/<app>/pages`, so looks like we will adopt this directory!

**Comment by ioanarusiczki** [comment]
@willdurand Could you give some STR for QA testing? Thanks!

**Comment by willdurand** [comment]
> @willdurand Could you give some STR for QA testing? Thanks!

there should be no regression, if we can still access all the pages of the website, that's fine. It should be enough to browse the homepage, an add-on detail page, its list of reviews, a list of collection, and a user profile.

**Comment by ioanarusiczki** [comment]
This has been verified in detail for https://github.com/mozilla/addons-frontend/issues/6189 
I'm marking this issue verified fixed on AMO dev with FF62(Win10).
