### ISSUE TITLE
The query parameter values should be string values, not numbers, everywhere

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5737]
The `page` parameter used for API calls is not always considered a string value, leading to inconsistencies and issues with Flow. It applies to ALL query parameters.

See also:

- https://github.com/mozilla/addons-frontend/blob/master/src/amo/api/reviews.js#L143
- https://github.com/mozilla/addons-frontend/pull/5652/files/d7e6609988c0f2a079e7e88d36b086d7c56c79d2#r205250173
- https://github.com/mozilla/addons-frontend/pull/5652#discussion_r205260797

**Comment by rebmullin** [comment]
I only addressed the `page` parameter in PR #6549. I am splitting this up since these are a bit more involved and to help keep PRs smaller in size.

**Comment by willdurand** [comment]
For QA: please make sure paginated content still works (search results, collections)
