### ISSUE TITLE
Create a AnimatedIcon component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5744]
This will be needed to implement #3954. The `AnimatedIcon` component should provide a "loading" animated icon:

![2018-07-26 16 44 38](https://user-images.githubusercontent.com/217628/43273208-27549bf8-90fc-11e8-8f41-30b3a6cfb0e1.gif)

See: https://github.com/mozilla/addons-frontend/issues/3954#issuecomment-405539718

**Comment by AlexandraMoga** [comment]
@willdurand should I be able to see this on  -dev for the discopane?

**Comment by willdurand** [comment]
@AlexandraMoga not yet, either I add "qa: not needed" here or we wait until we can see this icon in -dev. What do you prefer?
