### ISSUE TITLE
The Node Security Platform service is shutting down 9/30

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5750]
See: https://blog.npmjs.org/post/175511531085/the-node-security-platform-service-is-shutting

I think we should remove `nsp` from the list of dependencies and also remove the job run on Travis CI. We have Snyk for security checks, which seems more accurate and does not randomly fail.

What do you think?

**Comment by muffinresearch** [comment]
As noted by the link the functionality from nsp has moved into `npm@6` with `npm audit`. So if we did want to move in the direction of npm in the future that's another option.

Having Snyk means we can remove nsp sooner in any case.

**Comment by kumar303** [comment]
nsp was nice because it didn't require an API token like Snyk does. I guess we could move to Snyk temporarily until `npm audit` is available.
