### ISSUE TITLE
Add canonical link tags for pages excluding query parameters that don't change the content.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5755]
## Here's some examples:

* https://addons.mozilla.org/en-US/firefox/addon/emoji-cheatsheet/?src=homepage-collection-featured
* https://addons.mozilla.org/en-US/firefox/addon/emoji-cheatsheet/

The two URLS above should be seen as the same content. To fix that we need a link tag pointing to the link without the query param:

```html
<link rel="canonical" href="https://addons.mozilla.org/en-US/firefox/addon/emoji-cheatsheet/" />
```

Pages to consider in this issue (for QA):

- [x] add-on detail pages
- [x] homepage
- [x] Landing Extensions: https://addons.mozilla.org/en-US/firefox/extensions/
- [x] Landing Themes: https://addons.mozilla.org/en-US/firefox/themes/
- [x] Themes / category pages (https://addons.mozilla.org/en-US/firefox/themes/)
- [x] About page: https://addons.mozilla.org/en-US/about
- [x] Review guide: https://addons.mozilla.org/en-US/review_guide
- [x] Dictionaries and Lang Packs: https://addons.mozilla.org/en-US/firefox/language-tools/
- [x] Extensions / category pages (https://addons.mozilla.org/en-US/firefox/extensions/)

## Paginated content

If content has pagination the query parameters **do** change the content, because of this we should not rel="canonical" without query params or this will prevent indexing of paginated content.

See https://yoast.com/rel-canonical/ for more info.

Since paginated content has some additional requirements **it will be handled in a separate issue.**

Pages with paginated content:

- user profiles
- collections
- Search tools: https://addons.mozilla.org/en-US/firefox/search-tools/
- Collection pages: https://addons.mozilla.org/en-US/firefox/collections/mozilla/ad-blockers/

**Comment by willdurand** [comment]
@muffinresearch do we want this `meta` tag on static pages too? (e.g., about page, landing pages, etc.)

**Comment by ioanarusiczki** [comment]
I verified the pages mentioned by @muffinresearch [here](https://github.com/mozilla/addons-frontend/issues/5755#issue-345204723) and the 
```html
`<link data-react-helmet="true" rel="canonical" href="https://addons.allizom.org/en-US/firefox/">
```

is present for all the pages. The above example is AMO homepage.

Here's an extension's detail page example 
![extensions detail page](https://user-images.githubusercontent.com/33448286/46733901-55202500-cc9a-11e8-8f01-93543eda0d34.png)

I understood there's a followup for paginated content so I'm marking this issue verified on AMO dev with FF62 - Win10

**Comment by rraue** [comment]
This worked, its still not affecting all pages, as Google needs time to crawl the whole site but here we can see that most pages crawled and having a parameter not changing the content are now flagged as "Alternate page with proper canonical tag" and this is how it should be:
<img width="1789" alt="screen shot 2018-10-29 at 10 55 09" src="https://user-images.githubusercontent.com/36700618/47642711-9d2fba80-db69-11e8-881f-b0e4ab8b1409.png">
