### ISSUE TITLE
Add rel attributes for pagination

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5757]
We should be using `rel="next"` and `rel="prev"` for pagination. 

See https://support.google.com/webmasters/answer/1663744?hl=en for implementation details.

See also https://www.contentkingapp.com/academy/pagination/

**Comment by muffinresearch** [comment]
@willdurand I'm not sure that matters but maybe @rraue can confirm?

**Comment by willdurand** [comment]
I agree, and that will probably be covered by #5755 or a similar issue.

**Comment by AlexandraMoga** [comment]
I've checked the pagination functionality across the site and I din't find any issues.

I can also see a  `rel` attribute in relation to the `next` and `previous` links:

![image](https://user-images.githubusercontent.com/31961530/46347833-99397700-c655-11e8-8ae3-ff74d1ada019.png)

@willdurand let me know if you need any additional testing for this. Thanks.
