### ISSUE TITLE
De-index all users with no visible activity in profile

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5759]
User profile pages are now only public for developers. 

We should only start to index user profiles if they have one of the following:

* Any add-on or theme they've developed 
* Any other public content (this might change over time, but by the looks of it reviews are not public)

There's an open question on whether adding a bio should be enough for inclusion in the index. See https://docs.google.com/document/d/1W9LOw7wgbpY6Mw5Zd4V71hJ0YahY4DTNl23MHVpG0_E/edit#heading=h.4c7acvg46cwr 

If a user profile is mostly blank it should be proactively de-indexed.

See https://support.google.com/webmasters/answer/93710?hl=en for details around possible implementation. 

Note: we should **not** use rel="canonical" if sending a signal to deindex content. See https://www.seroundtable.com/google-noindex-rel-canonical-confusion-26079.html

**Comment by muffinresearch** [comment]
@jvillalobos rightly pointed out that by design the new user-profile pages should only show up if there's content. I've checked this on -dev and it does work that way so this is already fixed.

**Comment by AlexandraMoga** [comment]
I've also tried to open a profile page for a user with no contend and indeed the page will not show up, unless you are an admin. A page not found is displayed instead.
