### ISSUE TITLE
Add locale to page titles 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5761]
We need to de-duplicate titles, adding the locale the title will help to differentiate what is essentially the same title in both place where just the locale is different. 

The locale should be appended to the end of the title in brackets e.g `This is the title (en-US)`, this garantees non duplicate titles per locale irrespective of the state of translations.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/46295112-fa067800-c59f-11e8-9f81-7dc5fa4bd045.png)
![image](https://user-images.githubusercontent.com/31961530/46295126-fe329580-c59f-11e8-86fa-f94adfc428d9.png)
![image](https://user-images.githubusercontent.com/31961530/46295135-02f74980-c5a0-11e8-9993-b64160028661.png)


@muffinresearch was  this change intended only for the new frontend or should this be done on the server side too, for the pages that are still hosted by the legacy frontend (i.e dev hub, rev tools)

**Comment by muffinresearch** [comment]
Only the new frontend. The old site's user-facing pages will be shutdown in the not too distant future.
