### ISSUE TITLE
Review all redirects and where possible use 301 instead of 302

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5762]
301 redirects send a stronger signal to crawlers that the content has been permanently moved so unless we have a good reason to use 302 we should always use a 301 redirect.

This issue is to review the cases where we are doing this in the frontend and switch to 301s where it makes sense to do so.

See also https://docs.google.com/document/d/1W9LOw7wgbpY6Mw5Zd4V71hJ0YahY4DTNl23MHVpG0_E/edit#heading=h.zhq1cfmlyxk3

**Comment by willdurand** [comment]
@muffinresearch how is this different than #5677 and #5678? (both fixed)

**Comment by muffinresearch** [comment]
#5677 was specific to locales.

**Comment by willdurand** [comment]
For QA: search redirects should be 301 now (for example, when `atype` search parameter is supplied)

**Comment by willdurand** [comment]
> @willdurand #5677 was intended to be specific to locales. If you've already covered everything in one hit, then this can be closed.

ha, that makes sense. I read this issue, then the PRD and then my brain replaced "locale" by "internal" 🤦‍♂️

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF62, Win10x64

The following search redirect uses a 301 now:

![image](https://user-images.githubusercontent.com/31961530/46355792-2be41100-c66a-11e8-8ddc-7524ea24c0bc.png)
