### ISSUE TITLE
Allow ratings to be reflected in SERPs (Search Engine Results Pages).

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5763]
We should include metadata in the details page so that crawlers can pick up the ratings for add-ons and display them in search results pages.

Since bad reviews can prevent clicks we should only do this when the rating is >= 3.5 / 5

See also https://docs.google.com/document/d/1W9LOw7wgbpY6Mw5Zd4V71hJ0YahY4DTNl23MHVpG0_E/edit#heading=h.4qv8b8sbpzob

See https://schema.org/Rating

**Comment by jvillalobos** [comment]
This may already be covered in https://github.com/mozilla/addons-frontend/issues/4129.

**Comment by muffinresearch** [comment]
Duplicate of #4129.
