### ISSUE TITLE
Make withUIState() components use persistent state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5764]
**For QA**: please test for regressions in the following scenarios:
* Edit profile, click *delete profile*. Click cancel to exit.
* Go to an add-on detail page, click a star to rate, click cancel to exit the form.
* Edit a collection and leave a note about an add-on. Cancel to exit the form.

We have `withUIState()` as of https://github.com/mozilla/addons-frontend/issues/5343 and this was first implemented as a drop-in replacement for `this.setState()`.

When you use `setState()`, you reset your component's state at construction time. This strategy does not work well with Redux's idea that a component is *reactive to a single, persistent state*. Specifically, it breaks down when you try hot module reloading (see https://github.com/mozilla/addons-frontend/pull/5652#discussion_r205609278) because every time you make a change to the component code, the component resets its state. 

What we want instead: every time you make a change to component code, it should re-render *with its existing state* (stored in Redux).

Some components that were initially designed for `setState()` will need the old behavior but new ones should get the Redux-compatible behavior.

**Comment by ioanarusiczki** [comment]
Verified this issue on AMO dev with FF61(Win10&Android 8.0).

Did not see problems for:
> Edit profile, click delete profile. Click cancel to exit.
> Edit a collection and leave a note about an add-on. Cancel to exit the form.

I filed https://github.com/mozilla/addons-frontend/issues/5846 and https://github.com/mozilla/addons-frontend/issues/5847 for what I've noticed about the second scenario:

> Go to an add-on detail page, click a star to rate, click cancel to exit the form

Also, there's the problem when the user cannot use "Esc" key or click on it's sides to exit the rating window tracked here https://github.com/mozilla/addons-frontend/issues/3691
