### ISSUE TITLE
Add <meta name="description”> for details pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5766]
Details pages should have a meta description tag that uses the summary text for the add-on.

From https://docs.google.com/document/d/1W9LOw7wgbpY6Mw5Zd4V71hJ0YahY4DTNl23MHVpG0_E/edit?ts=5b5b40e5#heading=h.aqjhycqt8ulj

The heading for details pages should be:

“Download xyz for Firefox. Description of addon.”

**Comment by AlexandraMoga** [comment]
Verified on stage with FF62, Win10x64

Add-on detail pages include now a meta description that uses the add-on summary. If there is no summary available for a particular add-on, the description will be simply "Download {add-on name} for Firefox."

```
<meta data-react-helmet="true" name="description" content="Download Tab Mix Plus for Firefox. Tab Mix Plus erweitert die Tabbed-Browsing-Funktionen von Firefox um Funktionen wie das Duplizieren von Tabs, Kontrolle über das Öffnungsverhalten von Tabs und Fenstern, die Wiederherstellung geschlossener Tabs und vieles mehr."/>
```

@willdurand I think we have one exception for lightweight themes, which had a different submission flow that didn't require a Summary. If the user wanted to add extra information, he had to use a description field in dev hub. 
In consequence, the meta description for all lwt will be "Download {theme name} for Firefox." with no extra info.

This shouldn't be a big problem though, considering that all lwt will be migrated to static themes, in which case, the lwt description will be re-interpreted as a summary.

Here is an example of a migrated lwt:

view-source:https://addons-dev.allizom.org/en-US/firefox/addon/an-autumn-reverie/

**Comment by willdurand** [comment]
> @willdurand I think we have one exception for lightweight themes, which had a different submission flow that didn't require a Summary. If the user wanted to add extra information, he had to use a description field in dev hub.
> In consequence, the meta description for all lwt will be "Download {theme name} for Firefox." with no extra info.
> 
> This shouldn't be a big problem though, considering that all lwt will be migrated to static themes, in which case, the lwt description will be re-interpreted as a summary.

@AlexandraMoga that's exactly why we don't need to be more verbose in the case of LWTs :)
