### ISSUE TITLE
Add <meta name="description”> for all other pages

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5767]
Following on from https://github.com/mozilla/addons-frontend/issues/5766 we should also add descriptions to all other relevant pages represented by the new frontend.

See also https://docs.google.com/document/d/1W9LOw7wgbpY6Mw5Zd4V71hJ0YahY4DTNl23MHVpG0_E/edit?ts=5b5b40e5#heading=h.aqjhycqt8ulj

## Pages

⚠️ all of the page below are available for Firefox and Android (Firefox for Android):

- [x] Homepage: https://addons.mozilla.org/en-US/firefox/
- [x] Landing Extensions: https://addons.mozilla.org/en-US/firefox/extensions/
- [x] Landing Themes: https://addons.mozilla.org/en-US/firefox/themes/
- [x] Search tools: https://addons.mozilla.org/en-US/firefox/search-tools/
- [x] Reviews for an add-on: https://addons.mozilla.org/en-US/firefox/addon/user-agent-string-switcher/reviews/ --> https://github.com/mozilla/addons-frontend/pull/6712
- [x] user profile of a developer or artist or both: https://addons.mozilla.org/en-US/firefox/user/Testfahrer/
- Themes / category pages (https://addons.mozilla.org/en-US/firefox/themes/):
  - [x] Abstract
  - [x] Causes
  - [x] Fashion
  - [x] Film and TV
  - [x] Firefox
  - [x] Foxkeh
  - [x] Holiday
  - [x] Music
  - [x] Nature
  - [x] Other
  - [x] Scenery
  - [x] Seasonal
  - [x] Solid
  - [x] Sports
  - [x] Websites
- [x] About page: https://addons.mozilla.org/en-US/about
- [x] Review guide: https://addons.mozilla.org/en-US/review_guide
- [x] Collection pages (we can probably rely on the description of the collection, but there might be something to add before): https://addons.mozilla.org/en-US/firefox/collections/mozilla/ad-blockers/

Firefox-only pages:

- [x] Dictionaries and Lang Packs: https://addons.mozilla.org/en-US/firefox/language-tools/
- Extensions / category pages (https://addons.mozilla.org/en-US/firefox/extensions/):
  - [x] Alerts & Updates
  - [x] Appearance
  - [x] Bookmarks
  - [x] Download Management
  - [x] Feeds, News & Blogging
  - [x] Games & Entertainment
  - [x] Language Support
  - [x] Other
  - [x] Photos, Music & Videos
  - [x] Privacy & Security
  - [x] Search Tools
  - [x] Shopping
  - [x] Social & Communication
  - [x] Tabs
  - [x] Web Development

Android-only pages:

- Extensions / category pages (https://addons.mozilla.org/en-US/android/extensions/):
  - [x] Device Features & Location
  - [x] Experimental
  - [x] Feeds, News, & Blogging
  - [x] Other
  - [x] Performance
  - [x] Photos & Media
  - [x] Security & Privacy
  - [x] Shopping
  - [x] Social Networking
  - [x] Sports & Games
  - [x] User Interface

**Comment by willdurand** [comment]
@muffinresearch does that involve editorial/UX teams? Or should we try to add some descriptions first and see how it goes? Anything is better than nothing.

**Comment by muffinresearch** [comment]
> @muffinresearch does that involve editorial/UX teams? Or should we try to add some descriptions first and see how it goes? Anything is better than nothing.

I think it would make sense to loop @MeridelW in on that.

**Comment by willdurand** [comment]
@MeridelW I updated the issue description to list the pages that need a small description (max 250 chars, ~160 chars is usually recommended).

**Comment by MeridelW** [comment]
@willdurand Thanks, Will. There are 51 pages here (as discussed, we can use some repeat descrips for categories) but I may need to get some additional help from Scott and/or intern to power through these. I'll chat with Amy during check-in this week about that.

In the meantime, I'll take a first pass at a few and see how it goes.

FYI - Raphael is on PTO this week and next and we will want his review before go-live.

**Comment by MeridelW** [comment]
@willdurand What is the deadline for draft copy, and for final copy?

**Comment by willdurand** [comment]
@MeridelW ideally by the end of this month for the final copy, but the sooner the better (obviously). What's draft copy?

I'd suggest we only have one copy and see how it goes. It takes time for Google to crawl the site and display the descriptions (if Google thinks it is better than what it can find by itself).

**Comment by willdurand** [comment]
> Draft would be a rougher, incomplete copy before then—in case you wanted to have some text to work with as you build. Sounds like it won't be necessary so let's stick with final copy end of month or sooner.

Ah oki, no need to have a draft version indeed. What I will basically do is make sure what you write is visible to Google and localizable. Let me know when you have content available for some pages, I don't need all content for all pages before starting. Thanks!

**Comment by ioanarusiczki** [comment]
I verified for the pages mentioned [above](https://github.com/mozilla/addons-frontend/issues/5767#issue-345306050) by @muffinresearch.  - on AMO dev with FF63 (Win10)

The pages contain the meta description which includes a content such as mentioned [here](https://docs.google.com/document/d/1jCkeuyCuLpcwAVIXnqpYKgqnHnV0y1OkuQ1WHUc-ftI/edit#) 

Example for the Homepage

`<meta name="description" content="Download Firefox extensions and themes. They’re like apps for your browser. They can block annoying ads, protect passwords, change browser appearance, and more." data-react-helmet="true">`

Another example with categories

![photos music videos](https://user-images.githubusercontent.com/33448286/47783573-bb352080-dd0b-11e8-8cbf-38f743a9770e.png)
