### ISSUE TITLE
1-Click YouTube Video Download (own website broken download links)

### ISSUE THREAD

**Issue by Garfield1415** [mozilla/addons-frontend#5768]
### Describe the problem and steps to reproduce it:

Searched in "Add-ons" for "youtube download" 
clicked on the description "1-Click YouTube Video Download" which took me to this page =
https://addons.mozilla.org/en-US/firefox/addon/1-click-youtube-video-downl/?src=search
after the Add-on installed I got a webpage advertising there own product but both of the download links don't work!

### What happened? 

installed the add-on -> 

https://addons.mozilla.org/en-US/firefox/addon/1-click-youtube-video-downl/?src=search

after it installed another window opened, advertising this addon ->

http://www.clickvideodownload.com/getting_started.php

### What did you expect to happen? the addon to install and that was all
after the webpage loaded, I clicked the "Download" link and then clicked on 

"Download The Latest Version) -> 
https://addons.mozilla.org/en-US/firefox/addon/1-click-youtube-video-download/

and the tried the following 

"Download Previous Versions" -> 
https://addons.mozilla.org/en-US/firefox/addon/1-click-youtube-video-download/versions/

### Anything else we should know?

1-click website that popped up 
![image](https://user-images.githubusercontent.com/33879675/43338352-ffe5801e-91cd-11e8-922d-db374c414f12.png)
dowload webpage 
![image](https://user-images.githubusercontent.com/33879675/43338427-365fb038-91ce-11e8-91e4-dc1e0a16cd57.png)
![download latest version](https://user-images.githubusercontent.com/33879675/43338804-6e29d754-91cf-11e8-8a09-329cc16fca10.jpg)
![download previou version](https://user-images.githubusercontent.com/33879675/43338805-6e432fa6-91cf-11e8-89d0-9bdf16aeca1f.jpg)

**Comment by jvillalobos** [comment]
Please contact the developer about any issues with the website. It's up to them to keep their links up to date and provide an adequate first-run experience.
