### ISSUE TITLE
Addons that have the All Rights Reserved license are now showing up broken 

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5772]
### Describe the problem and steps to reproduce it:

Addons that have the "All Rights Reserved" license are showing up broken 

eg:
https://addons-dev.allizom.org/en-US/firefox/addon/wide-zmeurica/
https://addons-dev.allizom.org/en-US/firefox/addon/source/
https://addons-dev.allizom.org/en-US/firefox/addon/rm-theme-new-sizes/

### What happened?

I think this is related to the recent Router changes and Link being a little bit more strict.

### What did you expect to happen?

Pages would appear

**Comment by muffinresearch** [comment]
Here's the Sentry log: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/4503725/

`Invariant Violation: You must specify the "to" property`

**Comment by muffinresearch** [comment]
Bumping this up to a p1 since it needs to be fixed for the next release.
