### ISSUE TITLE
A new locale (az) has been added

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5783]
We need to update the config (allowed locales) to take this new locale into account.

**Comment by willdurand** [comment]
For QA: we should see a new language (http://www.localeplanet.com/icu/az/index.html).

**Comment by vcarciu** [comment]
Verified as fixed : 
![azer](https://user-images.githubusercontent.com/1583842/43453539-1309fb32-94c3-11e8-91a0-e27758d10c4e.png)
