### ISSUE TITLE
Don't list developer replies as user/developer reviews on user page

### ISSUE THREAD

**Issue by rctgamer3** [mozilla/addons-frontend#5788]
On my own profile page, several developer replies to user reviews are listed, while they weren't in the old design.

These show up as zero-star-reviews on the user page.

https://addons.mozilla.org/user/560520

**Comment by willdurand** [comment]
Hello, your reviews are only listed for yourself, no one else can see them on your profile page.

We are aware of the issue though, please see: #5684
