### ISSUE TITLE
Change "Add to Firefox" button colour

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#5789]
Currently, the "Add to Firefox" is #0a84ff (blue 50), it should be #0060df (blue 60). @willdurand, this might tie into the new button you're building?

**Comment by willdurand** [comment]
@pwalm I think all "action" buttons use `$blue-50`, see: https://github.com/mozilla/addons-frontend/blob/85cd96d023c24045c2aa7b43cfa172a28a159067/src/ui/components/Button/styles.scss#L142. `-60` is use for active state.

Do you want to update all button colors? Or only the "add to FF" needs this change?

Are you sure about and priority p1? This issue looks pretty harmless.

**Comment by pwalm** [comment]
Only the "Add to FF" button. It needs to be a shade darker to stand out as the main CTA.

And I'll bump it down to P2, but that's as low as I'll go ;)

**Comment by willdurand** [comment]
Thanks.

> Only the "Add to FF" button. It needs to be a shade darker to stand out as the main CTA.

what should be the colors for the active and hover states? Is this CTA type defined in Photon?

**Comment by willdurand** [comment]
For QA: all "action" buttons should get the update (i.e. the blue buttons are more blue than before, if that makes sense).

**Comment by vcarciu** [comment]
Verified as fixed: 
![buttoncolor](https://user-images.githubusercontent.com/1583842/43520604-eef42a90-959b-11e8-8151-5d72714da919.png)

**Comment by willdurand** [comment]
@vcarciu no label? :bowtie:

**Comment by vcarciu** [comment]
@willdurand : my bad. Label added 😄
