### ISSUE TITLE
Restart UI doesn't persist when add-on is in a install pending restart state

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#579]
It appears that if an add-on is in a state that requires a restart, refreshing the page the `getAddonByID` call is unable to tell us that restart is required because `getAddonByID` doesn't find the addon when in an uninstalling state pending restart.

As a result of this any restart UI is removed and the state of the Add-on in the disco pane does not match the state of the Add-on in about:addons#Extensions.

_Currently you can see this with `Video DownloadHelper` on -dev since it's out of date and does require a restart currently._ 
## STR:
- Install `Video DownloadHelper`
- See the requires restart UI
- Refresh the disco pane
### What should happen:
- We should see the requires restart UI still
### What happens:

The addon looks removed (even when it isn't yet):

![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/15959762/348fe870-2ef4-11e6-82a5-8aaf974509dc.png)

The about:addons#Extensions ui looks like this (This survives a refresh):

![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/15959732/13a98a26-2ef4-11e6-9069-25cfc5ba939e.png)

**Comment by muffinresearch** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1279472

**Comment by willdurand** [comment]
Marking as wontfix and closing since it is about to be removed in https://github.com/mozilla/addons-frontend/issues/2135.
