### ISSUE TITLE
Upgrade uglify to cope with es6 code

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5796]
The uglify we are currently using cannot handle non-es5 code. 

To fix this we will need to use uglify-es in place of uglify. This is only a problem if a npm package contains non-transpiled code.

We previously made this change in https://github.com/mozilla/addons-frontend/pull/4868 but it had to be reverted because webpack produced hashes that were the same even though the content of the files changed.

We'll need to understand why this occurred and we might need to make a change to ensure that hashes are different - a provision for that is here if we need it as a last resort:

https://github.com/mozilla/addons-frontend/blob/bcae92c4ce3bef0cdbfdfec708d7c667d998f139/bin/build-locales#L83

**Comment by willdurand** [comment]
Do you recall the STR? I tried the latest version of `uglifyjs-webpack-plugin` and I end up with different hashes for the main bundle (`amo-<hash>.js`). I did not change the locales, so it keeps the same hashes but I suppose there is something related to the locales.

**Comment by willdurand** [comment]
@muffinresearch Do you recall the STR? I tried the latest version of `uglifyjs-webpack-plugin` and I end up with different hashes for the main bundle (`amo-<hash>.js`). I did not change the locales, so it keeps the same hashes but I suppose there is something related to the locales.

**Comment by muffinresearch** [comment]
@willdurand it's completely possible it's been fixed in some way since the issues we had too. 

With the new uglify in place building a production build resulted in files with the same hashes but different content.

**Comment by muffinresearch** [comment]
QA: Notes: since this patch affects all JS code please keep an eye out for any JS breakage on the new frontend once this code lands.

**Comment by ioanarusiczki** [comment]
@muffinresearch We'll perform the release testing for this milestone and if problems are noticed we'll update this issue.
