### ISSUE TITLE
Restart UI doesn't persist when add-on is in uninstall pending restart state

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#580]
Related to https://github.com/mozilla/addons-frontend/issues/579 

When an uninstall requiress a restart and you refresh the page when we introspect the add-on state, `getAddonById` returns the Add-on but it doesn't provide a `needsRestart` hint so the restart UI is not shown.

_Currently you can see this with `Video DownloadHelper` on -dev since it's out of date and does require a restart currently._ 
## STR:
- Install `Video DownloadHelper`
- Restart
- Click to uninstall `Video DownloadHelper`
- Refresh the disco pane page
### What should happen:
- We should see the requires restart 
### What happens:

The addon appears to be installed, the needs restart state is not shown
![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/15960204/a3c28de0-2ef6-11e6-9e67-87eb0b67e3a8.png)

The about:addons#Extensions ui looks like this (This survives a refresh):

![add-ons_manager](https://cloud.githubusercontent.com/assets/1514/15960172/8ad2398e-2ef6-11e6-84f2-b2709300ea01.png)

**Comment by muffinresearch** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1279472

**Comment by willdurand** [comment]
Marking as wontfix since it is about to be removed in https://github.com/mozilla/addons-frontend/issues/2135.
