### ISSUE TITLE
Remove the static theme flag after has been verified in PROD

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#5802]
### Describe the problem and steps to reproduce it:

This should come after #5799 and it has been verified as good in prod. We should remove this enable flag altogether

**Comment by willdurand** [comment]
@rebmullin I think we are good for that, no?

**Comment by ioanarusiczki** [comment]
Static themes are displayed on their detail pages and in search results, in Themes Tab and AMO homepage. Verified fixed on AMO dev - FF62 (Win10)

AMO homepage
![on homepage static themes](https://user-images.githubusercontent.com/33448286/46941414-bb7abe00-d073-11e8-888e-2667b6e457aa.png)

Theme tab
![themes tab](https://user-images.githubusercontent.com/33448286/46941422-c0d80880-d073-11e8-9c2e-632813baf79a.png)

Search results
![displayed in search results](https://user-images.githubusercontent.com/33448286/46941446-ce8d8e00-d073-11e8-9280-55c79073dfbd.png)
