### ISSUE TITLE
9 August homepage content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#5808]
For the **9 August** push, please update the homepage to reflect the programming detailed [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#).

@muffinresearch

**Comment by ioanarusiczki** [comment]
Verified the hero banners, presence of the new added add-ons, the collection shelves and "See more" links on AMO dev with FF61(Win10 and Android 8.0).
Full validation will be made on AMO prod.

**Comment by madalincm** [comment]
Verified as fixed in FF61 win10 x64 in amo-prod.
Marking bug as verified fixed.
