### ISSUE TITLE
Feedly save to board not working

### ISSUE THREAD

**Issue by newza-fullmetal** [mozilla/addons-frontend#5809]
### Describe the problem and steps to reproduce it:

I need to install the extension : Feedkly save to board on firefox but the link from the official website is not working and no other extension exists

### What happened?
From this page : [Feedly blog](https://blog.feedly.com/5-ways-to-save-a-story/)
I got a link to [here](https://addons.mozilla.org/en-US/firefox/addon/save-to-knowledge-board-feedly/)

### Anything else we should know?
According to the feedly team it should be available. 

Thank you : ) 

Newza

**Comment by wagnerand** [comment]
See #5731.
