### ISSUE TITLE
Only run Snyk when the secret variables are available on Travis CI

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5819]
For security reasons, the secret environment variables are not exposed when a PR is submitted from a fork.

We should only run the snyk job when the secret vars are available, and add a note in the doc to push to this repo when fixing a snyk issue.

**Comment by kumar303** [comment]
I bumping priority on this since all PRs (created from forks) will fail.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label qa:not needed?
Thanks

**Comment by willdurand** [comment]
added qa:not needed
