### ISSUE TITLE
Adding a "<" before an add-on name will cause layout issues on  add-on details page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5828]
STR:

1. Log in to Developer Hub
2. Navigate to Manage my Submissions and select one of your listed add-ons to view its edit information page
3. Modify the Name of your add-on by adding a "<" right at the beginning
4. Save the changes and click on View listing to see the results on the frontend

Actual result:
The name of the add-on is not is not displayed and the author name has a different format

Expected results:
The frontend should render the add-on name as plain text to avoid any layout issues 

Notes:
- reproduced on all AMO servers with FF61, Win10x64

[1] DevHub

![image](https://user-images.githubusercontent.com/31961530/43587373-c41a0b64-9672-11e8-86cd-815238e93113.png)

[2] Frontend
![image](https://user-images.githubusercontent.com/31961530/43587398-d0cd63a6-9672-11e8-9cf3-311036b328a5.png)

**Comment by kumar303** [comment]
Thanks for the report. Here's the listing: https://addons.allizom.org/en-US/firefox/addon/devhub-release-02081/

I took a quick look to make sure there isn't any XSS potential here; I don't see any potential.

**Comment by muffinresearch** [comment]
I suspect this is being removed by DOMPurify.

**Comment by willdurand** [comment]
@AlexandraMoga is this still an issue?

**Comment by AlexandraMoga** [comment]
It seems fixed:

![image](https://user-images.githubusercontent.com/31961530/60717655-19fe0a00-9f2b-11e9-903f-dd0b30b5f314.png)

**Comment by willdurand** [comment]
\o/
