### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by gggustafson** [mozilla/addons-frontend#5830]
On the page 

https://support.mozilla.org/en-US/questions/756226#answer-107517

the link 

Incredible Bookmarks: https://addons.mozilla.org/firefox/addon/50722

is broken.

**Comment by muffinresearch** [comment]
We are unable to provide support for individual add-ons. In this case the add-on is no-longer available because it's been disabled by the developer.

**Comment by caitmuenster** [comment]
cc @MeridelW -- this is an example of users finding outdated SUMO content.
