### ISSUE TITLE
Plugin "3P Request Blocker" is no more available on Firefox Add-ons website

### ISSUE THREAD

**Issue by christian-momon** [mozilla/addons-frontend#5837]
### Describe the problem and steps to reproduce it:
I use 3P Request Blocker since february, it's a wonderful plugin. Now, I want install it on another computer and I can't find it anymore.

A previous link was: https://addons.mozilla.org/en-US/firefox/addon/3p-request-blocker/reviews/

### What happened?
The previous link returns "Page not found" and there is no result on the Firefox Add-ons website search.

How find it again? Why there is no information about its remove?

**Comment by jvillalobos** [comment]
It looks like the add-on was removed by the developers. You'll need to contact them for more information.
