### ISSUE TITLE
Can't access my profile to edit it.

### ISSUE THREAD

**Issue by emerysteele** [mozilla/addons-frontend#5842]
Can't view my profile or edit my profile on the addons.mozilla.org website. I login, hover over my username, click on Edit My Profile. Then it redirects to an error that says 'Page Not Found.'

The 'View My Profile' is: https://addons.mozilla.org/en-US/firefox/user/emerysteele-1364597629.54/
The 'Edit My Profile' url is: https://addons.mozilla.org/en-US/firefox/users/edit

![capture](https://user-images.githubusercontent.com/1169001/43683391-f25eec16-9847-11e8-90f9-83c40554d96d.PNG)

**Comment by willdurand** [comment]
@diox this looks like an API issue:

```
$ http 'https://addons.mozilla.org/api/v3/accounts/account/7841944/'

{
    "id": 7841944,
    ...
    "username": "emerysteele-1364597629.54"
}
```

```
$ http 'https://addons.mozilla.org/api/v3/accounts/account/emerysteele-1364597629.54/'

{
    "detail": "Not found."
}
```

**Comment by diox** [comment]
It's because the username contains a period. Need to double-check if that's supposed to happen, but looks like the API doesn't expect that.

**Comment by willdurand** [comment]
@diox added P3 here but it is probably worth moving to addons-server and see if we should not raise the priority. About 86k users have a username containing a period: https://sql.telemetry.mozilla.org/queries/58127.

**Comment by diox** [comment]
Periods are not currently allowed in usernames, we return a validation error.

I'll relax the API pattern to not cause a 404. I guess it was allowed a long time ago, or maybe on some users migrated from somewhere else... Affected users will be able to load their profile again, but they'll have to modify their username to save changes.

**Comment by AlexandraMoga** [comment]
This has been verified for AMO -dev in https://github.com/mozilla/addons-server/issues/8607
