### ISSUE TITLE
"See more" links are not working from "Explore all categories"  on Android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5845]
STR:
1. Load AMO dev and go to Theme tab and click the Explore all categories link.
2. Choose a random category then click one of the "See more" blue links.

Actual result:
A red error message with no results is displayed.

Expected result:
A list of themes are displayed for the chosen category.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF61(Android 8.0) with all categories (and any random "See more" link tapped).
It is not reproducible on Windows and iOS platforms.

![open categories](https://user-images.githubusercontent.com/33448286/43718015-0209bfba-9992-11e8-8740-2689c40d4a7c.png)

**Comment by willdurand** [comment]
ah, good catch! Since static themes are not supported on Android, we should not have a filter `type=statictheme,persona` on Android.

**Comment by ioanarusiczki** [comment]
I verified it on AMO dev with FF61(Android 8.0) and it is no longer reproducible.
On AMO stage - it is still reproducible so I will re-check this issue.
