### ISSUE TITLE
A rating should no longer be displayed with yellow if the user cancels it

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5846]
STR:
1. Load AMO dev and go to the detail page of an add-on.
2. Click on a star and after the review window is opened click outside the text box to cancel the rating.
3. Observe the screen.

Actual result:
The rating stars are all empty.

Expected result:
The previous rating is still visible - the stars remained yellow.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF61(Win10 & Android 8.0).
This issue is reproducible on both : add-on detail page and the reviews page.

![yellow rating](https://user-images.githubusercontent.com/33448286/43718674-00350242-9994-11e8-92d8-967cecae8810.gif)

**Comment by kumar303** [comment]
This is expected behavior. See https://github.com/mozilla/addons-frontend/issues/5847#issuecomment-411138892 for an explanation.
