### ISSUE TITLE
After the user cancels the rating but then refreshes the page the number of ratings increases

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5847]
STR:
1. Load AMO dev and go to an add-on/theme's detail page
2. Try to rate it by clicking on one of the stars (before observe the numbers of ratings displayed on the upper right side of the screen)
3. Don't click the submit review button and instead click outside the box to cancel your rating.
4. Refresh the page
5. Observe the number of ratings displayed again

Actual result:
Number of the ratings increases with one.

Expected results:
The number of ratings did not change because the stars remained yellow-> looks like an empty review attempt.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF61(Win10 and Android 8.0).
This issue is related with https://github.com/mozilla/addons-frontend/issues/5846

![refresh page after canceling the rating](https://user-images.githubusercontent.com/33448286/43719095-6501da00-9995-11e8-973f-c4a479313d70.gif)

**Comment by kumar303** [comment]
This is the expected behavior because selecting a star does submit a rating (just one without any text).

I think this will be more clear after https://github.com/mozilla/addons-frontend/issues/5519
