### ISSUE TITLE
Rename `reviews` endpoint to `ratings`

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5850]
The `reviews` endpoint has been renamed to [`ratings`](http://addons-server.readthedocs.io/en/latest/topics/api/ratings.html#). The old one still works but we should update our API calls everywhere.

**For QA**: Please test for regressions in the following scenarios:
- creating / editing a review
- viewing star ratings on add-on detail page
- viewing all reviews for an add-on

**Comment by bobsilverberg** [comment]
I believe this was fixed via https://github.com/mozilla/addons-frontend/pull/6420. Marking as assigned to @willdurand as he landed the patch that fixed it. Marking as "qa: not needed" because it will be been verified when #5527 is verified.
