### ISSUE TITLE
Synchronize font sizes with Sketch UI mock

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5866]
The standard font sizes we use across the app do not match the Sketch UI mock. They are mostly off by one or two pixels here and there.

See:

https://github.com/mozilla/addons-frontend/blob/f3efa1158a7e0b9f36d36e25b378bd4abb19a827/src/core/css/inc/vars.scss#L21-L27

**Comment by willdurand** [comment]
Given the upcoming redesign, this won't be needed.
