### ISSUE TITLE
The dev server stops responding after a syntax error

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5886]
### Describe the problem and steps to reproduce it:

- Start a dev server
- Visit any page
- Create a syntax error in the code (for example: unterminated JSX)
- Reload the page in the browser

### What happened?

The server no longer responds to requests

### What did you expect to happen?

The server should be able to respond after the syntax error is fixed.

### Anything else we should know?

Auto-reloading was added to the server in https://github.com/mozilla/addons-frontend/issues/5530

**Comment by willdurand** [comment]
I think the issue comes from [concurrently](https://www.npmjs.com/package/concurrently) and the `--kill-others` option that is passed. I think we should pass something like `--kill-others-on-fail` or no option at all if we can still exit all processes.
