### ISSUE TITLE
Sort add-on section is displayed on the Create a collection from

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5893]
STR:

1. Log in to AMO -dev
2. Select View My Collections from the user menu
3. Click on Create a collection
4. Observe the fileds available in the create a collection form - https://addons.allizom.org/en-US/firefox/collections/add/

Actual result:
The Sort add-ons section is present, even if the collection doesn't have any add-ons included yet

Expected result:
The "Sort add-ons' section should be hidden in the create a collection form

Notes:
- reproduced on all AMO servers with FF61, Win10x64
- this was fixed once in https://github.com/mozilla/addons-frontend/issues/5628 but it might have been reintroduced at some point (maybe by https://github.com/mozilla/addons-frontend/pull/5676)
- this time, the section is present only in the create collection form, when the user is logged in

![image](https://user-images.githubusercontent.com/31961530/43892566-f6ed87ac-9bd4-11e8-8a5c-83ba1c24540e.png)

**Comment by xu3u4** [comment]
Hello,
I'd like to take this issue!

**Comment by willdurand** [comment]
Thanks @xu3u4

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO - stage with FF63, Win10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/49219211-483aca80-f3db-11e8-84aa-7b81020448cc.png)
