### ISSUE TITLE
Verify that mozAddonManager is MITM-proof

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#5899]
See: #3867 – everything is described in this issue, don't skip it!

---

With the new `AMInstallButton`, we use `mozAddonManager` and we should look at #3867 and see if `mozAddonManager` is affected or not. If it is, then we'll have to see how we can pass hashes to `mozAddonManager` or look for other ways to fix this issue.

If `mozAddonManager` is not affected, then perfect! Nothing to do.

**Comment by muffinresearch** [comment]
Hah well done on digging up that old issue. According to my notes on that issue mozAddonManager should be ok but it's definitely worth double checking 👍

**Comment by willdurand** [comment]
I tried Charles Proxy locally and enabled the SSL proxy on the -dev CDN. I can see the requests to download add-ons passing though Charles (and could potentially abort the requests so I believe my setup is correct).

I was able to install add-ons, so I think we are good here.

For QA: please look at the STR in https://github.com/mozilla/addons-frontend/issues/3867 to test in -dev. Both AMO and Disco Pane should be tested as the new install button (`AMInstallButton`) is used on both apps.
