### ISSUE TITLE
Dictionary available in API endpoint but not available in language-tools page

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-frontend#5904]
The API endpoint includes a dictionary for az-IR
https://addons.mozilla.org/api/v3/addons/language-tools/?app=firefox&type=dictionary

But this dictionary is not displayed in the language-tools page, which is supposedly fed by the same API
https://addons.mozilla.org/firefox/language-tools/

I assumed this was a "feature", with the language-tools page being manually curated by editors and not generated from that API, but it doesn't seem to be the case.

**Comment by willdurand** [comment]
Hi @flodolo, I think that's because there is a mismatch in our code. What is the difference between `az` and `az-IR`. I see that the dictionary has `az-IR` as target language, but we do not recognize this locale I think.

**Comment by eviljeff** [comment]
`az-IR` is the Iranian variant of `az` (Azerbaijani).  Like `de` & `de-AT`, `pt-PT` & `pt-BR`, etc.

**Comment by willdurand** [comment]
This looks fixed.
