### ISSUE TITLE
"Save collection" button won't appear active promptly after the Name or Description fields are edited

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5908]
This issue is reproducible only when the user creates a collection from an add-ons detail page.

STR:
1. Load AMO dev and login then go to an add-on's detail page.
2. Create a collection using the Add to collection section.
3. On the second screen (after collection was created) add some chars into the Name or Description field.
4. Observe the Save collection button.

Actual result: 
Button is greyed out. 

Expected result:
Save button collection becomes active - dark blue.

Notes:
This issue is only reproducible with the above scenario on AMO dev and AMO stage with FF61 (Win10).
When chars are deleted the Save Button will become active only after moving into the next field using Tab key or the mouse.
These above are not reproducible when user creates the collections and then edits the second screen from View my collections.
It is not reproducible when the Custom URL field is edited.

Save collection button stays greyed out
![bugsavebutton](https://user-images.githubusercontent.com/33448286/43951224-41384bf0-9c9b-11e8-8d7b-bc4783d9e8c6.gif)

Not reproducible from View my collections - Create a collection
![view my collection](https://user-images.githubusercontent.com/33448286/43951246-560b7926-9c9b-11e8-8e31-a95e1a42f344.gif)

**Comment by ioanarusiczki** [comment]
I filed the related issue on Android platform here https://github.com/mozilla/addons-frontend/issues/5906

**Comment by bobsilverberg** [comment]
@ioanarusiczki As with #5988, I am not able to reproduce this on OS X. A few changes have landed to the Edit Collection screen, which might have fixed this, but I'm doubtful of that. Can you please check again, and, if possible, see if the issue only exists on Windows?
