### ISSUE TITLE
Change title of detail pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#5914]
For SEO purposes, we want the title of listing pages to be: "$NAME - Get this $TYPE for 🦊 Firefox (locale)".  $TYPE should be "extension", "theme", "dictionary", etc.

Adding the locale is covered in #5761.

**Comment by willdurand** [comment]
@jvillalobos so we want the fox emoji and the locale inside parentheses?

**Comment by willdurand** [comment]
I jus/t read about a potential A/B experiment for the fox emoji, is that still a thing

**Comment by jvillalobos** [comment]
Yes, adding the emoji and the locale are the changes requested here. I don't think we need to A/B test this (it would be really hard to measure the outcome anyway, given the unpredictability of search engine indexing).

**Comment by AlexandraMoga** [comment]
Verified on AMO stage with FF62, Win10x64

We have the following page titles:

[Extensions]
![image](https://user-images.githubusercontent.com/31961530/46403034-0dcded80-c70a-11e8-9bf9-d9f3fe2b8d3a.png)

[Themes - lwt and static]
![image](https://user-images.githubusercontent.com/31961530/46403051-17efec00-c70a-11e8-8f1f-694a4fed7def.png)

[Dictionaries]
![image](https://user-images.githubusercontent.com/31961530/46403067-22aa8100-c70a-11e8-9b0b-fc59323f8274.png)

[Language packs]
![image](https://user-images.githubusercontent.com/31961530/46403079-2c33e900-c70a-11e8-809c-8baa54697656.png)


@willdurand shouldn't there be a specific type for search tools as well? Currently, the title says simply 'Add-on'

[Search Tools]
![image](https://user-images.githubusercontent.com/31961530/46403088-35bd5100-c70a-11e8-8496-5fb163fd87ae.png)

**Comment by willdurand** [comment]
> @willdurand shouldn't there be a specific type for search tools as well? Currently, the title says simply 'Add-on'

@AlexandraMoga it could be nice indeed, thanks. Could you file an issue for this type?

**Comment by AlexandraMoga** [comment]
Filed #6509 as a follow up.

Marking this issue as verified fixed.
