### ISSUE TITLE
A browser tab is opened to http://127.0.0.1:3010/ when running yarn amo:dev

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5922]
When I run `yarn amo:dev` locally a browser tab is opened to `http://127.0.0.1:3010/`, which has the window title of "pino-devtools". This page just shows the following message:

<img width="662" alt="screenshot 2018-08-13 13 33 48" src="https://user-images.githubusercontent.com/142755/44047821-8a320e7c-9efd-11e8-8105-d48cf0361a91.png">

I'm not sure why this is required, and if it is not I suggest that it would be nice to find a way to disable this automatic opening of a browser tab to this page.

**Comment by kumar303** [comment]
Welcome back! 😄 

This was added in https://github.com/mozilla/addons-frontend/issues/4041 but a new feature is coming where you can see the server logs in the page of the AMO dev site itself. I think this will be much more useful.
