### ISSUE TITLE
When star breakdown is clicked, show reviews sorted by star ratings

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#5923]
When I click on one of the star rating breakdowns on a detail page, I expect to be taken to a reviews page that is sorted by the specific star rating I clicked. For example, clicking on the 5-star row should take me to the review page where 5-star reviews are shown first. ![breakdown](https://i.imgur.com/akvRHwn.png)

**Comment by jvillalobos** [comment]
I'm thinking this could be implemented as a filter in the All Reviews page, so clicking on the 3 star line should take you to that page with the 3 star filter applied.

**Comment by kumar303** [comment]
Yes! I was thinking the same thing. @pwalm has already started to think about a dropdown menu that can be used to filter reviews by helpful / not helpful (which isn't implemented yet). We could also show items in that that dropdown like *Show only one star ratings* or *Sort by rating* in addition to making the graph clickable. I think it may not be obvious to *everyone* that they can click on the star graph.

<img width="883" alt="screenshot 2018-08-15 11 26 32" src="https://user-images.githubusercontent.com/55398/44159838-3c223b80-a07e-11e8-931e-36ddd38321de.png">

**Comment by pwalm** [comment]
Here's how Amazon does it:
<img width="970" alt="screen shot 2018-11-28 at 2 57 55 pm" src="https://user-images.githubusercontent.com/6797635/49187996-1adc1700-f31e-11e8-889a-5667b866cc67.png">
We could add a new drop down that is for # of stars (or get real funky and add all sorts of filters at the top)

**Comment by atsay** [comment]
Let's keep the scope of this realistic and do these two things: 1) underline the numbers to the left and right of each star so it's obvious they're clickable 2) link to the all reviews page, sorted (or filtered) by the number of stars corresponding to what the user clicked.

We need to decide whether we'll sort or filter the number of stars, or have both options.

**Comment by kumar303** [comment]
> We need to decide whether we'll sort or filter the number of stars, or have both options.

Yeah, I agree that the dropdown could be added in a follow-up patch. I'll start this first pass as just clickable stars / numbers that filter reviews.

**Comment by atsay** [comment]
Or just have one drop-down for sorting or filtering star ratings, since that is the only attribute we have right now. But agree it can be done later if necessary.

**Comment by ioanarusiczki** [comment]
I tested on AMO dev with FF63 (Win10).  I filed https://github.com/mozilla/addons-frontend/issues/7216

These are already filed https://github.com/mozilla/addons-frontend/issues/7200 and https://github.com/mozilla/addons-frontend/issues/7206.
