### ISSUE TITLE
Move rating stars to the top in the add-on review listing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5924]
### Describe the problem and steps to reproduce it:

Go to any add-on review listing page, such as https://addons-dev.allizom.org/en-US/firefox/addon/feed-sidebar/reviews/

### What happened?

The star ratings are at the bottom.

### What did you expect to happen?

The UX mock has moved them to the top. Example:

<img width="882" alt="screenshot 2018-08-13 15 18 05" src="https://user-images.githubusercontent.com/55398/44055819-1cfcb104-9f0c-11e8-902e-d1d6372a0da8.png">

### Anything else we should know?

We are not yet ready to show the helpful / not helpful buttons. See https://github.com/mozilla/addons-frontend/issues/5360

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10&Android 8.0)
![ratings moved](https://user-images.githubusercontent.com/33448286/44713121-19027d80-aabb-11e8-8e78-5d458f2249ec.png)
