### ISSUE TITLE
Use configurable SVGs for rating stars

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5925]
We show rating stars in four different colors now and there is a custom SVG for each one. Let's move to an inline SVG so that we can apply colors with CSS. As an example, it could be implemented like [`IconXMark`](https://github.com/mozilla/addons-frontend/tree/405b2ca6892dd79af2278d9d557984cbdbf31eeb/src/ui/components/IconXMark).

**For QA**: please make sure there are no visual regressions for star ratings.

**Comment by willdurand** [comment]
I wish we could use `mask`, but support is not super good.

**Comment by ioanarusiczki** [comment]
I did not find visual regressions on AMO dev with FF64(Win10).

**Comment by AlexandraMoga** [comment]
Verifed on AMO stage with FF64, WIn10x64 and Android 8.0

There were some visual issues noticed, for which I've logged #7358 and #7359

**Comment by willdurand** [comment]
Due to the number of regressions and the fact that I am not sure how to come up with a patch to fix them all, I am going to revert the patch.

**Comment by kumar303** [comment]
Sorry about the revert, @rebmullin. I took a quick look at your patch and I think everything was on the right track. It's just missing some of the styles for all various states in https://github.com/mozilla/addons-frontend/pull/7263/files#diff-496f5bb7b2e875e2b48a2046477aeced (these styles grew organically so they are very complex).

I suggest beginning by making a story book for all possible rating star states (in a new issue). This will help serve as a visual regression test for when you resurrect the patch and switch everything to SVG. Without a story book it will be hard to do a visual check of all possible states, some of which require you to own a review or to be signed in.

**Comment by rebmullin** [comment]
yeh @kumar303 I was actually thinking the same..if we had had a story and percy/visual regression tool set up, we would have caught this at PR time. I do have a PR already started to get this reinstated but I can definitely do a story for this now to help make sure there are no other regressions.

**Comment by ioanarusiczki** [comment]
@kumar303 @rebmullin I did not finish testing but so far I've noticed a regression again and filed it here https://github.com/mozilla/addons-frontend/issues/7581

**Comment by ioanarusiczki** [comment]
@kumar303 @rebmullin I verified for regressions on the detail pages, all reviews page and user profile page with FF65 (Win10 & Android 8.0). Hovered over add-ons on the homepage, in categories, other popular extensions and more extensions by section from the detail pages and I did not see any regressions. So, the last week's filed issues are not reproducible except https://github.com/mozilla/addons-frontend/issues/7581

**Comment by kumar303** [comment]
Thanks. I think I know what the problem is for #7581
