### ISSUE TITLE
Button's state is "Enable" instead of "Add to Firefox" after clicking "Remove" from Add-on manager

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5929]
STR:
1. Load AMO dev and go to an add-ons detail page. 
2. Click the "Add to Firefox" button. 
3. Open a new tab and from add-on manager click the "Remove" button for the installed add-on.
4. Go back to the add-ons page and observe the state of the button, refresh page.

Actual result:
The button has the "+Enable" state. 

Expected result:
The button has the "+Add to Firefox" and the add-on can be re-installed.

Notes:
This issue is reproducible with FF63 (Win10).  

![enable state instead of add to firefox](https://user-images.githubusercontent.com/33448286/44095260-090ec846-9fe1-11e8-93ef-4282b5e0312a.gif)

**Comment by suhailsinghbains** [comment]
Hi, I guess this issue has been resolved by the latest closed PR, otherwise would love to work on it.

**Comment by willdurand** [comment]
@suhailsinghbains I was not aware of this issue, you can give it a try but I'll probably try to fix it by next Tuesday :)

**Comment by suhailsinghbains** [comment]
Okay, cool, I'll give this a try.

**Comment by willdurand** [comment]
Looks like we only receive a `UNINSTALLING` event but no `UNINSTALLED` event after.

**Comment by willdurand** [comment]
After page reload, the status of the add-on is `DISABLED` and not `UNINSTALLED`.

**Comment by willdurand** [comment]
Oh I see, if you close `about:addon`, then the state becomes correct. I wonder why though, but I don't think this is a bug we can fix.

**Comment by willdurand** [comment]
ok so that is related to the undo feature in `about:addons`. It does not remove the add-on until the page is closed to allow a user to undo their action (thus re-installing the add-on).

**Comment by willdurand** [comment]
Here is a patch to allow re-installing the add-on _via_ the "Enable" button:

```diff
diff --git a/src/core/components/AMInstallButton/index.js b/src/core/components/AMInstallButton/index.js
index a037c350b..de361186f 100644
--- a/src/core/components/AMInstallButton/index.js
+++ b/src/core/components/AMInstallButton/index.js
@@ -156,13 +156,22 @@ export class AMInstallButtonBase extends React.Component<InternalProps> {
     return false;
   };
 
-  enableAddon = (event: SyntheticEvent<HTMLAnchorElement>) => {
-    const { enable } = this.props;
+  enableAddon = async (event: SyntheticEvent<HTMLAnchorElement>) => {
+    const { enable, install, isAddonEnabled } = this.props;
 
     event.preventDefault();
     event.stopPropagation();
 
-    enable();
+    const isEnabled = await isAddonEnabled();
+
+    // When a user removes an add-on from about:addons (and keep this page
+    // open), the add-on's status is DISABLED, but the add-on is enabled,
+    // because of the "undo" feature. In this case, we re-install the add-on.
+    if (isEnabled) {
+      await install();
+    } else {
+      await enable();
+    }
 
     return false;
   };
```

**Comment by willdurand** [comment]
See also: https://bugzilla.mozilla.org/show_bug.cgi?id=1477155#c1

**Comment by willdurand** [comment]
I found another to partially fix this issue.

**Comment by suhailsinghbains** [comment]
I saw the PR, understood a bit, that you added another state that is possible that it is INACTAIVE.

**Comment by willdurand** [comment]
For QA: that only works for add-ons that are extensions, it won't work for themes (static or lightweight).

**Comment by ioanarusiczki** [comment]
@willdurand I tested this issue on AMO dev with FF63 (Win10)
1. The add-ons detail page will only show the button "+Add to Firefox" after refreshing the page. Until then it remains in the loading state.  I will file a separate issue to track it.

![continuous loading state plus refresh works](https://user-images.githubusercontent.com/33448286/44721216-d8fac500-aad1-11e8-8f5b-0a35ef41de9e.gif)

2.If we close this issue now then I must file a separate one for themes/static themes until the fix of https://bugzilla.mozilla.org/show_bug.cgi?id=1477155#c1 

Do you agree with it ?

**Comment by willdurand** [comment]
> The add-ons detail page will only show the button "+Add to Firefox" after refreshing the page. Until then it remains in the loading state. I will file a separate issue to track it. 

I forgot to mention that but there is nothing we can do for that.

> If we close this issue now then I must file a separate one for themes/static themes until the fix of https://bugzilla.mozilla.org/show_bug.cgi?id=1477155#c1

Yep, sounds good. I won't have news anytime soon though.

**Comment by ioanarusiczki** [comment]
The page refresh will be needed then.
I filed another issue to track the themes for this scenario https://github.com/mozilla/addons-frontend/issues/6091
This is verified fixed on AMO -dev with FF63(Win10)
