### ISSUE TITLE
Pagination is not displayed on the collection details page for a new collection with >25 add-ons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#5930]
STR

1. Log in to AMO
2. Go to your Collections page and Create a new collection
3. Add more that 25 add-ons to your new collection
4. Click on View my Collections from the user menu and select the new collection to view its details
5. Scroll down to the bottom of the page and try to navigate to the next page

Actual result:
The pagination component is not present on the collection details

Expected result:
Pagination is present for a new collection with >25 add-ons

Notes:
- reproduced on all AMO servers with FF61, Win10x64
- issue is solved when the collection details page is reloaded

**this video depicts what happens in Steps 4 and 5**

![no pagination](https://user-images.githubusercontent.com/31961530/44095236-f5c14872-9fe0-11e8-9f36-964a4ae11e2e.gif)

**Comment by xu3u4** [comment]
Hello,
May I take this bug?
Thanks.

**Comment by willdurand** [comment]
@xu3u4 sure!

**Comment by xu3u4** [comment]
Hmm...
I could produce the bug when I saw this issue.
Somehow, I cannot reproduce again. 
@AlexandraMoga would you test if this bug can be reproduced on your side?

**Comment by AlexandraMoga** [comment]
@xu3u4 I had another try and I can still reproduce the issue.

**Comment by xu3u4** [comment]
Hi @AlexandraMoga,
Sorry, can you give me more details about how to reproduce it?
Thank you.

**Comment by xu3u4** [comment]
Finally I can reproduce.

Let me give more details about how to reproduce.
1.  Log in to AMO
2. Go into a collection which has more than 25 add-ons 
3. At `/collections/:username/:slug/`, refresh
4. Go to /collections by clicking the dropdown menu on the top right
5. Go back to the collection which you visited has 25+ addons
6. The pagination is disappear
