### ISSUE TITLE
Hook up all analytics/tracking to the mozAddonManager install button

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5940]
### Describe the problem and steps to reproduce it:

Perform all the following actions with the new `mozAddonManager` install button from https://github.com/mozilla/addons-frontend/issues/3954 (this is only on in dev):
- install add-on / theme / etc...
- uninstall add-on / theme / etc...
- install and click the *Manage* button
- install but then cancel in the doorhanger prompt
- install an add-on in a way that fails (you can do this on dev by setting incorrect prefs)

Watch the developer console.

### What happened?

Some Google Analytics events are missing.

### What did you expect to happen?

You should see Google Analytics tracking events for each of these actions.

### Anything else we should know?

~~At the very least, we need to hook up the equivalent of successful installs~~ (I think they are handled already in https://github.com/mozilla/addons-frontend/blob/4578186b4c2c3dcf1fcf4f0670ac2f8adcb5aa18/src/core/installAddon.js#L475).

There are a couple unused tracking methods in `AMInstallButton` that may need to be removed.

**Comment by willdurand** [comment]
> There are a couple unused tracking methods in AMInstallButton that may need to be removed.

Those tracking methods are used when the `mozAddonManager` is not available.

**Comment by willdurand** [comment]
> install add-on / theme / etc...
> uninstall add-on / theme / etc...

I think those are sent already, as far as I can see.

> install and click the Manage button

You mean the "Enable" button? There is not tracking for that indeed, there is no constant yet.

> install but then cancel in the doorhanger prompt

This was never tracked IIRC, but this should probably be done.

> install an add-on in a way that fails (you can do this on dev by setting incorrect prefs)

Would you have a pref to set so that we can easily reproduce? In any case, a `INSTALL_ERROR` action is dispatched but there is no event sent, so we can find where this action is dispatched and add a tracking event.

**Comment by willdurand** [comment]
For QA: you should see analytics events sent (or logged in the console) for:

- install
- uninstall
- enable
- install followed by cancel

There is NO event sent when something wrong happens (failure/error). I am not sure what we want to track yet, so it should probably be moved to a new issue.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev (frontend and disco pane) with FF61, Win10x64

Here are some examples of events sent for the mentioned actions:

**Install add-on (ext, lwt, st):**

```
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs Started","eventAction":"addon","eventLabel":"Awesome Screenshot Plus - Capture, Annotate & More"}
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs","eventAction":"addon","eventLabel":"Awesome Screenshot Plus - Capture, Annotate & More"}
```

```
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Theme Installs","eventAction":"theme","eventLabel":"rainbow story unicorn"}
```

```
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Theme Installs","eventAction":"statictheme","eventLabel":"rm static theme 3"}
```



**Remove add-on:**
```
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Uninstalls","eventAction":"addon","eventLabel":"Awesome Screenshot Plus - Capture, Annotate & More"}
```

**Enable:**
```
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Activation","eventAction":"addon","eventLabel":"Awesome Screenshot Plus - Capture, Annotate & More"}
```

**Cancelled installation** - tested with the `extensions.webextPermissionPrompts` = `true`
```
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon Installs Cancelled","eventAction":"addon","eventLabel":"Magic Actions for YouTube™test"}
```


</br>

> There is NO event sent when something wrong happens (failure/error). I am not sure what we want to track yet, so it should probably be moved to a new issue.

@willdurand regarding this comment, is there already an issue filed for the missing logs or should I open one?

**Comment by willdurand** [comment]
> @willdurand regarding this comment, is there already an issue filed for the missing logs or should I open one?

can you please open one?

**Comment by AlexandraMoga** [comment]
Filed #6099
