### ISSUE TITLE
When you select a star, indicate that the add-on rating has been saved

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5941]
This is part of a new UX for reviews/ratings. See https://github.com/mozilla/addons-frontend/issues/5519

- Go to an add-on detail page
- Sign in
- Select a star to rate an add-on

A notice should tell you that the star rating was saved.

<img width="491" alt="screenshot 2018-08-14 16 32 51" src="https://user-images.githubusercontent.com/55398/44120010-9422ab88-9fe0-11e8-91f4-7b8ef9a141f2.png">

**Comment by suhailsinghbains** [comment]
Hi, would love to work on this bug.
Are you talking about the showing a Notice from Notice component.

**Comment by kumar303** [comment]
Thanks for offering to help! This is not a good issue to work on because it's already assigned to a developer. The best way to find issues to work on is to check this list https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome These are the issues we've labeled as `contrib: welcome` because they are ready to work on.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64 and Android 8.0

![saved rating](https://user-images.githubusercontent.com/31961530/45625846-8b50f700-ba96-11e8-9011-3e91250d13b7.gif)
