### ISSUE TITLE
Write a review inside of a text-box, not in an overlay

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5942]
This is part of a new UX for reviews/ratings. See #5519

- Go to an add-on detail page
- Sign in
- Select a star to rate an add-on

Instead of seeing an overlay, you should be able to write your review in a text box.

**QA**, please see the list of known issues for this patch at https://github.com/mozilla/addons-frontend/pull/5997

<img width="495" alt="screenshot 2018-08-14 16 33 26" src="https://user-images.githubusercontent.com/55398/44120134-f3a0d634-9fe0-11e8-8b63-eccd17375328.png">
<img width="487" alt="screenshot 2018-08-14 16 33 37" src="https://user-images.githubusercontent.com/55398/44120137-f659019e-9fe0-11e8-9a1d-fd2a5b202016.png">

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61 and Android 8.0

The current functionality is:
- rating is saved when a star is selected
- the review form is opened when a star is selected
- a different star rating can be selected and saved inside the review form
- a review can be written inside the the new textbox
- the review form can be dismissed by clicking on the "Nevermind, ...." button

@kumar303 I have two cases that haven't been specifically mentioned in the "known issues" list from #5997
I have logged #6120 and #6121 for more details
