### ISSUE TITLE
Implement read-only mode

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-frontend#5949]
As part of https://github.com/mozilla/addons-server/issues/1050 we implemented a read-only notification for the API as well.

The behavior is as follows:

In case of a maintainance / read-only mode get's turned on…
* `GET` requests behave normal
* `POST`, `PUT` and `DELETE` requests return `503` with a json response that contains a localized error message
* A custom `X-AMO-Read-Only` header is set to `true`
* a `Retry-After` header **may** be set, it's not a requirement though

In case that maintainance / read-only mode get's turned off…
* `GET`, `POST`, `PUT`, `DELETE` requests behave normal again
* `X-AMO-Read-Only` header is set to `false`

Since we're expecting a maintainance relatively soon it'd be really nice to give this a higher priority, hoping it's not too much work. But let me know in case it's more work and needs more time.

**Comment by kumar303** [comment]
It may be tricky because we don't have good ideas for how to make a global error handler yet (see https://github.com/mozilla/addons-frontend/issues/1484). Maybe if we implement standard page-level components (https://github.com/mozilla/addons-frontend/issues/5735) it will be easier.

**Comment by bobsilverberg** [comment]
Each component defines whether to display an error and where and how that error is displayed. Any component that dispatches an API call should have the capacity to show an error from that API call, but there could be a number of components on a given page, each of which display their own error messages.

**Comment by bobsilverberg** [comment]
I'm just wondering if and how we want to proceed with this. It sounds like a large and somewhat vague issue, so do we want to break it up into manageable pieces?

@EnTeQuAk @kumar303 @muffinresearch

**Comment by bobsilverberg** [comment]
I suppose we could watch the value of the `X-AMO-Read-Only` header and set a redux state to let the app know whether we're in read-only mode or not. It would still be a significant amount of work to respond to that, enabling and disabling features as a result.

**Comment by EnTeQuAk** [comment]
> enabling and disabling features as a result.

I think this could be tackled in different steps. Most importantly would be to always catch that 503 error and show a proper warning to the user. Next step would be to watch the header you mentioned and show a warning in case we are in read-only mode.

And once that's done, I'd guess and if there's time we could talk about disabling actual features imho. In the past, AMO never disabled anything but simply failed for write-requests in case of an failure. That's obviously not ideal but works for the few times we actually have to put the site in maintainance mode (happened… twice since I'm in the team, so, Oct 2015 afair)

**Comment by muffinresearch** [comment]
We really need to ability to define page level errors to support this e.g. if a critical API request results in a 503 we should know to show a whole-page 503 error page. @bobsilverberg I don't think we can currently do that yet can we?

The (possibly easier) alternative for the frontend would be to have ops send the 503 at the nginx level. In addition to this we also need sort out a decent looking self-contained static 5XX page.

**Comment by bobsilverberg** [comment]
> We really need to ability to define page level errors to support this e.g. if a critical API request results in a 503 we should know to show a whole-page 503 error page. @bobsilverberg I don't think we can currently do that yet can we?

I don't believe so, as @kumar303 mentioned at https://github.com/mozilla/addons-frontend/issues/5949#issuecomment-413212301.

I wonder if, as a first step, we could adjust our ErrorHandler to catch these specific errors and generate a more friendly version to explain why the API request failed? We'd still be showing that error in a specific spot on the page, as we do with many of our components, but it should be a fairly decent indication to a user that there was a problem with the data change they requested. I actually prefer this this to a whole-page 500 error in some cases, as it seems more user friendly.

For example, if you're looking at an add-on and you want to rate it, clicking on a star could either render a message just above the stars telling you the site is in maintenance mode and you should try your request again later, or it could take you away from the add-on details page to a full-page 500 error message. The former seems like a better user experience to me.

**Comment by EnTeQuAk** [comment]
> I wonder if, as a first step, we could adjust our ErrorHandler to catch these specific errors and generate a more friendly version to explain why the API request failed? We'd still be showing that error in a specific spot on the page, as we do with many of our components, but it should be a fairly decent indication to a user that there was a problem with the data change they requested

I do prefer that too and from what you're writing it doesn't sound too much of an effort? I don't think a global error has to happen, a global warning once `X-AMO-Read-Only` is set would be preferable but isn't a requirement.

We should make sure the frontend shows reasonable errors in case of read-only mode first, usually, read-only mode won't be turned on for an extended period of time anyway. (I think)

**Comment by muffinresearch** [comment]
> I wonder if, as a first step, we could adjust our ErrorHandler to catch these specific errors and generate a more friendly version to explain why the API request failed? We'd still be showing that error in a specific spot on the page, as we do with many of our components, but it should be a fairly decent indication to a user that there was a problem with the data change they requested. I actually prefer this this to a whole-page 500 error in some cases, as it seems more user friendly.

I 2nd the @bobsilverberg's idea of starting with the simplest solution - making sure inline error messages look ok for read-only mode is preferable doing something very specific and involved for such an infrequent use-case.

When we get to the point of adding the ability to control when we want to show page-level errors that will give us more options in the future.

**Comment by muffinresearch** [comment]
@bobsilverberg how much time do you think it would take to ensure inline messages are doing the right thing?

**Comment by willdurand** [comment]
Given that all write requests will be sent from the client, I believe we can change the `createApiError` function as follows:

```diff
diff --git a/.eslintrc b/.eslintrc
index 01491734b..6de7cf8de 100644
--- a/.eslintrc
+++ b/.eslintrc
@@ -37,7 +37,9 @@
     "FormData": true,
     // This is used to upload files in the browser.
     "File": true,
-    "FileReader": true
+    "FileReader": true,
+    // HTTP Response, for Flow
+    "Response": true,
   },
   "parser": "babel-eslint",
   "plugins": [
diff --git a/src/core/api/index.js b/src/core/api/index.js
index 819abb5d7..51cc4306e 100644
--- a/src/core/api/index.js
+++ b/src/core/api/index.js
@@ -23,6 +23,7 @@ import type { ReactRouterLocationType } from 'core/types/router';
 const API_BASE = `${config.get('apiHost')}${config.get('apiPath')}`;
 const { Entity } = normalizrSchema;
 
+export const AMO_READ_ONLY_HEADER = 'x-amo-read-only';
 export const DEFAULT_API_PAGE_SIZE = 25;
 
 export const addon = new Entity('addons', {}, { idAttribute: 'slug' });
@@ -41,9 +42,17 @@ export function makeQueryString(query: { [key: string]: any }) {
   return url.format({ query: resolvedQuery });
 }
 
+const isInReadOnlyMode = ({ response }: {| response: Response |}): boolean => {
+  return (
+    response.headers &&
+    response.headers.has(AMO_READ_ONLY_HEADER) &&
+    response.headers.get(AMO_READ_ONLY_HEADER) === 'true'
+  );
+};
+
 type CreateApiErrorParams = {|
   apiURL?: string,
-  response: { status: number },
+  response: Response,
   jsonResponse?: Object,
 |};
 
@@ -62,12 +71,18 @@ export function createApiError({
   const apiError = new Error(
     `Error calling: ${urlId} (status: ${response.status})`,
   );
+
   // $FLOW_FIXME: turn Error into a custom ApiError class.
   apiError.response = {
     apiURL,
     status: response.status,
-    data: jsonResponse,
+    data: isInReadOnlyMode({ response })
+      ? {
+          error: 'API is in read-only mode, please try later.',
+        }
+      : jsonResponse,
   };
+
   return apiError;
 }
 
```

**Comment by willdurand** [comment]
![screen shot 2018-10-10 at 12 11 21](https://user-images.githubusercontent.com/217628/46729651-416ac380-cc86-11e8-821d-1f189f0cdf33.png)

**Comment by muffinresearch** [comment]
@willdurand would you be up for converting this diff into a PR?

**Comment by willdurand** [comment]
> @willdurand would you be up for converting this diff into a PR?

Yes, I can do that.

**Comment by willdurand** [comment]
> I 2nd the @bobsilverberg's idea of starting with the simplest solution - making sure inline error messages look ok for read-only mode is preferable doing something very specific and involved for such an infrequent use-case.

Given that error messages is updated for `503` responses in case of read-only mode, everything just works already:

![2018-10-11 12 06 58](https://user-images.githubusercontent.com/217628/46797039-6165ba00-cd4e-11e8-872e-71fa77e7f1a4.gif)

There is no need to change anything.

**Comment by AlexandraMoga** [comment]
@willdurand how can we verify that this works in the frontend?

**Comment by willdurand** [comment]
@AlexandraMoga you can ask ops to turn read only mode on in -dev for some time, and try to add a review to an add-on.

**Comment by autrilla** [comment]
Let me know when you want it turned on and I'll flip the switch

**Comment by ioanarusiczki** [comment]
@autrilla anytime now Please let me know if I can start testing
Thanks!

**Comment by ioanarusiczki** [comment]
@bobsilverberg @willdurand @EnTeQuAk 
I verified this issue with FF62 and FF64 on AMO dev 

**read-only mode get's turned on**

- the POST/PUT/DELETE on AMO's new pages will return a `503 ` and a red error message is displayed. I verified for reviews, collections, user profile.

![what works](https://user-images.githubusercontent.com/33448286/47015717-5d72d700-d156-11e8-9d6d-43ff4e9fdf81.png)

- I've noticed that when an edit is made in Dev Hub the `503` is received without any message and the page is displayed in a continuous loading state. I did not test the submission of an add-on or to delete an add-on so I'll re-test and ask @autrilla to enable the switch again if this is needed.

![edit in dev hub](https://user-images.githubusercontent.com/33448286/47015932-00c3ec00-d157-11e8-880a-b9fc7f06a2d8.png)

- I could not log out, so the '503' is received but no message displayed on the new frontend


![log out](https://user-images.githubusercontent.com/33448286/47016128-77f98000-d157-11e8-982c-90ae30907b71.png)

and when I tried to log in I got a strange behavior - it looked like I could login and access the new AMO pages but I could not log in from dev hub (there was no error message there, it kept showing me the sign in button) - please note that I did not test the login with a clean profile

Here's the login issue
![strange login behavior](https://user-images.githubusercontent.com/33448286/47016331-0c63e280-d158-11e8-87bb-5ace20da798a.gif)

Please let me know if I should file a separate issue for dev hub and for the login/logout.

**read-only mode get's turned off**

- POST/PUT/DELETE works on AMO new pages
- PUT works in Dev Hub
- The login and logout works on both AMO new pages and from Dev Hub

**Comment by willdurand** [comment]
> I could not log out, so the '503' is received but no message displayed on the new frontend

I guess that's fine because we don't change the UI (it still appears logged in)

**Comment by willdurand** [comment]
You can probably file new issues for dev hub issues in addons-server.

**Comment by ioanarusiczki** [comment]
I filed on server a follow up for  dev hub here https://github.com/mozilla/addons-server/issues/9723 
This is verified fixed on AMO dev with FF62 - Win10
