### ISSUE TITLE
Add an underline to the links to "all reviews" from the AddonMeta component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5952]
The number of reviews and the title that reads "Reviews" was turned into a link in the `AddonMeta` component, with the number being displayed in black text and the title in grey text. To make these more obviously links, we should also display an underline for them. Both of them should become blue in colour when hovered over.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF61, Win10x64 and Android 8.0

![reviews link](https://user-images.githubusercontent.com/31961530/44262648-79283280-a224-11e8-8e67-99e0e2b794ce.gif)
