### ISSUE TITLE
Jest hides the test run summary at the end of a test run

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5956]
When you run `yarn test`, you can see a test summary at the bottom of the screen that is continually updating while the tests are running, which looks something like this:

![screenshot 2018-08-15 16 32 10](https://user-images.githubusercontent.com/142755/44171669-d0a19380-a0a8-11e8-8585-24568bbb8474.png)

At the end of the test run this summary is hidden, and replaced with the "Watch Usage" instructions:

![screenshot 2018-08-15 16 33 35](https://user-images.githubusercontent.com/142755/44171718-fb8be780-a0a8-11e8-87b5-01330307129b.png)

If I comment out our custom reporter at https://github.com/mozilla/addons-frontend/blob/master/jest.config.js#L18 it fixes the issue, so there's either a problem with our custom reporter, or a jest regression related to using a custom reporter.

**Comment by willdurand** [comment]
The new reporter extends Jest's default reporter, which does not provide a summary. Extending the `SummaryReporter` might be a good option to fix this issue if we can keep the output as clean as it is currently with the reporter we use in this project.

**Comment by AlexandraMoga** [comment]
Could you please add STR or the label 'qa:not needed'?
Thanks

**Comment by willdurand** [comment]
added "qa:not needed"
