### ISSUE TITLE
Two new warnings from yarn install

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5962]
On the current master branch, running `yarn` now yields the following warnings:

```
warning " > connected-react-router@4.4.1" has unmet peer dependency "react-router@^4.3.1".
warning " > url-loader@1.1.0" has incorrect peer dependency "webpack@^4.0.0".
```

I'm not sure if this is anything to be concerned about or something we want to address, but I know we got rid of all the warnings at some point.

**Comment by willdurand** [comment]
It is not an issue but I wonder why we did not get a greenkeeper PR for react router.

We should probably downgrade url-loader for webpack 3 compat, just to get rid of the warning
