### ISSUE TITLE
Preview image for my amazing theme didn't generate

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#5966]
I submitted this theme to try the system out: https://addons.mozilla.org/addon/greyscale-static/

Result: the edit page is stuck with the message "Preview still being generated". I used the theme creation wizard. The problem is most likely the background image I uploaded, which is a 1x1 transparent PNG (I just wanted to change colors).

I'm thinking that the placeholder text for the preview could also use some indicator that after X amount of time, an issue should be filed.

**Comment by willdurand** [comment]
Should we move this issue to addons-server instead?

**Comment by AlexandraMoga** [comment]
This might be somehow related to https://github.com/mozilla/addons-server/issues/9081 , which is indeed a server issue

**Comment by eviljeff** [comment]
This should definitely be a server issue @jvillalobos.  

I can't immediately see what's happened - if you look in the reviewer [tools](https://reviewers.addons.mozilla.org/en-GB/reviewers/review/greyscale-static) the wider preview (that's used for frontend search results) _is_ rendered, but the primary preview isn't.

**Comment by eviljeff** [comment]
@jvillalobos I can't replicate this on -dev or prod with the zip file from https://addons.mozilla.org/addon/greyscale-static/ or by using the theme wizard with the [same transparent png](https://addons.mozilla.org/en-GB/developers/addon/greyscale-static-test2/). (transparent gifs/pngs are used often for themes with additional backgrounds so shouldn't be a problem).

If you _can_ replicate with either another version on the same addon, or a new submission, can you file an issue on addons-server.

> I'm thinking that the placeholder text for the preview could also use some indicator that after X amount of time, an issue should be filed.

Can you file an issue on addons-server with new copy?  If we want to indicate some amount of time there really isn't a way of knowing how long - it should be very quick (e.g. a second) if there isn't a celery delay or some other problem so perhaps some vague wording about "keeping seeing this message" or similar is better.

**Comment by jvillalobos** [comment]
Uploading a new version using the XPI from devhub fixed the listing, so I don't know what failed the first time.
