### ISSUE TITLE
Configure DismissibleTextForm for inline add-on reviews

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#5976]
`DismissibleTextForm` needs some configuration for https://github.com/mozilla/addons-frontend/issues/5942

**For QA**: Please check for regressions where we already use this component:
- When editing or replying to a review on the add-on review listing page
- When leaving a note on a collection add-on

**Comment by ioanarusiczki** [comment]
I made some tests with FF61(Win10&Android 8.0) for
> When editing or replying to a review on the add-on review listing page
    When leaving a note on a collection add-on

no regressions found.
