### ISSUE TITLE
After expanding the description field and then some text is typed in, the "save collection" button still looks inactive

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#5988]
STR:
1. Load AMO dev and go to your collections, the user must be logged in
2. Click a collection and and go to it's edit page
3. Click inside the Description field and expand it a bit vertically - using the right edge of the box
4. Write something in the description text field
5. Observe the "Save collection" button

Actual result:
Save collection button is displayed as being inactive - greyed out.

Expected result:
Save collection should be active - dark blue.

Notes:
This issue is reproducible on AMO dev with FF61(Win10).
Mouse hovering over the save collection button will change it's state into active.

![expand description field then edit](https://user-images.githubusercontent.com/33448286/44340666-32d60c00-a48e-11e8-91b6-a4daba7b343d.gif)

**Comment by suhailsinghbains** [comment]
Hi @ioanarusiczki 
I'll check what's causing the issue.

**Comment by bobsilverberg** [comment]
@ioanarusiczki I cannot reproduce this on OS X. I wonder if it's a Windows quirk. It sounds like the browser is not sending the expected events from the textbox after it has been expanded. Are you able to check on a different OS?

**Comment by suhailsinghbains** [comment]
@bobsilverberg I have Arch Linux still get the same result as the short video attached above. And my browser is Firefox Dev Edition.
