### ISSUE TITLE
Move logic for Collection Details card into its own component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#5990]
To support #5748, and further simplify the `Collection` component, move the logic that renders the details card (which can end up being either a `CollectionDetails` component or a `CollectionManager` component) into its own component.

**Comment by bobsilverberg** [comment]
For QA: Please verify there are no regressions with the Collection Details page nor with editing the details of a collection.

**Comment by ioanarusiczki** [comment]
I verified collections - detail page and while editing - on AMO dev with FF61(Win10&Android 8.0)
No regressions found.
