### ISSUE TITLE
30 August homepage content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#5993]
For the **30 August** push, please update homepage content programming to reflect details in this [doc](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#).

@muffinresearch @bobsilverberg

**Comment by ioanarusiczki** [comment]
Verified the content as mentioned in the [doc](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#) on AMO dev with FF61(Win10&Android 8.0)
Full validation will be made on AMO prod
