### ISSUE TITLE
Grey on-state shows when turning on ABP

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#600]
Installing ABP via disco pane on Windows 10 latest Nightly causes a strange in-between state where I can see the check-mark and a green outline, but the background is still grey. This resolved itself after a short time. See animation for behavior:
![discopaneinstallwindows10statebug](https://cloud.githubusercontent.com/assets/8145891/16085619/80147850-3314-11e6-915c-bf2285bd1043.gif)

The console shows:

`[disco] [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Theme Installs","eventAction":"addon","eventLabel":"Adblock Plus"}(unknown)`
`[disco] [install] Adding listener for onDownloadStarted(unknown)`
`[disco] [install] Adding listener for onDownloadProgress(unknown)`
`[disco] [install] Adding listener for onDownloadEnded(unknown)`
`[disco] [install] Adding listener for onDownloadCancelled(unknown)`
`[disco] [install] Adding listener for onDownloadFailed(unknown)`
`[disco] [install] Adding listener for onInstallStarted(unknown)`
`[disco] [install] Adding listener for onInstallProgress(unknown)`
`[disco] [install] Adding listener for onInstallEnded(unknown)`
`[disco] [install] Adding listener for onInstallCancelled(unknown)`
`[disco] [install] Adding listener for onInstallFailed(unknown)`
`[disco] Events to handle the installation initialized.(unknown)`
`[disco] Event received Object { type: "onInstalling", id: "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c…", needsRestart: false }(unknown)`
`[disco] Event received Object { type: "onInstalled", id: "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c…", needsRestart: false }`

**Comment by muffinresearch** [comment]
I can't reproduce this one on a windows 10 vm - @designakt - can you still reproduce it?

**Comment by muffinresearch** [comment]
@designakt Ok I think I can see this albeit not as slowly as you do. The patch in #646 should fix it.

**Comment by designakt** [comment]
@muffinresearch I now only see the :heavy_check_mark: appear with a delay. As if the button was frozen for a second. Seams to me as if the install state disappears to soon?
![discopaneinstallwindows10statebug2](https://cloud.githubusercontent.com/assets/8145891/16384571/b740d8fe-3c89-11e6-8355-f06c13797c58.gif)

This is what the console logs:
```
[disco] [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Theme Installs","eventAction":"addon","eventLabel":"Adblock Plus"}(unknown)
[disco] [install] Adding listener for onDownloadStarted(unknown)
[disco] [install] Adding listener for onDownloadProgress(unknown)
[disco] [install] Adding listener for onDownloadEnded(unknown)
[disco] [install] Adding listener for onDownloadCancelled(unknown)
[disco] [install] Adding listener for onDownloadFailed(unknown)
[disco] [install] Adding listener for onInstallStarted(unknown)
[disco] [install] Adding listener for onInstallProgress(unknown)
[disco] [install] Adding listener for onInstallEnded(unknown)
[disco] [install] Adding listener for onInstallCancelled(unknown)
[disco] [install] Adding listener for onInstallFailed(unknown)
[disco] Events to handle the installation initialized.(unknown)
[disco] Event received Object { type: "onInstalling", id: "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c…", needsRestart: false }(unknown)
[disco] Event received Object { type: "onInstalled", id: "{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c…", needsRestart: false }(unknown)
```
Where the green background appears with onInstalling event, and the checkmark with onInstalled event.
![discopaneinstallwindows10statebug2log](https://cloud.githubusercontent.com/assets/8145891/16385006/6a90ad52-3c8b-11e6-980e-bb40220a2ca2.gif)
I expected both to appear with onInstalled.

**Comment by muffinresearch** [comment]
@designakt  Ah ok - thanks for the update. It appears we're on the right track - at least the background is now faster.

Seems to me that the transtions are getting bogged down on your machine. I'll look to turn off anything on the tick and see if we can get that working as it should.

**Comment by muffinresearch** [comment]
@designakt I've made a few changes re: the check mark svg. Can you re-test and let me know how you get on?

**Comment by muffinresearch** [comment]
This was cleared up with a new profile from talking to Markus on irc.
