### ISSUE TITLE
Why was "the fox only better" removed?

### ISSUE THREAD

**Issue by dserodio** [mozilla/addons-frontend#6002]
### Describe the problem and steps to reproduce it:

I found references to "thefoxonlybetter" in my about:config. I Googled this term and found https://support.mozilla.org/en-US/questions/1036432 which links to https://addons.mozilla.org/en-US/firefox/addon/the-fox-only-better/

### What happened?

https://addons.mozilla.org/en-US/firefox/addon/the-fox-only-better/ states that "This add-on has been disabled by an administrator."

### What did you expect to happen?

There should be an explanation about _why_ this add-on was disabled. 

### Anything else we should know?

Is (was) this a malicious add-on? Should I be worried about the thefoxonlybetter references in my about:config?

**Comment by jvillalobos** [comment]
The add-on was never blocklisted in Firefox, so whatever the reasons for disabling it were, they were not serious enough to warrant remote-disabling all instances. It might have been taken down for stability problems with future versions of Firefox, and the fact that it was abandoned by the developer (they announced it on their website).

`about:config` was used by extensions for storage purposes. If the extension is enabled, it uses those entries to store its configuration. It shouldn't a cause for concern.

For more information, you can try contacting the developer, though it's likely they are not responding to such requests.
