### ISSUE TITLE
Reviews count for the previous add-on are visible on the details page of an add-on opened from recommendations

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6003]
STR:

1. Load AMO stage
2. Select an add-on to view its details page
3. Scroll down to the recommendations section and select one of the recommended add-ons
4. Observe the Ratings card on top right

Actual result:
The reviews count and links from the previously visited add-on are displayed on the statistics card

Expected result:
Only the ratings pertaining to the current add-on are displayed on the statistics  card

Notes:
- Edit: also reproduced from a Theme details page when opening a theme from the More themes by author card
- correct count displayed after the page is reloaded 
- reproduced on AMO -dev and stage with FF61, Wib10x64

![double ratings](https://user-images.githubusercontent.com/31961530/44459871-cab13280-a613-11e8-90df-40e6f33b8be0.gif)

**Comment by kumar303** [comment]
This has been cherry-picked for the release https://github.com/mozilla/addons/blob/master/releases/2018/08/23.md

It should show up on dev and stage shortly.

**Comment by AlexandraMoga** [comment]
Verified fixed on stage with FF61, Win10x64

![correct reviews](https://user-images.githubusercontent.com/31961530/44521279-30b4bd00-a6db-11e8-95aa-c3f28d46d0c4.gif)
