### ISSUE TITLE
Disco pane Theme previews (lwt and static) are not responsive on Mac

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6005]
STR

1. Open your Firefox browser
2. Go to Discovery Pane
3. Resize the browser window

Actual result:
Theme previews, both leightweigt and static, are not responsive

Expected result:
Theme previews are responsive

Notes:
- reproduced on all AMO servers with FF61, macOs High Sierra 10.13.2

![image](https://user-images.githubusercontent.com/31961530/44460571-4c09c480-a616-11e8-94c2-e2bd8d198302.png)

<img width="551" alt="screen shot 2018-08-22 at 10 17 46" src="https://user-images.githubusercontent.com/31961530/44460609-72c7fb00-a616-11e8-819c-31a495c009ff.png">

**Comment by willdurand** [comment]
I think the issue is the `display:block` on `.addon.theme` for some reasons (at least without mozAddonManager).

**Comment by willdurand** [comment]
I can't reproduce anymore...

**Comment by AlexandraMoga** [comment]
I can't reproduce it either. The disco pane redeployment in -dev has fixed the problem.
