### ISSUE TITLE
dim disco pane while video is large

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#601]
Having the disco pane dim would make it more pleasant to focus on the video while watching it.

![screen-shot-2016-06-15-at-16 23 54](https://cloud.githubusercontent.com/assets/8145891/16086054/21a26352-3316-11e6-9a83-e283f417c3aa.png)
@pwalm what do you think? I wonder how this will impact closing the window.

Would need [Bug 1273974 - Discovery pane has extra left padding](https://bugzilla.mozilla.org/show_bug.cgi?id=1273974) to be fixed.

**Comment by pwalm** [comment]
I'm into it. Let me find values for the background and for the button. I'll post later!

**Comment by Ryuno-Ki** [comment]
@pwalm Any updates?

**Comment by muffinresearch** [comment]
Since we can't dim the sidebar I think is a wontfix.

**Comment by designakt** [comment]
Looking at the screenshot this will reduce distraction while watching the video even without dimming the sidebar.
@pwalm can you give a value for the background?

**Comment by tofumatt** [comment]
We’re concerned that not dimming the sidebar will make it look like a bug and quite odd. There is a fullscreen option for those who want to focus on the video, isn’t that enough?

Dimming the background while it’s playing also means users have to pause it to click on anything else on the page.

**Comment by designakt** [comment]
You are right. After a second look I agree with you. Users not being able to click at anything while watching is a good one. - For that to be OK the transition of the video would need to be different. (something we will not do.)
