### ISSUE TITLE
Copy edits for star string in new ratings/reviews panel

### ISSUE THREAD

**Issue by MeridelW** [mozilla/addons-frontend#6011]
**Current string:** # star average

**Recommend shortening and capitalizing. Revised string:** # Stars

![stars string](https://user-images.githubusercontent.com/33848177/44473518-0c32e500-a5f6-11e8-9101-308cd3343ec4.png)

**Comment by bobsilverberg** [comment]
@MeridelW @kumar303 

How do we want to deal with pluralization for this?

I think the following are both correct to use "Stars":
- 1.3 Stars
- 2.5 Stars

But what about exactly 1?  Should it be "1 Stars" or "1 Star"?

**Comment by kumar303** [comment]
We need to let our localization tools handle pluralization. It will be different across locales but, yes, "1 Star" and "1.3 Stars" is grammatically correct for English. Since you're using `ngettext()` in the patch it will get the right localization 👍

**Comment by ioanarusiczki** [comment]
I verified this with FF61(Win10&Android 8.0) on AMO dev.
@bobsilverberg 
I've noticed that no matter what language I test with the "Stars" is not translated but "Users" and "Reviews" are translated. 

Example in Hungarian 
![not translated](https://user-images.githubusercontent.com/33448286/44584988-6f1dab00-a7b3-11e8-99e6-97c28b1d7f0a.png)

**Comment by willdurand** [comment]
@ioanarusiczki isn't it that we did not get translations for this string yet? I have extract the locales today.

**Comment by ioanarusiczki** [comment]
@willdurand Should I be re-checking on Monday/Tuesday then?

**Comment by bobsilverberg** [comment]
@ioanarusiczki I think Will's correct. You could check again on Monday/Tuesday, but I suppose there's no guarantee that any translations will have been done by then either, as this is a brand new string.

**Comment by willdurand** [comment]
@ioanarusiczki you can try French: https://addons-dev.allizom.org/fr/firefox/addon/magic-birds/

**Comment by ioanarusiczki** [comment]
@bobsilverberg  I got confused reading Kumar's comment above. It's all good if translations will follow.

>We need to let our localization tools handle pluralization.

Verified fixed on AMO dev with FF61(Win10)
