### ISSUE TITLE
Show loading indicator for rating stars

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6014]
We never implemented a loading indicator for rating stars when the add-on detail page loads. It could benefit from one. It's definitely needed for https://github.com/mozilla/addons-frontend/issues/5942 (a new inline review form) because the stars look jumpy when you save them.

**For QA**:

- Sign in and rate an add-on on the detail page by selecting its stars
- Refresh the page
- You should now see an indication that the saved star rating is loading before it shows your previously saved rating.

**Comment by hritvi** [comment]
Hey @kumar303. Can I work on this issue? Thanks in advance :)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF61(Win10&Android 8.0)
The loading indicator for the rated stars

![loading state for rated stars](https://user-images.githubusercontent.com/33448286/44712213-f5d6ce80-aab8-11e8-9e81-d80a0297cc1a.gif)

**Comment by kumar303** [comment]
Hello @hritvi. Sorry but I missed your question until just now. The best way to find issues is to look through the [`contrib: welcome`](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) label.
