### ISSUE TITLE
Scrolling the disco pane is not possible on the left side of the page in about:addons

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#602]
There is an area in about:addons next to the sidebar that is part of the sidebar, but has the same color as the disco pane. Users will not understand why they can not scroll the page while their mouse is over that area.
![discopanescroll](https://cloud.githubusercontent.com/assets/8145891/16086544/d0f1fb46-3317-11e6-8359-c46c72298b0f.gif)
_(I am basically scrolling all the time, but it is not working if my mouse is too far to the left.)_

Can be fixed by [Bug 1273974 - Discovery pane has extra left padding](https://bugzilla.mozilla.org/show_bug.cgi?id=1273974).

**Comment by muffinresearch** [comment]
The Platform bug has been fixed and will landed in FF50. I've filed a separate bug to deal with removing our offset adjustment here: #639

**Comment by muffinresearch** [comment]
Closing this one since there's nothing to do here...

**Comment by ValentinaPC** [comment]
Verified as fixed on FF 52.0a1 (2016-10-30) using Win 7.
Video for this issue: 
![totheleft](https://cloud.githubusercontent.com/assets/15685960/19855126/90792b22-9f7b-11e6-81e1-cc13a7140a59.gif)
