### ISSUE TITLE
Install buttons on the disco pane are not responsive

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6027]
Follow up for #5887 

STR:

1. Open your Firefox browser
2. Go to the Discovery Pane
3. Resize the window

Actual result:
Install buttons are not responsive

Expected result:
Install buttons should fit in the main frame

Notes:
- reproduced on AMO -dev with FF61, WIn10x64
- link to discopane - https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/61.0.2/WINNT/normal

![image](https://user-images.githubusercontent.com/31961530/44521709-a5d4c200-a6dc-11e8-8e78-6f0a2849aa11.png)

**Comment by willdurand** [comment]
I think one way to fix this issue is to hide the extension icon on small screens.

**Comment by ShivangiKakkar** [comment]
Hey @AlexandraMoga @willdurand 
I would like to work on this issue.

**Comment by willdurand** [comment]
@ShivangiKakkar please go ahead!

**Comment by ShivangiKakkar** [comment]
@willdurand , Thanks for assigning me this :)
Before starting I have this one question, how do I access discovery page locally?

**Comment by willdurand** [comment]
@ShivangiKakkar you run `yarn disco` instead of `yarn amo:dev`.

**Comment by ShivangiKakkar** [comment]
Oh okay :) 
Thanks!
@willdurand

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF61, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/44661387-324fef00-aa13-11e8-9d29-8f4e356f71f5.png)
