### ISSUE TITLE
Simulate uncaught promise rejections

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6032]
We are currently running Node 8 where uncaught promise rejections show a warning. The process keeps running. In Node 11, uncaught promise rejections will cause the Node process to exit (see https://github.com/nodejs/node/issues/20392).

We should add an [error-simulation](https://github.com/mozilla/addons-frontend/tree/master/src/core/components/error-simulation) view to simulate this.

**Comment by willdurand** [comment]
We can probably listen to these events:

- https://nodejs.org/api/process.html#process_event_unhandledrejection
- https://nodejs.org/api/process.html#process_event_uncaughtexception

and log the error (highest level) + exiting properly.

**Comment by kumar303** [comment]
For the simulation, we just need to trigger it. It's probably as easy as:

```diff
diff --git a/src/core/components/error-simulation/SimulateAsyncError/index.js b/src/core/components/error-simulation/SimulateAsyncError/index.js
index 7c8c792f3..21bd2aecc 100644
--- a/src/core/components/error-simulation/SimulateAsyncError/index.js
+++ b/src/core/components/error-simulation/SimulateAsyncError/index.js
@@ -8,7 +8,10 @@ export class SimulateAsyncErrorBase extends React.Component {
   render() {
     log.info('Simulating an asynchronous error');
     setTimeout(() => {
-      throw new Error('This is a simulated asynchronous error');
+      const promise = new Promise();
+      promise.reject(
+        new Error('This is a simulation of an uncaught promise rejection'),
+      );
     }, 50);
     return <p>Asynchronous error simulated, check the logs</p>;
   }

```

(but in its own component, of course)
