### ISSUE TITLE
Firefox add-on not found

### ISSUE THREAD

**Issue by Muscogulus** [mozilla/addons-frontend#6033]
### Describe the problem and steps to reproduce it:

1. In Firefox, navigate to https://www.britannica.com/insights
2. Follow the link to install the Firefox add-on

### What happened?

Encountered a "Page not found" error at URL https://addons.mozilla.org/en-US/firefox/addon/britannica-insights/

### What did you expect to happen?

Expected to find a typical add-on page for the Britannica Insights extension

**Comment by championshuttler** [comment]
Hi @Muscogulus, I think this addon is deleted by the creator. We can not do anything in this case.
I suggest you search for another addon for same functionality if it's available.

**Comment by Muscogulus** [comment]
The creator still provides a link. I will contact Britannica and ask whether they have killed the extension.

**Comment by jvillalobos** [comment]
It wasn't deleted, but it was temporarily taken down due to a code review issue. This will probably be corrected and the add-on will be back up.
