### ISSUE TITLE
Hide Search Tool add-on type in search filter by default

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6038]
Regular searches on AMO shouldn't include Search Tool as a possible add-on type. This type should only appear on the filter if the user is searching for it in the first place (`type=search`). So, the only access points are Firefox settings and the AMO top navigation (More > Search Tools).

**Comment by willdurand** [comment]
@jvillalobos is this still relevant? I tried to reproduce the issue by searching "search" on AMO. I wouldn't be happy if I had to explicitly select "search" in the filters to find open search add-ons.

With the recommended extensions pushed to the top, maybe we don't need to do this anymore? WDYT?

**Comment by jvillalobos** [comment]
It's still an issue, but we plan to migrate open search add-ons soon, so I don't think we need to keep this open.
