### ISSUE TITLE
`<review-count> Reviews` is composed of two links

### ISSUE THREAD

**Issue by dessant** [mozilla/addons-frontend#6042]
![screenshot from 2018-08-24 11-22-49](https://user-images.githubusercontent.com/7513068/44573880-87c89980-a790-11e8-9c5d-813128471b5b.png)

Since both rows link to the reviews page, they should be merged into a single link. This would also avoid having to click on the first or second row to access the link, they could act as a single item, with the space between them being clickable.

**Comment by SeanPrashad** [comment]
We would look to have the `Link` component wrap both the `reviewCount` and `reviewTitle` found here:

https://github.com/mozilla/addons-frontend/blob/eec3da26c8c09487d8e3b9e87a7243614c6b3260/src/amo/components/AddonMeta/index.js#L70-L72

Then we could pass an empty string for the `Metacard`'s `title` prop:

https://github.com/mozilla/addons-frontend/blob/eec3da26c8c09487d8e3b9e87a7243614c6b3260/src/amo/components/AddonMeta/index.js#L97

**Comment by kumar303** [comment]
Thanks for taking the time to file an issue. This was implemented as intended. It is possible to click both links and it's not necessary to make the space between them clickable.
