### ISSUE TITLE
Reducer/Saga/API code to delete a review

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6054]
To support #5495 and #3075, we need reducer/saga/api support for deleting a review.

**Comment by bobsilverberg** [comment]
For QA: This code isn't exposed anywhere yet, as there's no UI to delete a review, but it did touch modules that do other things with reviews, so it's probably best to make sure there are no regressions with an review functionality.

**Comment by ioanarusiczki** [comment]
Release testing is completed - no regressions found. 
Verified fixed on AMO stage with FF61(Win10&android 8.0)
