### ISSUE TITLE
apiState should not be optional in api/reviews.js

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6055]
The flow type for `apiState` is defined as optional throughout the [api/reviews.js](https://github.com/mozilla/addons-frontend/blob/master/src/amo/api/reviews.js) file, but it really should be mandatory throughout. This issue is to fix that, and we should probably audit the flow types throughout the file to make sure there are no other issues as well.

**Comment by nabendu82** [comment]
Can you please check [6057](https://github.com/mozilla/addons-frontend/pull/6057)

**Comment by willdurand** [comment]
thanks @nabendu82!

**Comment by willdurand** [comment]
@AlexandraMoga the review feature should still work as intended (leaving a review, listing reviews)

**Comment by ioanarusiczki** [comment]
Looks good to me. Verified fixed on AMO dev with FF61(Win10 and Android 8.0)
This was also tested for https://github.com/mozilla/addons-frontend/issues/5998. I noticed an issue that is not reproducible on AMO stage right now and I filed it as a server issue here mozilla/addons-server#9263 Could be a regression.
