### ISSUE TITLE
Don't repeat Summary on product page if there's no Description

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6058]
Add-ons can have a short Summary and a longer Description, both of which appear in the product page. If the Description is missing, we currently duplicate the Summary and show that in place of a Description. Instead of doing that, the Description section should not show up at all. 

It looks like this was fixed for themes already, in https://github.com/mozilla/addons-frontend/issues/5364#issuecomment-404312967

**Comment by SeanPrashad** [comment]
Hey @jvillalobos - I think we'll need to take a look here:

https://github.com/mozilla/addons-frontend/blob/eec3da26c8c09487d8e3b9e87a7243614c6b3260/src/amo/components/Addon/index.js#L274

Keep your 👀 peeled for a PR!

**Comment by vcarciu** [comment]
Verified as fixed: 
![nodescription](https://user-images.githubusercontent.com/1583842/45439798-6b4ebb80-b6c3-11e8-80b4-714339ebe211.png)
