### ISSUE TITLE
Cleanup errors/warnings when running `yarn disco`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6059]
There are a lot of errors related to invalid props when starting disco locally. We should fix those errors. See #5860 for amo.

For QA:

- the install button should continue to work in -stage (which is not the same button as in -dev)
- the disco pane should work as intended in -dev (i.e. installing/removing add-ons with the mozAddonManager)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev and stage with FF61, Win10x64

No regressions found with install buttons on either of the servers.
