### ISSUE TITLE
My reviews section includes developer replies too

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#6070]
### Describe the problem and steps to reproduce it:
Login to AMO
Navigate to your profile(extension developer)
Say - https://addons.mozilla.org/en-US/firefox/user/trishulgoel/
Scroll to 'my reviews' section

### What happened?
'My reviews' section contains my developer replies along with my reviews.

### What did you expect to happen?
As section heading says 'my reviews', it should contain only the reviews I have given to addons, not the replies which I gave to user reviews of my addon

### Anything else we should know?

<img width="889" alt="screen shot 2018-08-26 at 4 47 35 pm" src="https://user-images.githubusercontent.com/5318732/44627716-38c96280-a950-11e8-860c-e77f0d3765e6.png">

**Comment by willdurand** [comment]
> As section heading says 'my reviews', it should contain only the reviews I have given to addons, not the replies which I gave to user reviews of my addon

This section lists all your reviews, including your replies to reviews since we consider those replies to be reviews as well.
