### ISSUE TITLE
Investigate potential issue with user profiles

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6077]
### Describe the problem and steps to reproduce it:

1. Browse https://addons-dev.allizom.org/en-US/firefox/user/00/
2. wait, wait, wait

### What happened?

Sometimes you get a 404 from disco pane (⚠️), sometimes a timeout.

### What did you expect to happen?

A `404` page from amo is displayed.

### Anything else we should know?

Likely related issue: https://github.com/mozilla/addons-frontend/issues/6007#issuecomment-416237859

**Comment by kumar303** [comment]
Weird. We should definitely make sure this does not have DOS implications.

**Comment by willdurand** [comment]
For some reasons, I cannot reproduce this issue anymore... closing.
