### ISSUE TITLE
Remove dead code related to editing old reviews

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6079]
**For QA**: please make sure editing reviews for matching add-on versions still works.

At some point, it no longer became possible to edit a review that was submitted for an older add-on version. See https://github.com/mozilla/addons-frontend/issues/4529

The code for this is dead. It doesn't work and is [not tested](https://codecov.io/gh/mozilla/addons-frontend/src/76640e28035b1581096b49ac6064cef37635ad4f/src/amo/components/RatingManager/index.js#L129). We should just remove it for now since there is no easy way to fix this -- the mapped `userReview` prop makes the code unreachable.

Keeping dead code around without tests is pointless. We will revisit this logic when we fix the bug up above.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64 and Android 7.0

User reviews and developer replies can be edited when they are posted for a current listed add-on version.
