### ISSUE TITLE
When overlay is open to rate an addon, the stars styles are now above overlay

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6082]
### Describe the problem and steps to reproduce it:

got to an addon detail page and click on a star to rate. 
You see stars above overlay 

### What happened?

You see stars above overlay and even modal if screen is small enough:

![Alt text](https://monosnap.com/image/q5KwyuVk5KIOpotk4ECCp1RQbb4cGC.png)

### Anything else we should know?

It could be a regression from PR #6056 (maybe?) and something just needs to slightly adjusted to account for this.

**Comment by rebmullin** [comment]
This might be a good first time bug except probably want to fix pretty soon..

**Comment by willdurand** [comment]
I see that stars are above the overlay and the stars in the overlay card are gone because the padding left/right is huuuuge 😞

**Comment by rebmullin** [comment]
ohhh.. yeh these are the stars that are supposed to be *in* the modal..I see

**Comment by rebmullin** [comment]
okay so 2 issues here I guess:

stars in modal are missing from overlay (as you noted..b/c of padding)
stars in rating manager z-index (or other styles) are off

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF61, Win10x64 and Android 8.0

The stars are in the right place now:

![image](https://user-images.githubusercontent.com/31961530/44734310-44548f00-aaf2-11e8-8ab5-0e114647f78e.png)

![image](https://user-images.githubusercontent.com/31961530/44734323-4c143380-aaf2-11e8-8e8d-04a9d83b2231.png)

@rebmullin  The only difference observed between -dev and stage is that on -dev the size of the overlay is slightly smaller than stage:

![image](https://user-images.githubusercontent.com/31961530/44734815-74506200-aaf3-11e8-9a87-24b48bab0ad9.png)

**Comment by willdurand** [comment]
> @rebmullin The only difference observed between -dev and stage is that on -dev the size of the overlay is slightly smaller than stage:

no problem with that
