### ISSUE TITLE
Missing Add-on

### ISSUE THREAD

**Issue by MyMammothTech** [mozilla/addons-frontend#6087]
I really really liked this adblocker add-on.  Any idea where it went?

https://addons.mozilla.org/en-US/firefox/addon/adblock-adblock/

![adblock](https://user-images.githubusercontent.com/42765315/44707673-07d55480-aa5a-11e8-8b98-3c25c9531de0.png)

**Comment by jvillalobos** [comment]
Either its URL was changed by the developer, or it was deleted. This repository is for code issues on the site, we can't help you find it.
