### ISSUE TITLE
Add Flow coverage to `installAddon` HOC

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6088]
We should add Flow types to the `installAddon` file, which contains the HOC for managing add-ons.

**Comment by willdurand** [comment]
For QA: add-ons install/uninstall should continue to work as expected.

**Comment by ioanarusiczki** [comment]
I verified installation of extensions, lang packs, dictionaries, static themes, lightweight themes on AMO dev with FF64 - (Win10)
I did not have problems installing, removing, disabling and then enabling them.  I've noticed again the already known and filed issues which is https://github.com/mozilla/addons-frontend/issues/5929 and https://github.com/mozilla/addons-frontend/issues/6091
