### ISSUE TITLE
Can't input values in popups on any site due to uninformed discontinued add-on.

### ISSUE THREAD

**Issue by Anutrix** [mozilla/addons-frontend#6090]
### What happened?
Can't input values in popups on any site after installing Enable Right Click and Copy that was supposedly at https://addons.mozilla.org/mn/firefox/addon/enable-rightclick-and-copy/ .
### What did you expect to happen?
I expected no issues.
### Anything else we should know?
The addon seems to be removed now. Wish there was a notice in addon manager that would tell if an buggy/old add-on was discontinued(its page removed) by its author.

https://addons.mozilla.org/mn/firefox/addon/enable-rightclick-and-copy/

**Comment by Anutrix** [comment]
One possible solution is that we could add an option in settings that would allow users to choose default/current behaviour or trigger rightclick regardless even if dragged.

**Comment by bobsilverberg** [comment]
This is the issue tracker for the addons.mozilla.org (AMO) web site, but your issue sounds like it's with a particular (although already removed) add-on.
