### ISSUE TITLE
There is no analytics event sent when a failure is received during installation

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6099]
Follow up for #5940 

STR:
1. Open your Firefox browser
2. Go to about:config and set `xpinstall.signatures.dev-root` to `false`
3. Go to AMO -dev and open the browser console
4. Install an extension
5. Observe the analytics events sent

Actual result:
There is no event sent mentioning the installation failure

Expected result:
An event that reports the installation failure should be sent

Notes:
- reproduced on AMO -dev with FF61, Win10x64

**Comment by bobsilverberg** [comment]
Quoting @willdurand from #5940:

> There is NO event sent when something wrong happens (failure/error). I am not sure what we want to track yet, so it should probably be moved to a new issue.

**Comment by bobsilverberg** [comment]
> Since the error triggered by the STR in the OP is the only reproducible error I can get, I am only sending a GA event for this error (i.e. download error).

Should we check with someone (I'm not sure whom) to make sure that this is in fact the only case we want to add analytics for?

**Comment by willdurand** [comment]
> Should we check with someone (I'm not sure whom) to make sure that this is in fact the only case we want to add analytics for?

Good idea, I'll open an issue if needed (and talk to @muffinresearch about it during our 1:1).

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

After a failed installation, a corrsponding event is sent.

Example:

```
sendEvent {"hitType":"event","eventCategory":"AMO Theme Installs Download Failed","eventAction":"statictheme","eventLabel":"rm static theme 3"}
```
