### ISSUE TITLE
User is not redirected to the Edit profile page after registering a new account

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6100]
STR:

1. Open AMO stage
2. Register a new user
3. After the account confirmation is processed, check the page you are redirected to

Actual result:
User lands on the page where the registration process started

Expected result:
User lands on the Edit profile page

Notes:
- reproduced only on stage and prod
- this was fixed already on -dev in https://github.com/mozilla/addons-frontend/issues/4376

![edit at register](https://user-images.githubusercontent.com/31961530/44784641-05c4e000-ab97-11e8-85eb-7d686be3580c.gif)

**Comment by bobsilverberg** [comment]
A similar issue, #4376, was dealt with via a patch for addons-server (https://github.com/mozilla/addons-server/pull/8297), so I've opened a similar one at https://github.com/mozilla/addons-server/pull/9311, but it could be that more than that should be done at this time. If that's the case we might want to re-file this on addons-server.
