### ISSUE TITLE
This add-on has been disabled by the administrator.

### ISSUE THREAD

**Issue by cybernetwebdesign** [mozilla/addons-frontend#6101]
{"detail":"You do not have permission to perform this action."}

Is my addon developer account banned?

I can't enter my developer account

**Comment by jvillalobos** [comment]
Please send an email to amo-admins AT mozilla DOT org and we'll help you there.

**Comment by jvillalobos** [comment]
It's the email address I included above. Sorry if that wasn't clear.

**Comment by cybernetwebdesign** [comment]
Okay, do you mean amo-admins@mozilla.org?

**Comment by EnTeQuAk** [comment]
Yes, that's correct.

**Comment by MightyPork** [comment]
Did you ever get your problem resolved?

I get this error after trying to log into the addons page, and my e-mail to amo-admins@mozilla.org has been ignored for over a month now :/

![Screenshot_20201205_205215](https://user-images.githubusercontent.com/2041118/101262037-dc169e00-373b-11eb-9edc-c00d9cac313b.png)
