### ISSUE TITLE
Reducers should not delete any object in state (this breaks the Redux devtool)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6102]
**For QA**: please check for regressions in the following features:
- Delete a collection
- Delete your user account

<hr>

When a reducer handles a deletion action, sometimes it does so with `delete`:

```js
case DELETE_A_THING: {
  const newState = { ...state };
  delete newState.byId[thingId];
  return newState;
}
```

This works for normal site usage but it breaks Redux time travel. You cannot go back in time to the previous state because all references to the old object have been removed. Going back in time will probably result in thrown error somewhere.

Here is a safe way to delete objects:

```js
case DELETE_A_THING: {
  return {
    ...state,
    byId: {
      ...state.byId,
      [thingId]: undefined,
    },
  };
}
```

Let's update all reducers.

**Comment by ioanarusiczki** [comment]
I tested for regressions on AMO dev with FF61 (Win10&Android8.0)
> Delete a collection
   Delete your user account
Delete works for both.
