### ISSUE TITLE
Delete my review and Delete my reply are not aligned with the other buttons

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6112]
STR:
1. Load AMO dev and go to the listed review page.
2. View the "Delete my review" button of your own review made for that add-on/theme.

Actual result:
The button is not aligned with "edit my review" and "flag".

Expected result:
All 3 buttons are aligned.

Notes:
This issue is also reproducible with Delete my reply - for a developer reply.
This is reproducible on AMO dev with FF61 (Win10&Android 8.0).

![not aligned](https://user-images.githubusercontent.com/33448286/44920080-b1ad2d80-ad47-11e8-8f83-13e65639e212.png)

![deletereply](https://user-images.githubusercontent.com/33448286/44920086-b40f8780-ad47-11e8-846c-384aeafa3e50.png)

**Comment by bobsilverberg** [comment]
I couldn't reproduce this locally on OS X with Firefox, but I can reproduce it with Chrome, so I guess there's something in the style that only works on Firefox on OS X. I'll need to experiment in Chrome to see if I can get it looking correct.
