### ISSUE TITLE
No add-ons shown when filtering by ALL on search page

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#6117]
### Describe the problem and steps to reproduce it:

On https://addons.mozilla.org/firefox/search/, when you sort Add-on Type and Operating System by ALL and uncheck Featured Add-ons Only, we return 0 searches.

### What did you expect to happen?

I expect to see all add-ons available on AMO, not 0 add-ons. So it seems we need a way to handle the situation where there is no query string.

![Imgur](https://i.imgur.com/VabPVSF.png)

**Comment by willdurand** [comment]
Looks like we've done that on purpose.

**Comment by atsay** [comment]
@jvillalobos ^

**Comment by jvillalobos** [comment]
We discussed in the frontend meeting and decided we should show all add-ons when there are no filters set.

**Comment by smayer97** [comment]
:-)

**Comment by ioanarusiczki** [comment]
I could no longer reproduce this issue on AMO dev - FF65(Win10). 
It happens while making a blank search and then changing Operating System to All ( the Add-on type is by default "All"). 

Before 
![before amo stage](https://user-images.githubusercontent.com/33448286/52867284-38fd2a80-3149-11e9-9529-1cfd619339ba.gif)

On AMO dev - problem fixed
![after amo dev](https://user-images.githubusercontent.com/33448286/52867302-49ada080-3149-11e9-9079-a988f2ba70c6.gif)
