### ISSUE TITLE
The install switch is sometimes jittery while installing a theme

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-frontend#612]
## steps to reproduce:
1. While pointing to dev, load Tools -> Add-ons
2. Install the Golden Butterfly theme
3. Uninstall
4. Repeat the steps 1 & 2 a few times and notice the install switch

## observed behavior:
The install button is jittery. See the screencast @ http://cl.ly/0B2E1V2b1u0A
If you install the theme 5 times, you can notice the jittery behavior at least twice.

[disco] [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Theme Installs","eventAction":"theme","eventLabel":"Golden butterfly_9"}(unknown)
[disco] Event received Object { type: "onInstalling", id: "362876@personas.mozilla.org", needsRestart: false }(unknown)
[disco] Event received Object { type: "onInstalled", id: "362876@personas.mozilla.org", needsRestart: false }(unknown)
[disco] Event received Object { type: "onDisabling", id: "{972ce4c6-7e08-4474-a285-3208198ce6…", needsRestart: false }(unknown)
[disco] Event received Object { type: "onDisabled", id: "{972ce4c6-7e08-4474-a285-3208198ce6…", needsRestart: false }(unknown)
[disco] Event received Object { type: "onEnabling", id: "362876@personas.mozilla.org", needsRestart: false }(unknown)
[disco] Event received Object { type: "onEnabled", id: "362876@personas.mozilla.org", needsRestart: false }(unknown)
[disco] [GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Addon / Theme Uninstalls","eventAction":"theme","eventLabel":"Golden butterfly_9"}(unknown)
[disco] Add-on found Addon { id: "362876@personas.mozilla.org", version: "", type: "theme", name: "Golden butterfly_9", description: "undefined", isEnabled: true, isActive: true }(unknown)
[disco] Requesting uninstall of 362876@personas.mozilla.org(unknown)
[disco] Event received Object { type: "onUninstalling", id: "362876@personas.mozilla.org", needsRestart: false }(unknown)
[disco] Event received Object { type: "onEnabling", id: "{972ce4c6-7e08-4474-a285-3208198ce6…", needsRestart: false }(unknown)
[disco] Event received Object { type: "onEnabled", id: "{972ce4c6-7e08-4474-a285-3208198ce6…", needsRestart: false }(unknown)
[disco] Event received Object { type: "onUninstalled", id: "362876@personas.mozilla.org", needsRestart: false }

**Comment by muffinresearch** [comment]
Can you still repro this?

What was the platform and FF version you were running?
