### ISSUE TITLE
Add more add-on info to UserReviewType

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6130]
We're going to need more add-on fields in `UserReviewType` to support #5858, and we're also going to need access to the `addon` object to support #6104 after #6108 lands, so I think the easiest thing to do would be to include `addon` in `UserReviewType`. 

I'm not sure if that might introduce caching issues, though, but I suppose we could have the same issues even if we just store the `name` and `iconUrl` of the add-on in the `review` object, so this seems like a reasonable approach to me.

@kumar303 I'm going to start working on this, unless you have any objections or better ideas.

**Comment by bobsilverberg** [comment]
Looking at this some more, I think maybe it's better to just store the data we need, and deal with the issue caused by #6108 in a different way. I might just make some changes to #6108 before it lands to address this.

**Comment by bobsilverberg** [comment]
Closing this as I think there's a better approach.

**Comment by bobsilverberg** [comment]
I'm re-opening this because I think we may have to do this, or if not this then we need to figure out how to solve the issue.

Based on the mockup at https://github.com/mozilla/addons-frontend/issues/5858#issuecomment-417794798, we need the add-on's name and icon for each review on the review listing on the User Profile page.

The API that returns this data to us only provides the add-on's `id` and `slug`, so we do not currently have access to this data when we need it. It seems like the best solution to this would be to also include the add-on's `name` and `icon_url` in the [review API response](https://addons-server.readthedocs.io/en/2018.05.17/topics/api/reviews.html#review-detail-object). If we don't do that they we'd have to look up that information ourselves which seems very inefficient.

I noticed also that we have a helper method, [`getAddonIconUrl`](https://github.com/mozilla/addons-frontend/blob/2018.08.28/src/core/imageUtils.js#L4), which accepts an `addon` object, but maybe we can just change that to accept either an `addon` object or just an `icon_url`, which would mean we wouldn't need to have an `addon` object inside the review object in order to call `getAddonIconUrl`.

@kumar303 Sorry, but I'm going to ping you again to ask your opinion about this and what approach you think would be best.

**Comment by kumar303** [comment]
I'd have to see it in the context of the patch to know for sure but I am a bit worried about storing `addon` on `review` objects because that will be one more thing to invalidate when fetching/updated/deleting add-ons.

**Comment by bobsilverberg** [comment]
I might not have been clear in the numerous comments I've made on this issue, but I do share your concern about storing the `addon` object in the `review` object and think it would probably be better to just store the data we need (i.e., name and iconUrl). I guess I was looking for confirmation of that, and I think I just got it.

**Comment by bobsilverberg** [comment]
Because I'm fairly sure that this is what we need to do, I've opened https://github.com/mozilla/addons-server/issues/9357 to request a change to the API. I realize that this will probably mean we need to update the reviews code to use v4 of the API, but I know that we want to start that upgrade pretty soon anyway.

**Comment by bobsilverberg** [comment]
For QA: Please verify that there are no regressions with any of the ratings and reviews functionality.

**Comment by AlexandraMoga** [comment]
I haven't noticed other regressions besides the issues we already know about.

Marking this as verified fixed on dev and stage.
