### ISSUE TITLE
Homepage content update 13 Septmber

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#6137]
For the **13 September** push, please update homepage programming in accord with details outlined [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
Verified it on AMO stage with FF62(Win10)
The "Fall-themes" and "YouTube boosters" are missing from AMO stage homepage On AMO dev they're available.

**Comment by bobsilverberg** [comment]
@ioanarusiczki I believe that you can create those collections on stage, which should unblock testing this on stage. Is that something you can do?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I created them from django admin pages. Looks better now.
Full validation will be made on prod.
