### ISSUE TITLE
Sometimes webpack does not reload/recompile after getting an error

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6139]
### Describe the problem and steps to reproduce it:

This is somewhat random (although it's happening more often)...

Sometimes after getting a local error, I see the following:
` ERR ~> http://127.0.0.1:3333/en-US/firefox/addon/acholi-ug-lp-test/ Error: connect ECONNREFUSED 127.0.0.1:3333`

and webpack never recompiles and I have to restart the server. Does this happen to anyone else??

### What did you expect to happen?
it would recompile and reload/restart so I don't have to restart the server manually

### Anything else we should know?

I looked into this a little bit and I came across this and I am wondering if the following will work:

See: https://github.com/webpack-contrib/webpack-hot-middleware#documentation 

if we add the reload (true) param to the hmr path?

**Comment by rebmullin** [comment]
did a little bit of testing and this doesn't fix the problem :/

Will keep looking into..

**Comment by willdurand** [comment]
It could be because webpack needs more time to recompile the app, especially after having saved a lot of files.

**Comment by bobsilverberg** [comment]
I have also been seeing this behaviour *a lot*. I spoke to @kumar303 about it last week, and tried to do some debugging, to see if another process was accessing any files belonging to the site and therefore causing webpack to continuously reload, but I didn't find anything. My (albeit naive) belief is that the webpack build is breaking somehow, so it never finishes recompliling, not that it is continuously reloading. 

I encounter this several times a day, and it would be nice if we could find a solution.

**Comment by kumar303** [comment]
> I have also been seeing this behaviour a lot ... and tried to do some debugging, to see if another process was ... causing webpack to continuously reload

@rebmullin didn't say anything about continuous reloading so maybe that's a different issue.

**Comment by kumar303** [comment]
> webpack never recompiles and I have to restart the server. Does this happen to anyone else??

I see it occasionally (yes, it is annoying) but it doesn't happen for every error. I'm not sure what's triggering it.

**Comment by bobsilverberg** [comment]
> @rebmullin didn't say anything about continuous reloading so maybe that's a different issue.

I think I must have just miscommunicated when I talked about it last week. I had no reason to believe that webpack was continuously loading, just that it was unable to respond to any requests.

**Comment by kumar303** [comment]
oh, sorry! OK, so, when I said I'd never seen that behavior I was totally lying. And all of the debugging tips I gave you were moot. D'oh.

**Comment by willdurand** [comment]
> Is it expected that that would break hot reloading completely?

No, but webpack and the server reload could be overloaded by too many "save" along with an error (which makes webpack recompiles more stuff than when there is no error).

**Comment by willdurand** [comment]
It is an empirical statement, I noticed that if I hit the save button a lot myself, it slows down webpack and the server (i.e. it takes more time to get the app UP again).

**Comment by bobsilverberg** [comment]
Fair enough, but in this case webpack never finishes successfully compiling the app, no matter how long I wait.

**Comment by willdurand** [comment]
When it occurs, can you try this command:

```
$ touch bin/server.js
```

and wait a bit before refreshing the page in your browser?

**Comment by rebmullin** [comment]
thanks for helping with this. I have been trying things too.. to no avail yet :/

unfortunately, I don't see `touch bin/server.js` doing anything. Maybe b/c this file already exists..?

**Comment by bobsilverberg** [comment]
I just had the issue again and tried `touch bin/server.js`. At first it didn't seem to work and then voila! I'll try it again next time to see if it works again.

**Comment by willdurand** [comment]
> I just had the issue again and tried touch bin/server.js. At first it didn't seem to work and then voila! I'll try it again next time to see if it works again.

I am asking because this command usually fixes a similar problem for me, but I want to be sure it is the same problem. If it is, then I'll be able to find a better fix.

**Comment by willdurand** [comment]
> unfortunately, I don't see touch bin/server.js doing anything. Maybe b/c this file already exists..?

Yep, the file does exist but `touch` also changes the last access time, which triggers the watcher to recompile the app.

**Comment by kumar303** [comment]
I ran into this again the other day and touching `bin/server.js` did fix it.

**Comment by willdurand** [comment]
I guess `touch bin/server.js` is a good enough workaround, so closing this issue for now.
