### ISSUE TITLE
mozAddonManager install features are not working on Android

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6141]
STR

1. Load AMO dev on Android
2. Install an extension
3. Observe the state of the 'Add to Firefox' button

Actual result:
'Add to Firefox' remains in the install state after the extension is successfully added

Expected result:
Install button changes to 'Remove' after an add-on is successfully installed

Notes:
- same behavior for all add-on types
- the button should also turn to 'Enable' if an add-on is disabled from addons manager
- reproduced on AMO -dev with Android 8.0, Nightly 63.0a1

![install android](https://user-images.githubusercontent.com/31961530/45084345-c4887f00-b106-11e8-8322-eb600c30db14.gif)

**Comment by willdurand** [comment]
Dumb question: is there a `mozAddonManager` on Android? And can we use it from -dev?

**Comment by AlexandraMoga** [comment]
@willdurand  they should have introduced it with https://bugzilla.mozilla.org/show_bug.cgi?id=1298178

**Comment by willdurand** [comment]
@AlexandraMoga I just tried on -dev and it is working for me, so I am confused.

**Comment by willdurand** [comment]
![amo-android](https://user-images.githubusercontent.com/217628/45171608-1e6e6f00-b203-11e8-9d62-3ae49e0edaff.gif)

**Comment by willdurand** [comment]
Note: it could be an issue related to #6152. Do you have the same issue if you refresh the add-on detail page?

**Comment by AlexandraMoga** [comment]
@willdurand it seems that I have forgotten to set `extensions.webapi.testing` = `true` when I configured Firefox for Android, so that's what caused my issue :disappointed:

With the right pref set, the install buttons are working as intended, which makes this issue is Invalid.

**Comment by willdurand** [comment]
awesome, thanks!
