### ISSUE TITLE
Develop mozAddonManager with example.com

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6143]
Currently, developing `mozAddonManager` features requires [building a custom Firefox](https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md) which is cumbersome and time consuming. Let's see if we can develop without a custom build of Firefox.

Instructions:

1. Build a dev server

```
NODE_APP_INSTANCE=amo NODE_ENV=dev yarn build
```

2. Run the dev server

```
NODE_APP_INSTANCE=amo NODE_ENV=dev USE_HTTPS_FOR_DEV=true SERVER_HOST=example.com yarn start
```

3. Make sure you are resolving `example.com` to your local server in `/etc/hosts`:

```
127.0.0.1   example.com
```

4. Create a Firefox profile and set the following prefs in `about:config` [per instructions](https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md#turning-on-mozaddonmanager-for-development):

```
extensions.webapi.testing = true
xpinstall.signatures.dev-root = true
```

5. Open https://example.com:4000/
6. Since this is a secure connection and we haven't installed certs into Firefox, you will have to ignore the cert warning.

Typing `navigator.mozAddonManager` into the JavaScript console on the page shows that it's available.

**TODO**

* [ ] get console logs to appear
* [ ] get the new install buttons to show up

**Comment by willdurand** [comment]
I took a different approach in https://github.com/mozilla/addons-frontend/pull/6210
