### ISSUE TITLE
Run A/B test for install button (green vs. blue)

### ISSUE THREAD

**Issue by shell1** [mozilla/addons-frontend#6144]
### Describe the problem and steps to reproduce it:

addons.mozilla.org product pages get ~4.3M views.  UX changes that improve add-on installation are high impact.   There was a [study done](https://mana.mozilla.org/wiki/display/FIREFOX/AMO+Optimization+for+Non-Firefox+Users+Landing+on+Add-on+Pages), that may have some correlations for ideas for the upcoming Product Page tweaks to drive engagement.  

The study looked for UX changes that improved engagement - specific to AMO pages visited from non-Fx browsers.   In that case the Action was to install Firefox (from non-Fx Browser), whereas users with Firefox we want them to install the add-on.  

### What happened?

Version B had ~10 times more engagement.  So highly worth testing out some of the relatable ideas in the new designs for both our AMO pages from Fx browsers and non-Fx Browsers.  @pwalm @atsay @jvillalobos 

Worth talking to Cmore - on who the UX and study folks were that tried the various UX components.  I think only one of the ideas in the study made it into the AMO pages from non-Fx browsers (the big green button).

### What did you expect to happen?
Data driven decisions on the page UX and content have helped fix the download button (big increase in engagement) and add TAAR to DiscoPane (0.8% increase in a user's probability to install overall, and a 1.2% increase for non-en-US users.  Users with TAAR retained 1% better than those without TAAR).

**Comment by atsay** [comment]
Product/UX discussions are currently happening.

**Comment by jvillalobos** [comment]
So... this boils down to making the installation button green. On one hand, research points to this being beneficial to conversions, and on the other there seems to be a hard rule in the design system to only use green for the Firefox install button.

I'd like to hear what UX have to say about this. /cc @pwalm @brassy-

**Comment by brassy-** [comment]
The study mention in Shell's first comment it's relative to the 'Get Firefox Now'.  **In none of the usability tests, we saw people having trouble to identify the CTA.**  

So, no, I don't think we should change the color of the button from blue to green in the product page.

**Comment by brassy-** [comment]
@jvillalobos would be possible to target an a/b test only on the product page?

**Comment by jvillalobos** [comment]
Yes, that's what I had in mind, too.

**Comment by jvillalobos** [comment]
We'll clarify with @shell1 next week, but I know that the green/blue question is what motivated this issue filing initially. It came up in a meeting we had earlier in the week.

**Comment by jvillalobos** [comment]
Okay, we talked this through today. Besides the button color, Shell wanted to know if the research recommendations were being taken into account for the new designs of the product page. UX confirmed they are, and that isn't something we need to track here.

This issue is now focused on running an A/B test for the Add to Firefox button, comparing the conversion rate between its current blue color, and the green color we use for the Get with Firefox button on non-Firefox browsers. I updated the subject to reflect that.

There's an open question about how much of the population we should show the green button for. @jenniferdavidson, do you have thoughts on that?

**Comment by willdurand** [comment]
> This issue is now focused on running an A/B test for the Add to Firefox button, comparing the conversion rate between its current blue color, and the green color we use for the Get with Firefox button on non-Firefox browsers. I updated the subject to reflect that.

So, we "just" want to A/B test the color of the install button (`AMInstallButton`), showing a green button for 50% of the traffic, and 50% will get the current button and sending click events to GA, correct?

1. do we want to change the color of the loading animation?

![](https://user-images.githubusercontent.com/31961530/46343264-e31a6100-c645-11e8-9484-af4ebed80ffc.gif)

2. Are we OK with splitting the traffic in half?

**Comment by shell1** [comment]
For question 1 - The color of the animation is fine to leave as it is, for both green and blue button.
For question 2 - @jenniferdavidson @jvillalobos @pwalm do any of you have a preference/guidance for the size/split of this test?

**Comment by jenniferdavidson** [comment]
As we talked about in the meeting, let's do 50/50 and make sure that the color contrast of the button compared to the background is the same for green and blue.

**Comment by pwalm** [comment]
Contrast ratio:
Blue: 5.6:1 (passes all but Normal AAA)
Green: 2.6:1 (fails all)

The Firefox download green on mozilla.org is 1.9:1 and also fails all.

**Comment by willdurand** [comment]
@pwalm do we want to change the green color globally then?

I am not sure to understand exactly why contrast ratio should be similar. If the user study revealed that the existing green was better, why not reusing it?

And what if the green color actually improves the contrast? (which might or might not be the case, but some tools show that we don't perform super well in some cases).

**Comment by pwalm** [comment]
Let's just leave it as is for now.

**Comment by willdurand** [comment]
**The experiment is only enabled in -dev**
