### ISSUE TITLE
fa-IR dictionary doesn't appear on Language Tools page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6145]
This dictionary doesn't appear in the [Language Tools](https://addons.mozilla.org/firefox/language-tools/) page: https://addons.mozilla.org/addon/lilak-persian-dictionary/.

The target locale was already set to `fa-IR`, and it can be seen in the Language Tools page in the old front end. There are two entries for Persian on the old page. The new one only has one for `fa`.

**Comment by willdurand** [comment]
I don't see this dictionary in the API response.

**Comment by diox** [comment]
I do. It has a `fa-IR` target_locale FWIW.

**Comment by willdurand** [comment]
I see it too now, I was not looking at the right API. I have added this add-on in -dev too, so that we have it for testing purpose.

**Comment by willdurand** [comment]
> The target locale was already set to `fa-IR`, and it can be seen in the Language Tools page in the old front end. There are two entries for Persian on the old page. The new one only has one for `fa`.

@jvillalobos what would you prefer: both tools under the same language (Persian) or one line for each language (Persian and Persian (Iran))?

**Comment by jvillalobos** [comment]
Not a strong preference, but two lines is better IMO.

**Comment by willdurand** [comment]
@jvillalobos ok, wfm. One more thing, I believe this lang pack should have "fa-IR" as target locale and not just "fa": https://addons.mozilla.org/en-US/firefox/addon/persian-ir-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-lang/

**Comment by jvillalobos** [comment]
Okay. I should update it after the next push, right? So it doesn't disappear temporarily from the list.

**Comment by willdurand** [comment]
> Okay. I should update it after the next push, right? So it doesn't disappear temporarily from the list.

Yes please

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

There are two dictionaries listed for Persian in the language tools list, including the missing one for `fa-IR`

![image](https://user-images.githubusercontent.com/31961530/46293677-dee63900-c59c-11e8-93a4-5a27148c1ccd.png)
