### ISSUE TITLE
Fix reducers/addons.js to discourage state mutation

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6147]
The case for `LOAD_ADDONS` in `reducers/addons.js` replaces keys in the state, which causes the same problems as deleting keys, as discussed at https://github.com/mozilla/addons-frontend/issues/6102.

We should rewrite the code in that case to avoid replacing the contents of keys.

**Comment by kumar303** [comment]
This specific reducer case looks like it's safe (so I reduced priority) but it's a dangerous pattern that can lead to accidental mutation. Rewriting the code using spreads and no assignments would be a good exercise and it's something we should strive for in the future.

Here is an example of why it's a dangerous pattern: https://github.com/mozilla/addons-frontend/pull/6108#discussion_r215660247

**Comment by arku** [comment]
@kumar303 I have attempted to fix this issue in https://github.com/mozilla/addons-frontend/pull/8206.

Please take a look when you get a chance.

Thanks!
