### ISSUE TITLE
Incorrect order + missing extensions when sorting by recently updated

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#6148]
### Describe the problem and steps to reproduce it:

1. Went to https://addons.mozilla.org/en-US/firefox/search/?sort=updated&type=extension.
2. Saw that [Markdown Viewer Webext](https://addons.mozilla.org/en-US/firefox/addon/markdown-viewer-webext/) was listed before [Read World Newspapers Online](https://addons.mozilla.org/en-US/firefox/addon/read-world-newspapers-online/)
3. Clicked through to their listing pages and found that the latter was published before the former.
4. Switch to the old AMO design and go to https://addons.mozilla.org/en-US/firefox/extensions/?sort=updated.
5. Compare with the list from step1. Notice that some extensions aren't listed in the new design even though they have had a recent update and are listed on the old design.

Screenshots: [imgur](https://imgur.com/a/fJPYPXI)

**Comment by jvillalobos** [comment]
> Saw that Markdown Viewer Webext was listed before Read World Newspapers Online

The sorting looks correct to me, now. Can you check again and see if the ordering changed for you?

> Notice that some extensions aren't listed in the new design even though they have had a recent update and are listed on the old design.

I can see that too, and I don't see any obvious reason they should be filtered out.

**Comment by willdurand** [comment]
that's probably a server issue.

**Comment by FatOrangutan** [comment]
>The sorting looks correct to me, now. Can you check again and see if the ordering changed for you?

They are indeed correctly sorted now, even though no new updates for either of them have been released since filing this issue.
The issue persists though: e.g. JIRA2Clipboard, released 3 hours ago, is listed before Hola Unblocker, released an hour ago.

Additionally, it looks like at least the sorting issue has little to do with the new frontend, because I can reproduce it on the old design itself - compare https://addons.mozilla.org/en-US/firefox/extensions/?sort=updated with https://addons.mozilla.org/en-US/firefox/search/?sort=updated&atype=1, both while on the old layout. Can't find an example of the other issue (extension missing on the new list) today so can't check.

**Comment by jvillalobos** [comment]
It sounds like there are two separate issues, and probably both on the server side. I'll get those filed and close this one.

**Comment by jvillalobos** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/9383. After looking into it a little more, it looks like both issues are the same one, since both seem to self-correct after some time.
