### ISSUE TITLE
AMInstallButton status is not updated

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6152]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-dev.allizom.org/en-US/firefox/addon/enhancer-for-youtube/ with a browser that has `mozAddonManager`
2. Click on the "Search by Image" add-on located in the "Other popular extensions"

### What happened?

The `AMInstallButton` (new button) is disabled:

![screen shot 2018-09-06 at 15 35 21](https://user-images.githubusercontent.com/217628/45160743-7ba9f680-b1ea-11e8-9483-beb1bc1203db.png)

### What did you expect to happen?

The button is NOT disabled.

### Anything else we should know?

Could be a regression related to #6094.

**Comment by willdurand** [comment]
Upgrading to p1 since this HOC is also used by the current/old install button, not sure it is affected but we never know :

**Comment by ioanarusiczki** [comment]
I verified this with FF64 (Win10) and FF62 (Android 8.0)  - on AMO dev 
I did not find the +Add to Firefox button disabled following the above scenario 

FF64 (Win10)
![new buttons](https://user-images.githubusercontent.com/33448286/45225597-9bfab380-b2c5-11e8-99ad-cca2ded51990.gif)

FF62(Android 8.0)
![android buttons](https://user-images.githubusercontent.com/33448286/45225614-a452ee80-b2c5-11e8-9475-2331a455be10.gif)
