### ISSUE TITLE
Format storybook existing components (button, badge)

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6159]
Currently we just have these 2 components set up - Button and Badge.

We should make it look something like described here:
https://github.com/mozilla/addons-frontend/pull/6060#discussion_r215322058

Check out addons to mentioned here to see if this makes it easier, etc

**Comment by kumar303** [comment]
My request was just to render all (or many) styles on one storybook page. This should make it easier in development when making changes to a component -- you could watch a single page as it auto-updates.

@willdurand suggested that these add-ons may do something similar:

- https://github.com/Checkfront/react-storybook-addon-chapters
- https://github.com/evgenykochetkov/react-storybook-addon-props-combinations

**Comment by rebmullin** [comment]
yep.. I'll check them out : )
