### ISSUE TITLE
Set up percy with storybook

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6160]
Start with a test account

**Comment by willdurand** [comment]
We should probably fix the other storybook issues before starting the work on this one.

**Comment by rebmullin** [comment]
yep this will come a bit later :)

**Comment by muffinresearch** [comment]
Following conversations with the Percy team last week, I'm going to check with them about the best way to go about this.

**Comment by muffinresearch** [comment]
Closing this, since we don't have any current plans to work on this.
