### ISSUE TITLE
After you submit a written review, the form does not close

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6162]
This is part of a new UX for reviews/ratings. See #5519

### Describe the problem and steps to reproduce it:

- Go to an add-on detail page
- Rate an add-on
- Click *Write a review* and enter some text
- Submit the review

### What happened?

The form stays open in edit mode

### What did you expect to happen?

The form should close and you should see your saved written review (https://github.com/mozilla/addons-frontend/issues/5943)

### Anything else we should know?

<img width="402" alt="screenshot 2018-09-06 22 56 06" src="https://user-images.githubusercontent.com/55398/45197664-107f1500-b228-11e8-9a01-a87ed853ef3d.png">

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF62, WIn10x64 and Android 8.0

The write a review form closes when selecting Submit or Update review buttons.

![close review form](https://user-images.githubusercontent.com/31961530/45550729-6b21fd80-b834-11e8-9e69-930af69c4ffb.gif)
