### ISSUE TITLE
The edit review link does not show an inline form

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6163]
This is part of a new UX for reviews/ratings. See #5519

### Describe the problem and steps to reproduce it:

- Go to an add-on detail page
- Rate an add-on
- Write a review and submit it
- View the saved review
- Click the *Edit my review* link in the lower left

### What happened?

The old overlay form is shown

### What did you expect to happen?

The new inline edit form should be shown

### Anything else we should know?

<img width="402" alt="screenshot 2018-09-06 22 14 05" src="https://user-images.githubusercontent.com/55398/45238452-7c549280-b2a7-11e8-9232-7d3ce3a03bc5.png">

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF62(Win10)

![the new inline form](https://user-images.githubusercontent.com/33448286/45627805-657a2100-ba9b-11e8-8f64-8ce92e851b70.gif)
