### ISSUE TITLE
Listen to `onOperationCancelled`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6164]
### Describe the problem and steps to reproduce it:

1. Install an add-on from AMO
2. Go to about:addons
3. Remove this add-on
4. Undo the removed add-on in about:addons
5. Close about:addons

### What happened?

Closing about:addons when the add-on is restored does not send any event, causing AMO -dev to not know the status of the add-on. In other words, the install button on AMO is in a "pending" state.

### What did you expect to happen?

The install button on AMO should not have a "pending" state.

### Anything else we should know?

We should listen to `onOperationCancelled` to update the state of the add-on, which will fix the button status.

Related issues:

- https://github.com/mozilla/addons-frontend/issues/562
- https://github.com/mozilla/addons-frontend/issues/3562
- https://bugzilla.mozilla.org/show_bug.cgi?id=1477155

**Comment by muffinresearch** [comment]
Isn't cancellation already listened to or is that some other event? For example cancelling a regular install by not accepting the permissions seems to work correctly.

**Comment by ioanarusiczki** [comment]
@willdurand This issue with https://github.com/mozilla/addons-frontend/issues/6227 are no longer reproducible on AMO dev - FF64(Win10)

![remove displayed](https://user-images.githubusercontent.com/33448286/46085007-abc33480-c1ad-11e8-9792-5cf8b2f5e7f1.gif)
