### ISSUE TITLE
Add smooth transitions to the AMInstallButton

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6165]
We should make the `AMInstallButton` look and feel slightly better by improving the transitions when the button switches from the "uninstalled" to "pending" to "installed" states.

Maybe this could be done with CSS transitions, I don't know yet.

**Comment by AlexandraMoga** [comment]
@willdurand  is there anything more specific to test here or checking that the install buttons are working as expected would cover enough?

**Comment by willdurand** [comment]
> @willdurand is there anything more specific to test here or checking that the install buttons are working as expected would cover enough?

I think it is enough. In theory, you should see a short animation when button changes.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62 and Nightly 64 with Win10x64 and Android 8.0.
