### ISSUE TITLE
Preload install animation (svg) to avoid a flicker on the very first time

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6169]
### Describe the problem and steps to reproduce it:

1. Go to a fresh add-on detail page
2. Install an add-on
3. Observe the animation

### What happened?

Sometimes (depending on the network), the SVG does not load the very first time or it is late because the SVG is downloaded when the animation is shown.

### What did you expect to happen?

No rendering issue.

### Anything else we should know?

Preloading the SVG will fix the issue.

**Comment by muffinresearch** [comment]
The animation needs a lot more work, but I played with trying to replicate this in a CSS animation here [1]. If the animation could be improved enough maybe that could remove the need for a large SVG sprite.

[1] https://jsfiddle.net/muffinresearch/9x7bshnz/35/

**Comment by willdurand** [comment]
Yep, if we can match the SVG animation. that would be a good idea to improve performances.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64 and Android 8.0

I couldn't see any flicker when I tried to install an add-on. I've used a fresh profile with no cache 

![install animation](https://user-images.githubusercontent.com/31961530/45366901-ab8d3b80-b5e8-11e8-9150-58905ae2c763.gif)
