### ISSUE TITLE
Use withRouter for AuthenticateButton so it gets a location prop

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6176]
**For QA**: Please check for regressions on the following pages: *TBA*

The `AuthenticateButton` requires a `location` prop which means every component that calls it must pass it a `location`. 

Let's use `withRouter()` instead so that it gets `history.location` automatically. 

This will allow us to remove prop drilling in a few components: `FlagReviewMenu`, `RatingManager`, `CollectionList`, and maybe others.

**Comment by willdurand** [comment]
Good idea!

**Comment by championshuttler** [comment]
On it!
