### ISSUE TITLE
Simplify how saved ratings are rendered

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6178]
This is part of a new UX for reviews/ratings. See #5519

### Describe the problem and steps to reproduce it:

- Go to an add-on detail page for an add-on you haven't rated
- Click a star to rate it

### What happened?

The rating is saved and you are presented with a screen like this:

<img width="402" alt="screenshot 2018-09-06 22 14 40" src="https://user-images.githubusercontent.com/55398/45236217-d69e2500-b2a0-11e8-85b4-064f0fab26e2.png">

### What did you expect to happen?

This should be simpler:

<img width="402" alt="screenshot 2018-09-07 13 17 29" src="https://user-images.githubusercontent.com/55398/45236258-f7ff1100-b2a0-11e8-9252-3de93c540d4b.png">

### Anything else we should know?

 
This is a follow-up to https://github.com/mozilla/addons-frontend/issues/5943

**Comment by vcarciu** [comment]
Verified as fixed(both desktop and Android) : 
![ratingsnew](https://user-images.githubusercontent.com/1583842/45366391-6c121f80-b5e7-11e8-95d1-76e976f73adb.gif)

One observation is that if an user delete his saved rating and then submit again a rating the "Request was throttled" message will appear and from my point of view this is not very user friendly.

@kumar303 : can we avoid somehow the "Request was throttled" message in this specific case described above? (after deleting and submitting again a rating)
