### ISSUE TITLE
Change the structure of home banner array so it can be mapped

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6179]
We want to do this so we can map through the array and return the React component from this. Also will help clean things up a bit:
https://github.com/mozilla/addons-frontend/pull/6157/files#r215910683

QA: make sure heroes are not broken and look the same on home page

**Comment by vcarciu** [comment]
Heroes looks good : 
![hero](https://user-images.githubusercontent.com/1583842/45359377-ff8e2500-b5d4-11e8-84d4-020c080ed0bf.gif)
