### ISSUE TITLE
Storybook has unmet peer dependency notice shows up when you run yarn install

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6181]
see this `@storybook/react@3.4.10" has unmet peer dependency "babel-runtime@>=6.0.0"`

storybook seems to work ok despite this issue.
I will look into this more to see if this is really an issue..

**Comment by willdurand** [comment]
duplicate of https://github.com/mozilla/addons-frontend/issues/6175?

**Comment by rebmullin** [comment]
Ok..missed that : ) Closing this in favor of #6175 then..
