### ISSUE TITLE
Remove componentWillReceiveProps calls (react upgrade)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6188]
See: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change

For QA: there should be no issue when navigating between pages (for example, when browsing multiple add-ons, refreshing a page, then navigating to some other add-ons linked on a page, etc.)

---

I filed issues for the following components:

- `Addon`: https://github.com/mozilla/addons-frontend/issues/6770
- `AutoSearchInput`: https://github.com/mozilla/addons-frontend/issues/6771
- `UserProfileEdit`: https://github.com/mozilla/addons-frontend/issues/6769

**Comment by ioanarusiczki** [comment]
@willdurand Release testing is completed, no new issues were noticed. 

Verified on AMO stage with FF63(Win10).
