### ISSUE TITLE
Add StrictMode component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6189]
See: https://reactjs.org/blog/2018/03/29/react-v-16-3.html#strictmode-component

**Comment by willdurand** [comment]
For QA: there should be no changes as it is only for local development. No logs in the console should mention strict mode or unsafe methods, or deprecated react methods.

**Comment by ioanarusiczki** [comment]
@willdurand Is this issue affecting all AMO pages or is there a more specific area we should focus while testing?

**Comment by willdurand** [comment]
> @willdurand Is this issue affecting all AMO pages or is there a more specific area we should focus while testing?

everything

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF62, FF64 (Win10)
