### ISSUE TITLE
Investigate ways to reduce the main JS bundle size (amo app)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6192]
The `amo` JS bundle gets bigger and bigger as we add more features. We use [bundlesize](https://github.com/siddharthkp/bundlesize) to fail a Travis CI build if the bundle gets too big given a threshold. The threshold has been increased in #6191 to avoid failing PRs but we should see if we can do anything to reduce the bundle size.

Various ideas: tree shaking, code-splitting, dead code elimination, babel-preset-env (and browserlist rules), ...

**Comment by diox** [comment]
Worth keeping this issue open to try to find a solution (might be a good candidate for our [Performance project](https://github.com/orgs/mozilla/projects/150)). We went from 400 KB to 475 KB limit in 2 years, this is only getting worse.

**Comment by diox** [comment]
From duplicate:
> Since we do Server Side Rendering and our JavaScript bundle is at the bottom of the pages, its size doesn't seem to have a huge negative impact on Core Web Vitals, but still, reducing that size would help performance in general - make the site more reactive for things that do depend on client-side JavaScript. So let's look at what we can do.

**Comment by willdurand** [comment]
See: https://github.com/mozilla/addons-frontend/issues/10171

**Comment by willdurand** [comment]
As of March 9, 2021, the JS bundle size is 385KB.

**Comment by willdurand** [comment]
I identified a kinda big dependency (especially given that it's only used once) in #10179. I am not sure what else we can do.

**Comment by willdurand** [comment]
I think we can close this issue now.
