### ISSUE TITLE
Users remain logged into AMO after deleting their account from FxA

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6193]
STR:

1. Log in to AMO
2. Go to Edit my Profile
3. Click on Manage Firefox accounts
4. Delete your account from FxA
5. Open AMO in a new Tab

Actual result:
The user is still logged in to AMO and is able to perform actions specific for logged in users

Expected result:
User should be logged out from AMO when the account is deleted from FxA

Notes:
- the user is not logged out after the AMO page is refreshed
- after logging out and trying to log back in with the same credentials, the account is not recognized (as expected)
- reproduced on AMO stage with FF62, Win10x64

![delete account](https://user-images.githubusercontent.com/31961530/45299912-aad7a500-b515-11e8-8448-7836720fa2c9.gif)

**Comment by eviljeff** [comment]
In mozilla/addons-server#7922 we were going to delete the AMO account after the FxA account was deleted but in the end it was decided that just messaging the user on the FxA side that they needed to take action themselves was enough and the issue was closed.
