### ISSUE TITLE
Make deploy builds more predictable with yarn.lock

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6194]
Related to #3034 

Currently, we do not use the `yarn.lock` file to download/install the dependencies in the `Dockerfile`, which means the build process does not rely on the `yarn.lock` file at all.

We should fix this by using the `yarn.lock` file when running `yarn install`.

For QA: both AMO and Disco Pane should be deployed without any problem (it will be either fine or completely broken).

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev. Both AMO and disco pane looks good.
