### ISSUE TITLE
Enable AMInstallButton in staging (amo only)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6198]
In order to enable the `AMInstallButton` (new install button) in -prod, let's start by enabling it in **-stage for AMO only** (not Disco Pane).

**Comment by ioanarusiczki** [comment]
I verified this issue for extensions, dictionaries, language packs, static themes and lw themes with FF62(Android 8.0) and FF64(Win10). 
I filed https://github.com/mozilla/addons-frontend/issues/6227 but I did not see other problems on AMO stage. 
Install/loading state/remove work as expected. Also Disabling from add-on manager and then clicking "Enable" from the add-ons detail page works.
