### ISSUE TITLE
Report a bug with an add-on instead of leave a negative rating

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6199]
### Describe the problem and steps to reproduce it:

As an add-on user, imagine you encounter a bug in the add-on. You might:
- Go to the add-on detail page
- Leave a one star rating
- Write a review about the bug

### What happened?

The developer gets penalized with a negative review

### What did you expect to happen?

The developer should get a chance to fix the bug. They may already have a support site or a bug reporting system designed for this.

### Anything else we should know?

We already link to the developer's support site on the detail page under *More information* but clicking this link may not be obvious if you first think to leave a negative rating. This issue is about discouraging negative ratings.

See https://github.com/mozilla/addons-frontend/issues/5519 for some ideas about this feature.

The current UX spec suggests to change the *Report this add-on for abuse* button to a generic *Report an issue with this add-on* button that will handle both cases. The UX for what happens when you click the button is TBA.

<img width="398" alt="screenshot 2018-09-10 12 53 53" src="https://user-images.githubusercontent.com/55398/45314960-c2546500-b4f8-11e8-914f-437d2b55dd53.png">

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-150
