### ISSUE TITLE
Create "loading" animation in CSS

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6207]
From: https://github.com/mozilla/addons-frontend/issues/6169#issuecomment-419372479

---

Let's try to recreate the SVG animation in plain old CSS to avoid a (rather) huge SVG to be loaded and animated in CSS. WIP at: https://jsfiddle.net/muffinresearch/9x7bshnz/77/

On IRC:

> Probably need to consider if it's possible to use other props to get hardware acceleration for that animation. height/width won't.

**Comment by muffinresearch** [comment]
This updated fiddle using scale in place of width/height for a smoother animation. https://jsfiddle.net/muffinresearch/aty2h61n/

It does still animate border-radius though.

**Comment by willdurand** [comment]
> It does still animate border-radius though.

Firefox devtools says all other animations are optimized, and I don't see a huge performance impact in the Performance tab. It slightly drops at the beginning but then it is quite good. The current JSON/SVG animation has the same issue.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF62, Win10x64 and Android 8.0

- from a visual perspective, there is no major difference observed compared tot he previous animation
![loading bubble](https://user-images.githubusercontent.com/31961530/46343264-e31a6100-c645-11e8-9484-af4ebed80ffc.gif)

@willdurand there are some differences in terms of the button size:

[1] mobile
![image](https://user-images.githubusercontent.com/31961530/46343463-76ec2d00-c646-11e8-9076-4d2a960c5190.png)

[2] medium screen size - the size of the animation expands more than the +Add to Firefox button

![animation medium screen](https://user-images.githubusercontent.com/31961530/46343751-76a06180-c647-11e8-95e8-a7f2c5449710.gif)


For the mobile case, I don't think the new size represents an issue but I'm not entirely sure about the medium size layout.

**Comment by willdurand** [comment]
> For the mobile case, I don't think the new size represents an issue but I'm not entirely sure about the medium size layout.

ah good catch, this is an issue. Can you file a new issue for the medium size?

**Comment by AlexandraMoga** [comment]
Filed #6482 for the medium size issue

I'm marking this issue as verified fixed on AMO dev with FF62, Win10x64 and Android 8.0
