### ISSUE TITLE
Upgrade to Babel 7

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6208]
That's not urgent but this should be done at some point. Babel 6 works well and B abel 7 does not have a lot of BC breaks, but it is not possible to upgrade directly, there are a few changes, including:

- renaming packages (from `babel-xyz` to `@babel/xyz`) in `package.json`, `.babelrc`, and webpack config files
- adopting [babel-preset-env](https://babeljs.io/docs/en/babel-preset-env), which is the recommended plugin for a while now. It means we should get rid of the ES2015 preset (deprecated anyway)

More info at: https://babeljs.io/docs/en/v7-migration

**Comment by hritvi** [comment]
@willdurand may I work on this issue?

**Comment by pranav1698** [comment]
@willdurand  I would like to work on this issue?

**Comment by willdurand** [comment]
@hritvi please go ahead, not sure it is an easy task though

**Comment by pranav1698** [comment]
I think that doing a simple bable upgrade using node and babel must solve the issue,
As I can also the dependencies and plugins have changed in `.bable.rc` and `package.json`

**Comment by hritvi** [comment]
@willdurand I have upgraded the babel version in my local but know the tests are failing at cloneDeep referenced [here](https://github.com/mozilla/addons-frontend/blob/master/tests/unit/helpers.js#L466).
Error:
`TypeError: Cannot read property 'cloneDeep' of undefined`

I am running the tests with this command `yarn test-coverage-once`
I have pushed my code [here](https://github.com/hritvi/addons-frontend/tree/upgrade_babel)
The changes re made using the command
```
npx babel-upgrade --write
yarn add --dev jest
yarn add --dev babel-jest 'babel-core@^7.0.0-0' @babel/core regenerator-runtime
```
Any insight into this would be helpful. Thanks :slightly_smiling_face:

**Comment by hritvi** [comment]
@willdurand I have updated the code. It is now [here](https://github.com/hritvi/addons-frontend/tree/Upgrade_babel7).
In this, I have changed `babel-register` to `@babel/register`. All the tests are passing except the one that are using cloneDeep referenced [here](https://github.com/hritvi/addons-frontend/blob/Upgrade_babel7/tests/unit/helpers.js#L455). 
Error:
```
 TypeError: Cannot read property 'cloneDeep' of undefined

      453 |     }
      454 |   }
    > 455 |   return Object.assign(configUtil.cloneDeep(config), params);
          |                                   ^
      456 | };
      457 | 
```

**Comment by willdurand** [comment]
@hritvi interesting, do you still have `configUtil` required? Did the `node-config` dependency version change?

**Comment by hritvi** [comment]
Yes configUtil is imported from the util function [here](https://github.com/hritvi/addons-frontend/blob/Upgrade_babel7/tests/unit/helpers.js#L6).
And `node-config` dependency has not been changed.

**Comment by AlexandraMoga** [comment]
@willdurand is there anything specific to be tested here?

**Comment by willdurand** [comment]
@AlexandraMoga if both AMO and Disco Pane work as intended, that's fine.

**Comment by ioanarusiczki** [comment]
Release testing results are here https://testrail.stage.mozaws.net/index.php?/plans/view/13844
Verified with FF63 (win10 & android 8.0)
