### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by atomsite66** [mozilla/addons-frontend#6222]
### Describe the problem and steps to reproduce it:

Link 404: https://addons.mozilla.org/ru/firefox/addon/roomy-bookmarks-toolbar/
Link from: https://addons.mozilla.org/ru/firefox/addon/smart-bookmarks-bar/

**Comment by jvillalobos** [comment]
That page was taken down by its developer. You can try asking the other one to remove the link, but there's nothing to fix on the site code.
