### ISSUE TITLE
The page footer is displayed briefly after an add-on rating/review is deleted

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6223]
STR

1. Log in to AMO -dev
2. Go to an add-on detail page
4. Rate the add-on
5. Delete your rating
6. Observe the page layout

Actual result:
When the review is deleted, the page footer is displayed for a brief moment during  refresh

Expected result:
The page footer should not be visible when the page is refreshed after a rating/review is deleted

Notes:
- I've seen this behavior also when I manually refreshed the add-on details page right after I submitted a rating, but the most constant way to reproduce this was with the delete part
- also reproduces on add-on reviews page
- I didn't see the issue happening on stage
- reproduced on AMO dev with FF62, Win10x64 and Android 8.0

[On smaller screen sizes the issue is more representative]
![delete review](https://user-images.githubusercontent.com/31961530/45421821-ef3e7e80-b696-11e8-9429-cbd936bbd8ba.gif)

**Comment by kumar303** [comment]
I can see how that might be a bit disorienting. It might be hard to fix, though.

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-151
