### ISSUE TITLE
The Edit Review and Delete Review options have different alignments on smaller screen sizes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6224]
STR:

1. Log in to AMO
2. Review an add-on (with text)
3. Refresh the page to see your written review
4. Observe the alignment of the Edit and Delete review links
5. Switch your locale to German to see the issue more properly

Actual result:
Edit review is aligned to the left while the Delete review is center aligned

Expected result:
The mentioned options should have the same alignment (centered looks better to me)

Notes:
- Also reproduced on the add-on reviews page
- reproduced on all AMO servers with FF62, Win10x64 and Android 8.0

[Addon details]
![image](https://user-images.githubusercontent.com/31961530/45422438-db941780-b698-11e8-944f-840c5cb12e5e.png)

[Reviews page]
![image](https://user-images.githubusercontent.com/31961530/45422444-e189f880-b698-11e8-98b2-e3450acf7d5a.png)

**Comment by kumar303** [comment]
Good catch. We should use center alignment for all of them.

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started.

**Comment by aditya81070** [comment]
I want to work this issue

**Comment by caitmuenster** [comment]
Hey @aditya81070, go for it! If you need any help, @ at the mentor in a comment. 

Happy bug fixing!

**Comment by caitmuenster** [comment]
Hey @aditya81070, are you still working on this bug? If not, I'll unassign it and let someone else pick it up.

**Comment by aditya81070** [comment]
Yes I am working on it. I was having health issues so I was not active. I
will submit a pull request till tomorrow.

**Comment by ekoeditaa** [comment]
Is this issue fixed yet? I checked on my local development setup and I don't see this issue. Both the options are justified with space between for smaller screen sizes and it is behaving that way.
Am I checking the wrong thing? Appreciate the help. Thank you!

**Comment by AlexandraMoga** [comment]
This looks fixed indeed. 

[Addon details]
![image](https://user-images.githubusercontent.com/31961530/48182786-34003200-e335-11e8-8a5b-77040230b972.png)

[Reviews page]
![image](https://user-images.githubusercontent.com/31961530/48182792-395d7c80-e335-11e8-9901-e678a7aa0703.png)
