### ISSUE TITLE
Failing to install Search Tools after creating a new FF profile 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6225]
STR:
1. Load AMO stage - and go to More click on Search Tools.
2. Try to install a search tools from the list (the install button will probably look as being inactive) but refreshing page will work.  You will notice that the search tool can be installed.
3. Create a new profile and go again in More click on Search Tools.
4. Try to install again a search tool from the list, click +Add to Firefox
5. Observe the page.

Expected results:
The search tools is installed without problems.

Actual results:
Page's layout is broken as displayed below and the search tool cannot be installed.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF62, FF64 (Win10, Mac OS X 10133)
 
The inactive button from step 2
![disabledinstallsearch](https://user-images.githubusercontent.com/33448286/45431024-66800c80-b6af-11e8-9355-cdbb342b127a.png)

The new profile issue 
![cannot install search tools](https://user-images.githubusercontent.com/33448286/45431058-7dbefa00-b6af-11e8-9bc0-2852b95a3d51.gif)

**Comment by willdurand** [comment]
I think the bug is caused by the new install button (`AMInstallButton`).

The new profile resets all prefs to their default values, hence the user with a new profile does not have access to `mozAddonManager`. Unfortunately, I missed this edge case (I added a fallback for themes, but not for opensearch add-ons...).

**Comment by willdurand** [comment]
Based on my previous comment, I am downgrading this issue from p1 to p2.

**Comment by willdurand** [comment]
Note: the first steps in the STR show a visual issue as well (button disabled). This cannot be reproduced with a old or new profile with the old install button. The problem comes from the new install button then, which does not go live this week.

**Comment by ioanarusiczki** [comment]
Tested it on AMO dev.
It is no longer reproducible with FF62 and FF64 (Win10).
