### ISSUE TITLE
Update AddonReviewManager to use RatingManagerNotification

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6236]
**For QA**: please check for regressions in the *Saving* / *Saved* notifications that are shown when you update a rating or review.

`RatingManagerNotification` was introduced via https://github.com/mozilla/addons-frontend/pull/6213, and while it's currently being used by `RatingManager` it should also be used by `AddonReviewManager`. It can be used to replace the code at https://github.com/mozilla/addons-frontend/blob/2018.09.13/src/amo/components/AddonReviewManager/index.js#L101-L111

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev with FF64(Win10), and Saving/Save is available on all pages when the rating is updated. Text can be edited too without issues.

![saving saved](https://user-images.githubusercontent.com/33448286/50909629-e8512e00-1434-11e9-8f94-295eacd656fb.gif)

**Comment by ioanarusiczki** [comment]
While testing for https://github.com/mozilla/addons-frontend/issues/5925 I've noticed an issue that I could not reproduce on AMO prod, looks like it's a regression https://github.com/mozilla/addons-frontend/issues/7355
