### ISSUE TITLE
Firefox Personas

### ISSUE THREAD

**Issue by littlegobbler** [mozilla/addons-frontend#6244]
### What happened?
Error message pops up.
### What did you expect to happen?
Access firefox personas files.
### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/gb-packers/https://addons.mozilla.org/en-US/firefox/addon/gb-packers/

![error](https://user-images.githubusercontent.com/43261726/45531828-8bfc3b80-b7bf-11e8-8edb-5a4c6f0f546e.gif)

**Comment by jvillalobos** [comment]
Is this is the link you intended to visit? https://addons.mozilla.org/en-US/firefox/addon/gb-packers/

I can access it fine. The one you pasted has the address copied twice, so that's why it doesn't work. Closing because there doesn't appear to be an issue.
