### ISSUE TITLE
Layout issues for review banner for some languages

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-frontend#6248]
Ref  issue #2056  and PR #6233 

After 6233 it looks like 
![screenshot_2018-09-14 lastpass add-ons fur android](https://user-images.githubusercontent.com/22130317/45546877-577a9500-b83c-11e8-9ab4-9c981397c00d.png)

Better to add some padding to blue button so it will be easy to read .

**Comment by championshuttler** [comment]
Hi @willdurand can we please reopen it ?

Thanks :smile:

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev - Win10 - I used the Responsive design mode for a screen of 320x480 px
When the language expands on the second row the padding is now wider - from 30.6 to 34 px

dev fix
![dev](https://user-images.githubusercontent.com/33448286/46951520-e1628b80-d090-11e8-94c1-814f80b9d607.png)

as it was before 
![stage](https://user-images.githubusercontent.com/33448286/46951530-ec1d2080-d090-11e8-8d25-293b8227d81e.png)
