### ISSUE TITLE
The installation process is interrupted if user navigates into a different tab

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6252]
Prerequisites:
This issue is only reproducible with extensions.webextPermissionPrompts true and usually add-ons with permissions that show the add/cancel dialog box when they're installed such as [this one](https://addons-dev.allizom.org/en-US/firefox/addon/magic-actions-for-youtube-test/?src=featured)

STR:
1. Load AMO dev and go to an add-on such as [this one ](https://addons-dev.allizom.org/en-US/firefox/addon/all-of-the-permissions/)
2. Click the install button. 
3. After the dialog box is opened don't click Add or Cancel. Just navigate into a different tab.
4. Return to the add-on and observe the page.

Actual result:
Installation process is no longer displayed.

Expected result:
Add or Cancel can be clicked and installation continues.

Notes:
This issue is reproducible on AMO dev with FF64(Win10). 
When the browser is minimized the issue is not reproducible. 

![no installation](https://user-images.githubusercontent.com/33448286/45556168-47b27f00-b843-11e8-97d1-77254e936840.gif)

**Comment by willdurand** [comment]
That's a browser behavior I believe. We cannot change that IMO.

**Comment by jvillalobos** [comment]
Seems like it's working as expected. You'll need to click on the button again to restart the process. The alternative would be to somehow make the popup persistent, which would need to be fixed in Firefox and probably isn't great UX.
