### ISSUE TITLE
The installation message should fade away after a while 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6253]
Prerequisites:
the extensions.webextPermissionPrompt pref must be set to false

1. Load AMO dev and go to an add-ons detail page and click Install
2. Observe that a confirmation window appears on the right top corner
3. Minimize the browser or navigate into a different tab

Expected result:
If the user won't click on the page or the "ok" the message fades away after a while. 

Actual result:
Message is still displayed.

Notes:
This issue is not reproducible with the old notification (webextPermissionPrompt is set to true). 
Reproducible on AMO dev with FF64(Win10). 

![message won t fade away until click](https://user-images.githubusercontent.com/33448286/45556907-12a72c00-b845-11e8-9a51-9d44fda4deaa.gif)

**Comment by willdurand** [comment]
I think this is intentional as it mimics the browser popup.

**Comment by willdurand** [comment]
I don't know what to think about that to be honest.

**Comment by willdurand** [comment]
ah wait, it is an AMO issue here because of the pref mentioned in the OP.

**Comment by willdurand** [comment]
> How so? That looks like a pref that turns platform code on/off [dxr.mozilla.org/mozilla-central/search?q=extensions.webextPermissionPrompts&redirect=true](https://dxr.mozilla.org/mozilla-central/search?q=extensions.webextPermissionPrompts&redirect=true)

With the pref set to `false`, Firefox does not display any dialogs (door hangers?). AMO has code to detect that and displays its own dialogs (that's why it is in the top right corner). The component for that is `InfoDialog` and we do not remove it after X seconds because: 1. it mimics the Firefox behavior, 2. we started to add timers and effects quite recently.
