### ISSUE TITLE
There is no error message displayed when an add-on fails to install with the new install buttons

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6261]
Follow up for #6240 

Prerequisites:
- open an unbranded version of Firefox
- set the following prefs:
`extensions.webapi.testing` =  `true`
`xpinstall.signatures.required` = `false`
`xpinstall.signatures.dev-root` = `true`
- optional pref:
`extensions.webextPermissionPrompts` = `false`

STR:

1. Load AMO dev
2. Search for an add-on that should fail to install - see https://addons-dev.allizom.org/en-US/firefox/addon/akan-spelling-dict-issue-6240/
3. Install the add-on

Actual result:
The add-on fails to install but there is no error message displayed

Expected result:
An error message should be displayed for every failed install attempt 

Notes:
- the reason why this drew my attention is that before the new install buttons, even on the configuration mentioned in the prerequisites, we used to receive an error when an add-on failed to install - i.e. a "corrupt" or "incompatible" message
- this scenario needs to be tested with an unbranded Firefox version, as the official version will always throw a "corrupt" message on -dev and stage because of the signatures 
- reproduced on AMO -dev and stage with FF62, Win10x64

![error on install](https://user-images.githubusercontent.com/31961530/45614289-b6751f80-ba71-11e8-86cb-ad375fa85bd8.gif)

**Comment by willdurand** [comment]
I can reproduce with a fresh profile. I get this error message in the logs and no prompt:

```
1537195209077	addons.xpi	WARN	Download of https://addons-dev.allizom.org/firefox/downloads/file/255648/akan_spelling_dictionary-0.9.1-typefix.xpi?src=dp-btn-primary failed: Error: Non-restartless extensions no longer supported(resource://gre/modules/addons/XPIInstall.jsm:647:13) JS Stack trace: loadManifestFromRDF@XPIInstall.jsm:647:13
```

I might be wrong but I believe it is a Firefox issue. We do not have control over the pop-ups.

**Comment by willdurand** [comment]
So, that's actually our problem.. Quoted from IRC:

> all the browser handles is the permission prompt and the post-install notification
> with mozAddonManager that is.  there shouldn't be any other browser-generated prompts with mozAddonManager

**Comment by willdurand** [comment]
@muffinresearch I assumed that all errors (and dialogs) would be handled by FF, but it turns out that it is not the case. I am not sure what we want to do here, but errors should be displayed by addons-frontend. I don't think we have UX for that.

**Comment by willdurand** [comment]
Actually, we have all the logic for that in Disco Pane, so I will just reuse that.

**Comment by willdurand** [comment]
Bumping priority because it would be nice to have error messages with the new install button.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, WIn10x64

https://addons-dev.allizom.org/en-US/firefox/addon/greek-spellchecking-dictionary/

![instal fail message](https://user-images.githubusercontent.com/31961530/45812616-ed00a380-bcd8-11e8-96b2-d00e7b3a9966.gif)

@willdurand I would propose, as a follow up, to improve the error message displayed, as in the current format it sounds a bit ambiguous.
