### ISSUE TITLE
update privacy policy link on Disco Pane

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#6264]
@devaneymoz refiled from mozilla/addons-server#9400

At the bottom of the "Get Add-ons" page in the Add-ons Manager (Disco Pane), the Privacy Policy links to an incorrect destination. 

Currently it links here:
https://www.mozilla.org/privacy/websites/

Per Mozilla Legal, it should link here:
https://www.mozilla.org/privacy/firefox/#addons

@muffinresearch

**Comment by muffinresearch** [comment]
As per the discussion in mozilla/addons-server#9400 an upstream bug has been filed to fix the issue with the proposed link in that it shows no information without a user interaction. See mozilla/bedrock#6164 for details.

**Comment by muffinresearch** [comment]
@devaneymoz the mozilla.org people are saying it will take some time to fix the link on their side, do we want to wait until they fix it or make this change anyway?

My question for legal would be are we covered by words that are not visible without the user knowing to click a heading?

**Comment by devaneymoz** [comment]
@muffinresearch I spoke with Legal and they're fine to hold on making any changes to Disco Pane until the new page is properly constructed. So, waiting is fine.

**Comment by willdurand** [comment]
@muffinresearch this has been stuck for a while now, and upstream project maintainers don't reply :(

**Comment by willdurand** [comment]
Got an update in https://github.com/mozilla/bedrock/issues/6164, looks good to go now!

**Comment by ioanarusiczki** [comment]
I verified the new Privacy Policy link on AMO dev Disco Pane with FF63 (Win10)
The new page redirects to https://www.mozilla.org/en-US/privacy/firefox/?utm_content=privacy-policy-link&utm_medium=firefox-browser&utm_source=discovery.addons.mozilla.org#addons and lands on the Add-on section of the page (as mentioned [above](https://github.com/mozilla/addons-frontend/issues/6264#issue-360859054))

![new privact policy page](https://user-images.githubusercontent.com/33448286/48067227-67797a00-e1d8-11e8-819b-069dc8ee5f49.gif)
