### ISSUE TITLE
A/B tests should be controlled by config flags

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6274]
The A/B test for the hero page doesn't currently have a config flag. One should be added since this will make it easier to enable in various envs as well as ensuring if we need to turn it off it's easy to do so.

**Comment by ioanarusiczki** [comment]
@willdurand Could you provide some STR for qa or mark it with "qa not needed"
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki you should see the Home Hero experiment in -dev but it should not be enabled in -stage. I think checking that there is no cookie (`experiment_home_hero`) is enough.

**Comment by ioanarusiczki** [comment]
I checked it - AMO dev and AMO stage - FF62(Win10). 

On AMO dev - new banners + cookie 
![cookie](https://user-images.githubusercontent.com/33448286/45758735-fcc3ad80-bc2e-11e8-8172-f43a934cc7f2.png)

On AMO stage - no cookie available and the old banners are still displayed
