### ISSUE TITLE
Redirect user profile URLs using user id to the canonical variant using username

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#6275]
### Describe the problem and steps to reproduce it:
- Visit https://addons.mozilla.org/en-US/firefox/user/4757633/

### What happened?
- The page loads directly

### What did you expect to happen?
- The client should be redirect to the canonical URL using the username instead of the user id, which is https://addons.mozilla.org/en-US/firefox/user/mozilla/

### Anything else we should know?
- We do that for add-ons already: https://addons.mozilla.org/en-US/firefox/addon/954390/ redirects to https://addons.mozilla.org/en-US/firefox/addon/facebook-container/

**Comment by eviljeff** [comment]
Didn't we do this already? #5594

**Comment by diox** [comment]
We support the URLs, but they should redirect instead of loading the page directly.

**Comment by willdurand** [comment]
Hi @suhailsinghbains, feel free to take it! We already have a similar redirect here: https://github.com/mozilla/addons-frontend/blob/e1d2c4001131c9105ae349796558fce60124e09a/src/amo/pages/SearchPage/index.js#L92-L99

**Comment by suhailsinghbains** [comment]
Thanks for assigning me @willdurand 
Working on it now.

**Comment by caitmuenster** [comment]
Mentor: @diox

**Comment by eviljeff** [comment]
Note mozilla/addons-server#8302 that requests doing this in reverse.  imo we should pause this until that issue has been resolved, or just implement the username -> user-id redirect now instead.

**Comment by diox** [comment]
Also I'm not the right mentor for this (I guess I could do it, but it's best to have a more frontend oriented engineer do it)

**Comment by willdurand** [comment]
@suhailsinghbains no, I believe we can do what @eviljeff suggested, that is: redirecting username -> user-id.

**Comment by suhailsinghbains** [comment]
Oh, okay.
Working on it right away!

Thanks

**Comment by willdurand** [comment]
@suhailsinghbains it is basically inverting a condition in your current PR :)

**Comment by caitmuenster** [comment]
@suhailsignhbains Hey there! How's it going with this bug?

**Comment by willdurand** [comment]
@caitmuenster it is going well (more or less done) but there is more work to do before we can get his PR merged..

**Comment by willdurand** [comment]
Closing this issue in favor of https://github.com/mozilla/addons-frontend/issues/6915.
