### ISSUE TITLE
Add flow types to Addon disco component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6294]
Supports #2917 

---

In order to make the disco pane code easier to update (and more readable), we should have more flow coverage. This issue is about adding flow types to the `Addon` disco component.

**Comment by willdurand** [comment]
For QA: please make sure add-ons listed on Disco Pane have all the information (icon, description) and can be installed.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF64 - Win10

![disco pane -dev](https://user-images.githubusercontent.com/33448286/46077368-482f0c00-c199-11e8-848d-ce9b0169d828.gif)
