### ISSUE TITLE
Qwant Junior Addon not available

### ISSUE THREAD

**Issue by stillcut** [mozilla/addons-frontend#6296]
### What happened?

The page for Qwant junior Addon is unavailble

### What did you expect to happen?

Acces to the download of Qwant Junior Addon

### Anything else we should know?

The link should be : https://addons.mozilla.org/fr/firefox/addon/qwant-junior/

**Comment by jvillalobos** [comment]
The add-on has been taken down due to pending code review issues. It should be back up once the developer addresses them.
