### ISSUE TITLE
27 September homepage content update 

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#6302]
Please update homepage content for the **27 Sept** push as detailed in the programming [doc](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by bobsilverberg** [comment]
@devaneymoz The changes listed for the Hero element are not accurate. You say to keep a number of add-ons, and to not remove any add-ons, but I see add-ons in the current component which are not in the "keep" list. So either the "keep" list is inaccurate or the "remove" list is inaccurate.

Can you please double check your document?

**Comment by devaneymoz** [comment]
@bobsilverberg you're right, sorry about that! I failed to carry over the previous update's content into the "keep" list. I've adjusted the doc.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev
