### ISSUE TITLE
Add a route for /addon/:addonSlug/reviews/:reviewId/

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6303]
We landed a patch which implements a new page at `/addon/:addonSlug/reviews/:reviewId/`, so we need a new nginx route for it. It has landed on dev and will go to production tomorrow (Sept. 20).

Please let me know if there are any questions or concerns.

**Comment by willdurand** [comment]
With or without trailing slash?

**Comment by bobsilverberg** [comment]
Oops, with a trailing slash. I will update the description.

**Comment by bqbn** [comment]
The change has been applied to -dev and -stage. Please test.

**Comment by willdurand** [comment]
Is this in production yet? Can we close it?

**Comment by bobsilverberg** [comment]
Seems to be present in production.
