### ISSUE TITLE
When I want to add a new theme to my collection after I have signed in it doesn't let me. 

### ISSUE THREAD

**Issue by lisaann51** [mozilla/addons-frontend#6304]
I get an error message: 

> Server Error  Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it. Suggested Pages      Browse all extensions     Browse all themes     Add-ons Home Page  If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it.

**Comment by kumar303** [comment]
Hi, thanks for the bug report. Sorry you are having trouble. What is the URL for the theme you were trying to install? What is the name?

**Comment by lisaann51** [comment]
here is the Autumn Morning Serenity by MaDonna – Add-ons for Firefox
I can't even get into my ones I have saved in my collections



 Lisa 

 

| 
| 
|  | 
Autumn Morning Serenity by MaDonna – Add-ons for Firefox


 |

 |

 |



   On Wednesday, September 19, 2018, 12:21:58 PM PDT, Kumar McMillan <notifications@github.com> wrote:  
 
 
Hi, thanks for the bug report. Sorry you are having trouble. What is the URL for the theme you were trying to install? What is the name?

**Comment by kumar303** [comment]
Thanks for the additional info. The theme you mentioned is this one: https://addons.mozilla.org/en-US/firefox/addon/autumn-morning-serenity/

I see some add-to-collection errors possibly related to this add-on but the messages are generic. I need to solve https://github.com/mozilla/addons-frontend/issues/6352 to get a clue as to where they are happening.

**Comment by willdurand** [comment]
@kumar303 did you get a chance to look at it?

**Comment by kumar303** [comment]
@lisaann51 could you try to add it to your collection again? Next time you encounter the error we will have more diagnostics.

**Comment by lisaann51** [comment]
I just tried it isn't letting me do anything. 



 Lisa 

    On Wednesday, October 17, 2018, 2:50:52 PM PDT, Kumar McMillan <notifications@github.com> wrote:  
 
 
@lisaann51 could you try to add it to your collection again? Next time you encounter the error we will have more diagnostics.

**Comment by lisaann51** [comment]
This is what happens when I sign in.

Server Error
Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.

Suggested Pages
   
   - Browse all extensions
   - Browse all themes
   - Add-ons Home Page

If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it.




 Lisa 

    On Wednesday, October 17, 2018, 2:50:52 PM PDT, Kumar McMillan <notifications@github.com> wrote:  
 
 
@lisaann51 could you try to add it to your collection again? Next time you encounter the error we will have more diagnostics.
