### ISSUE TITLE
Hide edit link when confirming review deletion

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6305]
STR:
- Select a star to rate an add-on
- Write a review and submit the review
- Click *Delete my review* to open the confirmation screen.

You see this:

<img width="358" alt="screenshot 2018-09-19 14 42 51" src="https://user-images.githubusercontent.com/55398/45777040-4d7cdb80-bc1a-11e8-96e3-f10ff9ec59e9.png">

...but the *Edit my review* link should be hidden.

This came up as feedback in a recent UX meeting.

**Comment by ioanarusiczki** [comment]
This is not reproducible anymore - verified on AMO dev with FF62 (Win10&Android 8.0)

![no edit available while deleting](https://user-images.githubusercontent.com/33448286/46877132-cd2c4d80-ce48-11e8-922b-47a9dc713fce.gif)
