### ISSUE TITLE
Clicking a review permalink reloads the entire page

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6306]
### Describe the problem and steps to reproduce it:

- Find an add-on with more than one review
- Click *Read reviews* to see the list
- Click on the timestamp of any review to see its detail page

### What happened?

The whole page gets reloaded in the browser

### What did you expect to happen?

Just like for other internal links, the page should not reload. 

### Anything else we should know?

The appearance will be the same but not reloading is important to keep the site fast and responsive.

**Comment by willdurand** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/6289?

**Comment by kumar303** [comment]
Indeed. Whoops.
