### ISSUE TITLE
After rating, immediately show the review form (A/B test)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6308]
### Describe the problem and steps to reproduce it:

- Sign in
- Go to an add-on you've never rated
- Select a star to enter a rating

### What happened?

You see a *Write a review* button

### What did you expect to happen?

You should see a review entry form immediately

### Anything else we should know?

We have a hypothesis that the *Write a review* button will discourage people from actually writing reviews and immediately showing a review entry form will encourage them to write reviews.

We should A/B test both scenarios to see if the hypothesis is correct.

When showing the form immediately, the UI must clearly indicate that the star rating has been saved.

Here are some goals to keep in mind:
- Rating an add-on should be easy! You shouldn't have to worry about writing a review.
- If a user wants to write a review, we should help them do so because written reviews are more helpful to developers.

**Comment by kumar303** [comment]
Before starting on it, let's take a look at the database to see if we got a meaningful drop off of written reviews or not. If so, this experiment would be worth pursuing.

**Comment by willdurand** [comment]
@kumar303 With reviews moving to FF, is this issue still relevant?

**Comment by kumar303** [comment]
I am not clear on how reviews would fully move into FF (I haven't seen a proposal for this). There is a use case of reviewing an add-on while not using Firefox which seems important to me, especially on iOS for example.
