### ISSUE TITLE
The tooltip text for the a developer response permalink should be 'Go to this reply'

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6312]
Follow up for #2771 

STR:

1. Log in to AMO stage with a developer account
2. Go to your profile page
3. Scroll down to the user reviews section and locate a developer reply (leave one now if you don't have any)
4. Hover over the permalink next to your developer response
5. Observe the tooltip text

Actual result:
The tooltip text is 'Go to this review'

Expected result:
The tooltip text is 'Go to this reply'

Notes:
- reproduced on dev and stage with FF62, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/45802335-33490900-bcbf-11e8-8875-7234025f5b98.png)

**Comment by bobsilverberg** [comment]
Yes, we should fix this, although I think it's fine as a P3.

**Comment by shristit** [comment]
Hello everyone i would like to work on it , can any one help me how to get started ?

**Comment by shristit** [comment]
Hi @kumar303 @AlexandraMoga is this issue still available , i am unable to find this line in code

**Comment by shristit** [comment]
I think in #6285, the tooltip is removed https://github.com/mozilla/addons-frontend/pull/6285/files#diff-8ac5e13d9f69883f4468abd7d2787b98L226

**Comment by AlexandraMoga** [comment]
@bobsilverberg are tooltips coming back for permalinks (reviews and replies), or are we going to stick to not showing a tooltip at all?

There is no tooltip displayed anymore for dev replies or user reviews:

![no tooltip](https://user-images.githubusercontent.com/31961530/46341095-02ae8b00-c640-11e8-976a-217f3542f26a.gif)

**Comment by bobsilverberg** [comment]
@AlexandraMoga I don't think that was intentional. We should bring the tooltip back.

**Comment by AlexandraMoga** [comment]
I have filed #6485 to cover the tooltip issue as the STR are slightly different than in this case.

**Comment by caitmuenster** [comment]
Hey @shristit -- this isn't a good first bug because this is going to be covered by the other bug that was opened. 

Want to take a look at another good first bug instead?
