### ISSUE TITLE
Fix discoResults state

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6314]
Supports #2917 

---

In order to make the disco pane code easier to update (and more readable), we should have a better state for the `discoResults` reducer. Currently, this reducer has a non-object state (array), which makes it difficult to add new properties to the state.

This issue is about changing the state shape from array to object.

For QA: please make sure Disco Pane still lists the add-ons as usual.

**Comment by ioanarusiczki** [comment]
This was previously verified for https://github.com/mozilla/addons-frontend/issues/6318 https://github.com/mozilla/addons-frontend/issues/6292 and https://github.com/mozilla/addons-frontend/issues/6294
Marking it verified fixed on AMO dev with Ff62 and FF64 (Win10)
