### ISSUE TITLE
Buttons are no longer highlighed when clicked on AMO dev 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6320]
Followup for https://github.com/mozilla/addons-frontend/issues/6176
STR:
1. Load AMO dev and log in
2. Observe the button when it's clicked

Expected result:
Button is highlighted - has a light blue border

Actual result:
Button won't show the active state when clicked - no light blue border

Notes:
Issue is reproducible on AMO dev with all buttons - tried the new install buttons, the log in to rate an extension button , log in to edit profile button - with FF62, FF64 (Win10)
This issue is not reproducible on AMO stage and AMO prod.

AMO dev 
![dev](https://user-images.githubusercontent.com/33448286/45805337-32b47080-bcc7-11e8-84e9-7eccd929c8a4.gif)

AMO stage
![stagenow](https://user-images.githubusercontent.com/33448286/45805388-54adf300-bcc7-11e8-8d80-695ac70cf597.gif)

**Comment by willdurand** [comment]
This change has been introduced in #6251 on purpose. There is no "active" (light blue border) style on click, but it should be shown when navigating with the keyboard.

**Comment by ioanarusiczki** [comment]
@willdurand Oh, so no more highlights for mouse clicking.  Ok, good to know!
