### ISSUE TITLE
The incompatibility banner for non-restartless addons is not very suggestive

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6323]
Follow up for #6240 

STR:

1. Go to AMO -dev
2. Open a non-restartless add-on detail page - https://addons-dev.allizom.org/en-US/firefox/addon/akan-spelling-dict-issue-6240/
3. Check the incompatibility banner

Actual result:
The banner says that  the add-on is not compatible with the user's platform

Expected result:
The  banner should say that the add-on is not compatible with the Firefox version used by the user

Notes:
- reproduced on AMO dev and stage with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/45815762-4e794000-bce2-11e8-9cbe-2454251de554.png)

**Comment by shristit** [comment]
Hello everyone i would like to work on it , can any one help me how to get started ?

**Comment by kumar303** [comment]
Hi @shristit , thanks for your interest! I don't see any existing commits from you so I suggest looking at the [good first bug](https://github.com/mozilla/addons-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22) list and starting with one of those. That will help you get familiar with the project and how the contribution process works by tackling a smaller problem. Welcome!

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/45950492-b2fd0d80-c008-11e8-9aa1-a4deb55b3706.png)
