### ISSUE TITLE
Create explicit API data mappings (i.e. replace normalizr) for Disco Pane

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6328]
We use magical schemas (via [normalizr](https://github.com/paularmstrong/normalizr)) to store API data in a mappable format. Sometimes this helps look up objects better but other times we have code that *unmaps* it entirely.

Instead of using `normalizr`, let's just map what we need explicitly in our reducers. It might require more code but the mapping logic will be a lot easier to follow. This is what our reducers are for!

---

Let's do this for Disco Pane!

For QA: please make sure the Disco Pane works as expected (listing of add-ons, installs)

**Comment by ioanarusiczki** [comment]
@willdurand The display and install works for me. - verified on FF62 and FF64 with AMO dev - Win10
For what I've noticed I filed a separate issue here https://github.com/mozilla/addons-frontend/issues/6524
