### ISSUE TITLE
Minor tweaks to buttons and links in review flow

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6346]
When leaving a review or rating, here are some minor tweaks requested by @pwalm 

- Simplify prompt to *How are you enjoying **[add-on]***?
- Rename button to Cancel
- Change color of Delete rating link 
- Drop the *My* in *Edit My Review* so that it becomes *Edit review*. This also applies to deletion prompts and edit reply prompts.

Mock for reference:

![ratings and reviews flow v2](https://user-images.githubusercontent.com/55398/45894152-2f86b680-bd93-11e8-9a92-5c693887c8a9.png)

**Comment by championshuttler** [comment]
Hi @kumar303 , i would like to work on it , can i take this up?

**Comment by kumar303** [comment]
Hi @championshuttler, thanks for offering to help. If an issue is not labelled with [contrib: welcome](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) or [good first bug](https://github.com/mozilla/addons-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22) then it's not available to work on. This is because the other issues are either complex or are in our critical path for completion. It would not fair if we asked you to dedicate yourself to an issue in the critical path.

**Comment by pwalm** [comment]
Updated screens:
![ratings and reviews flow v3](https://user-images.githubusercontent.com/6797635/45907136-a2039080-bdab-11e8-98ec-a11d3e98904d.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg  Verified this on AMO dev with FF62 - Win10&android 8.0
@pwalm 's mock shows the Edit and Delete like both being on the right side of the written review.
On AMO dev  Edit is on the left and Delete on the right on both Windows and Android platforms

![edit delete](https://user-images.githubusercontent.com/33448286/46352182-d60b6b00-c661-11e8-964d-74f1ed7899f9.png)

**Comment by bobsilverberg** [comment]
> @pwalm 's mock shows the Edit and Delete like both being on the right side of the written review.

Yes, we didn't address that aspect yet.
