### ISSUE TITLE
Simplify the confirmation screen for deleting a review / rating

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6347]
~~Depends on #6454~~

Here is how to see the current deletion prompts:

- Sign in
- Go to an add-on detail page
- Rate the add-on
- Click *Delete rating*
- Or ... Write a review
- Click *Delete review*

The screens for each of these should be simplified. Here is an example (below) but check Sketch for an up to date version.

## Known issues

* The stars will be made smaller according to the mocks in https://github.com/mozilla/addons-frontend/issues/6577
* When deleting a review, the prompt at the top of *Rate your experience* will be added in https://github.com/mozilla/addons-frontend/issues/6577
* @pwalm called for underlining all control links (*Edit*, *Delete*, *Flag*, etc) for accessibility but the mocks have not been updated to show this yet
* We intend to always show the *Report this add-on for abuse* button even though it's not in the mocks. See https://github.com/mozilla/addons-frontend/issues/6307#issuecomment-426713063
* The *Edit review* and *Delete review* links are not aligned to the right (like the mock) because the card size is very small. This needs more discussion which will happen in https://github.com/mozilla/addons-frontend/issues/6403

![ratings and reviews flow v2](https://user-images.githubusercontent.com/55398/45894396-ceabae00-bd93-11e8-9b44-cdb7bc82eb2e.png)

**Comment by bobsilverberg** [comment]
> Here is an example but check Sketch for an up to date version.

@kumar303 / @pwalm I looked in the Sketch file but cannot find anything like this anywhere? Are they there and I'm just not looking in the correct place?
