### ISSUE TITLE
Enable the inline review flow in production

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6349]
We have a new review writing / editing flow where the form appears inline as opposed to an overlay. See this for a screencast: https://github.com/mozilla/addons-frontend/pull/6231

Let's turn this on in production by enabling its config flag after these issues are closed:

* ~~https://github.com/mozilla/addons-frontend/issues/6300 : The review form should not be left open when switching pages~~
* ~~https://github.com/mozilla/addons-frontend/issues/6345 : Simplify the 'Rating saved' notification~~
* ~~https://github.com/mozilla/addons-frontend/issues/6346 : Minor tweaks to buttons and links in review flow~~
* ~~https://github.com/mozilla/addons-frontend/issues/6271 : The previous text is displayed after changing the star rating~~

These will be the next issues we follow up with after enabling the flow:
* https://github.com/mozilla/addons-frontend/issues/6347 : Simplify the confirmation screen for deleting a review / rating
* https://github.com/mozilla/addons-frontend/issues/5986 : The star breakdown doesn't always update after submitting a rating

**Comment by pwalm** [comment]
Most recent mock up for reference:
![ratings and reviews flow v3](https://user-images.githubusercontent.com/6797635/45907297-44237880-bdac-11e8-852a-c1780b894b0e.png)

**Comment by bobsilverberg** [comment]
Note that landing this should fix #6414 and #6417.

**Comment by kumar303** [comment]
We decided to push this out early, before all issues are fixed. This is because there are some bugs in production related to all of the recent code changes and enabling the new flow will fix them.

We will enable the inline review flow on Thursday 2018-10-04.
