### ISSUE TITLE
Something other than 'not found' when all that's required is a log in

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#6359]
Maybe related: 

- [The links to see a user profile are not working anymore · Issue #6118 · mozilla/addons-frontend](https://github.com/mozilla/addons-frontend/issues/6118)

> … we only display developer user profiles now (and your own profile). …

Whilst logged out: 

- https://addons.mozilla.org/user/grahamperrin/ is reportedly not found
- https://addons.mozilla.org/user/PixelGiant/ shows extensions but not reviews.

Side note: for the logged out view of my profile, or for the logged-out view of PixelGiant reviews: 

- switch to classic desktop view. 

After logging in: 

- https://addons.mozilla.org/user/grahamperrin/ describes me as an _Add-ons developer_ which really, I'm not; and displays my reviews
- https://addons.mozilla.org/user/PixelGiant/ continues to not show reviews if restricted to the new view. 

### Enhancement request

For content that does exist, the 'not found' message is confusing, misleading. 

Better to present a suitably-worded prompt to log in.

**Comment by jvillalobos** [comment]
User pages are now dedicated to show developers and their extensions, and for users to see their own content (reviews and collections). Non-developer profiles should no longer show anything, so the Not Found page is correct. Logging in would also lead to a Not Found page for all user pages except your own, so it wouldn't be very useful to ask people to log on those pages.

> describes me as an Add-ons developer which really, I'm not

That's worth filing a separate issue.
