### ISSUE TITLE
Perma-linked review: multiple reviews (more than 1) with '1 review for this add-on'

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#6360]
https://addons.mozilla.org/addon/newsit-hnews-and-reddit-links/reviews/1160317/ for example: 

![2018-09-23 15 25 58 about profiles - mozilla firefox](https://user-images.githubusercontent.com/192271/45929104-07d75000-bf45-11e8-9350-fcfb8bc3dd3f.png)

Obviously there's more than one ;-) and none of the four _2 months ago_ links offers a timestamp hint. 

If a review is version-specific, it will help to state the version.

**Comment by jvillalobos** [comment]
We're moving away from multiple reviews per-add-on, so that's just an edge case that should eventually go away.
