### ISSUE TITLE
Expose feature flags and experiments on `/__frontend_version__`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6363]
In order to quickly know/verify which features and/or experiments (A/B) are enabled/disabled for a given app and env, let's expose them on `/__frontend_version__`, which is an existing endpoint that returns a JSON response with some version numbers.

**Comment by willdurand** [comment]
For QA:

- on AMO, https://addons-dev.allizom.org/__frontend_version__ should show two new attributes `experiments` and `feature_flags`
- on Disco Pane, https://discovery.addons-dev.allizom.org/__frontend_version__ should show two new attributes `experiments` and `feature_flags`

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev and stage with FF62, Win10x64

[AMO]
![image](https://user-images.githubusercontent.com/31961530/46075581-9c36f200-c193-11e8-9c30-9e99b1fb143d.png)

[Disco]
![image](https://user-images.githubusercontent.com/31961530/46075602-abb63b00-c193-11e8-9205-24cdd728aba1.png)
