### ISSUE TITLE
Unable to map a locale from language code (UTM params)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6366]
### Describe the problem and steps to reproduce it:

I read production logs.

### What happened?

I saw:

```json
{
    "Fields": {
        "msg": "Unable to map a locale from language code [?utm_source=discovery.addons.mozilla.org&utm_medium=firefox-browser&utm_content=find-more-link-top&src=api]"
    },
    "Logger": "amo",
    "Severity": 3,
}
```

### What did you expect to happen?

I don't know. Maybe it is a false-positive but it would be nice to investigate.

**Comment by kumar303** [comment]
Weird. Maybe `getLangFromHeader()` is doing something wrong? Or maybe it was just malicious input.
