### ISSUE TITLE
No platform exists for user agent OS "<undefined agentOsName>"

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6368]
### Describe the problem and steps to reproduce it:

I read the production logs.

### What happened?

I saw:

```json
{
    "Fields": {
        "msg": "No platform exists for user agent OS \"<undefined agentOsName>\""
    },
    "Logger": "amo",
    "Severity": 3,
}
```

### What did you expect to happen?

I don't know. Maybe it is a false positive but we should investigate why the user agent OS value is `<undefined agentOsName>`.

### What to do?

We should change the log level of this message from `error` to `warning` by updating this block: https://github.com/mozilla/addons-frontend/blob/adb2ad0132798af9f5fee9e5c98c542265ba5b40/src/amo/components/PermissionsCard/permissions.js#L73-L77

Instead of calling `log.error`, we should call `log.warn`

**Comment by kumar303** [comment]
An `undefined` user agent name is a likely scenario, especially for scripted requests. The current error logging is trying to alert us to unmapped agents (which would be a bug):

https://github.com/mozilla/addons-frontend/blob/adb2ad0132798af9f5fee9e5c98c542265ba5b40/src/amo/components/PermissionsCard/permissions.js#L73-L77

However, it should probably only log a warning. There are too many scenarios where a user could trigger this error and spam Sentry.

**Comment by willdurand** [comment]
> However, it should probably only log a warning. There are too many scenarios where a user could trigger this error and spam Sentry.

Agreed!

**Comment by SeanPrashad** [comment]
Hey guys - this one looks like a quick and easy fix and I'd like to walk a friend through it as their first contribution if that's ok!

@willdurand You mentioned that their error was found in production logs (_which I regular contributors wouldn't have access to_). Is there another way that we can reproduce this locally?

**Comment by willdurand** [comment]
@SeanPrashad you can try to use a tool like HTTPie to send request without a user agent.

**Comment by willdurand** [comment]
Ok, so I guess this is a wontfix since we don't have the log entry anymore.
