### ISSUE TITLE
500 error on AMO website and "JavaScript heap out of memory" error

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#6369]
### What happened?

We got paged due to increased 500 errors on AMO website. Upon investigation, the log shows that the Javascript program failed with "JavaScript heap out of memory" error. This caused the instances to fall out of ELB, and thus the 500 errors.

### What did you expect to happen?

Ideally, no "JavaScript heap out of memory" errors because that may mean a memory leak somewhere.

### Anything else we should know?

1. The full log from one of the instances can be found at https://drive.google.com/open?id=1UrqzEKBAb9nYA9Rq-o2SadHIFGl4Pzh0

2. It looks like a little before the instances started to fail, there was an increase of incoming requests, the increased load seemed to have triggered the "JavaScript heap out of memory" on a couple of the nodes first, when those two failed the ELB health check and were taken out of ELB, it put more pressure on other instances, and more instances failed with the same "heap out of memory" error.

**Comment by willdurand** [comment]
>     1. The full log from one of the instances can be found at [drive.google.com/open?id=1UrqzEKBAb9nYA9Rq-o2SadHIFGl4Pzh0](https://drive.google.com/open?id=1UrqzEKBAb9nYA9Rq-o2SadHIFGl4Pzh0)

I filed the following issues after having read this log file:

- https://github.com/mozilla/addons-frontend/issues/6370
- https://github.com/mozilla/addons-frontend/issues/6368
- #6367 
- #6366

**Comment by bqbn** [comment]
After checking the Nginx logs, it looks like the increased incoming requests mentioned in https://github.com/mozilla/addons-frontend/issues/6369#issue-363077736 was coming from one IP. The IP started to send many requests to us at around September 24, 2018 8:14 AM UTC, and stopped at around 8:57 AM UTC. It sent roughly 3 million requests during that time.

Related log files can be found in [1].

Please let me know if there are questions.

[1] https://drive.google.com/open?id=1Jejjykm7WpMYakm_tNzgcEtUo_eLvHCl

**Comment by kumar303** [comment]
Thanks @bqbn. This looks like a DOS attempt that was successful. Here is a recap:

* The malicious request(s) triggered the frontend to log an error that included the entire response object. This used a lot of memory (about 36MB per message) and was multiplied by the number of requests.
* We are no longer logging the entire response object. See https://github.com/mozilla/addons-frontend/issues/6370
* The API was returning a lot of 504 timeout responses. I filed https://github.com/mozilla/addons-server/issues/9540 to investigate.

Based on https://github.com/mozilla/addons-frontend/issues/6370 , we believe that this same DOS attempt will not be successful in the future so I'm closing the issue.

**Comment by kumar303** [comment]
We will be reviewing log calls in https://github.com/mozilla/addons-frontend/issues/6426 to make sure they don't have similar problems.

**Comment by willdurand** [comment]
@AlexandraMoga I don't think so, thanks!
