### ISSUE TITLE
Add-on details page looks like it's loading the content twice

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6372]
STR:

1. Open AMO -dev
2. Click on any add-on from the homepage
3. Observe the detail page while loading

Actual result:
The detail page content looks like is loading twice

Expected result:
Add-on detail page is correctly loaded from a visual perspective

Notes:
- not reproduced on stage and prod
- it happens with all add-on types
- reproduce don AMO - dev with FF62, Win10x64 and Android 8.0

![twice loading](https://user-images.githubusercontent.com/31961530/45951142-0ec89600-c00b-11e8-9c07-140c8272d66b.gif)

**Comment by willdurand** [comment]
FWIW, I cannot reproduce locally with FF Nightly and I cannot reproduce with Chrome on -dev (Chrome is handy to use the redux devtools in -dev).

**Comment by AlexandraMoga** [comment]
I've also tried with Chrome and latest Nightly and I can't reproduce.

**Comment by kumar303** [comment]
This is a regression caused by https://github.com/mozilla/addons-frontend/pull/6335 and I've located the culprit. I'll have a fix soon.

**Comment by AlexandraMoga** [comment]
Verified fixed on dev ans stge with FF62, Win10x64 and Androd 8.0

![refresh ok](https://user-images.githubusercontent.com/31961530/46064357-dabeb380-c177-11e8-8d0a-771832e8325b.gif)
