### ISSUE TITLE
Remove `enableFeatureAddonRecommendations` feature flag (feature adopted)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6374]
we should remove all occurrences and most of the test cases related to the `enableFeatureAddonRecommendations` feature flag because this feature has been adopted.

```
config/default-amo.js:  enableFeatureAddonRecommendations: true,
config/default.js:    'enableFeatureAddonRecommendations',
config/default.js:  enableFeatureAddonRecommendations: false,
tests/unit/amo/pages/TestAddon.js:      enableFeatureAddonRecommendations: true,
tests/unit/amo/pages/TestAddon.js:      enableFeatureAddonRecommendations: true,
tests/unit/amo/pages/TestAddon.js:      enableFeatureAddonRecommendations: false,
tests/unit/amo/pages/TestAddon.js:      enableFeatureAddonRecommendations: true,
src/amo/pages/Addon/index.js:    const enableFeatureAddonRecommendations =
src/amo/pages/Addon/index.js:      config.get('enableFeatureAddonRecommendations') &&
src/amo/pages/Addon/index.js:            {enableFeatureAddonRecommendations && (
```

**Comment by suhailsinghbains** [comment]
Hi, can I please take this up ?

**Comment by willdurand** [comment]
@suhailsinghbains sure!

**Comment by suhailsinghbains** [comment]
Hey @willdurand Just a quick question, I cannot find a single reference of 'enableAddonRecommendations'(but, it is being shown in the code above that you shared). However, I could find 'enableFeatureAddonRecommendations'. Should I remove 'enableFeatureAddonRecommendations' then?

**Comment by willdurand** [comment]
@suhailsinghbains ah yes, sorry. I will update the snippet above. It is `enableFeatureAddonRecommendations` that needs to be removed.

**Comment by suhailsinghbains** [comment]
Okay, cool, working on it.

**Comment by AlexandraMoga** [comment]
Please add STR or the label qa:not needed.

Thanks

**Comment by willdurand** [comment]
@AlexandraMoga please make sure addon recommendations (add-on detail page) are still shown.

**Comment by AlexandraMoga** [comment]
Recommendations look fine on -dev. 
I'm waiting to verify this on stage too, since it has more valid data for recommendations testing.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage

![image](https://user-images.githubusercontent.com/31961530/46402296-060d4980-c708-11e8-898a-dbf75e8eec6d.png)
