### ISSUE TITLE
Add-on reviews page is not loaded properly after a review permalink is selected

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6377]
STR:

1. Load AMO -dev
2. Go to an add-on details page 
3. Open the reviews page for this add-on - - i.e. https://addons-dev.allizom.org/en-US/firefox/addon/stratiform/reviews/
4. Click on a review timestamp

Actual result:
Several sections in the page - add-on data, ratings breakdown, reviews header - are not loaded (are stuck in a loading state)

Expected result:
Add-on reviews page has no loading issues when opening a review permalink

Notes:
- I'm not always reproducing this on the first attempt, so you might have to click on several distinct reviews until the issue becomes visible
- I did not notice a specific error in the console except for the fact that there seem to be quite a few csp reports recorded for the add-on reviews page
- reproduced on AMO -dev with FF62, Win10x64

![loading ratings](https://user-images.githubusercontent.com/31961530/45956837-3aa04780-c01c-11e8-93d2-b5b46058227f.gif)

**Comment by bobsilverberg** [comment]
I have been unable to reproduce this either locally or on dev.

**Comment by AlexandraMoga** [comment]
Not reproducing anymore either. Maybe some other patch might have fixed this too.
