### ISSUE TITLE
The add-on detail page refreshes when rating an add-on

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6381]
When you click a star to rate an add-on, the "Saving star rating" message appears, but then, just before the "Star rating saved" message appears, the contents of the page refreshes.

![sep-24-2018 12-05-30](https://user-images.githubusercontent.com/142755/45963847-2fd0bd00-bff2-11e8-91a7-2b1e0559d04c.gif)

**Comment by kumar303** [comment]
Ugh. This is pretty bad. You can see the same thing by loading the home page and clicking on any add-on.

The regression was caused by https://github.com/mozilla/addons-frontend/pull/6335 🙈

**Comment by bobsilverberg** [comment]
> The regression was caused by https://github.com/mozilla/addons-frontend/pull/6335 🙈

Does that mean you're volunteering to fix it? Do you know ottoyh what needs to be done to fix it?

**Comment by AlexandraMoga** [comment]
I suppose the issue I logged yesterday -  #6372  -  is similar to what is shown here

**Comment by kumar303** [comment]
I reverted the code causing this regression (see https://github.com/mozilla/addons-frontend/pull/6399) and I reopened https://github.com/mozilla/addons-frontend/issues/6265

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

![no refresh on rating](https://user-images.githubusercontent.com/31961530/46064477-2bcea780-c178-11e8-8b67-f7f28553a724.gif)
