### ISSUE TITLE
Write a review button appears for the user who did not create a rating

### ISSUE THREAD

**Issue by mymindstorm** [mozilla/addons-frontend#6388]
### Describe the problem and steps to reproduce it:

Broken:

![image](https://user-images.githubusercontent.com/27789806/45978411-ed1edd00-c011-11e8-94d5-916bf759a45a.png)

Normal:

![image](https://user-images.githubusercontent.com/27789806/45978704-97970000-c012-11e8-975c-afeed8343dec.png)

[Example 1](https://addons.mozilla.org/en-US/firefox/addon/auth-helper/reviews/1165900/) [Example 2](https://addons.mozilla.org/en-US/firefox/addon/auth-helper/reviews/1197592/)

### Anything else we should know?

- Only appears when signed in, not sure if applies to non-developer accounts
- Only appears on blank reviews
- The button doesn't do anything when clicked

**Comment by bobsilverberg** [comment]
I don't think the presence of the button is a bug. It's fine to allow a user to write a review from that location, but the button is too big. This has been fixed and the change should land in production on Thursday.

**Comment by mymindstorm** [comment]
Should it show the write a review button for someone other than the user that created the review?

**Comment by bobsilverberg** [comment]
> Should it show the write a review button for someone other than the user that created the review?

No, it shouldn't. I didn't realize that was what was happening. I'll reopen this.

**Comment by kumar303** [comment]
Thanks for the bug report, @mymindstorm 

I swear at some point I thought to restrict this line of code to the review owner but I guess I forgot 😁 

https://github.com/mozilla/addons-frontend/blob/389b590cbfd8442a6a189777e9f9f0805bce8008/src/amo/components/AddonReviewCard/index.js#L438-L449

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/46211685-df809480-c33c-11e8-8bd9-70390f6a38d3.png)
