### ISSUE TITLE
"Choose Photo" button stays highlighted after being clicked on user profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6396]
Followup for https://github.com/mozilla/addons-frontend/issues/6251
STR:
1. Load AMO dev and sign in then go to "edit my profile" page 
2. Click the Choose Photo button and change the profile picture
3. Observe "Choose Photo" button after selecting a picture

Expected result:
Button is no longer highlighted 

Actual result:
Button is still highlighted

Notes:
This issue is also reproducible with "Find more add-ons" button from Disco Pane with FF62(Win10). 

![it stays highlighted2](https://user-images.githubusercontent.com/33448286/46012235-3e41d600-c0d1-11e8-824a-0c178133e859.gif)

**Comment by willdurand** [comment]
With FF 62.0.2 on MacOS, I cannot reproduce :(

**Comment by willdurand** [comment]
@ioanarusiczki can you test it with MacOS by chance? I am wondering if it is an OS issue or not.

**Comment by ioanarusiczki** [comment]
@willdurand Sure but not today. I'll return with results on Friday !

**Comment by willdurand** [comment]
>  This issue is also reproducible with "Find more add-ons" button from Disco Pane with FF62(Win10).

I cannot reproduce with Windows 10 and FF 62 (32 bits)

**Comment by willdurand** [comment]
I was able to reproduce the issue on Windows 10, but only for the "Choose photo" button with FF 62.
