### ISSUE TITLE
Disco Pane won't display "This add-on does not support your browser" message for incompatible lang packs

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6401]
Followup for https://github.com/mozilla/addons-frontend/issues/6331

1. Load the Disco Pane for AMO dev and make sure there's a lang pack added using admin tools which is not compatible with the current FF version, in this case FF62, list of incompatible lang packs are [here](https://addons-dev.allizom.org/en-US/firefox/language-tools/)
2. Check if disco pane displays the warning message

Expected result:
 "This add-on does not support your browser"  message is displayed in Disco Pane

Actual result:
No message displayed.

Notes:
This issue is reproducible on AMO dev with FF62, FF64 (Win10)

![armenian](https://user-images.githubusercontent.com/33448286/46022054-8ae5db00-c0ea-11e8-9e34-16fdc7ca057a.png)

**Comment by willdurand** [comment]
This issue requires an API change, requested here: https://github.com/mozilla/addons-server/issues/9520

**Comment by muffinresearch** [comment]
FWIW and AFAIK there are no current plans to surface lang packs on the disco pane.

**Comment by willdurand** [comment]
This should be fixed now, via the API change that has landed in -dev.

**Comment by ioanarusiczki** [comment]
This is no longer reproducible with the lang packs on AMO dev's disco pane - FF62 - Win10

![lang packs](https://user-images.githubusercontent.com/33448286/46281453-6456f280-c577-11e8-9d6f-b30759702cb4.png)
