### ISSUE TITLE
Theme wizard should preload latest version properties when uploading new version

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6408]
STR:

1) Create a theme
2) In the Dev Hub, click on Upload New Version.
3) Click on Create a Theme button.

Expected:
The properties of the current theme version should be preloaded, so they are easy to edit. Currently, the wizard is in its default state.

This won't work very well if the previous version was uploaded as an XPI and included properties that the wizard doesn't support. It's an edge case, however, and maybe we can show a warning on the wizard page explaining that those properties will be reset (or kept?).

**Comment by muffinresearch** [comment]
@jvillalobos can this be re-filed on addons-server?

**Comment by jvillalobos** [comment]
Bah! Moved to https://github.com/mozilla/addons-server/issues/9539.
