### ISSUE TITLE
Editing a developer reply on the user profile page will open the write a review form/overlay

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6414]
Almost similar to #6356 
Follow up for #6104 

STR:

1. Log in to AMO stage with a developer account
2. Go to your user profile page
3. Locate a developer reply in the list of reviews you posted
4. Click on Edit my reply

Actual result:
The Write a review overlay opens. The user can hover and select stars.

Expected result:
The Edit reply inline form should be opened 

Notes:
- I think it would have been much preferable to wait until all these possible flows have been fixed instead of launching a confusing UX in prod
- note that on the add-on reviews page we already have, in production, the inline form for editing a developer reply, so I;m not sure why we didn't use this for the user profile too
- reproduced on dev and stage with FF62, Win10x64

![edit reply on user profile](https://user-images.githubusercontent.com/31961530/46066097-8538d580-c17c-11e8-9764-5ede4fe9294b.gif)

**Editing a dev reply on the add-on reviews page:**
![image](https://user-images.githubusercontent.com/31961530/46066147-a8638500-c17c-11e8-9656-33718da20648.png)

**Comment by bobsilverberg** [comment]
This is another case of something that will work properly once the new reviews UI is enabled on stage/prod. I agree that it's unfortunate that we have landed some changes in prod which rely on the new UI to work properly. There are a bunch of changes needed to the experience of interacting with a reply, which have issues open for them, so it might make sense to tackle this at the same time.

As a stop-gap, if we don't think we'll be enabling the UI in the very near future, we could remove the link to edit a reply from the User Profile page, but I'm not sure if that is the best route to take.

@kumar303 We should take a look at all of these issues and decide how to proceed.

**Comment by bobsilverberg** [comment]
This should be fixed via https://github.com/mozilla/addons-frontend/issues/6349, which we hope to land on stage at the end of this week, and on prod for next week's push.

**Comment by kumar303** [comment]
The easiest thing would be to just enable the new inline form ASAP (#6349) and leave this bug as is until then. It's not ideal but the form mostly still works. You can edit the reply and save it.

**Comment by AlexandraMoga** [comment]
This is now fixed on stage by the inline review form (#6349)

![edit reply stage](https://user-images.githubusercontent.com/31961530/46396337-d3f3eb80-c6f7-11e8-980d-3cdbfe5d9a56.gif)
