### ISSUE TITLE
"Flag" should be removed from the profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6416]
STR:
1. Load AMO dev and go to the user profile page, make sure you have some reviews
2. Observe the buttons displayed

Expected result:
Edit reviews and Delete review are available.

Actual result:
Flag is present too - it has no functionality since the user cannot flag his own reviews (or developer responses)

Notes:
Issue is reproducible on AMO dev with FF62 -Win10

![own reviews cannot be flagged](https://user-images.githubusercontent.com/33448286/46067452-815a8280-c17f-11e8-96b8-503b4d8ce738.png)

**Comment by SeanPrashad** [comment]
Hey @ioanarusiczki, @kumar303 - I'd like to help work on this bug if it's available!

I was able to still reproduce it just now on FF 62.0.3 (64-bit):

![amo_bug_reproducable](https://user-images.githubusercontent.com/13009507/46897439-978b6280-ce50-11e8-8c00-016de8eb66ea.gif)

From my understanding, a solution would to completely remove it from being rendered for reviews by the current user?

**Comment by kumar303** [comment]
@SeanPrashad has fixed the issue 🎉  but his fix went further to not show the Flag link for a user's own review on any page. @ioanarusiczki please take a look at the other screens where we used to show the Flag link.

**Comment by ioanarusiczki** [comment]
@kumar303 I checked the profile page and the reviews page for reviews and developer replies for an admin account and a developer account and "Flag" is no longer displayed. Tested on AMO dev with FF62 (Win10 & Android 8.0)
Thanks @SeanPrashad for fixing this!

![flag is gone](https://user-images.githubusercontent.com/33448286/47221083-2dc50880-d3bc-11e8-956f-a73adf6c2dd3.gif)
