### ISSUE TITLE
"TotalAV Safe Site" not recognized in Firefox?

### ISSUE THREAD

**Issue by powysian** [mozilla/addons-frontend#6421]
As a paidup customer of TotalAV, I received an email invitation to install a 

"Recommended Security Add-On. Protect your privacy with TotalAV Safe Site for Firefox Install yours today totally free and benefit from over 5,000 new definitions every day"

When I clicked on their link I got an error as attached:
![error](https://user-images.githubusercontent.com/43604947/46074300-0ee9a280-c17f-11e8-81f1-d92cba04d1fb.JPG)

**Comment by muffinresearch** [comment]
Duplicate of #5466
