### ISSUE TITLE
StrictMode causes double action dispatching in local dev

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6424]
The `StrictMode` wrapper is causing components to dispatch their loading actions twice. 

With Redux DevTools open, load the home page and click on an add-on to see what I mean. Here are some doubling of action dispatches:

<img width="307" alt="screenshot 2018-09-26 09 14 45" src="https://user-images.githubusercontent.com/55398/46086068-00928b00-c16d-11e8-8d8c-3aad5ecef5b5.png">

If I apply this patch to remove `StrictMode`...

```diff
diff --git a/src/core/components/Root/index.js b/src/core/components/Root/index.js
index 634386f04..3e69583ec 100644
--- a/src/core/components/Root/index.js
+++ b/src/core/components/Root/index.js
@@ -18,10 +18,7 @@ type Props = {|
 const Root = ({ children, history, i18n, store }: Props) => (
   <I18nProvider i18n={i18n}>
     <Provider store={store} key="provider">
-      <ConnectedRouter history={history}>
-        {/* $FLOW_FIXME: https://github.com/facebook/react/issues/12553 */}
-        <React.StrictMode>{children}</React.StrictMode>
-      </ConnectedRouter>
+      <ConnectedRouter history={history}>{children}</ConnectedRouter>
     </Provider>
   </I18nProvider>
 );

```

...then the actions are dispatched normally:

<img width="323" alt="screenshot 2018-09-26 09 15 22" src="https://user-images.githubusercontent.com/55398/46086141-1738e200-c16d-11e8-9cd3-0802d8c6bcd2.png">

This does not happen on `addons-dev.allizom.org` probably because the `StrictMode` checks are disabled with `NODE_ENV` set to `production`.

**Comment by willdurand** [comment]
See: https://github.com/facebook/react/issues/12856#issuecomment-390206425

**Comment by kumar303** [comment]
I understand this now. That's a nice feature! 

I looked briefly at the two issues but I don't think we can do anything about them. `StrictMode` will create the component instance twice with the exact same props (invoking `constructor()` each time). 

How would you prevent a constructor from re-dispatching its loading action? I can't think of a way. Perhaps that's not the right question to ask. Maybe the question is: is it OK to dispatch a loading action twice? For both of these cases, the answer is yes. However, in the case of `FETCH_ADDON` there are *side effects* in the saga which is to make an API calls and load the data. That also doesn't cause anything bad to happen but it's confusing for development since many actions are duplicated.

**Comment by kumar303** [comment]
> is it OK to dispatch a loading action twice?

Yes, the docs suggest that this is the right question to ask. It wants you to see if your `constructor()` is idempotent. I believe that ours are in both cases, the results are just a little confusing.

**Comment by kumar303** [comment]
In any case, this is not a bug
