### ISSUE TITLE
Review our log calls

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6426]
We should review our log calls and make sure we don't log full objects (potentially large objects) and also make sure we log with the right levels.

**Comment by kumar303** [comment]
Yeah. Let's look for any log call that passes something other than a string as arguments.

**Comment by willdurand** [comment]
Here is what I have found:

https://github.com/mozilla/addons-frontend/blob/1e8e81c5b726959a465d79de6a4fe99247ddf987/src/amo/pages/Addon/index.js#L425-L426

https://github.com/mozilla/addons-frontend/blob/1e8e81c5b726959a465d79de6a4fe99247ddf987/src/amo/pages/AddonReviewList/index.js#L177

https://github.com/mozilla/addons-frontend/blob/1e8e81c5b726959a465d79de6a4fe99247ddf987/src/amo/pages/Collection/index.js#L489-L490

https://github.com/mozilla/addons-frontend/blob/1e8e81c5b726959a465d79de6a4fe99247ddf987/src/amo/pages/UserProfile/index.js#L242-L243

https://github.com/mozilla/addons-frontend/blob/1e8e81c5b726959a465d79de6a4fe99247ddf987/src/amo/pages/UserProfileEdit/index.js#L433-L434

This one logs a function (I think):

https://github.com/mozilla/addons-frontend/blob/1e8e81c5b726959a465d79de6a4fe99247ddf987/src/core/api/index.js#L351-L352

**Comment by willdurand** [comment]
I submitted a PR to remove the function in the log call pasted above. Other log calls look good to me.

**Comment by kumar303** [comment]
Excellent! Thanks for following up and digging in.
