### ISSUE TITLE
Document where storybook is hosted

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6427]
There is a bit of documentation on [storybook](https://github.com/mozilla/addons-frontend/#storybook) but it should include a link to the hosted storybook: http://mozilla.github.io/addons-frontend/

**Comment by AlexandraMoga** [comment]
Do you need any QA for thsi?

**Comment by rebmullin** [comment]
@AlexandraMoga, no QA on this one : ) thanks
