### ISSUE TITLE
Add introductory copy above hero area on homepage

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6431]
Per the [PRD](https://docs.google.com/document/d/1PZwtYeWC2_eWBOX4a8QUBoOHeAZpEEOFRzEhpsgFrKo/edit#), the new hero area will include some introductory text that explains what add-ons are about.

@MeridelW to provide copy.

**Comment by MeridelW** [comment]
We can remove "Needs: Content" here as the copy has been provided. See this doc: https://docs.google.com/document/d/1u1tbRo_ivfEAh_er2XKPciuYLARiNa2N5qXPGC0jfcY/edit

**Comment by rebmullin** [comment]
I'm closing this as this was included as part of the homepage #6433 work..
