### ISSUE TITLE
Redesign hero area and point to user guides

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6433]
For the [Homepage Hero Area](https://docs.google.com/document/d/1PZwtYeWC2_eWBOX4a8QUBoOHeAZpEEOFRzEhpsgFrKo/edit#), the new design will point to new user guide pages that are also part of this project.

The homepage will show a few (about 3), but there will probably be a couple more we have in reserve so the content changes regularly. The ones we show will be decided in the monthly homepage refresh that @devaneymoz requests, but further down the line they will be controlled by an admin tool (we might get into this in Q1 2019, so I wanted to mention it in case it changes anything about the implementation).

Final design to be provided by @pwalm.

**Comment by ioanarusiczki** [comment]
@rebmullin Hi Rebecca, is this ready for testing after https://github.com/mozilla/addons-frontend/issues/6701 is closed? I do not see the new home hero design on AMO dev - FF63(Win10)

**Comment by willdurand** [comment]
> @rebmullin Hi Rebecca, is this ready for testing after #6701 is closed? I do not see the new home hero design on AMO dev - FF63(Win10)

@ioanarusiczki no, it is not available yet. Adding "qa: not needed" for now.

**Comment by ioanarusiczki** [comment]
@willdurand Alright, thanks for the news !
