### ISSUE TITLE
Unauthorized users can access an edit collection page 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6436]
STR:

1. Log in to AMO with a regular user (no special permissions)
2. Follow this link: https://addons.mozilla.org/en-US/firefox/collections/mozilla/ad-blockers/edit/

Actual result:
A regular user can view a collection edit page. He doesn't have permissions to execute any action, so there is no actual damage done.

Expected result:
The collection edit page should be visible only to the owner or to users with special permissions. For all other users the page should not be available

Notes:
- the unauthorized user needs to have a direct link to the collection edit page or he should add `/edit/` in the collection URL himself in order to access the page
- reproduced on all AMO servers with FF62, Win10x64

![direct link to edit collection](https://user-images.githubusercontent.com/31961530/46152210-3886f480-c279-11e8-90da-5dcc264c2209.gif)

**Comment by bobsilverberg** [comment]
I don't think this is worth fixing. We enforce security via the API authorizations, and you confirm that an unauthorized user is unable to perform any actions from this screen. There is no way for an unauthorized user to access this screen from within the app - they can only access it via a direct URL.

I don't think we generally write extra code to block unauthorized users from accessing a URL directly, as long as we know they cannot perform any actions, so I am inclined to close this as wontfix.

@kumar303 What do you think?

**Comment by muffinresearch** [comment]
I think this should be fixed. It would be idea if this could be a 401 status code error page.

**Comment by kumar303** [comment]
> I don't think this is worth fixing. We enforce security via the API authorizations, and you confirm that an unauthorized user is unable to perform any actions from this screen. 
> ...
> @kumar303 What do you think?

I agree. I don't think it's worth fixing. Even though it looks like you can edit the collection, the message is pretty clear when you try it. Even if we were to fix it, we'd have to do some upfront API calls to check ownership somehow.

@muffinresearch feel free to re-open if you think we should keep it in the backlog.
