### ISSUE TITLE
Deleting a review from its permalink shows 'review was not found'

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6438]
### Describe the problem and steps to reproduce it:

* Sign in as a non-administrator
* Review an add-on
* Go to the review listing
* Click the timestamp of the review you just wrote to view its detail page
* On the detail page, click *Delete review* and confirm deletion

### What happened?

The review is deleted but you now see *The review was not found* at the top of the page.

### What did you expect to happen?

The page should redirect you to the review listing.

**Comment by bobsilverberg** [comment]
I implemented this "review was not found" message to address the case where someone shares a permalink to a review, but the review has been deleted. If we no longer show a message but rather just redirect the user to the review listing page, with no acknowledgment that they intended to visit a particular review, I think that could be confusing to them. I think it better to support that use case, and have a minor annoyance of an extra message at the top of the page immediately after you delete a review from a permalink.

We could change the message to "The review has been deleted by the author", which would be more specific and would address both cases.

What do you think @kumar303?

**Comment by kumar303** [comment]
Ah, ok, that makes sense and I see how it could be helpful. I'm not sure if we can easily determine whether a review was deleted or it simply doesn't exist. It's probably not worth the effort. I'm just going to close this for now.
