### ISSUE TITLE
When saving changes to a reply, it is not updated in other places

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6441]
There are a couple of different STRs:

From a permalink:

1. Log in as an admin and go to the list of reviews for an add-on.
2. Add a reply to one of the reviews.
3. Click the permalink of the reply you just created to be brought to the permalinked page for the reply.
4. In the "Reply by..." card, click the "Edit reply" link.
5. Change the text of the reply and click "Update reply".

Expected result:
The text of the reply is changed in both the "Reply by..." card and in the embedded reply which is visible in the list of reviews.

Actual result:
The text of the reply is changed in the "Reply by..." card but the old text is visible in the list of reviews.

From the list of reviews:

1. Log in as an admin and go to the list of reviews for an add-on.
2. Add a reply to one of the reviews.
3. Click the permalink of the reply you just created to be brought to the permalinked page for the reply.
4. In the embedded reply in the list of reviews (i.e., the one with the blue background), click the "Edit reply" link.
5. Change the text of the reply and click "Update reply".

Expected result:
The text of the reply is changed in both the "Reply by..." card and in the embedded reply which is visible in the list of reviews.

Actual result:
The text of the reply is changed in the embedded reply which is visible in the list of reviews but the old text is visible in the the "Reply by..." card.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This issue is reproducible with developer accounts too. If page is refreshed the last edit will be correctly displayed in both places.  - FF62(Win10)

![developer account](https://user-images.githubusercontent.com/33448286/46338050-cd05a400-c637-11e8-96aa-4bf9dc80a9d9.gif)

**Comment by kumar303** [comment]
We could fix this but showing the two forms is just a bug that we will fix in https://github.com/mozilla/addons-frontend/issues/6443 Thus, I'm closing this.

**Comment by bobsilverberg** [comment]
I'm not sure that this is related to the two forms, but maybe I'm misunderstanding the issue. To me this is about the fact that editing a reply in one place does not clear the cache and refresh the reply in another place. E.g., editing a reply in the Featured review card does not update the text of the reply as it appears in an embedded reply further down the page. I'm not sure how not displaying two forms would directly address that.
