### ISSUE TITLE
This site should be add to complements in firefox, but page was not found :https://hotsite.certisign.com.br/certiplugincorpng/firefox/plugin/InstallCertiPlugin.html

### ISSUE THREAD

**Issue by cegc14** [mozilla/addons-frontend#6445]

**Comment by muffinresearch** [comment]
We are unable to provide support for individual add-ons.

This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services.  

Please look at the add-on details page and see if the add-on author has provided support information. If supplied you'll find it in the "More information" section.

<img width="509" alt="facebook_container_ _add-ons_for_firefox" src="https://user-images.githubusercontent.com/1514/41969476-6de12c9e-79ff-11e8-9df5-45a79bb70975.png">

If you think this issue has been closed in error, please re-open and provide additional information.
