### ISSUE TITLE
Akismet spam messages are not displayed next to the field that generated them

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6452]
STR:

1. Log in to AMO -dev
2. Create a new collection
3. Enter some _spammy_ content inside the metadata fields (i.e special characters only)
4. Save the collection

Actual result:
An error message is displayed to inform the user that spam content was detected. The message is not correlated to the field that triggered the error. This could be confusing especially for false positives.

Expected result:
The spam error message needs to be correlated to the field that triggered it.

Notes:
- this is a follow up for https://github.com/mozilla/addons-server/issues/8703
- there is a similar issue logged on addons-server regarding how spam error messages are handled - see https://github.com/mozilla/addons-server/issues/9513 . 
- reproduced on AMO -dev with FF62, Win10x64

![image](https://user-images.githubusercontent.com/31961530/46210797-6bdd8800-c33a-11e8-8be3-159026ab3d26.png)

**Comment by muffinresearch** [comment]
@jvillalobos I think this issue highlights that we might need to rethink the visibility of spam flagging. 

Since for the most part we should assume akismet can be wrong. Because of that I think in every case it should be invisible to users. Otherwise there are at least two concerns; it will worry people that get a false positive when they're not entering spam, and it will also provide a feedback loop to someone that _is_ trying to add spam. 

If it was silent, whether the content stays on the site is up to moderation. Whilst this puts more load on moderation it seems like a less invasive approach.

**Comment by jvillalobos** [comment]
Moderation is what we already do, and adding Akismet to it wouldn't help. We need something that blocks spam creation for this project to be effective. If we can't have any level of trust on their system, then this won't work.

The PRD specifies sending the individual pieces of data separately, so we should be able to show the error message in the right place. Sure, some spammers will work around it, but we can report those to Akismet to try to keep the system working.

**Comment by eviljeff** [comment]
I'm not sure if there is any frontend component to this fix also, but displaying the akismet error next to the field requires API changes on addons-server so an issue should be filed there too if it should be fixed.

note: Collections have no moderation support at all currently.  There's no review of the creation/editing and no spam flagging button.  We don't even have an abuse report function - someone would have to go to the user's account profile and flag abuse from there (which may not be possible in the future if the collection owner isn't also an addon developer).

**Comment by willdurand** [comment]
> I'm not sure if there is any frontend component to this fix also, but displaying the akismet error next to the field requires API changes on addons-server so an issue should be filed there too if it should be fixed.

Shall we?

**Comment by jvillalobos** [comment]
We're dropping Akismet.
