### ISSUE TITLE
Adjust the appearance of the confirmation buttons when deleting a review/reply

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6454]
This is work towards #6347 which only implements the visual changes to the buttons, but does not address making other parts of the UI hidden when the confirmation is displayed.

Here is a copy of the current spec:

![ratings and reviews flow v2](https://user-images.githubusercontent.com/55398/45894396-ceabae00-bd93-11e8-9b44-cdb7bc82eb2e.png)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF62 (Win 10 and Android 8.0)

Delete Rating

![delete rating](https://user-images.githubusercontent.com/33448286/46412094-3237c300-c726-11e8-882a-1dc1ad03a582.gif)

Delete Review 

![delete review stage](https://user-images.githubusercontent.com/33448286/46412113-3cf25800-c726-11e8-8477-61fee41b08c8.gif)
