### ISSUE TITLE
Look at switching back to Sentry's babel-gettext-extractor lib

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6457]
Looks like they've pulled in the changes from the Mozilla fork so we can switch back to it and deprecate the mozilla version ([once the linter switches too](https://github.com/mozilla/addons-linter/issues/2211)).

See https://github.com/getsentry/babel-gettext-extractor

**Comment by ioanarusiczki** [comment]
@willdurand Could you add some STR for qa? Thanks!
