### ISSUE TITLE
Simplify delete confirmation UI in review listing

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6458]
### Describe the problem and steps to reproduce it:

- Sign in
- Rate an add-on and write a review
- Go to the review listing
- Find the review and click *Delete review*

### What happened?

It shows a prompt with two buttons

### What did you expect to happen?

It should be simplified like https://github.com/mozilla/addons-frontend/issues/6347

**Comment by pwalm** [comment]
Proposed:
<img width="1070" alt="screen shot 2018-09-28 at 1 52 56 pm" src="https://user-images.githubusercontent.com/6797635/46233013-07183280-c326-11e8-8590-19fc80fb6d32.png">

When "Delete review" is clicked, the prompt appears in place.

**Comment by ioanarusiczki** [comment]
Verified this issue on AMO dev with FF62 - Win10&Android 8.0 
I filed two separate issues 
https://github.com/mozilla/addons-frontend/issues/6612 
https://github.com/mozilla/addons-frontend/issues/6613

@kumar303 I don't know if the "Flag" button should be or can be removed for personal reviews and replies - user cannot flag it's own review or reply anyway.
