### ISSUE TITLE
moment-by-wetransfer

### ISSUE THREAD

**Issue by f0llows-you** [mozilla/addons-frontend#6460]
### What happened?
WeTransfer Moments Extension is not available. Article about WT on mozila websites have the link but not redirecting to extension.

### Anything else we should know?

https://blog.mozilla.org/internetcitizen/2018/07/31/wetransfer/ 
![image](https://user-images.githubusercontent.com/43313326/46254601-550c7200-c4af-11e8-8eab-824d469cfbf4.png)

**Comment by wagnerand** [comment]
The add-on is currently unavailable while the author addresses some issues found. Please contact the author for more information.

Thank you.
