### ISSUE TITLE
Update AddonReviewList to use new exclude_ratings API parameter

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6465]
Remove the code from AddonReviewList [that filters out the featured review](https://github.com/mozilla/addons-frontend/blob/2018.10.04-preview/src/amo/pages/AddonReviewList/index.js#L202) and instead use the `fetchReviews` action to pass the `reviewId` to the saga to exclude the review via the new `exclude_ratings` API parameter.

**Comment by bobsilverberg** [comment]
I started working on this and ran into an issue. We currently cache reviews in the reducer, which causes a problem if we filter via the API. Take this example:

1. A user visits a URL like http://localhost:3000/en-US/firefox/addon/view-page-archive-cache/reviews/564359/, which lists reviews and includes one specific review in a `FeaturedAddonReview` component. The API to fetch the reviews is called, and it is passed an `exclude_ratings` value of `564359`, which retrieves all reviews for add-on `view-page-archive-cache` *except for* the review with an `id` of `564359`. Those reviews are loaded into the redux store. 
2. The user clicks on the name of the add-on to get back to the details page, and then clicks on the reviews link from there, hoping to list all of the reviews.
3. The user lands on http://localhost:3000/en-US/firefox/addon/view-page-archive-cache/reviews/ but only sees one review because the reviews cached for `view-page-archive-cache` don't include the review with the `id` of `564359`.

Looking at the code for the various actions involved, I can see that when we fetch the individual review for the `FeaturedAddonReview` component, it doesn't get loaded into the state which is used for the review listing. We could potentially change that, so that it does load this review into state in such a way that it will appear in a subsequent rendering of the list, but there are a couple of issues with that:
1. The order of actions becomes important, as one completely replaces the state of the cached reviews and one adds to an existing state. If they don't run in the expected order (which is impossible to enforce, I believe), then it doesn't work. We could also change the bevahiour of `SET_ADDON_REVIEWS` so that it doesn't replace the state and works with an existing state, but I'm not sure that's a good idea either.
2. We still need to maintain the existing code that filters out the featured review client-side, because now it's going to be in the list anyway, which kind of makes the entire effort pointless.

Another option would be to stop caching the reviews and make sure that any navigation to the All Reviews page which does not include a `reviewId` fetches a new set of reviews. This is preferable to what I discussed above, but still seems like it doesn't really make this "enhancement" an improvement as now we'd be potentially issuing multiple API calls where currently we do not need to.

Based on all of the above, I'm not sure it actually makes sense to implement this change at all.

@kumar303 / @willdurand what do you think? Can you think of another way of making this all work that actually improves things? Maybe it makes sense to just keep things as they are?

**Comment by kumar303** [comment]
I'm not sure what the user impact is from reading this issue description but if it's only architectural, I suggest not spending time on it.

As for the caching issue, I would typically fix this by adjusting the "key" into the Redux state for the list of reviews. When the user navigates away from the featured review page back to the listing, a proper key would naturally force the listing page to reload all reviews.

It's always hard to get Redux keys right.

**Comment by bobsilverberg** [comment]
Thanks @kumar303. This would have near-zero user impact, so I think it's fine to just close it.
