### ISSUE TITLE
Sometimes the hero banner jumps in size on first page load

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6477]
### Describe the problem and steps to reproduce it:

* Clear all your cookies
* Load the prod home page
* Refresh the page a lot (10 or 20 times, nothing specific)

### What happened?

Sometimes, the hero banner jumps in size. It can go from small to big or big to small.

### What did you expect to happen?

The hero banner should not jump in size.

### Anything else we should know?

This happened both when I was pinned to a small banner and a large banner with the A/B cookie

**Comment by rebmullin** [comment]
I look into this a bit but since I can only replicate on prod I am not sure of the best way to test/debug. I have something I wanted to test but I have not been able to get charles proxy set up. Does anyone know if there is another way to test something like this?

**Comment by willdurand** [comment]
I am unable to reproduce locally:

- cookie is successfully loaded on the server
- cookie is successfully loaded on the client
- HOC is triggered on both the server and the client
- cookie value does not change over time

**Comment by AlexandraMoga** [comment]
This is verified fixed on AMO stage with FF62, Win10x64

I've tried with several new FF profiles and I'm, always getting the large hero variant, with no size distortions:

![hero large](https://user-images.githubusercontent.com/31961530/46401046-a3ff1500-c704-11e8-8c39-1704858658a7.gif)

**Comment by willdurand** [comment]
FTR: we added a bunch of logs to debug the issue in prod.

**Comment by kumar303** [comment]
After analyzing some logs on 2018-10-31 👻 , I was able to find a request ID like `cd7cc804-6775-4455-b5c8-cf1a2b743481` (and one other) which showed that the A/B variant cookie was getting generated twice. This led us to discover that our old version of `react-cookie` [uses a shared global object](https://github.com/reactivestack/cookies/issues/79#issuecomment-298998732) (specifically, [this](https://github.com/reactivestack/cookies/blob/v1.0.5/src/cookie.js#L5)) which can be polluted by any other request currently getting processed on the server. 

Since we do two server side renders for a given request, it's possible that the first or second render would read *someone else's* cookie. This might explain how the rendered HTML contained the wrong variant (not the one in the cookie) and would lead to the bug described up above. It would also explain how we only see the bug in production where the traffic is higher. 

This is an unproven theory but we are going to upgrade `react-cookie` anyway 😁
