### ISSUE TITLE
Bring back the tooltip for review permalinks

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6485]
Follow up for #6312 

STR:

1. Log in to AMO
2. Go to your user profile page
3. Scroll down to the Reviews section
4. Hover over the timestamp next to one of your listed reviews

Actual result:
There is no tooltip displayed to indicate the scope of this link

Expected result:
A tooltip should be displayed when hovering over a review timestamp. The titles should most likely be:
- for user reviews - 'Go to this review'
- for developer replies - 'Go to this reply'

Notes:
- reproduced on all AMO servers with FF62, Win10x64
![no tooltip](https://user-images.githubusercontent.com/31961530/46353142-2388d780-c664-11e8-93aa-9a4a89b8da92.gif)

**Comment by suhailsinghbains** [comment]
Hi,
Can I please be assigned this bug?

**Comment by willdurand** [comment]
@suhailsinghbains yep

**Comment by jvillalobos** [comment]
We decided we don't need this, since the link should be visible at the bottom of the window (as for all links in Firefox), which should make it clear what the link is for.
