### ISSUE TITLE
Align disco pane with inline content start

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#6486]
The discovery pane is currently centre aligned. There are some changes to the addons manager incoming for 64 that will match its width and alignment with the preferences page.

The width of the disco pane is good, but it should be left aligned as of Firefox 64. Due to some technical reasons, it looks like the easiest way to accomplish this will be to remove the centre alignment in the disco pane. Removing [this rule](https://github.com/mozilla/addons-frontend/blob/e1d2c4001131c9105ae349796558fce60124e09a/src/disco/pages/DiscoPane/styles.scss#L5) should align it correctly.

**Comment by willdurand** [comment]
Do you think it is going to be a problem with older versions (< 64)?

**Comment by mstriemer** [comment]
@brassy- should we only left align for 64+? Is it okay to left align it for the old about:addons, too?

**Comment by brassy-** [comment]
The old addons manager it’s not there anymore, isn’t it? Today in release I
saw the new one.

But to answer your question: yes, I think it’s ok.

Il giorno gio 13 dic 2018 alle 18:13 Mark Striemer <notifications@github.com>
ha scritto:

**Comment by ioanarusiczki** [comment]
I verified this issue with FF64, FF66, FF63 unbranded and FF52.9.0 esr on AMO dev (Win10). For all these versions the new alignment is left.

Disco pane is aligned to the left - this is now

![left alignment on dev](https://user-images.githubusercontent.com/33448286/50774930-7beff680-129d-11e9-800b-6e487227e4f9.png)

This was before - AMO stage with center alignment 

![center alignment on stage](https://user-images.githubusercontent.com/33448286/50774972-93c77a80-129d-11e9-8d50-5399d59204f1.png)
