### ISSUE TITLE
Remove `HomeHeroBanner` "small" variant and tracking code

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6490]
We do not want to show the "small" variant of the `HomeHeroBanner`, which was part of an A/B experiment. This issue is about removing this variant, but not entirely yet since we want to debug a potential issue in #6477.

We can also remove tracking code.

**Comment by AlexandraMoga** [comment]
Verified on AMO stage with FF62, Win10x64

I've checked with several profiles and the homepage is always rendering the large hero variant.
There are also no analytics events logged with regards to the hero experiment.

![hero large](https://user-images.githubusercontent.com/31961530/46400581-782f5f80-c703-11e8-920a-5d99e68364f7.gif)


@willdurand 
The `experiment_home_hero` cookie is preserved, though.  Is this only for debugging purposes, as mentioned in the comment above?

<details>
<summary> Console log </summary>

[WithExperiment.constructor] props: Object { _cookie: {…}, variantA: "small", variantB: "large" }
[WithExperiment.constructor] this.props: Object { _cookie: {…}, variantA: "small", variantB: "large" }
[WithExperiment.constructor] cookie name: experiment_home_hero
[WithExperiment.constructor] experiment cookie loaded: large 
[WithExperiment.render] exposed props: Object { experimentEnabled: true, variant: "large" }
[HomeHeroBanner.render] variant is: large 
[HomeHeroBanner.componentDidMount] variant is: large

</details>

**Comment by willdurand** [comment]
>  The `experiment_home_hero` cookie is preserved, though. Is this only for debugging purposes, as mentioned in the comment above?

Yes, exactly!

**Comment by willdurand** [comment]
@AlexandraMoga oops, looks like the deployed version on -stage is not correct, please wait a bit. I have pushed a new tag and it should be deployed soon-ish.

You can check the deployed version with this add-on BTW: https://addons.mozilla.org/en-US/firefox/addon/amo-info/

**Comment by AlexandraMoga** [comment]
@willdurand everything looks good now, thanks.
