### ISSUE TITLE
Listed owner / developer cannot edit other developer responses

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6491]
### Describe the problem and steps to reproduce it:

* As a developer, create an add-on
* In the Devhub, add user1 as a listed Owner and user2 as a listed Developer
* Sign into AMO as the main developer, go to your add-on's review listing, and reply to a review
* Sign into AMO as user1 or user2 and try to edit the reply

### What happened?

There is no way to edit the developer response.

### What did you expect to happen?

Since listed owners and developers may collaborate as a team, they may want to edit each other's responses.

**Comment by ioanarusiczki** [comment]
I verified this scenario on AMO dev with FF62 (Win10)
The edit works for added owners or developers.
@kumar303 The delete is not allowed and I don't know if it's the intended behavior or not so let me know if I should file an issue. 

![cannot delete](https://user-images.githubusercontent.com/33448286/46617019-6d6e3380-cb24-11e8-9ae8-2a047e0ae05d.png)

**Comment by ioanarusiczki** [comment]
After debating this I filed on server this issue https://github.com/mozilla/addons-server/issues/9633
