### ISSUE TITLE
11 October homepage content update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#6493]
For the **11 October** push, please update homepage content as detailed [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch

**Comment by ioanarusiczki** [comment]
Page looks good with AMO dev FF62- Win10 
Full validation will be made in production.

**Comment by vcarciu** [comment]
Verified as fixed in prod
