### ISSUE TITLE
DECPRECATION WARNING when running commands for the frontend

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6496]
I notice this warning whenever running commands from the console for the frontend:

`DECPRECATION WARNING: the xmlchar *module* is deprecated: please replace e.g. require('xmlchars') with require('xmlchars/xml/...')`

**Comment by willdurand** [comment]
This warning message is caused by a dependency of `jsdom`, called `saxes`. A patch version has been issued: https://github.com/lddubeau/saxes/blob/master/CHANGELOG.md#313-2018-10-01, it should not take too long for `jsdom` to release a new version.

**Comment by willdurand** [comment]
I don't see this message anymore so I suppose it has been fixed by an upgrade.
