### ISSUE TITLE
Delete all code related to the old overlay review flow

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6500]
The inline review flow is landing! https://github.com/mozilla/addons-frontend/issues/6349

Let's delete all code for the old overlay flow.

**For QA**: please make sure that creating / editing ratings and reviews still works.

**Comment by willdurand** [comment]
🏆

**Comment by ioanarusiczki** [comment]
I tested the ratings, reviews and developer replies on the detail page, from the user profile page and the reviews page on AMO dev with FF63(Win10).
Besides the [known issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3A%22component%3A+add-on+ratings%22label%3A%22type%3A+bug%22+label%3A%22priority%3A+p3%22+) I filed https://github.com/mozilla/addons-frontend/issues/6827
