### ISSUE TITLE
Update static theme size in header and search

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6507]
AMO: Update the header and search to use the 720 preview width as discussed in the following issues:

dependency: https://github.com/mozilla/addons-server/issues/9519
Also see REF: https://github.com/mozilla/addons-server/issues/9419

**Comment by rebmullin** [comment]
hey @jvillalobos, I guess we should update the preview in disco too?

**Comment by kumar303** [comment]
> hey @jvillalobos, I guess we should update the preview in disco too?

Let's track this in https://github.com/mozilla/addons-frontend/issues/7553

**Comment by kumar303** [comment]
Note that the images in our social media cards (e.g. [twitter cards](https://cards-dev.twitter.com/validator)) and search result metadata were also updated by this patch.
