### ISSUE TITLE
Update the versions reducer to use the correct file

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6510]
This is a follow-up to #6473. The current code in `reducers/versions.js` just uses the first file for a given version to provide the `created` and `filesize` properties, but we should really find the correct file to use, using logic similar to that found in [`findInstallURL`](https://github.com/mozilla/addons-frontend/blob/2018.10.11/src/core/installAddon.js#L222). This will likely involve refactoring [`installAddon.js`](https://github.com/mozilla/addons-frontend/blob/2018.10.11/src/core/installAddon.js) and possibly other modules as well.

**Comment by ioanarusiczki** [comment]
I tested the install on AMO dev - FF62 (Win10 and Android 8.0) - no regressions found
I've noticed two issues while testing and I filed them here https://github.com/mozilla/addons-frontend/issues/6652 and here https://github.com/mozilla/addons-frontend/issues/6650
