### ISSUE TITLE
Use photon cards style in discovery pane

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#6514]
The about:addons page is moving to the new photon style cards. This should happen in Firefox 64 at which point the disco pane and about:addons would be out of sync visually. We should update the card styles to match the new photon styles in the rest of about:addons.

The spec for the photon styles are in the [style guide](https://design.firefox.com/photon/components/card.html), but the gist of the change is:

```
:root {
  --grey-30: #d7d7db;
  --shadow-10: 0 1px 4px rgba(12, 12, 13, 0.1);
  --card-shadow: var(--shadow-10);
  --card-shadow-hover: var(--card-shadow), 0 0 0 5px var(--grey-30);
}

.card {
  border-radius: 5px;
  box-shadow: var(--card-shadow);
  transition: box-shadow 150ms;
}

.card:hover {
  box-shadow: var(--card-shadow-hover);
}
```

<img width="1113" alt="screenshot 2018-10-02 16 45 31" src="https://user-images.githubusercontent.com/211578/46487023-4a2f4580-c7ff-11e8-9760-58b9ea8de947.png">

**Comment by jvillalobos** [comment]
This will be deferred to Q1, unless someone has spare cycles to take it on before then.

**Comment by willdurand** [comment]
> This should happen in Firefox 64

Does that mean we need to support a different UI for ESR and older versions?

**Comment by willdurand** [comment]
> This should happen in Firefox 64

Does that mean we need to support a different UI for ESR and older versions? /cc @muffinresearch

**Comment by mstriemer** [comment]
Since there aren't any other cards in about:addons and the new styles already exist in about:newtab I would say this can go out whenever it's ready. /cc @brassy-

**Comment by willdurand** [comment]
> Since there aren't any other cards in about:addons and the new styles already exist in about:newtab I would say this can go out whenever it's ready. /cc @brassy-

Ah right, thanks. Given that the shield study ends next week, it can be done anytime.

**Comment by mstriemer** [comment]
After discussing with product, they're okay with the current design for now.
