### ISSUE TITLE
Install buttons reload when disco pane is opened with "about:addons" 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6524]
STR:
1. Load disco pane in a new tab by typing in "about:addons"
2. Observe the install buttons 

Expected result:
Buttons are displayed

Actual result:
Buttons reload

Notes:
This is also reproducible when the FF profile is opened and diso pane is left open in a tab from a previous session. - with FF62&FF64 - Win10
It is not reproducible when disco pane is opened from the FF menu or from tools (with "alt" key).

![refresh install buttons](https://user-images.githubusercontent.com/33448286/46528245-f7f03200-c89b-11e8-9a1c-94f9b7254f4c.gif)

**Comment by willdurand** [comment]
@ioanarusiczki I don't understand the issue. What do you mean by "reload"?

**Comment by ioanarusiczki** [comment]
@willdurand Like a button refresh - it's visible in the above .gif. Or just type about:addons in the browser with FF62 - watch the buttons

**Comment by willdurand** [comment]
I am sorry, I am still not sure to understand. The `mozAddonManager` updates the status of the different buttons, that's why buttons 1 and 3 blink once the page has loaded.

This has been the behavior for a while, we can see the same thing with the "switch" buttons in -prod. It is less visible with the switches, but it is the same thing.

**Comment by ioanarusiczki** [comment]
@willdurand Hmmm, it just seemed strange to me that they don't blink when disco pane is opened from the Menu when Add-on is clicked or from Tools, so it's 2 different behaviors.
You're right , the prod switch buttons do the same thing only it's less visible.  - FF62(Win10)

Prod switch buttons
![refresh install buttons prod](https://user-images.githubusercontent.com/33448286/46597644-bbb21100-cae9-11e8-9ce8-3ba18f5a708e.gif)

**Comment by willdurand** [comment]
I don't think we can do anything about it, closing this issue and marking it as wontfix.
