### ISSUE TITLE
Use user ID in all links to user profile pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6526]
In #6275, we want to redirect users browsing a user profile page with the `username` in the URL to the canonical URL, which contains the user ID.

1. We should change all links and the routing config to consider the user ID as the default parameter in the URL (currently, it is `username`).
2. All links to the user profile pages (and probably edit pages too) should use the user ID and not the username anymore.

**Comment by willdurand** [comment]
@muffinresearch are we OK with doing this? It seems required to enable https://github.com/mozilla/addons-server/issues/8302

**Comment by ioanarusiczki** [comment]
@willdurand 
- the view profile page will display user's ID in the URL (clicked from the More Menu or from a detail page) . Users with admin right (click Admin user button) have https://addons-internal.dev.mozaws.net/en-US/admin/models/users/userprofile/ID/change/
Also the canonical link displays the user ID.

- the edit profile page has the following format https://addons-dev.allizom.org/en-US/firefox/users/edit 
The only situation when edit page contains the ID is when as an admin I click on someone else's edit profile page and it looks like https://addons-dev.allizom.org/en-US/firefox/user/ID/edit/
Let me know if it's alright the way it is now for the edit page.

![edit profile - no id](https://user-images.githubusercontent.com/33448286/49146272-7ac8c280-f30a-11e8-9677-48e5d34ce59b.gif)

**Comment by willdurand** [comment]
That looks good to me.

**Comment by ioanarusiczki** [comment]
@willdurand Ok then. This is verified with FF63 (win10).
