### ISSUE TITLE
Add canonical link tag to user profile pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6527]
See also: #5755 

---

We should add:

```
<link rel="canonical" href="<URL of the user profile with user ID>" />
```

We have to determine how to pass the query string parameters (for pagination).

**Comment by willdurand** [comment]
@rraue this issue needs your input because the user profile can be paginated (as discussed on Slack). If I remember correctly, you said a canonical URL has no query params in any case, right?

If that's the case, that'd be easy to implement :)

**Comment by rraue** [comment]
No thats not correct, looks like I wrote not understandable enough:

- The canonical should be always without a parameter which doesn't alter the content (just sort or filters it, utm or referer data)
- But these pages are only available with a parameter url, therefore these parameter pages are unique

https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/?page_t=2 has different content (even if the content is just links to content like in this case) than page 3 and if all canonicals would point to https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/ it would be harder to index the themes/extentions on page X.

So in this case:

- https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/ must have <link rel="canonical" href="https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/" />
- https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/?page_t=2 must have <link rel="canonical" href="https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/?page_t=2" />
- https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/?page_t=3 must have <link rel="canonical" href="https://addons.mozilla.org/en-US/firefox/user/sassygirl1016/?page_t=3" />
- etc.

**Comment by willdurand** [comment]
ok great, that makes more sense. In case of different parameters, what do you suggest? we sort the query params alphabetically?

**Comment by rraue** [comment]
I don't understand, which different parameters? Do you have an example?

**Comment by willdurand** [comment]
Find a profile with both extensions and themes. There are two parameters: `page_t` and `page_e`, one for themes and one for extensions.

**Comment by willdurand** [comment]
That comment applies to search result pages too.

**Comment by rraue** [comment]
Okay, now I got it. That's a really complicated setup. Wouldnt it be easier and better UX to separate the themes and extensions pages? If you as a user want to see the themes of a user, you need to scroll all the way down and besides the small icon on the top, nothing indicates the profile has created themes as well. 

It is possible to do all the canonical work here, but I want to first check if separation wouldn't be an overall better solution? How will this be in the new design @MeridelW, same or differnet?

**Comment by willdurand** [comment]
> Okay, now I got it. That's a really complicated setup. Wouldnt it be easier and better UX to separate the themes and extensions pages? If you as a user want to see the themes of a user, you need to scroll all the way down and besides the small icon on the top, nothing indicates the profile has created themes as well.
> 
> It is possible to do all the canonical work here, but I want to first check if separation wouldn't be an overall better solution? How will this be in the new design @MeridelW, same or different?

This is pretty much the latest/new design. See also: https://mozilla.invisionapp.com/share/YCCYEOFRH#/310799956_User_Profile_-_View_-_1366px. There is no plan to change that page any time soon and not a lot of users will have both sections AND a lot of pages for each add-on type.

On a more personal note, I do prefer to have everything the user has produced on a single page rather than browsing different pages.

**Comment by rraue** [comment]
If we don't want to change it, here is what we need to do:

both page_e=X and page_t=X sort content, so all possibilities need to be indexed but we need to make sure, that not all combinations are indexed.

I will assume a example profile with both three pages for extensions and three for themes and here is a list of all combinations and their canonicals: [AMO profile pages canonicals](https://docs.google.com/spreadsheets/d/1mlH_i6fSsuYqPcy_p-wUE7jCOrMVKQsE6FuAig8OPXM/edit#gid=0)

In the example with 3 pages for themes and 3 pages for extensions we have 25 different url combinations of all these paginated profile urls and we can reduce it to 5 indexed pages. 

The logic is:

- The url is canonicalized always to just one parameter
- If all parameters are =1 the url is canonicalized to the main profile url
- A page with just one parameter if not =1 is canonicalized to itself
- Pages with two parameters are canonicalized to the higher value parameter
- Pages with two parameters with the same are canonicalized to the parameter first in the url

Please double check if my logic makes sense and have a look in the document as well.

**Comment by willdurand** [comment]
@rraue if we want to add `alternate` links, we will not add alternate links on most paginated pages because canonical URLs will only have one parameter (at most) and we must ensure `currentURL == canonicalURL`.

Is that ok to only add `alternate` links to the user profile pages when the current URL (in the browser) is equal to the computed canonical URL as per your instructions above?

**Comment by willdurand** [comment]
Example:

- current URL: `http://localhost:3000/en-US/firefox/user/10641574/?page_t=3`
- canonical URL: `http://localhost:3000/en-US/firefox/user/10641574/?page_t=3`
- alternate link (for `pt`): `http://localhost:3000/pt-PT/firefox/user/10641574/?page_t=3`

Example 2:

- current URL: `http://localhost:3000/en-US/firefox/user/10641574/?page_t=3&page_e=2`
- canonical URL: `http://localhost:3000/en-US/firefox/user/10641574/?page_t=3`
- no alternate links

**Comment by ioanarusiczki** [comment]
@willdurand I'm adding that the `hreflang` links and `og` meta data was added too. 
`og:description` "The profile of AdminUserTestDev, a Firefox extension and theme author. Find other apps by AdminUserTestDev, including average ratings, tenure, and the option to report issues." 
`og:image` has the standard image URL https://addons-amo-dev-cdn.allizom.org/cdecc075e09aee4207a940a3efd67cb8.png 

![alternate links](https://user-images.githubusercontent.com/33448286/49152475-9f796600-f31b-11e8-9b1e-7ec6c0b033db.png)
