### ISSUE TITLE
Display Category name on Category page

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#6531]
When you go to a category page, for example https://addons.mozilla.org/en-US/firefox/search/?category=download-management&sort=rating&type=extension, you see "531 add-ons found" but no indication that these are add-ons in the Download Management category.

We should change it to say "X add-ons found in $Category" for all category pages.

**Comment by atsay** [comment]
Sounds good to me.

**Comment by rebmullin** [comment]
hey @jvillalobos, thanks for the breakdown. That's a big help. I'll also look into the themes to see what's going on there...

**Comment by ioanarusiczki** [comment]
@rebmullin 
I verified this issue on AMO dev with FF64 (Win10). 
- the name of the categories is displayed now when the "See more links" are clicked inside each category for extensions and themes. 

![issue is fixed](https://user-images.githubusercontent.com/33448286/51846231-da9b1400-2321-11e9-9a1d-1046b37a989a.gif)

- search tools were not mentioned [here ](https://github.com/mozilla/addons-frontend/issues/6531#issuecomment-428375366) so when a search is made using a query and the filter is "search tools" "results" is displayed.  @jvillalobos Let me know if it's how you expect it to be or if I should file an issue to make it look like: N search tools found for "$Query"

![n search tools found](https://user-images.githubusercontent.com/33448286/51846399-2fd72580-2322-11e9-892b-ae2c933bb835.gif)

**Comment by atsay** [comment]
Jorge's out today so I'll answer--yes, please file an issue to show "search tools". Will leave it up to Jorge to prioritize. Thanks!

**Comment by ioanarusiczki** [comment]
@atsay Thanks for your answer! I filed it here https://github.com/mozilla/addons-frontend/issues/7508
This looks good on Android too. I'm marking it verified on AMO dev with FF64 (Win10 and Android 8.0)

![android search in categories](https://user-images.githubusercontent.com/33448286/51903042-0bcc2080-23c4-11e9-8350-27b0a2203e5f.png)
