### ISSUE TITLE
Can't view collection on addons.mozilla.org

### ISSUE THREAD

**Issue by Mireille005** [mozilla/addons-frontend#6533]
### Describe the problem and steps to reproduce it:
I got this page  moz-extension://525e6efa-755b-47a5-93c7-37e97417c2ac/notification/notification.html
stating "If you enjoyed using the Favorites feature in Personas Plus to save your favorite themes, please create a new collection on addons.mozilla.org. "
So I followed the link to the addons page, logged in and clicked on 'view collections' then I got the error below.

### What happened?
I got this message:
> Server Error
> Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.
> Suggested Pages
>     Browse all extensions
>     Browse all themes
>     Add-ons Home Page
> If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it.

### What did you expect to happen?
I want to see my collections, as stated on the first mentioned URL

### Anything else we should know?
If you want to kill a beloved addon and make it difficult for users to keep a collection of loved themes, either provide a theme-addon of siimilar quality or at least let your own site work as you promised on the same site.

**Comment by jvillalobos** [comment]
What's your username on addons.mozilla.org?

**Comment by Mireille005** [comment]
Thank you for responding.
My username is Mireille005. Hope you can help me, greatly appreciated.

Kind regards,
Mireille

**Comment by Mireille005** [comment]
I’ve tried renaming that. However, shouldn’t it be possible to have public ánd private collections?

Kind regards,
Mireille

**Comment by jvillalobos** [comment]
It used to be possible to make that distinction. We recently removed it, but we haven't changed anything about the old private collections. That's what makes me think this collection could be the source of the problem.

**Comment by willdurand** [comment]
We've updated a few things related to collections. We might have fixed your issue (but maybe not). I'm closing this issue for now but feel free to reopen it if that still does not work.
