### ISSUE TITLE
Add request-id in log calls

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6537]
It is currently not possible to correlate our log entries in Kibana because we do not have a unique identifier to focus on a specific request. We should generate and use a [request id](https://blog.heroku.com/http_request_id_s_improve_visibility_across_the_application_stack) in our frontend app, this ID would be passed to ALL `log` calls. It could also be passed to the API. 

⚠️ It MUST NOT be passed to third party services.

---

### Why it is not trivial?

- we use one "instance" of the logger everywhere, in a static way
- we need to generate an ID that is unique and request-scoped (one unique ID per request)
- the logging and HTTP layers are distinct
- same logger for client and server

**Comment by willdurand** [comment]
I think we could use this lib: https://www.npmjs.com/package/express-http-context to inject the request ID and retrieve it in the logger (because the logger is a sort of singleton).

**Comment by willdurand** [comment]
So I've got a patch working, it is not the easiest one to understand but it looks okay given our current code base: https://github.com/mozilla/addons-frontend/compare/request-id.

A few notes:

- it uses `express-http-context`, which creates a request-scoped context (a.k.a. shared storage in memory)
- it tells webpack to skip `express-http-context` at build time using the `browser` config in the `package.json`. On the client, the `import` will return an empty object, on the server it will load the lib since there is no compilation step
- the exposed logger is not `pino` anymore but a "decorated logger" that only exposes the log level methods
- each log level method adds the correlation ID to the log message by using the `mergingObject` first/optional argument, but only on the server: https://github.com/pinojs/pino/blob/master/docs/api.md#mergingobject-object
- on the server, two new middleware have been added
  - the first one is used to create the http context
  - the second one generates the correlation ID and adds it to both the HTTP context and response
- if a correlation ID is found in the request, it is used (this is how trace/request ids work usually)

**Comment by kumar303** [comment]
In general, the approach looks good. I had to learn about [continuation-local storage](https://github.com/jeff-lewis/cls-hooked#readme) -- it looks good. It uses "experimental" APIs in Node 8 so that's maybe something we should be aware of.

I'd rather not use webpack magic to exclude `express-http-context` from the client. Maybe there is another way? We could turn `core/logger` into a singleton where you'd need to set the logger before you can use it. The server code would begin by setting a server logger and the client would begin by setting its own logger. I dunno, that has other complications. Just a thought.

**Comment by willdurand** [comment]
> I'd rather not use webpack magic to exclude `express-http-context` from the client. Maybe there is another way?

I don't think so because, before pino, we already relied on a webpack feature (to replace the logger in the client). We must tell webpack to not "see" `express-http-context` in one way or another, because if it finds it, then it breaks (because cls is not supported in the browser).

I don't have a better solution in mind to keep things very similar and rather simple (the `"browser"` entry in the `package.json` is not an hidden webpack feature).

**Comment by willdurand** [comment]
So I might have found another way, i.e. publishing a "universal" package of `express-http-context`.

**Comment by willdurand** [comment]
The test suite needs a LOT more memory now that we rely on `express-http-context` 😭  It can be a memory leak or... < something something >.

**Comment by willdurand** [comment]
So, I load tested my patch in #6672 using [`siege`](https://www.joedog.org/siege-home/). Here are the instructions:

1. Install `siege`:

```
brew install siege
```

2. Apply this patch to enable node inspection:

```diff
diff --git a/package.json b/package.json
index 4914018dc..c279f255f 100644
--- a/package.json
+++ b/package.json
@@ -136,7 +136,7 @@
       }
     },
     "start-dev-proxy": {
-      "command": "npm run clean && concurrently 'npm run webpack-dev-server' 'node bin/server.js | pino-devtools --mode buffer --tee | pino-pretty' 'node bin/proxy.js | pino-pretty'",
+      "command": "npm run clean && concurrently 'npm run webpack-dev-server' 'node --inspect bin/server.js | pino-devtools --mode buffer --tee | pino-pretty' 'node bin/proxy.js | pino-pretty'",
       "env": {
         "ENABLE_PIPING": "true",
         "NODE_ENV": "development",
```

3. Start AMO:

```
yarn amo:dev
```

4. Use Chrome to open the Node devtools at `chrome://inspect`
5. Select the "memory" tab to take Heap memory snapshots
6. Run `siege`:

```
timeout 30s siege http://localhost:3000
timeout 30s siege http://localhost:3000/en-us/firefox/
timeout 30s siege http://localhost:3000/en-US/firefox/
```

7. Take multiple snapshots, before/during/after putting the app under siege.

**Comment by willdurand** [comment]
An example of my `master` branch snapshots:

![screen shot 2018-10-18 at 13 12 16](https://user-images.githubusercontent.com/217628/47150630-71921200-d2d7-11e8-98f2-b6ff5c27cf6b.png)

**Comment by willdurand** [comment]
An example of my `request-id` branch snapshots:

![screen shot 2018-10-18 at 13 18 34](https://user-images.githubusercontent.com/217628/47150878-5c69b300-d2d8-11e8-86d9-77f2a435a41d.png)


I don't think there is any obvious memory leak, so that looks good to me.
