### ISSUE TITLE
Enable `AMInstallButton`(new install button) on Disco Pane (all envs)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6539]
Once the [TAARDIS 🤓 shield study](https://docs.google.com/document/d/1m_zmiVh1Oq8sz4NPjEQJz5k3MJZSVdpfr6Ar2IvyQpI/edit#heading=h.415z7jbc6cfq) has ended, we should enable the new install button on Disco Pane.

For QA: we should see the new install buttons in -stage and -prod.

**Comment by willdurand** [comment]
Marking as blocked since there is a running shield study.

@muffinresearch it is written September/October in the Google doc but do we have a more precise end date?

**Comment by muffinresearch** [comment]
@willdurand: @mstriemer asked Martin last week and I think he said the study would be ending on the 15th October.

**Comment by willdurand** [comment]
This is re-scheduled for early November (shield study ends October 29th)

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO stage with FF63 unbranded (Win10)
The only thing that I noticed that works different compared to what's in production is when a lw theme is installed from disco pane or from theme's detail page.

On AMO stage the Install message is displayed asking to Allow or Cancel the installation, same way as for extensions - this is with FF63 unbranded. 

![lw themes messages](https://user-images.githubusercontent.com/33448286/47793752-a8304980-dd27-11e8-8251-7c7836d75862.gif)

On AMO prod the theme is automatically installed, no message displayed from disco pane or from the detail page.

![currently in prod](https://user-images.githubusercontent.com/33448286/47793945-12e18500-dd28-11e8-875d-47c716a90fdf.gif)

**Comment by willdurand** [comment]
> @willdurand Verified on AMO stage with FF63 unbranded (Win10)
> The only thing that I noticed that works different compared to what's in production is when a lw theme is installed from disco pane or from theme's detail page.
> 
> On AMO stage the Install message is displayed asking to Allow or Cancel the installation, same way as for extensions - this is with FF63 unbranded.

Isn't it because of the prefs you had to set?

**Comment by ioanarusiczki** [comment]
@willdurand I am not 100% sure is because of the prefs set for testing on AMO dev and AMO stage.  I tried again with a clean profile with FF63 release, FF63 unbranded and FF65 but still same results.
However, Lw themes migrate to static themes soon and in their case this message is not displayed.
