### ISSUE TITLE
Add "Developer Policies" to footer

### ISSUE THREAD

**Issue by MeridelW** [mozilla/addons-frontend#6548]
With input from legal and Mike Conca, we should add the Developer Policies (https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/AMO/Policy) to the footer of the AMO front-end site. 

When we launch a new Developer Hub landing page in November (formerly known as the "developer launchpad"), we want to clearly point devs to the policies in the footer, which employs the front-end footer (rather than current Dev Hub footer).

See the attached screenshot for illustration of the requested change.

![developer policies](https://user-images.githubusercontent.com/33848177/46632576-bfa55980-cb10-11e8-86c9-98ddb3deb66e.png)

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF62 - Win10
"Developer Policies" link is available on the new AMO pages in the footer below "Developer Hub"
![developer policies](https://user-images.githubusercontent.com/33448286/46872607-40c85d80-ce3d-11e8-82a4-c24fdeec383f.gif)
