### ISSUE TITLE
Link to Britannica Insights not working

### ISSUE THREAD

**Issue by robertmoose** [mozilla/addons-frontend#6553]
### Arrived at a page not found page on firefox
<img width="1528" alt="screenshot 2018-10-09 at 08 29 41" src="https://user-images.githubusercontent.com/3903534/46653285-82d37400-cb9d-11e8-836a-2b42ebb098e3.png">

**Comment by jvillalobos** [comment]
The add-on was disabled due to review issues. It's up to the developer to upload a new version that addresses those issues.
