### ISSUE TITLE
Add OpenGraph tags on other pages (not add-on detail pages)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6555]
Once #5766 is fixed, we will have descriptions for most pages on AMO. We could expose OpenGraph tags on most pages (including the homepage, excluding the search results) using:

- type: `website`
- description from #5766 
- title
- canonical URL from #5755 
- locale

**To go further**, we could add an image. Google uses [their logo](https://ssl.gstatic.com/chrome/webstore/images/chrome_web_store-128.png), but Facebook recommends a larger image (1200 x 630 pixels).

@pwalm do you think we could create a large image explaining what AMO is? Something slightly more engaging than a logo?

**Comment by rraue** [comment]
I think that's a good idea, but I would leave out  og:url as FB anyways uses the canonical over their own og:url.

**Comment by willdurand** [comment]
@rraue quick question: is it required to have an image? Or can it be an improvement?

**Comment by rraue** [comment]
I dont think that any og-tag is required, but the image is the most important one, as ctr in fb depends even more on the image than on the title, but fb will take one of the pictures on the page to show, if we do not provide the og:image.

We can ship code without og:image but we should keep in mind that og:image is the most important og-tag regarding ctr on fb.

**Comment by willdurand** [comment]
/cc @pwalm for a picture.

A few examples:

- GitHub blog

![](https://user-images.githubusercontent.com/7321362/26907144-178243fc-4ba6-11e7-8f15-8985451b33c2.jpg)

- NY Times

![](https://mwcm.nyt.com/.resources/mkt-wcm/dist/libs/assets/img/meta-og-image-fallback.jpg)

**Comment by willdurand** [comment]
@pwalm ^

**Comment by ioanarusiczki** [comment]
@willdurand The pages that contain `OpenGraph tags` other than detail pages: Homepage, Extensions page and all categories, Themes page and all categories, Dictionaries and Language Packs, Search Tools, About, Review Guide.

- all these pages display in the HTML the `og:URL` I'm not sure this is intended.
- all the pages have `<meta name="description" content="Download Firefox dictionaries and language pack extensions. Add a new language option to your browser spell-checker, or change the browser's interface language." data-react-helmet="true">`

 as well as

 `<meta property="og:description" content="Download Firefox dictionaries and language pack extensions. Add a new language option to your browser spell-checker, or change the browser's interface language." data-react-helmet="true">`  

Let me know if it's ok.

**Comment by willdurand** [comment]
> all these pages display in the HTML the `og:URL` I'm not sure this is intended.

yes, we keep it

**Comment by willdurand** [comment]
@ioanarusiczki for the description, each page has its own desc, but it is the same content in the two `meta` tags, right?

**Comment by ioanarusiczki** [comment]
@willdurand Yes, correct. The descriptions for each page was added before and verified, it was a dedicated issue for that.  And they're identical in the two meta tags.
