### ISSUE TITLE
Do not show a "Content review add-on" link for themes

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6559]
This is a follow-up to #4632 

[Quoting](https://github.com/mozilla/addons-frontend/issues/4632#issuecomment-428234938) @wagnerand:

> Then themes shouldn't show a "content review add-on" button.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF62(Win10)

Admins and Content reviewers don't see the "Content Review add-on" link for themes (lw and static)
