### ISSUE TITLE
Make sure that the "review theme" link points to the correct place for LWTs

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6574]
Followup for https://github.com/mozilla/addons-frontend/issues/4632

Prerequisites:
The user must be a theme reviewer - added into the  "Reviewers:Themes" group in Admin Tools

STR:
1.  Load AMO dev and go to a lw theme's detail page and click the "Review Theme" link
2. Observe the page

Expected result:
The user is redirected to the theme review page.

Actual result:
The reviews page is not displayed Oops! Not allowed.

Notes:
This issue is not reproducible for static themes - theme reviewers users
This issue is reproducible with FF62- Win10

![lw theme clicking the link](https://user-images.githubusercontent.com/33448286/46722668-c6ea7580-cc7e-11e8-8dd4-b1eb43ee7b0d.gif)

**Comment by bobsilverberg** [comment]
I'm not sure I understand what the fix is for this. Should we not be showing the "Review theme" link for lwts?

cc @wagnerand

**Comment by wagnerand** [comment]
I believe the following

>  The reviews page is not displayed Oops! Not allowed.

has one "not" too much.

Other than that, I believe this is a valid bug. Theme reviewers should be able to access the theme review page (even if it's a lightweight theme).

**Comment by bobsilverberg** [comment]
> I believe this is a valid bug. Theme reviewers should be able to access the theme review page (even if it's a lightweight theme).

@wagnerand So that would need an issue opened for addons-server, correct? That functionality is not in the frontend site, I believe.

**Comment by wagnerand** [comment]
@bobsilverberg I was wrong. The bug is that the link points to the wrong page. It should go to `/reviewers/themes/queue/single/SLUG`

**Comment by bobsilverberg** [comment]
@wagnerand Should `/reviewers/themes/queue/single/SLUG` be the new link for all themes, or is that only for lwts, and should other themes still use `/reviewers/review/SLUG`?

**Comment by wagnerand** [comment]
I believe it's:

`/reviewers/review/SLUG` for static themes.
`/reviewers/themes/queue/single/SLUG` for lightweight themes.

But let's confirm with @eviljeff...

**Comment by bobsilverberg** [comment]
@eviljeff Do you mind confirming @wagnerand's recommendation above?

**Comment by eviljeff** [comment]
Yes, I think thats correct.  With the same caveat about not spending much time on fixing something that will be obsolete in a few weeks.

**Comment by bobsilverberg** [comment]
Thanks @eviljeff. As with the other one, it's a simple fix, so we might as well do it.

**Comment by ioanarusiczki** [comment]
I checked this again with an Admin account then for theme reviewers users.  
Lw themes  link goes to  `/reviewers/themes/queue/single/SLUG` 
Static themes link goes to `/reviewers/review/SLUG`

![review theme link for lw](https://user-images.githubusercontent.com/33448286/46862053-bcfe7900-ce1c-11e8-8b65-9ca1f309a07f.gif)

verified on AMO dev with FF62 (Win10)
