### ISSUE TITLE
Show small stars in delete review / rating prompts

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6577]
This is a follow-up to https://github.com/mozilla/addons-frontend/issues/6347

Here is how to see the deletion confirmation UI:

- Sign in
- Go to an add-on detail page
- Rate the add-on
- Click *Delete rating*
- Or ... Write a review
- Click *Delete review*

Here are the changes we need:
* The stars should be made smaller in the confirmation UI according to the mocks (below).
* When deleting a review, there should be a prompt at the top like *Are you sure you want to delete your review of AddonName?*

## Known issues

* We intend to always show the *Report this add-on for abuse* button even though it's not in the mocks. See https://github.com/mozilla/addons-frontend/issues/6307#issuecomment-426713063

![ratings and reviews flow v2](https://user-images.githubusercontent.com/55398/45894396-ceabae00-bd93-11e8-9b44-cdb7bc82eb2e.png)

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev - FF62 (Win10)

deleting a rating on the detail page - stars are available
![delete rating shows the stars](https://user-images.githubusercontent.com/33448286/47348693-b5f82600-d6ba-11e8-9d78-4d7de48f5b57.gif)

deleting a review on the detail page - stars are available 
![delete review shows the stars](https://user-images.githubusercontent.com/33448286/47348731-cad4b980-d6ba-11e8-9614-df7c13bec7ef.gif)
