### ISSUE TITLE
Center text alignment makes the homepage collections shelf look inconsistent in some locales on Android

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6588]
STR

1. Load AMO homepage on mobile
2. Change your locale to  `es`, `fr`
3. Observe the "Customize the way Firefox works..." shelf

Actual result:
Some collection titles look inconsistent

Expected result:
Collection title alignment should look the same for all the shelf items

Notes:
- reproduced on all AMO servers with FF62, Android 8.0

![image](https://user-images.githubusercontent.com/31961530/46795498-f2d72b00-cd52-11e8-8924-c714fd546ff1.png)

**Comment by kumar303** [comment]
Good catch, thanks.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF62, Win10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/46938915-a438d200-d06d-11e8-824c-65fe35ac0cd5.png)

![image](https://user-images.githubusercontent.com/31961530/46938937-af8bfd80-d06d-11e8-968d-682b0d69ae62.png)

![image](https://user-images.githubusercontent.com/31961530/46938950-b4e94800-d06d-11e8-99ad-b37d6b7df822.png)
