### ISSUE TITLE
Make sure the "edit add-on" link directs to the correct page for LWTs

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6590]
STR:
1. Load AMO dev and login with an admin account
2. Go to a theme's detail page and click the "Edit add-on" link
3. Observe the page

Expected result:
It should direct to the Listing page of the lw theme such as [this](https://addons-dev.allizom.org/en-US/developers/theme/three-wolf-moon-shirt/edit) one 

Actual result:
We're sorry, but we can't find what you're looking for.

Notes:
Reproducible on AMO dev and AMO stage - FF62(Win10)

![lw themes edit addon](https://user-images.githubusercontent.com/33448286/46802541-47d06c80-cd66-11e8-82aa-bd148d4d3edf.gif)

**Comment by wagnerand** [comment]
What permissions does the admin account have? Afaik, you need to be in a group with `Addons:Edit`.

**Comment by bobsilverberg** [comment]
@wagnerand That link appears if the user has the `Addons:Edit` permission. 

Looking at the issue report, it looks like @ioanarusiczki is suggesting that the link should point to `/developers/theme/SLUG/edit` as opposed to `/developers/addon/SLUG/edit`. Is that accurate? Is that the fix required for this?

**Comment by wagnerand** [comment]
I am not that familiar with themes. Maybe @eviljeff knows.

**Comment by eviljeff** [comment]
@bobsilverberg I believe that's correct.  But all the LWT and their special developer tools will be obsolete in a few weeks when they're all migrated so it's debatable how much time should be spent fixing this if it's just an admin link.  (If it's developer facing it's probably a good idea to fix because we do still support editing existing themes until they're migrated)

**Comment by bobsilverberg** [comment]
Well, it's a pretty simple fix so I guess it's worth fixing. Thanks @wagnerand and @eviljeff.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I already see that this has been fixed on AMO dev - the user is from "Admin" Group
![admins](https://user-images.githubusercontent.com/33448286/46858351-cc2cf900-ce13-11e8-9844-b015fd7c62bf.png)

 and now the link redirects as expected.
![link works for themes](https://user-images.githubusercontent.com/33448286/46858968-2c706a80-ce15-11e8-90fe-d0840848329a.gif)
