### ISSUE TITLE
The page size query parameter type should be string values, not numbers

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6598]
I am splitting the following out from #5737 issue since these a bit more involved than I originally thought.

Any page_size query parameters like the following should be updated:
https://github.com/mozilla/addons-frontend/blob/master/src/amo/api/reviews.js#L143src/amo/api/reviews.js@master#L143

**Comment by ioanarusiczki** [comment]
@rebmullin Please add some STR for qa. Thanks!

**Comment by willdurand** [comment]
> @rebmullin Please add some STR for qa. Thanks!

Can you check paginated review pages and search results? This should work as expected, nothing fancy.

**Comment by ioanarusiczki** [comment]
@willdurand @rebmullin 
- Pagination is displayed and works correctly. I've noticed an issue and filed it here https://github.com/mozilla/addons-frontend/issues/7311 
- Pagination in search results is displayed and works correctly.

Verified with FF64(Win10).
