### ISSUE TITLE
Extract code to display install button and Get Firefox button

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6603]
The all versions page (#2770) will need to display an install button next to each version. If the version is not compatible it will need to display a message with a disabled button. If the user is not on Firefox it will need to display the Get Firefox button. Much of this logic is already present in [`Addon`](https://github.com/mozilla/addons-frontend/blob/2018.10.11/src/amo/pages/Addon/index.js), so we should extract it out into its own component so it can be shared between the two pages.

**Comment by bobsilverberg** [comment]
@willdurand you mentioned that `InstallButton` will be removed in https://github.com/mozilla/addons-frontend/issues/6540. I'm likely going to start working on this issue immediately and I'm not sure what your timing is for #6540. Even if you don't get to #6540 first, do you think it would be okay if I just remove the logic for `InstallButton` when I create the new component discussed in this issue? I think all that would do would be to lessen the amount of work required for #6540.

**Comment by willdurand** [comment]
@bobsilverberg the old install logic will be removed next week (next tag hopefully), the only blocker is the shield study that should end on October 15th. We'll get final confirmation tomorrow (October 12nd, 2018).

I am fine with removing the logic in `Addon` since this is not shared by the Disco Pane. AMO uses the `AMInstallButton` for a while now. This can be done at any time.

**Comment by rebmullin** [comment]
@bobsilverberg, would you be okay if we extracted out the Get Firefox Button into a separate issue (#6901)?

**Comment by bobsilverberg** [comment]
@rebmullin I replied in #6901 as well. I agree this is a good idea, we just need to figure out who's going to do it as it would be the next thing on my list to do.

**Comment by rebmullin** [comment]
hey @bobsilverberg, I don't want to block you so please go ahead and take over #6901 if you can.

**Comment by bobsilverberg** [comment]
Thanks @rebmullin, I will.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified the Install button with FF63 (unbranded) in the guide lines and detail pages - lookd alright and add-ons can be installed/removed. 

I've noticed a different display for Get Firefox button on Chrome versus Edge on desktop, on small screens there are no differences.  If this needs a fixing let me know, I'll file another issue. 

Edge 
![get ff edge](https://user-images.githubusercontent.com/33448286/49576151-167eb200-f94d-11e8-9e11-31585b0cc007.png)


Chrome
![get ff chrome](https://user-images.githubusercontent.com/33448286/49575959-b12ac100-f94c-11e8-8f9a-f362633fb277.png)

**Comment by bobsilverberg** [comment]
Thanks for noticing that @ioanarusiczki. I'm not sure that it's something we need to fix. @pwalm what do you think?

**Comment by bobsilverberg** [comment]
Thanks @pwalm. @ioanarusiczki can you file a separate issue for that please?

**Comment by ioanarusiczki** [comment]
@pwalm @bobsilverberg I filed https://github.com/mozilla/addons-frontend/issues/7205
