### ISSUE TITLE
Create an addon-summary card to use on the Review Listing and All Versions pages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6605]
Supports #2770 

As per the mock at https://github.com/mozilla/addons-frontend/issues/2770#issuecomment-406693377, the add-on summary card that is currently displayed in the upper-left of the Review Listing, will also be displayed in the upper-left of the All Versions page. Based on the mocks at https://github.com/mozilla/addons-frontend/issues/3697#issuecomment-406693873 and https://github.com/mozilla/addons-frontend/issues/1828#issuecomment-406693167, we will also be using this for the new License view and the new Privacy Policy view.

I'm attaching the mock from https://github.com/mozilla/addons-frontend/issues/2770#issuecomment-406693377 for reference:

![all versions - 1366px](https://user-images.githubusercontent.com/6797635/43019637-821abdea-8c12-11e8-9715-118b7bebdcac.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev with FF62(Win10) but when I click the "See all versions" from the detail page I don't see this [new page](https://user-images.githubusercontent.com/6797635/43019637-821abdea-8c12-11e8-9715-118b7bebdcac.png) 

I submitted a new version for an add-on that has reviews for the first version but the old version page is still displayed, please take a look

![old view](https://user-images.githubusercontent.com/33448286/47358294-0dee5700-d6d2-11e8-8b5f-1d4ab2febef5.gif)

**Comment by bobsilverberg** [comment]
Sorry for the confusing title and description @ioanarusiczki. The new versions page hasn't been done yet. This issue was just about creating a component that *will be* used in a new versions page. This new component *is being* used by the review listing page, so that's all that needs to be verified.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified the review listing page on AMO dev with FF62(Win10) and it seems to be working just fine!
What I've noticed is an already filed issue so I updated it here https://github.com/mozilla/addons-frontend/issues/6121
