### ISSUE TITLE
404 page uses legacy front-end when not an add-on URL

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6606]
If you visit an invalid AMO page, [like this one](https://addons.mozilla.org/en-US/firefox/dfoishdiosd), the error page is on the legacy front-end. Invalid pages under `/addon/`, [like this one](https://addons.mozilla.org/en-US/firefox/addon/sdfoijh/), do show the new error page. They should all go to the new page.

/cc @caitmuenster

**Comment by willdurand** [comment]
Duplicate of #7327
