### ISSUE TITLE
Words in strings unclear as a verb or noun

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-frontend#6607]
### Describe the problem and steps to reproduce it:

Some of the words in the strings can be translated as verb or adjective. Need note or clarification on the use of these words
### What happened?
https://pontoon.mozilla.org/sl/amo-frontend/all-resources/?search=add-on&string=191281
- Admin add-on
- Admin add-on status
- Content review add-on

### What did you expect to happen?
Have comments to indicate if the word preceded add-on is used as a verb or adjective?

add-on for admin?
add-on for content review?

Or as a verb to 

administrate add-on and review add-on (what's the difference between content review add-on and review add-on).

**Comment by willdurand** [comment]
Those are links for admins and reviewers (i.e. no user will see them), but I wonder if we can do better. /cc @wagnerand

**Comment by kumar303** [comment]
The next locale extraction will happen on Tuesday Oct 23rd. The comments for these strings won't be visible in localizer tools until then.

**Comment by flodolo** [comment]
What about [Admin links](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L144)?

**Comment by bobsilverberg** [comment]
@flodolo If there are still some strings that need hints, could you please open a separate issue about those? Thanks.
