### ISSUE TITLE
AddonsByAuthorsCard should take a list of user IDs, not usernames

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6610]
To support https://github.com/mozilla/addons-server/issues/8302, we need to change the `AddonsByAuthorsCard` component to take a list of user IDs instead of usernames.

This issue is blocked by an API change requested here: https://github.com/mozilla/addons-server/issues/8901

**Comment by willdurand** [comment]
API just landed 🎉

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64

The More add-ons by author cards from the user profile page are requested by user ID now.

Before:
![image](https://user-images.githubusercontent.com/31961530/47571331-f1a42180-d940-11e8-8eac-a7648c7cefa9.png)


After:
![image](https://user-images.githubusercontent.com/31961530/47571381-11d3e080-d941-11e8-8dbb-a901b8d41652.png)
