### ISSUE TITLE
Problems caused by the graphic Firefox icon in HTML titles of pages

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#6621]
For example: 

- https://addons.mozilla.org/en-GB/firefox/addon/simple-black-fade/
- https://addons.mozilla.org/en-GB/firefox/addon/lightbeam/
- https://addons.mozilla.org/en-GB/firefox/addon/diigo-web-collector/
- … and so on. 

The icon fails to appear in the title bars of: 

- Firefox 62.0.3 on FreeBSD-CURRENT
- Firefox Nightly 64.0a1 (2018-10-04) on Kubuntu, from the Ubuntu PPA
- Chromium
- Falkon
- New Moon (Pale Moon)
- Surf
- and so on, although Web seems to be OK. 

In lieu of the icon, there's a blank space; like a large typo (as if the page author accidentally pressed and held the space bar). It took me a while to figure out what was wrong. 

![2018-10-14 07 57 43 waterfox](https://user-images.githubusercontent.com/192271/46913542-e20efb00-cf86-11e8-9897-d7203e0e7557.png)

### Also 

https://www.diigo.com/user/grahamperrin?query=%232018-10-14+%40addons.mozilla.org the icon causes truncation of titles with the Diigo bookmarking service. 

Diigo aside: I expect the graphic to cause problems in other situations.

**Comment by grahamperrin** [comment]
> expect the graphic to cause problems in other situations.

### Broken in Firefox Quantum on a Mac

Firefox ESR 60.2.2 (64-bit) on Mountain Lion, Mac OS X 10.9.5. 

In lieu of the cartoon fox there's an airplane, plus something illegible:

![screen shot 2018-10-18 at 01 26 31](https://user-images.githubusercontent.com/192271/47129907-2ce28880-d28f-11e8-8e70-17642a9bee75.png)

----

Incidentally I find the 'Get … Get … Get … Get … Get … Get … Get …' quite pushy,

**Comment by willdurand** [comment]
that's because the fox emoji is not supported on your machine, nothing we can really do unfortunately. Emoji are now everywhere and support is good.

As for your bookmarking service, they have to fix their tool (I suppose using a different charset like utf8mb4, because that's also an issue on addons-server).
