### ISSUE TITLE
Allow to map moment locales

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6623]
See also: #1515

---

We should add some config and logic in (`bin/build-locales`) to map unsupported moment locales to supported moment locales (for example, using the short locale that groups similar languages).

**Comment by ioanarusiczki** [comment]
@willdurand I've been checking on AMO dev (FF62-Win10) for several languages if the "Last Updated" and the date is translated. 

If there's something else to check on let me know. 

![last updated field](https://user-images.githubusercontent.com/33448286/47219376-51d21b00-d3b7-11e8-8d06-869faa84333e.png)

**Comment by willdurand** [comment]
> If there's something else to check on let me know.

nope, I guess it's fine. Localizers will tell us if something is not accurate.

**Comment by ioanarusiczki** [comment]
@willdurand Alright then.  It's something that only they could tell. 
Thanks!
