### ISSUE TITLE
Use react-router for author links in an add-on detail page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6628]
See also: #6526 #6626 

---

Once #6626 lands, we can update its internals to use the `Link` component for each author link, instead of using hardcoded HTML. This is similar to what has been done in the AddonReviewCard (for the permalink with the timestamp).

**Comment by ioanarusiczki** [comment]
@willdurand Should I check that links to author's page still work? Please add some STR for qa.
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki author links should be functional on an add-on detail page and there should not be any page reload.

**Comment by ioanarusiczki** [comment]
@willdurand 
- when the author is clicked the user profile page loads without being followed by a second reload of the right side of the screen

AMO Dev

![no reload](https://user-images.githubusercontent.com/33448286/47292125-bdfa8c00-d60e-11e8-831d-564450ae34d9.gif)

AMO Stage - this is as before when page reloads

![reloading on stage](https://user-images.githubusercontent.com/33448286/47292165-dbc7f100-d60e-11e8-83c3-f353b1ef3cc1.gif)

-  on the add-on detail page the " Other popular extensions" section reloads when a link is clicked from "More information" and then user navigates back with the back button but this is an old behavior, I've noticed it before. If you think I should file this let me know. 

- while testing I've noticed that the user profile page reloads when a link is clicked and the user navigates back to the page using the back button - let me know if this should be filed , it's reproducible on AMO dev and AMO stage

![reloading on both dev and stage](https://user-images.githubusercontent.com/33448286/47292269-1df13280-d60f-11e8-8e05-5546a788b3f6.gif)
