### ISSUE TITLE
Update compatibility.js to work with a specific version

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6629]
Depends on #6634

The functions in [`compatibility.js`](https://github.com/mozilla/addons-frontend/blob/2018.10.11/src/core/utils/compatibility.js) are currently designed to work with an `addon` object and extract the version info from `addon.current_version`. In order to support #2770 we need to be able to pass a specific version into some of these functions.

This issue is about changing `compatibility.js` to allow us to do that.

For QA:

Please test installing an add-on and a theme, both from AMO and disco pane. Also check for regressions in the messaging around incompatible extensions, both in terms of incompatible versions and for when Firefox is not the client.

**Comment by kumar303** [comment]
Please update the description with instructions for how QA should test this.

**Comment by bobsilverberg** [comment]
For QA:

Please test installing an add-on and a theme, both from AMO and disco page. Also check for regressions in the messaging around incompatible extensions, both in terms of incompatible versions and for when Firefox is not the client.

**Comment by kumar303** [comment]
Our issue template encourages describing the steps to reproduce the problem so when we omit that, the issue should include steps for testing (i.e. QA instructions). It's not always easy to dig through the thread of comments to find instructions.

**Comment by bobsilverberg** [comment]
> Our issue template encourages describing the steps to reproduce the problem so when we omit that, the issue should include steps for testing (i.e. QA instructions). It's not always easy to dig through the thread of comments to find instructions.

Ok, I'll add it to the description. I have generally just added a comment at the bottom of the issue with "For QA:" and that seems to have worked in the past, but I can add it to the description as well.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF63, Win10x64 and Android 8.0

- all add-on types can be installed from their product page
- theme and extension installation in disco pane is working as expected
- a specific add-on version can also be installed form its versions page
- incompatible add-ons are displaying a message with regards to their incompatibility reason
- no regressions around the 'Get Firefox' button in non-firefox clients

Here is a list with the most common incompatibility messages:
![image](https://user-images.githubusercontent.com/31961530/48487763-d766b080-e827-11e8-956e-89ff40c3f560.png)
