### ISSUE TITLE
Store the versionId of the current version in addon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6634]
Depends on #6637 

**Edited**

While working on https://github.com/mozilla/addons-frontend/issues/6629 I realized that although we have a new `AddonVersionType` which represents an internal representation of a version, we're still storing a version with an `ExternalAddonVersionType` in `addon.current_version`, which complicates things when you want to be able to pass either a version or an add-on into a function.

Instead of this, we can just store the `versionId` of the current version in the add-on and use a selector to retrieve the current version when needed.

In order to avoid having to change a huge amount of code, I will introduce code to store the version id, but not remove the existing code for `current_version` yet. I will also update the versions reducer to make sure that we always store version details in response to an action that also loads add-ons. After that is complete we can start migrating individual components to access the version via a selector rather than via `addon.current_version`. Once everthing has been migrated we can remove the code for `current_version`.

**Comment by bobsilverberg** [comment]
This is going to be really big. :-(

I apologize in advance for this, and I've made it a tiny bit smaller by spinning off #6637, but I don't know that I can do much else. The problem is that I'm changing the type of data stored for an add-on, and therefore any component or code that currently interacts with an add-on version is also going to have to change. If I don't change everything at once then it all breaks.

I thought about trying to update the pieces that use an add-on version, in small chunks, but in order to allow them to work with an internal version I'll have to add a bunch of code which will later have to be removed when the code for the addon reducer itself is updated. I'm not sure that that's worth doing.

Any opinions on that?

**Comment by bobsilverberg** [comment]
I'll just keep talking to myself here, I'm sure nobody minds. ;-)

I think I've found a way to chunk it out into smaller pieces (thank goodness), so I'm going to give that a try.

**Comment by kumar303** [comment]
Could you add some steps to the description for what QA should verify?

**Comment by bobsilverberg** [comment]
For QA:

Most of the code here does not affect any feature that is currently deployed (as it has to do with versions), but I did touch the addons reducer, so a simple check to make sure that an add-on detail page still works should be sufficient.

**Comment by ioanarusiczki** [comment]
I filed an issue here https://github.com/mozilla/addons-frontend/issues/6746
Verified on AMO dev FF63 (Win10)
