### ISSUE TITLE
Bad collection data can cause every detail page to error

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6635]
### Describe the problem and steps to reproduce it:

* Create a collection with a leading emoji in the title so that the title is essentially blank as per https://github.com/mozilla/addons-server/issues/8923
* Ensure you are signed in
* Visit any details page

### What happened?

* Every details page is a "Server error"
* In the console there is: 'Caught application error: TypeError: "e.name is null; can't access its "localeCompare" property"'

### What did you expect to happen?

* Even if the collection data is broken it should not result in the details pages being error pages.

**Comment by willdurand** [comment]
I cannot reproduce because the server does not let me create a collection with an emoji, I get a 500 on both the old and new frontend.

**Comment by muffinresearch** [comment]
Hmm that's interesting - did something change on the server-side to cause MySQL to error? This used to drop string content after the emoji silently.

**Comment by ioanarusiczki** [comment]
@willdurand  I could not create such a collection either - I tried on Win10 and Android 8.0 but I received a `500` and the Internal Server Error too. 
But when I tested the emoji issue on Android a while ago I used 2 accounts, one on -dev and one on -stage that had this problem, I could not see the detail pages and instead a "Server Error" was displayed
 I tested again with these accounts and I can no longer reproduce it.
Still, for these accounts the collection page is still not available. - "Server Error" here too 
Verified on AMO dev and AMO stage with FF62 - Win10 & Android 8.0

Please take a look 

![the emoji problem](https://user-images.githubusercontent.com/33448286/47088885-2f5dc780-d228-11e8-8ab1-4f570482ac6e.gif)

**Comment by willdurand** [comment]
>  Still, for these accounts the collection page is not available. - "Server Error" here too

@ioanarusiczki could you please file a new issue for that? Would you have some error logs from the console? That's be helpful!

**Comment by ioanarusiczki** [comment]
@willdurand I filed it here https://github.com/mozilla/addons-frontend/issues/6671 and I attached the console logs with the error.
