### ISSUE TITLE
Add hreflang attribute/alternate links to cope with duplicate content and reduce crawl budget

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6644]
In #5755, we added `canonical` links to most pages (those without query parameters). We did that to avoid duplicate content (because of the random query parameters added for analytics, etc.). Yet, we still provide one `canonical` link per `locale` and `clientApp`.

Each AMO URL starts with: `/{locale}/{clientApp}/`.

We support a lot of locales and two apps: `firefox` and `android`. Content may change a lot between two locales but it does not change that much between `firefox` and `android`, except that some add-ons are not available/shown/compatible with Android, including static themes that are about to be numerous (because LWT will be migrated to static themes soon).

Therefore, there are two points to discuss/address: locales and client apps.

## Locales
Good read: https://audisto.com/insights/guides/30/

I believe we could do better by adding `alternate` links with a `hreflang` property. Those links tell crawlers that a page has variants, given a locale in our case.

For each indexed page, and in addition to the `canonical` link that must be a self referencing link (that's already the case), we should add an `alternate` link for each supported locale:

```
<link rel="alternate" hreflang="en-US" href="https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/">
<link rel="alternate" hreflang="en-GB" href="https://addons.mozilla.org/en-GB/firefox/addon/ublock-origin/">
<!-- self referencing canonical link -->
<link rel="canonical" href="https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/">
```

Each locale must be [ISO_639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) and [ISO_3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) compliant.

We can use the `x-default` special locale to denote a "default" page. Since AMO is capable of content negotiation (automatically sets the locale), we can probably use this special locale with a special URL without a locale:

```
<link rel="alternate" hreflang="x-default" href="https://addons.mozilla.org/firefox/addon/ublock-origin/">
```

**Does that sound good?**

## Client apps

**Do we really want to crawl Android pages?** Those pages are very similar to the Firefox pages (because we basically do `s/Firefox/Android/g` to replace all occurrences of "Firefox" with "Android").

What would be the best strategy to do that? I'd be incline to use a meta `robots` with `noindex, follow` for all pages as soon as we have `clientApp === 'android'`.

What do you think? /cc @rraue 

---

## Update for QA (and reviewers)

- We do NOT deindex android pages
- We add a `x-default` link pointing to the `en-US` page
- We add a `en` link pointing to the `en-US` page
- We add a `pt` link pointing to the `pt-PT` page
- We ignore ISO 639-2 locales for now (locales with three letters, e.g., `ast`, `cak`, etc.)
- We focus on add-on detail pages here

**Comment by rraue** [comment]
### Hreflang:
That sound everything perfect. I add some very important things we need to keep in mind, although I think @willdurand has them already right:

- hrefland must only be on pages with a self-referencing canonical, server code 200 (no 404 or 30x must have a hreflang in the head, this can break the whole setup for all pages) and the page needs to be indexed
- every page must have a hreflang link pointing to itself as well
- every page must return all hreflang links pointing to the page
- the hreflang link on every page and every alternate must be the same as the canonical of the specific pages

### Android:
I see quite a bit of traffic coming from Google to this pages and if we deindex them, we will lose this traffic. And as all search keywords include "Android, it seems Google is understnading our setup quite well:
<img width="1728" alt="screen shot 2018-10-16 at 14 16 09" src="https://user-images.githubusercontent.com/36700618/47015756-1ed91e80-d14e-11e8-929a-c2035d2c049b.png">
We keep it indexed but we need to change the <title> for the Android extensions. I havent thought about it requesting https://github.com/mozilla/addons-frontend/pull/6480. For all Android extentions the title should be 
`i18n.gettext(%(addonName)s – Get this Extension for 🦊 Android
            (%(locale)s)),`
so Crawlers still see the difference between the android and the desktop extension. Then we shouldnt have Problems.

**Comment by willdurand** [comment]
> We keep it indexed

Ah, cool 🏆 Thanks!

> but we need to change the <title> for the Android extensions. I havent thought about it requesting #6480. For all Android extentions the title should be
> `i18n.gettext(%(addonName)s – Get this Extension for 🦊 Android (%(locale)s)),`
> so Crawlers still see the difference between the android and the desktop extension. Then we shouldnt have Problems.

Good call, I wanted to ask you that question on Slack but I forgot.. Filed: https://github.com/mozilla/addons-frontend/issues/6645 for that.

**Comment by willdurand** [comment]
> hrefland must only be on pages with a self-referencing canonical, server code 200 (no 404 or 30x must have a hreflang in the head, this can break the whole setup for all pages) and the page needs to be indexed

@rraue does that mean we should not add a `x-default` alternate link that is locale-less?

**Comment by willdurand** [comment]
With this tool: https://app.hreflang.org, I get the following errors:

```
    Invalid hreflang (ast) found in HTML.
    Invalid hreflang (cak) found in HTML.
    Invalid hreflang (dsb) found in HTML.
    Invalid hreflang (hsb) found in HTML.
    Invalid hreflang (kab) found in HTML.
```

**Comment by rraue** [comment]
@willdurand Yes, even the x-default must return all hreflang links and pointing it to a redirect makes no sense for a crawler, as the x-default only is used if none of the hreflang languages fit the user and then the x-default cand redirect to what isn't there as well. We should point the x-default to the en-US version, as this is usually our most maintained one. Most search engines will do so anyways.

Invalid languages:
Yes all of these languages arent currently supported by Google and as far as I know not by any other mayor search engine, as Google supports only ISO_639-1 but the errors occur for languages in ISO 639-2. We should only use hreflang in ISO_639-1 languages till they are supported. So these languages arent referenced on other languages and do not reference the other languages.

**Comment by willdurand** [comment]
> @willdurand Yes, even the x-default must return all hreflang links and pointing it to a redirect makes no sense for a crawler, as the x-default only is used if none of the hreflang languages fit the user and then the x-default cand redirect to what isn't there as well. We should point the x-default to the en-US version, as this is usually our most maintained one. Most search engines will do so anyways.

Ok, so we add an alternate link with `hreflang = x-default` pointing to `en-US` (i.e. the default locale).




>  Yes all of these languages arent currently supported by Google and as far as I know not by any other mayor search engine, as Google supports only ISO_639-1 but the errors occur for languages in ISO 639-2. We should only use hreflang in ISO_639-1 languages till they are supported. So these languages arent referenced on other languages and do not reference the other languages.

I see. So, we'll have to maintain a list of locales for the alternate links (or an exclusion list).

>  and do not reference the other languages.

@rraue so, on these pages (e.g., with `ast` as locale), we don't want any alternate links, correct?

**Comment by rraue** [comment]
Yes, and to make it clear, then for en-US we will have two hreflang alternates in the head. One for the self reference and one for the x-default. Some tools see that as an error, but thats fine and we have this on www as well.

Yes, unfortunately we need to leave out any hreflang alternate on non-ISO_639-1 languages until they are supported. I am not sure if it will cause a problem, but it will show up every as an error and so we might miss some real errors, creating too much of these kind.

Btw. am I able to test the setup as well before it will be merged?

**Comment by willdurand** [comment]
> Btw. am I able to test the setup as well before it will be merged?

Let me know when you are available and I'll open a tunnel to my local setup.

**Comment by willdurand** [comment]
@rraue let me know if what you've crawled from my machine is useful/looking good.

**Comment by willdurand** [comment]
@rraue there are other locales that we could map to short codes. I am thinking about `nb-NO`, `nn-NO`, `fy-NL`, `ga-IE`, `bn-BD`, `sv-SE`, and `zh-(CN|TW)`. Do we want mapping for them too or only for `pt` and `en`?

**Comment by rraue** [comment]
As Norwegian and the other languages aren't much spoken outside these countries it's not as important as en and pt, but yes, we should do it. I am just not sure, which chinese version we should set as standard.

**Comment by willdurand** [comment]
> As Norwegian and the other languages aren't much spoken outside these countries it's not as important as en and pt, but yes, we should do it. I am just not sure, which chinese version we should set as standard.

Ok, I made the "aliases" list configurable anyway, so we can update later.

**Comment by ioanarusiczki** [comment]
@willdurand  I verified this issue on AMO dev - FF62(Win10)
- I checked the add-on detail pages, extensions, lw themes and static themes for firefox then for android (switching from the filter in the More Menu) and I can confirm that the `x-default` is pointing to en-US page, the `en` link and `pt `link were added. Three language letters do not support these changes yet. 

- I've noticed that a static theme displays the information even if I switched from firefox to android. 

Please confirm if it's ok. 
An example -> https://addons-dev.allizom.org/en-US/android/addon/victortestversions/?src=search
Console display
![console information](https://user-images.githubusercontent.com/33448286/47436234-c7225f00-d7ae-11e8-8279-ecea36dfeecf.png)

**Comment by willdurand** [comment]
>     * I've noticed that a static theme displays the information even if I switched from firefox to android.

Yep, that's what we want.

Everything looks good to me, I re-checked with https://app.hreflang.org/
