### ISSUE TITLE
Add an Android version of the page title for detail pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6645]
The add-on detail pages should have a different page title when client app is `android`. Currently it is:

```
Stratiform – Get this Extension for 🦊 Firefox (en-US)
```

It should be:

```
Stratiform – Get this Extension for 🦊 Android (en-US)
```

**Comment by ioanarusiczki** [comment]
Verified on AMO dev - FF62(Win10) for extensions and themes.
If the filter is "Add-ons for Android" the metadata will expose for `og:title` the `Stratiform – Get this Extension for 🦊 Android (en-US)` The same for localized pages (I checked a couple)

Here's an example
![metapropery title](https://user-images.githubusercontent.com/33448286/47086706-ec4d2580-d222-11e8-8eaa-e87dd70f3385.png)
