### ISSUE TITLE
Extract `AddonHead` component from `Addon`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6647]
In order to support #6644, we should extract a new component called `AddonHead` from the existing `Addon` component, which would contain the `Helmet` block in the `render()` method.

It will be easier to work on the metadata and it will reduce the size of this (too) big `Addon` component.

For QA: please make sure page title/description and other metadata (JSON+LD, other `meta` tags are present).

**Comment by ioanarusiczki** [comment]
@willdurand As a comparison I used AMO stage to check on all exposed meta-data. I did not find regressions.  Verified on AMO dev with FF62 (Win10)

![metadata seo](https://user-images.githubusercontent.com/33448286/47295325-0ec2b280-d618-11e8-8edb-0e3b2c7dbafe.png)
