### ISSUE TITLE
Consider a different title for Android pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6648]
We currently use `Firefox` for the Firefox pages and `Android` for the Android pages, e.g.:

- homepage with `clientApp` set to `firefox`: `Add-ons for Firefox`
- homepage with `clientApp` set to `android`: `Add-ons for Android`
- add-on detail page (`firefox`): `Stratiform – Get this Extension for 🦊 Firefox (en-US)`
- add-on detail page (`android`): `Stratiform – Get this Extension for 🦊 Android (en-US)`

Are we happy with this? @bobsilverberg and I find that not having "Firefox for Android" sounds a bit odd.

**Comment by willdurand** [comment]
@MeridelW I think that's a question for you :)

**Comment by MeridelW** [comment]
I agree not having "Firefox for Android" sounds odd. My once concern with including it is that Google character count limits might cut off the "Android" portion. This will only happen in cases where the extension name is longer. We could cut out the "for" to save some characters. How about this?

Get this Extension for 🦊 Firefox Android (en-US)

**Comment by bobsilverberg** [comment]
Sounds good to me! 👍
