### ISSUE TITLE
Update AddonMoreInfo to use a version stored in the versions redux state

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6651]
Depends on #6634 

As part of removing `current_version` from `addon`, update `AddonMoreInfo` to use a version retrieved via `mapStateToProps` instead of using `addon.current_version`.

**Comment by bobsilverberg** [comment]
For QA: Please check the Add-on Detail page, particularly license and version information.

**Comment by ioanarusiczki** [comment]
I tested on the detail page, particularly:
- License : I checked on all license types, I edited them for an add-on from Dev Hub, then checked the add-on detail page to see it's correctly displayed and that the link redirects to the license page.
- Version information : the page displays a list of versions, release notes with license, the green install button for all previous versions, clicked them from the detail page, the links open the pages. 

Verified on AMO dev with FF63 (Win10).
