### ISSUE TITLE
Update Addon to use a version stored in the versions redux state

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6653]
Depends on #6634 

As part of removing `current_version` from `addon`, update `Addon` to use a version retrieved via `mapStateToProps` instead of using `addon.current_version`.

**Comment by bobsilverberg** [comment]
For QA, please check for regressions on the Add-on Detail page, in particular with version release notes.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO dev with FF63(Win10)
Looks good to me. 

Release notes section

![release notes](https://user-images.githubusercontent.com/33448286/47799401-df582800-dd32-11e8-9cd8-6432d69f69c3.gif)
