### ISSUE TITLE
Consider replacing function based localization with Lingui

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6657]
Let's look at Lingui and understand what the implications would be of using it in the addons-frontend project.

The more I look at [Lingui](https://lingui.js.org/) (hattip to @willdurand for suggesting it) the more I like it because it appears to be a much more React friendly solution for translation which stays out of the way when using other components in JSX.

Here's an example of wrapping other JSX components:

```jsx
 <Trans>See the <Link to="/more">description</Link> below.</Trans>;
```

Would result in a `msgid` like this:

```icu
See the <0>description</0> below.
```

## Questions

* Can localizers handle icu format inside Pontoon ok?
* Are there any implications of icu format inside po files? Is it gettext tooling compatible for example?
* Could we run lingui side by side with our existing l10n tools or would we need to wholesale replace gettext with this?
  * Possibly - it might get complicated since you'd probably need to extract, merge and build each style of translation separately.
* How does extraction work?
  * Lingui provides a [CLI](https://lingui.js.org/ref/cli.html) for extraction and building locale output.
* Are PO files supported?
  * [Yes, but you use icu format within the PO files](https://lingui.js.org/ref/conf.html#po). 
* What does it make of more complicated markup do the placeholders work in those scenarios?
* Please add more questions here...

## Other libs to compare with

* [react-intl](https://github.com/yahoo/react-intl)
* [react-i18next](https://github.com/i18next/react-i18next)

**Comment by tricoder42** [comment]
Hey @muffinresearch, I'm LinguiJS maintainer. @willdurand ping me on Twitter about this issue. Unfortunately I don't have much experience with gettext tools / workflows. I have one comment though:

> Could we run lingui side by side with our existing l10n tools or would we need to wholesale replace gettext with this?

Do I understand correctly that you use `babel-gettext-extractor` which creates one POT file for each source file with translations? Then you collect messages from these POT files and create/merge a final catalog?

If so, extract command in Lingui could be configurable to allow using various babel plugins. I was just thinking yesterday if the same CLI could be reused with react-intl, which uses `babel-plugin-react-intl`. If it would help you I could refactor the extraction to make it configurable.

But still, you would need at least two separate catalogs, right? One for LinguiJS and one for existing l10n tools. I'm just finishing implementation of [new catalogs](https://lingui.js.org/rfc/002_catalogs.html) and that would solve this problem as well. You would simply whitelist/blacklist files which use Lingui. Still a lot of things to figure out, but I just want to share my thoughts.

**Comment by muffinresearch** [comment]
Hi @tricoder42 - thanks for your thoughts and suggestions.

> Do I understand correctly that you use babel-gettext-extractor which creates one POT file for each source file with translations? Then you collect messages from these POT files and create/merge a final catalog?

Yes this is correct except that there's only a single file as output today.

> But still, you would need at least two separate catalogs, right? One for LinguiJS and one for existing l10n tools. I'm just finishing implementation of new catalogs and that would solve this problem as well. You would simply whitelist/blacklist files which use Lingui. Still a lot of things to figure out, but I just want to share my thoughts.

That sounds really good. Our localizers have asked for us to split up the catalog more in the past so this would be very useful.

**Comment by jamuhl** [comment]
Just regarding the comparison with react-i18next (https://github.com/i18next/react-i18next):

The splitting up into multiple catalogs (called namespaces in i18next terms) was built in from day one as we always built i18next with large scale projects in mind.

The i18n formats we currently support:

- i18next's JSON https://www.i18next.com/misc/json-format
- ICU https://github.com/i18next/i18next-icu
- mozilla's fluent https://github.com/i18next/i18next-fluent
- airbnb's polyglot https://github.com/i18next/i18next-polyglot

Beside react.js there is also support for serverside (node, .net, ...) and other UI frameworks: https://www.i18next.com/overview/supported-frameworks

While you have option for runtime extraction there are multiple translation extraction tools available. Gettext PO/POT is supported using https://github.com/i18next/i18next-gettext-converter or https://github.com/queicherius/i18next-po-loader (complete list of available plugins/utils: https://www.i18next.com/overview/plugins-and-utils)

Having questions you always can reach me via jan.muehlemann@gmail.com or open an issue over at react-i18next repo. We would be happy to help out.

**Comment by willdurand** [comment]
While this looks like a good idea, I don't think we'll have time for that. Closing for now, we'll reopen if needed.
