### ISSUE TITLE
"Admin Links" string needs a localization comment

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-frontend#6669]
It's unclear what Admin means in this context, and I'm pretty sure everyone is going to translate it as "manage", given similar strings in the file.
https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L144

**Comment by championshuttler** [comment]
Can i take this up?

**Comment by ioanarusiczki** [comment]
@bobsilverberg  I checked  "Admin Links" string, on the add-on detail page, for a couple of languages, some have the string translated but some of them still don't. I don't see a "hint". 
Please let me know what to check in case I did not understood this correctly.

**Comment by championshuttler** [comment]
@ioanarusiczki I think these hints were for localisers. These will be available only on pontoon if i am not wrong. So this issue might not be need QA :wink:
