### ISSUE TITLE
Server error on the collection page after naming a collection using emojis

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6671]
Followup for https://github.com/mozilla/addons-frontend/issues/6635

STR:
1. Load AMO dev and after naming a collection with an emoji plus some text click on View My Collections
2. Observe page

Expected result:
The list of collections is displayed

Actual result:
Server Error is displayed

Notes:
This is reproducible on AMO dev and AMO stage with FF62- Win10

![the accounts with emoji issue](https://user-images.githubusercontent.com/33448286/47138498-42bd7100-d2c2-11e8-8a4c-e0cab886139a.png)

**Comment by willdurand** [comment]
haha, that makes sense actually.. I set the fallback name to an empty string, which is a falsey value for `invariant`.

**Comment by muffinresearch** [comment]
@ioanarusiczki Is this still reproducible?

**Comment by willdurand** [comment]
This should be fixed.
