### ISSUE TITLE
Number of add-ons in collections is not correct until sorting them by another criteria

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#6673]
Steps to reproduce:
1.Open a collection from AMO-dev homepage (https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/smarter-shopping/)
2.Observe that the number of add-ons is 5 even if we have only 2 add-ons in the collection

Expected results:
The number of add-ons should reflect how many add-ons are inside the collection

Actual results:
The number displayed in the right size is wrong

NOTES:
After sorting the add-ons by a different criteria, the number is correctly displayed
Not reproducible in production

Please see a video for this issue:
![collnumber](https://user-images.githubusercontent.com/1583842/47153192-824a8400-d2e7-11e8-9f98-4c1acc8d0734.gif)

**Comment by vcarciu** [comment]
Please note that after a refresh the number is wrong again

**Comment by kumar303** [comment]
This looks like an API issue: https://github.com/mozilla/addons-server/issues/9749

**Comment by kumar303** [comment]
> After sorting the add-ons by a different criteria, the number is correctly displayed

I think that might be a separate frontend bug. The API appears to always show the wrong number so I'm not sure how the frontend is getting its count value for this case.

**Comment by willdurand** [comment]
Looks like this has been fixed.
