### ISSUE TITLE
Edit profile textarea expands too much

### ISSUE THREAD

**Issue by saranshbarua** [mozilla/addons-frontend#6687]
### Describe the problem and steps to reproduce it:

- Sign in
- Navigate to edit your profile section
- Fill in your biography
- Enter a lot of text

### What happened?

The textarea expands too much

<details>
<summary>Example</summary>
<br>
<img src="https://user-images.githubusercontent.com/23500643/47218280-d9745580-d3c8-11e8-8ae8-f671557b714d.png"> 
<br>
<img src="https://user-images.githubusercontent.com/23500643/47218282-da0cec00-d3c8-11e8-9ba1-4ef86ea151a0.png">
</details>

### What did you expect to happen?

After certain characters, the textarea should stop expanding. Scrollbars should appear.

### Anything else we should know?

This is similar to #6344

**Comment by saranshbarua** [comment]
@kumar303 @willdurand  I find this similar to #6344 . I'll try to work on this too. Can you guide me on which components and stylesheets I should refer too?

**Comment by willdurand** [comment]
I don't know, we actually use a component on top of the `textarea` to adjust its size given the content. I don't think we should change that.

**Comment by saranshbarua** [comment]
@willdurand have a look at [this](https://github.com/mozilla/addons-frontend/pull/6660/files)

**Comment by saranshbarua** [comment]
So I figured out which component to refer to and solved the issue. Should I submit a PR?

**Comment by willdurand** [comment]
Sorry @saranshbarua but I still believe we don't need this.
