### ISSUE TITLE
Disable strict mode with a config flag

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6694]
We add `StrictMode` here for development:

https://github.com/mozilla/addons-frontend/blob/3d8200443ca1734cfbd5d3666a9154d632685881/src/core/components/Root/index.js#L23

This is nice because it warns us when we use deprecated lifecycle methods. However, it also double-triggers lifecycle methods to make sure they are idempotent. This is confusing when you are trying to debug a real problem like making too many API requests -- a common problem if your dispatching logic is incorrect.

I would like a config flag to disable `StrictMode` temporarily in my local environment. After I'm done debugging, I would put it back.

My current workaround is just to edit the code:

```diff
diff --git a/src/core/components/Root/index.js b/src/core/components/Root/index.js
index 634386f04..658985b0e 100644
--- a/src/core/components/Root/index.js
+++ b/src/core/components/Root/index.js
@@ -20,7 +20,7 @@ const Root = ({ children, history, i18n, store }: Props) => (
     <Provider store={store} key="provider">
       <ConnectedRouter history={history}>
         {/* $FLOW_FIXME: https://github.com/facebook/react/issues/12553 */}
-        <React.StrictMode>{children}</React.StrictMode>
+        {children}
       </ConnectedRouter>
     </Provider>
   </I18nProvider>

```

Just as an example, here's how you could use the config to conditionally render `<StrictMode>`:

https://github.com/mozilla/addons-frontend/blob/3d8200443ca1734cfbd5d3666a9154d632685881/src/amo/components/RatingManager/index.js#L343-L345

**Comment by saranshbarua** [comment]
@kumar303 @willdurand  I would like to take this.

**Comment by willdurand** [comment]
@saranshbarua ok, let me know if you have questions.

**Comment by SeanPrashad** [comment]
Hey @saranshbarua - I was wondering if you were still working on this? If not, could I give it a shot?
