### ISSUE TITLE
Remove componentWillReceiveProps() calls (react upgrade)

### ISSUE THREAD

**Issue by xu3u4** [mozilla/addons-frontend#6699]
### Describe the problem and steps to reproduce it:
![image](https://user-images.githubusercontent.com/6767433/47264406-2e3eda00-d549-11e8-98fd-491f97aa0e7c.png)
The warning keeps showing up in console.
It can be fixed by either adding [UNSAFE](https://reactjs.org/docs/react-component.html#unsafe_componentwillreceiveprops) for now or just rewriting.

Ref: https://reactjs.org/docs/react-component.html
Related PR for react upgrade: #6187 

### What happened?
`componentWillReceiveProps` is deprecated.

### What did you expect to happen?
Replace `componentWillReceiveProps` with `static getDerivedStateFromProps(props, state)` or use other solutions.

**Comment by luckykumardev** [comment]
@xu3u4  can i try this?

**Comment by championshuttler** [comment]
@xu3u4 If I am not wrong its duplicate of #6188

**Comment by xu3u4** [comment]
@championshuttler Oh thank you.
I didn't find it.
Let me close this issue.

**Comment by xu3u4** [comment]
@championshuttler Oh thank you.
I didn't find it.
Let me close this issue.

**Comment by xu3u4** [comment]
@championshuttler Oh thank you.
I didn't find it.
Let me close this issue.

**Comment by xu3u4** [comment]
@championshuttler Oh thank you.
I didn't find it.

**Comment by xu3u4** [comment]
@championshuttler Oh thank you.
I didn't find it.

**Comment by xu3u4** [comment]
@championshuttler oh thank you.
I didn't find it.
Let me close this issue.

**Comment by xu3u4** [comment]
@championshuttler oh thank you.
I didn't find it.
Let me close this issue.

**Comment by xu3u4** [comment]
@championshuttler oh thank you.
I didn't find it.
Let me close this issue.
