### ISSUE TITLE
Set up code splitting for guide pages

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6702]

**Comment by rebmullin** [comment]
hey @willdurand, should we leave this issue open? My understanding is the current code splitting set up doesn't make that big of a difference.

**Comment by willdurand** [comment]
> hey @willdurand, should we leave this issue open? My understanding is the current code splitting set up doesn't make that big of a difference.

I don't remember exactly. Is there any significant gain?

**Comment by rebmullin** [comment]
I don't think there was

**Comment by willdurand** [comment]
Then, maybe it is fine to close this issue for now, and re-open it if needed in the future.
