### ISSUE TITLE
Update AMO banner per legal feedback

### ISSUE THREAD

**Issue by MeridelW** [mozilla/addons-frontend#6706]
Per legal feedback (Mika Shah), we should make the following changes to the footer:

1. Delete the "Report Trademark Abuse" line - it's not required and legal is encouraging all web properties to remove it since it's pretty valuable real estate

2. Redirect Legal link at the bottom 
![amo footer](https://user-images.githubusercontent.com/33848177/47313366-65be8c80-d604-11e8-8134-f6a5503924f6.png)
here: https://www.mozilla.org/en-US/about/legal/terms/mozilla/

**Comment by willdurand** [comment]
Thanks @championshuttler!

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF62 (Win10)
"Report Trademark Abuse" was removed and "Legal" redirects to  https://www.mozilla.org/en-US/about/legal/terms/mozilla/

![legal new link](https://user-images.githubusercontent.com/33448286/47359004-2e1f1580-d6d4-11e8-90fa-15567ceef478.gif)

**Comment by MeridelW** [comment]
Fast work, thank you! @ioanarusiczki  you can take out the en-US also, because that page is localized to many languages:

https://www.mozilla.org/about/legal/terms/mozilla/
