### ISSUE TITLE
AMO dev content looks broken

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6710]
STR:

1. Load AMO -dev homepage
2. Observe the page content

Actual result:
There are a lot of missing add-on icons and many  lisitng pages will generate 404s, 

Expected result:
No display or content rendering issues on AMO

Notes:
- I've seen a discussion around this on IRC yesterday but since this issue is still happening today, I have filed this case to track its evolution
- reproduced on AMO -dev with FF62, Win10x64
- Cc @autrilla for more insight

![image](https://user-images.githubusercontent.com/31961530/47341623-34000100-d6aa-11e8-84fa-13930f9ae212.png)

**Comment by willdurand** [comment]
I also noticed this yesterday. cc @diox

**Comment by autrilla** [comment]
Judging by when this happened, this is probably my fault. I pointed my UTF8MB4 stack at the normal -dev ElasticSearch cluster yesterday. I think Celery reindex jobs might have written bogus data to ES, which causes this to happen.

**Comment by AlexandraMoga** [comment]
I've marked this as a P1 since it's blocking testing of several features that landed these days

**Comment by autrilla** [comment]
As suggested by @diox I ran `./manage.py reindex`, and -dev is looking much better now.

**Comment by AlexandraMoga** [comment]
-dev is back to normal, indeed.
Thanks

![image](https://user-images.githubusercontent.com/31961530/47356105-c95fbd00-d6cb-11e8-8093-416fe6a4e9b1.png)
