### ISSUE TITLE
Remove webpack workaround (browser config in package.json) when we upgrade express-http-context

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6714]
The next release of https://github.com/skonves/express-http-context should bring a safe browser API. When upgrading, we should remove our webpack workaround introduced in #6672 (the `browser` entry in the `package.json` file).

**Comment by skonves** [comment]
Version 1.2.0 of `epxress-http-context` has been published and includes the referenced safe browser API.

**Comment by willdurand** [comment]
Thanks @skonves!
