### ISSUE TITLE
Make the user object available to SSR rendered components

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6717]
### Describe the problem and steps to reproduce it:

* Create a component that waits for `siteUser` (e.g. [`getCurrentUser(state.users)`](https://github.com/mozilla/addons-frontend/blob/a02777625bb33f8eebff8eea38420e6b11c845f6/src/amo/reducers/users.js#L374)) before it dispatches a loading action
* Create a page requiring that component to load all its data on the server, before a response is written

### What happened?

This is not possible because `siteUser` does not predictably load before the [first server render](https://github.com/mozilla/addons-frontend/blob/44a07385698e25abad6247cb4ac8bbb53edd0642/src/core/server/base.js#L363)

### What did you expect to happen?

It should be possible to rely on `siteUser` when loading data in a server response.

### Anything else we should know?

* SSR data loading is already very fragile. We only get *one* render cycle to dispatch all loading sagas. Really, we need a holistic fix to this that lets us load all necessary data on the server in a predictable manner. Fixing this would be a big architectural change.
* Instead of loading `currentUser` [in a saga](https://github.com/mozilla/addons-frontend/blob/a02777625bb33f8eebff8eea38420e6b11c845f6/src/amo/sagas/users.js#L22) (which is triggered [right after parsing the cookie](https://github.com/mozilla/addons-frontend/blob/44a07385698e25abad6247cb4ac8bbb53edd0642/src/core/server/base.js#L309)), we could use a promise and make sure this promise completes before the first render. This would be a quick fix but it may have performance implications.

**Comment by kumar303** [comment]
For context, I ran into this when trying to render user review permissions on the server for https://github.com/mozilla/addons/issues/526 . However, I am able to just load the necessary data on the client.

**Comment by bobsilverberg** [comment]
Kumar and I discussed this a bit at ReactConf, although we didn't discuss any possible solutions. I think we agreed that we should discuss this as a group at the next all-hands, discussing the problems and challenges we face with our current approach and possible soltuions.

**Comment by kumar303** [comment]
It would be nice if we could think of a non-drastic solution, one that worked with our current saga strategy. My only idea for that is to keep rendering the app in a loop until it stops triggering sagas. Ha! 

Another nice thing would be to load data on the server exactly how we load it on the client (however we decide to do it).

@willdurand I think you had some ideas around this?
