### ISSUE TITLE
Comprehend all Redux actions dispatched during a given server response

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6719]
I would like to see all dispatched Redux actions for a given server response during development.

Why? I spent several hours debugging an SSR problem but when I finally added custom logging of all dispatched Redux actions and their state modifications (just the ones I was interested in), I found the bug immediately.

We've never had this feature and I don't know how to implement it 😁 ; I just want it.

Ideas I have that probably won't work:
- Let `pino-devtools` capture full object logging so that it can replay that on the client. This would expose standard object logging techniques in devtools like inspecting large objects (e.g. previous / next state objects). However, if I turn on the [Redux logger](https://github.com/mozilla/addons-frontend/blob/44a07385698e25abad6247cb4ac8bbb53edd0642/src/core/store.js#L22-L26), `pino-devtools` gets JSON parsing errors, probably because of the line buffering or something else related to the socket transport.
- Just dump all state objects to the server console. This is how we used to do it but it was never helpful since the objects are massive.
- There is, of course, a workaround where you can disable SSR and see all actions logged in the client. This may not be helpful, though, because SSR loading is different and fragile! The bug I was hunting down did not exist when SSR was disabled.

**Comment by bobsilverberg** [comment]
This does sound like a nice thing to have. I too have had issues where the problem only happened with SSR, to turning off SSR to make debugging easier didn't help.

👍
