### ISSUE TITLE
Log action types dispatched in a server response

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6722]
I think it might be useful to log all action types that are dispatched in a server response to help visualize server state. It won't be as nice as full state logging (https://github.com/mozilla/addons-frontend/issues/6719) but it would be easier to implement, at least.

**Comment by ioanarusiczki** [comment]
@kumar303 What should be tested on the frontend ? Please provide some STR or mark it "qa not needed".
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki there is nothing to see for QA I think, I marked the issue as "qa: not needed". Thanks!
