### ISSUE TITLE
Finish removing current_version and platformFiles from AddonType

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6727]
This will be the final refactor in support of #2770. This will remove `current_version` and `platformFiles` from `AddonType` so that the only place version information (including platformFiles) will be available is in an `AddonVersionType` object.

For QA:

This is a pretty major change, although no changes will be observable. Please check all install actions, as well as anything that relies on compatibility information.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF63, Win10x64 and Android 8.0

I've tried addon installations from their product page, from disco pane and from the addon version page.
I've also tried to trigger incompatibility errors to see if tjey are rendered as expected.
I didn't find any regressions.
