### ISSUE TITLE
Blank space in URLs can cause the requested page to get stuck in a loading state

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6735]
STR:

1. Load the following page - https://addons-dev.allizom.org/en-US/firefox/addon/stratiform%20/
2. Observe the layout

Actual result:
The page content is not displayed and it looks stuck in a continuous loading state. There are a lot of CSP reports in the console.

Expected result:
The page requested should return a 404, or should ignore the blank space, as the API does

Notes:
- if you call the same page from the API, its details are retrieved. The API seems to ignore the blank space: see https://addons-dev.allizom.org/api/v4/addons/addon/stratiform%20/
- I have also tried with a different page - https://addons-dev.allizom.org/en-US/firefox/addon/stratiform/reviews/563890%20/ and in this case, a 404 will be triggered, but from a legacy page. Again, the API will ignore the blank space and will return the review details: see https://addons-dev.allizom.org/api/v4/ratings/rating//563890%20/
- reproduced on all AMO servers with F62, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/47423821-b5c95a80-d78e-11e8-882c-32ba988a2176.png)

**Comment by kagehina919** [comment]
@AlexandraMoga can I work on this issue? My idea is to process the URLs to remove space characters and set a redirect component to the correct URL.

**Comment by AlexandraMoga** [comment]
Cc @willdurand ^

**Comment by kumar303** [comment]
Hi @kagehina919, thanks for your interest! We apply the labels [`good first bug`](https://github.com/mozilla/addons-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22) or [`contrib: welcome`](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) to issues that are open to contributors. This is only because we want to make sure each issue has enough information and also that it's not something we need to fix urgently. Please try solving a *good first bug* issue first to get a feel for contributing to AMO. Let me know if you have any questions.

**Comment by kumar303** [comment]
Here is an explanation of the bug:
* The page begins loading with the add-on slug of "stratiform " (note the space) in the URL
* The API receives a slug of "stratiform " but strips the whitespace, turning it into "stratiform"
* The API loads the "stratiform" add-on without any problems
* The page waits until data for the "stratiform " slug has loaded. This is the bug.

To fix this, I propose redirecting to a URL with the corrected slug when the API returns data containing the corrected slug. This is a fairly easy fix but it's not good as a "first bug" as it will require some knowledge of the AMO application. I can mentor this issue.

**Comment by kagehina919** [comment]
@kumar303 I have understood the issue and set up a local development server. Is there any IRC or any other chat which we can use?

**Comment by championshuttler** [comment]
Hi @kagehina919 , yes you can join `#amo` on Mozilla's IRC server. Details on how to connect can be found [here](https://wiki.mozilla.org/IRC).

**Comment by kumar303** [comment]
@kagehina919 that's great to hear you are set up with a local development server. Please try starting with a [good first bug](https://github.com/mozilla/addons-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22) to get introduced to the contribution process.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64

![2018-11-12_09-12-39](https://user-images.githubusercontent.com/31961530/48332198-a46fc180-e65b-11e8-9dc5-10d7cb42db67.gif)
