### ISSUE TITLE
Extract a CategoryHead component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6738]
In order to add new `meta` tags to the category pages (#5767), let's create a `CategoryHead` component that is similar to the `AddonHead` component. This new component will contain all the `Helmet` logic for a category page.

For QA: the category pages should have correct HTML titles and `canonical` links (in the HTML).

**Comment by ioanarusiczki** [comment]
Look good to me. Verified on AMO dev with FF63 (Win10) the category pages

![cannonical links](https://user-images.githubusercontent.com/33448286/47569822-5b223100-d93d-11e8-85d1-5d3aaa49040a.png)
