### ISSUE TITLE
If an add-on/theme name is changed to <script>alert(‘Problem1')</script>, discopane fails to load any content

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-frontend#674]
## steps to reproduce:
1. Among the list of featured add-ons on discopane, change the name for at least one add-on and one theme to <script>alert(‘Problem1')</script>
2. Load Tools -> Add-ons

## expected behavior:
https://discovery.addons.allizom.org/en-US/firefox/discovery/pane/50.0a1/Darwin/normal loads all the featured content

## observed behavior:
https://discovery.addons.allizom.org/en-US/firefox/discovery/pane/50.0a1/Darwin/normal loads no featured content

**Comment by muffinresearch** [comment]
Looking at https://addons.allizom.org/api/v3/discovery/?lang=en-US there's a 500 error because the output is {"detail":"Internal Server Error"}, I'll get a sentry log.

**Comment by muffinresearch** [comment]
From: https://sentry.prod.mozaws.net/operations/olympia-stage/issues/339799/

```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 14: ordinal not in range(128)
  File "rest_framework/views.py", line 463, in dispatch
    response = handler(request, *args, **kwargs)
  File "rest_framework/mixins.py", line 45, in list
    return self.get_paginated_response(serializer.data)
  File "rest_framework/serializers.py", line 674, in data
    ret = super(ListSerializer, self).data
  File "rest_framework/serializers.py", line 239, in data
    self._data = self.to_representation(self.instance)
  File "rest_framework/serializers.py", line 614, in to_representation
    self.child.to_representation(item) for item in iterable
  File "olympia/discovery/serializers.py", line 34, in to_representation
    unicode(instance.addon.name))
```

**Comment by muffinresearch** [comment]
Looks like it's barfing on the left quote.

**Comment by krupa** [comment]
Content shows up now but the add-on and theme are still missing their names.

<img width="1124" alt="screenshot 2016-06-30 14 33 51" src="https://cloud.githubusercontent.com/assets/301317/16505046/f2c5d508-3ecf-11e6-9191-fe7aa09e6189.png">

**Comment by muffinresearch** [comment]
This is because we use DOMPurify [1] on the parts of the API that contain HTML (because we're treating that content as safe (once sanitized) - the heading is one of those because it has a span and a link in it. `<script>` is not in the allowed tags list and gets removed so this is expected.

You can validate this by putting other text outside the script. That should appear but the script will still be stripped from the markup.

[1] https://github.com/cure53/DOMPurify

**Comment by muffinresearch** [comment]
One other thing to note the test payload here is `<script>alert(‘Problem1')</script>`, note the curly left quote. This was handy as it caught a unicode problem, but note this would cause `SyntaxError` rather than show an alert if it gets run.
