### ISSUE TITLE
Update category page header

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6741]
See: https://mozilla.invisionapp.com/d/main#/console/11679087/256136385/preview

---

We should update the category page header:

- title should be centered
- no description

![screen shot 2018-10-24 at 18 20 12](https://user-images.githubusercontent.com/217628/47445554-7f550500-d7b9-11e8-994f-e301ad02f9f9.png)

**Comment by ioanarusiczki** [comment]
Verified on AMO dev Win10&android 8.0 - category titles are centered now

![centered titles](https://user-images.githubusercontent.com/33448286/47567124-55751d00-d936-11e8-984e-6eacb434075d.png)
