### ISSUE TITLE
Add-on detail page - "Add to Collection" section reloads after returning on page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6746]
STR:
1. Load AMO dev and go to an add-ons detail page
2. Click on a link from the page and after the page loads click the back button
3. Observe the "Add to Collection" section

Expected result:
Collection section is not reloading.

Actual result:
For a short while the "Select a collection" glitches - it looks like a reload. 

Notes:
This issue is reproducible on AMO dev and AMO stage - FF63 (Win10). 
I could not reproduce it on AMO prod. 

![reload collections](https://user-images.githubusercontent.com/33448286/47487131-89731400-d84a-11e8-9fea-36e84d4f37dd.gif)

**Comment by willdurand** [comment]
mmh, this could totally be related to https://github.com/mozilla/addons-frontend/issues/6729

**Comment by willdurand** [comment]
I can reproduce in -prod too, so I guess this is the expected behavior.

**Comment by kumar303** [comment]
Yes, the *add to collection* select box should load whenever the page first loads. This is expected. You have to be signed in to see this behavior so perhaps when you could not reproduce it, you were not signed in.
