### ISSUE TITLE
Follow up on the new guide urls

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6751]
This is assuming that #6665 lands before we have the final guide urls.

Since the updated home page is behind a flag we are currently using temporary urls. We need to update these once these have been finalized.

See
https://github.com/mozilla/addons-frontend/issues/6432#issuecomment-432314539

**Comment by rebmullin** [comment]
@devaneymoz @pwalm @jvillalobos 

we currently have the final guide pages set up on dev and I want to see if we could finalize the guide url. Currently, I am using the following urls for each page:


    Stay Safe Online - `stay-safe-online`
    Organize Your Tabs - `organize-your-tabs`
    Enhance Your Media Experience - `enhance-your-media-experience`

is this okay?

**Comment by jvillalobos** [comment]
Looks good to me. /cc @rraue in case he has an opinion on this

**Comment by rebmullin** [comment]
also just to be clear, each url includes "guides" before the guide slug:

  Stay Safe Online - `guides/stay-safe-online`
  Organize Your Tabs - `guides/organize-your-tabs`
  Enhance Your Media Experience - `guides/enhance-your-media-experience`
