### ISSUE TITLE
A square is visible around a rating star when it's selected on Chrome

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6755]
STR:
1. Load AMO dev with Chrome
2. Login and go to an add-on detail page
3. Click a rating star 

Expected result:
Star is selected - becomes yellow.

Actual result:
The selected star becomes yellow with a blue border around it.

Notes:
This issue is not reproducible on FF63 or Edge (AMO dev, Win10), I could only reproduce it with Chrome on Win10 and Android 8.0 too ( except on android the  square is orange).
it's reproducible on all pages that contain editable rating stars.

Windows 10 - with Chrome 
![win10 -stars](https://user-images.githubusercontent.com/33448286/47557889-86dfef80-d91a-11e8-90c9-1b82534194b5.png)

Android 8.0 - with Chrome
![android stars](https://user-images.githubusercontent.com/33448286/47558068-eccc7700-d91a-11e8-9258-23a6c840aaa9.png)

**Comment by willdurand** [comment]
Thanks @klymenkoo!

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with Chrome on Win10 and Android 8.0 
The Square is no longer displayed on pages where rating stars are available.

![no square around the star](https://user-images.githubusercontent.com/33448286/47706749-b9e3f500-dc32-11e8-8c93-5da1bec02e08.gif)
