### ISSUE TITLE
Remove `componentWillReceiveProps()` in `UserProfileEdit`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6769]
See also: #6188

---

The whole logic should be updated to leverage both `componentDidUpdate()` (and maybe `getDerivedStateFromProps()`) as described here: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#fetching-external-data-when-props-change

**For QA**: please make sure there is no regression in the "edit" page of a user profile (the page should load/reload just fine, accurate data, etc.)

**Comment by ioanarusiczki** [comment]
@willdurand 
Page is working as before when loading /reloading. 
Except for this https://github.com/mozilla/addons-frontend/issues/7898

**Comment by willdurand** [comment]
Thanks @ioanarusiczki!
