### ISSUE TITLE
Fix `contributions_url` type

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6780]
This issue is related to the following server issue: https://github.com/mozilla/addons-server/issues/9845.

The `contributions_url` field has been updated to return a string value all the time, no more `null`.

For QA: please make sure that no "contribute" button is displayed for an add-on with no contributions url.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this issue on AMO dev with FF63(Win10) 
I used an admin account and verified for a couple of add-ons. "Contribute now" button is available on the add-ons detail page but if went and deleted the Contribution URL from dev hub then checked again the detail page the button is no longer displayed. 

![contribute now](https://user-images.githubusercontent.com/33448286/47796181-7cfc2900-dd2c-11e8-9380-e1379a33f296.gif)
