### ISSUE TITLE
Update permissions code to use information from a version rather than an addon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6782]
`current_version` and `platformFiles` are going to be removed from `addon` so permissions code should be updated to work with a specific `version` object and not use `current_version` or `platformFiles` from an `addon` object.

**Comment by bobsilverberg** [comment]
For QA: Please check the permissions display on the Add-on Detail page.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified permissions with this [sample](https://addons-dev.allizom.org/en-US/firefox/addon/all-of-the-permissions/) on AMO dev FF63 (Win10 & Android 8.0). No regressions found.
