### ISSUE TITLE
Move versions stuff to core

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6788]
Now that I'm working on the install code, which is shared between `amo` and `disco`, I realize that `disco` is going to need access to some of the versions code, so we should move it into `core`.

**Comment by willdurand** [comment]
> Now that I'm working on the install code, which is shared between `amo` and `disco`, I realize that `disco` is going to need access to some of the versions code, so we should move it into `core`.

We should really be careful about not introducing to many things in `amo`. Most (if not all) code related to `addons` should live in the `core` module.

**Comment by bobsilverberg** [comment]
For QA: Please verify the Add-on Detail page, in particular permissions, license, version, and release notes info.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Permissions were verified for https://github.com/mozilla/addons-frontend/issues/6782 
Also, I tested on the extension detail page the license, version and release notes, I edited them from Dev Hub too see different results. They look alright to me.

Verified on AMO dev with FF63 (Win10 & Android 8.0).
