### ISSUE TITLE
8 November homepage programming update

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#6790]
For the **8 November** push, please update the homepage to reflect the programming detailed [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by ioanarusiczki** [comment]
I verified AMO homepage on AMO dev with FF63(Win10 & Android 8.0) and it looks good.
Final validation will be made on AMO prod.
