### ISSUE TITLE
Redux DevTools Extension not available anymore

### ISSUE THREAD

**Issue by Daniel-Pichlmeier** [mozilla/addons-frontend#6792]
### Describe the problem and steps to reproduce it:

Pretty much any google result leads to a 404
the plugins github links to a 404

### What happened?
i don't know :(
### What did you expect to happen?
find the plugin and be able to install it
### Anything else we should know?
I need that plugin! Now i got to work with the filty chrome..

https://github.com/zalmoxisus/redux-devtools-extension
https://addons.mozilla.org/en-US/firefox/addon/remotedev/

**Comment by willdurand** [comment]
That sounds bad but there is nothing we can do here unfortunately, see: https://github.com/zalmoxisus/redux-devtools-extension/issues/568

**Comment by Daniel-Pichlmeier** [comment]
Thanks for the linking and sorry for spamming at you guys :)
FYI(for anyone else who lands here for the same reason): I installed it manually and it works just fine.
