### ISSUE TITLE
Update AMInstallButton to use platformFiles from a version rather than from an addon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6802]
This supports #2770 and depends on https://github.com/mozilla/addons-server/issues/9855.

Use `currentVersion`, which will be explicitly passed in as a prop, to get `platformFiles` as opposed to `addon`. This will affect code in both `amo` and `disco`.

For QA: Please check the install button on both AMO and disco pane.

**Comment by ioanarusiczki** [comment]
I've been testing this for https://github.com/mozilla/addons-frontend/issues/6846
No regressions found.
Verified on AMO dev with FF63 unbranded (Win10) & Android 8.0
