### ISSUE TITLE
Upgrade react-cookie for reliable cookie state

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6803]
**For QA**: please check for regressions in any feature that relies on a cookie:
* log in / log out
* A/B test for green/blue buttons https://github.com/mozilla/addons-frontend/issues/6144
* The *view classic desktop site* link in the footer

<hr/>

We need to upgrade `react-cookie` for better [SSR support](https://github.com/reactivestack/cookies/issues/79#issuecomment-298998732). See https://github.com/mozilla/addons-frontend/issues/6477#issuecomment-434843845 for details on how the older library is likely creating bugs.

**Comment by willdurand** [comment]
Raised to p2 because that seems like something we want sooner than later.

**Comment by kumar303** [comment]
Yeah, good point. We should probably do this before rolling out any new experiments.

**Comment by willdurand** [comment]
Upgrading was straightforward but Enzyme does not support the React Context API (not fully, not with `shallow`), which breaks some test cases...

**Comment by willdurand** [comment]
Documentation at: https://github.com/reactivestack/cookies/tree/master/packages/universal-cookie

**Comment by willdurand** [comment]
> Upgrading was straightforward but Enzyme does not support the React Context API (not fully, not with `shallow`), which breaks some test cases...

I found a nice workaround and filed: https://github.com/mozilla/addons-frontend/issues/6839 to remove it once Enzyme supports the Context API.
