### ISSUE TITLE
View kibana log entries in order of occurrence

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6804]
### Describe the problem and steps to reproduce it:

Try to debug something in [kibana](https://amo-kibana.prod.mozaws.net/_plugin/kibana/app/kibana#/discover?_g=()&_a=(columns:!(_source),index:'amo.frontend_amo*',interval:auto,query:(match_all:()),sort:!(Timestamp,desc))) by looking for all log entries by a given request ID. Example: https://github.com/mozilla/addons-frontend/issues/6477#issuecomment-434843845

### What happened?

The log entries are out of order

### What did you expect to happen?

We should be able to view the log entries in the order of occurrence. Without this, it's hard to debug certain problems.

### Anything else we should know?

The culprit is that we can't get enough timestamp precision so all timestamps are essentially within the same range.

Ideas for a solution? One hack would be to increment a counter in the http context ([example of using http context](https://github.com/mozilla/addons-frontend/blob/7b3232a0515339e63b3191768fbb95bee16de6a4/src/core/middleware/requestId.js#L17)) and add it to each log entry. We could then sort by this field in kibana.

**Comment by kumar303** [comment]
@willdurand can you add some details about why we can't get micro time precision?

**Comment by willdurand** [comment]
`pino` actually provides a way to configure the time function: https://github.com/pinojs/pino/blob/master/docs/api.md#opt-timestamp. I also found this lib: https://github.com/kamicane/microseconds. I can probably put everything together.

I have to update `pino-mozlog` too (because this lib currently does the milli -> micro conversion).

**Comment by willdurand** [comment]
I should actually find a nanoseconds lib because that's what we need to be mozlog-compliant: https://wiki.mozilla.org/Firefox/Services/Logging.
