### ISSUE TITLE
The recommendations card reloads when a rating is posted

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#6805]
STR:

1. Open AMO stage
2. Go to an add-on details page - https://addons.allizom.org/en-US/firefox/addon/narsier-chider-gullo/
3. Rate the add-on
4. Observe the recommendations card

Actual result:
The recommendations card reloads when a rating is posted

Expected result:
The recommendations card is not affected by the actions made in the ratings section

Notes:
- reproduced on all AMO servers with FF63, Win10x64 and Android 8.0

![recom loading](https://user-images.githubusercontent.com/31961530/47852732-5c43da00-dde5-11e8-89dc-1658b2fdaeb1.gif)

**Comment by bobsilverberg** [comment]
Agreed that this shouldn't be happening. I'm going to look into it.

**Comment by bobsilverberg** [comment]
This seems to be happening in prod too, so I don't think it's a recent regression.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF63, Win10x64 and Android 8.0

![recom loading no more](https://user-images.githubusercontent.com/31961530/47911204-822cb580-de9d-11e8-91b0-a325c7720456.gif)
