### ISSUE TITLE
Tweak description of SEO snippet to include add-on type and brand

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#6807]
Followup for https://github.com/mozilla/addons-frontend/issues/4129. I'm adding this to the Q4 project, but feel free to defer if it's not a quick fix.

We need to prepend a bit of text before the add-on description, as shown in the screenshot:

<img width="827" alt="screen shot 2018-11-01 at 2 35 10 pm" src="https://user-images.githubusercontent.com/62568/47867559-78388300-ddc7-11e8-8b1c-e4560adaebc1.png">

The text to add is `Firefox $TYPE 🦊: `. Ignore the underline in the screenshot.

/cc @MeridelW @rraue

**Comment by willdurand** [comment]
We already prepend "Download XXX for Firefox". It will be too long if we add yet another prepended string I think. 

In addition, there is absolutely no reason for Google to use these (meta) descriptions if Google thinks it is not as useful/helpful as what it can find itself.

**Comment by jvillalobos** [comment]
I hadn't noticed that prefix. So, I suppose the request is to replace that with the new one. @MeridelW, can you confirm?

**Comment by jvillalobos** [comment]
@toombsy this is not the right place to ask these questions. If you need general help with Firefox, you can go to https://support.mozilla.org/

**Comment by willdurand** [comment]
ping @MeridelW @rraue
