### ISSUE TITLE
Enable A/B test for install button (green vs. blue) in -prod (and -stage) // AMO only

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6822]
We want to enable the _install button color_ experiment in all AMO envs. The experiment is described in #6144.

**Comment by ioanarusiczki** [comment]
@willdurand I tested the A/B test on AMO stage - FF63(Win10)
- I created new FF profiles and loaded AMO stage. From 10 tries, I got 6 times the blue button and 4 times the green button.
- testing on the same profile, I cleared cookies and then reloaded a detail page.  10 tries: I got 5 times the green button and 5 times the blue button.
- when an add-on or theme is installed the event is sent to GA.

I think the test is ready to go.
Let me know if there anything else should be tested.
