### ISSUE TITLE
Upgrade connected-react-router to 5.0.0 (from 4.5.0)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6824]
We should upgrade `connected-react-router` to v5 to stay up-to-date.

**For QA:** please make sure client navigation works (for example, clicking an add-on on the homepage) and make sure canonical links are still correct in the HTML.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this issue on AMO dev with FF63 (Win10) - navigation works
About the canonical links -> I've noticed that the Search Tool page https://addons-dev.allizom.org/en-US/firefox/search-tools/ is missing the canonical link in the HTML.

The dictionaries and language packs page have a canonical link

`<link rel="canonical" href="https://addons-dev.allizom.org/en-US/firefox/language-tools/" data-react-helmet="true">`

Let me know if I must a separate issue for the Search Tool page.

**Comment by willdurand** [comment]
> @willdurand I verified this issue on AMO dev with FF63 (Win10) - navigation works
> About the canonical links -> I've noticed that the Search Tool page [addons-dev.allizom.org/en-US/firefox/search-tools](https://addons-dev.allizom.org/en-US/firefox/search-tools/) is missing the canonical link in the HTML.

@ioanarusiczki it is up to you. In any case, it will be added in https://github.com/mozilla/addons-frontend/pull/6796. Very good catch, thanks!

**Comment by ioanarusiczki** [comment]
@willdurand Alright. It's better twice than getting away. https://github.com/mozilla/addons-frontend/issues/6841
