### ISSUE TITLE
"Reply to this review" button is not displayed after deleting developer's reply

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6827]
STR:
1. Load AMO dev and make a developer reply for an add-on 
2. Click the permalink
3. Delete the reply, from the upper part of the screen or the one below the review
4. Observe the available buttons below the review

Expected result:
"Reply to this review" and "Flag" are displayed.

Actual result:
Only "Flag" is displayed. The page must be refreshed to display "Reply to this review" button.

Notes:
This is reproducible only when the permalink for a developer reply is displayed on the reviews page.  
This is reproducible on AMO dev and AMO stage with FF64 (Win10)

![delete response](https://user-images.githubusercontent.com/33448286/50160820-d7ecde00-02e2-11e9-9470-a6b613b9f275.gif)

**Comment by xu3u4** [comment]
Hello,
May I take this one?
Thanks.

**Comment by xu3u4** [comment]
Hi @ioanarusiczki 
Sorry, I have some questions,
To reproduce this bug, I create a new theme.
So, how long does it take to get a new theme approved? (so that I can reply it)
Or, is there any step I miss? 
Thank you.

**Comment by ioanarusiczki** [comment]
@xu3u4 The theme must be approved by an admin. Try to submit a dummy extension using this https://staticfil.es/webext-generator/ These are auto approved and then you will be able to see it's detail page and make reviews or developer replies. 
Sorry for answering with a delay. I also updated the bug since I found an easier way to reproduce it.

**Comment by kumar303** [comment]
Hi @xu3u4 , thanks for your interest in contributing! Not all issues are ready for contributors to work so please take a look at ones labelled as [good first bugs](https://github.com/mozilla/addons-server/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+good+first+bug%22).

**Comment by xu3u4** [comment]
Hi @ioanarusiczki ,
Thank you for your instruction. I can reply a review now.

Hi @kumar303 ,
Thank you for your advice. But because I have taken some bugs before, please let me try it.
Sorry I didn't have time previously, I am going to do it!

**Comment by kumar303** [comment]
@xu3u4 fixing this issue may require re-architecting the Redux state in ways that are complex to test so I don't think it's a great issue to work on. I haven't looked at in detail, though. We have lots of [contrib: welcome](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) issues which are in a better state for contributors to work on.

**Comment by kumar303** [comment]
I looked at your patch and I see that you found a simple solution. Good find!
