### ISSUE TITLE
Include a link to easily submit bugs/enhancements to discopane

### ISSUE THREAD

**Issue by krupa** [mozilla/addons-frontend#683]
In the new discopane, we should make it easy for users to report issues or file enhancements. We can add a link 'See a bug? File the bug at https://github.com/mozilla/addons-frontend/issues/new'. This link can exit underneath the AMO button. This would be a good way to seek feedback from our beta users.

**Comment by andymckay** [comment]
I know that @designakt wants to get feedback somehow, but I'm not mad keen on using github for something going out to so many users. AMO has this kind of link and we have it in the validation flow, but dunno, feels wrong on this page to me.

**Comment by designakt** [comment]
I think that is an interesting idea for while we are in beta, not for release. But should probably link to something simpler than github, or even reveal an input field right on the page.
We will also do user tests while in beta and will get a lot of feedback through that. So I don't think we would depend on this for feedback. But it would definitely be nice to have, an I'd happily read through feedback we might gather.

**Comment by muffinresearch** [comment]
Sounds like the beta user testing has this mostly covered, I'm going to mark this as wont fix. We should definitely give some thought to whether this is something we'd want to do on the new AMO pages.
