### ISSUE TITLE
Investigate why speedcurve shows such changeable bundle sizes

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6838]
Looking at the speedcurve graphs tracking bundle-sizes they seem to change up and down with fairly extreme swings. This seems very strange.

Once suggestion would be to log to datadog via the HTTP API the bundle-sizes output by each build so we can compare with speedcurve. 

This would would prove whether it's us or intermittently faulty measuring.

**Comment by willdurand** [comment]
I suppose we're not using speedcurve anymore.
