### ISSUE TITLE
Update core/utils/addons.js to use a direct version

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6846]
This supports #2770. As part of removing `current_version` and `platformFiles` from `addon` and using an actual version from the versions redux state for that data, we need to update the code in `core/utils/addons.js` to not expect to find that data in an addon.

For QA: Please check installing add-ons on both AMO and disco pane.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev - FF63 (unbranded) (Win10)

I tested installation with a few extensions, static themes, language packs and dictionaries. Also, lw themes still can be installed. 

Also 
Install on Disco Pane -dev

![disco pane dev](https://user-images.githubusercontent.com/33448286/48352441-5972a000-e695-11e8-889e-6e19100504c3.gif)

Install from AMO -dev

![amo dev](https://user-images.githubusercontent.com/33448286/48352476-6a231600-e695-11e8-9427-f8f9b75fbca3.gif)
