### ISSUE TITLE
Restart is required for a restartless addon after a Remove->Undo action

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#686]
Prerequisites:
Using the testing steps from: https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing and pointing at -dev.

Steps to reproduce:
1.From new disco pane, install Adblock Plus 
2.From Extensions tab, perform a Remove -> Undo action
3.Go back to Get Add-ons

Expected results:
Adblock plus appear installed 

Actul results:
User is asked for a restart for uninstalling the addon

NOTES: Reproducible on -dev on all languages , platforms and FF versions

Please see video for this bug : 
![refreshnotneeded](https://cloud.githubusercontent.com/assets/1583842/16524767/1e2b7364-3fb2-11e6-81e7-1234003040b3.gif)

**Comment by muffinresearch** [comment]
This is a dupe see https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Current_unresolved_issues specifically this is mostly https://github.com/mozilla/addons-frontend/issues/562
