### ISSUE TITLE
Add-on detail pages on Android when add-on is a static theme

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6862]
See also: https://github.com/mozilla/addons-frontend/issues/6689

---

We plan to migrate lightweight themes (LWT) to static themes (ST) on November 19th. Android currently does not support static themes, hence #6689 to hide everything related to themes (static themes because there won't be any LWT anymore).

ST detail pages are available for Firefox and Android:

- https://addons.mozilla.org/en-US/firefox/addon/reference-static-theme/
- https://addons.mozilla.org/en-US/android/addon/reference-static-theme/

On Android, we see a compatibility error: "This add-on is not available on your platform." and the install button is disabled.

Are we happy with that or do we want to return a 404 in this case? (i.e. clientApp = `android` and add-on is a ST).

/cc @jvillalobos for product input
/cc @rraue for SEO, what's the best? 404 and we re-activate those pages later (when Android supports ST) or we keep those pages indexed

**Comment by willdurand** [comment]
Note: it is possible that some ST will appear in collections and because the API always returns ALL the add-ons, no matter the `clientApp`, ALL add-ons including ST will be listed in a collection detail page.

This behavior is different than the Search API, which takes the `clientApp` into consideration. That is why we don't have to do anything in the search result pages.

**Comment by muffinresearch** [comment]
Aside from SEO implications which @rraue needs to address - I would think it would make sense to just leave these pages as is since the compatibility error is informative - assuming @jvillalobos.

**Comment by rraue** [comment]
I agree if someone searches for this and wants it on android, with the result page the user knows it's not available and that's all the user needs to know and more than we would have if not indexed. Let's leave it like it is.

**Comment by jvillalobos** [comment]
Agree. Show page with compatibility message.

**Comment by willdurand** [comment]
perfect, thanks!
