### ISSUE TITLE
Create a `HeadMetaTags` component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6864]
See also: #6555 

---

In order to add more `meta` tags to all other pages (not add-on detail pages), we need a component that does that in a generic manner.

**For QA:** please make sure OpenGraph metadata are still present in the HTML of an add-on detail page (#3969), as well as the `meta[name="description"]` (#5766), `meta[name="date"]` and `meta[name="last-modified"]` (#5916) tags.

**Comment by ioanarusiczki** [comment]
Verified on AMO Dev - FF63 (Win10)
I checked the metadata on extensions, static themes and lw themes - on their detail pages. All in place.

An example here

![metadata re-check](https://user-images.githubusercontent.com/33448286/48348647-9d13dc80-e68a-11e8-8d90-2704a4b5e082.png)
