### ISSUE TITLE
Invariant Violation: "Method "discoverynavigation" must be one of the registered values

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6866]
### Describe the problem and steps to reproduce it:

An event that logs tracking events when clicking the "Find more add-ons button" isn't registered and causes an invariant violation.

```
Unhandled promise rejection Invariant Violation: "Method "discoverynavigation" must be one of the registered values: addonthemeclicks,addonactivation,themeactivation,addoninstallscancell,themeinstallscancell,addoninstalls,addoninstallsstarted,themeinstallsstarted,themeinstalls,addonuninstalls,themeuninstalls"
```

Refs: #6797

**Comment by ioanarusiczki** [comment]
@willdurand This seems to be related to https://github.com/mozilla/addons-frontend/issues/6867
Please add some STR for qa.

**Comment by willdurand** [comment]
@ioanarusiczki please see my comment here: https://github.com/mozilla/addons-frontend/issues/6867#issuecomment-438633992, if that works, then it also verifies this issue.

**Comment by ioanarusiczki** [comment]
Verified fixed on AMO dev with FF65 (Win10) 
Results are here https://github.com/mozilla/addons-frontend/issues/6867
