### ISSUE TITLE
Unhandled promise rejection Invariant Violation: "Method "addoninstallsdownloa" must be one of the registered values:

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6867]
### Describe the problem and steps to reproduce it:

An event that logs an event for `AMO Addon Installs Download Failed` isn't registered and causes an invariant violation.

Another problem here is that due to string limitations the meaning of this message is hidden.

```
Unhandled promise rejection Invariant Violation: "Method "addoninstallsdownloa" must be one of the registered values: addonthemeclicks,addonactivation,themeactivation,addoninstallscancell,themeinstallscancell,addoninstalls,addoninstallsstarted,themeinstallsstarted,themeinstalls,addonuninstalls,themeuninstalls"
```

I think to fix this the registration of the events needs to be improved as well as covering the possibility of this specific event being logged.

Refs: #6797

**Comment by ioanarusiczki** [comment]
@willdurand  Could you add some STR for qa or perhaps it's a "qa not needed" issue? 
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki can you please try to follow the steps described here: https://github.com/mozilla/addons-frontend/blob/master/docs/telemetry.md#testing-on--dev-hosted-environment? If you can view telemetry events without errors, that will be more than enough! In addition, please let us know if the documentation is not clear.

**Comment by ioanarusiczki** [comment]
@willdurand I followed the steps from the documentation but I'm having problems receiving the events.
I tried on 3 different profiles but no success in receiving events. 
Steps: 
- following prefs set extensions.webapi.testing true, xpinstall.signatures.dev-root true, extensions.webservice.discoverURL for disco pane -dev, ( I used the link from the document too for disco pane -dev https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/57.0/Darwin/normal )

- I used the Browser Control (Ctrl+Shift+J) then run the command 
` const hostURI = Services.io.newURI(
  'https://discovery.addons-dev.allizom.org',
);
Services.perms.add(hostURI, 'hc_telemetry', Services.perms.ALLOW_ACTION);`

It's when the Console returns an "undefined"
- I opened about:telemetry#events-tab and made some interaction on Disco Pane dev, install, remove, refresh but when I select "dynamic" filter I have the one and only Sorry! There is currently no data available in “Events”

Here's how it looks like - I used Ff63 unbranded (Win10)

![telemetry data not received](https://user-images.githubusercontent.com/33448286/48485520-c7e46900-e821-11e8-97f3-39ebf62830bc.gif)

**Comment by willdurand** [comment]
>     * used the Browser Control (Ctrl+Shift+J) then run the command
>       ` const hostURI = Services.io.newURI( 'https://discovery.addons-dev.allizom.org', ); Services.perms.add(hostURI, 'hc_telemetry', Services.perms.ALLOW_ACTION);`
> 
> 
> It's when the Console returns an "undefined"

@ioanarusiczki did you refresh the disco pane after that? can you see "hct enabled" in the console logs (devtools that time, not browser console)?

**Comment by ioanarusiczki** [comment]
I received [GA: ON | HCT: ON] HCT enabled in dev tools and in the browser console too. 
Refreshed disco pane, install, remove again, I receive one event when "parent" is selected in filter but when I choose any other including dynamic there's no content.

dev tools - HCT enabled

![htc enabled](https://user-images.githubusercontent.com/33448286/48487133-fa906080-e825-11e8-954f-18ec64266067.png)

broswer console - HCT enabled

![browser console hct on](https://user-images.githubusercontent.com/33448286/48487332-915d1d00-e826-11e8-8aa9-d5e213ebeae5.png)

**Comment by willdurand** [comment]
> Here's how it looks like - I used Ff63 unbranded (Win10)

@ioanarusiczki can you try in Nightly to be sure?

**Comment by ioanarusiczki** [comment]
@willdurand It works in Nightly. Yey! I'll return with results.

**Comment by ioanarusiczki** [comment]
@willdurand So I could test this only with FF65 (Win10) and using the link given by the documentation for the disco pane meaning this one https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/57.0/Darwin/normal
I did not receive errors in the event "dynamic" tab. I made install, remove and enable of static themes and lw themes and install, remove for extensions ( could not check for enable because the Extensions, Themes tabs are not displayed in the disco pane link I've tested with)

Events are registered without receiving errors about:telemetry#events-tab, filter "dynamic"

![telemetry tab](https://user-images.githubusercontent.com/33448286/48490712-b2c20700-e82e-11e8-99a7-6b26cf33ec37.png)
