### ISSUE TITLE
Do not render featured "theme" collections on Android

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6870]
The homepage shows various shelves. Among them, we sometimes render featured collections. Featured collections seem to contain only "extensions" or "themes" and it is all or nothing. That is why we have a `isTheme` prop in the metadata: https://github.com/mozilla/addons-frontend/blob/50ac9c5e2ba43a95020dad1dd6e9405aa1c6c5a3/src/amo/pages/Home/index.js#L50-L65

We should find a nice way to NOT render the featured "theme" collections when clientApp is `android` (see: #6689).

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF63, Win10x64 and Android 8.0

Desktop
![image](https://user-images.githubusercontent.com/31961530/49794673-cfbffc00-fd40-11e8-93a4-f9ea7d118147.png)

Android
![image](https://user-images.githubusercontent.com/31961530/49794684-d64e7380-fd40-11e8-9680-a3ccefbaeb1a.png)
