### ISSUE TITLE
When an add-on was manually approved by an admin the "Review add-on code" link is not displayed for another reviewer 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6873]
STR:
1. Load AMO dev and with an Admin account approve an extension manually 
2. Go to the add-on detail page and log out then login with an account from the Reviewers: Add-ons Group
3. Click the "Review add-on code" from Admin Links

Expected result:
The review page is displayed. Such as https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/woosh-sease-gorpi

Actual result:
Oops! Not allowed.

Notes:
This issue is not reproducible when the user belongs to both Reviewers: Add-ons and Reviewers: Legacy Groups. 
It looks like it's a front-end issue because the add-on reviewer can open the listed detail page of the add-on from the Add-on Review Log with or without being a Legacy Reviewer. 
Reproducible on AMO dev with FF63 (Win10). 

Add-on reviewer without legacy review rights

![without legacy reviewer](https://user-images.githubusercontent.com/33448286/48262869-b91a4280-e42c-11e8-9d2a-adc8bec116fa.gif)

Add-on reviewer with legacy review rights

![with legacy reviewer](https://user-images.githubusercontent.com/33448286/48262897-d94a0180-e42c-11e8-9a23-bf9a3905c4ce.gif)

**Comment by bobsilverberg** [comment]
I'm not sure I fully understand the issue here, but it sounds like it's an issue with permissions. Either the Reviewer Tools isn't interpreting the permissions correctly, or we shouldn't be displaying the link in the Add-on Detail Page if the user shouldn't actually be able to access the reviewer tools page.

@wagnerand Do you understand the issue and can you comment on where you think the bug is?

**Comment by wagnerand** [comment]
> It looks like it's a front-end issue because the add-on reviewer can open the listed detail page of the add-on from the Add-on Review Log with or without being a Legacy Reviewer.

@ioanarusiczki could you provide a screencast of the this for a reviewer that does not have the Legacy permissions? (I am mostly interested in the the URL the log entry points to, so just that would be sufficient as well). I assume they link to slightly different URLs, since there is a lot of redirection going on in reviewer tools...

**Comment by ioanarusiczki** [comment]
@wagnerand URL is https://reviewers.addons-dev.allizom.org/en-US/reviewers/review/woosh-sease-gorpi
but I repeated the test and what I initially said about the Add-on Review Log is not correct, meaning that when I click the Approved link from the Add-on Review Log for a content reviewer without legacy rights I don't see the review page displayed. 

Therefore I think this issue should be moved to server.

Add-on Review Log

![not allowed without legacy](https://user-images.githubusercontent.com/33448286/48354518-9e4d0580-e69a-11e8-85d7-8628f263b363.gif)

**Comment by wagnerand** [comment]
Ah, you didn't mention you are trying as a content reviewer, not an add-on reviewer. For content reviewers, the correct url would be https://reviewers.addons-dev.allizom.org/en-US/reviewers/review-content/woosh-sease-gorpi

**Comment by ioanarusiczki** [comment]
@wagnerand My mistake again, I just wrote content reviewer but I am talking about an add-on reviewer , I know the difference but in a hurry I wrote "content" instead of "add-on".

**Comment by wagnerand** [comment]
Ok, then I agree, it's probably a permission issue, so in addons-server.

**Comment by bobsilverberg** [comment]
It sounds like everyone agrees this is a server issue. @ioanarusiczki Can you move this to addons-server?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, sure. When I'll file it on server I'll close this one and mention here the new issue( as soon as I can).

**Comment by ioanarusiczki** [comment]
I filed https://github.com/mozilla/addons-server/issues/10003 on server
