### ISSUE TITLE
Google Search "View Image" Button addon is unavailable

### ISSUE THREAD

**Issue by Korb** [mozilla/addons-frontend#6874]
https://addons.mozilla.org/ru/firefox/addon/google-search-view-image/
> Страница не найдена. Извините, мы не смогли ничего найти по адресу, который вы ввели.

Is the add-on removed by the developer?

**Comment by jvillalobos** [comment]
It was removed due to a code review issue. The add-on page will come back once the developer addresses the issues brought up and submits a new version.
