### ISSUE TITLE
Move userAgentInfo into mapStateToProps in withInstallHelpers

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#6878]
This is a follow-up to https://github.com/mozilla/addons-frontend/pull/6848#discussion_r232264142. Once #6848 lands we'll have a `mapStateToProps` in `withInstallHelpers` and we could move `userAgentInfo` out of `WithInstallHelpersProps` and into `WithInstallHelpersInternalProps`.

**Comment by willdurand** [comment]
Upgraded to p3 because that's quite important.

In addition to that, we should also remove the useless checks in `makeMapDispatchToProps`: https://github.com/mozilla/addons-frontend/blob/9eb6d09e6bd20f49014258e3b2454912e7229c0c/src/core/installAddon.js#L525-L545

We can add `invariant` statements in the newly added `mapStateToProps`. We can probably refactor this `makeMapDispatchToProps` function too.

**Comment by willdurand** [comment]
I've upgraded this issue again because #6848 has highlighted a more important issue. I'll update this issue ASAP but the gist is: the HOC assumes an `addon` is always available (and valid), but it is not correct or, at least, it should not be done that way anyway.

My explanation on IRC:

> Everything works as intended with the expectation that we always have an add-on in -prod. That's because the HOC likely gets an `addon` all the time and I think that's because we never run this HOC on the server, only on the client. The client always have an add-on when we load an add-on detail page.
> this is not specific to this HOC, this is how it is
> add-ons are loaded for search results, collections, etc. so we always have then in redux
> so that's why the Flow type assumes `addon` is not nullable

**Comment by kumar303** [comment]
If you load the home page then click on any add-on, it begins rendering with `addon=null`. It probably works because the user cannot trigger any install functions during that time.

**Comment by willdurand** [comment]
right, and we check for `undefined` 😓

**Comment by AlexandraMoga** [comment]
@willdurand is anything more specific to be tested here?
Thanks

**Comment by willdurand** [comment]
@AlexandraMoga I believe making sure we can still add-ons on AMO and Disco Pane should be enough.

**Comment by AlexandraMoga** [comment]
No regressions with add-on installations found on AMO or Discopane.

Verified fixed on -dev with FF63 and Nightly 65 Win10x64 and Android 8.0
