### ISSUE TITLE
Re-enable static theme support for Android

### ISSUE THREAD

**Issue by buttercookie42** [mozilla/addons-frontend#6899]
Companion issue to mozilla/addons-server#9941: As of [bug 1429488](https://bugzilla.mozilla.org/show_bug.cgi?id=1429488), the feature set of themes that was supported on Android with LWTs is also working with static themes now. At the moment this is only in Firefox 65, which would hit Release next February, and at this stage it's not clear whether an uplift to 64 (mid-December) is still possible or not.

Be that as it may, once that happens, Android users can safely be served static themes as well, although for the best experience it would be nice if static themes _without_ a header image could be filtered out: Themes that only change various UI colours won't have any effect on Android and likely won't have for some time to come.

**Comment by AlexandraMoga** [comment]
Now that static themes are also served on Android, users might run into themes that appear installable, but after installation they will have no effect on their browsers. Here are a few examples:

https://addons.mozilla.org/en-US/android/addon/simple-droids-red/?src=search
https://addons.mozilla.org/en-US/android/addon/simple-blue-modern-theme/?src=search
https://addons.mozilla.org/en-US/android/addon/greencrackedwall/?src=search

As mentioned in the comment above, these are all themes without a header, so maybe  we can find a solution to improve this use case.

**Comment by jvillalobos** [comment]
I don't think we'll ever fix this, and we expect to take a different approach for Fenix.
