### ISSUE TITLE
While guide addons are null use the LoadingText component

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6900]
While we are fetching the addon we should show loading text instead of blank space

**Comment by rebmullin** [comment]
hey @willdurand @bobsilverberg , question on this...

as I was looking into the Guide pages, I realized that except for the title, author and icon all of this data is hardcoded. The title and author are set up by the `AddonTitle` which already has the LoadingText set up. For this hardcoded text I feel like this isn't necessary, right? 

Please let me know if I missing something..

**Comment by kumar303** [comment]
Yes, it's still valid. The `GuidesAddonCard` component should render itself with placeholders when `addon` is null. Currently it does not render anything at all:

https://github.com/mozilla/addons-frontend/blob/f1541cdf6f9e5e7510f7263bf866e73551d9b5f5/src/amo/components/GuidesAddonCard/index.js#L82

This approach is bad UX because the page looks janky when it's loading. Here is an example. You can fix this by using loading text placeholders.

<details>
<summary>Screencast</summary>

![addons-frontend-loading mov](https://user-images.githubusercontent.com/55398/49827705-8e831880-fd4f-11e8-9ebf-0fb876a07d47.gif)


</details>

<hr>

Please add the steps to reproduce the bug in the description so that QA will know how to verify it.

**Comment by kumar303** [comment]
> Please add the steps to reproduce the bug in the description so that QA will know how to verify it.

Oh, it's labelled as qa not needed. That's fine but, in the future, try to always add steps to reproduce because it will help communicate why a change is needed.

**Comment by rebmullin** [comment]
ah ok..I see what you mean. Thanks for the demo and extra info :) 
I'll address this..thanks @kumar303.

**Comment by rebmullin** [comment]
QA instructions:
Go to the Home page
Next navigate to one of the Guides pages

You should see these loading bars briefly before addon card is shown: 
![Alt text](https://monosnap.com/image/d9IbgE5S3RpaYuniTJoazCJ3aopXh2.png)

*note this will open happen if the pages are not cached so you may have to clear cache (or try private mode)

**Comment by willdurand** [comment]
> You should see these loading bars briefly before addon card is shown:

We should rather show the cards and *in* the cards, we should have the loading bars. The current work in https://github.com/mozilla/addons-frontend/pull/7213 does not do that but it is a bit odd to see a long loading bar and suddenly a card. We use the loading bars to "mock" texts, not full UI components.

**Comment by AlexandraMoga** [comment]
Verified on dev and stage with FF64, Win10x64

For a really really brief moment, loading indicators will be present in place of an add-on name inside the guidelines' addon cards:

![image](https://user-images.githubusercontent.com/31961530/50897758-c4cabb00-1415-11e9-9d9a-c0fe9f816ac2.png)

I found it a bit odd that we still show the description of an add-on even when if it's details can't be fetched eventually - see first card in the Improve media guides (@rebmullin I think you mentioned this already in the pull discussion)
However, given the fact that the loading time is pretyy quick currently, I don't think it has such a bad impact on the end user.

**Comment by willdurand** [comment]
> I found it a bit odd that we still show the description of an add-on even when if it's details can't be fetched eventually - see first card in the Improve media guides (@rebmullin I think you mentioned this already in the pull discussion)

I don't really a problem with displaying data we already have. Sure, if an add-on cannot be loaded, the card will be hidden but this should not happen in theory. I personally like how it is.
