### ISSUE TITLE
Allow AddonCompatiblityError to determine its own compatibility

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6903]
I discussed this with @rebmullin over Vidyo. Both `AddonCompatibilityError` and the new `InstallButtonWrapper` (which I'll be implementing via #6603) need compatibility info to function. The current approach to this is to get the compatibility info in the parent (currently `Addon`, but soon `GuidesAddonCard` and `AddonVersionCard`) and then pass it into `AddonCompatibilityError` and also use it to determine the logic for the install/GetFirefox button.

Because there will now be multiple consumers of both the `AddonCompatibilityError` and the new `InstallButtonWrapper`, I think it would be better if each of those components could be self-contained and determine their own compatibility status, rather than relying on it to be passed in via their parents.

This issue is about changing the `AddonCompatiblityError` so that the logic for determining compatibility is contained within the component itself.

For QA: Please verify that the various states of the AddonCompatibilityError on the Add-on Detail page continue to work as expected.

**Comment by willdurand** [comment]
I removed the "component: code quality" label because it is not a code quality issue but a requested follow-up issue to break a big patch in smaller ones.

**Comment by bobsilverberg** [comment]
@willdurand I'm sure you have your reasons for not wanting this labelled with "component: code quality", and I don't really have a problem with that, but I did want to point out that I do think it is a valid code quality bug. 

Even though it's a follow-up, it's something that could be deferred as it has no impact on behaviour (or performance, afaict). I realize that @rebmullin probably intends to address it soon, but theoretically, if something more important comes up, it could be left for later, as all it does is *improve the quality* of our code base. Isn't that what a "code quality" bug is?

**Comment by willdurand** [comment]
The rationale behind that is that we should distinguish requested follow-up issues and the "nice to have" issues to improve the overall code quality. This issue was requested to go forward and be able to merge a PR instead of iterating on the same PR, but that was not an option. If we tag this issue as code quality, the request becomes optional and therefore stale.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF63, Nighlty 65 on Wn10x64 and Android 8.0

Compatibility errors were displayed as expected for the varios scenarios tested:
- installation failure
- non-public versions viewed by admins/addon owners
- platform incompatibility
- Firefox version incompatibility 
- legacy addons that require a restart
