### ISSUE TITLE
Circle CI integration test is timing out (exceeding 10 minutes)

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6906]
The integration test that runs on Circle CI has timed out in the last three runs with the error 'Too long with no output (exceeded 10m0s)'. The last log message was:

```
{"Severity": 6, "Logger": "http_app_addons", "Type": "prod_details", "Pid": 648, "Hostname": "2a95be8391d1", "Fields": {"msg": "Updating regions/es-ES.json from server", "uid": "", "remoteAddressChain": ""}, "Timestamp": 1542057206176847104, "EnvVersion": "2.0"}
```

This looks like it was still processing some kind ES related task.

Example: https://circleci.com/gh/mozilla/addons-frontend/11329

**Comment by kumar303** [comment]
@jrbenny35 could you take a look? Is this test crucial? We already run a similar test against the dev server from Travis CI.

**Comment by jrbenny35** [comment]
The current failures are due to upstream addons-server failures. I am working on those.
