### ISSUE TITLE
Add request ID to Sentry errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6908]
We should pass our fancy new request ID to Sentry so that we can correlate any error with related logging.

**Comment by willdurand** [comment]
Sentry is configured right after the `requestId` middleware, so the request ID should be available to Sentry. Apparently, the recommended location for such an ID is Sentry's context: https://docs.sentry.io/enriching-error-data/context/?platform=javascript. Maybe we could use a `amo_request_id` "tag"?

**Comment by kumar303** [comment]
Yeah, I was thinking of using tags but it's trickier on the server because of the concurrency. I have something working -- I'll be asking for feedback on it shortly.
