### ISSUE TITLE
500 internal server error when loading the edit user profile page 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6912]
STR:
1. Load AMO dev and login then click Edit my profile from the drop down menu displayed below the username

Expected result:
Page loads without errors

Actual result:
500 Internal Server Error message is displayed. 

Notes:
This issue is reproducible on AMO dev with FF63(Win10). Not reproducible on AMO stage.

![server error](https://user-images.githubusercontent.com/33448286/48407967-c55e1280-e740-11e8-88ca-eca1eed4bddd.png)

**Comment by willdurand** [comment]
This is not a frontend issue but a server issue, already filed here: https://github.com/mozilla/addons-server/issues/8421.

The -dev Basket API returns 500 errors, which impacts the notifications API endpoint. There is nothing we can do right now (AMO team) but the Basket team has been pinged on both Slack and IRC.
