### ISSUE TITLE
Follow up on how +Add for guide pages should look/be implemented on non-firefox browsers

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6916]
See https://github.com/mozilla/addons-frontend/issues/6432#issuecomment-433083079

I am adding this as its own issue so it stays on our radar.

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with Chrome, Safari, Edge and IE  Win10x64 and Android 8.0

1. **Crome and Safari-** Desktop and mobile

![image](https://user-images.githubusercontent.com/31961530/48894406-5c1a8580-ee4b-11e8-90a7-f3acd601c927.png)
![image](https://user-images.githubusercontent.com/31961530/48894409-5de44900-ee4b-11e8-9722-0ceeaff7197f.png)

2. **Edge** - the text has a slight issue with the center alignment 
![image](https://user-images.githubusercontent.com/31961530/48894450-748aa000-ee4b-11e8-9abb-3825f768c2d3.png)

3. **IE** - the buttons are either cut to the right or missing altogether. However, there are issues all over the site in IE, not just with the guides pages, so I'm not sure if we should invest time in fixing this
![image](https://user-images.githubusercontent.com/31961530/48894464-7d7b7180-ee4b-11e8-81ca-089b8dc40f8c.png)


4. The buttons are cut to the right at a width between 500-530px . This isn't a common breakpoint though.

![image](https://user-images.githubusercontent.com/31961530/48894589-c3383a00-ee4b-11e8-8de2-ed7984444c86.png)


@rebmullin please have a look at 2, 3 and 4 and let me know what you think

**Comment by rebmullin** [comment]
Hey @AlexandraMoga, 

I personally think **2** (on Edge) is fine. 

IE styles definitely looks pretty bad but I am not sure what the priority should be here.  I definitely think if there are other IE issues too then maybe IE is just not a high priority and that maybe we should just open a separate, low priority issue for this too.

@willdurand, what do you think?

**Comment by willdurand** [comment]
Edge looks good. What's the IE version? We support this list of browsers: https://browserl.ist/?q=last+2+versions.

I think we should fix the issue on IE if that's easy, because that'd be nicer.

**Comment by AlexandraMoga** [comment]
@willdurand @rebmullin I have IE 11. I can open a follow up issue to address this but, as I mentioned above, the guides pages are not the only ones that look weird on IE. 
Do you want to invest time in fixing other sections? Below are a few examples, but there are a lot more:

[1] Theme categories on Homepage not showing up
![image](https://user-images.githubusercontent.com/31961530/48999672-07834d00-f160-11e8-8910-87b7e39feb97.png)

[2] Get Firefox button cut on add-on product page' rating breakdown section not loading
![image](https://user-images.githubusercontent.com/31961530/48999666-03572f80-f160-11e8-8036-e6ebc6d4f370.png)

[3] search suggestions not not coming up
![2018-11-26_09-48-45](https://user-images.githubusercontent.com/31961530/48999902-9c864600-f160-11e8-80af-1b7bdd3e738d.gif)

**Comment by willdurand** [comment]
ah well, then maybe not :D

**Comment by rebmullin** [comment]
Since it's very similar, maybe we should handle this the same way we handled no 2 above: https://github.com/mozilla/addons-frontend/issues/4963
