### ISSUE TITLE
The review is not visible after closing and reopening a tab without refreshing page 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6917]
STR:
1. Load AMO dev and login then go to an add-on's detail page to make a review
2. After the review is saved and displayed close the tab
3. Undo closed tab and observe the detail page

Expected result:
The review is visible under the rating stars.

Actual result:
The review is not visible until the page is refreshed.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF63(Win10). 
This issue is also reproducible when the browser is closed and then reopened (with restore previous session option). 

![detail page write a review](https://user-images.githubusercontent.com/33448286/48419534-dfa7e880-e760-11e8-81e1-259ba86854b9.gif)

**Comment by kumar303** [comment]
I can reproduce it. That's sort of odd. I think it's maybe loading the API request from cache but I can't tell because devtools requires a refresh to see network requests.

Since this is an edge case I'm lower the priority.

**Comment by xu3u4** [comment]
I think, from a re-opened tab, the request is cached
![image](https://user-images.githubusercontent.com/6767433/48671301-11ee8700-eb61-11e8-959a-4bad3689c738.png)

**Comment by xu3u4** [comment]
I think it is because the request is cached.
After I ticked `Disable cache`, the result is updated.
![image](https://user-images.githubusercontent.com/6767433/48672743-cba32300-eb74-11e8-9b6b-81bf09390800.png)

**Comment by tsl143** [comment]
@kumar303 , using traditional way for this will be adding timestamp query param to URL.
IMO we should do this to all APIs which are get dynamic data like reviews, addon-details etc.

I can create a PR if we agree to this approach.

**Comment by kumar303** [comment]
I'd rather not go the route of adding a timestamp query param because we do want the request to be cached in some cases. There might be another bug (maybe in the API) because we should have Etags and other headers in the API response to tell the browser when and when not to cache it.

Since this is lower priority, I don't think it's worth spending time on right now. Thanks to everyone who looked into this!
