### ISSUE TITLE
Review usage of log statements

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6918]
Review usage of all log statements with these guidelines in mind. If some logging doesn't follow these guidelines then change them.

- `log.error()` goes to Sentry and should only be used for errors that indicate an application error that can be fixed
  - For example, if a user enters data that fails form validation, this should not result in `log.error()` because it's not an application error
- By default, all uncaught errors get reported to Sentry. Thus, we should not add `log.error()` messages if the error will be thrown; this would create duplicate entries in Sentry
- `log.debug()` messages are hidden by default in local and hosted development. If any debug statements would be useful to track down problems then consider changing them to `warn` or `info`. However, too much logging creates noise so use it in moderation.
- Any log statement at `info` or above should never pass complex objects as arguments. This might result in a memory related DOS if the complex objects are very large (see https://github.com/mozilla/addons-frontend/issues/6369)

**Comment by willdurand** [comment]
Amen to that! We can probably add some guidelines in the documentation.

In addition to all the points above, we could maybe rely more often on `log.warn` to log information related to an error when it makes sense. It would be slightly better than `log.info` because we can filter by severity in Kibana.
