### ISSUE TITLE
Ignore unimportant Sentry errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6919]
There are some Sentry errors that [Firefox clients](https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/?query=is%3Aunresolved+browser.name%3AFirefox) will trigger which we can ignore. We should only ignore errors that do not degrade the user experience, ones that we don't wish to spend time on fixing. 

For example, if we can determine that [this `Oe is null` error in photoswipe](https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/4858666/?query=is:unresolved%20browser.name:Firefox) is not degrading the user experience then we should ignore it.

Non-Firefox clients produce tons of unimportant errors but let's not worry about those for this issue.

We can ignore errors by using the `ignoreErrors` or `ignoreUrls` [config options](https://docs.sentry.io/clients/javascript/config/#optional-settings) in RavenJS.

**Comment by willdurand** [comment]
@kumar303 I'd like to revisit our current usage of Sentry for AMO frontend. Once https://github.com/mozilla/addons-frontend/issues/8270 is fixed, I'd like to wipe all the Sentry events and then start to aggressively manage the new events:

1. ignore all non-FF events as mentioned here, either _via_ config or using the web interface
2. create/bind GitHub issues to events of interest
3. mark events as resolved when we fix the problems

The idea would be to have a Sentry project that we can actually leverage. We did not do anything with 99% of the existing events so far, so removing all of them (except the one for #8259) and starting with a fresh dashboard won't be a problem. WDYT?

**Comment by bobsilverberg** [comment]
This sounds like a good idea to me. I agree it's an issue that we get so many Sentry errors and tend to just ignore most/all of them. It makes Sentry a lot less useful.

**Comment by willdurand** [comment]
@bobsilverberg thanks. Sorry, I did not mean to ignore you, I mainly replied to the original author.. I should use @mozilla/addons-engineering more often...

**Comment by bobsilverberg** [comment]
> @bobsilverberg thanks. Sorry, I did not mean to ignore you, I mainly replied to the original author.. I should use @mozilla/addons-engineering more often...

No worries, it did not bother me and I did not take offense. I saw it in my inbox so I replied. :-)

**Comment by kumar303** [comment]
>     1. ignore all non-FF events as mentioned here, either _via_ config or using the web interface
> 
>     2. create/bind GitHub issues to events of interest
> 
>     3. mark events as resolved when we fix the problems
> 

Sounds good to me as long as there isn't too much of a maintenance burden on the team. We should definitely start by ignoring non-FF errors, though.

**Comment by willdurand** [comment]
Alright so we have releases now. I tried to delete the old events but we have too many and we can't delete more than 1000 events at once.. I enabled a feature that auto-hides events that haven't been seen after 3 weeks. That should help reduce the number of events to look at.
