### ISSUE TITLE
The Guides index page should not double load data

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#6928]
### Describe the problem and steps to reproduce it:

- Go to a guides page, such as http://localhost:3000/en-US/firefox/guides/privacy/ (this isn't available on hosted dev yet)

### What happened?

When the page loads on the client, you can use the Redux tool to see that `FETCH_GUIDES_ADDONS` is dispatched.

### What did you expect to happen?

`FETCH_GUIDES_ADDONS` should not be dispatched on the client because it was already dispatched on the server. You can see this in the console logs:

```
[server|amo] Dispatching FETCH_GUIDES_ADDONS 
```

When it is dispatched twice, the API request to load the data is also made twice. The API request should only be made once.

### Anything else we should know?

Follow up to https://github.com/mozilla/addons-frontend/issues/6661

The pattern for preventing double loading looks like this:

```js
class MyComponent extends React.Component {
  constructor() {
    const { data, dispatch, isLoading } = this.props;
    if (!isLoading && data === undefined) {
      dispatch(loadTheData());
    }
  }
}
```

Here is an explanation:
* The `data` prop would be mapped to something in the state
* Dispatching `loadTheData()` would trigger a saga to make an API request and eventually populate `data` in state. If the API request results in *no data* then the state would be populated with `data: null`
* The loader needs to check `isLoading` to make sure a fetch is not currently in progress.

**Comment by rebmullin** [comment]
QA: Please make sure guide pages still load (you will need to navigate from the home page) until #6991 is ready (for dev)
