### ISSUE TITLE
Create a ducks file for landing code (reducers, actions)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6931]
See also: #4523

---

Let's reduce the number of files by creating a ducks file for the `landing` actions and reducer code. A "ducks" file is a single file following those conventions: https://github.com/erikras/ducks-modular-redux.

**For QA:** please make sure landing and category pages load correctly ("extensions" page, "themes" page, and the category pages).

**Comment by ioanarusiczki** [comment]
@willdurand Pages load correctly. Verified on AMO dev with FF63(Win10).
