### ISSUE TITLE
Create a ducks file for categories (reducers, actions)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6935]
See also: #4523

---

Similar to #6931, let's create a ducks for the `categories` and add more flow coverage.

**For QA:** please make sure categories load fine, all the category pages but also the list of categories on each landing page and the "hidden" categories pages on Android.

**Comment by ioanarusiczki** [comment]
@willdurand I don't see issues - verified the categories to load. 
I've noticed that on Android the pages load a little slower than on desktop but content is displayed.

Android 

![videotogif_2018 11 21_17 04 44](https://user-images.githubusercontent.com/33448286/48846741-85360a00-eda8-11e8-9253-d73ac62a558d.gif)

Desktop 

![category page on desktop](https://user-images.githubusercontent.com/33448286/48846727-7baca200-eda8-11e8-98a5-0e32e2e1c3a7.gif)
