### ISSUE TITLE
Rename landing constants

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6948]
See: https://github.com/mozilla/addons-frontend/pull/6932#discussion_r234034218

---

We should rename the landing constants so that constants and action creators have similar names.

**Comment by xu3u4** [comment]
Hi @willdurand,
I would like to do it.

**Comment by xu3u4** [comment]
Hi @willdurand 
I do some research, may I confirm the renaming with you?

As suggested in this [commit](https://github.com/mozilla/addons-frontend/pull/6932/commits/5f40204c15c55568449ae9645c4567324958ec01#r234034218)
1. `LANDING_GET` can be renamed to `FETCH_LANDING`, but at [/reducers/landing.js](https://github.com/mozilla/addons-frontend/blob/master/src/amo/reducers/landing.js#L61)
The action name is `getLanding`, would it be better to rename it as `GET_LANDING`?
2. If there is no issue, I am going to rename `LANDING_LOADED` to `LOAD_LANDING`.

**Comment by willdurand** [comment]
@xu3u4 please, do it!

I am fine with `LOAD_LANDING` and `GET_LANDING`

**Comment by willdurand** [comment]
@xu3u4 sorry, just saw https://github.com/mozilla/addons-frontend/pull/6965, which is a PR that fixes this issue already :/
