### ISSUE TITLE
Add origin to HCT collection

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6952]
Refs #6797 

In talking over the HCT collection with Will, we realized it was unclear if we are recording the origin or the telemetry collection. We need to do this so we can tell apart where the requests are coming from.

I since checked the data collected so far and there's nothing that indicates the origin of the collection.

To that end we'll want to add the origin to the collection via the extra parameter.

**Comment by muffinresearch** [comment]
Testing notes are here: https://addons-frontend.readthedocs.io/en/latest/telemetry/

If it's working you should end-up with something like this:

<img width="1383" alt="telemetry_data" src="https://user-images.githubusercontent.com/1514/48713208-a3b0cf80-ec07-11e8-9985-84e08120e3ee.png">

Albeit a different origin (this was with a patched firefox)

**Comment by ioanarusiczki** [comment]
@muffinresearch 
@willdurand 

I verified this issue with FF65 (Win10) -disco pane stage -  and the extra parameter is available

![extra parameter](https://user-images.githubusercontent.com/33448286/48844251-f1f9d600-eda1-11e8-864f-ca86d0cf8e07.png)
 
As I said here https://github.com/mozilla/addons-frontend/issues/6867 the last week, while checking the hybrid telemetry for disco pane -dev I tried with FF63 release, FF63 unbranded but I did not receive data until I tried with FF65. Same now, it won't work with FF63. 

Also now I checked with FF ESR 52.9.0 using the same settings mentioned by the documentation here https://github.com/mozilla/addons-frontend/blob/master/docs/telemetry.md#testing-on--dev-hosted-environment and opened the same profile with the settings made but with ESR I don't even see the "event" tab.

![esr](https://user-images.githubusercontent.com/33448286/48844564-e65adf00-eda2-11e8-8931-b86214bb6c0c.gif)

**Comment by muffinresearch** [comment]
@ioanarusiczki did you refresh the telemetry page - the events tab sometimes disappears and/or doesn't appear until there is event data? Also with some of these settings you might need to restart your browser, if you find we're missing a step in the testing notes please let us know.

**Comment by muffinresearch** [comment]
Looking at the screen-capture more closely it looks like you did refresh `about:telemetry` so maybe try a restart. Also, please check further up in the browser console for errors.

**Comment by muffinresearch** [comment]
Also it's worth noting the current ESR should be 60.3.0esr

**Comment by muffinresearch** [comment]
Ah ok I see the problem looks like there's a bug on the firefox side which ESR is too early to have the fix for - I see this message:

```
Security wrapper denied access to property "canUpload" on privileged Javascript object. Support for exposing privileged objects to untrusted content via __exposedProps__ has been removed - use WebIDL bindings or Components.utils.cloneInto instead. Note that only the first denied property access from a given global object will be reported.
```

That's this bug [1]  HCT can't work on the current ESR versions because that patch only made it to 63.  So the only check is to make sure it's not breaking the disco pane from functioning - from my testing I can still install add-ons and themes.

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1472228

**Comment by muffinresearch** [comment]
I'll file an issue to update the docs with a message about where collection is supported.

**Comment by ioanarusiczki** [comment]
@muffinresearch the stage about:addons is working, I can install and uninstall extensions and themes. - FF63 (unbranded) (win10)
Thanks for the updates. Then I think that I can mark this issue as verified.

**Comment by muffinresearch** [comment]
This doesn't need to block the release, but I can also confirm I don't see collection in release (63), so I'll need to find out what's going on there. I don't see any errors related to collection either.

**Comment by ioanarusiczki** [comment]
@muffinresearch I tried it with both FF63 -release & unbranded and I did not receive events. I did not receive errors either, and I tried with https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/57.0/Darwin/normal (because from about:addons won't work with FF63 or FF65, I receive [GA: ON] Not logging to telemetry since hctEnabled is disabled)

Console without errors
![no errors](https://user-images.githubusercontent.com/33448286/49162508-b330c680-f333-11e8-8cf7-3a5bbf87d4ed.png)
