### ISSUE TITLE
Improve Flow coverage of ` src/core/reducers/abuse.js `

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6959]
The file `src/core/reducers/abuse.js` lacks some Flow types. Let's add more Flow types for actions/params and also use `invariant`.

**For QA:** please make sure the report button located on an add-on detail page still works.

**Comment by ioanarusiczki** [comment]
@willdurand  I verified Report this add-on for abuse button on AMO dev and AMO stage - FF63(Win10 & Android 8.0) and a report can be done using it - with or without login.

![report for abuse1](https://user-images.githubusercontent.com/33448286/48842164-2ec2ce80-ed9c-11e8-8dc3-29938ab18030.gif)
