### ISSUE TITLE
Add tab_line picker to theme editor

### ISSUE THREAD

**Issue by nt1m** [mozilla/addons-frontend#6963]
Right now, there's no tab_line picker in the theme editor, which seems to be encouraging theme authors to change the accentcolor to change the tab line color, which produces inaccessible themes, since the accentcolor is used as window background.

Here's an example of a bug that this causes: https://bugzilla.mozilla.org/show_bug.cgi?id=1506913

@eviljeff Would it be possible to add a "Tab line color" field that changes the tab_line property ?

**Comment by willdurand** [comment]
That's probably a addons-server issue :)

**Comment by nt1m** [comment]
Isn't the interactive theme editor part of the front end though ?

**Comment by willdurand** [comment]
> Isn't the interactive theme editor part of the front end though ?

You probably mean the editor in DevHub, which is part of addons-server. This project is AMO only (the dark blue website).

**Comment by nt1m** [comment]
@willdurand Ok, feel free to transfer addons-server if you think it's relevant. (There's a beta "Transfer this issue" feature on Github available for admins that I probably don't have access to)

**Comment by willdurand** [comment]
Re-filed: https://github.com/mozilla/addons-server/issues/10028
