### ISSUE TITLE
Can't install any extensions

### ISSUE THREAD

**Issue by jish** [mozilla/addons-frontend#6964]
### Describe the problem and steps to reproduce it:

Can not view any Firefox extensions for installation.

1. Go to Tools -> Add-ons
2. Search for "stylish"
3. Click on "Stylish - Custom themes for any website"

### What happened?

Server error page is displayed

<img width="934" alt="screen shot 2018-11-17 at 12 27 22 pm" src="https://user-images.githubusercontent.com/1817/48665507-93142400-ea64-11e8-8d37-afb2565c6a9a.png">

### What did you expect to happen?

I can install a browser extension in Firefox

### Anything else we should know?

<img width="1680" alt="screen shot 2018-11-17 at 12 31 54 pm" src="https://user-images.githubusercontent.com/1817/48665519-d2db0b80-ea64-11e8-9032-63e261255ca3.png">

**Comment by willdurand** [comment]
@jish hi, sorry for that. Do you have cookies disabled by chance? I am asking because there is a similar issue #6962

**Comment by jish** [comment]
Cookies are sort of disabled in my browser, I whitelist cookies for websites that I want to log into. Yes, #6962 looks like a similar issue to this one. Firefox extensions can not be installed in either of our browsers.

**Comment by Alex-Canales** [comment]
I have the same problem as @jish and #6962. If I block all cookies, the page crashes; if I block only third party cookies, it works.

I would like to precise that if I enable the cookies, the only value stored in the cookie has as key `installButtonColorExperiment` and value `green` or `blue`. This is used to set the colour of the button `+ Add to Firefox`.

**Comment by willdurand** [comment]
> I would like to precise that if I enable the cookies, the only value stored in the cookie has as key `installButtonColorExperiment` and value `green` or `blue`. This is used to set the colour of the button `+ Add to Firefox`.

Yep, that's an experiment we deployed last Thursday evening. We should have tried with all cookies disabled...

How do you block all cookies BTW?

**Comment by bobsilverberg** [comment]
@willdurand To block cookies, go to Preferences -> Privacy & Security, and there's an option to "Block cookies and site data (may cause websites to break)".

I just tried with cookies turned off and it does indeed break the install process as described in this bug.

**Comment by bobsilverberg** [comment]
It sounds like this could be combined with #6962, and it also sounds like this should be a P1. I'm not sure if I'll have time to work on it today, but someone should probably pick it up ASAP. @willdurand do you want to take a look at it when you start on Monday?

**Comment by willdurand** [comment]
> It sounds like this could be combined with #6962, and it also sounds like this should be a P1. I'm not sure if I'll have time to work on it today, but someone should probably pick it up ASAP. @willdurand do you want to take a look at it when you start on Monday?

It is still the weekend here, so there is no rush... I'll ask the team tomorrow morning (Monday) to see if it needs a hotfix (I think that's needed).

**Comment by willdurand** [comment]
I just merged a patch to fix this issue into `master`. We'll deploy this patch as a hotfix today (November 19th). Thanks for the bug report and sorry for the inconvenience 😞

**Comment by ioanarusiczki** [comment]
@willdurand The search scenario for an add-on from Add-on manager and then opening the detail page had the same problem as in https://github.com/mozilla/addons-frontend/issues/6962 

As @bobsilverberg mentioned [above](https://github.com/mozilla/addons-frontend/issues/6964#issuecomment-439717675) the detail pages won't be displayed when "Block cookies and site data (may cause websites to break)" is set.

It is no longer reproducible on AMO dev and AMO stage with FF63 (Win10). 

![stage - all cookies blocked](https://user-images.githubusercontent.com/33448286/48702836-a22cda80-ebfa-11e8-99b6-5286cb72ba09.gif)

**Comment by willdurand** [comment]
The hotfix has been deployed on https://addons.mozilla.org/en-US/firefox/.

**Comment by jish** [comment]
Wow, that was fast!

I can install extensions now, thank you! 🙇
