### ISSUE TITLE
"Undo" drop down bar should be removed when a theme is uninstalled via on\off radio button

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#697]
Prerequisites:
Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:50.0) Gecko/20100101 Firefox/50.0

Steps to reproduce:
1.Follow instructions from https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing in order to set up the new disco pane on Nightly, AMO-dev
2.Install a new theme from about:addons(observe the "Undo" and "Manage Themes" drop down bar after a successful installation)
3.From on\of radio button, remove the theme

Expected results:
The "Undo" bar should be closed when a theme is uninstalled

Actual results:
"Undo" bar is still displayed

Please see video for this bug :  
![undo](https://cloud.githubusercontent.com/assets/1583842/16562694/e44ebb18-4206-11e6-9af2-2b9c82f3564a.gif)

**Comment by muffinresearch** [comment]
We need to work out what browser APIs exist to do this since this the display of the bar is something that happens indirectly as a result the theme installation and isn't something that's triggered from the page explicitly.

@aswan any thoughts?

**Comment by aswan** [comment]
This seems like something that the browser should be doing automatically (i.e., if there is a change to the theme's status coming from somewhere other than the bar, the bar should be dismissed).  I'm not familiar with the existing code that displays that bar so I don't know how difficult that would be, but can you open a Firefox bug?

**Comment by muffinresearch** [comment]
Filed: https://bugzilla.mozilla.org/show_bug.cgi?id=1284561

**Comment by designakt** [comment]
In future, it would be great to see themes show the same behavior than extension: 
Show a door-hanger confirming install instead of the notification bar.
(Unifies UI for users, and we would not need to maintain 2 separate systems)

**Comment by muffinresearch** [comment]
@designakt yep I agree, if we can stop the default behaviour then we can implement the notification / UiTour for themes too.

**Comment by Ryuno-Ki** [comment]
Bugzilla Bug was marked as "Resolved duplicate".

**Comment by muffinresearch** [comment]
Resolved upstream nothing to do here.
