### ISSUE TITLE
Add OpenGraph default image

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6971]
See also: https://github.com/mozilla/addons-frontend/issues/6555

---

We should add a default image to the Open Graph meta tags. The image has been provided by @pwalm here: https://github.com/mozilla/addons-frontend/issues/6555#issuecomment-439499941.

**For QA:** most add-on detail pages should have an image that is either the preview URL (LWT IIRC) or the first screenshot, but maybe the default image will be used if there is no preview or screenshot: that's fine. Other pages should have the default image, and no page should have no Open Graph image.

**Comment by ioanarusiczki** [comment]
@willdurand I verified the `og:image` on AMO dev with FF63(Win10)
- All pages have an image. This one https://addons-amo-dev-cdn.allizom.org/cdecc075e09aee4207a940a3efd67cb8.png
- A lw and static theme will have their own previews such as https://addons-dev-cdn.allizom.org/user-media/addons/165163/preview_large.jpg?modified=a90ba4c2 or https://addons-dev-cdn.allizom.org/user-media/version-previews/full/0/283.png?modified=1532105296
- An extension with screenshots will include in it's meta-data the first image displayed by the screenshot viewer. If it doesn't have a screenshot it will be replaced by the generic image https://addons-amo-dev-cdn.allizom.org/cdecc075e09aee4207a940a3efd67cb8.png
