### ISSUE TITLE
The product detail page for a non public addon is not displayed for admins and developers

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#6976]
Followup for https://github.com/mozilla/addons-frontend/issues/6944 and https://github.com/mozilla/addons-frontend/issues/4244

STR:
1. Load AMO dev and submit an add-on, wait for it's approval.
2. As a developer disable it's first version
3. Click on View Listing link

Expected result:
The detail page is shown for the developer with the message "This is not a public listing. You are only seeing it because of elevated permissions."

Actual result:
The page is not displayed. 

Notes:
This is not reproducible once the version is re-enabled  - but it's because of https://github.com/mozilla/addons-server/issues/3051.
Also when the add-on is disabled by an admin from rev tools the issue is not reproducible.
Reproducible on AMO dev and AMO stage with FF63(Win10).

![disabled - first version](https://user-images.githubusercontent.com/33448286/48719357-f600e900-ec25-11e8-8288-33bd0c589bcc.gif)

**Comment by bobsilverberg** [comment]
This is another case where `currentVersion` can be `null` and the code isn't dealing with it. The problem is at https://github.com/mozilla/addons-frontend/blob/2018.11.15-1/src/core/components/AMInstallButton/index.js#L296 and I will create a patch to fix it.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I still see some issues here. I verified it with FF63(Win10). 

- When the version is disabled from Dev Hub the link " View Listing" is still not working to redirect to the detail page. So before disabling the version I left the detail page opened in a different tab and refreshed it to check that there's no longer a server error. 

![the disabled by developer addon](https://user-images.githubusercontent.com/33448286/48777153-81d44d00-ecda-11e8-9714-22b2103e3169.gif)

- The messages displayed are not the same as when the add-on is disabled from rev tools by the admin or when it's left "invisible" by the developer. It's an extra "This add-on is not available on your platform." and "Not compatible with Firefox Quantum" but I think that "This is not a public listing. You are only seeing it because of elevated permissions." should be enough.

![extra warnings](https://user-images.githubusercontent.com/33448286/48777190-9c0e2b00-ecda-11e8-9cac-278b94dd59d8.png)

**Comment by bobsilverberg** [comment]
Thanks for the reports @ioanarusiczki. 

For the first one, about the link from DevHub not working, that seems like it must be a server issue. You said that it "is still not working ", so is this an old issue? In either case, I believe that needs to be filed for addons-server.

I'll look into the second issue about the extra messages being displayed.

**Comment by bobsilverberg** [comment]
@ioanarusiczki I think it would be best to open a separate issue for the second point because I believe the current issue has been resolved and this should be treated as a separate bug.

**Comment by bobsilverberg** [comment]
@ioanarusiczki Are you sure the "Not compatible with Firefox Quantum" badge is a regression? As far as I can tell, that would always have shown up in this case. There haven't been any changes to the logic for that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Then it is not a regression but I still believe that the quantum badge is not necessary.  I guess it could stay as it is too. 
I will file the problem on server for the link from dev hub as a followup and close this one.

**Comment by bobsilverberg** [comment]
@ioanarusiczki Thanks. I don't think we should spend time addressing the Quantum badge as this only affects admins looking at non-public add-ons. I could fix the other issue where we display both the "This is not a public listing." and the "This add-on is not available on your platform." messages, but maybe that's also too much of an edge case to bother with.

Let me know what you think.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Well, if that's not much of an effort then let's remove the platform message. I filed https://github.com/mozilla/addons-frontend/issues/7036 
Indeed, it is quite an edge case.
