### ISSUE TITLE
Update categories API code

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6978]
See: https://github.com/mozilla/addons-frontend/pull/6936#discussion_r234698020

---

We could extract the API code into its own file and change the name of the API functions. Instead of relying on API code located in `core/api/index` (or `core/api`), we should create a file `core/api/categories.js` and import the API functions from `core/api/categories`.

**For QA:** please make sure categories are successfully loaded on all landing pages (both extensions/themes and firefox/android).

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev and AMO stage - FF63 (win10 & android 8.0)
The category pages load correctly.

![category landing page](https://user-images.githubusercontent.com/33448286/48839807-52cee180-ed95-11e8-82bc-d6faa537876e.gif)
