### ISSUE TITLE
Turn on enableFeatureNewHomeHero in prod

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6981]
dependency: 

need to make sure guids/addons exist on stage too (currently they don't)

**Comment by rebmullin** [comment]
we will need to update prod instead and update any tests. I'll update the title

**Comment by ioanarusiczki** [comment]
@rebmullin 
I verified this issue on AMO stage with FF63 (Win10 & Android 8.0) 

- the guide lines don't have layout issues when the browser is resized
- the links redirect correctly
- the suggested add-ons can be installed/removed 
- Android platform will only display a text and the guide lines are hidden

The final validation will be made on AMO prod.
