### ISSUE TITLE
Add a route for the new guide pages ( /guides/:slug/)

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6991]
We'll need new routes in nginx for the new guide pages. Here is what we need:

/guides/:slug/

Right now we just need this for dev. 

I can update this issue when it's needed on stage and prod.

**Comment by bqbn** [comment]
We use the regex on https://github.com/mozilla/addons-server/blob/master/src/olympia/addons/urls.py#L9 to match ADDON_ID, similarly, can you recommend what a proper regex would be to match the guide `slug`?

**Comment by rebmullin** [comment]
hey @bqbn, I am not sure there will be a pattern we could use for these pages. 

I am actually waiting to hear back on the 3 current pages tho:

https://github.com/mozilla/addons-frontend/issues/6751

I'll keep you posted..

**Comment by willdurand** [comment]
> hey @bqbn, I am not sure there will be a pattern we could use for these pages.
> 
> I am actually waiting to hear back on the 3 current pages tho:
> 
> #6751
> 
> I'll keep you posted..

I believe it should be something like `[-a-zA-Z]+`

**Comment by bqbn** [comment]
The route is on -dev.  Please test it.

Let us know when it should be enabled on -stage and -prod.

**Comment by rebmullin** [comment]
this looks good on dev. thanks @bqbn.

**Comment by bqbn** [comment]
The route is now on -prod.
