### ISSUE TITLE
Enable Hybrid Content Telemetry for the disco pane in production.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#6993]
Enable HCT for collection in parallel with GA on stage and production

**Comment by ioanarusiczki** [comment]
@muffinresearch 
@willdurand 

- This was verified on AMO -dev with FF65(Win10) here https://github.com/mozilla/addons-frontend/issues/6968
- I also verified it on AMO -stage using the same steps. 
Disco Pane stage link is https://discovery.addons.allizom.org/en-US/firefox/discovery/pane/57.0/Darwin/normal and typed in the browser console 
`const hostURI = Services.io.newURI(
  'https://discovery.addons.allizom.org',
);
Services.perms.add(hostURI, 'hc_telemetry', Services.perms.ALLOW_ACTION);`

Navigated to about:telemetry#events-tab and selected the dynamic filter (top-right dropdown) 

Events from disco pane -stage

![telemetry stage](https://user-images.githubusercontent.com/33448286/48833575-573ece80-ed84-11e8-9396-ad2f59ca3a72.png)

The final validation will be made on AMO prod (so I'll leave it for now without the verified label).

**Comment by muffinresearch** [comment]
@ioanarusiczki This got reverted see https://github.com/mozilla/addons-frontend/issues/6797#issuecomment-440985010 for details. We'll need to await a fix in Firefox before further testing.

/cc @vcarciu
