### ISSUE TITLE
Replace `webpack-isomorphic-tools` by something else

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#6996]
We should replace https://github.com/catamphetamine/webpack-isomorphic-tools by something else given that the lib is not recommended by their author...

It still works as intended, and it survived a webpack4 upgrade (#6995) but it is a blocker to upgrade other webpack dependencies such as replacing `extract-text-webpack-plugin` with https://github.com/webpack-contrib/mini-css-extract-plugin.

**For QA:** the site should work as intended, everything should load fine, both from the server and when navigating in the browser.

**Comment by willdurand** [comment]
We had to switch to `mini-css-extract-plugin` in #7004 because of build issues (CSS was not sorted correctly in the final bundle). This seems to work fine but there are a few warnings from `webpack-isomorphic-tools` related to CSS files.

Yet, I did not notice any difference in terms of usability, and the generated `webpack-assets.json` file is very similar to the same file generated **before** webpack 4 + `mini-css-extract-plugin`.

In any case, we should get rid of `webpack-isomorphic-tools`...

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-frontend/issues/2377

**Comment by willdurand** [comment]
> Makes me wonder how does next.js handle this?

@muffinresearch next.js compiles the code for the client **and** for the server. By compiling the code for the server (with webpack), it opens the door to many solutions, like ignoring non-JS imports (converting the `import ...` to "nothing").

**Comment by willdurand** [comment]
Given that https://github.com/catamphetamine/universal-webpack is recommended to replace `webpack-isomorphic-tools`, that seems consistent with what next.js does at least.
