### ISSUE TITLE
'More...' label not in line with the other tabs (Explore, Extensions & Themes)

### ISSUE THREAD

**Issue by ItielMaN** [mozilla/addons-frontend#7005]
### Describe the problem and steps to reproduce it:
1. Open https://addons-dev.allizom.org/he/firefox/ 
2. See the 'More...' label at the top (...עוד)
3. Compare to the same label to the one at https://addons.mozilla.org/he/firefox/

### What happened?
The 'More...' label is not in the same line with the other tabs (Explore, Extensions, Themes).

### What did you expect to happen?
To look the same as it is in https://addons.mozilla.org/he/firefox/

### Anything else we should know?
New (bad):
![default](https://user-images.githubusercontent.com/18016656/48800719-45711300-ed13-11e8-9a0f-6e9cfc320be6.png)

Vs. old (good):
![default](https://user-images.githubusercontent.com/18016656/48800752-57eb4c80-ed13-11e8-943a-75be4e80d864.png)

I should also note that the anchor of the popup that is shown when hovering over the 'More...' label is not centered to the label's text:
![default](https://user-images.githubusercontent.com/18016656/48800817-8832eb00-ed13-11e8-8304-25f690da9ff2.png)

Vs. how it's shown in the en-US version of AMO:
![default](https://user-images.githubusercontent.com/18016656/48800880-adbff480-ed13-11e8-9f68-c55e821a7c25.png)

**Comment by willdurand** [comment]
This is probably related to the webpack upgrade

**Comment by ItielMaN** [comment]
Do you know if #7004 will take care of the other issue mentioned in the description?

**Comment by willdurand** [comment]
It is worth mentioning that with Node 11, the order of the CSS is correct. With Node 8 (current production version), the order is completely different with the same settings...

**Comment by willdurand** [comment]
So, I believe #7004 fixed this issue.

**Comment by ItielMaN** [comment]
@willdurand Yes, the main issue is fixed but the second one is still there. Shall I file a new bug for this?

**Comment by willdurand** [comment]
which second issue? I suppose yes.

**Comment by ItielMaN** [comment]
> which second issue? A new issue would be nice.

Done. See #7014.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, Win10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/48937944-5c348700-ef18-11e8-9f0d-da5991bac74a.png)
![image](https://user-images.githubusercontent.com/31961530/48937955-648cc200-ef18-11e8-9fc7-070541661b22.png)
