### ISSUE TITLE
Page layout looks broken on AMO -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7006]
STR:

1. Load AMO -dev homepage - https://addons-dev.allizom.org/en-US/firefox/
2. Observe the layout

Actual result:
The page components look broken

Expected result:
There are no layout issues on any of the AMO pages

Notes:
- #7005 seemed to mention a problem only with the `More`... menu alignment, hence I've opened this issue
- @willdurand it's possible that #7004 will also fix this issue?

![image](https://user-images.githubusercontent.com/31961530/48824523-374fe080-ed6d-11e8-8d70-413dd821379e.png)

**Comment by willdurand** [comment]
Hopefully #7004 will fix that, yep. I am working on it.

**Comment by willdurand** [comment]
So, I believe #7004 fixed this issue too.

@AlexandraMoga can you check AMO -dev and Disco -dev too? Thanks! Both apps should work fine and there should be no visual regression.

**Comment by AlexandraMoga** [comment]
@willdurand things are back to normal on -dev and disco pane. Thanks!

![image](https://user-images.githubusercontent.com/31961530/48832630-42f9d200-ed82-11e8-86d6-1026fe1d6963.png)

![image](https://user-images.githubusercontent.com/31961530/48832637-49884980-ed82-11e8-96dc-828d2afcf1d2.png)
