### ISSUE TITLE
Sourcemap in -prod, do we need it?

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7008]
Our `production` webpack configuration generates sourcemap files, which is not recommended according to this: https://webpack.js.org/configuration/devtool/#production.

I tried to use the JS sourcemap on addons.mozilla.org, but it crashed my browser.. I am not sure why we have this enabled, and why we need it... For sentry maybe?

Should we keep those files? I believe generating such sourcemaps has a cost during the build process.

/cc @muffinresearch @kumar303

**Comment by muffinresearch** [comment]
If it's not recommended and/or useful then I'm in favour of ditching it.

**Comment by kumar303** [comment]
Yes, we need source maps in prod for Sentry. Aside from that, I think it would come in handy when using developer tools to view an error in production. The source map shouldn't pose any problem in production (I think?) since it's only loaded on demand.

**Comment by willdurand** [comment]
> Yes, we need source maps in prod for Sentry. Aside from that, I think it would come in handy when using developer tools to view an error in production.

I could not use it personally, I don't know if it is FF that cannot digest it or something else, but that did not work. It seems to work for Sentry though, so I guess the generated source maps are still valid.

> The source map shouldn't pose any problem in production (I think?) since it's only loaded on demand.

No, but it is not recommended to expose it. Sentry recommends to use their plugin to automatically upload source maps to their servers, without exposing the files on The Internets. I am not sure it adds value though, given that everything is open here anyway.

Closing this issue now since I have the answer to my question.

**Comment by kumar303** [comment]
> I am not sure it adds value though, given that everything is open here anyway.

Yeah, I agree. That sounds like security through obscurity unless I'm missing something.
