### ISSUE TITLE
Coudn't find Saaspass extension page

### ISSUE THREAD

**Issue by jaysonwcs** [mozilla/addons-frontend#7010]
### Describe the problem and steps to reproduce it:

Couldn't find Saaspass extension.

### What happened?

Redirected to the page showing that "This add-on has been removed by its author."

### What did you expect to happen?

Redirect to Saaspass extension page download

### Anything else we should know?

Link showed in the page: https://addons.mozilla.org/en-US/firefox/addon/saaspass-single-sign-on/

**Comment by willdurand** [comment]
The page says "This add-on has been removed by its author." so we cannot do anything unfortunately. Sorry.
