### ISSUE TITLE
Jest no longer pauses nicely when pressing "p"

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7012]
As discussed in IRC:

In the past, I could press "p" during a test run and the run would stop and allow me to enter a pattern. Now, the run does not stop, it just keeps running, although it also seems to prompt me for a pattern. Pressing "Enter" does stop the run, but in the past any key would work.

Here's a screenshot. In this video I first press "a" to start the run with all the tests. Then I press "p" and you can see the prompt appear, but the tests also keep running. You can also see me enter some text at the prompt. A few seconds later I press "Enter" which does cause the tests to stop running. Finally I press "q" to quit from the test runner.

![nov-21-2018 09-39-34](https://user-images.githubusercontent.com/142755/48848462-f27a7880-ed71-11e8-857e-cfc24a813422.gif)

**Comment by bobsilverberg** [comment]
Note that I don't consider this a serious issue, as I can just start using "Enter" instead of "p" to pause the tests, but @willdurand asked me to file the issue anyway, so here it is. 😄

**Comment by willdurand** [comment]
I can reproduce, but not all the time. Maybe it is the Flow or ESLint reporter, or maybe a regression in Jest.

**Comment by willdurand** [comment]
Looks like it is fixed, probably because of recent lib upgrades.
