### ISSUE TITLE
[RTL] The anchor of the popup that is shown when hovering over the 'More...' label is not centered to the label's text

### ISSUE THREAD

**Issue by ItielMaN** [mozilla/addons-frontend#7014]
### Describe the problem and steps to reproduce it:
1. Open https://addons-dev.allizom.org/he/firefox/ 
2. Hover the 'More...' label at the top (...עוד)
3. Hover the same label at https://addons-dev.allizom.org/en-US/firefox/, and see the differences

### What happened?
The anchor is aligned to the beginning of the text, instead of its center.

### Anything else we should know?
![default](https://user-images.githubusercontent.com/18016656/48849557-4788af80-edaf-11e8-85bd-cb8da05123f8.png)

See how it's shown in the en-US version of AMO:
![default](https://user-images.githubusercontent.com/18016656/48800880-adbff480-ed13-11e8-9f68-c55e821a7c25.png)

**Comment by willdurand** [comment]
Hey @ItielMaN, awesome, thanks!

So this has always been like that I suppose, no? From what I can tell you, we align this white menu with the "down" arrow. Because in your language, "More..." is very short, we have this UI glitch.

**Comment by willdurand** [comment]
> Thought so. So I take it there's no solution to this?

Nope, I will see if I can fix that but it is rather low priority to be honest.

**Comment by ItielMaN** [comment]
> Nope, I will see if I can fix that but it is rather low priority to be honest.

Understood. Thanks!

**Comment by ItielMaN** [comment]
Well, this is still an issue.
Also, I'm not sure if this I'd valid to RTL languages only.

**Comment by ItielMaN** [comment]
My previous comment still stands.

**Comment by ItielMaN** [comment]
Yup, still an issue.

**Comment by ritik307** [comment]
Hey @ItielMaN , Can I work on this issue. I am new to open source and I am willing to contribute to the organization

**Comment by ItielMaN** [comment]
@ritik307 Go ahead, no one seems to be working on this.

**Comment by ritik307** [comment]
> @ritik307 Go ahead, no one seems to be working on this.

Can you provide repo link for the project please.

**Comment by ritik307** [comment]
@ItielMaN sir can you please provide the link to the repo

**Comment by ItielMaN** [comment]
Still an issue.

**Comment by ItielMaN** [comment]
Yup. Still an issue.
