### ISSUE TITLE
Move version-related types into versions reducer

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7015]
There are a number of types in `core/types/addons.js` which only pertain to versions. These should be moves into `core/reducers/versions.js` as that's where they really belong.

While doing this, we should update `VersionLicenseType` to support the new `is_custom` property that was added in https://github.com/mozilla/addons-server/issues/9914.

For QA:

While this will not change any observable behaviour, it does move code around in some highly used components, so should be checked. Checking for regressions on the Add-on Detail page, as well as with the install process should be sufficient.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified the detail pages on AMO dev and the install for extensions/themes with FF63 unbranded (Win10).  
Detail pages look good, reviews and reports work, links redirect to other pages and I could install/remove/enable add-ons without problems. 
Also install works on Disco Pane.
