### ISSUE TITLE
"Download Firefox" looks cut on small devices

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7020]
Followup for https://github.com/mozilla/addons-frontend/issues/6901

STR:
1. Load AMO dev with Chrome (on an android phone) or Safari (for an iOS phone) and observe the "Download Firefox" button

Expected result:
The button has no display issues.

Actual result:
The button doesn't have the right border.

Notes:
Reproducible on AMO dev and AMO stage Chrome and Safari with Android 8.0 and iOS 12.1

![no borders](https://user-images.githubusercontent.com/33448286/48891537-49e91900-ee44-11e8-8e56-73ccc21ab930.png)

**Comment by willdurand** [comment]
Current -dev:

<img width="360" alt="screen shot 2018-11-22 at 09 54 09" src="https://user-images.githubusercontent.com/217628/48891778-9892b500-ee3c-11e8-9dde-ec2dcc7f4196.png">

Current -prod:

<img width="356" alt="screen shot 2018-11-22 at 09 54 03" src="https://user-images.githubusercontent.com/217628/48891779-9892b500-ee3c-11e8-9ce7-bd23289cbe9b.png">

**Comment by ioanarusiczki** [comment]
@willdurand Yes, I was just about to update the issue because I've noticed it. Looks like a regression.
