### ISSUE TITLE
https://addons.mozilla.org/addon/anti-paywall

### ISSUE THREAD

**Issue by joelzipolite** [mozilla/addons-frontend#7023]
### Describe the problem and steps to reproduce it:

https://addons.mozilla.org/addon/anti-paywall

### Anything else we should know?

![image](https://user-images.githubusercontent.com/45261842/48902448-960f7a00-ee93-11e8-998e-a6e1a342149b.png)

**Comment by muffinresearch** [comment]
We are unable to provide support for individual add-ons.

This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services.
