### ISSUE TITLE
Page not found when clicking the photo, music & video extensions link from Enhance Your Media Experience

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7026]
Followup for https://github.com/mozilla/addons-frontend/issues/6701

STR:
1. Load AMO dev on android and click the Enhance Your Media Experience guide
2. Scroll down the page and click on  photo, music & video extensions

Expected result:
Page redirects to https://addons-dev.allizom.org/en-US/android/extensions/photos-media/

Actual results:
Page not found

Notes:
This issue is reproducible on AMO dev with FF63(Android 8.0)

![page not found](https://user-images.githubusercontent.com/33448286/48904914-aeb66a80-ee68-11e8-8c15-4ea148f9c09a.gif)

**Comment by willdurand** [comment]
I think we need content for Android now.. Categories are different for Firefox Desktop and Firefox for Android.

**Comment by rebmullin** [comment]
Maybe we should check with UX/ Product on this. I am guessing android should use this url instead: 

https://addons-dev.allizom.org/en-US/android/extensions/photos-media/

I am not sure, do we want to change the text here too?

if we change the clientApp, then the following pages will be firefox too which I don't think we want.

@pwalm @devaneymoz @jvillalobos @atsay

**Comment by ioanarusiczki** [comment]
@willdurand @rebmullin 
I've forgot to mention that there are add-ons in the guide lines which are not displayed for android (they have only Firefox compatibility, so in this case only choosing "Add-ons for Firefox" from the filter will display them). This requires UX too, so I filed https://github.com/mozilla/addons-frontend/issues/7058

**Comment by jvillalobos** [comment]
Like in #7058, we should probably consider not showing the guide block on Android.

**Comment by pwalm** [comment]
Correct, do not show the blocks on Android

**Comment by rebmullin** [comment]
@pwalm, so we are not to show the guide blocks on the home page on android? To be clear, we should keep the original look on android then?

**Comment by willdurand** [comment]
> Correct, do not show the blocks on Android

@pwalm please read this (and below) too: https://github.com/mozilla/addons-frontend/issues/7058#issuecomment-441675815

This is not a small change, especially if we need to bring back the current home hero as @rebmullin asked.

**Comment by muffinresearch** [comment]
@rebmullin the team discussed this today at the cross functional call and we're going with not showing the blocks on android which will then not show the links to Android. Would be nice to get code-splitting happening here as soon as possible so that we're not sending the guide pages in the bundle.

@pwalm if we leave the blocks out should the heading + sub-heading remain?

**Comment by pwalm** [comment]
@muffinresearch @rebmullin Yep, those should stay.

**Comment by pwalm** [comment]
@willdurand @rebmullin I would drop the old home hero area from android, but keep the heading/sub-heading. The old hero area isn't super useful (unless anyone has data to prove otherwise?).

**Comment by rebmullin** [comment]
@pwalm, so the homepage on android will look something like this:

![Alt text](https://monosnap.com/image/h3zIjQwrRD1FJYzz20Ryl4E9uiRLBk.png)

and to recap the guide pages will no longer be accessible on android so how we handle links on the guide pages is no longer a concern?

@muffinresearch, yes, I'll follow up with @willdurand on the code splitting

**Comment by pwalm** [comment]
@rebmullin Love it. Can we add a bit more padding above the header and below the subheader? Like 10px each.
