### ISSUE TITLE
Implement an isFirefox function in compatibiliy.js

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7027]
There are a few places where we need to know if the current browser is Firefox, including (for now) the `Addon` component, the `AMInstallButton` component and the `GetFirefoxButton` component. This issue is about creating a function for this in `compatibility.js` and using it in all the appropriate places.

Note that this is work in support of #6603.

For QA:

Please check for regressions in the "Get Firefox" button and the Install button.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on AMO dev (Win10 & Android 8.0) 
No regressions found. 

- with Chrome and Edge for the "Get Firefox" button

![get firefox now](https://user-images.githubusercontent.com/33448286/48949341-5357ab80-ef40-11e8-845d-5f5e6e799707.gif)

- with FF63 unbranded for +Add to Firefox and +Install Theme 

![install buttons](https://user-images.githubusercontent.com/33448286/48950207-14772500-ef43-11e8-8bc8-0f6564a91d5f.gif)
