### ISSUE TITLE
The second add-on's install process is interrupted when clicking Install for multiple add-ons

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7028]
STR:
1. Load AMO dev and click the guidelines
2. Find an add-on that during installation will open a new tab
3. Click the add-on from 2 and then click Install for the next one displayed
4. When returning to the guide page observe the second add-on clicked 

Expected results:
Both add-ons are installed

Actual results:
The first add-on is installed but the second is not

Notes:
Reproducible on AMO dev and AMO stage in the guide lines and with disco pane too -> FF63 unbranded (Win10)
I could not reproduce this issue on Android

Guide Lines 
![the second is not installed guides](https://user-images.githubusercontent.com/33448286/48906214-73b63600-ee6c-11e8-9e37-a6db79687799.gif)

Disco Pane 
![the second is not installed](https://user-images.githubusercontent.com/33448286/48906244-84ff4280-ee6c-11e8-9667-44ede58d263f.gif)

**Comment by rebmullin** [comment]
If this exists on disco pane already, then maybe this is a known issue already..? Altho I just checked and don't see any issue for this.

Maybe tho we could disable the other addons while the addon is installing or downloading.
