### ISSUE TITLE
Remove "This add-on is not available on your platform." from an add-on visible only for admins and developers

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7036]
Followup for https://github.com/mozilla/addons-frontend/issues/6976
STR:
1. Make sure the detail page of an addon is opened in a tab (because of https://github.com/mozilla/addons-server/issues/10033)
2. As a developer disable all versions of an add-on
3. Refresh the add-ons detail page and observe the red messages 

Expected result:
Only the message about the add-on not being public is available.

Actual result:
There's also a message about the add-on not being available on the platform (which is not necessary).

Notes:
The issue is reproducible only when the add-on is disabled by the developer from dev hub with FF63 (Win10). 

![messages](https://user-images.githubusercontent.com/33448286/48934290-0a85ff80-ef0c-11e8-8b99-095667f2cbb2.png)

**Comment by bobsilverberg** [comment]
As discussed in #6976, this is pretty simple and straightforward to do, so might be a good first bug. It just involves introducing an `if` statement into `Addons/index.js` to that either the [`AddonCompatibilityError` component](https://github.com/mozilla/addons-frontend/blob/2018.11.22-1/src/amo/pages/Addon/index.js#L501) is rendered or [this notice](https://github.com/mozilla/addons-frontend/blob/2018.11.22-1/src/amo/pages/Addon/index.js#L504-L508) is rendered, but not both.

**Comment by kumar303** [comment]
Why shouldn't we show both messages? They both seem important to indicate what's happening.
