### ISSUE TITLE
Scroll position is not maintained in search results list

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7037]
STR:

1. Open AMO homepage - https://addons.mozilla.org/en-US/firefox/
2. Enter a search term, i.e. "privacy"
3. Scroll down to the bottom of the search results list and click on an add-on to view its product page
4. Go back to search results

Actual result:
The scroll position is somewhere in the middle of the page

Expected result:
The scroll position should be at the bottom of the list 

Notes:
- reproduced on all AMO servers with FF63, Win10x64

![2018-11-23_10-37-43](https://user-images.githubusercontent.com/31961530/48934360-5df84d80-ef0c-11e8-9c17-82133100d580.gif)

**Comment by xu3u4** [comment]
Browser caches the scroll position. I think it has something to do with the cache.

**Comment by willdurand** [comment]
@AlexandraMoga was it working before?

**Comment by rebmullin** [comment]
React Router 4 does not provide support for scroll restoration so I am guessing it hasn't worked since before the upgrade. See here: https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md.

**Comment by willdurand** [comment]
> React Router 4 does not provide support for scroll restoration so I am guessing it hasn't worked since before the upgrade. See here: [ReactTraining/react-router:packages/react-router-dom/docs/guides/scroll-restoration.md@`master`](https://github.com/ReactTraining/react-router/blob/master/packages/react-router-dom/docs/guides/scroll-restoration.md).

We do have a component for that: https://github.com/mozilla/addons-frontend/blob/fd2d3b73df11c6c24f6fef59d6c1a46dc00588ff/src/core/components/ScrollToTop/index.js, so I believe it was working after the RR4 upgrade. I am just not sure this particular case was working before.

**Comment by rebmullin** [comment]
ScrollToTop implies you want it to scroll back to the top of the page, no? 
The expected result here is that the scroll position should be at the bottom (i.e. maintain its scroll position)

**Comment by willdurand** [comment]
> ScrollToTop implies you want it to scroll back to the top of the page, no?
> The expected result here is that the scroll position should be at the bottom (i.e. maintain its scroll position)

Ah. Right.

I don't think we should do anything about this bug anyway, because I don't think we supported this "feature" in our code before and as pointed out above, it is likely a browser feature.

**Comment by willdurand** [comment]
Ah 😞

**Comment by willdurand** [comment]
> When I learned that chrome manages scroll position for us now, and realized that different apps are going to have different scrolling needs, I kind of lost the belief that we needed to provide something–especially when people just want to scroll to the top (which you saw is straight-forward to add to your app on your own).
>
> Based on this, we no longer feel strongly enough to do the work ourselves (like you we have limited time!). But, we’d love to help anybody who feels inclined to implement a generic solution. A solid solution could even live in the project. Hit us up if you get started on it :)

Quoted from: https://reacttraining.com/react-router/web/guides/scroll-restoration

Not sure we should do anything about that since browsers start to implement this feature.
