### ISSUE TITLE
"Server error" received when navigating back from the edit profile to the view profile page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7038]
STR:

1. Log in to AMO -dev
2. Select View my Profile from the user menu
3. Click on Edit profile button
4. Go back (using the browser back button) to the View profile page

**Actual result:**
A "Server error" page is displayed
<details>
<summary>Console error:</summary>
Caught application error: InternalError: "too much recursion"
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1223759
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1223735
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1224167
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1223735
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1224167
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1223735
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1224167
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1223735
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1224167
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1223735
	exports https://addons-amo-dev-cdn.allizom.org/amo-e34d75daaeb8896920c6.js:1:1224167
 
Object { componentStack: "\n    in t\n    in t\n    in Translate(t)\n    in Connect(Translate(t))\n    in t\n    in t\n    in withRouter(t)\n    in div\n    in t\n    in Connect(t)\n    in Translate(Connect(t))\n    in Connect(Translate(Connect(t)))\n    in t\n    in t\n    in _r\n    in t\n    in Connect(t)\n    in div\n    in div\n    in div\n    in t\n    in t\n    in withRouter(t)\n    in NestedStatus\n    in SideEffect(NestedStatus)\n    in t\n    in withCookies(t)\n    in Translate(Component)\n    in Connect(Translate(Component))\n    in t\n    in withRouter(Connect(Translate(Component)))\n    in StrictMode\n    in t\n    in t\n    in r\n    in Connect(r)\n    in a\n    in t\n    in S" }

</details>
<br>

**Expected result:**
The View profile page is displayed

Notes:
- it also happens when you navigate back to the View profile from other pages accessed from the user profile, i.e  extension or theme product page, review permalinks
- the error disappears at page refresh
- reproduced on AMO -dev with FF63, Win10x64
- probably regression from https://github.com/mozilla/addons-frontend/issues/6526

![2018-11-23_12-56-46](https://user-images.githubusercontent.com/31961530/48940187-6908a900-ef1f-11e8-8268-af4427d22e7f.gif)

**Comment by willdurand** [comment]
> probably regression from #6526

That's an issue with https://github.com/mozilla/addons-frontend/issues/6527, not with #6526.

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF63, WIn10x64 and Andorid 8.0

![2018-11-27_18-00-45](https://user-images.githubusercontent.com/31961530/49094278-92eb0400-f26e-11e8-98d6-bcac69f9a09e.gif)

**Comment by willdurand** [comment]
Awesome, thanks!
