### ISSUE TITLE
Edit profile URLs that include a "username" are loading the page without content

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7040]
Follow up for https://github.com/mozilla/addons-frontend/issues/6915

STR:

1. Log in to AMO -dev with an Admin account
2. Try to access the Edit profile page of a user by `username` i.e.  https://addons-dev.allizom.org/en-US/firefox/user/adstomper/edit/

Actual result:
The Edit profile page loads with no content. If you click on 'View user's profile', you will be redirected to this profile page: https://addons-dev.allizom.org/en-US/firefox/user/NaN/

Expected result:
The Edit profile URL should probably be redirected to the `userId` when the request includes the `username`

Notes:
- this is an edge case that is very hard to trigger unless you are an Admin and you are deliberately using the `username` instead of the `userId` in an edit profile URL
- reproduced on AMO -dev with FF63, Win10x64

![2018-11-23_15-32-39](https://user-images.githubusercontent.com/31961530/48948787-7b460f80-ef3e-11e8-942e-b748fe7b7d77.gif)

**Comment by willdurand** [comment]
This is a wontfix, because Product said we did not need this feature. It is only for admins and admins use the buttons provided by the UI. We won't perform any redirect for the edit pages.
