### ISSUE TITLE
Add-on are not compatible with Android in the new guidelines 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7058]
Followup for https://github.com/mozilla/addons-frontend/issues/6701

STR:
1. Load AMO dev with Android and click Organize your tabs or Enhance your Media Experience guides
2. Observe if all the section display add-ons

Expected result:
All the guides display add-ons with descriptions and an Install button.

Actual result:
Some sections are missing the add-on given as example. 

Notes:
This issue is reproducible on AMO dev with FF63 (Android 8.0)

Guide lines on Android 

![android display](https://user-images.githubusercontent.com/33448286/49007119-5e465200-f173-11e8-9a82-f4f5ad971f7a.png)

This is how it looks like after changing filters (from android to FF and then back to android)

![android display2](https://user-images.githubusercontent.com/33448286/49007168-80d86b00-f173-11e8-8d9c-ffcedbbf3704.png)

**Comment by willdurand** [comment]
Is this issue similar to #7044?

**Comment by rebmullin** [comment]
For now I have a fix to show the same addons with the "This add-on is not available on your platform" notice but this brings to light that *maybe* we should actually be showing different addons on android.

My initial thought would be to do this in steps since figuring out the android list might be a bit more involved. Show the notice as shown above and then discuss if separate addons should be shown for android.

**Comment by rebmullin** [comment]
@jvillalobos, can you please advise on this?

**Comment by willdurand** [comment]
I think we can also ping @devaneymoz @atsay @MeridelW

**Comment by jvillalobos** [comment]
I'd like to hear first from Scott if it's feasible to make selections that generally support Android, so the error messages on those pages are rare. I suspect that's not the case, in which case I would suggest not showing the homepage guide block on Android at all.

**Comment by jvillalobos** [comment]
From x-func meeting: let's hide the block for Android.

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with FF63 (Android 8.0)

![android layout2](https://user-images.githubusercontent.com/33448286/49805705-7797f280-fd5e-11e8-9101-669e507e210b.png)
