### ISSUE TITLE
Make addons state selectors more versatile

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7074]
**For QA**: please make sure there are no regressions to add-ons and review related features.

All `addons` state selectors like `getAddonByID`, `getAddonBySlug`, and `getAddonByGUID` accept the `AppState` type as the first parameter but they should accept the `AddonsState` type instead. This will allow the `addons` reducer and reducer test code to utilize the selectors. 

As part of this refactoring, we should fix some of the naked state access added in https://github.com/mozilla/addons-frontend/pull/7064

**Comment by ioanarusiczki** [comment]
No regressions found. 
Verified on AMO stage - FF66(Win10 & Android 8.0).
