### ISSUE TITLE
Add new route for license view

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7079]
We need a new route in nginx to route requests for the custom license to the new front-end. Here is what we need:

License page: addon/:slug/license/

This landed in #7018

This should be enabled on dev only for now, and I will update this issue when we want it turned on for stage (which will be a week next Tuesday) and prod (which will be a week next Thursday).

**Comment by bqbn** [comment]
The route is on -dev. Please test it.

**Comment by bobsilverberg** [comment]
@bqbn This went to stage yesterday and goes to prod on Thursday. I'll update the push doc for Thursday. Could you please add the route to stage when you have time?

**Comment by bqbn** [comment]
The route is now on -prod.

**Comment by ioanarusiczki** [comment]
The Custom License to the new front-end URL is https://addons.allizom.org/en-US/firefox/addon/:slug/license/
Verified on AMO dev and AMO stage with FF64(Win10)

![url for license](https://user-images.githubusercontent.com/33448286/50004647-7d851200-ffb0-11e8-841b-f0f92b2f8666.gif)
