### ISSUE TITLE
simple white compact (theme for Firefox OS/2)

### ISSUE THREAD

**Issue by babydoc** [mozilla/addons-frontend#7094]
A few days ago I downloaded and installed the theme, Simple white compact, to Firefox-45-8-0 running in OS/2 (ArcaOS), but today I cannot find it. I am trying at <https://addons.mozilla.org/en-US/firefox/complete-themes/retro>, and without the "retro." Where can I get this theme?

**Comment by jvillalobos** [comment]
Complete themes are legacy add-ons that haven't been supported in Firefox for a long time. They were recently disabled on the site, so they are no longer available. You can try contacting the theme's developer to see if they have a copy you can use.

**Comment by babydoc** [comment]
The problem that remains is that there are users of OS/2 in its original and updated versions who are stuck with Firefox-45.9.0 which uses full function themes. If anyone at GitHub is old enough maybe he or she could explain to you what OS/2 is. It would be nice if you could let us share in a

**Comment by babydoc** [comment]
The problem that remains is that there are users of OS/2 in its original and updated versions who are stuck with Firefox-45.9.0 which uses full function themes. If anyone at GitHub is old enough maybe he or she could explain to you what OS/2 is. It would be nice if you could let us share in some way with the outdated themes.

Sorry, my cat sent the message before i had finished it. He knows OS/t.
