### ISSUE TITLE
Hero area edits: homepage

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#7097]
The following are homepage edits related to this issue: https://github.com/mozilla/addons-frontend/issues/6433

- Homepage headline should read singular “browser”
- Middle homepage tile should read: “Organize Tabs & Bookmarks” 
- Add a thin, 1px stroke (with 24px of padding around it) between the bottom of the guide blocks and the top of the “Customize the way Firefox…” block.

**Comment by rebmullin** [comment]
With this title change, should the "Organize Tabs & Bookmarks" url change too?
Right now it's `guides/organize-your-tabs` but I was wondering if this should now change to: `guides/organize-tabs-and-bookmarks`? 
I am not sure if it matters too much but I was trying to match the slugs to their titles.

**Comment by atsay** [comment]
Yes, if it's not too much trouble, let's change the slug to match!

**Comment by rebmullin** [comment]
@pwalm, a follow up question on the line for the home page:

Should it span the length of the guide blocks or the "Customize the way Firefox.." block?


![Alt text](https://monosnap.com/image/Wq1jnZbGPnWXGxqv9FdtsHIZ9ZWwYc.png)

or?

![Alt text](https://monosnap.com/image/75d6ypHCo00EDkMNdt7n3sxRNsTWTo.png)

**Comment by willdurand** [comment]
I vote for (1)

**Comment by pwalm** [comment]
Same, I vote for 1 as well. Thanks for checking!
