### ISSUE TITLE
Hero area edits: "organize tabs & bookmarks" guide page

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#7099]
The following edits are for the "organize tabs & bookmarks" guide page related to this issue: https://github.com/mozilla/addons-frontend/issues/6433

- Add an additional space between the final line of the opening paragraph, “...can dramatically change the way you deal with tabs and bookmarks,” and the header that follows it: “Re-imagine tab management”. (This way we make it clear spatially what groups of content are associated.)
- Remove the hyphen in the title “Re-imagine”. It can just be “Reimagine tab management”

**Comment by rebmullin** [comment]
Initially in the mocks there was a line between the guides header and the content below. It's actually already styled but the html was inadvertently changed and so you couldn't see it. 

Just checking do we still want this line here or just the space is enough:
![Alt text](https://monosnap.com/image/4PdVWjxuLx3UILSr5zTOl3bFasAIT2.png)

@pwalm @atsay

**Comment by pwalm** [comment]
Line, please!

**Comment by ioanarusiczki** [comment]
@rebmullin 
I verified this on AMO dev with FF63(WIn10& Android 8.0). Looks good!

![tab improvements](https://user-images.githubusercontent.com/33448286/49507924-2e413200-f88a-11e8-9fbe-2bc810526b4e.png)
