### ISSUE TITLE
Hero area edits: "enhance your media experience" guide page

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#7100]
The following edits are for the "enhance your media experience" guide page related to this issue: https://github.com/mozilla/addons-frontend/issues/6433

- Swap positions of the “Improve Videos” and “Bring media right into the browser” sections (it will read better because the page intro has a similar copy cadence to the “Improve Videos” copy that currently follows it, so it’d be good to avoid redundancy of style). 
- Need an additional space between final line of opening paragraph, “...from watching videos to handling images, music, and more..”   and the header that follows it: “Improve videos”
- Change this line, “If you enjoy video content, extensions offer a number of ways to optimize your experience, from customizing YouTube to taste, to playing videos in theater mode, and much more.” to: “If you enjoy video content, extensions offer a number of ways to optimize your experience, including customizing YouTube to your taste and playing videos in theater mode.”

**Comment by ioanarusiczki** [comment]
@rebmullin I verified this on AMO dev with FF63 (Win10& Android 8.0). 

- The position for “Improve Videos” and “Bring media right into the browser” is the same as the last week when they were changed here https://github.com/mozilla/addons-frontend/issues/7048.  Are they supposed to be switched again? 

![order now](https://user-images.githubusercontent.com/33448286/49505909-65611480-f885-11e8-913e-3e43cae57b9d.png)

- there is a separator line between the general description and the first section and it looks good.
-  "If you enjoy video content, extensions offer a number of ways to optimize your experience, including customizing YouTube to your taste and playing videos in theater mode" is available.

**Comment by rebmullin** [comment]
hey @ioanarusiczki, yes the order should be fine per the info in the very first comment of this issue (it says to switch these). I know it's a little confusing since we just switched this a few weeks ago but this request came in after that change and it's basically telling us to change it back. let me know if that helps clarify:)

**Comment by ioanarusiczki** [comment]
Thanks. It's quite clear now. I'm marking this verified on AMO dev with FF63 (Win10).
