### ISSUE TITLE
Hero area edits: "Add button" on guide pages

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#7101]
The following edit is for all 3 guide pages related to this issue: https://github.com/mozilla/addons-frontend/issues/6433

Change the "+Add" buttons to say “+ Add to Firefox” to make them consistent with the universal extension card design.

**Comment by rebmullin** [comment]
I have a related question:

Last week @pwalm mentioned the color of the button should be blue. Right now they are consistent with the color that is seen on the product detail page (which is still using the ab experiment to test the 2 colors). So if you see it green on the detail page you will see it green here too.. 

Is this okay to have it match what's seen on the product detail page or do you want it to always be blue on the guides page?

@atsay

**Comment by willdurand** [comment]
It would be much simpler and likely more accurate to keep the A/B test for ALL install buttons in my opinion. This experiment won't last too long anyway.

**Comment by atsay** [comment]
Yes, makes sense to keep the A/B test on these pages for now. We'll still show the green "Only for Firefox--Get Firefox now" buttons when viewed from another browser, right?

**Comment by rebmullin** [comment]
okay great. We'll keep the colors consistent for the "+Add to Firefox" buttons.

Yes, the "Only for Firefox--Get Firefox now" button will always be green (it's outside of the ab testing).
