### ISSUE TITLE
Selenium IDE: Flow Control plugin, version 2.9.1 Disappearance

### ISSUE THREAD

**Issue by VRIronFist** [mozilla/addons-frontend#7102]
### Describe the problem and steps to reproduce it:

I'm looking for access to Dave Hunt's Selenium IDE: Flow Control plugin, version 2.9.1

### What happened?

As of today, it is no longer offered on the Firefox add-on page. It was there yesterday.

### What did you expect to happen?

It to be available for installation. I need to get a copy of it.

### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/addon/flow-control/?src=search

**Comment by wagnerand** [comment]
This is an intended consequence of the removal of legacy add-ons from AMO.

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error. In the long run they will disappear from Google search results.
