### ISSUE TITLE
Mozrepl Unable to Download

### ISSUE THREAD

**Issue by nizamgates** [mozilla/addons-frontend#7105]
The Mozrepl add-on is no longer available for download:
https://addons.mozilla.org/en-US/firefox/addon/mozrepl/

Now it only shows "Page not found"
I need it for work.
Please help...

**Comment by wagnerand** [comment]
This is an intended consequence of the removal of legacy add-ons from AMO.

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error. In the long run they will disappear from Google search results.
