### ISSUE TITLE
No se encuentra la extencion S3 Traslator

### ISSUE THREAD

**Issue by Ing-Brayan-Martinez** [mozilla/addons-frontend#7111]
No se puede instalar la extencion S3 Traslator por alguna razón la pagina no existe, la pagina de la extencion es: https://addons.mozilla.org/es/firefox/addon/s3google-translator/ y la pagina oficial es : http://www.s3blog.org/s3translator.html esta extencion es necesaria para poder traducir paginas web, esto hace que firefox sea tan productivo como chrome para traducir algo necesario para hacer que firefox sea una mejor alternativa que chrome ya en rendimiento y funcionalidad es igual o mejor solo hace falta la traduccion, esta extencion cubría la mayoria de la necesidades de traduccion, espero que les ayude

**Comment by jvillalobos** [comment]
This is an intended consequence of the removal of legacy add-ons from AMO.

All versions of this add-on were disabled because they were legacy. This causes the add-on to be considered incomplete, and that's why you're seeing the error. In the long run they will disappear from Google search results.
