### ISSUE TITLE
Run small set of integration tests on pull requests

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#7116]
Currently, the integration test job for addons-frontend circleci only runs every 3 hours or so. It would be awesome if we could just run a small set of tests on commit. I know we have unit tests, but these would also be useful to make sure everything works together. I am talking like, 10-15 tests at most.

**Comment by willdurand** [comment]
Can we run integration tests for every commit on `master` instead? That would be already something. Ideally, we should have some feedback when tests fail (and not email).

**Comment by kumar303** [comment]
If we block merging a pull request on these tests, they need to be fast. The PR build is already a bit too slow. If you are suggesting to run these post merge then speed is not so much of an issue for me.

> Currently, the integration test job for addons-frontend circleci only runs every 3 hours or so. 

Is this the scheduled circle CI job? I am a bit worried about that one because it's a little flaky. Flaky tests are easy to ignore.

**Comment by jrbenny35** [comment]
> Can we run integration tests for every commit on master instead? That would be already something. Ideally, we should have some feedback when tests fail (and not email).

That could work too. I still don't think they all need to run

> If we block merging a pull request on these tests, they need to be fast. The PR build is already a bit too slow. If you are suggesting to run these post merge then speed is not so much of an issue for me.

I guess that's fine as if there is a break it needs to be fixed on addons-server.

> Is this the scheduled circle CI job? I am a bit worried about that one because it's a little flaky. Flaky tests are easy to ignore.

Most of the times if it fails it is because something is broken. Its more reliable on addons-frontend than server because there isn't that weird git checkout Chris does over on server.

**Comment by kumar303** [comment]
> > Is this the scheduled circle CI job?
>
> Most of the times if it fails it is because something is broken.

Actually, I meant to bring up these tests which seem to fail at least once a day: https://circleci.com/gh/mozilla/addons-frontend/tree/master

**Comment by jrbenny35** [comment]
Yeah those are the ones I am talking about. Right now, theyre failing because of a search change on addons-server. _MOST_ times it is because of a -server change but when the hero got changed a few days ago, it was a frontend thing. It would be cool just to have a few tests for things like that

**Comment by willdurand** [comment]
> _MOST_ times it is because of a -server change but when the hero got changed a few days ago, it was a frontend thing.

No, that's still a mistake with the environment/config/version of addons-frontend used in this test suite 🙈

**Comment by jrbenny35** [comment]
> No, that's still a mistake with the environment/config/version of addons-frontend used in this test suite 

I am happy to fix it but idk how. If you want to hack on this next week I am down.

**Comment by willdurand** [comment]
Closing since we want to move those tests in another repo.
