### ISSUE TITLE
Change "Developer Hub" link in header to "Extension Workshop"

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#7122]
The "Developer Hub" link in the top right of the header is now outdated. The copy should read "Extension Workshop" and the link should be: < pending link to Extension Workshop >

This needs to be updated in the footer as well.

**Comment by jvillalobos** [comment]
That link leads to `/developers/`, where developers can maintain their existing add-ons. I don't think we can link to the Extension Workshop just yet. The login button on that page just takes me back to AMO if I'm already logged in.

We also discussed not actively exposing developers to it for now. @atsay and @mconca can correct me on this.
