### ISSUE TITLE
User `userId` instead of `username` in collection saga/reducer/api

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7135]
See also: #6609

---

In order to change the collection URLs to use user IDs instead of usernames, we need to change the variable names to reflect this upgrade. In this issue, we should simply rename variables and make sure Flow types and test cases are synchronized.

**For QA:** please make sure collection pages load correctly and that no feature has been altered.

**Comment by ioanarusiczki** [comment]
@willdurand I tested around collections, pages load, I could edit, delete them.  Mozilla collections also load without problems and were editable using the frontend. 
Verified with FF63 (Win10 & Android 8.0)
