### ISSUE TITLE
User `userId` instead of `username` in collection routes

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7137]
See also: #6609

---

In order to change the collection URLs to use user IDs instead of usernames, we need to change the routing parameter names to reflect this upgrade.

**For QA:** please make sure collection pages load correctly. We still don't have user IDs in the URLs, so there should be no visible difference.

**Comment by ioanarusiczki** [comment]
@willdurand I verified personal collections and the Mozilla collections from AMO homepage on AMO dev with FF63 (Win10) - no regressions found.
