### ISSUE TITLE
Re-add Bypass Paywalls for Firefox

### ISSUE THREAD

**Issue by hasjahsjahksj** [mozilla/addons-frontend#7142]
# RE-ADD EXTENSION Bypass Paywalls for Firefox

### Describe the problem and steps to reproduce it:

Extension "Bypass Paywalls for Firefox" was deleted from mozilla store.

### What happened?

Tried to install it, but it was **deleted by Mozilla**

### What did you expect to happen?

Install the extension.

### Anything else we should know?

See: https://github.com/iamadamdev/bypass-paywalls-firefox/issues/82

**Comment by julian-alarcon** [comment]
Just be more direct with the info, was not Mozilla fault, is US law

Got this from here: https://github.com/nextgens/anti-paywall/issues/109#issuecomment-441097828

"It appears that your Add-on violates the Firefox Add-on Distribution Agreement and the Conditions of Use. Both prohibit Add-ons that violate the law. Your Add-on appears to be designed and promoted to allow users to circumvent paywalls, which is illegal.

This email is to notify you that we will remove your Add-on from addons.mozilla.org one week from the date of this email. Please feel free to contact us with questions or concerns by replying to this email."

I've asked which laws...

"There are various laws in the US that prohibit tools for circumventing access controls like a paywall. Both Section 1201 of the Digital Millennium Copyright Act (DMCA) and the Computer Fraud and Abuse Act (CFAA) are examples.

We are responding to a specific complaint that named multiple paywall bypassing add-ons. It did not target only your add-on.
"

**Comment by geotheory** [comment]
@julian-alarcon Instead of bypassing paywalls is there a way for the app to merely flag them so users can make more informed decisions about whether to click?  Bonus if the flag could bubble up the site's free articles policy.  If there is no such policy users will know to avoid.
