### ISSUE TITLE
Make sure code-splitted chunks are preloaded and loaded from cache on FF

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7144]
It looks like FF does not always load the prefetched/preloaded chunks from cache when actually needed. Chrome behaves differently. We should make sure that prefetching/preloading works as intended *and* that it is actually efficient on FF (and other browsers).

**Comment by willdurand** [comment]
FF does not allow preloading but it should allow prefetching. In FF Nightly, I got it working thanks to https://github.com/mozilla/addons-frontend/issues/8620, I guess.

By browsing the homepage with cache disabled (or no cache at all), we see 4 requests and the `x-moz: prefetch` header:

![Screen Shot 2019-09-19 at 15 47 00](https://user-images.githubusercontent.com/217628/65249817-e6c42380-daf4-11e9-92d8-274eaac7aaff.png)

After that, enable the cache, clear the requests in the network panel and navigate to the About page:

![Screen Shot 2019-09-19 at 15 49 51](https://user-images.githubusercontent.com/217628/65249992-1ffc9380-daf5-11e9-91eb-9015b90ab8b9.png)

**Comment by ioanarusiczki** [comment]
@willdurand 
I followed the steps [above](https://github.com/mozilla/addons-frontend/issues/7144#issuecomment-533139632) and got the same results on AMO Dev with FF69(Win10). 

![Works for me](https://user-images.githubusercontent.com/33448286/65604131-9430ae80-dfaf-11e9-9d9e-679b847b3bae.gif)
