### ISSUE TITLE
Implement an AddonVersionCard

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7159]
This supports #2770 

Implement an `AddonVersionCard` which will be used by the All Versions Page to render each version.

**Comment by willdurand** [comment]
@bobsilverberg could you add some instructions for QA?

**Comment by bobsilverberg** [comment]
> @bobsilverberg could you add some instructions for QA?

This is actually QA: not needed because this component won't be used until the `AddonVersions` component is also created. I'll update the issue.
