### ISSUE TITLE
Remove `username` field in `UserProfileEdit` page/component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7166]
We want to get rid of the `username` attribute on AMO, hence we should not display the input field for this attribute and remove the code related to it (so that we don't send `username` to the API anymore).

**For QA:** please make sure we can update user profiles and `username` is not displayed/editable.

**Comment by prateek76** [comment]
@wagnerand i want to work on this issue

**Comment by willdurand** [comment]
> @wagnerand i want to work on this issue

@prateek76 sorry, but this is not a bug opened for contributors.

**Comment by willdurand** [comment]
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by ioanarusiczki** [comment]
I verified this issue on AMO dev - FF64(Win10). 
- username is no longer available in the edit form.
- other fields can be updated.

![username no longer available](https://user-images.githubusercontent.com/33448286/50763737-505b1500-1279-11e9-8a14-10cb15a3315a.png)
