### ISSUE TITLE
не могу найти нужное расширение

### ISSUE THREAD

**Issue by volk3772** [mozilla/addons-frontend#7184]
помогите пожалуйста найти расширение для firefox mobile чтобы можно было открыть консоль на телефоне как в браузере на компьютере (ctrl+shift+i)

**Comment by muffinresearch** [comment]
This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services. If you think this issue has been closed erroneously please re-open the issue and provide as much information as possible so that we can assist you.
