### ISSUE TITLE
The theme names in disco pane should match the name in the Appearance page

### ISSUE THREAD

**Issue by SylviaOr** [mozilla/addons-frontend#719]
Firefox Developer Edition 49.0a2
OS X Yosemite 10.10.5

## STR
1. Navigate to: about:addons
2. Install theme by switching ON the installation switch
3. Click on the left side “Appearance” section

## Expected results:
After installing theme in the Appearance page there should be information that theme is in use.
It should display the name of theme in use.

## Current result:
There is error  “<script> alert('Problem1')</script>VISIBLE ”information about installed theme on Appearance page.
![falaaa](https://cloud.githubusercontent.com/assets/20317898/16626893/27345bc2-43ab-11e6-9620-3586ae059344.png)
![falaa](https://cloud.githubusercontent.com/assets/20317898/16626916/400f6178-43ab-11e6-8357-3a5ad9a43b0f.png)

**Comment by muffinresearch** [comment]
This was testing data added by @krupa on stage. See https://github.com/mozilla/addons-frontend/issues/674
