### ISSUE TITLE
`yarn amo` no longer works - no styles/JS

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7196]
### Describe the problem and steps to reproduce it:

* Go into `addons-server` and start up the container with `docker-compose up -d`
* Go back to `addons-frontend` and run `yarn amo` to develop with a local Docker image. This is [documented](https://github.com/mozilla/addons-frontend/#running-amo-for-local-development) as the preferred way to start a server yet no one uses it in practice.

### What happened?

The server starts but no styles or JS loads so the app is not usable.

### What did you expect to happen?

The site should be usable.

### Anything else we should know?

I think the culprit might be related to how the `addons-server` Docker container boots its own [frontend instance](https://github.com/mozilla/addons-server/blob/ab20a15d02a566102cf9202a14ada6aab6130ae7/docker-compose.yml#L84-L96) on the same port as what `addons-frontend` uses. There is an additional problem where the `addons-frontend` startup script does not report a failure about how it cannot bind to the port.

**Comment by jrbenny35** [comment]
We could move that to the ```docker-compose.selenium.yml``` file. That config is mainly used for testing anyways.

**Comment by kumar303** [comment]
That sounds like it would solve it

**Comment by EnTeQuAk** [comment]
addons-server now actually defaults to the new frontend by default so it's used for development kinda as well. Happy to change configs though to resolve any conflicts we may have.
