### ISSUE TITLE
The number of reviews by star does not match the count

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7200]
### Describe the problem and steps to reproduce it:

* After https://github.com/mozilla/addons-frontend/issues/5923 lands, go to an add-on detail page
* Click on one of the star rating counts in the star breakdown 
  * For example, go to Version Test (https://addons-dev.allizom.org/en-US/firefox/addon/versiontest/?src=featured) and click the number 1 which is the count of one star reviews.

### What happened?

You see *No reviews*

<img width="993" alt="screenshot 2018-12-11 16 17 12" src="https://user-images.githubusercontent.com/55398/49834380-d874fa00-fd61-11e8-8af2-166f4a7ac1c0.png">

### What did you expect to happen?

I'm not totally sure yet

### Anything else we should know?

There really *is* one single rating with the score of one for this add-on but there are zero written reviews. The page is doing the right thing but it's confusing. We need to somehow indicate that ratings without text are hidden.

**Comment by kumar303** [comment]
I have some ideas for how to fix this and still keep the all-rating counts.

**Comment by kumar303** [comment]
@bobsilverberg (et al) what do you think?

<details>
<summary>One big complicated notice</summary>

<img width="994" alt="screenshot 2018-12-11 16 12 41" src="https://user-images.githubusercontent.com/55398/49834455-0b1ef280-fd62-11e8-9165-c29092709809.png">
<img width="995" alt="screenshot 2018-12-11 16 13 18" src="https://user-images.githubusercontent.com/55398/49834457-0b1ef280-fd62-11e8-9937-f9845f3ffaf4.png">


</details>


<details>
<summary>Double notices</summary>

<img width="993" alt="screenshot 2018-12-11 16 14 10" src="https://user-images.githubusercontent.com/55398/49834516-2d187500-fd62-11e8-9298-7d2704c85c36.png">
<img width="993" alt="screenshot 2018-12-11 16 14 36" src="https://user-images.githubusercontent.com/55398/49834517-2d187500-fd62-11e8-9ed2-e05553a5f67a.png">


</details>


<details>
<summary>Dropdown menu navigation plus a notice</summary>

<img width="994" alt="screenshot 2018-12-11 16 25 24" src="https://user-images.githubusercontent.com/55398/49834542-415c7200-fd62-11e8-984b-666095fd1a30.png">
<img width="994" alt="screenshot 2018-12-11 16 25 59" src="https://user-images.githubusercontent.com/55398/49834543-415c7200-fd62-11e8-85a1-d9b04746b386.png">
<img width="993" alt="screenshot 2018-12-11 16 27 16" src="https://user-images.githubusercontent.com/55398/49834545-415c7200-fd62-11e8-9ed0-6c95c4a775d8.png">


</details>

**Comment by pwalm** [comment]
Can we do "one big complicated notice" with a drop down in it?
![add-ons - 2018-12-11 14 59 11](https://user-images.githubusercontent.com/6797635/49835993-eb81cd00-fd55-11e8-9b93-9c51257dc4d2.jpg)

**Comment by kumar303** [comment]
What would the notice say exactly? In the screen your referenced from above, the notice says you are only viewing reviews with three stars, etc. Would we still need to say that if there's a dropdown in it?

Also, @MeridelW, maybe you have some thoughts here?

**Comment by kumar303** [comment]
Here is a combination of a notice and dropdown navigation.

<details>
  <summary>Screenshots</summary>

<img width="992" alt="screenshot 2018-12-12 10 15 08" src="https://user-images.githubusercontent.com/55398/49882841-0b1d0200-fdf7-11e8-8dd6-496b0d2d9394.png">
<img width="991" alt="screenshot 2018-12-12 10 15 36" src="https://user-images.githubusercontent.com/55398/49882842-0b1d0200-fdf7-11e8-9eef-a157474e1376.png">
<img width="992" alt="screenshot 2018-12-12 10 16 02" src="https://user-images.githubusercontent.com/55398/49882843-0b1d0200-fdf7-11e8-8e05-13826f0f0484.png">


</details>

**Comment by bobsilverberg** [comment]
I like those last versions. A question: will the "Ratings without a written review are hidden" message always be displayed, or only when there are more ratings than reviews?

**Comment by kumar303** [comment]
At first I was thinking to only show it when more ratings than reviews exist but maybe it makes sense to always show it for consistency.

**Comment by ioanarusiczki** [comment]
Another example: when the left side of the screen displays a number of reviews (10) in this case and on the right there are only 6 written reviews (4 are only ratings).

![another example](https://user-images.githubusercontent.com/33448286/49884155-e51a5080-fe3c-11e8-848c-dd1859244172.png)

**Comment by pwalm** [comment]
The message should say "Only showing [#]-star reviews" and the drop down options should be:
- Show all reviews
- Show only five-star reviews
- Show only four-star reviews
- Show only three-star reviews
- Show only two-star reviews
- Show only one-star reviews

To counter the disparity in numbers between ratings and written reviews, should we always say "written reviews" instead of just "reviews" @MeridelW?

**Comment by kumar303** [comment]
After discussing this in the UX meeting, we decided that showing rating-only cards should clarify what's happening. Nothing will be hidden and we won't need to make a strong distinction between ratings and reviews.

<details>
<summary>Example</summary>

<img width="918" alt="screenshot 2018-12-12 11 53 13" src="https://user-images.githubusercontent.com/55398/49888411-8fc24d00-fe04-11e8-8c46-10a4a516914c.png">


</details>

**Comment by kumar303** [comment]
I think using a select box for navigation will still be helpful but for different reasons so I filed it separately: https://github.com/mozilla/addons-frontend/issues/7212
