### ISSUE TITLE
When navigating through reviews filtered by rating stars, the reviews page will always list the results for the link opened first

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7206]
Follow up for #5923

**STR:**

1. Open AMO stage
2. Go to an add-on details page - see https://addons.allizom.org/en-US/firefox/addon/tab-mix-plus/
3. Click on a rating link from the breakdown card to see the reviews for a specific score, i.e 1 star
4. Go back to the add-on details page
5. Click on another rating from the breakdown card, i.e 5 stars

**Actual results:**
The reviews for the previously visited rating score are listed on the reviews page

**Expected result:**
The reviews for the newly selected score are listed on the reviews page

**Notes:**
- only reproduced when the navigation starts from the add-on details page
- the correct reviews are listed after the page is refreshed
- reproduced on -dev and stage with FF63, Win10x64

![2018-12-12_16-20-17](https://user-images.githubusercontent.com/31961530/49877344-e2642f00-fe2d-11e8-9705-359fcd0919f0.gif)

**Comment by kumar303** [comment]
Well, huh. I designed this feature wrong from the get-go. I looked into it today but I don't think I'll have time to fix it before leaving on PTO. The fix is to add a `score` dimension to the reducer so that loading / fetching reviews always takes that into account.

Here is a patch for myself to remember when I'm back:

<details>
<summary>Patch</summary>

```diff
diff --git a/src/amo/pages/AddonReviewList/index.js b/src/amo/pages/AddonReviewList/index.js
index 596258817..2f1cc45e2 100644
--- a/src/amo/pages/AddonReviewList/index.js
+++ b/src/amo/pages/AddonReviewList/index.js
@@ -379,6 +379,7 @@ export function mapStateToProps(
 ): $Shape<InternalProps> {
   const { addonSlug } = ownProps.match.params;
   const addon = getAddonBySlug(state, addonSlug);
+  // TODO: create a state key with addonSlug + score
   const reviewData = state.reviews.byAddon[addonSlug];
 
   const siteUser = getCurrentUser(state.users);
@@ -399,6 +400,7 @@ export function mapStateToProps(
   return {
     addon,
     addonIsLoading: isAddonLoading(state, addonSlug),
+    // Add score to this
     areReviewsLoading: reviewsAreLoading(state, addonSlug),
     checkingIfSiteUserCanReply,
     clientApp: state.api.clientApp,
diff --git a/src/amo/reducers/reviews.js b/src/amo/reducers/reviews.js
index 675fffbc9..1b2356adc 100644
--- a/src/amo/reducers/reviews.js
+++ b/src/amo/reducers/reviews.js
@@ -145,6 +145,7 @@ export type ReviewsState = {|
   // Short-lived messages about reviews.
   flashMessage?: FlashMessageType,
   loadingForSlug: {
+    // Add score to this key
     [slug: string]: boolean,
   },
 |};
@@ -380,6 +381,7 @@ export const reviewsAreLoading = (
   state: AppState,
   addonSlug: string,
 ): boolean => {
+  // Add score to this key
   return Boolean(state.reviews.loadingForSlug[addonSlug]);
 };
 
@@ -567,6 +569,7 @@ export default function reviewsReducer(
         ...state,
         loadingForSlug: {
           ...state.loadingForSlug,
+          // Add score to this key
           [addonSlug]: true,
         },
       };
@@ -582,6 +585,7 @@ export default function reviewsReducer(
         byId: storeReviewObjects({ state, reviews }),
         byAddon: {
           ...state.byAddon,
+          // Add score to this key
           [payload.addonSlug]: {
             pageSize: payload.pageSize,
             reviewCount: payload.reviewCount,
@@ -590,6 +594,7 @@ export default function reviewsReducer(
         },
         loadingForSlug: {
           ...state.loadingForSlug,
+          // Add score to this key
           [payload.addonSlug]: false,
         },
       };
diff --git a/src/amo/sagas/reviews.js b/src/amo/sagas/reviews.js
index 45741a99b..2fd1eb1c6 100644
--- a/src/amo/sagas/reviews.js
+++ b/src/amo/sagas/reviews.js
@@ -102,6 +102,7 @@ function* fetchReviews({
     const response: GetReviewsApiResponse = yield call(getReviews, params);
 
     yield put(
+      // Add score to this
       setAddonReviews({
         addonSlug,
         pageSize: response.page_size,

```

</details>

**Comment by ioanarusiczki** [comment]
This is also reproducible when "Read All reviews" is clicked, or from search results (if previously the rating numbers were clicked for an add-on).  In both scenarios the page must be refreshed as a workaround. - tested with FF64 (Win10)

![reproducible with read all reviews](https://user-images.githubusercontent.com/33448286/50088846-d224c900-020c-11e9-9423-fe7e5df6c3e4.gif)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF64, Win10x64

![2019-01-14_15-37-34](https://user-images.githubusercontent.com/31961530/51116304-6b96c900-1813-11e9-8022-93e444e99111.gif)
