### ISSUE TITLE
Add support for OpenSearch

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/addons-frontend#7207]
This replaces https://github.com/mozilla/addons-server/issues/10072

I think this should be fairly easy and helpful to some users.

tldr; add something along the lines of

```html

        <link title="Firefox Add-ons"
          rel="search" type="application/opensearchdescription+xml"
          href="/en-US/firefox/opensearch.xml" />
```

Linking to https://addons.mozilla.org/en-US/firefox/opensearch.xml or provide our own opensearch.xml on addons-frontend.

**Comment by muffinresearch** [comment]
Duplicate of https://github.com/mozilla/addons-frontend/issues/3836

**Comment by EnTeQuAk** [comment]
Oops, shame on me :see_no_evil:
