### ISSUE TITLE
A glitch is visible when returning to "About" and "Review Guide" pages 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7208]
Followup for https://github.com/mozilla/addons-frontend/issues/3734

STR:
1. Load AMO dev and navigate to About or Review Guide pages
2. Click a link on that page
3. Click back and observe the screen

Expected result:
Page is displayed without display issues.

Actual result:
For a moment a glitch is visible.

Notes:
- With FF63 when the links from the content of the pages are clicked and then the user navigates back there's a glitch every time (but not when links from the footer or the FF logo is clicked) This glitch is not present on stage or prod.
- with Chrome the glitch is reproducible clicking any link (including those from the footer of the page) and it's more obvious.
- the FF and Chrome issue I mentioned is intermittent with Edge (it works quite well).
- the glitch is also reproducible on Android (I verified it with FF and Chrome and it's more obvious with Chrome)

![glitch2](https://user-images.githubusercontent.com/33448286/49879353-789a5400-fe32-11e8-80a1-1d3a6ede95e4.gif)

**Comment by willdurand** [comment]
I think this is fixed in Nightly.

**Comment by ioanarusiczki** [comment]
@willdurand This is no longer reproducible on FF69 or FF71 - tested on all AMO servers.

![no glitch ](https://user-images.githubusercontent.com/33448286/65520599-81a37000-def0-11e9-9f4d-b28e3e3b82f7.gif)

**Comment by willdurand** [comment]
awesome!
