### ISSUE TITLE
Fix addon's guid on guides page

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#7222]

**Comment by bobsilverberg** [comment]
@rebmullin There should be a description for this issue describing the problem.

**Comment by ioanarusiczki** [comment]
Verified on AMO prod with FF64 (Win10)

![ublock](https://user-images.githubusercontent.com/33448286/50005649-c2f70e80-ffb3-11e8-9652-315a1c1d0e75.gif)
