### ISSUE TITLE
Firefox add-on S3Translator not found in addon library

### ISSUE THREAD

**Issue by petitlou60** [mozilla/addons-frontend#7228]
Hello,
I use firefox add-on S3Translator release 6.19
and now URL link is invalid

https://addons.mozilla.org/addon/s3google-translator/

Is it possible to contact author at

http://www.s3blog.org/
to solve this link problem

I know he as renamed this extension from s3google-translator to s3translator
but when making this change on addons URL does not solve problem
whe have page not found message

**Comment by wagnerand** [comment]
Please get in touch with the author of the add-on so they can update the link.
