### ISSUE TITLE
Developer profile page is shown if developer has no public add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#7229]
### Describe the problem and steps to reproduce it:

We only show user profile pages if that user is an add-on developer. However, if that developer has no public add-ons, there is probably no reason to show that page, since it's "empty".

### What happened?

Developer profile page shown for developer with no public add-ons.

### What did you expect to happen?

Tbd. Maybe same like a non-developer user? At the very least, remove the `Add-ons developer` badge.

### Anything else we should know?

Example: https://addons.mozilla.org/en-US/firefox/user/14411083/

![amo](https://user-images.githubusercontent.com/873258/50005449-a5717700-ffaa-11e8-946c-e11328a95b72.png)

**Comment by AlexandraMoga** [comment]
@wagnerand probably you are seeing the page because you are an admin user?
I've tried with my prod account but I see a Page not found

**Comment by wagnerand** [comment]
Ah, you're right, thank you! Closing.
