### ISSUE TITLE
AMO loads error page during addon installation

### ISSUE THREAD

**Issue by Grossdm** [mozilla/addons-frontend#7237]
### What happened?
I arrived at some error page on AMO, which prompted me to file an issue.

### What did you expect to happen?
I expected AMO to remain on the page of the addon that I wanted to install.

### Anything else we should know?
This occurs when I tap the install button before the addon's page has finished loading. Interestingly, the addon does still download and install.

**Comment by kumar303** [comment]
Thanks for reporting the bug. There is probably something we can do in the UI to make it clear that the install button doesn't need to be tapped a second time.

**Comment by Grossdm** [comment]
Hmm...
I don't recall stating that I tapped the install button more than once.

**Comment by SeanPrashad** [comment]
Hey @Grossdm - does this happen for any addon? I'd like to try and recreate it so when the devs get back from holidays, they'll have more information to investigate with!

**Comment by AlexandraMoga** [comment]
I've also tried to reproduce this scenario with several add-ons, but I didn't land on an error page.
Maybe some more information with regards to the used environment  (i.e. platform, Firefox version) would be helpful.

**Comment by willdurand** [comment]
Hi @Grossdm, could you maybe share more information with us? Otherwise, I am not sure what we can do about your issue :/

**Comment by muffinresearch** [comment]
Closing this since without further info there's not a lot we can do. Please feel free to re-open this if you have further information.
