### ISSUE TITLE
Disabling "Awesome Screenshot Plus" from details page will close the Disco Pane

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#724]
Prerequisites:
FF beta 5
Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0

Steps to reproduce:
1.Set your disco pane to production following the steps from https://mana.mozilla.org/wiki/display/SVCOPS/AMO+Dev+Resources#AMODevResources-TestingDiscopaneinProd
2.Start disco pane and install "Awesome Screenshot Plus"
3.Go to Extensions tab and press "More" link for previously installed addon
4.Press Disable or Remove buttons from the bottom of "Awesome Screenshot Plus" details page

Expected results:
Addons is disabled\removed

Actual results:
Entire Disco pane is closed

NOTES:
Not reproducible with another addons 

Please see video for this bug:
![awesome](https://cloud.githubusercontent.com/assets/1583842/16654445/8708500e-445e-11e6-860e-18d2502792b9.gif)

**Comment by muffinresearch** [comment]
This needs looking into to see if it's a bug in FF or a bug in the add-on itself.

**Comment by wagnerand** [comment]
This looks like a bug in Firefox. Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1285493
