### ISSUE TITLE
Pass prefixed guid in utm_content for return to AMO

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#7240]
In order to facilitate a kill switch for "Return to AMO" (see https://github.com/mozilla/addons-server/issues/10228) we need to pass a prefixed and encoded version of the guid to the download page.

The suggested format is `rta:base64(extension_id)` we just need to make sure that the server-side implementation is using the same.

The original patch for this was [here](https://github.com/mozilla/addons-frontend/pull/6167/files) which should show the relevant parts of the code to modify.

**Comment by muffinresearch** [comment]
We're going to aim to get this fixed and ready to be released on Tuesday 18th assuming we can get ops support for an OOB release.

**Comment by diox** [comment]
Small caveat on the format: please use the so-called [`base64url` format described in RFC 4648](https://tools.ietf.org/html/rfc4648#section-5) instead of standard base64: it substitutes `-` instead of `+` and `_` instead of `/` in the standard base64. You should also omit any trailing slashes to avoid query parameter confusion (our implementation on the server will handle that, it's built-in in django since it's quite a common problem).

**Comment by bobsilverberg** [comment]
FYI, here's what a link from a "Get Firefox" button would look like with this patch:

`https://www.mozilla.org/firefox/new/?utm_source=addons.mozilla.org&utm_medium=referral&utm_campaign=non-fx-button&utm_content=rta%3AezJlNWZmOGM4LTMyZmUtNDZkMC05ZmM4LTZiODk4NjYyMWYzY30`

**Comment by AlexandraMoga** [comment]
I've used the 'Get Firefox' button on AMO sstage form an add-on product page and from the Guides pages, and the links seem to function and look as expected:
1.  https://www.mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=rta%3AezQ0NjkwMGU0LTcxYzItNDE5Zi1hNmE3LWRmOWMwOTFlMjY4Yn0&utm_medium=referral&utm_source=addons.mozilla.org - Bitwarden
2. https://www.mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=rta%3Ae2RjNTcyMzAxLTc2MTktNDk4Yy1hNTdkLTM5MTQzMTkxYjMxOH0&utm_medium=referral&utm_source=addons.mozilla.org - Tab mix plus
3. https://www.mozilla.org/en-US/firefox/new/?utm_campaign=non-fx-button&utm_content=rta%3Ae2JkZmNjZjM4LTBmMzgtNGM0YS04NzBjLTM3NzA2YjFmYTZiOX0&utm_medium=referral&utm_source=addons.mozilla.org -  a static theme

I would also like to test the "Get Firefox" button that will be present in the All versions page, once hey will be available on the new frontend.
@bobsilverberg is #2770 not testable yet?

**Comment by bobsilverberg** [comment]
> @bobsilverberg is #2770 not testable yet?

The code has landed, but the route has not been implemented on dev yet. That's been requested in #7244, but I'm not sure when that will be actioned.

**Comment by bobsilverberg** [comment]
@willdurand In https://github.com/mozilla/addons-frontend/issues/7240#issuecomment-447822245, @muffinresearch said we want to release this on the 18th, but I'm not sure why it couldn't be done on the 10th. 

@muffinresearch What do you think the milestone should be for this?

**Comment by muffinresearch** [comment]
It got deferred until today (7th Jan). We're planning to push this imminently. I've put it in the 10 milestone since that's the closest one and will do from the point of view of discussing the change.

**Comment by AlexandraMoga** [comment]
Verified fixed also with the "Get Firefox" button from the All version page.
