### ISSUE TITLE
Add new route for All Versions page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7244]
We need a new route in nginx to route requests for the All Versions page to the new front-end. Here is what we need:

All Versions page: addon/:slug/versions/

This landed in #7230 

This should be enabled on dev only for now, and I will update this issue when we want it turned on for stage (which will be the Tuesday before the next push: January 8th) and prod (which will be the next push: January 10th).

**Comment by willdurand** [comment]
The rule has been added to -dev.

**Comment by willdurand** [comment]
@autrilla or @bqbn can we deploy the rule in stage now too? Thanks!

**Comment by willdurand** [comment]
Deployed to stage!

**Comment by willdurand** [comment]
Closing this issue as it will be deployed to prod tomorrow! (deployed in dev and stage already)

**Comment by ioanarusiczki** [comment]
Verified on AMO Stage - FF64 (Win10). 
The rest of the verification and issues were mentioned here https://github.com/mozilla/addons-frontend/issues/2770
