### ISSUE TITLE
Fix inconsistencies between the All Versions page and the mocks

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7245]
From @kumar303 at https://github.com/mozilla/addons-frontend/pull/7230#issuecomment-447394672:

I see differences when comparing your screen to the mock: https://mozilla.invisionapp.com/share/YCCYEOFRH#/screens/310799532 

If these were not intentional, they can be addressed in follow-up issues.
- I don't see the *Be careful with old versions* warning.
- The version title should be blue (I guess it's meant to be a permalink?)
- The date / size subtext should be in gray (e.g. *Released Feb 22, 2018 - 24.35 KB*)
- The *Source code released under* text should be gray and smaller
- The *Latest version* and *Older versions* look a bit bigger in the mock but I didn't measure
- Unlike the mock, I see that you put each version in one of our standard cards (i.e. with a row gap between each one). I think that's fine for consistency but it makes it hard to see where the *Latest version* section ends and the *Older versions* section begins. I don't have a good solution to offer and it's just a minor nit so no biggie.

**Comment by bobsilverberg** [comment]
Another follow-up, which probably makes sense to do at the same time, from @kumar303 at https://github.com/mozilla/addons-frontend/pull/7230#issuecomment-447408781: 

I think it would be nicer on mobile if all the informational text (release date, size, release notes) filled the full width. Right now it only fills about 50%:

<img width="323" alt="screenshot 2018-12-14 12 15 38" src="https://user-images.githubusercontent.com/55398/50019955-19efea00-ff9a-11e8-9300-5996516b8fac.png">

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
The above inconsistencies were fixed (some already verified in other opened issues) on AMO dev and AMO stage - FF64 (Win10 & Android 8.0) 

 - the version title is blue but not a permalink
- there was a separator line between versions - no longer available but the titles are bigger and I think it's quite noticeable for the user

Before the improvements 

![before the fix versions](https://user-images.githubusercontent.com/33448286/51258702-3f19b300-19b3-11e9-9968-32a61678e7cb.png)

Now - AMO stage

![after the ux fixes](https://user-images.githubusercontent.com/33448286/51258724-4c36a200-19b3-11e9-816d-3a6032c48f9b.png)
