### ISSUE TITLE
The door-hanger is not dismissed after uninstall

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#725]
Steps to reproduce: 
1.Install an add-on from about:addons by clicking the green radio button using FF48b5 against AMO-prod (ie. Adblock Plus)
3. Click the radio button again to uninstall and observe the door-hanger

Expected results:
The door-hanger is dismissed.

Actual results:
The door-hanger is not dismissed.

Notes/Issues:
Verified on FF48b5 on Windows 7 X64 and Mac OS x10.8.
Screenshot for this issue: 
![dissmisssss](https://cloud.githubusercontent.com/assets/15685960/16654538/f6c5fc02-445e-11e6-8a42-6b911af0ae6f.png)

**Comment by muffinresearch** [comment]
Before we do this we'd need to know - can the UiTour do this in the future. @mstriemer do you know if it's possible to dismiss the showInfo hanger in the uitour?

Also should we do this for any other interactions, or only when un-installing the add-on that's related to the notification?

**Comment by mstriemer** [comment]
The UITour doorhanger can be closed with:

```js
document.dispatchEvent(new CustomEvent('mozUITour', {
    bubbles: true,
    detail: {
      action: 'hideInfo',
      data: {},  // This is required.
    }
}));

**Comment by muffinresearch** [comment]
@maritz any thoughts on the criteria for dismissing this based on other interactions. Right now this also matches the theme toolbar which is similarly not dismissed without the user closing it.

**Comment by muffinresearch** [comment]
See also https://github.com/mozilla/addons-frontend/issues/697

**Comment by maritz** [comment]
Hm, maybe turn it into a different door hanger that says "yey, uninstalled" instead of "yey, installed". That way the doorhanger didn't just vanish for the user but it also clearly conveys the real state. Would need some kind of visual indication that it changed though?!

Side suggestion: I don't think I'm the person you actually wanted to @ mention here. Maybe ask someone who actually knows what they are talking about. ;-)

**Comment by muffinresearch** [comment]
@maritz sorry about that @designakt was who I meant to notify (this is a downside of having irc nicks !== github usernames)

**Comment by designakt** [comment]
Removing the confirmation if the add-on in uninstalled again seams like the right thing to do.
I also think the confirmation should be dismissed by clicking anywhere like most door-hangers. (Which would solve the uninstall removal-problem as well.)

**Comment by muffinresearch** [comment]
Ok, sounds like we can make this work for the UITour as well.

**Comment by ValentinaPC** [comment]
The initial type of dorhanger is no longer displayed (intended), but the one that is, is dismissed while clicking outside.
Verified on about:addons FF55(Win 7).
Postfix video:
![doorhanger](https://cloud.githubusercontent.com/assets/15685960/25943707/75355d08-3649-11e7-9eb0-c70e00f8e57c.gif)

**Comment by muffinresearch** [comment]
@ValentinaPC fwiw: this should also be working when it's not nightly and uses the old dialogue.

**Comment by ValentinaPC** [comment]
Yes, you are right!
Postfix video for FF53 and the old dorhanger:
![door](https://cloud.githubusercontent.com/assets/15685960/25949676/fc54bb8c-3660-11e7-8411-19de08dacb27.gif)
