### ISSUE TITLE
404 on link to mail-merge plugin

### ISSUE THREAD

**Issue by fspade** [mozilla/addons-frontend#7250]
### Describe the problem and steps to reproduce it:
Go here:
https://addons.thunderbird.net/en-US/thunderbird/addon/mail-merge/
an click on "Add-on home page" which has this URL:
https://addons.mozilla.org/addon/mail-merge/

### What happened?
which is not found.
### What did you expect to happen?
To be led to:
https://addons.thunderbird.net/de/thunderbird/addon/mail-merge/
### Anything else we should know?
Keep up the good work.

**Comment by jvillalobos** [comment]
That's something that the developer of that extension needs to fix in its page. This repository is for bugs in the Firefox add-ons website.
