### ISSUE TITLE
Specified version of Node in .nvmrc is incorrect

### ISSUE THREAD

**Issue by SeanPrashad** [mozilla/addons-frontend#7254]
#### STR:

1. `Cd` into the `addons-frontend` repository
2. In a shell, run `nvm use`
3. Next, run `yarn` in the same shell
4. Observe the error message from `yarn`

Recently I found that the nvm docs had a section for [automatically switching node versions if a `.nvmrc` file existed in the current shell directory](https://github.com/creationix/nvm#zsh) for [zsh](https://github.com/robbyrussell/oh-my-zsh).

After successfully setting that up, I noticed that the version for this project found in `.nvmrc` is still `6` when `yarn` requires `>= 8.10`.

See below for more details:

<img width="1034" alt="screen shot 2018-12-18 at 9 28 17 pm" src="https://user-images.githubusercontent.com/13009507/50195774-80646780-030e-11e9-9479-a0f4858150d9.png">

### What happened?

`yarn` was unable to install dependencies for this project.

### What did you expect to happen?

All dependencies would be installed, if necessary.

### Anything else we should know?

This should be reproducible on Mac, Windows, and Linux if [nvm](https://github.com/creationix/nvm) is installed.

As per the docs found [here](https://github.com/mozilla/addons-frontend#requirements), the requirements state that users must have `Node 8.x which is the current LTS`. Let's also update that to say something like `Node 8.10`!

**Comment by SeanPrashad** [comment]
[This](https://github.com/creationix/nvm/issues/995#issuecomment-349670827) comment has a command that would help us update the correct version inside `.nvmrc` without having to guess at all 😀:

```shell
node -v > .nvmrc
```

It would make sense to checkout the correct version of node (`nvm use 8.11.3`) then run the above command which should update `.nvmrc`'s contents to be `v8.11.3`!

**Comment by SeanPrashad** [comment]
I'd like to help a friend land this as his first ever OSS patch if that's cool 😌

**Comment by rebmullin** [comment]
I never noticed this `.nvmrc` file:)

**Comment by rebmullin** [comment]
I think we want to keep the same format that we already see:
- 8.x in the docs (to match the release names [here](https://github.com/nodejs/Release#release-schedule): 
- 8 in the `.nvmrc` file. 

We are not on 10 yet but it seems like we should do that soon!

@willdurand @kumar303  - what do you think?

**Comment by SeanPrashad** [comment]
Version 8 LTS seems to be the way to go - there are new funky stuff in 10 that will require upgrading and it looks like the [team already has plans for Q1 of 2019](https://addons-pm.herokuapp.com/2019/Q1/)!
