### ISSUE TITLE
Dead link- Session Manager

### ISSUE THREAD

**Issue by Vyxenne** [mozilla/addons-frontend#7264]
### What happened?
Clicked "Session Manager" link at https://support.mozilla.org/en-US/questions/1020790, got page full of nothing, "Sorry, there's nothing at the page you specified."

### What did you expect to happen?
I expected to get a downloadable extension called Session Manager

### Anything else we should know?
I just want a way to selectively restore a 10-tab previous session.

**Comment by jvillalobos** [comment]
It looks like that add-on isn't being maintained anymore. You can find [numerous other session managers](https://addons.mozilla.org/firefox/search/?q=session&type=extension) on our site.
