### ISSUE TITLE
Typo in `HostPermissions` in spelling of `webextension`

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-frontend#7265]
Typo in spelling of `webextension` in `HostPermission` and `src/amo/components/PermissionsCard/permissions.js` . Spelling should be `webextension` instead of `webextention` in comments

**Comment by jayantsudo24** [comment]
Hello, I want to be get assigned for this.

**Comment by rebmullin** [comment]
hey @jayantsudo24, I think this one already has a pull request. Maybe you can look at something else if you're interested. You can get started with a [contrib: good first bug](https://github.com/mozilla/addons-frontend/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22contrib%3A+good+first+bug%22) if this is your first time or [contrib: welcome bugs](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome).
