### ISSUE TITLE
Scrollbar incorect positioning in RTL

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#727]
**steps to reproduce:**
1. Open about:addons  in FF48b5 (a RTL build) and observe the scroll bar

**Expected results:**
The scroll bar has no layout issues.

**Actual results:**
The scroll bar has a white padding near it.

**Notes/Issues:**
Verified in FF48b5
Screenshot for this issue:
![rtlscrollbar](https://cloud.githubusercontent.com/assets/15685441/16656826/cda9ac88-4468-11e6-8619-404f86d3ba42.png)

**Comment by muffinresearch** [comment]
Now I've seen this, this is controlled by the iframe - the padding is outside the iframe not inside it. The padding has been removed in FF50+ already - see nightly. The scrollbar is on the iframe when the content overflows it.

FF 50 will remove the padding which will make this better. Until then there's nothing we can do from here.

FWIW: It's the case with the current discovery pane in production too.

**Comment by muffinresearch** [comment]
@madalincm can you test with nightly and see if it is good enough to say this problem is gone. If not we might need to file further firefox bugs.

**Comment by muffinresearch** [comment]
Looks like you should be able to get an RTL build of 50 here: https://archive.mozilla.org/pub/firefox/nightly/latest-mozilla-central-l10n/

**Comment by muffinresearch** [comment]
Looks like this on an RTL nightly build (50) for mac - note on OSX the toolbar dissappears if you're not scrolling.

<img width="714" alt="_ _and_applications" src="https://cloud.githubusercontent.com/assets/1514/16657628/14728206-445b-11e6-9131-97d6f9cd7a41.png">

**Comment by madalincm** [comment]
I've checked in nightly and it looks good on windows to (Win7 x64)

![nightlyrtl](https://cloud.githubusercontent.com/assets/15685441/16658806/65a72fa4-4470-11e6-8f1a-9352542dbfc1.png)

**Comment by muffinresearch** [comment]
Ok great, there's nothing to do here other than the conditional padding removal which is logged in #639 and this will be fixed as of FF50.
