### ISSUE TITLE
can no longer download extensions .xpi for firefox 45 -52 and older

### ISSUE THREAD

**Issue by mrkapqa** [mozilla/addons-frontend#7278]
### Describe the problem and steps to reproduce it:

very much .xpi downloads seem no longer accessible; 
i use firefox 45 - 52 on most computers so i feel limited by this.

### What did you expect to happen?

install extensions 

### Anything else we should know?

please show where to download the .xpi as previously offered, thank you.

**Comment by kewisch** [comment]
This is an intended consequence of the [removal of legacy add-ons](https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/) from AMO. Please check [discourse.mozilla.org](https://discourse.mozilla.org/) for further questions/discussions.
