### ISSUE TITLE
Around the Extensions/Themes menu, a dotted line border is present

### ISSUE THREAD

**Issue by sv-sdeiac** [mozilla/addons-frontend#7298]
Environment: 
Device: Nexus 6P (Android 8.1.0);
Build: Nightly 66.0a1 (2019-01-02);

Steps to reproduce: 
1. Load AMO on an Android phone;
2. Tap on the 'Extensions' or 'Themes' menu;
3. Observe the behavior.

Expected result:
Any layout issue is presented.

Actual result: 
Around the Extensions/Themes menu, a dotted line border is presented.

Note:
This issue is also reproducible on AMO prod with FF64, Chrome and Edge with Win10 when clicking the "More" menu and the username (user must be logged in). 

The issue on Android

![screenshot_2](https://user-images.githubusercontent.com/40264165/50633017-78353a80-0f52-11e9-91b8-74cd9c3fde36.png)

The issue on Desktop 

![screenshot_3](https://user-images.githubusercontent.com/40264165/50633074-aadf3300-0f52-11e9-9ab3-e68144302f52.png)

**Comment by championshuttler** [comment]
Hi All, can i take this up , I think by adding `outline: none` to the anchor tag might resolve this issue, correct me please if i am wrong. Thanks

**Comment by willdurand** [comment]
> Hi, can i take this up , I think by adding `outline: none` to the anchor tag might resolve this issue, correct me please if i am wrong. Thanks

This style is added by Firefox IIRC, so I would not remove it.

**Comment by willdurand** [comment]
> This issue is also reproducible on AMO prod with FF64, Chrome and Edge with Win10 [...]

mmmmh, maybe not actually..

**Comment by willdurand** [comment]
Adding `contrib:welcome` to this issue.

**Comment by championshuttler** [comment]
Hi All I was testing it out on different OS , I was able to reproduce it over Debian (Linux ) but not on MacOS , can anyone please confirm it.

Also can i take this up?

**Comment by willdurand** [comment]
> Hi All I was testing it out on different OS , I was able to reproduce it over Debian (Linux ) but not on MacOS , can anyone please confirm it. I was using Firefox 64 in both OS

I think the main issue is with Android (according to the original post).

> Also can i take this up?

yep

**Comment by championshuttler** [comment]
> I think the main issue is with Android (according to the original post).

Oops, my bad , got it thanks @willdurand :smile:

**Comment by ioanarusiczki** [comment]
The rectangle is no longer present on Android (8.0) with FF64 for Extension Tab but the desktop issue is still present and I've also noticed that it's reproducible on Android with the FF logo so I filed the issue here https://github.com/mozilla/addons-frontend/issues/7389

![fara chenar](https://user-images.githubusercontent.com/33448286/51107750-69734100-17f8-11e9-819f-1ce05d2153ea.png)
