### ISSUE TITLE
Display name is now required, we should update the edit page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7301]
The "display name" field is now required (since the `username` removal). Yet, the "Profile" section in the edit page lists optional fields only. We should udpate the UI to make it clear that the "display name" field is not optional anymore.

**Comment by ioanarusiczki** [comment]
@willdurand The field is displayed as mandatory now on AMO dev - FF64(Win10). 

Maybe the text about fields being optional should be moved next to Homepage now? 

![next to homepage](https://user-images.githubusercontent.com/33448286/51848441-454e4e80-2326-11e9-91f3-2d0829ae6ecb.png)

**Comment by willdurand** [comment]
> Maybe the text about fields being optional should be moved next to Homepage now?

We changed the wording a bit, so I guess it is fine as is.
