### ISSUE TITLE
Hide "no users" metadata entry for search tools (on add-on detail pages)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7316]
Based on: https://github.com/mozilla/addons/issues/819.

---

We do not have any "install data" for search tools so we always show add-ons with "no users". Let's hide this message for search tools as it conveys a negative impact for no reason.

**Comment by twisted-sres** [comment]
Hey, I would like to work on this issue, please let me know how to get started

**Comment by caitmuenster** [comment]
Hey @twisted-sres, go for it! 

If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @willdurand

**Comment by twisted-sres** [comment]
I am trying to build it on my local machine, but ./mach build is taking a lot of time

**Comment by championshuttler** [comment]
Hey @twisted-sres are you building gecko on your laptop by any chance?

For addons-frontend development, you can check the requirements [here](https://github.com/mozilla/addons-frontend#requirements), in short, you need nodejs version 8+. After that, please install Yarn from [here](https://yarnpkg.com/en/docs/install).

After that, you can install the project dependencies by running `yarn install` and then please run `yarn test` to make sure project is installed successfully. Now you can start the local dev server by using `yarn amo:dev`.

If you have any doubt. Feel free to ask here :)

**Comment by twisted-sres** [comment]
I wanted to know the expected result,

**Comment by kartik-budhiraja** [comment]
@twisted-sres , From what I understand, the expected result is that for "search type" addons, we should not display "No Users" as we do not track the count of users for such addons.
For better reference :
![image](https://user-images.githubusercontent.com/34459894/51340762-d20f2780-1a5d-11e9-8b98-edc242671d84.png)
It is for [this](https://addons.mozilla.org/en-US/firefox/addon/youtube-10423/?src=search) addon.
"No users" in this image should not be there, but it is only for search-type addons.
If you still have any doubts, feel free to ask here ! :)

**Comment by twisted-sres** [comment]
![screenshot from 2019-01-19 01-45-15](https://user-images.githubusercontent.com/36242614/51410991-2f08fb80-1b8c-11e9-8e0a-7c823c7ac676.png)
Hey, I made the changes and it looks like this on my local system, should I create a PR?

**Comment by twisted-sres** [comment]
![screenshot from 2019-01-19 01-48-39](https://user-images.githubusercontent.com/36242614/51411046-68416b80-1b8c-11e9-80ca-f84e07f4991b.png)
Hey, I made the changes and it looks like this on my local system, should I create a PR?

**Comment by twisted-sres** [comment]
This is my first time contributing to open source, could someone please tell me why are the tests failing?

**Comment by twisted-sres** [comment]
So I figured out why the lint test was failing, and have made a commit to fix it, but now the test CI is failing, even though I have removed the test for 'average daily users' from  tests/unit/amo/components/TestAddonMeta.js

**Comment by twisted-sres** [comment]
@willdurand please review #7435

**Comment by championshuttler** [comment]
Hi @twisted-sres thanks for the Pull request , today is Sunday , most of the staff is on holiday so lets wait for tomorrow for review 😃

**Comment by twisted-sres** [comment]
Please review @willdurand

**Comment by willdurand** [comment]
> I was wondering if we should file an issue to hide user count for search tools from search results page because it shows 0 users for all of them.

Good call, we should probably do that too

**Comment by willdurand** [comment]
> @willdurand Should I file the issue?

Yes please

**Comment by willdurand** [comment]
Thanks @twisted-sres!
