### ISSUE TITLE
Remove the functionality of the "mamo" cookie

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7321]
In #7246 we are removing the link to view the classic site from the AMO footer. We would also like to disable the ability to view the classic site for anyone who currently has the `mamo` cookie set. I understand that this is something that is entirely configured via nginx. @bqbn is this something you can take care of?

**Comment by bqbn** [comment]
We can take care of it.

To be clear, is it correct that you want the proxy layer (nginx) to ignore the `mamo` cookie, no matter what its value is and/or if the cookie is present or not?

**Comment by bobsilverberg** [comment]
> To be clear, is it correct that you want the proxy layer (nginx) to ignore the mamo cookie, no matter what its value is and/or no matter the cookie is present or not?

I  believe that is correct. Our intention is for all traffic to go to the new site, not the legacy site, regardless of the cookie value or the presence of the cookie.

**Comment by willdurand** [comment]
This has been deployed in -dev and -stage if I am not mistaken. /cc @autrilla

**Comment by autrilla** [comment]
That is correct

**Comment by willdurand** [comment]
Closing this one then :)

**Comment by ioanarusiczki** [comment]
@autrilla 
I verified this issue on AMO stage with FF64 - Win10 
- the old pages left open were already displayed in the new view today even if the mamo cookie is present and has the value "off". 

![mamo cookie](https://user-images.githubusercontent.com/33448286/50959846-91973300-14cc-11e9-961b-35b468c60eed.png)

- after clearing the cookies, the mamo cookie is no longer available

Yesterday the new pages were displayed only after a refresh but it wasn't the case today 

![redirecting to the new site 1](https://user-images.githubusercontent.com/33448286/50959946-e044cd00-14cc-11e9-9f2c-53104f3fb45f.gif)
