### ISSUE TITLE
Error page when looking at my profile page while logged in

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#7322]
When I'm logged in and try to access [my profile page](https://addons.mozilla.org/en-US/firefox/user/4230/), I get a server error page. The page loads fine if I'm not logged in.

The page appears to be loading fine and then switches to an error page. I see this in the console, which may be related:

> Caught application error: Invariant Violation: "addonSlug is required"
> 
>     exports Redux
> 
> p reviews.js:551 value Cookies.js:37 ci21React
> 	y Redux	i selectors.js:199 u errors.js:47 dispatch index.js:96 Zn2Redux
> Ur addonsByAuthors.js:17 Br addonsByAuthors.js:25 Fr addonsByAuthors.js:17 O4Redux
> a es6.reflect.construct.js:25 R es6.reflect.construct.js:32 c es6.reflect.set-prototype-of.js:5 exports es6.regexp.constructor.js:16 <anonymous> es7.promise.finally.js:11 a5Webpack
>  
> Object { componentStack: "\n    in n\n    in Translate(n)\n    in Connect(Translate(n))\n    in Connect(Connect(Translate(n)))\n    in li\n    in ul\n    in div\n    in section\n    in t\n    in t\n    in div\n    in div\n    in div\n    in t\n    in Connect(t)\n    in Translate(Connect(t))\n    in Connect(Translate(Connect(t)))\n    in t\n    in t\n    in N\n    in t\n    in Connect(t)\n    in div\n    in div\n    in div\n    in t\n    in t\n    in withRouter(t)\n    in NestedStatus\n    in SideEffect(NestedStatus)\n    in t\n    in withCookies(t)\n    in Translate(Component)\n    in Connect(Translate(Component))\n    in t\n    in withRouter(Connect(Translate(Component)))\n    in StrictMode\n    in t\n    in t\n    in r\n    in Connect(r)\n    in a\n    in t\n    in x" }
> BigInteger.js:110

**Comment by bobsilverberg** [comment]
I can look into this. I tested it and was unable to reproduce it using my own profile as well as @jvillalobos's profile, so it might be specific to his profile viewed when logged in with his account. I'll do some digging into the code.

**Comment by bobsilverberg** [comment]
I did some digging and here's what I came up with:

There are only 3 places in the code whence this error could be coming from, and the only one that makes sense in the context of the User Profile page is the one in  [`reviewListURL`](https://github.com/mozilla/addons-frontend/blob/2018.12.18/src/amo/reducers/reviews.js#L68-L83).

I believe that `reviewListURL` is being called in this instance from [`AddonReviewCard`](https://github.com/mozilla/addons-frontend/blob/2018.12.18/src/amo/components/AddonReviewCard/index.js#L373-L376) because again that is the only logical conclusion for the User Profile page.

Therefore it seems that `review.reviewAddon.slug` is falsey at that point, but I'm not sure how that can be. According to Flow, [`reviewAddon.slug`](https://github.com/mozilla/addons-frontend/blob/2018.12.18/src/amo/actions/reviews.js#L63) cannot be missing, but it could be an empty string. I'm not sure that an add-on can have an empty string as a slug, but I wonder if this could be a result of an add-on being disabled or otherwise removed. Perhaps if a user has reviewed an add-on that no longer exists this could occur?

@kumar303 What do you think?

**Comment by kumar303** [comment]
> I wonder if this could be a result of an add-on being disabled or otherwise removed. 

Sounds likely. Perhaps @jvillalobos had reviewed an add-on which is now either deleted or disabled. His profile page is trying to display those reviews.

**Comment by bobsilverberg** [comment]
@kumar303 Yes, that seems like the most likely thing. I'm not sure how to test it though. I tried disabling an add-on by disabling its current version, and I also tried deleting an add-on via the Django admin (but that didn't seem to actually delete the add-on), but neither of those caused this error to reproduce.

I'm going to put up a PR that fixes this, assuming we are correct about the issue, and if it looks okay then maybe we can deploy it and see if it fixes the issue. Or maybe there's another way to *actually* delete an add-on that might surface this error.

**Comment by AlexandraMoga** [comment]
I wasn't able to reproduce this either. I've tried both with regular and admin accounts, with deleted or disabled addons, changed addons slugs..

I'm guessing there is a special case behind that will cause this issue to happen.

**Comment by AlexandraMoga** [comment]
Having tried this with several profiles and not being able to reproduce the issue, I think the only solution is to wait for @jvillalobos to confirm if the issue is fixed for his account.

**Comment by jvillalobos** [comment]
The profile page now loads correctly. Thanks!

**Comment by bobsilverberg** [comment]
I guess we fixed the problem. Thanks @jvillalobos. Can you check, is there a review listed on your profile page that appears without a permalink?

**Comment by jvillalobos** [comment]
They all appear to have permalinks, but a bunch of them are for add-ons that are disabled, so the link goes to an error page.

**Comment by bobsilverberg** [comment]
> They all appear to have permalinks, but a bunch of them are for add-ons that are disabled, so the link goes to an error page.

For those ones, does the link include the addonId as opposed to the slug? Can you paste an example of one of those links?

**Comment by jvillalobos** [comment]
[This one](https://addons.mozilla.org/en-US/firefox/addon/password-exporter/reviews/935676/) is disabled and the link still has the slug.

[This one](https://addons.mozilla.org/en-US/firefox/addon/495446/reviews/563122/) uses the add-on ID instead. I think this add-on was deleted.

**Comment by kumar303** [comment]
This add-on was fully deleted? I guess that explains it.

```
$ curl 'https://addons.mozilla.org/api/v4/ratings/rating/563122/' | jq .
{
  "id": 563122,
  "addon": {
    "id": 495446,
    "slug": null,
    "name": {
      "en-US": "Jorge V clown"
    },
    "icon_url": "https://addons.cdn.mozilla.net/user-media/addons/495446/icon.png?modified=51fd491e"
  },
  "body": "Finally, a theme I can use!",
  "created": "2014-03-19T14:04:52Z",
  "is_deleted": false,
  "is_developer_reply": false,
  "is_latest": true,
  "previous_count": 0,
  "user": {
    "id": 4230,
    "name": "Jorge Villalobos",
    "url": "https://addons.mozilla.org/en-US/firefox/user/4230/",
    "username": "jorge-villalobos"
  },
  "score": 5,
  "reply": null,
  "version": {
    "id": 1533582,
    "version": "0"
  }
}
```

**Comment by bobsilverberg** [comment]
Yes, mystery solved. Thanks @kumar303 and @jvillalobos!
