### ISSUE TITLE
Old view for the error message is displayed instead of the new message 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7327]
STR:
1. Load AMO dev and click the extension tab
2. Change the URL in order to receive the error message, https://addons-dev.allizom.org/en-US/firefox/extensions/, make it  https://addons-dev.allizom.org/en-US/firefoz/extensions/ or  https://addons-dev.allizom.org/en-US/firefoz/extensionz/ 
3. Observe the screen

Expected result:
Oops! We can’t find that page the new message is displayed such as here https://addons-dev.allizom.org/en-US/firefox/extensions/tabz/

Actual result:
The old view is displayed such as here https://addons-dev.allizom.org/en-US/firefox/guidez/stay-safe-online/

Notes:
It is reproducible when the address is not correct when changing /firefox/extensions part. If a category is selected https://addons-dev.allizom.org/en-US/firefox/extensions/tabs/ and /tabs/ is modified then the new message is visible. The same for the add-ons detail page such as https://addons.mozilla.org/en-US/firefox/addon/tab-reloader/, when the slug is incorrect the new message is visible, if /firefox/addon is modified the old view is displayed (same for a modified collection's URL), the guide lines (when /firefox/guides/ is incorrect).
This issue is reproducible on all AMO servers with FF64(Win10). 

![old view displayed2](https://user-images.githubusercontent.com/33448286/50825454-ba3ef180-1341-11e9-9cd6-87e0fac51246.gif)

**Comment by willdurand** [comment]
I noticed this issue yesterday too. I wasn't sure it was only me or not..

**Comment by willdurand** [comment]
From IRC:

> [It is] because we default route to olympia, and have some specific routes that go to frontend. So `/en-US/firefox/extensions/non-existent-extension` matches one of those routes and therefore goes to the frontend, but `/en-US/firefox/extensionadfaskjadsg/` does not and defaults to olympia
> I don't think this can be fixed unless we reverse it and default to frontend and special-case other pages

**Comment by willdurand** [comment]
>  I don't think this can be fixed unless we reverse it and default to frontend and special-case other pages

@bobsilverberg @muffinresearch is there any plan to do something like this once all legacy pages have been ported to the new frontend and we avoid to serve the old frontend?

**Comment by bobsilverberg** [comment]
> @bobsilverberg @muffinresearch is there any plan to do something like this once all legacy pages have been ported to the new frontend and we avoid to serve the old frontend?

That does sound like something we should do. I guess we should put a plan in place to do that, and discuss whether there are any situations in which we would still need to serve the old site.

**Comment by willdurand** [comment]
This issue has been filed a while ago actually... See: #6606. I'm going to keep this issue here and close #6606 because we started to comment here.

**Comment by jvillalobos** [comment]
This seems to be fixed already.
