### ISSUE TITLE
All versions page - the last version is installed no matter what version is clicked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7332]
STR:
1. Load AMO dev and go to All version page for an addon with multiple versions such as https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/versions/
2. Click one of the version and watch the screen

Expected result:
The chosen version is installed.

Actual result:
All the buttons start the install process and then all display "Remove" state. The last version of the add-on is installed.

Notes:
This issue is reproducible on AMO dev with FF64 unbranded (Win10). 

![all versions are installed](https://user-images.githubusercontent.com/33448286/50841409-53cfc880-136d-11e9-8194-bb76072ac9f8.gif)

**Comment by bobsilverberg** [comment]
There are a number of problems here, including the fact that "Remove" and "Enable" buttons are displayed for each version when a version is installed or disabled. I took a look at the legacy version of this page, which is still available in prod (e.g., at https://addons.mozilla.org/en-US/firefox/addon/auth-helper/versions/) and what I found was that the "All Versions" page on the legacy site simply shows "Install" buttons for every version, regardless of whether a current version is installed or disabled. This is certainly much simpler and would eliminate the issues I've discussed above.

@jvillalobos Should we do the same for the new version of the "All Versions" page? That is, should each version simply have an Install button that allows it to be installed, regardless of whether the add-on is already installed and/or disabled?

**Comment by jvillalobos** [comment]
I don't mind that all of the buttons on the page change state at the same time. It could be useful to know that you have the extension installed and have the option to remove it from that same page. I'd rather fix the original problem, which appears to be that the button isn't installing the correct old version.

/cc @atsay for second opinion.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. I do plan on fixing the main problem reported, making sure that clicking a button installs the correct version.

My comments were more about the other problems on the page. It seems a bit confusing to me to have all the buttons say "Enable" when only one of the versions (whichever is currently installed) will be enabled. It would be a significant amount of work to sync up the buttons so that only the one for the currently installed version says "Enable", which is why I was suggesting we just do what the old site did.

**Comment by jvillalobos** [comment]
I see what you mean, but the flip side is that the buttons then wouldn't react in the same way as everywhere else on the site (and the add-ons manager), and keeping consistent appearance and behavior has been a big UX goal.

**Comment by bobsilverberg** [comment]
@jvillalobos That makes sense. It therefore sounds like nothing has to change about this version of the page, other than making sure that installing an older version actually installs that version, correct? You're happy with the button behaviours otherwise?

**Comment by jvillalobos** [comment]
Yeah, I'm okay with their current behavior. If @atsay doesn't object soon, I think we can leave them that way.

**Comment by atsay** [comment]
Yes, agree with @jvillalobos that letting people install the version they mean to install is the biggie. Ok to leave everything else the same.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on AMO dev and AMO stage with FF64(Win10) for add-ons and static themes. 
- The correct version is installed now.  
- "Remove" and "Enable" can be clicked on any of the version and it will remove, enable the previous installed version. 
- The scenarios when the versions are enabled or removed from add-on manager behave the same way as for the other pages (detail pages, disco pane).

![works with the correct version](https://user-images.githubusercontent.com/33448286/50965043-8e567400-14d9-11e9-8c96-e03fdb9c1dfe.gif)
