### ISSUE TITLE
"Add to firefox" button could be centered on All version page 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7333]
STR:
1. Load AMO dev and go to an All version page for an add-on with more than one version displayed such as https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/versions/
2. Observe install button

Expected result:
The button is below the version's number. (center right)

Actual result:
Actual position is up on the right.

Notes:
Reproducible on AMO dev with FF64(Win10). 

![in the middle](https://user-images.githubusercontent.com/33448286/50843025-9ba41f00-1370-11e9-8d04-3cf43e2fce27.png)

**Comment by championshuttler** [comment]
Hi All, can i take this up . I guess by fixing 
```
.InstallButtonWrapper {
    align-self: start;
  }
``` to

````
.InstallButtonWrapper {
    align-self: center;
  }
```
at src/amo/components/AddonVersionCard/styles.scss will solve the issue.

Can i take a shot!?

Here is updated screenshot: 

![image](https://user-images.githubusercontent.com/22130317/50857810-bd26fa00-13b4-11e9-9ec8-45f24434b932.png)

**Comment by bobsilverberg** [comment]
Sure @championshuttler, that looks good. Go ahead and submit a pull request, and thanks!

**Comment by ioanarusiczki** [comment]
Looks good to me. Verified on AMO dev with FF64 (Win10). 

![example one](https://user-images.githubusercontent.com/33448286/51041955-b91cf700-15c3-11e9-9714-4dfe14786f4c.png)

![example2](https://user-images.githubusercontent.com/33448286/51041964-bde1ab00-15c3-11e9-8608-2a7f1af54b96.png)
