### ISSUE TITLE
About this addon section not using complete width

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-frontend#7337]
### Describe the problem and steps to reproduce it:
Go to https://addons.mozilla.org/en-US/firefox/addon/permission-inspector/ and check `About this extension` component.

### What happened?
I expected `About this extension` component to use full width, right now it looks like https://ibb.co/ByrVn8N

### What did you expect to happen?
I expected to see the description like this  https://ibb.co/C1Fpjym

**Comment by championshuttler** [comment]
Let me know if I need to provide any other details about it.
Happy to give this a shot!

**Comment by willdurand** [comment]
I don't think we plan to change that as per https://github.com/mozilla/addons-frontend/issues/4158#issuecomment-357923307
