### ISSUE TITLE
Server error message for mozilla collections opened from the guides pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7344]
Possible regression from #6609 

STR:
1. Open AMO stage homepage
2. Go to a guideline page - i.e. https://addons.allizom.org/en-US/firefox/guides/stay-safe-online/
3. Click on Explore more [password managers] to open the mozilla password managers collection

Actual result:
A Server error page is opened

Expected result:
The collection details page is opened

Note:
- probably these collection pages are hardcoded, the same as in the case of #7297 ; you can see that `username` /mozilla/ is used in the URLs
- I've also noticed the following error in the console:
```
Caught application error: Invariant Violation: "Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. "
```
- reproduced on -dev and stage with FF64, Win10x64

![2019-01-09_11-26-08](https://user-images.githubusercontent.com/31961530/50890196-6811d500-1402-11e9-873c-9d2134b898ab.gif)

**Comment by willdurand** [comment]
ah, looks like we did not change the URLs :(

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -stage with FF64, WIn10x64

![2019-01-10_09-56-38](https://user-images.githubusercontent.com/31961530/50954154-41b16f80-14be-11e9-97f8-86e79b3a11de.gif)
