### ISSUE TITLE
The install button should use the full width below the text of each version on the version page (on small screens)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7346]
The install button should be displayed below the text of each version on the version page (on small screens) and use the full width, rather than staying next to the content. This would match the style of the install button on an add-on detail page.

### Current:

![screen shot 2019-01-09 at 11 16 01](https://user-images.githubusercontent.com/217628/50893471-377d6b80-1401-11e9-9d5c-34ee95a2aeef.png)

### Expected:

![screen shot 2019-01-09 at 11 22 38](https://user-images.githubusercontent.com/217628/50893360-eff6df80-1400-11e9-954b-f0fbeafaa63d.png)

**Comment by championshuttler** [comment]
Can I try to give it a shot! ?

**Comment by willdurand** [comment]
> Can I try to give it a shot! ?

yep

**Comment by bobsilverberg** [comment]
@championshuttler I'd like to have this fix landed by next week's push. Do you plan on fixing it soon? If not, I might take it over and get it done. Please let me know what your plans are with respect to this issue.

**Comment by championshuttler** [comment]
Hi @bobsilverberg I will send patch soon by today only working on it:

**Comment by ioanarusiczki** [comment]
Verified on AMO dev with Android 8.0 

![ux issues](https://user-images.githubusercontent.com/33448286/51254600-14772c80-19aa-11e9-984f-cec72c83f6eb.gif)
