### ISSUE TITLE
All versions page for static themes returns a server error message

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7348]
Follow up for #2770

STR:
1. Open a static theme details page - https://addons.allizom.org/en-US/firefox/addon/128x128/?src=search
2. Click on See all versions in the More information card

Actual result:
A server error page is displayed

Expected result:
Static theme versions page is displayed

Notes:
- reproduced on -dev and stage with FF64, WIn10x64

![2019-01-09_13-21-34](https://user-images.githubusercontent.com/31961530/50896373-86330180-1411-11e9-82f0-54a97cda4db6.gif)

**Comment by willdurand** [comment]
It looks like a license might not have `text` or `url`.

**Comment by willdurand** [comment]
@muffinresearch @bobsilverberg can we live with that for a week or should we cherry-pick the patch for this issue? (hence marking it as `p1` instead of `p2`)

**Comment by muffinresearch** [comment]
> @muffinresearch @bobsilverberg can we live with that for a week or should we cherry-pick the patch for this issue? (hence marking it as `p1` instead of `p2`)

If the patch is low-risk then let's pick it.

**Comment by willdurand** [comment]
ok, let's cherry-pick then.
