### ISSUE TITLE
ABP icon not available from the toolbar

### ISSUE THREAD

**Issue by SylviaOr** [mozilla/addons-frontend#735]
Nightly 50.0a1
OS X Yosemite 10.10.5

### STR
1. Navigate to: about:addons
2. Install Adblock plugin by turning ON the switch. 
3. Message displayed says: “Your add-on is ready. Now you can access Adblock Plus from the toolbar.”

### Expected result:
Add-on is accessible from the toolbar.

### Current result:
Add-on is not available in the toolbar.
![nightly-abp-1](https://cloud.githubusercontent.com/assets/20317898/16662591/6fbf2e44-4478-11e6-994e-ef4e96a71f0b.png)
![nightly - no abp](https://cloud.githubusercontent.com/assets/20317898/16662597/7772c812-4478-11e6-8039-be86cfccd561.png)

**Comment by muffinresearch** [comment]
You're testing on nightly. What server are you running against? It's probably and old add-on.

You should ideally be testing on prod with 48Beta5+ 

Can you re-test there and let me know if that solves the problem?

**Comment by muffinresearch** [comment]
Closing, please reopen if there's still issues.

**Comment by SylviaOr** [comment]
Well - I did what you wanted, but problem is different...

OS X Yosemite 10.10.5
Firefox 48.0b5

STR
1. Navigate to: about:addons
2. Install Adblock plugin by turning ON the switch.

Expected result:
Add-on is installed and accessible from the toolbar.

Current result:
Message displayed says: "Download failed. Please check your connection."
![abp-beta](https://cloud.githubusercontent.com/assets/20317898/16683833/0f9267ea-4502-11e6-9946-8547906deb9d.png)

### But look:
https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing
There is a note:
Testing
To test on dev or stage:
NOTE: dev/stage certs no longer work in 48b5 onwards - to test after 48b4 you'll need to use dev edition or nightly.

**Comment by muffinresearch** [comment]
Are you actually pointing at production?

Since it's released you can use 48b5 and just go to about:addons, no other settings necessary.

**Comment by SylviaOr** [comment]
Ok... But I still have message "Download failed. Please check your connection." (but it is not about connection)

**Comment by muffinresearch** [comment]
Sure, but are you still running with the settings from https://wiki.mozilla.org/Add-ons/Projects/DiscoveryImprovements#Testing e.g. what is `extensions.webservice.discoverURL` set to?

To rule out settings can you try with 48b5 + a new profile and just open about:addons?

**Comment by SylviaOr** [comment]
After creating a new profile on 48b5 there is no problem. There is icon ABP in the toolbar

![ok](https://cloud.githubusercontent.com/assets/20317898/16687427/ddcfae04-4518-11e6-857b-eddcbbc27426.png)

Thanks.
