### ISSUE TITLE
Version notes - the text should be separated from Source code and should be wider on android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7350]
STR:
1. Load AMO dev and go to the all version page of an add-on, make sure it has version notes included
2. Observe the text

Expected result:
The notes are separated from the Source code line.

Actual result:
The notes and the Source code are not separated, they look like a paragraph. 

Notes:
This issue is also reproducible on android and also the text on small screen could expand more to the right. 
Reproducible on AMO dev with FF64 (win10&android 8.0). 

Desktop 
![desktop1](https://user-images.githubusercontent.com/33448286/50899733-abc50880-141b-11e9-96b2-2f14921b2a5f.png)

Android
![android layout](https://user-images.githubusercontent.com/33448286/50899743-b1bae980-141b-11e9-8d26-83d9f98624c0.png)

**Comment by dhruvgupta167** [comment]
Hi @ioanarusiczki , I would like to work on this issue. But I finding it difficult to reproduce. Could you please elaborate like which site I should visit?

**Comment by willdurand** [comment]
Hi @dhruvgupta167, sorry but this issue is not yet opened for external contributors. 
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by bobsilverberg** [comment]
I believe this will be fixed when https://github.com/mozilla/addons-frontend/pull/7370 lands.
