### ISSUE TITLE
Use react-router to link to the "all versions" page in an add-on detail page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7352]
We should change the link to the "all versions" page on an add-on detail page so that it fully uses react-router and client-side navigation when available.

**For QA:** when clicking the "See all versions" link, there should be no page refresh, the app should take you to the "all versions" page using client-side navigation.

**Comment by ioanarusiczki** [comment]
@willdurand I verified this issue on AMO dev with FF64 and Chrome (Win10).
AMO dev - not reproducible all the time but sometimes the right side of the screen (the list of versions) loads with a very little delay.

![the right side3](https://user-images.githubusercontent.com/33448286/51117865-9a16a300-1817-11e9-8648-3019e18e88bf.gif)


Before (checking on AMO stage) the left side of the screen ( ratings) and the Install button have a visual glitch/reload. This is no longer reproducible on -dev

![amo stage - reload](https://user-images.githubusercontent.com/33448286/51117820-7eab9800-1817-11e9-8c1c-97f7f58b12a0.gif)

Let me know if it's how you expected it.

**Comment by willdurand** [comment]
> @willdurand I verified this issue on AMO dev with FF64 and Chrome (Win10).
> AMO dev - not reproducible all the time but sometimes the right side of the screen (the list of versions) loads with a very little delay.

I believe that's normal.

**Comment by ioanarusiczki** [comment]
Verified on AMO Dev with FF64 & Chrome (Win10).
