### ISSUE TITLE
Add-on review listing gets stuck on page 2, 3, etc...

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7376]
### Describe the problem and steps to reproduce it:

- Go to an add-on review listing with more than 25 reviews, such as https://addons-dev.allizom.org/en-US/firefox/addon/awesome-screenshot-plus-/reviews/
- Scroll to the bottom and click *Next* to advance the page
- Take note of the first review at the top of the page
- Click on the add-on name to return to the detail page
- Click on *Read all N reviews* from the detail page to return to the review listing

### What happened?

The review listing begins with the first review on page 2

### What did you expect to happen?

It should begin with the first review on page 1. In other words: the listing should not get stuck on page 2.

### Anything else we should know?

This bug is very similar to https://github.com/mozilla/addons-frontend/issues/7206

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO dev with FF64, Win10x64 and Android 8.0

![2019-01-16_15-46-00](https://user-images.githubusercontent.com/31961530/51253150-35d61980-19a6-11e9-8368-990f50d6a944.gif)
