### ISSUE TITLE
Stand-up amo app  on dev

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#738]
This is to track anything we need to stand-up the amo app which will initially be mobile pages on -dev.

Relates to mozilla/addons#151

**Comment by muffinresearch** [comment]
As discussed in the stand-up we're probably going to want to temporarily use a separate domain for standing-up the new mobile pages so people can see the progress easily and that will allow us to get lots of feedback and iterate more effectively but without needing to worry about diverting mobile traffic just yet.

The main issue is going to be the install buttons that will need access to the addonManager API. 

What I propose is we can decide on a new hostname for this and then add that to the testing domains in Firefox so we can use nightly to test it. As I mentioned we will need a fall-back for UAs that don't have the API (in fact does android even have the addonManager API - if not then the API permission is less of an immediate problem except we will want to make sure it does work for both cases.)

Maybe `amo.addons-dev.allizom.org` will do since that's the name of the app. We could add that and `amo.addons.allizom.org` to the testing domains in FF and then we've got that at least covered for the short-term.

Better naming suggestions welcomed.

@jasonthomas @andymckay how does that sound?

**Comment by jasonthomas** [comment]
amo.addons-dev.allizom.org and amo.addons.allizom.org work for me. Are we ready to deploy the amo addons-frontend app to -dev and stage?

**Comment by muffinresearch** [comment]
It'll definitely be worth getting -dev at least. There's not much to see quite yet, but that will be a start and we can figure out all the necessary config to get it working.

Is the plan to use a similar separate CDN for statics along the same lines as the disco pane?

**Comment by kumar303** [comment]
A few times it's come up that "dev" is a poor description of what we typically use `addons-dev.allizom.org` for. What about calling it "latest" since it tracks master? Maybe `amo.addons-latest.allizom.org`?

Calling it "dev" is particularly confusing because we have to make a distinction for all local development type of servers by calling them "local" or something equally problematic.

Anyway, no need to bikeshed it but I thought I'd mention it since the server hasn't been named yet :)

If it will be extra confusing to name this one differently than it's companion "dev" environments then let's not.

**Comment by jasonthomas** [comment]
> Is the plan to use a similar separate CDN for statics along the same lines as the disco pane?
Yes.

**Comment by muffinresearch** [comment]
@jasonthomas hi - do you have a rough idea of the time line for standing up the first cut of the amo app on -dev?

**Comment by jasonthomas** [comment]
I should have it up later today if I don't run into any issues.

**Comment by jasonthomas** [comment]
https://amo.addons-dev.allizom.org/en-US/firefox/ is up but we need the static assets to point to the current CDN endpoint. https://github.com/mozilla/addons-frontend/pull/1242 for those changes.

**Comment by muffinresearch** [comment]
@jasonthomas thanks!

**Comment by kumar303** [comment]
Agreed on standardizing the naming across all servers
