### ISSUE TITLE
Dotted line border still present on desktop and android 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7389]
Part of https://github.com/mozilla/addons-frontend/issues/7298

STR:
1. On desktop load AMO dev login and click the username on the upper right side of the screen.
2. On android load AMO dev navigate away from homepage then tap the logo.

Expected result:
No display issues.

Actual result:
A white rectangle is present.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF64 (Win10) and Android 8.0
The desktop issue is also reproducible with Chrome and Edge. 

desktop
![chenar pe desktop](https://user-images.githubusercontent.com/33448286/51107602-e94cdb80-17f7-11e9-8d79-00d616187829.png)

android
![chenar pe android](https://user-images.githubusercontent.com/33448286/51107612-f1a51680-17f7-11e9-97f7-89f71bdefd22.png)

**Comment by willdurand** [comment]
⚠️ when fixing this, please make sure keyboard navigation (accessibility) still works.

**Comment by willdurand** [comment]
@suhailsinghbains yep

**Comment by suhailsinghbains** [comment]
I tried to remove the outline attribute, but 0 does not work, still working on it :)

> 0: warning when fixing this, please make sure keyboard navigation (accessibility) still works.

**Comment by ioanarusiczki** [comment]
@willdurand 

The dotted lines are no longer visible on desktop (win10). - FF65

![no longer available](https://user-images.githubusercontent.com/33448286/52127648-5f946f00-263b-11e9-948a-3837a610b6b2.gif)

But on Android (8.0) it is still displayed - FF65

![the dotted line on android](https://user-images.githubusercontent.com/33448286/52130329-8904c900-2642-11e9-9609-a3564d0b3f81.png)

I think we should reopen the issue.

**Comment by willdurand** [comment]
> I think we should reopen the issue.

no, I think it's fine.

**Comment by willdurand** [comment]
This is a browser default theme and honestly, I don't see the point of hiding it everywhere. I was keen to fix the homepage for Android, but we won't fix everything because that does not really make sense to me. I am thinking about reverting this patch now and wontfix'ing this issue because it is a lot of work/noise for a very little value.

**Comment by ioanarusiczki** [comment]
@willdurand Well the desktop problem was fixed. Let's just leave this as it is now.
