### ISSUE TITLE
If "Firefox for Android" was checked for a previous addon version it should remain checked on submitting a new version

### ISSUE THREAD

**Issue by creesch** [mozilla/addons-frontend#7394]
### Describe the problem and steps to reproduce it:
1. Submit a new addon to AMO.
2. Mark ` Firefox for Android` under `Which applications is this version compatible with?`
3. Submit an updated version of the same addon to AMO.
4. Check what the default state is of the `Firefox for Android` checkbox

### What happened?
The checkbox was not checked.

### What did you expect to happen?
The checkbox should be checked as previous version were also compatible with Firefox for Android. Now it is incredibly easy to miss that checkbox when submitting your addon and accidentally withhold updates from a user group. 

### Anything else we should know?
This issue is a result of the discussion in [this bugzilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1519725)

**Comment by willdurand** [comment]
Thanks. I moved this issue to addons-server: https://github.com/mozilla/addons-server/issues/10398.
