### ISSUE TITLE
Add-on screenshot images need a maximum width/height

### ISSUE THREAD

**Issue by erosman** [mozilla/addons-frontend#7395]
I noticed that the following add-on has images that are shown on pop-up wider than my screen thus cropping parts of the image and no method to scroll.
https://addons.mozilla.org/en-US/firefox/addon/%E7%AE%80%E5%8E%86%E5%B0%8F%E7%8C%8E%E6%89%8B/

I suggest the maximum dimensions of the pop-up should be limited to viewport width/height.

```
<div id="jquery-lightbox" style="top: 296.8px; left: 0px;">
  <div id="lightbox-container-image-box" style="width: 1431px; height: 709px;">
  ....
```

**Comment by erosman** [comment]
> I can't even access the add-on detail page

OH .. I see .... It seems it requires elevated permissions

> This is not a public listing. You are only seeing it because of elevated permissions.

**Comment by willdurand** [comment]
@erosman can you reopen an issue when we can get access to the add-on? There is nothing we can do so far 😞

**Comment by erosman** [comment]
66.0a1 (2019-01-26) (64-bit) Win 7

@willdurand Here is another example I came across today
`https://reviewers.addons.mozilla.org/en-US/reviewers/review/bookmarks-organizer`

Screenshot:
https://postimg.cc/4YwSNthq

**Comment by erosman** [comment]
More examples:

`https://reviewers.addons.mozilla.org/reviewers/review/1013926/`

@willdurand I suggest reopening this issue, instead of creating a new one which would be the duplicate of this one.

**Comment by willdurand** [comment]
So this issue is about limiting the width/height of an image when displayed in full size (we use this [react-photoswipe](https://github.com/minhtranite/react-photoswipe) for that).

**Comment by erosman** [comment]
@willdurand At the moment, on AMO larger screenshots are scaled to fit the browser window (with JS). However, that does not seem to be the case on 'reviewers.addons.mozilla.org'
I assumed the code dealing with the screenshot display would have been the same on both AMO and RAMO.

**Comment by willdurand** [comment]
> @willdurand At the moment, on AMO larger screenshots are scaled to fit the browser window (with JS). However, that does not seem to be the case on 'reviewers.addons.mozilla.org'
> I assumed the code dealing with the screenshot display would have been the same on both AMO and RAMO.

oh ok, well I am not sure I understand the issue then. If it is only on RAMO, then it's a wontfix because the code of RAMO does not live there.

**Comment by erosman** [comment]
To start with it was happening on both but it hasnt been the case for a while on AMO and therefore I opened https://github.com/mozilla/addons-server/issues/10551 for RAMO

**Comment by willdurand** [comment]
sorry for the confusion then, closing this issue as it seems to work on AMO.
