### ISSUE TITLE
24 January homepage content update 

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#7403]
For the **24 January** push, please update the homepage per these [programming details](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by ioanarusiczki** [comment]
@willdurand 
The [document](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#) mentions this link https://addons.mozilla.org/en-US/firefox/extensions/?sort=featured 
for Featured Extensions but I believe that redirects to the Extension tab. 
Still, on AMO dev I have this link https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=extension when I click on "See more featured extensions" so I think it should be alright. 

Final validation will be made on AMO prod.
