### ISSUE TITLE
Static themes are not returned in search results on Android when filter is set to Themes

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7410]
Prerequisites: Use Firefox beta or Nightly 66, which should have support for static themes on Android

STR:

1. Open AMO stage on an Android device - https://addons.allizom.org/en-US/android/
2. Enter a search term that should also bring themes as results, i.e _blue_
3. Observe the search results - number and examples
4. Filter by Themes
5. Check the search results again

Actual result:
When the Theme filter is applied, static themes disappear from search results. 

Expected results:
Static themes should be present in search results when filtering by Themes

Notes:
- https://github.com/mozilla/addons-server/issues/10019 added basic support for static themes on Android; simple themes, like the migrated LWT should be installable on mobile
- static themes are returned in search suggestions when the filter type is set to _All_
- reproduced on AMO stage with FF65, ANdroid 8.0

![2019-01-16_13-11-06](https://user-images.githubusercontent.com/31961530/51245951-d40bb480-1991-11e9-9f75-d939fb3d729e.gif)

**Comment by muffinresearch** [comment]
Looks like the wrong type params are being passed to the API. 

For the URL `https://addons.allizom.org/en-US/android/search/?platform=mac&q=live%20for%20music&type=statictheme%2Cpersona` (Note the *android* in the URL)

the API call is:

`https://addons.allizom.org/api/v4/addons/search/?app=firefox&appversion=66.0&platform=mac&q=live%20for%20music&type=persona&lang=en-US&wrap_outgoing_links=true`

Whereas for the URL `https://addons.allizom.org/en-US/firefox/search/?platform=mac&q=live%20for%20music&type=statictheme%2Cpersona` (note the **firefox** in the URL)

The API call is:

`https://addons.allizom.org/api/v4/addons/autocomplete/?app=firefox&appversion=66.0&platform=mac&q=live%20for%20music&type=statictheme%2Cpersona&lang=en-US&wrap_outgoing_links=true`

The first api call under the android client app is not passing `statictheme`.

Settings for stage as follows at time of testing:

<img width="261" alt="fullscreen_21_01_2019__12_59" src="https://user-images.githubusercontent.com/1514/51476168-92f21680-1d7c-11e9-88e4-adf7b8838f88.png">

**Comment by willdurand** [comment]
We have a function that does what @muffinresearch described above: https://github.com/mozilla/addons-frontend/blob/785b69b1f6d27c0deb05701406eaeeb70b2c652e/src/core/searchUtils.js#L128-L173

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO stage with FF66, Android 8.0

- static themes are returned in search results when a Theme filter is applied:

![2019-01-22_13-16-19](https://user-images.githubusercontent.com/31961530/51532218-4247ef80-1e48-11e9-8464-95324e4fb8b9.gif)

- on FF64, which doesn't support static themes for Android, this search query will bring some LWT, which unfortunately were broken during the migration on stage .
