### ISSUE TITLE
Consider implementing a sort by relevance for the All reviews page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7411]
Follow up for #7200 

STR:
1. Open an add-on product page - https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/?src=featured
2. Go to the addon reviews page - https://addons.mozilla.org/en-US/firefox/addon/new-tab-override/reviews/
3. Check the results

Actual result:
There are many empty ratings listed on the first page of reviews, which are not very relevant for a user who wants to lean about other users' experience with the addon

Expected result:
We should provide a more relevant sorting for the addon reviews page, to bring forth reviews that offer some valuable information. Ideally (but more complicated), this should happen in the background, without asking the user to sort reviews manually

Notes:
- reproduced on all AMO servers with FF64, WIn10x64

![2019-01-16_15-10-01](https://user-images.githubusercontent.com/31961530/51251731-9fecbf80-19a2-11e9-8479-d3972d89cbe7.png)

**Comment by jvillalobos** [comment]
The future default sort for reviews will be the usefulness rating, as shown in https://github.com/mozilla/addons-frontend/issues/5462 and other issues, which should address this problem. We could add a checkbox to filter out empty ratings, but so far it hasn't been reported by many users, so I don't think it's worthwhile doing now.

Closing this, but we might want to revisit it if it becomes a recurring problem.
