### ISSUE TITLE
"Added to " messages are still visible after the add-on was added to a collection 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7412]
STR:
1. Load a detail page and add the add-on to an existing collection
2. Try to add it again to the same collection
3. Navigate away from the page then click View my collections
4. Open the collection where the previous add-on was added and click on the add-on 
5. Observe the detail page

Expected result:
"Added to" messages are not visible.

Actual result:
The messages are still displayed.

Notes:
This issue is also reproducible when making a search result for the add-on and the detail page is opened.
This issue is reproducible on AMO dev and AMO stage - FF64(Win10). 

![messages still displayed](https://user-images.githubusercontent.com/33448286/51256593-75086880-19ae-11e9-8520-1357f7081c8c.gif)

**Comment by AlexandraMoga** [comment]
Just noticed that this is in prod as well, so  not a new issue (not from this week at least)

**Comment by willdurand** [comment]
oh, maybe that was always there then...

**Comment by willdurand** [comment]
One way to fix the issue would be to reset the boolean props in the state on LOCATION_CHANGE.

Other than, I don't really know what to do..

**Comment by bobsilverberg** [comment]
That sounds reasonable.

**Comment by jvillalobos** [comment]
I don't see much use in showing the multiple "Added" messages, so I agree with @bobsilverberg that it's fine to change it in order to fix this issue.

**Comment by willdurand** [comment]
I think I can come up with a fix that keeps multiple messages.

**Comment by willdurand** [comment]
@ioanarusiczki please see too https://github.com/mozilla/addons-frontend/pull/7448#event-2086696033

**Comment by ioanarusiczki** [comment]
@willdurand @bobsilverberg I knew about both messages, I was not precise when I wrote this down.
It's only visible in the gif. 
So, the green message is no longer displayed and for the red one I filed it here https://github.com/mozilla/addons-frontend/issues/7476 There's another issue filed and similar with this one here https://github.com/mozilla/addons-frontend/issues/5722

Verified on AMO dev - FF64 (Win10) 

![no green](https://user-images.githubusercontent.com/33448286/51599559-8f8b9600-1f08-11e9-9428-fafec31743d2.gif)
