### ISSUE TITLE
Editing the featured-personas collection cannot be done using the front end link

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7424]
Followup for https://github.com/mozilla/addons-frontend/issues/7325

STR:
1. Log in with an `Admin`, `Admin:Curation` or with `Collections:Contribute` account and click the link https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-personas/

Expected result:
The user should be able to edit the collection.

Actual result:
The link returns a "Server Error" message.

Notes:
This issue is reproducible with FF64 (Win10). 

![server error](https://user-images.githubusercontent.com/33448286/51318435-00433600-1a63-11e9-913d-a8dee06bdab3.png)

**Comment by willdurand** [comment]
Oh right

**Comment by willdurand** [comment]
It is a `p2` because it potentially breaks BC.

**Comment by willdurand** [comment]
It looks like we don't need any special permissions, so maybe it affects all collection URLs with a `username` 😞

**Comment by willdurand** [comment]
I'd like to cherry-pick the patch for this issue because old collection URLs will be broken otherwise 😞 It is low-risk.

**Comment by ioanarusiczki** [comment]
Verified on AMO Dev - FF64 -Win10 Also I checked with a personal collection. 

![works now](https://user-images.githubusercontent.com/33448286/51325713-363de580-1a76-11e9-9ade-335524e7253d.gif)

![collection url fixed](https://user-images.githubusercontent.com/33448286/51325737-45249800-1a76-11e9-9890-d0c3b5f10f47.gif)

**Comment by ioanarusiczki** [comment]
Stage is fine too - FF64(Win10) 

![colectia asta](https://user-images.githubusercontent.com/33448286/51328120-5c19b900-1a7b-11e9-854c-49fcbd3302cb.gif)
