### ISSUE TITLE
Score filtering dropdown menu disappears after selecting  zero-count rating

### ISSUE THREAD

**Issue by mirefly** [mozilla/addons-frontend#7436]
Describe the problem and steps to reproduce it:
1. Load addons-dev.allizom.org
2. go to reviews page (addon or theme without too many reviews..)
3. In score filtering dropdown menu, select rating with 0 review

What happened?
The dropdown disappears.

What did you expect to happen?
The dropdown still be there so that I can select other ratings. And "There are no reviews" message is confusing when the dropdown disappears.  

![no_filter](https://user-images.githubusercontent.com/4984681/51433471-f3ac1280-1c07-11e9-91cf-52d6ef5e5b99.gif)

**Comment by ioanarusiczki** [comment]
Verified on AMO dev and AMO stage - FF64(win10 & android 8.0).

![filter button 0 reviews2](https://user-images.githubusercontent.com/33448286/51528963-73242680-1e40-11e9-9c7e-5a7b1225b0c7.gif)
