### ISSUE TITLE
Addons cannot be added for homepage shelf collections using the front end links

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7443]
I am transferring https://github.com/mozilla/addons-server/issues/10151  from server 
Now that https://github.com/mozilla/addons-frontend/issues/7424 was fixed 
as a  Followup for https://github.com/mozilla/addons-server/issues/9235 and https://github.com/mozilla/addons-frontend/issues/7325

STR:
1. Load AMO dev or AMO stage and with an admin account add themes using https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/featured-personas/
2. Go to AMO homepage and observe the Features Themes shelf

Expected result:
The added themes are available.

Actual result:
The themes are not visible on AMO. Themes will be displayed on AMO only after editing them (adding an order) from Admin Tools using https://addons-internal.dev.mozaws.net/en-US/admin/models/bandwagon/collection/2143965/change/ 

Notes:
This issue is reproducible on AMO dev and AMO stage with FF63(Win10) with admin and contributor accounts.

![themes not editable using the frontend](https://user-images.githubusercontent.com/33448286/51459552-9d52e700-1d61-11e9-9eff-30f70db7d8ee.gif)

**Comment by ioanarusiczki** [comment]
@willdurand I tested with an Admin account the shelf collections such as https://addons-dev.allizom.org/en-US/firefox/collections/4757633/youtube-boosters/?page=1&collection_sort=-added
https://addons-dev.allizom.org/en-US/firefox/collections/4757633/health-wellness/?page=1&collection_sort=-added
I can add extensions using the front end , but when I go to the homepage the item added is not displayed, strange that I removed a theme (Galaxy of Andromeda) and only after that the theme I added using the link (Eco theme) showed on AMO homepage.

For a better understanding please watch the gif below

![frontendlink not working](https://user-images.githubusercontent.com/33448286/51467025-3854bc80-1d74-11e9-8b48-4d671f620bc5.gif)

Reproducible on AMO dev and AMO stage - FF64 (W10)

**Comment by eviljeff** [comment]
It's certainly an addon-server bug - somewhere along the way an addon being added to a featured collection isn't ending up with the (memoized) list of featured (creatured, I think in this case) addons being updated.

**Comment by ioanarusiczki** [comment]
This is filed here https://github.com/mozilla/addons-server/issues/10151
