### ISSUE TITLE
A link added in "Leave a note" is interpreted as html 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7444]
STR:
1. Load AMO dev login and go to collections
2. Click on Leave a note for an add-on and add a link than save
3. Observe the link then click the Edit button 

Expected result:
The URL can be clicked - it's blue.

Actual result:
The URL cannot be clicked and after clicking Edit it has a html format.

Notes:
This issue is reproducible on AMO dev and AMO stage with FF64 (Win10). 
It is not reproducible when making a review, but links cannot be clicked there either. 

![html format](https://user-images.githubusercontent.com/33448286/51463540-19522c80-1d6c-11e9-91b3-a7e4c64c919c.gif)

**Comment by ioanarusiczki** [comment]
@willdurand Sorry, I'll mention from now on clearly if it's a regression or not. I realized that yesterday when I saw that is was also reproducible on stage. It's not a regression of the node10 issue but while investigating around it I found this one.

**Comment by mirefly** [comment]
Is it expected to show `<a>` tag in textarea after clicking edit? or just text (as shown below)?
![fix_notes_link](https://user-images.githubusercontent.com/4984681/51555904-f8eea480-1e35-11e9-86a1-bb610fe305fb.gif)

**Comment by willdurand** [comment]
@mirefly I believe we want to display the link as shown in the gif.

Isn't it a matter of white-listing the `a`?

**Comment by mirefly** [comment]
> Isn't it a matter of white-listing the `a`?

Yes. I made some change hoping to have it fixed. #7484

**Comment by willdurand** [comment]
Thanks @mirefly!

**Comment by ioanarusiczki** [comment]
@mirefly @willdurand 
I tried again, this is not reproducible on AMO dev anymore. - FF64 (Win10) 

![url is clickable](https://user-images.githubusercontent.com/33448286/51750644-5ba4a200-20bb-11e9-8dec-5b80c9b67f3e.gif)
