### ISSUE TITLE
AutoCloseBookmarkFolder Mozilla

### ISSUE THREAD

**Issue by eislexus99** [mozilla/addons-frontend#7447]
Hello
Where can I get the tool AutoCloseBookmarkFolder for Mozilla Firefox ESR
Find version 52.9?
I really need it.
Thanks for your help
Greetings Joseph

**Comment by willdurand** [comment]
Hi, sorry but if you can't find it on https://addons.mozilla.org, I don't think we can do anything.

**Comment by eislexus99** [comment]
Thanks for the help.
It's hard to believe that today it's still not possible to include a function like close all bookmarks in Firefox.
Up to version 58 or in ESR version up to 52.9 this function was available from the website http://www.sephiroth-j.de/1/ as AutoCloseBookmark PlugIn.
Now I have to look around for something else.
Thanks for your help.
Joseph
