### ISSUE TITLE
Broken layout for theme categories on AMO dev

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7450]
STR:
1. Load AMO dev and go to Themes tab - all categories page.
2. Click a category that contains featured themes - Abstract or Nature (on AMO dev)
3. Click the back button

Expected result:
No layout issues.

Actual result:
Featured themes and Top rated themes have layout issues.

Notes:
I could only reproduce this issue with the categories that contain featured themes and then the back button of the browser is clicked, not reproducible on AMO stage - FF64(Win10). 

![themes categories](https://user-images.githubusercontent.com/33448286/51474427-f6ce0c80-1d87-11e9-834b-afdd2852b754.gif)

**Comment by willdurand** [comment]
This could be related to https://github.com/mozilla/addons-frontend/pull/5225.

**Comment by willdurand** [comment]
There is something weird with the API response, but we can fix the visual issue on our side, so I'll do that and see why the API response is weird in a separate bug (if any).

**Comment by ioanarusiczki** [comment]
I can't reproduce it anymore. I tested this on AMO dev and AMO stage - FF64 (Win10). 

![no issues themes](https://user-images.githubusercontent.com/33448286/51543990-8e565c80-1e67-11e9-8c59-1153f4eab8bc.gif)
