### ISSUE TITLE
All reviews are displayed instead of filtered reviews when a permalink is clicked 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7451]
STR:
1. Load AMO dev and go an add-on detail page then click the Read all N reviews link
2. Filter by "Show only n reviews" 
3. Click then the timestamp of a review and observe the page

Expected results:
The clicked review is displayed on the top of the page and while the other reviews rated with the same number of stars are visible below.

Actual result:
Below the permalink - All reviews are visible.

Notes:
This issue is reproducible on AMO dev - FF64(Win10).

![clicking the permalink](https://user-images.githubusercontent.com/33448286/51477037-dc982c80-1d8f-11e9-9ed8-a276b2ce1150.gif)

**Comment by willdurand** [comment]
A permalink should not be parametrized with a score in my opinion, so the current behavior looks correct to me.

**Comment by kumar303** [comment]
Yes, I agree: losing the filter for a permalink is fine. Losing the filter does not break a user's workflow (well, none that I can think of).
