### ISSUE TITLE
Maybe the filter button should be present for a page with no reviews too

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7452]
STR:
1. Load AMO dev and go to an addon detail page then click Read all N reviews link
2. From the left side of the screen click a star rating with 0 reviews
3. See the right side of the screen

Expected result:
The "Show all reviews" filter button is available. 

Actual result:
"There are no reviews" message is displayed and filter button is not available.

Notes:
Reproducible on AMO dev with FF64(Win10). Also, it is reproducible when the ratings are clicked from the detail page (on the upper right corner). 

![no filter button](https://user-images.githubusercontent.com/33448286/51478014-d8214300-1d92-11e9-85cb-4241ac112cb8.gif)

**Comment by willdurand** [comment]
How is this different than #7436?

**Comment by ioanarusiczki** [comment]
@willdurand Someone's been more agile. Better twice than zero!

**Comment by willdurand** [comment]
@ioanarusiczki ah woops, sorry I thought you were actually the author of the other issue 😅
