### ISSUE TITLE
We should surface Static Themes in -dev (and local dev too)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7453]
Since #7419 is a wontfix, we should also change the -dev and local dev configs so that all environments have the same configuration.

**For QA:** the "Themes" menu on Android should be displayed and search should return both LWT and ST.

**Comment by ioanarusiczki** [comment]
@willdurand 

I verified this issue with FF66 (Android 8.0) 
- Themes tab: mixed themes , LW and Static themes.
- Categories: I see only static themes in the following categories:
Abstract
Foxkeh
Music
Nature
Other
Solid
- search results return both static and lw themes.

![themes on dev](https://user-images.githubusercontent.com/33448286/51552317-ffead680-1e78-11e9-9fa2-8a7e13025650.gif)

With FF64 static themes are not visible on Android (known issue), only LW themes are displayed.
