### ISSUE TITLE
There are no featured themes returned for Android

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7461]
Prerequisites: Use Firefox beta or Nightly 66, which should have support for static themes on Android

STR:
1. Load AMO stage for android - https://addons.allizom.org/en-US/android/
2. Perform an empty search
3. Filter results by Themes and Featured

Actual result:
There are no themes returned for the above filter criteria

Expected result:
Featured themes should also be returned on android

Notes:
On prod, featured themes are available for android, so I compared the requests made on stage vs prod:

- on stage the request is:
`https://addons.allizom.org/api/v4/addons/search/?app=android&appversion=66.0&featured=true&platform=windows&type=statictheme,persona&lang=en-US&wrap_outgoing_links=true`

- on prod the request is:
`https://addons.mozilla.org/api/v4/addons/search/?app=firefox&appversion=66.0&featured=true&platform=windows&type=persona&lang=en-US&wrap_outgoing_links=true`

It seems that for prod, the `app` param is set to `firefox`, while on stage it is set to `android`

To solve this, we could either continue to query results for `firefox` instead of `android`, and file a server issue to fix the `android` case.

![2019-01-22_12-01-08](https://user-images.githubusercontent.com/31961530/51531466-2b080280-1e46-11e9-97ca-83b3558d8531.gif)

**Comment by willdurand** [comment]
>  Featured themes should also be returned on android

It looks like there is no featured (static) themes for Android. I don't really know where these featured themes come from, but it could also be a data "bug".

**Comment by willdurand** [comment]
>  However, in this case there are results returned when the `app` is set to `firefox`, therefore I deduced that we should have the same results for `app` = `android` too.

There is only one featured extension for Android (adblock plus), so I would not be surprised if there was no featured theme for Android.

**Comment by AlexandraMoga** [comment]
@willdurand I think you might be right. I've checked  the featured personas collection in admin and it looks like is set to be compatible with Application = Firefox.

![image](https://user-images.githubusercontent.com/31961530/51535953-a8397480-1e52-11e9-9fd8-9b506ec48e0d.png)

This is a server issue then, so I'm going to refile it there.
