### ISSUE TITLE
S3.Translator a Firefox

### ISSUE THREAD

**Issue by salvapil** [mozilla/addons-frontend#7470]
https://support.mozilla.org/it/kb/aggiungere-funzione-traduzioni-firefox

https://addons.mozilla.org/it/firefox/addon/s3google-translator/

**Comment by jvillalobos** [comment]
We'll update the support page, thanks. Unfortunately, it's not uncommon for add-ons to be disabled by their developers or us, so some links will be broken from time to time.

**Comment by Astrulises** [comment]
ricardo300 is no longer available for firefox and is the best translator for firefox. I used it often but a year or more ago it is not available anymore. They could make it available again. please.

**Comment by salvapil** [comment]
Ciò  che non riesco a comprendere è il perchè  usando firefox sul  notebook
personale,  non esiste il traduttore S3.Translator,  mentre usando Firefox
sul PC del lavoro, esiste  ancora.
Qualcuno  sa  dirmi  il  perchè  e  darmi  una  risposta ?

Grazie.

Il giorno sab 20 lug 2019 alle ore 18:20 Astrulises <
notifications@github.com> ha scritto:
