### ISSUE TITLE
"This add-on already belongs to the collection" is still visible after the user navigates away from page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7476]
followup as requested here https://github.com/mozilla/addons-frontend/pull/7448

STR:
1. Load AMO dev, login, go to an add-on detail page and add an add-on to a collection
2. Try to add it again
3. Navigate away from the detail page, go to Collections click the the collection where the previous add-on was added and then click the add-on to see it's detail page again 
4. Copy paste the name of the add-on in the search bar, open the detail page from there

Expected result:
This add-on already belongs to the collection" is no longer displayed. 

Actual result:
"This add-on already belongs to the collection" is still available.

Notes:
Reproducible on all AMO servers - FF64 (Win10). 

![already belongs to the collection](https://user-images.githubusercontent.com/33448286/51598427-2c98ff80-1f06-11e9-8dc9-41e6d250259e.gif)

**Comment by willdurand** [comment]
This is very similar to #5722.

**Comment by ioanarusiczki** [comment]
@willdurand Lol, I just wanted to tag that too.

**Comment by willdurand** [comment]
@ioanarusiczki is this issue similar to https://github.com/mozilla/addons-frontend/issues/5813 by chance?
