### ISSUE TITLE
Cannot list/edit my add-ons

### ISSUE THREAD

**Issue by birdie-github** [mozilla/addons-frontend#7477]
What on Earth is going on?

https://addons.mozilla.org/en-US/firefox/collections/3011436/useful-firefox-extensions/ : **65 add-ons**

I can neither edit them, nor list them, as each attempt to go beyond the first page leads to:

https://addons.mozilla.org/en-US/firefox/collections/3011436/useful-firefox-extensions/?page=2&collection_sort=-added

> Oops! We can’t find that page
> 
> If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:
> 
>     The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
>     Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.
> 
> If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.
> 
> Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes.

**Have you completely deleted XUL add-ons, so that they cannot be even viewed any longer?**

**Comment by willdurand** [comment]
I believe most of the add-ons in this collection have been disabled but the "number of add-ons" has not been updated for some reasons. That's why we only see 16 add-ons instead of 65. The pagination thinks there are 65 add-ons though...

**Comment by birdie-github** [comment]
> I believe most of the add-ons in this collection have been disabled but the "number of add-ons" has not been updated for some reasons. That's why we only see 16 add-ons instead of 65. The pagination thinks there are 65 add-ons though...

Just a month ago all these add-ons were available. You haven't answered the question: have you purged XUL add-ons?

**Comment by willdurand** [comment]
> have you purged XUL add-ons?

Yep, I think so, see: https://blog.mozilla.org/addons/2018/08/21/timeline-for-disabling-legacy-firefox-add-ons/

**Comment by birdie-github** [comment]
This explains everything. 😢😢😢

Is there an archive available on the internet?

This bug report might be safely closed then.

**Comment by willdurand** [comment]
> Is there an archive available on the internet?

I think https://archive.org/web/ tried to backup everything before the removal of the legacy add-ons, but I don't know much about it to be honest.

**Comment by birdie-github** [comment]
https://github.com/JustOff/ca-archive

**Comment by grahamperrin** [comment]
### Classic Add-ons Archive

https://discourse.mozilla.org/t/how-to-list-legacy-add-ons/36709/2?u=grahamperrin

> … you’ll probably find that collections are out of scope.
