### ISSUE TITLE
Remove `enableFeatureStaticThemesForAndroid` feature flag

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7479]
The `enableFeatureStaticThemesForAndroid` feature flag can probably be removed after the LWT->ST migration has complete. This feature flag is enabled in all environments.

It means removing all the code related to this feature flag and showing ST for Android.

**Comment by tsl143** [comment]
Is this workable, or shall we wait for migration?

**Comment by willdurand** [comment]
> Is this workable, or shall we wait for migration?

You can work on it if you like :)

**Comment by tsl143** [comment]
Here it is :)
