### ISSUE TITLE
Add l10n facility for parsing accept-language headers

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#748]
Amo typically in lieu of the lang being in the URL uses an accept-language header to work out the right locale to use.

This needs to take into account the fact that the disco pane does not work on this basis (it works on the UI locale of the browser which is part of the disco pane's URL), any additions here need to be configurable so that the disco pane doesn't start processing accept-language headers and continues to use the accept-language header. This might work out OK assuming a URL takes precedence.

Relates to mozilla/addons#151

**Comment by muffinresearch** [comment]
QA notes: This change shouldn't impact the disco pane but it will be worth checking to make sure locales are still working as expected. 

The locale in the URL should take precedence over the locale being determined from accept-language headers but it would be good to check if you look at the page using a localized build (e.g. arabic) that should still see the RTL arabic build even if the accept-language headers are set to en-US for example (This add-on might help https://addons.mozilla.org/en-GB/firefox/addon/quick-accept-language-switc/ to save on the need to dive into the settings).

**Comment by ValentinaPC** [comment]
While checking around other languages (checked ar, de), I found a minor RTL layout issue in disco pane, as follows:
![2016-08-18_1618](https://cloud.githubusercontent.com/assets/15685960/17775682/0566b02a-6562-11e6-87d9-a14f99c74bf9.png)
 aka "with" between add-on name and author.

AND

"close" link in the wrong side:
![close](https://cloud.githubusercontent.com/assets/15685960/17776242/53289100-6564-11e6-8e0a-8284d08c6929.png)


Note: does not affect functionality.
Please let me know if we want to fix this or not.
Thanks.

**Comment by muffinresearch** [comment]
@ValentinaPC - Yep, the issue with "close" is unrelated to this issue - can you file a new one please?

The "with" string is coming from the API, but it looks like that's not been translated yet. See https://github.com/mozilla/addons-server/blob/master/locale/ar/LC_MESSAGES/django.po#L7123

**Comment by ValentinaPC** [comment]
For the first thing: consider it done.
For the second: is not the translation of the "with" text that bothers me, but its position. What do you think?

**Comment by muffinresearch** [comment]
I think if it's translated the word order would be right. The problem is partly because the "by" is translated but there's a bug for fixing that so the entire string is built up correctly [1]

[1] https://github.com/mozilla/addons-server/issues/3277

**Comment by ValentinaPC** [comment]
Based on the above comment, I'll mark this verified fixed.
