### ISSUE TITLE
(Disco-TAAR) Add messaging and button link to Learn More page 

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#7494]
Add a messaging box and button link (goes to a Learn More page) to Disco Pane when Disco-TAAR launches. This messaging box should only display when the user is receiving personalized recommendations. 

The 'Learn More' will link to:
https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/personalized-addons

![learnmore](https://user-images.githubusercontent.com/8496249/51763818-49f5d700-2088-11e9-8b7c-5fe851198041.png)

@muffinresearch

**Comment by muffinresearch** [comment]
This should be conditionally displayed on the basis of recommendations being present. The TAAR service is turned off in production currently, but the header is still being sent. 

For a more accurate way to trigger the message we really need to know from the API that there are recommendations present in the response. This should be possible by looking for at least one case where a recommendation is returned. This could be done by looking at the property `is_recommended` as long as at least one add-on has that, it should be ok to show the message.

**Comment by devaneymoz** [comment]
FYI I just updated the link to:

https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/personalized-addons

(The one I originally provided would just display the hidden version).

**Comment by muffinresearch** [comment]
> FYI I just updated the link to:
> 
> https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/personalized-addons
> 
> (The one I originally provided would just display the hidden version).

OK, so I think this means we additionally need to extract the variable data out from the disco pane URL and use it to build this link too.

**Comment by willdurand** [comment]
A link to https://support.mozilla.org/1/firefox/66.0/Darwin/en-US/personalized-addons redirects to https://support.mozilla.org/en-US/kb/personalized-extension-recommendations?as=u&utm_source=inproduct, which has no content. Is that intended?

**Comment by willdurand** [comment]
The mock-up/screenshot above does not match the current disco pane UI, so I adjusted things a bit. Preview of what it would look:

![screen shot 2019-01-28 at 11 10 39](https://user-images.githubusercontent.com/217628/51829198-5c247f00-22ed-11e9-9a7c-f3ac6c2e9d56.png)

**Comment by willdurand** [comment]
> A link to [support.mozilla.org/1/firefox/66.0/Darwin/en-US/personalized-addons](https://support.mozilla.org/1/firefox/66.0/Darwin/en-US/personalized-addons) redirects to [support.mozilla.org/en-US/kb/personalized-extension-recommendations?as=u&utm_source=inproduct](https://support.mozilla.org/en-US/kb/personalized-extension-recommendations?as=u&utm_source=inproduct), which has no content. Is that intended?

@devaneymoz ^

**Comment by devaneymoz** [comment]
@willdurand The page is currently 'hidden' until we push the feature live, so that might explain the empty content?

**Comment by willdurand** [comment]
@devaneymoz ah, maybe yes. Any chance to unhide this page? (it would be good for QA)

**Comment by devaneymoz** [comment]
@willdurand Okay the page has been un-hidden. I think we're okay to leave it un-hidden through launch.

**Comment by AlexandraMoga** [comment]
Filed https://github.com/mozilla/addons-frontend/issues/7520 as a follow up.
