### ISSUE TITLE
Scoutbook Feature Assistant Extension

### ISSUE THREAD

**Issue by amammothsparkler** [mozilla/addons-frontend#7496]
### Describe the problem and steps to reproduce it:

Please make this extension available for use.  Scoutbook is now a free BSA Advancement Platform.

**Comment by CA0258** [comment]
Closed with no comments and the extension is still not available. Why did you take this extension from the users?

**Comment by wagnerand** [comment]
The repository is about the underlying add-ons platform and its development. I recommend contacting the developer of that add-on for questions on availability.
