### ISSUE TITLE
[Feature-request] Add locale list to product page

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#7497]
It will be really nice to know which languages an extension supports.
reference - chrome store

<img width="928" alt="image" src="https://user-images.githubusercontent.com/5318732/51792816-2e3d1e80-21b7-11e9-9662-65fd00a11280.png">

**Comment by willdurand** [comment]
cc @jvillalobos

**Comment by jvillalobos** [comment]
I agree it would be nice to have, but it's also low priority. We would need to store the locales the latest XPI includes and then show them on the product page, probably in the More information box. /cc @atsay
