### ISSUE TITLE
Do not display the 0 users on the search tool list 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7500]
As a followup for https://github.com/mozilla/addons-frontend/issues/7316

STR:
1. Load AMO dev and go to the Search Tools page https://addons-dev.allizom.org/en-US/firefox/search-tools/
2. Observe the right side of the screen

Expected result:
The numbers of users (which is 0 in most of the cases) is not available.

Actual result:
The number of users is displayed.

Notes:
This issue is reproducible on all AMO servers with FF 64 (Win10). 

![search tools with no users](https://user-images.githubusercontent.com/33448286/51828004-50d45200-22f3-11e9-9828-f1b6be224cd1.gif)

**Comment by willdurand** [comment]
Please see #7464

**Comment by twisted-sres** [comment]
@ioanarusiczki I don't understand, please explain what do you mean
