### ISSUE TITLE
Do not display 0 users for the search tools from More add-ons section

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7510]
As a followup for https://github.com/mozilla/addons-frontend/issues/7316

STR:
1. Load AMO dev and go to a search tool's detail page that has a "More add-ons section" 
2. Observe the search tool displayed in that section

Expected result:
The "0 users " is not visible.

Actual result:
The search tool from the More add-ons section displays the "0 users".

Notes:
This issue is reproducible on all AMO servers with FF64 (Win10). 

![hide the users from more addons section](https://user-images.githubusercontent.com/33448286/51904607-bc87ef00-23c7-11e9-9520-ff53c8baadfd.png)

**Comment by tsl143** [comment]
on it.

**Comment by twisted-sres** [comment]
@tsl143  are you working on this? Or can I take this up?

**Comment by tsl143** [comment]
Okay please go ahead then @twisted-sres

**Comment by twisted-sres** [comment]
Thanks @tsl143 .
@ioanarusiczki  Can I take this up?

**Comment by willdurand** [comment]
>  @ioanarusiczki Can I take this up?

Yes but please no more than one issue in parallel :)

**Comment by twisted-sres** [comment]
Okay, now that you have merged my PR for that other issue, can I take this up?
I am not working on any other issue.

**Comment by tsl143** [comment]
Yes please start working on it :) 
@twisted-sres

**Comment by twisted-sres** [comment]
@ioanarusiczki when I have hidden the number of users for all the search tools, why is it still being displayed on More add-ons section?

**Comment by willdurand** [comment]
> @ioanarusiczki when I have hidden the number of users for all the search tools, why is it still being displayed on More add-ons section?

@twisted-sres this is a different component.

**Comment by ioanarusiczki** [comment]
@twisted-sres @willdurand 
I checked now on AMO dev - FF65 (Win10) and the number of users in the More section is no longer displayed.

![number of users not shown1](https://user-images.githubusercontent.com/33448286/52266375-eba9dd80-293e-11e9-9913-cbf9375a6d90.gif)

**Comment by twisted-sres** [comment]
@ioanarusiczki then I guess we should close this issue?

**Comment by willdurand** [comment]
ah yes, sorry for the confusion.
