### ISSUE TITLE
Text in the personalized recommendations info box from the Discovery Pane is hard to read

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7520]
Follow up for #7494 

STR:

1. Open about:addons on -dev with a profile that receives recommendations
2. Read the personalized recommendations message

Actual result:
The font size is too small, making the information a bit hard to read unless you zoom in

Expected result:
The font size should be increased (~14px?) both for the message and the 'Learn More' button

Notes:
- reproduced on AMO -dev with FF65, Win10x64

![image](https://user-images.githubusercontent.com/31961530/51978503-0984c780-2493-11e9-9d08-a284e86b141b.png)

**Comment by twisted-sres** [comment]
Hey, can I take this up?

**Comment by willdurand** [comment]
@twisted-sres no

**Comment by willdurand** [comment]
Proposal:

![screen shot 2019-01-30 at 15 33 24](https://user-images.githubusercontent.com/217628/51988202-663cae00-24a4-11e9-90ae-f918ca69c90f.png)

**Comment by AlexandraMoga** [comment]
That looks good to me

**Comment by pwalm** [comment]
We have to leave the message bar text [the prescribed size](https://design.firefox.com/photon/components/message-bars.html). This piece of UI must be consistent with across Firefox, so please revert it back to whatever the design system specifies.

**Comment by AlexandraMoga** [comment]
Ok then. I guess people with poorer eyesight (yours truly) will have to zoom in if they want to make reading more comfortable. 

@pwalm 
Btw, the UI specs mention that generic information messages should be dismissible. 
Do we need to apply this to the disco pane message?

![image](https://user-images.githubusercontent.com/31961530/52037710-6dad9700-2538-11e9-9146-064190401ce9.png)

**Comment by willdurand** [comment]
Ok, so the `font-size` should be `13px` so I'm going to change that in the disco app.

I don't think we want a close button though, because this notice should not be dismissed (it is a super important one).

**Comment by pwalm** [comment]
Correct @willdurand

**Comment by AlexandraMoga** [comment]
Text size increased to 13px

![image](https://user-images.githubusercontent.com/31961530/52125784-3ae9c880-2636-11e9-9420-5d532c44056f.png)

@willdurand should't the button font also be 13px in size? Currently it's at 11px.

**Comment by willdurand** [comment]
> @willdurand should't the button font also be 13px in size? Currently it's at 11px.

not according to the spec

**Comment by AlexandraMoga** [comment]
OK, this is verified fixed then.
