### ISSUE TITLE
Disco Pane layout issue when an unbroken string is typed in the summary field

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7521]
As a followup for https://github.com/mozilla/addons-frontend/issues/7502 this is an edge case reproducible as it follows:
STR:
1. On AMO dev, I went to Dev Hub and edited the name of the add-on (with 2 chars) and the summary field with 68 chars (as maximum allowed)
2. On AMO stage, I went to Dev Hub and edited the summary field with a long unbroken string (maximum 250 chars allowed)
3.  I added the extension in Disco Pane from django admin (this is reproducible when from django the Custom Description field is edited with a long unbroken string). 
4. Went to Disco Pane (about:addons)
 
Expected results:
The layout of Disco Pane is correct.

Actual results:
The +Install button and text is not aligned correctly.

Notes:
Reproducible on FF64, FF67 (Win10). 

![ff67](https://user-images.githubusercontent.com/33448286/51982163-dbf14b80-249d-11e9-8ee1-680bb9853b5b.png)

![ff64](https://user-images.githubusercontent.com/33448286/51982172-e27fc300-249d-11e9-841d-fc20d26ebfbf.png)

**Comment by willdurand** [comment]
@ioanarusiczki I am sorry but I cannot really reproduce. Could you add these addons in -dev so that I can see them? Is it working with FF65 or Nightly?

**Comment by ioanarusiczki** [comment]
@willdurand I added a sample on disco pane -dev - the first position. I can reproduce it with both FF65 and FF67 (Win10).

**Comment by ioanarusiczki** [comment]
@willdurand I cannot reproduce this anymore on AMO dev with FF65 or FF67 (Win10). Once it goes on Stage I will do a re-check. 

![ff76 with amo dev](https://user-images.githubusercontent.com/33448286/52481596-9b898000-2bb7-11e9-81f6-c49ccae55ccd.png)

**Comment by ioanarusiczki** [comment]
Verified on AMO stage with FF65 (Win10). 

![amo stage](https://user-images.githubusercontent.com/33448286/52715350-ebe05380-2fa4-11e9-8ef2-617d5e8e6aa8.png)
