### ISSUE TITLE
Amazon Publisher Studio Firefox Add On missing from Mozilla's dir

### ISSUE THREAD

**Issue by bocatek** [mozilla/addons-frontend#7523]
### Describe the problem and steps to reproduce it:
https://affiliate-program.amazon.com/home/tools/pubstudio?ac-ms-src=ac-nav

I'm logged into Amazon Associates page,Publish Studio Management
[SCRN_GIT_AMAZON-PUBLISHER-STUDIO.pdf](https://github.com/mozilla/addons-frontend/files/2813553/SCRN_GIT_AMAZON-PUBLISHER-STUDIO.pdf)

, Amazon has a button to install Firefox Add on--->https://affiliate-program.amazon.com/home/tools/pubstudio?ac-ms-src=ac-nav
### What happened?
Firefox add on doesn't exist.
### What did you expect to happen?
Installation of Add-on
### Anything else we should know?
Nope, lmk if you need my login info to test, if its just me.

**Comment by wagnerand** [comment]
This repository is about the add-ons platform, not individual add-ons. I recommend you contact the developer about the availability of their add-on.
