### ISSUE TITLE
Hide SDK notifications

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7525]
See also: https://github.com/mozilla/addons/issues/884

**For QA:** this issue is about hiding the "SDK" notifications in the edit page of a user profile. There are 2 SDK notifications to hide. It should not cause any other issues when updating any data of a profile, including notifications of course.

**Comment by willdurand** [comment]
>     * I've noticed that using keyboard navigation, the options from Notifications cannot be checked/unchecked using Enter key. It will directly update the profile and then display the View profile page. It is reproducible on AMO prod too.  Should I file an issue for this?

No, I think we check/uncheck those inputs with the <kdb>space</kdb>, no?

**Comment by ioanarusiczki** [comment]
@willdurand Ups! It works with <kbd>space</kbd> AMO dev, AMo prod - FF65

![space navigation1](https://user-images.githubusercontent.com/33448286/52264057-7091f880-2939-11e9-8d2e-6f2444749507.gif)
