### ISSUE TITLE
Transfer to link http://seleniumbuilder.github.io/se-builder/ and give error in this page https://addons.mozilla.org/en-GB/firefox/addon/selenium-builder/ 

### ISSUE THREAD

**Issue by mapekova** [mozilla/addons-frontend#7528]
### Describe the problem and steps to reproduce it:
Transfer to link http://seleniumbuilder.github.io/se-builder/ and give error in this page https://addons.mozilla.org/en-GB/firefox/addon/selenium-builder/

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
