### ISSUE TITLE
Cancel and Save buttons in the add/edit collection forms are too close together in some locales on mobile

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7529]
STR:

1. Log in to AMO on a mobile device, or use the responsive design mode
2. Set your locale to `fr`
3. Observe the Cancel and Save buttons

Actual result:
Cancel and Save buttons are stuck together 

Expected result:
There is enough spacing between the Cancel and Save buttons

Notes:
- reproduced on all AMO servers with FF65, Win10x64 and Android 8.0
- the issue also applies to the Edit collection form

[1] mobile view - Create collection

![image](https://user-images.githubusercontent.com/31961530/52116204-411d7c00-2619-11e9-88c0-e7626c970aee.png)

[2] ~850px width - Create collection
![image](https://user-images.githubusercontent.com/31961530/52116232-509cc500-2619-11e9-8b71-1283baa9bcf2.png)

[3] ~850px width - Edit collection
![image](https://user-images.githubusercontent.com/31961530/52116239-55617900-2619-11e9-8752-f4fdc1544909.png)

**Comment by willdurand** [comment]
So the new UI should look like this:

![ezgif com-resize](https://user-images.githubusercontent.com/217628/52478003-35473200-2ba4-11e9-8a92-50735798a2c8.gif)

**Comment by AlexandraMoga** [comment]
Verified fixed on AMO -dev with FF65, WIn10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/52485038-87964c00-2bc0-11e9-842a-2cf96e5d8d72.png)

![image](https://user-images.githubusercontent.com/31961530/52485319-43577b80-2bc1-11e9-8533-2274b62dbbc6.png)
