### ISSUE TITLE
Incomplete version history (25 versions) for some add-ons, pagination navigation missing?

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#7533]
For example, https://addons.mozilla.org/en-US/firefox/addon/noscript/versions/ (captured, <https://web.archive.org/web/20190203063507/https://addons.mozilla.org/en-US/firefox/addon/noscript/versions/>): 

- 25 versions
- at the foot of the (only) page, 

> Version 10.1.8.7
> Released Jul 16, 2018 - 411.61 KB
> Works with android 59.0 and later, firefox 59.0 and later

Compare with <https://web.archive.org/web/20181002111533/https://addons.mozilla.org/en-US/firefox/addon/noscript/versions/?page=2>, which includes: 

> Version 10.1.1
> Released Nov. 20, 2017 • 570.7 KiB 
> Works with Firefox 57.0 and later

Please: is this a bug, should there be navigation to (at least) page 2 at the foot of <https://addons.mozilla.org/addon/noscript/versions/>?

----

I wondered whether the developer (or Mozilla) had intentionally removed n versions from history, leaving a neat number 25 on the page … http://www-sop.inria.fr/members/Doliere.Some/papers/empoweb.pdf comes to mind but I don't see NoScript tabled on the last page.

**Comment by AlexandraMoga** [comment]
What's happening here is that our API response is limited to 25 results per page.

As an example, for https://addons.mozilla.org/api/v4/addons/addon/ublock-origin/versions/ - there should be 39 versions available but the frontend will display only the first page of results (25): https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/

**Comment by grahamperrin** [comment]
Thanks for confirmation. 

An example workaround, lazily reusing the 20181002 date: 

https://web.archive.org/web/20181002/https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/?page=2

– and then a captured `.xpi` may be installed by opening a **new tab** for buttoned links such as **+ Add to Firefox**. 

(Not all archived pages are so lucky. https://www.reddit.com/r/waterfox/comments/adznrq/-/efjnutw/ notes inexplicable disappearance of a page from the Wayback Machine.)

**Comment by bobsilverberg** [comment]
When implementing the new page it was decided that showing the most recent 25 versions, and not having any pagination, was acceptable.

**Comment by grahamperrin** [comment]
WTF?
