### ISSUE TITLE
The all versions page does not let you page through all versions

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7542]
### Describe the problem and steps to reproduce it:

Go to an all versions page (https://github.com/mozilla/addons-frontend/issues/2770) for an add-on with more than 25 versions. Example: https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/versions/

### What happened?

You only see 25 versions.

### What did you expect to happen?

You should see pagination links so you can load more pages and eventually see all versions.

**Comment by grahamperrin** [comment]
https://github.com/mozilla/addons-frontend/issues/7533#issuecomment-460242461

**Comment by grahamperrin** [comment]
### Release note history

https://addons.mozilla.org/addon/enhancer-for-youtube/versions (above) is exemplary of a developer that does not provide expected information. 

A better example: 

- https://addons.mozilla.org/addon/ublock-origin/versions/ ([captured (en-GB)](https://web.archive.org/web/20190206055405/https://addons.mozilla.org/en-GB/firefox/addon/ublock-origin/versions/))

Pages 2 and 3 of release notes in the Wayback Machine, no longer available from Mozilla: 

- https://web.archive.org/web/20181003012550/https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/?page=2
- https://web.archive.org/web/20181003012552/https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/versions/?page=3

**Comment by bobsilverberg** [comment]
It was decided when implementing this page that we would not be supporting pagination and only display the 25 most recent versions. As was discussed in IRC around this issue, the API is available for anyone who really needs to retrieve information for versions older than that.

**Comment by kumar303** [comment]
Also, the legacy site never implemented pages for old versions correctly correctly due to limitations in the data.

**Comment by grahamperrin** [comment]
Anyone, please: 

> … If we can be given a real-world  example of how to use the API – resulting in an AMO link to the required `.xpi` – then future situations such as might become less complicated for people (like me) who are not developers …
