### ISSUE TITLE
14 Feb homepage programming updates

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#7543]
For the **Thursday, 14 February** push, please update homepage programming as detailed [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch

**Comment by ioanarusiczki** [comment]
@willdurand Looks good on AMO dev with FF65 (Win10). Final validation is on AMO prod on Thursday.

![checking the updates](https://user-images.githubusercontent.com/33448286/52485394-6eda6600-2bc1-11e9-87e8-f7c30f6044eb.gif)

**Comment by ioanarusiczki** [comment]
Verified on AMO prod - FF65 (Win10).
