### ISSUE TITLE
The legacy site is displayed if the page is refreshed after a search query

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7547]
STR:

1. Open AMO -dev homepage
2. Perform a blank search
3. Refresh the search results page

Actual result:
The legacy site is displayed

Expected result:
The new frontend is displayed

Notes:
- reproduced on AMO -dev with FF65, Win10x64
- I could not reproduce with other pages, just with search results

![2019-02-06_10-58-30](https://user-images.githubusercontent.com/31961530/52330553-5837e180-29fe-11e9-9ba9-243f58809f05.gif)

**Comment by willdurand** [comment]
@AlexandraMoga I believe it is a regression cause by https://github.com/mozilla/addons-server/issues/10428#issuecomment-460881053, could you please move this issue to addons-server? Thanks!

**Comment by AlexandraMoga** [comment]
@willdurand  Thanks for the heads up.

Filed https://github.com/mozilla/addons-server/issues/10608
