### ISSUE TITLE
Bad redirect for my addon from addons.thunderbird.net?

### ISSUE THREAD

**Issue by tjeb** [mozilla/addons-frontend#7548]
### Describe the problem and steps to reproduce it:

My thunderbird addon on addons.thunderbird.net is listed, but clicking on it results in a wrong redirect to a 'not available' page.

### What happened?

Clicked on the listing of my addon at https://addons.thunderbird.net/en-US/thunderbird/user/tjebbe/ (linkint to https://addons.thunderbird.net/en-US/thunderbird/addon/mailbox-alert/?src=userprofile). Got redirected to https://addons.mozilla.org/en-US/firefox/addon/mailbox-alert/ (not available).

### What did you expect to happen?

To get to the download page, and not redirected not a 'not available' message containing firefox in the URL.

### Anything else we should know?

IIRC it worked fine when the new version was reviewed and published about a month ago

**Comment by willdurand** [comment]
I am sorry but we don't support addons.thunderbird.net (ATN) here, you should contact the people behind ATN.
