### ISSUE TITLE
Update static theme size for Discovery Pane

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7553]
Static themes now have a different size, as of https://github.com/mozilla/addons-server/issues/9419

This issue is about updating the Discovery Pane to display themes in the new size. AMO was updated to display the new size in https://github.com/mozilla/addons-frontend/issues/6507

**Comment by kumar303** [comment]
I should point out that I'm not sure if Disco Pane needs to use this new size or not. If not, we can close this issue as wontfix.

**Comment by jvillalobos** [comment]
@atsay and @brassy should chime in. The new dimensions were introduced in mozilla/addons-server#9419 and come from the content optimization project. We need to figure out if/when it should be used on Disco Pane.

**Comment by eviljeff** [comment]
Unless there's a good reason why we can't have one size of theme preview in all the places, lets have one size of theme preview in all the places.

**Comment by willdurand** [comment]
The disco pane max width is 680px to match the other about pages. There is no need to use larger images (which would be scaled down). Maybe the "disco pane in the client" project will change that.

**Comment by atsay** [comment]
Let's shelve this for now as low priority.
