### ISSUE TITLE
AMO displays Mobile version layout on older Firefox Browsers

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#7554]
### Describe the problem and steps to reproduce it:

Using FF 48 for Mac to visit AMO shows the mobile layout instead of the desktop layout that takes advantage of screen space.

### What happened?
Shows AMO in long form, with no framing.

### What did you expect to happen?

To apply desktop layout framing to maximize usage of screen.

**Comment by jvillalobos** [comment]
AMO officially supports versions from the latest ESR (version 60) and up. I believe that what you're seeing is the fallback layout for browsers that don't support CSS Grid.

**Comment by smayer97** [comment]
Ok. Thx for pointing this out.

For those interested, CSS grid support for Firefox is turned in v52+ on by default (and in Chrome v57+, Safari 10.1+, etc.; see complete list here, slide 30: 
https://www.slideshare.net/jen4web/css-grid-finally-true-layout-arrives-version-5

or click
https://www.google.com/url?sa=i&source=imgres&cd=&ved=2ahUKEwi4gqrcm6jgAhWMoYMKHdxKBYAQjRx6BAgBEAU&url=https%3A%2F%2Fwww.slideshare.net%2Fjen4web%2Fcss-grid-finally-true-layout-arrives-version-5&psig=AOvVaw3xrQCfO2Qf1b7kb0Xl-Lqj&ust=1549580600962608

For older versions, you can turn on support manually. Check out this info for guidance:
https://caniuse.com/#feat=css-grid
