### ISSUE TITLE
AMO results = 0 when selecting OS = All

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#7555]
### Describe the problem and steps to reproduce it:

When visiting AMO https://addons.mozilla.org/en-US/firefox/search/, if switch operating system to All, results found = 0. Refreshing page (even forced refresh, does NOT update the results; results remain at 0. 

Switching to any other OS pulls up results correctly. Then switching to All sometimes cause the All setting to pull up results, but most times still comes up = 0. 

### What did you expect to happen?

Switching OS = All should pull up matching results each time.

### Anything else we should know?

Currently using FF v48 for Mac if that matters.

**Comment by jvillalobos** [comment]
The search string is empty, so there really aren't any relevant results. However, it may be more useful (and consistent) to show all results, like it's done when the OS are applied. I'm not sure if we intentionally decided to implement it this way, I seem to recall a discussion about it on an old issue.

**Comment by smayer97** [comment]
But the search string is empty even when you select a specific OS and yet results show up there. 

So my feedback is that I agree that it is more consistent to have it behave like the other selections, and it is more intuitive to always have results show.

**Comment by willdurand** [comment]
> But the search string is empty even when you select a specific OS and yet results show up there.

That's what I don't understand either but I also barely remember a decision about that to avoid returning all the results. /cc @diox maybe?

**Comment by diox** [comment]
I don't recall any decision to do that, and FWIW the API shouldn't - and doesn't in my experience - behave like this.
```
curl -s https://addons.mozilla.org/api/v4/addons/search/\?platform\=all\&app\=firefox\&appversion\=65.0 | jq .count
464881
```

**Comment by willdurand** [comment]
This is actually: https://github.com/mozilla/addons-frontend/issues/6117
