### ISSUE TITLE
Locale missing in language tools page, but available in the underlying API

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-frontend#7556]
We recently fixed an issue with 6 locales (missing target_locale attribute). 5 of them are now correctly displayed, but one is missing (`gn`, Guaraní).

Page: https://addons.mozilla.org/firefox/language-tools/

If you inspect the source, the locale is there, and it's also in the API response, but it's not displayed on the page for some reasons.

```
"690253": {
	"id": 690253,
	"default_locale": "en-US",
	"guid": "langpack-gn@firefox.mozilla.org",
	"name": "Guarani (Paraguay) Language Pack",
	"slug": "guarani-paraguay-language-pack",
	"target_locale": "gn",
	"type": "language",
	"url": "https:\u002F\u002Faddons.mozilla.org\u002Fit\u002Ffirefox\u002Faddon\u002Fguarani-paraguay-language-pack\u002F"
},
```

**Comment by flodolo** [comment]
I think that happens because we don't know anything about the `gn` locale here
https://github.com/mozilla/addons-frontend/blob/dab0639006f9a5c9b2e42e00f534f5b00edaf3ab/src/core/languages.js

And it's filtered out here
https://github.com/mozilla/addons-frontend/blob/dab0639006f9a5c9b2e42e00f534f5b00edaf3ab/src/amo/pages/LanguageTools/index.js#L41

It would be nice to double check if there are other locales excluded.

**Comment by flodolo** [comment]
It seems like `gn` is the only locale missing

```
    "af", "ach", "ak", "am-et", "an", "ar", "as", "ast", "az", "be", "bg",
    "bm", "bn-BD", "bn-IN", "br", "brx", "bs", "ca", "ca-valencia", "cak",
    "cs", "csb", "cy", "da", "dbg", "de", "de-AT", "de-CH", "de-DE", "dsb",
    "ee", "el", "en-AU", "en-CA", "en-GB", "en-NZ", "en-US", "en-ZA", "eo",
    "es", "es-AR", "es-CL", "es-ES", "es-MX", "et", "eu", "fa", "fa-IR", "ff",
    "fi", "fj-FJ", "fr", "fur-IT", "fy-NL", "ga", "ga-IE", "gd", "gl", "gu",
    "gu-IN", "ha", "he", "hi", "hi-IN", "hr", "hsb", "hu", "hy-AM", "ia", "id",
    "ig", "is", "it", "ja", "ja-JP-mac", "ka", "kab", "kk", "km", "kn", "ko",
    "kok", "ku", "ks", "la", "lg", "lij", "ln", "lo", "lt", "lv", "mai", "mg",
    "mi", "mk", "ml", "mn", "mr", "ms", "my", "nb-NO", "ne-NP", "nn-NO", "nl",
    "nr", "nso", "oc", "or", "pa", "pa-IN", "pl", "pt-BR", "pt-PT", "ro", "rm",
    "ru", "rw", "sa", "sat", "sah", "si", "sk", "sl", "son", "sq", "sr",
    "sr-Cyrl", "sr-Latn", "ss", "st", "sv-SE", "sw", "ta", "ta-IN", "ta-LK",
    "te", "th", "tl", "tn", "tr", "ts", "tsz", "tt-RU", "uk", "ur", "uz", "ve",
    "vi", "wo", "x-testing", "xh", "yo", "zh-CN", "zh-TW", "zu",
```

**Comment by ioanarusiczki** [comment]
@willdurand 
On AMO dev with Page Source I see the lang packs presence 
 `"502959":{"id":502959,"default_locale":"en-US","guid":"will@drnd.me","name":"Guarani (Paraguay) Language Pack","slug":"guarani-paraguay-lang-pack","target_locale":"gn","type":"language","url":"https:\u002F\u002Faddons-dev.allizom.org\u002Fen-US\u002Ffirefox\u002Faddon\u002Fguarani-paraguay-lang-pack\u002F"}}}`

And I see the lang pack on the page too 
![guarani lang pack](https://user-images.githubusercontent.com/33448286/52703843-ed4f5300-2f87-11e9-9664-96c4f18892e4.gif)

I think that it should be confirmed for prod too once the fix lands, to make sure it's all good.

**Comment by ioanarusiczki** [comment]
It is available on AMO prod - FF65(Win10).

![guarani lang pack on prod](https://user-images.githubusercontent.com/33448286/52850400-11dc3400-311c-11e9-9352-63918d39e5dc.gif)
