### ISSUE TITLE
1Password site links to non-existing extention for Linux platform

### ISSUE THREAD

**Issue by PombeirP** [mozilla/addons-frontend#7559]
### What happened?

I got a warning page telling me that the extension no longer existed.

### What did you expect to happen?

Being able to download the 1Password X extension.

### Anything else we should know?

https://1password.com/downloads/linux/

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons. Please contact the author of the add-on for questions about its availability.
