### ISSUE TITLE
1Password site links to non-existing extention for Firefox

### ISSUE THREAD

**Issue by AlanCurran** [mozilla/addons-frontend#7563]
### Describe the problem and steps to reproduce it:
The 1Password.com site directs users to the Mozilla add-on store for it's browser extention "1Password":

https://1password.com/downloads/windows/#browsers/

However, when following the link, it goes to a dead page. 

### What happened?

The browser extention appears to have been removed from the add-on store. 

### What did you expect to happen?

Find the extention in the add-on store

**Comment by mamhoff** [comment]
:+1: This makes my weekend difficult as I cannot install 1Password on my family's computers.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
