### ISSUE TITLE
S3.translator

### ISSUE THREAD

**Issue by JorgeM12** [mozilla/addons-frontend#7564]
my problem is that this extension basically translates what page and what text you have selected
and I do not know why it does not appear in your extensions, I do not know if you could provide me with a link to install it, I used to have it in my firefox but I had to delete all my mozilla firefox due to personal problems and I do not know if you can provide me with a link to install it please, I ask you

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
