### ISSUE TITLE
ExpressVPN Firefox Browser Extension App Missing

### ISSUE THREAD

**Issue by farley0422** [mozilla/addons-frontend#7565]
### What did you expect to happen? I expected it the ExpressVPN extension app to appear as usual.

![screen capture 2019-02-09 08-34-39](https://user-images.githubusercontent.com/47475233/52520198-a985e200-2c45-11e9-88f2-1724419bd12d.png)

**Comment by GrayCatCode** [comment]
I was about to open another issue on this exact topic, you beat me to it. ;)

**Comment by GrayCatCode** [comment]
Having the same issue.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
