### ISSUE TITLE
TAARDIS Conditionally return 400 based on FF version

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#7573]
As per the email from durst:

> we should only return TAAR results for clients that are 65.0.1 or greater

The API responses should only return recommendations from FF 65.0.1 onwards to avoid the clients that haven't yet upgraded to 65.0.1 getting recommendations.

**Comment by muffinresearch** [comment]
The client ID should be withheld from being sent if the version isn't greater than or equal to 65.0.1

**Comment by willdurand** [comment]
@muffinresearch so there are 2 ways to fix that: either we rely on the version in the URL or we use the user-agent metadata. I'd go for the version in the URL but what should we do? We could also check both 🤷‍♂️

**Comment by muffinresearch** [comment]
I'd use the URL as that's more likely to be right since that's set directly by FF.

**Comment by AlexandraMoga** [comment]
1. https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/65.0.1/WINNT/normal
 Moz-Client-Id is sent with the request header -> recommendations are received

2. https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/67.0a1/WINNT/normal
  Moz-Client-Id is sent with the request header -> recommendations are received

3. https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/64.0/WINNT/normal
   Moz-Client-Id NOT sent with the request header -> no recommendations are received

4. https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/60.5.0/WINNT/normal
 Moz-Client-Id NOT sent with the request header -> no recommendations are received

@willdurand  here is the result when using FF 65.0:
https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/65.0/WINNT/normal
 Moz-Client-Id **is sent** with the request header -> NO recommendations are received

From your QA instructions, I understood that we should not send the client ID at all if the FF version is <65.0.1. It's possible that we're seeing a boundary issue with FF 65.0?

**Comment by willdurand** [comment]
> @willdurand here is the result when using FF 65.0:
> [discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/65.0/WINNT/normal](https://discovery.addons-dev.allizom.org/en-US/firefox/discovery/pane/65.0/WINNT/normal)
> Moz-Client-Id **is sent** with the request header -> NO recommendations are received
> 
> From your QA instructions, I understood that we should not send the client ID at all if the FF version is <65.0.1. It's possible that we're seeing a boundary issue with FF 65.0?

It is sent by the browser but not actually sent to the API, right? If there are no recommendations, that's good. FF 65.0 sends the client ID as a request header but the disco app should not forward it to the API (which would return recommended results).

I think we're good to go.

**Comment by AlexandraMoga** [comment]
That's right. No recommendations are received back in Discovery Pane. 
That's clarified then, so I'm marking the issue as verified fixed on AMO -dev, with WIn10x64, FF 60.5.0esr , 64.0, 65.0, 65.0.1, 66.0b5, 67.0a1
