### ISSUE TITLE
Choose Language Background

### ISSUE THREAD

**Issue by suhailsinghbains** [mozilla/addons-frontend#7579]
Should be Fixed in #3205
### What happened?
Choose Language Background is black instead of White. I had applied a Theme, even if I remove it, the issue persists.
### What did you expect to happen?
Background is White
### Anything else we should know?
Version 65.0.(64-bit)

![screenshot from 2019-02-12 11-36-28](https://user-images.githubusercontent.com/10033914/52615391-0dfda700-2ebb-11e9-8f9d-4d309d1232e1.png)

**Comment by willdurand** [comment]
I guess we could fix the style of this select.

**Comment by suhailsinghbains** [comment]
Hi,
Can I please work on this?

**Comment by caitmuenster** [comment]
Hey @suhailsinghbains, could you give us the steps to reproduce this issue and let us know what theme you were using?

**Comment by suhailsinghbains** [comment]
When I filed this issue, I was using Elementary OS 5.0 Juno.
It makes all the select tags go dark with text in white in every website, but, in this and [this footer](https://www.mozilla.org/en-US/) I was getting [this](https://user-images.githubusercontent.com/10033914/52615391-0dfda700-2ebb-11e9-8f9d-4d309d1232e1.png)

I had switched to Manjaro XFCE4 I am getting similar issue
![image](https://user-images.githubusercontent.com/10033914/53109394-ca600880-355e-11e9-86a0-93e1eca6318c.png)

Regarding themes: I used Arc Darker Theme, FF Default Theme, FF Light Theme, FF Dark Theme. It is reproducible on all.

**Comment by suhailsinghbains** [comment]
Hi @willdurand 
Please add label state: verified
![image](https://user-images.githubusercontent.com/10033914/53416455-91f67980-39f9-11e9-97f4-50190458488e.png)
As shown [here](https://addons-dev.allizom.org/en-US/firefox/)

**Comment by willdurand** [comment]
QA people have to verify it, not me :)

**Comment by ioanarusiczki** [comment]
@willdurand  

I verified this on Win10, Ubuntu 12.0.4, Mac OS X.0.14.1 and did not find regressions. The background is white and stays this way even if a dark theme is installed.

If any further problems are encountered please let us know @suhailsinghbains 

![change language](https://user-images.githubusercontent.com/33448286/53497216-5f598900-3aac-11e9-8cac-60459c00cafe.png)
