### ISSUE TITLE
Incorrect text wrapping on an add-on details card in Disco Pane

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7580]
Prerequisites:
extensions.webservice.discoverURL pref points to the -dev server in about:config

STR:

1. Open your Firefox browser
2. Navigate to about:addons
3. Observe the description for any of the listed add-ons - i.e Awesome Screenshot Plus

Actual result:
Text for the description and custom heading are not correctly wrapped

Expected result:
There are no text layout issues in the add-on cards

Notes:
- reproduced on AMO -dev with FF65, WIn10x64

![image](https://user-images.githubusercontent.com/31961530/52629131-b878c880-2ec1-11e9-87ff-e33f7b683372.png)

**Comment by willdurand** [comment]
ah well, I guess that's because I used `word-break: break-all` 😞

**Comment by suhailsinghbains** [comment]
Hi, Can I please work on this?

**Comment by AlexandraMoga** [comment]
This is fixed now on AMO -dev

![image](https://user-images.githubusercontent.com/31961530/52865371-2d0f6980-3145-11e9-90a7-28ca8dd6f34d.png)

However, it seems we are running in circles a bit, because this fix reintroduced the issue mentioned in #7521 

![image](https://user-images.githubusercontent.com/31961530/52865452-516b4600-3145-11e9-90a0-733279c75a6d.png)

@willdurand I favor keeping this fix (i.e #7582), because it addresses a more user facing issue. Having an unbroken string in disco pane is less likely to happen in prod, therefore I'd treat that problem with a lower priority, but it's your call in the end.

**Comment by willdurand** [comment]
> @willdurand I favor keeping this fix (i.e #7582), because it addresses a more user facing issue. Having an unbroken string in disco pane is less likely to happen in prod, therefore I'd treat that problem with a lower priority, but it's your call in the end.

ok that works for me

**Comment by AlexandraMoga** [comment]
@willdurand should https://github.com/mozilla/addons-frontend/pull/7600 have fixed the long string issue?
I am still reproducing, hence the double check.

**Comment by willdurand** [comment]
Another patch has been merged and should fix everything.

**Comment by AlexandraMoga** [comment]
This looks fixed now:

![image](https://user-images.githubusercontent.com/31961530/53323040-c1b45d00-38e5-11e9-8338-f4412702ad26.png)
