### ISSUE TITLE
Firefox Add-ons feilrapport for Remember Reward-jegeren

### ISSUE THREAD

**Issue by barrymcvey** [mozilla/addons-frontend#7583]
### Describe the problem and steps to reproduce it:

I was sent to the Firefox Add-ons feilrapport skjerm på GitHub (Svensk) etter jeg forsøkt nedlasting av Remember Reward-jegeren for Firefox.

Jeg er på en Dell XPS PC og kjører Linux Mint 19.0.

Takk
Barry

Se https://addons.mozilla.org/sv-SE/firefox/addon/re-member-reward/?src=ss

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.

**Comment by barrymcvey** [comment]
Will do - thx.
Barry

Barry McVey
mob +47 90 82 60 50

On 13 Feb 2019, at 11:49, Andreas Wagner <notifications@github.com<mailto:notifications@github.com>> wrote:


This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
