### ISSUE TITLE
The autocomplete api is returning a 404 when searching for themes inside a specific category

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7584]
Follow up for #7459 

STR:

1. Load AMO homepage on an Andoid device 
2. Navigate to Themes and open a Category of your choice
3. Click on See More top rated themes - https://addons.mozilla.org/en-US/android/search/?category=abstract&sort=rating&type=statictheme%2Cpersona
4. Enter a search term to be found inside this category

Actual result:
An error message is displayed which points that the request is using an invalid combination of `app`, `type` and `category` parameters

Expected result:
Search suggestions are loaded

Notes:
- I believe this issue is happening because the query to the autocomplete API includes both `statictheme` and `persona` for  `type`
```
https://addons.mozilla.org/api/v4/addons/autocomplete/?app=android&appversion=65.0&category=abstract&q=color&sort=rating&type=statictheme,persona&lang=en-US&wrap_outgoing_links=true
```
By comparison, the following query (which excludes `persona` from `type`) will return resu;lts
```
https://addons.mozilla.org/api/v4/addons/autocomplete/?app=android&appversion=65.0&category=abstract&q=color&sort=rating&type=statictheme&lang=en-US&wrap_outgoing_links=true
```

- when #7459 was fixed, I believe that `persona` was completely excluded from the `type` query
- reproduced on all AMO servers, PROD included, with FF65, Android 8.0

![2019-02-13_13-30-11](https://user-images.githubusercontent.com/31961530/52709690-1ecf1b00-2f96-11e9-8fb1-37168e27a580.gif)

**Comment by kumar303** [comment]
In the status meeting, @diox says that we can just drop `persona` everywhere so that should be an easy fix.

**Comment by kumar303** [comment]
@AlexandraMoga I tried to only change what was necessary but my fix also touches some of the theme display logic. Can you do some general checks against all theme related features?

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF65, Win10x64 and Android 8.0

@kumar303 
First, I've checked that the reported issue was fixed:
![2019-02-26_16-37-15](https://user-images.githubusercontent.com/31961530/53424848-a8e29f00-39ec-11e9-9dff-0092e78de714.gif)

After that, I've verified that the functionalities around themes - homepage, search, details, categories - are still working as expected both on desktop and mobile.
I've also noticed that the api calls used for fetching themes are no longer using `persona` for `type` , only `statictheme` .
Manual search queries are still bringing up personas, but I understand this will be handled in future patches.

**Comment by kumar303** [comment]
Thanks!
