### ISSUE TITLE
Create/use a star rating widget

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#759]
There's existing 3rd part code for this. If it's good and meets the accessibilty requirements then we can use something that pre-exists.

A11y  needs are it must be understandable without visuals. It should use existing form controls as a basis. It must be navigable with the keyboard.

Relates to mozilla/addons#151

**Comment by kumar303** [comment]
We have a more concise plan for this widget in https://github.com/mozilla/addons-frontend/issues/1017
