### ISSUE TITLE
Give Addons for legacy version of Firefox

### ISSUE THREAD

**Issue by john7200** [mozilla/addons-frontend#7595]
Several addons like Flashstopper, Multi-Link Paste and Go and Remove Google Redirect in Google Results are no longer accessible in Firefox addons site, and I believe it was Mozilla's fault. Please create a specific place for addons for legacy Firefox to download these addons or at least give people links to download latest or beta xpi of these addons either for research/testing or just backup. Some people are still using Firefox legacy versions (pre-Quantum, v56 or v57 or ESR) for some reasons. For any addons that is still working for Firefox legacy but not Quantum, simply putting a warning "This is not compatible for Firefox Quantum" is more than sufficient than just outright killing it and make people who are still using it unable to get it.

**Comment by EnTeQuAk** [comment]
The archive team archived legacy add-ons here: https://archive.org/details/addons.mozilla.org_legacy_201810

That being said, old versions of Firefox should not be used as they're unsupported and potentially unsafe so I'd highly suggest upgrading to the latest version or at the very least Firefox ESR.
