### ISSUE TITLE
add redirect/support for `users/login`

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#7596]
Refs https://github.com/mozilla/addons-server/issues/10428

follow on from https://github.com/mozilla/addons-server/issues/10637#issuecomment-463200793

@jvillalobos says users/login still receives some traffic so it's probably best we redirect back to / for them to log-in.  

Logging this as frontend work because @bqbn expressed some concern in https://github.com/mozilla/addons-server/issues/10645#issuecomment-463498086 that too many nginx rules were adding complexity (and slowdown)

**Comment by bqbn** [comment]
`/users/login` is now redirected to `/`, and this rule is deployed on -dev.

Please test it.

**Comment by willdurand** [comment]
cc @AlexandraMoga @ioanarusiczki

**Comment by AlexandraMoga** [comment]
@bqbn @willdurand I've verified this new redirect on -dev. Please find my results below and leave your input:

1. https://addons-dev.allizom.org/users/login => we have a first 301 redirect to `/` , which then further redirects to `/en-US/firefox/`
![image](https://user-images.githubusercontent.com/31961530/53178364-64c15a00-35fa-11e9-80e6-113d765758c1.png)
2. https://addons-dev.allizom.org/en-US/firefox/users/login/ => throws a 404 on the new frontend
3. https://addons-dev.allizom.org/en-US/developers/users/login and https://reviewers.addons-dev.allizom.org/en-US/reviewers/users/login  => are throwing a 404 on the legacy site

**Comment by bqbn** [comment]
@diox regarding @AlexandraMoga's comment above, do you know if it is that `/<locale>/<app>/users/login` needs to be redirected to `/`, or is it just `/users/login` that needs to be redirected?

Thanks!

**Comment by diox** [comment]
@bqbn : `<locale></app>/users/login` needs to be redirected as well.

**Comment by eviljeff** [comment]
@AlexandraMoga 
>3\. https://addons-dev.allizom.org/en-US/developers/users/login and https://reviewers.addons-dev.allizom.org/en-US/reviewers/users/login  => are throwing a 404 on the legacy site

Where do/did we link to `/developers/users/login`?

**Comment by AlexandraMoga** [comment]
@eviljeff I was merely trying to see how these pages behaved when `/users/login` was present in the URL. If these pages are out of scope, you can ignore my test.

**Comment by bqbn** [comment]
We made it so that

*  `/users/login`
*  `/<locale>/firefox/users/login`
*  `/<locale>/android/users/login`

are redirected to `/`.

`/<locale>/developers` and `/<locale>/reviewers` are served by the legacy site anyways. If a page doesn't exist for these 2 prefixes on the legacy site, they will return 404.

Let us know if more `users/login` routes need to be redirected to `/`.

**Comment by AlexandraMoga** [comment]
@bqbn I've verified the new redirects on -dev and stage

* `/en-US/firefox/users/login`

![image](https://user-images.githubusercontent.com/31961530/53432293-e4846580-39fa-11e9-9785-549b3ef5f55c.png)

* `/de/firefox/users/login`

User is redirected to the default locale set by the browser (`en-US` in my case)
![image](https://user-images.githubusercontent.com/31961530/53432499-4b098380-39fb-11e9-9ed0-07146505558e.png)


* `/en-US/android/users/login`

On desktop, `/android/` is redirected to `/firefox/`. This doesn't seem to happen on a mobile device, where the user remains on `/android/`
![image](https://user-images.githubusercontent.com/31961530/53474308-69ac6080-3a75-11e9-95e6-576140cefe41.png)

**Comment by eviljeff** [comment]
The app and locale should be kept really, but as these are old urls coming from somewhere external I don't think we care that much.  @jvillalobos ?

**Comment by jvillalobos** [comment]
Yeah, not a big deal.

**Comment by willdurand** [comment]
Looks like this is fixed too :)
