### ISSUE TITLE
Investigate react form components/libs

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#760]
We're going to need a bunch of forms etc - there's some existing components for that it would be good to take a look at them and see if they're a good fit for our needs.

We must take into account

* Code quality
* Accessilibilty etc
* Flexibility.
* Relationship with redux

**Comment by muffinresearch** [comment]
- https://prometheusresearch.github.io/react-forms/
- http://redux-form.com/
- https://github.com/davidkpiano/react-redux-form

**Comment by mstriemer** [comment]
Are we feeling any pain on forms currently?

I had a friend ask me about using one of these libraries before (I think it was `redux-form` [no, not `react-redux-form`]) and it was way easier to do what he wanted without the library than with it.

I'd be cautious to add something if we aren't seeing a need right now. It seems like mostly these work by getting you to structure your data in redux a certain way. We don't necessarily need a library to do that.

**Comment by muffinresearch** [comment]
>Are we feeling any pain on forms currently?

No - since we aren't using any forms at all yet no really and search barely counts.

I wanted to see what the prior art is for this. Mainly because if we can have a consistent approach via a lib that might be good - especially thinking ahead to when we are handling input more. 

The outcome might be `YAGNI` - but I still think it's worth seeing what's out there.

**Comment by muffinresearch** [comment]
Ok, so lets consider this when we have some solid requirements of forms we need to implement.
