### ISSUE TITLE
Non-working link

### ISSUE THREAD

**Issue by Taggen-Trafik** [mozilla/addons-frontend#7605]
### Describe the problem and steps to reproduce it:
The non-working link is on this page:
https://addons.mozilla.org/sv-SE/firefox/addon/google-translator-webextension/?src=featured

The non-working link is inside the text-block headlined 
"About this extension" (back-translated Swedish→English)
The link-text of the non-working link is: 
"Google™ Translator (Add-on SDK)"
This link-text is hyperlinked to: 
"https://addons.mozilla.org/en-US/firefox/addon/google-translator/"

When I click this link, it's not working!  

### What happened?
I got transferred to the correct URL: 
"https://addons.mozilla.org/en-US/firefox/addon/google-translator/"
For this URL though, something other than expected is displayed

### What did you expect to happen?

I expected to be shown information about "Google™ Translator (Add-on SDK)"

Instead the page displayed the following headline:
"Oops! We can’t find that page"
Below there are some explanation text that is related to some conditions.
One of the conditions saying: 
"If you’ve followed a link from another site for an extension or theme //..."

Another condition saying:
"If you’ve followed a link on this site //..."

The second condition urged me to:
"Help us fix the link by filing an issue."

I can't judge which one of these conditions that's applicable in this case, so I'm filing this issue to be on the safe side.

### Anything else we should know?

I'm a person who always try to help if I can.
I found it a little bit difficult to know whether filing an issue was the correct thing to do or not. Maybe it's related to the fact that English isn't my native language. 
If I badly missed the message, on the page "Oops! We can’t find that page", consider to make the explanation text idiot-proof for people like me! :-)

**Comment by jvillalobos** [comment]
That add-on page is no longer available because the add-on hasn't been updated to work with supported versions of Firefox. Please contact the developer of the add-on to remove the link.
