### ISSUE TITLE
Can't find RAMBack page.

### ISSUE THREAD

**Issue by SteegHobland** [mozilla/addons-frontend#7609]
On the page **_Firefox uses too much memory (RAM) - How to fix_**, under the **Memory troubleshooting tools** heading, I clicked the link to the **RAMBack** tool.

I wound up on an **_Oops! We can’t find that page_** page.

I expected to arrive at the page for the **RAMBack** tool.

To reproduce, simply head to https://support.mozilla.org/en-US/kb/firefox-uses-too-much-memory-ram and click the link to **RAMBack**.

**Comment by EnTeQuAk** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.

The first tip on that page, regarding `about:memory` should be more than fine on todays Firefox versions as it has been optimized and improved a lot over the years.

**Comment by SteegHobland** [comment]
I followed a link from a page on mozilla.org that led to a missing page. It seemed to say, as I interpreted it then, I should report that here, though it appears that is not the case. I am sorry for any inconvenience I have caused.
