### ISSUE TITLE
i need firefox always show sites in desktop view , how can i do this?

### ISSUE THREAD

**Issue by UsernameIsAlreadyTakenByMe** [mozilla/addons-frontend#7619]

**Comment by UsernameIsAlreadyTakenByMe** [comment]
It's archived, but best solution is no longer available. I think it should be changed.
https://support.mozilla.org/en-US/questions/1114055

**Comment by jvillalobos** [comment]
You can ask for alternatives in the forum: http://discourse.mozilla.org/c/add-ons

This repository is for the add-ons website itself, so we can't help you with that here.
