### ISSUE TITLE
Move the Permissions card at the top of the detail page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7624]
In [this reddit thread](https://www.reddit.com/r/firefox/comments/asdvkn/keeping_addons_safe_for_our_users_future_releases/egv4nhb/), a user suggested to _"show the permission box higher in the extension page in AMO"_. I think it is a really good idea and we should probably do this. It could give more hints to the end user, which could improve safety somehow.

Here is an example of a detail page on a rather large screen:

![screen shot 2019-02-22 at 15 32 22](https://user-images.githubusercontent.com/217628/53249000-42d9dd00-36b7-11e9-8fc6-7675e87dfeb7.png)

We don't see the "permissions" card 😞 We should move it below the "reviews" card I believe and I also think the "Add to collection" card could be moved below the "more info" card.

ping @jvillalobos for product decision (are you ok with us making this change?)
ping @pwalm for UX guidance

---

**For QA:** according to https://github.com/mozilla/addons-frontend/issues/7624#issuecomment-508807849, we want to swap the Add to Collection card with the Permissions card.

**Comment by willdurand** [comment]
@jvillalobos is this something we could ship or can we close the issue?

**Comment by jvillalobos** [comment]
I'm in favor of swapping the Add to Collection box with the Permissions box on listing pages. @atsay @brassy-, what do you think?

**Comment by brassy-** [comment]
I agree

Il giorno ven 5 lug 2019 alle 18:20 Jorge Villalobos <
notifications@github.com> ha scritto:

**Comment by M4trox** [comment]
@willdurand I would like to work on this issue 🙂

**Comment by willdurand** [comment]
@M4trox go ahead!

**Comment by M4trox** [comment]
@willdurand great! I'll try to work this, but right now I'm having trouble with running `addons-frontend` on Windows 10. See issue: https://github.com/mozilla/addons-frontend/issues/8262

**Comment by caitmuenster** [comment]
Hey @M4trox, sorry to see that you were having problems running addons-frontend. Are you still working on this?

**Comment by willdurand** [comment]
> Hey @M4trox, sorry to see that you were having problems running addons-frontend. Are you still working on this?

I think this is fixed, isn't it?

**Comment by Shubhamchinda** [comment]
@willdurand Let me If I can work on this issue.

**Comment by willdurand** [comment]
@Shubhamchinda someone is already on it, sorry.

**Comment by M4trox** [comment]
PR added:  #8297

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx68, Win10x64 and Android 8.0

a screenshot where the Contribute card is also present:
![image](https://user-images.githubusercontent.com/31961530/61219499-04ec5c80-a71d-11e9-9328-9fef2742ccbf.png)
