### ISSUE TITLE
Add 5 more EU locales to AMO

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-frontend#7626]
Related to [#10758](https://github.com/mozilla/addons-server/issues/10758) on addons-server. 

This is a request to add locales to AMO for the following languages:

    * Croatian
    * Estonian
    * Latvian
    * Lithuanian
    * Maltese

Having these locales would be helpful to supporting EU-specific campaigns for extensions. These should be enabled by March 15, 2019 for an upcoming campaign.

@muffinresearch had mentioned that this should involve adding config and generating a locale file. If it becomes significantly more work, please holler -- campaign scope can be negotiated.

Thanks!

**Comment by AlexandraMoga** [comment]
Verified on AMO -dev with FF65, Win10x64

The new languages have been added in the frontend:

Croatioan
https://addons-dev.allizom.org/hr/firefox/
Estonian
https://addons-dev.allizom.org/et/firefox/
Latvian
https://addons-dev.allizom.org/lv/firefox/
Lithuanian
https://addons-dev.allizom.org/lt/firefox/
Maltese
https://addons-dev.allizom.org/mt/firefox/

However, until the server issue is fixed, we are going to run into 404s when navigating to pages that are based on the server:
ex. https://addons-dev.allizom.org/en-US/firefox/lt/developers/addons/

**Comment by AlexandraMoga** [comment]
@willdurand taking in consideration that the server side is not ready yet, which, as pointed in my previous comment, could lead to 404s, should we consider postponing the frontend part as well?
Probably, these new locales will have little traffic, but the issue highlighted above is still worth mentioning.

**Comment by willdurand** [comment]
@AlexandraMoga The issue in addons-server has been fixed. It is now in -dev and ready for cherry-pick if you confirm -dev looks good. Thanks!

**Comment by AlexandraMoga** [comment]
The server issue being fixed, eliminates the problems noticed before.
This can be marked now as verified fixed.
