### ISSUE TITLE
AOSSIE carbonFootprint Addon, not found

### ISSUE THREAD

**Issue by Sauravskv07** [mozilla/addons-frontend#7628]
### Describe the problem and steps to reproduce it:
I was trying to find AOSSIE's addon built to measure carbon footprint but there was no such thing. My browser is Firefox Quantam 65.0 and my operating system is ubuntu bionic.

### What happened?
I happened to find this thing so that I can find some new bugs. I went on its gitlab repository. Clicked this link for opening the addon in firefox.

### What did you expect to happen?
I expected to see the addon listed

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
