### ISSUE TITLE
No error message when logging out/in during read only mode

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#7636]
### Describe the problem and steps to reproduce it:

When `addons.mozilla.org` is in read-only mode, logging out looks like this:

* Click on your account dropdown menu from the header and select *Log out*

### What happened?

Nothing in the UI changes

### What did you expect to happen?

You should see a message saying that the site is in read-only mode.

### Anything else we should know?

This click handler is ancient:

https://github.com/mozilla/addons-frontend/blob/9a001afb248e1577be5ba1396fd633891bf3d140/src/core/components/AuthenticateButton/index.js#L133

It needs an error handler like the newer UI actions. See https://github.com/mozilla/addons-frontend/issues/5949

Logging out is not such a critical user action so this is lower priority than https://github.com/mozilla/addons-server/issues/10787

**Comment by willdurand** [comment]
Reopening this issue to implement what @eviljeff described in https://github.com/mozilla/addons-server/issues/10787#issuecomment-539389919

I think we can simply disable the login button and logout link when `site.readyOnly` is `true`.

**Comment by ioanarusiczki** [comment]
@bqbn @willdurand Can someone make read only available for this test ? 
Thanks!

**Comment by bqbn** [comment]
In which environment and when do you want RO to be enabled? I suppose the RO mode cannot be enabled for a long time, so this may need some coordination as to when to set RO mode.

**Comment by ioanarusiczki** [comment]
@willdurand As discussed on irc - I tested this with FF69(Win10).

When read only is active:
- Register/Login button was disabled when I logged out. Also the maintenance message is displayed.
- Log out was disabled + the maintenance message displayed.

![Logged out mode](https://user-images.githubusercontent.com/33448286/67263832-f2b75280-f4b1-11e9-81e3-b83a22e14170.gif)

**Comment by willdurand** [comment]
> In which environment and when do you want RO to be enabled? I suppose the RO mode cannot be enabled for a long time, so this may need some coordination as to when to set RO mode.

@bqbn I think it's fine for now. I was able to manually enable/disable the RO mode in -dev. I don't know if we'll need to do the same in stage (maybe not).
