### ISSUE TITLE
Error with log in in firefox add-ons

### ISSUE THREAD

**Issue by Dark-Scorpius0411** [mozilla/addons-frontend#7638]
After I tried to log in in firefox add-ons, the page send a message that says "No authorized".
I'm loging in to write son comments and reviews about the extensions for firefox that i has been used.

**Comment by kumar303** [comment]
Hi. The site was in read-only mode during maintenance but it may not have been apparent -- sorry about that. It should be back now. Can you try again? 

We filed https://github.com/mozilla/addons-server/issues/10787 to address the login issue.
