### ISSUE TITLE
S3.Translate missing !

### ISSUE THREAD

**Issue by vidalv** [mozilla/addons-frontend#7642]
### Describe the problem and steps to reproduce it:
Searching on FF 65.0.1 to add S3.Translate module addon : Not listed !

No idea !
### What happened?
Nothing.
### What did you expect to happen?
S3.Translate work on Chrome for example.
### Anything else we should know?
No.

![image](https://user-images.githubusercontent.com/16664649/53514170-60e47a80-3ac7-11e9-8ac7-9e405e624e09.png)

![image](https://user-images.githubusercontent.com/16664649/53514275-a9039d00-3ac7-11e9-9b29-6a19990b52db.png)

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
