### ISSUE TITLE
The warning message persists on the detail page after deleting the review with an admin account

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7645]
Followup for https://github.com/mozilla/addons-frontend/issues/6351

STR:
1. Log in AMO with an admin account, make a review and then delete it from the permalink from the add-on review listing page
2. Return to the detail page and observe the page
3. Navigate away from the page, search the reviewed add-on then open it from the search results and observe the page

Expected result:
The red warning message is no longer displayed for 2. and 3.

Actual result:
The message is still displayed. The page needs a refresh.

Notes:
Reproducible on AMO dev with FF65 (Win10). 

![needs refresh](https://user-images.githubusercontent.com/33448286/53556212-122cf400-3b4c-11e9-9642-892608e9b3cf.gif)

**Comment by Shubhamchinda** [comment]
Hey, I'd love to take this!
