### ISSUE TITLE
Text in the 'Log in to rate extension' button should be center aligned

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7646]
STR:

1. Open AMO on a mobile device (or use the responsive design mode) and make sure you are logged out
2. Switch to a locale that usually contains longer strings, such as `it` , `de`
3. Go to an extension details page - https://addons.mozilla.org/it/firefox/addon/font-inspect/
4. Scroll down to the ratings section
5. Observe the 'Log in to rate extension' button

Actual result:
Text is aligned to the left

Expected result:
Text is center aligned

Notes:
- reproduced on all AMO servers with FF65, Android 8.0

![image](https://user-images.githubusercontent.com/31961530/53562074-18759d00-3b59-11e9-9064-44727c928e94.png)

**Comment by suhailsinghbains** [comment]
Hi, I would to work on this issue, if possible :)
Thanks

**Comment by AlexandraMoga** [comment]
Verified fixed on stage with FF65, Android 8.0 and Win10x64

![image](https://user-images.githubusercontent.com/31961530/54683461-678c6d80-4b1a-11e9-8744-d1267e882608.png)
