### ISSUE TITLE
Prevent Disco pane video test from creating a memory leak, crashing

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#765]
If you run the tests with `npm run unittest:dev` which runs the unit tests with a watcher, eventually node runs out of memory. 

~~When running the tests in debug mode I noticed the video is actually being played in the disco pane tests. We should fix that.~~ (This is fixed but the memory leak is still happening.)

**Comment by tofumatt** [comment]
I nominate this as a work week bug because it is officially driving me crazy. I can hear the video play for a split-second in the background when running unit tests and it ruins my jams/surprises others around me.

**Comment by kumar303** [comment]
Really? I can't hear anything but it makes the tests slower over time and the final crash is inevitable. It wouldn't be so painful if starting up a new test runner didn't take so long.

**Comment by kumar303** [comment]
But to be clear: +1000 for nominating this!

**Comment by tofumatt** [comment]
Yeah I started noticing it recently, and as the tests get slower it plays for longer.

It weirded me out the first time it happened, sound coming from nowhere.

**Comment by kumar303** [comment]
I just got another crash locally with this patch. I think we need to either prevent the video tag from rendering or stub out the URLs that it loads for the sources.

**Comment by tofumatt** [comment]
Same here, I think I mentioned it on irc but not in the bug. Memory usage even on first run is up around 800mb, so in general finding a way to lessen our memory usage during tests would be great, but stubbing out the video (especially if it's autoloading) is a good idea. 👍🏻

**Comment by tofumatt** [comment]
I think with Jest this issue is effectively solved. We could stub out the URL if we wanted but this doesn't bite me anymore and I think we can close it.

**Comment by kumar303** [comment]
I think it might only be fixed because jest kills/re-spawns a new process for each test run. But, hey, that's good enough for me.
