### ISSUE TITLE
Link to "Find more search engines" in search preferences is broken

### ISSUE THREAD

**Issue by cesaredamico** [mozilla/addons-frontend#7652]
### Describe the problem and steps to reproduce it:

Clicking on the link "Find more search engines" from the "Search" Preferences page in firefox:

about:preferences#search

I get a 404

This is the page that is linked from that link:
https://addons.mozilla.org/en-US/firefox/search-engines/

**Comment by muffinresearch** [comment]
Thanks for the report. It looks like we're missing a redirect from https://addons.mozilla.org/en-US/firefox/search-engines/ to https://addons.mozilla.org/en-US/firefox/search-tools/

**Comment by muffinresearch** [comment]
A redirect has been added.

**Comment by AlexandraMoga** [comment]
Verified fixed on -prod:

![2019-03-01_15-35-23](https://user-images.githubusercontent.com/31961530/53641474-bb9ce400-3c37-11e9-91f0-c586a46ce36d.gif)
