### ISSUE TITLE
Implement users/unsubscribe

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#7656]
See https://github.com/mozilla/addons/issues/930 - we include an unsubscribe link in emails and, on following the link, show a page to confirm they are unsubscribed to that type of notification (with links to other actions).  We should implement that page on addons-frontend because it's a user facing page.

**Comment by willdurand** [comment]
API has landded!

**Comment by ioanarusiczki** [comment]
@willdurand I verified this with FF66(Win10) on AMO dev.
- I managed to unsubscribe successfully to the following options:

`an add-on developer replies to my review`
via https://addons-dev.allizom.org/en-US/firefox/users/unsubscribe/dGVzdGluZ3RoaXNAY2xlYXJtYWlsLm9ubGluZQ==/7ba7e8f1e3c7ad2f48e5693331d9d4b08d289c23fe0bbcc2d06fc8822e0cf68d/reply/

`new add-ons or Firefox features are available`
via https://addons-dev.allizom.org/en-US/firefox/users/unsubscribe/dGVzdGluZ3RoaXNAY2xlYXJtYWlsLm9ubGluZQ==/7ba7e8f1e3c7ad2f48e5693331d9d4b08d289c23fe0bbcc2d06fc8822e0cf68d/new_features/

`someone writes a review of my add-on`
via https://addons-dev.allizom.org/en-US/firefox/users/unsubscribe/dGVzdGluZ3RoaXNAY2xlYXJtYWlsLm9ubGluZQ==/7ba7e8f1e3c7ad2f48e5693331d9d4b08d289c23fe0bbcc2d06fc8822e0cf68d/new_review/

I tested for both logged in and logged out users. The edit profile page will show the option as being unchecked after the link is accessed.  Notifications will no longer be received on e-mail until the options are re-checked from the edit profile page.

- I did not find the `<setting>` from the URL's format `https://addons.mozilla.org/users/unsubscribe/<token>/<hash>/<setting>` as explained in https://github.com/mozilla/addons/issues/930 for
`my add-on's compatibility is upgraded successfully` , I tried to change compatibility for a lang pack in dev hub but looks like that's not the way to receive this e-mail
and `stay up-to-date with news and events relevant to add-on developers (including the about:addons newsletter)`  
but perhaps you can provide those to test that the unsubscribe pages load for them too. 
Thanks!

**Comment by willdurand** [comment]
@ioanarusiczki isnt it `upgrade_success`?

**Comment by willdurand** [comment]
I found it in this list: https://github.com/mozilla/addons-frontend/blob/6be8ac83c2be214b385a06da7b5ebd4b7397c1fc/src/amo/utils/notifications.js#L9-L25

**Comment by ioanarusiczki** [comment]
@willdurand Yes, that helped. I tested for the `announcements` and `upgrade_success` too and works for them too.
If I try with a mandatory notification such as `individual_contact` it won't apply, the frontend delivers a red warning message `Attempting to set [individual_contact] to False. Mandatory notifications can't be modified`. 
Marking this verified on AMO dev with FF66(Win10).

**Comment by willdurand** [comment]
🎉

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO stage too with FF66(Win10).
Unsubscribe link is generated and sent on email such as 
https://addons.allizom.org/en-US/firefox/users/unsubscribe/cnVzaWN6a2kuaW9hbmFAZ21haWwuY29t/bb67586e94aefcc585a0bc72e704ac3598001cec45576cfa7465b99d83454efb/new_review/
The new page is also displayed for the rest of the optional emails `reply`, `new_features`, `upgrade_success`, `announcements`.
