### ISSUE TITLE
65.0.2 (64-Bit) Add new search engine fails

### ISSUE THREAD

**Issue by derTHOMMESisses** [mozilla/addons-frontend#7664]
### Describe the problem and steps to reproduce it:

When trying to add new search engine in 65.0.2 (64-Bit) german the exception-site opens (Hoppla! Wir können diese Seite nicht finden. [sorry, we cannot find the required site...]):

https://addons.mozilla.org/de/firefox/search-engines/

**Comment by willdurand** [comment]
Thanks for the bug report, closing this one in favor of #7667.
