### ISSUE TITLE
In-product link to firefox/dictionaries is 404

### ISSUE THREAD

**Issue by flodolo** [mozilla/addons-frontend#7668]
Stumbled upon https://bugzilla.mozilla.org/show_bug.cgi?id=1532208

In products we have links to firefox/dictionaries, and apparently this is broken. Looking at the code, I can't seem to find anything that would explain it.

**Comment by willdurand** [comment]
Hi, it's being tracked in #7658. We changed the nginx config last week and a few things haven't been ported correctly.
