### ISSUE TITLE
addons subwatch

### ISSUE THREAD

**Issue by MrKulrat** [mozilla/addons-frontend#7670]
### What happened?
al tratar de instalar la extension de subwatch para firefox, la pagina de addons de firefox muestra que esta no existe

### What did you expect to happen?
poder instalar el addons de subwatch
### Anything else we should know?

https://sub.watch/extensions

**Comment by jvillalobos** [comment]
The page for this extension has been disabled. It's up to the developer to correct this or change the information on their website.
