### ISSUE TITLE
Can't get doc on extension you removed, and can't get rid of it

### ISSUE THREAD

**Issue by ivanlan9** [mozilla/addons-frontend#7671]
### Describe the problem and steps to reproduce it:
I tried to follow this link:  https://addons.mozilla.org/en-CA/firefox/addon/custom-tab-width/  and it gave me a 404. That means I cannot get info on it to try to help me uninstall this extension, WHICH YOU ARE NOT SHOWING AS INSTALLED.

Firefox does not admit that this extension is installed, but it is, and I CANNOT REMOVE IT UNLESS YOU ADMIT.

### What happened?
You're not showing this extension as installed, BUT IT IS.

### What did you expect to happen?
I would like to uninstall the extension as it is sucky.

### Anything else we should know?
When I open new tabs they come up with a huge blank between my last tab and the new one, and the blank spot can't be clicked on. I put up with it too long, and now you've removed it from the add-ons pages, but you unfortunately DID NOT REMOVE IT FROM MY FIREFOX.  I'm fine with removing things that don't work or are obsolete--but please, carry through.

This is making me very cranky.

https://addons.mozilla.org/en-CA/firefox/addon/custom-tab-width/

**Comment by caitmuenster** [comment]
Hi there, please see https://support.mozilla.org/en-US/kb/disable-or-remove-add-ons for guidance on how to remove an extension.

**Comment by ivanlan9** [comment]
Hi There, you didn't read my report. Please see the report for the reason that you shouldn't close it.

Because the plugin does not appear in my list of plugins, I CANNOT REMOVE THE PLUGIN.

I have no hope that anyone will read this. That's OK.  I will keep resubmitting until someone does.

**Comment by caitmuenster** [comment]
Hi, your report said that you were directed to a 404 page on AMO. We read these issues; please do not keep refiling. 

You might want to [refresh your Firefox](https://support.mozilla.org/kb/refresh-firefox-reset-add-ons-and-settings) if you can't remove the add-on from the Add-on Manager, or ask for help on the [Firefox support forum](https://support.mozilla.org/).
