### ISSUE TITLE
Local AMO fromend doesn't load direct links

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#7679]
### Describe the problem and steps to reproduce it:
Using the ```docker-compose.yml``` config within [addons-server](https://github.com/mozilla/addons-server), I can not get an addons page to load via its URL. An example URL is: ```http://olympia.test/en-US/firefox/addon/artisanal-pizza/?src=featured```.

### What happened?
I get a page that looks like this: 
![screenshot_2019-03-06 add-ons for firefox en-us](https://user-images.githubusercontent.com/5751892/53895412-02a42400-4000-11e9-8e0b-c55ee989a5dd.png)

### What did you expect to happen?
The addon information page to load correctly.

**Comment by willdurand** [comment]
@jrbenny35 is this still a problem? I believe it worked for me last time I tried to pull the docker env in addons-server.

**Comment by jrbenny35** [comment]
Yeah this works now.
