### ISSUE TITLE
You sent me here?

### ISSUE THREAD

**Issue by 1stupidname** [mozilla/addons-frontend#7681]
### Describe the problem and steps to reproduce it:

Was looking for HTML5 version history.   I ended up here instead.

Has Mozilla destroyed all the FireFox 52.9.0 (32 bit) add on files?   
Is there anywhere that will support the reinstalling of these older add-ons?

Currently I am looking for the HTML5 everywhere ver 0.4.8.   This is installed on most (but not all) of
my Firefox installations.   

Is there (or can there be) a program that will facilitate transferring add-ons from Firefox installation to another.   Eg.  An add-on backup and restore program.

**Comment by jvillalobos** [comment]
If you have the extension installed in some Firefox you use, you can find the installer in the [profile folder](https://support.mozilla.org/en-US/kb/profiles-where-firefox-stores-user-data). Extensions that don't work on supported versions of Firefox (60 and above) were disabled a while ago and are no longer available on the site.
