### ISSUE TITLE
Bookmark issues not resolved by any listed method

### ISSUE THREAD

**Issue by rowanwolf** [mozilla/addons-frontend#7683]
After upgrade to ver 65 could no longer add bookmarks 

While existing bookmarks and toolbar worked, the option to manage bookmarks disappeared. Drag and drop new bookmarks did not work. Manual add was greyed out.

I tried restarting in safe mode

I tried refreshing FF

I tried deleting /renaming xulstore
I tried downgrading to ver 64
I tried deleting/ renaming places.sqlite

The result of the latter was to effectively erase all bookmarks - though the folders themselves remained.

Now I am totally stuck. I guess I can go back to 65 and restore my bookmarks, but that will not fix the original problem which was that I could not add new book marks either to the toolbar or the sidebar display

I am using Windows 10

**Comment by jvillalobos** [comment]
You can find Firefox help here: https://support.mozilla.org/

This issue tracker is for the add-ons website, so we can't help you with that.
