### ISSUE TITLE
trouble with firefox 65 quantum

### ISSUE THREAD

**Issue by jibelito** [mozilla/addons-frontend#7692]
### Describe the problem and steps to reproduce it:  since the new version , I have many troubles for connect to facebook or any site with the lien arrived with thunderbird ? when I click on it impossible to access to the facebook  or an other site. I used mozilla TB & F.F.  since  + 10 years 
![Capture d’écran_2019-03-11_10-12-46](https://user-images.githubusercontent.com/6386456/54123388-eccba000-43ff-11e9-88f4-9b0332bdd416.png)

When I want to make the correction it's impossible to used firefox correctly?  I used another navigator no problem, the transfers is perfect with Chromium. I would like to know What doing? Many thanks see u

**Comment by wagnerand** [comment]
For support, please visit https://support.mozilla.org.
