### ISSUE TITLE
I can't access my Firefox theme collection

### ISSUE THREAD

**Issue by CV45** [mozilla/addons-frontend#7698]
### What happened? 
I received a "Server Error" message

### Anything else we should know?

<
![Screen Shot 2019-03-12 at 10 29 43 AM](https://user-images.githubusercontent.com/8496416/54208565-8eabc500-44b2-11e9-8d4c-44a3d241b5fd.jpg)
!-- Please include a link to the page, screenshots and any relevant files. -->

**Comment by wagnerand** [comment]
Can you please provide a link to the page?

**Comment by CV45** [comment]
Hi, here's a link to the addons page where I received the server error message. Add-ons for Firefox (en-US)

| 
| 
|  | 
Add-ons for Firefox (en-US)


 |

 |

 |





    On Tuesday, March 12, 2019, 10:59:03 AM EDT, Andreas Wagner <notifications@github.com> wrote:  
 
 
Can you please provide a link to the page?

**Comment by wagnerand** [comment]
Sorry, your comment does not contain any links.

**Comment by CV45** [comment]
https://addons.mozilla.org/en-US/firefox/collections/

**Comment by CV45** [comment]
Hi, I provided a link in the previous comment.
