### ISSUE TITLE
21 March homepage content refresh

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#7701]
For the **21 March** push, please update the homepage in accord with programming details [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by ioanarusiczki** [comment]
The shelves were updated as mentioned by the [document](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#heading=h.ezk7kl1svjxb) on AMO dev - FF65 (Win10). 
Final validation will be made in production.

![AMO dev homepageupdate](https://user-images.githubusercontent.com/33448286/54609524-db1b7580-4a5b-11e9-9fb2-54acdc52d6b9.gif)

**Comment by ioanarusiczki** [comment]
Verified on AMO prod - FF65(Win10&android8.0)
https://github.com/mozilla/addons-frontend/issues/7746 was filed
