### ISSUE TITLE
The detail page of an add-on should be displayed after using the platform filter button 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7713]
STR:
1. Load AMO and make sure you see the detail page of an add-on that is not compatible with your platform. The red message is displayed. Here's an example https://addons.allizom.org/en-US/android/addon/text444/
2. From the More Menu click the filter button (Add-ons for Platform)
3. Observe the page

Expected result:
The detail page is displayed (In this case such as https://addons.allizom.org/en-US/firefox/addon/text444/) and the compatibility warning is no longer available.

Actual result:
AMO homepage is displayed.

Notes:
This isssue is reproducible on all AMO servers with FF65(Win10).

![filter redirects to homepage](https://user-images.githubusercontent.com/33448286/54421594-6ec80b80-4715-11e9-8444-1aa351cc6ef9.gif)

**Comment by adred8** [comment]
I don't think that "Add-ons for firefox" is intended as a filter but as a link to the add ons to browse in other platforms either . I believe the functionality is correct but what I found is a little different
I landed on the AMO homepage like you mentioned after clicking "Add-ons for firefox". 

If you press back button, the url is [https://addons.allizom.org/en-US/android/addon/text444/](url) but screen is shown without any compatibility error. If you reload the screen, error is shown again

![Screenshot 2019-03-16 at 6 12 30 PM](https://user-images.githubusercontent.com/5622964/54475415-298c0280-4817-11e9-8b3c-d4517d0e2b10.png)

**Comment by willdurand** [comment]
I am not sure which behavior is intended. In some cases, we need to clear most of the state (data) so maybe that's why we go back to the homepage (although I am not sure that's really needed).

**Comment by jvillalobos** [comment]
@adred8 is correct. The menu item isn't intended to be a filter. It's supposed to be a link to a "different" site for Android extensions, which may or may not be compatible with the user's client. I don't think there's a bug to fix here.
