### ISSUE TITLE
Should we remove the lang and application from req.url?

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#772]
Working on #770 I found that we're going to need to have the lang var in all our URLS which might be a pain in the neck, albeit that ends up being very explicit.

An alternative approach would be to not use the router at all and instead deal with the lang purely in express earlier. This would then mean we could hide the lang from the router by essentially consuming the lang and passing only the rest of the URL forward from that point on.

We should think about the pros and cons and discus them.

**Comment by muffinresearch** [comment]
@kumar303 @mstriemer @tofumatt any thoughts on whether we should do this. 

Let me know if you need any more info. Since this issue was filed the lang and application detection *is* happening outside the router because it needs to do redirects for urls that might be initially invalid. Because of this "eating" the lang and application and providing just the part of the url after that would be quite easy. Also express provides req.originalUrl so that if req.url is modified you can still get the original.

**Comment by mstriemer** [comment]
I'm not sure how react-router would handle this. It needs to know a URL is valid to navigate in JS or it will do a full refresh. Adding some URL reversing that knows the lang might be a good way of avoiding the pain here. I guess we'd need to pass it down like i18n.

**Comment by muffinresearch** [comment]
Basically it would mean something like this:

the request comes in to /en-US/firefox/addon/adblock-plus/ 

The middleware takes the lang `en-US` and the application `firefox` and passes that along is `res.locals.lang` and `res.locals.clientApp`. (This is happening already).

If we modify req.url, we'd pass along /addon/adblock-plus/ and that would be what react-router would see. We'd have the lang elsewhere since we're already dispatching an action on that, we're going to need to do something similar for application too.

**Comment by kumar303** [comment]
If react-router can handle it then I'd be fine with removing the prefixes from the routes. However, explicit URL matching is nice. It's nice to look at the URL and know which exact route to look for.

**Comment by muffinresearch** [comment]
Talking this over with Kumar made me think that for now we'd be better off leaving things as they are for now for the following reasons: 

* Since we can use a router prefix to get the lang and application in the router we don't need to apply it to every route e.g. like this in the amo app:

  ```jsx
   <Route path="/:lang/:application" component={App}>
      <IndexRoute component={Home} />
      <Route path="addon/:slug/" component={DetailPage} />
  </Route>
  ```
* Looking at the router it's clear what you're going to respond to. For example whilst disco pane will eventually do a redirect if someone had a bad application in the url the app won't actually respond to something like `/en-US/android/discovery/pane/...`. Because firefox is a hard-coded part of the URL.
* If we need to link to something we'll need the lang and application in the url, so it makes sense for the router to be aware of the full url - we might some nice way to deal with reversing or it might be added in the future.

We can always revisit this if it looks like we're going to need it in future but I'll close it for now.
