### ISSUE TITLE
Not Authorized

### ISSUE THREAD

**Issue by HaLPaX** [mozilla/addons-frontend#7721]
So i wanted to download an add-on because my dad is starting to piss me off with his "security software" that he finds on ads (he disables my ad-blocker too)
How to recreate it:
Try going to the site while logedout, if it works fine it's good, then try to login on a very very old Mozilla account and you will get "Not Authorized" page.

Before loging-in everything was fine with all sites for add-ons, after trying to login i sent me to "Not Authorized" page and didn't log me in.

I expected a page with a add-on i wanted to download and install.

I have latest version of Mozilla Firefox, Windows 10 (64bit),
Add-ons: Adblock Plus, Avast Online Security and DuckDuckGo Privacy Essentials.

https://addons.mozilla.org/en-US/firefox/search/?q=url%20blocker&platform=WINNT&appver=65.0.2

![Mozilla Bug Report](https://user-images.githubusercontent.com/48623954/54476574-17c94180-47bc-11e9-9a1a-78481991747a.png)

**Comment by willdurand** [comment]
Hi, sorry for that. I am looking into it now.

Do you know how to open the "Developer Tools" by chance? There might be error messages in the console.
