### ISSUE TITLE
Extension does not exist.

### ISSUE THREAD

**Issue by manulsan** [mozilla/addons-frontend#7723]
### What happened?
I tried to install extension below but does not work ( Extension is not found] messages.
https://addons.mozilla.org/firefox/addon/oma-lwm2m-devkit/

Once inputted with 
      "https://addons.mozilla.org/firefox/addon/oma-lwm2m-devkit/"
URL is changed like below
https://addons.mozilla.org/ko/firefox/addon/oma-lwm2m-devkit/

so 
I am wondering that  tow things.
1. Above extension is removed from your site.
2. Is it happened because of URL re-direction with country code.

Thanks

**Comment by willdurand** [comment]
Hi, it looks like the add-on has been removed.
