### ISSUE TITLE
How can i add firebug and firepath in firefox

### ISSUE THREAD

**Issue by srivinayp** [mozilla/addons-frontend#7725]
am not able to install the firepath and firebug in Firefox browser 

now it says  Mozilla removed it.
[https://addons.mozilla.org/en-US/firefox/addon/firebug](url)

**Comment by EnTeQuAk** [comment]
Firebug is part of Firefox for years now and you should be using the most recent Firefox version to make use of many wonderful new tools for frontend development.

https://getfirebug.com/

https://www.mozilla.org/en-US/firefox/developer/
