### ISSUE TITLE
Version history has padding issues with <li>s

### ISSUE THREAD

**Issue by mymindstorm** [mozilla/addons-frontend#7732]
See title.

Screenshot:
![image](https://user-images.githubusercontent.com/27789806/54580093-8bde3200-49d4-11e9-9ff5-996d7732ecff.png)

Example: https://addons.mozilla.org/en-US/firefox/addon/auth-helper/versions/

**Comment by willdurand** [comment]
Ah yep, the CSS for the version descriptions could be improved.

**Comment by willdurand** [comment]
For QA, in -dev: I was able to reproduce the issue with this add-on: http://localhost:3000/en-US/firefox/addon/ublock-origin/versions/

**Comment by ioanarusiczki** [comment]
@willdurand Thanks for the sample. What I've noticed is that editing the fields from dev hub with spaces between the lines has no effect on the frontend no matter how many spaces I add (it is visible in the gif I added).
I can't tell if that's as expected right now. 

![text stays compact](https://user-images.githubusercontent.com/33448286/55784181-af1e6d80-5ab8-11e9-9c24-1fef265689a3.gif)

**Comment by mymindstorm** [comment]
@ioanarusiczki think that's intended since it's html. We don't have `<br>`, so I don't think you can add spaces between two `<li>`

**Comment by willdurand** [comment]
> @willdurand Thanks for the sample. What I've noticed is that editing the fields from dev hub with spaces between the lines has no effect on the frontend no matter how many spaces I add (it is visible in the gif I added).
> I can't tell if that's as expected right now.

that's indeed expected
