### ISSUE TITLE
bad link in bookmark menu

### ISSUE THREAD

**Issue by peyman974** [mozilla/addons-frontend#7736]
### Describe the problem and steps to reproduce it:
in bookmark menu bad link in get bookmark add-ons

### What happened?
https://addons.mozilla.org/en-US/firefox/bookmarks/

**Comment by willdurand** [comment]
@jvillalobos do you know in which FF version we had this link by chance? Should we keep it? (addons-server used to serve this URL).

**Comment by peyman974** [comment]
FF 66
after click on this link
the web page displayed with this text
https://addons.mozilla.org/en-US/firefox/bookmarks/

Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes.

**Comment by willdurand** [comment]
Hi @peyman974, thanks. Did you bookmark this link by yourself?

**Comment by jvillalobos** [comment]
The `/bookmarks/` URLs get fairly consistent traffic of over 10K visits (weekly), so I think we should redirect to `/extensions/bookmarks/`.

**Comment by peyman974** [comment]
> 
> 
> Hi @peyman974, thanks. Did you bookmark this link by yourself?

Hi 
No

**Comment by peyman974** [comment]
![bookmark](https://user-images.githubusercontent.com/29371425/54808103-d396df00-4c9c-11e9-8214-3073ce9ecc42.jpg)

**Comment by willdurand** [comment]
ah, perfect. thanks for the screenshot!

**Comment by muffinresearch** [comment]
@autrilla hi - would you be able to take a look at setting up a redirect for this please?

Looks like we need to redir from:

`https://addons.mozilla.org/%locale%/firefox/bookmarks/` 

to 

`https://addons.mozilla.org/%locale%/firefox/extensions/bookmarks/`

There's no android page for this so we don't need a variable client param.

**Comment by willdurand** [comment]
See: https://github.com/mozilla-services/cloudops-deployment/pull/3045

**Comment by willdurand** [comment]
> See: [mozilla-services/cloudops-deployment#3045](https://github.com/mozilla-services/cloudops-deployment/pull/3045)

This has been merged, so it should be deployed in -dev soon.

**Comment by willdurand** [comment]
@ioanarusiczki the -dev UR isL: addons-dev.allizom.org/en-US/firefox/bookmarks

**Comment by bqbn** [comment]
https://github.com/mozilla-services/cloudops-deployment/pull/3045 was deployed to -stage as well.

**Comment by AlexandraMoga** [comment]
Verified fixed in -dev and stage.

https://addons-dev.allizom.org/en-US/firefox/bookmarks/ is redirecting to https://addons-dev.allizom.org/en-US/firefox/extensions/bookmarks/
I've also made sure that this works with other locales.

![2019-03-28_09-17-09](https://user-images.githubusercontent.com/31961530/55137882-d0876d00-513a-11e9-8962-43e629bbdf91.gif)
