### ISSUE TITLE
Spring themes shelf is incomplete on AMO prod 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7746]
The Spring themes shelf from AMO homepage is incomplete - it displays only 3 themes instead of https://addons.mozilla.org/en-US/firefox/collections/4757633/spring-themes/

![Screenshot (531)](https://user-images.githubusercontent.com/33448286/54772704-9a189200-4c10-11e9-8605-4272da194062.png)

**Comment by willdurand** [comment]
@ioanarusiczki you should still see 3 themes but there should be a link in the header and the 3 themes should take the full width of the shelf.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev - FF65(Win10)

![spring themes](https://user-images.githubusercontent.com/33448286/54909569-35508680-4ef3-11e9-8b61-78d253543548.gif)

**Comment by ioanarusiczki** [comment]
Verified on AMO stage and AMO prod - FF65(Win10)

![amo prod](https://user-images.githubusercontent.com/33448286/54917882-794c8700-4f05-11e9-8ab4-3c4e329d41d3.gif)
