### ISSUE TITLE
smartadblock rejected by another developer????

### ISSUE THREAD

**Issue by smartadblock** [mozilla/addons-frontend#7757]
smartadblock was abusively rejected by erosman (a simple developer) in a case where the reviewer policy clearly states that more info should be requested. The extension has now been offline for 8hours? how has this guy been allowed to review extensions in the first place?

**Comment by willdurand** [comment]
cc @wagnerand

**Comment by caitmuenster** [comment]
This repository is for filing issues about addons.mozilla.org, and is not a place for discussing the review process.
