### ISSUE TITLE
WebExtension release notes rendering issue (html tags are not properly escaped)

### ISSUE THREAD

**Issue by nodeticswww** [mozilla/addons-frontend#7762]
### Describe the problem and steps to reproduce it:

We submitted a new version of our WebExtension. When submitting, we entered a description that contained "< code >" string (without the spaces). 

### What happened?

Now when you view the extension page and expand the "release notes" section by clicking "Read more", you can see that the < code > tag was not properly escaped and it actually causes incorrect rendering of the notes. I wonder if <script> tag behaves the same way which would open the door for all kinds of nasty attacks?

https://addons.mozilla.org/en-GB/firefox/addon/feedbroreader

### What did you expect to happen?

AMO should properly escape any html tags entered in release notes.

**Comment by nodeticswww** [comment]
Sheesh.... a description that contained < code > string (remove the spaces).

**Comment by muffinresearch** [comment]
@nodeticswww hi - the version notes field has a note saying that some HTML is supported. Since `<code>` is one of the elements that is allowed, you'll need to escape it yourself if you need it to be displayed literally rather than interpreted as HTML.
