### ISSUE TITLE
addons not found

### ISSUE THREAD

**Issue by Sodafinso** [mozilla/addons-frontend#7770]
### What happened?
I do not found the Firefox addon Axel Springer Blocker (ASB) für Firefox 
### What did you expect to happen?
I found same links to this side but the addon is not found.
### Anything else we should know?
https://addons.mozilla.org/de/firefox/addon/axel-springer-blocker-asb/?src=api
![Bug](https://user-images.githubusercontent.com/6643115/55011906-e5eb8280-4fe6-11e9-9154-c0676ceae365.png)

**Comment by muffinresearch** [comment]
Legacy add-ons are no longer available, which is why you can't find the add-on. The best route forward is to contact the developer and ask them to update their add-on to work as a web-extension.
