### ISSUE TITLE
Slight misalignment in search results list

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#7781]
**STR:**
1. Open AMO homepage (any server)
2. Perform an empty search
3. Look at the search results list

**Actual result:**
There is too much unused space on the right side of the card - this can be best viewed when you filter by Themes - https://addons.mozilla.org/de/firefox/search/?platform=windows&type=statictheme

**Expected result:**
There is the same amount of blank space to the left and the right of the search results card

**Notes:**
- I can confirm this was not the case before (check the second screenshot) and to my best guess, the issue appeared somewhere in February. At the beginning of March, the issue existed already.
- the alignment issue can also be seen on the collection details page - see https://addons.mozilla.org/de/firefox/collections/4757633/spring-themes/
- reproduced on all AMO servers with FF66, Win10x64; not reproduced on mobile

[1] current view
![image](https://user-images.githubusercontent.com/31961530/55074809-f7419700-5099-11e9-953b-d36a72829098.png)

[2] prior view
![image](https://user-images.githubusercontent.com/31961530/55074815-fc9ee180-5099-11e9-952b-44cf78754c31.png)

**Comment by willdurand** [comment]
This happens because we're using 720 x 92px theme preview images.

**Comment by willdurand** [comment]
> This happens because we're using 720 x 92px theme preview images.

On this basis, I believe we cannot do anything.
