### ISSUE TITLE
Allow reviewers to edit their reviewer name when editing their profile

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#7806]
Once mozilla/addons-server#11002 goes live the API will expose a new field for reviewers, called `reviewer_name`. This field should be editable in the edit my profile page. It should only appear for reviewers.

**Comment by kumar303** [comment]
I bumped priority to match that of https://github.com/mozilla/addons-server/issues/11002

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF66, Win10x64

Users with reviewer permissions (expect for rating moderators) will have the ability to set  a reviewer alias through the edit profile page.

Regular users will not see this additional field. 

![image](https://user-images.githubusercontent.com/31961530/55815960-eeb97980-5af9-11e9-8db9-f5b2bb37d7f1.png)
