### ISSUE TITLE
Exit Firefox Android by menu item without deleting anything

### ISSUE THREAD

**Issue by krasnoshtan** [mozilla/addons-frontend#7810]
### Describe the problem and steps to reproduce it:

I was surfing the Firefox help for Android and there was a page where describing how to add an item in the menu to exit Firefox. But link to this add-on is not working anymore.

**Comment by willdurand** [comment]
Hi, would you have the Firefox help page that linked to the missing add-on by chance?

**Comment by krasnoshtan** [comment]
Yes, of course, here
https://support.mozilla.org/en-US/kb/how-do-i-quit-firefox-android?&mobile=1

**Comment by willdurand** [comment]
Oh right, we should update this page if the add-on is really gone.

@jvillalobos there is this content in the link pasted in the comment above:

> Add-on option: If you prefer not to clear your history every time you quit, you can install an add-on that adds the option to the browser. Note: The add-on developer is responsible for all updates and support.

The add-on is: https://addons.mozilla.org/en-US/android/addon/quitnow/

**Comment by jvillalobos** [comment]
@caitmuenster ^^

**Comment by caitmuenster** [comment]
Thanks for the heads up! Removing the link to the add-on from the SUMO article now.

**Comment by bobsilverberg** [comment]
Looks like this was fixed.
