### ISSUE TITLE
Teamweek button

### ISSUE THREAD

**Issue by user-sol** [mozilla/addons-frontend#7811]
### What happened?
following the instructions in this page https://support.teamweek.com/article/35-teamweek-button 
### What did you expect to happen?
There is supposed to be an add-on for Teamweek button

**Comment by willdurand** [comment]
There might be an issue with the latest version of this add-on. /cc @mozilla/add-on-admin-reviewers

**Comment by muffinresearch** [comment]
The previous version looks to be legacy, the best course of action would be to ask the developers to submit a new version as a web extension.
