### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Delphi-Coder** [mozilla/addons-frontend#7821]
### What happened?
I clicked on famous and the best translation add-on (s3translator) link from its site. The Link not works.

### What did you expect to happen?
I expect Firefox team to keep add-on alive for us. Without it the web surfacing life become difficult and left users with a force to move on chrome browser.

### Anything else we should know?
I don't know what happened about s3translator add-on for Firefox. All I know that is very valuable add-on. It was capable of Translating word with just a click while browsing the webpages, without any huge OCR software. It's not a wise choice to let this add-on go.

https://addons.mozilla.org/addon/s3google-translator/

**Comment by muffinresearch** [comment]
@Delphi-Coder hi - the previous add-on version was a legacy add-on which are no longer supported. The best solution is to contact the developer and ask for them to update their add-on to be a web extension.

Another option is to consider some of the web extension alternatives that are already available e.g. https://addons.mozilla.org/en-US/firefox/search/?q=google%20translate&type=extension
