### ISSUE TITLE
Prettier-ci check doesn't catch un-processed files

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#7823]
```
npm run prettier -- --list-different || (echo '\n\nThis failure means you did not run `yarn prettier-dev` before committing\n\n' && exit 1)

> mozilla-addons-frontend@0.0.1 prettier /code/addons-frontend
> prettier --write '**' "--list-different"

README.md
src/amo/components/SearchFilters/index.js
tests/unit/amo/pages/TestUserProfileEdit.js
tests/unit/core/components/TestAMInstallButton.js
$ echo $?
0
```

**Comment by muffinresearch** [comment]
There's a easier command to run now too which is to run:

`prettier -c '**'`

e.g:

$ node_modules/.bin/prettier -c '**'
Checking formatting...
README.md
src/amo/components/SearchFilters/index.js
tests/unit/amo/pages/TestUserProfileEdit.js
tests/unit/core/components/TestAMInstallButton.js
Code style issues found in the above file(s). Forgot to run Prettier?
$ echo $?
1

**Comment by muffinresearch** [comment]
> Isn't it because we pass `--write`?

Yeah, but this means there are non-prettied source files in master - presumably that's not expected is it?

**Comment by willdurand** [comment]
Indeed, we don't want non-prettied files. I think the `prettier` behavior has changed recently and we did not catch that.

In code-manager, we use:

```
    "prettier-ci": "prettier --list-different '**' || (echo '\n\nThis failure means you did not run `yarn prettier-dev` before committing\n\n' && exit 1)",
```

**Comment by ioanarusiczki** [comment]
@willdurand Anything qa should be checking for this ?

**Comment by willdurand** [comment]
> @willdurand Anything qa should be checking for this ?

@ioanarusiczki oops, nope, sorry. Added the "qa: not needed" label :)
