### ISSUE TITLE
The title of the version page does not match the mock-ups

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7825]
The title of the "version page" should be "[extension name] version history".

Actual:

![](https://user-images.githubusercontent.com/27789806/55444894-544bba00-557e-11e9-9a45-e2fe58eda3de.png)

Expected:

![](https://user-images.githubusercontent.com/27789806/55444897-5c0b5e80-557e-11e9-974c-7b413fbbec15.png)

The mock-ups below has a different case but we're not using it anywhere else in the site... So I guess it's better if we are consistent. We can still file an issue to change the case everywhere if that's beneficial.

![Screen Shot 2019-04-03 at 14 35 21](https://user-images.githubusercontent.com/217628/55479156-bf989900-561d-11e9-89e6-b8201c8331b4.png)

**Comment by mymindstorm** [comment]
To add to this, the capitation for the category selector on the front page also seems to be off:

![image](https://user-images.githubusercontent.com/27789806/55521223-6f353180-5645-11e9-87ac-c2b1fb9875a1.png)
`Password managers` should be `Password Managers` and
`Ad blockers` should be `Ad Blockers`

**Comment by willdurand** [comment]
@mymindstorm would you like to submit another patch for these category names?

**Comment by willdurand** [comment]
Thanks for your first contribution @mymindstorm! (/cc @caitmuenster)

**Comment by mymindstorm** [comment]
@willdurand no problem.

> I read your comment #7820 (comment) and it looks like we use lowercase for titles, so let's ignore this problem with the category names.

If sentence case, the `Watching Videos` and `Smarter Shopping` strings should be changed (and the categories above that).

**Comment by willdurand** [comment]
> If sentence case, the `Watching Videos` and `Smarter Shopping` strings should be changed (and the categories above that).

ahm I overlooked these two categories and actually did not understand your previous comment correctly.. Sorry. You're right, it should match this mock-up: https://mozilla.invisionapp.com/share/YCCYEOFRH#/screens/259591847

**Comment by mymindstorm** [comment]
I can't find the mock-up for this:

![image](https://user-images.githubusercontent.com/27789806/55560882-ccb59680-56b6-11e9-895c-aa5a4628f891.png)

Do you know where that is?

**Comment by willdurand** [comment]
Nope, but I found https://mozilla.invisionapp.com/share/PRP2GJ5E7BW#/screens/324863887. These three blocks should remain as-is though.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev with FF66(Win10)

It's "version history", "Smarter shopping" and "Watching videos" now.

![capitalization issue](https://user-images.githubusercontent.com/33448286/55625058-56955a80-57b0-11e9-978a-3327a427d81c.gif)
