### ISSUE TITLE
Update -dev and local dev when EW gets a -dev env (if any)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7830]
~~Depending on https://github.com/mozilla/extension-workshop/issues/131, we might need to update the Extension Workshop URL value in the config.~~ EW will get a -dev env, so let's update our config!

We want to change the value of `extensionWorkshopUrl` in the following files:

- `config/dev-amo.js`
- `config/development-amo.js`

The new value should be: `https://extensionworkshop-dev.allizom.org`

**Comment by caitmuenster** [comment]
Extension Workshop is getting a -dev environment! See [issue #131](https://github.com/mozilla/extension-workshop/issues/131).

**Comment by willdurand** [comment]
Indeed, thanks!

**Comment by willdurand** [comment]
Thanks for your first contribution @feugy! /cc @cai

**Comment by ioanarusiczki** [comment]
@willdurand I receive a 404 on AMO dev when I click EW from both header and footer of the page. FF66(Win10) 

![404 received for ew dev](https://user-images.githubusercontent.com/33448286/56042738-6b3f9880-5d44-11e9-80d3-0b297a3cc12b.gif)

**Comment by willdurand** [comment]
> @willdurand I receive a 404 on AMO dev when I click EW from both header and footer of the page. FF66(Win10)

Yeah, I think the -dev env is not entirely set up yet.

**Comment by feugy** [comment]
Indeed, I've pointed out in the PR #7845 
> Please note the url is not available :cry:

**Comment by ioanarusiczki** [comment]
@willdurand Perhaps this should wait to be verified until dev is set up and change the milestone if it won't be ready this week.

**Comment by willdurand** [comment]
> @willdurand Perhaps this should wait to be verified until dev is set up and change the milestone if it won't be ready this week.

mmh correct, let's move it to the next milestone.

**Comment by ioanarusiczki** [comment]
@willdurand Moved this for the next push.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev - FF66(Win10)
Probably the same should follow for the dev hub links to EW https://github.com/mozilla/addons-server/issues/11099

![ew dev](https://user-images.githubusercontent.com/33448286/56950405-11114680-6b3e-11e9-8db4-11a5bb5ce3b9.gif)
