### ISSUE TITLE
Add tooltips to the Extension Workshop and DevHub header links

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#7831]
To better explain what Extension Workshop and Developer Hub are, and how they are different, @MeridelW suggested we add tooltip text to both links. This is only for the header links in the frontend.

* Extension Workshop: "Learn how to create extensions and themes"
* Developer Hub: "Submit and manage extensions and themes"

/cc @caitmuenster

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @kumar303

**Comment by ithompson4** [comment]
Hello, Can I work on this?

**Comment by willdurand** [comment]
@ithompson4 I think so. By "tooltip", I think we mean HTML titles.

**Comment by ithompson4** [comment]
Hello @willdurand. Yes, I will on this. Thanks.

**Comment by willdurand** [comment]
Thanks a lot for your first contribution @ithompson4! /cc @caitmuenster

**Comment by ithompson4** [comment]
@willdurand, thank you.

**Comment by ioanarusiczki** [comment]
@willdurand Both tooltips are available on AMO dev and stage - FF66(Win10) 
The background of the tooltip box is white not grey  here https://user-images.githubusercontent.com/16367007/55775406-2b886080-5a67-11e9-8527-18019d181bd0.png but I don't mind, it looks better white.

![tooltips on desktop](https://user-images.githubusercontent.com/33448286/55860601-46e58f80-5b7d-11e9-862a-44a2eb7f4640.gif)
