### ISSUE TITLE
Add info about AMO API to /about page

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-frontend#7838]
On https://addons.mozilla.org/about, let's add some info about the AMO API. 

Under **Get  Involved,** let's add: 

- Want to interact with addons.mozilla.org (AMO) programmatically?  Check out the documentation for the [Add-ons Servers documentation](https://addons-server.readthedocs.io/en/latest/index.html) for details about the AMO APIs, the APIs used by the [Add-ons Manager](https://blog.mozilla.org/firefox/add-ons-manager/).

Related note: can we also add a '.' next to 'wiki' at the end of To see more ways you can contribute to the add-on community, please visit our wiki?

**Comment by championshuttler** [comment]
Here you go @rahulsyal2512. Feel free to ask questions if you need any help.

**Comment by rahulsyal2512** [comment]
@championshuttler I have made necessary changes, please review it. Thank you for the guidance :)

**Comment by willdurand** [comment]
>     * Want to interact with addons.mozilla.org (AMO) programmatically?  Check out the documentation for the [Add-ons Servers documentation](https://addons-server.readthedocs.io/en/latest/index.html) for details about the AMO APIs, the APIs used by the [Add-ons Manager](https://blog.mozilla.org/firefox/add-ons-manager/).

@caitmuenster I find this paragraph hard to read. There are two repetitions:

- "the documentation for the Add-ons Servers documentation"
- "about the AMO APIs, the APIs"

I suggest we change the wording a bit, like:

> Want to interact with addons.mozilla.org (AMO) programmatically? Check out the Add-ons Servers documentation for details about the APIs used by AMO and the Add-ons Manager.

**Comment by caitmuenster** [comment]
Thanks for flagging @willdurand! Your wording makes sense -- let's go with that. 

@rahulsyal2512, if you could update your PR to reflect Will's wording above, that would be awesome! 

🙏🏼

**Comment by rahulsyal2512** [comment]
@caitmuenster I have changed the wording as per the comment.

**Comment by willdurand** [comment]
Thank you for your first contribution @rahulsyal2512!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF66, Win10x64

![image](https://user-images.githubusercontent.com/31961530/55856762-f3bb0f00-5b73-11e9-9f87-7359e6505b1d.png)
