### ISSUE TITLE
Hovering over relative time values on reviews should show time in absolute format

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#7849]
### Describe the problem and steps to reproduce it:

1. Go to a review page e.g. https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/
2. Try to find exactly when a review was posted, perhaps to see if any issues raised in the review might have been addressed in a recent update to the add-on.

### What happened?
There is just no way of knowing this. As long as it is reported in hours/days ago, you can calculate a bit[1], but once it gets to months/years ago, it is much less useful. Several extensions get updates more frequently than they get reviews e.g. https://addons.mozilla.org/en-US/firefox/addon/refined-github-/.

[1] The version history page uses absolute time so have to convert one way or the other.

### What did you expect to happen?
A tooltip containing absolute time should show up when hovering the `t time ago` link.

### Anything else we should know?
In the older design, reviews posted on older versions of an add-on were explicitly marked as such. That's not the only reason I'd prefer a way to see absolute time, but it was useful.

**Comment by willdurand** [comment]
That sounds like a good idea.

**Comment by ioanarusiczki** [comment]
@willdurand Verified the presence of the tooltip on AMO dev with FF66 (Win10 & Android 8.0)

The tooltip is present on all pages where a review is available - user profile page, detailed review page and an add-ons detail page when a user makes a review.

Desktop

![tooltip for timestamp desktop](https://user-images.githubusercontent.com/33448286/56212180-2bd5bc80-6062-11e9-9ba4-3fa1c9940b04.png)

When long tapping on Android device

![Android time stamp](https://user-images.githubusercontent.com/33448286/56212232-490a8b00-6062-11e9-95d5-9861efac427c.png)
