### ISSUE TITLE
Star reviews without accompanying text should be hidden/collapsed on review pages

### ISSUE THREAD

**Issue by FatOrangutan** [mozilla/addons-frontend#7850]
### Describe the problem and steps to reproduce it:

Go to a review page e.g. https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/

### What happened?
22/25 of the reviews on the first page carry no text.

### What did you expect to happen?
One of:
1) Reviews without text are entirely hidden. Downside: recent trend of even purely star rating reviews might convey useful information.
2) Such reviews are collapsed, and do not count towards the 25 limit on reviews shown per page. So each page will have 25 reviews+text, and theoretically any number of reviews without text.

### Anything else we should know?
Reviews that are just stars communicate little of value beyond what the average star rating (and its breakdown) at the left side of the page does. If I click to see the review page, I usually want to know *why* people rated the way they did.

**Comment by AlexandraMoga** [comment]
See that this was also reported in https://github.com/mozilla/addons-frontend/issues/7411

**Comment by willdurand** [comment]
> See that this was also reported in #7411


given that #7411 has been closed, I'm closing this one too.
