### ISSUE TITLE
Adding themes in the featured themes collection doesn't work

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7856]
As a followup for https://github.com/mozilla/addons-frontend/issues/7817 I tried with and admin account to add themes using the frontend collection URL https://addons-dev.allizom.org/en-US/firefox/collections/4757633/featured-personas/

Expected result:
All themes are displayed when See more link is clicked from AMO's homepage https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme

Actual result:
The themes are not visible here https://addons-dev.allizom.org/en-US/firefox/search/?featured=true&type=statictheme

Notes:
This is not reproducible when themes are removed from the collection. - FF66(Win10)
It is not reproducible for the other Mozilla collections from the homepage such as Feed readers, VPN solutions or Change up your tabs. 
On the server side there's a similar issue https://github.com/mozilla/addons-server/issues/10403

**Comment by willdurand** [comment]
@ioanarusiczki Isn't it a pure server issue? /cc @eviljeff

**Comment by eviljeff** [comment]
it's hard to say definitively without knowing exactly what the bug is, but I'd have thought it unlikely there is a frontend issue here - it's all just served from the API, as I understand it.

**Comment by ioanarusiczki** [comment]
@eviljeff I transferred this on server https://github.com/mozilla/addons-server/issues/11487
