### ISSUE TITLE
S3.Translator

### ISSUE THREAD

**Issue by salvapil** [mozilla/addons-frontend#7858]
### Anything else we should know?

Ho  sempre  usuto il componente aggiuntivo  "S3.Translator"  per  traduzioni  di  pagine  Web.
E'  stato  sempre  molto  efficace  e  eccelente  nella  traduzione,  nonché  di  facile  esecuzione.

Sul  PC  del  lavoro  è  ancora  in  funzione,  mentre  con  il  PC  di  casa  è  scomparso,  nè  si  trova  tra  i  componenti  aggiuntivi.

Di seguito  vi  invio  il  link  della  pagine  del  componente  aggiuntivo  "S3.Translator".

https://addons.mozilla.org/addon/s3google-translator/

Sarei  grato  conoscere  le  motivazioni  della  scomparsa.
grazie

**Comment by jvillalobos** [comment]
Any issues with the extension or an extension page missing from the site need to be brought up with the developer.
