### ISSUE TITLE
Replace `getLocalizedTextWithLinkParts` with `replaceStringsWithJSX`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7866]
Once the patch for #7597 lands, we can replace all calls to `getLocalizedTextWithLinkParts` with `replaceStringsWithJSX`.

**For QA:** the following pages will be affected by this change, please make sure information are still displayed correctly:

- the "guide" pages, e.g., https://addons-dev.allizom.org/en-US/firefox/guides/stay-safe-online/
- the "unsubscribe" page
- the version pages, e.g., https://addons-dev.allizom.org/en-US/firefox/addon/bitwarden-password-manager/versions/
- the review pages, e.g., https://addons-dev.allizom.org/en-US/firefox/addon/bitwarden-password-manager/reviews/

**Comment by ioanarusiczki** [comment]
Verified this on AMO dev - FF66(Win10). 
- all "Explore more" links work redirect as expected, sentences look as before.
- the unsubscribe edit profile link redirect as expected, text is fine.
- the license link redirects as expected.
- author and timpestamp are displayed and clicking the timestamp displays the permalink on top of the page.
