### ISSUE TITLE
Allow accessing product page by addon ID

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#7867]
Follow-up of https://github.com/mozilla/addons-server/issues/11154

We already support using an AMO ID or a slug in order to access an add-ons product page. We recently added support for using an add-on ID to reviewer and admin pages and want to do that for product pages as well.

In short: Let's add support for accessing a product page using `/firefox/addon/<addon-guid>`

**For QA:** an add-on can now be loaded by GUID (like it can be loaded by ID). The add-on detail page should load successfully when accessed with an URL containing a GUID. The URL will be changed with the add-on's slug.

In addition, a 404 should be displayed if an unknown GUID is used.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with FF66, Win10x64

- redirects to `/firefox/addon/<slug>`
https://addons-dev.allizom.org/en-US/firefox/addon/jid1-ZAdIEUB7XOzOJw@jetpack/
https://addons-dev.allizom.org/en-US/firefox/addon/{f9b9cdd3-91ae-476e-9c21-d5ecfce9889f}/

- this is a 404
https://addons-dev.allizom.org/en-US/firefox/addon/%7Bb585a736-4d7f-4692-b4ca-45a93f00c2/
