### ISSUE TITLE
delted dissenter. i am so disappointed by mozilla

### ISSUE THREAD

**Issue by hackoff** [mozilla/addons-frontend#7876]

**Comment by 1ykos** [comment]
I was under the impression firefox stood for my freedoms, but it does not.
Any recommendations for a browser that does believe in the freedoms of the software and the user?

**Comment by hackoff** [comment]
Hi, i recently got know that gab fotked their own version of browser based 
on Brave. You can give it a try

---------- Původní zpráva ----------
Od: Wolfgang Brehm 
Datum: 12. 4. 2019 v 09:09:27
Předmět: Re: [mozilla/addons-frontend] delted dissenter. i am so 
disappointed by mozilla (#7876)


I was under the impression firefox stood for my freedoms, but it does not.
Any recommendations for a browser that does believe in the freedoms of the 
software and the user?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
(https://github.com/mozilla/addons-frontend/issues/7876#issuecomment-482463936)
, or mute the thread
