### ISSUE TITLE
You removed Dissenter.  What is wrong with you?

### ISSUE THREAD

**Issue by draeftl0re** [mozilla/addons-frontend#7878]
You deleted free speech.  Congradulations, you are just as bad as the nazi party in 1940's and removing the ability to voice apposing opinions.

**Comment by mrksdiehl** [comment]
So I moved from chrome to Firefox because I wanted to get away from Big Brother. Now I need to move away from Firefox....

**Comment by 1ykos** [comment]
I will be switching to another browser, congratulations. I was under the impression firefox stood for my freedoms, but it does not.
Any recommendations?
