### ISSUE TITLE
Dissenter has been removed from the addons

### ISSUE THREAD

**Issue by 1ykos** [mozilla/addons-frontend#7879]
1. Search for dissenter on addons.mozilla.org
2. Dissenter is not found, no explanation given
3. I would expect mozilla to support free speech
4. People can install the extension manually by visiting https://dissenter.com/download and should be, just like me, on the lookout for a browser that believes in the freedoms of its users.

**Comment by willdurand** [comment]
This issue tracker does not accept issues for specific add-ons. The add-on you mentioned has been removed. You should contact the developer.

**Comment by 1ykos** [comment]
dissenter can't help me when mozilla removes the addon.

**Comment by alex2600** [comment]
The addon has been removed by mozilla. Not the addon developer.

**Comment by willdurand** [comment]
We are the developers of the website here, not the reviewers or anyone that can do anything about this specific addon. I recommend you to talk to the developer, who can talk to the reviewers
