### ISSUE TITLE
User profile avatar looks smaller than it's placeholder

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7880]
Followup for https://github.com/mozilla/addons-frontend/issues/7843

STR:
1. Sign in AMO and upload an image from edit profile page (take a look at it's placeholder displayed on view profile page).
2. Observe the uploaded image on view profile page

Expected result:
The avatar is at 64x64 pixels same size as it's placeholder.

Actual result:
The avatar is resized at 64x48 pixels. 

Notes:
Reproducible with custom icons displayed on their detail pages too - FF66(Win10). 

![avatar versus image](https://user-images.githubusercontent.com/33448286/56037415-e6e71880-5d37-11e9-8a7a-18fbe570c8cd.gif)

**Comment by willdurand** [comment]
@ioanarusiczki isn't it that the uploaded image has a landscape orientation?

**Comment by willdurand** [comment]
poke @ioanarusiczki

**Comment by avgupt** [comment]
@willdurand I was looking into this issue and I found the following:
1. If the uploaded image is square, it is displayed perfectly.
2. If the uploaded image is not square, the displayed image is resized according to the proportions.
I think this is the desired behaviour or should the image be resized into a square image (thus distorting its proportions)?

**Comment by willdurand** [comment]
@avgupt I am not sure to be honest. That's why I asked a question ot @ioanarusiczki

**Comment by ioanarusiczki** [comment]
@willdurand It's been a while since I filed this issue. Brb!

**Comment by ioanarusiczki** [comment]
@willdurand The picture is in landscape and it is not square. I tested again on AMO dev with FF73(Win10).

**Comment by avgupt** [comment]
Instead of stretching the image, we can crop it into a square image?

**Comment by ioanarusiczki** [comment]
@willdurand On the view profile - a square image is available now and looks good to me but I'm afraid this introduced a regression https://github.com/mozilla/addons-frontend/issues/9237

**Comment by ioanarusiczki** [comment]
@willdurand 
This is how the image looks croped on dev:

![image on dev](https://user-images.githubusercontent.com/33448286/77399906-02192f80-6db3-11ea-81de-74d8e7483084.png)

This is before the square crop on stage:

![this is on stage](https://user-images.githubusercontent.com/33448286/77399941-12c9a580-6db3-11ea-9d8e-d55a55c558fb.png)

I think that without a warning message that the image is going to be cropped this would not be an improvement but a problem for the user. I don't know how many of them are square.

Let me know what you think.

**Comment by willdurand** [comment]
Right, that does not sound optimal.

**Comment by willdurand** [comment]
We decided to revert the patch for this issue and to mark this issue as wontfix.
