### ISSUE TITLE
Server error is displayed when user makes a log out from edit profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7898]
STR:
1. Login AMO dev and go to edit profile page
2. Log out 
3. Observe the page

Expected result:
Log in to edit the profile.

Actual result:
Server error.

Notes:
Refreshing the page will displayed the log in blue button.
It is reproducible only on AMO dev - FF66 (Win10). 

![server error when logging out](https://user-images.githubusercontent.com/33448286/56135191-db465c80-5f98-11e9-9a22-4ac30030ccd8.gif)

**Comment by willdurand** [comment]
We fixed this issue in https://github.com/mozilla/addons-frontend/issues/5034, but the changes needed to fix https://github.com/mozilla/addons-frontend/issues/6769 re-introduced a variant of the issue.

**Comment by ioanarusiczki** [comment]
@willdurand It's no longer reproducible on AMO dev and stage - FF66(Win10).

![no longer reproducible](https://user-images.githubusercontent.com/33448286/56344524-4f197c80-61c6-11e9-95b6-f94e63d5d1db.gif)
