### ISSUE TITLE
Display issues for the star breakdown bar on android

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7903]
Followup for https://github.com/mozilla/addons-frontend/issues/7216

STR:
1. Load AMO dev on an android device and go to an add-on with ratings and reviews
2. Click a star breakdown bar - it will take you to the reviews page
3. Click again on any of the breakdown bars displayed and observe the bar

Expected results:
No display issues.

Actual result:
A black rectangle is visible around the tapped rating bar. 

Notes:
This ux issue is only visible on AMO dev with android devices - FF66 (android 8.0). 
It is not reproducible on desktop with Win10. Not reproducible on AMO stage or AMO prod.

![ux issue with the bar on android](https://user-images.githubusercontent.com/33448286/56215432-5b87c300-6068-11e9-8e72-1639234a87c4.png)

**Comment by willdurand** [comment]
This rectangle with dotted borders is probably the default focus style. We can also see similar rectangles on star numbers/number of reviews, on android only it seems.
