### ISSUE TITLE
Respond to prefers-color-scheme: dark

### ISSUE THREAD

**Issue by nt1m** [mozilla/addons-frontend#7907]
It would be nice if AMO could provide a dark mode when `prefers-color-scheme: dark` is true, especially given that add-ons can't style AMO.

**Comment by willdurand** [comment]
Given [the current support for this property](https://caniuse.com/#search=prefers-color-scheme), I doubt we'll implement that in the near future.

**Comment by bershanskiy** [comment]
`prefers-color-scheme` [already landed in Firefox 67](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) so it's probably already time to implement dark style for AMO.

**Comment by nt1m** [comment]
Hmm, can we please reopen this? Thank you. Support for this property is now pretty much in all latest browsers: https://caniuse.com/#search=prefers-color-scheme

**Comment by jvillalobos** [comment]
Is https://github.com/mozilla/addons/issues/1138 a duplicate of this one?

**Comment by nt1m** [comment]
@jvillalobos Yeah, pretty much.

**Comment by jvillalobos** [comment]
Okay, I'm reopening since this one has more detail. From the product perspective, I would stick to user-facing pages (so no devhub, no reviewer or admin tools), but we would still need the UX for it, which is unlikely to happen soon. I still want to have it in the backlog, though.

**Comment by avgupt** [comment]
Can I start working on this issue? Although it's a big issue, I think I can go on one page at a time.

**Comment by willdurand** [comment]
> Can I start working on this issue? Although it's a big issue, I think I can go on one page at a time.

I don't think so, we do not have a specification yet so we cannot work on this issue.

**Comment by rakleed** [comment]
.

**Comment by rakleed** [comment]
@willdurand @jvillalobos could you reopen the issue, please?

**Comment by willdurand** [comment]
Well, we could but the team does not have any plans to work on this issue unfortunately. Last week, I asked about that (technically not dark theme but "AMO redesign", which could possibly include dark theming) but we don't have much more information at the moment.

**Comment by dannycolin** [comment]
> Well, we could but the team does not have any immediate plans to work on this issue unfortunately.

That's ok. It could still stay open as P3 in this case. If not, I'm sure someone is going to open a new one pretty soon :p.
