### ISSUE TITLE
Add redirect(s) to Thunderbird addons site

### ISSUE THREAD

**Issue by logological** [mozilla/addons-frontend#7908]
Older (but presumably still supported) versions of Thunderbird display the page at https://addons.mozilla.org/en-US/firefox/thunderbird/dictionaries/ when users attempt to install a new dictionary via Edit->Preferences->Composition->Spelling->Download More Dictionaries.  Since Thunderbird and SeaMonkey addons have now been moved to their own website, this page now returns a 404 error ("Oops! We can’t find that page").

In the interests of not confusing hordes of Thunderbird users (who may be using slightly older versions in a corporate environment and therefore unable to update themselves), could you please add an HTTP redirect from https://addons.mozilla.org/en-US/firefox/thunderbird/dictionaries/ to https://addons.thunderbird.net/en-US/thunderbird/language-tools/ ?

**Comment by logological** [comment]
It occurs to me that the `/en-US` parts of both URLs might already be inserted by the web server as part of some localization detection.  Perhaps the URL Thunderbird is actually trying to open is https://addons.mozilla.org/firefox/thunderbird/dictionaries/ in which case the redirect should actually be from that URL to https://addons.thunderbird.net/thunderbird/language-tools/

**Comment by eviljeff** [comment]
I would be useful to get the exact url that Thunderbird is calling.  It must be defined in the code or default config for those old versions.

From the url I would have guessed it was `https://addons.mozilla.org/thunderbird/dictionaries/` instead (the `/firefox` is also added by middleware, like the `/en-US`) ... but https://addons.mozilla.org/thunderbird/dictionaries works.

**Comment by logological** [comment]
According to the config editor the URL (with some placeholders for string substitution) is `https://addons.mozilla.org/%LOCALE%/%APP%/dictionaries/`.

When searching the config editor for other instances of `addons.mozilla` I see a lot of other URLs that might also need redirecting.  Should I list them here?

**Comment by eviljeff** [comment]
https://addons.mozilla.org/en-US/thunderbird/dictionaries/ works too 😕 .   We really need the url that Thunderbird is initially trying to load to reproduce, before the various layers of redirects happen.

> I see a lot of other URLs that might also need redirecting. Should I list them here?

Not unless we know they're not working - as far as we know there are appropriate redirects for everything already.

**Comment by logological** [comment]
> We really need the url that Thunderbird is initially trying to load to reproduce, before the various layers of redirects happen.

I'm not sure I have any easy way of determining this.  I enabled HTTP(S) logging as described [on the wiki](https://wiki.mozilla.org/MailNews:Logging#Logging_prior_to_Thunderbird_55.0a1_.2F_SeaMonkey_2.52a1) but nothing gets written to the log file.  (MozillaZine suggests HTTP logging in the MailNews core is only for RSS feeds.)  Using tcpdump doesn't work because Thunderbird sends requests via HTTPS.  The only other thing I can think of is to install some sort of SSL-capable proxy server on my local machine, set Thunderbird to use it, and then examine the proxy logs.  I am not sure I have time for this at the moment.  If you can think of an easier solution, let me know.

**Comment by eviljeff** [comment]
what version of Thunderbird have this url?  (I'm on the latest beta, and it shows - or is redirected to - addon.thunderbird.net correctly)

**Comment by logological** [comment]
I suspect the URL was changed in or around release 60.0.

**Comment by eviljeff** [comment]
pre-60.0 is certainly unsupported for Firefox and AMO, but regardless, if there's a **valid*** URL that Thunderbird is accessing that AMO is incorrectly handing we can add a redirect, but we need the URL first because from our side we already think we have all appropriate redirects in place.

* https://addons.mozilla.org/en-US/firefox/thunderbird/dictionaries/ is not valid - but presumably there was a url that was valid in the past, and is still now (in theory), before its badly redirectly

**Comment by willdurand** [comment]
So is there anything we can actually do here? /cc @ev

**Comment by eviljeff** [comment]
We need some information about what URL isn't working.  If we get more information we can reopen but lets close for now.
