### ISSUE TITLE
Error: `text` does not appear to be compatible with the provided replacements

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7909]
https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/5572103/

```
Error: `text` does not appear to be compatible with the provided replacements
  File "/srv/code/src/core/i18n/utils.js", line 449, in replaceStringsWithJSX
    throw new Error(
  File "/srv/code/src/amo/components/AddonVersionCard/index.js", line 113, in AddonVersionCardBase
    const licenseLink = replaceStringsWithJSX({
  File "/srv/code/src/core/components/ServerHtml/index.js", line 206, in ServerHtml.renderToString [as render]
    const content = component ? ReactDOM.renderToString(component) : '';
  File "/srv/code/src/core/server/base.js", line 116, in renderToString
    return ReactDOM.renderToString(
  File "/srv/code/src/core/server/base.js", line 421, in renderHTML
    const finalHTML = renderHTML({ props, pageProps, store });
...
(16 additional frame(s) were not displayed)

Error: `text` does not appear to be compatible with the provided replacements
```

---

In prod, [this page](https://addons.mozilla.org/en-US/firefox/addon/google-translator-for-firefox/versions/) is currently broken because of the error above.

It happens because `license.name` is `null`, which is allowed according to https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#version-detail-object. It was silently failing before (I guess) but now that we have a new function that throws errors, this underlying/sleeping bug has been revealed.

**Comment by bqbn** [comment]
I just filed https://github.com/mozilla/addons-server/issues/11221, might be related.

**Comment by willdurand** [comment]
> I just filed [mozilla/addons-server#11221](https://github.com/mozilla/addons-server/issues/11221), might be related.

@bqbn yep, it's definitely related. Thanks!

**Comment by vcarciu** [comment]
Verified as fixed in prod.
