### ISSUE TITLE
Missing value when `license.name` is `null` in "More info" card

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7912]
### Describe the problem and steps to reproduce it:

1. Browse https://addons.allizom.org/en-US/firefox/addon/peasshee-hedder-swallamelo/
2. Observe the "More information" card

**Edit:** you can use this add-on in -dev: https://addons-dev.allizom.org/en-US/firefox/addon/gormine-dolphille-crant/

### What happened?

There is no value for "license":

![Screen Shot 2019-04-18 at 20 11 03](https://user-images.githubusercontent.com/217628/56381793-1f926080-6216-11e9-8317-1dd5a6e60435.png)

### What did you expect to happen?

The value should be "Custom License"

### Anything else we should know?

This is not a new bug but it was never an issue until https://github.com/mozilla/addons-frontend/issues/7909, which entirely broke a page. `license.name` can be `null`, which is why we do not have a value in the "More info" card. We should use a fallback value in that case.

addons-server (dev hub) uses "Custom License" as fallback. We should do that too.

**Comment by makkBit** [comment]
On it!

**Comment by vcarciu** [comment]
Verified as fixed for https://addons-dev.allizom.org/en-US/firefox/addon/gormine-dolphille-crant/ : 
![custom2](https://user-images.githubusercontent.com/1583842/57077320-6ee78f00-6cf4-11e9-9f29-e264014e7e4f.png)
