### ISSUE TITLE
Rename "unidentified license" to "Custom License" in `AddonVersionCard`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#7913]
### Describe the problem and steps to reproduce it:

1. Browse https://addons.allizom.org/en-US/firefox/addon/peasshee-hedder-swallamelo/versions/
2. Look at the first version entry

### What happened?

We see this sentence for the license:

![Screen Shot 2019-04-18 at 20 12 38](https://user-images.githubusercontent.com/217628/56381869-536d8600-6216-11e9-8163-28b8c7e1d576.png)

### What did you expect to happen?

The default/unidentified license should be "Custom License". The sentence should be:

![Screen Shot 2019-04-18 at 20 13 57](https://user-images.githubusercontent.com/217628/56381953-844dbb00-6216-11e9-8fe5-9bcae4fd9392.png)

### Anything else we should know?

This is related to https://github.com/mozilla/addons-frontend/issues/7909.

**Comment by xu3u4** [comment]
Hello, I would like to take this.

**Comment by willdurand** [comment]
@xu3u4 yep, thanks

**Comment by ioanarusiczki** [comment]
@willdurand I checked this with other addons on stage and prod - FF66(Win10) but I could not reproduce the issue.
The default text is "Custom License" when editing as a developer from dev hub. If I delete it and try to save changes "Custom License" automatically reapers. 
Perhaps for https://addons.allizom.org/en-US/firefox/addon/peasshee-hedder-swallamelo/versions/  the "an identified license" was manually typed in? 

![custom license is default](https://user-images.githubusercontent.com/33448286/56953498-63a23100-6b45-11e9-80b5-6c866354282c.gif)

**Comment by willdurand** [comment]
> @willdurand I checked this with other addons on stage and prod - FF66(Win10) but I could not reproduce the issue.
> The default text is "Custom License" when editing as a developer from dev hub. If I delete it and try to save changes "Custom License" automatically reapers.
> Perhaps for [addons.allizom.org/en-US/firefox/addon/peasshee-hedder-swallamelo/versions](https://addons.allizom.org/en-US/firefox/addon/peasshee-hedder-swallamelo/versions/) the "an identified license" was manually typed in?

This only works when the add-on does not have a licence name set. This is for very old add-ons and we manually changed the test add-ons using a SQL query to reproduce this issue. It's not possible to "unset" a license name anymore (_via_ Dev Hub or any other tool).

**Comment by vcarciu** [comment]
Verified as fixed for https://addons.allizom.org/en-US/firefox/addon/peasshee-hedder-swallamelo/versions/ : 
![custom](https://user-images.githubusercontent.com/1583842/57077192-12846f80-6cf4-11e9-86e1-66143b539560.png)
