### ISSUE TITLE
Oups, cette page est introuvable quand je clique sur le lien de mon extension

### ISSUE THREAD

**Issue by Awolnes** [mozilla/addons-frontend#7916]
dans la gestion de module et état et version il y a bien écrit approuvé  , mais aucun lien pour accéder au téléchargement

**Comment by Awolnes** [comment]
j'ai créé une extension il y a 3 Jours mais je ne peut pas le telecharger
via le site https://addons.mozilla.org/fr/firefox/

**Comment by willdurand** [comment]
@Awolnes quel est le nom de votre extension ? Pouvez-vous indiquer les liens qui ne fonctionnent pas précisément ?
