### ISSUE TITLE
Dissenter Blue missing

### ISSUE THREAD

**Issue by kabo** [mozilla/addons-frontend#7924]
### Describe the problem and steps to reproduce it:

I added Dissenter Blue (which was made to comply with Mozilla's policies) to my collection (https://addons.mozilla.org/en-US/firefox/collections/). Now it's not there anymore. If I use a link (https://addons.mozilla.org/en-US/firefox/addon/dissenter-blue-extension/) it's not there.

### What happened?

Yeah, that's what I'd like to know :)

### What did you expect to happen?

To find the Dissenter Blue addon.

**Comment by jvillalobos** [comment]
The extension does not comply with Mozilla’s Acceptable Use Policy (https://www.mozilla.org/about/legal/acceptable-use/) and is not suitable for being listed, so it was removed (same as the original Dissenter extension).
