### ISSUE TITLE
2 May homepage programming

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#7928]
For the **2 May** push, please update homepage programming to reflect details [here](https://docs.google.com/document/d/1g4RuGKW__eTHNd277rKPMM46ygonXzW68jSs2OXEkPM/edit#). 

@muffinresearch @bobsilverberg

**Comment by willdurand** [comment]
> For the **2 May** push

We do not have a push on May 2nd IIRC, so I guess that will be for May 9th?

**Comment by devaneymoz** [comment]
@willdurand No problem to push this back. Thanks for the update.

**Comment by ioanarusiczki** [comment]
@willdurand Shelves were updated on AMO dev and stage. - FF66(Win10).
Final validation, on prod.
