### ISSUE TITLE
The link for Amazon sendtokindle doesn't work.

### ISSUE THREAD

**Issue by tchaffee** [mozilla/addons-frontend#7931]
### Describe the problem and steps to reproduce it:

This page on Amazon has a link to sendtokindle which doesn't work:

https://www.amazon.com/gp/sendtokindle/firefox

### What happened?

It says "Oops! We can’t find that page"

### What did you expect to happen?

For it show the page for the addon.

### Anything else we should know?

The addon link is: https://addons.mozilla.org/en-US/firefox/addon/sendtokindle/

**Comment by jvillalobos** [comment]
The page is no longer available because the add-on doesn't work on current versions of Firefox. It looks like Amazon should take that page or link down.
