### ISSUE TITLE
Create a RecommendedBadge component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7957]
Supports #7794 

Create a component that will display the "Recommended" badge.

Note that I started by trying to alter the existing [`Badge`](https://github.com/mozilla/addons-frontend/blob/2019.04.25/src/ui/components/Badge/index.js) component to support the Recommended Badge, but there seem to be enough differences that it makes more sense to just create a unique component for this.

**Comment by bobsilverberg** [comment]
Here's a screenshot of the badge from the latest iteration of the InVision prototype:

<img width="695" alt="Screenshot 2019-05-03 16 59 36" src="https://user-images.githubusercontent.com/142755/57165370-e1c03b00-6dc4-11e9-832f-39fed8f49954.png">

**Comment by bobsilverberg** [comment]
@MeridelW Can you confirm what the text should be when hovering over the recommended badge? I've looked through some of the docs about this, but I'm not sure of the final decision. I currently have "Recommended extensions are safe, high-quality extensions."

**Comment by devaneymoz** [comment]
@bobsilverberg - @MeridelW is on parental leave. In her absence I'd like to propose different copy (because the current version seems to state unequivocally that Recommended extensions are "safe" and nowhere else are we making that definitive claim). 

I've discussed with @jorgev and and he's also okay with the following: "Recommended extensions are vetted for exceptional security and performance." 

But we should get final confirmation or copy direction from Michelle Heubusch (Meridel's manager). I will forward this issue to her.

**Comment by bobsilverberg** [comment]
> @bobsilverberg - @MeridelW is on parental leave. In her absence I'd like to propose different copy (because the current version seems to state unequivocally that Recommended extensions are "safe" and nowhere else are we making that definitive claim).
> 
> I've discussed with @jorgev and and he's also okay with the following: "Recommended extensions are vetted for exceptional security and performance."
> 
> But we should get final confirmation or copy direction from Michelle Heubusch (Meridel's manager). I will forward this issue to her.

Thanks @devaneymoz. I'll go with "Recommended extensions are vetted for exceptional security and performance." for now.

**Comment by mheubusch** [comment]
I think vetted is a fancy word, and I don't know that "exceptional" is meaningful in the context of security and performance. I'd say:  This extension passed a security and performance review. OR Firefox only recommends extensions that meet our standards for security and performance.

**Comment by devaneymoz** [comment]
Thanks for jumping in @mheubusch! 

Of the two options you provided I think the second one is closest to capturing the essence of the program, but is it too long for hover text? @bobsilverberg would this length of copy look alright in a hover state?

"Firefox only recommends extensions that meet our standards for security and performance."

**Comment by mheubusch** [comment]
If too long, maybe "This extension meets Firefox standards for security and performance."

**Comment by bobsilverberg** [comment]
> Thanks for jumping in @mheubusch!
> 
> Of the two options you provided I think the second one is closest to capturing the essence of the program, but is it too long for hover text? @bobsilverberg would this length of copy look alright in a hover state?
> 
> "Firefox only recommends extensions that meet our standards for security and performance."

The browser will deal with any length of hover text, but wrapping it and placing it wherever it can, so it's technically not too long. I'm not sure what sort of UX standards exist for the length of hover text. 

I will update the hover text to "Firefox only recommends extensions that meet our standards for security and performance." for now, and we can always change it later if we need to.
