### ISSUE TITLE
Remove Featured Extension badge

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#7960]
When we start showing the Recommended badge, we will no longer need the Featured Extension badge. ~~We'll still need the Featured Theme badge, however.~~

Updating this issue to include removal of the `enableFeatureRecommendedBadges` flag. Now that recommended badges have been enabled in production for some time, we can remove all of the code that deals with this flag.

For QA:

There should be no changes at all to the site as a result of landing this patch. A number of areas were touched which could be checked for regressions including:
- the home page
- the landing pages
- searching / search results
- badges

**Comment by bobsilverberg** [comment]
@jvillalobos I know this has been discussed extensively, but just to make sure this issue is accurate: after we "turn on" the recommended badges, we no longer will need the Featured Theme badge either - correct?

**Comment by jvillalobos** [comment]
Correct. We decided to use the Recommended badge instead of the Featured badge for themes (still determined by the Featured Themes collection), so the Featured badge should also go away for themes.

**Comment by ioanarusiczki** [comment]
The [release testing](https://testrail.stage.mozaws.net/index.php?/plans/view/21765) was completed on AMO stage with FF70(Win10) and FF68.2.0 (Android 8.0). 
No regressions found.
