### ISSUE TITLE
Update link from Recommended Badge to point to correct SUMO article

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7961]
The Recommended Badge, which is slated to land in #7958, is meant to link to a SUMO article, but that article has not been created yet. For now the badge, which will be hidden behind a flag for the foreseeable future, just links to the SUMO home page.

This issue is about updating the link to point to the appropriate place.

cc @devaneymoz as I think he might be in a position to update this issue when the article is ready.

**Comment by bobsilverberg** [comment]
@devaneymoz Do we have the final URL for this yet?

**Comment by devaneymoz** [comment]
@bobsilverberg I investigated and we do not yet have this link. I've reached out to Joni Savage (SUMO) to lend a hand getting it created. Hopefully we'll have it soon, at least a placeholder.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I investigated and we do not yet have this link. I've reached out to Joni Savage (SUMO) to lend a hand getting it created. Hopefully we'll have it soon, at least a placeholder.

Thanks @devaneymoz. Please update this issue once we have the correct URL.

**Comment by devaneymoz** [comment]
@bobsilverberg here are two versions of the same link destination:

(in-product version)
https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/recommended-extensions-program

(standard URL)
https://support.mozilla.org/en-US/kb/recommended-extensions-program

I'm not sure which you use in this case so I wanted to get you both.

**Comment by devaneymoz** [comment]
@bobsilverberg here are two versions of the same link destination...

(in-product)
https://support.mozilla.org/1/firefox/%VERSION%/%OS%/%LOCALE%/recommended-extensions-program

(standard URL)
https://support.mozilla.org/en-US/kb/recommended-extensions-program

I'm not sure which you use in this case so I wanted to get you both. Also, FYI, the actual content on the page is currently hidden.

**Comment by bobsilverberg** [comment]
Thanks @devaneymoz

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- clicking the `Recommended` badge from the add-ons detail page will open the SUMO article through 
https://support.mozilla.org/en-US/kb/recommended-extensions-program

![SUMO](https://user-images.githubusercontent.com/33448286/59091736-a57a8000-8918-11e9-9984-0f9eb0fb19d6.gif)

- clicking it while being in a search result will open the add-ons detail page but I believe this is as expected
 
![badge2](https://user-images.githubusercontent.com/33448286/59092013-3a7d7900-8919-11e9-9238-9b2507872a97.gif)

**Comment by ioanarusiczki** [comment]
@bobsilverberg Hmm, or not. I see https://github.com/mozilla/addons-frontend/issues/8102 filed for the search results.
