### ISSUE TITLE
500 error when accessing "/fi/firefox/tag/prefs.js"

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#7962]
**For QA:** URLs like `/fi/firefox/tag/prefs.js` should return a 404 in -dev and -stage. CDN domains are listed below (see: https://github.com/mozilla/addons-frontend/issues/7962#issuecomment-514283933).

---

### Describe the problem and steps to reproduce it:

We see a bunch 500 errors when `/fi/firefox/tag/prefs.js` endpoint is accessed.

Is this something that can be fixed?

### What happened?

Saw a bunch 500 in access logs.

```
1556827602.237 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=578&appver=30.0&atype=9&page=19616&cat=128 HTTP/1.1" 500 12110 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.658 0.658 "-"
1556827689.262 "157.55.39.139" "GET /fi/firefox/tag/prefs.js?appver=any&atype=9&page=20089&cat=106 HTTP/1.1" 500 11999 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.677 0.677 "-"
1556827693.765 "157.55.39.147" "GET /fi/firefox/tag/prefs.js?platform=all&appver=624&atype=9&page=17763&cat=104 HTTP/1.1" 500 12105 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.703 0.703 "-"
1556827698.408 "157.55.39.223" "GET /fi/firefox/tag/prefs.js?atype=9&page=19945&cat=100 HTTP/1.1" 500 11899 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.725 0.725 "-"
1556828056.074 "157.55.39.139" "GET /fi/firefox/tag/prefs.js?appver=31.0&atype=9&page=20226 HTTP/1.1" 500 11915 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.655 0.655 "-"
1556828119.266 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?appver=30.0&atype=9&page=20022&cat=100 HTTP/1.1" 500 12002 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.675 0.675 "-"
1556828940.759 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?appver=30.0&atype=9&page=17483&cat=124 HTTP/1.1" 500 12002 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.769 0.769 "-"
1556828943.574 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=all&atype=9&page=17405&cat=114 HTTP/1.1" 500 12007 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.698 0.698 "-"
1556828945.203 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=linux&appver=30.0&atype=9&page=20051&cat=106 HTTP/1.1" 500 12116 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.698 0.698 "-"
1556829193.473 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=all&appver=392&atype=9&page=20226&cat=126 HTTP/1.1" 500 12105 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.881 0.881 "-"
1556829615.197 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=all&atype=9&page=17566&cat=120 HTTP/1.1" 500 12007 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.960 0.960 "-"
1556829677.375 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=all&appver=31.0&atype=9&page=19904&cat=106 HTTP/1.1" 500 12110 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.699 0.699 "-"
1556829685.730 "157.55.39.223" "GET /fi/firefox/tag/prefs.js?platform=all&appver=31.0&atype=9&page=19906&cat=106 HTTP/1.1" 500 12110 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.663 0.663 "-"
1556829689.022 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?appver=4.0&atype=9&page=20231&cat=100 HTTP/1.1" 500 11999 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.018 0.018 "-"
1556830161.315 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=all&appver=28.0&atype=9&page=19650 HTTP/1.1" 500 12021 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.664 0.664 "-"
1556830457.208 "157.55.39.139" "GET /fi/firefox/tag/prefs.js?platform=all&atype=9&page=17826&cat=110 HTTP/1.1" 500 12007 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.969 0.969 "-"
1556830466.475 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?platform=all&appver=3.5&atype=9&page=17536&cat=102 HTTP/1.1" 500 12105 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.771 0.771 "-"
1556831181.480 "157.55.39.139" "GET /fi/firefox/tag/prefs.js?platform=linux&appver=31.0&atype=9&page=6&cat=124 HTTP/1.1" 500 12102 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.690 0.690 "-"
1556831185.488 "157.55.39.223" "GET /fi/firefox/tag/prefs.js?appver=3.5&atype=9&page=19135&cat=406 HTTP/1.1" 500 11999 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.646 0.646 "-"
1556831981.506 "157.55.39.139" "GET /fi/firefox/tag/prefs.js?appver=29.0&atype=9&page=17402&cat=112 HTTP/1.1" 500 12002 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.016 0.016 "-"
1556832252.400 "157.55.39.223" "GET /fi/firefox/tag/prefs.js?appver=20.0&atype=9&page=20213&cat=122 HTTP/1.1" 500 12002 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.660 0.660 "-"
1556832832.087 "207.46.13.153" "GET /fi/firefox/tag/prefs.js?appver=26.0&atype=9&page=17823&cat=126 HTTP/1.1" 500 12002 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.758 0.758 "-"
1556832836.209 "157.55.39.139" "GET /fi/firefox/tag/prefs.js?appver=30.0&atype=9&page=19613&cat=128 HTTP/1.1" 500 12002 "-" "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)" 0.697 0.697 "-"
```
### What did you expect to happen?

500 rate is one of the metrics that alerts operations, and we hope there is less noise in it if possible.

### Anything else we should know?

n/a

**Comment by willdurand** [comment]
I am not able to reproduce the 500 errors with the URLs pasted above :(

**Comment by bqbn** [comment]
It turns out the 500 comes from `addons.cdn.mozilla.net`, the site that hosts the static assets and user-uploaded contents.

```
$ curl -H "host: addons.cdn.mozilla.net" -I "https://addons.cdn.mozilla.net/fi/firefox/tag/prefs.js"
HTTP/1.1 500 Internal Server Error
Content-Type: text/html; charset=utf-8
Content-Length: 11623
Connection: keep-alive
... ...
```

Should this ticket be moved to addons-server repo then?

**Comment by willdurand** [comment]
whoa, I did not know addons-server was acting as a CDN too. This project does everything, heh. I think we should move this issue to addons-server indeed.

**Comment by willdurand** [comment]
Sentry logs here: https://sentry.prod.mozaws.net/operations/olympia-prod/issues/5328593/?query=is:unresolved

**Comment by willdurand** [comment]
It looks like a nginx misconfiguration because this path `/{locale}/firefox/tag/pref.js` should not be passed to addons-server but to the frontend. Could it be that the `.js` at the end makes nginx think it is an asset served by addons-server?

**Comment by eviljeff** [comment]
https://addons.cdn.mozilla.net/fi/firefox/tag/prefs.js is indeed throwing a addons-server 500 page, but it's because that url should have been passed to frontend via nginx (the /firefox/ views no longer exist on addons-server).  Is the CDN doing a redirect that bypasses the normal nginx rules?  https://addons.mozilla.org/fi/firefox/tag/prefs.js is correctly passed to frontend.

**Comment by bqbn** [comment]
Note that under the `addons.mozilla.org` domain, even `/{locale}/firefox/tag/pref.js` is NOT passed to the frontend. Per https://github.com/mozilla/addons-frontend/issues/5047, we 301 that path to `/<locale>/search/?tag=prefs.js` at the nginx level, which then is handled by the frontend.

Now, since we're talking about `addons.cdn.mozilla.net` domain, are you suggesting that we 301 `https://addons.cdn.mozilla.net/fi/firefox/tag/prefs.js` to `https://addons.mozilla.org/fi/firefox/search/?tag=prefs.js`, like we did in https://github.com/mozilla/addons-frontend/issues/5047?

Another option (which I prefer) is that, at the nginx level, we can simply return 404 for this path since it's the `addons.cdn.mozilla.net` domain, and semantically the CDN site doesn't have that path. 

And lastly, it looks like it is some search engines that are trying to reach this problematic url by the way.

**Comment by willdurand** [comment]
> Another option (which I prefer) is that, at the nginx level, we can simply return 404 for this path since it's the addons.cdn.mozilla.net domain, and semantically the CDN site doesn't have that path.

yep, I also think it'd be a good idea to return a 404.

**Comment by willdurand** [comment]
@bqbn can we do what you suggested above? (if not already done?)

**Comment by bqbn** [comment]
I'll move it to p3 because the issue is assigned and we know what needs to be done, and I can do it in a later time.

**Comment by willdurand** [comment]
@bqbn could you keep that in mind? It'd be nice to fix this issue. Maybe a good first issue for @oremj?

**Comment by bqbn** [comment]
Deployed to -dev and -stage.

**Comment by willdurand** [comment]
@bqbn what are the domains for -dev and -stage?

**Comment by bqbn** [comment]
addons-dev-cdn.allizom.org and addons-stage-cdn.allizom.org respectively.

**Comment by willdurand** [comment]
Awesome, thanks!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage.
The following URLs are throwing an nginx 404 now:

https://addons-dev-cdn.allizom.org/fi/firefox/tag/prefs.js
https://addons-stage-cdn.allizom.org/de/firefox/tag/prefs.js

![image](https://user-images.githubusercontent.com/31961530/61775261-40fc7d00-ae01-11e9-96d9-fe8a6a955a3b.png)

**Comment by bqbn** [comment]
Deployed to -prod yesterday.
