### ISSUE TITLE
Handle Fenix compatibility once it's possible to distinguish Fenix from Fennec

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#7963]
Original discussion is here https://github.com/mozilla-mobile/fenix/issues/1134 and the implementation is being discussed in https://bugzilla.mozilla.org/show_bug.cgi?id=1548428

Once a fix lands we'll need to see about updating our compat checks to make sure this works.

**Comment by cpeterso** [comment]
The Fenix and GV teams are considering three options at this time:
* Fenix 68 will spoof version 69 on AMO and SUMO. (Versions >= 69 is unambiguously not Fennec.)
* Fenix 68 will spoof a special version like "68.0.99" on AMO and SUMO. (This avoids unknown issues from pretending to be a different major version.)
* Or do nothing because Fennec 68 and Fenix 68 will overlap for only 6–8 weeks with a preview audience.

https://bugzilla.mozilla.org/show_bug.cgi?id=1548428
https://github.com/webcompat/webcompat.com/issues/2859

**Comment by willdurand** [comment]
@muffinresearch looks like we have a plan for Fenix https://github.com/mozilla-mobile/fenix/issues/1134#issuecomment-491412465, I'd be happy to work on this issue.

**Comment by cpeterso** [comment]
If you have any questions or concerns, just let me know. I'm hoping that any Fenix UA override will be compatible with your UA version check so you won't have to change your code again. :)

**Comment by cpeterso** [comment]
@jonalmeida is preparing to land a temporary Fenix UA override for addons.mozilla.org (and support.mozilla.org) in mozilla-mobile/fenix#1134. Fenix 68 will spoof version 69 on AMO and SUMO.

With the UA spoof, AMO and SUMO can assume that mobile Firefox UA with version <= 68.0 is Fennec and version >= 69.0 is Fenix forever.

**Comment by willdurand** [comment]
User-Agent sent to AMO (based on https://github.com/jonalmeida/fenix/commit/28e5251b03b50dc664e3feb05365818ed881547a):

```
Mozilla/5.0 (Android 9; Mobile; rv:69.0) Gecko/69.0 Firefox/69.0
```

**Comment by jonalmeida** [comment]
> User-Agent sent to AMO (based on [jonalmeida/fenix@28e5251](https://github.com/jonalmeida/fenix/commit/28e5251b03b50dc664e3feb05365818ed881547a)):
> 
> ```
> Mozilla/5.0 (Android 9; Mobile; rv:69.0) Gecko/69.0 Firefox/69.0
> ```

@willdurand Also note that 'Android 9' shows up for only my devices. That part will change depending on android OS version (I'm fixing my PR as well).

**Comment by willdurand** [comment]
> @willdurand Also note that 'Android 9' shows up for only my devices. That part will change depending on android OS version (I'm fixing my PR as well).

yep, I believe it's fine as far as we detect an Android OS, which should already be the case.

**Comment by ioanarusiczki** [comment]
@willdurand Please let me know if my way testing is correct:
I verified it with FF67 (Release) and FF69 (Nightly)  - on Win10 

- I went in about:config and there's the `devtools.responsive.userAgent` pref 
- I added the UA: `Mozilla/5.0 (Android 9; Mobile; rv:69.0) Gecko/69.0 Firefox/69.0`
The red message as shown [here](https://user-images.githubusercontent.com/217628/59351403-a0557080-8d1e-11e9-8d40-f5e6ce18aad2.png)  is displayed but only after I went in Responsive Design Mode and refreshed the page several times.  

- I added User Agent `UA: Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0`
No message is displayed (I only refreshed the page once and the red message was gone). 

- I deleted the UA (no string added to the pref)
No message is displayed (I had to refresh the page several times). 

I can't tell why the red message for Fenix shows with that delay but I hope my way of testing is fine. Please let me know. 
Thanks!

**Comment by willdurand** [comment]
mmh, I can't tell. I only used the responsive view during my tests, changing the UA from there.

**Comment by ioanarusiczki** [comment]
@willdurand I could not change back from `Mozilla/5.0 (Android 9; Mobile; rv:69.0) Gecko/69.0 Firefox/69.0` to ` Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0` using only the responsive view. 
But I think it should be fine. 

![user agent FF69](https://user-images.githubusercontent.com/33448286/59754983-d7cc9b80-928f-11e9-90d7-3e3a4f1ee3f6.gif)
