### ISSUE TITLE
All my addons except ONE have been set to LEGACY

### ISSUE THREAD

**Issue by FDNY8231** [mozilla/addons-frontend#7966]
Hi,
Using Firefox Version 67.0 64 bit on Windows 10

All my addons worked perfectly until a few minutes ago when I got a popup on the screen(didn't save) saying that some of my addons are no longer supported by Firefox. These have been added to a section called legacy extensions. Only ONE of my addons survived the axe. I am familiar with the fact that after version 57 some addons were not approved for use, but all of mine have been installed AFTER that version. The version 67.0 I just installed i guess today, but all those addons worked even afterwards and now they don't. I tried going back to older versions of FF and that didn't work. This is EXTREMELY aggravating ...  I want MY ADDONS BACK ... These are items that are USED daily, and there are no substitutes. Some I was FORCED to get after the Version 57 addon purge all in the name of my safety.

Any help would be appreciated .... Thanks

Below are screenshots of the issue ...

![screenshot3](https://user-images.githubusercontent.com/22012290/57172797-eac80100-6df2-11e9-8ecc-d853aeee8597.jpg)
![screenshot1](https://user-images.githubusercontent.com/22012290/57172798-eac80100-6df2-11e9-87ff-358ba95e4f61.jpg)
![screenshot2](https://user-images.githubusercontent.com/22012290/57172799-eb609780-6df2-11e9-92c5-78f98af30ef3.jpg)

**Comment by caitmuenster** [comment]
Hey there! This sounds related to a certificate issue that is currently ongoing. The team is currently working on a fix and we'll be providing updates on this thread: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047
