### ISSUE TITLE
Design the new mobile home page

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#797]
This is the design for the mobile home page on AMO. Here's the old one:

![image02](https://cloud.githubusercontent.com/assets/74699/16997325/b112a736-4e69-11e6-90c8-8bd473115e3f.png)

Supports: mozilla/addons#151

**Comment by pwalm** [comment]
First pass at a home screen!
![screen shot 2016-09-16 at 2 47 57 pm](https://cloud.githubusercontent.com/assets/6797635/18602297/f78357e8-7c1c-11e6-8041-7e70859a6d82.png)

Let's strip out... everything, and focus on search, use-case, and browse. We can move more traditional elements like charts and featured add-ons to extension home and theme home.

**Comment by kumar303** [comment]
Nice! I'm so happy to see the puzzle piece icon in play.

**Comment by muffinresearch** [comment]
We have this in the sketch file so I'm going to mark this closed.
