### ISSUE TITLE
Can't access Collections

### ISSUE THREAD

**Issue by Sidebottom1** [mozilla/addons-frontend#7970]
### What happened?
Out of nowhere, while using Firefox normally, my theme suddenly disabled itself and all my themes but one that I barely use anymore have been labeled as "could not be verified for use in firefox and has been disabled" so I looked up some info again about the retirement notification of persona plus where I got all my themes from and it said to "look at my collection."  So I logged into my firefox addons account and tried to view my collections again which I had added most of my themes to and it tells me there was an error and couldn't see my collections.
### What did you expect to happen?
My themes to work and my collections to be available.
### Anything else we should know?
I'm super fed up with this firefox color nonsense...

https://addons.mozilla.org/en-US/firefox/collections/

**Comment by Sidebottom1** [comment]
It seems there's just a global issue right now with 95%ish of all firefox certificates.  Hopefully the theme and my other addons which also seem to have broken will be fixed when the certificate issue is fixed, but I don't think that explains why the collections isn't working.  Time will tell

**Comment by wagnerand** [comment]
This is due to a certificate issue. Our team is currently working on a fix and we'll be providing updates on this thread: https://discourse.mozilla.org/t/certificate-issue-causing-add-ons-to-be-disabled-or-fail-to-install/39047/4
