### ISSUE TITLE
Add-on Download Attempt

### ISSUE THREAD

**Issue by oneeyedfranc** [mozilla/addons-frontend#7972]
### Describe the problem and steps to reproduce it:

When attempting to replace the firefox add-ons that were deleted by yesterday's bug, i got the following msg:  "The add-on downloaded from this site could not be installed because it appears to be corrupt."   This was repeated for the following add-ons:  Ghostery, AdBlock Plus, UBlock, NoScript.
![Add-on Download Attempt](https://user-images.githubusercontent.com/30188441/57184221-f1648000-6ea7-11e9-922f-812fd1e5fc21.jpg)

**Comment by wagnerand** [comment]
Hi there, this is related to https://github.com/mozilla/addons/issues/1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/

**Comment by oneeyedfranc** [comment]
i'm not a coder, am barely functional when it comes to computers.  would u
mind boiling down what i need to do to be able to reinstall my add-ons?  or
let me know that i'm fucked and need to stop using firefox?

**Comment by caitmuenster** [comment]
Hey @oneeyedfranc, we're not quite up and running yet. Please follow the instructions on https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ to get the temporary fix working (I promise no coding is required!).

**Comment by cup** [comment]
https://github.com/mozilla/addons/issues/1023
https://github.com/mozilla/addons/issues/1025

https://github.com/mozilla/addons-frontend/issues/7972

**Comment by cup** [comment]
as the hotfix requires submitting to an invasion of privacy, and the permanent
fix was only pushed for version 66 and 60, here is a fix for other versions:

https://support.mozilla.org/questions/1258165#answer-1218833

**Comment by wagnerand** [comment]
Please do not use unofficial workarounds from untrusted sources! They can have unintended or untested side-effects or could make things even worse. (Some already have, actually.)
