### ISSUE TITLE
Firefox Addons will not install, error reports file as corrupt.

### ISSUE THREAD

**Issue by JoelleEmmily** [mozilla/addons-frontend#7973]
### Describe the problem and steps to reproduce it:

Firefox Addons will not install, error reports file as corrupt.

### What happened?
Previous install of addon ceased functioning. Performed an uninstall/reinstall, install failed. Repeated on other addons which have also stopped functioning. 
### What did you expect to happen?
For the highly popular addon to work as described.
### Anything else we should know?
All addons have ceased functioning do to an inability to verify them. Found a firefox help page describing how to fix a seemingly similar issue, that did not work.

**Comment by JoelleEmmily** [comment]
Issue has resolved itself, likely server related.

**Comment by caitmuenster** [comment]
Thanks for checking in, @JoelleEmmily! This is related to an issue of an expired certificate. Glad that you've got the hotfix deployed; if anyone else comes across this issue, please refer to https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/ for updates.
