### ISSUE TITLE
FUCK YOU about new update with add-on

### ISSUE THREAD

**Issue by qetuowryip** [mozilla/addons-frontend#7974]
FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU     FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU 

What are you doing this mental retardation?
After the update, all add-ons can't be used.
The whole firefox becomes super hard to use
Why do you want to make this update without notifying the user in advance and let the user choose whether to update?

FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU  FUCK YOU

**Comment by caitmuenster** [comment]
This is due to a certificate expiration and you can follow progress updates on our blog: https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/  Also, we don't allow abuse like this on our repos.
