### ISSUE TITLE
Addon Problem

### ISSUE THREAD

**Issue by AssassinTR** [mozilla/addons-frontend#7976]
### Anything else we should know? I am Turkish my English is not good If I make grammer mistake. I am sorry

![resim](https://user-images.githubusercontent.com/46337813/57190801-4a272d80-6f27-11e9-865a-a002e8c2e57f.png)

**Comment by wagnerand** [comment]
Hi there, this is related to #1013. We have a temporary hotfix via our Studies program and are working on a more permanent fix. For more info please see blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox
