### ISSUE TITLE
Suggest older versions if current is not supported

### ISSUE THREAD

**Issue by AlexTalker** [mozilla/addons-frontend#7981]
### Describe the problem and steps to reproduce it:
Since all this events with broken signing I decided to downgrade by `Firefox` on `ESR` version.
Unfortunately, when I came to `Tree Style Tab` add-on page, it told me that version `65` is required for this add-on and suggested to upgrade. Now, if you use `ESR` or do not want to upgrade yet, you might want to look for an older version. But link to them is not quite as explicit as lets say for GitHub's `Release` tab.

### What happened?
It took me a bloody day to find out there's actually a version history.

### What did you expect to happen?
In addition to proposing a browser update, also propose link to version history.

### Anything else we should know?
https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/
Take a look from my perspective:
![image](https://user-images.githubusercontent.com/3531127/57215460-9ccf1b00-6ff5-11e9-9659-b957d44fa697.png)
I won't see the link unless I scroll down the page(for no particular reason) and it blends in the style.

**Comment by willdurand** [comment]
cc @jvillalobos and @pwalm

**Comment by jvillalobos** [comment]
We covered this topic in https://github.com/mozilla/addons-server/issues/5482 a while ago, and I think the reasons it's not practical haven't changed. /cc @diox for confirmation

**Comment by AlexTalker** [comment]
@jvillalobos Well, stylistically, the notification about incompatible version already looks as hell of a warning, so I think adding extra line to it won't do much harm. At least for certain versions(like ESR) where update is rare.

**Comment by diox** [comment]
> We covered this topic in mozilla/addons-server#5482 a while ago, and I think the reasons it's not practical haven't changed. /cc @diox for confirmation

Displaying the exact version that would be best compatible is costly in the add-on detail API, but the current notification could be reworded to suggest looking at older versions of the add-on or the design by updated to make it more obvious that this is possible. Obviously a product/ux decision though.
