### ISSUE TITLE
Connection error appears when add-on signature fails

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#7985]
The incident from last weekend revealed that AMO doesn't show an accurate error message if an add-on fails to install because of a signature failure. The error currently shown is 

> Download failed. Please check your connection.

This is inaccurate and misleading, since Firefox did download and process the file, but couldn't check the signature. I'm filing this issue to investigate whether Firefox returns anything useful for whatever installation error cases there are, and what AMO can do to provide better error messages.

---

**Update for QA:** this can be reproduced in -dev by setting the `extensions.webapi.testing` pref to `true` **and** `xpinstall.signatures.dev-root` to `false`.

**Comment by muffinresearch** [comment]
@jvillalobos looks like the event we're listening to that provides this message is `onDownloadFailed` see https://github.com/mozilla/addons-frontend/blob/924677b08d3b431153d11b995636751bd319188e/src/core/installAddon.js#L133 

I think we'll need to file a upstream bug in bugzilla for this and then update here to listen to a more specific event for this case.

**Comment by jvillalobos** [comment]
Thanks, it was filed already: https://bugzilla.mozilla.org/show_bug.cgi?id=1549704

**Comment by aswan** [comment]
When an error occurs, the `error` property on the install object should give you more detail:
https://searchfox.org/mozilla-central/source/dom/webidl/AddonManager.webidl#39

**Comment by AlexandraMoga** [comment]
Verified fixed on stage, AMO and Discopane, with Fx67, Win10x64 and Android 8.0

![image](https://user-images.githubusercontent.com/31961530/60583369-6878a080-9d93-11e9-8c8c-728990c27400.png)
