### ISSUE TITLE
Change colors of recommended badge

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7986]
This is a follow-up to #7958.

@brassy-, we landed the first iteration of the recommended badge, using some  [Firefox Orange](https://design.firefox.com/photon/visuals/color.html#orange) colors. We wanted to use photon colors, but I notice in the style guide that it says "Firefox Orange is only used for branding. Do not use it otherwise.", so maybe these need to change.

I'm currently using `Orange 70` for the default color and `Orange 50` for active/hover/focus.

Here are examples from our storybook:

<img width="162" alt="Screenshot 2019-05-07 10 45 02" src="https://user-images.githubusercontent.com/142755/57308944-3578a000-70b5-11e9-98c8-d146d1fcc96e.png">
<img width="175" alt="Screenshot 2019-05-07 10 45 41" src="https://user-images.githubusercontent.com/142755/57308999-4cb78d80-70b5-11e9-8f46-008b7fb1ccb4.png">

Can you please confirm what colors we should be using for normal and highlight?

**Comment by brassy-** [comment]
> This is a follow-up to #7958.
> 
> @brassy-, we landed the first iteration of the recommended badge, using some [Firefox Orange](https://design.firefox.com/photon/visuals/color.html#orange) colors. We wanted to use photon colors, but I notice in the style guide that it says "Firefox Orange is only used for branding. Do not use it otherwise.", so maybe these need to change.
> 
> I'm currently using `Orange 70` for the default color and `Orange 50` for active/hover/focus.
> 
> Here are examples from our storybook:
> 
> <img alt="Screenshot 2019-05-07 10 45 02" width="162" src="https://user-images.githubusercontent.com/142755/57308944-3578a000-70b5-11e9-98c8-d146d1fcc96e.png">
> 
> <img alt="Screenshot 2019-05-07 10 45 41" width="175" src="https://user-images.githubusercontent.com/142755/57308999-4cb78d80-70b5-11e9-8f46-008b7fb1ccb4.png">
> 
> Can you please confirm what colors we should be using for normal and highlight?

Considering future changing, it's ok to use the color orange here.

Please, always use `Orange 80` for the label for accessibility.

Default: `Orange 50`
Active/hover/focus: `Orange 60`

Thank you

**Comment by bobsilverberg** [comment]
> > Can you please confirm what colors we should be using for normal and highlight?
> 
> Considering future changing, it's ok to use the color orange here.
> 
> Please, always use `Orange 80` for the label for accessibility.
>

Sorry, I'm not sure what this means.
 
> Default: `Orange 50`
> Active/hover/focus: `Orange 60`
> 
> Thank you

**Comment by brassy-** [comment]
> > > Can you please confirm what colors we should be using for normal and highlight?
> > 
> > 
> > Considering future changing, it's ok to use the color orange here.
> > Please, always use `Orange 80` for the label for accessibility.
> 
> Sorry, I'm not sure what this means.
> 
The word `Recommended` uses `Orange 80` .

**Comment by bobsilverberg** [comment]
For reference, the new prototype is available at: https://mozilla.invisionapp.com/d/main#/console/16890313/351565696/preview, and looks like this:

<img width="706" alt="Screenshot 2019-05-09 13 08 23" src="https://user-images.githubusercontent.com/142755/57472497-8fb36580-725b-11e9-97c6-262602e66110.png">
