### ISSUE TITLE
Design the new login flow

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#799]
This login flow should just be Firefox Accounts only though, so might be a bit simpler. Here's the old one:

![image07](https://cloud.githubusercontent.com/assets/74699/16997407/23a4fea2-4e6a-11e6-9c1e-c42a5b2a69ef.png)

Supports: mozilla/addons#151

**Comment by pwalm** [comment]
Going to have a chat with Ryan Feeley about this!

**Comment by muffinresearch** [comment]
This is all FXA so I don't think there's anything to do here. Closing for now. We can re-open or refile if there's something we need action on.
