### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by GlenCooper** [mozilla/addons-frontend#7992]
### Describe the problem and steps to reproduce it:
When viewing page http://kb.mozillazine.org/Profile_Manager#Accessing_the_Profile_Manager, if you scroll down to the External Links section, when you click on the "Open Profile Folder extension" hyperlink, it sends that click to https://addons.mozilla.org/firefox/545, which is 404'ed.

### What happened?
404

### What did you expect to happen?
find the relevant content, or delete the external link

### Anything else we should know?
BUY BITCOIN

**Comment by jvillalobos** [comment]
Mozillazine is not a Mozilla property. Please report this problem to them.
