### ISSUE TITLE
Only show recommended badge for extensions

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#7995]
This is a follow-up to #7794.

As discussed in IRC, the recommended badge doesn't look great for themes, and we have no current intention to use it for themes, so let's only ever show it for extensions, for now.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on AMO dev - with FF66(Win10&Android 8.0). 
Extension types which don't show the badge (even if I set them from admin tools -> in Discovery items + extension version page the same way I tested for https://github.com/mozilla/addons-frontend/issues/7794):
- static themes  on Windows and Android - the featured labels continue to be displayed
- dictionaries and language packs on Windows and Android 
- add-ons - when the "Add-ons for Android" filter is set then the "Recommended" badge is no longer available and which is expected as described here https://github.com/mozilla/addons-frontend/issues/7794#issue-427045338

![badge not on android](https://user-images.githubusercontent.com/33448286/57626946-a4676480-759f-11e9-8209-16e6bd700143.gif)
