### ISSUE TITLE
User profile lets you enter broken HTML

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#7998]
Steps to reproduce:
1. Open edit profile page
2. Add the following in the bio:
```
<ol>
</li>test1<li>
</li>test1<li>
</li>test1<li>
</li>test1<li>
</ol>

<ul>
</li>test1<li>
</li>test1<li>
</li>test1<li>
</li>test1<li>
</ul>
```
3. Save and observe the user bio

Expected results:
The page should warn you that you entered broken HTML

Actual results:
The ordered list is not correctly aligned
The unordered list is missing the bullets 
 
Notes:
Verified in FF68(Win10)x64 Issue can be reproduced in amo-prod
Screenshot for this issue:
![ListBioIssue](https://user-images.githubusercontent.com/15685441/57472518-46ccd280-7296-11e9-86e2-457b4db6512f.png)

**Comment by kumar303** [comment]
I'm not sure if there's much we can do about broken HTML (we should probably warn about it, though). 

Can you try it again with valid HTML? Like this:

```
<ol>
<li>test1</li>
<li>test1</li>
<li>test1</li>
<li>test1</li>
</ol>

<ul>
<li>test1</li>
<li>test1</li>
<li>test1</li>
<li>test1</li>
</ul>
```

**Comment by kumar303** [comment]
I updated the issue to make it about telling the user that they entered broken HTML. We should do this.

**Comment by madalincm** [comment]
I tried with the valid HMTL and the ordered list is displayed correctly. The unordered list still has no bullets.

**Comment by kumar303** [comment]
> The unordered list still has no bullets.

Hmm, that might be on purpose. I'm not sure.

**Comment by kumar303** [comment]
> The unordered list still has no bullets.

On second thought, user-entered unordered lists should definitely show bullets. Otherwise, it's not useful to put an unordered list in a bio. Can you file a separate issue?

**Comment by willdurand** [comment]
The original issue is already covered by https://github.com/mozilla/addons-server/issues/10832. There is nothing we can do to address that in addons-frontend.
