### ISSUE TITLE
Design the new details page for an add-on

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#800]
A nice new details page. Here's the old one:

![image04](https://cloud.githubusercontent.com/assets/74699/16997426/40cd7914-4e6a-11e6-965f-cb92835279b5.png)

Supports: mozilla/addons#151

**Comment by pwalm** [comment]
**First pass (Aug 8)**

![extension detail - xxhdi](https://cloud.githubusercontent.com/assets/6797635/17502697/e8ceb1a8-5d9e-11e6-946e-e6979d132088.png)

**Comment by pwalm** [comment]
Revised!
![extension detail - xxhdi](https://cloud.githubusercontent.com/assets/6797635/18603785/4e122ab0-7c29-11e6-83f4-9049f9a43fa6.png)

**Comment by muffinresearch** [comment]
Most recent designs are in the sketch file so I'm going to close this one.
