### ISSUE TITLE
Image Collecting Button

### ISSUE THREAD

**Issue by asoknath** [mozilla/addons-frontend#8003]
### Describe the problem and steps to reproduce it:
Firefox Plug-in for collecting image from other websites Not Found

Trying to access the Firefox plug-in from http://indulgy.com/do/tools
### What happened?
Firefox "can't find" the Plug-in
### What did you expect to happen?
To install a button to collect the picture dashboard page link for client to visit
### Anything else we should know?
Is there other such applications to help getting links to image store board for shoppers to visit

![WebButton](https://user-images.githubusercontent.com/8018282/57570698-74468700-7422-11e9-8c1b-9ee99d33bc2d.png)
![indulgyLinkFailure](https://user-images.githubusercontent.com/8018282/57570704-7d375880-7422-11e9-8557-c92025ca2031.png)

**Comment by jvillalobos** [comment]
That is up to the website owner to correct. We can't do anything about it.
