### ISSUE TITLE
Firefox Click&Clean Extension Install Fail

### ISSUE THREAD

**Issue by JussM3** [mozilla/addons-frontend#8006]
### Describe the problem and steps to reproduce it:

When trying to add the following Firefox Extension from hotcleaner.com **https://www.hotcleaner.com/clickclean_firefox.html**
the response from firefox is:
"Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes."

### What happened?
Failed to install extension

### What did you expect to happen?
Installation of extension

**Comment by willdurand** [comment]
It looks like this add-on is not available anymore. It could be that the extension isn't maintained by the developer or that the latest version did not pass a review. You should start by contacting the developer of this add-on, I think.
