### ISSUE TITLE
Design the new details page for a theme

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#801]
Themes are special. Here's the old one:

![image03](https://cloud.githubusercontent.com/assets/74699/16997451/5fbc28e8-4e6a-11e6-96be-2190f0833746.png)

Supports: mozilla/addons#151

**Comment by pwalm** [comment]
![theme detail - xxhdi](https://cloud.githubusercontent.com/assets/6797635/18603726/fa4c4d66-7c28-11e6-86b4-805434dc029e.png)

**Comment by muffinresearch** [comment]
Most recent designs are in the sketch file so I'm going to close this one.
