### ISSUE TITLE
Design the new rate add-on flow

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#802]
Rating is about one of the few interactions that a user can do on mobile that causes a change. Here's the old one:

![image01](https://cloud.githubusercontent.com/assets/74699/16997482/89cacee6-4e6a-11e6-80b5-4d8d7432ac49.png)

![image05](https://cloud.githubusercontent.com/assets/74699/16997487/8c438d5c-4e6a-11e6-9ed5-102aa80e369f.png)

Would be good to know things like:
* what to do when not logged in
* the flow through to completion etc.
Supports: mozilla/addons#151

**Comment by kumar303** [comment]
this new flow is being designed in https://github.com/mozilla/addons-frontend/issues/927
