### ISSUE TITLE
"cannot update a WebExtensions add-on with a legacy add-on."

### ISSUE THREAD

**Issue by RealRaven2000** [mozilla/addons-frontend#8020]
### Describe the problem and steps to reproduce it:

I am trying to upload a bugfix for quickFilters for my ESR users and ATN won't let me now. I last week u9ploaded 2 versions - 3.12 (compatible with THunderbird 60ESR, based on install.rdf) and 3.12.1 (compatible with THunderbird 62beta - 68beta, with manifest.json).  one of my 13,000+ users found a bug, so I tried to upload a new "legacy" version 3.12.2.

### What happened?

A validation error:
"You cannot update a WebExtensions add-on with a legacy add-on. Your users would not be able to use your new version because Firefox does not support this type of update."

### What did you expect to happen?
ATN should allow hosting both versions so that my beta users can try out the new version and my existing ESR users (the vast majority) can be provided with updates. It is currently not possible to build a single version that supports both, so my expectation is that I can upload 2 different versions (which are managed via minver / maxver) to serve both groups - obviously with slightly differing version numbers. Also, it seems the "firefox / Webextensions" part of the error somehow probably doesn't really apply to Thunderbird.

### Anything else we should know?

https://i.imgur.com/wGQ2nGf.png
Is there a workaround? Can I delete the fake "WebExtension" version in oirder to reset the Add-ons status  so I can at least serve my existing users?

**Comment by kewisch** [comment]
addons-frontend is for AMO, please resolve this on thundernest/addons-server instead.

**Comment by RealRaven2000** [comment]
> 
> 
> addons-frontend is for AMO, please resolve this on thundernest/addons-server instead.

ok - added https://github.com/thundernest/addons-server/issues/87.
