### ISSUE TITLE
Replace "Featured" with "Recommended" in AMO Search

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8027]
Replace all references to "Featured" having to do with Search functionality to say "Recommended". This includes:
- the label for the check box in the search filters which currently says "Featured add-ons only" should be replaced with a label that says "Recommended add-ons only"
- the page title that is displayed when searching for featured add-ons which starts with the word "Featured" (e.g., "Featured extensions - Add-ons for Firefox"), should be changed to start with the word "Recommended".
- ~~we currently have an install source for "featured" (i.e., urls include "src=featured"). I assume we should also change that to be "recommended"?~~ @jvillalobos indicated that we should not change this.

As part of this we should update the filter/url param to use "recommended" instead of "featured" when performing a search.

@jvillalobos Can you please confirm all of the above, and let me know if there's anything you can think of regarding searching that I have missed?

**Comment by jvillalobos** [comment]
> we currently have an install source for "featured" (i.e., urls include "src=featured")

Let's keep this one, because it's used in developer stats dashboards to track downloads. I expect us to drop `src` when we redo our stats (maybe this year) so I think it's okay to have some temporary inconsistency.

Otherwise looks good.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO dev - FF67(Win10).
- the label for the check box in the search filters says "Recommended add-ons only"
- when searching the ?recommended=true is available instead of ?featured=true
- `src=featured` is still present

> the page title that is displayed when searching for featured add-ons which starts with the word >"Featured" (e.g., "Featured extensions - Add-ons for Firefox"), should be changed to start with the word >"Recommended".

While searching using the `recommended` filter the title of the page is "_N_ results found" or I did not understand what you mean ?

**Comment by bobsilverberg** [comment]
> @bobsilverberg Verified on AMO dev - FF67(Win10).
> 
> > the page title that is displayed when searching for featured add-ons which starts with the word >"Featured" (e.g., "Featured extensions - Add-ons for Firefox"), should be changed to start with the word >"Recommended".
> 
> While searching using the `recommended` filter the title of the page is "_N_ results found" or I did not understand what you mean ?

It's not the visible header on the page, it's the actual title of the html document, which you can see as the title of the tab. 

For example:

![Screenshot 2019-05-15 14 52 51](https://user-images.githubusercontent.com/142755/57807354-00acbe80-772f-11e9-8844-ad983ae5cfed.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg Tab's title then :) ok, while searching for recommended is now "Recommended add-ons - Add-ons for Firefox (en-US). " (changing locale works).

![search by recommended](https://user-images.githubusercontent.com/33448286/58307987-f5c9ec00-7e08-11e9-9a5b-6dfa8348dc98.png)
