### ISSUE TITLE
Replace Featured shelves with Recommended shelves

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8028]
This is a spin-off from #8050 which captures the decision made and described at https://github.com/mozilla/addons-frontend/issues/8050#issuecomment-496511219.

On the Extensions and Themes pages, we should replace the "Featured" shelf with a "Recommended" shelf. These will include only recommended add-ons and will be sorted by `random`.

**Comment by bobsilverberg** [comment]
@jvillalobos @devaneymoz I have another question about landing page shelves. There is currently a link in the upper right-hand corner of each shelf that takes the user to a Search Results page based on the criteria for the shelf. E.g., the link from the "Top rated extensions" shelf points to https://addons.mozilla.org/en-US/firefox/search/?sort=rating&type=extension. As we are going to have only recommended add-ons in these shelves on the extension landing page, should this search link also include `recommended=true` so that the search results page linked to is also restricted to recommended add-ons only?

**Comment by jvillalobos** [comment]
Yes.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on AMO dev with FF67(Win10).
**Homepage**
The Featured shelves were replaced with Recommended sorted by `random`. 
Recommended Extensions 
https://addons-dev.allizom.org/en-US/firefox/search/?recommended=true&sort=random&type=extension
Recommended themes
https://addons-dev.allizom.org/en-US/firefox/search/?recommended=true&sort=random&type=statictheme
**Extensions landing page**
See more top rated extensions 
https://addons-dev.allizom.org/en-US/firefox/search/?recommended=true&sort=rating&type=extension
See more trending extensions 
https://addons-dev.allizom.org/en-US/firefox/search/?recommended=true&sort=hotness&type=extension
**Themes landing page** 
See more top rated themes and See more trending themes still return ?sort=rating&type=statictheme 
?sort=hotness&type=statictheme without `recommended=true`.

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. My apologies but I cannot tell what above is an expression of verification and what, if anything, is an outstanding question. Please not that this issue was only about changing the Featured shelves to Recommended shelves and did not include any changes to other shelves, although those were dealt with via other issues.

**Comment by ioanarusiczki** [comment]
@bobsilverberg As discussed, the theme landing page is fine https://github.com/mozilla/addons-frontend/issues/8050#issuecomment-495412959
Verified on AMO dev - FF67(Win10).
