### ISSUE TITLE
Design the new categories page

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#803]
Here's the old one:

![image08](https://cloud.githubusercontent.com/assets/74699/16997514/b04e277a-4e6a-11e6-915b-412891c98889.png)

Supports: mozilla/addons#151

**Comment by pwalm** [comment]
![extension categories - xxhdi](https://cloud.githubusercontent.com/assets/6797635/18603686/b6b20cee-7c28-11e6-82c2-b01e93087e2f.png)
![theme categories - xxhdi](https://cloud.githubusercontent.com/assets/6797635/18603689/b929c9c6-7c28-11e6-97f3-2d9925cc6049.png)

**Comment by muffinresearch** [comment]
Most recent designs are in the sketch file so I'm going to close this one.
