### ISSUE TITLE
Display recommended bage for all add-on types

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8035]
As currently implemented, the Recommended badge only appears for extensions. A decision was made to display it for all add-on types, not just extensions. This issue is about removing the restriction(s) that make the badge exclusive to extensions.

Note that this also changes the behaviour of the "Featured" badge when the "Recommended" feature is enabled. With this patch, no add-on types will display a "Featured" badge when the "Recommended" feature is enabled.

**Comment by bobsilverberg** [comment]
@jvillalobos Can you please confirm that this is what we want to do.

**Comment by jvillalobos** [comment]
That's what we want, yes.

**Comment by AlexandraMoga** [comment]
Verified on -dev with Fx67, Win10x64
The recommended badge is present now for all add-on types:

Themes:
https://addons-dev.allizom.org/en-US/firefox/addon/aspergers-color-dance/?src=search
I'm adding some screenshots to show how the theme labels are looking now:
![image](https://user-images.githubusercontent.com/31961530/58624700-8c028400-82d9-11e9-8dd4-96d6048af2e1.png)

![image](https://user-images.githubusercontent.com/31961530/58624715-93299200-82d9-11e9-8780-10a8d38191ac.png)


Dictionaries:
https://addons-dev.allizom.org/en-US/firefox/addon/frisian-words/?src=search
Lang pack;
https://addons-dev.allizom.org/en-US/firefox/addon/georgian-language-pack/
Search Tool:
https://addons-dev.allizom.org/en-US/firefox/addon/eccellio-science/?src=search

The badge is alo displayed in search results and in autocomplete

**Comment by willdurand** [comment]
@bobsilverberg on the screenshots above, the recommended badge does not look aligned with the other badges.

**Comment by AlexandraMoga** [comment]
There is indeed a misalignment on the theme details page (although it is unlikely that themes will show any other badge besides the recommended badge)

![image](https://user-images.githubusercontent.com/31961530/58793882-b452f100-85ff-11e9-8885-5a50e1c60e84.png)
