### ISSUE TITLE
Design the new themes listing page

### ISSUE THREAD

**Issue by andymckay** [mozilla/addons-frontend#804]
Looks like one exists for themes specifically:

![image00](https://cloud.githubusercontent.com/assets/74699/16997537/c64f7696-4e6a-11e6-81e0-34bce38bda0b.png)

Supports: mozilla/addons#151

**Comment by pwalm** [comment]
![themes home - xxhdi](https://cloud.githubusercontent.com/assets/6797635/18603670/860876be-7c28-11e6-8e4d-422b43a5e31a.png)

**Comment by muffinresearch** [comment]
Most recent designs are in the sketch file so I'm going to close this one.
