### ISSUE TITLE
Fix up the css for RecommendedBadge

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8040]
There are some issues with the current css for the new RecommendedBadge component, which can be seen in my PR to add it to the [Search results](https://github.com/mozilla/addons-frontend/pull/7988). For example, when the size of the add-on card gets too small, the text is moved below the shape:

![Screenshot 2019-05-17 11 08 30](https://user-images.githubusercontent.com/142755/57937548-22738600-7894-11e9-812b-4b0d69326b85.png)

I am also having trouble changing the size of the badge for the search results without breaking the css entirely.

@kumar303 said he'd be willing to take a look and see if he can figure out some more robust css for it.

**Comment by kumar303** [comment]
Sure, I can look. @bobsilverberg did you end up getting a new SVG with the circle?

**Comment by kumar303** [comment]
> Sure, I can look. @bobsilverberg did you end up getting a new SVG with the circle?

Ah, yes, I see it in https://github.com/mozilla/addons-frontend/pull/8037 That might make things easier.

**Comment by bobsilverberg** [comment]
> > Sure, I can look. @bobsilverberg did you end up getting a new SVG with the circle?
> 
> Ah, yes, I see it in #8037 That might make things easier.

Yes, that has now landed so the [svg with the circle](https://github.com/mozilla/addons-frontend/blob/master/src/ui/components/Icon/img/recommended-circle.svg) is now available in the repo.

**Comment by kumar303** [comment]
There is a small screen issue that also needs addressing: https://github.com/mozilla/addons-frontend/pull/7988#issuecomment-490994429

**Comment by ioanarusiczki** [comment]
@bobsilverberg I was going to file a followup today, I've been noticing this too.
I think it should be ok now because I could no longer reproduce the issue (verified on AMO dev with FF67Win10). 

![resize](https://user-images.githubusercontent.com/33448286/58409560-02547b80-8079-11e9-8356-bc21477da0b9.gif)
