### ISSUE TITLE
S3.Translator Extension for Mozilla is not working

### ISSUE THREAD

**Issue by M-Zishan** [mozilla/addons-frontend#8053]

**Comment by muffinresearch** [comment]
@M-Zishan From the description it's unclear what the issue is. Please can you provide as much information as possible so that we can understand what the issue is?

Please include screenshots and URLs so we know where on the website the problem is occurring.

**Comment by grahamperrin** [comment]
Wild guess: https://techdows.com/2019/01/mozilla-pulls-s3-translator-and-screengrab-firefox-add-ons-from-amo.html ?

**Comment by willdurand** [comment]
@jvillalobos or @wagnerand could you give some more context about S3.Translator not being listed on AMO anymore? (unless this has been written somewhere already)

**Comment by wagnerand** [comment]
The add-on is unavailable due to review issues. It's up to the developer to resolve them.
