### ISSUE TITLE
Lightning i can't install it

### ISSUE THREAD

**Issue by Soriuky0** [mozilla/addons-frontend#8061]

**Comment by Soriuky0** [comment]
Lighting 4.0.5.2 for Thunderbird 38 is available here
https://addons.mozilla.org/addon/lightning/versions/4.0.5.2
if i try to gon on this page 
https://addons.mozilla.org/it/firefox/addon/lightning/versions/
i see this

**Comment by jvillalobos** [comment]
Thunderbird add-ons are available at https://addons.thunderbird.net/
