### ISSUE TITLE
Support Twitter card

### ISSUE THREAD

**Issue by rugk** [mozilla/addons-frontend#8066]
See https://github.com/mozilla/addons/issues/1055

Here is the markup you should support: https://github.com/mozilla/addons/issues/1055#issuecomment-494951763

**Comment by rugk** [comment]
Why have I been assigned?

**Comment by willdurand** [comment]
> Why have I been assigned?

You wrote a patch for it.

**Comment by rugk** [comment]
I did? How come, I don't know this?

Seriously, you mean https://github.com/mozilla/addons/issues/1055#issuecomment-494951763?
This was just copied from GitHub.
Don't know whether this could be integareted. But I can have a look, if you want.

**Comment by willdurand** [comment]
> I did? How come, I don't know this?

whoops, indeed. @voronianski actually wrote the patch 😅

**Comment by rugk** [comment]
Is this change already live, because in my test right now, it did not work:
![grafik](https://user-images.githubusercontent.com/11966684/65387225-61837d80-dd45-11e9-8f68-10ae35e20288.png)

Ah okay, just saw the milestone… okay :smile:

**Comment by ioanarusiczki** [comment]
@willdurand Please add some STR for qa.
Thanks!

**Comment by rugk** [comment]
## STR
1. Attach/add an add-on entry with [this image](https://github.com/rugk/offline-qr-code/blob/master/assets/repo-card-opengraph.png) as the first one in your screenshots on AMO.
2. Tweet a link on Twitter linking to your add-on URL, or e.g. toot it on a Mastodon.

## What should happen
It should look like this:
https://github.com/mozilla/addons/issues/1055#issuecomment-494547261

## What should not happen
It should *not* look like this:
https://github.com/mozilla/addons-frontend/issues/8066#issuecomment-533877823

**Comment by willdurand** [comment]
@rugk is right but that won't work in -dev or stage because the [Twitter Validator](https://cards-dev.twitter.com/validator) won't work (and same for twitter.com). The `robots.txt` in these envs prevent robots to parse the pages.

You can check the generated HTML and make sure two need `meta` tags have been added for web extensions: `twitter:site` and `twitter:card`, only for the Homepage and web extension detail pages.

**Comment by ioanarusiczki** [comment]
@willdurand @rugk 
I verified this in AMO stage with FF69(Win10).
- twitter:site and twitter:card are available on web extension's detail page as `meta` tags

![meta tags](https://user-images.githubusercontent.com/33448286/65683001-da941500-e064-11e9-9990-1908b4e75c0c.png)

- the generated HTML is:
https://addons-stage-cdn.allizom.org/user-media/previews/full/160/160083.png?modified=1569494172
