### ISSUE TITLE
The recommended badge is displayed in autocomplete results on Android 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8067]
**STR**

1. Open AMO -dev on an Android device - https://addons-dev.allizom.org/en-US/android/
2. Enter a search term in the search field-  i.e _block_
3. Observe the results

**Actual result:**
Recommended add-ons are displaying a recommended badge

**Expected result:**
The recommended badge should be hidden everywhere on Android

**Notes:**
- there was a specific product requirement to not show the recommended badge on the [details page](https://github.com/mozilla/addons-frontend/issues/7794#issue-427045338) or in [search results](https://github.com/mozilla/addons-frontend/pull/7988#discussion_r287048318) on Android. Having it in the autocomplete results is inconsistent.
- reproduced on -dev with Fx67, Android 8.0

![image](https://user-images.githubusercontent.com/31961530/58328786-afda4b80-7e3b-11e9-8a10-c104926368b8.png)

**Comment by bobsilverberg** [comment]
Thanks for catching this @AlexandraMoga. This should definitely be fixed.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

![image](https://user-images.githubusercontent.com/31961530/58560156-3375ad00-822d-11e9-9916-914498786960.png)
