### ISSUE TITLE
Can't find Microsoft .Net Framework Assistant for Firefox

### ISSUE THREAD

**Issue by prathyushakochuru** [mozilla/addons-frontend#8070]
### Describe the problem and steps to reproduce it:
I couldn't find the .Net Framework Assistant for Firefox under extensions.

 I would like to run Microsoft XBAP applications on Firefox which need the MS add on for Firefox. I don't see this under extensions.
### What did you expect to happen?
MS browser apps works on Firefox.

**Comment by jvillalobos** [comment]
I'm pretty sure that extension has been discontinued for many years. However, you should contact Microsoft support if you need help finding a copy or a workaround.
