### ISSUE TITLE
The tooltip should be “Recommended extensions are safe, high-quality extensions” 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8077]
STR:
1. Load AMO dev and make a search after "Recommended add-ons only".
2. Hover over the badge and see the text displayed in the Tooltip. 

Expected result:
"Recommended extensions are safe, high-quality extensions" according to[ PRD](https://docs.google.com/document/d/1fRxLy7h02tn1HBIlsTU_6h9DHmN8c3N6bg4JoxHF7J8/edit#heading=h.v5wqiwp147r4) 

Actual result:
"Firefox only recommends extensions that meet our standards for security and performance"

Notes:
This is up to discussion, but I filed it since it's different from the PRD. @bobsilverberg @jvillalobos 
Reproducible on AMO dev with FF67(Win10). 

![Tooltip](https://user-images.githubusercontent.com/33448286/58420565-473adb00-8096-11e9-8d02-6eb9cbff2fba.png)

**Comment by bobsilverberg** [comment]
@ioanarusiczki Please see https://github.com/mozilla/addons-frontend/issues/7957#issuecomment-490584381 for an explanation of why the text reads "Firefox only recommends extensions that meet our standards for security and performance". I believe this can be closed.

**Comment by jvillalobos** [comment]
Yes, the comment takes precedence. I updated the PRD just now to avoid confusion.
