### ISSUE TITLE
Force recommended results to the top when sorting from a Category page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8084]
This is a spin-off from #8079.

When a user is on a Search Results page which includes `category` in the search criteria, if they change the sort criteria using the form, ensure that recommended add-ons remain at the top of the list by changing the sort criteria sent to the API to include `recommended` as the first criterion.

This is required because we are doing away with Category pages and they are being replaced with Search Results. See #8079 for more info.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- I verified this issue on FF67(Win10) with different categories for both extensions and static themes and I did not see problems meaning that the default sort is `sort=recommended%2Cusers` and the recommended addons are displayed on top of the page and non-recommended are following. 
The same for the rest of the sort types: `relevance`, `updated`, `rating`, `hotness` which combined with `recommended` will keep the recommended addons on top of the page and then the non-recommended will follow. 
- the Android platform does not show the recommended badge on the pages. (not in scope yet)

![recommended first](https://user-images.githubusercontent.com/33448286/58890129-b6e24300-86f2-11e9-9abd-e588c85c2a13.gif)
