### ISSUE TITLE
Include only recommended add-ons on the Extensions landing page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8085]
This is a spin-off from #8050 which captures the decisions made and described at https://github.com/mozilla/addons-frontend/issues/8050#issuecomment-495327551 and https://github.com/mozilla/addons-frontend/issues/8050#issuecomment-495412959.

The logic for retrieving add-ons for the Extensions landing page should be updated to only retrieve recommended add-ons.

**Comment by ioanarusiczki** [comment]
@bobsilverberg
- the extension landing page displays only recommended add-ons.
- refreshing the page several times I've noticed that the same extension can appear on 2 shelves such as

![same addon](https://user-images.githubusercontent.com/33448286/58714422-5dfe6c00-83cd-11e9-87a7-3b9b26a9d818.png)

 We currently have 31 recommended add-ons on AMO dev.

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
>     * the extension landing page displays only recommended add-ons.
> 
>     * refreshing the page several times I've noticed that the same extension can appear on 2 shelves such as
> 
> 
> ![same addon](https://user-images.githubusercontent.com/33448286/58714422-5dfe6c00-83cd-11e9-87a7-3b9b26a9d818.png)
> 

Yes, we anticipated that could happen and decided not to do anything to prevent it.

Can you confirm that this is okay, @jvillalobos?

**Comment by jvillalobos** [comment]
It's okay, yes.
