### ISSUE TITLE
Not able to found awetest recorder

### ISSUE THREAD

**Issue by warademilind** [mozilla/addons-frontend#8087]
### Describe the problem and steps to reproduce it:

Not able to found awetest recorder

### What happened?
When tried with
https://addons.mozilla.org/en-GB/firefox/addon/awetest-recorder/versions/
It shows "Oops! We can’t find that page"

### What did you expect to happen?
It shows "Oops! We can’t find that page"

### Anything else we should know?
Need to have this addon, please check revert back.

When tried with
https://addons.mozilla.org/en-GB/firefox/addon/awetest-recorder/versions/
It shows "Oops! We can’t find that page"

**Comment by jvillalobos** [comment]
This add-on is no longer available. For further help, please contact the developer.
