### ISSUE TITLE
Update the home page to work with recommended add-ons

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8089]
This is a spin-off from #8028.

This issue is about updating the home page to work with recommended add-ons and includes the following changes:

- Replace the "Featured Extensions" shelf with a "Recommended Extensions" shelf.
- Replace the "Featured Themes" shelf with a "Recommended Themes" shelf.
- Update the logic for the Popular Add-ons and Trending Extensions shelves (neither of which are currently included in the home page, but the logic for retrieving the data for them still exists in the app) to only retrieve recommended extensions.

Note that all of this is gated via the `enableFeatureRecommendedBadges` flag.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

> Note that all of this is gated via the enableFeatureRecommendedBadges flag.

I see the `api-recommendations-priority` switch as being active on AMO dev. When you said enableFeatureRecommendedBadges flag did you refer to this one ? 

- Recommended Extensions and Recommended Themes were already verified in https://github.com/mozilla/addons-frontend/issues/8028

-  Trending Extensions shelves logic is the same as for recommended extensions meaning they'll retrieve only recommended. That can be verified being available in the Extensions landing page together with the top rated extensions (already mentioned https://github.com/mozilla/addons-frontend/issues/8028)
Popular Add-ons are currently not available on AMO dev. 

- As I already mentioned https://github.com/mozilla/addons-frontend/issues/8028 for static themes the Top Rated or Trending themes (available on Themes landing page) don't have the `recommended=true` yet.

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> > Note that all of this is gated via the enableFeatureRecommendedBadges flag.
> 
> I see the `api-recommendations-priority` switch as being active on AMO dev. When you said enableFeatureRecommendedBadges flag did you refer to this one ?
> 

No, this is a flag on the front-end which "turns on" the recommended badges feature. It is currently turned on in dev but not in stage or prod.

>     * Recommended Extensions and Recommended Themes were already verified in #8028
> 
>     * Trending Extensions shelves logic is the same as for recommended extensions meaning they'll retrieve only recommended. That can be verified being available in the Extensions landing page together with the top rated extensions (already mentioned #8028)
>       Popular Add-ons are currently not available on AMO dev.
> 
>     * As I already mentioned #8028 for static themes the Top Rated or Trending themes (available on Themes landing page) don't have the `recommended=true` yet.

I think that all of the above observations are related to the *landing* pages, but this issue is specifically and only about changes to the *home* page.

**Comment by ioanarusiczki** [comment]
@bobsilverberg
As per discussion I'm marking this verified on AMO dev - FF67(Win10).
