### ISSUE TITLE
Remove code for Category pages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8090]
~~Depends on #8079~~
Depends on #8092 

After we change the code that directs to Category pages to instead direct to the Search Results page, we can remove the code for Category pages. This should be done at this point, because it contains a lot of code referencing `featured`, which we are changing to `recommended` in #8028, and it will be a waste of time to update the code for Category pages if they are just waiting to be removed.

I didn't include this in #8079 in order to keep the patch small, but it should be done soon after #8079 lands, in order to reduce the impact on #8028.

**Comment by kumar303** [comment]
This may be obvious but as part of removing these pages, they will need to redirect to the new URLs (defined in https://github.com/mozilla/addons-frontend/issues/8079)

**Comment by bobsilverberg** [comment]
> This may be obvious but as part of removing these pages, they will need to redirect to the new URLs (defined in #8079)

I'm going to make this depend on #8092, which includes redirecting the category pages, so that should deal with this, but I'll make sure that any routes affected are redirected appropriately.

**Comment by bobsilverberg** [comment]
@jvillalobos We currently support the following URLs:

- https://addons.mozilla.org/en-US/firefox/themes/categories/
- https://addons.mozilla.org/en-US/firefox/extensions/categories/

I'm not sure what the purpose of these are, and they are not linked to anywhere in AMO. I am proposing that we delete the code that supports these URLs and not bother redirecting them to anywhere. Is that okay? What is the use case for these pages?

**Comment by jvillalobos** [comment]
I suppose they were kept around for legacy reasons. They still get regular (low) traffic, so I would prefer that they redirect to their parent. So `/themes/categories/` -> `/themes/`, etc.

**Comment by bobsilverberg** [comment]
> I suppose they were kept around for legacy reasons. They still get regular (low) traffic, so I would prefer that they redirect to their parent. So `/themes/categories/` -> `/themes/`, etc.

Thanks @jvillalobos. I opened #8104 for this.

**Comment by willdurand** [comment]
> @jvillalobos We currently support the following URLs:
> 
>     * [addons.mozilla.org/en-US/firefox/themes/categories](https://addons.mozilla.org/en-US/firefox/themes/categories/)
> 
>     * [addons.mozilla.org/en-US/firefox/extensions/categories](https://addons.mozilla.org/en-US/firefox/extensions/categories/)
> 
> 
> I'm not sure what the purpose of these are, and they are not linked to anywhere in AMO. I am proposing that we delete the code that supports these URLs and not bother redirecting them to anywhere. Is that okay? What is the use case for these pages?

Isn't it available when browsing from a mobile phone?

**Comment by bobsilverberg** [comment]
> > @jvillalobos We currently support the following URLs:
> > ```
> > * [addons.mozilla.org/en-US/firefox/themes/categories](https://addons.mozilla.org/en-US/firefox/themes/categories/)
> > 
> > * [addons.mozilla.org/en-US/firefox/extensions/categories](https://addons.mozilla.org/en-US/firefox/extensions/categories/)
> > ```
> > 
> > 
> > I'm not sure what the purpose of these are, and they are not linked to anywhere in AMO. I am proposing that we delete the code that supports these URLs and not bother redirecting them to anywhere. Is that okay? What is the use case for these pages?
> 
> Isn't it available when browsing from a mobile phone?

Yes, but you're late to the game @willdurand 😉 I've already closed #8104

**Comment by willdurand** [comment]
ah, sorry 😞

**Comment by bobsilverberg** [comment]
> ah, sorry 😞

No need to be sorry! It's valuable information. It's just that someone else beat you to it!

**Comment by ioanarusiczki** [comment]
@bobsilverberg Would testing for the other issues from this patch cover for this issue too ?  Such as https://github.com/mozilla/addons-frontend/issues/8092 https://github.com/mozilla/addons-frontend/issues/8094 and https://github.com/mozilla/addons-frontend/issues/8028

**Comment by bobsilverberg** [comment]
@ioanarusiczki Yes, there's nothing specific to test for this as all of the code has been removed. I wouldn't expect any regressions as a result, but the other testing you did for those other issues is a good sanity check.

**Comment by ioanarusiczki** [comment]
@bobsilverberg The one regression found was https://github.com/mozilla/addons-frontend/issues/8131 
and fixed. 
I'm marking this verified on AMO dev - FF67(Win10 &Android 8.0).
