### ISSUE TITLE
Redirect the links from the theme category shelf on the home page to Search Results

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8092]
This is a follow-up to #8079, and (potentially) encompasses two changes:

1. The links from the shelf in question (see screenshot below) should no longer point to a Category page, but rather should point to a Search Results page, in a similar manner to how the category links on the Extensions and Themes pages are being changed to point to a Search Results page.

~~2. The URLs that previously existed for theme categories (e.g., https://addons.mozilla.org/en-US/firefox/themes/abstract/) should continue to work, but should also redirect to the appropriate Search Results page. Whether we can do this via nginx rules or whether we need something in the front end to do this is being discussed.~~ - This has been moved to #8094.

**Comment by bobsilverberg** [comment]
A hint from @kumar303 in IRC: 

> we only need to care about server side redirects so I suggest following this example https://github.com/mozilla/addons-frontend/blob/master/src/core/server/base.js#L246

**Comment by willdurand** [comment]
See also: https://github.com/mozilla/addons-frontend/issues/8094#issuecomment-496832082

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67, WIn10x64 and Android 8.0

- the links from the theme category shelf on the homepage are now opening a search results page with results from the selected category. The results are sorted by `recommended,users` by default.

![2019-05-31_13-39-49](https://user-images.githubusercontent.com/31961530/58700779-b754a400-83a9-11e9-8d73-1e9d23429c17.gif)
