### ISSUE TITLE
Lookup users

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons-frontend#810]
Sometimes we need to find a user's account. We should have an easy way of looking up a user and getting some info and links to current tools just like add-ons. Likely just exact matches here, so we'll need to know the user's email, username or FxA ID.

We'll need the API from https://github.com/mozilla/addons-server/issues/3138 to complete this.

Request outlined in https://github.com/mozilla/addons-server/issues/979.

**Comment by eviljeff** [comment]
afaik there is no plan to resurrect the front-end admin tool anytime soon.
