### ISSUE TITLE
ICU issue on Travis-CI (and locally too)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8100]
Travis CI builds are failing because of an issue with ICU. I tried to clear the Travis cache, which fixed a bunch of things but there is still an issue with 3 test cases, due to ICU I think, but I don't know how it is related.

The expected non-breaking space char code is `160` but it seems to be `8239` now:

```
$ node -e "console.log([...new Intl.NumberFormat('fr').format(12345)].map(f => f.charCodeAt(0)))"
[ 49, 50, 8239, 51, 52, 53 ]
```

**Comment by ioanarusiczki** [comment]
@willdurand Is qa needed ? If yes could you add some STR? 
Thanks!

**Comment by willdurand** [comment]
> @willdurand Is qa needed ? If yes could you add some STR?

no need for QA, sorry, thanks!
