### ISSUE TITLE
The Recommended badge from search results should link to the mozilla support page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8102]
**STR**

1. Open AMO -dev
2. Search for a term that will also bring recommended extensions, i.e. _block_
3. Hover over the Recommended badge in search results

**Actual result:**
The badge contains a hyperlink that should open a mozilla support page. However, when you click on it, the add-on details page is opened instead

**Expected result:**
When clicking on the recommended badge in search results you should land on the mozilla support page

Notes:
- reproduced on -dev with Fx67, Win10x64

![image](https://user-images.githubusercontent.com/31961530/58564640-feba2380-8235-11e9-9187-8ecdb62ae85b.png)

![2019-05-29_17-19-49](https://user-images.githubusercontent.com/31961530/58564653-04176e00-8236-11e9-8650-0f845122dae2.gif)

**Comment by bobsilverberg** [comment]
It seems that it's illegal to nest `<a>` tags, but that's what our code ends up doing in this situation. We need to change our code so we're no longer nesting `<a>` tags in this context, which might be a bit challenging.

Perhaps a better approach would be to use an `onClick` event on a non-anchor element for the RecommendedBadge to create the link rather than an `a` tag.

@willdurand | @kumar303 what do you think?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Probably should be the same for `Recommended` badges that show in the `More extensions by " section from the add-on detail page.  - FF67(Win10)

![recommended](https://user-images.githubusercontent.com/33448286/59186303-30f34b80-8b7b-11e9-9880-f1d664c352a1.png)

**Comment by bobsilverberg** [comment]
> @bobsilverberg Probably should be the same for `Recommended` badges that show in the `More extensions by " section from the add-on detail page. - FF67(Win10)
> 

@ioanarusiczki Could you file a separate bug for that. I see that my changes have fixed this for some screen sizes, but there seems to be a styling issue causing it not to work with others. For example, this screen size works fine:

![Screenshot 2019-06-11 08 08 14](https://user-images.githubusercontent.com/142755/59270675-1626e280-8c20-11e9-9637-50a0ba72579d.png)

But this one looks off and doesn't work properly:

![Screenshot 2019-06-11 08 09 01](https://user-images.githubusercontent.com/142755/59270711-3191ed80-8c20-11e9-98b0-aa29f2b6892e.png)

**Comment by kumar303** [comment]
@bobsilverberg is there a bug on file yet for the styling issues? Feel free to assign it to me.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx67 Win10x64

The recommended badge shown in search results is now redirecting to the SUMO article.
 *Note - also verified for More addons by developer card and the Extension and Themes cards from a user profile page

![2019-06-12_08-56-03](https://user-images.githubusercontent.com/31961530/59329481-a6842680-8cf7-11e9-815d-e007a398c766.gif)

**Comment by ioanarusiczki** [comment]
@kumar303 @bobsilverberg I opened a new issue for the styling issue here https://github.com/mozilla/addons-frontend/issues/8161
