### ISSUE TITLE
Redirect categories URLs to their respective pages

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8104]
We currently support the following URLs:

- https://addons.mozilla.org/en-US/firefox/themes/categories/
- https://addons.mozilla.org/en-US/firefox/extensions/categories/

The CategoriesPage that these point to serves little purpose and are not linked to from anywhere in AMO. 

@jvillalobos [has requested](https://github.com/mozilla/addons-frontend/issues/8090#issuecomment-496694039) that they redirect to their parent. So `/themes/categories/` -> `/themes/`, etc.

Because this is a static redirect, I suggest we just do this via nginx. @kumar303 what do you think?

**Comment by kumar303** [comment]
If it's a permanent redirect, it should live in `addons-frontend` so that we don't accidentally break it as a feature. Nginx is better for temporary things like when we needed to serve `addons-frontend` alongside the old site as certain URLs weren't ready yet.

**Comment by AlexandraMoga** [comment]
> We currently support the following URLs:
> 
> * https://addons.mozilla.org/en-US/firefox/themes/categories/
> * https://addons.mozilla.org/en-US/firefox/extensions/categories/
> 
> The CategoriesPage that these point to serves little purpose and are not linked to from anywhere in AMO.

@bobsilverberg actually, we do link to `/themes/categories/` and `/extensions/categories/` on Android. For example, when you open the Extensions landing page, there is a button `Explore all extensions` that further opens `/android/extensions/categories/`. Currently, this is the only means of accessing categories on Android, so if we plan to redirect `/extensions/categories/` to  `/extensions/` we are going to break category access. 

![2019-05-31_11-45-37](https://user-images.githubusercontent.com/31961530/58693641-e531ec80-8399-11e9-9fba-3d787f45c03d.gif)

**Comment by bobsilverberg** [comment]
> @bobsilverberg actually, we do link to `/themes/categories/` and `/extensions/categories/` on Android. For example, when you open the Extensions landing page, there is a button `Explore all extensions` that further opens `/android/extensions/categories/`. Currently, this is the only means of accessing categories on Android, so if we plan to redirect `/extensions/categories/` to `/extensions/` we are going to break category access.
> 

Thanks @AlexandraMoga. I guess we should just keep the Categories pages then. Do you agree @jvillalobos?

**Comment by jvillalobos** [comment]
Yes. Good catch!

**Comment by bobsilverberg** [comment]
Ok, let's close this.
