### ISSUE TITLE
Footer items appearing in the midst of the page as well as at the foot

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#8108]
https://addons.mozilla.org/en-GB/firefox/addon/cookie-autodelete/versions/ in Waterfox 56.2.10 in safe mode on FreeBSD-CURRENT: 

![image](https://user-images.githubusercontent.com/192271/58653023-bb7eb400-830c-11e9-8b68-09c1b2050201.png)

Firefox, safe mode: 

![image](https://user-images.githubusercontent.com/192271/58653121-f385f700-830c-11e9-83d0-4e8c80dfdaf8.png)

**Comment by willdurand** [comment]
I think this is similar to https://github.com/mozilla/addons-frontend/issues/7653. @muffinresearch could you maybe update the content of this add-on (as described [here](https://github.com/mozilla/addons-frontend/issues/7653#issuecomment-468769285))?

**Comment by muffinresearch** [comment]
@willdurand yep this is fixed now. The first release note was missing an opening and closing `ul` around a set of `li`s
