### ISSUE TITLE
`src=featured` should be replaced with `src=recommended` in add-on details URLs opened from search results filtered by recommended 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8118]
**STR**

1. Open AMO -dev
2. Perform a blank search and filter the results to show only recommended examples
3. Select one of the returned add-ons to view its details page - https://addons-dev.allizom.org/en-US/firefox/addon/anonymox/?src=featured
4. Observe the parameters sent in the URL

**Actual result:**
The access source is `src=featured`

**Expected result:**
The source should be changed to `src=recommended`

**Notes:**
- reproduced on -dev with Fx67, Win10x64

**Comment by bobsilverberg** [comment]
This was discussed with @jvillalobos and he indicated that, because of existing analytics, we should keep the `src` as `featured`, even after replacing Featured shelves with Recommended shelves.

@jvillalobos can you please confirm or deny?

**Comment by jvillalobos** [comment]
That's correct. `src=featured` has a special meaning in the developer stats dashboards, so let's keep it for now.
