### ISSUE TITLE
Redirect category URLs to the Search Results page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8123]
To support legacy URLs (see https://github.com/mozilla/addons-frontend/issues/8090#issuecomment-496694039) after [removing category pages](https://github.com/mozilla/addons-frontend/issues/8090), we need to add some redirects.

It was decided we should do this via nginx, so this is a request to add a rule to redirect all traffic to category URLs to the Search Results page.

The current URLs look like:
`/:lang/:application/:visibleAddonType(extensions|themes)/:slug/`

And these should be redirected to URLs like:
`/${lang}/${application}/search/?category=${slug}&sort=recommended%2Cusers&type=${convertedAddonType}`

Where `convertedAddonType` is `extension` when `visibleAddonType` is "extensions" and `convertedAddonType` is `statictheme` when `visibleAddonType` is "themes".

@bqbn @autrilla Can one of you please take care of this for us?

For QA:
Please verify these redirects on dev when you can. They should be verified on stage after the tag lands on stage on Tuesday, and verified on prod after the push lands on Thursday.

**Comment by bobsilverberg** [comment]
Note that the code that we added to do the redirect in addons-frontend should be removed after this change lands. That code is at https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/core/server/base.js#L170-L187 and https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/core/server/base.js#L286-L299.

**Comment by bqbn** [comment]
> It was decided we should do this via nginx, 

Can we please get some background info what problems we're trying to solve, and why this is decided that we should do this via nginx? 

With all due respect, I think we should be engaged in the conversation at the beginning, instead of being notified with a decision afterwards.

**Comment by bobsilverberg** [comment]
Please accept my apologies @bqbn, I didn't know that you'd be interested in discussing it, and if I had I would have included you in the discussion. We can certainly do that now. It's after hours for me right now but tomorrow I'll try to summarize the discussions from the other issue and I will look forward to hearing your input.

**Comment by kumar303** [comment]
> It was decided we should do this via nginx...

We are requesting redirect logic to map legacy URLs to current URLs. Because of this, we don't consider it application logic. It's historic logic that needs to be mapped to new logic. This made nginx seem like a good place for it. However, we can still put it in the frontend application if that's helpful.

**Comment by bobsilverberg** [comment]
Thanks for the explanation @kumar303.

@bqbn Does that suffice? Would you like to discuss it further?

**Comment by bqbn** [comment]
Yes, that makes sense. Thanks!

The redirection rules are deployed to -dev now.

**Comment by bobsilverberg** [comment]
> Yes, that makes sense. Thanks!
> 
> The redirection rules are deployed to -dev now.

Thanks @bqbn. These rules can also be deployed to stage and prod whenever you are ready to do so. There's no rush, but it's also not blocked on anything.

**Comment by bqbn** [comment]
Do we need QA to verify things work as expected before pushing it to -prod?

(The redirection rules are deployed to -stage as well, btw)

**Comment by bobsilverberg** [comment]
> Do we need QA to verify things work as expected before pushing it to -prod?
> 
> (The redirection rules are deployed to -stage as well, btw)

Yes, that would be a good idea. I just merged #8144 which removes the code from addons-frontend, so that can now be verified on dev. Once the tag is pushed tomorrow, the redirects can be verified on stage. I guess it would make sense to push the changes to prod as part of Thursday's push as well. I'll add a comment to the push doc. I guess we should close this issue to flag it for QA to verify in all 3 places.

**Comment by bobsilverberg** [comment]
@bqbn I added a note at https://github.com/mozilla/addons/blob/master/releases/2019/06/13.md#before-we-push as a reminder to push these rules to prod as part of Thursday's push.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I've been going through all [categories ](https://addons-server.readthedocs.io/en/latest/topics/api/categories.html#id1) on AMO dev and AMO stage for
`/en-US/firefox/extensions/:categoryslug/`
`/en-US/firefox/themes/:categoryslug/`
`/en-US/android/extensions/:categoryslug/`
`/en-US/android/themes/:categoryslug/`
They redirect correctly to the new search pages.

**Comment by willdurand** [comment]
We do have an issue with the nginx rules, see: https://github.com/mozilla/addons-frontend/issues/8163.

There should be no redirect when `:categoryslug` is `categories`, so we should not rewrite `/(\w{2,3}(?:-\w{2,6})?/(?:firefox|android))/extensions/categories/$` and `/(\w{2,3}(?:-\w{2,6})?/(?:firefox|android))/themes/categories/$`.

**Comment by willdurand** [comment]
@bqbn ^ do you think it would be doable in nginx?

**Comment by kumar303** [comment]
@bqbn to put it another way, the nginx rule redirects `/extensions/$name/` to `/search/?category=$name` so we just need to exclude the URL `/extensions/categories/` because that one should not redirect.

**Comment by bobsilverberg** [comment]
It sounds like maybe we should re-open this issue and make it a P1 as it needs to be addressed before we push these new rules to prod.

**Comment by bobsilverberg** [comment]
I'm going to close this again and just use #8163 to track this fix.

**Comment by bqbn** [comment]
Heh, this should be doable, although, it's like pushing the use of Nginx configs to its limit. After all, Nginx config language is not a high level programming language, it's not good at handling complex control logic. :)

**Comment by ioanarusiczki** [comment]
Verified on AMO prod - FF67 -Win10
