### ISSUE TITLE
Redirect is missing for a link from Guides pages

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#8131]
Steps to reproduce:
1.Go to AMO Stage and open https://addons.allizom.org/en-US/firefox/guides/enhance-your-media-experience/
2. Go to "Bring media right into the browser" section and press the "photo, music & video extensions" link

Expected results:
The link should open https://addons.allizom.org/en-US/firefox/search/?category=photos-music-videos&sort=recommended%2Cusers&type=extension

Actual results:
"Oops! We can’t find that page" is returned

NOTES:
Probably a regression from https://github.com/mozilla/addons-frontend/issues/8094

Please see video for this bug : 
![oopsguides](https://user-images.githubusercontent.com/1583842/58954306-77befb00-87a1-11e9-97d8-36bcc6aeb78a.gif)

**Comment by bobsilverberg** [comment]
Because the redirect we added for the Category page is server-side only, this link isn't being redirected. The fix for this is to change this link to point at the Search results page just as we did with other existing category page links.

**Comment by bobsilverberg** [comment]
This fix is on dev and I also just cherry-picked it and pushed a new tag so it should be on stage soon as well.

**Comment by vcarciu** [comment]
Verified as fixed on Stage : the link is correctly redirecting to https://addons.allizom.org/en-US/firefox/search/?category=photos-music-videos&sort=recommended%2Cusers&type=extension
