### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by chaitannah** [mozilla/addons-frontend#8133]
Broken Link on MozillaWiki IRC page 
(https://wiki.mozilla.org/IRC)

Under the Pick an IRC client section, the link to Chatzilla on the extension market is broken.
https://wiki.mozilla.org/IRC#Pick_an_IRC_client

Would require an edit on the MozillaWiki html

**Comment by caitmuenster** [comment]
Thanks! I just removed it from the wiki.
