### ISSUE TITLE
Remove the code of redirection of urls

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-frontend#8143]
As redirection of the urls will be done at nginx level its best to delete the redirection's code at

 https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/core/server/base.js#L170-L187

and 

https://github.com/mozilla/addons-frontend/blob/6dcf336e0834d98499a7ce837b37d4d3373211d7/src/core/server/base.js#L286-L299

cc @bobsilverberg

**Comment by thisbutterfly** [comment]
I would like to work on this one. @championshuttler

**Comment by bobsilverberg** [comment]
Thanks for your interest @thisbutterfly, but this has already been completed.

**Comment by thisbutterfly** [comment]
It's alright @bobsilverberg  :)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I filed https://github.com/mozilla/addons-frontend/issues/8163 but that's not a regression from this week - it's reproducible on prod too. 

Would testing for https://github.com/mozilla/addons-frontend/issues/8123 cover for this ? 

I tested the redirect for a couple of categories in other locales too - no problems there either.

**Comment by bobsilverberg** [comment]
@ioanarusiczki yes, testing for #8123 should cover this. I'm a bit confused about your comment that #8163 is reproducible on prod. I don't see why that would be the case.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Click on https://addons.mozilla.org/en-US/firefox/extensions/categories or 
 https://addons.mozilla.org/en-US/android/extensions/categories
It will redirect to search results.

**Comment by bobsilverberg** [comment]
> @bobsilverberg Click on [addons.mozilla.org/en-US/firefox/extensions/categories](https://addons.mozilla.org/en-US/firefox/extensions/categories) or
> [addons.mozilla.org/en-US/android/extensions/categories](https://addons.mozilla.org/en-US/android/extensions/categories)
> It will redirect to search results.

Ah, I see. This is actually a bug from #8105 that was never caught. This should be fixed on prod when the new nginx rules are pushed.
