### ISSUE TITLE
Firefox extension for Kindle. Link broken.

### ISSUE THREAD

**Issue by kevitivity** [mozilla/addons-frontend#8149]
### Describe the problem and steps to reproduce it:
Download link for Firefox kindle extension is nroken.
URL: https://www.amazon.com/gp/sendtokindle/firefox

### What happened?
Page not found :oops"
### What did you expect to happen?
download start.
### Anything else we should know?

https://www.amazon.com/gp/sendtokindle/firefox

**Comment by jvillalobos** [comment]
Closing as a duplicate of https://github.com/mozilla/addons-frontend/issues/7282
