### ISSUE TITLE
I'm not sure if there's much we can do about broken HTML (we should probably warn about it, though).

### ISSUE THREAD

**Issue by 100004584750028** [mozilla/addons-frontend#8160]
I'm not sure if there's much we can do about broken HTML (we should probably warn about it, though). 

Can you try it again with valid HTML? Like this:

```
<ol>
<li>test1</li>
<li>test1</li>
<li>test1</li>
<li>test1</li>
</ol>

<ul>
<li>test1</li>
<li>test1</li>
<li>test1</li>
<li>test1</li>
</ul>
```

_Originally posted by @kumar303 in https://github.com/mozilla/addons-frontend/issues/7998#issuecomment-490995436_

**Comment by kumar303** [comment]
Hi. Thanks for helping out by filing a new issue but we already have this covered by https://github.com/mozilla/addons-frontend/issues/7998 and https://github.com/mozilla/addons-server/issues/10832 so we don't need a new issue.
