### ISSUE TITLE
AMO should use "Firefox Preview" in strings instead of "Fenix"

### ISSUE THREAD

**Issue by jonalmeida** [mozilla/addons-frontend#8179]
### Describe the problem and steps to reproduce it:

In the [AdddonCompatibilityError](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonCompatibilityError/index.js#L112), "Fenix" referred when it should be "Firefox Preview".

Fenix is the codename, Firefox Preview is the product name. (similar to fennec/Firefox for Android).

**Comment by jonalmeida** [comment]
cc: @willdurand

**Comment by championshuttler** [comment]
Can i take this up @willdurand

**Comment by willdurand** [comment]
@championshuttler yep, go for it!

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev - FF67, FF69
Useragent: `Mozilla/5.0 (Android 9; Mobile; rv:69.0) Gecko/69.0 Firefox/69.0`

![Preview](https://user-images.githubusercontent.com/33448286/59754297-7b1cb100-928e-11e9-88e0-c3c5890c6782.png)
