### ISSUE TITLE
Category buttons should use the Photon pallette

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8180]
The category pages shown in https://github.com/mozilla/addons-frontend/issues/3594 are using the wrong colors. They should follow the [Photon colors](https://design.firefox.com/photon/visuals/color.html). There isn't a mock-up that uses Photon colors but you could look at https://github.com/mozilla/addons-frontend/issues/3594 and try to come up with the correct mapping.

**Comment by M4trox** [comment]
Hello, I made a mock-up. It's the first time I have worked with Photon, so feedback is welcome.

![category-buttons-mock-up](https://user-images.githubusercontent.com/3310268/59790958-5f86ca00-92d1-11e9-9908-4373e2568d61.png)

Each category is represented by ["puffy" button](https://design.firefox.com/photon/components/buttons.html). In Figma, I cannot set inner horizontal margins for shapes, so keep that in mind that this mock-up is only to visualize things. I've used Photon color pallet and tried to match with current design.

**Comment by Shubhamchinda** [comment]
Hey @kumar303 , if you could help me out in this issue, I'd love to take this up.

**Comment by kumar303** [comment]
Hi @M4trox and @Shubhamchinda . Thanks for your time spent looking into this. We use the label [`contrib: good first bug`](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug) and [`contrib: welcome`](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) to indicate which issues are ready to be worked on. Patches for those issues will be easier for a team member to review. 

@M4trox I haven't compared the photon spec to your mock-up but if you'd like to create a pull request, I could take a closer look. There are some complications in how `addons-frontend` deals with theme category colors but that could be done separately from this issue.

Once again, thanks for your interest in the project!

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me on FF70(Win10). 

![colors1](https://user-images.githubusercontent.com/33448286/67566557-c5c4a300-f730-11e9-8b0e-eb83ae9310e3.png)

![themes colors](https://user-images.githubusercontent.com/33448286/67566580-d412bf00-f730-11e9-9223-d19774ea1f53.png)

The category pages do not display categories as before meaning on vertical alignment, one below the other, I don't know if on small devices is the expected result but to me it looks better as it is right now. 

![extensions categories](https://user-images.githubusercontent.com/33448286/67566644-0f14f280-f731-11e9-80a5-fb07e982cf05.png)

![Themes categories](https://user-images.githubusercontent.com/33448286/67566652-189e5a80-f731-11e9-9750-f03885efb55b.PNG)

**Comment by willdurand** [comment]
> The category pages do not display categories as before meaning on vertical alignment, one below the other, I don't know if on small devices is the expected result but to me it looks better as it is right now.

This is the expected result after #8824
