### ISSUE TITLE
The old RSS URL should be a 404

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8185]
### Describe the problem and steps to reproduce it:

Load an old RSS URL such as https://addons-dev.allizom.org/en-US/firefox/extensions/format:rss/?sort=featured

### What happened?

This redirects to https://addons-dev.allizom.org/en-US/firefox/search/?category=format:rss&sort=recommended%2Cusers&type=extension&sort=featured which triggers a 500 (https://github.com/mozilla/addons-frontend/issues/8177, https://github.com/mozilla/addons-frontend/issues/8181)

### What did you expect to happen?

The RSS URL should be a 404 like it was before adding the redirect. The patch in https://github.com/mozilla/addons-server/pull/11097/files#diff-51cb1918f67350b18c817fafabce2ac4L67 made it a 404.

### Anything else we should know?

The nginx redirect was added for https://github.com/mozilla/addons-frontend/issues/8123

We need to change the nginx redirect regex so that it doesn't redirect `/firefox/extensions/format:rss/` since that's not a valid category.

**Comment by kumar303** [comment]
> We need to change the nginx redirect regex so that it doesn't redirect `/firefox/extensions/format:xss/` since that's not a valid category.

@bqbn what do you think about adjusting the nginx rule for this?

**Comment by bobsilverberg** [comment]
@kumar303 I believe that every instance of `xss` in the description above should be changed to `rss`.

**Comment by bqbn** [comment]
> We need to change the nginx redirect regex so that it doesn't redirect `/firefox/extensions/format:xss/` since that's not a valid category.

@kumar303 we can add another nginx rule so it doesn't redirect for `/extensions/format:rss/`. One thing I wonder is how many of those special cases there are.

If there are too many, or if we plan to add more in the future, I wonder if we should let the application do the redirection, and let Nginx just cache the results. After all, Nginx is good at proxying and caching, and not so good at handling logic that seems to belong to the application. Less rules in the proxy layer means faster response time too. (for example, the proxy can hit the app once, and cache the result, which is faster than scanning through all the rules).

However, if there are going to be just 2 or 3 of these special cases, I think it should be fine to do it at the proxy layer.

**Comment by kumar303** [comment]
> @kumar303 I believe that every instance of `xss` in the description above should be changed to `rss`.

Whoops, thanks. I fixed everything.

**Comment by kumar303** [comment]
> @kumar303 we can add another nginx rule so it doesn't redirect for `/extensions/format:rss/`. One thing I wonder is how many of those special cases there are.

I looked at the legacy URLs and I don't see any other cases.

**Comment by bqbn** [comment]
We updated the Nginx rules in -dev and -stage environments such that `/<locale>/<app>/extensions/format:rss/` is no longer redirected to the search API, but forwarded to the frontend app.

Please test it. We can push the same change to -prod once verified.

**Comment by kumar303** [comment]
@bqbn thanks. I verified that this is fixed on dev and stage. I will close the issue so that QA can also check for any regressions.
