### ISSUE TITLE
broken link: from kb.mozillazine.org/Places.sqlite to addons.mozilla.org/en-US/firefox/addon/5817/

### ISSUE THREAD

**Issue by somestuff** [mozilla/addons-frontend#8195]
### Describe the problem and steps to reproduce it:

broken link from page http://kb.mozillazine.org/Places.sqlite to https://addons.mozilla.org/firefox/addon/5817 under anchor reads: "SQLite manager add-on"

Suggest all broken links be titled broken link with from to descriptor so that searching duplicates become much easier. Have to open issues with same name is a drag!

**Comment by wagnerand** [comment]
Please contact the mozillazine people about this.
