### ISSUE TITLE
Incompatibility error shown for opensearch add-ons (on the server)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8196]
### Describe the problem and steps to reproduce it:

1. Go to http://localhost:3000/en-US/firefox/addon/hellspy/?src=search
2. Refresh the page

### What happened?

A red banner is shown until the client side code removes it.

### What did you expect to happen?

No red banner stating that the add-on is not compatible.

### Anything else we should know?

This is due to the server side not being aware of the opensearch support (because this can only be detected on the client).

**Comment by ioanarusiczki** [comment]
@willdurand I could not reproduce it on -dev for 
https://addons-dev.allizom.org/en-US/firefox/addon/hellspy/?src=search or https://addons-dev.allizom.org/en-US/firefox/addon/hellspy/. 
I tested with a couple of other samples too on -dev and the red message which appears like a glitch and quickly disappears did not show up.

Unlike stage where I could reproduce it with 
https://addons.allizom.org/en-US/firefox/addon/enhanced-facebook/
https://addons.allizom.org/en-US/firefox/addon/enhanced-facebook/?src=search
Eventually I'll re-check it on stage too after this fix lands. 

on stage (now)
![red message stage without search](https://user-images.githubusercontent.com/33448286/60002960-610a1680-9672-11e9-9e81-6d63d627672e.gif)
