### ISSUE TITLE
Can Not Access My Collections

### ISSUE THREAD

**Issue by sammuelb** [mozilla/addons-frontend#8198]
### Describe the problem and steps to reproduce it:
I get a server error every time I try to access the "View My Collections" link

When on https://addons.mozilla.org/en-US/firefox/ clicking on my user name at the top, then clicking on "View My Collections", I am always greeted with a server error message.  I don't think I have ever been able to access my collections.

### What happened?
Server error when trying to access my collections

### What did you expect to happen?
To be brought to a page showing a list of my collections

### Anything else we should know?
When adding an add-on to a collection, I receive a confirmation message saying that the add-on was successfully added to the collection.

https://addons.mozilla.org/en-US/firefox/collections/
![ViewMyCollectionsLink](https://user-images.githubusercontent.com/10660288/59807304-36077780-92ac-11e9-9541-fb1eebe0c528.jpg)
![ServerError](https://user-images.githubusercontent.com/10660288/59807306-3869d180-92ac-11e9-9af5-26a7cca7e916.jpg)

**Comment by Shubhamchinda** [comment]
@sammuelb It's working fine for me.

**Comment by willdurand** [comment]
We have issues related to that but we can't figure out why it fails so far..
