### ISSUE TITLE
Spelling typo "publically"

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-frontend#8245]
### Describe the problem and steps to reproduce it:
In Pontoon: https://pontoon.mozilla.org/pa-IN/all-projects/all-resources/?status=missing&string=172546

#: src/amo/pages/StaticPages/About/index.js:71
Resource LC_MESSAGES/amo.po

The add-ons listed here are created by thousands of developers and theme designers from all over the world, ranging from individual hobbyists to large corporations. Some add-ons listed on AMO have been automatically published and may be subject to review by a team of editors once **publically** listed.

### What happened?
Spelling error `publically`

### What did you expect to happen?
Correct spelling  should be `publicly`

**Comment by Shubhamchinda** [comment]
@peiying2 Can i fix this?

**Comment by wagnerand** [comment]
@Shubhamchinda No need to ask for permission, please go ahead :)

**Comment by ioanarusiczki** [comment]
@willdurand 
How can qa help checking on this ? Can I access through AMO -dev a link to see this typo as being fixed somewhere?

**Comment by willdurand** [comment]
@ioanarusiczki yep, you can go to the "about" page (locale = en-US) and see that it's written "publicly" now.

**Comment by ioanarusiczki** [comment]
@willdurand Thanks! Ok, that is `publicly` on AMO dev - About page https://addons-dev.allizom.org/en-US/about - FF67(Win10) 

![Publicly](https://user-images.githubusercontent.com/33448286/60899339-fca2a600-a272-11e9-93be-18c92cd3a70e.png)
