### ISSUE TITLE
Add dynamic Secondary Hero Shelf to desktop homepage

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8249]
Part of [this PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit#). Depends on https://github.com/mozilla/addons-server/issues/11779 and https://github.com/mozilla/addons-server/issues/11780.

This shelf will appear below the Primary Hero Shelf and will replace the header and guide modules in the current homepage:

<img width="1291" alt="Screen Shot 2019-07-03 at 4 50 11 PM" src="https://user-images.githubusercontent.com/62568/60629360-a933e200-9db2-11e9-8402-2f9cee3a38cf.png">

Once the admin for this shelf is done (https://github.com/mozilla/addons-server/issues/11779, https://github.com/mozilla/addons-server/issues/11780), we should show it on the homepage.

All internal URLs in this module should have these params appended: `src=homepage-secondary-hero`. External URLs should have these: `utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-secondary-hero`. An event should be logged on GA when the CTA is clicked, recording a click on the shelf and the destination.

For QA:

Note that the requirements to append URL params to the links, as well as to send a GA event when a link is clicked, have been moved into follow-up issues (#8558 and #8559).

**Comment by AlexandraMoga** [comment]
On a first look, the Secondary hero module looks good. I've crossed checked it with the proposed  mock-up, and the only difference I've spotted is with the module headline not being bold (also discussed in the pull request).

![image](https://user-images.githubusercontent.com/31961530/65521444-e9a68600-def1-11e9-90e9-b7802833d483.png)
