### ISSUE TITLE
Layout issues caused by add-ons named with longer unbroken strings 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8254]
STR:
1. Load the detail page for https://addons-dev.allizom.org/en-US/firefox/addon/koutter2359/
2. Check the More extensions section (reload it in case the two add-ons with longer names are not available on the right)
3. Observe `WWWWWWWWWWWWWWWWW45678`

Expected result:
Name fits in the section.

Actual result:
Name of the add-on looks cut.

Notes:
Reproducible on AMO dev with FF67(Win10). 

![truncated](https://user-images.githubusercontent.com/33448286/60675123-50cd1500-9e84-11e9-855f-38fff9bff45d.png)

**Comment by willdurand** [comment]
I noticed this yesterday in https://github.com/mozilla/addons-frontend/issues/8161#issuecomment-508096198 and planned to file an issue. Thanks for opening it!

I believe this is a regression because I am pretty sure we handled this case in the past.

**Comment by vcarciu** [comment]
Reproducible also in homepage : 
![long](https://user-images.githubusercontent.com/1583842/60676037-84a93a00-9e86-11e9-8b26-3c41ba984565.png)

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on -dev with FF67(Win10)

![More extensions](https://user-images.githubusercontent.com/33448286/60815435-50908a80-a1a0-11e9-861e-9b06677987ef.png)

![homepage](https://user-images.githubusercontent.com/33448286/60815448-5a19f280-a1a0-11e9-967a-aefa48cf6c94.png)
