### ISSUE TITLE
Remove `getAddonTypeFilter()`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8256]
We can remove the `getAddonTypeFilter()` function now that we do not have to support lightweight themes. We only have static themes:

- All calls to `getAddonTypeFilter()` should be changed to `ADDON_TYPE_STATIC_THEME`
- The `config` is often given to this function. In the caller, if we only use the config to call `getAddonTypeFilter`, then we should also remove the config code since that won't be used elsewhere anymore

**For QA:** there should be no obvious regression. We changed code related to the "landing pages" (`/extensions/` and `/themes/` for both Android and FF Desktop). We also touched code related to the "other add-ons by authors".

**Comment by Shubhamchinda** [comment]
Hey @willdurand should I take it?

**Comment by willdurand** [comment]
@Shubhamchinda sure :)

**Comment by ruchikabgosain** [comment]
hey @Shubhamchinda are you still working on this?

**Comment by Shubhamchinda** [comment]
Yeah @ruchikabgosian .

**Comment by ruchikabgosain** [comment]
Hello, is this done? Or still available, let me know :)

**Comment by ioanarusiczki** [comment]
@willdurand I've noticed that the colors on the homepage in the Change the way Firefox looks with themes. section are different. 

![themes](https://user-images.githubusercontent.com/33448286/67567908-821f6880-f733-11e9-83c6-37b928565cff.png)

Categories pages - The categories are not aligned vertically 
https://addons-dev.allizom.org/en-US/firefox/extensions/categories/
https://addons-dev.allizom.org/en-US/firefox/themes/categories/

**Comment by willdurand** [comment]
> 've noticed that the colors on the homepage in the Change the way Firefox looks with themes. section are different.

Ah, interesting. Can you file an issue for that? It does not really matter to have the same colors for the same themes, but it'd be nice to have different colors in this shelf.

**Comment by ioanarusiczki** [comment]
@willdurand Done.
https://github.com/mozilla/addons-frontend/issues/8835

**Comment by ioanarusiczki** [comment]
@willdurand No issues found. Verified on AMO stage with FF70(Win10). 

Here are the [Release testing results](https://testrail.stage.mozaws.net/index.php?/plans/view/21991)
