### ISSUE TITLE
Add tag in Sentry

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8270]
I'd like to use the [Sentry "release" feature](https://docs.sentry.io/workflow/releases/?platform=javascript) so that events are bound to a tag (or commit id, maybe).

That would be useful to determine which tag has likely introduced a bug and to see if a hotfix/new tag has fixed it.

**Comment by EnTeQuAk** [comment]
That has been very helpful on addons-server, we are also using it there.

https://github.com/mozilla/addons-server/blob/7a40efb0cc3efd7b1e3a32082a9b8aa22846fbe2/src/olympia/lib/settings_base.py#L1769-L1776 and https://github.com/mozilla/addons-server/blob/7a40efb0cc3efd7b1e3a32082a9b8aa22846fbe2/src/olympia/lib/settings_base.py#L1748-L1766 for reference

**Comment by willdurand** [comment]
We'll need a way to read the `version.json` file and probably expose a constant at build time _via_ https://webpack.js.org/plugins/define-plugin/.
