### ISSUE TITLE
A recommended version will no longer display the corresponding badge if the add-on is marked as not recommended in Discovery admin

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8271]
Prerequisites: you will need an admin account in order to access https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/

**STR:**
1. Open the details page for an add-on with a Recommended status - see https://addons-dev.allizom.org/en-US/firefox/addon/axe-2/?src=search
  *Note: make sure that the version package contains the `mozilla-recommendation.json` file
2. Go to Admin [Discovery items](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/discoveryitem/) and remove the add-on from the recommendations list
3. Go back to the add-on details page and refresh the page

**Actual result:**
The add-on is no longer displaying a Recommended badge, although, according to its signature, the version was approved and signed as recommended. Furthermore, if you install the add-on in a FX version that supports recommendations in about add-ons (latest Nightly) , the add-on will expose the Recommended badge. 

**Expected result:**
(?)The recommended badge should not be removed from the version that was already approved as recommended. Only its next listed version should be impacted by the modifications made in Discovery admin.

**Notes:**
- this happens because the frontend reads the `is_recommended` status from https://addons-dev.allizom.org/api/v4/addons/addon/axe-2/, which becomes `false` when the add-on is marked as non-recommended in Discovery items (maybe an API change is needed as well)
- by contrast, addons manager relies on the add-on signature to render the corresponding badge

![2019-07-08_17-29-50](https://user-images.githubusercontent.com/31961530/60818582-9a7c6f00-a1a6-11e9-92c5-e12278d680f5.gif)

**Comment by bobsilverberg** [comment]
Thanks for filing this @AlexandraMoga. This is actually how I would expect it to behave, for exactly the reason you state (we're using `is_recommended` from the API). I suspect that maybe the Firefox behaviour is incorrect, but I could be wrong about that.

@jvillalobos What do you think? Should a version of an add-on that was recommended remain recommended when the status of the add-on is changed to "not recommendable", or should the version also be changed to not recommended? It seems that AMO enforces the latter, but Firefox does not.

**Comment by jvillalobos** [comment]
That's the expected behavior, yes. It's a bit inconsistent between Firefox and AMO, but it's not a use case we expect to come up often. We might require developers to upload a new version when this happens, in order to mitigate this.
