### ISSUE TITLE
Difficulty in finding a copper extension for firefox

### ISSUE THREAD

**Issue by pniharika123** [mozilla/addons-frontend#8276]
Hi
I am a research scholar working on contiki os cooja simulator for Internet of Things. For a protocol named CoAP i should have copper(cu) extension/pulg-in in mozilla firefox. The same extension was supported by mozila version upto 55 eariler. In current day it is been removed for some reason from firefox. I tried searching alternate method and installing it but it did not happen. Please help me out to find the copper extension to start working with my reaserch .
http://addons.mozilla.org/en-US/firefox/addon/copper-270430/ This was supposed to be the link to find the coppen extension. 

Thank you

**Comment by willdurand** [comment]
Hi! Yeah, I also wanted to find this extension but it has not been ported to the new "webextension" API so that's why the extension cannot be found on AMO anymore... There is nothing we can do, though.

You could maybe ask the developer to update the extension.
