### ISSUE TITLE
Enable Recommended Badges on stage and prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8277]
We plan on enabling recommended badges with this week's push, on July 11th. This issue is about flipping the config switch for stage and prod so the tag and the push will enable recommended badges.

@jvillalobos and @devaneymoz are we still on track to enable these on July 11th?

**Comment by jvillalobos** [comment]
We're on track for Thursday, yes.

**Comment by AlexandraMoga** [comment]
The Recommended badges have been verified on stage and they have been working as expected.
This issue will be marked as verified once we check prod as well.
