### ISSUE TITLE
The Recommended badge is not placed next to the add-on name in the guides pages for shorter names 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8284]
**STR**

1. Go to AMO stage homepage
2. Open the Stay safe online guide - https://addons.allizom.org/en-US/firefox/guides/stay-safe-online/
3. Examine the uBlock Origin card

**Actual result:**
The Recommended badge and the add-on name are too far apart

**Expected result:**
The Recommended badge is displayed next to the add-on name

**Notes:**
- another example is Tabliss in the https://addons.allizom.org/en-US/firefox/guides/organize-tabs-and-bookmarks/ guide
- reproduced on stage with Fx67, Win10x64

![image](https://user-images.githubusercontent.com/31961530/60956992-86eb1880-a30c-11e9-9204-0a7d93bbf506.png)
![image](https://user-images.githubusercontent.com/31961530/60957000-8c486300-a30c-11e9-98c8-1886802464db.png)

**Comment by muffinresearch** [comment]
The `by` line is part of the title so it's clear why this is happening. I agree it doesn't look great. 

@brassy- what do you think? Perhaps this could be improved by right-aligning the recommended badge and bottom-right aligning the install button?

**Comment by brassy-** [comment]
@muffinresearch I think you're suggestion is very reasonable! I'm ok with right-aligning the recommended badge.
For the button, I'll recommend to center align it with the description.

**Comment by muffinresearch** [comment]
Here's @brassy-'s sketch wireframe to demonstrate:

![Untitled11](https://user-images.githubusercontent.com/1514/61060084-f4bd4000-a3f1-11e9-8564-6bbc0a907ed1.jpg)

**Comment by muffinresearch** [comment]
@bobsilverberg I've assigned this to you for when you have a moment, though it's not super urgent. It will take some minimal refactoring of the layout to move the recommended badge to the right.

**Comment by bobsilverberg** [comment]
@muffinresearch I've started working on this, and I can move the badge to the upper right, but I'm having trouble trying to center align the button with just the description text (as opposed to the description plus the byline). I could do it by converting everything to a grid, but that seems like overkill. I'll come back to it, but I was wondering if you have any quick tips for doing this.

**Comment by muffinresearch** [comment]
> @muffinresearch I've started working on this, and I can move the badge to the upper right, but I'm having trouble trying to center align the button with just the description text (as opposed to the description plus the byline). I could do it by converting everything to a grid, but that seems like overkill. I'll come back to it, but I was wondering if you have any quick tips for doing this.

I'd probably try moving the description and the install button into their own flex container so you can align the button centrally vertically to the whole thing so that if the text is taller than the button the button sits in the centre vertically.

Here's a thrown together simplified example: https://jsbin.com/jejunup/6/edit?html,css,output

**Comment by bobsilverberg** [comment]
Thanks for the advice @muffinresearch. It was very helpful.

**Comment by vcarciu** [comment]
Verified as fixed : 
![allignright](https://user-images.githubusercontent.com/1583842/61383077-a955d680-a8b6-11e9-8842-948aa246c7c4.png)
