### ISSUE TITLE
Can't open HPE Networking Online Configurator on my browser

### ISSUE THREAD

**Issue by rajlabel11** [mozilla/addons-frontend#8286]
### Describe the problem and steps to reproduce it:
when open link https://partner.hpe.com/group/upp-apj/esm/-/link/181101 it said
While using Firefox, the configurator requires the IE Tab plugin to be installed and enabled.

To install the plugin, click here. Once the plugin installation is complete, please restart Firefox.

If you've already installed the plugin, you can make sure it is enabled by:

    Opening the Firefox Add-ons window
        Choose "Tools"
        Then "Add-ons"
    Locate IE Tab in the list of installed plugins, and click the button if it says 'Enable'.
    A button labeled 'Disable' means the plugin is enabled.

When click install plugin, it said:
Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes.

### What happened?
can't load the configuration

### What did you expect to happen?
online configurator

**Comment by wagnerand** [comment]
Please contact the developer of the add-on about its availability on addons.mozilla.org.
