### ISSUE TITLE
I can't find s3 google translator

### ISSUE THREAD

**Issue by RIBAMA** [mozilla/addons-frontend#8289]
All is in title
i don't speek english very well.
the link of astuce
https://www.presse-citron.net/10-extensions-a-installer-de-toute-urgence-sur-firefox/
the link i can't join
https://addons.mozilla.org/fr/firefox/addon/s3google-translator/?src=search

**Comment by jvillalobos** [comment]
It's up to the developer to bring the add-on back. We can't do anything about it.

**Comment by RIBAMA** [comment]
ok, Thank's.
