### ISSUE TITLE
AMO prod homepage fails to load properly

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8292]
STR:
1. Open AMO prod homepage - https://addons.mozilla.org/en-US/firefox/
2. Observe the shelves

Actual result:
The collection shelves are missing 
**Console error:** `Home collection: 4757633/be-more-productive failed to load: Error: Error calling: /api/v4/accounts/account/4757633/collections/be-more-productive/addons/ (status: 401)`

![image](https://user-images.githubusercontent.com/31961530/61035525-fd048380-a3cf-11e9-98cb-144ecc43fea3.png)

Expected result:
The collection shelves are present on the homepage

Notes:
- if I'm logged in when I'm opening the homepage, all the shelves will appear in a loading state and there is again an infinite 403 in the console for `https://addons.mozilla.org/api/v4/accounts/account/4757633/collections/be-more-productive/addons/`

**Comment by AlexandraMoga** [comment]
The issue extends to the collections from the Customize the way Firefox works... section, with the exception of The Password managers and the Ad blockers collections.


![image](https://user-images.githubusercontent.com/31961530/61037097-1529d200-a3d3-11e9-8dff-20461c156a42.png)

**Comment by willdurand** [comment]
"Be more productive" collection:

![Screen Shot 2019-07-11 at 11 25 21](https://user-images.githubusercontent.com/217628/61039222-a185c600-a3ce-11e9-97e3-a77ca4f4bc55.png)

**Comment by muffinresearch** [comment]
Initial single add-ons added back to those collections which should at least ensure the homepage loads. Going to add more data to restore the collections.

**Comment by willdurand** [comment]
YouTube boosters (add-on IDs):

- Enhancer for Youtube: `700308`
- Iridium: `930884`
- SoundFixer: `843270`

**Comment by willdurand** [comment]
Feed readers (add-on IDs):

- Brief: `4578`
- RSSPreview: `1005960`
- Feed Preview: `1006262`
- mPage: `358674`

**Comment by willdurand** [comment]
Screenshot from google cache:

![Screen Shot 2019-07-11 at 11 55 07](https://user-images.githubusercontent.com/217628/61041520-be23fd00-a3d2-11e9-8aad-3d775dec92f7.png)


Smarter Shopping (add-on IDs):

- AliTools for AliExpress: `893039`
- Aliexpress Shopping Assistant: `562120`
- Honey: `415198`
- Trusted Shops extension for Firefox: `523060`

**Comment by willdurand** [comment]
Screenshot from google cache:

![Screen Shot 2019-07-11 at 11 56 57](https://user-images.githubusercontent.com/217628/61041665-00e5d500-a3d3-11e9-8e31-f14617d95d7c.png)

Watching Videos (add-on IDs):

- Enhancer for Youtube: `700308`
- Iridium: `930884`
- SoundFixer: `843270`
- Video Speed Controller: `780998`

**Comment by willdurand** [comment]
Screenshot from google cache:

Bookmark Managers (add-on IDs):

- Group Speed Dial: `785721`
- LinkLocker - Private Bookmarking: `747893`
- OneNote Web Clipper: `731302`
- Bookmarks Manager and Viewer: `743689`

**Comment by willdurand** [comment]
We fixed the issue by re-creating the collections in production 🚀

**Comment by AlexandraMoga** [comment]
Verified fixed:

![image](https://user-images.githubusercontent.com/31961530/61042542-13fda280-a3dd-11e9-915a-ad7981fec068.png)

The collections in the Customize the way Firefox works... are also working

**Comment by willdurand** [comment]
>     * if I'm logged in when I'm opening the homepage, all the shelves will appear in a loading state and there is again an infinite 403 in the console for `https://addons.mozilla.org/api/v4/accounts/account/4757633/collections/be-more-productive/addons/`

I filed https://github.com/mozilla/addons-frontend/issues/8294 for that.
