### ISSUE TITLE
Extend unavailable

### ISSUE THREAD

**Issue by fjscorrea** [mozilla/addons-frontend#8293]
### Describe the problem and steps to reproduce it:

I searched for 'firefox auto refresh' on google and found the 'super auto refresh' link, but when I clicked the link, I was redirected to a page that says the extension is no longer available.

**Comment by wagnerand** [comment]
Please contact the author of the add-on about its availability.

**Comment by wagnerand** [comment]
Please contact the author of the add-on about its availability.
