### ISSUE TITLE
Homepage collections are fetched indefinitely when there is an error and user is logged-in

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8294]
Follow-up #8292 

---

### Describe the problem and steps to reproduce it:

1. Make sure a homepage collection is private or non-existent
2. Make sure your user is logged in
3. Navigate to the homepage

### What happened?

The loading indicators are visible and the page won't load the collection. In addition to that, we can observe countless API calls in the console.

The response is a `403` and when this happens, the frontend tries to re-fetch the collection.

### What did you expect to happen?

The shelf disappears and there is no more API calls.

### Anything else we should know?

When the user is logged out, the API returns `401` responses, which are handled correctly:

- the shelf becomes invisible
- no API call is performed unnecessarily

**Comment by AlexandraMoga** [comment]
Verified fixed on stage:
The homepage will load the available content for logged in users.
- in this screenshot, the Enhanced privacy extensions collection was made private, so its corresponfing shelf is hidden:

![2019-07-18_13-55-22](https://user-images.githubusercontent.com/31961530/61453996-4d4b8a80-a968-11e9-8f4a-7df68ed8605d.png)
