### ISSUE TITLE
Filter menu won't be collapsed when navigating back to a `see more` link

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8295]
STR:
1. On an android device load AMO stage
2. Go to Extensions tab and click a "See more link" from the page
3. Navigate to Themes Tab and click another "See more link"
3. Observe the Filter Menu

Expected result: 
The Filter Menu is closed. 

Actual result:
Filter Menu remained opened. 

Notes:
This is reproducible on all AMO servers - FF68 (Android 8.0)
A page refresh will close the Filter Menu. 

![filter menu](https://user-images.githubusercontent.com/33448286/61058385-ce9e9c80-a3ff-11e9-8b44-4e1f399082cf.gif)

**Comment by willdurand** [comment]
> Expected result:
> The Filter Menu is closed.
> 
> Actual result:
> Filter Menu remained opened.
> 
> Notes:
> A page refresh will close the Filter Menu.

Not sure what the best expected behavior would be here. At least, both actions should have the same result.
