### ISSUE TITLE
Error message displayed when searching addons from recommended addons page

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#8298]
Steps to reproduce:
1.Go to addons.mozilla.org
2.Press the "See more recommended extensions" link from homepage
3. Search for an addon and press Enter

Expected results:
A list of search results is displayed

Actual results:
"The "sort" parameter "random" can only be specified when the "featured" or "recommended" parameter is also present, and the "q" parameter absent." error is displayed and 0 results are found.

Please see screenshot of the issue:
<img width="1144" alt="Screen Shot 2019-07-11 at 19 53 30" src="https://user-images.githubusercontent.com/1583842/61071504-edaa2800-a419-11e9-9319-ddd3de39ff59.png">

**Comment by willdurand** [comment]
I think this patch should fix the issue:

```diff
diff --git a/src/amo/components/AutoSearchInput/index.js b/src/amo/components/AutoSearchInput/index.js
index 422f13fbe..ed9463956 100644
--- a/src/amo/components/AutoSearchInput/index.js
+++ b/src/amo/components/AutoSearchInput/index.js
@@ -9,6 +9,7 @@ import { connect } from 'react-redux';
 import { compose } from 'redux';
 import { withRouter } from 'react-router-dom';
 
+import { SEARCH_SORT_RANDOM } from 'core/constants';
 import SearchSuggestion from 'amo/components/SearchSuggestion';
 import { withFixedErrorHandler } from 'core/errorHandler';
 import { getAddonIconUrl } from 'core/imageUtils';
@@ -151,6 +152,13 @@ export class AutoSearchInputBase extends React.Component<InternalProps, State> {
       delete filtersFromLocation.page;
     }
 
+    if (
+      filtersFromLocation.sort &&
+      filtersFromLocation.sort === SEARCH_SORT_RANDOM
+    ) {
+      delete filtersFromLocation.sort;
+    }
+
     return {
       operatingSystem: convertOSToFilterValue(userAgentInfo.os.name),
```

**Comment by bobsilverberg** [comment]
Note that the fix for this has been pushed to stage, which also now has the recommended badges re-enabled. This should be ready for verification, and our plan is to push this change to prod on Monday.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage with Fx68, Win10x64 and Android 8.0

![2019-07-12_16-40-10](https://user-images.githubusercontent.com/31961530/61132652-80070600-a4c4-11e9-9db0-6efeff204d11.gif)
