### ISSUE TITLE
Error message received when removing the Recommended filter option if the `random` sort parameter is present

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8301]
Similar to #8298

**STR:**

1. Load AMO -dev or stage
2. Click on See more recommended extensions from the homepage shelf
3. Un-check the 'Recommended add-ons only' option from the filters panel

**Actual result:**
The follwoing error is received:
`The "sort" parameter "random" can only be specified when the "featured" or "recommended" parameter is also present, and the "q" parameter absent.`

**Expected result:**
A list of search results is returned

**Notes:**
- reproduced on -dev and stage, but my guess this is also a pre-existing bug, not something introduced by https://github.com/mozilla/addons-frontend/pull/8299

![2019-07-12_13-07-27](https://user-images.githubusercontent.com/31961530/61120612-0b24d380-a4a6-11e9-892f-61b1ef1f5303.gif)

**Comment by bobsilverberg** [comment]
This has been pushed to stage via `2019.07.11-3`, and should land there in a bit for verification.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage with Fx68, Win10x64 and Android 8.0

![2019-07-12_16-50-04](https://user-images.githubusercontent.com/31961530/61133041-4e426f00-a4c5-11e9-89e6-a68fe2ae87fd.gif)

**Comment by bobsilverberg** [comment]
@eviljeff There is a rule in the search API that disallows `sort=random` unless `recommended` was also passed as an argument (in addition to some other rules). This was the cause of the issue I am commenting on.

Now that we've switched to `promoted` from `recommended`, does that code also need to be changed? I'm asking because I'm working on the frontend code, and we have code to make sure we don't pass `sort=random` when we're not also passing `recommended`, and I'm wondering if I need to change that.

**Comment by eviljeff** [comment]
> Now that we've switched to `promoted` from `recommended`, does that code also need to be changed? I'm asking because I'm working on the frontend code, and we have code to make sure we don't pass `sort=random` when we're not also passing `recommended`, and I'm wondering if I need to change that.

yeah, that'll need changing.  Is there an (api) issue already?

**Comment by bobsilverberg** [comment]
> > Now that we've switched to `promoted` from `recommended`, does that code also need to be changed? I'm asking because I'm working on the frontend code, and we have code to make sure we don't pass `sort=random` when we're not also passing `recommended`, and I'm wondering if I need to change that.
> 
> yeah, that'll need changing. Is there an (api) issue already?

I just opened https://github.com/mozilla/addons-server/issues/15462
