### ISSUE TITLE
Add-on icons look squeezed in the guides pages after a page refresh

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8303]
**STR:**

1. Go to AMO homepage - https://addons.mozilla.org/en-US/firefox/
2. Open a guide page - i.e. Stay Safe Online
3. Refresh the page
4. Observe the add-on icons

**Actual result:**
Add-on icons look squeezed after a page refresh

**Expected result:**
Add-on icons are not distorted

**Notes:**
- reproduced on all servers with Fx68, Win10x64
- this could be connected with #8284 

![2019-07-12_15-56-31](https://user-images.githubusercontent.com/31961530/61129864-05d38300-a4be-11e9-8372-0ceb0c3eca46.gif)

**Comment by willdurand** [comment]
@AlexandraMoga could you still reproduce in -dev (as we fixed the other issue mentioned)?

**Comment by AlexandraMoga** [comment]
@willdurand I'm not reproducing anymore. Looks like this issue was indeed fixed by the other changes made for #8284
