### ISSUE TITLE
Remove button misaligned in collection edit pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8316]
### Describe the problem and steps to reproduce it:

1. Log in into AMO -dev and go to your collections https://addons-dev.allizom.org/en-US/firefox/collections/
2. Create a collection with an add-on or two
3. Add a comment to one of the add-ons (with more than 5-6 words)
3. Toggle the edit comment form (optional)

### What happened?

The "Remove" (add-on) button is misaligned when the edit comment form is closed:

<img width="858" alt="Screen Shot 2019-07-15 at 21 45 58" src="https://user-images.githubusercontent.com/217628/61244418-77bffc80-a74a-11e9-9cbf-cd5e8cfedabf.png">

<img width="852" alt="Screen Shot 2019-07-15 at 21 46 07" src="https://user-images.githubusercontent.com/217628/61244419-77bffc80-a74a-11e9-9112-169bbbb14b1e.png">

### What did you expect to happen?

The "Remove" button does not move.

**Comment by willdurand** [comment]
cc @Shubhamchinda

**Comment by Shubhamchinda** [comment]
@willdurand 
Now that I see this again it's not occuring, The "Remove" button is not moving.

**Examples:**

![Screenshot (167)](https://user-images.githubusercontent.com/21038543/61267634-44b35280-a7b6-11e9-9657-372e0e4a3235.png)

![Screenshot (169)](https://user-images.githubusercontent.com/21038543/61267635-454be900-a7b6-11e9-82a1-ece6fe6b974f.png)


I don't know why it's not occuring now.

**Comment by Shubhamchinda** [comment]
> @willdurand
> Now that I see this again it's not occuring, The "Remove" button is not moving.
> 
> **Examples:**
> 
> ![Screenshot (167)](https://user-images.githubusercontent.com/21038543/61267634-44b35280-a7b6-11e9-9657-372e0e4a3235.png)
> 
> ![Screenshot (169)](https://user-images.githubusercontent.com/21038543/61267635-454be900-a7b6-11e9-82a1-ece6fe6b974f.png)
> 
> I don't know why it's not occuring now.

**It's breaking again**
It's so wierd.

1.
![Screenshot (170)](https://user-images.githubusercontent.com/21038543/61267981-aaeca500-a7b7-11e9-9630-ce32af2bb23d.png)

2.
![Screenshot (171)](https://user-images.githubusercontent.com/21038543/61267982-ab853b80-a7b7-11e9-9653-b35b9c4e29df.png)

3.
![Screenshot (172)](https://user-images.githubusercontent.com/21038543/61267984-ab853b80-a7b7-11e9-8fa4-185208ec0fc2.png)

**Comment by willdurand** [comment]
@Shubhamchinda it looks related to the length of the collector's note, no?

**Comment by Shubhamchinda** [comment]
> @Shubhamchinda it looks related to the length of the collector's note, no?

@willdurand No, I meant the input text length but I guess it's fixed now. You can check the patch.

**Comment by vcarciu** [comment]
Verified as fixed: 
![remove](https://user-images.githubusercontent.com/1583842/61301712-23ba2400-a7ed-11e9-9333-c1bab0fe32a7.png)
