### ISSUE TITLE
Install button misaligned on guides page when add-on is not recommended

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8324]
This is a follow-up to PR #8315. If the Recommended Badge is not displayed, due to an add-on not being recommended, the Install Button is still center-aligned with the add-on description, rather than being center-aligned with the entire contents of the card.

We do not expect there to ever be any add-ons on the guides page that are not recommended, but we should probably address this in case there ever are.

Here's how it looks now, when the badges are missing:

![Screenshot 2019-07-16 12 22 49](https://user-images.githubusercontent.com/142755/61311496-77644780-a7c4-11e9-9cb6-758feff99bdb.png)

And here's how it looked before fixing the badge alignment issue:

![Screenshot 2019-07-16 12 24 01](https://user-images.githubusercontent.com/142755/61311575-9c58ba80-a7c4-11e9-882c-e006cbbca73f.png)

**Comment by Shubhamchinda** [comment]
@bobsilverberg Can I take it?

**Comment by bobsilverberg** [comment]
@Shubhamchinda certainly!

**Comment by Shubhamchinda** [comment]
@bobsilverberg Can you please tell me the exact link where the problem is occuring.
Thanks :)

**Comment by muffinresearch** [comment]
@bobsilverberg is this actually an issue?

**Comment by bobsilverberg** [comment]
> @bobsilverberg is this actually an issue? The first screenshot looks better to my eyes but maybe UX would disagree.

I think it both is and isn't an issue. There is a visual regression when the recommended badge is missing on a guides card, *but*, in production we really shouldn't ever have a situation where an add-on is on a guides page but it not recommended. For that reason I think we can safely close this issue. It really only needs to be fixed for the "just in case" case where a guides add-on is not recommended, but that isn't something we ever expect to be the case.

**Comment by muffinresearch** [comment]
> > @bobsilverberg is this actually an issue? The first screenshot looks better to my eyes but maybe UX would disagree.
> 
> I think it both is and isn't an issue. There is a visual regression when the recommended badge is missing on a guides card, _but_, in production we really shouldn't ever have a situation where an add-on is on a guides page but it not recommended. For that reason I think we can safely close this issue. It really only needs to be fixed for the "just in case" case where a guides add-on is not recommended, but that isn't something we ever expect to be the case.

The button being centred in reference to the description text seems fine to me with or without a recommended badge. So on the basis this is a "just in-case" fix and the "regression" state looks completely reasonable, I think we can definitely wontfix.

**Comment by bobsilverberg** [comment]
> 
> The button being centred in reference to the description text seems fine to me with or without a recommended badge. So on the basis this is a "just in-case" fix and the "regression" state looks completely reasonable, I think we can definitely wontfix.

Fair enough, and I agree. Thanks @muffinresearch.
