### ISSUE TITLE
recommended addon badge distorts listing in `Other popular extensions` section

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#8330]
### What happened?
Goto any URL with recommended addons in `Other popular extensions` section
(https://addons.mozilla.org/en-US/firefox/addon/fullscreen-plus/)

### What did you expect to happen?
4 addons listed without any distortion 

### Anything else we should know?
Recommended addon with long name breaks the layout. (Screenshot attached)

![image](https://user-images.githubusercontent.com/5318732/61374974-0002e680-a89e-11e9-9ba7-7ccc64d2ca59.png)

**Comment by kumar303** [comment]
Thanks for the bug report, @tsl143 . I can take a look.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with Fx68, WIn10x64

![2019-07-23_14-38-45](https://user-images.githubusercontent.com/31961530/61709715-7d27d300-ad58-11e9-8f22-438357171f07.gif)

**Comment by muffinresearch** [comment]
This can be broken as follows:

<img width="1122" alt="Webmail_Ad_Blocker_–_Get_this_Extension_for_🦊_Firefox__en-US_" src="https://user-images.githubusercontent.com/1514/61724387-c6325400-ad65-11e9-88b1-b6902bb5b8f8.png">

Width is 1189px. 
URL: https://addons-dev.allizom.org/en-US/firefox/addon/webmail-ad-blocker/

Note I did modify the title.

**Comment by kumar303** [comment]
@muffinresearch good idea, thanks. I added it in https://github.com/mozilla/addons-frontend/pull/8378

**Comment by ioanarusiczki** [comment]
@kumar303 I checked this on dev and stage with FF68(Win10). 
The `Recommended` badge falls right under the name of the add-ons once it's more than 204 px in length - I left the screen at the normal size without resizing it and I am working on a desktop (Win10 with recommended resolution 1920x1080)

The maximum allowed 

![204 px](https://user-images.githubusercontent.com/33448286/62214230-4e8ba700-b3ad-11e9-8a00-68661bee1ad4.png)

More than 204 px will push the badge right under the Name 

![more than 204 px](https://user-images.githubusercontent.com/33448286/62214286-6cf1a280-b3ad-11e9-926c-4ccde352d98a.png)

At 1372x830 px the badge will fall under the Name when resizing the screen 

![responsive mode](https://user-images.githubusercontent.com/33448286/62215171-1ab18100-b3af-11e9-8ed7-9e64d4b9802f.gif)

It looks good to me.
Let me know if it's how you expected it.

**Comment by kumar303** [comment]
Yes, that's how I expect it to work. Thanks.
