### ISSUE TITLE
Move locale bn-BD to bn 

### ISSUE THREAD

**Issue by peiying2** [mozilla/addons-frontend#8336]
We are going to merge the two bn-* locales into one to fully utilize the community resources. The frontend has only bn-BD. We want to sync up with the rest of the localized products/projects. The plan is

Dev:
- AMO Frontend creates a bn folder at repo
- Move bn-BD repo content to bn repo and confirm it's all there
- Remove bn-BD repo

Pontoon (l10n):
- Pontoon dev migrates the data to bn (this includes contributors histories)
- L10n PM confirms the update and closes this issue.

**Comment by peiying2** [comment]
@entequak

**Comment by muffinresearch** [comment]
Note: This will also need co-ordination with addons-server too to ensure the server has the correct locales there.

**Comment by peiying2** [comment]
> Note: This will also need co-ordination with addons-server too to ensure the server has the correct locales there.

Yes, indeed. I have opened two separate issues respectively: https://github.com/mozilla/addons-server/issues/11816, https://github.com/mozilla/addons-linter/issues/2696.

**Comment by AlexandraMoga** [comment]
Verified on stage with Fx68. The `বাংলা` option from the languages list will load the `/bn/` locale - https://addons.allizom.org/bn/firefox/

@willdurand I also have an observation:
If I'm trying to load https://addons.allizom.org/bn-BD/firefox/, the site will redirect to https://addons.allizom.org/en-US/firefox/.
On the server side (see https://github.com/mozilla/addons-server/issues/11816#issuecomment-514506634) `/bn-BD/` redirects to `/bn/`. Shouldn't this happen on the frontend as well?

**Comment by willdurand** [comment]
> @willdurand I also have an observation:
> If I'm trying to load [addons.allizom.org/bn-BD/firefox](https://addons.allizom.org/bn-BD/firefox/), the site will redirect to [addons.allizom.org/en-US/firefox](https://addons.allizom.org/en-US/firefox/).
> On the server side (see [mozilla/addons-server#11816 (comment)](https://github.com/mozilla/addons-server/issues/11816#issuecomment-514506634)) `/bn-BD/` redirects to `/bn/`. Shouldn't this happen on the frontend as well?

mmh, maybe? I don't think we support that out of the box. I don't know how it is handled in the server.. It's likely the first time we have to rename a locale, so I don't know.

Redirecting from `/bn-BD/` to `/bn/` seems logical though. I did not think about it when the patch has been merged because the linter and the server had their patches merged already and according to the comments above, we needed to sync the 3 projects.

@muffinresearch what do you think?

**Comment by muffinresearch** [comment]
@will you might be able to use this config:

https://github.com/mozilla/addons-frontend/blob/f33aa3e5da8bbf3c91fef0102bfd2e0ac7a0c783/config/default.js#L275-L281

Which is usually used to expand short locales.

**Comment by willdurand** [comment]
> @willdurand I also have an observation:
> If I'm trying to load [addons.allizom.org/bn-BD/firefox](https://addons.allizom.org/bn-BD/firefox/), the site will redirect to [addons.allizom.org/en-US/firefox](https://addons.allizom.org/en-US/firefox/).
> On the server side (see [mozilla/addons-server#11816 (comment)](https://github.com/mozilla/addons-server/issues/11816#issuecomment-514506634)) `/bn-BD/` redirects to `/bn/`. Shouldn't this happen on the frontend as well?

@AlexandraMoga thanks, I filed https://github.com/mozilla/addons-frontend/issues/8388 for that.

**Comment by AlexandraMoga** [comment]
Great! I can mark this as verified fixed then.
