### ISSUE TITLE
Problem running local site over https

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8341]
### Describe the problem and steps to reproduce it:
Try to run addons-frontend locally over https following all of the instructions at https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md#developing-with-a-local-https-server-recommended.

### What happened?
1. You get a warning about an invalid certificate which must be added as an exception.
2. After adding the exception for `example.com:3000`, the site does not look right (the css for the site appears not to be served) and AddonManager is not available.

### What did you expect to happen?
I expect to see the site as it's supposed to look, and to have AddonManager available.

### Anything else we should know?
Firefox warns that the certificate has expired. I found that adding a second exception for `example.com:3001` fixes the problem as that allows the webpack script to run.

It sounds like we should look into getting a new cert which is not expired.

**Comment by kumar303** [comment]
As a temporary solution we could add a step to the docs about overriding the expired cert.

> It sounds like we should look into getting a new cert which is not expired.

I think it came from an old test pilot repo? We could ask someone over there.

**Comment by willdurand** [comment]
The certificates have been added in this PR: https://github.com/mozilla/addons-frontend/pull/3808. @jrbenny35 do you know where you got them?

I think those are self-signed certificates, likely based on this script: https://github.com/TomShacham/http4js/blob/55ee6194117f7c6872ac4df801d1ee94cbf7359f/create-ssl-certs.sh#L22 (according to the `openssl` outputs).

I believe we can "just" generate new certificates.

**Comment by willdurand** [comment]
The SSL certificate expired on July 11:

```
$ openssl x509 -noout -dates -in bin/local-dev-server-certs/example.com.ca.crt.pem
notBefore=Sep 20 21:28:04 2016 GMT
notAfter=Jul 11 21:28:04 2019 GMT
```

**Comment by willdurand** [comment]
> As a temporary solution we could add a step to the docs about overriding the expired cert.

Can we? I think HSTS prevents that and it seems enforced somehow.

I don't know why we have built-in certificates/key and how we can update them, but if we do not need them anymore, let's adopt and document https://github.com/FiloSottile/mkcert

@jrbenny35 could you please look at the certs and see if we can update them in this repo? Thanks!

**Comment by kumar303** [comment]
Oh, heh, I filed https://github.com/mozilla/addons-frontend/issues/8661
