### ISSUE TITLE
containers on the go

### ISSUE THREAD

**Issue by keybounce** [mozilla/addons-frontend#8344]
### Describe the problem and steps to reproduce it:

I was  attempting to learn about "container tabs" (nb: a really bad name for what it is doing.)

On page https://blog.mozilla.org/tanvi/2017/10/03/update-firefox-containers/ I was referred to https://addons.mozilla.org/en-US/firefox/addon/containers-on-the-go/

That is now an error page, "this project is not available, please file this error report".

**Comment by willdurand** [comment]
@caitmuenster any chance we can update the blog post to adjust the link?

**Comment by caitmuenster** [comment]
Thanks, @keybounce! At the top of the blog, there's a link to the Multi-Account Containers extension. Is that sufficient?

**Comment by keybounce** [comment]
On 2019-07-23, at 1:41 PM, Caitlin Neiman <notifications@github.com> wrote:

> Thanks, @keybounce! At the top of the blog, there's a link to the Multi-Account Containers extension. Is that sufficient?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Not really, in my case. 
It was listed in the section on add-ons and the API.

> With these APIs, developers can create new Container addons that work for exactly the use case they have in mind.

I was hoping to look at those 3rd party "container" enhancements to see which would be what I'm looking for. I saw a lot of references to "Containers on the Go", so for some people, it was the right extension for a while.

"Multi-account containers" does not run on my system (stuck on 52.9 ESR). A much older version does work, and that enables the basic "container" GUI.

(Why the name "container"? It's really about web browsing context. A "container tab" would be a tab that contains tabs.)

---
Entertaining minecraft videos
http://YouTube.com/keybounce

**Comment by muffinresearch** [comment]
Since this repo isn't related to the blog content, there's no action we can take here so I'm closing this out.

**Comment by Davilink** [comment]
I have this extension installed on version of Firefox, but why i cannot find it in the store ?? Has it been deleted ? Why ? Should i stop using it ?

**Comment by caitmuenster** [comment]
@Davilink You can download the extension from here: https://addons.mozilla.org/firefox/addon/multi-account-containers/

**Comment by Davilink** [comment]
@caitmuenster Thats not the same thing. « Container on Go  » had a shortcut that opened a new tab with a new temporary container (C1, C2, C3, .... ). The extension you propose is just he containers mecanism. And when all the tab of same temporary containers, « Container on the go » whould clear that container.

* click on the button *
- open a new tab with the container to c1
* click on the button *
- open a new tab with the container to c2
* click on the button *
- open a new tab with the container to c3
[available container : c1, c2, c3]

*close tab of c1*
[available container : c2, c3]
*open a tab with the c2 container*
[available container : c2, c3]
*close tab of c3*
[available container : c2]
*close 1 tab of c2*
[available container : c2]
* click on the button *
- open a new tab with the container to c1 (it's a name c1, but it a completely new container)
[available container : c1, c2]
*close 1 tab of c2*
[available container : c1]
*close tab of c1*
[available container : -none-]
