### ISSUE TITLE
Create an InstallWarning component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8347]
This is a spin-off from #8137 

Create an InstallWarning component that can be displayed at the bottom of an add-on card to warn users about installing non-recommended add-ons. This component will also include most of the functionality for the A/B test.

Here's an example of what it will look like in an add-on card:

<img width="799" alt="Screenshot 2019-07-19 12 57 46" src="https://user-images.githubusercontent.com/142755/61552061-d2947500-aa24-11e9-9135-40aff92b04fa.png">

**Comment by rbrishabh** [comment]
Hey! Can I take this up?

**Comment by bobsilverberg** [comment]
Marking this as qa:not needed as it cannot really be tested without the warning being displayed anywhere, and there's nothing in this patch that causes the warning to be displayed. That will come in #8137 and I'll add some testing instructions about this into that issue.
