### ISSUE TITLE
link text is `see more popular extensions` in Popular themes section on home

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#8349]
### What happened?
Goto https://addons.mozilla.org/en-GB/firefox/
Scroll to popular theme section
Link has text `see more popular extensions`

### What did you expect to happen?
Link should have text `see more popular themes`

### Anything else we should know?
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/5318732/61575439-1abaa280-aacc-11e9-983b-9411e501fa4a.png">

**Comment by Shubhamchinda** [comment]
@tsl143 Can I take it?

**Comment by willdurand** [comment]
I believe it's a localization issue, see Pontoon entry: https://pontoon.mozilla.org/en-GB/amo-frontend/LC_MESSAGES/amo.po/?search=more+re&string=200348.

This should be fixed _via_ Pontoon I believe.
