### ISSUE TITLE
Display of recommendations badge in other popular extensions is broken for long text

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#8374]
### Describe the problem and steps to reproduce it:

See this screenshot:

<img width="866" alt="Google_Search_Fixer_–_Get_this_Extension_for_🦊_Firefox__en-US_" src="https://user-images.githubusercontent.com/1514/61722993-2ffd2e80-ad63-11e9-9c34-3c76c4271aa3.png">

### What happened?

With long text the recommendations badge display is impacted.

### What did you expect to happen?

The layout should accomodate long text.

### Anything else we should know?

N/A

**Comment by willdurand** [comment]
Is it different than https://github.com/mozilla/addons-frontend/issues/8330?

**Comment by muffinresearch** [comment]
> Is it different than #8330?

Ah thanks @willdurand it's a dupe, I didn't find it because I search for "Recommendations" not "Recommended" :/
