### ISSUE TITLE
Limit abuse report content to 10,0000 characters

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#8385]
Related to https://github.com/mozilla/addons-server/issues/11921.

The server is limiting the length of an abuse report body to 10,000 characters. We need to show this limitation in the frontend.

@brassy- for UX and deciding whether a static note will do or whether we need an interactive counter.

**Comment by willdurand** [comment]
Dowgrading to p3 as it needs some work in addons-server. Once done, the api will reject large abuse reports and we should already have the logic in place to show the error message.

**Comment by EnTeQuAk** [comment]
The server-side patch has landed on -dev and is targeted to land on -prod next week.

**Comment by willdurand** [comment]
So, as I said, we have the current UI:

<img width="402" alt="Screen Shot 2019-07-25 at 12 27 15" src="https://user-images.githubusercontent.com/217628/61867455-92773b80-aed7-11e9-8802-aeffe7314757.png">

It'd be nice to have a better validation message but that's all.

**Comment by ioanarusiczki** [comment]
@willdurand I think this can be closed as it landed on prod this week. I checked the message on the frontend while testing today for https://github.com/mozilla/addons-server/issues/11958
The message is now `Please ensure this field has no more than 10000 characters" 

![message from AMO](https://user-images.githubusercontent.com/33448286/62371444-8f1a2a80-b53d-11e9-9a06-0444a70516ed.png)

I verified with FF68 (Win10) on stage and prod.

**Comment by willdurand** [comment]
ah yes, perfect!
