### ISSUE TITLE
Redirect `bn-BD` to `bn`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8388]
### Describe the problem and steps to reproduce it:

Load an URL with `bn-BD` as locale, _e.g._, https://addons-dev.allizom.org/bn-BD/firefox/

### What happened?

You get redirected to https://addons-dev.allizom.org/en-US/firefox/

### What did you expect to happen?

You get redirected to https://addons-dev.allizom.org/bn/firefox/

### Anything else we should know?

See also: https://github.com/mozilla/addons-frontend/issues/8336

**Comment by ruchikabgosain** [comment]
hey @willdurand i would like to take this up! is this issue available?

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![2019-07-29_17-03-59](https://user-images.githubusercontent.com/31961530/62054797-fb85e880-b222-11e9-9333-5abe59425b3c.gif)
