### ISSUE TITLE
Yet another site (Interclue.com this time) claims a nonexistent page exists on your site

### ISSUE THREAD

**Issue by blahdiblah** [mozilla/addons-frontend#8394]
The homepage (http://interclue.com) of a bolt-on utility I use in your browser, at the address referenced by its documentation. auto redirects me to a page at your domain. Unfortunately all this gives is a 404 - currently this is the commonplace result of external links into your site, maybe you're running out of server space? I thought storage was pretty inexpensive these days :-(

**Comment by willdurand** [comment]
I think the URL is incorrect or the add-on has been removed by their author. We have enough storage, don't worry ;-)
