### ISSUE TITLE
Unify long string handling in CSS

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#8396]
We've had [many issues filed](https://github.com/mozilla/addons-frontend/search?q=unbroken+string&unscoped_q=unbroken+string&type=Issues) related to long string handling in the past. 

We've used a few different solutions.

* https://github.com/mozilla/addons-frontend/search?q=overflow-wrap&unscoped_q=overflow-wrap
* https://github.com/mozilla/addons-frontend/search?q=word-wrap&unscoped_q=word-wrap

`overflow-wrap: anywhere` is not cross browser looking at https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap#Browser_compatibility

So we should check on these cases and figure out how to unify them into one solution e.g. a mixin.

---

**For QA:** this can affect any page on any screen dimensions. Please double check all pages with user content, using long unbroken strings.

**Comment by harshsingla** [comment]
@muffinresearch ,I want to try this bug if possible ,can you explain more about it

**Comment by caitmuenster** [comment]
Hey @harshsingla, thanks so much for your interest in this issue! This probably isn't a good first issue to get started on (and muffinresearch is on PTO for the next few weeks). 

We label good entry issues with the `[contrib: good first bug](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug)` label. We don't have any open ones at the moment, but there will likely be some available if you check back in a few weeks!

**Comment by harshsingla** [comment]
hello @caitmuenster ,no problem i will go and check the 'good first bug' label ,thanks for the guidance.

**Comment by Shubhamchinda** [comment]
Hey @caitmuenster , please [see comment](https://github.com/mozilla/addons-frontend/pull/8366#issuecomment-515551586). We can create a mixin of `word-break: break-word;` to fix these issues.

Thanks!

**Comment by codeEmpress1** [comment]
Hi, I am an outreachy applicant, can I work on this issue

**Comment by caitmuenster** [comment]
Hi @codeEmpress1, welcome! Issues labled`contrib: welcome` in this repository are usually considered to be "good second bugs" or good for contributors familiar with the codebase. 

You can work on this, but if you're looking for more hands-on mentorship I would recommend working on an issue labeled `[contrib: good first bug](https://addons-pm.herokuapp.com/contrib/maybe-good-first-bugs/?dir=desc&sort=updatedAt).'

**Comment by codeEmpress1** [comment]
Thanks @caitmuenster, I will study the codebase and give it a trial. Also, I have shown interest in an issue labeled `contrib: good first bug`. I can contribute on both issues.

**Comment by Albaalah** [comment]
can I work on it seeing as it's still open?

**Comment by willdurand** [comment]
> can I work on it seeing as it's still open?

Sorry @Albaalah, this one is already taken.

**Comment by ioanarusiczki** [comment]
@willdurand I tried to cover all pages with user input on AMO dev and AMO stage - FF76(Win10). 
I filed the following (I find all of them edge cases, maybe expect for the first isssue which involves the homepage):
this looks like a regression https://github.com/mozilla/addons-frontend/issues/9432
https://github.com/mozilla/addons-frontend/issues/9433
https://github.com/mozilla/addons-frontend/issues/9436
