### ISSUE TITLE
problem with installing livereload

### ISSUE THREAD

**Issue by EvgeniyKoren** [mozilla/addons-frontend#8397]
### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/addon/livereload/

![изображение](https://user-images.githubusercontent.com/52611166/61962014-47d9ea00-afd1-11e9-8fde-170cf0122a05.png)

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
