### ISSUE TITLE
Remoku's Firefox Addon Link is Broken

### ISSUE THREAD

**Issue by djelttt** [mozilla/addons-frontend#8402]
### Describe the problem and steps to reproduce it:
![Remoku_Help_Page](https://user-images.githubusercontent.com/34720886/62002744-d3ca3f80-b0bf-11e9-9cd0-2136a9576882.jpg)

On <http://help.remoku.tv/>, I clicked the link, entitled "Firefox Addon", which requests I am taken to:  <https://addons.mozilla.org/addon/remoku/ 

### What happened?

I was taken to <https://addons.mozilla.org/en-US/firefox/addon/remoku/>, where I was given the following message:
------------------------------------------------------------------------------------------
Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes.
-----------------------------------------------------------------------------------------

### What did you expect to happen?

I wasn't sure what to expect. The Remoku was already working, in that it was controlling my Roku Stick Plus. I thought, with the addon, I might gain some additional functionality or integration.

### Anything else we should know?

Page: <http://help.remoku.tv/>

![Remoku_Help_Page](https://user-images.githubusercontent.com/34720886/62002744-d3ca3f80-b0bf-11e9-9cd0-2136a9576882.jpg)

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
