### ISSUE TITLE
IBM Agile Verse Extension Missing

### ISSUE THREAD

**Issue by GeeSkndr** [mozilla/addons-frontend#8403]
**### Describe the problem and steps to reproduce it:**
Click below link to IBM Agile Verse extension
**### What happened?**
"Oops! We can’t find that page"
**### What did you expect to happen?**
The extension to be available for installation
**### Anything else we should know?**
The extension was available and it was crucial for me to use IBM verse over firefox as it adds a lot of needed tweaks. I accidentally uninstalled it and tried to re-install but found it was removed. If the developer has removed it please let me know how to contact them.
_<https://addons.mozilla.org/mn/firefox/addon/agileverse/>_

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
