### ISSUE TITLE
install button issue while installing older versions

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#8405]
### What happened?
Try to install older version of any addon
1. Goto https://addons.mozilla.org/en-US/firefox/addon/word-count/versions/
2. click older version `1.1`
3. Spinner observed on every install button

### What did you expect to happen?
3. Spinner should be observed only on button clicked

### Anything else we should know?

![image](https://user-images.githubusercontent.com/5318732/62038598-548b5780-b1f6-11e9-8b60-3341b43ec26c.png)
![image](https://user-images.githubusercontent.com/5318732/62038626-62d97380-b1f6-11e9-860e-034b754d7b96.png)

**Comment by willdurand** [comment]
That looks intended (unfortunately): https://github.com/mozilla/addons-frontend/issues/7332.

/cc @bobsilverberg we should maybe revisit this, it's very confusing.

**Comment by bobsilverberg** [comment]
> That looks intended (unfortunately): #7332.
> 
> /cc @bobsilverberg we should maybe revisit this, it's very confusing.

It does look like this was discussed quite a bit in #7332, which resulted in this decision. I'm not sure it makes much sense to revisit it, as I don't imagine it would be given a very high priority even if we were to change our minds about it. I agree it is a bit confusing, but considering how often the use case would come up (which I assume is not very often), it doesn't seem like a very high priority.
