### ISSUE TITLE
Our Extension not available on Firefox : Amazon Publisher Studio

### ISSUE THREAD

**Issue by sanjay-git** [mozilla/addons-frontend#8407]
### What happened?

Our Add-on https://addons.mozilla.org/en-US/firefox/addon/amazon-publisher-studio-extens/ shows as not available anymore in Firefox.

### What did you expect to happen?
We would like to know the reason for the removal of this Add-on. And the timeline on when the add-on was removed

### Anything else we should know?

https://addons.mozilla.org/en-US/firefox/addon/amazon-publisher-studio-extens/

**Comment by wagnerand** [comment]
Please see the "Review History" details on https://addons.mozilla.org/en-US/developers/addon/amazon-publisher-studio-extens/versions.

Alternatively, you should have received an email when the review was sent.

**Comment by sanjay-git** [comment]
Hello,

I am from the Amazon team that developed this add-on, but the team has lost the credentials used to manage this add-on.

Is there any way to re-send the email to another amazon account so that we would know the timeline of the add-on?


Thanks in Advance,
Sanjay

**Comment by wagnerand** [comment]
You can reset your Firefox account password through https://accounts.firefox.com/.

**Comment by sanjay-git** [comment]
Thanks for the quick response. We do not have any details w.r.t the account used for this add-on.
Is there any way to transfer the ownership in cases like these? We will go through any process to authenticate ourselves as the rightful owners.

**Comment by wagnerand** [comment]
I'm sorry since we cannot verify your identity, we cannot transfer accounts.
