### ISSUE TITLE
ThreatPinch plugin?

### ISSUE THREAD

**Issue by d00m3dd00d** [mozilla/addons-frontend#8409]
### What happened?
Visited https://addons.mozilla.org/en-US/firefox/addon/threatpinch-lookup-for-firefox/

### What did you expect to happen?
The plugin was not found

### Anything else we should know?
I don't believe there are other threat-hunting tools like this, this tool is very useful.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
