### ISSUE TITLE
Add-on Count of Collections and Old Add-ons That Come Back

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8411]
### Describe the problem and steps to reproduce it:

What happens to add-on count of Collections?

When I visit the My Collections page of "new" addons.mozilla.org website, count of the number of add-ons in a collection is first based on last count using OLD add-ons (pre-v57). 

When you open a personal collection, count is updated to current number of add-ons that are now available. 

The question is, if an author then updates their add-on that was previously incompatible with v57+ that was originally part of a collection, but the count on the collection has been updated to no longer count that add-on, will that add-on re-appear in the collection and the respective count also be updated once again?

If not, that would be a great loss. I would ask that the link to the add-on be maintained and preserved incase it "resurfaces". If this is already accounted for, that is good news.

**Comment by smayer97** [comment]
This might also be related to:
https://github.com/mozilla/addons-frontend/issues/4789

**Comment by willdurand** [comment]
> The question is, if an author then updates their add-on that was previously incompatible with v57+ that was originally part of a collection, but the count on the collection has been updated to no longer count that add-on, will that add-on re-appear in the collection and the respective count also be updated once again?

Yes, I think this updated count is dynamic (it counts the number of items we're going to display instead of using the cached value).

**Comment by smayer97** [comment]
Sorry, but based on that reply, I am not sure if my original question was totally clear. My question is not simply about whether the count is dynamic but rather if a legacy add-on that was originally part of a collection, which now no longer shows up, would it automatically show up again, and therefore also impact the count? In other words, does the collection retain a hidden record that the legacy add-on is still part of it, so if it does get updated, the system will still remember to add it back?

I hope that is a little clearer.

**Comment by willdurand** [comment]
> Sorry, but based on that reply, I am not sure if my original question was totally clear. My question is not simply about whether the count is dynamic but rather if a legacy add-on that was originally part of a collection, which now no longer shows up, would it automatically show up again, and therefore also impact the count? In other words, does the collection retain a hidden record that the legacy add-on is still part of it, so if it does get updated, the system will still remember to add it back?

mmh, I believe it does although what we consider "legacy extensions" have been removed a while ago.

**Comment by smayer97** [comment]
Ok, so how do I get a definitive answer on my 2-part question?
