### ISSUE TITLE
A way to simplify the Add-on Collection page(s)

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8412]
### Describe the problem and steps to reproduce it:

2 pages are currently used for collections; one to list the add-ons in the collection, the other to edit the collection.

I propose simplifying the interface so that only one page is needed:
- move the "Edit this collection" features to the main page: Search, Add A Note, Remove, and Edit (when a note is present).
- move the "Edit collection details" to main page to replace "Edit this collection"

I think this would make for a simpler interface by keeping it all on one page; more obvious and eliminating the need to go back and forth all the time. It also makes the sort make more sense.

I also suspect it would make maintaining one page simpler than having two.

I believe it is a simple change that make the UX more straight-forward and streamlined.

**Comment by jvillalobos** [comment]
I don't think it makes things simpler. Editing an item while you're looking at it is a more intuitive approach than having to navigate out to the index. This proposal seems optimized for users who have very large numbers of collections, which is not the norm.

**Comment by smayer97** [comment]
Sorry, I do not understand the response.  

You say "Editing an item while you're looking at it is a more intuitive approach than having to navigate out to the index." That is EXACTLY what I am asking for... editing in place....

Currently, you have to click "Edit Collection" to go to a SEPARATE page to perform edits rather than "in place". What I am proposing IS "editing in place".

So I am not sure we are understanding each other. Please clarify.

**Comment by jvillalobos** [comment]
Oh yeah, I misunderstood what you meant by "main page", sorry about that. Editing in the same page was also something I wanted initially, but it turned out to be technically challenging. Keeping a separation between "view only" and "edit" pages allows the site to remain fast and easier to maintain.

**Comment by smayer97** [comment]
Oh, that's too bad. But thanks for clarifying.
