### ISSUE TITLE
Notes/Comments for Add-ons Missing in My Collections

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8413]
### Describe the problem and steps to reproduce it:

When accessing My Collections, I used to have LOTS of notes with many add-ons. Those are not currently showing up.

I vaguely recall having a similar discussion about this before but I cannot seem to track that down here. I recall something about Firefox Locales being part of the issue, something about the comments being entered using one locale, but if I use another, the comments do not show up. 

Is this correct and  still applicable? are my comments under a different locale than I might be using? If so, is there any way to know which locale notes/comments were entered with? And is there a way to have them show up under both, or transfer them? Or are they gone for good?

Any assistance would be appreciated.

**Comment by diox** [comment]
Collection notes are indeed locale-dependent (honestly there is no good reason for this anymore, but it's legacy we have to deal with).

@smayer97 if you give us your user id we could try to look if the comments are still there.

**Comment by smayer97** [comment]
what ID do you need, my e-mail address? That is what I use to log in. Is that not visible to you?

**Comment by jvillalobos** [comment]
Not on Github. The user ID is `2735762`.

**Comment by smayer97** [comment]
OK. so do you need anything more from me? Just want to be sure.

**Comment by diox** [comment]
You've got a lot of collections. Can you give me the name of one in particular that's missing notes ? And if possible, which add-on the note was for ?

**Comment by smayer97** [comment]
Sorry for the late reply...not easy finding a collection because so many of my notes were also tied to many add-ons that no longer exist.

Anyway, I did find one...this collection: https://addons.mozilla.org/en-CA/firefox/collections/2735762/favorites/

I notice that the note missing is for the Tiles Tabs WE add-on. I figured out that the note is tied to the en-GB locale. So if I view this collection with the en-CA or en-US locale, I cannot see the notes.
(This is only one example, and not much to work with. If I come across any more, I will point them out).

Problem is that over the years I have used all 3 locales, not realizing the impact. Not sure if there is more to this issue. Can notes in collections be made to not depend on the locale?

**Comment by diox** [comment]
Ok so, yeah, it's because of the locale and specifically, how locales work in collections (badly). We've got an issue about getting rid of the localization in collections entirely (https://github.com/mozilla/addons-server/issues/8701) so I'll close this one as duplicate.

**Comment by smayer97** [comment]
Ok Thx. I do hope that in whatever solution is implemented that it takes into account notes created in more than one locale for the same entry in a collection, e.g. merging them or something. 

I'll add a comment about this in the other thread.
