### ISSUE TITLE
Add Sort to "My Collections"

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8414]
### Describe the problem and steps to reproduce it:

currently My Collections  lists in seemingly random order. Would be nice if they were at least sorted by name. 

Ideally it would be even nicer if some sort options were added like: By Name, By date Created, By Date Updated.

**Comment by willdurand** [comment]
Thanks for your feedback, I am going to close this issue but will reference it in https://github.com/mozilla/addons-frontend/issues/3252.

**Comment by smayer97** [comment]
Actually, these do not appear to be the same...
#3252 seems to deal with sorting search results of add-ons by name.
My requests is about sorting the name of Collections on the My Collections page.

**Comment by willdurand** [comment]
I know, but collections are mentioned too and I've highlighted that.

**Comment by smayer97** [comment]
Ok. But as you know, these are different areas of the front-end. There are already sorting tools in other areas. But if you don't think that needs to be tracked separately, I defer to you.
Thx.
