### ISSUE TITLE
Add Indicator in Add To Collection menu to identify which Collection it already belongs to.

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8415]
### Describe the problem and steps to reproduce it:

It is frustrating to keep getting the "This addon already belongs to this collection" when adding it. OR worse, is thinking an add-on already belongs to a collection only to discover much later that you never added it, because there was no easy way to identify it is already added. You don't always remember if you added it in the past.

Also frustrating that there is no way to identify which of my collections an add-on already belongs to for curation. This can result in an addon being added to more than one collection or creating a new collection unnecessarily resulting in duplication. Makes a mess of collections.

Another use is when deciding where to add a new add-on to a collection, you want to place it with an existing one. So one way in the past that was used is to look at the list of add-ons that the other add-on already exists, then add the new one to the same collection. 

Please add some way to identify which of my collections an addon exists in, ideally right in the "Add to collection" drop-down menu, like a checkmark, a dot, or make the collection name bold.

**Comment by smayer97** [comment]
Please keep open...

**Comment by smayer97** [comment]
Please keep open...

**Comment by jvillalobos** [comment]
I don't think this is worth fixing. It's a valid issue, but collections on AMO aren't meant to be a power feature for people managing so many collections that they can't keep track which add-ons are in which collections.
