### ISSUE TITLE
JavaScript Debugger (Venkman)

### ISSUE THREAD

**Issue by bajacyn** [mozilla/addons-frontend#8419]
### Describe the problem and steps to reproduce it:
The problem is it is not in the addons section.

### What happened?
Was going through the list of Firefox addons for  Linux.
### What did you expect to happen.
Expected to find in the addons section.
### Anything else we should know?

Alternative to  search:  Firefox addons that are for Linux.  In the more information area relating to the app/addon stated could find  it in the addons in Firefox.

**Comment by jvillalobos** [comment]
Firefox ships with a JS Debugger. Venkman was discontinued a long time ago.

Additionally, you can filter search on AMO by platform, though most extensions are cross-platform now.

**Comment by shayneoneill** [comment]
Is there any writeups or clues on what became of that thing. Venkman was an absolutely epic piece of software, was it another casualty of the Quantum thing, or was it dead before that?
