### ISSUE TITLE
Add exclusions for prefix middleware.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#842]
AMO has exclusions for the prefix middleware, so we're probably going to need something similar in addons-frontend.

**Comment by muffinresearch** [comment]
Going to leave this one until we need it.

**Comment by muffinresearch** [comment]
> Going to leave this one until we need it.

We're going to need this to support the redirection based on 404s it should match the exclusions list in addons-server.

**Comment by muffinresearch** [comment]
List is here: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L262

On looking at this there's also a list of locale exclusions, we'll need to investigate if that's needed too: https://github.com/mozilla/addons-server/blob/master/src/olympia/lib/settings_base.py#L262

**Comment by vcarciu** [comment]
Can you please add some STRs for this bug or add _qa:not needed_ label?

**Comment by tofumatt** [comment]
On the new AMO frontend visit a URL like `/en-us/about` and `/developers/` to make sure you're served a page from the desktop site and don't get a 404 error.
