### ISSUE TITLE
“More…” drop down menu doesn't close on first mouse click 

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#8424]
### STR:
1. Access AMO homepage: https://addons.allizom.org/en-US/firefox/.
2. Mouse hover the “More…” menu button from the page header.
3. Click on the More button.

### Expected result:
Drop down menu should disappear after the mouse click.

### Actual result:
The drop down menu is open.

### Notes:
Same thing happens for the User profile drop down menu, located at the top right side from the page header, after logging in.
Reproduced in amo-dev, amo-stage and amo-prod with Fx68, Win10x64.

![2019-07-16_14h50_17](https://user-images.githubusercontent.com/15685441/62276346-83027000-b44c-11e9-8470-c8d2c19b6102.gif)

**Comment by rbrishabh** [comment]
I believe this is only happening one time after each page reload, and then it seems to be working fine.

Anyways, can I take this up as my first contribution on addons-frontend? :)

**Comment by stringtheory1234** [comment]
is anyone working on this issue ?

**Comment by stringtheory1234** [comment]
![Screenshot from 2020-01-09 03-44-29](https://user-images.githubusercontent.com/43103463/72020764-80753380-3292-11ea-8b0e-420e27de355a.png)
I guess this is how it's supposed to be as it's mentioned in the tests. Please let me know if i am wrong. 
https://github.com/mozilla/addons-frontend/pull/9067

**Comment by willdurand** [comment]
@stringtheory1234 hey, no one is working on this particular issue but I'd encourage you to take a look at our [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by bobsilverberg** [comment]
I'm a bit confused by this. If one looks at the tests for this component, one can see that [we have tests in place](https://github.com/mozilla/addons-frontend/blob/master/tests/unit/ui/components/TestDropdownMenu.js#L119-L150) that verify that a single click *will not* close the menu, and that a second click *is required* to close the menu. So at some point that was the expected behaviour.

It looks like that code was put in place to address #3452. When I take the patch from #9100 and apply it, it still seems like #3452 is not reproducible, so maybe we don't need this special behaviour anymore?  I am still loath to just remove behaviour that was obviously intentionally added.

@jvillalobos and/or @muffinresearch do you have any opinions about this?

**Comment by jvillalobos** [comment]
I'm okay with accepting the patch as long as #3452 isn't regressed.

**Comment by willdurand** [comment]
> It looks like that code was put in place to address #3452. When I take the patch from #9100 and apply it, it still seems like #3452 is not reproducible, so maybe we don't need this special behaviour anymore? I am still loath to just remove behaviour that was obviously intentionally added.
> 
> @jvillalobos and/or @muffinresearch do you have any opinions about this?

Make sure to test on a real Android device (ideally on both FF for Android and Preview) too.

**Comment by muffinresearch** [comment]
> I'm okay with accepting the patch as long as #3452 isn't regressed.

This sounds good to me.

**Comment by bobsilverberg** [comment]
> > It looks like that code was put in place to address #3452. When I take the patch from #9100 and apply it, it still seems like #3452 is not reproducible, so maybe we don't need this special behaviour anymore? I am still loath to just remove behaviour that was obviously intentionally added.
> > @jvillalobos and/or @muffinresearch do you have any opinions about this?
> 
> Make sure to test on a real Android device (ideally on both FF for Android and Preview) too.

This sounds like an excellent idea. I had to dig around to find an Android device, as I don't use one regularly. Is there a process for testing a local build on a physical device, or does it involve pushing the change to dev first?

**Comment by willdurand** [comment]
It'd be better to test the changes before it lands in -dev. There is no specific process in place, the device should have access to the local server. It can be done by configuring the machine's firewall or by using a tool like `ngrok`.

**Comment by ioanarusiczki** [comment]
@willdurand 
Verified on AMO dev with FF72(Win10). 

![clicks on More1](https://user-images.githubusercontent.com/33448286/73174249-f7724f00-410f-11ea-98e9-7d48208e8fd6.gif)
