### ISSUE TITLE
Selecting “Add-on Type”-“Theme” won't highlight “Themes” from the menu

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#8425]
### STR:
1. Access AMO homepage: https://addons.allizom.org/en-US/firefox/.
2. Type any searchable term in the search field, located at the right side in the page header and press enter.
3. Once on the Search results page, select “Theme” from the “Add-on Type” drop down list, from the “Filter results”, located on the left side of the page.
4. Observe the “Themes” menu button from the page header.

### Expected result:
“Themes” menu button should be highlighted. 

### Actual result:
“Themes” menu button is not highlighted.

### Notes:
Reproduced in amo-dev, amo-stage, amo-prod with Fx68, Win10x64.

![GIF](https://user-images.githubusercontent.com/15685441/62276894-b0035280-b44d-11e9-98f1-a4b51ba8556b.gif)

**Comment by Shubhamchinda** [comment]
Can I take it?

**Comment by Shubhamchinda** [comment]
Hey, in the `amo/components/SectionLinks` the viewContext has value "statetheme". So I think `ADDON_TYPE_THEME` should be replaced with `ADDON_TYPE_STATIC_THEME`. 

[Line](https://github.com/mozilla/addons-frontend/blob/26005ae51e6f7af359436179d8a44331ec9e9066/src/amo/components/SectionLinks/index.js#L97)
 
**After replacing with `ADDON_TYPE_STATIC_THEME` :**
![Screenshot (153)](https://user-images.githubusercontent.com/21038543/62315222-8a5c6480-b4b2-11e9-8667-1b0b8e084165.png)

Please let me know if I'm going right or if there some other dependency to it, How about I go for it?

Thanks!

**Comment by willdurand** [comment]
@Shubhamchinda awesome finding, you're correct!

**Comment by Shubhamchinda** [comment]
> @Shubhamchinda awesome finding, you're correct!

Thanks man!

**Comment by willdurand** [comment]
thanks @Shubhamchinda

**Comment by Shubhamchinda** [comment]
> thanks @Shubhamchinda

Your welcome @willdurand :)

**Comment by madalincm** [comment]
Verified in amo-dev.

![2019-08-06_09h26_47](https://user-images.githubusercontent.com/15685441/62516056-a9e5eb00-b82c-11e9-93f9-16d0725c383b.gif)
