### ISSUE TITLE
Small glitch in the primary hero at ~470px when the screen is in RTL mode 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8426]
Follow up for #8247 

### Describe the problem and steps to reproduce it:
1. Open AMO -dev homepage
2. Switch to an RTL locale - i..e. `/ar/`
3. Resize your browser until it's ~470px wide
4. Observe the bottom section of the primary hero

### What happened?
The hero decoration is (very) slightly falling outside the main frame

### What did you expect to happen?
No layout issues

### Anything else we should know?
- reproduced on -dev with Fx68 and latest Nightly

![image](https://user-images.githubusercontent.com/31961530/62278584-0c1ba600-b451-11e9-8753-64716e6761a8.png)

**Comment by kumar303** [comment]
I found a workaround but I also filed a Firefox bug for it: https://bugzilla.mozilla.org/show_bug.cgi?id=1570710

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/62537549-62c21f00-b859-11e9-8b03-b76e6050f81b.png)
