### ISSUE TITLE
Dismiss button should stay active after the red warning for more chars than allowed

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8433]
Followup for https://github.com/mozilla/addons-frontend/issues/8385

STR:
1. Send an abuse report from the detail page of an add-on/theme with more than 10000 chars
2. Observe the Dismiss button after the red message is displayed

Expected result:
It can be clicked and the `Report this add-on for abuse` button is available again. 

Actual result:
`Dismiss` is not active. 

Note:
`Report this add-on for abuse` is available again after a page refresh. 
Reproducible on FF68(Win10). 

![dismiss button](https://user-images.githubusercontent.com/33448286/62375408-e96bb900-b546-11e9-94e4-e4321c3fb0e8.gif)

**Comment by rbrishabh** [comment]
Hey! Can I take this up? =)

**Comment by rbrishabh** [comment]
I think I partially fixed this issue.

The ```dismiss``` button is now available when the error message comes.

![image](https://user-images.githubusercontent.com/22501334/62466671-7d3fbe00-b7af-11e9-92f5-caafa7b8767d.png)

On clicking it - ```Report this add-on for abuse``` is available again.

![image](https://user-images.githubusercontent.com/22501334/62466702-96e10580-b7af-11e9-8f7d-912aafa416d4.png)

I am now running into two problems:

1) The dismiss button is always available, so the user **can** click on it when the report form is being submitted. To tackle this issue, I did this -- 

- I added this code [here](https://github.com/mozilla/addons-frontend/blob/5118e409f4ca77e3858b1e3493fca66c1cd38992/src/ui/components/DismissibleTextForm/index.js#L128)

```
if (!this.props.isSubmitting) {
      this.setState({ text: '' });
      this.localState.clear();
    }
```

- And I made sure, that [here](https://github.com/mozilla/addons-frontend/blob/5118e409f4ca77e3858b1e3493fca66c1cd38992/src/amo/components/ReportAbuseButton/index.js#L42), the code always returns when there is _no_ error and ```loading``` is true.

```
 if (loading && this.props.errorHandler.capturedError === null) {
      log.debug(
        "Ignoring dismiss click because we're submitting the abuse report",
      );
      return;
    }
```

After this, even if the ```Dismiss``` button is clicked, and the report abuse form is still submitting, there will be no change and the dismiss button won't work.

2) The second problem is -
 After clicking, ```dismiss``` button and then again clicking ```Report this add-on for abuse``` button, the earlier text is still present and the submit button is still ```Sending abuse report``` and it is still disabled.

I think to tackle this, all that needs to be done is --

Over inside of [here](https://github.com/mozilla/addons-frontend/blob/5118e409f4ca77e3858b1e3493fca66c1cd38992/src/amo/components/ReportAbuseButton/index.js#L42), after writing this code, 

```
 if (loading && this.props.errorHandler.capturedError === null) {
      log.debug(
        "Ignoring dismiss click because we're submitting the abuse report",
      );
      return;
    }
```

we can add another ```if```along these lines: 
```
if (this.props.errorHandler.capturedError !== null && this.props.errorHandler.capturedError.messages[0] === 'Please ensure this field has no more than 10000 characters.') {
      // remove error and enable editing again by rendering ```DismissibleTextForm``` again
   }
```

I think this will solve this issue.
I need help with rendering DismissibleTextForm again.

Is this headed in the correct direction?
Let me know how I can solve this @willdurand 

Thanks!
