### ISSUE TITLE
Integration-test job is failing

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#8439]
See https://github.com/mozilla/fxa/issues/2074

**Comment by kumar303** [comment]
@jrbenny35 FxA is back up but I still see consistent failures, like: https://circleci.com/gh/mozilla/addons-frontend/16512?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Any ideas? I see a lot of index out of range errors which I'm not sure about.

**Comment by jrbenny35** [comment]
Yeah looks like some service isn't starting. I can't really see what's causing it, I'll have to test it locally.

**Comment by kumar303** [comment]
I upped the priority here since the consistent failures will make it difficult to notice other failures.

**Comment by jrbenny35** [comment]
This is now the reason: https://github.com/mozilla/addons-server/issues/12064

**Comment by muffinresearch** [comment]
Closing as https://github.com/mozilla/addons-server/issues/12064 is now fixed.
