### ISSUE TITLE
https://addons.mozilla.org/en-GB/firefox/addon/selenium-builder/ is not available

### ISSUE THREAD

**Issue by bbgool** [mozilla/addons-frontend#8444]
### Describe the problem and steps to reproduce it:

1. go to https://seleniumbuilder.github.io/se-builder/
2. Click "Install'

### What happened?
https://addons.mozilla.org/en-GB/firefox/addon/selenium-builder/ is not available

![Firefox_Seleniumbuilder](https://user-images.githubusercontent.com/32668362/62521192-fe02c680-b850-11e9-907a-c9153e258c4b.png)

### What did you expect to happen?
https://addons.mozilla.org/en-GB/firefox/addon/selenium-builder/ is available

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
