### ISSUE TITLE
400 received when clicking the Manage Firefox Accounts from Edit my profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8446]
STR:

1. Login with an account on AMO dev and go to Edit my profile
2. Click the Manage Firefox Accounts 
3. Observe the page 

Expected result:
Fxa page loads

Actual result: 
The page is blank. A 400 is received in the Network. 

Notes:
It is reproducible on AMO dev. - FF68(Win10)
It is not reproducible on AMO stage.- FF68(Win10)

![400](https://user-images.githubusercontent.com/33448286/62536006-83887580-b855-11e9-94f3-b7af9e438e85.gif)

**Comment by kumar303** [comment]
Thanks. I filed an FxA issue to track it: https://github.com/mozilla/fxa/issues/2092

**Comment by kumar303** [comment]
A comment on https://github.com/mozilla/fxa/issues/2092 says this is resolved but they're still looking into what caused it.

**Comment by willdurand** [comment]
@ioanarusiczki has this been fixed since we changed the FxA instance on -dev?

**Comment by AlexandraMoga** [comment]
@willdurand I've been using that link to navigate to the FxA account page for a while now, so I believe this was fixed long ago.
