### ISSUE TITLE
CircleCI pushes the Docker image twice

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8449]
### Describe the problem and steps to reproduce it:

Push a git tag

### What happened?

CircleCI pushes (deploys) the Docker image twice

### What did you expect to happen?

It should only push the image once because that's confusing. It makes tracking down and resolving push errors more difficult.

### Anything else we should know?

This determines which job to run on a tag: https://github.com/mozilla/addons-frontend/blob/master/.circleci/config.yml#L157-L168

This behavior is new, as of this week, possibly caused by https://github.com/mozilla/addons-frontend/pull/8416 (but I'm not sure).

**Comment by bqbn** [comment]
If we go to https://circleci.com/gh/mozilla/addons-frontend/16515, it has a message on that page that says,

> There was an issue while running this container and it was rerun. The most recent run is shown.

So if it was because CircleCI itself had to run the job twice for some reason, it may not be our issue. A new tag will tell for sure. 

For now, we can probably lower the priority and see if it happens again.

**Comment by jrbenny35** [comment]
Don't see how this is related to #8416 as that PR didn't change the frequency of the releases to Docker. Why circleci chooses to rerun something is a mystery as that text doesn't really provide any clues.

**Comment by kumar303** [comment]
> So if it was because CircleCI itself had to run the job twice for some reason, it may not be our issue.

Hmm. It happened twice in a row which was weird.

> Don't see how this is related to #8416 as that PR didn't change the frequency of the releases to Docker.

@jrbenny35 ok, thanks for looking into it. I guess we'll just wait to see if it happens again.
