### ISSUE TITLE
Unpublished add-on detail page causes high cpu load

### ISSUE THREAD

**Issue by mastef** [mozilla/addons-frontend#8450]
### Describe the problem and steps to reproduce it:
I just uploaded a new add-on, and left Firefox open on the pre-published add-on website. The next morning my Mac was still running on full fans, and this page seems to be the issue.

Checking the console output the page is trying to constantly fetch the latest user review, which fails. This happens every second. It fails with 403 forbidden, and then the request starts again and again.

`Failed to fetchLatestUserReview for addonId "2593012", userId "15187535": Error: Error calling: /api/v4/ratings/rating/ (status: 403)`

### What happened?
CPU load goes through the roof.
Page constantly tries to download reviews.

### What did you expect to happen?
CPU load should stay normal.
Page should stop downloading reviews after a few tries.

### Anything else we should know?

Link ( while it's not a public listing yet - you may need to have elevated access rights to see this - or try with any other unpublished add-on as developer ) : https://addons.mozilla.org/en-US/firefox/addon/tab-manager-plus-for-firefox/

![image](https://user-images.githubusercontent.com/762297/62517541-cba59900-b851-11e9-973a-a4e5b182f9cb.png)

**Comment by kumar303** [comment]
Thanks for the bug report, @mastef 

This is really bad. Even though https://github.com/mozilla/addons-frontend/issues/5891 will make this problem go away, it might come back later if there is another error. No page should ever get caught in an infinite loop due to an error 😞

**Comment by AlexandraMoga** [comment]
I've verified this on stage and there is no 403 loop in the console anymore when looking at the detail page of an unpublic add-on.

@kumar303 There used to be only one 403 before: `Failed to fetchLatestUserReview for addonId "1002944", userId "11685651": Error: Error calling: /api/v4/ratings/rating/ (status: 403)` 
Now, there is a second 403: - `Failed to fetch grouped ratings for add-on ID 1002944: Error: Error calling: /api/v4/ratings/rating/ (status: 403)` . This error is reflected in the UI through a red banner displayed in the Rate your experience section:

Add-on example: https://addons.allizom.org/en-US/firefox/addon/unapproved/
![image](https://user-images.githubusercontent.com/31961530/62956670-07190800-bdfc-11e9-98d8-bd3b966f0b52.png)

This is similar to the issue described in #5891 though
