### ISSUE TITLE
Integration Test job on CircleCI should run more often.

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#8458]
Right now the ```integration-test``` job on circleci runs about every 3 hours or so, between a set time period. We could have them run on each PR, but limit the suite to just a few tests. We could run the full suite on a merge to master instead as that wouldn't be blocking and wouldn't take so long.

Thoughts?

**Comment by willdurand** [comment]
How long does it take to run the full test suite?

**Comment by jrbenny35** [comment]
> How long does it take to run the full test suite?

About 30 min

**Comment by willdurand** [comment]
ah, ok. That's not fast.

I see that those tests are not in this repo, so I am not sure whether we should really be running them at all. If they break (for legit reasons, like a new feature or something), frontend devs cannot really fix them as they would have to patch another repo.

**Comment by kumar303** [comment]
I don't think we should run them on every PR as that would add extra waiting time. Running them on master for *every* commit sounds fine to me. I would rather move away from the 3 hour interval because it's too hard to glance at the master commits and determine if there is an intermittent or real failure happening.

**Comment by jrbenny35** [comment]
> I see that those tests are not in this repo, so I am not sure whether we should really be running them at all. If they break (for legit reasons, like a new feature or something), frontend devs cannot really fix them as they would have to patch another repo.

Well they could be moved completly here. That wouldn't be hard at all

**Comment by kumar303** [comment]
I guess they run in both places (`-server` and `-frontend`) so that the first breaking commit gets exposed?

**Comment by willdurand** [comment]
> Well they could be moved completly here. That wouldn't be hard at all

Didn't we discuss this in Whistler? What was the outcome? A third repo, no?

**Comment by kumar303** [comment]
I don't remember exactly what we discussed. A third repo sounds good but I don't know if github lets us do what you can do in Jenkins: an upstream commit triggers a downstream builder in a separate repo. Maybe we can do it with [actions](https://github.com/features/actions)!

**Comment by willdurand** [comment]
Yeah, maybe.

Maybe we should take ownership of these "ui tests" by moving all tests against addons-frontend here. I believe it's more likely that a frontend change breaks these tests.

**Comment by jrbenny35** [comment]
> Maybe we should take ownership of these "ui tests" by moving all tests against addons-frontend here. I believe it's more likely that a frontend change breaks these tests.

I like this idea

**Comment by kumar303** [comment]
> I believe it's more likely that a frontend change breaks these tests.

I agree. It makes more sense for them to live in `addons-frontend`.
