### ISSUE TITLE
Landing position not maintained for "See more enhanced privacy extensions" link in Android Homepage

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#8461]
### STR: 
1. Open AMO homepage on an Android device: https://addons.allizom.org/en-US/android/.
2. Scroll down to the "Enhanced privacy extensions" section and click on "See more enhanced privacy extensions" link.
3. After the page loads, press the Back phone button.
4. Observe the page.

### Actual result:
The landing page is placed at the page footer.

### Expected result:
The landing position on the page should be at the "Enhanced privacy extensions" section.

### Notes:
Reproduced also when clicking other links, which are not the same in all environments:
- for Amo-dev the bug is reproduced when clicking the "See more recommended themes" and "See more recommended password managers" links. 
- for Amo-stage the bug is reproduced when clicking the "See more popular extensions", "See more recommended themes" and "See more recommended password managers" links.
- for Amo-prod the bug is reproduced when clicking the "See more recommended password managers" link.

Reproduced with all AMO servers on small screen devices (Android 8.0.0).

![videotogif_2019 08 09_13 46 21 (1)](https://user-images.githubusercontent.com/15685441/62780166-b59c1080-babd-11e9-92bf-91f2fe5ca382.gif)

**Comment by bobsilverberg** [comment]
I took a look at this behaviour on dev, and at first I thought that any link below a certain point on the home page would yield this behaviour, but then noticed that the link for "See more enhanced privacy extensions" yields this behaviour, but the link for "See more popular extensions" does not, despite being lower on the page than the link for "See more enhanced privacy extensions". So this is quite odd. I'll do a bit more digging and see if I can come up with a theory for what is causing this behaviour.

@madalincm Do you have any idea if this is a new regression, or if this is possibly something that has been around for some time?

**Comment by bobsilverberg** [comment]
An additional piece of information: This also reproduces the same way for the desktop site, i.e., https://addons.allizom.org/en-US/firefox/. So it seems to have nothing to do with the fact that it's the "android" site, but rather with the small screen size.

**Comment by madalincm** [comment]
@bobsilverberg I don't think it's a new regression, since on Amo-prod the bug is reproduced for the "See more enhanced privacy extensions" and "See more recommended password managers" links by using the steps mentioned in the bug report.
