### ISSUE TITLE
https://addons.mozilla.org/en-US/firefox/addon/open-link-in-new-tab/ URL does not open correct website

### ISSUE THREAD

**Issue by CatherineHP** [mozilla/addons-frontend#8467]
### Describe the problem and steps to reproduce it:
missing website

I searched on Duck Duck Go for "open search links in new tab in firefox".  On the right side was a box with this in it: " Firefox can't do this natively, however there are various plugins.

I recommend https://addons.mozilla.org/en-US/firefox/addon/open-link-in-new-tab/ because it has filters, so you can enable it only on specific domains

--JohnKiller"

When I tried to open that web URL I was taken to a Mozilla page that said that link may no longer be valid and that I should report the issue to Mozilla.  That is what I am doing.
### What happened?
The website was not there.

### What did you expect to happen?
I expected to find the website.

### Anything else we should know?
I am trying to get Firefox to force my search engine to open links in new tabs.  I'm getting very frustrated having to remember to right-click, then try to line up my pointer to the right menu choice.  (I have trouble with small hand movements.)

https://addons.mozilla.org/en-US/firefox/addon/open-link-in-new-tab/

**Comment by wagnerand** [comment]
Please contact the author of the website you found the link on to update it.
