### ISSUE TITLE
open search engine links in new tab

### ISSUE THREAD

**Issue by CatherineHP** [mozilla/addons-frontend#8468]
### Describe the problem and steps to reproduce it:
There seems to be no way to get my search links to open in a new tab other than right-clicking and choosing "open link in new tab".  That is harder for me to do because I often have trouble lining up my mouse pointer with something on a menu.

I read online that I could go to about:config and change browser.search.openintab to TRUE, but that didn't work.  Although it says "TRUE", the links still open in the same tab.

Also I found two different add-ons that were supposed to fix this problem, but neither seems to be used anymore.

### What happened?
Search engine links from Duck Duck Go and Google won't open in new tab unless I use two clicks - right-click, then menu selection, which is harder for me to do.

Changing about:config did not work.

### What did you expect to happen?
I expected to be able to open links from search pages in a new tab with just one click.

Also, I expected that changing the about:config file would change how the search page links open.
### Anything else we should know?
People who have difficulty lining up mouse pointers with menu items need to have an option for opening web search links in a new tab with just one click.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform.
