### ISSUE TITLE
firefox/addon/16/

### ISSUE THREAD

**Issue by abs-plus** [mozilla/addons-frontend#8475]
step 1:               https://de.wikipedia.org/wiki/ChatZilla
step 2:  Offizielle Addon-Webseite von ChatZilla  https://addons.mozilla.org/de/firefox/addon/16/  
step 3:  led me to github

but, I exepted to find :
Offizielle Addon-Webseite von ChatZilla

little bit confusions, but hopefully comprehensible

greetings  Michelle

**Comment by abs-plus** [comment]
I guess that Wikipedia failed cause they didn`t interrupt the invalid link.

**Comment by muffinresearch** [comment]
We are unable to provide support for individual add-ons.

This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services.  

In this case the add-on is no-longer available as legacy add-ons are no longer supported or made available from AMO.
