### ISSUE TITLE
Themes Categories not available on Amo-dev and stage

### ISSUE THREAD

**Issue by madalincm** [mozilla/addons-frontend#8480]
### STR:
1. Access Amo Homepage: https://addons.allizom.org/en-US/firefox/.
2. Click on the "Themes" menu button.
3. Observe the page.

### Expected result:
Categories should be displayed.

### Actual result:
"No categories found." text is displayed where the categories should be displayed.

### Notes:
Reproduced on Amo-dev and Amo-stage with Fx68, Win10x64 and Android 8.0.0.

![2019-08-14_11h16_18](https://user-images.githubusercontent.com/15685441/63005439-345dc880-be85-11e9-89fb-44376627624d.gif)

**Comment by willdurand** [comment]
Updating the mapping in https://github.com/mozilla/addons-frontend/blob/45f3b09b38b7214345d37e9a9099654a5c1a56d0/src/core/constants.js#L84-L87 might solve this problem. Now that the persona server code has been removed, it'd be nice to also remove the persona code in this project too. There are issues filed for that.

**Comment by madalincm** [comment]
Verified in Amo-dev with Fx68, Win10x64 and Android 8.0.0.

![2019-08-14_16h28_26](https://user-images.githubusercontent.com/15685441/63024898-caf3af00-beb0-11e9-8fe4-c279698fc658.gif)

**Comment by ioanarusiczki** [comment]
Verified on stage with FF68 (Win10 & Android 8.0) 

![category on stage](https://user-images.githubusercontent.com/33448286/63032394-68091480-bebe-11e9-9d6b-744fe6d41a82.gif)
