### ISSUE TITLE
Define fonts for amo app

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#849]
We need to create the CSS for the core fonts used in the amo app.

We can work out weights and font-sizing later but it would be good to use variables as much as possible to aim for a consistent approach to the way we use fonts through-out the app.

**Comment by pwalm** [comment]
![screen shot 2016-07-28 at 11 08 31 am](https://cloud.githubusercontent.com/assets/6797635/17223951/aefe475c-54b3-11e6-8d95-316c4e2b1230.png)

Typeface lives [here](https://github.com/mozilla/addons-frontend/tree/master/assets/fonts).

(These values are @3x for Android xxhdi)

/* H1: */
font-family: Tofino-Bold;
font-size: 96px;
color: #000000;
line-height: 96px;

/* H2: */
font-family: Tofino-Bold;
font-size: 36px;
color: #000000;

/* H3: */
font-family: Tofino-Medium;
font-size: 42px;
color: #000000;
line-height: 56px;

/* body: */
font-family: Tofino-Book;
font-size: 42px;
color: #000000;
line-height: 56px;

/* link: */
font-family: Tofino-Medium;
font-size: 42px;
color: #0996F8;

/* caption: */
font-family: Tofino-Regular;
font-size: 30px;
color: #000000;
line-height: 34px;

/* date & time: */
font-family: Tofino-Book;
font-size: 42px;
color: #B1B1B1;

**Comment by muffinresearch** [comment]
As per our email, I'm going to start with Fira, and then as we need to we can update.

**Comment by muffinresearch** [comment]
This has been implmented and we're sticking with Fira due to licensing.
