### ISSUE TITLE
Make gradients for Primary Hero Shelf dynamic

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8499]
This is a follow-up to #8305 

That patch adds a dynamic Primary Hero Shelf (PHS), but only one gradient is currently available (and hardcoded). The code and styles for the PHS need to be updated to use the color names returned by the `hero` API to set the background gradient. 

This implementation will likely involve creating a new style for each possible combination of `start` and `stop` gradient which will define the colors for the gradient, as well as the button background color and possibly some other properties. Once those styles are defined, the code for `HeroRecommendation` can be updated to assign a `className` by concatenating the `start` and `stop` colors received from the API.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The primary hero changes colour based on the configuration added in Discovery admin:

![2019-09-25_10-17-37](https://user-images.githubusercontent.com/31961530/65578563-acd4a080-df7e-11e9-844f-1052a58a2f46.gif)
