### ISSUE TITLE
The /hero/ endpoint is called twice when loading AMO homepage

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8512]
Follow up for #8478 

### Describe the problem and steps to reproduce it:

1. Open AMO homepage on -dev
2. Navigate to Extensions
3. Refresh the page
4. Open your web console
5. Navigate back to the homepage by clicking on Explore or the home button
6. Check the calls made for the `/api/v4/hero/` endpoint

### What happened?
There are two calls made for the `/hero/` endpoint
### What did you expect to happen?
There is only one call made for the `/hero/` endpoint

**Notes**
- one of the requests is cached in the below screenshot:

![image](https://user-images.githubusercontent.com/31961530/63833702-59b9fe80-c97c-11e9-9491-1c74d3d9829b.png)

**Comment by willdurand** [comment]
marking this one as dup of #8572 even if this one was filed before.
