### ISSUE TITLE
withExperiment should set a permanent cookie

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8515]
Currently, the cookie set by [`withExperiment`](https://github.com/mozilla/addons-frontend/blob/master/src/core/withExperiment.js#L80) is a [`session` cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Session_cookies), which means that it is (generally) cleared when the browser closes.

For the purposes of keeping a user's experience consistent, and also being able to assume that the behaviour for a user over time is based on a consistent experience, it seems that we should be setting a [`permanent` cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Permanent_cookies) instead. We probably shouldn't create a cookie that never expires, but ideally the cookie would remain for the duration of the experiment. Perhaps a default of 1 month would be good, but perhaps we should allow this to be overridden by the experiment in question (via the call to `withExperiment`).

@willdurand / @kumar303 / @felixlawrence what are your thoughts?

For QA:

Please confirm that the cookie that is set (you can use the `installButtonWarningExperiment` cookie) has an expiry date that is 30 days (2592000 seconds) in the future.

Note that this patch should also address the issue reported about the A/B test using session cookies as discussed at https://github.com/mozilla/addons-frontend/issues/8137#issuecomment-525801292.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on dev with FF68 (Win10). 
- on a new or older profile a cookie is set from today until 2Oct with date and time. 

![Expires in a month](https://user-images.githubusercontent.com/33448286/64117825-d85cd480-cd9e-11e9-8134-3d1989e0da44.png)

I'll do some re-check on the cookie tomorrow to be sure it's everything alright.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Looks good to me. 
Verified on dev - FF68(Win10).
