### ISSUE TITLE
Create a function to append different query params to internal and external URLs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8516]
This supports #8249 

For #8249, we need a way to differentiate between internal and external URLs, and to append a different set of query params to each. It seems like a function that accepts a URL string, an `internalQueryParams` object and an `externalQueryParams` object, and then returns the appropriate URL would be a good helper for this use case, so that's what this issue is about.

**Comment by bobsilverberg** [comment]
Instead of creating this generic utility function, I'm going to put this code into the Secondary Hero component.

**Comment by AlexandraMoga** [comment]
@bobsilverberg are there some verification steps available or is this a qa:not needed issue?
Thanks.

**Comment by bobsilverberg** [comment]
Sorry, @AlexandraMoga, this actually never shipped, and I forgot to remove the milestone. I have done that now.
