### ISSUE TITLE
Primary hero description is not correctly aligned 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8521]
Follow up for #8305 

### Describe the problem and steps to reproduce it:
1. Open AMO homepage on -dev
2. Notice the description of the presented primary hero

### What happened?
The description is set between `blockquote` tags and does not match the alignment proposed in the mock-ups 
### What did you expect to happen?
The description should be aligned to the left, as presented in the mock-ups 

### Anything else we should know?
@bobsilverberg I see that the frontend uses the exact properties returned by the `/hero/` api for `description`:
```
{
 "description": "<blockquote>Custom description.</blockquote>"
}
```
Can the `blockquote` tag be avoided in the frontend directly or does this require an api change?

![image](https://user-images.githubusercontent.com/31961530/64022061-0a233080-cb3e-11e9-9b91-a1ffaf628d24.png)

**Comment by bobsilverberg** [comment]
@eviljeff I recall we discussed this at one point (about the `description` being wrapped in `<blockquote>`, but I don't recall what we decided to do about it. Did we come up with a solution?

**Comment by eviljeff** [comment]
> I recall we discussed this at one point (about the description being wrapped in <blockquote>), but I don't recall what we decided to do about it. Did we come up with a solution?

It was something I brought up in https://github.com/mozilla/addons-server/issues/12134#issuecomment-522045961 but that issue got wontfixed so it's not resolved.  It'd just be a server-side change to serve the plain text description instead (`description_text` from the discovery addon response).

**Comment by bobsilverberg** [comment]
> It was something I brought up in [mozilla/addons-server#12134 (comment)](https://github.com/mozilla/addons-server/issues/12134#issuecomment-522045961) but that issue got wontfixed so it's not resolved.  It'd just be a server-side change to serve the plain text description instead (`description_text` from the discovery addon response).

Thanks @eviljeff. I guess we need a new issue in addons-server for this. I'll open one.

**Comment by bobsilverberg** [comment]
I opened https://github.com/mozilla/addons-server/issues/12235 to discuss this further, as I think that just using `description_text` might not give us what we want/need.

**Comment by AlexandraMoga** [comment]
This has been fixed by https://github.com/mozilla/addons-server/pull/12254

![image](https://user-images.githubusercontent.com/31961530/64167753-b4f36180-ce52-11e9-9400-87e946c549f9.png)
