### ISSUE TITLE
Enable the non-recommended install warning A/B test on stage/prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8525]
Everything required for the warning and the A/B test has landed on dev, so all that is needed to enable the warning and test on stage and prod is a config change to flip the flag.

@felixlawrence Based on what you've been able to see on dev, are there any further changes required before we ship this on prod? Since yesterday's push, you should be able to see the events on prod that happen when a user clicks on an install button for both a recommended and non-recommended add-on.

In terms of timing, do we want to ship this to stage on Tuesday of next week via the tag, and then to prod on Thursday, or would we prefer to ship it only to stage next week, and the to prod with the push on Sept. 12?

@muffinresearch / @jvillalobos / anyone else with an opinion?

For QA:

Everything that is currently active for the warning and the test should be enabled on stage after today's tag, and then enabled on prod after Thursday's push.

**Comment by jvillalobos** [comment]
No strong opinion either way from me.

**Comment by felixlawrence** [comment]
> Based on what you've been able to see on dev, are there any further changes required before we ship this on prod?

I had a look at dev and everything seems to be ready to go, and everything I hoped would be possible does indeed seem to be possible. No blockers from me.

**Comment by bobsilverberg** [comment]
Based on the above responses, I'm going to enable everything on stage with today's tag, and enable everything on prod with Thursday's push.

**Comment by muffinresearch** [comment]
> Based on the above responses, I'm going to enable everything on stage with today's tag, and enable everything on prod with Thursday's push.

Sounds good to me.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
My only concern would be what I filed here https://github.com/mozilla/addons-frontend/issues/8546
I don't see other issues so I also think it's good to go 👍 

Verified on AMO stage with FF68 (Win10&Android 8.0)
