### ISSUE TITLE
Link to unlisted primary hero homepage should open in a new tab

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8533]
Follow up for #8305 

### Describe the problem and steps to reproduce it:

1. Open AMO homepage on -dev
2. Refresh the page until you receive an unlisted add-on in the primary hero section (see example from the below screencast)
3. Click on Get started 

### What happened?
The unlisted add-on homepage opens in the same window although the user is leaving the amo domain

### What did you expect to happen?
Since the add-on homepage is an external link, we might want to open it in a different tab

### Anything else we should know?
I'm not sure if on AMO we have strict rules about external links. For example, external links in the 'More information' card from an add-on details page are opened in the same window, while the sumo links for the 'Recommended' badge and 'Learn more about permissions' are opened in a different tab.  
I'm opening this issue for further discussion.

![2019-09-02_10-14-03](https://user-images.githubusercontent.com/31961530/64097745-be56ce00-cd6d-11e9-8722-479b892b01f0.gif)

**Comment by jvillalobos** [comment]
I don't know if we need to figure out a global policy for external links, but in this case it's a promotional link, so I think it makes sense to open it in a new tab when it isn't an internal link.

**Comment by bobsilverberg** [comment]
I'm going to reuse the code we now (or rather will) have that determines if a link is an internal or external link, to decide whether to open the link in a new tab or not.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev

![2019-09-11_12-24-34](https://user-images.githubusercontent.com/31961530/64685941-84ce4300-d490-11e9-8fff-ccf703c5a021.gif)
