### ISSUE TITLE
Set required parameters for URLs in the primary hero

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8537]
Follow up for #8305 

### Describe the problem and steps to reproduce it:

As part of the requirement for the new homepage primary hero:

>All internal URLs in this module should have these params appended: src=homepage-primary-hero. External URLs should have these: utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-primary-hero.

**Comment by bobsilverberg** [comment]
@AlexandraMoga Thanks for filing this. In order to minimize the size of the patches for this, I think it would be better to have two separate issues, one for the links and one for the GA event. Could you please open a separate issue for the latter?

**Comment by AlexandraMoga** [comment]
@bobsilverberg done in #8538 and updated this issue to reflect what is being implemented

**Comment by AlexandraMoga** [comment]
@bobsilverberg the `src=homepage-primary-hero` parameter has been appended to the call to action button, as demonstrated below:

![2019-09-09_17-36-02](https://user-images.githubusercontent.com/31961530/64587189-28432900-d3a7-11e9-9d23-3b9a04d99cc7.gif)

Apart from the call to action URL, we are also linking to the developer profile page, but here there are no parameters sent. 
I'm not sure how relevant it is to add these parameters to the author link, although the request does say that `All internal URLs in this module should have these params appended`.

**Comment by bobsilverberg** [comment]
Ah, good catch. I'm also not sure if we need to add that to the developer profile page links, so let's ask Jorge.

@jvillalobos:

Because we are reusing a component `AddonTitle` in order to display the name of the add-on with the authors, the author names become links to the authors' profile pages. Some questions:

1. Is it okay for these to be links in the Primary Hero shelf?
2. If they remain links, should we also be appending `src=homepage-primary-hero` to these links (to the author profile pages)?

**Comment by jvillalobos** [comment]
I'd rather we stick to the original design and not show author names. Would those names also appear in the case of unlisted add-ons?

**Comment by AlexandraMoga** [comment]
The api response for unlisted primary heroes (as noted in https://github.com/mozilla/addons-server/issues/11882#issuecomment-518191063) doesn't contain the `author` object, so, normally, the fronted doesn't expose it either. 

I can file a follow up issue to also exclude author names for listed primary heroes if this what we have in the requirements.

@bobsilverberg can you work around this in the frontend directly or do you require an api change for that?

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga and sorry for the late reply @jvillalobos. I added the author names based on a mock, but I can certainly remove them. In answer to your question, no, currently the author names only appear for listed add-ons, not unlisted add-ons, but I will remove them.

@AlexandraMoga this will not require any API changes, but if you could file an issue to exclude the author names from the Primary Hero shelf that would be appreciated.

**Comment by AlexandraMoga** [comment]
@bobsilverberg filed #8604 as a followup.
