### ISSUE TITLE
The non-recommended install warning looks unblanced on wide screens

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8540]
The install warning for non-recommended add-ons (https://github.com/mozilla/addons-frontend/issues/8525) is placed in an awkward position for wide screens. The edges of banner  do not line up with any other part of the design which makes the page look unbalanced.

Example:

<img width="887" alt="Screenshot 2019-09-03 10 40 26" src="https://user-images.githubusercontent.com/55398/64191506-40aec300-ce3e-11e9-8d85-a9f4963168f4.png">

**Comment by AlexandraMoga** [comment]
@kumar303 @bobsilverberg looks like this patch will enter with this week's push, yet the milestone was set for next week.

In any case, the layout does look better with the new position, my only objection being the blank space left on the right side of the InstallWarning. I've read the conclusion from  https://github.com/mozilla/addons-frontend/pull/8541#issuecomment-527548027 and it looks like, for now at least, we'll stick to this layout.

[details page]
![image](https://user-images.githubusercontent.com/31961530/64347728-19522480-cffd-11e9-93ae-8c9f36339500.png)

[versions page]
![image](https://user-images.githubusercontent.com/31961530/64347824-253de680-cffd-11e9-9def-f1cd41cf6318.png)

**Comment by bobsilverberg** [comment]
Oops, thanks @AlexandraMoga. I updated the milestone.
