### ISSUE TITLE
Add complete Flow coverage to all code

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8542]
Add Flow coverage to all code.

Most code has Flow coverage but some key components such as [pages/Addon](https://github.com/mozilla/addons-frontend/blob/591ffc138dc1372ba72b4aa3c50fe1dadebf0b92/src/amo/pages/Addon/index.js) do not. This makes it hard to add new features with accuracy, speed, and confidence.

**Comment by ruchikabgosain** [comment]
hey! @kumar303 is this issue available? let me know if I can take this up, and what changes would I need to make :)

**Comment by kumar303** [comment]
Hi @ruchikabgosain. Thanks again for your interest. We mark issues with [`contrib: welcome`](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) when we think they are ideal for contributors. Did you find anything in there? Even if someone commented on one already, if it's an old comment then they probably aren't working on it.

This issue about Flow coverage is very involved and will probably require many patches which would need to be reviewed separately (with corresponding issues). I don't think it would be a good one to work on right now since it could span several weeks.

**Comment by ruchikabgosain** [comment]
Okay! thankyou @kumar303 for this :) would find something that suits me.

**Comment by bobsilverberg** [comment]
Note: After reviewing the team's Q4 goals with @muffinresearch, we added this as a secondary goal. If time and resources permit this could be something that could be addressed in Q4.
