### ISSUE TITLE
The layout in guidelines is not correct when the screen is resized for a long unbroken addon name

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8554]
This is an edge case - I don't think it could be applicable on prod but FYI:
1. I edited the name of an addon aprox 560 px in length
2. Resized screen

Expected result:
No layout issues.

Actual result:
The recommended badge and install button looks cut.

Notes:
The issue is not reproducible with a 560 px in length addon name which contains spaces.

  
![layout cut](https://user-images.githubusercontent.com/33448286/64354357-f7aa6a80-d007-11e9-854e-5bae1bfc5f65.gif)

**Comment by willdurand** [comment]
@ioanarusiczki what happens if you resize and then reload the page? Also, does it happen with Chrome? I remember issues about FF not keeping up with the resize.

**Comment by willdurand** [comment]
@ioanarusiczki ^

**Comment by bobsilverberg** [comment]
@willdurand I think the guide pages might be deprecated now. With the new Heroes, we no longer provide a link to them. I suppose they can still be reached via a direct URL, but I don't think it makes sense to spend any time fixing issues with them. I guess changing this to a P4 makes sense, but at some point we may just want to close it as a WONTFIX.
