### ISSUE TITLE
Update link from InstallWarning

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8557]
Currently, the warning that appears for non-recommended add-ons contains a link which points to https://support.mozilla.org/en-US/kb/recommended-extensions-program. While this seems like the correct page, @diox suggested that we should point to the anchor for "What are the risks of installing non-Recommended extensions?", i.e., https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_what-are-the-risks-of-installing-non-recommended-extensions.

This sounds like a good idea to me.

@jvillalobos @devaneymoz What do you think?

<img width="889" alt="Screenshot 2019-09-06 08 07 47" src="https://user-images.githubusercontent.com/142755/64426761-72619d00-d07d-11e9-9cba-46fe369a8b76.png">

**Comment by jvillalobos** [comment]
Sounds okay to me, but @caitmuenster is more familiar with SUMO, so it should be her call.

**Comment by caitmuenster** [comment]
So sorry for the delayed response on this! Yes, we are good to link to https://support.mozilla.org/kb/recommended-extensions-program#w_what-are-the-risks-of-installing-non-recommended-extensions; some copy edits are needed to that section but Jorge and I can handle those

**Comment by AlexandraMoga** [comment]
Verified fixec on -dev:

![2019-09-10_16-44-49](https://user-images.githubusercontent.com/31961530/64619725-3adf5180-d3eb-11e9-86a8-bbac2383217e.gif)
