### ISSUE TITLE
Set required parameters for URLs in the secondary hero component

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8558]
This is a follow-up to #8249 

#8249 implements the Secondary Hero shelf, but does not add any parameters to the URLs on any of the cta links. According to #8249:

> All internal URLs in this module should have these params appended: `src=homepage-secondary-hero`. External URLs should have these: `utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-secondary-hero`.

This issue is about adding those params.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

- internal URLs
`https://addons-dev.allizom.org/en-US/firefox/collections/4757633/privacy-matters/?src=homepage-secondary-hero`
- external URLs
`https://www.charactercountonline.com/?utm_content=homepage-secondary-hero&utm_medium=referral&utm_source=addons-dev.allizom.org`
