### ISSUE TITLE
Send a tracking event when a Secondary Hero cta is clicked

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8559]
This is a follow-up to #8249 

#8249 implements the Secondary Hero shelf, but does send the tracking event. According to #8249:

> An event should be logged on GA when the CTA is clicked, recording a click on the shelf and the destination.

This issue is about adding that event.

**Comment by willdurand** [comment]
@bobsilverberg could you please add labels/projects to this issue? Thanks?!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

- example event fro internal URLs
`sendEvent {"hitType":"event","eventCategory":"AMO Secondary Hero Clicks","eventAction":"https://addons-dev.allizom.org/en-US/firefox/?src=homepage-secondary-hero"}`
- example event for external URLs*
`sendEvent {"hitType":"event","eventCategory":"AMO Secondary Hero Clicks","eventAction":"https://www.privacyend.com/firefox-privacy-add-ons/?utm_content=homepage-secondary-hero&utm_medium=referral&utm_source=addons-dev.allizom.org"}`

*see #8656 for the missing `outgoing` in external URLs
