### ISSUE TITLE
Design Toolkit

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#857]
I put a Sketch file on here called "AMO Mobile - Toolkit" that has spacing values and elements spec'd out. These might change over time, but are a good starting point. All px values are @3x.

**Comment by pwalm** [comment]
[File is here](https://github.com/mozilla/addons-frontend/blob/d175d8ab1b3db8235c78a5c4d3b1a9cb09bf7f4a/assets/sketch%20files/AMO%20Mobile%20-%20Toolkit.sketch)!

**Comment by muffinresearch** [comment]
Going to close this one since there's nothing to do here, and everyone is using the file.
