### ISSUE TITLE
Home hero data is fetched twice

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8572]
### Describe the problem and steps to reproduce it:

* Clear cache
* Go to any non-home page such as https://addons-dev.allizom.org/en-US/firefox/addon/adblock-plus/?src=featured
* Open the Network panel and clear all network requests
* Click on the Firefox icon to navigate home
* Watch the Network panel

### What happened?

The hero data is fetched twice:

<img width="501" alt="Screenshot 2019-09-10 15 11 48" src="https://user-images.githubusercontent.com/55398/64646956-afab8f00-d3dd-11e9-8310-42a04e0a70ac.png">

### What did you expect to happen?

The data should only be fetched once since it may impact API performance and page load time (especially as this is the home page).

### Anything else we should know?

It looks like `pages/Home` is dispatching `FETCH_HOME_DATA` twice:

<details>
<summary>Console log</summary>

<img width="528" alt="Screenshot 2019-09-10 15 12 09" src="https://user-images.githubusercontent.com/55398/64647148-15981680-d3de-11e9-8bf6-809d9646524b.png">

</details>

We typically prevent this by storing an `isLoading` flag on the first saga dispatch. This can then be used to prevent dispatching the loader. Example:

https://github.com/mozilla/addons-frontend/blob/28cd4cbebe6b0672f7af9b5ab0a1636ed81ee543/src/amo/reducers/reviews.js#L587-L598

and:

https://github.com/mozilla/addons-frontend/blob/fa9c74e2501bd4a2e4bf6841c4b52b66a757dc9c/src/amo/pages/AddonReviewList/index.js#L136-L146

**Comment by AlexandraMoga** [comment]
@kumar303 there was already an issue filed for this in https://github.com/mozilla/addons-frontend/issues/8512, so I guess this one is a duplicate.

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga. I *thought* this was already filed, but it seems I failed to triage it. Maybe we can keep this one open as it contains some technical details and mark #8512 as a duplicate?

@kumar303 I did look into this when I saw #8512 filed and was confused about why this was happening. It's true that we can, and probably should, deal with this via an `isLoading` flag, but do you have any idea *why* it's happening? I cannot see anything in the code that suggests that `FETCH_HOME_DATA` would be dispatched twice. Does it have to do with SSR and the two-step render?

**Comment by kumar303** [comment]
@AlexandraMoga sorry! I missed the issue you filed.

@bobsilverberg you can see it happen every time using the STR up above (which would happen client side or server side). You can look at the console log screenshot I posted to see exactly why. There are several subsequent dispatches after the first fetch which trigger updates in `pages/Home` and that in turn triggers the second fetch. This is a typical problem in data loading side effects that we always need to think about, unfortunately.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

`/hero/` data is fetched only once
![image](https://user-images.githubusercontent.com/31961530/65527392-3cd10680-defb-11e9-8c65-a12ecaa7454c.png)
