### ISSUE TITLE
Link to FireXPath from MDN Web XPath Doc is bad

### ISSUE THREAD

**Issue by Ashpabb** [mozilla/addons-frontend#8573]
### Describe the problem and steps to reproduce it:

Was  reading MDN XPath web doc (https://developer.mozilla.org/en-US/docs/Web/XPath) and clicked through to FireXPath which is link on the right column.

### What happened?

Got to add-on 404 esque page: https://addons.mozilla.org/en-US/firefox/addon/11900/

### What did you expect to happen?

Wanted to find the add-on :D

**Comment by willdurand** [comment]
cc @caitmuenster
