### ISSUE TITLE
Okta Plugin Not Available

### ISSUE THREAD

**Issue by brianwheatley** [mozilla/addons-frontend#8574]
### Anything else we should know?

When attempting to install the OKTA plugin to Firefox, I receive the page in the screenshot below. Did this plugin get removed?
![2019-09-11 10_32_17-Window](https://user-images.githubusercontent.com/19884329/64706441-74fa3300-d47f-11e9-8d03-ee78bc6ef821.png)

**Comment by brianwheatley** [comment]
Why did this get closed without a response?

**Comment by brianwheatley** [comment]
Ok. Just a heads up, this is where the link takes you when you click on "file an issue" on that Firefox page that is attached.

**Comment by wagnerand** [comment]
Please also see the text above the link on that page.
