### ISSUE TITLE
Disable `StrictMode` by default and log a message when it is enabled

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8586]
We use `StrictMode` to help us debug potential issues in development. It has been added in https://github.com/mozilla/addons-frontend/issues/6189.

In https://github.com/mozilla/addons-frontend/issues/6694, we introduce a config flag to enable/disable it but it is turned on by default in our config. `StrictMode` won't be executed in production because it respects `NODE_ENV=production`.

**Proposal 1:** I suggest we disable it by default and only enable it for local dev.

`StrictMode` triggers redux actions twice and it is confusing (sometimes). This behavior has been described in https://github.com/mozilla/addons-frontend/issues/6424.

**Proposal 2:** we should log a message when `StrictMode` is enabled and link to the issue https://github.com/mozilla/addons-frontend/issues/6424 so that we remember why we see redux actions dispatched twice.

**Comment by kumar303** [comment]
@willdurand why can't we just flat-out disable it by default? I don't see why it's helpful to enable this in local development by default as https://github.com/mozilla/addons-frontend/pull/8696 does.

**Comment by willdurand** [comment]
> I don't see why it's helpful to enable this in local development by default as #8696 does.

Mostly because it is designed and thus useful for development. If we disable it by default in local dev, we can remove it entirely because no one will ever enable it to double-check its output. Keeping it enabled by default for local dev will allow us to review the warnings, some of them being used to ease upgrades.

**Comment by kumar303** [comment]
> If we disable it by default in local dev, we can remove it entirely because no one will ever enable it to double-check its output. 

I say we disable it by default but keep the code and document how to turn it on. 

The double dispatch behavior is too confusing for daily development. I agree that it's useful for reviewing warnings but that is mostly useful when upgrading libraries and I think it needs to be done *consciously* so that one is aware of the side effects. The console warning will be easy to miss.
