### ISSUE TITLE
Allow some HTML tags in `SiteNotices`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8599]
In https://github.com/mozilla/addons-frontend/issues/8595, we added a `SiteNotices` component that is used to display `site_notice`.

We should allow some HTML tags like links (at least) so that admins can update the `site_notice` Config object (zadmin) with links to support URLs, SUMO, GitHub, etc.

**Comment by jvillalobos** [comment]
I think all we would have a use for is `b`, `strong`, `i`, `em`, and `a`.

**Comment by willdurand** [comment]
> I think all we would have a use for is `b`, `strong`, `i`, `em`, and `a`.

@kumar303 based on ^ I believe we could use (to keep some consistency): https://github.com/mozilla/addons-frontend/blob/b3eff6926b8b2b94eb5b09cd489f464504439406/src/core/utils/index.js#L122-L138

**Comment by kumar303** [comment]
Yep, agreed

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me. 
I went in Zadmin to the `site_notice` key and tested the `b`, `strong`, `i`, `em`, and `a` html tags. 

Zadmin:

![Zadmin](https://user-images.githubusercontent.com/33448286/65159659-1b74a400-da3d-11e9-9109-7f80ba3b260a.png)

Result on frontend: 

![frontend](https://user-images.githubusercontent.com/33448286/65159727-347d5500-da3d-11e9-89fb-84ab2d2bf314.png)

Result on server:

![server](https://user-images.githubusercontent.com/33448286/65159756-40691700-da3d-11e9-9cbc-527d93398c07.png)
