### ISSUE TITLE
Update code that interacts with Google Analytics to use sendBeacon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8605]
The script that we use for interacting with Google Analytics (GA) has an [option](https://developers.google.com/analytics/devguides/collection/analyticsjs/sending-hits#specifying_different_transport_mechanisms) that allows us to specify we want it to use [`sendBeacon`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon) as its transport mechanism. 

Using `sendBeacon` will minimize the number of events that get lost due to a page unloading while we are waiting for the event to be sent.

This issue is about updating the code in `core/tracking.js` to use this new option.

**Comment by bobsilverberg** [comment]
I'm marking this as P1 as it would be nice to get it into this week's push in order to see how much, if any, it improves the numbers being collected by the Install Warning A/B test.

**Comment by willdurand** [comment]
@muffinresearch I think this would also allow us to remove the google domain in the CSP config, no?

**Comment by muffinresearch** [comment]
> @muffinresearch I think this would also allow us to remove the google domain in the CSP config, no?

You'll need to remove from `img-src` and add to `connect-src`

**Comment by muffinresearch** [comment]
From the extension workshop it will need `https://www.google-analytics.com/r/collect` and  `https://www.google-analytics.com/collect`. On that I just used `https://www.google-analytics.com` for simplicity.

**Comment by willdurand** [comment]
> From the extension workshop it will need `https://www.google-analytics.com/r/collect` and `https://www.google-analytics.com/collect`. On that I just used `https://www.google-analytics.com` for simplicity.

Wouldn't it be nice to restrict the paths as much as we can?

**Comment by muffinresearch** [comment]
> > From the extension workshop it will need `https://www.google-analytics.com/r/collect` and `https://www.google-analytics.com/collect`. On that I just used `https://www.google-analytics.com` for simplicity.
> 
> Wouldn't it be nice to restrict the paths as much as we can?

Certainly you could to limit things as much as possible, but this does mean if there are changes to send beacons to other paths it will be blocked.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified on dev and stage with FF69(Win10). 
The GA event is available as shown here https://user-images.githubusercontent.com/142755/65063652-af1a7780-d94c-11e9-997a-4bd7a22af068.png 

I should detail the things noticed while testing which did not seem alright to me :
- I see the  beacon GA event posted twice when I navigate from Homepage to Extension tab -> Extensions categories-> click on a detail page.  This happens too when I refresh the detail page of an extension. 

Navigation 

![beacon twice](https://user-images.githubusercontent.com/33448286/65150667-46ef9280-da2d-11e9-9e09-ebd224ea5fc4.gif)

Refreshing a page (3 times registered in the Network)

![beacon three time ](https://user-images.githubusercontent.com/33448286/65150908-b2396480-da2d-11e9-8d81-fb51ba8a9f17.gif)

- when I refresh a page (any page) I receive `blocked` statuses related to CSP in the network which on prod are not reproducible right now

![blocked status](https://user-images.githubusercontent.com/33448286/65151914-af3f7380-da2f-11e9-8839-ce99a576de80.gif)

-  I don't understand why this happens but except for the extensions  the rest of the pages on AMO (themes, lang packs, dictionaries or search tools are excluded, homepage, guidelines, collections ) will show the google analytics requests only after I refresh the page I landed on (AMO prod has the same behavior). 

![must refresh page](https://user-images.githubusercontent.com/33448286/65152747-380adf00-da31-11e9-9aba-4803895d109e.gif)

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> I verified on dev and stage with FF69(Win10).
> The GA event is available as shown here [user-images.githubusercontent.com/142755/65063652-af1a7780-d94c-11e9-997a-4bd7a22af068.png](https://user-images.githubusercontent.com/142755/65063652-af1a7780-d94c-11e9-997a-4bd7a22af068.png)
> 
> I should detail the things noticed while testing which did not seem alright to me :
> 
> * I see the  beacon GA event posted twice when I navigate from Homepage to Extension tab -> Extensions categories-> click on a detail page.  This happens too when I refresh the detail page of an extension.
> 

I think this is okay. An individual page will often send multiple beacons if it is sending multiple events, and/or setting dimensions. There's no reason to expect that only a single beacon will be sent. I checked an extension page on stage and saw 3 beacons sent, but when I look at the data sent for the beacon I can explain why those 3 are present.

> 
> * when I refresh a page (any page) I receive `blocked` statuses related to CSP in the network which on prod are not reproducible right now
>

These are odd. Are we sure that these were not present before this patch landed. I don't see any reason why my patch would have changes the CSP related to these (which are for `default-src` for the host `https://addons-amo-cdn.allizom.org`).
cc @muffinresearch 

> 
> * I don't understand why this happens but except for the extensions  the rest of the pages on AMO (themes, lang packs, dictionaries or search tools are excluded, homepage, guidelines, collections ) will show the google analytics requests only after I refresh the page I landed on (AMO prod has the same behavior).
> 

This is likely because these pages don't send any beacons on their own, but when you refresh them a bunch of site setup things happen and that generates beacons.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I don't see the UI being affected by this.  

Those 4 files with 0B which are blocked on dev/stage have de domain `https://addons-amo-cdn.allizom.org/` 
On prod the domain is `https://addons-amo.cdn.mozilla.net/`

Stage after page refresh

![AMO stage](https://user-images.githubusercontent.com/33448286/65226980-84f1c280-dad0-11e9-86c8-280f49c1c443.png)


Prod after page refresh

![AMO prod](https://user-images.githubusercontent.com/33448286/65226996-8b803a00-dad0-11e9-862f-e74ef4f7948b.png)

cc @muffinresearch

**Comment by muffinresearch** [comment]
@ioanarusiczki I raised a separate bug here to deal with those errors which should now be fixed: https://github.com/mozilla/addons-frontend/issues/8620

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
This issue is verified on dev and stage with FF69(Win10). 
Also https://github.com/mozilla/addons-frontend/issues/8620 was verified on dev.
