### ISSUE TITLE
HeroRecommendation story in our Storybook is broken

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8607]
The Storybook story for the `HeroRecommendation` is currently broken: https://mozilla.github.io/addons-frontend/?path=/story/herorecommendation--default

**Comment by willdurand** [comment]
cc @bobsilverberg

**Comment by kumar303** [comment]
Can the Flow types do anything differently to have caught something like this?

**Comment by willdurand** [comment]
> Can the Flow types do anything differently to have caught something like this?

@kumar303 I think that's because `createHeroShelves()` and `createPrimaryHeroShelf()` are not covered with Flow because they live in `tests/unit/helpers.js`.

**Comment by kumar303** [comment]
Sure but `shelfData` gets passed as a [prop from the story](https://github.com/mozilla/addons-frontend/blob/2b4295f8f0be86438f9e9325ca7c76e711a051d9/stories/amo/HeroRecommendation.js#L13) into the [component prop](https://github.com/mozilla/addons-frontend/blob/2b4295f8f0be86438f9e9325ca7c76e711a051d9/src/amo/components/HeroRecommendation/index.js#L23) so it seems like that would enforce the object shape. I haven't looked into it so maybe object shape is not the problem here. To whomever looks into this, I suggest first investigating why Flow wasn't raising a type error.

Unfortunately, Flow is our only defense against broken stories until we do something like [this](https://github.com/mozilla/addons-code-manager/issues/425) (but for `addons-frontend`).

**Comment by willdurand** [comment]
I don't think Flow is able to infer anything from the test package, so when it looks at [the shelf type](https://github.com/mozilla/addons-frontend/blob/51590af5ef01bbc66a961254f5063b35a0d3ae8d/src/amo/reducers/home.js#L62-L76) and at what the helper function returns, it cannot determine if it is compatible or not, no?

**Comment by bobsilverberg** [comment]
I think there was a suggestion at some point to add Flow coverage to `tests/unit/helpers.js`, but I think it would be a pretty big job, and considering that none of our tests have Flow coverage, of limited value.

I wonder if we should have functions that return data used by stories in a different file that *is* covered by Flow?

**Comment by kumar303** [comment]
I see. Maybe this (type safety in stories) is a good reason to move some data creation helpers into a Flow file.

**Comment by bobsilverberg** [comment]
> I see. Maybe this (type safety in stories) is a good reason to move some data creation helpers into a Flow file.

Yes, that's what I was suggesting, but then it makes it more complicated to figure out from whence a helper needs to be imported when writing tests. I believe we had helpers in multiple locations at one point in this project and made an effort to centralize them, so this would be a step in the opposite direction.

Do we feel the benefit of adding type safety to stories would outweigh the pain of having helpers in multiple locations?

**Comment by willdurand** [comment]
> Do we feel the benefit of adding type safety to stories would outweigh the pain of having helpers in multiple locations?

Could we re-expose these data creation helpers in the main `helpers.js` file?

**Comment by bobsilverberg** [comment]
> > Do we feel the benefit of adding type safety to stories would outweigh the pain of having helpers in multiple locations?
> 
> Could we re-expose these data creation helpers in the main `helpers.js` file?

I suppose we could.

**Comment by willdurand** [comment]
> I suppose we could.

That would be the best of both worlds but I phrased it as a question because we only need to keep the two files in sync and not start to use the new file in `tests/`.

**Comment by bobsilverberg** [comment]
> > I suppose we could.
> 
> That would be the best of both worlds but I phrased it as a question because we only need to keep the two files in sync and not start to use the new file in `tests/`.

Right. That *is* a good idea.

I am going to just fix the story for `HeroRecommendation` right now, as I have a number of higher priority issues to tackle, but I will open a follow-up to move any helpers we have that are used in stories into a separate file which is covered by Flow.
