### ISSUE TITLE
DotVPN Extension error for FireFox

### ISSUE THREAD

**Issue by MaverickHunter07** [mozilla/addons-frontend#8612]
### Describe the problem and steps to reproduce it:
Go to https://dotvpn.com/en/download/firefox/
Click on download for firefox.

### What happened?
Link doesn't work for DotVPN Firefox.
### What did you expect to happen?
It should have took me to the extension page for DotVPN.
### Anything else we should know?

https://dotvpn.com/en/download/firefox/
https://addons.mozilla.org/en-US/firefox/addon/dotvpn/
![Screenshot (60)](https://user-images.githubusercontent.com/49660722/65094875-d4c77100-d98c-11e9-8dec-79e17c8c2213.png)
![Screenshot (61)](https://user-images.githubusercontent.com/49660722/65094878-d85af800-d98c-11e9-8cae-aaa4d3b8fa8f.png)

**Comment by muffinresearch** [comment]
Unfortunately this add-on isn't available as a web extension for Firefox hence the 404. Your best course of action is to ask the developers of that add-on for support.

**Comment by MaverickHunter07** [comment]
Ok, will do!
