### ISSUE TITLE
Add Triqui (trs), update name for ca-valencia

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8613]
We're in the process of adding trs and ca-valencia to Firefox 71, we need trs added in order to show the language pack on the page.

The decode name is Nánj nï'ïn.

**For QA:** 

- please verify that the native valencia locale name has been updated (capitalized)
- if there is a langpack for `trs`, it should appear in the list

**Comment by AlexandraMoga** [comment]
- For the `ca-valencia` locale

[before fix]
![image](https://user-images.githubusercontent.com/31961530/65523349-d2b56300-def4-11e9-9ba6-a1eb04c462cd.png)

[after fix]
![image](https://user-images.githubusercontent.com/31961530/65523434-f2e52200-def4-11e9-8db8-8db8091800a7.png)

For the `trs` locale, I've submitted a new lang pack and added `trs` as target_locale in admin. We'll see if it's going to be listed on the language tools page tomorrow.

**Comment by AlexandraMoga** [comment]
The language tools page has an entry for Triqui (trs):

![image](https://user-images.githubusercontent.com/31961530/65582862-de516a00-df86-11e9-9e44-47e23102c883.png)
