### ISSUE TITLE
Markup in site notice causes issues in server render

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#8616]
If you go to https://addons-dev.allizom.org you'll notice the site banner flashes up larger and then reduces in height when the JS kicks in.

Server rendered markup screenshot (with JS disabled):

<img width="749" alt="Add-ons_for_Firefox__en-US_" src="https://user-images.githubusercontent.com/1514/65148094-6bd90b00-da17-11e9-864d-0ec785587a10.png">

SiteNotice passes a div to Notice:

https://github.com/mozilla/addons-frontend/blob/0fadd956d4e9eb98d716aefeb6904e4becf2f346/src/core/components/SiteNotices/index.js#L36-L39

Whereas Notice wraps children with a `p`

https://github.com/mozilla/addons-frontend/blob/0fadd956d4e9eb98d716aefeb6904e4becf2f346/src/ui/components/Notice/index.js#L135

This results in a `div` inside a `p` which is not valid. Somehow the server side render results in even weirder markup as seen in the screenshot above.

To fix this the site notice could pass a `span` instead.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on dev and stage with FF69(Win10).  
- `<div>` is replaced by `<span>`
- I did not notice a visual glitch on SiteNotices.

![span](https://user-images.githubusercontent.com/33448286/65616820-60ac4f00-dfc4-11e9-8593-65d5560776f4.png)
