### ISSUE TITLE
All the integration tests run on Circle CI are broken

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8618]
All the integration tests run on Circle CI are broken after https://github.com/mozilla/addons-frontend/pull/8569.

It could be because there is no data for the hero shelves in the addons-server docker env, but I am not sure.

**Comment by willdurand** [comment]
cc @jrbenny35

**Comment by jrbenny35** [comment]
I'll take a look. Seems the small test suite we have on deploy jobs is also failing with some kinda 500 error.

**Comment by jrbenny35** [comment]
@willdurand @kumar303 what data is needed from server side for the new shelf?

**Comment by willdurand** [comment]
> @willdurand @kumar303 what data is needed from server side for the new shelf?

@bobsilverberg ^

**Comment by bobsilverberg** [comment]
> @willdurand @kumar303 what data is needed from server side for the new shelf?

The results of calling the `/hero/` endpoint: https://addons-server.readthedocs.io/en/latest/topics/api/hero.html#get--api-v4-hero-

**Comment by jrbenny35** [comment]
@bobsilverberg what would be a good headline? ```Showing 500 page for error: Invariant Violation: The headline property is required```

**Comment by bobsilverberg** [comment]
> @bobsilverberg what would be a good headline? `Showing 500 page for error: Invariant Violation: The headline property is required`

As per https://addons-server.readthedocs.io/en/latest/topics/api/hero.html#secondary-hero-shelf, it can be any string. Realistically I'd make it a few words.

**Comment by jrbenny35** [comment]
Updated the tests config but now running into an issue with pytest-xdist: https://github.com/mozilla/addons-server/pull/12502

**Comment by eviljeff** [comment]
How does a pytest plugin for addons-server tests affect ui tests for addons-frontend?  Or is the issue not related this repo?

**Comment by jrbenny35** [comment]
The tests on frontend pull from this repo, so I have to update things here until they get moved.

**Comment by jrbenny35** [comment]
Looks like I had my github tabs mixed up. The frontend tests pull from server as that is where all the tests currently live.

**Comment by jrbenny35** [comment]
Looks like these are passing now. Please re-open if that changes.
