### ISSUE TITLE
Deal with the jumpiness when navigating to the home page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8619]
This is a follow-up to #8601. 

Here is what it looks like when navigating to the home page from a non home page:

![Sep-18-2019 13-58-32](https://user-images.githubusercontent.com/142755/65173383-a002fa80-da1c-11e9-9474-7446bab85dc7.gif)

Note that this is exacerbated by #8601, but was already happening even before that landed if a user landed on the site at any page that was not the home page and then subsequently navigated to the home page.

It was suggested that we could provide a skeleton with a similar shape and size to the new hero shelves, which we would render while waiting for the data to load.

**Comment by AlexandraMoga** [comment]
Verified on dev with Fx69 on WIn10 and Android.

The homepage will show a skeleton where the content for the Primary and Secondary heroes will be populated :

[desktop]
![image](https://user-images.githubusercontent.com/31961530/66407350-ba197280-e9f5-11e9-8f43-a3543d542073.png)

[tablet]
![image](https://user-images.githubusercontent.com/31961530/66407544-0ebced80-e9f6-11e9-92c8-1f8c7f53bf18.png)

@bobsilverberg on mobile, there is no skeleton displayed for the Primary hero. It may be worth filing a follow up for that.

[mobile]
![image](https://user-images.githubusercontent.com/31961530/66407661-41ff7c80-e9f6-11e9-86b1-c8ea83ae27c2.png)
