### ISSUE TITLE
CSP errors related to preload/prefetch code 

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#8620]
There are some CSP errors observed on page loads on -dev and stage.

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://addons-amo-cdn.allizom.org/About-0a73a4250a85ff650ac8.css (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://addons-amo-cdn.allizom.org/About-36668d289d5b64cd4bf3.js (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://addons-amo-cdn.allizom.org/ReviewGuide-0a73a4250a85ff650ac8.css (“default-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at https://addons-amo-cdn.allizom.org/ReviewGuide-cc344a827941e24d9458.js (“default-src”).
```

These appear to be because of the following markup:

```html
<link as="style" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/About-0a73a4250a85ff650ac8.css" rel="preload"/>
<link as="style" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/About-0a73a4250a85ff650ac8.css" rel="prefetch"/>
<link as="script" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/About-36668d289d5b64cd4bf3.js" rel="preload"/>
<link as="script" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/About-36668d289d5b64cd4bf3.js" rel="prefetch"/>
<link as="style" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/ReviewGuide-0a73a4250a85ff650ac8.css" rel="preload"/>
<link as="style" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/ReviewGuide-0a73a4250a85ff650ac8.css" rel="prefetch"/>
<link as="script" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/ReviewGuide-cc344a827941e24d9458.js" rel="preload"/>
<link as="script" data-parent-chunk="amo" href="https://addons-amo-cdn.allizom.org/ReviewGuide-cc344a827941e24d9458.js" rel="prefetch"/>
```

You also see:

```
Content Security Policy: Couldn’t process unknown directive ‘prefetch-src’
```

`prefetch-src` is currently set to: `https://addons-stage-cdn.allizom.org`

FF doesn't support `prefetch-src` in CSP and falls back to `default-src`.

The fix here would be to fix `prefetch-src` (for chrome) to have the right values, and in addition default-src should be updated to match `prefetch-src` so that FF doesn't error any more.
 
If you don't see the errors check `network.prefetch-next` in `about:config` it should be set to `true`

**Comment by willdurand** [comment]
I am confused, the CDN variables don't seem correct in the config and there is a different `staticHost` variable in each config... That's why the values are all incorrect :/

**Comment by muffinresearch** [comment]
> I am confused, the CDN variables don't seem correct in the config and there is a different `staticHost` variable in each config... That's why the values are all incorrect :/

There's the CDN for addons-frontend statics (addons-amo-cdn.allizom.org), and the CDN for the django side of AMO (addons-stage-cdn.allizom.org). I think the two were potentially confused  when code-splitting was configured. 

Both are needed for images since API responses point to images from both locations, but for other statics (CSS, and script) only the frontend related CDN endpoints (`addons-amo...`) should be required.

Looks like prefetch is wrong across all the envs and either needs just the `addons-amo...` unless it will prefetch images as well.

**Comment by willdurand** [comment]
Oh, I see. I forgot about these two CDNs... I'll update the CSP config.

**Comment by muffinresearch** [comment]
We should probably also rename the vars to make this clearer for our future selves at the same time.

**Comment by willdurand** [comment]
This issue could explain https://github.com/mozilla/addons-frontend/issues/7144 and/or https://github.com/mozilla/addons-frontend/issues/7208

**Comment by ioanarusiczki** [comment]
@muffinresearch 
I checked on dev and I don't see the errors present in the Console 

![fixed on dev](https://user-images.githubusercontent.com/33448286/65245257-ec216e00-daf4-11e9-976a-483d7fd30b04.png)

The network.prefetch-next is set on true in about:config
