### ISSUE TITLE
Remove decorations (swoosh) from Primary Hero shelf

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8628]
As mentioned at https://github.com/mozilla/addons-frontend/issues/8623#issue-495695478, we are no longer going to include the decorations (e.g., the swoosh) in the Primary Hero shelf.

**Comment by AlexandraMoga** [comment]
Decoration is no longer present on the primary hero card:

![image](https://user-images.githubusercontent.com/31961530/65522615-b238d900-def3-11e9-8e65-5dd1a74bc884.png)
