### ISSUE TITLE
Different layout for primary hero based on primary image

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#8629]
This issue is a follow-up from the frontend review call.

If a photo isn't provided for the primary hero. It should change the layout to centred like so:

<img width="802" alt="Add-ons_Front_End_Review_-_Meeting_Notes_-_Google_Docs" src="https://user-images.githubusercontent.com/1514/65259209-39eda480-dafc-11e9-9520-972752f8719e.png">

If the admin requires an image, this will need to be relaxed on addons-server (cc @eviljeff)

Note: the lack of swoosh this is covered here: https://github.com/mozilla/addons-frontend/issues/8628

**Comment by eviljeff** [comment]
> If the admin requires an image, this will need to be relaxed on addons-server (cc @eviljeff)

It does, as per ["The checkbox shouldn't be toggled on if the other two properties haven't been set"](https://github.com/mozilla/addons-server/issues/11830)

**Comment by bobsilverberg** [comment]
> > If the admin requires an image, this will need to be relaxed on addons-server (cc @eviljeff)
> 
> It does, as per ["The checkbox shouldn't be toggled on if the other two properties haven't been set"](https://github.com/mozilla/addons-server/issues/11830)

Right, so we now need that to allow a `null` for featuredImage.

**Comment by muffinresearch** [comment]
@eviljeff thanks for confirming, I've filed https://github.com/mozilla/addons-server/issues/12403 to cover it.

**Comment by AlexandraMoga** [comment]
This will be verified once https://github.com/mozilla/addons-server/issues/12403#issuecomment-534903509 is fixed.

**Comment by AlexandraMoga** [comment]
Verified on dev

[large screen]
![image](https://user-images.githubusercontent.com/31961530/65974319-6b0f9280-e475-11e9-83f1-adc036a0803d.png)


[small screen]
![image](https://user-images.githubusercontent.com/31961530/65974328-6f3bb000-e475-11e9-9c41-d9fd3037e88f.png)

@bobsilverberg I see that the card  title in the mock contains 'Extension' after 'Recommended' . Do you know if this is a new requirement or something that was dropped in the meantime?

**Comment by bobsilverberg** [comment]
> Verified on dev
> 
> @bobsilverberg I see that the card title in the mock contains 'Extension' after 'Recommended' . Do you know if this is a new requirement or something that was dropped in the meantime?

The [PRD](https://docs.google.com/document/d/12aD_v5AOj1Y6VmT4xOuyNcrKfZxqhP8R_AOHroQVLV8/edit) and the [original issue](https://github.com/mozilla/addons-frontend/issues/8247) that implemented the Primary hero, both look like this (with just the word "RECOMMENDED"), so I think it's good.
