### ISSUE TITLE
The View Site links on Android have the same color as the rest of the text

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8632]
STR:
1. On an Android device the links  `<a href="https://youtu.be/w_lCi8U49mY">Click the following link </a>` or `  <a href="https://support.mozilla.org/en-US/kb/recommended-extensions-program">Visit SUMO </a>`

 could be more visible if they'd look like on Desktop 

Android 

![Links are black](https://user-images.githubusercontent.com/33448286/65315466-d5d0ec00-dba0-11e9-8ad7-dbe602985049.jpg)

Desktop 

![Links on desktop](https://user-images.githubusercontent.com/33448286/65315531-f13bf700-dba0-11e9-9fbf-6b91a193dc71.png)

This is reproducible on AMO dev with Android 8.0.0
Please note links without HTML format are interpreted as text.

**Comment by willdurand** [comment]
I don't know if it is our CSS or platform-specific.

**Comment by virgilt** [comment]
@ioanarusiczki @willdurand May I work on this issue?

**Comment by willdurand** [comment]
@virgilt go for it!

**Comment by virgilt** [comment]
@willdurand Thank you!

**Comment by virgilt** [comment]
@willdurand I'm having trouble with this one. Trying to emulate it in Android Studio on my Linux machine, by following the docs https://mozilla.github.io/geckoview/contributor/geckoview-quick-start

Can't get past Bootstrap Gecko. Are there any chats or place with more information?

**Comment by willdurand** [comment]
@virgilt hey, so there is no need for Android Studio. This is a web app with an Android version, but this version is still web-based.

You can get started by following these instructions:

- clone this repository
- run `yarn`
- run `yarn amo:dev`

Then you can browse: http://localhost:3000/en-US/android/

Note the "android" in the url. After that you should see the websitr with the yellow banner and the links that are not in blue.

**Comment by virgilt** [comment]
@willdurand finished the link color change.

**Comment by ioanarusiczki** [comment]
I see it reproducible on MacOS too.  - FF69

**Comment by willdurand** [comment]
ah, good catch @ioanarusiczki. So I think it was intended to have grey color on links, but maybe not by default, I am not sure.

**Comment by willdurand** [comment]
@bobsilverberg WDYT? It was introduced in https://github.com/mozilla/addons-frontend/pull/7364. I think we could remove the color on the links to keep the default style?

![Screen Shot 2019-09-23 at 15 28 03](https://user-images.githubusercontent.com/217628/65429634-cce95000-de16-11e9-9155-e66bd8b347fb.png)

```diff
diff --git a/src/ui/components/Notice/styles.scss b/src/ui/components/Notice/styles.scss
index 1052e371c..47545702c 100644
--- a/src/ui/components/Notice/styles.scss
+++ b/src/ui/components/Notice/styles.scss
@@ -131,13 +131,7 @@
   }
 
   background-color: $notice-background-color;
-
-  &,
-  :link,
-  :hover,
-  :active {
-    color: $notice-link-color;
-  }
+  color: $notice-link-color;
 }
 
 .Notice-error {
```

**Comment by bobsilverberg** [comment]
> @bobsilverberg WDYT? It was introduced in #7364. I think we could remove the color on the links to keep the default style?
> 

Sure, that seems fine. I don't think this colour difference was intentional.

**Comment by virgilt** [comment]
@willdurand Do you need me to do anything further?

**Comment by willdurand** [comment]
@virgilt would you like to update your patch with the one I provided above?

**Comment by virgilt** [comment]
@willdurand sure, no problem!

**Comment by virgilt** [comment]
@willdurand Just want to clarify that I should remove the previous code I had written correct?

**Comment by willdurand** [comment]
yep, correct. thanks!

**Comment by willdurand** [comment]
thanks for your work @virgilt

**Comment by ioanarusiczki** [comment]
@willdurand @virgilt Looks good to me! Verified on AMO dev - Android 8.0

![Links](https://user-images.githubusercontent.com/33448286/65766802-abe56f80-e134-11e9-9933-6ed91112a79b.jpg)
