### ISSUE TITLE
Error _promiseRejectionHandler in Sentry

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8633]
https://sentry.prod.mozaws.net/operations/addons-frontend-amo-prod/issues/6074703/

```
Error: 
  at _promiseRejectionHandler (/en-US/firefox/addon/ghostery/)
```

**For QA:** It is possible to reproduce by:

1. loading a product page for a webextension
2. clicking the install button
3. cancelling the install process

With these STRs, we get the error in the console.

Such issues are not new apparently (first seen in 2019.07.18) but we see more than before it seems. It could be because most people read the "warning" message and cancel the installation, or something else...

**Comment by willdurand** [comment]
> It could be because most people read the "warning" message and cancel the installation, or something else...

A lot of events appear around September 5, which is when we enabled the warning experiment in prod: https://addons-pm.herokuapp.com/milestones/2019.09.05/?dir=asc&sort=assignee

**Comment by bobsilverberg** [comment]
Do we know what exactly is causing this error, or do we only have an STR at this point?

**Comment by willdurand** [comment]
> Do we know what exactly is causing this error, or do we only have an STR at this point?

Yes, I added STRs in the original issue.

**Comment by willdurand** [comment]
I think the cause is the promise rejection when we call `install()` on the `mozAddonManager`.

**Comment by ioanarusiczki** [comment]
@willdurand 
I tried to install on dev/stage addons with FF69 (win10) and if I cancel the install I receive now a red warning on the detail page and an error in the Console which is not present right now on production. 

![Error on the page on dev](https://user-images.githubusercontent.com/33448286/65608376-cabdf780-dfb6-11e9-8312-776c8dfcbf59.gif)

There is an error in prod but it's only visible in the Console

![Error on prod](https://user-images.githubusercontent.com/33448286/65608418-dad5d700-dfb6-11e9-9bb9-cc9eeefb00f4.gif)

**Comment by willdurand** [comment]
>  I tried to install on dev/stage addons with FF69 (win10) and if I cancel the install I receive now a red warning on the detail page and an error in the Console which is not present right now on production.

Yeah, that is expected now.

**Comment by ioanarusiczki** [comment]
@willdurand Same when canceling a theme install. 
Some help to understand: Is this a temporary fix ?

**Comment by willdurand** [comment]
> Is this a temporary fix ?

heh, not sure 😅 

I think you can open a new issue if you think the message is not accurate enough, but we do receive an error because the installation has been aborted, but we do not know why we receive an error. I think we need to ask the FF team to see why it happens like this and what we can do about it.

**Comment by willdurand** [comment]
Seeing this screencast above multiple times, I am not sure whether we want to surface this generic error message.  It is generic because we receive an empty error from the `mozAddonManager`. I suppose that's because clicking the `cancel` button rejects the install promise somewhere in FF.

@kumar303 @muffinresearch @bobsilverberg I am not a fan of surfacing this error anymore. Should we log and swallow it instead? There might be other cases where the error is more specific, but who knows.. (and there is no easy way to know whether this error comes from the "cancel" button or not)

**Comment by ioanarusiczki** [comment]
@willdurand Personally I'd prefer no error on the detail page. It's not good UX. I think it scares the user even more.

**Comment by kumar303** [comment]
> @willdurand Personally I'd prefer no error on the detail page. It's not good UX. I think it scares the user even more.

I agree with this ^

@willdurand I also agree with your idea: log a warning about the error then ignore it. We already have `onInstallFailed` which is the time to show a message. Otherwise, we don't need to show a message.

**Comment by muffinresearch** [comment]
> > @willdurand Personally I'd prefer no error on the detail page. It's not good UX. I think it scares the user even more.
> 
> I agree with this ^
> 
> @willdurand I also agree with your idea: log a warning about the error then ignore it. We already have `onInstallFailed` which is the time to show a message. Otherwise, we don't need to show a message.

Yep, this sounds right to me too.

**Comment by willdurand** [comment]
Ok, cool. Working on a patch for that then.

**Comment by ioanarusiczki** [comment]
@willdurand Do you reopen this issue then?

**Comment by willdurand** [comment]
> @willdurand Do you reopen this issue then?

Could you please a separate issue?

**Comment by ioanarusiczki** [comment]
@willdurand This should be it https://github.com/mozilla/addons-frontend/issues/8668

**Comment by ioanarusiczki** [comment]
Fixed by https://github.com/mozilla/addons-frontend/issues/8575
