### ISSUE TITLE
Pass `NODE_CONFIG_ENV` to the discopane instances

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8634]
In https://github.com/mozilla/addons-frontend/issues/5898, we added the `NODE_CONFIG_ENV` but it is only set for AMO and not on the discopane instances. We should pass `NODE_CONFIG_ENV` to the discopane instances.

For the discopane app, we should have the following env variables:

- `NODE_ENV` always set to `'production'` (I believe it is already the case)
- `NODE_CONFIG_ENV` set to the deployed env (`dev`, `stage` or `prod`)

The puppet config should look like this, I think:

```yaml
NODE_ENV: 'production'
NODE_CONFIG_ENV: "%{::env}"
```

---

**For QA:** please verify that the web-based disco pane works as before.

**Comment by imskr** [comment]
I want to work on this issue!

**Comment by willdurand** [comment]
@imskr sorry, this issue is not opened to contributors.

**Comment by willdurand** [comment]
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by willdurand** [comment]
cc @bqbn

**Comment by willdurand** [comment]
Looks like it is fixed 🎉

**Comment by AlexandraMoga** [comment]
Verified the recommendations pane in Fx versions >=68 and the old disco_pane for Fx version prior 68 and there were no regressions spotted. 

Marking  the issue as verified fixed.
