### ISSUE TITLE
Ensure that helpers used in Storybook stories are covered by Flow

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8646]
In #8607 we discovered that a Storybook story was broken, but we had nothing in place to inform us of that other than stumbling across it. It was suggested that if we had full Flow coverage for stories that might have caught this issue. It is believed that the lack of complete Flow coverage is due to the fact that the helpers used by some stories are not themselves covered by Flow.

We have looked in the past into adding Flow coverage for all helpers, but it would be a large undertaking and considering that we do not have Flow coverage for tests in this repo, it would also be of questionable value.

However, having Flow coverage for just those helpers used in Storybook stories could be of value, and might have caught this error.

The proposal is to move any helpers which are used by stories out of `tests/unit/helpers.js` and into a separate file which is covered by Flow. Those helpers could also be imported and re-exported from `tests/unit/helpers.js` so that a) none of the existing tests would have to change, and b) test writers wouldn't have to worry about needing to figure out from whence to import a given helper.

**Comment by Jayashree-panda** [comment]
@bobsilverberg Can I take this issue?

**Comment by willdurand** [comment]
@Jayashree-panda no, please find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).
