### ISSUE TITLE
Log page views for client-side navigation

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#8647]
Since we're server-rendering a page and after then we're using client-side navigation we don't currently appear to be tracking all page views for client-side navigation.

This means that GA is only showing us landing page data, fixing this will require us to send a page view event on page navigation events.

See the docs for details: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

**Comment by willdurand** [comment]
A quick search revealed: https://github.com/react-ga/react-ga/wiki/React-Router-v4-withTracker

**Comment by willdurand** [comment]
We planned for that, it seems: https://github.com/mozilla/addons-frontend/blob/657e7e524871a67ea1b508044064d0bd796eda4b/src/core/tracking.js#L193-L202

**Comment by AlexandraMoga** [comment]
@willdurand there are two new GA events logged when navigating through amo pages: `setPage` - a relative URL of the page requested and `pageView` - with an empty `title` parameter:

**Comment by willdurand** [comment]
This looks good to me. I'll double check in the Google dashboard.
