### ISSUE TITLE
The code for internal URLs for the hero shelves is passing full URLs to the `to` param of `Link`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8651]
There's a bug I didn't discover until just now with the code that creates links for internal URLs for the hero shelves.

Internal URLs are defined as either a URL without a protocol (e.g., `/addon/slug/`) or a URL that points to the current host (e.g., `https://addons-dev.allizom.org/en-US/firefox/addon/soundfixer/` while on dev). The code that creates links for the hero shelves checks whether a URL is internal or not, and it if is internal then it creates a `Link` component with the `to` param set to the URL. 

The problem is that the latter type (e.g., one starting with `https://addons-dev.allizom.org`) is not a valid value for the `to` param. Our code for the `Link` component checks that any `to` param starts with `/`. So this is throwing an exception.

I took a look at the code for both our version of `Link` and `Link` in `react-router-dom, and it looks like we need to keep this check in place. That would mean that we'd have to strip off the protocol and host portions of a URL that is internal. I think that is the approach that we should take, but I'm open to other suggestions.

**Comment by willdurand** [comment]
@bobsilverberg in case you missed it, https://github.com/mozilla/addons-frontend/pull/8652#discussion_r327340829

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've looked at links present in the Primary and Secondary heroes, but please let me know if there is anything else that you'd like to be tested.
Thanks

**Comment by bobsilverberg** [comment]
> @bobsilverberg I've looked at links present in the Primary and Secondary heroes, but please let me know if there is anything else that you'd like to be tested.
> Thanks

That should be good enough, thanks @AlexandraMoga!
