### ISSUE TITLE
External links in the secondary hero shelf are not set up as outgoing URLs

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8656]
### Describe the problem and steps to reproduce it:

1. Load AMO homepage
2. In the Secondary hero module, locate an external URL set as a call to action

### What happened?
External links are set up like this:
![image](https://user-images.githubusercontent.com/31961530/65514682-751a1a00-dee6-11e9-950d-cedfc774157c.png)

### What did you expect to happen?
External links should start with  `https://outgoing.stage.mozaws.net/.....`

### Anything else we should know?
For the Primary hero, external links are set up as outgoing URLs

**Comment by bobsilverberg** [comment]
There is no special code in addons-frontend that is adding this "outgoing URL prefix" to the link in the Primary Hero. We are simply using the URL provided to us via the API in `external.homepage`. So I guess the server is doing something to prepend the URL? I didn't even realize this was a requirement. If it is then I guess we need to make sure the URLs for the secondary hero shelf are also prepended via the API, but this does raise an issue for internal URLs that start with `https://`.

@eviljeff Do you know about this requirement and is this something we need to do on the server?

**Comment by eviljeff** [comment]
In the other api endpoints, calls that need the outgoing wrapper around urls have to be sent with [?wrap_outgoing_links](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v4-addons-addon-(int-id|string-slug|string-guid)-) - though the hero apis don't support this currently.  To be consistent they should probably also support `?wrap_outgoing_links` but we could just always outgoing-ify them I suppose?

**Comment by bobsilverberg** [comment]
> In the other api endpoints, calls that need the outgoing wrapper around urls have to be sent with [?wrap_outgoing_links](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#get--api-v4-addons-addon-(int-id%7Cstring-slug%7Cstring-guid)-) - though the hero apis don't support this currently. 

This is odd, because according to this issue, the link for the Primary Hero shelf *is* getting the outgoing prefix but the links for the Secondary shelf are not. It's the same API call, but the links seem to be treated differently.

**Comment by eviljeff** [comment]
The primary shelf in part re-uses the `AddonSerializer` and _that_ supports `?wrap_outgoing_links`.  The secondary shelves don't reuse other serializers (because they're entirely different).  At least that's what I'm guessing - I'd need the API call to be sure.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/66040984-6d2f2b00-e521-11e9-96e9-af73055f3c82.png)
