### ISSUE TITLE
Update docs for how to develop locally in HTTPS

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8661]
These docs for running a local site in HTTPS are outdated: https://github.com/mozilla/addons-frontend/blob/master/docs/moz-addon-manager.md#developing-with-a-local-https-server-recommended

Specifically, the bundled `example.com` cert has expired.

This [PR](https://github.com/mozilla/addons-frontend/pull/8653) explains how to develop with HTTPS locally using [mkcert](https://github.com/FiloSottile/mkcert) so maybe that can be merged into the docs?

**Comment by willdurand** [comment]
We could potentially update the bundled certs only, if that is used elsewhere (ui tests I guess?)

**Comment by kumar303** [comment]
Yes, that would be nice. I think the UI tests have been failing on master ever since the certs expired. Sigh.

**Comment by willdurand** [comment]
> Yes, that would be nice. I think the UI tests have been failing on master ever since the certs expired. Sigh.

There is an issue for that https://github.com/mozilla/addons-frontend/issues/8618, for some reason, it does not seem to be related to the ssl certs, but I am not sure.
