### ISSUE TITLE
Unable to update Video Downloader Pro from the developer's website

### ISSUE THREAD

**Issue by oldyellor** [mozilla/addons-frontend#8664]
### Describe the problem and steps to reproduce it:
On the website: https://videodownloaderpro.net/#tutorial, there is a red button at the bottom of the page that should allow you to install the latest version 1.5.0 .
When you click on it, you get another page that says "Oops! We can’t find that page";
See the page at :https://addons.mozilla.org/en-US/firefox/addon/vdp-downloader/
Therefore, we cannot update the app from the developer's website.

**Comment by willdurand** [comment]
Sorry, there is nothing we can do. Please reach out to the videodownloaderpro folks to know why their extension is not listed anymore.
