### ISSUE TITLE
account profile edit page should support redirecting back (and new profiles)

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#8666]
Depends on https://github.com/mozilla/addons-server/issues/12479

From mozilla/addons-server#12417
> This would make the most sense to me:
>
> -   Send all users to the profile edit page.
> -   Have the button say Create My Profile instead of Update My Profile.
>  -  If there's a to in the URL, send them there after the profile is created.

addons-server can redirect to the account profile edit page with `?to=xxx/yyy` but addons-frontend will need to know what to do with the `to`, and change the button.  (In most cases, I suspect, the fxa registration will have started on frontend so the `to` will be a frontend page.  Though could also be developer hub)

**Comment by bobsilverberg** [comment]
@eviljeff You said that the frontend *would get* the `to` param *after* you make a change to deliver it. Is that change part of https://github.com/mozilla/addons-server/issues/12417, or is there another issue for it?

**Comment by eviljeff** [comment]
It was going to be added as part of the pr that fixes mozilla/addons-server#12417 (and probably mozilla/addons-server#10487 at the same time) though we can bring it forward in a separate patch if you prefer?

**Comment by bobsilverberg** [comment]
> It was going to be added as part of the pr that fixes [mozilla/addons-server#12417](https://github.com/mozilla/addons-server/issues/12417) (and probably [mozilla/addons-server#10487](https://github.com/mozilla/addons-server/issues/10487) at the same time) though we can bring it forward in a separate patch if you prefer?

If there's no rush to have this feature implemented, then I don't think you need to bring that forward in a separate patch.

**Comment by eviljeff** [comment]
okay, if it's a blocker then it needs to be done - and done first - or we've got a circular dependency because Jorge asked for these changes in mozilla/addons-server#2417 so that issue requires this issue.  

Filed mozilla/addons-server#12479

**Comment by bobsilverberg** [comment]
@eviljeff What can we expect this `to` query param to contain? Will it always be a fully qualified URL? Might it be a relative URL (e.g., `/addon/slug/`)? Will it always point to a page on AMO, or might it be to an external site?

**Comment by eviljeff** [comment]
It won't be an non-AMO property - we do a check to see if its safe. But if that passes it will pass along anything its sent and would otherwise redirect to if not for the new registration. 
I can have a look through the addons-server codebase for how it's called there. Addons-frontend originated logins i don't know about.

**Comment by bobsilverberg** [comment]
> It won't be an non-AMO property - we do a check to see if its safe. But if that passes it will pass along anything its sent and would otherwise redirect to if not for the new registration.
> I can have a look through the addons-server codebase for how it's called there. Addons-frontend originated logins i don't know about.

Thanks @eviljeff. The code I write will differ depending on whether we get a fully qualified URL, or just a path. It sounds like it will probably be just a path, but I'd want to be sure. So sometimes this originates from the server and sometimes from the frontend? 

Is the flow that a user tries to do something which requires login, they are redirected to FxA, which then redirects them to some server code, which then redirects back to frontend?

**Comment by eviljeff** [comment]
> So sometimes this originates from the server and sometimes from the frontend?

yeah.  Or code-manager, potentially, if it has support for it.

> Is the flow that a user tries to do something which requires login, they are redirected to FxA, which then redirects them to some server code, which then redirects back to frontend?

yes.  For frontend the only difference is it starts with an API call to get the url to call FxA (which then redirects to addons-server and redirects to frontend)

**Comment by bobsilverberg** [comment]
Thanks @eviljeff. I confirmed that the `to` parameter that the frontend sends to FxA is a relative path. Here's an example from my local instance: 

`http://localhost:3000/api/v4/accounts/login/start/?config=local&to=%2Fen-US%2Ffirefox%2Faddon%2Fublock-origin%2F`

**Comment by eviljeff** [comment]
addons-server side is landed now if you need to check the url is as expected.

**Comment by bobsilverberg** [comment]
Thanks @eviljeff, it all seems to be working perfectly!

**Comment by ioanarusiczki** [comment]
@eviljeff @bobsilverberg 

Dev Hub Registration:  
Edit profile page URL 
https://addons-dev.allizom.org/en-US/firefox/users/edit?to=%2Fen-US%2Fdevelopers%2F
Create Profile is confirmed
URL is https://addons-dev.allizom.org/en-US/developers/
but it lands on the homepage instead. 

So I filed https://github.com/mozilla/addons-server/issues/12629

And I'll continue testing this and get back with final results.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

"Create My Profile" - is greyed out until displayname is not edited.

After "Create my Profile" is clicked the user is redirected to the page the registration started, I tested for many pages. Here is the list:

- AMO homepage
- from a detail page 
- from a category
- from a search result (query) 
- from extensions tab 
- addon review page 
- dictionary and langpacks, search tools pages 
- about page
- log out edit page for an account and register from there to a new account

Verified on AMO dev with FF69(Win10).
