### ISSUE TITLE
Adjust the logic of `checkInternalURL` to remove code for relative URLs

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8673]
@muffinresearch pointed out that checking for a URL that starts with `/` isn't valid, because of protocol-free URLs. We could change that to check for exactly one `/` (i.e., `//` would not be internal), but it also looks like we do not need to handle relative URLs at all, because we will never get one from the API.

The API which returns the data for which we use this function (the `hero` API) *always* returns absolute URLs, so we can remove the code that checks for relative URLs.

**Comment by AlexandraMoga** [comment]
I haven't found other regressions apart form #8676 (fixed) in the homepage heroes.

Marking the issue as verified fixed
