### ISSUE TITLE
Internal URLs from homepage heroes are appended with parameters used for external links

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8676]
### Describe the problem and steps to reproduce it:

1. Load AMO homepage on -dev
2. Inspect the call to action URL for a listed primary hero, or a secondary hero that links to an internal page

### What happened?
Internal URLs are appended with parameters intended for external links - i.e. `?utm_content=homepage-primary-hero&utm_medium=referral&utm_source=addons-dev.allizom.org"`

### What did you expect to happen?
Internal URLs should have the following parameters: `src=homepage-primary-hero` or `src=homepage-secondary-hero`

**Notes**
This might be a regression from #8674, because the issue was not present last week

![image](https://user-images.githubusercontent.com/31961530/65769960-a7718480-e13d-11e9-8e80-5c4d33cc5263.png)

**Comment by bobsilverberg** [comment]
Ah, I now realized that #8674 was not accurate. While it's true that all URLs coming from an API call will be fully qualified, I ignored the fact that we are building some URLs ourselves, which can contain relative URLs and those also make use of the `checkInternalURL` function. I will fix this.

Thanks for filing this, @AlexandraMoga.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.

Internal URLs are appended with the correct parameters now:

[primary hero]
![image](https://user-images.githubusercontent.com/31961530/66033097-48ca5300-e50f-11e9-913f-af7196acff4d.png)

[secondary hero]
![image](https://user-images.githubusercontent.com/31961530/66033111-4ff16100-e50f-11e9-9307-efe7d05827c3.png)
