### ISSUE TITLE
Redirect search add-on URL coming from Firefox

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8679]
Part of [this PRD](https://docs.google.com/document/d/1FQq47mNCRy1enLsN0giseD2tnS0OaHth3S5mZL9C8jY/edit).

A link in Firefox sends users to `/search-engines/`, which in turn redirects to `/search-tools/`. Instead, it should redirect to the Search Tools extensions category, which is something like `/search/?category=search-tools&sort=recommended%2Cusers&type=extension`.

This depends on https://github.com/mozilla/addons-server/issues/12462 being resolved, so the timing isn't off.

**Comment by jvillalobos** [comment]
Forgot to mention that `/search-tools/` should also redirect to the new path.

**Comment by willdurand** [comment]
> This depends on [mozilla/addons-server#12462](https://github.com/mozilla/addons-server/issues/12462) being resolved, so the timing isn't off.

Looks like this issue has been fixed, so we should be good to go. Given that we need a feature flag for the whole removal, I believe we'll have to perform a redirect from the frontend. After that, we'll be able to move the redirect to Nginx.

**Comment by ioanarusiczki** [comment]
@willdurand 
https://addons-dev.allizom.org/en-US/firefox/search-tools/ and https://addons-dev.allizom.org/en-US/firefox/search-engines/ 
redirect to https://addons-dev.allizom.org/en-US/firefox/search/?category=search-tools&sort=recommended%2Cusers&type=extension

![redirecting](https://user-images.githubusercontent.com/33448286/68947457-2be79780-07be-11ea-85be-8e83acdc4bab.gif)
