### ISSUE TITLE
Remove Search Tool add-on type

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8680]
Part of [this PRD](https://docs.google.com/document/d/1FQq47mNCRy1enLsN0giseD2tnS0OaHth3S5mZL9C8jY/edit).

I think this involves removing the Search Tool type from the site search, and the Search Tools menu item in the More dropdown in the site header.

This change should be gated by an admin flag, so we can control the timing.

**Comment by willdurand** [comment]
@jvillalobos do we need to do anything to the search tool product pages? Example: https://addons.mozilla.org/en-US/firefox/addon/inudu-search/

**Comment by jvillalobos** [comment]
We won't disable those pages until 2020. For now we're just removing the main access points.

**Comment by willdurand** [comment]
> We won't disable those pages until 2020. For now we're just removing the main access points.

Thanks. Do we want to hide the search plugins in the search results (in addition to removing the filter option)?

**Comment by jvillalobos** [comment]
No, I think it's okay that they should up in search results.

**Comment by ioanarusiczki** [comment]
@willdurand 
- the `Search Tools` link has been removed from the `More` Menu
- the search no longer displays the search tools as an `Add-on` type

On Android the `More` Menu looks quite empty right now. 

![Android](https://user-images.githubusercontent.com/33448286/68946044-a6aeb380-07ba-11ea-83d5-b23f9420c3fb.png)

**Comment by willdurand** [comment]
> On Android the `More` Menu looks quite empty right now.

Ohh, that's a good catch. I don't think we need the "for Android" section anymore in that case. I will fix this!

**Comment by willdurand** [comment]
@ioanarusiczki I filed https://github.com/mozilla/addons-frontend/issues/8940
