### ISSUE TITLE
stay safe online section is not left aligned.

### ISSUE THREAD

**Issue by tsl143** [mozilla/addons-frontend#8695]
### What happened?
`HomeHeroGuides-sections` is not aligned to header logo and recommended section shelf

### What did you expect to happen?
All the shelves should be aligned, and eventually to the header logo

### Anything else we should know?

![image](https://user-images.githubusercontent.com/5318732/65960346-90d86f80-e454-11e9-9161-b97e2300d156.png)

**Comment by bobsilverberg** [comment]
This might be intentional, the way the headline is also centered above the guides pages boxes.

@brassy- can you comment on this?

**Comment by willdurand** [comment]
This was intentional according to the PRD: https://docs.google.com/document/d/1PZwtYeWC2_eWBOX4a8QUBoOHeAZpEEOFRzEhpsgFrKo/edit#
