### ISSUE TITLE
Where is Lightbeam ?

### ISSUE THREAD

**Issue by alaing13** [mozilla/addons-frontend#8704]
### Describe the problem and steps to reproduce it:
https://addons.mozilla.org/fr/firefox/addon/lightbeam/

### What happened?
Oups, cette page est introuvable

### What did you expect to happen?
New version available ? Last version ?

### Anything else we should know?
this is an important project

**Comment by jvillalobos** [comment]
The Lightbeam extension has been discontinued. Most of its features are being integrated into Firefox, so the extension is no longer available.
