### ISSUE TITLE
Temporarily disable the non-recommended warning banner

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8706]
In https://github.com/mozilla/addons-frontend/issues/8525 we enabled an experiment to understand the effect of showing a warning when users are about to install a non-recommended extension.

We have concluded the experiment -- we now have some numbers to help us understand how the warning affects installs (this includes recommended extensions, too).

During [today's front-end review meeting](https://docs.google.com/document/d/15djJvX80hDmOTZLuo4JzLpkcLlCN6cqEsLr-h0F366A/edit#heading=h.aa0uq5wil583), @jvillalobos and @atsay requested that we temporarily disable the warning banner for the following reasons:
- We've concluded the experiment so we don't need to collect more data
- We'd like to change the wording of the banner because it has created some confusion among developers (through feedback we've received).
- We'd also like to experiment with some UX changes to make the warning less scary. This will be done in a future experiment.

**Comment by vcarciu** [comment]
Verified as fixed in AMO-dev and Stage.
