### ISSUE TITLE
The Secondary hero message lacks some padding

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8720]
Update:

It was confirmed by UX that we do not want to center the text in the message area of the secondary hero, but @willdurand pointed out that this same area seems to be missing some padding, so I am going to implement that change for this issue.

### Describe the problem and steps to reproduce it:
1. Open AMO -dev homepage in mobile view
2. Notice the position of the Secondary hero message paralleled to the hero modules

### What happened?
The Secondary hero message is aligned to the left, while the modules are center aligned. 

### What did you expect to happen?
For a cohesive layout, the Secondary hero message should also be center aligned 

![image](https://user-images.githubusercontent.com/31961530/66298685-c8cf2f00-e8fa-11e9-8d9a-ca90863781e3.png)

**Comment by bobsilverberg** [comment]
@brassy- Can you please comment on this?

**Comment by brassy-** [comment]
I disagree. I don’t think is necessary to center aligned the intro text.

Il giorno lun 7 ott 2019 alle 15:37 Bob Silverberg <notifications@github.com>
ha scritto:

**Comment by willdurand** [comment]
This is stage currently:

![Screen Shot 2019-10-07 at 15 40 14](https://user-images.githubusercontent.com/217628/66316914-d2678f80-e918-11e9-8708-7ab8b605d24d.png)

The screenshot in the original issue looks like some style has not been loaded. All contents are in "boxes" (or cards) except this one. The link is too close to the card below. I think it needs some more love :)

**Comment by bobsilverberg** [comment]
Thanks for the feedback on this @willdurand. I'm not sure exactly where we stand though, after @brassy-'s statement that the message need not be centered. In the example above from stage, the initial message is not in a box or card, which matches the example from dev. I agree we need some more padding around the content, but is the suggestion that this initial message also be in a card?  

What's being requested is unclear enough to me that I think it would be good to have a mock of exactly what it's meant to look like on a mobile-sized viewport. Are you able to provide that @brassy-?

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/67551758-4de78000-f712-11e9-84d5-56b8db5fbac7.png)
