### ISSUE TITLE
AMO page for addon says it's not compatible with Firefox Quantum, not a public listing, and not compatible with my platform

### ISSUE THREAD

**Issue by steamp0rt** [mozilla/addons-frontend#8721]
### Describe the problem and steps to reproduce it:

I uploaded an addon to AMO yesterday. The URL is https://addons.mozilla.org/en-US/firefox/addon/opentagger/

The version, in the developer hub, is approved and validated for all platforms.

![firefox_vXDAh7IbnD](https://user-images.githubusercontent.com/25724666/66305888-d7641900-e8ef-11e9-8c0f-76e87c542584.png)

However, the page is invisible unless i'm logged in. And has a laundry list of red banners. If I manually install the extension via the xpi, _it works perfectly_
![firefox_S5LkBFhnST](https://user-images.githubusercontent.com/25724666/66305804-a84da780-e8ef-11e9-8346-833f094b212b.png)

### What happened?

The page is invisible and full of warnings.

### What did you expect to happen?

The page to be available and not full of warnings.

### Anything else we should know?

I used `web-ext sign` rather than uploading a zip.

**Comment by jvillalobos** [comment]
You need to upload a new version and choose the hosted option: https://extensionworkshop.com/documentation/publish/submitting-an-add-on/
