### ISSUE TITLE
Android main page of an add-on offers latest (incompatible) version instead of older (but compatible) version

### ISSUE THREAD

**Issue by buttercookie42** [mozilla/addons-frontend#8726]
### Describe the problem and steps to reproduce it:
Basically issue mozilla/addons#120, but this time concerning the split between Android and Desktop, where significant differences in API support still remain (and whereas we didn't have separate pages/URLs for older and newer Firefox versions, we *do* have separate URLs for Desktop and Android).

### What happened?
I.e. when the latest version of your add-on is incompatible with Android, but older versions are compatible, the problem is that even when visiting the Android page of the add-on, the overview page still only offers the *very latest* version of your add-on, albeit marked as incompatible and with the install button deactivated.

### What did you expect to happen?
Either the Android page should automatically offer the latest version of the add-on that is compatible with Android, or at least there should be an automatic prominent notice that an older version compatible with Android is available, too.

### Anything else we should know?
Originally [reported here](https://bugzilla.mozilla.org/show_bug.cgi?id=1582821), the add-on in question is https://addons.mozilla.org/en-GB/android/addon/ipfs-companion/, which is currently at version 2.8.5, but the latest Android-compatible version is 2.8.3.

**Comment by lidel** [comment]
Just realized this issue is not limited to Android. Same problem with the latest ESR release:

![esr-2019-10-08--19-37-59](https://user-images.githubusercontent.com/157609/66418925-6a41a800-ea03-11e9-8f03-55a906ca2013.png)


Due to slow release cycle of ESR, its users should be able to install "the last compatible version" from the main UI. Right now the `Add to Firefox` button is faded out, making ESR user unable to install extension.

**Comment by jvillalobos** [comment]
As I understand it, offering the latest compatible version would not be great for performance. One thing we _could_ do is change the error message so it says it's possible there's an older version available that could work, and link to the versions page.
