### ISSUE TITLE
[Primary hero] There's too much unused space at the bottom the primary hero on mobile view

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8732]
### Describe the problem and steps to reproduce it:
1. Open AMO -dev homepage in mobile view
2. Notice the layout of the primary hero module

### What happened?
There is too much unused space at the bottom

### What did you expect to happen?
The height could be reduced a little

### Anything else we should know?
- I've compared this view with a screenshot I took yesterday and it seems to me that this is a regression. 
- If I'm correct, the only patch that landed in the meantime was https://github.com/mozilla/addons-frontend/pull/8678

[old screenshot] - posted in https://github.com/mozilla/addons-frontend/issues/8623#issuecomment-538898374
![image](https://user-images.githubusercontent.com/31961530/66409169-d4088480-e9f8-11e9-8a99-800ced7b3c8f.png)

[new screenshot]
![image](https://user-images.githubusercontent.com/31961530/66409190-df5bb000-e9f8-11e9-9795-6ed21257b96c.png)

**Comment by nik72619c** [comment]
shall I work on this ?

**Comment by bobsilverberg** [comment]
> shall I work on this ?

Thank you for your interest, @nik72619c, but this issue isn't ready to be worked on. Issues that are good options for contributors can be found by searching using the `contrib: welcome` label, e.g., https://github.com/mozilla/addons-frontend/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22contrib%3A+welcome%22.

**Comment by bobsilverberg** [comment]
@AlexandraMoga I have fixed this, but please note that the loading skeletons for the hero elements will not line up exactly with the final versions except on a large viewport. This is something we knew would happen when we landed the loading skeletions. That said, with the patch I am landing for this issue there shouldn't be a significant amount of empty space at the bottom of the primary hero in the fully-loaded version.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/66817211-060f6e80-ef44-11e9-82f0-7ea7d92758ea.png)

![image](https://user-images.githubusercontent.com/31961530/66817223-0b6cb900-ef44-11e9-99a2-f4da816e86cc.png)
