### ISSUE TITLE
Some shelves titles and their see more links are overlapping in mobile landscape mode

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8737]
### Describe the problem and steps to reproduce it:
1. Open AMO homepage on a mobile device in landscape mode (or use the responsive design tools)
2. Change your locale to `/de/` or `/it/`
3. Check for layout issues in the shelf titles

### What happened?
For some shelves, the title and the see more link are overlapping 

### What did you expect to happen?
No layout issues

### Anything else we should know?
- this issue reproduces on all AMO servers, so it's not new

[german]
![image](https://user-images.githubusercontent.com/31961530/66478214-8b0d0a80-eaa2-11e9-85bd-916932b5d792.png)

[italian]
![image](https://user-images.githubusercontent.com/31961530/66478257-a2e48e80-eaa2-11e9-87f6-ae5d950a21c3.png)

**Comment by Aakash2408** [comment]
Is this issue still open?
