### ISSUE TITLE
Introduce some page-level error components

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8744]
This is a follow-up to #8743 

Some components, such as [`<Search>`](https://github.com/mozilla/addons-frontend/blob/262cafdc6d0aa45ebb0bee2534a2f694857e91e2/src/amo/components/Search/index.js#L213) render error components, such as [`<NotFound>`](https://github.com/mozilla/addons-frontend/blob/262cafdc6d0aa45ebb0bee2534a2f694857e91e2/src/amo/components/ErrorPage/NotFound/index.js), and when those components are themselves included inside a page-level component, such as [`SearchPage`](https://github.com/mozilla/addons-frontend/blob/262cafdc6d0aa45ebb0bee2534a2f694857e91e2/src/amo/pages/SearchPage/index.js#L107) we can end up with rendered output that includes a `<Page>` inside a `<Page>`. 

Another issue is that when a page-level component renders one of these error components as an alternative, such as [here](https://github.com/mozilla/addons-frontend/blob/260fc195f4c8ec20d9a3904a8c4883866a7b2392/src/amo/pages/UserProfileEdit/index.js#L485), it isn't clear that the resulting output will in fact be wrapped in a `<Page>`.

In order to address both of these issues it is suggested that we introduce a page-level component for each of these error components, which itself would simply wrap the error component in a `<Page>`. When one of these error components is meant to render the output of a page, such as [here](https://github.com/mozilla/addons-frontend/blob/260fc195f4c8ec20d9a3904a8c4883866a7b2392/src/amo/pages/UserProfileEdit/index.js#L485), we would use the new page-level error component.

**Comment by AlexandraMoga** [comment]
I've triggered several instances where a 404 page error should be displayed and didn't notice any regressions.

I know we also have a Server error page but I didn't know how to trigger that. 

In any case, I think we can mark this issue as verified.
