### ISSUE TITLE
Homepage information banners are too wide

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8750]
### Describe the problem and steps to reproduce it:
1. Load AMO homepage on stage
2. Notice the layout of the site notice

### What happened?
The banner is too wide

### What did you expect to happen?
The banner should be the same width as the rest of the content

### Anything else we should know?
- this is not reproducing on -dev, where to homepage hero is enabled; there must be some setting that controls the width which is present only when the hero is available
- this could be a regression from https://github.com/mozilla/addons-frontend/pull/8662
- the information banners have the correct with in the rest of the pages, so only the homepage is affected

[layout issues with the site-notice enabled and an server error banner]
![image](https://user-images.githubusercontent.com/31961530/66565632-9c6e1980-eb6b-11e9-8a0c-e6583996767e.png)

**Comment by muffinresearch** [comment]
> I can likely fix this right now, but as it is a cosmetic issue I think we should probably include the fix in next week's tag and not try to cherry-pick at this late stage.
> 
> @muffinresearch WDYT?

Yep that sounds reasonable. I'm not aware of a need to use the banner.

**Comment by muffinresearch** [comment]
> > I can likely fix this right now, but as it is a cosmetic issue I think we should probably include the fix in next week's tag and not try to cherry-pick at this late stage.
> > @muffinresearch WDYT?
> 
> Yep that sounds reasonable. I'm not aware of a need to use the banner.

On second thoughts that's the error notification. How big would the fix be, if it's a few lines then we could pick it and it would be low risk if it's more than that perhaps not?

**Comment by muffinresearch** [comment]
Ok, I think we can avoid a late pick if it's nothing but cosmetic and overall not likely to be seen by many people.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev and stage:

With new hero - dev:
![image](https://user-images.githubusercontent.com/31961530/66902563-88ae3180-f009-11e9-9611-989159f86101.png)


Without new hero - stage:
![image](https://user-images.githubusercontent.com/31961530/66902592-96fc4d80-f009-11e9-8d5d-7581f03dabdd.png)
