### ISSUE TITLE
Error messages too wide on home page with new hero

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8756]
While working on #8750, I discovered that the error banner is too wide when the new heros are active:

![Screenshot 2019-10-10 12 13 30](https://user-images.githubusercontent.com/142755/66587127-d2a19e00-eb57-11e9-8f02-d0ca0fd212d8.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/66903285-de370e00-f00a-11e9-9379-f3d2e43e47a2.png)
