### ISSUE TITLE
Problems with site banner and error messages on Android home page when new hero is enabled

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8757]
STR:

1. With `enableFeatureHeroRecommendation: true` (which means locally or on -dev), go to the Android home page (https://addons-dev.allizom.org/en-US/android/).
2. Generate an error.

Expected:

Site notices and error message appears in the usual places with the appropriate widths.

Actual:

No site notices are visible and the error message is too wide and too close to the header. See screenshot below:

![Screenshot 2019-10-10 15 14 37](https://user-images.githubusercontent.com/142755/66599229-b8c08500-eb70-11e9-9149-079261503f42.png)

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:
Site banners are displayed correctly when switching to /android/
![image](https://user-images.githubusercontent.com/31961530/66914291-29f3b280-f01f-11e9-9d68-88078d9b72d8.png)
![image](https://user-images.githubusercontent.com/31961530/66914304-32e48400-f01f-11e9-9159-19232fc9f99f.png)
