### ISSUE TITLE
lightbeam extension is gone

### ISSUE THREAD

**Issue by madjin** [mozilla/addons-frontend#8759]
### Describe the problem and steps to reproduce it:

Lightbeam is missing from the add-ons frontend.

### What happened?

Mysteriously disappeared after an update although the github reflects no recent changes. Why was there an update shown for the add-ons frontend but not the github?

### What did you expect to happen?

https://addons.mozilla.org/en-US/firefox/addon/lightbeam/  to show lightbeam and ability to install it.

### Anything else we should know?

Lightbeam is perhaps one of the greatest educational tools ever made by Mozilla!

**Comment by jvillalobos** [comment]
The extension was discontinued. Some of its features are being integrated into future versions of Firefox.
