### ISSUE TITLE
New A/B test for non-recommended warning

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#8760]
Following up on https://github.com/mozilla/addons-frontend/issues/8137, we want to run a new test to try out a more subtle UX. We also want to test a smaller population in order to reduce the backlash.

Based on feedback from Felix, I suggest we split it this way:
* 20% see the old warning (https://github.com/mozilla/addons-frontend/issues/8137).
* 20% see the [new warning](https://mozilla.invisionapp.com/share/7UU864JXYRK#/screens/387093697_addons-Messaging-Platforms).
* 60% don't see the warning.

Another nit is that the warning shouldn't show up in the cases where the platform warning in https://github.com/mozilla/addons-frontend/issues/8701 should appear.

Because of the smaller populations, Felix mentioned the test might need to run for longer.

**Comment by bobsilverberg** [comment]
@felixlawrence / @jvillalobos I want to make sure I understand how we're going to assign users to branches. Based on the above, are we going to take 100% of users and assign 60% of them to a branch that shows no warning, 20% to a branch that shows warning A, and 20% to a branch that shows warning B? Or are we going to take a sample of users that represents less than 100% of users, i.e., 20% of users, and then slot *those* users into the three buckets in a 60/20/20 ratio?

**Comment by jvillalobos** [comment]
I suggesting the former (100% of users divided 60/20/20). If there's a reason to go with the latter approach, then we could just pick a small enough group (say, 20% of users) and split it evenly three ways.

**Comment by felixlawrence** [comment]
I haven't been assigned to work on the new bug, but I'll throw in a quick recommendation: I'd recommend that if you want to run this, then you do follow @jvillalobos 's suggesting of picking a subset of users to be in the experiment, and splitting that group evenly three ways. If users are split between groups evenly, then that is resilient to a range of common implementation issues - if some branches have a much larger % of the population then certain types of errors (e.g. duplicate enrollments) can bias the results, whereas if the groups are even then the errors are comparable for each branch and no bias is added.

This can be implemented either as a pair of splits (is the user in the experiment 80/20?, if in the experiment which of the there branches are they in 33/33/33), or as a _four_ branch experiment (20% old warning, 20% new warning, 20% no warning, 60% no warning and not in the experiment so ignore their results)

**Comment by bobsilverberg** [comment]
> 
> This can be implemented either as a pair of splits (is the user in the experiment 80/20?, if in the experiment which of the there branches are they in 33/33/33), or as a _four_ branch experiment (20% old warning, 20% new warning, 20% no warning, 60% no warning and not in the experiment so ignore their results)

Thanks @felixlawrence. I assume the last breakdown would be 20% old warning, 20% new warning, 20% no warning, 40% no warning and not in the experiment so ignore their results? I replaced the `60%` in your statement with `40%` because 20+20+20+60 exceeds 100%.

**Comment by felixlawrence** [comment]
_cough_ yes.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev with FF70(Win10) and these are my test results:
- with 10 new profiles:
Profile 1: excludeWarning
Profile 2: notInExperiment
Profile3: excludeWarning
Profile4: excludeWarning
Profile5: includeWarning-proposed
Profile 6:includeWarning-proposed 
Profile7:  includeWarning-proposed
Profile8: notInExperiment 
Profile9: includeWarning-proposed
Profile10: includeWarning-proposed

**Total**:
5 times includeWarning-proposed is 50%
3 times  excludeWarning 50% 
2 times notInExperiment

So in this case, 50% of the users will not see the warning and the other 50% will see the new warning.

- I deleted the cookies on the same profile and the results are:
1  notInExperiment
2  notInExperiment
3 excludeWarning
4 notInExperiment
5 notInExperiment 
6 notInExperiment
7 includeWarning-current
8 excludeWarning
9 notInExperiment
10 includeWarning-current

**Total**:
6 times  notInExperiment
2 times excludeWarning
2 times includeWarning-current

80% will not see the warning and 20% will see the new warning. 

- the warning message is only available without the platform message. 

![the warnings ](https://user-images.githubusercontent.com/33448286/68596181-7bb71d80-04a3-11ea-827f-49983c7c44c7.gif)

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. Those numbers do not match our expectations, but because each time a cookie is assigned it is an independent event, there's not really any way to test the accuracy of our algorithm except to have it create a cookie a large number of times.

Your comment did make me realize a mistake in my implementation though. I need to change the name of the cookie being generated for this experiment, which I did not do. If we do not do that then users who were enrolled in the previous iteration of the experiment will not receive an updated cookie.  I will open an issue to address that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I will take a look on that issue then. 
I'm marking this issue verified on dev with FF70(Win10).

**Comment by bobsilverberg** [comment]
@jvillalobos This has landed on dev, so we now need to determine when to enable it on prod (and also if we want to make it active on stage for a full week beforehand, or just enable it on stage on a Tuesday and push to prod on the Thursday). We don't have a data scientist assigned to [the bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1588893) yet, but @felixlawrence suggested we would probably want to run this for a longer period than the last one, so maybe it's okay to get it started soon.

What do you think?

**Comment by jvillalobos** [comment]
I'm in favor of starting it as soon as possible, so we can wrap it up before the end of the year. I just don't want us to be stuck in a position where we can't stop it confidently because we don't know for how long we'll need to run it to get good data. I don't have a good answer for the time spent on stage. Is that more of a question for QA?

**Comment by bobsilverberg** [comment]
> I'm in favor of starting it as soon as possible, so we can wrap it up before the end of the year. I just don't want us to be stuck in a position where we can't stop it confidently because we don't know for how long we'll need to run it to get good data. I don't have a good answer for the time spent on stage. Is that more of a question for QA?

I don't think it's a particularly big feature, so I don't see any reason to keep it on stage for more than the usual amount of time. @vcarciu Do you have any opinion on that?

If we'd like to potentially activate it this week, then I can create a commit to enable it on stage and prod and I can cherry-pick it so it will be on stage this afternoon. If it's decided not to push it to prod on Thursday, we can always make that change. It's just a config flag.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @jvillalobos I'll take a look at this on stage and update then the issue https://github.com/mozilla/addons-frontend/issues/8955
