### ISSUE TITLE
Liner highlighter add-on is no longer available

### ISSUE THREAD

**Issue by Smurfie8981** [mozilla/addons-frontend#8761]
### Describe the problem and steps to reproduce it:
open firefox browser
navigate to https://getliner.com/
click "add to firefox button" on the page

### What happened?
got redirected to the url below
https://addons.mozilla.org/en-CA/firefox/addon/liner-web-pdf-highlighter/
### What did you expect to happen?
i was expecting to be able to add the extension to firefox browser

**Comment by jvillalobos** [comment]
Please contact the add-on developers about this problem. It is up to them to bring back the page or correct the link.
