### ISSUE TITLE
lightbeam for linux

### ISSUE THREAD

**Issue by justonemarko** [mozilla/addons-frontend#8768]
### Describe the problem and steps to reproduce it:
Down loaded lightbeam on linux mint for ubuntu using the software manager but it would not install to latest firefox and mozila does not have lightbeam in their repo for linux..  the add-on does not show up in the add-on section for firefox..  I have used this add-on in win7 for years and have found it very useful and would like to keep on using it with this linux mint distro.  
![image](https://user-images.githubusercontent.com/56524039/66725552-2566a880-ee2b-11e9-8c83-ff8f59a8bd1c.png)
The link above is where the add-on link to mozila shows and the add-on I downloaded

**Comment by justonemarko** [comment]
Thank you for your attention.

**Comment by marquezjohnchristian** [comment]
I was looking for this addon as well. Was it intentionally removed from the [page](addons.mozilla.org)?

**Comment by justonemarko** [comment]
It's there for windows OS but not for linux,, but I did download it from a ubuntu repo and it dowloaded ok but ,it did not install onto the firefox browser... I'll keep on trying with it and see if I can get it to work/ install on to the browser.

**Comment by jvillalobos** [comment]
The add-on was removed because it's no longer being supported. Some of its features are being integrated into Firefox in the future.

**Comment by justonemarko** [comment]
Thank you for the info jvillalobos,  I have noticed it has been removed from the Windows OS firefox web browser recently, I'm looking forward to seeing it again or some thing that closely resembles it...
