### ISSUE TITLE
Fix Storybook story for HeroRecommendation with an error

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8777]
This is a follow-up to #8753 

In that PR a story was added for `HeroRecommendation` which is meant to show a variant that includes displaying an error. The story is not working properly in that an error is not displayed in the hero element. 

In order to make this work it looks like we need to create a `store` in the `sectionFn` for the story, and then pass that store into the `Provider`.

**Comment by codeEmpress1** [comment]
Hi @bobsilverberg ,  I am an outreachy applicant, I will like to give this issue  a trial.

**Comment by willdurand** [comment]
@codeEmpress1 as mentioned elsewhere I dont think this is a good first bug. 
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by willdurand** [comment]
@codeEmpress1 if you know a bit of JS, please go ahead!

**Comment by Albaalah** [comment]
Hello @willdurand can I please work on this?

**Comment by willdurand** [comment]
@Albaalah not sure right now because @codeEmpress1 expressed an interested in working on this issue first

**Comment by accakks** [comment]
hi @willdurand  I'm also an Outreachy applicant. Can you suggest me some issues to work on, it seems all 4 are being worked on?

**Comment by willdurand** [comment]
@accakks you can also look into the `contrib: welcome` issues. We'll likely add new `contrib: outreachy` issues in the coming days.

**Comment by codeEmpress1** [comment]
Thanks @willdurand , I know JS and I have picked the issue, presently working on it, Can you kindly assign it to me so that others can know it has been assigned.

**Comment by bobsilverberg** [comment]
> Thanks @willdurand , I know JS and I have picked the issue, presently working on it, Can you kindly assign it to me so that others can know it has been assigned.

@codeEmpress1 done!
