### ISSUE TITLE
Firefox logo has an SVG glitch on iOS mobile browsers

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8788]
### Describe the problem and steps to reproduce it:

Load https://addons.mozilla.org on an iOS browser like Firefox or Mobile Safari.

### What happened?

The Firefox logo is missing some colors and looks broken.

<details>
<summary>Screenshots for iOS Firefox and Safari</summary>

![2019-10-17 10 31 57](https://user-images.githubusercontent.com/55398/67024631-587a9780-f0ca-11e9-95b7-eb220501adbd.png)
![2019-10-17 10 32 21](https://user-images.githubusercontent.com/55398/67024632-587a9780-f0ca-11e9-85ea-abda4d35c36c.png)

</details>

### What did you expect to happen?

The logo should look like this:

<details>
<summary>Screenshot from desktop Firefox in responsive mode</summary>

<img width="375" alt="Screenshot 2019-10-17 10 34 10" src="https://user-images.githubusercontent.com/55398/67024647-5f090f00-f0ca-11e9-8783-8f070ba4c6f0.png">

</details>

### Anything else we should know?

This is probably another glitch in our SVG optimizer, like https://github.com/mozilla/addons-frontend/issues/7191

Keep in mind that we will be switching logos (https://bugzilla.mozilla.org/show_bug.cgi?id=1582891) soon but we may still have a glitch, who knows.

**Comment by kumar303** [comment]
The new logo in https://github.com/mozilla/addons-frontend/pull/8885 does not have this problem which tells me it was an issue with the source SVG, not our compressor. I was testing it on iOS using my local dev server. Also noteworthy: the glitch was visible using a development build.

**Comment by ioanarusiczki** [comment]
@kumar303 I verified the issue on iOS 13.1.3 on AMO dev - it looks good now in both Safari and Firefox Browsers. 

![on Safari](https://user-images.githubusercontent.com/33448286/68218665-60ed3080-ffed-11e9-8992-1c6bf3012714.png)
