### ISSUE TITLE
Remove complete theme support

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8804]
We do not support XUL/complete themes in addons-server so let's remove the support for them in addons-frontend.

**For QA:** there should be no obvious regression.

**Comment by ioanarusiczki** [comment]
The [release testing](https://testrail.stage.mozaws.net/index.php?/plans/view/21765) was completed on AMO stage with FF70(Win10) and FF68.2.0 (Android 8.0). 
No regressions found.
