### ISSUE TITLE
Remove code that interacts with enableFeatureHeroRecommendation flag

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8810]
The `enableFeatureHeroRecommendation` flag was added during the development of the new hero promo shelves. Now that those are enabled in all environments, we can remove all of the code that interacts with that flag, which will include removing every code path for `enableFeatureHeroRecommendation === false`. Any tests which reference this flag will also need to be updated/removed.

We should wait for the feature to sit in production for a few weeks before doing this, but it will be good to clean it up when we are confident it is okay to do so.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Nothing unusual to catch my eye but I'll leave it for final validation after the release testing on stage.
Verified on dev with FF70(Win10).
