### ISSUE TITLE
Chrome Store Foxified removed

### ISSUE THREAD

**Issue by jordanli04** [mozilla/addons-frontend#8817]
### Describe the problem and steps to reproduce it:
Chrome Store foxified has been removed

Chrome Store foxified is removed by that developer or mozilla removed it!
### What happened?
This extension is unlikely to be removed
### What did you expect to happen?
I want to re-add it again!
### Anything else we should know?
I have no idea

https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/

**Comment by jvillalobos** [comment]
It's up to the developer to bring back the listing. We can't help you with that.

**Comment by jordanli04** [comment]
> 
> 
> It's up to the developer to bring back the listing. We can't help you with that.

Please bring back Chrome Store Foxified!
