### ISSUE TITLE
The category button list looks uneven when the list wraps

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8823]
### Describe the problem and steps to reproduce it:

1. Go to a category landing page, like:
* https://addons-dev.allizom.org/en-US/firefox/extensions/
* https://addons-dev.allizom.org/en-US/firefox/themes/

2. Adjust the browser window so that the list of categories wraps to a new line

### What happened?

The list is left justified which looks uneven.

### What did you expect to happen?

It should look more even.

**Comment by ioanarusiczki** [comment]
@kumar303 I verified this on AMO dev with FF69(Win10). 
This is how it looks when resizing the screen:

![categories](https://user-images.githubusercontent.com/33448286/67559989-a3c42400-f722-11e9-988d-dd157f5980d0.gif)

Category page on small screens:

![Themes categories](https://user-images.githubusercontent.com/33448286/67560242-24832000-f723-11e9-97cd-d5f36ed787f5.PNG)

Looks good to me.
