### ISSUE TITLE
The site notice banner has inconsistent margins on mobile view

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8827]
This was mentioned in a comment at https://github.com/mozilla/addons-frontend/pull/8797#pullrequestreview-305435576.

> The mobile view has inconsistent margins around the site notice. This might have nothing to do with your patch and since it just affects the site notice, feel free to address it in a follow-up.

<details>
<summary>Screenshot</summary>
<img width="361" alt="Screenshot 2019-10-22 14 51 48" src="https://user-images.githubusercontent.com/55398/67327371-70dd1e80-f4dd-11e9-8334-9d33aa225a5b.png">
</details>

**Comment by muskangupta-iitr** [comment]
Hi @willdurand, I am Outreachy aspirant and interested to proceed further with this task as it is open for all.

**Comment by willdurand** [comment]
@muskangupta-iitr hi, I assigned you to this issue.

**Comment by ioanarusiczki** [comment]
@willdurand I verified on Android 9.0, it looks good to me. 

![the fix looks good](https://user-images.githubusercontent.com/33448286/78234468-d9461800-74df-11ea-830f-a034b73f7dd9.png)

I can't tell if on the detail page is alright - the platform warning is not centered between the install button and the white margin (same in case the compatibility warning is displayed under the button). 

![platform warning](https://user-images.githubusercontent.com/33448286/78234600-0eeb0100-74e0-11ea-9124-217d5aa3e1e1.png)

**Comment by willdurand** [comment]
> I can't tell if on the detail page is alright - the platform warning is not centered between the install button and the white margin (same in case the compatibility warning is displayed under the button).


mmm I think this is a different problem (and likely not a problem at all)

**Comment by ioanarusiczki** [comment]
@willdurand I was hoping it's not :)

Verified on Android 9.0 with 68.6.0 - Fennec
