### ISSUE TITLE
See all extensions link from home page doesn't work

### ISSUE THREAD

**Issue by tborychowski** [mozilla/addons-frontend#8828]
### What happened?
1. Open https://addons.mozilla.org/en-US/firefox/
2. Click on "See all extensions" link
3. Error  page

### What did you expect to happen?
1. Hmmm... See all  extensions? :-)

### Anything else we should know?

<img width="1305" alt="Screenshot 2019-10-24 at 20 20 32" src="https://user-images.githubusercontent.com/392513/67518106-fc9ca980-f69b-11e9-81f3-4c1b253d68e2.png">

**Comment by kumar303** [comment]
Thanks for taking the time to submit a bug report. We'll work on a fix!

**Comment by kumar303** [comment]
This is a config problem just like https://github.com/mozilla/addons-server/issues/12717

I'm trying to find someone with access to the config but it's late in Europe ☠️

**Comment by kumar303** [comment]
This has been fixed in the config.

**Comment by vcarciu** [comment]
Verified as fixed in prod.
