### ISSUE TITLE
Remove `installTheme()` logic

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8830]
We cannot install LW themes anymore because we don't show LWT anymore. We can safely remove the logic to install LWT.

**For QA:** installing a static theme should work as expected, same for other supported add-ons.

**Comment by ioanarusiczki** [comment]
@willdurand 
I verified installs on AMO dev with FF70 unbranded (Win10) and FF 68.2.0 (Android 8.0) and I see them working as before.
