### ISSUE TITLE
Add support for abuseReportPanelEnabled and reportAbuse to addonManager.js

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8832]
In order to support #8762, we need to add support for the new `mozAddonManager` `abuseReportPanelEnabled` property and `reportAbuse` function to `addonManager.js`.

For QA:

This does not add any visible functionality, but it does touch the file that implements mozAddonManager, so a check for regressions in installing, uninstalling, enabling and disabling add-ons would be in order.

**Comment by ioanarusiczki** [comment]
@bobsilverberg No issues found. Verified on AMO dev and AMO stage with FF70(Win10). 

[Release testing results ](https://testrail.stage.mozaws.net/index.php?/plans/view/21991)
