### ISSUE TITLE
Homepage layout appears unbalanced in the absence of images

### ISSUE THREAD

**Issue by atsay** [mozilla/addons-frontend#8837]
Update:

Based on all of the discussions below, it sounds like the intention is to assign images to all of the items that could appear in the primary hero. In addition to that a number of changes to the styles of the hero elements were requested. This issue is now about implementing those style changes.

I'm not sure if a separate issue needs to be opened to address the assigning of images to all items.

---------------------

### Describe the problem and steps to reproduce it:

The new AMO homepage design originally included the use of images in the hero area. Without images, the design looks out of proportion--the secondary area appears very large compared to the primary area, possibly because there isn't something visual there to draw your attention.

<img width="1720" alt="Add-ons_for_Firefox__en-US_" src="https://user-images.githubusercontent.com/1514/67959301-69f69000-fbf0-11e9-9260-aef21860b2a8.png">

### What happened?

Product had made a last-minute decision to leave out the images.

### What did you expect to happen?

We did not expect the overall design to be impacted.

### Anything else we should know?

Things to consider:

- Editorial wanted to cycle through a library of 80+ extensions; having images for all of them isn't practical.

- We can consider reducing the number of extensions cycling through, and find images for all of them.

- We can consider reducing the size of the secondary hero area.

- Would like @aaronrbenson 's opinion on this.

**Comment by kumar303** [comment]
I agree with this. When we first implemented the centered text layout, I had proposed something that looked more like the left-aligned image variant. You can see it by [viewing this comment](https://github.com/mozilla/addons-frontend/pull/8648#discussion_r327711280) and toggling the *Screenshots* bullet point.

Since I made that comment the centered text layout has grown on me a little bit. It still feels kind of stark and overly spacious, though.

**Comment by atsay** [comment]
As discussed with UX, we will reduce the number of recommendations featured in the hero area to 5-7 and select images to go with them.

I also noticed that the subhead copy in the secondary promo shelf do not match the size of the original design. It's much larger. Let's reduce it so that it's the same size as the subhead copy in the hero area.

**Comment by bobsilverberg** [comment]
> 
> I also noticed that the subhead copy in the secondary promo shelf do not match the size of the original design. It's much larger. Let's reduce it so that it's the same size as the subhead copy in the hero area.

Thanks @atsay. Can you be more explicit about exactly which elements in the secondary hero need to be made smaller, and which elements in the primary hero they should match in terms of size?

**Comment by atsay** [comment]
Sure, for example if you look at the copy "Sync extensions across devices" on the live site: https://www.dropbox.com/s/t2whxigp8z329bo/Screenshot%202019-10-31%2011.55.39.png?dl=0 it looks larger than "Stop trackers in their tracks..." in the hero area. In comparison, the original design had them shown in the same size: https://www.dropbox.com/s/4ftirp3j4gjuxpz/Screenshot%202019-10-31%2011.56.05.png?dl=0

**Comment by bobsilverberg** [comment]
Thanks @atsay. I would argue that the original design had the text in the Primary hero larger than it is now, which is why it matched the Secondary hero, not the other way around, but I'm fine making the Secondary hero text smaller to match what we currently have in the Primary hero.

**Comment by atsay** [comment]
Ah, that could be the case as well! Let's have @aaronrbenson make the call.

**Comment by bobsilverberg** [comment]
In case it wasn't clear from @atsay's comment above - we are awaiting direction from @aaronrbenson on this.

**Comment by aaronrbenson** [comment]
I think after talking with @devaneymoz and @atsay last week we decided to use generic images here. I'm still not clear about who needs to provide those images or where we get them. @atsay or @jvillalobos, can you point me to where we would get image assets for the heroes?

**Comment by bobsilverberg** [comment]
Thanks @aaronrbenson. In addition to the use of generic images, @atsay raised an issue about the size of the fonts and how they differ between the Primary and Secondary heroes, the details of which are [here](https://github.com/mozilla/addons-frontend/issues/8837#issuecomment-548521860). Do you think you could help us resolve what to do about the font sizes?

**Comment by jvillalobos** [comment]
The images will be provided to @devaneymoz by Cherry.

**Comment by aaronrbenson** [comment]
@bobsilverberg the font sizes and weights in the comp look more balanced to me. Do you need a breakdown of what those are from the mockup or do you already have that?

**Comment by bobsilverberg** [comment]
> @bobsilverberg the font sizes and weights in the comp look more balanced to me. Do you need a breakdown of what those are from the mockup or do you already have that?

I thought I had them, but that's what I based the implementation on and something is off, so if you have an up to date mock that includes font sizes that would be helpful.

**Comment by bobsilverberg** [comment]
Here's a summary of the new font requirements from @aaronrbenson:

![font-changes](https://user-images.githubusercontent.com/142755/68159388-b0652b00-ff1f-11e9-9507-eb3e7e850db5.png)

**Comment by aaronrbenson** [comment]
Also want to point out that the fonts used in the mock are different than our real world situation so we made some calls based on the existing font families to get the proportions right. Thank you @bobsilverberg!

**Comment by atsay** [comment]
Thanks for working out these details! I noticed the line spacing is different for each section--should this be defined as well?

**Comment by aaronrbenson** [comment]
I just annotated the values I changed.

**Comment by bobsilverberg** [comment]
@aaronrbenson I implemented the changes you documented, and here's what the new page looks like:

![Screenshot 2019-11-05 13 41 31](https://user-images.githubusercontent.com/142755/68235899-1a3e0d00-ffd2-11e9-9348-ec5c6e8b5725.png)

Note that we support a number of different screen sizes, and the font for some of the elements changes at different screen sizes. I used your numbers for the largest screen size, which is likely the most common, and that's also what's shown in the screen shot above.

Please let me know what you think.

**Comment by aaronrbenson** [comment]
This looks good to me! I think I misunderstood what @atsay was saying yesterday re: the line-height -- so if the line-height for the elements in the three 'cards' (sync/privacy/media) could be the same as the body text to the left, I'd call this 💯

**Comment by bobsilverberg** [comment]
Thanks @aaronrbenson. Here's a version where the line-height of the three "cards" matches the line-height of the body text to the left:

![Screenshot 2019-11-06 09 00 43](https://user-images.githubusercontent.com/142755/68304574-077c1480-0074-11ea-812c-ace0247a67f7.png)

**Comment by aaronrbenson** [comment]
Very nice 👨‍🍳👌

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I checked on dev with FF70(Win10) and it can seems to me  that compared to MacOS the text from the `Hero Recommendation body`, ` SecondaryHero message description` and the `SecondaryHero module description` has a lighter color tone. 

Desktop 

![desktop new layout](https://user-images.githubusercontent.com/33448286/68485261-a73dcc00-0247-11ea-986c-7da43bd75d5b.png)

MacOS

![MacOSlayout](https://user-images.githubusercontent.com/33448286/68485273-ae64da00-0247-11ea-889c-f9c5d66b986f.png)

**Comment by bobsilverberg** [comment]
Those screenshots also make it look like everything is quite a bit larger on MacOS, which seems odd. Is your zoom in Firefox set differently on the two browsers? Do all sites look like the text is smaller on your Windows browser?

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
The zoom is 100% and I checked with Inspector on both platforms the size and weight:
hero recommendation body:
font size 21px
font weight 300

secondary hero message description and module description:
font-size 18 px
font-weight 400

If I check the image from the [pull request](https://user-images.githubusercontent.com/142755/68304967-d5b77d80-0074-11ea-8a1f-9d3d618aa881.png) it looks to me as the one I mentioned [above](https://github.com/mozilla/addons-frontend/issues/8837#issuecomment-551856504).

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. I'm not sure exactly what the issue is that you are reporting. It sounds like the page looks different on MacOS vs. Windows, but maybe that's to be expected? Do other pages from other sites also look different on MacOS vs. Windows? What about other pages on AMO?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Nevermind, it's a general issue on AMO. It's a different display resolution on 2 different devices. 
This is verified on dev with FF70(Win10).
