### ISSUE TITLE
404 page layout is broken for out of reach search results

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#8851]
### Describe the problem and steps to reproduce it:
1. Perform a blank search from AMO homepage
2. Modify the page query in the URL to an out of reach value - i.e. https://addons.mozilla.org/en-US/firefox/search/?page=19284
3. Notice the page layout

### What happened?
A new AMO page is opened inside the main AMO page - the `Page-amo` class is duplicated when inspecting the page HTML

### What did you expect to happen?
No layout issues

### Anything else we should know?
- so far, I could reproduce the issue only with out of reach search pages
- reproduced on all AMO servers with Fx70, WIn10x64

![2019-10-29_15-27-24](https://user-images.githubusercontent.com/31961530/67772776-54a02b00-fa63-11e9-8c0a-565f2644cc4a.png)

**Comment by bobsilverberg** [comment]
This should be fixed when we fix https://github.com/mozilla/addons-frontend/issues/8744, but it's worth leaving this open as a good repro case.

**Comment by bobsilverberg** [comment]
This was fixed via https://github.com/mozilla/addons-frontend/pull/8858

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

https://addons-dev.allizom.org/en-US/firefox/search/?page=1191
![image](https://user-images.githubusercontent.com/31961530/68131681-1fde1900-ff26-11e9-9a75-1e68aa4097ce.png)
