### ISSUE TITLE
"Last Updated" section should use current version created date instead

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#8861]
The `last_updated` property returned by the API for add-ons is updated for both unlisted and listed versions (there was an [addons-server bug about it](https://github.com/mozilla/addons-server/issues/6929), but it turned out to have been changed in the past on purpose), so it's not a good fit for the frontend.

Instead, the frontend should use the `created` or `reviewed` date of the `current_version`.

For QA:

- The "Last updated" in the "More information" card on the Add-on Detail page should use the `created` date of the current version (which is based on the corresponding `file` of `addon.current_version`), as opposed to the `last_updated` date of the `addon`.
- The Add-on Detail page should include a `last-modified` meta tag which uses the same date as "Last updated" as described above.

**Comment by bobsilverberg** [comment]
@diox I know you and @eviljeff have been discussing the whole `last_updated` issue in IRC. Where do we currently stand wrt which data frontend should be using to display "Last Updated" to users?

**Comment by eviljeff** [comment]
iirc, the `current_version` date - although we don't explicitly expose that.  `current_version.files[0].created` should be okay instead.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on dev with FF70(Win10).
- `Last Updated` from "More information" card was updated to the date of the last version submitted and approved for an extension and a static theme. 

![Last updated](https://user-images.githubusercontent.com/33448286/68392273-1cd76880-0172-11ea-8467-ed34e5e7ec48.png)
