### ISSUE TITLE
Allow for more than 2 branches in withExperiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8864]
This supports #8760 

The experiment detailed in #8760 requires 4 branches:
1. Users who will see the new warning (20%)
2. Users who will see the old old warning (20%)
3. Users who will see no warning (%20)
4. Users who will see no warning and are not in the experiment and therefore their results will be ignored in the analysis (40%)

This will actually be 3 experiment branches and one special `notInExperiment` branch for the last group, but I think the last group needs special handling because of the enrollment event that was added in https://github.com/mozilla/addons-frontend/commit/0b4b90eb7c5c6bfe8cd8cb74dc08b195cd4ca5a1, which we will not want to dispatch for the last group.

Currently the code in `withExperiment` only supports 2 branches for an experiment, so the code needs to be updated to support any number of branches, as well as a section of the population that will be excluded from the experiment.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Can you add some str for qa? 
The old A/B experiment for non -recommended add-ons had a cookie and 2 cohorts. On 10 new profiles - the message is no longer available and the cookie won't be displayed anymore. 

Issue https://github.com/mozilla/addons-frontend/issues/8760 says about a new warning and links to the platform warnings https://mozilla.invisionapp.com/share/7UU864JXYRK#/screens/387093697_addons-Messaging-Platforms
