### ISSUE TITLE
Dismiss button `x` should be centered on small android devices 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8867]
As discussed https://github.com/mozilla/addons-frontend/issues/8701#issuecomment-547975893

STR:
On a mobile device load the following page https://addons.allizom.org/en-US/firefox/

Expected result:

 Observe that the `X` button available for the yellow message " To find add-ons compatible with Firefox on Android, [visit our mobile site](https://addons.allizom.org/en-US/android/)" could be in the middle of the yellow message. 

Actual result:
Right now it is situated on the upper right side . 

![X button](https://user-images.githubusercontent.com/33448286/67935026-b67ea300-fbd1-11e9-8ac5-08b83c9548c8.png)

**Comment by kumar303** [comment]
The X is meant to be aligned at the top to strike a balance with the icon. This is how multi-line message bars are spec'd, see https://design.firefox.com/photon/components/message-bars.html
