### ISSUE TITLE
Encapsulate common error page styles

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8873]
Several error page components share styles for common layout. 

As an example, notice how [`NotAuthorized`](https://github.com/mozilla/addons-frontend/blob/4c6510613847ec4e32875b40922cf47caa6b36d4/src/amo/components/ErrorPage/NotAuthorized/index.js) adds an [`ErrorPage`](https://github.com/mozilla/addons-frontend/blob/4c6510613847ec4e32875b40922cf47caa6b36d4/src/amo/components/ErrorPage/NotAuthorized/index.js#L38) class name which is defined in [a different directory](https://github.com/mozilla/addons-frontend/blob/4c6510613847ec4e32875b40922cf47caa6b36d4/src/amo/components/ErrorPage/styles.scss). (https://github.com/mozilla/addons-frontend/pull/8858/ moved these files around and maybe renamed the class.)

This is risky because it would be easy to break these styles or use the wrong class name without knowing it.

This should be fixed by wrapping each error component in a common base component that sets the styles locally.

**Comment by Kiraeraser** [comment]
I want to work on this issue

**Comment by kumar303** [comment]
Hi @Kiraeraser, thanks for your interest. Feel free to work on this. Typically we only open up issues having the [good first bug](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug) or [contrib: welcome](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20welcome) labels and this didn't have one. However, I added `contrib: welcome` to this issue just now.

**Comment by atiqueahmedziad** [comment]
@Kiraeraser are you still working on it ? Or I want to pick it.

**Comment by wagnerand** [comment]
@atiqueahmedziad Feel free to do it!

**Comment by atiqueahmedziad** [comment]
Okay working on it! 😄

**Comment by ioanarusiczki** [comment]
@bobsilverberg Please add some STR for QA
Thanks!

**Comment by bobsilverberg** [comment]
> @bobsilverberg Please add some STR for QA
> Thanks!

Done! Added to the description.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I don't see any layout issues or broken links for a 404 and 500. 

Verified on AMO dev with FF76(Win10).
