### ISSUE TITLE
2ip add-on for Firefox. This page was not found

### ISSUE THREAD

**Issue by valentinych2012** [mozilla/addons-frontend#8875]
I wanted to download a plugin for mozilla firefox. 
To do this, click on the link from the site https://2ip.ru/toolbar/
This page was not found - https://addons.mozilla.org/ru/firefox/addon/2ipservices/

**Comment by muffinresearch** [comment]
We are unable to provide support for individual add-ons.

This issue tracker is only for issues related to the https://addons.mozilla.org (AMO) website and related services.  

In this case the add-on is no-longer available, the best way to get the add-on updated is to ask the original developer.
