### ISSUE TITLE
MDN docs link to unavailable extension "QR Code Image Generator"

### ISSUE THREAD

**Issue by dpathakj** [mozilla/addons-frontend#8876]
The page https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/What_are_WebExtensions links to https://addons.mozilla.org/en-US/firefox/addon/qr-code-image-generator, which 404s ("If you’ve followed a link from another site for an extension or theme, that item is no longer available.").

**Comment by muffinresearch** [comment]
Thanks that link has been removed.
