### ISSUE TITLE
Theme previews not loading on user profile page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-frontend#8881]
Pam (one of our theme reviewers) noticed that theme previews are not loading from a user's profile page: 

![profilepage](https://user-images.githubusercontent.com/23342476/68143457-53994e80-fee6-11e9-95cc-7aff96261f23.jpg)

**Comment by willdurand** [comment]
Looks like one of the patches that removed LWT related code introduced a bug. This is fixed in `master` since there is no LWT code anymore.. This issue will be fixed on Thursday.
