### ISSUE TITLE
Update Firefox logo to the Skyline style

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8884]
Update the Firefox logo in the header (see https://bugzilla.mozilla.org/show_bug.cgi?id=1582891#c4), as part of a larger Skyline rebranding effort. The Skyline branding landed in Firefox 70.

**For QA**: There should be no regressions in the header layout aside from the new logo and wording.

**Comment by ioanarusiczki** [comment]
@kumar303 I verified the new logo + text on AMO dev with FF70(Win10) and FF68.2.0 (Android 8.0). 

All looks good as shown by the [pull request](https://github.com/mozilla/addons-frontend/pull/8885#issue-336481901)

On a mobile phone maybe it could be a little more space between the search bar - the logo + "Firefox Browser ADD-ONS" and the Menu Bar. If you agree, I could file an issue. 

![new logo](https://user-images.githubusercontent.com/33448286/68215569-25039c80-ffe8-11e9-9963-d3269ec84281.png)

**Comment by kumar303** [comment]
> On a mobile phone maybe it could be a little more space between the search bar - the logo + "Firefox Browser ADD-ONS" and the Menu Bar. If you agree, I could file an issue.

I was thinking about this as well but I took some measurements and the spaces are proportionate with the existing mobile layout so I think we should leave it for now. In https://bugzilla.mozilla.org/show_bug.cgi?id=1582891 we will be doing bigger layout changes so it's probably best to wait for that.

**Comment by ioanarusiczki** [comment]
@kumar303 Alright, then this issue is verified on AMO dev with FF70(Win10) and Android 8.0 (FF68.2.0).
