### ISSUE TITLE
Site banner is misaligned for centered text heros

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#8886]
### Describe the problem and steps to reproduce it:

* Open your browser window as wide as possible.
* Refresh the home page on dev (so you get a site banner) until you see a centered text-hero. The other image-based heros will not reproduce the issue.

### What happened?

Look at the left and right edges of the site banner. They do not line up with the left and right edges of the page.

Here's an example of the misalignment:

<details>
<summary>Screenshot</summary>
<img width="2029" alt="Screenshot 2019-11-04 15 21 47" src="https://user-images.githubusercontent.com/55398/68159812-1d74c280-ff18-11e9-907a-616fe24c1838.png">

</details>

When resizing to a fluid breakpoint, the site banner is correctly aligned:

<details>
<summary>Screenshot</summary>
<img width="1215" alt="Screenshot 2019-11-04 15 22 08" src="https://user-images.githubusercontent.com/55398/68159851-32e9ec80-ff18-11e9-842b-63eabdad89a6.png">

</details>

When viewing an image based hero at any browser width, the site banner is correctly aligned:

<details>
<summary>Screenshot</summary>
<img width="2029" alt="Screenshot 2019-11-04 15 21 22" src="https://user-images.githubusercontent.com/55398/68159893-48f7ad00-ff18-11e9-853a-cc6eabb0181e.png">

</details>

### What did you expect to happen?

Everything on the page should be aligned at the same left / right edge.

### Anything else we should know?

I noticed this while working on https://github.com/mozilla/addons-frontend/pull/8885 and I confirmed that it is not related to the new logo.

**Comment by ioanarusiczki** [comment]
@kumar303 Looks good to me on dev with FF70(Win10). 

![site banner centered](https://user-images.githubusercontent.com/33448286/68480166-d69b0b80-023c-11ea-99d2-f7bb30a7eb40.png)
