### ISSUE TITLE
Remove the dismiss button from WrongPlatformWarning

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8904]
Following up on the discussion started at https://github.com/mozilla/addons-frontend/pull/8897#issuecomment-551111862, it has been suggested that we should remove the dismiss button from the warnings that are displayed both at the top of the page, and also on the add-on detail page which warn users that they are on the "wrong" site.

As this is a change from how it was initially implemented, I'd like to get product's sign off on this.

What say you, @jvillalobos?

Examples of what it currently looks like:

![Screenshot 2019-11-07 14 14 58](https://user-images.githubusercontent.com/142755/68419838-ffea6780-0168-11ea-8464-2c8ff0f3d0c6.png)

![Screenshot 2019-11-07 14 15 52](https://user-images.githubusercontent.com/142755/68419905-21e3ea00-0169-11ea-9299-05b1fbdf14f3.png)

**Comment by jvillalobos** [comment]
Removing the button is okay with me. I agree that the concept of "sessions" can be confusing to users. Our previous red sign was also permanent and it hasn't been a problem for users.

**Comment by ioanarusiczki** [comment]
@bobsilverberg `X` is no longer available on the platform warning message. 
Verified on dev with FF70(Win10). 

![no more `x`](https://user-images.githubusercontent.com/33448286/68752419-f4d18480-060b-11ea-81c2-9d704f09c05c.png)

![removing the `x`](https://user-images.githubusercontent.com/33448286/68752446-fb5ffc00-060b-11ea-90be-d4be2135b860.png)
