### ISSUE TITLE
Circleci Integration tests are failing during setup

### ISSUE THREAD

**Issue by jrbenny35** [mozilla/addons-frontend#8910]
This is the log I could get from ssh'ing into the circleci containers.
```
circleci@default-9076bcbc-1364-4121-86e4-42704070d297:~/addons-frontend/addons-server/tests/ui$ docker-compose logs web
Attaching to addons-server_web_1
web_1              | Traceback (most recent call last):
web_1              |   File "/deps/bin/supervisord", line 8, in <module>
web_1              |     sys.exit(main())
web_1              |   File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 358, in main
web_1              |     go(options)
web_1              |   File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 368, in go
web_1              |     d.main()
web_1              |   File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 70, in main
web_1              |     self.options.make_logger()
web_1              |   File "/deps/lib/python3.6/site-packages/supervisor/options.py", line 1472, in make_logger
web_1              |     backups=self.logfile_backups,
web_1              |   File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 417, in handle_file
web_1              |     handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
web_1              |   File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 213, in __init__
web_1              |     FileHandler.__init__(self, filename, mode)
web_1              |   File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 160, in __init__
web_1              |     self.stream = open(filename, mode)
web_1              | PermissionError: [Errno 13] Permission denied: '/code/logs/supervisord.log'
circleci@default-9076bcbc-1364-4121-86e4-42704070d297:~/addons-frontend/addons-server/tests/ui$ docker-compose logs worker
Attaching to addons-server_worker_1
worker_1           | Traceback (most recent call last):
worker_1           |   File "/deps/bin/supervisord", line 8, in <module>
worker_1           |     sys.exit(main())
worker_1           |   File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 358, in main
worker_1           |     go(options)
worker_1           |   File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 368, in go
worker_1           |     d.main()
worker_1           |   File "/deps/lib/python3.6/site-packages/supervisor/supervisord.py", line 70, in main
worker_1           |     self.options.make_logger()
worker_1           |   File "/deps/lib/python3.6/site-packages/supervisor/options.py", line 1472, in make_logger
worker_1           |     backups=self.logfile_backups,
worker_1           |   File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 417, in handle_file
worker_1           |     handler = RotatingFileHandler(filename, 'a', maxbytes, backups)
worker_1           |   File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 213, in __init__
worker_1           |     FileHandler.__init__(self, filename, mode)
worker_1           |   File "/deps/lib/python3.6/site-packages/supervisor/loggers.py", line 160, in __init__
worker_1           |     self.stream = open(filename, mode)
worker_1           | PermissionError: [Errno 13] Permission denied: '/code/logs/supervisord-celery.log'
```

Looking in those folders there is not a file made with those file names.

**Comment by jrbenny35** [comment]
I suspect it is related to this, https://github.com/mozilla/addons-server/pull/12579. Seems that the `user: olympia` is now the default user but if that user does not exist, the required files won't be created. I also ran into this problem trying to build the dockerfile from source.

@EnTeQuAk any thoughts here?

**Comment by EnTeQuAk** [comment]
> I suspect it is related to this, mozilla/addons-server#12579. Seems that the user: olympia is now the default user but if that user does not exist, the required files won't be created. I also ran into this problem trying to build the dockerfile from source.

That's confusing, that user gets created during build - https://github.com/mozilla/addons-server/blob/master/Dockerfile#L83-L84 and I'm pretty certain the build on dockerhub also has this information.

This patch has landed some ~20 days ago, can we somehow make sure that we do have the latest images pulled?

**Comment by EnTeQuAk** [comment]
When building the image locally, you need additional args:

```bash
$ docker build --build-arg GROUP_ID=$(id -g) --build-arg USER_ID=$(id -u) -t addons/addons-server:latest .
```

(ignore the `-t` tag if needed). I haven't come around to documenting the whole process yet unfortunately but I want to have circleci build the image automatically eventually.

Maybe that helps?

**Comment by jrbenny35** [comment]
Regarding that Dockerfile, what exact user is added from useradd? If it is built on circleci, would that user id match when the file is pulled? Maybe the solution is to enforce a build in the docker-compose file.

**Comment by jrbenny35** [comment]
Here is a recent run: https://circleci.com/gh/mozilla/addons-frontend/18204, seeoms to still be having permission problems.

**Comment by EnTeQuAk** [comment]
> Regarding that Dockerfile, what exact user is added from useradd? If it is built on circleci, would that user id match when the file is pulled? Maybe the solution is to enforce a build in the docker-compose file.

The user is named `olympia` and when building the image the `--build-arg`'s are ensuring permissions during the image build (which isn't automated at this moment for addons-server) - for running the local user/group ids aren't quite as important.

Then we're using the `--user` option in docker-compose to actually use that user when running the images: https://github.com/mozilla/addons-server/blob/master/docker-compose.yml#L28

So, in theory, when using `docker-compose` (which we are) should just do it… so I'm not sure what's not working on circleci, hmm…

> Maybe the solution is to enforce a build in the docker-compose file.

That will make things harder for local development unfortunately and imo shouldn't change things or at least won't fix anything.

As I said earlier, do we maybe have some cached files inside the `logs/` folder that gets stored between runs so that we run into permission issues? For a completely clean run we shouldn't run into issues.

**Comment by jrbenny35** [comment]
I don't think the circleci user has permission to make directories and such. If it can't download and install a package without ```sudo``` then it can't make a directory. Right now the dockerfile is assuming that whatever user is running the commands has full access to the system, and I know that the user that runs circleci commands does not.

**Comment by jrbenny35** [comment]
So it looks like the user that runs circleci jobs has a UID of 1001, the docker image uses UID 1000. Could that be a problem? I don't know if root user within circleci is UID 1000, but it shouldn't be.

**Comment by jrbenny35** [comment]
The user with UID 1000 is named ```ubuntu```. I can switch to it but it doesn't have any access to dependencies installed by circleci.

**Comment by jrbenny35** [comment]
@EnTeQuAk would it be too much to create a user named ```circleci``` and just have a tagged ```:circleci``` image? If we can have one with a UID that matches I think that solves our problems.

**Comment by EnTeQuAk** [comment]
You could try to use the `--user=circleci` option on the docker-compose command that you're running (and that is failing) first - as that overwrites the user option in the dockerfile. The uuid I'm building the image with doesn't matter as much for actually running it.

**Comment by jrbenny35** [comment]
From reading thishttps://medium.com/@mccode/understanding-how-uid-and-gid-work-in-docker-containers-c37a01d01cf, the UID that gets assigned to a user has the same permissions as whatever the UID is outside of the image. So in our case, ```UID=1001``` is a user within the circleci build that does not have permissions to create directories and such.

I'll give that flag a try as well.

**Comment by jrbenny35** [comment]
Trying the user flag:
```
circleci@default-a42b7b5d-26b1-4236-bc47-66e5309c1d69:~/addons-frontend$ docker-compose -f addons-server/docker-compose.yml -f addons-server/tests/ui/docker-compose.selenium.yml -f tests/ui/docker-compose.functional-tests.yml run --user circleci web

Error response from daemon: linux spec user: unable to find user circleci: no matching entries in passwd file
```

**Comment by jrbenny35** [comment]
@EnTeQuAk I just tried your local command suggestion, ```docker build --build-arg GROUP_ID=$(id -g) --build-arg USER_ID=$(id -u) -t addons/addons-server:latest .``` and that worked. Would it be too much to have a circleci image? I know I could have a local build within the CI run but that would just add time...

**Comment by jrbenny35** [comment]
Maybe I spoke too soon,
```
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/deps/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/deps/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/deps/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/deps/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 114, in collect
    handler(path, prefixed_path, storage)
  File "/deps/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 352, in copy_file
    self.storage.save(prefixed_path, source_file)
  File "/deps/lib/python3.6/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/deps/lib/python3.6/site-packages/django/core/files/storage.py", line 242, in _save
    os.makedirs(directory)
  File "/usr/local/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/code/site-static/css'
Makefile-docker:139: recipe for target 'update_assets' failed
```
