### ISSUE TITLE
How to update site icons hlp page useless

### ISSUE THREAD

**Issue by lucky06480** [mozilla/addons-frontend#8916]
On URL help page https://support.mozilla.org/en-US/questions/1014960 link to faviconreloader does not exist. So, this page is useless (no solution)

**Comment by willdurand** [comment]
I am going to close this issue because it is not directly related to AMO but ping @caitmuenster to see if you can do anything about it.

**Comment by caitmuenster** [comment]
Hey there @lucky06480, thanks for the report. It looks like that thread has been archived on the support forums. You might want to open a new thread in the forums for more updated information.
