### ISSUE TITLE
Link from Radial Insight's page to their addon page doesn't work

### ISSUE THREAD

**Issue by MacPhyle** [mozilla/addons-frontend#8917]
### Anything else we should know?

![Screen Shot 2019-11-09 at 3 25 14 PM](https://user-images.githubusercontent.com/1409655/68536283-3826ad00-0305-11ea-9e26-7cf0b22ad6a6.png)
![Screen Shot 2019-11-09 at 3 25 23 PM](https://user-images.githubusercontent.com/1409655/68536284-3826ad00-0305-11ea-9e3d-501790a164ac.png)

**Comment by willdurand** [comment]
Hi, I recommend contacting the developers of this extension.
