### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by Elyssa523** [mozilla/addons-frontend#8921]
### Describe the problem and steps to reproduce it:

https://addons.mozilla.org/en-US/firefox/addon/autopagerizeadvanced/?src=search
link broken to
https://addons.mozilla.org/en-US/firefox/addon/autopagerize/?src=search

### Anything else we should know?

see above

**Comment by jvillalobos** [comment]
That add-on is no longer available. It's up to the developers to bring it back if they choose to.
