### ISSUE TITLE
Use a new id for the new A/B test experiment

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8922]
The cookie generated for an experiment using `withExperiment` is based on the `id` of the experiment. Therefore, any time we start up a new experiment, the experiment should be assigned a new, unique, `id`. If we do not do that then users enrolled in the previous experiment will not receive a new cookie and will remain in the branch from the previous iteration.

I'm not sure what we can do to ensure that every new experiment (or iteration thereof) receives a unique `id` (other than be careful about it), but for now we need to make sure that the `id` for the experiment about to be released is at least unique from the one conducted back in September.

One mitigating factor for having to make sure that all experiments receive unique `id`s is the fact that experiment cookies expire after 6 months, so we don't necessarily need to be concerned about `id`s from experiments that are more than 6 months old.

For QA:

Any cookies generated for this experiment should have the name `installButtonWarning2Experiment`, whereas cookies created for the previous iteration would have the name `installButtonWarningExperiment`.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified this on dev with FF70(Win10). 
- on a new profile the cookie's name is `installButtonWarning2Experiment`

![new profile](https://user-images.githubusercontent.com/33448286/68748059-6d344780-0604-11ea-877a-8571351ad7c7.png)

- on a profile with the old cookie, a new cookie is generated.  Both expire in a month but I see that the profile respects the rules given by the new cookie `installButtonWarning2Experiment`
![new cookie on old profiles](https://user-images.githubusercontent.com/33448286/68748165-981e9b80-0604-11ea-923b-452b217f7441.png)

I think it should be fine. If it's not, let me know.
