### ISSUE TITLE
Use FF abuse report panel for extensions and static themes only

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8929]
From https://github.com/mozilla/addons-frontend/issues/8762#issuecomment-553398639:

> As an additional side note related to this, the integrated abuse report panel currently support only extension and themes (e.g. we do only have abuse categories and related localized descriptions only for these two kind of addons), and so currently it is going to refuse to create an abuse report panel for langpacks, dictionaries and search tools.

**For QA:** the FF abuse report should be opened for extensions and static themes only. (Note: there is a unrelated network problem mentioned in https://github.com/mozilla/addons-frontend/issues/8762 that might prevent the panel to be opened but it needs to be fixed in FF)

**Comment by ioanarusiczki** [comment]
@willdurand On FF72(Win10) from a detail page:
- `Report this add-on for abuse` for an extensions opens the new FF abuse report panel. (as I mentioned in https://github.com/mozilla/addons-frontend/issues/8762#issuecomment-553377660)

- for static themes the old form is available ( https://github.com/mozilla/addons-frontend/issues/8931 is open)

![old form for themes](https://user-images.githubusercontent.com/33448286/68841143-be0f7300-06cc-11ea-9080-c7baff96b80c.gif)

- for search tools, dictionaries and lang packs the old form is available too 

![the others](https://user-images.githubusercontent.com/33448286/68841329-1fcfdd00-06cd-11ea-8ec8-2b2ee6c97668.gif)


This should be verified after  https://github.com/mozilla/addons-frontend/issues/8931lands.
