### ISSUE TITLE
Enable abuse report in FF for static themes

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8931]
This is currently not possible because of an issue in FF, see: https://github.com/mozilla/addons-frontend/issues/8762#issuecomment-553430081

**For QA:** assuming all the prefs are correct, one should be able to open the FF abuse report panel on a statictheme product page.

**Comment by bobsilverberg** [comment]
> Bugzilla bug: [bugzilla.mozilla.org/show_bug.cgi?id=1596133](https://bugzilla.mozilla.org/show_bug.cgi?id=1596133)

This has been verified fixed in beta for 71. I think that means we can now add support back in for static themes. Is that correct @rpl? Are there any versions of Firefox in the wild that support the new `reportAbuse` API but do not contain this fix for `statictheme`?

**Comment by rpl** [comment]
> > Bugzilla bug: [bugzilla.mozilla.org/show_bug.cgi?id=1596133](https://bugzilla.mozilla.org/show_bug.cgi?id=1596133)
> 
> This has been verified fixed in beta for 71. I think that means we can now add support back in for static themes. Is that correct @rpl? 

Correct, the fix was pretty small and low risky, and so I requested an uplift to beta for it.

> Are there any versions of Firefox in the wild that support the new `reportAbuse` API but do not contain this fix for `statictheme`?

Nope, 71 is the version were the mozAddonManager.reportAbuse method has been landed.

**Comment by bobsilverberg** [comment]
Thanks Luca!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev with beta 71 and Nightly 72.

Static themes are now going through the new Firefox abuse report method:

![image](https://user-images.githubusercontent.com/31961530/69636751-f5ccd200-105f-11ea-9b94-e3f6f7489ce6.png)
