### ISSUE TITLE
Display of "Cookies" link jumps to page footer on Android

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/addons-frontend#8934]
### STR:
1. From any AMO page, scroll to the page footer.
2. Click on the "Cookies" link.

### Expected result:
The "Websites, Communications & Cookies Privacy Notice" page opens on the cookies page information.
### Actual result:
The "Websites, Communications & Cookies Privacy Notice" page opens on the page footer.

### Notes:
Reproduced on all AMO servers with an Android 8.0.0 small device.
 On Win10 the "Cookies" link displays the page as intended. (2nd gif)

![videotogif_2019 11 14_16 57 32](https://user-images.githubusercontent.com/54401091/68865607-c7640400-06fb-11ea-94af-be5d5b71797a.gif)

![2](https://user-images.githubusercontent.com/54401091/68865629-d0ed6c00-06fb-11ea-99fc-e72a26af27a5.gif)

**Comment by muffinresearch** [comment]
It's odd that it works like this, that fragment id doesn't appear to exist in the linked page AFAICT. Maybe it used to? I think the easiest solution is to remove the `#cookies` part of the url as that seems to then work as expected.

**Comment by rbrishabh** [comment]
Hey! Can I take this up? @muffinresearch

**Comment by muffinresearch** [comment]
> Hey! Can I take this up? @muffinresearch

Go for it 👍

**Comment by jvillalobos** [comment]
Mentor: @muffinresearch

**Comment by caitmuenster** [comment]
Hey @rbrishabh, how's it going with this bug?

**Comment by rbrishabh** [comment]
My bad. I totally forgot about this one! Working on this right away!

**Comment by stringtheory1234** [comment]
https://github.com/mozilla/addons-frontend/pull/9062 tries solving this issue by removing #cookies. Please review and let me know as I am new to open source.

**Comment by stringtheory1234** [comment]
Why is it showing 2 test failed ?

**Comment by stringtheory1234** [comment]
https://github.com/mozilla/addons-frontend/pull/9066 please let me know if there is some mistake.

**Comment by stringtheory1234** [comment]
what does it mean by : Merging #9066 into master will not change coverage.
The diff coverage is n/a.

**Comment by alexandra-martin** [comment]
Verified in Amo-dev with FF68.4 (Android 8.0.0).

![videotogif_2020 01 08_15 15 33](https://user-images.githubusercontent.com/54401091/71978287-9697db00-3223-11ea-8c4f-6b4d1dc70334.gif)
