### ISSUE TITLE
nobias.com to Firefox deadend

### ISSUE THREAD

**Issue by lgekeler** [mozilla/addons-frontend#8935]
### What were you doing?
I clicked on the "+Add to Firefox" link at the top of https://nobias.com which resulted in a 404.

### What did you expect to happen?
I expected to be able to install the nobias add on to Firefox.

### Anything else we should know?
Nope

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
