### ISSUE TITLE
Avast SecureLine VPN Web Extension

### ISSUE THREAD

**Issue by JohnFreeman13091939** [mozilla/addons-frontend#8936]
I use Avast VPN to add to my web surfing safety.  Today they offered me this add on to the VPN functionality.  
Clicking the link button took me to a web page
https://addons.mozilla.org/en-US/firefox/addon/avast-secureline-vpn/ 
whose text opened with the line liner 'Oops! We can't find that page.  Rest of the text read: -
"If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes.

I expected that as a result I would e able to control the VPN App from within the Firefox browser 70.0.1 (up to date).  Nothing happened bar what I have recorded here

John Freeman

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
