### ISSUE TITLE
Hide "for Android" section when there is no link for it

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#8940]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-dev.allizom.org/en-US/android/
2. Open the "More..." menu item

### What happened?

You see this:

![](https://user-images.githubusercontent.com/33448286/68946044-a6aeb380-07ba-11ea-83d5-b23f9420c3fb.png)

### What did you expect to happen?

The "for Android" section/title should not appear because there is no link below it.

**Comment by softvision-danielorban** [comment]
@willdurand 
The "for Android" section/title is not displayed anymore.
Issue verified on dev with FF 70.0.1 (Win10/64-bit); FF 68.2.0 (Android 8.0).
Screen capture attached:
![android link](https://user-images.githubusercontent.com/43445968/69057145-048d0680-0a1a-11ea-9802-461c2f0f1ea9.png)
