### ISSUE TITLE
Nectar notifer

### ISSUE THREAD

**Issue by ckemball** [mozilla/addons-frontend#8944]
### Describe the problem and steps to reproduce it:

Tried to get to Nectar Notifier from the Nectar website.  Click the Add to Browser (as instructed) https://addons.mozilla.org/en-US/firefox/addon/nectar-browser-add-on/

Error message - Oops! We can’t find that page

given access to a new browser

### Anything else we should know?
Did a search for Nectar Notifier using Google Click the link and had the same response.

**Comment by jvillalobos** [comment]
It's up to the developers to update the add-on and bring the listing page back up. Please contact them for help.
