### ISSUE TITLE
Sticky Password Add-in Not found

### ISSUE THREAD

**Issue by sb8301450** [mozilla/addons-frontend#8948]
When attempting to add stickypasswords extension I get:

Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes.

This is the URL that sent me to the issue:

https://www.stickypassword.com/extension-installation-windows-firefox?action=extension-win-firefox&btn=&lng=en-US&ose=WIN%2F10&build=SP%2F8.2.3.24&stickyid=c6894045ee28abadc834960b61e1e7a4&licstat=FULL&id=519fa555-77b8-46ab-a903-e97d7a2d16d3&packageid=&licprod=single&teamadm=false&extensionId=%7Becb80162-dfbd-4d91-a8da-17b35ba4707a%7D

**Comment by willdurand** [comment]
As stated in the page you quote, the developer likely removed their extension. There is nothing we can do, so I would suggest to get in touch with the developer instead.
