### ISSUE TITLE
Images - resizing the browser the images look larger or smaller depending on the lenght of the custom description

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#8949]
Followup for https://github.com/mozilla/addons-server/issues/12818

STR:
1. Load AMO dev and check the homepage - images were added for the primary hero shelf 
2. Resize the browser and observe the image

![AMO dev layout](https://user-images.githubusercontent.com/33448286/69147568-f2bf6800-0ada-11ea-952b-ae50a100a730.png)

3. Load AMO stage and check the hompeage - the testing placeholders are available for some add-ons
4. Resize the browser and observe the placeholders

![layout on AMO stage](https://user-images.githubusercontent.com/33448286/69147651-2ef2c880-0adb-11ea-9fc1-0bc66b181ddf.png)

I can't tell which would be the expected result (or which looks better). In my opinion, the size on AMO dev is a bit too large and the one from stage looks too small. 

I verified this issue with FF70(Win10).

**Comment by ioanarusiczki** [comment]
Testing this again on stage I've noticed that the size of the images when the browser is resized also depends on the length of the text which is next to it. If there's a longer description, the image gets smaller. 
This is reproducible only when the browser is resized. 

on stage  
![the images have different sizes](https://user-images.githubusercontent.com/33448286/69240674-ab51de00-0ba5-11ea-9702-d070ad851aa3.gif)

on dev - the same addon with more text added to the right side of the image 

![same addon with more text](https://user-images.githubusercontent.com/33448286/69241775-27e5bc00-0ba8-11ea-8f09-8c8006668e2a.gif)

**Comment by bobsilverberg** [comment]
@ioanarusiczki I had a bit of trouble understanding exactly what problem you are describing, but I think I figured out at least a part of it.

It looks like the primary hero image is changing its size, on smaller screens, depending on how much text there is in the area to the right of it. I agree that seems sub-optimal, so I have written a patch to address that, which is at https://github.com/mozilla/addons-frontend/pull/9015

**Comment by ioanarusiczki** [comment]
@bobsilverberg Thanks for looking into this. I think it's better as it looks now. 
Verified on dev with FF71(Win10). 

![same size](https://user-images.githubusercontent.com/33448286/70627597-2cddde80-1c2f-11ea-9ee5-2894b090bf67.gif)
