### ISSUE TITLE
Charless Autoconfiguration Addon for Firefox

### ISSUE THREAD

**Issue by aruvimal** [mozilla/addons-frontend#8950]
### Describe the problem and steps to reproduce it:
I'm trying install Charles proxy addon, it says, Please browser to http://charlesproxy.com/firefox in Firefox browser to install. But when trying this addon, it seems like it has been removed . please advise. 

### What happened?
Charles Proxy Addon - http://charlesproxy.com/firefox is not available for firefox
### What did you expect to happen?
Charles Proxy Addon should be available.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
