### ISSUE TITLE
INSTALLING ADDON FOR STICKY PASSWORD

### ISSUE THREAD

**Issue by ZAGOR52** [mozilla/addons-frontend#8951]
While completeing Sticky Password installation I was requested to install Firefox addon to manage automatically the passwords.(this site: https://www.stickypassword.com/extension-installation-windows-firefox?action=extension-win-firefox&btn=&lng=en-US&ose=WIN%2F10&build=SP%2F8.2.3.24&stickyid=2e7b983b94dc591799799b568584ff7d&licstat=TRIAL&id=c35e6ac5-d8a3-4702-b4b5-bb681777be7a&packageid=&licprod=single&teamadm=false&extensionId={ecb80162-dfbd-4d91-a8da). 
It appears that there isn't such add-on in Firefox, so I haven't been able to complete the installation.
![Screenshot (3)](https://user-images.githubusercontent.com/57959350/69171345-08915500-0afc-11ea-91af-85f642412ffc.png)
![Screenshot (4)](https://user-images.githubusercontent.com/57959350/69171356-0dee9f80-0afc-11ea-98c1-f07c5d25818d.png)

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
