### ISSUE TITLE
Reduce reports about missing add-ons

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#8952]
Numerous reports keep being filed about missing add-ons, where listing pages respond with a 404 page, including a link to file an issue. This creates some effort when going through the backlog of filed issues or during triage, because those reports are not issues that are actionable.

We should mitigate those reports. A couple of ideas:
* Show a specific 404 page for all `/firefox/addon/` pages, if possible not for sub pages like `/firefox/addon/<SLUG>/reviews/`. The page should remove the link to file an issue and focus on the add-on being unavailable (, which we already have on the page).
* Remove the "file an issue" part from all 404 pages altogether. 404 pages are rarely caused by a bug, usually there is a more suitable response code when things went wrong.

More ideas welcome!

---

**For QA:** we will update the content of the 404 page, please see the gdoc linked in the comments below.

**Comment by jvillalobos** [comment]
Maybe the help link for those 404 pages should be discourse rather than GitHub. At least there's a slim chance someone will help those users find alternatives. /cc @caitmuenster

**Comment by caitmuenster** [comment]
I like the idea of sending them to Discourse. 

@jorgev, should we remove the link to filing an issue on Github altogether from the 404 page? It should be pretty easy to refer any bug reports from Discourse back to Github.

**Comment by willdurand** [comment]
I like the idea of linking to Discourse instead of GitHub. As @jvillalobos suggested, other users might help find alternatives. As @caitmuenster, we can still report bugs from Discourse back to GitHub.

Can one of you suggest an updated content for the 404? Or should we simply change the GitHub link to a Discourse link? If so, which one? Thanks!

**Comment by caitmuenster** [comment]
You bet @willdurand! 

Copy edits are up here: https://docs.google.com/document/d/1iUT4bh4OtS1QnY7WaqdN34ghsiHfIqz0zfGY0sNABv0/edit

/cc @jvillalobos

**Comment by jvillalobos** [comment]
I would remove the paragraph that opens with "If you’ve followed a link on this site". Then, add to the last paragraph "You can also ask for help in our [community forum](https://discourse.mozilla.org/c/add-ons)." @caitmuenster, what do you think?

**Comment by jvillalobos** [comment]
Heh, mid-aired. Pretty much the same thing that's in the doc.

**Comment by ioanarusiczki** [comment]
@wagnerand I checked on AMO dev and for all the frontend pages the 404 looks like the one specified  [above](https://github.com/mozilla/addons-frontend/issues/8952#issuecomment-556152934)

Examples:
https://addons-dev.allizom.org/en-US/firefox/addon/search_by_imagez/?src=recommended_fallback
https://addons-dev.allizom.org/en-US/firefox/addon/search_by_imagez/reviews/
