### ISSUE TITLE
Enable A/B Test on stage/prod

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8955]
This is a follow-up to #8760. It is just a config change to enable the flag for the A/B test on stage and prod for this week's push.

**Comment by ioanarusiczki** [comment]
@bobsilverberg
 
My testing results on AMO stage - I tested with 2 profiles and cleared the cookie 10 and then 20 times:
Profile one: cookie cleared 10 times 
20% will see the new warning includeWarning-proposed 
20% will see the old warning includeWarning-current
60% will not see the warning  excludeWarning +  notInExperiment

Profile two: cookie cleared 20 times 
35% have  the new warning, includeWarning-proposed
10% have the current warming,  includeWarning-current
55% are not in the Experiment (exclude warning or not in Experiment)

It won't be 100% accurate as discussed in https://github.com/mozilla/addons-frontend/issues/8760#issuecomment-552907594 so I think this time the testing results look pretty good. 

Also the GA events are sent when the cookie is in the experiment. For notInExperiment there is no GA enrollment event neither when the add-on is installed.
