### ISSUE TITLE
discovery.addons.allizom.org has failed the web security baseline

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/addons-frontend#8958]
Site https://discovery.addons.allizom.org has failed the web security baseline scan.

The failing tests are:

 Cookie No HttpOnly Flag [10010] x 1 
 * https://discovery.addons.allizom.org/en-GB/firefox/discovery/pane/48.0.1/Linux/normal (200 OK)

 Cookie Without Secure Flag [10011] x 1 
 * https://discovery.addons.allizom.org/en-GB/firefox/discovery/pane/48.0.1/Linux/normal (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=discovery.addons.allizom.org) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by willdurand** [comment]
I suppose it is the cookie for the "install warning 2" A/B experiment. We should set the secure flag but we probably need access to this cookie in the client (so it cannot be http only).

**Comment by muffinresearch** [comment]
@bobsilverberg Is the disco pane actually dropping a cookie for the A/B testing?

**Comment by muffinresearch** [comment]
@bobsilverberg and I discussed this, and came to the conclusion that moving the config should prevent any cookies related to the experiment coming up on the disco pane see https://github.com/mozilla/addons-frontend/issues/8962 for details.

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://discovery.addons.allizom.org now passes - well done team!
