### ISSUE TITLE
Move the experiment config from default.js to default-amo.js

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#8962]
Having the experiment config in `default.js` will enable the experiment on disco pane, which we do not want.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this on AMO stage with FF70(Win10) with Browser Console: 
- I did not see a GA event or cookie set for the AMO experiment on `about:addons` page
- on the same profile after clearing data AMO will receive the experiment cookie and the events such as:
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Experiment Enrollment - installButtonWarning2","eventAction":"includeWarning-proposed"}
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Install Button Warning Experiment - Display","eventAction":"includeWarning-proposed","eventLabel":"All of the permissions"}
[GA: ON] sendEvent {"hitType":"event","eventCategory":"AMO Install Button Warning Experiment - Click-not_recommended","eventAction":"includeWarning-proposed","eventLabel":"All of the permissions"}
