### ISSUE TITLE
Nectar Notifier

### ISSUE THREAD

**Issue by timbo2011** [mozilla/addons-frontend#8968]
### Describe the problem and steps to reproduce it:

I am trying to download the Nectar Notifier from https://www.nectar.com/nectar-notifier?spMailingID=41155626&spUserID=ODg5NDQyOTI2NDc0S0&spJobID=1641852725&spReportId=MTY0MTg1MjcyNQS2

### What happened?

I was transferred to oops page https://addons.mozilla.org/en-US/firefox/addon/nectar-browser-add-on/

### What did you expect to happen?

I expected the download to start

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.

**Comment by timbo2011** [comment]
May be you could make your page more clear then.

 

It intercepted my attempt to download Nectar Notifier and invited me to join!

 
 

Sent: Thursday, November 21, 2019 at 12:47 PM
