### ISSUE TITLE
Sticky Password extension isn't available

### ISSUE THREAD

**Issue by Freedom-Coder** [mozilla/addons-frontend#8970]
### What happened?
I bought a premium license of sticky password manager (https://www.stickypassword.com/) and wanted to install the firefox extension of it. I got redirected from a site (https://www.stickypassword.com/de/erweiterung-installieren-windows-firefox?action=extension-win-firefox&btn=&lng=de-DE&ose=WIN%2F10&build=SP%2F8.2.2.14&stickyid=479ab53b4fd7dac5aeb51b4574aced14&licstat=TRIAL&id=b9beea18-2559-452e-a577-bd4bfc02e3f4&packageid=d-stacks-1346&licprod=single&teamadm=false&extensionId=%7Becb80162-dfbd-4d91-a8da-17b35ba4707a%7D) to this site (https://addons.mozilla.org/de/firefox/addon/sticky-password-extension/). But there is nothing.

### What did you expect to happen?
I expected to install the sticky password extension to use it.

### Anything else we should know?
I think thats all I can say about it.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
