### ISSUE TITLE
Nectar Notifier link to Mozilla doesnt work it has been removed from addons?

### ISSUE THREAD

**Issue by dlgenner43** [mozilla/addons-frontend#8971]
When clicking on the link for Nectar Notifier in Mozilla Firefox is comes up with an error saying the add-on has been removed.

I expected to have an add-on on my toolbar so If I went on websites which support nectar point I
 would receive them.

![Screenshot_2019-11-21 Add-ons for Firefox (en-US)](https://user-images.githubusercontent.com/58043928/69357998-0a832180-0c7e-11ea-932b-0ba2d12449e9.png)

 
https://www.nectar.com/nectar-notifier?spMailingID=41155626&spUserID=ODkyNTYxNDgzNzgwS0&spJobID=1641852725&spReportId=MTY0MTg1MjcyNQS2

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
