### ISSUE TITLE
Sticky password extension not found

### ISSUE THREAD

**Issue by dcb99** [mozilla/addons-frontend#8974]
### Describe the problem and steps to reproduce it:

Trying to install the sticky password extension from the link provided by the sticky password installer

### What happened?
An error was received saying the extension doesn't exist.
### What did you expect to happen?
The stickypassword extension should be available.

**Comment by wagnerand** [comment]
This repository is for the underlying add-ons platform, not individual add-ons listed there. Please contact the author of the add-on for questions about its availability.
