### ISSUE TITLE
firefox extension

### ISSUE THREAD

**Issue by Smith2369** [mozilla/addons-frontend#8981]
Hi,
i just want to state that, i am not able to add "MozRepl" extension in Firefox.
Seems MozRepl is not available now.
So, how can i have that or is there any alternative of MozRepl.
Thank you!

**Comment by jvillalobos** [comment]
You can look for alternatives on https://addons.mozilla.org, or ask in our [community forum](http://discourse.mozilla.org/c/add-ons). This repository is not the right place to ask for it, though.
