### ISSUE TITLE
Enable Sticky Password in Firefox

### ISSUE THREAD

**Issue by Sonicnova111** [mozilla/addons-frontend#8986]
### Describe the problem and steps to reproduce it:
States this addon is not supported 

### What happened?
I was unable to add it onto Firefox as an addon
### What did you expect to happen?
for it to work so I could use it to retrieve my logins and passwords
### Anything else we should know?
Yes I got an email from developers they stated the never took it off of Firefox so there is an error on with Firefox and this addon

https://addons.mozilla.org/en-US/firefox/addon/sticky-password-extension/

**Comment by jvillalobos** [comment]
The issue is being worked out with the developer, and the listing won't be available until the issue is resolved.

**Comment by Sonicnova111** [comment]
Great thanks so much!
