### ISSUE TITLE
Avast Secureline VPN Extension on Mozilla Firefox

### ISSUE THREAD

**Issue by AntClement** [mozilla/addons-frontend#8989]

**Comment by AntClement** [comment]
I can´t install the Avast Secureline vpn on mozilla firefox version 70.0.1 (64 bit).Everytime I try to install appears the mozilla firefox web page saying this: "Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes."
Please What can I do? greetings from Venezuela and forgive me for my bad English

**Comment by jvillalobos** [comment]
Please contact Avast for help getting the extension installed. It sounds like their site has an old link that they need to remove or change.
