### ISSUE TITLE
Adjust text to allow for dev name on blocks

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#899]
**Theme and extension block**
<img width="591" alt="screen shot 2016-08-09 at 9 45 09 am" src="https://cloud.githubusercontent.com/assets/6797635/17525139/526c2b82-5e16-11e6-88ce-e6528b6f4cba.png">

<img width="687" alt="screen shot 2016-08-09 at 9 54 22 am" src="https://cloud.githubusercontent.com/assets/6797635/17525380/4b1aa42a-5e17-11e6-8424-a21f984c5a2e.png">

/* header: */
font-family: HelveticaNeue-Bold;
font-size: 14px;
color: #444444;
letter-spacing: 0px;

/* dev name-normal: */
font-family: HelveticaNeue-Light;
font-size: 10px;
color: #6A6A6A;
letter-spacing: 0px;

/* dev name-hover: */
font-family: HelveticaNeue-Light;
font-size: 10px;
color: #0996F8;
letter-spacing: 0px;

/* secondary copy: */
font-family: HelveticaNeue;
font-size: 12px;
color: #444444;
line-height: 14px;

**Comment by andymckay** [comment]
Can I confirm that the theme author is not a link, but the extension author is a link (presumably to the add-on page on AMO)?

**Comment by pwalm** [comment]
Theme author is also a link, to said author's theme detail.

**Comment by designakt** [comment]
I have one tweak that could go with this:
During user research we discovered that people struggle somewhat to identify that the add-on name is a link. Currently we underline it when hovering the name with no indication that it is a link before a user hovers.
To make it more recognizable as a link we should show the underline already when the user over this add-ons card.

**Comment by pwalm** [comment]
Something like this?
![screen shot 2016-08-10 at 2 36 55 pm](https://cloud.githubusercontent.com/assets/6797635/17572128/ed125926-5f07-11e6-8a3a-773490c6daa6.png)

**Comment by mstriemer** [comment]
This depends on mozilla/addons-server#3261.

**Comment by ValentinaPC** [comment]
Verified on AMO-dev FF48(Win 7 x64)
Author name was added, as follows:
- for add-ons - name and author underlined, turning into blue at hover; if clicked add-on details page is loaded
- for themes -  author underlined, turning into blue at hover; if clicked _theme details page_ is loaded - is this intended? - seems intuitive that if is only the theme author that is underlined the author details page to be displayed.

Please see the video: 
![add-on author](https://cloud.githubusercontent.com/assets/15685960/17730564/de8077ca-6471-11e6-8d78-cb2ca195ebc7.gif)


Please see the video:

**Comment by ValentinaPC** [comment]
@mstriemer : what about my second question? Thanks!

**Comment by mstriemer** [comment]
You're right that does seem a little strange. 

@pwalm is the link supposed to go to theme detail or the author's page?

**Comment by muffinresearch** [comment]
Looking in the thread above - what we have seems to match this comment: https://github.com/mozilla/addons-frontend/issues/899#issuecomment-238671086

> Theme author is also a link, to said author's theme detail.

**Comment by ValentinaPC** [comment]
@muffinresearch : ...and "to said author's theme detail" from that comment means that the theme author link should load author's page? Because if this is true, we should reopen this or log a separate issue. Thanks!

**Comment by muffinresearch** [comment]
To me the "author's theme detail" means the theme detail page, but I it does look like that could be open to interpretation. Irrespective of that it seems a bit odd.

**Comment by muffinresearch** [comment]
I'm re-opening this issue since this is going to production like this today - if it's not doing what's intended then this might be a release blocker.

**Comment by pwalm** [comment]
@ValentinaPC @mstriemer The link on the theme block should go to the theme's detail page. I know it seems a bit incongruous, but it matches the interaction on the extension block link.

**Comment by muffinresearch** [comment]
@pwalm thanks for the clarification. That's what's live so I'll close this.
