### ISSUE TITLE
Avast! VPN Web Extension

### ISSUE THREAD

**Issue by JohnFreeman13091939** [mozilla/addons-frontend#8993]
I responded to Avast! offer of a new  'Web Extension  VPN Web Extension' to their Avast SecureLine VPN service that I already use.  The offer was on Avast! SecureLine VPN.  This was the link: -
https://addons.mozilla.org/en-US/firefox/addon/avast-secureline-vpn/
I expected this to add a Firefox extension to my browser, but instead I got this message from the URL quoted: -
"Oops! We can’t find that page

If you’ve followed a link from another site for an extension or theme, that item is no longer available. This could be because:

    The developer removed it. Developers commonly do this because they no longer support the extension or theme, or have replaced it.
    Mozilla removed it. This can happen when issues are found during the review of the extension or theme, or the extension or theme has been abusing the terms and conditions for addons.mozilla.org. The developer has the opportunity to resolve the issues and make the add-on available again.

If you’ve followed a link on this site, you’ve have found a mistake. Help us fix the link by filing an issue. Tell us where you came from and what you were looking for, and we'll get it sorted.

Try visiting the page later, as the theme or extension may become available again. Alternatively, you may be able to find what you’re looking for in one of the available extensions or themes."

This has happened three times in the last two weeks - and of course I was hoping someone else might notice and fix it! No such luck!
John Freeman

**Comment by kumar303** [comment]
Sorry for the inconvenience but this is not a bug on the addons.mozilla.org site. Please get in touch with Avast via https://support.avast.com/en-us to resolve the issue.
