### ISSUE TITLE
Add To Collection - Cannot search the list

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8996]
### Describe the problem and steps to reproduce it:
When clicking the Add To Collection drop down, there is no way to search the list of collection names in the list (I have over 120, so it is not always easy to find the one I want (or more than one with similar names, different purposes). 

And with the names not sorted, there is no alternative

### What happened?
Unable to type to search the list.  (BUT note, sorting does not replace the need to be able to search the list).

### What did you expect to happen?
To be able to type to search the Add To Collection list, like was possible in the older design of this list.

**Comment by willdurand** [comment]
I don't think we'll be able to provide such a feature, sorry.

**Comment by smayer97** [comment]
May I know what makes this not possible? Is it technically difficult?

**Comment by willdurand** [comment]
It is not technically difficult but it is still quite some work for a feature that will only benefit very few users, including you. That is because the vast majority of users have very few collections.

**Comment by smayer97** [comment]
Thanks for the reply. Please do keep in mind that some of us users with large collections actually support, and therefore impact, larger groups that do not have collections. Just food for thought, if it makes any difference.
