### ISSUE TITLE
A way to see all collections (personal ones) an add-on already exists in.

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8997]
### Describe the problem and steps to reproduce it:
There currently is NO WAY to identify which collections (personal ones) an add-on already belongs to. 

(this was one of the issues as part of the following issues raised here:
https://github.com/mozilla/addons-frontend/issues/4331)

As an alternative, and possibly simpler solution, the following could be implemented:
- under the "**Add to Collection**" section, add a drop down list that can pull up all (personal) collections the add-on already exists in (ideally, listed alphabetically).

The need for this is multiple-fold
- when going to add an add-on to a collection, a simple way to see where it has already been added (saves time and effort)
- provides an easy way to see if an add-on is in the wrong collection and/or needs to be added/removed.

**Comment by willdurand** [comment]
@jvillalobos wdyt?

**Comment by jvillalobos** [comment]
I wouldn't object for the dropdown to indicate if a collection already has the add-on, or to exclude collections the add-on already belongs to.

Having said that, I think it's a very minor improvement that should be weighed against the complexity and performance cost. We don't have many power users for collections, which is why these issues tend to be closed rather than fixed.

**Comment by smayer97** [comment]
Please do keep in mind that currently there is no alternate way to identify where an add-on is stored...that is the dilemma. BTW, I do not believe there would be much of a performance cost if the drop down is only populated when opened (if that is reasonable to do).

Thanks for your consideration.

**Comment by smayer97** [comment]
Still really needed. Please address,

**Comment by smayer97** [comment]
unstale...

**Comment by smayer97** [comment]
awaiting a solution...

**Comment by smayer97** [comment]
unstale
