### ISSUE TITLE
When adding add-on to collection but it already belongs, error message should say which one.

### ISSUE THREAD

**Issue by smayer97** [mozilla/addons-frontend#8998]
### Describe the problem and steps to reproduce it:

When adding an add-on to a collection but it already belongs to that collection, currently get error message "This add-on already belongs to the collection" but DOES NOT tell you which one.

<img width="518" alt="Screen Shot 2019-11-28 at 2 48 43 AM" src="https://user-images.githubusercontent.com/6752849/69787239-11cc9280-118a-11ea-89bd-ea4c7631db94.png">

### What did you expect to happen?

It should list the name of the collection.

### Anything else we should know?

The reason is that you may not know why the message comes up..., e.g. accidentally selected the one next to it, or a slip of on the trackpad selected the completely wrong one... so you do not know for sure what your error is. Not knowing can be confusing at times.

Please add the name of the collection to the error message.

**Comment by virgilt** [comment]
@willdurand May I work on this?

**Comment by smayer97** [comment]
please keep active.

**Comment by smayer97** [comment]
Still needs a solution.
