### ISSUE TITLE
Font styles look broken on AMO -dev

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9000]
### Describe the problem and steps to reproduce it:
1. Load AMO -dev homepage
2. Observe the font styles in all the page components
3. Compare with stage

### What happened?
On -dev, fonts look like they had a lower weight

### What did you expect to happen?
Font styles are looking as expected

### Anything else we should know?
- reproduced in other pages as well
- reproduced on -dev with Fx70, WIn10x64

![2019-11-28_17-25-45](https://user-images.githubusercontent.com/31961530/69818379-4cbfdc00-1205-11ea-8c63-1abe66be3e9f.png)

**Comment by willdurand** [comment]
-dev uses "Fira Sans Book" while stage uses "Fira Sans Light" for some reason 🤔

**Comment by willdurand** [comment]
Ha! Looks like it is because we do not provide the fonts in -dev, mmmm.

**Comment by willdurand** [comment]
It is probably an issue with the webpack loaders (file and url).

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![2019-11-29_10-16-14](https://user-images.githubusercontent.com/31961530/69854270-5bec6b80-1291-11ea-9eb5-b509b21f83ff.png)
