### ISSUE TITLE
clipboard access

### ISSUE THREAD

**Issue by alabamatoy** [mozilla/addons-frontend#9004]
### Describe the problem and steps to reproduce it:

go to this page: http://kb.mozillazine.org/Granting_JavaScript_access_to_the_clipboard

This page states: "Instead of manually setting preferences, the AllowClipboard Helper extension manages security policies with a convenient user interface and automates the steps below." and points to https://addons.mozilla.org/firefox/addon/852/ which returns a 404 not found.

**Comment by jvillalobos** [comment]
The add-on hasn't been supported for many years and doesn't exist anymore. The page linking to it is also obsolete. Also, this repository is for the site's code, not its content, so we can't do anything to fix this.
