### ISSUE TITLE
Add UTM params to Contribute button

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9005]
We should set UTM params in the Contribute button so our referrals can be tracked. In particular, some devs point to the Donate to Mozilla page, and with that data we can figure out how much donations we're driving.

The params should be `utm_content=product-page-contribute&utm_medium=referral&utm_source=addons.mozilla.org`

Since those links currently use the outgoing server, we might have the same problem as https://github.com/mozilla/addons-frontend/issues/8826. It looks like the solution chosen for that issue was to not use outgoing at all. We use a whitelist for contribute URLs, so maybe it's okay to do that there, too? It seems unlikely that any of these payment sites would be hijacked to try to trigger an add-on install...

**Comment by bobsilverberg** [comment]
@muffinresearch What do you think? Would we be okay not using outgoing for these links because they consist of a list of whilelisted URLs?

**Comment by muffinresearch** [comment]
> @muffinresearch What do you think? Would we be okay not using outgoing for these links because they consist of a list of whilelisted URLs?

If we bypassed outgoing for that list, there would likely still be a threat if those origins had an open redirect. So I think in this case we should look at providing the UTM params on the server (before the outgoing URL is generated) for this one specific case.

**Comment by bobsilverberg** [comment]
> > @muffinresearch What do you think? Would we be okay not using outgoing for these links because they consist of a list of whilelisted URLs?
> 
> If we bypassed outgoing for that list, there would likely still be a threat if those origins had an open redirect. So I think in this case we should look at providing the UTM params on the server (before the outgoing URL is generated) for this one specific case.

Looking at the code for the Contribute button, this also seems like a good idea because we do not make an API request specifically for the Contribute info, but rather for the add-on as a whole, which would make it complicated to outgoingify some URLs and not others.

**Comment by bobsilverberg** [comment]
Thanks for the help @muffinresearch. I have opened https://github.com/mozilla/addons-server/issues/13010 in place of this.
