### ISSUE TITLE
Have just one Remove button at versions/

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#9011]
Is it possible to have just one **Remove** button? 

From <https://www.reddit.com/comments/e4atfn/-/f9gmgif/?context=1>, for example:  

> … the Mozilla add-on page shows all versions as being installed. Weird. …

True: there's a benefit to having a set of buttons that will remove *any* version, in edge cases where the user tests more than one version and removes one before testing another. A button against each version makes it easier to keep track of things – **little (or no) need to scroll** when working from one version to the next. 

Still, I do agree that the current UX is a bit weird; implying that more than one version is installed. 

A _very_ rough mock up, kicking the ball around: 

![head](https://user-images.githubusercontent.com/192271/69976920-b69bf680-1521-11ea-9eac-091fca355671.png)

– with the one button 'floating', so that if the user scrolls to the foot of the page): 

![foot](https://user-images.githubusercontent.com/192271/69976900-af74e880-1521-11ea-9418-bc73d615632e.png)

**Comment by lucknaumann** [comment]
Here's what I see on WFClassic:
![STTB](https://user-images.githubusercontent.com/51302763/69984185-cd2c5880-14f5-11ea-84df-44378ae1e162.PNG)

**Comment by willdurand** [comment]
> Still, I do agree that the current UX is a bit weird; implying that more than one version is installed.

I agree too and we already discussed this point multiple times. We decided not to change that for the moment, though.
