### ISSUE TITLE
Outdated links in a Not Found page

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#9024]
https://addons.mozilla.org/en-GB/developers/docs/policies/recommended (for example)

* refers to https://addons.mozilla.org/en-GB/firefox/extensions/?sort=featured
* should refer to https://addons.mozilla.org/firefox/search/?recommended=true&sort=random&type=extension

– also: 

* refers to https://addons.mozilla.org/en-GB/firefox/search/ 
* that's probably redundant (I assume that there's no longer a dedicated search page)

**Comment by jvillalobos** [comment]
> https://addons.mozilla.org/en-GB/developers/docs/policies/recommended 

That link doesn't work at all for me. We removed everything under `/docs/` a long time ago, I think.

**Comment by willdurand** [comment]
> That link doesn't work at all for me. We removed everything under `/docs/` a long time ago, I think.

does not work for me either, sorry.

**Comment by grahamperrin** [comment]
> … We removed everything under `/docs/` a long time ago, I think.

Sorry, I omitted some context for this issue. 

<https://addons.mozilla.org/developers/docs/policies/recommended> was linked from the head of the 2018-04-12 revision of **AMO/Featured Board Process**: 

https://wiki.mozilla.org/index.php?title=AMO/Featured_Board_Process&oldid=1192259

I edited the referring page https://wiki.mozilla.org/index.php?title=AMO/Featured_Board_Process&oldid=1192259 – "Primarily correcting some outdated links … plus an attempt to rewrite some outdated content, although I don't know whether this is appropriate" (NB my re-write might be terrible; someone might like to revert some of it). 

----

Whether there are any other referring pages, I don't know …
