### ISSUE TITLE
🏆 Recommended (trophy) badges obscuring 💲 (dollar) badges? – Some features may require payment

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#9026]
### Example A

https://addons.mozilla.org/addon/xposer/ 

* not <strike>recommended </strike>monitored by Mozilla
* **💲**

– I see the hint re: payment so rarely I forgot that existed, but when it's visible, it **is** both eye-catching and effective: 

![Xposer dollar](https://user-images.githubusercontent.com/192271/70385209-21b35600-1984-11ea-9696-c27a26d365d4.png)

### Example B

https://addons.mozilla.org/addon/video-downloadhelper/

* 🏆
* no hint re: payment

![Video DownloadHelper, no dollar](https://user-images.githubusercontent.com/192271/70385419-f7ae6380-1984-11ea-9742-34833a8eaca5.png)

![Video DownloadHelper, about, commercial](https://user-images.githubusercontent.com/192271/70385418-f7ae6380-1984-11ea-8fb7-398f166a8086.png)

> … about 

> … _commercial_ …

### Example C

https://addons.mozilla.org/addon/lastpass-password-manager/

* 🏆
* no hint re: payment
* **Free**

![LastPass: Free Password Manager, no dollar](https://user-images.githubusercontent.com/192271/70385445-48be5780-1985-11ea-9571-a067648db260.png)

![LastPass: Free Password Manager, about, premium](https://user-images.githubusercontent.com/192271/70385443-4825c100-1985-11ea-9cb0-88d2d2e4a146.png)

> … about 

> … _premium_ …

![image](https://user-images.githubusercontent.com/192271/70385543-11e94100-1987-11ea-9546-c7f58e1a94eb.png)

### Example D

https://addons.mozilla.org/addon/roboform/

* 🏆
* no hint re: payment

![RoboForm, no dollar](https://user-images.githubusercontent.com/192271/70385482-cb471700-1985-11ea-9903-b1522bd3927d.png)

![RoboForm, about](https://user-images.githubusercontent.com/192271/70385481-cb471700-1985-11ea-9a14-949c1dd3dab3.png)

> … about 

* **no hint re: payment**
* availability of non-free products or services that increase the functionality of the extension become visible only after clicking away from AMO, to the home page or the support page

<details>
<summary>(click away from AMO)</summary>

![RoboForm home, buy now, start business trial](https://user-images.githubusercontent.com/192271/70385491-fa5d8880-1985-11ea-94ea-ba76ef7a702a.png)

![RoboForm support, buy now](https://user-images.githubusercontent.com/192271/70385492-faf61f00-1985-11ea-9a82-2af266d0ed05.png)
</details>

**Comment by grahamperrin** [comment]
For example B, a recent discussion in Reddit: <details>

<summary>(not particularly attractive – repeated over-emhphases on all things negative)</summary>

https://old.reddit.com/r/firefox/comments/e5sxch/are_addons_that_require_third_party_programs_to/ ([captured](https://web.archive.org/web/20191208071443/https://old.reddit.com/r/firefox/comments/e5sxch/are_addons_that_require_third_party_programs_to/))

</details>

It wasn't until long after the discussion ended/paused ("come off it", foot of the page) that I stumbled across an AMO page with: 

> **Some features may require payment** :heavy_dollar_sign: 

In retrospect, it should have been easier to make an *acceptably* positive argument re: the commercial aspect **if** the dollar badge re: payment had been upfront.

**Comment by willdurand** [comment]
@grahamperrin that's because the `requires_payment` flag is set to `false`, I guess. Here is an example:

```
$ curl -s https://addons.mozilla.org/api/v4/addons/addon/video-downloadhelper/ | jq '.requires_payment'
false
```

Xposer returns `true`, hence the presence of the badge:

```
$ curl -s https://addons.mozilla.org/api/v4/addons/addon/xposer/ | jq '.requires_payment'
true
```

It's up to the developers to define this property in DevHub:

<img width="691" alt="Screen Shot 2019-12-09 at 11 44 47" src="https://user-images.githubusercontent.com/217628/70429676-5fde7180-1a79-11ea-8a23-a4d9d128365f.png">

**Comment by grahamperrin** [comment]
Interesting, thanks. 

Please, might we have a brief chat in `#addons`? I'll fire up Riot app in around five minutes. (I'd like to draw attention to something, but not from GitHub.)

**Comment by grahamperrin** [comment]
Closing, re: William's https://github.com/mozilla/addons-frontend/issues/9026#issuecomment-563175763 since I found an example of AMO working as expected 👍

----

Re: one or more of the developers who either overlook or misinterpret this: 

![Screenshot of the 'Requires payment?' question](https://user-images.githubusercontent.com/217628/70429676-5fde7180-1a79-11ea-8a23-a4d9d128365f.png)

– I'll follow up in IRC.

**Comment by grahamperrin** [comment]
Note to self, another: <https://addons.mozilla.org/en-GB/firefox/addon/languagetool/> 

> … We offer a Premium version which is linked from several places in the add-on. This add-on also works without payment and registration, though. …
