### ISSUE TITLE
No loading indicators on primary hero page when homepage is loading

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#9034]
Steps to reproduce:
1.Go to addons.mozilla.org and press Firefox logo from top left corner multiple times
2.Observe the primare hero section while page is loading

Expected results:
Loading indicators should be present

Actual results:
No loading indicators 

Please see video for this issue:
![loadindicators](https://user-images.githubusercontent.com/1583842/70737082-6dfeed00-1d1a-11ea-9d8a-7059308b4b56.gif)

**Comment by ioanarusiczki** [comment]
@willdurand The loading indicator is available on dev when the logo is clicked. 

![loading indicator](https://user-images.githubusercontent.com/33448286/71348954-66d7aa80-2576-11ea-96e6-29022f94f5c6.gif)
