### ISSUE TITLE
Sort themes in chronological order from user's profile page 

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-frontend#9042]
This request came in from our theme reviewers. 

When reviewing themes, reviewers will check if a user has submitted a duplicate theme by going to their profile page. Currently, themes listed on the profile page are sorted by # of users, which can make it hard to identify themes that have been recently submitted. 

![Screen Shot 2019-12-17 at 9 26 53 AM](https://user-images.githubusercontent.com/23342476/71019585-76a34a80-20af-11ea-97f4-9df152e44568.png)

It would be great if themes could be sorted chronologically from a user's profile page.

**Comment by NitinMadhukar** [comment]
@caitmuenster  can i work on this

**Comment by caitmuenster** [comment]
Hi @NitinMadhukar, you might want to look for an issue marked with the label 'contrib:good first bug` label to help you get familiar with the code base and to get more hands-on support during the bug fix. 

It doesn't look like there are any tagged good first bugs in this repository at the moment. You're welcome to keep an eye on [this list](https://github.com/mozilla/addons-frontend/labels/contrib%3A%20good%20first%20bug) for when new ones become available, or fix bugs for other Mozilla projects by going to [codetribute.mozilla.org](https://codetribute.mozilla.org/).
