### ISSUE TITLE
Update Primary Hero loading skeleton to reflect a hero with an image

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9049]
This is a follow-up to https://github.com/mozilla/addons-frontend/pull/9045.

### Describe the problem and steps to reproduce it:

Visit any page on the site, and then visit the home page.

### What happened?

You see a loading skeleton, but it doesn't match the layout of the eventual primary hero element.

### What did you expect to happen?

The loading skeleton should more closely match the layout of the primary hero element with an image.

### Anything else we should know?

When the loading skeleton for the primary hero element was first implemented, it was believed that, for the most part, the primary hero *would not* contain an image. That assumption has been reversed and now the primary hero will almost always contain an image, so we should adjust the loading skeleton accordingly.

![2019-12-20 08 35 51](https://user-images.githubusercontent.com/142755/71258340-eb6ec280-2303-11ea-8ff9-960a49aeb46f.gif)

**Comment by snitin315** [comment]
@bobsilverberg Can i work on this issue??

**Comment by willdurand** [comment]
@snitin315 hi, 
I am not sure. Instead, you can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by willdurand** [comment]
Marking this issue as contributor friendly.

**Comment by nisamova** [comment]
> Marking this issue as contributor friendly.

Hello 
I am with Outreachy program in May 2020. Is this issue available to work/contribute? Thank yu

**Comment by snitin315** [comment]
> > Marking this issue as contributor friendly.
> 
> Hello
> I am with Outreachy program in May 2020. Is this issue available to work/contribute? Thank yu

Yes.

**Comment by nisamova** [comment]
> > > Marking this issue as contributor friendly.
> > 
> > 
> > Hello
> > I am with Outreachy program in May 2020. Is this issue available to work/contribute? Thank yu
> 
> Yes.

I apologize if it is a bad question. Here is the question: I would like to contribute. What steps should I take to make first contribution? Meaning where would I be able to get more info? Thank you

**Comment by snitin315** [comment]
First go through the README, setup the project locally and play around with the project to get yourself familiarized.

**Comment by willdurand** [comment]
> I apologize if it is a bad question. Here is the question: I would like to contribute. What steps should I take to make first contribution? Meaning where would I be able to get more info? Thank you

@snitin315 is right. Read the README and make sure you can run this website locally first.

If you are familiar with javascript (and maybe React), this is a probably a good (yet a bit challenging) issue. Otherwise I'd suggest looking for something else (that is a bit easier to get familiar with the language and so on) first.

**Comment by muskangupta-iitr** [comment]
@willdurand I am interested in this issue. There is a component `LoadingText` which contains the placeholder for texts when component loads. For image, instead of making a different component, we can create a generalized component containing both image as well as text loaders. IN future, if we further loader it can be placed here. Can you please assign me this issue ?

**Comment by willdurand** [comment]
@muskangupta-iitr so @snitin315 expressed interest first so I'd recommend you to try to find something else for now :)

**Comment by nisamova** [comment]
> @muskangupta-iitr so @nisamova expressed interest first so I'd recommend you to try to find something else for now :)

thank you for giving me a chance. I would like to experiment by creating a parent component that will have two child components which are image and text. Apply respective grid styles for each, and default properties as well. Each component should have a default prop so both image and text can further be self-functioning. I will be honest, I am new to React (used it while building Gatsby website, and created a couple React components for hands-on learning projects. I do not have any large working knowledge of React )However, I used and worked with several other javascript front-end libraries.

**Comment by willdurand** [comment]
@nisamova alright so I would recommend you to start running this project locally (see the README file). Then you should take a look at the [`HeroRecommendation`](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/HeroRecommendation/index.js) component. There are a few `LoadingText` components displayed. Those are the components that produce the loading effects.

The idea would be to not render these `LoadingText` components like in the video at the top of the issue (it looks like a few lines of loading text) but instead to render these loading indicators where text will appear. I don't know what we'll do for the image, maybe nothing or maybe we'll also use a `LoadingText` for it. I would start by the text on the right side of the Hero.

**Comment by nisamova** [comment]
> > > Marking this issue as contributor friendly.
> > 
> > 
> > Hello
> > I am with Outreachy program in May 2020. Is this issue available to work/contribute? Thank yu
> 
> Yes.



> @nisamova alright so I would recommend you to start running this project locally (see the README file). Then you should take a look at the [`HeroRecommendation`](https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/HeroRecommendation/index.js) component. There are a few `LoadingText` components displayed. Those are the components that produce the loading effects.
> 
> The idea would be to not render these `LoadingText` components like in the video at the top of the issue (it looks like a few lines of loading text) but instead to render these loading indicators where text will appear. I don't know what we'll do for the image, maybe nothing or maybe we'll also use a `LoadingText` for it. I would start by the text on the right side of the Hero.

I went ahead and added margin-left to.LoadingText in styles.scss. This allowed loading indicators(loading skeleton) shift from center to right side where the text currently renders after the download. As we expected the image space is empty. The changes are reflected in the desktop(not on mobile view yet) only. Is this the possible expected solution for issue #9049? In other words am I in the right direction? If yes I will try to apply this change to the mobile view as well. Thank you

**Comment by nisamova** [comment]
@willdurand how would you like to check ? should I create a pull request? Thank you

**Comment by snitin315** [comment]
Yes create a pull request , and move the discussion there.

**Comment by muskangupta-iitr** [comment]
@nisamova I think instead of shifting the text to left, you can add another loading test for the image having some height. And giving margin-left a hard coded values isn't a good practice as it will vary according to screen sizes and resolution. You can use flex-box or position.

**Comment by Aakash2408** [comment]
Hey @willdurand , Is this issue resolved or I can take this?

**Comment by caitmuenster** [comment]
Hey @Aakash2408! @willdurand is out on leave until September; you may want to hold off on this issue until he gets back. :)

**Comment by Cronus1007** [comment]
@willdurand Shall I take over this issue if no one is currently working upon it .

**Comment by caitmuenster** [comment]
Hey @Cronus1007, go ahead and pick this up! We will assign it to you once you submit a PR. :)

**Comment by Cronus1007** [comment]
@caitmuenster  I was approaching it in the manner that all the images doesnt have their loading screen so we can implement LoadingText like something where all the images will get their own shinnerLoadingScreen.

**Comment by snitin315** [comment]
Bump

**Comment by xlisachan** [comment]
@bobsilverberg, can you please assign me to this issue?

**Comment by snitin315** [comment]
@xlisachan PR welcome :)

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

- image placeholder is available on AMO dev

![test2](https://user-images.githubusercontent.com/33448286/133071612-871ae8af-1d91-4c21-b5bd-2546fdaac9de.gif)

- I've noticed that the loading state of the hero section when clicking the logo while being on the blog https://addons-dev.allizom.org/blog/ is not behaving the same way like the rest of AMO pages, meaning that the whole section loads directly. I believe it should be fine because it's been like that probably from day1 (looks good to me).

**Comment by bobsilverberg** [comment]
> 
> * I've noticed that the loading state of the hero section when clicking the logo while being on the blog [addons-dev.allizom.org/blog](https://addons-dev.allizom.org/blog/) is not behaving the same way like the rest of AMO pages, meaning that the whole section loads directly. I believe it should be fine because it's been like that probably from day1 (looks good to me).

Yes, I don't think that is an issue.
