### ISSUE TITLE
Keep source (src) referrer when navigating add-on page

### ISSUE THREAD

**Issue by rugk** [mozilla/addons-frontend#9054]
### Describe the problem and steps to reproduce it:

The underlying problem:
* I've noticed that the `?src=external-` sources were mostly useless: https://discourse.mozilla.org/t/does-tracking-external-source-src-external-even-work-on-amo/41760?u=rugkx

The apparently exact problem:
* When you [navigate around](https://discourse.mozilla.org/t/does-tracking-external-source-src-external-even-work-on-amo/41760/3?u=rugkx) e.g. click on "reviews" on an add-on listing you've visited with a referrer URL and then click at the top left add-on name, the download button link does not include the `src` anymore, but  actually `?src=dp-btn-primary`.

### What did you expect to happen?

The referrer (src) should be kept, around. You may do so by:
* either saving it in local storage, a cookie or so.
* or by re-adding the referrer to each link of the add-on you could use to navigate back.

---

**For QA:** as mentioned [here](https://github.com/mozilla/addons-frontend/issues/9054#issuecomment-572176640), we'll pass the `src` query parameter present in an add-on detail page URL to all the related pages for this add-on (links to the reviews, etc.). As long as the user stays on these related pages, the `src` parameter should be kept.

For statistics, it is passed but it won't be possible to come back to AMO with the `src` parameter (I think, because it is a different app under the hood).

**Comment by willdurand** [comment]
Someone reported a similar issue on the dev mailing-list: https://mail.mozilla.org/pipermail/dev-addons/2019-December/004250.html

**Comment by jvillalobos** [comment]
The idea here is that if you visit `/addon/(slug or ID)/*` with a `src` parameter, its value should be preserved as long as the user is navigating to other pages that match `/addon/(slug or ID)/*` for the same add-on. I think that covers All Reviews, All Versions, Stats Dashboard, and Privacy Policy, and excludes the developer profile.

**Comment by willdurand** [comment]
> Someone reported a similar issue on the dev mailing-list: [mail.mozilla.org/pipermail/dev-addons/2019-December/004250.html](https://mail.mozilla.org/pipermail/dev-addons/2019-December/004250.html)

That is actually a different issue, my bad..

> I think that covers All Reviews, All Versions, Stats Dashboard, and Privacy Policy, and excludes the developer profile.

Stats might be a problem because users will "leave" addons-frontend (but it is just a thought).

**Comment by jvillalobos** [comment]
Public stats aren't that common, so I'm okay with that case breaking.

**Comment by TheSTL** [comment]
I'm working on this issue

**Comment by willdurand** [comment]
> I'm working on this issue

@TheSTL please don't, this issue is already assigned (to me)

**Comment by TheSTL** [comment]
Sorry, @willdurand I didn't see.

**Comment by AlexandraMoga** [comment]
I've verified the navigation for add-on detail pages that contain a `src` parameter and the parameter is preserved when navigating to and back from the following pages:
- after the log in process (if the user accessed a direct link while being logged out)
- All reviews page
- All versions page
- Privacy Policy and EULA pages

One page where the `src` param is not preserved is the Custom license page, shown if an add-on is using its own defined license.

Here is an add-on example: 
https://addons-dev.allizom.org/en-US/firefox/addon/video-downloadhelper/?src=external-twitter

@willdurand should we support this case too, although add-ons with Custom licenses might be a more rare case?

**Comment by willdurand** [comment]
> One page where the `src` param is not preserved is the Custom license page, shown if an add-on is using its own defined license.
> 
> Here is an add-on example:
> [addons-dev.allizom.org/en-US/firefox/addon/video-downloadhelper/?src=external-twitter](https://addons-dev.allizom.org/en-US/firefox/addon/video-downloadhelper/?src=external-twitter)
> 
> @willdurand should we support this case too, although add-ons with Custom licenses might be a more rare case?

oops, you're right. We should fix this link too.

**Comment by willdurand** [comment]
@ioanarusiczki could you file a new issue for the custom licenses?

**Comment by willdurand** [comment]
> @ioanarusiczki could you file a new issue for the custom licenses?

Nevermind, I filed https://github.com/mozilla/addons-frontend/issues/9227
