### ISSUE TITLE
collection selection isnt working 

### ISSUE THREAD

**Issue by mickyfan2345** [mozilla/addons-frontend#9059]
### Describe the problem and steps to reproduce it:

![Screenshot_2019-12-30 Add-ons for Firefox (en-US)](https://user-images.githubusercontent.com/39664884/71608990-e7883f00-2b52-11ea-91e6-0962a836620e.png)

**Comment by jvillalobos** [comment]
Can you please add more detail? How did you end up seeing that page?

**Comment by mickyfan2345** [comment]
jvillalobos  like i said i would go to view my collection and that's how i got it

**Comment by bobsilverberg** [comment]
Closing this in favour of #9063 which has a bit more information in it.

**Comment by mickyfan2345** [comment]
bobsilverberg why is this closed


> 
> 
> Closing this in favour of #9063 which has a bit more information in it.

**Comment by bobsilverberg** [comment]
> bobsilverberg why is this closed
> 
> why is this closed

Because we do not need two issues open describing the exact same problem. We now have issue #9063 which you also opened, and we can use that to discuss and track the problem.
