### ISSUE TITLE
Windows-only and Linux-only add-ons are flagged as incompatible with Quantum

### ISSUE THREAD

**Issue by srikiwork** [mozilla/addons-frontend#9060]
### Describe the problem and steps to reproduce it:

    Create a windows-only or linux-only extension that supports Firefox 42 and above
    Go to its listing page in FF 71

### What happened?

It says incompatible with Firefox Quantum

### What did you expect to happen?

It should not include this badge.

**Comment by jvillalobos** [comment]
Can you give an example of such an add-on?

**Comment by vcarciu** [comment]
https://addons-dev.allizom.org/en-US/firefox/addon/forms-error-categories/ looks to meet the criteria for this issue, but we don't see any badge.

@srikiwork : can you please let us know how you uploaded the platform specific extension?
