### ISSUE TITLE
problem with veiwing my collection

### ISSUE THREAD

**Issue by ghost** [mozilla/addons-frontend#9063]

**Comment by mickyfan2345** [comment]
i click on veiw my collection and it takes me back to Server Error

Sorry, but there was an error with our server and we couldn't complete your request. We have logged this error and will investigate it.
Suggested Pages

    Browse all extensions
    Browse all themes
    Add-ons Home Page

If you have additional information that would help us you can file an issue. Tell us what steps you took that lead to the error and we'll do our best to fix it. 
![Screenshot_2020-01-06 Add-ons for Firefox (en-US)](https://user-images.githubusercontent.com/39664884/71838986-24d75a00-3088-11ea-8ba1-609668de4386.png) please fix it thank you

**Comment by bobsilverberg** [comment]
@mickyfan2345 Does this happen immediately after you choose the "View My Collections" link from the menu, or does it happen after you select an individual collection from your list of collections? Can you paste in the URL that is in the address bar when you are looking at this error page?

**Comment by mickyfan2345** [comment]
@bobsilverberg it happens immediately after i chose view my colletion

**Comment by mickyfan2345** [comment]
@bobsilverberg https://addons.mozilla.org/en-US/firefox/collections/

**Comment by bobsilverberg** [comment]
Thanks @mickyfan2345. I'll try to look into this further.

**Comment by mickyfan2345** [comment]
@bobsilverberg  thank you

**Comment by mickyfan2345** [comment]
@bobsilverberg this is the second time it done it

**Comment by mickyfan2345** [comment]
@bobsilverberg  did you see my post i said it's the second time it happened it happened 2 years ago and i also said ty

**Comment by bobsilverberg** [comment]
> @bobsilverberg did you see my post i said it's the second time it happened it happened 2 years ago and i also said ty

Yes, I saw that, thanks. I thought you might have meant it happened two times recently, but you're saying it happened a long time ago, and then everything was fine with your "My Collections" page for 2 years, and then it suddenly happened again? Do you recall if you filed an issue about it when it happened two years ago?

**Comment by mickyfan2345** [comment]
@bobsilverberg yes i filed complaint then to and it was resolved but all of a sudden did it again

**Comment by bobsilverberg** [comment]
@mickyfan2345 I see an old issue at https://github.com/mozilla/addons-frontend/issues/5116, but I don't see any resolution for it. There was something in there about you having a collection with an empty name - I wonder if that's the issue once again. It doesn't look like we made any changes as a result of https://github.com/mozilla/addons-frontend/issues/5116, so perhaps you did something to fix it yourself?

**Comment by mickyfan2345** [comment]
@bobsilverberg  i dont know but it's doing it again

**Comment by mickyfan2345** [comment]
@bobsilverberg i dont know but it's doing it again

**Comment by mickyfan2345** [comment]
hello @bobsilverberg  are you looking into the problem thanks

**Comment by bobsilverberg** [comment]
> hello @bobsilverberg are you looking into the problem thanks

I am looking into it.

**Comment by bobsilverberg** [comment]
As far as I can tell, the only API request that is being made when navigating to the "My Collections" page is the one to retrieve the collections, in my case, on dev, that's `http://localhost:3000/api/v4/accounts/account/10641570/collections/?lang=en-US&wrap_outgoing_links=true`. It sounds like there's something wrong with the data in this user's collections which is resulting in something invalid being returned.

I don't have access to prod to investigate the data issue, but I assume someone else does. It looks like the user's display name is `lynnette1`. Could someone with access possibly look into this? @wagnerand or someone else?

**Comment by jvillalobos** [comment]
I don't think it's possible to see a list of collections by another user in prod (outside the admin). I checked, and @mickyfan2345 still had a collection with an empty name, so I set a name for it. Maybe that fixes the problem.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos!

@mickyfan2345 Can you please try again and see if this fixed your problem?

**Comment by teohhanhui** [comment]
I'm having the same problem. When I go to https://addons.mozilla.org/en-US/firefox/collections/ I get the "Server Error" page and this error in the console:

> Caught application error: Invariant Violation: name is required

So it'd seem like I somehow have a collection without a name. (How?)

My AMO user id is 37076

**Comment by jvillalobos** [comment]
It should be fixed now. Since this is a rare problem, I'm closing this issue.
