### ISSUE TITLE
CSS seems to be broken when running the site locally

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9064]
I tried for the first time since late December to run the frontend site locally, and find that no css is being served. I tried running from an older commit, specifically https://github.com/mozilla/addons-frontend/commit/160b0096055420ab17813f9962411cc8460d816b, and with the repo in that state everything seems to be fine.

I'm going to look through the changes since that commit to see if I can figure out when this started and what the cause is.

**Comment by mirefly** [comment]
It may be related to https://github.com/webpack-contrib/style-loader/issues/445. New style-loader [v1.1.2](https://github.com/webpack-contrib/style-loader/releases/tag/v1.1.2) fixed that bug. I guess merging #9058 would fix this issue.

**Comment by bobsilverberg** [comment]
The commit which caused the problem is https://github.com/mozilla/addons-frontend/commit/a7286583a30c916a7577ff17b42a8c049f248ecd, which is a lock file maintenance from Renovate. It looks like that updated a whole bunch of internal dependencies, one of which may be the culprit.

@mirefly I will also see if simply merging #9058 fixes the issue - thanks!

**Comment by bobsilverberg** [comment]
It seems that #9058 does in fact fix the issue, thanks @mirefly! I'll merge that which should fix the problem. I guess I should have tried that first before spending an hour bisecting the code. :-P
