### ISSUE TITLE
can't access to my account web developper firefox

### ISSUE THREAD

**Issue by jvtgar2020** [mozilla/addons-frontend#9065]
### Describe the problem and steps to reproduce it:
Today I've tried to login in my account with my user an password and the system say me:

"Sorry, but you aren't authorized to access this page. If you aren't signed in, try signing in using the link at the top of the page."

https://addons.mozilla.org/en-US/firefox/

**Comment by jvillalobos** [comment]
There's a link to log in at the top of the page, like the message indicates. If you're an add-on developer and are having problems signing in, please email amo-admins AT mozilla DOT com with the details.
