### ISSUE TITLE
Warn AMO users when visiting the site with Fenix

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9068]
From the PRD at https://docs.google.com/document/d/1HOImPu2RO9PXIbrNvE_YhYyONw7n-rgjzMtMQ3Knk4Q/edit.

When a user visits AMO using Fenix, a warning should be displayed similar to the platform warning implemented via #8701. An an add-on detail page, the warning will appear below the install button, similar to the current warning:

![Screenshot 2019-10-21 12 20 03](https://user-images.githubusercontent.com/142755/67223585-8b3fcb00-f3fd-11e9-85e7-528e9fede1f1.png)

The text for this warning will be "This add-on is not compatible with Firefox for Android. Learn More."

On all other pages, the warning will appear at the top of the page, similar to the current warning:

![Screenshot 2019-10-21 12 19 47](https://user-images.githubusercontent.com/142755/67223590-90047f00-f3fd-11e9-93ff-a6e0a1c397ce.png)

The text for this warning will be "To learn about add-ons compatible with Firefox for Android, click here."

In each case there will be a link to either a SUMO article or a collection of add-ons that are compatible with Fenix. That is TBD.

**Comment by bobsilverberg** [comment]
@jvillalobos The SUMO article that we'll be using as the link destination, at least for now, has been published at https://support.mozilla.org/kb/add-compatibility-firefox-preview/. This article discusses our plans for add-on compatibility for Fenix, but doesn't present a list of extensions that are compatible. I am therefore wondering whether the text we're using in the warning makes sense, as it's not particularly accurate.

We're currently proposing using:

"This add-on is not compatible with Firefox for Android. Browse compatible add-ons."

and

"To find add-ons compatible with Firefox for Android, click here."

but the information in the linked article neither allows users to "Browse compatible add-ons" nor to "find add-ons compatible with Firefox for Android". 

Do you think we should change the text of the warnings for the initial implementation and update it later if we do have a link which helps people find compatible add-ons?

**Comment by jvillalobos** [comment]
How about
"This add-on is not compatible with Firefox for Android. Learn More."
and
"To learn about add-ons compatible with Firefox for Android, click here."

We will update the article once we have more information on Fenix compatibility. We can also change the messaging on AMO then.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified this issue on dev with FF Preview 71.0.1(Android 9.0) on a mobile device and also changing the UA in the FF72 browser (win10).
Mozilla/5.0 (Android 9.0; rv:69.0) Gecko/20100101 Firefox/69.0
Mozilla/5.0 (Android 9.0; rv:70.0) Gecko/20100101 Firefox/70.0
Mozilla/5.0 (Android 9.0; rv:73.0) Gecko/20100101 Firefox/73.0

- the red warning message from https://github.com/mozilla/addons-frontend/issues/9069 which was available on top of an add-on detail page has been replaced with the yellow warning below the disabled install button. The "Learn more link" opens the [specified](https://github.com/mozilla/addons-frontend/issues/9068#issuecomment-574193847) SUMO page in the same tab. 

![Android message](https://user-images.githubusercontent.com/33448286/72618198-4287a780-3943-11ea-9f6f-4b4480ca091c.gif)

I believe (but not 100% sure) that the red warning message is no longer wanted together with the new yellow warning - on the detail pages. Let me know if it's ok this way.

- the new yellow warning on the rest of the pages is available too. The `click here` link will redirect to  the same SUMO page. 

![click here link](https://user-images.githubusercontent.com/33448286/72618547-00ab3100-3944-11ea-8fc2-c0195dcd47a6.gif)

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> I verified this issue on dev with FF Preview 71.0.1(Android 9.0) on a mobile device and also changing the UA in the FF72 browser (win10).
> Mozilla/5.0 (Android 9.0; rv:69.0) Gecko/20100101 Firefox/69.0
> Mozilla/5.0 (Android 9.0; rv:70.0) Gecko/20100101 Firefox/70.0
> Mozilla/5.0 (Android 9.0; rv:73.0) Gecko/20100101 Firefox/73.0
> 
> * the red warning message from #9069 which was available on top of an add-on detail page has been replaced with the yellow warning below the disabled install button. The "Learn more link" opens the [specified](https://github.com/mozilla/addons-frontend/issues/9068#issuecomment-574193847) SUMO page in the same tab.
> 
> I believe (but not 100% sure) that the red warning message is no longer wanted together with the new yellow warning - on the detail pages. Let me know if it's ok this way.
>

Yes, the red warning about Fenix compatibility on an add-on detail page should no longer be seen.
