### ISSUE TITLE
Create a helper to identify Fenix

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9069]
This supports #9068 and is about creating a function in [compatibility.js](https://github.com/bobsilverberg/addons-frontend/blob/master/src/core/utils/compatibility.js) which can be used to identify Fenix as the current user agent.

We know a browser is Fenix if the OS is Android and the version is 69 or greater.

**Comment by willdurand** [comment]
Note that we already have some code for that here: https://github.com/bobsilverberg/addons-frontend/blob/7beae9b46d89e5a614c285e64b467d0b71000f4a/src/core/utils/compatibility.js#L140-L148

**Comment by bobsilverberg** [comment]
Thanks @willdurand. Yes, the patch I wrote is essentially an extract function from that, as we now need it in two places.

**Comment by willdurand** [comment]
> Thanks @willdurand. Yes, the patch I wrote is essentially an extract function from that, as we now need it in two places.

yeah, sorry I read the issue before and only saw the patch after..

**Comment by ioanarusiczki** [comment]
@bobsilverberg In case this can be verified by QA please add some STR. Thanks!

**Comment by bobsilverberg** [comment]
Sorry @ioanarusiczki, at first I thought this was `qa: not needed`, but then I realized that part of it is verifiable. I will add an STR to the description.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on a mobile device with Android 9.0 FF Preview 71.0.1 and also the Nightly Android version FF74.0a1
- on all AMO servers I see the red warning message displayed on the add-on detail pages. The install button is disabled. 
- I tried for FF69 too using the Responsive Design Mode, I added a device with User Agent: Mozilla/5.0 (Android 9.0; rv:69.0) Gecko/20100101 Firefox/69.0

![FF69](https://user-images.githubusercontent.com/33448286/72358137-c1d36c00-36f4-11ea-93cd-3e23226ca435.gif)
