### ISSUE TITLE
Update `Dockerfile` to install `gnupg`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9074]
It is currently not possible to build a docker image of this project because of a change in the upstream (base) image: https://github.com/nodejs/docker-node/pull/1182.

We should now install `gnupg` in our build deps, it seems.

**Comment by ioanarusiczki** [comment]
@willdurand Is this a qa not needed?

**Comment by willdurand** [comment]
> @willdurand Is this a qa not needed?

ha yes, sorry!
