### ISSUE TITLE
AMO does not show correct icon when privacy.resistFingerprinting.block_mozAddonManager is set

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/addons-frontend#9076]
### Describe the problem and steps to reproduce it:
When privacy.resistFingerprinting.block_mozAddonManager is enabled, install an add-on then view the add-on page.

### What happened?

You see the Add To Firefox button...

### What did you expect to happen?

instead of showing the 'Remove' button.

### Anything else we should know?

This is a known issue that I wanted to get on file. I'm not sure there is an easy solution, and the priority of this issue would be a P5 on Bugzilla.  block_mozAddonManager is a non-standard preference used by Tor Browser.

**Comment by willdurand** [comment]
I don't think we can fix this issue because the different states of the install button are retrieved from `mozAddonManager`.
