### ISSUE TITLE
Stars color in reviews list are grey even for 5 stars, don't match yellow style in sidebar

### ISSUE THREAD

**Issue by wesinator** [mozilla/addons-frontend#9077]
### Describe the problem and steps to reproduce it:
The stars in the reviews list are grey, making it look like zero stars (at least to me)
https://addons.mozilla.org/en-US/firefox/addon/mitaka/reviews/

### What happened?
![mitaka_reviews_grey_stars](https://user-images.githubusercontent.com/5124946/71783641-b6c36200-2fb7-11ea-8f1b-8c71af1432fa.png)
stars are grey, making five star reviews look like no stars

### What did you expect to happen?
Consistent yellow style for stars on reviews

**Comment by Shivansh2407** [comment]
I would like to work on this issue.

**Comment by caitmuenster** [comment]
Hi @Shivansh2407, we don't know if this is a bug. I recommend you look for an issue with the label 'contrib:good first bug`. Those bugs have all been confirmed and we offer mentorship for fixing them.

**Comment by Ebenezer997** [comment]
@ebenezer97 I would love to work on this issue, does anyone has suggestions for me since this is my first issue.

**Comment by caitmuenster** [comment]
Hi @Ebenezer997, see my comment above from Jan 23. :)

**Comment by wesinator** [comment]
https://addons.mozilla.org/firefox/user/15063723/

The preview also shows grey stars, making it look like it has 0 stars when it actually has 5
<img width="856" alt="image" src="https://user-images.githubusercontent.com/5124946/84959883-4d02c480-b0ce-11ea-93b6-b1d75a2958a1.png">

Thanks,

**Comment by wesinator** [comment]
> https://addons.mozilla.org/firefox/user/15063723/
> 
> The preview also shows grey stars, making it look like it has 0 stars when it actually has 5
> <img alt="image" width="856" src="https://user-images.githubusercontent.com/5124946/84959883-4d02c480-b0ce-11ea-93b6-b1d75a2958a1.png">
> 
> Thanks,

still an issue , the review info stars are grey when the sidebar are yellow 

![Screenshot from 2020-12-16 14-18-13](https://user-images.githubusercontent.com/5124946/102395952-cc078580-3fa9-11eb-8372-1af621f1fd59.png)

**Comment by bobsilverberg** [comment]
@wesinator If you look at the issue that you reference above (#4029), you'll see that it specifically states that "the add-on rating stars should be yellow whenever they indicate the site user's personal rating. They should be gray in all other cases (for example: cumulative ratings in add-on listings)." Therefore this appears to follow the guidelines from UX. Have you found instances where the stars are not yellow and yet they represent the current user's rating for the add-on?

**Comment by wesinator** [comment]
> @wesinator If you look at the issue that you reference above (#4029), you'll see that it specifically states that "the add-on rating stars should be yellow whenever they indicate the site user's personal rating. They should be gray in all other cases (for example: cumulative ratings in add-on listings)." Therefore this appears to follow the guidelines from UX. Have you found instances where the stars are not yellow and yet they represent the current user's rating for the add-on?

No. The issue here is with the gray coloring, if the reviews all have five stars, it may look to the user like there are 0 stars , because they don't see the shade that corresponds to an empty star, and the page mixes both yellow style and gray style stars. 
(see screenshot, info above) 

I think the UX guidelines maybe should be revisited

**Comment by willdurand** [comment]
> No. The issue here is with the gray coloring, if the reviews all have five stars, it may look to the user like there are 0 stars , because they don't see the shade that corresponds to an empty star, and the page mixes both yellow style and gray style stars.

How so? 5 stars = all stars are grey whereas 3 stars would only have 3 grey stars and 2 very light grey ones. See: https://addons.mozilla.org/en-US/firefox/addon/iorad-the-tutorial-builder/reviews/?
