### ISSUE TITLE
Update footer links to align with new Firefox products

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9089]
I was looking at the AMO footer and noticed that it links to Focus Browser, which is no longer promoted on mozilla.org. In fact, the link just goes to the mobile page.

I think we should update the AMO footer, replacing the Firefox section with the Browsers and Products sections in mozilla.org (making sure we still have UTM parameters on all of those links). Since that means 2 headers and more links, it's probably worth splitting into two columns (one for Browsers, one for Products and social media links).

**Comment by bobsilverberg** [comment]
I didn't see any Browsers or Products links in the mozilla.org footer, but I assume you mean these:

![Screenshot 2020-01-14 09 04 59](https://user-images.githubusercontent.com/142755/72350723-f7546700-36ac-11ea-8553-313702904110.png)

and these:

![Screenshot 2020-01-14 09 05 31](https://user-images.githubusercontent.com/142755/72350778-118e4500-36ad-11ea-9d85-ec85f8db259b.png)

Some other questions:

1. Do we need any UX input on this, or should we just switch to a three-column footer as you suggested?
2. Where would you place this as a priority?

**Comment by jvillalobos** [comment]
Ah, I didn't realize their footer is different on different pages. I mean the footer in https://www.mozilla.org/en-US/firefox/new/, for instance.

> Do we need any UX input on this, or should we just switch to a three-column footer as you suggested?

I'd like to see how it would look as three columns and then ping Aaron for confirmation that he's okay with it.

> Where would you place this as a priority?

It's low priority, maybe P3. Or it could also be a goodfirstbug, I suppose.

**Comment by Shivansh2407** [comment]
Can I please work on this ?

**Comment by bobsilverberg** [comment]
> Can I please work on this ?

Sure, go ahead.

**Comment by Shivansh2407** [comment]
So @bobsilverberg can you please help me like how should I proceed?
What needs to be done here?

**Comment by NitinMadhukar** [comment]
can i work on this ??

**Comment by bobsilverberg** [comment]
@NitinMadhukar Thank you for your interest, but there is already a contributor working on this. I suggest you look for available issues at https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22contrib%3A+welcome%22+

**Comment by bobsilverberg** [comment]
@Shivansh2407 Most of what needs to be done is described in the comments above at https://github.com/mozilla/addons-frontend/issues/9089#issuecomment-574361672. The code for the footer can be found in https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Footer/index.js, and there will likely also be style changes needed in https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/Footer/styles.scss to support another column.

**Comment by Shivansh2407** [comment]
Basically I need to make the footer in three parts right ?

**Comment by aarushivij** [comment]
Hey @Shivansh2407 are you still working on this?

**Comment by bobsilverberg** [comment]
> Basically I need to make the footer in three parts right ?

Correct. Now that the amount of information is greater, it was suggested that the footer be presented in 3 columns.

**Comment by AlexandraMoga** [comment]
This is how the footer looks with three columns. I didn't find any layout issues on the various screen sizes I've checked with.

![image](https://user-images.githubusercontent.com/31961530/75985941-d31b4680-5ef5-11ea-844d-eac759ec77b5.png)

From @jvillalobos instructions, I understand that the _Browser_ column should contain the same links promoted on [Firefox download page](https://www.mozilla.org/en-US/firefox/new/) footer instead of our old links:
![image](https://user-images.githubusercontent.com/31961530/75986256-6bb1c680-5ef6-11ea-9890-f9490c555396.png)

@jvillalobos should I also open an addons-server issue to change the footer links on [DevHub homepage](https://addons.allizom.org/de/developers/)?

**Comment by jvillalobos** [comment]
Yes, we should use the new links from the Firefox download page (with our UTM params added), and the header should be _Browsers_ (plural).

**Comment by jvillalobos** [comment]
> @jvillalobos should I also open an addons-server issue to change the footer links on DevHub homepage?

Yes, we should change that one too. Thanks.
