### ISSUE TITLE
Storybook is broken

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9092]
Our [Storybook](https://mozilla.github.io/addons-frontend/) is broken: it does not load because of a syntax error during
the initialization.

I noticed the issue while reviewing a Renovate PR to update one of the
Storybook dependencies. I think our Storybook has been broken for a
while now but it is hard to notice as we usually don't look at it and
the build did not failed.

The bug is caused by our main webpack config. We use a webpack plugin to
replace the `config` lib with our own version for the client side
(`config` being a server lib). Replacement is based on a regexp but,
because of it, a syntax highlighting file is "replaced" by "nothing" in
a sub-sub-sub-dependency of storybook. The file is named `dsconfig.js`
and the regexp matches `/config$/`.

This `dsconfig.js` file disappeared in the final bundle generated by
Storybook, preventing Storybook to load. Updating the regexp should
hopefully fix this issue.

**Comment by ioanarusiczki** [comment]
@willdurand Please add the qa not needed label. 
Thanks!
