### ISSUE TITLE
Enable feature to remove search tools in -stage

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9108]
Let's enable this feature in -stage to hide the search tools related pages/info.

**Comment by ioanarusiczki** [comment]
@willdurand 
Testing report on AMO stage with FF72(Win10):

- The OpenSearch plugins cannot be submitted (already available on prod) https://github.com/mozilla/addons-server/issues/12462 
- The OpenSearch plugins were deleted https://github.com/mozilla/addons-server/issues/12463
- Search Tools link from the 'More' menu was removed and the search results are no longer showing the type `Search tools` https://github.com/mozilla/addons-frontend/issues/8680
- The URLs mentioned by https://github.com/mozilla/addons-frontend/issues/8679 redirect as expected.
