### ISSUE TITLE
Enable feature to remove search tools in -prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9110]
Similar to https://github.com/mozilla/addons-frontend/issues/9108, we want to enable this feature in -prod too.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on prod with FF72(Win10). 
- I did not find `.xml` plugin formats while searching.
- the Search Tools link was removed from the `More` Menu.
- https://addons.mozilla.org/en-US/firefox/search-tools/ and https://addons.mozilla.org/en-US/firefox/search-engines/ redirect to the search tools extensions category. 
- I could not submit an `xml` plugin on prod.
