### ISSUE TITLE
Remove the `enableFeatureRemoveSearchTools` feature flag

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9112]
We enabled this feature in all envs in https://github.com/mozilla/addons-frontend/issues/9110, so we can safely remove the feature flag (and the if/else code) after today's push.

We want to remove the config for `enableFeatureRemoveSearchTools` as well as all the code that looks like `if (_config.get('enableFeatureRemoveSearchTools')) {`, etc.

**Comment by atiqueahmedziad** [comment]
I am working on it 😄

**Comment by Shivansh2407** [comment]
Can I work on this @muffinresearch ?

**Comment by willdurand** [comment]
> Can I work on this @muffinresearch ?

@Shivansh2407 no, sorry. This issue has already been assigned to someone.

**Comment by ioanarusiczki** [comment]
@willdurand There are no regressions. - FF72(Win10). 

The only thing which is still reproducible on dev (but it's from the last week and on AMO stage was not reproducible or in production) is that search results for plugins still show up (the autocomplete displays them) and then when the plugin is clicked there's a 404. 

An example: https://addons-dev.allizom.org/en-US/firefox/addon/eccellio/

**Comment by willdurand** [comment]
I guess that's a problem with our search service (ES).

**Comment by ioanarusiczki** [comment]
@willdurand I'm thinking to file an issue on the server repo maybe it does not take too much efforts to fix it ?

**Comment by ioanarusiczki** [comment]
I filed the followup on server 
https://github.com/mozilla/addons-server/issues/13382
