### ISSUE TITLE
Turn off non-recommended warning experiment

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9123]
Let's turn off the grey / yellow warning experiment for non-recommended extensions. For now, let's enable the grey warning for all users. Also, let's make sure we're not losing any of the data for future analysis. 

For QA:

This will disable the experiment, meaning that everyone should see the exact same thing, which is the newest version of the warning. It also should not be creating a cookie for anyone not already enrolled in the experiment.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on AMO dev and stage with FF72(Win10). 
- the experiment is no longer available on new profiles meaning that cookie is not created anymore
 and the GA events described in https://github.com/mozilla/addons-frontend/issues/8137#issue-452999111 are no longer sent. 
- on all pages with non-recommended add-ons the grey warning message is enabled. When the platform message is present the message is not displayed (as required in https://github.com/mozilla/addons-frontend/issues/8760#issue-505940596). 
- the grey message is enabled for older profiles too where there's a cookie such as `excludeWarning`. 

![the grey message](https://user-images.githubusercontent.com/33448286/73847861-c4c30780-482f-11ea-8970-cb8768c6112f.png)
