### ISSUE TITLE
Error from FingersCrossedReporter when a test fails

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9124]
When running a test via Jest, if the test fails we now see an error being generated from the `FingersCrossedReporter` as opposed to the failure from the test. It looks like `getConsoleOutput` is no longer available from `jest-util`, and that is causing an error at https://github.com/mozilla/addons-frontend/blob/master/tests/jest-reporters/fingers-crossed.js#L23.

Here's some example output:

```
 FAIL  tests/unit/amo/components/TestInstallWarning.js
 FAIL  tests/unit/amo/components/TestInstallWarning.js
  ● Test suite failed to run

    TypeError: getConsoleOutput is not a function

      21 |       // prettier-ignore
      22 |       this.log(
    > 23 |         `  ${TITLE_BULLET}Console\n\n${getConsoleOutput(
         |                                        ^
      24 |           config.cwd,
      25 |           !!this._globalConfig.verbose,
      26 |           consoleBuffer

      at FingersCrossedReporter.printTestFileHeader (tests/jest-reporters/fingers-crossed.js:23:40)
      at FingersCrossedReporter.onTestResult (node_modules/@jest/reporters/build/default_reporter.js:200:12)
      at ReporterDispatcher.onTestResult (node_modules/@jest/core/build/ReporterDispatcher.js:48:25)
      at onResult (node_modules/@jest/core/build/TestScheduler.js:193:30)

Test Suites: 2 failed, 2 of 1 total
Tests:       8 failed, 16 passed, 24 total
Snapshots:   0 total
Time:        3.641s
Ran all test suites matching /installw/i.

Flow: no errors 🌈  ✨

Eslint: no errors 💄 ✨

Watch Usage: Press w to show more.
```

I have confirmed that this regression occurred with the landing of https://github.com/mozilla/addons-frontend/commit/78f716e76b581a63aa8466105773b072252e6feb.

**Comment by bobsilverberg** [comment]
@willdurand I wonder if we should revert https://github.com/mozilla/addons-frontend/commit/78f716e76b581a63aa8466105773b072252e6feb until we have a fix for this?

**Comment by willdurand** [comment]
Looks like it is now part of `jest-console`, https://github.com/facebook/jest/blob/bcc2b103e14912cff566cbacb0c2c3871ecb0994/packages/jest-console/src/index.ts
