### ISSUE TITLE
Write tests for Jest reporters

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9127]
#9124 was an error in a Jest reporter that we use, which was not caught until it was found while running an interactive test. It would be nice to have unit tests for our Jest reporters. This issue is about investigating how to write tests for a Jest reporter and then, if feasible, creating some tests for them.

The reporters we use can be found in https://github.com/bobsilverberg/addons-frontend/tree/master/tests/jest-reporters

**Comment by virgilt** [comment]
@bobsilverberg May I work on this?

**Comment by bobsilverberg** [comment]
> @bobsilverberg May I work on this?

If you'd like to give it a try, you may. It's not a particularly small or simple issue, but if you're interested in figuring out how to write tests for Jest reporters, please feel free to do so.

**Comment by virgilt** [comment]
@bobsilverberg Yes, it didn’t sound like a simple proposition but that’s why I want try it.
