### ISSUE TITLE
Enforce naming convention for experiment ids

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9137]
This is a follow-up to #9125 

In order to reduce the possibility of collisions of experiment ids we are going to adopt a naming convention for experiment ids. The convention is `YYYYMMDD_experimentName`, where `YYYYMMDD` is the date that the `id` was added.

This issue is about adding code to [`withExperiment`](https://github.com/mozilla/addons-frontend/blob/master/src/core/withExperiment.js) to enforce this naming convention, and the patch should include a test to show the convention is enforced.

**Comment by imskr** [comment]
I would like to work on this!

**Comment by bobsilverberg** [comment]
@imskr You can work on this if you like, but it is not one of our issues labelled specifically for contributors. We have a number of issues that have been identified as good for contributors, and those can be found at https://github.com/mozilla/addons-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22contrib%3A+welcome%22

**Comment by bobsilverberg** [comment]
@willdurand further to https://github.com/mozilla/addons-frontend/issues/10188#issuecomment-796759761, this issue is about enforcing a naming pattern, but we also need to enforce uniqueness, which may be implied by this issue, but not explicitly called out.

This is also a discussion there of keeping a record of these ids forever, whereas now we delete them. Are you in favour of keeping them forever, and if so, are you okay with these simply existing in a config variable, or should we use a separate file for them?

**Comment by willdurand** [comment]
> This is also a discussion there of keeping a record of these ids forever, whereas now we delete them. Are you in favour of keeping them forever, and if so, are you okay with these simply existing in a config variable, or should we use a separate file for them?

well, the proposed pattern is to use a date, which is a fairly unique. Why would we keep record of ids, though? That does not seem very useful or needed.

**Comment by bobsilverberg** [comment]
> > This is also a discussion there of keeping a record of these ids forever, whereas now we delete them. Are you in favour of keeping them forever, and if so, are you okay with these simply existing in a config variable, or should we use a separate file for them?
> 
> well, the proposed pattern is to use a date, which is fairly unique. Why would we keep record of ids, though? That does not seem very useful or needed.

It's to ensure uniqueness. Our test can check the pattern, but it won't do anything with a specific date, so it's theoretically possible that someone could add an experiment to the file with a date that was used in the past. I know this seems unlikely, but this type of user error is not impossible. I guess it would have to get past a code review, which would likely catch it though. I'm just trying to make it foolproof.

**Comment by willdurand** [comment]
> Our test can check the pattern, but it won't do anything with a specific date, so it's theoretically possible that someone could add an experiment to the file with a date that was used in the past. I know this seems unlikely, but this type of user error is not impossible. I guess it would have to get past a code review, which would likely catch it though. I'm just trying to make it foolproof.

Given the number of times we run experiments, I think we can start without such a complicated setup and revisit it later.
