### ISSUE TITLE
The layout of the homepage is broken on AMO dev 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9182]
STR;
1. Open a new tab and load AMO dev

Expected result:
No layout issues

Actual result:
The layout is broken - I receive 404s in the Network for the css files

Notes:
I could only reproduce it on AMO dev - every time in a new tab when I first load AMO.
Refreshing page works. 

![broken css](https://user-images.githubusercontent.com/33448286/75329304-16d3d780-5888-11ea-964d-965537521db8.png)

**Comment by diox** [comment]
Seeing it after a hard-refresh. `None of the “sha512” hashes in the integrity attribute match the content of the subresource.` in the console, 404s similar to what @ioanarusiczki screenshot shows.

**Comment by ioanarusiczki** [comment]
@diox I could not reproduce it on AMO stage not even once while making release testing today.

**Comment by bobsilverberg** [comment]
I landed a bunch of dependency updates after the tag, but we have also discovered that the tag for frontend doesn't seem to include all the commits it needs, which would be another explanation for stage being different from dev. 

Having said that, the 404 for css files does sound like a deploy issue rather than a code issue.

**Comment by bobsilverberg** [comment]
I just pushed a new tag for addons-frontend, which should deploy to stage sometime soon. @ioanarusiczki I'm afraid that the release testing you've done thus far on stage were against an old version, so I think you may need to redo that once the new tag lands.

**Comment by bobsilverberg** [comment]
This seems to be fixed after the last deploy to dev. Can you verify @ioanarusiczki?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yes, I did not see it reproducible on AMO dev. - FF73(Win10).
