### ISSUE TITLE
Cherry-pick German and French translations needed for platform warnings

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9194]
There will not be any code landing for this specific issue, it's a placeholder to remember to do these two cherry-picks.

The German one is already available at https://github.com/mozilla/addons-frontend/commit/8b5a6ee0d8f78892ca268994f4d737bd9ef2d8ed

There are actually 3 French commits we need to cherry-pick:
- https://github.com/mozilla/addons-frontend/commit/ba1bc2d6404cc8274df001daf88ac61410314348
- https://github.com/mozilla/addons-frontend/commit/6ec0dec6695a13135902f00b66051340c17cc2c3
- https://github.com/mozilla/addons-frontend/commit/a18d4a6e48467bd01f8cb229403aa42a3df66a67

For QA:

Please verify that French and German translations exist for the messages discussed in https://docs.google.com/document/d/100dVSbAnp2irHUQXhCX_bkF-AyIuwbzIlSGa9EkcR1E/edit#

**Comment by bobsilverberg** [comment]
I have cherry picked everything needed to bring in the new translations for French and German. I needed a few more commits than those listed above, but I recorded everything in https://github.com/mozilla/addons/blob/master/releases/2020/03/05.md.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Translations are available on dev and stage for fr and de. I don't speak them but I'm sure they do not look exactly like the doc mentions them https://docs.google.com/document/d/100dVSbAnp2irHUQXhCX_bkF-AyIuwbzIlSGa9EkcR1E/edit so I hope they're alright.

Fenix - German
![Android - German for Fenix](https://user-images.githubusercontent.com/33448286/76005701-1389bd00-5f14-11ea-9ec0-3a81dff718ad.png)

Fennec - German 
![Android German for Fennec](https://user-images.githubusercontent.com/33448286/76005752-22706f80-5f14-11ea-9e43-c1e724850c6d.png)

Fenix - French
![Android french for Fenix](https://user-images.githubusercontent.com/33448286/76005785-2e5c3180-5f14-11ea-81e4-81dc2b69a5a6.png)

Fennec - French
![Android Fennec in french](https://user-images.githubusercontent.com/33448286/76005816-3916c680-5f14-11ea-9392-19db13e6f3a2.png)

iOS - German
![iOS German](https://user-images.githubusercontent.com/33448286/76005976-7bd89e80-5f14-11ea-87b5-503da23a523a.png)

iOS - French
![iOS French](https://user-images.githubusercontent.com/33448286/76006027-8e52d800-5f14-11ea-8565-f52af9b19e30.png)

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. We do not expect them to look exactly the same as in the doc, so all is fine.
