### ISSUE TITLE
Integration tests are failing on circle ci

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9195]
The integration tests have been failing consistently on circle ci since https://github.com/mozilla/addons-frontend/commit/8b1cd65fac8576d37d883f2d4550a40719f86dcb. I'm guessing it might have to do with the fact that the footers changed, and maybe the tests are trying to verify something about the footer?

cc @jrbenny35

**Comment by jrbenny35** [comment]
This is correct.

This line should be changed to match the "Browser" section: https://github.com/mozilla/addons-frontend/blob/master/tests/frontend/ui/pages/desktop/base.py#L176

And this line should be removed as there are only 5 links within this section now: https://github.com/mozilla/addons-frontend/blob/master/tests/frontend/ui/test_home.py#L95

**Comment by jrbenny35** [comment]
@bobsilverberg can you work on this?

**Comment by willdurand** [comment]
I'll take a lopk
