### ISSUE TITLE
Footer links headers should have the same font-size

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9197]
Follow up for #9089 

### Describe the problem and steps to reproduce it:
1. Open AMO stage
2. Scroll down to the footer section
3. Observe the `font-size` used for the footer links headers

### What happened?
The `font-size` is `16px` for Add-ons and `14px` for Browser and Products

### What did you expect to happen?
We should have the same size for all the headers. I think `16px` is preferable. 

![image](https://user-images.githubusercontent.com/31961530/75984305-d2cd7c00-5ef2-11ea-9418-8c9cccbd3965.png)

**Comment by ajinkabeer** [comment]
Hello @AlexandraMoga. I am an outreachy applicant. Can I work on this issue please?

**Comment by bobsilverberg** [comment]
Thanks for filing this issue @AlexandraMoga. I agree that 16px seems like the correct value, as that is what the older "Firefox" heading used before this change.

**Comment by ajinkabeer** [comment]
I found that the header `'Add-ons'` is wrapped inside a `Link` element within an `h4` whereas `Browser` and `Products` are simply wrapped inside an h4 without `Link`.

So should the headers be links or just h4 elements?
@bobsilverberg

**Comment by AlexandraMoga** [comment]
Verified fixed on stage:

![image](https://user-images.githubusercontent.com/31961530/76425523-6b13a700-63b2-11ea-9965-6e4e0c5e8753.png)
