### ISSUE TITLE
Update footer links from the 'Browsers' column to match those from Firefox download page

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9200]
Follow up for #9089 

### Describe the problem and steps to reproduce it:
1. Open AMO stage
2. Scroll down to the footer section
3. Observe the links under the _Browser_ column

### What happened?
The column is still referencing the old Browser links used previously by the AMO footer

### What did you expect to happen?
The column should reference the links present in [Firefox download page](https://www.mozilla.org/en-US/firefox/new/) footer. Also, the column header should be named _Browsers_ instead of _Browser_

### Anything else we should know?
From https://github.com/mozilla/addons-frontend/issues/9089#issuecomment-595336205
> Yes, we should use the new links from the Firefox download page (with our UTM params added), and the header should be _Browsers_ (plural).

[current footer column]
![image](https://user-images.githubusercontent.com/31961530/76070169-bd149100-5f9c-11ea-8ab5-3b5ea5eec79e.png)

[expected footer column]
![image](https://user-images.githubusercontent.com/31961530/76070193-c7368f80-5f9c-11ea-8ef0-b59423c5d7a9.png)

**Comment by ajinkabeer** [comment]
Hello @AlexandraMoga, I think I can work on it if it's possible.

**Comment by muznahaftab** [comment]
Hey @AlexandraMoga I'm an outreachy applicant. Can I work on this issue?

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/77314782-fe33d180-6d0e-11ea-94f0-a3bd75af4698.png)
