### ISSUE TITLE
Strip style attributes from HTML tags in add-on description

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#921]
The old [addons-server code](https://github.com/mozilla/addons-server/blob/master/src/olympia/translations/models.py#L174) stripped all HTML tag attributes (with some exceptions). This would strip out any `style` attributes. Even though we're using a dom-purify on `addons-frontend`, it doesn't strip `style` attributes. I don't know how serious it is because I can't think of a real XSS. However, there may be a possibility by crafting an add-on that has something like this in the description:

```
<b style="background-image: url(javascript:alert(document.cookie))">placeholder</b>
```

**Comment by muffinresearch** [comment]
Looks like we could default to removing style attrs using `FORBID_ATTR`.

Fwiw: their docs also has a relevant snippet about CSS attacks: 

> DOMPurify will NOT protect against CSS-based XSS attacks that work in ancient IE/Mozilla/Opera browsers or similarly ancient IE document modes. If you want to prevent attacks using @import in <style> elements or x:expression(alert(1)) in <style> or style attributes, please remove them from the white-list using the config options! As a matter of fact, DOMPurify will not even work (a.k.a fall-back to toStaticHTML) in these older modes and browsers where those attacks are possible as they are considered legacy and should not be used. See also: H5SC CSS Attacks

**Comment by kumar303** [comment]
seems like this is low risk (because CSP disallows inline style) but it would be an easy fix so we should do it
