### ISSUE TITLE
Serve details of blocked addons from AMO directly

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#9216]
we need an endpoint setting up that will serve details of blocked addons.  Needs to be something that accepts a guid + version, either as GET params or url components

**Comment by willdurand** [comment]
Marking as p3 for now. It needs API unless there is some sort of API spec somewhere.

**Comment by willdurand** [comment]
@jvillalobos under which URL path should these pages live now? And do we need to serve them from the `blocked.cdn...` domain or `a.m.o`?

@muffinresearch @diox I guess if we're still using the `blocked` CDN domain, we can use any URL path in the frontend as there will be some nginx redirect/config involved, no?

**Comment by jvillalobos** [comment]
Ideally I'd go with something like `AMO/blocked`, but I don't know the technical implications of that and wouldn't mind if we have to keep the old URL.

**Comment by eviljeff** [comment]
I think aiming to redirect urls from https://blocked.cdn.mozilla.net/ shouldn't be a goal here.  And can't be, practically, because the blocklist on AMO contains different data than the v1 blocklist data stored on kinto.  Things we don't have on AMO:
- blocks relating to addons that don't exist somewhere in AMO's database (i.e. they've been hard-deleted from the db at some point).  As currently implemented, the `import_blocklist` command wouldn't import them.
- a one-to-one relationship between the legacy id in kinto and a single add-on.  A single "block" in kinto can contain a regular expression that could match any number of guids.  (The oldest blocks - that were originally imported from AMO years back - use yet another style of id in the urls too)

If we're not willing to just to drop https://blocked.cdn.mozilla.net when the v2 blocklist is deprecated (or replace it with entirely static pages) then I'd implement the redirection (with frontend support for multiple responses per legacy id) in a followup in Q2.

**Comment by willdurand** [comment]
So we would likely create a new page for the AMO blocklist using data coming from the API, right? No backward compatibility?

I guess we could:

1. keep the blocklist cdn for the blocklist v1 (if I understood correctly the versioning scheme)
2. create a new blocklist page for the AMO blocklist, available at `/blocked/<id>` (with `id` being a `guid` (and a `versionId` as well? Optionally or all the time?)
3. aggressively cache these new frontend pages?

**Comment by diox** [comment]
Yeah I wouldn't re-use `blocked.cdn.mozilla.net` for v3, just serve from `addons.mozilla.org` under some path and aggressively cache at nginx level.

**Comment by willdurand** [comment]
API is about to land.

**Comment by willdurand** [comment]
@jvillalobos et al. WDYT?

![Screen Shot 2020-03-16 at 16 43 17](https://user-images.githubusercontent.com/217628/76775193-4ac65c80-67a5-11ea-8e9d-07efc9ad7c3a.png)

**Comment by willdurand** [comment]
Question: the API exposes min/max versions, do we need to display these values somewhere?

**Comment by eviljeff** [comment]
"Add-ons" and violating "multiple policies" - it'd just be a single add-on that possibly only violated one policy?

Not sure if we need to expose the guid somewhere (I do think we need to make it clear what versions are blocked)

**Comment by jvillalobos** [comment]
Looks good!

"Add-ons violating multiple policies" is in the name field for some blocks. Presumably the new blocks would just show the add-on name there instead.

We could add the versions blocked directly above the last line. Something like 

> Versions blocked: %(min) to %(max).
> Blocked on %(date). View block request.

I don't think we need to include the GUID.

**Comment by willdurand** [comment]
> "Add-ons violating multiple policies" is in the name field for some blocks. Presumably the new blocks would just show the add-on name there instead.

Good idea so we need to expose the add-on name in the API. /cc @eviljeff 

> We could add the versions blocked directly above the last line. Something like
> 
> > Versions blocked: %(min) to %(max).
> > Blocked on %(date). View block request.

:+1:

**Comment by willdurand** [comment]
Updated preview:

![Screen Shot 2020-03-16 at 19 13 39](https://user-images.githubusercontent.com/217628/76787974-57a17b00-67ba-11ea-8d64-e00ec32c5082.png)

Note: the blocklist API does not expose the add-on name yet so it isn't there. I think we should expose it in the API response, though. That will save an API call and more frontend complexity.

**Comment by willdurand** [comment]
Other question: the `reason` seems to be optional, so what would be a good fallback? For now, I have:

> This add-on violates Mozilla’s add-on policies.

**Comment by jvillalobos** [comment]
Looks good. I'd tweak it to:

> This add-on violates [Mozilla's Add-on Policies](https://extensionworkshop.com/documentation/publish/add-on-policies/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=blocked-addon).

I'm also thinking it should be included regardless of there being a custom `reason` or not. It would be the first paragraph, and then the `reason` would be the second paragraph, if present. /cc @wagnerand @caitmuenster

**Comment by willdurand** [comment]
>     * The pages will need access by block ID (to support the legacy blocklist, unless we intend to keep the old pages for that), or add-on ID for v3. I don't think we need the version number, given there should only be one block per add-on ID.

@jvillalobos currently, the URL takes the GUID as parameter. Should we change that?

**Comment by jvillalobos** [comment]
Pre-v3 versions of Firefox will link to pages like https://blocked.cdn.mozilla.net/41a53d4b-120a-4ab0-9dbc-8a8d3802b734.html, using the `blockId`, which I assume will redirect to the AMO pages. So, I think we'll need to support the old block IDs somehow.

**Comment by eviljeff** [comment]
> Pre-v3 versions of Firefox will link to pages like https://blocked.cdn.mozilla.net/41a53d4b-120a-4ab0-9dbc-8a8d3802b734.html, using the `blockId`, which I assume will redirect to the AMO pages. So, I think we'll need to support the old block IDs somehow.

Handling redirects from https://blocked.cdn.mozilla.net isn't part of the MVP for early April though, is it?  It's problematic because of the things I mentioned https://github.com/mozilla/addons-frontend/issues/9216#issuecomment-598465968

**Comment by jvillalobos** [comment]
Ah, I think I misread some of the backlog. If we're keeping https://blocked.cdn.mozilla.net for the older clients, then we don't need to worry about the `blockID` in the new version.

**Comment by willdurand** [comment]
> Good idea so we need to expose the add-on name in the API. /cc @eviljeff

I filed https://github.com/mozilla/addons-server/issues/13757

**Comment by willdurand** [comment]
> I'm also thinking it should be included regardless of there being a custom `reason` or not. It would be the first paragraph, and then the `reason` would be the second paragraph, if present. /cc @wagnerand @caitmuenster

Ok, that sounds good. Thanks

**Comment by willdurand** [comment]
> Ah, I think I misread some of the backlog. If we're keeping [blocked.cdn.mozilla.net](https://blocked.cdn.mozilla.net) for the older clients, then we don't need to worry about the `blockID` in the new version.

Indeed, we keep the blocked CDN as is. /cc @diox

**Comment by willdurand** [comment]
Latest UI state:

![Screen Shot 2020-03-18 at 10 15 45](https://user-images.githubusercontent.com/217628/76944540-7cecd100-6901-11ea-8b42-9c8fd51f1a3f.png)

**Comment by willdurand** [comment]
**Question:** I am thinking about feature-flagging this new page? Does that make sense?

**Comment by eviljeff** [comment]
> 
> 
> Latest UI state:
> 
> ![Screen Shot 2020-03-18 at 10 15 45](https://user-images.githubusercontent.com/217628/76944540-7cecd100-6901-11ea-8b42-9c8fd51f1a3f.png)

can you highlight which text is coming from block.reason?

**Comment by willdurand** [comment]
> can you highlight which text is coming from block.reason?

`block.reason` is the second paragraph in the first section. I added a new screenshot with the loading state so hopefully it is a bit more obvious.

**Comment by AlexandraMoga** [comment]
@willdurand what's the URL for the block page? I can seem to find it mentioned in the comments above.

**Comment by willdurand** [comment]
@AlexandraMoga sorry, it is `/blocked/{guid}/`.

**Comment by AlexandraMoga** [comment]
@willdurand  I'm receiving a redirect to `https://blocked.stage.mozaws.net/{guid}/.html`. The exact URL I was using: `https://addons-dev.allizom.org/en-US/firefox/blocked/{guid}/`

**Comment by willdurand** [comment]
> @willdurand I'm receiving a redirect to `https://blocked.stage.mozaws.net/{guid}/.html`. The exact URL I was using: `https://addons-dev.allizom.org/en-US/firefox/blocked/{guid}/`

Ugh, right. It turns out that we are already using this path for the (kinto) blocklist... I guess we would need to find a new path :|

**Comment by bqbn** [comment]
> Another separate consideration is caching these pages via nginx like we do for the disco pane. That way we won't hit the appserver / db hard if a block sees a lot of traffic for any reason.

Agreed! And I asked a question in https://bugzilla.mozilla.org/show_bug.cgi?id=1624357#c1 to the similar concern. Can someone tell me exactly which endpoints need to be aggressively cached?

Please comment in either the bugzilla ticket or here to let us know.

Thanks!

**Comment by willdurand** [comment]
@AlexandraMoga we added a second path to browse these pages in https://github.com/mozilla/addons-frontend/issues/9269 so that you can verify the feature.

**Comment by AlexandraMoga** [comment]
I've verified the new blocklist pages with several block examples. The page  is public, it can be accessed by all users (authenticated or not). 

I haven't noticed issues with the page layout and all links are functional*

![image](https://user-images.githubusercontent.com/31961530/77436201-e1210080-6deb-11ea-8de5-69776f888504.png)

@willdurand *since the URL field is optional in blocklist admin, there could be cases when that field will be empty. Currently, the block addon page is displaying the 'View block request' link even if the URL is empty. When clicked, the link falls back to AMO homepage.
Could we hide that link  when there is no URL given?

**Comment by willdurand** [comment]
> @willdurand *since the URL field is optional in blocklist admin, there could be cases when that field will be empty. Currently, the block addon page is displaying the 'View block request' link even if the URL is empty. When clicked, the link falls back to AMO homepage.
> Could we hide that link when there is no URL given?

ah, that looks like a bug. The link was supposed to be hidden in that case (and I thought we had a unit test for it, ugh)

**Comment by AlexandraMoga** [comment]
Filed #9272
