### ISSUE TITLE
Make the rev tools access visible from AMO homepage for ReviewerTools:View

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9219]
Followup for : https://github.com/mozilla/addons-server/issues/13652

1. Login on AMO frontend with a user that has the ReviewerTools:View permission - this user has access to all rev tools queues in read only. 
2. Observe the drop down menu below the user name

Expected result:
Reviewer Tools is displayed in the menu below Manage my Submissions.

Actual result:
The Rev tools link is missing. 

Expected result:
Rev tools link is available. 

Notes:
Reproducible on dev with FF73(Win10). 
The rev tools link is only present in dev hub for the specified users. 

![user who can view](https://user-images.githubusercontent.com/33448286/76513313-cbf8b900-645e-11ea-9f11-60d1c33e1fb3.gif)

**Comment by willdurand** [comment]
This will be fixed by #9218

**Comment by ioanarusiczki** [comment]
@willdurand Verified on dev with FF74(Win10). 

![reviewers](https://user-images.githubusercontent.com/33448286/76754740-4725dc00-678b-11ea-85b2-0cfdca9b7fe4.gif)
