### ISSUE TITLE
Clean up unused code around opensearch plugins

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#9222]
Frontend version of https://github.com/mozilla/addons-server/issues/13729

All code supporting opensearch plugins should be removed from addons-frontend since we are no longer supporting these.

To get started, search for uses of `ADDON_TYPE_OPENSEARCH` and `INCOMPATIBLE_NO_OPENSEARCH` in addons-frontend and adjust the code to be able to remove those constants.

**Comment by ajinkabeer** [comment]
Hey @diox, I am outreachy applicant. I would like to take work on this issue if that's alright. :)

**Comment by willdurand** [comment]
@ajinkabeer if you are familiar with javascript/react, then I'd say go ahead. If not, this might be a bit involved.

**Comment by ajinkabeer** [comment]
Thanks @willdurand. I'll take a look.

**Comment by ioanarusiczki** [comment]
@willdurand I tested on dev with FF74(Win10) around what was mentioned it the [requirements](requirement) and I did not find issues/regressions.
