### ISSUE TITLE
Pass `src` query parameter to custom license pages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9227]
### Describe the problem and steps to reproduce it:

1. Browse a detail page of an add-on with a custom license (page). Make sure to have a `src` query parameter in the URL. See: https://github.com/mozilla/addons-frontend/issues/9054#issuecomment-599506137

### What happened?

The `src` query parameter is not passed to this page.

### What did you expect to happen?

The `src` query parameter is passed.

### Anything else we should know?

no.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![2020-03-17_10-12-45](https://user-images.githubusercontent.com/31961530/76835510-e86a6c00-6837-11ea-8a0b-04710dda7626.gif)
