### ISSUE TITLE
The photo section's layout is broken on dev on edit profile page

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9237]
I think it's a regression caused by https://github.com/mozilla/addons-frontend/issues/7880

STR:
1. Go to edit my profile and add an image 
2. Observe the page

Expected result:
No layout issues

Actual result:
The layout is broken. 

Examples:
![on dev profile picture](https://user-images.githubusercontent.com/33448286/76961755-96ecda80-6926-11ea-8520-421732521dc0.png)

for a larger image 

![test](https://user-images.githubusercontent.com/33448286/76961878-d87d8580-6926-11ea-8763-344c3428f58f.png)

The issue is not reproducible on stage with FF74(Win10). 

![on stage profile picture](https://user-images.githubusercontent.com/33448286/76961908-e7643800-6926-11ea-9b0c-46c43bc5a7bb.png)

**Comment by willdurand** [comment]
oh, interesting.

**Comment by ioanarusiczki** [comment]
@willdurand This is no longer reproducible on dev with FF74(Win10). 

![fine on AMO dev](https://user-images.githubusercontent.com/33448286/77400668-33462f80-6db4-11ea-941b-8820d101559c.png)
