### ISSUE TITLE
Update `SearchTools` page component

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9248]
The `SearchTools` component continues to render a list of extensions but only when we navigate to the page in the client, which shouldn't be possible anymore.

We should change the behavior of this component to return a `NotFound` component instead.

**For QA:** I think adding a link to `/search-tools/` somewhere (like in an add-on detail page or something) would allow you to navigate to the search tools page with client side navigation. We shouldn't have a page with search results anymore but a 404 should be rendered instead (we cannot perform a redirect from the client).

**Comment by Albaalah** [comment]
Hi @willdurand , can I work on this?

**Comment by willdurand** [comment]
> Hi @willdurand , can I work on this?
i
This issue is for outreachy applicants. If you're not an outreach applicant, 
you can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by Albaalah** [comment]
@willdurand let me introduce myself. I'm albaalah, an Outreachy applicant. I would like to work on this issue as a part of my application process, please. Thank you

**Comment by willdurand** [comment]
@Albaalah ah, cool! Then I guess it is fine to start with this issue if you already know JavaScript and React. In any case, the first step would be to install and run this project locally. How does that sound?

**Comment by Albaalah** [comment]
@willdurand I am familiar with JavaScript and React. I have successfully installed and run the project locally. I have tried to reproduce the issue and I'm confused with what we mean by _but only when we navigate to the page in the client_. Could you kindly explain the issue a bit more maybe with a screenshot, please?

**Comment by Albaalah** [comment]
tagging you again @willdurand in case you missed my comment above :)

**Comment by willdurand** [comment]
Yes, I think you can trigger the bug by setting `disableSSR: true` in the `config/default.js` file.

**Comment by Albaalah** [comment]
I will be busy for the next couple of days so if any other Outreachy applicant is looking at this issue and wants to work, I'm currently not working on it so this is available for you to take

**Comment by amo-ali** [comment]
@willdurand I'm Amna Ali, an Outreachy applicant. I am familiar with JavaScript. i use JavaScript in web designing. I would like to work on this issue as a part of my application process, please Thank you

**Comment by amo-ali** [comment]
@willdurand i know only half day left to submit my contribution. but i talk to outreachy organizer, they said if mentor allow you then you have time till 14 April to submit your first contribution. Please give me one chance to do this. i will send you an outreachy organizer's email if you want to proof.

**Comment by willdurand** [comment]
> @willdurand i know only half day left to submit my contribution. but i talk to outreachy organizer, they said if mentor allow you then you have time till 14 April to submit your first contribution. Please give me one chance to do this. i will send you an outreachy organizer's email if you want to proof.

Hey @amo-ali, I am sorry but we believe that you won't have enough time to contribute to this project and submit your application, even with +7 days. It takes time to setup this project and understand how to contribute to it.

If you want to contribute to this project, you're very welcome but I don't think you should rush to submit your Outreachy application, it's too late for this round.

**Comment by amo-ali** [comment]
@willdurand  can you please tell me which project can take 7 day to complete? because its my last chance and i don't want to loss. Please help me

**Comment by amo-ali** [comment]
@willdurand  please help me to contribute in this project. if i will not select in any project outreachy project, i want to volunteer work in it and want your help to contribute in this project.

**Comment by bhushan-borole** [comment]
Hello @willdurand.
Can I work on this issue?

**Comment by willdurand** [comment]
> Hello @willdurand.
> Can I work on this issue?

Yep, go ahead

**Comment by bhushan-borole** [comment]
> Yes, I think you can trigger the bug by setting `disableSSR: true` in the `config/default.js` file and then go to: http://localhost:3000/en-US/firefox/search-tools/ (locally)

@willdurand 
Is this the correct approach to reproduce the bug?

**Comment by willdurand** [comment]
>  Is this the correct approach to reproduce the bug?

I think so yes

**Comment by bhushan-borole** [comment]
> > Is this the correct approach to reproduce the bug?
> 
> I think so yes

Thank you, will setup the project locally, and start working on this issue.

**Comment by bhushan-borole** [comment]
@willdurand 
This component should be returned right instead of search results?
https://github.com/bhushan-borole/addons-frontend/blob/master/src/amo/components/Errors/NotFound/index.js

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've added a link to `/search-tools/` in an add-on detail page (in description), as the STR suggested, and these are my results:

[Example from  -dev](https://addons-dev.allizom.org/en-US/firefox/addon/check-compatibility/): the `/search-tools/` link is redirecting to the Search Tools extension category page - https://addons-dev.allizom.org/en-US/firefox/extensions/category/search-tools/.
I've also added a link to each extension category we support and noticed that we also have a redirect for Bookmarks.
The rest of the categories will lead to a 404 page instead, i.e. there is no redirect to the corresponding extension category page. The same goes for Themes. 

So, what should be the expected behavior here? Should there be a redirect for all categories or should we always display a 404?

**Comment by bobsilverberg** [comment]
@AlexandraMoga I don't think the links you added for `search-tools` to that page are working the way you are expecting. As they are fully-qualified URLs, they are doing a true navigation, so the redirect code on the server is firing, which is giving you the redirect to the new URL. They are not testing client-side navigation.

As for the other links, it is not expecting that a link like `https://addons-dev.allizom.org/appearance/` would redirect. It is missing the add-on type. I don't know why the `bookmarks` one is redirecting - perhaps we have a special rule set up in nginx for this?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I'm not sure I follow. Instructions say to add `/search-tools/` somewhere on the detail page. If I navigate from another page (such as the search results https://addons-dev.allizom.org/en-US/firefox/search/?q=leoper-apecker-carose) to this one and click on https://addons-dev.allizom.org/search-tools/ I will get a redirect to https://addons-dev.allizom.org/en-US/firefox/extensions/category/search-tools/. Instructions say I should get a 404.  Is the format of the URL not good or the way I've tested it?

**Comment by bobsilverberg** [comment]
@ioanarusiczki The instructions are not accurate in that it's not possible to simply add a link to a page in order to test this. I'm going to just make it QA: not needed, as it's been tested locally and it's also something that should actually never happen.
