### ISSUE TITLE
Add add-on name to the `Block` page

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9249]
The API now exposes the add-on name for a block: https://github.com/mozilla/addons-server/issues/13757. This issue is about using this name in the `Block` page.

Note: it is possible that some blocks won't have a name (it will be set to `null` in the API response). In this case, we'll display a generic message.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev.
The add-on name is displayed in the page title and in the card header:

[with add-on name present]
![image](https://user-images.githubusercontent.com/31961530/77441709-69a29f80-6df2-11ea-9adf-75d9c1cf553b.png)

[with add-on name `null`]
![image](https://user-images.githubusercontent.com/31961530/77441690-64455500-6df2-11ea-9a77-ba2a212f104e.png)
