### ISSUE TITLE
Show "all versions" when a block has min = 0 and max = *

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9250]
See: https://github.com/mozilla/addons-frontend/pull/9236#discussion_r394357051

---

Instead of showing:

> Versions blocked: 0 to *

let's show:

> Versions blocked: all versions

in the newly added "block" page.

URL of a block in local dev (when using `yarn amo:dev` locally): http://localhost:3000/en-US/firefox/blocked/%7B46551EC9-40F0-4e47-8E18-8E5CF550CFB8%7D/

**Comment by valkyr13** [comment]
@willdurand can i work on this?

**Comment by willdurand** [comment]
I think so but https://github.com/mozilla/addons-frontend/pull/9236 has to land first.

**Comment by muskangupta-iitr** [comment]
@willdurand Is there any UI for this particular task?

**Comment by willdurand** [comment]
> @willdurand Is there any UI for this particular task?

No. It's the textual content that needs to be updated when `min_version` is equal to 0 *and* `max_version` is equal to `*`.

**Comment by Albaalah** [comment]
can I work on it, please?

**Comment by willdurand** [comment]
> can I work on it, please?

sorry, no. this one is assigned to @muskangupta-iitr

**Comment by Albaalah** [comment]
Didn't see it assigned to anyone which is why I asked :) got it, thanks

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/77634430-9d4c0980-6f59-11ea-9d72-5a1ac4278c4d.png)
