### ISSUE TITLE
[warning] Console warning for adding key in the SiteNoticesBase

### ISSUE THREAD

**Issue by muskangupta-iitr** [mozilla/addons-frontend#9255]
### Describe the problem and steps to reproduce it:
There is warning coming in logs for adding a unique key to the list items in SiteNoticesBase component.
Here is the Screenshot:

![Screenshot from 2020-03-22 20-42-35](https://user-images.githubusercontent.com/50856599/77253380-ba45bb80-6c7f-11ea-9666-3333b0de205e.png)

I would like to solve this issue!

**Comment by willdurand** [comment]
**For QA:** please make sure the site notices can still be displayed. There are 2 notices:

- the one we see in the screenshot attached above
- the read-only one

Ideally we should test without notices, with 1 notices and with the 2 notices. There should be no visual regression and I think testing the homepage and one other page should be enough.

**Comment by ioanarusiczki** [comment]
@willdurand I tested with the site notice and without it - looks alright to me. 

I think that the read only warning cannot be set using admin tools. Can you help?

**Comment by ioanarusiczki** [comment]
@willdurand no regressions - checked on dev with FF74(Win10). 

![notices](https://user-images.githubusercontent.com/33448286/77526020-9908e900-6e92-11ea-9df0-2f3ef02b2862.png)
