### ISSUE TITLE
The user cannot log back in from the frontend pages after an admin resets their session

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9260]
Followup for https://github.com/mozilla/addons-server/issues/13705
STR:
1. A new button was introduced in admin tools - Reset session(s)
2. Click a link from the user profile drop down menu such as my collections, click the FF logo to reload AMO 
3. Try to log out

Expected result:
The user should be redirected to the fxA page to log back in. 

Actual result:
The user receives "Incorrect authentication credentials." warning message and cannot log out.

Notes:
The issue is also reproducible when a user is banned. - FF74(Win10)
As a workaround the user can navigate to dev hub and log in from there.

![cannot log out](https://user-images.githubusercontent.com/33448286/77308078-13a2fe80-6d03-11ea-97a7-7270e26030a4.gif)

**Comment by willdurand** [comment]
@diox I lowered the priority because it shouldn't affect legit users.

**Comment by diox** [comment]
It can affect legit users: admins will typically use this if an account has been taken over by a malicious third party. Obviously in this case we don't care about errors seen by the third party after the sessions has been reset, but we need the legitimate user owning the account to be able to log back in as well.

IMHO, regardless of the result of the logout API call attempt, addons-frontend should forget the token it has for the user, forcing a logout no matter what. That should be sufficient to work around this issue.

**Comment by willdurand** [comment]
> we need the legitimate user owning the account to be able to log back in as well in case they still had a valid session.

Right. Clearing the cookies is enough to fix the problem (workaround).

**Comment by willdurand** [comment]
> IMHO, regardless of the result of the logout API call attempt, addons-frontend should forget the token it has for the user, forcing a logout no matter what. That should be sufficient to work around this issue.

I started to look into this and this is not trivial. The idea is to catch 401 errors and force logout the user + clear the auth cookie. This will only happen on the server, so users might still have to refresh the page to fix the issue mentioned in the OP.

**Comment by willdurand** [comment]
Ha wait, I missed something in your comment. Indeed, maybe we could force logout on the client all the time. That's a good idea and it is much simpler, thanks.

**Comment by willdurand** [comment]
I think if the user reloads the page, then it is possible to log in again (at least that's what I was able to do after having followed the STR in the OP). There is no need to clear the cookies.

**Comment by ioanarusiczki** [comment]
@willdurand If the session is reset and I try to update collections or the profile I will encounter again the message "Incorrect authentication credentials". I have now the option to logout and login again. Or if I refresh the page I will have Register or Login. 

![the expected](https://user-images.githubusercontent.com/33448286/78143881-831d9a00-7437-11ea-8c55-bb49c29b7811.gif)

Is this the expected right now?

**Comment by willdurand** [comment]
Yes, I think that's the expected behavior now.

**Comment by ioanarusiczki** [comment]
@willdurand I was hoping it will show the register/login without refreshing page or manually log out.
But eventually if I want to change something and make it work I have no choice but doing so. 
Verified on dev with FF74(Win10).
