### ISSUE TITLE
Temporarily serve blocked pages under a different path

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9269]
We currently serve the blocked pages under `/blocked/` but it was already used for something else so it does not work and QA cannot verify these new pages. Let's add a new URL in addition to the current one for QA.

I suggest `/addon-blocked/`.

**Comment by bobsilverberg** [comment]
@willdurand I'm late to this conversation/feature, so I don't really understand the context, but is there a reason we must serve this under `/blocked/` in production? I see the other issues about changing the nginx config, but why not just permanently serve this as `/addon-blocked/` and treat `/blocked/` as already in use?

**Comment by willdurand** [comment]
That's a Product decision. We'll change the path only if we can't have the nice `/blocked/` path.

**Comment by AlexandraMoga** [comment]
The blocked addon page can be accessed on -dev from the new `/addon-blocked/` URL.
