### ISSUE TITLE
AMO Progressive Rating & Review Flow

### ISSUE THREAD

**Issue by pwalm** [mozilla/addons-frontend#927]
As a starting off point, here is the proposed general flow for rating and reviewing an extension/theme on AMO. Suggestions? Comments?
- User comes across three faces under the header “Ratings & Reviews”: Happy, Meh, and Sad.
- Above the faces we ask: “How has your experience with [extension] been?” (If user has not installed this extension/theme, they will not be shown this feature)
- User selects one of the faces:
  - If user selects “Happy”, they are presented with six buttons/tags relating to how great the extension/theme is.
  - If the user selects “Meh”, they are presented with six buttons/tags relating to general problems with extensions/themes.
  - If the user selects “Sad”, they are presented with six buttons/tags relating to how the extension/theme could be better.
- After selecting up to six tags, we thank them and ask if they’d like to leave a more detailed, written review.
- If the user taps no, we take them back to the extension/theme detail page.
- If the user taps yes, we take them to a written review page.
  - Form field is pre-filled with instructions based on the face selected earlier.
    - If the review was positive: “Tell us what you love about [extension]!”
    - If the review was negative: “What could [extension] do better?”
  - Character length is limited. We want users to be concise.
  - We should scan the written review for abusive/inappropriate words.
- When finished, the user taps submit. We thank them and take them back to where they started on the extension/theme detail page.

**Comment by kumar303** [comment]
This sounds great! Here are some thoughts:
* After selecting the face, is it possible for the user to end there, without selecting tags? I'm just wondering if we should make the six tags optional or required. 
  * Maybe someone who is thinking about metrics knows how we need to capture data. 
  * It would be nice to make the six tags optional.
* I can't envision what you mean by buttons/tags but it will probably be easier to discuss when there's a visual mock
* I really like starting the flow with a low friction happy, meh, or sad UI
* It might be helpful to offer a path to a "support channel" when the user selects a sad face, i.e. guide them to submitting a bug or contacting the developer as opposed to leaving a rant-review.
* I like the concept of not showing the happy/sad faces unless the user has installed the add-on but I wonder if we need to provide a hint that this will be available to them after the add-on has been installed. Maybe it could be grayed out or maybe the install flow could provide some textual hint like "go here for feedback later on" (or something).

**Comment by muffinresearch** [comment]
As Kumar says It would definitely be useful to see some mocks of what the tags / buttons represent to understand a bit more what that would look like and what the goal is, e.g: are they to help the user or more for feedback to the developer and other users?

Another entirely separate consideration (and possibly too low level at this stage) is what to do with the current ratings data? Would 4/5 be happy, 2/3 be meh and 1 sad? Presumably we'd want to be able to convert that into something that fits any new model. Another thought is how we will deal with running this side by side with star ratings if we need to?

**Comment by atsay** [comment]
What is the thinking behind happy/meh/sad faces? Just curious... I like that it's possible to leave feedback without having to write anything.

To echo Kumar and Stuart, we should make it more obvious where people should go if they want support. And also link to review guidelines.

**Comment by pwalm** [comment]
@kumar303 
- Yes, it is possible to end after selecting a face. Tagging, like writing a review, is optional.
- Buttons/tags is a bad name. More like a button you can toggle on/off.
- Support channel/bug submission is something I’d love to do, not sure if it would be too much in this flow?
- We should def show some kind of greyed out/“install to review” prompt.

@muffinresearch 
- Mocks are def coming. Some had been done but I thought I’d pull back on that so we can all talk it out.
- Mapping the faces to star rating data is a must., gotta keep those existing ratings/reviews around.
- We can run faces and stars side by side until we have enough data to transition to faces-only.

@atsay 
- The faces rating system is instant and harder to game. You generally know how your experience with a piece of software is going/has gone pretty quickly, so if it’s been great and helpful you know to give a smiley. Unlike star ratings where someone could give something a 1 star rating for lacking a specific feature despite enjoying it. Faces/emoji rating is becoming a more common pattern across the web (and in real life, like once you make it through airport security at Heathrow).
- We could actually show support options if the user selects the negative faces. Would tailor the experience a bit better. 
- I’d like to spell out review guidelines in a quick way throughout the process, but yes, we should link to the full guidelines as well.

Some reading!
[The Problem With Online Ratings](http://sloanreview.mit.edu/article/the-problem-with-online-ratings-2/)
[Netflix wants to ditch its 5-star rating system](http://www.businessinsider.com/netflix-wants-to-ditch-5-star-ratings-2016-1?op=1)
[The Big Hidden Problem With Uber? Insincere 5-Star Ratings](http://www.wired.com/2015/03/bogus-uber-reviews/)
[Instagram is building the anti-harassment tools Twitter won't](http://www.theverge.com/2016/7/29/12327312/instagram-anti-harassment-commenting-tools)
[Men Are Sabotaging The Online Reviews Of TV Shows Aimed At Women](http://fivethirtyeight.com/features/men-are-sabotaging-the-online-reviews-of-tv-shows-aimed-at-women/)
[How I got 10,000 five-star reviews in 4 weeks](https://medium.com/mobile-growth/how-i-got-10-000-five-star-reviews-in-4-weeks-5246cc4c55c7#.h3h5o78fn)
[The rating game](http://www.theverge.com/2015/10/28/9625968/rating-system-on-demand-economy-uber-olive-garden)
[Microinteractions: The Secret of Great App Design](https://uxplanet.org/microinteractions-the-secret-to-great-app-design-4cfe70fbaccf#.gm0ku4kq0)

**Comment by diox** [comment]
> Another entirely separate consideration (and possibly too low level at this stage) is what to do with the current ratings data? Would 4/5 be happy, 2/3 be meh and 1 sad? Presumably we'd want to be able to convert that into something that fits any new model. Another thought is how we will deal with running this side by side with star ratings if we need to?

We definitely need a mapping, and it needs to go both ways : desktop is still going to show the old UI with the stars for the moment, isn't it ?

**Comment by diox** [comment]
Also a note about gaming the system: from an API point of view, we don't know if a user has installed the add-on. Storing that information is quite complex, we'd need the user to be logged in before installing, and it has some privacy implications as well. The consequence is, we can't prevent malicious users that have not installed an add-on to review it using the API. We should definitely prevent it on the frontend, but we won't be entirely protected from bad actors.

**Comment by kumar303** [comment]
> Support channel/bug submission is something I’d love to do, not sure if it would be too much in this flow?

Yeah, I can see how we could fall down a rabbit hole trying to offer an "I need support" flow. At the very least maybe we could provide a text link or show the developer's email at the top of the sad-face flow.

**Comment by andymckay-limited-access** [comment]
You can check if an add-on is installed using mozAddonsManager and send that in the API.

Ideally I'd like to see this flow broken down into stuff we should do for v1 and then iterate with the improvements.

**Comment by pwalm** [comment]
First pass at a proto for reviewing and reporting is here:
https://mozilla.invisionapp.com/share/A58EEQUK6

Leave comments here or in the proto.

**Comment by kumar303** [comment]
Nice one! I like this flow a lot. Just one minor comment came to mind: we don't collect a "submit bug report" URL in the submission flow (but we totally should). Even without that button, I think the action list is really good. We collect support URLs but that is optional. I think the developer email may be required (I will verify) so that should work as a button.

**Comment by kumar303** [comment]
I could see some situations where the canned summary buttons ("buggy", "crashy", etc) don't apply so maybe we should allow them to bypass that altogether so they can jump into the next action (writing a review or requesting support).

**Comment by wagnerand** [comment]
I like it!

When using `Report` button, we first show a screen that immediately goes to the next screen once you select something. On that next screen, you first have to click `Next` after making a selection.

I see reasoning for either solution, but do we want to have consistent experience ie use `Next` always or never?

**Comment by muffinresearch** [comment]
Closing leaving the remaining issues open for the rest.
