### ISSUE TITLE
Text alignment in the detail page sections should look alike 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9273]
STR:
Followup for https://github.com/mozilla/addons-frontend/issues/2764
A new section is now available on the add-on detail page, it's the "Developer comments" which is right below the "About this extension" . While testing I've noticed that the layout of the text is different.

As an expected result: 
Both sections should display the text the same way. I can't tell which is fine. @jvillalobos Please add your opinion about this.  Thanks! 

![developer comment layout](https://user-images.githubusercontent.com/33448286/77445879-4c6fd000-6df6-11ea-81b9-d54586b97cdd.png)

**Comment by willdurand** [comment]
Here is an add-on in -dev: https://addons-dev.allizom.org/en-US/firefox/addon/34esperanto-language-pack/

**Comment by jvillalobos** [comment]
The "About this extension" section has the correct look, judging by [how it currently looks in prod](https://addons.mozilla.org/addon/adblock-plus/).

**Comment by ioanarusiczki** [comment]
@willdurand Fixed on dev and stage with FF74(Win10). 
https://addons-dev.allizom.org/en-US/firefox/addon/34esperanto-language-pack/
https://addons.allizom.org/en-US/firefox/addon/weather-stage/

![fixed text](https://user-images.githubusercontent.com/33448286/77542339-b186fc80-6eae-11ea-81ff-d413519b132b.png)
