### ISSUE TITLE
Revert recent user profile avatar changes

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9275]
We fixed https://github.com/mozilla/addons-frontend/issues/7880 recently but it looks less nice than before so we want to revert these changes.

**Comment by ioanarusiczki** [comment]
@willdurand I verified the dev and stage servers. Look alright to me, the changes have been reverted. 
https://github.com/mozilla/addons-frontend/issues/7880 can be marked as a won't fix. 

![sample2](https://user-images.githubusercontent.com/33448286/77518650-d36c8900-6e86-11ea-9db3-f6d1069d9a8e.png)
 
![example2](https://user-images.githubusercontent.com/33448286/77518687-debfb480-6e86-11ea-8f8a-8e7938ddbe0a.png)
