### ISSUE TITLE
I cannot view my Collections in PERSONAS in Firefox v 74.0.

### ISSUE THREAD

**Issue by orsay54** [mozilla/addons-frontend#9277]
Hello, 
I use to be able to add/view a theme to my Collections in Firefox.
I can still add a theme but I cannot view the themes. Its says there an error. That it cannot be viewed at this time.. This started YEARS ago when you guys redesigned the program.

Thanks if you can fix this problem.
Pat

**Comment by jvillalobos** [comment]
If you mean the Personas Plus extension, it was discontinued a while ago. You can still access your collections if you go to addons.mozilla.org and log in.

**Comment by orsay54** [comment]
Thanks for such a speedy reply.. I am there, logged in. I see my collections.. can add to them but I can not open the collections.Am using the latest FIREFOX too.Any suggestions?Thanks,Pat-----Original Message-----

**Comment by orsay54** [comment]
Please view the ATTACHMENT.. this is what I get when I try to open a collection..I just sent you an email a few seconds ago.. please read.. Thanks,Pat-----Original Message-----

**Comment by jvillalobos** [comment]
I don't know what you mean by not being able to open the collections, but this is not the right place to ask for support. I suggest that you post the question in [our forum](https://discourse.mozilla.org/c/add-ons).

**Comment by orsay54** [comment]
Ok. But when it said ask for help... It was your email address that was given. How else would I  Have found it!? I sent you a screenshot of the error message  In another email. 
I will not bother you again..
