### ISSUE TITLE
[error] Site notice content overflowing the div

### ISSUE THREAD

**Issue by muskangupta-iitr** [mozilla/addons-frontend#9281]
### Describe the problem and steps to reproduce it:
Site notice content overflowing the div when It contains a long non-breaking word.

#### Screenshot:

![Screenshot from 2020-03-25 01-52-05](https://user-images.githubusercontent.com/50856599/77473343-5667f200-6e3b-11ea-9625-81265ebdf97f.png)

#### Solution:
It can be solved by `word-break: break-word` style.

![Screenshot from 2020-03-25 01-54-53](https://user-images.githubusercontent.com/50856599/77473596-b52d6b80-6e3b-11ea-8054-c75d75024242.png)

I would like to create PR for this.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on dev with FF74(win10). 

![unbroken string](https://user-images.githubusercontent.com/33448286/78221685-80b94f80-74cc-11ea-9530-0d9bcdb13fb4.png)
