### ISSUE TITLE
OpenSearch AMO engines are not recognised as already being installed

### ISSUE THREAD

**Issue by Standard8** [mozilla/addons-frontend#9284]
From https://bugzilla.mozilla.org/show_bug.cgi?id=1623063

**Steps to reproduce**
1. Launch Firefox
2. Add the Search bar in the toolbar
3. Go to https://addons.mozilla.org/en-US/firefox/
4, Click on the plus sign on the magnifying glass in the search bar
5. Click on Add "Firefox Addons (en-us)"

### What happened?
The search engine was added to the list of engines. However, the plus sign and the option to add the search engine are still displayed. 

### What did you expect to happen?
The plus sign and option to add the search engine should no longer be displayed

### Anything else we should know?

The problem here is that addons.mozilla.org is specifying the title differently to the xml file. In the html I see:

https://addons.mozilla.org/en-US/firefox/
```
<link data-react-helmet="true" title="Firefox Add-ons (en-US)" rel="search" type="application/opensearchdescription+xml" href="/en-US/firefox/opensearch.xml">
```

The xml file specifies:

https://addons.mozilla.org/en-US/firefox/opensearch.xml
```
<OpenSearchDescription>
  <ShortName>Firefox Add-ons</ShortName>
  <Url type="text/html" method="get" template="https://addons.mozilla.org/en-US/firefox/search/?q={searchTerms}"> </Url>
```

The problem here is that when Firefox tries to reconcile what is already installed, the title doesn't match between the installed engine ("Firefox Add-ons") and that provided by the page ("Firefox Add-ons (en-US)") so we think they are different.

Seeing as AMO provides a different URL in the opensearch.xml for each locale, I guess it would be possible to change the title in there for each locale as well.

**Comment by willdurand** [comment]
So the idea would be to update the `SearchForm` component by removing the locales in the `openSearchTitle` localization strings.

**Comment by xlisachan** [comment]
@willdurand , can I work on this?

**Comment by willdurand** [comment]
@xlisachan yep, go ahead

**Comment by xlisachan** [comment]
Thanks @willdurand! When you have a moment, please review the pull request linked above.

**Comment by ioanarusiczki** [comment]
@willdurand 
I verified this issue on dev with FF74(Win10). 
- once AMO as a search engine is added the "Add to Firefox" is no longer displayed.
- the locale has been removed. 

![no longer there](https://user-images.githubusercontent.com/33448286/77888420-ea3f2100-7274-11ea-8efa-a357a51ec91b.gif)
