### ISSUE TITLE
Serve blocked pages under `/blocked-addon/`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9286]
Because `/blocked/` is actually used, @jvillalobos decided to use `/blocked-addon/` to serve the new blocked pages.

**Comment by AlexandraMoga** [comment]
The block pages are now opening under `/blocked-addon/`:
https://addons-dev.allizom.org/en-US/firefox/blocked-addon/gmailnoads@mywebber.com/
