### ISSUE TITLE
Linkify usernames in ratings for admins

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#9297]
It would be helpful for administrative tasks if user names in ratings were linking to the respective user profile page (for both developers and non-developers).

Adding the link should be for admins only, gated by the same permission that gates showing user profile pages for non-developers.

**Comment by xlisachan** [comment]
@wagnerand , I am an Outreachy applicant. Can I work on this?

**Comment by wagnerand** [comment]
@xlisachan absolutely, please go ahead!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev
Usernames in ratings will point now to the respective profile page when the viewer is an admin.
For regular or non-authenticated users, there is no link present. 

[view for admin]
![image](https://user-images.githubusercontent.com/31961530/78148799-ed393d80-743d-11ea-86f7-de912fea971a.png)

[view for regular user]
![image](https://user-images.githubusercontent.com/31961530/78148823-f3c7b500-743d-11ea-9762-77d264c0ae02.png)
