### ISSUE TITLE
[ui] Cursor should be changed on hover on the dropdowns

### ISSUE THREAD

**Issue by muskangupta-iitr** [mozilla/addons-frontend#9301]
### Describe the problem and steps to reproduce it:

Dropdown in the reviews page should change cursor from `normal` to `pointer` so that user can understands that it is selectable.
Also, dropdown in the addon page of `Add to collection` card, also shows the same behaviour.

Here is the screenshot:

![Screenshot from 2020-03-29 11-42-59](https://user-images.githubusercontent.com/50856599/77842655-93711300-71b2-11ea-9bbd-ec20824ec6ac.png)

![Screenshot from 2020-03-29 17-07-28](https://user-images.githubusercontent.com/50856599/77848115-178dbf80-71e0-11ea-93d0-bbffc13951d0.png)

### Solution:
We can change the cursor on hover by adding style `cursor: pointer;`.

Here is the screenshot:

![Screenshot from 2020-03-29 11-49-03](https://user-images.githubusercontent.com/50856599/77842726-6709c680-71b3-11ea-8918-c11e931436b7.png)

![Screenshot from 2020-03-29 17-08-31](https://user-images.githubusercontent.com/50856599/77848118-1bb9dd00-71e0-11ea-9862-813fab39d103.png)

I would like to work on this issue :+1:

**Comment by bobsilverberg** [comment]
Thanks for filing this @muskangupta-iitr. I don't think it's a particularly serious problem, but you've already found a solution, so that's good.

**Comment by willdurand** [comment]
Shouldn't we keep the browser behavior? Otherwise, we would have to patch **all** the `select` tags I guess. In other words, we would need a rule that targets the `select` tag specifically, no?

See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by bobsilverberg** [comment]
Sorry, you're right @willdurand, it would be better to have a rule that addresses all `select` tags if we want this. Do you think we should revert this commit?

**Comment by willdurand** [comment]
> Sorry, you're right @willdurand, it would be better to have a rule that addresses all `select` tags if we want this. Do you think we should revert this commit?

np. I think we should decide if we want to modify the default browser style or not, and in the meantime we can indeed revert the commit.

**Comment by ioanarusiczki** [comment]
@willdurand @bobsilverberg The revert was verified https://github.com/mozilla/addons-frontend/issues/9317 
The milestone should be also updated for this issue.

**Comment by bobsilverberg** [comment]
> @willdurand @bobsilverberg The revert was verified #9317
> The milestone should be also updated for this issue.

I thought I did update the milestone. Is it not accurate?

**Comment by ioanarusiczki** [comment]
@bobsilverberg I see it on this milestone - can't tell when you want to add it back though :)

**Comment by bobsilverberg** [comment]
> @bobsilverberg I see it on this milestone - can't tell when you want to add it back though :)

Maybe never ;)

**Comment by ioanarusiczki** [comment]
@bobsilverberg Sits well here then!
