### ISSUE TITLE
Improve H1 so that addon name has a space before 'by'.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#9309]
### Describe the problem and steps to reproduce it:

* Go to https://addons.mozilla.org/en-US/firefox/addon/privacy-badger17/
* From the console run:

```
$('h1').textContent;
```

### What happened?

The output is:

"Privacy Badgerby EFF Technologists"

### What did you expect to happen?

The output should be:

"Privacy Badger by EFF Technologists"

### Anything else we should know?

It's unclear if this will have an impact on SEO, but it would probably be a good idea to make sure text extracted from the markup reads correctly and isn't concatenated like it is currently.

**Comment by willdurand** [comment]
This is interesting because we explicitly render a whitespace:

<img width="504" alt="Screen Shot 2020-03-31 at 12 20 09" src="https://user-images.githubusercontent.com/217628/78015673-03fe6800-734a-11ea-886e-675c5b493054.png">

**Comment by muffinresearch** [comment]
> This is interesting because we explicitly render a whitespace:
> 
> <img alt="Screen Shot 2020-03-31 at 12 20 09" width="504" src="https://user-images.githubusercontent.com/217628/78015673-03fe6800-734a-11ea-886e-675c5b493054.png">

Isn't that after the "by" rather than before it?

**Comment by ioanarusiczki** [comment]
@willdurand Verified on dev and stage - FF74(Win10). `by` was separated from the names.

![the correct name](https://user-images.githubusercontent.com/33448286/78150522-12c74680-7440-11ea-81ab-9727b6a149ca.png)
