### ISSUE TITLE
Use import linting to catch undefined imports

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#931]
Our lint checks [do not verify imports](https://github.com/mozilla/addons-frontend/blob/master/.eslintrc#L16), I guess because the path resolution is complicated? We should turn on import linting because I found the refactoring in https://github.com/mozilla/addons-frontend/pull/930 to be very difficult without it.

**Comment by muffinresearch** [comment]
Path resolution is complicated. If it's possible to get this working without major pain then we should do it, but it might not be worth it.
