### ISSUE TITLE
`ShowMoreCard` button used in developer reply has the wrong background color

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9311]
### Describe the problem and steps to reproduce it:

1. Go to https://addons-dev.allizom.org/en-US/firefox/addon/search_by_image/reviews/?src=recommended_fallback
2. Observe the "developer response" in the middle of the page

### What happened?

The `ShowMoreCard` displays a "read more" button with a white background:

<img width="1280" alt="Screen Shot 2020-03-31 at 14 38 17" src="https://user-images.githubusercontent.com/217628/78027415-9ceaae80-735d-11ea-8527-d8c26ea60816.png">

### What did you expect to happen?

The button background color should be blue-ish.

**Comment by AlexandraMoga** [comment]
@willdurand the same issue is visible on the Rate your experience card on the add-on detail page for user reviews:

![image](https://user-images.githubusercontent.com/31961530/78029722-babe1080-7369-11ea-889e-4d7b5e2b92c0.png)

**Comment by xlisachan** [comment]
@willdurand Can I work on this?

**Comment by willdurand** [comment]
> @willdurand Can I work on this?

Yep

**Comment by ioanarusiczki** [comment]
@willdurand I verified on dev with FF74(Win10)

- the addon detail page has a blue-ish background for the text and button - the button has no borders. 

![blue but no border](https://user-images.githubusercontent.com/33448286/78760114-59112e00-7989-11ea-962d-1a9538b2f2b3.png)

- on the reviews page I don't really see a difference for the reviews, text and button are white. The Developer reply has a blue-ish background (text and button). In both cases the button does not have borders.

![the review page](https://user-images.githubusercontent.com/33448286/78760308-a2617d80-7989-11ea-8633-83733566c0fc.png)

- view my profile shows both reviews and dev replies white.

![view my profile](https://user-images.githubusercontent.com/33448286/78760342-b0170300-7989-11ea-9b5d-c0fe7fd0d94e.png)

Let me know if that's what you expected after this fix.

**Comment by willdurand** [comment]
@ioanarusiczki yes, that looks good to me. Do you see any regression with -prod? If I look here, it is similar: https://addons.mozilla.org/en-US/firefox/addon/privacy-possum/reviews/?src=featured&page=5, but we fixed the blue background at least.

**Comment by ioanarusiczki** [comment]
@willdurand I looked into prod and the blue background for the button is available on the detail page.
Also for the developer reply the button's background is now blue-ish.
And no changes for the reviews on the other pages.

**Comment by ioanarusiczki** [comment]
@willdurand Also, I saw some discussions about the border. I think it would look better with borders too.
