### ISSUE TITLE
Revert changes to cursor on hover for selects

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9317]
https://github.com/mozilla/addons-frontend/commit/dfea0f60130911847add4954c1f7a735ce2e1ae6 introduced some styles that applied a cursor change for `hover` for some `select` elements. This overrides the default browser styles, and does not do it for every `select` element, but just for some.

We don't know if we want to override the browser style like that, and if we do then we should do it universally for all `select`s.

We should revert that commit for now until that decision is made.

**Comment by bobsilverberg** [comment]
@muskangupta-iitr My apologies, I should not have approved and merged this pull request. See above, and also https://github.com/mozilla/addons-frontend/issues/9301#issuecomment-606247242 for more details. Would you like to take on this issue, which is simply about adding a commit that reverts the changes?

**Comment by muskangupta-iitr** [comment]
@bobsilverberg Yes sure! I revert the changes.

**Comment by willdurand** [comment]
I guess it would be nicer if we could cherry-pick the revert too :)

**Comment by ioanarusiczki** [comment]
@bobsilverberg @willdurand 
I don't see the changes from https://github.com/mozilla/addons-frontend/issues/9301 being available on dev or stage. I verified with FF74(Win10).
