### ISSUE TITLE
Typo in header class name

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9323]
There is a typo in a css class name that could cause layout issues (related to the page header).

Regression introduced in https://github.com/mozilla/addons-frontend/commit/6be493910f23a8da45a5144da70cb11599d6a5a6

**Comment by AlexandraMoga** [comment]
Looks like the header background was affected by this:

![image](https://user-images.githubusercontent.com/31961530/78139398-1ef7d780-7431-11ea-8d40-67c5f2eb798c.png)

**Comment by AlexandraMoga** [comment]
The header background is fixed now and I didn't see any other regressions:

![image](https://user-images.githubusercontent.com/31961530/78343925-40c59b80-75a4-11ea-8fdd-17a9140f1e33.png)

Marking issue as verified fixed.
