### ISSUE TITLE
Update the blocked-addon URLs to take an optional version.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#9324]
Currently the URL format allows for passing a locale, clientApp and guid, we would like Firefox to send the version too, since that way we are covered in-case we would like to do something with the version information.

The new URL format would be as follows:

`/:locale:/:clientApp:/blocked-addon/:guid:/:version:/`

The version is optional so the following should continue to provide a response:

`/:locale:/:clientApp:/blocked-addon/:guid:/`

/cc @diox, @willdurand and @Rob--W

**Comment by muffinresearch** [comment]
@jvillalobos Since this URL will only be linked from the client, are you ok for us to explicitly de-index these pages so that we avoid spending crawl budget on these pages? If we do want these pages to appear in SERPs we would probably want to re-consider how we surface them.

**Comment by jvillalobos** [comment]
Yeah, I think it's okay not to index them.

**Comment by AlexandraMoga** [comment]
@willdurand should the the new `versionId` param accept any string value, like the below example?
https://addons-dev.allizom.org/en-US/firefox/blocked-addon/s3google@translator/any-string/

**Comment by willdurand** [comment]
> @willdurand should the the new `versionId` param accept any string value, like the below example?

Yep, this param is unused.

**Comment by AlexandraMoga** [comment]
In that case, I can mark this issue as verified.

Looking at the blocked page without adding the `versionId` (optional) parameter also works:
https://addons-dev.allizom.org/en-US/firefox/blocked-addon/s3google@translator/
