### ISSUE TITLE
Instrument clicks on Add-on names in Disco Pane

### ISSUE THREAD

**Issue by designakt** [mozilla/addons-frontend#933]
It would be great if we can add a new category of events for clicks on add-on names to see how often each of those gets clicked. It should be a new category as to not mix with other events we have.

**Comment by designakt** [comment]
And please tell me when that change goes live, or mark it in the timeline of Google Analytics as this will probably increase the total number of events.

**Comment by muffinresearch** [comment]
@designakt a PR is ready, expect this to go out next week.

**Comment by muffinresearch** [comment]
QA: notes clicking on themes + addons should be sending a beacon to google analytics:

If you open the network tab of devtools and filter on images you will see a request happening when clicking on a link (it opens a new tab, so you'll need to go back to the disco pane to see it in the inspector).

**Comment by ValentinaPC** [comment]
@muffinresearch : I have a question: every click sends a beacon to google analytics or only click on add-ons and themes (does this apply to install/uninstall?)? Because now it **also** happens when I click "see more addons!" or start/stop video.
Please see the screencast:

**Comment by muffinresearch** [comment]
Yep, we're specifically only interested in the links with authors for this release. The rest was there already.

**Comment by ValentinaPC** [comment]
Based on above comment, I'll mark this verified fixed.
