### ISSUE TITLE
Prevent blocked pages from being indexed by Google (et al.)

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9330]
According to the discussion in #9329, we do not want to index the blocked pages (anymore).

**For QA:** there should be a new `meta[name="robots"]` tag with `noindex, follow` as a value in all blocked pages.

**Comment by AlexandraMoga** [comment]
The following meta is present on all the blocked addon pages I've looked at:

`<meta data-react-helmet="true" name="robots" content="noindex, follow"/>`
