### ISSUE TITLE
Update warning messaging for non-Recommended extensions

### ISSUE THREAD

**Issue by devaneymoz** [mozilla/addons-frontend#9332]
Based on abundant feedback we've received from users and developers, and confirmed through a usertesting.com study, we need to change the warning messaging for clarity. Please change to the following new copy:

_This is not monitored for security through Mozilla's Recommended Extensions program. Make sure you trust it before installing. [Learn more](https://support.mozilla.org/kb/recommended-extensions-program#w_what-are-the-risks-of-installing-non-recommended-extensions)._

@muffinresearch

**Comment by wagnerand** [comment]
@devaneymoz should it be "This add-on..." or "This extension..." rather than "This is..."?

**Comment by muffinresearch** [comment]
Moving this up to a P1 as Amy has asked for this to go out next week.

**Comment by devaneymoz** [comment]
> @devaneymoz should it be "This add-on..." or "This extension..." rather than "This is..."?

I see what you're saying but it was intentionally worded this way to avoid the redundancy of "extension" in the sentence... "This extension ........ Recommended Extensions program."

Plus it was already so wordy to begin with.

**Comment by ioanarusiczki** [comment]
@bobsilverberg
This is how it looks on full screen - FF 74(win10)

![as it looks on desktop](https://user-images.githubusercontent.com/33448286/78645298-00c22980-78c0-11ea-97a6-7f4813ac4047.png)

This is how it looks if I resize the browser. - FF 74(win10)

![resizing browser](https://user-images.githubusercontent.com/33448286/78645350-15062680-78c0-11ea-9f94-69ba649ae581.png)

Verified on dev.
