### ISSUE TITLE
Move installations actions to the corresponding reducer

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9357]
Supports https://github.com/mozilla/addons-frontend/issues/8418

---

We should not have separate "actions" files as we adopted [the ducks pattern](https://github.com/mozilla/addons-frontend/issues/1299) a while ago. Let's fix the installations code.

**For QA:** please make sure the install button works as intended (right state/status, can install and uninstall an add-on, etc.)

**Comment by ioanarusiczki** [comment]
@willdurand Sure, last check tomorrow on stage @ release testing.

**Comment by ioanarusiczki** [comment]
@willdurand 
Install, remove , enable work as expected on AMO stage with FF75(Win10).
