### ISSUE TITLE
Get add-on screenshots working

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#936]
The add-on detail page was hooked up to API data in https://github.com/mozilla/addons-frontend/issues/883 but the screenshot widget is not working yet. It needs images and navigation, etc.

**Comment by muffinresearch** [comment]
I've hooked up react-image-gallery. Whilst it has some nice features it's immediate there's a few issues.

It uses style attributes directly which means it won't work with CSP. 

Secondly it's clear that as a solution we'll need to understand how this might fit within a desktop page to understand what the needs are.

If we end up needing to make our own gallery/screenshot widget I think we'd want to try and understand both the desktop and mobile use cases since they're likely to be different if at all possible it would be great if we could do this once and have it work to save having to special case desktopm later.

**Comment by muffinresearch** [comment]
I did a bit more exploring, having setup a test configuration running built code and with CSP enabled, I was able to get the react-image-gallery working under CSP.

Apparently react 15+ does poke style props directly (which alleviates most CSP concerns), but the caveat is server-side renders are still going to add attributes. Weird thing is some style seems to still cause CSP reports, need to understand where this is coming from.

If nothing else this should provide some food for thought as to howe we could build something. 

Other minor nits with react-image-gallery:

* Key events work regardless of focus we'd want to turn that off.
* Bullet points provide no text context which is not ideal and they're not focusable but they are clickable.

**Comment by mstriemer** [comment]
I went looking for a library to handle this as well just now. I tried react-image-gallery but it feels a little clunky on my phone. A quick swipe left or right doesn't always move the image over, you really need to slowly drag across to get it to flip consistently.

I found a library called PhotoSwipe that works quite well but looks like it is full screen only. This doesn't quite match the mocks but it does seem pretty solid. The raw JS library is at http://photoswipe.com/ and it has a react wrapper at https://github.com/minhtranite/react-photoswipe ([demo](http://minhtranite.github.io/react-photoswipe/)). It looks like it hasn't been updated in a year and there are 227 open issues but if it was fairly solid a year ago I don't think image galleries have changed a ton, could be fine.

I might try throwing the react one in there quickly to see how it looks.

**Comment by mstriemer** [comment]
I quickly mocked something up using react-photoswipe, here's how it looks.

![basic-screenshot-photoswipe mp4](https://cloud.githubusercontent.com/assets/211578/20782122/701c69e4-b74e-11e6-8ecc-e5f9f9e4a75d.gif)

If you look at the demo they have it has a nice transition after tapping an image to open the gallery where the image grows to the gallery size. I didn't set that up with this but I have a feeling it wouldn't be too bad.

It also does zooming/panning of images and has left/right buttons on desktop. I'm not sure how accessible that is but it seems promising.

@pwalm would this be appropriate for displaying screenshots or do you want to stick with something more in line with the mocks (scrolling between them in place on the page).

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF51(Android 6.0.1)
Postfix screenshot: 
![screenshot_20170206-163302](https://cloud.githubusercontent.com/assets/15685960/22651307/4a18a5ec-ec8b-11e6-8870-9b18007fac8b.png)
