### ISSUE TITLE
Change mobile compatibility message for add-ons in Fenix collections

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9360]
Currently, Fenix users see this message in all add-on pages:
> Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. Learn more about [add-ons for Android].

However, there's some add-on support being rolled out and users will start running into pages of add-ons that are supported but show this message. Additionally, it's still not possible to install those add-ons from AMO, so the message should still be present, just differently worded.

When an add-on is in the supported collection, the message for Fenix users should read:

> You can install this add-on in the Add-ons Manager. Learn more about [add-ons for Android].

There are currently two collections listing the supported extensions: one for the [Beta channel](https://addons.mozilla.org/collections/4757633/7e8d6dc651b54ab385fb8791bf9dac/) (which is what most Fenix users have) and one for the [Nightly channel](https://addons.mozilla.org/collections/4757633/16f6e5d9a40448b8955db57ced6d75/). Ideally we should detect the Fenix version being used and use the corresponding collection. If that's not feasible, we should at least use the Beta collection for all Fenix users.

/cc @kewisch 

For QA:

The list of add-ons that should be considered compatible are being stored in the config in frontend, rather than reading from a collection. The reference collection is https://addons.mozilla.org/collections/4757633/3204bb44a6ef44d39ee34917f28055/. Many of these add-ons also exist on dev and have the same `guid`, so that can be convenient for testing. The complete list of `guid`s supported can be found in https://github.com/mozilla/addons-frontend/blob/master/config/default.js, at the bottom.

**Comment by bobsilverberg** [comment]
Some questions:

1. If we're going to detect the channel the user is on, does that mean we'll have to update these version numbers every time there is a new release? That's probably okay if this is an important feature, but I just wanted to raise it as something to be aware of.

2. Is it possible to create a link that would take the user to the Add-ons Manager in Fenix? If so, is that something we'd want to use as the link destination?

3. Do these collections exist on every environment and do they have identical slugs in each environment?

**Comment by willdurand** [comment]
I think querying the collections api every time is not a very optimized solution. It takes weeks to get new addons to Fenix so maybe we could put addon GUIDs in config instead. It is only a few extensions so far, so we could start with that and evolve when it is needed.

For example, the add-on itself could have a flag to determine whether it is Fenix Beta or Nightly compliant (or not available at all). That would avoid yet another api call.

**Comment by jvillalobos** [comment]
> If we're going to detect the channel the user is on, does that mean we'll have to update these version numbers every time there is a new release?

I was wondering if we had some other part of the code that depended on the channel that we could latch on. If we need to manually update versions on every Firefox release, that probably isn't worth doing and we should just use the Beta list instead.

> Is it possible to create a link that would take the user to the Add-ons Manager in Fenix?

No, content can't point to privileged pages. We've made exceptions like with abuse reports, but that requires a client-side API, which would be overkill in this case.

> Do these collections exist on every environment and do they have identical slugs in each environment?

We might only have them in prod.

> For example, the add-on itself could have a flag to determine whether it is Fenix Beta or Nightly compliant (or not available at all).

That sounds okay to me, but @kewisch will need to remember to update two different places :)

**Comment by willdurand** [comment]
> That sounds okay to me, but @kewisch will need to remember to update two different places :)

Either that or the server could do that automatically. /cc @diox 

Making yet another api call, likely all the time, makes me nervous so this should rather be added to the add-on itself. I don't know exactly "how", though.

**Comment by bobsilverberg** [comment]
> > That sounds okay to me, but @kewisch will need to remember to update two different places :)
> 
> Either that or the server could do that automatically. /cc @diox
> 
> Making yet another api call, likely all the time, makes me nervous so this should rather be added to the add-on itself. I don't know exactly "how", though.

Well, we could cache the list of ids in the redux store, only requiring an API call once per session, but that would complicate the front end code. Having it returned in the addon API response sounds like a good idea.

**Comment by diox** [comment]
We already handle compatibility information on the server, and expose that to clients through `current_version.compatibility`. Until now since there was only one add-on and no clear plans regarding Fenix add-on compatibility in the future we haven't done anything for Fenix, but I think that's where it should happen.

Since Firefox for Android (the Fennec variant) is stuck on 68.x.y, we could replace the `max` version returned for add-ons: for most add-ons we'd return `68.*` (I don't remember if we can actually do that, we might need to return `68.99.99` or something), for add-ons compatible with Fenix Beta channel we'd return `75.*` and for nightly we'd return `77.*`.

Then in the frontend, on Android, we'd follow that a bit like if `is_strict_compatibility_enabled` was `true`, and add something specifically for Fenix on top saying to go install the add-on in add-on manager instead of on the page.

**Comment by bobsilverberg** [comment]
> We already handle compatibility information on the server, and expose that to clients through `current_version.compatibility`. Until now since there was only one add-on and no clear plans regarding Fenix add-on compatibility in the future we haven't done anything for Fenix, but I think that's where it should happen.
> 
> Since Firefox for Android (the Fennec variant) is stuck on 68.x.y, we could replace the `max` version returned for add-ons: for most add-ons we'd return `68.*` (I don't remember if we can actually do that, we might need to return `68.99.99` or something), for add-ons compatible with Fenix Beta channel we'd return `75.*` and for nightly we'd return `77.*`.
> 
> Then in the frontend, on Android, we'd follow that a bit like if `is_strict_compatibility_enabled` was `true`, and add something specifically for Fenix on top saying to go install the add-on in add-on manager instead of on the page.

This sounds like it would work from the front-end's perspective. I assume the code on the server would have to change with each new release though, as it won't be permanently `75` and `77`, which might be an argument in favour of a simple flag indicating if the add-on is compatible with Fenix and which version of Fenix (Beta vs. Nightly), as opposed to returning a compatible version number.

**Comment by jvillalobos** [comment]
I'd like to revisit this work since the majority of users are being migrated to Fenix and this error message is getting more attention.

**Comment by diox** [comment]
The [collection linked above for beta](https://addons.mozilla.org/en-US/firefox/collections/4757633/7e8d6dc651b54ab385fb8791bf9dac/) is already obsolete - it only links ublock origin as I'm writing this. The [one for nightly](https://addons.mozilla.org/en-US/firefox/collections/4757633/16f6e5d9a40448b8955db57ced6d75/) seems to match availability on release, so clearly it's not based on channels anymore.

To reinforces my point above that to solve this, we need a clear indicator of what add-ons are compatible with which *version*.

**Comment by jvillalobos** [comment]
The distinct collections for Fenix have been convenient so far for testing, because we've been extra careful about introducing new extensions. However, moving forward we expect the single list of recommended add-ons for Android to be the source of truth for all versions of Fenix, and if we go with full availability I don't expect us to keep track of which add-on versions are compatible with which application versions, neither on the manifest nor on AMO.

**Comment by jvillalobos** [comment]
This is the [current collection for Fenix release](https://addons.mozilla.org/collections/4757633/3204bb44a6ef44d39ee34917f28055/), which is the current source of truth. Since this is a temporary patch while we implement better Fenix support, I think we can either rely solely on this collection or just hardcode the solution for the 9 add-ons currently there. We plan to add some more in the coming months, but we can add those manually later if necessary.

**Comment by bobsilverberg** [comment]
So is the decision here to simply hardcode a list of ids in the frontend code (based on the collection linked above), as a temporary solution, and use that to determine which message to display? Should the new message still be "You can install this add-on in the Add-ons Manager. Learn more about [add-ons for Android]."? Is there anything else to discuss?

@jvillalobos @diox

**Comment by jvillalobos** [comment]
Nothing left to discuss from the Product side. If hardcoding is the best path forward, let's do that.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- The 9 add-ons from the [collection](https://addons.mozilla.org/en-US/firefox/collections/4757633/3204bb44a6ef44d39ee34917f28055/) display the new message metioned [above](https://github.com/mozilla/addons-frontend/issues/9360#issue-601390447).  The state of the install button is inactive and the message advises the user to install the add-on from Add-ons Manager. 


![message for Fenix collection](https://user-images.githubusercontent.com/33448286/93450231-65a59500-f8de-11ea-9dfa-c9cd29605ee0.png)

- Looking over other addons/themes I see the other message 
"Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. Learn more about [add-ons for Android]."

@jvillalobos Thanks for the [GUID](https://github.com/mozilla/addons-frontend/issues/9360#issue-601390447) list. 

I verified this on FF8.1.3 - Fenix with Android 9.0.
