### ISSUE TITLE
Make URLs derived from API data work as expected

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#937]
When URLs from API data are used on a page, they need to:
- link to a relative URL, not an absolute URL
- do the right thing in the react router (maybe they already do?)

As an example, you can try out the add-on author URL that was hooked up to the details page in https://github.com/mozilla/addons-frontend/issues/883

**Comment by tofumatt** [comment]
I think this would be related to #1349 as well, but I think a lot of API URLs are absolute so not sure they'll work with react-router.

**Comment by muffinresearch** [comment]
Already fixed
