### ISSUE TITLE
Add a script to extract & merge l10n

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#9373]
According to @willdurand (from https://github.com/mozilla/addons-frontend/blob/master/docs/i18n.md#extracting-newly-added-strings) the procedure is (trivially)
```
git checkout master
git pull
git checkout -b amo-locales
NODE_APP_INSTANCE=amo bin/extract-locales
git commit -a -m "Extract AMO locales"
NODE_APP_INSTANCE=amo bin/merge-locales
git commit -a -m "Merged AMO locales"
git push origin amo-locales
```
so we should have that as a script.  Ideally with some git diff verification but that can be an enhancement.  MVP should just be to avoid us having to manually type 16 lines of commands (8 per app) and make sure each person running the extraction is following the exact procedure each week.

**Comment by bobsilverberg** [comment]
One of the things we do after the `extract-locales` step is check to see if any new strings were actually extracted. If there are not any, then we stop there and do not create any commits nor any PR. Do we feel this is an important step even for the MVP of this, or are we happy to push new commits each week that potentially do nothing other than change the date of the extract?

**Comment by eviljeff** [comment]
I figured we could create the PR and then look on github.  If the PR is pointless just close it without merging.
