### ISSUE TITLE
Sunset the disco app

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9379]
The disco app isn't really used anymore or shouldn't be since FF has its own implementation for some time. We would like to stop maintaining the disco app as soon as possible (i.e. stop serving this remote disco app and delete the code related to the disco app in this repo).

Do we want to serve a different page instead of no page? (FF should have a fallback view when the remote disco app does not load)

@mstriemer do you know which FF version does not load https://discovery.addons.mozilla.org/ anymore? We have to make sure the current ESR does not use this disco app.

@jvillalobos you mentioned an issue when the disco app isn't available in FF. I thought we had a fallback view in FF in case the disco app failed to load for some reason. Would you be able to get more info on that?

**Comment by jvillalobos** [comment]
In https://github.com/mozilla/addons-server/issues/9468 we discontinued the legacy disco pane by redirecting that frame to a page to download the latest Firefox. I suggest we do the same with this one. I would just add UTM params to the URL for proper attribution (and to the old one while we're at it).

@muffinresearch mentioned the new disco pane having a fallback if it can't be loaded. I don't know what happens now, but Mark might.

**Comment by muffinresearch** [comment]
> In [mozilla/addons-server#9468](https://github.com/mozilla/addons-server/issues/9468) we discontinued the legacy disco pane by redirecting that frame to a page to download the latest Firefox. I suggest we do the same with this one. I would just add UTM params to the URL for proper attribution (and to the old one while we're at it).
> 
> @muffinresearch mentioned the new disco pane having a fallback if it can't be loaded. I don't know what happens now, but Mark might.

IIRC The fallback is just an error message saying it can't be loaded.

**Comment by muffinresearch** [comment]
So if that is in 60, looks like the new one was in 68 https://bugzilla.mozilla.org/show_bug.cgi?id=1533795 and 60ESR has long been superceded.

**Comment by muffinresearch** [comment]
@jvillalobos you mentioned a bug with `about:addons` if the disco pane (served from AMO) can't be loaded, do you have details of that?

**Comment by jvillalobos** [comment]
I don't have any references for that, sorry. I think it came up when we decided to discontinue the legacy panel in https://github.com/mozilla/addons-server/issues/9468, so it might not be relevant for this sunset.

**Comment by mstriemer** [comment]
The Firefox implementation shipped in 68 by default but that release still has preferences to disable the HTML about:addons stuff. Flipping `extensions.htmlaboutaddons.discover.enabled` will still load the discovery pane from AMO. Making the URL 404 shows the error page that Stuart posted earlier.

**Comment by muffinresearch** [comment]
> The Firefox implementation shipped in 68 by default but that release still has preferences to disable the HTML about:addons stuff. Flipping `extensions.htmlaboutaddons.discover.enabled` will still load the discovery pane from AMO. Making the URL 404 shows the error page that Stuart posted earlier.

Thanks Mark, has the move to the Firefox-based disco pane been made permanent since 68?

**Comment by mstriemer** [comment]
The pref was removed in [bug 1337627](https://bugzilla.mozilla.org/show_bug.cgi?id=1337627) which was 73.

**Comment by willdurand** [comment]
So, according to https://github.com/mozilla/addons-frontend/issues/9379#issuecomment-618940297, I suppose we can go ahead and stop building and deploying the discopane? That would be ops work first, and once that's done, we can remove the code in this repo.

I suppose we should keep the disco domain up and running and it should return a 404 so that FF displays the fallback view?

**Comment by willdurand** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1672924 to stop building and deploying the discopane, which is something we can do right now given that we don't update the discopane app anyway (the bug is only about removing the ops pipeline to build/deploy, the site will still be up).

**Comment by willdurand** [comment]
> I filed [bugzilla.mozilla.org/show_bug.cgi?id=1672924](https://bugzilla.mozilla.org/show_bug.cgi?id=1672924) to stop building and deploying the discopane, which is something we can do right now given that we don't update the discopane app anyway (the bug is only about removing the ops pipeline to build/deploy, the site will still be up).

This has been done so we can safely remove the code in this repo. After that, we'll have to see what we want to do with the current app and how we want to update the nginx config.

**Comment by AlexandraMoga** [comment]
@willdurand I've verified the `about:addons` page on -dev and stage with various Firefox version, old and more recent. 
Yesterday, Firefox versions below `68.0`  used to still display the old DiscoPane. Extensions and themes could be installed/uninstalled.
Today, however, the DiscoPane will throw a 404, including https://discovery.addons.allizom.org/__frontend_version__

404:
![image](https://user-images.githubusercontent.com/31961530/97583846-1041c500-1a00-11eb-9e4b-03b5fd7a4838.png)

New Firefox versions that serve the  Firefox-based disco pane are not affected by this change. 

The release tests for AMO fronted which cover all the major site functionalities didn't reveal any issues.

**Comment by willdurand** [comment]
>  Today, however, the DiscoPane will throw a 404, including [discovery.addons.allizom.org/__frontend_version](https://discovery.addons.allizom.org/__frontend_version)__

Yes, please see: https://bugzilla.mozilla.org/show_bug.cgi?id=1673924

**Comment by AlexandraMoga** [comment]
> the HTML discopane should be still available in all envs but -stage/-prod should have the version 2020.10.22

So, I understand that the above comment is no longer applicable and having only the 404 page is expected now.

**Comment by willdurand** [comment]
> So, I understand that the above comment is no longer applicable and having only the 404 page is expected now.

Exactly, it's good that you were able to take a look yesterday :)
