### ISSUE TITLE
Filter by license

### ISSUE THREAD

**Issue by yoasif** [mozilla/addons-frontend#9383]
### Describe the problem and steps to reproduce it:

I'd like to see a dropdown in my filters on my search result pages that let me filter by license type.

### What happened?

There is no filter.

### What did you expect to happen?

Something like 

![image](https://user-images.githubusercontent.com/152493/80320156-b22eed80-87e2-11ea-9612-2e2c1632c2d5.png)

### Anything else we should know?

Discussion here: https://www.reddit.com/r/firefox/comments/g89x5b/dear_mozilla_please_have_an_option_to_prioritize/

**Comment by ReticentAdjuvant** [comment]
In any case, increasing certainty related to the safety and security of add-ons is likely to be a positive move. I'm not familiar with this stuff enough to say what the way to do that would be but if allowing users to see and search by license is something that would allow me to legitimately distinguish between whats safe(er) and whats not then I. Am. In.

**Comment by virgilt** [comment]
@wagnerand May I work on this?

**Comment by wagnerand** [comment]
@virgilt This issue awaits a decision from the Product team. @jvillalobos will reply on next steps.

**Comment by jvillalobos** [comment]
The way we currently store licenses on AMO doesn't lend itself for a very reliable search feature. I also don't think this would be something most of our users would benefit from. The license name is available [through the API](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-object), though, so it is possible to implement a custom license-based search from an app or an extension.

**Comment by es20490446e** [comment]
I think this is important. Also automatically converting the current state of license data into something that could be put in a drop-box should be easy, as all known licenses have predictable text on them.

**Comment by ssokolow** [comment]
> Also automatically converting the current state of license data into something that could be put in a drop-box should be easy, as all known licenses have predictable text on them.

It depends on how you want to trade off false positives vs. false negatives. GitHub works on this paradigm and I have trouble pleasing [their license detector](https://github.com/licensee/licensee) without using their own pull request generator to add the license.

**Comment by es20490446e** [comment]
I mean performing the detection once for the already exiting data, converting them to a more predictable format.

So if there is a missing corner case it can just be manually fixed.

**Comment by ssokolow** [comment]
In that case, maybe *use* GitHub's Ruby-based detector as a first past, since, in my experience, it errs on the side of rejecting a license as unrecognized in favour of trustworthy output.
