### ISSUE TITLE
Search doesn't return all matching results and returns some non-matching results

### ISSUE THREAD

**Issue by nodeticswww** [mozilla/addons-frontend#9385]
### Describe the problem and steps to reproduce it:

Search functionality on Mozilla Add-on Store is not functioning properly. If you search with example the word "nodetics", the search is expected to return all WebExtensions which have this string in their description or author name.

### What happened?

The search returns 4 out of 6 matching extensions (Feedbro and LinCV are dropped out for some reason) and 2 results that don't have the search string at all.

Test link:
https://addons.mozilla.org/en-GB/firefox/search/?q=nodetics&sort=relevance&type=extension

**Comment by willdurand** [comment]
cc @diox

**Comment by nodeticswww** [comment]
Looks like the 4 extensions that are returned by the search have the search term as is in the text description. LinCV and Feedbro don't have that string in the description - only in author name.

But what I don't understand is where do those 2 extra results come from?

**Comment by diox** [comment]
Hi,

We don't match by author name anymore as it was abused by developers too much. The ones that are returned at the top have that word in their description.

The 2 others are because we do fuzzy matching to help with misspellings etc. They appear towards the bottom, as intended because the fuzzy matching gives them a lower score.

So everything is working as intended as far as I am concerned.

**Comment by nodeticswww** [comment]
Out of curiosity: how would developers "abuse" the fact that it is possible to search by developer name?
After all, developers are free to write pretty much anything to the extension description?
Also it looks like the two other results have basically nothing to do with the search phrase (the other result is even described in Russian and is totally unrelated. The second "fuzzy" result is also completely unrelated and there are very few if any common words in the description.
So I would say that the fuzzy search quality is very poor at least based on this particular search.
