### ISSUE TITLE
Help reduce logging volume in production

### ISSUE THREAD

**Issue by bqbn** [mozilla/addons-frontend#9389]
### Describe the problem and steps to reproduce it:

AMO generates about 600+ GB logs per month. All those go across the Internet from AWS to GCP, and incur data transfer fees.

Can we configure the app to suppress at least DEBUG level logs for production?

For example,

```
{"amo_request_id":"dabac1ce-c99b-479e-b3bb-676f8d97ed18","msg":"Replacing lang in URL fi -> fi"},"Hostname":"ip-172-31-40-157.us-west-2.compute.internal","Logger":"amo","Pid":229,"Severity":6,"Timestamp":1588117070517667300,"Type":"app.log"}
```

Not sure how useful that line is but there are a *LOT* of them like that.

### What did you expect to happen?

Suppress at least DEBUG level logs and/or unnecessary logs  to help reduce cost and possibly improve performance.

### Anything else we should know?

n/a

**Comment by willdurand** [comment]
I am actually surprised that addons-frontend has `DEBUG` logs in production. According to the config, the logging level should be `INFO`.

**Comment by willdurand** [comment]
> For example,
> 
> ```
> {"amo_request_id":"dabac1ce-c99b-479e-b3bb-676f8d97ed18","msg":"Replacing lang in URL fi -> fi"},"Hostname":"ip-172-31-40-157.us-west-2.compute.internal","Logger":"amo","Pid":229,"Severity":6,"Timestamp":1588117070517667300,"Type":"app.log"}
> ```

This looks like an `INFO` message but we can probably change its level.

**Comment by willdurand** [comment]
I think https://github.com/mozilla/addons-frontend/pull/9392 will help a lot but I am keeping this issue opened to see if there are other log statements we could change.

**Comment by bqbn** [comment]
Thanks @willdurand for acting on this issue!

> According to the config, the logging level should be INFO.

Curiously, where can I see the config? The log message just says `"Severity":6`, and it's hard to tell what level that is.

**Comment by willdurand** [comment]
> Curiously, where can I see the config?

This is configured here: https://github.com/mozilla/addons-frontend/blob/563b06af576b53c6847920f355abd26a0efec8c6/config/default.js#L52

> The log message just says "Severity":6, and it's hard to tell what level that is.

Stackdriver will show the logging level names (take a look at the logs in -dev) as of next week's push.

**Comment by willdurand** [comment]
I think the recent changes should be enough to fix this issue.
