### ISSUE TITLE
Use GUID instead of the add-on name when logging a GA event 

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9410]
I noticed in Google Analytics that install events are being logged differently for the same add-on because the label uses the add-on name, and the name can vary by locale. I think it would be best to use the default locale, so the results are better grouped. If wanted to be really strict we would use the GUID, but that would make the GA results harder to navigate, so let's stick to the name.

**Comment by bobsilverberg** [comment]
I believe that we only get the name back from the API for the current locale, so it sounds like this would need either an additional API request, or a change to the API to return both the name for the current locale *and* the name for the default locale, either of which might not make this a good first bug.

@jvillalobos To avoid this issue, perhaps we could use the `slug`, rather than either the `name` or the `guid`? `slug` is not translatable, and it is generally more easily interpreted than a `guid`.

**Comment by jvillalobos** [comment]
I'm more in favor of adding the default locale name to the API, so that we don't break historical data comparisons. If we were to change to a different attribute I think I'd just go straight to the GUID.

@muffinresearch also mentioned there may be some object that can be sent with events to add extra data. Can someone confirm that is possible? If so, it'd be great to add that GUID to id.

**Comment by bobsilverberg** [comment]
> I'm more in favor of adding the default locale name to the API, so that we don't break historical data comparisons. If we were to change to a different attribute I think I'd just go straight to the GUID.
> 
> @muffinresearch also mentioned there may be some object that can be sent with events to add extra data. Can someone confirm that is possible? If so, it'd be great to add that GUID to id.

Sure, I can look into that.

**Comment by bobsilverberg** [comment]
Also, just wondering, if we were able to send both the GUID and the name in the current locale (i.e., not the default locale), would that enable you to group events as you wish, and also be able to see the name (even though it might appear different for different events)? Just want to verify that changing the API is the only solution that is going to work for you before we take that task on. Also, because AMO is not the only consumer of this API, I need to check whether this would necessitate a version bump for that API, which would make this an even bigger task.

**Comment by diox** [comment]
I would rather we avoid doing the API change. As mentioned in https://github.com/mozilla/addons-server/issues/14250 returning the name in default locale is very difficult to do, at least not without incurring a significant perf cost - the translations mechanism was never meant to return multiple translations in an optimized way, and it's one of the more delicate parts of addons-server, if not the most delicate.

**Comment by muffinresearch** [comment]
Looks like the thing I was thinking of was the [objects with custom metrics sent along with an event as defined here](https://developers.google.com/analytics/devguides/collection/analyticsjs/custom-dims-mets) - I'm not sure that's necessarily useful for this case though.

**Comment by bobsilverberg** [comment]
When we send an event to GA we can specify 4 things: `action`, `category`, `label` and `value`. We are only using the first three when logging installs, so we could use the `value` to pass either a GUID or a `slug`. 

@jvillalobos do you think it's worth doing that as a first step and see how helpful it is? @diox seems to be indicating that we should avoid making the API change, and we could consider another API request, specifying the default locale, but I think we probably want to avoid that too.  What do you think?

**Comment by willdurand** [comment]
> I noticed in Google Analytics that install events are being logged differently for the same add-on because the label uses the add-on name, and the name can vary by locale. I think it would be best to use the default locale, so the results are better grouped.

Do we use the add-on name _only_ to group installs by add-on in GA?

**Comment by jvillalobos** [comment]
It looks like `value` won't help in this case. It's meant to be a numerical value in GA and can't be used in the main filtering features.

Let's change the `label` to be the GUID, for these event categories:

- AMO Addon / Recommendations Shown
- AMO Addon Installs Started	
- AMO Addon Installs	
- AMO Theme Installs Started	
- AMO Theme Installs	
- AMO Addon Installs Cancelled	
- AMO Addon Uninstalls
- AMO Theme Uninstalls
- AMO Addon Activation	
- AMO Theme Activation	
- AMO Addon Installs Download Failed	
- AMO Theme Installs Cancelled	
- AMO Theme Installs Download Failed

I'll file a separate issue to make some changes to other events, so they are more consistent across the board.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos. What is the priority of this change? This issue is marked as a possible good first bug, and while I agree that now it probably is one, leaving it to contributors means it might not be completed particularly quickly. Are you fine with that, or should I just fix it now?

**Comment by jvillalobos** [comment]
It's not urgent, so I think it's fine to leave it to a contributor.

**Comment by willdurand** [comment]
My question still stands because I am wondering whether the data in GA might have been corrupted somehow. For instance, if we only rely on the name to aggregate data, a set of random add-ons with the same name would increment only one add-on in GA, making it more downloaded and therefore popular than it should.

**Comment by bobsilverberg** [comment]
> My question still stands because I am wondering whether the data in GA might have been corrupted somehow. For instance, if we only rely on the name to aggregate data, a set of random add-ons with the same name would increment only one add-on in GA, making it more ~downloaded~ installed and therefore popular than it should in GA.

Yes, the only identifying info we send is the `name`, so it is true that if we have multiple add-ons with the same name, their data will be aggregated.

**Comment by jvillalobos** [comment]
Yes, we might want to fix this in Q3 if there are no takers before then, since we want to use GA for public download stats.

**Comment by caitmuenster** [comment]
Hi  @willdurand, can you leave a comment about how a contributor could fix this bug (if it's a good-first-bug)?

**Comment by caitmuenster** [comment]
@willdurand noted in a conversation on Matrix that this isn't a good first bug, and that because we're not using GA for download stats this might not be an issue anymore. 

@jvillalobos & @bobsilverberg, does that sound about right?

**Comment by bobsilverberg** [comment]
I think we're still planning on using GA for other types of analyses, so I think this issue still needs to be addressed. @jvillalobos?

**Comment by jvillalobos** [comment]
Yeah, we still want this. It might be too big for a gfb, though.

**Comment by willdurand** [comment]
> Yeah, we still want this. It might be too big for a gfb, though.

I think I opened a google docs with a description of all the changes once, am I correct? If so, we could link it here.

**Comment by bobsilverberg** [comment]
> 
> I think I opened a google docs with a description of all the changes once, am I correct? If so, we could link it here.

Is it this? https://docs.google.com/document/d/17KYC6cMY3hxWunFPdTgJGct6r6A47q2vvZc6yREYN3Q/edit#heading=h.5jehpcvz2ia3

**Comment by willdurand** [comment]
It is, thanks!

**Comment by caitmuenster** [comment]
Do we want to mark this as `contrib: welcome`?

**Comment by bobsilverberg** [comment]
> Do we want to mark this as `contrib: welcome`?

I think that would be fine.

**Comment by bobsilverberg** [comment]
Just going through issues that I've participated in and this one popped up. Now that we're nearing the end of Q3, and no contributors have picked this up, should I just get it done? Or are we fine with waiting for a contributor to do it?

@jvillalobos

**Comment by jvillalobos** [comment]
@bobsilverberg We're using GA events to track performance of the promoted add-ons pilot, so if this is something that can be fixed by the next push then I'm okay with it. Otherwise I'd rather hold off on changing this until after the pilot, in November.

**Comment by bobsilverberg** [comment]
I can get it done for next week's push. I'm going to close this one and do it all via #9417 though.
