### ISSUE TITLE
The 'Learn more about permissions' button should always be visible on the Permissions card

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9411]
Follow up for #7634 

### Describe the problem and steps to reproduce it:
1. Open the following extension detail page - https://addons.allizom.org/en-US/firefox/addon/many-files/
2. Scroll down to the Permissions card and look for the 'Learn more about permissions' button

### What happened?
The button is hidden in the `ShowMoreCard` 

### What did you expect to happen?
The button is always visible, i.e the user should not have to click on Read more to access the button

### Anything else we should know?
- a `ShowMoreCard` for Permissions was introduced when #7634 was fixed

![2020-05-07_12-19-51](https://user-images.githubusercontent.com/31961530/81278683-ac48d000-905e-11ea-9645-bb70cd231327.gif)

**Comment by Aakash2408** [comment]
I would like to work on this issue. Kindly assign this to me.

**Comment by willdurand** [comment]
@Aakash2408 done

**Comment by Kushagraw12** [comment]
Is this issue still open? Can i work on it? Thanks!

**Comment by Aakash2408** [comment]
@Kushagraw12  just wait for 2 days if it is not done  then I will inform you

**Comment by Kushagraw12** [comment]
> @Kushagraw12 just wait for 2 days if it is not done then I will inform you

Okay, I will wait. Thank!

**Comment by Aakash2408** [comment]
@Kushagraw12 just wait for one more day . If this is not done by tomorrow this time @willdurand  can surely assign  this to you.

**Comment by Kushagraw12** [comment]
> @Kushagraw12 just wait for one more day . If this is not done by tomorrow this time @willdurand can surely assign this to you.
Okkay. 
Thanks. 
I will make myself familiar with the code base by then.

**Comment by Aakash2408** [comment]
@willdurand I AM trying to push the code but it is showing access denied. 
![Screenshot from 2020-07-13 19-17-22](https://user-images.githubusercontent.com/47134609/87312338-0c1b9580-c53e-11ea-9dd4-a0257a2b7698.png)
What can I do?

**Comment by willdurand** [comment]
>  What can I do?

You should create a fork: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

**Comment by Aakash2408** [comment]
> > What can I do?
> 
> You should create a fork: https://docs.github.com/en/github/getting-started-with-github/fork-a-repo

oops! Really sorry I directly cloned it .

**Comment by willdurand** [comment]
> oops! Really sorry I directly cloned it .

That's no problem. Once cloned, you can still create a fork and then add a new "remote" that points to your fork.

**Comment by Aakash2408** [comment]
@willdurand can you just tell me if we want both buttons i.e, Read more and the other button or we just want to show 'learn more about permissions' without readme button?. I will push the code just now.

**Comment by Kushagraw12** [comment]
I guess its done. Can you suggest me some other easy issue through which i can make my first contribution to this organization? I am new to open source! 😅
Thanks! :)

**Comment by Aakash2408** [comment]
@Kushagraw12 no it's
 not done am having some yarn build issues you can do it if you want .

**Comment by Kushagraw12** [comment]
> @Kushagraw12 no it's
> not done am having some yarn build issues you can do it if you want .

Okay. I just finished up setting up my local development setup.
I will start working on this issue. Can you give me a heads up where to start from for this issue?
Thanks

**Comment by Kushagraw12** [comment]
@willdurand 
Does this look good enough or should i completely remove the 'Read More' from this card?
Thanks!
![Screenshot (51)](https://user-images.githubusercontent.com/53997603/87451882-22008780-c61e-11ea-85c7-98b90aed119a.png)

**Comment by bhushan-borole** [comment]
Hey @willdurand 
I would like to work on this issue.
As I understand, the Learn more about permissions button should be visible.
So is it okay if I remove the Read more button?

**Comment by bobsilverberg** [comment]
I think we could use some UX input/guidance on this. Trying to make sure that the button appears inside the compressed card when "Show more" is available is going to be tricky. A couple of suggestions are:
1. Move the button to the top of the card.
2. Get rid of the "Learn more about permissions" button and make it a link in the card header instead.

I'll add this to the front-end meeting agenda, but pinging @aaronrbenson in case he has time to take a look.

**Comment by bobsilverberg** [comment]
@aaronrbenson I believe you were going to take a look at this. We discussed it in the front-end meeting on August 4th. Have you had a chance to look at/think about it yet?

**Comment by bobsilverberg** [comment]
@Kushagraw12 We now have a direction for what we want to do with this issue. Are you still interested in working on it?

**Comment by Kushagraw12** [comment]
> @Kushagraw12 We now have a direction for what we want to do with this issue. Are you still interested in working on it?

Yeah, please tell me what has to be done, i will try my best to do it! ✌🏻

**Comment by bobsilverberg** [comment]
@Kushagraw12 We would like the following changes:
- Remove the "Learn more about permissions" button.
- Add a text link into the header of the card (where it currently shows "Permissions" in bold), which says "Learn more", and includes the icon from the current button (see below for a screen shot of the icon). This link should point to the same destination as the current button, and should be right-aligned in the card header.

Icon:

<img width="25" alt="Screen Shot 2020-10-06 at 11 09 19 AM" src="https://user-images.githubusercontent.com/142755/95220537-9170b800-07c4-11eb-896c-87cce673a57a.png">

**Comment by Kushagraw12** [comment]
> 
> 
> @Kushagraw12 We would like the following changes:
> 
>     * Remove the "Learn more about permissions" button.
> 
>     * Add a text link into the header of the card (where it currently shows "Permissions" in bold), which says "Learn more", and includes the icon from the current button (see below for a screen shot of the icon). This link should point to the same destination as the current button, and should be right-aligned in the card header.
> 
> 
> Icon:
> 
> <img alt="Screen Shot 2020-10-06 at 11 09 19 AM" width="25" src="https://user-images.githubusercontent.com/142755/95220537-9170b800-07c4-11eb-896c-87cce673a57a.png">

Sure, I will look right into it! 
Thanks!

**Comment by Kushagraw12** [comment]
@bobsilverberg Which of the following versions do you like more?
1. 
![Screenshot from 2020-10-29 02-25-52](https://user-images.githubusercontent.com/53997603/97496346-d1bff200-198e-11eb-892c-4e67e62766bf.png)

2. 
![Screenshot from 2020-10-29 02-27-18](https://user-images.githubusercontent.com/53997603/97496378-dc7a8700-198e-11eb-93e9-ca81881d4cbe.png)

I personally like the second one more(without the icon)

**Comment by bobsilverberg** [comment]
Thanks for the screenshots, @Kushagraw12! I agree that the one with the icon doesn't look very nice, partially because the icon includes the grey background. It is possible to make an example of that one where the background is white or transparent? I think that would greatly improve its appearance.

**Comment by Kushagraw12** [comment]
Okay @bobsilverberg , I will try making the bg transparent

**Comment by AlexandraMoga** [comment]
This issue is verified on dev, FF88, Win10 and Android 10:

![image](https://user-images.githubusercontent.com/31961530/117427561-d6f98d00-af2d-11eb-8cdd-84b1953cb339.png)

@willdurand one slight issue that I've noticed is the gap between the 'Learn more' link and the external icon, which is a bit too much in my opinion (the icon has a `margin-left:` of  `12px;`.

The Developer Hub and Extension Workshop links in the header also have an external icon attached, but the `margin-left` there is set at `5px`:
![image](https://user-images.githubusercontent.com/31961530/117428304-9d755180-af2e-11eb-90ff-5976e760a93d.png)
[Learn more with `margin-left: 5px;`]
![image](https://user-images.githubusercontent.com/31961530/117428490-ce558680-af2e-11eb-80aa-52aff45a8737.png)

It's a small change, but I think it looks better. If you also agree, I can file a follow up for this.

**Comment by willdurand** [comment]
> It's a small change, but I think it looks better. If you also agree, I can file a follow up for this.

Yes I was also not happy with this but I couldn't find a reason why it was like this. It looks like it's the default... Let's have an issue filed and I'll check again.
