### ISSUE TITLE
/users/edit?to=<URL of code manager> does not redirect to the desired page after saving the user profile

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-frontend#9413]
### Describe the problem and steps to reproduce it:

1. Visit https://code.addons-dev.allizom.org/
2. Start the login flow.
3. After completing the FxA login flow, it redirects to https://addons-dev.allizom.org/en-US/firefox/users/edit?to=https%3A%2F%2Fcode.addons-dev.allizom.org%2F
4. Set a display name and click on "Update My Profile" at the bottom.

### What happened?

I end up at https://addons-dev.allizom.org/en-US/firefox/https://code.addons-dev.allizom.org/

### What did you expect to happen?

I should be at https://code.addons-dev.allizom.org/

### Anything else we should know?

This issue is because a `/` is unconditionally prepended when the `to` value does not start with a `/`: https://github.com/mozilla/addons-frontend/blob/f3e61e2f8a3b8f1070acef0de6b067cf8e0d660f/src/amo/pages/UserProfileEdit/index.js#L205-L207

I guess that the implementation is designed to only allow redirects to trusted locations within AMO. The code manager is a trusted location and should be allowed too

**Comment by bobsilverberg** [comment]
Yes, I believe this code is only meant to redirect users to pages within AMO. What is the use case for needing this for Code Manager?

**Comment by Rob--W** [comment]
The code manager requires a login to AMO. When I start the login flow from the code manager and choose to create a new account, I end up at the user profile page, which forces me to create a display name before being able to proceed. After saving the changes, the user should be redirected to the code manager instead of a non-existing page on AMO.

**Comment by willdurand** [comment]
Yeah, that only occurs for newly created amo accounts from code-manager. I'm not sure we want to support that, it's an edge case. We could probably only reset the `to` value in addons-server when it comes from code-manager, though.

**Comment by bobsilverberg** [comment]
My thoughts were along the lines of @willdurand's. Code Manager accounts will only ever be set up for a select group of users, and I would imagine that most of them would already have an AMO account. I'm not sure this is something worth supporting.

**Comment by willdurand** [comment]
I am marking this issue as wontfix.
