### ISSUE TITLE
Use consistent attribute values across GA events

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9417]
Followup to https://github.com/mozilla/addons-frontend/issues/9410

[This document](https://docs.google.com/document/d/17KYC6cMY3hxWunFPdTgJGct6r6A47q2vvZc6yREYN3Q/edit#) describes the changes I'd like to make to the GA event values we're logging.

**Comment by bobsilverberg** [comment]
@jvillalobos Is this actually a follow-up to #9410, or is it a replacement for that? Also, is this something you'd like to have fixed reasonably soon? If so, I can take it.

**Comment by jvillalobos** [comment]
I called this a follow-up because it involved changing the "Action" attribute to some events (see the yellow rows in the doc). They could both be fixed together, though.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

I went through the document, and I have 2 things to clarify:

- I've met  "The fallback no results" and fallback invalid results" in the Console except for “recommended_fallback-timeout” which I don't know how to trigger, if you can give me a tip. 

- I've seen all the install events except for "AMO Addon Installs Download Failed". Same for a theme. 
I tried with 
https://addons-dev.allizom.org/en-US/firefox/addon/tabby-catextension/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured
https://addons-dev.allizom.org/en-US/firefox/addon/testing-log-out/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search

I can see in the Console a GA event with AMO Theme Installs Started but I did not notice an AMO Theme Installs Download Failed

![not installed](https://user-images.githubusercontent.com/33448286/94808624-12613580-03fa-11eb-9f46-dc49f4034ee9.gif)

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> I went through the document, and I have 2 things to clarify:
> 
> * I've met  "The fallback no results" and fallback invalid results" in the Console except for “recommended_fallback-timeout” which I don't know how to trigger, if you can give me a tip.

I'm not sure how that can be tested. That means that there was a timeout inside the server code which calls the TAAR API, so it's not really something we can emulate via the frontend. Considering that the code that generates the other two pings is basically the same for this one as well, I think it's fine to not verify it specifically.

> 
> * I've seen all the install events except for "AMO Addon Installs Download Failed". Same for a theme.
> I tried with
> [addons-dev.allizom.org/en-US/firefox/addon/tabby-catextension/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured](https://addons-dev.allizom.org/en-US/firefox/addon/tabby-catextension/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=featured)
> [addons-dev.allizom.org/en-US/firefox/addon/testing-log-out/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search](https://addons-dev.allizom.org/en-US/firefox/addon/testing-log-out/?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=search)
> 
> 
> I can see in the Console a GA event with AMO Theme Installs Started but I did not notice an AMO Theme Installs Download Failed
> 
> ![not installed](https://user-images.githubusercontent.com/33448286/94808624-12613580-03fa-11eb-9f46-dc49f4034ee9.gif)

I'm not sure how the changes I made would have an impact on this. Are you able to generate those events on stage, or is this perhaps either an existing issue, or something to do with the way it's being tested?

**Comment by ioanarusiczki** [comment]
@bobsilverberg On the second matter, I tried an install of an addon on stage - the addon is corrupt, I have the same result as I described above.
I don't think this issue had an impact either. Also I don't know if the way I tried to test it is alright but if it's needed I could file it.

**Comment by bobsilverberg** [comment]
> @bobsilverberg On the second matter, I tried an install of an addon on stage - the addon is corrupt, I have the same result as I described above.
> I don't think this issue had an impact either. Also I don't know if the way I tried to test it is alright but if it's needed I could file it.

@jvillalobos Can you confirm whether we are seeing events in GA from these "AMO Addon Installs Download Failed" events (and also for themes)? I just want to check whether the testing methodology is unable to recreate them, or if @ioanarusiczki has uncovered an existing bug here.

**Comment by jvillalobos** [comment]
I see both of those events being reported in GA. "AMO Addon Installs Download Failed" is reported about 1,500 times a day, for example. I have no idea under what circumstances they are reported, or if we're covering all failure cases.
