### ISSUE TITLE
Add comments to eslintrc file

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#942]
The `.eslintrc` file is currently in JSON which means we cannot add any comments. Some rules and configuration would be a lot easier to comprehend with comments so we should move it to `.eslintrc.yaml` or something that allows comments.

**Comment by muffinresearch** [comment]
I think you'll find eslintrc will tolerate comments despite being JSON.

**Comment by kumar303** [comment]
huh! You're right. That's super weird but works for me ;)

**Comment by WiliTest** [comment]
but how do you add a comment?

**Comment by teikmeout** [comment]
Just leaving this here for whoever needs more reference on JSON5 commenting:
- [https://json5.org/](https://json5.org/)

Example tho:
```json5
// glory to JSON5 and to comments
{
  "rules": {}
  // couple of ideas... this should be JSON5 that supports comments
  // https://json5.org/
}
```
