### ISSUE TITLE
Remove `overflow-wrap: anywhere;`

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9423]
This issue is about removing `overflow-wrap: anywhere;` from our codebase if that's possible.

**Comment by MayankVir** [comment]
I am new to Open Source and I would like to contribute in this issue

**Comment by caitmuenster** [comment]
Hi @MayankVir, welcome! This isn't a good bug for contributors. :) You will want to get started with an issue labeled '[contrib: good first bug](https://github.com/mozilla/addons-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22contrib%3A+good+first+bug%22).'

Currently it doesn't look like there are any open good first bugs. We tend to refresh the list about every two weeks. You're welcome to pick up one of those bugs when they become available, or head over to [Codetribute](https://codetribute.mozilla.org/) for other good-first-bugs across Mozilla projects. :)

**Comment by Yashs911** [comment]
Hi, @willdurand I would like to work on this issue.

**Comment by patil2097** [comment]
hi @willdurand  let me if this issue is still open? I would love to help in solving this issue.

**Comment by willdurand** [comment]
> hi @willdurand let me know if this issue is still open? I would love to help in solving this issue.

Please see this comment: https://github.com/mozilla/addons-frontend/issues/9423#issuecomment-680145839

**Comment by willdurand** [comment]
this was fixed by https://github.com/mozilla/addons-frontend/pull/9440
