### ISSUE TITLE
Rename blockpage feature flag

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9426]
We have a convention to prefix our feature flags with `enableFeature`. This was done for the block pages.

For QA: please make sure -dev serves blocked pages. Other envs should not.

**Comment by AlexandraMoga** [comment]
The `/blocked-addon/` pages are still available on -dev. I'll verify that stage doesn't serve them when the code lands there.

**Comment by AlexandraMoga** [comment]
The `/blocked-addon/` pages are not available on stage.
