### ISSUE TITLE
UI tests are failing

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9428]
Looks like the UI tests are back to red :/

Example: https://circleci.com/gh/mozilla/addons-frontend/21034

**Comment by willdurand** [comment]
@jrbenny35 hey could you please take a look? We might need to update FoxPuppet but I am not sure.

**Comment by fiddlytompkus** [comment]
Is there anyone working on it

**Comment by willdurand** [comment]
> Is there anyone working on it

No, but this isn't really an issue for contributors.

**Comment by jrbenny35** [comment]
Got held up a bit on another project. Will get to this before Wednesday

**Comment by jrbenny35** [comment]
So I was able to reproduce the failure locally and it seems the addon needed to be installed for the addon install test returns a 404. Looking in ```storage/files``` I can see a directory with the file but maybe something with nginx has changed?

**Comment by jrbenny35** [comment]
```nginx_1             | 2020/06/17 15:36:37 [error] 7#7: *184 open() "/srv/user-media/addons/98/ui_addon_install-0.0.1-an+fx.xpi" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /user-media/addons/98/ui_addon_install-0.0.1-an+fx.xpi?filehash=sha256%3A812a6841cefa535047d80a0c14fa59da1ccf0706aee547261a03f66a923875bc HTTP/1.1", host: "olympia.test", referrer: "http://olympia.test/en-US/firefox/addon/ui-test-install/"
```

**Comment by willdurand** [comment]
mmm do we use this project? https://github.com/mozilla/addons-nginx

**Comment by jrbenny35** [comment]
> mmm do we use this project? https://github.com/mozilla/addons-nginx

Yes and everything there seems fine

**Comment by jrbenny35** [comment]
Not sure what happened but these are passing again. @willdurand can you confirm this?

**Comment by willdurand** [comment]
ha, hu. indeed. well.. let's close this issue for now then.
