### ISSUE TITLE
Output a summary of both steps of the l10n script at the end

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9430]
### Describe the problem and steps to reproduce it:

Run the l10n script at https://github.com/mozilla/addons-frontend/blob/master/bin/run-l10n-extraction.

### What happened?

Both the `amo` and `disco` steps are run, and the summary for the `amo` step is output after that step completes. Then the output of the `disco` step fills the buffer so you cannot see the summary from the `amo` step.

### What did you expect to happen?

The summary from both steps should appear at the end, so nothing is lost.

**Comment by AlexandraMoga** [comment]
Does this issue require QA?
