### ISSUE TITLE
Homepage layout issue when long unbroken strings are used for the recommended addons

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9432]
Followup for https://github.com/mozilla/addons-frontend/issues/8396#issue-473403723

1. It may seem that https://github.com/mozilla/addons-frontend/issues/8522 regressed
There's a layout issue when the name and description is a longer unbroken string on [Homepage](https://addons-dev.allizom.org/en-US/firefox/).
I tested with FF76(Win10).

![regression nr 1](https://user-images.githubusercontent.com/33448286/82448117-fb0c5600-9ab1-11ea-991c-aa436446ded0.gif)

**Comment by bobsilverberg** [comment]
We should fix this. It's not a very high priority as we are in control of what goes into that field, and I cannot imagine an administrator adding a long unbroken text string.

This is likely just a one-line css change, so I think it's a decent candidate for a good first bug.

**Comment by ioanarusiczki** [comment]
@willdurand 

Verified on AMO dev with FF76(Win10).

![long stringfix1](https://user-images.githubusercontent.com/33448286/82871942-fc6ad200-9f3a-11ea-8f79-9289439aa461.png)
