### ISSUE TITLE
The versions notes are cut on the version page when a long unbroken string is used

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9433]
As a followup for https://github.com/mozilla/addons-frontend/issues/8396#issue-473403723

STR:
1.  I edited the release notes for a version adding a long unbroken string. The version page looks like:
https://addons.allizom.org/en-US/firefox/addon/search_by_image/versions/?src=rating

![versionnotes](https://user-images.githubusercontent.com/33448286/82448913-12980e80-9ab3-11ea-9c6c-6d0cbfe18d51.png)

I tested on FF76(Win10). 
When resizing, at ~600 width the text is entirely visible.

**Comment by bobsilverberg** [comment]
This is similar to https://github.com/mozilla/addons-frontend/issues/9432. It's probably just a simple css fix, but not a high priority as it's unlikely that the release notes for a version would contain a long unbroken string in the wild.

**Comment by ioanarusiczki** [comment]
@willdurand This is still reproducible. Please take a look: https://addons.allizom.org/en-US/firefox/addon/search_by_image/versions/

**Comment by willdurand** [comment]
> @willdurand This is still reproducible. Please take a look: [addons.allizom.org/en-US/firefox/addon/search_by_image/versions](https://addons.allizom.org/en-US/firefox/addon/search_by_image/versions/)

@ioanarusiczki mm would you have a link in -dev?

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev with FF76(Win10).  
Sorry once again. I was awake I wasn't on coffee this morning.

![fixed](https://user-images.githubusercontent.com/33448286/82910754-acf4c800-9f73-11ea-8bff-7a77c707094d.png)
