### ISSUE TITLE
Layout issue when resizing `All reviews` page using Responsive Design Mode

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9436]
Followup for https://github.com/mozilla/addons-frontend/issues/8396#issue-473403723

Similar with https://github.com/mozilla/addons-frontend/issues/4108 

Resizing this page with Responsive Design Mode https://addons.allizom.org/en-US/firefox/addon/search_by_image/reviews/716646/?src=rating somewhere between 720 ~790px width the name of the reviewer and the text are not entirely displayed.

This is reproducible when the name of the reviewer is a long unbroken string. The review is a text with or without spaces.

![edge case](https://user-images.githubusercontent.com/33448286/82450756-c5696c00-9ab5-11ea-9b1e-3daa91174f2c.gif)

I tested on FF76(Win10) - AMO stage.

**Comment by bobsilverberg** [comment]
This is similar to https://github.com/mozilla/addons-frontend/issues/9432. It's probably just a simple css fix, but not a high priority as it's unlikely that the name of a reviewer would be a long unbroken string in the wild.

**Comment by ioanarusiczki** [comment]
@willdurand This is still reproducible on AMO dev 

![cut](https://user-images.githubusercontent.com/33448286/82873220-d6dec800-9f3c-11ea-9e37-2e7c7f46c909.png)

**Comment by willdurand** [comment]
@ioanarusiczki could you please share a link in -dev?

**Comment by ioanarusiczki** [comment]
@willdurand Sure, I tested with https://addons.allizom.org/en-US/firefox/addon/search_by_image/reviews/716646/?src=rating

**Comment by ioanarusiczki** [comment]
@willdurand Same problem. It is AMO stage.

**Comment by willdurand** [comment]
> @willdurand Same problem. It is AMO stage. Brb

@ioanarusiczki so AMO stage hasn't been patched yet?

**Comment by ioanarusiczki** [comment]
@willdurand As far as I know if it has this week's milestone this should go only Wednesday on stage.

However, I tested on dev and I changed the name of the user from a long unbroken string of 50 chars to one with spaces but I used the maximum of 50. 
I see the date "2 months ago"  and some words cut (maximum 2 chars missing), maybe 2 letters from the display name too are missing. 

https://addons-dev.allizom.org/en-US/firefox/addon/dark22reader/reviews/564593/

**Comment by willdurand** [comment]
Ok, so this is indeed a problem. mmmm

**Comment by willdurand** [comment]
@ioanarusiczki I added another fix.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me. Verified on AMO dev with FF76(Win10). 

![Bugfix](https://user-images.githubusercontent.com/33448286/82987892-00612780-a001-11ea-89f1-7a9d7658a24f.png)
