### ISSUE TITLE
Flagged label for reviews is too narrow

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9446]
I noticed this while testing https://github.com/mozilla/addons-frontend/pull/9437, but it's not a result of that update. I imagine it's been around for some time, perhaps since https://github.com/mozilla/addons-frontend/pull/9252.

When you flag a review, and the word "Flag" gets updated to "Flagged", the container is too narrow and the word gets wrapped. See below for a couple of examples:

<img width="844" alt="Screenshot 2020-05-25 10 53 01" src="https://user-images.githubusercontent.com/142755/82823680-02e34600-9e76-11ea-979e-c7c732918b21.png">

<img width="856" alt="Screenshot 2020-05-25 10 53 24" src="https://user-images.githubusercontent.com/142755/82823703-10003500-9e76-11ea-91c1-3d8fb005a757.png">

**Comment by atiqueahmedziad** [comment]
I guess this is a regression from pr #9210 for `overflow-wrap: anywhere;`. I was comparing a old version of the codebase with the current version and found the above change in between them.

**Comment by bobsilverberg** [comment]
> (Edit: sorry, i mentioned wrong pr earlier)
> I guess this is a regression from pr #9440 for [`overflow-wrap: anywhere;`](https://github.com/mozilla/addons-frontend/pull/9440/files#diff-46b8e211d527633d95f3e81e59f5cb98R36). I was comparing a old version of the codebase with the current version and found the above change in between them.

Interesting! Thanks for looking into this @atiqueahmedziad. Are you interested in submitting a patch to fix it?

**Comment by atiqueahmedziad** [comment]
Yeah 😄

**Comment by bobsilverberg** [comment]
Now a duplicate of #10138
