### ISSUE TITLE
Investigate downgrading or removing common warning log message about unknown add-on type

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#9453]
Stackdriver is full of these:
```
"add-on category for unknown add-on type "persona" for clientApp "persona" received from API."
"add-on category for unknown add-on type "search" for clientApp "search" received from API."
"add-on category for unknown add-on type "theme" for clientApp "theme" received from API."
```

There is no context, so we don't know what request caused this. But it's extremely common, it's filling up the stackdriver console.

- Is this an actual problem ? With the API or the frontend ?
- Should we continue logging this ? If so, consider adding context. If not, let's remove or downgrade it sooner rather than later.

**Comment by willdurand** [comment]
Ha yeah, I've seen those too. It's coming from https://github.com/mozilla/addons-frontend/blob/9839f45f1192f1fb50c324fbb306e34c23d23173/src/core/reducers/categories.js#L114-L133 and I think we don't care. Let's change `warn` to `debug`.

**Comment by eviljeff** [comment]
As I was saying the meeting, pretty sure this is because addons-server still has all the categories for obsolete legacy types in it's constants.  If we remove them from addons-server (and the database) then they won't appear in the API response

**Comment by willdurand** [comment]
Yeah, I'll give that a try
