### ISSUE TITLE
Do not use `public_stats` anymore

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9455]
We'll get rid of public stats soon (cf. https://github.com/mozilla/addons-server/issues/14463) so let's remove the use of `public_stats` everywhere. We'll keep links to the stats but only for developers and admins.

**For QA:** add-on detail pages for add-ons with public stats won't show a link to the stats anymore, unless the user is authenticated AND the author OR an admin.

**Comment by willdurand** [comment]
cc @jvillalobos

**Comment by ioanarusiczki** [comment]
@willdurand 

For listed add-ons: 
"Visit stats dashboard" is available when the user is an admin or if the user is the author of the addon.

Verified on AMO dev with FF76(Win10).
