### ISSUE TITLE
Install button fallback for FF < 48 and FFAndroid < 50

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#946]
Once we have the new install button up and running on the amo pages one consideration is what we need to do for clients that don't have the API available to them.

We should probably feature detect that and fall-back to a pre-48 install route when that happens.

This will need some UX for the button.

**Comment by muffinresearch** [comment]
This also impacts Firefox Android before 50.

**Comment by muffinresearch** [comment]
@pwalm any chance you can look at this we're going to need to get this figured out ahead of hooking up the install buttons?

**Comment by pwalm** [comment]
Can we fall back to the existing button? Not sure what other route we would take. @designakt? Any insight on this?

**Comment by pwalm** [comment]
Button states for fallback:
<img width="1028" alt="screen shot 2016-10-24 at 12 38 05 pm" src="https://cloud.githubusercontent.com/assets/6797635/19660968/c02acef6-99e6-11e6-8e0c-a767d011ea00.png">

**Comment by pwalm** [comment]
Agreed, re-skin the current controls. Will update the mocks.

**Comment by tofumatt** [comment]
A long press on a theme link could be a neat preview method, provided the
theme won’t be too obscured by a finger on the screen.

Otherwise toggle is the best option I think.

**Comment by Ryuno-Ki** [comment]
Sounds rather like a `checkbox` than a `button` to me, because `checkbox` can hold a state (“Preview” clicked or not). You can bind the other buttons (“Keep it” and “Cancel”) on it.

**Comment by mstriemer** [comment]
@pwalm @designakt how should the **Try it on** functionality work when we have `mozAddonManager` present? Should we standardise this between the two cases as I suggested above in https://github.com/mozilla/addons-frontend/issues/946#issuecomment-256757056?

**Comment by pwalm** [comment]
> there is no way to preview a theme with the toggle

Do we need "preview"? I think the user just switches it on, and if they don't like it, the switch it off (and we use the spec'd fall back otherwise)

**Comment by mstriemer** [comment]
The problem with that is if you have theme "Butterflies" installed and install theme "Puppies" then uninstall "Puppies" you go back to the default theme (no theme).

We might be able to do something to remember the last theme that was installed but it wouldn't work across page refreshes and it might seem a little odd to turn off one theme and have another one turn on.

**Comment by pwalm** [comment]
We could do something like this:
<img width="688" alt="screen shot 2016-11-16 at 3 06 16 pm" src="https://cloud.githubusercontent.com/assets/6797635/20369522/45ab44be-ac0e-11e6-8d36-910139cbf786.png">
The top one would be what you see the first time, and it would change to just an eye icon once you've tried it out. And that way we can keep the switch, and not have a totally separate interaction for themes.

**Comment by mstriemer** [comment]
@pwalm would tapping the eye icon preview it or show the **PRESS AND HOLD TO PREVIEW** label?

**Comment by mstriemer** [comment]
Maybe tapping the image alone would be good for previewing? The "button" could say "Tap to preview" and then when previewing say "Tap to stop previewing" (or something better). We could still only show the button until it's clicked the first time.

Hover could still be used on desktop once we set that up.

**Comment by pwalm** [comment]
I like "press" instead of "tap". Tapping is just like flicking the switch. Pressing is a deliberate action: press down and you preview, release and you go back to what it was before. Made the label/icon a bit smaller:
![screen shot 2016-11-18 at 1 54 57 pm](https://cloud.githubusercontent.com/assets/6797635/20448093/27b31cf4-ad97-11e6-9654-7f4f5900c632.png)

**Comment by pwalm** [comment]
Oh, nix that "icon only" view.

**Comment by mstriemer** [comment]
Theme preview has moved to #1422. The work for the button fallbacks is being done in #1429.
