### ISSUE TITLE
update delete copy on account profile page - addons are now deleted too if they delete their account

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#9467]
We need to update the copy and or logic on account profile page to indicate that users with addons will have those addons deleted too if they delete their account on AMO.
From https://github.com/mozilla/addons-server/issues/13896#issuecomment-639663492

Revised copy:
> Your data will be permanently removed, including profile details (picture, user name, display name, location, home page, biography, occupation), notification preferences, reviews, and collections.
If you authored any add-ons they will also be deleted, unless you share ownership with other authors. In that case, you will be removed as an author and the remaining authors will maintain ownership of the add-on.
When you use this email address to log in again to addons.mozilla.org, you will create a new Firefox Add-ons profile that is in no way associated with the profile you deleted.

**Comment by eviljeff** [comment]
@jvillalobos 
> When you use this email address to log in again to addons.mozilla.org, you will create a new Firefox Add-ons profile that is in no way associated with the profile you deleted.

This isn't going to be technically true after #14613 - it'll be the same profile just empty and with no content.  (It should appear as if it's a new profile to the user though)

**Comment by jvillalobos** [comment]
Revised:

> When you use this email address to log in again to addons.mozilla.org, your profile on Firefox Add-ons will not have access to any of its previous content.

**Comment by AlexandraMoga** [comment]
@eviljeff I can see the new message copy on account deletions, but the frontend is currently preventing developers with published addons from deleting their accounts, i.e the Delete button is disabled. 

![image](https://user-images.githubusercontent.com/31961530/85408900-ccc8dd00-b56d-11ea-961a-8b412ef0b90b.png)

**Comment by eviljeff** [comment]
@AlexandraMoga #9479

**Comment by AlexandraMoga** [comment]
The 'Delete My Profile' button is no longer disabled for users with add-ons. 

This issue is verified fixed on -dev.
