### ISSUE TITLE
Dictionary extensions missing from developer profile pages

### ISSUE THREAD

**Issue by adakaleh** [mozilla/addons-frontend#9469]
[Dictionary extensions](https://wiki.developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/dictionaries) (used by the Firefox spellchecker) are not displaying on developer profile pages, even though they are counted under "Number of add-ons".

Example:

- https://addons.mozilla.org/en-US/firefox/user/142774/
  - https://addons.mozilla.org/en-US/firefox/addon/romanian-spellchecking-diction/

-----

By the way, [this extension](https://addons.mozilla.org/en-US/firefox/addon/romanian-spellchecking-diction/) ought to be included in the [language tools page](https://addons.mozilla.org/en-US/firefox/language-tools/).

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @willdurand 

Will, could you add a few more comments about how a contributor can fix this? :)

**Comment by Manish-Giri** [comment]
Hello, I would like to work on this, please.

**Comment by willdurand** [comment]
So we only list extensions on purpose I think. I am not sure how it would work with dictionaries because we'd need to update translations and so on. Should we consider dictionaries as extensions (something we tried to avoid in the past)? Or should we continue to not display dicts on user profiles?

**Comment by willdurand** [comment]
cc @jvillalobos

**Comment by jvillalobos** [comment]
We want to eventually group dictionaries with extensions, so if that's possible to do in the profile page, I'm okay with it. I wouldn't bother trying to create a new section for them.

**Comment by caitmuenster** [comment]
@willdurand Could you give a couple of pointers for how to fix this? Then @Manish-Giri should be able to get started on a fix. ✨

**Comment by eviljeff** [comment]
this is blocked by https://github.com/mozilla/addons-server/issues/14997 (not really a good first bug)

**Comment by willdurand** [comment]
The frontend issue is quite involved too.

**Comment by eviljeff** [comment]
unblocked by mozilla/addons-server#14997 ... because I forgot I implemented it already 2 years ago.

**Comment by Aakash2408** [comment]
I can do this but @willdurand  @eviljeff  can you give some points/hints which tells how to fix this?

**Comment by Yrkan** [comment]
I wanted to request this but i found this issue. @Aakash2408  are you still working on it ?
I'll send a PR with the changes i did in case @Aakash2408 isn't working on it.
