### ISSUE TITLE
[RTL] "Close" link from about:addons add-on installation error-message is in the wrong side

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#947]
Copied verbatim from: https://github.com/mozilla/addons-server/issues/3296

Steps to reproduce:

1. Change the browser language to RTL 
2. Set the about:addons for AMO-dev
3. Try to install an add-on

Expected results:
An error message is displayed together with a "Close" link.

Actual results:
The "Close" link is on the wrong side.

Notes/Issues:
Verified on FF48.0.1 AR- build (Win 7 x64, Mac OS 10.10.4). Issue is reproducing in dev and stage. (or production if add-on cannot be installed)
Screenshot for this issue: 
![close](https://cloud.githubusercontent.com/assets/15685960/17803185/8234d8a2-65fd-11e6-9bdf-27fe0e937881.png)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF48 - AR Build (Win 7 x64)
Postfix screenshot: 
![close](https://cloud.githubusercontent.com/assets/15685960/17883724/d3d54bd4-691c-11e6-8809-b5314ea345fd.png)
