### ISSUE TITLE
Hide stats dashboard link for dictionaries

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9471]
See: https://github.com/mozilla/addons-server/issues/14533

---

We're going to temporarily remove the stats dashboard for dictionaries.

**Comment by ioanarusiczki** [comment]
@willdurand 
Usage Statistics section with "Visit stats dashboard" link is no longer available on the detail page of a dictionary for a developer or the admin.
Verified on AMO dev with FF76(Win10).
