### ISSUE TITLE
Use the term "Downloads" instead of "Users" for dictionaries and langpacks

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9472]
See: https://github.com/mozilla/addons-server/issues/14533

---

We will use the download stats to compute the `addon.average_daily_users` on the server so let's change the title from `Users` to `Download` on a detail page of a dictionary or langpack. This change should also be visible in search results.

**Comment by ioanarusiczki** [comment]
@willdurand Verified on AMO dev with FF76(win10). 

detail page

![Downloads](https://user-images.githubusercontent.com/33448286/85011595-6a856c00-b16a-11ea-954a-96886c7a8b41.png)

search results
![search results](https://user-images.githubusercontent.com/33448286/85011934-ef708580-b16a-11ea-9515-44a322607de7.png)
