### ISSUE TITLE
Addon detail page 404s at page refresh for users who deleted their accounts on FxA

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9490]
Follow up for #9482 

### Describe the problem and steps to reproduce it:
1. Log in to AMO stage
2. Open an add-on detail page
3. In a separate tab, open the FxA account management page
4. Delete your account from FxA
5. Go back to AMO and refresh the tab where the add-on detail page was opened

### What happened?
You receive a 404 for the add-on detail page

### What did you expect to happen?
The add-on detail page is loaded

### Anything else we should know?
- the error will also reproduce when trying to reload an reviews page
- as far as I can tell, the error happens because the frontend-auth cookie was force deleted

![2020-07-01_12-37-54](https://user-images.githubusercontent.com/31961530/86229490-77598500-bb98-11ea-96f2-d67685dfa0ee.gif)

**Comment by willdurand** [comment]
Is the page public? What happens if you refresh again?

**Comment by AlexandraMoga** [comment]
@willdurand yes, the page is public and If I refresh the error will persist

**Comment by willdurand** [comment]
@AlexandraMoga could you tell me which cookies are present?

**Comment by AlexandraMoga** [comment]
@willdurand I can see the `frontend_auth_token` and `sessionid` cookies in Storage:

![image](https://user-images.githubusercontent.com/31961530/86232855-3d3eb200-bb9d-11ea-92cd-17f7d60f99cf.png)

**Comment by willdurand** [comment]
> @willdurand I can see the `frontend_auth_token` and `sessionid` cookies in Storage:

is there any value for the `frontend_auth_token` cookie?

**Comment by AlexandraMoga** [comment]
Yes, the cookie has a value

**Comment by willdurand** [comment]
> Yes, the cookie has a value

Can you give me all the details of this cookie (you can cut the first 5-10 of its value)?

**Comment by AlexandraMoga** [comment]
Add-on detail pages can be loaded now without errors.
I'm marking the issue as verified fixed on -stage.
