### ISSUE TITLE
"Profile photo" can be deleted if "Profile" fields are selected and "Enter" is pressed in "Edit my profile"

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/addons-frontend#9493]
### Describe the problem and steps to reproduce it:
1. Log in and successfully upload a "Profile photo" through "Edit my profile".
2. Click on "Edit my profile" again and write something in any of the fields from the "Profile" section.
3. Press "Enter" and observe the page.

### What happened?
The user is asked whether to confirm or cancel deleting the "Profile photo".

### What did you expect to happen?
User profile is updated, if mandatory fields are filled up. If mandatory fields are not filled up, nothing should happen. 

### Anything else we should know?
Reproduced on all Amo servers.
Reproduced also if the "Profile" fields are selected and no text is written, before pressing "Enter".
If "Enter" is pressed two times, the "Profile photo" is deleted.
Not reproduced if there is no "Profile photo" or if the "Profile photo" is uploaded at the same time with the other updates. 

![9](https://user-images.githubusercontent.com/54401091/86248676-df1ec880-bbb6-11ea-99de-952f2bfcb666.gif)

**Comment by karthikshetty03** [comment]
I would like to work on this issue

**Comment by caitmuenster** [comment]
Hi @karthikshetty03, thanks for your interest! We recommend that you get started with an issue labeled `contrib: good first bug.` You can find a list of those [here](https://github.com/mozilla/addons-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22contrib%3A+good+first+bug%22). We try to triage new bugs every two weeks, so if there aren't any to work on at the moment, wait another week or so and check again. :)

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:

![mS8Lwp9jSS](https://user-images.githubusercontent.com/31961530/104923057-33976300-59a4-11eb-8d00-b45edada0b2c.gif)

Keyboard navigation in Edit my Profile is working as expected.
