### ISSUE TITLE
Log in fails if a user registers a new account after having deleted a previous account from FxA

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9495]
Prerequisites: `fxa-account-delete` waffle is enabled

### Describe the problem and steps to reproduce it:
1. Log in to AMO stage
2. Open the Firefox account management page in a separate tab
3. Delete your account from FxA
4. Switch back to the AMO tab and refresh the page - make sure that you've been logged out
5. Log in again with the same email or a new email address - this will trigger the account registration again
6. Complete the registration process and notice your login state on AMO once done

### What happened?
You are not being logged in automatically when you register a new user after having deleted your account from FxA
### What did you expect to happen?
You should be logged in automatically when you register a new user

### Anything else we should know?
- you will be signed in only at the second Login attempt
- if I'm starting the new registration process from DevHub for example, I'm being logged in on the first attempt; apparently the issue reproduces only if I'm beginning the new registration from a frontend page

This video captures the new registration process right after the FxA verification code is confirmed and the redirection to AMO occurs:
![2020-07-02_10-47-16](https://user-images.githubusercontent.com/31961530/86335875-bd295280-bc57-11ea-9768-8ae2f2f36569.gif)

**Comment by willdurand** [comment]
This seems to be a problem with the session cookie. I feel like deleting the session cookie (in addition to the auth cookie) would fix this issue.

**Comment by willdurand** [comment]
@AlexandraMoga I fixed the issue in -dev but I am not sure we can fully reproduce the issue in -dev

**Comment by AlexandraMoga** [comment]
I couldn't find a way to reproduce this on -dev either, so, unfortunately, we'll have to wait until the code lands on stage to verify this fix.

**Comment by willdurand** [comment]
@AlexandraMoga hey, I just deployed tag `2020.07.06` in stage, which is based on last week's tag + the fix for this issue.

**Comment by AlexandraMoga** [comment]
@willdurand I'm not reproducing this issue on stage anymore, so it looks like the fix worked. 

I'm marking the issue is verified fixed on -dev.
