### ISSUE TITLE
Switch from node-sass to dart-sass

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9501]
I noticed in the [release notes](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#900-2020-07-02) for `sass-loader` that is is strongly suggested we use `dart-sass` (which is the same as the default `sass` package on npm) instead of `node-sass`, which we are currently using.

**Comment by bobsilverberg** [comment]
It turns out this isn't as simple as just switching out `node-sass` for `sass`, as we are getting some compilation errors after making that switch.

It seems we are encountering a similar problem to that described at https://github.com/sass/dart-sass/issues/898, but I'm having trouble coming up with a solution that works with our `breakpoints`. I did discover that simply removing `only` from each of the breakpoints solves the problem, but I'm not sure if that is a viable solution. It might be, as part of the description for `only` says "The only keyword prevents older browsers that do not support media queries with media features from applying the given styles. It has no effect on modern browsers."

@willdurand WDYT?

**Comment by willdurand** [comment]
> It turns out this isn't as simple as just switching out `node-sass` for `sass`, as we are getting some compilation errors after making that switch.
> 
> It seems we are encountering a similar problem to that described at [sass/dart-sass#898](https://github.com/sass/dart-sass/issues/898), but I'm having trouble coming up with a solution that works with our `breakpoints`. I did discover that simply removing `only` from each of the breakpoints solves the problem, but I'm not sure if that is a viable solution. It might be, as part of the description for `only` says "The only keyword prevents older browsers that do not support media queries with media features from applying the given styles. It has no effect on modern browsers."
> 
> @willdurand WDYT?

Given that there is an issue in LibSass too, that `dart-sass` is clearly not a drop-in replacement for `node-sass`, I'd keep `node-sass` for now, which is both working fine and maintained. We could follow the `dart-sass` and `libsass` issues and work on this issue when things get better, no?

**Comment by bobsilverberg** [comment]
> > It turns out this isn't as simple as just switching out `node-sass` for `sass`, as we are getting some compilation errors after making that switch.
> > It seems we are encountering a similar problem to that described at [sass/dart-sass#898](https://github.com/sass/dart-sass/issues/898), but I'm having trouble coming up with a solution that works with our `breakpoints`. I did discover that simply removing `only` from each of the breakpoints solves the problem, but I'm not sure if that is a viable solution. It might be, as part of the description for `only` says "The only keyword prevents older browsers that do not support media queries with media features from applying the given styles. It has no effect on modern browsers."
> > @willdurand WDYT?
> 
> Given that there is an issue in LibSass too, that `dart-sass` is clearly not a drop-in replacement for `node-sass`, I'd keep `node-sass` for now, which is both working fine and maintained. We could follow the `dart-sass` and `libsass` issues and work on this issue when things get better, no?

Sure, that makes sense. I probably wouldn't have even opened this if I knew it wasn't going to be a drop-in replacement. I didn't realize that until I started trying to get it to work.

**Comment by willdurand** [comment]
> I didn't realize that until I started trying to get it to work.

Yeah, that's what other folks said in one of the issues too.. Not sure why this lib would be the recommended one now.

**Comment by muffinresearch** [comment]
FWIW I found node-sass is quite a bit faster than dart-sass when running compilation timings for extension workshop. That's even after taking into account the notes about `sync` vs `async` and using `Fiber`.[1]

[1] https://sass-lang.com/dart-sass
