### ISSUE TITLE
Create new badges for promoted add-ons

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9503]
We will need 3 new badges:
- One for Verified Tier 1
- One for Verified Tier 2
- One for Line

Samples can be found at https://docs.google.com/drawings/d/141R80FYZve9rHq3-1oSopUPnMUTPsMgUhj0QNs3d8VI/edit

For QA:

None of the three new badges will appear anywhere on the site yet, but the existing Recommended badge and icon have been replaced to use the new code, so verifying no regressions with those would be great.

**Comment by AlexandraMoga** [comment]
I've looked at the Recommended badges on -dev and, apart from the decision of making all the badges text center aligned, there are no other differences:

[small badge - search results]
![image](https://user-images.githubusercontent.com/31961530/87424279-5b1c0600-c5e4-11ea-8cfd-c6be8d4b4b7c.png)

[large badge - addon listing]
![image](https://user-images.githubusercontent.com/31961530/87424024-f2cd2480-c5e3-11ea-8726-69d15f00eab3.png)

[icon in search suggestion]
![image](https://user-images.githubusercontent.com/31961530/87424043-fa8cc900-c5e3-11ea-85e0-6696514fc823.png)

I'm marking the issue as verified fixed.
