### ISSUE TITLE
Adjust the logic for the Recommended badge to work with other categories

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9504]
Depends on https://github.com/mozilla/addons-server/issues/14923

Once the other promotional categories exist for add-ons, adjust the logic that displays Recommended badges to be able to display the appropriate badge for the category. This will include a specific tooltip and link destination for each category.

**Comment by jvillalobos** [comment]
I'm adding the new proposed tooltips here:

- Recommended: "Firefox only recommends extensions that meet our standards for security and performance"
- Line: "This extension was created by the makers of Firefox"
- Verified: "This extension has been code-reviewed for safety"
- Sponsored: "This extension has been code-reviewed for safety"

/cc @caitmuenster Don't know if we should add more detail to the last two, but in that case we should update them after the public announcement.

**Comment by andreicristianpetcu** [comment]
The dependency was fixed. Also, is it related to this post, or should it be another bug for it? https://www.reddit.com/r/firefox/comments/iclh13/watch_out_guys_this_mozilla_company_might_be_a/

**Comment by caitmuenster** [comment]
Hey, thanks @andreicristianpetcu. :) No need to open another issue -- [we've got plans](https://github.com/mozilla/addons-frontend/pull/9513#issuecomment-657679230) to badge extensions developed by Firefox/Mozilla. ;)

**Comment by bobsilverberg** [comment]
> I'm adding the new proposed tooltips here:
> 
>     * Recommended: "Firefox only recommends extensions that meet our standards for security and performance"
> 
>     * Line: "This extension was created by the makers of Firefox"
> 
>     * Verified: "This extension has been code-reviewed for safety"
> 
>     * Sponsored: "This extension has been code-reviewed for safety"
> 
> 
> /cc @caitmuenster Don't know if we should add more detail to the last two, but in that case we should update them after the public announcement.

@jvillalobos Do we have updated links for the destination URL for the Line and Verified badges? The recommended badge links to https://support.mozilla.org/kb/recommended-extensions-program. It also sounds like maybe the tooltip for Verified was going to be updated since your last comment.

**Comment by caitmuenster** [comment]
Hey @bobsilverberg, we don't have a set URL for the SUMO article yet (I was going to wait until we were closer to turning this on). I'm going to ask for the URL https://support.mozilla.org/kb/promoted-addons-program when we create the article. Can you use that as a placeholder and then we can update if necessary?

**Comment by jvillalobos** [comment]
Small tweak for the link:

https://support.mozilla.org/kb/promoted-addons-program?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=promoted-addon-badge

All badges should link to it, including Recommended.

The tooltip for Verified can stay as-is.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos and @caitmuenster. I have opened https://github.com/mozilla/addons-frontend/issues/9622 to track updating the link.

**Comment by AlexandraMoga** [comment]
The new promoted badges are being displayed on the site as follows:

[1] - Detail page:
![image](https://user-images.githubusercontent.com/31961530/93197435-4d097380-f754-11ea-980c-ad822a5bff8b.png)
![image](https://user-images.githubusercontent.com/31961530/93197724-a7a2cf80-f754-11ea-996c-722322f29f19.png)


[2] - Search results (+tooltip):
![image](https://user-images.githubusercontent.com/31961530/93198150-42031300-f755-11ea-9c79-9c3a1fbbc3aa.png)
![image](https://user-images.githubusercontent.com/31961530/93197235-12074000-f754-11ea-9710-896be4446ea9.png)
![image](https://user-images.githubusercontent.com/31961530/93197299-1f242f00-f754-11ea-9682-14af8fc01c4f.png)


[3] - Autocomplete:
![image](https://user-images.githubusercontent.com/31961530/93197319-277c6a00-f754-11ea-9776-49a04d8bec71.png)

[4] - Android:
![image](https://user-images.githubusercontent.com/31961530/93197349-3105d200-f754-11ea-8484-5f983d0d34a8.png)
![image](https://user-images.githubusercontent.com/31961530/93197564-79bd8b00-f754-11ea-9ea7-5ddc94a2414c.png)


The _Verified_ badge is displayed for add-ons belonging both to the Verified and Sponsored groups.
Each badge will display a tooltip on hover with the message defined in https://github.com/mozilla/addons-frontend/issues/9504#issuecomment-670174426

I'm marking this issue as verified fixed on -dev.
