### ISSUE TITLE
Adjust the logic for the non-recommended warning to deal with other categories

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9505]
Depends on https://github.com/mozilla/addons-server/issues/14923

Once the other promotional categories exist for add-ons, adjust the logic that displays non-recommended warning to hide it when appropriate.

Specifically, any promoted add-on should have the warning suppressed, except for those in the "Strategic" category.

**Comment by andreicristianpetcu** [comment]
The dependency was fixed. Also, is it related to this post, or should it be another bug for it? https://www.reddit.com/r/firefox/comments/iclh13/watch_out_guys_this_mozilla_company_might_be_a/

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified the issue on AMO dev - FF80(Win10). 

- all categories except for Strategic, won't show the warning.
https://addons-dev.allizom.org/en-US/firefox/addon/more-optional-permissions/

![no warning](https://user-images.githubusercontent.com/33448286/93331444-e99d4580-f828-11ea-9662-83ae109bedef.png)

- Strategic addon displays the warning message.
https://addons-dev.allizom.org/en-US/firefox/addon/a-test-for-promoted-addons/

![strategic](https://user-images.githubusercontent.com/33448286/93331490-08034100-f829-11ea-9410-a8bcb36cebbb.png)
