### ISSUE TITLE
Create a home page shelf for promoted add-ons

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9506]
As per the PRD at https://docs.google.com/document/d/1dm6d8pBvUVP4sTAQcg5WvXu10NGZJtbOzPU9eyb0AH4/edit#, add a shelf between the Primary and Secondary hero which displays promoted add-ons.

Some specs:
- The cards are larger than regular shelves, showing three horizontally, instead of four.
- The shelf will support two rows of cards.
- If there are cards to show, the shelf should appear. If there are 3 cards or fewer, show only one line of cards.
- Impressions and clicks of add-ons shown in this section must be recorded in Google Analytics.
- This shelf must have a “What is this” link pointing to SUMO documentation on Sponsored add-ons.

**Comment by bobsilverberg** [comment]
I've started working on this. Here is what I have so far, which I think pretty closely resembles the example in the PRD. What do you think, @jvillalobos?

<img width="1105" alt="Screenshot 2020-07-13 15 18 08" src="https://user-images.githubusercontent.com/142755/87344518-9bb04c80-c51c-11ea-9f82-940d7c659414.png">

**Comment by jvillalobos** [comment]
Let's try the following:

- Text for add-on names about 20% larger.
- Text for "What is this" link about 25% smaller. Also change the label to "What is this?", with the question mark.

Thanks!

**Comment by bobsilverberg** [comment]
Thanks for the feedback, @jvillalobos. For the changes you suggested, I used the standard font sizes we have defined for the app. Before each was `14px`, which is `$font-size-default`. I changed the add-on names to use `$font-size-m`, which is `16px`, and I changed the "What is this?" link to use `$font-size-s`, which is `12px`. I'm attaching a screenshot from Storybook. Please let me know is this looks good, or if you think we need to vary from the standard sizes already defined in the app for these elements.

![Screenshot 2020-07-13 16 57 38](https://user-images.githubusercontent.com/142755/87352988-f8663400-c529-11ea-9617-1ee9853000f6.png)

**Comment by jvillalobos** [comment]
Yes, I think we need to vary from the pre-defined sizes. I don't think we need the link to be too prominent, and we should also make the sponsored extensions stand out more. Part of the reason there are only three across the shelf is so that they can be larger without impacting layout.

**Comment by bobsilverberg** [comment]
> Yes, I think we need to vary from the pre-defined sizes. I don't think we need the link to be too prominent, and we should also make the sponsored extensions stand out more. Part of the reason there are only three across the shelf is so that they can be larger without impacting layout.

I bumped the add-on name to 18px and reduced the link to 10px. Please let me know what you think:

<img width="1139" alt="Screenshot 2020-07-14 08 03 27" src="https://user-images.githubusercontent.com/142755/87423610-90a2fe00-c5a8-11ea-92d6-3bddcda0a3de.png">

**Comment by willdurand** [comment]
We aren't very Photon-compliant when it comes to font-sizes. I think it would time for us to look at what we should update to match the Photon specs and then see which font-sizes we could use for this new shelf. We have quite a lot of various font-sizes already and adding new ones isn't going to help :/

**Comment by bobsilverberg** [comment]
> We aren't very Photon-compliant when it comes to font-sizes. I think it would time for us to look at what we should update to match the Photon specs and then see which font-sizes we could use for this new shelf. We have quite a lot of various font-sizes already and adding new ones isn't going to help :/

That's why I asked the question. If we're going to re-evaluate font sizes across the site, I think that's something that UX should be involved in. Do we know if they are able to devote some time to helping us with that?

**Comment by jvillalobos** [comment]
> I bumped the add-on name to 18px and reduced the link to 10px. Please let me know what you think

The modified sizes look good to me, thanks.

> If we're going to re-evaluate font sizes across the site, I think that's something that UX should be involved in. Do we know if they are able to devote some time to helping us with that?

Aaron is aware of the changes we're introducing and is as involved as his time allows. Unfortunately that's not a lot, so we have to take the initiative whenever possible. [Maybe this scaling guide](https://design.firefox.com/photon/visuals/typography.html) can help decide which sizes to use here. However, let's keep in mind that AMO is a fairly unique site in the Mozilla web universe and not all guidelines will apply to it.

**Comment by bobsilverberg** [comment]
Thanks for the link to that, @jvillalobos. I can use sizes from that photon scaling guide for these new elements. I think @willdurand was suggesting that we should change all of our default sizes on the site to match these as well. What do you think about that?  We'd probably need to replace a bunch of custom sizes as well, but I believe we mostly use the default sizes, so it wouldn't be a huge amount of work.

**Comment by bobsilverberg** [comment]
I adjusted the fonts to match the photon scaling specs. I made the link consistent with "Caption 10" (11px, 400 weight), and the add-on name consistent with "Title 20" (17px, 500 weight):

![Screenshot 2020-07-15 09 53 56](https://user-images.githubusercontent.com/142755/87553618-214d0d00-c681-11ea-93f7-0f35f7443c7e.png)

**Comment by bobsilverberg** [comment]
One thing to note: In addition to Photon, there is also Protocol, which I believe is newer. The specs for font sizes for Protocol (https://protocol.mozilla.org/fundamentals/typography.html) are different from the specs for font sizes for Photon. The former are closer to what we're using now, whereas the Photon ones are different (using mostly odd px sizes). 

Stuart also pointed out that our default font sizes for AMO seem to be smaller than a lot of other sites, and hence could benefit from a change.

As mentioned above, I don't think making this change would be a lot of work, but we definitely need to figure out which spec, if any, we want to adhere to.

**Comment by jvillalobos** [comment]
>I adjusted the fonts to match the photon scaling specs

Let's use the sizing in this last mockup for now. I'll ask Aaron about Protocol and Photon to see which one we should be following and we'll figure out where to go from there.

**Comment by willdurand** [comment]
> I bumped the add-on name to 18px and reduced the link to 10px. Please let me know what you think:

Sorry, my previous comment about Photon specs was more about updating all font-sizes in case we'd want to use new font sizes specifically for this new shelf (and not just cherry-pick one or two font sizes in the Photon spec only).

It turns out that 18px and 10px are font sizes we're already using in addons-frontend and @jvillalobos was ok with them, so I feel like we should use 18px/10px instead of 17px/11px.

Ideally we'd still want to be Photon compliant eventually but... it's unrelated to this issue.

**Comment by bobsilverberg** [comment]
Thanks @willdurand. We're back to 18/10.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Perhaps the qa not needed label has been added and then forgotten by mistake?

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. I added qa: not needed before because this didn't actually show up anywhere, but as of this week it's available on dev, so it would be great if it could be verified. A flag will prevent it from appearing on stage and prod for another week or two.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev - FF80(Win10).

**Test results:** 

**the way they show up**:
- I have 9 sponsored add-ons (compatible on All Applications) on [AMO dev](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=2). If I make one to be "not promoted", the frontend result is only one shelf with 3 add-ons.

![one shelf](https://user-images.githubusercontent.com/33448286/93770312-b2fa6d00-fc24-11ea-94b4-42e68a3fdd81.png)


- the page refresh is going to show the same add-ons on shelves.
- when there are no sponsored add-ons, the title of the shelf and the blue link are displayed but no addon is available. Perhaps all the components of the shelf should be gone?

**the layout**:

- the alignment to the left -> it's too much empty space to the right, I don't know if that's expected:
![alignmnent](https://user-images.githubusercontent.com/33448286/93768048-7bd68c80-fc21-11ea-9b8e-6e69304e56df.png)

- [font-size](https://github.com/mozilla/addons-frontend/issues/9506#issuecomment-659358490): is 10 px for "What is this" and 14px for the cards which is the same as for the add-ons from the other shelves on the homepage. Let me know if I should file an issue.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I verified on AMO dev - FF80(Win10).
> 
> **Test results:**
> 
> **the way they show up**:
> 
> * I have 9 sponsored add-ons (compatible on All Applications) on [AMO dev](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=2). If I make one to be "not promoted", the frontend result is only one shelf with 3 add-ons.
> 

I'm not sure I understand what you're saying here. If there are at least 6 sponsored add-ons, then the shelf should show 6 add-ons. It should only show 3 add-ons if there are less that 6 sponsored add-ons. Are you saying that there are 8 sponsored add-ons and yet the shelf is only showing 3?

> 
> ![one shelf](https://user-images.githubusercontent.com/33448286/93770312-b2fa6d00-fc24-11ea-94b4-42e68a3fdd81.png)
> 
> * the page refresh is going to show the same add-ons on shelves.

I don't understand this one either. If you refresh, or even leave the home page and then return to the home page, the API call is made again and the shelf will contain a new set of add-ons. There's always the chance the add-ons will be the same, especially if there are a small number of sponsored add-ons, but the code is in place to refresh the shelf.

> 
> * when there are no sponsored add-ons, the title of the shelf and the blue link are displayed but no addon is available. Perhaps all the components of the shelf should be gone?
>

The issue here is with the loading skeleton. If we make the shelf disappear entirely then the whole layout of the page shifts after the API responses come back, which we're trying to avoid. I believe the approach here is to always have at least 3 sponsored add-ons as long as the shelf is being enabled to appear on the home page, and that will make it impossible for the shelf to be empty.

@jvillalobos Can you please confirm that that is the approach we want to take?

> 
> **the layout**:
> 
> * the alignment to the left -> it's too much empty space to the right, I don't know if that's expected:
> ![alignmnent](https://user-images.githubusercontent.com/33448286/93768048-7bd68c80-fc21-11ea-9b8e-6e69304e56df.png)
> 

I agree this looks possibly a bit off, but I'm not sure what, if anything we can/want to do about it. It's partially due to the short add-on names of the sample add-ons and would be less of an issue if the names were longer.

@jvillalobos and/or @aaronrbenson what do you think?

> * [font-size](https://github.com/mozilla/addons-frontend/issues/9506#issuecomment-659358490): is 10 px for "What is this" and 14px for the cards which is the same as for the add-ons from the other shelves on the homepage. Let me know if I should file an issue.

That is as expected and seems fine.

**Comment by jvillalobos** [comment]
> I believe the approach here is to always have at least 3 sponsored add-ons as long as the shelf is being enabled to appear on the home page, and that will make it impossible for the shelf to be empty.

While that's what we expect to happen operationally, we should be prepared for any errors. In the future the list of add-ons to show will be handled by a third party tool, and that increases the risk of failure here. If there are no add-ons to show in the shelf, the entire shelf should not be shown.

> I agree this looks possibly a bit off, but I'm not sure what, if anything we can/want to do about it.

Yeah, I think this is okay. We want to refine the layout in the future, so we shouldn't spend too much time on this.

**Comment by bobsilverberg** [comment]
> > I believe the approach here is to always have at least 3 sponsored add-ons as long as the shelf is being enabled to appear on the home page, and that will make it impossible for the shelf to be empty.
> 
> While that's what we expect to happen operationally, we should be prepared for any errors. In the future the list of add-ons to show will be handled by a third party tool, and that increases the risk of failure here. If there are no add-ons to show in the shelf, the entire shelf should not be shown.
> 

Ok, I opened https://github.com/mozilla/addons-frontend/issues/9675.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
-  I also expected to see some new add-ons displayed. For a number of 12 add-ons I keep seeing the same order no matter how many times I refresh the page. I even opened a different profile but I see the same add-ons in the same order.

![refreshing page1](https://user-images.githubusercontent.com/33448286/93864600-d0374600-fccd-11ea-97a7-68529ae0ebbd.gif)

- for a number of 6 promoted add-ons I see only one shelf (3 are displayed). The same for 8. I need 9 to see the 2 rows. I filed https://github.com/mozilla/addons-frontend/issues/9678

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> * I also expected to see some new add-ons displayed. For a number of 12 add-ons I keep seeing the same order no matter how many times I refresh the page. I even opened a different profile but I see the same add-ons in the same order.
> 
> 
> ![refreshing page1](https://user-images.githubusercontent.com/33448286/93864600-d0374600-fccd-11ea-97a7-68529ae0ebbd.gif)
> 

@eviljeff Is there any reason we should expect the same add-ons to be returned in the same order for this API request:

https://addons-dev.allizom.org/api/v4/addons/search/?app=firefox&appversion=81.0&page_size=6&promoted=sponsored&sort=random&type=extension&lang=en-US&wrap_outgoing_links=true

**Comment by bobsilverberg** [comment]
Thanks for the clarifications, @ioanarusiczki! I've asked a question of Andrew here, and commented on the new issue you opened.

**Comment by eviljeff** [comment]
> @eviljeff Is there any reason we should expect the same add-ons to be returned in the same order for this API request:
> 
> https://addons-dev.allizom.org/api/v4/addons/search/?app=firefox&appversion=81.0&page_size=6&promoted=sponsored&sort=random&type=extension&lang=en-US&wrap_outgoing_links=true

there's a random seed set based on the current date so the "random"-ness will be consistent for queries on a given day.

**Comment by bobsilverberg** [comment]
> > @eviljeff Is there any reason we should expect the same add-ons to be returned in the same order for this API request:
> > [addons-dev.allizom.org/api/v4/addons/search/?app=firefox&appversion=81.0&page_size=6&promoted=sponsored&sort=random&type=extension&lang=en-US&wrap_outgoing_links=true](https://addons-dev.allizom.org/api/v4/addons/search/?app=firefox&appversion=81.0&page_size=6&promoted=sponsored&sort=random&type=extension&lang=en-US&wrap_outgoing_links=true)
> 
> there's a random seed set based on the current date so the "random"-ness will be consistent for queries on a given day.

Thanks for the explanation @eviljeff!

@jvillalobos Are we okay with that? That will have the same effect on the "Recommended Extensions" and "Recommended Themes" shelves, which I'm not sure we even noticed before.

**Comment by eviljeff** [comment]
it's not a new feature - it's how `?sort=random` has worked since #13574 (the pr was reviewed by a certain @bobsilverberg 😉)

**Comment by bobsilverberg** [comment]
I forgot all about that!

**Comment by jvillalobos** [comment]
Since we only plan to have 6 add-ons during the pilot, I don't think the randomness will matter much. After that we'll probably be using Adzerk as the data source so it won't matter either.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I also forgot about https://github.com/mozilla/addons-server/issues/13574

Based on all comments above - I'm marking this verified on AMO dev - FF80(Win10).
