### ISSUE TITLE
Remove pinning of isort when possible

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9508]
We had to add a pinning of `isort` to `tests/ui/requirements/flake8.txt` in order to fix a build failure, but we should be able to remove it once https://github.com/gforcada/flake8-isort/pull/89 lands and a new version is released.

**Comment by willdurand** [comment]
Looks like the upstream lib was fixed last night: https://github.com/gforcada/flake8-isort/pull/89
