### ISSUE TITLE
Make the Delete button in the Edit profile page red

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9515]
The "Delete My Profile" button in the Edit Profile page is light grey and it appears to be confusing some users when they are creating their account for the first time. We should make this button red like other Delete buttons to make it clear what it's for.

**Comment by AlexandraMoga** [comment]
This is verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/87405845-a45e5c80-c5c8-11ea-91c3-ef8c38429fd7.png)
