### ISSUE TITLE
Add the Promoted add-ons shelf to the home page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9518]
Depends on https://github.com/mozilla/addons-server/issues/14923

The component for the new Promoted Add-ons shelf will land in #9517, but it doesn't appear anywhere. This issue is about adding the shelf to the home page.

From the PRD:
- Impressions and clicks of add-ons shown in this section must be recorded in Google Analytics.

**Comment by bobsilverberg** [comment]
@jvillalobos All of the add-ons shown on shelves in the home page have an `addonInstallSource` of `featured`, except for those on shelves that are powered by a collection, which have an `addonInstallSource` of `homepage-collection-featured`. Should we continue to use `featured` for the Sponsored shelf, or do we want to introduce a new source?

**Comment by jvillalobos** [comment]
We'll need a new one. Let's go with `homepage-sponsored-shelf`.

**Comment by bobsilverberg** [comment]
We don't currently display the primary and secondary hero on the `/android` site. This shelf appears between the two. Do we want this new shelf to appear on the `/android` site?

**Comment by bobsilverberg** [comment]
@jvillalobos We don't currently display the primary and secondary hero on the `/android` site. This shelf appears between the two. Do we want this new shelf to appear on the `/android` site?

**Comment by jvillalobos** [comment]
No, the shelf is desktop-only.

**Comment by ioanarusiczki** [comment]
@bobsilverberg GA events are registered when an addon from the shelf is clicked. 

![google collect](https://user-images.githubusercontent.com/33448286/93432824-b9a87d80-f8ce-11ea-836c-9cac2dba9b5c.gif)

Verified on dev - FF80(Win10).
