### ISSUE TITLE
Enhance `SearchResult` to allow for recording of impressions and clicks

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9519]
#9518 requires that all impressions and clicks of promoted add-ons in the Promoted Add-Ons shelf be recorded via Google Analytics. As this shelf component uses the `SearchResult` component to display the individual add-ons, that component needs to be updated to allow extra behaviour added for impressions and clicks.

**Comment by ioanarusiczki** [comment]
@bobsilverberg If qa can check this, please let me know what I should be looking for.
Thanks!

**Comment by bobsilverberg** [comment]
> @bobsilverberg If qa can check this, please let me know what I should be looking for.
> Thanks!

Oops, sorry @ioanarusiczki. This does not add any testable behaviour, but it is a change to the `SearchResult` component, so we should check for regressions. This component is used on the Search Results page, as well as any page that shows a list of add-ons (e.g., the home page, the profile page, etc.).

Thanks!

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO stage:
- the see more links which use search results use the same parameters as before. 
- search in general worked for me.
- visually I don't see issues when a list of add-ons is shown.
