### ISSUE TITLE
Change fonts for Promoted shelf to match other shelves

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9533]
This is a follow-up to https://github.com/mozilla/addons-frontend/pull/9517. After discussing in the Add-ons Front End Review meeting, it was decided to use the same fonts for the new Sponsored shelf as is being used for the existing shelves on the home page, as opposed to the unique fonts used in #9517.

One question for @jvillalobos: As the "What is this?" link is unique to this shelf, do we want to keep the smaller font that we are currently using for that, and only revert the fonts for the add-on names?

**Comment by jvillalobos** [comment]
Yes, let's keep that link small, since it serves a different purpose than the others.
