### ISSUE TITLE
Update/Fix the promoted badges

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9534]
This is a follow-up to https://github.com/mozilla/addons-frontend/pull/9513. There are a couple of changes required for the new badges:

1. Make the label one shade darker for the green and grey badges.
2. The icon doesn't seem to change colour on hover, the way the outline does. That should be fixed.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I only see the `recommended` badges being available (as they were before). 
The add-ons added in the [list of promoted add-ons](https://addons-internal.dev.mozaws.net/en-US/admin/models/promoted/promotedaddon/) from admin don't show badges on the detail pages yet.

If I did not understand the issue then please add some STR. 
Thanks!

**Comment by bobsilverberg** [comment]
Sorry, @ioanarusiczki, I should have marked this as `qa: not needed`.
