### ISSUE TITLE
Display optional permissions

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9542]
~~Depends on https://github.com/mozilla/addons-server/issues/15036~~

PRD: https://docs.google.com/document/d/1px08vsGEbI3dggO8xj-6CVAJsh1MAk9IFROBfv3mT6Y/edit?usp=sharing

The PRD does not contain any UX specs, but assuming these will just be displayed in a similar manner to how required permissions are currently displayed.

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

Optional permissions are displayed inside the Permissions card only for add-on that do have optional permissions defined:

https://addons-dev.allizom.org/en-US/firefox/addon/perms-and-optional-perms/
![image](https://user-images.githubusercontent.com/31961530/89034107-faf5c580-d340-11ea-9401-1185e27d11a6.png)
