### ISSUE TITLE
The bottom of the permissions box (when fully expanded) does not have rounded corners

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9551]
Before expanding:

<img width="487" alt="Screenshot 2020-07-29 14 02 11" src="https://user-images.githubusercontent.com/142755/88836045-1d061100-d1a4-11ea-8517-10315f09180c.png">

After expanding:

<img width="494" alt="Screenshot 2020-07-29 14 02 44" src="https://user-images.githubusercontent.com/142755/88836092-31e2a480-d1a4-11ea-9072-0adcb95385b5.png">

**Comment by Kushagraw12** [comment]
Can I work on it?
Thanks!

**Comment by caitmuenster** [comment]
If this is your first contribution, please refer to https://wiki.mozilla.org/Add-ons/Contribute/Code on how to get started. 

Mentor: @bobsilverberg 

@Kushagraw12, go ahead and pick this one up!

**Comment by Creatoon** [comment]
hello sir , i want to work on this issue.
please guide me how can i reach this issue, if possible.

**Comment by bobsilverberg** [comment]
@Creatoon It looked like @Kushagraw12 was interested in working on this, but I'm not sure it they've started yet. 

In terms of how to get started, there is some general information available at https://wiki.mozilla.org/Add-ons/Contribute/Code. In terms of this specific issue, the code for component in question can be found at https://github.com/mozilla/addons-frontend/tree/master/src/amo/components/PermissionsCard. The fix for this will likely involve some modifications to the styles of that component, and/or a component that it uses.

**Comment by Kushagraw12** [comment]
@bobsilverberg I am working on it. @Creatoon if it is not done in another 2 days, you can take it up! 
Thanks!

**Comment by Creatoon** [comment]
@Kushagraw12 OK brother,  no problem.

**Comment by zaryanz** [comment]
It seems like Travis CI is expecting the border-bottom-left-radius line to come before the border-bottom-right-radius line if I'm interpreting this correctly. You could try swapping those lines and see if the check passes.
Thanks!
![image](https://user-images.githubusercontent.com/51870531/89874698-d7047080-dbd9-11ea-897f-8f37c2144ed9.png)

**Comment by Kushagraw12** [comment]
> It seems like Travis CI is expecting the border-bottom-left-radius line to come before the border-bottom-right-radius line if I'm interpreting this correctly. You could try swapping those lines and see if the check passes.
> Thanks!
> ![image](https://user-images.githubusercontent.com/51870531/89874698-d7047080-dbd9-11ea-897f-8f37c2144ed9.png)

Okay, I will swap the lines and update it!
Thanks!

**Comment by Aakash2408** [comment]
Hey,@kushagraw @bobsilverberg  Is this issue resolved or i can take it?
