### ISSUE TITLE
Lots of errors in the build script

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#9554]
Looking at some of the builds on CI there's lots of logs along the lines of the following:

```bash
[webpack-isomorphic-tools/plugin] [error] Module "css ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/amo/components/GetFirefoxButton/styles.scss" has no source. Maybe Webpack compilation of this module failed. Skipping this asset.

[webpack-isomorphic-tools/plugin] [error] Module "css ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/amo/components/GuidesAddonCard/styles.scss" has no source. Maybe Webpack compilation of this module failed. Skipping this asset.

[webpack-isomorphic-tools/plugin] [error] Module "css ./node_modules/css-loader/dist/cjs.js??ref--5-1!./node_modules/postcss-loader/src??ref--5-2!./node_modules/sass-loader/dist/cjs.js??ref--5-3!./src/amo/components/Header/styles.scss" has no source. Maybe Webpack compilation of this module failed. Skipping this asset.
```

Would be good to look at this. Since `webpack-isomorphic-tools` is no longer recommended,  we might want to consider taking a look at `universal-webpack`, the main difference is the latter builds a node target output instead of using `require` magic to handle the differences between client and server. Though there might be a simpler fix in the meantime.

The error message relates to https://github.com/catamphetamine/webpack-isomorphic-tools/blob/7ddfafd735f7ea46ea2510964e090af64917610a/source/plugin/write%20assets.js#L223

Since nothing appears to be broken, this might not be anything to worry about, but it would be good to understand what's going on if nothing else.

**Comment by willdurand** [comment]
See also https://github.com/mozilla/addons-frontend/issues/2377 and https://github.com/mozilla/addons-frontend/issues/6996

**Comment by muffinresearch** [comment]
Another thing that prompted this was on trying to use webpack to provide an asset pipeline for the Extension Workshop, in the end I dropped that approach because it was both brittle and too complicated (and didn't seem like it would necessarily continue to work in the future) with webpack 5. All of this made it pretty clear there will be a fair bit of change coming in webpack 5.

**Comment by gabefair** [comment]
Thanks for creating this issue

**Comment by ioanarusiczki** [comment]
@willdurand Does the issue require qa? Please add some str.
Thanks!
