### ISSUE TITLE
Clean-up UTM feature flag once it is enabled on prod

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9555]
We introduced a feature flag in https://github.com/mozilla/addons-frontend/issues/9547. Let's remove it when we fully switch to UTM parameters.

For QA: this could introduce regressions related to the UTM parameters in all pages.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me. I verified this on AMO dev with FF80(Win10), using as reference https://github.com/mozilla/addons-frontend/issues/9547
