### ISSUE TITLE
Stop passing an install source/`src` param to Addon Manager

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9556]
We're passing a `src` parameter to the Addon Manager to track attribution. This won't be needed once we switch to UTM parameters so let's remove all of that.

**Comment by AlexandraMoga** [comment]
I've verified installations on -dev for all add-on types we support and I didn't find issues. Also, the `src=dp-btn-primary` parameter is no longer passed to the install button.

@willdurand I've looked in `about:telemetry#events-tab` but, apart from the `install` events, I couldn't see any `install_stats` events. I've looked with Firefox 80.0.1 and the latest Nightly.

**Comment by willdurand** [comment]
> @willdurand I've looked in `about:telemetry#events-tab` but, apart from the `install` events, I couldn't see any `install_stats` events. I've looked with Firefox 80.0.1 and the latest Nightly.

ha, interesting. I think we should have that one, unless it only works with AMO prod.

**Comment by AlexandraMoga** [comment]
I'll have a look on prod after the push

**Comment by AlexandraMoga** [comment]
The `install_stats` event is present on prod:

	addonsManager 	install_stats 	extension  	{"addon_id": "jid1-MnnxcxisBPnSXQ@jetpack", "utm_source": "addons.mozilla.org", "utm_medium": "referral", "utm_content": "featured"}
