### ISSUE TITLE
The content of the summary is not displayed when there's no custom description

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9557]
Followup for https://github.com/mozilla/addons-server/issues/15028
This could be a frontend issue, in that case please transfer it to the right repo

STR:
1. Add to the primary hero shelf an add-on from `models/promoted/promotedaddon/212/change/` without adding anything in the description field
2. Check the frontend

Expected result:
The summary of the add-on is displayed

Actual result:
The content is not loading

Reproducible on dev - FF78(Win10). 

![description on dev](https://user-images.githubusercontent.com/33448286/89037075-8cb40180-d346-11ea-8c3e-1bf694a14d56.png)

**Comment by bobsilverberg** [comment]
We should not be showing these loading indicators for an empty `description`, so that's definitely a bug, but it also looks like the API response should be returning something other than `""` for the `description`, so I think we have bugs on both server and frontend.

**Comment by eviljeff** [comment]
I tracked it down to a condition that we only fall back to the addon.summary for extensions, and this addon was a langpack; so in the absence of a defined description for the primary hero shelf, it's returns `""`.  (it's a feature! not a bug 😜)  

Though it was logic copied from DiscoveryItem and doesn't really make sense any longer so we'll remove that condition.

**Comment by eviljeff** [comment]
Filed mozilla/addons-server#15134 to remove the extension only restriction.

**Comment by AlexandraMoga** [comment]
The loading indicators are no longer displayed for a Language pack without a custom description added in the admin:
![image](https://user-images.githubusercontent.com/31961530/89396582-67910b80-d717-11ea-9225-62bbb5cca82f.png)

If there is a custom description added for a language pack, the Primary hero will display it.

For extensions, we continue to fallback to the add-on summary if there is no custom description added in the admin.

Verified fixed on -dev
