### ISSUE TITLE
The `utm_content` parameter for addons opened from Top rated/Trending shelf search results is set to `featured`

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9565]
Follow up for #9547 

### Describe the problem and steps to reproduce it:
1. Open the Extensions landing page - https://addons-dev.allizom.org/en-US/firefox/extensions/
2. Click on an add-on from the Top rated shelf
3. Notice the `utm` parameters from the detail page URL - you should be able to see `utm_content=rating`
4. Go back to the Extensions landing page and click on the  'See more' link in the Top rated shelf
5. Click on an add-on from the [search results](https://addons-dev.allizom.org/en-US/firefox/search/?recommended=true&sort=rating&type=extension)
6. Notice again the `utm` parameters from the detail page URL 

### What happened?
The `utm_content` parameter is set to `featured`

### What did you expect to happen?
Since the search filter is set to `rating` and the shelf promotes Top rated extensions, the `utm_content` parameter should be set to `rating` as well

### Anything else we should know?
- the same steps can be applied to the Trending shelf, for which the `utm_content` parameter should be set to `hotness` instead of `featured`
- this issue is valid both for Extensions and Themes 

![2020-08-03_18-41-50](https://user-images.githubusercontent.com/31961530/89201306-f12ac700-d5b9-11ea-81a5-802fde75fdbd.gif)

**Comment by willdurand** [comment]
@jvillalobos WDYT? (it's not a new problem, QA found it because they verified the patch for the UTM params)

**Comment by jvillalobos** [comment]
I think we can wontfix this for now. We should figure out how we want these params to work internally, but it's a bigger issue than this.

**Comment by willdurand** [comment]
@jvillalobos Good, thanks! Note that if you want to tweak the UTM parameter values, it'd be useful to have the new set of params/values ahead of time. Currently (and on -dev only), we replace `src` with UTM params according to the PRD.

@AlexandraMoga UTM params will likely be updated in the future so that's why we're closing this one now.
