### ISSUE TITLE
500 Errors on nn-NO locale for 404

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#9566]
Go to https://addons.mozilla.org/nn-NO/firefox/addon/mx4/

This should be a 404 but it's a 500 due to a locale placeholder issue. This was also highlighted in Google Analytics.

**Comment by AlexandraMoga** [comment]
The following link will trigger a 404 instead of a 500 on stage:
https://addons.allizom.org/nn-NO/firefox/addon/search_/

This issue can be marked as verified fixed.
