### ISSUE TITLE
Display URL to source code repository in listing pages

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9568]
When https://github.com/mozilla/addons-server/issues/15174 is fixed, show the URL in listing pages. It can be added to the bottom of the list in the "More information" box, under "Add-on Links". The label can be "Source code".

**Comment by Aakash2408** [comment]
Can you kindly provide any images or screenshots showing the issue?

**Comment by jvillalobos** [comment]
You can see this as an example of a listing page: https://addons.mozilla.org/addon/ublock-origin/. However, note that https://github.com/mozilla/addons-server/issues/15174 needs to be fixed first.
