### ISSUE TITLE
Remove link to 'Admin add-on status' from add-on detail pages

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9578]
### Describe the problem and steps to reproduce it:
The Add-on manage admin tool has been removed in https://github.com/mozilla/addons-server/issues/15234. The frontend still exposes a link to that tool in the Admin links section present on add-on detail pages. This link should be removed. 

![image](https://user-images.githubusercontent.com/31961530/90012384-f4a20a80-dcab-11ea-92df-7a86a827ecbf.png)

**Comment by bobsilverberg** [comment]
Thanks for filing this issue, @AlexandraMoga.

@eviljeff Should we remove this link, or change it? Looking at https://github.com/mozilla/addons-server/issues/15234, it sounds like the destination of the link had an alternative.

**Comment by bobsilverberg** [comment]
Ah, I was reading my email in reverse chronological order, so I just saw @eviljeff mention that there's a replacement tool at admin/models/addons/addon/<addon-id>/change/. I gather we should update the frontend to point to that?

**Comment by AlexandraMoga** [comment]
@bobsilverberg I think the 'Admin add-on' link that is listed just below 'Admin add-on status' is already directing to `/admin/models/addons/addon/<addon_id>/change/`, so we just to remove the non-relevant link.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I think the 'Admin add-on' link that is listed just below 'Admin add-on status' is already directing to `/admin/models/addons/addon/<addon_id>/change/`, so we just need to remove the non-relevant link.

Thanks makes sense, thanks @AlexandraMoga!

**Comment by Aakash2408** [comment]
Hey @bobsilverberg ,can I take this?

**Comment by rochisha0** [comment]
Hey! Can I work on this issue?

**Comment by bobsilverberg** [comment]
@Aakash2408 asked first, so yes, you may work on this. It should be as simple as removing the link defined at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L82-L94, and also removing the tests at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L82-L94.

**Comment by Aakash2408** [comment]
> @Aakash2408 asked first, so yes, you may work on this. It should be as simple as removing the link defined at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L82-L94, and also removing the tests at https://github.com/mozilla/addons-frontend/blob/master/src/amo/components/AddonAdminLinks/index.js#L82-L94.

Ok Thanks i will do it

**Comment by Aakash2408** [comment]
Hey @bobsilverberg, when I run the yarn command to install the dependencies  then the following error, shows up
![Screenshot from 2020-08-14 21-20-13](https://user-images.githubusercontent.com/47134609/90268001-f4ed0200-de73-11ea-96d7-eb04f8aaa139.png)

**Comment by bobsilverberg** [comment]
I have never heard of that error before. Do you have all of the requirements listed at https://github.com/mozilla/addons-frontend/blob/master/README.md#requirements? Which operating system are you on?

**Comment by Aakash2408** [comment]
> I have never heard of that error before. Do you have all of the requirements listed at https://github.com/mozilla/addons-frontend/blob/master/README.md#requirements? Which operating system are you on?

Thanks for the response ,but I have figured out the problem and forked the repo will commit the changes before going to sleep

**Comment by Aakash2408** [comment]
Hey @bobsilverberg, I have made the changes kindly check and merge the pull request.
