### ISSUE TITLE
Use `promoted` from the API response in place of `is_recommended`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9579]
Now that [`promoted`](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#addon-detail-promoted-category) is part of the API response for add-ons, we should update any code that uses `is_recommended` from the API response to use `promoted` instead. For now this won't result in any changes for users, but it will prepare us to expose other categories when we need to.

**Comment by Aakash2408** [comment]
Hey, If this is not resolved yet can I take this?

**Comment by caitmuenster** [comment]
Hey @Aakash2408, thanks for your interest! This isn't a good bug for contributors. :) You will want to get started with an issue labeled '[contrib: good first bug](https://github.com/mozilla/addons-frontend/issues?q=is%3Aopen+is%3Aissue+label%3A%22contrib%3A+good+first+bug%22).'

Currently it doesn't look like there are any open good first bugs. We tend to refresh the list about every two weeks. You're welcome to pick up one of those bugs when they become available, or head over to [Codetribute](https://codetribute.mozilla.org/) for other good-first-bugs across Mozilla projects. :)

**Comment by ioanarusiczki** [comment]
@bobsilverberg I did not encounter regressions so far after looking over AMO dev/stage. I'm going to take one more look tomorrow while release testing (same for https://github.com/mozilla/addons-frontend/issues/9605 and https://github.com/mozilla/addons-frontend/issues/9609).
