### ISSUE TITLE
Need UX to show that an add-on cannot be uninstalled.

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#959]
When this bug is fixed https://bugzilla.mozilla.org/show_bug.cgi?id=1297028 we'll need to use the exposed state that defines that a globally installed add-on cannot be uninstalled and reflect that in the UI.

This will be relevant to both the discovery pane and AMO.

In a nutshell the UX question here is "how should we reflect that an add-on is not uninstallable?"

**Comment by pwalm** [comment]
We've got some mock-ups for future add-on pref pane that can address extensions like these as "uninstallable" or something similar. And we've also designed a version of the install switch that is turn on but disabled.

**Comment by pwalm** [comment]
I designed a "disabled-on" version of the switch, does that work for this?
