### ISSUE TITLE
Details page still tries to render if the API returns an error response

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#960]
If you request an add-on that doesn't exist or is in some other state the details page still tries render the add-on e.g: /en-US/firefox/addon/foo/ - this results in a 500 in the amo app.

**What happens:**

Internal Server Error

**What should happen:**

404

**Comment by kumar303** [comment]
Are you sure this happens with server side rendering turned on? I was experiencing something similar but only with SSR disabled.

**Comment by muffinresearch** [comment]
Yes 100%, what's happening is both redux-async-connect and redux-connect (which is a fork of the former) eat exceptions from the API request on the server. This means that the view tries to render data that doesn't exist which is why the 500 occurs.

**Comment by muffinresearch** [comment]
This is fixed now for the server-side render at least.
