### ISSUE TITLE
Update icon for Line extensions

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9605]
We want to change the icon for Line extensions so it's a bit more colorful.

<img width="840" alt="CleanShot 2020-08-25 at 11 33 21@2x" src="https://user-images.githubusercontent.com/62568/91865473-ac349780-ec2e-11ea-94b9-a8863e29e7fd.png">

The SVG can be found in this patch: https://phabricator.services.mozilla.com/D86124

Please check how this icon looks when it is at its smallest, like in search results. We should figure out if the badges should be a bit larger in those cases.

For QA:

Although this should not cause any changes in appearance/behaviour on the current site (as we're not using this badge yet), it does touch components that are used for the Recommended badge, so please check for regressions there.

**Comment by bobsilverberg** [comment]
Here's what I have for the complete badges:

<img width="976" alt="Screen Shot 2020-09-01 at 1 41 26 PM" src="https://user-images.githubusercontent.com/142755/91887599-fc285400-ec58-11ea-9829-2f43c116091a.png">

and for the icons (used in autocomplete results):

<img width="331" alt="Screen Shot 2020-09-01 at 1 44 51 PM" src="https://user-images.githubusercontent.com/142755/91887854-55908300-ec59-11ea-8fcb-5ad5840f6443.png">

Note that I made the outline of the Line badge fairly light, as I think it should match the outer circle of the Line icon (which itself is quite light). They are using `grey-30`. I could bump them both up to `grey-40`, but I think that looks pretty dark for the icon, and doesn't really match the example above.

Please let me know what you think @jvillalobos and @aaronrbenson.

**Comment by aaronrbenson** [comment]
Looks good @bobsilverberg!

**Comment by jvillalobos** [comment]
Nice!

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on dev/stage - FF80(Win10).
