### ISSUE TITLE
Remove the Guides page from AMO

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9609]
We introduced "Guides" to AMO back in 2018, based on this mockup:

![hero - article page](https://user-images.githubusercontent.com/217628/46752198-e902e880-ccbc-11e8-9810-2d6c6a49e294.png)

I believe we stopped using them back when we implemented the new Primary and Secondary Hero elements. Looking at the logic, these guides pages are never displayed on the desktop (`/firefox`) site, and on the mobile (`/android`) site all that is displayed is the header (see screenshot). Links to the actual guides pages are never displayed, so I don't think we need them anymore.

This has come up because some changes are required to the guides page to support the new promoted categories, and I'd rather not spend time updating pages that are not actually used by the site.

My suggestion is to delete all the code for the guides pages, and move the code for the header, which is still used on `/android` elsewhere (perhaps into the home page itself). 

@jvillalobos WDYT?

Screenshot showing header from `HomeHeroGuides` as appears on `/android`:

<img width="524" alt="Screen Shot 2020-09-02 at 4 23 58 PM" src="https://user-images.githubusercontent.com/142755/92033010-f43fe100-ed38-11ea-8bf6-482155cfbe4e.png">

For QA:

There should be no changes to the current site. Please just check the home page, both on Desktop and Android for regressions.

**Comment by jvillalobos** [comment]
Yeah, it looks like we stopped linking to them back in October. I don't know if we'll need them again, but I think it should be okay to drop them for now. @devaneymoz should confirm.

**Comment by bobsilverberg** [comment]
Thanks for your response, @jvillalobos. The nice thing about Git is that if we remove the code, and decide later we want it back, it's not too difficult to retrieve it from the history. Based on that I'm going to go ahead and remove the code that supports the Guides pages in order to make working on the other new features a bit easier.

**Comment by willdurand** [comment]
@bobsilverberg are those pages still available in Google search results? Do we get 404s or the actual pages?

**Comment by bobsilverberg** [comment]
> @bobsilverberg are those pages still available in Google search results? Do we get 404s or the actual pages?

They do still appear in Google search results (e.g., https://www.google.com/search?q=The+web+is+a+wonderful+but+wild+place), but I think it's fine for that to return a 404. I don't see how we can have it continue to return the actual page and yet remove the code from the repo. Do you have a suggestion for that?

**Comment by willdurand** [comment]
> They do still appear in Google search results (e.g., [google.com/search?q=The+web+is+a+wonderful+but+wild+place](https://www.google.com/search?q=The+web+is+a+wonderful+but+wild+place)), but I think it's fine for that to return a 404. I don't see how we can have it continue to return the actual page and yet remove the code from the repo. Do you have a suggestion for that?

I don't have a suggestion but it would be interesting to know if those pages drive a lot of traffic or not (cc @muffinresearch). Those pages were designed with SEO in mind so they might still be useful (but maybe not and that's a product call).

**Comment by bobsilverberg** [comment]
> > They do still appear in Google search results (e.g., [google.com/search?q=The+web+is+a+wonderful+but+wild+place](https://www.google.com/search?q=The+web+is+a+wonderful+but+wild+place)), but I think it's fine for that to return a 404. I don't see how we can have it continue to return the actual page and yet remove the code from the repo. Do you have a suggestion for that?
> 
> I don't have a suggestion but it would be interesting to know if those pages drive a lot of traffic or not (cc @muffinresearch). Those pages were designed with SEO in mind so they might still be useful (but maybe not and that's a product call).

@jvillalobos What do you think? Considering that those pages call out specific add-ons, and that we're not really maintaining the pages anymore, perhaps it's a good thing if they go away, even though Google still links to them in search results? I believe there is a way to tell Google to remove a page from their search results (a page which no longer exists), but I'm not sure how well it works.

**Comment by bobsilverberg** [comment]
Another suggestion, made my @eviljeff in the PR, would be to direct these links to the homepage, rather than just 404. Do we think that's something we'd want to do?

**Comment by muffinresearch** [comment]
I think 410/404'ing them is fine. Essentially if the content is gone they should be de-indexed fairly quickly. 

Apparently they got 1,421 page views in August according to GA

One other benefit of cutting them is less pages to be crawled that we don't link to and smaller bundle sizes.

**Comment by jvillalobos** [comment]
Yeah, their traffic has been very low since we stopped linking to them, so I think it's okay to 404 them. The 404 page should be good enough for people to continue navigating (if not, that's a separate problem).

**Comment by ioanarusiczki** [comment]
Verified on AMO dev/stage with FF80(win10 & android).
