### ISSUE TITLE
AMO permission card bottom corners are not rounded 

### ISSUE THREAD

**Issue by navdhakar** [mozilla/addons-frontend#9610]
### what happened?
when i visit any extension permission cards bottom corners are not rounded as other card.
>as previously permission card appearance was changed in issue #9588 caused this problem.
![permission card not rounded corner](https://user-images.githubusercontent.com/27907778/92115326-df824c80-ee0f-11ea-8128-d91ca1227474.png)
### expected
>rounded corner
### step to remove
>change the scss for permission card in ui components.

**Comment by fantonangeli** [comment]
This seems to be already fixed. Maybe we can close it.

**Comment by navdhakar** [comment]
Yes we can close it
