### ISSUE TITLE
Update AMO Search to work with promoted categories as opposed to just Recommended add-ons

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9615]
Allow users to search for different types of promoted add-ons. Replace the "Recommended" checkbox with a dropdown. As @jvillalobos said at https://github.com/mozilla/addons-server/issues/15272#issuecomment-685941863:

> That's correct, we don't need a filter for "not promoted".
> 
> We just need the ones explained in the PRD: "Recommended", "Verified", "Line" and "Reviewed", with the added note that for users "Verified" includes both what we call "Verified" and "Sponsored".

Notes for QA:
- The dropdown should include values for "All", "Recommended", "Verified", "By Firefox" and "Reviewed".
- Verified should return add-ons in both the Verified and Sponsored categories.
- Reviewed should return add-ons in the Line, Recommended, Verified and Sponsored categories.
- API requests issued for recommended add-ons (e.g., on the Home page and the Landing pages) should use `promoted=recommended` instead of `recommended=true`.
- All links to search results (e.g., from the footers on the shelves on the Home and Landing pages) should use `promoted=recommended` instead of `recommended=true`.
- Page headings for Search results that have been filtered by promoted category should reflect that category (e.g., "Recommended extensions", "Verified extensions", "Reviewed extensions", "Extensions by Firefox").

**Comment by jvillalobos** [comment]
> @jvillalobos Should "Line" be used in the dropdown, or should it be "By Firefox"?

It should be "By Firefox".

> Also, confirming that "Reviewed" is "Recommended" + "Verified" + "Line" + "Sponsored", correct?

Correct.

**Comment by bobsilverberg** [comment]
@jvillalobos We have some code that generates a page title for search results. Currently, if the "Recommended" check box is checked, the title says "Recommended extensions", regardless of the other criteria. If "Recommended" is not checked, then the "Sort by" determines the title. For example, "Popular extensions", if "Most Users" is selected.

Now that we're going to have multiple options for promoted (namely "Recommended", "Verified", "By Firefox" and "Reviewed"), how should this figure in to the page title? Should one of these be used, if selected (e.g., "Verified extensions"), and if none is selected then use the "Sort by" as currently done?

If yes to the above, should the titles be "Recommended extensions", "Verified extensions", "Reviewed extensions", and "Extensions by Firefox" (note the different sequencing of the words in the last one)?

**Comment by jvillalobos** [comment]
> Should one of these be used, if selected (e.g., "Verified extensions"), and if none is selected then use the "Sort by" as currently done?

Yes

> If yes to the above, should the titles be "Recommended extensions", "Verified extensions", "Reviewed extensions", and "Extensions by Firefox" (note the different sequencing of the words in the last one)?

Yes, but noting that (extensions|themes|add-ons) is used in the title depending on the Add-on Type filter, which makes sense to keep.

**Comment by bobsilverberg** [comment]
> > Should one of these be used, if selected (e.g., "Verified extensions"), and if none is selected then use the "Sort by" as currently done?
> 
> Yes
> 
> > If yes to the above, should the titles be "Recommended extensions", "Verified extensions", "Reviewed extensions", and "Extensions by Firefox" (note the different sequencing of the words in the last one)?
> 
> Yes, but noting that (extensions|themes|add-ons) is used in the title depending on the Add-on Type filter, which makes sense to keep.

Yes, I didn't call that out, but my plan was to keep that. Thanks for the answers!

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

- there's a "Promoted Add-Ons" dropdown which includes the categories mentioned above.  (by Firefox is next after Recommended but should be alright, I don't know if not Verified is expected to be the next one)

![promoted filter](https://user-images.githubusercontent.com/33448286/93215470-21e04d80-f76f-11ea-8aa3-c063bacff1a9.png)

- verified returns sponsored and verified add-ons and both display the verified green badge.
- reviewed is returning line, recommended, verified and sponsored categories. 
- the URLs where recommended=true was replaced with promoted=recommended are working as expected.
- the page titles look good to me. An example, it's Add-ons by Firefox, Extensions by Firefox, Themes by Firefox.
