### ISSUE TITLE
Enable UTM params in all envs

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9616]
This issue is about enabling the UTM params feature (see #9547) in all envs, including prod.

**Comment by AlexandraMoga** [comment]
I've tested this more extensively in https://github.com/mozilla/addons-frontend/issues/9547#issuecomment-667919835 but I had another quick re-check on -dev. When this lands on stage, I'm going to verify it again.

**Comment by AlexandraMoga** [comment]
I've verified the new UTM parameters on stage and they are now being used in the same locations mentioned in https://github.com/mozilla/addons-frontend/issues/9547#issuecomment-667919835

I'm marking this issue as verified fixed on stage, but I'll also verify prod after the push.
