### ISSUE TITLE
Homepage goes to top after clicking "Back" from a Footer link page

### ISSUE THREAD

**Issue by alexandra-martin** [mozilla/addons-frontend#9619]
### Describe the problem and steps to reproduce it:

1. Go to https://addons.allizom.org/en-US/firefox/ and scroll down to Footer.
2. Click a link from the Footer, e.g. "Developer Hub".
3. Click the "Back" button.

### What happened?
Homepage is displayed from the Header.

### What did you expect to happen?
Homepage to not change page location.
### Anything else we should know?
Reproduced on all AMO servers with FF 80.0.1 on Win10x64.

![footer links](https://user-images.githubusercontent.com/54401091/92741470-54610380-f387-11ea-99de-45f09c2c0984.gif)

**Comment by Rachitatrey** [comment]
what did you expect it should point developer hub

**Comment by alexandra-martin** [comment]
@Rachitatrey yes, when I click the "Developer Hub" Footer link, the correct page is displayed. But, if I click the "Back" button, the page will not be where it was, at the bottom of the page, it will redirect the user at the top of the page.

**Comment by lakshyabatman** [comment]
I can work on this issue.

**Comment by lakshyabatman** [comment]
I can work on this issue.

**Comment by alexandra-martin** [comment]
Reproduced also on a small screen Android 10 on all AMO servers with FF 81.1.1 (Build #2015764547).

![20200924_163940](https://user-images.githubusercontent.com/54401091/94154517-a1180480-fe86-11ea-8def-32514f3346ec.gif)

**Comment by alexandra-martin** [comment]
Another behavior was observed being reproduced intermittently on all AMO servers. 

After a Footer link is accessed and the "Back" button is clicked, the page can be blank, with no information and in a dark color. The page is displayed again if a scroll down (through mouse or keyboard) or a page refresh is made. 

![2](https://user-images.githubusercontent.com/54401091/94813291-7a1a7f00-0400-11eb-94c5-679842f85ba4.gif)

**Comment by saurabh-jaiswal-333** [comment]
Hi @alexandra-martin can I take this issue, or is someone already working on this?

**Comment by Viraj1812** [comment]
i wanna work on this issue.

**Comment by sarthakkundra** [comment]
Hi @alexandra-martin I had a look on this issue and I had some doubts and an approach I wanted to discuss with you.

DOUBTS

- The footer links show a 404 when running a local dev server. Is that the expected behaviour?
- Where is the starting point of the code? Is it server side rendered?

APPROACH

- I was thinking of using this [package](https://www.npmjs.com/package/react-router-scroll-memory). It seems very lightweight and does exactly what you want.

**Comment by ioanarusiczki** [comment]
@bobsilverberg in case you wish to fix this, please take a look at the comments above.

Thanks!
