### ISSUE TITLE
Update the URL for the promoted badges when the page becomes available

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9622]
All of the promoted badges currently point to https://support.mozilla.org/kb/recommended-extensions-program. The should point to https://support.mozilla.org/kb/promoted-addons-program?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=promoted-addon-badge, but that page does not yet exist on SUMO.

The link from the new Promoted Extensions shelf on the homepage should be updated as well.

This issue is about updating the code to point to the correct location once that page exists.

@caitmuenster Could you please add a comment to this issue when the page is ready?

**Comment by caitmuenster** [comment]
Hi @bobsilverberg! The SUMO article has been published. The updated URL is: 

https://support.mozilla.org/kb/add-on-badges?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=promoted-addon-badge

**Comment by bobsilverberg** [comment]
Thanks @caitmuenster!

@jvillalobos A couple of questions of clarification:

1. Should this new link be used for *all* badges, including the Recommended badge, or should the Recommended badge continue to point to https://support.mozilla.org/kb/recommended-extensions-program? I.e., only the Line and Verified badges would link to the new SUMO article.

2. Should we use `utm_content=promoted-addon-badge` for the link from "What's this?" on the new Promoted Add-Ons shelf, or should we use a different value, like `promoted-addon-shelf`?

**Comment by bobsilverberg** [comment]
Actually, looking at the content of https://support.mozilla.org/kb/add-on-badges, I'm not sure it even makes sense as a target for the "What's this?" link on the promoted add-ons shelf. Do we have a different article that describes the program?

**Comment by jvillalobos** [comment]
1. All badges, yes.

2. `promoted-addon-shelf` sounds good.

3. Yeah, I think we need to make some adjustments to the article to support this use case. You can use this as the URL, and we'll edit the article to add the appropriate section:

https://support.mozilla.org/kb/add-on-badges?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=promoted-addon-shelf#sponsored

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified this issue on AMO stage  with FF80(Win10) and I see the changes:
- What is this? URL redirects to https://support.mozilla.org/en-US/kb/add-on-badges?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=promoted-addon-shelf#sponsored (available now on AMO dev)

- on all pages when the badges are available and the badge is clicked, a new tab is opened and it's URL is: 
https://support.mozilla.org/en-US/kb/add-on-badges?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=promoted-addon-badge
