### ISSUE TITLE
Reword the message for non-reviewed add-ons

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9638]
As per the PRD:

Reword the message shown on listing pages for add-ons that aren’t reviewed and update the link for the Learn More action: “This is not monitored for security through Mozilla's Promoted Add-ons program. Make sure you trust it before installing.”

**Comment by bobsilverberg** [comment]
@jvillalobos Is this okay to land now, or do we want to delay this until the pilot program officially starts? Also, can you please confirm this is still the exact message we want?

**Comment by jvillalobos** [comment]
We discussed this earlier today and would like to hold off on applying the change until the pilot is ready to launch and the SUMO page is ready.

**Comment by bobsilverberg** [comment]
> We discussed this earlier today and would like to hold off on applying the change until the pilot is ready to launch and the SUMO page is ready.

Ok, we're going to gate the updated message using the same flag that is being used to control whether the new Promoted Add-Ons shelf appears on the home page.

**Comment by jvillalobos** [comment]
One more change we need here: we need to update the Learn More link to point to the same SUMO article that @caitmuenster is working on.

**Comment by jvillalobos** [comment]
@bobsilverberg sorry for the last-minute change. We're currently discussing the message [in this doc](https://docs.google.com/document/d/1MzhHmHrU4QRGcFFy-tcF7xe1IFHAQDdH_L9H8_dVSWo/edit#heading=h.q5m6wu6zv34z), and coming up with a version that doesn't use the term "Promoted". I hope we'll have a new version before the tag next week.

**Comment by jvillalobos** [comment]
@bobsilverberg here's the latest version of the message:

`This add-on is not actively monitored for security by Mozilla. Make sure you trust it before installing.`

**Comment by bobsilverberg** [comment]
@jvillalobos Now that this is more generic, could we land this message now? We were planning on gating the new message on the launching of the pilot, but maybe that is now unnecessary?

**Comment by jvillalobos** [comment]
No need to gate on the message. We plan to start testing some stuff out (like Line extensions) as early as this week, so having the updated messaging would be good.

**Comment by bobsilverberg** [comment]
> No need to gate on the message. We plan to start testing some stuff out (like Line extensions) as early as this week, so having the updated messaging would be good.

I ended up landing the change, with the feature flag in place, in order to make today's tag. I can remove the gate and cherry pick the change tomorrow, if you feel it would be best for it to go out on Thursday without the flag.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

On AMO Dev I see the new message as being available. It's "This add-on is not actively monitored for security by Mozilla. Make sure you trust it before installing." and "Learn More" link is the same as on AMO stage and prod -> https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_what-are-the-risks-of-installing-non-recommended-extensions

On AMO stage - the old message is displayed. 

Let me know if that's expected because I understand that @jvillalobos said the SUMO page should change and it should go to prod this week.

**Comment by bobsilverberg** [comment]
> @bobsilverberg
> 
> On AMO Dev I see the new message as being available. It's "This add-on is not actively monitored for security by Mozilla. Make sure you trust it before installing." and "Learn More" link is the same as on AMO stage and prod -> [support.mozilla.org/en-US/kb/recommended-extensions-program#w_what-are-the-risks-of-installing-non-recommended-extensions](https://support.mozilla.org/en-US/kb/recommended-extensions-program#w_what-are-the-risks-of-installing-non-recommended-extensions)
> 
> On AMO stage - the old message is displayed.
> 
> Let me know if that's expected because I understand that @jvillalobos said the SUMO page should change and it should go to prod this week.

The changes to the URLs just landed on stage as a cherry-pick, as well as the fact that the new warning message should now appear on stage and prod.

**Comment by ioanarusiczki** [comment]
@bobsilverberg The URL from the "Learn More" is https://support.mozilla.org/en-US/kb/add-on-badges?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=install-warning on AMO dev and stage - FF80(Win10).
