### ISSUE TITLE
Update the label and "all" item for the Promoted drop-down

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9650]
From the PRD:

The AMO search tool must have a filter for Badging, instead of the current Recommended checkbox, with the following values:
- Any
- Recommended
- By Firefox
- Verified
- All Reviewed

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on AMO dev - FF80(Win10). 

![the filter](https://user-images.githubusercontent.com/33448286/93874497-24492700-fcdc-11ea-8b7e-9a2230d344ce.png)
