### ISSUE TITLE
The Choose photo button doesn't respond on Fenix with Android 10 

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9657]
Similar to #9620 

### Describe the problem and steps to reproduce it:
1. Log in to addons.mozilla.org
2. Go to the Edit profile page - `https://addons.mozilla.org/en-US/firefox/user/{user_id}/edit/`
3. Scroll down to the Upload photo section
4. Tap on the 'Choose photo' button 

### What happened?
The button is focused but the upload photo prompt is not displayed

### What did you expect to happen?
You should be prompted to upload a photo

### Anything else we should know?
The button responds when double tapping 

### Device information
* Android device: Xiaomi Mi 9T Pro, Pixel 3a
* Fenix version: 80.1.2
* I did not reproduce with the same devices and Android version on other mobile browsers
* I did not reproduce with the same Fenix version on Android 9

![1600336040439](https://user-images.githubusercontent.com/31961530/93455903-a1902880-f8e5-11ea-89f6-0688ff120d09.gif)

**Comment by willdurand** [comment]
> I did not reproduce with the same Fenix version on Android 9

This is likely a bug with Fenix itself, no?

**Comment by AlexandraMoga** [comment]
> > I did not reproduce with the same Fenix version on Android 9
> 
> This is likely a bug with Fenix itself, no?

It could be, yes, although it is a bit interesting that other buttons do not have this behavior. Maybe this has something to do with the fact that the Choose photo button is triggering that upload prompt.

**Comment by AlexandraMoga** [comment]
Fixed by https://github.com/mozilla/addons-frontend/issues/11135
