### ISSUE TITLE
Browser detection does not work for Firefox forks

### ISSUE THREAD

**Issue by sammacbeth** [mozilla/addons-frontend#9658]
### Describe the problem and steps to reproduce it:

We are working on a Firefox fork, and set the `general.useragent.compatMode.firefox` pref such that the Firefox version is included in the UA string, and sites can treat the browser as Firefox (this pref is documented on [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent/Firefox)). This results in a UA string that contains both Firefox version and our application name:

`Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0 AppName/1.0`

The ua-parser.js library that this project uses for UA parsing unfortunately does not handle this UA string properly, setting the browser as 'Mozilla', rather than 'Firefox'. This means that the AMO site does not recognise the Firefox fork as being able to install addons, showing a call to action to install Firefox instead of the addon install button.

### What happened?

Mozilla addons site does not show the addon install button for Firefox forks:
<img width="293" alt="Screenshot 2020-09-17 at 15 38 33" src="https://user-images.githubusercontent.com/248111/93478309-0c4c5e80-f8fc-11ea-9cd7-e5cf3ccadd4a.png">

### What did you expect to happen?

It should be possible to install addons from the Mozilla addons site from Firefox forks (Note spoofing the UA to a Firefox one does make this possible).

### Anything else we should know?

I also filed an issue for the parsing bug in the ua-parser.js project: https://github.com/faisalman/ua-parser-js/issues/444

**Comment by willdurand** [comment]
It looks like the issue in `ua-parser-js` has been fixed, which I think should fix this issue as well.
