### ISSUE TITLE
Warning about Autoprefixer browsers option when running `yarn amo`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9659]
There is a new warning displayed when running the site locally:

```
Replace Autoprefixer browsers option to Browserslist config.
Use browserslist key in package.json or .browserslistrc file.

Using browsers option can cause errors. Browserslist config
can be used for Babel, Autoprefixer, postcss-normalize and other tools.

If you really need to use option, rename it to overrideBrowserslist.

Learn more at:
https://github.com/browserslist/browserslist#readme
https://twitter.com/browserslist
```

This could be related to the [recent upgrade to autofixer](https://github.com/mozilla/addons-frontend/pull/9653). We should address this if possible.

**Comment by willdurand** [comment]
I've seen this one but it seems to be quite old, I am not sure why we didn't see it before. I read some issues related to this message and it wasn't clear to me what we needed to do. We're using a `.browserslistrc` file and we don't configure `autoprefixer` with `browsers` in the `webpack-common` file.

**Comment by bobsilverberg** [comment]
> I've seen this one but it seems to be quite old, I am not sure why we didn't see it before. I read some issues related to this message and it wasn't clear to me what we needed to do. We're using a `.browserslistrc` file and we don't configure `autoprefixer` with `browsers` in the `webpack-common` file.

Yeah, that's what I've also just discovered. We seem to be doing exactly what they say we should be doing, so I'm not sure why this is showing up, or what we can do about it. I'll do a bit more digging and then just leave it, I guess.

**Comment by bobsilverberg** [comment]
I think I found it! Please stand by...

**Comment by bobsilverberg** [comment]
I believe the problem might be coming from: https://github.com/minhtranite/react-photoswipe/blob/master/postcss.config.js#L9

I opened https://github.com/minhtranite/react-photoswipe/issues/49

**Comment by willdurand** [comment]
> I believe the problem is coming from: [https://github.com/minhtranite/react-photoswipe/blob/master/postcss.config.js#L9](https://github.com/minhtranite/react-photoswipe/blob/master/postcss.config.js?rgh-link-date=2020-09-17T17%3A03%3A21Z#L9)

woah!
