### ISSUE TITLE
Add src to the addon url used by install

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#966]
We need to add `src=discovery-promo` to the add-on urls used by the install so that they're picked up in AMO stats.

**Comment by muffinresearch** [comment]
QA notes: Check the install url has `?src=discovery-promo` on the end of it. Since the url is consumed by an internal API you'll need to look for the network request in a proxy as it doesn't show up on the network tab.

**Comment by muffinresearch** [comment]
I've looked at on stage via charles and I'm seeing what is expected:

![charles_3_11_2_-_session_1__](https://cloud.githubusercontent.com/assets/1514/18127179/a16fdd2a-6f76-11e6-99e2-7d0692c2b454.png)

**Comment by ValentinaPC** [comment]
I've also verified as fixed on AMO-dev FF51.0a1 using Charles.
Postfix screenshot: 
![d](https://cloud.githubusercontent.com/assets/15685960/18133305/b7221e54-6fa2-11e6-8bfe-8d16994418e2.png)
