### ISSUE TITLE
Update tooltip text for Promoted badges

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9660]
I just realized that I provided different tooltip strings for the Promoted badges than those that were reviewed by Meridel. Here are the updated strings:

Recommended: `Firefox only recommends add-ons that meet our standards for security and performance.`
Verified: `This add-on has been reviewed to meet our standards for security and performance.`
By Firefox: `This is an official add-on built by the creators of Mozilla Firefox.`

Note: I tweaked the Recommended string to use "add-on" rather than "extension".

**Comment by ioanarusiczki** [comment]
@bobsilverberg Looks good to me. Verified on AMO dev - FF80(Win10). 

![recommended](https://user-images.githubusercontent.com/33448286/93873101-d03d4300-fcd9-11ea-8c77-fee5c0f0b509.png)
![verified](https://user-images.githubusercontent.com/33448286/93873128-d9c6ab00-fcd9-11ea-92f7-da27d2affdb4.png)
![by Firefox](https://user-images.githubusercontent.com/33448286/93873112-d3383380-fcd9-11ea-8b67-29c3ed06ae8d.png)
