### ISSUE TITLE
Update react-redux to v7

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9665]
In addition to updating `react-router` (see #9663), we should also try to update `react-redux` to the latest version, which is `7.2.1`. This issue will replace https://github.com/mozilla/addons-frontend/pull/9627.

I noticed that we use `connected-react-router` `v5.0.1`, but it has actually released `v6.8.0`, which requires `react-redux` version 6 or 7, but we're currently still on `v5`. So it seems like it makes sense to attempt the `react-redux` upgrade first, and then `react-router`, which could either be combined with, or followed by an upgrade to `connected-react-router` `v6`.

**Comment by willdurand** [comment]
There was an issue about it already: https://github.com/mozilla/addons-frontend/issues/8251

**Comment by bobsilverberg** [comment]
Ok, we should probably close this one then. Do you agree?

**Comment by willdurand** [comment]
yes
