### ISSUE TITLE
Collections page crashes when logged in

### ISSUE THREAD

**Issue by vaindil** [mozilla/addons-frontend#9668]
### Describe the problem and steps to reproduce it:

Simply open the collections page at https://addons.mozilla.org/en-US/firefox/collections/ while logged in.

### What happened?

Going to the page causes the collection info to flash for a brief moment before displaying an error message.

### What did you expect to happen?

The page should not crash.

### Anything else we should know?

The problem occurs in Firefox 80 and 81 as well as Chrome 85.

I have the error below in my console:

> Caught application error: Invariant Violation: name is required

![image](https://user-images.githubusercontent.com/771134/93775842-e4f1dc00-fbf0-11ea-986e-e23bdc2a233d.png)

**Comment by muffinresearch** [comment]
Somehow this collection was missing a name (maybe it was created before collections were updated some time ago?). You should find you can access the collection now and edit it.

**Comment by vaindil** [comment]
Perfect, I'm able to access collections now. Thank you!
