### ISSUE TITLE
Add more space between the Download file link and the install warning message

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9670]
Follow up for #4910 

### Describe the problem and steps to reproduce it:
1. Open the following extension detail page - https://addons-dev.allizom.org/en-US/firefox/addon/signature-files/
2. Notice the add-on detail card layout

### What happened?
There's too little space between the Download file link and the installation warning message

### What did you expect to happen?
Some extra space between the Download file link and the installation warning message should be added

### Anything else we should know?
This issue does not apply to the mobile view

![image](https://user-images.githubusercontent.com/31961530/93783142-0d4efa00-fc34-11ea-84b7-57bf01cd7fc8.png)

**Comment by rochisha0** [comment]
Hi! Can I work on this?

**Comment by bobsilverberg** [comment]
@rochisha0 This needs to be fixed ASAP, so I don't think it will be open to contributors. Thanks for offering!

**Comment by AlexandraMoga** [comment]
Verified fixed on -dev:

![image](https://user-images.githubusercontent.com/31961530/93904974-1955bd00-fd03-11ea-947b-496774da3e8f.png)
