### ISSUE TITLE
Hide the promoted add-ons shelf if there are no add-ons

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9675]
This is a follow-up from https://github.com/mozilla/addons-frontend/issues/9506#issuecomment-696328269.

If there are no add-ons returned by the API request for sponsored add-ons, hide the entire promoted add-ons shelf.

**Comment by ioanarusiczki** [comment]
@bobsilverberg When the API https://addons-dev.allizom.org/api/v4/addons/search/?app=firefox&appversion=81.0&page_size=6&promoted=sponsored&sort=random&type=extension&lang=en-US&wrap_outgoing_links=true is not returning sponsored add-ons the shelf is not displayed. 

Adding one add-on -> Shelf shows 1 add-on
Adding 2 -> Shelf shows 2 add-ons
Adding 3 -> the add-ons are shown on one row
Adding 4, 5-> still one row is displayed 
Adding 6 -> all 6 add-ons are shown on 2 rows

This works as expected, so I'm going to mark it verified on AMO dev - FF80(Win10).
