### ISSUE TITLE
more than 6 sponsored add-ons approved by the admin should be displayed on 2 rows

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9678]
Followup for https://github.com/mozilla/addons-frontend/issues/9506
1. I added 6,7, 8 and then 9 add-ons in [admin ](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=2) as "Sponsored" for "All Application" 

Expected result:
2 row of add-ons should be visible

Actual result: 
only 3 add-ons are displayed

Notes:
I reproduced this issue on AMO dev - FF80(win10).

**Comment by bobsilverberg** [comment]
Can you please check the API response in the network tab for the request to https://addons-dev.allizom.org/api/v4/addons/search/?app=firefox&appversion=81.0&page_size=6&promoted=sponsored&sort=random&type=extension&lang=en-US&wrap_outgoing_links=true?

If the response is returning fewer than 6 add-ons, that would explain why the shelf is only showing 3, and then we need to figure out why the API is returning fewer than we expect. If the response is returning 6, 7 and 8 add-ons, then the issue is on the frontend.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I think it's 7.

![it is 7](https://user-images.githubusercontent.com/33448286/93880396-18faf900-fce6-11ea-86d1-bfd53e471495.png)

**Comment by bobsilverberg** [comment]
I cannot reproduce on dev. Can you please set up the data that reproduces this and then let me know. I currently see 6 add-ons in the shelf on dev.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Done, I left 8 promoted add-ons on [admin](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=2), meaning I set them from `Sponsored` to `Not promoted`,  I see now one row on dev.

![one row](https://user-images.githubusercontent.com/33448286/93893697-9dee0e80-fcf6-11ea-8425-1ff709a99bce.png)

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. The network panel shows only 5 add-ons being returned, which explains why we don't see two rows. There must be an issue with the data, where you are expecting some add-ons to be returned which are not being returned. Can you identify one or more add-ons that you think should be returned but are not?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Can you open the list of active promoted add-ons from admin?
https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=2
You will find there those displayed above and the rest of them are the one not displayed.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Nevermind, I checked each one myself and the API response is correct, because one is a theme https://addons-dev.allizom.org/en-US/firefox/addon/green-spring/ and the second is not compatible with Firefox, it was uploaded for android (that's a limitation that you can add in the Promoted admin `All platforms`). 
I am going to repeat the tests, to make sure I work with type=extension and app=firefox (this means I'll check the compatibility on dev hub, because the promoted admin is not a good reference)

**Comment by ioanarusiczki** [comment]
@bobsilverberg Yep, mystery solved. I added extensions compatible with `Firefox`.

When 6 addons are available:

![6 addons](https://user-images.githubusercontent.com/33448286/93999911-16a8a580-fd9f-11ea-8665-6e441f1f7df8.png)

At 7 addons:
![7addons](https://user-images.githubusercontent.com/33448286/93999947-20320d80-fd9f-11ea-8f07-bce976783353.png)

At 8:
![8 addons](https://user-images.githubusercontent.com/33448286/93999963-258f5800-fd9f-11ea-9742-ae5f2032cf88.png)

With 9:
![9 addons right now](https://user-images.githubusercontent.com/33448286/93999987-2de79300-fd9f-11ea-8806-debe24c90dac.png)

Sorry for forgetting about [that](https://github.com/mozilla/addons-frontend/issues/9678#issuecomment-697221143)
I'm closing this.
