### ISSUE TITLE
Redirect from add-on detail page if the current URL doesn't match `addon.url`

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9692]
This is a follow-up from https://github.com/mozilla/addons-frontend/issues/9667.

As discussed in our meeting, on the add-on detail page, we should check the API response and if the `url` property in the response does not match the current URL, then we should redirect to `addon.url`. Note that the `url` property does not contain the querystring, so we'll need to compare without that, and then add it back in for the redirect.

**Comment by willdurand** [comment]
I don't know why we need to check the url if we are able to store and load the addon detail data in redux (which I think is a challenge here). I have the feeling that the existing logic would already work given that we already support loading an addon by ID and GUID.

**Comment by bobsilverberg** [comment]
I believe the idea was to use the `url` returned by the API as that is guaranteed to be the cannonical URL, as opposed to building one ourself. The current logic already compares the `slug` from the URL to `addon.slug`, so all we're really talking about here is comparing the path from the URL to `addon.url`, so I'm not sure what you're taking issue with.

You are right about the redux issue though. I started to experiment with this yesterday and quickly came across that issue. When we load the retrieved add-on data, it is stored based on the `slug` returned by the API. Therefore, if we try to retrieve it from the store in the component using a different `slug`, e.g., `some-slüg`, as opposed to `some-slug`, the latter of which was used when storing it, we won't find it. We are getting around this a bit by using `trim` when retrieving the `addon` from the store in the component, which addresses cases of " some-slug" and "some-slug ", but doesn't address any non-space case.

So our current code doesn't really support this. We could change our approach so that we store the add-on data in the redux store indexed by the actual `slug` we had on the URL, but that would be a pretty major architectural change. It wouldn't necessarily be a lot of work, but it's a major change in approach.

What happens with the current code is that, even though we did retrieve an add-on, the component is unable to find it, and therefore has nothing to display, so we're left with an add-on detail page in a loading state. Because the API request returned with a 200, and not a 404, we don't end up with a 404 page, and we cannot redirect to the correct URL, because we don't know what it is, because we don't have an add-on.

What do folks think we should do at this point?

**Comment by bobsilverberg** [comment]
For reference, here's a URL on dev that leads to a loading state but not a 404: https://addons-dev.allizom.org/en-US/firefox/addon/t%C3%AFgers-matter/

**Comment by bobsilverberg** [comment]
@willdurand I think we can close this and replace it with an issue about dealing with this in a different way, as discussed on Matrix. I believe you were going to move forward with a patch for a different solution, so I'll leave it to you to either re-purpose this issue, or close it and open a new one.
