### ISSUE TITLE
Strip the language out of the url passed to GA for the secondary hero

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9708]
This is a follow-up to https://github.com/mozilla/addons-frontend/issues/9417. https://github.com/mozilla/addons-frontend/pull/9707 will land the changes to the `action` and `label` data being passed to GA, but one requirement left for this follow-up is to strip the lang from the URL that is passed to GA when a secondary hero element is clicked.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev - FF81(Win10) and the language is no longer present. 

On AMO Dev:  
"eventLabel":"https://addons-dev.allizom.org/firefox/extensions/?utm_sourc….org&utm_medium=referral&utm_content=homepage-secondary-hero"}
