### ISSUE TITLE
Promoted badges don't look nice in RTL mode

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9711]
I noticed this issue while reviewing a different patch.

In RTL mode, the left border is not visible and the right one is too big.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good to me. Verified on dev/stage with FF81(Win10).

![rtl issue](https://user-images.githubusercontent.com/33448286/94796139-04ee8000-03e7-11eb-9ef8-e8625b09fa5f.gif)
