### ISSUE TITLE
Change source of truth for Fenix compatibility

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9713]
From the PRD at https://docs.google.com/document/d/1QTt1G05tjQqfi4ZuAx8Jy4lAshQKdFQpTC3_zqMQHQA/edit#heading=h.fiarmnx52wyo:

Milestone 1, item 3a: "Fenix needs to change its source of truth for supported extensions to Recommended Extensions, instead of a collection. Users can still override this setting with a custom collection in Nightly."

Note that we have already updated AMO to no longer use a collection, and instead it uses a hardcoded list of `guid`s that are supported on Fenix. I assume this issue is about getting rid of the hardcoded list, and using data from the AMO database instead.

(Some) add-ons that are recommended on Fenix have already been marked as Recommended for `android` (or all platforms), in order to allow them to appear on the home page. I'm not sure if all such add-ons have been marked as Recommended. We do not, in fact, need them to be marked specifically as Recommended. We could allow for an add-on in any promoted category (e.g., Line) to be recognized as compatible with Fenix.

@jvillalobos / @diox Other than making sure that any add-ons that are compatible with Fenix are marked as belonging to a promoted category for `android`, is there anything else that is blocking us from moving forward with using that as the source of truth for Fenix compatibility at this time?

**Comment by jvillalobos** [comment]
> We could allow for an add-on in any promoted category (e.g., Line) to be recognized as compatible with Fenix.

Let's stick to Recommended for now. Those are the only add-ons we know work in Fenix.

> is there anything else that is blocking us from moving forward with using that as the source of truth for Fenix compatibility at this time?

Not really. Fenix will need to make an equivalent change, since they currently use collections, but we can make the change on AMO with the caveat that we'll need to update both the recommended list and the collections for some time.

**Comment by bobsilverberg** [comment]
Just to confirm: We will be changing the logic on AMO to no longer use a hardcoded list of `guid`s to identify which add-ons are compatible with Fenix, and instead we will consider any add-on that belongs to the `promoted` category of "Recommended" and is promoted for either `android` or "all platforms" to be compatible.

@jvillalobos Correct?

**Comment by jvillalobos** [comment]
Correct!

**Comment by bobsilverberg** [comment]
@jvillalobos | @devaneymoz When this lands on Thursday, we will no longer be using a hardcoded list of `guid`s to determine which add-ons are compatible with Fenix. Instead, any (and only) add-ons that are listed as being Recommended for `android` (or all platforms) will be considered to be compatible with Fenix, so it would be a good idea to check on production to make sure that all compatible add-ons are in fact listed as Recommended for `android`.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Test results on dev - FF81.1.5 (Android) & FF82(Win10):

- ["See more recommended"](https://addons-dev.allizom.org/en-US/android/search/?promoted=recommended&sort=random&type=extension) shows on Android the list of addons that are recommended for "All Applications" or "Firefox for Android" in the [promoted model](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/promotedaddon/?group_id__exact=1).

- the detail pages for these add-ons show the install button as being inactive (with the "download file" below the button).

- when the admin changes the Application from "Firefox" to "All Applications" or "Firefox for Android" a new version of the add-on must be submitted (the developer also has to check the android platform at submission). Only after the approval of the new version the add-on will be displayed with a recommended badge on android in the recommended shelf.

I think that this works as expected. If there's anything else I should check, please let me know.

**Comment by bobsilverberg** [comment]
That all sounds good, thanks @ioanarusiczki!
