### ISSUE TITLE
Update compatibility messaging for all pages on AMO that aren’t the homepage, search, or supported listing pages.

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9714]
From the PRD at docs.google.com/document/d/1QTt1G05tjQqfi4ZuAx8Jy4lAshQKdFQpTC3_zqMQHQA/edit#heading=h.fiarmnx52wyo:

Milestone 1, item 4: "Update compatibility messaging for all pages on AMO that aren’t the homepage, search, or supported listing pages."

I am unclear about the requirements for this one. Currently, on all pages other than the Add-On Detail page, the message a user sees when visiting with Fenix is:

"To learn about add-ons compatible with Firefox for Android, click here.", with the "click here" link pointing to https://support.mozilla.org/kb/find-and-install-add-ons-firefox-android

@jvillalobos In what way does this need to change?

For QA:

The document at https://docs.google.com/spreadsheets/d/1rqPj5NXPNE9EPDuIPy8AjMxs5k0BBic9c_c7WGjGhWs/edit?usp=sharing details what messages should now be shown in various use cases.

**Comment by jvillalobos** [comment]
Let's change the message to this:

"To find add-ons compatible with Firefox for Android, click here.", with the "click here" link pointing to the AMO homepage.

**Comment by bobsilverberg** [comment]
I'm working on this, and I made the specific change discussed above, but I'm not sure it's exactly what we want. The message I am replacing appears on both the `firefox` and `android` sites, but it doesn't seem to make a lot of sense to redirect users to the homepage of the `firefox` site to find add-ons compatible with Firefox for Android. I think in that case we want to re-direct them to the homepage on the `android` site, no?

We currently have separate rules for what we do with users depending on whether they are on Fennec or Fenix, and we are not currently re-directing users on Fenix from the `desktop` site to the `android` site, but maybe we want to change that now? If our assumption is that all users will now be on Fenix (or at least that's our target audience), should we be re-evaluating the rules we have in place both for Fennec and for Fenix? If so then perhaps I should start by documenting exactly what the rules are for each product.

@jvillalobos WDYT?

**Comment by jvillalobos** [comment]
> The message I am replacing appears on both the firefox and android sites, but it doesn't seem to make a lot of sense to redirect users to the homepage of the firefox site to find add-ons compatible with Firefox for Android. I think in that case we want to re-direct them to the homepage on the android site, no?

That's correct, assuming we're talking about mobile users. Sending them to the `/android/` homepage makes sense.

> should we be re-evaluating the rules we have in place both for Fennec and for Fenix?

We should be treating Fenix and Fennec users in the same way and avoid keeping Fennec-specific behaviors. It'd be good to review what rules we have for both browsers that are different.

**Comment by bobsilverberg** [comment]
@jvillalobos I created [this doc](https://docs.google.com/spreadsheets/d/1rqPj5NXPNE9EPDuIPy8AjMxs5k0BBic9c_c7WGjGhWs/edit?usp=sharing) which lists which messages appear in various cases based on which "site" a user is on, which browser they are using, and the compatibility of the current add-on.

Please take a look and let me know what changes you think we should make.

**Comment by jvillalobos** [comment]
I added the proposed changes to the doc. Let me know what you think.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos, that looks good. I'll summarize the changes below:

- There should be no differences between messaging for users on Fennec and Fenix. More detail about specific messages can be found below:

- For all pages other than the add-on detail page, the home page, and the search results page, if a user is on mobile (Fennec or Fenix), regardless of the site they are visiting, we should show "To find add-ons compatible with Firefox for Android, click here."
Question: In the doc you indicate this should also be shown to users on the desktop browser when visiting the `android` site. Is that correct? It seems to me that users on desktop Firefox visiting `android` should still get the "To find add-ons compatible with Firefox on desktop, visit our desktop site." message.

- On the add-on detail page, visitors on mobile should see "You can install this add-on in the Add-ons Manager. Learn more about add-ons for Android." when viewing an add-on that is compatible with Fenix, regardless of which site they are on.

- On the add-on detail page, visitors on mobile should see "To find add-ons compatible with Firefox for Android, click here." when viewing an add-on that is *not* compatible with Fenix, but only on the `android` site. If they are visiting the `firefox` site, the message should read "Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. Learn more about add-ons for Android."

Does that capture all the changes?

**Comment by jvillalobos** [comment]
> In the doc you indicate this should also be shown to users on the desktop browser when visiting the android site. Is that correct? It seems to me that users on desktop Firefox visiting android should still get the "To find add-ons compatible with Firefox on desktop, visit our desktop site." message.

You're right, I corrected row 4 in the doc.

> "Not available on Firefox for Android. You can use this add-on with Firefox for Desktop. Learn more about add-ons for Android."

I updated rows 18 and 20 to remove the sentence "You can use this add-on with Firefox for Desktop.", given that there are some Fennec-specific extensions for which this is incorrect.

> Does that capture all the changes?

Looks good.

**Comment by bobsilverberg** [comment]
Sorry, @jvillalobos, I have one last question: With the requirements as described above, a user who is using an Android browser, but it visiting the desktop site, will see the message "To find add-ons compatible with Firefox for Android, click here.", which directs them to the home page. If they click on that they'll end up on the home page for the desktop site, and therefore will still be presented with add-ons that might not be compatible with Fenix. Are you sure we don't want to continue directing users to the mobile site if they are on an Android browser, but visiting the desktop site?

**Comment by jvillalobos** [comment]
I forgot to mention that the link in the proposed column is pointing to `/android/`, so yes, we should totally be sending those users to the mobile homepage.

**Comment by bobsilverberg** [comment]
Thanks @jvillalobos, I missed that the link was pointing there!  Also, I lied, that wasn't my last question. I have one more:

In the case where a user is on the desktop site (`/firefox/`) and using an Android browser, and they're on the Add-on Detail page and the add-on is *not* Fenix compatible, the doc says to show "Not available on Firefox for Android. Learn more about add-ons for Android." (with a link to the SUMO article), but this seems inconsistent with what we do when they are on the mobile (`/android/`) site. If they are on the mobile site, for an incompatible add-on, we show "To find add-ons compatible with Firefox for Android, click here." and direct them to `/android/`. To me it seems like we should also do this for the use case I describe.

WDYT?

**Comment by jvillalobos** [comment]
I agree. I updated lines 18 and 20 to match what you're proposing.

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've verified the compatibility messages on -dev and I've updated the [spreadsheet](https://docs.google.com/spreadsheets/d/1rqPj5NXPNE9EPDuIPy8AjMxs5k0BBic9c_c7WGjGhWs/edit#gid=0) with my results for each case. 
In addition to that, I have a question regarding themes on mobile (both Fennec and Fenix): currently, every recommended theme will display the "You can install this add-on in the Add-ons Manager. Learn more about add-ons for Android." message and the install button appears enabled:

https://addons-dev.allizom.org/en-US/android/addon/the-baby-of-nevermind/
![image](https://user-images.githubusercontent.com/31961530/98671442-ede36c00-235c-11eb-84fe-42f29663d337.png)

I've checked stage for comparison and the compatibility message is displayed there as well, but the Install button is disabled. 
Non-recommended themes will display a disabled Install button.

As a side note, Fennec was tested in Responsive design with the User Agent override option (`Mozilla/5.0 (Android 9; Mobile; rv:68.0) Gecko/68.0 Firefox/68.0`)

**Comment by bobsilverberg** [comment]
Thanks @AlexandraMoga. Regarding your observation about lines 4-5 in the spreadsheet, I notice that I missed the note about not showing the message on the homepage and search pages, but I actually think it's better to have in on these pages too.

@jvillalobos You had requested not to display the message "To find add-ons compatible with Firefox for Android, click here.", which includes a link to the *mobile* home page, for users visiting the *desktop* homepage with an Android browser. My current implementation actually does show this message on the homepage and search results, but I think that makes sense, as the user is currently on the *wrong site*. If they are using an Android browser, but looking at the desktop homepage, doesn't it make sense to show them the message with a link to the mobile site?

@jvillalobos It looks like a second issue was raised by @AlexandraMoga about themes. I guess what's happening is that the logic we use to determine that an add-on is compatible with Fenix (that it is currently Recommended for android), is causing Recommended Themes to appear as compatible with Fenix. I take it that they are not? Should we therefore adjust our logic to exclude all themes and treat them as not compatible with Fenix?

**Comment by jvillalobos** [comment]
> @jvillalobos You had requested not to display the message "To find add-ons compatible with Firefox for Android, click here.", which includes a link to the mobile home page, for users visiting the desktop homepage with an Android browser. My current implementation actually does show this message on the homepage and search results, but I think that makes sense, as the user is currently on the wrong site. If they are using an Android browser, but looking at the desktop homepage, doesn't it make sense to show them the message with a link to the mobile site?

I agree with the current implementation and removed the note.

> @jvillalobos It looks like a second issue was raised by @AlexandraMoga about themes. I guess what's happening is that the logic we use to determine that an add-on is compatible with Fenix (that it is currently Recommended for android), is causing Recommended Themes to appear as compatible with Fenix. I take it that they are not? Should we therefore adjust our logic to exclude all themes and treat them as not compatible with Fenix?

Correct, themes are not compatible, so they shouldn't show up as such.

**Comment by bobsilverberg** [comment]
> > @jvillalobos You had requested not to display the message "To find add-ons compatible with Firefox for Android, click here.", which includes a link to the mobile home page, for users visiting the desktop homepage with an Android browser. My current implementation actually does show this message on the homepage and search results, but I think that makes sense, as the user is currently on the wrong site. If they are using an Android browser, but looking at the desktop homepage, doesn't it make sense to show them the message with a link to the mobile site?
> 
> I agree with the current implementation and removed the note.
> 
> > @jvillalobos It looks like a second issue was raised by @AlexandraMoga about themes. I guess what's happening is that the logic we use to determine that an add-on is compatible with Fenix (that it is currently Recommended for android), is causing Recommended Themes to appear as compatible with Fenix. I take it that they are not? Should we therefore adjust our logic to exclude all themes and treat them as not compatible with Fenix?
> 
> Correct, themes are not compatible, so they shouldn't show up as such.

Thanks @jvillalobos. @AlexandraMoga could you open an issue for this?
