### ISSUE TITLE
Call impression URL when displaying sponsored homepage shelf

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#9720]
When implementing https://github.com/mozilla/addons-frontend/issues/9719 to fetch the sponsored shelf through the specific API we're building in https://github.com/mozilla/addons-server/issues/15617 we need to call an impression URL, that should be part of the response from the API. See also https://github.com/mozilla/addons-server/issues/15618 for the impression endpoint implementation.

One open question is around whether we call one endpoint for the whole shelf or multiple ones.

Maybe consider using https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon to make the call.

**Comment by bobsilverberg** [comment]
Ha, I was just coming here to comment on using `sendBeacon`! I'd like to do that, but I see it's unsupported on IE. Do we care about that? Do we need to program our own fallback, or just not record an impression if `sendBeacon` is unsupported?

cc @jvillalobos

**Comment by jvillalobos** [comment]
IE traffic to the homepage is negligible, so it's fine to not support it.

**Comment by ioanarusiczki** [comment]
@bobsilverberg
When the homepage is displayed/reloaded: POST | https://addons-dev.allizom.org/api/v4/shelves/sponsored/impression/ is present in the Network with a 202 Accepted status. 

![call impression URL](https://user-images.githubusercontent.com/33448286/96268187-69a5ff00-0fd1-11eb-8517-08662fa848ba.png)
