### ISSUE TITLE
Call click URL when clients follow a link from the sponsored homepage shelf

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#9721]
When implementing #9719 to fetch the sponsored shelf through the specific API we're building in mozilla/addons-server#15617 we need to call a special click URL when the user follows a link from the shelf. See https://github.com/mozilla/addons-server/issues/15619 for the implementation of that endpoint.

We may want to track conversions (installs following a click) as well through Adzerk - that's up to product, we'd need to research what needs to be implemented for that to happen.

**Comment by bobsilverberg** [comment]
Do we want to consider using `sendBeacon` for this as well?

**Comment by diox** [comment]
The `clickUrl` will eventually redirect to the right URL, including utm query parameters, so we probably only need to follow the redirects (request to AMO, which redirects to adzerk, which redirects back to AMO)

**Comment by bobsilverberg** [comment]
> Adzerk's `clickUrl` will eventually redirect to the right URL, including utm query parameters, so we probably only need to follow the redirects (request to AMO, which redirects to adzerk, which redirects back to AMO)

Ok, so we simply make the `href` of the `a` tag the value returned in `clickURL` from the API response? I was planning on sending a beacon to the `clickURL` via javascript, and just keeping the link destination as it currently is, but it sounds like we don't need to do that at all, correct?

**Comment by diox** [comment]
From discussion on slack:

Current locale and app need to be injected in the URL, but Adzerk would only have a single immutable URL to redirect to, so that's not very convenient. Our new strategy would be to have the proxy endpoint live under /api/ and be called through `sendBeacon` (which is a `POST`) and that endpoint would make a request to Adzerk's `clickUrl` while the frontend just follows the regular URL for the add-on, just adding the relevant `utm` parameters.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Verified on dev - FF82(Win10). 

![the event API](https://user-images.githubusercontent.com/33448286/96972922-d7957d80-151f-11eb-8e6f-e72fb7d99705.png)
