### ISSUE TITLE
Animated Zoom of Screenshots Triggers Eye Strain and Migraines

### ISSUE THREAD

**Issue by MarjaE2** [mozilla/addons-frontend#9723]
### Describe the problem and steps to reproduce it:
(Please include as many details as possible.)

Examining add-ons, the small screenshots are too small to read. If I click on the screenshot to enlarge them, addons.mozilla.org animates the resizing, inflicting a lot of eye strain and migraines.

### What happened?

I clicked. I got hit with animation of the resizing. I got another migraine. For whatever reason, zooming animation [e.g. Google Maps] reliably triggers my migraines.

### What did you expect to happen?

I don't know but many sites can show full-sized images without triggering my migraines.

### Anything else we should know?
(Please include a link to the page, screenshots and any relevant files.)

**Comment by willdurand** [comment]
We use `prefers-reduced-motion` nowadays so I think this is has been fixed (feel free to reopen if I am wrong).
