### ISSUE TITLE
Send GA event for clicks on Download Firefox button

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9729]
This would be **really** useful to track for our metrics:

- Event Category: "AMO Download Firefox"
- Event Action: "download-firefox-click"
- Event Label: Add-on GUID if it's the main Download Firefox button on a listing page. Empty if it's the Download Firefox button in the site header.

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on AMO stage:

[Clicking on the Download Firefox button in the header]
```
sendEvent {"hitType":"event","eventCategory":"AMO Download Firefox","eventAction":"download-firefox-click","eventLabel":""}
```
[Clicking on the Download Firefox button in the addon detail page or on the All Versions page]
```
sendEvent {"hitType":"event","eventCategory":"AMO Download Firefox","eventAction":"download-firefox-click","eventLabel":"{37f296a5-e429-430f-9154-2151d1369ddc}"}
```
