### ISSUE TITLE
Rename loadAddonResults to loadAddon

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9730]
This is needed to implement a fix for #9692 

**For QA:** please make sure we can load add-on detail pages as before (note: the issue described in #9692 isn't fixed yet). Also make sure the disco pane (the old HTML one, yeah) is still working.

**Comment by AlexandraMoga** [comment]
I didn't have issues with loading add-on detail pages and the old DiscoPane is still working:

![image](https://user-images.githubusercontent.com/31961530/95311806-ca795d00-0896-11eb-868d-a30557dbc19f.png)

This was verified on AMO stage.
