### ISSUE TITLE
Load add-on detail page with data coming from the API

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9731]
Follow-up https://github.com/mozilla/addons-frontend/issues/9667

---

Sometimes the API returns an add-on (data in the API response) but the frontend does not display the detail page because of a slug mismatch or something like that. We support loading an add-on detail page by add-on (numeric) ID, GUID and slug (case sensitive).

The API supports trailing spaces as well as some other fancy characters. Here are a few examples:

- https://addons-dev.allizom.org/en-US/firefox/addon/firefox-COLOR/
- https://addons-dev.allizom.org/en-US/firefox/addon/firefox-color   /
- https://addons-dev.allizom.org/en-US/firefox/addon/firefox-colör/

This URL does not work, though, because the API does not support leading spaces:

- https://addons-dev.allizom.org/en-US/firefox/addon/ firefox-color/

Let's try to show an add-on detail page when the API returns data for the add-on, no matter the parameter passed in the URL.

**Comment by ioanarusiczki** [comment]
@willdurand 

I verified on AMO dev - FF81(Win10), results:

- with upper cases, the GUID or slug is returning the addon detail page.

https://addons-dev.allizom.org/en-US/firefox/addon/forecastfox@s3_fix_VERSION/
https://addons-dev.allizom.org/en-US/firefox/addon/forecastfox-FIX-version/

- replacing some letters with unicode is returning the detail page when the slug is used but it's a 404 when I used them with the GUID:

slug: https://addons-dev.allizom.org/en-US/firefox/addon/fÖrecastfox-fix-versiÖn/
GUID: https://addons-dev.allizom.org/en-US/firefox/addon/forecÁstfox@s3_fix_version

- when a space is added before (or in the middle somewhere) the slug, GUID, or ID, the result is a 404 as described in https://github.com/mozilla/addons-frontend/issues/9667#issuecomment-698390545

- with spaces added at the end of the slug, GUIDS, ID's the detail page is displayed. 

Let me know if that's as expected or there's anything else I should check on. 
Thanks!

**Comment by willdurand** [comment]
I think that works as intended yeah, thanks!
