### ISSUE TITLE
Enable the Sponsored add-ons shelf on the homepage

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9735]
Flip the flag so that the Sponsored add-ons shelf will appear on the homepage on stage and prod.

Requested by @diox via Matrix on behalf of @jvillalobos

**Comment by bobsilverberg** [comment]
It looks like impression events are being sent to GA twice when the homepage is rendered on the server. If a user lands on a different page, and navigates to the homepage, it sends the expected number of events, but if a user starts on the homepage, or refreshes the homepage, then two events are sent for each add-on. 

I'm not sure how quickly I'll be able to come up with a fix for this. 

@jvillalobos Should we delay implementing the shelf until this can be fixed, or would we prefer to have the shelf live ASAP and possibly have to deal with this data issue?

**Comment by jvillalobos** [comment]
Let's enable the shelf anyway. We'll just need to keep in mind that the impression data will be temporarily inflated. /cc @devaneymoz

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
- I enabled the sponsored shelf on [AMO stage](https://addons.allizom.org/en-US/firefox/). Looks good to me. 

- I could reproduce the GA event issue at a page reload - The Console shows the events twice but that's going to be fixed.
