### ISSUE TITLE
Sponsored add-on impressions are recorded twice with SSR

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9737]
Impression events are being sent to GA twice when the homepage is rendered on the server. If a user lands on a different page, and navigates to the homepage, it sends the expected number of events, but if a user starts on the homepage, or refreshes the homepage, then two events are sent for each add-on.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev and AMO stage. The issue is no longer reproducible.

![one GA event](https://user-images.githubusercontent.com/33448286/95426016-e8ee5f80-094d-11eb-99bc-afefc8be22bb.gif)
