### ISSUE TITLE
Rename PromotedAddonsCard to SponsoredAddonsShelf

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9746]
Supports #9719.

This is just a small cleanup that I'd like to do, and doing it as a separate issue will reduce the size of the final patch for #9719.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Let me know if testing for https://github.com/mozilla/addons-frontend/issues/9744#issuecomment-707107338 covers this too. 
Thanks!

**Comment by bobsilverberg** [comment]
> @bobsilverberg Let me know if testing for [#9744 (comment)](https://github.com/mozilla/addons-frontend/issues/9744#issuecomment-707107338) covers this too.
> Thanks!

Yes, that should cover it. Thanks!
