### ISSUE TITLE
Measure installation of add-ons in the sponsored shelf

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9762]
For add-ons in the sponsored shelf, we need to measure impressions, clicks, and installations. There are some additional steps that need to be taken in the Adzerk setup for installations to be measured.

**Comment by bobsilverberg** [comment]
@willdurand ottomh, I'm thinking we could store the info needed for the install ping in the redux store, and then use that info when an add-on is installed. WDYT? This seems a lot easier than trying to carry that data around on a URL.

@jvillalobos At its simplest, this could send the ping if a user installs an add-on immediately after clicking on the link, but there may be other use cases we want to capture, such as:
- A user clicks a link for a sponsored add-on, installs a different add-on, and later installs the sponsored add-on
- A user clicks a link for sponsored add-on "A", then clicks a link for sponsored add-on "B", and then installs add-on "A" (i.e., they don't install the sponsored add-on that was most recently clicked)

Note that when I say "immediately" above, I don't necessarily mean immediately, but I mean that they install it before installing any other add-ons and before clicking on any other sponsored add-ons.

**Comment by jvillalobos** [comment]
Yes, we should check that the add-on being installed is the one that was clicked on in the sponsored section. I think keeping track of the sponsored add-on that was **last** clicked on should be good enough.

**Comment by bobsilverberg** [comment]
Further to this, we should define exactly what we consider to be a conversion. What is the exact flow that constitutes a conversion?

Should it only count if a user goes directly from the sponsored shelf to an add-on detail page and then immediately installs? Can a user do some other navigation/activity on the site before installing and still have it count?

**Comment by jvillalobos** [comment]
I think that having the install following the click within the same session should be enough to count as a conversion. It's possible the user would navigate to the versions page or the reviews page to gather more info before installing.

**Comment by willdurand** [comment]
I agree we should use the session storage. That being said, we'll have to make sure it works as intended because browsers tend to do (not so) smart things with session storage, e.g., by retaining the session storage after browser restart.

**Comment by bobsilverberg** [comment]
> I agree we should use the session storage. That being said, we'll have to make sure it works as intended because browsers tend to do (not so) smart things with session storage, e.g., by retaining the session storage after browser restart.
>

I was actually leaning more towards using the Redux store, and not session storage:
- We already have everything in place to just use it
- We're guaranteed that it will be cleared on browser restart
 
> Question: this tracking only involves Adzerk, right?

Correct, this is just to enable us to send pings back to addons-server on add-on install for the purposes of addons-server then pinging Adzerk.

**Comment by willdurand** [comment]
Ha, sorry I read "latter" for some reasons :/

I don't think a page refresh should clear the state, though, and that's what will happen with Redux. If Product wants to track an `install following the click within the same session`, then I think we need session storage.

**Comment by ioanarusiczki** [comment]
@bobsilverberg  
- https://addons-dev.allizom.org/api/v4/shelves/sponsored/event/ responds with a 202 status twice : when I click on a sponsored add-on from the shelf and after completing an installation: 

![at install](https://user-images.githubusercontent.com/33448286/97542929-38b1cb00-19d0-11eb-9975-e4e19cf547ad.gif)

- I tried the scenarios [described](https://github.com/mozilla/addons-frontend/issues/9762#issuecomment-708417788). 

About: 

> A user clicks a link for sponsored add-on "A", then clicks a link for sponsored add-on "B", and then installs add-on "A" (i.e., they don't install the sponsored add-on that was most recently clicked)

If this scenario happens all in one tab, then is the user navigating back to "A" using the back button?

**Comment by bobsilverberg** [comment]
> 
> About:
> 
> > A user clicks a link for sponsored add-on "A", then clicks a link for sponsored add-on "B", and then installs add-on "A" (i.e., they don't install the sponsored add-on that was most recently clicked)
> 
> If this scenario happens all in one tab, then is the user navigating back to "A" using the back button?

Yes. It's important that they don't click on add-on "A" from the Sponsored shelf, otherwise that would become the most recent one again.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I could see the /event/ API being called when I did not have the problem that the detail page for addon "A" is not displayed. I can't tell if that's from the browser or AMO:

![this is not going back right](https://user-images.githubusercontent.com/33448286/97689236-f2c63700-1aa3-11eb-85c3-aea14cc8128e.gif)

**Comment by bobsilverberg** [comment]
> @bobsilverberg I could see the /event/ API being called at installation of the addon "A" when I did not have the problem that the detail page for addon "A" is not displayed. I can't tell if that's from the browser or AMO:
> 
> ![this is not going back right](https://user-images.githubusercontent.com/33448286/97689236-f2c63700-1aa3-11eb-85c3-aea14cc8128e.gif)

I'm sorry, I don't follow what you're saying/asking. First off, there are two different reasons that the /event/ API may be called:
1. It is called when an add-on is clicked from the Sponsored shelf. In this case if you look at the request data it should include a form field called `type` with a value of `click`.
2. It is called when an add-on is installed, and that add-on is the last add-on clicked from the Sponsored shelf. In this case if you look at the request data it should include a form field called `type` with a value of `conversion`.

Having explained that, I don't understand your question, so can you try to clarify exactly what behaviour you are questioning?

**Comment by ioanarusiczki** [comment]
@bobsilverberg Nevermind, I am going to mark verified this issue because the /event/API is happening as [described ](https://github.com/mozilla/addons-frontend/issues/9762#issuecomment-719513699)
