### ISSUE TITLE
Configure the Primary Hero area to interact with GA

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9763]
Like with the Sponsored shelf, we need the Primary Hero area to report impressions and clicks to GA. We want it to be possible to show non-Recommended content in that area next year (https://github.com/mozilla/addons-server/issues/15671).

We already report clicks with the `AMO Primary Hero Clicks` event, so we would only need the equivalent `AMO Primary Hero Impressions` event to be reported.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
-  AMO primary hero impression is reported to GA.

![primary hero impression](https://user-images.githubusercontent.com/33448286/96263244-758ec280-0fcb-11eb-933c-8526d47d9436.png)

- AMO primary hero click is also reported to GA. 

![primary hero click](https://user-images.githubusercontent.com/33448286/96263469-b686d700-0fcb-11eb-88d8-bc3ad2571aa6.png)
