### ISSUE TITLE
Support non-Recommended extensions in the Primary Hero area

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9764]
Per https://github.com/mozilla/addons-server/issues/15671, we want to be able to display non-Recommended extensions in the Primary Hero area of the homepage. At least in this iteration we won't worry about using Adzerk, so they will still be managed in the Discovery admin.

The header text should say: `Recommended` for Recommended add-ons, `By Firefox` for By Firefox add-ons, `Sponsored` for anything else. If the header says `Sponsored`, the "What is this?" link should appear next to it (design tbd).

**Comment by bobsilverberg** [comment]
As https://github.com/mozilla/addons-server/issues/15671 has landed, I'm going to start working on this with an aim to land it for next week's tag. I can either add the link for "What is this?" in a way that seems best to me, and then we can change it once we have UX feedback, or I can leave off the "What is this?" link for now.

Which would be preferable, @jvillalobos?

**Comment by bobsilverberg** [comment]
@jvillalobos Another question: Currently the header actually says "RECOMMENDED" (all uppercase), not "Recommended". Does this issue include changing the header to now be in mixed case as opposed to all uppercase?

**Comment by jvillalobos** [comment]
> I can either add the link for "What is this?" in a way that seems best to me

That would be good for now. We can use a screenshot from -dev to get the discussion going with UX.

> @jvillalobos Another question: Currently the header actually says "RECOMMENDED" (all uppercase), not "Recommended". Does this issue include changing the header to now be in mixed case as opposed to all uppercase?

Let's keep them all uppercase.

**Comment by bobsilverberg** [comment]
Great, thanks @jvillalobos. I've basically copied the style of the existing "What is this?" link from the Promoted shelf and used it as is for now. The blue colour looks a bit funny depending on the background gradient of the Primary Hero. Here are a few examples:

<img width="885" alt="Screen Shot 2020-10-15 at 12 21 48 PM" src="https://user-images.githubusercontent.com/142755/96158172-3a17c980-0ee1-11eb-836a-d8a140df133c.png">

<img width="882" alt="Screen Shot 2020-10-15 at 12 23 54 PM" src="https://user-images.githubusercontent.com/142755/96158298-603d6980-0ee1-11eb-8a06-d3bfa4079870.png">

<img width="886" alt="Screen Shot 2020-10-15 at 12 24 15 PM" src="https://user-images.githubusercontent.com/142755/96158333-69c6d180-0ee1-11eb-997f-ba821a5d5e26.png">

**Comment by jvillalobos** [comment]
I suggest using the same grey color as the header.

**Comment by bobsilverberg** [comment]
Ok, here's what it looks like with that colour:

<img width="830" alt="Screen Shot 2020-10-15 at 2 37 15 PM" src="https://user-images.githubusercontent.com/142755/96172172-04301080-0ef4-11eb-9f19-0624ca2ed816.png">

**Comment by bobsilverberg** [comment]
With this landed, it should now be fine to use verified, sponsored and line add-ons in the Primary Hero. Note that this won't land on prod until this Thursday though.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on dev:

- recommended addons look like before. They have RECOMMENDED displayed.
- sponsored addons have SPONSORED and What is this? URL - which is also grey and it redirects to https://support.mozilla.org/en-US/kb/add-on-badges?utm_source=addons.mozilla.org&utm_medium=referral&utm_content=homepage-primary-hero#sponsored

![Sponsored addons](https://user-images.githubusercontent.com/33448286/96593068-c6672980-12f1-11eb-940e-96533c495687.png)

- by firefox

![By Firefox](https://user-images.githubusercontent.com/33448286/96593115-d4b54580-12f1-11eb-8c78-b2168f35fd26.png)

- spotlight addons are displayed the same way as sponsored (with the What is this? URL included).  I think that it should be included here from the  [request](https://github.com/mozilla/addons-frontend/issues/9764#issue-720853289)

![Spotlight as sponsored](https://user-images.githubusercontent.com/33448286/96593682-750b6a00-12f2-11eb-9d1f-69c02a35d4c4.png)

- as I said in https://github.com/mozilla/addons-server/issues/15671#issuecomment-711936977 something goes wrong when I add an android addon to the primary hero. So I'm filing it and if that's a server issue I will transfer it there, let me know. https://github.com/mozilla/addons-frontend/issues/9781
