### ISSUE TITLE
Always show all add-ons returned by the sponsored endpoint

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9771]
There is code in place to only display 3 add-ons in the Sponsored shelf if only 4 or 5 are returned via the API. This causes issues for recording impressions with the current implementation, so it has been decided that we will always show all of the add-ons, even if only 4 or 5 are returned. This will be mitigated by ensuring that there are always more than 6 sponsored add-ons available.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
I verified this on dev - FF82(Win10): 

When 4 addons are displayed

![4addons](https://user-images.githubusercontent.com/33448286/96716450-b745b180-13ad-11eb-8bec-2a2e01deaad4.png)


When 5 addons are displayed

![5 addons](https://user-images.githubusercontent.com/33448286/96716495-c62c6400-13ad-11eb-8675-4d498e09605c.png)
