### ISSUE TITLE
Take the DNT setting into account for sendBeacon

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9779]
This is a follow-up to https://github.com/mozilla/addons-frontend/pull/9766.

In order to support the callbacks for Adzerk integration, we have added a new utility function that calls `navigator.sendBeacon` to send data to addons-server which then sends data to Adzerk. In our `tracking` utility which interacts with GA, we check the DNT setting and if it is on we do not send any data to GA. It was suggested that we do the same with this new `sendBeacon` method so that we wouldn't send any data anywhere with it if DNT is turned on. This would affect our calls for the sponsored add-ons shelf for impressions, clicks and conversions.

@jvillalobos Thoughts?

**Comment by jvillalobos** [comment]
Yes, I think we should treat Adzerk the same way we do GA.

**Comment by AlexandraMoga** [comment]
@bobsilverberg I've verified the Sponsored shelf and the site in general with DNT enabled and disabled and, apart from #9800, I haven't noticed other issues. Let me know if you have anything specific that you'd like me to verify more closely.
