### ISSUE TITLE
Move sendBeacon into tracking

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9782]
To support #9762, we need to be able to send a beacon from within `installAddon`, which lives in `core`. Our own `sendBeacon` function currently lives in `amo/utils`, so it needs to move into `core`, and `tracking` seems like a logical place for it. This will also help with #9779 

This is just a refactoring exercise, so nothing should change about the behavior of the app.

**Comment by AlexandraMoga** [comment]
Apart from #9800, which could be a potential regression, I haven't noticed other issues, tracking related or general.

I'm marking the issue as verified fixed on -dev.
