### ISSUE TITLE
Search results do not honor or allow to be opened in a new tab/window

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#9791]
### Describe the problem and steps to reproduce it:

1. Do a search, e.g. https://addons.mozilla.org/en-US/firefox/search/?q=fox
2. CTRL+Click on the description of a result

### What happened?

The result is opened in the current tab.

### What did you expect to happen?

The result should be opened in a new tab.

### Anything else we should know?

Only when CTRL+Clicking on the add-on name a new tab is opened, since that is actually an link element.

**Comment by bobsilverberg** [comment]
@wagnerand I think I found the already opened issue: https://github.com/mozilla/addons-frontend/issues/8724

Is this one a duplicate of that?

**Comment by wagnerand** [comment]
@bobsilverberg ah, that's likely it. I assume the add-on card elements are reused in several places, e.g. homepage and search results page?

**Comment by bobsilverberg** [comment]
Yes, they are.

**Comment by wagnerand** [comment]
Alright, thanks for digging that up. Closing this one.
