### ISSUE TITLE
The homepage is not displayed when no addon is added to primary hero shelf

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9795]
Depends on https://github.com/mozilla/addons-server/issues/15811

STR:
When there's no primary hero addon added to the shelf from[ admin](https://addons-internal.stage.mozaws.net/en-US/admin/models/discovery/promotedaddon/?) the homepage shows a 500 error

![Server Error](https://user-images.githubusercontent.com/33448286/96856983-26cba780-1467-11eb-9662-ed1c3f6a157f.png)

This is reproducible on AMO stage - FF82(Win10).

**Comment by bobsilverberg** [comment]
@eviljeff One problem with the response is that it contains both `addon` and `external`, but it really should only ever return one of the two (as per the docs). This complicates things for the logic on the frontend which is looking for the existence of one or the other to determine what to do with the response data. I think that's a bug that should be fixed. Based on this it seems like it should just return `null` for `primary`, and then the docs can be updated to reflect this and frontend will be able to identify a missing primary hero by seeing that `primary` is `null`.

WDYT?

**Comment by eviljeff** [comment]
whatever is best for frontend to consume

**Comment by bobsilverberg** [comment]
Ok, thanks, I'll open an issue on addons-server.

**Comment by ioanarusiczki** [comment]
@bobsilverberg This is fixed on AMO dev - FF83(Win10).  Homepage containing the rest of the shelves is displayed. 

![no primary image](https://user-images.githubusercontent.com/33448286/99957176-e9bd4280-2d8f-11eb-8776-e455ff17c0c6.png)
