### ISSUE TITLE
Collections menu not present on windows 10 firefox

### ISSUE THREAD

**Issue by DimYong** [mozilla/addons-frontend#9797]
### Describe the problem and steps to reproduce it:

The collection menu via this link does not work:
https://support.mozilla.org/en-US/kb/how-use-collections-addonsmozillaorg#w_create-a-collection

It works fine on android but is not present on windows 10. Can this be brought back? It's very useful

**Comment by jvillalobos** [comment]
Which menu are you referring to? If you mean the dropdown from your user with the "View My Collections" option, I can see it on the desktop site.

**Comment by willdurand** [comment]
No answer from OP, closing the issue for now
