### ISSUE TITLE
Merge "amo" and "core" packages

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9804]
This is only be possible after https://github.com/mozilla/addons-frontend/issues/9379. We only have one app in this project so let's remove the `amo` and `core` folders and merge some of the common files together.

For QA: this is a major code change but it shouldn't have any impact on the site.

**Comment by lakshyabatman** [comment]
I'm interested to work on merging the folders.

**Comment by lakshyabatman** [comment]
Mind if you can brief me more regarding this to get me started as soon as possible. Thankyou

**Comment by lakshyabatman** [comment]
Hello, I'm interested to work on this issue as well. Please let me know if it's possible. Thankyou.

**Comment by willdurand** [comment]
No, it's not, sorry.

**Comment by lakshyabatman** [comment]
No problem, thankyou.

**Comment by willdurand** [comment]
You can find issues by looking at the [opened `contrib: welcome` issues](https://github.com/mozilla/addons-frontend/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22).

**Comment by bobsilverberg** [comment]
@willdurand After #9872 lands, we'll be one step closer to being able to do this. I was thinking we might want to continue taking small steps, as opposed to just trying to merge all of the code in one big patch. For example, maybe we can start by moving individual things out of `core` and into `amo`? What do you think of taking that approach?

Also, do you imagine that everything will end up in `amo`, or do you envision doing away with both `amo` and `core` and just having everything live under `src`?

**Comment by willdurand** [comment]
I think we can get rid of both amo and core. We can land incremental patches.

**Comment by willdurand** [comment]
Here is the plan:

1. move `core` sources to `amo` (we need a directory level in `src/` otherwise it breaks our absolute imports)
2. move `core` test files to `amo`
3. move `core` stories to `amo`

I'll file an issue for the `ui` package.

**Comment by ioanarusiczki** [comment]
@willdurand Looks good. Release testing is completed - on AMO stage with FF84(Win).
