### ISSUE TITLE
Review comments about discopane in addons/versions reducers

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9805]
After #9379, we shouldn't mention "discopane" anymore. We do fancy stuff in two reducers and it seems related to discopane. It's not clear what we're doing exactly or why so let's see if we can refactor our code.

**Comment by willdurand** [comment]
See also https://github.com/mozilla/addons-frontend/pull/9803#discussion_r512569155

**Comment by bobsilverberg** [comment]
I'd be happy to take this on if you like, @willdurand, but if you were planning on doing it that's fine too.

**Comment by willdurand** [comment]
> I'd be happy to take this on if you like, @willdurand, but if you were planning on doing it that's fine too.

Yep, no problem.

And FYI: I was going to take a look at https://github.com/mozilla/addons-frontend/issues/9804 but not necessarily right now given that you're landing code there. I'll wait until things get a bit more stable.

**Comment by bobsilverberg** [comment]
Heh, I was going to offer to take that one as well! I'll leave that to you.

**Comment by willdurand** [comment]
> I'd be happy to take this on if you like, @willdurand, but if you were planning on doing it that's fine too.

Ohhh, that's nice! If you want to work on that, no problem and feel free to request reviews from me then!

**Comment by bobsilverberg** [comment]
Ok, will do.

**Comment by AlexandraMoga** [comment]
I did not find regressions caused by this code change.

I've verified that old Firefox versions will display the fallback page when accessing about:addons.
The release tests also did not reveal any frontend issues.

This was verified fixed on stage.
