### ISSUE TITLE
Get rid of the `NODE_APP_INSTANCE` env var requirement

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9807]
The `NODE_APP_INSTANCE` env var is currently required in this project but as soon as we only have a single app, we should try to get rid of it being required.

**Comment by bobsilverberg** [comment]
@willdurand In addition to getting rid of `NODE_APP_INSTANCE`, we can probably get rid of the whole concept of an `app`. That means doing away with the `appName` config value, and also means we won't need separate config files for `*-amo` as we have now. It makes sense to me that we would simply combine the code from all of the `/config/*-amo.js` files into the non `-amo` versions. Do you agree?

Also, do you think it's worth doing all of that in one patch, or would it be better to just get rid of `NODE_APP_INSTANCE` first, and have everything default to an `appName` of `amo`, and then later, in a different patch, get rid of the concept of `app` altogether?

**Comment by willdurand** [comment]
That depends on the size of the final patch. I started doing this to see how far I could go. Merging config files is tricky, especially for things like CSP. I'd start with merging the config files first, and then remove the concept of an `app`.

It could be done in the same PR but I'd like to see at least two different commits.

**Comment by bobsilverberg** [comment]
Yeah, this sounds like a good plan. To keep things simple I think I'll just get rid of `NODE_APP_INSTANCE` in a single patch, defaulting it to `amo`, and get rid of code that is there to deal with multiple apps. Then I'll open follow-ups for other things like merging the config files.

**Comment by AlexandraMoga** [comment]
I believe this issue (and its follow-ups) can be tested by checking for regressions throughout the frontend. So far, I haven't found anything broken on -dev. 

I will give the final results once we complete the release tests on stage.

**Comment by bobsilverberg** [comment]
I agree, there's nothing specific to check, just that nothing is broken. 😄

**Comment by AlexandraMoga** [comment]
There were no issues found on the frontend while running the release tests on stage.
I'm marking this issue as verified fixed.
