### ISSUE TITLE
Show download links instead of install buttons in all versions page

### ISSUE THREAD

**Issue by Rob--W** [mozilla/addons-frontend#9811]
### Describe the problem and steps to reproduce it:

1. Install NoScript (possibly an older version).
2. Visit https://addons.mozilla.org/en-US/firefox/addon/noscript/versions/ and/or
  https://addons.mozilla.org/en-US/firefox/addon/noscript/
3. Try to install an older version, or at least find a "Download file" link (from #4910).

### What happened?
I am not able to install or download an older version. All buttons have changed to "Remove".

I cannot upgrade to the latest version via the addon listing because there is only a "Remove" button.

### What did you expect to happen?
It should be possible to install or download an older version.

### Anything else we should know?

Actually, it is possible to download, by right-clicking on the button and opening it in a new tab/window, because the button is actually a link. This is however not obvious and not a great user experience.

**Comment by willdurand** [comment]
Yes, that all versions page is weird and I never liked all the install buttons everywhere. I think we should only link to xpis, without buttons.

We shouldn't encourage users to install older versions, though, so the download linka should be more than enough.

ping @jvillalobos as it's a product call

**Comment by jvillalobos** [comment]
I agree that installing old versions isn't a core use case so we shouldn't make it easier. I like the idea of changing from buttons to links. We recently [reintroduced the Download File link](https://github.com/mozilla/addons-frontend/issues/4910) on listing pages, so we could reuse something like that.

**Comment by Rob--W** [comment]
> I like the idea of changing from buttons to links. We recently [reintroduced the Download File link](https://github.com/mozilla/addons-frontend/issues/4910) on listing pages, so we could reuse something like that.

For non-Firefox user agents, there is both a button (to download/install Firefox) and an inconspicuous link to the XPI.
In Firefox, there is only a button (which is actually a link that wraps a button).

I think that it's a good idea to turn the button into links for older versions.

**Comment by bobsilverberg** [comment]
I agree with the approach described above, using just text links instead of buttons. What is the priority of this? Should we just add it to `contrib: welcome`, or do you think it's important to fix sometime soon? As discussed, the buttons themselves *are* download links, and this issue has existed since this page was implemented.

**Comment by jvillalobos** [comment]
Tagging it as `contrib: welcome` sounds good to me.

**Comment by SushantAA** [comment]
I want to work on this issue

**Comment by bobsilverberg** [comment]
That's fine, @SushantAA, you can work on this. Please note that this is labelled `contrib: welcome`, not `contrib: good first bug`, so while it is something that can be worked on by a contributor, it is not necessarily a particularly simple or easy issue to work on.

**Comment by SushantAA** [comment]
I didn’t know about contrib: welcome and thought it was for beginners.

**Comment by Creatoon** [comment]
i want to work on this

**Comment by sarthakkundra** [comment]
@bobsilverberg I'd like to take this up seeing it has the appropriate tag. One quick favour can you provide with a screenshot of what is to be changed as I am using Chrome so that'll remove any confusion.

**Comment by bobsilverberg** [comment]
> @bobsilverberg I'd like to take this up seeing it has the appropriate tag. One quick favour can you provide with a screenshot of what is to be changed as I am using Chrome so that'll remove any confusion.

Well, you really should test it on Firefox to verify the changes you make, but here's a screenshot from Firefox showing the buttons we're talking about:

<img width="931" alt="Screen Shot 2021-01-06 at 3 10 01 PM" src="https://user-images.githubusercontent.com/142755/103815469-67cc6480-5031-11eb-94a6-062e22c3170e.png">

It's the buttons that currently say "Remove" which should be removed and replaced with a link to download the file. When you visit the same page with Chrome, you'll see green "Only with Firefox—Get Firefox Now" buttons, with a text link to "Download file" underneath each one. Those are the types of download links that should replace the buttons.

**Comment by sarthakkundra** [comment]
<img width="1440" alt="Screenshot 2021-01-08 at 12 59 38 PM" src="https://user-images.githubusercontent.com/52133994/103986829-72ae0300-51b1-11eb-8367-44e2291bcd1a.png">
@bobsilverberg It says "add to Firefox" .  Am I at the right place? If I am should I go ahead and replace these buttons with links?

**Comment by bobsilverberg** [comment]
Correct. If the add-on is installed, the buttons say "Remove", if it is not installed, they say "Add to Firefox".

**Comment by sarthakkundra** [comment]
Cool @bobsilverberg can you please assign me this issue

**Comment by AlexandraMoga** [comment]
I've verified the All versions page on -dev and these are my results:

- the Add to Firefox/Install Theme/Remove buttons have been replaced with 'Download file' links for older versions
- the Latest version will still display the install button
- in Firefox, Download links trigger an installation - but this has been mentioned several times before and it's the accepted use case
- in other browsers, Download links will download the .xpi

[Firefox]
![image](https://user-images.githubusercontent.com/31961530/115356934-ca063b00-a1c4-11eb-90f6-bc3a3a899bdc.png)


[Other browser]
![image](https://user-images.githubusercontent.com/31961530/115356963-d1c5df80-a1c4-11eb-8542-2938e52cc651.png)

[Mobile - note that when using the responsive design mode in Firefox, issue #10417 is visible]
![image](https://user-images.githubusercontent.com/31961530/115357011-de4a3800-a1c4-11eb-92cb-f665b97f987d.png)

@bobsilverberg As far as I can tell, the only remaining inconsistency appears when a user has an older version installed, but the All versions page will display a 'Remove' button next to the Latest version. I'm not sure if or how we should to address this.

**Comment by bobsilverberg** [comment]
> @bobsilverberg As far as I can tell, the only remaining inconsistency appears when a user has an older version installed, but the All versions page will display a 'Remove' button next to the Latest version. I'm not sure if or how we should to address this.

This is a good point. We felt it made sense to display the install button for the most recent version, but this is a result of doing that. We end up with a "Remove" button displayed beside the most recent version if the add-on is installed, regardless of which version is installed. I think this is probably fine, as if someone really wants to remove the add-on they likely don't care which version is currently installed and therefore being removed, but let's check with product.

@jvillalobos What are your thoughts on this?

**Comment by jvillalobos** [comment]
Yes, they're unlikely to know or care which version they have installed, so I think it's fine to leave that as is.
