### ISSUE TITLE
discovery.addons.allizom.org has failed the web security baseline

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/addons-frontend#9816]
Site https://discovery.addons.allizom.org has failed the web security baseline scan.

The failing tests are:

 Strict-Transport-Security Header Not Set [10035] x 10 
 * https://discovery.addons.allizom.org/en-GB/firefox/discovery/pane/48.0.1/Linux/normal (404 Not Found)
 * https://discovery.addons.allizom.org/robots.txt (404 Not Found)
 * https://discovery.addons.allizom.org/sitemap.xml (404 Not Found)
 * https://discovery.addons.allizom.org/en-GB (404 Not Found)
 * https://discovery.addons.allizom.org/en-GB/firefox (404 Not Found)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=discovery.addons.allizom.org) dashboard.
If you have any questions or concerns please get in contact with secops+web-baseline@mozilla.com

**Comment by arroway** [comment]
This app is about to be decommissioned. It's unreachable per https://bugzilla.mozilla.org/show_bug.cgi?id=1673924, but is still up in prod.
@moz-hwine do you know what's the process there, do we wait for the service to be completely shut down before updating our metadata for the security checks, or is now good enough?

**Comment by willdurand** [comment]
> @moz-hwine do you know what's the process there, do we wait for the service to be completely shut down before updating our metadata for the security checks, or is now good enough?

note that we're going to keep the domain alive to return a 404 (in order to trigger a fallback in old FFs)

**Comment by arroway** [comment]
I updated our metadata, so these endpoints should not be included in our scans anymore.

**Comment by arroway** [comment]
@bobsilverberg yes!
