### ISSUE TITLE
Refactor some code for Fennec, Fenix and iOS

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9819]
This supports #9714 

While working on #9714 I ended up doing quite a bit of refactoring, and the patch became quite large, so I am splitting out some of the refactoring work into this issue. The changes involve code about Fennec, Fenix and iOS.

**Comment by bobsilverberg** [comment]
I'm merging this work into the work for #9714

**Comment by ioanarusiczki** [comment]
@bobsilverberg Could you add some STR for qa? 
Thanks!

**Comment by bobsilverberg** [comment]
Sorry, @ioanarusiczki, this was never fixed, just closed. I have removed the milestone.
