### ISSUE TITLE
discovery.addons.mozilla.org has failed the web security baseline

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/addons-frontend#9821]
Site https://discovery.addons.mozilla.org has failed the web security baseline scan.

The failing tests are:

 Strict-Transport-Security Header Not Set [10035] x 10 
 * https://discovery.addons.mozilla.org/en-GB/firefox/discovery/pane/48.0.1/Linux/normal (404 Not Found)
 * https://discovery.addons.mozilla.org/robots.txt (404 Not Found)
 * https://discovery.addons.mozilla.org/sitemap.xml (404 Not Found)
 * https://discovery.addons.mozilla.org/en-GB (404 Not Found)
 * https://discovery.addons.mozilla.org/en-GB/firefox (404 Not Found)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=discovery.addons.mozilla.org) dashboard.
If you have any questions or concerns please get in contact with secops+web-baseline@mozilla.com

**Comment by diox** [comment]
Dupe of https://github.com/mozilla/addons-frontend/issues/9816

**Comment by moz-hwine** [comment]
The web security baseline for site https://discovery.addons.mozilla.org is still failing, this issue should stay open.
