### ISSUE TITLE
Try to do away with appName

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9840]
After #9807 lands, we will no longer have `NODE_APP_INSTANCE`, but to make the patch for that more manageable, plenty of files still make use of an `appName` which is set to `amo` in `config/default.js`. As there is only one app now, we really shouldn't need this `appName` at all. This issue is about looking at any files that make use of `appName` and trying to see if we can eliminate it entirely from those files.

**Comment by AlexandraMoga** [comment]
@bobsilverberg do you have some STR for verifying this issue or would a general regression be enough?

**Comment by bobsilverberg** [comment]
> @bobsilverberg do you have some STR for verifying this issue or would a general regression be enough?

Yes, a general regression should be enough. Any breakage should be fairly obvious.

**Comment by bobsilverberg** [comment]
@AlexandraMoga I just realized that this is labelled with the wrong milestone. It's not landing this week, so no need to test it just yet. Sorry for the confusion.

**Comment by AlexandraMoga** [comment]
There have been no regressions found during our release testing.
I'm marking this issue as verified fixed on stage.
