### ISSUE TITLE
Restrict add-on detail and versions page for add-ons in specific regions

### ISSUE THREAD

**Issue by diox** [mozilla/addons-frontend#9842]
We need some add-ons to be restricted in some specific regions. 

The client "region" is going to be detected using geoip by nginx (*) and then passed down to addons-frontend nodejs server through a header called `X-Country-Code` containing a 2 letter code following [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). When calling addons-server API for a detail or versions page, addons-frontend will then need to pass that header to the add-on detail/versions API call (this technically doesn't need to be done for client side rendering, because then addons-server would receive the actual client IP and can do the geoip lookup).

Regardless of whether we're on the server side or frontend side, if the API answers with a HTTP 451 status code, then we need to display an error page saying the add-on is not available in this region instead of the normal detail page. Other pages like search or homepage shouldn't be affected.

(*) We may have to change this to use geoip directly ourselves in node but at the moment depending on the results of some experiments ops are running, but at the moment we're working under the assumption it will be handled by nginx, and that the header will always be added by nginx, overwriting whatever clients send.

**Comment by bobsilverberg** [comment]
I believe with the landing of #9843 and #9844 this is now done.

**Comment by AlexandraMoga** [comment]
The issues related to this feature have been marked as verified. I will also mark this parent issue as verified on -dev and stage.
