### ISSUE TITLE
Display a Not Available In This Region Page

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9843]
This supports #9842 

When addons-frontend receives an API response from addons-server with a response code of 451, it should immediately stop processing and display a special page explaning that the content is not available in your region. We can model this after the 404 page, but should get confirmation on the actual text to be displayed from someone.

**Comment by bobsilverberg** [comment]
Here is what the current implementation of this page looks like:

<img width="1416" alt="Screen Shot 2020-11-09 at 3 31 44 PM" src="https://user-images.githubusercontent.com/142755/98593153-bfa05680-22a0-11eb-8c7a-38b6503fdb13.png">

**Comment by bobsilverberg** [comment]
@jvillalobos I'm going to update the header to say "Not available for legal reasons", which is the definition of the 451 status code we are using, but I imagine you might have something better/more official for the text of the page. Ideally we'd have something before this week's push. Thanks!

**Comment by willdurand** [comment]
> @jvillalobos I'm going to update the header to say "Not available for legal reasons", which is the definition of the 451 status code we are using, but I imagine you might have something better/more official for the text of the page. Ideally we'd have something before this week's push. Thanks!

We'd want to be accurat, though, so I think this header sounds good to me

**Comment by AlexandraMoga** [comment]
@bobsilverberg I will verify the 451 error page when I'll be testing https://github.com/mozilla/addons-server/issues/15942 and #9844.

**Comment by AlexandraMoga** [comment]
This issue was verified in #9856
