### ISSUE TITLE
Adjust copy for "Not available in this region" page

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9856]
Following up on https://github.com/mozilla/addons-frontend/issues/9843, here's the copy we decided on.

Header
> That page is not available in your region

Body
> The page you tried to access is not available in your region.
>
> You may be able to find what you’re looking for in one of the available [extensions](url) or [themes](url), or by asking for help on our [community forums](url).

**Comment by willdurand** [comment]
Can we link to the [Transparency Report](https://www.mozilla.org/en-US/about/policy/transparency/) too, since this is relevant?

**Comment by bobsilverberg** [comment]
> Can we link to the [Transparency Report](https://www.mozilla.org/en-US/about/policy/transparency/) too, since this is relevant?

@jvillalobos?

**Comment by bobsilverberg** [comment]
Here's what the new page looks like (without the link suggested by Will):

<img width="1061" alt="Screen Shot 2020-11-12 at 2 54 56 PM" src="https://user-images.githubusercontent.com/142755/98989442-1dc67700-24f7-11eb-89f2-0fe87c156af3.png">

**Comment by bobsilverberg** [comment]
@jvillalobos Just checking in again for a response to the link to the Transparency page question. It sounded like the answer is "no" on Slack, but I'd like to document the decision here as well.

**Comment by jvillalobos** [comment]
We're discussing if anything should be changed to the proposed copy, but that shouldn't block landing it in its current form.

**Comment by AlexandraMoga** [comment]
The add-on detail and its related pages (reviews, license, versions, eula) will display the "Not available in your region" page when accessed from an excluded country:

![image](https://user-images.githubusercontent.com/31961530/99394978-77101b00-28e8-11eb-83c9-3b6e449a9def.png)

This issue is verified fixed on -dev.
