### ISSUE TITLE
Remove emotion package

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9857]
Prompted by https://github.com/mozilla/addons-frontend/pull/9853, I was looking to see what we use the `emotion` package for, and I cannot find any references to it. Locally, if I remove it I don't seem to have any problems. The build doesn't break, the site works fine, and Storybook works fine.

@willdurand Do you think we can remove it?

**Comment by willdurand** [comment]
> @willdurand Do you think we can remove it?

That will be answered by the answer to this question: https://github.com/mozilla/addons-frontend/pull/9853#issuecomment-726254902

I am pretty sure a peer dependency was involved, hence the need for this package to be present in our `package.json` without being actually required in our code.
