### ISSUE TITLE
Recommended themes appear compatible on Fenix

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9860]
Follow up for #9714 

### Describe the problem and steps to reproduce it:
1. Load AMO on an Android device using Fenix
2. Open a recommended theme's detail page - see https://addons.mozilla.org/en-US/android/addon/foxx-theme/
3. Notice the Install button and the compatibility message

### What happened?
The Install Theme button is enabled and we show the following compatibility message: "You can install this add-on in the Add-ons Manager. Learn more about add-ons for Android."

### What did you expect to happen?
There shouldn't be any indication that the theme can be installed on Fenix, since themes are not compatible yet

### Anything else we should know?
The issue does not apply to non-recommended themes

![image](https://user-images.githubusercontent.com/31961530/99059286-0b0b7b00-25a7-11eb-853e-4b05866cdf47.png)

**Comment by bobsilverberg** [comment]
@jvillalobos What about language packs and dictionaries? Should the rule be "treat themes as incompatible", or "treat any add-on with a type other than `extension` as incompatible"?

**Comment by jvillalobos** [comment]
Treat any add-on with a type other than extension as incompatible.

**Comment by AlexandraMoga** [comment]
Recommended themes on Fenix are displayed as incompatible now (the same as non-recommended themes):


![image](https://user-images.githubusercontent.com/31961530/99521304-ec3d2800-299c-11eb-81be-3a352c56c6bb.png)

As note: Fennec users will have the same view, meaning that they won't be able to install themes either. 

This issue is verified fixed on stage.
