### ISSUE TITLE
Show more Recommended add-ons in the Android homepage

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9863]
Following up on https://github.com/mozilla/addons-frontend/issues/9716, I'd like the homepage to show up to 10 Recommended extensions, so it doesn't appear too empty.

For QA:
In addition to more add-ons appearing in the Recommended shelf on the mobile home page, when visiting the mobile home page only the two required API requests will be made, as opposed to the large number needed for the desktop home page.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I verified on AMO dev and AMO stage:
- the layout of the shelf has changed meaning a number of 10 addons are available on the homepage.

- See more recommended extensions URL redirects to https://addons.allizom.org/en-US/android/search/?promoted=recommended&sort=random&type=extension and it is available on the homepage when at least 10 addons are promoted for android. 

![android recommended](https://user-images.githubusercontent.com/33448286/100892852-6d2f1000-34c3-11eb-9b9c-c9df5209c8ef.gif)


- the 2 API calls are available when visiting the homepage:
https://addons.allizom.org/api/v4/hero/?lang=en-US and
https://addons.allizom.org/api/v4/addons/search/?app=android&appversion=83.0&page_size=10&promoted=recommended&sort=random&type=extension&lang=en-US&wrap_outgoing_links=true

- mobile small device layout looks good - verified with Android 8.0
