### ISSUE TITLE
Search query is not trimmed

### ISSUE THREAD

**Issue by Sparsh1212** [mozilla/addons-frontend#9866]
### Describe the problem and steps to reproduce it:
Case1: Leave the search field blank and press the enter Key.
We get xyz no. of search results.
Case2: Now just enter 1-2 spaces instead of a blank query and then press the enter Key.
Now we get 0 search results.

Case1:
![image](https://user-images.githubusercontent.com/55937724/99143757-04076a00-2686-11eb-96c7-d3266cb33df9.png)
Case2:
![image](https://user-images.githubusercontent.com/55937724/99143758-0b2e7800-2686-11eb-8d35-fe1cf7e002c6.png)

### What happened?
The search results of case1 and case2 were different.
### What did you expect to happen?
The search results should be the same for case1 and case2.

**Comment by LordReigns** [comment]
Can I try to work on this issue?

**Comment by Sparsh1212** [comment]
@caitmuenster  If this isn't the expected behaviour, I will like to work on this issue. Please assign this to me.

**Comment by caitmuenster** [comment]
Hi @Sparsh1212, we would accept a patch for this. 

@LordReigns, thanks for your interest! Sparsh is going to be working on this issue, but you are welcome to work on one of our other good-first-bugs! Please take a look at our [onboarding information](https://wiki.mozilla.org/Add-ons/Contribute/Code#Improve_addons.mozilla.org_.28AMO.29), which includes links to our available good-first-bugs. :)

**Comment by Sparsh1212** [comment]
@caitmuenster I have initiated a patch for this. Please assign a mentor for reviewing the pr.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 
This issue is no longer reproducible on -dev with FF84(Win10).

![blank search results](https://user-images.githubusercontent.com/33448286/103779952-0dd19c00-503d-11eb-9e28-827f46759959.gif)
