### ISSUE TITLE
Searching for mobile add-ons should only display compatible results

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-frontend#9893]
Searching for mobile add-ons on AMO will currently display add-ons based on their Fennec compatibility, which is no longer relevant. The new source of truth is the Recommended list, and it's likely to stay that way for a long time.

A couple of solutions that come to mind:
* Have the server return only Recommended results for Android.
* Have the front-end force the Recommended filter for all searches.
* Reset all mobile compatibility data so it matches the current Recommended list.

**Comment by ioanarusiczki** [comment]
@bobsilverberg What I've noticed so far on AMO dev with Fenix:

- blank search will return results composed of the addons available in the recommend shelf and static themes which I think they've been added into a collection of recommended themes.  I don't know if themes are expected to appear right now. 
- blank search displays the Badging but no matter what badge I choose the results are the same: all recommended add-ons and themes.  I don't know if that's expected or if this filter should be hidden on android. 
- search queries seem to respond as expected, but I'm going to do some more testing around them. Also, the recommended static themes mentioned above are returned when making search queries. 

Example: 

![themes](https://user-images.githubusercontent.com/33448286/101365831-f0c67380-38ac-11eb-8a9b-ab560d6b2806.png)

**Comment by bobsilverberg** [comment]
Thanks @ioanarusiczki. We should be excluding themes as well on Android. That's something I missed when implementing this. Can you please open a separate issue for that? 

As for the "Badging" filter, it's true that it won't really have an effect currently as we are only ever returning Recommended add-ons for Android. We could remove it for the Android site, or just leave it in case we need it later. @jvillalobos So you have an opinion on this?

**Comment by jvillalobos** [comment]
If changing the filter doesn't have any effect on the results, I would favor hiding it.

**Comment by ioanarusiczki** [comment]
@jvillalobos @bobsilverberg 
Themes removal https://github.com/mozilla/addons-frontend/issues/9903
The filter removal https://github.com/mozilla/addons-frontend/issues/9904

Same question for the themes as type - filters have Add-on Type: All, Extension, Theme. Once static themes are removed selecting Theme won't return results. Is that alright ?

**Comment by bobsilverberg** [comment]
> @jvillalobos @bobsilverberg
> Themes removal #9903
> The filter removal #9904
> 
> Same question for the themes as type - filters have Add-on Type: All, Extension, Theme. Once static themes are removed selecting Theme won't return results. Is that alright ?

I think if we're planning on hiding the "Badging" filter on Android, it would make sense to also hide the "Type" filter. I'll update #9904 to cover that as well.
