### ISSUE TITLE
Re-enable the badging and/or add-on type filters for search on Android

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9905]
This is a follow-up to #9904.

We are removing the badging and add-on type filters from the Search form on Android because currently we only ever return Recommended extensions on Android, so these filters will do nothing.

If we change this behaviour in the future, we will want to re-enable these filters, which is why I am opening this issue.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/ADDFRNT-181)

**Comment by sarthakkundra** [comment]
Hi @bobsilverberg I'm a new contributor here. Do you mind explaining the issue a bit thoroughly and what is exactly expected from the fix?

**Comment by bobsilverberg** [comment]
@sarthakkundra Thanks for your interest, but this is not an issue that needs to be addressed. It's a bookmark for something we *may* have to do at some point in the future. I suggest you only look at issues that are marked with "contrib: welcome" when looking for issues to work on.

**Comment by sarthakkundra** [comment]
Sure @bobsilverberg thanks for clarifying.

**Comment by willdurand** [comment]
That has been fixed in https://github.com/mozilla/addons-frontend/pull/12400

**Comment by KevinMind** [comment]
Old Jira Ticket: https://mozilla-hub.atlassian.net/browse/ADDFRNT-181
