### ISSUE TITLE
Handle user-entered urls in the API being an object containing both wrapped and raw urls in api/v5

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons-frontend#9911]
(needs better issue title 😬 )
The changes in the fix for mozilla/addons-server#11206 are breaking in api/v5 and will require some changes to the API handling code (reducer? saga?)

**Comment by bobsilverberg** [comment]
Thanks for opening this @eviljeff. Do you mind opening a similar one for addons-code-manager as well?

**Comment by eviljeff** [comment]
Note: (oddly) we've never supported wrapping the account profile homepage property with outgoing, and the addons-server commit doesn't change this.  (We perhaps _should_, but that would be a future issue/problem)

**Comment by ioanarusiczki** [comment]
@eviljeff 
I'm thinking that I should check that layout of the detail pages for the addons from https://github.com/mozilla/addons-server/issues/11206#issuecomment-756809828 is not broken. 

If there's anything else please let me know.

**Comment by eviljeff** [comment]
> 
> 
> @eviljeff
> I'm thinking that I should check that layout of the detail pages for the addons from [mozilla/addons-server#11206 (comment)](https://github.com/mozilla/addons-server/issues/11206#issuecomment-756809828) is not broken.
> 
> If there's anything else please let me know.

the changes are:
- on the addon detail page
  - contributions
  - homepage
  - support_url
- on a blocklist block page
  - the block request link
- the hero shelves on the homepage
  - the CTA links ("get the addon", "more", etc).  Note these specifically _don't_ use outgoing, even for external links.

There shouldn't be any changes noticeable vs. prod - what was wrapped in outgoing before should still be wrapped in outgoing; what was an unwrapped url should still be the same.

**Comment by ioanarusiczki** [comment]
@eviljeff I verified on AMO dev - FF84(Win10) and I did not find issues (differences). Also the URLs redirect as expected.
