### ISSUE TITLE
storybook deployment is currently broken

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9927]
It's not clear why given that we're using the same config than addons-code-manager but storybook deployment fails for this project: https://app.circleci.com/pipelines/github/mozilla/addons-frontend/3324/workflows/0b8d0dea-a34e-4041-a75a-5397205c50c2/jobs/24197

**Comment by willdurand** [comment]
It works now, there was an extra space in the env variable on circle ci.

**Comment by ioanarusiczki** [comment]
@willdurand In case qa can check this issue, please add some str.
Thanks!
