### ISSUE TITLE
Use husky and lint-staged to implement a pre-commit hook

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9939]
[`husky`](https://www.npmjs.com/package/husky) and [`lint-staged`](https://www.npmjs.com/package/lint-staged) can be used in combination to manage a pre-commit hook which will work for anyone who installs the site locally. We can automatically run `prettier`, `eslint`, `stylelint`, and `flow` on every commit, which will help avoid linting errors in commits, and will help users who do not have `prettier` configured to run automatically in their IDE.

Note that the `eslint` step can take a few seconds when there are a large number of files being added to a commit. The time it takes is proportional to the number of files being checked, but I feel like it's worth waiting a few seconds every now and then to have these automatic checks in place.

If we decide this works well, we can add it to addons-code-manager and addons-server as well.

**Comment by ioanarusiczki** [comment]
@bobsilverberg In case qa can test for this issue please add some str.
Thanks!

**Comment by bobsilverberg** [comment]
I don't think we need QA testing for this.
