### ISSUE TITLE
Add a test for the new trim functionality in AutoSearchInput

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9954]
Some trimming was added into src/amo/components/AutoSearchInput/index.js for #9866, but a test was not added to verify the new behaviour. This issue is about adding such a test.

@Sparsh1212 has volunteered to take this on, as they did with #9866. If you can comment on this issue, I can assign it to you.

**Comment by Sparsh1212** [comment]
Please assign this to me.

**Comment by willdurand** [comment]
I'd make it a p2 because we shouldn't land code without a test case.

**Comment by bobsilverberg** [comment]
@Sparsh1212 This is something we'd like to address soon. Do you think you'll have time to get to it in the next week or so?

**Comment by Sparsh1212** [comment]
@bobsilverberg I am actually unable to find time due to some urgent work. Please assign this to someone else, if its urgent.

**Comment by AlexandraMoga** [comment]
Should this be a 'qa:not needed'?

**Comment by bobsilverberg** [comment]
> Should this be a 'qa:not needed'?

Yes, sorry @AlexandraMoga.
