### ISSUE TITLE
Use alphabetical order for platform identifiers in per-version addon downloads

### ISSUE THREAD

**Issue by polyzen** [mozilla/addons-frontend#996]
https://addons.mozilla.org/firefox/downloads/file/492123/ublock_origin-1.9.2-fx+sm+tb+an.xpi

The order of the "platform identifiers" change _every_ release. If you remove anything from the last slash onward, it downloads the latest version.

Many addons are packaged for global installation in Arch Linux (eg. see [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=firefox-ublock-origin)). If we source from AMO, we have to match the new, random order every release, which is quite monotonous.

If they could be made to follow alphabetical (or any) order going forward, that would be extremely appreciated.

Edit: Well, apparently not [_every_](https://addons.mozilla.org/firefox/downloads/file/492500/ublock_origin-1.9.4-fx+sm+tb+an.xpi?src=version-history) release.

**Comment by kumar303** [comment]
Hi, thanks for filing a bug report about this. Technically, this would fall under the backend service so I moved it to https://github.com/mozilla/addons-server/issues/3358 for easier triaging (although we are considering moving to a monorepo :)).

**Comment by polyzen** [comment]
Thank you very much. Right after filing the issue, I figured it was in the
wrong place. :p
