### ISSUE TITLE
Sponsored shelf is not displayed correctly when loading the homepage using the FF logo

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#9961]
STR:
1.  Load AMO dev -homepage and navigate away from it
2. Click the logo on the left side of the screen
3. Observe the Sponsored shelf

Expected result:
Addons are displayed.

Actual result:
Addons are in a continuous loading state. A page refresh will display them again.

Notes:
This behavior is specific for AMO dev - FF84(Win10), (this might be related https://github.com/mozilla/addons-frontend/issues/9953)
There's been an issue filed for similar behavior on AMO stage. https://github.com/mozilla/addons-server/issues/16267 in that case the API returns a 500, but this is not the case on AMO dev. 

![sponsored shelf error](https://user-images.githubusercontent.com/33448286/103779042-d9a9ab80-503b-11eb-99ce-677e0fe95ac4.gif)

**Comment by bobsilverberg** [comment]
@ioanarusiczki This is fixed on dev and I also cherry-picked the fix so it should be on stage soon as well.

**Comment by ioanarusiczki** [comment]
@bobsilverberg I can confirm that it's not reproducible on -dev.

-AMO stage verification is blocked by https://github.com/mozilla/addons-server/issues/16267. 

When repeating this scenario I ran twice into a 500 (it's intermittent). Best case scenario is this:

![behavior on stage](https://user-images.githubusercontent.com/33448286/103869407-ecbb8a80-50d2-11eb-86b5-7e37f89afa1e.gif)

**Comment by ioanarusiczki** [comment]
@bobsilverberg as expected, the 500 errors are only specific to -stage. 
AMO dev and AMO prod don't have issues. 

Verified with FF84(Win10).
