### ISSUE TITLE
Cannot open collections

### ISSUE THREAD

**Issue by ameeno** [mozilla/addons-frontend#9965]
### What happened?
Can't open collections
### What did you expect to happen?
Collections open properly
### Anything else we should know?
Server error after login.
And choosing view my collections. I have tried multiple browsers

**Comment by eviljeff** [comment]
@ameeno can you provide some details of your account?  e.g. user profile id* or email.

*https://addons.mozilla.org/firefox/user/<user-id>/

Also, can try it again today and let us know the time you tried it so we can look for the timestamp in our logs.

**Comment by ameeno** [comment]
Hiya. Thanks for the message. My uid is 7227658 and I tried just now multiple times it's 11:54-11:55 gmt

**Comment by ameeno** [comment]
Ps I have used the file issue options and I have been trying this a few times over the last few days.

**Comment by eviljeff** [comment]
Can you confirm the page (the https url) you're on when you get the error?  And what version of Firefox you tried with?

**Comment by eviljeff** [comment]
For what it's worth, you only appear to have a single collection, and it's empty.

**Comment by ameeno** [comment]
Hello, @eviljeff I have tried numerous browsers and ff/chrome versions on mac m1 android windows pc and ubuntu.


Thanks for notifying me about the empty collection. The thing is I wanted to build up my collections to enable xpi testing of my ff extension on firefox nightly android.

The route to do this is via a collection of addons.

However, my collections page will not load ever.

So I am glad you found my profile.

Btw I have tried variants of en_GB and en_US ur, and click on the My Collections link on the logged profile on addons.firefox.com.

The exact URL that shows me an error is:

https://addons.mozilla.org/en-US/firefox/collections/
or https://addons.mozilla.org/en-GB/firefox/collections/


I appreciate my collections are currently empty. Perhaps you can try nuking my empty collections to start again? (Please don't delete my profile or uploaded extension though, as I want it to stay, just the collections bit.

I am happy to start building up collections again from scratch!


Thanks in advance for all your assistance!

**Comment by eviljeff** [comment]
Hi, 
we've been investigating the problem and we're pretty certain it's due to some old data (the empty collection is from 2013, probably auto-created when you created your AMO account the first time) that's now considered invalid.  We're still deciding on the best fix and we'll update the issue when we've sorted out your profile,
thanks.

**Comment by eviljeff** [comment]
@ameeno we've deleted the errant empty collection, so you should be able to access your my collections page and create new collections as you need to now.

**Comment by ameeno** [comment]
hi, thanks. yes i can connect and create a collection now. thanks for all your help 👯
