### ISSUE TITLE
Remove the UI tests

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons-frontend#9980]

**Comment by willdurand** [comment]
The new plan is to actually remove those tests from this repo: https://github.com/mozilla/addons-frontend/pull/9985

**Comment by jrbenny35** [comment]
> The new plan is to actually remove those tests from this repo: #9985

Why is this the new plan?

**Comment by willdurand** [comment]
@jrbenny35 @krupa hey, we're going to remove the "frontend" ui-tests in this repo. It looks like there is a new repo with integration tests and the test suite in this repo is very flaky and not very useful to us. It would catch things we would catch anyway (or would be caught by QA on -dev). We'll keep the smoke tests though (as they are useful to ensure we ship Docker images that work).

**Comment by willdurand** [comment]
> Why is this the new plan?

I was writing a comment to let you know about it. The job for this test suite has been failing for weeks or months now and no one in our team has bandwidth to maintain it. I noticed you didn't have lots of time too, which is perfectly okay. I attempted to rescue them last week but it went anywhere so we think not having those tests would be a good trade-off for everyone. We all browse -dev daily so we would notice obvious issues that are "encoded" in the scenerios of this uitests suite.

**Comment by willdurand** [comment]
In addition to what I wrote above, we think it's the best way to go since it's not a good use of Benny's time to continue to maintain those test as they have less value than before. Our team is not really able to maintain the tests either.

Our unit test suite is very comprehensive, we rely on -dev for developing and our team is smaller so it's easier to land breaking changes in the server repo (the same dev will likely update the frontend as well). We don't really land breaking changes these days anyway.

**Comment by willdurand** [comment]
Thank you for your excellent work @jrbenny35!
