### ISSUE TITLE
Add --no-verify option to run-l10n-extraction script

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9989]
The new git commit hook is being triggered when the `run-l10n-extraction` script is run to generate locales, and because of the large number of files it's not very fast. We should update the script to add `--no-verify` when it does a `git commit`.

**Comment by willdurand** [comment]
One can probably `export HUSKY_SKIP_HOOKS=1` before running the script in the meantime.

**Comment by ioanarusiczki** [comment]
@bobsilverberg If qa can verify this issue please add some str or mark it qa not needed.
Thanks!
