### ISSUE TITLE
The Add to collection list from add-on details shows a blank space for collections with no name

### ISSUE THREAD

**Issue by AlexandraMoga** [mozilla/addons-frontend#9994]
Follow up for #9977 

### Describe the problem and steps to reproduce it:
1. Log in to AMO with an account that has a few collections with a blank name
2. Open an add-on details page and scroll down to the Add to collection section
3. Click on Select a collection to open the available collections list 

### What happened?
The list displays a blank space for the collections that have no name set

### What did you expect to happen?
The list should display the blank name collections with a "(no name)", same as in My Collections list

![image](https://user-images.githubusercontent.com/31961530/104598160-eb640200-567e-11eb-9a88-5fa80c887cb1.png)

**Comment by bobsilverberg** [comment]
Note that the notice that currently displays when adding to a collection also shows a blank for the name of a collection with a missing name. This will be fixed in the patch for this issue as well, and the notice will also say "(no name)".

**Comment by AlexandraMoga** [comment]
This issue is verified fixed on -dev:
![image](https://user-images.githubusercontent.com/31961530/105046275-90148400-5a71-11eb-9194-224f724cd4b4.png)
