### ISSUE TITLE
Consolidate API requests for the home page shelves into a single API call

### ISSUE THREAD

**Issue by bobsilverberg** [mozilla/addons-frontend#9996]
Now that we have the [homepage shelves endpoint](https://addons-server.readthedocs.io/en/latest/topics/api/shelves.html#homepage-shelves), and with the addition of https://github.com/mozilla/addons-server/issues/16309, there is a single API call that should be able to deliver the contents of all the homepage shelves, as well as the primary and secondary hero elements.

To improve performance of the homepage, we should update it to call this single endpoint, rather than the large number of API calls it is currently making. This will also enable us to make use of the shelves admin that @xlisachan developed.

This will likely be implemented in a few patches, so additional issues will be filed and this issue can be treated as a tracking issue for the endeavour.

**Comment by bobsilverberg** [comment]
@jvillalobos | @devaneymoz When an admin is defining a homepage shelf, they can optionally provide a footer pathname, which will override the default. This will be the destination for the link on the shelf that usually says "See more {shelf type}". We can build a default link for collections and for shelves based on search criteria, but there is also an option to override this.

What sorts of values do you think an admin would use to override the default? Will they always be internal links (e.g., a link to a different collection), or might they be external links? For context, the way the code is currently structured, it doesn't support external links. In order to support that we'd need some extra code, so we wanted to check to see if that's something that is needed now, or ever.

**Comment by jvillalobos** [comment]
I think the most likely targets will be posts in the new editorial area or collections, so it should be okay not to support external URLs for now.

**Comment by ioanarusiczki** [comment]
@bobsilverberg Testing is in progress, I'm going to add my test results on Monday morning after I finish because I did not cover the primary/secondary hero shelves yet.

**Comment by ioanarusiczki** [comment]
@bobsilverberg 

Adding shelves using the module worked for me, I did not test with mixed collections (addons and themes) because I don't think it's in scope. Adding a custom number of extensions or themes worked for me. 

 Here are my observations: 

Frontend:
1. UX - as "Title" and "Footer text" fields from the [shelfmodule](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/shelfmodule/) are not limited to a number of chars, at 100 chars added for both:

![100 chars](https://user-images.githubusercontent.com/33448286/114384010-dbcd5a00-9b96-11eb-80e9-4cc2c8417a3d.png)

This is at 50 chars in both fields when I resize the screen:

![resize screen](https://user-images.githubusercontent.com/33448286/114384091-f4d60b00-9b96-11eb-9d2b-37f93bb7d105.gif)

2. I've noticed that "Footer pathname" supports external URLs too. The pages are opened into the same tab - these URLs into the secondary hero shelf have a different behavior - the pages are opened into a new tab. 

On django side:

3. "Footer pathname" field from the shelfmodule has an issue which is also reproducible with "Cta URL" field from secondary hero shelf . If I try to add the about or review guide pages it will result into a 404. Same for dev hub pages. For example: I add "about" -> frontend generated this URL https://addons-dev.allizom.org/en-US/firefox/about. If I use the entire URL "https://addons-dev.allizom.org/en-US/about", frontend will generate https://addons-dev.allizom.org/en-US/firefox/en-US/about which results again into a 404. 

4. Shelfmodule "Footer text" and "Footer pathname" fields are independent meaning that the module won't throw a warning if only one of them is defined, unlike the secondary hero module which requires both "Cta url" and "Cta text" to be defined.

5. I enabled multiple shelves while testing in the [homepageshelf](https://addons-internal.dev.mozaws.net/en-US/admin/models/discovery/homepageshelves/) module. Then I tried to switch places for 2 shelves, for example, I want "Recommended themes" from position 1 to be 0 but the position is taken by "Recommended extensions" shelf which is also enabled. To do that I must: disable both shelves and save, add 0 for "Recommended themes", add 1 to "Recommeded extensions" enable and save. So this would be the method, because if I just switch the positions for 2 enabled shelves and try to save, I receive the error: "Shelf management with this Enabled and Position already exists."

**Comment by xlisachan** [comment]
@ioanarusiczki - thank you for the feedback!

@bobsilverberg @eviljeff - please see below.

> 1. UX - as "Title" and "Footer text" fields from the shelfmodule are not limited to a number of chars, at 100 chars added for both:
The character limit for both fields is currently 200 in `models.py`. The longest shelf title that is currently live is "Recommended password managers" which is 29 characters long (38-character footer text), which has no overlap at the 768x1024 (iPad) setting - I can force an overlap when the screen width is at 728 though. While I don't believe the admin would set a shelf title that is 100+ characters long, please let me know if I should proceed to decrease the limit of both fields to 40 characters to prevent overlap.

> 2. I've noticed that "Footer pathname" supports external URLs too. The pages are opened into the same tab - these URLs into the secondary hero shelf have a different behavior - the pages are opened into a new tab.
I can fix this - I believe it's just adding `target: '_blank'` to `footerLink`.

> 3. "Footer pathname" field from the shelfmodule has an issue which is also reproducible with "Cta URL" field from secondary hero shelf . If I try to add the about or review guide pages it will result into a 404. Same for dev hub pages. For example: I add "about" -> frontend generated this URL https://addons-dev.allizom.org/en-US/firefox/about. If I use the entire URL "https://addons-dev.allizom.org/en-US/about", frontend will generate https://addons-dev.allizom.org/en-US/firefox/en-US/about which results again into a 404.
TBH I am not sure how to quickly resolve this, but I can look into it.

> 4. Shelfmodule "Footer text" and "Footer pathname" fields are independent meaning that the module won't throw a warning if only one of them is defined, unlike the secondary hero module which requires both "Cta url" and "Cta text" to be defined.
Please let me know if you'd like me to proceed with editing the shelves `models.py` to include a class similar to `CTACheckMixin` used in the hero `models.py` (line 218).

> 5. I enabled multiple shelves while testing in the homepageshelf module. Then I tried to switch places for 2 shelves, for example, I want "Recommended themes" from position 1 to be 0 but the position is taken by "Recommended extensions" shelf which is also enabled. To do that I must: disable both shelves and save, add 0 for "Recommended themes", add 1 to "Recommeded extensions" enable and save. So this would be the method, because if I just switch the positions for 2 enabled shelves and try to save, I receive the error: "Shelf management with this Enabled and Position already exists."
A unique constraint was added to prevent shelves from occupying the same position when enabled [#15309](https://github.com/mozilla/addons-server/issues/15309). I believe another approach was to reorder the shelves with positions that have not been saved. I'll look into whether there is a better way to resolve these two issues.

**Comment by eviljeff** [comment]
it's difficult to deal with many different problems in the same issue - please split out follow-ups into their own issues - anything related to the models/api/admin in addons-server.

> UX - as "Title" and "Footer text" fields from the shelfmodule are not limited to a number of chars, at 100 chars added for both:

I'd treat this as an addons-frontend issue first of all, to decide what the maximum text length the UI should support (some languages are much longer than others), and how longer text should be handled (wrapping seems a lot more desirable than rendering the text on top of each other!).

**Comment by bobsilverberg** [comment]
> @ioanarusiczki - thank you for the feedback!
> 
> @bobsilverberg @eviljeff - please see below.
> 
> > 1. UX - as "Title" and "Footer text" fields from the shelfmodule are not limited to a number of chars, at 100 chars added for both:
> 
> The character limit for both fields is currently 200 in `models.py`. The longest shelf title that is currently live is "Recommended password managers" which is 29 characters long (38-character footer text), which has no overlap at the 768x1024 (iPad) setting - I can force an overlap when the screen width is at 728 though. While I don't believe the admin would set a shelf title that is 100+ characters long, please let me know if I should proceed to decrease the limit of both fields to 40 characters to prevent overlap.
> 

I agree with @eviljeff that we should probably try to handle this on the frontend by wrapping the text, but I also recall an issue from awhile back where we had trouble getting that to work. I think it's also reasonable to add a character limit to the admin, but we need to decide what that should be. We should get feedback from @devaneymoz on that. @xlisachan can you file 2 issues for this, one on frontend and one on server? I don't think this is a serious issue right now, as we have control on what these values are, and they shouldn't need to be particularly long.

> > 1. I've noticed that "Footer pathname" supports external URLs too. The pages are opened into the same tab - these URLs into the secondary hero shelf have a different behavior - the pages are opened into a new tab.
> 
> I can fix this - I believe it's just adding `footerLinkProps.target = '_blank';` to `if (footerLink.href) ` in the `LandingAddonsCard` component.
> 

I agree we should fix this. Can you file a separate issue for that?

> > 1. "Footer pathname" field from the shelfmodule has an issue which is also reproducible with "Cta URL" field from secondary hero shelf . If I try to add the about or review guide pages it will result into a 404. Same for dev hub pages. For example: I add "about" -> frontend generated this URL [addons-dev.allizom.org/en-US/firefox/about](https://addons-dev.allizom.org/en-US/firefox/about). If I use the entire URL "[addons-dev.allizom.org/en-US/about](https://addons-dev.allizom.org/en-US/about)", frontend will generate [addons-dev.allizom.org/en-US/firefox/en-US/about](https://addons-dev.allizom.org/en-US/firefox/en-US/about) which results again into a 404.
> 
> TBH I am not sure how to quickly resolve this, but I can look into it.

I don't think this is an issue. There are a few special URLs that don't follow the rules for `/lang/clientApp/`, but I don't see any reason why we'd need to link to any of these in a shelf footer.

> 
> > 1. Shelfmodule "Footer text" and "Footer pathname" fields are independent meaning that the module won't throw a warning if only one of them is defined, unlike the secondary hero module which requires both "Cta url" and "Cta text" to be defined.
> 
> Please let me know if you'd like me to proceed with editing the shelves `models.py` to include a class similar to `CTACheckMixin` used in the hero `models.py` (line 218).
>

This isn't an issue either. It's perfectly valid to override one of those without overriding the other, so we don't want this limitation in place.
 
> > 1. I enabled multiple shelves while testing in the homepageshelf module. Then I tried to switch places for 2 shelves, for example, I want "Recommended themes" from position 1 to be 0 but the position is taken by "Recommended extensions" shelf which is also enabled. To do that I must: disable both shelves and save, add 0 for "Recommended themes", add 1 to "Recommeded extensions" enable and save. So this would be the method, because if I just switch the positions for 2 enabled shelves and try to save, I receive the error: "Shelf management with this Enabled and Position already exists."
> 
> A unique constraint was added to prevent shelves from occupying the same position when enabled [(#15309)](https://github.com/mozilla/addons-server/issues/15309). I believe another approach was to reorder the shelves with positions that have not been saved. I'll look into whether there is a better way to resolve these two issues.

This is a known limitation and I don't think it's worth spending the time trying to figure out another way around.
